### ISSUE TITLE
Gzip performance

### ISSUE THREAD

**Issue by bobrik** [moby/moby#10181]
This is how `perf report` looks for `docker push`.

![perf](https://pbs.twimg.com/media/B7tB3BeIgAAUQkI.png:large)

Looks like `compress/gzip` in golang is quite slow. To check this I write `gzip` and `gunzip` that can work with `compress/gzip` and `code.google.com/p/vitess/go/cgzip`.

`gzip.go`:

``` go
package main

import (
    "compress/gzip"
    "code.google.com/p/vitess/go/cgzip"
    "flag"
    "io"
    "log"
    "os"
)

func main() {
    l := flag.Int("l", -1, "compression level")
    c := flag.Bool("c", false, "use cgzip")
    flag.Parse()

    var w io.Writer
    var err error

    if *c {
        w, err = cgzip.NewWriterLevel(os.Stdout, *l)
    } else {
        w, err = gzip.NewWriterLevel(os.Stdout, *l)
    }

    if err != nil {
        log.Fatal(err)
    }

    io.Copy(w, os.Stdin)
}
```

`gunzip.go`:

``` go
package main

import (
    "compress/gzip"
    "code.google.com/p/vitess/go/cgzip"
    "os"
    "io"
    "log"
    "flag"
)

func main() {
    c := flag.Bool("c", false, "use cgzip")
    flag.Parse()

    var r io.Reader
    var err error

    if *c {
        r, err = cgzip.NewReader(os.Stdin)
    } else {
        r, err = gzip.NewReader(os.Stdin)
    }

    if err != nil {
        log.Fatal(err)
    }

    io.Copy(os.Stdout, r)
}
```

I have test layer that is 521mb in tar and 66mb in gzipped tar with default compression level. This is real image and final layer of our production image. Now it takes 90s+ to push 2 layers to the registry and this is mostly CPU-bound issue.

Below my tests on on my mbp (core i5 with ssd, so it's not io bound). I ran every command twice and picked best result.

Gunzip:

| cmd | time | slowdown |
| --- | --- | --- |
| `time cat layer.tar.gz | gunzip > /dev/null` | 0m1.041s | baseline |
| `time cat layer.tar.gz | ./bin/gunzip > /dev/null` | 0m4.596s | 4.41x |
| `time cat layer.tar.gz | ./bin/gunzip -c > /dev/null` | 0m1.134s | 1.08x |

Gzip:

| cmd | time | slowdown |
| --- | --- | --- |
| `time cat layer.tar | gzip -c > /dev/null` | 0m12.567s | baseline |
| `time cat layer.tar | ./bin/gzip > /dev/null` | 0m25.794s | 2.05x |
| `time cat layer.tar | ./bin/gzip -c > /dev/null` | 0m12.854s | 1.02x |

Clearly current performance is far from perfect.

This issue is related to #7291 where comments are restricted to collaborators. If docker migrates to `cgzip` then #9060 is going to improve too.

cc @unclejack

**Comment by unclejack** [comment]
@bobrik We can only switch to cgzip for pushing right now. cgzip was running into problems when decompressing layers produced by the compress/gzip package the last time I've tried this.

This means we'd have to do a static link for zlib in the static build and link zlib dynamically in the dynamic link build. Both options would require that we actually add a new dependency. Using cgzip for compression needs to be discussed before we can add this.

**Comment by bobrik** [comment]
Do you have a link for issues you were having with cgzip?

Speed benefits overweight additional dependency in my opinion.

What do you think about creating an issue about gzip performance in golang repo? Maybe it's their problem after all.

**Comment by phemmer** [comment]
I thought external gzip was added as part of #7542, but browsing through the changes, it doesn't appear so.
Is there any reason we don't try to detect and use an external `gzip`? We could then detect the `pigz` utility as well for even faster operations.

**Comment by bobrik** [comment]
Currently docker can saturate only one core, with `pigz` it can use more resources, but this is not necessarily a good thing.

**Comment by phemmer** [comment]
@bobrik `pigz` was just a nice bonus. If you're concerned about docker using more than 1 core, then I would put forth a few comments.
1. You're still going to be bottle necked by network throughput. If the network can't handle the data being pushed through it, `pigz` will slow down. Thus `pigz` will only use the resources it needs to keep up.
2. Docker has never committed that the daemon won't use more than one core (that I am aware of). Such behavior is at the control of the GO scheduler. It is entirely possible for the scheduler to change in which it will start using multiple cores (without having to set `GOMAXPROCS`).
3. Go can do detection of the `GOMAXPROCS` value. If set to 1, don't use `pigz`.

**Comment by bobrik** [comment]
10Gbps of gzip can easily saturate many cores, I assume. I like the idea of using `GOMAXPROCS` for `pigz`.

I'd love to know about `cgzip` issues, because I had no success googling them myself.

**Comment by bobrik** [comment]
I compiled docker with cgzip and ran into an error when tried to download image packed with usual docker instance:

```
FATA[0004] Error pulling image (2015-01-13.1) from <redacted>, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
```

@unclejack is this what you meant?

My `gunzip.go -c` works as expected without any errors on the same layer file.

**Comment by bobrik** [comment]
I hacked `applyLayer` to write stdin to a file:

```go
func applyLayer() {
	runtime.LockOSThread()
	flag.Parse()

	f, err := os.Create(fmt.Sprintf("/var/tmp/docker-layer-%s.tar", path.Base(path.Dir(flag.Arg(0)))))
	if err != nil {
		fatal(err)
	}

	defer f.Close()

	io.Copy(f, os.Stdin)

	encoder := json.NewEncoder(os.Stdout)
	if err = encoder.Encode(applyLayerResponse{8}); err != nil {
		fatal(fmt.Errorf("unable to encode layerSize JSON: %s", err))
	}

	flush(os.Stdout)
	flush(os.Stdin)
	os.Exit(0)
}
```

Looks like for each `docker pull` stdin gets different length:

```
web605 ~ # ls -la /var/tmp/docker-layers-*/docker-layer-fe95bf7d5f5090fdaf5c5d442f9f05211f9cb338107a41ff10c7a46be4be2dea.tar
-rw-r--r-- 1 root root 196949644 Jan 22 11:18 /var/tmp/docker-layers-1/docker-layer-fe95bf7d5f5090fdaf5c5d442f9f05211f9cb338107a41ff10c7a46be4be2dea.tar
-rw-r--r-- 1 root root 196934405 Jan 22 11:37 /var/tmp/docker-layers-2/docker-layer-fe95bf7d5f5090fdaf5c5d442f9f05211f9cb338107a41ff10c7a46be4be2dea.tar
-rw-r--r-- 1 root root 196912275 Jan 22 11:43 /var/tmp/docker-layers-3/docker-layer-fe95bf7d5f5090fdaf5c5d442f9f05211f9cb338107a41ff10c7a46be4be2dea.tar
```

@alainjobart looks like you written `cgzip`, do you have any idea what could be wrong?

**Comment by bobrik** [comment]
Okay, I only replaced compression code in 1.4.1 (master has #10269) and here's what I've got:

|version|time|win|
|-------|----|---|
|1.4.1+gzip|80s|baseline|
|1.4.1+cgzip|58s|28% faster|

Pretty nice improvement, if you ask me :)

Pulls work just fine for those images on vanilla docker 1.4.1.

**Comment by bobrik** [comment]
@unclejack any updates on this?

**Comment by unclejack** [comment]
@bobrik I'll ping you on a PR soon.

**Comment by bobrik** [comment]
@unclejack how soon, btw?

**Comment by qwerty55** [comment]
One should try LZO or lrzip instea dof gzip. I've found this to beat gzip in both compression and time to compress.

**Comment by unclejack** [comment]
@bobrik I've looked into this a while ago and had working code. However, the code has been changed quite a bit since then and I need to look into this again.

**Comment by bobrik** [comment]
Any news? I tried migrating v1->v2 registry on 1.8.1 and it takes forever even with a small registry when v1 takes less than 100gb on disk.

**Comment by unclejack** [comment]
@bobrik This will most likely be fixed through the upgrade to Go 1.6. Both compression and decompression performance will be improved.

There's no point in doing anything else for this now as there are many high priority actionable items to take care of before doing this.

Even though this will be fixed automatically when upgrading to Go 1.6, this issue should stay open because we could make other improvements in the meantime.

**Comment by bobrik** [comment]
@unclejack do you have any links that makes you think that go 1.6 will improve things dramatically?

**Comment by icecrime** [comment]
Ping @vatts @aaronlehmann: I wasn't aware of this, thought you might find it interesting.

**Comment by aaronlehmann** [comment]
I looked at the git history for Go's `compress/flate` package and didn't see any recent changes that look like they will boost deflate speed. There are some optimizations to inflate, but I don't think they will close the decompression speed gap. @unclejack, which Go 1.6 changes are you thinking of?

I came across https://github.com/klauspost/compress, which looks promising. But I wonder how we would convince ourselves that this package is robust enough to switch over to it.

**Comment by unclejack** [comment]
@bobrik @icecrime @aaronlehmann https://go-review.googlesource.com/#/c/14080/ is one such important change which affects both compression and decompression speeds on CPUs with that instruction.

https://go-review.googlesource.com/#/c/15651/ is yet another change.

https://github.com/klauspost/compress is indeed promising, but those changes need to go into the stdlib's version of gzip. There's a lot more to be done regarding the performance of the gzip package.

Anyone interested in improving performance should look into 1) improving https://github.com/klauspost/compress 2) getting those changes into the stdlib 3) improving the testing of all compression related packages 4) finding and getting rid of differences between gzip archives produced by the Go gzip package and by those produced using the `gzip` command (the zlib based one)

**Comment by stevvooe** [comment]
Another approach here would be to avoid compressing inline during the push. If we saved the image artifacts, and do the compression at commit time, the cost would be amortized for every push. It would also contribute to layer hash stability and dramatically decrease registry storage requirements.

**Comment by unclejack** [comment]
@stevvooe That would have to be done as background jobs. Everyone would complain about slow commits otherwise.

**Comment by AkihiroSuda** [comment]
Optional support for `unpigz` (parallel gunzip) was introduced in Docker 18.02: https://github.com/moby/moby/commit/871afbb304422877e683cbafc0ebd0b029b85379
