### ISSUE TITLE
Error response from daemon: Cannot start container c64662f04dde

### ISSUE THREAD

**Issue by zopyx** [moby/moby#10218]
Running the following image from scratch on a new CentOS 7 installation fails badly:

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest

a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83
## 2015/01/20 14:32:11 Error response from daemon: Cannot start container a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83:  (exit status 1)

[root@docker log]# uname -a
Linux docker.zopyx.com 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@docker log]# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
[root@docker log]# docker --version
Docker version 1.3.2, build 39fa2fa/1.3.2
[root@docker log]# docker -D info
Containers: 11
Images: 175
Storage Driver: devicemapper
 Pool Name: docker-253:1-203062427-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 9.075 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 11.17 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): false
Debug mode (client): true
Fds: 36
Goroutines: 44
EventsListeners: 0
Init SHA1: c906504aa058139c1d0569ecd0aa5f462a73440f
Init Path: /usr/libexec/docker/dockerinit

---

Jan 20 08:31:50 localhost docker: [7a34f2cd] +job create(cadvisor)
Jan 20 08:31:51 localhost kernel: device-mapper: thin: Creation of new snapshot 192 of device 185 failed.
Jan 20 08:31:51 localhost kernel: device-mapper: thin: Creation of new snapshot 193 of device 185 failed.
Jan 20 08:31:51 localhost kernel: device-mapper: thin: Creation of new snapshot 194 of device 185 failed.
Jan 20 08:31:51 localhost kernel: device-mapper: thin: Creation of new snapshot 195 of device 185 failed.
Jan 20 08:31:59 localhost kernel: EXT4-fs (dm-8): mounted filesystem with ordered data mode. Opts: discard
Jan 20 08:32:09 localhost docker: [info] GET /images/json?all=False
Jan 20 08:32:09 localhost docker: [7a34f2cd] +job images()
Jan 20 08:32:09 localhost docker: [7a34f2cd] -job images() = OK (0)
Jan 20 08:32:09 localhost docker: [info] GET /images/json?all=True
Jan 20 08:32:09 localhost docker: [7a34f2cd] +job images()
Jan 20 08:32:09 localhost docker: [7a34f2cd] -job images() = OK (0)
Jan 20 08:32:09 localhost docker: [info] GET /containers/json?all=False&size=False
Jan 20 08:32:09 localhost docker: [7a34f2cd] +job containers()
Jan 20 08:32:09 localhost docker: [7a34f2cd] -job containers() = OK (0)
Jan 20 08:32:09 localhost docker: [info] GET /containers/json?all=True&size=False
Jan 20 08:32:09 localhost docker: [7a34f2cd] +job containers()
Jan 20 08:32:09 localhost docker: [7a34f2cd] -job containers() = OK (0)
Jan 20 08:32:09 localhost docker: [info] GET /events?since=1421760710&until=1421760729
Jan 20 08:32:09 localhost docker: [7a34f2cd] +job events()
Jan 20 08:32:09 localhost docker: [7a34f2cd] -job events() = OK (0)
Jan 20 08:32:10 localhost docker: [7a34f2cd] +job log(create, a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83, google/cadvisor:0.8.0)
Jan 20 08:32:10 localhost docker: [7a34f2cd] -job log(create, a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83, google/cadvisor:0.8.0) = OK (0)
Jan 20 08:32:10 localhost docker: [7a34f2cd] -job create(cadvisor) = OK (0)
Jan 20 08:32:10 localhost docker: [info] POST /v1.15/containers/a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83/start
Jan 20 08:32:10 localhost docker: [7a34f2cd] +job start(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)
Jan 20 08:32:10 localhost kernel: EXT4-fs (dm-8): mounted filesystem with ordered data mode. Opts: discard
Jan 20 08:32:11 localhost docker: [7a34f2cd] +job allocate_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job allocate_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83) = OK (0)
Jan 20 08:32:11 localhost docker: [7a34f2cd] +job allocate_port(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)
Jan 20 08:32:11 localhost docker: [7a34f2cd.allocate_port(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)] Received an unexpected error during port allocation: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 ! -i docker0 -j DNAT --to-destination 172.17.0.12:8080: iptables: No chain/target/match by that name.
Jan 20 08:32:11 localhost docker: (exit status 1)
Jan 20 08:32:11 localhost docker: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 ! -i docker0 -j DNAT --to-destination 172.17.0.12:8080: iptables: No chain/target/match by that name.
Jan 20 08:32:11 localhost docker: (exit status 1)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job allocate_port(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83) = ERR (1)
Jan 20 08:32:11 localhost docker: [7a34f2cd] +job release_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job release_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83) = OK (0)
Jan 20 08:32:11 localhost docker: [7a34f2cd] +job release_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job release_interface(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83) = OK (0)
Jan 20 08:32:11 localhost docker: [7a34f2cd] +job log(die, a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83, google/cadvisor:0.8.0)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job log(die, a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83, google/cadvisor:0.8.0) = OK (0)
Jan 20 08:32:11 localhost docker: Cannot start container a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83:  (exit status 1)
Jan 20 08:32:11 localhost docker: [7a34f2cd] -job start(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83) = ERR (1)
Jan 20 08:32:11 localhost docker: [error] server.go:1207 Handler for POST /containers/{name:.*}/start returned error: Cannot start container a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83:  (exit status 1)
Jan 20 08:32:11 localhost docker: [error] server.go:110 HTTP Error: statusCode=500 Cannot start container a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83:  (exit status 1)
^C
[root@docker log]#

**Comment by tiborvass** [comment]
Ping @vbatts @unclejack

**Comment by vbatts** [comment]
Just tried a couple of times on a centos7 with docker 1.4.1-dev 2feb2d0, and did not get this failure.
Trying again on docker v1.3.2

**Comment by vbatts** [comment]
Still not able to reproduce :-\

```
centos@vbatts-centos7-docker ~ (master) $ $DOCKER version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa
centos@vbatts-centos7-docker ~ (master) $ $DOCKER info
Containers: 0
Images: 1302
Storage Driver: devicemapper
 Pool Name: docker-253:1-2162572-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 3.811 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 30.45 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.9.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 10
EventsListeners: 0
Init SHA1: e13f3c56a7630e64b7291f29e4ae4742c23e42aa
Init Path: /home/centos/docker/bundles/1.3.2/dynbinary/dockerinit
```

**Comment by phemmer** [comment]
Just curious, but why was this tagged with devicemapper? The issue appears to be with iptables, not the storage driver.

```
Jan 20 08:32:11 localhost docker: [7a34f2cd.allocate_port(a2324698f5efaf98bfd9efc952cca898c58d8b38faf3f9e5272ff0851d048a83)] Received an unexpected error during port allocation: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 ! -i docker0 -j DNAT --to-destination 172.17.0.12:8080: iptables: No chain/target/match by that name.
Jan 20 08:32:11 localhost docker: (exit status 1)
Jan 20 08:32:11 localhost docker: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 ! -i docker0 -j DNAT --to-destination 172.17.0.12:8080: iptables: No chain/target/match by that name.
Jan 20 08:32:11 localhost docker: (exit status 1)
```

@zopyx Do you have a firewall daemon of some sort running? Something which may have removed the `DOCKER` chain?
Can you run `iptables -t nat -nvL` and provide the output here?

**Comment by zopyx** [comment]
[ajung@docker base]$ sudo iptables -t nat -nvL
[sudo] password for ajung:
Chain PREROUTING (policy ACCEPT 71 packets, 2871 bytes)
 pkts bytes target     prot opt in     out     source               destination
13988  645K PREROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13988  645K PREROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13988  645K PREROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 24 packets, 1478 bytes)
 pkts bytes target     prot opt in     out     source               destination
10380  636K OUTPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain POSTROUTING (policy ACCEPT 24 packets, 1478 bytes)
 pkts bytes target     prot opt in     out     source               destination
10380  636K POSTROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0
10380  636K POSTROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
10380  636K POSTROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING_ZONES (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 POST_public  all  --  *      veth654f473  0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 POST_public  all  --  *      veth75ab5d7  0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 POST_public  all  --  *      veth579449c  0.0.0.0/0            0.0.0.0/0           [goto]
 6813  422K POST_public  all  --  *      ens3    0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 POST_public  all  --  *      veth5d5ebfb  0.0.0.0/0            0.0.0.0/0           [goto]
 3477  209K POST_public  all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           [goto]
   90  5376 POST_public  all  --  *      +       0.0.0.0/0            0.0.0.0/0           [goto]

Chain POSTROUTING_ZONES_SOURCE (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain POST_public (7 references)
 pkts bytes target     prot opt in     out     source               destination
10380  636K POST_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0
10380  636K POST_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0
10380  636K POST_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain POST_public_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain POST_public_deny (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain POST_public_log (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain PREROUTING_ZONES (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 PRE_public  all  --  veth654f473 *       0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 PRE_public  all  --  veth75ab5d7 *       0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 PRE_public  all  --  veth579449c *       0.0.0.0/0            0.0.0.0/0           [goto]
13628  619K PRE_public  all  --  ens3   *       0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 PRE_public  all  --  veth5d5ebfb *       0.0.0.0/0            0.0.0.0/0           [goto]
  360 25308 PRE_public  all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           [goto]
    0     0 PRE_public  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto]

Chain PREROUTING_ZONES_SOURCE (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain PREROUTING_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain PRE_public (7 references)
 pkts bytes target     prot opt in     out     source               destination
13988  645K PRE_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13988  645K PRE_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13988  645K PRE_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain PRE_public_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain PRE_public_deny (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain PRE_public_log (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by phemmer** [comment]
Yup, that appears to be the issue. You have something which is manipulating the iptables firewall, and it deleted the `DOCKER` chain.

**Comment by zopyx** [comment]
How do you restore the docker chain?

2015-01-20 18:54 GMT+01:00 Patrick Hemmer <notifications@github.com>:

**Comment by phemmer** [comment]
@zopyx simplest solution is to restart docker. But if this other tool is managing the firewall, it could wipe it out again.

**Comment by zopyx** [comment]
I don't know of any tool. The only changes made to the firewall settings
was adding some public ports...but I will check



2015-01-20 18:57 GMT+01:00 Patrick Hemmer <notifications@github.com>:

**Comment by nwood888** [comment]
I'm running into the same issue.  I've determined that once docker is running, if I restart iptables (systemctl restart iptables) the docker chain is lost and I need to restart docker to get going again.  Maybe I should be restarting iptables a different way or maybe docker should persist the chain somewhere?

**Comment by zopyx** [comment]
Also this issue shows again that the monolithic design of Docker is broken
by design..giving up further tries with Docker. Docker is completely
unusable. I wished the developers would turn on their brains and think
about the bullshit they put into code before bringing such a fragile
technology into the world and get $$$$$$ venture capital for bullshit that
has more flaws than features.

2015-01-20 22:33 GMT+01:00 Nick Wood <notifications@github.com>:

**Comment by unclejack** [comment]
Similar problems have been encountered with third party firewall scripts and cron jobs which alter netfilter (iptables) rules, and chains.
This has been observed in https://github.com/docker/docker/issues/9236 and it turned out it was actually APF (Advanced Policy Firewall, https://www.rfxn.com/projects/advanced-policy-firewall/). The user had this on their system and it was making their containers lose Internet connectivity when the cron job would flush rules and add other rules.

On such setups where external tools are altering the netfilter rules, there's no way to guarantee that everything will function properly.
Even if Docker would just re-create the chains and rules it needs on systems where a tool is deleting Docker's chain and rules is being used, this wouldn't guarantee any of the following: 
* that the rules and chains won't be removed again
* continuous and interrupted Internet connectivity for the containers 
* the connectivity between the containers themselves
* that all the rules and chains won't be removed between the execution of one iptables command and the next

As far as Docker is concerned, this is what can be done:
1. try to detect the removal of chains / rules which have been created before 
2. document this problem in the official documentation to make it easier to debug

I've also got CentOS 6 and CentOS 7 systems running Docker, but I haven't run into these problems so far. This means that the problem is most likely not caused by something found in a standard install of CentOS 6 and CentOS 7.

Netfilter would never remove the DOCKER chain on its own while the system is running. This is something done by an external tool.

Your system is probably running some kind of firewall scripts which re-apply netfilter rules from time to time, possibly with a cron job or using a daemon. Please take a look at your system to try to find the actual tool which does this. Once you've figured out what tool is doing this, you can probably grab the netfilter rules it's setting up and write a new less intrusive firewall script or you could simply modify that firewall script to stop deleting chains and to not flush rules.

After you've taken a look and investigated, please comment again on this issue so that we can investigate this further if required, document the problem in a better way and let other users avoid it.

**Comment by erikh** [comment]
Hi,

So, fundamentally iptables is a transactional system. You write a bunch of rules out and then you commit the results. You can see this in `iptables-save` and `iptables-restore` implementations, and the xtables/iptc API deliberately goes out of its way to make this possible.

My point is, if APF or UFW or firewalld operate like `iptables-restore`, your rules are going to be replaced in a transaction rather than one-by-one, making it extremely hard for docker to keep up with the changes.

I am writing an iptables library @ https://github.com/erikh/iptables to resolve this issue inside docker. The iptables invocations are pretty broken as it stands and probably super racy.

I hope this helps give some context into how we see the problem and what needs to be done. It's not a small amount of work and literally nothing out there exists in this form now (other than the xtables/iptc API, which is in C).

**Comment by nwood888** [comment]
In our case, centos7, Docker didn't work at all with firewalld - similar issues to what's described here https://groups.google.com/forum/#!topic/docker-user/CUOz0el897M.

So yes, @unclejack, you are correct, we're not running a "stock install" of centos7, we switched to iptables for the above reason.

Maybe Docker plays nice with firewalld now and using it avoids the problem from this thread?  I haven't tested in the last few weeks.

**Comment by unclejack** [comment]
@nwood888 That's not the case currently, there's no integration with firewalld.
Please take a look at https://github.com/docker/docker/issues/9395 and at the PR which implements support for firewalld: https://github.com/docker/docker/pull/9397

**Comment by jochenseeber** [comment]
We have the same issue, however we run the docker daemon with iptables=false. In this case I would expect docker to not touch the iptables rules at all. However, it still tries to do that and so running a container fails:

    +job link(-A)                                
    /sbin/iptables, [--wait -t filter -A DOCKER -i docker0 -o docker0 -p tcp -s 172.17.0.4 -d 172.17.0.3 --dport 3306 -j ACCEPT] 
    s --wait -t filter -A DOCKER -i docker0 -o docker0 -p tcp -s 172.17.0.4 -d 172.17.0.3 --dport 3306 -j ACCEPT: iptables: No chain/target/match by that name.
    
    -job link(-A) = ERR (1)                      
    +job link(-D)                                
    /sbin/iptables, [--wait -t filter -D DOCKER -i docker0 -o docker0 -p tcp -s 172.17.0.4 -d 172.17.0.3 --dport 3306 -j ACCEPT] 
    -job link(-D) = OK (0)

**Comment by bubenkoff** [comment]
disabling iptables worked for me to fix this issues
but should it (firewall issue) be reported properly by docker then?
error code 1 and nothing in logs doesn't tell you much...

**Comment by zopyx** [comment]
Docker must perform much more consistency checks for checking kernel,
distro constraints etc. Right now Docker users remain standing in the rain.

2015-04-13 7:30 GMT-04:00 Anatoly Bubenkov <notifications@github.com>:

**Comment by bubenkoff** [comment]
+1

**Comment by mindscratch** [comment]
seeing similar issues with CentOS 7, iptables, Docker 1.6

**Comment by v1k0d3n** [comment]
same issues here on CentOS7: Docker version 1.6.0, build 8aae715/1.6.0

**Comment by Matt-Deacalion** [comment]
Same on Arch, Docker version 1.6.2.

**Comment by erikh** [comment]
Seeing this on arch too. It’s the iptables code.

-Erik

**Comment by marcoamorales** [comment]
FWIW, I was getting this error after upgrading many packages in Arch and not rebooting, including those packages was the kernel.

After rebooting the error was gone.

**Comment by pablobs** [comment]
I have using shorewall with docker from months with sucess utilizing iptables=false in configuration. But, after make a actualization in Debian its stops.. Why altering this functionality? My actual version is 
1.6.1. If i remember well, my version before is 1.4.0

**Comment by zopyx** [comment]
Because the Docker guys give a shit about functionality and bugs.

2015-05-28 16:52 GMT+02:00 Pablo B. Santiago <notifications@github.com>:

**Comment by pablobs** [comment]
Yes for sure. And the worst is that I think it is precisely to encourage the use of firewalld. This is another way to encourage the use of RedHat!? I will not use Centos or whatever solution. What hapeness to "freedom of choice" ?!

**Comment by darkermatter** [comment]
I arrived here due to container start problems. Lo and behold, it was indeed a problem with iptables which I restarted after starting Docker.

I simply made a note to self not to do that and the problem has gone away - funny that, no need for colourful language.

I have a question for the esteemed developers... We are in the process of moving *everything* over to Docker. If a server is Docker-only, then this sort of thing shouldn't be an issue, right? We should just let Docker handle all firewall stuff?

Cheers,
Jason.

**Comment by malnick** [comment]
Same issue on Ubuntu 12.04 Docker 1.7

Status: Image is up to date for malnick/mesos-marathon:latest
f4d0896c5469fc81cdecb711065fb3032ffe9b039c544b9cf66a39b9ed1f9c8b
Error response from daemon: Cannot start container f4d0896c5469fc81cdecb711065fb3032ffe9b039c544b9cf66a39b9ed1f9c8b: device or resource busy

 *
root@mesosmaster:/etc/puppetlabs/puppet# docker --version
Docker version 1.7.0, build 0baf609
root@mesosmaster:/etc/puppetlabs/puppet# uname
Linux
root@mesosmaster:/etc/puppetlabs/puppet# uname -a
Linux mesosmaster 3.2.0-83-virtual #120-Ubuntu SMP Wed Apr 29 15:49:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@mesosmaster:/etc/puppetlabs/puppet#

**Comment by beetree** [comment]
Having a similar issue on fresh CentOS 7.1 installation. Docker 1.7.1.

The problem only happens "sometimes" but too often to make it a serious problem. Here is a session to highlight the problem:

```
[root@m3210 ~]# docker stop d6fafcd35c6b
d6fafcd35c6b
[root@m3210 ~]# docker start d6fafcd35c6b
Error response from daemon: Cannot start container d6fafcd35c6b: adding interface veth6a7a1d4 to bridge docker0 failed: could not find bridge docker0: no such network interface
Error: failed to start containers: [d6fafcd35c6b]
[root@m3210 ~]# docker start d6fafcd35c6b
Error response from daemon: Cannot start container d6fafcd35c6b: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 11138 -j DNAT --to-destination 172.17.0.162:11138 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
Error: failed to start containers: [d6fafcd35c6b]
[root@m3210 ~]# docker start d6fafcd35c6b
d6fafcd35c6b
[root@m3210 ~]# docker stop d6fafcd35c6b
d6fafcd35c6b
[root@m3210 ~]# docker start d6fafcd35c6b
Error response from daemon: Cannot start container d6fafcd35c6b: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 11174 -j DNAT --to-destination 172.17.0.164:11174 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
Error: failed to start containers: [d6fafcd35c6b]
[root@m3210 ~]# docker start d6fafcd35c6b
Error response from daemon: Cannot start container d6fafcd35c6b: adding interface veth7849511 to bridge docker0 failed: could not find bridge docker0: no such network interface
Error: failed to start containers: [d6fafcd35c6b]
[root@m3210 ~]# docker start d6fafcd35c6b
d6fafcd35c6b
```

Does anyone have a solution?


@darkermatter don't do it.

**Comment by jlj** [comment]
I just had a similar issue on Ubuntu 14.04, with Docker version 1.8.1, build d12ea79

````
~# docker run --name site-ssh --volumes-from site-data -p 9252:22 --restart=always -d ssh-base
b05100a09893fdcaac3fdd776cfb69e2568289870ef65c201946fead08a08a91
Error response from daemon: Cannot start container b05100a09893fdcaac3fdd776cfb69e2568289870ef65c201946fead08a08a91: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9252 -j DNAT --to-destination 172.17.0.6:22 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
````

Trying to start the container again did not help:

````
~# docker start site-ssh
Error response from daemon: Cannot start container site-ssh: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9252 -j DNAT --to-destination 172.17.0.7:22 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
Error: failed to start containers: [site-ssh]
````

But simply removing the container and running the exact same command again fixed the issue in this case:

````
~# docker rm -v site-ssh
site-ssh
~# docker run --name site-ssh --volumes-from site-data -p 9252:22 --restart=always -d ssh-base
ce4c1f05d7574b1110b881eb6f00a565f62a473507a0f694fa19a25e195532f1
~# 
````

**Comment by hudsantos** [comment]
Got the same issue today, and solved with **service docker stop** and **service docker start**. It seems a human messed up iptables rules through iptables-persistent.. hehe. And restarting docker it rebuilds this docker needed iptables chains structure.

Thanks for the community.

**Comment by Bones12345** [comment]
Had this problem using Docker and a mail server; turns out FireHOL was my issue.  FireHOL basically deletes all the IPTables rules you have, and re-creates them on every boot.

I "solved" the issue by installing iptables-persistent, and saving the rules to /etc/iptables/ with:

/etc/init.d/iptables-persistent save

Then I renamed /etc/init.d/firehol to /etc/init.d/firehol.disabled so it doesn't run on every boot.

Dumb thing is that now, if I change my FireHOL rules, I have to remember to re-start Docker to get the Docker rules back in there, THEN save.

**Comment by dredgerman** [comment]
I'm getting this error in Ubuntu 12.04 running firewalld, so are Docker saying the entire distro setup should be changed as standard to fit round their useless buggy code?  Been trying to install their "30 min" install of discourse using docker and 48 hours later still battling through, only to find it doesn't work with stock firewall products, ridiculous!!

**Comment by SeanZhu20** [comment]
I also encountered this issue with CentOS 7 and docker 1.9.1

Error response from daemon: Cannot start container ad4147a19faccd36b3d235d557866e23dd9f395082c9b54f95ddf03d642a7b6c: network bridge not found

**Comment by SeanZhu20** [comment]
I stilled encountered this error.
I'm excuting docker run on CentOS 7 and my docker version is 1.9.1:

got this:
## Error response from daemon: Cannot start container 99718c9e8778152da6297cd3c6652519a99aa439ff5c376c2d535ecb5ac61c2c: network bridge not found


[issue18113]( https://github.com/docker/docker/issues/18113) is a similar issue and Deleting /var/lib/docker/network/files/local-kv.db was suggested, but not works for me.

Restart docker daemon works for me.

**Comment by dannykorpan** [comment]
Same issue here with Docker 20.10.22 on Ubuntu 22.04.

**Comment by thaJeztah** [comment]
let me close this one as stale; the original issue reported is 10 years old (and basically all components involved have been replaced), and the "bridge" network error looks unrelated to the original issue.
