### ISSUE TITLE
can docker change the device access permission during container running

### ISSUE THREAD

**Issue by mayujsw** [moby/moby#10637]
I'd use --device to bind an Android device to a container (cause there are several Android devices connecting to the physical host), and this contianer can only access to this binded device only, so i use --device /dev/bus/usb/003/102 when starting to run the container, everything is OK,  but when i do adb reboot in this container, the device node (e.g. 189:361) will change to new node name like 189:362, but the container i just created just only has permission to acess 189:361. then it can not access to new node now, even its the same android device.

my quesiton is that is there a way that i can change the device permission for a running container, this should be a common feature when using docker with Android devices....Thanks in advance

**Comment by mayujsw** [comment]
anyone any idea ....

**Comment by timthelion** [comment]
not at this time. See https://github.com/docker/docker/pull/8826

If you launch the Docker daemon with the lxc backend, you should be able to use `--lxc-conf=lxc.cgroup.devices.allow = c 189:* rwm` to allow your container to access all devices of that group, and then use a volume `-v /dev/bus/usb/` to access all USB devices.

**Comment by nuaays** [comment]
@mayujsw  hi, would you please help show the docker run command how to start a container with mounting the android usb devices for accessing in container

thanks

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
