### ISSUE TITLE
Proposal: deprecate "docker run" pulling unknown containers and add explicit "--pull" flag

### ISSUE THREAD

**Issue by tianon** [moby/moby#10693]
While having `docker run` automatically pull images that don't exist locally is nice for first-time users (since they can just `docker run some-image` and see the magic happen), it can be very frustrating for more experienced users who want to control the images they have and run on their host, especially since a pull cannot be cancelled except by restarting the entire daemon.  A stray `docker run` of the wrong image in the wrong terminal, for example, is a very frustrating situation to be in, especially since you then get to wait for that image to download (or not wait and then try to remember to delete it afterwards).

In other cases (especially scripted ones), `docker pull some-image && docker run some-image` emerges as a very common pattern.  For consistency with the new `docker build --pull`, I propose the addition of `docker run --pull` (ideally implemented daemon-side like `docker build --pull` is), which will default to `false` and thus change:

``` console
$ docker run --rm lolimage
Unable to find image 'lolimage:latest' locally
Pulling repository lolimage
FATA[0002] Error: image library/lolimage:latest not found 
```

into:

``` console
$ docker run --rm lolimage
FATA[0002] Error: image library/lolimage:latest not found 
```

Since this is a broader proposal than #10639 (deprecating an existing "feature"), I opted to make a new one instead of just commenting there.

**Comment by phemmer** [comment]
I'm on both sides of the fence. Some times I like the implicit pull, some times I hate it. I could get behind this option though. But would propose an addition: `--pull=ask`. As you would expect, it would prompt you if it needs to pull it.

**Comment by jfrazelle** [comment]
I like the addition of a --pull flag on run a lot, I'm going to have to
think about depreciating automatically pull tho.
I have felt the pain (seriously so bad) of doing a run and it pulling and
being like nooooooooo then waiting then forgetting to remove too too too
many times. So yeah but I think maybe it could also be solved by being able
to ctrl C a pull (ugh if only)

**Comment by thaJeztah** [comment]
Same for me; so "yes", but unsure about the deprecation if other options become available (`CTRL-C`).

(I see some value in @phemmer's comment wrt being more configurable, but I don't think *this* issue is the right place to discuss that)

**Comment by frank-dspeed** [comment]
yes i think simply adding the pull flag invalidates the current existing img and pulls newer img as also it pulls images when the --rm flag is given.

so i think the correct way of implamenting this is add a --pull flag here to the docker run command that does realy befor it starts the container job quees a regular pull job for the img like if we did docker pull image befor.

Results: If img is there checks for newer if there pull if not go to next step run if --pull supplyed.

**Comment by tianon** [comment]
Closing given the explicit `--pull` flag was implemented in https://github.com/docker/cli/pull/1498 (and the other half is probably too hostile to new users).

Perhaps there could be a new proposal to define a "default" pull policy as daemon configuration instead? :smile:

**Comment by thaJeztah** [comment]
Perhaps a default in the cli config? Or did you think of putting it on the daemon?

**Comment by tianon** [comment]
CLI config would be an OK compromise, but IMO things like "default platform" and "default pull-policy" are really daemon-level preferences.

**Comment by frank-dspeed** [comment]
out of my view (open-pwa) Platform i would like to see that on the daemon settings and only there

**Comment by cpuguy83** [comment]
I don't see how there can be a default pull policy.
Since "docker run" is explicitly calling pull rather than the daemon automatically pulling.
I suppose the daemon could return a non-404 error response if the image doesn't exist on create.

**Comment by tianon** [comment]
Yeah, I understand that due to the technical details of how the pull happens, it's difficult to have the configuration on the daemon, my thought was simply that from a user / system administrator's perspective, that's where the strongest user preference is going to be, so that's why I'd love to see it as a daemon flag, but totally get that it's complicated (which is why I'm not planning to open the explicit proposal myself :innocent:; I'm happy enough with a `--pull` flag).
