### ISSUE TITLE
Clarify content in Dockerfile Reference 

### ISSUE THREAD

**Issue by moxiegirl** [moby/moby#10743]
Reading Docker documentation as a first time user. The general structure and tutorial are great, but texts have some problems. For example

https://docs.docker.com/reference/builder/

It's not clear at some places, contains details but not general information, referring to ambiguous terms. e.g. for CMD, ENTRYPOINT, ENV, ADD, .... 
- each topic does not start with clear description of the command purpose and what problem it tries to solve
- the context is not clearly defined (e.g. CMD vs RUN): is it for process of building an image or for running inside of a container based on the image being built.
- the reference like "this is to set defaults" is completely confusing. For defaults in which context and what kind of commands?
- ADD copies files from source to destination. Where are source and destination, copying on which phase?
- environment - there must be a clear explanation about one environment that exists in a Dockerfile scope, another for commands that are RUN to build image, third - for everything that will be run inside a container built on the image.
- word "container" here often is confusing. Container at the build time or after running a container based on built image?

**Comment by LK4D4** [comment]
@thaJeztah still actual?

**Comment by thaJeztah** [comment]
Some things look to be addressed, but it still needs some TLC

/cc @mstanleyjones

**Comment by AkihiroSuda** [comment]
I think we have good docs now (and the docs are out of scope of this repo now).

Let me close this issue.
