### ISSUE TITLE
Need to define a format for container image config

### ISSUE THREAD

**Issue by jlhawn** [moby/moby#10753]
The docker distribution team is working on finalizing a [generic application content manifest](https://github.com/docker/distribution/pull/62) and for the new distribution tools to be used by Docker, we'll need to define an application media type for images.

An example media type would be:

```
application/vnd.docker.container.image.params.v1+json
```

with a format similar to that of the [docker image runconfig field](https://github.com/docker/docker/blob/802802b7812b7c73aefec4e922cad82f8dcddd4c/image/spec/v1.md#container-runconfig-field-descriptions)

``` json
{
    "user": "alice",
    "group": "staff",
    "cpuShares": 8,
    "memory": 2048,
    "memorySwap": 4096,
    "workingDirectory": "/home/alice",
    "ports": [
        {
            "port": 8080,
            "protocol": "tcp"
        }
    ],
    "volumes": [
        "/var/job-result-data",
        "/var/log/my-app-logs"
    ],
    "entrypoint": [
        "/bin/my-app-binary"
    ],
    "command": [
        "--foreground",
        "--config",
        "/etc/my-app.d/default.cfg"
    ],
    "environment": {
        "DEBUG": "True",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "RETRO": "False"
    }
}
```

**Comment by phemmer** [comment]
I would use `uid` and `gid` (and the appropriate numbers instead of names) in place of `user` and `group`.
If the image does not contain an `/etc/passwd`, user name is meaningless, while a setuid call to the uid number will still work fine. Basically, uid number always works, name doesn't.

**Comment by jlhawn** [comment]
@phemmer The `user` and `group` field would be flexible enough to handle either UID/GID or username/groupname. If the container doesn't have `/etc/passwd` then the builder of the image would just use a number for `user` and `group` rather than a name string.

**Comment by jlhawn** [comment]
@phemmer here's some of the original comments on that part of the current spec: https://github.com/docker/docker/pull/9560#discussion_r22246592

**Comment by jlhawn** [comment]
@estesp While I opened this issue to get started on a container image data scheme, I know you're very interested in multi-os/arch images, which would be a separate application media type, but it's probably a good idea that those two JSON formats be developed together.

**Comment by thaJeztah** [comment]
I guess this should now be covered by the OCI
