### ISSUE TITLE
Debug/Diagnostics tools

### ISSUE THREAD

**Issue by jlhawn** [moby/moby#10861]
As the complexity of docker continues to grow, it is becoming increasingly difficult to diagnose the many issues that are reported daily. While there are some guidelines we have when reporting issues (daemon log dump, `docker info`, `docker version`, etc), anything more specific requires the user to manually collect info that may be difficult to find.

It may be beneficial to provide a simple tool that users can run to collect basic info about their docker installation and can also be used to collect broader information about their system and network configuration to better diagnose issues. The user could then simply attach the output of this tool to a github issue so that maintainers/contributors may inspect it and better understand the issue and more quickly find a resolution.

@docker/maintainers what kind of info (outside of the basics like version, and `docker info`) do you suggest be collected by such a tool, and do you think we could start an effort to implement such a diagnostic tool?

**Comment by jlhawn** [comment]
ping @brianbland

**Comment by thaJeztah** [comment]
Isn't the [check-config.sh](https://github.com/docker/docker/blob/master/contrib/check-config.sh) meant for this?

**Comment by dustin-decker** [comment]
I'm considering building a tool to do this for overlay networking and ingress networking with Swarm mode. It seems like a lot of people are struggling to have stable networking. With many variables to consider and layers of technology to look at it is a necessary tool for troubleshooting.

**Comment by thaJeztah** [comment]
Looks like this one went stale, and is a bit too broad to keep open as tracking ticket. That said, there's some exploratory work being done on debugging tools for networking issues and some other areas.

Let me close this one for now.
