### ISSUE TITLE
docs: Support for non-proxied private registry

### ISSUE THREAD

**Issue by oldhamtj** [moby/moby#10972]
In some or many organisations the HTTP_PROXY is appropriate only for external registry access and may not function correctly for an internal private registry. The purely global nature of the proxy from the environment makes running a private registry problematic.
The code in registry.go for defining registry access could be made conditional through a new unproxied_registry flag - so instead of an unconditional
httpTransport := &http.Transport{
        DisableKeepAlives: true,
        Proxy:             http.ProxyFromEnvironment,
        TLSClientConfig:   &tlsConfig,
    }
the Proxy: could be conditional. This might be conditional based on an address map or other specification of registry addresses that should not be proxied even when the proxy is set in the environment.

It could be argued that this is working around broken internal proxies. This is a fair argument but it is not necessarily straightforward to modify proxy configuration in large organisations. It is also a network optimisation to use a private registry rather than use a proxy in many cases.

**Comment by jfrazelle** [comment]
we have this for the daemon https://github.com/docker/docker/pull/10748 @dmp42 @dmcgowan do you think this issue should be opened on the registry because it is registry specific

**Comment by dmp42** [comment]
@oldhamtj what happens if you use the `no_proxy` environment variable?

**Comment by oldhamtj** [comment]
Excellent, that's it sorted. Suggest minor doco change to point at proxy behaviour.

**Comment by dmp42** [comment]
@jfrazelle marking this as a documentation enhancement then?

**Comment by jfrazelle** [comment]
nice

**Comment by oldhamtj** [comment]
Yes please. Thanks for your support.

**Comment by DoraALin** [comment]
greets,
I think the a comment about NO_PROXY variable in http need to be appended to [https://docs.docker.com/registry/configuration/#http](url) . I am new here and would like to take this task as a start.
#dibs

**Comment by DoraALin** [comment]
get the location of registry.go wrong... I modify the location where comment needed.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/22778 was merged
