### ISSUE TITLE
Explain downloaded image and container sizes  in User Guide

### ISSUE THREAD

**Issue by moxiegirl** [moby/moby#11160]
From a user via docs feedback.

"How much disk space containers will take up. The registry doesn't appear to
have any indication and AFAICT one would need to visit several places to
get an estimate. Maybe I have missed some crucial point? I understand
how containers could be "lightweight" if a one was intended to be hosted
on the same OS/version I have on my desktop but if not then potentially
I'm looking a several gigs of download yes?"

https://docs.docker.com/userguide/dockerimages/ Has information  --- is the closests but this user was more about "predicting" the size prior to download.

**Comment by thaJeztah** [comment]
Predicting the size will probably depend on changes in Docker Hub, and can only be requested via support@docker.com (also see https://github.com/docker/docker/issues/7919).

Perhaps the docker client can query in advance which layers must be downloaded for an image and display the size, but then it should also first check if (some of) those layers are allready present locally.

In addition, pulling images currently isn't an "interactive" process, ie, there is no confirmation *before* the pull is started, perhaps an `--interactive` flag?

**Comment by moxiegirl** [comment]
Good points all.  I think this ticket may split into docs and functionality ticket.  I'm waiting to see if the user that asked about this comments on the issue.

**Comment by yangyuqian** [comment]
#dibs

**Comment by yangyuqian** [comment]
Hi @moxiegirl,

I've just submitted a [PR](https://github.com/docker/docker/pull/26470).

This is my very first PR for Docker and any suggestion is appreciated.

**Comment by yangyuqian** [comment]
Redo the closed PR 11160 in https://github.com/docker/docker.github.io/pull/408

**Comment by thaJeztah** [comment]
looks fixed by https://github.com/docker/docs/pull/408
