### ISSUE TITLE
Client sends wrong authorization header in search request

### ISSUE THREAD

**Issue by ghost** [moby/moby#11161]
# Context

I am using a private Docker registry together with an authentication proxy. That one has been set up by following the [nginx sample configuration](https://github.com/docker/docker-registry/blob/master/contrib/nginx/nginx_1-3-9.conf). The setup works fine so far.
# Problem Description

Now I issue a _docker search_ command after logging in. But the client does not set the HTTP header of the request properly:

```
Authorization: Basic Og==
```

The Docker client only writes the colon ":" in base64 encoding to the HTTP request header but skips the username and password part. So no valid authentication information is passed to the registry and thus the search request does not work.
# Workaround

The search works when authorization is disabled for those requests:

```
location /v1/search {
    auth_basic off;
    include docker-registry.conf;
}
```
# Environment

I am running an installation via boot2docker on my Mac:

```
h5:~ hs$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
