### ISSUE TITLE
Proposal: Improvements for creating images without Dockerfile

### ISSUE THREAD

**Issue by joelwurtz** [moby/moby#11205]
Hello,

Actually there is 2 way for creating images with Docker:
1. The popular Dockerfile
2. Creating a new container, make some changes and commit this container to an Image

For various reasons, I really don't like using a Dockerfile (this is not the topic of why, but i can comment more on this subject if you want) and I prefer to use the commit method.

However, using this workflow for long term and in a team has serious downsides: the history of an image is too light (see #9785 for example) and there is no possibility to have a diff between 2 images (only 2 containers atm).

Here are a bunch of propositions in order to improve this workflow:
## Commit message should be mandatory

On a new commit you will have to set a message of what you have changed, which can be empty. Having it mandatory will force people to set something, and we can hope that it will be something useful. (Do you imagine the crap in a repository if git commit would not require a message ?)
## Add a mandatory author information for a commit

A commit message specifies the what and/or how of the change. For collaboration we also need the who (mainly to make the author wear a dunce cap when his commit is stupid), for that purpose a commit, in docker, should require a name and an email of the commit author.

To not have too much information to enter at each commit, the docker client can use environnements variables to set the default author name and email.
## Add information to history output

A line, in docker history, should return the message, author name and author email of commit. (see also #9785)
## Diff between 2 images

History is great but not enough, when reviewing a commit, we also need to see which and how these files have been changed. For a start this diff can exactly be like a diff between 2 containers but it can also be improved:
### Binary (actual) diff

A diff between 2 binary files is not possible, so only the information about the status of the file (added/modified/deleted) should be show (like the current diff on containers).
### Textual diff

When the file is a text (like a configuration), it would be nice if the diff could show more information than the binary one, which lines has changed, before and after content, ... like a git diff
## Docker hub and repository integration

With all these information Docker Hub or any other image storage service would be able to show better insight of an image and gain trust from users using images created without Dockerfile.

**Comment by hansgru** [comment]
> .. i can comment more on this subject if you want ...

Please comment what's the problem with the Dockerfile, and if it has any missing features, why wouldn't it be better for fix those instead.

**Comment by joelwurtz** [comment]
> Please comment what's the problem with the Dockerfile, and if it has any missing features, why wouldn't it be better for fix those instead.

It's not a problem of missing features, but more a problem of having something that is build everytime.

Having a Dockerfile involve much more maintenance for my services, as if i run a Dockerfile of 2 years old i will not be sure that this will work again. (like having a wget to some url will maybe not work as the host will be down)

I know there is some workaround for this kind of problem, but using the second workflow really fix image: what is done is done and doesn't need to bo rebuild, this has also some downsides (as i will need to repeat the maintenance of the source image) but i think this a matter of user choice.

**Comment by thaJeztah** [comment]
@joelwurtz we're currently in the process of moving the "builder" (which is the part of Docker that handles building images from Dockerfiles) client-side, this will allow building custom implementations of the Dockerfile syntax or a custom builder; see https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

**Comment by AkihiroSuda** [comment]
Custom syntax can be now implemented with `# syntax = <BuildKit frontend image>` directive.
Closing.
