### ISSUE TITLE
docs: Add article describing how to migrate images and containers to another host

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#11238]
**Summary**: There is no documentation on "how to" migrate containers/images to another host
**Proposed solution**: write an article that describes how containers, images and their volumes can be migrated to a new/other host. The article should contain practical examples and limitations of the process. Possible alternatives/best practices can be considered to be included in the article.

---

This came up in another issue (see https://github.com/docker/docker/issues/10702#issuecomment-76508564); how can image, containers (and their volumes) be migrated to another host.

**Comment by LK4D4** [comment]
@thaJeztah ping

**Comment by AkihiroSuda** [comment]
What's the status of this issue?

I think image registry is the recommended way for transferring images.
No need to migrate containers when they are "cattles" 🐮

**Comment by thaJeztah** [comment]
I think we can close this here; otherwise have an issue in the docs repo /cc @mstanleyjones
