### ISSUE TITLE
Document running Docker on RaspberryPI

### ISSUE THREAD

**Issue by icecrime** [moby/moby#11580]
**Problem**

Document running Docker on RaspberryPI

**Solution**

Many blogs are out there, some of which are quite old, that talk about ways to get Docker running on a RaspberryPI.  We should put together better documentation in a central place on how to run Docker on various common OS distros used on RaspberryPI (raspbian, snappy ubuntu, etc.)

**Comment by thaJeztah** [comment]
@icecrime I think the article should mention that it is "experimental" and not officially supported (or has that changed?)

**Comment by aetherical** [comment]
I'd be happy to work on this one....

**Comment by thaJeztah** [comment]
@aetherical great! Make sure to mention `closes #11580` in the description of your pull request

**Comment by usultrared** [comment]
Guys, We have already worked out one way to deploy Docker in Raspberry Pi with Arm11

**Comment by alexellis** [comment]
I was going to contribute here but with #12519 it looks like it has been done already. Does this issue need to stay open?

**Comment by thaJeztah** [comment]
@alexellis good question; perhaps after we have official binaries for rPi

**Comment by alexellis** [comment]
I have a fair amount of experience using Docker with the Raspberry PI ARMv6 and ARMv7 chipset. Is there any need for a short document or jump off? Does #12519 cover what was wanted?

**Comment by alexellis** [comment]
I have around 22 tutorials on running Docker on the Raspberry Pi / ARM.

Is there any potential for a link-back or mention if we cannot agree on how to best write instructions for ARM/Pi in the official docs?

http://blog.alexellis.io/tag/raspberry-pi/

**Comment by thaJeztah** [comment]
Let me ping @mstanleyjones, she's on the docs team

**Comment by mstanleyjones** [comment]
We already have instructions for Raspbian but they are pretty old. If this is a goal, it would be nice to polish these and bring them up to date.

**Comment by AkihiroSuda** [comment]
As of 2020, there are a lot of blogs about installing Docker on Raspberry Pi, e.g. https://www.docker.com/blog/happy-pi-day-docker-raspberry-pi/
