### ISSUE TITLE
Feature Request:  CPU usage limits in MIPS

### ISSUE THREAD

**Issue by calh** [moby/moby#11647]
I posted [this as a comment](https://github.com/docker/swarm/issues/475#issuecomment-85102816) on a Swarm issue, but @bacongobbler suggested this should be posted as a feature request to the main docker app.  (Which I think would work better as a cluster-wide metric with Swarm)

I think it would be nice to specify an app's utilization in MIPS. Lets say you benchmark an app, and at 5 concurrent requests it uses 500MB of memory, and utilizes 50% of a CPU running at 8500 BogoMIPS. 

In production, if I wanted my application to scale up to 50 concurrent users, I'd fire off 5 containers, each with a limit of 1GB of memory and 8500 MIPS. (With some added wiggle room) I would know that my total application is worth 5GB of memory, and 42,500 MIPS. I could forecast and purchase hardware a lot easier that way too.

If you have a mixture of different speeds of machines, it's easier to distribute shares across a cluster. My app's requirement for 8500 MIPS might just be 1 CPU on one machine, or 2 CPUs on older hardware.

Save the arguments over bogomips for later though.  Maybe this could be FLOPS, or Hz, or... whatever.  If you could override the host's total available bogomips setting on the docker daemon command line, then it doesn't matter what the unit is.  Web ops has control over the ceiling for each host, and dev ops has control over requesting CPU utilization with a properly weighted metric.  

Whatever the chosen unit is, the main point is that it's a consistent value throughout the lifecycle of the container.  A static 0 - 1024 in cgroups isn't very helpful on the grand scheme of clustering.

Thanks for considering this!

**Comment by unclejack** [comment]
CPU shares can't be specified in MIPS/HZ/etc. Only cfs_quota can be used which can be set as a percentage of the CPU.

**Comment by calh** [comment]
What if it were calculated?  Say with the current 0 - 1024 CPU Shares, you could do something like:

`cpu_shares = ( app_mips / (total_mips * num_cpus) * 1024)`

**Comment by unclejack** [comment]
@calh That's not a hard limit, it's just a way to tell the scheduler "given a total of N shares, give this container X shares". It's more of a limit relative to other containers.

**Comment by calh** [comment]
Oh okay.  So, this just isn't possible to do then?

**Comment by unclejack** [comment]
@calh Something like this will be possile once #10736 or an equivalent PR gets merged, but this needs some further discussion. I think we need to leave this issue open so that something like this can be discussed, but the implementation is most likely not going to be done with CPU shares.

**Comment by calh** [comment]
Thanks for keeping it open for discussion!  No matter the chosen unit, I think it's a worthwhile feature for capacity planning on larger architectures.  It would be nice to run an app on disparate host hardware and have well defined units for scalability.

For example, I have a monster (SuperMicro 5806B-TRF)[http://www.supermicro.com/products/system/5U/5086/SYS-5086B-TRF.cfm] with 160 cores, and some Dell blades with 16 cores, and some other old hardware with 4 cores.  CPU shares relative to other containers doesn't help me much there.  But if I knew that an app had a requirement for a specific MIPS threshold, I'd know which hosts would be suitable for the container.

**Comment by Piste** [comment]
+kind/feature

**Comment by yixingjia** [comment]
Do we have plan when will we have this feature?

**Comment by cpuguy83** [comment]
@yixingjia You can use the CFS quota to limit CPU usage. There are a couple of parameters you can use to fine-tune this, or you can use the `--cpus` flag to have Docker do the calculation... If you want to allow a container to use 1.5 CPUs then you'd do `--cpus 1.5` and Docker will handle the calculation for the various cgroup settings (cfs_period and cpu_quota).

You can also pin a container to a specific core (or set of cores) with `--cpuset-cpus`.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
