### ISSUE TITLE
Allow user to search multiple registries at once

### ISSUE THREAD

**Issue by miminar** [moby/moby#11818]
This is based on issue #11815. And together with _pull_ (issue #11816) and _push_ proposals (issue #11817) supersedes #8329.
### Use case

As a regular Docker user working with several private and corporate registries, I'd like to be able to search them all at once. Docker daemon shall accept a list of registries that shall be queried during searches.

So when I issue:

```
$ docker search ubuntu
```

it'd show results gathered from all the registries given. I'd also expect Docker to print source index name for each repository found e.g.:

```
NAME                                DESCRIPTION                                     STAR
docker.io/ubuntu                    Official Ubuntu base image                      1227
docker.io/dockerfile/ubuntu         Trusted automated Ubuntu (http://www.ubunt...   40
docker.io/tutum/ubuntu              Ubuntu image with SSH access. For the root...   14
docker.io/tleyden5iwx/ubuntu-cuda   Ubuntu 14.04 with CUDA drivers pre-installed    1
docker.io/partlab/ubuntu            Simple Ubuntu docker images.                    0
registry.my.org/xavier/ubuntu                                                       2
registry.my.org/custom/ubuntu                                                       0
registry.my.org/my/ubuntu                                                           0
```

To aid legibility, Docker should sort the results primarily by index name.
### Requirements
- Docker daemon accepts a list of registries used for searching.
- Docker daemon queries all registries given.
- Docker doesn't budge when one or more registries is inaccessible.
- Output of search command shows source index name.
- Results are sorted by index name.
### Proposal

This is based on configuration schema outlined in #11815. It uses the same default list of registries as a pull proposal (issue #11816). Here they are being searched 

```
general:
    # Default registries used during search.
    default_registries:
        - redhat
        - public
```

In this case the order doesn't matter. They could be searched in parallel.

**Comment by dmp42** [comment]
Definitely interesting.

Brainstorming on search for v2 has just started so this is definitely something to consider.
I'm linking to https://github.com/docker/distribution/issues/206 to track this.

**Comment by LK4D4** [comment]
@stevvooe do you know if this will be implemented?

**Comment by stevvooe** [comment]
@LK4D4 There are no plans for this. We really need to have a proposal for a search API that supports this.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and there's no plans to provide this.
