### ISSUE TITLE
Useless error message if kernel has CONFIG_VETH=n

### ISSUE THREAD

**Issue by ojab** [moby/moby#11889]
Description of problem:
All containers fail to start with `[8] System error: operation not supported`. Client output:

```
$ docker -l debug run  -i -t centos /bin/bash
DEBU[0036] End of CmdRun(), Waiting for hijack to finish.
                                                          DEBU[0036] [hijack] End of stdout
                                                                                                                  DEBU[0036] Error receiveStdout: read unix /var/run/docker.sock: use of closed network connection
FATA[0036] Error response from daemon: Cannot start container 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566: [8] System error: operation not supported
$
```

Daemon output:

```
…
INFO[0037] POST /v1.18/containers/2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566/start
INFO[0037] +job start(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566)
INFO[0037] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]
INFO[0037] +job allocate_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566)
INFO[0037] -job allocate_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566) OK
INFO[0037] +job log(start, 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566, centos:latest)
INFO[0037] -job log(start, 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566, centos:latest) OK
WARN[0037] signal: killed
DEBU[0037] attach: stdout: end
DEBU[0037] attach: stderr: end
DEBU[0037] attach: stdin: end
INFO[0037] +job release_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566)
INFO[0037] -job release_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566) OK
INFO[0037] -job attach(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566) OK
ERRO[0037] use of closed network connection
ERRO[0037] use of closed network connection
INFO[0037] +job release_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566)
INFO[0037] -job release_interface(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566) OK
INFO[0037] +job log(die, 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566, centos:latest)
INFO[0037] -job log(die, 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566, centos:latest) OK
INFO[0037] -job start(2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566) ERR: Cannot start container 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566: [8] System error: operation not supported
ERRO[0037] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566: [8] System error: operation not supported
ERRO[0037] HTTP Error: statusCode=500 Cannot start container 2f5332dbfa4265e454b668f69e0d09953018b21c2e763d766268863bf11df566: [8] System error: operation not supported
DEBU[0037] Closing buffered stdin pipe
```

`docker version`:

```
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 61069d8
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 61069d8
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 2
Images: 3
Storage Driver: vfs
Execution Driver: native-0.2
Kernel Version: 3.19.3-ojab
Operating System: <unknown>
CPUs: 4
Total Memory: 7.792 GiB
Name: ojab.ru
ID: 7IC6:XLGR:PK6I:JWM4:A7F4:6ZG2:RX2I:MKIR:VHCU:RWKY:YL3Q:FP5P
Debug mode (server): true
Debug mode (client): true
File Descriptors: 10
Goroutines: 15
System Time: Sat Mar 28 20:49:48 MSK 2015
EventsListeners: 0
Init SHA1: f3cda244f28a77e8d2e91ad29cf4ebb5a381ce5f
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

Swap support is disabled in kernel config

`uname -a`:
`Linux ojab.ru 3.19.3-ojab #60 SMP Fri Mar 27 21:23:22 MSK 2015 x86_64 GNU/Linux` (vanilla kernel)

Environment details (AWS, VirtualBox, physical, etc.):
bare metal

How reproducible:
100%

Steps to Reproduce:
1. Start any container

Actual Results:
Container won't start with `[8] System error: operation not supported`

Expected Results:
Container starts

Additional info:
Related strace output parts [here](https://gist.githubusercontent.com/ojab/2df22264532f65f720c1/raw/2db36028979256c5a47af4aa57a813fdf28de778/gistfile1.txt) and [here](https://gist.githubusercontent.com/ojab/6c279fd44148465950ba/raw/ff5807ed3c4fd1fb7eb5cc2eace2afd80cf87b0d/gistfile1.txt).

**Comment by ojab** [comment]
The same happens with docker-1.5.0.

**Comment by ankushagarwal** [comment]
I know you have included `uname -a`, but what operating system is this? I don't recognize this (`ojab.ru`).

**Comment by ojab** [comment]
It's Linux From Scratch, the issue is reproducible only in this host.

**Comment by ojab** [comment]
…and netlink debugging tells me that docker wants CONFIG_VETH, viva la nlmon!

**Comment by coolljt0725** [comment]
docker use veth device to link container to bridge, you have to has `CONFIG_VETH=y` unless you don't use `--net=bridge` which is default. Maybe, run container with  `--net=none` or `--net=host` will not case this problem with `CONFIG_VETH=n`

**Comment by chenhanxiao** [comment]
@ojab 
FYI:
We already checked `VETH` flags in contrib/check-config.sh

**Comment by ojab** [comment]
Yeah, but there is no way to learn about contrib/check-config.sh (AFAIR there is no hint in docs etc).

**Comment by thaJeztah** [comment]
@ojab were you able to resolve the issue with the hints in https://github.com/docker/docker/issues/11889#issuecomment-87660553 (using `CONFIG_VETH=y`)?

Am I right that what's needed is;

- Enhance the error response returned by the daemon to include some reference to `VETH` (If possible)
- Add a reference to the `contrib/check-config.sh` to the documentation?

Does that summarise it correctly?

**Comment by ojab** [comment]
Actually --net=none and --net=host fails with the same error (haven't debugged netlink in that cases though).
Your summary is perfectly accurate.

**Comment by rlpowell** [comment]
I'm getting the same error, but CONFIG_VETH=m and the module is loaded.  I've
narrowed it down to something to do with volume mounts:

    rlpowell@ip-10-0-5-208> sudo docker run --name btm -d -t -v /data/cytobank:/data/cytobank:rw 10.0.1.16:5000/cytoweb-btm /sbin/docker.init
    4a787b8c6e1cc2502ec8138898bd22926a0451270ca8bf2d34d9948e5008f1c4
    FATA[0000] Error response from daemon: Cannot start container 4a787b8c6e1cc2502ec8138898bd22926a0451270ca8bf2d34d9948e5008f1c4: [8] System error: operation not supported
    rlpowell@ip-10-0-5-208> sudo docker rm btm
    btm
    rlpowell@ip-10-0-5-208> sudo docker run --name btm -d -t -v /tmp:/tmp:rw 10.0.1.16:5000/cytoweb-btm /sbin/docker.init
    6ef0f848ff2818681e4b85819889d9689f5cc355df7543954a09753861125faa
    rlpowell@ip-10-0-5-208>

The difference is that /data/cytobank is NFS mounted.  This always worked
before.

This is reliably reproducible on my Fedora 21 AWS instances with docker 1.6.0.
I doubt very much it has anything to do with VETH.  Making SELinux permissive
does not help.

    rlpowell@ip-10-0-5-208> sudo docker version
    Client version: 1.6.0
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 350a636/1.6.0
    OS/Arch (client): linux/amd64
    Server version: 1.6.0
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 350a636/1.6.0
    OS/Arch (server): linux/amd64


    rlpowell@ip-10-0-5-208> sudo docker info
    Containers: 3
    Images: 8
    Storage Driver: devicemapper
     Pool Name: docker-202:1-384909-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file:
     Metadata file:
     Data Space Used: 4.966 GB
     Data Space Total: 107.4 GB
     Data Space Available: 102.4 GB
     Metadata Space Used: 3.703 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.144 GB
     Udev Sync Supported: true
     Library Version: 1.02.93 (2015-01-30)
    Execution Driver: native-0.2
    Kernel Version: 4.0.5-200.fc21.x86_64
    Operating System: Fedora 21 (Twenty One)
    CPUs: 8
    Total Memory: 14.69 GiB
    Name: ip-10-0-5-208
    ID: BOHI:ZCZP:63NL:MFOP:GNUG:NPQY:UB3N:X5LS:WHVR:VZWH:DH5Z:ZAB7
    rlpowell@ip-10-0-5-208>

**Comment by ojab** [comment]
Is this reproducible on clean Fedora 21 AWS install? If so -- give me AMI id, I'll try to debug it this week[end].

**Comment by rlpowell** [comment]
Here's strace: https://gist.github.com/56268cb57c10eeaa779b

**Comment by rlpowell** [comment]
I don't know for sure if it's reproducible on a clean install.  I mean, you'd need an NFS mount, for one thing.  But the base AMI I'm using is ami-c3d43b87 in us-west-1 ; the name is Fedora-Cloud-Base-21-20150506.x86_64-us-west-1-HVM-gp2-0

**Comment by rlpowell** [comment]
So interestingly there is exactly one ENOTSUPP in strace:

    [pid 13152] stat("/data/cytobank", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 13152] stat("/var/lib/docker/devicemapper/mnt/f9651faf5cdcefa0bd4ba7aa79cb42c01619649eaecdd132a2355b950b7f6c7e/rootfs/data/cytobank", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 13153] <... select resumed> )      = 0 (Timeout)
    [pid 13152] mount("/data/cytobank", "/var/lib/docker/devicemapper/mnt/f9651faf5cdcefa0bd4ba7aa79cb42c01619649eaecdd132a2355b950b7f6c7e/rootfs/data/cytobank", 0xc20804dcd0, MS_BIND|MS_REC, 0xc2080c05c0) = 0
    [pid 13152] lstat("/data/cytobank",  <unfinished ...>
    [pid 13153] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
    [pid 13152] <... lstat resumed> {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 13152] lsetxattr("/data/cytobank", "security.selinux", "system_u:object_r:svirt_sandbox_file_t:s0:c594,c755", 51, 0) = -1 EOPNOTSUPP (Operation not supported)
    [pid 13153] <... select resumed> )      = 0 (Timeout)
    [pid 13152] read(3, "", 512)            = 0
    [pid 13153] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
    [pid 13152] open("/etc/localtime", O_RDONLY) = 6
    [pid 13152] read(6,  <unfinished ...>
    [pid 13153] <... select resumed> )      = 0 (Timeout)

**Comment by rlpowell** [comment]
So yeah, lsetxattr is absolutely guaranteed to fail over NFS.  This was working in 1.5.0.  Ironically, I suspect another bug I submitted is responsible for that lsetxattr.  Can we make it warn instead of fail?

**Comment by Pastafarianist** [comment]
Getting the same on a custom Debian Jessie ARM [from here](https://github.com/tomuta/debian-mini-odroid-c1).

**Comment by bdonnahue** [comment]
Hello. I ran into this issue over the weekend. Luckily I had this working on a previous release.
I can confirm the issue disappears when running docker-1.3.2-4.el7.centos.
I have confirmed it is present in:
1.6.0-11.0.1.el7.centos
1.6.2-14.el7.centos

Im not familiar enough with github or blame or the project to draw a conclusion but hope this helps.

**Comment by Pastafarianist** [comment]
Downgrading doesn't help me, unfortunately. I tried 1.3.2, but the error message is the same.

Created a separate issue [here](https://github.com/docker/docker/issues/14673).

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
