### ISSUE TITLE
Failed to build Debian squeeze images for architectures other than i386 and amd64 by default

### ISSUE THREAD

**Issue by vicamo** [moby/moby#11919]
Failed with console error message:

```
W: Failed to fetch http://ftp.us.debian.org/debian/dists/squeeze-lts/Release  Unable to find expected entry  main/binary-mips/Packages in Meta-index file (malformed Release file?)

E: Some index files failed to download, they have been ignored, or old ones used instead.
```

Debian LTS supports only amd64 and i386 architectures. See https://wiki.debian.org/LTS/Using . Since **DONT_TOUCH_SOURCES_LIST** is not set by default, _contrib/mkimage/debootstrap_ tries to replace `squeeze` with `squeeze-lts` and causes the problem.

**Comment by cpuguy83** [comment]
ping @tianon

**Comment by vdemeester** [comment]
Given the activity on this issues, I'll close it as I think it's either not needed or already done. But if you think otherwise, feel free to discuss it and we'll re-open 😉
