### ISSUE TITLE
qcow2 based graphdriver for docker

### ISSUE THREAD

**Issue by bohai** [moby/moby#11948]
My idea is to implement a graphdriver based on qcow2 files.  Every layer of the image is a qcow2 file. 
Use qemu-nbd or other tools to make the qcow2 files looks like a block device, and then used them for the docker container.

How  do you think about this idea? Any advice is welcome.
##### About qcow2:

The QCOW image format is one of the disk image formats supported by the QEMU processor emulator. It is a representation of a fixed size block device in a file.Benefits it offers over using raw dump representation include:
- Smaller file size, even on filesystems which don't support holes (i.e. sparse files)
- Copy-on-write support, where the image only represents changes made to an underlying disk image
- Snapshot support, where the image can contain multiple snapshots of the images history
- Optional zlib based compression
- Optional AES encryption  

https://people.gnome.org/~markmc/qcow-image-format.html

**Comment by gdm85** [comment]
Interesting! Also on the interoperability side. I think its implementation would share at least some similarities with the devmapper driver.

**Comment by thaJeztah** [comment]
It does sound interesting. How's platform support? Is it widespread, or targeted at specific distro's?

**Comment by Peter--wang** [comment]
I think it is indeed a good idea.
With qemu and qcow2, we can run containers on shared storages, for instance, NAS or SAN. 
And qcow2 is being widely used in kvm which is one of the most famous virtualization hypervisor.
Thirdly, qcow2 already has all the features that docker needs.

**Comment by thaJeztah** [comment]
>And qcow2 is being widely used in kvm which is one of the most famous virtualization hypervisor.

Good to hear; I wasn't familiar with it (but that's me)

> we can run containers on shared storages, for instance, NAS or SAN. 

It actually surprised me that (so far) I hadn't seen *any* NAS manufacturing stepping into Docker; to me it sounded like a "match made in heaven" to deploy/distribute "apps" running on NAS (compared to the package managers currently used)

...but that's really off-topic for this discussion

**Comment by Peter--wang** [comment]
>to me it sounded like a "match made in heaven" to deploy/distribute "apps" running on NAS (compared to the package managers currently used)
Yes, it is what I mean. We can use NAS as a backend storage.

sorry for my poor English...

**Comment by sunyc** [comment]
qcow2 is mounted through  NBD kernel module (which support a large array of imaging format , including raw, vdi, vmdk etc etc). I think this driver should just be called as  nbd graph driver.   using what format is left as a execerise for the readers.

**Comment by sunyc** [comment]
qcow2 is mounted through  NBD kernel module (which support a large array
of imaging format , including raw, vdi, vmdk etc etc). I think this driver
should just be called as  nbd graph driver.   using what format is left as
a execerise for the readers.

**Comment by nixun** [comment]
quite good idea, it can solve the page cache problem as well as the disk space waste problem in one solution.

**Comment by thefallentree** [comment]
+ @vangie

**Comment by crosbymichael** [comment]
i was talking to a few people about doing this.  looks really cool.  someone should try it ;)

**Comment by bohai** [comment]
@thaJeztah   Yes, i think it's possible to support more image formats using for virtual machine now.
@crosbymichael @thaJeztah  and others,  I'm  so happy to see your supports.

**Comment by xuxinkun** [comment]
I want to have a try. But I am not familiar with qcow2. What I know to mount qcow2 is using guest-mount tool. How about using this tool?

**Comment by Peter--wang** [comment]
I think it's OK

**Comment by xuxinkun** [comment]
@Peter--wang I have tested guestmount. Though I don't know how it works, but I see that when mount a qcow2 image with guestmount, system will boot a kvm process. I guess guestmount make use of kvm to mount the qcow2 image. I don't know whether this will have effect on performance of docker. So, I prefer to use nbd to mount image. I am writing code now. Several days after, I will provide it and ask for review.

**Comment by thefallentree** [comment]
we implemented a custom daemon mounting through NBD, and we met a few problems, it seems that NBD (at least in 3.13 - 3.16 ) have some stability issues that can cause lockup etc.

Another choice would be  libguestfs ,which also support doing the samething (through FUSE) .

**Comment by wulibin163** [comment]
I try it success, using qemu-nbd。But the perfermence is so poor。So I use  qemu source（through fuse）

**Comment by AkihiroSuda** [comment]
I'm closing this, but if anybody still wants this, feel free to open a new issue with updated information .
