### ISSUE TITLE
Change number of images's format from docker info 

### ISSUE THREAD

**Issue by Mashimiao** [moby/moby#12217]
Hello everyone,
When I use `docker info`, it returns the total number of images.
Usually, We just use top images to create containers, we may even don't know what the intermediate images can do.
So, I want change `docker info` just return number of top images.
WDYT?

**Comment by ahmetalpbalkan** [comment]
@Mashimiao it would be breaking others as the current contract says: `/info` endpoint of Docker Remote API (what's reported as `Containers:` to you) will return number of all containers. Could you please elaborate why do you want to get this data?

Also, an image that looks like "top image" can be an intermediate image later on. So it's not really a solid concept either.

**Comment by cpuguy83** [comment]
Yes, there's really no such thing as an intermediate image.

**Comment by Mashimiao** [comment]
Hi @ahmetalpbalkan and @cpuguy83,
I agree there is not really a solid concept about intermediate image.
In my opinion, intermediate image  means it it not needed and "top image" means it can be used directly.
Sometimes we need count how many images we have, which we can use to create containers directlly. we have to use command "docker images | wc -l".
If "docer info" can directly supply this data, I think this will be very convenient.
Thanks.

**Comment by cpuguy83** [comment]
@Mashimiao The thing is, _any_ image can be used directly.
We do have a concept of `dangling` images, which are images that aren't part of the makeup of any tagged image. But I'm also not sure this information would be particularly useful in `docker info`.

**Comment by Mashimiao** [comment]
@cpuguy83 , 
That's true every images can be used directly. But usually if we want to get the final image, we have to create several intermediate images to based on. Though the intermediate images can be used directlly, from the aspect of application, we look at them as unuseful and can't be used directlly.
WDYT?

And I know about dangling images, but I think it's different from what I want to get.
Dangling images contains untagged top images and intermediate images.

**Comment by AkihiroSuda** [comment]
For compatibility, we can no longer change this .
