### ISSUE TITLE
Document the --read-only flag in the Security page

### ISSUE THREAD

**Issue by moxiegirl** [moby/moby#12656]
https://github.com/docker/docker/blob/master/docs/sources/articles/security.md

Should mention --read-only on container here.

**Comment by bettyjunod** [comment]
We should update the page with some of content from the "intro to container security" paper, the read only container flag and some of the 1.6 features like ulimits, user namescape.. #dibs

**Comment by vdemeester** [comment]
Quick note, the link is probably https://github.com/docker/docker/blob/master/docs/articles/security.md now :blush:.

**Comment by LK4D4** [comment]
ping @thaJeztah @vdemeester

**Comment by thaJeztah** [comment]
This page moved to the docs repo; https://github.com/docker/docker.github.io/blob/374d240c6a1ed1a4baa2d1d22ac7314d1f6943cd/engine/security/security.md. Created a new issue there; https://github.com/docker/docker.github.io/issues/6526
