### ISSUE TITLE
Should be able to tell the difference between a container from a docker build or not

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#12725]
I would like to be able to tell the difference if a container was created by a user or by a Docker build.  Would anybody be opposed to adding a label on the container indicating it is from a build?

**Comment by jfrazelle** [comment]
seems reasonable to me

**Comment by ripcurld00d** [comment]
#dibs

**Comment by ripcurld00d** [comment]
Hi @ibuildthecloud,
When you say "created by a user" do you mean whether it was created by running `docker build` or not?

What will happen when the user will run docker commit, should the label be removed?

Thanks.
