### ISSUE TITLE
Docker humanizes/truncates several fields server side

### ISSUE THREAD

**Issue by aes** [moby/moby#12792]
This kind of defeats the purpose of having an API in the first place and is completely unnecessary since the client and the server are typically the same binary.

**Comment by runcom** [comment]
@aes could you be a bit more specific and tell us which fields you are referring to?

**Comment by aes** [comment]
`GET /v1.18/containers/json?all=1 HTTP/1.1` gives me `"Status":"Up 2 minutes"`, for example.

`GET /v1.18/images/json?all=1 HTTP/1.1` gives me full images id:s, correct sizes, and created is in unix seconds. I don't recall what it looked like before, but I'm pretty sure some of these fields were truncated and/or mangled earlier.

The API docs for 1.17 still show these truncated things:
```json
{
   "Id": "8dfafdbc3a40",
   "Image": "ubuntu:latest",
   "Command": "echo 1",
   "Created": 1367854155,
   "Status": "Exit 0",
   "Ports": [{"PrivatePort": 2222, "PublicPort": 3333, "Type": "tcp"}],
   "SizeRw": 12288,
   "SizeRootFs": 0
}
```

Perhaps status is the last remaining truncation? If so, could we have it split into status and since when?

**Comment by LK4D4** [comment]
I'm not sure what should be done here. Probably we need to create another issue with a proposal for `running` or `started` field.
ping @thaJeztah

**Comment by thaJeztah** [comment]
For the status, this was duplicated by;

- https://github.com/moby/moby/issues/18962

Which was fixed in;

- https://github.com/moby/moby/pull/18966


I think we can close this one for now (although there may be some other fields that could use a better format)
