### ISSUE TITLE
reverse mount read-only volume

### ISSUE THREAD

**Issue by Kallin** [moby/moby#12853]
It would be great to have a native, standard way to mount a folder from within a docker container to the host, perhaps in a read-only mode.

The scenario I'm thinking about ( and currently struggling with ) is how to have my development tools see the libraries within a container (ruby gems from a bundle, js/css from a bower install, node from npm, etc.). There's a stackoverflow where someone else has this issue here, http://stackoverflow.com/questions/28083920/how-to-mount-a-directory-in-the-docker-container-to-the-host . 

Personally I like using a GUI IDE that will index all the libraries my project uses, but I imagine the same thing would be useful for anyone using ctags w/ VIM etc. It's really nice to have a docker project that contains none of the libraries required to run it, as all libraries are isolated in the container. However, we still need a way to browse the libraries of the project, and in the case of docker, I guess that means sharing certain folders out of the container and back into the host, and I don't see a straightforward idiomatic solution to this as of yet.

**Comment by radriaanse** [comment]
I'm interested in this as well, I know that it maybe isn't a "best practice" but would be very nice to have for some reasons, like the one @Kallin describes would also be my biggest use case.
Any suggestions on how to accomplish this? Or can someone explain why this isn't implemented?

**Comment by cpuguy83** [comment]
If you have access to the host you can certainly mount whatever you want, the filesystems are all there in docker root, and `docker inspect` even provides details about the container's fs from the graph driver.
You can now (on master, and soon 1.8) stat paths from the container FS via the API.

I think beyond this it is best left to external tooling.

**Comment by Kallin** [comment]
@cpuguy83 
I'm not sure what you mean by 'mount whatever you want'. I know how to mount folders from host to container, but what about the reverse? IE, I have a folder in the container I want to mount to a folder that doesn't exist on the host. When I've tried this, it ends up taking the empty folder from the host and pushing that to the container, thus erasing the data in the container. I'm interested in letting the host read the contents of the container as though it's part of the host's filesystem.

**Comment by cpuguy83** [comment]
@Kallin from the host: `mount --bind /var/lib/docker/<graphdriver path>/<container id>/<path in container> </path/on/host>`

**Comment by Kallin** [comment]
Thanks @cpuguy83, I'll give that a shot, and hopefully this is useful reference to anyone else trying to pull off something similar.

**Comment by nioncode** [comment]
I have created a script for that: https://gist.github.com/nioncode/fff8c92eb3fbe1ee6e2b
It mounts all volumes from a given container to a user supplied mount point.

**Comment by presho-anna** [comment]
@cpuguy83 I'm trying to run the command from the mount method you suggested, but it does not work. Error "mount: special device <path> does not exist." Could you elaborate on what you mean by the graphdriver path?

**Comment by cpuguy83** [comment]
@presho-anna graphdriver path is the path where the container's FS is stored by the storage (aka graph) driver... typically somewhere in /var/lib/docker.

Also note that you can now (in master) also specify mount propagation for volumes (shared, rshared, private, slave, rslave).
This would allow you to mount things in the container and have that mount propagated to the host
