### ISSUE TITLE
/etc/hosts does not contain IPv6 addresses (of linked containers)

### ISSUE THREAD

**Issue by TimWolla** [moby/moby#13228]
Description of problem: The `/etc/hosts` inside a container does not contain the IPv6 addresses of the container itself and linked containers.

`docker version`:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 0
Images: 65
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 2
Total Memory: 3.84 GiB
Name: example.com
ID: *snip*
WARNING: No memory limit support
WARNING: No swap limit support
```

`uname -a`:

```
Linux example.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): Bare metal server running Debian Jessie w/ systemd

How reproducible: Always

Steps to Reproduce:
1. `docker run -it --rm -p 6379:6379 --name redis redis`
2. `docker run -it --rm --link redis:redis debian cat /etc/hosts`

Actual Results:

```
172.17.0.4  fea75d4d8cc1
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.3  redis bc96986c14f3
```

Expected Results:

```
172.17.0.4  fea75d4d8cc1
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.3  redis bc96986c14f3
2001:db8:1234:5678:1337:242:ac11:1 redis bc96986c14f3
```

Additional info: Docker is running with `--icc=false --ipv6 --fixed-cidr-v6="2001:db8:1234:5678:1337::/80"`

**Comment by vdemeester** [comment]
#dibs for @MalteJ (so we can see somebody's working on it ;))

**Comment by lanwen** [comment]
Hello, is there any workaround for it?

**Comment by aboch** [comment]
@MalteJ Are you interested in porting your change to libnetwork ?
This feature is still not provided.

**Comment by MalteJ** [comment]
@aboch unfortunately I have no time at the moment.
Feel free to fork and port :wink:

**Comment by lanwen** [comment]
Can it be resolved with #19198?

**Comment by thaJeztah** [comment]
@lanwen `--link` on the default (bridge) network still uses `/etc/hosts`?

**Comment by lanwen** [comment]
It seems so by default.

**Comment by JonasT** [comment]
Any chance this will be fixed soon? (since it doesn't seem to be fixed for the default (bridge) network as per the comments above) It's just a detail thing but it is one of the last remaining issues that makes using IPv6 with docker annoying, so it would be neat to see it addressed eventually.
