### ISSUE TITLE
docker pull no have checksum file

### ISSUE THREAD

**Issue by blackfader** [moby/moby#13245]
docker pull image

it is not file "checksum" in /var/lib/docker/graph/layer.id。

my scene is ：

I have a machine ， ”docker in docker “ ， every docker in charge of “docker build”。

so ， I build a image in “docker build container one” ， and push to registry success。

in "docker in docker container two", I pull this image , and rebuild image by Dockerfile .

it will push all image layers, from 0 to last . 

becasue , "docker in docker container two" , pull image , it is not "checksum" file , so , when docker push, docker client will repush image layer , and calculate digst , rewrite checksum.

So, i think when i docker pull image, it can save this image layer "checksum" file . 

```
[root@6cb4047675ad files-2]# docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 1b09ac5
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 1b09ac5
OS/Arch (server): linux/amd64
[root@6cb4047675ad files-2]# docker info
Containers: 0
Images: 20
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.12.35-100.el6.x86_64
Operating System: <unknown> (containerized)
CPUs: 24
Total Memory: 63.01 GiB
Name: 6cb4047675ad
ID: DC22:7RXB:BZFM:SYPE:XBVK:TYT6:GLBE:GZVS:KHOF:TOU2:DDXX:HIC
```

**Comment by blackfader** [comment]
@thaJeztah “docker pull no have checksum file ” I think it is docker client's problem

**Comment by thaJeztah** [comment]
@blackfader we generally add a "distribution" label for issues related to images as well, perhaps it's not the right one here, we'll see :)

**Comment by thaJeztah** [comment]
Looks like this issue went stale, and lots of things changed since Docker 1.7, including the move to a [content-addressable store](https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration) in [Docker 1.10](https://github.com/moby/moby/releases/tag/v1.10.0)

I'll close this issue because of the above, but feel free to open a new issue with details and reproduction-steps if you think this is still current
