### ISSUE TITLE
add more filters to docker ps [feature request]

### ISSUE THREAD

**Issue by dhrp** [moby/moby#13365]
For day-to-day use and simple scripting purposes It'd be great if the --filter function was extended with filters on more columns.

Specifically:

```
$ docker ps --filter image=myname/test 
```

Would be great so we can kill all our tests in one go like so:

```
$ docker ps --filter image=myname/test -q | xargs docker rm -f
```

This is helpful specifically in this combination because I want only image id's to be returned, and |grep thus doesn't work.

Other filters that would make sense to me:

_For images_
- Repository (with tag)
- Age? (--filter agemore=4h --filter ageless=2w)

_For containers_
- Image (with tag)
- Name (this is implemented by the way https://github.com/docker/docker/issues/10897, but undocumented)
- Age? (as above)
- Status (running, exited, etc)

**references**
I found this ticket: https://github.com/docker/docker/pull/11904 which describes something that sounds similar but (I think) is actually for the bash completion (only).

**Comment by phemmer** [comment]
Just as an fyi, you can do this with `awk`:

    docker ps | awk '$2 == "myname/test" { print $1 }' | xargs docker rm -f

**Comment by runcom** [comment]
@dhrp is the new docker ps --filter option with templates fixing this?

**Comment by vdemeester** [comment]
I think we are close to fixing it. Almost all of them are implemented. The only thing I see that could be nice to have is a *invert* mechanism for filters (like `!=` or something).

**Comment by dhrp** [comment]
@vdemeester, Oh, interesting. I was trying to look at the documentation changes to understand what had actually changed, and could not understand at first. 

-- the main reason being that the name of this filter is 'ancestor', (as @tiborvass has suggested). My main request would be that we add to the documentation that the ancestor filter really is 'by image'.

**Comment by slaupster** [comment]
+1 for filter inverter

**Comment by alias1** [comment]
Sort of related to this: it would be nice to be able to filter on an exact name.

Eg. `--filter name="foo"` (or other syntax) matches only `foo` not `food`, `fool`, etc

**Comment by twbecker** [comment]
Some sort of age/time based filter is desperately needed. Use case would be to list containers that have been running more than 24hours.

**Comment by thaJeztah** [comment]
Many new filters have been added since this request was opened (https://docs.docker.com/engine/reference/commandline/ps/#filtering), and https://github.com/moby/moby/issues/13533 is tracking negative filters, so I'll go ahead and close this one.

If there's a specific filter you're looking for, please open a new feature request with details 👍
