### ISSUE TITLE
Add a quiet option to docker pull

### ISSUE THREAD

**Issue by eburnette** [moby/moby#13588]
Docker pull is pretty noisy about checking and downloading images. It would be nice to have an option such as --quiet to suppress all that output. 

This is exacerbated by #13331 which requires us to run docker pull before every docker run.

**Comment by bradmccormack** [comment]
How do I claim this issue please?

It looks like a beginner issue task. I'm only just following guides now to set up building docker and i'm working through docker inception now.

Having a cursory look ( I know ZERO about docker codebase atm) it looks like it might be a matter of checking to make sure --quiet has been specified in the variadic function here https://github.com/docker/docker/blob/master/api/client/pull.go#L17   (args)  and then suppressing output accordingly at https://github.com/docker/docker/blob/master/api/client/pull.go#L45 by specifying nil for the  io.Writer arg.

How does one claim issues?

Cheers

**Comment by bradmccormack** [comment]
#dibs

**Comment by oryband** [comment]
:+1:

**Comment by thaJeztah** [comment]
@eburnette just reading up, do you think this is a duplicate(-ish) of https://github.com/docker/docker/issues/3694?

**Comment by eburnette** [comment]
@thaJeztah Fixing #3694 would be one solution yes.

**Comment by yegor256** [comment]
+1

**Comment by shakefu** [comment]
+1

**Comment by tdensmore** [comment]
+1

**Comment by pnathan** [comment]
+1  - a --hush mode would be nice... in automation, I only want to see errors, basically.

**Comment by steinnes** [comment]
+1

**Comment by thaJeztah** [comment]
@steinnes @pnathan IIUC, https://github.com/docker/docker/pull/17924 should bring improvements and be more quiet in scripts, per https://github.com/docker/docker/issues/3694#issuecomment-167888577 this should be improved in 1.10

**Comment by HariSekhon** [comment]
+1 👍 

This is actually causing my builds to fail in my online CI now because of all the very verbose docker pull output assuming it's an interactive terminal and the job ends up detecting too much output and assumes it's recurring exceptions and terminates the build :(

**Comment by igormoochnick** [comment]
+1
terraform output goes crazy

**Comment by dgtlmoon** [comment]
+1

**Comment by conf** [comment]
For everybody struggling with enormous output from `docker pull` in Jenkins logs, you can use the following workaround:
```bash
docker pull <image> | cat
```
Just pipe the output of `docker pull` to some other program like `cat` that will tell `docker pull` that stdout is not a tty and makes it switch to a non-interactive mode and greatly reduce output size. 

![](https://cl.ly/2S3n2G3k3y04/Screen%20Recording%202016-07-13%20at%2001.03%20PM.gif)

**Comment by docwhat** [comment]
The `docker pull <image> | cat` solution doesn't work for me via Jenkins Pipeline builds... I wish it did.  :-(

**Comment by justincormack** [comment]
I think only docker since 1.12 looks to see if the output is a tty...

**Comment by docwhat** [comment]
> I think only docker since 1.12 looks to see if the output is a tty...

It doesn't work for me with 17.03...

```
$ docker version
Client:
 Version:      17.03.0-ce-rc1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce-rc1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
$ docker pull ubuntu | cat
Using default tag: latest
latest: Pulling from library/ubuntu
d54efb8db41d: Pulling fs layer
f8b845f45a87: Pulling fs layer
e8db7bf7c39f: Pulling fs layer
9654c40e9079: Pulling fs layer
6d9ef359eaaa: Pulling fs layer
9654c40e9079: Waiting
6d9ef359eaaa: Waiting
f8b845f45a87: Verifying Checksum
f8b845f45a87: Download complete
e8db7bf7c39f: Download complete
6d9ef359eaaa: Verifying Checksum
6d9ef359eaaa: Download complete
9654c40e9079: Verifying Checksum
9654c40e9079: Download complete
d54efb8db41d: Verifying Checksum
d54efb8db41d: Download complete
d54efb8db41d: Pull complete
f8b845f45a87: Pull complete
e8db7bf7c39f: Pull complete
9654c40e9079: Pull complete
6d9ef359eaaa: Pull complete
Digest: sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
Status: Downloaded newer image for ubuntu:latest
```

**Comment by docwhat** [comment]
Maybe there is some confusion (especially since the example is `busybox` above).  I want a `--quiet` option to hide everything except errors and maybe the `Status` line.

**Comment by thaJeztah** [comment]
For consistency with other commands that have a `--quiet` option, the output should probably be just the image-id or `ubuntu@sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535` if `--quiet` is used.

For comparison;

```
docker build -t foo -q .
sha256:fb9f055c51960cf740ef0c8571766fd92e5df984dd5923a2281f955be1b8c36f
```

Which is the image-id (but when pulling an image, it _could_ make sense to show `image@digest` instead)

**Comment by mzedeler** [comment]
+1

**Comment by pramodhkp** [comment]
I would like to take this up as it seems like a good point to start with. #dibs

**Comment by thaJeztah** [comment]
This would be a change in the CLI, so changes need to be made in https://github.com/docker/cli

**Comment by pramodhkp** [comment]
@thaJeztah Thanks. Made some progress.

Should this be implemented only in the CLI, or the daemon as well? If it's just in the CLI, I'm thinking it's better to create a new method to display messages, as the current method is being used in multiple places.
https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go#L312

**Comment by thaJeztah** [comment]
@pramodhkp I would have to dive in it as well; perhaps the `docker build` command provides some pointers on how that one is implemented?

**Comment by jesselang** [comment]
Something like this might get @docwhat by:

`docker pull busybox:stable | grep -e 'Pulling from' -e Digest -e Status -e Error`

**Comment by thaJeztah** [comment]
This is being worked on in https://github.com/docker/cli/pull/882

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/882 was merged; this feature will be in the next (19.03) version of Docker, but should already be available on nightly builds

**Comment by tdensmore** [comment]
Only 3.5 years! Woo Hoo! Thank you @thaJeztah !

**Comment by mydockergit** [comment]
@thaJeztah From where can I get Docker version 19.03 ?  the latest is v18.06.3-ce.

**Comment by thaJeztah** [comment]
Docker 19.03 has not been released yet, but you can download the nightly builds; the change is in the CLI, so you can download a static version of the nightly build (e.g. https://download.docker.com/linux/static/nightly/x86_64/ for linux), and use the CLI from that download.

**Comment by hazcod** [comment]
Could this be done for `docker push` as wel?

**Comment by thaJeztah** [comment]
there's a PR for that here; https://github.com/docker/cli/pull/1221

looks like there's some remaining review comments on that one

**Comment by Kent-H** [comment]
Hm... `--quiet` doesn't seem to work for `docker run`.

**Comment by thaJeztah** [comment]
`docker run` (behind the scenes) is a sequence of;

- `docker pull`
- `docker create`
- `docker start`
- `docker attach`

I think a `--quiet` option for that would become quite ambiguous ("what" should be suppressed? Only `docker pull` output, or also output of the container itself after it's started?)

For that situation, `docker pull --quiet <image> && docker run <image>` (or a variation thereof) should work. A new option to influence pull behavior on `docker run` (e.g., allowing `--pull=never`)  has also been merged in https://github.com/docker/cli/pull/1498 (and will be in an upcoming release)

**Comment by Kent-H** [comment]
`docker start` and `docker run` can be silenced by redirecting stdin with `-a`, so `--quiet` would not be needed in these cases. 
`docker attach` is explicitly useful because it allows for reattaching pipes to a running process, so `--quiet` wouldn't apply there either.

If the flag is truly ambiguous, consider renaming it (`--pull-quiet`), but I don't think it should be excluded.
(Personally, I think `--quiet` is fine, and consistent across the other commands.)
