### ISSUE TITLE
Routing from docker containers using a different physical network interface and default gateway than on the host

### ISSUE THREAD

**Issue by michaeljsmalley** [moby/moby#13762]
I'm having an issue routing container traffic out of an interface that isn't the default gateway on the host. Docker seems to send traffic to whatever gateway is configured as the default on the host regardless of any iproute2 configuration that is put in place on the host. I've detailed this issue in-depth here, and there is also some discussion around it here as well: https://serverfault.com/questions/696747/routing-from-docker-containers-using-a-different-physical-network-interface-and

My setup looks like so:

```
                                              +------------+        /
                                              |            |       |
                                +-------------+ Gateway 1  +-------
                                |             | 10.1.1.1   |     /
                         +------+-------+     +------------+    |
                         |     eth0     |                      /
                         |   10.1.1.2   |                      |
                         |              |                      |
                         | DOCKER HOST  |                      |
                         |              |                      | Internet
                         |   docker0    |                      |
                         |   (bridge)   |                      |
                         |  172.17.42.1 |                      |
                         |              |                      |
                         |     eth1     |                      |
                         |  192.168.1.2 |                      \
                         +------+-------+     +------------+    |
                                |             |            |     \
                                +-------------+ Gateway 2  +-------
                                              | 192.168.1.1|       |
                                              +------------+            
```

I want to route all traffic from/to any Docker containers out of the second `eth1` `192.168.1.2` interface to a default gateway of `192.168.1.1`, while having all traffic from/to the host machine go out the `eth0` `10.1.1.2` interface to a default gateway of `10.1.1.1`. I've tried a variety of things so far to no avail but the one thing that I think is the closest to correct is to use iproute2 like so:

```
echo "1 docker" >> /etc/iproute2/rt_tables
# ip rule add from 172.17.0.0/16 table docker
# ip route add default via 192.168.1.2 dev eth1 table docker
# ip route flush cache
/etc/init.d/docker restart
```

Here are some details about the Docker install I'm testing with (this is a physical server):

```
# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651/1.6.0
OS/Arch (server): linux/amd64
```

```
# docker info
Containers: 25
Images: 11
Storage Driver: devicemapper
 Pool Name: docker-253:2-173539331-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 1.211 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.2 GB
 Metadata Space Used: 2.941 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.el6.x86_64
Operating System: <unknown>
CPUs: 8
Total Memory: 31.32 GiB
Name: docker.stuntmachine.local
ID: 23ED:X23D:CVVR:RBKA:KRE6:42KH:SJLN:UKX5:RXO5:2Z4J:5R3K:5HJK
```

```
# uname -a
Linux docker.stuntmachine.local 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Is this still an issue? Networking has been completely rewritten from scratch since 1.6.

**Comment by pbcole** [comment]
I'm facing the same/similar problem.  In my case I'd like to be able to send the output from the container to a network interface (can be identified at container start time).  So some would go through NIC1, some through NIC2, some through NIC3 etc.

# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

# docker info
Containers: 14
Images: 711
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 739
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 23.35 GiB
Name: ###redacted###
ID: SVMG:SQOA:5YIL:XM6F:NTPG:YIWG:Y5V7:457M:W6KI:KDKY:YEPS:2YCI
Http Proxy: http://###redacted###:8080/
WARNING: No swap limit support

# uname -a
Linux ###redacted### 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by PatrickHuetter** [comment]
+1 for this feature.

**Comment by maclof** [comment]
+1

**Comment by aboch** [comment]
@michaeljsmalley @PatrickHuetter 
You can specify your own default gw for the containers, see https://github.com/docker/docker/issues/20758#issuecomment-192108550

**Comment by jmcdonagh** [comment]
What is the current status of this? I'd like to have a management network on eth0 that is for communicating with the docker daemon and consul, and then have my containers listening on an application network on eth1. Seems like the same thing the OP wants. Can docker be "aware" of multiple bridges?

**Comment by thaJeztah** [comment]
closing as this one went stale

**Comment by Berbe** [comment]
I note this issue has been close for staleness, while the original problem is still very much present and got no solution.

Would it be possible to reopen it and deactivate this staleness artificially closing this issue?
