### ISSUE TITLE
ntpd from ubuntu container is blocked from the host (ubuntu) apparmor policy (surely an aufs+apparmor bug)

### ISSUE THREAD

**Issue by kiorky** [moby/moby#13998]
reopening of unfixed https://github.com/docker/docker/issues/2800

related to #2276

**Comment by kiorky** [comment]
It is not because of caps but because of bugs between apparmor & aufs.
docker fork (on top of 159f5e0)
(and our custom apparmor profile is a bit more laxist on certains points than ubuntu one.

**Comment by kiorky** [comment]
btw, lot of users are bitten by this ... https://groups.google.com/forum/#!topic/passenger-docker/B7Cq3gs1paw

**Comment by kiorky** [comment]
https://lists.ubuntu.com/archives/apparmor/2015-May/007848.html help to workaround the bug without tearing down apparmor.

**Comment by thaJeztah** [comment]
ping @ewindisch because you were working on apparmor thingies at the moment :smiley_cat:

**Comment by AkihiroSuda** [comment]
AUFS was deprecated in 19.03: https://github.com/docker/cli/pull/1484/files
