### ISSUE TITLE
Pull for a single repository tries to download same image twice

### ISSUE THREAD

**Issue by rhuss** [moby/moby#14179]
I have several images which has the reproducible behaviour in trying to download the same image layer twice. It is always the last image image layer of the repo:

```
==> default: Finding the docker images inside template with name logging
==> default: 1.5.2: Pulling from docker.io/fabric8/elasticsearch-k8s
==> default: 64e5325c0d9d: Pulling fs layer
...
==> default: 7e1ea801e108: Pulling fs layer
==> default: 9f98887039cd: Pulling fs layer
==> default: 9f98887039cd: Pulling fs layer
==> default: 9f98887039cd: Layer already being pulled by another client. Waiting.
...
==> default: e96a900a1f99: Verifying Checksum
==> default: e96a900a1f99: Download complete
==> default: 9f98887039cd: Verifying Checksum
==> default: 9f98887039cd: Download complete
==> default: 9f98887039cd: Download complete
....
==> default: 7e1ea801e108: Pull complete
==> default: 9f98887039cd: Pull complete
==> default: 9f98887039cd: Already exists
```

The full output can be found [here](https://gist.github.com/rhuss/e061926727cfff053cd2#file-gistfile1-txt).

Is this an expected behaviour ? How can it be avoided ?

I asked, because we have the same issues described in #9718 but already by pulling all our images in sequence (via a shell script). I suspect, that this could be a reason.

Additional Info:
- Docker version: Docker version 1.6.2.el7, build c3ca5bb/1.6.2
- Platform: CentOS Linux release 7.1.1503 (Core)
- Docker info:

```
Containers: 17
Images: 99
Storage Driver: devicemapper
 Pool Name: root-docker--pool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.206 GB
 Data Space Total: 44.87 GB
 Data Space Available: 41.66 GB
 Metadata Space Used: 1.823 MB
 Metadata Space Total: 109.1 MB
 Metadata Space Available: 107.2 MB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: vagrant.f8
ID: V4VP:J7JQ:YRU2:FFGS:BU3X:ROK6:KFN3:5VLG:AGXQ:RWVD:T223:HYEP
```
- Using lvm thinpool devicemapper as backend
## Steps to reproduce
- `docker pull  openshift/origin-haproxy-router:v1.0.0 | less` (**Important**: Pipe or redirect the output to avoid fancy terminal animations which will hide the double fetch)
- Look at output for layer `fd7282bf6d2f`

**Comment by rhuss** [comment]
BTW, this behaviour is not specific to OpenShift or centos. I also get it when I do the steps given on my local, standard, boot2docker environment.

**Comment by rhuss** [comment]
Another example where you can see this: `docker.io/fabric8/elasticsearch-k8s:1.5.29` and layer `f98887039cd` (this is the one from the gist)

**Comment by Tily-wlx** [comment]
+1

**Comment by sam-thibault** [comment]
This is an old issue, and the manifest version for the mentioned image is no longer supported.  I will close this as stale.
