### ISSUE TITLE
Improve information architecture commandline/run.md and reference/run 

### ISSUE THREAD

**Issue by moxiegirl** [moby/moby#14384]
We have a document for reference/run which looks like it might be better suited as  a "how to use run" and the commandline/run.md file which is actually a reference.

Need to take a closer look and see what the intention was in the original design and solve it.

![image](https://cloud.githubusercontent.com/assets/1347209/8503836/a61aa1de-217a-11e5-92bc-2c79777e6505.png)

**Comment by thaJeztah** [comment]
Now that the CLI commands are split into separate documents, this gives us more room to add extra information per command (without becoming a *huge* document). Still, `docker run` has so many options that there's still a risk it becomes a very large document.

So :+1: on evaluating and trying to reorganise / come up with a better way to document

**Comment by moxiegirl** [comment]
@thaJeztah Yeah, I thought about just consolidating into the single reference.  At this point, not sure.  Any work should step back and see the overlap in other documents that discuss `run`

**Comment by LK4D4** [comment]
@thaJeztah Do you think this was done?

**Comment by thaJeztah** [comment]
@LK4D4 hm, no it's not done yet, still a pain point, we just need time and someone to dive into this.

/cc @mstanleyjones

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
