### ISSUE TITLE
Race condition in debian initscript

### ISSUE THREAD

**Issue by itsafire** [moby/moby#14403]
For some system startups I get the following error output on rebooting my machine:

```
Mon Jul  6 11:00:46 2015: [....] Starting Docker: docker ok
Mon Jul  6 11:00:46 2015: [....] Starting OpenBSD Secure Shell server: sshd ok
Mon Jul  6 11:00:46 2015: [....] Starting MTA:Post http:///var/run/docker.sock/v1.17/containers/redis/start: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
Mon Jul  6 11:00:46 2015: Error: failed to start one or more containers
```

Docker is started ok, but not right when the initscript says: `Starting Docker: docker ok`. It is most probably not ready then, but a little bit later.

Sometimes when the filesystem on my VM is not yet cached by the host I experience this error.
On our production server with rotating disc memory I had to add a `sleep 10` to the script that will setup our environment after a reboot. Otherwise docker would not be ready.

The start script is placing docker as a required dependency and seems to do the right thing:

```
#!/bin/sh

### BEGIN INIT INFO
# Provides: dockermachines
# Required-Start:       docker
# Required-Stop:    docker
# Default-Start:    2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    docker web server environment
### END INIT INFO

# do the startup ...
```

Steps to reproduce:
1. /etc/init.d/docker stop
2. rm /var/run/docker.sock
3. /etc/init.d/docker start && ls /var/run/docker.sock

This should give the following output:

```
[ ok ] Starting Docker: docker.
ls: cannot access /var/run/docker.sock: No such file or directory
```

/var/run/docker.sock is created eventually.

Setup info:

```
uname -a :
Linux debian 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux

docker version: 
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

docker info:
Containers: 4
Images: 279
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 287
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 2
Total Memory: 986.8 MiB
Name: debian
ID: UCC5:UZDR:M3KU:3WGY:73I4:OQAW:DKKF:KJX2:EY5F:QCOX:EZHB:USYF
WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by itsafire** [comment]
Update for 1.7.0. I did a quick check for 1.7.0. Startup seems to be much quicker now. When I can always reproduce with 1.5.0, I only get it every other try with 1.7.0. But the race condition still seems to exist in 1.7.0.

**Comment by icecrime** [comment]
Thank you for your report. I'm sorry the issue didn't get much attention recently: can you please test again with the latest version of Docker and let us know if this is still an issue? Thanks!

**Comment by itsafire** [comment]
I just ran it against docker 1.11.2 at home on a Debian Stretch VM on a 2016 MacBook with quite wide IO bandwidth. I can not reproduce the behaviour. I will check on a rotating media later this day.

**Comment by itsafire** [comment]
On Debian jessie the behaviour is not reproducible. The problem still exists for Debian wheezy and  the most recent docker 1.12.1. So I guess the problem is tied to the shell init scripts and not present in systemd based boot environments.

**Comment by thaJeztah** [comment]
The init scripts used for our packages can be found here; https://github.com/docker/docker/tree/master/contrib/init

ping @tianon is this something that can/should be addressed?

**Comment by AkihiroSuda** [comment]
wheezy is no longer supported https://github.com/docker/docker-ce-packaging/pull/253
