### ISSUE TITLE
Error: driver aufs is returning inconsistent paths for container

### ISSUE THREAD

**Issue by PlugIN73** [moby/moby#14461]
Hello, guys!
Yesterday, my docker container was refused to start with error:  

```
    "Error": "Error: driver aufs is returning inconsistent paths for container 5b176ee68c9a256eaf9fcfdc6e5b582ea2cb9df21546165e739f2229f7986d30 ('/var/lib/docker/aufs/diff/5b176ee68c9a256eaf9fcfdc6e5b582ea2cb9df21546165e739f2229f7986d30' then '/var/lib/docker/aufs/mnt/5b176ee68c9a256eaf9fcfdc6e5b582ea2cb9df21546165e739f2229f7986d30')",
    "ExitCode": -1
```

$ sudo ls -lha /var/lib/docker/aufs/diff/5b176ee68c9a256eaf9fcfdc6e5b582ea2cb9df21546165e739f2229f7986d30

```
total 3.3M
drwxr-xr-x    13 root root 4.0K Jul  7 19:11 .
drwxr-xr-x 24058 root root 3.3M Jul  8 09:44 ..
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 dev
drwxr-xr-x     3 root root 4.0K Jul  7 19:11 etc
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 hexlet-ide
drwxr-xr-x     3 root root 4.0K Jul  7 19:11 home
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 proc
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 sys
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 tmp
drwxr-xr-x     4 root root 4.0K Jul  7 19:11 usr
drwxr-xr-x     3 root root 4.0K Jul  7 19:11 var
-r--r--r--     1 root root    0 Jul  7 19:11 .wh..wh.aufs
drwx------     2 root root 4.0K Jul  7 19:11 .wh..wh.orph
drwx------     2 root root 4.0K Jul  7 19:11 .wh..wh.plnk
```

sudo ls -lha /var/lib/docker/aufs/mnt/5b176ee68c9a256eaf9fcfdc6e5b582ea2cb9df21546165e739f2229f7986d30

```
total 3.3M
drwxr-xr-x     2 root root 4.0K Jul  7 19:11 .
drwxr-xr-x 24061 root root 3.3M Jul  8 09:47 ..
```

What happened?

UPD:
$ docker version

```
 Client version: 1.5.0
 Client API version: 1.17
 Go version (client): go1.4.1
 Git commit (client): a8a31ef
 OS/Arch (client): linux/amd64
 Server version: 1.5.0
 Server API version: 1.17
 Go version (server): go1.4.1
 Git commit (server): a8a31ef
```

$ docker info

```
 Containers: 11023
 Images: 2021
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 24067
 Execution Driver: native-0.2
 Kernel Version: 3.13.0-44-generic
 Operating System: Ubuntu 14.04.1 LTS
 CPUs: 4
 Total Memory: 7.305 GiB
 Name: ip-10-0-1-224
 ID: YN3T:56E2:VDEV:3W7E:M47C:LNM7:O6GX:G3NG:AALK:TD34:5E4F:IMLN
 WARNING: No swap limit support
```

uname -a
Linux ip-10-0-1-224 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by PlugIN73** [comment]
@GordonTheTurtle thank you. I added more info to my post.

**Comment by BenHall** [comment]
Likewise I'm also getting this error on a physical box.

```
{ [Error: HTTP code is 500 which indicates error: server error - Cannot start container st_ejzbe1_d2d1: Error: driver aufs is returning inconsistent paths for container 53468f2ee5c
8a84ccc43618d7a89e7424ef143d9d560d2c08c17b98d87c0ea39 ('/home/docker/data/aufs/diff/53468f2ee5c8a84ccc43618d7a89e7424ef143d9d560d2c08c17b98d87c0ea39' then '/home/docker/data/aufs/mnt/53468f2ee5c8a84ccc436
18d7a89e7424ef143d9d560d2c08c17b98d87c0ea39')
```

```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```
 docker info
Containers: 1260
Images: 248
Storage Driver: aufs
 Root Dir: /home/docker/data/aufs
 Backing Filesystem: extfs
 Dirs: 2772
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 94.41 GiB
ID: Q5KU:ZERZ:ET63:6GAH:J7V3:7LVH:LADZ:V32L:BDJQ:MWHU:H3NK:VM4K
Registry: https://index.docker.io/v1/
```

```
$ uname -a
Linux 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by PlugIN73** [comment]
This is still happened.

**Comment by PlugIN73** [comment]
Just now:
^[[31mERRO^[[0m[180994] Handler for POST /containers/create returned error: Error: driver aufs is returning inconsistent paths for container 2bf34970b49ef6d647b27e24f9bc8298721727ed171a0939a2aef57b82c308a8 ('/var/lib/docker/aufs/diff/2bf34970b49ef6d647b27e24f9bc8298721727ed171a0939a2aef57b82c308a8' then '/var/lib/docker/aufs/mnt/2bf34970b49ef6d647b27e24f9bc8298721727ed171a0939a2aef57b82c308a8')

**Comment by PlugIN73** [comment]
I have about 17339 folders in /var/lib/docker/aufs/diff/
Now, my docker version:
alexander.v@ip-10-0-1-80:~$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

docker info:
alexander.v@ip-10-0-1-80:~$ docker info
Containers: 6660
Images: 3916
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17444
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-10-0-1-80
ID: X5OZ:4RPT:25RO:GGLP:SAD3:T3PI:ULI6:AHFE:VYAU:KEVC:7LAF:H7H4
WARNING: No swap limit support

**Comment by muikrad** [comment]
This issue just randomly popped on one of our servers. Had to remove and recreate all containers to fix it.

**Comment by thaJeztah** [comment]
The error itself looks to be generated here; https://github.com/docker/docker/blob/9c1006c8bf2efc71659ec3b5412ce987661decca/daemon/daemon.go#L941-L943

**Comment by manuelmazzuola** [comment]
I'm experiencing the same issue.
I'm trying to upgrade from docker 1.7.1 to docker 1.8.3 and each `docker start container-name` is getting the same error message
```
Error: driver aufs is returning inconsistent paths for container "long hash"('/var/lib/docker/aufs/diff/long hash' then '/var/lib/docker/aufs/mnt/long hash')",
```

**Comment by calmera** [comment]
+1

**Comment by AkihiroSuda** [comment]
AUFS was deprecated in 19.03: https://github.com/docker/cli/pull/1484/files
