### ISSUE TITLE
RFE: Environment variables defined by running a command in the image (not static set)

### ISSUE THREAD

**Issue by hhorak** [moby/moby#14490]
There are technologies, like Software Collections [1] or environment modules, where the whole trick to make some binary (installed into alternate directory /opt) available is to change environment variables. For the changing environment variables there is a dedicated tool, since the variables are not static (we want only to adjust the PATH, LD_LIBRARY_PATH, etc). When delivering such packages as Docker images, calling a command to set environment variables is quite challenging.

It lead to a small study how we can do it:

Commands that users run in the container:
- bash
- showenv.sh (simulates any bash script)
- showenv.py (simulates any non-bash binary)

Cases where we check if env. variables are changed:
c#1) echo "" | docker run $IMG showenv.py
c#2) docker run -ti $IMG showenv.sh
c#3) docker run $IMG bash -c 'something'
c#4) docker run -ti $IMG bash
c#5) docker run -ti $IMG bash -l

c#6) docker exec -ti $CONT showenv.py
c#7) docker exec -ti $CONT showenv.sh
c#8) docker exec $CONT bash -c 'echo $MYVAR'
c#9) docker exec -ti $CONT bash -l
c#10) docker exec -ti $CONT bash

Possible implementations of changing environment:
A) change in the entrypoint
B) set BASH_ENV variable
C) define HOME and place a script into ~/.bashrc
D) place a script into /etc/profile.d

Result matrix for cases above and particular solution variants:

| Solution | c#1 | c#2 | c#3 | c#4 | c#5 | c#6 | c#7 | c#8 | c#9 | c#10 |
| --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| A | YES | YES | YES | YES | YES | NO | NO | NO | NO | NO |
| B | NO | YES | YES | NO | NO | NO | YES | YES | NO | NO |
| C | NO | NO | NO | NO | YES | NO | NO | NO | NO | YES |
| D | NO | NO | NO | YES | NO | NO | NO | NO | YES | NO |
| B+C+D | NO | YES | YES | YES | YES | NO | YES | YES | YES | YES |
| A+B+C+D | YES | YES | YES | YES | YES | NO | YES | YES | YES | YES |

We see that in order to address the most of the use cases, we need to implement all the ways mentioned above together.

We also see that there is no way (at least nothing I'm aware of) to change environment for running a non-bash binary as `docker exec` -- such a process will always have default environment.

This is an RFE request for implementing this in the docker properly. I've also send it to discussions while back, but without any feedback [2].

[1] http://softwarecollections.org/
[2] https://groups.google.com/forum/#!searchin/docker-user/environment/docker-user/l-LUQQdZqKw/yQRy7ffadFgJ

**Comment by jfrazelle** [comment]
can you make the title more respresentitive of the content

**Comment by cpuguy83** [comment]
Can we get a definition of what "implementing this properly" means?
It seems like the only thing we can really do here is allow `-e` on exec, but this may not be desirable, and can be done easily enough by wrapping the exec in a shell command.

**Comment by hhorak** [comment]
@cpuguy83 Good question :) What I had on mind was something like `/etc/bashrc` is for bash. So, imagine a file inside a container (e.g. `/etc/dockerrc`). If this file is present in the image, it would be executed before every `docker run` and `docker exec`.

**Comment by cpuguy83** [comment]
Is docker-engine the right place for this?

**Comment by hhorak** [comment]
What we've found out is that it is not possible to do it inside the image. So in order to allow that there must be some support in the docker-engine, probably somewhere around where the entrypoint is handled.

**Comment by thaJeztah** [comment]
@hhorak docker 1.13 will add support for `--env` on `docker exec` (see https://github.com/docker/docker/pull/24594), and also sets `$PATH` and `$TERM` is `docker exec` is started with `-t` (see https://github.com/docker/docker/pull/26461)

Does this address your use case? (So, can this issue be closed?)

**Comment by hhorak** [comment]
I don't think `--env` on `docker exec` will help us here, since it would require us to run the `docker exec` for every start of the container, which is not doable.

**Comment by thaJeztah** [comment]
Closing this because of age, and I'm not sure  if there would be a one-size-fits-all solution for this (or if it should be part of the engine itself)
