### ISSUE TITLE
Clarify relationship process=application=service or not as relates to containers

### ISSUE THREAD

**Issue by moxiegirl** [moby/moby#14646]
User reports:

https://docs.docker.com/articles/dockerfile_best-practices/#run-only-one-process-per-container implies that process=application=service which IMO may not be always true, WDYT?

"In almost all cases, you should only run a single process in a single container. Decoupling applications into multiple containers makes it much easier to scale horizontally and reuse containers. If that service depends on another service, make use of container linking."

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
