### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ianblenke** [moby/moby#14755]
While trying to deploy an environment using docker-compose, we ran into a unique issue with resolv.conf that seems odd.

When running `docker-compose up`, any container definitions that use a pre-build `image:` start up with the docker server's resolv.conf that is generated from passing `--dns` to the docker server when it starts. At the same time, any container defintions that use `build:` to do a `docker build` will inherit the docker host's `/etc/resolv.conf` file.

Our particular use case was a developer that was rebuilding their ubuntu docker environment. The underlying ubuntu VM somehow had `nameserver 127.0.1.1` in its `/etc/resolv.conf`. A caching bind9 setup on that ubuntu VM resulted in name resolutions working on the ubuntu VM itself. The docker server wasn't being started with any `--dns` option, so it was inheriting this `resolv.conf`.  

Attempting to run the docker server with `--dns 172.17.42.1` was not enough. While this did make it through to the `image:` containers started with `docker run`, it was blindly ignored by the `docker build`.

This means that the `docker build` steps were failing as unable to do DNS resolution, but the docker containers started with `docker run` were just fine.

This particular developer problem was experienced with docker 1.7.0 and docker-compose 0.3.0 on an Ubuntu VM under VMWare on a Windows host.

Our workaround was to modify the Ubuntu VM's `/etc/resolv.conf` to `nameserver 172.17.42.1` so that the `docker build` steps would use that.

Call me crazy, but this sure seems like a bug.

**Comment by tinabme** [comment]
Running on:
    VMware Workstation 11.1.2
    Ubuntu 14.04.2 64-bit

Docker version:
   Client version: 1.7.0-dev
   Client API version: 1.19
   Go version (client): go1.4.2
   Git commit (client): 5e06332
   OS/Arch (client): linux/amd64
   Server version: 1.7.0-dev
   Server API version: 1.19
   Go version (server): go1.4.2
   Git commit (server): 5e06332
   OS/Arch (server): linux/amd64

Docker info:
   Containers: 6
   Images: 140
   Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 152
    Dirperm1 Supported: true
   Execution Driver: native-0.2
   Logging Driver: json-file
   Kernel Version: 3.16.0-39-generic
   Operating System: Ubuntu 14.04.2 LTS
   CPUs: 1
   Total Memory: 6.847 GiB
   Name: ubuntu
   WARNING: No swap limit support

uname -a:
   Linux ubuntu 3.16.0-39-generic #53~14.04.1-Ubuntu SMP Wed May 27 10:03:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

List the steps to reproduce the issue:
   1.docker-compose up
   2.See initial comment for full information
Describe the results you received:
   See initial comment for full information
Provide additional info you think is important:
    See initial comment for full information

**Comment by thaJeztah** [comment]
just to exclude things; would you be able to try if you're able to reproduce this on docker 1.7.1, which was just released?

also, if you're able to provide the exact steps to reproduce (preferably with just Docker, to exclude compose), that would be helpful

**Comment by mrjana** [comment]
@ianblenke Nameserver entries belonging to loopback ranges are intentionally removed when a container inherit's the host's `resolv.conf` file and in your particular case `--dns` option when running a container is not going to help since there is know way to pass these options during the build steps which internally run temporary docker containers to achieve these build steps. But fortunately the same `--dns` options are available as daemon options as well. So if it is possible for you to pass the same options as daemon options it will work for your use case.

**Comment by ianblenke** [comment]
@mrjana, we ran into the same problem with another developer workstation, this time it was because his boot2docker VM picked up a DNS server of 192.168.1.1 somehow. Same behavior.

**Comment by cpuguy83** [comment]
From what I'm reading, the build containers are ignoring the daemon's `--dns` option.
This smells like a bug to me.
Build containers should be exactly equal to a vanilla `docker run`.

**Comment by thaJeztah** [comment]
@cpuguy83 that was my initial impression as well. Could be a dup of https://github.com/docker/docker/issues/14357, which was recently closed. I thought that was in 1.7.1, but not sure, could be in master only?

**Comment by mrjana** [comment]
@ianblenke Are you saying that in the other VM the host had DNS entry of 192.168.1.1 but that wasn't getting inherited by the container or just that the docker build steps are not able to resolve names. Is the host able to resolve names using 192.168.1.1 as the DNS server?

**Comment by mrjana** [comment]
@cpuguy83 @thaJeztah We don't know if @ianblenke used `--dns` daemon option in the first place

**Comment by ianblenke** [comment]
My apologies, I thought I had made it clear in the original issue comment.

We are experiencing the "docker-compose build" using the host's /etc/resolv.conf pointing at `nameserver 127.0.1.1`, even when the docker daemon itself is running with "--dns 172.17.42.1".

To answer your question: yes, we are seeing this problem even when we use `--dns`

**Comment by yvadugu** [comment]
After lot of trail and error, if it is on AWS box, copy namespace from /etc/resolv.conf and use as --dns for daemon

**Comment by larytet** [comment]
Reproduced in the Ubuntu 17.10
I am getting "[Errno 14] PYCURL ERROR 6 - "Couldn't resolve host"
Ping to the host works just fine 


Linux sub-2 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:38 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:09 2018
  OS/Arch:	linux/amd64
  Experimental:	false

Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 5
Server Version: 18.02.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.43GiB
Name: sub-2
ID: JLHF:V5TB:YMHQ:FAAQ:ZA4T:WHVN:UVPR:FQR4:JWOY:XIET:PLKI:BMBF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by thaJeztah** [comment]
> I tried to add --dns in the/etc/default/docker DOCKER_OPTS - did not help.

Note that the `/etc/default/docker` file is not used by systems that use systemd as an init (see the [comment at the top of that file](https://github.com/docker/docker-ce-packaging/blob/dafbbb4fa4fbaade4ae0a6abcba39bbfcd8f755d/deb/common/docker-ce.docker.default#L3-L8); for systemd, either use a drop-in unit file, or (easier), use a [`daemon.json` configuration file](https://docs.docker.com/v17.09/engine/reference/commandline/dockerd/#daemon-configuration-file)

**Comment by larytet** [comment]
@thaJeztah , thanks. I created a file  /etc/docker/daemon.json with 

```
{
"dns": ["my-nameserver"]
}
```
Solved the problem

**Comment by thaJeztah** [comment]
> From what I'm reading, the build containers are ignoring the daemon's --dns option. This smells like a bug to me. Build containers should be exactly equal to a vanilla docker run.

Testing if this is the case on Docker CE 17.12;

Starting the daemon with:

```bash
dockerd --dns=1.1.1.1
```

Then performing a  build;

```bash
docker build -<<EOF
FROM busybox
RUN cat /etc/resolv.conf
EOF
```

Produces:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM busybox
latest: Pulling from library/busybox
57310166fe88: Pull complete 
Digest: sha256:1669a6aa7350e1cdd28f972ddad5aceba2912f589f19a090ac75b7083da748db
Status: Downloaded newer image for busybox:latest
 ---> 5b0d59026729
Step 2/2 : RUN cat /etc/resolv.conf
 ---> Running in 9deb1c0fe1b9
nameserver 1.1.1.1
Removing intermediate container 9deb1c0fe1b9
 ---> 63fc888e8f2d
Successfully built 63fc888e8f2d
```

From that information, I think this issue should be closed - @cpuguy83 ?

**Comment by thaJeztah** [comment]
Looks like this is resolved through https://github.com/moby/moby/issues/14755 ?

**Comment by thaJeztah** [comment]
closing as stale
