### ISSUE TITLE
--volume-driver not being recognized "flag provided but not defined: --volume-driver"

### ISSUE THREAD

**Issue by bezelga** [moby/moby#14889]
Experimental Docker does not seem to recognize the `--volume-driver` param, running something like:

`docker run -ti -v test:/data --volume-driver=myplugin busybox sh`

Results in:

`flag provided but not defined: --volume-driver`

The docker version I am using is:

```
docker -v
Docker version 1.8.0-dev, build a031b64
```

**Comment by bkeyoumarsi** [comment]
I would say update your experimental build by running  curl -sSL https://experimental.docker.com/ | sh

```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5fdc102
 Built:        Wed Jul 22 23:59:08 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

It works for me. It's been working for a few weeks now since that's how I'm testing my volume-driver plugin :) It still worked after I updated the build on my local dev.

**Comment by bezelga** [comment]
Hello @bkeyoumarsi, thanks for the answer.

I tried to update with the command you said but the version seems to remain the same. You version was built in July 22... mine in July 15 and it does not have the `Experimental: true` as well.

```
docker-engine is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
+ sh -c docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   a031b64
 Built:        Wed Jul 15 05:21:52 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   a031b64
 Built:        Wed Jul 15 05:21:52 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment]
I'd imagine the issue you are having is that both packages (experimental and non-experimental) are called `docker-engine` and have the same version.

ping @jfrazelle is there something we can/should do here to differentiate these packages?

**Comment by jfrazelle** [comment]
no its the build script that broken ive opened a PR here https://github.com/docker/docker/pull/14903

we switched to the new apt/yum repos today so if the worst thing is we broke experimental ill be happy

**Comment by jfrazelle** [comment]
so this is a dup of #14896 closing

**Comment by bezelga** [comment]
what should i do to install the experimental version now?

**Comment by jfrazelle** [comment]
wait 30 min and it will be updated

**Comment by jfrazelle** [comment]
patience is a virtue ;) ill update here when its done

**Comment by bezelga** [comment]
ok thanks @jfrazelle !

**Comment by jfrazelle** [comment]
updated should be all good now!

**Comment by bezelga** [comment]
yayy, it works! thanks!!!!
