### ISSUE TITLE
Add image size to docker search result

### ISSUE THREAD

**Issue by phuihock** [moby/moby#14989]
Please add as an extra column to `docker search` to show image size. Different people build same-purpose image differently. At the moment, there is no way of telling the size of an image is on the registry/hub without first pulling it and run `docker images` locally.

docker version:

```
1.7.0
```

docker info:

```
Containers: 0
Images: 192
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 7.566 GiB
Name: e440
ID: F6U4:3L3A:6ZCS:TCOZ:EFL4:GNRS:TIFD:7Z63:5D3L:VOW3:MCYM:2MJN
Username: phuihock
Registry: https://index.docker.io/v1/
```

uname -a: 

```
Linux e440 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by njuettner** [comment]
+1

**Comment by thaJeztah** [comment]
This requires changes to Docker Hub, because at this moment that information is not returned (see https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#search-images)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and this still depends on the information returned by the search service
