### ISSUE TITLE
Proposal: dl.dockerproject.org

### ISSUE THREAD

**Issue by jessfraz** [moby/moby#15035]
Since we now have apt.dockerproject.org and yum.dockerproject.org I propose we migrate old static binaries to dl.dockerproject.org and start pushing new ones there. Then we can turn on indexing like we have on apt. and yum. and things could be more easily found and also then we can stop pushing things to s3 once and for all and have one infrastructure for hosting things.

ping @docker/core-maintainers

**Comment by jfrazelle** [comment]
just in case extra ping @tianon bc idk if the above ping works ;)

**Comment by tiborvass** [comment]
@jfrazelle +1 and I wonder if we could take that opportunity to rethink the URL (use GOOS and GOARCH) and maybe have "engine" in the URL somewhere? Just food for thought

**Comment by jfrazelle** [comment]
yes I want better routes ;)

**Comment by tianon** [comment]
Big +1 here, although just GOOS/GOARCH isn't quite granular enough if we
want to actually support more arches -- for example, right now the ARM
binaries we release are pretty horrible for basically everyone, so it'd be
great to be able to granularize at least that one into arm/5, arm/6, and
arm/7 separately.

**Comment by jfrazelle** [comment]
yes down for all the things, if we do this, we will do it right, just like
the apt/yum repos ;)

**Comment by tianon** [comment]
:metal:

**Comment by ankushagarwal** [comment]
Related : https://github.com/docker/docker/issues/7974. We can probably close that in sight of the discussion here.

**Comment by unclejack** [comment]
Mentioning this so that it's really equivalent to #7974:
Checksums should also be provided.

**Comment by vdemeester** [comment]
Given the activity on this issues, I'll close it as I think it's either not needed or already done. But if you think otherwise, feel free to discuss it and we'll re-open 😉 
cc @thaJeztah @andrewhsu
