### ISSUE TITLE
Docker daemon tries to load deleted images

### ISSUE THREAD

**Issue by jwogrady** [moby/moby#15047]
### docker version:

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
### docker info:

Containers: 5
Images: 69
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-44-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 3.665 GiB
### uname -a:

Linux status26-ub01 3.16.0-44-generic #59~14.04.1-Ubuntu SMP Tue Jul 7 15:07:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Using Docker version 1.7.1, build 786b29d on Ubuntu 14.04.2 LTS

List the steps to reproduce the issue:
1.  `docker rmi [image name]`
2.  `sudo docker -d`
#### Describe the results you received:

The daemon tries to load a deleted image.

`INFO[0000] Loading containers: start.                   
....ERRO[0000] Failed to load container 26501a33826d62551cb6875a089ca533233c08db2b28647572a978803a521c98: open /var/lib/docker/containers/26501a33826d62551cb6875a089ca533233c08db2b28647572a978803a521c98/config.json: no such file or directory 
...ERRO[0000] Failed to load container c7ab60f8ce2df850c81d31cd4d36dc0715cfbbde20a2c3513265c9c13917a0e0: open /var/lib/docker/containers/c7ab60f8ce2df850c81d31cd4d36dc0715cfbbde20a2c3513265c9c13917a0e0/config.json: no such file or directory 
.ERRO[0000] Failed to load container d5feb28c0d3516448544687e1bcffeeb2f1e065aa53512d4845234ba0b008d8f: open /var/lib/docker/containers/d5feb28c0d3516448544687e1bcffeeb2f1e065aa53512d4845234ba0b008d8f/config.json: no such file or directory`
#### Describe the results you expected:

Expected the daemon to run with no errors.
### Provide additional info you think is important:

The deleted image folders remained in /var/lib/docker/containers.  I resolved the issue by droping into a root shell and deleting the folders manually.
##### drop into root shell

`sudu su root`
`cd /var/lib/docker/containers`
`rm -rf [image reference id given in report]`
#### exit root user

`exit`

No errors reported when `sudo docker -d`.

**Comment by cpuguy83** [comment]
Looks like the issue is related to a partially removed container.
Can you update the title accordingly? Thanks!

**Comment by vrehak** [comment]
We ran into the same error on 1.8.2 when a server got out of memory and we did hard reset. Lots of containers where left in /var/lib/docker/containers and 'docker ps' hanged.

**Comment by wiemBA** [comment]
I have the following daemon.json file:
{
  "storage-driver": "overlay2",
  "graph": "/var/lib/docker",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "2"
  },
  "debug": false,
  "userns-remap": "1000:1000"
} 
But i didn't uderstand what does it mean every key. Can you help me and thank you.

**Comment by thaJeztah** [comment]
@wiemBA the options in `daemon.json` basically match the flags that are present on `dockerd` (`dockerd --help` shows the available flags). Documentation for `dockerd` and an overview of options for `daemon.json` can be found here; https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by thaJeztah** [comment]
Looking at the issue above, this issue looks to be very old now, and I think there's improvements made in this area, so I'm going to close and lock the issue for housekeeping. If you run into this issue with a current version of docker, please open a new issue instead
