### ISSUE TITLE
Docs for 'docker run' do not explain security-opts

### ISSUE THREAD

**Issue by pmorie** [moby/moby#15089]
The docs for 'docker run' should explain the `security-opts` flag.

**Comment by thaJeztah** [comment]
Do you mean *mention*, or *explain* the options. The options are mentioned in the "run reference" section here; https://docs.docker.com/reference/run/#security-configuration

**Comment by pmorie** [comment]
@thaJeztah i had meant that they should be explained - I might actually make a PR for this myself. I'll provide more detail; I had created this so I wouldn't forget and then some person stuff came up almost immediately afterward.

**Comment by thaJeztah** [comment]
@pmorie ah, alright, I wasn't sure (some people miss the "run reference" section).

Some explanation should be good, just be careful though, to not make it into a full AppArmor tutorial, because then it would be better to add a link a reference, instead of trying to write that ourself. :-)

**Comment by pmorie** [comment]
@thaJeztah heh, it would be an SELinux tutorial in my case ;-)

**Comment by thaJeztah** [comment]
@pmorie oh, I have a great idea! We could create a colouring book. Oh wait, LOL

Anyway, I marked this issue as "claimed" so that other people won't start working on it. Looking forward to your contribution!

**Comment by LK4D4** [comment]
@pmorie any chance that you still interested in this?

**Comment by pmorie** [comment]
I am interested, but have zero bandwidth to contribute at the moment :)

On Tue, Sep 13, 2016 at 2:37 PM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment]
@pmorie I'll leave it opened than. Thanks :)

**Comment by neersighted** [comment]
Closing for now as https://docs.docker.com/reference/cli/docker/container/run/#security-opt exists and is decent; if anyone has specific improvements/shortcomings in mind, please open a new issue.
