### ISSUE TITLE
/proc hung - unable to kill container and daemon

### ISSUE THREAD

**Issue by hermansc** [moby/moby#15204]
Hi.

I've been running a container which now has put my system in a funny state. I first noticed it by not being able to do `ps -aux`, because it just hangs forever. I did `strace` and I got the following output:

```
stat("/proc/20262", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
open("/proc/20262/stat", O_RDONLY)      = 6
read(6, "20262 (java) D 20258 20258 20258"..., 1024) = 226
close(6)                                = 0
open("/proc/20262/status", O_RDONLY)    = 6
read(6, "Name:\tjava\nState:\tD (disk sleep)"..., 1024) = 801
close(6)                                = 0
open("/proc/20262/cmdline", O_RDONLY)   = 6
read(6,
```

And there it hangs. So trying to read PID 20262's cmdline blocks the call. Reading [this blog post](https://rachelbythebay.com/w/2014/10/27/ps/) I think I know why:

> Some process managers have decided they would rather be the ones who keep tabs on memory size and do the killing themselves. To do this, they run a task in a container, set a limit, and disable the kernel's oomkiller behavior in that container. Then they wait for notifications of it getting too big and kill it themselves.
> This is all well and good, but have you ever seen what happens when the process manager fails? Life gets ... interesting.

So I'm suspecting the docker daemon has gotten itself in a pickle and now this is effecting the rest of my system. I'd prefer not to restart the docker daemon, as that would interrupt business critical services running there already -- but if forced to I'd at least love to know how I got in this state so I don't do the same again.

Here's the output from running `docker inspect <container>`:

``` json
{
    "AppArmorProfile": "",
    "Args": [
        "-c",
        " /usr/lib/spark/bin/spark-class org.apache.spark.executor.MesosExecutorBackend"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "-c",
            " /usr/lib/spark/bin/spark-class org.apache.spark.executor.MesosExecutorBackend"
        ],
        "CpuShares": 2048,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/bin/sh"
        ],
        "Env": [
            "LIBPROCESS_PORT=0",
            "MESOS_CHECKPOINT=0",
            "MESOS_DIRECTORY=/local/mesos/work/slaves/20150516-115645-1209730570-5050-2077-S1/frameworks/20150518-110443-1243285002-5050-3534-19520/executors/20150516-115645-1209730570-5050-2077-S1/runs/25bb51b6-752b-4168-a516-ceca9ae03aae",
            "MESOS_EXECUTOR_ID=20150516-115645-1209730570-5050-2077-S1",
            "MESOS_FRAMEWORK_ID=20150518-110443-1243285002-5050-3534-19520",
            "MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos-0.22.1.so",
            "MESOS_NATIVE_LIBRARY=/usr/lib/libmesos-0.22.1.so",
            "MESOS_SLAVE_ID=20150516-115645-1209730570-5050-2077-S1",
            "MESOS_SLAVE_PID=slave(1)@xxxxxxx:5051",
            "SPARK_EXECUTOR_MEMORY=4096m",
            "SPARK_EXECUTOR_OPTS=",
            "SPARK_USER=root",
            "SPARK_EXECUTOR_OPTS=",
            "SPARK_USER=root",
            "SPARK_EXECUTOR_MEMORY=4096m",
            "MESOS_SANDBOX=/mnt/mesos/sandbox",
            "PATH=/usr/lib/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/root",
            "JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
        ],
        "ExposedPorts": null,
        "Hostname": "hostname",
        "Image": "apache/spark:1.4.0",
        "MacAddress": "",
        "Memory": 4723834880,
        "MemorySwap": -1,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-07-31T08:52:37.635002186Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": [
        "613c2bde550aa451215657b9310ba1a5a9997f2eaf8f5797fa1e5f652e16ee18"
    ],
    "HostConfig": {
        "Binds": [
            "/usr/local/lib/libmesos.so:/usr/local/lib/libmesos.so:ro",
            "/local/mesos/work/slaves/20150516-115645-1209730570-5050-2077-S1/frameworks/20150518-110443-1243285002-5050-3534-19520/executors/20150516-115645-1209730570-5050-2077-S1/runs/25bb51b6-752b-4168-a516-ceca9ae03aae:/mnt/mesos/sandbox"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "ContainerIDFile": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LxcConf": [],
        "NetworkMode": "host",
        "PidMode": "",
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/local/docker/containers/158a48817335ef1c49b11cf02237cbda34997e8116055e6b63543e62aa1a1308/hostname",
    "HostsPath": "/local/docker/containers/158a48817335ef1c49b11cf02237cbda34997e8116055e6b63543e62aa1a1308/hosts",
    "Id": "158a48817335ef1c49b11cf02237cbda34997e8116055e6b63543e62aa1a1308",
    "Image": "e246fb601d8f6e505b3264bc3fa3f1641ffca8dd80ae985588d4d451ae188a0f",
    "MountLabel": "",
    "Name": "/mesos-25bb51b6-752b-4168-a516-ceca9ae03aae",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/bin/sh",
    "ProcessLabel": "",
    "ResolvConfPath": "/local/docker/containers/158a48817335ef1c49b11cf02237cbda34997e8116055e6b63543e62aa1a1308/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 20258,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-07-31T08:52:38.712678631Z"
    },
    "Volumes": {
        "/mnt/mesos/sandbox": "/local/mesos/work/slaves/20150516-115645-1209730570-5050-2077-S1/frameworks/20150518-110443-1243285002-5050-3534-19520/executors/20150516-115645-1209730570-5050-2077-S1/runs/25bb51b6-752b-4168-a516-ceca9ae03aae",
        "/usr/local/lib/libmesos.so": "/usr/lib/libmesos-0.22.1.so"
    },
    "VolumesRW": {
        "/mnt/mesos/sandbox": true,
        "/usr/local/lib/libmesos.so": false
    }
}
```

And the last output from `docker logs --tail=1 <container>`:

```
I0731 09:20:18.223043    70 exec.cpp:379] Executor asked to shutdown
```

Which is a somewhat mesos specific message, but it should indicate that the docker container should be in a state where it's about to shutdown. And just to confirm, since you can see that the PID of the docker container itself is 20258 - the hanging PID (20262) is indeed the child of this process:

```
$ pgrep -P 20258
20262
```

Here's the output from `docker -D info`:

```
$ sudo docker -D info
Containers: 38
Images: 1057
Storage Driver: aufs
 Root Dir: /local/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1293
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 16
Total Memory: 18.9 GiB
Name: hostname
ID: QKNF:WVIG:DEPM:VKSW:57WQ:OIVP:6EHK:WNB6:RQME:STMT:YFLX:N5IY
Debug mode (server): false
Debug mode (client): true
Fds: 100172
Goroutines: 600660
EventsListeners: 1
Init Path: /usr/bin/docker
Docker Root Dir: /local/docker
WARNING: No swap limit support

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ uname -a
Linux hostname 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I'm sorry for not knowing how to reproduce this state, nor am I sure if the similar issue already exists in the bug tracker. Issue #9605 and #13885 seems related, but doesn't quite match my issue.

**Comment by hermansc** [comment]
Looking more at this ticket (#14440) it definitely looks to be related to the OOM. I'm not entirely sure though. The issue does happen when I'm running a container with high memory usage, which indeed may go over the allocated memory limit that you can see from my inspect command.

**Comment by cpuguy83** [comment]
@hermansc 

The mentioned issue# is talking about a feature that was added in Docker 1.7.0, you are on 1.5.0.
Docker does not perform OOM operations itself, this is done by the kernel.
OOM does not appear to have happened against this container as it is not reflected in your `inspect` output.

This, to me, looks like an issues with the process itself.

**Comment by pwaller** [comment]
The title of this reminds me of Rachel's blog post: http://rachelbythebay.com/w/2014/10/27/ps/

**Comment by hermansc** [comment]
Hi, @cpuguy83 thanks for responding and clearing up some confusion. I did actually link to the blog post that @pwaller added too, and I think it quite accurately describes the problems I'm experiencing.

It may indeed be a problem with the process itself, but it's affecting docker in such a way that:
a) I can't kill my container
b) I can't stop docker
c) /proc/pid/cmdline is hung forever forcing me to reboot

Any steps I can take to try to debug this on my system? Or indeed flags I can add to see if it stops it from happening again?

**Comment by pwaller** [comment]
Heh, apologies for chiming in with a redundant link @hermansc, was blind to it on first reading.

**Comment by cpuguy83** [comment]
@hermansc Do you have some more details about the system? Like is it using upstart/systemd/sysvinit? How did you start the container? How is docker daemon started?
Also note that your kernel is a bit out of date and there may be bug fixes on a more recent version (I'm not saying this is the problem, just take note).

**Comment by achanda** [comment]
FWIW, I saw similar behavior on a box with docker 1.7. The box was using systemd, containers were started using ansible. Systemd was managing the docker daemon.

**Comment by talos** [comment]
I experienced the same issue with docker 1.9.1.  `ps aux` hangs.  `docker ps` and `docker info` also hung.  I was unable to restart the docker service, although after trying it seemed it died on its own -- although that didn't fix `ps aux`.

Unfortunately, I can't get more specific debug info right now as the machine became unresponsive after an attempted restart -- it seems to have shut off all services but gotten stuck on Docker.

**Comment by icecrime** [comment]
Thank you for your report. I'm sorry the issue didn't get much attention recently: can you please test again with the latest version of Docker and let us know if this is still an issue? Thanks!

**Comment by patsak** [comment]
I have the same issue.
```bash
$ sudo docker -D  info                                                                                                                                                             Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
```
```bash
$ sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```
I try to run spark on mesos cluster with docker containerization. Output for `docker inspect` is similar to @hermansc version. Also I noticed that application needs to use swap to reproduce this issue. When I increase memory limit - issue go away.

**Comment by morsik** [comment]
Just went into same problem when using OKD 3.10.

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by thaJeztah** [comment]
closing as this one went stale
