### ISSUE TITLE
Unable to run docker daemon with client authentication disabled but TLS enabled

### ISSUE THREAD

**Issue by gauravphoenix** [moby/moby#15232]
# What am I trying to achieve?

I want to run docker daemon with TLS enabled but client certificate authentication disabled so that clients can verify authenticity of docker daemon but docker daemon  doesn't need to verify clients.
# How am I trying to achive?

As per [documentation](https://docs.docker.com/articles/https/) I am running following command:
(_I think documentation needs to provide some more examples in this context_)

```
./docker -d  --tls=true --tlscert=server-cert.pem --tlskey=server-key.pem -H=0.0.0.0:2376
```

Above command gives me error- 

```
 Shutting down due to ServeAPI error: Could not read CA certificate: open /root/.docker/ca.pem: no such file or directory
```

So I re-ran the command like this- 

```
./docker -d --tlsverify=false --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H=0.0.0.0:2376
```

This doesn't help as when I try to run docker client with flags `--tlsverify=true --tlscacert="\path\to\ca.cert"` I get following error- 

```
tls: oversized record received with length 20527
```

which indicates that docker daemon is not using TLS. 

If I run docker daemon like this:

```
./docker -d  --tls=true --tlsverify=false --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H=0.0.0.0:2376
```

and docker client like this- 

```
docker --tls=true --tlsverify=true --tlscacert=D:\ca.pem -H=$HOST:2376 ps
```

I get following error message on client `remote error: bad certificate` and on server I see error message- `tls: client didn't provide a certificate`

This is behavior is not intuitive- I am telling docker to `--tlsverify=false` but still it is still enforcing client cert verification. 

The only way docker client is able to verify docker daemon cert is when docker daemon is enforcing client cert verification something which I don't want. I just want one way verification - docker client verifying docker daemon.

So, how do I go about running docker in the way I described above? Example command for client and server will be **greatly appreciated**. 
# Version information

Docker client running on Windows 7

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): windows/amd64
```

Docker server running on Debian jessie

```
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

```

**Comment by xiaods** [comment]
/usr/lib/omega/docker -d -D -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --tlscert /etc/omega/agent/cert.pem --tlskey /etc/omega/agent/key.pem --tlscacert /etc/omega/agent/ca.pem --tlsverify

**Comment by gauravphoenix** [comment]
@xiaods - are you referring to client or server command? In both cases I am passing --tlsverify flag

**Comment by kamaljeetrathi** [comment]
how to connect if both on different machine using authentication

**Comment by cpuguy83** [comment]
I can't repro on master.

```
$ docker daemon -H tcp://127.0.0.1:80 --tls --tlscert=/certs/server.pem --tlskey=/certs/server-key.pem &
...
$ docker -H tcp://127.0.0.1:80 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ docker -H tcp://127.0.0.1:80 --tls --tlsverify --tlscacert=/certs/ca.pem ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Please note that docker will look for an env var called `DOCKER_TLS_VERIFY`, and if it is set at all, it will do verification.

**Comment by xiaods** [comment]
@cpuguy83 thanks for your hints. it indeed.cool

**Comment by TimLudwinski** [comment]
Part of the problem (or at least the problem I'm having), is that `docker -d` ignores the environment variable `DOCKER_CERT_PATH`.

**Comment by bhagwandassoni1953** [comment]
root@localhost:/LIST/Test1/DEMO22/ledgers# docker-compose -f docker-compose.yml up                                                                                Traceback (most recent call last):                                                 File "/usr/bin/docker-compose", line 11, in <module>                               load_entry_point('docker-compose==1.21.0', 'console_scripts', 'docker-compose')()                                                                               File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 71, in main        command()                                                                      File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 124, in perform_command                                                                             project = project_from_options('.', options)                                   File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 38, in project_from_options                                                                      tls_config=tls_config_from_options(options, environment),                      File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 84, in tls_config_from_options                                                             ssl_version=tls_version                                                        File "/usr/lib/python3/dist-packages/docker/tls.py", line 81, in __init__          'Path to a certificate and key files must be provided'                       docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.

**Comment by thaJeztah** [comment]
@bhagwandassoni1953 That's expected if your client is not configured with the client certificate;

```
Path to a certificate and key files must be provided through the client_config param.
TLS configurations should map the Docker CLI client configurations.
See https://docs.docker.com/engine/articles/https/ for API details.
```

**Comment by thaJeztah** [comment]
Overall, I'm not sure this is something we'd want to implement. If I understand the proposal correctly, then this would allow for a TLS connection without any protection, which means that  The Docker API is exposed (publicly), without access control, meaning anyone that has access to it will have full `root` access to the host.

The API uses TLS client verification exactly for that reason (encrypt traffic, _and_ provide access control). Current versions of docker also allow the client to connect with the daemon using an SSH connection (which for many uses may be preferable over exposing the API over HTTPS).


Because of the above, and because of the age of this ticket, I'm closing this proposal, but feel free to comment if there's compelling reasons to add this feature that I overlooked.

**Comment by BalJoc** [comment]
@thaJeztah 
Sorry, to comment your 2 years old post. But this is the same issue I'm looking for.
I read your comment. It sounds logical and comprehensible, but somehow contradicts the [documentation](https://docs.docker.com/engine/security/protect-access/).

> **Other modes**
> If you _don’t_ want to have complete two-way authentication, you can run Docker in various other modes by mixing the flags.
> 
> **Daemon modes**
> tlsverify, tlscacert, tlscert, tlskey set: Authenticate clients
> tls, tlscert, tlskey: _Do not authenticate clients_
> 

Also in the help
```
dockerd --help | grep verify
      --tls                                     Use TLS; implied by --tlsverify
      --tlsverify                               Use TLS and verify the remote

```
When reading this I understand, that  --**tlsverify** activating security, but **with** client authentication and --**tls** is activating security, but **without** client authentication.

So maybe the documentation has to be updated!?

**Comment by davidkhala** [comment]
I run some tests again document section
> **Daemon modes**
> tls, tlscert, tlskey: Do not authenticate clients
by running `sudo dockerd --tls -H=0.0.0.0:2376 --tlscert=server-cert.pem --tlskey=server-key.pem`

It doest not work and prompts like 
```
invalid TLS configuration: could not read CA certificate "/root/.docker/ca.pem": open /root/.docker/ca.pem: no such file or directory
```
