### ISSUE TITLE
`firewall-cmd --reload` still wipes Docker 1.7.1's iptables rules on CentOS 7

### ISSUE THREAD

**Issue by exarkun** [moby/moby#15254]
``` sh
[root@docker-upgrade-testing ~]# docker --version
Docker version 1.7.1, build 786b29d
[root@docker-upgrade-testing ~]# firewall-cmd --version
0.3.9
[root@docker-upgrade-testing ~]# systemctl status docker
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: active (running) since Mon 2015-08-03 15:59:51 UTC; 12s ago
     Docs: https://docs.docker.com
 Main PID: 19313 (docker)
   CGroup: /system.slice/docker.service
           └─19313 /usr/bin/docker -d -H fd://

Aug 03 15:59:51 docker-upgrade-testing systemd[1]: Started Docker Application Container Engine.
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.744753918Z" level=info msg="[graphdriver] using prior storage driver...apper\""
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.755388909Z" level=warning msg="Running modprobe bridge nf_nat failed...tatus 1"
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.894797426Z" level=info msg="Loading containers: start."
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.895059221Z" level=info msg="Loading containers: done."
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.895079910Z" level=info msg="Daemon has completed initialization"
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.895098843Z" level=info msg="Docker daemon" commit=786b29d execdriver...on=1.7.1
Aug 03 15:59:51 docker-upgrade-testing docker[19313]: time="2015-08-03T15:59:51.895149298Z" level=info msg="Listening for HTTP on fd ()"
Hint: Some lines were ellipsized, use -l to show in full.
[root@docker-upgrade-testing ~]# systemctl status firewalld
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled)
   Active: active (running) since Fri 2015-07-31 15:02:45 UTC; 3 days ago
 Main PID: 25824 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─25824 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

[root@docker-upgrade-testing ~]# docker run -p 8080 --rm busybox                                                                                            
[root@docker-upgrade-testing ~]# firewall-cmd --reload
success
[root@docker-upgrade-testing ~]# docker run -p 8080 --rm busybox
Error response from daemon: Cannot start container 31297ce119c3f591b762b84c3d4514cc42694817c9e05d179b6855dcb13317c0: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32778 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
[root@docker-upgrade-testing ~]# 
```

I expected Docker to re-populate iptables with the rules necessary for its proper operation (given that #9397 was merged and the 1.7.0 release notes suggest automatic firewalld integration).

Instead it seems Docker's rules were wiped and not restored.

This seems easy to reproduce on, for example, Rackspace's CentOS 7 image using standard system packages plus the latest docker from get.docker.com.

Other details:

``` sh
[root@docker-upgrade-testing ~]# uname -a
Linux docker-upgrade-testing 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@docker-upgrade-testing ~]# docker info
Containers: 0
Images: 28
Storage Driver: devicemapper
 Pool Name: docker-202:1-1313392-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 577.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 81.63 GB
 Metadata Space Used: 1.495 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.452 GiB
Name: docker-upgrade-testing
ID: IUP5:4FRG:TIZM:KVTM:FDIC:7QAW:V2MQ:3LXQ:3JEY:43E2:2V3I:QWKV
[root@docker-upgrade-testing ~]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
[root@docker-upgrade-testing ~]# 
```

**Comment by aboch** [comment]
@exarkun During the transition to libnetwork, it does not seem the necessary changes made it to libnetwork in time for 1.7.1. Specifically the FirewalldInit() invocation in bridge driver.
It will be there in docker/docker 1.8 release

**Comment by aboch** [comment]
@exarkun Can you please confirm things work in [1.8.0-rc1](https://test.docker.com/builds/Linux/x86_64/docker-1.8.0-rc1) image. Thanks.

**Comment by aleksijohansson** [comment]
Stopped the docker service and replaced the binary with the 1.8.0-rc2 and restarted the service. Can't even connect to the docker daemon just by running:

<pre>docker version</pre>

Tried reloading the Firewalld config by running:

<pre>firewall-cmd --reload</pre>

but that doesn't help. After disabling Firewalld everything works fine on my Fedora 22.

**Comment by exarkun** [comment]
The linked Docker binary also doesn't work on my CentOS 7 system.  It hangs during startup:

```
# strace -p 3735
Process 3735 attached
futex(0x18a18d8, FUTEX_WAIT, 0, NULL
```

**Comment by thaJeztah** [comment]
ping @aboch could you have another look here?

**Comment by tazle** [comment]
This issue seems to still exist in 1.9.1:

If I reload firewall configurtion:
{code}
$ sudo firewall-cmd --reload
success
$ docker --version
Docker version 1.9.1, build a34a1d5
{code}

I can still start containers that don't require port forwards
{code}
$ sudo docker run -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
583635769552: Pull complete
b175bcb79023: Pull complete
Digest: sha256:c1bc9b4bffe665bf014a305cc6cf3bca0e6effeb69d681d7a208ce741dad58e0
Status: Downloaded newer image for busybox:latest
/ #
{code}

But if port forwards are required, startup fails because firewalld wiped the DOCKER chain upon `firewall-cmd --reload`:
{code}
$ sudo docker run -it -p 12345:12345 busybox
Error response from daemon: Cannot start container 715fb2d743a4d76d077cee6244888724bbd7712ad1c4073e35339d49d1c4612a: failed to create endpoint jovial_ride on network bridge: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 0/0 --dport 12345 -j DNAT --to-destination 172.17.0.3:12345 ! -i docker0' failed: iptables: No chain/target/match by that name.
{code}

**Comment by asdr14** [comment]
@thaJeztah

**Comment by thaJeztah** [comment]
Was the daemon restarted after the firewall-cmd was run?

**Comment by jmeth** [comment]
I can confirm this issue still exists in 1.9.1 build a34a1d5
Restarting the docker daemon will reload the necessary iptable rules, but it would be nice if I could run firewall-cmd without having to restart docker everytime.

**Comment by rgarrigue** [comment]
I got the same issue running `Docker version 1.11.1, build 5604cbe` and `firewalld 0.3.12` over debian 8

**Comment by treksler** [comment]
I can do sudo firewall-cmd --reload without losing the DOCKER chain.
I can also do sudo service firewalld restart without losing the DOCKER chain.

Docker version 1.11.2, build b9f10c9 on Red Hat Enterprise Linux Server release 7.2 (Maipo) kernel 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tallandtree** [comment]
Still does not work in my environment as well with respect to DOCKER-ISOLATION and custom docker networks. See also: https://github.com/docker/docker/pull/9397.

**Comment by azdle** [comment]
I'm also seeing this problem on Fedora 24, here's the error message I;m seeing (for the googleability for others): 

```
$ docker-compose up -d --build --remove-orphans
Creating network "okami_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (COMMAND_FAILED: '/usr/sbin/iptables -w -t nat -I DOCKER -i br-59d5580a1102 -j RETURN' failed: )
```

Running `sudo systemctl restart docker` after `sudo firewall-cmd --reload` does temporarily fix it.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale. I also think improvements were made in this area (but haven't verified all cases)
