### ISSUE TITLE
Builder EXPOSE documentation broken link

### ISSUE THREAD

**Issue by pwaller** [moby/moby#15401]
Someone came to me trying to understand how `--publish` worked, confused that `--publish 1234` wasn't publishing `1234` on the host. They had come from the builder `EXPOSE` documentation and had left confused.

[This link is broken in the builder documentation is broken](https://github.com/docker/docker/blame/f3af9c8bdb68e5db7aaed7aec11aa2a78fd7e546/docs/reference/builder.md#L457).

Or at least, it doesn't go where I think was intended. In addition, [the `docker run`](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) documentation doesn't mention the long form of `-p` (`--publish`) at all. 

If someone is new to docker trying to understand how port publishing works, the `EXPOSE` section in the `docker run` documentation is not as up front as it could be about how to control the host port. (likewise with the `EXPOSE` in the builder docs).

I would have submitted a fix to just point the link to `/reference/run/#expose-incoming-ports` but then I realised that it wouldn't really fix the problem of explaining what `-p` is, and that this would mean repeating the same link many times, which I don't think would have made for very good documentation.

So I thought I would punt the problem to the documentation experts here - sorry! :)

/cc @SvenDowideit

**Comment by pwaller** [comment]
Ping.

**Comment by thaJeztah** [comment]
Hi @pwaller we recently merged a PR to improve documentation around `EXPOSE`. Could you check if this PR makes this a bit clearer for you? https://github.com/docker/docker/pull/16965

I'll check if the link is fixed and if the `--publish` long form is documented in the current docs :+1:

**Comment by pwaller** [comment]
Looking at it, the documentation is improved. I still think the original confusion is not ameliorated very well. The first line of this issue still stands:

> Someone came to me trying to understand how --publish worked, confused that --publish 1234 wasn't publishing 1234 on the host.

The documentation is not upfront with this, and one might read for example (from http://docs.docker.com/reference/run/#expose-incoming-ports):

> If the operator uses -P or -p then Docker will make the exposed port accessible on the host and the ports will be available to any client that can reach the host.

You might read that, and then stop, thinking you are done - not understanding that there is also a random mapping going on.

Thinking about it, the documentation pre-supposes that you understand that the container has its own network interfaces, and that those are unreachable from the outside world. This is obvious to us, but not to a newbie.

I think the expose documentation would be better if A) it made clear that if you run a program in the container which listens it is unreachable unless docker arranges some forwarding from the host and B) it stated up front that unless the host port is provided explicitly, it is random (and can be seen in the output of `docker ps` or `docker port <container id/name>`). For instance there are few parts of the documentation you could read and think `-p 80` will "publish port 80 inside the guest".

**Comment by pwaller** [comment]
Ping @thaJeztah. I'd like to close this remove this from my personal global github issues list (eventually). I'd be happy to close it at this point; however I think some of the points I made above may still stand.

**Comment by thaJeztah** [comment]
@pwaller would you be interested in opening a pull request to make the modifications you think would enhance the docs? The markdown used to generate that part of the documentation is part of this repository, and can be found here; https://github.com/docker/docker/blob/master/docs/reference/run.md

**Comment by thaJeztah** [comment]
Linking https://github.com/docker/docker.github.io/issues/3913

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
