### ISSUE TITLE
KVM Bridge not forwarding large fragmented packets

### ISSUE THREAD

**Issue by piaohai** [moby/moby#15618]
I'm trying to do the following setup:

HOST--> KVM<-- docker 0 --> container

My eth1 connection sets the MTU to 1500 and on the kvm host, through.  inside container i can only query sql  less than MTU size; packets of files bigger than MTU get dropped even thouth i set mtu.

Host kernel: 3.13-4.02  Ubuntu 14.04
Docker: 1.7 

![image](https://cloud.githubusercontent.com/assets/1393745/9293244/76158686-4455-11e5-82e5-9f819bfb9569.png)

![image](https://cloud.githubusercontent.com/assets/1393745/9293245/882148e2-4455-11e5-8973-b65065916999.png)

before frame 13,every is ok but after 13, packages are drops

DOCKER_OPTS=" -iptables=false -s overlay -mtu 1367 -b lxcbr0

KVM NET:

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:c7:82:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.165.124.128/22 brd 10.165.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fec7:82f3/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:8a:e4:b3 brd ff:ff:ff:ff:ff:ff
    inet 10.165.154.53/24 brd 10.165.154.255 scope global eth1

CONTINAER :

27: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc noqueue state UP 

VM-BR
28: veth88f7114: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1367 qdisc noqueue master lxcbr0 state UP group default 
    link/ether ea:90:d4:08:65:f5 brd ff:ff:ff:ff:ff:ff

**Comment by lylepratt** [comment]
We also experience this issue. Especially on GCE since they have an odd, non-standard, MTU size.

**Comment by LK4D4** [comment]
@mrjana @mavenugo @aboch @sanimej was this fixed? Should people use --mtu-size to fix this?

**Comment by thaJeztah** [comment]
Let me close this one, as it went stale
