### ISSUE TITLE
Please add *.dockerproject.org to status.docker.com

### ISSUE THREAD

**Issue by pdericson** [moby/moby#15619]
apt.dockerproject.org and yum.dockerproject.org we're recently introduced.  They are not currently listed on status.docker.com.

If possible could the status of *.dockerproject.org be discoverable on status.docker.com?

**Comment by jfrazelle** [comment]
ya maybe we can make our own status page, unsure who manages that one and we have a whole different set of infra

**Comment by thaJeztah** [comment]
This was done:

<img width="920" alt="screen shot 2018-02-14 at 10 22 05" src="https://user-images.githubusercontent.com/1804568/36196419-f5f1c35c-1170-11e8-9bc4-f93415a7cc19.png">
