### ISSUE TITLE
OOMKilled flag isn't always set to true when OOM occurs? 

### ISSUE THREAD

**Issue by eleweek** [moby/moby#15621]
I wrote a simple program to allocate memory in python, 1 line: 

`wasted_memory = range(200000000)`

When I run `docker run -m 200m --memory-swap -1 -v /Users/putilin/base/example_solutions/waste_memory.py:/waste_memory.py python:2.7 python /waste_memory.py` and then do `docker inspect`, I see `"OOMKilled": true` and `"ExitCode": 137`.

This is expected. 

When I run bash and then run the program from bash(
`docker run -m 200m --memory-swap -1 -v /Users/putilin/base/example_solutions/waste_memory.py:/waste_memory.py python:2.7 bash`)

I get this:

```
root@a9eade3085a5:/# python /waste_memory.py
Killed
root@a9eade3085a5:/# dmesg | tail -n 5
[    0.000000] pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[19392.000000]     0 19392     5485      755      15       3      125             0 bash
[19417.000000]     0 19417   396156    42487     618       4   266041             0 python
[    0.000000] Memory cgroup out of memory: Kill process 19417 (python) score 890 or sacrifice child
[    0.000000] Killed process 19417 (python) total-vm:1584624kB, anon-rss:168368kB, file-rss:1580kB
```

When I exit, I see `"OOMKilled": true,`. This is expected.

When I increase memory limit to 1000m and run it(`docker run -it -m 1000m --memory-swap -1 -v /Users/putilin/base/example_solutions/waste_memory.py:/waste_memory.py python:2.7 python /waste_memory.py`), I get `"OOMKilled": false` but `"ExitCode": 137`.

However, here is what happens when I run the same code using bash:

```
$ docker run -it -m 1000m --memory-swap -1 -v /Users/putilin/base/example_solutions/waste_memory.py:/waste_memory.py python:2.7 bash
root@3a5beec90eb5:/# python /waste_memory.py
Killed
root@3a5beec90eb5:/# dmesg | tail -n 5
[26074.000000]     0 26074   501970   219067     962       5   265246             0 python
[26075.000000]     0 26075     2441       23       9       3        0             0 getty
[    0.000000] Out of memory: Kill process 26074 (python) score 880 or sacrifice child
[    0.000000] Killed process 26074 (python) total-vm:2007880kB, anon-rss:876268kB, file-rss:0kB
[    0.000000] docker0: port 1(veth8728d13) entered forwarding state
```

It is clearly being killed by OOM killer. However, when I run `docker inspect` I see `"OOMKilled": false` for some reason.

PS: I am on OS X, using docker-machine which automatically used boot2docker image. 

Providing system information:

So, I think I provided all the steps, as for the system information. I am on OS X, I am using docker-machine with virtualbox as a driver. 

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 19:47:52 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 40
Images: 37
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: ZL7J:LSB7:3B5E:MUWQ:EW5T:5QXF:OWPE:NKW7:7SS2:LP4M:GGRN:ACSR
Debug mode (server): true
File Descriptors: 11
Goroutines: 20
System Time: 2015-08-16T19:44:09.773836677Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: eleweek
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

```
$ uname -a
Darwin putilin-osx.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by eleweek** [comment]
So, I think I provided all the steps, as for the system information. I am on OS X, I am using docker-machine with virtualbox as a driver. 

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 19:47:52 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 40
Images: 37
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: ZL7J:LSB7:3B5E:MUWQ:EW5T:5QXF:OWPE:NKW7:7SS2:LP4M:GGRN:ACSR
Debug mode (server): true
File Descriptors: 11
Goroutines: 20
System Time: 2015-08-16T19:44:09.773836677Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: eleweek
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

```
$ uname -a
Darwin putilin-osx.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by clnperez** [comment]
I wonder if this is an issue with the child container state not inheriting its parent's state.

**Comment by Spritekin** [comment]
I got the same problem. A job starts a container, then crashes with an error 137, but no OOM flag is set. 
I know the problem is OOM because I increased the allocated RAM and it run fine. I reduced it again and it crashed, but no OOM flag set.
As the OP I'm running with --memory-swap -1, it might be the reason.

**Comment by thaJeztah** [comment]
Looking at the example, I think this may actually be the kernel randomly killing of processes before the memory-limit taking effect. Basically;

```
Total Memory: 996.2 MiB
```

So the memory-limit (set to `1000m`) will never be active before the whole machine runs out of memory. Also see the difference in output;

```
Memory cgroup out of memory: Kill process 19417 (python) score 890 or sacrifice child
```

and

```
Out of memory: Kill process 26074 (python) score 880 or sacrifice child
```

In the first one, the memory reaches the limit set in the cgroup for the container. In the second case, the memory-limit hasn't been reached, but the system is running out of memory, so a random process is killed.

Based on the above, it doesn't look like there's a bug here, and this works as intended

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
