### ISSUE TITLE
Stopping paused containers

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#15853]
Right now the API will send an error when someone tries to call `stop` or `kill` on a paused container.
This is because signals alone don't do anything to processes that have been frozen by cgroup freezer.

However once the process is unfrozen the kernel will go ahead and send those signals.
We should be able to update the API to go ahead and send the requested signal to the container, then automatically unpause it.

This is better than asking the user to unpause it first as the container may be paused due to some bad behavior in the container.

Introducing this behavior would also allow us to remove the work-around added in #13304

**Comment by coolljt0725** [comment]
+1 for this, we should have a way to sop or kill a paused container directly, because  if some containers was paused by some reason and unpause it would case some unsafe problem. I can work on this if we really need this.

**Comment by LK4D4** [comment]
Still an issue.

**Comment by dannydulai** [comment]
absolutely... I have a container that iIve paused and now it would be very dangerous to unpause it.

**Comment by cpuguy83** [comment]
Opened #34027 to resolve this

**Comment by thaJeztah** [comment]
The PR implementing this (https://github.com/moby/moby/issues/34027) will be included in the upcoming Docker 17.07 release
