### ISSUE TITLE
Proposal: A place to provide contribution statistics

### ISSUE THREAD

**Issue by Pensu** [moby/moby#15944]
Hi,

So, I am thinking that we should have a project where we can store/present contribution statistics, like how many contribution did a developer make, and the number of contributions in a particular release etc. Something like http://stackalytics.com/. Any thoughts?

**Comment by thaJeztah** [comment]
ping @icecrime might be something you're interested in?

**Comment by icecrime** [comment]
That's definitely something I'd like us to have.

I'm (slowly) working on some dashboards internally, but I'm not sure I will be able to share them as they are. However, I'll have the data, so we should be able to build some sort of dashboard, probably less fancy that stackalytics is though!

**Comment by duglin** [comment]
+1 a stackalytics version of Docker would be great!

**Comment by Pensu** [comment]
@icecrime That's great. Let me know if you need any help with that!

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
We have the "Docker Bulletin" repository https://github.com/icecrime/docker-bulletin/blob/master/repositories/docker.docker/2016-09-17.md, which is generated from the stats we have, and there's some internal dashboards. but afaik no active work on making those publicly accessible (@icecrime?)

**Comment by icecrime** [comment]
No active work indeed :-( It's of course not that the data isn't public, it's just that it needs infrastructure work as there's no easy way to have a public facing Kibana instance... I don't know enough there, sorry :-(

The only easy way out is to screenshot the dashboard at a given frequency and have those available somehwere.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
