### ISSUE TITLE
Docker build should support chattr

### ISSUE THREAD

**Issue by tranceitionalMynd** [moby/moby#15959]
I want to chattr custom /bin/uname and /bin/arch files and make sure they don't get replaced later by setting the immutable flag on them during the build step.  Currently, I think this can only be done by using "docker run --privileged" which would be hacky to do as part of my image build process.

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

docker info
Containers: 39
Images: 106
Storage Driver: devicemapper
 Pool Name: docker-253:1-1175046-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 7.254 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.51 GB
 Metadata Space Used: 10.8 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Data loop file: /media/docker/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /media/docker/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.798 GiB
Name: builder
ID: UDUT:CUP5:KCRC:QMZ7:MPH3:CM3D:5JE7:ASC3:T2QC:ILQZ:65HF:GZX6

uname -a
Linux builder 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

cat Dockerfile
FROM busybox
RUN chattr +i /bin/uname

docker build -t asdf ./
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon
Step 0 : FROM busybox
 ---> 8c2e06607696
Step 1 : RUN chattr +i /bin/uname
 ---> Running in 45d5d3a99246
chattr: setting flags on /bin/uname: Operation not permitted
 ---> c39f3e7f364c
Removing intermediate container 45d5d3a99246
Successfully built c39f3e7f364c

docker run --rm asdf lsattr /bin/uname
------------- /bin/uname

**Comment by cpuguy83** [comment]
ping @LK4D4 
WDYT? This would require `CAP_LINUX_IMMUTABLE`
Doesn't seem like this would be harmful.

**Comment by wulonghui** [comment]
I also have this issue,  any solution?

**Comment by foxx** [comment]
This is surprisingly default behaviour to say the least, any ideas when it'll get fixed?

**Comment by ewindisch** [comment]
I suspect this would break some graph drivers.

**Comment by foxx** [comment]
I've had a look into `CAP_LINUX_IMMUTABLE`, it seems to set inode flags [`FS_APPEND_FL`][1] (writes to file may only append) and [`FS_IMMUTABLE_FL`][2] (immutable file), with no other side effects. As far as I can tell, there are no security implications of adding this, although having sign off from someone with experience in the kernel would be nice.

[1]: http://lxr.free-electrons.com/source/include/uapi/linux/fs.h?v=3.7#L173
[2]: http://lxr.free-electrons.com/source/include/uapi/linux/fs.h?v=3.7#L172

**Comment by pandada8** [comment]
any updates?

**Comment by o6uoq** [comment]
+1

**Comment by foxx** [comment]
@pandada8 You'll be waiting a long time, just set the caps manually for now.

**Comment by o6uoq** [comment]
Hi,

What do you mean 'just set the caps manually' - any help/guidance would be appreciated :)

D.

**Comment by thaJeztah** [comment]
@o6uoq I think @foxx means using `--cap-add`

**Comment by justincormack** [comment]
I don't know how useful this is for `docker build` as extended attributes will not be transferred to the image, so they will be lost when you run.

**Comment by mitar** [comment]
I would also like this feature. It would make easier to assure that during build some critical files inside our image are not overridden by accident by some other package and are at the precise content/version we want. When one is installing multiple packages, it can be that there are some conflicting versions and different dependencies override same files. Setting this flag on files from version we want/expect would mean build would fail if there is a conflict by some other package trying to override them.

**Comment by mitar** [comment]
The issue seems that if you do set `+i` on some files, then such layer cannot be removed by Docker. So you have to make sure you unset it before trying to ask Docker to remove such file.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
