### ISSUE TITLE
Can't reach docker container via localhost anymore

### ISSUE THREAD

**Issue by farnzworld** [moby/moby#15977]
Problem:
I have a docker container with glassfish and one with postgres. Last week I tried to set up this combination on my server (debian 7) and failed to reach the glassfish web-context via localhost (-> curl -v http://localhost:8080/). At first I thought my iptable settings were so messed up, that I block myself, but then I encountered the same problem on my laptop. On the other side, docker opens all its ports to the world via iptables. Following data is from my laptop.

docker version:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 7
Images: 65
Storage Driver: devicemapper
 Pool Name: docker-8:1-6160664-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.576 GB
 Data Space Total: 107.4 GB
 Data Space Available: 32.08 GB
 Metadata Space Used: 5.394 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-1-ARCH
Operating System: Arch Linux
CPUs: 2
Total Memory: 3.705 GiB
Name: farnzmobile
ID: UQ7M:HGIZ:KMX3:B6OT:3BNJ:V547:SZTP:34KG:CGR6:QPQG:KNYM:GUOE

uname -a:
Linux farnzmobile 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

iptables -V:
iptables v1.4.21

sudo iptables -L: 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination  
DOCKER     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination  
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:postgresql
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:intermapper
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:appserv-http

Steps:
I recognized this problems about a week ago. Last time I worked with docker before, was about the end of May. I keep my systems regularly up to date.

**Comment by cpuguy83** [comment]
How did you run the container?

**Comment by farnzworld** [comment]
database is a modified postgres 9.3 container (internal shell script modified for advanced rights for the db user)
webapplication is a glassfish 4.1 container with updated libs

Data-Container:
docker run --name db-data -v /data -e PGDATA=/data -it --entrypoint /bin/bash database:9.3

Database-Container:
docker run -d --name db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e PGDATA=/data -p 5432:5432 --volumes-from db-data database:9.3

docker run -d --name webApp --link db:db -p 8080:8080 -p 8181:8181 -p 4848:4848 webapplication:base-9.3

**Comment by cpuguy83** [comment]
@farnzworld Can you paste docker daemon arguments used to start docker?

**Comment by farnzworld** [comment]
/usr/bin/docker daemon -H fd://

**Comment by farnzworld** [comment]
I found a solution for my arch linux system with docker 1.8.1:
sudo iptables -A FORWARD -i docker0 -o lo -j ACCEPT
sudo iptables -A FORWARD -i lo -o docker0 -j ACCEPT

What's odd, because the standard policy is is set to ACCEPT for all chains (INPUT, OUTPUT, FORWARD)

**Comment by sanderboom** [comment]
Same problem on Arch & Docker 1.8.1, and @farnzworld solution worked

**Comment by thaJeztah** [comment]
Let me close this one, as it went stale
