### ISSUE TITLE
default Docker NAT on Mac incorrectly changes source address of outside hosts

### ISSUE THREAD

**Issue by rohanmahy** [moby/moby#16010]
I need to run a UDP server (specifically a RADIUS server) inside a container that will be accessible from hosts on the same ethernet subnet as my Mac. Unfortunately Docker or VirtualBox are mangling the source IP address. I am running Docker 1.8.1b + VirtualBox 5.0.2.

_IP configuration_
Mac is on 192.168.1.40
VM eth0 (NIC1) is nat with IP 10.0.2.15/24 (default gateway 10.0.2.2)
VM eth1 (NIC2) is hostonly with IP 192.168.99.100/24
VM docker0 is 172.17.42.1/16
container IP is 172.17.0.8/16 

_What I did to enable forwarding_
I have `EXPOSE 1812/udp` in the Dockerfile.
I map the container port to the VM with `docker run -p 10.0.2.15:1812:1812/udp image`
I map the Mac port to the VM with `VBoxManage controlvm natpf1 'foo,udp,192.168.1.40,1812,10.0.2.15,1812'`

When I send UDP packets from 192.168.1.103 and .104 (same subnet as my Mac) they arrive at the container but **both** with an apparent source IP address of 10.0.2.2 (the default gateway of the VM). This is totally wrong behavior for a NAT and is especially problematic for RADIUS because the RADIUS server uses the source IP address to lookup the correct RADIUS secret. 

Is there a workaround for this?

**Comment by LK4D4** [comment]
@justincormack Do you know if it was handled in d4m?

**Comment by justincormack** [comment]
This should work on Docker for Mac - can you try?

**Comment by thaJeztah** [comment]
Closing; looks like this went stale
