### ISSUE TITLE
List of error codes

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#16034]
It would be useful to have a list of error codes and their corresponding cause. This could be in a tabular format such as:

| Error Code | Meaning |
| --- | --- |
| NNN | Text |
| NNN | Text |

**Comment by duglin** [comment]
See https://github.com/docker/docker/pull/15069  its the start of that piece of work.

**Comment by arun-gupta** [comment]
Cool, good to see that there is already work happening on it.

**Comment by AkihiroSuda** [comment]
Documented in https://docs.docker.com/engine/api/v1.40/
