### ISSUE TITLE
[1.8.1] Cannot stop/rm a container

### ISSUE THREAD

**Issue by vaceletm** [moby/moby#16047]
I got one container I can no longer remove:

```
$> docker stop e0175157cdda
Post http:///var/run/docker.sock/v1.20/containers/e0175157cdda/stop?t=10: EOF.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
Error: failed to stop containers: [e0175157cdda]
```

Of course the daemon is running and I can create and delete/stop containers.
What can I do ?

```
Containers: 12
Images: 655
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 691
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.677 GiB
WARNING: No swap limit support
```

docker version

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by anthonygreen** [comment]
does `sudo docker stop e0175157cdda` work ?

**Comment by mountkin** [comment]
Perhaps the daemon crashed when you try to stop the container.
Can you provide the logs in `/var/log/upstart/docker.log` as well?

**Comment by vaceletm** [comment]
@anthonygreen I was root when I ran the command

@mountkin here is the stack trace of a rm
```
INFO[1749] DELETE /v1.20/containers/tuleap_web_1?force=1&v=1 
2015/09/03 16:18:25 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 171 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc208412b40, 0x9, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:387 +0x3b5
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc208412b40, 0x9, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:405 +0x58
github.com/docker/docker/daemon.(*Container).Kill(0xc208412b40, 0x0, 0x0)
```
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:463 +0xdb
github.com/docker/docker/daemon.(*Daemon).rm(0xc2080a28c0, 0xc208412b40, 0x1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/delete.go:64 +0x101
github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc2080a28c0, 0xc208587199, 0xc, 0xc20857f915, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/delete.go:48 +0x4d1
github.com/docker/docker/api/server.(*Server).deleteContainers(0xc20809f4c0, 0xc208587189, 0x4, 0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0, 0xc2087488d0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1008 +0x21c
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.deleteContainers)·fm(0xc208587189, 0x4, 0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0, 0xc2087488d0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1682 +0x7b
github.com/docker/docker/api/server.func·008(0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc2081cc000, 0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20813ec80, 0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081aecc0, 0x7f82be147ce0, 0xc2088cb900, 0xc20880b5f0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2088cb2c0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by mountkin** [comment]
The same problem as #14845 and #14199

**Comment by obi12341** [comment]
Same Problem here:
```2015/09/10 11:42:32 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 141 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc20813bc20, 0xf, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:387 +0x3b5
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc20813bc20, 0xf, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:405 +0x58
github.com/docker/docker/daemon.(*Container).Stop(0xc20813bc20, 0xa, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:498 +0x93
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc208069260, 0xc208606cd7, 0xc, 0xa, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stop.go:13 +0x12b
github.com/docker/docker/api/server.(*Server).postContainersStop(0xc2080352c0, 0xc208606cc7, 0x4, 0x7f885fa75840, 0xc20819c5a0, 0xc208388a90, 0xc208626720, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1087 +0x1e1
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStop)·fm(0xc208606cc7, 0x4, 0x7f885fa75840, 0xc20819c5a0, 0xc208388a90, 0xc208626720, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1668 +0x7b
github.com/docker/docker/api/server.func·008(0x7f885fa75840, 0xc20819c5a0, 0xc208388a90)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc208035580, 0x7f885fa75840, 0xc20819c5a0, 0xc208388a90)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20812caf0, 0x7f885fa75840, 0xc20819c5a0, 0xc208388a90)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081bfce0, 0x7f885fa75840, 0xc20819c5a0, 0xc208388a90)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20819c460)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e```

Is there any way to kill this container? A workaround or smth?

**Comment by michaelperrin** [comment]
Same question here, using Docker 1.8.2. Is there a workaround to kill or stop the container?

**Comment by cpuguy83** [comment]
Indeed this is a dup, unfortunately finding the others is difficult...

**Comment by mausch** [comment]
Same with 1.8.3 . Can't seem to find any workarounds.

**Comment by cpuguy83** [comment]
@mausch This is likely happening because the container was partially removed and the daemon was restarted... so the container is registering, but there's things missing.
To fix, I would remove the dir `/var/lib/docker/containers/<container id>` then restart docker.

**Comment by mausch** [comment]
@cpuguy83 Thanks, I just restarted the daemon and then was able to stop the container. But I'll keep your workaround in mind :)

**Comment by thaJeztah** [comment]
@cpuguy83 so, is this just a one-off incident, or something that needs a fix (e.g., make the container removal more atomic)?

**Comment by mausch** [comment]
At least in my case, this seems to have started when I upgraded from 1.6.2 to 1.8.3. Perhaps this "partial removal" is due to some data missing in the old version? 
It only happened with a couple of containers, but it was cumbersome to find out because docker reports these containers as running even though they are not.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
