### ISSUE TITLE
docker fails to start memcached container after reboot

### ISSUE THREAD

**Issue by stapelberg** [moby/moby#16242]
Description of problem:

I’m running CoreOS in a VM, and that CoreOS instance recently rebooted itself due to a software upgrade:

``` text
Sep 09 16:42:31 dock1 systemd-logind[448]: System is rebooting.
[…]
Sep 09 16:42:35 dock1 systemd[1]: Stopping Docker Application Container Engine...
Sep 09 16:42:35 dock1 dockerd[4858]: time="2015-09-09T16:42:35Z" level=info msg="Received signal 'terminated', starting shutdown of docker..."
Sep 09 16:42:35 dock1 systemd[1]: Stopped Docker Application Container Engine.
```

When it came back up again, docker wouldn’t start my memcached container:

``` text
Sep 09 16:42:59 dock1 dockerd[535]: time="2015-09-09T16:42:59.323933824Z" level=info msg="Loading containers: start."
Sep 09 16:43:00 dock1 dockerd[535]: .............................................
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.042939686Z" level=info msg="Loading containers: done."
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.042979359Z" level=info msg="Daemon has completed initialization"
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.043001162Z" level=info msg="Docker daemon" commit=2c2c52b-dirty execdriver=native-0.2 graphdriver=overlay version=1.7.1
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.043054605Z" level=info msg="Listening for HTTP on fd ()"
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.043793269Z" level=info msg="POST /v1.19/images/create?fromImage=nginx%3A1"
Sep 09 16:43:00 dock1 dockerd[535]: time="2015-09-09T16:43:00.044235558Z" level=info msg="POST /v1.19/images/create?fromImage=memcached%3Alatest"
Sep 09 16:43:02 dock1 dockerd[535]: time="2015-09-09T16:43:02.218497992Z" level=info msg="Image manifest for nginx:1 has been verified"
Sep 09 16:43:02 dock1 dockerd[535]: time="2015-09-09T16:43:02.285148005Z" level=info msg="Image manifest for memcached:latest has been verified"
Sep 09 16:43:08 dock1 dockerd[535]: time="2015-09-09T16:43:08.046340805Z" level=error msg="Error from V2 registry: Driver overlay failed to create image rootfs 698d48539402381fc20f20899670dba347ca0da45543e11541de8e457feb2a53: lstat /var/lib/docker/overlay/4a5e6db8c0693a16de88b7559ded7c1cb804018571b137e13abb1713ce6a71cf: no such file or directory"
Sep 09 16:43:13 dock1 dockerd[535]: time="2015-09-09T16:43:13.468076237Z" level=error msg="Error from V2 registry: lstat /var/lib/docker/overlay/2c49f83e0b13f73bf3d276c9fe26ba9aa94d2a1614e866642b95cb0245d0cdab/root/media: no such file or directory"
```

Rebooting the machine did not fix the issue.

After stopping docker, running `rm -rf /var/lib/docker/overlays/*` and restarting docker, docker successfully pulled and started the memcached container.

I’d argue that docker should never get into a state where it cannot start containers, and the error message I’ve gotten isn’t particularly helpful either.

`docker version`:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2c2c52b-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2c2c52b-dirty
OS/Arch (server): linux/amd64

I’m on CoreOS’s stable track, and the version before 766.3.0 is 723.3.0, which contained docker 1.6.2 on linux 4.0.5.

`docker info`:
Containers: 17
Images: 36
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-coreos-r1
Operating System: CoreOS 766.3.0
CPUs: 2
Total Memory: 3.864 GiB
Name: dock1
ID: HCKC:XNI4:IT5L:PROQ:ZGYH:NAYT:YO3E:XRHU:AHZG:MNLO:THXT:2F3Z

`uname -a`:
Linux dock1 4.1.6-coreos-r1 #2 SMP Wed Sep 2 04:16:15 UTC 2015 x86_64 QEMU Virtual CPU version 1.1.2 AuthenticAMD GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
KVM

How reproducible:
Haven’t tried.

Additional info:

This is the systemd service file I use to start memcached:

``` text
# cat /etc/systemd/system/i3faq-memcached.service 
[Unit]
Description=memcached
After=docker.service
Requires=docker.service

[Service]
Restart=always
StartLimitInterval=0
ExecStartPre=/usr/bin/docker pull memcached:latest
ExecStartPre=-/usr/bin/docker kill memcached
ExecStartPre=-/usr/bin/docker rm -f memcached
ExecStart=/usr/bin/docker run \
  --name memcached \
  --read-only \
  --entrypoint=/usr/local/bin/memcached \
  memcached \
    -m 64

[Install]
WantedBy=multi-user.target
```

**Comment by LK4D4** [comment]
Btw I saw such errors too. I wonder if it's some unfinished cleanup on ungraceful restart.

**Comment by nudgegoonies** [comment]
We have this error regulary on two gitlab-ci-runners that use docker very extensive. We use Kernel 4.9.51 in combination with docker ce 17.06.0. We use an ext4 filesystem exclusive for /var/lib/docker/overlay2 which is the mountpoint. We prune every 30 minutes. Could it be that this deletes stuff that is still needed?

**Comment by nudgegoonies** [comment]
We don't have this error anymore.
