### ISSUE TITLE
Upper bound on restart delay

### ISSUE THREAD

**Issue by andrewmichaelsmith** [moby/moby#16368]
Previously discussed in #9759, for our case the ever increasing restart delay of the restart on error policy is causing us issues because it can get very big (many hours).

If a database goes down our applications will keep restarting until it comes back up. We are using the restart policy to achieve this. However - if the database is down for any long amount of time, the restart delay can be hours. This is obviously not useful for us - we want our applications to try and start in seconds or minutes.

For our purposes a global upper bound on the limit would be acceptable. Is this something a pull request would be considered for?

**Comment by HuKeping** [comment]
I'm thinking if we could put a cap like 2 minute there?

**Comment by LK4D4** [comment]
@andrewmichaelsmith @HuKeping yes, it should be upper bounded. I think PR will be accepted. Sorry that it took so long to find this issue.

**Comment by TAGC** [comment]
Has this not been implemented yet?

**Comment by cpuguy83** [comment]
Yes, max restart back-off time is 1 minute.
https://github.com/moby/moby/blob/9bd3a7c0297fdb93deb846070c85ac23da0a20e8/restartmanager/restartmanager.go#L80-L82

Implemented in 9bd3a7c0297fdb93deb846070c85ac23da0a20e8

**Comment by azerum** [comment]
This is old, but any reasons to hardcode the value of 1 minute? Each user may have different needs on how quickly the service should restart

**Comment by thaJeztah** [comment]
@azerum could you open a new ticket instead, and describe the use case / problem you have in a bit more detail? Comments on closed issues easily get lost, and it's useful to have a better understanding of the problem you're trying to solve.
