### ISSUE TITLE
Push to private registry from Docker 1.8.2 produces unknown error.

### ISSUE THREAD

**Issue by robertfirek** [moby/moby#16374]
I've update my docker clients to version 1.8.1 (Macbook) and 1.8.2 (Linux). When I try to push image to my private registry I receive the following message:

```
The push refers to a repository [my.private.registry/myImage] (len: 1)
afedd571519b: Image already exists
88cb8f8f5608: Pushing [==================================================>] 1.305 kB/1.305 kB
unknown: Unable to upload blobs to a remote repository.
```

When I run the same command on version 1.7.1 I don't have any issues.

Registry run from docker image registry:2.1.1 (on NGINX proxy). 

Docker client 1 version:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

Docker client 2 version:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

Docker client 2 logs:

```
time="2015-09-17T10:46:49.923645674Z" level=debug msg="Calling POST /images/{name:.*}/push"
time="2015-09-17T10:46:49.923697907Z" level=info msg="POST /v1.20/images/my.private.registry/myImage/push?tag=110"
time="2015-09-17T10:46:49.953651235Z" level=debug msg="hostDir: /etc/docker/certs.d/my.private.registry"
time="2015-09-17T10:46:49.953815314Z" level=debug msg="Trying to push my.private.registry/myImage to https://my.private.registry v2"
time="2015-09-17T10:46:50.108017384Z" level=debug msg="Checking \"110\" against graph.Repository{\"110\":\"06caef6ba17673051617dc360d084d61680f645ee6443c8d14e46afd75753bef\"}"
time="2015-09-17T10:46:50.108631967Z" level=debug msg="Pushing repository: myImage:110"
time="2015-09-17T10:46:50.109222664Z" level=debug msg="Pushing layer: 06caef6ba17673051617dc360d084d61680f645ee6443c8d14e46afd75753bef"
time="2015-09-17T10:46:51.198450688Z" level=debug msg="Pushing layer: 3935ec903bd30eeaf2eefd5958cbd3330e698b38e354f3a2238af0bb53b40799"
time="2015-09-17T10:46:51.370436253Z" level=debug msg="[graph] TarLayer with reassembly: 3935ec903bd30eeaf2eefd5958cbd3330e698b38e354f3a2238af0bb53b40799"
time="2015-09-17T10:46:51.370684665Z" level=debug msg="[graph] 3935ec903bd30eeaf2eefd5958cbd3330e698b38e354f3a2238af0bb53b40799 is at \"/mnt/sda1/var/lib/docker/aufs/mnt/3935ec903bd30eeaf2eefd5958cbd3330e698b38e354f3a2238af0bb53b40799\""
time="2015-09-17T10:46:51.375391301Z" level=debug msg="rendered layer for 3935ec903bd30eeaf2eefd5958cbd3330e698b38e354f3a2238af0bb53b40799 of [135] size"
time="2015-09-17T10:46:51.814760931Z" level=debug msg="Not continuing with error: unknown: Unable to upload blobs to a remote repository."
```

**Comment by vishalvsh1** [comment]
I am also facing same issue.

docker version:
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 0
Images: 18
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 29.45 GiB
Name: jenkins2.prod-release.olacabs.net
ID: DVPP:KZHB:QPRO:FU7K:3UGU:HHQS:IEZD:D5IS:H547:DHKZ:NINO:DIFI
WARNING: No swap limit support

uname -a:
Linux jenkins2.prod-release.olacabs.net 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

its aws machine

Steps
1. Created Image
2. tagged image 
docker tag entit:0.0.1-SNAPSHOT artifactory.something.com:5002/entit:0.0.1-SNAPSHOT
3. Pushing the image
+ docker push artifactory.something.com:5002/entit:0.0.1-SNAPSHOT
The push refers to a repository [artifactory.something.com:5002/entit] (len: 1)
7cbb85593880: Buffering to Disk
7cbb85593880: Image successfully pushed
c531daf06980: Buffering to Disk
unknown blob

4. When i checked the repo and tried to pull the image, i was able to pull.
docker pull artifactory.something.com:5002/entit:0.0.1-SNAPSHOT
0.0.1-SNAPSHOT: Pulling from entitystore
0f0a9711963c: Pull complete 
e6b8fa445a2d: Pull complete 
b216b2445a50: Pull complete 
c5c00563e7fb: Pull complete 
0087662cba47: Pull complete 
c55f539f6808: Pull complete 
b95540f6cd8a: Already exists 
0105f98ced6d: Already exists 
66395c31eb82: Already exists 
002fa881df8a: Already exists 
a005e6b7dd01: Already exists 
Digest: sha256:58d5f6afcfa72d6f4a6c5b2adcca459d20a5debe4bf8c30c5f980826e50bbdc2
Status: Downloaded newer image for artifactory.something.com:5002/entit:0.0.1-SNAPSHOT

**Comment by thaJeztah** [comment]
@vishalvsh1 based on the name of your private repository, I'm assuming you're using artifactory, and you're issue could have a whole different cause.

**Comment by vishalvsh1** [comment]
@thaJeztah, Yes you are right partially, it looks like it was some sort of permission issue.
It seems they(docker) have changed some behavior from 1.6 to 1.8 on authentication part. 
Same configuration was working on 1.6, but it wasn't working for 1.8. 
We fixed this issue by changing artifactory configuration. So i can not say its bug or feature introduced with 1.8 docker client.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
