### ISSUE TITLE
docker restart silently does nothing when provided a slash-prefixed container name

### ISSUE THREAD

**Issue by BrianBland** [moby/moby#16563]
Description of problem:
When attempting to restart a container with a slash-prefixed name, the docker CLI (and engine API) act as if the operation was successful but don't actually restart the container.

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 1301
Images: 3793
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6397
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: 3YCN:IHBG:FR4D:TDIK:EL4I:YIIY:YUSE:BX73:DTYO:JQOO:A7HL:ZNK2
Username: brianbland
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`:

```
Linux vagrant-ubuntu-trusty-64 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox via docker toolbox

How reproducible:
Happens every time

Steps to Reproduce:
1. `docker run -d --name test busybox sleep 100`
2. `docker restart /test`
3. `echo $?`
4. `docker inspect /test`

This also happens when prefixing the container id with `/`, such as `docker restart /02bb798097e104046837b54f83afef7469cae9af278511e46a77486e44434768`.

Actual Results:
The name of the container as provided is printed out and the return code is 0.

Expected Results:
The container is restarted or an error is returned.

Additional info:
After further testing the same behavior is found with `stop` and `kill` and maybe other commands.

**Comment by coolljt0725** [comment]
@BrianBland  Follow your step, can't repoduce.
<pre><code>$ docker run -d --name test busybox sleep 100
168ec20a0b3b6b716e8c10764c57925ad94a40408f3590f86968c60be629c59a
$ docker restart /test
/test
$ echo $?
0
</code></pre>
`docker 1.8.2 git 0a8c2e3` 
`fedora 4.0.4-301.fc22.x86_64`

**Comment by BrianBland** [comment]
@coolljt0725: this is exactly the issue. It doesn't restart the container but returns 0 anyway as if it succeeded.

**Comment by coolljt0725** [comment]
@BrianBland  Sorry, I misunderstand your description.  I'll take a look

**Comment by coolljt0725** [comment]
@BrianBland  we can't has a prefix `/` in the container name. see https://github.com/docker/docker/blob/master/api/client/restart.go#L27
`_, _, err := readBody(cli.call("POST", "/containers/"+name+"/restart?"+v.Encode(), nil, nil))`
if we has a `/` prefix in the name, the API would be like `POST  /containers//test/restart` which is invalid.
I think we should truncate the prefix `/`

**Comment by thaJeztah** [comment]
Looks like this now works, at least from the CLI; `docker restart /test` restarts the container.

We still need to look at removing the `/` prefix at some point, but that's tracked in https://github.com/moby/moby/issues/29997
