### ISSUE TITLE
Debug logs should trace a 302/301 when pulling an image

### ISSUE THREAD

**Issue by sdodson** [moby/moby#16588]
Just got done debugging some image pull problems. It'd be helpful if when pulling images redirects are noted in the logs

**Comment by LK4D4** [comment]
Why not. Sounds like valid debug info.

**Comment by krasi-georgiev** [comment]
@LK4D4 , @thaJeztah - is this still ongoing ? 
I want to give it a try.

**Comment by thaJeztah** [comment]
I don't think anyone is working on it, but also must add that this is the only request, and only time I've seen it requested, so it may depend on the amount of code to maintain if it will be accepted

**Comment by thaJeztah** [comment]
Let's close this one in favor of https://github.com/moby/moby/issues/6927
