### ISSUE TITLE
AppArmor profile should include a `#include <local/docker>` line

### ISSUE THREAD

**Issue by frioux** [moby/moby#16705]
Description of problem:

Docker uses AppArmor on Ubuntu, which is great, but without an include line as mentioned above the user is forced to modify the file _every time she upgrades docker._  This is both very frustrating and already solved by local include files in more typical dists.  See `/etc/apparmor.d/local/README` on ubuntu for details.

`docker version`: 

``` Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`: 

```
Containers: 5
Images: 154
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 15.37 GiB
Name: zfp
ID: WWAV:EBRG:XQKU:LLZ7:JUMU:MDR4:BPJ4:C7T3:XKVQ:WFUT:3DAP:6ZHU
WARNING: No swap limit support
```

`uname -a`:
`Linux zfp 3.19.0-30-generic #33-Ubuntu SMP Mon Sep 21 20:58:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details: n/a

How reproducable: 100%

Steps to reproduce:
1. Install docker
2. Be frustrated when ptrace doesn't work in a container (eg rsyslog, monit, and strace all break) and you have to add a ptrace line to /etc/apparmor.d/docker and restart the apparmor "service"

Actual Results: annoyance and frustrating ;)

Expected Results: the ability to tweak this once and have it Just Work

**Comment by cpuguy83** [comment]
ping @ewindisch

**Comment by ewindisch** [comment]
This is a reasonable feature request.

**Comment by Thell** [comment]
:+1:

**Comment by frioux** [comment]
For others who this might be driving crazy every time there is an upgrade, here is a workaround to entirely disable apparmor for docker till it's fixed: `dpkg-divert --divert /etc/diverted-docker --rename /etc/apparmor.d/docker`

**Comment by Thell** [comment]
@frioux Disabling the apparmor profile completely shouldn't be needed unless _your or her_ apparmor version is too old and doesn't support either of the following additions to `/etc/apparmor.d/abstractions/base`

````
ptrace (trace) peer=docker-default,

# or

ptrace (trace) peer=@{profile_name},

````

I opted for the specific `docker-default` instead of opening all profiles to trace.

**Comment by ewindisch** [comment]
The ptrace issue is separate to supporting local changes to the profile. The ptrace bug was fixed but reverted due to apparmor compatibility issues (an updated fix is forthcoming). It would *also* be nice to be able to hotfix such issues locally and have a local default policy, which is how I see this specific issue.

**Comment by thaJeztah** [comment]
@ewindisch if there are issues around this that need to be picked into the next 1.9 RC, make sure to add it to the milestone and assign Tibor

**Comment by Thell** [comment]
I agree completely @ewindisch, just responding to the OP point 2 and the expressed frustration. A proper #include local setup is the real answer.

**Comment by frioux** [comment]
@Thell I changed my stuff to do what you said; it actually works better anyway.  Thanks!  Looking forward to this issue being changed but in the meantime the alternative makes me perfectly happy.

**Comment by jfrazelle** [comment]
This is fixed now https://github.com/docker/docker/pull/18178/files

**Comment by jfrazelle** [comment]
at least `ptrace` part, sorry reopening

**Comment by justincormack** [comment]
I am not sure about using `include` for local modifications, as it makes the meaning of the default policy depend on these. I think having a way to modify the default policy globally, ie as a daemon option, might be better (also potentially for seccomp).

**Comment by AkihiroSuda** [comment]
I agree with Justin. Let me close this issue.
