### ISSUE TITLE
Apache2 Permission denied AH00035

### ISSUE THREAD

**Issue by Tazeg** [moby/moby#16741]
BUG REPORT INFORMATION

docker version:
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 112
Images: 56
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 280
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.852 GiB
Name: ubunjeff
ID: 7PU2:EG7P:7OVK:TQAZ:HLJY:GXSQ:DMBF:SNEJ:GNMU:4D4C:ZGEO:ZXEI
WARNING: No swap limit support

uname -a:
Linux ubunjeff 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce the issue:

I have thoses files :

./www/jQuery/css/uidarkness/test.css

``` css
﻿.test { width:100%; }
```

./www/index.html

``` html
<link href="jQuery/css/uidarkness/test.css" rel="stylesheet" type="text/css"/>
```

./Dockerfile

``` bash
FROM debian
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update && apt-get install -y apache2
COPY ["www","/var/www/html"]
RUN chgrp -R www-data /var/www && find /var/www -type d -exec chmod 775 {} + && find /var/www -type f -exec chmod 664 {} +
EXPOSE 80
CMD ["/usr/sbin/apache2ctl","-DFOREGROUND"]
```

Build command line :
docker build -t test .

Running command :
docker run -d -p 80:80 test

Go to the browser :
http://localhost/

Use browser debug mode, inspect element. I can see error :
GET http://localhost/jQuery/css/uidarkness/test.css 403 (Forbidden)

Connect to the container :
docker exec -it e5947c26b5ec bash
cat /var/log/apache2/error.log
getting Apache error :
Permission denied: [client 172.17.42.1:38503] AH00035: access to /jQuery/css/uidarkness/test.css denied (filesystem path '/var/www/html/jQuery/css') because search permissions are missing on a component of the path, referer: http://localhost/

HOW TO FIX THE PROBLEM ?
Just type still in bash container :
ls /var/www/html/jQuery/css/uidarkness/
Refresh brower : fixed !
Is it magic ?

Files permissions into container are :
drwxrwxr-x 4 root www-data 4096 Oct  3 09:33 /var/www/html
-rw-rw-r-- 1 root www-data   80 Oct  3 09:32 /var/www/html/index.html
drwxrwxr-x 4 root www-data 4096 Oct  3 09:33 /var/www/html/jQuery
drwxrwxr-x 4 root www-data 4096 Oct  3 09:33 /var/www/html/jQuery/css
drwxrwxr-x 2 root www-data 4096 Oct  3 09:33 /var/www/html/jQuery/css/uidarkness
-rw-rw-r-- 1 root www-data   25 Oct  3 09:32 /var/www/html/jQuery/css/uidarkness/test.css

**Comment by thaJeztah** [comment]
Hm, I think I've seen a similar issue, which was related to the aufs driver. IIRC, using a [sync](http://linux.about.com/library/cmd/blcmdl8_sync.htm) worked on that occasion. You could also try to split up your `RUN chgroup...` line to multiple `RUN` statements, then work from that.

I'll try to find the reference to the other issue, but perhaps the above helps to find a solution.

**Comment by Tazeg** [comment]
Hi,

"RUN chgroup" on different lines did nothing.

Fixed by using "devicemapper" instead of "aufs" thanks to this post :
http://muehe.org/posts/switching-docker-from-aufs-to-devicemapper/

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
