### ISSUE TITLE
Cannot interupt `docker push` with SIGINT / ^C

### ISSUE THREAD

**Issue by frioux** [moby/moby#16777]
Description of problem:

If you ^C a docker push, the push keeps going in the background.  Preferably it
would cancel the way sigint does for docker run and docker build.  If for some
reason that can't happen, at least allowing the user to reconnect to the stopped
push would be nice.

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

```

`docker info`:

```
Containers: 2
Images: 53
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 15.56 GiB
Name: wanderlust
ID: X22W:GVF5:ZUZY:YZ67:TDF5:JUAT:5XO6:WQAR:DJMF:DT6Q:MXJK:LTE6
WARNING: No swap limit support
```

`uname -a`:

```
Linux wanderlust 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): bare metal

How reproducible: 100%

Steps to Reproduce:
1. docker push my-big-image
2. ^C
3. 😠

Actual Results:

Keeps pushing in background

Expected Results:

Cancelled push

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/6928, which is for "pull", but basically it's the same problem/issue

**Comment by frioux** [comment]
I figured that.

**Comment by vvoland** [comment]
This is no longer the case and push is correctly aborted when ^C'd and doesn't continue in the background.

Let me close this one.
