### ISSUE TITLE
SELinux and --security-opt interpretation

### ISSUE THREAD

**Issue by shaded-enmity** [moby/moby#16792]
Description of problem:
It seems that the SELinux --security-opt parsing is interpreted in reverse

`docker version`:

``` Client:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-1.gitf1db8f2.fc22.x86_64
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 92
Images: 199
Storage Driver: devicemapper
 Pool Name: docker-253:3-9700527-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 28.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 78.77 GB
 Metadata Space Used: 27.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.12 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /home/docker/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/docker/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 15.37 GiB
Name: localhost
ID: YQXU:IGKU:PEPP:K7ZO:KM4G:25YM:23KO:6MDZ:2TQF:26L4:4GLF:SSG4
Registry: https://index.docker.io/v1/
```

`uname -a`:
`Linux localhost 4.1.7-200.fc22.x86_64 #1 SMP Mon Sep 14 20:19:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

How reproducible:
Always

Steps to Reproduce:
`1.` reproducer:

```
docker run -td --security-opt label:disabled fedora bash
```

`2.` reproducer:

```
docker run -td --security-opt label:system_u:system_r:unconfined_t:s0:c0,c1023 fedora bash
```

Actual Results:
1. Error response from daemon: Bad SELinux Option
2. Success

Expected Results:
1. Sucecss
2. Error response from daemon: Bad SELinux Option

@rhatdan Please confirm.

**Comment by rhatdan** [comment]
The first one is correct the 

```docker run -td --security-opt label:disabled fedora bash```

should be

```docker run -td --security-opt label:disable fedora bash```

The second one is a selinux/label not returning an error.

**Comment by rhatdan** [comment]
Just opened a pull request for this.

**Comment by thaJeztah** [comment]
@rhatdan Is this fixed? was this vendored in docker already?

**Comment by rhatdan** [comment]
Not vendored yet.

**Comment by Omnifarious** [comment]
Where is the documentation for what things are valid to pass as arguments for `--security-opt` in the first place? How did you figure out that `label:disable` might even be a thing you could pass?

**Comment by thaJeztah** [comment]
@Omnifarious see https://docs.docker.com/engine/reference/run/#security-configuration

**Comment by thaJeztah** [comment]
Also, looking at https://github.com/opencontainers/runc/pull/320. The code moved around a bit since, but has been vendored, and is now here: https://github.com/moby/moby/blob/73c82386148fe14a47cc515c622bd23b9b7d99b9/vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go#L12-L19

Closing this issue, because the code was vendored since

**Comment by rhatdan** [comment]
Golden oldie.  :^(

**Comment by thaJeztah** [comment]
Haha, yes

**Comment by Omnifarious** [comment]
I'm hampered by the fact that Fedora ships a really old Docker. :-( And my Google searching for security-opt found this bug and none of the other links were particularly relevant. I will link to the docker run documentation in the questions I have on SO and ServerFault that touch on this topic.

**Comment by thaJeztah** [comment]
@Omnifarious official Docker packages for Fedora will give you a current version; https://docs.docker.com/install/linux/docker-ce/fedora/
