### ISSUE TITLE
Support for Debian Wheezy

### ISSUE THREAD

**Issue by bjoernjacobs** [moby/moby#16878]
I followed the installation steps at https://docs.docker.com/installation/debian/ for Debian Wheezy. However, I was unable to install the package docker-engine because of this error:

`The following packages have unmet dependencies: docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable`

In issue https://github.com/docker/machine/issues/1607 I read that if support for Wheezy is requested, an issue should be openend - which I'm doing with this.

We have a large cluster currently running many Debian Wheezy machines. They won't be upgraded to Debian 8 in the foreseeable future, so support for Debian 7 would be highly appreciated.

**Comment by cpuguy83** [comment]
Debian Wheezy's kernel is from 3.2, which is too old to run Docker.

**Comment by bjoern-jacobs** [comment]
I see. And if we used a backported newer kernel (what we actually do, 3.18)?

**Comment by lidel** [comment]
@bjoern-jacobs `init-system-helpers` (missing dependency) can be installed from backports repo.
Just  add `deb http://http.debian.net/debian wheezy-backports main`  at the end of `/etc/apt/sources.list` and run `apt-get update && apt-get install init-system-helpers`.

**Comment by tianon** [comment]
Yeah, if you want to use Docker on Wheezy, you'll need to use the backports
repository, especially for the kernel.

**Comment by bjoern-jacobs** [comment]
Thank you for your replies. I added the backports repository and did an `apt-get update`. Now when I try to install init-system-helpers, I get this message. Any suggestion how to proceed?

`$ sudo apt-get install init-system-helpers`
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`You might want to run 'apt-get -f install' to correct these:`
`The following packages have unmet dependencies:`
` cgroupfs-mount : Depends: mountall (> 2.48~) but 2.46 is to be installed`
`E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).`

**Comment by lidel** [comment]
I have `mountall` 2.46 and it works fine, but  I remember doing `aptitude update && aptitude safe-upgrade`  before installing `init-system-helpers`. 
It updated kernel and some packages and had no further problems.
Check if you have any pending/backported updates.

**Comment by ektich** [comment]
The https://docs.docker.com/engine/installation/linux/debian/ should be updated then, specifying that the Docker is NOT supported on Debian 7.7 Wheezy unless you enable backports (and by the look of it switch to systemd ?)

**Comment by thaJeztah** [comment]
@ektich hm, `systemd` should not be required, but it looks like some information was lost during a rewrite; this older version mentions the backports for Wheezy; https://github.com/docker/docker/blob/e6ca006d8634a0fa9c6eb655aa9c872b84c5e438/docs/installation/debian.md

**Comment by ektich** [comment]
@thaJeztah you're right, systemd is not required. But the docs should also mention init-system-helpers (available in backports, but it should be installed with an explicit "apt-get install init-system-helpers", after backports are properly configured.

**Comment by deed02392** [comment]
I found this issue as it's still not documented that back-ports must be enabled for wheezy to support the installation of docker-engine from the docker repos.

**Comment by AkihiroSuda** [comment]
Support for wheezy was dropped after the release of 18.03
https://download.docker.com/linux/debian/dists/wheezy/pool/stable/amd64/
