### ISSUE TITLE
remote api: wrong /logs content-type

### ISSUE THREAD

**Issue by gesellix** [moby/moby#16885]
Description of problem:

As described in the docs for [`/containers/(id)/logs`](https://docs.docker.com/reference/api/docker_remote_api_v1.20/#get-container-logs), the response Content-Type should be `application/vnd.docker.raw-stream`. Actually, it is always `text/plain`, using the current Docker 1.8.2 release.

Things become a bit more complex, though, because plain text works well as long as the container isn't running in detached mode (Config.Tty = false). Only for a detached container the logs will be a raw stream, supporting multiplexing on stdout and stderr.

For consistency with `../attach`, it would be nice to always return the raw stream (and declare it correctly via `Content-Type`), with disabled multiplexing for attached containers.

If you like, I can try to create a PR, but I was a bit lost in the different router/cli/daemon source files... any pointer or suggestions how to tackle this would help!

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 3
Images: 97
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: BDI6:3E4G:RBCP:BURV:FYFE:GEPK:J4QI:53U4:HKG4:ZUJW:XFCL:7A72
Debug mode (server): true
File Descriptors: 14
Goroutines: 23
System Time: 2015-10-09T15:50:19.097175534Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: gesellix
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

`uname -a`:

```
Darwin foo.bar 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
Mac w/ Docker Toolbox

How reproducible:
always

Steps to Reproduce:
1. run the Docker daemon
2. `docker run -d --name container-id busybox:latest ping 127.0.0.1`
3. `GET https://docker.host:2376/containers/container-id/logs?follow=true&stdout=true&stderr=true&timestamps=false&since=0`

Actual Results:

```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Fri, 09 Oct 2015 15:55:53 GMT
Server: Docker/1.8.2 (linux)
Transfer-Encoding: chunked
```

Expected Results:

```
HTTP/1.1 101 UPGRADED
Connection: Upgrade
Content-Type: application/vnd.docker.raw-stream
Date: Fri, 09 Oct 2015 15:55:53 GMT
Upgrade: tcp
Server: Docker/1.8.2 (linux)
```

Additional info:

**Comment by gesellix** [comment]
The docs for the current api version 1.41 now explicitly [describe the response headers](https://docs.docker.com/engine/api/v1.41/#operation/ContainerLogs) regarding the encoding and content-type:

> logs returned as a stream in response body. For the stream format, [see the documentation for the attach endpoint](https://docs.docker.com/engine/api/v1.41/#operation/ContainerAttach). Note that unlike the attach endpoint, the logs endpoint does not upgrade the connection and does not set Content-Type.

I still wonder why the api has such inconsistent behaviour, but at least it's documented now.

**Comment by thaJeztah** [comment]
> I still wonder why the api has such inconsistent behaviour, but at least it's documented since #38819.

I recall there was some discussion around this on https://github.com/moby/moby/issues/35761 and https://github.com/moby/moby/pull/39812

**Comment by gesellix** [comment]
Thanks for the links @thaJeztah, I'm going to follow those issue/pr :)
