### ISSUE TITLE
Default hosts file contents should contain localhost.localdomain

### ISSUE THREAD

**Issue by Firstyear** [moby/moby#16912]
Most big distributions contain a hosts file that contains as the first entries:

127.0.0.1   localhost.localdomain localhost
::1         localhost.localdomain localhost

This is true on Fedora and RHEL, and some research indicates it's the same on debian and ubuntu.

However, docker's default hosts file creates:

127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback

Would be it possible to change the defaults in docker's created /etc/hosts to:

127.0.0.1   localhost.localdomain localhost
::1         localhost.localdomain localhost ip6-localhost ip6-loopback

This shouldn't affect existing applications or containers, and fixes a few edge cases of applications that expect a domain name to be available on the system.

**Comment by konstruktoid** [comment]
Agreed, but I suggest adding localhost.localdomain as a alias, so 127.0.0.1 resolvs to localhost by default.

When it comes to Debian and Ubuntu, I believe they removed localhost.localdomain in 2005 (https://lists.debian.org/debian-devel/2005/10/msg00587.html).

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Wily Werewolf (development branch)
Release:        15.10
Codename:       wily
$ cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       ubulab

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
$
```

```sh
$ cat /etc/redhat-release
Fedora release 22 (Twenty Two)
$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
$
```

**Comment by Firstyear** [comment]
Some applications require there to be a domain name available, which is why I think the ordering should be:
127.0.0.1 localhost.localdomain localhost

So that a host lookup of 127.0.0.1 returns the fqdn, rather than the short name. For applications that don't need this, they will split the localdomain part off  and for the applications that do need the fqdn, this will potentially fix some issues.

Perhaps there should be an easier way in docker to specify the contents for the 127.0.0.1/::1 addresses so that both styles can be provided?

**Comment by konstruktoid** [comment]
I have yet to see a distro that uses `127.0.0.1 localhost.localdomain localhost`. Can you please post and example?

```sh
[rancher@rancher ~]$ cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.1.1 rancher.lan
[rancher@rancher ~]$
```

**Comment by Firstyear** [comment]
Centos / Redhat both provide this in the hosts file.

Is there really something that could go so wrong by adding localhost.localdomain to the hosts file in docker?

**Comment by thaJeztah** [comment]
ping @mrjana @mavenugo any preference on this one?

**Comment by LK4D4** [comment]
still an issue
ping @sanimej @aboch @mrjana @mavenugo

**Comment by carrete** [comment]
@konstruktoid 

> I have yet to see a distro that uses 127.0.0.1 localhost.localdomain localhost. Can you please post and example?

From https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html

    The hostnames "localhost" and "localhost.localdomain" (as well as any
    hostname ending in ".localhost" or ".localhost.localdomain") are resolved
    to the IP addresses 127.0.0.1 and ::1.

**Comment by konstruktoid** [comment]
Thanks @carrete, I've long since forgotten this issue. Nice too see that things have changed during the last three years.

**Comment by akerouanton** [comment]
This issue went stale, so let me close it.
