### ISSUE TITLE
Docker uses invalid JSON format in some API functions

### ISSUE THREAD

**Issue by linquize** [moby/moby#16925]
As of docker 1.8,
Docker uses invalid JSON format in some API functions, as they reply with header `Content-Type: application/json`. So I expect they reply valid JSON.
- /build
- /images/create
- /images/(name)/push
- /events

This make parsing the output of these functions troublesome.

**Comment by linquize** [comment]
```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 2
Images: 12
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 3
Total Memory: 2.939 GiB
ID: CSW2:43XR:RLYS:M257:ZMCO:VYSA:5GZM:WKOT:LHBY:EOVG:HCNZ:O3G2
WARNING: No swap limit support

$ uname -a
Linux ub144-1 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

1. Call these API via HTTP
-    /build
-    /images/create
-    /images/(name)/push
-    /events

Received: Data in invalid JSON format (missing array at root level, missing comma between each element)
Expected: Data in valid JSON format

**Comment by runcom** [comment]
IIRC these routes are actually *streaming* new line delimited json. The only thing I can come up with is using `application/json; boundary=NL` instead of just plain `applicatoin/json`. Does this sound good?

**Comment by poliveira89** [comment]
@linquize @runcom using `boundary=NL` on the `Content-Type` worked for you?

Because I tried with the following URL `/images/create?fromImage=nginx&tag=latest` and did not see any change :/

**Comment by LK4D4** [comment]
@thaJeztah @runcom @vdemeester Do you think we can close this?
