### ISSUE TITLE
Triggering bad file descriptors and consuming CPU.

### ISSUE THREAD

**Issue by hekaldama** [moby/moby#17074]
# Description of problem:

Can trigger `bad file descriptor` and consume > 100% CPU per rsyslogd and docker process when trying to kill a container running `yes`. Stumbled upon this while trying to make synthetic load docker containers to consume hosts. Not sure if this exposes a bigger problem with the current json-file based logging system. If I run it with `--log-driver=none` I _cannot_ reproduce.

```
Client:                                                                                                                 
 Version:      1.8.3                                                                                                    
 API version:  1.20                                                                          
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64


Containers: 9
Images: 1182
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1200
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 11.43 GiB


Linux 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
## Environment details (AWS, VirtualBox, physical, etc.):

Physical.
## How reproducible:

Everytime.
## Steps to Reproduce:

First start session tailing syslog on your system. Then run any of the following:

`docker stop $(docker run -d alpine yes)`
`docker stop $(docker run -d ubuntu yes)`
`docker stop $(docker run -d centos yes)`

On my Ubuntu host I ran `sudo systemctl restart {docker,syslog}` to recover.
## Actual Results:

docker and rsyslogd consume > 100% CPU.
## Expected Results:

It would just stop the container.

**Comment by hekaldama** [comment]
@GordonTheTurtle not sure how your parser works, but I thought I did what you wanted based off of https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-other-issues. Someone let me know if @GordonTheTurtle actually needs more info or is just naive.

Thanks!

**Comment by thaJeztah** [comment]
The "default" (JSON) logger is not really suitable for production use and use for high-volume logging, and `log-driver=none` can be suitable for that.

Are you running into this when using the default (JSON) driver, or the syslog driver? There are still some issues with the syslog driver, in situations where syslog is not fast enough to handle the amount of logging, see https://github.com/docker/docker/issues/13552#issuecomment-122513354

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
