### ISSUE TITLE
Getting unicode with string when doing an inspect on a container that uses --net host.

### ISSUE THREAD

**Issue by hekaldama** [moby/moby#17070]
# Description of problem:

Getting unicode with string when doing an inspect on a container that uses `--net host`. 

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64


Containers: 8
Images: 1182
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1198
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 11.43 GiB


Linux 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux 
```
## Environment details (AWS, VirtualBox, physical, etc.):

Physical. 
## How reproducible:

Always.
## Steps to Reproduce:

``` bash
docker inspect $(docker run -d --net host alpine sh) | grep \"Gateway
```

or

``` bash
docker inspect --format={{.NetworkSettings.Gateway}} $(docker run -d --net host alpine sh) 
```
## Actual Results:

See above steps to reproduce commands.
## Expected Results:

Would get the docker host's IP address.

**Comment by hekaldama** [comment]
@GordonTheTurtle not sure how your parser works, but I thought I did what you wanted based off of https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-other-issues. Someone let me know if @GordonTheTurtle actually needs more info or is just naive.

Thanks!

**Comment by cpuguy83** [comment]
I'm not sure why docker would provide this info with `--net=host` since docker did not create or manage it.
Also the gateway would be the host's gateway, not the host's IP address.
