### ISSUE TITLE
start integration-cli daemon in go rather than bash

### ISSUE THREAD

**Issue by jessfraz** [moby/moby#17129]
Currently we start the inegration cli daemon via https://github.com/docker/docker/blob/master/hack/make/.integration-daemon-start but instead we should use the daemon start utils in the integration cli suite. that way it is consistent

**Comment by icecrime** [comment]
+1! One thing I would add is that all test utility functions (such as `dockerCmd`) should  operate on a particular `Daemon` instance. Right now, it's too easy to misuse `dockerCmd` versus `Docker.Cmd` and hit the "wrong" daemon instance.

**Comment by icecrime** [comment]
Ping @vdemeester :innocent: :snowman:

**Comment by vdemeester** [comment]
@icecrime yay, on it :sweat_smile: :angel: :santa:

**Comment by alexellis** [comment]
@thaJeztah I guess the actual change for this is probably exp/beginner but you'd need quite a decent amount of knowledge about the types of tests and shell scripts to be able to do this change.

@vdemeester was this actually fixed already through the referenced issues/PRs?

**Comment by vdemeester** [comment]
Nop, it's a little big more complicated than it sounds, and I got carried away on othef thingies. I think exp/beginner is not that appropriate...

**Comment by AkihiroSuda** [comment]
We have pure-go `integration` now and freezed `integration-cli` code base. Closing.
