### ISSUE TITLE
api.go doesn't respect nsswitch.conf

### ISSUE THREAD

**Issue by eliasp** [moby/moby#1715]
Due to the implementation of api.go [which reads only](https://github.com/dotcloud/docker/blob/master/api.go#L1106-L1120) `/etc/group`, it is impossible to rely on other auth mechanisms (e.g. LDAP, NIS).

``` go
groups, err := ioutil.ReadFile("/etc/group")
if err != nil {
        return err
}
re := regexp.MustCompile("(^|\n)docker:.*?:([0-9]+)")
if gidMatch := re.FindStringSubmatch(string(groups)); gidMatch != nil {
        gid, err := strconv.Atoi(gidMatch[2])
        if err != nil {
                return err
        }
        utils.Debugf("docker group found. gid: %d", gid)
        if err := os.Chown(addr, 0, gid); err != nil {
                return err
        }
}
```

Instead, the [`getgrnam`](http://man7.org/linux/man-pages/man3/getgrnam.3.html) syscall should be used to determine, whether a `docker` group exists or not.

The implemenation of [`lookup_unix.go`](http://golang.org/src/pkg/os/user/lookup_unix.go) in the [`user`](http://golang.org/pkg/os/user/) Go package might serve as inspiration on how to do this.

**Comment by runcom** [comment]
seems like there's a new patch but still in review since ~6 months https://codereview.appspot.com/101310044

**Comment by prune998** [comment]
Any news on this ? 
Group lookup is still done in the staticaly defined /etc/group file without any support to NSS lookups.
Any chance to have Docker support basic Linux features ? 

Thanks.

**Comment by rmrf** [comment]
+1

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Comment by nicoulaj** [comment]
Not sure why this would be closed, this bug is still there. See docker/for-linux#186 and analysis by @mjameswh.

**Comment by prune998** [comment]
Please fix before closing !

**Comment by mjameswh** [comment]
@vdemeester Could you please consider reopening this issue?

I think the PR I submitted yesterday should fix it, but I'm afraid that at present, it won't get any attention because it has been closed a long time ago...
