### ISSUE TITLE
syncfs instead of sync in devmapper discard

### ISSUE THREAD

**Issue by mighq** [moby/moby#17233]
When discarding devmapper block device, do sync just on related device,
not on all devices. It could save some time on i/o busy hosts.

I ran into this issue, when running docker on host with multiple disks. Other disks were i/o busy, but docker disk was idle. I still had to wait until kernel commited buffers of all devices.

**Comment by LK4D4** [comment]
there is #17234
Not sure if we'll proceed, but issue looks like worth research.

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637
