### ISSUE TITLE
Be more specific what we consider "notable" in names-generator

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#17249]
The [names-generator states](https://github.com/docker/docker/blob/ab31d9500ebe0c3bf039321bb8c83c7b01c21e4e/pkg/namesgenerator/names-generator.go#L76-L77);

```
// Docker, starting from 0.7.x, generates names from notable scientists and hackers.
// Please, for any amazing man that you add to the list, consider adding an equally amazing woman to it, and vice versa.
```

We may want to be more specific about what we consider "notable", and what "rules" we use when adding people to this list. This came up a few times in the past, i.e. "being a CEO or founder of a company" does not per-definition make a person "notable".

For reference, see the discussion in https://github.com/docker/docker/pull/17156 and https://github.com/docker/docker/pull/15218#discussion_r36033279

**Comment by phemmer** [comment]
What about: Has a wikipedia page which is not classified as a stub?

**Comment by thaJeztah** [comment]
:smile: yup, that's a good first filter.

**Comment by LK4D4** [comment]
@thaJeztah I think it's time!

**Comment by asmaier** [comment]
I propose to put https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss on the list. He seems to be notable: https://en.wikipedia.org/wiki/List_of_things_named_after_Carl_Friedrich_Gauss

**Comment by thaJeztah** [comment]
We froze the names generator (for reasons similar to what this ticket is about);

- https://github.com/moby/moby/pull/43210

closing this one
