### ISSUE TITLE
Expose information about running containers via "AgentX"

### ISSUE THREAD

**Issue by maxmeyer** [moby/moby#17302]
We use SNMP to monitor our infrastructur. Unfortunately there's no easy pluggable solution - at least to my knowlegde - to integrate docker into this.

`AgentX` is a [standard protocol](https://www.ietf.org/rfc/rfc2741.txt) to register a sub-agent with an Master SNMP agent for some particular information - plus some more things. Rather than writing a script which uses some hacks to get information about running containers, `docker daemon` could expose this information via `AgentX` to a SNMP-master daemon running on the same node.

I found this [paper](http://research.arpa2.org/library/nyczak-2015-systemd-snmp-zeroconf.pdf) which describes a solution for systemd. And [here's](http://wiki.libvirt.org/page/Libvirt-snmp) the solution for libvirt.

In general it looks like this:

```
docker <--agentx--> snmpd <--snmp--> monitoring solution
```

Docker would expose information about the service running in it's containers to the snmpd via AgentX-protocol ([RFC](https://www.ietf.org/rfc/rfc2741.txt)).

What do you think? Does this makes sense?

**Comment by LK4D4** [comment]
From my non-DevOps point of view, this seems like overkill.

**Comment by maxmeyer** [comment]
1. But what kind of solution would you propose to integrate into enterprise monitoring systems. To my knowledge most of them are based on SNMP

2. What is you point of view if yours is "non-DevOps"? Dev? Ops? I'm an operator very interested in having a solution which is easy to integrate into an existing RFC-standard-based environment - in regards to used network protocols.

**Comment by cpuguy83** [comment]
@maxmeyer This is already exposed via the HTTP API.
This could easily be a separate service that reaches into docker's API to talk back to the snmpd.
Docker will also expose metrics via a new API endpoint, see #25820

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I don't think there's plans to implement this
