### ISSUE TITLE
644 permissions for config.json and the like security issue

### ISSUE THREAD

**Issue by WolfgangFahl** [moby/moby#17310]
uname-a
Linux capri 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

How reproducible:
always

Steps to Reproduce:
1. create a docker container
ls -l /var/lib/docker/containers/xxx
Actual Results:
644 permissions

Expected Results:
600 or 640 permissions

Additional info:
out of the box state of affairs on Ubuntu 14.04 LTS

**Comment by phemmer** [comment]
If you do `ls -ld /var/lib/docker/containers/xxx`, you'll notice that it's 600. Thus this isn't really an issue.

**Comment by WolfgangFahl** [comment]
The headling should be "security risk issue" and not "security issue" then

**Comment by phemmer** [comment]
> There is now a single point of failure for this security issue

It doesn't work that way. Otherwise you could use that argument for a huge number of files on the system. `/etc/shadow`, `/dev/kmem`, `/dev/sda`, `/etc/ssh/ssh_host_key`, etc.
Additionally, you would still have to get through `/var/lib/docker/containers`, which is also 700.

**Comment by thaJeztah** [comment]
Stumbled upon this old issue; I agree with the above assessment; the `/var/lib/docker/container` directory is already protected (`0700` or `0701` permissions), so this should not be a security concern.

On a current version of docker (19.03.x), permissions on the container directories are now `0700` (which may have changed at some point);

```console
ls -la /var/lib/docker/containers/
total 28
drwx------  7 root root 4096 Oct 29 15:51 .
drwx--x--x 14 root root 4096 Jun 30 11:34 ..
drwx------  4 root root 4096 Jul 29 09:01 05bd752a1f25e29d84096f60a0b1cc59dc467f05d06c66d67f450eba99d5d6de
drwx------  4 root root 4096 Jul 29 08:59 18bacf85eb36da2446686c19fc6d56f33d986d23becc280ee86076fb7763d666
drwx------  4 root root 4096 Jul 29 09:01 3a0c926386772c79960e12a744d5c7ad76c528ce874345926efeaa7562fe64b3
drwx------  5 root root 4096 Aug  4 07:17 c3d6bc49fe5d3941fff2366a0bfea76f7eccd70852bd41d35b15cc9ccfd3e22a
drwx------  4 root root 4096 Jul 29 08:59 d33b5fe840f10e029a20121f25b5d5128421bd8eadbe18d4162f716a79e66974
```

I did notice that https://github.com/moby/moby/pull/34419 updated the permissions of the `config.v2.json` inside those directories to `0600`, so for consistency I opened https://github.com/moby/moby/pull/41620 to update permissions on `hostconfig.json` to match.
