### ISSUE TITLE
Report sha256 digest in `docker inspect`

### ISSUE THREAD

**Issue by michaelbarton** [moby/moby#17670]
Issue #11109 allows images to be pulled by their digest. As far as I can tell the only way to get this digest is using docker pull.

``` bash
docker pull bioboxes/velvet | grep sha256: | cut -f 3 -d :
```

This requires parsing an unstructured string and connecting to dockerhub. I suggest that this data is available in the `docker inspect` metadata so that instead the command could be:

``` bash
docker inspect --format='{{.SHA256}}' bioboxes/velvet
```

Thank you.

**Comment by michaelbarton** [comment]
This is a feature request so I'm not sure if the information requested above is applicable. However:

docker version:

	Client:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:10:10 UTC 2015
	 OS/Arch:      darwin/amd64

	Server:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:10:10 UTC 2015
	 OS/Arch:      linux/amd64

docker info:

	Containers: 383
	Images: 339
	Storage Driver: aufs
	 Root Dir: /mnt/sda1/var/lib/docker/aufs
	  Backing Filesystem: extfs
	   Dirs: 1105
	    Dirperm1 Supported: true
	    Execution Driver: native-0.2
	    Logging Driver: json-file
	    Kernel Version: 4.0.9-boot2docker
	    Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
	    CPUs: 1
	    Total Memory: 1.956 GiB
	    Name: default
	    ID: KJOP:HDKR:646Q:F6BB:ZHOH:V5KU:CWBA:3FMP:5HTH:7HAU:BFL5:3X7D
	    Debug mode (server): true
	    File Descriptors: 21
	    Goroutines: 34
	    System Time: 2015-11-04T01:01:21.962508588Z
	    EventsListeners: 0
	    Init SHA1:
	    Init Path: /usr/local/bin/docker
	    Docker Root Dir: /mnt/sda1/var/lib/docker
	    Labels:
	     provider=virtualbox

uname -a

	Darwin mbarton-lm.XXXXX 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin


**Describe the results you received:**

The docker image sha256 digest can only be retrieve by grepping the output of `docker pull`

**Describe the results you expected:**

Ability to retrieve sha256 digest of image from `docker inspect` metadata.

**Comment by thaJeztah** [comment]
Docker 1.9 now includes a `RepoDigests` field containing the digest (but possibly only if the original image was pulled by digest); https://github.com/docker/docker/pull/13185 and https://github.com/docker/docker/pull/17275

**Comment by michaelbarton** [comment]
Ah, thank you. I think it would certainly be useful to also get the digest if you've not pulled it by the digest.

**Comment by thaJeztah** [comment]
@tonistiigi any thoughts on that? I just pulled an image by name and that doesn't propagate the digest, only if I took the digest, and pulled, the digest shows up in docker inspect

**Comment by tonistiigi** [comment]
@thaJeztah Yes, that make sense. I think its currently held back from the UI side as every digest makes a new row for `docker images`. See comment in https://github.com/docker/docker/blob/c9208953fac6174bb205bd1b3705f81a602869c2/graph/pull_v2.go#L422

**Comment by amouat** [comment]
I'd really like this feature. Currently the digests are borderline unusable. I had to advise a client to do the following when pushing.

imagehash=$(docker push repo/image:tag | grep sha | cut -d '  ' -f 3)

Which is clearly hacky and fragile, but there is no other solution I can see (apart from a beter regexp). I can only assume that nearly no-one uses digests due to this, which is a huge shame given they offer big advantages for security and provenance.

**Comment by amouat** [comment]
Another option would be to create a `docker digest` command that calculates the digest for a given image so that the above hackery isn't necessary. Adding the info to `docker inspect` is still my preferred solution, but `docker digest` would work and may have other uses.

If I can find the time and figure out the code, I'll have a look at creating a stand-alone docker-digest tool.

**Comment by TomasTomecek** [comment]
@shaded-enmity had a go on a similar topic but the PR was closed: https://github.com/docker/docker/pull/17402 would be awesome if someone could resurrect it

**Comment by michaelbarton** [comment]
I use Docker in scientific research and the use case for me would be using the digest to get the exact image version that was used by someone else and reproduce their results.

As the comments above suggest this data is accessible similarly to other image metadata using `docker inspect`. The problem/issue seems to be that the '{{.RepoDigests}}'` field is only available is the image was pulled by its digest, and therefore cannot be retrieved otherwise.

**Comment by runcom** [comment]
I wrote a [tool](https://github.com/projectatomic/skopeo) which can do this (and other):

- Get an image's digest (unverified):
```
$ skopeo inspect docker://docker.io/busybox | jq '.Digest'
"sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92"
```
- Get the whole manifest (_template'd_, to be later parsed by tools like `jq` or by other programs i.e. `atomic`):
```
$ ./skopeo inspect docker://docker.io/busybox               
{
    "Name": "docker.io/library/busybox",
    "Tag": "latest",
    "Digest": "sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92",
    "RepoTags": [
        "1-glibc",
        "1-musl",
        "1-ubuntu",
        "1-uclibc",
        "1.21-ubuntu",
        "1.21.0-ubuntu",
        "1.23.2",
        "1.23",
        "1.24-glibc",
        "1.24-musl",
        "1.24-uclibc",
        "1.24.0",
        "1.24.1-glibc",
        "1.24.1-musl",
        "1.24.1-uclibc",
        "1.24.1",
        "1.24.2-glibc",
        "1.24.2-musl",
        "1.24.2-uclibc",
        "1.24.2",
        "1.24",
        "1",
        "buildroot-2013.08.1",
        "buildroot-2014.02",
        "glibc",
        "latest",
        "musl",
        "ubuntu-12.04",
        "ubuntu-14.04",
        "ubuntu",
        "uclibc"
    ],
    "Created": "2016-03-18T18:22:48.810791943Z",
    "DockerVersion": "1.9.1",
    "Labels": {},
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:385e281300cc6d88bdd155e0931fbdfbb1801c2b0265340a40481ee2b733ae66"
    ]
}
```
- Get a raw manifest:
```
$ ./skopeo inspect --raw docker://docker.io/busybox
{
   "schemaVersion": 1,
   "name": "library/busybox",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:385e281300cc6d88bdd155e0931fbdfbb1801c2b0265340a40481ee2b733ae66"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"156e10b83429\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"sh\"],\"Image\":\"56ed16bd6310cca65920c653a9bb22de6b235990dcaa1742ff839867aed730e5\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"container\":\"5f8098ec29947b5bea80483cd3275008911ce87438fed628e34ec0c522665510\",\"container_config\":{\"Hostname\":\"156e10b83429\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [\\\"sh\\\"]\"],\"Image\":\"56ed16bd6310cca65920c653a9bb22de6b235990dcaa1742ff839867aed730e5\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2016-03-18T18:22:48.810791943Z\",\"docker_version\":\"1.9.1\",\"id\":\"437595becdebaaaf3a4fc3db02c59a980f955dee825c153308c670610bb694e1\",\"os\":\"linux\",\"parent\":\"920777304d1d5e337bc59877253e946f224df5aae64c72538672eb74637b3c9e\"}"
      },
      {
         "v1Compatibility": "{\"id\":\"920777304d1d5e337bc59877253e946f224df5aae64c72538672eb74637b3c9e\",\"created\":\"2016-03-18T18:22:48.262403239Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:47ca6e777c36a4cfffe3f918b64a445c8f32300deeb9dfa5cc47261bd7b75d21 in /\"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "YWT2:DY2S:XWKO:LT3K:HG47:OP7F:2B5B:JQFT:YGBD:YU37:TM72:C3GI",
               "kty": "EC",
               "x": "0LITllC5k8mFtLLK81KtHT3K_u1jsROIXUMlM0a0IV4",
               "y": "YZBBmiv6CIpoJHvjtHVzw_V-snrEpP0Og5TILhHsVR8"
            },
            "alg": "ES256"
         },
         "signature": "WsSDRVEFj_exB8XODtAG0NzhzcI6UWZ22ezjj-ACGeLdT8_XS2Xans3GjS5nvAexjtLroP3f-VerrVZ7z-4M1w",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjE5MjIsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wNi0wM1QwOTozOTo1MloifQ"
      }
   ]
}
```

**Comment by mschwager** [comment]
Is there a simple way to just calculate the `RepoDigests` value from existing information? If I, for example, wanted to calculate said information before pushing to a remote source.

@runcom I looked into your tool a bit, but it's not immediately obvious how the `Digest` value is calculated.

Something like `sha256(this_data + that_data)` would be great!

**Comment by carlossg** [comment]
you can do this in docker 1.13+ IIRC

    docker image inspect busybox --format '{{.ID}}'
    sha256:c75bebcdd211f41b3a460c7bf82970ed6c75acaab9cd4c9a4e125b03ca113798

**Comment by powerman** [comment]
@carlossg Actually your answer is wrong, value of `{{.ID}}` differs from real digest and can't be used:
```
$ docker image ls --digests circleci/picard
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
circleci/picard     latest              sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213   932926da21bf        10 hours ago        83.9 MB

$ docker image inspect --format='{{.ID}}' circleci/picard
sha256:932926da21bff1c81d80563ecdecb37363efa19862af61e4a523098ad5e4b419
$ docker image inspect --format='{{.RepoDigests}}' circleci/picard
[circleci/picard@sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213]

$ docker pull circleci/picard@sha256:932926da21bff1c81d80563ecdecb37363efa19862af61e4a523098ad5e4b419
Error response from daemon: manifest for circleci/picard@sha256:932926da21bff1c81d80563ecdecb37363efa19862af61e4a523098ad5e4b419 not found
$ docker pull circleci/picard@sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213
sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213: Pulling from circleci/picard
Digest: sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213
Status: Image is up to date for circleci/picard@sha256:af8d416a5fbec4ce1766c0b9e945f0a93be79bed8b2713209d4bb8a6af5ec213
```

BTW, why RepoDigests is a slice? Is it may contain more than one element? And which element will be useful for `docker pull` then?

**Comment by tonistiigi** [comment]
> Ah, thank you. I think it would certainly be useful to also get the digest if you've not pulled it by the digest.

This was added a while back so this issue can be closed now.

> why RepoDigests is a slice?  Is it may contain more than one element?

Yes

> And which element will be useful for docker pull then?

`RepoDigest` stores a reference(or reference+digest) that was used when an image was pulled. Two pulls from different references may pull the same image.

**Comment by ringerc** [comment]
For other readers, note that `RepoDigest` is not computed for locally built images.

If you are looking for the sha256 sum of the `application/vnd.docker.distribution.manifest.v2+json` manifest, it looks like dockerd knows nothing about it, and you have to compute it, e.g. using `skopeo inspect`. `docker push` may change it, but `skopeo copy --preserve-digests` will not.
