### ISSUE TITLE
Ubuntu 14.04, docker 1.9.0 + dnsmasq result in hostname lookup failure in containers

### ISSUE THREAD

**Issue by UndeadBaneGitHub** [moby/moby#17689]
Formal info:

`docker version`:

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info` (however, the bug was initially reproduced on a much larger AWS `m4.2xlarge` instance, this `t2.micro` was used later for isolating the bug):

```
Containers: 0
Images: 0
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-398179-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.81 GB
 Metadata Space Used: 1.479 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
```

`uname -a`:

```
Linux ip-172-31-32-210 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

---

Tested on Amazon instances (`t2.micro` with `Ubuntu 14.04` free instance is enough), shell script for reproducing the bug is attached. The bug is always there, shows up in 100% of cases.

The test script is written so that it can be ran on a fresh AWS instance and give the result (the crash), no additional preparation is required - just create a shell file with this script and run it.

The bug was caught on mesosphere docker images, so they are referenced in the script, but I suppose, something more lightweight, that also uses hostname lookup (like `php`) can be used.

Nothing like this happened on docker `1.8.3` - the images are started and run without any issues, `dnsmasq` or not.

The script can be easily edited to install `1.8.3` docker or not install `dnsmasq` - then the bug goes away. But with `dnsmasq` and the latest version stuff just does not work.

The script:

```
#!/bin/bash
HOST_IP=$(hostname --ip-address)
DOCKER_OPTS='DOCKER_OPTS="--log-driver=json-file --log-opt max-size=20m --log-opt max-file=5"'

apt-get update && apt-get install -y libdevmapper-dev libpthread-stubs0-dev libsqlite3-dev libudev-dev

# Without DNSMASQ everything seems to work
apt-get install -y dnsmasq
# Sleep is required to let dnsmasq start properly
sleep 1m

apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

rm -f /etc/apt/sources.list.d/docker.list

echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list

apt-get update && apt-get purge -y lxc-docker*

# Everything works fine with docker 1.8.3
# apt-get install -y docker-engine=1.8.3-0~trusty
# ...but fails with 1.9.0
apt-get install -y docker-engine=1.9.0-0~trusty

GREPPED_DOCKER_OPTS=$(grep "$DOCKER_OPTS" /etc/default/docker)
if [[ $? -eq 1 ]]
then
    sed -e "\$a$DOCKER_OPTS" /etc/default/docker
    service docker restart
fi

# Start Zookeeper
docker run -d \
    --name=zookeeper \
    --net=host \
    --name=zookeeper \
    jplock/zookeeper

# Start mesos master
docker run -d \
    --name=mesos_master \
    --net=host \
    mesosphere/mesos-master:0.25.0-0.2.70.ubuntu1404 \
        --ip=$HOST_IP \
        --zk=zk://$HOST_IP:2181/mesos \
        --work_dir=/var/lib/mesos/master \
        --quorum=1

# Start mesos slave
docker run -d \
    --name=mesos_slave \
    --privileged \
    --net=host \
    -v /sys:/sys \
    -v /usr/bin/docker:/usr/bin/docker:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02:ro \
    -v /lib64/libpthread.so.0:/lib/libpthread.so.0:ro \
    -v /lib64/libsqlite3.so.0:/lib/libsqlite3.so.0:ro \
    -v /lib64/libudev.so.1:/lib/libudev.so.1:ro \
    -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro \
    -v /opt/intempt/docker/docker_cfg.tar.gz:/etc/docker_cfg.tar.gz:ro \
    mesosphere/mesos-slave:0.25.0-0.2.70.ubuntu1404 \
        --ip=$HOST_IP \
        --containerizers=docker \
        --master=zk://$HOST_IP:2181/mesos \
        --work_dir=/var/lib/mesos/slave \
        --log_dir=/var/log/mesos/slave \
        --resources='mem:1024;cpus:1;ports:[2000-40000]'


# Watch the slave crash within 30s or so with the following error:

# F1104 14:53:12.548439     1 slave.cpp:369] Failed to get hostname: Temporary failure in name resolution
# *** Check failure stack trace: ***
#     @     0x7f6b5eaad64d  google::LogMessage::Fail()
#     @     0x7f6b5eaaf48d  google::LogMessage::SendToLog()
#     @     0x7f6b5eaad23c  google::LogMessage::Flush()
#     @     0x7f6b5eaafd89  google::LogMessageFatal::~LogMessageFatal()
#     @     0x7f6b5e52cdc9  mesos::internal::slave::Slave::initialize()
#     @     0x7f6b5ea5ebb1  process::ProcessManager::resume()
#     @     0x7f6b5ea5f29a  process::ProcessManager::wait()
#     @     0x7f6b5ea5fa17  process::wait()
#     @           0x409ab4  main
#     @     0x7f6b5cf61ec5  (unknown)
#     @           0x40a1f8  (unknown)
# *** Aborted at 1446648792 (unix time) try "date -d @1446648792" if you are using GNU date ***
# PC: @     0x7f6b5cf7a227 (unknown)
# *** SIGSEGV (@0x0) received by PID 1 (TID 0x7f6b5f47e800) from PID 0; stack trace: ***
#     @     0x7f6b5d315340 (unknown)
#     @     0x7f6b5cf7a227 (unknown)
#     @     0x7f6b5eab5909 google::DumpStackTraceAndExit()
#     @     0x7f6b5eaad64d google::LogMessage::Fail()
#     @     0x7f6b5eaaf48d google::LogMessage::SendToLog()
#     @     0x7f6b5eaad23c google::LogMessage::Flush()
#     @     0x7f6b5eaafd89 google::LogMessageFatal::~LogMessageFatal()
#     @     0x7f6b5e52cdc9 mesos::internal::slave::Slave::initialize()
#     @     0x7f6b5ea5ebb1 process::ProcessManager::resume()
#     @     0x7f6b5ea5f29a process::ProcessManager::wait()
#     @     0x7f6b5ea5fa17 process::wait()
#     @           0x409ab4 main
#     @     0x7f6b5cf61ec5 (unknown)
#     @           0x40a1f8 (unknown)

# The master crashes too - zookeeper refuses connections, I suppose, because of the same bug. No crashes happen, if 1.8.3 docker is installed, or there is no dnsmasq
```

**Comment by bpradipt** [comment]
I ran your test script on my AWS instance (t2.micro + Ubuntu 14.04) but couldn't recreate the issue. 
# docker ps --format "{{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}"
f724bd395a32    31 minutes      Up 31 minutes   mesos_slave
85d00c463171    31 minutes      Up 31 minutes   mesos_master
d573c17aa9a2    31 minutes      Up 31 minutes   zookeeper

Checked docker logs o/p as well and containers are running fine. 
I just created an AWS instance and ran your script. Absolutely no changes done..

**Comment by UndeadBaneGitHub** [comment]
@bpradipt This is really weird, as I've just now created a new t2.micro + Ubuntu 14.04 instance (`Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-5189a661`), copy-pasted the script into `/tmp/test.sh`, chmoded it, ran it - and now I get the same error exactly: both master and slave have crashed with errors, leaving only zookeeper running:
    
    docker ps --format "{{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}"
    662ad270a2bf	3 minutes	Up 3 minutes	zookeeper

I wonder, what can be different. Are you sure, that you have not apply any changes to the script?

I will also try to create AWS instance under a different account and test it there as well.

**Comment by bpradipt** [comment]
@UndeadBaneGitHub, I redid the test on a new 14.04 instance and no luck ..
The only difference is the AMI used. In my case it is ami-d05e75b8. 
<pre>
docker ps --format "{{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}"
1cd7d1144c09	44 minutes	Up 44 minutes	mesos_slave
afde80476261	44 minutes	Up 44 minutes	mesos_master
4598ecb457f4	44 minutes	Up 44 minutes	zookeeper
</pre>

**Comment by thaJeztah** [comment]
@UndeadBaneGitHub @bpradipt is this still an issue?

**Comment by UndeadBaneGitHub** [comment]
@thaJeztah Yep, still an issue - although, I suspect, might be instance-type dependent.
Got it reproduced under a different Amazon account, but with the same instance type (`ami-5189a661`). Maybe, some combination of Amazon settings for this kind of instances + dnsmasq cause the thing...

**Comment by thaJeztah** [comment]
Thanks @UndeadBaneGitHub, I'm not very fluent in AWS, but perhaps another maintainer or contributor has some thoughts.

**Comment by AkihiroSuda** [comment]
Ubuntu 14.04 and Docker 1.9 are no longer supported.
Feel free to open a new issue if somebody hitting same issue with the supported versions.
