### ISSUE TITLE
Config options for multiple user-defined network bridges in '/etc/default/docker'?

### ISSUE THREAD

**Issue by DKBgit** [moby/moby#17748]
docker version:

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

Hello,

What the format of the **'/etc/default/docker'** config file if the user wants to implement multiple user-defined network bridges?

I would like to create a new user-defined network linked to different bridge(network interface) than the default 'bridge' network.
I can do this using the 'docker network create ...' command 
eg.  `docker network create -o com.docker.network.bridge.name=docker1 test`
(Note: the bridge _'test'_ is using the _'docker1'_ interface while the _'default'_ bridge is set to use the _'docker0'_ interface.)

How can I implement this in the **'etc/default/docker'** options file?
eg. of current options file

```
BRIDGE=docker0
CIDR= ...
DNS= ...

wait_ip() {
  address=$(ip add show $BRIDGE | grep 'inet ' | awk '{print $2}')
  [ -z "$address" ] && sleep $1 || :
}

wait_ip 5
wait_ip 15

DOCKER_OPTS="
    -H unix:///var/run/docker.sock
    -H tcp://0.0.0.0:2375
    --fixed-cidr=$CIDR
    --bridge $BRIDGE
    --iptables=false
    --dns $DNS
    --mtu=1426
"
```

There is currently no documentation to aid a user in doing this.

**Comment by thaJeztah** [comment]
These options are only for the default bridge network, but not for configuring custom networks. Not sure if that is something that's planned

/cc @mavenugo

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
