### ISSUE TITLE
Specify hostname on docker network connect 

### ISSUE THREAD

**Issue by ael-g** [moby/moby#17805]
Hi all !

The new `docker network connect` command is great, would it be possible to pass a hostname alias to this command to set specific hostnames for each interface added to the container ?
For instance :
`docker network connect br1:Alan1 container_A`
`docker network connect br2:Alan2 container_A`

which would add two entries to `container_A`'s `/etc/hosts` with specified hostname and IP ?

I see there are some open issues for supporting multiple `--net` flag on container `run`, it would be nice to have the same syntax on this flags too I think, like :
`docker run --net br1:Alan1 --net br2:Alan2 ...`

What I'd like to achieve eventually is to declare several containers in a docker-compose yml, each container may be connected to several networks and has one hostname per network.
Then, I'd like to be able to issue `docker-compose up` which would fill every `/etc/hosts` on every containers with hostname of containers connected to the same networks.
But maybe this part is more related to `docker-compose`.

Thanks a lot for your help !

**Comment by cpuguy83** [comment]
see docker/libnetwork#737

**Comment by ael-g** [comment]
Ok !
I'd be happy to contribute but I'm a bit new to contributing to big github projects.
How to know someone from the official docker team, or someone else, is not already working on it ?
Are we supposed to speak about this functionality only on docker/libnetwork#737 from now ?
Can I just (try to) develop the functionality and issue a PR ?

Also it seems that `--mac-address` on the `docker run` command would be more suited inside the `docker network` subsystem don't you think ?

**Comment by cpuguy83** [comment]
Definitely I'd discuss with the maintainers from libnetwork.
Also there is IRC, #docker-network on freenode.

`--mac-address` could be interesting on `docker network connect`.

**Comment by LK4D4** [comment]
@cpuguy83 Do you know if this was addressed?

**Comment by cpuguy83** [comment]
Not addressed.

**Comment by LK4D4** [comment]
ping @mrjana @mavenugo @sanimej @aboch

**Comment by thaJeztah** [comment]
- I think mac-address will be handled by https://github.com/moby/moby/pull/45905

Not 100% sure if that covers "network connect" as well

/cc @akerouanton

**Comment by akerouanton** [comment]
> which would add two entries to container_A's /etc/hosts with specified hostname and IP ?

* The tracking issue on libnetwork side was https://github.com/moby/libnetwork/issues/737 ;
* The discussion then moved to https://github.com/moby/moby/issues/18699 ;
* https://github.com/docker/engine-api/commit/c6a57eeb9407710fc97cf56eeaf73bde321521dc added the `Aliases` field to `EndpointSettings` ;
* https://github.com/moby/libnetwork/pull/859/commits/3163129297330ed268d8f6d0b92e83da6e3c6fe2 added support for network-scoped aliases ;
* This PR added the required plumbing to libnetwork integration into the daemon https://github.com/moby/moby/pull/19242 ;

So it should be safe to close this issue as completed.
