### ISSUE TITLE
UDP broadcast not working with multi-host networking

### ISSUE THREAD

**Issue by AxelVoitier** [moby/moby#17814]
Hello,

It seems UDP broadcast does not work when using multi-host networking.
I am trying to use https://github.com/zeromq/pyre for cross-application discovery and communication. It uses UDP broadcast ("zbeacons") to discover other nodes on the network.

Here is how to reproduce it (assuming you have at least two different physical hosts and docker multi-host networking setup with the overlay network named my_net).

```
- docker pull python:2
- docker run -it --rm --net=my_net python:2 bash
> pip install pyzmq
> pip install https://github.com/zeromq/pyre/archive/master.zip
> python
>>> import pyre
>>> node = pyre.Pyre()
>>> node.start()
>>> node.peers()
```

Do this twice. If the two containers are on the same host, the UDP broadcast will work and the two Pyre nodes will discover each other: "node.peers()" will list one UUID.
But if the two containers are on different hosts they won't discover each other and the list of peers UUID will be empty.

Versions:

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 6
Images: 234
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 246
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 19.6 GiB
Name: dekarion
ID: TJ77:LNBM:QAAE:5JBU:UCVM:ZE5G:CQI6:7OUX:7CQP:QFXC:34WN:7BI4
WARNING: No swap limit support
Cluster store: consul://192.168.1.5:8500
Cluster advertise: 192.168.1.70:2376
```

**Comment by AxelVoitier** [comment]
I tried between two hosts in 4.1.8 and I still got the same results. Here is their config:
```
$ docker info
Containers: 1
Images: 28
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.8-hypriotos+
Operating System: Raspbian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 434.4 MiB
Name: agrippa
ID: NO5X:BES2:N2VX:H3CG:VDJA:EIMQ:OWH3:SESS:OL2F:VNKS:BINX:GT5I
Debug mode (server): true
 File Descriptors: 27
 Goroutines: 75
 System Time: 2015-11-10T00:19:00.673262101+01:00
 EventsListeners: 0
 Init SHA1: 5246a6ddd203054e34d43c740f96958125d00994
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Cluster store: consul://neuron.local:8500
Cluster advertise: 192.168.1.51:2376

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Sun Nov  8 20:32:37 UTC 2015
 OS/Arch:      linux/arm

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Sun Nov  8 20:32:37 UTC 2015
 OS/Arch:      linux/arm
```

I also inspected the network config from within a container. The broadcast address on the shared network is actually not set (0.0.0.0).
By pinging on 255.255.255.255 I receive replies only from the local host:
```
# ping -b 255.255.255.255
WARNING: pinging broadcast address
PING 255.255.255.255 (255.255.255.255) 56(84) bytes of data.
64 bytes from 172.18.0.1: icmp_req=1 ttl=64 time=0.601 ms
64 bytes from 172.18.0.1: icmp_req=2 ttl=64 time=0.424 ms
64 bytes from 172.18.0.1: icmp_req=3 ttl=64 time=0.420 ms
64 bytes from 172.18.0.1: icmp_req=4 ttl=64 time=0.427 ms
```
(I made sure /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts is set to 0 on both hosts.)

It also seems impossible to set a broadcast address on the interface connected to the shared network:
```
# ifconfig eth0 broadcast 10.0.0.255
SIOCSIFBRDADDR: Operation not permitted
SIOCSIFFLAGS: Operation not permitted
```


Is that a limitation in the network plugin, or in the kernel support?

**Comment by AxelVoitier** [comment]
That's odd:
On the host /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts is set to 0.
But within containers it is set to 1... and cannot be changed as it is in read-only.

**Comment by morxa** [comment]
I have this problem too.
Description of problem:
UDP broadcasts don't work in multi-host network between hosts. UDP broadcasts only work if both containers run on the same host.


`docker version`:
````
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
````

`docker info`:
````
Containers: 12
Images: 158
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 11.68 GiB
Name: ubuntu-desktop
ID: YZLT:IPVE:XB4L:E6LT:EQNA:AFE6:ZCFY:7WA2:ZC44:5YMV:FDP2:UPSR
Http Proxy: http://127.0.0.1:3128
Https Proxy: http://localhost:3128
WARNING: No swap limit support
````

`docker -H 127.0.0.1:2376 info`:
````
Containers: 21
Images: 10
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 ubuntu01: 192.168.137.160:2375
  └ Containers: 12
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-32-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
 ubuntu02: 192.168.137.159:2375
  └ Containers: 9
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.044 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-32-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
CPUs: 4
Total Memory: 4.087 GiB
Name: 8609a7d85a3a
````

`uname -a`:
````
Linux ubuntu01 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Linux ubuntu02 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Linux ubuntu-desktop 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

Environment details (AWS, VirtualBox, physical, etc.):
Two VMWare Workstation machines with Ubuntu Server 14.04.3 configured as swarm agents, swarm master running on an addtional Ubuntu Desktop 14.04.3.
Swarm configuration with `etcd`.


How reproducible:
always

Steps to Reproduce:

1. Set up a swarm with two agents
1. Create an overlay network: 

        % docker network create broadcast_test
3. Start two containers on the first node and a third container on the second node, e.g.:
    
        % docker run -ti --net=broadcast_test -e constraint:node==ubuntu01 --name=sender ubuntu:14.04 bash
        % docker run -ti --net=broadcast_test -e constraint:node==ubuntu01 --name=rec1 ubuntu:14.04 bash
        % docker run -ti --net=broadcast_test -e constraint:node==ubuntu02 --name=rec2 ubuntu:14.04 bash
3. Install `socat` on `sender`
4. Run on `rec1` and `rec2`:

        % nc -luv 5555
5. Run on `sender` (adapt broadcast address accordingly):

        %  echo "HELLO"  | socat - UDP4-DATAGRAM:10.0.1.255:5555,broadcast

Actual Results:
On `ubuntu01` the message is received, on `ubuntu02` no message is received.

Expected Results:
Both containers should receive the message.

**Comment by oobles** [comment]
Also observing this issue while using 1.9.1.  Is this a known limitation or a defect?

**Comment by thaJeztah** [comment]
I think this is currently being discussed in the libnetwork repository; https://github.com/docker/libnetwork/issues/552

/cc @mavenugo @sanimej

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
