### ISSUE TITLE
Dockerfile, Request feature, ADD_AND_RUN

### ISSUE THREAD

**Issue by win-t** [moby/moby#18184]
I often write Dockerfile like this:

``` dockerfile
FROM ubuntu:trusty
MAINTAINER Kurnia D Win <kurnia.d.win@gmail.com>

ADD _build /_build/
RUN /_build/run && rm -rf /_build
```

because sometime 'RUN' is not enough

with this approach, 'ADD' and 'RUN' will create 2 layer, because each statement will commit an image
i think, it will be great if these statement can be combine into something,

like this:

``` dockerfile
FROM ubuntu:trusty
MAINTAINER Kurnia D Win <kurnia.d.win@gmail.com>

ADD_AND_RUN _build /_build/ /_build/run && rm -rf /_build
```

or this:

``` dockerfile
FROM ubuntu:trusty
MAINTAINER Kurnia D Win <kurnia.d.win@gmail.com>

ADD_AND_RUN my_package.tar /target/ /target/setup.sh
ENTRYPOINT ["/target/run.sh"]
```

**Comment by LK4D4** [comment]
Sorry, but Dockerfile syntax is frozen now. Also I think that 2 layers is big problem because of CoW nature. However layers issue will be fixed later when we split builder from daemon.

**Comment by thaJeztah** [comment]
Thanks for suggesting, @win-t as @LK4D4 explained, we currently cannot accept changes to the Dockerfile syntax: for more information, see the roadmap; https://github.com/docker/docker/blob/master/ROADMAP.md#2-frozen-features

**Comment by win-t** [comment]
Sorry i didn't read the roadmap before,
thanks for your response

**Comment by thaJeztah** [comment]
@win-t no problem, I thought I'd add the link to clarify @LK4D4's comment :+1:

**Comment by win-t** [comment]
i think we can reopen this issue, can't we?,
because Dockerfile syntax is not frozen feature anymore, as https://github.com/docker/docker/commit/07250457df03396ea61dbf3782b5f8cf1094e7e0

**Comment by win-t** [comment]
solved by https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypebind-the-default-mount-type
