### ISSUE TITLE
Docker can not start when iptables is disabled.

### ISSUE THREAD

**Issue by higkoo** [moby/moby#18388]
## docker version 

Client:
    Version:      1.9.0
    API version:  1.21
    Go version:   go1.4.2
    Git commit:   76d6bc9
    Built:        Tue Nov  3 17:29:38 UTC 2015
    OS/Arch:      linux/amd64
Server:
    Version:      1.9.0
    API version:  1.21
    Go version:   go1.4.2
    Git commit:   76d6bc9
    Built:        Tue Nov  3 17:29:38 UTC 2015
    OS/Arch:      linux/amd64  
## docker info

Containers: 0  
Images: 0  
Server Version: 1.9.0  
Storage Driver: devicemapper  
    Pool Name: docker-8:1-33748157-pool  
    Pool Blocksize: 65.54 kB  
    Base Device Size: 107.4 GB  
    Backing Filesystem: xfs  
    Data file: /dev/loop0  
    Metadata file: /dev/loop1  
    Data Space Used: 1.821 GB  
    Data Space Total: 107.4 GB  
    Data Space Available: 26.72 GB  
    Metadata Space Used: 1.483 MB  
    Metadata Space Total: 2.147 GB  
    Metadata Space Available: 2.146 GB  
    Udev Sync Supported: true  
    Deferred Removal Enabled: false  
    Deferred Deletion Enabled: false  
    Deferred Deleted Device Count: 0  
    Data loop file: /data/docker/devicemapper/devicemapper/data  
    Metadata loop file: /data/docker/devicemapper/devicemapper/metadata  
    Library Version: 1.02.90 (2014-09-01)  
Execution Driver: native-0.2  
Logging Driver: json-file  
Kernel Version: 3.16.0-4-amd64  
Operating System: Debian GNU/Linux 8 (jessie)  
CPUs: 24  
Total Memory: 31.44 GiB  
Name: higkoo-docker-s1  
ID: WBUY:QT3L:26BW:PTYJ:SSEA:WQO6:JC7Q:3Q2Z:3JDS:GE6N:PCCV:RYU2   
## uname -a

Linux higkoo-docker-s1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux  
## Provide additional environment details
- Dell PowerEdge M620  
- Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz  
- Ethernet controller: Broadcom Corporation NetXtreme II BCM57810 10 Gigabit Ethernet (rev 10)  
## steps to reproduce the issue
1. script for iptables disable  
   https://github.com/higkoo/linux-tunning-config/blob/master/script/iptables-switch.sh  
2. iptables-switch.sh disable  
3. systemctl restart docker  
   [....] Restarting docker (via systemctl): docker.service  
   /sbin/iptables --wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER  
4. docker daemon -s devicemapper --iptables=false --ip-masq=false --debug=true  
5. hang-up at:  
   INFO[0000] Firewalld running: false  
   DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKE]

**Comment by higkoo** [comment]
#### Start docker after iptables started, then iptables disable
1. iptables-switch.sh enable
1. systemctl start docker
1. iptables-switch.sh disable
1. docker info  
	Containers: 0  
	Images: 0  
	Server Version: 1.9.0  
	Storage Driver: devicemapper  
		Pool Name: docker-8:1-33748157-pool  
		Pool Blocksize: 65.54 kB  
		Base Device Size: 107.4 GB  
		Backing Filesystem: xfs  
		Data file: /dev/loop0  
		Metadata file: /dev/loop1  
		Data Space Used: 1.821 GB  
		Data Space Total: 107.4 GB  
		Data Space Available: 26.72 GB  
		Metadata Space Used: 1.483 MB  
		Metadata Space Total: 2.147 GB  
		Metadata Space Available: 2.146 GB  
		Udev Sync Supported: true  
		Deferred Removal Enabled: false  
		Deferred Deletion Enabled: false  
		Deferred Deleted Device Count: 0  
		Data loop file: /data/docker/devicemapper/devicemapper/data  
		Metadata loop file: /data/docker/devicemapper/devicemapper/metadata  
		Library Version: 1.02.90 (2014-09-01)  
	Execution Driver: native-0.2  
	Logging Driver: json-file  
	Kernel Version: 3.16.0-4-amd64  
	Operating System: Debian GNU/Linux 8 (jessie)  
	CPUs: 24  
	Total Memory: 31.44 GiB  
	Name: higkoo-docker-s1  
	ID: WBUY:QT3L:26BW:PTYJ:SSEA:WQO6:JC7Q:3Q2Z:3JDS:GE6N:PCCV:RYU2

**Comment by thaJeztah** [comment]
I think docker still has iptables as a requirement; http://docs.docker.com/engine/installation/binaries/#check-runtime-dependencies, and http://docs.docker.com/engine/userguide/networking/default_network/container-communication/

The `--iptables=false` option will disable docker making *changes* to the iptables rules, not disable the use of iptables

> Docker will never make changes to your system iptables rules if you set `--iptables=false` when the daemon starts

**Comment by phemmer** [comment]
see also #16964 and #15357

**Comment by higkoo** [comment]
* Iptables must be enable when docker start.
* Iptables can be disable after docker started.

`/usr/bin/docker daemon -H fd:// -H 0.0.0.0:2376 --tls=true --tlscacert=/etc/pki/CA/cacert.pem --tlscert=/etc/pki/libvirt/servercert.pem --tlskey=/etc/pki/libvirt/private/serverkey.pem -s devicemapper --iptables=false --ip-masq=false --ip-forward=false --bridge=none`  
` systemctl -l status docker.service`  
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since Mon 2015-12-07 13:15:20 HKT; 49s ago
     Docs: https://docs.docker.com
  Process: 37415 ExecStart=/usr/bin/docker daemon -H fd:// -H 0.0.0.0:2376 --tls=true --tlscacert=/etc/pki/CA/cacert.pem --tlscert=/etc/pki/libvirt/servercert.pem --tlskey=/etc/pki/libvirt/private/serverkey.pem -s devicemapper --iptables=false --ip-masq=false --ip-forward=false --bridge=none (code=exited, status=2)
 Main PID: 37415 (code=exited, status=2)
Dec 07 13:13:50 docker-svr-31 docker[37415]: time="2015-12-07T13:13:50.985429658+08:00" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
Dec 07 13:13:50 docker-svr-31 docker[37415]: time="2015-12-07T13:13:50.992661150+08:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Dec 07 13:13:51 docker-svr-31 docker[37415]: time="2015-12-07T13:13:51.003383849+08:00" level=info msg="API listen on /var/run/docker.sock"
Dec 07 13:13:51 docker-svr-31 docker[37415]: time="2015-12-07T13:13:51.003435457+08:00" level=info msg="API listen on [::]:2376"
Dec 07 13:13:51 docker-svr-31 docker[37415]: time="2015-12-07T13:13:51.048682966+08:00" level=info msg="Firewalld running: false"
Dec 07 13:15:20 docker-svr-31 systemd[1]: docker.service start operation timed out. Terminating.
Dec 07 13:15:20 docker-svr-31 systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 13:15:20 docker-svr-31 systemd[1]: Failed to start Docker Application Container Engine.
Dec 07 13:15:20 docker-svr-31 systemd[1]: Unit docker.service entered failed state.
```

**Comment by thaJeztah** [comment]
@higkoo there have been some changes made in docker 1.10 (see https://github.com/docker/libnetwork/pull/873) would you be able to test if this issue is resolved in the current release candidate for docker 1.10? https://github.com/docker/docker/releases/tag/v1.10.0-rc2
