### ISSUE TITLE
Headless install of docker fails on ubuntu 15.10

### ISSUE THREAD

**Issue by wr0ngway** [moby/moby#18444]
Description of problem:

I'm trying to install docker-engine 1.9.1 in a  headless fashion on ubuntu wily 15.10, and it is failing with:

```
Setting up docker-engine (1.9.1-0~wily) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
```

By headless, I mean I am using the user-data feature of ec2 to run the install script:

```
#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo bash -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list'
sudo apt-get update && sudo apt-get install -y docker-engine
```

I launch an ec2 instance (m3.medium) using the ubuntu wily 15.10 ami (ami-305d115a) and the above user-data script (you can do this in the ec2 web ui)

Once the instance comes up, you can watch the cloud-init logs to see when it fails:

```
tail -f /var/log/cloud-init-output.log
```

If you subsequently run the install manually with an `apt-get install docker-engine`, it will then succeed.  Likewise if you start a similar instance with no user-data, then a manual install will also succeed.

When looking at the output of `journalctl -xe` I notice that in the failure case, the docker.socket service does not get started, whilst in the success case, it does get started, so I'm guessing the problem lies somewhere near there, but don't know enough about systemd to contribute further.

Failure case:

```
Dec 04 21:55:38 ip-10-1-3-83 cloud-init[1086]: Setting up docker-engine (1.9.1-0~wily) ...
Dec 04 21:55:38 ip-10-1-3-83 groupadd[2197]: group added to /etc/group: name=docker, GID=999
Dec 04 21:55:38 ip-10-1-3-83 groupadd[2197]: group added to /etc/gshadow: name=docker
Dec 04 21:55:38 ip-10-1-3-83 groupadd[2197]: new group: name=docker, GID=999
Dec 04 21:55:39 ip-10-1-3-83 systemd[1]: Reloading.
Dec 04 21:55:39 ip-10-1-3-83 systemd[1]: Reloading.
Dec 04 21:55:39 ip-10-1-3-83 systemd[1]: Reloading.
Dec 04 21:55:39 ip-10-1-3-83 systemd[1]: Reloading.
Dec 04 21:55:39 ip-10-1-3-83 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Dec 04 21:55:40 ip-10-1-3-83 docker[2283]: time="2015-12-04T21:55:40.104265748Z" level=fatal msg="No sockets found"
Dec 04 21:55:40 ip-10-1-3-83 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 04 21:55:40 ip-10-1-3-83 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Dec 04 21:55:40 ip-10-1-3-83 systemd[1]: docker.service: Unit entered failed state.
Dec 04 21:55:40 ip-10-1-3-83 systemd[1]: docker.service: Failed with result 'exit-code'.
```

Success case:

```
Dec 04 22:02:41 ip-10-1-3-83 systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Dec 04 22:02:41 ip-10-1-3-83 systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Dec 04 22:02:41 ip-10-1-3-83 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Dec 04 22:02:41 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:02:41.771564686Z" level=info msg="API listen on /var/run/docker.sock"
Dec 04 22:02:41 ip-10-1-3-83 systemd-udevd[328]: Network interface NamePolicy= disabled on kernel command line, ignoring.
Dec 04 22:02:41 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:02:41.843392181Z" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Dec 04 22:02:41 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:02:41.861958623Z" level=warning msg="XFS is not supported in your system. Either the kernel doesnt support it or mkfs.xfs is not in your PATH. Defaulting to ext4 filesystem"
Dec 04 22:03:28 ip-10-1-3-83 kernel: Bridge firewalling registered
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.668257106Z" level=info msg="Firewalld running: false"
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.706934982Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 04 22:03:28 ip-10-1-3-83 systemd-udevd[2519]: Could not generate persistent MAC address for docker0: No such file or directory
Dec 04 22:03:28 ip-10-1-3-83 kernel: IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.804027004Z" level=warning msg="Your kernel does not support swap memory limit."
Dec 04 22:03:28 ip-10-1-3-83 audit[2564]: AVC apparmor="STATUS" operation="profile_load" profile="unconfined" name="docker-default" pid=2564 comm="apparmor_parser"
Dec 04 22:03:28 ip-10-1-3-83 kernel: audit: type=1400 audit(1449266608.886:15): apparmor="STATUS" operation="profile_load" profile="unconfined" name="docker-default" pid=2564 comm="apparmor_parser"
Dec 04 22:03:28 ip-10-1-3-83 systemd[1]: libcontainer-2442-systemd-test-default-dependencies.scope: Scope has no PIDs. Refusing.
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.894238435Z" level=info msg="Loading containers: start."
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.894654457Z" level=info msg="Loading containers: done."
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.894897537Z" level=info msg="Daemon has completed initialization"
Dec 04 22:03:28 ip-10-1-3-83 docker[2442]: time="2015-12-04T22:03:28.895149450Z" level=info msg="Docker daemon" commit=a34a1d5 execdriver=native-0.2 graphdriver=devicemapper version=1.9.1
Dec 04 22:03:28 ip-10-1-3-83 systemd[1]: Started Docker Application Container Engine.
-- Subject: Unit docker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished starting up.
-- 
-- The start-up result is done.
```

`docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-148879-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.447 GB
 Metadata Space Used: 1.479 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
CPUs: 1
Total Memory: 3.675 GiB
Name: ip-10-1-3-27
ID: TACN:SGUX:6WGI:U6L4:4KQE:O2H5:5XIB:BOAZ:GQHR:RL7N:JWN3:MCC4
WARNING: No swap limit support
```

uname -a:

```
Linux ip-10-1-3-27 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
AWS

How reproducible:
See Description

Steps to Reproduce:
1. See Description

Actual Results:
Running headless prevents install

Expected Results:
Should be able to do a headless install

Additional info:
See Description

**Comment by HackToday** [comment]
For the failed cases, you can manually start docker, and check why it failed, from logs. I think it can help.

**Comment by wr0ngway** [comment]
If I start it manually with `service docker start` after the failure case (without reinstalling), it starts successfully.
Note from the failure case above, this message:

    Dec 04 21:55:40 ip-10-1-3-83 docker[2283]: time="2015-12-04T21:55:40.104265748Z" level=fatal msg="No sockets found"

**Comment by wr0ngway** [comment]
Likewise, if I modify the user-data script to `sudo service docker start` at the end, docker starts up successfully even though the install failed as before.  Thus my conclusion that for some reason the docker.socket service (systemd dependency?) does not get started during a headless install, but everything else is otherwise ok.

Note that I'm actually trying to setup an AWS auto scale group for a docker swarm provisioned via ansible, but have isolated the problem to the above.  This is preventing me from being able to automatically scale up my swarm nodes when experiencing high load.

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/docker/docker/issues/17464, and https://github.com/docker/docker/pull/17903. I see you're using devicemapper with loop-lvm; the change to 100G makes initialization a lot longer, and in some cases causes systemd to timeout. Also, using loops for production is really discouraged because performance is really slow.

**Comment by wr0ngway** [comment]
Thanks for the tips, this is for a project for internal development needs, so nothing too performance critical yet, but its good to know what the easy wins are.  Is there a way to set things up pre-install so that the docker install picks a better set of defaults (i.e. to avoid a potential systemd timeout during install)?

**Comment by thaJeztah** [comment]
Hm, in your case, systemd is used, so I think you should create a drop-in file that overrides the default settings defined in the systemd unit file. Here's some info on creating a drop-in to override settings; http://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

The default unit file as is used by docker can be found here; 
https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service

And the version for 1.9.1 (which may be different from master);
https://github.com/docker/docker/blob/v1.9.1/contrib/init/systemd/docker.service

**Comment by thaJeztah** [comment]
Also interested to hear if that worked out for you. I don't think we currently have anything in our documentation describing how to set the defaults in an automated setup, perhaps we should have some docs around that to give users some pointers (obviously, we shouldn't go into detail w.r.t ansible, chef etc, but some pointers could be useful)

**Comment by thaJeztah** [comment]
Just thinking, perhaps docker-machine could be an option, because docker-machine allows you to set additional options to be used when creating a machine. I think work is done to make docker-machine more usable for automated installs, but I'd defer that one to @nathanleclaire who should be better able to tell that

ping @nathanleclaire perhaps you have some suggestions?

**Comment by wr0ngway** [comment]
Ok, thanks, I am already creating drop-in files for systemd post-install to setup --cluster* options for use with consul, but not sure if that will work pre-install to avoid the issue I'm seeing.  I'll play with the settings from the other issues and see if that helps, but given that I'm able to install manually on a fresh instance, but not install headless on an identical fresh instance, it may work around the issue but not address the root cause

**Comment by thaJeztah** [comment]
cool, I'm really no systemd expert, so cannot give you advice there, but keep us informed, we welcome feedback and suggestions for additions or improvements to the docs :+1:

**Comment by wr0ngway** [comment]
Thanks.  I wasn't able to get a good handle on what the plans for docker-machine are - calling docker-machine from ansible might work (constrained to keep using it for provisioning), but from what I could tell, docker-machine doesn't seem to be targeted towards running on the instances itself, but more as a utility for users to spin up instances - in this case, spin up needs to be controlled by the AWS auto scale group.

**Comment by thaJeztah** [comment]
reeling in @mikedougherty I may be waaaaay off here, but I know he implemented auto scaling for our CI. Worth a shot as well to ask if he has thoughts.

**Comment by wr0ngway** [comment]
I was able to work around this problem by using policy-rc.d to skip running the daemon on install - my provisioning scripts restart it after updating the config anyway, so doesn't matter that it doesn't get started on install, YMMV.

/usr/sbin/policy-rc.d:

    #!/bin/bash
    if [[ "$1" == "docker" && "$2" == "start" ]]; then exit 101; fi

Also filed a ubuntu/cloud-init/systemd bug in case it ends up being the root cause:
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1525361

**Comment by jpetazzo** [comment]
I have the same issue.

**Easy way to reproduce:**

This will boot an instance using current Ubuntu 15.10 image.

(Just set the environment variables to put your keys, and change `key-name` to your SSH key in this specific region.)

```
aws --region us-west-2 ec2 run-instances --image-id ami-9f2cc8ff --key-name jpetazzo --instance-type m3.medium --user-data https://get.docker.io/
```

**Cloud-init output log excerpts:***

```
Setting up docker-engine (1.9.1-0~wily) ... 
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.21-0ubuntu4) ... 
Processing triggers for ureadahead (0.100.0-19) ... 
Processing triggers for systemd (225-1ubuntu9) ... 
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1) 
```

**systemctl info:***

```
ubuntu@ip-172-31-19-17:~$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-01-29 21:11:44 UTC; 2min 49s ago 
     Docs: https://docs.docker.com
 Main PID: 8701 (code=exited, status=1/FAILURE)

Jan 29 21:11:43 ip-172-31-19-17 systemd[1]: Starting Docker Application Container Engine...
Jan 29 21:11:44 ip-172-31-19-17 docker[8701]: time="2016-01-29T21:11:44.012172274Z" level=fatal msg="No sockets found"
Jan 29 21:11:44 ip-172-31-19-17 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 21:11:44 ip-172-31-19-17 systemd[1]: Failed to start Docker Application Container Engine.
Jan 29 21:11:44 ip-172-31-19-17 systemd[1]: docker.service: Unit entered failed state.
Jan 29 21:11:44 ip-172-31-19-17 systemd[1]: docker.service: Failed with result 'exit-code'.
ubuntu@ip-172-31-19-17:~$ 
```

**`docker info` after it's manually started:**

```
ubuntu@ip-172-31-7-238:~$ sudo docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
CPUs: 1
Total Memory: 3.675 GiB
Name: ip-172-31-7-238
ID: RIQZ:OV3U:SPNH:WXL3:V7VI:VQUC:MB73:Y4ME:5JNH:TF2C:AHLP:NI4D
WARNING: No swap limit support
ubuntu@ip-172-31-7-238:~$ 
```

**Current workaround:**

Execute `sudo systemctl start docker` after the boot process.

**Notes:**

This doesn't seem to be linked to the storage driver (since I'm using AUFS).

This happens with stable and test versions of Docker.

This also happens with Ubuntu 15.04 (which is also using systemd).

It doesn't happen with Ubuntu 14.04 (which uses upstart).

It also happens when executing `curl -sSL https://get.docker.com/` from a cloud-init script.

It doesn't happen when running `curl sSL https://get.docker.com/` from a shell once the instance is booted.

I wonder if this could be caused by socket activation, since the message is `No sockets found`, but I'm totally out of my element here.

**Comment by mlaventure** [comment]
The error is from [here](https://github.com/docker/docker/blob/master/api/server/server_unix.go#L104)

I don't know enough about systemd internal to further guess why being started from a cloud-init script would cause no listeners to be found though.

**Comment by bradjones1** [comment]
I can verify I ran into the same problem installing from the docker deb repo on Ubuntu 15.10. The default version, 1.10.0, hangs after the following output:
```
Setting up docker-engine (1.10.0-0~wily) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
insserv: warning: script 'binfmt-support' missing LSB tags and overrides
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `binfmt-support'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `binfmt-support'
```

A quick 'top' of the system shows a number of docker daemon processes and high system load.

If you purge that package and explicitly request an earlier version with `sudo apt-get install docker-engine=1.9.1-0~wily`, there is considerably less system load and the installer reportedly fails with:

```
Setting up docker-engine (1.9.1-0~wily) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
insserv: warning: script 'binfmt-support' missing LSB tags and overrides
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `binfmt-support'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `binfmt-support'
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (225-1ubuntu9) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Per the note above, you can subsequently start the daemon with `sudo systemctl start docker`, and also `sudo service docker start`.

I apologize I'm not able to debug this much more but hopefully this additional info helps.

**Comment by thaJeztah** [comment]
@bradjones1 was this a fresh install? otherwise this could be related to the migration to content addressable storage; https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by bradjones1** [comment]
@thaJeztah I re-ran this at a time I could be more patient and yes, this appears to be a long migration job. I wonder if it wouldn't be helpful to put some sort of note in the apt install script that says "Migrating...this might take a while..." ?

**Comment by studentIvan** [comment]
I had to turn off my openvpn connection before I start "sudo systemctl start docker"
After this all problems gone away.

**Comment by radimklaska** [comment]
Turning off openvpn helped me too.

**Comment by ahawkins** [comment]
Related: #22847 and #23793. This seems to me the most indepth issue as @jpetazzo pointed out. I've duplicated this bug on ubuntu 16.04 with docker version 1.11.2.

**Comment by matyapiro31** [comment]
Same error at Ubuntu 16.04 LTS.
