### ISSUE TITLE
Container's own hostname not set in /etc/hosts when using --x-networking

### ISSUE THREAD

**Issue by maxirus** [moby/moby#18539]
#### Problem Description

When using the --x-networking switch to bring up a docker-compose, each container is unaware of it's own hostname. For example, if I have LOCAL/docker-compose.yml with service_a and service_b, service_b can ping service_a and vice-versa however service_b can NOT ping service_b. This is because the container's hostname is not being added to /etc/hosts, 127.0.0.1 local_service_b.
#### Host Setup
- Environment: Physical
- `docker version`: 
  _Client_:
  Version:      1.9.1
  API version:  1.21
  Go version:   go1.4.2
  Git commit:   a34a1d5
  Built:        Fri Nov 20 13:12:04 UTC 2015
  OS/Arch:      linux/amd64
  _Server_:
  Version:      1.9.1
  API version:  1.21
  Go version:   go1.4.2
  Git commit:   a34a1d5
  Built:        Fri Nov 20 13:12:04 UTC 2015
  OS/Arch:      linux/amd64
- `uname -a`: Linux bimmer 3.19.0-39-generic #44~14.04.1-Ubuntu SMP Wed Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `docker info`: 
  Containers: 0
  Images: 115
  Server Version: 1.9.1
  Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 115
  Dirperm1 Supported: true
  Execution Driver: native-0.2
  Logging Driver: json-file
  Kernel Version: 3.19.0-39-generic
  Operating System: Ubuntu 14.04.3 LTS
  CPUs: 4
  Total Memory: 15.58 GiB
  Name: bimmer
  ID: YUKB:J3D7:GXOM:OSLT:RUJZ:RKVY:BA7D:ARBD:TKPT:26ZZ:ZIY2:QLPO
  WARNING: No swap limit support
- `docker-compose --version`: docker-compose version 1.5.2, build 7240ff3
#### How to Reproduce

To reproduce, create a docker-compose.yml file with two services. Bring then bring the services up using `docker-compose --x-networking up` and then inspect the `/etc/hosts` file.
### Steps to Reproduce
1. Create/Pull CentOS 7.1.1503 image
2. Create a LOCAL/docker-compose.yml with two services (service_a and service_b) using the CentOS image.
3. Run `docker-compose --x-networking up`
4. Inspect one of the container's (`docker exec -it <CONTAINER_ID> /bin/bash`) `/etc/hosts` file
#### Actual Result

No entry for `127.0.0.1 local_service_(a|b)` in `/etc/hosts`
#### Expected Results

`127.0.0.1 local_service_a` in service_a's `/etc/hosts`
`127.0.0.1 local_service_b` in service_b's `/etc/hosts`

**Comment by thaJeztah** [comment]
Why not use `localhost` if you want the local service? Just wondering what the use case is here. Also, I'm not sure it'd be logical to use 127.0.0.1 for this, and not the IP-address of the container

**Comment by maxirus** [comment]
We have a use case for Hazelcast. When a Hazelcast node is brought up, it tries to join other nodes that are outline in it's config. If the hostname of the node is it's self, then it binds to that address whether it be localhost (127.0.0.1) or some RFC1918 address. However, since the hostname is not set in /etc/hosts, it fails to bind and thus the nodes won't join together as a cluster.

**Comment by mavenugo** [comment]
@maxirus we added an explicit check to avoid adding self into the `/etc/hosts`. I dont recall the scenario that forced us to do that. @mrjana might point us to the PR that brought in the change in libnetwork.

**Comment by mrjana** [comment]
@maxirus `127.0.0.1` will only be resolved by the standard string `localhost` or `localhost.localdomain`. If you want to resolve self you need to add an explicit `--hostname` argument in your `docker run` command and we add an entry in `/etc/hosts` file for that host name to point to the IP address of the container. If you did not provide the `--hostname` option container ID is used for creating this entry, which is not all that useful. This works across all kinds of networks so you don't need to worry about whether you are using the default bridge network or some other network or even if the container has a name or not.

**Comment by thaJeztah** [comment]
There's also `--add-host=hostname:ip-address`, which will add an entry to the host file; see https://docs.docker.com/engine/reference/commandline/run/#add-entries-to-container-hosts-file-add-host

**Comment by thaJeztah** [comment]
@maxirus can you work with the suggestions mentioned above, would they solve your use-case?

**Comment by maxirus** [comment]
No, unfortunately these won't work as they all assume you know the hostname/ip of the container.

The hostname is variable based on the name of the directory the compose file is in as well as the service name. IP assignment is not static to a service so that will change as well. Using these suggestions adds another layer of (redundant) config when running a docker-compose.yml definition. What is the use-case for a container to **not** want to know it's own hostname?

**Comment by bmcgiv** [comment]
+1 for this issue.  

I see that the container's own ID is currently being added to /etc/hosts to resolve to its assigned IP address, but would have expected that the container's own *name* would also appear (as that container name is added to every other container's /etc/hosts file).

**Comment by kierr** [comment]
I too seem to have the immediately above issue, of a container's own ID being added to the hosts file, but nothing for it's name.

**Comment by mathiasconradt** [comment]
I am seeing even the behavior that the container takes the hostname of its container host rather then his own container id. This happens on a Windows container though (on Windows Server 2016 TP4):
While a "`docker inspect`" shows the container id, executing a "`hostname`" inside a container shows the name of the container host instead. In my case this is relevant because the Visual Studio remote debugger seems to take the hostname from the docker config. I described the issue on [StackOverflow](http://stackoverflow.com/questions/36420337/running-visual-studio-remote-debugger-in-windows-container-docker-managed).
But I should probably open a new ticket for that, since it's Windows container specific and not directly related to `x-networking switch`.

**Comment by jannemann** [comment]
Another use-case for the availability of the containers hostname is to configure an akka cluster. If you want to use hostnames to connect to a master the master itself has to validate the called hostname.

http://doc.akka.io/docs/akka/snapshot/java/remoting.html

**Comment by PommeVerte** [comment]
Or supporting multiple apache vhosts.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
