### ISSUE TITLE
[Proposal] Inject temporary secret files into build

### ISSUE THREAD

**Issue by bfirsh** [moby/moby#18603]
A common request is to be able to inject secret files into the build process and have them not end up in the built image.

For example:
- A user may be using RHEL and need to put their license key inside the container to install packages, but they don't want it to end up in the final image.
- A user may need to pass in their SSH agent/key to clone a Git repository, use a private Gem repo, use a private APT repo, etc.
- A user may need to pass in SSL certs to be able to install dependencies.
### Possible solutions
- [Some way of forwarding SSH agents into the build](https://github.com/docker/docker/issues/6396)
- [Build could allow volumes to be mounted](https://github.com/docker/docker/issues/14080)
- Use some kind of secrets store which the build process could read from and turn into files. This could either need to be done in a single build step, or the files could be marked somehow as files which aren't committed to the image.
### Related issues
- [Proposal: Dockerfile BINDMOUNT for secure- and/or offline Dockerfile build environments](https://github.com/docker/docker/issues/10199)
- [Proposal: Dockerfile add BIND_CONTEXT](https://github.com/docker/docker/issues/3056)
- [Proposal: SLINK instruction for Dockerfile](https://github.com/docker/docker/issues/7654)
- [Secrets: write-up best practices, do's and don'ts, roadmap](https://github.com/docker/docker/issues/13490)

**Comment by runcom** [comment]
> Build could allow volumes to be mounted

I have a patch which allows binds at build time https://github.com/runcom/docker/commit/16fe6c8ea50b463a7e5895724e041f61292dd399
related to https://github.com/docker/docker/issues/14080
Only bind mounts are allowed, it's pretty rough and it currently skip cache if binds are passed but can be thought and worked on :)

**Comment by thaJeztah** [comment]
If we allowed volumes during build, the volume could also use a volume-driver, thinking of the Keywhiz driver (I think I mentioned that in https://github.com/docker/docker/issues/13490)

**Comment by NikolausDemmel** [comment]
Additional possible solution: Support tmpfs mounts during build, similar to what is possible during `run` since 1.10: https://github.com/docker/docker/pull/13587

**Comment by jdiaz5513** [comment]
call me crazy, but can't the `ARG` instruction be modified so that it doesn't store the build arg itself in the metadata, but just a (non-reversible) hash of it? that'll keep the secret itself out of any persistent storage _and_ preserve the ability to cache based on the arg value.

**Comment by cpuguy83** [comment]
@jdiaz5513 secrets in environment variables are not secret.

See #28079 for build secrets.

**Comment by jdiaz5513** [comment]
Very happy to see that PR. That's a much better solution! 😄

**Comment by AkihiroSuda** [comment]
`docker build --secret` is finally available in Docker 18.09 https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066
