### ISSUE TITLE
docs: installation instructions for mac drive new users into vboxfs sendfile bug

### ISSUE THREAD

**Issue by felixge** [moby/moby#18666]
Description of problem:

The [Installation on on Mac OS X](https://docs.docker.com/engine/installation/mac/) tutorial instructs users to mount a local folder as a container volume for nginx to serve.

```
$ docker run -d -P -v $HOME/site:/usr/share/nginx/html --name mysite nginx
$ echo "my new site" > index.html
$ echo "This is cool" > cool.html
etc.
```

This works, but if you're a little red riding hood such as myself, you may let the whale-wolf trick you into venturing into the forrest to pick some flowers for your grandmother, or in my case overwrite one of the files with new data. This will drive you into the arms of a [5 years old vboxfs sendfile bug](https://www.virtualbox.org/ticket/9069), causing updates to the file to show only partially, or not at all, when served via nginx. And we all know how that story ends :smile: .

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
`docker info`:
Containers: 12
Images: 65
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 89
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: P2Y6:MOYK:HJRI:XNP2:LAZ5:JB4C:CLHS:I56K:BEVH:WTTK:ZY3G:IGPY
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 35
 System Time: 2015-12-15T13:16:40.814333675Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: felixge
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
`uname -a`:
Darwin Felix-MBP-2012.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

VirtualBox:  5.0.10 r104061

Steps to Reproduce:
1. Follow the tutorial
2. Overwrite one of the html files with e.g. "echo 1235" > index.html after initially creating it
3. Reload the file in the browser

You may need to overwrite several times with different data to see the problem. I've also found that `echo <data> > <file>`  produces the problem more reliably than editing it with vim.

Ideally this bug could be fixed in VirtualBox. But short of that, I think the best solution is to create a dedicated description of this as a "known issue" somewhere, and link to that article from the installation tutorial, as well as other tutorials that make use of nginx / containers that are using sendfile.

**Comment by thaJeztah** [comment]
> This works, but if you're a little red riding hood such as myself, you may let the whale-wolf trick you into venturing into the forrest to pick some flowers for your grandmother, or in my case overwrite one of the files with new data. 

Haha :smile_cat: 

> Ideally this bug could be fixed in VirtualBox. But short of that, I think the best solution is to create a dedicated description of this as a "known issue" somewhere.

Yes, we may want to add a note if many people are running into this. Perhaps it should also be mentioned here; https://docs.docker.com/machine/drivers/virtualbox/ (that file is in the "machine" repository; https://github.com/docker/machine/blob/master/docs/drivers/virtualbox.md)

Are you interested in creating a pull request to add a note in the "installation" section? The Markdown files for Mac and Windows are here; https://github.com/docker/docker/blob/master/docs/installation/mac.md and https://github.com/docker/docker/blob/master/docs/installation/windows.md

**Comment by felixge** [comment]
@thaJeztah sounds good. I'll send a PR tomorrow.

**Comment by thaJeztah** [comment]
@felixge awesome! I see you've not contributed before; we have a contributors guide in our documentation that contains lots of useful information https://docs.docker.com/opensource/

**Comment by felixge** [comment]
@thaJeztah I created PR for the machine docs here: https://github.com/docker/machine/pull/2597

Once that is merged, I'll send a PR for the mac/windows docs to link to the detailed problem description.

Let me know what you think.

**Comment by thaJeztah** [comment]
Thanks @felixge! Your PR in "machine" was just merged (yay!)

**Comment by felixge** [comment]
@thaJeztah sweet. I'll do another one for the installation tutorials tomorrow.

**Comment by thaJeztah** [comment]
@felixge great! I marked this issue "claimed" for you. No hurry :smile:

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
