### ISSUE TITLE
How can we output the full urls when visiting registries for `docker pull`?

### ISSUE THREAD

**Issue by freewind** [moby/moby#18675]
This is from this question: http://stackoverflow.com/questions/34294234/how-to-let-docker-registry-log-all-the-accurate-urls-it-visits-for-better-debugg

If docker doesn't support it now, is it possible to add this support? Thanks in advance

**Comment by LK4D4** [comment]
Probably still valid request for more debugging info.

**Comment by thaJeztah** [comment]
- closing in favor of https://github.com/moby/moby/issues/11621
