### ISSUE TITLE
Reference package should not be forked

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#18731]
#18586 basically forked the `distribution/reference` package. We need to fix this up so this issue is tracking the movement. https://github.com/docker/distribution/pull/1277 has been submitted to upstream some changes from that PR but we'll need to undo the duplicate type definitions (reference.Named, etc.).

**Comment by thaJeztah** [comment]
Adding this to the 1.10 milestone, think we should try to fix it before it's in a release

**Comment by thaJeztah** [comment]
@tonistiigi I'll assign you to this, if you can co-ordinate with @aaronlehmann and @stevvooe?

**Comment by stevvooe** [comment]
@thaJeztah No rush here but that is a reasonable target. This is more of a code quality issue than anything else.

**Comment by thaJeztah** [comment]
@stevvooe sure, I saw the discussion on the other issue, and realize it's not a show-stopper. Thought it'd be good to have somebody assigned to it and try and get it done before the release :+1:

**Comment by LK4D4** [comment]
It's still an issue btw. Not sure whom to ping
ping @stevvooe @aaronlehmann @tonistiigi @dmcgowan

**Comment by dmcgowan** [comment]
Upstream work is here https://github.com/docker/distribution/pull/1778

**Comment by thaJeztah** [comment]
Looks like this was already fixed for some time; but should be fully resolved by;

- https://github.com/moby/moby/pull/46376
