### ISSUE TITLE
Should be able to change graph driver mount points across Get and Put

### ISSUE THREAD

**Issue by gourao** [moby/moby#18732]
In our graph driver, we would like to change the mount point returned in the `Get` call for a given ID.  The mount point should be allowed to change after a `Put`.

That is, when Get is called, I return a certain path.  Then Put is called and I release that path and re-use it for other containers.

When Get is called on the original ID again, I may return a different mointpoint and Docker does not seem to like that. 

```
Error response from daemon: Error: driver unionfs is returning inconsistent paths for container a7f0fbc25768f625592322a58c76443be237bd817aa4a239f22181b8916c1c6a ('/var/lib/openstorage/fuse/virtual/1' then '/var/lib/openstorage/fuse/virtual/2')
```

We can improve the metadata performance if Docker allows this.
ping @cpuguy83 

---

`docker version`:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9-dirty
 Built:        Mon Nov  9 23:37:50 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   ee03a05
 Built:        Tue Dec  8 21:28:02 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 0
Images: 0
Server Version: 1.10.0-dev
Storage Driver: openstorage-unionfs
 OpenStorage FUSE: OK
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.304 GiB
Name: ip-172-31-24-98.us-west-1.compute.internal
ID: 37MZ:22MW:QPLA:GI63:PBJT:JEBJ:PCFK:XYSO:ODVF:PE4U:6OD3:HU6W
Experimental: true

`uname -a`:
Linux ip-172-31-24-98.us-west-1.compute.internal 3.19.3-1.el7.elrepo.x86_64 #1 SMP Thu Mar 26 10:57:36 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
ping @cpuguy83 could you have a look at this?

**Comment by cpuguy83** [comment]
Yeah, I don't know why the daemon cares about this.
Maybe there was a bug from before, but I know this has been in for awhile.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
