### ISSUE TITLE
Should be able to start Docker and run a container even if the graph driver is not loaded

### ISSUE THREAD

**Issue by gourao** [moby/moby#18735]
ping @cpuguy83 

This is with respect to 
https://github.com/docker/docker/blob/master/experimental/plugins_graphdriver.md

We would like to run our graph driver in a container.  This causes obvious problems.

Two possible options
1. Allow a "bootstrap"  container to start with a default graph driver.
2. Allow a container to specify it's graph driver target with the same exact parameters and `storage_options` used by the daemon.

---

docker version:
Client:
Version: 1.9.0
API version: 1.21
Go version: go1.4.3
Git commit: 76d6bc9-dirty
Built: Mon Nov 9 23:37:50 UTC 2015
OS/Arch: linux/amd64
Experimental: true

Server:
Version: 1.10.0-dev
API version: 1.22
Go version: go1.5.1
Git commit: ee03a05
Built: Tue Dec 8 21:28:02 UTC 2015
OS/Arch: linux/amd64

docker info:
Containers: 0
Images: 0
Server Version: 1.10.0-dev
Storage Driver: openstorage-unionfs
OpenStorage FUSE: OK
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.304 GiB
Name: ip-172-31-24-98.us-west-1.compute.internal
ID: 37MZ:22MW:QPLA:GI63:PBJT:JEBJ:PCFK:XYSO:ODVF:PE4U:6OD3:HU6W
Experimental: true

uname -a:
Linux ip-172-31-24-98.us-west-1.compute.internal 3.19.3-1.el7.elrepo.x86_64 #1 SMP Thu Mar 26 10:57:36 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
This is possible with v2 plugins.
Thanks!
