### ISSUE TITLE
docker overlay network lost when  reboot ?

### ISSUE THREAD

**Issue by Dreampie** [moby/moby#18841]
docker overlay network lost when reboot,recreate error:

```
docker network create --driver overlay swarm-net
Error response from daemon: error getting pools config from store during init: could not get pools config from store: Unexpected response code: 500
```

must rm consul  and  recreate it

```
docker run -d -p 8500:8500 -h consul --name consul progrium/consul -server -bootstrap
```

and I must recreate all container in this swarm master

```
docker version && docker info && uname -a
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
Containers: 10
Images: 118
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-33993639-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.941 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.86 GB
 Metadata Space Used: 5.575 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 993 MiB
Name: localhost.localdomain
ID: R2NX:ZX6S:PQIE:R65Y:X62A:ACXU:MALH:RXHK:BRF5:6RMU:NJLG:TMPL
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: consul://192.168.60.41:8500
Cluster advertise: 192.168.60.41:2376
Linux localhost.localdomain 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by brikeyes** [comment]
I am getting the same error for months on a 1.91 and now on 1.11 docker I am at a total loss to figure out what is going on 

Error response from daemon: error getting pools config from store during init: could not get pools config from store: Unexpected response code: 500

**Comment by brikeyes** [comment]
I restarted the host , removed the consul container , rebuilt the container  with 
"docker run -d -p 8500:8500 -h consul --name consul progrium/consul -server –bootstrap"
and it works now

**Comment by cpuguy83** [comment]
Running the store in a container can make things funky.
We do a pretty good job at trying to make this happen in 1.11.2 where we wait to initialize any containers that use a network that is using the cluster store... this allows the container with the cluster store to come up before attempting to load containers that require it.

Not surprised that things aren't perfect in 1.9.1, it's pretty old and we've fixed many things.
Can you try on 1.11.2?

**Comment by brikeyes** [comment]
this was 1.1.2 on Ubuntu 15.10 , rebooted and rebuilt conatiner for consul and it worked ,

one question what log would have been helpful to look into this ?

thanks!!

**Comment by mavenugo** [comment]
@cpuguy83 +1. But in this case, @brikeyes is trying to create a network (and is not a container runtime issue).

@brikeyes i dont see the restart policy set for this consul container. Are you not expecting the container to restart automatically during daemon restart ?
Also, I have seen issues in the past with consul and restarting that container if its ip-address changes. So I typically run consul with `--ip` option (which provides a static IP) in an `user-defined` network.
These are some of the steps to take to make sure consul container works properly across restarts.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and overlay networks with external k/v stores has been deprecated and removed.
