### ISSUE TITLE
Delete data in a container devicemapper can not  free used space

### ISSUE THREAD

**Issue by cxxly** [moby/moby#18867]
# Environment

```
[root@localhost Desktop]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 

[root@localhost Desktop]# uname -a
Linux localhost.localdomain 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015         x86_64 x86_64 x86_64 GNU/Linux

[root@localhost Desktop]# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

[root@localhost Desktop]# docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-24931-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 53.74 MB
 Data Space Total: 107.4 GB
 Data Space Available: 35.46 GB
 Metadata Space Used: 606.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
# Reproduced

```
[root@localhost Desktop]# docker pull busybox

[root@localhost Desktop]# docker info
Containers: 0
Images: 2
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-24931-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 61.01 MB
 Data Space Total: 107.4 GB
 Data Space Available: 35.45 GB
 Metadata Space Used: 626.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Write a file in container**

```
[root@localhost Desktop]# docker run -it busybox
/ # dd bs=1M count=1024 if=/dev/zero of=test
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 1.378665 seconds, 742.7MB/s

[root@localhost Desktop]# docker info
Containers: 1
Images: 2
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-24931-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.14 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.37 GB
 Metadata Space Used: 1.176 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**After delete it, the used space can not free**

```
[root@localhost Desktop]# docker run -it busybox
/ # dd bs=1M count=1024 if=/dev/zero of=test
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 1.378665 seconds, 742.7MB/s
/ # rm -f test 

[root@localhost Desktop]# docker info
Containers: 1
Images: 2
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-24931-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.14 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.37 GB
 Metadata Space Used: 1.176 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
# Other information

Delete images or container, the space wil be reclaimed

**Comment by thaJeztah** [comment]
> Delete images or container, the space wil be reclaimed

so, if you remove the containers, the space will be returned? (otherwise this one may be related: https://github.com/docker/docker/issues/3182)

This may be expected behavior for device mapper on loop-devices, but perhaps @rhvgoyal can have a look

(note: using loop devices is not really suitable for productions, for more information on how to configure device mapper for production, see https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/)

**Comment by rhvgoyal** [comment]
I think you are talking about reclaiming space upon file removal and that will happen only if filesystem issues discards. And there seem to be two ways to do that.

- Either mount filesystem using option `-o discard`. But this often imposes significant performance penalty.

- Or run `fstrim /` after file removal and that should reclaim the space back.

Note: you will have to run container with `--cap-add=SYS_ADMIN` to be able to run `fstrim`

**Comment by cxxly** [comment]
I have run a application in a container which will write and delete some temp continually, it will cause the size of devicemapper over 100G and be readonly mode.

**Comment by cxxly** [comment]
@rhvgoyal , I have made a test,  fstrim cannot solve this problem.

	[root@localhost Desktop]# docker info 
	Containers: 0
	Images: 2
	Server Version: 1.9.1
	Storage Driver: devicemapper
	 Pool Name: docker-253:1-24931-pool
	 Pool Blocksize: 65.54 kB
	 Base Device Size: 107.4 GB
	 Backing Filesystem: 
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 61.01 MB
	 Data Space Total: 107.4 GB
	 Data Space Available: 35.45 GB
	 Metadata Space Used: 626.7 kB
	 Metadata Space Total: 2.147 GB
	 Metadata Space Available: 2.147 GB
	 Udev Sync Supported: true
	 Deferred Removal Enabled: false
	 Deferred Deletion Enabled: false
	 Deferred Deleted Device Count: 0
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.93-RHEL7 (2015-01-28)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.10.0-229.14.1.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	CPUs: 2
	Total Memory: 1.784 GiB
	Name: localhost.localdomain
	ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
	WARNING: bridge-nf-call-iptables is disabled
	WARNING: bridge-nf-call-ip6tables is disabled

	[root@localhost Desktop]# docker run --cap-add=SYS_ADMIN -it busybox
	/ # dd bs=1M count=1024 if=/dev/zero of=test
	1024+0 records in
	1024+0 records out
	1073741824 bytes (1.0GB) copied, 1.547162 seconds, 661.9MB/s
	/ # 


	[root@localhost Desktop]# docker info
	Containers: 1
	Images: 2
	Server Version: 1.9.1
	Storage Driver: devicemapper
	 Pool Name: docker-253:1-24931-pool
	 Pool Blocksize: 65.54 kB
	 Base Device Size: 107.4 GB
	 Backing Filesystem: 
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 1.14 GB
	 Data Space Total: 107.4 GB
	 Data Space Available: 34.37 GB
	 Metadata Space Used: 1.176 MB
	 Metadata Space Total: 2.147 GB
	 Metadata Space Available: 2.146 GB
	 Udev Sync Supported: true
	 Deferred Removal Enabled: false
	 Deferred Deletion Enabled: false
	 Deferred Deleted Device Count: 0
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.93-RHEL7 (2015-01-28)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.10.0-229.14.1.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	CPUs: 2
	Total Memory: 1.784 GiB
	Name: localhost.localdomain
	ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
	WARNING: bridge-nf-call-iptables is disabled
	WARNING: bridge-nf-call-ip6tables is disabled

	/ # rm -f test 
	/ # fstrim /
	/ # 

	[root@localhost Desktop]# docker info
	Containers: 1
	Images: 2
	Server Version: 1.9.1
	Storage Driver: devicemapper
	 Pool Name: docker-253:1-24931-pool
	 Pool Blocksize: 65.54 kB
	 Base Device Size: 107.4 GB
	 Backing Filesystem: 
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 1.14 GB
	 Data Space Total: 107.4 GB
	 Data Space Available: 34.37 GB
	 Metadata Space Used: 1.176 MB
	 Metadata Space Total: 2.147 GB
	 Metadata Space Available: 2.146 GB
	 Udev Sync Supported: true
	 Deferred Removal Enabled: false
	 Deferred Deletion Enabled: false
	 Deferred Deleted Device Count: 0
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.93-RHEL7 (2015-01-28)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.10.0-229.14.1.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	CPUs: 2
	Total Memory: 1.784 GiB
	Name: localhost.localdomain
	ID: K3C5:7YDM:RIXL:3SFO:FNGY:5N5E:44BM:Z72Y:O6N6:RYU5:ZOWQ:XWR3
	WARNING: bridge-nf-call-iptables is disabled
	WARNING: bridge-nf-call-ip6tables is disabled

**Comment by rhvgoyal** [comment]
If fstrim is not working, I suspect there is some bug somewhere. I had tried it yesterday and it worked for me. I was using latest upstream docker on fedora 23. We will have to figure out what's different.

**Comment by cxxly** [comment]
@rhvgoyal  can you paste your steps here. I also had tried on fedora, but it didn't work for me yet. May be I overlook something.

**Comment by avra911** [comment]
Hi,

Same for me:
```
[razvan@localhost]$ docker info
Containers: 4
Images: 90
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:2-919473-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.199 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.2 GB
 Metadata Space Used: 4.923 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/razvan/.docker/devicemapper/devicemapper/data
 Metadata loop file: /home/razvan/.docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.8-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
CPUs: 4
Total Memory: 7.43 GiB
Name: localhost.localdomain
```

Strange that `Base Device Size: 107.4 GB` has exactly the same size.

Best,
R

**Comment by rhvgoyal** [comment]
@cxxly I did following.

- Installed latest Fedora 23
- Built latest docker (1.10-dev)
- Start latest docker
- `docker pull fedora`
-  `docker run -ti --cap-add=SYS_ADMIN fedora bash`
- Inside container created a 1G file, removed it and then issued fstrim.
 `dd if=zerofile bs=1M count=1K; sync`
`rm zerofile;sync`
`fstrim /`

And this reclaimed 1G back from data space usage. My filesystem on host is ext4 and xfs inside container.

Following is my docker info output.

`
# docker info
Containers: 1
Images: 1
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-252:1-1441970-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 293.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 37.1 GB
 Metadata Space Used: 806.9 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.8-300.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
CPUs: 8
Total Memory: 7.797 GiB
Name: vm4-f23.localdomain
ID: EXMN:AVQR:2MQN:SHIC:RBXI:4PAX:WHUC:HHZL:A5I5:5UTS:PMBG:DRLS
Debug mode (server): true
 File Descriptors: 19
 Goroutines: 45
 System Time: 2016-01-04T15:29:20.302040928Z
 EventsListeners: 0
 Init SHA1: 75c088f2fefd5ab61b1cb7ef065d3cc7e3c21445
 Init Path: /root/git/rhvgoyal-docker/bundles/latest/dynbinary/dockerinit
 Docker Root Dir: /var/lib/docker
`

**Comment by karolzmuda** [comment]
I am experiencing similar issue which can be found under #19083. Is it possible to solve this problem without changing OS?

**Comment by rhvgoyal** [comment]
To me, it is best to move away from loop devices. Not only these are slow but these will introduce the issues of discards.

If you just can't move away from loop devices, then one has to either issue `fstrim` at regular intervals or enable online discard in container filesystem. (`-o discard`).

Right now in the code, for ext4 `nodiscard` is hard coded. So I don't think there is a way to enable online discards for ext4. But one should be able to do so for xfs. Try following.

- Remove existing instance of docker metadata `rm -rf /var/lib/docker`
- Pass following options to docker daemon. 
  `-s devicemapper --storage-opt dm.fs=xfs --storage-opt dm.mountopt=discard`
- Start docker daemon.

Now if you remove the file, fs should issue discards and reclaim the space back. This should be slower though as discards are issues inline.

**Comment by cxxly** [comment]
Testing with --storage-opt dm.mountopt=discard options on centos7,  fs  reclaim the space back successfully, but it is very slow.

**Comment by rhvgoyal** [comment]
right, online/inline discard is very slow and that's why it is disabled by default. Using inline discard is least preferred option and fstrim is recommended instead.

I would say if you move away from loop devices and start using an lvm thin pool, that would work out better for you.

**Comment by cxxly** [comment]
However, fstrim cann't  reclaim the space back which make me confused.

Additional, using direct-lvm mode with physical block device(reference https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/) still cann't solve this problem without --storage-opt dm.mountopt=discard option. And if I use this option, it is still very slow.

I made all tests on VMWARE Workstation, is it related?

**Comment by cerber717** [comment]
any new on this one ?

**Comment by cxxly** [comment]
Have this problem been solved?

**Comment by depay** [comment]
running `fstrim /proc/$(docker inspect --format='{{ .State.Pid }}' <cid>)/root` on host works for me.

centos 7.2 + docker 1.9.1(devicemapper, xfs)

**Comment by depay** [comment]
@cxxly , i found something interesting, maybe having no relation to this issue... why is your used+available space less than total one so much?

```
 Data Space Used: 61.01 MB
 Data Space Total: 107.4 GB
 Data Space Available: 35.45 GB
```

**Comment by Umkus** [comment]
Awesome! @depay's solution worked perfectly!
Here's a version to apply this for all containers:

```bash
# docker ps -qa | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/
```



*Before:*
```shell
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G   28G  378M  99% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  394M  3.6G  10% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
```

*After:*
```bash
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G   16G   13G  55% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  394M  3.6G  10% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
```

**Comment by thaJeztah** [comment]
@rhvgoyal you think this is something that needs to be documented? ^^

**Comment by cerber717** [comment]
^ 👍

**Comment by rhvgoyal** [comment]
This seems to be working for me. Did not know about /proc/pid/root stuff.

Anyway, this will work only for running containers. So we can do "docker ps -q" instead of "docker ps -aq".

Useful when container app does not have fstrim or does not have permission to run fstrim. I think its a good idea to document it and see how well does it work. I tried to run docker daemon in its own mount namespace and still it seemed to work.

**Comment by cxxly** [comment]
This solution worked for me. @depay I had not noticed that . Currently I use docker 1.11, have not the problem
```
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 36
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-2150053334-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.631 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.7 GB
 Metadata Space Used: 10.93 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.596 GiB
Name: master
ID: TNEP:LMFO:3LK6:QKSS:CKE6:L3HE:LNTD:73X7:NLPA:O4U2:5PSA:D23G
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by dj-hedgehog** [comment]
Can I also use `fstrim` to free up space on containers I already deleted? 
Also will switching to `direct-lvm` mode fix my problem?

**Comment by rhvgoyal** [comment]
If you deleted container, blocked occupied by that container have already been returned to thin pool. So no need to run fstrim.

**Comment by aekazitt** [comment]
When I run the command above, it does not solve the issue.
This command: 
```
docker ps -qa | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/
```
Instead I get this response
```
fstrim: cannot open /proc/0/root: No such file or directory
```

The distribution version is below, running on AWS Beanstalk:
```
Linux version 4.14.62-65.117.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC))
```
Docker version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Jul 20 19:24:06 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6/18.03.1-ce
  Built:        Fri Jul 20 19:25:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by L-P** [comment]
@aekazitt that's because you have stopped containers, running `docker container prune` beforehand should fix it (or you could put a `grep -Ev '^0$'` before `xargs`).

**Comment by Imaskar** [comment]
For me the workaround above shows the following error:
```
fstrim: /proc/5210/root/: FITRIM ioctl failed: Structure needs cleaning
xargs: fstrim: exited with status 255; aborting
```
And it has happened on several virtual machines on AWS EC2.

**Comment by ggregoire** [comment]
Kinda cross-topic, but FYI, AWS ElasticBeanstalk released 2 months ago a new type of Docker environment based on Amazon Linux 2, which uses OverlayFS instead of DeviceMapper: https://aws.amazon.com/blogs/compute/introducing-a-new-generation-of-aws-elastic-beanstalk-platforms

> The Docker AL2 platform is rewritten internally, but provides largely the same customer experience. It does offer improved I/O performance by using the OverlayFS storage driver. This is a change from the previous Docker platform, which used the older and slower Device Mapper storage driver and required an extra Amazon EBS volume.

The option is now visible in the console:

![Screen Shot 2020-06-30 at 6 41 33 PM](https://user-images.githubusercontent.com/591804/86187722-13847d00-bb02-11ea-9539-884c2530e442.png)

I guess OverlayFS doesn't have the same issue than DeviceMapper, so hopefully I'll fix the issue for people running their Docker apps on AWS EB.
