### ISSUE TITLE
docker daemon fails to restart containers on startup randomly

### ISSUE THREAD

**Issue by zfil** [moby/moby#19004]
**Description**

From time to time when the docker daemon starts it fails to restart containers (with restart policy always).
The containers are left in `Exited` state and 2 veth interfaces are left behind per container.

At this point:
- it is not possible to restart or remove these containers
- it is not possible to start new ones as well (they stays in `Created` state).

Stopping and starting the docker daemon don't fix the issue. However rebooting the machine fixes the problem (and the stuck containers restart normally).

From the daemon log it appears there is an issue when the docker daemon tries to configure cpuset cgroups (infinite loop in ensureParent function). It seems it is triggered by a race condition (you can see 2 goroutines doing this in the stack trace). The PR docker/libcontainer#642 seems to be what introduced this bug.

I don't have a bug reproduction scenario, it happens regularly after a system reboot.

**uname -a**
`Linux shepard 3.19.0-42-generic #48~14.04.1-Ubuntu SMP Fri Dec 18 10:24:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**docker version**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info**

```
Containers: 2
Images: 37
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-42-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.43 GiB
Name: shepard
ID: YAWF:OY7V:IGZ5:GGI4:3RYT:2K3W:UU3N:ZKKH:BFST:S6PF:YCYU:UAYO
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 21
 System Time: 2015-12-30T19:37:08.30542934+01:00
 EventsListeners: 0
 Init SHA1: 4fc7c03a06c675f115b39958c13486d53df10a14
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: zfil
Registry: https://index.docker.io/v1/
```

**daemon debug log**

[docker.log.zip](https://github.com/docker/docker/files/75220/docker.log.zip)

**Comment by zfil** [comment]
I wonder if the issue is not triggered by a host network configuration change.

I'm on a laptop plugged on a docking station using the wired NW from it, this morning I'm not in the office and booting the laptop with only the wifi connection and I noticed I have the issue (same log errors ...).

I'll let you know if I can confirm this.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
