### ISSUE TITLE
Decide on how to support Notary servers for non-Hub registries

### ISSUE THREAD

**Issue by mtrmac** [moby/moby#19129]
At the moment Docker special-cases the `index.docker.io`/`notary.docker.io` hostname pair, leaving users of other registries to either manually use `$DOCKER_CONTENT_TRUST_SERVER` (which can only support one Notary at a time), or requiring registries to set up a separate front-end proxy / load balancer to serve both the registry and notary services at the same host name (see https://github.com/docker/notary/issues/398#issuecomment-168781526 ).

Assuming Notary becomes popular, various ISVs and company-private Notary servers will appear, and it will become necessary to support several Notary servers at the same time. So we should decide whether to support such scenarios:
-  By using a single host name for both the registry and notary? If so, it would be useful for the registry to support forwarding requests to the notary without a third-party front-end, or perhaps the other way around, or to support both services from a single executable.
- By having clients explicitly configure a host name for a notary corresponding with each registry, possibly including trust pinning configuration (https://github.com/docker/notary/issues/399 )? If so, Docker needs a configuration mechanism for this.
- By doing something else?

**Comment by thaJeztah** [comment]
ping @endophage

**Comment by LK4D4** [comment]
ping @endophage @thaJeztah

**Comment by endophage** [comment]
The first bulleted option is already supported and in use. The trust code will (and if it's not working, let us know) fall back and attempt to use the registry hostname. Notary traffic can then be proxied based on hostname by matching `/v2/{image name regex}/_trust/*`

We also intend to add support in the future to for the second bullet, permitting notary "GUN" prefixes to be mapped to specific trust servers.

**Comment by ruimarinho** [comment]
@endophage would that help me proxying traffic to `notary.docker.io` when building from a CI system where trusted data does not exist? I need to have `DOCKER_CONTENT_TRUST_SERVER` set to my private notary server, but that means building private images based on signed tags (e.g. `FROM alpine`) requires switching back and forth notary servers.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
