### ISSUE TITLE
Add a new document about debugging docker

### ISSUE THREAD

**Issue by jalateras** [moby/moby#1921]
I thought it may be useful to start a document about how to debug a docker binary once you've built it, The document would sit under the docs/soruces/contributing directory.

What do others think?

**Comment by pnasrat** [comment]
I'm back after lots of busy time and ready to make a start on this unless anyone else is working on

**Comment by npcode** [comment]
I am struggling to debug docker but I failed:

1. gdb - It raises [segfault](https://github.com/docker/docker/issues/14173).
2. godebug, delve - They require to rebuild docker binary by them instead of go compiler. I don't know how to do that.

It would be great if there is a document about how to debug docker!

**Comment by thaJeztah** [comment]
Slightly related; https://github.com/docker/docker/pull/21316

**Comment by npcode** [comment]
in docker-dev IRC channel, WeiZhang555 taught me how to debug docker by delve: Bulid docker by `DOCKER_DEBUG=1 make binary` then you can debug the binary.

**Comment by Ch3ck** [comment]
Hi @thaJeztah @justincormack  Is someone still working on this? I will like to know the status of this issue and what I could do to complete it.
Thanks,

**Comment by justincormack** [comment]
@Ch3ck I don't think so. Any sort of start would be helpful and can get people to review. It is a bit more complex now as there are multiple binaries, and eg people may need to debug `docker-containerd` instead.

**Comment by Ch3ck** [comment]
@justincormack Alright, any particular documentation or wikis I could look at to give me more info to work on this?

**Comment by justincormack** [comment]
@Ch3ck I don't know if there are, I suspect the information is scattered around all over the place unfortunately

**Comment by Ch3ck** [comment]
@thaJeztah @justincormack If you saw my post on the slack channel. I'm writing this document using the delve debugger. With the currently research I've done so far. GDB is not well suited to debug a large docker binaries. Delve seems to be the best choice. I don't know if this is ok.
