### ISSUE TITLE
apt-get install doesn't install latest docker, and installation instructions are long

### ISSUE THREAD

**Issue by samthebest** [moby/moby#19235]
I used `apt-get install docker.io` and I ended up with version 1.6, though 1.9 is the latest.  So I had a look at https://docs.docker.com/engine/installation/ubuntulinux/ and my face melted, so I googled a bit harder and found that all I actually need run is this:

```
curl -fsSL https://get.docker.com/ | sh
```

(edit: changed `wget` to `curl` because we use `curl` in all places now)

**Comment by HackToday** [comment]
hi @samthebest  I did not think instructions are long, the apt source configure ways are recommended by docker community, 

for wget -qO- https://get.docker.com/ | sh, it is script ways, it also did the same way as above (configure apt source, and install recommended package and install docker).

maybe @thaJeztah  or @jfrazelle  can give more comments about this

**Comment by samthebest** [comment]
@HackToday Thanks.  How about just adding something like:

"You can follow the below instructions to install, or run this command: `wget -qO- https://get.docker.com/ | sh`"

**Comment by thaJeztah** [comment]
Hm, looks like we actually do that on the other distros (e.g. on [CentOS](https://github.com/docker/docker/blob/9cf29be0ee0b19c25471c19c224f9af150beaf1e/docs/installation/centos.md#install))

> There are two ways to install Docker Engine. You can install using the yum package manager. Or you can use curl with the get.docker.com site. This second method runs an installation script which also installs via the yum package manager.

And this doc; https://github.com/docker/tutorials/blob/master/docs/linux/step_one.md#install-docker

So I think it would make sense to do the same for the ubuntu and debian pages

**Comment by HackToday** [comment]
yes, @thaJeztah   sounds OK

**Comment by longliqiang88** [comment]
#dibs

**Comment by LK4D4** [comment]
@thaJeztah There is still no such section and you're closed PR about it. So, this issue is yours :)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
