### ISSUE TITLE
docker complains about disk space even though it lacks memory

### ISSUE THREAD

**Issue by gotcha** [moby/moby#19299]
Description of problem:
While running `docker build` on a swarm cluster, I get the following error message even though the disks are mostly empty.

```
Error pulling image (2-onbuild) from docker.io/library/python, Untar re-exec error: exit status 1: output: write /usr/lib/python2.7/dist-packages/mercurial/cmdutil.py: no space left on device
```

If I give more RAM to the Virtualbox VM's, `docker build` succeeds more often.

I'd like to see a better error message that is explicit about not having enough RAM.

`docker version`:

```
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.5.1
     Git commit:   a34a1d5
     Built:        Sat Nov 21 00:48:57 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      swarm/1.0.1
     API version:  1.21
     Go version:   go1.5.2
     Git commit:   744e3a3
     Built:
     OS/Arch:      linux/amd64
```

`docker info`:

```
    Containers: 4
    Images: 3
     Role: primary
     Strategy: spread
     Filters: health, port, dependency, affinity, constraint
     Nodes: 3
     c0-master: 192.168.99.112:2376
      └ Status: Healthy
      └ Containers: 2
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 2.054 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
     c0-n0: 192.168.99.113:2376
      └ Status: Healthy
      └ Containers: 1
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 2.054 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
     c0-n1: 192.168.99.114:2376
      └ Status: Healthy
      └ Containers: 1
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 2.054 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-boot2docker, operatingsystem=Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015, provider=virtualbox, storagedriver=aufs
    CPUs: 3
    Total Memory: 6.161 GiB
    Name: c0-master
```

`uname -a`:

```
15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
- MacOSX 10.11.2
- VirtualBox Version 5.0.10 r104061
- docker-machine version 0.5.5, build

How reproducible:
Hard

Steps to Reproduce:
- Create machines for swarm cluster
  
  $ docker-machine create   -d virtualbox --virtualbox-memory "768"   --swarm --swarm-master --swarm-discovery="consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-store=consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-advertise=eth1:2376"   c0-master
  $ docker-machine create   -d virtualbox --virtualbox-memory "768"  --swarm --swarm-discovery="consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-store=consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-advertise=eth1:2376"   c0-n0
  $ docker-machine create   -d virtualbox --virtualbox-memory "768"  --swarm --swarm-discovery="consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-store=consul://$(docker-machine ip kv):8500/c0"   --engine-opt="cluster-advertise=eth1:2376"   c0-n1
- Make the following `Dockerfile`

```
FROM python:2
RUN pip install libzmq==15.2.0
```
- Build it in parallel under different tag names

```
$  eval "$(docker-machine env --swarm c0-master)"
$ docker build -t rep1 .
$ docker build -t rep2 .
$ docker build -t rep3 .
```

Actual Results:

nox space left on device like above

Expected Results:

A better error message that informs about not having enough memory rather than complaining about disk space.

Additional info:

I think that the bug only appears when each builds is built on different node, maybe putting too much pressure on VirtualBox.
As `swarm` does not allow to specify which node will be used to build an image, the bug is hard to reproduce as  in some cases, all paralell builds happen on the same node.

**Comment by cpuguy83** [comment]
hmm, this error is likely coming from the kernel directly and not translated from docker.

**Comment by HackToday** [comment]
@gotcha have some questions about this issue,  

"I think that the bug only appears when each builds is built on different node, maybe putting too much pressure on VirtualBox."

it seems strange, if all paralell  builds on same node, it seems can consume much memory for that node.

when on different nodes, each node would handle that. since each node have that same memory. it would success more often.

**Comment by gotcha** [comment]
@HackToday I did not read the code but my guess is that parallel builds on the same node share some process. for instance layers are downloaded only once.

**Comment by KamilKopaczyk** [comment]
I'm having the same symptoms, but with different environment.
_df -i_ and _df -h_ shows plenty of space and inodes. 
Although memory usage is high i didn't see it dropping below 200M free while doing _docker pull_.
Restarting docker daemon helped a little bit - previously it was failing when pulling very first layers.

Any ideas or suggestions?


Issue:
```
$ docker pull php:5.6-fpm
5.6-fpm: Pulling from library/php

efd26ecc9548: Already exists
a3ed95caeb02: Pull complete
589a9d9a7c64: Pull complete
4683f98d2423: Pull complete
d5f645469de1: Pull complete
890b0c19aae8: Extracting [==================================================>] 26.45 MB/26.45 MB
5f436ae8a9de: Download complete
bbcd14f3b9c3: Download complete
failed to register layer: Untar re-exec error: exit status 1: output: open /usr/src/php/ext/pcre/tests/bug69864.phpt: no space left on device
```

Info:
```
$ uname -r
3.16.0-4-amd64
```

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 1
```

```
$ free -lmh
             total       used       free     shared    buffers     cached
Mem:          7.8G       7.4G       489M       388M       7.2M       975M
Low:          7.8G       7.4G       489M
High:           0B         0B         0B
-/+ buffers/cache:       6.4G       1.4G
Swap:         1.0G       335M       702M
```

**Comment by LK4D4** [comment]
@cpuguy83 @tonistiigi I wonder if it was tmpdir in ram. WDYT?

**Comment by tonistiigi** [comment]
@LK4D4 It is strange though because builder should use `/var/lib/docker/tmp` as the temporary directory and that shouldn't be in ram unless the storage dir was specifically changed. And during pull the extraction of rootfs only happens directly to aufs mount and diff folders. It starting to work after removing containers seems to hint that the disks weren't actually that empty.

**Comment by LK4D4** [comment]
@tonistiigi however, it's somehow related to RAM. At least for the original report, because it states that it was okay after increasing VirtualBox memory. Maybe swapfile or whatever :/

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
