### ISSUE TITLE
More information on authentication failure

### ISSUE THREAD

**Issue by Licenser** [moby/moby#19306]
When the client authentication fails with the docker endpoint it just prints 'authentication failed' so that can have more then one reason, bad certificate, no certificate, wrong certificate. It would be helpful for debugging this situations  when  some information would be printed out like:
- no client certificate
- bad format
- certificate rejected

as the oath of finding out what the issue is can be very different in this cases.

Disclaimer: This ticket is born out of my stupidity naming the `cert.pam` `client.pam` and trying to debug signature issues for two days. Clearly user error but the error message is misleading or at least not very informative.

**Comment by LK4D4** [comment]
ping @thaJeztah 
Do you know if it's still worth to do?

**Comment by thaJeztah** [comment]
let me defer to @stevvooe @dmcgowan

**Comment by stevvooe** [comment]
@Licenser I agree that troubleshooting certificate issues can be confusing. Do you have an example of the confusing error message? These problems are lot easier to address if we enumerate the _exact_ failures causing confusion.

Otherwise, we'll have pontificate the possible failures and their resolutions, which may be boundless. 🐹

**Comment by Licenser** [comment]
Hey,
this has been so long ago I don't remember exactly to be honest :(.

I **think** the situation was that the certificate names were wrong (so there was no client certificate at all) and the error just said `authentication failed`.

I don't know the internals of this but my original thought was that "can't open the cert file", "can't parse/read the cert file" and "the server rejected the certificate" could print different error messages.

It sure won't cover 100% (or anything close to that) of the cases (SSL is a bottomless pit, I sadly know that too well :P), but they are some easy cases that would cover the kind of silly I (and probably other people too) tend to do when I don't got my morning coffee

**Comment by stevvooe** [comment]
@Licenser Agreed but I am not sure that this particular issue is actionable without a specific example. What would be the criteria for closing this issue?

**Comment by neersighted** [comment]
Closing as this is a UX issue on the CLI; please open a ticket on `docker/cli` if this is still an issue for you.
