### ISSUE TITLE
Docker restart policy

### ISSUE THREAD

**Issue by ybalt** [moby/moby#19307]
Is it possible to make restart policy works in such way:
- if restart caused by OOM, Segfault or other erros in container, it will be restarted
- if restart caused by reboot, it not restarted, with is helps in case need to run something before any containers starts, but after docker start?

**Comment by thaJeztah** [comment]
Docker 1.9 also added a `--restart unless-stopped` option; https://github.com/docker/docker/pull/15348 would that work for you?

Perhaps you can clarify your use-case?

**Comment by ybalt** [comment]
Slightly not. 

This option (unless-stopped) did not include case of accidentally reboot, so containers will be started, if it was not stopped before reboot. In some cases it not useful, as may be need to run something before ANY containers start.

Real example:

I'm using weave for multihost connection, service discovery and DNS. Weave launch when docker daemon started, but need to be run before any other containers to provide them ifaces/services/etc.

It can be done via startup scripts - it's ok. 

I'm just set --restart=no and manually up all containers after weave launch. But in this case I lost restarts on OOM/SegFault/other app errors.

If I set --restart=always, containers may start before weave and didn't use it.

If I set --restart=on-fail, containers started if status code is interpeted as error, reboot also include in this case.

If I set --restart=unless-stopped, containers started if it not be manually stopped (of course it not true for accidental reboot)

So, to save restart functionality, I imagine it may implemented by introducing new restart policy like

--restart=unless-reboot.

This restart policy same as on-fail, but skip restart if docker daemon runs this container first on boot. To detect that docker daemon was rebooted and container need to start manually, it may be good to generate and save some kind of random value every docker daemon start. This value (fingerprint) stored in docker daemon and change every daemon restart. Also, this fingerprint sets 
in container metadata for every container started manually (not via restart).
- If value in daemon not the same as in container, this container not be started automatically. We need to start it manually, and on manual restart fingerpring in container updated.
- If value in daemon the same as in container, thats mean container may be restared automatically, assuming docker evironment already prepared. 


Sorry for long read, but I tried to explain the feature I'm really need for my work.

**Comment by ybalt** [comment]
Or, as a variant, add to Docker daemon option like
--no-start
to prevent start any containers on daemon start.

But first variant is more flexible, of course. We may separate containers that may start always, may start only manually on boot/daemon restart.

The whole idea is to create env that can up from any state.If you know other ways, may be already exists, please let me know. I'll be very appreciated.

**Comment by cpuguy83** [comment]
@ybalt I'd be +1 to the `--no-start` proposal (with a different name), there is another proposal just for that.

**Comment by gdm85** [comment]
Related: #8821

**Comment by dontub** [comment]
I would also appreciate a restart policy that is like `on-failure`, but doesn't start containers on docker daemon (re)start.

**Comment by francislavoie** [comment]
I actually want the opposite as well, if possible. `unless-stopped`, but not restarting on errors (or with max-tries), or in other words only restarting on daemon restart but not on errors.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
