### ISSUE TITLE
1.10-rc1 docker run should not create container if network options are invalid

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#19418]
Related to https://github.com/docker/docker/issues/19417

Docker creates a container, even if the network options are invalid. For example;

``` bash
# docker run --ip=172.17.0.18 -itd --net=bridge busybox sh
14bed02fbc4c9901b4d562844ec3d03e7773259375a07037a2f4062ce0671b17
docker: Error response from daemon: User specified IP address is supported on user defined networks only.
```

The above instruction created a container, and apparently assigned an IP-address

(note that **the same** IP-address is used for each container that fails);

``` json
"Networks": {
    "bridge": {
        "IPAMConfig": {
            "IPv4Address": "172.17.0.18"
        },
        "Links": null,
        "Aliases": null,
        "NetworkID": "",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": ""
    }
}
```
#### Expected result

No container being created if the passed options are invalid

**Comment by wenchma** [comment]
root@e989dce7ba44:/go/src/github.com/docker/docker# docker run --ip=172.19.0.18 -itd --net=simple-network --name user01  busybox sh
    9ddb71eac97bcb6ee0ffb9a9471cf24756e885a5cc77b104fce582dabfac740e
    docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
    root@e989dce7ba44:/go/src/github.com/docker/docker# docker run --net=simple-network --ip=172.19.0.18 --name user02 busybox sh
    docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user
    root@e989dce7ba44:/go/src/github.com/docker/docker# docker ps -a
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                              PORTS                     NAMES
    1c42c7e75480        busybox             "sh"                     2 minutes ago       Created                                                    user02
    9ddb71eac97b        busybox             "sh"                     3 minutes ago       Created                                                    user01

The containers should not be created in above cases.

**Comment by wenchma** [comment]
.... I can take a look at this,  @thaJeztah

**Comment by thaJeztah** [comment]
Thanks @wenchma!

@mavenugo any pointers where / how you think it should be implemented?

**Comment by mavenugo** [comment]
@thaJeztah @wenchma most of the networking related logic is invoked in container start. all of the existing validations are done as part of that container start (not container create). If we have to get this done, we have to identify those validations that are applicable to container creation and move the logic appropriately. This can become an involved change and I would like to keep it out of 1.10.

**Comment by aboch** [comment]
@wenchma 
Regarding
> I think the containers should be created successfully in above cases.

The logic is that we accept a `--ip` only for network which were created with the `--subnet` option.
The reason for this is that there is no guarantee that after an host reboot the network's bridge interface is assigned the same IP address.
Imagine user has created many networks. 
The order with which they will be recreated after reboot is not guaranteed to be the same with which they were created.

**Comment by aboch** [comment]
@thaJeztah 
To add to @mavenugo 's point, given the container cannot anyway be restarted and no network resources are being held by the container (ip for ex), I think it is not that bad of an issue, the fix can come after 1.10. WDYT ?

**Comment by mavenugo** [comment]
@wenchma @thaJeztah the reason most of the validations are in the container start is that, we are doing these validations in the common code path for `docker run` and `docker network connect`.
`docker network connect` can be done both after a container create and start.

If we are moving this to the container create time, then we have to make sure `docker network connect` also reuse the same validation checks.

Since the validation checks clearly result in failure, I think we can get this done in 1.10.

**Comment by wenchma** [comment]
@aboch thanks for your explanation, got it `--ip` only works for `-subnet` specified.
If that, my above test cases should fail to create containers same as @thaJeztah reported this issue,
@mavenugo  I think at least  the validations should happen before  a container create and start.

**Comment by wenchma** [comment]
@thaJeztah  should we document the logic about `--ip` and `--subnet`  ?

**Comment by mavenugo** [comment]
@thaJeztah @wenchma since we haven't made any progress on this issue, I would recommend to remove this issue from 1.10. 
As explained above https://github.com/docker/docker/issues/19418#issuecomment-173305867, this is not a critical issue.

**Comment by LK4D4** [comment]
@mavenugo @aboch @sanimej still an issue?
