### ISSUE TITLE
AppArmor prevents java process from starting

### ISSUE THREAD

**Issue by fruboes** [moby/moby#19491]
Attached dockerfile installs and tries to start ambari-server inside kubuntu 14.04 based container. With apparmor  in enforce mode I get the following error:

```
$ docker build -t apparmortest .
(...)
$ docker run apparmortest
(...)
Waiting for server start.........
ERROR: Exiting with exit code -1. 
REASON: Ambari Server java process died with exitcode -1. Check /var/log/ambari-server/ambari-server.out for more information.
```

I cannot see anything useful in mentioned logfile. The problem seems to be apparmor related - after switching it to complain mode (sudo aa-complain /etc/apparmor.d/docker;  before that one specific line in /etc/apparmor.d/docker; needs to be commented out since it confuses aa-complain) ambari-server starts properly:

```
$ docker run apparmortest
(...)
Waiting for server start....................
Ambari Server 'start' completed successfully.
```

I'm using devicemapper in order to avoid any aufs+java related problems. Could you have a look on this? Should docker apparmor rules be altered or this is somehow expected (ie the ambari-server does something extra that it shouldnt)?

Docker file: [dockerfile.zip](https://github.com/docker/docker/files/97435/dockerfile.zip)

Standard info:

```
$ uname -a
Linux  3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


$ docker info
Containers: 28
Images: 48
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:4-148510495-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.812 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.6 GB
 Metadata Space Used: 6.697 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-43-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.54 GiB
Name: ----
ID: 5NCJ:KUJT:U2QP:S6WW:4S63:3JUX:EE3N:JHSI:JIEW:GVLX:ZSWS:5GI7
WARNING: No swap limit support

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
It's possible that Ambari server needs additional privileges, or a modified profile. I see that a popular ambari image on Docker Hub (https://hub.docker.com/r/hortonworks/ambari-server/) includes some shell scripts to run the server with the right options; https://github.com/sequenceiq/docker-ambari/blob/master/ambari-functions

**Comment by AkihiroSuda** [comment]
I assume this was resolved in recent releases
