### ISSUE TITLE
EXDIR when renaming non-empty directories on lower AUFS layers

### ISSUE THREAD

**Issue by jake-low** [moby/moby#19512]
Consider this simple example:

```
$ docker run -it centos:6 bash
[root@becb74d41dba /]# mkdir /foo && touch /foo/bar
[root@becb74d41dba /]# python 
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.rename('/foo', '/foo2')
>>>
```

What I've done is made a directory with a file in it, then used python to call the `rename` syscall on the directory. It succeeds. Note that both the directory and the file exist in the top AUFS layer, since they were created inside the running container.

Now consider a similar example, this time using the Dockerfile below.

```
FROM centos:6
RUN mkdir /foo && touch /foo/bar
```

If I build this Dockerfile and run a container from it, this happens:

```
$ docker run -it aufs-bug-test bash
[root@a445e45dea66 /]# python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.rename('/foo', '/foo2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 18] Invalid cross-device link
>>> 
```

Errno 18 is `EXDIR`, which means you've tried to do a `rename` from one filesystem to another. You'd see this error on a typical Linux system if you tried to rename a file into `/proc`, since `/proc` is a separate filesystem. Programs like `mv` are smart enough to catch this error and implement a copy-and-delete instead, so to reproduce you'll need to call `rename` directly, as I have above.

This error **only occurs** (as far as I can reproduce) when renaming non-empty directories, and only if the source directory was created in the Dockerfile (i.e. in an AUFS layer _beneath_ the container-runtime layer). It doesn't matter which layer in the Dockerfile creates the directory, or the file(s) inside it, and it doesn't matter where you create them on the filesystem.

I haven't tested this on images other than `centos:6`. I also haven't tested on storage drivers other than AUFS.

---

System information:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 34
Images: 85
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 153
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: JB5T:FIJH:K2TD:7C3L:4F7E:CKK6:IB5U:NICN:A4UC:ZYZH:R2B2:3OGA
Debug mode (server): true
 File Descriptors: 29
 Goroutines: 70
 System Time: 2016-01-20T20:43:21.844440295Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by HackToday** [comment]
yes, it could be reproduced,

**Comment by ZYNCMA** [comment]
Met same issue.
Look like bug of aufs.

**Comment by donaldguy** [comment]
This persists up through at least 1.11.1 - as stated its an AUFS bug more than a docker bug but it keeps biting me

**Comment by rovner** [comment]
The same issue on docker 1.12, host with ubuntu 16.04 and ovelay2 fs

**Comment by thaJeztah** [comment]
@rovner can you open a separate issue for that; if possible with steps to reproduce?

**Comment by rovner** [comment]
Sure, https://github.com/docker/docker/issues/25409

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
