### ISSUE TITLE
Docker API: archive does not untar file content, tar archive is owned by root

### ISSUE THREAD

**Issue by rteusner** [moby/moby#19545]
Description of problem:
Docker API: [archive in](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container) (post) does not untar the file content I want to place inside the docker container, tar file is owned by root (and sometimes by my user..).

Eventually I am doing something wrong with access rights?
Help is greatly appreciated. 

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 6
Images: 238
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 7.798 GiB
Name: vagrant-ubuntu-trusty-64
ID: 42J6:7X73:Q5LK:LVEV:KAMQ:SAYK:DH3D:KSTC:JQF7:HBSC:IOZR:44NA
WARNING: No swap limit support

`uname -a`:
Linux vagrant-ubuntu-trusty-64 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Vagrant on Virtualbox, physical is an OSX, but appears on other machines as well.

How reproducible:
Always. I am using the [swipely docker API gem](https://github.com/swipely/docker-api) for Ruby on Rails. See script below.

Steps to Reproduce:
1. Start up a docker container.
2. Access the container via an interactive ruby shell:

require 'docker'
container = Docker::Container.get('#yourID')
container.archive_in('/some/folder/', '/home/python/', overwrite: false)

archive_in is implemented [here, Line 250ff](https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb). Seems nothing wrong with the Ruby code for me. 
1. Check what happens on your docker container (I did this via: 'docker exec -it #yourID bash' and then having a look at the file system).

Depending on whether I used Binds in the container creation options, the still untar-ed archive belonged to root or python (the user I use inside my container).
If Binds were used on the target folder for my archive, it belonged to python, if I used another folder it belonged to root.

Actual Results:
A tar file owned by root.

Expected Results:
An unarchived file owned by my actual used user.

Additional info:

**Comment by unclejack** [comment]
Can you reproduce this using the `docker cli`?

**Comment by rteusner** [comment]
I could reproduce it partly.

When using Postman to interact with the REST interface, the tar gets unpacked properly. Files are however also owned by root afterwards (regardless where I place them). 
Is there any option to change/set the owner of the files via the API?

Concerning the situation that the archives are not unpacked when using the Ruby gem, I will open a ticket on their repo. Thanks for your help so far.

**Comment by unclejack** [comment]
@rteusner Support isn't provided for third party libraries interacting with the API, generally speaking. The issue is that there's no way to guarantee they're doing things the exact same way as the Docker CLI or that they've gone through the same testing.

**Comment by rteusner** [comment]
@unclejack I totally understand that and agree. 
My question with regards to the Docker CLI  / Remote API is, whether the files unpacked by the Docker Remote API always have to belong to root afterwards. The Docker Remote API is part of the CLI, right? Or does the question belong somewhere else?

I could not find more information in the [documentation](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container), however I located the (probably) respective part of the source [here](https://github.com/docker/docker/blob/master/daemon/archive.go) (I would have guessed it is under /api instead of /daemon, first, but found it in the second try). Is there some documentation with regards to unix user handling when using the Docker Remote API in general? 

Thanks in advance!

**Comment by unclejack** [comment]
@rteusner Last time I've checked, the owner was changed to root.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
