### ISSUE TITLE
Consul and log error

### ISSUE THREAD

**Issue by auzias** [moby/moby#19589]
Hi everyone.

Docker runs on a cluster on a few machines. The command for the daemon is as follow:
`docker daemon -H tcp://0.0.0.0:2375 --cluster-advertise eth0:2375 --cluster-store consul://127.0.0.1:8500`

About every 20 seconds the daemon, **whether or not consul is running**, appends in the logs:

> Jan 13 09:50:04 bugs20 docker[29356]: time="2016-01-13T09:50:04.203417359+01:00" level=error msg="Registering as \"192.168.196.20:2375\" in discovery failed: cannot set or renew session for ttl, unable to operate on sessions"
> Jan 13 09:50:19 bugs20 docker[29356]: time="2016-01-13T09:50:19.056980231+01:00" 
> level=error msg="discovery error: Unexpected watch error"

I can't get rid of these errors than generate log all days long while no accident are experienced during Swarm usage (consul is used for Swarm).

---
#### Environment details

**`docker version`**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
```

**`docker info`**

```
Containers: 68
Images: 12
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 148
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 47.25 GiB
Name: bugs20
ID: DVQZ:XBAT:IN4R:VLTP:2B4H:J4LX:4TDT:HXL7:U6QT:O3IQ:MB6E:XSRP
WARNING: No memory limit support
WARNING: No swap limit support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 192.168.196.20:2375
```

**`uname -a`**

```
Linux bugs20 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```

**`docker -H tcp://0.0.0.0:5732 -v #swarm-docker -v`**

```
Docker version 1.9.1, build a34a1d5
```

**`consul -v`**

```
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)
```

**Comment by HackToday** [comment]
Seems you first report it in docker swarm ?  It can move the issue faster if they diagnose it is docker issue

**Comment by vieux** [comment]
@abronan @mavenugo can you please take a look?

**Comment by mavenugo** [comment]
@auzias it depends on how you are running the consul server. Since you are seeing the error during discovery heartbeat with or without consul running, it suggests that the consul server is not properly configured. Also, I have observed in the past that Consul server is a bit sensitive when the ip-address changes across consul reboots. Hence, if you run consul as a container with ip-address changing across container restarts, then you will face such issues. Can you pls troubleshoot along these lines ?

**Comment by abronan** [comment]
Hi @auzias, can you please also clarify what version of **Consul** or **Swarm** you are using?

I see that the daemon points to a local Consul Agent or Server (`consul://127.0.0.1:8500`) when registering.

At a first glance, this looks like a configuration issue. My guess is that there is one docker daemon pointing to an old version of a Consul Agent or Server (minimum supported for the discovery is `0.5.1`) or a Consul Agent/Server that is faulty and not configured properly. If you find this faulty process and stop it, this will get rid of the log pollution you're seeing. You can then troubleshoot and restart the Consul Server alongside the docker daemon with the appropriate configuration.

Would be perfect if we can have more informations on your Consul setup and the versions though.

**Comment by auzias** [comment]
Thanks @vieux for the pings, thanks @mavenugo and @abronan for the pongs.

@mavenugo:
**Consul** do not run in a container and all **Consul** are usually rebooted when the **Consul** master changes. Usually it does not change unless I'm done with my what I'm doing, and next -few days after- the whole process of **Swarm**+**Consul** is re-deployed on (other) nodes of the cluster.


@abronan:
**Swarm** ad **Consul** versions are appended in the issue (see below too).
[The process I follow for the deploying is described on my websitel](https://www.auzias.net/en/docker-network-multihost).

The docker daemon are always running however the **Consul** master/members are running only when needed.

Note that the errors are present on nodes:
 - running `consul` without being a member nor a master.
 - running `consul` while being a member.
 - running `consul` while being the master.
 - **not** running `consul` at all.

----

##### Swarm and Consul version
**`docker -H tcp://0.0.0.0:5732 -v #swarm-docker -v `**
````
Docker version 1.9.1, build a34a1d5
````
**`consul -v`**
````
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)
````

**Comment by mavenugo** [comment]
@auzias when you use, `-bind=192.168.196.20 -client 192.168.196.20`, consul seems to listen only on `192.168.196.20` and not on localhost. Hence when starting the docker daemon you must use `--cluster-store=consul://192.168.196.20:8500` and not `127.0.0.1`.

**Comment by auzias** [comment]
I see, but then how can it work?
According to what you are saying it seems that when the `docker daemon` will try to register it won't be able as it will not successfully connect to the local `consul`, but it works so far. The only thing is that it produces error logs.

The previous answer has been updated. On a node running `consul` as a member the `docker daemon` will **not** produce error log!

**Comment by sam-thibault** [comment]
This feature has been deprecated and removed.  I will close this issue.
