### ISSUE TITLE
"rm -f" fails  on Windows files without write permission with "Operation not permitted"

### ISSUE THREAD

**Issue by mayfield2333** [moby/moby#19587]
Description of problem:

Attempts to forcibly remove (rm -f) a readonly file in a Centos container on Windows fails
Changing permission of file (chmod a+w file) solves the problem.
The problem doesn't occur using the same container on Linux host.

`docker version`: 1.9.1, build a34a1d5

`docker info`:
Containers: 2
Images: 26
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: 3I2B:OOM7:CI4Q:7N5Z:BBHA:Y4X5:7YT3:2Y46:KJJ6:3ZXC:DRKX:3JPS
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2016-01-22T14:43:26.738877663Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

`uname -a`:
- _QuickStart_: MINGW64_NT-10.0 Kevin-i5-HP 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
- _Centos container_: Linux a4111332fd19 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox on Windows: Version 5.0.12r104815

**How reproducible:**
Everytime

**Steps to Reproduce:**
1. Open the QuickStart Terminal, and run the docker container, mounting the current directory (HOME and PWD) to the container.
2. `MSYS_NO_PATHCONV=1 docker run -it --rm -v $HOME:/home/me -v $PWD/work -e MYUID=$(id -u) -e MYGID=$(id  -g) -e ME=$USERNAME kmayfiel/development-centos`
3. `echo test > file`
4. `chmod a-w file`
5. `rm -f file`

Actual Results:

> rm: cannot remove 'file': Operation not permitted

Expected Results:
_file removed without error_

Additional info:

**Comment by LK4D4** [comment]
Not sure if it's related to windows or aufs. At least it works on overlay2.
@thaJeztah could you try with aufs?

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
