### ISSUE TITLE
[1.10-rc1] daemon start up slow with a lot of containers

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#19664]
If you have over a hundred containers or so you really notice a slow down on startup.  It takes a while while printing messages like the following over and over again

```
DEBU[0011] Releasing addresses for endpoint r-nginx_nginx_325's interface on network bridge 
DEBU[0011] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.77) 
```

**Comment by ibuildthecloud** [comment]
Also these aren't containers with `--restart=always`, so on daemon start all of the 100+ containers would be stopped.

**Comment by cpuguy83** [comment]
@ibuildthecloud I saw this too.
I believe @LK4D4 and @mrjana are profiling this.

Note that you should only really see this after an ungraceful shutdown.
Also still slows down the actual shutdown process too, from what I can tell.

**Comment by ibuildthecloud** [comment]
@cpuguy83 Most likely an ungraceful shutdown.  I'll double check if this impacts shutdown.  I'm more of a `kill -9` type of person :)

**Comment by LK4D4** [comment]
Yes, on graceful shutdown you'll wait for this on shutdown instead :)

**Comment by ibuildthecloud** [comment]
@LK4D4 I'm actually not seeing this on graceful shutdown, by graceful shutdown I mean I do `CTRL+C` on the window running Docker.

**Comment by cpuguy83** [comment]
If the containers are running you should.

**Comment by ibuildthecloud** [comment]
@cpuguy83 I'll check again :)  maybe they aren't running.  But... regardless I see it on startup.  So fast shutdown, slow startup.

**Comment by ibuildthecloud** [comment]
@cpuguy83 Okay, I'm completely wrong about shutdown.  I'm doing `tee` and apparently if you do `CTRL+C` that is somehow the equivalent of a hard kill.  So I thought I was gracefully killing it, but not.

**Comment by thaJeztah** [comment]
@ibuildthecloud so this is only on a ungraceful shutdown?

**Comment by ibuildthecloud** [comment]
Yes this is only ungraceful shutdown.

**Comment by LK4D4** [comment]
@ibuildthecloud I believe this is still an issue. Could you confirm?
