### ISSUE TITLE
Unable to pull images in Windows Server 2016 TP4

### ISSUE THREAD

**Issue by follesoe** [moby/moby#19685]
Description of problem:
Unable to pull Docker Images in Windows Server 2016 TP4 running in VM on Azure

`docker version`:
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   59a341e
 Built:        Fri Nov 13 17:23:07 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   59a341e
 Built:        Fri Nov 13 17:23:07 UTC 2015
 OS/Arch:      windows/amd64

`docker info`:
Containers: 0
Images: 2
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 59a341e
 Default Isolation: process
Logging Driver: json-file
Kernel Version: 10.0 10586 (10586.0.amd64fre.th2_release.151029-1700)
Operating System: Windows Server 2016 Technical Preview 4
CPUs: 1
Total Memory: 3.5 GiB
Name: nnugdemo
ID: PZUR:4XNN:WNZZ:G37R:JRI5:3Y4M:LXFO:EUCV:XLTU:R2C6:STA6:QAEN
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 16
 System Time: 2016-01-25T21:55:02.9619991Z
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\Docker

`uname -a`:
NA

Environment details (AWS, VirtualBox, physical, etc.):
Windows Azure VM running Windows Server 2016 TP4

How reproducible:
Consistent on 25th January 2016

Steps to Reproduce:
1. docker search microsoft
2. docker pull microsoft/iis

Actual Results:
It does list the different images available when running `docker search microsoft`.
Running `docker pull microsoft/iis` outputs:

```
Using default tag: latest
Pulling repository docker.io/microsoft/iis
Error: image microsoft/iis:latest not found
```

Expected Results:
Expected it to download the microsoft/iis image.

Additional info:
Same error for all images.

**Comment by jhowardmsft** [comment]
That's not TP4 docker (should be build Nov 23 @ `18c9fe0`).https://get.docker.com/windows/tp4/docker.exe

**Comment by powersplay** [comment]
Correct.   I recall that Nov. 13th docker.exe had exactly this problem.

**Comment by follesoe** [comment]
@jhowardmsft It's set up using the template on Windows Azure, following the guide on https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/azure_setup

So maybe the Azure template needs updating? Or at least some documentation about how to update it after you've set up a VM. Is it as easy as replacing docker.exe in my VM?

**Comment by jhowardmsft** [comment]
I can let folks know who own the template. You should be able to stop the docker service through nssm stop docker or sc stop docker, copy the new binary and start the service.

**Comment by friism** [comment]
Paging @enderb-ms and @taylorb-microsoft

**Comment by powersplay** [comment]
This script should update your containerhost:  https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/live/windows-server-container-tools/Update-ContainerHost/Update-ContainerHost.ps1

**Comment by follesoe** [comment]
Thanks for the swift reply to my issue. I ran the script @powersplay posted - and now have the Nov 23 build installed, and ``docker pull microsoft/iis`` works just fine.

Thanks!

**Comment by colemickens** [comment]
If you happen to deploy a Windows Server TP4 VM in Azure, you can do this to get `docker pull`, etc working. It might seem obvious, but to those unfamiliar with PS, just figuring out how to acquire the update script can be a time suck.

```
wget https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/live/windows-server-container-tools/Update-ContainerHost/Update-ContainerHost.ps1 -OutFile Update-ContainerHost.ps1

./Update-ContainerHost.ps1
```

Note: You *might* need to add `-UseBasicParsing` to the `wget` invocation, but it seems like it's already doing it. (`Invoke-WebRequest` still gives the lovely error about IE being unavailable, but `wget` worked).

**Comment by rs38** [comment]
thank you. works fine. azure tp4 core provisioning is still using the old docker

**Comment by lfarnell** [comment]
I am still facing the same issue as @follesoe. I ran the script @powersplay posted, but i still get an error

Docker version:
```
>docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64
```
Docker info:

```
>docker info
Containers: 0
Images: 1
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 18c9fe0
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network:
Kernel Version: 10.0 10586 (10586.212.amd64fre.th2_release_sec.160328-1908)
Operating System: Windows Server 2016 Technical Preview 4
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 4 GiB
Name: WIN-1NU5L36K867
ID: L5XR:WQ6F:CT36:SXGH:UN6M:RT7S:LLTG:JZVY:2ZDV:P4EA:MWV2:VZVG
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 19
 System Time: 2016-04-22T11:35:59.3261599-07:00
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\docker
```

uname -a
NA

Environment details (AWS, VirtualBox, physical, etc.):
Windows Server 2016 TP4(GUI) running in VMWare workstation 9

How reproducible:
After windows updates and following along with dozens of different [blog posts](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/inplace_setup), nothing seems to work

Steps to Reproduce:
1. docker search microsoft
2. docker pull microsoft/iis

Actual Results:
It does list the different images available when running docker search microsoft.
Running docker pull microsoft/iis outputs:

```
>docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
6a182c7eba7e: Download complete
39b8f98ccaf1: Pulling fs layer
Pulling repository docker.io/microsoft/iis
Driver windowsfilter failed to create image rootfs 6a182c7eba7e87f917f4806f53b2a7827d2ff0c8a22d200706cd279025f830f5: Cannot create layer with missing parent 6801d964fda5b67eb36e005261c1529ec96974bb02dfad52ee249638a18a93d1: GetFileAttributesEx C:\ProgramData\docker\windowsfilter\6801d964fda5b67eb36e005261c1529ec96974bb02dfad52ee249638a18a93d1: The system cannot find the file specified.
Error: image microsoft/iis:latest not found
```

Expected Results:
Expected it to download the microsoft/iis image.

Additional info:
Same error for all images.

**Comment by StefanScherer** [comment]
@lfarnell It seems that your VM does not have the Docker base images installed. What does `docker images` say in your VM?

In my VM I can see that the `windowsservercore` image has the image id `6801d96...`

```
PS C:\Users\vagrant> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
windowsservercore   10.0.10586.0        6801d964fda5        5 months ago        0 B
nanoserver          10.0.10586.0        8572198a60f1        5 months ago        0 B
nanoserver          latest              8572198a60f1        5 months ago        0 B
```

If you have or images or only nanoserver image, just run `C:\Install-ContainerHost.ps1 -SkipDocker`. For my VM I also have to [call it twice](https://github.com/StefanScherer/packer-windows/blob/8c67ae31e86635ee825896ac1474f26baf6b5b66/scripts/install-docker.ps1#L111) to have both base images.

**Comment by lfarnell** [comment]
I just downloaded TP5 and followed the [new documentation](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment) and everything seems to be working now.  Still some minor errors which i just had to run the script again. Thanks again @StefanScherer for your help!

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
