### ISSUE TITLE
containers traffic and cgroup net_cls.classid not working

### ISSUE THREAD

**Issue by thechile** [moby/moby#19802]
Hi

I am having trouble getting docker container traffic to be tagged by the cgroup `net_cls.classid` and picked up by tc.

I am using VirtualBox 5.0.10 and the vbox guest interface is enp0s3

Here is an example of my testing.

```
# On the vbox guest

tc qdisc del dev enp0s3 root
tc qdisc add dev enp0s3 root handle 10: htb default 30
tc class add dev enp0s3 parent 10: classid 10:1 htb rate 80kbit burst 2k
tc filter add dev enp0s3 protocol all parent 10: prio 10 handle 1: cgroup
```

```
# In a container, ping google dns and leave running

docker run --rm -ti yikaus/alpine-bash /bin/bash
$ ping 8.8.8.8
```

```
# Back on vbox guest, add the classid to docker cgroup so in theory all containers in the docker net namespace should be tagged and picked up by the above tc filter rule.

/bin/echo 0x00100001 > /sys/fs/cgroup/net_cls,net_prio/docker/net_cls.classid
```

At this point no traffic is hitting the class. I'd expect the ping traffic to show.

```
tc -s -d class show dev enp0s3

class htb 10:1 root prio 0 quantum 1000 rate 80Kbit ceil 80Kbit linklayer ethernet burst 2Kb/1 mpu 0b overhead 0b cburst 1600b/1 mpu 0b overhead 0b level 0 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 0bit 0pps backlog 0b 0p requeues 0 
 lended: 0 borrowed: 0 giants: 0
 tokens: 3200000 ctokens: 2500000
```

But if i add the shell pid to the docker namespace and ping then the traffic shows in class.

```
/bin/echo $$ > /sys/fs/cgroup/net_cls,net_prio/docker/tasks
ping -c 4 8.8.8.8

tc -s -d class show dev enp0s3

class htb 10:1 root prio 0 quantum 1000 rate 80Kbit ceil 80Kbit linklayer ethernet burst 2Kb/1 mpu 0b overhead 0b cburst 1600b/1 mpu 0b overhead 0b level 0 
 Sent 392 bytes 4 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 0bit 0pps backlog 0b 0p requeues 0 
 lended: 4 borrowed: 0 giants: 0
 tokens: 3046875 ctokens: 2346875
```

So it seems that for some reason the container traffic is going AWOL somewhere ? 

Am i missing something ?

Thanks

**Comment by thechile** [comment]
I forgot the version and info output.. Will update tomorrow when in office but the vbox guest is Ubuntu 15.10 with all updates applied and docker is 1.10.0-dev

**Comment by thechile** [comment]
```
docker version
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7aafa76
 Built:        Sun Jan 24 14:05:29 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7aafa76
 Built:        Sun Jan 24 14:05:29 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

 ```
docker info
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 4
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.9 MiB
Name: scott-VirtualBox
ID: 6AXB:LAJA:MB74:ICY6:WPZ7:2Z7B:ICX6:7BXX:44OI:X774:LNLZ:POL7
Experimental: true
```

**Comment by thaJeztah** [comment]
ping @mrjana perhaps you can answer this one?

**Comment by thechile** [comment]
just to say that i don't think this is docker specific.. I've tested the same logic with nspawn and lxc and no type of container seems to have its traffic tagged with the cgroup classid. Maybe this is a kernel bug but not sure how to confirm.

My understanding is that when you add a PID to the cgroup tasks file that it and all child processes with inherit the net_cls_classid and have all traffic tagged. The code for this in kernel was in `core/net/sock.c` but was moved into own file in 3.14 `net/core/netclassid_cgroup.c`. Maybe within the context of a container the way socket is identified as a member of a cgroup and tagged is broken ?

**Comment by thechile** [comment]
i think this is due to the network namespace, so the skb marks are relevant only within the containers associated namespace. 

There was some more info on this here http://lists.linuxfoundation.org/pipermail/containers/2014-January/033848.html which i think would have restored the classid as the traffic translated from one namespace to another but it was never accepted into kernel.

**Comment by LK4D4** [comment]
ping @mavenugo @mrjana @aboch @sanimej

**Comment by Rid** [comment]
@thechile did you find any work around for this? or test the kernel patch from http://lists.linuxfoundation.org/pipermail/containers/2014-January/033848.html ?

**Comment by thechile** [comment]
no, after much reading i decided that what i was trying was not the correct approach. Namespaces are there for isolation so traffic tagged in that namespace wasn't escaping to the host and being seen by tc tooling. Makes sense i guess if you think multi-tenant environments etc.. 

I moved on to other projects but from what i can remember i ended up getting what i wanted by manipulating the actual packets with info that i could later use on host with tc. Like ToS field which won't be fiddled with or dropped as it goes from container to host. Not as nice a solution though. 

If anyone knows more recent methods maybe via later kernel please tell.

**Comment by akerouanton** [comment]
As there's presumably not much we can do on our side, I'll close this issue.
