### ISSUE TITLE
Can't remove files on an overlay filesystem inside a container

### ISSUE THREAD

**Issue by semekh** [moby/moby#19992]
Description of problem:
Although it is possible to mount `overlay` filesystem(s) inside a container with `--privileged`, it is not possible to remove any files on the resulting mountpoint.

`docker version`: 

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 15:43:56 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 15:43:56 UTC 2016
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 2
Images: 110
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-3-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 15.59 GiB
Name: scarla
ID: JPTO:REHK:YKIJ:B6RM:3CKK:MWZI:VIPE:DDPX:KKC3:4CTD:S3HL:VQWS
```

`uname -a`:

```
Linux scarla 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Thinkpad Edge 520

How reproducible: Always

Steps to Reproduce:
1. Run:

```
docker run --rm --privileged debian:jessie sh -c "mkdir /lower /upper /work /res; touch /lower/hello; mount -t overlay overlay -o lowerdir=/lower/,upperdir=/upper/,workdir=/work/ /res; rm /res/hello"
```

Actual Results:
The output is `rm: cannot remove '/res/hello': Operation not permitted`

Expected Results:
The file should be successfully removed without any errors.

Additional info:

**Comment by dmcgowan** [comment]
Able to reproduce with just attempting to rm from an overlay within overlay. 

Script to reproduce
```
#!/bin/sh

mkdir upper lower work merged
touch lower/test1
mount -t overlay overlay -olowerdir=lower,upperdir=upper,workdir=work merged

mkdir merged/lower merged/upper merged/work merged/merged
touch merged/lower/test2
touch merged/lower/test3
mount -t overlay overlay -olowerdir=merged/lower,upperdir=merged/upper,workdir=merged/work merged/merged

chmod 640 merged/merged/test3
chown 1:1 merged/merged/test3
touch merged/merged/test4
rm merged/merged/test2
```

When running the script the last command `rm merged/merged/test2` fails with the same message `rm: cannot remove ‘merged/merged/test2’: Operation not permitted`. This is a limitation in the kernel and not in the storage driver so also added the kernel flag. My kernel version is `4.4.8-300.fc23.x86_64`.

**Comment by sam-thibault** [comment]
This is an old issue, and the legacy overlay driver has now been deprecated.  I will close this.
