### ISSUE TITLE
External volumes specified during run may not be consistently handled

### ISSUE THREAD

**Issue by clintkitson** [moby/moby#20176]
ping @cpuguy83 

The feature for using the external volume information from a platform during the `volume ls` command is introducing a new challenge for consistency.  At a high level, you cannot run `docker run -ti -v data4-newvol3:/yes busybox` across Docker container hosts, and expect the same behavior or response.

Example #1
If I issue a `docker run -ti -v data4-newvol3:/yes busybox` command after `docker rm -f $(docker ps -qa)` and `service docker restart`, then the behavior will be to create a new volume locally.

If I start from a clean docker start as before, but do a `docker volume ls` then the `data4-newvol3` is consumed from the volume plugin.

Note: Always specifying a volume driver avoids the problem.  Doing a List() internally before a volume driver/plugin is chosen could help remedy this.  But the List() operation would need to be lightweight if serving as a blocking call before any operation.

Example #2
If I have a more complex environment with multiple storage plugins attached to docker and I run through a similar scenario then it is even more problematic.

With a clean docker start, `docker run -ti -v vol-platform1:/vol1 -v vol-platform2:/vol2 busybox` will again create local volumes.  

Another variation of this would be to assume that maybe a volume was created through `docker volume create --driver=platform1 --name=vol-platform1`.  A `docker run -ti --volume-driver=platform2 -v vol-platform1:/vol3 -v vol-platform2:/vol4` will implicitly create a new volume for `vol-platform2` on `platform2` and will work as expect.  But take the same command to a second host that does not know about `vol-platform1` yet.  The same command will yield a volume of `vol-platform2` being created on `platform1`.

Example #3
Multiple plugins are configured on all Docker hosts.  If I have an overlapping volume name across storage platforms then it may be random which volume is recognized on which platform.

Note:  A deterministic capability here where plugin responses are returned in some type of priority order (by plugin name possibly) would be helpful.  This would be stated through documentation to say a best practice is to name plugins appropriately across hosts.  It would be implemented possibly through just reporting back volumes in alphabetical order from the driver.

**Comment by cpuguy83** [comment]
1 and 2 seem simple enough to resolve by checking all the available volume drivers for a volume with the given name.

3, this is user discipline. We can provide a better experience here by having some distributed state for volumes, but this is a much more difficult problem to get right.

**Comment by clintonskitson** [comment]
Yes.  On #3 a simple approach prior to that would be to just ensure deterministic behavior based on common confiugration.  For example, reviews driver by alphabetical listing versus random.

**Comment by clintonskitson** [comment]
For #2 if the uniqueness of volumes can be respected across storage platforms then this would work.

**Comment by clintonskitson** [comment]
@cpuguy83 Re #3 here is a practical example.  I have REX-Ray using profiles and advertising multiple volume endpoints as vb2 and vb3 (so same volumes coming through).  For volumes not associated to containers or known yet, an `inspect` after a docker restart will yield a different volume driver responding.  

I believe the biggest problem here is going to be with `swarm` in this use case.

```
dicey1:docker clintonkitson$ docker volume inspect newvol2001
[
    {
        "Name": "newvol2001",
        "Driver": "vb2",
        "Mountpoint": ""
    }
]
dicey1:docker clintonkitson$ docker-machine ssh testing2 "sudo /etc/init.d/docker restart"
Need TLS certs for testing2,127.0.0.1,10.0.2.15,192.168.99.105
-------------------
dicey1:docker clintonkitson$ docker volume inspect newvol2001
[
    {
        "Name": "newvol2001",
        "Driver": "vb3",
        "Mountpoint": ""
    }
]
```

**Comment by thaJeztah** [comment]
I see https://github.com/docker/docker/issues/20198 is linked to this one; is this resolved, or are more changes needed? (Didn't read through the whole description/discussion, just checking)

**Comment by LK4D4** [comment]
@cpuguy83 was this fixed? at least partially?

**Comment by cpuguy83** [comment]
A distributed store for volumes is not there yet.

**Comment by thaJeztah** [comment]
Let me close this as it went stale, but support for CSI was added for swarm services, as well as (experimental) support for CDI, which can solve some other cases
