### ISSUE TITLE
1.10 docker daemon high cpu usage

### ISSUE THREAD

**Issue by clkao** [moby/moby#20185]
Although there's no running containers and this host should have done the image migration already, the daemon is in high load: 

```
root       1074 30.1  0.3 7409156 104624 ?      Ssl  Feb08 697:50 /usr/bin/docker daemon
```

restarting the daemon seems to bring it back to normal:

```
root      64027  0.1  0.1 978960 43112 ?        Ssl  04:13   0:00 /usr/bin/docker daemon
```

Is there anything that should be used to diagnose what's happening? strace is showing futex wait probably because everything is happening in threads.

ec2 c4.4xlarge instance: `Linux ip-10-0-0-4 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

docker info:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 230
Server Version: 1.10.0
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-49-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.44 GiB
Name: ip-10-0-0-4
ID: WQ5A:YSST:Q7BM:WDJV:EDRE:YCBF:J2BS:3OYK:Z7DX:U4JS:WHWD:DOUN
Username: _______
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Is this the first time starting docker 1.10 after upgrading? Because I suspect this is the migration step to content-addressable storage, as explained in the changelog; https://github.com/docker/docker/releases/tag/v1.10.0, and the wiki; https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by clkao** [comment]
No, this box shoud have done migration (through several 1.10 rc releases upgrades)

**Comment by thaJeztah** [comment]
Alright, strange. Anything useful in the daemon logs? Could you try enabling debug mode (add `-D` to the daemon options), and see if the logs show anything useful.

Also, wondering if apparmor could be an issue here; we've had issues with apparmor not working as expected on Ubuntu 14.04 in RC1, so we removed the apparmor profile in RC2

**Comment by timothyparez** [comment]
Experiencing the exact same thing here. Disabled all containers from starting, still a very high CPU usage as soon as the system starts and commands such as `docker ps` do not respond.

**Comment by thaJeztah** [comment]
@timothyparez could you also post the output of `docker version` and `docker info` for your setup? Also, have you had docker 1.10.0-RC1 installed before upgrading to docker 1.10.0?

**Comment by timothyparez** [comment]
`docker version` and `docker info` simply sit there returning nothing forever.
I came from 1.9 directly and installed the latest 2 days ago.

**Comment by thaJeztah** [comment]
@timothyparez did it finish the content-addressable migration process?

**Comment by timothyparez** [comment]
Yes it did. Now after about half an hour the CPU usage went down and I can get the following

```
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

```
```
docker info
Containers: 335732
 Running: 0
 Paused: 0
 Stopped: 335732
Images: 71
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 702065
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51 GiB
Name: NIIP-APPSERVER
ID: CTR5:UC6D:DFZ7:5CIK:ZDDX:BNVW:23MV:VUF6:5WVB:U5FA:E3LD:NMRI
WARNING: No swap limit support
```

However, I was able to achieve the same yesterday on the same machine with the same version.
I will issue a full reboot now and see if it occurs again

**Comment by timothyparez** [comment]
Sure enough, after a reboot the CPU usage is up again and none of the docker commands are responding. I think in half an hour or so it will go back to normal CPU usage and then those commands will work again.

**Comment by thaJeztah** [comment]
Really strange, and haven't seen that before. Anything useful in the docker daemon logs, `/var/log/syslog` or `/var/log/dmesg` ?

**Comment by timothyparez** [comment]
This is the output in syslog containing docker since the last reboot

`Feb 11 20:01:49 localhost kernel: [  925.596855] aufs au_opts_parse:1155:docker[4305]: unknown option dirperm1
Feb 11 20:31:05 localhost kernel: [  328.227224] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
Feb 11 20:31:05 localhost kernel: [  328.334722] type=1400 audit(1455193865.684:49): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="docker-default" pid=2652 comm="apparmor_parser"
Feb 11 20:31:07 localhost ntpd[2163]: Listen normally on 6 docker0 172.17.0.1 UDP 123
`
Nothing interesting in dmesg.

Another strange this is that while I can run `docker info`  `docker version` and `docker ps`,  
running `docker ps -a` just causes it to wait forever again.

**Comment by timothyparez** [comment]
I let it run for a while and it completed. Apparently I have thousands of exited containers,  
that might explain a few things and it might be unrelated to the issue posted by the OP.

**Comment by thaJeztah** [comment]
Ah, right; actually that could be related to this change in 1.10; https://github.com/docker/docker/pull/16032 if there's so many containers, possibly constructing the links/relations could take a while

ping @cpuguy83 wdyt?

**Comment by timothyparez** [comment]
So after deleting all those containers (which took the better part of an hour, so must have been thousands) everything is back to normal. Which means I kinda hijacked this issue, since the OP's issue is probably unrelated to mine. Anything I should do about that?

**Comment by cpuguy83** [comment]
@thaJeztah Not likely. The actual operations are quite fast.

**Comment by clkao** [comment]
I am seeing this happening reliable after a few hundreds of container launches (mostly via run --rm).  Is it possible that there are thread leaks?

When there's no container left running:

    root       1066 23.6  0.4 11181264 132900 ?     Ssl  13:43  19:26 /usr/bin/docker daemon -D

However there are 329 threads:

    % ps -eLF |grep $(cat /var/run/docker.pid) | grep daemon | wc
        329    4935   34216

If I restart the daemon it looks a lot better:

    root      23192  3.1  0.1 986656 40204 ?        Ssl  15:05   0:00 /usr/bin/docker daemon -D
    ps -eLF |grep $(cat /var/run/docker.pid) | grep daemon | wc
         22     330    2288

**Comment by thaJeztah** [comment]
@clkao are all your nodes running with btrfs? wondering if there's something graph-driver related in your setup. What does `ps -auxf` give, no other processes below the docker daemon?

**Comment by clkao** [comment]
@thaJeztah  Yes it's all btrfs, and there are no other processes below the daemon (but lots associated with ps -eLF)

**Comment by clkao** [comment]
This is still happening on 1.10.2.  I can now more reliably trigger the cpu spin.  But there's nothing interesting in the daemon debug output.  I am trying to see if there's a minimum reproducible case.

Meanwhile Is there any recommended way to trace what's going on?

**Comment by vdemeester** [comment]
@clkao You seems to have a lot of images (230 layers) and I guess you might have some volumes too (maybe older ones too).

Could you list the current docker volumes (`docker volume list`) and also list the BTRFS subvolumes (https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume :angel:). By experience (ran docker on btrfs for a while on my laptop), the more you have subvolume in BTRFS, the slower it gets.

**Comment by clkao** [comment]
@vdemeester There are 45 actual images, the others are layers referenced by them I believe. There are about 350 subvolumes from `btrfs subvolume list`

`docker volume list` shows about 2000 volumes.  Mostly uuid names - not explicitly created intentionally (could `docker run --rm` not be cleaning up volumes?).  There are about 3 volumes that are intentionally created.

**Comment by atedja** [comment]
I am also seeing this on my Xubuntu 14.04.5 LTS, running Docker 1.12

```
$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 397
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-252:0-3938484-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 15.77 GB
 Data Space Total: 107.4 GB
 Data Space Available: 30.52 GB
 Metadata Space Used: 23.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.124 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.2-031302-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.714 GiB
Name: mybox
ID: 6IPB:NF55:4RQ2:JC62:ZAWK:3KLX:EQCE:OUTR:JLOR:SIHI:AJ2D:TR7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

CPU was high across all 8 cores.  After a minute, it's cooling down, but computer still slow.  Now, I regretted upgrading :grin:

**Comment by thaJeztah** [comment]
@atedja 

> CPU was high across all 8 cores. After a minute, it's cooling down, but computer still slow

What version did you upgrade from? Was this a version older than 1.10? What process is consuming CPU? Your `docker info` output says there's no containers running; could it be something else on the host?

In general; it looks like you're running with the devicemapper graph driver (and on loopback devices); this is known to consume a lot of resources, and be slow (also see the warning that's printed). Since you're on (X)Ubuntu, I'd recommend trying aufs, which is the default, but requires the linux-image-extra package to be installed (see [the documentation](https://docs.docker.com/engine/installation/linux/ubuntulinux/)).

**Comment by atedja** [comment]
I was upgrading from 1.7.  A clean installation of Docker 1.12 on a clean Ubuntu 14.04 does not seem to have this problem.  I also used auf as the storage driver rather than the devicemapper.  So it's possible there were some leftover junks from the old docker installation.

**Comment by cpuguy83** [comment]
@atedja This is expected as from docker 1.10+ docker has to go through all the images and migrate them to the content addressable store. More details here: https://docs.docker.com/engine/migration/

**Comment by calaniz** [comment]
@thaJeztah once the images have been content migrated, does the docker daemon on every restart check image migration again?  Anyway to disable that behavior?  Seems as though this check is causing long delays.  The docker daemon isn't ready till after this step.

**Comment by cpuguy83** [comment]
@calaniz It's only run once per image.
If you enable debug logging on the daemon you'll see detailed information about what it's working on.

**Comment by cpuguy83** [comment]
You can also run the migrator separately from the daemon.

**Comment by calaniz** [comment]
@cpuguy83 I've been through the migration.  I'm just pointing out that post migration, docker versions greater than v1.10.0 may be checking images for any migration steps necessary by default.  Even if no migration is required.  I believe this is causing a long delay in the docker daemon starting for users with lots of images.

I'm running in Google Cloud and in my development cluster, with 1 TB+ persistent disks that are magnetic, I'm seeing delays of 30 minutes before the docker daemon is ready on every restart.  It only started happening post v1.10 I believe.

**Comment by thaJeztah** [comment]
@calaniz upon restart, the migration process should only *check* each image if it's already migrated (by checking if a migration file is present, see [migrate/v1/migratev1.go#L144](https://github.com/docker/docker/blob/0b67f4c8951bccfecc8bafba66e7248309fb0c7c/migrate/v1/migratev1.go#L144)) 30 minutes sounds like a _very_ long time for that; how many images and containers are present on those hosts? If this is still an issue, perhaps it's better to open a separate feature request for an option to override the migration check

**Comment by calaniz** [comment]
@thaJeztah so we'd have to walk the /var/lib/docker/graph directory and stat that file for every directory entry?  

I've currently got 5812 directories, or 5812 .migration-diffid files to check.

**Comment by calaniz** [comment]
if it helps any

docker info gives

Containers: 3134
 Running: 25
 Paused: 0
 Stopped: 3109
Images: 5371
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.1-coreos
Operating System: CoreOS 1153.4.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.46 GiB
Name: <redacted>
ID: W6FK:AXKR:TMWQ:CBNI:77MF:W6EJ:IKSL:JQG4:FM6S:I5PE:SKDD:GRHI
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

**Comment by anonymuse** [comment]
For a quick fix while this is worked out, [do this](https://github.com/docker/for-mac/issues/82#issuecomment-256733511):

`$ sudo pkill docker`

**Comment by Lewiscowles1986** [comment]
I just had this on xenial. Pulled the network, closed a few processes and top showed docker-daemon using >200% CPU (it's in that mode where each core counts as 100%)

latest docker-ce from official docker repo's. I have a firewall which is up and not reporting any problems in logs, the problem persisted even after wifi disconnect. I've no idea what is causing but docker is the reported process from `top`.

Other notes are that the nvidia graphics card after killing the docker server has a lot of compositing issues.

**Comment by shiquanwang** [comment]
I have this same issue today. Ubuntu 16.04

```
~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 89623f28b87a6004d4b785663257362d1658a729)
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.33GiB
Name: shiquan-dl
ID: B7EX:LJZE:XPUM:BFQT:LF3P:2MN5:5RA2:BFWS:KLOF:Y6QC:POU6:REZF
Docker Root Dir: /media/data2/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Use `top` to check shows:
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
2322 root      20   0 1420204  34724  11300 S 269.8  0.1  10556:17 dockerd
```

**Comment by cpuguy83** [comment]
@shiquanwang @Lewiscowles1986 Almost certainly this is a different issue.
Can you open a new one with more details?

Thanks!

Closing this because it is a known problem due to migration of old images to content addressable storage, there was no way around it, and there was also a migration script that could be run separately  as was convenient prior to upgrades to alleviate that pain.
