### ISSUE TITLE
Ubuntu/Debian - connection resets inside container

### ISSUE THREAD

**Issue by normalser** [moby/moby#20220]
Inside container when `npm` tries to install a lot of packages for the project then `ECONNRESET` keeps happening and it fails the installation.

```
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 17
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.71 GiB
Name: eb.lcl
ID: HML4:NII7:MUTU:UD7X:T7XK:K4JS:WI7W:SS5J:H6KA:PMWS:OLPG:J4JJ
Labels:
 provider=generic
```

Environment: `Physical (MacBook Pro 8,2)`
Tried with fresh installs of: `Ubuntu 15.10, Ubuntu 14.04, Ubuntu 12.04, Debian 8.3 (all failed)`
Tried with fresh install of: `CentOS 7 (worked fine)`
## Steps to reproduce the issue:
1. Create Docker file with:

```
FROM node:4.3


RUN echo '{\
  "name": "test",\
  "version": "0.0.0",\
  "private": true,\
  "scripts": {\
    "start": "node ./bin/www"\
  },\
  "dependencies": {\
    "archiver": "^0.20.0",\
    "basic-auth": "^1.0.3",\
    "bluebird": "^3.0.2",\
    "body-parser": "~1.13.2",\
    "bytes": "^2.1.0",\
    "connect-session-sequelize": "^2.3.1",\
    "cookie-parser": "^1.3.5",\
    "debug": "^2.2.0",\
    "depd": "^1.1.0",\
    "destroy": "^1.0.3",\
    "escape-html": "^1.0.3",\
    "etag": "^1.7.0",\
    "express": "~4.13.1",\
    "express-session": "^1.12.1",\
    "forever": "^0.15.1",\
    "forever-monitor": "^1.7.0",\
    "formidable": "^1.0.17",\
    "fresh": "^0.3.0",\
    "gcloud": "^0.24.1",\
    "googleapis": "^2.1.6",\
    "hashids": "^1.0.2",\
    "http-errors": "^1.3.1",\
    "i18next": "^1.10.5",\
    "jade": "~1.11.0",\
    "lodash": "^3.10.1",\
    "mailgun-js": "^0.7.7",\
    "mime": "^1.3.4",\
    "mkdirp": "^0.5.1",\
    "moment": "^2.11.2",\
    "morgan": "~1.6.1",\
    "ms": "^0.7.1",\
    "multer": "^1.1.0",\
    "mysql": "^2.9.0",\
    "node-sass-middleware": "0.8.0",\
    "node-uuid": "^1.4.3",\
    "on-finished": "^2.3.0",\
    "range-parser": "^1.0.3",\
    "request": "^2.67.0",\
    "rimraf": "^2.5.1",\
    "sanitize-filename": "^1.4.5",\
    "selenium-webdriver": "^2.48.2",\
    "send": "^0.13.0",\
    "sequelize": "^3.13.0",\
    "sequelize-json": "^2.1.2",\
    "serve-favicon": "~2.3.0",\
    "shortid": "^2.2.4",\
    "socket.io": "^1.3.7",\
    "speakingurl": "^7.0.0",\
    "statuses": "^1.2.1",\
    "stream-stream": "^1.2.6",\
    "stream-throttle": "^0.1.3",\
    "throttle": "^1.0.3",\
    "tmp": "0.0.28",\
    "validator": "^4.2.1",\
    "webdriverio": "^3.3.0"\
  },\
  "devDependencies": {\
    "gulp": "^3.9.0",\
    "gulp-uglify": "^1.4.2"\
  }\
}\
' > package.json

```
1. `docker build -t test .`
2. `docker run -it --rm test bash`
3. `npm install`
## Results received:

Npm starts to install a lot of libraries.
Pretty much every time it will fail with ECONNRESET after some time (which will cause libraries that are being downloaded interrupted and corrupted), so npm returns:

```
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
```

```
npm ERR! shasum check failed for /tmp/npm-12-7ac4318c/registry.npmjs.org/prettyjson/-/prettyjson-1.1.3.tgz
npm ERR! Expected: d0787f732c9c3a566f4165fa4f1176fd67e6b263
npm ERR! Actual:   f7f9ec6b39ad70792a7b8538f349190b942478d7
npm ERR! From:     https://registry.npmjs.org/prettyjson/-/prettyjson-1.1.3.tgz
```
## Describe the results you expected:

Expected result is for npm to install packages successfully
## Provide additional info you think is important:

I tried multiple scenarios to make sure it's not an issue with npm / my hardware:
1. I did fresh installs of Ubuntu 15.10, Ubuntu 14.04, Ubuntu 12.04, Debian 8.3 (i followed https://docs.docker.com/engine/installation/linux/ubuntulinux/ for Ubuntus)
1a. It always failed in docker with these errors
1b. If I did run locally (without docker) - with exact node / npm - then it worked fine
1c. I did install virtualbox and started ubuntu/wily64 in vagrant and it worked fine outside of docker and inside of docker
1d. I made sure to connect my hardware to modem directly (to exclude issue with router)
1e. I took the HDD and put to other (some HP laptop) and exactly the same issue existed in docker
2. I installed Centos 7 and then docker and it worked fine

One more note that if I set npm to use http (not https): `npm config set registry http://registry.npmjs.org/` then it seems like it gets a little bit further - and I managed to finish the install couple of times, but ECONNRESETs were happening most of the time

**Comment by gazzer82** [comment]
Did you ever manage to resolve this, I'm seeing the same issue on my docker builds?

**Comment by wallverb** [comment]
Unfortunately I did not @gazzer82  - I just stopped using Docker. Not sure if Docker has some networking problems with Ubuntu but I had another issue with Ubuntu @ Azure - I did setup swarm, one container was MariaDB master, another container (different machine) was MariaDB slave and as soon as I tried to import huge mysql dump on master - it would blow entire networking on Master - the only way was to reboot the machine. It was only happening in the Docker and only on Ubuntu. I installed CentOS and everything was fine.

**Comment by gazzer82** [comment]
This seems to be an issue that crops up for some people, not others, very odd. Interestingly if i use a container to do the build, and pass that container --net=host this problem goes away, so it definitely seems to be related to the interaction of dockers NAT and my network, but it's very off that builds on my Ubuntu and OSX machines, on the same network, build without issues. Properly stumped on this one . . .

**Comment by wallverb** [comment]
Yea, you are right, `--net=host` does not have this problem, so it's something with default `--host=bridge`. Docker team - any help with this? Thanks

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  Possibly related to:
-  https://github.com/moby/libnetwork/issues/1090
