### ISSUE TITLE
Linking to a container running codenvy/che fails with error "argument list too long."

### ISSUE THREAD

**Issue by gissehel** [moby/moby#20274]
When I try to link to a container running image `codenvy/che`, I end up with the error `System error: argument list too long.`
# BUG REPORT INFORMATION
## Environment where the problem was noticed

docker version:

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 17
 Running: 3
 Paused: 0
 Stopped: 14
Images: 61
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.59 GiB
Name: [removed]
ID: KU57:P757:EDQZ:P4Q2:6SF2:MLXX:WY2K:TW62:CX7C:EVHS:DORS:K6ZH
WARNING: No swap limit support
```
## Steps to reproduce the issue

```
$ sudo docker run --detach --volume "/run/docker.sock:/var/run/docker.sock:rw" --name che codenvy/che
2316bb55fff91474959a2de99237b90d8ed00d4117f7ae2eeca46c7e5180092b
$ sudo docker run -ti --link che:slot ubuntu /bin/bash
```
## Actual results

_long wait (probably some timeout)_

```
argument list too long
docker: Error response from daemon: Cannot start container 81ccaf9711825c1d30bf4eba6a332d53ea27509c42a8f12c0f2691d608e4ce22: [9] System error: argument list too long.
```
## Expected results

```
root@81ccaf971182:/#
```
# My analysis

I suspect the number of port exported by the `codenvy/che` image to be the problem here.

```
$ sudo docker inspect codenvy/che | grep "/tcp" | wc -l
65538
```

In the other hand, it look like the environment variables XXX_PORT_YYYY_TCP_PORT/ADDR aren't generated anymore, thus I don't understand why the ports of the linked containers would be parsed/enumerated while creating the new container that link to codenvy/che (or any other with too much exposed ports)

**Comment by thaJeztah** [comment]
The environment vars are still created for the default (bridge) network

**Comment by fermayo** [comment]
We have also seen this issue without links using the `dockercloud/builder:latest` image, on Docker Engine 1.9.1-cs2

**Comment by thaJeztah** [comment]
The error comes from linux; http://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands. If you're exposing / publishing such a long list of ports, running in `--net=host` may be an alternative.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
