### ISSUE TITLE
Docker with multiple host public ip

### ISSUE THREAD

**Issue by JrCs** [moby/moby#20444]
Hi,
it's not really an issue.
I have a server with multiple public IPs.
Is it possible to force a container to use a specific public ip (and not the default host gateway) when it want to access internet ?

**Comment by LK4D4** [comment]
I think it's possible with iptables.
ping @mavenugo @mrjana @aboch @sanimej

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
