### ISSUE TITLE
Changeable/Editable volumes / ports

### ISSUE THREAD

**Issue by kiorky** [moby/moby#2045]
Even if it needs a container restart, it should be easy to reconfigure ports and volumes for a specific container.

Indeed, for long lived containers (like in the use case of simili - VMs) we would need time to time to change their configuration.

Basically the '-v' and '-p' arguments of docker run should also apply to the start and restart commands.
Related to #2276

**Comment by jfrazelle** [comment]
see also https://github.com/docker/docker/issues/3285

**Comment by marcosArruda** [comment]
A big +1 for this. Need to unexpose a port in a running container, just that. Or, override already exposed ports on run command.

**Comment by reduardo7** [comment]
+1

**Comment by drinktee** [comment]
+1,I need to change hostport mapped to the existing container.

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Comment by reduardo7** [comment]
@vdemeester It was implemented? where is the related doc?

**Comment by kengregson** [comment]
May have missed the resolution unless manipulating iptables is the final answer [map ports](https://github.com/moby/moby/issues/2045), [unmap ports](https://superuser.com/questions/803772/remove-exposed-port-from-docker/808124)?

Ran across this while still having the same issue with Docker 24.0.2 in VirtualBox VMs with Vagrant 2.4.1. Even a service/contrainer restart would be better than having to stop/rm the container from within the VM, tear the VM down and remember to --provision (reload isn't enough). Perhaps a rare use-case but annoying.
