### ISSUE TITLE
docker cp does not parse ~ correctly under mingw

### ISSUE THREAD

**Issue by Giszpenc** [moby/moby#20517]
ls ~/foo/bar works fine in the mingw shell.

```
docker cp ~/foo/bar mycontainer:/some/path/that/is/not/a/problem
```
Produces the following:

```
GetFileAttributesEx C:\c: The system cannot find the file specified.
```

```
$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 146
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: W32A:DI5K:SUJP:2VNQ:IBPP:KJL5:3Z7F:232J:K6DI:55W5:WU5T:MDF3
Debug mode (server): true
 File Descriptors: 66
 Goroutines: 84
 System Time: 2016-02-19T21:27:40.503024569Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by HackToday** [comment]
it seems said 

 C:\c: The system cannot find the file specified.
 
did you use double `c:` ?

**Comment by Giszpenc** [comment]
I used the tilde '~' which works for things like ls but not apparently for docker.

**Comment by thaJeztah** [comment]
This is probably a weird interaction between mingw and docker. I'm wondering what gets sent to the daemon in this case. Also, wondering if there's something related to the lowercase/uppercase `c:`

**Comment by Giszpenc** [comment]
When I do a pwd for example, it gives the response as:
/c/Users/MyUserName/SomeDir/I/am/in
MYDOMAIN+MyUserName/@MyHostname MINGW64 ~/SomeDir/I/am/in

I don't know where the upper case C: comes from.

**Comment by Giszpenc** [comment]
It is not a problem with tilde ~.
When I use the path /c/Users/MyUserName/SomeDir with docker cp it still fails.  Somehow there is a problem in the mingw environment.  Using docker cp filename or docker cp ../filename works OK.
Other commands handle the path with no problem.  It is only an issue with docker cp.

**Comment by arnfox** [comment]
Similar here.
If I try to copy a file at d:\tmp.txt like this
`
$ docker cp /d/tt.txt contname:/tt.txt 
`
`
GetFileAttributesEx C:\d: The system cannot find the file specified.
`

But if I navigate to d:\
`
cd d:
`
`
$ docker cp tt.txt contname:/tt.txt 
`

it goes through OK, no issues. 

Any advice?

**Comment by adj7388** [comment]
I had the same problem. I found I had to:

1. Leave off the /c/
1. Use Windows style slashes: \ instead of /
1. Escape the slashes \\\\

So this works for me:

$ docker cp \\\\Users\\\\Alan\\\\time_scraper\\\\backup.sql my_container:backup.sql

**Comment by silverkorn** [comment]
Using the Git Bash from Git for Windows, this in a script works on a cross-platform perspective (Windows/MinGW, Linux, MacOSX), so you may base on that too as a workaround:

``` bash
#! /usr/bin/env bash

DOCKER_CONTAINER_NAME=docker_container_name
CURRENT_SCRIPT_DIRPATH=$(dirname $(realpath "$0"))

# Windows / MinGW / Docker workaround
[[ "$(uname)" =~ "MINGW" ]] && CURRENT_SCRIPT_DIRPATH=$(echo "${CURRENT_SCRIPT_DIRPATH}" | sed -E 's;^/[^/]+;;g')

MSYS_NO_PATHCONV=1 docker cp "${CURRENT_SCRIPT_DIRPATH}/target_dir" "${DOCKER_CONTAINER_NAME}:/dest_dir/"
```

You can refer here ([https://github.com/docker/toolbox/issues/673](https://github.com/docker/toolbox/issues/673)) for more info about `MSYS_NO_PATHCONV` with Docker for Windows.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
