### ISSUE TITLE
Correct or Repair Docker Installation

### ISSUE THREAD

**Issue by brentarias** [moby/moby#20592]
On my Windows 10 desktop, with a fresh install of Docker 1.10.0, I tried to remove an image.  I was told the image could not be removed because it was used by a container.  I tried `docker ps -a` and saw there were no containers.

Thinking something was unstable, I then tried uninstalling docker. This included deleting the "default" VM in VirtualBox.  I re-installed Docker, but when I ran the quick-start it produced an error which I will describe in a moment.  First, the basics:

> $ docker version
> Client:
>  Version:      1.10.0
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   590d5108
>  Built:        Thu Feb  4 18:18:11 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.10.2
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   c3959b1
>  Built:        Mon Feb 22 22:37:33 2016
>  OS/Arch:      linux/amd64
> 
> $ docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 1.10.2
> Storage Driver: aufs
>  Root Dir: /mnt/sda1/var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 0
>  Dirperm1 Supported: true
> Execution Driver: native-0.2
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: bridge null host
> Kernel Version: 4.1.18-boot2docker
> Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
> OSType: linux
> Architecture: x86_64
> CPUs: 1
> Total Memory: 996.1 MiB
> Name: default
> ID: FGA6:T7ZM:W7XO:OY42:IIWI:MZNL:5LMH:TF3Y:ZNTZ:5KL4:IRWN:OOGG
> Debug mode (server): true
>  File Descriptors: 10
>  Goroutines: 21
>  System Time: 2016-02-23T14:22:36.216401989Z
>  EventsListeners: 0
>  Init SHA1:
>  Init Path: /usr/local/bin/docker
>  Docker Root Dir: /mnt/sda1/var/lib/docker
> Labels:
>  provider=virtualbox

After the re-install I opened the quick-start shell, and saw this error:

> Running pre-create checks...
> (default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
> (default) Latest release for github.com/boot2docker/boot2docker is v1.10.2
> (default) Downloading C:\Users\baria.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.10.2/boot2docker.iso...
> (default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
> Creating machine...
> (default) Copying C:\Users\baria.docker\machine\cache\boot2docker.iso to C:\Users\baria.docker\machine\machines\default\boot2docker.iso...
> (default) Creating VirtualBox VM...
> (default) Creating SSH key...
> (default) Starting the VM...
> (default) Check network to re-create if needed...
> (default) Waiting for an IP...
> Waiting for machine to be running, this may take a few minutes...
> Detecting operating system of created instance...
> Waiting for SSH to be available...
> Detecting the provisioner...
> Provisioning with boot2docker...
> Copying certs to the local machine directory...
> Copying certs to the remote machine...
> Setting Docker configuration on the remote daemon...
> 
> This machine has been allocated an IP address, but Docker Machine could not
> reach it successfully.
> 
> SSH for the machine should still work, but connecting to exposed ports, such as
> the Docker daemon port (usually <ip>:2376), may not work properly.
> 
> You may need to add the route manually, or use another related workaround.
> 
> This could be due to a VPN, proxy, or host file configuration issue.
> 
> You also might want to clear any VirtualBox host only interfaces you are not using.
> Checking connection to Docker...
> Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
> You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
> Be advised that this will trigger a Docker daemon restart which will stop running containers.
> 
> Looks like something went wrong... Press any key to continue...

What now?  After the above failure I got this:

> C:>docker version
> Client:
>  Version:      1.10.0
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   590d5108
>  Built:        Thu Feb  4 18:18:11 2016
>  OS/Arch:      windows/amd64
> An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

Then I rebooted the machine and discovered the quick-start MinGW bash shell was able to open and seemingly "behave," so then I:
1. built a new image (which contained a web server)
2. ran the image

I could never find a way to have local-browser requests be forwarded to the new web server container.  After about a half-hour of fiddling with VirtualBox NAT forwarding rules, I noticed the container reported the following:

> C:\Users\baria\Documents\Visual Studio 2015\Projects\acore\src\acore>docker run webapitest
> Hosting environment: Production
> Now listening on: http://0.0.0.0:5000
> Application started. Press Ctrl+C to shut down.
> read tcp 192.168.99.1:59607->192.168.99.100:2376: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

The server was listening on 5000 for a half-hour before the error message emerged.  I then tried to restart the docker-machine, and had further problems:

> baria@DESKTOP-057K4L5 MINGW64 ~
> $ docker-machine restart default
> Restarting "default"...
> Waiting for SSH to be available...
> Detecting the provisioner...
> Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
> 
> baria@DESKTOP-057K4L5 MINGW64 ~
> $ docker-machine env default
> Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
> You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
> Be advised that this will trigger a Docker daemon restart which will stop running containers.

It seems something is still unstable.

**Comment by AkihiroSuda** [comment]
Let me close this, v1.10 is no longer supported, and Docker Machine and Boot2Docker are deprecated.
