### ISSUE TITLE
can`t run rancher agent & rethinkdb on docker with storagedriver is overlay

### ISSUE THREAD

**Issue by yutian1224** [moby/moby#20640]
Output of `docker version`:

```
[root@test481 ~]# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
[root@test481 ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.73 GiB
Name: test481
ID: KEMR:FF7O:PG5I:5G72:O5AS:DYZJ:3SW4:ERDV:VMEW:A7QQ:FEJ5:T4LW

```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
physical

List the steps to reproduce the issue:
rethinkdb:
1. 

```
docker run -ti  -d --restart=always --name shipyard-rethinkdb-qa  rethinkdb
```

2.

```
docker: Error response from daemon: mkdir /data/docker/overlay/e808ebab6a8aa82acfe27f2b147f164f747606aee78cb34714a3a40f60587a62-init/merged/dev/shm: invalid argument.
```

rancher agent:
1.

```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher stargate.lufax.tool/rancher/agent:v0.9.0 http://172.19.48.3:8080/v1/scripts/D8411D6DCA17E45CE30E:1456243200000:pTHp5MYII1LmtgKUUszpBQZDpFk
```

2.

```
docker: Error response from daemon: mkdir /data/docker/overlay/c7d0f314c8ea4993da8ee27f44222adf0a24f639ac5f0195360326488ed523ed-init/merged/dev/shm: invalid argument.
See 'docker run --help'.
```

Describe the results you received:
But rancher-agent & rethinkdb can run on docker with devicemapper.

**Comment by erikh** [comment]
https://gist.github.com/anonymous/a65ea64eccde7d3e0ba3 is my capture of the docker logs related to this issue.

**Comment by yutian1224** [comment]
I realised that docker can not work prefectly on RHEL/Centos.
The problem is gone when I change node OS to Ubuntu.

**Comment by erikh** [comment]
I am also seeing this on redhat

**Comment by unclejack** [comment]
RHEL/CentOS both use a backport of Overlay to kernel 3.10. This means it might lack some specific changes made to Overlay are missing or that the kernel features it's using aren't exactly the same as they are in the newer kernels.

@rhvgoyal Do you happen to know if the issues encountered on Overlay with the 3.10 kernel on RHEL/CentOS are being investigated? Will there be an update to fix these issues?

**Comment by rhvgoyal** [comment]
I am not sure if this `shm` issue is related to overlay. 

@dwalsh any idea?

**Comment by justincormack** [comment]
Certainly the `rethinkdb` works fine on other overlay based distros, so it seems a `rhel` specific issue.

**Comment by thaJeztah** [comment]
Perhaps someone can open an issue in https://bugzilla.redhat.com ?

**Comment by dserodio** [comment]
@yutian1224 [Red Hat says](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.1_Release_Notes-File_Systems.html#TP-OverlayFS) you should use ext4 when using Overlay on RH 7.1:

>     It is recommended to use ext4 as the lower file system; the use of xfs and gfs2 file systems is not supported.

On RH 7.2, however, you should use xfs instead
