### ISSUE TITLE
Document output format for container logs retrieved from Remote API

### ISSUE THREAD

**Issue by hypirion** [moby/moby#20726]
The docker remote API documentation pages (f.ex. [Remote API v.1.22](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-logs)) describe how to connect and retrieve container logs, but does not describe _how_ the log messages are formatted. I expect to be able to understand what to do with the data I get back.

From what I am able to tell, the log results is a sequence of chunks (I am unsure if these are separated by newline or not, but this seems to be the case). Each chunk seems to be on the format (`fd`, `chunk length`, `contents`). `fd` is a single (1) byte telling you from which file descriptor (1 for stdout, and 2 for stderr) the chunk is from. Next follows `chunk length`, which is 7 bytes telling you how long the length of the log chunk. The length does not include the `fd` field or the `chunk lenght` fields, only the contents. Finally, the contents follow.

This is, however, a result of look-and-guess based only on enabling stdin and stderr. I have no clue what would happen if I enable timestamps, if I only read data from a single source, or if I even use the right terminology here.

It would be much easier to use logs fetched via the remote API if this is properly documented.

**Comment by smalot** [comment]
Many thanks hyPiRion for your analyze.
I encountered the same behavior using the 'docker-php/docker-php' API.
https://github.com/docker-php/docker-php/issues/184#issuecomment-202989046

It's not very clear in the documentation ...

**Comment by isubuz** [comment]
#dibs

**Comment by isubuz** [comment]
I have started to look into this. The remote API docs is missing an additional argument `details` which represents the log driver attributes as documented [here](https://docs.docker.com/engine/admin/logging/overview/).

The log format is composed of the following space separated components as bytes:

`<timestamp> <attrs> <log>`

timestamp is logged if a truth value is passed for `timestamps` argument
attrs is logged if a truth value is passed for `details` argument

For e.g. when the log driver is setup as documented above, the container log file will have a entry like:

```json
{"log":"Hello from Docker.\n","stream":"stdout","attrs":{"fizz":"buzz","foo":"bar"},"time":"2016-05-24T19:36:19.524190052Z"}
```

I will update the related documentation if this sounds ok.

**Comment by isubuz** [comment]
I missed the `journald` driver for which the logs have a different format.

The logger message struct has the format:

```go
type Message struct {
	ContainerID string
	Line        []byte
	Source      string
	Timestamp   time.Time
	Attrs       LogAttributes
}
```

However the implementation for the `json-file` and `journald` drivers are slightly different. For the former, the message is constructed as:

daemon/logger/jsonfilelog/read.go
```go
msg := &logger.Message{
		Source:    l.Stream,
		Timestamp: l.Created,
		Line:      []byte(l.Log),
		Attrs:     l.Attrs,
	}
```

And for the latter it is:
daemon/logger/journald/read.go

```go
logWatcher.Msg <- &logger.Message{ContainerID: cid, Line: line, Source: source, Timestamp: timestamp}
```

Note that `Attrs` and `ContainerID` are not set consistently in both cases. Also it seems like we ignore the `details` argument for the `journald` driver. However attributes are [supported](https://docs.docker.com/engine/admin/logging/overview/#journald-options) for the `journald` driver. 

@thaJeztah Do you know the reason for the inconsistency? Also is this valid for version 1.22 and above?

**Comment by cpuguy83** [comment]
@isubuz The details being ignored on journald is my fault.
@nalind did this work but never made it into docker master.

**Comment by isubuz** [comment]
@nalind do you have plans to integrate your changes? Or should i keep working on this?

**Comment by nalind** [comment]
@isubuz if you've got something worked up, I haven't yet, so go ahead.  Otherwise I can retarget it today, I think.

**Comment by nalind** [comment]
@hyPiRion the framing you're describing is used when the container doesn't have a terminal allocated for it.  When there's a terminal, you just get the output as a stream received from the pseudoterminal, give or take whatever's happening at the HTTP level.

**Comment by isubuz** [comment]
@nalind I have worked on the docs mostly, but know how to get the log formats consistent for both the drivers. Should we do that as part of this task?

**Comment by nalind** [comment]
@isubuz not sure I follow.  Do you mean making sure that the readers are both populating all of the fields of the Message that they hand back to the LogWatcher, or something else?

**Comment by isubuz** [comment]
Yes, so basically the documentation change to describe the log message format and add a note about the attributes. And the code change to populate all fields of the Message for both the drivers and also support the `details` argument for the journald driver (which is currently ignored and the attributes aren't printed)

**Comment by nalind** [comment]
@isubuz Having the json-file reader populate the container ID probably belongs in a different PR than the add-details change for the journald reader, since they're independent fixes, but I can open one for that, too.  I haven't got any docs changes to propose, but FWIW I'm happy to take a look at anything you've worked up.

**Comment by nalind** [comment]
While looking at setting the ContainerID in Message structures, I don't see any part of the code, other than tests, that ever reads that field.  The log drivers that care about the container ID are consistently reading the value from the Context that they're passed when they're initialized, and referring to that value later.  So I'm leaning toward removing the field.
