### ISSUE TITLE
No ppc64le Ubuntu repository

### ISSUE THREAD

**Issue by stewart-ibm** [moby/moby#20801]
After adding the apt repository according to https://docs.docker.com/engine/installation/linux/ubuntulinux/ instructions, it fails to fetch Docker. There is nothing in the documentation to suggest that ppc64le is not supported in this setup.

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-wily/Release  Unable to find expected entry 'main/binary-ppc64el/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by daxtens** [comment]
This is an ugly hack, but you can substitute 'ubuntu' for 'ppc64le/ubuntu' in your FROM line and things will work.

**Comment by daxtens** [comment]
Whelp, completely misunderstood your bug. Carry on!

**Comment by suiyuan2009** [comment]
#dibs

**Comment by suiyuan2009** [comment]
I will try my first commit. just add a note to the installation guide?

**Comment by thaJeztah** [comment]
I think that should work (although we may want to think of having a central "prerequisites" page at some point.

Looking further, it looks like we're actually building static binaries for ppc64le, see https://master.dockerproject.org.

**Comment by duglin** [comment]
correct - that's why I'm a bit confused as to what the exact issue.  Is it just that we need to point to these bleeding edge binaries or is there something wrong with the ppc64le ubuntu distro stuff?
@stewart-ibm can you be more explicit about the specific step that failed?

**Comment by thaJeztah** [comment]
@duglin it's possible that we have only static builds for ppc64le, but no dynamic builds, hence it not being present in the apt/yum repositories?

**Comment by stewart-ibm** [comment]
I think @clnperez comment above about pointing to master.dockerproject.org for non-x86 platforms would work as an interim until the repositories have binaries for all arches.

**Comment by ligc** [comment]
any update on the progress of adding the ppc64le deb packages into the docker Ubuntu repository https://apt.dockerproject.org/repo/? Thanks.

**Comment by thaJeztah** [comment]
@ligc No progress at this moment; having official support likely also should include having the official images available for these architectures, and multi-architecture images is still a work-in-progress. Current state for official images can be seen here https://hub.docker.com/u/ppc64le/.

Possibly we can add "experimental" builds at some point, but we probably need more CI for PowerPC architecture then as well

**Comment by tophj-ibm** [comment]
@thaJeztah any idea what the next steps are for this? I've added functionality to be able to build power debs into Docker for 14.04 and 16.04, and we already have the corresponding images in the ppc64le dockerhub. We also should have enough CI machines in Jenkins to handle adding in another job for building/testing if we have to.

**Comment by thaJeztah** [comment]
let me check with @tiborvass 😇

**Comment by tophj-ibm** [comment]
@thaJeztah @tiborvass any updates / ideas? I know the release-deb script needs updating to add in ppc64le, but I'm not sure if there is anything else or of my authority in this.

**Comment by thaJeztah** [comment]
ping @andrewhsu could you have a look?

@tophj-ibm feel free to open a PR for updating the release script, then we can discuss there

**Comment by vdemeester** [comment]
@andrewhsu @thaJeztah what is the status here ? Should we move this issue to `docker/docker-ce` instead ?

**Comment by thaJeztah** [comment]
Packages are now there; https://download.docker.com/linux/ubuntu/dists/xenial/stable/ (they're named `ppc64el`, not `ppc64le`, which is a Debian/Ubuntu convention

**Comment by thaJeztah** [comment]
Oh, and the docs have a matrix of supported platforms: https://docs.docker.com/install/#server

<img width="922" alt="screen shot 2018-02-14 at 11 10 53" src="https://user-images.githubusercontent.com/1804568/36198766-cbf693aa-1177-11e8-84e9-c38343282699.png">
