### ISSUE TITLE
daemon.CopyOnBuild from daemon/archive.go should use go-winio on Windows

### ISSUE THREAD

**Issue by swernli** [moby/moby#21009]
The docker daemon uses the archiver package in CopyOnBuild to in order to get files into a container as part of an ADD command in a build.  Unfortunately, this means that Windows specific alternate data streams are lost, as the regular archiver implementation does not capture these.

To better support Windows file attributes and alternate data streams, the files should be copied using backup-streaming semantics introduces in https://github.com/Microsoft/go-winio package.  This is already in use for docker commit, and could be extended into the archiver package so that Windows specific files are handled properly.

For an example of the alternate data streams being lost, use "dir /r" on a file that was downloaded from the internet (it will have a Zone.Identifier alternate data stream identifying where it was downloaded from).

On the host:
dir /r \test\simple*
 Volume in drive C has no label.
 Volume Serial Number is 3622-361C

 Directory of C:\test

02/10/2016  11:17 AM            67,646 simple_icon_50.ico
                                    26 simple_icon_50.ico:Zone.Identifier:$DATA
               1 File(s)         67,646 bytes
               0 Dir(s)  11,712,167,936 bytes free

In the container after ADDing that file:
Step 3 : RUN dir /r \simple*
 ---> Running in 94b92d329f78
 Volume in drive C has no label.
 Volume Serial Number is ECAB-5980

 Directory of C:\

02/10/2016  11:17 AM            67,646 simple_icon_50.ico
               1 File(s)         67,646 bytes
               0 Dir(s)  21,269,565,440 bytes free

**Comment by thaJeztah** [comment]
@swernli @jhowardmsft is this still an issue? Is this still needed?

**Comment by swernli** [comment]
@thaJeztah The problem still repros for me.  When files are copied into a container, they lose their alternate data streams, which means metadata (like where the file was downloaded from) are gone.  Using go-winio as suggested about should be able to resolve this issue, but may be @jstarks can comment more.

**Comment by simonferquel** [comment]
I suppose it won't fix the issue, as the client context is first built into a tar archive (which have no notion of alternate data stream IIRC).

If we want to support those, we would need to use another kind of archive.
