### ISSUE TITLE
Remote API Event filters 

### ISSUE THREAD

**Issue by carlskii** [moby/moby#21066]
Hi,

Ok, so I've finally worked out what I needed to do as <a href="http://blog.arungupta.me/enable-docker-remote-api-mac-osx-machine/">workaround</a> for the Mac Kitematic issue so that I can access the API using curl. 

This works OK: 

```
curl -s --no-buffer -XGET --insecure --cert cert.p12 --pass mypass https://127.0.0.1:52376/events
```

However, I now want to filter the response stream. The API 1.21 docs suggest that this should work:

```
https://127.0.0.1:52376/events?filter=........
```

e.g.

   events?filters=%7B%22image%22%3A%5B%22injcristianrojas%2Fnginx-ssl%22%5D%7D

However, no matter what I try here the filter gets ignored.

I need to filter on the `status` and `name`fields but so far I can't get this to work. The docs aren't particularly clear as to the filter should be constructed. 

Are there any examples out there ? 

I'm trying to create a filter that only returns based on a `Type=container` and `status=start or status=die`

**Comment by HackToday** [comment]
This page include what filters are supported.

Check this would help you figure out what format would be used in curl

https://docs.docker.com/engine/reference/commandline/events/

**Comment by vdemeester** [comment]
@carlskii not sure if it's still an issue for you, but the *status* you mean is the `event` filter (for event).
