### ISSUE TITLE
Docker Daemon Aufs Mount Panic

### ISSUE THREAD

**Issue by dadgar** [moby/moby#21078]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /opt/docker/data/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-43-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: c1m-nomad-client-us-central1-b-n1-standard-8-1-1mu9
ID: QK7Z:NE6P:BKB6:L6EJ:CYC4:EULW:46AA:FMGN:35V7:GYJ3:E2VV:V2CV
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Environment: GCE
Machine Type: n1-standard-8

List the steps to reproduce the issue:
1. Running hundreds of containers on the same docker daemon in a very short time frame

This is fairly reproducible, on a 500 node cluster, 8 nodes had this panic.

Describe the results you received:

Docker daemon panics. Logs attached.

[docker_2.txt](https://github.com/docker/docker/files/166278/docker_2.txt)
[docker_3.txt](https://github.com/docker/docker/files/166279/docker_3.txt)
[docker.txt](https://github.com/docker/docker/files/166280/docker.txt)

**Comment by HackToday** [comment]
From above comments, the case is `create and delete containers repeatedly`  right ?   Parallel test?

**Comment by cpuguy83** [comment]
This is probably because of https://github.com/docker/docker/blob/v1.10.2/daemon/graphdriver/aufs/aufs.go#L230
Modification is happening while not protected by a mutex.
This is most likely fixed in master since it is now protected: https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L232

**Comment by dadgar** [comment]
@HackToday it is mainly a batch of creates and then minutes later a batch of deletes

**Comment by kenorb** [comment]
Related: [Nomad - Million Container Challenge](https://www.hashicorp.com/c1m/)

**Comment by thaJeztah** [comment]
Let me close this issue, because this was most likely fixed (see https://github.com/moby/moby/issues/21078#issuecomment-194598933), and we received no other reports of this since
