### ISSUE TITLE
Removal of containers on NFS using aufs storage driver often fails

### ISSUE THREAD

**Issue by trianglee** [moby/moby#21086]
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /shared/temp-docker-graph/aufs
 Backing Filesystem: nfs
 Dirs: 6
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.8 GiB
Name: prov-dev
ID: N5JQ:J4OH:U2D2:EAHM:K2RK:L5TI:5RBL:IMCE:72AO:7NHA:ERK3:EKC7
WARNING: No swap limit support
```

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**
The problem is reproduced on a physical machine.
The problem is only reproduced when the graph is stored on an NFS export.

**List the steps to reproduce the issue:**
1. Create and remove containers quickly, by running the following script -

```
#!/bin/bash

ITERATIONS_COUNT=10

ITERATIONS=`seq -s" " 1 $ITERATIONS_COUNT`
for ITERATION in $ITERATIONS; do
        rm cid.txt
        docker run -ti --cidfile=cid.txt ubuntu echo hello
        CID=`cat cid.txt`
        docker rm -f $CID
        if [ $? -ne 0 ] ; then
                echo ERROR!
                exit
        fi
done
```

**Describe the results you received:**
After a few iterations (typically, very few), "docker" reports -

```
Failed to remove container (3a846d4f0c6e4c0e4e782e08ab0d766fa6abf0c2c2ba2c212402e5b638de4411): Error response from daemon:
Unable to remove filesystem for 3a846d4f0c6e4c0e4e782e08ab0d766fa6abf0c2c2ba2c212402e5b638de4411: 
remove /shared/temp-docker-graph/containers/3a846d4f0c6e4c0e4e782e08ab0d766fa6abf0c2c2ba2c212402e5b638de4411: 
directory not empty
ERROR!

```

**Describe the results you expected:**
Creation and removal of containers shouldn't result in such errors, even on NFS.

**Provide additional info you think is important:**
A workaround for the problem is to store the "containers" directory on non-NFS storage (a symlink works fine). This isn't a scalable solution, though.

**Comment by cpuguy83** [comment]
NFS is not supported for graph storage.

**Comment by trianglee** [comment]
@cpugu83, thanks for the reply.

Is this "not supported" in the sense that "We don't support it, but we don't know of any significant issues - if it works for you, fine!" or in the sense that "It is really dangerous to use NFS, you should really avoid that!"?

In both cases, I recommend adding this information somewhere in the documentation (I couldn't find such reference), and maybe also to the output of "docker info" ("nfs" is already detected there, it may be important to add some comment stating this isn't recommended).

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
