### ISSUE TITLE
Is `-v /var/run/docker.sock:/var/run/docker.sock` a ticking time bomb?

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#21109]
So..... `-v /var/run/docker.sock:/var/run/docker.sock` is super common, and I'm very guilty of this.  For anyone who has dealt with bind mounting UNIX sockets finds out really quickly that you can't bind mount the socket itself, but instead you must bind mount the directory containing the socket.  This is because the listening process will delete and recreate the socket so if you bind mount a socket you hold a reference to something that is possibly not used.  BUT... `/var/run/docker.sock` is special because if that file is deleted and recreated, well, your container is too.  With containerd integration #2658 is supposed to be fixed, but what happens to `/var/run/docker.sock` on daemon restart.  How will this be addressed.

**Comment by jfrazelle** [comment]
only you :clap: nice find

**Comment by phemmer** [comment]
This might be nice to fix for other uses as well. Another common case of binding sockets is `-v /dev/log:/dev/log`, which fails if the syslog daemon restarts on the host.
There are only 2 solution I can think of.
1. The docker daemon were to proxy the socket instead of bind mounting it. We could do this, and make it transparent by just having docker check if the `-v` argument is a socket, and if so, implement the proxy.
2. The docker daemon does a bind mount, but monitors the socket on the host. If it gets recreated, it recreates the mount. This is potentially problematic though as there are edge cases where this wouldn't behave right (though the cases I can think of are really rare).

**Comment by cpuguy83** [comment]
@phemmer Recreating the mount won't really work since the container won't see the updated mount info.

**Comment by bboreham** [comment]
Or you could add a way to declare a container as "needs to interact with host Docker", then the socket is provided without any `-v` flags.  Related to #20363, perhaps.

**Comment by phemmer** [comment]
> @phemmer Recreating the mount won't really work since the container won't see the updated mount info.

Eh? Why wouldn't it?

**Comment by cpuguy83** [comment]
@phemmer I mean I guess it's possible, but we'd have to enter the mount namespace, would we not?

**Comment by phemmer** [comment]
> @phemmer I mean I guess it's possible, but we'd have to enter the mount namespace, would we not?

Yeah, but we're docker, we can do whatever we want to our containers :-)

**Comment by crosbymichael** [comment]
It would be no different than today.  If you have a container with the socket bind mounted into it.  Docker exits but your container keeps running, it sill cannot access the docker API.  You should have your container exit and get restarted anyways if it gets an error from the socket right?

**Comment by ibuildthecloud** [comment]
@crosbymichael That doesn't really work out well because your code talking to the socket has to special case a connect error.  Typically you are using some docker client and most of the `err` response are opaque and treated as a typical API error.  Now you have to catch and deal with this one error in a very specific way.  I know on a lot of errors you might exit your application, but if I'm talking to remote API it don't just panic on the first error I see.

**Comment by ibuildthecloud** [comment]
I do like @bboreham suggestion where I can just request the docker socket to be put in the container.

**Comment by thaJeztah** [comment]
We are still looking into providing an introspection API, but no ETA for that (yet)

**Comment by MetalArend** [comment]
could this not be done by adding something like the `--privileged` option?

**Comment by ferrx** [comment]
How do any of these proposed workarounds impact the _CIS Docker Community Edition Benchmark_ control 5.31 "**Ensure the Docker socket is not mounted inside any containers**" https://docs.docker.com/compliance/cis/docker_ce/

Do any of these workarounds circumvent other controls? I'd imagine --privileged would not be a suitable workaround.

(Also: Does UCP bind to Docker socket? Does this mean UCP is not compliant? I'm just reading from the CIS for CE, maybe EE is different?)

**Comment by bboreham** [comment]
The circumstances in which you want a container to talk to the Docker unix socket are ones in which you have already decided to grant absolute power to that container.
