### ISSUE TITLE
docker0 broken WAN connectivity - after docker network create 192.168.*

### ISSUE THREAD

**Issue by dreamcat4** [moby/moby#21141]
**docker version:**

``` sh
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

**docker info:**

``` sh
 docker info

Containers: 125
 Running: 6
 Paused: 0
 Stopped: 119
Images: 1143
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.791 GiB
Name: emachines-e520
ID: NG2B:QLY4:W2SH:6FQF:FYGU:TVLX:3IQL:CQ4S:N5DL:CTND:52ZD:GCDH
```

**Additional details:**

List the steps to reproduce the issue:

If the host machine's subnet is 192.168.*/16 (same as LAN / router) - then adding a docker network with the same subnet will break docker0.

``` sh
docker network create --subnet 192.168.0.0/16
```

Wereas its fine on any other subnets :mag: 

**Results received:**
- The `docker0` interface initially continues to remain working, but only during the first < 1 minute after creating the new docker network.
- Broken `docker0`. No WAN connectivity from within the container. No `ping 8.8.8.8` or anything else. There is an endpoint still given in the container. But its broken.
- Cannot build images with `docker build`. Because that relies upon `docker0`.
- Partitioning the `/16` subnet into two `/17` subnets (half), does not break the `docker0` straight away. But causes other serious connectivity issue. So unfortunately is no way to solve it.
- Have tried everything I can possible think of at this point.

**Results expected:**

The regular `docker0` WAN connectivity to continue un-broken. eg successful ping to google.com 8.8.8.8 during docker builds.

Provide additional info you think is important:
- When the subnet is in 172.\* and isolated, then setting the bridge name has no negative impact.
- When the subnet is in 192.167.\* and again outside / isolated of the physical LAN net, then setting the bridge name has no negative impact.
- When the subnet is in 192.168.*, then setting the bridge name results in broken `docker0` bridge network connectivity.

----------END REPORT ---------

**Comment by dreamcat4** [comment]
This is something:

```sh
s$ docker exec -it smb.ansible ip route
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2 
```

Here we can see ^ that the routing table still going through `eth0`. Which becomes 'broken' after physical bridging. I suppose it could be circum-vented with the use of 2 physical NIC adapters. As 1 could be left working normally (while the other became bridged). Unfortunately this machine only has 1 NIC port. So that would not be an option for me...

So perhaps to get `docker0` default route through my other bridge interface instead. Which is `br-docker-eth0` (added to interface `eth0`). Not sure how though :/

**Comment by dreamcat4** [comment]
Here is how I create the external bridging, at boot time. It happen before docker daemon is started.

1. Create bridge at system boot:

```sh
cat /etc/network/interfaces
# cat /etc/network/interfaces
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback


# eth0 - disable all networking configuration
auto eth0
iface eth0 inet manual


# added for docker network bridge
auto br0
iface br0 inet dhcp
  hwaddress ether 02:42:c0:a8:03:21
  bridge_ports eth0
```

**Comment by dreamcat4** [comment]
Any suggestion?

**Comment by jeromepin** [comment]
Hi @dreamcat4,

What happens if you don't create the bridge manually, but let docker do it for you ?

**Comment by dreamcat4** [comment]
> What happens if you don't create the bridge manually, but let docker do it for you ?

Thanks for the suggestion @jeromepin. Unfortunately its no help :(

Test results:

1. Persistence across reboots isn't possible that way
2. Host machine configuration by static DHCP isnt possible that way 
3. the `docker0` legacy bridge still breaks anyhow
4. Breakage of `docker0` occurs straight after the line `docker network create ...`
5. Breakage of `docker0` occurs before `brctl addif ..` line. Which means that external bridging to `eth0` hasn't happened yet.
6. Breakage does not 'un-fix' itself at any future point (subsequent steps). Only known solution is to delete the docker network and reboot host machine.
7. My computer is a laptop, it only has 1 NIC interface for me to play with.

Gist log of test results: https://gist.github.com/dreamcat4/ee505cd32363dfa00fe5

* Is this is a bug in new docker networking / legacy `docker0` interopability?
* Any extra cmds to run and better see why `ping 8.8.8.8` fails inside of the container for `docker0` bridge?

Keen to see this issue resolved. Any further help I can be here?

**Comment by dreamcat4** [comment]
BTW

My laptop also has a wifi card!

So now I also enable that 2nd NIC too now (`wlan1`) for regular host WAN connectivity. Unfortunately there is no improvement :(

Also: I don't know how to tell docker to point `docker0` bridge to my `wlan1` interface instead. Both of them (`br0` + `wlan1`) show up as default route:

```sh
# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         tomato.lan      0.0.0.0         UG    425    0        0 br0
default         tomato.lan      0.0.0.0         UG    600    0        0 wlan1
link-local      *               255.255.0.0     U     1000   0        0 br0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.0.0     *               255.255.0.0     U     0      0        0 br0
192.168.0.0     *               255.255.0.0     U     600    0        0 wlan1
```

**Comment by dreamcat4** [comment]
Well... this is un-expected.

setting `-o com.docker.network.bridge.name` seems to be the flag that results in broken `docker0` / docker build network connectivity.

**Comment by dreamcat4** [comment]
Ah I'm getting tired of this. The problem persists, even when I cut the subnet in half, and allocate the extern bridge `br0` to be the 2nd half of the IP range: `192.168.128.0/17`

*Which 'looks like it might work to begin with'... yet doesnt after the remaining network configuration is finalized.

**Comment by dreamcat4** [comment]
This issue can be 'somewhat' worked around by running dind. However that is a massive hack and impacts server performance. It requires several shell hacks to mask / redirect the `docker build` command, and `docker save | docker load` between the inside and the ourside docker daemons.

My overall feeling is that this bug can be more easily fixed in docker code itself. Ironically you guys for other reasons removed an experimental 'set default network' option, which may have more easily avoided such dependance on docker0 whilst building. But I cant set that here anymore as the option has been taken away from users.

**Comment by neersighted** [comment]
This is very old/relates to networking code that no longer exists. However, this issue is by design: as container networking uses the kernel network stack, adding two routes to the same subnet will obviously cause one to win out over the other. There is no solution other than avoiding the collision, as a single IP address/subnet can only ever refer to a single host/group of hosts from the perspective on a single network namespace.
