### ISSUE TITLE
iptables: add -j DOCKER to OUTPUT chain

### ISSUE THREAD

**Issue by lheckemann** [moby/moby#21167]
Currently, the DOCKER chain which allows access to containers' exposed ports from anywhere is only added to the FORWARD chain. This means that in a fairly restrictive firewall configuration (OUTPUT policy set to DROP), the host will not be able to access container ports even if they are exposed. Would it be possible to add a -j DOCKER rule to the OUTPUT chain as well as FORWARD?

**Comment by thaJeztah** [comment]
ping @aboch ptal

**Comment by iclanzan** [comment]
I have just run into the same problem. I have the default policy of OUTPUT set to DROP and cannot access ports exposed by Docker.

Are there plans to add `-A OUTPUT -j DOCKER` or a similar rule?

**Comment by aboch** [comment]
@iclanzan @lheckemann If your OUTPUT chain default policy is set to DROP, whoever/whatever did it seems like a security policy, I am not sure it would be a good idea for docker to add a chain and rule in there to bypass that policy.

**Comment by iclanzan** [comment]
I did it to prevent all traffic by default and only allow traffic to the internet through the VPN IP.

**Comment by iclanzan** [comment]
> I am not sure it would be a good idea for docker to add a chain and rule in there to bypass that policy.

Can’t the same be said for the FORWARD chain? And yet Docker bypasses that.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
