### ISSUE TITLE
using networking (with compose v2 syntax) adds 1 second delay

### ISSUE THREAD

**Issue by schmunk42** [moby/moby#21168]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        2016-03-10T21:49:11.235199091+00:00
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 101
Images: 522
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1205
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
CPUs: 3
Total Memory: 1.463 GiB
Name: dev7
ID: C63I:2K5W:YZ5P:7M54:KD65:SVJE:QKDE:H5JS:BXHI:I27N:BOOP:GECU
Debug mode (server): true
 File Descriptors: 49
 Goroutines: 75
 System Time: 2016-03-13T21:06:17.199571395Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: schmunk42
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox

**Steps to reproduce the issue:**
1. upgrade to v2 format
2. use networking features

**Describe the results you received:**

1 second delay when PHP container connects DB container.

**Describe the results you expected:**

No delay like in v1.

**Additional information you deem important (e.g. issue happens only occasionally):**

<img width="910" alt="bildschirmfoto 2016-03-13 um 21 59 14" src="https://cloud.githubusercontent.com/assets/649031/13731404/f4ae59ca-e967-11e5-8d8d-37128eeca9d8.png">

Old vs new syntax: https://github.com/phundament/app/commit/01bc986fbcd4c8348b88f114881b790148364fa7

Probably related issues: https://github.com/docker/docker/issues/21126

**Comment by thaJeztah** [comment]
This is quite old now, and may have been fixed in docker 1.11 and up; https://github.com/moby/moby/issues/21126#issuecomment-216840446
