### ISSUE TITLE
Suggesting a fixed Docker group ID of # 357 

### ISSUE THREAD

**Issue by KamranAzeem** [moby/moby#21184]
This is a Feature Request.

Attempting to automate docker containers through jenkins (docker in docker, and docker beside docker, etc) is proving to be difficult. Most of the automation solutions are centered around the fact that docker socket is mounted from the host and then the other container can manage the docker daemon on the docker host, such as building container images, starting or stopping containers, etc. 

The problem is that this socket has read permissions for the group docker, which may have different group ID on different systems. E.g. I have Fedora 23 as my desktop, and it has the docker group id as "978" (strange!) . Inside a jenkins container (I installed docker inside it), the group id for docker group is 999. On a production (ubuntu) server the group id of docker group is 1001. It is quite crazy to try to make docker a group member of all possible / conceivable group ids, when setting up some automation, e.g. using jenkins. I thought of using 999 as a standard group ID for docker across the board, but then I saw Fedora 23 (on my work computer), is using 999 for some group named "input" . 

I though of what group ID to make standard across all distros, and I though of "dkr" which translates to "357" when pressed on a phone key-pad. A quick check revealed that this group is unused on all three distros . May be Docker (you guys) can use this group id and make it de-facto standard on all distros?
Thanks!

**Comment by thaJeztah** [comment]
Thanks for suggesting, actually I don't know if there's a way to register a standard uid/gid so that all distros will use that. If you know of a way to register this, that would be helpful!

**Comment by j16sdiz** [comment]
I doubt you can reserve 357 across all distro.

LSB 3.0 said only 0-99 are statically allocated; 100 to 499 are dynamically allocated for system use (i.e. system package dynamically pick one when installed).
It will collude with other system packages if you pick one in this dynamic range.

For debian, you can reserve one in 60000-64999 range by filing a bug against `base-passwd` package. 
For fedora, they are not entertaining static gid allocation any more.

Before asking for an id in Debian, you have to think about migration strategy...

**Comment by KamranAzeem** [comment]
Thank you!
I had a look too on some documents, in the morning, but then I got bogged
down with work. I also wanted to quote what you quoted. So thanks for that.

So may be we can use a new abbreviation , such as "dokr", making it 3657
and bringing it out from the reserved range into a more open range?

It can be used as a de-facto standard, instead of being a formal one. I
just wanted to have a more standardized approach; and I am pretty sure,
that when you announce such a group ip on your website, through various
documents, (and when it gets mentioned enough times), people will notice,
including distributions, and hopefully no one will try to step on this one.

Just trying to make Docker more friendly , easy to use , including better
migration strategies.
Regards

On Tue, Mar 15, 2016 at 2:22 PM, Daniel Cheng (鄭郁邦) <
notifications@github.com> wrote:

> I doubt you can reserve 357 across all distro.
>
> LSB 3.0 said only 0-99 are statically allocated; 100 to 499 are
> dynamically allocated for system use (i.e. system package dynamically pick
> one when installed).
> It will collude with other system packages if you pick one in this dynamic
> range.
>
> For debian, you can reserve one in 60000-64999 range by filing a bug
> against base-passwd package.
> For fedora, they are not entertaining static gid allocation any more.
>
> Before asking for an id in Debian, you have to think about migration
> strategy...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/docker/docker/issues/21184#issuecomment-196813479
>



-- 
http://www.wbitt.com
Computer bugs are like shipwrecks. They are not found, unless they want to
be found.

**Comment by thaJeztah** [comment]
Thanks @j16sdiz I already suspected this would be hard to achieve. Based on that information, it looks like we'll never be able to get a consistent uid/gid among distros. IMO, this'll only have benefits if we can guarantee that it's the same on all distros, otherwise it'll still be a hit and miss.

**Comment by jhovell** [comment]
Looks like one possible workaround for this feature might be to use the --group-add flag when launching containers. @KamranAzeem did you find an acceptable workaround for this issue with Jenkins and Docker-on-Docker? I'm still looking for a workaround since the --group-add flag does not seem to be exposed yet for schedulers such as ECS or Kubernetes.

https://docs.docker.com/engine/reference/run/#/additional-groups

https://github.com/kubernetes/kubernetes/issues/12686
No open ECS issue that I am aware of.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I don't see anything actionable per the discussion above.
