### ISSUE TITLE
aufs: builder: ADD file.tar.xz fails

### ISSUE THREAD

**Issue by cyphar** [moby/moby#21216]
Unfortunately, at the moment I can only reproduce this with the openSUSE `.tar.xz` rootfs.

```
% docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4 MiB
Name: debian-jessie
ID: AVB6:I5YK:XKEG:DA4C:KLRP:EEVR:OG5A:Q7CI:LZUA:VELA:7JJM:NT2U
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
% docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64
```

```
% git clone https://github.com/openSUSE/docker-containers-build.git
% cd docker-containers-build/
% git checkout -b openSUSE-Tumbleweed
% cd docker
% docker build -t opensuse:tumbleweed
Sending build context to Docker daemon 34.57 MB
Step 1 : FROM scratch
 ---> 
Step 2 : MAINTAINER Flavio Castelli <fcastelli@suse.com>
 ---> Running in e75fcd5603b0
 ---> 9b38353a8fa2
Removing intermediate container e75fcd5603b0
Step 3 : ADD openSUSE-Tumbleweed.tar.xz /
Untar re-exec error: exit status 1: output: operation not supported
```

On `1.9.1` this resulted in the file just being copied to `/openSUSE-Tumbleweed.tar.xz`. I have a feeling it might be related to the set-capabilities we've added in the newest version of the image tar (and AUFS doesn't appear to support extended attributes).

This doesn't happen on `btrfs` or `devicemapper` (I haven't tested any others). This is the root cause of the issues described in docker-library/official-images#1537 and openSUSE/docker-containers#13.

/cc @tianon

**Comment by cyphar** [comment]
Since `docker pull opensuse/amd64:tumbleweed` works (which is an image that contains layers with extended attributes), this means that the `docker import` machinery works. Maybe the trick is to combine that machinery with the un-tarring we do with `ADD` (although it might be necessary to update `ADD` and `COPY` in all instances -- since the build context preserves extended attributes IIRC).

I'd be happy to work on this this week.

**Comment by yosifkit** [comment]
Can confirm that it extracted the tar on `ADD` with docker 1.9.1 on overlay.

**Comment by cyphar** [comment]
I think I've figured out how to fix this. If we combine `CopyOnBuild` with the layer store's `ApplyDiff` functionality, this might result in both cleaner code and allowing each `graphdriver` to deal with its own peculiarities separately. I'm going to work on this over the next few days.

**Comment by cyphar** [comment]
I've made a /preliminary/ fix in #21251. But a proper fix would have to do the `CopyOnBuild` cleanup that I reference above.

**Comment by runcom** [comment]
This is happening as well on RHEL and Fedora with Fedora 24 base tar.xz and devicemapper (XFS) but only when `--selinux-enabled` is provided to the docker daemon /cc @rhatdan

**Comment by rhatdan** [comment]
As I explained in the other issue.  Setting SELinux labels is not supported if you use a context mount of a file system.  When using SELinux with devicemapper we are mounting the thin devices with context mounts, so when the builtin tar tries to write the SELinux label, the kernel rejects the label as ENOTSUPP, which we should ignore.  We really do not want these labels preserved from the tar anyways.

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
