### ISSUE TITLE
Docker, ipc resources and '--privilaged' option

### ISSUE THREAD

**Issue by yogmk** [moby/moby#21239]
[Issue also posted on Stackoverflow http://stackoverflow.com/questions/36009532/docker-ipc-resources-and-privilaged-option]

Docker version 1.9.1

We're trying to qualify our company's application with Docker, but facing an issue.

Application, on start up sets up chunks of shared memory and message queues and then spawns several other processes who share them.

Normally on 'AppStop', the spawned processes are brought down and the ipc resources (shm and msgq) are cleaned up. However in Docker container, the cleanup is not happening. We're seeing errors like "UNIX errno 1 from msgctl", "Operation not permitted". Though processes go away, ipcs still show the shared memory segments and msg queues left behind. As a result, subsequent 'Appstart' in the same container fails to start new set of processes. The way around is to exit the container, stop it and start again.

We have created a new user "appuser" in the Docker image and the application runs as that user. The startup and cleanup binaries have the setuid bit set so that they run as root. The Docker command line is

`docker run -d -u appuser -w /home/appuser/node -e TERM=vt100 -p 9876:6666 --name "demo" <IMAGE_ID> bash -c '. ./setup; Appstart $APPSYS; tail -f $APPSYS/Appmain.log'`
after adding '--privilaged' option to the above command, the problem (of ipc resources left behind) goes away. I can stop and start the Application in the same container.

I'm unable to understand why.
-     What difference does '--privilaged' make?
-     could there be any unintended side effects of using this option?
-     In the documentation, there is also a mention of capabilities '--cap-add' with values like 'IPC_LOCK' and 'IPC_OWNER'. I'm curious as to what these option will do.

Can anyone throw more light on this? We need to finalise a 'recommended way' to run our Application with docker. Thanks.

**Comment by thaJeztah** [comment]
Have you tried if it works when adding those capabilities? Usually it's best to not use `--privileged`, but find which capabilities are actually needed. `IPC_OWNER` is probably what you need, otherwise `SYS_ADMIN` capability is a likely candidate.

Let me know if that works, or if you need more info

**Comment by thaJeztah** [comment]
closing because this went stale
