### ISSUE TITLE
recursive RUN command

### ISSUE THREAD

**Issue by abe-winter** [moby/moby#21230]
Hi,

Please consider implementing a recursive RUN command for Dockerfile -- i.e. running the command on its own cache output. This would vastly accelerate any package management command.

For example:

```
RRUN cache_tag apt-get -qqy install pkg1 pkg2
```

When this changes, the new `RRUN cache_tag` line should run on the old output. (when the ancestor layers are the same).

```
RRUN cache_tag apt-get -qqy install pkg1 pkg2 pkg3
```

Allowing volumes at build-time (https://github.com/docker/docker/issues/14080) would probably be just as good. The non-sequential caching proposal (https://github.com/docker/docker/issues/17260) also may be asking the same question.

**Comment by thaJeztah** [comment]
This has gone stale, and I think (although a slightly different approach) the experimental [`RUN --mount=type=cache`](https://github.com/moby/buildkit/blob/b939973129b3d1795988e685f07a50a2afe8a401/frontend/dockerfile/docs/experimental.md#run---mounttypecache) syntax (available when using BuildKit) should address this, so I'm closing this one
