### ISSUE TITLE
Docker Volume not deleted after machine susspension

### ISSUE THREAD

**Issue by stmuraka** [moby/moby#21234]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
Images: 327
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.10.0
CPUs: 1
Total Memory: 1.958 GiB
Name: coreos-03
ID: SSHW:SRIX:DWT7:QHNW:R7VF:QSJ7:4JNM:OURM:3JGG:FMGP:TB3W:5AEA
Cluster store: etcd://127.0.0.1:2379
Cluster advertise: 192.168.110.103:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox CoreOS

**Steps to reproduce the issue:**
1. run docker container linked to a volume
2. suspend the VM
3. resume the Vm
4. docker rm -fv (all the containers)
5. docker volume ls 

**Describe the results you received:**
`docker volume ls` shows remaining volumes not attached to any containers

```
core@coreos-03 ~/repo/build $ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

core@coreos-03 ~/repo/build $ docker volume ls
DRIVER              VOLUME NAME
local               b0486e67a7061320dd3514a55e8a051b8330be7d0ce02d2d9da307b48d8aaf14
local               9bd439ba847e1f3d6718ff38fc919b363cdf6b4958920f14b06379c0c369b415

core@coreos-03 ~/repo/build $ docker volume rm b0486e67a7061320dd3514a55e8a051b8330be7d0ce02d2d9da307b48d8aaf14 9bd439ba847e1f3d6718ff38fc919b363cdf6b4958920f14b06379c0c369b415
Error response from daemon: Conflict: volume is in use
Error response from daemon: Conflict: volume is in use

```

**Describe the results you expected:**
the volumes should be deleted or able to be deleted

**Additional information you deem important (e.g. issue happens only occasionally):**
this happens on occasion. running CoreOS vms managed by vagrant. when the machine suspends, the vms are also suspended and resumed on power up.

**Comment by thaJeztah** [comment]
I think changes were made to address this; @stmuraka are you still having this issue on the current release?

**Comment by thaJeztah** [comment]
closing; this one went stale
