### ISSUE TITLE
yum terminated at docker build time

### ISSUE THREAD

**Issue by willievu** [moby/moby#21288]
**Output of `docker version`:**

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 16:08:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 16:08:02 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 44
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.12-32.2.1.el6uek.x86_64
Operating System: Oracle Linux Server 6.7
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.59 GiB
Name: slc05pqu
ID: QVKQ:7BSH:JQO2:BUQD:FXNH:Q44V:Z5I2:IWL2:WMZN:CNRF:KPJR:ALGA
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 27
 System Time: 2016-03-17T12:16:38.456491337Z
 EventsListeners: 0
 Init SHA1: 200d4f3160fe68bee17595b72766d177b3b32244
 Init Path: /usr/libexec/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Http Proxy: http://`<corporate proxy>`
Https Proxy: http://`<corporate proxy>`

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Oracle VM

**Steps to reproduce the issue:**

Use a Dockfile like the following:

```
FROM oraclelinux:6.7

ARG HTTP_PROXY=<corporate proxy>
ARG HTTPS_PROXY=<corporate proxy>

RUN printf "\nproxy=${HTTP_PROXY}\ndebuglevel=1\nerrorlevel=1\ntimeout=1\n" >> /etc/yum.conf
# The following works so proxy is fine.
# RUN curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
RUN yum -d 10 repolist -v
RUN yum -y -d 10 install unzip
```

**Describe the results you received:**

....
Step 20 : RUN yum -d 10 repolist -v
 ---> Running in 9027781d202e
Not loading "rhnplugin" plugin, as it is disabled
Loading "ulninfo" plugin
Loading "security" plugin
Config time: 0.031
Yum Version: 3.2.29
<docker build terminated>
bash$

docker build terminated.  No error messages from yum repolist.

yum install has similar problem.  docker build just terminated.  The following is the output from yum install:

....
Step 20 : RUN yum -y -d 10 install unzip
 ---> Running in b2999f61df53
Not loading "rhnplugin" plugin, as it is disabled
Loading "ulninfo" plugin
Loading "security" plugin
Running "config" handler for "security" plugin
Config time: 0.034
Running "init" handler for "ulninfo" plugin
Yum Version: 3.2.29
COMMAND: yum -y -d 10 install unzip
Installroot: /
Ext Commands:

   unzip
Reading Local RPMDB
rpmdb time: 0.000
Setting up Install Process
Setting up Package Sacks
<docker build terminated>
bash$

**Describe the results you expected:**

Funny thing is, yum install was successful in the first few builds.  Suddenly, it stops working.  

The same commands work at run time if I create a oraclelinux:6.7 container.

**Additional information you deem important (e.g. issue happens only occasionally):**

What is the fundamental difference between the network access used in docker build and docker container run time?

**Comment by AndrewGuenther** [comment]
Can you comment with your exact docker build command?

**Comment by cpuguy83** [comment]
yum has known issues on overlay.
When this was working were you on a different graph driver?

**Comment by willievu** [comment]
Here is the docker build command:

```
DOCKER_HOST=tcp://<IP>:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/etc/docker
$ docker build .

```

**Comment by willievu** [comment]
I tried to switch to devicemapper and restart docker daemon.  Run docker info to confirm storage change and then build.  Same result.

I also tried vfs.  No luck either.

**Comment by AndrewGuenther** [comment]
If you aren't specifying a proxy at build-time, then what does yum do with that empty config line?

**Comment by willievu** [comment]
As I described previously, The proxy is specified inside the Dockerfile:

```
ARG HTTP_PROXY=http://<proxy host>:<port>
ARG HTTPS_PROXY=http://<proxy host>:<port>

RUN printf "\nproxy=${HTTP_PROXY}\ndebuglevel=1\nerrorlevel=1\ntimeout=1\n" >> /etc/yum.conf
```

Besides, it worked in build time for a little while.  Then, somehow it stops working.  Also, all the same commands work in run time.

**Comment by simskij** [comment]
I'll try this out with fiddler and report back whether the issue still remains.
I find it hard to believe that it does however, as that would have generated a lot more traffic to this issue.

**Comment by simskij** [comment]
Ok, after adding `proxy=<hostname>:<port>` to `/etc/yum.conf` everything works as expected and I'm able to verify that all yums traffic is going through the proxy.

This issue could be closed, @thaJeztah :)

**Comment by thaJeztah** [comment]
Thanks for verifying!
