### ISSUE TITLE
Feature reuqest: Add ALL_PROXY to list of supported variables for Build-time arguments

### ISSUE THREAD

**Issue by otheus** [moby/moby#21319]
In https://github.com/docker/docker/issues/14634, variables were whitelisted to add support for proxying via cURL and other libraries. `ALL_PROXY` should be added to that list. A possible bonus feature is to emulate ALL by adding entries for HTTP, HTTPS, and FTP.

**Comment by thaJeztah** [comment]
We're okay with adding this, would you be interested in opening a pull request?

**Comment by otheus** [comment]
@thaJeztah  Were you asking *me* if I would open a pull request? This isn't code I want to deal with.

**Comment by thaJeztah** [comment]
Discussing this with other maintainers, and we didn't get more requests and actual use-cases for this; users can already add them as a custom `ARG`, so there's no big reason to add this. Let's close for now

**Comment by shrmrf** [comment]
Hi @thaJeztah 

In my company, I'm working with/on Clearlinux and its primary tool is `swupd`. It requires the `ALL_PROXY` environment variable at least I've noticed inside a container environment (it uses `libcurl` and `ALL_PROXY` is one of the [environment variables that `libcurl` understands](https://curl.haxx.se/libcurl/c/libcurl-env.html).

Looking at the popularity of `libcurl` and Clearlinux, it might not be a bad idea to add `ALL_PROXY` to the list of supported-by-default build-time arguments.
