### ISSUE TITLE
Feature request: add names to exposed ports

### ISSUE THREAD

**Issue by davidsonr** [moby/moby#21322]
On some Dockerfiles you can have multiple exposed ports.  For example the selenium-debug one has a port exposed for VNC, RemoteWebDriver.  Others expose more...
It would be good if when we are exposing ports we assign names to them.

**Dockerfile**
EXPOSE 5900 VNC
EXPOSE 4444 REMOTE_WEBDRIVER
EXPOSE 5555 SOME_OTHER_PORT

**command line**
docker port container-name
VNC: 5900/tcp -> 0.0.0.0:32771
REMOTE_WEBDRIVER: 4444/tcp -> 0.0.0.0:32773
SOME_OTHER_PORT: 5555/tcp -> 0.0.0.0:32772

**Comment by justincormack** [comment]
There are already standard port names that could be supported, see http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml or (incomplete) `/etc/services`. Potentially you could select `-p 1022:ssh` for example for `-p 1022:22`. This would work for services with registered ports, like `vnc`.

**Comment by thaJeztah** [comment]
ping @mrjana is this still something to consider?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
