### ISSUE TITLE
Documentation changes for containerd integration

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#21334]
For Docker 1.11, containerd integration (https://github.com/docker/docker/pull/20662)
only brings a minimum amount of user-facing changes.

There _are_ some changes that need to be documented. This is a first inventory
of those changes (more changes may follow).
## ~~Installation from binaries~~

~~Docker Engine no longer is a single binary, and requires 4 binaries to run;
(docker, containerd, containerd-shim, runc).~~

~~We need to update the "installation from binaries" documentation;
https://docs.docker.com/engine/installation/binaries/~~

addressed in https://github.com/docker/docker/pull/21994
## ~~New daemon flag~~

There is a new `--containerd=` option in the daemon that needs to be documented;
- https://github.com/docker/docker/blob/master/docs/reference/commandline/daemon.md
- https://github.com/docker/docker/blob/master/man/docker-daemon.8.md

This was resolved in https://github.com/docker/docker/pull/21576
## ~~Changes in "privileged" containers~~

~~There is a change with `--privileged` and restricted readonly paths. In docker 1.10
there are no restrictions, in 1.11 restrictions are applied but because the user is
privileged they can revert them inside container.~~

For reference; https://github.com/docker/docker/blob/e6573a5d18c3045fb021668f3c7539ffa52696fe/daemon/execdriver/native/template/default_template_linux.go#L86-L98

(resolved by https://github.com/docker/docker/pull/21751)
## ~~Systemd groups~~

~~This is still being worked on, but there's a chance that systemd cgroups won't
work in the initial release, so `--exec-opt native.cgroupdriver=systemd` cannot 
be used.~~

~~If systemd cgroups are not supported, this should be documented. ~~

(resolved in https://github.com/docker/docker/pull/21592)
## Experimental features

Slight user facing change is that in case of a daemon crash, containers will
not die but we will still shut them down on start. In experimental we will
leave them running and reattach upon daemon start.

(currently blocked on https://github.com/docker/docker/issues/21933, we can add documentation
for the experimental features once those are resolved)
## ~~Controlling the containerd daemon~~

~~t.b.d.; the docker daemon automatically takes care of starting/stopping the
containerd daemon. Do we need to describe how to start/stop (and configure?) 
the containerd daemon manually?~~

no changes needed for the regular installation, and binary installation is
updated in https://github.com/docker/docker/pull/21994
## Overview of binaries and their role

t.b.d.; provide an overview of the binaries that are installed, and what their
role is.
## Packagers documentation

https://github.com/docker/docker/blob/master/project/PACKAGERS.md
## Contributors guide

https://github.com/docker/opensource/tree/master/docs

**Comment by jfrazelle** [comment]
why anyone would ever use butts cgroups by default is beyond me

**Comment by mlaventure** [comment]
For containerd daemon workflow documentation, this should probably be in [github.com/docker/containerd](github.com/docker/containerd) directly (and documentation for containerd doesn't exist atm)

**Comment by thaJeztah** [comment]
I think the changes should be all known by now 👍
