### ISSUE TITLE
Docker container exited with System error: stat /system.slice/docker.service: no such file or directory.

### ISSUE THREAD

**Issue by sybrandy** [moby/moby#21444]
Hello,

I got the following output from a docker container that was running in Mesos via Marathon (please forgive the typos as I'm manually copying from one terminal to another :( ):

```
Code: System error

Message: state /system.slice/docker.service: no such file or directory

Frames:

---
0: setupRootfs
Package github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40

---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*libStandardInit)
File: standard_init_linux.go@57

---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242

---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35

---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26

---
5: main
Package: main
File: docker.go@18

---
6: main
Package: runtime
File: proc.go@63

---
7: goexit
Package runtime
File: asm_amd64.s@2232
Error response from daemon: Cannot start container <id>: [8] System error: state /system.slice/docker.service: no such file or directory
```

**Output of `docker version`:**

```
Client/Server:
 Version: 1.9.0
 API version 1.21
 Go version: go1.4.2
 Git commit: 76d6bc9
 OS/Arch: linux/amd64
```

Some additional info:
Kernel version: 3.10.0-123.el7.x86_64
OS: CentOS Linux 7 (Core)
Storage Driver: devicemapper

Any clue as to why this happened?  It seems very out of the blue as this is the first we've seen this issue.  I've seen similar on the internet, but none reference this specific file.

Thanks.

**Comment by HackToday** [comment]
is it possible for you to check with Marathon  guys first, if it is a docker issue ?

**Comment by thaJeztah** [comment]
Can you try configuring docker to use `cgroupfs` instead of `systemd` for cgroups? We changed to `cgroupfs` as a default in https://github.com/docker/docker/pull/17704, because systemd cgroups have a lot of issues, including systemd doing really weird things https://github.com/docker/docker/pull/20633

You can switch to using `cgroupfs` by adding `--exec-opt native.cgroupdriver=cgroupfs` to your daemon options

**Comment by thaJeztah** [comment]
closing because this went stale, and the default is now `cgroupfs`
