### ISSUE TITLE
How to integrate docker-storage-setup better with docker

### ISSUE THREAD

**Issue by rhvgoyal** [moby/moby#21469]
I am opening this issue so that we can have a conversation and figure out how to integrate docker-storage-setup better with docker.

When using devicemapper graphdriver, there are 3 ways to setup thin pool.
- Docker will setup loop devices and create thin pool on thse.
- Pass two block devices to docker and docker will setup thin pool on these
- Setup an lvm thin pool externally and pass it to docker and docker will use it.

First two use cases seem to be well documented but third one is not. I think third use case is important one and should be recommended way of doing things. There are few reasons for that.
- lvm developers actively work and maintain lvm utilities for creating and managing lvm thin pool. If we rely on creating a thin pool ourselves in docker, we will just be doing a catch up job and duplicating functionality.

For example, it is recommended to run thin_chcek on thin pool before it is used to make sure thin pool is in good state. lvm automatically does it when thin pool volume is activated. There is no such check in docker.

lvm has utilities to that one can automatically grow thin pool on need basis as thin pool is getting full. Docker does not have any such thing.

lvm has directions and commands on how to repair thin pool if it gets into bad state. Docker has no such thing.

So while creating thin pool in docker itself is was a good starting point but we now need to start thinking about maintenance and management of thin pool. Users will invariably run into this at some point of time.

docker-storage-setup sets up an lvm thin pool and passes it to docker. 

https://github.com/projectatomic/docker-storage-setup

We ship it in fedora/redhat/centos and docker service is dependent on docker-storage-setup. As soon as docker starts, first it triggers docker-storage-setup, which setups a lvm thin pool and docker uses that thin pool. Now docker does not have to deal with creation or management of thin pool. lvm utilities can take care of growing thin pool automatically and one can refer to `man lvmthin` to repair thin pool if need be.

I see that other developers are now trying to enhance debugging tools like device_too.go to be able to grow thin pool and I think this is not the right direction. Hence I am opening this issue.

**Comment by rhvgoyal** [comment]
Adding more things to device_tool does not seem like a very good idea to me. It is duplicating the functionality of what `dmsetup` and `lvm` can already do and also device_tool.go has no idea if docker is running with different set of parameters.

https://github.com/docker/docker/pull/21389

**Comment by rhvgoyal** [comment]
I can think of two options here.

- Either figure a way out to merge docker-storage-setup like functionality in docker so that based on
  input parameters docker uses lvm commands to create lvm thin pool.

- Or let  the code be in docker-storage-setup and modify documentation to guide how a user can
  make use of it to setup lvm thin pool and pass it to docker.

**Comment by rhvgoyal** [comment]
cc @thaJeztah @cgwalters @rhatdan

**Comment by chenchun** [comment]
Thanks for opening this.

**Comment by thaJeztah** [comment]
Thanks @rhvgoyal, yes, making it easier for people to do the "right" thing when setting up devicemapper would be a good thing. Haven't really thought about what the best way would be to achieve this; including in docker, or keeping as an external tool.

**Comment by thaJeztah** [comment]
ping @cpuguy83 any thoughts on this one?

**Comment by cpuguy83** [comment]
I think it would be nice if the devmapper driver could auto-configure a device based on storage-opts.

**Comment by thaJeztah** [comment]
@cpuguy83 like what David tried on https://github.com/docker/docker/pull/21139 ?

**Comment by thaJeztah** [comment]
devicemapper was deprecated and removed, so this is no longer needed
