### ISSUE TITLE
Log file grows too big due to repeated "Activate/GetCapability" calls to the plugins

### ISSUE THREAD

**Issue by uday-shetty** [moby/moby#21488]
---
## BUG REPORT INFORMATION

/Plugin.Activate, /NetworkDriver.GetCapabilities getting called for every container launch and many other actions

Feb 22 23:03:15 localhost volplugin: time="2016-02-22T23:03:15Z" level=debug msg="Dispatching Activate with "
Feb 22 23:03:15 localhost netplugin: time="Feb 22 23:03:15.094146162" level=info msg="Handling \"activate\" event"
Feb 22 23:03:15 localhost netplugin: time="Feb 22 23:03:15.097994973" level=info msg="Handling \"getCapability\"
 event"
Feb 22 23:03:15 localhost docker: time="2016-02-22T23:03:15.098500652Z" level=error msg="error registering
 driver for netplugin due to Driver already registered for type \"netplugin\""
Feb 22 23:03:15 localhost netplugin: time="Feb 22 23:03:15.100634860" level=info msg="Handling 
\"getIpamCapability\" event"
Feb 22 23:03:15 localhost docker: time="2016-02-22T23:03:15.104438765Z" level=error msg="error registering 
remote ipam driver netplugin due to ipam driver \"netplugin\" already registered"

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical node running CentOS 7.1

Docker version: 1.10.2

**Steps to reproduce the issue:**
1. install Docker Engine
2. Install Docker UCP
3. Configure Contiv plugin
4. create sample containers

**Describe the results you received:**

grep -r "activate" /var/log/messages | wc -l

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan ptal

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
