### ISSUE TITLE
TestDaemonNoSpaceleftOnDeviceError fails on overlay

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#21601]
https://jenkins.dockerproject.org/job/Docker%20Master%20(overlay%20on%20overlay)/2436/console

Also confirmed locally.

**Comment by thaJeztah** [comment]
Labeling with "flakytest" for easier finding, even though it's not a "flaky" test :wink:

**Comment by cpuguy83** [comment]
Adding better logging here: #21634

**Comment by runcom** [comment]
Current failure in CI: https://jenkins.dockerproject.org/job/Docker%20Master%20(overlay%20on%20overlay)/2438/console
```
----------------------------------------------------------------------
FAIL: docker_cli_daemon_test.go:1823: DockerDaemonSuite.TestDaemonNoSpaceleftOnDeviceError

docker_cli_daemon_test.go:1841:
    c.Assert(err, checker.IsNil, check.Commentf(string(out)))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8207c6b60)} ("exit status 32")
... mount: /tmp/testfs.img: failed to setup loop device: No such file or directory



----------------------------------------------------------------------
```
this is also consistent on my fedora box running vfs on overlay:
```
----------------------------------------------------------------------
FAIL: docker_cli_daemon_test.go:1917: DockerDaemonSuite.TestDaemonNoSpaceLeftOnDeviceError

docker_cli_daemon_test.go:1934:
    c.Assert(err, checker.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8204022c0), Stderr:[]uint8(nil)} ("exit status 1")


----------------------------------------------------------------------
```

**Comment by tonistiigi** [comment]
@runcom That jenkins output is from before #22172 . This test passed in jenkins using overlay daemon after #22172 https://jenkins.dockerproject.org/job/Tonis%20Docker%20debugginig/label=overlay/14/console

**Comment by runcom** [comment]
Alright, sorry for that, I may have overlooked. Still doesn't work on my host though :(

**Comment by ddingel** [comment]
This test also failed multiple times on s390 [#1345](https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/1345) but is now back to normal.

**Comment by vdemeester** [comment]
Closing it as duplicate with https://github.com/moby/moby/issues/37277 (as this one is a bit old)
