### ISSUE TITLE
Docker log files have wrong SELinux type

### ISSUE THREAD

**Issue by elyscape** [moby/moby#21672]
**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-0.1.origin.23.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      f97fb16/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-0.1.origin.23.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      f97fb16/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 89
Images: 263
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker_vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 9.802 GB
 Data Space Total: 16.02 GB
 Data Space Available: 6.221 GB
 Metadata Space Used: 6.947 MB
 Metadata Space Total: 16.78 MB
 Metadata Space Available: 9.83 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 7.389 GiB
Name: [REMOVED]
ID: [REMOVED]
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 OpenShift Origin node running on AWS.

**Steps to reproduce the issue:**
1. On a system with SELinux, run something in a container: `docker run busybox echo hi`
2. Find the container ID: `CID="$(docker ps -ql)" ; echo $CID`
3. Find the container's log path: `LOGPATH="$(docker inspect --format '{{ .LogPath }}' $CID)" ; echo $LOGPATH`
4. View the SELinux context of the log file: `ls -Z $LOGPATH`

**Describe the results you received:**

``` shellsession
$ docker run busybox echo hi
hi
$ CID="$(docker ps -ql)" ; echo $CID
3801e5add348
$ LOGPATH="$(docker inspect --format '{{ .LogPath }}' $CID)" ; echo $LOGPATH
/var/lib/docker/containers/3801e5add3488923ac96f74788580c5ad895ed924415814b7fb183ea4c254428/3801e5add3488923ac96f74788580c5ad895ed924415814b7fb183ea4c254428-json.log
$ ls -Z $LOGPATH
-rw-------. root root system_u:object_r:docker_var_lib_t:s0 /var/lib/docker/containers/3801e5add3488923ac96f74788580c5ad895ed924415814b7fb183ea4c254428/3801e5add3488923ac96f74788580c5ad895ed924415814b7fb183ea4c254428-json.log
```

The log file is of type `docker_var_lib_t`.

**Describe the results you expected:**
The log file should be of type `docker_log_t`.

**Additional information you deem important (e.g. issue happens only occasionally):**
Most processes put their logs under `/var/log`, which automatically results in them being assigned the `var_log_t` type. Those that want custom types generally have policy definitions that feed it to [the `logging_log_file` macro](https://github.com/TresysTechnology/refpolicy/blob/f7286189b30bad9edf9a800772d703c54c2ea504/policy/modules/system/logging.if#L3-L50), which (among other things) gives it the `logfile` attribute, and then then use [the `logging_log_filetrans` macro](https://github.com/TresysTechnology/refpolicy/blob/f7286189b30bad9edf9a800772d703c54c2ea504/policy/modules/system/logging.if#L437-L497), which makes objects created by the executable's type inside a directory of type `var_log_t` be automatically assigned the custom type. Policy writers who then want to make a type that can work with any log type can pass their type into [the `logging_read_all_logs` macro](https://github.com/TresysTechnology/refpolicy/blob/f7286189b30bad9edf9a800772d703c54c2ea504/policy/modules/system/logging.if#L823-L842) or one of its siblings to receive the necessary permissions on any log type.

Docker attempts to do this. It [defines a `docker_log_t` type and passes it to `logging_log_file`](https://github.com/docker/docker/blob/v1.10.3/contrib/docker-engine-selinux/docker.te#L48-L49) and later [feeds it to `logging_log_filetrans`](https://github.com/docker/docker/blob/v1.10.3/contrib/docker-engine-selinux/docker.te#L97). Unfortunately, Docker puts a given container's logs in `/var/lib/docker/containers/$CONTAINER_ID/`, which has type `docker_var_lib_t`. As such, the condition on `logging_log_filetrans` that the file be placed inside a directory of type `var_log_t` is not met, and the log files inherit their parent directory's type of `docker_var_lib_t`.

This causes problems when trying to make an SELinux type under which to run a container with a tool like Logstash or Fluentd to collect Docker logs. If you try to [create a new type to read logs](https://www.projectatomic.io/blog/2016/03/selinux-and-docker-part-2/), the new type is (sensibly) capable of reading `docker_log_t` files but unable to read `docker_var_lib_t` files. Since, however, Docker's log files are created with the latter type, the new type is denied access [unless you also grant it access to `docker_var_lib_t`](https://github.com/openshift/origin-aggregated-logging/issues/89#issuecomment-203260654). This is less than ideal, as it provides wider read access than is necessary.

In theory, this could be fixed by adding another file transition, something like this:

```
filetrans_pattern(docker_t, docker_var_lib_t, docker_log_t, file)
```

Unfortunately, this would result in all files created by a `docker_t` process inside a `docker_var_lib_t` direcetory being assigned type `docker_log_t`, which is clearly wrong. A file name transition could work:

```
filetrans_pattern(docker_t, docker_var_lib_t, docker_log_t, file, "*-json.log")
```

If not for [this problem](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/sec-file-name-transition.html):

> Note that file name transition uses an exact match done by the `strcmp()` function. Use of regular expressions or wildcard characters is not considered.

So that doesn't work either. It would be an option if the log file were always named `json.log`, but it's not, and some preliminary experimentation on my part indicates that attempting to change to that would cause a lot of breakage both in downstream projects that rely on Docker's logs without explicitly querying for the `LogPath` (e.g. [Kubernetes](https://github.com/kubernetes/kubernetes/blob/v1.2.0/pkg/kubelet/dockertools/manager.go#L1537)) and in Docker's own `docker log` command when used on containers created before the change.

As such, it seems like the best solution at this point is to simply fix the label on log files immediately after creation.

**Comment by thaJeztah** [comment]
The files inside `/var/lib/docker`, including the logs, are not intended to be used by external tools, so I don't think things should be changed to facilitate that. Logging plugins were added to Docker a while back; https://docs.docker.com/engine/admin/logging/overview/, including a Fluentd logging driver; https://docs.docker.com/engine/admin/logging/fluentd/.

Perhaps I'm misunderstanding the use case here

**Comment by elyscape** [comment]
Kubernetes creates symlinks in `/var/lib/containers` that point at the log files.

**Comment by calavera** [comment]
Unfortunately, we cannot control what other projects do with the host filesystem. I think the tag is correct, so I'm going to say that this is not a bug.

**Comment by AkihiroSuda** [comment]
I'm closing this.

If this is still an issue, this should should be discussed in https://github.com/containers/container-selinux
