### ISSUE TITLE
1.8.2 => 1.10 save-load breaks

### ISSUE THREAD

**Issue by chx** [moby/moby#21757]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 47
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
```

**Steps to reproduce the issue:**
1. docker save on an  Version:      1.8.2
2. docker load on the machine described above

**Describe the results you received:**

Error response from daemon: open /var/lib/docker/tmp/docker-import-944635007/bin/json: no such file or directory

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by tonistiigi** [comment]
I tested this with busybox and redis and didn't have any issues. So it looks like it is specific to your images. Can you provide more details on how to reproduce.

**Comment by thaJeztah** [comment]
@tonitiigi would the tar of the image itself help you? (if it can be shared)?

**Comment by chx** [comment]
Sure it can be shared, it's built from http://github.com/drupalhu/bot.drupal.hu

**Comment by tonistiigi** [comment]
This image doesn't build for me anymore. Probably it's too old `Err http://ftp.debian.org squeeze/main amd64 Packages`.

**Comment by chx** [comment]
That is certainly possible. See above for the image.

**Comment by tianon** [comment]
Dunno if it'll still reproduce the issue properly, but you might be able to
build it successfully if you swap the "FROM" to be "FROM
debian/eol:squeeze" (https://hub.docker.com/r/debian/eol/).

**Comment by AkihiroSuda** [comment]
These version are no longer supported. Let me close this issue.
