### ISSUE TITLE
Docker Container Connected to Multiple Bridge Networks is not Accessible Externally

### ISSUE THREAD

**Issue by josephearl** [moby/moby#21798]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-25804197-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.609 GB
 Data Space Total: 107.4 GB
 Data Space Available: 7.427 GB
 Metadata Space Used: 13.59 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389 GiB
Name: ip-172-31-30-202.eu-central-1.compute.internal
ID: G4GR:O5ZR:LJTX:USGA:EUG3:5CXK:RSAY:VCOX:QFRY:XPLS:A62C:VJ7Q
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=amazonec2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS.

**Steps to reproduce the issue:**
1. Create a compose file with 2 containers, and 3 networks
2. Connect container 1 to only 1 network and expose a port
3. Connect container 2 to all 3 networks and expose a port

**Describe the results you received:**

Container 1 is accessible externally. Container 2 is not.
If I SSH onto the AWS machine then I am able to access container 2 on the exposed port, but not externally. I have verified AWS networking rules.

**Describe the results you expected:**

Both containers are accessible. The number of Docker networks connected to should not affect exposing ports.

**Additional information you deem important (e.g. issue happens only occasionally):**

If you change container 2 to only connect to 1 network, then it is accessible externally.

Compose file example:

```
version: '2'
services:
  service-a:
    ports:
      - "8091:8091"
    networks:
      - network-a
  service-b:
    ports:
      - "8092:8092"
    networks:
      - network-a
      - network-b
      - network-c
networks:
  network-a:
  network-b:
  network-c:
```

**Comment by JosephEarl** [comment]
Possible duplicate of #21741

**Comment by steve-gray** [comment]
Hey,

@cpuguy83 -Requesting a re-open. The other issue is mitigated by means of lexicographically sorting the networks and having the first be the one that is the one that's touchable remotely. To this end I've renamed my networks as external, fabric and services - but nothing on external gets mapped. 

What I'm hitting is the same issue, but with a container that is on both external and fabric not being able to communicate outside:

`networks:
  external:
    driver: bridge
  fabric:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
  services:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
`

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by aboch** [comment]
@steve-gray Trying to gather more information. Can you provide your compose file. Thanks.

**Comment by ryneeverett** [comment]
```yml
version: '2'
services:
  whoami:
    image: jwilder/whoami
    networks:
      - net1
      - net2
    ports:
      - "80:8000"

networks:
  net1:
    driver: bridge
  net2:
    driver: bridge
```

I tested this with a [coreos-vagrant](https://github.com/coreos/coreos-vagrant/) box with CoreOS-1010.5.0 and docker 1.10.3.

1) On the host 
```console
(core-os) $ docker-compose up 
```

2) Locally:
```console
(local) $ curl core-01
curl: (7) Failed to connect to core-01 port 80: Connection timed out
```

3) On the host:
```console
(core-os) $ docker network disconnect core_net1 core_whoami_1
```

4) Locally:
```console
(local) $ curl core-01
I'm 14c5e86ca170
```

**Comment by akerouanton** [comment]
This ticket went stale and both issues reported by @josephearl and @ryneeverett were fixed, so let me close this.
