### ISSUE TITLE
Add removal of volume driver plugins

### ISSUE THREAD

**Issue by holgerreif** [moby/moby#21920]
### Situation

The registration / deregistration is incomplete. The plugin starts the  registration process by with creating the unix socket  `/run/docker/plugins/<drivername>.sock`. Docker engine acknowledges the registration with the [handshake API](https://docs.docker.com/engine/extend/plugin_api/#handshake-api) calling `/Plugin.Activate`.  Then the plugin knows registration has completed.
This activation is done automatically when the plugin is [first needed](https://docs.docker.com/engine/extend/plugin_api/#plugin-activation).
### Drawbacks
1. It might take some time to initialise the plugin. This will increase startup time for the container first using this driver.
2. It is not possible to update the plugin even if it's currently not in use [w/o stopping docker daemon](https://docs.docker.com/engine/extend/plugin_api/#plugin-lifecycle).
3. It is not possible to remove a plugin. If you do so (stop the plugin, remove the plugin socket) many `docker volume` commands will [timout](https://docs.docker.com/engine/extend/plugin_api/#plugin-retries). The only way is to restart docker daemon.
### Proposal
1. Add a command `docker plugin-start <drivername>`. This activates the plugin without actually using it. This is optional, on-demand activation is still possible.
2. Add a `/Plugin.Deactivate` API call indicating to the plugin it is not longer in use.
3. Add a command `docker plugin-stop <drivername>`. This deactivates the plugin and forgets about the driver (as if not beeing activated). Of course, this would fail if still volumes managed by this driver exist.
4. Add the option `docker volume rm -d <driver>`. This  would remove all volumes managed by this driver which are not in use by a container.

As further lifecycle elements I thouhgt about `/Plugin.Pause` and `/Plugin.Unpause` together with corresponding `docker plugin-<...>` commands. A paused plugin cannot be used to manage (create, rm, ls, mount) volumes, however existing volumes can be further used. This would allow to take the plugin in maintainance mode (if there is something in backend) or allow for the update of a plugin (the plugin would have to preserve state of it's volumes; the updated plugin would accept activation with `/Plugin.Unpause`).
However, it is not clear whether there is a real use case for it.
### Advantages

The lifecycle of a plugin gets more complete, plugin usage becomes more flexible and more deserves the term _cycle_.
### Notes
1. The proposal was first targeted on volume driver plugins it could be useful for other nplugin types as well.
2. While this proposal provides a way to take a plugin out of use by docker engine, it is still the responsibility of an external entity (i.e. admin) to possibly stop and unload the plugin.

**Comment by coolljt0725** [comment]
There is a similar issue #20363 :-)

**Comment by holgerreif** [comment]
@coolljt0725 Thanks for cross linking.

However, while #20363 is a more general (should I say philosophical) discussion (that yet has to find consensus ) about how engine should be able to handle all the plugin infrastructure more or less automatically, my proposal targets more the smaller case to support an admin wants to do things manually. 

That beeing said I'm open for a BIG solution covering my ideas as well. Hopefully that won't take forever ;-)

**Comment by cpuguy83** [comment]
It's probably safe to remove a registered volume driver if there is a timeout issue.

**Comment by holgerreif** [comment]
Well even if I remove `/run/docker/plugins/<drivername>.sock` docker engine still thinks it has the driver registered and runs into timeouts.

**Comment by cpuguy83** [comment]
@holgerreif I mean it's probably ok to de-register it from the engine on timeout.

**Comment by holgerreif** [comment]
Okay, you mean implicit deregistration. Fine, as long as you forget about the volumes handled by this driver too. But what about volumes currently in use by containers? Remember them? And what do we do with the `Umount` call to a non-existing driver then?

Anyway, if we find answers to those questions deregistration on timeout is an acceptable workaround. However as a long term solution I'd prefer an explicit lifecycle declaration.

**Comment by cpuguy83** [comment]
@holgerreif The driver should be automatically re-registered once something requires it.
If the driver needs to be up for the volumes to work, then it's likely already broken before we actually de-register the driver in the daemon.
We shouldn't need to remove the existing volumes themselves.

**Comment by cpuguy83** [comment]
Driver registration is an optimization.

**Comment by holgerreif** [comment]
@cpuguy83  automatic re-registration gave the answer to my questions in [comment](https://github.com/docker/docker/issues/21920#issuecomment-208403610).

But it opens up new questions:
   * Should a create or mount fail if the re-registration of the driver fails? I guess yes, same behaviour as with a non-existent driver.
   * Should the umount or remove fail if the re-registration of the driver fails? I guess no, it should be ignored silently (with respect to the client's request) and possibly logged on the host.

**Comment by holgerreif** [comment]
One more consern:
   * If the `volume create` had driver specific options and you call `Plugin.Mount` then plugin might not know about those opts and mount fails. 

Actually it's a cornerstone but one should keep this in mind.

**Comment by cpuguy83** [comment]
@holgerreif Yes, I agree with the create opts, but it's a problem with or without registration changes.

Yes, I'd expect create/mount/etc all to fail if the driver is not up.
Errors should not be ignored since it's a legitimate problem that will likely cause other errors (like removing a container when the volume couldn't be unmounted.

**Comment by holgerreif** [comment]
@cpuguy83 I did some test on how 1.10. behaves when the volume plugin was killed in several situatuations and sometimes restarted. The overall behaviour is overall quite failure forgiving. The deregistration of the volume driver would not change the behaviour in general, just eliminate unnecessery timeouts, So I would vote for this.

Should I make a separate issue for "automatic deregistration of failed plugins"?

**Comment by cpuguy83** [comment]
@holgerreif I'd say let's hijack this one, because anything else in here is really going to be related to the aforementioned issue with enhancing plugin support.

**Comment by holgerreif** [comment]
Okay, but don"t close the issue after the first quick enhancement!

**Comment by LK4D4** [comment]
#20363 was closed.
@cpuguy83 @anusha-ragunathan @holgerreif is this still an issue?

**Comment by cpuguy83** [comment]
I'm not sure, will have to check how the volume store handles the driver list in this case.

**Comment by TJC** [comment]
I'm hitting this now when trying to remove the docker-volume-netshare plugin. After stopping it, `docker volume ls` hangs until it times out trying to connect to the plugin.

Is there a way to manually sort this out in the meantime?

**Comment by cpuguy83** [comment]
Docker 1.13 has support for first-class plugins.
There's probably some enhancements that can be made on plugin ref-counting, but we'll find out when it's in the wild.

In the meantime I think we can close this since plugins should move to the v2 interface.

**Comment by thaJeztah** [comment]
closing per the discussion above
