### ISSUE TITLE
Container start fails, but volume remains mounted

### ISSUE THREAD

**Issue by holgerreif** [moby/moby#21921]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v3.16+20140829
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local nfs cifs
 Network: null host bridge
Kernel Version: 3.12.53-60.30-default
Operating System: SUSE Linux Enterprise Server 12 SP1
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.728 GiB
Name: SOMENAME
ID: KTVH:NB4H:RWZH:7MEA:ZYBF:EIHE:GFLD:T7ZO:47Z7:KWSK:NZCE:SKU4
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It is a virtual machine.

**Steps to reproduce the issue:**
1. provide a non-empty cifs share where you don't have permissions to `chmod` the share's root.
2. run `docker volume create --name host/share`
3. run `docker run -v host/share`

**Describe the results you received:**

```
$ docker run -it -v  host/share:/mnt --rm alpine ash
DEBU[0027] Host path for host/share is at /var/lib/docker-volumes/netshare/cifs/host/share
INFO[0027] Mount: host/share, map[]
INFO[0027] Mounting CIFS volume //host/share on /var/lib/docker-volumes/netshare/cifs/host/share
DEBU[0027] GetCreds: host=host, netrc=<nil>
DEBU[0027] Executing: mount -t cifs -o username=username,password=****,rw //host/share /var/lib/docker-volumes/netshare/cifs/host/share

docker: Error response from daemon: chmod /var/lib/docker-volumes/netshare/cifs/host/share: permission denied.
See 'docker run --help'.
$ docker volume ls
DEBU[0327] Entering List: { map[]}
DRIVER              VOLUME NAME
cifs                host/share
```

The failing `chmod` probably comes from `func copyOwnership()` of [docker/docker container/container_unix.go](https://github.com/docker/docker/blob/master/container/container_unix.go). 

Furthermore the volume remains mounted, which makes it impossible to `docker volume rm`.

**Describe the results you expected:**
1. Since the volume has data in it, I think the function `CopyImagePathContent` (calling `copyExistingContents` calling `copyOwnership` should not be called.
2. Even if there is a problem, the volume should be unmounted after the failed copying.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Would you like to investigate further?
The CopyImagePathContent indeed should not be run if the volume is populated.

**Comment by holgerreif** [comment]
Yes, I'll do anything for what I don't need a working go dev environment ;-)
Just tell me.

**Comment by erikh** [comment]
Hi. I ran into this today implementing NFS support.

The problem in my case is that root UID/GID mapping is remapped to `nobody` on NFS4 by default. I investigated several kernel options to turn this off and remap the UID/GID, but unfortunately that is not possible on the client side (which is the important bit here).

To support this, I think the chmod needs to be a toggle somehow, or docker should log or warn (at `docker run` time) instead of erroring out.

Deep integration with the volume drivers (e.g., passing back a payload of `no chmod` in some fashion so volume drivers can control this behavior) would be really really really nice.

I can assist with parts of the patches if that's necessary.

**Comment by cpuguy83** [comment]
You can already provide a `nocopy` option.
I don't think it makes sense to skip a chmod since the chmod is happening so that the data is owned by the same user as the data in the image. There's little/no benefit to having docker copy data that differs from the image content.

**Comment by erikh** [comment]
Unfortunately, with NFS (and probably any kind of network mount that 
incorporates POSIX permissions) you can't chmod the root of the mount.

How do I access the nocopy option? I'm not seeing it in docker volume or 
run commands.

**Comment by cpuguy83** [comment]
`docker run -v foo:/bar:nocopy`

**Comment by erikh** [comment]
Ah. Thank you!

**Comment by erikh** [comment]
Ok, this is working for my use-cases, but it'd be nice to not have to 
expect users to supply this option if the volume driver knows it needs 
it. I hope that makes sense; this'll need to be applied to all 
containers that take a NFS mount. Since we're supporting multiple 
backends now (all of the others do not need this support), it would be 
really nice if I could provide a consistent UX to my consumers across 
any storage system. I think others that provide NFS options will need 
this too.

If you're comfortable with it, I could supply this patch.

-Erik

**Comment by cpuguy83** [comment]
I have a patch for asking the driver for capabilities, could incorporate chmod in this capability set (after merge)... but we'll have to assume chmod is possible by default.

**Comment by erikh** [comment]
Definitely. As long as I can say, "this mount is a nocopy mount" on the 
return path for `run -v`, that would be a huge boon.

Can I help with the patch?

-Erik

**Comment by cpuguy83** [comment]
#22077 implements Capabilities on volume drivers

**Comment by holgerreif** [comment]
@erikh you actually hijacked my issue ;-)

While we are experiencing the same root cause (you cannot chmod() the root of the network mounted volume) our demands differ: You are concerned about getting rid of the error itself, I'm concerned about the  behaviour of docker enginge not handling the failure well.

@cpuguy83 how do we proceed with getting rid of mounted volume in case of failure? Could probably be another container start failure as well, not only a volume related reason one.

**Comment by thaJeztah** [comment]
@cpuguy83 @holgerreif is this still an issue?

**Comment by cpuguy83** [comment]
I do believe the issue with volume being unmounted is fixed.
@holgerreif Can you check on 1.13-rc2?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
