### ISSUE TITLE
docker daemon tries to bind to ip from --cluster-advertise

### ISSUE THREAD

**Issue by vikstrous** [moby/moby#22008]
When UCP sets up overlay networking on AWS it uses its `--host-address` parameter as the value of `--cluster-advertise` for the docker daemon. If the `--host-address` is set to the external IP of the AWS instance, the value of `--cluster-advertise` will be too. When the daemon starts it tries to bind on this IP, but it's not in the list of IPs known to the operating system because AWS has a 1:1 NAT that gives the instance a different internal IP address instead. There should be another flag, ex. `--cluster-listen-ip` that I can set to 0.0.0.0 or the internal IP to make this set up work. For example, etcd has `--listen-xxx-urls` flags and rethinkdb has `--bind`.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Mon Apr 11 21:53:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Mon Apr 11 21:53:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 18
Server Version: 1.11.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay null host bridge
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-172-31-36-121
ID: XFIT:N2GL:FZR2:JQ4Q:GUOH:JOJM:VDTY:CNXH:4GGO:B2H6:U5JK:PZRF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://x.x.x.x:12379
Cluster advertise: x.x.x.x:12376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
See above

**Describe the results you received:**
See above

**Describe the results you expected:**
See above

**Additional information you deem important (e.g. issue happens only occasionally):**
The error that the daemon prints:

```
ERRO[0010] Multi-Host overlay networking requires cluster-advertise(x.x.x.x) to be configured with a local ip-address that is reachable within the cluster 
ERRO[0010] initializing serf instance failed: failed to create cluster node: Failed to start TCP listener. Err: listen tcp x.x.x.x:7946: bind: cannot assign requested address 
```

**Comment by tectoro** [comment]
Hello there, I have a similar issue which I posted in #22087

I would like to add here, if the OS is not aware of the elastic ip (public ip), how can docker bind to that IP?

I was trying to achieve the same thing, finally succeeded by using --cluster-advertise=eth0:2375
This advertises the host on the network using AWS internal IP. Also ports exposed will be accessible over  public (elastic) ip.

**Comment by yongtang** [comment]
I can take a look at this issue. It seems that changes might be needed in libnetwork side. #dibs

**Comment by yongtang** [comment]
@vikstrous @tectoro I created a PR #22663 to add an additional flag of `--cluster-listen` so that the bind IP could be different from the advertised IP. Please take a look and let me know if there are any issues.

**Comment by vikstrous** [comment]
Awesome! That seems like the right solution. I don't know the code itself.

**Comment by thaJeztah** [comment]
let me close this one, as (IIUC) this was for the legacy overlay networks, which has been deprecated and removed
