### ISSUE TITLE
kpartx hangs on semap() call and pushes the loop device to the DM table

### ISSUE THREAD

**Issue by andrey01** [moby/moby#22025]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 11 Apr 2016 14:15:45 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 11 Apr 2016 14:15:45 +1200
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 108
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-18-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.488 GiB
Name: [redacted]
ID: [redacted]
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- physical box
- `/usr/bin/docker daemon -H fd:// --storage-driver=overlay --icc=false`

**Steps to reproduce the issue:**
1. start the container

 `docker run -ti --rm --privileged opensuse /bin/bash`
2. Install kpartx

`zypper in -y kpartx`
3. Allocate some file

`fallocate -l50M /tmp/file50M.raw`
4. Mount it as loop device

`losetup /dev/loop1 /tmp/file50M.raw`
5. Launch kpartx

`strace /sbin/kpartx -sa /dev/loop1`
6. Try remove loop device

`losetup -d /dev/loop1`

**Describe the results you received:**
- kpartx hangs on `semap()` call

```
# strace /sbin/kpartx -sa /dev/loop1
... ... ...
semop(229383, {{0, 1, 0}}, 1)           = 0
semctl(229383, 0, GETVAL, 0x7f069d59a7c7) = 2
ioctl(3, DM_DEV_CREATE, 0x189c790)      = 0
ioctl(3, DM_TABLE_LOAD, 0x189c790)      = 0
ioctl(3, DM_DEV_SUSPEND, 0x189c660)     = 0
semget(0xd4d6646, 1, 0)                 = 229383
semctl(229383, 0, GETVAL, 0x800)        = 2
semop(229383, {{0, -1, IPC_NOWAIT}}, 1) = 0
semop(229383, {{0, 0, 0}}, 1
```

**Describe the results you expected:**
I expected two things:
- `kpartx` shall not hang;
- `losetup -d /dev/loop1` to always work;

**Additional information you deem important (e.g. issue happens only occasionally):**
Prior to running `kpartx` I can see the following points are true:
- `dmsetup table` does not list `loop1p1`
- `losetup -d /dev/loop1` works well, the device then is not listed on `losetup -a` as expected

After running the `kpartx` which then hangs (and even after I kill its PID), I observe the observations now are following:
- `dmsetup table` does list `loop1p1`
- `losetup -d /dev/loop1` exits with 0 code, however the device is still present on `losetup -a`

**Comment by andrey01** [comment]
I've found two things, one is that if I run `udevd &`, then `kpartx` does not hang and seems like there is some workaround already out there `https://github.com/NaohiroTamura/diskimage-builder/blob/master/elements/vm/block-device.d/10-partition#L39`

I am wondering about the Docker Devs opinion :-)

**Comment by andrey01** [comment]
With the `centos:7` image I did not experience this behavior as with the `opensuse` Docker image.

`docker run -ti --rm --privileged centos:7 /bin/bash`

```
yum install -y strace
fallocate -l50M /root/bbb
losetup /dev/loop1 /root/bbb
strace /sbin/kpartx -sa /dev/loop1
```

`kpartx-0.4.9-85.el7.x86_64`

```
[root@043f2e588f21 /]# strace /sbin/kpartx -sa /dev/loop1 2>&1|grep sem
[root@043f2e588f21 /]# strace /sbin/kpartx -sa /dev/loop1 2>&1|grep ioctl
ioctl(3, DM_VERSION, 0x22509f0)         = 0
ioctl(3, DM_LIST_VERSIONS, 0x2250910)   = 0
ioctl(3, DM_DEV_STATUS, 0x2250910)      = -1 ENXIO (No such device or address)
ioctl(3, DM_DEV_STATUS, 0x2250910)      = -1 ENXIO (No such device or address)
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKGETSIZE64, 52428800)        = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKGETSIZE64, 52428800)        = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKGETSIZE64, 52428800)        = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(4, BLKSSZGET, 512)                = 0
ioctl(3, DM_DEV_STATUS, 0x22515c0)      = -1 ENXIO (No such device or address)
ioctl(4, 0x81784401, 0x7ffc2f5fb300)    = -1 EINVAL (Invalid argument)
```

**Comment by lool** [comment]
Hi,

kpartx calls libdevicemapper to get the UUID of the loop device that was created. When run in sync mode (-s), libdevmapper will wait for udev to signal that the device was created properly. I suspect your host system never reaches this point, perhaps it's lacking the dmsetup udev scripts?

NB: I recently faced a similar issue on a non-docker platform and found this bug report with the same symptoms - https://lists.ubuntu.com/archives/snapcraft/2016-September/000893.html

Cheers,
- Loïc Minier

**Comment by thaJeztah** [comment]
Device mapper without udev sync support is indeed known to cause issues, which is a reason for docker itself to (by default) refuse to use it if udev sync is not available (see https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L1715-L1726)

As far as I know, udev sync never works when running inside a container (and on top of a layered filesystem), so I suspect this issue is related to that. I'm not sure if this can be solved

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated and removed, so closing this ticket.
