### ISSUE TITLE
compose 1.5 failed to start container: containerd: container did not start before the specified timeout

### ISSUE THREAD

**Issue by ahmetb** [moby/moby#22053]
When I immediately run `docker-compose up` after restarting docker, I get the following error in `docker-compose@1.5` running against `docker-engine@1.11.0`:

```
$ /usr/local/bin/docker-compose -p compose -f /etc/docker/compose/docker-compose.yml up -d
Pulling web (nginx:latest)...
Creating compose_web_1
rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"
```

(exit code=1)

Next time I run it myself manually, it works. (For the first time it gets executed in an headless startup script and fails.)

Also please note that **this is intermittent** and I can't consistently repro.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-33-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.637 GiB
Name: dockerextensiontest-3
ID: HLNH:UION:TVUX:WEN2:ZV4X:LCMV:SUP2:7SQS:6BAM:643N:PTID:LQ4O
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. `wget -qO- https://get.docker.com | sh`
2. set docker-engine opts and restart `service restart docker`
3. (and rapidly after) `docker-compose -f compose.yml up -d`
3. Error says `containerd: container did not start before the specified timeout`

**Comment by thaJeztah** [comment]
/cc @tonistiigi @mlaventure 

Thanks @ahmetalpbalkan

**Comment by thaJeztah** [comment]
@ahmetalpbalkan could you provide your docker-compose.yml to see if we can reproduce? Also wondering if docker-compose 1.7 also has this issue?

**Comment by ahmetalpbalkan** [comment]
@thaJeztah I upgraded to docker-compose 1.6.2, the issue still persists and is intermittent.

my compose file is roughly like:

```
web:
  image: nginx
  restart: always
  ports:
  - 80:80
```

**Comment by lmillott** [comment]
I'm seeing the same issue intermittently (about 10% of the time). Some version data:
**docker version:**
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

**docker-compose version:**
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**DockerExtension version:**
Microsoft.Azure.Extensions.DockerExtension-1.1.1604142300

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
