### ISSUE TITLE
Overlay networking issues - AWS

### ISSUE THREAD

**Issue by tectoro** [moby/moby#22087]
**Output of `docker version`:**

```
Docker version 1.10.0, build 590d5108
```

**Output of `docker info`:**

```
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 122
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 326
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host overlay bridge null
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: ip-XXX-XXX-XXX-XXX
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS - Ubuntu 14.04

**Steps to reproduce the issue:**
1. Create AWS Ubuntu 14.04 instance. Assign an elastic IP.
2. Create Ubuntu 14.04 instance on any other provider e.g our own data center
3. Run consul on an external server. Use cluster-advertise on both instances to connect to this consul. AWS instance advertises over network using eth0 (which is internal IP of the instance).
4. Create an overlay network
5. Create a container on AWS instance using this network e.g. nginx
6. Create a container on the other instance using this network e.g. alpine

**Describe the results you received:**

From the alpine node, nginx hostname is resolved to an IP in the overlay network, which is good. But we can not ping or access ports of the nginx container.

**Describe the results you expected:**

Nginx container should be reachable from alpine in the above case

**Additional information you deem important (e.g. issue happens only occasionally):**

The same scenario works absolutely fine if we run both instances on the other providers who have public IPs directly assigned to one of the networks interfaces on the host.

Since we are using elastic IP mapping in AWS, this is not working. Since we are using internal AWS IPs for advertising, overlay networking works fine between 2 AWS instances but not with other providers.

Can someone please shed some light on this?

**Comment by doronp** [comment]
@tectoro While I am not sure what is the planed scope of the overlay support in such distributed cases:

> Containers can only communicate within networks but not across networks

see:
https://docs.docker.com/engine/userguide/networking/dockernetworks/

for your case I think there are some workarounds:

1 - Consider using VPC
https://aws.amazon.com/vpc/
and eve:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html

2 - Did you associate the Elastic IP with the primary network interface (eth0)?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#working-with-eips

Hope this helps

**Comment by pilgrim2go** [comment]
I have the same issue. 
This case, overlay network doesn't work with 2 instances in AWS even.
