### ISSUE TITLE
Windows: failed to mount nested bind-mounts / volumes

### ISSUE THREAD

**Issue by hcoona** [moby/moby#22141]
**Output of `docker version`:**

```
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 18
Images: 2
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 18c9fe0
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network:
Kernel Version: 10.0 10586 (10586.212.amd64fre.th2_release_sec.160328-1908)
Operating System: Windows Server 2016 Technical Preview 4
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.997 GiB
Name: SHUAIZ-DOCKER
ID: OPOY:ZUOZ:UUEP:ICPZ:GAC7:XDXJ:JK24:QTN6:5ERT:ZRGX:T6Y2:D3ML
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 16
 System Time: 2016-04-19T15:06:10.1563151+08:00
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\docker
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016 TP4, physical machine

**Steps to reproduce the issue:**
1. mkdir C:\parent\child\
2. docker.exe run -v C:\parent -v C:\parent\child windowsservercore cmd

**Describe the results you received:**

```
docker: Error response from daemon: Cannot start container c582bb9aa568aa44e4169d10f9e1d158cd987c6da6d57f31ef9c50d0b156d438: HCSShim::CreateComputeSystem - Win32 API call returned error r1=2147942403 err=The system cannot find the path specified. id=c582bb9aa568aa44e4169d10f9e1d158cd987c6da6d57f31ef9c50d0b156d438 configuration={"SystemType":"Container","Name":"c582bb9aa568aa44e4169d10f9e1d158cd987c6da6d57f31ef9c50d0b156d438","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{0ef2a5f6-fae4-11e5-b971-00155d7a5217}","Devices":[{"DeviceType":"Network","Connection":{"NetworkName":"Virtual Switch","EnableNat":false,"Nat":{"Name":"ContainerNAT","PortBindings":null}},"Settings":null}],"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\c582bb9aa568aa44e4169d10f9e1d158cd987c6da6d57f31ef9c50d0b156d438","Layers":[{"ID":"84ea5d62-64ed-574d-a0b6-2d19ec831a27","Path":"C:\\ProgramData\\Microsoft\\Windows\\Images\\CN=Microsoft_WindowsServerCore_10.0.10586.0"}],"HostName":"c582bb9aa568","MappedDirectories":[{"HostPath":"C:\\ProgramData\\docker\\volumes\\cfac65b003b3d135ef6445487ad6c14ee8035b2a97173b5f2b0ebfcf8be3a435\\_data","ContainerPath":"c:\\parent","ReadOnly":false},{"HostPath":"C:\\ProgramData\\docker\\volumes\\58b5b2344669be74a14311bf59541831445d51eea02bbb2472e86cdce0cc536f\\_data","ContainerPath":"c:\\parent\\child","ReadOnly":false}],"SandboxPath":"","HvPartition":false}.
```

**Describe the results you expected:**
Mount C:\parent and ignore mounting C:\parent\child

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
@jhowardmsft is this something that's addressed in TP5?

**Comment by jhowardmsft** [comment]
No. I doubt it can be fixed with the current design of the Windows internals.

**Comment by thaJeztah** [comment]
@jhowardmsft perhaps we should add a detection; if paths overlap, error out before the container is created/started (with a more descriptive error). Think that's doable?

**Comment by hcoona** [comment]
Maybe we can detect thec overlap and just ignore the deeper path.

On 周二, 4月 19, 2016 at 11:35 下午, Sebastiaan van Stijn <notifications@github.com> wrote:
@jhowardmsft [https://github.com/jhowardmsft] perhaps we should add a detection; if paths overlap, error out before the container is created/started (with a more descriptive error). Think that's doable?

**Comment by hcoona** [comment]
Ahh, ignore my previous post, maybe user want to mount another irrelative folder to the overlapping container path.

On 周二, 4月 19, 2016 at 11:40 下午, satan.student@gmail.com <satan.student@gmail.com> wrote:
Maybe we can detect thec overlap and just ignore the deeper path.

On 周二, 4月 19, 2016 at 11:35 下午, Sebastiaan van Stijn <notifications@github.com> wrote:
@jhowardmsft [https://github.com/jhowardmsft] perhaps we should add a detection; if paths overlap, error out before the container is created/started (with a more descriptive error). Think that's doable?

**Comment by thaJeztah** [comment]
Yes, we should not silently ignore things, better to error out than to silently ignore

**Comment by thaJeztah** [comment]
ping @jhowardmsft is this still something to be improved? (error message?)

**Comment by jhowardmsft** [comment]
No plans to....

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
