### ISSUE TITLE
Internet connectivity drops in random container.

### ISSUE THREAD

**Issue by byrnedo** [moby/moby#22144]
We're seeing regular drop in network connectivity from within one container at a time in a swarm cluster. This has been happening since we upgraded to 1.11. It doesn't seem to effect other containers in the cluster.

It's a 3 node swarm with a 3 node consul group. Dns is provided by consul agents on each docker node.

Restarting the culprit container fixes the issue temporarily.

We notice that the container effected has a hard time contacting nodes on the same **overlay** network, or the outside world.

Checks done:

```
dig <someservice>.service.consul
```

```
ping www.google.com
```

Both fail to respond or at best respond after quite a while.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64
ubuntu@aws-prod-master:~$ docker info
Containers: 32
 Running: 30
 Paused: 0
 Stopped: 2
Images: 107
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 aws-prod-master: 10.0.11.18:2376
  └ Status: Healthy
  └ Containers: 8
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.016 GiB
  └ Labels: ec2.instance.type.t2.micro=true, executiondriver=, kernelversion=4.2.0-35-generic, nodeindex=0, operatingsystem=Ubuntu 14.04.4 LTS, provider=generic, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T08:43:53Z
 aws-prod-node-1: 10.0.15.232:2376
  └ Status: Healthy
  └ Containers: 12
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.05 GiB
  └ Labels: ec2.instance.type.t2.small=true, executiondriver=, kernelversion=4.2.0-35-generic, nodeindex=1, operatingsystem=Ubuntu 14.04.4 LTS, provider=generic, role.infra=true, role.service=true, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T08:43:53Z
 aws-prod-node-2: 10.0.0.200:2376
  └ Status: Healthy
  └ Containers: 12
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.05 GiB
  └ Labels: ec2.instance.type.t2.small=true, executiondriver=, kernelversion=4.2.0-35-generic, nodeindex=2, operatingsystem=Ubuntu 14.04.4 LTS, provider=generic, role.infra=true, role.service=true, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T08:43:51Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.2.0-35-generic
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 5.116 GiB
Name: aws-prod-master
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Aws

**Steps to reproduce the issue:**
Occurs irregularly

**Describe the results you received:**
Network connectivity in one container is poor or non-existent

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens every day since we updated to docker 1.11

**Comment by mavenugo** [comment]
@byrnedo few questions.

Is this a name resolution issue or general connectivity issue ? Can you confirm this by reaching other containers in the overlay network (or external services) using direct ip-addresses instead of by name ?

If you confirm that it is a name resolution issue -

1. Since docker 1.11 provides embedded DNS service, ideally to reach other containers in the same overlay network, one would not need Consul service. But since you are using Consul as a DNS service, can you explain how you are passing the `--dns` parameter ?
2. Do you have more than 1 external DNS servers using `--dns` or in the host `/etc/resolv.conf` ?

cc @sanimej

**Comment by byrnedo** [comment]
Hi @mavenugo 

I hadn't checked whether it was name resolution alone, will do as soon as it reoccurs.

I may look at switching over to docker's built in dns as well. Would reduce my dependency on consul.

**Comment by sanimej** [comment]
@byrnedo For containers on overlay networks embedded DNS server is enabled by default and it should be forwarding the queries to the consul DNS. When you see the connectivity issue please check if the name resolution is as @mavenugo mentioned. If it is a name resolution issue it will help if you can run the daemon in debug mode and send the debug logs during the name resolution.

**Comment by byrnedo** [comment]
So a `dig www.google.com` hangs for about 10 seconds then spits back:
```
dig www.google.com

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59664
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		299	IN	A	209.85.203.104
www.google.com.		299	IN	A	209.85.203.99
www.google.com.		299	IN	A	209.85.203.106
www.google.com.		299	IN	A	209.85.203.147
www.google.com.		299	IN	A	209.85.203.103
www.google.com.		299	IN	A	209.85.203.105

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Tue Apr 19 16:43:33 UTC 2016
;; MSG SIZE  rcvd: 139

```

I can ping the other containers:
```
/# ping 172.28.0.3
PING 172.28.0.3 (172.28.0.3) 56(84) bytes of data.
64 bytes from 172.28.0.3: icmp_seq=1 ttl=64 time=0.826 ms
64 bytes from 172.28.0.3: icmp_seq=2 ttl=64 time=0.773 ms
64 bytes from 172.28.0.3: icmp_seq=3 ttl=64 time=0.750 ms
```

I'm passing `--engine-opt=dns=172.17.0.1`  with docker-machine, resulting in `--dns=172.17.0.1` 

I have just the one `--dns` flag. I'm using recursors on consul in the config like `"recursors": ["8.8.8.8", "8.8.4.4"]`

**Comment by sanimej** [comment]
@byrnedo Is this delay in dig happening on one of the nodes, but other nodes are ok ? And, is this consistent or happens randomly ?

Its clear that there is some timeout when the queries are forwarded to external servers causing the delay.. if you can run the daemons in the debug mode and collect the traces when you do the dig it will  help.

**Comment by byrnedo** [comment]
It's happening within 1 container alone. The node itself responds quickly to the dig. 
I hadn't thought of trying to dig via consul on the node itself. Will do that next time.

It seems to happen after ~ 2hours of running the container. Then restarting that container solves it for another 2 hours. 

Restarting the consul agent on the host does not fix it. 

I can't really put the debug mode on until tonight (CEST) as this is a production server.

**Comment by thaJeztah** [comment]
@byrnedo actually, there is; if you use a daemon.json configuration file, you can love reload certain options by sending a `SIGHUP` to the daemon; https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

**Comment by axper** [comment]
Seems like we have the same problem #22142

**Comment by byrnedo** [comment]
thanks @thaJeztah.

Last night we tore down the env and rebuilt the cluster (including the consul server) from scratch and since then we've seen no problems.

**Comment by thaJeztah** [comment]
@byrnedo interesting; exactly the same configuration and versions? (kernel etc)

**Comment by byrnedo** [comment]
Yeah except that swam is now at 1.2, before it was 1.1.3.

There have been some weird happenings in the last hour with one container again, so I may have spoken too soon.

**Comment by sanimej** [comment]
@byrnedo By weird happenings do you mean the same connectivity issue you had before ? If it is the connectivity issue, can you confirm if the name resolution is failing. Can you please run the daemon in debug mode so that we can look at the logs if there is a resolution failure.

**Comment by byrnedo** [comment]
I just attempted to reload the config using SIGHUP:
```
time="2016-04-21T05:36:44.063033171Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json" 
time="2016-04-21T05:36:44.063386209Z" level=error msg="Error reconfiguring the daemon: discovery service not supported" 

root@aws-prod-master:/etc/docker# cat daemon.json 
{
"debug": true
}
```

Do I need more in the `/etc/docker/daemon.json` file?

**Comment by byrnedo** [comment]
@sanimej The weird happenings are the following series of events:

1. Container makes a dns lookup to some.domain
2. Consul logs:
```
    2016/04/21 08:15:04 [ERR] dns: recurse failed: read udp 10.0.7.95:33508->8.8.8.8:53: i/o timeout
    2016/04/21 08:15:04 [ERR] dns: recurse failed: read udp 10.0.7.95:57775->8.8.8.8:53: i/o timeout
    2016/04/21 08:15:06 [ERR] dns: recurse failed: read udp 10.0.7.95:51556->8.8.4.4:53: i/o timeout
    2016/04/21 08:15:06 [ERR] dns: all resolvers failed for {some.domain. 1 1} from client 172.18.0.11:34106 (udp)
    2016/04/21 08:15:06 [ERR] dns: recurse failed: read udp 10.0.7.95:35560->8.8.4.4:53: i/o timeout
    2016/04/21 08:15:06 [ERR] dns: all resolvers failed for {some.domain. 28 1} from client 172.18.0.11:34106 (udp)
    2016/04/21 08:15:09 [ERR] dns: recurse failed: read udp 10.0.7.95:41163->8.8.8.8:53: i/o timeout

```
3. Container that made the dns request becomes partially unresponsive from that point onwards when being accessed by ip. 

Another thing I've seen in the docker logs on the master is:
```
time="2016-04-21T13:23:27.897466577Z" level=error msg="could not resolve peer \"<nil>\": timed out resolving peer by querying the cluster" 
time="2016-04-21T13:23:28.898120784Z" level=error msg="could not resolve peer \"<nil>\": timed out resolving peer by querying the cluster"
```

One more thing is that from any container on the master node, pinging one particular container *by ip* which is running on another node fails, but works from containers running on either of the other 2 hosts.

**Comment by sanimej** [comment]
@byrnedo If you able to recreate either of the issues (_1.container unresponsive after query,_  _2.could not resolve peer error_) with some consistency can you give me the exact steps you are following ?

**Comment by byrnedo** [comment]
Hi @sanimej, I've updated to the 1.12.0-rc3 and no longer see this issue.

**Comment by thaJeztah** [comment]
@byrnedo should we close this issue?

**Comment by byrnedo** [comment]
I spoke too soon. After leaving the environment up and running overnight it's back to the same old problem.  

Steps to reproduce: 

1. Take any docker build after 1.10.3 and make a swarm using consul (0.6.4) as the kv store for discovery on a ubuntu host (14.04 or 16.06) on aws.
2. Create an overlay network.
3. Run x number of containers on the network with a port or two open
4. Try and do a dns lookup to another container ( in my case dns is through consul )

All the culprit dns failures were on 1 specific host in the swarm. I restarted it and now things are working again. I will check in if it starts failing again.

1.10.3 is running great in production by that's now been removed from the apt sources (to be honest that seems a bit slack considering dns resolutions is obviously heavily bugged in some way in 1.11 and now anyone like myself who wants to run a working swarm on overlay has to jump through hoops)

@cupracer in #22185 seems to have had the same problem as I am and he's done a much better job of documenting it.

Since it is to my eyes the same issue then there's no point in having 2 issues ongoing with this.

**Comment by thaJeztah** [comment]
> 1.10.3 is running great in production by that's now been removed from the apt sources

how do you mean it's removed from apt sources?

**Comment by byrnedo** [comment]
On ubuntu 16.04 I only get the following versions from `apt-cache policy`
```
~> apt-cache policy docker-engine
docker-engine:
  Installed: 1.11.2-0~xenial
  Candidate: 1.12.0~rc3-0~xenial
  Version table:
 *** 1.11.2-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.11.1-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
     1.11.0-0~xenial 500
        500 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages
```
My `/etc/apt/sources.list.d/docker.list` reads as:
`deb https://apt.dockerproject.org/repo ubuntu-xenial main`

**Comment by sanimej** [comment]
@byrnedo When you see DNS failures can you please capture the traffic and also the deamon logs (should be running in debug mode) ? That will help to confirm if this is a duplicate of #22185

**Comment by byrnedo** [comment]
I've had it running a few days now and actually not seeing failures. My false positive was most likely due to [this](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457) kernel issue with kswapd eating up all cpu on ubuntu16.04. I've turned on debug mode now and will report if I notice anything.

**Comment by thaJeztah** [comment]
> On ubuntu 16.04 I only get the following versions from apt-cache policy

That's correct; Ubuntu 16.04 was not yet released when docker 1.10 was released, so the first release available for Ubuntu 16.04 is Docker 1.11. Docker 1.10 was not *removed* from the 16.04 repository, it never existed.

**Comment by byrnedo** [comment]
Ok, thanks for clarifying, my bad.

**Comment by byrnedo** [comment]
I just noticed that this issue is still open, I think it's been so long and it didn't reoccur in later docker version so from my perspective this could be closed. @thaJeztah

**Comment by thaJeztah** [comment]
Thanks, yes let me close this one, as a lot of code has changed since as well
