### ISSUE TITLE
Retrying issue while pushing

### ISSUE THREAD

**Issue by Somebi** [moby/moby#22188]
6255d70a91d0: Image push failed
a1e9ae5cde95: Retrying in 1 seconds
24600f12e14b: Retrying in 1 seconds
0ddf332b6471: Image push failed
1f273775685e: Retrying in 1 seconds

unknown: too many failed login attempts for username or IP address

Issue maybe caused by repository deletion and creating the same, then trying to push again into it.
I'm using docker version: Docker version 1.10.0, build 590d5108 on Ubuntu 15.10

Some docker push clean parameter is required, to avoid checking or cleaning any local/remote history related to the same repository name. I didn't go into docker mechanics, by i think problem is somewhere there. :)

**Comment by Somebi** [comment]
It's very odd. Now, after a LOT of retries it finally started to push. But again, it's very odd because it wasn't pushing whole image, which is around ~6gb, but only few layers. I have deleted repository and created with the same name again. It seems old images data still available even after deletion and recreation on docker hub...

**Comment by Somebi** [comment]
Images deletion of deleted repositories are scheduled for deletion or what is this?

**Comment by thaJeztah** [comment]
Are you pushing to Docker Hub, or a private repository?

/cc @aaronlehmann

**Comment by aaronlehmann** [comment]
Please upgrade to 1.10.3 or 1.11.0. Docker 1.10.0 has a few known bugs that could be at fault.

If this doesn't help, the image may be corrupted. You could try deleting it and rebuilding it.

**Comment by dgilling** [comment]
I am using Docker version 1.11.0, build 4dc5990 and I also see this.
While I like security, this issue can be a big blocker on CI/CD flows once locked out of account.

I am pushing to Private Docker Hub repo and seems that it keeps retrying with possibly invalid credentials until it errors out. 
Now, I am locked out of my account (I wish even reseting my password would remove this lock)

unknown: too many failed login attempts for username or IP address

**Comment by Somebi** [comment]
I'm using private repo on docker hub, after a while i finally managed to push the image. Image is not corrupted, i was using it on another server, after push.

**Comment by tmds** [comment]
Once you get into the "too many failed login attempts for username or IP address" state. How do you reset/unlock your account?

**Comment by sparklyballs** [comment]
i am getting "too many failed login attempts for username or IP address" trying to pull the official alpine image.
running 1.11.1 on ubuntu xenial.

**Comment by tmds** [comment]
@sparklyballs even for public images the credentials are used, probably if you clear your credentials, you'll be able to pull the public image

**Comment by Somebi** [comment]
It's kinda solved in a newest version.

**Comment by dgonzalez** [comment]
This is also happening to me. Mac with docker-machine keeps retrying when pushing to amazon. It looks very critical to me.

**Comment by thaJeztah** [comment]
@dgonzalez what exact issue are you having? Is that due to "too many failed login attempts"? I'm not sure theres much more that can be done there, as it's a valid response if incorrect credentials are provided.

**Comment by arashbina** [comment]
Same is happening to me. I'm trying to push to a public repository I just created. There are no errors. It just keeps retrying.

**Comment by pms1969** [comment]
I'm getting the same pushing to a private nexus repo.

Docker version 1.12.1, build 23cf638 on Windows 10.

**Comment by Omnipresent** [comment]
Same here. Using Docker for mac. Pushing to a Docker Trusted Registry running on AWS (with no authentication) just keeps retrying. Additionally, the Docker Trusted Registry is added to `Preferences -> Advanced -> Insecure Registries`.

`Docker version 1.12.1, build 6f9534c`

**Comment by vikas027** [comment]
I am too facing the same issue.

# Environment
CentOS 7.2
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

# Problem
Small Images (around 5MB) pushes fine, but slightly large images (mine was 180 MB) fails with messages similar to these
`4dcab49015d4: Retrying in 4 seconds`

Here is the link  https://asciinema.org/a/0r30xzn9p2qdslmtkd8o9g8vd

**Comment by dgonzalez** [comment]
@thaJeztah no. Is like network failures between my computer and the docker-machine when pushing to amazon. I think it is more a virtual box problem than docker as recreating the docker-machine worked for me (had to do it few times).

**Comment by aaronlehmann** [comment]
@vikas027: This sounds like it may be a registry configuration issue. Could you provide logs from the Docker daemon and registry?

In general I'd recommend opening up new issues in cases like this. The original issue was related to authentication rate-limiting, but yours looks like it has a different root cause.

**Comment by vikas027** [comment]
@aaronlehmann Has something changed in the last few hours ? I just re-did everything today (to open another ticket and paste logs) and it is working fine for me now :)

**Comment by caryyu** [comment]
In my case , the main reason why is that `Connection-Timeout` by `Nginx`, because `proxy_connect_timeout ` parameter default value is `60s`, so give an one bigger than that by `300s`, my problem is gone, maybe you face the same issue like me, specific configuration below: 
```
...

location / {
        
        ....

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        client_max_body_size 5000m;
}

....
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
