### ISSUE TITLE
`docker inspect` can get stuck for many minutes

### ISSUE THREAD

**Issue by pcarrier** [moby/moby#22322]
We have production issues with docker 1.10.3 (binary from //get.docker.com/builds/Linux/x86_64/docker-1.10.3) where we observed:
- `docker inspect` taking over 90 seconds
- `docker ps -a` taking over 20 minutes
- `docker info` taking over 2 minutes

None of those times are predictable, those are the longest times recorded.

Environment:
- `m4.4xlarge` EC2 instances
- `amazon-ecs-agent` 1.8.2
- Ubuntu 16.04 AMI
- `overlay` as a storage driver
- `journald` as a logging driver
- Plenty of margin for memory, CPU, network, storage I/O.

In all cases, `docker info` displayed fewer than 100 containers total. We don't have a good way to reproduce, and this has only affected our production environment.

We have identified that this issue is caused by semaphore contention in `datastore.(*datastore).List` in the case of `docker info`. Here is how (TL;DR: wrote a poor person's sampling profiler):
1. Start docker with `DEBUG=1` (or create `/etc/docker/daemon.json` with `{"debug":true}` and send `SIGHUP` to `docker daemon`).
2. Expose Docker's Unix socket with `$ sudo socat -d TCP-LISTEN:8080,fork,bind=127.0.0.1 UNIX:/var/run/docker.sock`
3. Run https://gist.github.com/pcarrier/5cf3845f26f52ee4b8c42253ac09cecd and collect its output; leave it running in the background
4. Run `docker info`. When it finishes, the script in (3) should terminate.
5. Process the output from (3) with `sort|uniq -c|sort -nr`

The result:

```
    627 sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks
      1 syscall.Syscall syscall.read syscall.Read os.(*File).read os.(*File).Read
      1 encoding/json.fieldByIndex encoding/json.(*structEncoder).encode encoding/json.(*structEncoder).(encoding/json.encode)-fm encoding/json.(*structEncoder).encode encoding/json.(*structEncoder).(encoding/json.encode)-fm
```

**Comment by pcarrier** [comment]
I'll collect who's blocked by that semaphore. We saw a lot of things waiting for it. There might be a bias towards whatever holds the semaphore for the longest not being who waits for the semaphore for the longest, but it'll probably be useful.

**Comment by pcarrier** [comment]
I'm not sure I would call it merely "performance", when "docker ps -a" can take over 25 minutes to return 100 containers. That's so unexpectedly slow (orders of magnitude slower than one would expect) that it'll break even reasonable health check scripts.

**Comment by pcarrier** [comment]
We haven't seen the issue in prod since our last deploy on Monday last week. Given how little changed besides starting fresh with more reliable removal of old containers, makes me think the issue might be triggered when a lot of containers are around and persist once the containers are removed.

**Comment by estesp** [comment]
@pcarrier can you characterize your use of libnetwork? Are you using `docker network create` in the flow of creating containers? Any characterization of the numbers at or near failure? E.g. "200 containers connected to 10 networks, using the standard overlay driver"? Obviously if you are using any libnetwork plugins or can explain if you have any multi-host activity here (e.g. swarm; what distributed kv store, if you are running one, etc.)

Thanks

**Comment by pcarrier** [comment]
@estesp we're on ECS, we don't create any network (everything is on `docker0`), we haven't tweaked the network stack at all.

**Comment by estesp** [comment]
@pcarrier ok, now I'm even more curious--do you happen to have a full trace of any of the call stacks that lead up to that libnetwork dataStore.List() call?  I know a few common paths that end there, but that is usually via the `docker network create` path.  Very curious what API path is walking (or attempting to) the kvstore of networks.  ping @mavenugo in case your team has any thoughts right off the bat.

**Comment by pcarrier** [comment]
@estesp not at hand no. But the stats are for goroutines that contain `systemRouter.getInfo` so that shouldn't be too hard to find in a debugger?

**Comment by estesp** [comment]
no problem--I think I'm getting the picture; `docker info` is going to ask libnetwork for a list of it's networks (to figure out what plugins are involved) here: https://github.com/docker/docker/blob/master/daemon/network.go#L195-L211

So that's already a bit painful; I assume `inspect` we'll find something similar (or at least it needs that lock temporarily) as it wants to report on some network details for the container being inspected; and `docker ps -a` effectively becomes a **for all containers { inspect(c) }**; so a O(n) walk of all containers with the same inspect cost (and lock) for each.  The concern is, what's holding that lock for so long as you don't appear to have a deadlock; just dreadful performance which leads to a long lock-hold, which prevents other commands from returning.

**Comment by pcarrier** [comment]
Yes. I've written another poor man's sampling profiler to look at what holds the lock; I'll try to collect that from my dev environment (not sure we can reliably reproduce the issue right now but I've seen it in the last few days; sadly I rotate instances pretty often in my dev env instead of creating separate ones).

**Comment by pcarrier** [comment]
Updated the gist, the new version traces every goroutine contending.

```
$ sort trace|uniq -c|sort -nr
   5129 > sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks github.com/docker/docker/daemon.(*Daemon).GetNetworkDriverList github.com/docker/docker/daemon.(*Daemon).showPluginsInfo github.com/docker/docker/daemon.(*Daemon).SystemInfo github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm
      1 > syscall.Syscall syscall.Lstat os.Lstat os.(*File).readdir os.(*File).Readdir io/ioutil.ReadDir github.com/docker/docker/pkg/fileutils.GetTotalUsedFds github.com/docker/docker/daemon.(*Daemon).SystemInfo github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm
```

**Comment by pcarrier** [comment]
(Sorry, deleted last comment as it was useless)

OK I now have a version that tracks goroutines acquiring _any_ semaphore.

```
$ sort trace|uniq -c|sort -nr
  65061 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/container.(*State).IsRunning github.com/docker/docker/daemon.(*Daemon).ContainerStop github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1 github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1 github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1
  40343 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/container.(*State).SetRemovalInProgress github.com/docker/docker/daemon.(*Daemon).ContainerRm github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1 github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1 github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1
  35364 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/daemon.(*Daemon).containerInspectPre120 github.com/docker/docker/daemon.(*Daemon).ContainerInspect github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersByName github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersByName)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1 github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1 github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1
  32030 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/container.(*State).getExitCode github.com/docker/docker/container.(*State).WaitStop github.com/docker/docker/daemon.killProcessDirectly github.com/docker/docker/daemon.(*Daemon).Kill github.com/docker/docker/daemon.(*Daemon).containerStop github.com/docker/docker/daemon.(*Daemon).ContainerStop github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm
  24872 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic github.com/docker/libnetwork.(*controller).updateToStore github.com/docker/libnetwork.(*network).CreateEndpoint github.com/docker/docker/daemon.(*Daemon).connectToNetwork github.com/docker/docker/daemon.(*Daemon).allocateNetwork github.com/docker/docker/daemon.(*Daemon).initializeNetworking github.com/docker/docker/daemon.(*Daemon).containerStart github.com/docker/docker/daemon.(*Daemon).ContainerStart
  13593 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/layer.(*layerStore).ReleaseRWLayer github.com/docker/docker/daemon.(*Daemon).cleanupContainer github.com/docker/docker/daemon.(*Daemon).ContainerRm github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1 github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1
  13458 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic github.com/docker/libnetwork.(*controller).deleteFromStore github.com/docker/libnetwork.(*sandbox).storeDelete github.com/docker/libnetwork.(*sandbox).delete github.com/docker/libnetwork.(*sandbox).Delete github.com/docker/docker/daemon.(*Daemon).releaseNetwork github.com/docker/docker/daemon.(*Daemon).Cleanup github.com/docker/docker/container.(*containerMonitor).Close
  13447 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/container.(*State).getExitCode github.com/docker/docker/container.(*State).WaitStop github.com/docker/docker/daemon.(*Daemon).containerStop github.com/docker/docker/daemon.(*Daemon).ContainerStop github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1
  11463 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks github.com/docker/libnetwork.(*controller).WalkNetworks github.com/docker/libnetwork.(*controller).NetworkByName github.com/docker/docker/daemon.(*Daemon).GetNetwork github.com/docker/docker/daemon.(*Daemon).FindNetwork github.com/docker/docker/daemon.(*Daemon).releaseNetwork
  11150 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).GetObject github.com/docker/libnetwork/ipam.(*Allocator).getAddressSpaceFromStore github.com/docker/libnetwork/ipam.(*Allocator).refresh github.com/docker/libnetwork/ipam.(*Allocator).ReleaseAddress github.com/docker/libnetwork.(*endpoint).releaseAddress github.com/docker/libnetwork.(*endpoint).Delete github.com/docker/libnetwork.(*sandbox).delete github.com/docker/libnetwork.(*sandbox).Delete
  10656 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic github.com/docker/libnetwork.(*controller).updateToStore github.com/docker/libnetwork.(*endpoint).sbLeave github.com/docker/libnetwork.(*endpoint).Leave github.com/docker/libnetwork.(*sandbox).delete github.com/docker/libnetwork.(*sandbox).Delete github.com/docker/docker/daemon.(*Daemon).releaseNetwork github.com/docker/docker/daemon.(*Daemon).Cleanup
   9950 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/layer.(*layerStore).CreateRWLayer github.com/docker/docker/daemon.(*Daemon).setRWLayer github.com/docker/docker/daemon.(*Daemon).create github.com/docker/docker/daemon.(*Daemon).ContainerCreate github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersCreate)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1
   9741 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks github.com/docker/libnetwork.(*controller).WalkNetworks github.com/docker/libnetwork.(*controller).NetworkByName github.com/docker/docker/daemon.(*Daemon).GetNetwork github.com/docker/docker/daemon.(*Daemon).FindNetwork github.com/docker/docker/daemon.(*Daemon).updateNetworkConfig
   9276 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic github.com/docker/libnetwork.(*controller).updateToStore github.com/docker/libnetwork.(*endpoint).sbJoin github.com/docker/libnetwork.(*endpoint).Join github.com/docker/docker/daemon.(*Daemon).connectToNetwork github.com/docker/docker/daemon.(*Daemon).allocateNetwork github.com/docker/docker/daemon.(*Daemon).initializeNetworking github.com/docker/docker/daemon.(*Daemon).containerStart
   9085 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic github.com/docker/libnetwork.(*controller).updateToStore github.com/docker/libnetwork.(*sandbox).storeUpdate github.com/docker/libnetwork.(*controller).NewSandbox github.com/docker/docker/daemon.(*Daemon).connectToNetwork github.com/docker/docker/daemon.(*Daemon).allocateNetwork github.com/docker/docker/daemon.(*Daemon).initializeNetworking github.com/docker/docker/daemon.(*Daemon).containerStart
   8957 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic github.com/docker/libnetwork.(*controller).updateToStore github.com/docker/libnetwork.(*sandbox).storeUpdate github.com/docker/libnetwork.(*sandbox).populateNetworkResources github.com/docker/libnetwork.(*sandbox).SetKey github.com/docker/docker/daemon.(*Daemon).setNetworkNamespaceKey github.com/docker/docker/daemon.(*Daemon).Run.func1 github.com/docker/docker/daemon/execdriver/native.(*Driver).createNetwork.func1
   1921 > sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks github.com/docker/docker/daemon.(*Daemon).GetNetworkDriverList github.com/docker/docker/daemon.(*Daemon).showPluginsInfo github.com/docker/docker/daemon.(*Daemon).SystemInfo github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm
   1921 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).List github.com/docker/libnetwork.(*controller).getNetworksFromStore github.com/docker/libnetwork.(*controller).Networks github.com/docker/docker/daemon.(*Daemon).GetNetworkDriverList github.com/docker/docker/daemon.(*Daemon).showPluginsInfo github.com/docker/docker/daemon.(*Daemon).SystemInfo github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm
   1921 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/daemon.(*Daemon).reducePsContainer github.com/docker/docker/daemon.(*Daemon).reduceContainers github.com/docker/docker/daemon.(*Daemon).Containers github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm github.com/docker/docker/api/server.versionMiddleware.func1 github.com/docker/docker/api/server.(*Server).corsMiddleware.func1 github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1
   1921 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/docker/container.(*State).getExitCode github.com/docker/docker/container.(*State).WaitStop github.com/docker/docker/daemon.(*Daemon).Kill github.com/docker/docker/daemon.(*Daemon).containerStop github.com/docker/docker/daemon.(*Daemon).ContainerStop github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStop)-fm github.com/docker/docker/api/server.versionMiddleware.func1
   1921 =
   1389 < sync.runtime_Semacquire sync.(*Mutex).Lock github.com/docker/libnetwork/datastore.(*datastore).GetObject github.com/docker/libnetwork.(*controller).getNetworkFromStore github.com/docker/libnetwork.(*endpoint).getNetworkFromStore github.com/docker/libnetwork.(*network).CreateEndpoint github.com/docker/docker/daemon.(*Daemon).connectToNetwork github.com/docker/docker/daemon.(*Daemon).allocateNetwork github.com/docker/docker/daemon.(*Daemon).initializeNetworking github.com/docker/docker/daemon.(*Daemon).containerStart
      1 < sync.runtime_Semacquire sync.(*WaitGroup).Wait github.com/docker/docker/pkg/pubsub.(*Publisher).Publish github.com/docker/docker/daemon/events.(*Events).Log github.com/docker/docker/daemon.(*Daemon).LogImageEvent github.com/docker/docker/daemon.(*Daemon).LogImageEvent-fm github.com/docker/docker/distribution.Pull github.com/docker/docker/daemon.(*Daemon).PullImage github.com/docker/docker/api/server/router/local.(*router).postImagesCreate github.com/docker/docker/api/server/router/local.(*router).(github.com/docker/docker/api/server/router/local.postImagesCreate)-fm
```

**Comment by mavenugo** [comment]
@pcarrier am not familiar with `amazon-ecs-agent` and what its functionality is. Would you mind explaining how it plays a role in your environment ?

**Comment by estesp** [comment]
@mavenugo looks like it is Amazon's intermediary for a particular EC2 instance running as a docker host--e.g. has access to the Docker socket for running containers, configures logging, log levels, whether privileged containers can be run, etc: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html

Doesn't *seem* like it would have any performance impact on a container actually running on an EC2 hosted daemon.

**Comment by thaJeztah** [comment]
source code for that can be found here https://github.com/aws/amazon-ecs-agent, but @samuelkarp probably would be able to tell if there's anything that can influence this

**Comment by estesp** [comment]
I've taken some pprof blocking data from @pcarrier and netted out long block times, which all happen to end up at the lock which protects access to the BoltDB-backed local store. Of course there is more than one lock represented here as I believe there is a datastore for networks, one for endpoints, and one for sandbox keys (netns entries on Linux); however, interesting that they all are experiencing pretty evenly distributed performance, which would seem to point out a significant perf. issue with the lower layer of BoltDB reads or writes?

Note that these libnetwork locks are the only thing that catches your eye in the entire block cycle data from pprof. Most of the lock contention listed averages out to sub-second per cycle, and the only few things that rise above a single second are actual I/O waits (layer mounts and log buffering, which were as high as 13 seconds [in a few cases; average was few seconds] for layers and 3 seconds for log buffer waits).  Also, the container monitor's *wait for start* averaged 103 seconds, but that is I assume because the 70-90 seconds waiting for network allocation shown below is part of that entry's lock time.

```
45 minutes (29 times) github.com/docker/libnetwork/datastore.(*datastore).List
= avg 93sec           containerStart > allocateNetwork > GetNetwork > WalkNetworks

44 minutes (34 times) github.com/docker/libnetwork/datastore.(*datastore).GetObject
= avg 77sec           Cleanup > releaseNetwork > ipam.ReleaseAddress > getAddressSpaceFromStore

29 minutes (20 times) github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic
= avg 87sec           (pre-start-hook) > setNetworkNamespaceKey > sandbox.SetKey -> storeUpdate

29 minutes (18 times) github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic
= avg 96sec           containerStart > allocateNetwork > CreateEndpoint > updateToStore

28 minutes (20 times) github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic
= avg 84sec           Cleanup > releaseNetwork > endpoint.Leave > updateToStore

27 minutes (22 times) github.com/docker/libnetwork/datastore.(*datastore).List
= avg 73sec           Cleanup > releaseNetwork > FindNetwork > WalkNetworks

23 minutes (16 times) github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic
= avg 86sec           containerStart > allocateNetwork > endpoint.Join > updateToStore

18 minutes (12 times) github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic
= avg 90sec           containerStart > allocateNetwork > NewSandbox > updateToStore

14 minutes (12 times) github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic
= avg 70sec           Cleanup > releaseNetwork > sandbox.Delete > deleteFromStore

10 minutes (7 times)  github.com/docker/libnetwork/datastore.(*datastore).GetObject
= avg 85sec           containerStart > allocateNetwork > CreateEndpoint > getNetworkFromStore

3 minutes  (2 times)  github.com/docker/libnetwork/datastore.(*datastore).GetObject
= avg 90sec           containerStart > allocateNetwork > CreateEndpoint > ipam.GetAddressSpaceFromStore

1 minute   (1 time)   github.com/docker/libnetwork/datastore.(*datastore).List
= avg 60sec           containerStart > allocateNetwork > CreateEndpoint > WalkEndpoints > getEndpointsFromStore
```

@mavenugo anyone from your team versed in how to dig deeper on BoltDB performance or understand what might be occurring? The level of detail I have only lets me divine that there are long lock holds because of that lower layer, but I have no idea why.

**Comment by mavenugo** [comment]
@pcarrier @estesp yes. @aboch spent a lot of time analyzing BoltDB performance particularly in a specific AWS configuration (in CI). That is one of the reasons I would like to understand about `amazon-ecs-agent`. As the name indicates, I would like to understand if this is some sort of gateway into ECS (and not just EC2) so that we can better understand the environment that we are dealing with.

**Comment by benbjohnson** [comment]
@estesp Bolt author here. Do you have the raw pprof profile data and binary? I'm happy to take a look and help point you in the right direction if it's a Bolt issue.

**Comment by estesp** [comment]
@benbjohnson thanks for the offer!  I do not have the raw pprof data, but @pcarrier is probably the best source for that. Maybe you and @aboch could interact given it sounds like he has done more here than I have.

**Comment by pcarrier** [comment]
@benbjohnson can you reach out to pcarrier on Freenode or pierre@meteor.com ? That would come from a dev env but I'm still concerned about potential leaks, so can't be public.

**Comment by pcarrier** [comment]
@mavenugo ECS is a container clustering solution from Amazon. amazon-ecs-agent runs on the EC2 instances that run the containers themselves and interacts with Docker, reports its state to the centralized, proprietary management solution and receives orders from it, reports its metrics to an ECS cloudwatch endpoint. This agent is open source, see https://github.com/aws/amazon-ecs-agent or https://github.com/meteor/amazon-ecs-agent for our small fork (tightly kept up-to-date and with very few patches, 1 from us and others published in PRs/the dev branch by AWS and backported as we work on with them on our issues).

**Comment by pcarrier** [comment]
We've upgraded to Docker 1.11.x and moved to DeviceMapper as a storage backend across all our systems; couldn't reproduce this issue since. So we're no longer actively working on this.

**Comment by jimmycmh** [comment]
I encountered the same issue.
In my case it's connected to overlay network.

**Comment by ondrejhlavacek** [comment]
We're experiencing a similar issue, `docker rm`, `docker inspect` or `docker run` of a simple container can take minutes. 

Originally we were attributing this behaviour to IO load (we were able to simulate this behaviour under heavy IO load), but after reading this thread I am no longer sure.

Our environment is a EC2 instance (m4.4xl) which runs batch jobs using Docker. There should be no more than 40 container running at the same time, but there can be hundreds of containers spun up every hour (each job consists of `docker run`, `docker inspect` and `docker rm`). 

Can this be related? What can I do to provide some more debugging information? We are able to remove `docker rm`, but still a very simple alpine linux `docker run` with a pulled image executing a very simple command can take minutes (seconds are expected).

**Comment by thaJeztah** [comment]
Is anyone still running into this issue? I think quite some parts that could relate to this have been rewritten since, and I haven't heard issues reporting / mentioning this for a long time.

I'll go ahead and close this ticket, but feel free to comment if I closed prematurely.
