### ISSUE TITLE
[DOCS] Development environment setup tutorial outdated

### ISSUE THREAD

**Issue by AbheekG** [moby/moby#22393]
Tutorial  [Work with a development container](https://docs.docker.com/opensource/project/set-up-dev-env/) talks about the **binary** directory. Current development source makes **binary-client** and **binary-daemon**. This modifies a few steps, like the one where we copy the binary file.

The documentation can benefit from updates also.

**Comment by thaJeztah** [comment]
Thanks for reporting @abheekg there's work in progress for updating that documentation, but the "binary split" (client / daemon) has not yet been incorporated in those changes. See https://github.com/docker/opensource/pull/62

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
