### ISSUE TITLE
seccomp support on Debian Jessie

### ISSUE THREAD

**Issue by lblackstone** [moby/moby#22453]
The necessary package for seccomp support in Debian Jessie has been [backported](https://packages.debian.org/jessie-backports/libseccomp-dev).

The build process could be updated to use this backport, and remove the restriction documented [here](https://docs.docker.com/engine/security/seccomp/#seccomp-security-profiles-for-docker). (quoted below)

> Note: seccomp profiles require seccomp 2.2.1 and are only available starting with Debian 9 “Stretch”, Ubuntu 15.10 “Wily”, and Fedora 22. To use this feature on Ubuntu 14.04, Debian Wheezy, or **Debian Jessie**, you must download the latest static Docker Linux binary. This feature is currently not available on other distributions.

**Comment by justincormack** [comment]
It would be nice to get Debian working, but I am not sure the best way to do it, not really sure if we should be adding backports to people's config, so not sure the best way to approach this.

**Comment by lblackstone** [comment]
FWIW, Wheezy [already uses](https://github.com/docker/docker/blob/master/contrib/builder/deb/amd64/debian-wheezy/Dockerfile#L11) a backport.

**Comment by tianon** [comment]
Backports _should_ be mostly harmless -- in the default config, no packages from backports will be used unless they're explicitly necessary to satisfy some dependency or requested by the user at the command line.  My concern with adding them is that we've had a lot of trouble with users of Wheezy actually enabling backports, and the error message they get if they don't is really non-obvious (cannot satisfy dependency XYZ).

**Comment by ijc25** [comment]
There's one exciting corner case with backports wrt whether it is requested by the user. If a user does `apt install foo` for `foo` which is only present in jessie-backports (and stretch/sid/etc) but not in jessie then it will end up installing foo from jessie-backports, which can be unexpected/non-obvious.

I'm also unsure what the situation is with security support for *-backports, but I suspect it isn't at the same level as stable. AFAIK the developer doing the upload to backports is supposed to take on responsibility for security updates to that package, compared with the dedicated security team dealing with stable.

**Comment by AkihiroSuda** [comment]
Jessie is no longer supported https://github.com/docker/docker-ce-packaging/pull/253
