### ISSUE TITLE
[RFE] docker info should show space used by /var/lib/docker

### ISSUE THREAD

**Issue by shishir-a412ed** [moby/moby#22510]
What is the nature and description of the request?

The output for 'docker info' should include space details for /var/lib/docker

Why does the customer need this? (List the business requirements here)

"docker info should include /var/lib/docker usage as it gets used for local volumes. though thin pool may have  space container creation gets blocked as their can be no space in /var/lib/docker" 

How would the customer like to achieve this? (List the functional requirements here)

An additional line in docker info output that shows space available under /var/lib/docker

Is there already an existing RFE upstream or in Red Hat bugzilla?

No

Does the customer have any specific timeline dependencies?

No

Is the sales team involved in this request and do they have any additional input?

No

List any affected packages or components.

docker

**Comment by thaJeztah** [comment]
Would possibly make more sense to show the amount of space free on the system, instead of calculating the total amount of space used by /var/lib/docker

Not sure though, as basically this would be replicating `df`

**Comment by shishir-a412ed** [comment]
@thaJeztah I agree. Showing the amount of space available to `/var/lib/docker` makes more sense.
Something like `df -h /var/lib/docker|awk 'NR==2{print $4}'`.

Again are you guys open to exposing this data in `docker info` command ?

**Comment by thaJeztah** [comment]
@shishir-a412ed I'm still on the fence; it *can* be useful, but also may be considered general information (I.e., would any other software expose this information? A database server? A webserver?). Some things that should be taken into account;

- this should show information about the storage location / device that docker uses (which is configurable)
- is there a overhead? (I think `df` is quite fast, but not sure if there's situations where it can be a performance issue?)
- is there an equivalent on Windows?

Note that the *API* should not return a human-readable value, formatting should be done in the client.

So, not strongly against, if the issues above are taken into account (but I can't talk for other maintainers)

**Comment by shishir-a412ed** [comment]
Yeah AFAIK `df` is pretty fast. 
I think there should be one for windows. A google search bought me to this: 
http://stackoverflow.com/questions/293780/free-space-in-a-cmd-shell

Let me check if we really need this. Honestly on second thought I feel creating a wrapper for `df` is not really worth it. Since if a user's container creation is blocked because of no space in `/var/lib/docker` an administrator can easily do a `df` and check the storage.

**Comment by thaJeztah** [comment]
Agreed, unless it's useful to expose this information for Swarm

ping @vieux wdyt, should this be useful, or should we skip this, and close?

**Comment by shishir-a412ed** [comment]
@thaJeztah right so docker Swarm might need this.
Same thing for other orchestration frameworks like Kubernetes.

If Kubernetes has information on how much disk space is left on a particular node (/var/lib/docker). It can make a decision of whether to launch the container on this node, or redirect it to a different node.

Shishir

**Comment by shishir-a412ed** [comment]
@thaJeztah 
https://github.com/moby/moby/pull/26108 fixes this ?
I think we can close this issue.

Shishir

**Comment by thaJeztah** [comment]
Thanks for the ping @shishir-a412ed, yes, I think we can close this as it addresses the main issue
