### ISSUE TITLE
flags and shell expansion with `=` sign in `--config`

### ISSUE THREAD

**Issue by runcom** [moby/moby#22526]
The argument to `--config` misbehave in those cases:

`--config ~/.docker/` -> path is expanded by the shell and the config will be `/home/$USER/.docker/`
`--config=~/.docker/` -> path is **not** expanded and the config will be at `~/.docker/`
`--config="~/.docker/"` -> path is **not** expanded and the config will be at `~/.docker/`
`--config='~/.docker/'` -> path is **not** expanded and the config will be at `~/.docker/`

So the only thing which works is only the first case.

You can try it out playing around with `--config` and `--attach` for instance.
1. Specify `detachKeys` in your `~/.docker/config.json` file
   
    `"detachKeys": "ctrl-e,e"`
2. run a container with `-dit`
3. attach to this container specifying `--config=~/.docker/`
4. try to detach with the above sequence - it won't work
5. try the other failing case above
6. try with the first, working, case above where there's no `=` sign

So, the problem seems to be that `=` sign and shell expansion. Any other _relative_ path will fail the above cases of course (`../` for instance)
Not sure what to do other that checking that the path is relative and warning the user.

ping @tianon @vdemeester @calavera @cpuguy83 @thaJeztah

**Comment by rhatdan** [comment]
I don't see this as a docker problem, it is a shell issue, and is just the way it is.
 echo --config=~/.docker/
--config=~/.docker/

echo --config= ~/.docker/
--config= /home/dwalsh/.docker/

**Comment by runcom** [comment]
Agree with that, I'm just proposing to deal with it, otherwise we just close this.

**Comment by thaJeztah** [comment]
Since this is a client-side setting, can't we just convert it to an absolute path at all times? i.e.;

```go
filepath.Abs("~/.docker/")

# already an absolute path, so would probably be a no-op;
filepath.Abs("/home/$USER/.docker/")
``

**Comment by runcom** [comment]
@thaJeztah 

`filepath.Abs("~/.docker/")` expands to `$PWD/~/.docker/` which it doesn't seem to be correct

**Comment by thaJeztah** [comment]
hm, interesting; should we use our homedir package for that? https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/pkg/homedir/homedir.go#L22-L30

Could work, but starts to be a bit dirty

**Comment by runcom** [comment]
I don't know, not sure `~` is the only tricky case

**Comment by rhatdan** [comment]
I think this is a slippery path.

**Comment by tianon** [comment]
Indeed.  IMO, this is something that might warrant a little documentation,
but "~" is really a shell feature, and not worth supporting a workaround
directly in our code for.

**Comment by duglin** [comment]
```
$ echo foo=~dug
foo=/home/dug
$ echo --foo=~dug
--foo=~dug
```
just FYI

**Comment by runcom** [comment]
> Indeed.  IMO, this is something that might warrant a little documentation,
> but "~" is really a shell feature, and not worth supporting a workaround
> directly in our code for.

agree then, let's enhance the docs to make this clear

**Comment by LK4D4** [comment]
@thaJeztah can you pls move this to docs repo and probably fix?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
