### ISSUE TITLE
docker container does not recognize the environment variable

### ISSUE THREAD

**Issue by BediarSofiane** [moby/moby#22595]
Hello guys,
I'm trying to test a ping service between two containers. There are two scenarios: 
# First scenario

1- I create an **ubuntu** container that I name **ipserver**:
     -> docker create --name ipserver -it ubuntu /bin/bash
2- I connect this container (ipserver) to an existing bridge network (**sofiane**):
     -> docker network connect sofiane ipserver
3- I create a second **ubuntu** container that I name **ipclient**, and I insert the name of **ipserver** as an **env variable**:
    -> docker create --name ipclient -e ServerName=ipserver -it ubuntu /bin/bash
4- I connect **ipclient** to the same network (sofiane):
    -> docker network connect sofiane ipclient
5- I start the two containers:
    -> docker start ipserver
    -> docker start ipclient
6- I attach to **ipclient**:
    -> docker attach ipclient
7- I ping with the **env variable name**:
    -> ping $ServerName
With this scenario the ping works very well.
# Second scenario (The one with problem)

Before creating containers, I created an Image that I named **sofiane/ping_client** and whose **dockerfile** is:

`FROM ubuntu
MAINTAINER BediarSofiane
RUN apt-get update
ENTRYPOINT ["ping"]
CMD ["$ServerName"]`

1- I create an **ubuntu** container that I name **ipserver**:
     -> docker create --name ipserver -it ubuntu /bin/bash
2- I connect this container (ipserver) to an existing bridge network (sofiane):
     -> docker network connect sofiane ipserver
3- I create a  **sofiane/ping_client** container that I name **ipclient**, and I insert the name of **ipserver** as an **env variable**:
    -> docker create --name ipclient -e ServerName=ipserver  sofiane/ping_client
4- I connect **ipclient** to the same network (sofiane):
    -> docker network connect sofiane ipclient
5- I start the two containers:
    -> docker start ipserver
    -> docker start ipclient
6- I print the **env variables** of **ipclient**:
    -> docker exec ipclient env
**Result:**
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=6ae1a3497a3f
ServerName=ipserver
HOME=/root

7- I print the logs of **ipclient**:
    -> docker logs ipclient
**Result:**
ping: unknown host $ServerName

I really don't understand why the second scenario is not workin even though the env variable is really inserted in the container. I believe the problem is in the **dockerfile** but I don't know how to resolve it. 

Thank you for any answer.

**Comment by mYmNeo** [comment]
`ENTRYPOINT` will not run a container, just assign a variable, but `RUN` actually get environment variables, I think.
related code
https://github.com/docker/docker/blob/2b97201e0cd8301484fde379d2bf7f0ad3f36f10/builder/dockerfile/dispatchers.go#L415
https://github.com/docker/docker/blob/2b97201e0cd8301484fde379d2bf7f0ad3f36f10/builder/dockerfile/dispatchers.go#L497

**Comment by phemmer** [comment]
Variable substitution (the process of converting `$ServerName` into `ipserver` is handled by the shell. Since you are not using a shell, but calling `ping` directly, there is nothing to do the substitution.

Running `env` works because the issue isn't with getting the variable into the container. The issue is converting `$ServerName` into `ipserver`.

**Comment by BediarSofiane** [comment]
Thank you @phemmer 
Is there a manner to use the shell in the docker file.
If not, what would be the better manner of using environment variables inside dockerfile?

Cordially

**Comment by thaJeztah** [comment]
This is explained in the Dockerfile docs; https://docs.docker.com/engine/reference/builder/#cmd

> Note: Unlike the shell form, the exec form does not invoke a command shell. This means that normal shell processing does not happen. For example, `CMD [ "echo", "$HOME" ]` will not do variable substitution on `$HOME`.

Try using;

```Dockerfile
FROM alpine
CMD ping $ServerName
```

**Comment by ddgenome** [comment]
@thaJeztah Later in that same document, on a similar note for the exec form of ENTRYPOINT, the note goes on to say something that does not appear to be correct:

> Variables that are defined in the `Dockerfile` using `ENV`, will be substituted by the `Dockerfile` parser.

This is right above this anchor link: https://docs.docker.com/engine/reference/builder/#/shell-form-entrypoint-example

Source code for that text: https://github.com/docker/docker/blame/master/docs/reference/builder.md#L1078-L1079

Trying various ways to get the described substitution to take place never resulted in a successful substitution. For example, none of the examples below result in `$APP` being replaced with the value of the variable in the resulting image as shown by `docker inspect IMAGE`.

This results in the literal string `$APP` being exec'ed:
```
...
ENV APP foobar
ENTRYPOINT ["$APP"]
...
```

This results in the JSON array parsing to fail so docker tries to shell command it, i.e., `/bin/sh -c [$APP]`:
```
...
ENV APP foobar
ENTRYPOINT [$APP]
...
```

**Comment by vitr** [comment]
@ddgenome This has been changed to 

> When using the exec form and executing a shell directly, as in the case for the shell form, it is the shell that is doing the environment variable expansion, not docker.

is it correct now?

**Comment by Quar** [comment]
@vitr seems to me `ENV` will not expand env variables except for `$PATH`, ref #2637

**Comment by ddgenome** [comment]
I do not think environment variables will get expanded in the exec form at all.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
