### ISSUE TITLE
Flaky test: TestConsumeWithSpeedWithStop (WindowsTP5)

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#22602]
Seen failing on https://github.com/docker/docker/pull/22580 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP5/1488/console)

```
00:30:14 --- FAIL: TestConsumeWithSpeedWithStop (0.07s)
00:30:14    utils_test.go:472: Expected to have read 2 bytes, got 4
00:30:14 FAIL
```

**Comment by LK4D4** [comment]
Didn't see for a long time.

**Comment by tophj-ibm** [comment]
Just saw this on s390x in #34407. 

https://jenkins.dockerproject.org/job/Docker-PRs-s390x/4912/consoleFull

**Comment by andrewhsu** [comment]
Looks like this flaky test was removed with #34600 commit 1455086

**Comment by thaJeztah** [comment]
ok; good to close then 👍
