### ISSUE TITLE
error: level=fatal msg=\"no sandbox present

### ISSUE THREAD

**Issue by mrsanuk** [moby/moby#22625]
**Output of `docker version`:**

```
Docker version 1.11.0, build 4dc5990
```

**Output of `docker info`:**

```
Containers: 52
 Running: 43
 Paused: 0
 Stopped: 9
Images: 48
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
node02: 192.168.150.151:2375
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 36.09 GiB
  └ Labels: executiondriver=, kernelversion=4.2.0-16-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-10T08:41:06Z
  └ ServerVersion: 1.11.0
node01: 192.168.150.152:2375
  └ Status: Healthy
  └ Containers: 28
  └ Reserved CPUs: 0 / 9
  └ Reserved Memory: 0 B / 41.26 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-16-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-10T08:41:12Z
  └ ServerVersion: 1.10.3
node03: 192.168.150.150:2375
  └ Status: Healthy
  └ Containers: 13
  └ Reserved CPUs: 0 / 6
  └ Reserved Memory: 0 B / 24.72 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-16-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-10T08:41:14Z
  └ ServerVersion: 1.10.3
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.2.0-16-generic
Operating System: linux
Architecture: amd64
CPUs: 23
Total Memory: 102.1 GiB
Name: a698c6c4c271

```

I have cluster swarm cluster with consul and registrator.
I create overlay network and run all my containers with this network, but after restart node2 I can`t start old containers and have next message:

Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1: time=\"2016-05-10T11:34:07+03:00\" level=fatal msg=\"no sandbox present for 3edaede1e26068579d9fc2d200156c7ab0df736eddb31119e6ff92cc0260d923\" \n"

What should i do to resolve this problem?

**Comment by thaJeztah** [comment]
Error comes from https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go#L152-L171

Not sure what can cause this on a restart.

**Comment by mrsanuk** [comment]
maybe somebody know how i can start my container again?

**Comment by thaJeztah** [comment]
ping @mavenugo any idea how to resolve this?

**Comment by mavenugo** [comment]
@mrsanuk I could reproduce this issue in 1 scenario (which we will fix) 

```
$ sudo docker run --net=mylocalnet --name ttt3 -d busybox sh
265d8abf2c4354678744ee332e903b0d1c8f0a6a71978f40dc6ccacdc4dc056e
$ sudo docker stop ttt3
ttt3
$ sudo docker network disconnect mylocalnet ttt3
$ sudo docker start ttt3
Error response from daemon: rpc error: code = 13 desc = invalid header field value "oci runtime error: exit status 1: time=\"2016-05-11T08:22:33-07:00\" level=fatal msg=\"no sandbox present for 265d8abf2c4354678744ee332e903b0d1c8f0a6a71978f40dc6ccacdc4dc056e\" \n"
Error: failed to start containers: ttt3
```

Could this be your case as well ? 

Can you share the `docker inspect {container-1}` output ?

A possible workaround is to connect the container to a network and start it.

```
docker network connect bridge {container}
docker start {container}
```

**Comment by tehlers320** [comment]
getting the same with dtr 

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock   docker/dtr migrate *passwords and stuff*`

```
INFO[0000] phase 1 starting...                          
WARN[0000] In DTR 2.0, DTR and UCP share an authentication system. Therefore, this migration process will overwrite your UCP authentication configuration with your DTR 1.4's settings. An example of settings that will be overwritten are: LDAP server configuration, User search configurations, and Admin LDAP group details. No other UCP configuration will be overwritten. 
INFO[0000] Run the full migration? If N, this will log configuration files to assist you in performing the migration manually. (Y/N)   
y
WARN[0002] Couldn't get network ID for network 'dtr'    
FATA[0003] There was a problem running the dtr-phase2 container: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1: time=\"2016-06-07T16:32:13Z\" level=fatal msg=\"no sandbox present for 97a9107a460ae3707ca3e12e270111727caf01e3d38f2458aba0b7f3ea629b7e\" \n" 
```

**Comment by randunel** [comment]
Getting this in fresh docker swarm install, with `dc up -d`.

3 apparently random containters out of 15 did not start. Removed them, recreating worked. Later, `dc scale service=33` resulted in ~25 containers failing to start with the same error:

```
ERROR: for EDITED  Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2016-08-12T11:25:13Z\" level=fatal msg=\"no sandbox present for EDITED\" \n"
```

**Comment by alvinr** [comment]
I'm using 1.12.1, I'm seeing a similar issue. I'm using Interlock, which restarts HAproxy when a new web containers starts. The restart of HAProxy fails with 

```
time="2016-09-09T16:09:22Z" level=error msg="error restarting container: id=16958e013428 err=500 Internal Server Error: Cannot restart container 16958e0134280f3821b60ab41faba64bce7c92d2e49225130f85c64d9d03b727: oci runtime error: process_linux.go:334: running prestart hook 0 caused \"exit status 1: time=\\\"2016-09-09T16:09:22Z\\\" level=fatal msg=\\\"no sandbox present for 16958e0134280f3821b60ab41faba64bce7c92d2e49225130f85c64d9d03b727\\\" \\n\"\n" ext=haproxy
```

**Comment by sergtezt** [comment]
@mavenugo - the workaround suggested doesn't work 

```

> docker network connect bridge {container}
> docker start {container}

```
Given the issue is reproducible even on the latest release - I'd mark it as **kind/bug**
We personally have experienced it twice already.

@mavenugo any idea when we can expect a fix?

**Comment by sanimej** [comment]
@sergtezt Can you give the exact sequence and the commands with which you are able to recreate this issue ?

**Comment by sergtezt** [comment]
@sanimej 
Environment: Docker swarm cluster, consul and registry, all containers run in overlay network

After a hard reset of node, I can not start any container, getting the following error message: 
`Error response from daemon: service endpoint with name es already exists ` when starting container

I tried to use  `docker network dissconect {container} {network}` but it results in the following error:

`Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1: time=\"2016-09-30T11:34:07+03:00\" level=fatal msg=\"no sandbox present for 3edaede1e26068579d9fc2d200156c7ab0df736eddb31119e6ff92cc0260d923\" \n`

I tried to connect using `docker network connect {container}  {network}`, and again get an error:
`Error response from daemon: service endpoint with name es already exists` when starting container

**Comment by sergtezt** [comment]
And the only way to fix that issue after it has happened - 

- remove and recreate all containers
- reinstall docker cluster and rebuild overlay network

None of which is an option for production docker use.

**Comment by westsouthnight** [comment]
@sergtezt not real way if in production you already have multiple clusters and etc. As example im get that error when try upgrade one ES cluster in array of multiple ES clusters in one ENV (i have more two ES cluster per ENV in swarm), and you propose me recreate all ES clusters? You really?

**Comment by westsouthnight** [comment]
And people - after recreate network have same error. Possible workaround not work.

**Comment by sergtezt** [comment]
@westsouthnight Do you read before commenting? Really? 
I'm not on Docker team and I said 
> None of which is an option for production docker use.
It means we **haven't found** a workaround that is **suitable for production use**. Which renders Docker itself **not ready for production** usage.

**Comment by mavenugo** [comment]
ping @sanimej

**Comment by mavenugo** [comment]
@sergtezt apologies on the delayed response on this thread. Can you use Docker 1.12.3's swarm-mode and see if the overlay networking support satisfies your needs ? (we also added some more backward compatible features in 1.13 - currently in RC, if you are interested in trying that). I will try to give a background on this topic which I hope will answer some of the questions. 

Prior to 1.12 swarm-mode, Docker natively didn't have clustering concepts & hence any distributed computing paradigm (such as multi-host networking using overlay driver) is a bit complex to achieve. We relied on external KV-store for a distributed mgmt plane. (control-plane uses gossip). Such dependency on an external KV store to achieve consistency will not scale if all the nodes in the cluster are equal and participate in achieving consistency. We had seen the KVStore watches melting down as the number of nodes grow. Also we had to depend on the same kvstore for discovery and that really impacted scale. Having states in this store is tricky especially when a node dies ungracefully. Since every node can be a owner of the data, other nodes cannot and should not clean it up (since it could be a network partition at the control-plane). That causes the endpoint issues as raised here.

With the introduction of swarm-mode in 1.12, the mgmt plane is fully handled only within the managers using Raft and the workers are never involved in the Raft. This dramatically simplified the operations and increased scale. This also removed the need for external KVStore, which is a huge win.

We are trying to see if we can deprecate the external kvstore configuration (via --cluster-store and --cluster-advertise flags) in lieu of the swarm-mode. It helps everyone. If we deprecate it, then trying to patch these endpoint issues in kv-store isn't worthwhile. Please let us know your opinion.

**Comment by PhilippHeuer** [comment]
I have the same issue, my `workaroud` solution was to rename the container. It's just a single container name which i aren't able to use anymore.

**Comment by Stonesjtu** [comment]
@PhilippHeuer 's solution works for me.

**Comment by alshaboti** [comment]
I tried to rename it, it doesn't solve the problem in my case. 

However, when I connect it to docker bridge before I start the container it does WORK!!
`docker network connect bridge <container>
docker start <container>`

**Comment by zybQAQ** [comment]
AnyBody have ideas about this issue? In 2021 year, I have thie same problem... for I tried to move docker from /var/lib/docker to other disk , I copy all of /var/lib/docker and paste in other disk ,restart docker service,all containers down,and throws this error
`Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:339: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2021-06-24T22:38:31+08:00\\\" level=fatal msg=\\\"no sandbox present for b02d166a3085946e1ba5a87c07b8055e11cbc124ac02f978453ac2c2e015da0f\\\" \\n\""
`

**Comment by thaJeztah** [comment]
Let me close this one, as it went stale
