### ISSUE TITLE
Docker returns a warning as a critical error when running docker build user on windows in Powershell ISE

### ISSUE THREAD

**Issue by cannontrodder** [moby/moby#22623]
Seems like the same issue mentioned here: https://forums.docker.com/t/a-docker-build-command-returning-a-warning-as-a-critical-error/8531 which I can't seem to see as a current issue in github.

When I run a docker build command that ADDs files from the windows filesystem, I get the security warning about permissions. That's fine, I can resolve that (or choose to ignore it) but when running in Windows Powershell script in Powershell ISE this is returned as a critical error.

Ideally, I'd like to suppress this error with a command line switch.

PS P:> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

5      0      10586  122     

PS P:> docker --version
Docker version 1.11.1, build 5604cbe

PS P:> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: docker
ID: PENT:6U4L:VWM5:QAPO:JR3I:7LAC:25RG:JRCQ:6PUB:MEGT:VV67:FSIQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
![image](https://cloud.githubusercontent.com/assets/6507976/15139554/a34f6160-168e-11e6-826a-d2f5cbae4b5d.png)

Running in Windows 10 Professional

**Steps to reproduce the issue:**
Run script that uses ADD to include windows files in a docker image from Powershell ISE

**Comment by friism** [comment]
Related to this: https://github.com/docker/docker/issues/21368

**Comment by DmitryEfimenko** [comment]
+1

**Comment by cannontrodder** [comment]
According to this in the next version the error will come out on stdout not stderr so should fix it: https://github.com/moby/moby/issues/20397

**Comment by thaJeztah** [comment]
Ah, yes, looks like I overlooked this one. Thanks @cannontrodder !
