### ISSUE TITLE
Error response from daemon: Cannot start container lstat /dev/.rename_device.lock: no such file or directory

### ISSUE THREAD

**Issue by awu-platfora** [moby/moby#22710]
Docker very sporadically cannot start a container and gives this error:

```
12-May-2016 15:37:59    Error response from daemon: Cannot start container cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417: lstat /dev/.rename_device.lock: no such file or directory
```

Our build system run in AWS and we build inside the containers. The very next job run on the same machine with same container will start without issue. 

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

``````
Containers: 1
Images: 158
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-264857-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.555 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.666 GB
 Metadata Space Used: 11.25 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.5-15.26.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-252-1-90
ID: 2Y65:XIRX:EYHK:T7HR:C5RF:CEPX:MIUA:64WC:562F:NFO2:MSJY:IKFQ```
``````

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
This seems to be very transient and I am unable to reliably reproduce the issue.

Our scripts are doing the following:
1. Remove any containers that may be previously running
2. Pull build container
3. docker run with `--privileged --rm -t` options as well as mounting host volume folders with `-v`

**Describe the results you received:**
The following logs are from /var/log/docker at the time of failure and includes the next successful run.

```
time="2016-05-12T15:20:15.233530335-07:00" level=info msg="POST /v1.21/containers/f3ea8d6fea09c24c4b4654b8bb610906cdc9bf42223e710abac8d07e6adb3448/start"
time="2016-05-12T15:33:46.185212412-07:00" level=info msg="GET /v1.21/containers/f3ea8d6fea09c24c4b4654b8bb610906cdc9bf42223e710abac8d07e6adb3448/json"
time="2016-05-12T15:33:46.560844045-07:00" level=info msg="DELETE /v1.21/containers/compile?force=1"
time="2016-05-12T15:33:50.298809369-07:00" level=info msg="POST /v1.21/containers/create"
time="2016-05-12T15:33:50.641213603-07:00" level=info msg="POST /v1.21/containers/8dcc34dbe11e6914d93fe83da85a8c18bff7f62aa458ab50d1df762eb5c2207f/attach?stderr=1&stdout=1&stream=1"
time="2016-05-12T15:33:50.641696667-07:00" level=info msg="POST /v1.21/containers/8dcc34dbe11e6914d93fe83da85a8c18bff7f62aa458ab50d1df762eb5c2207f/start"
time="2016-05-12T15:35:51.142006298-07:00" level=info msg="GET /v1.21/containers/8dcc34dbe11e6914d93fe83da85a8c18bff7f62aa458ab50d1df762eb5c2207f/json"
time="2016-05-12T15:37:29.388331688-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:37:29.428616105-07:00" level=info msg="DELETE /v1.21/containers/8dcc34dbe11e?force=1"
time="2016-05-12T15:37:34.135112857-07:00" level=info msg="POST /v1.21/images/create?fromImage=*****%2Fbase-build%3Alatest"
time="2016-05-12T15:37:34.150172558-07:00" level=warning msg="Error getting v2 registry: endpoint does not support v2 API"
time="2016-05-12T15:37:37.090081923-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:37:49.374345773-07:00" level=info msg="POST /v1.21/containers/create"
time="2016-05-12T15:37:49.841185094-07:00" level=info msg="POST /v1.21/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417/attach?stderr=1&stdout=1&stream=1"
time="2016-05-12T15:37:49.841647585-07:00" level=info msg="POST /v1.21/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417/start"
time="2016-05-12T15:37:50.077394244-07:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417/shm: invalid argument\nfailed to umount /var/lib/docker/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417/mqueue: invalid argument"
time="2016-05-12T15:37:50.077443373-07:00" level=error msg="Error unmounting device cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417: UnmountDevice: device not-mounted id cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417"
time="2016-05-12T15:37:50.077536013-07:00" level=error msg="Handler for POST /v1.21/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417/start returned error: Cannot start container cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417: lstat /dev/.rename_device.lock: no such file or directory"
time="2016-05-12T15:37:50.077580249-07:00" level=error msg="HTTP Error" err="Cannot start container cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417: lstat /dev/.rename_device.lock: no such file or directory" statusCode=500
time="2016-05-12T15:37:50.078287096-07:00" level=info msg="DELETE /v1.21/containers/cefad363db1c915d395c0bd5a646055fc253074a7f31222324e1f6a70d843417?v=1"
time="2016-05-12T15:37:59.321763331-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:38:00.273418822-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:38:49.145272920-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:38:49.242570349-07:00" level=info msg="POST /v1.21/images/create?fromImage=*****%2Fbase-build%3Alatest"
time="2016-05-12T15:38:49.258145415-07:00" level=warning msg="Error getting v2 registry: endpoint does not support v2 API"
time="2016-05-12T15:38:52.321446977-07:00" level=info msg="GET /v1.21/containers/json?all=1"
time="2016-05-12T15:39:05.534859132-07:00" level=info msg="POST /v1.21/containers/create"
time="2016-05-12T15:39:05.989228077-07:00" level=info msg="POST /v1.21/containers/8be613a693b7f35c2313aff24bb8df7708a5a2dd288d2b70d6bc0253f35c4a17/attach?stderr=1&stdout=1&stream=1"
time="2016-05-12T15:39:05.989686465-07:00" level=info msg="POST /v1.21/containers/8be613a693b7f35c2313aff24bb8df7708a5a2dd288d2b70d6bc0253f35c4a17/start"
time="2016-05-12T15:48:35.363312999-07:00" level=info msg="GET /v1.21/containers/json"
time="2016-05-12T15:52:17.998789289-07:00" level=info msg="GET /v1.21/containers/json?all=1"
```

**Comment by thaJeztah** [comment]
Looks like this file is created here https://git.fedorahosted.org/cgit/initscripts.git/plain/src/rename_device.c

> and we build inside the containers

Can you explain what / how you build? Are you running docker-in-docker (i.e. run a docker daemon inside the container)?

**Comment by awu-platfora** [comment]
We are not running docker-in-docker. 

To build, we mount the host volume which contains our source code into the container, the container itself is built from the ubuntu 14.04 image pulled from the docker hub and we installed our build dependencies ( java, python, etc.), and we leave behind the compiled java package.

We also use the same container to run JUnit tests which also has our compiled build artifacts from the host mounted into the container, which then runs our tests.

The first thing we attempt to do inside the container is to start sshd, however, it does not appear from the log messages on our build system that we get that far, the container itself does not start and throws the error.

The base layers of the image has not been updated in quite awhile (I'm guessing 1.3.x?) as well as it is coming from one of our older docker private hubs we host.

**Comment by justincormack** [comment]
As @thaJeztah says, this file seems to be coming from `udev`, and is probably related to the fact you are running with `--privileged` so it is sharing the host `/dev`. But why there is some sort of race is less clear. Do you actually need to run with `--privileged`? For most use cases you can just use eg `--cap-add sys_admin` to get the privileges you need without getting fullprivileges which gives full host system access.

**Comment by awu-platfora** [comment]
@justincormack - I see, I will look into using  `--cap-add` `sys_admin` but that makes sense, I only recently added in the `--privileged` flag. We only need `--privileged` for certain unit test runs, specifically when we are setting up MapR inside the container; their install process creates/modifies rules that required `--privileged`. I can create a case to limit when we call `--privileged` to only the MapR runs to hopefully reduce this from occurring.

**Comment by justincormack** [comment]
@awu-platfora what do they do that requires `--privileged`? generally there should be ways to work around this, and always good to try not to use it. Although it would be good to also fix the underlying issue. Can you also test with a more recent version of docker, as this may have been fixed.

**Comment by awu-platfora** [comment]
@justincormack They attempt to set `ulimit -n`, nice level, `ulimit -u`, `sysctl -q -w net.core.somaxconn`. They also try to create `udev` rules but this step does not seem to succeed with or without `--privileged`

Locally I am running 1.11.1 (docker-machine on OSX), however, we are using Amazon Linux on AWS for the build system and are bound to their version.

**Comment by mkleint** [comment]
```
linux runtime spec devices: lstat /dev/.udev/data/n564: no such file or directory
linux runtime spec devices: lstat /dev/.rename_device.lock: no such file or directory
linux runtime spec devices: lstat /dev/.udev/queue.tmp: no such file or directory

```
I'm seeing these reasonably frequently when running docker:*dind with privileged:true on AWS ECS (latest official AMI), docker 1.12.6, overlay storage driver

**Comment by thaJeztah** [comment]
closing as this went stale, and doesn't look like a bug in our code base. Ulimits can now also be set as option on `docker run` (through the `--ulimit` flag), so possibly the container can be started with the correct ulimits so that the container's process doesn't require privileged
