### ISSUE TITLE
random "unable to remove filesystem."

### ISSUE THREAD

**Issue by chromerobv** [moby/moby#22734]
randomly when i try and rm a container i get.

> Error response from daemon: 500 Internal Server Error: Unable to remove filesystem for 74bef250361c7817bee19349c93139621b272bc8f654ae112dd4eb9652af9515: remove /var/lib/docker/containers/74bef250361c7817bee19349c93139621b272bc8f654ae112dd4eb9652af9515/shm: device or resource busy

the container is no longer listed under docker ps -a but there is leftovers in /var/lib/docker

> # ls -al /var/lib/docker/containers/74bef250361c7817bee19349c93139621b272bc8f654ae112dd4eb9652af9515/
> 
> total 8
> drwx------.  3 root root   16 May 14 02:01 .
> drwx------. 47 root root 4096 May 14 02:23 ..
> drwx------.  2 root root    6 May 14 00:55 shm

this is a brand new setup. running docker 1.11, devicemapper thin pool on centos 7.

> # docker version
> 
> Client:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Wed Apr 27 00:34:42 2016
>  OS/Arch:      linux/amd64
> Server:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Wed Apr 27 00:34:42 2016
>  OS/Arch:      linux/amd64

...

> # docker info
> 
> Containers: 14
>  Running: 14
>  Paused: 0
>  Stopped: 0
> Images: 15
> Server Version: 1.11.1
> Storage Driver: devicemapper
>  Pool Name: vglocal01ssd-docker--pool
>  Pool Blocksize: 65.54 kB
>  Base Device Size: 10.74 GB
>  Backing Filesystem: xfs
>  Data file:
>  Metadata file:
>  Data Space Used: 8.521 GB
>  Data Space Total: 80.53 GB
>  Data Space Available: 72.01 GB
>  Metadata Space Used: 12.98 MB
>  Metadata Space Total: 1.074 GB
>  Metadata Space Available: 1.061 GB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: true
>  Deferred Deletion Enabled: false
>  Deferred Deleted Device Count: 0
>  Library Version: 1.02.107-RHEL7 (2015-12-01)
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: null host bridge
> Kernel Version: 3.10.0-327.13.1.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 24
> Total Memory: 125.7 GiB
> ID: 5C74:BCSY:MLUR:CEXI:5FTG:AUYH:OOLJ:EOQW:7HC4:IGUX:PXM6:LBUU
> Docker Root Dir: /var/lib/docker
> Debug mode (client): false
> Debug mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled`

**Comment by thaJeztah** [comment]
Is this for any container, or a specific one? What image are you using, and what options are you using to start the container? (using bind-mounted volumes, `--privileged` etc.)

**Comment by chromerobv** [comment]
any containers really. mostly my own images just running a java process in them base is phusion/baseimage. 
options are nothing crazy. -v mounting some volumes, setting some env vars with -e, and setting some labels.
no privileged.

but any image does it. ive had swarm do it. interlock. never the same one.

**Comment by chromerobv** [comment]
this is happening to me more and more. i see others have issues open with this happening on aufs.
can i give anything else?

**Comment by littlexiaoxiao** [comment]
Error response from daemon: Unable to remove filesystem for aa12931c4c490c075466bcb320de3f4bfdecd7b2067bcf4ac66dafb9681c8758: remove /var/lib/docker/containers/aa12931c4c490c075466bcb320de3f4bfdecd7b2067bcf4ac66dafb9681c8758/hostconfig.json: read-only file system

**Comment by littlexiaoxiao** [comment]
Error response from daemon: Unable to remove filesystem for 402c146746aed410590159a00d17db666d9de0a80679d772ce1a34b475aab913: remove /var/lib/docker/containers/402c146746aed410590159a00d17db666d9de0a80679d772ce1a34b475aab913/hostconfig.json: read-only file system

**Comment by justincormack** [comment]
Which directories are you mounting with `-v`?

**Comment by thaJeztah** [comment]
closing as this one went stale
