### ISSUE TITLE
Ubuntu/Upstart issues as a container/full machine

### ISSUE THREAD

**Issue by kiorky** [moby/moby#2276]
One again, i am on my upstart-related bunch of issues while putting the stuff in a docker container, so i think it would be good to have a meta bug for upstart issues and a starter for further documentation.
For now:
- configuration of container is not that editable after start (ports, volumes), see #2045 
- you need to tweak a bit some jobs, disable others, and emit some virtual events, see along Dockerfiles and shipped with upstart jobs & scripts
- FIXED in "master: restart/reboot/poweroff from within the container won't work unless we keep sys_boot lxc CAP, the only mean to kill/restart if from a docker restart/kill/stop call, see https://github.com/dotcloud/docker/issues/1960
- docker top <CID> doesnt show any process even if the container is running and well. Indeed when you ssh'in the container, processes are there up and running., see #2277 
- /etc/hostname & /etc/resolv.conf as they are mounted-readonly are also problematic (#2068)
- Some base packages wont install/update either because of CAPS or ReadOnly Files. We repackage them on the fly in the dockerfile and mark them as non upgradable.
  - resolvconf 
  - ntp
  - fuse
- ntpd from container hit apparmor breakage from host, see : #2800

To reproduce all this stuff, you can find my debug env here:
-  https://github.com/makinacorpus/vms/blob/master/docker/make.sh :  this shell help makes images from ubuntu cloudarchives images, plus  some modifications (see dockerfiles) to run smoothly on docker.
  - notice : https://github.com/makinacorpus/vms/blob/master/docker/makinacorpus/ubuntu_template/lxc-setup.conf
  - notice : https://github.com/makinacorpus/vms/blob/master/docker/makinacorpus/ubuntu_template/lxc-stop.conf
  - notice : https://github.com/makinacorpus/vms/blob/master/docker/makinacorpus/ubuntu_template/lxc-cleanup.sh

Use the script like this:

```
git clone https://github.com/makinacorpus/vms.git
cd docker
./make.sh make_image ubuntu
```

then run it:

```
 docker run -d makinacorpus/ubuntu /sbin/init
 docker ps
 ./make.sh dattach $dockerid

```

dups: #1024
links:#3182

**Comment by mike503** [comment]
+1. I was hoping to also use docker as well instead of LXC.

Mainly so that the provisioning scripts and everything can be reused for Packer.

Packer can then produce Docker and Vagrant images for our development and staging, and Docker and/or EC2 for production images... for some reason Packer does not support LXC directly and still refuses to support it officially.

https://github.com/mitchellh/packer/issues/790

Docker still seems more suitable for shippable images, not long running "instances" like a VPS would provide (KVM, Xen, LXC, OpenVZ, etc)

**Comment by jfrazelle** [comment]
what is the actionable item here?

**Comment by jfrazelle** [comment]
ping @kiorky ^

**Comment by kiorky** [comment]
See all open bugs ?

**Comment by kiorky** [comment]
(Plus the ones closes without fixing, like the ntp one)

**Comment by jfrazelle** [comment]
can we close this now

**Comment by kiorky** [comment]
well this isnt fixed ;)

**Comment by pradeepchhetri** [comment]
I tried using `ubuntu-upstart` images but i am unable to start a service. I followed the workaround which i found in another github issue as well but it didn't work too:

```
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl
```

Can you help me out in debugging this.

**Comment by thaJeztah** [comment]
@pradeepchhetri by running `/bin/bash` you're overriding the default command of the image, and upstart will not be started, and not be the primary process of the container, see https://github.com/tianon/dockerfiles/blob/4d24a12b54b75b3e0904d8a285900d88d3326361/sbin-init/ubuntu/upstart/14.04/Dockerfile#L53

If you start it without a custom command, ssh will be running and you can login using the default password `docker.io`;

```bash
docker run -d -it -p 2200:22 ubuntu-upstart:14.04
efd1555328e2034cb8a237a46798ec4a5a4fccd2da3d8518add1bf7aaeda2029

ssh root@192.168.99.100 -p 2200
The authenticity of host '[192.168.99.100]:2200 ([192.168.99.100]:2200)' can't be established.
RSA key fingerprint is 5b:e5:be:07:05:47:06:2a:f8:8d:42:4a:50:3c:61:ca.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[192.168.99.100]:2200' (RSA) to the list of known hosts.
root@192.168.99.100's password:
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.19.0-31-generic x86_64)
....
```

**Comment by pradeepchhetri** [comment]
@thaJeztah Ahh, thank you for the reply. I want to run a curl command after container starts which will install a package that depends on upstart. Should i first ssh and then execute the command on it ?

**Comment by thaJeztah** [comment]
@pradeepchhetri why not build an image using a Dockerfile that uses `ubuntu-upstart` as parent? e.g.

```Dockerfile
FROM ubuntu-upstart:14.04
RUN apt-get update && apt-get install something
```

However, the GitHub issue tracker is not the best place to discuss this; can you ask this question in the #docker IRC channel? There's probably someone there to help you further.

**Comment by LK4D4** [comment]
@thaJeztah do you know what's going on here? I'm certainly not :/

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉
