### ISSUE TITLE
/var/run/docker.sock mount in containers refuse connection after daemon hot upgrade

### ISSUE THREAD

**Issue by BSWANG** [moby/moby#22789]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   e29d696
 Built:        Mon May 16 06:21:25 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   e29d696
 Built:        Mon May 16 06:21:25 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 12
 Running: 6
 Paused: 0
 Stopped: 6
Images: 9
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: cce2610ec7aa247048a35ecdbdc616338-node2
ID: C7W5:3DNC:QNKF:F3FW:MXGW:LMN3:25PB:4MM6:PBCL:YRWN:QLAJ:GWA4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 49
 Goroutines: 120
 System Time: 2016-05-17T19:40:08.476257757+08:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Cluster store: etcd://1.2.3.4:2379/cce2610ec7aa247048a35ecdbdc616338
Cluster advertise: 2.3.4.5:2376
```

**Steps to reproduce the issue:**
1. start docker deamon in Experimental mode to use hot upgrade
2. docker run -v /var/run/docker.sock:/var/run/docker.sock -itd docker
3. attach the "docker in docker" container and use docker commander, no problem.
4. kill the docker daemon thread and rerun docker daemon
5. reattach to the container before, can not connect to /var/run/docker.sock

**Describe the results you received:**

```
dial unix /var/run/docker.sock: connect: connection refused
```

Because the `/var/run/docker.sock` mount not update after daemon thread restart, there is the old unix socket file mounted in container, however the docker daemon listen on a new unix socket file.

**Describe the results you expected:**
Docker daemon should auto update `/var/run/docker.sock` mount, thus application can listen on the latest daemon API, and do something such as service-discovery, docker-plugins,etc.

**Additional information you deem important (e.g. issue happens only occasionally):**
Many docker-plugins(network, volume, ipam) run in containers use the `/var/run/docker.sock` to communicate with docker daemon, so hot-upgrade should assure this socket file be mount correctly after daemon thread restart.

**Comment by thaJeztah** [comment]
Thanks @BSWANG! I'll add this to the 1.12 milestone (as it relates to https://github.com/docker/docker/issues/2658)

/cc @crosbymichael

**Comment by justincormack** [comment]
Yes, the daemon will need to reopen the same inode for a bind mount to work, not delete and recreate.

**Comment by phemmer** [comment]
You can't reuse an existing unix domain socket file. You have to unlink it. The only way you could get this to work is to pass the open file descriptor to the new process. On systemd this wouldn't be an issue as that's already how systemd does it (passes it on start). But for non-systemd systems, docker will have to hand the file descriptor off.

**Comment by crosbymichael** [comment]
We will try our best to find a good solution to fix this but its not necessarily a pre req for completing the daemon restore feature.  Its an advanced usecase and if the fix is too complicated, it maybe better to to **do a workaround like not mounting the socket but bind mounting the directory where the socket is created**.  That will solve your issue today and in the future.

**Comment by mpalmer** [comment]
Do you have any workable suggestions for how to achieve the workaround you suggest, @crosbymichael?  Bind-mounting all of `/var/run` is a non-starter (for reasons that are hopefully obvious), moving the socket to a subdirectory breaks all the default tools (wedging an env var into *every* process on a system is surprisingly hard to do, especially when you can't necessarily just reboot machines with wild abandon), and the Docker upstart config doesn't support multiple `-H` options in `DOCKER_OPTS`.

**Comment by thaJeztah** [comment]
> and the Docker upstart config doesn't support multiple -H options in DOCKER_OPTS.

@mpalmer you could configure the `-H` through a daemon.json configuration file instead of through upstart https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
