### ISSUE TITLE
Internal DNS hangs for 2.5 second each ~2000 requests

### ISSUE THREAD

**Issue by nordluf** [moby/moby#22791]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:57:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:57:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 152
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-2097165-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.21 GB
 Data Space Total: 107.4 GB
 Data Space Available: 94.16 GB
 Metadata Space Used: 20.66 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/homeFS/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /mnt/homeFS/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: RFRemix 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: luf-t450s
ID: 2B45:OD3N:ZLYL:EVD2:FCJP:Q5US:O4OG:6QLP:I3JM:QCOZ:OASI:GKRR
Docker Root Dir: /mnt/homeFS/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
Cluster store: consul://127.0.9.1:8500
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have internal DNS server in the overlay network. All containers start with --dns=[internal_ip] of this server. Then I start my own test app inside this overlay network to check performance of this DNS server. If I have `nameserver 127.0.0.11` in the resolv.conf, then one request for (about) 2000 requests hangs for 2500ms and then resolve with correct IP. In the DNS server we sent IP for hanged request in proper time. After changing resolve.conf to be `nameserver 10.0.100.254` test work already for 6 hours without any issues. 

I think this issue is related to the #22185

**Comment by thaJeztah** [comment]
Have you checked your log files if you see the same error message as is mentioned in https://github.com/docker/docker/issues/22185 ?

**Comment by nordluf** [comment]
I checked - no errors, no warnings. Only some infos after changing resolv.conf - 
level=info msg="Skipping update of resolv.conf file with ipv6Enabled: false because file was touched by user"

**Comment by thaJeztah** [comment]
do you have a minimal reproducible case?

**Comment by nordluf** [comment]
I can make it. Is it possible to provide commands to execute, or I need to make it more complex and easy ti use?

**Comment by thaJeztah** [comment]
just the commands should be fine. Basically, something that the networking team is able to execute, and reproduce a comparable situation

**Comment by nordluf** [comment]
First, you need docker-engine works with --cluster-store=consul://<consulip>:8500 or any other store. Then:
```
docker network create -d=overlay --subnet=10.0.0.0/24 testnet
docker run -d -v /var/run/docker.sock:/var/run/docker.sock nordluf/swarm-discovery --debug
docker run -d --net-alias=ngx -net=testnet nginx
docker run --rm --dns=10.0.0.254 --net=testnet nordluf/dnstestapp
```

After some seconds you'll see output of dnsapp container: 
`Resolving takes 2503ms after 1860 requests `
It means that name resolution hangs for 2500ms

**Comment by sanimej** [comment]
@nordluf Is it possible the DNS server is doing some throttling (many servers typically do) ? In the embedded DNS server we try to use the same UDP socket for all the queries from a container instead of opening a new one every time. So when you are sending lot of queries the server might throttle some responses.

**Comment by nordluf** [comment]
This is my own DNS server without throttling at all. Also, you can try change resolv.conf inside dnstestapp container to work with my DNS server directly - there will be no hangs

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
