### ISSUE TITLE
Wire up `variant` and `features` for selecting images from manifest lists

### ISSUE THREAD

**Issue by friism** [moby/moby#22816]
From distribution: https://github.com/docker/docker/blob/master/distribution/pull_v2.go#L619

It would be great to get this wired up in engine so that images get OS variant metadata when built and if this were used when choosing an image from a manifest list.

This has applicability for Windows, where we need to disambiguate between images for Nanoserver and Windowsservercore.

cc @glennc @tianon @aaronlehmann @jstarks

**Comment by thaJeztah** [comment]
I think this is all done
