### ISSUE TITLE
volume remove+create false positive window when done fast enough

### ISSUE THREAD

**Issue by erikh** [moby/moby#22827]
**Output of `docker version`:**
https://gist.github.com/anonymous/ce7c17167ebdb78f87579d85c6eb3ae6
**Output of `docker info`:**

(see above)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centos 7.2 inside vbox: vagrantfile is here: https://github.com/erikh/volplugin/blob/master/Vagrantfile

**Steps to reproduce the issue:**
1. create a volume
2. remove it
3. create it again quickly

**Describe the results you received:**

It seems that the volume drivers do not get called when quickly cycling through create/delete cycles. Perhaps there is some TTL or expiration which is being triggered; not sure if this is a feature or not.

What happens is like when you create twice: it silently ignores the create and makes it available for use. Since volplugin has not actually processed the create, nothing is created and therefore badness happens at mount/remove time.

Here is some code which triggers the bug, undistilled: it's a battery test. I sincerely apologize for its clarity; I am an army of one.

https://github.com/contiv/volplugin/blob/master/systemtests/battery_test.go#L77

What it does is:
1. Across 3 hosts, create 15 volumes apiece spread random. Since docker will ignore the multiple creates since /List returns the same payload on all hosts, this is successful.
2. mount the volumes on all hosts.
3. one of volplugin's key features is mutex locks on all volume mounts, and that's what's tested here. So, two hosts should fail and one succeeds.

What ends up happening is that after the first set of create/delete, the signal is not fired like I describe above; then the mounts/removes fire and since there is no record/volume that actually exists, volplugin vomits.

**Describe the results you expected:**

the volume should be re-created, and the appropriate signal sent to the volume driver.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is reproducible every time for me, and a significant show-stopper for running volplugin in containers. Please let me know what you need.

**Comment by erikh** [comment]
So, just to be clear, this line is keeping this test passing:

https://github.com/contiv/volplugin/blob/master/systemtests/battery_test.go#L136

I think it's self-explanatory. :) In the event you do try the code, please remove this line to trigger the bug.

**Comment by thaJeztah** [comment]
ping @cpuguy83 @anusha-ragunathan ptal

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
