### ISSUE TITLE
Some mistakes in remote api doc v1.23

### ISSUE THREAD

**Issue by coldTea214** [moby/moby#22848]
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23

Create a container -- status codes:
[mistake] 404: no such container --> image
[miss] 409: the name "xxx" is already in use
[confuse] 406: impossible to attach.
How to trigger a 406 error in a create action?

Start a container -- status codes:
[mistake] 404: no such container --> can also be "executable file not found in $PATH"

**Comment by thaJeztah** [comment]
The MarkDown based docs have been replaced with a swagger file, and many changes were made since this was reported; feel free to open a pull-request though if there's still some mistakes in that file; https://github.com/moby/moby/blob/6f8c671d702197a189d162d86a3f4cccfa5a3db2/api/swagger.yaml
