### ISSUE TITLE
"docker build" output is confusing when using "--build-args"

### ISSUE THREAD

**Issue by nshalman** [moby/moby#22860]
I couldn't easily find an existing issue that matches this one. Apologies if I missed it.

**Output of `docker version`:**

``````
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64```
``````

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:16-294913-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.052 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.28 GB
 Metadata Space Used: 1.54 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 11.74 GiB
Name: ubuntu1404
ID: GRIA:F3RM:7DCR:GNEI:XUB6:D2R5:A6S4:R5OD:4N5Z:2YR2:47SY:443B
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04 in a VM (hypervisor happens to be SmartOS)

**Steps to reproduce the issue:**

Example Dockerfile:

```
$ cat Dockerfile
```

```
FROM alpine:latest

ARG USER=somebody
USER ${USER}
ENTRYPOINT ["/bin/bash", "-i", "-l"]
```

Use `--build-arg`:

```
$ docker build --tag foo:1 --build-arg USER=notme .
```

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:latest
 ---> 13e1761bf172
Step 2 : ARG USER=somebody
 ---> Running in 1f0559519615
 ---> d18a707a6090
Removing intermediate container 1f0559519615
Step 3 : USER ${USER}
 ---> Running in 234964abd42f
 ---> 8a0fc8e92102
Removing intermediate container 234964abd42f
Step 4 : ENTRYPOINT /bin/bash -i -l
 ---> Running in 98ba2ad02ec9
 ---> 598c5f8c0113
Removing intermediate container 98ba2ad02ec9
Successfully built 598c5f8c0113
```

```
$ docker run -it --rm foo:1
docker: Error response from daemon: linux spec user: Unable to find user notme.
```

**Describe the results you received:**

When running `docker build` I see this line:

```
Step 2 : ARG USER=somebody
```

**Describe the results you expected:**

I expect to see this line when I've used `--build-args USER=notme`:

```
Step 2 : ARG USER=notme
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
I don't know about this. The output is a bit confusing I agree, but it is simply echoing out the lines of the Dockerfile, and changing some of them seems a bit inconsistent.

**Comment by duglin** [comment]
I agree this could be misleading, but in this case the "=" doesn't mean assign, it defines the default value if one wasn't provided on the build command. I suppose it might be possible to print something to indicate that ARG is already defined by the build command and this is therefore just enabling it for the build (and the value provided is ignored), but since we don't print anything for other metadata-setting commands (like ENV) I'm included to not change the build output. More doc updates are always welcome though.

**Comment by thaJeztah** [comment]
Yes, I was wondering if we should as well. For example `RUN echo $PATH` also wouldn't replace the variable, so doing it for other instructions would be inconsistent.

**Comment by nshalman** [comment]
Improving the documentation will help a bit (see #22906), but honestly, as a relatively new user with little appreciation for the history behind why "docker build" echoes each line of the Dockerfile, I personally care much more about what is actually being done rather than what is being read.

If that's a lot of work to make it be the case for the many different kinds of lines in a Dockerfile, then this is a larger feature request rather than a simple bug report.

I leave it in your good hands to decide whether this is something to consider improving or not.

**Comment by nshalman** [comment]
I think this is probably not even relevant to this repository any more. Closing.
