### ISSUE TITLE
New Dockerfile instruction to SYMLINK non-persistent and read-only files/folders from host during build

### ISSUE THREAD

**Issue by brunoborges** [moby/moby#22864]
There are workarounds to prevent creating large images, by squashing them, or downloading files from remote location instead of using COPY. This issue is to track the proposal for a new COPY instruction that simply does not creates another layer.

Take the following sample Dockerfile definition:

``` Dockerfile
FROM busybox
COPY veryLargeFile.zip ./
RUN unzip ./veryLargeFile.zip && \
    sh someScriptFromLargeFile.sh && \
    rm veryLargeFile.zip
```

The resulting image of Dockerfile above is around twice as large as `veryLargeFile.zip`. 
The `rm` instruction at the end does not help much. 
## Workaround 1: squash

First solution to this problem would be to [squash](https://github.com/jwilder/docker-squash) the image. Not a 1st-class feature.
## Workaround 2: download files from a server on piped RUN

A usual practice is to download the file from somewhere instead of using COPY:

``` Dockerfile
FROM busybox
RUN wget http://somehost/veryLargeFile.zip && \
    unzip ./veryLargeFile.zip && \
    sh someScriptFromLargeFile.sh && \
    rm veryLargeFile.zip
```

The resulting image of Dockerfile above is much smaller than the first version.
But files used as part of Docker images may not be always available on remote servers to be downloaded.
## Workaround 3: run temporary server before building image

A third workaround would be to run a local container before the build, that will serve the large file (that lives along with Dockerfile to be built) over HTTP (or FTP):

``` bash
#!/bin/sh
echo "Building Docker image."
echo "Starting local file server..."
CID_SERVER=$(docker run -d -v `pwd`:/usr/share/nginx/html:ro -d nginx:stable-alpine)
IP_SERVER=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID_SERVER})

docker build --build-arg "IP_SERVER=$IP_SERVER" -t imageName .

docker rm -f $CID_SERVER
```

And the Dockerfile looks like:

``` Dockerfile
FROM busybox
ARG IP_SERVER
RUN wget http://$IP_SERVER/veryLargeFile.zip && \
    unzip ./veryLargeFile.zip && \
    sh someScriptFromLargeFile.sh && \
    rm veryLargeFile.zip
```

The problem with this 3rd workaround is that build becomes dependent on a shell script and on a second container to temporarily serve files. The image cannot be built with simple `docker build`.

It would be better if there was a convenient, OOTB, solution to this problem.

**Comment by justincormack** [comment]
There is a current PR for flattening images, see https://github.com/docker/docker/pull/22641

**Comment by brunoborges** [comment]
Not sure if flattening would fix the issue. #22641 has this:

        Flattening does not destroy any images or layers, and preserves the build cache.

What the issue I raise here is actually about, is to prevent needed temporary files from persisting into the image (i.e. software installers, source tar.gz files, rpm/deb packages, etc).

I agree that mounting a folder during build is not the way to go, but neither should be using a hack to download a file over HTTP (see workaround 3):

A new Dockerfile instruction such as `SYMLINK` may be a good approach:
 - no layer is created for this instruction
 - file/dir is linked from inside the during-build-containers back to the host environment as read-only
 - file/dir won't be persisted on any layer nor the final image
 - if file referenced by `SYMLINK` does not exist, build shall fail

Some feedback by Docker Inc. folks here would be nice.

**Comment by cpuguy83** [comment]
@brunoborges The build machine would contain this, but the image that you distribute would not.

**Comment by brunoborges** [comment]
@cpuguy83 but that is the intention. SYMLINK'ed files and folders are only necessary to _build_ the image. The distributable image does not require these files anymore, and thus these files should not be persisted in any image layer, to save image size.

**Comment by cpuguy83** [comment]
@brunoborges It seems like we're saying the same thing...
Yes, you need the build tools to build the image, they'll be in there as part of the build cache on the build machine, but once flattened, assuming the tools were removed as part of the build, they will be gone from the image.

**Comment by brunoborges** [comment]
@cpuguy83 you saying then that #22641 would save image size after flattening them? I read that and seems it won't, because it won't destroy layers. 

Each COPY is a layer. And even if the COPY'ed file is removed on a subsequent RUN, that layer won't be destroyed by flattening.

**Comment by cpuguy83** [comment]
@brunoborges It doesn't destroy the layers (which are part of the build cache). The final image that the build creates is an image that is literally the `FROM` image with 1 layer on top.

**Comment by brunoborges** [comment]
@cpuguy83 what happens with `veryLargeFile.zip` that was COPY'ed, then removed? Will it cound on the image size?

**Comment by cpuguy83** [comment]
@brunoborges It will not be part of the final image, but the layers will still be on the system that built it.
