### ISSUE TITLE
network scoped alias cannot isolate network properly

### ISSUE THREAD

**Issue by Sakib37** [moby/moby#22886]
**Output of `docker version`:**

```
(paste your output here)
```

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

```
(paste your output here)
```

Containers: 14
 Running: 9
 Paused: 0
 Stopped: 5
Images: 7
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.566 GiB
Name: Openstack
ID: ZA4W:C5QO:Y2WM:ZCJC:QLDV:4CCW:RJCV:MIJX:X7LO:2FPJ:EX4A:RTTN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vitualbox VM
Ubuntu 15.10 

**Steps to reproduce the issue:**
1. Follow the "Network-scoped alias" section in the documentation available in [https://docs.docker.com/engine/userguide/networking/work-with-networks/ ](url)
2. $ docker network create -d bridge --subnet 172.25.0.0/16 isolated_nw
3. $ docker run --net=isolated_nw -itd --name=container4 --link container5:c5 busybox
    $ docker run --net=isolated_nw -itd --name=container5 --link container4:c4 busybox
4. $ docker network create -d bridge --subnet 172.26.0.0/24 local_alias
5. $ docker network connect --link container5:foo local_alias container4
    $ docker network connect --link container4:bar local_alias container5
6. $ docker network disconnect isolated_nw container5
7. $ docker run --net=isolated_nw -itd --name=container6 --net-alias app busybox
8. $ docker network connect --alias scoped-app local_alias container6

**Describe the results you received:**
container6 is now aliased as app in network ''isolated_nw'' and as scoped-app in network ''local_alias".
attach with container5 and ping to 'app' and 'scoped-app' both are successful. 
## My outputs for the scenarios:

$ docker inspect --format='{{json .NetworkSettings.Networks}}' container5 | python -m json.tool 
{
    "local_alias": {
        "Aliases": null,
        "EndpointID": "394b57c70a056ba684b3963d2f5d467c94acfabfbc3f9fbc4ab12b2cffaa1bdc",
        "Gateway": "172.26.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAMConfig": {},
        "IPAddress": "172.26.0.3",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "Links": null,
        "MacAddress": "02:42:ac:1a:00:03",
        "NetworkID": "d232553af4f4b1fd296fe5f54954ba111ff6d8fa96df893ad34f3550acdf567e"
    }
## }

$ docker inspect --format='{{json .NetworkSettings.Networks}}' container6 | python -m json.tool 
{
    "isolated_nw": {
        "Aliases": [
            "app"
        ],
        "EndpointID": "ca03b7330acbbece8af2b8ca86ec6eb60f50fa7d8e3a205a3d275378a0b7c162",
        "Gateway": "172.25.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAMConfig": null,
        "IPAddress": "172.25.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "Links": null,
        "MacAddress": "02:42:ac:19:00:03",
        "NetworkID": "9ab70d61f57c320cdf08e157531465ab67312c1e5897a3ce9b5c11b9785231d8"
    },
    "local_alias": {
        "Aliases": [
            "scoped-app"
        ],
        "EndpointID": "fa59cc6358347f10ebb47ea8ccde843ec9e3311e8d1a1126b8591b5dd5eea1a3",
        "Gateway": "172.26.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAMConfig": {},
        "IPAddress": "172.26.0.4",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "Links": null,
        "MacAddress": "02:42:ac:1a:00:04",
        "NetworkID": "d232553af4f4b1fd296fe5f54954ba111ff6d8fa96df893ad34f3550acdf567e"
    }
## }

$ docker network inspect --format='{{json .Containers}}' isolated_nw | python -m json.tool
{
    "6aa56e8884185d3c2940736e7d6533400faf8cc69fd20369bda22a754cae1248": {
        "EndpointID": "0338356431b9742a78919bac30a5d444691c272115bbc445486785dac174641d",
        "IPv4Address": "172.25.3.3/16",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:19:03:03",
        "Name": "container3"
    },
    "71481f6ddd2b2b60137439c5e947203f57a78eeb55a8fb128867e5a64797e91e": {
        "EndpointID": "dadc5a945a3ae8a33469297bacbeb03919127b7b5660a5b23581745d4320b42a",
        "IPv4Address": "172.25.0.2/16",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:19:00:02",
        "Name": "container2"
    },
    "7e645b6ae256262e5685245bbfd9e65fd611ed017f4d1a206cc1762ba239a806": {
        "EndpointID": "ca03b7330acbbece8af2b8ca86ec6eb60f50fa7d8e3a205a3d275378a0b7c162",
        "IPv4Address": "172.25.0.3/16",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:19:00:03",
        "Name": "container6"
    },
    "e7fac60e4b41c626fd89f1509b70a13bd1d99fc187638d52f8ca11513ac79450": {
        "EndpointID": "f407329c8673e9fc79d7dd477cbd80cb9c938e1841119abf9fc07e500f4bfdb9",
        "IPv4Address": "172.25.0.4/16",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:19:00:04",
        "Name": "container4"
    }
## }

$ docker network inspect --format='{{json .Containers}}' local_alias | python -m json.tool
{
    "7e645b6ae256262e5685245bbfd9e65fd611ed017f4d1a206cc1762ba239a806": {
        "EndpointID": "fa59cc6358347f10ebb47ea8ccde843ec9e3311e8d1a1126b8591b5dd5eea1a3",
        "IPv4Address": "172.26.0.4/24",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:1a:00:04",
        "Name": "container6"
    },
    "e7fac60e4b41c626fd89f1509b70a13bd1d99fc187638d52f8ca11513ac79450": {
        "EndpointID": "c7b2abf7d16bf5e105aa116e1178c064f35cd871b09a71d8892be26d7a4d146a",
        "IPv4Address": "172.26.0.2/24",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:1a:00:02",
        "Name": "container4"
    },
    "fe3bf1d908560f07028ee654c7b4611eee8e115c689ab47a1b72578cc142ae4b": {
        "EndpointID": "394b57c70a056ba684b3963d2f5d467c94acfabfbc3f9fbc4ab12b2cffaa1bdc",
        "IPv4Address": "172.26.0.3/24",
        "IPv6Address": "",
        "MacAddress": "02:42:ac:1a:00:03",
        "Name": "container5"
    }
## }

$ docker attach container5
/ # ping -w3 app
PING app (127.0.53.53): 56 data bytes
64 bytes from 127.0.53.53: seq=0 ttl=64 time=0.016 ms
64 bytes from 127.0.53.53: seq=1 ttl=64 time=0.052 ms
64 bytes from 127.0.53.53: seq=2 ttl=64 time=0.076 ms

--- app ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.016/0.048/0.076 ms
/ # ping -w3 scoped-app
PING scoped-app (172.26.0.4): 56 data bytes
64 bytes from 172.26.0.4: seq=0 ttl=64 time=0.044 ms
64 bytes from 172.26.0.4: seq=1 ttl=64 time=0.107 ms
64 bytes from 172.26.0.4: seq=2 ttl=64 time=0.151 ms

--- scoped-app ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.044/0.100/0.151 ms
/ # 

**Describe the results you expected:**

As we already disconnected container5 from 'isolated_nw' in step 6, it should not be able to ping "app''(which is alias of container6 in 'isolated_nw' network)
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mavenugo** [comment]
@Sakib37 as you can see ` PING app (127.0.53.53): 56 data bytes` the app is resolved to `127.0.53.53` which doesnt belong to `isolated_nw` (172.25.0.0/16). It seems the DNS resolution for `app` is performed by an external DNS server ?

**Comment by Sakib37** [comment]
Thank you for your response. Yes, you are correct. The ping request for 'app' is replied by 127.0.53.53. FYI, this is a fresh test VM for only docker. So there is no external DNS server. Also I do not get it how an external DNS server will even know about 'app' when it is created only for ''isolated_nw'' inside docker.

Even if there is any external DNS server, as I created container6 alias 'app' for 'isolated_nw', no one outside of 'isolated_nw' should get access to 'app', isn't it? I do not understand how an external DNS could possibly get access to 'isolated_nw' network or 'app' alias for container6. Can you please clarify? 
However if you know any docker config which may create an ip ''127.0.53.53'' please let me know. 
Thanks

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
