### ISSUE TITLE
Temporary integration with persistent data during docker build.

### ISSUE THREAD

**Issue by brianbruggeman** [moby/moby#22954]
There is a strong need in provisioning/building docker instances to have some sort of mechanism of copying temporary data during the build process to a docker instance.  Later that temporary data can be (and often is) removed.  In some cases, this could be the installation of a local repository without adding credentials to the docker image.  In other instances, (e.g. gentoo), this might be several gigabytes worth of binary packages, only some of which are needed but many are used in other repositories.  The mountable volume mechanism seems kludgy at best considering that in many cases, I'll likely already have much of what I want on my local host.  A share with a temporary mount point only available during build would be far more preferable.

Note: I'm new to docker, but I feel like this issue has not been properly addressed.

**Comment by justincormack** [comment]
We would like to support these use cases, and there are other issues created requesting this. The problem is that it then adds a requirement that maybe will not be met if someone else wants to build your Dockerfile, or you want to build it on CI or Docker Hub automated builds, where the data will not necessarily be available, so the build becomes non repeatable. So we want to have a solution that has fallbacks eg to the network.

**Comment by brianbruggeman** [comment]
Thanks for taking the time to respond.  I'm somewhat confused as to why that's really an argument.  While I understand the desire to build a docker ecosystem rapidly and this constraint is one way of ensuring idempotent behavior, I completely disagree with that philosophy from a practical standpoint for getting things done:  building virtual environments shouldn't be tied to where you run that build command.   And it's unlikely that I want all of my docker images available to the public.  I do want them visible and buildable by my team -- but I can control how my team uses the dockerfile through our processes.  I hope that makes sense.

My ultimate desire would be to use a docker repository for both development, continuous integration and continuous deployment.  Once the image is created by the developer, I don't want QA and Infrastructure to be recreating the images -- I want them to use that docker image directly.  As a consequence, I could care less if QA and Infra can actually build it.  I only care if my development team can -- and I can ensure that by setting up internal team processes.

**Comment by vdemeester** [comment]
@brianbruggeman the workflow you describe is almost the most common workflow with docker.

Developpers can build the image in dev but the 'final' image, that will be passed through each stage of the continuous deployement pipeline, have to be built as part of this pipeline (first steps). Thus it kinda needs to be reproducible across environment (at least dev machines and continuous integration). I think it also add a certain level of confidence for the dev to be able to build an image the same way the 'final' one is buils.

Having a reproducible way to build image doesn't mean you have to build it each time at each step.

Ans it's just one workflow to use docker…

**Comment by thaJeztah** [comment]
You may be interested in this proposal; https://github.com/moby/moby/issues/32507 (re: gentoo, etc)

**Comment by brianbruggeman** [comment]
@thaJeztah That proposal (and discussion) is definitely what I was thinking about.  I'm going to close this.  Thank you for pointing me to the discussion.

**Comment by thaJeztah** [comment]
Thanks! Feedback on that discussion is appreciated - it's difficult to get it right, so if there's a usecase that's not mentioned there, feel free to add :+1:
