### ISSUE TITLE
hack/make.sh dynbinary ubuntu fails

### ISSUE THREAD

**Issue by kshcherban** [moby/moby#23018]
Hello,

Can not build docker v1.11.1 ubuntu package using hack/make.sh. Tested under 14.04.

**Steps to reproduce the issue:**
- Clone docker repo into clean ubuntu:14.04 container

```
apt-get update
apt-get -y install git
git clone https://github.com/docker/docker
cd docker && git checkout v1.11.1
```
- Install build dependencies

```
apt-get -y install golang-1.6 go-md2man libdevmapper-dev debhelper \
  build-essential libapparmor-dev dh-systemd btrfs-tools
```
- Try to build it 

```
export AUTO_GOPATH=1
hack/make.sh dynbinary ubuntu
```
- See it fails

```
root@4cdfe923d1de:/docker# hack/make.sh dynbinary ubuntu
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

bundles/1.11.1 already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.11.1/dynbinary)
Building: bundles/1.11.1/dynbinary/docker-1.11.1
Created binary: bundles/1.11.1/dynbinary/docker-1.11.1
+++ '[' -x /usr/local/bin/docker-runc ']'

---> Making bundle: ubuntu (in bundles/1.11.1/ubuntu)
cp: cannot stat 'bundles/1.11.1/ubuntu/../binary/docker-1.11.1': No such file or directory
```

Expecting to see deb package.

**Comment by thaJeztah** [comment]
If you want a dynamically linked binary for your local machine, you can run:

```bash
hack/make.sh dynbinary
```

That should put the binaries in the bundles/1.11.1/dynbinary directory

debs are built inside a container, usually it's built with docker-in-docker (see https://github.com/docker/docker/blob/master/Makefile#L85-L86);
```bash
make deb

# or just the `ubuntu-trusty` deb;
DOCKER_BUILD_PKGS=ubuntu-trusty make deb
```

Not running docker-in-docker (deb is still built in a container though); I think this should work (see
https://github.com/docker/docker/blob/master/hack/make/build-deb#L49-L109
and https://github.com/docker/docker/blob/master/contrib/builder/deb/amd64/ubuntu-trusty/Dockerfile)
```bash
DOCKER_BUILD_PKGS=ubuntu-trusty hack/make.sh dynbinary build-deb
```

**Comment by kshcherban** [comment]
@thaJeztah thx for the hints.
Where can i find latest documentation on package building?
I want to get debian source package for in-house build system. Is it possible?

**Comment by thaJeztah** [comment]
If you're planning to package docker for a distribution, there's documentation here; https://github.com/docker/docker/blob/master/project/PACKAGERS.md

@tianon is the right person to ask for assistance with packaging

**Comment by kshcherban** [comment]
Also i've found that single docker binary is not sufficient:
```
time="2016-05-26T14:43:17.516607150+03:00" level=fatal msg="Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: exec: \"docker-containerd\": executable file not found in $PATH"
```

Seems that docker depends on containerd, runc which are distributed in separate repositories.

**Comment by thaJeztah** [comment]
@kshcherban you can see the build process for all binaries in the Dockerfile at the root of the repository; https://github.com/docker/docker/blob/master/Dockerfile. This file is called if you run `make binary` (which runs in a container). To build all, and try them out, my usual steps are;

```
make binary shell
(builds the binary and opens a shell in the container)
cp bundles/*-dev/binary-*/docker* /usr/bin/
dockerd --debug &
```

**Comment by kshcherban** [comment]
@thaJeztah yeah, I saw it, that's not a debian way to create a package imho. For example in https://github.com/tianon/debian-containerd there is prepared debianization, so you can call ```dpkg-buildpackage -F``` to generate source and binary packages.

**Comment by AkihiroSuda** [comment]
Makefiles have changed significantly; closing
