### ISSUE TITLE
Daemon does not respect "no_proxy" variable when creating overlay networks in a Swarm cluster

### ISSUE THREAD

**Issue by chriscowley** [moby/moby#23056]
**Output of `docker version`:**

```
(paste your output here)
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server: 
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 34
 Running: 1
 Paused: 0
 Stopped: 33
Images: 6
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 368.4 MiB
Name: docker-swarm-1
ID: VIBI:E7JO:TAX3:6NWZ:5TJL:XRQU:LWYH:WY3S:YCVM:LW25:ERYG:VQTM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://172.16.1.254:80/
Registry: https://index.docker.io/v1/
Cluster store: consul://172.16.6.41:8500
Cluster advertise: 172.16.6.41:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMs with a VMware environment. Access to internet is via a Squid proxy. 

There are 4 VMs:
- swarm1 
- swarm2
- docker1
- docker2

The 3 Consul servers are on swarm1/2 and docker1.

**Steps to reproduce the issue:**
1. Deploy a Swarm cluster with a Consul backend (as described in official docs).
2. Try to add an overlay network

**Describe the results you received:**

Instead of creating network, it returns the err message:

```
failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
```

No network is created.

However, a search within Consul implies that the key/value pairs have been added (`curl -v http://localhost:8500/v1/kv/docker/network/v1.0/endpoint/?recurse`), but the daemon appears to not find them. Thus it seems to me that the _no_proxy_ variable is respected when WRITING to consul, but not when reading.

**Describe the results you expected:**
Overlay network created, UUID for network returned by CLI

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems to be consistent across at least Debian 8 and CentOS 7.

**Comment by cpuguy83** [comment]
ping @mrjana
