### ISSUE TITLE
Document /run/docker/libcontainerd/docker-containerd.pid

### ISSUE THREAD

**Issue by timstclair** [moby/moby#23069]
We'd like to use the `/run/docker/libcontainerd/docker-containerd.pid` file to lookup the containerd pid, but I couldn't find any documentation around this file. How stable is this location expected to be? Is there a prefered way to lookup the docker-containerd pid?  (Apologies if this is not the right place for this question).

xref: https://github.com/kubernetes/kubernetes/pull/26391

**Comment by thaJeztah** [comment]
Not sure, but note that it's also possible to start containerd separately, and specify the path to its socket via the `--containerd` daemon option; https://docs.docker.com/engine/reference/commandline/daemon/. If that flag is provided, the docker daemon will not control/start containerd.

Haven't looked into your exact use case, but perhaps it's useful information

**Comment by SergeyKanzhelev** [comment]
Hello 4 years later =) Removing the reliance on this file: https://github.com/kubernetes/kubernetes/pull/97888/ So the question is not actual any longer

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
