### ISSUE TITLE
`-h` inconsistency with dockerd/docker daemon

### ISSUE THREAD

**Issue by albers** [moby/moby#23103]
`dockerd` re-introduces `-h` as an alias for `--help` _in its help message_:

``` bash
root@85796c413084:~# dockerd --help | grep -e --help
Usage: dockerd [ --help | -v | --version ]
  -h, --help                               Print usage
```

Not surprisingly, this is also the case when `dockerd` is called as `docker daemon`:

``` bash
root@85796c413084:~# docker daemon --help | grep -e --help
Usage: dockerd [ --help | -v | --version ]
  -h, --help                               Print usage
```

And that's the point: all other `docker` subcommands got rid of this flag in the help messages, so this introduces an inconsistency into the `docker` command.
Examples:

``` bash
root@85796c413084:~# docker run --help | grep -e --help
  --help                          Print usage
root@85796c413084:~# docker images --help | grep -e --help
  --help             Print usage
root@85796c413084:~# docker ps --help | grep -e --help
  --help             Print usage
```

The simplest solution would be to remove `-h` from the help message.
A more sophisticated solution could check the name of the command being called and include `-h` only if the  command were `dockerd`, but I dont't think it's worth the effort.

**Comment by thaJeztah** [comment]
Yes, I was working on a PR to remove it https://github.com/docker/docker/pull/22980, but the mflags package was a real PITA, so have to do some additional changes to make it work :blush:

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.

**Comment by albers** [comment]
Thanks @bsousaa. The issue is indeed resolved. `dockerd --help` no longer mentions `-h`:
```bash
$ dockerd --help | grep -e --help
      --help                                    Print usage
```
