### ISSUE TITLE
non-downloaded containers passed 

### ISSUE THREAD

**Issue by PedramMarandi** [moby/moby#23115]
Hello guys,

I tried to pull Laradock container but when it was php-7 turn I closed terminal and process 4cea9bf5d067 marked as downloaded 
`Step 1 : FROM php:7.0-fpm 7.0-fpm: Pulling from library/php 51f5c6a04d83: Already exists a3ed95caeb02: Pulling fs layer a28c68f3894c: Already exists 1818204ff701: Already exists 4cea9bf5d067: Downloading [======> ] 5.359 MB/40.85 MB 733550adfc5c: Download complete 99b1c7d2a3b6: Download complete`

How can I complete that process ? because php: 7.0-fpm not listed in images list and I'm not able to delete it

**Comment by thaJeztah** [comment]
Can you try pulling it again? `docker pull php:7.0-fpm`?

**Comment by lenxeon** [comment]
me too

![image](https://cloud.githubusercontent.com/assets/251825/15743848/f72b62d8-28fa-11e6-9d4b-fc1a3d68813f.png)

**Comment by lenxeon** [comment]
@HackToday @thaJeztah  progress stop at  4.651 MB/6.459 MB
use ctrl+c to break  it and pull agin, it will stop at here everytime

**Comment by PedramMarandi** [comment]
@lenxeon I think the problem is exactly with ctrl+c, as  I told that in first of topic when I force-closed terminal this happened

**Comment by lenxeon** [comment]
@PedramMarandi maybe yes, but if not use ctrl+c to break it, it will stop at here forever，so i have no choice but to uninstall docker and reinstall it.  bad terrible experience

**Comment by PedramMarandi** [comment]
@lenxeon It seems the only way was that you said, thanks

**Comment by aaronlehmann** [comment]
@PedramMarandi @lenxeon: What version of Docker are you running? I haven't been able to reproduce this problem with 1.11.1.

Versions of Docker since 1.10 should cleanly cancel pulls on `^C`, so I wouldn't expect to see this behavior where the pull continues from the same place it left off. I'm wondering if you're running an older version.

Otherwise, it would be helpful to post a daemon debug log (run Docker the Docker daemon with `-D`) from the time when this happens.

**Comment by lenxeon** [comment]
@aaronlehmann 
```
Run 'docker COMMAND --help' for more information on a command.
 Mac@MacdeMacBook-Pro  /Volumes/data/workspace/resource-view/public/javascripts   master ●  docker -v
Docker version 1.11.1, build 5604cbe
 Mac@MacdeMacBook-Pro  /Volumes/data/workspace/resource-view/public/javascripts   master ● 
```

**Comment by lenxeon** [comment]
maybe cause network not ctrl+c, i use ctrl+c to break it because it stop at here for a long time.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
