### ISSUE TITLE
Cannot run Java 8 in Docker 1.11 on a GRSEC Debian kernel, extended attributes not propagated?

### ISSUE THREAD

**Issue by eembsen** [moby/moby#23125]
**Output of `docker version`:**

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 335
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-254:0-1835061-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 8.009 GB
 Data Space Total: 42.09 GB
 Data Space Available: 34.08 GB
 Metadata Space Used: 12.18 MB
 Metadata Space Total: 859.8 MB
 Metadata Space Available: 847.7 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.14.57-xnt
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 23.57 GiB
Name: xxxx.yyyyy.zz
ID: DQEU:VCZT:CHO3:PXWN:BY5V:V6VN:TEN3:RQWT:HWLZ:MXP7:QF6L:AXEW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Not available

**Steps to reproduce the issue:**

Docker image based on this Dockerfile:

FROM debian:jessie

ENV JAVA_VERSION 8u72
ENV BUILD_VERSION b15

RUN apt-get update -y
RUN apt-get --yes install wget
RUN apt-get --yes install unzip
RUN apt-get --yes install attr

RUN cat /dev/null > $HOME/wgetrc
RUN echo "noclobber = off" >> $HOME/wgetrc
RUN echo "dir_prefix = ." >> $HOME/wgetrc
RUN echo "dirstruct = off" >> $HOME/wgetrc
RUN echo "verbose = on" >> $HOME/wgetrc
RUN echo "progress = dot:mega" >> $HOME/wgetrc
RUN echo "tries = 5" >> $HOME/wgetrc

RUN WGETRC=wgetrc && wget --quiet --continue --no-check-certificate -O /tmp/oracle-jdk-linux-x64.tar.gz --header "Cookie: oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/jdk-$JAVA_VERSION-linux-x64.tar.gz
RUN WGETRC=wgetrc && wget --quiet --continue --no-check-certificate -O /tmp/jce_policy-8.zip --header "Cookie: oraclelicense=a" http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip

RUN mkdir /opt/jdk
RUN cd /opt/jdk && tar zxvf /tmp/oracle-jdk-linux-x64.tar.gz

RUN cd /opt/jdk/jdk*/jre/lib/security && unzip -j -o /tmp/jce_policy-8.zip

RUN update-alternatives --install /usr/bin/java java /opt/jdk/jdk_/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk_/bin/javac 100

RUN setfattr -n user.pax.flags -v m /opt/jdk/jdk*/bin/java

RUN rm -f /tmp/oracle-jdk-linux-x64.tar.gz

WORKDIR /data

**Describe the results you received:**

`root@xxx:/root/docker/images/oracle-java# docker run -it oracle-java:8u72-b15 /bin/bash`
`root@1304779d0620:/data# getfattr -n user.pax.flags /opt/jdk/jdk1.8.0_72/bin/java`
`/opt/jdk/jdk1.8.0_72/bin/java: user.pax.flags: No such attribute`
`root@1304779d0620:/data# setfattr -n user.pax.flags -v m /opt/jdk/jdk*/bin/java`
`root@1304779d0620:/data# getfattr -n user.pax.flags /opt/jdk/jdk1.8.0_72/bin/java`
`getfattr: Removing leading '/' from absolute path names`
`# file: opt/jdk/jdk1.8.0_72/bin/java`
`user.pax.flags="m"`

As a result, starting Java shows:

`Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000076f26d000000, 2555904, 1) failed; error='Operation not permitted' (errno=1)`

`There is insufficient memory for the Java Runtime Environment to continue.`
`Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory.`
`An error report file with more information is saved as:`
`/data/hs_err_pid7.log`

This means that I will not be able to run Sonar, Nexus, Jenkins, etc...

**Describe the results you expected:**

I would expect the first getfattr to output the same as it does when it is issued the second time.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
It looks like support for user extended attributes in Docker was never merged, see #6190 and #6189 (the system ones should work fine). The main problem seems to have been around inconsistent behaviour as some filesystems need special mount options to support these (and at the time eg aufs did not support them at all, although I think that may have been resolved).

Ideally to support grsec better we would like to make these options flags on `docker run` eg `docker run --security-opt grsec:pax.flags=m ...` or similar, but you cannot do this at present, it needs per file labels.

cc @ncopa

**Comment by eembsen** [comment]
Hi Justin,

Thanks for the quick response. Any idea when this could be available? Perhaps in docker 1.12?

Cheers,
Erwin

**Comment by ncopa** [comment]
This is not easily solvable as it would require kernel change in PaX.

**Comment by eembsen** [comment]
Could I use a different storage driver that correctly propagates the extended attributes to upper layers? In the output I see that docker is running with the devicemapper storage driver. Defaulting to a stock Debian kernel is not an option for me.

**Comment by justincormack** [comment]
The only workaround I think will work is to add the attributes at run time in the container not at build time, which should work, at least with `aufs` the attributes persist then. So you can add a wrapper script at build time that sets the attribute and `exec`s Java and put that in the path instead of just Java.

**Comment by eembsen** [comment]
I was trying to avoid this workaround because some of our apps are started by means of a shell script that has the java command in it. These shell scripts are not only used in Dockerfiles but also used locally by developers.

**Comment by justincormack** [comment]
If you move java to a different location and replace with a shell script which calls it, then you should avoid any visible difference. Yes node will be the same as it also uses a JIT compiler.

Sorry we don;t have a better solution at present, as far as we know.

**Comment by eembsen** [comment]
No problem. Thanks for being helpful.

**Comment by powerman** [comment]
Same issue with /usr/local/bin/node in dockersamples/visualizer:stable used in Get Started guide.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
