### ISSUE TITLE
Inheritance between Docker networks

### ISSUE THREAD

**Issue by mitar** [moby/moby#23139]
I have a setup where I have a common HTTP reverse proxy container for multiple other container. I would like that now that I can put other containers in their own networks, that one common HTTP reverse proxy container would be automatically available in each of that networks. Currently it seems that this is not possible. That there is no way to say that one Docker network should inherit for example everything from another (in which reverse proxy container is).

**Comment by gw0** [comment]
As far as I see, a hook would be needed to dynamically connect/attach the container to all networks:

```
$ docker network connect containerX_net proxy_container
```

**Comment by thaJeztah** [comment]
Yes, I'm not sure we should do this automatically (as a default); you can connect the proxy-container to any network, which could be automated if you have a tool that listens for `network create` events https://docs.docker.com/engine/reference/commandline/events/

Given that there's many users that *don't* need this particular use case (or, e.g. want different proxy servers to handle only a subset of all networks), I think it's best to keep this out of the core functionality

**Comment by mitar** [comment]
Hm, I would not do this automatically, but that an user can configure such relation between networks. So that one network is a subset of another. Having hooks manually move containers between networks to simulate such inheritance seems to me a bit ... clunky. :-)

Is there some general daemon to provide easy scripting for such events? I am familiar with dockergen. Is there something similar for events themselves?

**Comment by sam-thibault** [comment]
This is an old issue.  There are no plans to pursue this functionality.
