### ISSUE TITLE
Unable to install Docker on CentOS7.1

### ISSUE THREAD

**Issue by walquis** [moby/moby#23134]
Giving Docker a first try, for managing glibc incompatibilities in a build.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine, running CentOS 7.1.1503

**Steps to reproduce the issue:**

```
$ sudo yum update
$ curl -fsSL https://get.docker.com | sh
```

**Describe the results you received:**

```
[admin@centos71bld ~]$ curl -fsSL https://get.docker.com | sh
+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libdevmapper.so.1.02(DM_1_02_97)(64bit)
Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libsystemd.so.0()(64bit)
Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker-main-repo)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[admin@centos71bld ~]$

[admin@centos71bld ~]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.1.1503 (Core)
Release:        7.1.1503
Codename:       Core
[admin@centos71bld ~]$
```

**Describe the results you expected:**

Expected successful install.

**Comment by thaJeztah** [comment]
This looks similar to https://github.com/docker/docker/issues/20484, can you check that discussion for possible clues? But I wonder why `yum update` didn't upgrade you to the current (7.2) version of CentOS

**Comment by walquis** [comment]
Thanks for getting back to me.  Yeah, I had checked that thread, but nothing I could use.  Here is the output of 'yum update':
````
[admin@centos71bld ~]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
[admin@centos71bld ~]$ sudo yum update
Loaded plugins: fastestmirror, langpacks
cent-7u1_64                                          | 3.4 kB  00:00:00
centos-7u1                                           | 3.6 kB  00:00:00
docker-main-repo                                     | 2.9 kB  00:00:00
dsu_repository_dependent                             | 2.3 kB  00:00:00
dsu_repository_independent                           | 2.3 kB  00:00:00
Loading mirror speeds from cached hostfile
No packages marked for update
[admin@centos71bld ~]$
````
(I'm glad it didn't upgrade the OS; that would have been an undesirable outcome!).

The [compatibility matrix](https://success.docker.com/Get_Help/Compatibility_Matrix_and_Maintenance_Lifecycle) lists Docker 11.1 as compatible with CentOS7.1, if I'm reading it right; so based on that matrix, I would have expected it to work.

No need to spend time on it if it's not an issue for others; for my purposes, I'll just back off the CentOS to 6.5 (which was my original purpose for looking at Docker anyway).

Cheers,
-chris

**Comment by thaJeztah** [comment]
Hm, the compatibility matrix is for the CS version of Docker Engine (commercially supported), although it should be using roughly the same code base. We actually had some discussion about mentioning 7.1 / 7.2 separately, because (as we've been informed) for CentOS and RHEL, basically 7.2 does not exist; it's simply CentOS/RHEL 7, and an "up to date system" is (at this moment), 7.2.

However, I'm surprised why it works for *some* but not for others; it would be great if we could resolve this, or at least know what's causing it, because this is not the best user experience :blush:

**Comment by JevonQ** [comment]
@walquis Did you resolve the prolem you reported?

**Comment by walquis** [comment]
Sorry @JevonQ, no I haven't touched it since last June.

**Comment by AkihiroSuda** [comment]
The package scripts were removed from this repo and moved to https://github.com/docker/docker-ce-packaging
