### ISSUE TITLE
Slow performance when installing RPMs to create new Docker images

### ISSUE THREAD

**Issue by ipeoshir** [moby/moby#23137]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2+20141003
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.7-35-default
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 49.24 GiB
Name: opensuse
ID: SOBQ:JD7L:AJMY:QBLH:QHUL:IFWP:EQZV:JQYY:5N7H:5533:SGTM:6RRY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
openSUSE 13.2, 50GB RAM, ext2 filesystem with LVM.
/var/lib/docker mounted on btrfs disk partition.

**Steps to reproduce the issue:**
1. Download openSUSE's iso and add it to /disks/openSUSE-13.2-DVD-x86_64.iso
2. Run the commands below:

```
mountpoint -q /workspace/iso && umount /workspace/iso
rm -fr /workspace/root
rm -fr /workspace/zypper
rm -fr /workspace/iso
mkdir -p /workspace/iso
mount /disks/openSUSE-13.2-DVD-x86_64.iso /workspace/iso

rpm --initdb --dbpath /workspace/root/rpm
zypper --reposd-dir /workspace/zypper/reposd --cache-dir /workspace/zypper/cache --solv-cache-dir /workspace/zypper/solv --pkg-cache-dir /workspace/zypper/pkg --non-interactive addrepo --name suse-13.2-oss --no-gpgcheck /workspace/iso suse-13.2-oss
```
1. On the host, run:

```
time zypper --reposd-dir /workspace/zypper/reposd --cache-dir /workspace/zypper/cache --solv-cache-dir /workspace/zypper/solv --pkg-cache-dir /workspace/zypper/pkg --non-interactive --root /workspace/root install rpm subversion
```
1. Re-run step 2 and on container, run:

```
docker run --rm --net=none --log-driver=none -v "/workspace:/workspace" -v "/disks:/disks" opensuse bash -c "time zypper --reposd-dir /workspace/zypper/reposd --cache-dir /workspace/zypper/cache --solv-cache-dir /workspace/zypper/solv --pkg-cache-dir /workspace/zypper/pkg --non-interactive --root /workspace/root install rpm subversion"
```

**Describe the results you received:**
Results from steps 3:

```
real    0m11.248s
user    0m7.316s
sys     0m1.932s
```

Results from steps 4:

```
real    0m31.089s
user    0m14.876s
sys     0m12.524s
```

**Describe the results you expected:**
The output is sluggish when installing RPMs on containers. This may be the reason why creating new images on Dockerfiles takes such a long time to complete.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ipeoshir** [comment]
Simulation on Ubuntu, as I am not sure how we can simulate package installation there...

First create some random files:
```
rm -fr /workspace/image
mkdir -p /workspace/image
for i in {1..10000}; do echo . > /workspace/image/${i}; done;`
```

Then we can simulate RPM installation by compressing/decompressing these files:
```
time for i in {1..5}; do tar -C /workspace -cvf /workspace/image.tar.gz image -J; tar -C /workspace -xvf /workspace/image.tar.gz; done;
```
On host it takes:
```
real    0m42.219s
user    0m13.868s
sys     0m8.624s
```
Then we simulate the same thing running on docker:
```
docker run --rm --net=none --log-driver=none --read-only -v "/bin/tar:/bin/tar" -v "/workspace:/workspace" opensuse bash -c "time for i in {1..5}; do tar -C /workspace -cvf /workspace/image.tar.gz image -J; tar -C /workspace -xvf /workspace/image.tar.gz; done;"
```
On docker it takes:
```
real    0m53.630s
user    0m13.736s
sys     0m7.280s
```

In my real use case I have the system package installation taking 7414 seconds on containers vs 846 seconds on a host, so the performance is quite bad.

**Comment by thaJeztah** [comment]
Sound like it may be related to your other issues? (https://github.com/docker/docker/issues/21485)

ping @cyphar ptal

**Comment by cyphar** [comment]
This might be related to the `blkio` cgroup stuff I mentioned in #21485. I'll take a look at this later today.

/cc @flavio

**Comment by ipeoshir** [comment]
Sounds similar, but I did change all my filesystems to ext2, so this is not related to how the filesystem is mounted. So I found a way to run it on any OS and confirmed that this also seems to impact openSUSE13.2/SLES12 only:

Pre-Setup:
- Download Ubuntu's ISO (http://mirror.pnl.gov/releases/14.04.4/ubuntu-14.04.4-server-amd64.iso) and copy it to "/workspace/ubuntu-14.04.4-server-amd64.iso"
- Run "docker pull opensuse"

Setup:
```
mountpoint -q /workspace/iso && umount /workspace/iso
rm -fr /workspace/root
rm -fr /workspace/iso
mkdir -p /workspace/root
mkdir -p /workspace/iso
mount /workspace/ubuntu-14.04.4-server-amd64.iso /workspace/iso
unsquashfs -f -d /workspace/root /workspace/iso/install/filesystem.squashfs
mkdir -p /workspace/root/workspace/iso
mount --bind /workspace/iso /workspace/root/workspace/iso
echo "deb file:/workspace/iso/ubuntu/ trusty main restricted" > /workspace/root/etc/apt/sources.list
chroot /workspace/root apt-get update
```

Host (**always** run the "Setup" steps before running below):
```
time chroot /workspace/root apt-get -y install qemu-kvm samba tomcat7
umount /workspace/root/workspace/iso
umount /workspace/iso
```
Host's results:
```
# Ubuntu 14.04
real    0m31.152s
user    0m15.744s
sys     0m3.528s

# openSUSE 13.2
real    0m34.119s
user    0m15.572s
sys     0m3.884s
```

Docker (**always** run the "Setup" steps before running below):
```
docker run --rm --net=none --log-driver=none --read-only -v "/workspace:/workspace" opensuse bash -c "time chroot /workspace/root apt-get -y install qemu-kvm samba tomcat7"
umount /workspace/root/workspace/iso
umount /workspace/iso
```
Docker's results:
```
# Ubuntu 14.04
real    0m34.728s
user    0m16.244s
sys     0m5.864s

# openSUSE 13.2
real    1m3.131s
user    0m16.140s
sys     0m6.048s
```

Or you can just follow the steps that I posted initially on this issue with zypper using an openSUSE's iso. It can be done only on openSUSE/SLES though because it requires zypper, but you can see how it takes longer to install packages on containers based on these results...

**Comment by tripzero** [comment]
I don't think RPM performance issues are entirely blkio cgroup related.  Here's a test using yocto build times as the load:

mkdir /workspace && cd /workspace
git clone git://git.yoctoproject.org/poky.git

source oe-init-build-env
bitbake core-image-sato
bitbake core-image-sato -c clean
time core-image-sato -c do_rootfs

real    2m29.580s
user    0m3.084s
sys     0m0.460s

rm -rf /workspace
mkdir /workspace && cd /workspace
git clone git://git.yoctoproject.org/poky.git

docker run --rm -it -v /workspace/poky:/workspace:Z" crops/poky --workdir=/workspace
source oe-init-build-env
bitbake core-image-sato
bitbake core-image-sato -c clean
time core-image-sato -c do_rootfs

real    8m0.646s
user    0m3.176s
sys     0m0.624s

Repeat test after "echo deadline >/sys/block/sdb/queue/scheduler" and the results are the same.  Now, I cannot repeat this with my ubuntu 17.10 system running a 4.13 kernel.  This machine is running ubuntu 16.04 and a linux 4.10 kernel.  Could something have changed in the kernel that fixed this?  We can look at the dnf.rpm.log (in tmp/work/qemux86-poky-linux/core-image-sato/1.0-r0/temp/dnf.rpm.log) and see that it takes about 1 second for each package in docker vs dozens per second on the host.

If I change PACKAGE_CLASSES in /workspace/poky/build/conf/local.conf to "package_ipk" or "package_deb", I do not see a major impact.  This suggests that there is something that rpm is doing that is triggering a performance issue.  What is it doing?  While building in the container, you can find the pid of dnf by running:

ps -aux | grep python3 | grep dnf

sudo strace -f -p [the pid from above]

You can see that it sure spends a lot of time doing:

fcntl(18307, F_GETFD)       = -1 EBADF (Bad file descriptor)

It looks like it's starting at fcntl(4) and going up to a 1048575.  Wow.  On the host, I still get EBADF, but it only goes up to 1023.  Ding!  within the container, ulimit -n says "1048576".  That's exactly how many times it tries fcntl F_GETFD.  Setting ulimit -n to 1024 in the container fixes dnf/rpm's issue.

Seems like a bug somewhere in dnf or rpm that it tries to run fctl GETFD on every possible file descriptor.

**Comment by thaJeztah** [comment]
Interesting. Ping @kolyshkin

**Comment by cyphar** [comment]
@tripzero Here's the relevant section of code from RPM. It's part of the POSIX lua library that's inside RPM, and was added by rpm-software-management/rpm@7a7c31f551ff167f8718aea6d5048f6288d60205.

```c
static int Pexec(lua_State *L) /** exec(path,[args]) */
{
	/* ... */
	open_max = sysconf(_SC_OPEN_MAX);
	if (open_max == -1) {
	    open_max = 1024;
	}
	for (fdno = 3; fdno < open_max; fdno++) {
	    flag = fcntl(fdno, F_GETFD);
	    if (flag == -1 || (flag & FD_CLOEXEC))
		continue;
	    fcntl(fdno, F_SETFD, FD_CLOEXEC);
	}
	/* ... */
}
```

So the reason for doing `F_GETFD` is because they are setting all of the FDs to `CLOEXEC` before doing the requested `exec(2)`. There's a [redhat bugzilla entry](https://bugzilla.redhat.com/show_bug.cgi?id=919801) in the commit message, which says that this was an SELinux issue where Fedora (or RHEL) have an SELinux setup where you cannot execute a process if it will inherit FDs it shouldn't have access to?

I guess if this is an SELinux issue it should be handled by only applying this fix when SELinux is used (though there are arguably security reasons why you might want to `CLOEXEC` every file descriptor).

**Comment by kanavin** [comment]
I have reported this upstream. Do make noise there:
https://bugzilla.redhat.com/show_bug.cgi?id=1537564

**Comment by thaJeztah** [comment]
Nice, thanks!

**Comment by thaJeztah** [comment]
I see the PR was carried in https://github.com/rpm-software-management/rpm/commit/5e6f05cd8dad6c1ee6bd1e6e43f176976c9c3416 (for those searching)

Yes, let's close, as it's not a bug in this codebase, and the issue is resolved upstream
