### ISSUE TITLE
Docker port mapping (-p) gives an iptables error on RHEL 7.2

### ISSUE THREAD

**Issue by kapcip** [moby/moby#23154]
**Whenever I start any container by mapping ports, it gives an iptables error.** 

docker: Error response from daemon: driver failed programming external connectivity on endpoint naughty_babbage (ca698c082b2ffe55229b7183a1588100a2011f82df0e718f16274e02a6cf26fb): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).

**Whereas host mode (--net=host) works fine**

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/issues/16816. This can be an interaction with firewalld running on the host, and if it's started *after* docker is started. You can try restarting docker (it should re-create the iptables rules).

Also might be worth checking the docker daemon logs to see if there's some other reason that the iptables rules could not be created.

**Comment by jeffreycwitt** [comment]
I had the same problem. Restarting docker service worked for me.

**Comment by toddlers** [comment]
followed this [stackoverflow](http://stackoverflow.com/questions/31667160/running-docker-container-iptables-no-chain-target-match-by-that-name) . Worked !

**Comment by thaJeztah** [comment]
Let me close this issue, because I think this is a duplicate of https://github.com/moby/moby/issues/16816, or something else modifying the IPTables rules

**Comment by siyavashhamdi** [comment]
Use command:
`systemctrl restart docker`
