### ISSUE TITLE
DNS Resolve Issues when creating overlay network in same subnet as eth0

### ISSUE THREAD

**Issue by plieningerweb** [moby/moby#23207]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 34
 Running: 3
 Paused: 0
 Stopped: 31
Images: 9
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 176
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.61 GiB
Name: WS23
ID: 3GNK:7E76:MOGV:QU5Y:XE53:NLP6:ZHIV:S5FF:J2KR:VZGN:RGZV:QGSR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Cluster store: consul://ws23:8500
Cluster advertise: 10.0.102.23:2375
```

**Steps to reproduce the issue:**
1. setup docker swarm
2. create network on docker swarm using `docker -H :4000 network create test`
3. run container in this network `docker -H :4000 run -it --net=test busybox bash`
4. in container run `ping google.com` -> will fail!

**Describe the results you received:**
Ping did not resolve to company internal DNS (10.0.0.1)

**Describe the results you expected:**
Should resolve name using the company iternal DNS

**Solution**
Do not create a network with the same subnet as eth0 of host (10.0.0.0/24).

Workaround: Specify subnet in create network, which is different than eth0
e.g. `docker -H :4000 network create --subnet=172.31.0.0/24 --gateway=172.31.0.1 hadoop`

Also checkout this gist: https://gist.github.com/plieningerweb/dc83d5133e8bf113f2010e1bc79a9d16 

**Expected Fix**
docker network create should not create a network in the same subnet as the hosts' eth0, if this leads to routing issues and (in this case) failure of DNS lookups.

**Comment by jmzwcn** [comment]
Maybe similar to [this issue](https://github.com/docker/docker/issues/19499)

Refer to [code](https://github.com/docker/libnetwork/blob/master/network.go#L1168), it directly returns a un-check's pool due to overlay network's datastore scope is global?

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
