### ISSUE TITLE
Windows Server 2016 TP5 installation issue

### ISSUE THREAD

**Issue by tiagomacarios** [moby/moby#23252]
**Output of `docker version`:**

Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 2.009 GiB
Name: WIN-CCT7A9MKF3O
ID: SDPB:LHWB:35A6:3SQF:TGX5:TATW:Q4ME:CT73:X7OU:52DW:2CT6:PGZ2
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2016 TP5

**Steps to reproduce the issue:**

Same as described here: https://blogs.msdn.microsoft.com/jcorioland/2016/04/28/getting-started-with-containers-and-docker-on-windows-server-2016-technical-preview-5/
1. wget -uri https://aka.ms/tp5/Install-ContainerHost -OutFile C:\Install-ContainerHost.ps1
2. ./C:\Install-ContainerHost.ps1

**Describe the results you received:**

Querying status of Windows feature: Containers...
Feature Containers is already enabled.
SUCCESS: The scheduled task "ContainerBootstrap" was successfully deleted.
Configuring ICMP firewall rules for containers...
Installing Docker...
Installing Docker daemon...
Creating Docker program data...
This script uses a third party tool: NSSM. For more information, see https://nssm.cc/usage
Downloading NSSM...
Extracting NSSM from archive...
Configuring NSSM for Docker service...
Starting Docker...
Waiting for Docker daemon...
Successfully connected to Docker Daemon.
The following images are present on this machine:
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

Installing ContainerImage provider...
Getting Container OS image (WindowsServerCore -MinimumVersion 10.0.14300.1000 -MaximumVersion 10.0.14300.1010) from OneGet (this may take a few minutes)...
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As
part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well
as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell
Container base image install complete.
Creating a first boot layer...
Error checking context: 'can't stat '\?\C:\Windows\System32\LogFiles\WMI\RtBackup''.
Script complete!

**Second try:**

Above seemed to be related to a permission problem. So I overwrote the permissions of the RtBackup folder and tried again. This time I got this:

...
Failed to write to log, New state of 'nil' is invalid.
Failed to write to log, New state of 'nil' is invalid.
Failed to write to log, New state of 'nil' is invalid.
Failed to write to log, New state of 'nil' is invalid.
Script complete!

**Describe the results you expected:**

Installation to complete successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

**Comment by jhowardmsft** [comment]
@mebersol - known?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
