### ISSUE TITLE
Docker upgrade stops containers

### ISSUE THREAD

**Issue by paulmenzel** [moby/moby#23277]
**Output of `docker version`:**

```
$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ sudo docker info
Containers: 20
 Running: 7
 Paused: 0
 Stopped: 13
Images: 815
Server Version: 1.11.2
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.43 GiB
Name: kulturprojekte01
ID: TPT4:YLLY:D2XM:YXEN:BHKY:YUBB:MOCF:XSNR:5LFF:YEEF:5P5O:POKQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 8.4 (Jessie/stable)

**Steps to reproduce the issue:**
1. Run `apt update` and `apt upgrade`

**Describe the results you received:**

Upgrading from Docker 1.11.0 to 1.11.2 not all containers were running again.

**Describe the results you expected:**

The state after the upgrade should be as before. All running containers before the upgrade should be running after the upgrade.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue also happened upgrading from Docker 1.10.0 to 1.11.0.

**Comment by thaJeztah** [comment]
Only containers with a restart policy are restarted after an upgrade; did those containers have a restart policy set?

Note that we're working on allowing the daemon to be upgraded without stopping the containers; https://github.com/docker/docker/issues/2658

**Comment by paulmenzel** [comment]
Interesting, though confusing. *Restart* for me always means, in case the container dies/stops unexpectedly.

One DB container (MariaDB) has a restart policy of *always* but wasn’t started.

```
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
```

Another container (Memcached) was restarted properly though.

All other containers have a restart policy of 0.

If this should be debugged further, please tell me, where I can find the reason, why the MariaDB container did not start. In the mean time it was started after a system reboot.

**Comment by thaJeztah** [comment]
Ok, if the container has a restart policy set, then it should be restarted, yes. Do the daemon logs or logs for that container show anything that indicates why it refused to start?

Note that, if the container fails to start, the timeout before the next attempt is increased exponentially (100ms, 200, 400, and so on), if it's tried in quick succession, that timeout can quickly become large, keeping the container in "restarting" status (which means, waiting before the next attempt)

**Comment by paulmenzel** [comment]
> Do the daemon logs or logs for that container show anything that indicates why it refused to start?

How do I find that out? `zgrep containername /var/log/syslog*` doesn’t show anything.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
