### ISSUE TITLE
Can not install Docker on Ubuntu 16.04 (Xenial) due to server verification

### ISSUE THREAD

**Issue by jianghaitao** [moby/moby#23315]
I was following the instruction on https://docs.docker.com/engine/installation/linux/ubuntulinux/ for Ubuntu 16.04. After add entry to /etc/apt/sources.list.d/docker.list and run apt-get update, I got

```
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

The installation is behind a firewall and I have the http_proxy and https_proxy set, and I can reach out to the Internet. 

```
# ls -l /etc/ssl/certs/ca-certificates.crt 
-rw-r--r-- 1 root root 274340 Jun  6 17:12 /etc/ssl/certs/ca-certificates.crt
```

Any help is highly appreciated.

**Comment by thaJeztah** [comment]
The certificates were recently replaced with new ones, because they were about to expire, could it be that a proxy server pinned the old certificate, and therefore refuses the new one?

**Comment by jianghaitao** [comment]
Possibly. How do I check and update? Thanks.

**Comment by thaJeztah** [comment]
Good question. I was just thinking out loud, because I know the certificates were recently updated (in case it helped you further), but I don't know how to help you further than that :blush:

**Comment by jianghaitao** [comment]
@thaJeztah thanks. Just for the record, I have run following before hitting the issue
```
# apt-get install -y -q apt-transport-https ca-certificates
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.12~ubuntu16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```

**Comment by thaJeztah** [comment]
Is this a corporate proxy you're behind? It's possible that there's a "man in the middle" proxy that replaces certificates. This answer may give some info http://stackoverflow.com/a/21181447/1811501

**Comment by HackToday** [comment]
I am thinking even we behind firewall or proxy, the install would still be OK.  But not sure if different proxy mechanism could cause different issue, like this one. so glad to know any clue for that

**Comment by richteelbah** [comment]
Thanks, I switched to my mobile hotspot and tried again and was able to get past the error. For me, the issue was apparently a corporate proxy server.

**Comment by Starkmann** [comment]
On my machine 16.04 ubuntu is was able ti fix this issue with:
`sudo apt-get install --reinstall ca-certificates`

**Comment by caffeineaddiction** [comment]
On my machine I was able to fix this issue with:
`sudo apt-get install apt-transport-https`

**Comment by thaJeztah** [comment]
I haven't heard others report this, and it doesn't look like a bug, so closing this issue

**Comment by alijawadfahs** [comment]
as simple as it may sound but also check the time, for me the NTP was not configured and the time wrong and the certificates were not trusted.

**Comment by jrzhao** [comment]
hit the same issue on ubuntu 16 when launching apt-get update:
Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none E: Some index files failed to download. They have been ignored, or old ones used instead.

tried all the workaround above -- not work either. Any other good idea is appreciated.

**Comment by mohantysubhendu** [comment]
@jrzhao did you get the solution ?
I am also unable to fix the issue.

**Comment by samsonahk** [comment]
I am using ubuntu desktop v18.04.1.  I tried to install kubectl.  My VM is behind the corporate proxy.  I followed the following steps

(1) sudo apt install -y apt-transport-https
(2) apt install curl
(3) apt install --reinstall ca-certificates
(4) mkdir /usr/local/share/ca-certificates/cacert.org
(5) wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
(6) update-ca-certificates
(7) Download https://packages.cloud.google.com/apt/doc/apt-key.gpg to VM.  Execute 'apt-key add apt-key.gpg'
(8) touch /etc/apt/sources.list.d/kubernetes.list
(9) echo "deb [trusted=yes] http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
(10) apt update

Hit:1 http://hk.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://hk.archive.ubuntu.com/ubuntu bionic-updates InRelease                            
Hit:3 http://hk.archive.ubuntu.com/ubuntu bionic-backports InRelease                          
Ign:4 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                       
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease        
Ign:6 https://packages.cloud.google.com/apt kubernetes-xenial Release
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial/main i386 Packages
Ign:9 https://packages.cloud.google.com/apt kubernetes-xenial/main all Packages
Ign:10 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:11 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en_HK
Ign:12 https://packages.cloud.google.com/apt kubernetes-xenial/main Translation-en
Ign:13 https://packages.cloud.google.com/apt kubernetes-xenial/main all DEP-11 Metadata
Ign:14 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 DEP-11 Metadata
Ign:15 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 48x48 Icons
Ign:16 https://packages.cloud.google.com/apt kubernetes-xenial/main DEP-11 64x64 Icons
Ign:17 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 c-n-f Metadata
Ign:18 https://packages.cloud.google.com/apt kubernetes-xenial/main all c-n-f Metadata
Err:7 https://packages.cloud.google.com/apt kubernetes-xenial/main Sources
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
Reading package lists... Done
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/source/Sources  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-i386/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-all/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/i18n/Translation-en_HK  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/i18n/Translation-en  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/dep11/Components-all.yml  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/dep11/Components-amd64.yml  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/dep11/icons-48x48.tar  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/dep11/icons-64x64.tar  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/cnf/Commands-amd64  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 172.5.2.110 8080]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by thaJeztah** [comment]
apt.dockerproject.org is the old package repository, which has been deprecated. you'll have to use the package repository at `download.docker.com`. Make sure the old one [is removed from the list of repositories](https://unix.stackexchange.com/questions/219341/how-to-apt-delete-repository), and install docker using the instructions in the documentation; e.g. for Ubuntu: https://docs.docker.com/install/linux/docker-ce/ubuntu/

You can also use the convenience script (after removing the old repository);

```bash
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
```
