### ISSUE TITLE
windowsTP5: unable to create networks

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#23314]
Noticed while working on a PR; https://github.com/docker/docker/pull/23300#issuecomment-224007858, it looks like it's not possible to create a network containing a dash in its name.

@cpuguy83 was able to reproduce locally on a WindowsTP5 machine, so looks like an actual issue.

```
15:27:19 FAIL: docker_cli_ps_test.go:808: DockerSuite.TestPsListContainersFilterNetwork
15:27:19 
15:27:19 docker_cli_ps_test.go:810:
15:27:19     // create a network, and some containers
15:27:19     dockerCmd(c, "network", "create", "network-a")
15:27:19 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
15:27:19     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
15:27:19 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc082400180)} ("exit status 1")
15:27:19 ... "network create network-a" failed with errors: Error response from daemon: plugin not found
15:27:19 , exit status 1
15:27:19 
```

/cc @jhowardmsft @msabansal

**Comment by thaJeztah** [comment]
Hm, so looks to be not related to the name, getting the same name after the network-name was changed;

```
17:28:04 ----------------------------------------------------------------------
17:28:04 FAIL: docker_cli_ps_test.go:808: DockerSuite.TestPsListContainersFilterNetwork
17:28:04 
17:28:04 docker_cli_ps_test.go:810:
17:28:04     // create a network, and some containers
17:28:04     dockerCmd(c, "network", "create", "somenetwork")
17:28:04 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
17:28:04     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
17:28:04 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0823a38a0)} ("exit status 1")
17:28:04 ... "network create somenetwork" failed with errors: Error response from daemon: plugin not found
17:28:04 , exit status 1
```

**Comment by msabansal** [comment]
The plugin not found error means that we are using incorrect driver name. In windows we can't create multiple nat networks and the daemon automatically creates a nat network when it starts.

**Comment by friism** [comment]
@msabansal `plugin not found` seems like not the right error message for that eventuality, or maybe I'm missing something. Eg. is should indicate that the `nat` network driver is used and then say that only one network is support for that driver and it has already been created.

**Comment by thaJeztah** [comment]
Can I create custom networks at all? Otherwise the command should just error "not supported on windows"

**Comment by friism** [comment]
@thaJeztah you can in principle: https://github.com/docker/libnetwork/blob/master/drivers_windows.go

cc @mavenugo

**Comment by msabansal** [comment]
@friism  This is a problem with how the call is being made. I would have to look in the test code bug please take a look at https://github.com/docker/docker/blob/master/daemon/daemon_windows.go on how we create the default nat network for windows. Daemon logs will show which plugin we are trying to find.

**Comment by thaJeztah** [comment]
ping @cpuguy83 @msabansal is this still an issue? We no longer have TP5, but wondering if it's resolved in RS1

**Comment by sixeyed** [comment]
@thaJeztah - seems to still be an issue. I've just run TP5 from the Azure image `2016-Technical-Preview-with-Containers`  and upgraded manually to 1.12.1. Running a basic `docker network create -d overlay winweb` gives the `plugin not found` error, and in the Event Log I see `Unable to locate plugin: overlay, retrying in 8s`.

Originally I had this Windows box as a worker node in a Linux swarm. I got the error when I tried to create a service from a Windows image (constrained to the Windows node). Thought it might be a swarm mode issue, but then I left the swarm and got the error above, trying to create an overlay network manually.

**Comment by msabansal** [comment]
@sixeyed We are working on adding swarm support but its not released in RS1. You can create multiple nat networks with some new changes but that requires a docker PR to be merged and some manual configuration on the system which we will be documenting soon. 

https://github.com/docker/docker/pull/25097

**Comment by thaJeztah** [comment]
Looks like overlay support for Windows is available now for Windows 10 insider
https://blogs.technet.microsoft.com/virtualization/2017/02/09/overlay-network-driver-with-support-for-docker-swarm-mode-now-available-to-windows-insiders-on-windows-10/

**Comment by mustafamagdy** [comment]
I think this is kinda old, but I got it working by specifying the driver to nat
`$ docker network create -d "nat" test-net1`

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
