### ISSUE TITLE
Avoiding private registry hostname in FROM directive of Dockerfile

### ISSUE THREAD

**Issue by salmanbaset** [moby/moby#23320]
Say I have an image FOOBASE in a private registry (hostname:port PRIVREGHOSTNAME:5000)

I want to use this image in a Dockerfile for a new image FOONEW. Currently, it is done as follows:
# Dockerfile

FROM PRIVREGHOSTNAME:5000/FOOBASE
...

That is, the hostname of the private registry is in the Dockerfile.

Now say, I want to change the registries. I have to change the Dockerfile of FOOBASE, rebuild it, and rebuild the image FOONEW that depends on FOOBASE. Obviously, changing the Dockerfile is not desirable. The registry hostname should not be in the Dockerfile

Instead, a better solution is to define a new parameter --registry-url for docker build. E.g.,

docker build -t . --registry-url PRIVREGHOSTNAME:5000

So by default, the image referenced in Dockerfile is searched first in the registry-url and then in Dockerhub.

**Comment by duglin** [comment]
oh, if only you could have written something like:
```
FROM ${registry:-myregistry.com}/foobase
...


docker build --build-arg registry=yourregistry.com
```
:-)

**Comment by runcom** [comment]
This is a long outstanding issue :) I bet there are other issues around about this problem

**Comment by jkubrynski** [comment]
Are you going to answer to this issue? Working with private issues in Docker is really annoying, and confirming that there are many issues regarding it is probably not enough for users...

**Comment by duglin** [comment]
FYI: https://github.com/docker/docker/pull/31352

**Comment by salykin** [comment]
This opportunity is valuable for me. The only way I can do this is to preprocess dockerfile template file with `envsubst` like this:

```bash
$ cat Dockerfile.template
FROM ${REPO_NAME}:${tag}
$ export REPO_NAME=myrepo:5001
$ envsubst '$REPO_NAME' < Dockerfile.template > Dockerfile
$ cat Dockerfile
FROM myrepo:5001:${tag}
```

Am I missed any other solutions?

**Comment by cpuguy83** [comment]
You can use --build-arg to pass a registry name.

```Dockerfile
ARG REGISTRY
FROM $REGISTRY/my/img
...
```

And then `docker build --build-arg REGISTRY=myreg:5000 ...`

Closing since this this can be done via build args.

**Comment by salykin** [comment]
> You can use --build-arg to pass a registry name.

Right! I forgot to pass `--build-arg REGISTRY=...` to build command thinking it will be passed automatically. Thanks!

**Comment by augensalat** [comment]
> You can use --build-arg to pass a registry name.
> 
> ```dockerfile
> ARG REGISTRY
> FROM $REGISTRY/my/img
> ...
> ```
> 
> And then `docker build --build-arg REGISTRY=myreg:5000 ...`

But this does not work if you don't specify any registry!
In that case `docker build .` is effectively resulting in `FROM /my/img` and gives me

> Step 1/10 : ARG REGISTRY
Step 2/10 : FROM $REGISTRY/my/img
invalid reference format

However it seems Docker knows Bourne Shell parameter expansion a bit (I did not find anything usefull in the docs though).
Just tested with version 19.03.8 on MacOS, where this works for both situations:

```dockerfile
ARG REGISTRY
FROM ${REGISTRY:+$REGISTRY/}my/img
...
```
