### ISSUE TITLE
Why does `ENV` Dockerfile command do I/O

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#23321]
I have been noticing lately that `ENV` commands in the Dockerfile run quite slow.  Now I'm running something on a crappy ARM device and there it's ridiculously slow.  So the question I have is why does `ENV` end up doing so much I/O?

**Comment by ibuildthecloud** [comment]
Also note, I'm using overlay primarily.

**Comment by thaJeztah** [comment]
@duglin any ideas?

**Comment by ibuildthecloud** [comment]
I think the basic thing is that each build step does a container commit and overlay does a fsdiff which isn't as fast as something like aufs.  It seems for commands that just change metadata we should be able to skip the container commit.

**Comment by thaJeztah** [comment]
You may be interested in https://github.com/docker/docker/pull/22126 (sorry, won't run on a 3.10 kernel probably :wink:)

**Comment by cpuguy83** [comment]
I'm really suprised that `ENV` creates a container at all anymore.
The image format supports this now.

**Comment by vdemeester** [comment]
@couguy83 I don't think we changed anything to the builder that would not make create a container for each Dockerfile instruction, so I'm not surprised.
