### ISSUE TITLE
It is not clear how to get only daemon logs under systemd

### ISSUE THREAD

**Issue by bobrik** [moby/moby#23339]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   83db9ef
 Built:        Fri Mar 11 15:07:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   83db9ef
 Built:        Fri Mar 11 15:07:19 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.3-cloudflare
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6 GiB
Name: hehe
ID: 6BGO:IA27:4JCV:GSXF:EW3K:4DCP:ZL75:ZA6T:H66L:T5IO:4VS7:XSF7
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian Jessie with systemd. I have the following override unit:

`/etc/systemd/system/docker.service.d/override.conf`:

```
# MANAGED BY SALT -- DO NOT MODIFY

# https://docs.docker.com/engine/articles/systemd/

[Service]
# https://github.com/docker/docker/pull/4519
Environment=DOCKER_RAMDISK=1
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver overlay --exec-opt native.cgroupdriver=systemd --log-driver journald
```

**Steps to reproduce the issue:**
1. Run `journalctl -fu docker`.

**Describe the results you received:**

Observed bazillion log lines from containers 😕.

I've tried googling how to get only docker daemon logs, but without any luck.

**Describe the results you expected:**

I'd like to see docker daemon logs in obvious standard manner. Alternatively, I want to be able to google/look up in unit file comment a command to do so.

**Additional information you deem important (e.g. issue happens only occasionally):**

Dumping journald logs in json given me the idea that docker daemon logs with `SYSLOG_IDENTIFIER=docker`, while containers ran by docker do not use this.

```
journactl -fu SYSLOG_IDENTIFIER=docker
```

Should we have a comment in the unit file and in [systemd docs](https://docs.docker.com/engine/articles/systemd/)?

**Comment by runcom** [comment]
Not sure about SYSLOG_IDENTIFIER (not working on my laptop)
but you should be able to get only daemon logs with (just for 1.10.3):
```
journalctl -fu docker _TRANSPORT=stdout + OBJECT_EXE=docker
```
we're tracking this into https://bugzilla.redhat.com/show_bug.cgi?id=1328214

**Comment by bobrik** [comment]
I don't have `OBJECT_EXE` on systemd 215, but I do have `_TRANSPORT=stdout`.

The issue you linked is `CLOSED CANTFIX`.

**Comment by cpuguy83** [comment]
Wouldn't `-fu docker.service` work?

**Comment by bobrik** [comment]
@cpuguy83 nope, same as `-fu docker`.

**Comment by jfrazelle** [comment]
this is with the journald driver right? maybe we need to pass something to journald in the driver to differenciate it?

**Comment by cirocosta** [comment]
Are the new versions tackling this somehow?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
