### ISSUE TITLE
Ignore docker login -e option flag

### ISSUE THREAD

**Issue by sentientmonkey** [moby/moby#23390]
The following PR removed the email address from login: 
https://github.com/docker/docker/pull/20565 

This left the -e flag as a warning to customers, and is slated for deprecation in docker 1.13. 

The AWS CLI relies on the docker login command for authentication with the EC2 Container Registry. 
https://github.com/aws/aws-cli/blob/develop/awscli/customizations/ecr.py#L55

If this flag is removed in the AWS CLI, customers using older version of docker (1.10 or older) will no longer be able to login without upgrading docker or downgrading the AWS CLI.

I'd like to propose that newer versions of docker silently ignore this flag, or accept "-e none" as a valid option, and not deprecate the flag.

**Comment by cpuguy83** [comment]
IMO, This is why we have deprecation notices.
1.13 is still at least 3 months away, this seems like plenty of time to update awscli.

**Comment by sentientmonkey** [comment]
The AWS CLI provides an easy mechanism for customers to authenticate with EC2 Container Registry using `docker login`. Because the CLI can be used inside non-interactive scripts and because `docker login` would fall-back to interactive behavior when `-e` was omitted, a junk value of `-e none` is part of the generated `docker login` command. Changing the behavior in the AWS CLI to omit the `-e` option will make it harder for people to use an up-to-date version of the AWS CLI with an old version of Docker, while conversely keeping `-e` will make it fail for people using new versions of Docker. Our data shows that people tend to update Docker slowly (at least in production) while they do update the AWS CLI primarily with the goal of accessing new features in AWS services.

**Comment by cpuguy83** [comment]
@sentientmonkey But the version can be queried, or the API can be used instead.

**Comment by sentientmonkey** [comment]
Thanks for the suggestion.  When we were thinking through this interaction initially, we were concerned with the risks for credential exposure, escalation of privilege, and functionality that would be introduced by invoking another executable on your PATH or making a call to an already-privileged process like the Docker daemon.  As an additional component in the design, we were concerned about portability between different end-user systems (making sure the same process works for customers on Linux, Windows, or Mac).  There are a few cases that deserve some examples:

* Invoking a process on PATH risks that a malicious executable placed earlier on the PATH may get invoked instead

* Making a call to the Docker daemon through a socket risks privilege escalation for a user who is in the 'docker' group (or whatever group is set on the Docker daemon)

* Making a call to the Docker daemon through the socket could fail if the current user is not privileged (and not part of the 'docker' group)

* The Docker daemon might not be available at a socket, but instead at a TCP endpoint potentially secured with a certificate

There is more documentation around the `get-login` command here:
http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html

**Comment by sentientmonkey** [comment]
Any update that we can share with our customers? I've linked the corresponding aws-cli issue.

**Comment by avandendorpe** [comment]
As 1.13 nears this seems more and more relevant. Is there a particular adverse effect from silently ignoring the -e option?

**Comment by sentientmonkey** [comment]
Just checking in for another update here. Based on the latest documentation, this is now slated for the docker 1.14 release: 

https://docs.docker.com/engine/deprecated/#/e-and---email-flags-on-docker-login

Silently ignoring this field (vs explicltly erroring) is the safest way to provide both backwards and forward compatibility for customers.

**Comment by trinitronx** [comment]
IMHO: breaking the command line API in a minor version upgrade is bad form according to best practices adopted by the software development community such as [SemVer](http://semver.org/)

**Comment by thaJeztah** [comment]
Just a heads up that this flag will be removed in the upcoming 17.06 release.

This flag has been deprecated in docker 1.11 (https://github.com/moby/moby/releases/tag/v1.11.0) through aee260d in April 2016, and when used has been outputing a deprecation warning since;

Flag --email has been deprecated, will be removed in 17.06.

Originally this option was scheduled to be removed in docker 1.13, but extended to docker 17.06 due to a change in the deprecation policy.

Given that only docker 1.10 and older use this flag (which is EOL, including for CS versions, as of February 2017), will now be removed.


I see the aws-cli includes instructions to adapt for this;
https://github.com/aws/aws-cli/blob/9417311ddf284eaa02155aff850dd90b3e5d2c43/awscli/customizations/ecr.py#L49-L55

> Specify if the '-e' flag should be included in the 
> 'docker login' command.  The '-e' option has been deprecated 
> and is removed in docker version 17.06 and later.  You must 
> specify --no-include-email if you're using docker version
> 17.06 or later.  The default behavior is to include the
> '-e' flag in the 'docker login' output.


I would recommend to _reverse_ the default, given that the AWS cli currently
uses a deprecated option by default that hasn't been in use for more than a
year, and only is used by unsupported versions of Docker with known CVE's.

**Comment by kitingChris** [comment]
2019 :D 

```
$ eval $(aws --profile **** ecr get-login --region ****)
unknown shorthand flag: 'e' in -e
```

**Comment by oesteban-vx** [comment]
Adding `--no-include-email` to the aws call results in no `-e` option.
