### ISSUE TITLE
Recursive mount directories

### ISSUE THREAD

**Issue by ScreamingDev** [moby/moby#23424]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```

**Describe the results you received:**

Currently all directories need to be mounted by hand.

**Describe the results you expected:**

Imagine you have this tree:
- docker-compose.yml (making container1..3)
- fs
  - container1
    - home
      - me/hello.txt
      - you/hi.txt
  - container3
    - etc
      - foo.conf
    - var
      - log

There shall be an option like `recursive_mount: {host_path}:{container_path}`.
With

```
conainer1:
    recursive_mount: ./fs/container1/home:/home
```

It will merge the host directory into the container directory (only "home" in this case).

**Siblings:** So if the container has a directory "/home/yo-mama" then this will be kept.
**Diff in children**: If the container has "home/me/contain.txt" then it won't be synced back into the host. This would be only the case if the mapping is on the directory and not on the file.

Maybe container2 has the same mapping set. Then docker work as if it is a normal mapping because the host-dir is missing.

For **container3** the "var/log" directory is interesting to merge.

**Children**: If the container has "/var/log/other.log" on start which is missing in the host, then it will be synced to the host. Same for a directory but recursive/deep.

The normal mount currently would delete it.
This makes it very easy to setup new systems and overwrite only a part of it. By simply adding files in a directory the config stays clean, readable and is less work from now on.

There might be needed some options at least for the sync. With this (not sure about the syntax):

```
recursive_mount:
  -
    host: ./fs/foo
    container: /foo
    sync: false
```

You can disable the syncing back into the host. This will be common for large directories such as "/var/log".

Options like `sync: host` or `sync: container` could determine the sync direction. Upon starting and mounting the host always wins but after that the direction might be important.

**Comment by justincormack** [comment]
You can use `docker run -v path:/path,shared ...` to mount shared which should include submounts, if the host path is mounted shared, which is likely under a systemd based Linux distro.

By coincidence there was a LWN article yesterday explaining how shared mounts work (it is not simple) https://lwn.net/SubscriberLink/689856/149fdfd660fabdea/
