### ISSUE TITLE
swarm + embedded DNS + consul + php = getaddrinfo failed

### ISSUE THREAD

**Issue by vingrad** [moby/moby#23450]
**Output of `docker version`:**

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 36
 Running: 16
 Paused: 0
 Stopped: 20
Images: 36
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 master0: x.x.x.x:2376
  └ ID: F5I3:Y4I4:QODL:IWS2:NIMT:EL6D:OVKF:QOSL:IEI4:XNSJ:F64Y:F345
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.061 GiB
  └ Labels: executiondriver=, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=generic, storagedriver=aufs
  └ UpdatedAt: 2016-06-11T08:57:36Z
  └ ServerVersion: 1.11.2
 node1: x.x.x.x:2376
  └ ID: GIMW:3NUU:FIRF:OIUX:MJOF:C2DV:DQKW:QTDG:TFRY:MNNL:37GI:PTRG
  └ Status: Healthy
  └ Containers: 16
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 65.88 GiB
  └ Labels: executiondriver=, instance=d0, kernelversion=4.5.0-0.bpo.2-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=generic, storagedriver=overlay
  └ UpdatedAt: 2016-06-11T08:57:31Z
  └ ServerVersion: 1.11.2
 node2: x.x.x.x:2376
  └ ID: RREZ:AI62:UH4Z:FI4Q:UMGE:JRCG:YG7N:O3MI:AVHL:QLYK:3BYV:7NDR
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 4.966 GiB
  └ Labels: executiondriver=, instance=d1, kernelversion=4.5.0-0.bpo.2-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), provider=generic, storagedriver=overlay
  └ UpdatedAt: 2016-06-11T08:57:29Z
  └ ServerVersion: 1.11.2
Plugins:
 Volume:
 Network:
Kernel Version: 3.16.0-4-amd64
Operating System: linux
Architecture: amd64
CPUs: 14
Total Memory: 72.91 GiB
Name: a47d344ed774
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
all containers are definded in docker compose. There are no extern containers.

**Describe the results you received:**
Next exception 'MongoConnectionException' with message 'Failed to connect to: 'xxx_mongodb_1:27017: php_network_getaddresses: getaddrinfo failed: Name or service not known'

**Describe the results you expected:**
I use docker swarm with one master node, consul and two nodes for containers. I use also docker compose and user defined overlaynetwork with this definition: "network_mode: my-net" in the compose project config.

The problem is that I get the following error in my PHP-Container: " php_network_getaddresses: getaddrinfo failed: Name or service not known", but a sample ping-command in that container works Ok! 
.
ping xxx_mongodb_1
PING xxx_mongodb_1 (10.0.9.2): 48 data bytes
56 bytes from 10.0.9.2: icmp_seq=0 ttl=64 time=0.104 ms
.

With ping I get the hostname resolved, but not from PHP-FPM 5.5.
`
<?php
$result =`dns_get_record("xxx_mongodb_1");`
print_r($result);
`
The ouput from this PHP-script is:
Array ()

**Comment by thaJeztah** [comment]
What does the `/etc/resolv.conf` and `/etc/hosts` file inside that container look like? I've seen some other issues with PHP itself not being the best in resolving hosts (e.g., it also ignores `/etc/hosts`);

One other thought; PHP may reject `mongodb_1` as a hostname, because underscores are not allowed in hostnames, and it expects a valid DNS hostname; http://php.net/manual/en/function.dns-get-record.php

Does it work if you use the service name? (e.g. `mongodb`?)

**Comment by HackToday** [comment]
It seems not valid host for `mongodb_1`, something strange would cause issue like in chef related

**Comment by vingrad** [comment]
> What does the /etc/resolv.conf and /etc/hosts file inside that container look like? 
`
 cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
root@4aa4f2e8f3ee:/etc/php5/fpm# cat  /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
136.xxx.xxx.xxx vvi-convert.xxx.com  // this is defined with "extra_hosts" in compose-file.
136.xxx.xxx.xxx vvi-uploads.xxx.com  // this is defined with "extra_hosts" in compose-file.
10.0.9.12       4aa4f2e8f3ee
172.18.0.14     4aa4f2e8f3ee
`

> Does it work if you use the service name? (e.g. mongodb?)
No, this does not work via PHP neither with ping, but with **ping xxx_mongodb_1** I don't have any problem.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info. Additionally, Classic Swarm is deprecated.
