### ISSUE TITLE
Docker run sub-command reference documentation needs improvement

### ISSUE THREAD

**Issue by charleswhchan** [moby/moby#23468]
> Mount volume (-v, --read-only)
> 
> `$ docker  run  -v `pwd`:`pwd` -w `pwd` -i -t  ubuntu pwd`
> 
> The -v flag mounts the current working directory into the container. The -w lets the command being executed inside the current working directory, by changing into the directory to the value returned by pwd. So this combination executes the command using the container, but inside the current working directory.

Source: https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volume--v---read-only

Areas for improvement: :smiley: 
- It assumes the user understands `pwd` command is evaluated to get the current working directory: Perhaps it's simpler to use `/current/directory` in the example instead? (Similar to the the `/doesnt/exist` used in the example just below this block.)
- Explanation for `-w` switch is confusing. My understanding is that the `-w` refers to a working directory **insider** the container. So the example should explain that the command is executed in a directory inside the container that happens to have the same name as the current working directory. In additional, because of the bind volume, the directory inside the container is mapped to the current working directory on the host.

**Comment by sbose78** [comment]
#dibs

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
