### ISSUE TITLE
incorrect port shown for docker registry

### ISSUE THREAD

**Issue by ghost** [moby/moby#23465]
Even though I'm providing my own config.yml for docker registry, with my own custom port (not 5000), `docker ps -a` still shows 5000/tcp, which is incorrect.

Registry run cmd
`docker run -d --net=foo --ip=192.168.123.123 --name registry -v /tmp/config.yml:/etc/docker/registry/config.yml registry:2`

config.yml includes the lines:

```
http:
  addr: :1234
```

netstat inside the registry CT shows

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35517        0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::1234                 :::*                    LISTEN      1/registry      
udp        0      0 127.0.0.11:33750        0.0.0.0:*                           -
```

As you can see there is no 5000 anywhere.

**Steps to reproduce the issue:**
1. Start registry on custom docker bridge without any docker port forwarding magic options
2. Specify custom port in config.yml
3. Confirm registry is working on custom port, confirm there's nothing listening on port 5000 `netstat -lntup` inside CT
4. Run `docker ps -a` on host and notice it still says 

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
abc123        registry:2          "/bin/registry serve "   8 minutes ago       Up 8 minutes            5000/tcp            registry
```

**Describe the results you received:**
Registry works as expected on custom port. But the default port of 5000/tcp is displayed on `docker ps -a`. This CT does not and has never listened on port 5000 since I used `docker run`. I did not request any port forwarding or write 5000 anywhere.

**Describe the results you expected:**
1. Run on custom port specified in config.yml.
2. Don't do any docker port forwarding magic if I don't ask for it. (I did not specify -p 5000 blah)
3. Don't show 5000/tcp when it was not requested with `-p` and does not exist as a listening port inside the CT.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 16 GiB
Name: foo
ID: foo
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 host

**Comment by HackToday** [comment]
I am thinking if it is because that

https://github.com/docker/distribution-library-image/blob/5cbbc8d1e6046cef5938e3380fd2a5fbd854f921/Dockerfile

It expose 5000 port.

```
...
VOLUME ["/var/lib/registry"]
EXPOSE 5000

ENTRYPOINT ["/bin/registry"]
CMD ["serve", "/etc/docker/registry/config.yml"]
```

**Comment by HackToday** [comment]
maybe @aaronlehmann  knows more

**Comment by thaJeztah** [comment]
Correct, `docker ps` only shows what the image/container *says* it exposes, it does not check if there's actually a process in the container listening on that port, or if the containers process also listens on another port. (Also see https://docs.docker.com/engine/reference/builder/#expose)

I don't think there's a bug here, but happy to hear if you think there is

**Comment by lope** [comment]
Hey guys,

Thanks for your responses.

Yes, I think it's a "bug" or unwanted behavior.
In fact I was thinking of writing my own wrapper that removes the whole port column (as well as container ID, as I name all of my CTs).

It's only natural that containers will be deployed by people that did not write the docker file, and quite likely they will want to select their own port for deployment. The display of the original container author's port number is purely an annoyance. It's like having a clock hanging on the wall that is set 2 hours early/late. People see the clock and think, "oh it's really late/early". It's ridiculous to display status information that is not status. (Just a wild guess, but doesn't `ps` stand for process status?) Rather than being status information, it's an arbitrary and often useless historical fact.

**Comment by thaJeztah** [comment]
@lope however, to change the port number, there's usually no need to change the settings;

    docker run -p <hostport>:<containerport>

in your case;

    docker run -d -p 1234:5000 --name registry registry:2

Which is output as;

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
0e3020fd23a1        registry:2          "/bin/registry serve "   5 seconds ago       Up 4 seconds        0.0.0.0:1234->5000/tcp   registry
```

**Comment by aaronlehmann** [comment]
I agree with @thaJeztah here. Docker mentions that port 5000 is exposed, because that's configured in the Dockerfile. If you override the port mapping with `-p`, `docker ps` will reflect that change.

**Comment by lope** [comment]
@thaJeztah @aaronlehmann you guys would be correct in the simplest networking use-case. But not everybody uses the do-it-for-me docker networking stuff.

If you run a custom bridge there's no `-p` options involved. I mentioned that I'm using custom networking in the original issue.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
