### ISSUE TITLE
insecure registry nor self signed certificates working with docker 1.11 (worked with 1.9)

### ISSUE THREAD

**Issue by maxnoe** [moby/moby#23512]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.676 GiB
Name: maxnoe-mac
ID: AJ2Z:G6U4:LKAZ:PXNC:PBBJ:7B73:BM6B:NYTX:JZAS:XW6H:VAV2:7XDM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit suppor
```

**Steps to reproduce the issue:**
1. Try logging in to a registry with self signed certificates

```
docker login myregstry.example.com:5000
```

This worked with docker `1.9` on my machine because I have `--insecure-registry myregistry.example.com:5000` added to the `DOCKER_OPTS` in `/etc/defaults/docker`.
Also I registered the certificate system wide. `curl` works without providing the certificate explicitly

**Describe the results you received:**
`Error response from daemon: Get https://registry.e5.physik.tu-dortmund.de:5000/v1/users/: x509: certificate signed by unknown authority`

Or, when also added to `/etc/docker/certs.d/<url>/ca.crt`:
`Error response from daemon: Get https://registry.e5.physik.tu-dortmund.de:5000/v1/users/: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "registry.e5.physik.tu-dortmund.de")`

**Describe the results you expected:**
Succesfull login

**Additional information you deem important (e.g. issue happens only occasionally):**
The registry is running as a rancher service behind a loadbalancer.

**Comment by thaJeztah** [comment]
Did you also update to a newer version of Ubuntu? The `/etc/defaults/docker` file is only used for systems running upstart. Ubuntu 16.04 uses systemd, so that file is not used.

The easiest way to configure is to use a `daemon.json` configuration file, as explained here;
https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

For example:

```json
{"insecure-registries":["myregstry.example.com:5000"]}
```

Alternatively, use a systemd drop-in configuration file, as explained here: https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by MaxNoe** [comment]
That is strange, because the system was a fresh ubuntu 16.04 installation.

**Comment by thaJeztah** [comment]
Did you previously install the packages that are shipped by ubuntu (not the docker packages)? I think they ship with a different systemd unit file that includes the `/etc/defaults/docker` file

**Comment by MaxNoe** [comment]
That might be.

**Comment by MaxNoe** [comment]
But does it not work to register the self-signed certificate?

**Comment by thaJeztah** [comment]
If you only set the options in `/etc/defaults/docker`, those options are not read by the daemon, so basically you don't have `--insecure-registry` configured in that case.

**Comment by MaxNoe** [comment]
Yes,  but installing the certificate should make it unnecessary to set `insecure-registry`,  shouldn't  it?

**Comment by thaJeztah** [comment]
Hm, you used these installation instructions for configuration? https://docs.docker.com/engine/security/certificates/

**Comment by MaxNoe** [comment]
No, I just followed these instructions: https://docs.docker.com/registry/insecure/. So I only copied the `.crt` file .

**Comment by MaxNoe** [comment]
Ok. This solved the issue. It was indeed the missing `.key` and `.cert` files. The documentation on the registry page should be updated.

**Comment by thaJeztah** [comment]
would you be interested in opening a PR to update that? Looks like that page is actually in a different repository; https://github.com/docker/distribution/blob/master/docs/insecure.md

**Comment by MaxNoe** [comment]
Sorry. But i might have been to optimistic.  

I am using rancher and the registry stack from their catalog. This generates a self-signed certificate
`registry.crt` and a `registry.key`. 

What do I have do do, to make it work with `docker login`? 
I added the `registry.crt` to `/etc/docker/certs.d/<mydomain>/` and to `/usr/local/share/ca-certificates`. I ran `update-ca-certificates`. I can use `curl <mydomain>` and get the correct response.

Stil, trying to login I get:
```
Error response from daemon: Get https://registry.e5.physik.tu-dortmund.de:5000/v1/users/: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "registry.e5.physik.tu-dortmund.de"
```

**Comment by sbose78** [comment]
#dibs ( claiming this to myself to make the doc change )

**Comment by sbose78** [comment]
#dibs

**Comment by sbose78** [comment]
@MaxNoe , @thaJeztah 
This is what I understand.

registry.crt sounds like the client certificate to me , and not the CA / SubCA certificate. 

The *docker login* command is complaining about not finding the CA/SubCA Certificate.

So I'm guessing copying over the registry.crt wouldn't suffice. I think we would need to copy over the SubCA of the registry.crt into the appropriate locations.

Does docker look up the chain?

**Comment by sbose78** [comment]
As per https://docs.docker.com/engine/security/certificates/
You need 3 files:

1. The Client certificate which is a **.cert** file. 
2. The private key of this client certificate which is a **.key** file.
3. The CA Certificate which is a .**crt** file.

So (1) and (2) is used for client certificate auth. Here, (1) is not the CA Certificate.
Is the *registry.crt* you are using a CA / SubCA certificate or is it the client certificate?

If it's the client certificate then 
Have you added the CA Certificate ( (3) in the list above ) to  /usr/local/share/ca-certificates ? That is what *docker login* is complaining about as per the message.

**Comment by sbose78** [comment]
This is where the auth happens https://github.com/docker/engine-api/blob/master/client/login.go#L14
and it consumes the certificates as per https://github.com/docker/engine-api/blob/master/client/client.go#L40

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
