### ISSUE TITLE
Feature request: keep files timestamp if copy to container

### ISSUE THREAD

**Issue by gebele** [moby/moby#23511]
As you describe the cp command behaves like cp -a I miss timestamps I work with for some files. I would really appreciate the --preserve implementation cp -p for that. Or at least an implementation of the files timestamp out of cp -p e.g. a command like: cp -t.

**Comment by thaJeztah** [comment]
Looks like this is a duplicate of (or very similar to) https://github.com/moby/moby/issues/17175. Closing this one
