### ISSUE TITLE
Windows: requirement for Hyper-V on Windows client should be explicit in error message.

### ISSUE THREAD

**Issue by swernli** [moby/moby#23588]
Now that HYPER-V is the default isolation mode for the daemon when running on Windows client, users who have not installed the HYPER-V feature in addition to the Containers feature will get an error message when starting a container indicating that a hypervisor is not present.  That message comes from Windows itself (via the HCS) and while accurate, doesn't give the additional info about what features need to be installed to successfully run containers.  The HCSShim in Docker should add additional guidance to this error message before returning it to the user in order to better guide them on how to get containers running.

**Comment by swernli** [comment]
@jhowardmsft FYI

**Comment by jhowardmsft** [comment]
@darrenstahlmsft I think you were looking at this and using dism APIs. Did that ever happen, or was it just too expensive to consider in the end as IIRC you said it was. Although the alternate I believe was to look for a unique DLL.
