### ISSUE TITLE
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: write /usr/share/man/man3/zgeequb.f.3.gz: read-only file system

### ISSUE THREAD

**Issue by ztetfger** [moby/moby#23660]
**Output of `docker version`:**

```
[root@COM240 ~]# docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
[root@COM240 ~]# docker info
Containers: 0
Images: 3
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-2492958-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/mapper/vg_docker-docker_data
 Metadata file: /dev/mapper/vg_docker-docker_metadata
 Data Space Used: 7.162 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.2 GB
 Metadata Space Used: 4.325 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.el7.x86_64
Operating System: ZTE Virtulization Environment i
CPUs: 16
Total Memory: 23.4 GiB
Name: COM240
ID: UYX4:Y2RP:4KKF:NA6P:PZP3:BPGY:QGBW:COZN:BOYE:4LXV:6XL3:7FSW

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos

**Steps to reproduce the issue:**
1.docker load < AA.tar

**Describe the results you received:**
[root@host ]# docker load < AA.tar
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: mkdir /usr/lib/python2.7/site-packages/keystone/assignment: read-only file system
[root@host ]# docker load < /home/fengshq/AA.tar
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib64/python2.7/site-packages/scss/functions/compass/sprites.py: read-only file system
[root@host ]# docker load < /home/fengshq/AA.tar
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: write /usr/share/man/man3/zgeequb.f.3.gz: read-only file system

**Describe the results you expected:**
After "docker load",the command "docker images" will show the new loaded image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Have you tried using `sudo`, or no difference?

What distro are you running on? (output says "ZTE Virtulization Environment i")

**Comment by ztetfger** [comment]
Yes, I tried, but I got the same error information.

**Comment by cpuguy83** [comment]
Did your whole filesystem go read-only?

**Comment by thaJeztah** [comment]
closing; this one went stale
