### ISSUE TITLE
GELF Driver single DNS resolution 

### ISSUE THREAD

**Issue by lauraglasu** [moby/moby#23679]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 159
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 328
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: 46H5:U5JJ:KU56:E6TG:M2SV:OZCP:RKIR:QAUL:72FB:PVIW:BZSQ:LEPF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 52
 System Time: 2016-06-17T14:53:30.170427953Z
 EventsListeners: 0
Username: laurag
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker installation with toolbox on mac

**Steps to reproduce the issue:**
1. docker run -p 5000:5000 --log-driver=gelf --log-opt gelf-address=udp://graylog-test.my-domain.com:12201 --log-opt tag=registry --log-opt env=test registry:2.4.1
When running the registry with the command above any logs get to the graylog server just fine
When deploying a second graylog server and changing the graylog-test.my-domain.com dns record to point to the new server:
- From the host running the registry container and from the container I can resolve the IP for the new graylog server
- all the registry logs are still being sent to the old graylog server

**Describe the results you received:**
- gelf log driver seems to resolve the dns for the gelf address only at container startup

**Describe the results you expected:**
- expecting the gelf driver to have some default or configurable ttl for the gelf address dns

**Additional information you deem important (e.g. issue happens only occasionally):**
Previously closed issues:
https://github.com/docker/docker/issues/17904
https://github.com/docker/docker/issues/16330

**Comment by thaJeztah** [comment]
@lauraglasu have you tried the test build mentioned in https://github.com/docker/docker/issues/17904#issuecomment-194403940 to see if that resolved your issue?

**Comment by thaJeztah** [comment]
I'm closing this issue in favour of https://github.com/moby/moby/issues/17904, was reopened, and has more information/discussion.
