### ISSUE TITLE
docker cp occasionally times out

### ISSUE THREAD

**Issue by mzhaom** [moby/moby#23685]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1223
Images: 42
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2488
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 16
Total Memory: 62.82 GiB
Name: jenkins-03
ID: K2ML:X3FB:YYFA:NF52:OSDH:57Y3:CPY4:YJE7:QCBZ:FD4U:6FPB:5OM2
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:**
1. Run a bunch of docker containers 
2. Stop them
3. Copy contents inside contains' /tmp to host

**Describe the results you received:**
Sometimes the docker cp command hangs for 60 seconds or even more. The size of /tmp directory is not large, at most around ~100MB.

**Describe the results you expected:**
docker cp should finish in a reasonable time.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Comment by thaJeztah** [comment]
are you still able to reproduce this issue on the current (1.11.2) release?

**Comment by mzhaom** [comment]
We added some timing and I saw some improvement with the upgrade, but still the result looks worrisome to me.

With 1.9.1, a lot of time we saw it took about 20 seconds to copy less than 1MB data from the container to host, with 1.11.2, I saw the time dropped to 11 seconds, but still that's significant.

**Comment by thaJeztah** [comment]
closing; this one went stale
