### ISSUE TITLE
Block new unsupported docker commands on Windows

### ISSUE THREAD

**Issue by StefanScherer** [moby/moby#23680]
Trying the latest rc binaries on Windows Server 2016 TP5 leads to errors that lead to the assumption that new function could work. It would be better to block these commands on Windows with a better error message.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 30
Server Version: 1.12.0-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Kernel Version: 10.0 14300 (14300.1030.amd64fre.rs1_release_svc.160603-1734)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: QIHN:JA6P:4W5I:ASMZ:2P5G:3VU3:ILQZ:MTN4:ONGA:BOC7:JBRI:N3NB
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanscherer
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2016 TP5

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

```
C:\> docker swarm init
Error response from daemon: remove C:\ProgramData\docker\swarm\worker\tasks.db: The process
cannot access the file because it is being used by another process.
```

**Describe the results you expected:**

```
Command swarm is not supported on Windows
```

**Comment by jhowardmsft** [comment]
Sure, I'll look after Dockercon.

**Comment by aaronlehmann** [comment]
cc @tonistiigi

**Comment by thaJeztah** [comment]
ping @jhowardmsft 😇

**Comment by dnephin** [comment]
I can pick this up if no one else has it.

We could remove the commands entirely, or print an error message saying they aren't supported. I'll start with the latter.

**Comment by duglin** [comment]
I'd like to see some kind of daemon flag to enable this so its not just a Windows-only thing. There will be deployments that don't support this model of orchestration so having them present a consistent and nice "sorry" msg would be nice.

Additionally, hiding it from the "docker help" stuff too would be nice, but secondary.

**Comment by dnephin** [comment]
> hiding it from the "docker help" 

Yes, that is easy to do.

> I'd like to see some kind of daemon flag to enable this

I'm going to leave that for a separate PR, I can see it being a more controversial.

**Comment by jhowardmsft** [comment]
@dnephin - Yes, please, if you have the cycles, go for it. Sorry, I'm swamped with other work at the moment, no time to immediately look at this.

**Comment by tonistiigi** [comment]
What commands are we talking about? Is there some unfixable problem why swarm command could not work. We should fix the issues instead of hiding commands. https://github.com/docker/swarmkit/pull/941 is one pr tackling these issues and I see @jhowardmsft working on that.

**Comment by dnephin** [comment]
@tonistiigi that's a good question. Is swarm mode supposed to be working on windows?

I've got a branch to hide these on windows (https://github.com/docker/docker/compare/master...dnephin:block_swarm_cmds_on_windows), but I'll wait to open the PR

**Comment by duglin** [comment]
when not using swarm mode I see stuff like this:
```
$ docker service create ubuntu
Error response from daemon: This node is not a Swarm manager. Use "docker swarm init" or "docker swarm join --manager" to connect this node to Swarm and try again.
```
so it would be nice if, when not running in swarm mode, users don't see cmds that will fail and API calls get a consistent "not supported" type of error.

**Comment by tonistiigi** [comment]
> so it would be nice if, when not running in swarm mode, users don't see cmds that will fail and API calls get a consistent "not supported" type of error.

Only daemon knows if it is a swarm manager. Client doesn't know that before making the request. So unless we want to make a `docker info` request when running `--help` there is not much that can be done here.

**Comment by duglin** [comment]
well that was going to be my question for @dnephin but I decided to wait until his PR to see how he managed that  :-)

**Comment by dnephin** [comment]
Oh ya, I guess I was implementing it with go build tags, which isn't correct because a windows client can still hit a linux engine.

**Comment by StefanScherer** [comment]
Closing, `docker swarm init` now works on Windows :-)
