### ISSUE TITLE
[1.12-rc2] docker service --help should show the default endpoint-mode value

### ISSUE THREAD

**Issue by dgageot** [moby/moby#23728]
In 1.12, I can create a service and set its `endpoint-mode` with:

```
$ docker service create --endpoint-mode VALUE ...
```

The output given by `docker service create --help` doesn't say which is the default endpoint-mode value:

```
$ docker service create --help

Usage:  docker service create [OPTIONS] IMAGE [COMMAND] [ARG...]

Create a new service

Options:
      --constraint value             Placement constraints (default [])
      --endpoint-mode string         Endpoint mode(Valid values: VIP, DNSRR)
...
```

**Comment by dgageot** [comment]
Same issue with `docker service update --help`

**Comment by thaJeztah** [comment]
I think this may be if the default is set on the daemon, and not the client (client default values are automatically shown)

**Comment by dgageot** [comment]
It looks like the default is `vip` on the daemon

**Comment by arthurtsang** [comment]
what does ```vip``` and ```dnsrr``` mean?  it's not documented in the web page.  https://docs.docker.com/engine/reference/commandline/service_create/

**Comment by cpuguy83** [comment]
@arthurtsang virtual IP and dns round robin.

**Comment by outcoldman** [comment]
Btw a little bit of documentation can be found in the code https://github.com/docker/swarmkit/blob/60115eac10ffac0e77b0085df0b77be04c1ad1bc/api/specs.proto#L186

**Comment by thaJeztah** [comment]
Looks like is now shown;

```
docker service create --help | grep endpoint
      --endpoint-mode string               Endpoint mode (vip or dnsrr) (default "vip")
```
