### ISSUE TITLE
BUG REPORT INFORMATION : Docker volume is not working in windows

### ISSUE THREAD

**Issue by ravi523096** [moby/moby#23744]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 116
 Running: 0
 Paused: 0
 Stopped: 116
Images: 62
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 333
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: 4A5T:746J:RJQD:6OZR:4V67:CBQX:NW37:3MFG:BKLZ:2QJV:XNG6:HSES
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 31
 System Time: 2016-06-19T21:03:19.450746817Z
 EventsListeners: 0
Username: ravikalla
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have installed Docker on my Windows desktop

**Steps to reproduce the issue:**
1.Start a container with volume that points to a Windows host folder
2. Files in the windows folder are not visible in the container

Eg:
$ ls /C/Users/Public/XMLCompareFiles/resources
    file1.xml  file2.xml
$ docker run -i -t -v /C/Users/Public/XMLCompareFiles/resources:/resources ubuntu bash
# ls /resources

<no files>

**Describe the results you received:**
Couldn't view the files from the container 

**Describe the results you expected:**
Files that are present in Windows Host Directory should be visible inside container.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue is happening always. I checked with Ubuntu and Java image

**Comment by thaJeztah** [comment]
This one is really old now, and I suspect this may have been due to paths not shared between the host and the boot2docker VM.
