### ISSUE TITLE
Allow use of network name for network interface

### ISSUE THREAD

**Issue by bergtwvd** [moby/moby#23742]
Containers can be connected to several networks simultanously. The network interfaces are typically named eth0, eth1, eth2, etc. In some instances containers need to be directed to use, say, interface ethX for traffic on Docker network A, and ethY for traffic on Docker network B. Currently there is no relationship between network interface name and Docker network name.

The current (clumsy) work round (via Docker Compose) is to define an ip range per Docker network, and tell the container to use the network interface that falls in that ip range.

A better solution is the ability to name network interfaces after the Docker network name. If the container needs to use a certain network, it can be instructed to use the interface name that matches the Docker network name.

Feature request against:
Docker version 1.11.2, build b9f10c9

Thanks!

**Comment by p-thurner** [comment]
I also have this issue, we would like to do accouting via iptables and need to know the names of the network interfaces.

**Comment by michaelkwan** [comment]
+1 vote as well

**Comment by thaJeztah** [comment]
@bergtwvd there's another issue that is slightly newer, but duplicates this one, and has some more discussion around this; https://github.com/moby/moby/issues/25181. I'll close this one to keep the discussion central, but feel free to participate in the discussion on that issue 👍
