### ISSUE TITLE
container image not matching what is actually running

### ISSUE THREAD

**Issue by chromerobv** [moby/moby#23774]
we have our own images that run java jar files within them. this weekend we had a strange thing happen. our deploy script was run like normal but for some reason all the new images that were started were running the wrong thing inside the image. so for instance we have some images like auth, transaction,invoice. after the deploy the container running invoice actually had auth inside it running. no the images were not bad. when we redeployed each of them they came up fine.
we are using swarm so if this belongs in the swarm issues i will gladly close and move it. i wasn't sure which was best.

*forgot to mention this also happened on several of our machines.

version 1.11.1
swarm 1.2.0

**Comment by thaJeztah** [comment]
how did you deploy? do you have some tooling to deploy/build those images? also, "running the wrong thing in the image"; are all services using the same image, but running a different command? are they using different images?

It's really hard for us to help / investigate without more information

**Comment by chromerobv** [comment]
they all have different images that are built via jenkins. the base image is the same but the jar that goes it is different. so again if the image was called auth it somehow seemed as though the invoice jar as being run inside of it. 
deploy we use ansible to just run docker run commands.

**Comment by thaJeztah** [comment]
That really sounds as if something went wrong in Jenkins. I don't see how docker can run the wrong jar. If you check those images, do they have the right jar in them?

**Comment by chromerobv** [comment]
Just had it happen on another server. On a whim I restarted some of the containers and they suddenly went back to normal. It's like some metadata is screwy or something, pointing the ports to the wrong containers.

**Comment by thaJeztah** [comment]
Alright, for port mapping it's possible you're running into https://github.com/docker/docker/pull/22997, which is resolved in docker 1.11.2 https://github.com/docker/docker/releases/tag/v1.11.2

**Comment by thaJeztah** [comment]
@chromerobv is this still an issue for you, or is it okay to close?

**Comment by thaJeztah** [comment]
Closing, as this went stale
