### ISSUE TITLE
Swarm events

### ISSUE THREAD

**Issue by tiborvass** [moby/moby#23827]
We should add swarm events to the docker events stream.

Cc @tonistiigi @vieux

**Comment by cleishm** [comment]
I'd love to see changes to the service replica count appear as events.

**Comment by cpuguy83** [comment]
@tiborvass What do you think for 1.12? I would think we should at least be able to add _some_ events rather simply and could argue that it's needed.

**Comment by vdemeester** [comment]
@tiborvass @cpuguy83 looking into it but one question would be : should these swarm events be *send* to daemon `/events` endpoint or should it be an endpoint on its own `/swarm/events` (`docker swarm events` then) ?

**Comment by cpuguy83** [comment]
I think /events

**Comment by bitsofinfo** [comment]
Any idea on an eta for this?

**Comment by thaJeztah** [comment]
@bitsofinfo this requires changes in SwarmKit (also see the discussion on https://github.com/docker/docker/issues/23964), so most likely in 1.13

**Comment by thaJeztah** [comment]
with which I mean to say; not in a patch release for 1.12

**Comment by tlvenn** [comment]
@thaJeztah I just want to emphasis how important this is. Any custom L7 load balancer such as Traefik or Fabio will need to tap into swarm events to react to service/task updates in order to route traffic properly.

>I'm a bit worried that those projects will now implement all kind of workarounds, and by the time Swarm events are implemented, it's too late.

Ya it's already happening... :(

**Comment by thaJeztah** [comment]
Swarm events are now available as part of the `docker events` (on manager nodes); https://github.com/moby/moby/pull/32421

This feature is included in docker 17.06 and up
