### ISSUE TITLE
Left nav can render with no clear indication of where the current page is in the nav

### ISSUE THREAD

**Issue by davidmichaelkarr** [moby/moby#23906]
When rendering a left nav where selections in that area render pages in the main content area, it's important to have a clear indication in the left nav where the user is.  That is, where the content for the main content area came from.

I imagine I could find many examples of this, but I'm currently looking at [Docker networks feature overview](https://docs.docker.com/engine/userguide/networking/).  I would provide a screenshot, but imagebin isn't working for me right now.

What I see on the screen indicates that I might be somewhere in the "User Guide" section, and I imagine that I know this page is talking about networking, so I might be somewhere around the "Network configuration" section, but the rendering of the left nav isn't helping me here.

**Comment by thaJeztah** [comment]
Thanks for reporting! I think @sfsmithcha was working on this for "index" pages that are not directly accessible from the menu (such as the one you linked to).
