### ISSUE TITLE
[FEATURE] Set docker timezone from Windows/MAC GUI

### ISSUE THREAD

**Issue by Murf** [moby/moby#23926]
It would be great to be able to set the /etc/localtime link on the docker VM via the UI

PS C:> date
Fri Jun 24 09:57:56 AUSEST 2016
PS C:> docker run --rm -it centos date
Thu Jun 23 23:57:57 UTC 2016
PS C:>

**Comment by thaJeztah** [comment]
I think the timezone in the VM is set to UTC at all times (the time is synchronized with the host machine), but I may be wrong, For the timezone inside the *container* (which *is* UTC by default), see https://github.com/docker/docker/issues/3359 and https://github.com/docker/docker/issues/12084

However this is a feature request for Docker for Mac / Windows, so best reported through https://forums.docker.com/c/docker-for-mac

perhaps @justincormack knows what the plans are in this area; e.g. Can it be. Add to follow the timezone of the system?

**Comment by justincormack** [comment]
What is the use case for setting the host timezone? You can set the in container timezone if you want by setting `/etc/localtime` in the container. UTC is just the default if you don't set this, unrelated to the host timezone. None of the times you show are related to the VM localtime link.

**Comment by Murf** [comment]
I put this in my Dockerfile and it worked great, thanks.
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Australia/Melbourne /etc/localtime

**Comment by prlauko** [comment]
The use case for setting the host timezone is to give a meaningful default to all containers running on that host. It is much simpler setting it once, than messing with all containers one by one.

**Comment by benoitscherrer** [comment]
I agree. It is very useful to map the localtime and timezone folders, for example with: 
```
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
```

I really think it would make sense for Docker for Windows to support that as well.

**Comment by taraslegan** [comment]
@benoitscherrer  I didn't find any solution to run docker container with host timezone on windows. Yes, we can directly specify timezone using TZ flag `docker run -e TZ=Europe\Kiev ........`, but when you don't know who will run your image and in which timezone person is located, what is the workaround?
