### ISSUE TITLE
User-specified network driver option defaults

### ISSUE THREAD

**Issue by programmerq** [moby/moby#23938]
It is possible to configure network drivers at network create time:

```
docker network create -d overlay -o "com.docker.network.mtu=9001" foobar
```

In some cases, you need to change an option for _all_ networks created on a system. Right now, the way to accomplish that will be to change _every_ compose file, Makefile, bash script, or other deploy mechanism to accommodate this host-wide requirement. This is not a scalable solution.

There should be a ui/ux that would allow a user to set defaults system-wide: "all overlay networks will need to have this value for that option".

Implementing an alternate driver that has the needed behavior is not a viable workaround. It requires the same amount of effort to change _all_ compose/make/bash/deploy scripts to use the alternate driver, so this won't address the issue.

**Comment by thaJeztah** [comment]
This was implemented in https://github.com/moby/moby/pull/43197
