### ISSUE TITLE
Docker build URL does not work with ssh://

### ISSUE THREAD

**Issue by synotna** [moby/moby#23932]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:36:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:36:47 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 33
 Running: 6
 Paused: 0
 Stopped: 27
Images: 281
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 291
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.865 GiB
Name: devvm-ase.dev
ID: SLOY:VLX5:7LUO:4Y2Q:4RT3:LSVS:XSMG:GQ5G:EOIA:NXXO:TJYX:EWE7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker build ssh://git@github.com:docker/docker.git

**Describe the results you received:**
unable to prepare context: unable to evaluate symlinks in context path: lstat /home/tech/partner-backend-deploy/ssh:: no such file or directory

**Describe the results you expected:**
docker successfully cloning the git repo into context

**Additional information you deem important (e.g. issue happens only occasionally):**
git clone supports ssh://[user@]host.xz[:port]/path/to/repo.git/ so I think docker should?

scp-like syntax ( [user@]host.xz:path/to/repo.git/ ) does not cover having ssh on a non-standard port without resorting to using ssh config

**Comment by thaJeztah** [comment]
AFAIK, only http(s) is supported https://github.com/docker/docker/blob/master/docs/reference/commandline/build.md, I don't think there's plans currently to extend the available options.

**Comment by vdemeester** [comment]
@synotna it's a rather tricky to support `ssh://` for `docker build` though, as the build is daemon-side. This would mean that either we would send a private ssh key to the daemon (security-wise this is no good), or to clone the repository on the client and send it to the daemon, which would double the amount of data received/send.

For a client side builder, this would be a little bit easier to do though I think.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/33711#issuecomment-341512110

**Comment by Ilhicas** [comment]
As referenced by @shin- in https://github.com/docker/docker-py/issues/980

Copying $HOME/.ssh to /root/.ssh does the trick for local builds.

I believe that at least for local builds we should be able to point the SSH key to look for as well as the known_hosts file as it will also complain for unknown hosts.

**Comment by jannik-mohemian** [comment]
This workaround ☝️does not work on macOS
