### ISSUE TITLE
Attach both --device=XXX and --net=host to docker run command will always only add one same device to container, no matter how many times you run this command to start a new container.

### ISSUE THREAD

**Issue by sqstars** [moby/moby#23972]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 121
Images: 446
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-205149010-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 29.38 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.514 GB
 Metadata Space Used: 58.05 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.089 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.628 GiB
Name: stf.example.org
ID: 42IK:ZPOO:HX7V:JVUJ:XECG:Y6MT:QSV7:7AF5:6B2C:LQ7I:DBT4:M3ZL
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

host os is Centos 7

**Steps to reproduce the issue:**
1. lsusb

Bus 002 Device 024: ID 12d1:1052 Huawei Technologies Co., Ltd. 
Bus 002 Device 026: ID 2717:0368

two mobiles have been connected.
1. run docker container

docker run --name slave1 --device=/dev/bus/usb/002/024 --net host myimage 
docker run --name slave2 --device=/dev/bus/usb/002/026 --net host myimage

I think myimage is any image that has a Android sdk.
1. into container and check the devices

docker exec -it slave1 bash, then adb devices
docker exec -it slave2 bash, then adb devices

**Describe the results you received:**

both adb devices will output the **same** serial id of /dev/bus/usb/002/024, the second device is missing.

**Describe the results you expected:**

the first displays the serial id of /dev/bus/usb/002/024,  the second shows serial id of /dev/bus/usb/002/026

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
