### ISSUE TITLE
Remote API env variable

### ISSUE THREAD

**Issue by rumkin** [moby/moby#24037]
How to provide linking-like variables inside of container with remote API? Docker itself provides variables:

```
DB_PORT_5432_TCP_PORT=5432
DB_PORT_5432_TCP_ADDR=172.17.0.5
```

I need to provide my own variables with infrastructure data when starting container. How could I do that.

**Comment by cpuguy83** [comment]
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#create-a-container

See the "Env" field.

**Comment by rumkin** [comment]
I know about "Env" field but I need to update variables sometimes without recreating whole container.

**Comment by cpuguy83** [comment]
You cannot update the environment of a running container (it would be impossible to inject into the process).

**Comment by rumkin** [comment]
I need to update it when it stopped.

**Comment by cpuguy83** [comment]
It is not... not sure if it would be supported b/c it would always have to be an offline change.
How come creating a new container is not workable?

**Comment by rumkin** [comment]
As I see in sources linking is working this way. I'm building distributed microservice application manager and recreation will remove all logs, change ids and so. It could be hard to debug. And finally It looks expensive.

**Comment by cpuguy83** [comment]
Approx same cost to create a new container as to stop/start a container.

BTW, I'm not saying no, however: a distributed system needs to be fault tolerant. Relying on container ID's, logs, or even which node it is scheduled to is counter to this.

**Comment by rumkin** [comment]
Yep, it should be fault tolerant. But it's also should be very simple and strict to stay clear for those who support them. I think mess of containers is not a good solution.

Container creation will cause multiple disk read/writes to create new container fs structure. And I think it couldn't be so cheap as start/stop.

**Comment by rumkin** [comment]
@cpuguy83 Reopen this issue. [This is](https://github.com/docker/docker/issues/24037#issuecomment-229044532) not an answer to my question and nobody can discuss it or help to solve.

**Comment by cpuguy83** [comment]
Yep, we can talk about it.
Likely if this is implemented we'll need a warning on the CLI that changes won't take affect until the container is restarted.

**Comment by rumkin** [comment]
@cpuguy83 Thanks!

**Comment by rumkin** [comment]
I see two possible places to realise this behaviour: containers start/restart method and container update method.

**start method**: As I see in the source each time container is starting it's environment modifies with linked containers' environments. Calls order:

1. [containerStart](https://github.com/docker/docker/blob/e76e52b38b9829ccf613995f2afa0394230800ef/daemon/start.go#L130) line 130.
2. [createSpec](https://github.com/docker/docker/blob/e76e52b38b9829ccf613995f2afa0394230800ef/daemon/oci_linux.go#L606) line 606.
3. [populateCommonSpec](https://github.com/docker/docker/blob/e76e52b38b9829ccf613995f2afa0394230800ef/daemon/oci_linux.go#L579) line 579.

So it's necessary to update start and restart methods to pass env variables there.

**Update method**: Uses HostConfig structure as the only argument and this structure could not be modified. I think that there is should be second argument with type ContainerUpdate or so.

**Comment by thaJeztah** [comment]
let me close this one for now; I don't think there's plans on enhancing the legacy `/etc/hosts` based linking (which provided the env-vars); see https://github.com/moby/moby/issues/22295
