### ISSUE TITLE
From inspect back to run

### ISSUE THREAD

**Issue by efrecon** [moby/moby#24041]
[This gist](https://gist.github.com/efrecon/8ce9c75d518b6eb863f667442d7bc679) provides a good (?) starting point at regenerating the `docker run` command that led to a container, based on the templating facilities of `docker inspect`. Extend it to fully support the complete set of command-line options for `docker run` could be a good way to improve the documentation of `docker inspect`.

To run the gist, save it to `run.tpl`, and run the following commands at the (bash) prompt:
    tpl=$(<run.tpl)
    docker inspect --format "$tpl" running_container_name

What do you think?

**Comment by thaJeztah** [comment]
Overall, we recommend using (for example) Docker Compose (https://github.com/docker/compose) or in future, the Docker Application Bundles; https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md to describe how to run your application, in stead of reverse-engineering the command-line options that were provided to run the container

**Comment by efrecon** [comment]
Yes, I understand and use Docker Compose a lot. But there are times when it's not enough. My use case was in completely automating the steps necessary to setup an OpenVPN server using [this](https://github.com/kylemanna/docker-openvpn) project. I've reached a point where I create the volume and the main container using Compose, but since there are (manual, but I am automating those) steps involved, I end up needing to recreate (not restart) the main OpenVPN container once those steps have been completed.

I don't think that I am the only user with this particular need. See for example [rekcod](https://github.com/nexdrew/rekcod) and [runlike](https://github.com/assaflavie/runlike), two projects trying to achieve the same thing, but using external tools instead.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
