### ISSUE TITLE
 With ICC false, communication stays open if the "parent" container is removed first

### ISSUE THREAD

**Issue by shishir-a412ed** [moby/moby#24043]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   83e6197
 Built:        Tue Jun 28 10:40:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   83e6197
 Built:        Tue Jun 28 10:40:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121929-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 725.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.6 GB
 Metadata Space Used: 1.524 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 23

**Steps to reproduce the issue:**
1. mkdir httpd-docker
2. cat > httpd-docker/Dockerfile <<EOF
FROM fedora
RUN yum -y install httpd && yum clean all
RUN echo "Test Server" > /var/www/html/index.html
EXPOSE 80
CMD [ "/usr/sbin/apachectl", "-D", "FOREGROUND" ]
EOF
3. docker build -t httpd-docker httpd-docker
4. In first terminal, docker run --rm -ti --name httpd1 httpd-docker
5. In second terminal, docker run --rm -ti --name httpd2 --link httpd1 httpd-docker
6. In third terminal, iptables-save | grep -i docker, see lines like

-A DOCKER -s 172.17.0.4/32 -d 172.17.0.3/32 -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -s 172.17.0.3/32 -d 172.17.0.4/32 -i docker0 -o docker0 -p tcp -m tcp --sport 80 -j ACCEPT
1. Press Ctrl-C in the first terminal.
2. After the docker client process ends, press Ctrl-C in the second terminal.
3. Run iptables-save | grep -i docker

**Describe the results you received:**
The records are still there.

**Describe the results you expected:**
The records are gone.

**Additional information you deem important (e.g. issue happens only occasionally):**

The steps so see the incorrectly allowed access:
1. In first terminal, docker run --rm -ti --name httpd1 httpd-docker 
2. In second terminal, docker run --rm -ti fedora curl 172.17.0.3

and see

Test Server

output instead of error, in spite of the fact that this new "client" container is not --link'ed to the container started in the first terminal.

**Comment by akerouanton** [comment]
The old links mechanism was deprecated a long time ago and is going to be removed in a few releases. As it seems this issue will never be fixed (if it still exists), let me close it.
