### ISSUE TITLE
How to 'docker rmi' or 'docker rm -v' etc. across Swarm cluster?

### ISSUE THREAD

**Issue by nathanleclaire** [moby/moby#24079]
If one ends up scheduling a lot of containers using `docker service` they are also likely to accumulate a lot of images on those nodes.  Imagine the case where a service has been updated 20+ times in a short timespan, plus the usual Docker disk space woes, and it's easy to see how users will start running out of disk space quickly.  How will the usual Docker disk cleanups work in this case?

Likewise, what about containers which run using volumes?  Will there be an equivalent `rm -v` to Docker's `rm -v`?  Otherwise, [volumes will stick around forever | data will be lost automatically].

Other Docker orchestrators have encountered this in various ways, e.g. here is a selection in a proposal from https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/disk-accounting.md:

> As of kubernetes v1.1 clusters become unusable over time due to the local disk becoming full. The kubelets on the node attempt to perform garbage collection of old containers and images, but that doesn’t prevent running pods from using up all the available disk space.

**Comment by thaJeztah** [comment]
I think this issue will become more relevant for Swarm mode; https://github.com/docker/docker/issues/22871, and plans are to work on that for 1.13

**Comment by nathanleclaire** [comment]
Oh man, will `docker system prune` ever work cluster-wide? That'd be awesome.

**Comment by thaJeztah** [comment]
It doesn't currently; I agree that that would be desirable, to prevent having to log in to each node to perform those actions. No idea how to integrate that into the way swarmkit works though

/cc @mlaventure @aluzzardi

**Comment by mlaventure** [comment]
Hum, that's indeed a good point, but I don't know how this can be integrated within swarmkit either, will let @aluzzardi answer that :)

**Comment by schmunk42** [comment]
For cleanup, we're running this against our `docker/swarm` since a while:

```
docker ps -a -f status=exited -q | xargs docker rm -fv

docker volume ls -q | xargs docker volume rm

# Filter broken on swarm, see https://github.com/docker/swarm/issues/1700 and https://github.com/docker/swarm/pull/2514
docker images -a | grep "none" | awk '{print $3}' | xargs docker rmi

docker network ls -q | xargs docker network rm
```

**Comment by thaJeztah** [comment]
@schmunk42 agreed, cleanup scripts can run on a _per node_ base (a cronjob doing the cleanup). Ideally, if would not be needed to set up such scripts on a node, but have SwarmKit manage that. Given that SwarmKit handles _state_ of tasks / containers, and not directly controls _daemon_ actions, it may require a different approach to trigger/control GC

**Comment by stevvooe** [comment]
I think we could do something that looks at the currently assigned task set and collects unused images. Most of this is hidden behind the `Prepare` call, so resources are hidden behind controller. Thus, this may be outside the scope of swarmkit.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
