### ISSUE TITLE
docker node accept/reject, promote/demote but no drain/pause/activate

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#24086]
```
  accept      Accept a node in the swarm
  reject      Reject a node from the swarm
  promote     Promote a node as manager in the swarm
  demote      Demote a node as manager in the swarm
```

Either we do everything through `node update` or we have commands for everything, but right now it's incosistent

/cc @dnephin @aanand @stevvooe

**Comment by dnephin** [comment]
Everything in `node update` has my vote.

**Comment by vdemeester** [comment]
Same for me (and for `service`), `node update (--accept|--reject|…)` seems good to me

**Comment by cpuguy83** [comment]
I'd go the other way here.... accept/reject/promote/demote are simple to understand.
One could make the case to get rid of promote/demote as they can be ambiguous, especially if we later have more than manager/worker (maybe storage nodes or something?)... but accept/reject to me are requirements.

`docker node update` is not simple and is a bit unintuitive in this case, IMO.

**Comment by LK4D4** [comment]
I'm with @cpuguy83 here.

**Comment by dnephin** [comment]
After more thought I can definitely see the argument for keeping only accept/reject. They are kind of like `create` and `rm` but for a workflow that requires authorization. They should continue to be relevant if we add more types of nodes.

**Comment by dnephin** [comment]
@aluzzardi  to make it consistent we could remove `--membership` flag from `update`. That way memership is managed with commands, and roles and availability are managed with update.

**Comment by aaronlehmann** [comment]
Agree with @cpuguy83 - I like exposing `drain`/`pause`/`activate` as verbs.

**Comment by aluzzardi** [comment]
@vdemeester It wouldn't be `update --accept`, it actually would be `--membership=accepted`. Same with promote: `--role=manager`. Update is a low-level plumbing command that lets you tweak the internals but it's not really user friendly

**Comment by vdemeester** [comment]
@aluzzardi hum I see, make sense to think as `update` low-level command and expose simpler one :angel:

**Comment by tiborvass** [comment]
@aluzzardi do you mind having this in a later release?

**Comment by tiborvass** [comment]
unpause instead of activate ?

**Comment by aaronlehmann** [comment]
> unpause instead of activate ?

I like this, but you can also `activate` a drained node, so I'm not sure it makes sense.

**Comment by vdemeester** [comment]
ping @thaJeztah @vieux what is the status here ?
Should we close as it is stale and there is no really any users asking for it ?

**Comment by thaJeztah** [comment]
Yes, let's close for now
