### ISSUE TITLE
[1.12-rc2] we'd better support Stack and Deploy in the server side

### ISSUE THREAD

**Issue by allencloud** [moby/moby#24102]
Hi,

Stack and deploy command now are experimental features in docker 1.12.

While currently, stack and deploy are concepts in the client side. We can only use DockerCLI to use both two. We can not use API to take advantage of both two. So both two are coupled with dockerCLI, not so open for users.

**We had better support Stack and Deploy in the server side**

It needs engine-api to add both two and implement code in engine side.

**Comment by cpuguy83** [comment]
I would put it a little nicer than that, but yes :)

**Comment by allencloud** [comment]
I think there is no need to support this. And the design should change a lot which I am not really on that. Closing this.
