### ISSUE TITLE
Support tasks that are constrained by other tasks in swarm

### ISSUE THREAD

**Issue by F21** [moby/moby#24115]
I am interested in running HDFS in HA mode on swarm.

A minimum HA configuration will need each component of HDFS running on different nodes like so:
- Node 1: Namenode (with ZKFC) and Journal node
- Node 2: Standby Namenode (with ZKFC) and Journalnode.
- Node 3: Journalnode
- Node 4: Datanode

For reliability, there should be at least 3 Datanodes, but the above is the bare minimum for an HA HDFS setup.

It would be nice if I can do the following when creating services:
- Affinity: I want Journalnode and Namenode containers to run on the same node, but there should be only 1 journal node per machine.
- Aversion: Datanodes should not run on nodes where a Namenode or journalnode is running.
- Global task with aversion: Datanodes should run on every single node in the swarm (subject to constraints), but should avoid nodes where Journalnodes and Namenodes are running, while giving priority to Journalnodes and Namenodes.

**Comment by mgoelzer** [comment]
Dup of #24113

**Comment by mgoelzer** [comment]
Oops, wrong issue.  nm

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
