### ISSUE TITLE
Impossible to bind mount registry certificates

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#24157]
Registry certificates have the format `<host>:<port>`. These cannot be bind mounted into a container, due to syntax limitations.

Here is a contrived example:

``` console
docker run -v $PWD/file:/localhost:5000 alpine -- echo /localhost:5000
docker: Error response from daemon: Invalid bind mount spec "/tmp/file:/localhost:5000": invalid mode: 5000.
See 'docker run --help'.
```

Similar to #8604, #22825

cc @tiborvass

**Comment by varunmved** [comment]
I apology for the level of noob of my response (second week using docker, first time trying to contribute to OSS), but I tried 
`docker run -v $PWD/file:/localhost --expose 5000 alpine -- echo /localhost:5000`

based on https://docs.docker.com/engine/userguide/networking/default_network/binding/ 

specifically 

"If you want containers to accept incoming connections, you will need to provide special options when invoking docker run. There are two approaches.

First, you can supply -P or --publish-all=true|false to docker run which is a blanket operation that identifies every port with an EXPOSE line in the image’s Dockerfile or --expose <port> commandline flag and maps it to a host port somewhere within an ephemeral port range. The docker port command then needs to be used to inspect created mapping. The ephemeral port range is configured by /proc/sys/net/ipv4/ip_local_port_range kernel parameter, typically ranging from 32768 to 61000."

**Comment by stevvooe** [comment]
@varunmved This is more about the insufficiencies `--volume` syntax, than anything else. It prevents one from ever mount to a path with a `:` in the file name, which is valid on linux.

Docker uses the hostname, which includes the port, as the file name of registry certificates. For example, the file name might be `/etc/docker/certs.d/localhost:5000` to specify the TLS certificate to trust on a remote registry. If one wanted to run docker in docker and bind mount certs, the `--volume` syntax would prevent. If any other projects use this syntax for filenames, they will be limited, as well.

**Comment by wcgcoder** [comment]
@stevvooe, I'm just running into this issue today and have yet to devise an elegant solutions. I'm trying to do the exact scenario you mention; my ca.crt is in a registry with port 5000, and I want to share it into a container. 🙄 

I guess I'm doing a symlink. 😿

**Comment by stevvooe** [comment]
@wcgcoder We are introducing the `--mount` syntax to deal with this issue. As a workaround, you can bind mount a directory with the certificates or use some sort of symlinking.

**Comment by stevvooe** [comment]
Unfortunately, for some reason, the `--mount` flag has been removed from `docker run`.

We'll have to reevaluate that decision, as it is very poorly considered.
