### ISSUE TITLE
In old mkimage-debootstrap.sh one could configure an apt-cache http_proxy, add it to new mkimage.sh

### ISSUE THREAD

**Issue by arthurzenika** [moby/moby#24178]
**Output of `docker version`:**

```

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.71 GiB
Name: siaf2
ID: E4H5:KOVN:WIPH:RLBB:TXUY:W42V:XCTL:E4WB:DZFW:ILDN:VKYD:AB3C
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Steps to reproduce the issue:**
1. /usr/share/docker-engine/contrib/mkimage.sh -t debian:jessie debootstrap --variant=minbase jessie

old version of that was : /usr/share/docker-engine/contrib/mkimage-debootstrap.sh -p proxy:3142 ...

The debootstrap can't use an http proxy (apt-cacher-ng in our case) 

**Describe the results you received:**

the image build fine but is slow and consumes a lot of bandwidth.

**Describe the results you expected:**

Being able to add a --proxy somewhere that is then fed to the debootstrap command in /usr/share/docker-engine/contrib/mkimage/debootstrap

**Comment by thaJeztah** [comment]
Looks like that feature was contributed in PR https://github.com/docker/docker/commit/bc8a1081b047f6ee4ebf0adb22695fe3c98425c6, perhaps you're interested in contributing that feature?

/cc @tianon

**Comment by thaJeztah** [comment]
@arthurlogilab I meant to say; if you know what changes are needed for the new debootstrap script, feel free to open a pull request

**Comment by tianon** [comment]
It was removed because it should not be necessary anymore -- something like this ought to do the trick:
```bash
sudo http_proxy='correct value here' ./mkimage.sh ...
```

or even `sudo -E`, which will simply preserve environment variables from your current session

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
