### ISSUE TITLE
Don't show transfer progress bar when not a tty

### ISSUE THREAD

**Issue by mcandre** [moby/moby#24188]
When the shell is not interactive, please hide transfer progress bars to reduce clutter.

**Comment by thaJeztah** [comment]
I seem to recall some enhancements were made to detect a TTY, but if not, there's now a `--quiet` option for both `docker pull` and `docker push` (for `push` it's currently in master only, not yet in a release; this was the PR implementing it: https://github.com/docker/cli/pull/2197)

Closing this one for now, but feel free to open an issue in the docker/cli repository if this is still an issue
