### ISSUE TITLE
Docker documentation missing for new Config and HostConfig fields in Docker Remote API

### ISSUE THREAD

**Issue by juanrhenals** [moby/moby#24180]
Looking through the [documentation](https://docs.docker.com/engine/reference/api/docker_remote_api/) for the Docker Remote API [v1.22](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/) and [v1.23](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/), I don’t see any mention of the following fields which were added to the [Config](https://github.com/docker/engine-api/blob/release/1.11/types/container/conf... ...) and [HostConfig](https://github.com/docker/engine-api/blob/release/1.11/types/container/host... ...) types in docker/engine-api from version [1.10](https://github.com/docker/engine-api/tree/release/1.10/types/container) to 1.11. 
- [ArgsEscaped - Config](https://github.com/docker/engine-api/blob/release/1.11/types/container/conf... ...) 
- [AutoRemove - HostConfig](https://github.com/docker/engine-api/blob/release/1.11/types/container/host... ...) 
- [Cgroup - HostConfig](https://github.com/docker/engine-api/blob/release/1.11/types/container/host... ...) 

I'd like to make a contribution, but I'm not sure how/if these fields are supported; I'd like to get someone to chime in on this. If the information is provided I can file the PR to update the docs.

**Comment by cpuguy83** [comment]
@juanrhenals autoremove and args escaped are not being used by Docker yet.

**Comment by bsousaa** [comment]
This as been addressed and is now documented at https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerInspect
