### ISSUE TITLE
Windows Docker build Version  1.12.0-rc2-beta17

### ISSUE THREAD

**Issue by theCompanyDream** [moby/moby#24223]
**1.12.0-rc2-beta17**
DockerFile

```
FROM php:latest

# install the PHP extensions we need
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip

WORKDIR /var/www/html

# https://www.drupal.org/node/3060/release
ENV DRUPAL_VERSION 8.1.3
ENV DRUPAL_MD5 965ab5fe5457625ec8c18e5c1c455008

RUN curl -fSL "http://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERSION}.tar.gz" -o drupal.tar.gz \
    && echo "${DRUPAL_MD5} *drupal.tar.gz" | md5sum -c - \
    && tar -xz --strip-components=1 -f drupal.tar.gz \
    && rm drupal.tar.gz


```

**Output of `docker info`:**

```
Sending build context to Docker daemon 65.53 MB
Step 1 : FROM php:latest
Pulling repository docker.io/library/php
Error while pulling image: Get https://index.docker.io/v1/repositories/library/php/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:44826->[::1]:53: read: connection refused
```

**Hypervisor: HyperV**

**Steps to reproduce the issue:**
1. go to dockerfile 
2. type command: docker build -t myimage .

**I've tried pulling a different image, declaring the virtual machine I'm going to be using docker-machine env vmname, running as admin, and disabling the firewall.this message still persists for some reason**

*_I expected docker to pull the image and finish building it for me *_

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by samoht** [comment]
Probably in IPv6 issue:
```
Error while pulling image: Get https://index.docker.io/v1/repositories/library/php/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:44826->[::1]:53: read: connection refused
```

I am not sure which level of support we have for ipv6 on Docker for Windows.

**Comment by dgageot** [comment]
@theCompanyDream can you try setting a custom DNS server in docker for Windows GUI? Something like `8.8.8.8`

**Comment by aharpervc** [comment]
possibly related: https://github.com/docker/docker/issues/22398
