### ISSUE TITLE
removal of containers often fails

### ISSUE THREAD

**Issue by arnisoph** [moby/moby#24232]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 149
 Running: 45
 Paused: 0
 Stopped: 104
Images: 893
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1175
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.71 GiB
Name: <HOSTNAME>
ID: XURX:5IIX:KGPN:JZ5D:EJ5K:343Q:XTOP:OOYN:7FZD:ZLS3:S4W7:QUA3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Steps to reproduce the issue:**
1. Create _a_ container
2. Copy files into the container using `docker cp`
3. Execute commands using `docker exec`
4. Force-Remove the container using `docker rm -f <container_id>`
5. Fail Hard
(all steps are done sequentially, no parallel magic here)

**Describe the results you received:**
`docker rm -f` fails with the following message:

```
Error response from daemon: Unable to remove filesystem for a3368cdfdf25e91bb9d734b79a451e23cae421ca0d57da345117906d26b19b46: remove /var/lib/docker/containers/a3368cdfdf25e91bb9d734b79a451e23cae421ca0d57da345117906d26b19b46/shm: device or resource busy
```

**Additional information you deem important (e.g. issue happens only occasionally):**
That command fails on more than 6 identical hosts veeery often.

**Comment by cpuguy83** [comment]
I want to say we fixed this with `docker cp`, it might be in 1.11.2, but may not be in until 1.12. Let me see if I can find the PR.

**Comment by cpuguy83** [comment]
Ok, yeah fixes are only in 1.12
Would you be able to test with the 1.12 RC?

**Comment by bechtoldt** [comment]
@cpuguy83 you think this issue is related to ``docker cp``?

**Comment by cpuguy83** [comment]
@bechtoldt Based on your usage yes, but it's a combination of things.
Basically mounts leaking from the container during `cp` (or potentially other things) causing the busy error.

**Comment by thaJeztah** [comment]
@bechtoldt would you be able to test if 1.12 resolves this for you?

**Comment by bechtoldt** [comment]
@thaJeztah yeah I will give it a try

**Comment by harobed** [comment]
> @bechtoldt would you be able to test if 1.12 resolves this for you?

Always issue with 1.12

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I haven't seen issues with this for a long time.
