### ISSUE TITLE
Watch status change for services in docker ls

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#24258]
`docker service ls` can be improved by adding a watch flag. This will update the output of services as replicas are scaled up or down. This will simplify the interaction where the user will not have refresh the output.

**Comment by thaJeztah** [comment]
How about `watch docker service ls`?

**Comment by arun-gupta** [comment]
Is `watch` a standard Mac or Linux command? I could not find it on OSX.

**Comment by thaJeztah** [comment]
Hm, I think its standard http://linux.die.net/man/1/watch, not sure about on OS X, but should be available through Homebrew https://github.com/Homebrew/homebrew-core/blob/e47584620498e0fa1cac90957c0a5c84521d054f/Formula/watch.rb

**Comment by arun-gupta** [comment]
That can work but it would not know about state change within Docker. I think a global switch that monitors the state change within Docker and display only when necessary would be useful.

**Comment by thaJeztah** [comment]
Yes, perhaps it's worth considering, not sure if that'll make it in 1.12

/cc @stevvooe

**Comment by dnephin** [comment]
This would need #23827

**Comment by thaJeztah** [comment]
I'm adding this to the 1.12 milestone; it's a "nice to have", I don't think it's a show-stopper for 1.12

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
