### ISSUE TITLE
Distributed Application Bundle name

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#24250]
https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md explains that the generated bundle will contain an `Image` tag. This will point to a Docker image.

Is there a plan to support other image formats?

If not, I think the word `Distributed` is redundant and the new name should instead be `Docker Application Bundle`.

**Comment by thaJeztah** [comment]
ping @mgoelzer @aanand PTAL

**Comment by robbyoconnor** [comment]
:eyes:

**Comment by mgoelzer** [comment]
@arun-gupta What other image format are you referring to?  ACI?

Btw, just a note that the bundle format (including the name) is experimental in 1.12, which means it could change significantly.  We're aiming to get it to GA for Docker 1.13.  So, now is a good time to discuss issues related to the format.

**Comment by arun-gupta** [comment]
If Docker image is the only format, then may be `Docker Application Bundle` is a more appropriate name. 

Alternatively, Rkt, VM or some other format may be specified. This will blend well with "batteries include but replaceable" philosophy.

**Comment by funkydorian** [comment]
Is there an obstacle against the other formats, like Rkt, to be supported? If not, dab name can remain and the one who is interested to implement Rkt in the future is welcome...

**Comment by Mansarde** [comment]
I wouldn't say it's an incorrect name-choice, because the "distributed" part refers to the "application".
I.e. the application is something that can be distributed.

Whatever container format you can or can not use at the moment, the application is still distributable using the bundle, so I see no fault with the name.

**Comment by thaJeztah** [comment]
w.r.t. supporting different image formats; there are currently no plans to add those, but the feature is still "experimental" and likely the format may change, features added/removed. Feature requests and feedback welcome!

**Comment by AkihiroSuda** [comment]
DAB support was removed in https://github.com/docker/cli/pull/2216 .

https://github.com/docker/app is the successor.
