### ISSUE TITLE
docker-engine_1.11.2-0~trusty_amd64.deb susceptible to root PATH changes

### ISSUE THREAD

**Issue by anacrolix** [moby/moby#24405]
Attempting to # apt-get -V dist-upgrade

```
Preparing to unpack .../docker-engine_1.11.2-0~trusty_amd64.deb ...
/anacrolix/anacrolix/bin/stop: line 3: cd: docker: No such file or directory
invoke-rc.d: initscript docker, action "stop" failed.
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
/anacrolix/anacrolix/bin/stop: line 3: cd: docker: No such file or directory
invoke-rc.d: initscript docker, action "stop" failed.
dpkg: error processing archive /var/cache/apt/archives/docker-engine_1.11.2-0~trusty_amd64.deb (--unpack):
 subprocess new pre-removal script returned error exit status 1
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/docker-engine_1.11.2-0~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I have an alternative `stop` executable in my root user's PATH, and the installation scripts are trying to use it, instead of the system default.

`# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games apt-get -V dist-upgrade` works around it.

I expect the service utilities used by the docker package scripts should use absolute paths or clobber PATH prior to beginning.

**Comment by thaJeztah** [comment]
ping @tianon @kencochrane PTAL

**Comment by kencochrane** [comment]
@anacrolix have you seen this with any other package installs before, or is docker the first one?

**Comment by anacrolix** [comment]
Docker is the first one. I wasn't able to track down the repository for the deb file to check how you're doing things, but I'd hazard to guess that "stop", and other service-related commands aren't be used with absolute paths. I think this is standard in Debian scripts.

**Comment by thaJeztah** [comment]
@anacrolix scripts used to build the debs can be found here; https://github.com/docker/docker/blob/master/hack/make/build-deb, and here; https://github.com/docker/docker/tree/master/hack/make/.build-deb

**Comment by thaJeztah** [comment]
And sysvinit/upstart scripts can be found here; https://github.com/docker/docker/tree/master/contrib/init

**Comment by tianon** [comment]
IIRC, we're not doing anything abnormal here -- just letting `debhelper` insert the necessary bits for `postinst` (https://github.com/docker/docker/blob/8a0acaa5126ff0afd4588ffa76dd31e325ac359c/hack/make/.build-deb/docker-engine.postinst#L20 and https://github.com/docker/docker/blob/8a0acaa5126ff0afd4588ffa76dd31e325ac359c/hack/make/.build-deb/rules#L36)

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
