### ISSUE TITLE
Multiple Inheritance of Docker Images

### ISSUE THREAD

**Issue by HariSekhon** [moby/moby#24445]
Feature Request to support multiple inheritance in Docker.

I have a scenario where I have several projects, each with their own docker image and I have larger images containing more than one project but which require re-building each one again as I can't inherit from multiple images, even though the end state contents are the same as the single project images. This is very wasteful of space, bandwidth and builds.

It's a massively useful feature to be able to inherit from multiple existing docker images using `FROM` - it would save build time, bandwidth and storage to be able to re-use the image layers.

Since docker images are just filesystem layers conflict resolution could be as simple as default last write wins (ie. last FROM line wins) with configurability for first write wins or specific image layer wins or possibly an optional number priority suffix to the `FROM` line to maintain backwards compatability.

**Comment by phemmer** [comment]
See #13026

**Comment by HariSekhon** [comment]
@phemmer I already saw that ticket.

I still want multiple inheritance support as a first class citizen, it will significantly improve efficiency all round.

**Comment by thaJeztah** [comment]
There's been some other discussions on this, for example, on https://github.com/docker/docker/issues/3378, and https://github.com/docker/docker/issues/735. I don't see us implement this easily, as this will introduce a lot of complexity; what would the end result be of:

```
FROM centos:6
FROM ubuntu:16.04
FROM nginx
```

**Comment by HariSekhon** [comment]
See last paragraph of my opening post - last write wins default or configurable to first write wins or specific image layer wins or priority suffix - any of these options (preferably configurable) would result in a deterministic result.

**Comment by nholthaus** [comment]
@thaJeztah I don't think this has to be as difficult as you think it does, if you force certain limitations. Namely, that the container made from the `FROM` statements form an a-cyclical tree, which can be verified with an O(N) algorithm, where N is the number of `FROM`'s. Then you use @HariSekhon 's suggestion for direct conflict resolution.

Require the root of the tree to be `FROM: scratch`, which will prevent the most glaring problems.

**Comment by nholthaus** [comment]
@thaJeztah I don't think this has to be as difficult as you think it does, if you force certain limitations. Namely, that the container made from the FROM statements form an a-cyclical tree. Require the root of the tree to be `FROM: scratch`, which will prevent the most glaring problems. Then you use @HariSekhon 's suggestion for direct conflict resolution.

**Comment by toddwildey** [comment]
@thaJeztah Just require that the root of all images FROM-ed be the same image.  I don't think that's unreasonable?  This would be a *very* useful feature to have.

**Comment by xenoterracide** [comment]
Hmm... I' not sure I do agree that having multiple FROM's is a bad idea, but if it works (and I didn't know it existed until finding this, so I haven't tried it) it should work as a flattened composition (https://en.wikipedia.org/wiki/Trait_(computer_programming)). Perhaps though an alternate syntax `FROM alpine:latest WITH java-alpine:latest, ruby-alpine:latest`where foo acts like inheritance and is a base image like alpine, or ubuntu, but you could have some way to define bar, and baz, like java and ruby, so that you could easily compose languages (or other applications) into a single image.

Food for thought.

**Comment by pawelprazak** [comment]
Personally I would be more interested in a `MIXIN` feature where you could 'merge-in' additional layers, e.g:

- create a Cassandra datastore image
- create an image from `scratch` with only a backup script
- create an image from `scratch` with only a migration script
- combine the above by 'mixing-in' the additional scripts to the base image

That would make it easier to have separate lifecycles and test pipelines.

**Comment by AkihiroSuda** [comment]
Multi-stage Dockerfile (introduced in 17.05) should have covered use cases.
