### ISSUE TITLE
Impossible to extend ENV variables

### ISSUE THREAD

**Issue by riuvshin** [moby/moby#24441]
**Output of `docker version`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 152
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 339
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-64-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37 GiB
Name: ROMANSHORSE
ID: 7IB3:FHFQ:FQ5P:PDSY:E2EU:HLCE:NBCP:KPVF:XVIU:D5W5:3KAD:GRBM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: riuvshin
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Output of `docker info`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 152
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 339
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-64-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37 GiB
Name: ROMANSHORSE
ID: 7IB3:FHFQ:FQ5P:PDSY:E2EU:HLCE:NBCP:KPVF:XVIU:D5W5:3KAD:GRBM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: riuvshin
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

I have some basic `JAVA_OPTS` env var defined in bashrc in a container but in some cases I need to provide additional parameters like proxy, so im trying to extend `JAVA_OPTS` env variable in my container but due to some reason it appear in not valid state.

**Steps to reproduce the issue:**
1. run container like this: `docker run -e 'JAVA_OPTS=${JAVA_OPTS} -Dhttp.proxyHost=proxy.com -Dhttp.proxyPort=7777' -it roman/ubuntu_jdk8 bash`
2. check env variables inside of a container: `export | grep JAVA`

**Describe the results you received:**
Here is what I've received: `JAVA_OPTS="\${JAVA_OPTS} -Dhttp.proxyHost=proxy.com -Dhttp.proxyPort=7777"``

**Describe the results you expected:**
Here is what I've expected: `JAVA_OPTS="-Xms512m -Xmx1024m -server -XX:+HeapDumpOnOutOfMemoryError -Dhttp.proxyHost=proxy.com -Dhttp.proxyPort=7777"`

**Additional information you deem important (e.g. issue happens only occasionally):**
Due to some reason docker escape any dollar `$` symbol in ENV variabes

**Comment by justincormack** [comment]
Variables are not expanded by the shell inside single quotes ie `'JAVA_OPTS=${JAVA_OPTS}'` just means that literally, you need to put it in doubles quotes for expansion ie `"JAVA_OPTS=${JAVA_OPTS}"`

**Comment by duglin** [comment]
I think they're looking for Docker to do the env var expansion within the container prior to running the cmd - similar to how we do it for ENV in Dockerfiles.  Still ponding the idea...

**Comment by duglin** [comment]
I think my biggest initial worry with an idea like this is the possible confusion as to where the expansion will happen and the amount of effort people will have to go through to avoid it - meaning the amount of escaping (or double-escaping) because things will be env-var expanded twice (sort of).

**Comment by riuvshin** [comment]
@justincormack  
I want expand that var inside of a container, in case of double quoting that, it will be resolved on my host instead of docker container.

**Comment by justincormack** [comment]
Ah I see. I am really not sure that is a good idea.

You can do something like `docker run image sh -c 'JAVA_OPTS="$JAVA_OPTS ..." bash'` though.

**Comment by riuvshin** [comment]
@justincormack  Well actuallty I'm doing that not using CLI I have to do that via API, but to me it looks like a bug.

**Comment by justincormack** [comment]
In the API it is definitely not a bug - it is intended that these values are passed straight to the environment on the `execve` call and are not interpreted in any way. This is what the underlying Unix interface looks like, so it is not going to change I don't think. You can still pass the `sh -c ...` through in the API though as the command to run.

**Comment by garagatyi** [comment]
In that case we can't change CMD or ENTRYPOINT of container. We just want to add java options that tell java app that it is behind the proxy.

**Comment by justincormack** [comment]
And you can't modify the application to set the proxy itself from a different environment variable?

I don't see any way in which what you are asking for could be implemented, unfortunately, not sure if anyone else can think of one.

**Comment by duglin** [comment]
I think its possible to do - just have Docker use the same env substitution code on the -e vars/values (grabbing the current values from the image's metadata) like we during a build.  I'm just not sure if we should yet or not....

**Comment by justincormack** [comment]
@duglin oh I see get docker to do it before it passes the values to `runc`. Hmm. Yeah I am not sure either.

**Comment by duglin** [comment]
@justincormack yea, when I think of it as a "late-binding `ENV`" then it doesn't seem so bad - still pondering....

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
