### ISSUE TITLE
Containers not restarting

### ISSUE THREAD

**Issue by jacobtomlinson** [moby/moby#24529]
**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe/1.11.1
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-1441793-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.774 GB
 Data Space Total: 107.4 GB
 Data Space Available: 49.85 GB
 Metadata Space Used: 4.465 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.14-24.50.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.8 GiB
Name: ip-172-31-0-229
ID: HGF5:UHNN:PQ3C:5Y4X:UB54:5RXP:5YEX:HWMO:G4AU:UP3T:UZSY:OBYQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. Create a container which sleeps for between 5s and 120s and then exits
2. Start the container with `restart=always`
3. Wait

**Describe the results you received:**
The container eventually stops restarting and ends up showing the following in `docker ps`.

```
d4b50884b6b2        my-image:latest   "./run.sh"   56 minutes ago      Restarting (1) 27 minutes ago
```

**Describe the results you expected:**
Expected the container to restart always.

**Comment by thaJeztah** [comment]
The "restarting" status indicates that Docker is waiting for the next attempt to start the container. A container isn't considered "started" if it doesn't stay "up" for less than 10 seconds. Each restart, the time between restarts is increased exponentially, so if the container didn't run for 10 seconds, the time before the next start is increased (100ms, 200ms, 400ms).

If you inspect the container, can you see that the restart count is incremented?

**Comment by jacobtomlinson** [comment]
Thanks for the response @thaJeztah.

I may be missing something but I can't find a "restart count" or similar metric in `docker inspect <container id>`.

That being said I think I can answer your question anyway. It seems the majority of the time the container lives for <10s. Which follows with what you are saying about an increasing delay.

I can think of a solution, to add a sleep to the container code before it exits, however that does seem a little hacky. Do you have any suggestions?

**Comment by jacobtomlinson** [comment]
Also a further problem is once a container is in a `Restarting` state it cannot be stopped, removed or killed.

**Comment by thaJeztah** [comment]
Do you have a host to test on, and would you be able to test if that is still an issue in docker 1.12? I think some changes were made in that area, but not sure if those are resolving that (e.g. see https://github.com/docker/docker/pull/21854, and https://github.com/docker/docker/pull/21879)

**Comment by thaJeztah** [comment]
@jacobtomlinson is this still an issue for you on 1.12?

**Comment by jacobtomlinson** [comment]
I am able to stop containers that are in a `Restarting` state, but if I run `docker restart` on them it has no effect.

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now

**Comment by jacobtomlinson** [comment]
Wow Docker `1.11`. Those were the days 😆. 

Thanks for all your efforts here @thaJeztah.
