### ISSUE TITLE
Bug: Docker load with no params on Windows 10

### ISSUE THREAD

**Issue by pcgeek86** [moby/moby#24540]
I'm getting a bug running `docker load` without any parameters on Windows 10. Looks like this should be a fairly easy one to resolve. If the user doesn't specify any parameters, then show the `--help` for `docker load`.

![image](https://cloud.githubusercontent.com/assets/466713/16773407/189ef2d4-4815-11e6-9daa-3c726639f45a.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by thaJeztah** [comment]
Possibly the same as;

- https://github.com/docker/for-win/issues/9770
- which was fixed by https://github.com/Azure/go-ansiterm/pull/31
- and https://github.com/Azure/go-ansiterm/pull/32


(not 100% sure though)

**Comment by thaJeztah** [comment]
A colleague with access to a Windows machine was able to verify; looks like this works as expected now;

```powershelgl
PS C:\> docker load
requested load from stdin, but stdin is empty
```
