### ISSUE TITLE
[1.12.0-rc3] Swarm mode is incompatible with "--cluster-store" config so calico network will not work

### ISSUE THREAD

**Issue by gwanii** [moby/moby#24569]
**Output of `docker version`:**

```
Docker version 1.12.0-rc3, build 91e29e8, experimental
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:0-852-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop4
 Metadata file: /dev/loop5
 Data Space Used: 1.572 GB
 Data Space Total: 107.4 GB
 Data Space Available: 33.38 GB
 Metadata Space Used: 2.65 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay calico bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993 MiB
Name: node-01
ID: UMYR:CRAN:APVZ:QPZD:YQMY:WJT6:377C:NBJC:RDAF:2KUM:W54X:IXP2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Cluster Store: etcd://localhost:2379
Cluster Advertise: 192.168.1.55:2376
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

1.Run docker: 

```
[root@node-01 ]# /usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --cluster-store etcd://localhost:2379 --cluster-advertise 192.168.1.55:2376
```

2.Init swarm manager

```
[root@node-01 ]# docker swarm init
```

**Describe the results you received:**

```
[root@node-01 ]# docker swarm init
Error response from daemon: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode
```

**Describe the results you expected:**

```
I excepted to use calico network(plugin mode) with new swarm feature in docker 1.12, 
but from the received result above, I know that "--cluster-store" and "--cluster-advertise"
is incompatible with swarm mode.  
ps. To use calico network with docker,  "--cluster-store" and "--cluster-advertise"  
are necessary to set when run [docker](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/ManualSetup.md#docker).
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
This is a known issue, network plugins will not work in swarm mode in 1.12, I believe this will be fixed for 1.13. They will still work in the default non-swarm mode.

**Comment by gwanii** [comment]
@justincormack thanks, waiting for 1.13 :)

**Comment by rade** [comment]
> network plugins will not work in swarm mode

correction: *global* mode network plugins will not work in swarm mode. local mode network plugins do.

**Comment by jiaoge** [comment]
i want use calico in v1.12.1 。
when i can？

**Comment by cpuguy83** [comment]
@jiaoge docker 1.12 is fully backwards compatible with previous Docker releases.
You can use Calico just as you (may) have always used it.

It is not supported only with swarm-mode enabled.

**Comment by jiaoge** [comment]
@cpuguy83 
i know ,but i want use in  swarm-mode

**Comment by JamieCressey** [comment]
+1 for Swarm mode

**Comment by wrotki** [comment]
Just tried it with docker 1.13 RC1 - same error:

$docker version
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
$ docker swarm init --advertise-addr eth0 --listen-addr  eth0
Error response from daemon: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode

**Comment by jolly2** [comment]
Trying to use OpenVSwitch/OVN with docker swarm with docker 1.14.0-dev version. When tried to  swarm init , getting the following error 
ERRO[0159] Handler for POST /v1.25/swarm/init returned error: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode.
OVS/OVN works fine with docker engine - non-swarm mode. Want to use OVN network plugin.
Is there any config missing?

**Comment by cirocosta** [comment]
Where can we find the work being done to get this into 1.13? Just so it can be better tracked by the issue.

Thx!

**Comment by mavenugo** [comment]
@cirocosta @jolly2 @wrotki @jiaoge @gwanii 1.13 supports network plugins with swarm-mode. Once Calico network plugin is implemented as global-scoped, it will work with `docker service`.
btw, swarm-mode must be first enabled using `docker swarm init`

**Comment by jolly2** [comment]
With swarm mode enabled ( with swarm init ) , ovn does not work .  It throws unsupported in swarm mode error. This is as of docker 1.14-dev version.
Thanks!

**Comment by mavenugo** [comment]
@jolly2 we should bring this up with OVN developers and make sure the plugin is made compatible for swarm-mode.

**Comment by jonathan-kosgei** [comment]
@mavenugo Hi, I  just tried using calico as the network driver in swarm mode and got the same error

```
"Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode"
```
with :

```
root@sc-swarm:~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mavenugo** [comment]
@jonathan-kosgei Calico might require a KV store for its own purpose. But docker swarm-mode doesnt need one. Also in order to work in swarm-mode, the calico plugin must be implemented as a managed plugin. For example the weave team has implemented a proper swarm-mode plugin using managed plugin `docker plugin install bboreham/weave2`. We must raise it in the Calico project to make it swarm-mode compatible.

**Comment by lucas1993ch** [comment]
so,for now ,we can't upgrade the docker while keeping the containers running in swarm mode.
Looking forward the built-in function to realize it in swarm mode just like it does in live-restore with non swarm mode.
We can see things in the docs pages:

Live restore and swarm mode
The live restore option is not compatible with Docker Engine swarm mode. When the Docker Engine runs in swarm mode, the orchestration feature manages tasks and keeps containers running according to a service specification.

anyone have any good idea to solve this?

**Comment by vanquangthanhhao** [comment]
Please remove "docker.pid" and "docker.sock" at /var/run. Next, restart your host-machine and restart service docker by "sudo service docker restart"

Good luck to you !!!

**Comment by thaJeztah** [comment]
closing this issue, as this is something to be addressed by the plugin developer
