### ISSUE TITLE
docker run has no output in dind via exposed port

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#24575]
**Steps to reproduce the issue:**
1. Start dind `docker run --privileged --name dind -p 4000:4000 -d docker:1.12.0-rc3-dind --host tcp://0.0.0.0:4000`
2. Run `docker -H :4000 run  busybox echo 1`

**Describe the results you received:**

No output

**Describe the results you expected:**

`1`

**Additional information you deem important (e.g. issue happens only occasionally):**

These work: 

`docker -H :4000 run -i busybox echo 1`
`docker -H $(docker inspect -f '{{.NetworkSettings.Networks.bridge.IPAddress}}' dind):4000 run  busybox echo 1`

**Comment by thaJeztah** [comment]
@tonistiigi seems to work with the official image;

```
docker run --privileged --name some-docker -p 4000:2375 -d docker:1.12.0-rc3-dind
docker -H :4000 run busybox echo 1
1
```

**Comment by tonistiigi** [comment]
@thaJeztah Switching image doesn't fix it for me. Maybe the difference is that you are using docker4mac. I'll change the image in the description.

```
docker -H :4000 info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.12.0-rc3
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Kernel Version: 4.3.0-0.bpo.1-amd64
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.957 GiB
Name: 7d003ae77ff3
ID: JXR6:LCGC:MHNZ:ARMS:6RPW:7B5P:KBUE:AH3O:JB4P:TI7O:TRIP:ZJCV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by AkihiroSuda** [comment]
Should have been resolved?
