### ISSUE TITLE
No easy way to get stats for a service

### ISSUE THREAD

**Issue by beverts312** [moby/moby#24597]
In the old swarm, we could retrieve stats from any container via the swarm API.
In the new swarm mode, in order to get container stats, we would need to:  
1. ssh onto the node where the container is running  
2. then run a `docker stats <id>`  

Ideally we should be able to view the folowing from any manager:  
1. Aggregated stats for a service
2. Individual stats for a task in a service
3. Aggregated stats for a node

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
Thanks for opening!

**Comment by thaJeztah** [comment]
I don't think this is critical for the 1.12 release, but let me add it to the 1.13 milestone so that we don't forget taking a decision on this

**Comment by sam-thibault** [comment]
Per recent team discussion, the recommended approach is to use cadvisor or similar solutions and collect output in a tool like prometheus or similar.  We do not plan to implement an alternative approach for service stats.
