### ISSUE TITLE
Persistent deleted files in container

### ISSUE THREAD

**Issue by johnmarcou** [moby/moby#24611]
Hi all,

I have an unexpected behavior with Docker container when I delete a directory or file in a cascaded image.

Two image : imagea and imageb. The first one is based on centos, the second one is based on the first one.

In imagea, I "ADD files" via Dockerfile, then I "RUN rm" it. Those files are used only during the building process.
In imageb, I "ADD files" in a directory, which has **the same directory name than before**.

Then I start an imageb instance, and I delete the files in the directory, but they "re-appear".

To reproduce, please find the attached archive and run start.sh :
[Test.zip](https://github.com/docker/docker/files/362819/Test.zip)
# docker version

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
# docker info

Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 17
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.955 GiB
Name: asciengine
ID: PFXO:ZWNM:KU6R:74QO:WWEX:IOCJ:6A7M:NXIU:2UNN:WJ44:IC5O:FFTC
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by cpuguy83** [comment]
Can you provide exact steps, Dockerfiles, etc?

**Comment by johnmarcou** [comment]
Yes, everything is in the archive.

Structure :
a/Dockerfile
a/config/dir/OKA
b/Dockerfile
b/config/dir/OKB

Dockerfile for a:
FROM centos:7
ADD config /
RUN rm -Rf /dir

Dockerfile for b:
FROM imagea
ADD config /

Run building process :
docker build -t imagea a
docker build -t imageb b

Then, to check the issue:
docker run imageb bash -c 'ls /dir; rm -Rf /dir; ls /dir'

Or you can :
# docker run -it imageb bash
$ ls /dir
OKB
$ rm -Rf /dir
$ ls /dir
OKB

**Comment by AkihiroSuda** [comment]
I did not (yet) try to analyze this issue, but I think it is worth linking https://github.com/docker/docker/issues/24309 to this.

**Comment by thaJeztah** [comment]
Thanks @AkihiroSuda, I thought there was another issue indeed. Let us know when you had time to look into this and if it's indeed a duplicate

**Comment by justincormack** [comment]
Yes @AkihiroSuda that was my thought too, I think they are probably the same bug in aufs.

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
