### ISSUE TITLE
Permission denied when directory owner/mode changed in different layer on AUFS

### ISSUE THREAD

**Issue by csrwng** [moby/moby#24660]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 11
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: 4YNL:JTNE:RBTF:6FLS:K2NA:UG6R:4RKY:JJRN:V2OI:S3DD:VQ54:FI4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 31
 System Time: 2016-07-15T02:44:52.3596901Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: cewong
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac, Version 1.12.0-rc4-beta19 (build: 10258)

**Steps to reproduce the issue:**
1. Create an image with the following Dockerfile:

```
FROM ubuntu:14.04
RUN useradd test
RUN mkdir /var/lib/test && chown test:test /var/lib/test && chmod 700 /var/lib/test
RUN chgrp root /var/lib/test && chmod 770 /var/lib/test
```
1. Run with an arbitrary user id, group 0:

```
$ docker run -ti -u 10000:0 testimage
```
1. Attempt to write to /var/lib/test directory:

```
$ touch /var/lib/test/afile
```

**Describe the results you received:**
Permission is denied, even though the user's group has write access to the directory:

```
touch: cannot touch '/var/lib/test/afile': Permission denied
```

**Describe the results you expected:**
Creating the test file is allowed

**Additional information you deem important (e.g. issue happens only occasionally):**
If the mode/group is set within the same layer, then permissions work as expected:

```
FROM ubuntu:14.04
RUN useradd test
RUN mkdir /var/lib/test && chown test:test /var/lib/test && chmod 700 /var/lib/test && \
      chgrp root /var/lib/test && chmod 770 /var/lib/test
```

**Comment by csrwng** [comment]
Could be related to https://github.com/docker/docker/issues/24309

**Comment by AkihiroSuda** [comment]
Looks also related to https://github.com/docker/docker/issues/20240 (dupe?)

**Comment by thesteve0** [comment]
I encountered this on Windows 10 as well with a pre-existing directory. 

My workaround was to delete the directory, recreate the directory, and then change permissions:

Here is the Dockerfile I ended up with

FROM centos:centos7
MAINTAINER Steve Pousty <thesteve0@redhat.com>
RUN yum install -y --setopt=tsflags=nodocs httpd.x86_64 && yum clean all -y
# A custom httpd.conf that
# 1. binds to port 8080
# 2. sends all logs to stdout through log = "|more"
COPY conf/httpd.conf /etc/httpd/conf/httpd.conf
#Expose the port
EXPOSE 8080
# need to change some permissions to allow non-root user to start things
# had to do these steps to give the httpd deamon the ability to
RUN rm -rf /run/httpd && mkdir /run/httpd && chmod -R a+rwx /run/httpd
USER 1001
CMD /usr/sbin/apachectl -DFOREGROUND

Without the recreation steps Apache couldn't start bc it couldn't write the pid file to the directory.

Docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64


Docker Info

Containers: 34
 Running: 0
 Paused: 0
 Stopped: 34
Images: 19
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 98
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: SFGT:237X:J52Q:5H6W:U62T:YI5C:EM3X:AHFB:TBH2:JEHG:JRPJ:LR7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by anthony-o** [comment]
I think I'm having the same problem ([described here in stackoverflow](http://stackoverflow.com/q/40954245/535203)):

```
$ docker run -it --rm tomcat:8.5-alpine sh
/usr/local/tomcat # adduser -D -g '' -u 1000 user
/usr/local/tomcat # chown -R user:user $CATALINA_HOME
/usr/local/tomcat # su user -c 'catalina.sh run'
sh: catalina.sh: Permission denied

/usr/local/tomcat # echo $CATALINA_HOME
/usr/local/tomcat
/usr/local/tomcat # ls -la $CATALINA_HOME
total 128
drwxr-xr-x   20 user     user          4096 Dec  4 00:47 .
drwxr-xr-x   10 root     root          4096 Dec  4 00:47 ..
-rw-r-----    1 user     user         57092 Nov  3 21:16 LICENSE
-rw-r-----    1 user     user          1723 Nov  3 21:16 NOTICE
-rw-r-----    1 user     user          7063 Nov  3 21:16 RELEASE-NOTES
-rw-r-----    1 user     user         15946 Nov  3 21:16 RUNNING.txt
drwxr-x---    2 user     user          4096 Dec  4 00:47 bin
drwx------    2 user     user          4096 Dec  4 00:47 conf
drwxr-xr-x    4 user     user          4096 Dec  4 00:47 include
drwxr-x---    2 user     user          4096 Dec  4 00:47 lib
drwxr-x---    2 user     user          4096 Nov  3 21:14 logs
drwxr-xr-x    4 user     user          4096 Dec  4 00:47 native-jni-lib
drwxr-x---    2 user     user          4096 Dec  4 00:47 temp
drwxr-x---   12 user     user          4096 Dec  4 00:47 webapps
drwxr-x---    2 user     user          4096 Nov  3 21:14 work

/usr/local/tomcat # su user -c 'ls -la /usr/local/tomcat/bin'
ls: can't open '/usr/local/tomcat/bin': Permission denied
total 0

/usr/local/tomcat # su user -c 'ls -la /usr/local/tomcat/include'
total 12
drwxr-xr-x    4 user     user          4096 Dec  4 00:47 .
drwxr-xr-x   20 user     user          4096 Dec  4 00:47 ..
drwxr-xr-x    2 user     user          4096 Nov 17 23:45 apr-1
```

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
