### ISSUE TITLE
Error while starting docker: 'Failed to create Switch "DockerNAT": Element not found.'

### ISSUE THREAD

**Issue by ErwinSteffens** [moby/moby#24672]
When trying to start Docker for Windows it gives the error `Failed to create Switch "DockerNAT": Element not found.`

**Output of `docker version`:**

Could not generate this because the docker service does not start. 
Version is `1.12.0-rc4-beta19 (build: 5465) c84feba`

**Output of `docker info`:**

Could not generate this because the docker service does not start. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Windows 10 Pro - 10.0.10586 Build 10586

**Describe the results you received:**

Error dialog pops up with `An error occured` and showing details:

```
Failed to create Switch "DockerNAT": Element not found.

   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.<>c__DisplayClass28_0.<RestartVm>b__0()
   at Docker.Core.TaskQueue.<.ctor>b__16_0()
```

**Describe the results you expected:**

Docker services starts

**Additional information you deem important (e.g. issue happens only occasionally):**
- 'Reset to factory defaults...' does not resolve the issue
- Re-installing does not help

See log file:
[log-2016-07-15_09-24-21.txt](https://github.com/docker/docker/files/365464/log-2016-07-15_09-24-21.txt)

**Comment by dgageot** [comment]
Hi @ErwinSteffens, thank you for the bug report. Could you try reinstalling le latest (Beta20) version?

**Comment by maxrebar** [comment]
Just tried to install the latest version: same issue...

**Comment by CharlesSong** [comment]
Failed to create Switch "DockerNAT": Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled
   在 Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   在 Docker.Core.Backend.BackendClient.Start(Settings settings)
   在 Docker.Actions.<>c__DisplayClass26_0.<RestartVm>b__0()
   在 Docker.Core.TaskQueue.<.ctor>b__16_0()

**Comment by rickekins** [comment]
Same issue here, windows 10 pro.  Was restarting to install Hyper-V:
Failed to create Switch "DockerNAT": Hyper-V was unable to find a virtual switch with name "DockerNAT".
   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Core.TaskQueue.<.ctor>b__16_0()

**Comment by wmatsushita** [comment]
Same issue here, windows 10 pro. And even worse, going back to the Toolbox approach stopped working after this.
Failed to create Switch "DockerNAT": Hyper-V was unable to find a virtual switch with name "DockerNAT".
at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
at Docker.Core.Backend.BackendClient.Start(Settings settings)
at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
at Docker.Core.TaskQueue.<.ctor>b__16_0()

**Comment by goody** [comment]
Was having trouble mounting volumes(Win10 + Stable just installed) and 'Rest to Factory...":
Failed to create Switch "DockerNAT": Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Actions.<ResetToDefault>b__18_0()
   at Docker.Core.TaskQueue.<.ctor>b__16_0()

**Comment by dgageot** [comment]
Hi everyone, thank you for reporting this issue and sorry for the inconvenience.

Most of the time this issue comes from switching hyper-v support on and off while Docker for Windows is running.

Could you run this command **from an elevated powershell"**, then restart Docker and see if it fixes the issue?

```
$vmNetAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName DockerNAT
Get-NetAdapter "vEthernet (DockerNAT)" | ? { $_.DeviceID -ne $vmNetAdapter.DeviceID } | Disable-NetAdapter -Confirm:$False -PassThru | Rename-NetAdapter -NewName "OLD"
```

**Comment by maxrebar** [comment]
@dgageot:
Thanks a lot ! 
your fix is working and solved my problem.
Very cordially
Eric

**Comment by ErwinSteffens** [comment]
@dgageot:
Running v1.12.0-beta21 (build: 5971) 5b59d37 now, but this does not solve the problem.
Running the script above solves it and docker is running now.

When I view my network adapter list I see that all my virtual switch interfaces have multiple 'disabled' instances. No idea why this is happening. 

![image](https://cloud.githubusercontent.com/assets/6931114/17515465/d346592c-5e38-11e6-91a7-b115dfdc74f0.png)

**Comment by taylorsilva** [comment]
As an FYI.
I installed docker `1.12.0` on Windows 10 Pro Build 10586. Restarted windows to enable Hyper-v.
After reboot Docker tried starting and returned the above error.
I closed docker and ran it again with elevated permission (run as admin...) and it started successfully. Seems like it just needed elevated permissions to create the network adapter.

**Comment by NLKNguyen** [comment]
Version 1.12.0-stable (build: 5968)
PC has Docker Toolbox previously installed

I only had this problem at the first time Docker for Windows trying to start. After going to settings/reset and restart Docker, the problem is gone. Docker can start normally. No other actions had been taken.

**Comment by HitmanDeCoder** [comment]
Version 1.12.0 - stable
Windows 10 Enterprise .
    I also had same issue. As per @taylorsilva  It is working , when I start it with admin permission (Run as Admin) .

**Comment by thaJeztah** [comment]
Looks like this issue is quite old, and from the looks of it, resolved. So let me go ahead and close
