### ISSUE TITLE
Issue with dockerized Neovim in ConEmu

### ISSUE THREAD

**Issue by Tset-Noitamotua** [moby/moby#24681]
Tryed to use [Dockerized Neovim](https://hub.docker.com/r/fxdgear/alpine-neovim/) from within [ConEmu](http://conemu.github.io/) (console emulator on Windows) and had a bad experience with it. Check issue details below and see one possible solution in next comment. 

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: KZW4:LH6P:EVKJ:RKRO:6ZIK:INTQ:FZJW:GY5D:CGVS:D55V:O2MI:NC77
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 57
 System Time: 2016-07-15T11:14:08.219663228Z
 EventsListeners: 0
Http Proxy: XXX
Https Proxy: XXX
No Proxy: XXX
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Windows 7 64bit
- [ConEmu](http://conemu.github.io/)
- [Dockerized Neovim](https://hub.docker.com/r/fxdgear/alpine-neovim/)

**Steps to reproduce the issue:**
1. Do: `docker run -it --rm fxdgear/alpine-neovim:latest` in ConEmu (bash or cmd - does not matter).
2. Wonder why it looks like ***\* ;-/

**Describe the results you received:**

Result in ConEmu (cmd / bash - same appearance)
![image](https://cloud.githubusercontent.com/assets/5635462/16872803/9c2c13da-4a8f-11e6-8806-14c29556c7a9.png)

**Describe the results you expected:**

In comparison result from Windows` nativ cmd.exe:
![image](https://cloud.githubusercontent.com/assets/5635462/16872929/60ab45fa-4a90-11e6-801c-fe65cb02f2f7.png)

**Comment by Tset-Noitamotua** [comment]
One possible solution is (as by chance found in #13817 - dont know if they are related) is to run with

 `-e TERM`, e.g.:

```
docker run -e TERM -it --rm fxdgear/alpine-neovim:latest
```
Result:
![image](https://cloud.githubusercontent.com/assets/5635462/16873368/0ada4f4c-4a93-11e6-959d-93c1cd63e547.png)

**Comment by fxdgear** [comment]
it looks like ConEmu has some issues with rendering the glyphs as well... 

with `TERM=xterm256-color`

https://www.dropbox.com/s/uozhknxz2y8n1pt/screenshot_26ty7znp.png?dl=0

with `TERM=xterm`

https://www.dropbox.com/s/4y1dsc8q0m6yjht/screenshot_i30v2kr0.png?dl=0

**Comment by thaJeztah** [comment]
We've seen more issues reported recently with ConEmu, so I'm wondering if there's a bug in recent versions? https://github.com/docker/docker/issues/25476, https://github.com/docker/docker/issues/25475,
