### ISSUE TITLE
Any body know what is NanoCPUS in inspect node response and how is that value calculated? Thanks

### ISSUE THREAD

**Issue by cmingxu** [moby/moby#24713]

**Comment by yongtang** [comment]
@cmingxu Based on the calculation:
https://github.com/docker/docker/blob/v1.12.0-rc4/daemon/cluster/executor/container/container.go#L328-L332

Its seems that `NanoCPUs` is defined as the CPU shares in units of `1/1e9` (or `10^-9`) of the CPU. In other words, `NanoCPUs` is exactly `1 nano CPU`.

**Comment by lbguilherme** [comment]
This issue should be closed. This should be documented in https://docs.docker.com/engine/reference/commandline/service_create/#options (thus this issue is superseded by #30222)

**Comment by MoShaaban13** [comment]
> [@cmingxu](https://github.com/cmingxu) Based on the calculation: https://github.com/docker/docker/blob/v1.12.0-rc4/daemon/cluster/executor/container/container.go#L328-L332
> 
> ```
> resources.CPUQuota = r.Limits.NanoCPUs * resources.CPUPeriod / 1e9
> ```
> 
> , `NanoCPUs` is defined as the CPU shares in units of `1/1e9` (or `10^-9`) of the CPU.
> 
> In other words, `NanoCPUs` is the number of `nano (1/1e9) CPUs` by a process.

what if the CpuPeriod is 0 what will that mean ?
