### ISSUE TITLE
--network-alias option missing on docker service create (as well as corresponding options on docker service update)

### ISSUE THREAD

**Issue by Stehsegler** [moby/moby#24787]
docker/docker#23542 added support for network aliasing of services. Comment 2 in docker/libnetwork#1263 shows this feature in action, by providing the `--network-alias` option to `docker service create`. However, for all clients I checked, this just returns the error `unknown flag: --network-alias`. This also applies for `docker service update` (flags should probably be `--network-alias-add` and `--network-alias-rm` here).

Clients tested were:
- the one from the Docker-provided testing repo for CentOS (https://yum.dockerproject.org/repo/testing/centos/7/Packages/docker-engine-1.12.0-0.4.rc4.el7.centos.x86_64.rpm)
- the latest experimental build (https://experimental.docker.com/builds/Linux/x86_64/docker-latest.tgz - downloaded today)
- the binaries built from master (https://master.dockerproject.org/linux/amd64/docker-1.12.0-dev - downloaded today)

**Comment by thaJeztah** [comment]
Thanks for reporting! Services don't have all options that containers have; some options will be added, and other options may find their way in some other form (compared to `docker run`). More options will be added in the next release, so I'll add this to the 1.13 milestone for consideration

**Comment by mavenugo** [comment]
@Stehsegler you are correct. we added the support for API. But having it done in CLI is tricky because there is no clean way to add per-network alias. But we support  multiple networks per service. And we have to think of a better alternative to alias when it comes to services. Keeping it as 1.13 milestone is reasonable.

**Comment by Stehsegler** [comment]
Thank you @mavenugo for the explanation.

An option to tackle the problem of allowing different aliases for different networks - and at the same time improve consistency between the various CLI flags of `service create` - would be to take the same approach as with the `--mount` option (see comments 2 and 4 in docker/docker#24277), i.e. passing options as key-value pairs to `--network`. Instead of `--network net1 --network net2 --network-alias alias` you could then specify `--network net1,alias=alias1 --network net2,alias=alias2`.

**Comment by hvpareja** [comment]
Hi, I agree this suggestion is going to be a good improvement. It could be very useful to duplicate the same stack of services in different overlay networks. As the service name can't be duplicated this is not possible at the moment until we are able to force the name in network.

As I knew about the `--network-alias` argument I was going to use this feature for blue-green deployments. I felt disappointed when I realised this feature is gone.

I'll keep an eye on this milestone. Thanks!!

**Comment by kleptog** [comment]
I would like to add my vote for this issue. We're investigating swarm and were disappointed that the feature of linking was missed. It was very handy to be able to be able to reference other containers by  service name (there are different containers providing the same service on different networks).

I'd also like to suggest an alternate command line option format, it's not as flexible as the other suggestion, but perhaps fits better with the existing options, namely: --network-alias net1=alias1, and perhaps --network-alias alias for an alias over all networks.

Another possibility that might work even nicer: --name service.namespace, which would allow resolving both on "service" and "service.namespace".

**Comment by hvpareja** [comment]
@kleptog "" It was very handy to be able to be able to reference other containers by service name"" <- this is something you can do with swarm as soon as you declare the services in the same overlay network. No missing functionality but the opposite.

**Comment by hipposareevil** [comment]
@mavenugo  How do we add the network alias to a service via the API? I've looked through the docker-py docs and was unable to find a way to do this.

**Comment by kleptog** [comment]
@hvpareja note my comment right after: (there are different containers providing the same service on different networks)

Ok, so I should have written "overlay networks" there, but my point was if you have a testing and a staging environment which both have a database, they can't both be called "database", whereas with links that was possible. So now testing and staging cannot use the same configuration.

In other word, adding the --network-alias switch is a good idea.

**Comment by hvpareja** [comment]
@kleptog, oh right, sorry.

**Comment by PanJ** [comment]
Yeah I needed that namespacing stuffs also. Pointed out in https://github.com/docker/docker/issues/25369. Still not sure what the command line argument should look like in terms of consistency to the existing ones.

**Comment by kinghuang** [comment]
Was @hipposareevil's question ever answered? I'm also not sure how to add network alias via the API. Can someone point me in the right direction for this?

**Comment by hipposareevil** [comment]
@kinghuang  I haven't found an answer yet.

**Comment by Yogu** [comment]
@kinghuang @hipposareevil In theory, you can do it like so:

```
POST /services/create
{
    ...,
    networks: [
        {
            target: "network-name",
            aliases: [ "the-alias" ]
        }
    ]
}
```

However, this currently does not work for me - it shows the alias in `docker service inspect`, but not in `docker inspect` (inspecting the container).

**Comment by nordluf** [comment]
1.13 release is coming. Any news ?

**Comment by ldesi** [comment]
News???

**Comment by billryan** [comment]
This issue is similar to the closed issue #26247, since 1.13 introduced template support for hostname, mount and env while creating services(#28486), I think it's reasonable to add template support for this network-alias feature too.
This feature would ease Cluster HA setup(Spark/Elasticsearch/...), worker/slave nodes need the master node hostname/IP before setup.

**Comment by hamburml** [comment]
I just got here because @thaJeztah pointed me to this issue. I need network-aliases for a service which runs with `mode:global`. But the network-alias must support the usage of templates to give each running container a unique network-alias.

**Comment by fabio-barile** [comment]
Fully agree, net-alias should support templates . 👍

**Comment by sbrattla** [comment]
@mavenugo and @thaJeztah multiple people have asked about how one can use the API to assign DNS aliases to a service. I've looked through https://docs.docker.com/engine/api/v1.25/#tag/Service but can not find anything in the documentation which indicates that this is possible. Would you have the chance to guide us in the right direction?

**Comment by sbrattla** [comment]
Created a guide for how to create service with DNS aliases using the API on https://github.com/docker/docker/issues/30708

**Comment by cirocosta** [comment]
from https://github.com/docker/docker/issues/24787#issuecomment-277628072 it looks like it's only missing the `--network-alias` on the command line. Is this the case?

**Comment by sbrattla** [comment]
@cirocosta the aliases are network scoped; I believe the suggestion by @Stehsegler in his comment https://github.com/docker/docker/issues/24787#issuecomment-233853394 makes sense. That is, you must be able to define which network a given alias applies to.

However, declaring network aliases along with `--network` might be a somewhat tricky approach if you want to add or remove aliases later on. It could, be that allowing something like `--network-alias net1:alias2 net1:alias2` could be a way to go. In other words, keep declaration of aliases on its own.

**Comment by billryan** [comment]
If `--network-alias` can be used in `docker service update`, it would be better.
Currently I can only use this in service create API.

**Comment by Noodle05** [comment]
If this is already available in API but not CLI, can I use {{.Task.Slot}} as part of network alias? Some think like:

--network-alias zookeeper-{{.Task.Slot}}

But through API directly?

**Comment by fentas** [comment]
My use case is, that I have a haproxy reverse proxy and I need to route internal network traffic through this haproxy. To be able to this I need `--network-alias` or otherwise I have to touch all other containers and modify `hosts` which is not always possible. Another possibility would be to deploy a DNS service, which I would like to avoid.

**Comment by mustafaakin** [comment]
Would really love this since I normally use <name>.{{ .Task.Slot }} and would like to use them by domain name. Currenlt I use endpoint spec with dnsrr, and do a reverse lookup for the IP addreses, which is really not cool.

**Comment by EliSnow** [comment]
I believe this is accomplished through the undocumented csv network options (see #33130). The milestone for the referenced PR says 17.06, I haven't tested it on 17.06 but it definitely works with 17.09.

**Comment by nomoon** [comment]
I tried to do this as well using a compose file for `docker stack deploy` but no luck:

```
service:
  db:
    image: mariadb:10.2
    networks:
      cdli_nodelocal:
        aliases:
          - db_nodelocal
      swarm:
    deploy:
      mode: global
      endpoint_mode: dnsrr
networks:
  swarm:
    driver: overlay
  nodelocal:
    external: true
```

The only alias that appears on the `nodelocal` network via `docker inspect` is the container id.

**Comment by fduxiao** [comment]
Now I'm facing a problem that I need a mongo cluster which can be used with docker stack, and also, I need to start some other services according to demands (actually I'm starting a service for each client of my company which is built a docker image). These services will be run for a long time (a solid business relationship), but may also be removed (if they are no longer used). I've been struggling with the connect from my services to the mongo cluster in the stack. Now I have to use unix sockets since files can be located by mounting to filesystem. Could you add some mechanism to allow easy access from one container(or service or stack) to another (even if only network is enough)? I mean I'd like to have all my services communicate via network with there hostname(or alias I can specify as a static config I can tell my services without knowing the id of the container or something like that), so what should I do instead of unix socket(I don't want expose it to file system).

**Comment by trapier** [comment]
Issue with stacks was address at latest by 17.12 https://github.com/docker/cli/issues/744#issuecomment-351118283

As for `service create`:
> Long form syntax of --network allows to specify list of aliases and driver options:
--network name=my-network,alias=web1,driver-opt=field1=value1
https://docs.docker.com/engine/reference/commandline/service_create/#attach-a-service-to-an-existing-network---network

**Comment by thaJeztah** [comment]
Yes, looks like this one is resolved; the same syntax will be added for `docker run` through https://github.com/docker/cli/pull/1767
