### ISSUE TITLE
Use HTTP constant status codes names and not thier respective numbers

### ISSUE THREAD

**Issue by doronp** [moby/moby#24783]
Right:
`http.StatusInternalServerError`
Wrong:
`500`

This helps readability a lot IMHO

**Comment by doronp** [comment]
I'd leave it open until we are done. There are some more places in which we need to change
(This is why I did not not PR with fix #24784 which would auto close this)
Other wise it would just be open issue for each change like that.

**Comment by thaJeztah** [comment]
I'll reopen the issue; can you refer to this issue in follow ups? (e.g. relates to https://github.com/docker/docker/issues/24783 in the PR description)?

**Comment by bsousaa** [comment]
Closing this issue as it is done https://github.com/moby/moby/pull/24784
