### ISSUE TITLE
Chain DOCKER always resetted in iptables.

### ISSUE THREAD

**Issue by MagicMicky** [moby/moby#24848]
On my server, I want to configure the exposed ports of my containers to only be accessible for a few ip addresses. I want to make this restrictition using netfilter and iptables.

On the [documentation](https://docs.docker.com/v1.7/articles/networking/#communication-between-containers-and-the-wider-world) you say the following

> Docker will not delete or modify any pre-existing rules from the DOCKER filter chain. This allows the user to create in advance any rules required to further restrict access to the containers.

As far as I've tested everything, if I  precreate a DOCKER chain in my filter table, and add a rule (such as the negated rule given in example in your documentation), as soon as I restart the docker daemon, the rule is removed from the chain, and my rule is replaced with dockers' specific rules.

``` bash
service docker stop
#Reset your iptables
#...
iptables -N DOCKER
iptables -A DOCKER ! -s x.x.x.x -j DROP
iptables -L DOCKER
# Docker rule is added
# Now restart docker
service docker start
ps aux | grep docker
# docker started with '/usr/bin/docker daemon -H fd://'
iptables -L DOCKER
# Only container specific rules, my rule doesn't exist anymore
```

I can see either two mistakes. 
Either the documentation isn't uptodate, and Docker used to keep pre-existing rules, but doesn't anymore. Or Docker isn't keeping them as it should.
I'm using docker v1.11.2

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
ping @aboch ptal :smile:

**Comment by corverfuga** [comment]
Same problem here, we have custom IPtables rules on our INPUT chain to firewall application ports to out own IPs, DOCKER chain bypasses this, so I tried adding these rules to DOCKER chain, but this gets deleted/reseted with docker daemon restart.

I need a way to firewall my docker containers in the cloud. Please help.

~~~~
corver@testa:~$ sudo iptables -I DOCKER -p tcp --dport 80 -j ACCEPT
corver@testa:~$ sudo iptables -L DOCKER -n -v --line-numbers
Chain DOCKER (2 references)
num   pkts bytes target     prot opt in     out     source               destination
1        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80
corver@testa:~$ sudo service docker restart
docker stop/waiting
docker start/running, process 1938
corver@testa:~$ sudo iptables -L DOCKER -n -v --line-numbers
Chain DOCKER (2 references)
num   pkts bytes target     prot opt in     out     source               destination
corver@testa:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
~~~~

**Comment by rubycut** [comment]
👍  

This effectively doesn't allow any docker container firewall, which makes the whole thing look silly:

* you can't put rules in PREROUTING chain becuase nat table doesn't allow filtering
* if you put rules it in FORWARD chain, on docker restart, docker will INSERT his rules on TOP OF THE CHAIN, making any custom rules you added inactive
* if you put your rules to DOCKER chain, on restart, docker will flush this chain
* So, only option is to go with host networking, but then many advanced features don't work, such as new "docker create service" command option.

**Comment by rubycut** [comment]
Same problem is present in 1.12 which just got release few days, ago, so labels are not correct.

**Comment by thaJeztah** [comment]
@rubycut label is automatically applied based on the version an issue was reported with

**Comment by jcstover** [comment]
@rubycut: 
I had the same problem, but the solution is in the default iptables file. If the FORWARD rules are present in that default file, docker won't change these and you can add you filtering rules. In #23987 I've described the solution with an example iptables files. In this solution traffic to the bridges is first send to a chain called DOCKER-BLOCK in which you can filter the traffic. Since the rules of the bridges for docker are present, these will not be inserted before the rule to send traffic to de DOCKER-BLOCK chain.

**Comment by rubycut** [comment]
@jcstover,  docker always inserts it's rules on top of forward chain, that is the problem. Loading default rules from some file doesn't matter.

**Comment by jcstover** [comment]
True, but in the case the forward rules of the docker bridges are in place docker will not insert these at the top. Try the mentioned solution, since we have tested it and for us it is working. We faced the same problem, if the forward rules for the bridges are not in place docker will insert these at the top, that why we have them in the default rulesset of iptables.

**Comment by rubycut** [comment]
Yes, I am not exactly sure how packets are travelling, bot those 4 rules are inserted above my SALT chain, and I am afraid that some packets might escape, these rules include DOCKER-OVERLAY and DOCKER-ISOLATION chains, and there is quite a lot of traffic travelling without being checked.

```
1516K  169M DOCKER-OVERLAY  all  --  *      *       0.0.0.0/0            0.0.0.0/0
1505K  149M DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
57359 3962K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0
14592   61M SALT  all  --  eth0   *       0.0.0.0/0            0.0.0.0/0
1567K 6291M SALT  all  --  eth0   *       0.0.0.0/0            0.0.0.0/0           
  581 1104K DOCKER     all  --  *      br-6ecda70e063c  0.0.0.0/0            0.0.0.0/0
  330 1077K ACCEPT     all  --  *      br-6ecda70e063c  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 2544  166K ACCEPT     all  --  br-6ecda70e063c !br-6ecda70e063c  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-6ecda70e063c br-6ecda70e063c  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER     all  --  *      br-a82b3fade826  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      br-a82b3fade826  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  br-a82b3fade826 !br-a82b3fade826  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-a82b3fade826 br-a82b3fade826  0.0.0.0/0            0.0.0.0/0
3591K   14G DOCKER     all  --  *      br-f6aac37b6ed7  0.0.0.0/0            0.0.0.0/0
3591K   14G ACCEPT     all  --  *      br-f6aac37b6ed7  0.0.0.0/0            0.0.0.0/0
```

**Comment by jcstover** [comment]
If you saven the output of iptables-save to the iptables file and place the to rules with SALT just after de DOCKER-ISOLATION rule and the reload iptables then these rules will have the correct order. If then you restart docker the order of the rules should stay the same. I see in your output that other DOCKER rules are after the SALT rules. That indicates that docker leaves existing rules for bridge alone if they are present.

**Comment by rubycut** [comment]
Well, this needs to be documented somewhere, because I was afraid if I let DOCKER-ISOLATION and DOCKER-OVERLAY rules to stay at the top of the chain, then packets I want to block may slip through them before reaching SALT chain.

**Comment by delfuego** [comment]
@jstover I cannot figure out a single way to have any rule I put into the `FORWARD` chain stay at the top of the chain when the Docker daemon starts; at startup, every time, the Docker daemon re-inserts its own rules at the very top of the chain.

As a result, there's no way I can figure out to have my rules (related to blocking container port access) persist across a Docker daemon restart. If I put them into the `DOCKER` chain, that chain gets flushed entirely at the time of a daemon start. If I add a new chain and put a rule into the `FORWARD` chain directing Docker traffic to the new chain, then at daemon startup time, Docker re-inserts its own rules above my rule, allowing the traffic to the container before my block rules block it.

At a minimum, I've put in the above pull request to update the Docker docs, so that people don't believe that bit about rules in the `DOCKER` chain remaining untouched by Docker.

**Comment by ck-1** [comment]
With Docker v.17.06 there is a new iptables chain called DOCKER-USER. This one is for your custom rules, see my answer on serverfault: https://serverfault.com/questions/704643/steps-for-limiting-outside-connections-to-docker-container-with-iptables/886257#886257

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.

**Comment by vjt** [comment]
If you ended up on this issue like I did, maybe my super simple script may help you as well: https://github.com/vjt/docker-user-firewall

**Comment by akerouanton** [comment]
@vjt Did you try the new nftables backend? It removes a lot of the pain points you ran into. See https://docs.docker.com/engine/network/firewall-nftables/

**Comment by vjt** [comment]
Hey @akerouanton no, as I am running debian 13 that has docker 26. I'll try it once it reaches debian stable :). Thanks for the pointer!

**Comment by thaJeztah** [comment]
> I am running debian 13 that has docker 26. I'll try it once it reaches debian stable

Note that Debian won't update to newer versions of Docker for Debian 13 (trixie), as they always pick a major version, and won't update for a release, so newer versions of Docker won't be included until Debian 14 ("Forky") is released (likely sometimes August 2027).

Docker 26.x [reached EOL here in upstream](https://github.com/moby/moby/blob/docker-v29.2.1/project/BRANCHES-AND-TAGS.md#docker-engine-branches), so wont receive updates (but the Debian packagers may apply patches for critical security fixes).

In general, I highly recommend installing Docker's official packages, which will always provide the latest releases (installation instructions are here in the docs; https://docs.docker.com/engine/install/debian/ - make sure to uninstall the existing `docker.io` and its dependencies (`docker-cli`, `runc`, `containerd`) first).

But of course, if you're running in production, always test upgrades in a test environment first.
