### ISSUE TITLE
Activating routing mesh requires a wait period

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#24876]
When running `TestApiSwarmExposePort`  https://github.com/docker/docker/pull/24613/files#diff-248890d27a734b6320cc5296c4695f1dR102 integration test that tests routing mesh there are sleep calls after cluster creation and service creation. Removing these sleeps increase the chance of the test failing.

For creating cluster the test waits for all the nodes to reach ready status. For creating service the test waits for the containers to be running and only after that starts testing the networking features. But that doesn't seem to be enough and extra sleep calls are required for the test to pass.

@mavenugo

**Comment by tonistiigi** [comment]
Failed again in https://jenkins.dockerproject.org/job/Docker-PRs/30654/console

Daemon logs: https://gist.github.com/tonistiigi/af0d4bdea8f178e0bb7b9ff591886bb4#file-d5543370-log-L287 . If I understand this properly then seems that the tasks was never created/assigned. 

@mrjana

**Comment by akerouanton** [comment]
This issue went stale, so let me close it.
