### ISSUE TITLE
Daemon fails to start on Ubuntu 16.04 if DOCKER_OPTS includes -H tcp://172.17.0.1:2375 in /etc/default

### ISSUE THREAD

**Issue by Confusion** [moby/moby#24886]
I'm using the following `/etc/default/docker`:

```
DOCKER_OPTS="-H tcp://172.17.0.1:2375 -H unix:///var/run/docker.sock"
```

so some containers can spawn new containers.

This used to work fine, but since upgrading from Ubuntu 14.04 to 16.04, Docker 1.10.3, this causes the Docker daemon startup to fail with

```
Jul 21 09:49:03 photon docker[7548]: time="2016-07-21T09:49:03.734615702+02:00" level=fatal msg="listen tcp 172.17.0.1:2375: bind: cannot assign requested address"
```

This is because the `docker0` bridge does not yet exist. If I remove the `-H tcp://172.17.0.1:2375`, start docker, add `-H tcp://172.17.0.1:2375` and restart, everything is fine, because the first start succeeds and creates the `docker0` bridge. So it seems something changed regarding when the daemon attempts to start listening on a TCP address: it used to do that after the bridge had been created, which allows the use of a TCP address on the bridge IP.

```
user@photon:~$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
```

```
user@photon:~$ docker info
Containers: 9
 Running: 4
 Paused: 0
 Stopped: 5
Images: 711
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 542
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.35 GiB
Name: photon
ID: IG3A:UAZZ:TTMW:EPRF:VMZG:NQEW:Y4OA:MCUN:74LE:EAYM:NIVY:NTT4
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Not sure what changed in this, but wondering; why not bind-mount the docker socket in those containers you want to give access to the API? That would give more fine grained control; using the setting you describes would give *every* container access to the API (and effective `root` access to your host!), which is really insecure, so e.g.;


    docker run -v /var/run/docker.sock:/var/run/docker.sock some-image-that-needs-access

**Comment by Confusion** [comment]
Thanks for the advice. There are currently no security concerns due to using this configuration, but in the future I will certainly switch to such an alternative. And if these DOCKER_OPTS are e.g. no longer supported, I will have to switch a bit earlier :)

**Comment by thaJeztah** [comment]
Oh! can you edit the top description and add the output of `docker version` and `docker info`?

**Comment by justincormack** [comment]
I don't think we can guarantee the ordering here. Linux does however have
an IP_FREEBIND option to bind to addresses that do not yet exist, so it
would be possible to add an option for doing this I guess.

**Comment by sam-thibault** [comment]
This is an old question.  I will close it as stale.
