### ISSUE TITLE
[1.12-rc4] Service discovery not working

### ISSUE THREAD

**Issue by ianlewis** [moby/moby#24890]
I have a docker swarm cluster running on GCE. I've started 4 services in the cluster as follows:

```
ianlewis@swarm-dev:~$ docker service ls
ID            NAME       REPLICAS  IMAGE                                          COMMAND
3ep49061lhyh  guestbook  1/1       asia.gcr.io/ultimate-hydra-87508/guestbook:v3
5fer8snc1acz  web        1/1       asia.gcr.io/ultimate-hydra-87508/web:v8
991huh0e6s5o  ngword     1/1       asia.gcr.io/ultimate-hydra-87508/ngword:v2
e2pwnci25ky4  redis      1/1       redis
```

I expect that each of the services will have service discovery enabled. For example,
accessing the host "guestbook" will resolve to a container for the guestbook app and
allow me to connect to it. But I cannot resolve any services. The logs for the web container
contain the following:

```
2016/07/21 09:25:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup guestbook on 127.0.0.11:53: no such host"; Reconnecting to {"guestbook:8080" <nil>}
2016/07/21 09:25:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup ngword on 127.0.0.11:53: no such host"; Reconnecting to {"ngword:8080" <nil>}
```

The local 127.0.0.1:53 DNS is being used but the services are not resolving. Is
there something else that is needed to get service discovery working?

**Comment by mavenugo** [comment]
@IanLewis can you pls give the following details -

* exact command you used to initialize the swarm cluster (manager and workers)
* ifconfig on these machines
* OS & kernel details

FYI. We highly recommend you to use `docker swarm init --listen-addr=<valid-unique-cluster-ip>`. not using the `listen-addr` might result in daemon binding to a default interface that may not be cluster capable.

**Comment by IanLewis** [comment]
@mavenugo Thanks for the tip. I didn't use --listen-addr but it looks like the port is bound properly anyway. I can see the connections from the worker nodes.

    root@swarm-manager:~# lsof -i :2377
    COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    dockerd 21621 root   13u  IPv6  40822      0t0  TCP swarm-manager.c.ultimate-hydra-87508.internal:2377->swarm-worker-1.c.ultimate-hydra-87508.internal:35616 (ESTABLISHED)
    dockerd 21621 root   15u  IPv6  40000      0t0  TCP *:2377 (LISTEN)
    dockerd 21621 root   21u  IPv4  40008      0t0  TCP localhost:34814->localhost:2377 (ESTABLISHED)
    dockerd 21621 root   22u  IPv6  40016      0t0  TCP localhost:2377->localhost:34814 (ESTABLISHED)
    dockerd 21621 root   25u  IPv6  41159      0t0  TCP swarm-manager.c.ultimate-hydra-87508.internal:2377->swarm-worker-2.c.ultimate-hydra-87508.internal:40464 (ESTABLISHED)

Nodes look like they have joined the cluster properly:

    ianlewis@swarm-dev:~$ docker node ls
    ID                           HOSTNAME        MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
    0dlg70jdijrln8seaidoa018o *  swarm-manager   Accepted    Ready   Active        Leader
    bogybyfydcnlpcgtnr0cu011x    swarm-worker-2  Accepted    Ready   Active        
    ecic9i6ibdq7ib8vvxwdafbsh    swarm-worker-1  Accepted    Ready   Active

I used the following commands to create the cluster (secrets and hashes withheld to protect the innocent):

  docker-machine create swarm-manager \
      --engine-install-url experimental.docker.com \
      -d google \
      --google-machine-type n1-standard-1 \
      --google-zone europe-west1-b \
      --google-disk-size "500" \
      --google-tags swarm-cluster \
      --google-project ultimate-hydra-87508
  eval $(docker-machine env swarm-manager)
  docker swarm init

  docker-machine create swarm-worker-1 \
      --engine-install-url experimental.docker.com \
      -d google \
      --google-machine-type n1-standard-1 \
      --google-zone europe-west1-b \
      --google-disk-size "500" \
      --google-tags swarm-cluster \
      --google-project ultimate-hydra-87508

  eval $(docker-machine env swarm-worker-1)
  docker swarm join --secret XXXX --ca-hash sha256:XXXX 10.240.0.4:2377

  docker-machine create swarm-worker-2 \
      --engine-install-url experimental.docker.com \
      -d google \
      --google-machine-type n1-standard-1 \
      --google-zone europe-west1-b \
      --google-disk-size "500" \
      --google-tags swarm-cluster \
      --google-project ultimate-hydra-87508

  eval $(docker-machine env swarm-worker-2)
  docker swarm join --secret XXX --ca-hash sha256:XXXX 10.240.0.4:2377

**Comment by mavenugo** [comment]
@IanLewis Even though the swarm node connectivity is established, the gossip may not have because of the possible issue with the invalid interface selection. Hence my request to see the `ifconfig` of these nodes so that we will know if there is a possibility of such a scenario. Also, that is the reason why we recommend specifying the listen-addr explicitly (in rc4) and we are planning on forcing the user to specify advertise-addr in rc5 if the auto-detection is ambigous.

Could you please share the `ifconfig` on the manager and also redoing the cluster by setting the `--listen-addr 10.240.0.4:2377` in the manager ?

**Comment by IanLewis** [comment]
Server info

    root@swarm-manager:~# uname -a
    Linux swarm-manager 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Heres the output from ifconfig -a

    root@swarm-manager:~# ifconfig -a
    docker0   Link encap:Ethernet  HWaddr 02:42:37:5d:69:32  
              inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:160 errors:0 dropped:0 overruns:0 frame:0
              TX packets:143 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:10630 (10.6 KB)  TX bytes:14784 (14.7 KB)

    docker_gwbridge Link encap:Ethernet  HWaddr 02:42:16:ac:08:f9  
              inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:9472 errors:0 dropped:0 overruns:0 frame:0
              TX packets:9430 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:586683 (586.6 KB)  TX bytes:901132 (901.1 KB)

    eth0      Link encap:Ethernet  HWaddr 42:01:0a:f0:00:04  
              inet addr:10.240.0.4  Bcast:10.240.0.4  Mask:255.255.255.255
              UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
              RX packets:832165 errors:0 dropped:0 overruns:0 frame:0
              TX packets:778196 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:429770736 (429.7 MB)  TX bytes:124375356 (124.3 MB)

    lo        Link encap:Local Loopback  
              inet addr:127.0.0.1  Mask:255.0.0.0
              UP LOOPBACK RUNNING  MTU:65536  Metric:1
              RX packets:202308 errors:0 dropped:0 overruns:0 frame:0
              TX packets:202308 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:30189098 (30.1 MB)  TX bytes:30189098 (30.1 MB)

    lxcbr0    Link encap:Ethernet  HWaddr e2:fc:be:49:49:7f  
              inet addr:10.0.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

    veth3d2e769 Link encap:Ethernet  HWaddr 96:70:29:6b:01:5a  
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:9278 errors:0 dropped:0 overruns:0 frame:0
              TX packets:9290 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:703230 (703.2 KB)  TX bytes:892438 (892.4 KB)

    vethd624295 Link encap:Ethernet  HWaddr 2a:43:2a:8d:9f:ff  
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:8 errors:0 dropped:0 overruns:0 frame:0
              TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:648 (648.0 B)  TX bytes:690 (690.0 B)

    vetheb93061 Link encap:Ethernet  HWaddr e6:a6:a3:6e:cc:76  
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:146 errors:0 dropped:0 overruns:0 frame:0
              TX packets:217 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:12173 (12.1 KB)  TX bytes:14428 (14.4 KB)

**Comment by mavenugo** [comment]
@IanLewis thanks. Can you also confirm if the security-groups (or its equivalent) has all the appropriate ports opened ?

* TCP and UDP port 7946 for communication among nodes
* TCP and UDP port 4789 for overlay network traffic

**Comment by upccup** [comment]
@thaJeztah there has a similar program, hope to support info 
https://github.com/docker/docker/issues/24679

**Comment by IanLewis** [comment]
@mavenugo By default GCP allows traffic on all ports between VMs on the same network. So yes, the ports are opened.

However, I currently don't have routing set up to route the overlay network's traffic. Is Docker NATing and forwarding the traffic internally? or relying on the environment's network to route traffic?

**Comment by IanLewis** [comment]
@upccup It looks like in your case you are able to resolve the service's hostname to an IP but can't actually connect. I'm not even able to resolve the hostname's IP using DNS.

**Comment by upccup** [comment]
@IanLewis  yes the hostname resolved but it was wrong

**Comment by IanLewis** [comment]
I did `docker swarm leave` on every node in the cluster and then `docker swarm init --listen-addr 10.240.0.4:2377` to reinitialize the cluster, and `docker swarm join --secret XXXXX --ca-hash sha256:XXXX 10.240.0.4:2377` to rejoin each of the workers.

I still don't get the nodes to resolve

    2016/07/22 13:39:22 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup guestbook on 169.254.169.254:53: no such host"; Reconnecting to {"guestbook:8080" <nil>}
    2016/07/22 13:39:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup ngword on 169.254.169.254:53: no such host"; Reconnecting to {"ngword:8080" <nil>}
    2016/07/22 13:40:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup ngword on 169.254.169.254:53: no such host"; Reconnecting to {"ngword:8080" <nil>}

Not sure what the IP address `169.254.169.254` is but it's now trying to resolve using that now. Will try to recreate the cluster from scratch and see if that helps.

**Comment by thaJeztah** [comment]
@IanLewis is this still an issue on the current (1.12.3) release?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
