### ISSUE TITLE
Support --dns or --addn-hosts for 'docker build' like 'docker run'

### ISSUE THREAD

**Issue by nhnb** [moby/moby#24928]
Docker should support dns options on `docker build` in the same way it supports them on `docker run`.

This feature has been requested a number of times in the past, but all issues have been closed with a references to an extremely impractical workaround (issue #5779). 

This workaround requires to overwrite /etc/hosts from the Dockerfile at the beginning of the build and restoring it at the end. This especially means that there needs to be some proprietary configuration to store the ip address of the dns server  (in the Dockerfile,  a configuration file, someone else) .

Even worse: If the author of the Dockerfile did not face the dns issue himself, he will not have added such a configuration option at all.

A clean solution is to have `docker build` understand the dns configuration provided on the command line of `docker build` or the daemon in exactly the same way `docker run` does. This will provide a standardized solution that will work out of the box.

**Comment by thaJeztah** [comment]
Could you explain why setting the `--dns` option on the daemon doesn't work for your use case? This sounds like a general configuration issue for the environment you're running docker in, not for individual builds

**Comment by glehmann** [comment]
Is there a way to pass that flag to the daemon with the mac application?

**Comment by thaJeztah** [comment]
> Is there a way to pass that flag to the daemon with the mac application?

I don't think it's currently exposed in the UI, so may be worth opening a feature request for in the docker for mac issue tracker (if it doesn't exist); https://github.com/docker/for-mac/issues

**Comment by glehmann** [comment]
Thanks. There is actually already a ticket for that: https://github.com/docker/for-mac/issues/179

**Comment by thaJeztah** [comment]
`--add-host` was added to `docker build` in Docker 17.04, and Docker for Mac now has a control panel to set the `daemon.json` configuration (e.g. to set a dns different than the host), so I think this should be resolved

<img width="380" alt="screen shot 2017-06-14 at 18 25 19" src="https://user-images.githubusercontent.com/1804568/27143531-f295d278-512e-11e7-9a54-18969f0287b1.png">

**Comment by alonl** [comment]
I suggest to reopen this issue. I'd really much like to specify ad-hoc `--dns` and `--dns-search` to the `docker build` command, like `docker run` has. 

My use case:
We're building a docker image through a jenkins-slave pod that runs within a Kubernetes cluster in  GKE (Google Container Engine).
I don't have an access to the Docker daemon settings in GKE, but I'd really much like to have custom dns configurations for the `docker build` context.
(More specifically, I run `npm install`, which tries to resolve a kubernetes-local address, in one of the `docker build` stages).

Many thanks.

**Comment by sourcekick** [comment]
We also would like to see `--dns` etc. on `docker build`. Also experiencing problems in that area and it is not so easy to find workarounds.

**Comment by nikos9742** [comment]
Pleasee  :'(

**Comment by mfthomps** [comment]
Yes, a --dns on docker build would be a huge help.  Currently have to diddle /etc/resolv.conf, which is an ugly hack with terrible side effects.

**Comment by chris-heathwood-mood** [comment]
Just hit this too and --dns on build would be really handy.

**Comment by socketpair** [comment]
+1

**Comment by praveenksarathi** [comment]
+1

**Comment by KBlansit** [comment]
++1

**Comment by DeanD-code** [comment]
++1

**Comment by thaJeztah** [comment]
I'm locking the conversation on this one; because this feature was implemented, so there's no need to add "+1"'s and send out e-mails and notifications to thousands of users.

If there are additional features you'd like to see added to `docker build`, and you have a use-case that describes why those features are needed, please open a ticket in https://github.com/moby/buildkit.

> `--add-host` was added to `docker build` in Docker 17.04 (see #30383), and Docker for Mac now has a control panel to set the `daemon.json` configuration (e.g. to set a dns different than the host), so I think this should be resolved
> 
> <img alt="screen shot 2017-06-14 at 18 25 19" width="380" src="https://user-images.githubusercontent.com/1804568/27143531-f295d278-512e-11e7-9a54-18969f0287b1.png">
