### ISSUE TITLE
Slow execution within NodeJS container

### ISSUE THREAD

**Issue by mindvox** [moby/moby#24933]
Hi All,

I have a rabbitmq consumer which is a nodejs application. The process is simple, upon receipt of a message payload. Launch a python script which exports from a database using the parameters of the message payload.

The issue is that the NodeJS applications runs, gets to the Python script (python-shell) and begins. However this is where the worker hangs and no other response.. or error is provided.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.5 MiB
Name: exports.oxheyhall.com
ID: QHWH:MFDP:RWI6:DK7H:NG6T:GWQL:MUIW:AYHD:GKH6:HPGZ:VWKH:6BCX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Digital Ocean droplet, 512mb RAM, 20GB SSD, Debian amd64 Jessie 8.5, Node LTS argon, Python 3.4

**Steps to reproduce the issue:**
1. Build the image.
2. Launch a container.
3. Send a message to the consumer.

**Describe the results you received:**

Container runs but halts at the step where the Python script is launched.

**Describe the results you expected:**

Should complete and send a notification email. The consumer, then continues to listen for further messages.

**Additional information you deem important (e.g. issue happens only occasionally):**

Due to the sensitive nature of the application, I cannot provide a repo or any source code. I will however provide as much information and assistance as possible to get this solved.

Regards,
Karl

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
