### ISSUE TITLE
Docker install shell script to allow setting proxy on docker.repo

### ISSUE THREAD

**Issue by adamjk-dev** [moby/moby#24931]
It would be nice if we had a way to pass in a parameter to set the proxy on the docker.repo file. The code can be seen here:

https://github.com/docker/docker/blob/master/hack/install.sh#L450-L457

**Comment by thaJeztah** [comment]
Couldn't you just `export http_proxy=.....`, then run the installation script?

**Comment by adamjk-dev** [comment]
Yeah that works of course. Just thinking about automating it all etc. and I dislike setting that env variable on the root user to be honest. I can't recall the entire internals of how Puppet handles env variables (I think they are temporary in an exec{} resource), just thought I would ask about it here.

**Comment by thaJeztah** [comment]
But you'd still have to pass that information to the script (most likely through an environment variable). Could you describe what it would look like / work with your suggested changes?

**Comment by adamjk-dev** [comment]
Wouldn't the install script take a param (or more), one for proxy. Then you invoke it and pass the param:

curl -fsSL https://test.docker.com/ | sh <proxy.address>

**Comment by thaJeztah** [comment]
Have you tried;

```
curl -fsSL https://test.docker.com/ | http_proxy=foobar sh
```

**Comment by adamjk-dev** [comment]
Just tried that and it didn't work for me. I had to export the env variables first then run the curl installer.

**Comment by CodingSpiderFox** [comment]
Ran into that issue, too today

**Comment by bsousaa** [comment]
Installation related issues can be reported at https://github.com/docker/docker-install/issues. Meanwhile I'm closing this one here.
