### ISSUE TITLE
Cannot join swarm after join-token update

### ISSUE THREAD

**Issue by nostrebor** [moby/moby#24953]
**Output of `docker version`:**

```
Docker version 1.12.0-dev, build 771cf83
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-253:0-1123074-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.743 GB
 Data Space Total: 107.4 GB
 Data Space Available: 46.12 GB
 Metadata Space Used: 6.038 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: dewx6a4pw3t8359accavftyjx
 Is Manager: true
 Managers: 1
 Nodes: 1
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.664 GiB
Name: VM-DevDockE3.sseng.local
ID: KFRT:CW3U:J5UA:PELM:32BF:CDE5:LKNE:VYBR:LWA5:S55I:GHZE:THNN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS VM created through HyperV. i386 architecture.

**Steps to reproduce the issue:**
1 `docker swarm init --listen-addr:$(hostname)`

Verify: Token text is empty

2 `docker swarm inspect`

```
[
    {
        "ID": "cu92x31nskc0u7il0m8yfjw6f",
        "Version": {
            "Index": 10
        },
        "CreatedAt": "2016-07-22T22:03:01.692078046Z",
        "UpdatedAt": "2016-07-22T22:03:01.911365077Z",
        "Spec": {
            "Name": "default",
            "Orchestration": {
                "TaskHistoryRetentionLimit": 10
            },
            "Raft": {
                "SnapshotInterval": 10000,
                "LogEntriesForSlowFollowers": 500,
                "HeartbeatTick": 1,
                "ElectionTick": 3
            },
            "Dispatcher": {
                "HeartbeatPeriod": 5000000000
            },
            "CAConfig": {
                "NodeCertExpiry": 7776000000000000
            },
            "TaskDefaults": {}
        },
        "JoinTokens": {
            "Worker": "",
            "Manager": ""
        }
    }
]
```

3 Attempt to connect with the empty join token:

```
docker swarm join \
--token  \
--listen-addr=$(hostname) \
VM-DevDockE3:2377
```

Verify: 

```
Error response from daemon: Your node is in the process of joining the cluster but needs to be accepted by existing cluster member.
To accept this node into cluster run "docker node accept 0e33ys2oz6hobugo07cq38wnp" in an existing cluster manager. Use "docker info" command to see the current Swarm status of your node.
```

4  Attempt to run the `docker node accept` command

Verify: The usage for docker node comes up, as the add command has been removed.

**Describe the results you received:**

Using the token workflow, I was unable to have a node join the swarm. 

**Describe the results you expected:**

My expected behavior would be that of the previous swarm, where nodes are auto accepted (or the option to auto accept nodes is configurable) and tokens are generated when a swarm is initialized. What is the expected behavior of swarm init now?

**Additional information you deem important (e.g. issue happens only occasionally):**
Is it bad practice to file bugs against the master branch here?

**Comment by thaJeztah** [comment]
> Is it bad practice to file bugs against the master branch here?

No! Please do, it's appreciated; sometimes bugs can be known issues, or related to "work in progress", but otherwise, we can never have enough eyes! :+1: 

ping @aaronlehmann

**Comment by thaJeztah** [comment]
It looks like your server is not the current master, only the client, is that correct?

**Comment by nostrebor** [comment]
Probably. What is considered the server? Two of us in it were having issues
and googling docker server is not very fruitful

**Comment by thaJeztah** [comment]
Server is the daemon; how did you install the "master" version? Did you install it inside the VM, or on the host?

**Comment by nostrebor** [comment]
I installed it on the host, and then `export DOCKER_API_VERSION=1.2.4`. I think I did forget to restart the daemon. I'll try that now.

**Comment by thaJeztah** [comment]
After restarting the daemon, both client and server version are the same in `docker version` output?

**Comment by nostrebor** [comment]
No, the daemon is still v1.24. I didn't see that on masterproject there are dockerd files available for download as well, but I don't see any for linux/386. Is there a reason?

**Comment by thaJeztah** [comment]
@nostrebor the daemon requires 64-bit, only the client can run on 32-bit. Note that the 1.24 is the API version; you need to look at the `Git commit` in `docker version`

**Comment by nostrebor** [comment]
Sorry, I wasn't clear, the daemon version is still e4a0dbc, the release version for rc4.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
