### ISSUE TITLE
clarify docker daemon v/s dockerd command in "Configuring and running Docker on various distributions"

### ISSUE THREAD

**Issue by sfsmithcha** [moby/moby#24989]
Reference to `docker daemon` v/s `dockerd` is ambiguous in "Configuring and running Docker on various distributions" (docs/admin/index.md).  See @mlaventure 's comment on https://github.com/docker/docker/pull/24970/files/88ebfc701238dcfacfaf1d3f0a363848460df452#r71992335

This article looks like it needs to be reworked for clarity in general.

**Comment by thaJeztah** [comment]
docs moved to a separate repository, and I don't think this is still an issue
