### ISSUE TITLE
Proposal : Daemon labels auto discovery

### ISSUE THREAD

**Issue by zepouet** [moby/moby#25024]
Hello,

Instead of writing its own label for each docker engine into a cluster, it would be nice to have an option to enable for auto discovery. 

At the moment, we need to write 

```
docker daemon \
  --dns 8.8.8.8 \
  --dns 8.8.4.4 \
  -H unix:///var/run/docker.sock \
  --label com.example.environment="production" \
  --label com.example.storage="ssd"
```

We need to use custom agent on each host to discover capabilities for machine. It will be nice to have this feature integrated into Docker. For example :

```
docker daemon \
  --dns 8.8.8.8 \
  --dns 8.8.4.4 \
  -H unix:///var/run/docker.sock \
  --labels.mode.discovery=true
```

We must define a list of capability to discover. 
The result could be  equivalent to :

```
label disks.size 2048
label disks.number 2
label filesystems.type btrfs
label provider.identity gce
label machine.is_virtual false
label kernel.majversion 4.7
label kernel.release 3.13.095
label os.release xxx
label os.family centos
label os.architecture xxx
... 
...
label. os.selinux enabled
label processors.count 4
label processors.speed 2048
label processors.model XEON
label timezone UTC
... ... 
```

We could imagine many usecases with these feature with labels constraint in Swarm mode.
What do you think about this feature ? It is important to override any labels with manual value.
A new command from docker client to display all daemon labels would be useful too.

Thanks you very much. Best regards

**Comment by holtkampjs** [comment]
Hi @zepouet,

It appears that this issue has been addressed by work done since this enhancement was suggested. 

For the context of future users, the command `docker daemon...` has been replaced by [`dockerd`](https://docs.docker.com/config/daemon/) and it's associated functionalities.

The ability to define multiple labels (or other docker daemon configurations) in a reusable manner has been implemented in the [`daemon.json`](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) file.

**Comment by thaJeztah** [comment]
Yes, manually setting labels for the engine itself is possible through the `daemon.json`, and for swarm-nodes, can also be managed centrally through `docker node`;

```
docker node update --help

Usage:  docker node update [OPTIONS] NODE

Update a node

Options:
      --availability string   Availability of the node ("active", "pause", "drain")
      --label-add list        Add or update a node label ("key=value")
      --label-rm list         Remove a node label if exists
      --role string           Role of the node ("worker", "manager")
```

I think the proposal here was to _automatically_ generate labels for the engine that contain properties of the system it's running on, such as amount of disk-space, number of processors, kernel version, etc.

However, I don't think there's currently plans to implement that; to do so, we'd st least need to define _what_ labels to set (what information is important may vary widely between use-cases), and collecting that information would potentially add a significant amount of work (e.g. amount of disk-space cannot be assumed to be "static", as storage can be attached, detached, or scaled).

I will close this ticket for now at least.
