### ISSUE TITLE
swarm: Tasks are not re-balanced to other nodes when the registry fails

### ISSUE THREAD

**Issue by abronan** [moby/moby#25026]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   19ec73b
 Built:        Mon Jul 25 15:32:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   19ec73b
 Built:        Mon Jul 25 15:32:30 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 0qij1ldlpnowrt90xkguvefz1
 Is Manager: true
 Managers: 3
 Nodes: 6
 Node Address: X.X.X.X
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: node02
ID: GKPJ:V5TB:W373:3WHL:LMIH:2S7O:CM6H:QGHE:6GGU:WUUC:TF5E:MNGC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Digital Ocean VMs:

_3 Managers_: 2 GB Memory / 40 GB Disk / Ubuntu 16.04 x64
_3 Agents_: 1 GB Memory / 30 GB Disk / Ubuntu 16.04 x64

`rm` of `/var/lib/docker` between each test.

**Steps to reproduce the issue:**
1. Create a cluster with 3 Managers (without `--availability drain`) and 3 Workers
2. Create a test service with `docker service create --replicas 5 --name redis redis`
3. Check if at least one of the tasks is scheduled on a Manager node
4. Update the 3 Manager nodes with `--availability drain`
5. Introduce an error on one of the Worker's access to registry (wrong credentials? or cutting the connectivity of this node to the registry).
6. Periodically look at `docker service ls` and `docker service tasks redis` to see if the tasks are re-scheduled.

**Describe the results you received:**

The system does not try to reconcile the number of Replicas to the expected number of **5** after experiencing a failure with the registry on one of the Workers:

```
ERRO[12300] fatal task error                              error=No such image: redis:latest module=taskmanager task.id=cj8w489wmk9ln6gkk0pqfp3bd
ERRO[12300] container status unavailable                  error=context canceled module=taskmanager task.id=cj8w489wmk9ln6gkk0pqfp3bd
ERRO[12301] Error trying v2 registry: context canceled   
ERRO[12301] Not continuing with pull after error: context canceled 
ERRO[12301] pulling image failed                          error=context canceled module=taskmanager task.id=1y3vo9wghp300dst0jld4n1fh
ERRO[12301] fatal task error                              error=No such image: redis:latest module=taskmanager task.id=1y3vo9wghp300dst0jld4n1fh
ERRO[12301] container status unavailable                  error=context canceled module=taskmanager task.id=1y3vo9wghp300dst0jld4n1fh
```

It seems to be stuck at `3/5` forever:

```
node01:~# docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
cvwjisfemr7b  redis  3/5       redis
```

```
node01:~# docker service tasks redis
ID                         NAME     SERVICE  IMAGE  LAST STATE             DESIRED STATE  NODE
akwdf32if8hxuy8339yes04u4  redis.2  redis    redis  Running 6 minutes ago  Running        node06
eawgxcscxp3xvwh66atqmyhvt  redis.4  redis    redis  Running 6 minutes ago  Running        node05
4hhfxfkin0xbivrxlcua09ssk  redis.5  redis    redis  Running 6 minutes ago  Running        node06
```

**Describe the results you expected:**

Number of Replicas should reconcile after draining the Managers and be at `5/5` for the redis service. I should see 5 containers running on the Workers with `docker ps` on the nodes and `docker service tasks redis` despite one of the nodes failure to pull the image for what seems to be a registry error.

**Additional information you deem important (e.g. issue happens only occasionally):**

If I try a `docker service scale redis=10` I get:

```
node01:~# docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
cvwjisfemr7b  redis  6/10      redis
```

The difference of 4 to get to the expected `10` replicas might be because those 4 tasks should end up on the faulty node with the registry error. Somehow I would expect the orchestrator to schedule the tasks on the other nodes to get to the expected number of replicas and be aware of the pull errors experienced on the faulty node.

/cc @aaronlehmann @stevvooe @aluzzardi

**Comment by aaronlehmann** [comment]
> Somehow I would expect the orchestrator to schedule the tasks on the other nodes to get to the expected number of replicas and be aware of the pull errors experienced on the faulty node.

Yeah, that's not currently how it works. It tries to balance the number of tasks on each node. So if one node is responsive isn't able to start tasks, the state will never converge.

I don't think we can fix this for 1.12.

**Comment by abronan** [comment]
Agreed. I think it is reasonable to remove the milestone and tentatively try to enhance this for `1.13`.

**Comment by aluzzardi** [comment]
@aaronlehmann But shouldn't the tasks be flagged as `REJECTED`, forcing the orchestrator to start other tasks?

**Comment by aaronlehmann** [comment]
Yes, but they would land on the same node, because that one has fewer tasks than the others.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
