### ISSUE TITLE
library/nginx:1.9 should not be same with nginx:1.9 on CentOS 7?

### ISSUE THREAD

**Issue by ywk253100** [moby/moby#25061]
I have an image named nginx:1.9 on CentOS 7, and when I started a container using "docker run -it library/nginx:1.9 /bin/bash", docker went to download the image instead of using nginx:1.9. The image downloaded was named docker.io/nginx:1.9.  Does this make sense?

docker version:
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.6.2-14.el7.centos.x86_64
docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.6.2-14.el7.centos.x86_64
docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

**Comment by thaJeztah** [comment]
Looks like this was reported with the Red Hat fork of Docker, which has many changes that are not in the official Docker source code (and which modifies this behavior, causing this). Closing because this issue is very old now
