### ISSUE TITLE
Pull will unconditionally download and expand all layers for an image, even if those layers are already present on the box

### ISSUE THREAD

**Issue by swernli** [moby/moby#25091]
@stevvooe @aaronlehmann 
When performing a docker pull, the only check that is performed to see if the host already contains the data is based on the image hash.  This means that all layers in that image end up getting downloaded and expanded if the image isn't present, even if some of the intermediate layers are.  In the case of Windows, where base layer can be multiple GB in size, there is a very high cost to downloading, expanding and processing the layer into the graphdriver only to end up deleting it once the layerstore identifies it as a duplicate.

Ideally, the pull code would check the hashes of the layers provided in metadata against the layerstore first and skip downloading layers that are already present on the machine.

FYI @jhowardmsft @jstarks

**Comment by stevvooe** [comment]
@swernli Do you have any log output demonstrating this? What are you seeing that makes you think this?

**Comment by swernli** [comment]
@stevvooe I have some logs I can provide.  Here is a rundown of my scenario:
I have a base image that I've loaded into the daemon via `docker load` and then built a new image on top of that base layer called tlist.  I then push the tlist image to my private registry, which will push both the new layer and the base layer.  Then I delete tlist from my daemon, and do a `docker pull` of the image from the repository.  From the debug output in the daemon, I can see that both layers are downloaded and added to the graphdriver, but then the base layer is deleted after the layerstore rejects it with the error "layer already exists".  Note that this only happens the first time I do the pull, as the layer has never been pulled before (since it was added to the system via `docker load`).  See logs below:

<code>
time="2016-07-26T15:06:19.766359000-07:00" level=debug msg="Trying to pull 10.124.186.147:5000/swernli/tlist from http://10.124.186.147:5000 v2"
time="2016-07-26T15:06:19.782386700-07:00" level=debug msg="Pulling ref from V2 registry: 10.124.186.147:5000/swernli/tlist:latest"
time="2016-07-26T15:06:19.783361200-07:00" level=debug msg="pulling blob \"sha256:6e9c5f899461ff38bd05dac7ec0381bc89ccfa0e8fadb27b4929d45efb176950\""
time="2016-07-26T15:06:19.783361200-07:00" level=debug msg="pulling blob \"sha256:cf62dbf6d334601f3e026a976218e4d73641ab8c3e66a842a4e4dbdc72768b18\""
time="2016-07-26T15:06:19.796389900-07:00" level=debug msg="Downloaded 6e9c5f899461 to tempfile C:\\Users\\swernli\\AppData\\Local\\Temp\\GetImageBlob387585093"
time="2016-07-26T15:06:35.705723700-07:00" level=debug msg="Downloaded cf62dbf6d334 to tempfile C:\\Users\\swernli\\AppData\\Local\\Temp\\GetImageBlob348265184"
time="2016-07-26T15:06:35.706690800-07:00" level=debug msg="hcsshim::CreateLayer Flavour 1 ID 23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a parent "
time="2016-07-26T15:06:35.710810700-07:00" level=debug msg="hcsshim::CreateLayer  - succeeded id=23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a parent= flavour=1"
time="2016-07-26T15:08:08.490979300-07:00" level=debug msg="Applied tar sha256:58684737b3d187dfa028519839976bc5393e6c7d838a78f1d3468a4c7ba75ad6 to 23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a, size: 969845625"
time="2016-07-26T15:08:08.522020000-07:00" level=debug msg="Cleaning up layer 23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a: layer already exists"
time="2016-07-26T15:08:08.522020000-07:00" level=debug msg="hcsshim::DestroyLayer Flavour 1 ID 23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a"
time="2016-07-26T15:08:14.329686000-07:00" level=debug msg="hcsshim::DestroyLayer succeeded flavour=1 id=23acde6b55a6338769c6c0b8ce76abaca06f6e3c7cb572f90ddbf2c2e037f53a"
</code>

**Comment by aaronlehmann** [comment]
> I have a base image that I've loaded into the daemon via docker load

I think this is the issue.

We do check if the layers already exist, but we don't use the DiffIDs given in the image configuration directly. Instead, we consult a cache that maps artifact digests from the manifest to DiffIDs. So if we have downloaded an artifact before, we know what DiffID it maps to. But this information is not carried on save/load.

One reason it works this way instead of using DiffIDs directly is that the image configuration can download in parallel with the layers. Otherwise, the process would be more serialized.

It may make sense to propagate the `distribution descriptor` -> `DiffID` mapping metadata along with images that are transmitted through `docker save` / `docker load`.

cc @tonistiigi @dmcgowan

**Comment by tonistiigi** [comment]
> It may make sense to propagate the distribution descriptor -> DiffID mapping metadata along with images that are transmitted through docker save / docker load.

This only works if the tar contains compressed layers. This isn't implemented because by default the layers in `docker load` tarballs are not compressed but I've heard this is different for some windows tars(https://github.com/docker/docker/pull/23949#issue-162242634).

**Comment by aaronlehmann** [comment]
The tar doesn't need to contain the compressed layers. It would just be a way of prepoplating the cache so when trying to push the layers, Docker can start with `HEAD .../<compressed sha256>` instead of compressing the layer and pushing it up.

Not sure whether we would want to trust this kind of metadata through `docker load`. But we do trust the tags saved in the tarball, so this seems reasonable.

**Comment by tonistiigi** [comment]
> Not sure whether we would want to trust this kind of metadata through docker load. But we do trust the tags saved in the tarball, so this seems reasonable.

I think using a tag is from tarball is not the same as trusting a hash without validation. By doing this we can't be sure the pulled image is correct(at least for v2/schema1).

**Comment by aaronlehmann** [comment]
I don't think it would affect pull. You would need the reverse mapping for pull.

**Comment by tonistiigi** [comment]
@aaronlehmann The original issue seems to be more about pull than push. But I don't see it as being much different, then after push user can't be sure that the image they pushed is the same as on user's disk.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
