### ISSUE TITLE
Can not trap non-zero exit code

### ISSUE THREAD

**Issue by Murf** [moby/moby#25102]
When a build fails in my docker container, it still exits with exit code 0

[10:51:35] make: **\* [dist] Error 1
[10:51:35]The command '/bin/sh -c cd src && make' returned a non-zero code: 2
[10:51:38]Process exited with code 0

Here is the relevant Dockerfile entries:
ADD ./src/ /src
RUN chown -R rpm: /src
USER rpm
RUN cd src && make 
CMD /bin/bash

**Comment by duglin** [comment]
@Murf is this still an issue?  I'm not able to reproduce it.

**Comment by thaJeztah** [comment]
Closing this because of age
