### ISSUE TITLE
Failed to use the client credentials store when running headless

### ISSUE THREAD

**Issue by HuKeping** [moby/moby#25169]
With the `docker-credential-secretservice` Release v0.3.0. under $PATH

docker version

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```

The config.json

```
$ cat ~/.docker/config.json 
{
    "credsStore": "secretservice"
}
```

docker login failed with this error:

```
$ docker login docker.io
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by thaJeztah** [comment]
ping @runcom any ideas?

**Comment by HuKeping** [comment]
I think it would be lack of the external credential store on my machine, I'll try it out and feedback.

**Comment by HuKeping** [comment]
On another machine,  with the `gnome-keyring` installed, I still get
```
delegation_docker@ubuntu:~$ gnome-keyring
usage: gnome-keyring command [options]
commands: certificate-exception
          import
          version

delegation_docker@ubuntu:~$ docker login docker.io
error getting credentials - err: exit status 1, out: `Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached`
```

**Comment by runcom** [comment]
The Linux credentials store is meant to be used with an active gnome session where the gnome keyring is there. The Linux credentials isn't meant for headless servers. I'm currently working on one for headless server though.

**Comment by HuKeping** [comment]
@runcom Does the credential data of registry user login with was stored in gnome keyring still as plain text?

**Comment by runcom** [comment]
It isn't store in plain text if that's what's your asking, it's store in the current login session

**Comment by HuKeping** [comment]
Thanks @runcom ! So  if my password for login to the machine was compromised, can the attacker also get the credential for docker registry(or can he `docker login docker.io` successfully)?

**Comment by runcom** [comment]
He can use that if it's logged into your session because the keyring is unblocked when you login (at least on fedora iirc)

**Comment by HuKeping** [comment]
@runcom would you please ping me when the headless version online, thanks :)

**Comment by thaJeztah** [comment]
Should we close this issue? It looks like this is not a bug in docker, but the way the Linux credential store works

**Comment by HuKeping** [comment]
Sure @thaJeztah , but still want a way to track since in most scenario docker would like to be run in a headless server. And without the credential store, the security problem still alive #10318

**Comment by justincormack** [comment]
Ping @runcom are you still working on an alternative?

The credentials store as is is not suited to this use case, a different
version is needed...

**Comment by runcom** [comment]
> Ping @runcom are you still working on an alternative?
> 
> The credentials store as is is not suited to this use case, a different
> version is needed...

we're actively working to integrate the dbus system service not to rely on an X session using `custodia` as its backend on headless installation. We just started working on this at RH but it's another team. I'll keep you posted as we go forward.

**Comment by rdwrt** [comment]
Hi @runcom any news?

**Comment by thaJeztah** [comment]
Since Docker 17.10, the `pass` credentials-store is the default for Linux, which should be able to run headless; https://github.com/docker/cli/pull/451

Closing this issue, because I think this is resolved, but feel free to comment if I closed by mistake

**Comment by jeremyrempel** [comment]
I'm encountering this issue w/ Ubuntu 18.04 and 18.05.0-ce

**Comment by DeadMate** [comment]
Same here. Ubuntu 18.04 - Docker login gives me the very same error

**Comment by thaJeztah** [comment]
Could you open a ticket in the https://github.com/docker/cli issue tracker with details and steps to reproduce?

**Comment by jpjodoin** [comment]
@mindovermiles262: 
Thanks it worked.
Here are the full steps I did:

1) Download docker-credential-secretservice from https://github.com/docker/docker-credential-helpers/releases
2) tar -xvf docker-credential-secretservice.tar.gz 
3) mv docker-credential-secretservice /usr/bin
4) create a ~/.docker/config.json with:
{
    "credsStore": "pass"
}

5) docker login XXX (will fail)
   Output: Error saving credentials: error storing credentials - err: exec: "docker-credential-pass": executable file not found in $PATH, out: ``
6) rm ~/.docker/config.json
7) sudo mv /usr/bin/docker-credential-secretservice /usr/bin/docker-credential-secretservice_x
8) docker login XXX (works magically)

**Comment by thaJeztah** [comment]
@jpjodoin your instructions effectively disable the use of credential-helpers, therefore **storing your credentials _unencrypted_** (in plain text, other than base64 encoded) in the `config.json`.

Looking at your reproduction steps;

- you are downloading /installing the `secretservice` credentials-helper, but
- configure the CLI to use the `pass` credentials helper
- the `pass` credentials helper is not found on your system, thus  storing the credentials fails.

If you repeat those steps, but install the `docker-credential-pass` (https://github.com/docker/docker-credential-helpers/releases/download/v0.6.0/docker-credential-pass-v0.6.0-amd64.tar.gz) helper instead, does it work?

Also note that that credential-helper should be installed by default with current versions of Docker; what version of docker do you have installed?

**Comment by jpjodoin** [comment]
@thaJeztah : Thanks for your feedback !
I am using Docker version 18.06.1-ce, build e68fc7a on Ubuntu 18.04 LTS.

Indeed, changing to docker-credential-pass does work. I followed the steps outlined here to set it up:
https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388634452

**Comment by jpjodoin** [comment]
I have updated my above steps based on your answer:
1) Download docker-credential-pass from https://github.com/docker/docker-credential-helpers/releases
2) tar -xvf docker-credential-pass.tar.gz
3) mv docker-credential-pass /usr/bin
4) You will need to setup docker-credential-pass (following steps are based of https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388634452) 
4.1) install gpg and pass (apt-get install gpg pass)
4.2) gpg --generate-key, enter your information. You should see something like this:
pub   rsa3072 2018-10-07 [SC] [expires: 2020-10-06]
      1234567890ABCDEF1234567890ABCDEF12345678
	  ^-------------------------------------- Copy this string
4.3) pass init (paste string)
4.4) pass insert docker-credential-helpers/docker-pass-initialized-check and set the next password "pass is initialized" (without quotes).
4.5) pass show docker-credential-helpers/docker-pass-initialized-check. You should see pass is initialized.
4.6) docker-credential-pass list
5) create a ~/.docker/config.json with:
{
"credsStore": "pass"
}
6) docker login should now work

**Comment by programingnotes** [comment]
> @jpjodoin your instructions effectively disable the use of credential-helpers, therefore **storing your credentials _unencrypted_** (in plain text, other than base64 encoded) in the `config.json`.
> Also note that that credential-helper should be installed by default with current versions of Docker; what version of docker do you have installed?

This assertion is false.  

My current docker version: 
```
Docker version 18.06.1-ce, build e68fc7a
``` 

Output of docker info : 
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-32-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.4MiB
Name: localhost
ID: 7MF4:NH32:RTBF:EXP2:L5PV:6TO5:7ZPK:QO2J:TQ6P:UWP4:BCOZ:SQVM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

OS info: 
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
``` 

Attempting to find docker-credential-helper in `/usr/bin/ `: 
```
admin@localhost:~$ find /usr/bin/ | grep docker 
/usr/bin/docker-containerd-shim
/usr/bin/dockerd
/usr/bin/docker-containerd-ctr
/usr/bin/docker-runc
/usr/bin/docker-init
/usr/bin/docker-containerd
/usr/bin/docker-proxy
/usr/bin/docker
``` 

Attempting to find docker-credential-helper in `/usr/bin/ `: 
```
root@localhost:~$ sudo find /usr/local/ | grep docker 
/usr/local/bin/docker-compose
```
