### ISSUE TITLE
Swarm mode overcommit configuration

### ISSUE THREAD

**Issue by yoshiokatsuneo** [moby/moby#25201]
I could not find the overcommit option on Docker Swarm mode.
On the traditional docker swarm, I can use option like "swarm.overcommit=3".
How can I overcommit resource on Docker Swarm mode ?

**Comment by icecrime** [comment]
Ping @abronan @dongluochen!

**Comment by dongluochen** [comment]
Thank you @yoshiokatsuneo for the question. It's not a complicated feature but we need to revisit it from resource reservation and stats collection point of view. Cc @aluzzardi, @aaronlehmann.

**Comment by yoshiokatsuneo** [comment]
Any possible plan or idea about the overcommitting on swarm mode?

**Comment by dongluochen** [comment]
@yoshiokatsuneo Currently swarm mode can set resource `reservation` and `limit` on task. `reservation` takes the amount from node's resource, while `limit` would cap/kill the task when it's reached. You may approach overcommit with these 2 parameters. 

Let's say a task may use memory between 200MB - 2GB where >1 GB with low possibility. You can set task memory `reservation` to 1GB and `limit` to 2GB. You may fit 10 tasks into a node of 10GB physical memory. If you look at the sum of `limit` it's overcommitted 100%. Overcommit level is based on the probability of resource requesters peak demands. 

See https://github.com/docker/swarmkit/issues/1211. We would like to hear your use case to see if it can be improved.

**Comment by yoshiokatsuneo** [comment]
@dongluochen Ah, I got it. Thanks !

**Comment by bvis** [comment]
Hi @dongluochen, I'd like to explain here my use case to get your opinion if possible.

I have some services running in a production cluster.
I'm defining the `reservation`/`limit` in a similar way you suggest. It has all the sense of the world and it's something I try to do by default. Some values need to be adapted once you see how the service performs and it's something that should be checked regularly to see if the defined limits still apply. Until here everything is correct.

But I have another cluster for staging, in my case and I think usually it' the case, the cluster has much less capacity than the productive, imagine this situation:

- SWARM PROD: 20 nodes with 16GB/4vCPUs each.
- SWARM STAGING: 5 nodes with 4GB/2vCPUs each.

When I try to adapt a CI/CD pipeline to deploy the same services in both clusters for different testing strategies, I find a capacity problem in the staging cluster where many tasks remain in the undesired "pending" status, as their resource are being defined thinking in SWARM PROD.

To save this situation I can do some things:

- `A.` Maintain different configurations for each of my services based on the cluster to be deployed. It's something feasible but as the more services I have, more the effort invested on this.
- `B.` Define an overcommit value in the staging cluster to "emulate" a similar capacity to the productive cluster. In my example it could be `8x` overcommit in the staging cluster. 
- `C.` Any other suggestion?

**Comment by dongluochen** [comment]
Overcommit is the way a cluster puts more requests than physical resources (like node's memory) and hopes tasks do not really overrun them. IMHO I think option `A` is a good approach. Some automation on user side can help you reduce the management overhead. 

Option `B` looks simple but you are trying to stretch resources uniformly, which I think doesn't work well in practice. Each container is different from another. Stretching memory like CPU doesn't seem right. It'd also conflict with abstract resources https://github.com/docker/swarmkit/issues/594 if we  implement it.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
