### ISSUE TITLE
docker swarm mode initial docker node labels on join

### ISSUE THREAD

**Issue by Richard-Mathie** [moby/moby#25220]
initial set of node labels during swarm join

Version Docker 1.12

When getting a node to join a swarm it should be able to set some of its initial labels to advertise its hardware setup (network=public, storage=ssd ect...). Without this we may get containers provisioned on the node before we are able to set the label constraints, or if we have a node which is added to the swarm through auto scaling containers will not be provisioned to the node until the manager has set the node's config, and why should the  

there is an issue on swarmkit which may be related, is anyone looking at this what needs to be done to get this to work?

[https://github.com/docker/swarmkit/issues/1160#issuecomment-235833933]

**Output of `docker version`:**

``````
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:21:59 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:04:57 2016
 OS/Arch:      linux/amd64
 Experimental: true```


**Output of `docker info`:**

``````

Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: b10jl9vt0ems2tmug5lln4bbp
 Is Manager: true
 Managers: 1
 Nodes: 4
 Node Address: 192.168.99.103
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-boot2docker
Operating System: Boot2Docker 1.12.0-rc5 (TCL 7.2); HEAD : 9b97e11 - Tue Jul 26 22:20:20 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: master1
ID: BOGQ:N6C2:OJDY:IC7Z:JD3Y:AC3B:H25Y:YK4K:TCZP:MDUA:AHP5:3UDE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 62
 Goroutines: 170
 System Time: 2016-07-29T12:08:04.249755937Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: true
Insecure Registries:
 127.0.0.0/8

``````

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox


**Steps to reproduce the issue:**
```docker swarm join --token <worker token> <master address>:2377```

**Describe the results you expected:**
i would like to have flags so that i can `--label-add key=value` to tag the joining node
``````

**Comment by thaJeztah** [comment]
You can set *engine* labels on the node itself (using a `daemon.json` file, or the `--label` flag on the daemon).

Node labels cannot be set by the node itself by design; node labels are "trusted", and only Swarm managers are allowed to set these labels.

**Comment by Richard-Mathie** [comment]
Thanks @thaJeztah for the explanation. closing this issue.

**Comment by thaJeztah** [comment]
You're welcome!
