### ISSUE TITLE
Expose ```parse``` command with a way to extract LABEL, ARG, ENV before the build 

### ISSUE THREAD

**Issue by ydewit** [moby/moby#25227]
We have a Makefile based builder we use to build all our images. At a minimum, we have to specify the IMAGE_NAME and the IMAGE_VERSION and then include a base Makefile.mk where all rules are located. For more complex images with all kinds of dependencies, we end up having to add more metadata to our Makefiles.

Why not embed this metadata directly in the `Dockerfile` and provide a simple way for any build infrastructure to extract that information from it?

As far as I can see, all (most?) the relevant mechanisms already exist in a `Dockerfile`: namely ARG, ENV, LABEL, FROM, EXPOSE, etc. If there was an easy way to extract that information from a `Dockerfile` _before_ the actual `docker build``, we could have a generic builder without spreading metadata across two or more files.

For example, consider the following `Dockerfile`:

```
FROM java:8u92-jre-alpine

MAINTAINER frevvo Inc <dev@frevvo.com>

ARG GIT_COMMIT

LABEL image.name docker-sample
LABEL image.version 2.1.0
LABEL git.commit=${GIT_COMMIT}

LABEL maven.dependencies=["org.apache.tomcat:tomcat-catalina-jmx-remote:7.0.65:jar"]

RUN ...
RUN ...

VOLUME /root/config
VOLUME /root/logs

ENTRYPOINT java -jar sample-exec.war
```

The builder could parse the `Dockerfile` and look for known (possibly required) labels, such as `image.name` and `image.version` that can be used to tag the image when building.

Or a Jenkins plugin could parse the FROM directive to automatically derive build dependencies: i.e. build this when that one builds/changes.

Or based on the `Dockerfile` args, automatically build a `--build-arg` list based on known arguments (GIT_COMMIT, SVN_COMMIT, etc) for inputs coming from the environment/context.

Warn or error when key required labels are not defined in the `Dockerfile` (granted this could be done after the build is done by inspecting the image.

This definitely could be provided as an external `Dockerfile` parser (the path we are taking now), but it is error prone, limited as it may not easily account for ARGS/ENVs interpolations, for instance, unless we start heading to a serious parser, which seems like a waste of time since Docker already has one. The only thing missing is a way to query (--filter) and export (--format) information out of it.

**Comment by cpuguy83** [comment]
@ydewit the parser is in an importable package.
I'm not sure why this would be error prone.

**Comment by rodlogic** [comment]
I meant error prone in terms of rewriting the parser in your language of choice. But sure, if I were to create a parser in Go that imports the Docker parser, that is a different story.

I guess the question is mainly whether does it make sense to support such functionality in the Docker engine.

**Comment by bsousaa** [comment]
The definition of the Dockerfile syntax is now defined in the BuildKit repo: https://github.com/moby/buildkit.
