### ISSUE TITLE
Inexplicable Performance Characteristics (Macbook Air faster than AWS c4.8xlarge at container creation)

### ISSUE THREAD

**Issue by tolmasky** [moby/moby#25259]
We are trying to optimize for container creation and I am hoping that I am simply doing something silly. The app we're building spins up many containers in response to user actions, and Docker seems to very quickly degrade in performance when it is asked to do this. We've tried just about everything: switching to overlayfs, mounting on a ram disk, running separate docker instances to try to parallalize the work -- nothing really has an affect on our container throughput (at least without impacting performance of individual creation time). Frustrated, I put together what I thought was the simplest test I could think of in this script:

  I put together a very simple test script:

``` bash
#!/bin/bash
        for i in `seq 1 10`;
        do
                echo `time docker run mhart/alpine-node:latest node`;
        done
```

I then run it twice concurrently like this:

`$ time ./test.sh & time ./test.sh & wait`

As this runs you can watch container creation performance degrade. Now, on my 1.7 GHz Intel Core i7 Macbook Air running Docker 1.12 through the standard installation (which means its using that VirtualBox system and is limited to ONE CPU and 1.58GB of memory), this test takes about real 0m5.512s to complete. The median container creation time is 0.538s.

Now, we have a c4.8xlarge machine on AWS where I run the same test. Docker there has full access to all 36 CPUs clocked at 2.7Ghz each I believe, 60GB of memory, the test takes about real 9.340s. The median container creation time is 0.9415s, so twice as slow basically.

Some observations: c4.8xlarge creates more threads (perhaps because it notices it has more CPUs to play with?) Perhaps the threads are all contending with each other or something? Interestingly enough, when we limit Docker to one CPU it appears to perform better (but not 100% sure on this, just started testing - we spun up 1 cpu Digital Ocean machine and it did better than the 36 core AWS machine). Anyways, as an initial step I'd like to at the very least make my server Docker match my Macbook Air's performance. Below are the Docker infos:

MACBOOK AIR

Containers: 210
 Running: 0
 Paused: 0
 Stopped: 210
Images: 7
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 428
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-07-30T19:02:29.045775555Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

AWS

Containers: 103
 Running: 0
 Paused: 0
 Stopped: 103
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 208
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 58.97 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by thaJeztah** [comment]
actually; @icecrime didn't you find something in Go wrt performance on a single processor vs multi processor?

**Comment by icecrime** [comment]
@thaJeztah I do indeed, but I don't know if that the case here (see golang/go#15395).

**Comment by tolmasky** [comment]
So, I've put my AWS docker into one CPU mode by editing docker.service to be:

ExecStart=/usr/bin/taskset -c 16 /usr/bin/dockerd -D ...

I also added -D to match the debug mode that my Macbook Air docker is in.

docker info confirms that it now matches my Macbook Air setup (see below). The only real remaining differences now seem to be OS (Ubuntu vs Boot2Docker), the fact that docker is running in a VM on my Mac, and the fact that my mac has lower clock speed and memory. Would the OS difference make a huge difference here?

SType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 58.97 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-07-31T01:20:03.907639357Z
 EventsListeners: 0

**Comment by tolmasky** [comment]
Sorry, forgot to say the most important part: this has *not* changed the performance of the AWS docker.

**Comment by unclejack** [comment]
@tolmasky Docker makes it easy to move workloads around from one system to another. Docker uses features of the Linux kernel to spin up containers on the particular hardware it runs on. As you can imagine, it can't magically work around a kernel bug, faulty hardware or slow hardware.

The amount of time it takes to spin up a container depends on many things. A machine with one core might need more time to start a container than one with 6 cores. A machine with 16 cores might not require significantly less time to start a container than the one with 6 cores. 

A laptop with a 5400 RPM drive will need a lot more time to start a container than one equipped with a 500 MB/s SSD. Macbooks of all kinds have very fast SSDs these days. A cloud instance could be slower than a Macbook's internal SSD (depending on the type of the provisioned storage - HDD vs SSD).

In your case, it seems the performance issue is related to the performance of your disk. I really don't think you're running into one of Docker's performance issues here. I'm not implying there are or that there aren't such problems in the code base. A Docker container has been starting in the about the same amount of time for me over the years. It also doesn't seem that you're stressing the Docker daemon somehow with these tests.

Please feel free to take a look at the type of storage you've provisioned for your cloud instance. This should help you figure out what's going on.

**Comment by tolmasky** [comment]
Hi @unclejack, one of the first things we tried to rule out the storage possibility is running docker entirely in tmpfs. The machine has 60GB of ram and we made a dedicated 10gb tmpfs for it with no change in performance, so I believe that is not the issue here. Additionally, we can somewhat reproduce the performance slowdown locally (will be reporting back with more numbers soon). But suffice to say, docker-machine's boto2docker with one CPU is quick on our machines, but Ubuntu on a 2 CPU VM in the same computer is slow. This seems to match up with the bug mentioned above ( golang/go#15395 ), which would imply a Docker/go issue.

**Comment by pouwerkerk** [comment]
I was able to confirm this too. On the same VirtualBox VM, I changed the number of CPUs the VM could use and timed the same `docker run` command three times. I did this for 1-4 CPUs, but the speed slows by nearly 3x when going from a single core to two cores, and remains at that speed for all multi-core configurations I've tested.

**1 CPU**
```
$ time docker run mhart/alpine-node:latest node
real    0m 0.25s
user    0m 0.00s
sys     0m 0.00s
$ time docker run mhart/alpine-node:latest node
real    0m 0.22s
user    0m 0.00s
sys     0m 0.00s
$ time docker run mhart/alpine-node:latest node
real    0m 0.22s
user    0m 0.00s
sys     0m 0.00s
```

**2 CPUs**
```
$ time docker run mhart/alpine-node:latest node
real    0m 0.78s
user    0m 0.01s
sys     0m 0.00s
$ time docker run mhart/alpine-node:latest node
real    0m 0.63s
user    0m 0.00s
sys     0m 0.01s
$ time docker run mhart/alpine-node:latest node
real    0m 0.67s
user    0m 0.00s
sys     0m 0.01s
```

You can see the full results [here](https://gist.github.com/pouwerkerk/e5030558352d1dd8d5bd59c1bf740a30).

**Comment by capkurmagati** [comment]
I also tested this using 3 AWS instance: `t2.micro`, `t2.medium` and `c4.8xlarge`. 

|  Instance Type | vCPU  | Memory | Real Time| 
|---|---|---|---|
| t2.micro  |  1 | 0.5  | 0m5.707s/0m5.742s | 
| t2.medium | 2  | 4  | 0m6.831s/0m6.887s  | 
|  c4.8xlarge |  36 | 60  | 0m7.153s/0m7.219s  |

**Comment by icecrime** [comment]
I don't think there's anything to be done on Docker side unfortunately. I opened up the issue on Golang several months back and it's not getting much attention :cry:

**Comment by vincentwoo** [comment]
@icecrime I think it would be super relevant if you explained what the issue with Golang was and linked to it here.

**Comment by unclejack** [comment]
There seems to be an issue. alpine-node and the `node` command aren't the best choices for benchmarking container startup time. You probably want to stick to the `alpine` image and something such as `echo foo`. You're benchmarking the startup time of the node binary as well, but we're interested only in how long it takes to bring up the container.

**Comment by pouwerkerk** [comment]
@unclejack seems fair. I've rerun this test using the `alpine` image and `echo foo`, so that the results aren't inflated because of node startup time. The test was simply designed to be uniform, changing only the number of CPUs available to illustrate this effect where container startup time unexpectedly increases as the number of CPUs increases from one to multiple.

**1 CPU**
```bash
$ time docker run alpine echo foo
foo
real    0m 0.19s
user    0m 0.00s
sys     0m 0.00s
$ time docker run alpine echo foo
foo
real    0m 0.15s
user    0m 0.00s
sys     0m 0.00s
$ time docker run alpine echo foo
foo
real    0m 0.15s
user    0m 0.00s
sys     0m 0.00s
```
**2 CPUs**
```bash
$ time docker run alpine echo foo
foo
real    0m 0.62s
user    0m 0.01s
sys     0m 0.00s
$ time docker run alpine echo foo
foo
real    0m 0.59s
user    0m 0.01s
sys     0m 0.00s
$ time docker run alpine echo foo
foo
real    0m 0.59s
user    0m 0.00s
sys     0m 0.01s
```

Full results [here](https://gist.github.com/pouwerkerk/a04fb2e82407620ad44ce20ae72e0be3).

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
