### ISSUE TITLE
Image download fail due to network connection and can't re download

### ISSUE THREAD

**Issue by ShaneC-C-Y** [moby/moby#25264]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 2
 Paused: 0
 Stopped: 9
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: TDW5:YU6E:RY5E:VFTV:MKC7:AEQG:XEZY:H7CB:UOJB:7XI2:SKFN:XDBA
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 37
 Goroutines: 136
 System Time: 2016-07-31T03:00:57.123892292Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `$ docker build -t chienuyuc/catnip .`
I have a Dockerfile with `FROM python:3-onbuild` and it is my first time to download python:3-onbuild image.Command is `$ docker build -t chienuyuc/catnip .` However, the network connection fail during the download. So when next time tried to pull the python image, the download process always stop like that

**Describe the results you received:**

```
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM python:3-onbuild
3-onbuild: Pulling from library/python
5c90d4a2d1a8: Already exists 
ab30c63719b1: Already exists 
c6072700a242: Already exists 
abb742d515b4: Downloading [==============================>                    ]  78.4 MB/129.7 MB
7663bd2e167e: Download complete 
d0f49e193c5a: Download complete 
28969a7d8e03: Download complete 
7bf948f6f849: Download complete 
```

**Describe the results you expected:**
The expected results is re download and finish the download

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by aaronlehmann** [comment]
Thanks for the report.

Does the download always get stuck at the same place?

Do you only have the problem with this image, or do other images get stuck as well?

Do any error messages show up in the Docker daemon log when you try to pull this image?

**Comment by ShaneC-C-Y** [comment]
Thanks for the reply.
The download always starts and gets stuck at the same place as above.
I can download other images well, only the one stop in the middle due to internet fail works wrong, and there is no other error message show up.
The same thing happens in downloading python2, `abb742d515b4` is broken.

**Comment by aaronlehmann** [comment]
The only thing that I can think of is that the pull started by the build is still going on in the background, and it's stuck because of the network interruption. Restarting the Docker daemon should fix this.

A few things to try if this doesn't work:

- See if the `--max-concurrent-downloads` daemon option makes a difference. Try setting it to 1.
- If nothing else works, consider wiping or moving away `/var/lib/docker`. Note that **this will delete all your local images**.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
