### ISSUE TITLE
rpc error: code = 2 desc = "oci runtime error: exec failed: fork/exec /proc/self/exe: no such file or directory"[

### ISSUE THREAD

**Issue by anannaya** [moby/moby#25289]
I am seeing this issue on Docker 1.11.2  

```
[root@dockerhost ~]# docker -v
[root@dockerhost ~]# Docker version 1.11.2, build b9f10c9
```

```
 [root@dockerhost ~]# docker exec -it configcontainer bash
rpc error: code = 2 desc = "oci runtime error: exec failed: fork/exec /proc/self/exe: no such file or directory"[root@dockerhost ~]# 
[root@dockerhost ~]# 
[root@dockerhost ~]#
```

```
 [root@dockerhost ~]# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                         PORTS               NAMES
697ae23d35c3        10.43.44.217:5000/icmgwcafless_ab_2      "/root/install_docker"   About an hour ago   Exited (1) About an hour ago                       LI01
9b255a49867f        10.43.44.217:5000/consulagent            "consul agent -server"   About an hour ago   Up About an hour                                   CONSULSERVER01
38ff1eb0ad77        10.43.44.217:5000/cmrelay_60             "bash"                   About an hour ago   Up About an hour                                   CMRELAYMASTER01
42ed84f20dc9        10.43.44.217:5000/glusterfs              "/usr/sbin/init"         About an hour ago   Up About an hour                                   gluster_client
d6b805fe469e        10.43.44.217:5000/config_configurator    "/bin/sh -c /opt/swre"   8 days ago          Up About an hour                                   configcontainer
1df60644b6d1        10.43.44.217:5000/network_configurator   "/bin/sh -c /opt/swre"   8 days ago          Up About an hour                                   znetworkcontainer
```

```
 [root@dockerhost ~]# docker restart configcontainer 

Error response from daemon: Cannot restart container configcontainer: rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker/devicemapper/mnt/32c34746be3668240c3e2336c18039cb32ad80f7994e28cfffdaaaa0521751fa/rootfs\") does not exist"
```

```
 [root@dockerhost ~]# docker ps -s
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES               SIZE
9b255a49867f        10.43.44.217:5000/consulagent            "consul agent -server"   About an hour ago   Up About an hour                        CONSULSERVER01      274.7 kB (virtual 1.463 GB)
38ff1eb0ad77        10.43.44.217:5000/cmrelay_60             "bash"                   About an hour ago   Up About an hour                        CMRELAYMASTER01     0 B (virtual 1.489 GB)
42ed84f20dc9        10.43.44.217:5000/glusterfs              "/usr/sbin/init"         About an hour ago   Up About an hour                        gluster_client      -1 B (virtual 260.1 MB)
1df60644b6d1        10.43.44.217:5000/network_configurator   "/bin/sh -c /opt/swre"   8 days ago          Up About an hour                        networkcontainer    -1 B (virtual 378.2 MB)
```

**Comment by anannaya** [comment]
[docker_logs.txt](https://github.com/docker/docker/files/393720/docker_logs.txt)
[var_log.txt](https://github.com/docker/docker/files/393719/var_log.txt)

**Comment by thaJeztah** [comment]
can you add the output of `docker version` (not `docker --version`), and `docker info` as well?

**Comment by anannaya** [comment]
[root@dockerhost ~]# docker -v
Docker version 1.11.2, build b9f10c9
[root@dockerhost ~]# docker info
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-135083487-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.235 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.7 GB
 Metadata Space Used: 9.142 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: dockerhost
ID: LVR4:JHJD:7K6N:QAWZ:WPYI:NMLV:2Y3N:AEZ6:EQ37:5STY:VYQT:76KT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
[root@dockerhost ~]#

**Comment by anannaya** [comment]
PLease let me is there any bug in devmapper side.. I have tried direct LVM as well. Still the same issue seen.

**Comment by thaJeztah** [comment]
Are you having this issue only with that container/image, or with any container/image?

**Comment by anannaya** [comment]
I faced this issue with 2 container images... May i am mounting 2 many parameters.. Is this causing?
#docker create -t --privileged  --restart=unless-stopped --net=host -v /opt/swrepo/vmtools.conf:/opt/swrepo/vmtools.conf -v /var/run/docker.sock:/var/run/docker.sock -v /etc/sysconfig/network-scripts:/etc/sysconfig/network-scripts -v /etc/sysconfig/docker:/etc/sysconfig/docker -v /root/.ssh:/host/ssh -v /etc/sysconfig/network:/etc/sysconfig/network  -v /dev:/dev/ -v /etc/fstab:/etc/fstab -v /etc/hosts:/etc/hosts -v /lib/modules:/lib/modules --name configcontainer 10.43.44.217:5000/config_configurator

**Comment by thaJeztah** [comment]
The number of parameters should not matter, but bind-mounting some directories, such as `/dev` inside the container, especially with a `--privileged` container is really dangerous, basically, you're giving the container full access on the host, and allow it to mess with those directories (which can have all kinds of side-effects); see also

https://github.com/docker/docker/issues/17865 (https://github.com/docker/docker/issues/17865#issuecomment-232621655), https://github.com/docker/docker/issues/19464#issuecomment-173269279,

So it *could* be related

Also, be aware that if you're trying to bind-mount a *file* into the container, and the file doesn't exist, that docker creates a *directory* with that name and tries to bind-mount it into the container, which may result in strange things if there's actually a *file* with the same name in the container. We're improving the error message for those situations in 1.13 (see https://github.com/docker/docker/pull/24754)

**Comment by anannaya** [comment]
This issue especially i am seeing with Docker version 1.11.2.. not seen in older versions.

**Comment by anannaya** [comment]
Could you suggest me something on this issue... I am not able to exec to any of the container. 
I tried restart of docker service and container. Tried the Host reboot as well.
Still the same issue.. Could you help in come out of this problem.

**Comment by thaJeztah** [comment]
I suggest to try and narrow down the cause by starting with a very minimal container (and `docker run` options), then see what option causes docker to fail.

As mentioned, you're giving the container full access to a lot of locations on your host, and bind-mounting `/dev` is known to cause issues as well. I'm not sure we'd be able to help, because this may be specific to your machine and/or the image you're using (which is not public)

**Comment by anannaya** [comment]
@thaJeztah  Thanks .. But Is  Docker does not supports /dev bind mout inside the container?
I have reinstalled the docker rpms ..this issue resolved..I really dont know what was causing it.

**Comment by anannaya** [comment]
@thaJeztah  :  I avoided using /dev mount inside the container, Some of the issues are resolved.
I have problem with glusterfs container ,where i am running systemd inside contianer.  rpc error occurs when i use the --net=host option ... I have disabled the all the services except glusted  Could you suggest what might be wrong here.

**Comment by sam-thibault** [comment]
this is an old issue.  I will close it as stale.
