### ISSUE TITLE
Suggestion for a more secure use of the docker group (documentation)

### ISSUE THREAD

**Issue by ricardobranco777** [moby/moby#25299]
Instead of adding users to the **_docker_** group as the [Installation manuals](https://docs.docker.com/engine/installation/#installation) suggest, which is a security hole by definition and antonomasia, I think it's better to add a password to the **_docker_** group and use the **sg** and **newgrp** commands as follows:

Add a password to **_docker_** group:
`gpaswd docker`

Create a session with the **_docker_** group added to the supplementary group ID's:
`sg docker newgrp $(id -gn)`

At this point the user may run **docker** commands...

Logout:
`exit`

Note: The **sg** command is needed to avoid running the sequence: `newgrp docker` and then `exec newgrp $USER`

On the plus side, there's no need to use **sudo** anymore with its side-effects of resetting environment variables, etc.

**Comment by ricardobranco777** [comment]
We're assuming the same group name for the user.  The command may be:

 `sg docker newgrp $(id -gn)`.

**Comment by thaJeztah** [comment]
ping @tianon @diogomonica ptal

**Comment by diogomonica** [comment]
Not exactly sure how this helps. If the user still has unrestricted access to Docker, then it can still escalate privileges, right? What am I missing?

**Comment by ricardobranco777** [comment]
@diogomonica  The goal is that the user opens a session with the docker group (protected by a password), run docker commands and then exit.

With the docker group being added as suggested by the documentation, any process (a web browser plugin, for example) can escalate privileges.

My point is to password protect the docker group.

**Comment by diogomonica** [comment]
And my point is that as it stands, if you don't use an authorization plugin that restricts API access, you might as well sudo to root.

**Comment by ricardobranco777** [comment]
**sudo** has the annoying side effects of resetting environment variables.  **sg** is predictable and no special configuration is needed.

**Comment by neersighted** [comment]
I'm going to close this as a Linux system administration issue; the socket file is managed using standard permissions and ACLs, and how the user chooses to escalate to the `docker` group is up to them.
