### ISSUE TITLE
Flannel install command hangs

### ISSUE THREAD

**Issue by Deepak-Vohra** [moby/moby#25301]
**Output of `docker version`:**

```
sudo docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
ubuntu@ip-172-30-1-24:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: ip-172-30-1-24
ID: BADX:JASO:3JP3:AM7S:EXD4:GGCM:PEJQ:R5D2:MCJZ:TCWP:BZNA:NUN7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
ubuntu@ip-172-30-1-24:~$ 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 Instance AMI Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-2d39803a
Instance type
m3.2xlarge

**Steps to reproduce the issue:**
1. Create a AWS EC2 instance  and login.
2.Install Docker. Install etcd. 
`sudo sh -c 'docker daemon -H unix:///var/run/docker-bootstrap.sock -p /var/run/docker-bootstrap.pid --iptables=false --ip-masq=false --bridge=none --graph=/var/lib/docker-bootstrap 2> /var/log/docker-bootstrap.log 1> /dev/null &'`

`sudo docker -H unix:///var/run/docker-bootstrap.sock run --net=host -d gcr.io/google_containers/etcd:2.0.13 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data`

`sudo docker -H unix:///var/run/docker-bootstrap.sock run --net=host gcr.io/google_containers/etcd:2.0.13 etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'`

`sudo service docker stop`
1. Run following command to install Flannel 
   `sudo docker -H unix:///var/run/docker-bootstrap.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5`

**Describe the results you received:**

Command hangs with following output:

```

sudo docker -H unix:///var/run/docker-bootstrap.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5
Unable to find image 'quay.io/coreos/flannel:0.5.5' locally
0.5.5: Pulling from coreos/flannel
7bfac8493465: Already exists 
a3ed95caeb02: Pull complete 
fdaeea203ca1: Pull complete 
1f0ee8606937: Pull complete 
Digest: sha256:1cb2d3569d19c3c9da3293cbaed3399aec1da61c3e146d5c41ae9344e76cf051
Status: Downloaded newer image for quay.io/coreos/flannel:0.5.5
9cd468e356f68770791ebd14123f2137f119485104a00766404f66d098907415
```

**Describe the results you expected:**

The command should complete after the download is complete.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens each time tested; tested 2-3 times over 2 days. CPU could not be the issue as same result with EC2 Instance Type hs1.8xlarge, the largest available.

**Comment by thaJeztah** [comment]
Do the daemon logs show anything useful? Note that running a multi-daemon setup is considered experimental, some hints can be found here; https://docs.docker.com/engine/extend/plugins/#/volume-plugins

(e.g., I see you don't specify `--exec-root`), perhaps those instructions are outdated?

**Comment by dvohra** [comment]
The multi-daemon setup is for Kubernetes.  Even the latest documentation does not list `--exec-root`
http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/

Should the command be:

sudo docker -H unix:///var/run/docker-bootstrap.sock run -d \
    --net=host \
    --privileged \
    -v /dev/net:/dev/net \
    quay.io/coreos/flannel:${FLANNEL_VERSION} \
    /opt/bin/flanneld \
        --ip-masq=${FLANNEL_IPMASQ} \
        --iface=${FLANNEL_IFACE}
       --exec-root

**Comment by thaJeztah** [comment]
no, the `--exec-root` is an option for `dockerd` / `docker daemon` when starting the "bootstrap" daemon. I'm not even sure if kubernetes already supports docker 1.12; looks like they're still testing https://github.com/kubernetes/kubernetes/issues/28698. Perhaps open an issue in the kubernetes issue tracker?

**Comment by dvohra** [comment]
Docker 1.12 is supported according to 
"You need to have Docker version >= “1.10” installed on the machine."
http://kubernetes.io/docs/getting-started-guides/docker/

Validation with 1.12 could still be having some issues.

**Comment by thaJeztah** [comment]
I just created a new ubuntu 14.04 host and ran those commands, and got the same result (the command hanging after the container was started).

However, when properly configuring the `--exec-root` for the bootstrap daemon, the command completed succesfully, so this appears to be a documentation issue in the kubernetes docs.

Basically, with these steps;

```bash
# install docker
curl -fsSL https://get.docker.com | sh

# create the exec-root dir (to be sure it exists, but may be optional)
sudo mkdir -p /var/run/docker-bootstrap

# start the bootstrap daemon
sudo sh -c 'docker daemon -H unix:///var/run/docker-bootstrap.sock -p /var/run/docker-bootstrap.pid --exec-root=/var/run/docker-bootstrap --iptables=false --ip-masq=false --bridge=none --graph=/var/lib/docker-bootstrap 2> /var/log/docker-bootstrap.log 1> /dev/null &'

sudo docker -H unix:///var/run/docker-bootstrap.sock run --net=host -d gcr.io/google_containers/etcd:2.0.13 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data

sudo docker -H unix:///var/run/docker-bootstrap.sock run --net=host gcr.io/google_containers/etcd:2.0.13 etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'

sudo service docker stop

sudo docker -H unix:///var/run/docker-bootstrap.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5
```

I also note that the kubernetes docs include changing the docker unit file for systems running on systemd;

```
shell DOCKER_CONF=$(systemctl cat docker | head -1 | awk '{print $2}') sed -i.bak 's/^\(MountFlags=\).*/\1shared/' $DOCKER_CONF systemctl daemon-reload systemctl restart docker
```

I would strongly suggest to not modify the unit file, and use a systemd drop-in file instead; modifying the unit file will result in issues when an updated version of the unit file needs to be installed when upgrading docker to a newer version. (see https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
