### ISSUE TITLE
Docker run freezes host os if images are on ntfs filesystem

### ISSUE THREAD

**Issue by nikhilw** [moby/moby#25328]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 43
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /home/nikhil/DockerImages/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.712 GiB
Name: WORK-MACHINE
ID: ##########################
Docker Root Dir: /home/nikhil/DockerImages
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N.A.

**Steps to reproduce the issue:**
1. On a Linux (Mint 17.3) machine.
2. Edit `/etc/default/docker` and change `DOCKER_OPTS`, adding `-g` to point to a directory in a partition with NTFS filesystem. Ex.: `DOCKER_OPTS="-g /media/Data/DockerImages"`
2. Restart docker daemon
3. execute `docker run ubuntu`

**Describe the results you received:**
Host operating system freezes, no keypresses are registered and hard reset is the only way out.

**Describe the results you expected:**
Should either throw error saying the filesystem cannot be used, or should work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Moving the directory to an ext4 filesystem works fine; which currently is the path visible in the info above. `/media/Data` in the example above is not a removable drive.

**Comment by thaJeztah** [comment]
Thanks for reporting; we currently use a "blacklist" of backing-filesystems that are known to be incompatible, but we are not able to test every possible combination.

Perhaps we should switch to a "whitelist", although that may block combinations that *do* work, but are untested.

Possibly, we can add a daemon flag to override that check `--storage-opt i-know-what-im-doing-dont-check`

**Comment by tfpereira** [comment]
+1 What's the current state of this issue? Just ran into this problem when I tried to migrate my images to a ntfs filesystem

**Comment by thaJeztah** [comment]
@tfpereira I don't think someone is looking into this currently.

ping @dmcgowan @jhowardmsft may know more

**Comment by jhowardmsft** [comment]
@thaJeztah I'm not sure this has anything to do with NTFS in the Windows sense...

**Comment by cpuguy83** [comment]
People are using ntfs for critical things on Linux? That's scary.

If someone wants to do a statfs and graph the magic number for ntfs we can try and detect it.... but who knows if it will work.

**Comment by nikhilw** [comment]
@cpuguy83 Well, not intentionally, but when you dual boot, your largest drive tends to be a partition which can be used in both OSs and OS partitions tend to be small. NTFS is the natural choice for this drive, among FAT32, NTFS and ext4. And when you keep on downloading images, eventually you need to move them out of OS partition and you encounter this issue! :D

**Comment by GurvanKervern** [comment]
I have the same problem, although my host OS doesn't freeze, but docker does (an "auplink one-of-the-container-filesystems flush" child of dockerd is blocked in state D, and docker doesn't respond to any command after that : search, ps, etc )

I think it did not happen before, as I could have sworn I had my -g option pointing to a NTFS partition before and things were ok before version X (forgot which one) (and this started to happen right after an upgrade of docker-engine through apt)

**Comment by jhowardmsft** [comment]
@GurvanKervern Can you open a new issue - I can't see that what you put above is related to this issue.

In the new issue, please describe the symptoms, what you have done prior to it, output of docker info and docker version. If the system is still in this state with the daemon not responding to `docker ps` (a common symptom of a deadlock behind the global container lock), also attach the stack-dumps from the daemon using https://github.com/jhowardmsft/docker-signal  - run as `docker-signal -pid=nnnnn` where nnnn is the process ID of the daemon.

**Comment by theoden-dd** [comment]
Confirm the bug of aufs upon ntfs on Ubuntu 16.04.
Moved `/var/lib/docker/` to my big ntfs partition and had that system-wide freezes. Poor ubuntu even couldn't restart in a clean way: hanged on stopping container engine and unmounting aufs.

[Switching to devicemapper](https://github.com/moby/moby/issues/19336#issuecomment-211864264) **solved the issue**. That's just a workaround, however.

Docker version:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-8:17-553498-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.408GB
 Data Space Total: 107.4GB
 Data Space Available: 105GB
 Metadata Space Used: 2.552MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /media/theoden/dataz/docker/devicemapper/devicemapper/data
 Metadata loop file: /media/theoden/dataz/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.748GiB
Name: ThunderBluff
ID: HBZL:6MYN:WIHS:HJNE:WSLB:4X2H:AHSI:72VV:NMTY:O7UT:F3G2:5NHA
Docker Root Dir: /media/theoden/dataz/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
What driver is being used for ntfs? I'm assuming ntfs-3g fuse driver?

**Comment by theoden-dd** [comment]
From fstab: 
```
UUID=6D3DC1C18177A808 /media/user/dataz ntfs rw,nosuid,nodev,allow_other,default_permissions,uid=1000,gid=1000,fmask=0077,dmask=0077 0 0
```
I guess that's for ntfs-3g

**Comment by cpuguy83** [comment]
So I remember looking at this before now... the issue is this is a fuse fs. I'm not sure how to detect beyond fuse, what the underlying fs is. We could just block all FUSE on AUFS but I would be worried about breaking people then.

**Comment by thaJeztah** [comment]
closing as this one went stale

**Comment by t0stiman** [comment]
closed without a solution :|

**Comment by GurvanKervern** [comment]
> closed without a solution :|

agreed, I had to convert my main data partition from ntfs to ext4 just to avoid docker filling my main partition with images. But as a result I can't access that partition (easily) when I do boot on Windows, so I also had to move some voluminous video games on another partition first because ntfs suddenly caused a problem for using some tools on Linux, like in 2005. I think many people like to multi-boot if only for video games and usually access ntfs from Linux/Unix rather than the other way around. Docker is a great application but this is a bit annoying.

**Comment by t0stiman** [comment]
@GurvanKervern i managed to get my docker data on an NTFS partition by using the Device Mapper storage driver. Instead of placing this:
```json
{
  "data-root": "/path/to/dockerdata"
}
```
in `/etc/docker/daemon.json`, use:
```json
{
    "graph": "/path/to/dockerdata",
    "storage-driver": "devicemapper"
}
```
It seems to work but now i get a warning that device mapper is deprecated. If anyone knows a better way, I'd love to hear about it...

**Comment by seamlik** [comment]
Confirmed that `fuse-overlayfs` works on NTFS.

**Comment by rakshith95** [comment]
@seamlik how did you change it to use `fuse-overlayfs` ?

**Comment by seamlik** [comment]
@rakshith95 

Just changed `storage-driver` in `daemon.json`, then turn `/var/lib/docker` into a symlink pointing to an NTFS directory.

However, since NTFS does not support the execution permission, a lot of things are still broken.
