### ISSUE TITLE
test-integration-cli for userns don not use DockerDaemonSuite

### ISSUE THREAD

**Issue by keloyang** [moby/moby#25355]
I find that test-integration-cli for janky has 1403 testcases,  and userns has only 1091 testcases
eg. https://github.com/docker/docker/pull/25341
janky      19:53:40 OK: 1363 passed, 40 skipped
userns    19:13:38 OK: 967 passed, 124 skipped

Actually all testcases in DockerDaemonSuite are not being executed for userns, but I don't know why.
at the same time , if DockerDaemonSuite is executed,  I think we need the change to adapt userns testcases:

```
 func (d *Daemon) Start(args ...string) error {
+       if root := os.Getenv("DOCKER_REMAP_ROOT"); root != "" {
+               d.root = filepath.Dir(d.root)
+       }
        logFile, err := os.OpenFile(filepath.Join(d.folder, "docker.log"), os.O_RDWR|os.O_CREATE|os.O_APPEND, 0600)
        d.c.Assert(err, check.IsNil, check.Commentf("[%s] Could not create %s/docker.log", d.id, d.folder))

@@ -340,9 +343,7 @@ func (d *Daemon) Restart(arg ...string) error {
        // remapped root is added--we need to subtract it from the path before calling
        // start or else we will continue making subdirectories rather than truly restarting
        // with the same location/root:
-       if root := os.Getenv("DOCKER_REMAP_ROOT"); root != "" {
-               d.root = filepath.Dir(d.root)
-       }
+
        return d.Start(arg...)
 }
```

**Comment by coolljt0725** [comment]
ping @vdemeester  @thaJeztah

**Comment by vdemeester** [comment]
@estesp probably knows more but `DockerDaemonSuite` does not run for userns because docker does run inside usernamespace. There is a PR to fix that though : https://github.com/docker/docker/pull/20902 ! With that PR we should be able to re-activate some `DockerDaemonSuite` 'tests.

**Comment by keloyang** [comment]
https://github.com/docker/docker/pull/20902 and https://github.com/docker/docker/pull/25672 are about running engine daemon inside a user namespace, the userns' testcase about DockerDaemonSuite are run a user namespace engine daemon inside a docker container, they are not conflict, so why Docker-PRs-userns configure has "-e TESTFLAGS='-check.f DockerSuite' " to skip DockerDaemonSuite ?
ping @estesp @vdemeester

**Comment by estesp** [comment]
@keloyang it is mostly about duplicating test runs that do nothing different than the "non-userns" case--only the `DockerSuite` tests are running against a single started daemon with user namespaces enabled. The rest of the suites either start their own daemon or test something without user namespaces that is unrelated. So, for the user namespaces "CI" the only part of the overall test suite that makes sense to actually test user namespace support is running `DockerSuite` with the user namespace mapping enabled.
