### ISSUE TITLE
Alpine seccomp support absent from documentation

### ISSUE THREAD

**Issue by WhisperingChaos** [moby/moby#25377]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.13.0-74-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
Name: 8ec66a261c28
ID: N3UI:RKZ2:VB4H:JSIZ:7WWV:B6RJ:5VQP:KYT2:4S54:534L:46UT:SZZB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running Docker in Docker (dind).
Also, applies to dind  version 1.10.1

**Steps to reproduce the issue:**
1.  `docker info`

**Describe the results you received:**
`docker info` reports `seccomp` support: `Security Options: apparmor seccomp`.
The unexpected application of the default seccomp profile caused failure in Chrome container started by Alpine dind container.

**Describe the results you expected:**
Didn't expect application of default seccomp profile when running containers started by Alpine dind container.  According to the [seccomp documentation](https://docs.docker.com/engine/security/seccomp/),

> Note: seccomp profiles require seccomp 2.2.1 and are only available starting with Debian 9 “Stretch”, Ubuntu 15.10 “Wily”, Fedora 22, CentOS 7 and Oracle Linux 7. To use this feature on Ubuntu 14.04, Debian Wheezy, or Debian Jessie, you must download the latest static Docker Linux binary. This feature is currently _not_ available on other distributions.

Alpine Linux should not offer seccomp support but it does.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
The docker-in-docker images use a static binary, therefore support seccomp

**Comment by WhisperingChaos** [comment]
Yes, I realize this is again a small nit but, at best, the _"Note"_ above is misleading as it clearly indicates: _"This feature is currently not available on other distributions."_ which refers to this list of Linux distributions:  Debian 9 “Stretch”, Ubuntu 15.10 “Wily”, Fedora 22, CentOS 7 Oracle Linux 7, Ubuntu 14.04, Debian Wheezy, and Debian Jessie which is enumerated immediately before this statement.  This list fails to include the Alpine distribution which does support seccomp profiles.

If support simply requires the latest static Docker Linux binary for any Linux distribution whose kernel includes seccomp then just remove the note.

**Comment by justincormack** [comment]
The Alpine 3.4 distro docker packages also support seccomp.

Generally it is not as simple as kernel support, it also depends on the
libseccomp library version in the distro.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
