### ISSUE TITLE
RPC error running container: rootfs does not exist

### ISSUE THREAD

**Issue by mwhouser** [moby/moby#25382]
**Output of `docker version`:**

```
Client:
Version: 1.11.2
API version: 1.23
Go version: go1.5.3
Git commit: b9f10c9/1.11.2
Built: 
OS/Arch: linux/amd64

Server:
Version: 1.11.2
API version: 1.23
Go version: go1.5.3
Git commit: b9f10c9/1.11.2
Built: 
OS/Arch: linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: devicemapper
Pool Name: docker-202:1-263574-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 482.5 MB
Data Space Total: 107.4 GB
Data Space Available: 6.536 GB
Metadata Space Used: 1.114 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.146 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
Volume: local
Network: bridge null host
Kernel Version: 4.4.11-23.53.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: ip-172-31-23-137
ID: LVEV:HTNL:E4U5:E7NM:QD67:MZKK:3BMB:TUDL:VO5G:QCUR:NPEJ:UXNP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Amazon Web Services using Amazon Linux.

**Steps to reproduce the issue:**
1. `service docker stop`
2. `service docker start`
3. `docker version` (not required)
4. `docker info` (not required)
5. `docker run -v /mnt:/mnt:rw myimage`

**Describe the results you received:**

The container does not run. Instead, I get an error message:

>  docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker/devicemapper/mnt/4b6a50d59a0f562ae80249167f7b35f44b4a1b1644618fa1a28a1fb8d424a4c5/rootfs\") does not exist".

**Describe the results you expected:**

I would hope the container would run.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue is intermittent (only happens occasionally).

I have attempted to add `sleep` commands between the commands to see if it helps. If there are no `sleep` commands at all, then it seems to happen more frequently. However, even with `sleep` commands, this issue happens around 1 out of 20 times.

I am able to execute `docker version` and `docker info` immediately before the failure (as seen in my steps to reproduce).

If I do not perform the stop and start of docker, then `docker run` will hang indefinitely (intermittently).

**Comment by nathan-v** [comment]
I'm running into this exact same issue today on an Amazon Liunux AMI that is completely up to date after being freshly launched. After a reboot the issue did not persist.

**Comment by afoldesi-gds** [comment]
Ran into the same issue today. 

It's especially painful as it has happened after an automatic update cron job, eg.
sudo yum update -y ecs-init
sudo service docker restart
sudo start ecs

After this the docker daemon fails to restart at all (even when manually started) - Although it says it's started OK, the docker commands fail as if it wasn't. It's only 1 out of 6 servers, but still.

I'm going with

docker ps || sudo reboot

for now, and hope that rebooting will always fix the issue. Not a happy place to be.

**Comment by cwkinard** [comment]
Ran into issue as well on RHEL 7.2 using devicemapper, direct LVM.

`docker info`

`Containers: 31
 Running: 31
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 1.11.2-cs5
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 9.733 GB
 Data Space Total: 71.4 GB
 Data Space Available: 61.67 GB
 Metadata Space Used: 4.469 MB
 Metadata Space Total: 750.8 MB
 Metadata Space Available: 746.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 13.7 GiB
Name: app2-dev400
ID: A2QV:NQB7:2WCR:4T7N:HZTU:YFJV:3EYV:6ASV:R6GJ:PIRK:AAU7:7BY3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
 File Descriptors: 208
 Goroutines: 314
 System Time: 2017-02-03T11:54:28.245250276-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 xxxxxxxxxxxxxxxx
Cluster store: consul://localhost:8500
Cluster advertise: 10.86.241.11:2376`

A restart of the daemon fixes the issue.

**Comment by thaJeztah** [comment]
Is anyone still running into this on a current version of Docker? Docker 1.11 has reached EOL almost a year ago, and a lot of things have changed. Also note that Amazon Linux is not a supported platform (Docker does not ship packages for Amazon Linux); if you're running into this on Amazon Linux, your best point of entry would be to contact Amazon support, as they maintain those packages, and should provide support for that.

@cwkinard I see you're running the CS (commercially supported) version of Docker; if you have a support contract, and are running Docker CS / Docker EE; it's best to contact your support representative.

**Comment by thaJeztah** [comment]
closing as this one went stale
