### ISSUE TITLE
Its hard to remove particular container by filter

### ISSUE THREAD

**Issue by usultrared** [moby/moby#25390]
**Output of `docker version`:**

Sams-MacBook-Pro:default samchen$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Sams-MacBook-Pro:default samchen$ docker info
Containers: 39
 Running: 0
 Paused: 0
 Stopped: 39
Images: 226
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 318
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: bqo9wjuolar5qk0qm8v3nnmg1
 Is Manager: true
 ClusterID: f350z8ybay7jshcq2k97rilnw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: W7NK:RAXS:XQ7B:NA3W:HHTC:6UJJ:6E4R:PRTR:WLID:ZTP7:NIIP:5ARH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 121
 System Time: 2016-08-04T05:07:11.825339259Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. there are so many docker instances going there
2. I want to delete some instance by filter , like created time, status, ports etc 
3. I need to use awk/sed to make it happen, like "docker rm `docker ps | awk ....".  This is useless and complicated.  Can we add filter ?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by icecrime** [comment]
Did you check the reference for [`docker ps`](https://docs.docker.com/engine/reference/commandline/ps/#/filtering)? It supports filtering on id, label, name, existed, status, etc. This allows for things such as `docker rm $(docker ps --filter "label=color=blue" -q)`.

Let me know if that helps, and if there's some filter types we should be adding.

**Comment by usultrared** [comment]
Actually I am saying "docker rm --filter "label=color=blue". Would it be helpful?

**Comment by thaJeztah** [comment]
I think this is related to https://github.com/docker/docker/issues/9054, which also asks for adding a filter option to `docker rmi`

**Comment by thaJeztah** [comment]
Also Relates to https://github.com/docker/docker/issues/22871

**Comment by algorithme** [comment]
Currently working on adding the --filter option to `rm`. Once it's done, I'll consider whether there are enough filters supported or if we should extend.

**Comment by krasi-georgiev** [comment]
@thaJeztah 
docker rm --filter=
docker rmi --filter=

is there a plan to add these and is anyone working on it ?

I want to give it a try.

**Comment by thaJeztah** [comment]
don't think anyone else is working on it, but we should take the `docker prune` commands into account and see if there would be an overlap in functionality; we can discuss that on the PR of course

**Comment by krasi-georgiev** [comment]
@thaJeztah 
Would you need to discuss it with the maintainers first or it is ok if add the new code ? I mean I don't want to invest the time unless this is something you want to add to docker

**Comment by thaJeztah** [comment]
ping @mlaventure WDYT?

**Comment by mlaventure** [comment]
@thaJeztah I think now it'd make more sense within `docker image/container prune` than `docker rm`

We can leave `docker rm` to delete images explicitly, whereas `prune` has a far reaching hands according to possible filters (which don't exist atm).

**Comment by krasi-georgiev** [comment]
@mlaventure so shall I implement docker prune --filter or wait until it is requested by some use case ?

**Comment by mlaventure** [comment]
@krasi-georgiev feel free to make a PR for it!

Keep in mind that there's several prunes though: `image prune`, `container prune`, `volume prune` and `network prune` atm.

Some of the filters can be applied to all of them, some will be specific to the category being pruned.

It'd be great if you could avoid some code duplication for the common one.

**Comment by krasi-georgiev** [comment]
@mlaventure I looked through the code the seems that most filters are already implemented just not documented so probably can close this. 

--filter filter   Provide filter values (e.g. 'until=<timestamp>')

only volumes are missing it , but at the moment volume created doesn't save creation date so can't be used with the "until" filter

**Comment by thaJeztah** [comment]
@krasi-georgiev it's not "documented" on docs.docker.com, because it's only available in "master" docs for master are in [docs/reference/commandline/system_prune.md#filtering](https://github.com/docker/docker/blob/52df69f00d966904ba230dc2e3a0646cc52b7688/docs/reference/commandline/system_prune.md#filtering). 

However, it looks like the only filter is currently `until`, so we may want to think of adding filters such as filter by _label_, and possibly _name_ patterns

**Comment by krasi-georgiev** [comment]
@thaJeztah sure I can do a pull request if you let me know what other filters should be there.

**Comment by krasi-georgiev** [comment]
@thaJeztah ok I will open a pull request

**Comment by thaJeztah** [comment]
@krasi-georgiev oh, actually, it looks like work is in progress for label filtering :blush: https://github.com/docker/docker/pull/30740

**Comment by krasi-georgiev** [comment]
@thaJeztah  ok ,great
