### ISSUE TITLE
Explain what `docker run` does under the hood

### ISSUE THREAD

**Issue by sa2ajj** [moby/moby#254]
**Summary**: The documentation does not explain what `docker run` does under the hood.

**Proposed solution**: Add documentation to explain in reasonable detail what `docker run` does.

Some useful links:
- https://docs.docker.com/reference/commandline/cli/#run
- https://docs.docker.com/reference/commandline/cli/#create
- https://docs.docker.com/reference/commandline/cli/#start
- https://github.com/docker/docker/blob/master/image/spec/v1.md
- https://github.com/docker/libcontainer/blob/master/SPEC.md
# 

**Original comment**:
I think it would make a good addition to the documentation to explain what exactly happens when a user issues `docker run`

**Comment by cpuguy83** [comment]
@fredlf Did this ever happen?

**Comment by fredlf** [comment]
@cpuguy83 No, sorry, I never finished it. It's on my backlog. We finally hired some help, so maybe I'll be able to move forward on some of these side-project sorts of things.

**Comment by funkyfuture** [comment]
we came over some unclear phrasing about volumes in context with the `run`-command (or rather the `RUN`-directive) in [a discussion](https://github.com/samos123/docker-drupal/issues/10), to quote myself:

> actually, referring to [this documentation](https://docs.docker.com/reference/builder/#volume) the behaviour you describe (the empty `…/all/modules`-folder in your `Dockerfile`), which i can reproduce,  would rather be a bug:

>> The docker run command initializes the newly created volume with any data that exists at the specified location within the base image. (...) This Dockerfile results in an image that causes docker run, to create a new mount point at /myvol and copy the greating file into the newly created volume.

> As the `run`-command wasn't invoked at the time of the build, there wouldn't be any volume intialized. and when this will happen, the content at the mount-point of the image will be copied into the volume. or am i getting something very wrong here?

as a response to [this case](https://gist.github.com/cerisier/b14c0f79d0a6ba2332dc).

so, i'd have these questions to be clarified:
1. does a `RUN`-directive in a `Dockerfile` do the same as a `docker run`?
2. if so, why would it be useful that it initializes volumes in the same way?

or is it a bug we stumbled over here?

**Comment by cpuguy83** [comment]
@funkyfuture 
1) Yes, `docker run` and `RUN` in a Dockerfile are equivelent.
2) It's not useful and there have been a few attempts to resolve this, none of which have been particularly acceptable.

**Comment by funkyfuture** [comment]
@cpuguy83 thanks, can you hint me to an issue or PR regarding 2) to follow?

**Comment by AkihiroSuda** [comment]
Is this issue closable?

docker-containerd-runc model has been explained in a bunch of documents / presentations / whatever :smile:

**Comment by vdemeester** [comment]
Given the activity on that one, I think it's closeable and thus I will close it 👼
