### ISSUE TITLE
Incorrect default PID value? 

### ISSUE THREAD

**Issue by innocentme1** [moby/moby#25412]
This is in reference to PIDs cgroup limit https://github.com/docker/docker/pull/18697 

I am confused. Whats the default value for PIDs cgroup limit? below link says setting the value to -1 allows unlimited processes to be forked
Ref:  https://docs.docker.com/engine/reference/commandline/run/

But i was checking on my machine and the default value for it is "0" in which situation its allowing me to do unlimited forks. First two containers dont have any PIDs limit set and by default it was '0'.

Ref: docker ps --quiet | xargs docker inspect --format '{{ .Id }}: PidsLimit={{ .HostConfig.PidsLimit }}'
\60b19cf162aaa262765608f1533d0532c324f03a2f5e1701d5d98392da624802: PidsLimit=0
6f8a8454a6f23d29163a22ee9533756d706382bbe3ba467f11f80f3e6489fd4b: PidsLimit=0
8f2ecc51968d29010d6b6dc58bbfcf7fb4dc4ef52b465f04ff1a37e7ed7e734a: PidsLimit=512

**Comment by icecrime** [comment]
Ping @LK4D4!

**Comment by justincormack** [comment]
Both 0 and -1 are treated as "max"

https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/pids.go#L29

Setting to zero would mean allow no processes, which would be fairly pointless, so 1 for no forking is the sane minimum.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
