### ISSUE TITLE
[swarm] swarm cluster didn't recover upon VM restart (rpc error: code = 2 desc = raft: no elected cluster leader)

### ISSUE THREAD

**Issue by rogaha** [moby/moby#25431]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: active
 NodeID: 2jml8zh2ap8gnw3ghchc03g09
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot interval: 0
  Heartbeat tick: 0
  Election tick: 0
 Dispatcher:
  Heartbeat period: Less than a second
 CA configuration:
  Expiry duration: Less than a second
 Node Address: 192.168.99.100
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: master1
ID: XFBC:QIPK:ZJH5:MGSZ:D6IA:32XG:TUHL:6E43:HXOQ:FVLW:OY64:HWD4
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 72
 Goroutines: 218
 System Time: 2016-08-05T09:22:12.607462985Z
 EventsListeners: 4
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
5 VirtualBox VMs cluster

**Steps to reproduce the issue:**
1. Create a cluster with 2 managers and 3 workers
2. Turn off the laptop

**Describe the results you received:**

```
docker@master1:~$ docker node ls
Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader
docker@master1:~$
```

manager logs -- 
[logs.txt](https://github.com/docker/docker/files/403519/logs.txt)

It might be related to https://github.com/docker/docker/issues/25395#issuecomment-237718994

**Describe the results you expected:**

```
rogaha@Robertos-MacBook-Pro:~$ docker node ls                                                                                                                               1:37:46
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
2jml8zh2ap8gnw3ghchc03g09 *  master1   Ready   Active        Leader
3tdlv4cze7r11d5qis26dwrrs    node3     Ready   Active
9fs2d5teotj8d4bsmpy7ml3wq    master2   Ready   Active        Reachable
9j07wl6mklsz56gf4gf6x0m4v    node2     Ready   Active
dnojrk9arbs9m864okbdwhygd    node1     Ready   Active
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by aaronlehmann** [comment]
This could be a manifestation of #25055, which will be fixed in the next patch release.

Otherwise, there could be something particular about the VM setup that causes problems on restart. For example, if the VMs don't have static IP addresses, and they change after restart, that would prevent the two managers from communicating.

A cluster of two managers can't survive any manager failures. We recommend using an odd number of managers for the best resiliency.

In a situation like this where too many managers are down and the quorum is lost, it's possible to recover using the `--force-new-cluster` option (which starts a new cluster with a single manager, using the existing state).

**Comment by toutougabi** [comment]
Having the same issue
Docker version 1.12.0, build 8eab29e

Currently hosting the service in Azure.

The difference is that i did not reboot all the hosts, only one of the leaders got rebooted and the end result is the same, election seems to have failed.

let me know if there's anything i can add to this that would help

**Comment by toutougabi** [comment]
@aaronlehmann  i did try with the --force-new-cluster, this broke the cluster even further. when it executed the result was context deadline exceeded

now if i try to do a docker node ls from what was a manager before, i get "this node is not a swarm manager" but i cannot find any node that is !?

**Comment by thaJeztah** [comment]
@toutougabi if you have just two manager, then that may be expected; if one of two managers is down, you lost quorum, and there's no way to re-elect a new leader (because both leaders are needed to elect a new leader), also see https://docs.docker.com/engine/swarm/admin_guide/#add-manager-nodes-for-fault-tolerance. Basically having a single manager is better than two

**Comment by toutougabi** [comment]
@thaJeztah i had 3 managers

**Comment by toutougabi** [comment]
anything new on this ?

**Comment by aaronlehmann** [comment]
The original issue is reported in this ticket is quite possibly fixed in the upcoming 1.12.1 release (https://github.com/docker/docker/issues/25055).

The issue related to `--force-new-cluster` is not something I've seen before. @abronan do you have any ideas what might cause this?

**Comment by michaelkrog** [comment]
I just experienced this as well. I had a seemingly healthy swarm with 1 manager and 2 workers:
```
$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
0xzzb9ocuwrpoq8aque2ckgtv    engine2   Ready   Active        
7yo9kjx7csti4qjehlsci0d3u *  engine1   Ready   Active        Leader
dzjdm8lm1f48t9aqjuojc9byr    engine3   Ready   Active 
```

After rebooting all 3 servers the swarm cannot recover.

Following is from the master:
```
$ docker node ls
Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader

$ docker info
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 137
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: pending
 NodeID: 7yo9kjx7csti4qjehlsci0d3u
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 ClusterID: 
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 10.2.5.1
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.38 GiB
Name: engine1
ID: HRFF:EBHJ:CG5E:VI7S:YIJN:NHSE:WOTR:V7CH:TPOF:PQK2:DHID:CMQ7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by rogaha** [comment]
More logs: 
[docker_2016_09_29.txt](https://github.com/docker/docker/files/500876/docker_2016_09_29.txt)

/cc @mrjana

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
