### ISSUE TITLE
Copying and pasting from IPython when inside a docker shell also copies and pastes the ANSI color escape code when using ConEmu as console in Windows 

### ISSUE THREAD

**Issue by MatthewMiele** [moby/moby#25476]
**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e
```

**Output of `docker info`:**

```
Containers: 32
 Running: 2
 Paused: 0
 Stopped: 30
Images: 28
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 108
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: SUPY:2DKV:N3C2:ZPXD:AZQ5:DQIQ:5I7W:XFEN:M2YV:Y2VY:L3EO:FAZC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Windows 10 with Anniversary update
ConEmu 160724 [64]
```

**Steps to reproduce the issue:**
1. Open ConEmu using regular windows CMD as shell.
2. Start a docker container and then enter into it. Such as docker exec -it CONTAINER /bin/bash
3. Install IPython in the container. `pip install ipython`
4. Enter IPython `ipython`
5. Type `import datetime` and hit enter, just so we have a colorized line.
6. Copy the first line i.e "In [1]: import datetime"
7. Now paste.

**Describe the results you received:**
The text that gets pasted is `[?20?~n?[1]: import datetime[201~`

**Describe the results you expected:**
Expect the exact same text that was copied. i.e `In [1]: import datetime`

**Additional information you deem important (e.g. issue happens only occasionally):**
I have tested this without ConEmu, i.e directly using CMD and the correct expected result happens.
I have also tested IPython locally on Windows though ConEmu and the correct behavior happens there also. 
Only with IPython inside a docker container through ConEmu does this behavior appear.

The reason I have posted this on the docker page rather than IPython is that it may be related to these
https://github.com/docker/docker/issues/13817 https://github.com/docker/docker/issues/25475
as docker modifies how ansi colors work when using ConEmu as a shell, from what I have read.

**Comment by jhowardmsft** [comment]
I am intrigued - why are so many people using conemu rather than the native cmd shell? It's probably a bug in conemu though.

**Comment by rwilliams** [comment]
@jhowardmsft We're using ConEmu because of [cmder](http://cmder.net/)

**Comment by jhowardmsft** [comment]
@rwilliams So the obvious follow-on question :smile: why `cmder`?

**Comment by rwilliams** [comment]
@jhowardmsft Mostly because it gives us a nice tabbed console emulator. It's quite customizable so we can have for example windows bash, powershell, cmd, cygwin, etc all as different tabs of the same window. And of course the Monokai color scheme.

**Comment by MatthewMiele** [comment]
@rwilliams dont forget split window consoles

**Comment by rwilliams** [comment]
Looks like Looks like https://github.com/docker/docker/commit/4acc2c7499425b9c2521977019d9fe4da73e6af8 blew away the working code for ConEmu.

**Comment by MatthewMiele** [comment]
Any updates on this / conemu docker issues?

**Comment by rwilliams** [comment]
@MatthewMiele Are you using alpine base images?

**Comment by MatthewMiele** [comment]
No. Ubuntu if I remember correctly from the original time when I posted this

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
