### ISSUE TITLE
API/CLI version mismatch

### ISSUE THREAD

**Issue by icecrime** [moby/moby#25498]
# Problem statement

The API/CLI version compatibility requirement is a pain for a huge number of users, and is only getting worse as we have Docker deployed on more and more heterogeneous environments. On the daemon-side, that logic is implemented in the [`VersionMiddleware`](https://github.com/docker/docker/blob/master/api/server/middleware/version.go).

```
        if versions.GreaterThan(apiVersion, v.defaultVersion) {
            return badRequestError{fmt.Errorf("client is newer than server (client API version: %s, server API version: %s)", apiVersion, v.defaultVersion)}
        }
        if versions.LessThan(apiVersion, v.minVersion) {
            return badRequestError{fmt.Errorf("client version %s is too old. Minimum supported API version is %s, please upgrade your client to a newer version", apiVersion, v.minVersion)}
        }
```

Today, the only possible workaround is a horrific hack that simply overrides the version string using the [`DOCKER_API_VERSION`](https://github.com/docker/docker/blob/7c8780ea6327b1d403b13c8b144d9557b5e655e5/api/client/cli.go#L221-L223) environment variable.
# Possible solution

Create a Go package capable of detecting the remote version and accommodating for that (up to its own capabilities, of course). Perhaps we could create a repository that packages multiple versions of the [`docker/engine-api`](https://github.com/docker/engine-api) project and would be "version-aware"? It would expose the latest Go interface, and could provide policies on ways to deal with unsolvable incompatibilities (e.g., the server you're interacting with doesn't implement feature X).

Any idea is welcome on the best way to tackle this!

Cc @vdemeester @fermayo @crosbymichael.

**Comment by thaJeztah** [comment]
Slightly related https://github.com/docker/docker/issues/21157

**Comment by dnephin** [comment]
https://github.com/docker/docker-py supports downgrading. You can instantiate it with `version="auto"`, and it will query for the server version. As features are added, there are version checks added as well, so if you try to use a feature that is unavailable for the version it will include the required version in the error message.

**Comment by stevvooe** [comment]
@icecrime Rather than creating the complexity of multiple packages, shouldn't we maintain `engine-api` to have types that will work with different versions? We can then polyfill the behavior in the new interfaces and ensure that everything works together. Otherwise, the omni-project will have to define a new interface that does the polyfill.

**Comment by cpuguy83** [comment]
I have some thoughts on this... working on a proposal which also happens to address a version issue on the `/info` API on engine-api master (which is currently breaking docker-py).

**Comment by icecrime** [comment]
@cpuguy83 Cool :-) You should sync with @vieux!

**Comment by palfrey** [comment]
If I made a PR that implemented the docker-py "auto" version but at the Go level, would that be of interest? Don't want to do a bunch of effort and then have something rejected!

**Comment by cpuguy83** [comment]
@palfrey The docker client already handles this and is able to negotiate a version with dockerd since 1.13.
Thanks!

Closing since this completed for some time now.
