### ISSUE TITLE
userland-proxy: debugging

### ISSUE THREAD

**Issue by adityats** [moby/moby#25500]
---
## BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

Docker version 1.10.3, build 8acee1b

**Output of `docker info`:**

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.55 GiB
Name: localhost
ID: YFLF:NYNQ:7N5B:HUZV:76LV:Y45V:YQKF:VJOK:P6ZX:VOSK:7U4I:DYAS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare Virtual Machines

**Steps to reproduce the issue:**
1. Enable per-IP container networking.
2. Create some iptables rules for apps for accepting traffic.

**Describe the results you received:**
Traffic flow is busted and doesn't reach the container as intended. There are iptables rules to re-direct traffic to a specific container.

**Describe the results you expected:**
Expect traffic to reach the intended container always. It works about 60% of the time with absoultely no difference in each run from our side.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens reliably 60% of the time and debugging it has become a nightmare as we suspect it is going thru the userland-proxy.

**Comment by thaJeztah** [comment]
could you provide the exact steps to reproduce? I'm not sure we'd be able to help with the information provided currently. Note that you can disable the user land proxy on the daemon (`--userland-proxy=false`).

**Comment by adityats** [comment]
1) Enable per-container IP mode (give docker the Host IP network rather than the default bridge) 
2) Create a sample nginx container.
3) Create another container (this is our specific one) for which add itpables rules to redirect any traffic to ports in range 10000-11000 to the default gateway from the output of `ip route from inside the container 2` to come to this container.
4) Send traffic from container in 2) to the bridge gateway IP:10000 and the traffic works sometimes and some other times it doesn't/

**Comment by thaJeztah** [comment]
I don't really understand;

> Enable per-container IP mode (give docker the Host IP network rather than the default bridge) 

What options do you set; can you provide the exact steps?

> Create another container (this is our specific one) for which add itpables rules to redirect any traffic 

Likewise; please provide the exact steps; what rules are you adding?

**Comment by adityats** [comment]
1) Create a bridge called bridge0 and associate with the primary interface IP as "/usr/bin/ip link set bridge0 address <ip-addr>"
2) Start docker with --bridge=bridge0 and --fixec-cidr=10.10.90.0/24 (Host's network).

the actual iptables rules for the container look like the following:

DNAT       tcp  --  anywhere            10.10.90.2         tcp dpts:10000:20000 to:10.10.90.129:10000-20000

**Comment by thaJeztah** [comment]
closing; this one went stale
