### ISSUE TITLE
docker-containers-shim duplication

### ISSUE THREAD

**Issue by T24-hunter** [moby/moby#25544]
Hi Team !
I have a problem need help
docker-containers-shim duplication
not showing the container when using ps command docker 
do not use docker exec -it container
## Server Version: 1.12.0

---

**Output of `docker version`:**

```
Server Version: 1.12.0
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 16.11 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 2.948 GB
 Data Space Total: 310 GB
 Data Space Available: 307.1 GB
 Metadata Space Used: 2.179 MB
 Metadata Space Total: 3.263 GB
 Metadata Space Available: 3.261 GB
 Thin Pool Minimum Free Space: 31 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge macvlan host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.38 GiB
Name: caas-693.251
ID: 75PQ:KCAJ:KAXA:JNJI:PIRP:JZLT:FRSV:3KWN:GN5F:ZC2N:SGVO:P676
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 46
 Goroutines: 59
 System Time: 2016-08-10T01:38:28.604348442+07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 ip=10.60.93.251
 type=mix
Insecure Registries:
 10.30.70.16:5000
 registry-localhost:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1. using docker exec -it container suspend fail to work
2. not using docker ps & not show list container runing 
3. detect duplicate process docker-containers-shim 
4. kill procces duplicate Back to normal operation , check log not show error 

**Describe the results you received:**

root     30927 33206  0 00:25 ?        00:00:00 docker-containerd-shim 6a69f0fc2490fc66ff2091650c602e7cb45234f7ac4b6902a18b3e6173416954 /var/run/docker/libcontainerd/6a69f0fc2490fc66ff2091650c602e7cb45234f7ac4b6902a18b3e6173416954 docker-runc

root     35017 33206  0 00:36 ?        00:00:00 docker-containerd-shim 6a69f0fc2490fc66ff2091650c602e7cb45234f7ac4b6902a18b3e6173416954 /var/run/docker/libcontainerd/6a69f0fc2490fc66ff2091650c602e7cb45234f7ac4b6902a18b3e6173416954 docker-runc

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mlaventure** [comment]
@T24-hunter Could you give us the command you used to reproduce the issue? I unfortunately could not derives them from your issue description. Also, if you have the daemon logs it could help.

Thanks!
