### ISSUE TITLE
Can't scale up to more than 252 replicas with overlay network

### ISSUE THREAD

**Issue by eungjun-yi** [moby/moby#25558]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Fri Jul 29 03:37:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Fri Jul 29 03:37:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 257
 Running: 252
 Paused: 0
 Stopped: 5
Images: 35
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: macvlan overlay bridge host null
Swarm: active
 NodeID: 2fp1bkz2cfcxgc1vbii29jf3l
 Is Manager: true
 ClusterID: 9pezlreronl7l28nezoq7bsk6
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 127.0.0.1
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.5-1-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.493 GiB
Name: naomint
ID: ZGPT:EALC:K6BX:ZU6F:OG7T:2U3M:5D25:LMAY:KAUI:NWSQ:G6NT:JAZH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.99.211.65:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1. `docker network create -d overlay ovnet`
2. `docker service create --network=ovnet --replicas=256 --name=web nginx`
3. Wait 5 mins and `docker service ls`

**Describe the results you received:**

`web` has 252/256 replicas.

**Describe the results you expected:**

`web` has 256/256 replicas.

**Additional information you deem important (e.g. issue happens only occasionally):**

In another docker host, I can't scale a service up to more than 246 replicas.

It works fine without a overlay network.

I tried this because an overlay network which has /24 subnet seems not to be able to have more than 255 endpoints.

**Comment by cpuguy83** [comment]
I'm not sure I understand the problem here.
You have a network with a /24. Docker cannot add more than 252 replicas to the network, so those are not started.

.1 = gateway
.2 = service VIP
.255 = broadcast
That leaves 252 available IP's.

**Comment by npcode** [comment]
@cpuguy83 I have two problems.

1. I'm not sure what is the proper way to create more than 252 replicas. Is `docker network create -d overlay --subnet=10.2.0.0/16 ovnet` enough?

2. `docker service ps web` shows no error so it's hard to know what's the problem.

**Comment by cpuguy83** [comment]
I agree it should show some more detail, but it does say that `New n minutes ago` where as desired state is "Running"
