### ISSUE TITLE
macvlan network driver only documented as experimental

### ISSUE THREAD

**Issue by sfsmithcha** [moby/moby#25572]
Release notes list macvlan as released with 1.12:

https://github.com/docker/docker/releases/tag/v1.12.0
https://github.com/docker/docker/pull/23524

Only docs are in experimental

https://github.com/docker/docker/blob/master/experimental/vlan-networks.md#user-content-getting-started

Per @programmerq :
programmerq [9:58 AM]  
It could do with a one or two paragraph description of what the macvlan driver is, what technologies it uses, the fact that it is a local scope network driver, and why you might use it instead of another local scope driver (bridge)

cc: @aboch

**Comment by thaJeztah** [comment]
There's documentation now in https://docs.docker.com/engine/userguide/networking/get-started-macvlan/, so we can close this 👍
