### ISSUE TITLE
"Invalid reference format" while running docker commit command

### ISSUE THREAD

**Issue by apunraghu** [moby/moby#25599]
**Output of `docker version`:**
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.819 GiB
Name: moby
ID: YQIK:BKLP:OVLV:FNMX:KEC2:UT4G:272I:4VMY:UIZB:6PO2:Y7WC:3AQO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 32
 System Time: 2016-08-11T03:37:23.441820664Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker on MAC

OSX EI Captain - verion 10.11.6

**Steps to reproduce the issue:**
1. docker run -t -i ubuntu:14.04 /bin/bash
2. apt-get update
3. apt-get install default-jdk
4. exit
5. docker commit <container id> <image name>:<tag>

**Describe the results you received:**
Getting "Invalid reference format" while running docker commit command

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
root@d03e49f45325:/# java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
root@d03e49f45325:/# exit
exit
bash-3.2# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
d03e49f45325        ubuntu:14.04        "/bin/bash"         5 minutes ago       Exited (0) 5 seconds ago                        amazing_yonath
1a7894a53d66        ubuntu:16.10        "/bin/bash"         10 minutes ago      Exited (0) 8 minutes ago                        focused_sammet
941c0128a24c        ubuntu:16.10        "/bin/bash"         15 minutes ago      Exited (0) 15 minutes ago                       zen_cray
06a4dd7037e6        training/webapp     "python app.py"     24 hours ago        Exited (0) 24 hours ago                         goofy_cori
bash-3.2# docker ps  
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
bash-3.2# docker commit d03e49f45325 Raghu-JDK:v0.1
invalid reference format

**Comment by thaJeztah** [comment]
The "invalid reference format" is because image names can only consist of lowercase (`a-z`) characters; try using `raghu-jdk:v0.1`, and it should work

I agree that the message is not very helpful, I'll have a look if we can improve that.

**Comment by thaJeztah** [comment]
opened a pull request in https://github.com/docker/distribution/pull/1900

**Comment by noamhasin** [comment]
There is another problem , if i'm trying to use this command on a running image it still output the same message. so it covers 2 problems. I think should you first check if image is running and then check if the new name is valid.

**Comment by thaJeztah** [comment]
You should be able to commit a running container (by default it is `paused` during commit), if you're having troubles with committing a running container, might be worth opening an issue with details.

Note that `commit` commits a _container_ to an image, so you need to specify the name of the _container_ that you want to commit, not the _image_ it is started from

**Comment by MazharIITK** [comment]
I had also got the same error once. I found that I had to keep the name of my image with all lower case letters. Then after making all of them is lower case, I didn't get any such error.

**Comment by thaJeztah** [comment]
https://github.com/docker/distribution/pull/1900 was merged, and is now included in this repository; closing

**Comment by leviwheatcroft** [comment]
This is also thrown if you forget a flag on an option that contains an uppercase letter. for example:

`docker create -v /srv/pathOne:/pathOne /srv/pathTwo:/pathTwo reponame`

This command should have a second -v before `/srv/pathTwo`.

**Comment by pranotiB** [comment]
Hello,
 can anyone tell me whats is wrong in this docker command?? 

`docker run \ -d \ -e COMPOSER_CARD=${COMPOSER_CARD} \ -e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES} \ -e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION} \ -e COMPOSER_MULTIUSER=${COMPOSER_MULTIUSER} \ -e COMPOSER_PROVIDERS="${COMPOSER_PROVIDERS}" \ -e COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}" \ -v ~/.composer:/home/composer/.composer \ --name rest \ --network composer_default \ -p 3000:3000 \ myorg/composer-rest-server`

Its throwing error as *docker: invalid reference format. See 'docker run --help*

**Comment by honeyankit** [comment]
I am executing the below command and getting the error (/run/torcx/bin/docker: invalid reference format.)

/usr/bin/docker run --rm --name mon-zookeeper-1 --env ZK_SERVER_NUMBER=1 --hostname zookeeper-1 --env ZK_SERVERS=zookeeper-1,10.31.92.1,10.31.94.1 -p 2181:2181 -p 2888:2888 -p 3888:3888 --volume /opt/montana/zookeeper/data:/data ${REGISTRY_ENDPOINT}/montana/mon-zookeeper:3.4.6-1.3

/run/torcx/bin/docker: invalid reference format.
See '/run/torcx/bin/docker run --help'.


Any help?

**Comment by thaJeztah** [comment]
@honeyankit what's the value of `${REGISTRY_ENDPOINT}` ? If that's not set or has an invalid value, then you're trying to run an image name with the wrong format, which is what the message is about

**Comment by honeyankit** [comment]
@thaJeztah : Yes you are correct. I figured it out. In my codebase ${REGISTRY_ENDPOINT} variable name was incorrect. I changed it to our config which is ${REGISTRY_END_POINT} and all good.
