### ISSUE TITLE
External access to a exposed service do not work throught some hosts

### ISSUE THREAD

**Issue by asmialoski** [moby/moby#25598]
I created a new Cluster Swarm Mode with 3 nodes. I create a new service with 2 replicas and I exposed this service on the port 8080. I can access the service throught IP address:8080 of 2 nodes, but throught IP address of 1 node it do not work.

Details:
Docker --version
Docker version 1.12.0, build 8eab29e

Steps to reproduce:
1. docker node ls:
ID HOSTNAME STATUS AVAILABILITY MANAGER STATUS
0aful1un3c9n8oo2mczpzk2yg CN04 Ready Active
18t7hp87t6cntwdlynfa3ewmb \* CN05 Ready Active Leader
b18166fmf4doycbprzrmxq1js CN03 Ready Active
1. docker network create --driver overlay overlay1
2. docker service create --name vote --network overlay1 --replicas 2 -p 8080:80 instavote/vote

After this steps, I am trying to access the exposed service from a external computer using a browser:
- http://cn03:8080 => WORK
- http://cn05:8080 => WORK
- http://cn04:8080 => NOT WORK

Details:
CN03
docker ps:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
ed82e2e44fd3 instavote/vote:latest "gunicorn app:app -b " 29 minutes ago Up 29 minutes 80/tcp vote.2.bkpyzbk2mnwc8ww4xx10cyi17

CN05:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
23d66151fc80 instavote/vote:latest "gunicorn app:app -b " 29 minutes ago Up 29 minutes 80/tcp vote.1.ewtms271k8uh2erqvc46q3j3p

CN04:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES

Command "iptables -nvL -t nat" in all nodes return:
pkts bytes target prot opt in out source destination
34 2040 DNAT tcp -- \* \* 0.0.0.0/0 0.0.0.0/0 tcp dpt:8080 to:172.18.0.2:8080

If I run "curl http://172.18.0.2:8080" directly from the nodes, it work on nodes CN03 and CN05, but it do not work on node CN04. Sometimes, command "curl http://172.18.0.2:8080" return the webpage, but other times return nothing.

I have tried several applications, several containers, several different nodes, different versions of docker (1.12, 1.12-rc04, 1.12-rc05) and the behavior is the same: published services work throught some nodes, but through other nodes it do not work.

Thanks!
Alexandre Smialoski

**Comment by thaJeztah** [comment]
Looks similar to https://github.com/docker/docker/issues/25325, could you have a look if this is the same issue?

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
