### ISSUE TITLE
expose RemovalInProgress state in docker inspect

### ISSUE THREAD

**Issue by timfeirg** [moby/moby#25652]
**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-33556103-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.871 GB
 Data Space Total: 171.8 GB
 Data Space Available: 168.9 GB
 Metadata Space Used: 6.959 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 17.04 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-123.4.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.64 GiB
Name: ***
ID: ***
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: ***
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker inspect [container_id]`

**Describe the results you received:**
One can't tell if the container inspected is in removal

**Describe the results you expected:**
I expect there's a `RemovalInProgress` in `State` from the inspect results, to indicate that the container is in removal.

**We'll be happy to create a PR for this**

**Comment by tonicbupt** [comment]
+1, can this state be exposed? 😆

**Comment by cpuguy83** [comment]
AFAIK it is exposed already.
A container has a state, if the state is removal in progress then that's what you'll see: https://github.com/docker/docker/blob/master/container/state.go#L58

I can't imagine you'd be able to see this very often, though.

**Comment by timfeirg** [comment]
correct me if I'm wrong, the `RemovalInProgress` shown in https://github.com/docker/docker/blob/master/container/state.go#L58 is exposed through some docker commands, but I don't think if that state is retrievable through docker APIs (in particular `Container.inspect`)

@cpuguy83

**Comment by cpuguy83** [comment]
Should be `docker inspect --format '{{ .State.Status }}'`

**Comment by timfeirg** [comment]
@cpuguy83 look at https://github.com/docker/docker/blob/master/container/state.go#L78, when computing a `StateString`, it didn't check for `RemovalInProgress`, so there's no way of getting that state with `docker inspect`

simply adding one more check would do the job (is that correct? @tonicbupt ):

```
// StateString returns a single string to describe state
func (s *State) StateString() string {
	if s.Running {
		if s.Paused {
			return "paused"
		}
		if s.Restarting {
			return "restarting"
		}
###############look at me##############
		if s. RemovalInProgress {
			return "in_removal"
		}
#####################################
		return "running"
	}

	if s.Dead {
		return "dead"
	}

	if s.StartedAt.IsZero() {
		return "created"
	}

	return "exited"
}
```

**Comment by timfeirg** [comment]
@thaJeztah can I send a pr just like the snippet above?

**Comment by allencloud** [comment]
@timfeirg 
I think pr is totally welcomed. It is one of the most important kinds of contribution to this docker project.
