### ISSUE TITLE
FATA[0344] unexpected EOF on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [moby/moby#25714]
**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/386
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/386
```

**Output of `docker info`:**

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 14.04.5 LTS
CPUs: 2
Total Memory: 1.967 GiB
Name: e-cdh
ID: UQW7:3LR2:YJRQ:T6EK:QCFN:NRDE:SRHC:PBVJ:5YXO:3SJZ:NTQY:NHSK
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Clean DigitalOcean droplet with Ubuntu 14.04

**Steps to reproduce the issue:**
1. sudo apt-get install docker.io
2. sudo docker pull cloudera/quickstart:latest
3. 

**Describe the results you received:**
latest: Pulling from cloudera/quickstart
2cda82941cb7: Downloading [==================================================>] 2.147 GB/148.6 MB
FATA[0344] unexpected EOF
**Describe the results you expected:**
Successful pull from the Hub

**Additional information you deem important (e.g. issue happens only occasionally):**
2GB RAM on the droplet and over 2GB image but [documentation](https://docs.docker.com/engine/reference/commandline/pull/) doesn't contain information about `docker pull` to be using RAM during pulling

**Comment by thaJeztah** [comment]
Looks like you're installing the docker package that's maintained by Ubuntu, not the official package (and 1.6.2 is over a year old; https://github.com/docker/docker/releases/tag/v1.6.2)

Could you try uninstalling that package, and install from the official repository? The "easy" install method is to do;

    curl -fsSL https://get.docker.com | sh

Or you can follow the procedure in https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
