### ISSUE TITLE
service create --mount doesn't allow options for "ephemeral" volumes

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#25768]
I briefly discussed with @cpuguy83, but opening an issue to track this.

While I was writing documentation for the `--mount` option, I noticed that it's not possible to specify `volume-opt` options for an anonymous volume. Because of this, it's not possible to let docker create a new, _unique_ volume with specific options, with the same lifecycle as the task it's used on.

This restriction comes from [/api/client/service/opts.go#L238](https://github.com/docker/docker/blame/a9a6d4e2145ab98355b6a8749f2e37f400cbe464/api/client/service/opts.go#L238), which was added in https://github.com/docker/docker/pull/24053

For example; I tried to create a `tmpfs` volume, unique to each task backing the service;

``` bash
docker service create \
  --name my-service \
  --replicas 3 \
  --mount type=volume,destination=/path/in/container,volume-driver=local,volume-opt="type=tmpfs",volume-opt="device=tmpfs",volume-opt="o=size=100m" \
  nginx:alpine
```

Which resulted in this error:

```
invalid argument "type=volume,destination=/path/in/container,volume-driver=local,volume-opt=type=tmpfs,volume-opt=device=tmpfs,volume-opt=o=size=100m" for --mount: source is required when specifying volume-* options
```

So, I'm wondering if there's a specific reason to disallow volume options for anonymous/ephemeral volumes.

/cc @stevvooe

**Comment by stevvooe** [comment]
The argument would be the following:

`--mount type=tmpfs,destination=/path/in/container,tmpfs-opt="size=100m"`

I'm not sure that I added this at the docker level, but this is supported in the swarm api.

Also, `tmpfs` isn't the same as ephemeral, nor would I recommend it be used this way. We should just support anonymous volumes:

`--mount type=volume,destination=/path/in/container`

I am not sure how we handle per-volume resource constraints.

**Comment by thaJeztah** [comment]
@stevvooe yes, @cpuguy83 just mentioned that `tmpfs` is a type (but not yet in the Docker code afaics), however, this was just to illustrate

> Also, tmpfs isn't the same as ephemeral,

Agreed, the "ephemeral" here is that the volume is destroyed if the container/task is destroyed. Read it as `volume-opt="type=whatever"`. The point is, being able to specify options for "anonymous" volumes as well (like we do for "named" volumes)

**Comment by cpuguy83** [comment]
@thaJeztah Volumes that are specified that way would no longer be destroyed by docker on task removal.
They are not really "anonymous", you just didn't give it name, docker did (or rather would).

**Comment by thaJeztah** [comment]
Note that we *do* support anonymous volumes;

```bash
docker service create --mount type=volume,destination=/path/in/container nginx:alpine
```
  
But not if you specify any `volume-xyz` option (including `volume-driver`)

```bash
docker service create --mount type=volume,destination=/path/in/container,volume-driver=local nginx:alpine

invalid argument "type=volume,destination=/path/in/container,volume-driver=local" for --mount: source is required when specifying volume-* options
See 'docker service create --help'.
```

**Comment by thaJeztah** [comment]
@cpuguy83 hm.. alright, so that's probably because Swarm mode, basically does;

```
docker volume create
1bd0168dc72ee540f8bad6969c9d5988cc0d72e27d6f60f8fbc8f607252174cd

docker run -v 1bd0168dc72ee540f8bad6969c9d5988cc0d72e27d6f60f8fbc8f607252174cd:/foo
```

correct?

**Comment by cpuguy83** [comment]
Yes.

**Comment by thaJeztah** [comment]
Thanks, understood, hm.. didn't we have a PR that added "ephemeral" property to volumes?

**Comment by stevvooe** [comment]
@thaJeztah This is the bug:

```
invalid argument "type=volume,destination=/path/in/container,volume-driver=local" for --mount: source is required when specifying volume-* options
See 'docker service create --help'.
```

We may also want to add a lifecycle option that will delete it after the container exits.

**Comment by thaJeztah** [comment]
> We may also want to add a lifecycle option that will delete it after the container exits.

We should probably keep the volume around as long as the container / task exists, but when Swarm garbage collects old containers, it can then also remove the volume. Will need a property on the volume that indicates it's "ephemeral" (because there's no real distinction in the volume itself)

**Comment by stevvooe** [comment]
@thaJeztah I suspect this was fixed?

**Comment by thaJeztah** [comment]
Good question; let me give it a try later on (thanks for the ping!)

**Comment by thaJeztah** [comment]
oh! yes, this was fixed

**Comment by mterron** [comment]
That's only fixed for tmpfs, not for a 'normal' anonymous volume as far as I can see.

**Comment by cpuguy83** [comment]
@mterron Can you explain? Works for me.

**Comment by mterron** [comment]
> 
> 
> @mterron Can you explain? Works for me.

I tried both `docker run` and  `docker-compose`: 
```sh
$ docker run -it --rm --mount 'type=volume,dst=/pp,volume-opt=mode=750,uid=2000' alpine
invalid argument "type=volume,dst=/pp,volume-opt=mode=750,uid=2000" for "--mount" flag: unexpected key 'uid' in 'uid=2000'
See 'docker run --help'.
$ cat docker-compose.yml
(...)
    volumes:
      - type: volume
        target: /etc/app
        volume-opts:
          o: mode=750,uid=2000,gid=2000
(...)
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.app.volumes contains unsupported option: 'volume-opts'
```
For tmpfs this works:
```sh
$ cat docker-compose.yml
(...)
    tmpfs:
      - /home/vault:mode=700,uid=2000,gid=2000
(...)
```

Maybe I'm using the wrong incantation.

**Comment by cpuguy83** [comment]
> Maybe I'm using the wrong incantation.

Indeed.
For compose, the correct way to do this is to put the volume specification in the top-level volumes section:


```yaml
services:
  foo:
    image: busybox
    command: top
    volumes:
      type: volume
      source: foo
      target: /foo

volumes:
  foo:
    driver: local
    driver_opts:
      o: "foo=bar,baz=quux"
```

This of course will fail because those volume options are not valid on the local driver, but that's how you do it.

**Comment by mterron** [comment]
@cpuguy83 that doesn't work if you need to scale the number of containers. I need to do it for ephemeral volumes, not named volumes.

**Comment by cpuguy83** [comment]
@mterron Hmm, perhaps the compose spec should define a field to allow for an anonymous volume.

**Comment by mterron** [comment]
@cpuguy83 the `tmpfs` syntax works fine as far as I can see. Is there a reason why that couldn't be reused? Even the code paths should be mostly the same regarding mount options.
