### ISSUE TITLE
Docker volume plugin API provides incorrect name when given single character volume name

### ISSUE THREAD

**Issue by lmprice** [moby/moby#25773]
When issuing a docker run command with the --volume option, a volume name with a label one character in length will result in a long random string being provided to the driver as the name (like: 051280b61be3b55d1d3a80899475ea7abb657da4cf9bd65a4263a6c4ceacde73).

This was found utilizing the NetApp volume plugin, but is present without the plugin involved.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local netapp
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: openstack2
ID: OMJ2:4XKE:HUKO:C3VM:KHEG:UK2D:BHDG:CEP5:ON5Y:SGWX:2W5V:CFMW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM running under KVM/QEMU

**Steps to reproduce the issue:**
1. Issue a docker run of the form `docker run --rm -it --volume <name>:/my_vol java bash`, where name is a single character in length.

**Describe the results you received:**
The volume driver receives a garbage/generated value rather than the expected name.

**Describe the results you expected:**
The name passed in through the Create request should be the same name that the user passed in.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Comment by thaJeztah** [comment]
Looks like there's a validation step missing, because volume-names should have a minimum length of two characters. I think what's happening is that the single-character name is not passing the check and is subsequently being ignored, resulting in docker thinking this was run:

    docker run --rm -it --volume /my_vol java bash

i.e., "no name provided", in which case docker *generates* a random name

/cc @cpuguy83

**Comment by cpuguy83** [comment]
A volume that looks like `-v d:/foo` is being interpreted as a windows path, and instead of a named volume called `d` you are getting an anonymous volume to `d:/foo` in the container.

This is a limitation of the docker client right now.
Basically, don't use a single char name.

**Comment by lmprice** [comment]
Okay, thanks for the information. For now, we'll simply document for our project that this is a known limitation.

**Comment by chx** [comment]
I would be inclined to take this but @cpuguy83 's answer confuses me:

> you are getting an anonymous volume to d:/foo in the container.

I thought containers do not contain drive letters?

**Comment by thaJeztah** [comment]
> I thought containers do not contain drive letters?

They do when running native Windows containers

**Comment by chx** [comment]
So what would be a desirable fix here? Is this widely used? Could we replace it with `//d:/foo` perhaps?

**Comment by thaJeztah** [comment]
I'm not sure there's a real fix for this, other than not attempting to use a single-letter volume. The shorthand `-v foo:bar` syntax was implemented before docker running on Windows was considered to be possible, and has known limitations.

The intent is to provide the "extended" format as is used for services (`--mount source=<path>,dest=<path>`) for `docker run` as well, which does not have this problem (see https://github.com/docker/docker/issues/28527)

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
