### ISSUE TITLE
Proposal: Add support for OCI Image Layout

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#25779]
To validate support for the [OCI Image Spec](https://github.com/opencontainers/image-spec/), we are going to add support for image layout to `docker save` and `docker load`.

The [OCI Image Format](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) is a content-addressable package roughly equivalent to the docker save/load format. It contains manifests with references to them.

When OCI images are loaded into docker, they become regular docker images. When they are exported again as OCI images, they will be serialized to the OCI Image Layout. The main additions here will be provisions to control which references become which images when imported to docker. Because the OCI Image Spec lacks naming, we include simple parameters for safely importing images into desired names.

This is best demonstrated by example.

The following would generate an image `ubuntu:latest` into an OCI Image Layout:

```
docker save --oci ubuntu > ubuntu-oci.tar.gz
```

This would create a ref "latest" pointing to the relevant OCI structures.

We can also support multiple tags:

```
docker save --oci ubuntu:15.10 ubuntu:16.04 > ubuntu-oci-multi.tar.gz
```

The above would create an image layout where the refs "15.10" and "16.04" would point to their respective manifests. This can also work with images from different repositories:

```
docker save --oci redis:3.2-alpine alpine > ubuntu-redis-oci.tar.gz
```

The above would create refs for `latest` and `3.2-alpine`. However, the following would create a collision:

``` console
$ docker save --oci redis alpine
error: unable to include unique references in oci image
```

In this case, both `redis` and `alpine` have a latest, so we would have to map them. We introduce the `--ref` flag to handle these cases:

```
$ docker save --oci --ref redis=redis-latest --ref alpine=alpine-latest redis alpine > ubuntu-redis-refs-oci.tar.gz
```

At this point, it's important to note that mapping tags to references is merely a convention. The user can then use the `--ref` flag to map from the unconstrained ref space into the docker image namespace.

Let's introduce our first `docker load`, using the tars generated above:

```
docker load --oci --name ubuntu < ubuntu-oci.tar.gz
```

By default, this command will import the provide OCI image layout, into an image named `ubuntu`, translating all refs directly into tags. The same command from above can be used with the `ubuntu-oci-multi.tar.gz`:

```
docker save --oci --name ubuntu < ubuntu-oci-multi.tar.gz
```

Because `ubuntu-oci-multi.tar.gz` has refs "15.10" and "16.04", those tags are created in docker.

Let's move to the multi-image example:

```
$ docker load --oci --ref redis=redis-latest --ref alpine=alpine-latest < ubuntu-redis-refs-oci.tar.gz
```

Because we had multiple images, we have to tell docker how to correctly import each image based on the refs in the image layout file. First thing to note is the structure of the `--ref` command. It is always `--ref <image>=<ref>`, whether using it with `docker save` or `docker load`. For example, the above is really equivalent to `--ref redis:latest=redis-latest`. The other thing to note is the rough equivalence of the `--name` command and `--ref` command. The `--name` command is the same as listing all the refs in an image layout creating a `--ref <image>:<ref>=<ref>` where `<image>` is the argument to `--name`.

**Comment by wking** [comment]
On Tue, Aug 16, 2016 at 04:00:09PM -0700, Stephen Day wrote:
> ```
> docker save --oci redis:3.2-alpine alpine > ubuntu-redis-oci.tar.gz
> ```
>
> The above would create refs for `latest` and `3.2-alpine`.

Is redis:3.2-alpine typoed?  I'd expect ‘redis alpine:3.2’ to create
refs ‘latest’ (with the redis:latest content) and ‘3.2’ (with the
alpine:3.2 content).

> However, the following would create a collision:
>
> ```console
> $ docker save --oci redis alpine
> error: unable to include unique references in oci image
> ```
>
> In this case, both `redis` and `alpine` have a latest, so we would
> have to map them. We introduce the `--ref` flag to handle these
> cases:
>
> ```
> $ docker save --oci --ref redis=redis-latest --ref alpine=alpine-latest redis alpine > ubuntu-redis-refs-oci.tar.gz
> ```

This seems overly complicated.  Why not use REPO[:TAG[:REF]]?  So

* ‘alpine’ gives a repo, and you get the default tag ‘latest’ and the
  default ref for that tag (‘latest’).
* ‘alpine:3.2’ gives a repo and tag, and you get the default ref for
  that tag (‘3.2’).
* ‘alpine:3.2:alpine-3.2’ gives a repo, tag, and ref explicitly.

Personally, I'd rather just make the default refs ‘repo:tag’
(e.g. ‘docker save --oci alpine’ creates an ‘alpine:latest’ ref and
‘docker save --oci alpine:3.2’ creates an ‘alpine:3.2’ ref).  Nice and
simple.  The current image-layout format doesn't allow colons, but
that's easy to fix (e.g. with ocitools/image-spec#174).

Stepping away from the syntax and choice of ref names, how is security
going to work here until something like opencontainers/image-spec#176
lands with a way to represent signatures and name-assertions in the
OCI framework?  Does a save/load cycle lose any previous signatures?
Or does Docker attempt to re-fetch missing signatures from an external
(central?) store when you load an unsigned image?

**Comment by runcom** [comment]
(fat finger) 

BTW, I have a somehow, hacked, working branch to support this. I'll be back from vacation next Monday, I can open a PR to discuss more.

**Comment by cpuguy83** [comment]
Definitely -1 on a `--oci` flag. I think `--format oci` would be better.
Not sure about the `--ref` stuff, seems really complex, but I'm not sure how else to handle it (other than not).
A bit worried about compatibility with older daemon versions (e.g., save in oci format in one daemon, hand off to someone else running an older daemon and it won't load).
Is the only thing that's different the manifest?

**Comment by stevvooe** [comment]
> Is redis:3.2-alpine typoed?  I'd expect ‘redis alpine:3.2’ to create
refs ‘latest’ (with the redis:latest content) and ‘3.2’ (with the
alpine:3.2 content).

Read the example again. The tags are `latest` (implied) and `3.2-alpine`. We merge tags for the images presented in the command.

Note that the default tag mapping is just a convenience. There is no requirement for these to have any relation. The power of the `--ref` argument is that it provides a tool for mapping the ref space of an image layout to the names we see in docker. If naming is added, the `--ref` option will no longer be needed.

In general, the verbosity in this proposal ensures we have room for additions in the future.

> This seems overly complicated.  Why not use REPO[:TAG[:REF]]?

The syntax for an image reference is already MASSIVELY overloaded. I don't want to introduce any kind of ambiguities.

> The current image-layout format doesn't allow colons, but
that's easy to fix (e.g. with ocitools/image-spec#174).

Assuming you mean opencontainers/image-spec#174. I really don't see a move to base64 happening. Aside from the usability problems, it creates a tight link between naming on the docker side and naming in oci image format, which both an optional layer and  

> Stepping away from the syntax and choice of ref names, how is security
going to work here until something like opencontainers/image-spec#176
lands with a way to represent signatures and name-assertions in the
OCI framework?  Does a save/load cycle lose any previous signatures?
Or does Docker attempt to re-fetch missing signatures from an external
(central?) store when you load an unsigned image?

Any information that is not loaded into docker with not be output into the resulting OCI image. OCI Image Layout _will not_ round trip through docker untouched. For all intents and purposes, the generated layout will be a new image layout, but _may_ share content.

If we add naming and signatures to the image spec, we add support for those, but let's keep the scope limited.

> A bit worried about compatibility with older daemon versions (e.g., save in oci format in one daemon, hand off to someone else running an older daemon and it won't load).
Is the only thing that's different the manifest?

Older daemons don't have support for the OCI Image Layout.

**Comment by stevvooe** [comment]
@runcom Would love to see a WIP PR. Let me know and we'll work towards something.

**Comment by stevvooe** [comment]
@cpuguy83 

> Definitely -1 on a --oci flag. I think --format oci would be better.

What other formats do you see working here in the future? Ideally, we'd be able to deprecate this flag and autodetect in the future.

> A bit worried about compatibility with older daemon versions (e.g., save in oci format in one daemon, hand off to someone else running an older daemon and it won't load).
Is the only thing that's different the manifest?

Older daemons don't have support for the OCI Image Layout.

**Comment by duglin** [comment]
ociv1, ociv2, appc, ....

**Comment by stevvooe** [comment]
@duglin I don't think we'd want to require a flag per version. Once you know what class of format you're accepting, disambiguating the version is done with internal mediatypes. If we can detect the tarfile is an oci image, this flag isn't needed at all.

**Comment by duglin** [comment]
I was thinking more on the `docker save` side of things - where its a question of how does the user want the image serialized. `docker save --format ociv1` or `docker save --format oci:v2` ...

I agree that `docker load` shouldn't need it since it can check the incoming bits to get that info.

**Comment by stevvooe** [comment]
> I was thinking more on the docker save side of things - where its a question of how does the user want the image serialized. docker save --format ociv1 or docker save --format oci:v2 ...

Yes, true!

Why would we favor a micro-format for `--format` over simply doing these as flags (`--oci-experimental`, `--oci-v1`, `--oci-v2`)? They have a much clearer deprecated policy and really represent a mode of operation than a format.

**Comment by duglin** [comment]
While the net result might be the same I think a `--format` flag gives us a natural (scoped) extension point - the same way other projects have a `--output` type of flag. You just add new values to this flag instead of new flags.

I don't view this as a "mode of operation" - to me this is about serialization/format - like going from `--output json` to `--output yaml` is about format not semantics.

**Comment by stevvooe** [comment]
@duglin You missed my point. This isn't as simple as a format change. There are options and behavior that change. For example, `--ref` isn't valid. Also, you've failed to recognize the complexity of defining the support-level of a new micro-format, taken in the `--format` flag.

Why add that complexity when we can do this at the flag level, where we have ways of defining support?

**Comment by duglin** [comment]
@stevvooe I do realize that and I don't think the weeds matter when all the user wants is to change the of output file from docker to oci to appc.  As I said, in the end its the same net result, its just a UX issue.

**Comment by stevvooe** [comment]
@duglin Exactly. And we avoid the weeds if we just use flags, rather than a micro-format.

**Comment by mikebrow** [comment]
Not sure why `--format type`  is a micro format and `--type` isn't.  Don't they hold the same meaning?  Put another way, what do you mean by micro format?

**Comment by wking** [comment]
On Thu, Aug 18, 2016 at 12:28:58PM -0700, Stephen Day wrote:
> > Is redis:3.2-alpine typoed?  I'd expect ‘redis alpine:3.2’ to
> > create refs ‘latest’ (with the redis:latest content) and ‘3.2’
> > (with the alpine:3.2 content).
>
> Read the example again. The tags are `latest` (implied) and
> `3.2-alpine`. We merge tags for the images presented in the command.

So the example is saving alpine:latest → latest and redis:3.2-alpine →
3.2-alpine?  If that's the case, I'd suggest picking different
examples so you don't have an alpine image with an implicit tag and a
redis image with an explicit tag that includes the string “alpine”.
If I'm still misunderstanding, it would help if you replaced:

  The above would create refs for latest and 3.2-alpine.

with:

  The above would create refs for latest (referencing the manifest for
  Docker's $IMAGE_1) and 3.2-alpine (referencing the manifest for
  Docker's $IMAGE_2).

plugging in full image names (e.g. alpine and redis:3.2-alpine) for
$IMAGE_1 and $IMAGE_2.

> Note that the default tag mapping is just a convenience. There is no
> requirement for these to have any relation.

Yeah, +1 to making this flexible.  I just think that we can come up
with something more expressive than a per-ref --ref option.  For
example, you should be able to say “map all ubuntu:$TAG images to
ubuntu-$TAG refs” compactly.

> > This seems overly complicated.  Why not use REPO[:TAG[:REF]]?
>
> The syntax for an image reference is already MASSIVELY overloaded. I
> don't want to introduce any kind of ambiguities.

Fair enough.  How about:

  $ docker save --oci --ref-prefix ubuntu=ubuntu- ubuntu:15.10 ubuntu:16.04 >ubuntu-ref-prefix-oci.tar.gz

which would create an image-layout with two refs, ‘ubuntu-15.10’ and
‘ubuntu-16.04’.  The syntax is ‘--ref-prefix DOCKER_REPO=REF_PREFIX’.
As another example:

  $ docker save --oci --ref-prefix redis=redis- --ref-prefix alpine=alpine- redis alpine > redis-alpine-ref-prefix-oci.tar.gz
  $ docker save --oci --ref-prefix redis=redis- --ref-prefix alpine=alpine- redis:latest alpine:latest > redis-alpine-ref-prefix-oci.tar.gz

both of which would create an image-layout with refs for
‘redis-latest’ and ‘alpine-latest’.

> > The current image-layout format doesn't allow colons, but that's
> > easy to fix (e.g. with ocitools/image-spec#174).
> 
> Assuming you mean opencontainers/image-spec#174.

Yeah, thanks.  I've updated my initial comment.

> I really don't see a move to base64 happening. Aside from the
> usability problems, it creates a tight link between naming on the
> docker side and naming in oci image format, which both an optional
> layer and

and… ?  I don't think it creates a tight link (you should still be
able to overide the ref↔image mapping if you want).  I'm more
interested in it as a way to provide a default ref↔image mapping that
can multiple repos with the same tag (e.g. alpine:latest and
redis:latest) in a single image-layout instance.

Also, you seem to switch back and forth between ‘ubuntu’ and ‘alpine’
in your examples.  Maybe pick one or the other?

**Comment by wking** [comment]
On Thu, Aug 18, 2016 at 02:55:03PM -0700, W. Trevor King wrote:
> Thu, Aug 18, 2016 at 12:28:58PM -0700, Stephen Day:
> > > This seems overly complicated.  Why not use REPO[:TAG[:REF]]?
> >
> > The syntax for an image reference is already MASSIVELY overloaded. I
> > don't want to introduce any kind of ambiguities.
> 
> Fair enough.  How about:
> 
>   $ docker save --oci --ref-prefix ubuntu=ubuntu- ubuntu:15.10 ubuntu:16.04 >ubuntu-ref-prefix-oci.tar.gz

My main concern with --ref (as you currently have it) is that:

  --ref redis=redis-latest … redis

says “map Docker's ‘redis’ to ref ‘redis-latest’ and save Docker's
‘redis’”.  But why would you be mapping the refs if you didn't intend
to save that image?  If my --ref-prefix is too blunt an instrument,
I'm also open to other syntaxes where giving a Docker↔ref mapping for
a particular image/ref *also* tells the command to save/load that ref.
That's what I was shooting for with REPO[:TAG[:REF]], although I can't
think of a way to do it that doesn't risk further overloading the
argument.  On the other hand, ‘--ref REPO[:TAG]=REF’ seems to have
similar overloading issues to REPO[:TAG[:REF]].  If the idea is just
to reduce parsing complication and increase explicitness, I'm also
fine requiring all save/load references to be REPO:TAG:REF with no
optional portions (e.g. redis:latest:redis-latest).

If you want to get really explicit, there's always:

  $ docker save --oci '{"repo": "redis", "tag": "latest", "ref": "redis-latest"}' >redis-ref-oci.tar.gz

;).

**Comment by stevvooe** [comment]
@mikebrow 

> Not sure why --format type is a micro format and --type isn't. Don't they hold the same meaning?

`--oci` would be a documented flag. We have documentation about when it is supported and when it is deprecated. The meaning of the field and how to use it output from help output. Compare with other `--format` fields, where the format is buried in the docs, usually a Go template expression or something other set of values, buried deeply.

The idea here is that the user can say "How do I OCI? O, it's right there" and be on their way. Hiding this behind a `--format` creates another level of indirection where the user has to go to the docs before they're up and running.

> what do you mean by micro format?

A micro-format is a format that has structure and meaning in a particular context. Examples of micro-formats include port mapping ('8080:8080'), `--volume` syntax or the image reference syntax. We also see micro-formats in tools like git and ssh. They usually have a small, lightweight grammar specified only by the implementation itself. `--ref`, in this proposal, is a micro-format, chosen to be compatible with the existing micro-format for image references.

(I looked for this definition somewhere on the Internet, but unfortunately, the XML/HTML decorator features have completely taken over the terminology for micro-format. If there is a better word for this class of under-specified data schema, I'm all ears.)

**Comment by mikebrow** [comment]
I see. So by micro-format you meant buried inside the save --format options list.

The presumption appears to be that the --format option in this case and more particularly the pick list of --format options would not be documented in a first class way. Or that --format is typically intertwined with go template options, for example when the data is a table. The documentation for --format could be improved on for some of the other apis, yes. It's pretty easy to add documentation, to command help. Example: 
`--format <option> :  Save with the selected format where <option> is one of [docker], oci, appc`  
vs
`[--docker]: save defaults to docker format`
`--oci :  save with the oci format`
`--appc: save with appc format`

Further usage examples can also be provided in the --help for the save command.

The same failings that may occur with choices in a pick list of formats could also occur with a plurality of format options raised that have been raised up a level in the ux. 

When you have too many options at the highest levels of a ux the ux becomes unwieldy. With the plurality output formats [--docker[v1,v2?]] --oci --appc --ociv2 etc. one can see that they are all mutually exclusive format choices and none is a go template expression. It's a pick list (where the user picks one from this list.  You couldn't say `save --oci --appc --docker` you'd have to pick one for each save operation.  Typically when there is a list of a thing classifying the list is a good thing that is readily understood.  

For example, you could have argued for a new `save-oci` command to un-hide the difference between save [docker format] and save [oci format] but you didn't presumably because it makes sense that both are save operations. Similarly the format chosen from a pick list of options are all formats. If you don't like --format you could use --s(pec) or --in or --using ...

Cheers, Mike

**Comment by wking** [comment]
On Fri, Aug 19, 2016 at 08:08:43AM -0700, Mike Brown wrote:
> For example, you could have argued for a new `save-oci` command to
> un-hide the difference between save [docker format] and save [oci
> format] but you didn't presumably because it makes sense that both
> are save operations.

Another common way to represent this sort of mutually-exclusive
behavior is with subcommands.  So:

  $ docker save oci …
  $ docker save appc …

which also gives you a convenient way to scope format-specific options
like --ref.

The drawback to taking that route here is that we already have ‘docker
save …’ committed to the existing Docker format(s), and pushing that
down into ‘docker save docker …’ or some such would break existing
users.  If we had no existing users, I'd prefer the subcommand
approach.

But we do have existing users, so I prefer ‘--format
[docker|oci|appc|…]’ because it collects all the mutually-exclusive
choices in one place.  You have to cover the OCI-specificity of --ref
(or whatever we end up with to fill that role) in the --ref
documentation, which isn't as convenient as if it was a subcommand
option, but isn't that bad.

**Comment by runcom** [comment]
@stevvooe I expect to propose a PR to discuss more about this by the end of the next week

**Comment by c4milo** [comment]
@runcom any update?

**Comment by runcom** [comment]
Working on fixing remaining tests and update the spec to v1

**Comment by Zalgo2462** [comment]
I have a use case where I am redistributing Docker images into an air-gapped environment. Previously, we had only supported amd64 architectures, but now we are now using `buildx`/ BuildKit to build multi-architecture images. As such, we can no longer simply `docker save` and `docker load` the images to distribute the multi-architecture images. 

`docker save` will not save out a Docker image with a manifest list which includes all of the architectures. So, to get around this I am using a tool such as `regclient` to export the image from our registry as an OCI format image. However, now, I cannot `docker load` this OCI format image either. Instead, I am looking at standing up a local docker registry as a container on the target machine, importing our OCI image into the registry, and then using `docker pull` to load the image on to the system. While this should work, it is a very roundabout process.

Any alternatives or news regarding this issue would be welcome.

**Comment by thibaut-lo** [comment]
@runcom , any update on this ? Thanks ! 🙏
