### ISSUE TITLE
inconsistent mapping of images names when using fully qualified name

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#25827]
This was original described in https://github.com/docker/docker/pull/24719#issuecomment-233455620.

For the purpose of pulling `redis`, we make the following assumption:

```
redis == library/redis == docker.io/library/redis
```

This is because we don't know which registry `redis` is associated with. And when we do this pull, only `redis` shows up in the image list. We do not populate the other variants.

The reverse assumption cannot be made:

```
docker.io/library/redis != library/redis != redis
```

This breaks down because we do not know whether an existing image `redis` is from `library/` without having the tag.

The real bug here is the following:

```
$ docker pull docker.io/library/redis
Using default tag: latest
latest: Pulling from library/redis
5c90d4a2d1a8: Already exists
8e636c10fc4b: Pull complete
a4486ffc4334: Pull complete
66471c0ab8a7: Pull complete
b8697f5c1d8a: Pull complete
c771d8e60b99: Pull complete
ebd65895367f: Pull complete
Digest: sha256:b50f15d427aea5b579f9bf972ab82ff8c1c47bffc0481b225c6a714095a9ec34
Status: Downloaded newer image for redis:latest
```

We would expect that the image shows up as `docker.io/library/redis`, but it does not:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
redis               latest              4465e4bcad80        4 weeks ago         185.7 MB
```

This should be the following:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/library/redis               latest              4465e4bcad80        4 weeks ago         185.7 MB
```

The main issue is that for the command `docker pull docker.io/library/redis`, the image will be created as `redis`, where as we would expect it to be `docker.io/library/redis`.

**Comment by dmcgowan** [comment]
I definitely recognize this as an issue but still not sure what we can and should do about it. I have picked up my work on getting the reference changes upstream and part of that is ensuring that throughout the code we are using strong typing for normalized and non-normalized references. Ideally the client is doing the normalization and the daemon only deals with normalization, but in that scenario we can not distinguish between user given "docker.io/library/redis" and "redis". As is in the code there is a normalization pass before we hit the reference store causing the inconsistency that is being referred to here. From my perspective, a client side reference store could handle this, but this is no longer being worked on. Based on looking at the code, I am more in favor of always normalizing and presenting the user with a "familiar" or "short" form. Do you have any ideas of how should handle this without significant changes to the way references are stored. One thing that comes to mind is expanding the `NormalizedNamed` type to have the original value. In this case we could preserve the user's given value at the cost of carrying around 2 strings in references. 

This work is ongoing at https://github.com/docker/distribution/pull/1778 and an experimental docker integration here https://github.com/dmcgowan/docker/pull/27.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
