### ISSUE TITLE
Hash Sum mismatch on xenial armhf repo?

### ISSUE THREAD

**Issue by MikeLund** [moby/moby#25838]
I see there is https://github.com/docker/docker/issues/23396, but not many people have noticed it? Or is it just that like no one uses docker on armhf?

It could be user-error (my side), but I see no possible reason for it, and have cleaned my apt cache etc.

> ~# sudo apt-get update
> Hit:1 http://mirror.scaleway.com/ubuntu-ports xenial InRelease
> Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
> Hit:3 http://ports.ubuntu.com xenial-security InRelease
> Get:4 https://apt.dockerproject.org/repo ubuntu-xenial InRelease [29.8 kB]
> Get:5 https://apt.dockerproject.org/repo ubuntu-xenial/main armhf Packages [931 B]
> Err:5 https://apt.dockerproject.org/repo ubuntu-xenial/main armhf Packages
>  Hash Sum mismatch
> Fetched 30.7 kB in 2s (12.1 kB/s)
> Reading package lists... Done
> E: Failed to fetch store:/var/lib/apt/lists/partial/apt.dockerproject.org_repo_dists_ubuntu-xenial_main_binary-armhf_Packages.bz2  Hash Sum mismatch
> E: Some index files failed to download. They have been ignored, or old ones used instead.

Thanks.

**Comment by justincormack** [comment]
I don't think there are Xenial armhf debs yet.

**Comment by MikeLund** [comment]
Makes sense;

I suggest that "armhf" be removed from the Architectures section in the InRelease files, if it's not intended to work.

**Comment by withinboredom** [comment]
See #25879

**Comment by calston** [comment]
Same on Jessie, still... - W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-armhf/Packages  Hash Sum mismatch

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
