### ISSUE TITLE
Distributed application bundles service instantiation and DNS service resolve

### ISSUE THREAD

**Issue by shalberd** [moby/moby#25865]
https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md

I realize the distributed application bundles feature is still experimental, but am wondering the following for a multi-node cluster scenario and service discovery. 
1. Can one and the same distributed application bundle be instantiated / deployed multiple times? Can there be multiple stacks?
2. Assuming yes, I would have multiple services with different service.replicamember.randomid, correct?
3. If indeed I can instantiate / deploy one and the same distributed application bundle multiple times, how are the "short", not fully-qualified DNS names resolved? Could I resolve the service part of the stack [service.replicamember.randomid] easily? I apparently have no way of knowing the random ID that is part of the fully-qualified name. 

Sincerely

Sven

**Comment by alex-berger** [comment]
It looks like there are still some pieces missing, https://github.com/docker/docker/issues/25369 and https://github.com/docker/docker/issues/24787.

**Comment by AkihiroSuda** [comment]
DAB support was removed in docker/cli#2216 .

https://github.com/docker/app is the successor.
