### ISSUE TITLE
docker swarm model networks support `--network host` or not?

### ISSUE THREAD

**Issue by fanux** [moby/moby#25873]
First of all, the docker swarm model is very convenient for us, easy to use and deploy.
But our application need share host network witch swarm model is not support now.

The reason why we need share host network is:
- Our application is audio engine, each node only run one container, overlay or other network model drop down network speed and consume more CPU. 
- There are two network interfaces on our machine，independence from each other, for example, eth0:172.0.0.3 for command transmission and eth1:192.168.0.4 for data  transmission, both of then are physics network interface, and link to different switch. An application container will use then at a same time.  How overlay network solve this problem, two overlay networks on same node?
- We don't have the load balance requirement.  

We need the `--network host` model badly, it is the simplest way to solve all the problems of us，and the achieve  best performance.

@thaJeztah

**Comment by discoverkl** [comment]
@thaJeztah  
I have the same problem too.
```
# docker service create --name demo --network host alpine /bin/sh    
Error response from daemon: network host is not eligible for docker services
```
**We REALLY need '--net host' in Docker Swarm**, because iptables's NAT module is missing in out company, for security reasons. So all the fancy overlay network is not working for us.

**Comment by kyhavlov** [comment]
I'd find this really useful as well, mostly for running high performance things. We use swarm to schedule one database container per host with --net=host and not having this option is holding us back from using 1.12's services (which we'd really like because of the update/rolling restart feature).

**Comment by jpetazzo** [comment]
The corresponding issue in SwarmKit is docker/swarmkit#989.

**Comment by xiaods** [comment]
please close it as the swarmkit #989 is created

**Comment by thaJeztah** [comment]
@xiaods I think it's ok to keep this open for the docker side

**Comment by rootsongjc** [comment]
@theJeztah Does docker has any road plan for swarm mode to support host network?

**Comment by thaJeztah** [comment]
@rootsongjc this is the issue tracking it, also see the swarm kit issue linked above (docker/swarmkit#989) that has more details on the current status

**Comment by sm0svx** [comment]
Already wrote this in #25303 but adding it here as well for easy reference.

+1 on network=host. The lack of this option is basically a showstopper for me since my application connect out to a specific hardware unit using TCP. The unit then send data back using UDP to the originating IP address for the TCP connection. This works well in docker run with net=host but of course fail using the docker0 bridge in swarm mode.

**Comment by wanghongfei** [comment]
+1 for the need of host mode. The overlay network of swarm mode has performance penalty

**Comment by OnlySlon** [comment]
+1 for host mode @swarm

**Comment by hkvemuri** [comment]
+1 for exposing host network namespace to a swarm service

**Comment by adventurer2008** [comment]
+1 for host mode @swarm

**Comment by kleinsasserm** [comment]
Yes we need this too, because without it it is not possible to dynamically add host network devices (VIP's) from inside a container through swarm service configuration.

**Comment by sulphur** [comment]
+1

**Comment by marcellodesales** [comment]
+1

**Comment by xiaods** [comment]
+1

**Comment by mavenugo** [comment]
https://github.com/moby/moby/pull/32981 is addressing this requirement.

**Comment by mmariani** [comment]
still not supported in yml files afaik - works in `docker service create`, not in `docker stack deploy`

**Comment by robbatt** [comment]
+1

**Comment by thaJeztah** [comment]
@mmariani @robbatt I think this will work with the upcoming 17.06.1 release (haven't tested on 17.06.0 yet), but this looks to work;

```
version: '3.3'

services:
  web:
    image: "nginx:alpine"
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"
```

**Comment by mmariani** [comment]
@thaJeztah I already tried that, I got "container cannot be disconnected from host network or connected to host network"

**Comment by thaJeztah** [comment]
@mmariani are you trying to _publish_ a port (does your service have the `ports:` option set)? If so, that's expected; when using "host" networking, the container's process runs directly in the host's network stack, thus all ports that the container listens on are accessible. (The error message could be improved :smile:)

**Comment by mmariani** [comment]
@thaJeztah thanks, the `ports:` option was indeed the reason, now it works!

The similar `pid: host` option, by the way, is silently ignored for swarm services. It should be honored or forbidden, I guess

**Comment by rdxmb** [comment]
works for me with
`Docker version 17.07.0-ce`

**Comment by realcbb** [comment]
@thaJeztah  
I also got "container cannot be disconnected from host network or connected to host network".
docker 17.06.1-ee-2

**Comment by thaJeztah** [comment]
I re-tested this on Docker 17.10, and this should now work (see my previous example in https://github.com/moby/moby/issues/25873#issuecomment-319109840)

@realcbb if the example I gave doesn't work on the latest 17.06.x EE release, please contact your support representative

**Comment by svscorp** [comment]
@thaJeztah in 17.11-ce deploying a Swarm Mode stack via docker-compose v3.3 I am getting this error. In my case I also have `ports` published in docker-compose. Any ideas? :)

````
Rejected less than a second ago   "container cannot be disconnected from host network or connected to host network"
````

**Comment by thaJeztah** [comment]
@svscorp can you check if you're publishing a port for a service connected to the host network? When using host networking, you can't publish ports (any port exposed by the service is accessible, because it's running directly on the host's network stack); that error message is printed in that case

**Comment by svscorp** [comment]
Hi @thaJeztah thank you for quick response. Okay, now I see - my mistake. You are right. May I ask one more question then, if I want to attach a service (nginx in my case) to two networks - host and a custom overlay (to have services talking to each other across the Swarm). Is my assumption correct - I should be able to access a service on exposed port(s) directly accessing the node AND other services can connect to this "host service" thru the overlay normally?

**Comment by zsz1990ustc** [comment]
@thaJeztah Thank you for providing that way to use host network in docker compose file! But when I did docker stack deploy to swarm, only the master machine is good to run. Other machines on swarm will show the error "only one instance of "host" network is allowed".

So if host network is only allowed in one machine, the docker compose file for swarm will be useless, since I can do docker run on one machine.

**Comment by thaJeztah** [comment]
`host` networking unfortunately cannot work on Docker for Mac, due to the way that Docker for Mac runs; on Docker for Mac, the docker daemon (and containers) run in a lightweight VM, and networking traffic from the Mac "host" network is proxied to the VM's network.

**Comment by grikdotnet** [comment]
Host network works in Mac.
```
networks:
  router:
    image: nginx:1.15-alpine
    networks:
      - hostnet

  hostnet:
    external: true
    name: host

```

Though, there is no name resolution for other services in the container in the host network

**Comment by mohsenasm** [comment]
In `swarm mode`, you can also use `networks` like this:

    version: '3.6' # not 3.4
    
    services:
      a_service:
        image: "nginx:alpine"
        command: sleep 10000
        networks:
          - outside
    
    networks:
      outside:
        name: host
        external: true

with `docker stack deploy -c filename.yml temp_stack`
