### ISSUE TITLE
Swarm mode - SSL certificate problem 

### ISSUE THREAD

**Issue by mnbao1975** [moby/moby#25887]
I used docker swarm mode (1.12.1) to setup a swarm on AWS including 2 EC2 instances: 1 manger (manger.example.com) and 1 node (node.example.com). I also installed SSL certificates for those EC2 so that I can have my nodejs web server can work with https.

When I use "curl  https://manager.example.com" for the first time, it work well. But, if I do it one more, then I will get an error about "SSL certificate problem" from curl. Continue to repeat it again and it work well. But, if do it one more time, then I will get the same error.

In general, that will be fine when the request of https://manager.example.com is routed to the server manager.example.com. But, if it's routed to the node.example.com, then I will get that error.

PS: everything is fine if I use curl with http instead of https.

Thanks,
Bao

**Comment by neersighted** [comment]
Swarm ingress is not L7 aware/application-level, as such, your terminating server needs to have a valid TLS certificate for any DNS names you refer to it by during a HTTPS request.

Closing as invalid/long stale; please let us know if there's anything in the docs that mislead you/could be improved.
