### ISSUE TITLE
Networking route to bridge network not defined to use proper interface (when multiple public ip aliases)

### ISSUE THREAD

**Issue by YouriT** [moby/moby#25923]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 121
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 63.02 GiB
Name: srv13.rockfox.ovh
ID: 5ULA:ZFT3:GDCU:WSFI:MRM6:75BQ:E5Q4:XKJ4:4IKS:2HVF:NEH2:NILK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal

**Steps to reproduce the issue:**
1. Add multiple IP aliases to your host (public IP's routed to `eth1` whereas the default server IP is on eth0)
2. Add a routing table for these IP's to get out of the host through `eth1` instead of going through out the default gateway (0.0.0.0) which is bound to `eth0`
3. Create a user-defined bridge network 192.168.16.0/24
4. Add the appropriate routing table for 192.168.16.0/24 to get out through the right interface again and not through the default gateway
5. Create a container bound to one of the additional public IP's (ex: `$ docker run -d --net=user-defined -p ADDITIONAL_PUBLIC_IP:80:80 nginx`
6. Try to `telnet ADDITIONAL_PUBLIC_IP:80` from the host

**Describe the results you received:**
Packets are handled by netfilter and try to fly away through `eth1` (normal as I defined that `eth1` is the output dev in the routing table) 
`TRACE: filter:OUTPUT:policy:2 IN= OUT=lo SRC=ETH1_PUBLIC_MAIN_IP DST=192.168.16.10
TRACE: mangle:POSTROUTING:policy:1 IN= OUT=eth1 SRC=ETH1_PUBLIC_MAIN_IP DST=192.168.16.10`
 instead of going out through the user defined interface `br-XXXXX`

**Describe the results you expected:**
I expected that when docker creates the new interface, it adds a rule in the routing tables to route 192.168.16.0/28 packets through this specific user-defined interface.
So I did:
`ip route add 192.168.16.0/24 dev br-XXXXX table 125` to solve my problem.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Comment by cpuguy83** [comment]
ping @mrjana

**Comment by thaJeztah** [comment]
ping @mrjana @aboch

**Comment by justincormack** [comment]
Why don't you create a bridge with `eth1` on it with the public IPs on and use that as the Docker bridge?

**Comment by YouriT** [comment]
@justincormack wouldn't you get the same issue but towards `eth0`?

**Comment by mavenugo** [comment]
@YouriT am trying to understand the use-case, but cannot get the full picture based on your description. Could you somehow explain the scenario better ? I wish I can ask more meaningful pondering questions, but the scenario is a bit vague for me to understand.

**Comment by thaJeztah** [comment]
ping @YouriT could you reply to @mavenugo's question?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
