### ISSUE TITLE
FEATURE REQUEST - Control the container name in scale mode

### ISSUE THREAD

**Issue by groyee** [moby/moby#25934]
I can set container_name="foo" in my docker-compose.yml to control the name of my container. This is great. But then I can't scale it anymore.

Why can't docker just take my name and use it as a "prefix" and concatenate to it some random string when it in scale mode? If you scale with docker-compose then the container name will always start with the same.

**Comment by icecrime** [comment]
Ping @aanand!

**Comment by cpuguy83** [comment]
This really belongs in github.com/docker/compose

**Comment by thaJeztah** [comment]
Yes, this looks like something for compose, not the engine, so lets close this one.
