### ISSUE TITLE
Issue with --with-registry-auth on docker service

### ISSUE THREAD

**Issue by geNAZt** [moby/moby#25952]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local stocker
 Network: null overlay bridge host
Swarm: active
 NodeID: 9zlx8sdx2squcrme9ijzd2rfy
 Is Manager: true
 ClusterID: 8ako44khzlbgvdg2l048lpkte
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.135.28.156
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.871 GiB
Name: Docker-Cluster01
ID: GBOS:EONW:VSZ5:MYTA:2C7S:N4PA:FZSC:HJIO:OUAL:OG6A:CRQT:XJ3R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on DigitalOcean VPS running Debian 8 (3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux)

**Steps to reproduce the issue:**
1. Create docker swarm for services
2. Docker login with quay.io credentials
3. Create a Service with

```
docker service create --mode global --name gommehdnetpe-proxy --with-registry-auth --network=gommehdnet-pe -p 19132:19132/udp quay.io/gommehdnet/pe-proxy:latest
```

**Describe the results you received:**

We got preparing Tasks for all 3 Nodes we currently have for testing. All of them do output this to journal:

```
Aug 23 04:49:25 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:25.755244136-04:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5m0laifk8u7m0fm0a32wt5h40 node.session=cph8m2nq4g0zaslpcdop6wjp3 task.id=ecd8wheg9dctvyngyascg167k
Aug 23 04:49:25 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:25.812376816-04:00" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=ecd8wheg9dctvyngy
```

The task still stays in preparing state forever (tested 6 days then we removed the service which went without problems)

**Describe the results you expected:**

I would assume that the docker swarm master sends its stored auth token to the swarm node to be able to pull the image. After a short time there should be a either running or failed service.

**Additional information you deem important (e.g. issue happens only occasionally):**

When i create the service without --with-registry-auth i get a expected result:

```
Aug 23 04:37:40 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:40.863206643-04:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: access to the requested resource is not authorized"
Aug 23 04:37:44 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:44.373550516-04:00" level=error msg="Not continuing with pull after error: Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\""
Aug 23 04:37:44 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:44.373675224-04:00" level=error msg="pulling image failed" error="Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\"" module=taskmanager task.id=1odmvnc5zgbpzmw6pmwy5nrgf
```

**Comment by nishanttotla** [comment]
It's not immediately evident that this is a `--with-registry-auth` issue, but we'll try to find out.
@geNAZt are you able to create a service that doesn't use private images on your setup?

**Comment by geNAZt** [comment]
Yes i have two Redis Services running using images from dockerhub. They work just fine. Just for info when i use the config.yml created by Docker inside of ~/.docker/ and copy it over to the other nodes and trigger a ``docker pull`` it downloads the image just fine quay.io/gommehdnet/pe-proxy:latest

**Comment by nishanttotla** [comment]
@geNAZt I tried on my machine and was able to start a service from a private image using `--with-registry-auth`. The errors you are getting indicate that tasks are perhaps not getting created.

Could you check if your `quay.io/gommehdnet/pe-proxy:latest` image was actually downloaded on the three nodes? Secondly, after you run the `docker service create` command, what output do you see for `docker service ps gommehdnetpe-proxy`?

**Comment by geNAZt** [comment]
``docker images`` on Node1,2,3:

```
root@Docker-Cluster01:~# docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
quay.io/gommehdnet/pe-proxy         latest              013d546858bf        9 hours ago         153.2 MB
quay.io/gommehdnet/stocker-plugin   latest              65b98a13a2be        4 days ago          754.7 MB
redis                               alpine              46838178915b        2 weeks ago         29.68 MB
```

```
root@Docker-Cluster02:~# docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
quay.io/gommehdnet/pe-proxy         latest              013d546858bf        9 hours ago         153.2 MB
quay.io/gommehdnet/stocker-plugin   latest              65b98a13a2be        4 days ago          754.7 MB
```

```
root@Docker-Cluster03:~# docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
quay.io/gommehdnet/pe-proxy         latest              013d546858bf        9 hours ago         153.2 MB
quay.io/gommehdnet/stocker-plugin   latest              65b98a13a2be        4 days ago          754.7 MB
redis                               alpine              46838178915b        2 weeks ago         29.68 MB
```

So images should be there and should be fine.

This is the ``docker service ps gommehdnet-proxy``:

```
root@Docker-Cluster01:~# docker service ps gommehdnetpe-proxy
ID                         NAME                    IMAGE                               NODE              DESIRED STATE  CURRENT STATE          ERROR
ba1vvtr52j49kpen6l0hdeybf  gommehdnetpe-proxy      quay.io/gommehdnet/pe-proxy:latest  Docker-Cluster03  Running        Running 8 hours ago
be4jlcqleqqfjlekh18xh6zk4   \_ gommehdnetpe-proxy  quay.io/gommehdnet/pe-proxy:latest  Docker-Cluster02  Running        Preparing 8 hours ago
f0c5ukjiabiv5mdjqmmbm4yh6   \_ gommehdnetpe-proxy  quay.io/gommehdnet/pe-proxy:latest  Docker-Cluster01  Running        Preparing 8 hours ago
```

**Comment by nishanttotla** [comment]
Since the images did get downloaded on all nodes, this is not a `--with-registry-auth` issue, but for some reason your tasks aren't starting. Not sure if this is something in the agent loop, I'll look some more.

cc @thaJeztah have you seen something like this before?

**Comment by manast** [comment]
I am getting a very similar behaviour (also in 1.12.1). In my case I am just building an image on the nodes in the cluster. The images appear when running ```docker images```, but in docker daemon logs I get this:
```
Aug 29 16:15:46 caturra docker[9117]: time="2016-08-29T16:15:46.779781894+02:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Aug 29 16:15:47 caturra docker[9117]: time="2016-08-29T16:15:47.216510113+02:00" level=error msg="Not continuing with pull after error: Error: image adleria/proxy:1.0.0 not found"
Aug 29 16:15:47 caturra docker[9117]: time="2016-08-29T16:15:47.216606067+02:00" level=error msg="pulling image failed" error="Error: image adleria/proxy:1.0.0 not found" module=taskmanager task.id=4s5k6xwf16yfp6obmk9z469ug
```

If I on the other hand use official images from docker hub, like redis, mongo, etc, it just works without any issues...

**Comment by manast** [comment]
Another piece of information: If I run the container using docker run instead of docker service, then there are no issues, the image is found and it works normally. These are my start commands:
```
eval "$(docker-machine env caturra)"
docker service create\
 --replicas 1\
 -p 8080:8000\
 -p 443:8443\
 --env PROXY_PORT=8000\
 --name proxy\
 --constraint 'node.hostname == caturra'\
 adleria/proxy:1.0.1
```

```
docker run adleria/proxy:1.0.1
```

**Comment by manast** [comment]
And another piece: It works with docker service if I do not use the ```--constraint``` argument. How this can affect not being able to find local images is beyond my understanding, maybe somebody closer to the source code can understand...

**Comment by manast** [comment]
Btw, any idea why if I create an image without the "host" prefix, i.e. ```adleria``` instead of ```optimalbits/adleria```, the daemon complains that image ```library/adleria``` is missing?

**Comment by nishanttotla** [comment]
@manast could you provide daemon logs for all three nodes? In a previous comment, it seemed like at least one of the containers for the service did get started.

**Comment by manast** [comment]
@nishanttotla I think you mean @geNAZt not me :)

**Comment by nishanttotla** [comment]
That's right, my bad! I did mean @geNAZt :)

**Comment by geNAZt** [comment]
Sorry for the late response:  

This is from Node 1:

``
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.975200382-04:00" level=error msg="network gommehdnet-pe remove failed: network gommehdnet-pe not found" module=taskmanager task.id=9cwypx7dhe30vdirx4xh2ckys
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.976840382-04:00" level=error msg="remove task failed" error="network gommehdnet-pe not found" module=taskmanager task.id=9cwypx7dhe30vdirx4xh2ckys
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.977462655-04:00" level=error msg="network gommehdnet-pe remove failed: network gommehdnet-pe not found" module=taskmanager task.id=azdwm0iiir2lzodlqhne7j7bp
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.977622249-04:00" level=error msg="remove task failed" error="network gommehdnet-pe not found" module=taskmanager task.id=azdwm0iiir2lzodlqhne7j7bp
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.977725045-04:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5m0laifk8u7m0fm0a32wt5h40 node.session=cph8m2nq4g0zaslpcdop6wjp3 task.id=593h40f79her9e9ghr$
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.977792234-04:00" level=error msg="network gommehdnet-pe remove failed: network gommehdnet-pe not found" module=taskmanager task.id=b4fi7ldqa6ia78yn9dz1s8uu5
Aug 23 04:37:09 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:09.977831419-04:00" level=error msg="remove task failed" error="network gommehdnet-pe not found" module=taskmanager task.id=b4fi7ldqa6ia78yn9dz1s8uu5
Aug 23 04:37:10 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:10.061743801-04:00" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=593h40f79her9e9ghrm6k82yp
Aug 23 04:37:31 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:31.785612035-04:00" level=error msg="Error creating service : network gommehdnet-net not found"
Aug 23 04:37:31 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:31.785710671-04:00" level=error msg="Handler for POST /v1.24/services/create returned error: network gommehdnet-net not found"
Aug 23 04:37:40 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:40.863206643-04:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: access to the requested resource is not authorized"
Aug 23 04:37:44 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:44.373550516-04:00" level=error msg="Not continuing with pull after error: Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\""
Aug 23 04:37:44 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:44.373675224-04:00" level=error msg="pulling image failed" error="Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\"" module=taskmanager task.id=1odmvn$
Aug 23 04:37:47 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:37:47-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:20 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:42:20.052069976-04:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5m0laifk8u7m0fm0a32wt5h40 node.session=cph8m2nq4g0zaslpcdop6wjp3 task.id=7hixp3tt8pg4kjx4qw$
Aug 23 04:42:20 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:42:20.099754736-04:00" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=7hixp3tt8pg4kjx4qwyn4hftt
Aug 23 04:42:20 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:42:20-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:38 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:42:38-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:25 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:25.755244136-04:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5m0laifk8u7m0fm0a32wt5h40 node.session=cph8m2nq4g0zaslpcdop6wjp3 task.id=ecd8wheg9dctvyngya$
Aug 23 04:49:25 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:25.812376816-04:00" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=ecd8wheg9dctvyngyascg167k
Aug 23 04:49:26 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:26-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster01 dockerd[6643]: time="2016-08-23T04:49:54-04:00" level=info msg="Firewalld running: false"
``

It says that the gommehdnet-pe network is not available but it is:

``docker network ls``

``
root@Docker-Cluster01:/var/log# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
03aa482e03f0        bridge              bridge              local
4a9874a8cf25        docker_gwbridge     bridge              local
7q2lub0oum0t        gommehdnet-pe       overlay             swarm
61016e5df85e        host                host                local
cmbgm3emkhfs        ingress             overlay             swarm
eb0ff701e1d8        none                null                local
0juby4gk0avz        stocker-net         overlay             swarm
``

``docker network inspect``

``
root@Docker-Cluster01:/var/log# docker network inspect gommehdnet-pe
[
    {
        "Name": "gommehdnet-pe",
        "Id": "7q2lub0oum0tz42k5z452fvre",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "258"
        },
        "Labels": {}
    }
]
``

Node 3 (the one who started the container):

``
Aug 23 04:37:09 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:09.972549371-04:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=593h40f79her9e9ghrm6k82yp
Aug 23 04:37:10 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:10-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:12 Docker-Cluster03 ntpd[5678]: Deleting interface #42 veth3510d30, fe80::70fe:ebff:fe4a:bc24#123, interface stats: received=0, sent=0, dropped=0, active_time=181 secs
Aug 23 04:37:12 Docker-Cluster03 ntpd[5678]: peers refreshed
Aug 23 04:37:41 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:41.172604570-04:00" level=error msg="Attempting next endpoint for pull after error: unauthorized: access to the requested resource is not authorized"
Aug 23 04:37:42 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:42.449913014-04:00" level=error msg="Not continuing with pull after error: Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\""
Aug 23 04:37:42 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:42.450061722-04:00" level=error msg="pulling image failed" error="Error: Status 403 trying to pull repository gommehdnet/pe-proxy: \"{\\\"error\\\": \\\"Permission Denied\\\"}\"" module=taskmanager task.id=7hixp3$
Aug 23 04:37:46 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:46-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:47 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:47-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:47 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:47-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:47 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:47-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:47 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:47-04:00" level=info msg="Firewalld running: false"
Aug 23 04:37:47 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:37:47.578269364-04:00" level=error msg="containerd: notify OOM events" error="cgroup path for memory not found"
Aug 23 04:37:51 Docker-Cluster03 ntpd[5678]: Listen normally on 43 veth4fba932 fe80::607c:b9ff:fea9:f4cc UDP 123
Aug 23 04:37:51 Docker-Cluster03 ntpd[5678]: peers refreshed
Aug 23 04:42:20 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:20.046064214-04:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=7hixp3tt8pg4kjx4qwyn4hftt
Aug 23 04:42:20 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:20-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:20 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:20-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:22 Docker-Cluster03 ntpd[5678]: Deleting interface #43 veth4fba932, fe80::607c:b9ff:fea9:f4cc#123, interface stats: received=0, sent=0, dropped=0, active_time=271 secs
Aug 23 04:42:22 Docker-Cluster03 ntpd[5678]: peers refreshed
Aug 23 04:42:37 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:37-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:37 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:37-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:38 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:38-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:38 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:38-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:38 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:38-04:00" level=info msg="Firewalld running: false"
Aug 23 04:42:38 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:42:38.412260097-04:00" level=error msg="containerd: notify OOM events" error="cgroup path for memory not found"
Aug 23 04:42:42 Docker-Cluster03 ntpd[5678]: Listen normally on 44 veth71ddb81 fe80::70ef:3aff:fe8d:4a9e UDP 123
Aug 23 04:42:42 Docker-Cluster03 ntpd[5678]: peers refreshed
Aug 23 04:49:25 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:25.748375946-04:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=ecd8wheg9dctvyngyascg167k
Aug 23 04:49:26 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:26-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:26 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:26-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:28 Docker-Cluster03 ntpd[5678]: Deleting interface #44 veth71ddb81, fe80::70ef:3aff:fe8d:4a9e#123, interface stats: received=0, sent=0, dropped=0, active_time=406 secs
Aug 23 04:49:28 Docker-Cluster03 ntpd[5678]: peers refreshed
Aug 23 04:49:53 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:53-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:54-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:54-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:54-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:54-04:00" level=info msg="Firewalld running: false"
Aug 23 04:49:54 Docker-Cluster03 dockerd[6640]: time="2016-08-23T04:49:54.604474359-04:00" level=error msg="containerd: notify OOM events" error="cgroup path for memory not found"
Aug 23 04:49:58 Docker-Cluster03 ntpd[5678]: Listen normally on 45 veth34213dc fe80::588f:80ff:fef9:9101 UDP 123
Aug 23 04:49:58 Docker-Cluster03 ntpd[5678]: peers refreshed
``

**Comment by thaJeztah** [comment]
I know of two prior issues with quay.io repositories and docker 1.12; https://github.com/docker/docker/issues/23792, and https://github.com/docker/docker/issues/25211, but the first one was a DNS issue, second one was resolved with the `--with-registry-auth` option. I don't have insight into the authentication mechanism that quay.io uses, wondering if there's (for example) a rate limit, or if authentication tokens are tied to a specific IP-address?

**Comment by RangerMauve** [comment]
I think I might be having the same problem. In my case it started with having 4 copies of a service when I had the scale set to 1. This happened after my cluster of three nodes got split up and had trouble communicating with each other. I'm not sure why it scaled up to that many, but there was something like three on one VM and one on another. After scaling it 1 the load balancer wasn't working as I couldn't connect to the published port anywhere but the node that was actually running the container. I tried scaling down to 0 and then back to 1, but after scaling to 1, it was unable to start the task with the same error messages being reported above. I only looked at the daemon logs at the end of all this so I might have missed something.

**Comment by nishanttotla** [comment]
@RangerMauve your issue sounds like a routing mesh issue. Some related issues have been fixed since 1.12.1. Since your tasks were able to start, doesn't sound like you had registry authentication issues.

**Comment by RangerMauve** [comment]
@nishanttotla Yeah, I just realized after I posted already. I'll look into it some more tomorrow. 😛

**Comment by ebarlaskar** [comment]
Did anyone manage to solve @manast  issue? Even I am getting the same problem. In my case I am building an image on the nodes in the cluster and also I have tried to use the images from my docker hub registry. I can pull the images from my hub registry in each of the swarm nodes but it doesn't work with docker service create command. 

These are my start commands:

ubuntu@swarmmasternew:/$ sudo docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username : <myDockerId>
Password: *****
Login Succeeded

ubuntu@swarmmasternew:/$ sudo docker service create --name streaming_dataset --network swarm-network  --constraint "node.nodename==swarm1" --with-registry-auth <dockerid>/repository:dataset
l3emhilu51c00ivijkk4hag3z
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

But with service ls I see that the service fails to start:

ubuntu@swarmmasternew:/$ sudo docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
81ddszzjwjl9        streaming_dataset   replicated          0/1                 <dockerid>/repository-dataset   

ubuntu@swarmmasternew:/$ sudo docker service ps streaming_dataset
ID                  NAME                  IMAGE                              NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
ohxmvg2vel6e        streaming_dataset.1   eshabarlaskar/repository:dataset                       Running             Pending 29 seconds ago                       

However, as @manast said even I  can use official images from docker hub, like redis, nginx, etc, it just works without any issues.

Would really appreciate any kind of help.

**Comment by opera443399** [comment]
@ebarlaskar 
get logs/inspect output like this:
```bash
docker service logs --tail 10 your_service_name
docker service inspect --pretty your_service_name
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
