### ISSUE TITLE
Remote Api: exec prepend some strange bytes in front of output

### ISSUE THREAD

**Issue by GongT** [moby/moby#25975]
**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-26.git1ecb834.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      1ecb834/1.10.3
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-26.git1ecb834.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      1ecb834/1.10.3
 Built:
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.614 GB
 Data Space Total: 42.9 GB
 Data Space Available: 41.29 GB
 Metadata Space Used: 360.4 kB
 Metadata Space Total: 109.1 MB
 Metadata Space Available: 108.7 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.122 (2016-04-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.7-300.fc24.x86_64
Operating System: Fedora 24 (Twenty Four)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 4
Total Memory: 3.842 GiB
Name: localhost.vm
ID: DJJT:4CSJ:ARKC:JQHU:DE2Z:6Z4S:CKP2:RVQD:KQSI:BJWS:LABC:ORFI
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
**> uname -a**
Linux localhost.vm 4.6.7-300.fc24.x86_64 #1 SMP Wed Aug 17 18:48:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**> cat /etc/fedora-release**
Fedora release 24 (Twenty Four)

**> curl --version**
curl 7.47.1 (x86_64-redhat-linux-gnu) libcurl/7.47.1 NSS/3.25 zlib/1.2.8 libidn/1.33 libpsl/0.13.0 (+libidn/1.33) libssh2/1.7.0 nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL

**Steps to reproduce the issue:**
1. create and run any container ( I'm using `docker run -d --name nginx nginx:alpine` for example )
2. put a file in it `docker exec nginx sh -c 'echo -e "abc\n123\n✓" > /xxx'`
3. run `docker exec nginx cat /xxx | hexdump`
4. run `hexdump /xxx` thru exec and exec/start api , `hexdump` the api result

**Describe the results you received:**
the API prepend some strange bytes in front of output

> 0000000 **_0001 0000 0000 0c00**_ 6261 0a63 3231 0a33
> 0000010 9ce2 0a93
> 0000014

( and the `0c` may change in different try?)

**Describe the results you expected:**
two output is same

**Additional information you deem important (e.g. issue happens only occasionally):**
also tried in Ubuntu 14.04.5 LTS

testing script: (`./test.sh | hexdump`)

``` bash
#!/usr/bin/env bash

CURL="curl --unix-socket /var/run/docker.sock --insecure --silent"

RET=`
${CURL} \
    http:/v1.20/containers/nginx/exec \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"Cmd":["cat", "/xxx"],"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"DetachKeys":"ctrl-p,ctrl-q","Tty":false}'
`

if [ $? -ne 0 ]; then
    echo $RET
    exit
fi

Id=`echo ${RET} | grep -oE '"[a-f0-9]+"' | grep -oE '[a-f0-9]+'`

${CURL} \
    http:/v1.20/exec/${Id}/start \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"Detach": false, "Tty": false}'
```

**Comment by GongT** [comment]
In my test script,
if change "Tty" to true
will work well

**Comment by cpuguy83** [comment]
This is the prefix for stdout/stderr since both streams are being multiplexed onto a single stream.
TTY doesn't have this problem because the TTY is a single stream (no stdout/stderr).

See https://github.com/docker/docker/blob/master/pkg/stdcopy/stdcopy.go
