### ISSUE TITLE
Stop re-creating shortcuts on my desktop

### ISSUE THREAD

**Issue by oliversalzburg** [moby/moby#25973]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 317
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: OV6J:OPDY:DVEB:U2KO:DISY:YJAH:3BIO:RITP:KJQY:T5KS:5U3R:RKFK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Docker for Windows or apply an update for Docker for Windows

**Describe the results you received:**
You will create a shortcut for Docker for Windows on my desktop.

**Describe the results you expected:**
You don't create a shortcut on my desktop.

**Comment by friism** [comment]
@oliversalzburg thanks for reporting, I've noticed this also. We already have an internal issue to address this by making creating the desktop icon optional.

**Comment by oliversalzburg** [comment]
Just FYI, this is even a point Microsoft is talking about themselves in the [Windows Application Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742493.aspx):
> **If you do only one thing...**
Don't abuse the desktop—keep users in control. If your target users are likely to use your program frequently, provide an option during setup to put a shortcut on the desktop, unselected by default.

That being said, I don't really understand why this is done/offered *at all*. If someone is capable of using Docker, I'm sure they're capable of dragging and dropping a shortcut to their desktop if they feel inclined to do so.  
The application that is started through the shortcut is, by default, also automatically started when Windows starts, making the existence of the shortcut even more pointless and this use case does not satisfy the "frequently used" requirement IMHO.

**Comment by oliversalzburg** [comment]
I have 1.12 installed, updated yesterday and there is still a new shortcut being created on my desktop. Am I misinterpreting the `version/1.12` tag?

Is this a difficult change to make, is this something you're not planning to change or why is there no progress on this issue? Can someone point me in the right direction so I can submit a PR?

**Comment by cpuguy83** [comment]
@oliversalzburg It means it is the version that the issue was reported against.
The issue is still open, as such is not resolved.

**Comment by oliversalzburg** [comment]
@cpuguy83 Could you point me to the installer sources? I'm having a hard time finding them in the repo. I'd love to start a PR for this.

**Comment by cpuguy83** [comment]
@friism would know best, but I don't think this is open source.

**Comment by oliversalzburg** [comment]
@cpuguy83 Ah, I see. That's disappointing. Thanks for letting me know.

**Comment by Schweinepriester** [comment]
+1

**Comment by thaJeztah** [comment]
@oliversalzburg @Schweinepriester could you reopen this issue in the docker for windows issue tracker? Given that this issue is specific to Docker for Windows, perhaps it's best to open the issue there https://github.com/docker/for-win/issues

**Comment by oliversalzburg** [comment]
Reported as https://github.com/docker/for-win/issues/246

**Comment by thaJeztah** [comment]
Thanks!

**Comment by oliversalzburg** [comment]
Aaaaaand it's back again! \o/
