### ISSUE TITLE
Docker remote api 1.24 /auth do not return IdentityToken.

### ISSUE THREAD

**Issue by Tairy** [moby/moby#26000]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 127
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: BB2H:UQSW:MGNW:V6CB:AU2D:P243:OQ5B:X4AB:E2C5:PANL:4S3O:2ZEY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 56
 System Time: 2016-08-25T06:32:18.298982269Z
 EventsListeners: 1
Username: tairy
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine

**Steps to reproduce the issue:**
1. Post data to docker remote api `/auth` like below, it should return `IdentityToken`, but I only get `Status`.

```
{"serveraddress":"https://my-registry.com:5000","username":"xxx","password":"xxx"}
```

Response to me:

```
{"Status":"Login Succeeded"}
```

**Describe the results you received:**

```
HTTP/1.1 200 OK
{
     "Status": "Login Succeeded"
}
```

**Describe the results you expected:**

It should contain an IdentityToken field.

```
HTTP/1.1 200 OK
{
     "Status": "Login Succeeded",
     "IdentityToken": "9cbaf023786cd7..."
}
```

**Comment by jhorwit2** [comment]
I was able to replicate this hitting docker hub. 

```
curl --unix-socket /var/run/docker.sock -X POST http://localhost/auth --data '{"serveraddress": "https://index.docker.io/v1", "username":"xx", "password": "xxxx"}'
```

**Comment by cpuguy83** [comment]
AFAICT the only reason this wouldn't show up is if the token is empty, and I'm not sure why it would be empty.

ping @dmcgowan

**Comment by dmcgowan** [comment]
@Tairy @jhorwit2 which authorization server are you using? Could you show me a curl directly to the authorization?

**Comment by jhorwit2** [comment]
@dmcgowan 
```
curl --unix-socket /var/run/docker.sock -X POST http://localhost/auth --data '{"serveraddress": "https://index.docker.io/v1", "username":"xx", "password": "xxxx"}'
``` 

?

**Comment by dmcgowan** [comment]
@jhorwit2: this is a curl to the docker daemon. The auth server is used by the registry to provide identity tokens and access tokens for the registry. I want to see the authorization server is returning an identity token according to spec (see https://docs.docker.com/registry/spec/auth/token/#/requesting-a-token). Otherwise the username and password only response is the expected output.

**Comment by jhorwit2** [comment]
@dmcgowan It's a curl to the daemon requesting docker hub (note the server address) to authorize my credentials. I have no idea what the auth server is for docker hub.

**Comment by dmcgowan** [comment]
@jhorwit2 This issue is related to identity tokens on a private registry, the hub does not currently return identity tokens so there is nothing unexpected about your curl.

**Comment by jhorwit2** [comment]
my bad 👼

**Comment by Tairy** [comment]
I am sorry that I just see this message.

This is my
```
curl --unix-socket /var/run/docker.sock -X POST http://localhost/auth --data '{"serveraddress": "https://my-private-registry/v2/", "username":"XXX", "password": "XXX"}'
```

and I got 

```
{"Status":"Login Succeeded"}
```

without IdentityToken.

**Comment by sam-thibault** [comment]
This is an old issue, and behavior appears expected.  I will close this one as stale.
