### ISSUE TITLE
node state and availability not findable in docs search

### ISSUE THREAD

**Issue by sfsmithcha** [moby/moby#26056]
Feedback on finding Node state and availability in the docs:

Doc is here: https://docs.docker.com/engine/swarm/manage-nodes/#manage-nodes-in-a-swarm

 I searched for "status", "node status", "node state", "availability", "node availability", "swarm availability". I assumed there was no such page so I didn't search for "Reachable", which would have been my next keyword, but it looks like that one correctly points to that page. Also, I went to the swarm-mode overview page looking for some sort of "concepts" or "keywords" page, followed the url to the "key-concepts" page which did not mention any details node status and noticed that the only follow-up URL at the bottom redirected me back to swarm-mode overview. I didn't suspect to go to the "manage nodes" headline as I imagined that would cover the various leave/rm/demote/promote flows, rather than document the possible node states

**Comment by mstanleyjones** [comment]
"node state" doesn't appear in the page at all so I don't know how it would result in that page coming up. "Node availability" does, but it is only a pretty small part of the page. Maybe the page needs a better title?

**Comment by mstanleyjones** [comment]
@johndmulhausen PTAL

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
