### ISSUE TITLE
CentOS7 missing dependecy in rpm e2fsprogs

### ISSUE THREAD

**Issue by vondeetzen** [moby/moby#26054]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
A virtual machine of a virtual server hosting provider. On this machine e2fsprogs is removed in the default install.

**Steps to reproduce the issue:**
1. Remove e2fsprogs
2. Ensure docker was not installed before or remove it and remove /var/lib/docker
3. Install docker following https://docs.docker.com/engine/installation/linux/centos/
4. Try to start docker

**Describe the results you received:**
Docker does not start

```
Aug 26 19:51:32 centos dockerd[4639]: time="2016-08-26T19:51:32.404762982Z" level=info msg="devmapper: Error while creating filesystem ext4 on device docker-253:3-1045948-base: exec: \"mkfs.ext4\": executable file not found in $PATH"
```

**Describe the results you expected:**
Docker starts successfully because after installing the rpm file the dependency e2fsprogs is included

**Additional information you deem important (e.g. issue happens only occasionally):**
I know it is rare that e2fsprogs is missing on a default CentOS install. Some providers of virtual hosting are removing it.

**Comment by thaJeztah** [comment]
Error originates here; [daemon/graphdriver/devmapper/deviceset.go#L599-L623](https://github.com/docker/docker/blob/c2f57291ac04a1d582d7fcdedda7b1ad707543d5/daemon/graphdriver/devmapper/deviceset.go#L599-L623)

I'm not sure we could simply add this as a dependency, because the daemon is fully capable to run without (but with a different storage driver). Possibly detection in the device mapper driver should be improved

ping @rhvgoyal

**Comment by rhvgoyal** [comment]
What daemon options are being passed. I think our default should be xfs and by default it should be trying to create xfs filesystem. And that means mkfs.xfs should be available (provided by xfsprogs).

Dependency on e2fsprogs is must only if ext4 is default filesystem for container rootfs. If xfs is default, then there is no point in forcing installation of e2fsprogs on system.

**Comment by vondeetzen** [comment]
mkfs.xfs was also not available on the machine.

**Comment by vondeetzen** [comment]
Sorry missed the daemon options. It was a default fresh docker installation.

**Comment by rhvgoyal** [comment]
Where did you get docker 1.12? I see that in redhat docker rpm we have dependency Requires on xfsprogs.  So if you did not install docker rpm and built it from somewhere else, xfsprogs will not be pulled in.

**Comment by thaJeztah** [comment]
@rhvgoyal looks like it's not in the RPM specs in this repo; https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec

However, it's only required for device mapper, should it be a _dependency_ or _recommendation_ ?

**Comment by rhvgoyal** [comment]
I am leaning towards making it a dependency.

**Comment by vondeetzen** [comment]
cat /etc/yum.repos.d/docker.repo
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg

xfsprogs was not installed as a dependency.
