### ISSUE TITLE
Output docker run command with arguments

### ISSUE THREAD

**Issue by f1yegor** [moby/moby#26062]
I want to see the command with which docker container was started. 
Ex. `docker run --net=host --name -p8080:80 -e EVN_PARAM1=... -v /outside:/inside`
Now I can construct this command by looking at `docker inspect` output, but would be nice to have more streamlined way to do this, some new command like `docker show-create`

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
