### ISSUE TITLE
Get error "exec format error"  when restart container

### ISSUE THREAD

**Issue by zjxpsetp** [moby/moby#26072]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
`root@root:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-57775-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.96 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.38 GB
 Metadata Space Used: 3.83 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.829 GiB
Name: doctor
ID: MBX4:LN2T:RZ3I:OZYJ:T57U:KR3A:CKCJ:IDXZ:NVAN:HQOE:MDXA:TAUJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:``

**Additional environment details (AWS, VirtualBox, physical, etc.):**



**Steps to reproduce the issue:**
1.
2.
3.


**Describe the results you received:**
standard_init_linux.go:175: exec user process caused "exec format error"

**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**
When we restart our container, we got this error. It seems that someting wrong 
with the script in our entrypoint.  But we indeed can start this container at the 
beginning. And the same image works well in other server.

Another question is when we remove this image using `docker rmi` and pull again,
 `docker images` show that the image has been created several 
days( The first time when we pull the image)? Why docker store these message
 even we rm the image?
```

**Comment by cpuguy83** [comment]
Can you provide more details?
`exec format error` comes from the kernel when trying to execute something that is for another platform for architecture.
It can also occur in simpler scenarios, like running a shell script with no `#!/bin/bash`, for example.

**Comment by zjxpsetp** [comment]
@cpuguy83 thanks for your response.
 Yes, our entrypoint is a shell script start with `#!/bin/bash`. We just migrate from docker 1.9 & 1.10 to 1.12.0/1 but meet this problem. 
It is not easy to reproduce this defect (we are trying now). 
We deploy the same image in hundreds of servers (Ubuntu 14.04 and kernel version is from 3.13 to 4.xx). The more interesting is that most of servers work well. Even sometime all work well. But this defect may be occured when the container restart or run `service docker restart`. That means when we first start the container it works well, but may get this error when restart it.

I found this error means  something wrong with our entrypoint script from runc source code but why it can work when we first start? And we are using devicemapper as our storage dirver, I don't know whether  they have the relationship.

**Comment by zjxpsetp** [comment]
@cpuguy83 
More info about this defect.
When this defect happened, we found the following message by "docker history", why the base images are missing.

1b0ed4fe3b6f        12 weeks ago        /bin/sh -c #(nop) ENTRYPOINT ["sh" "/opt/star   0 B                 
<missing>           12 weeks ago        /bin/sh -c chmod -R 655 /opt/bbo/  && chmod 7   27.53 MB            
<missing>           12 weeks ago        /bin/sh -c #(nop) ADD file:446ec33955dcdb2a55   693 B               
<missing>           12 weeks ago        /bin/sh -c #(nop) ADD file:435172fa402c81910c   950 B               
<missing>           12 weeks ago        /bin/sh -c #(nop) ADD file:a2df17955d436971da   3.809 kB            
<missing>           12 weeks ago        /bin/sh -c #(nop) ADD file:75c6b48eaee684e3cd   30.17 kB            
<missing>           12 weeks ago        /bin/sh -c #(nop) ADD file:72cc573bb1c2ce7f14   27.53 MB            
<missing>           7 months ago        /bin/sh -c cd /opt && bundle install            74.72 MB            
<missing>           7 months ago        /bin/sh -c #(nop) ADD file:1fd6620c769e550579   902 B               
<missing>           7 months ago        /bin/sh -c apt-get -y update && apt-get insta   284.4 MB            
<missing>           7 months ago        /bin/sh -c echo 'deb http://archive.ubuntu.co   2.015 kB            
<missing>           7 months ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           7 months ago        /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
<missing>           7 months ago        /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB            
<missing>           7 months ago        /bin/sh -c #(nop) ADD file:482777a8ad62044151   187.7 MB

**Comment by zjxpsetp** [comment]
We encounter this error again. And get the following error when we try to download another version of this image:
docker: Error pulling image (3.67) from 10.xxx.xxx.xxx:5000/xxx/xxx, failed to register layer: ApplyLayer exit status 1 stdout:  stderr: mkdir /etc/al
ternatives: input/output error.
See 'docker run --help'.

@cpuguy83

**Comment by thaJeztah** [comment]
Closing this because of age, and from the description, I don't think this is a bug, but may be something in the environment
