### ISSUE TITLE
Configure Docker daemon with “icc” and “disable-legacy-registry” on Debian 8.4

### ISSUE THREAD

**Issue by thibentran** [moby/moby#26095]
Hello,

I try to configure the Docker daemon on **Debian 8.4** with **Docker 1.12.1**.

Note: I added a post on [Docker Community Forums](https://forums.docker.com/t/configure-docker-daemon-with-icc-and-disable-legacy-registry-on-debian-8-4/21073) but I got no answer.
# Goal

I would like to use the "icc" and "disable-legacy-registry" options of the Docker daemon. My aim is to be compliant with the rules of the Docker Bench for Security v1.1.0. In particular, I check the 2.1 and 2.13 rules.
# Issue

However, both options have no effect when using the "daemon.json" file or "docker.service" file.
# Tried solutions
## "docker.service" file
1. I replaced `ExecStart=/usr/bin/dockerd -H fd://` by `ExecStart=/usr/bin/dockerd -H fd:// --icc=false --disable-legacy-registry=true` in _/lib/systemd/system/docker.service_.
2. I execute `systemctl daemon-reload`
3. I execute `systemctl restart docker`

Rules 2.1 and 2.13 have still "WARN" status with Docker Bench for Security.

But when I execute "ps" I see that the launch command is correct: `/usr/bin/dockerd -H fd:// --icc=false --disable-legacy-registry`
## "daemon.json" file
1. I create _/etc/docker/daemon.json_ file and add: `{ "icc": false, "disable-legacy-registry": true }`
2. I execute `systemctl restart docker`

Rules 2.1 and 2.13 have still "WARN" status with Docker Bench for Security.

But if I execute `docker daemon --icc=false --disable-legacy-registry=true`, I get:

> unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: disable-legacy-registry: (from flag: true, from file: true), icc: (from flag: false, from file: false)

Thus, it means that Docker daemon see the option.
## "docker daemon" command

If I bypass the autolaunching of the daemon and I manually execute the command `docker daemon --icc=false --disable-legacy-registry=true`, then it works! The two rules of the Docker Bench for Security are in "PASS" status.

To have more information, I execute the "ps" command and see that a process was launched with:
`dockerd --icc=false --disable-legacy-registry=true`

But when I execute `dockerd --icc=false --disable-legacy-registry=true` myself, it does NOT work.
# Context

_docker version_

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

_docker info_

```
Containers: 24
 Running: 11
 Paused: 0
 Stopped: 13
Images: 213
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 746
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.818 GiB
Name: hbddc2685
ID: KTAT:QWRS:QW46:CVQA:AERW:YZYX:T3CQ:P33S:QSUA:KVNX:SJED:4O5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Comment by sam-thibault** [comment]
This is an old question.  I will close it as stale.
