### ISSUE TITLE
Named volumes mysteriously vanish and come back after restart

### ISSUE THREAD

**Issue by withinboredom** [moby/moby#26157]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 26
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: moby
ID: ZGAL:XHQS:FSR3:IO3L:QKYK:3ASA:VSKA:DIZV:SAFD:X5SA:4PPO:3GE2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 89
 System Time: 2016-08-30T18:08:57.141083394Z
 EventsListeners: 1
Username: withinboredom
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 localhost:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for mac

**Steps to reproduce the issue:**
Unknown how to reproduce ... it appears to be completely random. Smells like a race condition.

docker-compose file would look something like:

``` yml
service_name:
  image: ubuntu:16.04
  volumes:
    - ./app:/app
    - named1:/app/test
    - named2:/app/test2
```

Randomly -- and extremely rarely, the named volumes will not be present inside a freshly started container. I've gotten reports from coworkers where they've seen the bind mount not being present as well.

**Describe the results you received:**
I had no volumes, just an empty directory

**Describe the results you expected:**
I had mounts, with the files that should be there

**Additional information you deem important (e.g. issue happens only occasionally):**
I searched for an issue similar but couldn't find one...

**Comment by justincormack** [comment]
It might help if you can provide the logs from Docker when this happens. You can use the diagnose function in Docker for mac and we can look at the logs and see if there are errors - it may well be a Docker for Mac specific issue.

**Comment by gumho** [comment]
My colleagues and I have been seeing this issue multiple times. We are also using Docker for Mac and it seems to be happening on both the 1.12.0-rc2-beta and the 1.12.0 stable. The only way to fix the problem when it comes up is quitting Docker for Mac or killing all the Docker processes and restarting the daemon.

**Comment by justincormack** [comment]
Could it be related to https://github.com/docker/docker/issues/25326 (for the bind mount case).

The named volume case is odd, I don't see how it can be related to Docker for Mac as these are exactly the same as normal named volumes. But it has never been reported as an issue. The logs when it happens would be the best way to see what has happened as some failure ought to be logged.

**Comment by withinboredom** [comment]
Everyone on the team is aware of this issue, and when it happens again one of us will post the logs.

**Comment by thaJeztah** [comment]
@withinboredom is this still an issue for you?

**Comment by jalogut** [comment]
Hi, I am facing the same issue if I configure a bind mount subdirectory as named volume. 

This is my configuration:

* Docker for mac: 18.06.1-ce-mac73

```
version: "3"

services:
  phpfpm:
    image: modestcoders/php:7.1-fpm
    volumes: &appvolumes
      - .:/var/www/html:delegated
      - app-vendor:/var/www/html/vendor
```

In my case I put vendor in a named volume, so it does not get synced and improves performance. I use `docker cp` to replicate the content in my host. Everything goes weel but from time to time the name volume stops working and the vendor folder starts getting synchronised.

Although there is no specific way to reproduce that, I noticed that when it happens, it is because a file is modified inside the vendor folder. That can be inside the container or in the host.

It is like sometimes, when docker notices a change inside the vendor, it forgets that it is a named volume and starts syncing it because the parent folder is a bind mount.

In order to recover the volume, sometimes is enough by spinning up the container again and sometimes I even need to restart de docker app.

Is that a bug? Or is my approach wrong?

Thanks for clarifying.

**Comment by cpuguy83** [comment]
That should be exactly what's happening unless someone changed this logic.

**Comment by jalogut** [comment]
Hi @thaJeztah 

Well I do not think that the order is the problem in my case. Named volumes are always properly created. Issues arise later while developing. At some point if I a file is edited in the named volume, docker forgets about the volume and starts binding everything ¯\_(ツ)_/¯

**Comment by kolyshkin** [comment]
> I think you were working on something similar in #37704

@thaJeztah nope, that one was about user-specified mounts vs the built-in ones (i.e. mounts coming from the oci spec). User mounts are/were always sorted in a proper way so one can't shadow another.

It looks like a run-time error to me (like a volume is unmounted some time later). I do not know what "delegated" mode does, but it's probably not playing well with a bind-mounted volume underneath.

**Comment by jalogut** [comment]
Hi @thaJeztah 

Yeah, it seems to be a run-time error. Unfortunately removing `:delegated` option does not fix it, I just tested it. `:delegated` is just a type to bind folders to make them more performant on docker for mac, see:

- https://docs.docker.com/docker-for-mac/osxfs-caching/#tuning-with-consistent-cached-and-delegated-configurations

> delegated: the container’s view is authoritative (permit delays before updates on the container appear in the host)

IMHO the problem has nothing to do with the bind type but with the fact the a named-volume does not seem to behave properly when it is contained inside a bind mounted directory.

**Comment by thaJeztah** [comment]
Yes, wondering if this could be something in Docker for Mac getting confused which mount to sync to/from due to the overlapping paths 🤔. Don't know how those internals work, so perhaps it's a silly thought.

**Comment by markoshust** [comment]
I chatted with @jalogut outside of this thread briefly and am definitely noticing a bug, however I believe it is one we should *NOT* fix for the time being.

I'm able to consistently replicate the bug. Given this docker compose file:

```
version: "3"

services:
  phpfpm:
    image: modestcoders/php:7.1-fpm
    volumes:
      - .:/var/www/html:delegated
      - app-vendor:/var/www/html/vendor

volumes:
  app-vendor:
```

When running `docker-compose up`, the root folder consistently bind mounts into `/var/www/html`. There are two ways to replicate the issue.

Way 1:
- Run `composer require psr/log` on the host machine from the root folder. The artifacts built to `vendor` on the host are synced back to the container. This is the bug.

Way 2:
- Run `composer require psr/log` from within the container after exec'ing into it as root. The artifacts are built to `vendor` within the container, but are not synced back to the host. This is correct.
- Exit the container and run `docker cp CONTAINER_ID:/var/www/html/vendor ./`. This correctly copies the `vendor` folder back to the host. Now, run `touch vendor/test1` on the host. Connect back to the container by exec'ing into it, and you can do `ls vendor` to notice the test1 file has synced back to the container. This is the bug.

Now, I'm highly recommending NOT to fix this bug as while the syncing actions are unexpected, I can basically confirm that named volumes are are still known as (performant) named volumes as far as the container is concerned. From my experience after triggering the sync with a docker cp, the volumes are still extremely performant! This gives credence that while the syncing action is probably a bug, it is an extremely useful bug as it appears to solve the ever-lasting issues of performance with bind mount filesystems on Docker for Mac.

I'd actually recommend this not be considered a bug and somehow moved into Docker for Mac core, or just completely ignored and we can use this configuration as it stands today if we wish. I'm using this configuration on my Magento 2 docker setup (https://github.com/markoshust/docker-magento/blob/master/compose/magento-2/docker-compose.yml) that has over 100,000 files on a bind mount, by triggering the docker cp on the start script immediately after starting the containers (https://github.com/markoshust/docker-magento/blob/master/compose/magento-2/bin/start -- look at the `bin/copydirall` command). After implementing this a few days back, this is the best performance I've ever had with Docker for Mac, bind mounts immediately sync, and named volumes appear to still be working and referencing properly from within the containers.

**Comment by huy-nguyen** [comment]
Any updates? I've run into this problem many times recently and wondering if there's a official explanation or if there has been any progress towards fixing it.

**Comment by sznowicki** [comment]
Bump please. This is super annoying. I'm trying to get a correct pattern on Mac to avoid sharing `node_modules` between docker container and host but everything I try fails hard.

**Comment by bsousaa** [comment]
Since this issue is related with Docker Desktop on Mac please open the issue at https://github.com/docker/for-mac with reproducible steps.
