### ISSUE TITLE
BUG: docker-compose running on Windows doesn't pull images from private Registry

### ISSUE THREAD

**Issue by gabrielstein** [moby/moby#26198]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: 3NYZ:RZBK:ZVUJ:GAHH:4TXY:U7CS:5V3O:L5VG:5K67:RUNK:PECQ:SGLP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

`OS: Windows 10 Pro
` Two private registry tested

**Steps to reproduce the issue:**

1.docker login private.registry.tld(Should result: Login Successful)

```
C:\Users\user\test_project>docker login  private.registry.tld
Username (chucknorris):
Password:
Login Succeeded

```

2.docker-compose up -d

```
C:\Users\user\test_project>docker-compose up -d
Pulling npm-test (private.registry.tld/npm-boiler:latest)...
ERROR: Get https://private.registry.tld/v2/npm-boiler/manifests/latest: unauthorized: authentication required

```

3.Using docker-compose pull

```

ERROR: Get https://private.registry.tld/v2/npm-boiler/manifests/latest: unauthorized: authentication required

```

4.If I pull them one by one works 

```
C:\Users\user\test_project>docker pull private.registry.tld/npm-boiler
Using default tag: latest
latest: Pulling from npm-boiler
8ad8b3f87b37: Downloading [======>                                            ] 6.291 MB/51.37 MB
751fe39c4d34: Downloading [======================>                            ] 8.257 MB/18.53 MB

```

5.insecure-registry already used, doesn't works.

What should I do? Can I use docker-compose inside Windows? Private-Registry Problems?

I will appreciate your help, thank you!

**Comment by friism** [comment]
I don't quite understand why you're getting that error, but I think the first problem is that you're running this against a Linux Docker daemon. You need to run a Windows Docker daemon to pull and run Windows Docker images. I posted an overview here: https://forums.docker.com/t/linux-and-windows-images-side-by-side/20518/4

If you fix that, I think you'll find that docker-compose won't work on Windows. This is because Compose relies on overlay networking support that's not yet ready on Windows.

This is probably as far as you'll get:

```
version: '2'
services:
  test:
    image: friism/foo-vote:win
    networks:
      - nat
networks:
  nat:
    external: true
```

```
docker-compose up
Pulling test (friism/foo-vote:win)...
win: Pulling from friism/foo-vote
Digest: sha256:877371808abe9ab20a494dc653da64583efc3e81244fc695d86ff5685e130688
Status: Downloaded newer image for friism/foo-vote:win
Creating composeprivaterepo_test_1

ERROR: for test  Windows does not support disconnecting a running container from a network
ERROR: Encountered errors while bringing up the project.
```

**Comment by gabrielstein** [comment]
Hi!

Thank you for quickly answer!

> I don't quite understand why you're getting that error, but I think the first problem is that you're running this against a Linux Docker daemon

Well, I just downloaded Docker for Windows and then installed it with next=>next... finish. What should I do, to install the Windows Docker Daemon? And where is it documented?

I tried this example, and it works: https://docs.docker.com/compose/wordpress/

But why isn't possible with my private registry? Should I post the logs from my registry?

**Comment by gabrielstein** [comment]
And BTW: I build it and pushed it using a linux machine, and it runs without problems on Linux/Mac environments.

**Comment by friism** [comment]
To run Windows Docker containers, you have to install the Windows Docker engine. That's what's outlined here: https://forums.docker.com/t/linux-and-windows-images-side-by-side/20518/3

(we know this is a bit confusing, and we're working on also shipping the Windows Docker engine in Docker for Windows. At the moment Docker for Windows only includes a Linux Docker setup)

**Comment by gabrielstein** [comment]
OK, but I need that? I will just use Linux-Containers on Windows.

My example that I posted first, was a Container that uses a Ubuntu Image and it will be a "wrapper" to npm/node.

**Comment by friism** [comment]
@gabrielstein ah, sorry - if you're just wanting to use Linux containers, you should be fine.

Can you check whether this works with a private Docker Hub repo (first one is free). Also, are you using the wincred credential helper with Docker?

**Comment by gabrielstein** [comment]
@friism Thanks for your work!

@friism ok, I created a private repo and it works. 

## Tests with Docker Hub, Private Repo

#### Linux

```

docker-compose up -d                                                                                       {master} 
Pulling npm-test (gabrielstein/npm-boiler:latest)...
latest: Pulling from gabrielstein/npm-boiler
8ad8b3f87b37: Already exists
751fe39c4d34: Already exists
ae3b77eefc06: Already exists
7783aac582ec: Already exists
393ad8a32e58: Already exists
2d923dade19b: Already exists
233f8d07049f: Pull complete
578720e3591b: Pull complete
Digest: sha256:368ce9bbbaff8b825f38c8facd6f8efd36bb879ad587c5b0d196870d10c964a4
Status: Downloaded newer image for gabr
 
```

#### Windows 

- test1

``` 
docker-compose up -d
Pulling npm-test (docker.io/gabrielstein/npm-boiler:latest)...
Pulling repository docker.io/gabrielstein/npm-boiler
ERROR: Error: image gabrielstein/npm-boiler:latest not found

```











-  test2


```

docker-compose up -d
WARNING: Found orphan containers (testnode_wordpress_1, testnode_db_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling npm-test (gabrielstein/npm-boiler:latest)...
Pulling repository docker.io/gabrielstein/npm-boiler
ERROR: Error: image gabrielstein/npm-boiler:latest not found

```


**But why there is a problem only with Windows, Docker-Compose and "Pulling"? Linux and Mac work smoothly**


I use to create Images and push them using Linux only. I test that also with Linux and Mac, no problem at all. But on Windows....

**Comment by friism** [comment]
@gabrielstein are you using the credential helper?

**Comment by gabrielstein** [comment]
Hi @friism , I'm using the standard from docker. 


#### Login

``` 
docker login registry.domain.tld
User... Pass


#### config.json(Windows)

```
	"auths": {
		"registry.domain.tld": {}
	},
	"credsStore": "wincred"
}

```

**Comment by gabrielstein** [comment]
Hi@friism 

I made some tests,  to be sure that is a windows+private+registry+docker-compose bug and isn't a Docker Registry misconfiguration.

I have 3 Servers, 2 runs Registry as Containers, 1 just for tests uses Registry directly on host installed.

#### Below my environment to test it(All running in different servers, DNS-Reverse working and so on)

* Registry1: DEV(just Images for developers)

Uses Registry:2.4
I'm using a docker-registry-web-ui to authenticate against registry, using token. 
I found it here: https://hub.docker.com/r/hyper/docker-registry-web/

##### Error: Authentication Required, ignores docker login(Login Succeeded)

* Registry2: SYSTEM(Just Images for Sysadmins)

Uses Registry:2.4
No Web-UI, using Registry:2.4 too, Apache-Proxy and auths against Windows AD(LDAP)

##### Error: Image doesn't exists, docker login auth works.

* Registry3: TESTS

Uses Registry 2.4
Uses Portus(https://github.com/SUSE/Portus) to Authenticate against Registry, using Token.

##### Error: Authentication Required, ignores docker login(Login Succeeded)

I think that confirms a bug, or? How can I help you further?

**Comment by gabrielstein** [comment]
I can also try to do a tcpdump and post it here. it is helpful for you?

**Comment by friism** [comment]
@gabrielstein can you try to disable the wincred credential helper? https://github.com/docker/docker-credential-helpers#with-the-docker-engine

**Comment by justincormack** [comment]
The credential helper is not currently supported on compose, see https://github.com/docker/compose/issues/3622

**Comment by gabrielstein** [comment]
@justincormack @friism  without wincred docker-compose works, pulls even automatically. Do you have an idea when it will be fixed? 

Thanks a lot for your work!

**Comment by friism** [comment]
@gabrielstein thanks for confirming. A fix is tracked on this issue: https://github.com/docker/docker/pull/23100#issuecomment-244614496

**Comment by sam-thibault** [comment]
This is an old issue, and it appears the relevant fix was merged.  Closing.
