### ISSUE TITLE
Support a method in volume plugin interface to fetch performance counters managed by the plugin for persistent volumes.

### ISSUE THREAD

**Issue by govint** [moby/moby#26246]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 136
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 306
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local vmdk
 Network: overlay bridge null host
Swarm: inactive
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: hte-1s-eng-dhcp98
ID: H3SC:SAIV:HFHW:WYI5:WC4O:GEVQ:S6AJ:VIJ2:4CVT:UXDQ:T4GW:7MCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 26
 System Time: 2016-09-01T05:31:01.183697871-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run a container with persistent volumes via a plugin driver
2. Run docker stats 
3. Docker stats shows block IO stats for disk

**Describe the results you received:**
"docker stats" by design shows only blk IO issued stats irrespective of what volumes are in use by the container-app. There is no way figure performance of the application, especially when its heavily using persistent volumes provided by volume drivers. This issue is to have Docker support getting volume performance stats per volume mounted for a container. Without IO stats from those plugins its very limiting when trying to understand why the app isn't operating as it should. Forces the user to go look at other interfaces to figure whats happening with the storage.

**Describe the results you expected:**
a) Add a new method to the volume driver interface to get block IO stats per volume managed by the plugin.
b) Or extend Get() to return IO stats along with the "Status" returned today by the plugin.
c) Determine if Docker will define what stats must be returned by the plugins or allow the plugins the freedom to provide what stats they can support (as applicable to the volumes they provide).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
