### ISSUE TITLE
How to enable remote API with newest build (1.12.1)

### ISSUE THREAD

**Issue by farahfa** [moby/moby#26253]
I was on 1.10.3 and I had the remote api enabled by changing the $DOCKER_OPS from `/etc/init/docker.conf` to `'-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock'`, but now that doesn't work anymore!

I upgraded to Ubuntu Xenial (from Trusty) and docker engine from 1.10.3 to 1.12.1...

Any help is greatly appreciated!

EDIT: I [reverted back to Upstart](https://wiki.ubuntu.com/SystemdForUpstartUsers#Permanent_switch_back_to_upstart) on this Ubuntu... still same issue.

**Comment by icecrime** [comment]
@farahfa Thanks for the report. Can you please confirm that things work as expected when manually starting `dockerd` (e.g., without going through the init script)?

I don't know of any changes on that in the recent versions, so I have a strong feeling that this might be an issue with your setup.

**Comment by cpuguy83** [comment]
`/etc/init/docker.conf` is specifically for upstart.
It is recommended to make customizations in `/etc/docker.daemon.json` (which by default is empty), which is distro/init-agnostic
Documentation is here: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

That said, if you are using upstart, it should be reading /etc/init/docker.conf.
Unfortunately this file is not portable to systemd.

**Comment by farahfa** [comment]
Yes, I had a mistake with reverting back to Upstart, after fixing that small problem, everything works just great now.. 

However, so @cpuguy83 does it mean that there's no way to configure docker remote api on systemd? Or do you mean that we now have to modify `/etc/docker.daemon.json`? Also, if I want to achieve what I need from OP, what do I need to change in `docker.daemon.json` file?

**Comment by cpuguy83** [comment]
@farahfa There are ways to modify the systemd file as well, but generally `/etc/docker/daemon.json` is the best approach and has the nice side effect that you can hot-reload the daemon to pick up (some/many of) the changes to the file.

You would need to set something like so:
```json
{
    "hosts": ["tcp://1.2.3.4:2375", "unix:///var/run/docker.sock"]
}
```

**Comment by farahfa** [comment]
@cpuguy83 Ah ok that makes sense! Thanks for the help! :)

**Comment by farahfa** [comment]
@icecrime Btw, I do find that the Docker documentations are confusing (like they're all over the place).. Especially when it comes to the Remote API, it would be nice to have straight-forward way to setup Remote API and use it.. (Something [like this](http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-8-docker-remote-api) perhaps?)

**Comment by neersighted** [comment]
Closing this as the feature in question (unencrypted TCP daemon API) is slated for removal in the next major version.
