### ISSUE TITLE
Support custom commands for volume plugins to manage persistent volumes and storage use cases

### ISSUE THREAD

**Issue by govint** [moby/moby#26368]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 136
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 306
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: hte-1s-eng-dhcp98
ID: H3SC:SAIV:HFHW:WYI5:WC4O:GEVQ:S6AJ:VIJ2:4CVT:UXDQ:T4GW:7MCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 24
 System Time: 2016-09-07T01:45:28.255550189-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. NA
2.
3.

**Describe the results you received:**
NA

**Describe the results you expected:**
This issue is to address current issues with persistent volumes for containers,
1. The current set of commands (ls, create, rm, inspect) are fairly limited in allowing exposing storage system (via volume plugin) capabilities to the container user (backup/recovery, stats, attribute-updates).
2. Volume plugins and Docker releases may be async and while plugins may be ready with newer features Docker releases may not always be aligned to support those features.
3. Features of volume plugins may not be uniform across plugins nor may be worth explicitly supporting via docker volume commands.
4. However,  features provided by volume plugins (outside of create/remove, inspect) may be very useful for use cases like monitoring for performance, snapshot'ing, backup/recovery, etc. Currently unsupported as we don't have any plugin interfaces that a container user/manager can leverage. These can only be supported today via legacy interfaces.

To allow a single interface and full use of storage system capabilities can we consider enabling the volume plugin interface to support custom commands (plugin specific). Something like,
1. Support a "query" command to the plugin - a plugin can advertise plugin-specific commands that it supports.
2. Support a "--custom" or "--plugin-specific" option to allow specifying a plugin-specific command on docker volume commands (or as required by the custom command).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
