### ISSUE TITLE
docker run fails on missing aufs layer

### ISSUE THREAD

**Issue by harishkadamudi** [moby/moby#26367]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1. Pull source code from https://github.com/spring-guides/gs-spring-boot-docker.git
2. Run maven goal, package docker:build.
3.

Note: Only change being done is changing <docker.image.prefix>springio</docker.image.prefix> in pom.xml to <docker.image.prefix>harishkadamudi</docker.image.prefix>

**Describe the results you received:**
Exception-
Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project sample-docker: Exception caught: open /var/lib/docker/aufs/layers/fc8d5f1f258fe1b19093667cde51918813aba8fe5dd68631b424dbda1b9eae56: no such file or directory -> [Help 1].

**Describe the results you expected:**
Build Docker image successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using Ubuntu 16.04.1 LTS.

similar issue is being reported but not sure about the resolution #22343

**Comment by RangerRick** [comment]
We're seeing the same thing on ubuntu 16.04 as of a few days ago after an `apt-get dist-upgrade`.  I tried downgrading to docker-engine `1.11.2-0~xenial` and I see the same issue.  Maybe a kernel-upgrade issue from ubuntu?  Currently on `4.4.0-36-generic`.

**Comment by RangerRick** [comment]
I was able to get it working again by switching storage backends:

```
# added to /etc/default/docker
DOCKER_OPTS="--storage-driver=devicemapper"
```

Looks like maybe Ubuntu broke aufs in a recent kernel update?

**Comment by cpuguy83** [comment]
@RangerRick Well, if you switch storage backends, it will require re-pulling/re-building everything.

**Comment by RangerRick** [comment]
That is true; in our case I was fine with blowing everything away and rebuilding because these are test/CI machines.  I was just trying to point out that docker itself still works with another storage driver, and reverting docker versions doesn't fix it, so it points to an issue with aufs on Ubuntu's side.

**Comment by leslau** [comment]
Having same issue on Ubuntu 16.04.1 `4.4.0-34-generic`

switched to devicemappper and everything works like a charm

**Comment by kiview** [comment]
I've updated my Ubuntu to `4.4.0-45-generic` and it works again!

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
