### ISSUE TITLE
[Proposal] Handle deferred deletion on rm errors

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#26372]
Somewhat frequently users see this error when trying to `docker rm foo`: `device or resource busy`.
This error is returned from the kernel when trying to remove container rw layers and/or the container config root... typically due to mounts leaked into other namespaces.
When this happens the container gets flagged as `Dead` and they can re-try later... or if the user specified `-f` it'll just get removed from the container list by force even if the underlying files are still there... this may leak disk space.

I propose instead of erroring out we add these paths to a deferred deletion queue where we can re-try unmounting and removing them every X amount of time.

Paths in this state should be visible to the data management command proposed here: #26108
And a call to `docker prune` would also cause a forced GC run of these deferred removals out-of-band from the normal run.

`Dead` containers should not be seen by end users... except maybe in the aforementioned data management command.

ping @mlaventure

**Comment by mlaventure** [comment]
Maybe we should just mark the container as needing to be garbaged collected so it can correctly happen if the daemon is restarted before the busy mounts get in a state where they can be removed.

**Comment by cpuguy83** [comment]
Device or resource busy is no longer a problem since ~17.12 so closing this.
