### ISSUE TITLE
Define 'docker ps -l' behavior when swarm mode active

### ISSUE THREAD

**Issue by nathanleclaire** [moby/moby#26400]
An old standby in Docker is the trusty `docker ps -l`, which will show last container created.

```
  -l, --latest          Show the latest created container (includes all states)
```

This is extremely useful for things like scripts where you'd like to `docker run` a container and then do something with it later, e.g. `docker cp` some build artifact out of it.  A common pattern became to do things like this:

```
docker run foo
LAST_CONTAINER=$(docker ps -lq)
docker logs ${LAST_CONTAINER}
```

Situations where `docker ps -lq` would give you something other than the container ID from the last invocation of `docker run` were extremely rare and I never heard of any issues with this approach.  Thusly, it [propagated a lot](https://github.com/search?l=bash&q=docker+ps+-l+-q&ref=searchresults&type=Code&utf8=%E2%9C%93) (some of those are false positives, but you get the idea).  You didn't really have to reason about concurrency since multi-user / multi-"thread" Docker systems are not really all that common.

However, with swarm mode, all of this changes completely, and I think it's worth defining what the expected and/or acceptable behavior is before a large swath of folks start switching over their CI etc. to mix these two features and potentially cause inconsistent / extremely difficult to debug behavior.

Imagine that there's a user running some kind of script which uses this pattern.  They also have swarm mode enabled and are running a few services.  If any of those services fails, swarm mode will do its job and create a new task.  Without user doing anything, output of `docker ps -lq` will change over time.

``` console
$ docker service create alpine sh -c 'sleep 1;'
$ docker ps -lq
0344a871a1b9
$ docker ps -lq
d743a337d24d
$ docker ps -lq
2daf1b16c993
```

Though there's a pretty big assumption there of a service task failing in the in-between of a `docker run` and a `docker ps -l` (I've seen Docker CLI hang while making scheduling decisions before, though those seem _mostly_ fixed now), it's not too crazy to imagine it happening eventually when you multiply thousands of users by hundreds/thousands of containers per user.  I think it'd be worth defining that this might be a known issue at least, if not re-defining `docker ps -lq` to mean "show last container created _by this client_" or something.  I dunno, what do you all think?  It's easy to say "Just use container names", but this pattern is already extremely common.

**Comment by cpuguy83** [comment]
I don't think people should be relying on `-l` for anything other than local dev or simple admin functions.
This is a problem with docker-swarm as well... maybe worse since `docker ps` hits every node.

**Comment by thaJeztah** [comment]
I guess https://github.com/docker/docker/pull/24411 would help for this

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
