### ISSUE TITLE
Add LOADCHECK script and --entrypoint-mode=dnsload for load balancing services

### ISSUE THREAD

**Issue by ktwalrus** [moby/moby#26446]
I opened another issue (#26222) to use HEALTHCHECKs for communicating load information back to the DNS load balancer. After thinking about it more, I think that this capability would best be implemented as its own feature, separate from HEALTHCHECK'ing.

So, I propose that Docker add a LOADCHECK feature to the Dockerfile which runs a script within a container and returns a status between 0 and 255. A status of 255 would indicate that the container is fully loaded and cannot handle any further connections. A status of less than 255 would give an indication of how loaded the container thinks it is.

When used with a service that specifies `--entrypoint-mode=dnsload`, the internal DNS load balancer would regularly invoke the LOADCHECK script for each replica/task to determine the overall load of the service. The replica with the lowest load would receive the next connection. If there are more than one replica with the lowest load status, the load balancer would use round-robin to these replicas.

An auto-scale feature could also be implemented to scale a service based on its LOADCHECK statuses. The `docker service create` should allow defining `--minimum-replicas=N` and`--maximum-replicas=N` for the service. The service would be started with `--minimum-replicas` and auto-scale. If the current lowest load status of all healthy replicas is 128 or greater, Docker would add another replica for the services (up to `--maximum-replicas`).  If the load status is 127 or lower for all replicas, one replicas would be stopped/removed from the service (down to `--minimum-replicas`).

If such an auto-scale feature were implemented, maybe use `--entrypoint-mode=auto-scale` to enable this feature in conjunction with LOADCHECK entrypoint being required in the service images.

The important part of this proposal is that the containers themselves should be able to communicate their load (as defined by the container and not the load balancer) back to the load balancer and Docker should manage the service automatically using the load balancer to determine when to scale up/scale down a service.

**Comment by ktwalrus** [comment]
Oh... The auto-scale down feature should cause the load balancer to stop sending requests to the replica with the lowest load status. The load balancer should continue to do LOADCHECKs for this replica and when the status is 0 (indicating "no current load"), the replica may be removed from the service. That is, the auto-scale down feature should allow the replica to "drain" before removing it.

So, replicas that don't want to be removed should make sure they always return a non-zero status. Those that don't mind being removed, should return a status of 0 after they wait a bit to fully "drain" the replica.

Anyway, auto scale is hard to get right, but this feature could make higher server utilization a real possibility by eliminating replicas that are not needed but are reserving CPU, Memory, and Disk on the cluster which inhibits high server utilization (increasing operating costs).

**Comment by mgoelzer** [comment]
@ktwalrus Can you explain more about the use case?

**Comment by thaJeztah** [comment]
We discussed this proposal, and having more details about your use case would help us see what improvements could possibly be made to scheduling. We're not sure about the design you're proposing, so having a use case description helps with that :smile:

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
