### ISSUE TITLE
Swarm: Manager is unable to remove nodes and even leave swarm itself.

### ISSUE THREAD

**Issue by michaelkrog** [moby/moby#26477]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 964
 Running: 0
 Paused: 0
 Stopped: 964
Images: 7
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1938
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: pending
 NodeID: 5p1vjiuqbgteubr7zpuuvtl95
 Is Manager: true
 ClusterID: dr5jaeyxs39jvp5pko9mnm497
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.129.23.9
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: engine1
ID: K6VW:TLMS:3G4J:2GJR:VUJQ:ZOJD:7BJD:QGFW:N7C4:2BGT:MXZO:PXXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**_UFW Status**_

```
To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
2377/tcp on eth1           ALLOW       Anywhere                  
7946 on eth1               ALLOW       Anywhere                  
4789 on eth1               ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
2377/tcp (v6) on eth1      ALLOW       Anywhere (v6)             
7946 (v6) on eth1          ALLOW       Anywhere (v6)             
4789 (v6) on eth1          ALLOW       Anywhere (v6)   
```

**Steps to reproduce the issue:**
1. Install Ubuntu 16.04 on 3 servers on digital ocean
2. Configure UFW to allow only port 80, 443 and 2377 (not 7946 and 4789).
3. Create swarm via digital oceans private networking
4. Create encrypted overlay network
5. Create a service based on nginx serving a plan html page
6. Create a service based on nginx,  functioning as a proxy for the other server.
7. Expose the proxy on port 80.
9. Connect to master on port 80.
10. Find that the Swarm is not working correctly.
11. Open up port 7946 and 4789 in UFW.
11. Play with it for a whole workday. The swarm will be very unstable even after recreating the swarm. Continue until services are no longer able to start new containers and begins to report "network not found" even though the network is still there.
12. Let it be for a few days.
13. Find that CPU of the manager has gone through the roof for a long period of time and you are unable to access the machine again.
14. Shut down the workers.
15. Hard reset the manager.
16. Remove nodes via CLI from the manager and leave the swarm. 

**Describe the results you received:**
When trying to remove a worker from the swarm.

```
$ docker node ls
ID                           HOSTNAME  STATUS   AVAILABILITY  MANAGER STATUS
4ou2nellu0jatzu5kdrst6kvs    engine3   Unknown  Active        
5p1vjiuqbgteubr7zpuuvtl95 *  engine1   Unknown  Active        Leader
7jtwok0dinwkfsmtctrtfq0wb    engine2   Unknown  Active        
```

```
$ docker node rm engine3 --force
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

The worker node is not removed afterwards.

When trying to make the manager leave the swarm.

```
$ docker swarm leave
Error response from daemon: You are attempting to leave the swarm on a node that is participating as a manager. Removing the last manager erases all current state of the swarm. Use `--force` to ignore this message.
```

```
$ docker swarm leave --force
Error response from daemon: context deadline exceeded
```

**Describe the results you expected:**
First of all I would expect that swarm mode just worked. It did not, and it just seems to break the more I use it. So I would expect that I at least could remove the swarm in order to create a new. Initially I could, but now it has come to a state where it is not possible anymore.

I had to dd this to get it working again:

```
$ sudo apt-get remove docker-engine
$ sudo rm -rf /var/lib/docker
$ sudo apt-get install docker-engine
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by michaelkrog** [comment]
REMARK:
The issue I am seeing with nginx acting as a proxy for another service is possibly because nginx actually caches the ip's of the hostnames it resolve.

See http://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytime-when-doing-p

But the main issue is that I ended up being unable to delete the swarm.

**Comment by thaJeztah** [comment]
Looks like this may be a duplicate of https://github.com/docker/docker/issues/25432

**Comment by michaelkrog** [comment]
This is no longer an issue.
