### ISSUE TITLE
Add "EBUSY errors on container remove" to known issues and document workaround.

### ISSUE THREAD

**Issue by anusha-ragunathan** [moby/moby#26510]
**Description**
Linux kernel version 3.19 introduced lazy removal of mounts on unlinked files and directories.
This greatly reduces EBUSY errors when removing bind mounted directories used in containers. For more information, refer to 
1. http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?h=linux-3.19.y&id=8ed936b5671bfb33d89bc60bdcc7cf0470ba52fe
2. https://github.com/docker/docker/issues/21704

Update necessary documentation and pre-req check code.

**Comment by anusha-ragunathan** [comment]
@icecrime : This needs update to prerequisite check code @ https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L207 in addition to the docs.

**Comment by icecrime** [comment]
Oops! :speak_no_evil: Thanks :-)

**Comment by anusha-ragunathan** [comment]
I thought about it a bit more and concluded that it is intrusive to require *all* users to upgrade to 3.19, while the issue might not be applicable to them. Instead, we can doc it in a known issues section and suggest the kernel upgrade as a workaround.

Adding a "Known issues" section in the release (https://github.com/docker/docker/releases).

cc @thaJeztah

**Comment by anusha-ragunathan** [comment]
We are not going to make kernel 3.19 as a hard requirement. So no code changes necessary.

**Comment by anusha-ragunathan** [comment]
@thaJeztah : Would you be able to take care of this? Feel free to ping me if you need more details. Thanks.

**Comment by thaJeztah** [comment]
@anusha-ragunathan yes, I already put some issues on my list. I'll have to search if the actual "known issues" list is still somewhere in the docs, otherwise create a new one 👍

**Comment by anusha-ragunathan** [comment]
Great!

**Comment by hdimitriou** [comment]
Is there a 'known issues' section ?

**Comment by anusha-ragunathan** [comment]
@thaJeztah : Looks like https://docs.docker.com/engine/admin/troubleshooting_volume_errors is a good doc on the symptom described here. I'm happy to close this issue in lieu of that. WDYT?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale; I also think most of these were fixed since
