### ISSUE TITLE
Docker container cannot access internet

### ISSUE THREAD

**Issue by hansij66** [moby/moby#26567]
From a docker container, I cannot ping gateway on my LAN (192.168.1.254) or 8.8.8.8 on the internet. 
I can ping docker host (192.168.1.1). 
I can ping other containers
I cannot build new docker images, as apt-get fails...
(from a KVM instance on same host, I can ping the world...(with or w/o iptables up) - hence basic network configuration seems ok (?)
Running a container with -net=host, all is fine. But that is not what I want and it does not allow me to build new images.
As I am pinging ip-addresses, the resolv.conf shouldn't matter - but it is pointing to my LAN gateway.

I cannot get my head around this; I had this working...two weeks ago on this system. AFAIK, I just added 3 new containers...

Configuration:
docker with option --iptables=false
Docker version 1.12.1, build 23cf638
sudo sysctl net.ipv4.ip_forward --> net.ipv4.ip_forward = 1
Host = debian jessie

Whether I have iptables up (with the iptables configuration which worked last week) or iptables flushed (-X, -F), I cannot ping outside world or LAN

I have reloaded docker daemon; I have deleted docker0 interface and started docker daemon.

I am clueless where to look. Any suggestion are greatly appreciated!

Hi Justin, my apologies - I mis read the template slightly; attached (I hope) the requested info:

docker info
Containers: 35
Running: 5
Paused: 0
Stopped: 30
Images: 10
Server Version: 1.12.1
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 175
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.732 GiB
Name: ijntema-svr
ID: 4R6H:4F4B:2JIZ:I5OI:4LWL:WPY3:M2BB:GCWC:733P:TTWW:4BNP:NKCZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
127.0.0.0/8

docker version
Client:
Version: 1.12.1
API version: 1.24
Go version: go1.6.3
Git commit: 23cf638
Built: Thu Aug 18 05:02:53 2016
OS/Arch: linux/amd64

Server:
Version: 1.12.1
API version: 1.24
Go version: go1.6.3
Git commit: 23cf638
Built: Thu Aug 18 05:02:53 2016
OS/Arch: linux/amd64

docker0 Link encap:Ethernet HWaddr 02:42:0c:68:06:64
inet addr:172.17.42.1 Bcast:0.0.0.0 Mask:255.255.0.0
inet6 addr: fe80::42:cff:fe68:664/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:98689 errors:0 dropped:0 overruns:0 frame:0
TX packets:131638 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:20952707 (19.9 MiB) TX bytes:47646030 (45.4 MiB)

eth0 Link encap:Ethernet HWaddr 00:22:4d:aa:fc:0e
inet addr:192.168.1.1 Bcast:192.168.1.255 Mask:255.255.255.0
inet6 addr: 2001:981xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/64 Scope:Global
inet6 addr: fe80::222:4dff:feaa:fc0e/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:13577484 errors:0 dropped:100 overruns:0 frame:0
TX packets:11625067 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:14942275940 (13.9 GiB) TX bytes:2373320371 (2.2 GiB)
Interrupt:20 Memory:f7f00000-f7f20000

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:1312336 errors:0 dropped:0 overruns:0 frame:0
TX packets:1312336 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:3307576126 (3.0 GiB) TX bytes:3307576126 (3.0 GiB)

tun0 Link encap:UNSPEC HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
inet addr:10.65.0.1 P-t-P:10.65.0.2 Mask:255.255.255.255
UP POINTOPOINT RUNNING NOARP MULTICAST MTU:1500 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:33927 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:100
RX bytes:0 (0.0 B) TX bytes:12516563 (11.9 MiB)

veth5968406 Link encap:Ethernet HWaddr 0a:a9:13:de:bd:05
inet6 addr: fe80::8a9:13ff:fede:bd05/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:8 errors:0 dropped:0 overruns:0 frame:0
TX packets:30858 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:648 (648.0 B) TX bytes:6912331 (6.5 MiB)

veth8c679e4 Link encap:Ethernet HWaddr 6a:4f:5a:0f:55:87
inet6 addr: fe80::684f:5aff:fe0f:5587/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:98265 errors:0 dropped:0 overruns:0 frame:0
TX packets:132752 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:22295548 (21.2 MiB) TX bytes:47825246 (45.6 MiB)

vetha9e37b2 Link encap:Ethernet HWaddr 02:60:f6:be:2b:0c
inet6 addr: fe80::60:f6ff:febe:2b0c/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:8 errors:0 dropped:0 overruns:0 frame:0
TX packets:30861 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:648 (648.0 B) TX bytes:6912525 (6.5 MiB)

vethad16b16 Link encap:Ethernet HWaddr 1e:02:26:81:b9:73
inet6 addr: fe80::1c02:26ff:fe81:b973/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:8 errors:0 dropped:0 overruns:0 frame:0
TX packets:30873 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:648 (648.0 B) TX bytes:6916872 (6.5 MiB)

virbr0 Link encap:Ethernet HWaddr fe:54:00:8c:22:a4
inet addr:192.168.122.1 Bcast:192.168.122.255 Mask:255.255.255.0
inet6 addr: fe80::fc54:ff:fe8c:22a4/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:39752 errors:0 dropped:0 overruns:0 frame:0
TX packets:58566 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:39847592 (38.0 MiB) TX bytes:18915147 (18.0 MiB)

vnet0 Link encap:Ethernet HWaddr fe:54:00:8c:22:a4
inet6 addr: fe80::fc54:ff:fe8c:22a4/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:39752 errors:0 dropped:0 overruns:0 frame:0
TX packets:95333 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:500
RX bytes:40404120 (38.5 MiB) TX bytes:21080091 (20.1 MiB)
# 

sudo route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.254   0.0.0.0         UG    0      0        0 eth0
10.65.0.0       10.65.0.2       255.255.255.0   UG    0      0        0 tun0
10.65.0.2       0.0.0.0         255.255.255.255 UH    0      0        0 tun0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0

sudo ip route show
default via 192.168.1.254 dev eth0
10.65.0.0/24 via 10.65.0.2 dev tun0
10.65.0.2 dev tun0  proto kernel  scope link  src 10.65.0.1
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.1
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1

**Comment by justincormack** [comment]
You need to give us the information requested in the form, and some more information about the networking setup, as it is not possible to debug with the information you have provided.

**Comment by hansij66** [comment]
Hi Justin, my apologies - I mis read the template slightly; attached (I hope) the requested info:

docker info
Containers: 35
 Running: 5
 Paused: 0
 Stopped: 30
Images: 10
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 175
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.732 GiB
Name: ijntema-svr
ID: 4R6H:4F4B:2JIZ:I5OI:4LWL:WPY3:M2BB:GCWC:733P:TTWW:4BNP:NKCZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

==============================================================
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

============================================================
docker0   Link encap:Ethernet  HWaddr 02:42:0c:68:06:64
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:cff:fe68:664/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:98689 errors:0 dropped:0 overruns:0 frame:0
          TX packets:131638 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:20952707 (19.9 MiB)  TX bytes:47646030 (45.4 MiB)

eth0      Link encap:Ethernet  HWaddr 00:22:4d:aa:fc:0e
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: 2001:981:9065:1:222:4dff:feaa:fc0e/64 Scope:Global
          inet6 addr: fe80::222:4dff:feaa:fc0e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13577484 errors:0 dropped:100 overruns:0 frame:0
          TX packets:11625067 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14942275940 (13.9 GiB)  TX bytes:2373320371 (2.2 GiB)
          Interrupt:20 Memory:f7f00000-f7f20000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1312336 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1312336 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:3307576126 (3.0 GiB)  TX bytes:3307576126 (3.0 GiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.65.0.1  P-t-P:10.65.0.2  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33927 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:12516563 (11.9 MiB)

veth5968406 Link encap:Ethernet  HWaddr 0a:a9:13:de:bd:05
          inet6 addr: fe80::8a9:13ff:fede:bd05/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30858 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:6912331 (6.5 MiB)

veth8c679e4 Link encap:Ethernet  HWaddr 6a:4f:5a:0f:55:87
          inet6 addr: fe80::684f:5aff:fe0f:5587/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:98265 errors:0 dropped:0 overruns:0 frame:0
          TX packets:132752 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:22295548 (21.2 MiB)  TX bytes:47825246 (45.6 MiB)

vetha9e37b2 Link encap:Ethernet  HWaddr 02:60:f6:be:2b:0c
          inet6 addr: fe80::60:f6ff:febe:2b0c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30861 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:6912525 (6.5 MiB)

vethad16b16 Link encap:Ethernet  HWaddr 1e:02:26:81:b9:73
          inet6 addr: fe80::1c02:26ff:fe81:b973/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30873 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:6916872 (6.5 MiB)

virbr0    Link encap:Ethernet  HWaddr fe:54:00:8c:22:a4
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          inet6 addr: fe80::fc54:ff:fe8c:22a4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:39752 errors:0 dropped:0 overruns:0 frame:0
          TX packets:58566 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:39847592 (38.0 MiB)  TX bytes:18915147 (18.0 MiB)

vnet0     Link encap:Ethernet  HWaddr fe:54:00:8c:22:a4
          inet6 addr: fe80::fc54:ff:fe8c:22a4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:39752 errors:0 dropped:0 overruns:0 frame:0
          TX packets:95333 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:40404120 (38.5 MiB)  TX bytes:21080091 (20.1 MiB)

**Comment by hansij66** [comment]
I got it fixed; but I don't understand why/how.

What I have done to get it to work again:
I have been running docker with OPTIONS="--iptables=false"
This worked fine till a few days ago (symptoms in original ticket)

I changed OPTIONS (in a few steps and different values) to:
OPTIONS="--iptables=false --ip-forward=true --ip-masq=true --icc=true"
From that moment onward all pings to the outside world work again.

I moved back to OPTIONS="--iptables=false";
Everything is still working.
In between any change, I stopped docker and removed docker0 with sudo ip link del docker0;

Initially, I though it is a stupid configuration error on my host side which I somehow introduced after docker was working;

Now I think it is an defect, as I can get it to work again by changing a few config options and subsequently I can go back to the original configuration.

**Comment by hansij66** [comment]
Everything worked fine for a few days; building/deploying a few new docker containers; once in a while a reboot to verify if all is fine after a reboot.
This morning (not sure if related - after updating Debian & reboot), suddenly all communication from containers to outside world stopped; specifically ping 8.8.8.8 did not work anymore; I could not build any containers anymore (when apt-get is required).
I started to apply the "fix" from previous post. It seems (but not 100% sure yet) that changing  --iptables=false to true to false (and restarting dockerd & removing docker0 in between) fixing the network connectivity....

Any clue?

**Comment by bnordbo** [comment]
I am seeing this issue too, or a similar one, after upgrading to Docker 1.12.1. The container networking is down, i.e. the ARP requests from the host never reaches the broken container. Other containers on the same host are fine. In my case, at least, it seems to be due to the VIF not being added to the `docker0` bridge:

```
58: veth47fc599@if57: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 4a:03:5e:8c:c5:c0 brd ff:ff:ff:ff:ff:ff
```

Adding it via `sudo brctl addif docker0 veth47fc599` fixes the issue.

## Steps to reproduce the issue

The issue occurs somewhat randomly, even with basic examples such as `/usr/bin/docker run --rm   anigeo/awscli`. This container worked, and then a few minutes later did not. Once it has stopped working, it seems somewhat stable, i.e. I can repeadedly run this container and it will consistently fail (in this case with "Unable to locate credentials").

## Describe the results you received

The container is started and assigned an IP address on the `172.17/16` network. It's routing table looks fine, but it cannot ping `172.17.0.1`, nor does it see the ARP requests from the host, nor any other traffic.

## Describe the results you expected

I would expect the container to start with working networking, as this was the case before we upgraded from 1.10.3, and the container is pretty bare bones.

## Additional information you deem important

As mentioned in the preamble, the issue is likely caused by the container VIF not being added to the `docker0` bridge.

## Output of `docker version`

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   f1e1b83
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   f1e1b83
 Built:
 OS/Arch:      linux/amd64
```

## Output of `docker info`

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.7.3-coreos
Operating System: CoreOS 1164.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.3 MiB
Name: public-worker
ID: ON76:XQK6:U5YA:4UNO:6YEY:VFQL:NELR:727N:C6D2:TL5D:RUHJ:H6YQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

## Additional environment details

The host is running CoreOS alpha on an AWS EC2 VPC instance.

Hope this helps,
  Bjørn

**Comment by hansij66** [comment]
It happened again; I got connectivity back by:
set iptables=false to true to false (and restarting dockerd & removing docker0 in between)

**Comment by hansij66** [comment]
Hi All, I am still running into this issue, that at some point, I cannot access the www from a container (ping 8.8.8.8); verified with iptables disabled.

The only way to fix:
1. Toggle iptables=false to true; restarting dockerd
2. Toggle iptables=true to false; restarting dockerd

(just restarting dockerd does not fix my issue)

Ticket is still flagged as "more-info-needed"; afaik, I have added all requested info @ top;
Since original submission, dockerd got updated to Docker version 1.12.2, build bb80604, still facing this issue.

**Comment by bnordbo** [comment]
@hansij66, as mentioned above, we were able to fix this simply by adding the VIF to `docker0`, i.e. `sudo brctl addif docker0 <vif>`. Does this not work for you?

Anyway, we downgraded to `1.11` and have not had this problem since.

**Comment by hansij66** [comment]
I missed this as a real solution; I will give i a try! Thanks

**Comment by bnordbo** [comment]
@hansij66 It's more of a simpler workaround than a solution I'm afraid. But at least it's not intrusive.

**Comment by hansij66** [comment]
Hi, I tried:
sudo brctl addif docker0 veth44dac6e

but get response:
device veth44dac6e is already a member of a bridge; can't enslave it to bridge docker0

Issue is still randomly happening; today again.

**Comment by Nepoxx** [comment]
I've created an issue similar to this one: https://github.com/moby/moby/issues/36151

(this issue hasn't seen activity in over a year)

**Comment by kevinhooke** [comment]
Steps in this comment worked for me too https://github.com/moby/moby/issues/26567#issuecomment-255517029

**Comment by boolooper** [comment]
> The only way to fix:

> Toggle iptables=false to true; restarting dockerd
> Toggle iptables=true to false; restarting dockerd
> (just restarting dockerd does not fix my issue)

Can someone explain how this tick on https://github.com/moby/moby/issues/26567#issuecomment-255517029 works?

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
