### ISSUE TITLE
Request: new experimental plugins should be able to publish / expose ports

### ISSUE THREAD

**Issue by chungers** [moby/moby#26726]
Feature request

Currently the experimental plugins can only expose endpoints via unix sockets and access (as a client) to other network services via the host's networking stack (via `host` mode in the networking section of the manifest).   There is no way for plugins to bind to a host port and listen, even though Docker containers all have the ability to expose / publish their services via the `--publish` option in `docker run` and `EXPOSE` in Dockerfile. 

The ability to expose/publish will allow plugins to listen on host ports and be comparable to Docker containers and will enable many use cases.  Please consider implementing this in 1.13.

cc @anusha-ragunathan

**Comment by cpuguy83** [comment]
Can you explain the use-case? As a plugin I would expect that only docker would be communicating with it.

**Comment by anusha-ragunathan** [comment]
Their use case is that the plugin exposes a service via port publish. Containers access that service via the port.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
