### ISSUE TITLE
Error when executing a docker client function twice

### ISSUE THREAD

**Issue by aacebedo** [moby/moby#26793]
---
## BUG REPORT INFORMATION

**Description**
Using client interface to connect to a docker unix socker, the second call to a client function display an error saying the server returned an HTTP response to an HTTPS client.

Go seems to change the value of the TLSClientConfig pointer within a transport object when a request is performed thus the function resolveTLSConfig from file docker/client/transport.go is returning a TLSClientConfig not nil and the client thinks it has a https access now. 

**Steps to reproduce the issue:**
1. Compile the example located in docker/client
2. Add the line containers, err := cli.ContainerList(context.Background(), options) after the first call
3. See the result

**Describe the results you received:**
panic: error during connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json?all=1&limit=0: http: server gave HTTP response to HTTPS client

**Describe the results you expected:**
Displaying containers

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 27
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.48 GiB
Name: corei7
ID: DJY2:C6W2:V4PZ:34VD:YE72:IQAN:36G3:23WJ:C2RS:EY4E:FS26:DJGP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 30
 System Time: 2016-09-21T21:10:50.862297222+02:00
 EventsListeners: 0
Username: aacebedo
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by vdemeester** [comment]
This could be related to https://github.com/docker/docker/issues/26781

**Comment by runcom** [comment]
I believe it's the same

**Comment by runcom** [comment]
@vdemeester can you add close #26781 to his PR?

**Comment by thaJeztah** [comment]
@runcom is it the same issue? Looks like this issue is on 1.12.1, not on master?

**Comment by justincormack** [comment]
@thaJeztah its not exactly clear when this issue started.

**Comment by thaJeztah** [comment]
@justincormack I thought it was because @runcom lead it to https://github.com/docker/docker/pull/26436, but possibly that was unrelated then.

If this is an issue introduced in 1.12, should we add it to the 1.12.2 milestone?

**Comment by justincormack** [comment]
@thaJeztah yes it still seems unclear, but potentially if it was, yes.

**Comment by stevvooe** [comment]
I don't this is related to #26781. This is 1.12.1. #26436 may have exposed an already existing issue.

I can't reproduce either at this point.

**Comment by vdemeester** [comment]
I'm gonna close this issue as it is stale and is probably already fixed.
If you encounter the same problem, please open a new issue :angel: :pray:
