### ISSUE TITLE
Constraints in Docker Engine Swarm mode

### ISSUE THREAD

**Issue by saithala** [moby/moby#26806]
**Description**

I'm using Docker Engine is swarm mode (v1.12) and I have 4 nodes in the cluster. I have two services S1 and S2 where S2 needs S1 to function.  Following are my questions

**Steps to reproduce the issue:**
1. Although S1 and S2 are assigned to the same overlay network, it does not work unless S1 and S2 are scheduled in the same node. I dont understand why. Can someone explain?
2. Assuming that the problem described in Point 1 is a limitation in the swarm mode, how do I use constraints in such a way to ensure that S1 and S2 end up getting scheduled in the same node irrespective of how I scale S1 and S2?  The documentation in https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint provides some insight but I'm not sure how I can come up with an intelligent constraint criteria without having to sacrifice the flexibility of scaling a service in any node inthe cluster.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 75
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-201541897-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.807 GB
 Data Space Total: 107.4 GB
 Data Space Available: 35.11 GB
 Metadata Space Used: 2.683 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: active
 NodeID: 7202wve4874tcwecl7tiswea6
 Is Manager: true
 ClusterID: 5ul6qb71qfpqjtmxc6wt1r7uq
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.1.2.58
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 47.01 GiB
Name: cmcmdmz103
ID: EEXU:DFS7:DAED:TCKX:SLAT:ZJKR:VXQT:XBPI:N23Y:R7RU:GZ3H:LU6H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by michelvocks** [comment]
> 1. Although S1 and S2 are assigned to the same overlay network, it does not work unless S1 and S2 are scheduled in the same node. I dont understand why. Can someone explain?

Can you please provide us more information that we can help you? What is the error output? Can you ping S2 from S1 (inside the container)?

**Comment by thaJeztah** [comment]
> it does not work unless S1 and S2 are scheduled in the same node

This should work, but if not, possibly there's an issue with overlay networking. At least make sure that the required ports are opened between the nodes;
https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts

Also, I see you're running docker 1.12.0. A patch update (1.12.1) was released, which fixes various issues. We're also working on a 1.12.2 release for additional fixes.

> Can you ping S2 from S1 (inside the container)?

"pinging" the Virtual IP of another service may not work between hosts, but you should be able to ping individual tasks / containers, or connect to the service through other means.

**Comment by saithala** [comment]
@thaJeztah Thanks for your response. In our environemnt, all the hosts are in the same subnet so there should be no restrictions on ports. Any other reason you can think of

**Comment by thaJeztah** [comment]
@saithala not directly, but it looks similar to https://github.com/docker/docker/issues/26747 (and some other issues), although some issues can have the same effect, but a different cause

/cc @mrjana

**Comment by mrjana** [comment]
@saithala If you are trying to ping service names (which resolves to VIP) it is not supposed to work. Can you confirm if you are trying to ping the VIP or directly the task container?

**Comment by saithala** [comment]
@mrjana  So in the example I gave, S1 and S2, one of them is a config service whose job is to just load configurations and the other service is supposed to consume the configurations provided by the config service. So this is just a service to service communication where one service is trying to access the other service by its name. Does that answer your question?

**Comment by mrjana** [comment]
@saithala The question was more specific than that? How are they trying to communicate? Are they using a TCP connection and if so are they using the ports that the apps are actually listening on?

If the communication is not just ping and you are saying they work in the same host, did you make sure these set ports are open in your host: 7946/tcp, 7946/udp and 4789/udp?

**Comment by saithala** [comment]
@mrjana  I think the issue that i have is similar to the another issue Im having now. I have a discovery service and I have published that port to the swarm while creating the service --publish 8761:8761. The service which is trying to register with the discovery is doing so using the http protocol. http://discovery:8761. The error in this case is hostnotreachable. if I attach to the container and do a curl on  http://discovery:8761 i get the same hostnotreachable.. I made sure that when i start the services I attach it to the default ingress network using --network ingress option.  Like I mentioned since all the nodes are in the same subnet in our env, there should not be any restrictions on the ports. Also as suggested, I upgraded to 1.12.1 now.

**Comment by mrjana** [comment]
@saithala Trying to attach to `ingress` network is your problem. You should not use `ingress` for your intra-cluster connectivity purposes. It should always be done using a network that you define. If you do so it will work. In fact we should forbid attaching to ingress network in code.

**Comment by thaJeztah** [comment]
@mrjana see https://github.com/docker/docker/issues/25396, but there's some discussion, perhaps you could have a look

**Comment by saithala** [comment]
@mrjana @thaJeztah  Creating a custom overlay network appears to have solved the issue. Since creating a swarm cluster provides a default ingress network, i was under the impression that I dont need to create a custom network but just use the default one that is already provided. Just for my knowledge I'm curious to understand the purpose of the ingress network. https://docs.docker.com/engine/swarm/ingress/#use-swarm-mode-routing-mesh. Please add a note to the docs explaining the motive of the default network. Thanks all for your support

**Comment by thaJeztah** [comment]
@saithala agreed; can you open an issue for that (docs improvement)?

**Comment by saithala** [comment]
@mrjana @thaJeztah.. So now I have a strange problem. After creating a custom overlay network, some services still have the same issue. In the example I mentioned above of services not able to register to  the discovery service, it now seems that some of the services can connect to the discovery and some of them cannot. The exception in the logs is 
I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://discovery:8761: Host is unreachable

Any thing else I need to do apart from attaching the service to the custom overlay network?

**Comment by mrjana** [comment]
@saithala Can you please attach daemon logs from the node where you are having this problem?

**Comment by saithala** [comment]
[Logs.txt](https://github.com/docker/docker/files/496277/Logs.txt)

@mrjana  here it is. Please let me know if you have any questions

**Comment by mrjana** [comment]
@saithala From your logs it seems like the service did not start properly. Can you see what `docker service ps <service_name>` shows?

**Comment by saithala** [comment]
@mrjana I restarted the services multiple times and it seems to me that the services start properly

**Comment by mrjana** [comment]
@saithala Can you point me to `docker service ps <service_name>` when you have this problem? Also if it is a test setup  is it possible to try https://github.com/docker/docker/releases/tag/v1.12.2-rc3 to see if your problem is gone?

**Comment by saithala** [comment]
@mrjana Here it is..
`sudo docker service ps webhook
ID                         NAME           IMAGE                                            NODE        DESIRED STATE  CURRENT STATE                ERROR
83vw5seodk0e8tlqa51ynqk60  webhook.1      docker/api-payment-webhook:0.0.1-SNAPSHOT.49  dmz104  Ready          Ready 2 seconds ago
as49ddricfipz4k4hi9c67mag   \_ webhook.1  docker/api-payment-webhook:0.0.1-SNAPSHOT.49  dmz104  Shutdown       Complete 3 seconds ago
96jef4ztprwla061epr2cjc2x   \_ webhook.1  docker/api-payment-webhook:0.0.1-SNAPSHOT.49  dmz104  Shutdown       Complete 27 seconds ago
3ijv2hx7ko4t0o3u451qx8dud   \_ webhook.1  docker/api-payment-webhook:0.0.1-SNAPSHOT.49  dmz104  Shutdown       Complete 51 seconds ago
2ht9tfmhc41pyt28ywmodgivt   \_ webhook.1  docker/api-payment-webhook:0.0.1-SNAPSHOT.49  dmz104  Shutdown       Complete about a minute ago`

**Comment by thaJeztah** [comment]
@saithala is the process in your containers something that keeps running, or does it exit after it's run?  Looking at the history in your `docker service ps` it could be that it's a process that does not keep running (in which case docker starts a new container to replace it)

**Comment by saithala** [comment]
@thaJeztah 
It does not startup at all. Like you mentioned, the swarm keeps restarting it until someone tries to manually remove the service.

**Comment by saithala** [comment]
@thaJeztah  Any idea when 1.12.2 will be officially released? Our sysAdmins do not want to pull the docker version (rc-3) from the test repo

**Comment by thaJeztah** [comment]
@saithala should be any day now (1.12.2)

However, I'd still be interested to find why those containers don't start; is there anything in their logs? What's the exit code of those containers?

**Comment by mrjana** [comment]
@saithala The image you are using does not seem to be a daemon. It runs on an average for about 24 seconds and exits and that is why you see all those tasks in `COMPLETE` state. And this is the likeliest reason for you other container to not be able to discover this. You need to check your image and may be run it as a normal container and observe it's behavior. I don't see any bug here other than an unintended usage of an image.

**Comment by saithala** [comment]
@thaJeztah  @mrjana  In my case it just throws a null pointer exception and exits out since the service thats supposed to provide some configs are is not available. This issue is sporadic and inconsistent. We have a bunch of micros-services that make up our application. The issue i'm facing today is with a different microservice than it was a few days ago. Restarting the docker daemons and the hosts magically seems to solve the issue. Im thinking there must be some random issue with service to service communication

**Comment by mrjana** [comment]
@saithala A null pointer exception on the image should show up in a failed exit code on the task status but seems all of the tasks exited normally. In any case if what you posted here https://github.com/docker/docker/issues/26806#issuecomment-252981759 is not the correct image where you are facing a problem today can you provide `docker service ps <service_name>` output for the image where you are facing an issue which you think is still running but there is still a problem with communication?

**Comment by saithala** [comment]
@mrjana .  The output I placed earlier was from the command docker service ps webhook 
Following is the logs from docker logs -f containerName of that container which failed. To clarify these are the last lines from the command docker logs -f containerName

```````````````````````````

"Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.config.internalTransactionAdvisor' defined in class path resource [org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.transaction.interceptor.BeanFactoryTransactionAttributeSourceAdvisor]: Factory method 'transactionAdvisor' threw exception; nested exception is java.lang.NullPointerException)"}
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 1 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/cmc/api/repo/jpa/JPAConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at com.cmc.api.webhook.WebhookServiceApplication.main(WebhookServiceApplication.java:30)
        ... 6 more
Caused by: org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.
        at org.hibernate.cache.internal.NoCachingRegionFactory.buildEntityRegion(NoCachingRegionFactory.java:83)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:364)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 22 more


`````````````````````````````````

**Comment by mrjana** [comment]
@saithala I don't know much about this app to tell why they are failing. Do you have an idea of why they are failing? Also I am assuming all of the containers started with this image fail like this during startup. So does that explain why they are able to communicate. I am sorry this issue now holds a lot of different issues. Can you tell me in a few brief steps what you did and what you expected to work and what worked and what did not work? Also please provide `docker service ps` output for all the services that form your microservice and you are having trouble with.

**Comment by saithala** [comment]
@mrjana Like I mentioned earlier. I know why they are failing.  Just to give you a brief background, our micro services run on SpringCloud platform. So we have a service discovery micro service, a config micro service and a few other micro services  that expose REST API endpoints. The API microservices need configs like DB connection details etc that are provided by the config microservice. Also after each API micro service boots up, they register with Service Discovery (Eureka). In this case communication from API service to config and SD is failing. Somewhere hiding and nested inside the same logs I also see Connection refused; nested exception is java.net.ConnectException: Connection refused.This is the root cause of my problem.

 All services are attached to the same "custom" overlay network and restart of docker engines and nodes magically solves the problem which is sporadic and inconsistent. 

We initially had this set up running in docker-compose and it was OK although it was not production tested. After the Swarm mode was released, we thought of using that and our problems began.

**Comment by mrjana** [comment]
Ok, if you are sure there are sporadic failures because of `Connection refused` errors please try out 1.12.2 when it is going to be out today. It is packed with many important networking fixes.

**Comment by saithala** [comment]
Well, Im not sure these are sporadic failures because Ive been experimenting with Swarm mode over the past few weeks. It took me a while to figure out and  convert/migrate docker run provided by compose to docker service create. The reason I say sporadic is when i reboot the hosts and rebuild the swarm cluster, everything is fine. I stop and recreate all services then some of come up fine and some of them fail with this exception. Rebooting again solves all the problems. Keeping my fingers crossed for 1.12.2

**Comment by thaJeztah** [comment]
@saithala one thing to keep in mind when designing / developing your micro services is that they should be resilient against (networking) failures. In your local setup (docker compose on a single machine), generally services will be available directly, whereas on a cloud deployment, it may take time to have the services deployed, and networking established.

Your services should take this into account, and (for example) not fail directly if networking cannot be established. If the connection cannot be established, they should retry instead of fail. A very simple example of this can be found in the official WordPress image; https://github.com/docker-library/wordpress/blob/7d40c4237f01892bb6dbc67d1a82f5b15f807ca1/php7.0/apache/docker-entrypoint.sh#L145-L156 there you can see the image (re)tries to connect to the database until it's up. That's during initial startup, but should also be taken into account after the service is running (networking interruptions  _will_ fail at some point, and should not result in all services to fail)

**Comment by mrjana** [comment]
@saithala 1.12.2 is out. Have you had a chance to upgrade and report back?

**Comment by saithala** [comment]
@mrjana  yes I did. Unfortunately it did not solve the problem : (
We still have problems with service to service communications. Any idea how we can resolve this? Are there more fixes coming? One thing I noticed was the service that was failing to communicate with other service worked fine when the service was started again with a constraint. (--constraint 'node.hostname==hostname). I dont know if this will help in your investigation but so far there is no definite pattern that can pin point what/where the problem is.. Pretty frustrating. 

One other question I had was, we tried to set up a global service (fluentd) which functions as a log collector for that node. Each service hosted in that node is supposed to route logs to this global fluentd service for that node. So when we start other services (docker service create --log-driver fluentd --log-opt fluentd-async-connect=true --log-opt fluentd-address=fluentd:24224 ) where fluentd is the global service, it immediately fails saying that the service is not reachable/available. Are we doing something wrong? If a service is started in this way, will it validate the presence of fluentd before it starts? Do you have any solutions?

I also reported two new problems with the new version
#27321 
#27323

**Comment by mrjana** [comment]
@saithala Ok we probably need to understand the reproduction steps for your issue. Can you provide all the reproduction steps that you did to create your networks and services which resulted in the problem?

As for as the log collector problem yeah that's not how it works. First of all the docker service that you are creating is not part of the network to which the global service attaches. So both these two services are not discoverable by each other. Even when they are part of the same service if you try to reach them using the service name it may not go to the instance running in the same node as your other service. It may be routed to some other instance using rr rotation. What you need is a different way to communicate with that instance of the service. This may not be trivial. Let me think about it a bit more.

**Comment by saithala** [comment]
@mrjana As far as the reproduction steps are concerned, i think its pretty straight forward. So the steps I followed
Create Custom Overlay network, start all services attaching each one of them to the overlay network. 
1) Start Discovery service
2) Start Config service
3) start all other services 

I did not quite understand you explanation about the log collector. I first start the global service attaching it to the overlay network. Then I start other services attaching it to the same network. Why are these not discover-able to each other?

**Comment by mrjana** [comment]
@saithala I don't think there is any known fundamental problem in starting multiple services in the same network and trying to make it work. So if we have to make any progress on these issues that your are experiencing you would have to provide the exact reproduction steps as you performed to reproduce the problem.

As far as log collector and your service goes you said this:
```
So when we start other services (docker service create --log-driver fluentd --log-opt fluentd-async-connect=true --log-opt fluentd-address=fluentd:24224 ) where fluentd is the global service
```
I don't see a network option in that to suggest you have the service in the same network as fluentd. In any case using a service as log-driver is not supported at the moment.

**Comment by mrjana** [comment]
Also in addition to the reproduction steps please provide the `docker service ps` output of all the services that you have started.

**Comment by saithala** [comment]
Sorry my bad for the log collector, I only pasted part of the command. The full command for starting the global service makes sure its attached to the overlay network

**Comment by saithala** [comment]
@mrjana . this one example of a  service ps output thats not able to communicate with another service and the exception in the logs is Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused
In this case this service is not able to communicate with raabitmq service and when we start both of them, they were attached to the same overlay network.
`````````````````````````
ID                         NAME    IMAGE                                             NODE        DESIRED STATE  CURRENT STATE           ERROR
16zjk0ulr77q9b9dznzglfmky  edge.1  api-gateway-server:0.0.1-SNAPSHOT.perf  Host1 Running        Running 31 minutes ago

````````````````````````

The following is the service ps output of the rabbitmq (with 2 replicas) to which the above service is trying to connect.

`````````````````````````````````````````````````
ID                         NAME        IMAGE                      NODE        DESIRED STATE  CURRENT STATE           ERROR
9glu1m9b9t0f4aygawd0dqyon  rabbitmq.1  rabbitmq:3.6.3-management  cmcmdmz103  Running        Running 40 minutes ago
er9i8ib6auonjcjadc9c8sxz2  rabbitmq.2  rabbitmq:3.6.3-management  cmcmdmz103  Running        Running 40 minutes ago

``````````````````````````````````````````````

**Comment by mrjana** [comment]
@saithala Have you made sure you opened up gossip ports 7946/udp and 7946/tcp in your environment? Can you attach the daemon logs from `Host1` to the issue?

**Comment by saithala** [comment]
@mrjana  all the nodes in the swarm cluster are in the same subnet. So there should be no restriction on the ports

**Comment by mrjana** [comment]
@saithala That doesn't mean there are no restrictions on the ports. If you attach the daemon logs from `Host1` that will clarify a lot better.

**Comment by saithala** [comment]
@mrjana 
Attached is the daemon logs from host1.  There are some errors related to logging driver. Please ignore that. Thats the error related to the logging driver I explained earlier.
[docker.txt](https://github.com/docker/docker/files/529629/docker.txt)

**Comment by mrjana** [comment]
@saithala I don't see any obvious problems from the logs other than the fact that there are a lot of containers getting started on that node based on this log:
```
Oct 13 22:46:00 host1 dockerd: time="2016-10-13T22:46:00-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:25 host1 dockerd: time="2016-10-13T22:46:25-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:25 host1 dockerd: time="2016-10-13T22:46:25-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:25 host1 dockerd: time="2016-10-13T22:46:25-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:25 host1 dockerd: time="2016-10-13T22:46:25-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:25 host1 dockerd: time="2016-10-13T22:46:25-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:26 host1 dockerd: time="2016-10-13T22:46:26-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:28 host1 dockerd: time="2016-10-13T22:46:28-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:34 host1 dockerd: time="2016-10-13T22:46:34-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:34 host1 dockerd: time="2016-10-13T22:46:34-04:00" level=info msg="Firewalld running: false"
Oct 13 22:46:34 host1 dockerd: time="2016-10-13T22:46:34-04:00" level=info msg="Firewalld running: false"
```

Every line with the text `Firewalld running` is a container getting started.  I don't think you are starting as many containers. Are you service tasks going down frequently? To just debug this problem in manageable manner can you just start a simple service with say 3 replicas with a simple image (like` jwilder/whoami` or even nginx) and then starting another service(client) on the same network and exec into that client service container and curl the replicated service. If we can get that working on your cluster we know the cluster is working properly. Then we can bring in your application into the mix.

**Comment by saithala** [comment]
@mrjana  The reason you see so many containers is we were trying again and again (trial and error) to see if we can identify any pattern of when and how this is happening. Like I mentioned before, we restart the docker daemon and start all services and all of them start fine as long as we dont bring them down again or update them. Im thinking there is some issue with embedded DNS/VIP/IpTables. Just dont know what/where the problem is

**Comment by mrjana** [comment]
@saithala Ok, if you are saying everything is fine in steady state, we need to identify what sequence of changes to the cluster creates the problem. Let's start with what commands you issued that causes the communication to break down. If we can boil down the characterization of this problem to basically this:
* service A is able to communicate with service B
* I performed the following operations on the cluster
* After those set of operations service A is not able to communicate with service B

Is it possible to boil down this issue to such a sequence of steps?

Also for starters you can describe your cluster as in how many nodes, how many managers, how many networks, how many services and what is the replica size and how many are in these networks. Things like that will greatly help in accelerating the troubleshooting process.

**Comment by saithala** [comment]
Sequence of steps. I build the swarm cluster with 4 nodes. 3 of them are managers and 1 worker. To begin with, I start one replica (or I think replicas does not matter) of each service and attach all of them to the "same" custom overlay network. I have around 12 services.  So as you described, this is steady state. The service to service communication is fine at this point as all the services come up. Now, any change I make to the cluster randomly breaks service to service communication. By any change I mean, it could be I bring down one service or scale up a service. This change could be any for any service. The interesting thing is its not always communication between service A to service B breaks, Sometimes A-> B breaks, other times C->D breaks. So its completely random. At this point accessing another service by name does not work and I have shared the actual exceptions I got earlier in this post. No specific errors in the daemon logs as well as you saw.

**Comment by saithala** [comment]
@mrjana Just wanted to reiterate that in our case, service to service communication is happening over http protocol (http://discovery:8761) and not either tcp or udp. Is there anything special that needs to be done or should http work as well ?

**Comment by mrjana** [comment]
@saithala Yeah not been able to reproduce your problem. When you get into this situation i.e when the application errors out, can you try getting into the container where the application was running by running `docker exec` and try to manually execute `curl` (or even nslookup if you are having discovery problem) to see if there is really a problem in discovery? At the moment we are still looking at the problem from too high a level and that isn't providing sufficient clarity on what the actual problem is.

**Comment by thaJeztah** [comment]
closing as this one went stale
