### ISSUE TITLE
Do a fail-quick-syntax-check on the Dockerfile on the client

### ISSUE THREAD

**Issue by yongtang** [moby/moby#26877]
As is discussed in https://github.com/docker/docker/pull/26516#issuecomment-248868526 ,
it might be good to do a quick syntax check on the Dockerfile on client side. 

The reason for the above proposal is that, sending Context to docker daemon takes time and sometimes it takes a long time (when context is huge). In case there are syntax errors in Dockerfile, it is advantages to fail quick and not wasting time/bandwidth for a remote docker daemon.

There might be situations while client side Dockerfile syntax check is not enough. However, it is still a better UX experience to not wasting time/bandwidth for the user.

This issue is opened to track the above proposal.

cc @thaJeztah @duglin

**Comment by justincormack** [comment]
The quick hack way is to do `tar cf - Dockerfile | docker build -` now your patch is merged. I guess with a `--check-syntax-only` build option the client could use this rather than duplicating the code.

**Comment by thaJeztah** [comment]
@justincormack @yongtang yes, my intent was not to replicate the logic client-side, but to have the client send the Dockerfile to the daemon for validation (before sending the build context)

**Comment by duglin** [comment]
if we do this, I'd prefer for it to be part of the normal workflow and not behind a new flag. If it being there is too hard, or slows things down, then I don't think we should do it at all.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/26516 was merged, and with buildkit, the dockerfile will be parsed before the rest of the build-context is sent (if any), so I think we can close this one.
