### ISSUE TITLE
Error response from daemon: Driver devicemapper failed to remove root filesystem ...... devicemapper: Error running DeleteDevice dm_task_run failed

### ISSUE THREAD

**Issue by eromoe** [moby/moby#26900]
Linux zk1 3.10.0-327.28.3.el7.x86_64(centos 7)
Docker version 1.12.1, build 23cf638

There is a lot of exited containers which full of the disk.
I use `docker ps -a | grep Exited | gawk '{print $1}' | xargs docker rm` to delete exited container and get:

```
Error response from daemon: Driver devicemapper failed to remove root filesystem 228f2c2da3de4d5abd3881184aeb330a4c18e4311ecf404e2fb8cd4ffe15e901: devicemapper: Error running DeleteDevice dm_task_run failed
```

relate to https://github.com/docker/docker/issues/5684 which is closed.

**Comment by eromoe** [comment]
After `service docker restart`, `docker ps --all` show nothings, but disk still full.

Then I tried:
```
rm -rf /var/lib/docker/devicemapper/devicemapper/data
service docker restart
```

not work,  `service docker status` shows:
```
Sep 26 12:30:10 zk1 systemd[1]: docker.service: main process exited, code=exited, ...URE
Sep 26 12:30:10 zk1 systemd[1]: Failed to start Docker Application Container Engine.
Sep 26 12:30:10 zk1 systemd[1]: Unit docker.service entered failed state.
Sep 26 12:30:10 zk1 systemd[1]: docker.service failed.
```

**Comment by coolljt0725** [comment]
@eromoe  Since you have deleted `/var/lib/docker/devicemapper/devicemapper/data`, I think you should also delete the  whole `/var/lib/docker/devicemapper` and try if it can restart again

**Comment by eromoe** [comment]
@coolljt0725 Would that remove my docker images?

**Comment by ackris** [comment]
@eromoe Did the solution of @coolljt0725 work? I am facing the same issue!

Regards

**Comment by eromoe** [comment]
@ackris Too long ago, not remember clearly , but I think it worked.

**Comment by thaJeztah** [comment]
Let me close this issue, @ackris opened a new issue; https://github.com/moby/moby/issues/34463
