### ISSUE TITLE
Provide TLS infra for services

### ISSUE THREAD

**Issue by tlvenn** [moby/moby#26915]
Now that Docker with v1.12 and the swarm mode enabled can transparently handle TLS for its swarm, I think it would be great if this could be extended to services as well.

Most clusterable solution leverage TLS infra and ask the user to provide the CA cert as well as the node cert and this is just as tedious as settings TLS for the swarm manually.

**Comment by thaJeztah** [comment]
ping @diogomonica PTAL

**Comment by thaJeztah** [comment]
In general, we think it's a nice idea / concept, but it really needs more design (as it can be quite complex); would you be able to write up your proposal in more detail? Possibly adding some use-cases as well to help us think along

**Comment by diogomonica** [comment]
I have a few ideas on how to do this. I'm planning on shipping it right after 1.13 so we have a long time to test it.

**Comment by tlvenn** [comment]
Use case for example would be to provide PKI infra for running a CockroachDB cluster with Docker:
> https://www.cockroachlabs.com/docs/create-security-certificates.html

**Comment by AkihiroSuda** [comment]
@diogomonica 
Can I hear your ideas? :smiley:

**Comment by diogomonica** [comment]
@AkihiroSuda I'll share with you the design doc, how does that sound?

**Comment by tlvenn** [comment]
Hi @diogomonica , any chance you can share the roadmap / progress on this please ? Thanks !

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
