### ISSUE TITLE
Copying files to container on run before executing ENTRYPOINT/CMD

### ISSUE THREAD

**Issue by titpetric** [moby/moby#26944]
Scenario: I'm injecting some environment specific configuration that extends whatever is already packed into the container. These are various conf.d folders provided by various software (supervisord, php, nginx) and which already contain some files in the included conf.d folder to begin with. I want to provide these files before running CMD/ENTRYPOINT commands.

Problem: The obvious issue by using a volume mount on a folder is that the complete folder contents are replaced by whatever is provided from the volume. The running container is missing the defaults provided, before the volume is mounted.

Workaround 1: Currently, the only way I can move forward is to mount individual config files to their respective conf.d locations. It's not comfortable to do this, because I basically have to generate the complete `docker run` command.

Workaround 2: Another way to get the files into the running container is with `docker cp`, but there's a race condition between copying the file, and executing whatever is in cmd/entrypoint.

Suggestion (for docker run): add some kind of switch flag like `-V [source]:[destination] which would copy the files into the filesystem set up for the container, before running CMD/ENTRYPOINT.

Suggestion (for service create): There's already a --mount option, which might have already everything available to do this, but docs are scarce. There's a type=bind/volume/gluster which I asume is the name of the volume driver. Is it possible to create a "copy" volume driver, which would be close to what COPY/ADD inside the Dockerfile do?

What I would like is ideally the following:

Swarm: `docker service create --mount type=copy,source=[source],target=[destination]`<br/>
Docker: `docker run -V [source]:[destination] image`

Both should be equivalent to running something like this Dockerfile:

```
FROM image
COPY [source] [destination]
```

Except that the resulting image wouldn't be commited & used for docker run/service.

Is it possible to create something like this with a custom storage driver? I'll gladly review some docs for it if it's possible and evaluate if it's feasible to develop this on my side, because I'm not sure how high on your priority list this feature request would land.

**Comment by thaJeztah** [comment]
Yes, bind-mounting single files can be troublesome; however, can be worked around given the right directory-layout of the image (but may depend on what's running in the container). Either building an image with the configuration built-in, using a configuration management solution (e.g. https://github.com/kelseyhightower/confd) or using environment variable (not for credentials), could be considered as an alternative. 

However, this is already possible through `docker cp`, as there's no race if you don't start the container; Simply _create_ the container, then copy the files, and then start it;

```bash
$ docker create --name web -p 8080:80 nginx:alpine
52f2d3b0c44ad32d4245412cb79246775b635c20364dff0681a222a0a5f5fb0c

$ docker cp index.html web:/usr/share/nginx/html/
$ docker start web
web

$ curl localhost:8080
<html>
<body>
HELLO CUSTOM HOMEPAGE
</body>
</html>
```

**Comment by titpetric** [comment]
Hi,

you are of course correct when it comes to daemons, but I have significant use cases for cli. I'm sorry for not being very clear on this point.

1. There's some convenience in `docker run` which I'm relying on, most notably `--rm`,
2. I'm relying on arguments which override CMD for various cli software (composer, php, egon, go, gvt, hexo, hugo, lessc, mkdocs, mysql, node, npm, php, phpunit, phpcs, sqlite, ssmtp, swagger,...)

For those cases which require custom configuration, I try to structure my projects directory-layout in such a way that the configuration can be injected with minimal number of -v options. So I have projects which rely on quite different configuration/settings. I just keep hitting this problem with time as most software provides some sort of conf.d directory also provides "reasonable" defaults, which you'd keep, or which you would generate runtime.

It's also quite a prohibitive practice to "install" these configs in the container via entrypoint (run.sh), as it's commonly done. Yes, I could map a config volume to "/install_configs" and then let the container copy everything to the correct locations (I asume this is what `confd` does), because:

1. I would like PID 1 to be the software which is supposed to run (php, go, nginx, etc.),
2. If it's not, I have to figure out some reasonable way to pass signals to it (`tini`?),
3. It's not enough just to pass signals, if you want to generate some configs from ENV you need to have an execution chain.

If I would build images, at least they would be efficient because of the copy-on-write, the only problem is that I don't want them to exist. I want to throw changes away when the container finishes it's run.

**Comment by thaJeztah** [comment]
> There's some convenience in docker run which I'm relying on, most notably `--rm`

There's good news on that part; in docker 1.13, the `--rm` feature is moved from the "client" to the "daemon". This means that you can also set `--rm` through `docker create`, and the daemon handles removing the container after it exits. See https://github.com/docker/docker/pull/20848 (and https://github.com/docker/docker/pull/26030)

> I would like PID 1 to be the software which is supposed to run (php, go, nginx, etc.)

An entrypoint script still allows you to do so; the trick here, is to execute the entrypoint script, but after it completes, use `exec <main-process>`, so that `<main-process>` becomes PID 1 (see for example the [entrypoint-script for the official MySQL image](https://github.com/docker-library/mysql/blob/9f95658f528699d2c2017ca42ad163a9d5c5e7c1/5.7/docker-entrypoint.sh#L132-L134)

**Comment by titpetric** [comment]
@thaJeztah Major karma/libation points for `exec`! Solves at least half of my problems :D

**Comment by thaJeztah** [comment]
With the introduction of `docker config`in Docker 17.06 (https://github.com/moby/moby/pull/32336) it's now possible to add configuration files to services (also `docker secret` allows providing "secrets" in a similar way). 

Additional enhancements in this area may still be coming, for example: templated configs; https://github.com/moby/moby/pull/33702

With the above, I think this enhancement request is (at least largely) addressed, so I'll go ahead and close 👍  (feel free to comment or open a follow-up feature request if something is missing)

**Comment by samrocketman** [comment]
In my case, I would like to unit test an image using `goss`.  My docker daemon is remote from my docker client.  My current options are:

* bake the `goss` binary into my image.
* bake a second image on top of my real image including the `goss` binary for running tests.
* Download the `goss` binary to the daemon host when I first configure it.  Then, mount the goss binary inside as a volume.

`goss` can read tests via stdin so it is trivial to pass test to the binary inside of the container without the need for any configs.
