### ISSUE TITLE
'depends_on' field in docker-compose.yml file is not honored when used with 'docker-compose bundle' to create '.dab' file.

### ISSUE THREAD

**Issue by Saravana9210** [moby/moby#26943]
**Description**
'**depends_on**' field in _docker-compose.yml_ file is not honored when used with 'docker-compose bundle' to create docker bundle (**.dab** file).

**Steps to reproduce the issue:**
1. Define 3 services in _docker-compose.yml_ with service2 and service3 depends on service1 (using depends_on field)
2. Go to the directory where you have the docker-compose.yml file. 
3. Create docker bundle using '**docker-compose bundle**' command (this will create a **docker.dab** file)
4. Deploy the bundle using '**docker deploy docker**' command

**Describe the results you received:**
1. All 3 services are started 
2. But, order of starting services is random ('depends_on' field is not considered)

**Describe the results you expected:**
1. service1 should be stared first

**Additional information you deem important (e.g. issue happens only occasionally):**
Also, pls throw some light on service registry, service discovery and communication among services. Thanks in advance !!!

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've 3 VMs with docker 1.12.1 installed

VM1 - swarm master
VM2 - Node1
VM3 - Node2

**Comment by thaJeztah** [comment]
The `depends_on` option is currently not supported in the compose v3 format (a discussion on this can be found in https://github.com/moby/moby/issues/31333), and the `.dab` format was experimental (and is now removed), so I'm closing this issue
