### ISSUE TITLE
Is there a way to list a set of Repos from a registry v2 service using only docker client?

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#26969]
**Description**

"/v2/_catalog" provides the list of repos in a private registry, and I know how to use REST + curl to read that content. However, different authorization methods (token, htpasswd, ..) make it complex to login for token and conduct REST response by curl every time. Are there some methods to make it easy, like the following: 

docker login priv-registry:port
docker push priv-registry:port/example
docker list priv-registry:port    -- to lookup "/v2/_catalog" using existing token

Thus, we don't need to use curl request based on complex and different AUTH methods.

**Comment by justincormack** [comment]
Not at present. The current thinking is to make a tool for interacting with the registry to do more complex things rather than adding everything to the `docker` command.

**Comment by ghostplant** [comment]
Okay. But unless "docker pull/push" are dropped regardless of keeping compatibility with the earlier version, docker itself has to implement full authorization support which is as complex and redundant as a special tool to make.

**Comment by ghostplant** [comment]
I found that docker records its login session to "~/.docker/config.json". However, the "auth" string is unuseful to me. Is it a good idea to store the long Token as well? Thus I can use curl with this token to request what I want to look up.
For security consideration, if Token string is unsafe to store in "~/.docker/config.json", it might be stored in /var/lib/docker together with other configuration.

**Comment by Alessar** [comment]
I vote that docker command for get list of registries will be very helpful.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
