### ISSUE TITLE
nocopy bind mode applicable to mounts?

### ISSUE THREAD

**Issue by dmandalidis** [moby/moby#27046]
Although docker-run(1) (1.12.1) states that :

`To disable automatic copying of data from the container path to the volume, use the nocopy flag. The nocopy flag can be set on bind mounts and named volumes.`

when I do :

`docker run -v /home/mandas/foo:/tmp:nocopy busybox`

I get :

`docker: Error response from daemon: Invalid bind mount spec "/home/mandas/foo:/tmp:nocopy": invalid mode: nocopy.`

Is the man page wrong or is it an issue?

**Comment by thaJeztah** [comment]
The man page is wrong, as copying _never_ takes place on bind-mounted directories

**Comment by sn-narang** [comment]
#dibs
