### ISSUE TITLE
cli: add ability to set domainname and hostname separately

### ISSUE THREAD

**Issue by cyphar** [moby/moby#27067]
Currently `docker run --hostname` will set `hostname` to the full value of the field, even though [because of this PR](https://github.com/docker/docker/pull/20200) we should be able to specify both without issue. Namely this could be implemented with just a `--domainname` flag to `docker run` and the other relevant commands.

```
% docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
```

```
% docker info
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 141
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.7.2+20160906
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: apparmor
Kernel Version: 4.8.0-rc8-1-default+
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.671 GiB
Name: baradur
ID: DOHI:RAQ5:MYV5:73JL:7UHU:6NXS:RWGD:IQ7D:IQZ2:COCW:BWJ6:HHYN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

What I got:

```
% docker run --hostname hello.cyphar.com hostname
hello.cyphar.com
% docker run --hostname hello.cyphar.com hostname -f
hello.cyphar.com
```

What I would like:

```
% docker run --hostname hello --new-flag-name cyphar.com hostname
hello
% docker run --hostname hello --new-flag-name cyphar.com hostname -f
hello.cyphar.com
```

This would also have to handle things correct with `/etc/hosts`, but I assume that the API already handles that (we just need to have the client do it). Cheers.

**Comment by thaJeztah** [comment]
Looks like duplicate(ish) / related to https://github.com/docker/docker/issues/26444

Not sure which one we should close though (this description is clearer as feature request) :smile:

**Comment by justincormack** [comment]
Yes, this one is clearer...

**Comment by cyphar** [comment]
I just checked and runC doesn't support handling the `Domainname` separately (specifically `setdomainname(2)`. So we'd have to modify runtime-spec and runC -- which would mean that there would be some backwards-compatibility questions wrt how the `Domainname` API should be handled.

**Comment by crosbymichael** [comment]
Whats the actual usecase for this?

**Comment by justincormack** [comment]
@crosbymichael there are two use cases that I know of: 1. the name length limit for `hostname` is shorter than `hostname` plus `domainname`, so as people are trying to cram a FQDN into a `hostname` sized field they run out of space. 2. applications that actually look for `domainname`, the only ones I know of are YP/NIS which use it (I think that is why it is there). Not many people run these now, so we have not had many complaints, but it is a valid use case.

**Comment by cyphar** [comment]
We had some customers that were lamenting the lack of this feature. I'm not _completely_ sure what the reason was, but I believe it had something to do with some legacy software they were running in containers that depended on setting the domainname.

**Comment by justincormack** [comment]
@cyphar probably NIS, it does require this.

Opened an issue for OCI spec here https://github.com/opencontainers/runtime-spec/issues/592

**Comment by squeed** [comment]
Be careful, different distros handle hostnames with periods differently: https://github.com/coreos/rkt/issues/2042#issuecomment-242390194.

**Comment by justincormack** [comment]
@squeed that command is testing the behaviour of the `hostname` command which seems to mess with the underlying data. I recommend using `cat /proc/sys/kernel/hostname ` and `cat cat /proc/sys/kernel/domainname` to see what the kernel has set, as different versions of `hostname` seem to display different things from the same data.

**Comment by cyphar** [comment]
^^ You could also write some code that just reads `uname(2)` directly (because `domainname` is a field of the `utsname` struct the kernel returns).

**Comment by justincormack** [comment]
@squeed the man page explains how the different `hostname` options work http://man7.org/linux/man-pages/man1/hostname.1.html in particular in this issue we are talking about the NIS domain name, as the FQDN can't be set directly, other than via file config.

**Comment by squeed** [comment]
@justincormack Yeah, I realize the output of `hostname` doesn't actually reflect the real UTS value; just pointing out a fun little divergence between distros in case it came up. Had us stuck in a weird support loop for a while.

**Comment by justincormack** [comment]
Actually hmm. I got confused too....

So yes, there is the NIS domainname, now being tracked for `runc` as above.

However... We write the `hostname` into `/etc/hosts`, which is the FQDN that `hostname` will look up via DNS ie if I do

```
docker run --hostname banana.test alpine cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	banana.test
```

Then I have a FQDN being set, and I also get correctly

```
docker run --hostname banana.test alpine hostname -d
test
```

Which is reading it from there - if you do `docker run --hostname banana.test --cap-add SYS_PTRACE justincormack/debian strace hostname -d` you can see that there is no `gethostname` call just a `read` from `/etc/hosts`.

So this one is probably the one that people want to be above 64 characters and allow underscores after the first segment. But we can't pass a longer version through to `sethostname(2)`.

So we should probably take the part up to the first `.` and use that as the `hostname` for `runc`, and change the validation... Question is will that break anything?

(We could be more cautious and try to not change existing behaviour with some hybrid).

**Comment by cyphar** [comment]
@justincormack The hostname used to be split by Docker before #20200. Now it's just passed directly. What IMO we should do is add a `--domainname` flag or similar so that you explicitly set the `Domainname` field in the response.

**Comment by justincormack** [comment]
@cyphar reading the old issues again....

**Comment by cyphar** [comment]
@justincormack Is this still something that you're interested in us working on, or should we close this?

**Comment by thaJeztah** [comment]
it came up recently again, and I personally love explicit > implicit, so i'm +1

**Comment by thaJeztah** [comment]
+1 to looking into this that is lol

**Comment by ithh** [comment]
+1 we have a need to run software that checks the domainname for its licensing. Having a separate parameter or capability would be great.

**Comment by mjgar** [comment]
+1 we have a need to run software that checks the domainname for its licensing. Having a separate parameter or capability would be great.
