### ISSUE TITLE
Create services with node-local networks

### ISSUE THREAD

**Issue by mavenugo** [moby/moby#27082]
`docker service create` explicitly takes in `--network` option to let user select a globally scoped network for which swarmkit can allocate and manage resources.

But `--network` is optional and if the user doesn't specify one then swarmkit doesn't setup any network or allocate network resources ( _one exception is -p where swarmkit uses the default `ingress` network_ ).. In such a scenario docker daemon uses the node-local default network, `docker0` bridge in Linux or `nat` in Windows, etc... 

This proves that swarmkit and services are robust enough to work in node-local network setup. Infact, there is absolutely no special case to support this scenario and that means the same logic must work for other node-local networks such as `--host`, `--none` or other user-defined `bridge` network or `macvlan` or `ipvlan` drivers. (there has been a few requests to enable this  as well)

But, we don't have the UX/API to enable this functionality & this is a proposal to enable that support.

node-local networks (aka `local-scoped` networks) needs resource allocation and management done locally by the engine in the same traditional ways. Hence swarm manager cannot be involved in such a node specific resource allocation. Hence it is not appropriate to overload the `--network` keyword in `docker service create` to convey the same functionality. Infact, (as per @mrjana) this feature can be considered more of a `network constraint` applied by the swarm manager and schedule the task only on the nodes on which the corresponding `node-local` network is present.

In order to achieve this, we can consider either of the following UX -
- overload the `--network` API in `docker service create` that will take in `node-local` networks as well and make a decision to use a `global-scoped` network if present or apply the `network constraint` to filter schedule the tasks only to those nodes where the `node-local` network is present.
- introduce a new `--net-constraint`flag (apologies on poor choice for the flag name), and that is explicitly meant for such a constraint mechanism and scheduling the task on appropriate nodes.

In either case, the only role of swarmkit is to schedule the task on a particular node and the rest of the functionality is handled at the engine level just as it is done today for the `default` case.

ping @mrjana @icecrime @al @stevvooe @cpuguy83

**Comment by mavenugo** [comment]
also ping @jpetazzo . This will help with your request for `--network=host` use-case.

**Comment by thaJeztah** [comment]
Do local networks have to be created in advance, or should a service carry all the information to create that network on the node it's scheduled on? Comparing this to how `-v named-volume:/foo` differs from `--mount ...`, where `--mount` contains the full definition of the volume to create. Similarly, we may implement a flag that contains the full definition of the network to create if it doesn't exist.

**Comment by mavenugo** [comment]
@thaJeztah I don't think we should be doing that. We must just use it as a constraint to schedule the tasks on those nodes where the network is already present. A similar proposal was put forward for `docker run` and we decided to stay with the idea of letting the `operator` to manage the networks while container is placed on the network.

**Comment by jpetazzo** [comment]
Questions:

1) Would it make sense to express constraints with `--constraint` instead of a separate flag?

I guess there is a good reason if you propose a different flag, but I'm wondering. :)

2) What about `--publish` with node-local networks?

When the container ends up having a network sandbox, I suppose that it is possible (and relatively reasonable) to support it.

In the case of the host network, it still makes sense (it would mean that the IPVS load balancer would serve request to services running on the host namespace) but it would be trickier:
- either IPVS sends traffic directly to the hosts, and traffic then goes unencrypted on the underlay;
- or we want traffic to be encrypted, and then we have to use a trick to force it on an overlay.

As far as I'm concerned, I'm fine with forbidding `--publish` together with `--net <host-local>` for now (since it can always be designed and added later).

Other than that – I think that this will be very useful. Thanks for coming up with this design!

**Comment by mavenugo** [comment]
@jpetazzo thanks for the feedback.

> 1) Would it make sense to express constraints with --constraint instead of a separate flag?

My assumption is that `constraint` is a manager only operation to select a node to schedule a task. The node itself doesn't get involved in how the constraint is applied or the content of it. If we have to overload the constraint for node-local networks, then the node must look into this field and extract the network value to apply it on the local containers while scheduling the task. am not certain if such a special case is acceptable.

> 2) What about --publish with node-local networks?

`--publish` results in routing-mesh by default (via the `ingress` overlay network). If we have to think this proposal as a `constraint`, then it shouldn't matter if a service is connected to `ingress` network for the north-south traffic and another node-local network on individual nodes where it is ultimately placed. Since we support services connected to multiple networks, this will naturally work without any special cases.

But it might cause a confusion on the user's mind if the constrained `node-local` network will handle the publishing (or) if it is managed by the routing-mesh.  Having said that, the current UX `docker service create -p 80:80 --network foo xxxxxx` will result in a similar scenario where `-p` results in routing-mesh and the service connected to network foo as well.  That makes it inline with the existing functionality.

**Comment by mavenugo** [comment]
@jpetazzo as you can see in https://github.com/docker/docker/issues/27266, am using the `selector` approach to match on labels. Please share your feedback.

**Comment by stevvooe** [comment]
@mavenugo Why not define a `default` network that will grow as nodes join?

**Comment by thaJeztah** [comment]
We should look at this in light of https://github.com/docker/swarmkit/pull/1645 as well

**Comment by mavenugo** [comment]
@thaJeztah i dont think these are related. but sure we can discuss the relationship.

**Comment by mavenugo** [comment]
@stevvooe not sure if I follow. 

The intention of this proposal (we can certainly replace the current label approach to another - maybe constraints-based) is to let the user handle local resource management at the node level and relieve swarmkit of the duty of node-level resource allocation/management. There are multiple use-cases that triggered this requirement. Especially those local-scoped network plugins that has stronger ties to the location of a node (such as macvlan/ipvlan) 
* the subnets must come from a particular range per node
* parent interface should be specified (also per node)
* next-hop neighbor could be a ToR switch with a specific IP (again per node-config).

**Comment by rootsongjc** [comment]
I create "mynet" bridge network on every swarm node, I want to use mynet now, but it doesn't work. I really need the future to choose my own node-local network now instead of overlay network.

**Comment by thaJeztah** [comment]
@rootsongjc other than "I need this", can you add more information about your use case? e.g., why does your use case need a local network, and not an overlay network; such information can be helpful when designing/developing a feature.

**Comment by rootsongjc** [comment]
@thaJeztah I have a docker plugin named "docker-ipam-plugin" [https://github.com/rootsongjc/docker-ipam-plugin](url) I need to make a flat network in my company so that the docker hosts and containers can recognize each other and the containers will get the fixed IP address. This is very helpful and we realized it in docker 1.11 applied to hadoop yarn. Now I hope I can use my own local node network other than overlay network inn docker1.12 swarm mode.
NETWORK ID          NAME                DRIVER              SCOPE
01b1d643b734        bridge              bridge              local               
a5cc6b68aa89        docker_gwbridge     bridge              local               
ed079ba7b63f        host                host                local               
eideqqvbuslp        ingress             overlay             swarm               
**85fec12c0870        mynet               bridge              local**               
9edec16bc302        none                null                local

**Comment by JustAdam** [comment]
Our case is to be able to access the service from the host (or container which is not a service) via tcp/udp.

Think of monitoring agents that pull stats from a service via an endpoint or special port.  How to actually access the endpoint from the host when it just exists on the overlay network?  Adding the container to a local network seems a good solution.

We made [this](https://github.com/SymfoniNext/ola) to help us out in the meantime.

**Comment by thaJeztah** [comment]
Thanks @rootsongjc @JustAdam, that's helpful

@JustAdam 

> Our case is to be able to access the service from the host

I think that should be possible without attaching it to a local network;

```bash
docker service create --name foo nginx:alpine

docker inspect --format '{{ .NetworkSettings.IPAddress }}' <container-id>
172.17.0.2

curl 172.17.0.2

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
...
```

> or container which is not a service

I _think_ that should work as well from inside a container;

```
docker run --rm alpine sh -c 'apk add --no-cache curl && curl 172.17.0.2'
...
(4/4) Installing curl (7.51.0-r0)
...
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

One trick is also to join the network namespace of the service container;

```
docker run --rm --network=container:<container-id> alpine sh -c 'apk add --no-cache curl && curl localhost'
...
(4/4) Installing curl (7.51.0-r0)
...
<html>
<head>
<title>Welcome to nginx!</title>
<style>
```

For **docker 1.13**, an option is added to make overlay networks "attachable" for non-service containers (with the `--attachable` flag);

```
docker network create -d overlay --attachable test-network
7d9otkjb5uo8ahwbt01pxld8g

docker service create --name web --network test-network nginx:alpine
dhofpt8pmfq7crannil6yc4gt

docker run --rm --network test-network alpine sh -c 'apk add --no-cache curl && curl web'
...
(4/4) Installing curl (7.51.0-r0)
...
<html>
<head>
<title>Welcome to nginx!</title>
...
```

We have a release candidate available for testing docker 1.13 (not recommended for production, as it may still contain bugs); https://github.com/docker/docker/releases

**Comment by JustAdam** [comment]
@thaJeztah The services are attached to a custom overlay network so I don't think that will work.

```
$ docker network create -d overlay test-net
aqom28oa5pphkgce62yzx1tp8

$ docker service create --name web --network test-net nginx:alpine
85cl37a81oacugb7if5uqo7oh

$ docker inspect -f "{{ .NetworkSettings.IPAddress }}" web.1.xxx

$ 
```

The test-net network is not routable from the host so using that IP address is also out.   Having the container on the local bridge network seems to be the easiest solution (and mimics how things would be without SwarmKit).
The `--attachable` flag looks a good solution for non-service containers, there is still the case for host level access.

**Comment by mavenugo** [comment]
@rootsongjc with docker 1.13, `docker service create` supports plugins. The only restriction is that the plugins must be global scoped so that Service Discovery and Load-balancing can work seamlessly across the nodes. So, in order to take care of your requirement, can you make your network and ipam plugin to be global scoped ? That way, you get the best of both worlds.

**Comment by mavenugo** [comment]
@JustAdam PTAL : https://github.com/docker/docker/pull/27917, which brings in node-level access to each container launched via `service create`. With this, you can get individual container access via tcp/ucp ports (just like one can access a container via `docker run -p x:y` tcp/udp port) for monitoring and other purposes. Does that satisfy your requirement ?

**Comment by mavenugo** [comment]
@jpetazzo @aluzzardi @stevvooe @thaJeztah we have 2 different kinds of requirement here.

1. Host level access to the containers launched via `docker service create`. We introduced #27917 to alleviate some of the requirements. But some use-cases are more performance sensitive with a tighter underlay integration. So, they prefer `--host` support for such scenarios. When it comes to non-swarm-mode use-cases, docker networking doesn't add any Service-Discovery or Load-Balancing primitives to `--host` mode. But with swarm-mode, supporting `--host` mode without SD/LB might impact use-cases which depend on such seamless access which we come to expect of swarm-mode. If we have to support `--host` mode for `docker service create`, should we take up the SD/LB challenge as well ? (Note : `--host` is a special case)

2. Generic support for `node-local` networks for `docker service`. This use-case is applicable for those scenarios where containers needs individual routable ip-address in the underlay (such as macvlan & ipvlan drivers/plugins) and these drivers typically rely on dedicated subnet per node. Having such node-level configuration doesn't work well with global network drivers because of the centralized management at the swarm-manager level. Hence, we depend on node-local networks to deal with distributed network management. one down-side of this would be that swarm-mode cannot provide SD and internal LB for such local-scoped networks. The users must supply SD/LB functionality to these containers. Do you think it is confusing at the user level to provide this node-local network feature and let them handle the SD/LB ?

**Comment by rootsongjc** [comment]
@mavenugo Approved! I think if we use the node-local network, we have to handle the Service Discovery and Load Balance by ourself.

**Comment by JustAdam** [comment]
@mavenugo Yes I think so, as long as this works :smile:;

```
docker service create --network test-net --publish target-port=1234,published-port=127.0.0.1:1234,mode=host ...
```

**Comment by rootsongjc** [comment]
@JustAdam What's the docker version you running the command?

**Comment by JustAdam** [comment]
@rootsongjc It should work from 1.13.  See #27917

**Comment by thaJeztah** [comment]
FYI Lots of discussion about that one; after UX consistency review it was decided that it will be renamed to `--publish` before 1.13 GA

**Comment by SilentHunter124** [comment]
@mavenugo Are there any news concerning this ticket? We are using the commercial data center version and this feature is the last piece which is missing in our architecture. Our security department only allows docker with macvlan, no other, so we need to manage services with macvlan driver...

**Comment by mavenugo** [comment]
@SilentHunter124 can you PTAL my [comment](https://github.com/docker/docker/issues/27082#issuecomment-263080861) above and confirm if you are okay with the limitation of swarm-mode will not be providing SD & LB for these containers and the apps have to rely on the user provided external SD & LB ?

**Comment by SilentHunter124** [comment]
@mavenugo I can confirm that a Service Discovery is not neccessary when the container gets the static ip address using --ip (or otherwise) and also a load balancer is not required when launching a service with known ip addresses, an external load balancer can be configured using these known addresses... Do you understand my thoughts?

**Comment by mavenugo** [comment]
@SilentHunter124 yes. I understand your point. Being a service driven work-flow, you will not be able to use the `--ip` static-ip address for the containers. And yes, with macvlan and proper underlay integration, external load-balancer integration will be pretty smooth. The only trick would be for you to program the external LB dynamically with the container IP  as and when the service scales up/down. Which I believe you would have thought of given you are asking for macvlan underlay integration ;-)

**Comment by SilentHunter124** [comment]
@mavenugo The external F5 Load Balancer has an API for that and jenkins is doing the job automatically with deploying the container. Can you explain a little bit more about how to assign ip address of a macvlan container? Simply without swarm it would be: docker run -d --net=macvlanXXX --ip=x.x.x.y --name=nameX+1 <imagename, how do you achieve it in your proposal?

**Comment by xmackex** [comment]
Was able to get it work "oldway" with 
`docker service create --name my-web --publish mode=host,target=80,published=80 --mode global nginx`
Looks good, but I wonder are you planning to add this functionality to "docker-compose.yml" file?
Unfortunately have not found anything according to this mode in [(docker-compose file reference)](https://docs.docker.com/compose/compose-file/). 
Also checked with `network_mode: host`, but it was ignored as expected.
Compose file:
```
version: '3'

services:
    redis:
        image: redis
        # restart: always
        network_mode: host
        ports:
            - "6379"
        logging:
            driver: "json-file"
            options:
                max-size: '1m'
                max-file: '5'
        #healthcheck:
        #    test: ["CMD", "curl", "-f", "http://localhost"]
        #    interval: 30s
        #    timeout: 5s
        #    retries: 3
        deploy:
            mode: global
            #mode: replicated
            #replicas: 2
            update_config:
                parallelism: 1  # number of containers to update at a time
                delay: 5s  # time to wait between updating a group of containers
            restart_policy:
                condition: any
                delay: 1s
                window: 5s
            placement:
                constraints:
                    - node.role == worker
                        #- node.labels.role != common
            resources:
                limits:
                    memory: 1g
                    cpus: '2'
```

**Comment by chicco785** [comment]
@thaJeztah in relation to what are the concrete use case needs, in our case we are working on containerised VNF, and for us the benefit would be:

1. performance: overlay networks are less performing that ipvlan / host ones
2. direct control of routing for network service chaining: everything behind the overlay network, is kind of out of control. to which instance will you connect? how do you chain an external service to a a specific docker service instance inside a swarm cluster?

of course, you could achieve everything giving up on docker swarm, and self orchestrating the different docker-engines, but then you will have the burden of managing service status yourself across the single engines, while docker swarm is currently taking care of that.

@mavenugo while i agree with the discussion above on the fact that there is no need for swarm load balancing support (you can easily use an external one or one self-setup in the swarm), i think that exactly in relation to facilitating the automatic re-configuration of the load balancer, still some level of service discovery would be beneficial. not sure what's the complexity in there to have the ability to update dns in the swarm taking into account ipvlan / host ips. (i am quite naive on some docker architecture aspects, sorry for that)

**Comment by jkaberg** [comment]
Our use case centers on needing to route Docker Services through a specific VLAN and gateway (while having the host's on another VLAN), which we can achieve with the macvlan driver (as I understand it).

**Comment by eyz** [comment]
In lieu of having VIPs provisioned, such as with overlay, are there currently events created in an event stream during global-scoped network join / leaves, or if not, are there any plans to have a generic reverse proxy / LB plugin API perhaps? I would be interested in wiring this implementation to something like haproxy in my environments, to implement a transparent load balancing solution, which seems to be missing with no VIP creation. Is there any API assistance for an integration like this on a roadmap, or already available?

**Comment by eyz** [comment]
> I have a docker plugin named "docker-ipam-plugin" https://github.com/rootsongjc/docker-ipam-plugin I need to make a flat network in my company so that the docker hosts and containers can recognize each other and the containers will get the fixed IP address. 

@rootsongjc, I would be interested if you have updated your IPAM plugin to support 1.13, or have plans to. It is a good example of how to handle IPAM, and I would like to use it as an example of how to implement IPAM in the future.

**Comment by rootsongjc** [comment]
@eyz sorry, after such a long time to reply you. I have no plan to update it to support docker 1.13, as we have migrated to Kubernetes and make use of **flannel** as a network plugin.

**Comment by eyz** [comment]
@rootsongjc, no problem. Also, I've made my own IPAM plugin since then.
