### ISSUE TITLE
Forwarding swarm mode commands from worker to manager

### ISSUE THREAD

**Issue by bgokden** [moby/moby#27091]
Currently worker nodes, does not respond to "docker service" and "docker node" commands. In consul which uses raft protocol, worker nodes forward command to the manager nodes. 
So same behaviour can be implemented in docker swarm mode.

This will be useful in large cluster scenarios, where a user/application lost the list of managers.

**Comment by thaJeztah** [comment]
As far as I know, this is by design; only managers should have access to these commands / information, to keep control over the swarm secure.

> This will be useful in large cluster scenarios, where a user/application lost the list of managers.

Can you explain this a bit more? I don't fully understand - applications running in the Swarm should have no need to know where / what the managers of the swarm are; could you give an example?

**Comment by bgokden** [comment]
It is ok if it is for security.

I have built a simple client with docker-machine, I stored the manager locally to a file. I wanted to use the cluster with another colleague who has ssh access to nodes, but since he does not have list of manager, he has to poll every node in the cluster to find the manager. It is easy for a small cluster but it would be hard for a large cluster. One idea was to store manager node addresses in a kv store in the cluster. There are a few work-arounds to find manager nodes.

One of my colleague said they had query forwarding to manager nodes in consul. For me, it would be better if worker node return the ip address of the manager/leader node. Does this also violate security model?

**Comment by cpuguy83** [comment]
@bgokden 
The difference between swarm and consul here is that in consul, all the nodes are either participating in the raft or specifically engaged as a proxy, where it is normal to forward requests to a leader.

In swarm, only the "manager" nodes participate in the raft. Among the manager nodes only 1 is a leader, and in that sense, each manager will forward requests as needed to the leader.
Worker nodes have no access here.

So a "worker" node in swarm is not the same as a worker node in consul.

**Comment by bgokden** [comment]
@cpuguy83 Thank you for the information.

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
