### ISSUE TITLE
Add file or directory info to the "oci runtime error: no such file or directory" error message

### ISSUE THREAD

**Issue by AntoineCezar** [moby/moby#27112]
**Description**
When "oci runtime error: no such file or directory" appears no file or directory is provided

**Describe the results you received:**
'oci runtime error: no such file or directory'

**Describe the results you expected:**
'oci runtime error: no such file or directory "the/missing/path"'

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64
```

**Comment by tonistiigi** [comment]
This particular error comes from https://github.com/opencontainers/runc

**Comment by thaJeztah** [comment]
closing as duplicate of https://github.com/moby/moby/issues/29420, which has more details on some of this
