### ISSUE TITLE
[QUESTION] Can I configure swarm for one way networking overlay?

### ISSUE THREAD

**Issue by hamid-elaosta** [moby/moby#27141]
We have a common setup with infrastructure that we deploy, in that it consists of two Docker hosts, one on LAN and another in DMZ, between the two hosts is a firewall.

The LAN machine hosts services that connect outward to the DMZ machine, through the firewall, allLAN host network connections are outgoing or established only.

On each of the two hosts are several services. Within each host, the services intercommunicate with a docker virtual network, each finding each other using their Docker hostnames.

We are looking for a way to merge these two virtual networks, so that services on the LAN host can access those on the DMZ host using their Docker virtual network names, but maintain the outgoing only security model.

Is there a swarm configuration we can use, so that LAN services can access DMZ services on the same (overlay) network without allowing return networking, except for established connections, in the same vein as our existing setup?

Currently, we expose a port on each service on the DMZ and make outgoing connections from the LAN host. No incoming ports are open on the LAN host.

All LAN to DMZ connections are using TLS to exposed ports on the LAN IPs of the DMZ services, this adds difficultly in that we have to either expose an additional port (to the external facing ones) or use the same exposed port, and add the LAN IP of the DMZ services to the TLS certificate (which is not acceptable).

If I can further clarify, please let me know. Any help and/or suggestions within the security requirements would be appreciated.

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by hamid-elaosta** [comment]
Any input on this yet? I'm still looking for a solution.

**Comment by sanimej** [comment]
@hamid-elaosta Docker networking model allows all the tasks on a overly network to communicate on all ports. There is no option currently to limit the access only to certain ports or based on connection status.

**Comment by hamid-elaosta** [comment]
This issue was inevitably solved outside of Docker/Swarm and its networking capabilities. Closing as it's unlikely to see further discussion/progress.
