### ISSUE TITLE
Docker Remote API info missing lots of fields in documentation

### ISSUE THREAD

**Issue by Khazrak** [moby/moby#27166]
**Description**
When I ran the "info" path in the Remote API v1.24 I got a lot more fields then the documentation said, these are:

Plugins > Authorization
CPUShares
CPUSet
BridgeNfIptables
BridgeNfIp6tables
ExecutionDriver
LoggingDriver
RegistryConfig > Mirrors??? (the IndexConfigs have array of Mirrors but the RegistryConfig itself has also Mirrors, maybe a bug?)
ClusterAdvertise
Runtimes
DefaultRuntime
Swarm (has lots of things in it)
LiveRestoreEnabled

I attach the raw response json I got:
[info.txt](https://github.com/docker/docker/files/512218/info.txt)

**Steps to reproduce the issue:**
1. run "/info" on the remote api v1.24
2. check the response JSON and compare to docs
3.

**Describe the results you received:**
Lots of more fields then documentation has

**Describe the results you expected:**
Documentation of all fields

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-10223820-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 664.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.7 GB
 Metadata Space Used: 1.389 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135 (2016-09-26)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.49 GiB
Name: karl_rog
ID: IOCD:Y7FK:RDB6:43I7:QLCF:OBP5:LKJR:QLYD:NC6U:V7GA:ROQA:TCVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 codeslasher.se:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by shaynewang** [comment]
#dibs

**Comment by 149alexniu149** [comment]
#dibs

**Comment by Jsgoller1** [comment]
New to Docker and Golang here- mind if I claim this issue?

**Comment by Jsgoller1** [comment]
#dibs

**Comment by Jsgoller1** [comment]
@thaJeztah not to rush or anything (new contributor here, and I realize it's the weekend), but the contributing docs say that @GordonTheTurtle should automatically mark this ticket as `claimed` once I comment with `#dibs` - is it safe to start working on this anyways?

**Comment by thaJeztah** [comment]
@Jsgoller1 sure, go ahead; looks like there's an issue with the bot doing that 😊 , let me set the label on its behalf

**Comment by Jsgoller1** [comment]
Thanks!

**Comment by karsinkk** [comment]
@Jsgoller1 @thaJeztah can I work on this?

**Comment by Jsgoller1** [comment]
@karsinkk Sure, consider this ticket yours now.

**Comment by karsinkk** [comment]
@Jsgoller1 Thanks, I'll start working on it right away.

**Comment by thaJeztah** [comment]
Should be fixed by https://github.com/moby/moby/pull/34485
