### ISSUE TITLE
Docker swarm from DAB file infinitely tries to pull an image. 

### ISSUE THREAD

**Issue by PaulKGray** [moby/moby#27318]
---
## BUG REPORT INFORMATION

**Description**

When you deploy a dab file to docker swarm with a reference to a docker image that does not exist, it does not stop trying to get the image. Docker logs each of these attempts until the dockerfile.log file fills the server.

**Steps to reproduce the issue:**
1. From a team city deployment script
2. Create a docker DAB file with an image repository that does exist and a tag that does not exist. 
3. Run the command "docker deploy --with-registry-auth --file environment..dab xxxxxx"
4. Load up the log and watch it grow "less /var/log/docker.log"

**Describe the results you received:**

The log file grows till the server is full, it does not give up trying to pull this image. 

**Describe the results you expected:**

Possibly try 10 times then give up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker log`:**

time="2016-10-12T14:09:55.208732899Z" level=error msg="Not continuing with pull after error: Tag develop not found in repository docker.io/xxxxxx/xxxxxqueueprocessor"
time="2016-10-12T14:09:55.208784224Z" level=error msg="pulling image failed" error="Tag develop not found in repository docker.io/xxxxxx/xxxxxqueueprocessor" module=taskmanager task.id=bikwjqdey83gt4gr3h6nmiu8n
time="2016-10-12T14:09:55.209408668Z" level=error msg="fatal task error" error="No such image: controlf1/cf1.charles.journeysummaryqueueprocessor:develop" module=taskmanager task.id=bikwjqdey83gt4gr3h6nmiu8n
... Lots more times 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS Docker swarm beta 5 and 6

**Comment by justincormack** [comment]
The idea is that the tag may exist in future, so it continues to try. This is the "desired state" model. You can update the service if you made a mistake.

I don't think the file will "fill the computer" though.

**Comment by PaulKGray** [comment]
The problem was that due to the AWS preview only having 20GB it did fill it. There may have been other logs contributing but this the example code was one of the main lines.

**Comment by justincormack** [comment]
How often is it retrying?

**Comment by PaulKGray** [comment]
On the environment I have now I recreated the issues for a while and it was trying to pull once every 3 or so seconds. I lost 2 managers to this issue and both were due to the log file being massive 7gb plus. When this happened on the aws beta we were not able to reload the daemon so I flattened these boxes.

**Comment by justincormack** [comment]
If it happens again (or to anyone else) a sample of the contents of the log would be useful to determine why it fills up so fast, as a pull every 2s would not fill up 7GB, there must have been something else.

**Comment by aluzzardi** [comment]
https://github.com/docker/swarmkit/issues/1201 would provide a way to slow down retries over time

**Comment by nathanleclaire** [comment]
Log with debug mode on, maybe.  I have been thinking about this and we need to ensure Docker logs at least are rotated over time...

**Comment by thaJeztah** [comment]
@nathanleclaire I ran into that, and IIRC on Ubuntu 14.04, log rotation (and limit) is off by default, whereas systemd actually had a sensible default to not fill up the disk

**Comment by PaulKGray** [comment]
After looking at this a bit more over the last two weeks removing the intial issue has prolonged the life of the machine, we still are using more disk space every day. Here are the sizes of the log files as you can see "service-port-opener.log" and  "docker.log" are getting huge. 

-rw-r-----    1 docker   docker           0 Oct 20 13:55 acpid.log
-rw-r--r--    1 root     root             0 Oct 20 13:56 cfn-init-cmd.log
-rw-r--r--    1 root     root           259 Oct 20 13:56 cfn-init.log
-rw-r--r--    1 root     root           765 Oct 20 13:56 cfn-wire.log
-rw-r--r--    1 root     root             0 Oct 20 13:56 containerd.log
-rw-r-----    1 docker   docker       27479 Oct 20 13:55 dmesg
-rw-r-----    1 docker   docker     3673233 Oct 27 08:35 docker.log
-rw-r-----    1 root     wheel        23992 Oct 27 12:14 messages
-rw-r-----    1 root     wheel       204828 Oct 27 08:35 messages.0
-rw-r--r--    1 root     root       8284783 Oct 27 08:35 service-port-opener.log
-rw-rw-r--    1 docker   docker           0 Oct 20 13:55 wtmp

**Comment by AkihiroSuda** [comment]
DAB was removed: https://github.com/docker/cli/pull/2216
