### ISSUE TITLE
Docker Swarm + --mount flag

### ISSUE THREAD

**Issue by saithala** [moby/moby#27321]
**Description**

I'm facing an issue with --mount flag. Im trying to create a service for Postgres SQL. For data persistence, I'm trying to mount the container directory to the host directory. The following are  the steps I took. What Im I doing wrong?
**Steps to reproduce the issue:**
1.  sudo docker service create --name database --mount type=bind,source=/opt/api-db/qa,destination=/var/lib/postgresql/data,readonly=false --with-registry-auth --network api  postgres:9.4 

**Describe the results you received:**
The service does not start up and I get the following error.
chmod: changing permissions of â/var/lib/postgresql/dataâ: Read-only file system

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-204175771-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 420.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 36.44 GB
 Metadata Space Used: 1.368 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: active
 NodeID: dmj47opflh4c3uxdnfej8h9px
 Is Manager: false
 Node Address: 10.1.2.59
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 47.01 GiB
Name: cmcmdmz104
ID: 2HX7:GUJN:2KP7:6YH4:ELOR:J6BZ:FBIL:FCHO:YDGY:B6WC:L3YB:MOY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cmcdocker
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by xiaods** [comment]
use docker volume?

**Comment by saithala** [comment]
@xiaods can i create a specific directory as a docker volume ? For ex. I want a specific directory on the host system (/opt/somepath)

**Comment by cpuguy83** [comment]
@saithala Sounds like a bug that using `readonly=false` would set readonly to true... but please try dropping the `readonly` flag, since it is false by default.

**Comment by saithala** [comment]
Thanks @cpuguy83 . The first time I tried it without readonly=false, since I read that its false by default. In both cases its the same result

**Comment by cpuguy83** [comment]
@saithala Are you sure the host path isn't flagged as read-only?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
