### ISSUE TITLE
Can't mount local directory to windows native docker instances

### ISSUE THREAD

**Issue by Shuliyey** [moby/moby#27340]
**Description**
mounting directories to windows native docker instances/contiainers doesn't seem to work.

so 

``` cmd
docker run -it -d -v <host_path>:<container_path> microsoft/windowsservercore
```

The host_path doesn't get mounted into the container

**Steps to reproduce the issue:**
1. You need to have a **Windows Server 2016** Environment (Either installed on bare metal/VM). I'm running a Windows Server 2016 in a VM. ISO can be downloaded at https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2016
2. Follow this instruction to install **windows native docker** on **Windows Server 2016**
3. _Recommended) You might need to have latest update applied after docker is installed, or else *_windows natvie docker*\* might not work
4. Open Powershell/CMD in **Administrator Mode**
5. Try creating a docker container/instance from the microsoft/windowsservercore docker image and try to mount some folder on the host to the docker container. For me I'm mounting a local **temp** folder (on the host) to the **C:\temp** folder (in the docker container)

``` cmd
docker run -it -d -v temp:C:\temp microsoft/windowsservercore
```
1. You have to use command prompt in **Administrator Mode** in order to hop into the container.

``` cmd
docker exec -it <container_name> powershell
```

**Describe the results you received:**
the C:\temp is not where to be found in the docker container/instance
**Describe the results you expected:**
The C:\temp path should be present and is a direct mount from the temp directory on the host

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens

**Output of `docker version`:**
To be completed

**Output of `docker info`:**

To be completed

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm doing this in a Virtual Machine running in Openstack

**Comment by johnstep** [comment]
Which version of Docker? Is the 'temp' directory in the container missing or empty? If empty, try passing a full (absolute) path for the host directory, something like this:

`docker run -it -d -v C:\source\temp:C:\temp microsoft/windowsservercore`

With a simple name such as 'temp', Docker creates a named volume, which it manages. You can get information about the named volume with 'docker volume ls' and 'docker volume inspect foo' (or 'docker inspect foo'). Please see the following for more information:

https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
