### ISSUE TITLE
Path error when trying to pull microsoft/windowsservercore on Windows native docker 1.13.0-dev

### ISSUE THREAD

**Issue by tormodhau** [moby/moby#27355]
Hi! 

I downloaded [microsoft/windodsservercore:latest](https://hub.docker.com/r/microsoft/windowsservercore/tags/) three weeks ago (TP5 i believe), and have been experimenting with it since. Due to consistent freezes, I decided to check for upgrades for Windows, the Docker Engine, and lastly the image.  However, if I try to pull any of the latest images, I only get the following error:

> .>docker pull microsoft/windowsservercore:latest
> latest: Pulling from microsoft/windowsservercore
> 9c7f9c7d9bc2: Already exists
> de5064718b3f: Extracting 
> 
> [==================================================>] 613.1 MB/613.1 MB
> failed to register layer: re-exec error: exit status 1: output: cloning the parent utility VM image failed: open \?\C:\ProgramData\Docker\windowsfilter\f4475eaee7106cc16ae7cb0d4e51c26901b635feae41406fc761c1beded34d27\UtilityVM\Files\Users\Administrator\AppData\Local\Application Data: The system cannot find the path specified.

The file path in the error exist, but I cannot access the "...\Application Data" directory even as an admin manually. 

Does anyone know what is going wrong here? I cannot seem to find any occurrences of this issue elsewhere. 

**Docker info:**

> .> docker info
> Containers: 3
>  Running: 0
>  Paused: 0
>  Stopped: 3
> Images: 5
> Server Version: 1.13.0-dev
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: nat null overlay
> Swarm: inactive
> Default Isolation: hyperv
> Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
> Operating System: Windows 10 Pro
> OSType: windows
> Architecture: x86_64
> CPUs: 4
> Total Memory: 15.7 GiB
> ID: CKXW:YMLA:ZZA3:G2TG:3SFA:FAFP:ISK7:RXOD:TXZ7:UW3J:UFZR:WOX3
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Docker version:**

> .> docker version
> Client:
>  Version:      1.13.0-dev
>  API version:  1.25
>  Go version:   go1.7.1
>  Git commit:   16a45db
>  Built:        Thu Oct  6 12:38:10 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.13.0-dev
>  API version:  1.25
>  Go version:   go1.7.1
>  Git commit:   16a45db
>  Built:        Thu Oct  6 12:38:10 2016
>  OS/Arch:      windows/amd64

**Comment by friism** [comment]
@tormodhau there might be a problem with the master build that you ended up with. Since you're on Windows 10, can you either try install the public channel version of Docker for Windows or grab a known-good Docker Engine build: https://download.docker.com/components/engine/windows-server/cs-1.12/docker-1.12.2.zip

Please also make sure you have all the latest Windows Updates.

**Comment by tormodhau** [comment]
@friism Downgrading docker to version 1.12.2 seemed to fix the issue (for now):

> .> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

> Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Thanks!

**Comment by thaJeztah** [comment]
Thanks @tormodhau; should we close this issue?

**Comment by tormodhau** [comment]
@thaJeztah I guess the issue is still there for 1.13.0-dev, and downgrading doesn't really fix that version.. I'm going to leave that decision up to you. :-)

**Comment by thaJeztah** [comment]
@friism do you know if the issue is still there on current master?

**Comment by thaJeztah** [comment]
Closing because this went stale
