### ISSUE TITLE
Named volumes don't work with services

### ISSUE THREAD

**Issue by adrahon** [moby/moby#27379]
**Description**

It seems that to have a different volume for each task in a service, you need to use anonymous volumes, which apparently only work with the local driver.
If you want named volumes, each task gets the same volume.

**Steps to reproduce the issue:**
Create a service with a named volume using a shared storage driver:

```
 docker service create  --name my-service  --replicas 3 \
  --mount type=volume,volume-driver=somedriver,source=my-volume,destination=/path/in/container \
  nginx:alpine
```

**Describe the results you received:**

The same volume with the same name is presented to all tasks

**Describe the results you expected:**

Volumes of with a recognisable name, but unique for each tasks, eg. "servicename.taskid" should be created.

**Comment by justincormack** [comment]
I think there was a discussion around templated resource names, I can't find it immediately.

**Comment by cpuguy83** [comment]
Services don't have volumes, they have mounts. Mounts happen to be able to be backed by a volume.
This is an intentional limitation that there are no orchestrated volumes (yet) in 1.12.

That said 1.12.2, IIRC, will allow mounts to use an anonymous volume even when a driver is specified.... this may only be in 1.13, I can't remember.

**Comment by adrahon** [comment]
We tried with 1.12.2 and anonymous volumes didn't work with a driver, but if it's in 1.13 that's enough for this use case and we can close the issue.

**Comment by justincormack** [comment]
See https://github.com/docker/swarmkit/pull/1650

**Comment by stevvooe** [comment]
@adrahon This is a limitation of the volume driver. It is completely up to the driver whether or not to mount the same thing for every mount or a different thing. The same thing is true of anonymous volumes. If the volume driver supports them, they should work.

We can probably template volume names, per docker/swarmkit#1650, but I am not sure if that is going to be a part of 1.13 or not.

It might be best to get a better idea of the errors encountered here. What is the actual error message you are seeing with the source-less volumes and with which driver?

**Comment by thaJeztah** [comment]
- closing, as https://github.com/moby/swarmkit/pull/1650 was merged, and support for CSI was added, but there may be more things to look into w.r.t. swarm and volumes
