### ISSUE TITLE
can we enable creating a pure data image? for pure data container

### ISSUE THREAD

**Issue by bchenSyd** [moby/moby#27450]
I know that in docker we can run data volume containers like this

```
#create a pure data container based on my data_image
docker run -v /data   --name data-volume-container   data-vol-container-img

# here I'm using the data volume in a property container (ubuntu)
docker run --volumes-from data-volume-container     ubuntu
```

my question is how do we create the data_image?

I know that the easiest way is to create a image based on ubuntu, or anything like that

```
From ubuntu
Copy data /data
CMD["true"]
```

But the thing is , why do I need ubuntu as my base image??? (I know it's not a big deal as ubuntu is going to re-used in other scenarios). I really want to know why can't I use scratch??

```
FROM scratch
COPY data /data
#I don't know what to put here
CMD ["???"]
```

The image i'm creating here is meant to be a dummy one, it execute absolutely NOTHING and only act a dummy data container, i.e to be used on in docker run -v /data --name my_dummy_data_container   my_dummy_data_image

any ideas??
(is it because scratch doesn't implement a bare minimum file system? but docker can use host system's file system if a container doesn't implement its own)

**Comment by bochen2014** [comment]
so far I've got this
```
FROM busybox
COPY data.json /data/
CMD ["true"]
``

in production, `data.json` is my compiled react project, i.e. bundle.js + index.html + css + woff + png
I just want to create a static file container, so that my nginx can use it;
I don't quite understand why I must create my static file image based upon ,, an operation system, even thought it's just a busybox

**Comment by thaJeztah** [comment]
If you're going to use it with nginx, why not add those files to the nginx container?

```Dockerfile
FROM nginx
COPY my-project /usr/share/nginx/html
```

If these are static files, there may not even be a need to use a volume.

Also note that docker now has top level commands for managing volumes (e.g. `docker volume create`), which in many cases make "data-only" containers redundant.

**Comment by thaJeztah** [comment]
If you still want to use a separate image for data-only, you could consider using https://hub.docker.com/r/tianon/true/, which is very minimal (but adding to nginx would be my first choice)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
