### ISSUE TITLE
#windows docker 1.13 dev transparent networking not working

### ISSUE THREAD

**Issue by ghost** [moby/moby#27529]
I have docker 1.13 dev version installed on Windows Server 2016 Datacenter Evaluation, I have created transparent network and connected to container with specific IP address 172.21.2.66, below is config of my transparent network:

[
    {
        "Name": "mynet",
        "Id": "d7e8fb2ff01d03e62bd579470688fa42eab55d81b7db790237cf86d7ea93e33a",
        "Scope": "local",
        "Driver": "transparent",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.21.2.0/23",
                    "Gateway": "172.21.2.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "f1a55c56d0a7464dc5af4a7b4a313a5d232745cf558d83144c6dfe23774c7fe1": {
                "Name": "jchen",
                "EndpointID": "0d2c67118ad4c1143a6b0a815ff7854d7be78a555fd5a8a73f579194e5e0c5b4",
                "MacAddress": "00:15:5d:a1:63:26",
                "IPv4Address": "172.21.2.66/23",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "fda768e5-1659-4dee-9a0e-f33e0fe321b1",
            "com.docker.network.windowsshim.networkname": "mynet"
        },

my understanding that transparent network is connect to my physical nic directly thus I am believe that container could be access through any windows ports; the docker container has been installed IIS server also nginx. but i cannot access it either IIS or nginx from docker host and external also I do see port is listening inside of container as below:
# **[container inside]**

PS C:> netstat -a
Active Connections
  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             jchen:0                LISTENING
  TCP    0.0.0.0:135            jchen:0                LISTENING
  TCP    0.0.0.0:5985           jchen:0                LISTENING
  TCP    0.0.0.0:8000           jchen:0                LISTENING
  TCP    0.0.0.0:47001          jchen:0                LISTENING
  TCP    0.0.0.0:49152          jchen:0                LISTENING
  TCP    0.0.0.0:49153          jchen:0                LISTENING
  TCP    0.0.0.0:49154          jchen:0                LISTENING
  TCP    0.0.0.0:49155          jchen:0                LISTENING
  TCP    0.0.0.0:49157          jchen:0                LISTENING
  TCP    172.21.2.66:80         jchen:49161            ESTABLISHED
  TCP    172.21.2.66:49161      jchen:http             ESTABLISHED
  TCP    [::]:80                jchen:0                LISTENING
  TCP    [::]:135               jchen:0                LISTENING
  TCP    [::]:5985              jchen:0                LISTENING
  TCP    [::]:8000              jchen:0                LISTENING
  TCP    [::]:47001             jchen:0                LISTENING
  TCP    [::]:49152             jchen:0                LISTENING
  TCP    [::]:49153             jchen:0                LISTENING
  TCP    [::]:49154             jchen:0                LISTENING
  TCP    [::]:49155             jchen:0                LISTENING
  TCP    [::]:49157             jchen:0                LISTENING
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5355           _:_
  UDP    [::]:5353              _:_
  UDP    [::]:5355              _:_

PS C:> Get-IISSite

Name             ID   State      Physical Path                  Bindings

---

Default Web Site 1    Started    %SystemDrive%\inetpub\wwwroot  http *:80:
Test             8712 Started    c:\site                        http *:8000:
                 0476
                 2

PS C:> ipconfig
Windows IP Configuration
Ethernet adapter vEthernet (Temp Nic Name):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::55bd:4f9e:5025:c81%34
   IPv4 Address. . . . . . . . . . . : 172.21.2.66
   Subnet Mask . . . . . . . . . . . : 255.255.254.0
   Default Gateway . . . . . . . . . : 172.21.2.1

PS C:> Invoke-WebRequest http://172.21.2.66 -UseBasicParsing

StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
                    <html xmlns="http://www.w3.org/1999/xhtml">
                    <head>
                    <meta http-equiv="Content-Type" cont...
RawContent        : HTTP/1.1 200 OK
                    Accept-Ranges: bytes
                    Content-Length: 703
                    Content-Type: text/html
                    Date: Wed, 19 Oct 2016 05:54:18 GMT
                    ETag: "1cc07f94b729d21:0"
                    Last-Modified: Wed, 19 Oct 2016 03:19:19 GMT
                    Serve...

here is my docker run command:
**docker run -itd --network=mynet --ip=172.21.2.66 --dns=8.8.8.8 --restart=always -h jchen --name jchen microsoft/windowsservercore powershell**

please let me know is anything i am missing out here.

**Comment by msabansal** [comment]
@5245010 Its likely that windows firewall is blocking the traffic. Try manually forwarding the port through the firewall and see if it works. We have a fix planned for this for the next release which will enable -p option for all the networks.

**Comment by 5245010** [comment]
but why NAT is working well without issue, both containers on same docker host. i have digged the network setting and found no MAC address assigned if the container connect to transparent network? do I need to manual assign Mac?

**Comment by msabansal** [comment]
@5245010 We only enabled port forwarding for nat. With NAT we forward the ports and unblock them in windows firewall. Port forwarding is not supported on other networks as windows doesn't have a mechanism to do this. As a result there is no mechanism to unblock ports in windows firewall on other networks. You will have to do it manually. We are thinking on how to enable it for other networks in future releases.

**Comment by 5245010** [comment]
thanks for your explain. i checked windows firewall service is stoped in docker container then may i know what is reason block the network traffic still? I did open firewall in my docker host however the traffic didn't pass by.

**Comment by bassebaba** [comment]
I am seeing the same issue. Firewall not activated in container but i can not connect.

I'm sooo dissapointed about Docker on Windows server 2016. Feels like an alpha. Important features are either broken or missing.

I have spent hours and hours on "troubleshooting", only to find out feature either missing or broken.

How am i supposed to host a website on a server in a container on windows docker when I cant even map an transparent IP + port in a container?!!!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
