### ISSUE TITLE
udp failed between docker containers

### ISSUE THREAD

**Issue by evagle** [moby/moby#27528]
**Description**
There are two machines running with docker: hostA and containerA, hostB and containerB
containerB exposes it's port 10050 with 'run -p 10050:10050/udp'.

**Steps to reproduce the issue:**
1. Run command "nc -u -l 10051" on hostB and  run "nc -u ip_of_hostB 10051" on hostA and containerA,  hostB can receive packets from both hostA and containerA.
2. Run command "nc -u -l 10050" on containerB,  run "nc -u ip_of_hostB 10050" on hostA and containerA, containerB can only receive packets from hostA

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```
(paste your output here)
```

**Output of `docker info`:**
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: PP-Test-Server
ID: LYB3:5VAF:DZVS:ADZV:VOXX:A2WT:RNUN:6OC3:OQFH:VF2J:Y7XX:HIH4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
Does it help if you specify the listen address as `0.0.0.0` in the container that is listening? The docs says that `nc` listens on `127.0.0.1` otherwise.

**Comment by evagle** [comment]
No, it's still the same result.
