### ISSUE TITLE
Docker user namespacing map user in container to specific user in host

### ISSUE THREAD

**Issue by kidambisrinivas** [moby/moby#27548]
I'd like to map user postgres or root inside container to user myuser on the host. There's a lot of references to this online, but it is not very clear to me how to achieve the following:

Is there a simple way to map arbitrary user inside container to user in host by a simple command line flag at the docker-run level

**Map root user inside container to myuser on host**

```
docker run --user-remap "mysuser:root" -p 6379:6379 redis:alpine
```

and

**Map postgres inside container to myuser on host**

```
docker run -it -p 5431:5432 --user-remap "myuser:postgres" --rm -v /home/myuser/data:/var/lib/postgresql/data postgres:9.6.0
```

I do not want to apply the same settings to all my containers. So doing this at the docker daemon level by applying

```
sudo docker daemon --userns-remap myuser
```

and updating /etc/passwd, /etc/group, /etc/subuid, /etc/subgid would not help solve my problem. Is there a way to solve this problem at the docker run stage, so that these settings can be applied on a container by container basis.

This problem has been referenced [here](http://stackoverflow.com/questions/35291520/docker-and-userns-remap-how-to-manage-volume-permissions-to-share-data-betwee) in this stackoverflow thread. However, for my use case the user inside the container could change from application to application (user:postgres for postgres image, user:influx for influx image and so on). 

It'll be really good if I could specify on a **container by container** basis during **docker run** time  

```
User A inside container --> to --> User B in host
```

This particular variant does not seem to be referenced in other issues.

Thanks

**Comment by koflerdavid** [comment]
Hi,
I know your pain. Correctly using `userns` is quite tricky.

According to [this blogpost](https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/) it is possible with Docker to add multiple mappings. 
Maybe you can play a bit with these.
Important: no more than five entries are currently supported on the Linux kernel.

There are two ways to approach this:
 1. If you just want `root` to be equal to your account, use the following entries in `/etc/subuid`.
    For the other container users the usual remapping is done.
    ````
    you:1000:1
    you:10000:65536
    ````
 2. If the images are your own you could assign all interesting service users (`postgres`, `mysql`) the same user ID, say, `930`.
    You can then use a line similar to the above one to map that UID to your host user's UID:
    ````
    you:100000:929
    you:1000:1
    you:100930:65536````

Please let me know what happens!

**Comment by karlgrz** [comment]
I am finding myself wanting to set a particular userns at container run time instead of the daemon. For example, I have two containers running on a host that both have volumes they are writing to with data. I'd like both of these containers to be locked down in terms of file access, with different users for each. In the current state of the world, I have to add a single user as the userns-remap setting in /etc/docker/daemon.json which makes that impossible. Am I wrong in that assumption?

**Comment by koflerdavid** [comment]
You could try using the `--userns` argument of `docker run` where you specify which user namespace to use.

**Comment by karlgrz** [comment]
@koflerdavid that doesn't work for anything other than `host`. I can only specify a user in the daemon.json file.

I resolved this by making sure my user and group id's were within the range of the `dockremap` namespace configured in `/etc/subuid` and `/etc/subgid`. Seems live a bug to me.

**Comment by thaJeztah** [comment]
Per-container mappings are currently not supported, and a known limitation of user namespaces. Supporting this requires changes in the kernel (shiftfs, among others). Future enhancements to user namespaces in Docker/Moby are currently tracked through https://github.com/moby/moby/issues/28593.

I'm closing this issue to prevent the discussion from diverging; feel free to continue the conversation in https://github.com/moby/moby/issues/28593
