### ISSUE TITLE
Add option to splunk log driver to match environment variables by a regex.

### ISSUE THREAD

**Issue by rothrock** [moby/moby#27561]
**Description**
Currently the splunk log driver will include as attributes the environment variables that match the ones named in the <code>--env</code> flag passed as part of <code>--log-opts</code> when starting the Docker daemon. For example, supplying <code>--env="APP_VAR_1,APP_VAR2"</code> will inspire the driver to attach the environment variables that have names that exactly match APP_VAR1 and APP_VAR2. 

I would like to be have an additional option <code>--splunk-env-regex="" </code> to specify a regex to match environment variable names instead. 
So, supplying <code>--splunk-env-regex="^APP_" </code> would match APP_VAR1 and APP_VAR2

29-November-2016 - update
In response to comments from @cpuguy83 and @outcoldman I have generalized the functionality to all log drivers. The flag is <code> --env-regex</code>

**Comment by outcoldman** [comment]
That is good idea, but my guess it should be implemented not on the level of Splunk Logging Driver, but on level of all logging drivers, so actually a --log-opt should support it.

**Comment by rothrock** [comment]
Thanks @outcoldman for looking at this. @cpuguy83 made the same suggestion. The open PR implements the enhancement on all logging drivers.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/27565 was merged for 17.05, so looks like we can close this one 👍
