### ISSUE TITLE
Releases unbuildable because of unset `DOCKER_GITCOMMIT`

### ISSUE THREAD

**Issue by paulmenzel** [moby/moby#27581]
**Description**

Docker 1.12.1 and 1.12.2 (and probably before), cannot be built from the [published release tarballs]().

It might be related to issue #25116, but this turned into a different discussion.

**Steps to reproduce the issue:**
1. Download the [source tarball](https://github.com/docker/docker/archive/v1.12.2.tar.gz)
2. Unpack and run `make build`, `make binary`.

**Describe the results you received:**

```
[…]
Step 50 : COPY . /go/src/github.com/docker/docker
 ---> Using cache
 ---> 6dddad44e4e4
Successfully built 6dddad44e4e4
docker run --rm -i --privileged -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER=overlay -e DOCKER_INCREMENTAL_BINARY -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -v "/dev/shm/bee-root/docker/docker-1.12.2-0/source/bundles:/go/src/github.com/docker/docker/bundles" -t "docker-dev" hack/make.sh binary

error: .git directory missing and DOCKER_GITCOMMIT not specified
  Please either build with the .git directory accessible, or specify the
  exact (--short) commit hash you are building using DOCKER_GITCOMMIT for
  future accountability in diagnosing build issues.  Thanks!
Makefile:65: recipe for target 'binary' failed
make: *** [binary] Error 1
```

**Describe the results you expected:**

A successful built after `make binary`.

**Comment by justincormack** [comment]
Hmm yes that is a bit annoying. Obviously you can specify the hashes but it should be automated. I guess we should create a file with the commit info in it which the build also checks for, and put that in the archive.

**Comment by paulmenzel** [comment]
Yes, that’s what I did. I also corrected my original report to document, that `make binary` fails.

```
$ make DOCKER_GITCOMMIT=bb80604 binary
```

… builds correctly.

**Comment by paulmenzel** [comment]
For people with build scripts, as a workaround just use the tag of the commit, and not the commit hash.

For the [bee package manager](http://www.beezinga.org/) (bee file):

```
mee_build() {
    start_cmd make build
    start_cmd make DOCKER_GITCOMMIT=${PKGVERSION} binary
}
```

**Comment by rootsongjc** [comment]
+1

**Comment by vdemeester** [comment]
I'm pretty sure this is fixed in 1.13 even 👼

**Comment by rootsongjc** [comment]
@vdemeester I encountered this problem just now.

**Comment by vdemeester** [comment]
@rootsongjc if you're building `docker/docker` from that tar/zip downloaded from the releases, then there is no `.git` folder and you need to specify `DOCKER_COMMIT` by hand. Otherwise (from git), the `Makefile` should take care of getting the right commit.

**Comment by rootsongjc** [comment]
@vdemeester I fork docker to my own repo and then pull it onto my own laptop. I can see the ``.git`` folder but not visible on the dockercore/docker container. Sure, specify ``DOCKER_GITCOMIIT`` works, but it is inconvenient.

**Comment by paulmenzel** [comment]
@vdemeester, why do you think it’s fixed. I just tried it, and I get the same error.

Sorry for being harsh, but before closing an issue, please read what the report is actually about.

**Comment by vdemeester** [comment]
@paulmenzel I re-opened it though 👼 
@rootsongjc yeah, it's removed from the build context (see `.dockerignore`). `make` does get the correct commit though before building. If you're using a git fork you don't need to use `dockercore/docker` image, `make` commands will build the image and run everything in a container.

The only "official" way to build docker is doing `make binary` from a git repository. I didn't even know we published `dockercore/docker` images 😅. I don't really see anything to do here, except maybe provide a way to specify the image to use to build instead of building it locally through a variable but…

**Comment by rootsongjc** [comment]
@vdemeester I think use ``dockercore/docker`` image is a good way to build docker in China, because the softwares defined on **Dockerfile** are not reachable in China. But pull the docker image is convenient because the we have [accelerator](aliyun.com).

**Comment by paulmenzel** [comment]
> The only "official" way to build docker is doing make binary from a git repository.

Then please don’t publish release archives in GitHub.

**Comment by vdemeester** [comment]
@paulmenzel as far as I know, it's automatic on github when you tag/do a release, it include source code archive automatically, maybe we could remove them but pretty sure we shouldn't as some packager use it (NixOS for example). With github you can literaly get a source code archive from any commit, there is nothing we can do about it, it's a github feature.

**Comment by thaJeztah** [comment]
I just tried this by downloading a `.zip` from current master, and this looks to be working now. Note that it _works_ (i.e., builds successfully), but the `dockerd --version` output is not very useful without specifying the values to use;

```
Docker version dev, build unsupported
```

`DOCKER_GITCOMMIT` defaults to `unsupported`; https://github.com/moby/moby/blob/c057825cf56850ffb97cae532d0bfa261b4b9a53/Makefile#L26

Closing this issue as the failing build was resolved, but feel free to continue the conversation
