### ISSUE TITLE
Proxy with self signed cert causing hosts to not be found?

### ISSUE THREAD

**Issue by deanpeterson** [moby/moby#27591]
I am behind a proxy server with a self signed certificate. I am able to reach docker.io/hub to fetch the latest centos image, but all other hosts seem to be unreachable. I had to set the proxy settings in /etc/sysconfig/docker and drop in the docker.io certificate chain downloaded from the browser into the docker certificate folder to even get that to work. Has anyone heard of this behavior, where all hosts are inaccessible because a proxy server has a self signed certificate? Again, I have set the proxy settings in /etc/sysconfig/docker. I still was unable to reach docker.io to do a docker pull centos until I dropped in the downloaded certificate files to docker.io from a browser to the docker certificate folder. Everything looked fine until I tried doing a build that did a curl statement trying to reach pkg.jenkins-ci.org. That host and it seems all other hosts are unreachable. What can cause this? I have attached an image of a simple "docker build ." with the Dockerfile in the current directory.

![buildjenkins](https://cloud.githubusercontent.com/assets/1156788/19570793/770a00c2-96c9-11e6-8a1e-0f920fafb496.png)

Redhat 7.2 on a virtual machine inside a private network using a proxy with a self signed certificate.

**Comment by deanpeterson** [comment]
Unfortunately I have tried every combination of putting the proxy settings in the container and Dockerfile as well. I did try: docker build --build-arg HTTP_PROXY="username:password@proxy.ourproxy.rtg:9090"; --build-arg HTTPS_PROXY="password:username@proxy.ourproxy.rtg:9090"; . and I get the same timeout.

**Comment by thaJeztah** [comment]
Can you add the output of `docker info` and `docker version`? Based on the mention of `/etc/sysconfig/docker`, I suspect you're running the Red Hat fork of Docker. For the official packages, setting up a proxy can be done through systemd drop in files; https://docs.docker.com/engine/admin/systemd/#/http-proxy

However, I'm not sure that's sufficient if you're behind a MITM proxy, also, it may be deliberately blocking access? Some information can be found in this issue https://github.com/docker/docker/issues/3203

**Comment by justincormack** [comment]
Looks to me like there may be an issue with your proxy config, but it is a bit unclear. If you are MITM https as well you will need to trust the CA as well.

**Comment by deanpeterson** [comment]
Is this possibly the problem/ correct assessment?
The containers being run cannot resolve internal network hosts. The proxy server sits at a specific internal host/ip (only seen on the internal network). Docker creates containers on its own subnetwork. The containers on the Docker/Kubernetes network cannot see the proxy server host sitting at a specific internal host url/ip because of the subnetwork not being part of the internal network. So, even though we can specify a proxy, that proxy sits on an internal network the containers have no access to (they are on their own subnetwork). There is a command line option (--net=host), that allows runnable containers to use the network of the host computer. That is only an option for running pre-built containers Ex. "run -it --net=host <containerid>". Then if we specify the http_proxy, that container can it. Openshift and Kubernetes do not support that command. Their internal subnetwork overlays are even more complex. Also, --net=host is not an option for "docker build" commands.  See this request with many people screaming for the option (the last +1 was 8 days ago):  

https://github.com/docker/docker/issues/10324

In another github issue similar to what we face (docker daemon without internet access), a Docker contributor offers this advice: 
There is currently no way to specify custom networks for build, see #10324 (That is the same link above). I would recommend using a separate build machine and a registry, that is a good solution for builds anyway." - https://github.com/docker/docker/issues/22064

He means a separate build machine and registry with internet access. 

From what I am seeing, to make the proxy work, it should also be running in a pod, and other pods should communicate with it inside normal Openshift channels. I know that is not an option.

 It was just bothering me why I could not figure out why containers could not see external hosts in the build (not even the proxy host). We could get to docker.io because the "from centos:7" command in the Dockerfile triggers a pull that happens external to the container. Curl commands and other basic networked "RUN" commands use the internal container network. Since we can't see the proxy host, we can't get to the outside world.

I can foresee this being a problem for running containers in the future if they need to access the internet for whatever reason. Right now, the only option I see is to add a node to the openshift cluster that has internet access, run the proxy on that node and make all the pods/containers in the openshift cluster point to that proxy.

-Dean

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
