### ISSUE TITLE
Set "always used build arg" in the (daemon) configuration file

### ISSUE THREAD

**Issue by davvdg** [moby/moby#27605]
I'm tired to have to set the http_proxy through build arg everytime I run a build. We should be able to set environment variables that are specific to our local build scenario but generic enough to be used all the time (and of course, should not be in the dockerfile) in a configuration file.

**Comment by thaJeztah** [comment]
I think the proxy case is solved through;

- https://github.com/docker/cli/pull/93

There's no plans for a daemon configuration to object build args afaik, so let me close this one
