### ISSUE TITLE
/proc/partitions within container not as expected, between feature request and bug

### ISSUE THREAD

**Issue by suppeee** [moby/moby#27641]
Hello,

i use the docker run command with the --device option to pass loop devices to the container as block devices. the device option allows to rename device names; the devices appear within the container with its changed names.

However, the device names in /proc/partitions are not changed. I have not found a way yet to fake the file /prov/partitions so it goes along with the changed devicenames.

i.e. docker run --device=/dev/loop0:/dev/sda1
creates a device /dev/sda1 within the container which is linked to /dev/loop0 outside the container, /proc/partitions however still shows the old device names.

My container app checks the names in /proc/partitions and fails to work correctly.

Is there a way to allow bind mounts for /proc/partitions? 

I read on the internet, that bind mounts were possible for some old versions of docker, but the functionality was changed at some point.

Thanks for your help!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
