### ISSUE TITLE
docker-pull return codes

### ISSUE THREAD

**Issue by neilhwatson** [moby/moby#27658]
docker pull <image> should return different status based on if the image is present and up to date, a newer image is pulled, or the image is missing and pulled.

**Comment by thaJeztah** [comment]
Can you describe your use case? Also, what kind of status codes would you expect?

**Comment by neilhwatson** [comment]
If an automated program is using docker-pull, docker-pull's return code will allow the calling program to know the results of the pull.

**Comment by thaJeztah** [comment]
but there's two outcomes;

- the pull succeeded. the image is now present and up to date
- the pull failed

**Comment by KristofErr** [comment]
Hi,

We could probably use this feature, for example for:

- reporting: telling the users/admins what's going wrong without parsing the log file: is the docker registry down? Or maybe the image doesn't exists? Is there a wrong invocation of the command? Etc.
- retrying: if the image doesn't exist there is no point in retrying but if the registry/network was just down there is!

**Comment by thaJeztah** [comment]
>  is the docker registry down? Or maybe the image doesn't exists?

If you're using the API, both will return a 404. But be aware that an existing image that you don't have permissions for also returns a 404.

>  Is there a wrong invocation of the command? Etc.

The API returns a 500 error if the tag/image is in an invalid format


However for the CLI, the error-messages should generally give enough information to the user what the reason is;

Private or non-existing image

```
docker pull thajeztah/private-test-image
Using default tag: latest
Error response from daemon: repository thajeztah/private-test-image not found: does not exist or no pull access
```

Invalid format;

```
docker pull a##b
Error parsing reference: "a##b" is not a valid repository/tag: invalid reference format
```

Non existing host;

```
docker pull registry.example.com:5000/one/two:latest
Error response from daemon: Get https://registry.example.com:5000/v1/_ping: dial tcp: lookup registry.example.com on 192.168.65.1:53: no such host
```

Not a registry / not listening on the specified port;

```
docker pull www.docker.com:5000/one/two:latest
Error response from daemon: Get https://www.docker.com:5000/v1/_ping: dial tcp 104.239.220.248:5000: getsockopt: connection refused
```

**Comment by KristofErr** [comment]
Well, our use case is the following: 

We automatically create a cluster with cloudformation and fleet. The fleet unit files have the docker pulls, something like this:
ExecPreStart="docker pull ..."

I don't argue that we should never submit a template with an invalid docker version but currently it happens(the version comes from the user). True we can probably fix that but it maybe would be still useful to have code in the template which can terminate the whole unit if it's unrecoverable or keep retrying if not. 

But probably it's not a huge issue, we can work around it, and it probably better to do that anyway...

**Comment by thaJeztah** [comment]
Are there standard exit codes that would allow "translating" API (HTTP) error codes to CLI exit codes that would make this more logical? A proposal with exit codes would help in the decision if this is something that could be implemented.

**Comment by DenerKup** [comment]
We are using `docker pull` in automated deployment. And in case of login failure (automation error: forget to use `docker login`) we can't detect it by exit code. Can you at least make `docker pull` return non-zero code (3 [for example](http://tldp.org/LDP/abs/html/exitcodes.html)) when pull failed? I think this will cover most of the cases.  After that we can think on better codes for other cases.

**Comment by ripcurld0** [comment]
I am closing this as this should be opened in docker/cli

**Comment by gregmartyn** [comment]
If an issue was created in docker/cli, could someone please point me to it? I can't find it. Thanks.

**Comment by ripcurld0** [comment]
Sorry, I will open an issue there and put a link here.

**Comment by ripcurld0** [comment]
@gregmartyn https://github.com/docker/cli/issues/538

**Comment by geraldstanje** [comment]
hi sorry for re-opening the discussion. does docker pull return an error code in the following case?

```
Pulling from  xxxxxxxxxxx
9f0706ba7422: Retrying in 1 second 
d3942a742d22: Retrying in 1 second 
2b95a7bc6bf9: Downloading [==================================================>] 243.1 kB/243.1 kB
e4c7597bbbc1: Waiting 
5f5ed4ce77dc: Waiting 
63038208f189: Waiting 
1138b1f02201: Waiting 
f027013454f1: Waiting 
41cf8eaed89c: Waiting 
08038cdd003c: Waiting 
d4afc280bba7: Waiting 
a0416d3a601b: Waiting 
173941a1f6c9: Waiting 
unexpected EOF
```

what is the error code for ```$ echo $?```

Docker version 18.09.9, build 039a7df9ba
