### ISSUE TITLE
Sharing windows host SSH key with a docker container resolve in a "Permissions are too open" error.

### ISSUE THREAD

**Issue by JnMik** [moby/moby#27685]
Hey guys ! 

We're having issues with Docker on windows that we don't have on Linux.

Mounting the host (windows 10) ssh key into the container via volume makes the permissions over 600 and using composer install resolve in an ssh error "SSH keys are too open" when installing private repositories.

Probaly some kind of NTFS / linux problem or something..

We tried with the SSH_AGENT_SOCKS as well without success.

I've even tried using cygwin to changes permissions on the host but it did not work, and it's clearly not an acceptable solution for me even if it would have worked as it implies way too much overhead.

Any one had success doing this ? 
thanks ! 

EDIT: thread moved https://github.com/docker/for-win/issues/167

**Comment by thaJeztah** [comment]
Can you reopen this in the Docker for Windows issue tracker? This is specific to docker for Windows, so best reported there https://github.com/docker/for-win/issues

**Comment by justincormack** [comment]
I don't think this is specific to Docker for Windows, it is due to the mismatch between Windows and Linux permissions models.

I would try creating a named volume and syning the credentials to that to see if it is easier to fix the permissions.

Maybe @jhowardmsft has an idea?

See also https://github.com/docker/for-win/issues/167

**Comment by jhowardmsft** [comment]
Not entirely sure what the issue is here trying to break it down to the lowest level, but suspect I know what's going on. It sounds like you have a cygwin generated cert on the host and are trying to use it in some way in a container.

Is this a Hyper-V container or a Windows Server container? As volume mapping permissions behaves differently - one is a shared kernel, one is isolated in a utility VM.  And is the error coming from SSH running in a container? I honestly have no idea though how cygwin applies its permissions in terms of NTFS semantics, if indeed it does at all (I suspect it doesn't, and stores them external in some way to NTFS). 

How can I repro this with a simple docker run outside of compose/d4w etc? Maybe that would help narrow something down to something that may be able to be improved in the platform in a future version of Windows.

**Comment by JnMik** [comment]
Hey @jhowardmsft ! First, thx for the help ! 

So let's make a basic reproduction scenario here :

- Forget about cygwin, that was just a test I run. Hopefully it will not be part of the solution
- Install docker for windows, make sure your c: is shared in the settings.
- You need a simple image with PHP able to install dependencies from composer.json pointing to a private repository (github or bitbucket)
- docker run -v /your/windows/ssh/path:~/.ssh your-project-name -ti bash  (enter the container here)
- try composer install here and it should fail (inside the container)

"Composer install" command will try to use the ssh key to access the private repository, but as the ssh key permissions  is over 600, it will exit with error "Permissions are too open".

Tell me if it's clear enough :)

**Comment by jhowardmsft** [comment]
So to be clear this is pointing at a Windows or Linux daemon?

**Comment by JnMik** [comment]
I'm not sure I understand the question 

The key is hosted on windows 10, but it is used inside the docker container (via volume).
My container runs on centos7 and PHP is installed.
The container is  simply run on the host, where "Docker for Windows" is installed.

**Comment by jhowardmsft** [comment]
Yes, exactly that. It sounds like the container is running on a linux daemon. Can you confirm by docker version?

**Comment by JnMik** [comment]
Hmm I'm not at home right now (at the office), but I've installed the stable channel like 1 week ago.
And my collegue who's having the same issue he's runing on the beta channel (installed last friday)

![image](https://cloud.githubusercontent.com/assets/4965516/19660694/d5310fa0-99fe-11e6-8804-b119960bae53.png)

**Comment by jhowardmsft** [comment]
I think the default is Linux based on your comment `My container runs on centos7 and PHP is installed.`. Getting an answer to what the daemon is is going to be able to point this in the right direction (or at least rule out the Windows daemon which is where I have the most knowledge)

**Comment by coolfarmer** [comment]
I confirm having the issue on the Linux daemon _(I'm the collegue who have the Beta)_

**Comment by jhowardmsft** [comment]
@justincormack In which case on account of above, it sounds kind of exactly the same as https://github.com/docker/docker/blob/master/cli/command/image/build.go#L333 during a `build` from a Windows client to a Linux daemon. I've no idea how D4W does "drive sharing" though in terms of 'raw' docker CLI commands.

**Comment by JnMik** [comment]
Are you saying running "Docker for windows" on Windows daemon would fix all our SSH issues ?

**Comment by jhowardmsft** [comment]
No, that's not what I'm saying at all. You obviously can't run centos7 on a Windows daemon regardless - Windows daemons can only run Windows...

**Comment by justincormack** [comment]
@jhowardmsft It is a CIFS mount from Linux to the host, then it bind mounts like a normal Linux daemon would. So the issue is going to be that a CIFS mount from Linux to Windows is not going to have the right Unix permissions.

**Comment by jhowardmsft** [comment]
Ah, I see. I'm not sure this is fixable in that case - it's something way outside docker engine. Maybe a workaround would be to cp the files inside the container and chmod/chown as necessary to get the right perms?

**Comment by JnMik** [comment]
I think that makes it difficult for users to use docker on windows without hassle.
And new users might even just drop it because they just don't get how to make things work.

It's very common for developers to have private repository, and running the dependency manager inside the container is the right way to go because most of DM validates your have the right technos in place before pulling the dependencies (Like composer verify your php version etc). 

I wonder what could be put in place to work around this and keep things easy !

**Comment by friism** [comment]
@JnMik probably the way to go is to use GitHub tokens and pass them in as build args during `docker build`: https://docs.docker.com/engine/reference/commandline/build/#/set-build-time-variables---build-arg

**Comment by coolfarmer** [comment]
@friism , true for Github, we can use Oauth token, but for BitBucket (correct me if i'm wrong) it's impossible to use this functionality with Composer.

Ref: https://github.com/composer/composer/issues/4398

**Comment by JnMik** [comment]
@friism  Thanks for your reply

My reflexion on this is, if the build time variables are dismiss after docker build, it prevents us to go inside the container to refresh our dependencies (composer update / composer install etc). 

We will be forced to rebuild the whole image to refresh our dependencies. 

I don't think it's optimal, but we're getting closer.

**Comment by justincormack** [comment]
Not sure it is, I think it is a general permissions mapping issue. As
Windows does not understand Unix permissions it does not map them.

I would recommend creating a Linux volume for your keys and syncing them,
and then adjusting the permissions, I think this should work.

**Comment by JnMik** [comment]
This could work,  I will try this.

But still, we gotta admit  this will still be painful to do. Unallocate disk space, create a new partition ext, copy ssh key, adjust permissions, mount them in the volume and hope for everything works.

I hope for something easier in the docker future.

**Comment by JnMik** [comment]
I've bump an idea in https://github.com/docker/for-win/issues/167
Not sure this is the right way to go, but it would definitely make things easier ?

**Comment by JnMik** [comment]
Actually, one of our collegue found this in authfile.c

`
sshkey_perm_ok(int fd, const char *filename)
{
 struct stat st;

 if (fstat(fd, &st) < 0)
  return SSH_ERR_SYSTEM_ERROR;
 /*
  * if a key owned by the user is accessed, then we check the
  * permissions of the file. if the key owned by a different user,
  * then we don't care.
  */
#ifdef HAVE_CYGWIN
 if (check_ntsec(filename))
#endif
 if ((st.st_uid == getuid()) && (st.st_mode & 077) != 0) {
  error("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
  error("@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @");
  error("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
  error("Permissions 0%3.3o for '%s' are too open.",
      (u_int)st.st_mode & 0777, filename);
  error("It is required that your private key files are NOT accessible by others.");
  error("This private key will be ignored.");
  return SSH_ERR_KEY_BAD_PERMISSIONS;
 }
 return 0;
}
`

So it might just work if the ssh key is mounted as ROOT, and we switch the user in the Dockerfile 
for a non-ROOT user. The condition will skill all the validation.

I know one shall not run a container as ROOT, just didn't make the switch yet, but if it solves our SHH problem I'll do it right away lol

**Comment by ebuildy** [comment]
Hey guys, what about specifying an user when running the container :

```
➜  docker run -v $(pwd)/README.md:/toto/README.md debian:8 ls -alh /toto
total 12K
drwxr-xr-x 2 root root 4.0K Jan 24 08:08 .
drwxr-xr-x 1 root root 4.0K Jan 24 08:08 ..
-rw-r--r-- 1 root root 1.6K Jan 23 18:39 README.md

➜  docker run -v $(pwd)/README.md:/toto/README.md --user www-data debian:8 ls -alh /toto
total 12K
drwxr-xr-x 2 root     root     4.0K Jan 24 08:08 .
drwxr-xr-x 1 root     root     4.0K Jan 24 08:08 ..
-rw-r--r-- 1 www-data www-data 1.6K Jan 23 18:39 README.md
```

Or, you can change the ownership with a custom entrypoint, or with a clean base image such as https://github.com/phusion/baseimage-docker#running-scripts-during-container-startup.

**Comment by JnMik** [comment]
I didn't know we could overwrite the user on run-time. Interesting.
I still haven't try to change the user in my dockerfile like I said in my previous comment tho, but I'm pretty sure it's gonna work.
I  switched on my linux laptop to finish the work and never came back to the problem lol.

I might give it a try soon just to be able to close the issue xD

**Comment by JnMik** [comment]
It's working by the way, as long as the User is not root.

Sorry we took that long to reply !

**Comment by benbou8231** [comment]
I had the same issue, root or not.

[sjpilot](https://github.com/sjpilot)'s comment worked perfectly to workaround the issue [https://github.com/docker/for-win/issues/167#issuecomment-585103167](https://github.com/docker/for-win/issues/167#issuecomment-585103167)

I ended adding this line in my Dockerfile:
`ENTRYPOINT eval `ssh-agent` ; cat ~/.ssh/id_rsa | ssh-add -k - ; /bin/sh`
