### ISSUE TITLE
Swarm. Consul. Docker Upgrade. Address already in use.

### ISSUE THREAD

**Issue by westsouthnight** [moby/moby#27681]
---
## BUG REPORT INFORMATION

I have troubles when update docker to latest version.

Some containers on Docker Node (~50% of all connected to swarm network) not start after restart docker service.

I got error - Error response from daemon: 

`Cannot restart container cc8543c658dc: Address already in use.`

Then i try to disconnect container from network

`docker network disconnect swarm-production production-logging-storage-12`

after then

`docker network connect --ip 10.21.2.4 swarm-production cc8543c658dc`

and again got

`Error response from daemon: Address already in use`

**Describe the results you received:**

Not started containers connected to swarm network

**Describe the results you expected:**

Started containers connected to swarm network

**Additional information you deem important (e.g. issue happens only occasionally):**

Consul: 0.6.4
Swarm: swarm version 1.2.3 (eaa53c7)

**Output of `docker version`:**

Before: Docker version 1.11.0, build 4dc5990
Current: Docker version 1.12.2, build bb80604

Before:

```
Containers: 14
 Running: 12
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 159
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 125.8 GiB
Name: 12-node
ID: DDRZ:VXBT:MP3Y:NE3Q:GXFP:NAQB:A6HK:JIYQ:6JZY:AUMX:YBXD:VXGL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: devevote
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://192.168.0.237:8500
Cluster advertise: 192.168.0.237:2375
```

After:

```
Containers: 14
 Running: 9
 Paused: 0
 Stopped: 5
Images: 8
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 113
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 125.8 GiB
Name: 12-node
ID: DDRZ:VXBT:MP3Y:NE3Q:GXFP:NAQB:A6HK:JIYQ:6JZY:AUMX:YBXD:VXGL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: devevote
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://192.168.0.237:8500
Cluster advertise: 192.168.0.237:2375
Insecure Registries:
 127.0.0.0/8
```

**Comment by westsouthnight** [comment]
And how have one strange situation. We have network, which work between old (host which i not upgrade yet), but in network inspect i no see anything...

```
docker network inspect swarm-develop
[
    {
        "Name": "swarm-develop",
        "Id": "01745c14f3fd4c6bcbcb2e1c7d3264d1cfc53c0ca3524ac8e11072896af5a2eb",
        "Scope": "global",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.31.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]


```


```
/opt/servicecontainer # ping 10.31.200.2
PING 10.31.200.2 (10.31.200.2): 56 data bytes
64 bytes from 10.31.200.2: seq=0 ttl=64 time=0.407 ms
^C
--- 10.31.200.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.407/0.407/0.407 ms
/opt/servicecontainer # ping 10.31.200.1
PING 10.31.200.1 (10.31.200.1): 56 data bytes
64 bytes from 10.31.200.1: seq=0 ttl=64 time=0.058 ms
^C
--- 10.31.200.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.058/0.058/0.058 ms
/opt/servicecontainer # 

```

**Comment by westsouthnight** [comment]
How to convert IP address to consul k/v hash?

I don't want to recreate all network,

We need simple way to force connect to swarm or removing broken IPs.

![screen_shot_2016-10-24_at_14_39_24](https://cloud.githubusercontent.com/assets/17825649/19644339/c617414e-99f7-11e6-9afb-c09943ba1d06.png)

**Comment by aboch** [comment]
Not sure what happened, but one reason could be that an address release did not happen properly   for for some network endpoints on the `swarm-develop` network, during an ungraceful shutdown (this can in fact only happen for k/v store based overlay networks) during the upgrade.

A workaround would be to delete and recreate the `swarm-develop` network only.

**Comment by westsouthnight** [comment]
@aboch In practice work, if we have work application with services, (100+ services on 20+ nodes), In future major/minor upgrades Docker Engine or Swarm/Consul components can damage some containers and networks, - from that as expected we get one thing = we need some way for repair or remove old ip from k/v. I no see other ways. Recreate all network its may be very very big problem for production network/services/application in mission critical systems.

**Comment by westsouthnight** [comment]
@aboch May be we can do procedure or swarm docker param which can real check about used and attached IPs in K/V to real containers in Swarm, and if containers on exists which matched to IP remove that IP from K/V.

**Comment by aboch** [comment]
@westsouthnight Agree my suggestion is just a workaround.
In the long term it would ideal if you could move to the new docker swarm mode (1.12.x), which would be resilent to this kind of issues.

**Comment by westsouthnight** [comment]
@aboch Where i can get manual for correct migration to new swarmkit? No have information about networking (overlay) in new swarmkit.

**Comment by aboch** [comment]
@westsouthnight
Look at https://docs.docker.com/engine/swarm/ for more information about the swarm mode, if you have not done so yet. Look at the new service/task model `docker service create ...`.

But if you are looking to migrate your existing containers as is, then you need to wait for docker 1.13 which will let you connect your existing containers to the swarm overlay networks.

In 1.12.x you can not `docker run ...` or `docker network connect ...` to a swarm overlay network.

**Comment by westsouthnight** [comment]
@aboch i have multiple working containers and services now more then 6 env, and yes, i want to migrate without or with minimal downtime to new docker, as result i'm wait 1.13

Thanks

**Comment by westsouthnight** [comment]
@aboch Its really not real!!! Second day after any restart docker service ( current versions which i test 1.12.2 & 1.12.3) or restart VM, or restart Consul, and i have 30% broken IPs and containers. Im update Consul to Latest version and Docker Swarm. Please, if you can do some magic which can resolve anytime "address already in use" or give some way to remove old from K/V. I cannot every time to change IP in repository, rebuild, test, and re-deploy.

**Comment by aboch** [comment]
@westsouthnight 

For all your containers on that nw:
`docker network disconnect <nw> <container>`

Delete the network which IPAM pool got in trouble state (this will destroy the pool):
`docker network create --subnet <> nw`

For all your containers:
`docker network connect --ip <ip>  <nw> <container>`

**Comment by westsouthnight** [comment]
@aboch very bad idea for production application and services

**Comment by westsouthnight** [comment]
Dear @aboch and @thaJeztah hi! I hope you will find time for this. Q1. You can please give me some way for respawn brocken IP. Q3. How to match values from container with consul K/V? 
Q4. May bee not really long to write small path with new item/setting/row in to json output **of** the ``` docker inspect ID ``` ?
Q.5 May be, I something not know, or about where get this matching pattern information will be can finded?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
