### ISSUE TITLE
error while running 

### ISSUE THREAD

**Issue by laithrafid** [moby/moby#27688]
every-time i'm running docker on of our servers i'm getting this error , only on this server tho ... 
and i couldn't  reproduce the issue on other servers 

**Describe the results you received:**
docker run -it centos  
YES
YES
YES
YES
YES
YES
YES
futexwakeup addr=0xc82009c108 returned -14
fatal error: unexpected signal during runtime execution
futexwakeup addr=0xc82006a908 returned -14
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1006 pc=0x440995]

runtime stack:
runtime.throw(0x18ebcc0, 0x2a)
        /usr/lib/golang/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.futexwakeup(0xc82009c108, 0x1)
        /usr/lib/golang/src/runtime/os1_linux.go:75 +0x75
runtime.notewakeup(0xc82009c108)
        /usr/lib/golang/src/runtime/lock_futex.go:135 +0xc2
runtime.startm(0xc820016a00, 0x100000001)
        /usr/lib/golang/src/runtime/proc.go:1601 +0x1fd
runtime.wakep()
        /usr/lib/golang/src/runtime/proc.go:1667 +0x59
runtime.newproc1(0x1a17928, 0xc820089f38, 0x8, 0x42d883, 0x7f4e07e8c1d0)
        /usr/lib/golang/src/runtime/proc.go:2747 +0x461
runtime.newproc.func1()
        /usr/lib/golang/src/runtime/proc.go:2661 +0x48
runtime.systemstack(0x219d700)
        /usr/lib/golang/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/lib/golang/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/lib/golang/src/runtime/asm_amd64.s:245 fp=0xc820089ee0 sp=0xc820089ed8
runtime.newproc(0x8, 0x1a17928)
        /usr/lib/golang/src/runtime/proc.go:2662 +0x62 fp=0xc820089f28 sp=0xc820089ee0
runtime.gcenable()
        /usr/lib/golang/src/runtime/mgc.go:191 +0x53 fp=0xc820089f50 sp=0xc820089f28
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:150 +0x138 fp=0xc820089fa0 sp=0xc820089f50
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820089fa8 sp=0xc820089fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1
[signal 0xb code=0x1 addr=0x1006 pc=0x440995]

runtime stack:
runtime.throw(0x18ebcc0, 0x2a)
        /usr/lib/golang/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.futexwakeup(0xc82006a908, 0x1)
        /usr/lib/golang/src/runtime/os1_linux.go:75 +0x75
runtime.notewakeup(0xc82006a908)
        /usr/lib/golang/src/runtime/lock_futex.go:135 +0xc2
runtime.startm(0xc820014000, 0x100000001)
        /usr/lib/golang/src/runtime/proc.go:1601 +0x1fd
runtime.wakep()
        /usr/lib/golang/src/runtime/proc.go:1667 +0x59
runtime.resetspinning()
        /usr/lib/golang/src/runtime/proc.go:1994 +0xcf
runtime.schedule()
        /usr/lib/golang/src/runtime/proc.go:2082 +0x27b
runtime.mstart1()
        /usr/lib/golang/src/runtime/proc.go:1108 +0x118
runtime.mstart()
        /usr/lib/golang/src/runtime/proc.go:1068 +0x72

**Output of `docker version`:**
 docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

**Output of `docker info`:**
 docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 4
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-202480769-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.016 GB
 Data Space Total: 107.4 GB
 Data Space Available: 50.21 GB
 Metadata Space Used: 1.634 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 56
Total Memory: 125.6 GiB
Name: dhcp-10-17-17-40.diablo.lan
ID: 6OBI:6S3K:4E3D:BI4H:4MKZ:DJVY:3OZQ:WDJ2:LHDF:GVKR:WXZM:ZSZ6
Registries: docker.io (secure)

 physical 

uname -a
Linux dhcp-0.laith.lan 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Can you try with the official docker packages instead of the centos-provided one?

**Comment by thaJeztah** [comment]
closing because this went stale
