### ISSUE TITLE
Building yocto image in docker with overlay2 stops the container unexpectedly

### ISSUE THREAD

**Issue by ernstp** [moby/moby#27683]
0) Setup docker with overlay2 on Ubuntu 16.04.1.

1) Create a docker container based on Ubuntu 16.04 with everything needed to do a Yocto build:
http://www.yoctoproject.org/docs/2.1/dev-manual/dev-manual.html#wic-requirements

2) Run a bash shell in it for example.

3) Setup a yocto workspace

4) bitbake core-image-minimal

After a few seconds into the actual building part the whole container seems to be abruptly killed. However docker ps -a simply lists exit status 0 and there are no logs indicating any issues (docker logs, host dmesg).
Changing to overlay (1) solved this issue.

docker info 
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.8 GiB
Name: be358qzm
ID: LZYB:F6ND:AESL:BFVG:XXEM:6KCB:NYVK:OHNJ:L7GN:MT3Z:MKHL:G7FY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

**Comment by dmcgowan** [comment]
@ernstp do you mind sharing an image which has up to step 3 completed to help us reproduce?

**Comment by ernstp** [comment]
Ok, here's an image:
https://drive.google.com/file/d/0B9HfxHnX3jqLSmdxZzBZdF93TFE/view?usp=sharing
Or did you mean Dockerfile?

And then you run with something like:
docker run -u builder -w /home/builder <image> ./build.sh

**Comment by ernstp** [comment]
When I imported the image on another computer running linux 4.8 I could not easily reproduce the problem. This is probably related to the layer system so you need to build this image locally.. ?

**Comment by dmcgowan** [comment]
@ernstp a dockerfile would work, although would be just as good to create your container, run through to step 3. After exit the container, call `docker commit <container id> <yourhubusername>/test27683` then `docker push <yourhubusername>/test27683`. That will at least keep the layering. If that does not work then the commands you used to reproduce would be helpful as I am not familiar with yocto and would have no idea if I was reproducing your setup.

**Comment by thaJeztah** [comment]
Looks like this issue went stale; I'll go ahead and close this, but let us know if you still have this issue on the current version of Docker, and an up-to-date Ubuntu kernel

**Comment by paroque28** [comment]
I have the exact same issue. Do you have any update on this?

**Comment by ernstp** [comment]
Not using that setup anymore, but I would recommend trying a newer kernel, like the latest HWE kernel on Ubuntu.
