### ISSUE TITLE
DNS value in daemon.json format

### ISSUE THREAD

**Issue by eliassal** [moby/moby#27694]
Can you please provide a daemon.json example with data. I am trying to do 
"dns": [192.168.1.13]
tried 
"dns": ["192.168.1.13"]
tried
"dns": "192.168.1.13"
tried
"dns": 192.168.1.13

Unfortunately nothing is working
Thanks in advance

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
The file should be valid JSON, have you tried something like this?

```JSON
{"dns":["208.67.222.222"]}
```

**Comment by eliassal** [comment]
Thanks, yes ite seems the right format, however, after spinning a container, doing ipconfig I still see the old DNS value I stopped container, docker service to be sure but still not getting the DNS mentiones in the daemon.json

**Comment by cpuguy83** [comment]
@eliassal What's the value of the "old DNS value"

**Comment by eliassal** [comment]
The value is 192.168.2.254. 
My subnet is 192.168.1.0, Gateway is my netgear router who is DHCP as well and just behine my ISP box which has DNS as the same value 192.168.2.254. So my machines on the subnet 192.168.1.0 all have DHCP for getting an IP and static DNS 192.168.1.13, so I thought that putting DNS value in daemon.json will do the same thing, NON?

**Comment by thaJeztah** [comment]
Closing this because of age, but feel free to open a new ticket if there's still an issue to resolve
