### ISSUE TITLE
No network connectivity while running docker build 

### ISSUE THREAD

**Issue by kminooie** [moby/moby#27706]
I run docker with an existing bridge. I encounter this issue only in this scenario. this is how I run dockerd: 

```
ExecStart=/usr/bin/dockerd` --dns 192.168.0.100 \
     --dns 192.168.0.120 \
     --ip-masq=false \
     -b kmtestbr0 \
     --fixed-cidr=192.168.7.0/25 \
     --default-gateway=192.168.0.2 \
     -l debug

```

the network used here is 192.168.0.0/16. This setting works when I am running a container. But when I try to build something I can't run commands like apt-get update or similar, and I get line like this in the syslog:

```
Oct 24 12:24:06 km systemd-udevd: Could not generate persistent MAC address for veth52eec58: No such file or directory
Oct 24 12:24:06 km NetworkManager[1153]: <warn>  [1477337046.1758] device (veth52eec58): failed to find device 77 'veth52eec58' with udev
Oct 24 12:24:06 km NetworkManager[1153]: <info>  [1477337046.1794] manager: (veth52eec58): new Veth device (/org/freedesktop/NetworkManager/Devices/106)
Oct 24 12:24:06 km NetworkManager[1153]: <warn>  [1477337046.1797] device (veth528358c): failed to find device 78 'veth528358c' with udev
Oct 24 12:24:06 km systemd-udevd: Could not generate persistent MAC address for veth528358c: No such file or directory
Oct 24 12:24:06 km NetworkManager[1153]: <info>  [1477337046.1851] manager: (veth528358c): new Veth device (/org/freedesktop/NetworkManager/Devices/107)
Oct 24 12:24:06 km kernel: kmtestbr0: port 3(veth528358c) entered blocking state
Oct 24 12:24:06 km kernel: kmtestbr0: port 3(veth528358c) entered disabled state
```

the full log is at https://paste.fedoraproject.org/460372/

I have to emphasis that this is not a problem with the image. I get the same thing in Debian, Fedora, Alpine, etc. Also, this is not an IP or dns issues. I have the following lines in a test Dockerfile:

```
RUN ip a s
RUN cat /etc/resolve.conf
RUN ping 192.168.0.2 || ping google.com
```

and I can see that a correct IP address has been assigned to the interface and resolve.conf has correct values, but I can NOT ping anything, my gateway, dns servers, goolge for that matter. Nothing.

I am running docker on fedora 24 taken from docker repository:
 docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:  
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:  
 OS/Arch:      linux/amd64

As I was looking at the existing issues, I saw this one that also had similar lines in its log file:

from https://github.com/docker/docker/issues/26655

```
Sep 17 10:36:46 node_master kernel: device veth80827e6 entered promiscuous mode
Sep 17 10:36:46 node_master NetworkManager[748]: (veth4ae3215): failed to find device 910 'veth4ae3215' with udev
Sep 17 10:36:46 node_master NetworkManager[748]: (veth4ae3215): new Veth device (carrier: OFF, driver: 'veth', ifindex: 910)
Sep 17 10:36:46 node_master NetworkManager[748]: (veth80827e6): failed to find device 911 'veth80827e6' with udev
Sep 17 10:36:46 node_master NetworkManager[748]: (veth80827e6): new Ethernet device (carrier: OFF, driver: 'veth', ifindex: 911)
Sep 17 10:36:46 node_master NetworkManager[748]: (docker0): bridge port veth80827e6 was attached
Sep 17 10:36:46 node_master NetworkManager[748]: (veth80827e6): enslaved to docker0
Sep 17 10:36:46 node_master dockerd: time="2016-09-17T10:36:46.069473191+08:00" level=debug msg="Assigning addresses for endpoint centos6.1.5hgikv2r357fs0k5lqn7uahcz's interface on network bridge"
Sep 17 10:36:46 node_master dockerd: time="2016-09-17T10:36:46.335922315+08:00" level=debug msg="Programming external connectivity on endpoint centos6.1.5hgikv2r357fs0k5lqn7uahcz (60e70145fcf129e452ed3d27a1e4e58fc9c5aa1f143ff0fd568a6120a3ebdc14)"
Sep 17 10:36:46 node_master dockerd: time="2016-09-17T10:36:46.588175968+08:00" level=debug msg="Revoking external connectivity on endpoint centos6.1.5hgikv2r357fs0k5lqn7uahcz (60e70145fcf129e452ed3d27a1e4e58fc9c5aa1f143ff0fd568a6120a3ebdc14)"
Sep 17 10:36:47 node_master kernel: docker0: port 1(veth80827e6) entered disabled state
```

is this a bug? or are we doing something wrong here?

**Comment by MatthiasLohr** [comment]
I've currently the same state... any solution to this?

**Comment by thaJeztah** [comment]
@MatthiasLohr can you try disabling NetworkManager, and see if that makes a difference?

**Comment by WyseNynja** [comment]
I just ran into something similar. The nameserver in /etc/resolv.conf was 192.168.0.1 instead of the proper IP for my network.

**Comment by thaJeztah** [comment]
@kminooie are you still having this issue?

**Comment by thaJeztah** [comment]
Closing because this went stale
