### ISSUE TITLE
"docker exec" and "docker stop" commands throw permission denied exception

### ISSUE THREAD

**Issue by vtutrinov** [moby/moby#27742]
**Steps to reproduce the issue:**
1. build and image from dockerfile like

FROM alpine:latest
CMD /bin/sh
1. run it in -dit mode

docker run -dit --name mycontainer mynewimage
1. stop running container
   docker stop mycontainer

**Describe the results you received:**
Error response from daemon: Cannot stop container mycontainer: Cannot kill container 194b31df7d8cb97efcc53905d7b1172ffda90c1909274b7b2efba9f0a36fd925: rpc error: code = 7 desc = permission denied

![image](https://cloud.githubusercontent.com/assets/1343632/19691163/f7a5ed16-9adb-11e6-9388-916744a47e5c.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay

Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73 GiB
Name: tutrinov-pro
ID: BA5U:WBBF:DR6E:CYE3:EGZP:FJTC:IOVO:GX3O:TGNA:FT2T:EBYP:PFBC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: vtutrinov
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by vtutrinov** [comment]
Run with 

> --security-opt apparmor:unconfined

fixed issue.
But I expected such behavior by default.

**Comment by thaJeztah** [comment]
Can you try if you're still able to reproduce this on docker 1.12.3?

**Comment by vtutrinov** [comment]
version 1.12.3 has the same issue

![image](https://cloud.githubusercontent.com/assets/1343632/19932295/a71f1cbe-a120-11e6-88bb-f14d2eb36563.png)

**Comment by ripcurld00d** [comment]
@thaJeztah @vtutrinov tried to reproduce it unsuccessfully.
```shell
$$ echo "FROM alpine:latest
CMD /bin/sh" | docker build -t test1 -
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM alpine:latest
latest: Pulling from library/alpine
3690ec4760f9: Pull complete 
Digest: sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Status: Downloaded newer image for alpine:latest
 ---> baa5d63471ea
Step 2/2 : CMD /bin/sh
 ---> Running in 64847361d9a7
 ---> 15515b478593
Removing intermediate container 64847361d9a7
Successfully built 15515b478593
$ docker run -dit --name bla test1
3330a621dc79367d527fcf86d801a83b6e82b282316b6f32bac961404eebf65d
$ docker exec bla ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c /bin/sh
    7 root       0:00 /bin/sh
    8 root       0:00 ps
$ docker stop bla
bla
```

```shell
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.13.0-dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.9-200.fc24.x86_64
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.43 GiB
Name: 242d7a0e8f56
ID: ZTHG:TAKY:G23Z:XOVM:QGYK:L3OW:FCLA:2TGL:MK5W:LSNI:6PZZ:LCDG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-11-03T19:28:29.886663128Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
root@242d7a0e8f56:/go/src/github.com/docker/docker# 
root@242d7a0e8f56:/go/src/github.com/docker/docker# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.13.0-dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:                                                                                                                                             [0/214]
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.9-200.fc24.x86_64
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.43 GiB
Name: 242d7a0e8f56
ID: ZTHG:TAKY:G23Z:XOVM:QGYK:L3OW:FCLA:2TGL:MK5W:LSNI:6PZZ:LCDG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-11-03T19:29:03.216098891Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dalareo** [comment]
Any solution to this? I suddenly cannot manage my container in DigitalOcean. It throws:

code = 7 desc = permission denied

**Comment by dmullaney** [comment]
I'm also having this problem - any ideas on how to resolve?
I'm running Docker 1.13 on Ubuntu 16.04.1 LTS

**Comment by ripcurld0** [comment]
@dalareo and @dmullaney to solve this (I guess you both are using Ubuntu) do as @vtutrinov suggested:
Add the `--security-opt apparmor:unconfined` option

**Comment by cpuguy83** [comment]
Ping @justincormack 
Some new apparmor hell?

**Comment by dalareo** [comment]
But why is it working without the hack in my local machine, @ripcurld0 ? It also uses Ubuntu!!

**Comment by ripcurld0** [comment]
@dalareo can you provide both Ubuntu and Docker versions on your laptop and DigitalOcean?

**Comment by dalareo** [comment]
My PC uses Ubuntu 16.04 and Docker 1.13.0

My DO droplet uses Ubuntu 14.04 and Docker 1.12.5

**Comment by ripcurld0** [comment]
@dalareo could it be that AppArmor is disabled on your laptop.
Run `sudo apparmor_status`

**Comment by dalareo** [comment]
I am afraid it is not:

apparmor module is loaded.
28 profiles are loaded.
28 profiles are in enforce mode.
   /sbin/dhclient
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince-thumbnailer//sanitized_helper
   /usr/bin/evince//sanitized_helper
   /usr/bin/lxc-start
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/telepathy/mission-control-5
   /usr/lib/telepathy/telepathy-*
   /usr/lib/telepathy/telepathy-*//pxgsettings
   /usr/lib/telepathy/telepathy-*//sanitized_helper
   /usr/lib/telepathy/telepathy-ofono
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
   /usr/sbin/ippusbxd
   /usr/sbin/mysqld
   /usr/sbin/tcpdump
   docker-default
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
0 profiles are in complain mode.
3 processes have profiles defined.
3 processes are in enforce mode.
   /usr/lib/telepathy/mission-control-5 (2560) 
   /usr/sbin/cups-browsed (13579) 
   /usr/sbin/cupsd (13577) 
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

**Comment by ripcurld0** [comment]
Thanks for the input. I will try to investigate this more.

**Comment by gbozee** [comment]
I kinda resolved this issue by restarting the server/machine.

**Comment by lukaszgryglicki** [comment]
Works for me too with `--security-opt apparmor:unconfined`
The Strange part is that I need this option on one Ubuntu 17.04 while I don't need it on another.
They have different kernels but both were installed as "Ubuntu 17.04"

This server is OK without this option:
```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
>>> uname -a
Linux cncftest.io 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

And this server requires this option:
```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
>>> uname -a
Linux devstats.io 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
