### ISSUE TITLE
docker ps hang if log tag illegal

### ISSUE THREAD

**Issue by ghost** [moby/moby#27770]
I create service always hang(on the worker node use ps) if I use wrong config(I use fluentd)
   "tag": '"docker.{{.Name}}"',
the right config is: 
    "tag": "docker.{{.Name}}",
I don't know if you can Reproduction this 
docker info:
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-144735-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.272 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.23 GB
 Metadata Space Used: 2.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: 7y98mueh7qojrugn2sityx1z1
 Is Manager: true
 ClusterID: 750w4cbchgc1hn6f6b69zr1b1
 Managers: 5
 Nodes: 9
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.19.29.12
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: sa-swarm0-cnc0.hlg01
ID: GQYK:LD57:TCAA:DEB3:FA63:QZ2S:DN7N:W23E:ODEB:FEBM:J4T2:OV5E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 135
 System Time: 2016-10-26T15:13:26.681290012+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 hub.internal.wandoujia.com
 127.0.0.0/8

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
