### ISSUE TITLE
Windows: Error response from daemon: missing device in volume options

### ISSUE THREAD

**Issue by jessegranger** [moby/moby#27792]
**Description**

Cannot use a named local data volume on Windows.

"Error response from daemon: missing device in volume options."

**Steps to reproduce the issue:**

1 > docker volume create --name mongodata
2 > docker volume ls | grep mongodata

```
local               mongodata
```

3 > docker run -it -v mongodata:/data/db mongo

```
docker: Error response from daemon: missing device in volume options.
See 'docker run --help'.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This is unrelated to daemon restarts (there is a similar closed ticket where volumes are not usable after a daemon restart, here there is no restart happening).

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 89
 Running: 2
 Paused: 0
 Stopped: 87
Images: 651
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 422
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.942 GiB
Name: moby
ID: 5R42:RGC2:JJIX:YXKW:WWOZ:LLU7:2ZDB:5DTW:L4CY:SDSH:S2XX:2A6J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 51
 System Time: 2016-10-26T16:40:44.3117157Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 Pro 64-bit.

**Comment by allencloud** [comment]
@jessegranger Have you ever set options for this volume?
As I searched the related code, if you set options, there is some possibility to throw this error.

**Comment by jessegranger** [comment]
It's possible that an earlier call to volume create did pass options with that name, but I can't recall for sure.

If I try a totally new name, it seems to work (didn't do any real testing but the container launches without crashing).

I definitely did ```docker volume rm mongodata``` several times, so it sounds like there are two bugs:

1. `docker volume rm` doesn't remove the [side-effects of] past options, and
2. those specific option values have silently caused the volume to be both 'created' and also 'missing' at the same time.

**Comment by cpuguy83** [comment]
opts are definitely removed when the volume is removed. Are you sure you don't have something else creating it? Maybe a swarm service?

**Comment by jessegranger** [comment]
I can't get the rm to fail when trying to reproduce it now.

The best (worst) I can reproduce is not that bad after all:

```
> docker volume create --name badhombres --opt=o=4G # a typo in the options here
badhombres
> docker volume create --name badhombres # any --opt here is ignored, but it reports success
> docker run -v badhombres:/data/db mongo # fails (correctly, sort of)
docker: Error response from daemon: missing device in volume options.
See 'docker run --help'.
```

So, all I can reproduce is two mostly-correct behaviors conspiring with each other (ignoring rather than failing duplicate calls to "volume create", and the ambiguous error message).

**Comment by cpuguy83** [comment]
The error messages are already much better on master (and subsequently 1.13).
The double-create is being worked on. It's unfortunately not so simple due to legacy reasons.

**Comment by yongtang** [comment]
#27675 is related to double-create. I will double check so that different volume create options will return error.

**Comment by typik89** [comment]
try this: docker run -it -v /mongodata:/data/db mongo

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
