### ISSUE TITLE
--insecure-registry is not working when docker pull started by cron

### ISSUE THREAD

**Issue by skoch123** [moby/moby#27823]
Hello!
 I have crontab:
`*  *   *   *   * if [ -f /opt/image ]; then rm /opt/image && docker pull hub:5000/image; fi;`
 syslog:

<pre>
dockerd[12776]: time="2016-10-27T16:48:01.492256773+07:00" level=warning msg="Error getting v2 registry: Get https://hub:5000/v2/: http: server gave HTTP response to HTTPS client"
Oct 27 16:48:01 dockerd[12776]: time="2016-10-27T16:48:01.492370392+07:00" level=error msg="Attempting next endpoint for pull after error: Get https://hub:5000/v2/: http: server gave HTTP response to HTTPS client"
</pre>

docker info:

<pre>
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/storage/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.76 GiB
Name: sandbox-01
ID: DOLN:GPKA:Z5OU:NUEQ:N34M:5FVS:XUIM:ZORY:AJQK:QQED:7KDT:KYXL
Docker Root Dir: /var/storage/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 hub:5000
 127.0.0.0/8
</pre>

What I doing wrong?

**Comment by thaJeztah** [comment]
Given that `--insecure-registry` is set on the daemon, it shouldn't make a difference where/what is calling it. Are you sure the cronjob is connecting to the same daemon as you're connecting to when running `docker pull` manually?

**Comment by skoch123** [comment]
When I run `docker info` by cron, I get same output information: 
<pre>
Insecure Registries:
 hub:5000
 127.0.0.0/8
</pre>

**Comment by thaJeztah** [comment]
so, it looks like the setting is correctly picked up; i suspect there's something wrong in your setup. Do you use authentication for your registry? The cron job may not be logged in.

**Comment by skoch123** [comment]
I don't use authentication for registry. When I running `if [ -f /opt/image ]; then rm /opt/image && docker pull hub:5000/image; fi;` from CLI - all works.

**Comment by thaJeztah** [comment]
The cron job should not make a difference here; the `daemon.json` is read by the `dockerd` daemon when starting up. Clients connect with the daemon over the remote API (through a socket, or through a tcp connection).

@vvp83 are you sure the cron job is connecting to the same daemon as you're connecting to when running the command manually?

**Comment by vvp83** [comment]
Yes, im  sure. Same host, same docker, same command.  One host, One docker, One command. 
Why u cannt emulate this? Issue open 2 year and i dnt see that it solved. Joke?

**Comment by thaJeztah** [comment]
closing as this one went stale

**Comment by Cajga** [comment]
We run into the same issue here and willing to help in the debug. Please let me know what could be the next step.

**Comment by thaJeztah** [comment]
> for some reason the crontab does not use the credentials stored in /root/.docker/config.json

Is the crontab running  as root? The CLI will look in `~/.docker/` (home-directory of the user that executes the CLI); to get the home-directory, the CLI may also look at the `$HOME` environment-variable in some cases. You can have the crontab run `docker --help``, which should print the path it looks for by default in the `--config` flag description;

```bash
docker --help | grep -- --config

      --config string      Location of client config files (default "/Users/sebastiaan/.docker")
```


To force the CLI into using a specific directory to look for the configuration file, you can also use the `--config` option to specify the directory (`docker --config=/root/.docker/ pull ...`)

**Comment by Cajga** [comment]
Thanks for the help, our issue was the change of `$HOME` in the crontab file. Due to that, the docker command was trying to load the config from from somewhere else.

**Comment by thaJeztah** [comment]
Good to hear you found the cause 👍
