### ISSUE TITLE
Print a diagnostic when pull failure causes fallback to v1 registry API

### ISSUE THREAD

**Issue by bmerry** [moby/moby#27821]
**Description**

As discussed in #27281, if `docker pull` encounters any problems using the v2 API (such as a 401 error due to not having logged in), it falls back and tries the v1 API. If the registry doesn't implement the v1 API, this in turn causes a 404 error, and the user sees only the message "not found", and the original error via the v2 API is lost.

**Steps to reproduce the issue:**
1. Install a registry (I use the image registry:2.5) with htpasswd auth.
2. Log in to the registry and push an image
3. On another machine (or after logging out of the registry), run `docker pull <registry>:<port>/<image>`.

**Describe the results you received:**

Docker output:

```
Using default tag: latest
Pulling repository registry:5000/bmerry/abacuscm
Error: image bmerry/abacuscm:latest not found
```

Registry log file:

```
time="2016-10-11T09:14:34Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=2ec10df4-0f18-4d69-b69b-e017b720b5ea http.request.method=GET http.request.remoteaddr="172.17.0.1:32768" http.request.uri="/v2/" http.request.useragent="docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" instance.id=be638723-6e27-43a5-a2d6-1fc5254d7b71 version=v2.5.0 
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
2016/10/11 09:14:34 http: TLS handshake error from 172.17.0.1:32772: tls: first record does not look like a TLS handshake
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v1/_ping HTTP/1.1" 404 19 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v1/repositories/bmerry/abacuscm/images HTTP/1.1" 404 19 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
```

**Describe the results you expected:**

Docker Engine should print a diagnostic when access with the v2 API fails, indicating the cause of the failure, and warn that it is falling back to the v1 API. That way the real error is not suppressed.

**Additional information you deem important (e.g. issue happens only occasionally):**
The fundamental problem (that the real error returned by the registry is not reported, and a misleading one is instead) keeps getting reported (#17721, #18263, #27281, https://bugzilla.redhat.com/show_bug.cgi?id=1347805, probably more I missed), and they keep getting closed as "by design". I don't actually care how it gets fixed, but this is a suggested fix that I'm hoping will be acceptable and hopefully not too difficult to implement.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 385
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 634
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.36 GiB
Name: kryton
ID: MFLN:XRFL:372N:VPKR:3AWK:USXB:3Q3E:EAH2:66ZK:T5U2:NEOP:TSCH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box running Ubuntu 14.04.

**Comment by thaJeztah** [comment]
support for v1 registries was removed, so we can close this one
