### ISSUE TITLE
PXE BOOT CentOS 7 run Docker error?

### ISSUE THREAD

**Issue by jixuege** [moby/moby#27861]
OS:
CentOS 7.2
Kernel:
3.10
describe:
CentOS 7.2 boot from pxe , docker module is devicemapper  ,now i got a error by start container ,this is the Details of the error message:
[root@jycloud ~]# docker run -itd box
WARNING: IPv4 forwarding is disabled. Networking will not work.
b96378de871d15293de011eb5129ed0db548170e2fccee10747930ac710d8207
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\"rootfs_linux.go:89: jailing process inside rootfs caused \\\\"pivot_root invalid argument\\\\"\\"\"\n".

os mount result :+1: 
[root@jycloud ~]# mount
rootfs on / type rootfs (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=16577268k,nr_inodes=4144317,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=27,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
configfs on /sys/kernel/config type configfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=3362888k,mode=700)

hope to fix this problem,thans!!!hope you reply.

**Comment by thaJeztah** [comment]
can you add the output of `docker info` and `docker version` as well, as was requested in the bug report template?

**Comment by jixuege** [comment]
hello，dockinfo  MES：
[root@jycloud ~]# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 2
Server Version: 1.12.3-rc1
Storage Driver: devicemapper
 Pool Name: docker-8:16-134217866-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop4
 Metadata file: /dev/loop5
 Data Space Used: 63.44 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.2 GB
 Metadata Space Used: 667.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 32.07 GiB
Name: jycloud
ID: KSRV:EIGE:GLPO:QTTH:KC5Q:6NTD:LI6D:ERB2:4JCS:OQXQ:WYM7:LFDM
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

Docker Version:
[root@jycloud ~]# docker version
Client:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        
 OS/Arch:        linux/amd64
 Experimental: true

Before ,I just use docker version 1.10，Still the same mistakes

**Comment by AkihiroSuda** [comment]
I guess you are hitting this limitation
https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt
> you can neither pivot_root rootfs, nor unmount it. 

Can you configure the system to use initrd instead of rootfs?

**Comment by AkihiroSuda** [comment]
Or another workaround is to install VirtualBox, KVM, or VMware onto your PXE env, and use [Docker Machine](https://github.com/docker/machine)

**Comment by jixuege** [comment]
@AkihiroSuda 
hello，this is PXE config ,we use initrd to start centos 7 system ,but always error 
pxelinux.cfg/default
default auto
label auto
prompt 0
kernel  vmlinuz-3.10.0-327.36.3.el7.x86_64
append  initrd=w1.img.gz selinux=0 ip=dhcp rw nomodeset

this is our step to use initrd:
1、install system（centos 7）
2、 rsync /*  to  a  dir(for ex. /pxe) 
3.chroot /pxe
4、find . |cpio -c -o >w1.img
5、gzip w1.img  
6.mv w1.img.gz to tftp workstation
7.Modify  pxelinux.cfg/default  initrd=w1.img.gz
8.network boot vm form pxe
system is booting,but docker run  is error

as well as my first question

**Comment by jixuege** [comment]
@thaJeztah  hello，help me, pls

**Comment by liangwei1988** [comment]
l have the same problem

**Comment by AkihiroSuda** [comment]
@jixuege 
your initrd is actually initramfs but not initrd

> In the initrd scheme, the image may be a file system image (optionally compressed), which is made available in a special block device (/dev/ram) that is then mounted as the initial root file system.[3] The driver for that file system must be compiled statically into the kernel. Many distributions originally used compressed ext2 file system images...
>
> In the initramfs scheme (available since the Linux kernel 2.6.13), the image may be a cpio archive (optionally compressed). 
>
> ...
>
>On an initrd, the new root is mounted at a temporary mount point and rotated into place with pivot_root(8) (which was introduced specifically for this purpose). This leaves the initial root file system at a mount point (such as /initrd) where normal boot scripts can later unmount it to free up memory held by the initrd.
>
>On an initramfs, the initial root file system cannot be rotated away.[8] Instead, it is simply emptied and the final root file system mounted over the top.


Can you configure your system to use initrd instead?
(But I'm not sure CentOS7 kernel still supports initrd.. Needs investigation)

**Comment by thaJeztah** [comment]
closing because this went stale
