### ISSUE TITLE
Windows Containers - Location for images download

### ISSUE THREAD

**Issue by eliassal** [moby/moby#27941]
Hi, when windows containers are used, which directory is used when pulling, downloading images and how it can be changed in order not to fill the C drive?
Thanks

**Comment by cpuguy83** [comment]
ping @friism

**Comment by StefanScherer** [comment]
I can measure these folders while a `docker pull`.

1. download docker image layer to
C:\ProgramData\docker\windowsfilter\XXXXX\Hives\System_Base

2. extract to system windows temp
C:\Windows\Temp\hcsXXXXX\Files\...

then some writes to:
C:\ProgramData\docker\image\windowsfilter\layerdb\tmp\write-set-XXXXX\tar-split.json.gz

and the final files go to:
C:\ProgramData\docker\windowsfilter\XXXXX\Files\...

procmon is your friend :-)

**Comment by eliassal** [comment]
Thanks Stefan, but how this can be changed, I ran only 1 container (Multi-Container Applications labfrom  https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md)
windowsfilter is now 24 GIG !!!!!!!!!

**Comment by StefanScherer** [comment]
Haven't tried it yet, but have a look at http://docs-stage.docker.com/v1.10/engine/reference/commandline/daemon/ and there the option `-g` or show the usage of dockerd:

```
PS C:\vagrant> dockerd --help | sls graph

  -g, --graph string                          Root of the Docker runtime (default "C:\\ProgramData\\docker")
```

Are you on Win2016 or Win10 with Docker-for-Windows?

For Win2016: The `dockerd --register-service` command needs the `-g` option and your path.
For Win10: I don't know.

**Comment by StefanScherer** [comment]
Or try to cleanup old containers and temporary images.

See https://blog.sixeyed.com/ve-installed-docker-on-windows-now-what/ for some PowerShell aliases.
Upcoming Docker 1.13 will have `docker system prune` and similar commands.

**Comment by eliassal** [comment]
It is  ein 10 enterprise with Docker for windows, it seems that there is no dockerd.
There is a service "com.docker.service" its executable is "C:\Program Files\Docker\Docker\com.docker.service"

**Comment by eliassal** [comment]
Stefan, the url you provided is very useful. I issued the command
docker images --no-trunc
I get back 3 records which is correct, however, in "C:\ProgramData\Docker\windowsfilter" I gave 32 directories

35f34a62175c8213b981d84964e5392d338d9f72b16b74088902183479b4ef72
73cff097674dc109928640c97811907b9680edd6401d217e53069f96c1912f62
875e897cfcc5262ee3008f4c73922bc9efabe03bbb30d3879e5814e43acd17ae
.....
......
.....
![dockerimages](https://cloud.githubusercontent.com/assets/8447864/19901726/6511b61e-a068-11e6-9963-fe3f73509f29.jpg)
![dockerimages_002](https://cloud.githubusercontent.com/assets/8447864/19901763/83dc93de-a068-11e6-8029-c883ba4194b4.jpg)

**Comment by eliassal** [comment]
If you look at the 1st snapshot size column, by adding the size for the 3 images, we get the 24Gig. Does this mean that all those 32 directories are parts of the 3 images? 
I understand from the comcepts behind Docker is light and fast running containers which seems not the case here as for running 2 containers, DB and a very basic web app, 24 GIG is needed and between 5 to 6 hours of executing the docker-compose stuff according to the lab. I come from MS side and started working with working on Docker on Ubuntu and Centos, really huge difference on all levels. On a Centos machine I run 5 or 6 containers, never reached 2 Gig of disk

**Comment by friism** [comment]
@eliassal No, 24GB is not needed for storing those images. The size listed is the size of all the layers comprising a particular image, but typically lots of layers will be shared between many images.  This is also the case on Windows, and those three images that you refer to probably all share the same `microsoft/windowsservercore` base layer, and that base layer only exists in one copy on your machine.

**Comment by eliassal** [comment]
@friism Ok not needed maybe but when I check the windowsfilter directory it indicates 24G, my C drive now is ain a very bad shape and has 400Meg free space out of 30Gig, so the question now is how this can be cleaned if I docker for windows does not need those 24Gig of data
![dockerimages_003](https://cloud.githubusercontent.com/assets/8447864/19925750/9c55a96c-a0f1-11e6-9bce-c56b66cc39cc.jpg)

**Comment by eliassal** [comment]
@friism so my main question in this thread is can we change the location for Docker operations to a different location, on another disk in order to avoid foilling the C drive, any idea?

**Comment by friism** [comment]
@eliassal it's not currently possible to customize this with Docker for Windows, but if you install the daemon yourself, you can do it how Stefan suggested. We're also tracking this as a future enhancement to Docker for Windows.

**Comment by eliassal** [comment]
@friism I followed instructions for a workaround in the thread 
https://github.com/docker/for-win/issues/191
which allowed me to have all files in another drive. Yes, I beleive it should be added as a seeting as not too many developers assign more than 30 to 40G to C drive which is filled so quickly for running 2 containers.
Thanks for your help

**Comment by rmcolbert** [comment]
@friism You can use the graph attribute in daemon.json to change where the filesystem is stored. The piece that is missing is a config setting in the Docker for Windows UI.

**Comment by friism** [comment]
@rmcolbert Indeed! We have an internal issue to track adding this.

**Comment by jupaol** [comment]
This is how I did it:

**Windows 2016**

docker info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ee-4
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.031GiB
Name: ****
ID: GYBO:TTZK:EZTD:WL5B:A5S2:GXTY:527R:ZPTU:66T4:RQBL:M6MM:WJ5D
Docker Root Dir: C:\_c
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Create a daemon.json file under: C:\ProgramData\docker\config
With the following configuration: 
{
  "data-root": "E:\\_c\\whatever"
}
Example:
New-Item C:\ProgramData\docker\config\daemon.json -Force -Value '{"data-root": "{{Your Path Here}}"}'

Restart the service:
Stop-Service Docker -Force
Start-Service Docker

Note:
In my case, all the existing images/container/etc were not moved to the new location

**Windows 10**

docker info

Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 8
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 23.92GiB
Name: ****
ID: JVRO:IBMT:UTN2:PVVW:26M4:GJB2:MHGX:UYLC:HJMO:MQZE:GWGU:7W7L
Docker Root Dir: D:\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 40
 System Time: 2017-10-19T12:48:37.4711807-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Update/Add this file:
C:\ProgramData\Docker\config\daemon.json

(This is how mine looks)
{"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true, "graph": "D:\\Docker"}

You are all set!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
