### ISSUE TITLE
Add the ability to specify global build args

### ISSUE THREAD

**Issue by LaurentGoderre** [moby/moby#27949]
**Description**

Using `--build-arg` is convenient for setting proxy settings for build but it isn't ideal in many scenario, most of all when using compose. To get our images to build behind corporate firewall, we have to add the `arg` section to all our compose file. Ex:

```
 args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
```

This solves our own images but if we contribute on Dockefile from anyone else, we have to patch those files with these args to get them to build.

It would be nice if in addition to being able to specify command line build args, it was possible to specify global ones using `DOCKER_BUILD_` environment variables. This would allow those of us unfortunate enough to be behind proxy to have our build arguments specific to our environment in env vars and not anywhere else. The `DOCKER_BUILD_` vars could be merged with the cli `--build-arg`, with the cli options taking precedence.

**Comment by duglin** [comment]
if we can find the right syntax for this, it sounds good to me.

It might be nice to consider that some people may want to specify other `docker build` flags via env vars too - like `--rm` or `-q` so if we can either combine them into one or find a pattern that can be reused for others then that would be good.

e.g.
```
DOCKER_BUILD=-rm --build-arg foo=bar --quiet`
```
of course this can be tricky to get the parsing right but we have parsers in the builder we can reuse.

**Comment by LaurentGoderre** [comment]
That would work for me as long as expansion works within so I could do something like:
```
DOCKER_BUILD=--build-arg http_proxy=$http_proxy`
```

**Comment by duglin** [comment]
we'd need to make sure the env var processing rules made sense, yea

**Comment by thaJeztah** [comment]
Isn't this exactly where the multiple compose files / override files are implemented for? https://docs.docker.com/compose/extends/#/different-environments

**Comment by LaurentGoderre** [comment]
The multiple compose file is for creating different containers for different environments. Our issues is that every Dockerfile we have to build, using container or otherwise, we have to pass `--build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy`. It's not exactly the same use case.

**Comment by thaJeztah** [comment]
@LaurentGoderre AFAIK, it should be possible to use that to _just_ override / append build-args. That way you can simply have a `docker-compose.override.yml` containing the build-args for your environment, without touching the regular `docker-compose.yml`.

Have you tried?

**Comment by LaurentGoderre** [comment]
@thaJeztah yes it is possible but far than ideal because we'd have to create overrides for each docker compose file and each service within it. Not only that but we'd also have to create and maintain patches for all Makefile and scripts that invoke `docker build` to add these params.

I know our setup isn't ideal either but corporate proxy are pretty common and any help we can get to help us work efficiently within them would help us greatly.

**Comment by eigood** [comment]
You can just do "--build-arg http_proxy", without specifying a value, and docker-build will copy whatever setting it already has from it's parent environment.  This should simply things a bit.

The issue I am having with docker-compose, is that in my yml files, I had to do args: ["http_proxy", "https_proxy"] for each and every single build context.  It's acting like the internal default list of build-args that docker-build has it not being read when docker-compose is run.

**Comment by dan-compton** [comment]
hI like this. Global build arguments would also eliminate the necessity of running per-service docker-compose build calls when all of those services share the build-arg.   Currently, docker-compose requires a service to build when build-arg is passed.  That's not technically necessary if all services share the same build-args as mentioned above.

I might go a step further and introduce something like following syntax:

```
--build_arg SERVICE:KEY=VALUE
```
It would be nice if you could at least specify 2 build args, one for each service and it makes sense if the default behavior for build is to build all services.

**Comment by brunowego** [comment]
Think about the option below to around this.

Environment variables:

```sh
# Proxy
export PROXY_HOST=$(ip route get 1 | awk '{print $NF;exit}')
export PROXY_PORT=3128

# HTTP Proxy
export http_proxy=http://$PROXY_HOST:$PROXY_PORT
export https_proxy=$http_proxy
export no_proxy=localhost,127.0.0.1

# Docker Build
export DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg no_proxy=$no_proxy"
```

Makefile:

```Makefile
SHELL := /bin/sh

DOCKER_BUILD_OPTS ?=

HBASE_VERSION := $(shell git describe --tags --abbrev=0 2> /dev/null)

DOCKER_REPO := rowupper
DOCKER_IMAGE := hbase
DOCKER_TAG := ${HBASE_VERSION}

.PHONY: docker/build docker/push

docker/build:
	docker build \
		${DOCKER_BUILD_OPTS} \
		--build-arg HBASE_VERSION=$(HBASE_VERSION) \
		-t $(DOCKER_REPO)/$(DOCKER_IMAGE):$(DOCKER_TAG) \
		-t $(DOCKER_REPO)/$(DOCKER_IMAGE):latest \
		.

docker/push:
	docker push $(DOCKER_REPO)/$(DOCKER_IMAGE):$(DOCKER_TAG)
	docker push $(DOCKER_REPO)/$(DOCKER_IMAGE):latest

```

**Comment by thaJeztah** [comment]
Actually; looks like this is a duplicate of https://github.com/moby/moby/issues/36102, and for proxies, this was implemented;

- https://github.com/docker/cli/pull/93 Allow Proxy Configuration in config.json
  - continuation of https://github.com/moby/moby/pull/30588 
- (related) https://github.com/moby/moby/pull/31584 Exclude “default” build-args from image history
- (related topic); https://github.com/moby/moby/issues/30323 Improve UX around http-proxy for those in corporate environment


Docker 17.07 and up, you can set default proxy settings in the CLI configuration file (`~/.docker/config.json`) those settings will be applied both when starting a container (`docker run`) and during `docker build` (they will be automatically passed as `--build-arg`)

With that configuration in place, no changes would have to be made to the compose file, or build scripts (as the `docker` cli reads the configuration from its `~/.docker/config.json` configuration file)


As to changes for the docker-compose, that would be best kept for the docker-compose issue tracker (https://github.com/docker/compose), but given that environment variables can already be substitutes in the docker-compose file I'm not sure if additional features should be added there (but; best left to the docker compose maintainers)


I'll close this issue, because I think the original request has been addressed.
