### ISSUE TITLE
Docker invalidates default Seccomp profile json

### ISSUE THREAD

**Issue by guoger** [moby/moby#27978]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
I followed Docker Seccomp usage guide [here](https://docs.docker.com/engine/security/seccomp/) and used [default profile](https://raw.githubusercontent.com/docker/docker/master/profiles/seccomp/default.json), and got error:
`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"empty string is not a valid syscall\"\n".
`

**Steps to reproduce the issue:**
(Essentially just follow the guide in above link)
1. Download default seccomp profile json from [here](https://raw.githubusercontent.com/docker/docker/master/profiles/seccomp/default.json)
2. docker run --rm -it --security-opt seccomp=/path/to/seccomp/profile.json hello-world

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.797 GiB
Name: myserver
ID: RZN7:A4OM:DVGC:3OUT:GEBY:ANAX:3DGF:BE7G:FZ4L:H6O2:4XG7:DGDF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

Is this json format outdated? Where can I find a proper guide to write correct one? Thanks in advance!

**Comment by thaJeztah** [comment]
There's a change in format for the upcoming 1.13 release, can you try using the default profile in the 1.12.3 tag instead of master? https://raw.githubusercontent.com/docker/docker/v1.12.3/profiles/seccomp/default.json

**Comment by guoger** [comment]
@thaJeztah thanks for your prompt reply! Problem solved! It would be nice if we update original doc to refer to correct branch.

A follow up question: I don't see runc checks if architecture already exists in Seccomp context while adding them. If that actually happens, I would be very grateful if you could point it out.

**Comment by justincormack** [comment]
@mstanleyjones we should update the docs for this

@guoger sorry I don't quite follow your question. The handling is mainly done in `libseccomp` at present, rather than directly in `runc` which just uses the Go libseccomp API.

**Comment by guoger** [comment]
@justincormack I see `IsArchPresent` method in libseccomp-golang: https://github.com/seccomp/libseccomp-golang/blob/master/seccomp.go#L549

However, I couldn't find any runc code actually using it so I suspect it is not checked?

**Comment by justincormack** [comment]
Ah, libseccomp automatically adds the native arch to the filter if none is specified and you do not explicitly remove it, see http://man7.org/linux/man-pages/man3/seccomp_arch_add.3.html so we allow the profile to not specify and arch at all and use this fallback.

**Comment by guoger** [comment]
@justincormack my question is actually where the error of adding existing arch is ignored. And I just found libseccomp-golang does it here https://github.com/seccomp/libseccomp-golang/blob/master/seccomp.go#L584-L590

Anyway, thanks guys, I will close this issue unless you want to use it to track doc change.

**Comment by justincormack** [comment]
We should track the doc change, as this has come up before.

**Comment by thaJeztah** [comment]
Not sure what's best for the docs, as we do want people to use the up to date version; perhaps explain how to get the one for the cersion they're running?

**Comment by guoger** [comment]
@justincormack OK I'll leave this issue open to you guys then. Another question: I see that `SCMP_ACT_ERRNO` and `SCMP_ACT_TRACE` return code is currently hard-coded to `EPERM` (https://github.com/opencontainers/runc/blob/master/libcontainer/seccomp/seccomp_linux.go#L20-L21). I wonder the reason behind this?

**Comment by justincormack** [comment]
I think there was some discussion about this a long time ago on the OCI
mailing list, I think it was just a simplification as there were not strong
use cases to change it.

In my view we need to change a lot more things about the format as it is
not very expressive, will be looking at the options.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
