### ISSUE TITLE
network my-bridge-network not found  failed to start containers: mysql

### ISSUE THREAD

**Issue by qiunet** [moby/moby#27975]
**Description**

**Steps to reproduce the issue:**
1. Create a network name is `my-bridge-network`  with USB Network Interface. 
2. Specify my-bridge-network and Ip to a running container.
3. Close  Macbook  and push out USB Network Interface 
4. open Macbook , container is stop.  and can not start.  

**Describe the results you received:**
Error response from daemon: network my-bridge-network not found
Error: failed to start containers: mysql

`my-bridge-network ls lost , but can not create same.`
````
docker network create -d bridge  --ip-range=172.25.16.0/24 --subnet=172.25.0.0/16  my-bridge-network
Error response from daemon: cannot create network bcff0138eb4a12e3e09f9a0ae32e1a373ac9ec96e90be4f66621a74f7f4d4969 (br-bcff0138eb4a): conflicts with network 17f983edcdf593d1daf299ad8db754f8b248ab8be4539e021726aa38b631dfa3 (br-17f983edcdf5): networks have overlapping IPv4
````

**Describe the results you expected:**
Start my container

**Additional information you deem important (e.g. issue happens only occasionally):**
MacOs x 10.11.6

Create a network name is `my-bridge-network`  with usb network interface.
specify it to my container . and specify Ip address. All container is running.

Then,  Close my mac, push out usb network interface And  open mac.  Container is stoped. 
Because network is switch to Wifi.

my-bridge-network is lost , can not start my containers,  cannot create the same docker network
 with name `my-bridge-network` .

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 36
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: W7VN:JV2B:VKUB:WGMM:RRM7:VDI5:HIMP:TYPK:RAKV:FDK5:SUP5:J7ZG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 46
 System Time: 2016-11-02T01:50:11.438729997Z
 EventsListeners: 1
No Proxy: 1<�v��*.local, 192.168.*.*, 119.29.*.*, *.tencent.com, *.baidu.com
Username: qiunet
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Mac Os 10.11

**Comment by qiunet** [comment]
I try again . can not create any docker network. all return
````
Error response from daemon: cannot create network bcff0138eb4a12e3e09f9a0ae32e1a373ac9ec96e90be4f66621a74f7f4d4969 (br-bcff0138eb4a): conflicts with network 17f983edcdf593d1daf299ad8db754f8b248ab8be4539e021726aa38b631dfa3 (br-17f983edcdf5): networks have overlapping IPv4
````
can not start container. 

now I was reset my docker.

**Comment by justincormack** [comment]
Can you be more specific about how you run the container?

**Comment by qiunet** [comment]
1. docker run -d -e MYSQL_ROOT_PASSWORD=***  -h qiunet -p 3306:3306 --name=mysql qiunet/debian:mysql

2. docker run -d --name vm -h qiunet -p 40022:22  qiunet/debian:java /usr/sbin/sshd -D

3. docker network create -d bridge  --ip-range=172.25.16.0/24 --subnet=172.25.0.0/16  my-bridge-network

**Comment by orangebook** [comment]
Here is a example to create bridge Network 

``` bash
docker network create --gateway 10.199.45.200 --subnet 10.199.45.0/24 -o com.docker.network.bridge.name=br-oak --aux-address "DefaultGatewayIPv4=10.199.45.1"  oak-net
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
