### ISSUE TITLE
docker container does not resolve dns entry from /etc/hosts file

### ISSUE THREAD

**Issue by pratapsingh** [moby/moby#28066]
I have some requirement and I wanted my docker container to resolve few DNS entry from /etc/hosts file but it is not working. 

**Steps to reproduce the issue:**
1. start any simple container with below command
docker run --net=host image-1
#added dockerhost entry in /etc/hosts file as well. dockerhost entry is pointing to IP of underlying host which is hosting the containers.
or 
docker run --add-host dockerhost:10.0.0.5 image-1
2. on the prompt ping dockerhost
ping dockerhost
ping: unknown host

3. It is showing unknown host. Don't know what I am doing wrong here.

**Comment by cpuguy83** [comment]
Works for me.
What version of docker? Can you paste what `/etc/hosts` looks like?

**Comment by sanimej** [comment]
@pratapsingh unknown host response from the ping means its not able to resolve the name. Typically for name resolution `hosts` file is preferred before dns. This is controlled by the settings in the file /etc/nsswitch.conf. It should have something like, `hosts:          files dns`.

If you are using a custom image can you try it out with a stock ubuntu or centos image. What you are trying should work.

**Comment by pratapsingh** [comment]
**Docker version 1.11.2, build b9f10c9/1.11.2**
@cpuguy83 I am keeping the default /etc/hosts file entry as it ships with docker image .. I am just appending my entry at the end of /etc/hosts file using --add-hosts 
the host which is running the container have following entries 

> cat /etc/hosts
> 127.0.0.1 localhost
> # The following lines are desirable for IPv6 capable hosts
> ::1 ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> ff02::3 ip6-allhosts
> 10.0.0.5 dockerhost

@sanimej It is not the issue of nsswitch at all all the entries are fine and set to default.
