### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by zhaojigang** [moby/moby#28091]
I used serverA push image to serverB(registry:docker run -d -p 5000:5000 -v /opt/registry/:/var/lib/registry registry)
serverA:docker1.10.3
serverB:docker1.12.3
serverB:(ip:10.211.55.4)
cat /etc/docker/daemon.json
{ "insecure-registries":["10.211.55.4:5000"] }

but the error still ocurr:
<img width="989" alt="2016-11-05 16 10 56" src="https://cloud.githubusercontent.com/assets/14085645/20028639/7c0d369c-a372-11e6-82e2-5ef2e813a8b4.png">

**Comment by thaJeztah** [comment]
Can you also give the output of `docker version` and `docker info`? Is it possible you're running the Red Hat fork of Docker? That version has a lot of modified code in this area, which may be involved

**Comment by thaJeztah** [comment]
closing because this went stale
