### ISSUE TITLE
docker stats show a wrong value of block write I/O when using dd if=/dev/zero in a container

### ISSUE THREAD

**Issue by KevinTHU** [moby/moby#28114]
**Description**
when we use dd if=/dev/zero command in a centos container, like we write a 1GB file with /dev/zero for 4 times, theoritically, docker stats should show 4GB or 0GB in the block write I/O（I have not research the way docker write zero, maybe really write zero maybe not）, however it is not, the block write I/O is 9GB, and every time you redo the process above, the docker stats result is different but not the right result we think should.

**Steps to reproduce the issue:**
1. docker run -d --name=hx-test centos ping www.baidu.com
2. docker exec -it hx-test /bin/bash
3. dd if=/dev/zero of=./test.txt count=1000 bs=1M  (you can redo this for 4 times)
4. docker stats

**Describe the results you received:**
the stdout of docker stats is not right on  BLOCK I/O

**Describe the results you expected:**
the BLOCK write I/O of docker stats should be 0GB or 4GB

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 137
 Running: 14
 Paused: 0
 Stopped: 123
Images: 41
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 47.59 GB
 Data Space Total: 1.1 TB
 Data Space Available: 1.052 TB
 Metadata Space Used: 17.2 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.72 GB
 Thin Pool Minimum Free Space: 110 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: vlcp bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.6 GiB
Name: kvm-yz-dev-073-003-004
ID: CED3:DJX6:VW6I:LJLX:CEVJ:Z4L2:FYPX:KTIQ:CTO2:4JRD:U7L3:WN4L
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: zk://100.73.3.4:2181,100.73.3.5:2181,100.73.3.6:2181
Cluster Advertise: 100.73.3.4:2375
Insecure Registries:
 jdocker.me
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos7.2 pysical machine

**Comment by KevinTHU** [comment]
no one care this question?

**Comment by keyolk** [comment]
I have same issue.
I don't understand how the block i/o stats are collected. 
Seems it uses cgroup blkio interface.
Could anyone can explain why it shows like that ?

**Comment by ripcurld0** [comment]
@keyolk what `docker version` are you using?

**Comment by keyolk** [comment]
@ripcurld0  

see below
```
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:08:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:09:11 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

And I found that on overlay2, it shows well.
I also tracked cgroups blkio.io_service_bytes.
It shows same result.

**Comment by ripcurld0** [comment]
@cpuguy83 @thaJeztah WDYT?

**Comment by guods** [comment]
dd if=/dev/zero of=./test.txt count=1000 bs=1M
 if=/dev/zero is a character device，but the block I/O is a block device
so the docker stats show a "wrong" value.

**Comment by DrmagicE** [comment]
same issue: https://github.com/google/cadvisor/issues/2378

**Comment by DrmagicE** [comment]
if reduce the count number,`if=/dev/zero of=./test.txt count=20 bs=1M`, docker stats can show correct value. Maybe there are some tricky problem with cgroup?

**Comment by DrmagicE** [comment]
@KevinTHU try to add `oflalg=direct` flag with dd ` if=/dev/zero of=./test.txt count=1000 bs=1M  oflag=direct`. This work for me, but i am still confusing why `dd if=/dev/zero of=./test.txt count=1000 bs=1M && sync` is not working properly....

**Comment by KevinTHU** [comment]
@DrmagicE you are right, the result had a relation with the count of IO block when I found this problem. untill now I still have no idea above the reason of this problem, but docker still have this problem for the newest version?

**Comment by DrmagicE** [comment]
@KevinTHU Yes. In my case, docker stats show 0 write I/O after dd without oflag=`direct`, but this may not be a docker problem. Docker read the I/O metric form cgroups files: 
```
cat /sys/fs/cgroup/blkio/docker/$CONTAINER_ID 
253:0 Read 168951808
253:0 Write 4609994752  <--- not changed
253:0 Sync 4568051712
253:0 Async 210894848
253:0 Total 4778946560
Total 4778946560 
```
I compared the file before and after dd. I found the file was not changed. This problem may be relevant to how dd work and how cgroup calculate the I/O data.

**Comment by josefwilfinger** [comment]
I write to a mounted local docker volume, and these values does not change if i write onto it. This problem is already so old and not yet fixed. whats going on?

**Comment by raginigupta6** [comment]
Hi there,

I ran some DISK benchmarks using dd utility on LXD (ubuntu) container and compared it’s performance with the host Debian OS. I see a very large difference between the latency in creating files on LXD container Vs. that on the host OS. The host performs way better than LXDs. Any insights as to what is causing that? What specifics of LXD container filesystem is giving such a large overhead ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
