### ISSUE TITLE
Move duplicated unix code into a common file

### ISSUE THREAD

**Issue by mlaventure** [moby/moby#28129]
With the addition of Solaris (see #28056), a few routine were copied (almost) verbatim into the `_solaris.go` files.

This can end up being problematic as we may forget to update the Solaris version when making update to those routines as we have no CI running on Solaris (yet?).

This issue is here to prevent us to forget that these need to be deduplicated :)

**Comment by justincormack** [comment]
Much of the freebsd code is just wrong, I was going to do a cleanup but not until after 1.13 is out although I pointed out a few things on the Solaris PR. It is pretty bitrotted, as there is no CI on the daemon parts, only the cli.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
