### ISSUE TITLE
iptables MASQUERADE rules not created with iptables set to off ip-masq set to true

### ISSUE THREAD

**Issue by JimmyAstle** [moby/moby#28133]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
When a new user defined docker bridge network is created and the docker daemon has `iptables=false` and `ip-masq=true` the nat masquerade rules are not created for the user defined bridge network. This causes machines attached to this network to have no external access outside of the docker host.

***Use-Case**
We are running several containers on a single docker host and don't want Docker to automatically create iptables allow rules for all of the exposed ports for security reasons. We then manage our own iptables rules via Puppet.  Not sure if this is a bug but at the very least the documentation [https://docs.docker.com/engine/reference/commandline/dockerd/#/miscellaneous-options](url) is lacking any details when setting the `iptables` and `ip-masq` settings other then there explicit purpose. When setting `iptables` to false and `ip-masq` to true should Docker still create the masquerade rules related to the containers? I even went ahead and set `com.docker.network.bridge.enable_ip_masquerade=true` and the rules are not created. 

**Steps to reproduce the issue:**
1. Setup a Ubuntu 16.04 Server 64 bit with docker 1.12.3. For this example this server has an IP address on eth0 of 192.168.100.40 and the default gateway is 192.168.100.1. The default gateway accepts pings.
2. Set your Docker daemon with the following flags: `--ip-forward=true --iptables=false --ip-masq=true`
3. Create a new Docker bridge network: `docker network create --driver bridge --gateway=192.168.10.1 --subnet=192.168.10.0/24 --opt "com.docker.network.bridge.name"="example" example `
4. Attach and run any container image so you can issue ping commands to the network created above: `docker run -itd --network=example busybox`
5. Exec into the container and attempt to ping 192.168.100.1. 

**Describe the results you received:**
A tcpdump on the server shows packets leaving the host to the correct destination and source but the masquerade iptables nat rules are never created for the new bridge network thus ipables doesnt know were to send the original packets. When I delete the network, turn on `iptables=true`, and recreate the network the correct masquerade rules are created along with all of the rules for the exposed ports which we dont want. 

**Describe the results you expected:**
Since `ip-masq=true` I was expecting the nat masquerading rules to still be created and the exposed ports to not be created in the DOCKER chain. I didnt see anything in the documentation that mentioned the nat rules not being created with the `--iptables=false --ip-masq=true` settings in place. It would be good if the official documentation had more details in how docker is interacting with iptables on the host. At the very least if you disable iptables nat masquerade rules will not be created event though the settings are in place at the daemon and network level.

I have a workaround of adding the nat masquerade rules via puppet but is this the expected behavior? 

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /opt/data/aufs
 Backing Filesystem: extfs
 Dirs: 189
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: server..com
ID: XURH:HQYH:VWQ6:25GJ:DB2C:4RVF:B2KL:LJI3:GJ2W:ZYV7:C4T6:Z5LY
Docker Root Dir: /opt/data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
`iptables=false` means that Docker does not change do anything to iptables settings at all.

**Comment by JimmyAstle** [comment]
Thanks for the update Justin. This was the expected behavior as reported. Is it possible to add a few sentences to the documentation to save other folks from having the same issues I ran into? Maybe an additional sentence [https://docs.docker.com/engine/reference/commandline/dockerd/](url) like:   
 "`--iptables=false` prevents the Docker daemon from adding iptables rules. This also means that nat masquerade rules will also not be created when using networks other than the default bridge resulting in not external connectivity outside of the docker host"    

Or something along those lines. In my research there are a number of folks who have also had this issue and a quick blurb in the docs would have saved folks a lot of time.

**Comment by justincormack** [comment]
sure, cc @mstanleyjones  or if you want you can do a PR on https://github.com/docker/docker.github.io

**Comment by bbayani** [comment]
#dibs

**Comment by thaJeztah** [comment]
- docs were updated in https://github.com/moby/moby/pull/28607
