### ISSUE TITLE
C/R breaks existing TCP connections

### ISSUE THREAD

**Issue by Tchinmai7** [moby/moby#28159]
**Description**

I'm running Apache Traffic Server in a docker container, and the container acts as a reverse proxy to YouTube. The  certs of youtube,etc are cloned and are available in the container.
I have two hosts, and the container runs on only one host at any point of time. I'm using HAProxy as a loadbalancer to route the traffic onto the containers. TLS is terminated only at the container end and not at the load balancer. Everything works fine when I configure my browser to point to the HAproxy ip and  access youtube. Videos play smoothly. The setup is as follows

![setup](https://cloud.githubusercontent.com/assets/7880027/20091857/f865c552-a5ba-11e6-9c9b-da40522a60ef.png)

I'm trying to migrate the container from host1 to host2. 

**Steps to reproduce the issue:**
1. create the network on both hosts
docker network create -d bridge --subnet=10.10.0.0/16 criu

2. create the containers on both hosts 
docker create --name YouTube --security-opt seccomp:unconfined --network criu --ip 10.10.10.1 -p 8080:8080 -p 444:443 tchinmai7/youtube_ats:5.0

3. Checkpoint container on host1, and scp files to host2.
docker checkpoint create  YouTube c1
container_id="$(docker inspect --format="{{.Id}}" $container)"
sudo tar -czf YouTube.tar /var/lib/docker/containers/${container_id}/checkpoints/c1
scp YouTube.tar tchinmai@172.25.196.15:

4. Restore the container on host2.
dest_container_id="$(docker inspect --format="{{.Id}}" YouTube)"
sudo mkdir -p /var/lib/docker/containers/${dest_container_id}/checkpoints/c1
sudo tar xzf YouTube.tar --strip-components=6 -C /var/lib/docker/containers/${dest_container_id}/checkpoints/
docker start --checkpoint $checkpoint_id YouTube

HaProxy listens on 443: and the default backend is configured as follows

backend youtube
	mode tcp
	balance roundrobin
	server lab_18 172.25.196.18:444 check
	server lab_15 172.25.196.15:444 check

**Describe the results you received:**
When C/R is being done, the youtube video still plays. However, on looking at the TCP connections using Wireshark, it is seen that the connections are being severed and recreated.  And the Checkpoint process itself fails *sometimes* with this error
http://pastebin.com/fFANpWDN

**Describe the results you expected:**
TCP connection is maintained despite migration, and the dumping process goes smoothly.

**Additional information you deem important (e.g. issue happens only occasionally):**
mentioned above

**Output of `docker version`:**
**Host 1** 
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   8eadd43
 Built:        Mon Sep 26 08:22:26 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   8eadd43
 Built:        Mon Sep 26 08:22:26 2016
 OS/Arch:      linux/amd64
 Experimental: true

** Host 2 ** 
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   8eadd43
 Built:        Mon Sep 26 08:22:26 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   8eadd43
 Built:        Mon Sep 26 08:22:26 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**
**Host1 :**
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 31
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.77 GiB
Name: tchinmai-X9SCL-X9SCM
ID: 5VNE:SXTN:H5NE:WVUW:KZTJ:ZE2R:4HWI:53PI:MOPX:MPYB:5KWX:3AOY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: tchinmai7
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Host 2 :** 
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.757 GiB
Name: tchinmai
ID: VYLO:AN53:XQLJ:LYEY:H7FN:KPS5:3H5B:BD2O:AMWO:3FYI:5HZZ:RKDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machines running ubuntu 14.04.5 LTS 4.4.0-45-generic kernel

**Comment by Tchinmai7** [comment]
UPDATE: 
upgraded to kernel 4.8.0-040800-generic 
criu to version Version: 2.7
GitID: v2.7-154-g55573a6
docker version 
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   69efb46
 Built:        Tue Nov  8 09:46:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   69efb46
 Built:        Tue Nov  8 09:46:35 2016
 OS/Arch:      linux/amd64
 Experimental: true

Still seeing the same results.

**Comment by cpuguy83** [comment]
ping @boucher 

Not sure that restore on another server is meant to work, specifically.

**Comment by boucher** [comment]
This is definitely out of scope right now. @Tchinmai7 have you looked into p.haul? The networking bit of live migration is the hardest part, and I haven't actually accomplished it myself (though @crosbymichael has, and @xemul and @avagin can also chime in). You need to mess with iptables to keep the connection alive during the migration.

**Comment by Tchinmai7** [comment]
@boucher Would love to hear pointers on how to do so!. I've not gone through p.haul yet. will look into it!. I was also wondering if Floating an IP across the machines will keep the connection alive.

**Comment by xemul** [comment]
@Tchinmai7 we have some reading about TCP migration, you can start with this small howto: https://criu.org/Simple_TCP_pair

And yes, p.haul does this, but it's in very raw state ATM to live migrate Docker container. We and @tych0 are going to improve this in the nearest future though :)

**Comment by Tchinmai7** [comment]
@xemul I've tried this example, and I see that it requires us to pass the --tcp-established flag to Criu. Does docker do that? I've tried digging through the docker source to find it out, but i'm not able to find it.

**Comment by xemul** [comment]
AFAIK Docker doesn't do it and there's no easy way to pass custom options to it.

**Comment by boucher** [comment]
It does pass the tcp established flag (which isn't currently configurable).

**Comment by Tchinmai7** [comment]
@boucher okay, you were mentioning something about iptables right? can you tell me what kind of rules will be needed for this?  and will floating an ip across the machine make sure the tcp connection doesn't break?

**Comment by avagin** [comment]
@Tchinmai7 does the container have the same address after migration?

**Comment by Tchinmai7** [comment]
@avagin with respect to the docker overlay? It has the same ip. The host has a different one though.

**Comment by avagin** [comment]
@Tchinmai7 How containers go to internet? If they use NAT, where is it? If each host has own NAT, it is a problem, because when you migrate a tcp connection, the NAT on the send host knows nothing about it.

**Comment by Tchinmai7** [comment]
@avagin The containers are bound to the ports 444 and 8080 of the host machine. They can access the internet through the host. Both hosts are on the same local network only. I'm not sure what you mean by the NAT part.

**Comment by Tchinmai7** [comment]
I've tried to float an IP address across the machines too. Still seeing the same thing

**Comment by Tchinmai7** [comment]
Is there anyway I can make this work? @avagin @boucher @xemul
