### ISSUE TITLE
remaining issues for experimental build changes

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#28194]
Now that we are on our way to changing the experimental features from a compile time option to a runtime configuration with #26713, there is still a few more items we need to take care of before release.

In the upcoming 1.13.0 release, there will NOT be a separate experimental binary release.

- [ ] update docs explaining all the ways to enable experimental in configuration (command line option and `daemon.json`) and how to tell if they are enabled, e.g. `docker version`, and how it will not be enable-able via live reload
- [ ] update changelog about experimental changes
- [ ] update [deprecation docs](https://github.com/docker/docker.github.io/blob/949a89e6ea4d47e8306451d84752654d18c5253b/engine/deprecated.md) about experimental changes
- [ ] update experimental [instructions](https://experimental.docker.com/builds/) for manual install of static binaries

**Comment by AkihiroSuda** [comment]
linking https://github.com/docker/docker/pull/28160 to this issue ("Enable exp features by default if built with DOCKER_EXPERIMENTAL")

**Comment by andrewhsu** [comment]
fyi @tiborvass @mlaventure @thaJeztah @icecrime @vieux

**Comment by andrewhsu** [comment]
FYI, i've updated the issue description. There will not be a release of experimental binaries for the 1.13.0 GA, so no need to create work for making sure the binaries are released.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and BuildKit is now the default
