### ISSUE TITLE
[Discuss] How to get a smaller docker binary?

### ISSUE THREAD

**Issue by ibuildthehealth** [moby/moby#28200]
**Description**
As we all know, docker is getting bigger and bigger. In some scenarios, we hope to get a smaller docker binary, because the resource is limited, especially embedded systems.

Inspired by the Linux kernel, how about to make the docker be **customized** and **configurable** before compile.
* some core functions are always compiled into docker.
* some optional features can be configurable, if people do not want them, they can disable them and do not compile them.(we can use the go build tag to implement this goal)

**Any ideas are welcome**

**Comment by justincormack** [comment]
I think the first step would be some measurements, trying to determine what takes up the space and how much it is necessary (Go does not necessarily do good dead code elimination) and how much supports potentially optional features. This could be complicated as it means understanding the dependency structure.

**Comment by cpuguy83** [comment]
One way that's currently available is to set the build flags to only compile the graphdriver you need... e.g. `exclude_graphdriver_devicemapper`

**Comment by cpuguy83** [comment]
We could/should probably do the same for log drivers, which mostly rely on absolutely insanely large libraries (aws-sdk, gce-sdk, etc).

**Comment by unclejack** [comment]
Perhaps it'd be a good idea to have those log drivers as standalone binaries. This would make it easier to add new drivers and not have them around when not needed.

**Comment by thaJeztah** [comment]
Related to that; https://github.com/docker/docker/issues/18604

**Comment by stevvooe** [comment]
Note that Go 1.8 has loadable plugins coming. This would be great for graphdrivers and log drivers, at least.

Albeit, there is a cost to configurable builds: its is absurdly obnoxious for users' just trying to get things to work. This is a nightmare in the kernel and conditional compilation of language runtimes (take ssl in python, nginx modules) is no picnic, either.

**Comment by ibuildthehealth** [comment]
@unclejack ,it quite a good ideas, and @thaJeztah said that there ware performance issue if the drivers were external.

before solve the performance issue. how about to make build flags for log driver in order to compile only drivers we need.,

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
