### ISSUE TITLE
'search' API doesn't return proper result on format 'repo:tag'

### ISSUE THREAD

**Issue by madhuri-rai07** [moby/moby#28232]
**Description**
`docker search` doesn't work properly now. Below are few issues which I think can be fixed:
1. When searching for specific tag, docker doesn't return proper response.
2. There should be a way to return exact match in `search` command.
3. It fails to search image with special character in name. 

**Steps to reproduce the issue:**
1. When searching for specific tag, docker doesn't return proper response.
$ sudo docker search busybox:1
NAME                    DESCRIPTION   STARS     OFFICIAL   AUTOMATED
dmcgowan/busybox-1                    0                    
alch888/busybox-1                     0                    
mkrastev/my-busybox-1                 0  

2. There should be a way to return exact match in `search` command.
$ sudo docker search busyboxplus              
NAME                             DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
radial/busyboxplus               Full-chain, Internet enabled, busybox made...   11                   [OK]
grengojbo/busyboxplus                                                            0                    
tracker/busyboxplus                                                              0                    
cloudfoundry/busyboxplus                                                         0                    
cloudrepo/busyboxplus                                                            0                    
journera/busyboxplus-jq          radial/busyboxplus with jq 1.4 added            0                    
concourse/busyboxplus                                                            0                    
hemant24/busyboxplus                                                             0                    
doc2run/busyboxplus                                                              0                    
glestarispivotal/busyboxplus                                                     0                    
concourse/busyboxplus-tarmaker                                                   0                    
jsokel/busyboxplus-jq                                                            0                    
0xff/git                         a fork of radial/busyboxplus:git                0                    [OK]

3. `docker search` fails to search image with special character in name.
$ sudo docker search mkrastev/my-busybox-1
NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED

**Describe the results you received:**
Results are shown above.

**Describe the results you expected:**
1. When searching for specific tag, docker doesn't return proper response.
$ sudo docker search busybox:1
NAME                    DESCRIPTION   TAG    STARS     OFFICIAL   AUTOMATED
dmcgowan/busybox-1                    1          0          

2. There should be a way to return exact match in `search` command.
$ sudo docker search busybox
NAME                            DESCRIPTION                    TAG                 STARS     OFFICIAL   AUTOMATED
busybox                         Busybox base image.         latest                 852       [OK]                    

3. `docker search` fails to search image with special character in name.
$ sudo docker search mkrastev/my-busybox-1
NAME                    DESCRIPTION   TAG   STARS     OFFICIAL   AUTOMATED
mkrastev/my-busybox-1                 latest  0  

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: zun
ID: ZYIG:XJ2W:H7TE:EUF2:4F43:3WKR:ZLKK:A3WF:LUIQ:YYAT:XGBC:4O2N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by madhuri-rai07** [comment]
I am working on this patch and will submit a patch soon.

**Comment by thaJeztah** [comment]
I suspect this cannot be fixed in the docker engine, but is something that has to be changed in the Docker Hub search API. The docker engine simply forwards these search queries to Docker Hub, so for example;

```
sudo docker search mkrastev/my-busybox-1
```

sends this query to docker hub;
https://index.docker.io/v1/search?q=mkrastev/my-busybox-1&n=100

which returns;

```json
{"num_pages": 1, "num_results": 0, "results": [], "page_size": 100, "query": "mkrastev/my-busybox-1", "page": 1}
```

The relevant code is here; https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/registry/session.go#L733-L757

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
