### ISSUE TITLE
Error response from daemon: containerd: container did not start before the specified timeout (docker 1.12 + CRIU)

### ISSUE THREAD

**Issue by Tobeez** [moby/moby#28248]
I am trying to checkpoint and restore containers on different systems using the docker-checkpoint-restore branch of Boucher's fork of Docker.

However, on restore on the new system, some processes that spurn several threads like ffmpeg (from jrottenberg/ffmpeg:ubuntu) and tensorflow(from tensorflow/tensorflow) fail to restore with error:

`Error response from daemon: containerd: container did not start before the specified timeout`

The container starts  from scratch successfully, but fails to start (restore) from a checkpoint.

Other simple processes are restored successfully.
Is there a way to increase container start timeout on this build?

**Comment by cpuguy83** [comment]
We don't support C/R in 1.12 I thought?

ping @boucher

**Comment by boucher** [comment]
@cpuguy83 No, not supported in 1.12, but I imagine @Tobeez meant in some version of my branch that's identifying itself as 1.12?

But it would probably be best to first suggest trying running from docker/master in experimental mode, now that its been merged.

I don't have any ideas about the actual failure though...

**Comment by Tobeez** [comment]
Actually it's 1.13.0-dev

Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   67f607a
 Built:        Fri Nov  4 17:13:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   67f607a
 Built:        Fri Nov  4 17:13:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by boucher** [comment]
@Tobeez Have you tried restoring the same process outside of Docker to see if it works and approximately how long it might take?

**Comment by thaJeztah** [comment]
closing because this went stale
