### ISSUE TITLE
Docker and Iptables false

### ISSUE THREAD

**Issue by albertogviana** [moby/moby#28241]
**Description**

I would like to protect my container to receive unwanted calls from outside of my firewall. To avoid it, I am using for quite a while `--iptables=false`.

I built a swarm cluster running Docker 1.12.1 and setting `--iptables=false`, and it works really well. Two days ago I started a new cluster using docker 1.12.3 and setting `--iptables=false`, doesn't and it is not working like before, my containers don't have any connection to the internet.

**Steps to reproduce the issue:**
1. On Ubuntu Server 16.04
2. On `/etc/default/ufw` I set `DEFAULT_FORWARD_POLICY="DROP"`
3. Using ufw to block all the incoming traffic
4. On `/etc/docker/daemon.json` I set to
```
{ "iptables": false }
```

**Version and Info**

**Output of `docker version`:**
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 71
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 275
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: 8ssl90vurrrl1xvpquhj6xjov
 Is Manager: true
 ClusterID: ds8oce3qhx357htk5wyx7jm41
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: <my-ip>
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67 GiB
Name: vtdc01
ID: RGID:5NN5:GOR4:UGYV:DF5Z:ARDG:IFOO:OAQD:Q34E:KNTK:4VZF:INLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 1
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: bagus1cgacwskek8vwic6sibh
 Is Manager: true
 ClusterID: dei6pblv2n2bm0jwqwjaa40lo
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: <my-ip>
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: routing-api
ID: TQTZ:OYFF:RF36:AYOZ:N32E:B7FJ:WICQ:MD4X:6OHQ:HW6T:WIAN:LMYK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 139
 System Time: 2016-11-10T14:51:51.330670217Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Describe the results you received:**
- Running the version 1.12.1 with `--iptables=false` I could block the access to my container. 
- Running the version 1.12.3 with `--iptables=false` I could not connect to the internet from my container.

Then I decided to check the docker network configuration

**Output of `docker network inspect bridge` version 1.12.1:**
```
[
    {
        "Name": "bridge",
        "Id": "b5f485656c504971a8604f94a5e83c611f8faa586d4b84fafa02eaf07704139b",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**Output of `docker network inspect bridge` version 1.12.3:**
```
[
    {
        "Name": "bridge",
        "Id": "62c361fbabead290aabadb6ee02031ea656142fa293895efc19eb7983738c68b",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

I checked the iptables rules, and they are different, below you will find the output.

**Output of `iptables -t nat -L` version 1.12.1:**
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            
MASQUERADE  all  --  172.18.0.0/16        anywhere            
MASQUERADE  all  --  anywhere             anywhere             ADDRTYPE match src-type LOCAL

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-INGRESS (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:9000 to:172.18.0.2:9000
RETURN     all  --  anywhere             anywhere
```

**Output of `iptables -t nat -L` version 1.12.3:**
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  anywhere             anywhere             ADDRTYPE match src-type LOCAL

Chain DOCKER-INGRESS (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http-alt to:172.18.0.2:8080
RETURN     all  --  anywhere             anywhere 
```
I would expect that docker follows the same behavior like `1.12.1` and just to make it clear I am using docker `1.11.2` in other machines with `--iptables=false` and it is working.

One thing that is clear is that `--iptables=false` on docker version 1.12.3 is treat in a different way, and for me, this is breaking the compatibility between versions.

**Comment by thaJeztah** [comment]
ping @aboch PTAL

**Comment by aboch** [comment]
@albertogviana 

I don't think the `--iptables=false` setting has ever taken effect. The output of your iptables in both 1.12.1 and 1.12.3 shows that docker had programmed your iptables.

From your network inspect on 1.12.3, this field has changed to false from true:
`"com.docker.network.bridge.enable_ip_masquerade": "false",`
in fact we see docker has not programmed the MASQUERADE rules in the POSTROUTING chain, as it did when you were using 1.12.1.
Did you add the `--ip-masq=false` option recently ?

**Comment by albertogviana** [comment]
Hi @aboch,

After I ser up iptables as false, the ip-masq was false and even if I set as true it didn't change.

**Comment by aboch** [comment]
My guess then is that things were working because of the stale nat rules you had from a previous docker daemon run in which iptables was not disabled.

The you may have restarted the machine (is that the case?) and your containers could no longer rely on those rules therefore cannot talk to the outside.

AFAIK nothing has changed in the iptables programming / iptables flag processing across the 1.12.x releases.

If you start your daemon with the `-D` debug flag, from the log it will be clear whether `--iptables=false` was effectively accounted. I can take a look at the logs if you can collect them.

Thanks

**Comment by albertogviana** [comment]
All machines have a fresh installation and haven't upgrade the docker there. I will collect the log for you. I restarted the machines many times and in the version 1.12.1 still work.

**Comment by albertogviana** [comment]
Hi @aboch,

Here is the log files for both versions [1.12.1](https://gist.github.com/albertogviana/a65eeb44bd958eaf01c52ebc9198304c) and [1.12.3](https://gist.github.com/albertogviana/3b676e36f9660ef5a20d9de5e7dd87ea) as you asked.

**Comment by aboch** [comment]
Ah you are using swarm services. It looks like the daemon option `--iptable=false` is not respected for that.  This explains why we see docker rules in your iptables.

Nevertheless, iptables programming is needed for your tasks to be reachable.
As a side note, maybe we should block the service deployment on the host if iptables==false.
As of now that flag only affect the bridge driver, which may not be what the user expect.

But I see there were behavior changes between 1.12.1 and 1.12.3 around iptables programming around services: A DOCKER-INGRESS chain was added in the filter chain by https://github.com/docker/libnetwork/pull/1398.
@sanimej would know more about this, if that change may have to do with your use case stop working.

After 1.12.1 many fixes around networking were added and sometime they also blocked some use cases which were unintentionally working.

**Comment by thaJeztah** [comment]
ping @sanimej PTAL! Can you confirm if this is a bug, or if @albertogviana was relying on a previous bug that has now been resolved?

**Comment by albertogviana** [comment]
Hello @aboch and @sanimej ,

Sorry to disturb, but do you have any news about this ticket? Is it going to be an issue?

Thank you

**Comment by or-shachar** [comment]
I understand this is not a bug but I wish docker would offer different configuration for "iptables-inbound" and "iptables-outbound". Because while I don't want docker to play with my firewall for inbound communication - I do want it to play  for outgoing communication.

**Comment by lenovouser** [comment]
I have the same issue and think that @or-shachar's Idea is pretty good

**Comment by stychos** [comment]
For now it is near impossible to restrict inbound connections for published Swarm Services, because of DOCKER-INGRESS recreates every time Docker daemon restarts (I need to allow connections only from selected IP addresses). I forced to use the cron job, periodically updating nat rules, is there some way to implement this without crunches?

**Comment by thaJeztah** [comment]
@or-shachar @stychos @lenovouser please open a new issue / feature request for that discussion, it's orthogonal to this issue.

**Comment by edouardKaiser** [comment]
Maybe related or not, but since we moved to Docker 1.12.3, the iptables are different. No more `DOCKER-ISOLATION` chain in the filter table. Neither the one regarding docker0 (eg: `ACCEPT     all  --  docker0 !docker0 anywhere anywhere`)

We're running on CoreOS 1235.4.0. Any option to get that behaviour back?

**Comment by clems4ever** [comment]
I have the same issue as @stychos. I will use the cron solution he is proposing however it would be nice to be able to add custom rules before DOCKER-INGRESS rules and keep them after a restart. Is there anything in 1.13 that could fix this?

**Comment by wenjianhn** [comment]
@clems4ever I have sent a pull request to fix this issue.

https://github.com/docker/libnetwork/pull/1675

**Comment by clems4ever** [comment]
Thank you @wenjianhn!

**Comment by thaJeztah** [comment]
- related https://github.com/moby/moby/issues/46467
Let me close this ticket for now, as it looks like it went stale.
