### ISSUE TITLE
Multiple images with the same name and Docker remote API

### ISSUE THREAD

**Issue by manast** [moby/moby#28303]
I have tried to find an old issue regarding what I am going to expose below but couldn't find any.

My issue is that, sometimes, untagged images (not sure if this can also happen for tagged ones), can have the same the name as others while being different images. Besides being confusing when doing ```docker images```, it also introduces a weird behaviour on the 'inspect image' remote api:
```GET /images/(name)/json```
Because it returns one random image, instead of an array or all the images with the same name. A workaround for this in some situations is to use the imageId, but in my case I am building a deploy tool that first checks if a given image is present, and a label with a github sha, and if not present or different sha, it builds it and updates the service. However, since I have multiple images with the same name, it often happens that the deploy tool gets one of the old images, and therefore decides it needs to build and update the service while in reality it shouldn't need to.

Any comments?

**Comment by cpuguy83** [comment]
You cannot have multiple images with the same name.
An image name consists of a repo and a tag, these are unique. If you try to name an image the same name as an existing one, the name from the old image will be removed and applied to the new image.

**Comment by manast** [comment]
so you mean that something like this should be impossible?
```
registry.example.com/template-builder   latest              99fa76d0136d        About an hour ago   904.9 MB
registry.example.com/template-backend   latest              4b5fb0f5bbcc        About an hour ago   718.3 MB
registry.example.com/template-backend   <none>              2ec4c1a71071        2 hours ago         718.3 MB
registry.example.com/template-backend   <none>              4e28a1426346        3 hours ago         718.3 MB
registry.example.com/template-backend   <none>              7d1d7414f863        3 hours ago         718.3 MB
registry.example.com/template-builder   <none>              8d8b18009a58        4 hours ago         904.9 MB
registry.example.com/template-backend   <none>              395c7b2a1af7        4 hours ago         718.3 MB
```

because that is exactly what I get when I do ```docker images``` ...

**Comment by cpuguy83** [comment]
So it looks like you tagged a new image with an existing tag, thus untagging the existing one.
What you have is multiple images with the same repo and with no tag associated with them.

The inspect endpoint cannot (must not) return an array. It could be argued that it should not return anything if there are multiple matches (which we do for containers since you can lookup by id/name prefix).
If you'd like an array, then hitting the `docker images` endpoint with a filter is probably what you are looking for.

**Comment by manast** [comment]
yes, I fully agree that inspect should not return an array, but for that to be consistent, it should be impossible to have several different images with the same name, don't you agree?

**Comment by thaJeztah** [comment]
> it should be impossible to have several different images with the same name, don't you agree

I think the confusion here is that what you call an "image", is actually a _repository_. For example, `registry.example.com/template-builder` is a _repository_, not an _image_. A _repository_ can contain multiple images, and those images can be tagged.

For images that are _untagged_, you can still reference those images by _digest_,
for example:

    docker run -it --rm ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

> I have also managed to have images with the same name and tagged with latest... should this be reported as a bug?

Do you have a way to reproduce that? That doesn't sound right indeed

**Comment by manast** [comment]
@thaJeztah ok. Thanks for the explanation. I have understood that a repository contains different images with the same name and different tags, that makes sense. But the problem I see is that if I have a repository of images, and I use the remote api to inspect one image by name, I get an undefined response, I cannot now which image I am getting, this gets of course acerbated by the strange situation where I have several images with the same tag. I don't know how I did get to that situation, but I will be more observant to see if I can find a way to reproduce it.
Maybe a solution is to return an error if you inspect an image by name and there are several, then either you provide a tag or an imageId, at least the user will understand something is wrong and she gets a change to fix it.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
