### ISSUE TITLE
Should -i be default for docker run and exec?

### ISSUE THREAD

**Issue by AndreKR** [moby/moby#28315]
Without `-i`, stdin doesn't work with `docker run` and `docker exec`:

`docker run -i alpine cat < /etc/hostname` prints the hostname of the host
`docker run alpine cat < /etc/hostname` does nothing

I wonder if there is any situation where you would *not* want to specify `-i`, otherwise it should just be the default (and the flag removed).

**Comment by bfirsh** [comment]
See also: https://groups.google.com/d/msg/docker-dev/1nfuQFnki4k/wpQdoH5r2lUJ

**Comment by justincormack** [comment]
It does make a difference with some other flags eg `docker run -id busybox sh` is very different without the `-i`.

**Comment by AndreKR** [comment]
@justincormack Can you elaborate? What is the difference, what would `docker run -d busybox sh` used for?

**Comment by justincormack** [comment]
One waits for input, which can be attached later, the other exits
immediately.

**Comment by bfirsh** [comment]
Indeed, lots of stuff behaves differently, so this would be a backwards incompatible change.

I suppose a better way of framing this proposal is: is `-it` the thing users _usually_ want? If so, it should be enabled by default, and there should be an option to disable it (similar to how `-T` disables TTY in openssh).

**Comment by AndreKR** [comment]
Yeah, but what would be the purpose `docker run -d busybox sh`? My allegation was that absolutely nobody would be using `docker run` anywhere where `docker run -i` wouldn't work. Might not be true, that's why I'm asking.

`-t` is a totally different beast, because it breaks stdin:

`# docker run -i alpine cat < /etc/hostname` works
`# docker run -it alpine cat < /etc/hostname` prints `the input device is not a TTY`

**Comment by bfirsh** [comment]
@AndreKR See the Google Groups thread I linked to. OpenSSH auto-detects whether `stdin` is a TTY, which is what I'm proposing we adopt.

**Comment by AndreKR** [comment]
@bfirsh I support that proposal, but I think it is independent from the scope of this issue - this is about getting rid of `-i` because it is apparently useful in zero cases.

**Comment by bfirsh** [comment]
Agreed that TTY is out of scope, but I would disagree that we get rid of `-i`.

As @justincormack points out, there are cases where commands behave differently depending whether `stdin` is available or not. This is clearly an unusual use-case though, so I would propose:

1) We enable `stdin` by default
2) Replace `-i` with `-I`, which _disables_ `stdin`.

This makes `docker run` easier to use for the vast majority of users who want `stdin` by default, but still keeps the ability to disable `stdin` for the few people who want that.

**Comment by AkihiroSuda** [comment]
This doesn't seem going to be implemented.

I'm closing but feel free to continue discussion.
