### ISSUE TITLE
Swarm Mode: Overlay networks intermittently stop working

### ISSUE THREAD

**Issue by JoelJ** [moby/moby#28325]
**Description**

I'm running a docker swarm cluster. Running Centos7 with the LTS kernel. They're brand-new machines. I've been deploying and updating services for about an hour (iterating on testing changes). I have one overlay network I created that I just called `app` and everything communicates over the network `app`. So config for all my containers has `someotherapplocation=someother.app` for example.

I have three nodes in the swarm: two workers, one master. After about an hour, the two workers started giving me the error "network `app` doesn't exist". However, `docker network ls` shows the overlay network `app` on all nodes. However, no DNS names resolve on existing containers on the working nodes. And eventually they all crash out and swarm restarts them and fails because the above error. 

**Steps to reproduce the issue:**
1. Create a swarm
2. Start services, make sure you have services on each node all using the same overlay network, update them. Wait and hope you get lucky
3. Observe that the workers can no longer use the `app` network

**Describe the results you received:**
See above

**Describe the results you expected:**
I expect overlay networks to work in Swarm Mode

**Additional information you deem important (e.g. issue happens only occasionally):**
Intermittently happens. I am running on EC2 all on the same VPC, same Subnet, same Security group. But I have seen this happen locally as well with local kvm machines on my dev workstation.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 1
 Paused: 0
 Stopped: 16
Images: 4
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 70ycgf7413u2l39ts9f69dxxg
 Is Manager: false
 Node Address: 10.33.11.19
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.31-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-10-33-11-19.blah.us.example.com
ID: UJQH:47E5:BBZX:MZDZ:RS7D:MSFG:G4RJ:P56T:M3P2:RZXF:5GJR:UZA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 com.example.region=ca
 com.example.country=us
 com.example.hostname=dockerswarmtest-11-19-joeljohnson
 com.example.domain=dockerswarmtest-11-19-joeljohnson.ca.us.example.com
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, also have seen using Vagrant + libvert + kvm

**Comment by JoelJ** [comment]
I wanted to point out as well: If I remove all services, then remove the network, then restart them all, it works again. But this will obviously not work in a production environment, which is what I'm prepping to set up.

**Comment by aaronlehmann** [comment]
ping @mrjana @mavenugo

**Comment by manast** [comment]
@JoelJ I am having the same issue after upgrading from 1.12.1 to 1.12.3. In my case I can ping the services from one container to another but if I try to curl the service via domain or even IP it just times out. I have different services in the overlay network and this issue can intermittently happen on any of them (or all of them).

Is there any documentation on how to debug the routing mesh? If I can gather more information about what is going behind the scenes it would be easier to understand the problem.

**Comment by mrjana** [comment]
@JoelJ @manast Can you provide `docker service ps` dump for the services which are having the problem. Also daemon logs from the nodes which are having a problem with any service will be helpful.

**Comment by manast** [comment]
I have checked the logs in the docker daemon that is running the container that is not reachable and there really is no useful info. I can bash enter into one of the containers that are in the same network as the unreachable container, and when I curl it it just hangs and times out after some time. The logs do not show anything at all regarding this access. My guess is there are more logs that handle the rounting mesh where we may find more useful information, do you know where those are?

**Comment by dalefwillis** [comment]
+1 on this, I've been experiencing it for a while but was unable to reliably recreate it (should have just posted anyway)... I have found that I experience this issue in two different cases:

1) while using an overlay network (ie. adding `--network proxy` option on service creation, after creating a `proxy` overlay) I find that it actually happens to me quite often, so much so that I couldn't use the system in production without a script to check for failures and burn down the cluster and restart it.

2) I have also tried my services without the `--network` option my containers can access each other just fine even without an overlay network (not sure if this is expected behavior - if an overlay is designed to let containers in a swarm communicate but they can without it, then am I missing something??) 

Both of these cases I've been dealing with for a few weeks in a cluster on AWS using `docker-machine` to setup the cluster, I can provide more details just let me know what you would like to see. I'm using docker 1.12.3

**Comment by soar** [comment]
I have same issue. It was on 1.12.3 and after upgrade to 1.12.4 - all the same. Containers in overlay network see each other 2-3 hours and then lose connections randomly.

**Comment by fantix** [comment]
The same here, Docker 1.12.6 on Ubuntu 16.04 in AWS. 

Services access each other by service name as host address. For example, NGINX accesses uWSGI Python servers by `uwsgi_pass api_staging:3031;`, and Python server accesses PostgreSQL by `SQLALCHEMY_DATABASE_URI=postgresql://xxx:xxx@pg_staging/xxx`, where `docker service ls` looks like:

```
ID            NAME            REPLICAS  IMAGE                                                                                                     COMMAND
2q3s53ahuxcp  pg_staging      1/1       ...
891qfjfxjwpo  web_staging     2/2       ...
d83kxfzdlozv  api_staging     8/8       ...
```

All services are attached to this overlay network:

```
NETWORK ID          NAME                DRIVER              SCOPE
...
duz304pwarm9        staging             overlay             swarm               
```

Logs are using driver `awslog`, some typical errors looks like this:

```
## NGINX to Python
10.255.0.3 - xxx [16/Jan/2017:08:25:25 +0000] "GET /xxx/xxx/ HTTP/1.1" 502 575 "https://xxx.xxx.xxx/xxx/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" "xxx.xxx.xxx.xxx"

## Python to PostgreSQL
psycopg2.OperationalError: server closed the connection unexpectedly
```

Meanwhile, AWS load balancer loses the NGINX services from time to time too, with `504 Gateway Time-out`.

**Comment by savayg** [comment]
@fantix did you find any solution? same issue here and I'm considering to switch to plain docker engine with host mode to overcome this issue

**Comment by fantix** [comment]
@savayg Negative, we fall back to non-Docker solution as the system is not big yet. I'm not sure what QingCloud did has anything to do with this issue, perhaps it is worth a look: https://www.qingcloud.com/sdn_passthrough  @Xuanwo @osier @Sunight

**Comment by thaJeztah** [comment]
ping @mavenugo @aboch PTAL

**Comment by dutchakdev** [comment]
@JoelJ pls, try:
`sudo rm -rf /var/lib/docker`

or this flow:
`$ sudo service docker stop
$ sudo rm -rf /var/lib/docker
$ sudo service docker restart`

**Comment by fluder** [comment]
I also experinecing this problem. Some containers randomly become unavailable from random containers. The workaround solution i found is to run new container with ubuntu and just ping container that stopped to work.

**Comment by gablank** [comment]
We are also seeing this issue. Running a setup with three managers and two workers. Some of the machines we use have two network interfaces. We're also using VLANs.

Hoping for a fix to this issue, as this is really a deal breaker for using Docker Swarm Mode in production.

**Comment by stefanfritsch** [comment]
I experience the same problem. I try docker swarm now and then but I always had to backtrack because networking simply isn't working reliably.

**Comment by mattlqx** [comment]
Running into a similar problem where creating an overlay network on the swarm doesn't create it on the workers and as such any service with that new network specified is unable to be scheduled. The unreliability of this is a huge blocker.

**Comment by krjensen** [comment]
We are seeing the same problem. 
We deploy a stack across 5 worker nodes but when/if the docker daemon restarts, 3 out of 5 nodes looses the swarm overlay network.

To recover I do the following:
````
$ sudo service docker stop
$ sudo rm -rf /var/lib/docker
$ sudo service docker restart
Re-join the worker to the swam and the network will be created when the service schedules a container on the worker. 
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
