### ISSUE TITLE
docker stop should give a proper error on container in "Created" state instead of success

### ISSUE THREAD

**Issue by dattatrayakumbhar** [moby/moby#28331]
**Description**
If we ran 'docker stop' on container in "Created" state it runs without any failure however it actually
does not take any affect as its in "Created" state
If it does not take any affect then it should give proper error

**Steps to reproduce the issue:**
1. Create a container 
   docker create --name test busybox
  
    docker ps -a
   CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
   128630add359        busybox             "sh"                23 seconds ago      Created                                 test

2. Kill container in #1
   docker kill 128630add359
   Error response from daemon: Cannot kill container 128630add359: Container 128630add3593a41423b9f0ca91b6760d8610e5bdc502448d2c0aa5c15e0fe5c is not running 
	
2. Stop containr in #1
   docker stop 128630add359
   128630add359

![image](https://cloud.githubusercontent.com/assets/21226676/20235979/cb2053de-a8c9-11e6-90fa-266969ac1aa9.png)

**Describe the results you received:**
"Docker kill" did not work and gave proper error as conatiner not running.
"Docker stop" worked without error however it did not affect container as its s stopped state.

**Describe the results you expected:**
Docker stop should not work on container in "Created" state and should give a proper error like 'container is not running' as it gives for docker kill

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `docker version`:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 94
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: datta-bastion-dns.cisco.com
ID: 7ZBB:T5UR:R7FN:ZMZS:DG4R:26W5:GOW7:5CV4:CDCE:GQ54:LVXV:OQPK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dattatrayakumbhar04
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by allencloud** [comment]
In this case, docker returns a status code of `StatusNotModified(304)`.
In another case, docker start an already started container also returns 304.
```
root@ubuntu:~# docker kill 108
108
root@ubuntu:~# docker start 108
108
root@ubuntu:~# docker start 108
108
```

In both above case, although code like this, seems to return an error.:
```
        if !container.IsRunning() {
		err := fmt.Errorf("Container %s is already stopped", name)
		return errors.NewErrorWithStatusCode(err, http.StatusNotModified)
	}
```
or in daemon/start.go
```
	if container.IsRunning() {
		err := fmt.Errorf("Container already started")
		return apierrors.NewErrorWithStatusCode(err, http.StatusNotModified)
	}
```
However client side will not get an error, then cli get no error but display the container id.

I was wondering if there is something related with the status code dealing in the http middleware.

**Comment by yongtang** [comment]
In HTTP restful APIs, `2xx` and `3xx` are typically considered as `No Error`. I am wondering if that should be taken into consideration?

**Comment by dattatrayakumbhar04** [comment]
I have raised a pull request where I have made changes as 
https://github.com/docker/docker/pull/28332
Made below change:
     if container is not running and its in created state then give error as "container is not running "

docker stop 18
docker stop 18
if container stopped which is stopped state then it gives proper error that container is already is stopped state. 

@allencloud , Please let me know it looks good ?  how do I need to check with http error code change

**Comment by allencloud** [comment]
Great, Thanks for your information. It is really helpful. If 3xx is as no error, then some related code are not proper to construct an error @yongtang

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
