### ISSUE TITLE
Docker Start Hangs

### ISSUE THREAD

**Issue by arciisine** [moby/moby#28364]
**Description**
I have a program that is maintaining a pool of containers, and it does so by running 
```
docker create --name=<container> -it -v <local folder>:<internal dir> -w <internal dir> /bin/sh
docker start <container>
```
to initialize the container and by running 
```
docker kill <container>
docker rm -vf <container>
```` 
to destroy the containers as needed.  Once created I call `docker exec <container> <cmd>` to send commands to the container

After running this program for a period of time (with everything working properly), `docker start` will hang without actually running the container.  

It looks like there is a lock that is being waited on, that never finishes.

**Steps to reproduce the issue:**
1.  `docker create/start`
2.  `docker kill/rm`
3. Repeat until `docker start` fails

**Describe the results you received:**
`docker start` fails to complete, and `docker ps` as well as `ps` indicate no new containers are running.  

**Describe the results you expected:**
The container should start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 9
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: W5AD:EWCG:RHC3:3MWN:O33Y:6HWD:QQM7:DOKL:WNWK:Z3RV:F5ZC:5HIX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-11-13T05:45:30.88393807Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Restarting the docker server resolves the issue immediately.

**Comment by tonistiigi** [comment]
@arciisine Thanks for the report. Could you send `SIGUSR1` signal to the dockerd process while the hang happens and copy stacktrace that is printed to the logs.

**Comment by arciisine** [comment]
I'm attempting to kill the dockerd process, and I'm seeing some really odd behavior.
```
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1094: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1099: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1104: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1109: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1114: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1119: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1124: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1129: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1134: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1139: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1144: No such process
osx-mbp:rest user$ ps aux |grep dockerd | awk '{print $2}' | xargs kill -s SIGUSR1
kill: 1149: No such process
osx-mbp:rest user$
```

Basically by the time the system attempts to kill the process, it looks like it has already died and is moving onto the next pid.  I've yet to be able to actually kill the dockerd.  I also attempted to use pkill to no avail.

**Comment by tonistiigi** [comment]
@arciisine `ps aux | grep dockerd` probably matches the `grep` command as well and this is the process that has died.

**Comment by tonistiigi** [comment]
@arciisine What version of docker are you running? If it's an older version then the process you are looking for is is `docker` process with `daemon` subcommand.

**Comment by arciisine** [comment]
I'm running 
```
Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```
and this is on OSX.

**Comment by tonistiigi** [comment]
@arciisine On osx you can use `docker run --rm --pid=host busybox sh -c "kill -s sigusr1 \$(pgrep dockerd)" . The trace should be in `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/docker.log`

**Comment by arciisine** [comment]
[gostack.txt](https://github.com/docker/docker/files/594908/gostack.txt)

I've uploaded the stack trace which is when `docker start <container>` is running and hanging.

**Comment by tonistiigi** [comment]
In this trace there is one goroutine that is in the middle of starting a container, but it doesn't quite show if it is actually blocked as that goroutine has been running for less than a minute. That goroutine is in the middle of running `fsync` syscall.

@justincormack Any docker4mac specific issues that could cause `fsync` to block while writing the container config file under `/var/lib/docker`?

**Comment by thaJeztah** [comment]
ping @justincormack @dsheets ^^

**Comment by arciisine** [comment]
Wondering if there was any update on this, or there is anything else I can add to assist with the process.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
