### ISSUE TITLE
Healthcheck cli arguments CMD vs CMD-SHELL

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#28385]
`HEALTHCHECK` supports `CMD` and `CMD-SHELL` as command to run. `CMD-SHELL` make docker prepend the healthcheck command with `/bin/sh` (hard-coded in the source code) — This makes it not work with some images that would not have a `/bin/sh` inside (like `traefik` or `swarm` or …).

This is ok, but any healthcheck `cli` flag (for `run` or `service create/update`) is only using `CMD-SHELL`. This makes it impossible to set a custom healthcheck for any image that do not provide a `/bin/sh` binary inside the image.

I think we should either do the other way around (i.e. using `CMD` by default on cli flags) or find a way to detect/specify if it should use `CMD-SHELL` or `CMD`.

Note that on `docker build` the use of `CMD` and `CMD-SHELL` is set depending on whether the `HEALTHCHECK CMD` is specified as a string or an array. We're also gonna do the same for `compose` (both here and in docker/compose)

/cc @thaJeztah @aanand @dnephin @talex5

**Comment by justincormack** [comment]
It should use the `SHELL` setting that we already have to customise the shell, not hardcoded. Probably got missed when that was switched.

**Comment by thaJeztah** [comment]
Do we have some way to set "`SHELL none`"? I think that's what's needed in this case (IIUC)

**Comment by talex5** [comment]
What would the syntax be for specifying a command without using a shell? JSON on the command-line? `docker run --health-cmd '["/myprog"; "--foo"]'`? The quoting gets a bit exteme...

**Comment by justincormack** [comment]
We don't allow specifying json on command line, yeah its not nice.

**Comment by vdemeester** [comment]
@talex5 yeah that's the tricky part… I would tend to only use `CMD` via the command line (and let people use `sh -c` if they want the shell 👼).

@justincormack yep this is an orthogonal issue, but using the defined `SHELL` would be nice, I'll prepare a PR on that.

**Comment by vdemeester** [comment]
https://github.com/docker/docker/pull/28438 for using the Container configured shell instead of hardcoded ones.

**Comment by wolverian** [comment]
This doesn't look solved yet - at least I don't see how to specify on the CLI to not use a shell at all.
