### ISSUE TITLE
permissions broken after chown in overlay2

### ISSUE THREAD

**Issue by snth** [moby/moby#28391]
Similar to this #20240 and #24913 but overlay2 instead of `aufs` and `overlay`.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 1.12.3
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.48 GiB
Name: aam-inv-tb1
ID: Q7SH:ZX2R:YBQB:S5O6:327O:XBYL:G2MI:JS52:7XJ6:7TMH:ATBE:6BNT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 registry:5000
 127.0.0.0/8
```

**Output of `uname -a`**

```
$ uname -a
Linux aam-inv-tb1 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical machine running Ubuntu 14.04

**Comment by thaJeztah** [comment]
Could you include the steps to reproduce, to have all information available in this issue?
Also, if you have a machine available for testing; could you try the 1.13.0-rc1 release candidate? Some fixes have gone into that release for overlay2, and one of those works around a kernel bug for some kernel versions that haven't been patched yet

**Comment by snth** [comment]
Thank you for your reply @thaJeztah. Unfortunately I won't be able to create a reproducible example or try the 1.13.0-rc1 version. However interestingly on my Ubuntu 16.04.1 box it works and the error doesn't show up.

Details for the working setup below: 

**Output of `docker version`**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 1.12.3
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.851 GiB
Name: aamsvr10
ID: KGCG:TRSV:OHB5:CR7T:7TNB:WV6H:MAWH:YCNE:K2F5:V3IK:GWED:EL3I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 registry:5000
 127.0.0.0/8
```

**Output of `uname -a`**

```
Linux aamsvr10 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
>  However interestingly on my Ubuntu 16.04.1 box it works and the error doesn't show up.

Interesting, as it's saying it's the same kernel version.

@dmcgowan any ideas?

**Comment by snth** [comment]
Hi,

So the following example reproduces it for me and fails on the last step of the build with `overlay2`:
```
mkdir overlay2_bug && cd overlay2_bug
mkdir -p a/b && echo "hello" > a/b/file.txt
chmod o-rwx -R .
(cat <<'EOF'
FROM ubuntu:14.04
COPY . /opt
RUN adduser test
RUN chown test -R /opt
USER test
RUN cat /opt/a/b/file.txt
EOF
) > Dockerfile
docker build .
```

Using `overlay` it builds fine. Still only on the Ubuntu 14.04 machine with the details as above.

**Comment by dmcgowan** [comment]
@snth are you still only able to reproduce this on one machine? Also if you build with `docker build --no-cache .` on that machine are you getting the same result. Tried a couple different kernels and unable to reproduce, do you mind adding a command for `RUN id && ls -l /opt/a/b/` right before the `cat` line and sending the output.

**Comment by snth** [comment]
I couldn't `ls -l /opt/a/b` because that also generates a `Permission Denied` so I did `ls -l /opt/a`.

Here's the output:

**Output**
```
$ docker build .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM ubuntu:14.04
 ---> 1e0c3dd64ccd
Step 2 : COPY . /opt
 ---> feda80648121
Removing intermediate container 82a83d234604
Step 3 : RUN adduser test
 ---> Running in 03b264831adc
Adding user `test' ...
Adding new group `test' (1000) ...
Adding new user `test' (1000) with group `test' ...
Creating home directory `/home/test' ...
Copying files from `/etc/skel' ...
Enter new UNIX password: Retype new UNIX password: passwd: Authentication token manipulation error
passwd: password unchanged
Use of uninitialized value $answer in chop at /usr/sbin/adduser line 563.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 564.
Try again? [y/N] Changing the user information for test
Enter the new value, or press ENTER for the default
        Full Name []:   Room Number []:         Work Phone []:  Home Phone []:  Other []: Use of uninitialized value $answer in chop at /usr/sbin/adduser line 589.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 590.
Is the information correct? [Y/n]  ---> 21e1a6de87e6
Removing intermediate container 03b264831adc
Step 4 : RUN chown test -R /opt
 ---> Running in 65ff55d4a756
 ---> f063d19d8d4a
Removing intermediate container 65ff55d4a756
Step 5 : USER test
 ---> Running in 4bcd602b2141
 ---> 68e9a55b6eb8
Removing intermediate container 4bcd602b2141
Step 6 : RUN id && ls -l /opt
 ---> Running in fc2d6c9521d9
uid=1000(test) gid=1000(test) groups=1000(test)
total 8
-rw-rw-r-- 1 test root  145 Nov 16 08:04 Dockerfile
drwxrwx--- 1 test root 4096 Nov 15 13:29 a
 ---> ecc5354b03ee
Removing intermediate container fc2d6c9521d9
Step 7 : RUN ls -l /opt/a
 ---> Running in 534addb309db
total 0
d????????? ? ? ? ?            ? b
ls: cannot access /opt/a/b: Permission denied
The command '/bin/sh -c ls -l /opt/a' returned a non-zero code: 1
```

**Dockerfile**
```
FROM ubuntu:14.04
COPY . /opt
RUN adduser test
RUN chown test -R /opt
USER test
RUN id && ls -l /opt 
RUN ls -l /opt/a
RUN cat /opt/a/b/file.txt
```

**Host directory contents**
```
$ pwd && ls -lR
/home/tobias/docker/overlay2_bug
.:
total 8
drwxrwx--- 3 tobias tobias 4096 Nov 15 15:29 a
-rw-rw-r-- 1 tobias tobias  129 Nov 16 09:56 Dockerfile

./a:
total 4
drwxrwx--- 2 tobias tobias 4096 Nov 15 15:29 b

./a/b:
total 4
-rw-rw---- 1 tobias tobias 6 Nov 15 15:29 file.txt
```

**Comment by snth** [comment]
As I pointed out right at the beginning, I first had this issue on `aufs` and my problem was identical to #20240.

Then I started reading about the docker `storage-drivers` and tried switching to `devicemapper`, `overlay` and `overlay2`. `overlay2` is the fastest for me and looks like the best option so I would like to use that but currently I'm stuck with `overlay` because of this bug.

I'm only having this problem on the Ubuntu 14.04.5 LTS box, it works on my Ubuntu 16.04.1 LTS machine.

The `--no-cache` option makes no difference.

Because I have to keep switching back and forth between storage drivers I have also deleted the `/var/lib/docker/{aufs,devicemapper,overlay2}` directories and cleared out all images for `overlay2` with `docker rmi $(docker images -aq)`.

**Comment by AkihiroSuda** [comment]
I can hit the issue (https://github.com/docker/docker/issues/28391#issuecomment-260642494) on Ubuntu 16.04 with the master Docker daemon.

Also, confirmed that I can hit the issue on overlay2 but not on overlay.

```console
$ docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 319
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ws01
ID: SN3T:CNK6:JKQD:54CY:XKF2:BRX3:CIRU:DQBT:6DVZ:VWQ2:Q5ET:F23L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 30
 System Time: 2016-11-25T06:24:16.051658103Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```console
$ docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   b8e3a28
 Built:        Fri Nov 25 06:21:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          b8e3a28
 Built:               Fri Nov 25 06:21:47 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

I'll try to look into this issue

**Comment by AkihiroSuda** [comment]
Similar to https://github.com/docker/docker/issues/24913#issuecomment-240666349, I can hit the issue with kernel v4.5.7(vanilla) but cannot hit the issue with v4.6(vanilla).
So probably the bug has been fixed in v4.6.

@snth Can you please try to reproduce again on 16.04 machine? If your kernel is older than v4.6, I think it should hit the issue.

**Comment by thaJeztah** [comment]
Adding this to the 1.13 milestone; we should check if this is an issue, because we promoted the overlay/overlay2 driver in 1.13

**Comment by andrewmichaelsmith** [comment]
I think we're seeing similar issue but in 4.8, so I don't think this is fixed in 4.6.

My reproduction is pretty simple, when I try and delete any file it goes in to the funky permission mode:

```
sudo docker run -ti centos bash -c "rm -f /etc/yum.conf && ls -alFh /etc | grep yum.conf"
ls: cannot access /etc/yum.conf: No such file or directory
??????????  ? ?    ?       ?            ? yum.conf
```

```
Containers: 69
 Running: 4
 Paused: 0
 Stopped: 65
Images: 121
Server Version: 1.12.3
Storage Driver: overlay2
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.10-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.72 GiB
Name: gnl-jenkins2
ID: 6LZ7:WGNN:7GS6:EF22:ITS7:NRKP:WWSC:OUOT:A6XI:IDNC:RKFE:RXOV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Comment by andrewmichaelsmith** [comment]
I can confirm that downgrading docker (sudo yum downgrade docker-engine) to docker 1.12.2 fixes this bug. So this bug appears to have been introduced in 1.12.3.

**Comment by thaJeztah** [comment]
@andrewmichaelsmith if this is a test host, could you try if you're having the same issue on 1.13.0-rc2? https://github.com/docker/docker/releases

**Comment by AkihiroSuda** [comment]
@andrewmichaelsmith 
I couldn't hit your issue in my 1.13.0-rc2 environments (vanilla kernel 4.5.7 and 4.6, on Ubuntu 16.04).

Probably your issue is different from the original one?

Can you hit the original issue with https://github.com/docker/docker/issues/28391#issuecomment-260642494 ?

**Comment by AkihiroSuda** [comment]
For the original issue of which reproduction procedure is described at https://github.com/docker/docker/issues/28391#issuecomment-260642494, I cannot hit the issue with [38b78a5](https://kernel.googlesource.com/pub/scm/linux/kernel/git/clk/linux/+/38b78a5f18584db6fa7441e0f4531b283b0e6725), but can hit with the previous commit [3c9fe8cd](https://kernel.googlesource.com/pub/scm/linux/kernel/git/clk/linux/+/3c9fe8cdff1b889a059a30d22f130372f2b3885f) .

(For this bisecting, I used https://github.com/AkihiroSuda/latest-docker-on-latest-kernel. e.g. `ldlk --kernel-version 38b78a5 --docker-version v1.13.0-rc2 tmp01`)

So I believe the original issue was resolved in [38b78a5](https://kernel.googlesource.com/pub/scm/linux/kernel/git/clk/linux/+/38b78a5f18584db6fa7441e0f4531b283b0e6725), and suggest closing this issue.

PTAL @dmcgowan 

@andrewmichaelsmith 
Please open another issue?

**Comment by andrewmichaelsmith** [comment]
@AkihiroSuda I was saying the bug was in 1.12.3, not 1.13. So (assuming it is fixed in 1.13) I don't think I need to create another issue?

Does my test case reproduce for you on 1.12.3?

@thaJeztah Not a test server unfortunately, otherwise would try that out, apologies.

**Comment by snth** [comment]
Hi,

I excitedly upgraded to Docker 1.13 on my Ubuntu 14.04 machine yesterday, hoping that this would resolve this `overlay2` bug. While my reproducible example above works now, I am still hitting a (the same?) problem in my actual application containers. I think it's a related, if not the same bug because I get directory listings with questions marks again and the problem goes away if a visit each directory entry as root first before trying to access it (with `sudo ls -R`). I am trying to update my reproducible example to hit the same error but that remains elusive for now. Settings below:

```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker info
Containers: 22
 Running: 20
 Paused: 0
 Stopped: 2
Images: 525
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.48 GiB
Name: aam-inv-tb1
ID: Q7SH:ZX2R:YBQB:S5O6:327O:XBYL:G2MI:JS52:7XJ6:7TMH:ATBE:6BNT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Let me reopen this issue for further investigation

ping @dmcgowan @AkihiroSuda

**Comment by dmcgowan** [comment]
Unfortunately I don't see [38b78a5f1858](https://kernel.googlesource.com/pub/scm/linux/kernel/git/clk/linux/+/38b78a5f18584db6fa7441e0f4531b283b0e6725) backported to [ubuntu kernel 4.4.0-59](http://changelogs.ubuntu.com/changelogs/pool/main/l/linux/linux_4.4.0-62.83/changelog).

**Comment by thaJeztah** [comment]
@sforshee do you know if that patch is scheduled to be back ported in the Ubuntu kernel?

**Comment by sforshee** [comment]
@thaJeztah we would only pull it in if it is part of upstream 4.4 stable or if someone reports a bug to us which is fixed by the commit. As far as I know neither of those are currently true.

So someone will either need to request the commit be added to the upstream 4.4 stable tree or else file a bug in Launchpad.

**Comment by snth** [comment]
@sforshee is this bug report good enough? I'm happy to file the bug but I haven't used Launchpad before so I don't know if there are extra requirements.

**Comment by sforshee** [comment]
@snth we require a bug in launchpad for any changes to stable releases. I went ahead and created a bug:

http://bugs.launchpad.net/bugs/1659417

Our release process requires that our release candidate kernels be tested before release to verify that the bug is fixed. I'll post back here at that point to request testing, which should be 2-3 weeks from now.

**Comment by snth** [comment]
Thank you @sforshee . Much appreciated!

**Comment by thaJeztah** [comment]
Looks like this is fixed in kernel 4.4.0-67.88 (see http://bugs.launchpad.net/bugs/1659417), is it save to close this issue?

**Comment by snth** [comment]
I've been meaning to test this. I should get to it on Monday. Can you wait until then?

**Comment by thaJeztah** [comment]
Sure! Thanks in advance 👍

**Comment by snth** [comment]
Hi,

I just retested and it seems fixed with the following config. Good to close!

Thanks!

```

# docker info
...
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
...
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64

# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by thaJeztah** [comment]
Good to hear, thanks @snth !

**Comment by liudonghua123** [comment]
I can reproduce this issue using the latest docker.
```
root@ubuntu:/tmp/overlay2_bug# docker -v
Docker version 18.06.1-ce, build e68fc7a
root@ubuntu:/tmp/overlay2_bug# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-42-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.78GiB
Name: ubuntu
ID: SKI5:XV3F:KQ3T:SJFU:76F4:PZGY:5QBF:KYNE:XKDD:MBMJ:DTLU:WZ2Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@ubuntu:/tmp/overlay2_bug#
```

It seems works only on `"storage-driver": "overlay"`, if I change to aufs or overlay2, it didn't work either.

```
root@ubuntu:/tmp/overlay2_bug# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
root@ubuntu:/tmp/overlay2_bug#
```

**Comment by kumy** [comment]
We had this bug using kernel 4.4, downgrading to 3.10 (centos 7 default) solved our issue.

**Comment by sebastienhasa** [comment]
I got the same problem and my storage driver is overlay2.

I run on Fedora 30:
```
Linux 5.3.8-200.fc30.x86_64
```

With docker version 1.13.1, build 47e2230/1.13.1:
```
docker info
Containers: 15
 Running: 2
 Paused: 0
 Stopped: 13
Images: 96
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: runc oci
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 5.3.8-200.fc30.x86_64
Operating System: Fedora 30 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 11.58 GiB
Name: %
ID: WL5N:W3LH:72MH:63MT:REKR:I6UI:2GH5:Z2KL:LZSD:Y6WQ:KEU7:JX3C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Registries: docker.io (secure), registry.fedoraproject.org (secure), quay.io (secure), registry.access.redhat.com (secure), registry.centos.org (secure), docker.io (secure)
```

**Comment by sebastienhasa** [comment]
Soooo, my problem was caused because one of the 3 volumes was not mounted with the ":z" option and Selinux block the access to one of my filffes
