### ISSUE TITLE
Docker push fails with most builds on my home machine

### ISSUE THREAD

**Issue by jkriesel** [moby/moby#28412]
I have been using a previous version (I believe 1.8) very successfully to push docker images to google's private repository.  However, in the latest release 1.12, they fail almost all the time.  I have had one successfully complete.  Every single time it's a some variant of an I/O timeout at different stages in the process.  I find it hard to believe it's an issue with my network as it worked almost 100% of the time with the previous version.  I've tried to set the concurrent upload limit to 1 and that doesn't seem to help in anyway.  

I only upgraded as Google now requires v2 images.  It's certainly possible this issue is on Google's end, but I also saw this issue logged with the same title and didn't see much in the form of resolution.  

Why is uploading a file so hard?  This should be very reliable.  Every other file upload on my system seems to work just fine.

**Comment by icecrime** [comment]
Cc @aaronlehmann @dmcgowan.

**Comment by dmcgowan** [comment]
@jkriesel could you provide the output of `docker info` as well as debug logs from the daemon during a failed push.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
