### ISSUE TITLE
[Proposal] build test plugins during make test-integration-cli

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#28411]
This is a proposal for moving the test plugins from pulling from Dockerhub to within Docker itself, either in plugins, contrib, or even vendor (probably not ideal). 
When looking at CI failures, I found these three plugins:
```
tiborvass/no-remove:latest
mavenugo/test-docker-netplugin:latest
riyaz/authz-no-volume-plugin:latest
```
I was talking with @estesp and there are a few issues with the current test plugins:

1.) Not having multi-arch support. This could be solved by moving the tests into docker somewhere and building them when running the tests. We could have multiple dockerfiles for each platform just like we do for the manpages. I don't see source code on tiborvass/no-remove but the other two took 30-60s to build with no-cache, but will probably be less because we are re-using the same image.

2.) Being in private dockerhubs. I understand trying to hack together some tests for experimental, but I really think that less links to private repo's the better.

3.) Needing to see the plugin in the case of a test failure. This came up recently in CI failures, where we weren't able to see the plugin to figure out what was wrong and had to wait to see if the issue would be fixed.

In order for any of this to happen, we would need to figure out where it would go, pull in the source-code to build the three plugins, and then add/build the multi-architecture dockerfiles. I can currently see the github for all of the plugins except for @tiborvass' so we would also need access to that.

WDYT @tiborvass @riyazdf @cpuguy83 @anusha-ragunathan

**Comment by tiborvass** [comment]
@tophj-ibm thanks for the issue, we are aware of this but now we have an issue to track it ;)

My source code is available on https://github.com/tiborvass/local-persist but I might change it again.
We def dont want to call out to hub, was just a stop gap.

**Comment by tophj-ibm** [comment]
@tiborvass @vdemeester do you think pulling in the 3 codebases into docker and then building at runtime of the testing environment is a solid approach? It will involve copying a lot of external github code into docker which feels wrong, but I can't think of a better way.

**Comment by tophj-ibm** [comment]
I see #30626 which looks pretty similar as well.

**Comment by vdemeester** [comment]
@tophj-ibm for images we do fetch them during the `docker build` before the execution of the actual tests so maybe we could do the same 👼

**Comment by tophj-ibm** [comment]
closing in favor of #30626
