### ISSUE TITLE
Container inspect with size will mount and unmount base layer

### ISSUE THREAD

**Issue by maxim28** [moby/moby#28464]
**Description**

The reason i report this issue is because i encountered a kernel(version 4.6.4) panic when running with docker containers(version 1.10.3). The panic seems like a kernel bug which was fixed and patched in kernel 4.8(https://patchwork.kernel.org/patch/9179461/).  

Except for the panic, i also found so many kernel logs like below, i suspect if these mounts caused the kernel bug: 

> EXT4-fs (dm-10): mounted filesystem with ordered data mode. Opts: (null)
> ...
> EXT4-fs (dm-10): mounted filesystem with ordered data mode. Opts: (null)

So i decide to investigate the docker code(Version 1.10.3), add some debug and build my own binary and found each time i call container inspect with size, docker daemon will mount the current layer of container(which is already mounted) and mount the base layer of container(which is not mounted usually), calculate the diff size and unmount them. my program will call container inspect every second, so the mount and unmount will be executed for base layer every second.

Frankly speaking,  such frequent mounts is caused by my frequent container inspect call. but i wonder if this will bring burden to kernel and if there are better ways to calculate the diff size without mount and unmount base layer ? e.g. store the base layer size in a memory map and update it when base layer is updated?

Actually i did not find any relations between many mount operations and kernel bug,  ignore the kernel panic problem if you guys also think so.

**Steps to reproduce the issue:**
1. call the container inspect with size every second

**Describe the results you received:**
1. you will find so many mount operations in kernel log

**Describe the results you expected:**
1. not so many mount operations

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.2
 Git commit:   20f81dd-unsupported
 Built:        Tue Nov 15 18:46:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.2
 Git commit:   20f81dd-unsupported
 Built:        Tue Nov 15 18:46:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 634.9 MB
 Data Space Total: 456.1 GB
 Data Space Available: 455.5 GB
 Metadata Space Used: 770 kB
 Metadata Space Total: 4.798 GB
 Metadata Space Available: 4.798 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host null
Kernel Version: 4.6.4-040604-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.8 GiB
Name: nq79
ID: FT5L:U3O3:4OZV:THVT:7GYC:TJFE:BBXD:2M3U:I7IN:XMEY:3IBM:S5WM
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 30
 System Time: 2016-11-16T11:27:15.488018082+08:00
 EventsListeners: 0
 Init SHA1: 85330d6c18d3ef97dd88b6f4cb58d75b661f72cb
 Init Path:
 Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
No

**Comment by runcom** [comment]
Ping @rhvgoyal

**Comment by rhvgoyal** [comment]
So right now `docker inspect -s` is reporting two sizes. Total size of container and size of diff layer. Size of diff layer calculation requires list of changed files in container since -init layer and calculating the total size. So we have to activate container rootfs and mount -init device. (To be able to calculate diff). We will need a list of changed files and that will require both the devices to be mounted. I am not sure how you can avoid id.

Second thing docker inspect shows total size of container and it add size of diff layer on top of image size. And image size is stored in image metadata (no devices mounted).

So I can't see how to calculate diff layer size without actually mouting -init layer. If you have ideas, please write a patch and open a PR.

**Comment by cpuguy83** [comment]
Also this is a very good reason why size requires a flag.

**Comment by maxim28** [comment]
here is my suggestion, please check if it is feasible:

1. if we only need **Size** of diff layer (not including list of changed files), why would we activate rootfs, calculate the rootfs size ( e.g. by du command) and minus the image size since it is stored in metadata?
2. if we also need list of changed files, could we store the list of changed files in memory maps when containers is created(key could be image id) or docker daemon is restarted?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
