### ISSUE TITLE
Host networking Doesn't Act As Expected

### ISSUE THREAD

**Issue by k2xl** [moby/moby#28491]
I have a debian container running with ```net=host```

On my host mac machine, I have ssh port forwarded port 30001 on my local mac to a remote MySQL server.

When running ```telnet localhost 30001``` on my host mac machine, I get a response from mysql
When running ```telnet localhost 30001``` inside my docker container, it is unable to connect

If I run other containers and open their ports, the debian container can access those thru localhost, but it doesn't appear that ports forwarded from the host machine are respected with host networking on the containers

I'm using docker for mac (latest version). ```docker version``` output:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true```

**Comment by cpuguy83** [comment]
Are you listening on localhost in the container?
Can you provide more details as to what is running, how it's setup, etc?

**Comment by k2xl** [comment]
@cpuguy83 I can listen on localhost on the container.

To reproduce, just try ssh port forwarding on your host, let's say to some remote MySQL instance on port 3306.

Then, inside the container that is running on host networking, try curling localhost:3306.

**Comment by thaJeztah** [comment]
closing as this one went stale, and may be specific to how Docker Desktop networking is set up
