### ISSUE TITLE
[feature request] gcplogs : Ability to set primary/secondary keys 

### ISSUE THREAD

**Issue by evmin** [moby/moby#28515]
Primary and secondary key labels are used by Google UI to provide a structural, drop down menus.

I would like to be able to set these values to organise the log hierarchy.

![image](https://cloud.githubusercontent.com/assets/5507517/20369383/cff7e7a0-acac-11e6-94eb-b5b06ad12737.png)

The keys are set through labels:

custom.googleapis.com/primary_key
custom.googleapis.com/secondary_key

    {'resource': {'type': 'global'}, 
     'labels': {'custom.googleapis.com/primary_key': 'DEMOTEST', 
            'custom.googleapis.com/secondary_key': 'TEST2'}, 
     'logName': 'projects/project/logs/TEST', 
     'severity': 'ERROR', 'textPayload': 'Something went wrong'}

Using the current labels to set them up does not work. 

    --log-opt labels=custom.googleapis.com/primary_key,location \ 
    --label custom.googleapis.com/primary_key=TESTS \

Results in 

![image](https://cloud.githubusercontent.com/assets/5507517/20369550/b4dd17a0-acad-11e6-918b-1d53259f7c2c.png)

Gcloud API example that works:

    #!/usr/bin/env python
    from gcloud import logging
    logging_client = logging.Client()
    logger = logging_client.logger("PYTHON_TEST")
    labels = {'custom.googleapis.com/primary_key' : 'DEMOTEST','custom.googleapis.com/secondary_key' : 'TEST2' }
    logger.log_text('Something went wrong', severity='ERROR', labels=labels)

**Comment by evmin** [comment]
The issue relates to 
https://github.com/docker/docker/issues/28508

**Comment by thaJeztah** [comment]
ping @mikedanese wdyt?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
