### ISSUE TITLE
[feature request] gcplogs : Ability to send the log text as textPayload

### ISSUE THREAD

**Issue by evmin** [moby/moby#28555]
At the moment the log body is sent over as structPayload.data field

I would like to be able to configure the driver to send the log body as textPayload field as it is more readable through the Google Logging console.

Relates to https://github.com/docker/docker/issues/28515 and https://github.com/docker/docker/issues/28508

**Comment by scole-scea** [comment]
Based on what I see in the StackDriver web U/I, changing the log line from a field called `data` to a field called `message` would also do the trick.

That's a breaking API change, though, which has it's own problems.

**Comment by gkze** [comment]
Is there any progress on this? Would like to see this change - `jsonPayload.data` => `jsonPayload.message` as it will make the logs more readable in the GCP Logs Console.

Happy to PR if no one is working on it :)

**Comment by thaJeztah** [comment]
@gkze I don't think anyone started working on this, so feel free to go ahead! We can further discuss design/changes on the pull request. Should I add a "claimed" label for you?

**Comment by gkze** [comment]
@thaJeztah please do! Going to get it done in the next day or so

**Comment by thaJeztah** [comment]
Perfect, thanks in advance for contributing!

**Comment by thaJeztah** [comment]
- looks like implemented in https://github.com/moby/moby/issues/28555
