### ISSUE TITLE
Descrepancy in /proc/net/dev stats for eth0(inside container), veth0, docker0

### ISSUE THREAD

**Issue by aagarwal-optumsoft** [moby/moby#28572]
I have a setup where a raspberry Pi is connected using wifi to the internet, runs the docker container, inside which there are bunch of processes communication with a public server over TCP. I monitor /proc/net/dev for 100 secs at eth0 (inside container) and  veth0 & docker0 (outside the conatiner). I see that bytes transmitted from veth0 and docker0 interface are same but very less in comparison to eth0 In spite of all having same number of packets. Following is the e.g stats of that:

eth0: 73,427 bytes and 165 packets
veth0: 11,842 bytes and 166 packets
docker0: 11,842 bytes and 166 packets
wlan0 (on host): 84,964 bytes and 228 packets.

so the actual data sent should be at wlan0 interface and that is very much consistent with eth0 (inside the container). 

Am I mistaken in some way?

Thanks
Abhinav

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
