### ISSUE TITLE
Docker volume .md files need more detail

### ISSUE THREAD

**Issue by khudgins** [moby/moby#28612]
**Description**

Docker volume command documentation files do not fully describe expected behavior for contributors writing volume drivers. In particular, volume management in swarm mode can be troublesome for clustered storage systems when determining which node to create volumes and where to report volume list. This can lead to cartesian bugs when creating volumes (every node creates a volume based on the volume create request). Some plugin authors have been confused as to where to report a volume as available depending on how their storage system manages volumes.

@anusha-ragunathan is aware of this and will be following up with more info.

CC'ing @thaJeztah @stevvooe @vieux per Anusha's request.

**Comment by anusha-ragunathan** [comment]
There are some issues that attempted to track this effort. #24089 for example, but it has been closed and there is are no docs on `Swarm mode volume management best practices`. We could start off with something like https://github.com/docker/docker/issues/24089#issuecomment-230471368

@cpuguy83 : Is there a gist that you can put together for this issue? It'll help move the issue forward.

**Comment by stevvooe** [comment]
@khudgins Do you have specific examples that can be addressed?

These kinds of issues have a way of getting closed to early or getting nothing done because they don't have clear criteria.

It sounds like volume visibility is a problem, which I agree with, but what else falls under this?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
