### ISSUE TITLE
Security Proposal: add "--pids-limit" to "docker service create/update" option list

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#28618]
This limit can prevent from OS resource damage by applications inside the container using fork bomb attack.

And this issue can also be easy to implement referencing from "--limit-memory".

=> Setting pids value to: /sys/fs/cgroup/pids/docker/**$container**/pids.max

**Comment by thaJeztah** [comment]
I linked this to https://github.com/docker/docker/issues/25303, which is where we keep track of options that are present on `docker run` but not (yet) supported for services

note that `--pids-limit` is already supported for `docker run`

**Comment by matthanley** [comment]
Is this close to being implemented now support is in swarmkit?

**Comment by thaJeztah** [comment]
Looks like a follow-up PR to implement the API changes was never opened; I just opened https://github.com/moby/moby/pull/39882 to expose the SwarmKit change in the Docker remote API. After that, changes still have to be made in the CLI repository, to add support in the `docker service create` and `docker service update` commands, as well as add it to the docker-compose schema

**Comment by thaJeztah** [comment]
This has been implemented, but not yet released (will be in the upcoming 20.xx release)
