### ISSUE TITLE
Client ImagePull doesn't work in 1.13.0-rc1

### ISSUE THREAD

**Issue by perigee** [moby/moby#28646]
**Description**

**Steps to reproduce the issue:**

I have created:

```
resp, err := client.ImagePull(context.Background(), "nginx", types.ImagePullOptions{})
defer resp.Close()

if err != nil {
	panic(err)
}
```

**Describe the results you received:**

no panic, no image pulled

**Describe the results you expected:**

pull the image nignx from hub to my local docker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:41:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:41:05 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 21
 Running: 3
 Paused: 0
 Stopped: 18
Images: 239
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 349
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: jh-ThinkPad-T520
ID: UYL3:WSQU:P3GC:P3TZ:PAPH:4PZN:ZJL6:UIF4:HUCF:KQSV:2XQL:ZD77
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: perigee
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mcwienczek** [comment]
I have similar issue. The image gets pulled only when stopped/throttled by
```
io.Copy(os.Stdout, out)
```

Looks like ImagePull is asynchronous and it doesn't wait for image to be pulled.

**Comment by scottbuckel** [comment]
@mcwienczek This worked, 4 years later! Thanks so much. I was running into the same issue in the latest version....whenever I was pulling a large image or running with low CPU resources it was continuing along in the code while the docker daemon continues pulling the image in the background.

**Comment by thaJeztah** [comment]
@scottbuckel if you think the example at https://docs.docker.com/engine/api/sdk/examples/ needs to be more clear about this, feel free to open a pull request (perhaps a comment in the code example to mention it's asynchronous). There's an "edit this page" button to open a pull request.

**Comment by zainq11** [comment]
I ran into the same issue. If you are not interested in printing to stdout(`io.Copy(os.Stdout, reader)`), `io.Copy(io.Discard, reader)` is an alternative that worked for me.
