### ISSUE TITLE
[rcf] do not allow experimental features if client/daemon versions don't match

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#28655]
Starting with docker 1.13 we allow newer clients to work with older
daemon versions, and "detect" if experimental features are enabled
on the daemon.

Given that experimental features can (and in many cases, _will_) change
before they leave experimental, this can result in unexpected behavior.

For example, if the "checkpoint / restore" feature leaves experimental
in 1.14, and a 1.14 client communicates with a 1.13 daemon, it will no
longer check if experimental features are enabled on the daemon (because
according to the client, the feature is no longer experimental).

The _daemon_ on its side, will allow requests to the "checkpoint" API 
endpoints if the `--experimental` flag is set.

I think we should prevent this, for example:

1. a client should only allow running experimental options if the client
  and daemon versions match
2. a daemon should also only allow access to experimental API endpoints
  if the client has the same version (_actual_ version, not downgrade
  / upgraded API version)
3. if a feature leaves experimental, the minimum API version of the 
  related endpoints should be set to the version in which it left experimental.

I'm not sure if `2.` is possible; does the client request contain information
that it downgraded / upgraded the API version?

Perhaps parts of this are already in place, but opening this issue
so that we don't forget checking before GA :smile:

/cc @vieux

**Comment by justincormack** [comment]
SGTM
