### ISSUE TITLE
sha calculation of docker image layers

### ISSUE THREAD

**Issue by kuriousengineer** [moby/moby#28665]
I used following docker file:

> FROM ubuntuBaseImage
> MAINTAINER Abhinav "abhinav.10888@gmail.com"
> RUN mkdir /root/imageLayer

issue following commands in the directory of the Dockerfile:

> docker build -t build1 .
> docker build --no-cache -t build2 .

to create build1 and build2 docker images. As expected all the layers in build2 and build1 have different sha so here I want to understand how sha is calculated for a docker command in docker file. What is the other criteria except a command that generates different sha for same docker command in docker file.

Thanks
Abhinav

**Comment by justincormack** [comment]
There are various things (timestamps, other metadata). I did look at this, and plan to revisit so it is possible to get the same hash, but there are quite a few changes needed at present unfortunately.

**Comment by AkihiroSuda** [comment]
Seems answered.

Deterministic build is discussed in https://github.com/moby/buildkit/issues/1058
