### ISSUE TITLE
How to install Docker from behind a firewall that only allows traffic based on IP addresses?

### ISSUE THREAD

**Issue by JensPiegsa** [moby/moby#28666]
**Description**

I want to install docker-engine through APT on Debian in a restricted environment
in which outgoing traffic is only allowed to specific numeric IP addresses. However,
multiple calls to `host apt.dockerproject.org` result in different IP adresses.
How to work around that issue?

**Comment by justincormack** [comment]
It is on cloudfront, you could try to list all the addresses, but you are probably better off mirroring it locally from a less restricted machine?

**Comment by thaJeztah** [comment]
You can download the packages locally, or install apt-cacher-ng to cache the packages locally; https://www.unix-ag.uni-kl.de/~bloch/acng/html/

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
