### ISSUE TITLE
Bug: iptables execution denied by selinux

### ISSUE THREAD

**Issue by damon-atkins** [moby/moby#28713]
The following and more iptables errors are occurring due to an issue with selinux

ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: No chain/target/match by that name.`

selinux is reporting

type=AVC msg=audit(1479747374.929:1115): avc:  **denied**  { read write } for  pid=6161 comm="iptables" path=2F6465762F73686D2F666669536A654E6833202864656C6574656429 dev="tmpfs" ino=30503 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:firewalld_tmpfs_t:s0 tclass=file

Appears on boot and restart of docker

```
Linux box 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.2.1511 (Core)
docker-engine-1.12.3-1.el7.centos.x86_64
python-docker-py-1.7.2-1.el7.noarch
docker-engine-selinux-1.12.3-1.el7.centos.noarch
```

```
Name        : docker-engine-selinux
Version     : 1.12.3
Release     : 1.el7.centos
Architecture: noarch
Install Date: Tue 22 Nov 2016 02:24:34 AM AEDT
Group       : Tools/Docker
Size        : 43725
License     : GPLv2
Signature   : RSA/SHA512, Thu 27 Oct 2016 09:59:05 AM AEDT, Key ID f76221572c52609d
Source RPM  : docker-engine-selinux-1.12.3-1.el7.centos.src.rpm
Build Date  : Thu 27 Oct 2016 08:47:09 AM AEDT
Build Host  : 719d8d68f3dc
Relocations : (not relocatable)
Packager    : Docker <support@docker.com>
Vendor      : Docker
URL         : https://dockerproject.org
Summary     : SELinux Policies for the open-source application container engine
```

**Comment by thaJeztah** [comment]
ping @andrewhsu @sanimej ptal

**Comment by thaJeztah** [comment]
@damon-atkins is this still an issue on the current (17.03) release?

**Comment by damon-atkins** [comment]
Still seeing in the audit logs

type=AVC msg=audit(1490252059.500:7605): avc:  denied  { read write } for  pid=510 comm="iptables" path=2F6465762F73686D2F6666693241306A4F50202864656C6574656429 dev="tmpfs" ino=17192 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:firewalld_tmpfs_t:s0 tclass=file


type=AVC msg=audit(1490252059.505:7607): avc:  denied  { read write } for  pid=511 comm="iptables" path=2F6465762F73686D2F6666693241306A4F50202864656C6574656429 dev="tmpfs" ino=17192 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:firewalld_tmpfs_t:s0 tclass=file

docker-engine-17.03.0.ce-1.el7.centos.x86_64
docker-engine-selinux-17.03.0.ce-1.el7.centos.noarch

This could be inside the container given the pid numbers.

**Comment by kidfrom** [comment]
Hi, any heads up? I found this is still an issue if you enforce SELinux to Docker container.

**Comment by sam-thibault** [comment]
I will close this issue as stale.  If you have run into this issue on a more recent version, please comment with more information.
