### ISSUE TITLE
`docker stack ps --filter id=` seems to be broken

### ISSUE THREAD

**Issue by albers** [moby/moby#28719]
I'm trying to figure out how filtering in `docker stack ps` works. The docs provide no information.
I think the `id` filter is broken.

Say, I have a stack `Hugo` with one service `Hugo_web`:
```bash
$ docker stack services Hugo
ID            NAME      MODE        REPLICAS  IMAGE
kdxfi96jlgi8  Hugo_web  replicated  1/1       nginx@sha256:9038d5645fa5fcca445d12e1b8979c87f46ca42cfb17beb1e5e093785991a639
```
Filtering on `name` works:
```bash
$ docker stack ps --filter name=Hugo_web Hugo
NAME                     IMAGE                                                                          NODE          DESIRED STATE  CURRENT STATE              ERROR  PORTS
Hugo_web.1.fxcahjdjrzoy  nginx@sha256:9038d5645fa5fcca445d12e1b8979c87f46ca42cfb17beb1e5e093785991a639  4e31b14c60cf  Running        Running about an hour ago
```
Now, I'm trying to use the `id` filter. What value should I supply?
```bash
# using the short ID returned by `docker stack services Hugo` does not find a match
$  docker stack ps Hugo --filter id=kdxfi96jlgi8
Nothing found in stack: Hugo
# using the long ID does not find a match, too
$ docker stack services -q Hugo
kdxfi96jlgi8cm6ocs8wkgpou
$ docker stack ps Hugo --filter id=kdxfi96jlgi8cm6ocs8wkgpou
Nothing found in stack: Hugo
```
Observed in current master

**Comment by albers** [comment]
Note: For the related `docker stack services` command, the `id` filter works:
```bash
$ docker stack services Hugo --filter id=kdxfi96jlgi8
ID            NAME      MODE        REPLICAS  IMAGE
kdxfi96jlgi8  Hugo_web  replicated  1/1       nginx@sha256:9038d5645fa5fcca445d12e1b8979c87f46ca42cfb17beb1e5e093785991a639
```
I would expect `docker stack ps` to accept the same filter expression.

**Comment by ushuz** [comment]
`docker stack services` lists **Service**s while `docker stack ps` gives you **Task**s, Service and Task are different concepts in Docker Swarm. 

`kdxfi96jlgi8` is a Service ID, not Task ID, so you can't filter tasks by Task ID using Service ID. What you actually want is equivalent to this,

```
docker stack ps Hugo --filter service-id=kdxfi96jlgi8
```

but [the above filter is not implemented](https://docs.docker.com/engine/reference/commandline/stack_ps/#filtering), you should use this instead.

```
docker service ps kdxfi96jlgi8
```

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
