### ISSUE TITLE
docker cp autocompletion doesn't support both usage formats

### ISSUE THREAD

**Issue by thornycrackers** [moby/moby#28736]
[Official docker cp documentation](https://docs.docker.com/engine/reference/commandline/cp/)

In the file docker/contrib/completion/zsh/_docker line 616 the autocomplete declaration only supports the following docker cp usage format:
```
docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
```
It would be awesome if it also supported the other format of:
```
docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH
```
It's annoying that the autocompletion doesn't work when you want to copy a file to a running container. I don't think this would be overly complicated to solve for someone who understands zsh autocompletion.

**Comment by albers** [comment]
ping @sdurrheimer PTAL.

**Comment by sdurrheimer** [comment]
https://github.com/docker/docker/issues/17029#issuecomment-149025245

I'm still not sure how to do that properly.

**Comment by albers** [comment]
@sdurrheimer Is there a way to compute a combined list and use that in completion?

**Comment by thornycrackers** [comment]
I know that you can build two separate contexts using tags, this is how my scp autocomplete works:

<img width="1413" alt="scpauto" src="https://cloud.githubusercontent.com/assets/4313010/20564707/aa14e5d0-b14b-11e6-8d69-445ff9d2505c.png">

The issue, I think I don't know haha, is that the current autocompletion is building two separate contexts for each situation?
```
(cp)
    local state
    _arguments $(__docker_arguments) \
        $opts_help \
        "($help -L --follow-link)"{-L,--follow-link}"[Always follow symbol link]" \
        "($help -)1:container:->container" \
        "($help -)2:hostpath:_files" && ret=0
    case $state in
        (container)
            if compset -P "*:"; then
                _files && ret=0
            else
                __docker_complete_containers -qS ":" && ret=0
            fi
            ;;
    esac
    ;;

```
My Reference [How to build zsh autocomplet](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org). 

I think your can just use something like the example for _alternatives for this situation to build the two context:

```
local -a options
options=$(docker ps --format "{{.Names}}")
_alternative "args:docker containers:($options)" 'files:filenames:_files'

```
 I'm not sure but maybe that helps?

**Comment by sdurrheimer** [comment]
Combined list is not a problem. What is more complicated is to keep the state that the first argument will be a contrainer path or a host path in order to complete the second argument.

I could makes suggestion for both all the time, but this would let people do `docker cp container:path container:path` which is incorrect.

**Comment by thornycrackers** [comment]
If we are not worried about the constrained list being the problem then we should only have to add the proper term inside the "($help -)" to make the command mutually exclusive. From the docs:

> If the name given for one of the mutually exclusive sets is of the form ‘(name)’ then only one value from each set will ever be completed; more formally, all specifications are mutually exclusive to all other specifications in the same set. This is useful for defining multiple sets of options which are mutually exclusive and in which the options are aliases for each other.

They have an example on there as well that looks like it might solve this problem. I tried to figure out how to do this on my own but in the examples in the docs they have actual command line arguments like '-c' and '-d' which makes ours a bit more tricky since we are trying to make the arguments mutually exclusive based on their tags. Does that seem like it might be in the right direction?

**Comment by zhenyulin** [comment]
Came across this problem in Mac Terminal bash, and file path autocompletion in ssh `scp` works well, wondering if this can be a reference to the solution here?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
