### ISSUE TITLE
/etc/resolv.conf on the host was updated after docker run.

### ISSUE THREAD

**Issue by reasonerjt** [moby/moby#28740]
Hi, I see this issue on some of my VMs(non-dhcp), and not reproducing it on my ubuntu(with dhcp)

Steps to reproduce:
```
# cat /etc/resolv.conf

nameserver 10.117.0.1
domain .......
search .......
```
```
# docker run -d --name mynginx nginx:1.11.5
e87e8263877509365e786f888ee4ad07680e0ce743912b57f3a4eb762beb131c
```
Then the /etc/resolv.conf changed.
```
# cat /etc/resolv.conf

# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
# Too many DNS servers configured, the following entries may be ignored.
nameserver 2001:4860:4860::8844
```
My Environment info:
```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.8
Operating System: VMware Photon/Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name:.......
ID: ......
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
Please let me know if this is a known issue, or what other information's needed for debugging.  Your help is appreciated.

**Comment by reasonerjt** [comment]
I found the resolv.conf was updated by "systemd-resolved.service"
Also I see this:
```
# cat /etc/systemd/resolved.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
LLMNR=false
```

However I don't quite understand why docker run would trigger that.

**Comment by pavlix** [comment]
As far as I know, resolved attempts to handle `resolv.conf` in some cases. Last time I talked to Lennart he said resolved would only manage its own copy of `/etc/resolv.conf` and that the administrator should create a `/etc/resolv.conf` symlink to that one. I don't know if it still holds but you might at least want to check that you don't have such a symlink.

As a side note, docker normally bind-mounts a `/etc/resolv.conf` which is IMO not a good idea either as it the prevents it from being replaced. I personally would not expect resolved getting around that limitation and writing directly to the bind-mounted file.

**Comment by pavlix** [comment]
And you are talking about the host `/etc/resolv.conf`. But in that case you should double check how your system is actually configured and whether it is really triggered by docker at all. And if it is, docker is probably making some changes in network interface configuration and resolved might be directly or indirectly reacting to that and updating its version of `resolv.conf` that might be the target of a `/etc/resolv.conf` symlink.

**Comment by thaJeztah** [comment]
Each container gets its own `resolv.conf`, which is bind-mounted into that container; you can find the path to the file from `docker inspect`, for example;

```
        "ResolvConfPath": "/var/lib/docker/containers/fe0ea0071a597f654131856d031ade48fd63bb28e381492a61b45a807af6a53e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/fe0ea0071a597f654131856d031ade48fd63bb28e381492a61b45a807af6a53e/hostname",
        "HostsPath": "/var/lib/docker/containers/fe0ea0071a597f654131856d031ade48fd63bb28e381492a61b45a807af6a53e/hosts",
        "LogPath": "/var/lib/docker/containers/fe0ea0071a597f654131856d031ade48fd63bb28e381492a61b45a807af6a53e/fe0ea0071a597f654131856d031ade48fd63bb28e381492a61b45a807af6a53e-json.log",
```

Docker is _not_ managing `/etc/resolv.conf` on the host

**Comment by pavlix** [comment]
@thaJeztah If that was supposed to be a reaction to my comments (given the time you posted)... The information you added was already known to me and it doesn't change what I already posted in any way. Please disregard if that wasn't a reaction to me.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
