### ISSUE TITLE
Stopping "Docker for Windows Service" returns Error 1067

### ISSUE THREAD

**Issue by MihaMarkic** [moby/moby#28742]
**Description**
Stopping Docker for Windows Service results in error 1067.

**Steps to reproduce the issue:**
1. Stop Docker for Windows Service through computer management

**Describe the results you received:**
```
A Message box:
---------------------------
Services
---------------------------
Windows could not stop the Docker for Windows Service service on Local Computer.

Error 1067: The process terminated unexpectedly.
```

The service stops though. Docker isn't running at the time.

**Describe the results you expected:**

Normal behavior (no errors)

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens always, running Windows 10 AU

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 639
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 451
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.918 GiB
Name: moby
ID: MMEV:J3D4:HLSY:7YKR:AJ2O:ZRP7:K7F5:KD3T:YMHZ:XQTQ:GZVS:CMOY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mihamarkic
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by myusrn** [comment]
This issue still repros running latest windows 10 October 2018 update insider slow install, v1809/bld17754.1, and docker for windows 18.06.0-ce-win72 install.  Is anything happening to look into fixing it since doing a net stop "com.docker.service" or net stop "docker for windows service" should be able to complete w/o throwing any errors as it messes up scripted stops of service.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
