### ISSUE TITLE
Switch to Jekyll for docs makes man-pages markdown different from CLI docs

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#28750]
Just adding this for discussion so that we can find how to resolve this; this occurred to me while reviewing https://github.com/docker/docker/pull/28734

Jekyll requires some non-standard markdown markup markers for certain parts of the documentation (`{% raw %}` / `{% end raw %}`). Before the switch to Jekyll, these markers were not needed, so it was possible to copy / re-use the same markdown for both the CLI reference, and the man-pages.

If we want to generate both the CLI docs and man-pages using the same source, we may have to make some changes so that the man-page generation understands those markers

/cc @johndmulhausen @FrenchBen @dnephin @cpuguy83

**Comment by cpuguy83** [comment]
We'll have to make some changes to blackfriday (md parser) most likely.
What goes inside here? Should the manpage generator attempt to do anything with what's inside these markers?

**Comment by thaJeztah** [comment]
Basically it is if there's a Go template in the example, e.g.

```
docker inspect --format '{{ .Foo }}{{ .Bar }}'
```

In that case, these Jekyll markers have to be added;

```
{% raw %}
docker inspect --format '{{ .Foo }}{{ .Bar }}'
{% end raw %}
```

or 

```
docker inspect --format {% raw %}'{{ .Foo }}{{ .Bar }}'{% end raw %}
```

Perhaps a simple find/replace suffices (not sure if those Jekyll markers are case insensitive though. @johndmulhausen may know, but I can do a search in the Jekyll documentation if needed

**Comment by johndmulhausen** [comment]
@thaJeztah It's actually `{% endraw %}` (one word) to be clear!

**Comment by thaJeztah** [comment]
Oh, thanks @johndmulhausen

**Comment by thaJeztah** [comment]
docs are back to using Hugo, so we can start removing these where needed
