### ISSUE TITLE
[Docker for Windows] Error: EACCES: permission denied

### ISSUE THREAD

**Issue by lyquocnam** [moby/moby#28790]
i use ubuntu:14.04 with docker windows 10 x64.
i mounted drives and create nodejs project working on it.
sometimes i must restart docker and restart container for this error.
`Error: EACCES: permission denied`

**Comment by AkihiroSuda** [comment]
Please use this template? https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by thaJeztah** [comment]
closing because this went stale
