### ISSUE TITLE
[1.13 UX consistency] Secret names are case-insensitive

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#28807]
I noticed that secret names are "case-insensitive";

```bash
$ echo foo | docker secret create FOO
mhtq1y7gggojnt0sjm8ea01gp

$ echo foo | docker secret create foo
Error response from daemon: rpc error: code = 6 desc = secret foo already exists

# This also works:
$ docker secret rm foo
```

(note that this is only for _validation_, the secret names _are_ stored with the original case);

```
docker secret ls
ID                          NAME                CREATED             UPDATED
amlzbwp5kdml54amfr2zw1u7l   FoO2                16 minutes ago      16 minutes ago
mhtq1y7gggojnt0sjm8ea01gp   FOO                 19 minutes ago      19 minutes ago
```

This is inconsistent with other objects;

```bash
$ docker volume create foo
foo
$ docker volume create FOO
FOO

$ docker create --name foo busybox
fa47b73014b27a6451919e96ef7b6419d5769626028e1c456fa011d71fea811d

$ docker create --name FOO busybox
2136ed965eea62743e8e5ed6cf01377d9470e41583b799795c255da3ad7d7c2d

$ docker network create foo
4247de5ea77df3a42bd41fa112ff3ae62616d8c868f81279b46e8b3d034445e1
$ docker network create FOO
a8d46d4e5f9147bd90c4f31a1026ce347fd3098f7400eb991dec1fcda52114b8

$ docker checkpoint create --leave-running my-container foo
$ docker checkpoint create --leave-running my-container FOO
```

**Question** volume-names (and checkpoint names) are directly mapped to the filesystem. Do we support case-sensitive volume names on Windows? Do we _want_ to?

/cc @dnephin @icecrime @ehazlett @diogomonica

**Comment by icecrime** [comment]
Cc @johnstep for Windows.

**Comment by aaronlehmann** [comment]
I believe all SwarmKit objects are named case-insensitively. I don't recall why this decision was made. It's certainly unfortunate that it's not consistent with other things in Docker.

@diogomonica: We already do this validation server-side. The error message in the example comes from the manager.

**Comment by stevvooe** [comment]
In general, case insensitive matching should be used for user friendly systems. It ensures that matching happens as humans understand names and limits impact when exporting data to a system where case insensitivity is out of our control.

In this case, since we are projecting names to the file system, the lowest common denominator is case insensitive. This ensures that things work _the same_ in _all_ cases.

However, doing this _correctly_ requires a few considerations:

1. Names _should_ be stored in their original casing.
2. When validating and comparing names, the case _must_ be flattened.
3. When exporting names to a case sensitive system, the case _must_ be flattened.

There are a few variations on the above, but this mostly provides the framework for user friendly case insensitivity. While the details are key in following the above, this is mostly the behavior favored in swarmkit. I also believe this is the most secure approach, since case sensitive systems can be open to homograph attacks.

**Comment by diogomonica** [comment]
I agree with @stevvooe that the current behavior is the right one (store using the original case, compare using the lowest common denominator).

**Comment by thaJeztah** [comment]
The current behavior is really inconsistent with all other objects in docker, and even inconsistent with itself (https://github.com/docker/docker/issues/28808#issuecomment-262836822).

> When exporting names to a case sensitive system, the case must be flattened.

Then what is the use of allowing mixed case characters, if it's resulting in a lowercase secret in all cases? If we don't want mixed case secrets on the filesystem, we should not allow them in the first place.

**Comment by stevvooe** [comment]
> The current behavior is really inconsistent with all other objects in docker, and even inconsistent with itself (#28808 (comment)).

I am not sure that the docker behavior prescribes to a particular philosophy other than "allow anything and work out the problems later". We see this haphazard approach to naming cause issues with container id collisions, container name collisions, DNS collisions and registry collisions, resulting issues across the board.

It looks like the behavior in https://github.com/docker/docker/issues/28808#issuecomment-262836822 is a bug, so I am not sure it could be used as a counter point to the proposal above. It clearly does not meet the framework outlined.

> Then what is the use of allowing mixed case characters, if it's resulting in a lowercase secret in all cases? If we don't want mixed case secrets on the filesystem, we should not allow them in the first place.

This is to preserve the human-readable feel of the input name. Let's say that I liked the look of `StephenDay` across my services and entered the name that way. I would not expect that to be flattened, but I would expect it to be equal to `stephenday` when using DNS, deleting the object, or creating a colliding object.

**Comment by thaJeztah** [comment]
> This is to preserve the human-readable feel of the input name.

But we're using it to map the secrets in the container as well. If it's really just a human readable input name, I would expect _more_ flexibility (My last name is "van Stijn"; two words). However, it's not just a name, because (by default) we're using these names to map to a filename. So now I want to have a file "MySecretSecurityToken" in my container, but docker decides to mangle this name, and rename it "mysecretsecuritytoken", and I have to jump through extra hoops to restore my name

**Comment by stevvooe** [comment]
> If it's really just a human readable input name, I would expect more flexibility (My last name is "van Stijn"; two words). However, it's not just a name, because (by default) we're using these names to map to a filename.

Note that, normally, there is a space in "Stephen Day". 😉 

> So now I want to have a file "MySecretSecurityToken" in my container, but docker decides to mangle this name, and rename it "mysecretsecuritytoken", and I have to jump through extra hoops to restore my name

If the medium is case insensitive, referencing it as `MySecretSecurityToken` is sufficient. However, under rule 3, above, we can add a clause to say "don't flatten the case if the case sensitivity of the target system is unknown or implementation defined" or strictly read it as "Only flatten the case of exported names when it is known that the target system is case sensitive".

**Comment by vieux** [comment]
why store in the original casing then ? the current behaviour looks confusing to me

**Comment by stevvooe** [comment]
@vieux I think that was suggested, was it not? https://github.com/docker/docker/issues/28807#issuecomment-263396168
