### ISSUE TITLE
Secrets rm not working properly with mixed case

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#28808]
```bash
$ echo foo | docker secret create foo

$ echo foo | docker secret create FOO
Error response from daemon: rpc error: code = 6 desc = secret FOO already exists

$ docker secret rm FOO
# (no output)

# the secret has not been removed:

$ docker secret ls
ID                          NAME                CREATED             UPDATED
y6oy4t5ecf4dy6l0ug9ar20th   foo                 4 minutes ago       4 minutes ago

$ docker secret rm bar
WARN: Error response from daemon: rpc error: code = 5 desc = could not find secret bar
bar
```

It looks like `secret rm` does an initial case insensitive match, but
performs the actual delete case-sensitive, but fails to print an error
that the secret could not be found.

Also note that the last example prints `bar` twice

ping @ehazlett @diogomonica (also related: https://github.com/docker/docker/issues/28807)

**Comment by diogomonica** [comment]
Case insensitivity seems like the right thing. Question is: do we do it server-side or enforce it on the API.

As far as the `bar bar` goes, not sure what is going on there.

**Comment by thaJeztah** [comment]
I don't think being case-insensitive is the right thing to do. It's inconsistent, and being case-insensitive now, means we won't be able to change in future.

Also, looks like we're not consistently doing this in other places;

```
echo foo | docker secret create FOO
Error response from daemon: rpc error: code = 6 desc = secret FOO already exists

docker service create --secret FOO --name web nginx:alpine
secret not found: FOO

docker service create --secret foo --name web nginx:alpine
o5ng3xyu6sc18hszdlj8ds9ky
```

If we want to restrict, we should either only accept lower or uppercase, or accept both, and stick to that. The secrets are mounted inside the container using the name that was specified when creating the secret, and if this is a Linux container (currently, the only platform supporting secrets), the container _is_ case sensitive, so `secret create SOMETHING` has a different meaning than `secret create something`

**Comment by justincormack** [comment]
I tend to think that secrets are and will always remain files, so should be sensitive. We have had issues that some things become DNS names later, but this seems less likely here.

**Comment by ehazlett** [comment]
Yes I agree they should be case sensitive.

**Comment by thaJeztah** [comment]
ping @ehazlett @diogomonica what should we do with this?

**Comment by aaronlehmann** [comment]
The initial bug doesn't seem to exist anymore:

```
$ docker secret ls
ID                          NAME                CREATED              UPDATED
xmsbq3u4rh9oi8zrl0znt5158   foo                 About a minute ago   About a minute ago
$ docker secret rm FOO
FOO
$ docker secret ls
ID                  NAME                CREATED             UPDATED
```

As for case insensitivity, this is consistent with other objects in swarmkit:

```
$ docker service create --name top busybox top
mlvvesvnv888y3xyqvpg5maxe
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
$ docker service create --name TOP busybox top
Error response from daemon: rpc error: code = 2 desc = name conflicts with an existing object
```

If we want to change this, it needs to be a swarmkit-wide change, not just secrets.

@justincormack mentioned that filenames should be case-sensitive, but this is about the name of the secret object, not the filename (which can be configured separately when the secret is attached to a service).

I'd suggest closing this issue.
