### ISSUE TITLE
Docker Registry Issue: dial tcp xx.xx.xx.xxx:443: getsockopt: connection refused

### ISSUE THREAD

**Issue by ed11e** [moby/moby#28831]
**Description**

Error when trying to pull or login to a private docker registry from a docker client node. 

**Steps to reproduce the issue:**
1. docker login https://XX.XX.XX.XXX
2. Or sudo docker pull XX.XX.XX.XXX:5000/v1/repositories/ubuntu/images

**Describe the results you received:**
Error response from daemon: Get https://XX.XX.XX.XXX/v1/users/: dial tcp xx.xx.xx.xxx:443: getsockopt: connection refused 

**Describe the results you expected:**
Docker to login or to successfully execute the pull request. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Have checked the ports and the firewall. The required ports are open and docker is listening on the correct ports. 

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: docker-registry
ID: BOVF:MDOA:SK26:TCVZ:WUG7:POGH:ZYXK:USOK:N2YA:ZPEP:FWNI:EYXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenStack Vm's running Ubuntu trusty 14.04.

**Comment by thaJeztah** [comment]
We really need more info;

- what version of the registry are you running?
- how is it configured?
- is it configure with an authorization system? if so, which one?
- did this setup work before, or is this a new setup?
- is this the literal command you're running ? `sudo docker pull XX.XX.XX.XXX:5000/v1/repositories/ubuntu/images`? That does not look like a correct reference for an image (should probably be like `sudo docker pull XX.XX.XX.XXX:5000/ubuntu`

**Comment by ed11e** [comment]
Hi, 

Apologies for the delay in responding. 

**- what version of the registry are you running?**
Docker Registry Version: 1.12.3, build 6b644ec

**how is it configured?**
What do you mean by how it's configured? 

**is it configure with an authorization system? if so, which one?**
The authentication is set to use SSL via port 443. The certificates appear to be configured correctly on both machines. 

**is this the literal command you're running ?** 
The command I'm running is in fact `sudo docker pull XX.XX.XX.XXX:5000/ubuntu` (The one shown in the original post was a typo).

**Comment by thaJeztah** [comment]
> Docker Registry Version: 1.12.3, build 6b644ec

That's the version of _docker_. You are running a private registry, and it looks like the issue is either related to that registry, or the way it's set up. Trying to do a basic test, I cannot reproduce.

```bash
docker run -d -p 5000:5000 --restart=always --name registry registry:2
6bbc4497c9b6a91d66374fe813b90b79c603308e2312ab5e2089deb34d82d463

$ docker tag alpine:latest localhost:5000/alpine:latest

$ docker push localhost:5000/alpine:latest
The push refers to a repository [localhost:5000/alpine]
011b303988d2: Pushed
latest: digest: sha256:1b6c543cc889c8f5f8d7061ddd3941b04568f725960e95896a2fbc06311fa4c0 size: 528

$ docker rmi alpine:latest localhost:5000/alpine:latest
...


$ docker pull localhost:5000/alpine:latest
latest: Pulling from alpine
28c417e954d8: Already exists
Digest: sha256:1b6c543cc889c8f5f8d7061ddd3941b04568f725960e95896a2fbc06311fa4c0
Status: Downloaded newer image for localhost:5000/alpine:latest
```

**Comment by ed11e** [comment]
The docker registry version is version=v2.5.1

The registry is as you say a private registry and I'm trying to connect to it with a docker client running Docker Registry Version: 1.12.3, build 6b644ec. 

I can neither pull from the registry or login using 

`sudo docker login https://XX.XX.XX.XXX`

**Comment by thaJeztah** [comment]
@ed11e is this an existing setup, or a "fresh" install of that registry? Did it work before? How is authentication set up? Did the registry work without authentication set up? Do the logs of the registry show anything useful? 

Please be aware that the GitHub issue tracker is not a general support forum for configuring and running docker.

**Comment by ed11e** [comment]
I've tried it with both a fresh install and an existing one and the sam issue occurs both times. 

Authentication is set up using an SSL certificate which is present on both servers and then a user name and password is provided. The registry runs behind nginx. 

I've just tried disabling the authentication then restarting docker and the same issue occurs. 

The logs indicate that Daemon has initialised correctly and is listening.

**Comment by rachit1arora** [comment]
any update on this issue ? I tried setting up docker registry as service in kubernetes and i am hitting into this issue.

**Comment by tobilarscheid** [comment]
We see a similar error with our kubernetes on core os. Docker Login works, pull fails

**Comment by anannaya** [comment]
Hi,
I followed the procedure in https://docs.docker.com/registry/recipes/nginx/#setting-things-up
Registry and nginx both the containers are up.

docker login also successfull.
When i tried to  push the image ..it is failing.
{{{
[root@imsfuture-buildmachine dockerregistry.ims.nokia.com:5043]# docker login dockerregistry.ims.nokia.com:5043
Username: admin
Password: 
Login Succeeded

[root@imsfuture-buildmachine dockerregistry.ims.nokia.com:5043]# docker push dockerregistry.ims.nokia.com:5043/redhatbaseimage:7.3
The push refers to repository [dockerregistry.ims.nokia.com:5043/redhatbaseimage]
86888f0aea6d: Retrying in 4 seconds 
86888f0aea6d: Retrying in 20 seconds 
dda6e8dfdcf7: Retrying in 20 seconds 
^C
[root@imsfuture-buildmachine dockerregistry.ims.nokia.com:5043]# docker push dockerregistry.ims.nokia.com:5043/redhatbaseimage:7.3
The push refers to repository [dockerregistry.ims.nokia.com:5043/redhatbaseimage]
86888f0aea6d: Pushing [==================================================>]  1.744kB/1.744kB
dda6e8dfdcf7: Pushing [==================================================>]  192.7MB/192.7MB
dial tcp 10.43.192.3:5003: getsockopt: connection refused
}}}
Registry log:
{{
c6d6 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))" http.response.duration=5.748463ms http.response.status=202 http.response.written=0 instance.id=8a69a4f6-521a-4220-9405-e12939eb89f1 version=v2.6.2 
172.17.0.4 - - [13/Mar/2018:20:30:52 +0000] "POST /v2/redhatbaseimage/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))"
time="2018-03-13T20:30:52Z" level=info msg="response completed" go.version=go1.7.6 http.request.host="dockerregistry.ims.nokia.com:5043" http.request.id=068a3252-1e53-4a42-bea5-7716cb3553ca http.request.method=POST http.request.remoteaddr=10.43.192.8 http.request.uri="/v2/redhatbaseimage/blobs/uploads/" http.request.useragent="docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))" http.response.duration=6.35032ms http.response.status=202 http.response.written=0 instance.id=8a69a4f6-521a-4220-9405-e12939eb89f1 version=v2.6.2 
172.17.0.4 - - [13/Mar/2018:20:30:52 +0000] "POST /v2/redhatbaseimage/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))"
}}
Br,
Anand

**Comment by SaurabhDev** [comment]
I am also facing the same issue. I had setup the docker repository on jfrog and getting below error

docker login -u admin -p admin docker-devops.192.168.10.247
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://docker-devops.192.168.10.247/v2/: dial tcp 192.168.10.247:443: getsockopt: connection refused

**Comment by toomaj** [comment]
It is possible that you are trying to communicate with a **insecure private registry** and docker expects the registries to be secure by default, but if you still like to use your own insecure one then docker needs to know about it on the client machine.
Just put the following in `/etc/docker/daemon.json` on Linux/Mac or `C:\ProgramData\docker\config\daemon.json` on windows:
```json
{
  "insecure-registries" : ["registry.server:port"]
}
```

**Comment by thaJeztah** [comment]
Closing as this went stale
