### ISSUE TITLE
How to ensure the consistency of the same image in different docker registry?

### ISSUE THREAD

**Issue by bobo200128docker** [moby/moby#28853]
I have a question:
In my work sence，I have three docker registries with localfile system. How can I ensure the consistency of the same image?

1. I will push image to three registries from the same machine. 
    merit:simple operation
    demerit:there is not a master and not too good to verify their consistency
2. I will push image to registry_A , rsync registry_A to registry_B and registry_C
    merit:simple operation and have a master registry_A
    demerit:I feel a little bit countrified

there are any other method which can resolve this problem smartly?

thanks!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, but reproducible digests for manifest should be possible with the containerd image-store integration (which stores all intermediate artifacts on disk)
