### ISSUE TITLE
docker top CONTAINER [ps OPTIONS] -- OPTIONS not working

### ISSUE THREAD

**Issue by looselytyped** [moby/moby#28867]
**Description**

There was a similar issue reported earlier (https://github.com/docker/docker/issues/6482) but that does not seem to be my issue. Please see below. 

**Steps to reproduce the issue:**
1. Start an interactive `ubuntu` container

```
docker run -it ubuntu /bin/bash
```

2. Inspect processes with formatting
```
root@9789d48f3b76:/# ps o pid,cmd
  PID CMD
    1 /bin/bash
   12 ps o pid,cmd
```

3. In another terminal, ensure container is being listed

```
docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED              STATUS              PORTS                    NAMES
9789d48f3b76        ubuntu                "/bin/bash"         About a minute ago   Up About a minute                            pensive_meitner
```

4. Use the same options that worked in the container with `docker top`

```
docker top 9789d48f3b76 o pid,cmd
PID                 USER                TIME                COMMAND
8962                root                0:00                /bin/bash
```

**Describe the results you received:**

No matter what options I offer `docker top` I always get the same results back.

**Describe the results you expected:**

I would have expected that if the container can support the arguments being supplied to `ps` then supplying them to `top` would return the same results (which apparently was the case with issue https://github.com/docker/docker/issues/6482)

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried this with commands that expect a `-` as well

**In the container**
```
root@9789d48f3b76:/# ps -e
  PID TTY          TIME CMD
    1 ?        00:00:00 bash
   24 ?        00:00:00 ps
```

**Using the docker CLI**

```
docker top 9789d48f3b76 -e
PID                 USER                TIME                COMMAND
8962                root                0:00                /bin/bash
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 50
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: KRFD:CKJW:ZKSQ:WMJJ:T477:ZPYU:NKXF:L6Y6:THDM:4AE6:RGBI:BPU6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 54
 System Time: 2016-11-27T13:39:01.058080347Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: looselytyped
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

If there is anything other details I can provide you with, please let me know.

Thank you so much!

**Comment by thaJeztah** [comment]
IIRC, the ps/top is executed on the docker _host_ but in the container's namespace. Docker for Mac uses "Moby", an Alpine based Linux, which may not have these options

@justincormack ?

**Comment by justincormack** [comment]
Yes that's alas true. We do not document the options that docker top
supports for that reason. Its not a good design, really docker should ship
with its own version of ps that is always the same, or a Go implementation
built in.

**Comment by looselytyped** [comment]
Thank you @thaJeztah and @justincormack ! 

OK. That makes sense. I did not realize that. 

I am not sure of the protocol here, but should I go ahead and close this?

**Comment by thaJeztah** [comment]
I think we can close this, although possibly it would be a good thing to improve the documentation perhaps you're interested in opening a pull request? The reference docs for the `docker top` command is in the docs directory of this repository

**Comment by justincormack** [comment]
I think there should be an open issue that arguments to docker top are not
defined and therefore undocumented. Its not a good thing to have. There are
potential compatibility issues in finding a solution.

**Comment by RootTJNII** [comment]
Docker top should probably operate off the host and gather processes that way instead of depending on ps being present in the container (which is not guaranteed).  This is possible using /proc/*/cgroups, I'm not familiar enough at this level to know if there is an easier way.

Having a reliable docker top that is container independent would be useful for security audits, I'm currently auditing for processes in containers running with UID 0 and having to poke around /proc/ due to this issue.

**Comment by thaJeztah** [comment]
> Docker top should probably operate off the host and gather processes that way instead of depending on ps being present in the container (which is not guaranteed)

That's what it currently does; it executes `ps` on the host, but in the container's namespace (or filters based on processes in the namespace)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
