### ISSUE TITLE
Debian 8.5 Server running docker 1.9.1,1.11.1,1.11.2,1.12.1.1.12.2.1.12.3 all crashed

### ISSUE THREAD

**Issue by tuhaolam** [moby/moby#28870]
**Description**

**Steps to reproduce the issue:**
1.Linux Server run Debian  8.5, kernel version 3.16.0-4-amd64
2.run docker version 1.9.1,1.11.1,1.11.2,1.12.1.1.12.2.1.12.3
3.after less a week, system crash

**Describe the results you received:**
linux kernel crash

**Describe the results you expected:**
run normally as long as it can
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Docker version 1.11.1
```

**Output of `docker info`:**

```
time="2016-09-07T20:22:19.450573015+08:00" level=warning msg="Your kernel does not support cgroup memory limit"
time="2016-09-07T20:22:19.450618295+08:00" level=warning msg="Your kernel does not support cgroup cfs period"
time="2016-09-07T20:22:19.450640785+08:00" level=warning msg="Your kernel does not support cgroup cfs quotas"
time="2016-09-07T20:22:19.450769672+08:00" level=warning msg="mountpoint for pids not found"
aufs au_opts_verify:1570:dockerd[2725]: dirperm1 breaks the protection by the permission bits on the lower branch
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine
```
[PRODUCT INFO]
 Vendor : Dell Inc.
 Manufacturer: Dell Inc.
 Product : PowerEdge R420
 System : Linux
 Kernel : 3.16.0-4-amd64
 Disto : Debian
 Version : 8.5
 Arch : x86_64
```

** kernel crash log**
```
[275908.774746] BUG: unable to handle kernel NULL pointer dereference at 0000000000000078
[275908.774934] Oops: 0000 [#1] SMP 
```

**Comment by AkihiroSuda** [comment]
Can you provide much more lines of the crash log?
Also, please provide the full output of `docker info`?

**Comment by thaJeztah** [comment]
closing; this one went stale, and debian Jessie is no longer by docker
