### ISSUE TITLE
secrets still accessible after node leaves the swarm

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#28929]
**Description**

Secrets are still accessible after a node left the swarm.
**Steps to reproduce the issue:**

Create a secret and use the secret for a service;

```bash
echo "hello world" | docker secret create top-secret -
coayc5tyz5107dv1cx0ovyx7y

docker service create --name web --secret top-secret nginx:alpine
```

Update the service so that a new task is created;

```bash
docker service update --force web
```

There's now a running and a stopped task / container;

```bash
docker ps -a
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
327bf43d5685        nginx@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4   "nginx -g 'daemon ..."   34 seconds ago      Up 31 seconds               80/tcp, 443/tcp     web.1.p0cphxihp6r7hsn0jaobmvi89
061ecbc7aeb4        nginx@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4   "nginx -g 'daemon ..."   47 seconds ago      Exited (0) 32 seconds ago                       web.1.inlwh3emp0jtisgzi3m8x25a4
```

Now, leave the swarm (using `--force`, because this is a single node/manager, not sure if that plays a role here);

```bash
$ docker swarm leave --force
Node left the swarm.
```

Notice that the _running_ task/container is removed, but the  stopped task / container still exists;

```
 docker ps -a
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                     PORTS               NAMES
061ecbc7aeb4        nginx@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4   "nginx -g 'daemon ..."   3 minutes ago       Exited (0) 2 minutes ago                       web.1.inlwh3emp0jtisgzi3m8x25a4
```

Start the container;

```bash
docker start 061ecbc7aeb4
```

In the daemon logs, it's visible that the secrets are mounted;

```
DEBU[0273] Calling POST /v1.26/containers/061ecbc7aeb4/start
DEBU[0273] container mounted via layerStore: /var/lib/docker/aufs/mnt/dc3b0eed21cc50303b76c4ed3d21bb0896b5c6c35a83aa61836637c6c4ca4c1e
DEBU[0273] Assigning addresses for endpoint web.1.inlwh3emp0jtisgzi3m8x25a4's interface on network bridge
DEBU[0273] RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])
DEBU[0273] Assigning addresses for endpoint web.1.inlwh3emp0jtisgzi3m8x25a4's interface on network bridge
DEBU[0273] Programming external connectivity on endpoint web.1.inlwh3emp0jtisgzi3m8x25a4 (65d826d4b1396aa6ff2414948569f97e62f0b259e5b1d23d58f3b14a9dd4fada)
DEBU[0273] secrets: setting up secret dir: /var/lib/docker/containers/061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f/secrets
DEBU[0273] injecting secret                              name=top-secret path="/var/lib/docker/containers/061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f/secrets/top-secret"
DEBU[0274] sandbox set key processing took 101.083812ms for container 061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f
DEBU[0274] libcontainerd: received containerd event: &types.Event{Type:"start-container", Id:"061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f", Status:0x0, Pid:"", Timestamp:(*timestamp.Timestamp)(0xc4212dab50)}
DEBU[0274] libcontainerd: event unhandled: type:"start-container" id:"061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f" timestamp:<seconds:1480415559 nanos:533152391 >
```

confirm the secret is _readable_ as well;

```bash
$ docker exec 061ecbc7aeb4 sh -c 'cat /run/secrets/top-secret'
hello world
```

**Describe the results you received:**

The secrets still accessible by the old task/container even if it's no longer part of the swarm

**Describe the results you expected:**

The secret should be destroyed when the node leaves the swarm. The
container should no longer be able to access the secret (or "read" / "decrypt" the secret)

**Output of `docker version`:**

Tested on current master (1ef10c8);

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   1ef10c8
 Built:        Tue Nov 29 10:27:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   1ef10c8
 Built:        Tue Nov 29 10:27:02 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

ping @diogomonica @cyli @ehazlett

**Comment by thaJeztah** [comment]
Note that even after a _new_ swarm is created on that node (`docker swarm init`), the container could be started and read the secrets.

**Comment by ehazlett** [comment]
This is behaving as expected.  Since the container never stops it has the mount.  Perhaps Swarm should track when it leaves and remove the tasks assigned to that node.  That would remove the container that has access to the secret(s).

**Comment by thaJeztah** [comment]
@ehazlett in this case, the container was stopped before `swarm leave`. The container could be started again, and even be stopped/started again after running `docker swarm init`.

Solution would probably be to make sure that _all_ tasks, including stopped ones, are removed on `docker swarm leave` (currently only running tasks are removed), but I wondered if different measures would be needed to explicitly invalidate the secrets.

**Comment by aaronlehmann** [comment]
It seems wrong if the container still has the mount after being stopped. We should definitely remove these mounts whenever a container stops.

**Comment by thaJeztah** [comment]
Not sure if the mounts are still there, but (see the logs above) they are injected again when the container starts;

```
DEBU[0273] secrets: setting up secret dir: /var/lib/docker/containers/061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f/secrets
DEBU[0273] injecting secret                              name=top-secret path="/var/lib/docker/containers/061ecbc7aeb4a11a309f1e3267cc27329de16164b97d52169de7b7111f82b36f/secrets/top-secret"
```

Which led me to think the secrets ("at rest"?) are still on the host

**Comment by ehazlett** [comment]
Ok I misread sorry.  I cannot reproduce locally.  I'm trying with the steps above.

**Comment by ehazlett** [comment]
I don't believe they are -- that is probably a bad log line where it should say "requesting secret"

**Comment by ehazlett** [comment]
Ok this is confirmed.  I'm investigating.

**Comment by diogomonica** [comment]
This should solve it: https://github.com/docker/swarmkit/pull/1758

**Comment by ehazlett** [comment]
thx @diogomonica

**Comment by diogomonica** [comment]
Let's make sure to try this again after it gets merged.

**Comment by ehazlett** [comment]
@diogomonica this should be resolved now correct?  It looks like the 1.13x branch has Swarmkit vendored at `99adeb1c6b33cebc81c31dd05b163080033062f2` which has this fix.

**Comment by aaronlehmann** [comment]
Yes, the fix has been vendored. @dongluochen tested and found that this resolved the issue. It wouldn't hurt to have someone double check, given the severity of this issue.

**Comment by thaJeztah** [comment]
oh, forgot about this one; yes `docker swarm leave --force` removes all containers from the host, so this issue is resolved.
