### ISSUE TITLE
docker can not push images 

### ISSUE THREAD

**Issue by linpf870208** [moby/moby#28932]
i just suddenly can not push images by docker push command.

```
1963422757ad: Pushing [==================================================>] 45.06 kB
5f70bf18a086: Layer already exists 
510e363c12a3: Layer already exists 
f09fdb5ddd25: Layer already exists 
a2ab78debd3e: Layer already exists 
66754d2993e3: Layer already exists 
b435f567e45e: Layer already exists 
df09ce9c9073: Layer already exists 
6eb35183d3b8: Layer already exists 
digest invalid: provided digest did not match uploaded content
```

```
docker -v
Docker version 1.12.3, build 6b644ec
```

```
docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 72
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: GDTW:Q2BH:OB3P:3YFX:KLAG:FVWB:6E3H:LDNS:GO57:UX3M:N3OU:EAGY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 62
 System Time: 2016-11-29T11:54:50.258301314Z
 EventsListeners: 1
Http Proxy: 172.16.19.13:8080
No Proxy: *.local、169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 172.16.19.22:5000
 127.0.0.0/8
```
it will retry a few times, then show digest invalid. 

anyone knows why?

**Comment by runcom** [comment]
Can you provide all the Docker info/version stuff, hard to say anything otherwise...

**Comment by linpf870208** [comment]
@runcom  ok

**Comment by thaJeztah** [comment]
could it be your "moby" VM is out of disk space?

/cc @justincormack is there an easy way to view this?

**Comment by runcom** [comment]
@linpf870208 could you tell us which image are you trying to push?

**Comment by justincormack** [comment]
Can you open an issue on https://github.com/docker/for-mac/issues

You can check for free space with `docker run alpine df -h`

**Comment by linpf870208** [comment]
@justincormack 

docker run alpine df -h
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine

3690ec4760f9: Pull complete 
Digest: sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Status: Downloaded newer image for alpine:latest
Filesystem                Size      Used Available Use% Mounted on
none                     59.0G      2.9G     53.1G   5% /
tmpfs                   998.9M         0    998.9M   0% /dev
tmpfs                   998.9M         0    998.9M   0% /sys/fs/cgroup
/dev/vda2                59.0G      2.9G     53.1G   5% /etc/resolv.conf
/dev/vda2                59.0G      2.9G     53.1G   5% /etc/hostname
/dev/vda2                59.0G      2.9G     53.1G   5% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   998.9M         0    998.9M   0% /proc/kcore
tmpfs                   998.9M         0    998.9M   0% /proc/timer_list
tmpfs                   998.9M         0    998.9M   0% /proc/sched_debug

OK

**Comment by linpf870208** [comment]
@runcom i build an local image by dockerfile

FROM 172.16.19.22:5000/node:6.9

RUN mkdir -p /parse-server
COPY ./ /parse-server/

RUN mkdir -p /parse-server/config
ADD ./local/config/config.json /parse-server/config/
VOLUME /parse-server/config

RUN mkdir -p /parse-server/cloud
ADD ./local/cloud/*.js /parse-server/cloud
VOLUME /parse-server/cloud

WORKDIR /parse-server

RUN npm config set registry https://registry.npm.taobao.org --global
RUN npm config set disturl https://npm.taobao.org/dist --global

# RUN npm install && \
#     npm run build

ENV PORT=1337

EXPOSE $PORT

ENTRYPOINT ["npm", "run", "start_trace", "--"]

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
