### ISSUE TITLE
Ubuntu Yakkety repository for docker is not working as expected

### ISSUE THREAD

**Issue by BartoszKosiorek-TomTom** [moby/moby#28942]
Ubuntu Yakkety repository for docker is not working as expected.
You could follow official instruction taken from:
https://docs.docker.com/engine/installation/linux/ubuntulinux/

and add docker repository to Yakkety:
 $ echo "<REPO>" | sudo tee /etc/apt/sources.list.d/docker.list

Unfortunately during displaying all available version of docker, none is displayed:
`$ apt-cache madison`
``
It is causing issues on script which is rely on that functionality (getting packages version from cache)

Also when I'm trying to install:
$ sudo apt-get install docker-engine 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-engine

**Comment by grfiv** [comment]
I found the same; changed to xenial and all was well ...

```
$ echo "deb https://apt.dockerproject.org/repo ubuntu-yakkety main" | tee /etc/apt/sources.list.d/docker.list
deb https://apt.dockerproject.org/repo ubuntu-yakkety main
$ apt-get update
          ...
Get:8 https://apt.dockerproject.org/repo ubuntu-yakkety InRelease [27.5 kB]
$ apt-cache policy docker-engine
N: Unable to locate package docker-engine

# but ...

$ vi /etc/apt/sources.list.d/docker.list
deb https://apt.dockerproject.org/repo ubuntu-xenial main
:x
$ apt-get update
$ apt-cache policy docker-engine
docker-engine:
  Installed: (none)
  Candidate: 1.12.3-0~xenial
  Version table:
     1.12.3-0~xenial 500
etc.
```

**Comment by andrewhsu** [comment]
I'll have a look.

/cc fyi @mlaventure

**Comment by vieux** [comment]
@gang65 Yakkety will be supported for 1.13 

It's not available yet for the stable release (1.12) only for the release candidates for the next one (1.13) on https://test.docker.com/

**Comment by thaJeztah** [comment]
Correct; an update to the documentation was published, but should not have been yet for the current docs

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
