### ISSUE TITLE
[1.13]: Volume plugins require access and control of dynamic device paths

### ISSUE THREAD

**Issue by srust** [moby/moby#28948]
**Summary**

*1.13: Volume plugins require access and control of dynamic device paths*

As currently designed, a volume plugin (the `docker plugin` infrastructure in docker 1.13) is allowed access only to devices that are specified in the static `config.json` file when the plugin is created (`docker plugin create`). Even if device specifications are allowed at runtime (`docker plugin enable / install`), the device list is essentially static, and all device paths must exist _before_ the plugin is executed. This limitation prevents a volume plugin from managing any type of dynamic device. Specifically, in a software defined storage environment, or cloud provider instance with elastic block storage, this is essentially a **SHOWSTOPPER** for volume plugins.

**History**

In Linux, all device nodes are essentially dynamic. Through the evolution of `udev`, a device driver basically presents a device to the kernel, which in turn triggers a `udev` event for the arrival of a new device node. It is `udev's` job to create the necessary device nodes, symlinks, and other paths that are considered the canonical device paths for the device. Once a storage target bus is enumerated, the device nodes are created, and the devices may then be used. Increasingly, however, virtual disks and remote network-attached storage are being deployed. Disks (and their devices) come and go at any time on a host, due to user request, administrator action, failure, bus re-enumeration, etc.

**Requirement**

For a volume plugin to be able to manage this class of block storage, it must be able to manage a dynamic set of block devices. A pre-defined static set just does not work, when the underlying system is by-nature dynamic. Particularly when the volume plugin itself can provide provisioning services, attaching devices at-will due to user request (`docker volume create -d plugin`), the plugin may be creating the device nodes itself. The plugin must have appropriate privileges (cgroups, etc) to open and access the dynamically created devices, as if the devices were known and given to the plugin at runtime. It is my assertion that these dynamic environments are _far_ more common than any static device environment, particularly for block storage.

**Examples**

As an example, consider a hypothetical `Amazon EBS` plugin. The volume plugin receives a `VolumeDriver.Create` and in turn calls an `Amazon API` to create an `EBS` volume, attaching it to the local instance. The device shows up on the system as `/dev/xvda` or similar, dynamically. The device previously did not exist on the system, so there is no way the volume plugin could have specified it ahead of time.

The same example can be expanded to any cloud provider with dynamic block storage, iSCSI attached storage, VMware vsphere attaching a new disk, and others. Containerized volume plugins (`docker plugin`) are currently not possible for managing block storage devices / volumes in these environments.

**Proposals**

To solve this problem, below are two proposals. Perhaps there are others. This is intended to start the discussion to come up with the best way to address this.

**Proposal 1: Allow device whitelist specification**

Allow a plugin configuration to whitelist device paths, rather than specifying static device paths. Any device matching the whitelist pattern would be manageable by the volume plugin container. The whitelist could be specified with wildcard as:

* `/dev/path*`
* `/dev/directory/prefix*`

Specifically this proposal does _NOT_ limit specification of device whitelisting to major / minor values. For block devices, particularly SCSI disk devices, the major number range is quite extensive and varying, depending on kernel version. Please see [https://www.kernel.org/doc/Documentation/devices.txt](https://www.kernel.org/doc/Documentation/devices.txt) for a _subset_ of the major number list, and take particular note of the different major number ranges for `SCSI disk devices`. Depending on disk usage on the host, a SCSI block device can be of any valid major number.

**Proposal 2: Allow a volume plugin to be _privileged_**

In the canonical `docker engine` meaning of _privileged_, a privileged container has access to all devices in the system. If a plugin were to `mknod` any block device that it required, the _privileged_ plugin could then open that device and manage it appropriately. No set of `capabilities` enables this same behavior as being _privileged_ does.

**Conclusion**

Without dynamic device support, volume plugins supporting (at least) software-defined block storage and elastic block storage cannot be containerized in the `docker` 1.13 `docker plugin` infrastructure. This would seem to affect a large percentage of potential uses for volume plugins. I do not see restarting the plugin, or launching a new plugin to be a valid option, particularly when the plugin itself may be doing the provisioning on behalf of the user.

Thanks for reading.  I’m looking forward to your feedback and alternative proposals to solve this problem.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 117
Server Version: 1.13.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 7.923 GB
 Data Space Total: 102 GB
 Data Space Available: 94.08 GB
 Metadata Space Used: 1.749 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.068 GB
 Thin Pool Minimum Free Space: 10.2 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.27-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: srust7.localnet
ID: MIUE:GKLN:L4OB:B2JU:OIPH:BTWO:L2P5:RQLP:F4DZ:GS5A:RHEH:PDCX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 29
 System Time: 2016-11-29T20:46:31.376495552Z
 EventsListeners: 0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
ping @tiborvass @anusha-ragunathan 

re: capabilities, "privileged" is something we specifically don't want to add. Plugins are low-level and ought to be explicit about what they need.
`--privileged` is "--cap-add ALL" and disables security profiles (selinux, apparmor, seccomp).... I'm not sure what all we are adding for plugins wrt sec profiles.

One should be able to `mknod` even from an unprivileged container.

**Comment by srust** [comment]
The proposal 1 is similar in spirit, I think, to functionality provided by #22563. Although reasoning is provided above to prefer a path-based approach as opposed to a major/minor approach.

**Comment by mlaventure** [comment]
the device cgroup only allows specifying device access via `major:minor` mechanism, to support path based whitelisting the daemon would have to continually monitor the targeted directory for changes via inotify (or similar) then generate an update to the relevant container cgroup rules before exec'ing into the container to mknod the device.

I personally would like to avoid such a scenario.

**Comment by mlaventure** [comment]
ping @anusha-ragunathan @tiborvass

**Comment by srust** [comment]
@mlaventure thanks for the reply! I do understand what you are saying.

Scoping this just to address the needs of a volume plugin, I think the potential impact and work needed in the short term could be small.

As the plugin infrastructure exists today:
1. the plugin can perform the mknod itself, by requesting CAP_MKNOD. In the plugins I am involved with, the device major/minor is available inside the plugin container, and the mknod is performed.
2. however, once the device node exists, opening/accessing it is restricted by cgroup.

This issue was filed and intended to solve point 2, as the plugin does not currently have the ability to request the permissions it needs.

So, another proposal to address this would be to simply allow a plugin developer to specify that the plugin can "manage block devices", and request that permission from the user at plugin install time.

If the plugin could specify a device whitelist in the `config.json` as such:

````
   "devices": [
        {
            "allow": true,
            "access": "rwm"
            "type": "b",
        }
    ]
````

For volume plugins managing block devices, that should be all they need..

Would something like that be more agreeable in the short term to solve the plugin case?

**Comment by mlaventure** [comment]
That'd be equivalent of addind `b *:* rwm` with my above PR. The difference being it'd be specified in the manifest of the plugin, wouldn't it?

I can think of a couple issues out of my head:
- It's a pretty broad range, and non storage devices can also be exposed as block devices which can be annoying.
- We also most certainly want to prevent raw access to the main device of the host to volumes plugins.

**Comment by srust** [comment]
I agree the broad range is not ideal.. just coming at it from an angle of simplicity, and ease of implementation for 1.13...

Okay, taking _what_ we can whitelist aside. Do you agree that some kind of **device whitelist** mechanism in the plugin manifest/config.json is in order? If so, that's great. And appropriately restricting the set of devices possible for whitelisting can come next..

Thanks!

**Comment by mlaventure** [comment]
I do agree that we need such a mechanism for volume plugins to be able to handle dynamic devices, yes :)

**Comment by srust** [comment]
@mlaventure Awesome! :)

I agree having a device whitelist is required -- coupled with a _docker reserved_ set of devices that are always denied. This would enable block storage plugins that manage block devices to use the 1.13 plugin infrastructure. Without it, I am afraid its a showstopper.

Re: reserved devices, believe me I've done this several times in the past and there are definitely some good heuristics that can be used to blacklist system or reserved devices, that a plugin would not be allowed to touch. That would be a great enhancement.

In the short term, I propose a phased approach to address this. Solving the immediate need, and enhancing it in the future.

**Phase 1**

Allow a plugin `config.json` manifest to specify a device whitelist by major/minor and type. Borrowing from the current syntax, this would be specified as:

````
"linux": {
    "devices": [
        {
            "type": "b",
            "major": 8,
            "allow": true
        },
        {
            "type": "b",
            "major": 65,
            "allow": true
        },
    ]
}
````

This alternative form of device specification allows whitelisting by major/minor.

**Phase 2**

Docker reserves system devices. Entries in the `devices.deny` cgroup are added for a plugin for the reserved devices.

**Phase 3**

Okay, call me crazy, but I think something like the following would be an ideal enhancement in the future.

A driver specifies in their device whitelist array a set of `udev` attributes (a subset of which docker would allow to be specififed) for the devices. This would allow for whitelisting devices by vendor, model, path prefix, etc.

Specification such as:

````
"devices": [
    {
        "ID_MODEL": "S630DC-400",
    },
    {
        "DEVNAME": "/dev/sd*",
    },
]
````

Imagine that these udev attributes are then written to a `udev` rules file and dropped onto the system. When a device is dynamically added to the system, there is no inotify or directory watching mechanism needed, the udev rule is triggered by the kernel, and that rule could issue any command to notify docker to take action at that time that a new device was added. The appropriate cgroup `devices.allow` is then modified for the plugin container. And even potentially do the `mknod` at that point, as well.

The `udev` rule can be written to send docker the device path to whitelist and the plugin it belongs to. Using the above example, a sample rules file could be written:

````
ACTION=="add|change", SUBSYSTEM=="block", ENV{ID_MODEL}=="S630DC-400", ENV{DEVNAME}=="/dev/sd*", RUN+="/docker/add/device-to-plugin $env{DEVNAME} my/plugin"
````

Anyway, that would seem to be pretty cool for a future enhancement..

**1.13**

But for the immediate needs, I'd like to get some feedback on doing a Phase 1 (or similar. maybe borrowing some from #22563?) in the immediate timeframe. In my mind this is required for 1.13, as without it these class of plugins cannot request the permissions they need to operate. What do you think, @mlaventure @cpuguy83 @anusha-ragunathan @tiborvass @vieux ?

If phase 2 is part of that initial work (to allow devices to be reserved from plugins view) that is great too.

Thoughts?

Thanks.

**Comment by cpuguy83** [comment]
ping @mlaventure

**Comment by tiborvass** [comment]
@srust sorry for the late response.

We agree with the solution you suggested in phase1, it's more future-proof. We'll send out a PR shortly and prioritize it for 1.13.0 as I see how it can be a big need for plugin authors. Thanks for your input.

As for phase 2, would you mind elaborating a bit more?

And for phase 3, that's a bigger suggestion that we'll have to leave open. And if we implemented it, it would need to be done for regular containers too.

**Comment by srust** [comment]
awesome @tiborvass! Thanks.

The phase 2 came down to restricting the set of devices that a user/container could whitelist. This would prevent things like the device hosting the root filesystem, other mounted devices, lvm volumes, the docker image store devices, and so forth. It is perhaps worth it to think about how to handle those restrictions up front, but was prioritized as phase 2 as it isn't strictly required in order to enable a device whitelisting mechanism for plugins.

**Comment by khudgins** [comment]
Seems like there's already a phase 0 available. In the docs at

https://github.com/docker/docker/blob/master/docs/extend/config.md

looks like there's a "DeviceCreation" keyword in the Linux section of config.json. I've talked with @anusha-ragunathan and she's confirmed that, if set to true, the plugin has access to any device on the host.

The above-referenced #30014 is a change to make the keyword more obvious.

**Comment by tiborvass** [comment]
@khudgins @srust I'm trying to rename it to `AllowAllDevices` to make it clearer.

**Comment by sitamet** [comment]
I'm currently working on [docker-volume-rbd](https://github.com/wetopi/docker-volume-rbd)

In order to give access to dynamic dev we mount it:

[... config.json](https://github.com/wetopi/docker-volume-rbd/blob/master/config.json)

```bash
    "linux": {
        "AllowAllDevices": true,
        "capabilities": [
            "CAP_SYS_ADMIN"
        ],
        "devices": null
    },
    "mounts": [
        {
            "source": "/lib/modules",
            "destination": "/lib/modules",
            "type": "bind",
            "options": [
                "rbind"
            ]
        },
        {
            "source": "/dev",
            "destination": "/dev",
            "type": "bind",
            "options": [
                "rbind"
            ]
        },
        {
            "source": "/sys",
            "destination": "/sys",
            "type": "bind",
            "options": [
                "rbind"
            ]
        }
    ],
```

**Comment by anusha-ragunathan** [comment]
Issue has been long resolved
