### ISSUE TITLE
Should protect intermediate image when do docker build

### ISSUE THREAD

**Issue by lovemyliwu** [moby/moby#29011]
**Description**

when do `docker build` the intermediate image not protected! This is a big issue when do `docker rmi <none>:<none>` at the same time!

the real example is in our CI system, we have two jobs, one for build image and one for clean images.

**Steps to reproduce the issue:**
1. do `docker build`
2. do `docker rmi <none>:<none>` at the same time
3. docker build will fail due to intermediate image removed by `docker rmi`

**Describe the results you received:**

docker build fail

**Describe the results you expected:**

docker build success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 8
 Paused: 0
 Stopped: 9
Images: 45
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 170
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 1.952 GiB
Name: moby
ID: FYWR:2TN5:XXJD:OYS6:GWJX:YSZY:ZQVK:GO5J:NV2L:LEOW:Y4AA:IIXZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 62
 Goroutines: 100
 System Time: 2016-12-01T05:14:17.493898224Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

jenkins ci

**Comment by thaJeztah** [comment]
```
docker build -t foobar .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM alpine
 ---> baa5d63471ea
Step 2/3 : RUN echo "foo"
 ---> Running in f73e5d7413b8
foo
 ---> e3df98b90edd
Removing intermediate container f73e5d7413b8
Step 3/3 : RUN echo "bar"
 ---> Running in 273d58206a6c
bar
 ---> 48f9a0da6b41
Removing intermediate container 273d58206a6c
Successfully built 48f9a0da6b41
```

I'm not sure this would be easy to fix. Basically, between build steps, there is a short window where the intermediate container is committed to an image (`---> baa5d63471ea`), and the next intermediate container is started from that image (`---> Running in 273d58206a6c`). During that time, there is no container using the image, nor is there a "child" image using it, so it is "dangling".

Possibly we should have a way to specify a filter for "minimum age" for images, to reduce the possibility of this happening, which can be added to the `docker image prune` command that's added in docker 1.13. Such an option would not prevent repeated builds that use a "cached" image (which can be older than that "age")

Also, disabling auto-removal of the intermediate containers (`docker build --rm=false`), may help a bit, but you'd have to manually clean up the intermediate containers afterwards

**Comment by kkeane** [comment]
I wanted to chime in and say that the same issue also exists with docker image prune. Since it seems to be the same underlying cause, I do not want to open a new issue.

**Comment by thaJeztah** [comment]
I don't think this is an issue with buildkit, 
Let me close this ticket for now, as it looks like it went stale.
