### ISSUE TITLE
Overlay networking VXLAN ARP and intermittent connectivity failures

### ISSUE THREAD

**Issue by loginoff** [moby/moby#29024]
**Description**
A brief description of our setup:
- We are running a three node Swarm cluster using Ubuntu 16.04 VMs.
- We use the "old" Swarm version 1.2.4 (5d5f7f0) with progrium/consul as the datastore. 
- On each node we run a swarm-manager, a swarm-agent and a consul instance all inside containers.
- We utilize a single overlay network so that containers on all three hosts can communicate freely with each other using container names as DNS names.
- We create containers in the Swarm from a fourth host using the Swarm remote API and docker-compose. This is the main reason we don't use "swarm mode", AFAIK there is no way to use docker-compose remotely with "swarm mode".

We are experiencing intermittent connection failures on containers attached to the overlay network. The symptoms are that some containers just lose all network connectivity for 1-10 seconds and afterwards everything returns to normal.

**Steps to reproduce the issue:**
This happens between seemingly arbitrary intervals: sometimes every other day, sometimes once or twice a week. We have not yet found a way to reproduce it reliably or at all for that matter.

**Additional information you deem important (e.g. issue happens only occasionally):**
Today we had a longer outage and I managed to gather some more information while the outage was occurring for 3 or 4 containers connected to the overlay network:
- All the affected containers were running on the same Docker host
- On the affected host I went into the namespace of the overlay network (nsenter --net=/var/run/docker...) and executed "ip monitor":
dev veth7 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:07 REACHABLE
dev veth7 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:05 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth5 lladdr 02:42:0a:00:00:05 REACHABLE
dev veth7 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:07 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth7 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:07 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:05 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:22 REACHABLE
dev veth16 lladdr 02:42:0a:00:00:22 REACHABLE

Here you can see the MAC addresses of the affected containers. It's as though their routing is constantly being switched around between the vxlan interface and their local veth interface.
Some containers experienced this kind of switching more often than others.
Am I correct in assuming that this shouldn't happen (since they are on the same host) and that this is the underlying cause of the connectivity issues?

We are also running the Docker daemons in debug mode on all hosts, but have found nothing out of the ordinary in the logs, even when this issue is occurring.

After restarting the affected containers, they get a new MAC address and the issue goes away (for a while), but we are afraid that it can hit us again at any moment.

This is a critical production setup for us, so any advice is greatly appreciated. Also please let me know if we can provide you with any additional information.

PS
Despite this issue, we really love what you guys are doing with the platform - keep up the great work :)

**Output of `docker version`:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
root@prod-docker3:~/incident# docker info
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 130
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.42 GiB
Name: prod-docker3
ID: GVNR:4JUL:ZFXX:X6T2:HPSL:KP5R:6YFM:K4J3:3KUJ:2KS5:NZBA:EAEN
Docker Root Dir: /docker-storage/docker-runtime
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 142
 Goroutines: 218
 System Time: 2016-12-01T09:18:43.145998783Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster Store: consul://localhost:8500
Cluster Advertise: 10.0.11.13:2376
Insecure Registries:
 127.0.0.0/8

**Update:**
I can confirm that the same issue occurs with version 1.13 and 17.03.0-ce as well, but only when creating overlay networks using an external cluster store.

**Comment by loginoff** [comment]
I can confirm that the same issue occurs with version 17.03.0-ce as well, but only when creating overlay networks using an external cluster store.

I believe that I have managed to track down the root cause, here's what I did:
1. Setup a three node Docker cluster: --cluster-store=consul://localhost:8500 with Consul running inside a container on each node (with --net=host)
2. docker network create -d overlay overlaytest
3. Create a container attached to this overlay network on each host named test1 - test3

At this point everything works exactly as it should - all the containers on different hosts can ping each other just fine.
```
root@docker1:~# docker network inspect overlaytest
[
    {
        "Name": "overlaytest",
        "Id": "433dd31985eca2ebb09d1bc013c1c2f29bec7fbe5f5d3e519c8ec20e47199f0b",
        "Created": "2017-03-07T16:47:08.851496678Z",
        "Scope": "global",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "0a492108bd112b0d52cd8203cde3b91d671b7818a5af8f3d0a6ae1b025445852": {
                "Name": "test1",
                "EndpointID": "448a8b7185c847e7a7dfc34ac4d4ac5b40a83ace6bc4061a7963a6b7bf31edac",
                "MacAddress": "02:42:0a:00:00:04",
                "IPv4Address": "10.0.0.4/24",
                "IPv6Address": ""
            },
            "ep-a8b03be235e4225babafad46802ad8703942cca46204423fc0f5ced2851613b8": {
                "Name": "test2",
                "EndpointID": "a8b03be235e4225babafad46802ad8703942cca46204423fc0f5ced2851613b8",
                "MacAddress": "02:42:0a:00:00:02",
                "IPv4Address": "10.0.0.2/24",
                "IPv6Address": ""
            },
            "ep-bf138e0b6c623eb9b89dfdea9d6ba2c4215891a689a33cc2fd665f98598b0cd4": {
                "Name": "test3",
                "EndpointID": "bf138e0b6c623eb9b89dfdea9d6ba2c4215891a689a33cc2fd665f98598b0cd4",
                "MacAddress": "02:42:0a:00:00:03",
                "IPv4Address": "10.0.0.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

Now on node1, I'll enter the network namespace of the overlay network "overlaytest" 
nsenter --net=/var/run/docker/netns/1-433dd31985

Let's have a look at the bridge forwarding table
```
root@docker1:~# bridge fdb show
33:33:00:00:00:01 dev br0 self permanent
01:00:5e:00:00:01 dev br0 self permanent
33:33:ff:76:eb:eb dev br0 self permanent
5a:1d:77:da:b5:eb dev vxlan1 master br0 permanent
5a:1d:77:da:b5:eb dev vxlan1 vlan 1 master br0 permanent
02:42:0a:00:00:03 dev vxlan1 dst 10.10.31.13 link-netnsid 0 self permanent <---test3
02:42:0a:00:00:02 dev vxlan1 dst 10.10.30.12 link-netnsid 0 self permanent <---test2
5a:48:e2:5a:07:7f dev veth2 master br0 permanent
5a:48:e2:5a:07:7f dev veth2 vlan 1 master br0 permanent
33:33:00:00:00:01 dev veth2 self permanent
01:00:5e:00:00:01 dev veth2 self permanent
33:33:ff:5a:07:7f dev veth2 self permanent
```
I have highlighted the correct entries in the forwarding table that point to containers running on remote nodes. Again everything works fine and I can ping test2 and test3 from test1.
Things start to get weird once I create and attach a new container to "overlaytest" on node1, let's call it "test1_2".
Once I ping "test1_2" from "test1" the bridge forwarding table looks like this:
```
root@docker1:~# bridge fdb show                                                                                                     
33:33:00:00:00:01 dev br0 self permanent
01:00:5e:00:00:01 dev br0 self permanent
33:33:ff:76:eb:eb dev br0 self permanent
5a:1d:77:da:b5:eb dev vxlan1 master br0 permanent
5a:1d:77:da:b5:eb dev vxlan1 vlan 1 master br0 permanent
02:42:0a:00:00:03 dev vxlan1 dst 10.10.31.13 link-netnsid 0 self permanent
02:42:0a:00:00:02 dev vxlan1 dst 10.10.30.12 link-netnsid 0 self permanent
02:42:0a:00:00:05 dev vxlan1 dst 10.10.30.11 link-netnsid 0 self permanent <---test1_2
5a:48:e2:5a:07:7f dev veth2 master br0 permanent
02:42:0a:00:00:04 dev veth2 master br0
5a:48:e2:5a:07:7f dev veth2 vlan 1 master br0 permanent
33:33:00:00:00:01 dev veth2 self permanent
01:00:5e:00:00:01 dev veth2 self permanent
33:33:ff:5a:07:7f dev veth2 self permanent
02:42:0a:00:00:05 dev veth3 master br0 <---test1_2
22:e0:69:bf:c8:95 dev veth3 vlan 1 master br0 permanent
22:e0:69:bf:c8:95 dev veth3 master br0 permanent
33:33:00:00:00:01 dev veth3 self permanent
01:00:5e:00:00:01 dev veth3 self permanent
33:33:ff:bf:c8:95 dev veth3 self permanent
```
As you can see for some reason the entry
02:42:0a:00:00:05 dev vxlan1 dst 10.10.30.11 link-netnsid 0 self permanent
got added to the bridge forwarding table pointing the local container to go over the vxlan1 interface, when it would suffice to have just the entry:
02:42:0a:00:00:05 dev veth3 master br0

Having the dev vxlan1 entry for local containers causes problems with ARP. After I wait for the ARP cache of "test1" to clear, I try to ping "test1_2" again. At the beginning of the ping a lot of packets are dropped.
At the same time, I'm monitoring the network namespace of "overlaytest" with "ip monitor":
```miss 10.0.0.5 dev vxlan1  STALE
10.0.0.5 dev vxlan1 lladdr 02:42:0a:00:00:05 PERMANENT
??? dev vxlan1 lladdr 02:42:0a:00:00:05 PERMANENT
dev vxlan1 lladdr 02:42:0a:00:00:05 PERMANENT
Deleted dev vxlan1 lladdr 02:42:0a:00:00:02 STALE
Deleted dev vxlan1 lladdr 02:42:0a:00:00:03 STALE
Deleted dev veth1f8d99b lladdr 02:42:0a:00:00:05 STALE
Deleted dev veth2 lladdr 02:42:0a:00:00:04 STALE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
??? dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth1f8d99b lladdr 02:42:0a:00:00:05 REACHABLE
??? dev vxlan1 lladdr 02:42:0a:00:00:05 PERMANENT
dev vxlan1 lladdr 02:42:0a:00:00:05 REACHABLE
dev veth1f8d99b lladdr 02:42:0a:00:00:05 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:05 REACHABLE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth1f8d99b lladdr 02:42:0a:00:00:05 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:05 REACHABLE
dev vxlan1 lladdr 02:42:0a:00:00:04 REACHABLE
dev veth1f8d99b lladdr 02:42:0a:00:00:05 REACHABLE
miss 10.0.0.4 dev vxlan1  STALE
10.0.0.4 dev vxlan1 lladdr 02:42:0a:00:00:04 PERMANENT
??? dev vxlan1 lladdr 02:42:0a:00:00:04 PERMANENT
dev vxlan1 lladdr 02:42:0a:00:00:04 PERMANENT
dev veth2 lladdr 02:42:0a:00:00:04 REACHABLE
```

Having the dev vxlan entry for node local containers causes duplicate ARP replies - one from the actual veth interface connected to the container and from from vxlan1 interface (is the vxlan1 interface doing "proxy arp"?). 
Each time one of the ARP replies goes through br0, the bridge forwarding table updates itself. In case the ARP reply from vxlan1 arrives later, all subsequent packets, that should be bridged to the veth interface of the container, get bridged to vxlan1 instead, causing the packet loss.

I tried manually deleting the dev vxlan1 entries from the bridge forwarding table for containers local to a node. Although the entries got deleted, it didn't stop the ARP replies from vxlan1 for the respective containers.
Is there any way of stopping vxlan1 from sending out ARP replies for local containers?

**Comment by loginoff** [comment]
I found a workaround to stop vxlan1 from sending ARP replies to local containers.
It does not seem necessary to remove the forwarding table entries from br0.

On each node, figure out the IP addresses of containers running locally on that node. Then inside the network namespace of the overlay network, just remove the static permanent ARP entries for these IP addresses for the vxlan1 interface:
`arp -d  [IP address of local container] -i vxlan1`

Of course this works only until the containers are recreated (it does seem to work with container restarts, however). Still it should be a viable workaround for production systems, where updating the entire networking layer requires some planning and testing beforehand.

I used the following one-liner on each node in the Swarm to carry out the removal of static ARP entries described above:
```
for i in $(arp -i vxlan1 | grep -f <(bridge fdb show | grep -E "NODE_IP|127.0.0.1" | awk '{print $1}') | awk '{print $1}'); do arp -d $i -i vxlan1; done
```

**Comment by thaJeztah** [comment]
ping @aboch @sanimej PTAL

**Comment by dongluochen** [comment]
I was tracking another issue in Swarm mode where requests would be lost for ~10 seconds after container is added to IPVS https://github.com/docker/docker/issues/30321#issuecomment-289527063. I suspect the issue is VTEP records for local node are added to peerdb and cause switching error. The following patch seems to fix this issue. 

```
diff --git a/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go b/vendor/github.com/docker/libnetwor
index adc370f..4a7174a 100644
--- a/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go
+++ b/vendor/github.com/docker/libnetwork/drivers/overlay/peerdb.go
@@ -273,6 +273,11 @@ func (d *driver) peerAdd(nid, eid string, peerIP net.IP, peerIPMask net.IPMask,
        if sbox == nil {
                return nil
        }
+       // only add remote entries to peerdb
+       // this is a test. The proper fix should update entry.isLocal.
+       if vtep.Equal(net.ParseIP(d.advertiseAddress)) || vtep.IsLoopback() {
+               return nil
+       }

        IP := &net.IPNet{
                IP:   peerIP,
```

**Comment by tgeens** [comment]
@loginoff thanks you for your analysis and workaround!

@thaJeztah is docker still interested in fixing bugs in the external overlay network ?

**Comment by thaJeztah** [comment]
@tgeens if @dongluochen's patch resolves the issue, possibly it can be considered by the libnetwork team. We didn't get confirmation from @loginoff if it resolved his issue

**Comment by loginoff** [comment]
Sadly I do not have access to an environment where to test out the patch.
We have since rebuilt all our environments to use swarm mode --attachable overlay networks instead.  Swarm mode overlay networks do no seem to exhibit this particular issue.

We are still using the old standalone Swarm manager to manage our individual Docker hosts and only utilize swarm mode for the creation of overlay networks. This seems a little hacky, but required minimal changes to our existing entirely docker-compose based deployment flow.

Also the concept of a Swarm manager exposing the exact same remote API over n Docker hosts as a single Docker host just seemed so utterly brilliant. I'm incredibly sad to see this being ditched for the UX of the new swarm mode. Swarm mode, while being an incredible technical feat on it's own, would be just amazing, if it would have stuck to the "old" concepts.

**Comment by thaJeztah** [comment]
Thanks for the update @loginoff! 
Given that we don't have access to the environment to test, I'll go ahead and close this issue
