### ISSUE TITLE
Add the completion file to .deb package

### ISSUE THREAD

**Issue by franklinyu** [moby/moby#29052]
I installed Docker via https://apt.dockerproject.org/repo. After installation, the completion file for Bash is not in `/etc/bash_completion.d`; I have to install it manually (with `curl`). I think it should be installed by the package, or at least the completion file should be provided somewhere (so that I can symlink to it). I searched `/usr/share/docker-engine/contrib/` but the `completion` folder is not there.

Note: For Zsh I installed the completion in `/usr/local/share/zsh/site-functions/`, but I guess (from folder name) that the `.deb` package should install the completion in `/usr/share/zsh/vendor-completions`.

**Comment by thaJeztah** [comment]
This PR https://github.com/docker/docker/pull/27735 adds the completion scripts to the `.tgz. downloads, perhaps we _can_ do the same for the `.deb` / `.rpm`

/cc @andrewhsu @justincormack

**Comment by thaJeztah** [comment]
I think this is now the case; https://github.com/docker/docker-ce-packaging/blob/33325c8a2598c94bc5136a9fe7213e3ebe152dd7/rpm/fedora-26/docker-ce.spec#L109-L115

and https://github.com/docker/docker-ce-packaging/blob/50c7ac954e520fc9270cc765d3c11afb5b261154/deb/common/docker-ce.install#L5-L6, https://github.com/docker/docker-ce-packaging/blob/7416a7521a6ad21c7925237230d26855c76b222f/deb/common/docker-ce.bash-completion#L1

Closing, but feel free to comment if it's still an issue
