### ISSUE TITLE
Implementation of shared storage graphdriver

### ISSUE THREAD

**Issue by bacaldwell** [moby/moby#29080]
## What is different from previous issues/ideas
1. It doesn't try to share /var/lib/docker. Image layers are stored on a separate mount if shared 
2. It is agnostic to chosen shared filesystem
3. Changes are isolated to graphdriver code (except for RO mount function in pkg/loopback)
3. Implementation is functional and based on HEAD of master(as of Dec 1)

## Goals
1. Storage of image layers on common cluster filesystems
2. Share image layers between docker daemons on different hosts
3. Provide layered image abstraction on top of filesystems that don't support overlayfs

## Proposal
- A loop_overlay2 graphdriver than stores layers as loopback images (XFS) and merges layers together using overlayfs for running containers

## Implementation
Docker fork:
https://github.com/bacaldwell/docker/tree/stateless4
Graphdriver code:
https://github.com/bacaldwell/docker/commit/48159c8376c23da850f266423a7bb133a00a794d
README:
https://github.com/bacaldwell/docker/blob/stateless4/daemon/graphdriver/loop_overlay2/README.md

## Features of loop_overlay2
- Layers are mounted on-demand as loopback devices
  - Read-write mode for ApplyDiff
  - Read-only for Get
- Upper writable layer for the container resides in /var/lib/docker. On 'docker commit', the upper layer gets written to a loopback device
- The scheme from the overlay2 driver is reused for multiple read-only lower layers identified by symbolic links to maximize number of layers supported
- Supports a common cluster computing/high performance computing shared filesystem organization scheme that allows a set of layers (and associated Layer Store) to be shared read-only, and protected by UNIX access permissions. When root Layer Store is not writable, a configurable fallback location is used for storing layers added by the daemon. This can be persistent or ephemeral. On graph driver initialization, the stores are merged into a new store (using overlayfs) in the daemon's expected place (e.g. /var/lib/docker/image)

## Target use case
Cluster environments, especially high-performance computing environments, already have shared filesystems such as NFS, Lustre, or GPFS. The distributed and parallel variants Lustre and GPFS may have petabytes of storage capacity, are designed to be highly reliable, and shared by tens of thousands of nodes. Furthermore, due to complexity and failure rate concerns, nodes that share these filesystems are often "diskless" or "stateless" nodes without any local persistent disks.
- The loop_overlay2 graphdriver allows these "stateless" nodes to run Docker and on startup, have a consistent view of images available on shared storage.
- Changes made by "stateless" nodes can be captured in a per-node/per-user directory on shared storage or in a ramdisk (ephemeral)
- Note that the use of loopback devices mitigate excessive metadata traffic and leverage the block performance of parallel filesystems

## Related issues
#9935
#15887

# Presentation with early architecture
https://www.youtube.com/watch?v=8yfMd96ll4s

## Status
Feature-complete and passes most integration tests. One test that elicits race conditions (DockerSuite.TestEventsLimit) is problematic. Despite refcounting loopback mounts, sometimes mounting a layer returns device or resource busy

**Comment by aashidham** [comment]
Hey @bacaldwell now that Linux 4.5 is patched to be able to support overlayfs directly with nfs (http://www.spinics.net/lists/linux-fsdevel/msg93672.html), I'm curious if this needs to be used directly, or if there is a runtime option that can be set with the overlay2 driver to store the "lower" image layers on a seperate nfs mount.

**Comment by caengcjd** [comment]
Wow,you must be a geek!owesome idea,I need it too much!!

**Comment by caengcjd** [comment]
Oh dear,I build your source code (the stateless4 branch), how do I start the daemon?The driver  have  no loop_overlay2 option.What can I do ?

**Comment by caengcjd** [comment]
This is my log:
 ./dockerd     -s   loop_overlay2
INFO[0000] libcontainerd: new containerd process, pid: 25792 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
WARN[0001] Unable to locate plugin: loop_overlay2, retrying in 1s 
WARN[0002] Unable to locate plugin: loop_overlay2, retrying in 2s 
WARN[0004] Unable to locate plugin: loop_overlay2, retrying in 4s 
WARN[0008] Unable to locate plugin: loop_overlay2, retrying in 8s 
ERRO[0016] Failed to GetDriver graph loop_overlay2 /var/lib/docker 
Error starting daemon: error initializing graphdriver: driver not supported

**Comment by archfz** [comment]
Is this still not possible?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
