### ISSUE TITLE
Create tutorial for multi-host swarm

### ISSUE THREAD

**Issue by 0zeroth** [moby/moby#29118]
As far as I can tell all tutorials are for sandbox style swarm where multiple VMs run on a single physical host. I can't find a good resource that gives a simple tutorial on getting a swarm running across more than one physical machine. Maybe this would need to be done per OS, as my understanding is Windows and MacOS don't support this natively, but do when using docker-machine.

In an ideal tutorial, I think a user should be able to follow the commands on their OS, and get a swarm running across two physical hosts. 

From my Windows OS perspective, questions I'd like answered in such a tutorial (as these are areas where I'm stuck after looking at the current tutorials and also production swarm docs):
* On Windows must I (or is it best practice to) use `docker-machine create --swarm etc`
* What is the relationship between `docker-machine create --swarm etc`, `docker swarm etc`, `docker run swarm etc`. After trial and error I think I understand how the layers build upon each other, but an explicit description would be nice

As a final bit of context to this request, I'm trying to set up a two node swarm across two Windows hosts. I think I must use `docker-machine create --swarm etc` - and everything appears to work OK except the worker node is stuck in pending. I _think_ this is because TLS is enabled by default (and it can't be disabled, or disabling is too dangerous to provide any explanation of how to do it :P ) so that's my next thing to try... but it would be nice if there was a quick one pager that pointed out all the relevant steps.

**Comment by AkihiroSuda** [comment]
There are two things called "Swarm"
https://github.com/docker/swarm#swarm-disambiguation

`docker-machine create --swarm` and `docker run swarm` are for "Docker Swarm standalone" (sometimes called "Swarm classic"), but `docker swarm etc` is for the built-in Swarm-mode feature (available in Docker >= 1.12), which is based on Swarmkit.

**Comment by AkihiroSuda** [comment]
Probably this article is helpful for you: https://stefanscherer.github.io/build-your-local-windows-docker-swarm/

Note that
* Docker Machine does not support creating Windows VMs yet. So even if you want to use "Docker Swarm standalone", you won't be able to use `docker-machine create --swarm`
* Swarm-mode does not support Windows  yet

**Comment by 0zeroth** [comment]
@AkihiroSuda Thanks for your reply. It sounds like you are saying "with Windows on the physical hosts it is not possible to create a mutli-physical-host cluster". Is this correct?

I just want to clarify that using `docker-machine create --swarm etc` seems to work fine, and I get a bit of swarm communication that appears to fail on TLS certificates (docker info on the master shows nodes in pending state, a commonly reported 'bug' caused by TLS issues). In particular,  `/var/log/boot2docker` on  node01 ends with `Need TLS certs for node01`, and there is similar message on master01

Looking at `/var/lib/boot2docker/profile` it seems some sort of certificates have been set up, but I'm unsure what docker-machine is trying to do by default so I'm unsure how to proceed further. Its not obvious to me where I would go about adding/replacing certificates or trying to disable TLS.

As a final note, since this thread seems to be turning into me asking for help for my specific problems, I can at least offer that if I can find a solution I'll post a reproducible recipe for multi-host swarm using docker-engine and more than one physical Windows host.

**Comment by AkihiroSuda** [comment]
Maybe I misread your comments about "Windows"..

Just to make it clear, are you trying to use Linux containers on Linux VMs on physical Windows hosts? (So, it is not attempt to "running Windows containers on Windows VMs on Windows hosts"? I misread so in my previous comment)

**Comment by 0zeroth** [comment]
Linux container on a Linux VM on a physical Windows host.
The Linux VM is boot2docker-  provisioned using docker-machine.
After more digging, I'm becoming convinced I need to install TLS certificates, since docker-machine creates TLS enabled VMs by default. See [boot2docker issue 347](https://github.com/boot2docker/boot2docker/issues/347)

IMO this strengthens the need for a good tutorial that covers multi-physical-host swarm. I suspect there will be many users interested in a small cluster (possibly using Windows which required docker-engine or maybe wanting to use docker-engine to create better separation between environments) rather than jumping straight from single physical machine to a cloud provider- and debugging and diagnosing these problems seem complex enough to me to warrant some hand-holding.
