### ISSUE TITLE
cli ignores invalid names

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#29126]
I noticed this when writing https://github.com/docker/docker/issues/29125, and found that it's an issue with all commands.

When calling `rm` commands with an invalid name, no delete takes place, but the CLI prints the given name, leading to the suggestion that the delete was successful;

```bash
$ docker secret rm ../containers/foo
../containers/foo

$ docker rm ../networks/foo
../networks/foo

$ docker network rm ../containers/foo
../containers/foo
```

Note that nothing _bad_ happens, i.e., no API call is attempted to `DELETE /v1.26/containers/foo`, so it looks like the call is blocked inside the client. However, the feedback on the CLI is misleading.

**Comment by ripcurld0** [comment]
@thaJeztah I easily reproduce it on my machine:
```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   9c96768-unsupported
 Built:        Wed Jan 11 15:17:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   9c96768-unsupported
 Built:        Wed Jan 11 15:17:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

I think I have an idea why it happens:
* When providing a container name that starts with two dots: `..`, the client sends a request to DELETE /vX.YZ/containers/**../container_name** 
* The daemon [can't find a match to this path](https://github.com/docker/docker/blob/master/vendor/github.com/gorilla/mux/mux.go#L77-L88) (after cleaning it -- /vX.YZ/container_name) and responds with status code 301 (Moved Permanently).
* The client doesn't consider status code 301 as an error and prints all the `opts.containers`, which are the containers given in the `rm` command.

I think I have a workaround for that, though.

**Comment by ripcurld0** [comment]
#dibs

**Comment by ripcurld0** [comment]
I think #32127 fixes this and thus it can be closed.
@thaJeztah

**Comment by thaJeztah** [comment]
Yup, looks like it :+1:
