### ISSUE TITLE
Pluggable RAFT-compatible external KV store for Swarm Mode

### ISSUE THREAD

**Issue by bklau** [moby/moby#29140]
See https://github.com/docker/swarmkit/issues/1412 for background.

Proposal:
 That Swarm Mode have the ability to accept some pluggable means for a RAFT-compatible external KV store:
1. User may already use a store like Consul for storing other metadatas and would like to reuse the **SAME** store for Swarm Mode.
2. Allows other third-party RAFT-compatible KV store to be in the play instead of just using ETCD by default.
Avoids violation of the "Batteries Included" principle espoused by Docker and promotes innovation and best-of-breed softwares.
(See https://raft.github.io/ for various implementation)

**Comment by cpuguy83** [comment]
@bklau swarmkit does not use a K/V store. It is not using etcd.
Swarmkit uses the same raft implementation that etcd uses. These are two very different things.

It does not make much sense for swarm to support swappable raft backends.
This is like asking the consul team to support etcd's raft implementation.

**Comment by AkihiroSuda** [comment]
What is your motivation to use another raft backend?

If you want to store some metadata about your cluster in the raft storage, you can use Annotations: https://github.com/docker/infrakit/blob/master/pkg/store/swarm/swarm.go
(Note that it should not be abused to store huge data)

**Comment by bklau** [comment]
The problem we are facing is that before SwarmKit or Swarm Mode ever exists, we uses the old standalone Swarm  with Consul backing to create our own service "orchestration" layer. Since externally backed KV store and Swarm Mode( which uses SwarmKit) are **mutually exclusive**, this puts us in the bind.
We would like to move to Swarm Mode and possibly  adapt/wrap our orchestration later to use SwarmMode infra, but we also need to store some data like we used to when we had the external Consul KV store.
So that's the motivation. It had been somewhat of a frustration...

**Comment by cpuguy83** [comment]
@bklau One way around this is to create the network in swarm mode, then you can enable containers to attach to it by setting `--attachable` on network create. There are some security implications around this (worker nodes can now create new containers on the swarm-mode network themselves), but could be an option for you.

Example:

```
$ docker network create --attachable --driver overlay myNet
$ docker run -d --network myNet busybox top
$ docker network connect myNet someExistingContainer
```

This can provide the migration path you are looking for.

**Note**: this is for Docker 1.13

**Comment by bklau** [comment]
@cpuguy83 : Brian, not sure if it solve our problem entirely since the external KV store that we used needs to be factored in. We used it to store orchestration data/metadata.My understanding is that you cannot have both external KV store and Swarm Mode co-existing at same time. That's crux of the problem. Would be nice if  Swarm Mode has a "thunking" or "adapter" mechanism to  the old native Swarm/external KV store. For those of us that has already invested time and effort, that would be a boon.

**Comment by cpuguy83** [comment]
@bklau Docker cannot both use external K/V for discovery and swarm-mode.
But metadata storage is not a feature docker provides with the K/V store.

It is simply not possible for swarmkit to use the external K/V, the data-model is not right and is generally undesirable.

**Comment by bklau** [comment]
@cpuguy83 , I guess we are left hanging without a solution and will just have to continue to use the old standalone Swarm with external KV store backing. **Sigh**

**Comment by justincormack** [comment]
@bklau can you just run your own instance of `etcd` in the swarm and use that?

**Comment by bklau** [comment]
@justincormack : No, we already build our orchestration layer based on Consul. Any change to ETCD would just be too much without heavy reafctoring, retesting all over again. Not going to happen.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
