### ISSUE TITLE
[1.13.0-rc] POST /swarm/leave responds with incorrect status code if node is not in Swarm

### ISSUE THREAD

**Issue by shin-** [moby/moby#29192]
**Description**

In Docker 1.12, making a POST request to the `/v1.24/swarm/leave` endpoint to an engine not part of a Swarm would respond with status code `406 (NOT ACCEPTABLE)`. 
In Docker 1.13, the same POST request now responds with status code `503 (SERVICE UNAVAILABLE)`.

This is a breaking change for this endpoint at a pre-existing API version.

**Steps to reproduce the issue:**
1. Set up a Docker engine node that is not part of a Swarm and exposes the API over HTTP (e.g. `sudo docker -H 127.0.0.1:2375 daemon`)
2. Make a POST request to the `/v1.24/swarm/leave` endpoint:
```
curl -v -d '' http://127.0.0.1:2375/v1.24/swarm/leave
```

**Describe the results you received:**

```
$ curl -v -d '' http://127.0.0.1:2375/v1.24/swarm/leave
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2375 (#0)
> POST /v1.24/swarm/leave HTTP/1.1
> Host: 127.0.0.1:2375
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 503 Service Unavailable
< Api-Version: 1.25
< Content-Type: application/json
< Docker-Experimental: false
< Server: Docker/1.13.0-rc3 (linux)
< Date: Tue, 06 Dec 2016 20:07:31 GMT
< Content-Length: 47
* HTTP error before end of send, stop sending
< 
{"message":"This node is not part of a swarm"}
```

**Describe the results you expected:**

`HTTP/1.1 406 Not Acceptable`, as indicated in the [Remote API 1.24 reference](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#leave-a-swarm)

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by shin-** [comment]
Addendum: This also affects `GET /v1.24/swarm` - not sure about other swarm endpoints.

**Comment by allencloud** [comment]
@shin- We discussed it before. And What you said is indeed something now api suffers. Here is the PR which led to this issue https://github.com/docker/docker/pull/28532

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/29408

**Comment by stevvooe** [comment]
The 406 response code was never specified as part of 1.24 API. Making the assumption of a response code means the code was wrong, as that wasn't part of the specification at release time. If status codes are specified, the caller should not make assumptions about what they might be.

**Comment by thaJeztah** [comment]
Closing this one, per the above discussion
