### ISSUE TITLE
Docker Repository API to get images with filter returns "RepoDigests" as null

### ISSUE THREAD

**Issue by tyrone-grech** [moby/moby#29203]
Docker Repository API to get images with filter returns "RepoDigests" as null.

**Steps to reproduce the issue:**
1. Call Docker API on a repository without a filter (i.e. `.../images/json`)
2. Call Docker API on a repository with a filter (e.g. `.../images/json?filter=<anImageName>`)
3. Compare the returned "RepoDigests" fields of the first response with that of the second response

**Describe the results you received:**
The API responds with a null "RepoDigests" when a filter is used

**Describe the results you expected:**
I expect the API to return the same response whether I use the filter or not

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 26
 Running: 25
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 1.12.3
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.775 GiB
Name: moby
ID: Z26R:GZO7:W4TE:77XS:6XQT:XS7R:ABTC:DFAA:LJLL:AR7W:QIPL:HBK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Experimental: true
Insecure Registries:
 md1drepo01.lnx.ix.com:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by vdemeester** [comment]
Closing this as it seem to be fixed (at least on 18.05 CE).
