### ISSUE TITLE
service logs: Support for individual tasks

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#29223]
Currently, `docker service logs` expects a service name or ID and will stream the combined output of every task that is part of the service.

It would be neat to support `docker service logs <task ID>`.

This is already implemented in the SwarmKit backend, so it's really a matter of plumbing it into the API/CLI.

Relevant bits: In `daemon/cluster/cluster.go` there is:
```go
	stream, err := state.logsClient.SubscribeLogs(ctx, &swarmapi.SubscribeLogsRequest{
		Selector: &swarmapi.LogSelector{
			ServiceIDs: []string{service.ID},
		},
		Options: &swarmapi.LogSubscriptionOptions{
			Follow: config.Follow,
		},
	})
```

In order to stream logs for a task using SwarmKit, one would need to use the exact same code, using a different selector: `TaskIDs: []string{task.ID}`.

I think the workflow would look like:
1) The user calls `docker service logs <something>`
2) The CLI attempts to call `/services/<something>/inspect`
3) If that succeeds, then it continues with `/services/<something>/logs`, and the rest of the code is the same
4) If it fails, then it attempts to call `/tasks/<something>/inspect`
5) If that works, it calls `/tasks/<something>/logs` and continues with the rest of the code
6) if that also fails, the CLI errors out saying <something> is neither a service nor a task

/cc @thaJeztah @aaronlehmann

**Comment by aaronlehmann** [comment]
SGTM

**Comment by justincormack** [comment]
SGTM, was discussing just yesterday...

**Comment by thaJeztah** [comment]
sgtm, wondering why there's a need to call `/services/<something>/inspect` and `/tasks/<something>/inspect` before calling `.../logs` ?

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
#dibs
Great, I will try.

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
#dibs

**Comment by cirocosta** [comment]
Hey, this has already been shipped, right?

**Comment by thaJeztah** [comment]
Yes, this was addressed in https://github.com/moby/moby/pull/32015

Thanks for the ping @cirocosta, we missed linking the PR to this issue 👍
