### ISSUE TITLE
Docker for Windows: Bridge Network starts timing when connecting to resource outside of Docker containers.

### ISSUE THREAD

**Issue by JaronrH** [moby/moby#29280]
Windows 10 Pro: v1607 (build 14393.447)
Docker for Windows: 1.12.3 (8488) -- Stable Channel

Sorry for the long winded subject but the issue is just as hard to explain!  I have Docker for Windows setup with 11 containers.  One of those containers runs Node Red and connects to the rest of my network using the bridge network driver.  Node red will poll other services on my network using HTTP Get (among other methods, such as MQTT).  The host's IP address is resolved through my DNS server (DNSMasq).

What I'm finding is that after ~24 hours, Node-Red starts complaining that it cannot connect to these external services due to timing out (MQTT still works).  These are services that are outside of docker, but either still on my private network or on the internet.  When this happens, I can confirm that, in all of these cases, the services are really up and available.  Even the Windows host itself can talk to these services.

I've restarted the container to see if it is just Node Red but that does not resolve the problem.  The only way I can resolve this issue is to restart Docker.

Please let me know if there is anything else I can provide to help with the diagnosis!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
