### ISSUE TITLE
Docker does not remove Btrfs quota groups when destroying container

### ISSUE THREAD

**Issue by Hexta** [moby/moby#29325]
**Description**

Docker does not remove Btrfs quota groups when destroying container.

**Steps to reproduce the issue:**
1. Configure docker to use Btrfs storage driver.
1. Check list of Btrfs quota groups.
1. Start a container.
1. Check list of Btrfs quota groups.
1. Stop and remove the container
1. Check list of Btrfs quota groups.

**Describe the results you received:**
All quota groups created on step 3 are still present.

**Describe the results you expected:**
Quota groups created on step 3 have been removed.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.867 GiB
Name: k8s-worker-2
ID: PNZC:U3FB:AYVT:UQ57:YW4O:SW7U:ZXY2:C6UZ:MKEL:M3BU:EJVZ:ZDJ6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment]
ping @zhuguihua could you have a look? (looks like this was implemented in https://github.com/docker/docker/pull/19651)

**Comment by yongtang** [comment]
Added a PR to try to fix the issue. @zhuguihua please take a look.

**Comment by yongtang** [comment]
PR is #29427 (missed the PR number in the last comment).
