### ISSUE TITLE
Access published port from different container

### ISSUE THREAD

**Issue by holzgeist** [moby/moby#29330]
**Description**

I want to access a container via the host IP through a published port from a container in the same network. The packages however get dropped by iptables (firewalld logging enabled).

**Steps to reproduce the issue:**
1. create server (e.g. docker run -p 80:80 nginx:alpine)
2. create client (e.g. docker run -it alpine, then install curl or similar)
3. `curl <public host ip>`

**Describe the results you received:**
curl: (7) Failed to connect to <public host ip> port 80: Host is unreachable

**Describe the results you expected:**
HTML code of nginx default page

**Additional information you deem important (e.g. issue happens only occasionally):**
I have iptables enabled and firewalld running on host.
A nmap only lists ssh as open port (sshd is running on host)

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   4d92237
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   4d92237
 Built:
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.13.0-rc3
Storage Driver: btrfs
 Build Version: Btrfs v4.8.5
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: v0.2.4 (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: c91b5be (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.799 GiB
Name: genttest
ID: FV4M:EMNW:CLXY:5RYM:7GP3:QTRM:EBRZ:LFNS:74KE:XIJQ:7S2N:HQI2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
Can you be more explicit about what address you `curl` to, your instructions are soemwhat incomplete.

**Comment by holzgeist** [comment]
Oh, sorry. I was tricked by the MD-syntax..
It should be `curl <public host ip>`
The error message is `curl: (7) Failed to connect to <public host ip> port 80: Host is unreachable`

**Comment by aboch** [comment]
@holzgeist I am not aware of this not working.
When you say `<public host ip>` is this IP address configured on any interface on your host ?

**Comment by holzgeist** [comment]
Sorry for the late reply!

`<public host ip>` is the ip address of the main ethernet device (dns resolves this ip). The result is the same for `curl my.domain.name`

`docker-proxy` is definitely listening, as i can connect from the main host to `localhost` (e.g. `curl localhost`). Using the server-containers ip in the other container works, too.

I do not really understand iptables-nat but it could be due to following iptables rules:
```
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.17.0.2:80
```

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
