### ISSUE TITLE
Unable to use some of the docker API due to vendoring issues

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [moby/moby#29362]
**Description**

I am trying to use version 1.13.0-rc3 of the docker api for golang. My imports are:

```
"github.com/docker/docker/api/types"
"github.com/docker/docker/api/types/container"
"github.com/docker/docker/api/types/network"
"github.com/docker/go-connections/nat"
"github.com/docker/go-units"
```

I am unable to create a HostConfig like:

```
portBindings := make(nat.PortMap)
var ulimits []*units.Ulimit
hostConfig := &container.HostConfig{
		PortBindings: portBindings,
		Resources: container.Resources{
			Ulimits: ulimits,
		},
	}
```

Due to the errors:

```
cannot use portBindings (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value

cannot use ulimits (type []*"github.com/docker/go-units".Ulimit) as type []*"github.com/docker/docker/vendor/github.com/docker/go-units".Ulimit in field value
```

I cannot use the vendored versions, so how can I get around this?

**Steps to reproduce the issue:**
1. Try to create a container.HostConfig using github.com/docker/go-connections/nat.PortMap or github.com/docker/go-units.Ulimit

**Describe the results you received:**
Failed to compile

**Describe the results you expected:**
Compile

**Comment by tamird** [comment]
This was introduced in https://github.com/docker/docker/pull/27912#issuecomment-258334492 and a fix was previously attempted in https://github.com/docker/docker/pull/28080, which was closed without explanation.

cc @LK4D4

**Comment by vdemeester** [comment]
Quoting @dnephin on this as I do agree with him.

> If you're using `docker/docker` as a dependency to your project you should manage your dependencies using a tool like `vndr` or `glide`. You shouldn't rely on the `vendor/` directory in this project.

The workaround is to remove the `vendor/` folder of the `docker/docker` after getting it. It's a little bit tricky depending on what you are using to manage your dependencies though.

And as @tiborvass said 

> Hopefully we'll find a solution as part of the ongoing works in the Go world.

**Comment by tamird** [comment]
This rationale is beyond absurd. The API client was previously in a
separate repository (https://github.com/docker/engine-api) but it was
deprecated and folded into docker/docker, leaving us (your users) with no
choice but to depend on docker/dcoker.

**Comment by vdemeester** [comment]
@tamird I do agree it's not the best. It's just the *current* workaround, and I really wish we could somehow make it work. Having a `vendor` folder is a huge enhancement on the development on docker/docker itself as we don't rely on some autopath hack anymore but it broke users of the client side.

Still looking at some possible ideas like extracting the client `client.APIClient` to a repository for each tagged version of docker (i.e. any RC and GA releases) or something else.

**Comment by jeffw-wherethebitsroam** [comment]
Agreeing with @tamird here that it would be really great if the API client could be returned to it's own repository and be vendored into docker/docker along with all of the other dependencies. 

A couple of other alternatives:
- the API client does not expose any of the vendored types directly.
- the docker/docker project uses a tool like glide and does not actually store the vendor directory in the git repository, but installs them at build time.

For what its worth, I am using glide for dependencies, but that doesn't resolve the issue by itself, just makes for more interesting error messages. I've now added:

```
glide install --strip-vendor
```

As part of my 'dependencies' make target. But it just feels a little dirty. Works for now though.

**Comment by jeffw-wherethebitsroam** [comment]
Also, see https://groups.google.com/forum/#!msg/golang-nuts/AnMr9NL6dtc/UnyUUKcMCAAJ

**Comment by ds0nt** [comment]
Well then... time to wrap everything in exec commands?

**Comment by ds0nt** [comment]
Well then... wow.

**Comment by CpuID** [comment]
Any movement on this? It's still in a pretty nasty state :(

I went to use a project I wrote back a year or two ago, to find something was busted between the N `docker` repos + the various vendor dirs in each of them.

Example:

```
cannot use index (type *"github.com/docker/docker/api/types/registry".IndexInfo) as type *"github.com/docker/cli/vendor/github.com/docker/docker/api/types/registry".IndexInfo in argument to command.ResolveAuthConfig
```

**Comment by CpuID** [comment]
I *think* I worked around my issues for now, by going:

```
cd GOPATH/src/github.com/docker
rm -rf docker/vendor
rm -rf cli/vendor
rm -rf distribution/vendor
```

And then ensured my version of `cobra/spf13` + `cobra/pflag` were up to date. Not elegant, but technically works around my issues.

**Comment by Xjs** [comment]
This totally breaks depending on `docker/docker` from Bazel build files (need to fork each and every docker repository and remove the vendor directories, and rebase to keep in sync), since https://github.com/bazelbuild/bazel-gazelle cannot ignore vendor directories for dependencies. Are there any plans to remove the `vendor` directory (especially in the light of Go modules)?

**Comment by zscole** [comment]
Just wanted to chime in here, several years later, that this is still a recurring and prevalent issue. My existing workaround was deleting the vendor folder, but this is entirely impractical and absurd. Currently trying to solve the issue with [go deps](https://github.com/tools/godep). Life is pain.

**Comment by P0sa** [comment]
I am currently also stuck with this. It's very frustrating trying to get it to work with vendoring in a Pipeline

**Comment by SweeXordious** [comment]
Any update on this ?

**Comment by akerouanton** [comment]
@SweeXordious You can take a look at [this comment](https://github.com/moby/moby/issues/39056#issuecomment-633575517) from @thaJeztah, he explains what procedure should be followed to get it work with `go mod` :wink:

**Comment by thaJeztah** [comment]
This issue was related to the original change to switch to use `vendor/` as the path for vendoring, which is the standard path for vendored dependencies. The solution for that is to use a vendoring tool that strips nested dependencies (or to configure the tool you're using to do so).

Unfortunately, using go modules with this repository is still difficult (and complicated to resolve). There are some newer issues that discuss this, and which are more current. Let me close this one in favour of those, and link to some comments on those that may be helpful https://github.com/moby/moby/issues/39056 (https://github.com/moby/moby/issues/39056#issuecomment-633575517) and  https://github.com/moby/moby/issues/39302 (https://github.com/moby/moby/issues/39302#issuecomment-635253855)
