### ISSUE TITLE
Docker occasionally fails to restart Windows containers, both temporarily and permanently

### ISSUE THREAD

**Issue by sandersaares** [moby/moby#29392]
**Description**

Despite `--restart always`, Windows containers do not always start after Docker is restarted.

**Steps to reproduce the issue:**

The behavior is not consistent, so a restart loop is the best way to reproduce it (that I have found so far).

1. Create some containers using `docker run --detach --restart always microsoft/windowsservercore powershell.exe -Command "while (1) { Start-Sleep 30 }"`
2. In PowerShell, execute `while (1) { restart-service docker ; start-sleep 10 ; docker ps -a }`
3. Wait some hours.

**Describe the results you received:**

I performed a 16 hour overnight run with 6 containers on an Azure DS1v2 VM.

The PowerShell transcript stopped recording `docker ps -a` output after a while, so my results are only approximate but this is what I got:

* During the first part of the run (visible in transcript) 0.4% of container startups failed.
* During the last part of the run (visible in console) 33% of containers had failed permanently and never started again.
* During the last part of the run (visible in console), for the remaining 66% of containers, 8.8% of startups failed.

Statuses for temporary failures followed the pattern `Exited (1073807364) 38 seconds ago` or `Exited (2147483648) 2 minutes ago`.

Statuses for permanent failures followed the pattern `Exited (2147483648) 5 hours ago`

**Describe the results you expected:**

Containers start after every Docker restart if they are configured with `--restart always`

**Additional information you deem important (e.g. issue happens only occasionally):**

I have also seen exit code 1067 when the container entry point was cmd.exe or ServiceMonitor.exe (using the `microsoft/iis` image) instead of PowerShell.

The issue occurs more often in "real usage". I first ran into it when restarting Docker during playing around with Docker configuration changes, when out of my 5-10 restarts, most had a single container fail to start up (out of 2 or 3 I had running). Under artificial usage (the restart loop), the issue happens less often.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   e308f6b
 Built:        Tue Nov 22 18:15:55 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          e308f6b
 Built:               Tue Nov 22 18:15:55 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.479.amd64fre.rs1_release.161110-2025)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: temphost02
ID: ASKC:36AM:3TCL:UB2Y:4DDO:5HGG:2GJD:5JHE:SZHK:AP2I:4ANZ:WJZS
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure DS1v2 VM. Also tried with 1.13-dev, with no difference in results.

**Comment by johnstep** [comment]
I am testing the now. Thanks.

**Comment by sandersaares** [comment]
@johnstep did you manage to reproduce this?

**Comment by sandersaares** [comment]
Issue remains on .1480.

**Comment by vitr** [comment]
I'm on the Docker CE edge channel and still have this issue
```
Version 17.07.0-ce-rc1-win21 (12927)
Channel: edge
76a8c4b
```

**Comment by darrenstahlmsft** [comment]
Sorry, just seeing this for the first time. I've previously seen issues with this related to service dependencies not being correctly set. What is the output of `sc.exe qc docker`?

**Comment by sandersaares** [comment]
```
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: docker
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : "C:\Program Files\docker\dockerd.exe" --run-service
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Docker Engine
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem
```

Docker was installed using `dockerd --register-service`

**Comment by darrenstahlmsft** [comment]
What happens if you unregister with `dockerd --unregister-service` then re-register via above? I'd expect that it should add a dependency on `ConDrv` service given your build number. Though I'm not sure that would help here on second thought. I'll try to repro this soon and let you know if I can get a local repro.

**Comment by sandersaares** [comment]
No change in the service configuration after re-registering - still no dependencies listed. This is with Docker 17.06.0-ce.

**Comment by darrenstahlmsft** [comment]
I'm able to repro this locally (So far I've seen a temporary failure, no permanent failures yet). I'm investigating.

**Comment by darrenstahlmsft** [comment]
I see the permanent errors. Looking

**Comment by darrenstahlmsft** [comment]
I understand what's happening here, and have submitted a temporary fix in https://github.com/moby/moby/pull/35184.

Essentially the daemon shutdown timeout is too short, causing a forced terminate, resulting in leaked containers (and root filesystems held open and mounted on the host). This can be worked around by increasing the daemon shutdown timeout `--shutdown-timeout` flag on dockerd.exe or `shutdown-timeout` in the JSON config file.

My PR changes the default value from 10 seconds to 30 seconds, I'd recommend the same value to work around this issue in released Docker versions.

This will be more correctly fixed with containerd 1.0 integration, which moves responsibility of mounting the root filesystem to the runtime, letting containerd to the cleanup properly.

**Comment by ekitagawa** [comment]
@darrenstahlmsft We are seeing multiple cases with windows node restart just like this.  However, in their cases, the errors are related to network like this.  
``` 
Handler for POST /v1.24/containers/9328457.../start returned error: failed to create endpoint ucp-port-check-12376 on network nat: HNS failed with error : The object already exists.
```
This `ucp-...` containers are management containers for Docker EE Standard/Advanced that must keep running at all time across restart or unexpected failure.  
It seems as though HNS data were not cleared properly, and blocking the new instance.  Is this the same issue as this?  Shall I file separate report?

**Comment by darrenstahlmsft** [comment]
@ekitagawa That looks like a separate issue. Can you file a new issue and CC me on it? Thanks.

**Comment by ekitagawa** [comment]
It's a support case from our enterprise customer, so I will work with Microsoft Support team to escalate it to you.  Thank you for the comment!

**Comment by martencassel** [comment]
If a server does a bluescreen or a reset of the machine is performed, i expected that i could remove any stopped containers with docker container rm or docker system prune.
> docker ps -a 
> docker system prune 
These command will fail because the VHDX disks are mounted and not dismounted.

**Comment by martencassel** [comment]
Neither docker rm or docker system prune works in if VHDX disks are not dismounted correctly for stopped containers.

This can be reproduced by doing a forced machine reset or generating a bluescreen with a set of containers on the machine running.
After reset you see that the VHD disks are mounted, and the daemon will report Access Denied when trying to run docker rm or system prune.

Could you possible do support a VHD dismount operation during container removals from docker ? 

Version: 17.06.2-ee-6, Windows 10.0.14393

**Comment by Dressee** [comment]
Still seeing the permanent failures even when increasing the shutdown-timeout.
Is there any fix yet?

**Comment by sandersaares** [comment]
I overcame this and other Windows container issues by migrating my containers to Linux.

**Comment by AbsolutelyFreeWeb** [comment]
I have exit code `4294967295`

and it fails to start with the same error message:
`DockerDo : Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)`

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
