### ISSUE TITLE
docker make install error

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#29531]
ERRO[0001] devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storage-driver-option 
ERRO[0001] [graphdriver] prior storage driver devicemapper failed: driver not supported 

my docker is 1.13.0-rc3  and driver is devemapper

docker run --rm -i --privileged -e BUILD_APT_MIRROR -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_ARGS -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER=devicemapper -e DOCKER_INCREMENTAL_BINARY -e DOCKER_PORT -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY -e http_proxy -e https_proxy -e no_proxy -v "/home/tim/eclipse/workspace/src/github.com/docker/docker/bundles:/go/src/github.com/docker/docker/bundles" -v /home/tim/eclipse/workspace/src/github.com/docker/docker:/go/src/github.com/docker/docker/  -t "docker-dev:master" hack/make.sh binary

**Comment by AkihiroSuda** [comment]
You can try `make cross` to build the dynamic binary, which is needed for devmapper.
The binary will be located at `bundles/latest/dynbinary-daemon`

**Comment by thaJeztah** [comment]
AFAIK, you can't run devicemapper inside the dev container; also, the graph driver inside the dev container doesn't have to match what you're running on the host, so if it's just for testing, the default `vfs` driver may work.

If you want to build a package to install on your host; you may be looking for `make rpm`

**Comment by timchenxiaoyu** [comment]
when I use make rpm also get error
--> Making bundle: dynbinary (in bundles/1.13.0-rc3/dynbinary)
Building: bundles/1.13.0-rc3/dynbinary-client/docker-1.13.0-rc3
Created binary: bundles/1.13.0-rc3/dynbinary-client/docker-1.13.0-rc3
Building: bundles/1.13.0-rc3/dynbinary-daemon/dockerd-1.13.0-rc3
Created binary: bundles/1.13.0-rc3/dynbinary-daemon/dockerd-1.13.0-rc3

---> Making bundle: build-rpm (in bundles/1.13.0-rc3/build-rpm)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.13.0-rc3/build-rpm/docker.sock --storage-driver devicemapper --pidfile bundles/1.13.0-rc3/build-rpm/docker.pid --userland-proxy=true
...........................................................
error: daemon at unix:///go/src/github.com/docker/docker/bundles/1.13.0-rc3/build-rpm/docker.sock fails to 'docker version':
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   857c251-unsupported
 Built:        Mon Dec 19 09:29:14 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///go/src/github.com/docker/docker/bundles/1.13.0-rc3/build-rpm/docker.sock. Is the docker daemon running?
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-rc3/build-rpm)
make: *** [rpm] Error 1

**Comment by timchenxiaoyu** [comment]
My docker env is devicemapper ，so I want to complie for devicemapper

**Comment by timchenxiaoyu** [comment]
after I compile ，deploy error

**Comment by thaJeztah** [comment]
But it's not needed in the build container; Did you manually set the `DOCKER_GRAPHDRIVER` env-var? If so, unset that variable, or set it to `vfs`

**Comment by timchenxiaoyu** [comment]
ERRO[0001] devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storage-driver-option
ERRO[0001] [graphdriver] prior storage driver devicemapper failed: driver not supported

**Comment by thaJeztah** [comment]
Is that when running on the host, or inside the container? What distro (and release) are you running on?

**Comment by timchenxiaoyu** [comment]
yes,on host ,not contanier,docker1.13 rc3

**Comment by timchenxiaoyu** [comment]
https://github.com/docker/docker/issues/13179

**Comment by thaJeztah** [comment]
What Linux distro are you running on? Is your system fully up to date?

**Comment by timchenxiaoyu** [comment]
CentOS Linux release 7.2.1511

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
