### ISSUE TITLE
[swarm] Downgrades from 1.13 to 1.12 can cause panic

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#29557]
The vendored version of `etcd/raft` changed their WAL file format in a non-backward-compatible way. Also, Docker 1.13 now encrypts WAL files. Because of these changes, it's not possible for 1.12 to read WAL files written by 1.13.

We were aware of this near the start of the release cycle, and decided to work around the problem by migrating the files to a new directory, and keeping the old ones in place. The idea was that on a downgrade, the engine would see the old state directory, and catch up to the latest state through Raft. See this PR for more details: https://github.com/docker/swarmkit/pull/1483

Unfortunately, this turns out not to work reliably. `etcd/raft` can panic if the node appears to have gone back in time. The leader keeps track of which data each node has, and will send messages based on this information. If a node receives a message that implies it previously had data that it no longer has, it will panic. See https://github.com/docker/swarmkit/pull/1815#issuecomment-267703760 for more details.

Here are a few ideas of how to deal with this:

- Document a process for downgrading from 1.13 to 1.12, involving demoting the manager and promoting it again after the downgrade.
- Provide a reverse migration tool that can translate the new WAL format into the old one. This would involve forking the old version of the `etcd/raft` WAL code.

cc @dongluochen @cyli @aluzzardi @icecrime

**Comment by cyli** [comment]
https://github.com/docker/swarmkit/pull/1756 attempts to provide a downgrade tool to allow users to go from v3 back down to v2.

**Comment by aaronlehmann** [comment]
We will document this rather than providing a migration tool.

**Comment by aaronlehmann** [comment]
I'm going to close this, since it's safe to say that downgrades to Docker 1.12 are not going to be supported by any future versions.
