### ISSUE TITLE
[go1.8] New behavior in HTTP client redirect

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#29602]
Go 1.8 changes behavior for HTTP redirects (specificlaly 301, 307, and 308) in the client .
The Docker client (and by extension docker API client) can be made to to send a request like `POST /containers//start` where what would normally be in the `name` section of the URL is empty. This triggers an HTTP 301 from the daemon.
In go 1.8 this 301 will be converted to a `GET` request, and ends up getting a 404 from the daemon.

This behavior change manifests in the client in that before the 301 was not followed and the client did not generate an error, but now results in a message like `Error response from daemon: page not found`.

This should be minor, but also already found a place in our test suite that this is an issue (easy fix).

**Comment by cpuguy83** [comment]
Relevant discussion is golang/go#18347

**Comment by bradfitz** [comment]
And the updated documentation is in https://github.com/golang/go/commit/2eae691d56125c62e0e5f0e4a3bd42e67e423f01

**Comment by nieksand** [comment]
Should this be mentioned in 1.8 release notes?

Broke some unit tests on code I was working with.  (Was checking http client behavior under various response scenarios).  Trivial fix now that I see what's changed.

**Comment by ripcurld0** [comment]
Hey @cpuguy83!
I built Docker using Go 1.8 and started executing the integration tests (DockerSuite only) today but didn't get any failed test.
Can you elaborate more what tests should have failed.

I do get the "Error response from daemon: page not found" message when sending a container name that starts with `../` and I wonder if it's a good idea to catch it in [`client/request.go`](https://github.com/docker/docker/blob/master/client/request.go#L184-L206) and to change it to something clearer for the user.

Waiting for your feedback.
Thanks.

**Comment by cpuguy83** [comment]
@ripcurld0 This is because the tests have been updated to not break in such a case.
I agree we should probably just have the clients not redirect in this case.

Ping @krasi-georgiev

**Comment by ripcurld0** [comment]
OK, so I guess it takes only to set [here](https://github.com/docker/docker/blob/master/client/client.go#L103-L107) and [there](https://github.com/docker/docker/blob/master/client/client.go#L149-L151) the http.Client's CheckRedirect to our own.

And basically, when this function will be called it will return an error message saying "You provided some bad argument because the request wasn't supposed to be redirected".

Correct?

**Comment by krasi-georgiev** [comment]
@cpuguy83 @ripcurld0 short answer is don't use ../ as a container name 😄 

I spend some time on trying to improve this , but didn't find a good solution

https://github.com/gorilla/mux/issues/226
https://github.com/docker/docker/pull/30933


the go version is irrelevant as the url cleanup happens in the gorilla mux before it returns a reply to the client so I don't see how disabling the redirect follow in the client will fix it.
I tried it anyway but disabling the redirect in the clientdidn't change anything. 

I would be really happy to discuss a solution on the slack channel.

@cpuguy83 out of interest do you remember which test was failing after the golang 1.8 upgrade ?

**Comment by cpuguy83** [comment]
@krasi-georgiev It was issues with test cleanup which were failing on any error.
Somewhere along the way during test cleanup the container name was an empty string which causes the redirect.

**Comment by ripcurld0** [comment]
@cpuguy83 any feedback regarding this suggestion: https://github.com/docker/docker/issues/29602#issuecomment-286476215

Or maybe validate the arguments don't contain this '../'

**Comment by cpuguy83** [comment]
I think we should drop the redirect as you suggest.

**Comment by cpuguy83** [comment]
Resolved in #32127
