### ISSUE TITLE
endpoint join on GW Network failed: Bind for 0.0.0.0:10050 failed: port is already allocated.

### ISSUE THREAD

**Issue by jperez110** [moby/moby#29677]
I intermittently hit a problem where my port mapping is not release when a container is removed. I'm running docker 1.12.2 on an Azure VM running CentOS Linux release 7.2.1511.

# docker info
Containers: 15
 Running: 7
 Paused: 0
 Stopped: 8
Images: 38
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-523680-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 15.19 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.365 GB
 Metadata Space Used: 32.87 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.115 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 55.04 GiB
Name: hostname
ID: 2C3V:5PU2:DKIN:2XLM:6VHQ:JTBP:FRP5:JZIP:MCMC:R7S2:FCA6:T3EZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: consul://hostname.com:8500/network
Cluster Advertise: x.x.x.x.:2375
Insecure Registries:
hostname.com:5601
hostname.com:6601
hostname.com:6602
 127.0.0.0/8
---------------------------------------------------------------------------------------------------------------

I stopped my zabbix-agent2 container via "docker stop zabbix-agent2" and got no errors. Next I tried restarting it via...

**docker run --name zabbix-agent2 --net DEV --privileged -v /dev/sda1:/dev/sda1 -v /tmp:/hosttmp -P -p 10050:10050 -e ZBX_SERVER_HOST=x.x.x.x.x --restart=unless-stopped -d zabbix/zabbix-agent:latest**
and get...

1f82c5c3031765403f29aabfad1bd73ceccce6fa464529716c486dbeaa691907
docker: Error response from daemon: container 1f82c5c3031765403f29aabfad1bd73ceccce6fa464529716c486dbeaa691907: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_1f82c5c30317 (022e658fde15c86271a6e4b57b0c75432af32c478f051f5a51023c9a4e24f11f): Bind for 0.0.0.0:10050 failed: port is already allocated.

Doing a **netstat -plan | grep 10050** shows no process using this port.
Now, when I run **iptables -L -t nat --line-numbers** it does show...
9    DNAT       tcp  --  anywhere             anywhere             tcp dpt:zabbix-agent to:x.x.x.x:10050
in the DOCKER chain which is a problem so I tried removing that rule via **iptables -D DOCKER 9** but it would not remove it.

Researching this some people said do a **service docker restart** would fix problem but I cannot do this because it would stop all other containers and its a prod environment. I have not been able to tell if its a known bug so opening this bug report. Thank you..Jesse Perez

**Comment by aboch** [comment]
If possible, I'd suggest you to move to the most recent 1.12.5.
In regards to this specific issue, it is possible that you are hitting the issue fixed by docker/libnetwork/pull/1504. The fix is present in docker starting from 1.12.3.

**Comment by BSWANG** [comment]
I meet the same issue on 1.12.6，I guess some race condition will cause it.
And no way to walk around except restart docker daemon.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
