### ISSUE TITLE
docker pull always probes HTTPS, causes 15s delay

### ISSUE THREAD

**Issue by gm42** [moby/moby#29736]
**Description**

docker always tries to pull/push over HTTPS, although the insecure registry specified is HTTP. I did not find any way to specify that for a certain domain, HTTP must be used. Trying HTTPS before HTTP causes severe slowdowns.

Probably related: #8887

**Steps to reproduce the issue:**
1. add `--insecure registry example.com` to your docker daemon options
2. setup an HTTP nginx proxy to an HTTPS registry as in https://forums.aws.amazon.com/thread.jspa?threadID=223934
3. push an image and then pull it back (multiple times to repeat the test)

**Describe the results you received:**
```
time docker pull example.com/test:v2
test-v2: Pulling from example.com/test
a3ed95caeb02: Already exists 
300273678d06: Already exists 
df3d611b4b09: Already exists 
25a7aaae0182: Already exists 
79d9f3e9b763: Already exists 
244760a9aebc: Already exists 
Digest: sha256:df2012764b00277c5a0d5810aa9c56b3f43a4f95625bcfa17fade003e947ce89
Status: Image is up to date for example.com/test:v2

real	0m15.148s
user	0m0.012s
sys	0m0.000s
```
and in the log:
```
ime="2016-12-27T22:17:44.069472892Z" level=warning msg="Error getting v2 registry: Get https://example.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
```

**Describe the results you expected:**
An immediate return with <200ms response, as it happens when I use an equivalent HTTPS registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a scenario where in a LAN I do not need to run the registry on HTTPS; specifically, it's a simple nginx proxy for AWS ECR which does not support clean domain aliases (see also https://forums.aws.amazon.com/thread.jspa?threadID=223934)

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.35-33.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.4 MiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
An AWS EC2 instance.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
