### ISSUE TITLE
upstart shutdown change to stop on starting to allow for things like AWS ECS deregister

### ISSUE THREAD

**Issue by danbf** [moby/moby#29731]
Feature request:

Right now the shutdown in docker is a bit harsh with no warning outside schedulers to allow allow for things like AWS ECS deregister, https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeregisterContainerInstance.html  Can we switch https://github.com/docker/docker/blob/68dab9bd0910e22c96d5dfcbd4e972f8ce770a88/contrib/init/upstart/docker.conf#L4 to something more like:

```stop on starting rc RUNLEVEL=[016]```

this would allow for adding in a pre-stop cleanup script that does not get killed in 20 seconds along the lines of:
```
pre-stop script
	cluster=`jq -r .Data.Cluster /data/ecs/ecs_agent_data.json`
	region=`jq -r .Data.ContainerInstanceArn /data/ecs/ecs_agent_data.json | awk -F: '{print $4}'`
	container_instance_id=`jq -r .Data.ContainerInstanceArn /data/ecs/ecs_agent_data.json | awk -F/ '{print $2}'`

	#de-register the instance
	/usr/local/bin/aws --region $region ecs deregister-container-instance --cluster $cluster --container-instance $container_instance_id --force > /dev/null 2>&1

	#stop the ecs-agent if its running
	if (wget -qO- http://localhost:51678/v1/metadata > /dev/null 2>&1) ; then 
		docker stop `/usr/bin/docker ps | grep \/amazon-ecs-agent | head -n 1 | /usr/bin/awk '// {print $1}'` > /dev/null 2>&1
	fi 

	#remove the ecs_agent data
	rm -f /data/ecs/ecs_agent_data.json

	#sleep to allow the deregister to take effect and connection draining to complete
	sleep 300
end script
```

This has a lot less moving parts then something like the life-cycle hooks based approach in https://engineering.circle.com/the-hook-the-message-and-the-function-16e7df31666c#.r5ft4tgpz

**Comment by thaJeztah** [comment]
ping @ijc25 @tianon PTAL

**Comment by vdemeester** [comment]
Given there hasn't been any activities on that for the past year, and given the comment from @ijc, I'm gonna close this issue for now. Feel free to still discuss this if it's still a valid problem and I'll re-open 😉
