### ISSUE TITLE
docker restart failed after machine  reboot

### ISSUE THREAD

**Issue by sandyskies** [moby/moby#29748]
Description

Steps to reproduce the issue:

machine reboot 

then  start docker
``` 
dockerd -g /data/docker -H unix:///var/run/docker.sock -b none --live-restore -s aufs --iptables=False
 and  
FATA[0000] open /var/run/docker/libcontainerd/containerd/10cf98fe5158d10b4c337017d7a6cb67166ac1ea3d1aa2733a8b27fa6c235a07/state.json: no such file or directory 
```

I have to rm -rf /var/run/docker  and start docker again，and all is fine again
Additional information you deem important (e.g. issue happens only occasionally):
always
Output of docker version:
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
Output of docker info:

Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: xfs
 Dirs: 163
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.10.104.xxxxxx
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.3 GiB
Name: xxxxxxxxxxxxxxxxx
ID: VTSE:3AJP:MWYG:XSRO:VLHA:7RUN:S5KP:SDB4:HVDP:5HT3:24XC:VW52
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Additional environment details (AWS, VirtualBox, physical, etc.):
```
centos 6 with 3.10.x kernel version.

**Comment by cpuguy83** [comment]
ping @mlaventure

**Comment by thaJeztah** [comment]
@sandyskies just to be sure; you mentioned you wanted to try another RunC version in https://github.com/docker/docker/issues/29700#issuecomment-269442068. Is this with the "default" RunC version, or with a custom/different version?

**Comment by mlaventure** [comment]
@sandyskies can you start the daemon in debug mode and provide the log when this occurs?

This might be due to `--live-restore` being used, after the failure could you try again without it being activated?

**Comment by sandyskies** [comment]
time="2017-01-07T21:33:27.192921733+08:00" level=debug msg="docker group found. gid: 502" 
time="2017-01-07T21:33:27.192988417+08:00" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)" 
time="2017-01-07T21:33:27.193488987+08:00" level=info msg="libcontainerd: new containerd process, pid: 12604" 
time="2017-01-07T21:33:27.194178095+08:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE" 
time="2017-01-07T21:33:27.204290372+08:00" level=debug msg="containerd: read past events" count=0 
time="2017-01-07T21:33:27.204416356+08:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1915b785d4b33931f665c6510f6cf8399f58f5d41166f2400264b6fdc5c1ca0f/state.json: no such file or directory" 
time="2017-01-07T21:33:30.194614972+08:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE" 
time="2017-01-07T21:33:33.195307836+08:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE" 
time="2017-01-07T21:33:33.195817302+08:00" level=info msg="libcontainerd: new containerd process, pid: 12623" 
time="2017-01-07T21:33:33.206395711+08:00" level=debug msg="containerd: read past events" count=0 
time="2017-01-07T21:33:33.206518791+08:00" level=fatal msg="open /var/run/docker/libcontainerd/containerd/1915b785d4b33931f665c6510f6cf8399f58f5d41166f2400264b6fdc5c1ca0f/state.json: no such file or directory" 
time="2017-01-07T21:33:42.882045312+08:00" level=debug msg="libcontainerd: containerd connection state change: CONNECTING" 
time="2017-01-07T21:33:42.882156444+08:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"

**Comment by sandyskies** [comment]
docker-containerd can't start

**Comment by mlaventure** [comment]
@sandyskies it seems a `state.json` is missing for the `1915b785d4b33931f665c6510f6cf8399f58f5d41166f2400264b6fdc5c1ca0f` container somehow.

Deleting that directory should allow `containerd` to keep going (i.e. `rm -rf /var/run/docker/libcontainerd/containerd/1915b785d4b33931f665c6510f6cf8399f58f5d41166f2400264b6fdc5c1ca0f/`).

Although, if that container is still running or docker hasn't seen it die, it won't be able to be acted upon afterwards.

**Comment by sandyskies** [comment]
@mlaventure  I know the workaround is to delete the dir ,but as machine reboot happen all the time ,we can't manually delete the directory everytime ,can we?

**Comment by mlaventure** [comment]
@sandyskies so the machine get rebooted without a clean shutdown of the daemons? Could you increase the grace period for `docker` to shutdown (unless it's not a clean shutdown)?

I'll make a patch for `containerd` to ignore invalid directory on startup. But I don't know what the effect will be on `docker`, it would all depends on what state it was when it got forced killed by the reboot process.

**Comment by sandyskies** [comment]
@mlaventure machine reboot  is a unexpected process,  not manually.  So we can't have a grace period for dockerd . 
As for the PR , how about just remove the state diretory?

**Comment by mlaventure** [comment]
@sandyskies because that way things can be troubleshooted later. This state should rarely happen in normal operations.

You should really figure out why your machine reboot unexpectedly otherwise.

**Comment by artemg** [comment]
@mlaventure 

> You should really figure out why your machine reboot unexpectedly otherwise.
E.g. because of power outage. After that happens docker can't start.

**Comment by sandyskies** [comment]
https://github.com/docker/containerd/pull/410 @artemg  This pr should fix your problem , issuse closed.

**Comment by mlaventure** [comment]
Re-opening, until that version of `containerd` get vendored in here, the issue will still be present.

**Comment by derosm2** [comment]
Did this issue get resolved? If so in what version?

**Comment by thaJeztah** [comment]
The fix was merged into docker in https://github.com/moby/moby/pull/31662, which is part of the 17.03.1 release, so let me close this issue
