### ISSUE TITLE
[Documents] service update document is not so in detail

### ISSUE THREAD

**Issue by allencloud** [moby/moby#29758]
**Description**
I found that `docker service update` command document is not so detailed in https://github.com/docker/docker/blob/master/docs/reference/commandline/service_update.md

I think there are lots of missing options in explanation, such as `--rollback`, and so on.

In addition, in the doc it says:
```
The parameters are the same as [`docker service create`](service_create.md).
``` 

I think that is not true.

Here is the evidence:
```
root@ubuntu:~# docker service create --help | grep "\-\-" | wc -l
45
root@ubuntu:~# docker service update --help | grep "\-\-" | wc -l
57
```
 So, there is at least 12 parameters that are not the same.

I think we need a detailed `docker service update` doc for the users.

**Comment by allencloud** [comment]
`--rollback                         Rollback to previous specification`

I was wondering what does this mean? 

Roll back to the original status of the service before update action, in case that the update fails?

@aaronlehmann @tonistiigi

**Comment by thaJeztah** [comment]
The `--rollback` flag is documented in the swarm user guide; https://github.com/docker/docker.github.io/pull/219, but perhaps it makes sense to add a link, similar to what we do on the `service create` reference; https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#create-a-service-with-a-rolling-update-policy

**Comment by allencloud** [comment]
I am afraid `--rollback` is not a flag in `docker service create`, but in `docker service update`.

**Comment by allencloud** [comment]
Thanks @erxian for adding `--rollback` flag usage example in docs.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
