### ISSUE TITLE
contrib/mkimage-alpine fails on RaspberryPI 2 armhf with "segmentation fault"

### ISSUE THREAD

**Issue by itwars** [moby/moby#29757]
I'm trying to generate a new docker minimal image on my RPI. It works fine with v3.4, but not with v3.5.

On my RPI : 
```
Linux black-pearl 4.4.39-hypriotos-v7+ #1 SMP PREEMPT Sun Dec 18 15:01:46 UTC 2016 armv7l GNU/Linux

```
Here is my output 

```
sudo ./mkimage-alpine.sh -s -r v3.5
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
apk-tools 2.6.8, compiled for armhf.
fetch http://nl.alpinelinux.org/alpine/v3.5/main/armhf/APKINDEX.tar.gz
(1/16) Installing musl (1.1.15-r5)
(2/16) Installing busybox (1.25.1-r0)
Executing busybox-1.25.1-r0.post-install
(3/16) Installing alpine-baselayout (3.0.4-r0)
Executing alpine-baselayout-3.0.4-r0.pre-install
Executing alpine-baselayout-3.0.4-r0.post-install
(4/16) Installing openrc (0.21.7-r3)
Executing openrc-0.21.7-r3.post-install
(5/16) Installing alpine-conf (3.5.0-r2)
(6/16) Installing libressl2.4-libcrypto (2.4.4-r0)
(7/16) Installing libressl2.4-libssl (2.4.4-r0)
(8/16) Installing zlib (1.2.8-r2)
(9/16) Installing apk-tools (2.6.8-r1)
(10/16) Installing busybox-suid (1.25.1-r0)
(11/16) Installing busybox-initscripts (3.0-r8)
Executing busybox-initscripts-3.0-r8.post-install
(12/16) Installing scanelf (1.1.6-r0)
(13/16) Installing musl-utils (1.1.15-r5)
(14/16) Installing libc-utils (0.7-r1)
(15/16) Installing alpine-keys (1.3-r0)
(16/16) Installing alpine-base (3.5.0-r0)
Executing busybox-1.25.1-r0.trigger
OK: 5 MiB in 16 packages
Segmentation fault
```

Any ideas?

**Comment by thaJeztah** [comment]
ping @ncopa

**Comment by ncopa** [comment]
@itwars can you try identify what program that is segfaulting? Does `dmesg` give any hint?

**Comment by itwars** [comment]
mkbase() {
        $TMP/sbin/apk.static --repository $MAINREPO --update-cache --allow-untrusted \
                --root $ROOTFS --initdb add alpine-base
}

It seems to be the apk.static and nothing in dmesg!

**Comment by alexellis** [comment]
I could test this on Raspbian, what are the repo steps @itwars ?

**Comment by itwars** [comment]
HypriotOS is Raspbian based, with extra repo for Docker.

**Comment by alexellis** [comment]
That's not quite right, it's similar to Raspbian but with a lot of customisations including a different kernel. If you can provide repo instructions I'm offering to test on my device.

**Comment by itwars** [comment]
```
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main
deb https://packagecloud.io/Hypriot/rpi/debian/ jessie main
deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main
deb http://archive.raspberrypi.org/debian/ jessie main
```

**Comment by vimagick** [comment]
:cry: Got segmentation fault on pi3 (2017-01-11-raspbian-jessie-lite).

**Comment by alexellis** [comment]
@vimagick I tried running the script last week - I don't have the exact error but it seemed like something else was required. Do you just invoke this shell script after `git clone` of docker/docker or do you have to do a Docker build first?

**Comment by alexellis** [comment]
@itwars are the images in `armhf/alpine` any use to you in the interim? I think @tianon generates these either manually or though CI.. is that through a cross-compilation target @tianon or on a Scaleway/armv7 device?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
