### ISSUE TITLE
Failed to start any container

### ISSUE THREAD

**Issue by saksmt** [moby/moby#29771]
**Description**

Containers fail to start without matter of amount nor timeouts

**Steps to reproduce the issue:**
1. `docker run -it debian bash`

**Describe the results you received:**
`docker: Error response from daemon: containerd: container not started.`

**Describe the results you expected:**
Bash prompt inside container

**Additional information you deem important (e.g. issue happens only occasionally):**
It is not occasional, it happens all the time no matter after reboot or other special action

**Output of `docker version`:**
```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   88862e7
 Built:        Wed Dec 28 16:28:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   88862e7
 Built:        Wed Dec 28 16:28:20 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 7
Server Version: 1.13.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-8:1-488082-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 15.24 GB
 Data Space Total: 107.4 GB
 Data Space Available: 92.13 GB
 Metadata Space Used: 19.05 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.128 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135 (2016-09-26)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: v0.2.5 (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: c91b5be (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.863 GiB
Name: smt-server
ID: BHO7:2LFB:SDOW:OPR4:UPIG:37HS:QEMV:RENH:5R4V:63OF:TLXT:QQEZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[kcfg.txt](https://github.com/docker/docker/files/676795/kcfg.txt)

```
smt-server ~ # uname -a
Linux smt-server 4.9.0-gentoo #1 SMP Wed Dec 28 17:52:32 MSK 2016 x86_64 Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz GenuineIntel GNU/Linux
smt-server ~ # # in attachment: zcat /proc/config.gz | grep -vP "^#" | grep -vP "^$"
```

**Comment by thaJeztah** [comment]
Did you build this version of docker yourself? It looks like the versions of `containerd`, `runc` and `init` don't match the required versions; using a different version of these can result in docker not working;

```
containerd version: v0.2.5 (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: c91b5be (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
```

**Comment by saksmt** [comment]
@thaJeztah, It's built with standard tools from gentoo, you can see build file (ebuild) at http://data.gpo.zugaina.org/gentoo/app-emulation/docker/docker-1.13.0_rc4.ebuild

Also if `init` here is sysvinit then it's version is: `2.88-r9`.

And runc is `1.0.0_rc2-r1`:
```
smt-server ~ # runc --version
runc version 1.0.0-rc2
commit: c91b5be
spec: 1.0.0-rc2-dev
```

**Comment by saksmt** [comment]
@thaJeztah Since which version docker depends on unreleased runc and containerd? I don't have any binaries in gentoo since 1.5.x, which fails to install due to dependency on outdate kernel flag, so I need to install it somehow

**Comment by saksmt** [comment]
Ok, I've tested all versions from 1.10 to 1.13-rc-r3, same problem persists everywhere... Also tested binaries - they just don't see lvm so they can't start due to missing device-mapper...

**Comment by saksmt** [comment]
UPD: copied all versions from my work-vm (for those, who want running docker of any version right now):
```
docker: 1.12.1
runc: 1.0.0_rc1
containerd: 0.2.3
kernel: 4.9
systemd: 232 (don't forget to set GRUB_CMDLINE_LINUX_DEFUALT="systemd.legacy_cgroup_controller=yes")
```

Tired of reinstalling/rewriting bunch of ebuild, will try to figure out which versions are compatible and where exactly bug is hidden after new year.
 
[Attached currently working ebuilds](https://github.com/docker/docker/files/678554/docker-backup-ebuilds.zip)

**Comment by kinzess** [comment]
works. thank you.

**Comment by ITPro360** [comment]
I too was having this issue and it was a result of attempting to override the docker.service in systemd and i just used the drop-in to override my docker settings and then added my socket and every thing seemed to start working again.

i am running coreos stable with docker 1.12.6.

Using the docker docs to properly configure docker with systemd solved my problem. Hope this helps anyone else looking for a solution to this problem.

**Comment by saksmt** [comment]
@ITPro360, if you have this on gentoo, than it's really strange... Otherwise it's not about this one, cause it is related to radius of curvature of gentoo maintainers hands, that's why I think I should close this one and open another one for gentoo repo. But I won't close this because it is not really good that I'm not able to just use binaries from build due to missing device-mapper in llvm (which is enabled) at least until I would see some reasoning about it.

P.S. Yeah, I know that source-based-distro-buddies must suffer, but anyway it is too weird... Especially when I'm afraid to update almost anything (glibc, go, systemd, kernel, ...) on my home server, because I really need docker to be working.

**Comment by thaJeztah** [comment]
ping @tianon any help you could offer?

**Comment by thaJeztah** [comment]
closing; this one went stale
