### ISSUE TITLE
Solo vs management commands

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#29801]
With 1.13 RC4

I like the nicely organized Docker commands in 1.13. However there are still a few commands that are shown solo. 

```
Commands:
  build       Build an image from a Dockerfile
  deploy      Deploy a new stack or update an existing stack
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  run         Run a command in a new container
  search      Search the Docker Hub for images
  version     Show the Docker version information
```

`build` can be accommodated in `image` management command, `run` in `container`. Similarly other solo commands may be aligned with other management commands.

**Comment by vdemeester** [comment]
@arun-gupta `build` is under `image`, `run` under `container`, `deploy` under `stack`, they are *alone* because of retro-compatibility — they are (at least `build` and `run`) so widely use as is that it would be crazy to move them.

```
λ docker image --help                                                                                                                                                                                                         

Usage:  docker image COMMAND

Manage images

Options:
      --help   Print usage

Commands:
  build       Build an image from a Dockerfile
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Display detailed information on one or more images
  load        Load an image from a tar archive or STDIN
  ls          List images
  prune       Remove unused images
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rm          Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE

Run 'docker image COMMAND --help' for more information on a command.
```

`login`, `logout`, `search` and `version`, it's another story 😝, they don't really fit in any category.

**Comment by arun-gupta** [comment]
@vdemeester All the legacy commands exist in 1.13 because of compatibility anyway. `build` and `run` may be given special treatment. `deploy` was introduced in 1.12 only. Does it need to be a top-level command?

How about `version` in `system`? Ditto for `login` and `logout`?

`search` is for images and so may fit there.

**Comment by vdemeester** [comment]
The root `deploy` command should only be available with `experimental` enabled (if it appears it's a little bit weird /cc @dnephin).

For `search` why not, but this could evolve into a `search` for plugins too for example.

**Comment by arun-gupta** [comment]
@vdemeester Commands were tested with 

```
Version 1.13.0-rc4-beta34.1 (14853)
Channel: Beta
b4ff3714d7
```

**Comment by thaJeztah** [comment]
I think the beta channel has experimental features enabled by default: should be visible in `docker version`

**Comment by thaJeztah** [comment]
Note that there's an environment variable that can be set to hide the "legacy" commands; https://github.com/docker/docker/pull/29803.

**Comment by rawkode** [comment]
Shouldn't `docker search` become `docker image search` or `docker registry search`?

Examples being:

`docker image search --registry "https://my-registry" -f is-official=true docker`
or
`docker registry search https://my-registry -f is-official=true docker`

I'm probably leaning more towards `docker image search`

**Comment by dnephin** [comment]
It should probably be something like `docker registry search`. We didn't feel the need to move everything right away. Doing `container` and `image` covered most of the top level commands.

`docker image` is for managing local images

**Comment by vdemeester** [comment]
Closing this as it is `cli` only. If you feel it's still relevant, please create the issue on `docker/cli` repository :angel: :pray:
