### ISSUE TITLE
Google DNS fallback logic does not work when only dnssearch is set

### ISSUE THREAD

**Issue by ibuildthecloud** [moby/moby#29815]
**Description**
If your host is using 127.0.1.1 for the DNS nameserver Docker uses Google DNS for the containers (8.8.8.8, 8.8.4.4) instead of 127.0.1.1.  This fallback behavior does not work if `--dns-search` is set.

**Steps to reproduce the issue:**
1. Run `docker run --dns-search foo.com ubuntu cat /etc/resolv.conf`

**Describe the results you received:**

```
search foo.com
nameserver 127.0.1.1
```

**Describe the results you expected:**
```
search foo.com
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 11
 Paused: 0
 Stopped: 4
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 975 MiB
Name: ubuntu
ID: OOSO:YJMC:LA6W:TWZL:XZK2:BMNH:OVL5:DQBE:ZJMF:KD4C:VVC5:7MDH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by yongtang** [comment]
I think the issue is located here:
https://github.com/docker/docker/blob/v1.13.0-rc4/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go#L191-L220

In case `--dns-search` is provided and `--dns` is not provided, `resolvconf.FilterResolvDNS()` will not be invoked to replace `localhost/127.*`.

I think the following diff may resolve the issue?
```udiff
diff --git a/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go b/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go
index f4d1fad..0ee398f 100644
--- a/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go
+++ b/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go
@@ -208,7 +208,9 @@ func (sb *sandbox) setupDNS() error {
                if err != nil {
                        return err
                }
-       } else {
+               currRC = newRC
+       }
+       if len(sb.config.dnsList) == 0 {
                // Replace any localhost/127.* (at this point we have no info about ipv6, pass it as true)
                if newRC, err = resolvconf.FilterResolvDNS(currRC.Content, true); err != nil {
                        return err
```

**Comment by sanimej** [comment]
@yongtang The block you referred to is where the issue is. But the fix needs to be more than calling `resolvconf.FilterResolvDNS()`. If any one of the dns configs `--dns`, `--dns-opt`, `--dns-search` is passed the code currently uses all the three from the user config to build the `resolv.conf`. Fix would be to use only the user provided config and take the rest from the host resolv.conf. Please push a libnetwork PR if you want to fix this.

**Comment by thaJeztah** [comment]
> Fix would be to use only the user provided config and take the rest from the host resolv.conf.

I guess we need some documentation around that as well, as the search-domain may be tied to the DNS server that's used, and which, in this example, is ignored/replaced by 8.8.8.8

**Comment by yongtang** [comment]
Added a PR https://github.com/docker/libnetwork/pull/1606 in libnetwork. Please take a look.
