### ISSUE TITLE
Docker Daemon can not restart containers after Windows Server reboot

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#29832]
**Description**

Sometimes our AWS Windows Server 2016 hangs and we have to reboot it from AWS console. After that Docker Daemon can not restart containers. Docker services is configured as "Automatic (Delayed start)". 

When it begins to start on Windows boot I see in the Event log a lot of errors (Failed to register container {hash}: name is reserved):
```
Failed to register container c347af82c1cd933a47f63ddbbb481c7bfc8545b72e14a371453fd0af1759ba02: name is reserved
Failed to register container 847d7d0f9cf4644db8aadfd55e16a252d532689ae24d406577e37a0026232e07: name is reserved
...
```
Then a lot of information messages (Removing stale sandbox):
```
Removing stale sandbox 80b25bde1824b96bbc0213d7a0a086c49de31e03b2468b90ec5bc43adaa1058c (329dabbbe7a11f59d56a7a30f9950846c2c0c20d6151352f1528c94cc359e51a)
Removing stale sandbox 6ddd3d57bd70f295c1fc7963d105f807a0e70ae5c6d1397c22aad323d13b3d54 (54c0dda8b963aa51f11f4a599757ac4e38a5d61ccf371125341128fca5d40c56)
...
```

after that a lot of another information messages (Removing stale sandbox):
```
Removing stale endpoint company-uat4_fl8_service (9604c705673659541f2be9f152911b30f9e7e51b0f63dd3015d57f9e266cf8c0)
Removing stale endpoint company-uat4_th4_service (27c58d6582b5f873dd38c5a2b083ad0d1592a5ae0816b113a93a8836789cb315)
...
```

Then a lot of mixing warnings (error locating sandbox id {hash}: sandbox {hash} not found) and errors (Failed to start container {hash}: failed to create endpoint hrms-nuview-prod_uri_service on network nat: HNS failed with error : The parameter is incorrect. ) :
```
Error: Failed to start container 4f0f49832f7bf31caa020c6344ec37615387b41a78ee3d17374c4eddd3b9466b: failed to create endpoint hrms-nuview-prod_uri_service on network nat: HNS failed with error : The parameter is incorrect. 
Warning: error locating sandbox id 3ca99656eca268fd37700ce38d90f2f75f115b47ec85195874a53f6e4258ecd0: sandbox 3ca99656eca268fd37700ce38d90f2f75f115b47ec85195874a53f6e4258ecd0 not found
...
```

After that Docker Daemon failt to start. But I see a lot of Virtual disks which were mounted by Docker.
```
PS>  (Get-Disk | ? {$_.Location -like "*docker*"}).count
199
```

Before server hangs we run about 50 containers with "--restart always" option.

Then, when I try to start Docker again then it can start, but it did not restart any containers.
In the Event log I see a lot of hcsshim errors
```
Failed to mount container 00820a08c68a4073f4d23d5d0509515414c2fe3d143111609110e34c9c937228: hcsshim::ActivateLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=00820a08c68a4073f4d23d5d0509515414c2fe3d143111609110e34c9c937228 flavour=1
```
```
hcsshim::ActivateLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=00820a08c68a4073f4d23d5d0509515414c2fe3d143111609110e34c9c937228 flavour=1
```

`docker ps` shows an empty list and `Get-Disk` more than 200 virtual disks.

If I stop Docker, dismount all virtual disk by similar command:
```
Get-Disk | ? {$_.Location -like "*docker*"} | foreach { Write-Host "Dismounting" $_.Location; Dismount-VHD -DiskNumber $_.Number}
```
and start Docker again then it shows the same error messages as first boot.

So, I expected that Docker Daemon would start my containers. Or at least would not mount so many virtual disks for corrupted containers. 

**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
PS C:\Users\Administrator> docker info
Containers: 55
 Running: 55
 Paused: 0
 Stopped: 0
Images: 97
Server Version: 1.13.0-rc4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 64
Total Memory: 1.906 TiB
Name: WIN-B737EJJT7B8
ID: 62EZ:P3MP:SQ3U:3UET:3JAP:QLAU:X2O4:E5NA:7WAH:BUGN:CAQT:VZ5V
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is an AWS x1.32xlarge instance

May be you can advise me where I need to investigate deeply or collect extra statistics/information?

Thank you in advance!

**Comment by thaJeztah** [comment]
ping @jhowardmsft @jstarks PTAL

**Comment by georgyturevich** [comment]
Hello all,

I have some extra information.

It stoped first time because of panic error. I run dockerd with -D flag and at the end it show me following error

```
panic: runtime error: slice bounds out of range

goroutine 215 [running]:
panic(0x14997e0, 0xc04200a050)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
syscall.Readlink(0xc042cb6300, 0x3b, 0xc042537e00, 0x80, 0x80, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_windows.go:1031 +0x3a9
os.Readlink(0xc042cb6300, 0x3b, 0x1eb7d00, 0xc042c96780, 0x0, 0x0)
        /usr/local/go/src/os/file_posix.go:21 +0x94
github.com/docker/docker/pkg/symlink.evalSymlinksInScope(0xc042cb6240, 0x3b, 0xc042cb62c0, 0x30, 0x0, 0x0, 0xc042cb61c0, 0x3b)
        /go/src/github.com/docker/docker/pkg/symlink/fs.go:122 +0x4b9
github.com/docker/docker/pkg/symlink.FollowSymlinkInScope(0xc042cb6240, 0x3b, 0xc0422517c0, 0x30, 0x3b, 0xd, 0x7, 0x7)
        /go/src/github.com/docker/docker/pkg/symlink/fs.go:30 +0xea
github.com/docker/docker/container.(*Container).GetResourcePath(0xc04223d6c0, 0xc042291ef0, 0xd, 0xd, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/container/container.go:273 +0x126
github.com/docker/docker/container.(*Container).SetupWorkingDirectory(0xc04223d6c0, 0x0, 0x0, 0x60, 0x1b0000)
        /go/src/github.com/docker/docker/container/container.go:238 +0xd5
github.com/docker/docker/daemon.(*Daemon).createSpec(0xc0420f81e0, 0xc04223d6c0, 0x0, 0x0, 0xc0420f81e0)
        /go/src/github.com/docker/docker/daemon/oci_windows.go:23 +0x205
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc0420f81e0, 0xc04223d6c0, 0x0, 0x0, 0x0, 0x0, 0xc042296a01, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/start.go:149 +0x297
github.com/docker/docker/daemon.(*Daemon).restore.func2(0xc042943af0, 0xc0420f81e0, 0xc04257cb10, 0xc04223d6c0, 0xc0424a6f60)
        /go/src/github.com/docker/docker/daemon/daemon.go:310 +0x272
created by github.com/docker/docker/daemon.(*Daemon).restore
        /go/src/github.com/docker/docker/daemon/daemon.go:314 +0x9dd
```

So. Docker was unable to mount all VHDs for all container but did not have a change to complete a start. If I try to start service second time it shows `hcsshim` errors (as I described in above post) for every container because VHDs were mounted in first try of start. As a result Docker service works but it does not  restart any containers.

Any ideas how I can investigate this panic error?

**Comment by georgyturevich** [comment]
It seems it is related to the GO 
issue [syscall: panic within syscall_windows.go Readlink](https://github.com/golang/go/issues/15978) which was fixed in https://github.com/golang/go/commit/e65bce7144dbced232df8842ef6825d7e45f094e for Go 1.8

Will try to debug Docker Daemon to understand a reason. Maybe someone else also has some ideas about possible workaround?

**Comment by friism** [comment]
@georgyturevich I haven't reproduced your problem but I did build a Go 1.8rc3 deamon for you to test with. Find it here: https://github.com/friism/docker-1/releases/tag/test-go-18rce3

You can also build it yourself (assuming a Windows daemon):

    git clone -b test-go-18rce3 https://github.com/friism/docker-1 docker
    cd docker
    docker build --compress -t builder -f Dockerfile.windows .
    docker run --name out -e DOCKER_GITCOMMIT=foo builder hack\make.ps1 -Binary
    docker cp out:C:\go\src\github.com\docker\docker\bundles\docker.exe .
    docker cp out:C:\go\src\github.com\docker\docker\bundles\dockerd.exe .

**Comment by friism** [comment]
I guess we have to wait for Go 1.8: https://github.com/moby/moby/pull/29030

**Comment by friism** [comment]
Related: https://github.com/moby/moby/issues/25440

**Comment by thaJeztah** [comment]
@friism is this resolved now that Go 1.8 is used? Or do we have to wait for Go 1.9? (https://github.com/moby/moby/issues/25440#issuecomment-305120423)

**Comment by friism** [comment]
@georgyturevich have you had a chance to try Docker CE 17.06? https://download.docker.com/win/static/stable/x86_64/

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
