### ISSUE TITLE
--cluster-advertise=eth0:2376 may not work with current systemd unit files

### ISSUE THREAD

**Issue by JamieGarside** [moby/moby#29876]
**Description**
With the current systemd unit file, using the `--cluster-advertise` flag of the form `adapter:port` may not work correctly, as the network may not have been configured by the time the Docker daemon starts and hence the daemon cannot obtain the IP address to bind to.

The root cause of this issue is that the unit file only specifies that Docker must be started after `network.target` has been fulfilled, however, `network.target` only specifies that network management is available, not that the interfaces have an address. Instead, the unit files should wait for the `network-online.target` target ([more info](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/))

For now, we can add a shim by creating the file `/etc/systemd/system/docker.service.d/wait-for-network.conf` with these contents:

    [Unit]
    Wants=network-online.target
    After=network-online.target

We noticed this issue on SoftLayer's recent CentOS 7 distributions, where it seems that a slight change to `NetworkManager-wait-online.service` has caused us to notice this issue. The previous configuration was as follows:

```
[network.target]
WantedBy=NetworkManager-wait-online.service NetworkManager.service
Before=docker.service network-online.target
After=NetworkManager.service network-pre.target network.service NetworkManager-wait-online.service

[network-online.target]
Wants=NetworkManager-wait-online.service
WantedBy=network.service
After=network.target network.service NetworkManager-wait-online.service

[network.service]
Wants=network-online.target system.slice
WantedBy=graphical.target multi-user.target
Before=network-online.target network.target
After=NetworkManager.service NetworkManager-wait-online.service

[NetworkManager-wait-online.service]
Requisite=NetworkManager.service
Wants=network.target system.slice
WantedBy=network-online.target
Before=network.target network.service network-online.target
After=NetworkManager.service

[docker.service]
After=network.target
```

Because `network.service` pulls in `network-online.target`, which pulls in `NetworkManager-wait-online.service`, which then _finally_ pulls in `network.target`, and the sequencing is set correctly, Docker used to wait successfully until after `network.target`, which will be fulfilled at the same time as `network-online.target`.

In the new setup, `NetworkManager-wait-online.service` no longer wants `network.target`. The result is that `network.target` is never actually pulled into the dependency graph, and hence `docker.service`'s `After=network.target` is a no-op, and `docker.service` then just starts with `multi-user.target`. Because it can then start simultaneously with `network.service`, there is no guarantee that the adapters have been configured correctly.

There's a few questions regarding this issue and the setup anyway (e.g. `NetworkManager-wait-online.service` actually shows as disabled in our setup, yet it still has a symlink in `/usr/lib/systemd/system/network-online.target.wants`) that could be a misconfiguration on SoftLayer's part. I also don't know whether this affects a "stock" CentOS install, or the CentOS images on other cloud providers.

**Steps to reproduce the issue:**
1. Provision a CentOS machine using `docker-machine` in SoftLayer, in clustered configuration (i.e. using the `--cluster-advertise=eth0:2376`) flag
2. Reboot the machine
3. Notice that Docker does not start on boot, complaining that it cannot get an IP address for `eth0:2376`)

**Describe the results you received:**
Docker does not start after a reboot, error `level=fatal msg="Error starting daemon: discovery advertise parsing failed (couldnt find a valid ip-address in interface eth0:2376)"`)

**Describe the results you expected:**
Docker should start successfully after the reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue started in mid-December, which we're assuming was at the same time that SoftLayer updated the CentOS 7 image (or CentOS upstream changed the unit file for `NetworkManager-wait-online.service`). We can reliably reproduce this now.

**Output of `docker version`:**
Can reproduce on 1.11.1 and 1.12.4

**Output of `docker info`:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-1187873-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 44.11 MB
 Data Space Total: 107.4 GB
 Data Space Available: 24.54 GB
 Metadata Space Used: 659.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.791 GiB
Name: NAME
ID: NL7U:JC7D:MVYN:QNRB:FD3F:VTZJ:NLNK:LRJN:P4K5:6QZV:R7EO:6WTD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
Cluster store: zk://IP:2181
Cluster advertise: IP:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Only tested and reproduced on SoftLayer. We can't currently test on other cloud providers.

**Comment by thaJeztah** [comment]
Actually, there's an open pull request adding this; https://github.com/docker/docker/pull/29727. I see it does not add `Wants=network-online.target`; do you think that's important to add?

**Comment by JamieGarside** [comment]
Aha, sorry, I had only searched issues when looking around :)

I think technically you should, since networking being alive is a dependency of Docker, so you'd want to also start networking with Docker, and `networking-online.target` isn't a passive dependency of Docker. The link I added above also suggests adding both `Wants` and `After`.

**Comment by JamieGarside** [comment]
These changes would also need making in Docker-Machine too though, or by resolving this bug: https://github.com/docker/machine/issues/3750

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
