### ISSUE TITLE
Unable to build simple docker image

### ISSUE THREAD

**Issue by yashgt** [moby/moby#29873]
I am following the instructions to build my image as given in :
https://www.ibm.com/developerworks/community/blogs/messaging/entry/introducing_a_docker_image_for_mq_advanced_for_developers?lang=en

**Steps to reproduce the issue:**
1. Create a dockerfile as
FROM ibmcom/mq
COPY config.mqsc /config.mqsc

2. Build the image
[root@dockervm1 mq]# docker build -t usp_docker_poc/mq .

**Describe the results you received:**
Sending build context to Docker daemon 5.12 kB
Step 1/2 : FROM ibmcom/mq
---> 9e2baaf570fd
Step 2/2 : COPY config.mqsc /config.mqsc
mkdir /var/lib/docker/overlay/cc96633cc0034b3575d34841ed4e1203acc21cec73fcf64aad2bdf29b5372e50-init/merged/dev/shm: invalid argument

**Describe the results you expected:**
Was expecting the image to build.

**Additional information you deem important (e.g. issue happens only occasionally):**
The build works for all other images that I have.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 61
 Running: 1
 Paused: 0
 Stopped: 60
Images: 27
Server Version: 1.13.0-rc3
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ghm1lwkgwr7bvsyo0rc2s7hnj
 Is Manager: true
 ClusterID: mfox5x2biauof9q4m8qodywg7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.44.209.53
 Manager Addresses:
  10.44.209.53:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.86 GiB
Name: dockervm1.persistent.co.in
ID: ZIF4:S7RM:3TMM:NOZH:DN24:T62P:VCAT:IEU7:YESM:EIM7:H7KA:6F25
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://myuser:mypwd@10.44.208.10:8080
Https Proxy: https://myuser:mypwd@10.44.208.10:8080
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Can you add the information that was requested in the issue template; https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

Without this information, we won't be able to look into your issue.

**Comment by thaJeztah** [comment]
Looks like you're using the `overlay` storage driver, but the backing filesystem does not have `d_type`  enabled. This may be related here; see https://github.com/docker/docker/issues/27358, https://github.com/docker/docker/issues/10294, and https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

**Comment by yashgt** [comment]
Do I need to re-format the filesystem? If so, which mount of the filesystem is to be formatted?
How is it that other images are building?

**Comment by thaJeztah** [comment]
An overview of storage drivers can be found [in the documentation](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/). You can use the device mapper driver, but performance will be a lot less than overlay, and for any serious work, it also needs a [dedicated device](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/for-a-direct-lvm-mode-configuration).

If you have a separate partition to reformat, you can configure docker to use that partition as storage location (either using the `-g` / `--graph` daemon flag, or using a [daemon.json configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file)

**Comment by yashgt** [comment]
How is it that other images are getting built without issue?

I tried:

> [admin@gol05854 ~]$ sudo cat /etc/docker/daemon.json
> {
>         "storage-driver": "aufs"
> }

I get the error:

> Jan 09 05:23:22 gol05854 dockerd[6298]: Error starting daemon: error initializing graphdriver: driver not supported

I have the following mounts:

> [admin@gol05854 ~]$ df -T
> Filesystem            Type     1K-blocks     Used Available Use% Mounted on
> /dev/mapper/rhel-root xfs       26967180 21642124   5325056  81% /
> devtmpfs              devtmpfs   2008504        0   2008504   0% /dev
> tmpfs                 tmpfs      2023612       84   2023528   1% /dev/shm
> tmpfs                 tmpfs      2023612    17180   2006432   1% /run
> tmpfs                 tmpfs      2023612        0   2023612   0% /sys/fs/cgroup
> /dev/sda1             xfs         508588   179100    329488  36% /boot
> tmpfs                 tmpfs       404724       16    404708   1% /run/user/42
> tmpfs                 tmpfs       404724        0    404724   0% /run/user/1000
> 

Only option left is to add a new partition. Is it sufficient to add an XFS partition with d_type=true? Kindly point me to the documentation that lays down this requirement explicitly. If this is not documented, I would request the documentation to be updated so that nobody else comes across this issue again.

**Comment by thaJeztah** [comment]
> Error starting daemon: error initializing graphdriver: driver not supported

Yes, the aufs storage driver needs the `linux-image-extra` package. I see it's mentioned in the Ubuntu docs (https://docs.docker.com/engine/installation/linux/ubuntulinux/#/prerequisites-by-ubuntu-version), but not in the AUFS storage driver document; I opened an issue for that in the documentation issue tracker; https://github.com/docker/docker.github.io/issues/1061 

> Only option left is to add a new partition. Is it sufficient to add an XFS partition with d_type=true

I think that would work, yes

> If this is not documented, I would request the documentation to be updated so that nobody else comes across this issue again.

Agreed; I opened an issue for that as well; https://github.com/docker/docker.github.io/issues/1062, but perhaps you're interested in opening a pull request? (You can find an "edit" link at the [bottom of the page](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/)

**Comment by yashgt** [comment]
Just wondering:
How is it that other images are getting built without issue?

**Comment by shaikhkhushboo** [comment]
@thaJeztah  As suggested by you, we have mounted docker on xfs30 file system with suggested –d option,  however looks like solution is not working.
We are facing same issues while building usp_docker_poc/mq from  ibmcom/mq.

![dockerfile](https://cloud.githubusercontent.com/assets/16779774/22280722/abe06e6e-e2f8-11e6-99e6-2e9f52ae863c.PNG)
![error](https://cloud.githubusercontent.com/assets/16779774/22280728/b56239c2-e2f8-11e6-9e12-63896be300ea.PNG)
![d_info](https://cloud.githubusercontent.com/assets/16779774/22280731/ba532e5a-e2f8-11e6-87bc-69eea7a03763.PNG)
![d_version](https://cloud.githubusercontent.com/assets/16779774/22280735/bdc10d78-e2f8-11e6-8f3b-ea2989cb837b.PNG)

Is there any alternative that can be given as a try ??

**Comment by thaJeztah** [comment]
I don't have a direct answer; some suggestions;

- check your daemon logs, and system logs
- the version of docker you're using is outdated (docker 1.13.0 has been released)
- you're running an old version of RHEL (7.3), with an old kernel. A vanilla kernel 3.10 does not support the overlay storage driver, and support for overlay is back ported by Red Hat to their 3.10 kernels. However, it's important to keep that kernel up to date, because they're still working on fixing things in that back port.

**Comment by thaJeztah** [comment]
Closing, because this went stale, and most likely is related to;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

Running overlay (or overlay2) on XFS without `d_type` is known to cause issues. Docker currently "allows" it for backward-compatibility, but will block it in future, you'll see a warning being logged about this as well when starting the daemon;

```
overlay: the backing xfs filesystem is formatted without d_type support,
which leads to incorrect behavior. Reformat the filesystem with ftype=1
to enable d_type support.
Running without d_type support will no longer be supported in Docker 17.12.
```

Also see these issues, which contain some information https://github.com/moby/moby/issues/10294, https://github.com/moby/moby/issues/29873.

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.

**Comment by anhilde** [comment]
Hi, I have issues with the ftype flag as well and can't figure out how to get rid of the problem. Generally I have problems understanding docker storage and fail to find a thourough explanation I can work with. I have been looking at this for quite some time. If I start the daemon it says:

WARN[0001] overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior. Reformat the filesystem with ftype=1 to enable d_type support. Running without d_type support will no longer be supported in Docker 17.12. 

However prior to starting I created the file system using the command:

`mkfs -t xfs -n ftype=1 /dev/rhel/docker-pool
meta-data=/dev/rhel/docker-pool  isize=512    agcount=32, agsize=10147968 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=324734976, imaxpct=5
         =                       sunit=128    swidth=128 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=158562, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0`

I have no clue whatsoever what more I can do then to create the xfs file system using the command used. Any clue as to where to read up on this issue to understand what is going on and who is responsible for what (i.e. what do I have to do during setup as preparation so the docker deamon can run?), would be greatly appreciated.

Best Regards,

André

**Comment by chinkung** [comment]
@anhilde Try to stop docker, mount **/dev/rhel/docker-pool** to **/var/lib/docker** then start docker and check again.
