### ISSUE TITLE
Docker pull hangs while trying to pull the registry

### ISSUE THREAD

**Issue by prashantabkari** [moby/moby#29870]
While trying to deploy the registry the docker pull hangs and it is stuck and is not coming out
[root@centos-master progs]# /bin/docker run -d -p 5000:5000 --restart=always --name registry registry:2
Unable to find image 'registry:2' locally
Trying to pull repository docker.io/library/registry ...
2: Pulling from docker.io/library/registry
b7f33cc0b48e: Downloading [>                                                  ] 32.26 kB/2.313 MB
46730e1e05c9: Waiting
b7574c100797: Waiting
2e5b74c7b611: Waiting
ba42bd458a59: Waiting

**Expected** 
Docker pull of registry should be successful and a container should start. 

**Output of `docker version`:**
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

**Output of `docker info`:**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-67310226-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 265.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 49.91 GB
 Metadata Space Used: 892.9 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.555 GiB
Name: centos-master
ID: LDOW:AQ24:BUH3:GESV:6USN:5EEM:ZNLJ:PB2C:YVY4:B7GG:BQ56:YW4Z
Http Proxy: http://87.254.212.120:8080/
Https Proxy: https://87.254.212.120:8080/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Kubernetes is installed. 

[root@centos-master progs]# ps -eaf | grep docker
root      7904     1  0 Jan03 ?        00:00:55 /usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled --log-driver=journald
root     10527 10240  0 10:42 pts/0    00:00:00 grep --color=auto docker

**Comment by thaJeztah** [comment]
It looks like you're running a Red Hat fork of docker. That fork contains a lot of modifications from the official packages (https://github.com/docker/docker/compare/v1.10.3...projectatomic:rhel7-1.10.3), which may well be related, and we cannot support those versions. Also, docker 1.10.3 is no longer maintained.

Are you also having this issue if you install the official packages? https://docs.docker.com/engine/installation/linux/centos/

**Comment by prashantabkari** [comment]
This came along with the Kubernetes package. So should i uninstall the
existing one and install the newer docker-engine version?

**Comment by thaJeztah** [comment]
The Kubernetes package in the CentOS repository is probably "pinned" to use the Red Hat fork. Maybe this procedure works; http://kubernetes.io/docs/getting-started-guides/kubeadm/, but I'm not sure I'm able to help you with that.

**Comment by prashantabkari** [comment]
Sorry i didnt get how kubeadm's functionalities are related to Docker? 
Probably the question is more on Kubernetes as to why docker package which is pinned does work to pull the messages. But is there a way to get the internal logs to understand why this is happening?

**Comment by thaJeztah** [comment]
The docker daemon logs can be found in your system logs (e.g. on a system running `systemd`, `journalctl -u docker.service`)

**Comment by prashantabkari** [comment]
Any idea how to move this issue to Kubernetes ? Should it create a new issue?

**Comment by thaJeztah** [comment]
Yeah, kubernetes is a whole separate project, so may be worth opening an issue there (how to install the official docker packages together with kubernetes)

**Comment by thaJeztah** [comment]
closing; this one went stale
