### ISSUE TITLE
Invalid plugin references in docs

### ISSUE THREAD

**Issue by albers** [moby/moby#29886]
The docs contain plugin examples/references that do no longer work: `tiborvass/no-remove`, `vieux/sshfs`.

```bash
$ docker plugin install tiborvass/no-remove
Error response from daemon: repository tiborvass/no-remove not found: does not exist or no pull access
$ docker plugin install vieux/sshfs
Error response from daemon: invalid rootfs in image configuration
```

Solution: either update the plugins so that they work again or use other plugins.
An even better solution would be to create official sample plugins in the docker namespace for each extension point and consistently use these.

These are the references I found:
```bash
$ grep -Rl 'vieux/sshfs'
docs/reference/commandline/plugin_install.md
docs/extend/index.md
$ grep -Rl 'no-remove'
docs/api/v1.24.md
```

Note: the following plugins do work:
* `cpuguy83/docker-overlay2-graphdriver-plugin`
* `tonistiigi/authz-no-volume-plugin`

**Comment by albers** [comment]
related: bcead92

**Comment by tonistiigi** [comment]
There will be incompatible plugin changes between `rc4` and `rc5`. New versions will be pushed to old names after `rc5` is out.

**Comment by albers** [comment]
@tonistiigi ATM, it is difficult to test the plugin commands (e.g. when developing bash completion) because there are so few plugins. How about adding tags for the old and upcoming plugin versions?

**Comment by albers** [comment]
1.13.0 is out now. The `vieux/sshfs` plugin now works, but `tiborvass/no-remove` still gives an error:

```bash
$ docker plugin install tiborvass/no-remove
Error response from daemon: repository tiborvass/no-remove not found: does not exist or no pull access
```
Ping @tiborvass Please update the plugin or remove the reference in _docs/api/v1.24.md_.

**Comment by rootsongjc** [comment]
+1 
`viex/sshfs` doesn't work on docker 1.13.1
https://github.com/docker/docker/issues/31723

**Comment by thaJeztah** [comment]
@albers I think these are all ok now, or is there still something to fix?

**Comment by albers** [comment]
@thaJeztah I still found two issues that I fixed in https://github.com/docker/cli/pull/423.

**Comment by thaJeztah** [comment]
Thanks! https://github.com/docker/cli/pull/423 was merged, so let me close this here (docs will have to be cherry-picked, so are not online yet)
