### ISSUE TITLE
The Go API cannot be used

### ISSUE THREAD

**Issue by dlsniper** [moby/moby#29890]
I'm trying to run the example in this documentation: https://godoc.org/github.com/docker/docker/client#hdr-Usage

```go
package main

import (
	"context"
	"fmt"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)

func main() {
	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	containers, err := cli.ContainerList(context.Background(), types.ContainerListOptions{})
	if err != nil {
		panic(err)
	}

	for _, container := range containers {
		fmt.Printf("%s %s\n", container.ID[:10], container.Image)
	}
}
```

But for obvious reasons, when running the example against the latest release of Docker, 1.12.5, that doesn't work.
The error I get is: 
```
panic: Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)
```
I understand that semantic versioning has no significance for this project, because the API breaks in point releases, but it would be cool if at least examples would work.

**Comment by thaJeztah** [comment]
You can either set environment variables to override the version if you're talking to an older daemon; https://godoc.org/github.com/docker/docker/client#NewEnvClient, or use `NewClient()` to explicitly set a version; https://godoc.org/github.com/docker/docker/client#NewClient

That documentation is generated from "master", so matches a daemon built from master. 

Perhaps a mention of that can be added to the top example; are you interested in opening a pull request to improve the description? https://github.com/docker/docker/blob/master/client/client.go#L17

**Comment by cpuguy83** [comment]
>  because the API breaks in point releases

Do you have an example of this?

**Comment by ahmetalpbalkan** [comment]
This is rather an issue belongs to go-dockerclient repo. This has always been the case and probably will be. Maybe the default client should not specify a version (as it is optional),

**Comment by stevvooe** [comment]
@dlsniper Please reword your bug report with a little respect. That sort of tone is unacceptable.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale; the client can now also be configured with API version negotiation, which should help with cases like this
