### ISSUE TITLE
docker build from git repo with ssh protocol url

### ISSUE THREAD

**Issue by bytesandwich** [moby/moby#29919]
**Description**

**Steps to reproduce the issue:**
1. docker build ssh://git@mygitrepo.com/repo.git

**Describe the results you received:**

unable to prepare context: unable to evaluate symlinks in context path: lstat `pwd`/ssh:: no such file or directory

**Describe the results you expected:**

I expected that the build would invoke git checkout 
https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/gitutils/gitutils.go#L99

**Additional information you deem important (e.g. issue happens only occasionally):**

Can we just add ssh:// here:
https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/urlutil/urlutil.go#L11
?

**Output of `docker version`:**

```
docker --version
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
docker info
Containers: 174
 Running: 0
 Paused: 0
 Stopped: 174
Images: 1940
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2290
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.817 GiB
Name: moby
ID: ROGJ:KNVT:MHXG:Q7FS:2EV3:PPTL:WXQ7:RADW:FY2R:MR3R:INKU:HA46
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-01-05T19:58:37.009670518Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
[redacted]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
It works fine without the `ssh://` which I think is the standard git ssh URL syntax.

**Comment by bytesandwich** [comment]
Thanks for responding, @justincormack. We can definitely get by without it, but the ssh style has its pros and cons. Using the scp like style, if you have a non default port, then you have to specify it in your ssh config, when otherwise you might not have needed it. I also find that bitbucket tends to prefer using ssh:// in all its documentation and in its `clone` links on pages.

**Comment by justincormack** [comment]
@bytesandwich Yes, it would seem reasonable to support it.

**Comment by ijc25** [comment]
@justincormack,

> It works fine without the ssh:// which I think is the standard git ssh URL syntax.

I think you are thinking of `git@mygitrepo.com:repo.git` rather than the `git@mygitrepo.com/repo.git` you'd get from stripping `ssh://` from the example given in this issue (subtle difference in `:` vs `/` after the domain).

`git@mygitrepo.com:repo.git` and `ssh://git@mygitrepo.com/repo.git` are both valid according to [`git-clone(1)`](http://www.kernel.org/pub/software/scm/git/docs/git-clone.html#URLS) while I don't think `git@mygitrepo.com/repo.git` is (or at least isn't documented to be).

The problem with just treating `ssh://` as a possible git url is that you then rule out the possibility of cloning from other types of VCS repo via ssh. Some projects support `git+ssh://` to mean git clone over ssh to avoid this (and likewise support `svn+ssh://` etc too).

**Comment by ecnerwala** [comment]
#dibs, I'll add the `git+foo://` syntax, which is pretty universally accepted afiak.

**Comment by thaJeztah** [comment]
closing this per https://github.com/moby/moby/pull/33711#issuecomment-341512110

**Comment by beruic** [comment]
Has this been released?

**Comment by thaJeztah** [comment]
@beruic if you can spare two seconds to click the link above, you’ll get your answer

**Comment by beruic** [comment]
@thaJeztah Sorry. I guess I may need to open a new issue, since I cannot make it work.

**Comment by thaJeztah** [comment]
@beruic did you _click_ the link, and read what was there?

**Comment by beruic** [comment]
Yes, and I just read it again. It got me a bit further, so now I'm sure there is something wrong. It won't accept that I have a port number other than 22 in my URL.
