### ISSUE TITLE
[feature]: add daemon flag to set no_new_priv as default for unprivileged containers

### ISSUE THREAD

**Issue by jessfraz** [moby/moby#29951]
Would be nice :)
naming can be up to the implementer, i dont care

**Comment by justincormack** [comment]
It would be nice. There is no way to disable it at the moment on `docker run`, so it would be quite effective...

**Comment by runcom** [comment]
Ping @mrunalp

**Comment by mrunalp** [comment]
:+1: That way admin could secure all containers by default and we could still allow per container to override the daemon setting.

**Comment by justincormack** [comment]
@mrunalp there is currently no way to override I don't think... `--security-opt=no-new-privileges=false` fails. Because there was no way to set a default before there is no way to override.

**Comment by mrunalp** [comment]
@justincormack I see what you mean. However I imagine there would be use cases where one would want to disable NNP but not pass privileged.

**Comment by justincormack** [comment]
@mrunalp yes, it would make sense to convert it to a proper boolean flag at the same time

**Comment by jmzwcn** [comment]
Great, put some reference [here](https://www.freedesktop.org/software/systemd/man/systemd.exec.html).

**Comment by jessfraz** [comment]
Is that the right link

**Comment by jmzwcn** [comment]
I thnk this is [right](https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt).

**Comment by jmzwcn** [comment]
Great, could we set it [here](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file)?:
look like:
{
    "no-new-privileges": true
}
in /etc/docker/daemon.json?

**Comment by jmzwcn** [comment]
Having created a PR for this issue, please feel free to let me know if there is any problem.

**Comment by jmzwcn** [comment]
Very sorry for so many duplicated commit, already created a new one. Please let me know if there is any problem.

https://github.com/docker/docker/pull/29984

**Comment by thaJeztah** [comment]
implemented through https://github.com/moby/moby/issues/29984, and https://github.com/moby/moby/pull/32944
