### ISSUE TITLE
Install script should warn/error with future distro releases

### ISSUE THREAD

**Issue by tiborvass** [moby/moby#29983]
The problem is apparent right now with Ubuntu Yakkety 16.10 and Docker 1.12 on https://get.docker.com/

Basically https://github.com/docker/docker/blob/v1.12.5/hack/install.sh#L451 makes it so that regardless of what is supported in our apt.dockerproject.org repo, any new ubuntu release will fail installing docker if our apt repo has not been updated before the ubuntu release.

I suggest we add a variable corresponding to the latest supported `${lsb_dist}-${dist_version}` version and the script could either warn if the latest distro is not yet supported and/or install that latest supported version instead. IOW, ubuntu-yakkety would install docker from the ubuntu-xenial repo.

Thanks @erikh for pointing this out.

**Comment by tiborvass** [comment]
cc @mlaventure @andrewhsu @vieux

**Comment by thaJeztah** [comment]
We'd still have a similar problem for releases no longer supported (installing old versions of docker), or architectures not supported.

Not sure if there's an easy solution unless we bake all literal arch/versions into the script

**Comment by vdemeester** [comment]
The script is now living https://github.com/docker/docker-install, and issue related to that should be reported there. Closing 👼
