### ISSUE TITLE
cluster error is not so readable ("context deadline exceeded")

### ISSUE THREAD

**Issue by allencloud** [moby/moby#29987]
**Description**

Hi, All, 

I found that the error returned from swarmkit and returned to docker daemon, finally returned to client side is not so readable.

Since we always get rpc error like `rpc error: code = 4 desc = context deadline exceeded`, however we always cannot decide which part returns such kind of error.

When user calls an API, the handler may call swarmkit several times and each time may return an error like `rpc error: code = 4 desc = context deadline exceeded`, for programmers we need to debug 
where it returns, but obviously currently we cannot.

ping @aaronlehmann @tonistiigi 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:59:15 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   e75ca4f
 Built:        Mon Jan  9 02:24:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 37
Server Version: 1.14.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 7ae07lyjg73yt09kdu2mrox49
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 192.168.59.103
 Manager Addresses:
  0.0.0.0:2377
  192.168.59.103:2377
  192.168.59.104:2377
  192.168.59.105:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: Q2ZC:GWDN:27OH:GRMH:G6QU:W7QP:4TIX:Q5F6:YEVK:45XP:EXHC:HOB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 96
 System Time: 2017-01-09T10:48:33.835141601+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://a.b.c/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aaronlehmann** [comment]
I don't really like the current errors either.

I think whenever we encounter a context deadline exceeded error, we should rewrite it to a coherent explanation of what timed out, and perhaps list possible reasons that could cause the timeout (loss of quorum, etc).

**Comment by dperny** [comment]
When working on docker/docker-e2e, I had problems where things were timing out causing `context deadline exceed` errors, but the root cause of the timeout was some other error that was getting ignored, superseded, or otherwise buried. At the very least, moving forward, we need to make sure that raw `context deadline exceeded` errors are annotated with some... like... context.

**Comment by aaronlehmann** [comment]
We may want to try moving some timeout logic from the gRPC client to the gRPC server. I suspect that often we let the RPC client time out, instead of having timeout logic in the handler that can return a specific reason for why the operation didn't succeed.

**Comment by allencloud** [comment]
Hi, @dperny 
Could you share a little bit about the progress of handling this issue? 😄

**Comment by dperny** [comment]
Sorry, @allencloud, it slipped my mind. I'll let you know in a couple of hours where this falls in my triage.

**Comment by dperny** [comment]
This is like a P2 or a P3 for me right now, so I don't know when I'll get to it.

**Comment by dperny** [comment]
This is still lower-priority, but I don't *think* the work is hard. You would need to go through the code and wherever the engine calls out to swarmkit, wrap that error with a message explaining what failed, perhaps using `github.com/pkg/errors.Wrap`. Tedious, but not difficult.

**Comment by thaJeztah** [comment]
@allencloud @ripcurld0 perhaps one of you would be interested in helping with this?

**Comment by ripcurld0** [comment]
@thaJeztah sure I would.
@allencloud is that OK if I call #dibs on that?

**Comment by thaJeztah** [comment]
I was chatting with @dperny and he was still busy on other things, hence me asking :smile: but ask away if help if needed for implementing :heart:

**Comment by allencloud** [comment]
@ripcurld0 Thanks a lot for helping this. And yes, feel free to add #dibs for you to solve this.
I am a little bit busy on other things as well.  😄

**Comment by ripcurld0** [comment]
@allencloud thanks a lot.
calling #dibs 😃

**Comment by allencloud** [comment]
friendly ping @ripcurld0 
What is the status of this one? 😄 ☀️

**Comment by ripcurld0** [comment]
I was trying to reproduce such a case but didn't successfully so I was reading the source code and did some changes but I have no way to test it and got frustrated. 

I will contact @dperny through slack in the next days to get some ideas how to verify this change.

**Comment by aaronlehmann** [comment]
I think the situation has improved a lot since this issue was filed. There's now a special error message when quorum has been lost for some time: https://github.com/docker/swarmkit/pull/2129

Most of the cases where a "context deadline exceeded" error showed up were actually loss-of-quorum situations, and now these show a more useful error.

I suppose there are further improvements we could make for other situations, like showing whether the deadline was exceeded in the client or in the swarm manager. This seems relatively unimportant, though.

What do you think? Should we close this issue?

**Comment by allencloud** [comment]
That is great. Thanks a lot. Closing this.

**Comment by cecton** [comment]
Hello @aaronlehmann I have just a small question. Is it planned to port the fix to the previous versions of Docker? I see it is tagged as an "enhancement" so I suppose not but there are only 2 versions of Docker that still have the behavior: 17.05 and 17.04.

**Comment by thaJeztah** [comment]
17.05 and 17.04 are "edge" (monthly, short term support) releases, both are EOL now that 17.06 is released
