### ISSUE TITLE
Need a way to mask objects from `docker system prune`

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#29999]
Right now `docker system prune` removes resources which are not currently in use.
This can be problematic since some of these objects store persistent data which is important even if it's not in use at the moment prune is called.

We need some way to mask these items from `docker system prune` (and the object specific commands).
The simple thing may be to add support for filters... so it could be something like `docker system prune --filter label!=my_important_stuff`

Another approach may be to mark these objects in some way... `docker volume pin foo`, for example.
The problem with this particular verb is it can mean different things for images.

**Comment by thaJeztah** [comment]
Initial filters are here; https://github.com/docker/docker/pull/29226

**Comment by craigbarrau** [comment]
Thanks for the update @thaJeztah 

In the future, would you consider a filter based on image name in addition to the filter based on time mentioned in #29226?

Perhaps a less common use case, but I have some large 3rd party vendor images (up to or greater than 10Gb) and live where there is relatively slow internet (read: Australia). Deleting these images is not desirable if I plan to boot containers from them in the foreseeable future as it will take up to 10-20 minutes to download the again (best case scenario).

**Comment by thaJeztah** [comment]
@craigbarrau yes, I can see more filters being useful, name could be considered, or the suggestion that @cpuguy83 gave; i.e. being able to "pin" images/containers/volumes to explicitly mark them, and prevent them from being removed

**Comment by yongtang** [comment]
Added a PR #30740 to add `label=..` and `label!=...` filters.

**Comment by cpuguy83** [comment]
Let's close this since you can now filter and even the docker cli can have default filters.
