### ISSUE TITLE
Deprecate --cluster-store and --cluster-advertise daemon flags

### ISSUE THREAD

**Issue by mavenugo** [moby/moby#30013]
With the introduction of `--attachable` flag in 1.13.0 for overlay driver in docker daemon and proper support for this flag in the upcoming `docker-compose 1.10.0`, I think it is a good time to deprecate the old `--cluster-store` and `--cluster-advertise` daemon flags that depends on external KV-Store. With the help of `--attachable` flag, users can run traditional containers in multi-host overlay network using docker swarm-mode.

@docker/core-maintainers pls 👍 or 👎

**Comment by thaJeztah** [comment]
Makes sense, if Docker Swarm (standalone) is modified to automatically take this into account, and we take the deprecation period into account.

**Comment by tomdee** [comment]
Where does this leave network plugins? Calico is a global driver and relies on having those flags set. It looks like networking plugins aren't going to work with swarm-mode in v1.13.0 so deprecating seems a little premature.

**Comment by mavenugo** [comment]
@tomdee I agree. unfortunately we had to disable the network plugin support in swarm-mode just prior to 1.13.0-rc6. Until we get that resolved, we should not deprecate these flags. We are actively working to resolving this situation.

**Comment by y2kenny** [comment]
Please don't deprecate this until cap-add works for swarm mode.  My application cannot use swarm mode w/o cap-add so I need a way to have multi-host networking without swarm.

**Comment by thaJeztah** [comment]
@y2kenny if you enable swarm mode, and create overlay networks with `--attachable`, you can use `docker run` with those networks; you don't have to use swarm services if you don't want to

**Comment by y2kenny** [comment]
um... can you elaborate a bit more?  So I setup a swarm with an overlay network and have worker nodes joining the swarm.  And I can use `docker run` on the worker nodes to join the overlay network?  Would `docker-compose` work as well?

**Comment by thaJeztah** [comment]
Yes;
- install docker on all nodes.
- Initialize swarm on a manager node (`docker swarm init`)
- join workers to the swarm (`docker swarm join ...`)

You're now set;

- on a manager node, run `docker network create -d overlay --attachable testnet`
- on another node, run, e.g. `docker run -d --network=testnet nginx:alpine`

The container is now on the overlay network

**Comment by thaJeztah** [comment]
docker compose would work, but would obviously only deploy containers on the node that it is communicating with.

**Comment by y2kenny** [comment]
Do I need to network create on the workers?  I defined this in the compose file:
```
networks:
  testnet:
    external:
      name: testnet
```
but it tells me testnet not found.

**Comment by thaJeztah** [comment]
hm odd; does it work if you use `docker run`?

**Comment by y2kenny** [comment]
looks like it does.  I guess I need to convert the compose file into a run command?

**Comment by thaJeztah** [comment]
I guess what may happen is that compose attempts to find the network, but swarm managed networks are automatically extended to the node they're needed on; not entirely sure

**Comment by thaJeztah** [comment]
May be worth opening an issue in the docker compose issue tracker

**Comment by y2kenny** [comment]
I also find the internal DNS doesn't work with swarm mode (just on the manager node).  The same exact compose file (except the networks part), which brings up multiple containers that talk to each other via name, works when I just have a bridge network.  But doesn't work in swarm.  (The containers each get an IP as defined by the overlay network but DNS doesn't work.)  It stays broken even after I tried `docker node leave --force`.  Reboot fixed it.

**Comment by y2kenny** [comment]
Sorry for distracting from the original issue, I will stop.

**Comment by hard-fault** [comment]
@mavenugo It will be inconvenient to use standalone containers to the overlay network. Will --attachable flag allow me to connect a standalone container to the overlay without Swarm?

**Comment by thaJeztah** [comment]
@hard-fault swarm mode needs to be enabled (to activate the built-in key/value store), but you can `docker run --network=some-overlay-network` for any overlay network that was created with the `--attachable` option

**Comment by thaJeztah** [comment]
- superseded by https://github.com/moby/moby/issues/40383 (work on this was completed)
