### ISSUE TITLE
--log-ops ignored when log-driver is journald

### ISSUE THREAD

**Issue by roasties** [moby/moby#30023]
**Description**
Unable to get tag information into the journald log when logging-driver=journald is used, always just logs the output under dockerd[pid]:

**Steps to reproduce the issue:**
`docker run --log-driver=journald --log-opt tag="{{ .ID }}" centos:7 echo TEST`
or
`docker run --log-driver=journald --log-opt tag="xxxxxx" centos:7 echo TEST`

**Describe the results you received:**
In journal log:
`Jan 09 17:40:28 <hostname> dockerd[18793]: TEST`

**Describe the results you expected:**
`Jan 09 17:40:28 <hostname> <container ID>[18793]: TEST`
or
`Jan 09 17:40:28 <hostname> xxxxxx[18793]: TEST`

**Additional information you deem important (e.g. issue happens only occasionally):**
Setting log-driver to syslog works, the tag is added to the log.

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64```

**Output of `docker info`:**

```
Containers: 16
 Running: 4
 Paused: 0
 Stopped: 12
Images: 10
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 2.593 GB
 Data Space Total: 8.154 GB
 Data Space Available: 5.561 GB
 Metadata Space Used: 1.032 MB
 Metadata Space Total: 83.89 MB
 Metadata Space Available: 82.85 MB
 Thin Pool Minimum Free Space: 815.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993 MiB
Name: merlinworker-a3
ID: UYTI:ESK5:EN2C:DSPS:RBND:HJR2:QR42:JQVJ:T7S4:VY5W:WLC5:E4WV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 7 running under vagrant on virtualbox

**Comment by roasties** [comment]
Same happens on Centos 7 in AWS

**Comment by milindchawre** [comment]
I would like to work on it.
#dibs

**Comment by milindchawre** [comment]
I am trying to run docker container with log-driver as journald inside docker dev container.
But was unable to run it getting this error : `docker: Error response from daemon: failed to initialize logging driver: journald is not enabled on this host.`
When I tried to run this `systemctl status systemd-journald` inside docker dev container, getting this error : `Failed to get D-Bus connection: Unknown error -1`
Is there anyway to have journald log-driver inside docker dev container.

**Comment by piersharding** [comment]
Hi -

This would be great if it worked properly as journald seems to be the only other logging mechanism that works with docker service logs other than json files.  The opts appear to be deliberately disabled - https://github.com/docker/docker/blob/master/daemon/logger/journald/journald.go#L85
Cheers,
Piers Harding.

**Comment by ripcurld0** [comment]
@piersharding the `--log-opts tag` option is actually enabled.

**Comment by ripcurld0** [comment]
@roasties to see the tag in the journal logs, use `-o json`.
Does that work for you? Is there any good reason to see the tag in the message?

**Comment by piersharding** [comment]
Ah - my bad @ripcurld0 - I did not know the -o json option for journalctl .  I assumed that what's in the message is all that you get.  The real problem for me is that when ForwardToSyslog=yes is enabled none of the tag data gets passed along, and I'm using syslog forwarding to centralise logging (I don't want to run logstash on every node, and journalbeat is not there yet).

Cheers,
Piers Harding.

**Comment by ripcurld0** [comment]
@piersharding so I guess you just want the tag in the message, right?
I tried to Google it but didn't find any satisfied result about how to forward the journal logs as JSON to syslog.

Anyway, I will work on it in the next days.

**Comment by piersharding** [comment]
Yes - that's where I ended up too.  The nearest approximation that I have come up with is:
journalctl --unit=docker --follow -o json | python -c 'import sys; import socket;sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM); [sock.sendto(l, ("<IP>", <SOCKET>)) for l in sys.stdin]'

A bit like using logspout - could put it in a container, or run it as a unit.

Cheers,
Piers Harding.

**Comment by bestofmukul** [comment]
@ripcurld0 When you add tag in the message, can you please include other log-opts like env and labels too, just like jsonfile logging driver.
-Thanks

**Comment by ripcurld0** [comment]
@bestofmukul do you mean to see labels and envs in the journald log message?

**Comment by bestofmukul** [comment]
Yes, that way configured log-opt vars can be easily forwarded to centralized logging server using mechanism described [here](https://github.com/docker/docker/issues/30023#issuecomment-286878975).

**Comment by ripcurld0** [comment]
wouldn't be too much? The message might be longer.

**Comment by bestofmukul** [comment]
The only extra information that is being added is log-opts attributes and value. This is controlled by user configuration. So, I don't think message length should be a problem(user can always go back and change log-opts).

**Comment by zarnovican** [comment]
```
docker run --log-driver=journald --log-opt tag=foo
```
I believe, that sending `SYSLOG_IDENTIFIER` _in addition_ to `CONTAINER_TAG` would elegantly fix the problem. Not only would journalctl start printing the tag (foo), instead of unit name (docker) as the message source. You would be able to use native journalctl filtering as well (journalctl -u docker -t foo):

* Can you send `SYSLOG_IDENTIFIER` even if transport is journal ? Yes, you can. Journald does not mind (tested).
* What if no log option tag was specified ? Personally, I believe no `SYSLOG_IDENTIFIER` should be generated. But even the current default value (container id) is ok.
* You have all of this in `syslog` driver, why not to use that instead ? Syslog driver does not work with `docker service logs`.
* Why not just rename CONTAINER_TAG to SYSLOG_IDENTIFIER ? This was suggested on PR, but frankly I didn't get author's reasoning https://github.com/moby/moby/pull/19564/files#r50530679. Adding an attribute is probably safer.
