### ISSUE TITLE
Windows docker -f doesn't follow instantly

### ISSUE THREAD

**Issue by hongxima** [moby/moby#30046]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

Windows docker -f  doesn't follow instantly as expected. Most the times It just outputted the history logs and stuck there , seldom it outputted new logs every one minute.
This happens ONLY to Windows docker.

**Steps to reproduce the issue:**
1.
`docker run -d --name=log-tester microsoft/windowsservercore powershell while ($true) {$d=Get-Date; write-host 'Time is:' $d; Sleep 1}`
2.
`docker logs -f log-tester`

**Describe the results you received:**
Logs didn't get printed every second. Instead, only history logs were outputted but new logs either didn't printed (most testcases) or printed in a batch  every one minute (in very few testcases)

**Describe the results you expected:**
logs should be outputted in stream instantly. In this particular testcase, logs should get printed every second. 

**Output of `docker version`:**

```
C:\Users\Administrator>docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   f93c04d
 Built:        Sat Dec 17 15:16:54 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          f93c04d
 Built:               Sat Dec 17 15:16:54 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
C:\Users\Administrator>docker info
Containers: 8
 Running: 3
 Paused: 0
 Stopped: 5
Images: 25
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.999 GiB
Name: WIN2016-DOCKER-01
ID: MCVH:SYEM:X2IN:FRIH:CYGH:HGLB:PAKZ:XAME:2IE7:PNZF:XTTL:EDLM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.180.200:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Workstation 12.5.1 Virtual Machine

**Comment by thaJeztah** [comment]
Wondering; is it _time_ related, or does if flush logs once a specific size is reached? If you try the same test container,  but make it log a bigger log message, does that change what you're seeing?

Is your client also running inside the VM, or is it running on the host, and connecting with the VM over tcp/ip?

/cc @johnstep

**Comment by johnstep** [comment]
I am looking into this now.

**Comment by hongxima** [comment]
We also tried containers with massive logs, it did prove either _time_ or _'log-buffer'_ related. Most of the test cases it just stuck there with the history logs printed.

**Comment by StefanScherer** [comment]
This happens with Windows engine, both locally with Windows Docker client as well as remote Mac Docker client.
And it happens with both `docker container logs -f containerid` and `docker service logs -f servicename`

**Comment by thaJeztah** [comment]
@johnstep were you able to find something?

**Comment by Cisien** [comment]
This happens for me on windows server 2016
```
C:\Windows\system32>docker --version
Docker version 17.03.0-ee-1, build 9094a76

C:\Windows\system32>docker version
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64
 Experimental: false

C:\Windows\system32>docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.0-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.992 GiB
Name: winsrv2016
ID: RDTA:6DP2:6LKS:6A6X:PLHA:AGP6:AJXH:33B6:7DEL:7RQI:R7FV:ZXJP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: cisien
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
ping @johnstep PTAL

**Comment by friism** [comment]
@johnstep @jhowardmsft any news on this?

**Comment by jhowardmsft** [comment]
TBH if it isn't LCOW, everything else is falling behind. I doubt I'd get a chance to look any time soon. Sorry 😕

**Comment by eurythmia** [comment]
confirmed on docker for mac as well:
![screen shot 2017-07-10 at 15 24 52](https://user-images.githubusercontent.com/1179573/28035816-fb301be6-6583-11e7-85f7-09cb7077ac52.png)

**Comment by eurythmia** [comment]
confirmed on Docker for Mac
![screen shot 2017-07-10 at 15 24 52](https://user-images.githubusercontent.com/1179573/28036017-a9538b40-6584-11e7-9093-a96e375fa988.jpg)

**Comment by dariuszparys** [comment]
Is anyone working on this?

**Comment by mnltejaswini** [comment]
I looked into issue to root cause.

The issue is with the Windows [ file caching](https://docs.microsoft.com/en-us/windows/desktop/FileIO/file-caching) where the file data is lazily written to the disk. The docker logs with follow flag is based on a file watcher on the docker log file. As Windows is not committing the bytes to the disk, there is no system notifications for file update and hence the watch signals are not firing at all. I have verified that certain actions like reopening the log file either manually or by issuing docker logs is triggering the writing to disk and fires the watch signal and there by flushes the logs on the follow stream. Other actions that trigger the logs on follow stream are, refresh the explorer of the container folder, opening the log file in the notepad etc.  The file watcher is based on the underlying OS ReadDirectoryChangesW() system call which is some how not detecting the writes to the cache. It is detecting writes to the disk. The same behavior is observed by using the .net class FileSystemWatcher class. 

Some possible options to workaround this issue with Windows are

1. Disable the buffering but not recommended as it increases the I/O pressure
2. We trigger the flush either based on time or size by invoking file.Sync() that forces the writing to disk and thereby detected by the watcher

Any thoughts? @johnstep @thaJeztah

**Comment by cpuguy83** [comment]
Another alternative is to fallback to file polling for Windows.

**Comment by johnstep** [comment]
@mnltejaswini Thanks for looking into this. If we cannot be notified about cached changes, then yes, we should into alternatives. I would lean toward polling/flushing rather than disabling buffering. I'd like to do a few tests first. There is also the change journal for NTFS volumes (https://docs.microsoft.com/en-us/windows/desktop/fileio/change-journal-records), but that is a much more involved solution.

**Comment by johnstep** [comment]
Issue https://github.com/fsnotify/fsnotify/issues/53 discusses adding change journal support.

**Comment by mnltejaswini** [comment]
As a first step we can workaround the issue with flushing or polling so that it unblocks users and then solve it comprehensively using journal support.

**Comment by johnstep** [comment]
Unfortunately, from my quick testing, the change journal is not updated each time the file is modified, so this might not be a viable option. A file system filter driver will work, but is definitely overkill for this.

**Comment by cpuguy83** [comment]
Also thinking that if writes are buffered that polling *may not* help either.

**Comment by mnltejaswini** [comment]
@cpuguy83  if polling is based on opening the file, it will trigger the flush and watch fires.

**Comment by cpuguy83** [comment]
It's just stating the file: https://github.com/moby/moby/blob/master/pkg/filenotify/poller.go#L157

**Comment by mnltejaswini** [comment]
A quick testing with filenotify.NewPollingWatcher() showed that the write events are fired. So this watcher based on polling should work

**Comment by mnltejaswini** [comment]
https://github.com/moby/moby/blob/aba2735e3fe66333ac1064bed3b476f30b1d1c00/daemon/logger/loggerutils/logfile.go#L644 Changing to filenotify.NewPollingWatcher() allowed the logs to follow :) Currently we fallback to polling watcher if fsnotify watcher has errors. Maybe for Windows, we can use polling watcher by default. I can make the change if this is approved

**Comment by PS-StuartZahn** [comment]
Happens on OSX too

**Comment by stephenfriedman** [comment]
Also an issue on OSX. Running Docker for Mac (now called Docker Desktop ?) on hyperkit.
Version 2.0.0.0-mac78 (28905) Engine: 18.09.0
