### ISSUE TITLE
Docker client overwriting non-standard ports in metadata assignment during push operations

### ISSUE THREAD

**Issue by AGloberman** [moby/moby#30086]
When executing a push operation from the command line, the docker client appears to be ignoring the specified non-standard SSL port when pushing to a private registry, causing connection-refused errors when port 443 is not open on target server.

Repro Steps:
1. docker pull hello-world
2. docker tag <ImageId> registry.example.com:32443/hello-world:test
3. docker login registry.example.com:32443 -u <username> -p <password> (SUCCESSFUL)
4. docker push registry.example.com:32443/hello-world:test (ERROR)
5. `curl -u <username>:<password> https://registry.example.com:32443/v2/_catalog` returns the expected response, so I know my private registry is accessible at that endpoint and that the SSL and creds are valid.

Observed: 
First image layers partially push, but failures are observed after a series of retries when uploading layer metadata to private registry: "**dial tcp 1.2.3.4:443: getsockopt: connection refused**".  Note the port is 443, not 32443 as specified during tag/push.

Expected:
Docker client should respect the port value specified in tag/push operations.

Private registry configuration:
Standard registry (v2.3.0) container running in Kubernetes on AWS.  Nginx container (v1.11) in front for routing and SSL termination.  Kubernetes exposes an IP and assigns an externally-facing port from a pre-configured range (1.2.3.4:32443).  For simplicity, we put this IP behind a Route53 record set (registry.example.com), with the hostname matching the SSL certs in the Nginx deployment.  Basic auth on the registry container.

Client Information: 
bash-4.3# docker version                                                                                                                                                                                   
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

bash-4.3# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 77
Server Version: 1.12.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.795 GiB
Name: 0fbdf3820eed
ID: JK6O:BVE4:LVPA:Y7UI:EWWC:T5SG:QCRI:YTL4:PUY5:J673:LQJZ:UE2N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by Jsvcycling** [comment]
Since Docker uses regular expressions to parse the container reference strong, it's very likely that it is parsing the `:` (colon character) separating the hostname and port as the separator between the container name and tag.

See [docker/distribution/reference/regexp.go#65](https://github.com/docker/distribution/blob/master/reference/regexp.go#L65) for the regexp to parse the container reference.

**Comment by thaJeztah** [comment]
the registry should be provided without scheme (`https://`);

```
docker tag <some image> registry.example.com:32443/hello-world:test

docker push registry.example.com:32443/hello-world:test
```

**Comment by AGloberman** [comment]
Thanks for the responses, folks.

@thaJeztah The behavior is the same is when the scheme is omitted, which makes me think that...

@Jsvcycling This might not be the root cause, either.  If so, how does pushing a tagged image to `localhost:5000` work properly?  Heuristically, isn't my example the same as the tag/push of `localhost:5000/hello-world:test`?

**Comment by Jsvcycling** [comment]
@AGloberman you have a point, I'd totally forgotten about that...

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
