### ISSUE TITLE
Feature Request: add `--add-host=[]` option to `docker build` 

### ISSUE THREAD

**Issue by twang2218** [moby/moby#30096]
`docker run` has `--add-host=[]` which is very handy, especially in the network environment without internal DNS. However, `docker build` don't have `--add-host=[]` option.

During the image building process, sometimes, we need to have specific `name`, `ip` mappings. Such as:

* accessing internal Git server via HTTP with internal domain name;
* accessing some websites (such as, GitHub repo) from inside of GFW, which often contaminated certain domain names;
* accessing internal HTTP API server with internal domain name;

There is a workaround by adding `echo 1.2.3.4 >> abc.com /etc/hosts` in the begining of each `RUN` command which has the problems, however it would be handy to have `--add-host=[]` option in the `docker build` command.

Related issues:

* https://github.com/docker/docker/issues/1916#issuecomment-40007129
* https://github.com/docker/docker/issues/2267
* https://github.com/docker/docker/issues/3851
* https://github.com/docker/docker/issues/5779
* https://github.com/docker/docker/issues/7966
* https://github.com/docker/docker/issues/10171
* https://github.com/docker/docker/issues/10324
* https://github.com/docker/docker/issues/24928

**Comment by TDAbboud** [comment]
#dibs

**Comment by TDAbboud** [comment]
#dibs

Question on the implementation:
Should the hosts only be available during build time and not when you do `docker run` after the build?

I have implemented the `--add-host` feature which works when you do the `docker build`, but once you explicitly run the docker image without the --add-host options the hosts are no longer there.

**Comment by cpuguy83** [comment]
@TDAbboud This is expected and desirable. It is a runtime configuration not something to be persisted into an image.

**Comment by TDAbboud** [comment]
okay perfect. Here is an example of the output as well with the Dockerfile I used

![screen shot 2017-01-23 at 11 57 47 am](https://cloud.githubusercontent.com/assets/5448017/22213771/55b95744-e163-11e6-8d6c-ef566be12096.png)

**Comment by tonistiigi** [comment]
Added in #30383 (v17.04+)
