### ISSUE TITLE
Docker api build 1.12.3 error 

### ISSUE THREAD

**Issue by cristhianbicca** [moby/moby#30104]
I'm following the Dockerfile build documentation, but it always returns an error message. It's working?

curl -v -X POST -H "Contet-Type:application/tar" --data-binary '@dockerfile.tar.gz' http://ip:porta/build?t=teste

* About to connect() to IP port 2376 (#0)
*   Trying IP
* Connected to IP (IP) port 2376 (#0)
> POST /build?t=cuuu HTTP/1.1
> User-Agent: curl/7.29.0
> Host: IP:2376
> Accept: */*
> Contet-Type:application/tar
> Content-Length: 313
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 313 out of 313 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Server: Docker/1.12.3 (linux)
< Date: Thu, 12 Jan 2017 18:37:34 GMT
< Content-Length: 61
<
{"message":"Cannot locate specified Dockerfile: Dockerfile"}
* Connection #0 to host IP left intact

**Comment by cpuguy83** [comment]
The error is because the builder could not find `Dockerfile` in the tarball you uploaded.

**Comment by cristhianbicca** [comment]
@cpuguy83  This I understand, but I put all the ways and it did not work.

**Comment by cpuguy83** [comment]
@cristhianbicca What is the content of the tarball?

**Comment by cristhianbicca** [comment]
@cpuguy83  Contains a Dockerfile file with

From centos7
RUN yum install httpd -y
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]


I tried to put the file path also with the dockerfile option of the query parameters for example in: /opt/Dockerfile
But the same error happens

**Comment by cpuguy83** [comment]
@cristhianbicca tarball would need to be a tree with `Dockerfile` at the root.

**Comment by cristhianbicca** [comment]
@cpuguy83  Yes, Dockerfile is the only file inside the correct tar?

**Comment by cpuguy83** [comment]
Also maybe something wrong your header. Not sure if that would cause docker to do something different here.

**Comment by cristhianbicca** [comment]
@cpuguy83 
Is there an example curl I can test that works?

**Comment by cpuguy83** [comment]
@cristhianbicca Try your curl but fix the `-H "Contet-Type:application/tar"` which is incorrect.
`-H 'Content-Type: application/tar'`

**Comment by cristhianbicca** [comment]
@cpuguy83  I'm talking to the dockerfile parameter and not tar

**Comment by cpuguy83** [comment]
@cristhianbicca You'll have to be more specific.

From your original post I see you are trying to post a tarball to the build endpoint which is failing because it can't find a file called `./Dockerfile` in the posted tarball and also your content header is not correctly set.

Please try again with a corrected curl command and let's see the results.

**Comment by thaJeztah** [comment]
Closing this because of age
