### ISSUE TITLE
 Failed to start Docker Application Container Engine.

### ISSUE THREAD

**Issue by cloudscode** [moby/moby#30115]
**Description**
```
[root@localhost ~]# sudo systemctl status docker -l 
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 五 2017-01-13 09:03:51 CST; 4s ago
     Docs: https://docs.docker.com
  Process: 2294 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 2294 (code=exited, status=1/FAILURE)
   Memory: 43.1M
   CGroup: /system.slice/docker.service

1月 13 09:03:50 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:50+08:00" level=warning msg="Running experimental build"
1月 13 09:03:50 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:50.309890829+08:00" level=info msg="libcontainerd: new containerd process, pid: 2297"
1月 13 09:03:51 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:51.364045488+08:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
1月 13 09:03:51 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:51.375563702+08:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
1月 13 09:03:51 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:51.382794876+08:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
1月 13 09:03:51 localhost.localdomain dockerd[2294]: time="2017-01-13T09:03:51.427263746+08:00" level=fatal msg="Error starting daemon: layer does not exist"
1月 13 09:03:51 localhost.localdomain systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
1月 13 09:03:51 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
1月 13 09:03:51 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
1月 13 09:03:51 localhost.localdomain systemd[1]: docker.service failed.

```

**Steps to reproduce the issue:**
1. systemctl start docker.service

**Describe the results you received:**
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:24:00 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox
```
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# uname -r
3.10.0-514.2.2.el7.x86_64
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core) 

```

**Comment by yaozaiyong** [comment]
@cloudscode , as indicated in your message, please using command like below after running "systemctl start docker" to get detailed failure information:
journalctl -f -u docker
 or directly using "dockerd" to start the docker.

**Comment by cloudscode** [comment]
@yaozaiyong  Thanks.
[root@localhost ~]# journalctl -f -u docker
-- Logs begin at 五 2017-01-13 11:52:34 CST. --
1月 13 11:52:53 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:53+08:00" level=warning msg="Running experimental build"
1月 13 11:52:53 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:53.462444614+08:00" level=info msg="libcontainerd: new containerd process, pid: 1919"
1月 13 11:52:56 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:56.226812272+08:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
1月 13 11:52:56 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:56.935559114+08:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
1月 13 11:52:56 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:56.943846213+08:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
1月 13 11:52:57 localhost.localdomain dockerd[921]: time="2017-01-13T11:52:57.820427941+08:00" level=fatal msg="Error starting daemon: layer does not exist"
1月 13 11:52:57 localhost.localdomain systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
1月 13 11:52:57 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
1月 13 11:52:57 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
1月 13 11:52:57 localhost.localdomain systemd[1]: docker.service failed.
[root@localhost ~]# dockerd
WARN[0000] Running experimental build                   
INFO[0000] libcontainerd: new containerd process, pid: 2318 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
WARN[0001] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
WARN[0001] devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored. 
INFO[0001] [graphdriver] using prior storage driver "devicemapper" 
FATA[0001] Error starting daemon: layer does not exist

**Comment by yaozaiyong** [comment]
@cloudscode , the above problem might be similar to this one(https://github.com/docker/docker/issues/20267):
Try using command "dockerd -D" to know more detailed information about which layer not working, then you can try solutions hinted in #20267 to see if it work.

**Comment by cloudscode** [comment]
@yaozaiyong  Thanks again.

**Comment by murthis** [comment]
This issue went off when i was rebooting my machine.

**Comment by ipa-srd-rd** [comment]
I tried removing the docker directory (/var/lib/docker) using this script [https://serverfault.com/questions/780844/cant-start-docker-daemon-invalid-image](url). It initially worked and I was able to build images again. During the build process however I got error message 

<pre>
failed to export image: failed to create image: failed to get layer sha256:df8e04f5dd976ca0d5a09d0bb6515512b2b4ebadb8f454b14
</pre>

After building with `--no-cache` option it worked but after restarting the docker daemon I am now back to the roots:

<pre>
srd-rd@rd-x1y:~$ sudo dockerd
DEBU[2018-03-22T14:24:33.035007216+01:00] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[2018-03-22T14:24:33.035335288+01:00] libcontainerd: started new docker-containerd process  pid=22813
INFO[0000] starting containerd                           module=containerd revision=9b55aab90508bd389d7654c4baf173a981477d55 version=v1.0.1
DEBU[0000] changing OOM score to -500                    module=containerd
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  module=containerd type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...  module=containerd type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...  module=containerd type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...  module=containerd type=io.containerd.runtime.v1
DEBU[0000] loading tasks in namespace                    module="containerd/io.containerd.runtime.v1.linux" namespace=moby
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.introspection"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
INFO[0000] containerd successfully booted in 0.002022s   module=containerd
DEBU[2018-03-22T14:24:33.047870075+01:00] Using default logging driver json-file       
DEBU[2018-03-22T14:24:33.047908023+01:00] Golang's threads limit set to 110970         
DEBU[2018-03-22T14:24:33.050259128+01:00] [graphdriver] trying provided driver: overlay2 
DEBU[2018-03-22T14:24:33.050685767+01:00] processing event stream                       module=libcontainerd namespace=plugins.moby
DEBU[2018-03-22T14:24:33.051487647+01:00] backingFs=extfs,  projectQuotaSupported=false 
DEBU[2018-03-22T14:24:33.051502114+01:00] Using graph driver overlay2                  
DEBU[2018-03-22T14:24:33.053734227+01:00] Max Concurrent Downloads: 3                  
DEBU[2018-03-22T14:24:33.053744443+01:00] Max Concurrent Uploads: 5                    
DEBU[2018-03-22T14:24:33.073383954+01:00] Cleaning up old mountid : start.             
Error starting daemon: layer does not exist
</pre>

**Comment by kalyankalapala** [comment]
Thanks a lot. It really helped to resolve my issue.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
