### ISSUE TITLE
Not able to set priority inside docker container

### ISSUE THREAD

**Issue by paresh-sao** [moby/moby#30122]
I already supplied all the necessary during creating docker container --cap-add=sys_nice --privileged=true but still I am not able to set priority in any process. It's a redhat container.

Output:

[root@739d81f5d72a /]# chrt -r -p 99 1
chrt: failed to set pid 1's policy: Operation not permitted
[root@739d81f5d72a /]#

Docker version:

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
See #23430

I believe this is because `cpu.rt_runtime_us` is not set for your container. This should work in 1.13.
Ping @erikstmartin

**Comment by mistin** [comment]
My host is Redhat 7 Vm and its already have that value, but still is not working.

cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us
950000

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
