### ISSUE TITLE
in macvlan network,inbound connections don't work until ARP cache is updated

### ISSUE THREAD

**Issue by qiankunli** [moby/moby#30238]
environment： 
1. netwok driver ： macvlan
2. ipam driver ： custom implementation  which can allocate ip for container

I started with an static ip `docker run -it --rm --net macvlan96  --ip 172.31.20.101` , and this with an macvlan interface. So the external switch knows the mac from the macvaln interface from the container with the ip in the arp table .
Then the container is destroyed , and then it gets created again(`docker run -it --rm --net macvlan96  --ip 172.31.20.101`), with the same IP, but another MAC. So the mapping MAC <=> ip is no longer valid in the external Switch arp table. The Problem is now that the arp entry had a timeout, and the timeout is long (with cisco per default 4h).

**Comment by gianarb** [comment]
Hello! Can we have more info about your environment?
Can you copy/paste your `docker info` and `docker version` command?
Thanks

**Comment by qiankunli** [comment]
docker info

`Containers: 20
 Running: 2
 Paused: 0
 Stopped: 18
Images: 11
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:4-3342343-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 919.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.5 GB
 Metadata Space Used: 2.576 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host macvlan bridge null overlay
Swarm: active
 NodeID: 728qablmwej04md60qayvfhog
 Is Manager: false
 Node Address: 192.168.60.22
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.52 GiB
Name: test-a2-60-22
ID: T7LX:LJVL:3UFJ:ZFU3:WL2C:7X6R:4MXX:GDJM:HTDR:RFSS:XHF6:ZFFC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 192.168.60.8
 127.0.0.0/8`

**Comment by aboch** [comment]
@qiankunli 
Based on https://github.com/docker/libnetwork/blob/master/drivers/macvlan/macvlan_endpoint.go#L38
the interface's MAC for the same IP address should still be the same.

**Comment by qiankunli** [comment]
in my ipam driver

	func (iph *MyIPAMHandler) GetCapabilities() (response *ipam.CapabilitiesResponse, err error) {
		log.Infof("GetCapabilities")
		return &ipam.CapabilitiesResponse{RequiresMACAddress: true}, nil
	}

RequiresMACAddress is true,so the mac address is exist before querying ip from ipam driver.

RequiresMACAddress may should be false.

**Comment by aboch** [comment]
Ah that explains. 
Then your only option is to specify `--mac-address` when you run the container.

**Comment by aboch** [comment]
@qiankunli Does your IPAM driver really require libnetwork to provide the container's MAC address when it requests for an IP address for the container ?

It does not seem like, given you are manually specifying the IP address of the container.

If it does not require that, then have your IPAM driver return false for that capability and you will get the same MAC address every time you run the container with `--ip` option specified.

If instead you want your driver to manage the MAC to IP mapping, then I would expect you run the container with the `--mac` option only, so that the driver will stick to the same IP for the container with that mac address.

Please let me know if this is still an issue.

**Comment by thaJeztah** [comment]
Closing because this went stale
