### ISSUE TITLE
cp: Copying a directory containing hard links fails if DEST_PATH doesn't exist

### ISSUE THREAD

**Issue by eZanmoto** [moby/moby#30249]
**Description**

`docker cp` fails with `link ...: no such file or directory` if the DEST_PATH argument (second argument, specifying a path on the host) doesn't specify an existing directory and if the source directory contains hard links.

**Steps to reproduce the issue:**
In an empty directory:
1. `docker run --name=test alpine /bin/sh -c "cd /tmp && echo hi > a && ln a b" && docker cp test:/tmp tmp_`

**Describe the results you received:**

    $ docker run --name=test alpine /bin/sh -c "cd /tmp && echo hi > a && ln a b" && docker cp test:/tmp tmp_
    link /home/sean/test/tmp/a /home/sean/test/tmp_/b: no such file or directory
    $ ls -li tmp_
    total 4
    401413 -rw-r--r-- 2 sean sean 3 Jan 18 15:13 a
    $ cat tmp_/*
    hi

**Describe the results you expected:**

    $ docker run --name=test alpine /bin/sh -c "cd /tmp && echo hi > a && ln a b" && docker cp test:/tmp tmp_
    $ ls -li tmp_
    total 8
    401413 -rw-r--r-- 2 sean sean 3 Jan 18 15:13 a
    401413 -rw-r--r-- 2 sean sean 3 Jan 18 15:13 b
    $ cat tmp_/*
    hi
    hi

**Additional information you deem important (e.g. issue happens only occasionally):**
The files seem to get copied correctly if DEST_PATH exists (including when DEST_PATH is `.`) or if the base name of DEST_PATH matches the base name of SRC_PATH.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 3
 Paused: 0
 Stopped: 18
Images: 312
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 287
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: ubuntu-512mb-lon1-01
ID: 6OOY:LXG2:PKSW:7IFZ:IBIE:LPSF:HRLX:RV4B:QDW6:FAHQ:Q6ZN:NKOK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
DigitalOcean Ubuntu 512MB London 1.

**Comment by thaJeztah** [comment]
I think this will be resolved through https://github.com/moby/moby/pull/33956, which is included in the upcoming 17.09 release.

I'll close this issue, but ping me if you're still able to reproduce this on docker 17.09 when it's released

**Comment by likan999** [comment]
I am on 17.09.0-ce-mac35 (19611), and I am still hitting the same problem. How do I work around this problem? Thanks.

**Comment by eZanmoto** [comment]
@likan999 I think the way I worked around it was probably to create the destination directory first, perhaps using a wrapper script.
