### ISSUE TITLE
get the service details that  the starting task belongs to -  from within the task

### ISSUE THREAD

**Issue by krasi-georgiev** [moby/moby#30255]
I couldn't find any documentation about all dns records that can be queried from inside a container so posting my case hoping for a simple solution

trying to improve the percona cluster image 

every starting task needs to know the ip addresses of all existing task in a healthy state and its own ip address for the sync linking

--wsrep_cluster_address="gcomm://$joinNodes" --wsrep_node_address="$myIp" 

my idea is that each starting task queries the dns get this information (form within the task itself)

dig $(hostname)
to get some info about the service name this task belongs to ($serviceName) and the ip address of the network the tasks is attached to ($myIp)

then using the service name I can $joinNodes=dig tasks.$serviceName to get all other running tasks 

one way I managed solve the issue is bind mounting the docker.sock and
getting all info from there using curl and parsing the json using jq, 
but using dns would be a lot cleaner so hoping for some bright ideas :)

percona/percona-docker@105a4b4#diff-2ccb91d8e101f4269c720edffee04bdd

**Comment by krasi-georgiev** [comment]
I found this PR #26331 which is exactly what I need so closing this

**Comment by thaJeztah** [comment]
I think you should be able to work around this for now, by passing the service name to the container as an environment variable, so that it can be used for the `dig tasks.<servicename>` lookup

@mavenugo do you think we need a "special" way to look up tasks for the same service that the task is part of? `dig tasks.<some-special-name>`

**Comment by thaJeztah** [comment]
@krasi-georgiev let me reopen this issue for a bit; while an introspection API can certainly be used for this, it may also be a "heavy weight" solution for service discovery
