### ISSUE TITLE
Loose stat after reboot on live-restore mode

### ISSUE THREAD

**Issue by sebglon** [moby/moby#30274]
**Description**
It seems related to the option "live-restore": true,
When i restart docker daemon, containers are not restarted and then when i try a docker stats on one of my running conatiner, there is no metrics :
CONTAINER CPU % MEM USAGE / LIMIT MEM % NET I/O BLOCK I/O PIDS
infra_consul_static_1 -- -- / -- -- -- / -- -- / -- --
after restart of the container i got my metrics back:
CONTAINER CPU % MEM USAGE / LIMIT MEM % NET I/O BLOCK I/O PIDS
infra_consul_static_1 0.00% 10.81 MiB / 3.86 GiB 0.27% 17.8 kB / 8.624 kB 7.401 MB / 16.38 kB 0

**Steps to reproduce the issue:**
1. add live-restore=on daemon.json
2. systemctl start docker
3.  docker run --name httpd -d httpd && docker stats httpd => all is OK
4. systemctl restart docker
5. docker stats httpd => No data received

And on docker log, i can see

Got lots of lines like this one on 1.12.5 on centos7 (and 1.12.6) :
docker: time="2017-01-18T16:04:28.671968138+01:00" level=error msg="collecting stats for httpd: sandbox httpd not found"

**Comment by gianarb** [comment]
Hello @sebglon! Thanks for your report.
Can you paste here your `docker info` and `docker version` output?
We had before some similar issue and it can be also a kernel compatibility problem https://github.com/docker/docker/issues/28373

**Comment by sebglon** [comment]
[root@t-vscloud-swarm-cluster-node0 centos]# docker info
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.955 GB
 Data Space Total: 20.4 GB
 Data Space Available: 16.44 GB
 Metadata Space Used: 1.524 MB
 Metadata Space Total: 213.9 MB
 Metadata Space Available: 212.4 MB
 Thin Pool Minimum Free Space: 2.039 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local flocker
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: t-vscloud-swarm-cluster-node0
ID: VNHI:YRMO:6CLK:5MCD:I4YO:I6H2:FMEV:GWAR:HBOZ:C6HN:UIGI:QAYF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 53
 Goroutines: 110
 System Time: 2017-01-19T14:16:56.41534987+01:00
 EventsListeners: 2
Http Proxy: arborea-vip01.socrate.vsct.fr:3128
Https Proxy: arborea-vip01.socrate.vsct.fr:3128
No Proxy: localhost,127.0.0.1,169.254.169.254,*.socrate.vsct.fr,socrate.vsct.fr,kina-vip02,kina-vip02.socrate.vsct.fr,nexus,nfsostackt2,10.98.81.132,10.207.126.15,169.254.169.254,192.168.0.18,192.168.0.18,10.207.16.11,10.207.20.41,t-vscloud-swarm-cluster-node0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 stack_id=5b2dba6d-9cc6-4769-a2fb-2a628bbebb09
Cluster Store: consul://10.207.16.11:8500/t-vscloud/swarm_cluster
Cluster Advertise: 192.168.0.18:2375
Insecure Registries:
 127.0.0.0/8





[root@t-vscloud-swarm-cluster-node0 centos]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**Comment by gianarb** [comment]
@runcom can you have a look? It seems very similar this one https://github.com/docker/docker/issues/28373 Same kernel version too

**Comment by runcom** [comment]
> docker: time="2017-01-18T16:04:28.671968138+01:00" level=error msg="collecting stats for httpd: sandbox httpd not found"

This seems related to network @mavenugo ?

**Comment by aboch** [comment]
I will take a look.

**Comment by aboch** [comment]
@sebglon Are you sure the live restore is in place ?
I see from the docker info you posted, that you are running the daemon with the `--cluster-store` option.
In this case, if `--live-restore` was also specified, the daemon would fail to start with

`FATA[0002] Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode 
`

My guess is that the `--live-restore` option was not read at boot, and the `httpd` container is not actually running after daemon service restart.

**Comment by aboch** [comment]
I have not been able to reproduce this.

One reason for this to happen would that the existing active container's sandboxID somehow was not passed to the network controller creation (https://github.com/docker/docker/blob/1.12.x/daemon/daemon.go#L223), therefore the running container's network sandbox got cleaned up during the network controller initialization 
(https://github.com/docker/docker/blob/1.12.x/vendor/src/github.com/docker/libnetwork/controller.go#L222)

We have seen a couple of reports where this has happened.

If you can consistently reproduce (and set the daemon logs to debug level, `-D`), the logs would clarify if you are hitting the same issue.

**Comment by sebglon** [comment]
**New Test on new machine:**

[root@t-dev-heat-swarm-cluster-node0 centos]# docker run --name httpd -d httpd && docker stats httpd
Unable to find image 'httpd:latest' locally
latest: Pulling from library/httpd
5040bd298390: Pull complete
63408554ba61: Pull complete
4dfe9ef0af52: Pull complete
84871cd4d3da: Pull complete
b376204f8aa6: Pull complete
2a8d452c2c14: Pull complete
7cfa9c4a8891: Pull complete
Digest: sha256:1407eb0941b010035f86dfe8b7339c4dd4153e2f7b855ccc67dc0494e9f2756c
Status: Downloaded newer image for httpd:latest
a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613
CONTAINER           CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
httpd               0.12%               13.32 MiB / 3.86 GiB   0.34%               3.092 kB / 568 B    5.711 MB / 0 B      0
CONTAINER           CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
httpd               0.13%               13.32 MiB / 3.86 GiB   0.34%               3.252 kB / 658 B    5.711 MB / 0 B      0
CONTAINER           CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
httpd               0.13%               13.32 MiB / 3.86 GiB   0.34%               3.252 kB / 658 B    5.711 MB / 0 B      0
CONTAINER           CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
httpd               0.17%               13.32 MiB / 3.86 GiB   0.34%               3.342 kB / 658 B    5.711 MB / 0 B      0
CONTAINER           CPU %               MEM USAGE / LIMIT      MEM %               NET I/O             BLOCK I/O           PIDS
httpd               0.17%               13.32 MiB / 3.86 GiB   0.34%               3.342 kB / 658 B    5.711 MB / 0 B      0
^C
[root@t-dev-heat-swarm-cluster-node0 centos]# systemctl restart docker
[root@t-dev-heat-swarm-cluster-node0 centos]# docker stats httpd
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
httpd               --                  -- / --             --                  -- / --             -- / --             --
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
httpd               --                  -- / --             --                  -- / --             -- / --             --
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
httpd               --                  -- / --             --                  -- / --             -- / --             --
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
httpd               --                  -- / --             --                  -- / --             -- / --             --
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
httpd               --                  -- / --             --                  -- / --             -- / --             --
^C
[root@t-dev-heat-swarm-cluster-node0 centos]#


**Build  info:**
[docker.txt](https://github.com/docker/docker/files/719231/docker.txt)
[root@t-dev-heat-swarm-cluster-node0 centos]# docker info
Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 4.1 GB
 Data Space Total: 20.4 GB
 Data Space Available: 16.3 GB
 Metadata Space Used: 1.499 MB
 Metadata Space Total: 213.9 MB
 Metadata Space Available: 212.4 MB
 Thin Pool Minimum Free Space: 2.039 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local flocker
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: t-dev-heat-swarm-cluster-node0
ID: XA3Q:WXKO:5NNF:QWR5:O5QD:4UTK:IPHV:GU2E:4P4V:MGXR:2HG6:TQPL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 84
 Goroutines: 102
 System Time: 2017-01-20T12:20:42.023980232+01:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 stack_id=1a2d9941-7ba2-4a38-be36-2d66651e1ea6
Cluster Store: consul://10.207.16.11:8500/t-dev-heat/swarm_cluster
Cluster Advertise: 192.168.0.204:2375
Insecure Registries:
 127.0.0.0/8


**Docker version:**
[root@t-dev-heat-swarm-cluster-node0 centos]# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Comment by sebglon** [comment]
[docker.txt](https://github.com/docker/docker/files/719234/docker.txt)

**Comment by thaJeztah** [comment]
Relevant part looks to be this;

```
Jan 20 12:19:54 host-192-168-0-204 docker: time="2017-01-20T12:19:54.498634360+01:00" level=debug msg="Calling GET /v1.24/containers/httpd/stats?stream=1"
Jan 20 12:19:55 host-192-168-0-204 docker: time="2017-01-20T12:19:55.427460391+01:00" level=error msg="collecting stats for a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613: sandbox 21e5178d25fc9a5352cbe4f5784a32bd016585f1128d913525fc1a2f4ad59f29 not found"
Jan 20 12:19:56 host-192-168-0-204 docker: time="2017-01-20T12:19:56.428934648+01:00" level=error msg="collecting stats for a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613: sandbox 21e5178d25fc9a5352cbe4f5784a32bd016585f1128d913525fc1a2f4ad59f29 not found"
Jan 20 12:19:57 host-192-168-0-204 docker: time="2017-01-20T12:19:57.422206409+01:00" level=error msg="collecting stats for a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613: sandbox 21e5178d25fc9a5352cbe4f5784a32bd016585f1128d913525fc1a2f4ad59f29 not found"
Jan 20 12:19:58 host-192-168-0-204 docker: time="2017-01-20T12:19:58.423077881+01:00" level=error msg="collecting stats for a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613: sandbox 21e5178d25fc9a5352cbe4f5784a32bd016585f1128d913525fc1a2f4ad59f29 not found"
```

I also see a lot of requests to the v1.15 API; do you have something else running on the host that's polling the API? (should probably not be relevant, just wondering)

**Comment by sebglon** [comment]
**At the same time i have an error on docker exec -it httpd bash:**

[root@t-dev-heat-swarm-cluster-node0 centos]# docker exec -it httpd bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"

**with this error on log:** 
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.175857051+01:00" level=debug msg="Calling POST /v1.24/containers/httpd/exec"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.176019447+01:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"bash\"],\"Detach\":false,\"DetachKeys\":\"\",\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.177135874+01:00" level=debug msg="Calling POST /v1.24/exec/20c7afa40e586c671aecb4ebbacea47b991bf4c3baafae725d1e8ac4be3d4139/start"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.177259592+01:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"bash\"],\"Detach\":false,\"DetachKeys\":\"\",\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.177406455+01:00" level=debug msg="starting exec command 20c7afa40e586c671aecb4ebbacea47b991bf4c3baafae725d1e8ac4be3d4139 in container a3c096bb847cd436d08ec748048e4115e8c29b68accf9536adcd56b040885613"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.181795832+01:00" level=debug msg="attach: stdin: begin"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.181927820+01:00" level=debug msg="attach: stdout: begin"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.186156381+01:00" level=debug msg="Calling POST /v1.24/exec/20c7afa40e586c671aecb4ebbacea47b991bf4c3baafae725d1e8ac4be3d4139/resize?h=55&w=234"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.236648015+01:00" level=error msg="Error running exec in container: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\"process_linux.go:75: starting setns process caused \\\\\\\"fork/exec /proc/self/exe: no such file or directory\\\\\\\"\\\"\\n\""
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.236744278+01:00" level=debug msg="Closing buffered stdin pipe"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.236840502+01:00" level=debug msg="attach: stdin: end"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.236860341+01:00" level=debug msg="attach: stdout: end"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.237398607+01:00" level=error msg="Handler for POST /v1.24/exec/20c7afa40e586c671aecb4ebbacea47b991bf4c3baafae725d1e8ac4be3d4139/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"
Jan 20 14:00:38 host-192-168-0-204 docker: time="2017-01-20T14:00:38.241989953+01:00" level=debug msg="Calling GET /v1.24/exec/20c7afa40e586c671aecb4ebbacea47b991bf4c3baafae725d1e8ac4be3d4139/json"

**Comment by sebglon** [comment]
Workaroud to have new acces on exec:
docker stop httpd
systemctl restart docker
docker start httpd
and now docker exec -it httpd bash WORK

**Comment by aboch** [comment]
Thanks @sebglon for the logs.
This is the culprit:

```
Jan 20 12:19:40 host-192-168-0-204 docker: time="2017-01-20T12:19:40.014232241+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox 21e5178: failed to create a netlink handle: failed to set into network namespace 24 while creating netlink socket: invalid argument"
Jan 20 12:19:40 host-192-168-0-204 docker: time="2017-01-20T12:19:40.019589895+01:00" level=info msg="Removing stale endpoint httpd (bfc0e3481695cbcba1e6180168cffae86248e7168af6e371da4609b5ff50c407)"
Jan 20 12:19:40 host-192-168-0-204 docker: time="2017-01-20T12:19:40.081698616+01:00" level=debug msg="Releasing addresses for endpoint httpd's interface on network bridge"
Jan 20 12:19:40 host-192-168-0-204 docker: time="2017-01-20T12:19:40.081753581+01:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Jan 20 12:19:40 host-192-168-0-204 docker: time="2017-01-20T12:19:40.106446762+01:00" level=info msg="Fixing inconsistent endpoint_cnt for network bridge. Expected=0, Actual=1"
``` 

I will look into it

**Comment by sebglon** [comment]
Have you find any solution to solve this?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
