### ISSUE TITLE
Unable to scale Golang server app on docker host beyond 120 containers - Error too many open files

### ISSUE THREAD

**Issue by subbu05** [moby/moby#30287]
CentOS Linux release 7.2.1511 (Core) 64 bit

docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
 

ulimit  -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15014
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 840000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 840000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

cat /proc/811/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       15014                15014                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

Details
1.We have golang app server wanted to scale on a single docker host
2.Using a script tried to run 200 containers 
#!/bin/perl
$i=$ARGV[0];
$port=10001;
for($j=1;$j<=$i;$j++){
   `docker run  -d  --name "app"$port  -p $port:8080 go-app`;
    `sleep 1`;
   $port+=1;
}
3.After containers are launched unable to send requests 121st container.
4.I see in the container logs - too many files error
5.Tried comparing open files before and after each container spawn - I see ~2500 files are opened per container, most of the open files are FIFI, a_inode.

Possibly open file leak exists - docker daemon.

**Comment by subbu05** [comment]
I was able to modify the ulimits for docker daemon, inspite I see issues:
cat /proc/3673/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    0                    bytes
Max resident set          unlimited            unlimited            bytes
Max processes             840000               840000               processes
Max open files            900000               900000               files
Max locked memory         524288               524288               bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       15014                15014                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us


After debugging for a while I suspect issue with OS. when the issue occurred I was unable to stop other services. Complains too many open files.

**Comment by ijrandom** [comment]
How much descriptors are consumer by dockerd?
```sudo ls /proc/$(pidof dockerd)/fd | wc -l```

**Comment by subbu05** [comment]
Process ID of the dockerd  - 31550
ls /proc/31550/fd|wc -l
739

cat /proc/sys/fs/file-nr
7136	0	500000

lsof|wc -l
390154

lsof includes duplicates, hence we cannot count for.

I changed the docker service settings 
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target firewalld.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=900000
LimitNPROC=900000
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target



Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             900000               900000               processes
Max open files            900000               900000               files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       15005                15005                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

**Comment by ijrandom** [comment]
Does not look like a docker issue. 739 per 120 containers looks pretty normal. As well as total number of open files per system. lsof show resources per thread so counting total lines in lsof output is useless.

There is no go-app in public repo so I can't check this on my computer.

**Comment by subbu05** [comment]
Yes,lsof doesn't make sense ( I mentioned above ). We can find max open files using -  /proc/sys/fs/file-nr.  We were able to deploy multiple Nginx containers and go beyond 500+. 

We tried on CoreOS and Centos , same issue. I am facing issues pushing go-app to docker hub, once issue resolved I will push go-app for further debugging.

**Comment by subbu05** [comment]
We resolved it by changing increasing 
sysctl -w fs.inotify.max_user_instances = 5000
