### ISSUE TITLE
swarm mode and overlay networks issues

### ISSUE THREAD

**Issue by Riziero** [moby/moby#30288]
Hello,

I am creating a swarm cluster and then an overlay network which I am then using to spin up services. It appears that by trying to constraint a service to run on a specific node (--constraint node.hostname==node3) then the overlay network does not work.

As in I can not ping a service by its name from other services in the same network.
As soon as I get rid of the node contraint everything goes back to being pingable again.

Anyone have any clue about this?

Thanks!

**Comment by gianarb** [comment]
Hello @Riziero can you copy paste your docker info and docker version output?
Thanks

**Comment by aboch** [comment]
@Riziero In addition to what @gianarb already asked, please also add the info about how many managers/workers,  the service creation command you are using, the network creation command, and any suspicious docker daemon warn/err logs if any. Thanks.

**Comment by Riziero** [comment]
@gianarb @aboch here's some more info.

I have 1 leader and 2 worker nodes:

`$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
6pth9qm7d82j2324oqpd3cif9    node3     Ready   Active
990z5o48vtsrfgrqfao6b3vjp    node2     Ready   Active
bpu3bwt85gon8sn0say2tcqgz *  node1     Ready   Active        Leader`

Docker info from node2:

`$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 990z5o48vtsrfgrqfao6b3vjp
 Is Manager: false
 Node Address: 172.28.128.6
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: node2
ID: TQ74:V2AL:7IKR:IYXW:V5HW:UUWE:BXW7:HL7E:3WQQ:LVDI:CXYP:E762
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
`

Docker version from inside the nodes:

vagrant@node2:/buildbot$ docker -v
Docker version 1.12.6, build 78d1802

Now what I am using to service2 on node2 and service3 on node 3:
`docker service create \
--network foo \
--name postgres2 \
--constraint node.hostname==node2 \
postgres:9.5`

docher ssh node2
docker exec -i -t ID_OF_THE_CONTAINER_FOR_SERVICE_2 bash
ping postgres3

gives:

`root@f93d8621a144:/# ping postgres3
PING postgres3 (10.0.4.5): 56 data bytes
92 bytes from f93d8621a144 (10.0.4.4): Destination Host Unreachable
92 bytes from f93d8621a144 (10.0.4.4): Destination Host Unreachable
92 bytes from f93d8621a144 (10.0.4.4): Destination Host Unreachable
`
Note how something strange happens with IP, going from .5 to .4

Thanks!

**Comment by Riziero** [comment]
Hope this can help a bit.

Same exact test on trusty64 works well. The fail was with wily.

**Comment by hezor** [comment]
I have this exact same problem with Docker Swarm (1.12.6 running on three CentOS 7.3 Swarm Nodes). So @Riziero did you get this solved?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
