### ISSUE TITLE
weird volume behavior after updating to docker 1.13

### ISSUE THREAD

**Issue by louissalin** [moby/moby#30298]
We had docker auto-updated last night without our knowledge (we didn't know yum-cron was a thing...) and seemingly lost production data stored in docker volumes after restarting our containers. We went from docker 1.10 to 1.13. We assume the docker daemon was running while the update was going on.

I say "seemingly" because the data was still inside the [docker path]/volumes/[vol name]/_data directory but wouldn't show up inside a container after mounting the volume.

I thought it may initially be related to https://github.com/docker/docker/issues/20079, but I was asked to create a new issue.

We inspected one of the volumes and we saw this:

```
$ docker volume inspect pipeline-data
[
    {
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/\"/mnt/disks/data/docker\"/volumes/pipeline-data/_data",
        "Name": "pipeline-data",
        "Options": {},
        "Scope": "local"
    }
]
```

The quotes in the mount point seemed weird to us, so we tried to list the content of the directory with and without the quotes (with customer name removed):

```
$ ls /\"/mnt/disks/data/docker\"/volumes/pipeline-data/_data
<customer> <customer>_historical
```

```
$ ls /mnt/disks/data/docker/volumes/pipeline-data/_data
asset.json  drop.sql  <customer> <customer>_historical
```

Our old data is in the directory without the escaped double quotes.
We found a workaround by mapping the full pathname to a container path instead of using a volume name, so this is not urgent but it did give us somewhat of a scare this morning. It is also unclear to us how to reproduce this issue.

Please let me know if you need any additional details. We'll do our best to provide them to you.

Thanks!

**Comment by thaJeztah** [comment]
Can you tell how you configured the daemon (e.g. through a systemd unit file, or drop-in file)?

I may have a clue; if the graph-dir is specified with quotes, specifying it inside a Environment-variable or inside the systemd unit file may result in the quotes not being stripped (which is usually handled by the shell).  (see https://github.com/docker/docker/issues/29761)

It looks like the volumes were re-created after upgrading, and a path _including_ the quotes was used. You can try updating your configuration (removing the quotes), and restarting the daemon

**Comment by louissalin** [comment]
yep, there are quotes!

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --graph="/mnt/disks/data/docker" --storage-driver=overlay
```

**Comment by louissalin** [comment]
for the sake of completeness, this is where I learned to set up docker with systemd: https://docs.docker.com/engine/admin/systemd/

The docs include quotes for the graph-dir.

**Comment by thaJeztah** [comment]
Thanks for that! I think that example relied on an old behavior, so should be updated. On the command-line that should be fine (the shell handles quotes there), but in a unit-file that's not the case. I'll get that fixed 👍

**Comment by wrsuarez** [comment]
This bit us as well too. We also followed the Docker documentation and had double quotes around the path in the graph setting for systemd. Just basically killed Docker across all of our clusters following the update. We just pulled the double quotes from the docker systemd file and restarted docker and its working fine but definitely not a happy day for our end users

**Comment by thaJeztah** [comment]
Looks like the incorrect documentation was fixed in https://github.com/docker/docker.github.io/pull/1185

**Comment by jeffbonhag** [comment]
Thanks, this got us, too:

    ExecStart=/usr/bin/dockerd --graph="/data/docker"

We moved the graph setting out of the service definition and into `/etc/docker/daemon.json`

    {
        "graph": "/data/docker"
    }

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
