### ISSUE TITLE
Log tags documentation is out of date

### ISSUE THREAD

**Issue by asilversempirical** [moby/moby#30324]
'docker/' is no longer automatically added as a prefix (after https://github.com/docker/docker/pull/22384), but https://docs.docker.com/engine/admin/logging/log_tags/ still prepends 'docker/'. That log-opt tag would no longer result in the example log line. It would be missing the 'docker/' prefix.

**Comment by cthomas15** [comment]
Does this just involved removing 'docker/' from the code examples?

**Comment by asilversempirical** [comment]
I think so, but I wasn't confident enough in validating the example and didn't want to send a PR that makes things worse.

I also wasn't 100% sure the change was permanent (it actually broke us when it landed so I was worried it might get reverted if others complained).

**Comment by thaJeztah** [comment]
It won't be reverted, so it's safe to update the examples.

The `docker/` (or `dockerd/`, as it depends on the binary name) prefix is still used by default, but is now a separate formatting option for the tag, so if you need the prefix, it's possible by adapting the tag format accordingly

**Comment by asilversempirical** [comment]
Update in https://github.com/docker/docker.github.io/pull/4157

**Comment by thaJeztah** [comment]
Thanks!
