### ISSUE TITLE
docker import -c is broken

### ISSUE THREAD

**Issue by sjlongland** [moby/moby#30339]
**Description**

Docker documentation states that the `docker import` command accepts `Dockerfile` commands as arguments to be applied to a newly imported image.

```
--change, -c 	  	Apply Dockerfile instruction to the created image
```
https://docs.docker.com/engine/reference/commandline/import/

Looking at the `Dockerfile` reference, I see that `RUN` is one such command:
https://docs.docker.com/engine/reference/builder/#/run

… but combining the two does not work:

```
RC=0 stuartl@beast ~/projects/home-docker/base $ docker import -c "RUN sed -i -e 's/#rc_sys=\"\"/rc_sys=\"docker\"/g' /etc/rc.conf && echo UTC > /etc/timezone" /var/tmp/catalyst/builds/hardened/stage3-amd64-20170121.tar.bz2 localhost:65000/base:20170121
Error response from daemon: run is not a valid change command
```

Apparently not valid, yet it is documented as a change command in the `Dockerfile` reference, and works fine when used in a `Dockerfile` as part of a `docker build`.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.7.1
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.7.1
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-301999999-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 71.58 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.8.2-beast-dirty
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.781 GiB
Name: beast
ID: 4QZ3:4AAD:2H47:GR7W:TG24:TSWD:O3KS:4PCB:6OXZ:5USG:ENHA:MJJ2
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Host is running Gentoo Linux/AMD64 (hardened), Docker installed via ebuild script.

**Comment by thaJeztah** [comment]
This is the expected behavior; it's only possible to update certain parts of the image's "configuration".  The `RUN` instruction is not supported for this, because `RUN` requires a _new_ container to be started for the command to run in. You can achieve the same by using `docker exec` into the container, and running the `sed` manually.

The command line reference in this repository describes this; https://github.com/docker/docker/blob/master/docs/reference/commandline/import.md

However, it looks like that document is not properly published on docs.docker.com; could you open an issue for that in the docs issue tracker? https://github.com/docker/docker.github.io/issues/new

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
