### ISSUE TITLE
Dockerd do not respect log level settings other than `debug`. 

### ISSUE THREAD

**Issue by stuszynski** [moby/moby#30349]
**Description**

**Steps to reproduce the issue:**
1. Set an `log-level` flag to `error`

```
/usr/local/bin/dockerd --log-level error
```

**Describe the results you received:**

Docker still logging from `info`, and `warning` level: 

```
dockerd[22069]: time="2017-01-22T10:22:13.992707846Z" level=info msg="containerd: e352ec85603a5d20c1e58281e4410756a1a51f7a02831532f5ee6ab29fc18367:8c629e553eb27e7b31437b323d2c01098aad43bb961bd33341ff5ce09ce0c475 (pid 29975) has become an orphan, killing it"
dockerd[22069]: time="2017-01-22T10:22:14.02387473Z" level=warning msg="containerd: unable to save 05bd1daf367d772b2c7fb0ec4f27cb744f6e7d3585e20e3a7b188bf96d6cdf77:a710333e98141f486172b603df948a2c049e2173afe8220d8521b71b18e3986e starttime: open /proc/29997/stat: no such file or directory"
```

**Describe the results you expected:**

No `info` nor `warning` level in logs. 

Docker logging a lot of entries on `info` and `warning` log level multiplied by a number of machines. This produces a lot of noise in our log aggregation system. We want to cut it out on production. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I also checked this  on `fatal` with no effect, but `debug` works as it intended (unlocks `level=debug` in logs).

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 42
 Running: 20
 Paused: 0
 Stopped: 22
Images: 14
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: <node-name>
ID: <id>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 instance, Kubernetes cluster.

**Comment by dnephin** [comment]
I just tried this with 1.13.

The `--log-level` flag correctly sets the log level for `dockerd`, but I guess it doesn't pass the log level along to `containerd`.  I believe the log lines you're seeing are coming from  `containerd`, they just happen to look the same.

It looks like the `containerd` 0.2.3 (which is included with docker 1.13) does not have a `--log-level` flag, so that will have to be added first.

**Comment by mlaventure** [comment]
@dnephin is correct, `containerd` only support `debug` level or the `logrus` default (which is `Info`). We'll have to add a new flag in.

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
Seems not find incorrect code?
https://github.com/docker/docker/blob/8e64ca31f2822eb5d11e4b14de59ed3555ef21a1/cli/flags/common.go#L109

**Comment by jmzwcn** [comment]
hmm, containerD...

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and containerd defaults to running as it's own service now (and own config)
