### ISSUE TITLE
Wi-Fi on host machine became inaccessible after package docker-engine was installed and even after removing it 

### ISSUE THREAD

**Issue by ant1ucem** [moby/moby#30343]
**Description**
I have installed latest docker-engine package on my laptop with Kubuntu 16.10 via
 `deb https://apt.dockerproject.org/repo/ ubuntu-xenial main `
On docker installation something happens with networking stuff of my system. After restart Wi-Fi connection grayed in network manager like wifi adapter is not visible anymore and I unable to connect to it. Instead I see running connection named "docker0", but my internet is not working. I still can access the internet via USB modem or USB Ethernet adapter.

Also I noticed network works again after I completely delete all networking stuff from my computer (service network, package network-manager and so on) and reinstall it from offline repository (without installing docker ofcourse). This was year ago with Kubuntu 15.04. Today the same situation, but I have no offline repository. Help me please, maybe by telling me what happens with networking during docker installation.

**Steps to reproduce the issue:**
1. Install latest docker on Kubuntu 16.10 (or older 15.04)
2. Reboot
3. Remove docker or not, `sudo apt purge docker` if you want 

**Describe the results you received:**
Wi-Fi disappeared from network manager and I lost my internet

**Describe the results you expected:**
Installing docker should not force me buying Ethernet USB adapter to get access to the internet

**Output of `docker version`:**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: ant1ucem-Lenovo-IdeaPad-Yoga-13
ID: 6266:D6RS:BCDR:7OXF:4H2J:MH2L:S5VV:2JZD:XOML:KHGX:EM6Q:R5R4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by joaocc** [comment]
Have the same problem with Lubuntu 16.10 freshly installed + docker 1.13 (installed as per https://docs.docker.com/engine/installation/linux/ubuntu/).

**Comment by cpuguy83** [comment]
ping @aboch, PTAL

**Comment by aboch** [comment]
Is your wi-fi interface up, do you see it in `ip link` output ?
Probably ubuntu network manager decides to manage the newly added `docker0` and brings down the wifi  one. After fresh machine boot, check `service network-manager status` logs for any clue.

**Comment by joaocc** [comment]
@abock: I will try to check it today. 
Also, this seems to be related to https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1458322

**Comment by joaocc** [comment]
```ip link``` lists
* lo (link/loopback)
* enp7s11 (link/ether)
* docker0 (link/ether)
(difficult to past all details because machine lost network connectivity)

However, after rebooting (as suggested in another page) the wifi adapter is now visible, and I now have
* lo (link/loopback)
* enp7s11 (link/ether)
* wl35 (link/ether)
* docker0 (link/ether)

So, i'm sorry on not being able to provide more details, but it seems that (yet) another reboot solved it.

**Comment by mattrixman** [comment]
Not sure if this is related, but I found that network-manager (in ubuntu) misbehaves when it tries to manage the `docker0` interface.  

If this is related, one workaround is to prevent network-manager from managing `docker0`, which you can do by modifying `/etc/NetworkManager/NetworkManager.conf` like so: https://gist.github.com/lanrat/458066dbdeb460b9cef40dc2af639a24

**Comment by Hronom** [comment]
Still have this bug when I do docker-compose up -d my network connection is restarted or something similar because it breaks internet connection.

**Comment by altanai** [comment]
I came across this thread while looking to solve the exact same problem and it was the docker0 bridge that didn't go away even after purging docker on ubuntu, so the solution that worked was to purge the docker0 bridge `ip link del docker0`

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
