### ISSUE TITLE
container is already exists

### ISSUE THREAD

**Issue by yunghoy** [moby/moby#30359]
v 1.13.0

After several stopping, removing and creating the same image to container, the container shows the status of it is "Created." And it shows "the container is already exists" in the error section of inspection.

**Comment by thaJeztah** [comment]
Could you please provide more information, as there's not information to look into this. `the container is already exists` indicates that a container with the given name already exists; if you created a container with the same name before, are you sure you _removed_ that container before starting the next one?

How are you starting the container, and removing the previous one? Do you use a script?

**Comment by yunghoy** [comment]
$ docker ps -a | grep log
ef0a2d0f26eb        **********                        "bash -c 'sleep 10..."   19 seconds ago      Created                                                                                                                          dl_log_1

$ docker rm -f dl_log_1
dl_log_1

$ docker ps -a | grep log
none

$ docker-compose up -d --no-recreate
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

WARNING: Found orphan containers (**********) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating dl_log_1

ERROR: for log  Cannot start service log: service endpoint with name dl_log_1 already exists
ERROR: Encountered errors while bringing up the project.

**Comment by yunghoy** [comment]
// Docker Version
Client:
Version: 1.13.0
API version: 1.25
Go version: go1.7.3
Git commit: 49bf474
Built: Tue Jan 17 09:50:17 2017
OS/Arch: linux/amd64

Server:
Version: 1.13.0
API version: 1.25 (minimum version 1.12)
Go version: go1.7.3
Git commit: 49bf474
Built: Tue Jan 17 09:50:17 2017
OS/Arch: linux/amd64
Experimental: false

// Docker Info
Containers: 46
Running: 45
Paused: 0
Stopped: 1
Images: 415
Server Version: 1.13.0
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 4802
Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: active
NodeID: ********************************************
Is Manager: true
ClusterID: ********************************************
Managers: 5
Nodes: 10
Orchestration:
Task History Retention Limit: 5
Raft:
Snapshot Interval: 10000
Number of Old Snapshots to Retain: 0
Heartbeat Tick: 1
Election Tick: 3
Dispatcher:
Heartbeat Period: 5 seconds
CA Configuration:
Expiry Duration: 3 months
Node Address: ********************************************
Manager Addresses:
********************************************:2377
********************************************:2377
********************************************:2377
********************************************:2377
********************************************:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
apparmor
Kernel Version: 3.13.0-107-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67 GiB
Name: ********************************************
ID: ********************************************
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
Could you check if the daemon logs show anything useful? The "endpoint with name xyz already exists" looks similar to https://github.com/docker/docker/issues/20398

ping @mavenugo

**Comment by westsouthnight** [comment]
Have same issue on latest Ubuntu & Latest Docker 1.13.0

``` root@06-host:/home/westsouthnight# docker ps -a | grep fluentd-develop-10.10.100.6
a04ef794c53e        fluentd-local-develop                          "/bin/sh -c 'exec ..."   7 minutes ago       Created                                                             fluentd-develop-10.10.100.6  ```

```

Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 41
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 286
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.25 GiB
Name: 06-tier
ID: K3F6:B7IL:E5E4:O5C5:CRFQ:MAOZ:AX6T:QMRE:QPMI:WFLJ:ILBK:TEQI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: devevote
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
closing because this went stale, and more information and a reproducible case would definitely be needed to determine if there's a bug at hand and to work on
