### ISSUE TITLE
bind error. port is already in use

### ISSUE THREAD

**Issue by yunghoy** [moby/moby#30358]
This is a crazy bug.
After upgrading docker 1.12.6 to 1.13.0, I got the next errors when I launching docker images.

```
$ docker -v
Docker version 1.13.0, build 49bf474
$ docker-compose -v
docker-compose version 1.10.0, build 4bd6f1a
```

```
$ sudo netstat -natop | grep 6379
tcp6 0 0 :::6379 :::* LISTEN 696/dockerd off (0.00/0/0)
```

```
$ docker service ls
ID NAME MODE REPLICAS IMAGE
$ docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
```

```
$ docker-compose -f dc-extern.yml up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use docker stack deploy.

Creating network "dl_default" with the default driver
Creating dl_redis_1

ERROR: for redis Cannot start service redis: driver failed programming external connectivity on endpoint dl_redis_1 (5726fd29068d284e2fe1d0041d12043e6862a1baf8b4e0c33a882dfe47e77121): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in us
```

```
==> The port is also bind in another nodes shared by swarm mode in the cluster.
Restarting linux machine and dockerd gives nothing.
```

**Comment by thaJeztah** [comment]
Could you provide the information that was requested in the issue template as well? At least the full output of `docker version` and `docker info` (https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md)

**Comment by yunghoy** [comment]
// Docker Version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false



// Docker Info
Containers: 46
 Running: 45
 Paused: 0
 Stopped: 1
Images: 415
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4802
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ********************************************
 Is Manager: true
 ClusterID: ********************************************
 Managers: 5
 Nodes: 10
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: ********************************************
 Manager Addresses:
********************************************:2377
********************************************:2377
********************************************:2377
********************************************:2377
********************************************:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-107-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67 GiB
Name: ********************************************
ID: ********************************************
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by yunghoy** [comment]
Obviously, this is a swarm issue. After detatching from swarm mode, I could check out the occupied port has been removed. This was the only way that I could use the port again.

**Comment by thaJeztah** [comment]
@yunghoy if you have a service running in the swarm that uses port `6379`, that is expected. When deploying services, ports are allocated on _every_ node in the swarm, so that traffic to any node in the swarm is routed through the routing mesh. If you `docker service ls` on a manager node, do you have services running? Is one of those services publishing port `6379`?
