### ISSUE TITLE
Docker works on file-level on commit with devicemapper

### ISSUE THREAD

**Issue by 94d90b08-c4ef-416c-bf7b-b6c5b7275e6a** [moby/moby#30357]
**Description**

I configure docker by [guide](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/) without steps 7-12 (pool autoextention).
But it seems to work with files on `docker commit ...` instead of blocks.
I fugure out problem when i start DB inside container, then stop and try to commit it.
Docker copy every DB file (30G). But I'm sure that 3G maximum was changed in blocks.

**Steps to reproduce the issue:**
Steps below shows that docker works with files - not blocks - on `commit` command.
1. Run centos container `docker run -it centos bash`
2. Write 1G file inside that container `dd if=/dev/urandom of=/root/payload.file bs=1M count=1000;exit`
3. Commit container `docker commit <id> test:g_created`
4. Run commited image `docker run -it test:g_created`
5. Write a bit at the end of payload file `echo "123" >> /root/payload.file; exit`
6. Commit your little changes `docker commit <id2> test:g_changed`
7. Review what happens: `docker history test:g_changed`

**Results i received:**
A part of 7 step output:
```
e5330874b924        25 minutes ago      /bin/bash        1.074 GB            
f0bb2206cf80        30 minutes ago      /bin/bash        1.074 GB  
```

**Results i expected:**
Second layer (e5330874b924) should be ~1M size (thin pool block)

**Output of `docker version`:**

```
# docker --version
Docker version 1.12.6, build 78d1802
```

**Output of `docker info`:**

```
CentOS 7.3
# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vg0-docker_pool
 Pool Blocksize: 1.049 MB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 48.42 GB
 Data Space Total: 84.83 GB
 Data Space Available: 36.4 GB
 Metadata Space Used: 2.38 MB
 Metadata Space Total: 83.89 MB
 Metadata Space Available: 81.51 MB
 Thin Pool Minimum Free Space: 8.482 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.685 GiB
Name: xxxxxxxxxxxxxxxxxxxxxxx
ID: xxxxxxxxxxxxxxxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 docker.io:443
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Server: HP ProLiant DL380 G5
OS: CentOS 7.3
[Serverfault link](http://serverfault.com/questions/827476/why-docker-duplicate-device-on-commit-image-instead-of-using-lvm-thin-snapshot)

**Comment by demankiller** [comment]
As i [see](https://github.com/docker/docker/blob/master/daemon/commit.go#L120) such behaviour is a part of docker daemon and can't be changed by driver (devicemapper). On commit daemon copy container step-by-step start with history and so on.
Do you plan to realize workflow explained in issue report?
