### ISSUE TITLE
Default Compose file with docker stack deploy command

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#30352]
Using Docker 1.13:

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

`docker stack deploy couchbase-master` gives the error message:

```
Please specify either a bundle file (with --bundle-file) or a Compose file (with --compose-file).
```

The directory already has a `docker-compose.yml`. A default file name should be use if none is specified.

`docker stack deploy --compose-file docker-compose.yml couchbase-master` feels a bit redundant.

**Comment by vdemeester** [comment]
@arun-gupta as `docker stack deploy` also supports (in experimental) bundle files, we did not want to rush on having a default file name to look for. But yeah, might be a bit redundant for now and is a little bit different that the usual `docker-compose up` 👼

**Comment by arun-gupta** [comment]
@vdemeester Docker Compose v2 and v3 commands are compared towards end of the blog at https://blog.couchbase.com/2017/deploy-docker-compose-services-swarm. Minimalist is better :)

**Comment by dnephin** [comment]
Defaulting to deploying a `docker-compose.yml` is not viable given the project plan in #26876.

The "default" behaviour for `docker stack deploy` in the future should be to accept a "bundle" name and deploy from that.  the `--compose-file` flag is just a "shortcut" to build a bundle and deploy directly in a single command.

In the future we might want to introduce some more subcommands for the old Compose workflows, but I don't know if they would be under `docker stack` or something else.

**Comment by dnephin** [comment]
I think we should close this issue, since it conflicts with the long term plan.

**Comment by vdemeester** [comment]
Closing the issue as it is a `docker/cli` issue anyway
