### ISSUE TITLE
Installing older version of docker-engine on CentOS 7.2.1511 (without some updates) fails

### ISSUE THREAD

**Issue by breser** [moby/moby#30377]
**Description**

When installing on CentOS 7.2 any version of Docker using the docker provided packages fails due to a failure to meet the selinux-policy* packages version requirement if you have updates pegged to a certain point (i.e. you're not directly following the upstream updates repo).  This is occurring due to two reasons:

1. The docker-engine package has a requirement on the docker-engine-selinux package of greater than or equal to the same version of the docker-engine package.  This means trying to install an older version of docker-engine installs the latest version of the docker-engine-selinux.

2. The docker-engine-selinux package for 1.13.0 has a requirement on a version (3.13.1-102) of the selinux packages which was only recently put out (January 18th 2017).  Granted this package is in the generic CentOS 7 updates repo, that does not mean that everyone has it available.

This breaks the ability to easily install older docker versions on older OS versions where you're managing when you roll out updates (e.g. an enterprise environment).  The problem can be worked around by specifying an explicit version of docker-engine and docker-engine-selinux.  But I believe that this is something an end user really shouldn't need to be concerned with.

**Steps to reproduce the issue:**
1. docker run --rm -it centos:7.2.1511
2. sed -i -e "s/mirrorlist=/#mirrorlist=/" -e "s/#baseurl=/baseurl=/" -e "s/\\$releasever/7.2.1511/" /etc/yum.repos.d/CentOS-Base.repo
3. yum install -y yum-utils
4. yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
4. yum makecache fast
5. yum -y install docker-engine-1.12.6-1.el7.centos

The sed command modifies the baseurl for the yum repos so it'll use the version specific repos rather than the generic CentOS 7 ones which have CentOS 7.3 in them.  This mirrors an environment where you might be managing package upgrades and providing a snapshot of these repos and rolling out updated snapshots in a reliable way.

**Describe the results you received:**

Docker fails to install due to the failed dependency of docker-engine-selinux-1.13.0-1 even though I told yum to install docker-engine-1.12.6-1.  

```
Error: Package: docker-engine-selinux-1.13.0-1.el7.centos.noarch (docker-main)
           Requires: selinux-policy-base >= 3.13.1-102
           Available: selinux-policy-minimum-3.13.1-60.el7.noarch (base)
               selinux-policy-base = 3.13.1-60.el7
           Available: selinux-policy-minimum-3.13.1-60.el7_2.3.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.3
           Available: selinux-policy-minimum-3.13.1-60.el7_2.7.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.7
           Available: selinux-policy-minimum-3.13.1-60.el7_2.9.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.9
           Available: selinux-policy-mls-3.13.1-60.el7.noarch (base)
               selinux-policy-base = 3.13.1-60.el7
           Available: selinux-policy-mls-3.13.1-60.el7_2.3.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.3
           Available: selinux-policy-mls-3.13.1-60.el7_2.7.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.7
           Available: selinux-policy-mls-3.13.1-60.el7_2.9.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.9
           Available: selinux-policy-targeted-3.13.1-60.el7.noarch (base)
               selinux-policy-base = 3.13.1-60.el7
           Available: selinux-policy-targeted-3.13.1-60.el7_2.3.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.3
           Available: selinux-policy-targeted-3.13.1-60.el7_2.7.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.7
           Available: selinux-policy-targeted-3.13.1-60.el7_2.9.noarch (updates)
               selinux-policy-base = 3.13.1-60.el7_2.9
Error: Package: docker-engine-selinux-1.13.0-1.el7.centos.noarch (docker-main)
           Requires: selinux-policy-targeted >= 3.13.1-102
           Available: selinux-policy-targeted-3.13.1-60.el7.noarch (base)
               selinux-policy-targeted = 3.13.1-60.el7
           Available: selinux-policy-targeted-3.13.1-60.el7_2.3.noarch (updates)
               selinux-policy-targeted = 3.13.1-60.el7_2.3
           Available: selinux-policy-targeted-3.13.1-60.el7_2.7.noarch (updates)
               selinux-policy-targeted = 3.13.1-60.el7_2.7
           Available: selinux-policy-targeted-3.13.1-60.el7_2.9.noarch (updates)
               selinux-policy-targeted = 3.13.1-60.el7_2.9
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Describe the results you expected:**

Yum to install docker-engine and docker-engine-selinux 1.12.6 without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

This means that the release of 1.13.0 has now broken fully functional deployment setups for previous versions in certain setups.  Ideally docker-engine would require the exact version of docker-engine-selinux.  That could certainly be fixed for going forward but that doesn't really solve the existing problem.

[This commit](https://github.com/docker/docker/commit/ec9a05e5e2e82363fae21131f869e2e34a597c50) that upgraded the selinux policies to the 3.13.1-102 version could be reverted to resolve the problem, but I'm under the impression there's a pretty good reason for changing that since people were having issues with selinux policies.

That doesn't leave a very good fix path for anyone in this situation.  I suppose the Docker project could go put out new revs of the old versions of Docker that are broken by this (e.g. 1.12.6-2) with the explicit requires on the exact version of docker-engine-selinux.  But I'm not sure if that would break anyone that upgrades to the newest version of the package to their specified version of docker-engine which in turn downgrades their docker-engine-selinux.

But at a minimum I think it's necessary to make the docker-engine requirement on docker-engine-selinux be = rather than >=.  To allow changes like this to be made.

**Comment by breser** [comment]
Please ignore the older commits.  I'd pushed a few without the proper branch name and/or the commits weren't signed per the contribution policies.

**Comment by lukewendling** [comment]
any workaround for this? broken deployments ongoing...

**Comment by justincormack** [comment]
I believe there was nothing we could do other than this, as upstream made changes; I think @andrewhsu can explain in detail.

**Comment by lukewendling** [comment]
@justincormack  to be clear, installing 1.12 from a local rpm package fails, and tries to install 1.13, which fails as the OP described. is it possible to install 1.12 and bypass issues caused in 1.13?

**Comment by breser** [comment]
Workaround for local users is instead of running:
```
yum -y install docker-engine-1.12.6-1.el7.centos
```

Run:
```
yum -y install docker-engine-1.12.6-1.el7.centos docker-engine-selinux-1.12.6-1.el7.centos
```

This works because docker-engine the docker-engine-selinux of the same version still meets the requirement, but yum prefers installing the newest version that will still meet the requirement.  Which means if you let it select it then it will select docker-engine-selinux-1.13.0, which fails.

**Comment by Maximus86** [comment]
Confronted with the same issue, thank you for the workaround @breser!

**Comment by cpuguy83** [comment]
The version of `selinux-policy` specified is unfortunately the minimum version required to install `docker-engine-selinux` for 1.13.0.

One way to get around this would be to remove the requirement of `docker-engine-selinux` from the `docker-engine` package, but then there's no way for yum to handle these pseudo-depdendencies... deb handles this sort of issue with recommends, but rpm does not have such a concept AFAIK.

We should update the required version of `docker-engine-selinux` to match the `docker-engine` package, though.

**Comment by lukewendling** [comment]
Thanks @breser that works.

**Comment by breser** [comment]
The only good way forward to unbreak existing users and not require them to use a workaround would be to put out new releases of the older versions with the the requirement between docker-engine and docker-engine-selinux set to be an exact version requirement rather than an >= requirement.

That could be done by merging the pull request onto the various release branches and then cutting new releases from there.  I'd expect rather than bumping the version of docker you'd just bump the release version of Docker.  I.E. 1.12.6-1 would become 1.12.6-2.

That's not a perfect solution to end users because if they were using 1.12.6-1 in their configurations they'd have to update them to 1.12.6-2.  But it would be far better than forcing them to specify both docker-engine and docker-engine-selinux for any of these older versions.

At my place of employment we've updated our Puppet configuration to downgrade all the docker-engine-selinux packages to match the version-release of the docker-engine package we have installed on the systems.  While for systems that we're just installing Docker for we've made it install both with the same version.  But this code is rather ugly compared to what we had before.

If we had fixed releases of the packages we could simply remove that code and go back to just installing a specified version of docker-engine.

**Comment by esalberg** [comment]
What if you leave the >= but add an option to the manifest to specify the version of docker-engine-selinux / install it before docker-engine?  We just added that to our profile for the time being, but it really would belong in install.pp.

**Comment by dansou901** [comment]
fails on Oracle Linux 7 due to too old selinux-policy-base:
Error: Package: docker-engine-selinux-1.13.0-1.el7.noarch (dockerrepo)
           Requires: selinux-policy-base >= 3.13.1-102
           Installed: selinux-policy-targeted-3.13.1-60.0.1.el7_2.9.noarch (@local_ol7)
               selinux-policy-base = 3.13.1-60.0.1.el7_2.9
           Available: selinux-policy-minimum-3.13.1-60.0.1.el7_2.9.noarch (local_ol7)
               selinux-policy-base = 3.13.1-60.0.1.el7_2.9
           Available: selinux-policy-mls-3.13.1-60.0.1.el7_2.9.noarch (local_ol7)
               selinux-policy-base = 3.13.1-60.0.1.el7_2.9
Error: Package: docker-engine-selinux-1.13.0-1.el7.noarch (dockerrepo)
           Requires: selinux-policy-targeted >= 3.13.1-102
           Installed: selinux-policy-targeted-3.13.1-60.0.1.el7_2.9.noarch (@local_ol7)
               selinux-policy-targeted = 3.13.1-60.0.1.el7_2.9

**Comment by arivolispark** [comment]
Thanks @breser.

The following worked for me:

yum -y install docker-engine-1.12.6-1.el7.centos docker-engine-selinux-1.12.6-1.el7.centos

**Comment by tstibbs** [comment]
Same problem seems to exist now that it's docker-ce except that the workaround from @breser doesn't work for CE. Does this effectively mean that the latest versions of docker are no longer expected to work on Centos 7.2?

**Comment by cpuguy83** [comment]
CentOS point releases are not actual releases, they are points in time. CentOS follows a rolling release cycle. Yes you can pin your repos to particular versions but then of course you can't install newer packages.
docker-ce supports "Centos 7". Due to changes to the base selinux policy package we had to bump the minimum required version of the selinux policy package. If you are pinned to older packages you won't be able to install newer versions of Docker unless you tell it to skip the selinux dep.

**Comment by HackToday** [comment]
Find similar issue with docker-ce as following:

```
Error: Package: docker-ce-selinux-17.04.0.ce-1.el7.centos.noarch (docker-ce-edge)
           Requires: selinux-policy-base >= 3.13.1-102
           Installed: selinux-policy-targeted-3.13.1-60.el7_2.9.noarch (@updates)
               selinux-policy-base = 3.13.1-60.el7_2.9
           Available: selinux-policy-minimum-3.13.1-60.el7.noarch (base)

```

**Comment by cpuguy83** [comment]
Yes, I do not think there is anything we can do here. We only support Centos `7`, not targeted patch releases, which requires pinning your repos to specific versions.

SELinux policies are required to be compiled against the running base policy, or rather a version of the base policy that both has everything that the policy needs and does not conflict with. Since the base policies were changed to conflict with our packages we had to both change our policy to remove those conflicts and bump the minimum required version version of the base policy.

Going forward we plan to use `container-selinux` on supported RH-based distros.

**Comment by Justluckyg** [comment]
How do you reproduce this from a centos server that dont have access to the internet?

Basically our partner environment only allows us to access to a jumpbox that can access their servers inside.

These servers cant egress out.

Thanks for your help in advance!

**Comment by cpuguy83** [comment]
@Justluckyg You'll need to make sure you have access to the required `container-selinux` version.
Closing since this is a non-issue.
CentOS is a rolling release that should always be updated otherwise you end up missing important updates.

Docker does support targeted RHEL versions with docker-ee.
