### ISSUE TITLE
`docker service ps` matches prefix

### ISSUE THREAD

**Issue by dongluochen** [moby/moby#30417]
**Description**

`docker service ps` matches all services with prefix. This makes checking one service difficult.

**Describe the results you received:**

```
~$ docker service ls
ID            NAME      MODE        REPLICAS  IMAGE
px48rzlk1tsv  monitor2  replicated  1/1       dongluochen/centos:latest
ybxxtvw800pq  monitor   replicated  1/1       dongluochen/centos:latest

~$ docker service ps monitor
ID            NAME        IMAGE                      NODE               DESIRED STATE  CURRENT STATE          ERROR  PORTS
v7zw5bsvys83  monitor2.1  dongluochen/centos:latest  ip-172-19-241-144  Running        Running 6 minutes ago
nosm3pqdauir  monitor.1   dongluochen/centos:latest  ip-172-19-241-146  Running        Running 6 minutes ago
```

**Describe the results you expected:**

```
~$ docker service ps monitor
ID            NAME        IMAGE                      NODE               DESIRED STATE  CURRENT STATE          ERROR  PORTS
nosm3pqdauir  monitor.1   dongluochen/centos:latest  ip-172-19-241-146  Running        Running 6 minutes ago
```

**Output of `docker version`:**

```
~$ docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   9adee23
 Built:        Sat Jan 21 01:42:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   9adee23
 Built:        Sat Jan 21 01:42:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by aaronlehmann** [comment]
I agree that we should change this. It's different behavior from other Docker commands, which match first on ID, then on name, then on ID prefix (but not name prefix).

But I wonder if we would need to deprecate this behavior before changing it. Even though I suspect this is unintentional, someone may be relying on it.

**Comment by thaJeztah** [comment]
Duplicated by https://github.com/moby/moby/issues/32556, pull requests in https://github.com/moby/moby/issues/32800, and https://github.com/docker/cli/pull/72

Let me close this one for housekeeping, as we're tracking it through https://github.com/moby/moby/issues/32556

(sorry, didn't see this earlier, it got lost in my backlog :blush:)
