### ISSUE TITLE
Docker 1.13.0 - Must be connected to a terminal. - screen

### ISSUE THREAD

**Issue by phlegx** [moby/moby#30421]
I enter my docker container (docker version ```1.13.0```, the container was started via docker-compose version ```1.8.1``` ) via ```docker exec -it container_name bash``` I then install ```screen``` within my docker container and trying to run in it just by typing ```screen```

however I then get the following error:

```Must be connected to a terminal.```

I remember this working just fine a while ago with an older docker version. 

Is someone familiar with this problem? Could it be a bug?

**Comment by cpuguy83** [comment]
@phlegx You probably need to run the container with `-t` in addition to running the exec with `-t`.

**Comment by phlegx** [comment]
hi  @cpuguy83! Thanks and yes that is correct, it works when I run the container via docker and add there the ```-t``` flag.  However I'm pretty sure that with either previous versions of ```docker``` or ```docker-compose``` this tty was enabled by default, since this worked out of the box some time ago.

I was wondering now how to model the same ```-t``` behaviour with docker-compose?   I tried to set the flag ```tty: true``` (I tried this also with the newest docker-compose version ```1.10.0```) as mentioned [here](https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir). However this has no effect and I still get:

```Must be connected to a terminal```

**Comment by cpuguy83** [comment]
@phlegx That's indeed interesting. I believe compose does set tty by default.
Can you post the `inspect` output of the container created by compose which is not working with screen/`exec -t`?

**Comment by phlegx** [comment]
Here is some crucial part of the the inspect:

```        "Config": {
            "Hostname": "cdf3df3fc2dd",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
...
```

So It seems even if I set:

```tty: true```

in the docker-compose file under the correct docker container settings.

I assume this is a bug. Do you need some more info @cpuguy83?

**Comment by amir-beheshty** [comment]
Has this issue been resolved? I'm dealing with the same exact issue...

**Comment by phlegx** [comment]
@amir-beheshty Yes this issue still persists also for me.

However I came to the conclusion that its probably way better to install screen on the host and run the command inside the container from there with docker exec, something like

```screen docker exec -it CONTAINER_NAME sleep 10```

So one does not need to install `screen` in the container at all and can manage everything from the host.

**Comment by amir-beheshty** [comment]
@phlegx good idea. I just tried it:
- `sudo yum install screen`
- `screen docker exec -it CONTAINER_KEY /bin/bash`
Not sure what `sleep 10` is for. But so far this has worked for me. Thanks for the tip!

**Comment by wmchris** [comment]
```
Run script /dev/null to own the shell
```
then try screen again. Works like a charm for me.

**Comment by amir-beheshty** [comment]
@wmchris Good to know, thanks!

**Comment by thaJeztah** [comment]
@phlegx is this still an issue for you? I tried to reproduce using the following steps;

1. run a container without `-t` / tty attached;

```bash
docker run -d --name foo nginx:alpine
```

2. `docker exec -it` into the container

```bash
docker exec -it foo sh
```

3. inside the container, install `screen`

```bash
/ # apk add --no-cache screen
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.0-r7)
(2/4) Installing ncurses-terminfo (6.0-r7)
(3/4) Installing ncurses-libs (6.0-r7)
(4/4) Installing screen (4.5.1-r0)
Executing busybox-1.25.1-r0.trigger
OK: 20 MiB in 30 packages
/ #
```

4. start `screen`

```bash
/ # screen

GNU Screen version 4.05.01 (GNU) 25-Feb-17

Copyright (c) 2015-2017 Juergen Weigert, Alexander Naumov, Amadeusz Slawinski
Copyright (c) 2010-2014 Juergen Weigert, Sadrul Habib Chowdhury
Copyright (c) 2008-2009 Juergen Weigert, Michael Schroeder, Micah Cowan, Sadrul Habib Chowdhury
Copyright (c) 1993-2007 Juergen Weigert, Michael Schroeder
Copyright (c) 1987 Oliver Laumann

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along with this program (see the file COPYING); if not, see http://www.gnu.org/licenses/, or contact Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA  02111-1301  USA.

Send bugreports, fixes, enhancements, t-shirts, money, beer & pizza to screen-devel@gnu.org


Capabilities:
+copy +remote-detach +power-detach +multi-attach +multi-user +font +color-16 +utf8 -rxvt -builtin-telnet
```

**Comment by ryenus** [comment]
@thaJeztah may I ask what's your docker version? I guess most of the users are still waiting for 17.06, which as [you noted](https://github.com/moby/moby/issues/8755#issuecomment-300152451) would fix the tty issue, isn't it?

BTW, in #8755 it was mentioned multiple times that things would work with `docker exec -it $container script /dev/null`, e.g. [this one](https://github.com/moby/moby/issues/8755#issuecomment-60707979), but using docker 17.03 on macOS I don't have this `script` thing, any details? Thanks!

**Comment by thaJeztah** [comment]
You're right, I forgot that machine was updated to 17.06.0-rc3. I tested in 17.05 and there the issue still occurs. Docker 17.06.0-rc3 is available for testing (but obviously not for production use yet)

**Comment by glycerine** [comment]
Inside the docker container, run `script /dev/null` first. Then you should be able to start `screen`.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
