### ISSUE TITLE
Slow build with overlay storage driver 

### ISSUE THREAD

**Issue by AleksandrIakhnev** [moby/moby#30436]
**Description**

Docker build  with storage driver `overlay` is much slower then `aufs` driver because of enumeration base image for every build step

**Steps to reproduce the issue:**
1. Create dockerfile 
```
FROM python:3.5

ARG INJECTED_VAR1
ENV INJECTED_TEXT1  INJECTED_VAR1
ENV INJECTED_TEXT2  INJECTED_VAR1
ENV INJECTED_TEXT3  INJECTED_VAR1
ENV INJECTED_TEXT4  INJECTED_VAR1
ENV INJECTED_TEXT5  INJECTED_VAR1
ENV INJECTED_TEXT6  INJECTED_VAR1
ENV INJECTED_TEXT7  INJECTED_VAR1
ENV INJECTED_TEXT8  INJECTED_VAR1
ENV INJECTED_TEXT9  INJECTED_VAR1
```
2. Build with overlay storage driver
```
time docker build --no-cache --build-arg INJECTED_VAR1="abc"  \
    --rm -t docker-test/env -f Dockerfile .
```
3. Build with storage driver aufs

**Describe the results you received:**
I receive build time with overlay about 16-20 seconds and about 2 seconds foraufs. If I use sysdig
```
sudo sysdig -p "%fd.name"  proc.name=dockerd
``` 
then it is about 700 K file operations during build with overlay driver and about 7K for aufs, seems that overlay driver lists base image for every build step

**Describe the results you expected:**
I expect that overlay driver does not enumerate base image and build speed is relatively equal to aufs

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 134
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.307 GiB
Name: aleksandr-VirtualBox
ID: PBD7:NQKL:4OZJ:LIKL:I4P7:X6QH:BESD:QAG3:MAKM:RIZQ:4H6E:ZZZR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Stable reproducing on Ubuntu 16.04 AWS/VirtualBox

**Comment by justincormack** [comment]
cc @dmcgowan

**Comment by justincormack** [comment]
Have you tried `overlay2`? This should work much better and should be fine with your kernel version. Can you see if it has the same slowdown? It is generally much more efficient than the original `overlay` but you need a 4.0 kernel to support it.

**Comment by justincormack** [comment]
As a reference it takes about 6 seconds for me with `overlay2` on Docker for Mac, which seems much better than your measurement on `overlay`, vs 8s on `aufs`, vs 21s with `overlay` so I think if you change it will be the same or better than `aufs`.

**Comment by AleksandrIakhnev** [comment]
@justincormack Thank you, with overlay2 build is even faster than with aufs. I'm just wondering then why overlay driver is default when aufs support is not available in the kernel.

**Comment by justincormack** [comment]
I think there were some concerns about how to know if `overlay2` is supported, and it was relatively new. We did start to make some changes to the default ordering in 1.13, maybe we need to make some more. cc @thaJeztah

**Comment by justincormack** [comment]
@thaJeztah points out that `overlay2` should be chosen before `overlay` now https://github.com/docker/docker/blob/78a83a22699198b31c8cbdace3a73c8502f99ba1/daemon/graphdriver/driver_linux.go#L59

How did you select the driver?

**Comment by AleksandrIakhnev** [comment]
@justincormack overlay is default for docker 1.12.5 I'll check with 1.13

**Comment by thaJeztah** [comment]
@AleksandrIakhnev could it be you're running running the Ubuntu package of docker 1.12, which is not maintained by us, and has a different configuration. I just tried to install their `docker.io` version on a fresh machine, and got this;

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64
root@ubuntu-2gb-ams3-01:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: ubuntu-2gb-ams3-01
ID: DZYA:7MME:2IIN:IM2F:HJGN:P2CX:JDDF:UIMV:XPLS:K5AG:QSKV:GM66
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

That's pretty bad, because 1.12.3 has a CVE which is fixed in 1.12.6, but possibly they patched runc separately;
http://changelogs.ubuntu.com/changelogs/pool/universe/d/docker.io/docker.io_1.12.3-0ubuntu4~16.04.2/changelog

There is no configuration set in the systemd unit-file or the daemon.json, but I think they moved "overlay" up in the list based on this entry in the changelog;

```
docker.io (1.8.3~ds1-2) unstable; urgency=medium
  * Move "overlay" higher in priority (Closes: #799087)
```

**Comment by thaJeztah** [comment]
So, correct, the Ubuntu package is modified to put overlay higher up the list;

```patch
Description: move "overlay" to a higher priority (now that AUFS is not supported in Debian kernels)
Author: Tianon Gravi <tianon@debian.org>
Forwarded: no
diff --git a/daemon/graphdriver/driver_linux.go b/daemon/graphdriver/driver_linux.go
index 410a62f..eab78e7 100644
--- a/daemon/graphdriver/driver_linux.go
+++ b/daemon/graphdriver/driver_linux.go
@@ -48,8 +48,8 @@ var (
 		"aufs",
 		"btrfs",
 		"zfs",
-		"devicemapper",
 		"overlay",
+		"devicemapper",
 		"vfs",
 	}

 ```

**Comment by rrichardson** [comment]
Since `overlay2` is broken on my Kernel (https://github.com/docker/for-linux/issues/711) I have been forced to switch the fs to `overlay`. I am running into this slowness issue.  It took 5+ hours to build a docker image yesterday that should have taken a few minutes.  Are there any options I could tweak to help speed this up?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
