### ISSUE TITLE
install.sh doesn't support debian stretch RC1

### ISSUE THREAD

**Issue by flx42** [moby/moby#30456]
Installed debian stretch [RC1](https://www.debian.org/devel/debian-installer/) with KVM.
`/etc/debian_version` is `9.0` and there is no case in `install.sh` for this version:
https://github.com/docker/docker/blob/06e3812b6e50f63b13b9a6eefb012da83f6283ab/hack/install.sh#L180-L187

`/etc/apt/sources.list.d/docker.list`:
```
deb [arch=amd64] https://apt.dockerproject.org/repo debian-9 main
```
Which doesn't exist.

**Comment by thaJeztah** [comment]
We don't have packages yet for stretch, so this error is expected. Generally, we only release for stable releases (currently Jessie), but we may want to start testing on Stretch

ping @andrewhsu @justincormack @ijc25

**Comment by flx42** [comment]
Is that true? The following works:
```
$ docker run -ti debian:stretch
root@1804d8526439:/# apt-get update && apt-get install -y curl 
root@1804d8526439:/# curl -sSL https://get.docker.com/ | sh
[...]
+ sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sh -c echo deb \[arch=amd64\] https://apt.dockerproject.org/repo debian-stretch main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Get:4 https://apt.dockerproject.org/repo debian-stretch InRelease [30.2 kB]
Get:5 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages [6362 B]
[...]

root@1804d8526439:/# apt-cache policy docker-engine
docker-engine:
  Installed: 1.13.0-0~debian-stretch
  Candidate: 1.13.0-0~debian-stretch
  Version table:
 *** 1.13.0-0~debian-stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
```
The `install.sh` script works fine here because of this:
```
root@1804d8526439:/# cat /etc/debian_version 
stretch/sid
```

**Comment by thaJeztah** [comment]
oh, my, you're right, got my wires crossed. Hm, looks like that part was added in https://github.com/docker/docker/commit/9728269424461696cf2223ebb723828041da1f61 to accommodate forked distros. t.b.h. we're trying to move away from that script, because detection can fail in various situations, but perhaps you're interested in opening a pull request to fix this?

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/issues/30480 was merged, so closing this
