### ISSUE TITLE
client.Client package should provide testable/mockable version for unit (not e2e) testing

### ISSUE THREAD

**Issue by alexellis** [moby/moby#30454]
**Description**

I'm trying to write tests against code consuming client.Client, I can see a number of ways of abstracting this but they all feel obtuse and repetitive.

Are there efforts to create a testable / mockable version of the client.Client code in the `docker/docker` repository?

Go includes modules to allow testing of http servers - so it seems like it could be an idiomatic pattern to provide a docker/docker client.Client version which can also provide a testable interface. 

I may be missing something here, but have had a chat with Justin and browsed the source, I didn't seem to find something like a way to create a client for unit testing.

Ideally I could do something like this:

```
testClient := client.NewTestClient{}
error := scaleService(alert, &testClient)

....

func scaleService(req requests.PrometheusAlert, c *client.Client) error {
	var err error
        serviceName := req.Alerts[0].Labels.FunctionName
	service, _, inspectErr := c.ServiceInspectWithRaw(context.Background(), serviceName)
	if inspectErr == nil {
		var replicas uint64
		if req.Status == "firing" {
			if *service.Spec.Mode.Replicated.Replicas < 20 {
				replicas = *service.Spec.Mode.Replicated.Replicas + uint64(5)
			} else {
				return err
			}
           // c.ServiceUpdate(......
       }
```

I wondered if @dnephin might have some ideas?

**Comment by thaJeztah** [comment]
Also ping @vdemeester

**Comment by alexellis** [comment]
@nathanleclaire we were talking about a similar subject. ^^

**Comment by alexellis** [comment]
@cpuguy83 Looks like exactly what I'm looking for. There is a compilation error about the vendored context struct. How do you implement the interface in a test-double? 

```
# github.com/alexellis/faas/gateway/tests
./scale_test.go:33: cannot use tClient (type testClient) as type client.ServiceAPIClient in argument to handlers.MakeAlertHandler:
	testClient does not implement client.ServiceAPIClient (wrong type for ServiceInspectWithRaw method)
		have ServiceInspectWithRaw("context".Context, string) (swarm.Service, []byte, error)
		want ServiceInspectWithRaw("github.com/docker/docker/vendor/golang.org/x/net/context".Context, string) (swarm.Service, []byte, error)
FAIL	github.com/alexellis/faas/gateway/tests [build failed]
```

If I alias "context" to "github.com/docker/docker/vendor/golang.org/x/net/context" then Go complains about using a vendored package, aliasing "golang.org/x/net/context" to context also fails for the error above.

Code:

```
import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/alexellis/faas/gateway/handlers"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/swarm"
	"github.com/docker/docker/client"
)

func (t testClient) ServiceInspectWithRaw(ctx context.Context, serviceID string) (swarm.Service, []byte, error)
func (t testClient) ServiceUpdate(ctx context.Context, serviceID string, version swarm.Version, service swarm.ServiceSpec, options types.ServiceUpdateOptions) (types.ServiceUpdateResponse, error)

type testClient struct {
	client.ServiceAPIClient
}

func Test(t *testing.T) {
	rr := httptest.NewRecorder()

	body := "{\"alertStatus\": \"firing\"}"
	req, err := http.NewRequest("POST", "/system/alert", bytes.NewBufferString(body))
	if err != nil {
		t.Fatal(err)
	}
	tClient := testClient{}
	handler := handlers.MakeAlertHandler(tClient)
```

**Comment by cpuguy83** [comment]
You need `golang.org/x/net/context` in your import instead of `context`

**Comment by alexellis** [comment]
That was what I tried originally, even with `	context "golang.org/x/net/context"` I get the same error. I've also dropped the docker/docker folder in go/src/ and ran `go get` again to make sure it's up to date.

```
./scale_test.go:39: cannot use tClient (type testClient) as type client.ServiceAPIClient in argument to handlers.MakeAlertHandler:
	testClient does not implement client.ServiceAPIClient (wrong type for ServiceCreate method)
		have ServiceCreate("golang.org/x/net/context".Context, swarm.ServiceSpec, types.ServiceCreateOptions) (types.ServiceCreateResponse, error)
		want ServiceCreate("github.com/docker/docker/vendor/golang.org/x/net/context".Context, swarm.ServiceSpec, types.ServiceCreateOptions) (types.ServiceCreateResponse, error)
FAIL	github.com/alexellis/faas/gateway/tests [build failed]
```

**Comment by cpuguy83** [comment]
Oh, yes the vendoring issue...

You'll need to strip the vendors.

**Comment by alexellis** [comment]
How do you do that? The only thing I found Google "strip vendors" was re: a tool called glide.

**Comment by thaJeztah** [comment]
@alexellis you can use `vndr` 😇 https://github.com/lk4d4/vndr. even though the description is "stupid", it's actually pretty cool, and you may recognize the author of that project 😇

**Comment by marcosnils** [comment]
further info: 

https://github.com/peterbourgon/wtf

**Comment by antonosmond** [comment]
I hit the same problem - have an app that uses the docker library and functions that accept types that implement the interface `client.CommonAPIClient`. I designed my package like this specifically so I could pass in mock docker clients in my tests but due to the vendored 'context' package my tests fail to compile. 😞

**Comment by cpuguy83** [comment]
@antonosmond You just need to strip `vendor/` from the vendored docker/docker.
This is a nasty go bug.

**Comment by alexellis** [comment]
@antonosmond did you get anywhere with your tests? the vndr tool @thaJeztah mentions is also used by the containerd project.

**Comment by antonosmond** [comment]
@alexellis yes thanks!
I was previously vendoring the docker package with the command:
```
govendor add -tree github.com/docker/docker/client
``` 
This basically just does a copy/paste from the package in the GOPATH to the vendor directory in my package and because `go get` pulls the vendor folder i.e. the vendor folder was in the docker package in my GOPATH, this was being included when I used `govendor add`.

I now add the vendored package using:
```
govendor fetch -tree github.com/docker/docker/client
```
This fetches the packages directly from the remote into my vendor folder, excluding any vendor folders from the source

**Comment by vinicyusmacedo** [comment]
Hi, I'm also having trouble writing unit tests using the client. On the Docker Swarm repo, there's a really nice [mock](https://github.com/docker/swarm/blob/master/api/mockclient/mock.go) for the it. Unfortunately, it looks outdated, and a lot of functions are missing. Could this repo have something like this?

**Comment by umamaheswar52** [comment]
Hi team, when could be this available?

**Comment by Jeanhaley32** [comment]
Hey all, It seems like the intent for this issues was actually resolved by @cpuguy83 with a comment pointing to the client interface. Everything else is a discussion about implementation. Should this ticket still be open? It's pretty old, and seems stagnant at this point. Going to suggest we close it.

**Comment by alexellis** [comment]
@Jeanhaley32 this issue is ancient, and looks like it was forgotten about. Closing.
