### ISSUE TITLE
docker daemon should support support default option for --storage-opts "size" parameter for supported drivers.

### ISSUE THREAD

**Issue by imkin** [moby/moby#30491]
Currently Docker create and run commands supports the --storage-opt "size" param for a few graph drivers. 
Documentation: https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container

> This (size) will allow to set the container rootfs size to 120G at creation time. This option is only 
available for the devicemapper, btrfs, overlay2, windowsfilter and zfs graph drivers. For the 
devicemapper, btrfs, windowsfilter and zfs graph drivers, user cannot pass a size less than the 
Default BaseFS Size. For the overlay2 storage driver, the size option is only available if the backing fs is xfs and mounted with the pquota mount option. Under these conditions, user can pass any size less then the backing fs size.

This issue is to request that the optional "<btrfs/dm/grafdriver>.default_size" param be supported for the docker daemon --storage-opts for the supported drivers[in the above list] so that a global predicatble value could be set if the user does not pass any.

**Comment by bklau** [comment]
I think there's just too many "clauses" and "provisos" in using --storage-opt. Also no clarity as to what --storage-opt size=XXX meant:
1.  The max size for the container's diff(CoW) layer, or
2.  The max size for the container's base image layers plus its diff(CoW) layer
etc. etc.
Most end users are not filesystem experts; so making it easy for 80% of the usecases would help.
