### ISSUE TITLE
Docker for Windows RUN Rename-Item causes file to vanish

### ISSUE THREAD

**Issue by drnybble** [moby/moby#30512]
**Description**

Using RUN Rename-Item in a Dockerfile causes the item to disappear.

**Steps to reproduce the issue:**
1.
Create this Dockerfile:
FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN New-Item Stuff.txt -type File
RUN Rename-Item Stuff.txt OtherStuff.txt
CMD ls

2.
docker build -t bug .

3.
docker run bug

**Describe the results you received:**
The file is not there:

    Directory: C:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/16/2016   9:18 AM                PerfLogs
d-r---        1/27/2017  12:34 PM                Program Files
d-----        7/16/2016   9:18 AM                Program Files
d-r---        1/27/2017  12:34 PM                Users
d-----        1/27/2017  12:34 PM                Windows
-a----       11/22/2016   5:45 PM           1894 License.txt

**Describe the results you expected:**
The file is there. If you instead use Copy-Item both files show up.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried with Linux Docker (using touch and mv) and works as expected.

FROM debian:jessie
RUN touch Stuff.txt
RUN mv Stuff.txt OtherStuff.txt
CMD ls

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 129
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8 GiB
Name: WIN-U9UU27TK2FQ
ID: HOYH:CLDY:C2SF:SJJN:VEN6:H2CS:FECI:QKIM:WA3K:3PJX:2QPE:F443
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 pa-docker:5000
 127.0.0.0/8
Live Restore Enabled: false

```

Running on Server 2016 in a VirtualBox VM.

**Comment by jhowardmsft** [comment]
That looks like a platform bug in the filter driver. I'll investigate next week.

**Comment by jhowardmsft** [comment]
I have a repro. We are tracking internally via VSO bug #10943100

@patricklang FYI.

**Comment by thaJeztah** [comment]
ping @jhowardmsft @patricklang still being worked on?

**Comment by jhowardmsft** [comment]
Yes. The bug (actually there's two) hasn't been service yet. I wouldn't expect a fix going out before 6B earliest.

**Comment by amccool** [comment]
I seem to have a similar problem with `move-item`
`RUN ["powershell", "move-Item", "-force", "-path /app/OrleansConfiguration.vDEVINT.xml", "-destination /app/OrleansConfiguration.xml"]`
where the destination file is not overwritten

**Comment by drnybble** [comment]
@jhowardmsft Is this issue resolved yet?
