### ISSUE TITLE
[Windows] Executable bits not set/propagating

### ISSUE THREAD

**Issue by killerspaz** [moby/moby#30511]
**Description**

Files marked as executable in the host environment (Win10, git bash [not UFW/LsW/etc]) do not propagate executable bit to Container.

Originally building via `docker-compose`, you get absolutely no warning about any potential file permission issues. When building with `docker build` you actually do:

> SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

However, inside the container, the file permissions are absolutely NOT 755 as promised. 

Local:
```
-rwxr-xr-x 1 killerspaz 197609 439 Jan 27 10:25 gatherLogs.js.sh*
```

Container:
```
-rw-rw-rw-    1 root     root           439 Jan 27 16:25 gatherLogs.js.sh
```

I found https://github.com/docker/docker/issues/11047 which also backs up the permission setting by default on Windows hosts, but to no avail. I can understand having a hard time propagating permissions, but not setting them to what is expressed in both an Issue, Documentation, and Warning message (which for some reason is only exposed in docker engine) is not exactly easy to figure out what's going on.

**Steps to reproduce the issue:**
1. Using gitbash, set executable bit on file
2. Build an image, where Dockerfile has `COPY ./folderFullOfFiles /path`

**Describe the results you received:**
The FOLDER is `755`.
File permissions are a useless `666`

**Describe the results you expected:**
As stated in the warning, documentation, and everything else I expect *ALL* COPIED FILES TO BE `755`.

**Additional information you deem important (e.g. issue happens only occasionally):**

My current assumption is because I'm copying a folder, the operation of setting permissions is only done on said folder, and not all of its contents. If this is expected/desired, I'd like to make an argument that either it's completely wrong to do so, or all notes about the permission functionality should be appropriately updated to inform the user of ACTUAL outcome.

Error originally found in `1.12.*`, attempted with `1.13` and still broken.

**Output of `docker version`:**

```
time="2017-01-27T11:33:03-06:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
time="2017-01-27T11:33:26-06:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.43-boot2docker
Operating System: Boot2Docker 1.13.0 (TCL 7.2); HEAD : 5b8d9cb - Wed Jan 18 18:50:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: EY5M:2K3Z:J4U7:P5PS:L3U7:SH44:TU5T:45HS:4BFE:2NJK:YZMC:RJ2V
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 38
 System Time: 2017-01-27T17:33:26.117159709Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* GitBash 2.11.0.windows.1
* Win10 Home, 64bit, v1607 build 14393.693
* VirtualBox  5.1.14 r112924

**Comment by thaJeztah** [comment]
Thanks for reporting; are you still having this issue on the current release? If so (trying to come up with a minimal reproduction case); can you reproduce the issue with the steps below?

```bash
mkdir repro-30511 && cd repro-30511

mkdir somedirectory
touch somedirectory/one somedirectory/two somedirectory/script.sh
chmod 755 somedirectory/script.sh


docker build -t repro-30511 --no-cache . -f -<<EOF
FROM busybox
COPY ./somedirectory /path
RUN ls -la /path
EOF
```

**Comment by thaJeztah** [comment]
closing as this one went stale
