### ISSUE TITLE
Need a documentation about tools and technologies that docker uses internally in the code

### ISSUE THREAD

**Issue by milindchawre** [moby/moby#30528]
A while ago, I started contributing to docker and was able to fix few doc and cli related issues.
But was unable to pick issues related to other areas like runtime, networking, etc. It is bit difficult to know how runc, containerd, etc are used by docker in its code.

For any beginner level contributor, it becomes difficult to understand the entire code flow or even a single docker component codebase.
There are documentation available for few of the tools but it don't mention anything about the tools used internally within docker.
There should be documentation explaining all tools and technologies that docker uses internally in the code like : `runc, libnetwork, containerd, docker-containerd-shim, ctr, cobra, rootfs, etc`
Should also document : how docker creates namespaces, which all system calls do docker calls internally, how docker uses runc and so on.
There should be pointers to files and repository where the code resides for each of these tools like code for rootfs related stuff, image related stuff, etc.
Such documentation will really help beginner level contributor a lot.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
