### ISSUE TITLE
docker commit -c does not expand from container/parent environment

### ISSUE THREAD

**Issue by henryptung** [moby/moby#30538]
**Description**

`docker commit -c` does not expand environment variables from parent images or the container, the way a `Dockerfile` does.

**Steps to reproduce the issue:**

```
bash-3.2$ grep '' -r .
./base/Dockerfile:FROM busybox
./base/Dockerfile:ENV ABC abc
./next/Dockerfile:FROM local/base
./next/Dockerfile:ENV DEF $ABC
bash-3.2$ docker build -t local/base base
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM busybox
 ---> 7968321274dc
Step 2/2 : ENV ABC abc
 ---> Running in 469e22f566ec
 ---> 6cba68c627bc
Removing intermediate container 469e22f566ec
Successfully built 6cba68c627bc
bash-3.2$ docker build -t local/next next
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM local/base
 ---> 6cba68c627bc
Step 2/2 : ENV DEF $ABC
 ---> Running in 2bbbd2c5d335
 ---> f2c0582b954c
Removing intermediate container 2bbbd2c5d335
Successfully built f2c0582b954c
bash-3.2$ docker inspect local/next | jq '.[].Config.Env'
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "ABC=abc",
  "DEF=abc"
]
bash-3.2$ docker create --name test-commit local/base
770c21912fdede7bf48ac93472b9521d8302e9051b6e3e21d5cba78cee552070
bash-3.2$ docker commit -c 'ENV DEF $ABC' test-commit local/test-commit
sha256:60448d42c689cf079cb3399d1a99f46acf496ebae89d406b17b00ec3e564ac5e
bash-3.2$ docker inspect local/test-commit | jq '.[].Config.Env'
[
  "DEF=",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "ABC=abc"
]
bash-3.2$
```

**Describe the results you received:**

Expression `$ABC` was not expanded in the `docker commit -c` command, even though it was in the chained Dockerfile build.

**Describe the results you expected:**

`DEF=abc`, just as in the `local/next` chained-Dockerfile build.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 95
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.787 GiB
Name: moby
ID: ILWD:XNQW:SI6X:EQLJ:UDJA:ZQOC:EGRY:XGXD:OR66:NC6R:T6ZW:NHDB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 33
 System Time: 2017-01-28T22:05:15.595520577Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac 1.13.0, though I strongly suspect this issue lies inside the Docker daemon code (inside the Docker machine VM), not in the Mac client.

**Comment by thaJeztah** [comment]
ping @duglin - I don't think this feature was ever designed as a full replacement for `docker build`, so not sure it's even possible

**Comment by asottile** [comment]
This should be fairly easy to implement, from what I can tell (at a first glance) the implementation of `--change` ends up here:

https://github.com/moby/moby/blob/d032264e1365a1cea621b7105e1ca521cb4218ef/builder/dockerfile/builder.go#L359

The missing magic that makes this work from a `Dockerfile` appears to be this bit here:

https://github.com/moby/moby/blob/d032264e1365a1cea621b7105e1ca521cb4218ef/builder/dockerfile/builder.go#L289

(notably this bit): https://github.com/moby/moby/blob/d032264e1365a1cea621b7105e1ca521cb4218ef/builder/dockerfile/builder.go#L261

This is entirely missing from the `BuildFromConfig` dispatch:

https://github.com/moby/moby/blob/d032264e1365a1cea621b7105e1ca521cb4218ef/builder/dockerfile/builder.go#L389-L407

**Comment by asottile** [comment]
Here's a patch that fixes this: https://github.com/moby/moby/pull/35582
