### ISSUE TITLE
Docker container fails to start - no such file or directory

### ISSUE THREAD

**Issue by sybrandy** [moby/moby#30531]
**Description**

This has happened a couple times where I try to start a container and it fails with an error like this:

    docker: Error response from daemon: lstat /var/lib/docker/overlay2/...: no such file or directory

This latest time, it happened after a reboot.  The file path specified in the error doesn't exist.  The only way I can resolve this is to delete the image, and any associated containers, and pull it down again.

**Output of `docker version`:**

Version: 1.12.1
API version: 1.24
Go version: go1.6.3
Git commit: 23cf638
OS/Arch: linux/amd64

**Output of `docker info`:**

(Can't copy an paste from this box, so here's a summary)
Storage Driver: overlay2
  Backing Filesystem: exstfs
Logging Driver: journald
Cgroup Driver cgroupfs
Kernel Version: 4.9.1-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
Architecture: x86_64
CPUs: 64
Total Memory: 251.9 GiB

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server.

**Comment by thaJeztah** [comment]
I see a couple of issues;

- First of all, you're using CentOS on a non-standard kernel; we only support the default kernel as are provided by the distro
- Overlay(2) is only supported on XFS on RHEL/CentOS, see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html
- You're running an outdated version of docker; a lot of fixes went in to subsequent patch releases, and the current version is 1.12.6 (for 1.12), or 1.13 for the most up to date version
- make sure your filesystem is formatted correctly, see https://github.com/docker/docker/issues/27358#issuecomment-254066211

**Comment by sybrandy** [comment]
Hello,

Thanks for the info.  I'll try to let you know if the suggestions help.  Unfortunately, I have to get a sysadmin to assist with changing the filesystem, so I have no idea how long it will take.

One suggestion though: could you update the Docker documentation for Overlay to mention what you referenced in your second and fourth bullets?  I remember reading that documentation to see if there would be any issues by switching and never would have thought that the type of filesystem would have such an effect.

**Comment by thaJeztah** [comment]
@sybrandy would you be interested in contributing, and opening a pull request for that? The Markdown file to generate the overlay documentation can be found here; https://github.com/docker/docker.github.io/blob/master/engine/userguide/storagedriver/overlayfs-driver.md

If you're not able to contribute; could you open an issue in the documentation issue tracker? https://github.com/docker/docker.github.io/issues (so that we don't forget about it :smile:)

**Comment by sybrandy** [comment]
I created a new ticket for the documentation.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by thaJeztah** [comment]
Closing because https://github.com/docker/docker.github.io/pull/3276 updated the docs
