### ISSUE TITLE
docker ps documentation is missing Formatting section

### ISSUE THREAD

**Issue by emersonf** [moby/moby#30541]
The [configuration file documentation](https://docs.docker.com/engine/reference/commandline/cli/#/configuration-files) states

> The property psFormat specifies the default format for docker ps output. When the --format flag is not provided with the docker ps command, Docker’s client uses this property. If this property is not set, the client falls back to the default table format. For a list of supported formatting directives, see the [Formatting section in the docker ps documentation](https://docs.docker.com/engine/reference/commandline/ps/)

There's no such section in the docker ps documentation.

**Comment by thaJeztah** [comment]
thanks for reporting; the documentation switched to a different system for publishing the reference docs, and some parts haven't been migrated yet - i think this is being worked on 

/cc @mstanleyjones

**Comment by thaJeztah** [comment]
This was fixed; https://docs.docker.com/engine/reference/commandline/ps/#format
