### ISSUE TITLE
setcap not supported on BTRFS storage backend

### ISSUE THREAD

**Issue by jcberthon** [moby/moby#30557]
**Description**

I would like to set particular capabilities to a file while building a new container. When building the Dockerfile, the build fails when setting the capabilities if the host uses BTRFS as storage backend, but the build is successful when using OverlayFS2 as storage backend.

**Steps to reproduce the issue:**
1. Create a Dockerfile which sets a capability on a regular file (e.g. `setcap 'cap_sys_resource+ep' /bin/ls`)
2. Build the Dockerfile on a host where Docker uses BTRFS for storage backend
3. The build fails when trying to execute the setcap command

**Describe the results you received:**

This was done on a Dockerfile which is based on ubuntu:16.04 image and install ntp and try to set the capabilities on the file /usr/sbin/ntpd. The following is displayed:

```
Step 4/6 : RUN setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice=+ep' /usr/sbin/ntpd
 ---> Running in 75025f7b6071
Failed to set capabilities on file `/usr/sbin/ntpd' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
The command '/bin/sh -c setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice=+ep' /usr/sbin/ntpd' returned a non-zero code: 1
```

Of course `/usr/sbin/ntpd` is a regular file: `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked`. In addition, if I install ntp on Ubuntu 16.04 on a bare metal host and if I run this:

```
$ getcap /usr/sbin/ntpd
$ sudo setcap cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice=+ep  /usr/sbin/ntpd
$ getcap /usr/sbin/ntpd
/usr/sbin/ntpd = cap_net_bind_service,cap_sys_nice,cap_sys_resource,cap_sys_time+ep
$ df -Th /usr/sbin/ntpd
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sda4      btrfs   23G   11G   12G  49% /
```

**Describe the results you expected:**

This is the expected result (from another host which uses OverlayFS2 as storage backend over an ext4 partition):

```
Step 4/6 : RUN setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep' /usr/sbin/ntpd
 ---> Running in 72ec9ec7d0ce
 ---> a5ed9956ab95
Removing intermediate container 72ec9ec7d0ce
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It works with this backend:
```
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
```

But fails with this one:
```
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker system info
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 39
Server Version: 1.13.0
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.55 GiB
Name: mercury
ID: 
Docker Root Dir: /var/lib/docker/235536.235536
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The tests were run both on physical boxes (bare metal). One (BTRFS) is on x86_64 (Ubuntu 16.04 with kernel 4.8), the other one (OverlayFS2 over ext4) is on ARM 32bit (Raspberry Pi, Raspbian Jessie with custom kernel 4.9). Both run the same version of Docker (1.13.0). Here is the Docker information command for the ARM host:

```
$ docker system info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 94
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.9.5-v7-lowlat-tick-rtc1307+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 969.9 MiB
Name: venus
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I want to set capabilities because I have basically the problem described here #8460 and I want to work around it while waiting for ambient capabilities to be implemented.

**Comment by justincormack** [comment]
Hi, I am trying to work on ambient caps, but it will need changes to the OCI specification so will take a while longer. Which capabilities do you need?

I don't know why btrfs has no fs caps support. AUFS is the same but as you say overlay is fine, and with overlay they do round trip through Docker Hub alright. btrfs supports them fine, so it is quite odd, if you can work out what is happening that would help.

**Comment by jcberthon** [comment]
Hi @justincormack,

I'm trying to set the minimum capabilities required by a container and run it in a user namespace. My goal is to apply this to a mariadb container, but I'm also experimenting with a NTP container (simpler in my opinion). I'm dropping all capabilities and add only the required ones.

For MariaDB, the minimum capability set I have found until now is: NET_BIND_SERVICE, CHOWN, SETUID, SETGID.

For NTP, it is: NET_BIND_SERVICE, SYS_TIME (and optionally SYS_RESOURCE and SYS_NICE, but those are not required).

As I said, I can set those capabilities to the NTP executable when I do that on the host system, eventhough the NTP executable is on a BTRFS file system.

I did a bit more investigations but the results are odd, perhaps you could help/guide me and I could then dig further into it. Here is the statement:

* when I do `setcap cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep /usr/sbin/ntpd` inside the Dockerfile as a `RUN` step, it fails with the error mentioned in the issue.
* when I remove the line with the setcap instruction from the Dockerfile, it builds successfully but the capabilities is not set on the file obviously. However if I then run the build image and execute inside the running container the command `setcap cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep /usr/sbin/ntpd`, it is successful (if I gave the `SETFCAP` capability to the run command obviously).

Both times, the command runs on top of BTRFS (same partition). I'm not using volumes.

**Why is the `setcap` working inside the running container and not when building it?** Where should I look to investigate that further?

**Comment by justincormack** [comment]
Running strace on docker-containerd is probably useful, to see if a syscall
is failing.

**Comment by jcberthon** [comment]
I guess I have to set-up a test environment for that. Running strace on my current set-up which has about 10 containers is going to be noisy...

In order to do as you suggest, shall I edit the systemd unit (I mean overriding the ExecStart line in a file under /etc/systemd/system)? How do you usually proceed for this kind of debugging?

**Comment by jcberthon** [comment]
Hi @justincormack 

I have investigated further and found the reason: not a bug.

Setting capabilities on a file (during docker build) works even with a BTRFS backend.

That did not work before because user namespace was activated. But when it is deactivated, it works.

So the permission problem I reported is due to the fact that I'm building an image with this daemon.json configuration:

```
{
    "userns-remap": "default"
}
```

Now I'm starting to have a real problem... In French we say that "the cat is biting its own tail", I think in English it is something like "running in circles".

My goal is to run a service (e.g. NTP) in its own user namespace but that it is still able to listen to a privilege port (e.g. 123) and adjust the system time, so it requires some extra capabilities (e.g. NET_BIND_SERVICE and SYS_TIME). That container works perfectly when using `--userns host` (so deactivating user namespace for that container), but fails to bind to privilege port or perform privilege action (such as changing system time). To workaround this, there are 2 solutions:

1. Using ambient capabilities: you are working on this and that's really really great :-)
2. Setting the capabilities on the file itself: I cannot do it at build time because of the daemon configuration using user namespaces; I can also obviously not do it once running the container because it runs as an unprivileged user.

**Therefore I conclude that it is not possible to run a container using user namespace when it requires special capabilities.**

_Note: do you know if the following would work? Building the image (which set the capabilities on the file) on a machine which does not use user namespace, pushing that image to a container registry, pulling that image to my host which is running Docker with user namespace activated, running it hopefully successfully because the file has the correct capabilities now._

_Note2: I manage to run mariadb in such an environment, but it does not require extra capabilities that a standard user does no have._

**Comment by jcberthon** [comment]
Another information. It seems that the solution of setting the file capability does not work anyway.

I decided to directly modify the file under the `/var/lib/docker` folder and as root on the host to set the file capabilities.

Setting the capabilities seems to have work using that "hack" (this was done after recreating the running container): 
```
$ docker exec -it ntpd getcap /usr/sbin/ntpd                                                                                           [11:46:57]
/usr/sbin/ntpd = cap_net_bind_service,cap_sys_nice,cap_sys_resource,cap_sys_time+ep
```

However, displaying the container logs I can see that ntpd can still not change the time nor bind to the privilege port. And this does not seem to be a problem due to the seccomp profile, because running with `--security-opt seccomp=unconfined` shows the same operation not permitted error.

**Comment by justincormack** [comment]
Cc @estesp

**Comment by estesp** [comment]
@jcberthon thanks for the detailed information in this and other issues on the topic.

Can you clarify for me something from the original report above? When the statements are made around "works on overlay2, fails on btrfs" is that with user namespaces enabled in both cases? Specifically, does userns+overlay2 **work**, but userns+btrfs **fail** to allow `setfcap`?

Again, thanks for all the info and hopefully we can figure out something here, with the awareness that distros, kernel versions and other environmental settings can make these issues challenging to validate at times.

**Comment by jcberthon** [comment]
Hi @estesp 

Sorry, indeed that is now confusing. So on the 2nd platform (overlayfs over ext4) it does not use user namespaces, hence it worked.

On one platform I had correctly set up the option in the daemon.json file, while on the other one I used the `/etc/default/docker` file to define the command line options. But it seems that a "recent" update disable/deprecated that feature on Debian. So there was a point in time where both platforms were having user namespaces ON, but it was deactivated on one without me noticing it.

But I can see this:

Platform 1 (x86_64, Docker 1.13.0):

```
$ docker info
(...)
Server Version: 1.13.0
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
(...)
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
```

And platform 2 (Raspberry Pi 2, ARM 32bit, Docker 1.13.0):

```
$ docker info
(...)
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
(...)
Security Options:
 apparmor
Kernel Version: 4.9.5-v7-lowlat-tick-rtc1307+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
```

I will try to activate on platform 2 userns (using daemon.json) and see if it works or not. But I would expect now that it fails as well in this configuration. I will report soon.

I will also run the check-config.sh Docker script on both platform and attach the output in an upcoming comment. Platform 1 should have the "standard Ubuntu" kernel features, as I'm using the stock Kernel (albeit the hwe-edge version); platform 2 should have many more feature activated compare to the stock Raspberry Pi foundation kernel as I'm building my own (in order to support seccomp filtering, AppArmor, etc. although for [seccomp filtering I managed to get Kernel support but not the user space tools](https://github.com/raspberrypi/linux/issues/1172#issuecomment-252655607).)

N.B.: Is the limitation that I cannot use `setcap` during build time when using userns related to this issue #1916?

**Comment by justincormack** [comment]
@jcberthon capabilities (including `SET_FCAP` that sets filesystem caps) are very restricted in user namespaces. From the man page http://man7.org/linux/man-pages/man7/user_namespaces.7.html

> Having a capability inside a user namespace permits a process to
       perform operations (that require privilege) only on resources
       governed by that namespace.  In other words, having a capability in a
       user namespace permits a process to perform privileged operations on
       resources that are governed by (nonuser) namespaces associated with
       the user namespace (see the next subsection).

The files that you are trying to change are not covered, they are global, because you changing them could affect other processes that might have access to those files, letting them raise privileges, so `SET_FCAP` does nothing in a user namespace, even though you have it...

**Comment by jcberthon** [comment]
Hi @justincormack 

Thanks for the explanation and reference. But as far as I understand the rest of the user manual page, if the initial process which creates the first user namespace would have the capability, then a process within that user namespace could use that capability if granted (e.g. set on the file).

I would have thought that granting the capability when creating the container (e.g. using `--cap-add SYS_TIME` when doing the `docker run ...`) would then allow any process within the user namespace to use that capability if it was set on one of the file executed within that namespace.

If it was not the right approach, how to grant capabilities to the user namespace when it is created? And side question will ambient capabilities solve that problem or are we also limited by the user namespace (there was no mention of ambient capabilities in the man page).

**Comment by jcberthon** [comment]
Hi @estesp 

So I've tested trying to set capabilities on a file in a Dockerfile when the backend is overlayfs2 over ext4 but using user namespace, and in this configuration it fails exactly as with the BTRFS backend configuration when using user namespace.

So the problem in this case was not the storage backend, but the user namespace. So it is related to the bug I have mentioned.

Therefore I think - if I'm correct - that a part of this bug report is a duplicate (a specialisation) of bug #1916. And, unless Justin reports that when using `--cap-add <...>` should have granted the capability to the user namespace and therefore my "hack" should have worked, we could close this issue.

**Comment by CsterKuroi** [comment]
**problem:**
```
root@6639eed34eae:/bin# touch jihao

root@6639eed34eae:/# setcap 'cap_net_bind_service=+ep' /bin/jihao              
Failed to set capabilities on file `/bin/jihao' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```
**docker info:**
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 36
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: iZ25g9famsqZ
ID: M555:WYFH:KG3O:JGS6:5OT4:G4JH:GJAU:ZBLE:W4YQ:6QVM:M4FX:PI6P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jcberthon** [comment]
@CsterKuroi this is because you are using the AUFS storage backend. AUFS does not support extended file attributes.

As you are still on Ubuntu 14.04.5, you should try to get a newer Kernel (see this Ubuntu official guide: https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Ubuntu_14.04_LTS_-_Trusty_Tahr). With this newer Kernel, you should be able to choose OverlayFS for the storage backend of Docker. OverlayFS support extended attributes and therefore your use case should work.

Take case that when switching of storage backend, you are losing access to your images created with the previous backend (but if you switch back to it, you can still see them). So if you switch to OverlayFS, you will have to recreate the images and containers.

**Comment by jcberthon** [comment]
I was proposing to close this issue, as there is no feedback I'm closing it.
