### ISSUE TITLE
BUG: Swarm "mode=vip" publishing host port hangs up

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#30566]
**How to reduce BUG**

0. docker pull nginx
1. docker swarm init
2. docker service create -p 10000:80 nginx
3. ab -n 100000 -c 8 http://localhost:10000/

After step 3, the 10000 port access hangs up.

**Describe the results you expected:**

quickly get response for each http request

**Output of `docker version`:**

both docker 1.12 and docker 1.13

**Comment by thaJeztah** [comment]
ping @aboch @mavenugo PTAL

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
