### ISSUE TITLE
Docker 1.13.0-0~debian-jessie connect inside the conainers doesnt work

### ISSUE THREAD

**Issue by tecchnikBA** [moby/moby#30561]
Hi there,
last Monday(23.01.2017) we made a docker upgrade.
docker-engine:amd64 (1.12.6-0~debian- +++jessie, 1.13.0-0~debian-jessie
So far everything fine.
On Saturday we got an out of memory exception, because our server has not enough memory.
so we restarted the machine and all our about 50 containers came up again.
This morning we tried to connect do a container with mariadb  from a client. - no connection-.
On the host we were able to connect with the IP and port, but no container was access able from outside the machine.
after searching for a few hours if there something corrupt with out LAN, we decided to downgrade docker.
After the downgrade the containers still were not access able.
After a reboot - at least - the mariadb containers are aces able again.

We run debian Linux 8.7 with the kernel 
3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Lin

Downgrade: docker-engine:amd64 (1.13.0-0~debian-jessie, 1.12.6-0~debian-jessie)

unfortunately I cannot reproduce this, because its a live server.
I will try to reproduces it tomorrow on another server.

Has anyone the same issue?

best regards
Andreas

**Comment by gianarb** [comment]
Helllo @tecchnikBA thanks for your report.
Can you provide more info about your server? Can you run `docker info`? 
Thanks

**Comment by bodote** [comment]
docker info on our machine result : 

Containers: 75
 Running: 75
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 205
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 126.1 GiB
Name: xxxx
ID: 7AXF:UEEM:4HCS:TSBZ:DHEQ:AGCK:2KVB:XW6O:RTBT:PCKE:ETHR:LI24
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

and we are also running  ZFS on this machine, although i don't think that this has anything to do with the described problem, has it ?

**Comment by tecchnikBA** [comment]
Hi,
we now tried an update to Docker 1.17 - same issue.
As soon as we make an upgrade all our Docker containers are not available from outside the host....
can anyone reproduce this issue?
best regards

**Comment by thaJeztah** [comment]
Do the daemon logs show anything useful? What options have you set on the daemon, other than using zfs? For example, do you have `--iptables=false`? Anything useful in your IPTables rules before and after upgrading?

**Comment by tecchnikBA** [comment]
We have no Ip Tables active. I already made a downgrade because its a productive maschine.
These are my network settings for on example container:

  "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2fb2d655617ffd6f3123fc1b1d1745c77352e4a2d5cf7483a613d839fb19951d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/2fb2d655617f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "445fcce64959a7973995b9fcabca89ea93a46d7b4dcdc70990d23fe9096c8c5e",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.23",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:17",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "73fdfa039ec6808ef9ede9628709eaa59428b2a661e6330499f6a5a10fd92202",
                    "EndpointID": "445fcce64959a7973995b9fcabca89ea93a46d7b4dcdc70990d23fe9096c8c5e",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.23",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:17"
                }

ZFS is used to snapshot mariadb Databases and with the snapshot we create a clone, which is mapped as /var/lib/mysql
see:

 "Mounts": [
            {
                "Source": "/home/xxx/mysql_docker",
                "Destination": "/etc/mysql",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/zfsdata/clones/20161125.155345xxxx-xxxxkopie",
                "Destination": "/var/lib/mysql",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

**Comment by tecchnikBA** [comment]
Update to Docker 17 CE fixed it. IPV4 Forward was disabled
