### ISSUE TITLE
Unable to create DockerNAT

### ISSUE THREAD

**Issue by psykzz** [moby/moby#30571]
**Description**

When starting docker for windows, the client locks up.
After looking through some logs i see that HyperV doens't progress from the Create stage.

After some looking around, it seems its the powershell script MobyLinux.ps1 that is having issues, again digging deeper i've noticed the issue is with the hyper v network switch, stalling while creating.

To visualise the issue, If i manually try to create the interface, i get the following... forever, it never goes away.

![image](https://cloud.githubusercontent.com/assets/1134201/22441296/b8148c3a-e72e-11e6-889c-fd621ac221a8.png)

**Steps to reproduce the issue:**
1.  Turn on docker for windows
2.  Client never finishes "startup"
3.

**Describe the results you received:**
Docker never started,

**Describe the results you expected:**
Docker should start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
C:\Users\PsyKzz>docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
C:\Users\PsyKzz>docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

![image](https://cloud.githubusercontent.com/assets/1134201/22441377/0dbe07c4-e72f-11e6-9b13-07e57c00c14d.png)

(Funny, not actually sure if product ID should be secret or not.)

**Comment by psykzz** [comment]
Apologies, i forgot i already opened this issue in another repo https://github.com/docker/for-win/issues/434.

I'm not sure whether to leave this open, please close if needed.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
