### ISSUE TITLE
Containers on some nodes cannot connect to certain other containers in an overlay network

### ISSUE THREAD

**Issue by petestorey26** [moby/moby#30595]
We have a Docker setup running on Centos 7, v 1.12.1 in production and 1.13.0 in staging, and both of them are affected by a bizarre issue.  There are 8 Docker nodes, running an overlay network across them with a Consul backend, all running on AWS.  We are starting a lot of containers, which get re-deployed frequently-ish.  The vast majority of the containers (about 150 across the setup - note it's not running Swarm, just overlay networking) are microservices running HTTP on 8080.

The odd thing is the after a while, containers on some nodes will no longer be able to talk to certain other containers - the connection times out every time - even though containers on other nodes have no problem accessing the very same ip:port combo, so we know it's running.

I wrote a python script which queries consul for all the service endpoints and tries to connect to them all, and put this inside an image, which another bash script then runs on every node.  The result is we can check every endpoint from every node, and in doing so, discover that even for a fresh container on a particular node, it will not be able to connect to the same set of containers every time.

I can't "reproduce" this specifically - it just happens; we originally noticed it as some web requests would hang for ages, and we eventually determined it was because a microservice call would wait 60 seconds for a timeout before trying another instance, so the whole thing got very slow.

I'm not sure where to start to try and highlight how this happens, or what we should be looking at, because it's not the network configuration per se - since generally containers on 7 of the 8 nodes can connect to the errant endpoint just fine.

**Comment by warroyo** [comment]
@petestorey26 can you see if this is only happening with communication between containers on the same host? I am seeing this with centos7.2 kernel `3.10.0-327` and docker `1.12.1` seems to be a kernel incompatibility. after upgrading my kernel or downgrading docker to 1.11.x I dont see the issue.

**Comment by petestorey26** [comment]
Hi @warroyo we do run that kernel in prod, but 3.10.0-514 in staging, with docker 1.13.0, and the same problem exists.  

It also happens across nodes in every example we have, though this may or may not be meaningful, it may simply not have happened node to itself yet.

**Comment by schikin** [comment]
Same issue here. Using Docker for AWS. Here's a little bit of detail:
docker version:
`Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 21:19:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 21:19:34 2017
 OS/Arch:      linux/amd64`

docker info: 
`Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 14
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: lopewx8gx6kzc4ro2xtwtbq91
 Is Manager: false
 Node Address: 172.31.31.127
 Manager Addresses:
  172.31.27.223:2377
  172.31.36.249:2377
  172.31.5.195:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991 MiB
Name: ip-172-31-31-127.ec2.internal
ID: TZPP:5IHS:YR65:5W4Z:R2HK:4QI7:MKUU:SWV5:H3M6:RPWJ:OOBF:LQRR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 161
 System Time: 2017-02-04T22:38:11.308264033Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

Services are weirdly losing TCP connectivity at some point. My setup is ELB -> Kong (as a Swarm Service) -> Services. Kong and services are on the same overlay net (10.0.0.0/16). Ingress network is working fine. All the containers can reach each other (they weren't yesterday though) except for Kong. Kong is able to ping all the other containers but fails to connect on a tcp port. It could connect and work ok just after it was deployed. Then in an hour or so this issue has emerged. Here are the examples:
`$ ssh docker@staging
Welcome to Docker!

 ~ $ docker service ps kong
ID            NAME        IMAGE        NODE                           DESIRED STATE  CURRENT STATE           ERROR                        PORTS
2wg1iwew1nzg  kong.1      kong:latest  ip-172-31-31-127.ec2.internal  Running        Running 54 minutes ago                               

~ $ ssh ip-172-31-31-127.ec2.internal
Welcome to Docker!

~ $ docker ps
CONTAINER ID        IMAGE                                                                          COMMAND                  CREATED             STATUS              PORTS                               NAMES
fab73d83448a        kong@sha256:a20a4a1a60c5353f8d7cf01cfc1bf065719c9f38be81d16c11093b0999f23d49   "/docker-entrypoin..."   55 minutes ago      Up 55 minutes       7946/tcp, 8000-8001/tcp, 8443/tcp   kong.1.2wg1iwew1nzg9zqwq1ncylgd4
c5fb7855b974        docker4x/guide-aws:aws-v1.13.0-1                                               "/entry.sh"              5 days ago          Up 5 days                                               guide-aws
2e5a317c62e2        docker4x/shell-aws:aws-v1.13.0-1                                               "/entry.sh /usr/sb..."   5 days ago          Up 5 days           0.0.0.0:22->22/tcp                  shell-aws

~ $ docker exec -it fab73d83448a bash
[root@fab73d83448a /]# ping auth
PING auth (10.0.0.2) 56(84) bytes of data.
64 bytes from ip-10-0-0-2.ec2.internal (10.0.0.2): icmp_seq=1 ttl=64 time=0.037 ms
64 bytes from ip-10-0-0-2.ec2.internal (10.0.0.2): icmp_seq=2 ttl=64 time=0.046 ms
64 bytes from ip-10-0-0-2.ec2.internal (10.0.0.2): icmp_seq=3 ttl=64 time=0.057 ms
^C
--- auth ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2043ms
rtt min/avg/max/mdev = 0.037/0.046/0.057/0.011 ms

[root@fab73d83448a /]# nc auth 8080
Ncat: Connection timed out.
[root@fab73d83448a /]# 
`

That's how it look from the other container on the same overlay network:
`[root@6651c7184520 app]# nc auth 8080
GET /

HTTP/1.1 404 Not Found
access-control-allow-origin: *
access-control-allow-headers: Content-Type
access-control-allow-headers: Authorization
Content-Type: text/plain; charset=utf-8
Content-Length: 9
Date: Sat, 04 Feb 2017 22:51:54 GMT
Connection: close

Not Found

Ncat: Broken pipe.
`

Has been fighting this for 2 days now. So any help appreciated

**Comment by aboch** [comment]
@schikin  Your issue is different, you are using swarm mode. 
From @petestorey26 's report, it looks they are not using swarm mode

>There are 8 Docker nodes, running an overlay network across them with a Consul backend [...]
> [...]note it's not running Swarm, just overlay networking

@petestorey26 please confirm and add the docker info o/p to this issue

@schikin Please open a new GH issue.

Thanks

**Comment by petestorey26** [comment]
OK so in our production version, docker info is:

`Containers: 25
 Running: 24
 Paused: 0
 Stopped: 1
Images: 177
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-226492659-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 14.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 92.97 GB
 Metadata Space Used: 15.55 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.53 GiB
Name: ip-10-0-4-100
ID: ODT4:7YYR:2GGY:QBBW:GVWV:F4MT:A5F4:UXJ2:5FRO:AYX5:VTOT:ZXMB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: consul://consul.engage.local:8500
Cluster Advertise: 10.0.4.100:2375
Insecure Registries:
 127.0.0.0/8`

**Comment by petestorey26** [comment]
And our staging (same issue, different versions)

```
Containers: 26
 Running: 24
 Paused: 0
 Stopped: 2
Images: 167
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 13.27 GB
 Data Space Total: 122.4 GB
 Data Space Available: 109.1 GB
 Metadata Space Used: 4.702 MB
 Metadata Space Total: 1.288 GB
 Metadata Space Available: 1.283 GB
 Thin Pool Minimum Free Space: 12.24 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.53 GiB
Name: ip-10-0-3-69
ID: 6GD7:3JN5:2XWR:VPIL:WU5M:UJ6U:N33I:N7JP:OUKB:FGRR:XRRJ:GRAP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: consul://consul.engage.local:8500
Cluster Advertise: 10.0.3.69:2375
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by tgeens** [comment]
@petestorey26 We're experiencing similar issues on 1.12.6 on CentOS 7 with an external Consul backend for the overlay network. 

In our case sometimes these failures seems to be intermittent: connectivity issues can happen for 30 seconds and recover after a minute - or for other combinations no connectivity at all would be possible.

Did you manage to work through these issues ?

**Comment by petestorey26** [comment]
Not really I'm afraid, no.  We ultimately ditched the overlay network as
it's just not quite reliable, and the failure modes are so hard to get a
grip of that it wasn't worth it.

**Comment by tgeens** [comment]
@petestorey26 If you are still interested, have a look at issue https://github.com/moby/moby/issues/29024 That thread provides a (verifiable) explanation + workaround for the connectivity issues  we had!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
