### ISSUE TITLE
[Feature request] Hide Windows specific options in --help if not applicable

### ISSUE THREAD

**Issue by albers** [moby/moby#30624]
Docker already hides experimental options and commands in the help messages. To get to this information, it queries the server for its experimental property.

This feature could be extended to also hide operation system specific commands and options. At present, this would be Windows specific options, e.g. `docker run --cpu-count --cpu-percent -credentialspec --io-maxbandwidth --io-maxiops --isolation`. But this could as well be Mac or Solaris specific ones in the future.

Bash completion already has this feature, see #30438. It issues `docker version --format '{{.Server.Os}}'` to get the required information.

**Comment by ripcurld0** [comment]
@albers can you give an example of an experimental option?
I just know there are experimental commands.

**Comment by albers** [comment]
@ripcurld0 `docker build --squash` and `docker stack deploy --bundle-file` are experimental.

**Comment by ripcurld0** [comment]
#dibs

**Comment by thaJeztah** [comment]
We could  probably handle this with annotations, similar to  https://github.com/docker/docker/pull/30186

@dnephin wdyt?

**Comment by albers** [comment]
@thaJeztah Hm, wondering if #30186 could also be applied to bash completion...

**Comment by thaJeztah** [comment]
This was implemented in https://github.com/moby/moby/pull/30788, so let me close this issue
