### ISSUE TITLE
panic in 1.12.5

### ISSUE THREAD

**Issue by samoht** [moby/moby#30641]
Reported by @cloutiertyler on Docker for Mac: https://github.com/docker/for-mac/issues/205#issuecomment-276240698

I made a gist which isolate the panic stack trace: https://gist.github.com/samoht/ad87fb019d6e29580145c31bd4ec6488

Please let me know if you need more information (or if you want this kind of issues to be formatted differently / reported in a different place). It happened using the stable channel of Docker for Mac on the 10th of January and was using 1.12.5

**Comment by tonistiigi** [comment]
By the trace this seems to be go1.6 so not 1.13

**Comment by samoht** [comment]
@tonistiigi you are right, sorry. The user is now on 1.13 but the stack trace appeared on the 10th of January, using 1.12.5.

**Comment by tonistiigi** [comment]
@tiborvass I think we can lower the priority on this one as it's not a `v1.13` regression. Really hard to say anything about the trace, it seems like the memory corruption that causes the panic has also had an effect on the trace. There seems to be things missing in the backtrace of first goroutine.

**Comment by AkihiroSuda** [comment]
Closable?
