### ISSUE TITLE
Unexpected behavior at .dockerignore file

### ISSUE THREAD

**Issue by Alessar** [moby/moby#30676]
#### Description
Behavior by documentation and behavior of docker is not the same.
https://docs.docker.com/engine/reference/builder/#/dockerignore-file
Documentation says that /foo/bar and foo/bar at ```.dockerignore``` file are the same.
#### Expected behavior
Expected that ```/node_modules``` and ```node_modules``` will be the same too.
#### Actual behavior
In case ```node_modules``` in ```.dockerignore``` file, looks like, all stuff in that directory are ignored correctly.
In case ```/node_modules``` docker try to push node_modules into container and sometimes get error:
WindowsError: [Error 3] The system cannot find the path specified: 'E:\\Project\\node_modules\\very-very-long-path\\filename'

And additionally, looks like, docker cannot work with long names - possible it is issue too.

**Comment by gianarb** [comment]
Hello thanks for your report but we need more info about your system. Can you copy the output of 
`docker info` and `docker version`?
Thanks

**Comment by Alessar** [comment]
```Docker version 1.13.0, build 49bf474```

```
Containers: 28
 Running: 16
 Paused: 0
 Stopped: 12
Images: 282
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: CBKD:JBNB:DF4W:4CZW:UBBE:BVJY:54GL:2QH7:ZVNT:Q4QE:E7AH:PQVP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 166
 Goroutines: 200
 System Time: 2017-02-02T16:52:07.3492984Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Alessar** [comment]
I hope it does not contain secure data of my system :-)

**Comment by tonistiigi** [comment]
I guess the issue may be backslashes in windows client. cc @duglin

**Comment by simonferquel** [comment]
I just tested with @vdemeester on a Linux client / server, and the same behavior is there. Having `/testfile` in .dockerignore does not exclude `testfile` at the root of the build context. (tested on a 1.13.x though).

Should we fix both Linux and Windows or should we update the docs ? cc @tonistiigi

**Comment by simonferquel** [comment]
cc @thaJeztah

**Comment by tonistiigi** [comment]
@simonferquel Yes, I'd expect it to work.
@duglin Can you confirm?

**Comment by duglin** [comment]
hmm odd that we don't have a testcase for that when someone explicitly talked about that situation in the docs.  I think this PR is the one that added the text:  https://github.com/docker/docker/pull/15265  
I **think** we were expecting people to only put relative paths in there since it doesn't really make sense to have absolute ones.  While on the daemon / does equal the root of the build context, that's not true for the client.  However, given a choice between throwing an error and just ignoring the leading / it probably would be more friendly to just assume we knew what they really meant and let it work.

**Comment by simonferquel** [comment]
Ok, I'll remove all leading `/` or `\\` from the .dockerignore entries on read then. Does it sound good ?

**Comment by thaJeztah** [comment]
Removing leading `\` - won't that be a problem for escaping?

**Comment by simonferquel** [comment]
Hmm I think you are right @thaJeztah, I don't think .dockerignore is supposed to support windows style file paths
