### ISSUE TITLE
Permisson denied when svlogd tries to rotate a log

### ISSUE THREAD

**Issue by mitar** [moby/moby#30697]
I have a series of Docker images I have been using on Ubuntu 14.04 LTS with aufs. I have upgraded my servers recently to Ubuntu 16.04 LTS and started using overlay2. Now I am noticing occasional strange errors by [svlogd](http://smarden.org/runit/svlogd.8.html), a logging daemon inside my Docker images. It collects stdout of daemons and writes them to a file. When file reaches 1 MB, it rotates them by moving a file from `current` to timestamped filename and opening a new file instead under `current` log. But on this upgraded servers occasionally svlogd throws an error that it could not rename the file, and pauses itself. As a consequence (maybe because stdout gets full) or because of some other correlated issue with a container also the daemon (like database) hangs as well. Which means that Docker container becomes useless.

Restarting the container resolves the issue and things start working again.

This happened to me on multiple Docker images on multiple servers, but with the same version of underlying Ubuntu, Docker, and kernel. Log (`current` file, and its timestamped old versions) is being written to a directory which is a volume.

Sadly, I was unable to create a simplified reproduction (yet). Here is an [example image where this happened](https://github.com/tozd/docker-mongodb). And here is my attempt at a [simplified version which just logs heavily](https://github.com/mitar/docker-heavy-logging), but where an issue was not reproduced.

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 38
 Running: 38
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.41 GiB
Name: intel2
ID: JBXO:FLAI:HV2W:3XOP:FOYA:A6OP:GANE:X3EN:AMFH:LWSC:5PPW:RO4H
Docker Root Dir: /srv/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment]
The switch from aufs to overlay should not play a role here, because the logs are written to volume or a bind-mounted directory, so are not an overlay filesystem.

Is there a reason you're using `/dev/shm` (which probably is a tmpfs) to write your logs to? Do you see the same issue if you use a different location?

**Comment by mitar** [comment]
This was just in reproduction, I tried different things, I tried tmpfs to try to get it to be faster to maybe trigger the condition.

The mongodb images it is just a normal ext4 directory binded in from outside.

If there are some ideas what it could be, I can try in the reproduction to get that. My guess was an overlay system, but it seems it is not.

**Comment by thaJeztah** [comment]
No direct clue what the issue could be. Have you checked the daemon- and system logs?

To exclude possibilities, it's worth trying to run the container with `--security-opt seccomp=unconfined`, or `--privileged` (just for testing) to disable seccomp and apparmor

Apart from having a newer kernel, ubuntu 16.04 also supports seccomp filtering, and runs on `systemd` (instead of upstart/sysvinit). Although I don't see a _direct_ relation in the last one, you never know with `systemd` :smile:

**Comment by mitar** [comment]
This is still regularly happen on multiple servers. Log rotation is done by runit's svlogd inside a container.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
