### ISSUE TITLE
Docker swarm mode networking timeout and MongoDB replication issue

### ISSUE THREAD

**Issue by vingrad** [moby/moby#30751]
**Description**

Very big replication lag with mongodb in docker swarm mode 1.13 (encrypted network). Many network timeouts in database log.

Every ten seconds, this kind of error is written to the log on db secondaries:
```
[replication-334] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 2769905 -- target:.....
...
cmd:{ getMore: 16761306662, collection: "oplog.rs", maxTimeMS: 5000, term: 262, lastKnownCommittedOpTime: { ts: Timestamp 1486218283000|47, t: 262 } }. Last fetched optime (with hash): { ts: Timestamp 1486218285000|49, t: 262 }[3084471424447709631]. Restarts remaining: 3
```
```
> db.printReplicationInfo()
configured oplog size:   9458.8388671875MB
log length start to end: 1433730secs (398.26hrs)
oplog first event time:  Thu Jan 19 2017 19:25:06 GMT+0000 (UTC)
oplog last event time:   Sun Feb 05 2017 09:40:36 GMT+0000 (UTC)
now:                     Sun Feb 05 2017 09:40:36 GMT+0000 (UTC)
```
**Steps to reproduce the issue:**
1. You need to have ca. 10 Gb Database in Replica Set with 1 master and no secondaries.
2. Add new secondary member.
3. Init sync from master
3. After init sync you should have a replication lag. Sometimes this lag occurs after 2-3 days.

**Additional information you deem important (e.g. issue happens only occasionally):**
Discussion about this problem: https://jira.mongodb.org/browse/SERVER-19605
But this problem occurs by me only in  docker swarm mode (encrypted network)

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 105
 Running: 14
 Paused: 0
 Stopped: 91
Images: 35
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-9:2-2754765-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 28.99 GB
 Data Space Total: 107.4 GB
 Data Space Available: 78.39 GB
 Metadata Space Used: 60.11 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.087 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 32i1l88w4pr418gi1eepfo6ea
 Is Manager: false
 Node Address: xxx
 Manager Addresses:
  xxx:2377
  xxx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 4.7.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.76 GiB
Name: jupiter6
ID: DRHU:45KY:AU3X:UW5I:GUCI:PFTX:LWHT:7PRA:52KG:CO2K:XNHS:LO7E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
2 physical server with docker  1.13

**Comment by aboch** [comment]
Can you please add some more details about the setup.
Number of swarm manager/worker nodes.
How you create the overlay network, docker service, number of replicas.
Thanks.

**Comment by vingrad** [comment]
swarm manager: 2
Worker nodes: 3

worker node1 (physical): nginx, php etc, mongodb master
worker node2  (physical): mongodb with very big replication lag and many network timeouts
worker node3 (kvm):  mongodb with very big replication lag and many network timeouts

**How you create the overlay network**
>docker network create --driver overlay  --opt encrypted my-net

**How you create the docker service, number of replicas**
> docker service create --with-registry-auth ... --network my-net --constraint 'node.hostname==node1' ...
> docker service create --with-registry-auth ... --network my-net --constraint 'node.hostname==node2 ...

**Also, did you isolate the issue to the use of encrypted networks, it does not happen when encryption is off monitoring the system for few days ?**
no, may be this occurs without encryption too. I will try this.

**Comment by thaJeztah** [comment]
Unrelated to this issue, but I'd strongly recommend using either 1 or 3 managers in your setup; using two managers _doubles_ the chance you loose quorum, and loose control over your cluster. If one manager fails, your cluster becomes uncontrollable.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
