### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/

### ISSUE THREAD

**Issue by xinchrome** [moby/moby#30757]
Hi, everyone:

Docker failed when runing "RUN pip install flask", content of Docker file is as follows: 

FROM python:3.4
RUN mkdir /code
COPY app.py /code/app.py
WORKDIR /code
RUN pip install flask redis
CMD ['python', 'app.py']

When I run in the terminal : "$ sudo docker build -t fig_ex .", it shows:

Sending build context to Docker daemon 3.072 kB
Step 1 : FROM python:3.4
 ---> d87c6dbd17a7
Step 2 : RUN mkdir /code
 ---> Using cache
 ---> 4049bfe07335
Step 3 : COPY app.py /code/app.py
 ---> Using cache
 ---> bbe0353172b6
Step 4 : WORKDIR /code
 ---> Using cache
 ---> 2535608c604c
Step 5 : RUN pip install flask redis
 ---> Running in 4a49dee8c8b1
Collecting flask
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f88deec18>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f88dee2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f88dee908>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f88dd0978>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f8914d630>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Could not find a version that satisfies the requirement flask (from versions: )
No matching distribution found for flask
The command '/bin/sh -c pip install flask redis' returned a non-zero code: 1

I have restarted everything, error still occurs.
my docker version is 1.12.3.

Thank you !

**Comment by codingant007** [comment]
I am using 1.12.3 and facing the exact same issue.

**Comment by ay8-dev** [comment]
Same here (1.12.3)

**Comment by TimDorand** [comment]
# For Ubuntu users
You need to add new DNS addresses in the docker config

1. `sudo nano /lib/systemd/system/docker.service`
Add the dns after `ExecStar`. `--dns 10.252.252.252 --dns 10.253.253.253`
Should look like that:
`ExecStart=/usr/bin/dockerd -H fd:// --dns 10.252.252.252 --dns 10.253.253.253`

2. `systemctl daemon-reload`
3. `sudo service docker restart`
4. Should work

**Comment by xinchrome** [comment]
the methods above do not work ...

**Comment by fermenreq** [comment]
dont work ..

**Comment by fermenreq** [comment]
Hi everyone ! 

I'm working on Ubuntu 14.04 currently and it's not required to do the methods above. I think that can be some problems on Ubuntu 16.10 using docker. 

check it here : [http://pastebin.com/Kn2Z2xZi](http://pastebin.com/Kn2Z2xZi )

Regards

**Comment by ay8-dev** [comment]
Have you done _sudo killall -HUP dhclient_ after editing _/etc/dhcp/dhclient.conf_? It worked perfectly for me.

**Comment by campestrini** [comment]
Hi!
I'm facing the same problem.
I have tried the methods above, without success.

Ubuntu 16.04
Docker: 17.03.0-ce

**Comment by yudori** [comment]
Had the same problem (Ubuntu 14.04). This solution worked for me http://stackoverflow.com/a/41989423/3972515

**Comment by sibilkov** [comment]
Hi! (Why this issue in moby repo instead docker repo?)
Have the same problem on Centos7.

`Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f38995194a8>: Failed to establish a new connection: [Errno 101] Network unreachable',)': /simple/aiokafka/`

Tried to add google DNS addresses in my local config /etc/dhcp/dhclient.conf
Thied to add google DNS addresses in docker service and start it with --dns parameter.
It didnt help.

I didnt have this problem on my local VM which I use for tests with centos7.  When it works network packet detalisation from iptraf looks like:
on docker0 interface:
```
UDP (61 bytes) from 172.17.0.2:46453 to 8.8.8.8:53 on docker0
UDP (61 bytes) from 172.17.0.2:46453 to 8.8.8.8:53 on docker0 
UDP (165 bytes) from 8.8.8.8:53 to 172.17.0.2:46453 on docker0
UDP (213 bytes) from 8.8.8.8:53 to 172.17.0.2:46453 on docker0
```
on eth0:
```
UDP (61 bytes) from 192.168.0.11:46453 to 8.8.8.8:53 on docker0
UDP (61 bytes) from 192.168.0.11:46453 to 8.8.8.8:53 on docker0 
UDP (165 bytes) from 8.8.8.8:53 to 192.168.0.11:46453 on docker0
UDP (213 bytes) from 8.8.8.8:53 to 192.168.0.11:46453 on docker0
```

AND when it doesn't work i have the same result:
```
UDP (61 bytes) from 172.17.0.2:48874 to google-public-dns-a.google.com:domain
UDP (61 bytes) from 172.17.0.2:48874 to google-public-dns-a.google.com:domain 
UDP (165 bytes) from google-public-dns-a.google.com:domain to 172.17.0.2:48874  
UDP (213 bytes) from google-public-dns-a.google.com:domain to 172.17.0.2:48874
(On eth0 connection established too) 
```
**(This means I doesnt have any problems with dns)**
And docker makes many https connections 
```
172.17.0.2:47954                             =       3        180 S--- docker0  
│└151.101.0.223:https                          =       0          0 ---- docker0  
```
But doesn't download anything.
I tried to download something with wget and its didnt works too
```
Resolving  www.mydomain.ru ( www.mydomain.ru)... 188.188.188.188
Connecting to www.mydomain.ru |188.188.188.188|:80... failed: Connection timed out.
Retrying. 
```
My firewall has complex settings with synproxy, but nothing changes when I turn it off
If someone have any ideas about this, I will be very grateful if you answer (because I do not have any).

**Comment by thaJeztah** [comment]
This looks like an issue in you environment and (as mentioned), could be related to the DNS that is configured for your container;

```bash
$ docker build -t repro-30757 -<<'EOF'
FROM python:3.4
RUN pip install flask redis
EOF
 
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.4
3.4: Pulling from library/python
85b1f47fba49: Already exists
5409e9a7fa9e: Already exists
661393707836: Already exists
1bb98c08d57e: Pull complete
c842a08369e2: Pull complete
e639d6c3a797: Pull complete
2e0d93ba8849: Pull complete
9e4c4ef684d8: Pull complete
Digest: sha256:602a002f554d617e33f7d9cfe9cf3add9b067ae9a52b346d9c2739e2b04f1911
Status: Downloaded newer image for python:3.4
 ---> 9ff45ddb54e9
Step 2/2 : RUN pip install flask redis
 ---> Running in 84ec0cfea344
Collecting flask
  Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
Collecting redis
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
Collecting Werkzeug>=0.7 (from flask)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
Collecting click>=2.0 (from flask)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting Jinja2>=2.4 (from flask)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
Collecting itsdangerous>=0.21 (from flask)
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask)
  Downloading MarkupSafe-1.0.tar.gz
Building wheels for collected packages: itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for itsdangerous: started
  Running setup.py bdist_wheel for itsdangerous: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built itsdangerous MarkupSafe
Installing collected packages: Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, flask, redis
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 click-6.7 flask-0.12.2 itsdangerous-0.24 redis-2.10.6
 ---> 066e7628d835
Removing intermediate container 84ec0cfea344
Successfully built 066e7628d835
Successfully tagged repro-30757:latest
```

I'm closing this issue, because I don't think there's a bug here; if you are running into this issue, and think there's a bug, please open a new ticket, and provide the information that's requested in the [issue template](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md).
