### ISSUE TITLE
Service update may fail with "update out of sequence" error

### ISSUE THREAD

**Issue by cezarsa** [moby/moby#30794]
**Description**

Repeatedly calling `docker service update` may trigger an `update out of sequence` error. This seems to happen because the api call to service inspect (`GET /services/{id}`) returns an old `Version.Index` even after the successful return of previous a call to service update (`POST /services/{id}/update`).

**Steps to reproduce the issue:**
```
docker swarm init
docker service create --name test busybox tail -f /dev/null
while docker service update test --constraint-add "node.labels.a != b"; do true; done
```

**Describe the results you received:**

After some time repeatedly updating the service (~30s on my machine) the last command will fail with the error `Error response from daemon: rpc error: code = 2 desc = update out of sequence`.

**Describe the results you expected:**

I expected that successful calls to `POST /service/{id}/update` would guarantee that subsequent calls to `GET /service/{id}` returned an updated `Version.Index`. This seems not to be the case. I'm not sure if this behavior is intended or not, if this is working as expected I think a clarification in the API documentation would be nice.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Fri Jan 27 21:54:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Fri Jan 27 21:54:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
The problem also happens with `1.13.0` and `1.12.6`

**Output of `docker info`:**

```
$ docker info
Containers: 26
 Running: 4
 Paused: 0
 Stopped: 22
Images: 264
Server Version: 1.13.1-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 397
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: n2osx48m66gag48ggoyg1w1pc
 Is Manager: true
 ClusterID: 66490aoqoo9cdx00t5n95hw34
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.50.4
 Manager Addresses:
  192.168.50.4:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.915 GiB
Name: vagrant
ID: XXOL:4PPB:VZV3:W7ZD:QRDT:FY6D:L2WN:OI5T:3Z3I:HZS5:TI6Z:BXJN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 153
 System Time: 2017-02-07T17:31:31.46294919Z
 EventsListeners: 1
Username: cezarsa
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested on Vagrant + Virtualbox and also on Ubuntu 14.04 on private Cloudstack.

**Comment by cpuguy83** [comment]
I think this is intentional as the service API is asynchronous.
But ping @aaronlehmann

**Comment by aaronlehmann** [comment]
This is discussed in detail here: https://github.com/docker/swarmkit/issues/1379

I've tried very hard to push for fixing this by versioning the service spec separately from the service object (https://github.com/docker/swarmkit/pull/1392), but we were never able to reach a consensus on the fine details, so this hasn't moved forward.

**Comment by jmalloc** [comment]
This is a real problem for automation. Without getting into the details of the optimistic locking in the API, would it make sense for the CLI to (optionally) block after a successful update until the version it created becomes visible?

**Comment by osman-masood** [comment]
I have the same problem running on Ubuntu 16 (Linux kernel 4.4.0-93-generic), Docker version 17.06.2-ce, build cec0b72.

There are 100+ services in my docker-compose.yml, and I get this error after the 4th service is updated:
```
Updating service my-stack_process1 (id: 5en4bmfbo4ikkq2znwgftlhqk)
Updating service my-stack_process2 (id: i7gd2ygtk3xye3zxt8hsnu3la)
Updating service my-stack_process3 (id: l4jxbe9kxmszoxmulrw1dacsl)
Updating service my-stack_process4 (id: mos51805p7b5x9fzq1f8h59rs)
Error response from daemon: rpc error: code = 2 desc = update out of sequence
```

**Comment by prologic** [comment]
This is problematic too for [autodock-cron](https://github.com/prologic/autodock-cron) with usage of the API like this:

```#!go
package plugin

import (
	"context"
	"errors"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/filters"
	"github.com/docker/docker/api/types/swarm"
	"github.com/docker/docker/client"

	log "github.com/sirupsen/logrus"
)

func serviceUpdate(client *client.Client, name string, force bool) error {
	service, err := getService(client, name)
	if err != nil {
		log.Errorf("unable to get service %s: %s", name, err)
		return err
	}

	/*
		serviceSpec := swarm.ServiceSpec{
			Annotations: swarm.Annotations{
				Name: name,
			},
			TaskTemplate: swarm.TaskSpec{
				ContainerSpec: &swarm.ContainerSpec{
					Image: service.Spec.TaskTemplate.ContainerSpec.Image,
				},
			},
		}
	*/

	if force {
		// oldForceUpdate := service.Spec.TaskTemplate.ForceUpdate
		service.Spec.TaskTemplate.ForceUpdate++
	}

	_, err = client.ServiceUpdate(
		context.Background(),
		service.ID,
		swarm.Version{Index: service.Version.Index},
		//serviceSpec,
		service.Spec,
		types.ServiceUpdateOptions{QueryRegistry: false},
	)

	if err != nil {
		log.Errorf("error updating services %s: %s", name, err)
		return err
	}

	return nil
}

// getService queries the docker API for a service with the name as provided
// serviceName is the desired name
func getService(client *client.Client, name string) (swarm.Service, error) {
	args := filters.NewArgs(filters.Arg("name", name))
	services, err := client.ServiceList(context.Background(), types.ServiceListOptions{Filters: args})

	if services == nil || len(services) == 0 {
		return swarm.Service{}, errors.New("No matching service found for name " + name)
	}

	return services[0], err
}
```

Only work-around I can *think* of is to the `Version.Index` myself.

**Comment by tedivm** [comment]
Can confirm, this is still an issue.

**Comment by turbo** [comment]
Still an issue for us. Makes CI review deployments next to impossible without some nasty hacks.

**Comment by manziman** [comment]
Also having issues with this. We are writing a service management tool and are getting the following error whenever we try to call `ServiceUpdate`:
```
Error response from daemon: rpc error: code = Unknown desc = update out of sequence
```
Output of `docker version`:
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

I validated that the `ServiceSpec` is good. The only suspect I could come up with was the `Version` meta tag. I tried manually passing an arbitrary number larger than the current version to `ServiceUpdate`, only to get the same result. 

Upon inspecting the output of `docker service inspect` after manually running an update command, it appears that the new `Version` is automatically set to a random(?) higher number. If the docker server (apparently) sets the version automatically, why is `Version` a mandatory argument for `ServiceUpdate`?

Our current workaround is to simply kill the service and create a new one with the same name/updated configs...not exactly a great solution.

**Comment by cpuguy83** [comment]
@manziman It's a sequence number. When you do an update you need to specify the current version of the service. If the version of the service in swarm in swarm is different than the version of the service you passed in it causes an out of sequence error.

The reason for this is to ensure that two updates don't conflict with each other.
Once the update is completed the service gets a new version. This should only ever be generated by swarm.

**Comment by manziman** [comment]
@cpuguy83 Awesome thanks! I'll go try that out.

**Comment by harrisonturton** [comment]
@cpuguy83 How do you find the version of the service? I'm running into this issue with the Go SDK, and I can't find a way to pass in the correct version.

**Comment by cpuguy83** [comment]
@harrisonturton You'll need to inspect the service first.

**Comment by cpuguy83** [comment]
Proposing an update to the API doc here: https://github.com/moby/moby/pull/38040

**Comment by alexellis** [comment]
@aaronlehmann @cpuguy83 I have had this issue with using the API programatically from multiple calls within a short period of time. In this instance I want to programatically update the replica count from 0 to 1 as part of traffic-based auto-scaling.

The current solution I have in mind with input from @stefanprodan is to try to scale, then if there is an error thrown check the state to see if the desired state is > 0 replicas (exit condition) or to loop several times trying again.

What would you suggest? 

This is the routine for context: https://github.com/openfaas/faas/blob/master/gateway/scaling/function_scaler.go#L62

**Comment by ZivotJeKrasny** [comment]
> Same issue happens, sometimes, when executing the following command while the stack and its services are active (i.e updating them because a new image has been pulled):
> 
> ```shell
> #!/usr/bin/env bash
> docker stack deploy ourapp --with-registry-auth --compose-file=docker-compose.yml
> ```
> 
> Two global services, five replicated services.
> 
> ```
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 17.10
> Release:	17.10
> Codename:	artful
> ```
> 
> #### Output of `docker version`
> ```
> Client:
>  Version:      18.03.1-ce
>  API version:  1.37
>  Go version:   go1.9.5
>  Git commit:   9ee9f40
>  Built:        Thu Apr 26 07:17:38 2018
>  OS/Arch:      linux/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:15:45 2018
>   OS/Arch:      linux/amd64
>   Experimental: false
> ```
> 
> #### Output of `docker info`
> ```
> Containers: 27
>  Running: 24
>  Paused: 0
>  Stopped: 3
> Images: 11
> Server Version: 18.03.1-ce
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 160
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: active
>  NodeID: jejb6my7n50ulnilktgd2fxof
>  Is Manager: true
>  ClusterID: 0yus20uq607uzugzqbv9a1vzr
>  Managers: 1
>  Nodes: 1
>  Orchestration:
>   Task History Retention Limit: 5
>  Raft:
>   Snapshot Interval: 10000
>   Number of Old Snapshots to Retain: 0
>   Heartbeat Tick: 1
>   Election Tick: 10
>  Dispatcher:
>   Heartbeat Period: 5 seconds
>  CA Configuration:
>   Expiry Duration: 3 months
>   Force Rotate: 0
>  Autolock Managers: false
>  Root Rotation In Progress: false
>  Node Address: 192.168.2.102
>  Manager Addresses:
>   192.168.2.102:2377
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.13.0-41-generic
> Operating System: Ubuntu 17.10
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 23.54GiB
> Name: linuxcompany
> ID: FLM4:OCTS:BWQR:ZLRQ:HVGG:VBSW:O5NE:IA2W:4Z6T:SS47:4BSE:A6ZT
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Username: ourcompany
> Registry: https://index.docker.io/v1/
> Labels:
>  provider=generic
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> ```

I am having the same issue. Is there any solution/workaround except remove the stack and create it again?

```
docker version 
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by misaon** [comment]
+1

**Comment by rcstanciu** [comment]
+1
