### ISSUE TITLE
docker-compose not working on windows when node app is listening on localhost

### ISSUE THREAD

**Issue by mr-e-** [moby/moby#30805]
Took me a while to track this one down. I have a node.js app which is using hapi.js to create an httpserver, which listens on localhost. App works fine if I run locally OR if I run docker using 
"docker run -p 4000:4000 api"

However, if I use docker-compose the app is not able to connect, I receive a no response from server error. If I use the same docker-compose file on linux, it works. 

docker-compose.yml looks like this:

`api:
  build: .
  ports: 
    - "4000:4000"`

I found I was able to resolve this issue by having the underlying app listen on 0.0.0.0 instead of localhost. I was then able to browse localhost:4000 in the browser and the app worked fine. Now I don't want to have to change my underlying apps bindings just to use docker on windows, and I am having a similiar issue with a caddy docker container so is there something else obvious I am missing here?

**Comment by sunshineo** [comment]
@mr-e- Could you rename the title? It is not for just windows. It's the same on Linux. I have something perfectly working. I put it in docker-compose, it complains that it cannot find localhost
```
mariadb-connect_1  | java.net.UnknownHostException: mariadb-connect: mariadb-connect: Name or service not known
mariadb-connect_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
```
Above is Java's way of complaining that it cannot resolve localhost.
It works very well if I do not put it in docker-compose and start it myself.
It works very well if I downgrade to docker 1.12 from 1.13

**Comment by ripcurld0** [comment]
@sunshineo @mr-e- 
I might be wrong, but why can't you bind your app to 0.0.0.0:4000?
Binding to 127.0.0.1:4000 won't receive requests from remote machines but only from the local one.

**Comment by mr-e-** [comment]
When I say I am binding to localhost I mean my app http-server is hosting on localhost... example:

https://hapijs.com/tutorials
const server = new Hapi.Server();
server.connection({ port: 3000, host: 'localhost' });

If I change the host to 0.0.0.0 it works, yet if I run the exact same code on a linux machine it works fine with localhost. I am also having the same issue using the caddy docker here: https://github.com/abiosoft/caddy-docker. So the real problem is that I cannot always change the code I am hosting inside the container so updating my code to 0.0.0.0 does not seem like a feasible solution and won't help me in terms of using caddy. Also, if I use docker run instead of docker-compose, it works fine on windows. Why would there be any differences here?

**Comment by mr-e-** [comment]
Another note: The web browser behaves exactly the same as if I do docker run but do not provide a port. 

Example:

"docker run caddy" <- does not work (Receive This site can’t be reached,localhost refused to connect. in the browser.
"docker-compose up" <- does not work (Receive This site can’t be reached,localhost refused to connect. in the browser.

docker run -p 2015:2015 <- works

docker-compose.yml
version: '2'

services:
    caddydata:
        image: ubuntu:latest
        volumes:
            - /var/lib/caddy/data

    caddy:
        build: .
        volumes_from:
            - caddydata
        network_mode: "host"
        ports:
            - "2015:2015"
            - "80:80"
            - "443:443"

**Comment by ripcurld0** [comment]
@mr-e- thanks for these details.

However, can you also specify what addresses you put at the URL bar in the browser to connect to the servers running inside the containers.

Moreover, can you provide more details about how you're doing this in your Digital Ocean droplet?

Thanks.

**Comment by mr-e-** [comment]
I have tried both browsing with "localhost:2015" || "localhost:4000" and I have also tried "127.0.0.1:2015" || "127.0.0.1:4000". Neither work through docker-compose. 

When I try it on my droplet I access it through the droplets [ip]:[2015/4000] and it just works.

**Comment by ripcurld0** [comment]
OK so let me see if I got it right.
Specifying the `-p` flag in the `docker run` command allows you to browse to http://localhost:2015.
However, even though you specify this port in the `docker-compose.yml` file, running `docker-compose up` doesn't expose that port to the host and browsing to that address fails.

Is that it?

**Comment by mr-e-** [comment]
Yes.

**Comment by mr-e-** [comment]
Any further update on this?

**Comment by ripcurld0** [comment]
Could it be related to this https://github.com/docker/docker-py/issues/1451 ?
Anyway, I don't have Windows to attempt reproducing this.
I will let the guys at Microsoft provide some answers, though.

**Comment by friism** [comment]
@mr-e- I don't think Docker can help if your app is listening on the loopback interface - it'll have to listen on public interface.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
