### ISSUE TITLE
Network issue when linking containers

### ISSUE THREAD

**Issue by plus500s** [moby/moby#30821]
**Description**

Networking stops to work after launching new container. The case basically is that: I have 2 containers: webserver and database (postgresql) linked to webserver. Whenever I run a 3rd container and link it to db one, both containers become unable to connect to database. Ping is working tho. The most interesting thing is that running 

`docker exec -it postgres-server apt-get update` solves the problem! after running the `apt-get update` both webserver and the 3rd container become able to connect to postgresql. Can someone explain me this? How can I prevent this from happening?

**Steps to reproduce the issue:**
1. Run postgres container
2. Run 2nd container and link it to postgres
2. Run 3nd container and link it to postgres

**Describe the results you received:**

Both containers can access postgres normally

**Describe the results you expected:**
Connection breaks after linking a container (works for any subsequent containers). Tho, apt-get update on the postgres container restores the connections. It breaks again after re-launching 2nd or 3rd container 

**Output of `docker version`:**

```
 ✘ ⚡ root@server  /home/nginx  docker -v
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
 root@server  /home/nginx  docker info
Containers: 30
 Running: 16
 Paused: 0
 Stopped: 14
Images: 108
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 584
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.49 GiB
Name: server
ID: VC6W:KUHD:7BZ4:H7EV:VTDY:UNGT:D4IN:RE6U:FDRG:UBW2:Q7LN:FO2C
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux server 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
regular physical server

**Comment by thaJeztah** [comment]
I'm not able to reprouce this. I used these steps;

Create a "database" container, and link two containers to it

```bash
docker run -d --name database nginx:alpine
docker run -dit --name one --link database alpine sh -c 'apk add --no-cache curl && watch curl database'
docker run -dit --name two --link database alpine sh -c 'apk add --no-cache curl && watch curl database'
```

Link a third container;

```bash
docker run -dit --name three --link database alpine sh -c 'apk add --no-cache curl && watch curl database'
```

After that, check logs of all containers, and confirm that they're still able to connect;

```
docker logs -f one

Every 2s: curl database                                     2017-03-21 13:05:08

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
^C⏎

docker logs -f two

Every 2s: curl database                                     2017-03-21 13:05:08

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
^C⏎
```



Having said the above, I strongly discourage using the `--link` feature on the default ("bridge") network. The `--link` feature on the default network is a legacy feature.

The legacy links option has a lot of downsides. One of those is that links are uni-directional. Another issue is that a linked container cannot be replaced with a different container, as doing so breaks the link (which cannot be re-established); forcing you to re-create all linked containers.

I recommend using a custom network, and attach your containers to that network. When using a custom networks, containers are able to connect to other containers by their _name_. A  `--link` option is still available for custom networks, but works by creating a DNS-based "container scoped" alias for the "linked" container.

For example, create a network;

```bash
$ docker network create mynetwork
```

Create three containers, all of them connected to the network you created;

```bash
$ docker run -d --name=database --network=mynetwork nginx:alpine
$ docker run -dit --name=one --network=mynetwork busybox sh -c 'ping database'
$ docker run -dit --name=two --network=mynetwork busybox sh -c 'ping database'
$ docker run -dit --name=three --network=mynetwork busybox sh -c 'ping database'
```

Confirm that the containers are able to communicate;

```bash
$ docker logs -f one
PING database (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.078 ms
64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.083 ms
64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.116 ms
64 bytes from 172.19.0.2: seq=3 ttl=64 time=0.085 ms
64 bytes from 172.19.0.2: seq=4 ttl=64 time=0.082 ms
64 bytes from 172.19.0.2: seq=5 ttl=64 time=0.087 ms
64 bytes from 172.19.0.2: seq=6 ttl=64 time=0.106 ms
```

You can even remove the "database" container, and replace it with a new container, and after it's started, all other containers will be able to connect again. For fun; replace the `nginx` container with an Apache (httpd) container;

```bash
$ docker stop database
$ docker rm database
$ docker run -d --name=database --network=mynetwork httpd
```

```bash
$ docker logs -f one
64 bytes from 172.19.0.2: seq=93 ttl=64 time=0.085 ms
64 bytes from 172.19.0.2: seq=94 ttl=64 time=0.087 ms

(here some pings went missing, because the container was gone)

64 bytes from 172.19.0.2: seq=123 ttl=64 time=0.124 ms
64 bytes from 172.19.0.2: seq=124 ttl=64 time=0.081 ms
```

You can read more about docker networks here; https://docs.docker.com/engine/tutorials/networkingcontainers/

**Comment by thaJeztah** [comment]
Let me know if this resolves your use case, or if you have other ways to reproduce your original issue

**Comment by thaJeztah** [comment]
closing because this went stale
