### ISSUE TITLE
[Feature request] `docker network ls --filter dangling=true|false`

### ISSUE THREAD

**Issue by albers** [moby/moby#30825]
We have
- `docker image ls --filter dangling=true|false`
- `docker volume ls --filter dangling=true|false`

For cleanup purposes, it would be helpful to find unused networks with `docker network ls --filter dangling=true`.
Related: Dry run mode for prune commands #30623

**Comment by KarthikNayak** [comment]
Working on this, #dibs

**Comment by yxliang01** [comment]
@KarthikNayak How is this going? Since it has been 1.5 yr from your last comment. Thanks.

**Comment by KarthikNayak** [comment]
@yxliang01 Sorry for the lack of updates here, I'm picking this up again.

**Comment by yxliang01** [comment]
@KarthikNayak Great! Thanks & looking forward to that! :)

**Comment by yxliang01** [comment]
@KarthikNayak Thanks so much for your contributions! :)
