### ISSUE TITLE
Link plugin v2 to container

### ISSUE THREAD

**Issue by nkkodkani** [moby/moby#30857]
**Description**

I am trying to port my volume plugin to v2 plugin architecture (Docker 1.13). Currently, let say I have container A and B, where A=deals with extended volume plugin and B=is the backend
A links to B to make REST API calls. So, I used to "link" B with A. Now with the introduction to v2 plugin, docker plugin CLI is quite different from an earlier version.
I am planning to port my container A (extends vol-plugin) to v2 plugin infrastructure where I am using config.json to start the plugin.

I am not sure now how to "link" the v2 plugin to the container B through config.json.
Is this kind of usecase supported in v2 plugin?
 I couldn't see any option specified atleast in the docs or probably I missed it.

**Output of `docker version`:**

```
[root]# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@punr710vm32 plugin]#
```
**Output of `docker info`:**

```
[root]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local veritas
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 23.37 GiB
Name: XYZ
ID: K2UQ:UIWI:CFU3:CH7P:VZUL:DW3J:SYFE:5IZN:Z7AW:IUWI:2ZD5:WRYV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nkodkani
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
[root@punr710vm32 plugin]#

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
This is not supported.
I'm not sure it should be, seems overly complicated for a plugin.

**Comment by mtneug** [comment]
@cpuguy83  IMHO this makes total sense. Think, for example, about integrations with secret stores like Vault or Keywhiz. I would love to run such a data store as a container and put the plugin container within the same (overlay) network such that it could use Docker's integrated DNS server.
