### ISSUE TITLE
stop healthcheck after start all container.

### ISSUE THREAD

**Issue by mazankod** [moby/moby#30860]
Hello.
How i can stop healthcheck after start all containers in docker-compose? If that ability doesn't exist, maybe it can be add at next release?

**Comment by gianarb** [comment]
Hello @mazankod , at the moment there are not ways to disable Healthcheck runtime. 
I think that it's a useful feature for debugging and troubleshooting.

**Comment by mazankod** [comment]
Thank you for answer. 
Maybe it can be realise like option at featured release? Because for some project we don't need do healthcheck after all containers already started.

**Comment by cpuguy83** [comment]
I don't think this makes sense and is a mis-use of the healthcheck.
There is discussion on providing a "ready check" separately from healthcheck, which seems more closely aligned with what you are looking for here.

**Comment by mazankod** [comment]
@cpuguy83 yes you right.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
