### ISSUE TITLE
Feature Request: docker cp -a/-p to keep the file ownership/permissions

### ISSUE THREAD

**Issue by danweller18** [moby/moby#30877]
**Description**
Would like to copy a file from inside of a docker container to the outside host machine while maintaining the file permissions/ownership of the file. The user who owns the file in docker does not exist on the host machine and the file will be moved to another host machine. However I do not have sudo privilege to modify the ownership and file permissons on the host machines.

I am thinking it would be an equivalent linux command like `cp -a` or `cp -p`.

**Comment by thaJeztah** [comment]
Looks like this is what https://github.com/docker/docker/pull/28923 is working on (see https://github.com/docker/docker/pull/28923#issuecomment-267420321)

**Comment by danweller18** [comment]
Yes I think it covers the ownership part. However I am unclear if it would preserve the file permission attributes. Sure the permissions can be changed later on if the owner is correct but I think it makes more sense to preserve both.

**Comment by erikh** [comment]
It should already preserve them, but i will verify. I think there's a test for it though, check the PR #28923's patch set.

**Comment by ripcurld0** [comment]
@thaJeztah seems like this issue can be closed.

**Comment by thaJeztah** [comment]
Yes, looks like this can be closed (documentation changes are still needed if I look at the linked PR)
