### ISSUE TITLE
command output: aliasing documentation and 

### ISSUE THREAD

**Issue by mbana** [moby/moby#30881]
from my personal experience using the tooling. it would be great if these were resolved. please, do not take these as criticism.

#### output:

i  wonder how everyone deals with the docker ouput, in particular the core team. i suspect, i could be wrong, that people are handcrafting scripts for common operations.

dealing with the ouput in a *unix env could be easier:

* requires extra work when using common tools, e.g., `docker history <id>` -> `SIZE` contains spaces so `sort -h` doesn't handle it that well. one needs to do deal with Go templates.
* some commands don't take formatting options so they're harder to deal with, e.g., `docker history`.
* is there a standard delimiter that is always used for all the commands? quick test: remove just the `COMMENT` column, note the space(s) in the fields themselves.

```sh
$ docker history golang_1.4-alpine:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
f687c7a9c8fd        22 hours ago        /bin/sh -c echo 'hello world from' 'golang...   0 B                 
0deea0c51a1c        11 months ago       /bin/sh -c #(nop) WORKDIR /go                   0 B                 
<missing>           11 months ago       /bin/sh -c mkdir -p "$GOPATH/src" "$GOPATH...   0 B                 
<missing>           11 months ago       /bin/sh -c #(nop) ENV PATH=/go/bin:/usr/lo...   0 B                 
<missing>           11 months ago       /bin/sh -c #(nop) ENV GOPATH=/go                0 B                 
<missing>           11 months ago       /bin/sh -c set -ex  && apk add --no-cache ...   138 MB              
<missing>           11 months ago       /bin/sh -c #(nop) ENV GOLANG_SRC_SHA1=486d...   0 B                 
<missing>           11 months ago       /bin/sh -c #(nop) ENV GOLANG_SRC_URL=https...   0 B                 
<missing>           11 months ago       /bin/sh -c #(nop) ENV GOLANG_VERSION=1.4.3      0 B                 
<missing>           11 months ago       /bin/sh -c #(nop) ADD file:0f9cfb2e848f093...   4.79 MB             
```

what i'm trying to get at is, it would nice if the output played nicely with the tools folks are familiar with, and some consistent behaviour in the flags commands take (some take `--format` other don't).

#### aliasing

the alias, specifically, at the bottom is confusing, e.g., https://docs.docker.com/engine/reference/commandline/images/ says `docker images` -> ` docker image ls`:

* why not then just redirect to the page?
* the alias should be at the top of the page, it is less confusing that way.

#### links to docs

it would _really_ nice to have links to the docs directly (not the alias) available on the command line. something like below, or whatever fits your bill.

```sh
$ docker images --help

https://docs.docker.com/engine/reference/commandline/image_ls/

Usage:	docker images [OPTIONS] [REPOSITORY[:TAG]]

...
```

---

```sh
$ docker version
```

```sh
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```sh
$ docker info
```

```sh
Containers: 153
 Running: 0
 Paused: 0
 Stopped: 153
Images: 1589
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1290
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: NRXU:ZFNJ:3AC2:WVYL:UODL:44GO:E7AA:AFWL:22FC:FJYR:URTX:SV2N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-02-09T19:26:55.917920388Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: mohamedbana
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by AkihiroSuda** [comment]
> * requires extra work when using common tools, e.g., docker history <id> -> SIZE contains spaces so sort -h doesn't handle it that well. one needs to do deal with Go templates.

Recently fixed in the master https://github.com/docker/docker/pull/30790

> * some commands don't take formatting options so they're harder to deal with, e.g., docker history.

Tracked in https://github.com/docker/docker/issues/30431

> links to docs

SGTM 👍

**Comment by AkihiroSuda** [comment]
If this is still an issue, could you reopen at https://github.com/docker/cli ?
