### ISSUE TITLE
Docker Swarm Mode-If --reserve-cpu  and --reserve-memory more than the --limit-cpu  and  --limit-memory respectively service should not get created, but it does

### ISSUE THREAD

**Issue by Deepak-Vohra** [moby/moby#30882]
**Description**

In Docker Swarm Mode if `--reserve-cpu`  and `--reserve-memory ` are more than the `--limit-cpu`  and  `--limit-memory` respectively service should not get created, but it does. 

**Steps to reproduce the issue:**
1. Create a service with the following command:
```
docker service create \
  --env MYSQL_ROOT_PASSWORD='mysql'\
  --replicas 1 \
  --name mysql \
  --reserve-cpu 1 --limit-cpu .5 --reserve-memory  256mb --limit-memory 128mb \
 mysql
```

2. List the service with `docker service ls`. 

**Describe the results you received:**

The service gets listed with 3 replicas.

```
core@ip-10-0-0-35 ~ $ docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
auo45dsaqkrk  mysql  3/3       mysql  
```

Service is listed as Completed with `docker service inspect mysql`.

```
core@ip-10-0-0-35 ~ $ docker service inspect mysql
[
    {
        "ID": "auo45dsaqkrkr003voji67cpg",
        "Version": {
            "Index": 119
        },
        "CreatedAt": "2017-02-09T19:03:30.886722553Z",
        "UpdatedAt": "2017-02-09T19:08:24.829974577Z",
        "Spec": {
            "Name": "mysql",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "mysql",
                    "Env": [
                        "MYSQL_ROOT_PASSWORD=mysql"
                    ]
                },
                "Resources": {
                    "Limits": {
                        "NanoCPUs": 500000000,
                        "MemoryBytes": 134217728
                    },
                    "Reservations": {
                        "NanoCPUs": 1000000000,
                        "MemoryBytes": 268435456
                    }
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 3
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
```

Service tasks do not get started stably, but keep getting started and shutdown.

```
core@ip-10-0-0-35 ~ $ docker service ps mysql
ID                         NAME         IMAGE  NODE                        DESIRED STATE  CURRENT STATE              ERROR
eoh85ydmw1eiufszsvhzp6qux  mysql.1      mysql  ip-10-0-0-35.ec2.internal   Running        Running 28 seconds ago     
3bcd2q6ykbic4fr8ht54wefqv   \_ mysql.1  mysql  ip-10-0-0-35.ec2.internal   Shutdown       Failed 34 seconds ago      "task: non-zero exit (1)"
cwn5sd4nev9yiyw3fs7hwwru6   \_ mysql.1  mysql  ip-10-0-0-35.ec2.internal   Shutdown       Failed about a minute ago  "task: non-zero exit (1)"
29z6kzrvva38r3u7eqkybogg1   \_ mysql.1  mysql  ip-10-0-0-35.ec2.internal   Shutdown       Failed 2 minutes ago       "task: non-zero exit (1)"
2pif8acknqe805sbf15cm0p5b   \_ mysql.1  mysql  ip-10-0-0-35.ec2.internal   Shutdown       Failed 2 minutes ago       "task: non-zero exit (1)"
28xesm7f14oq7l4du48sl7se2  mysql.2      mysql  ip-10-0-0-151.ec2.internal  Ready          Ready 3 seconds ago        
0wkztqf0p4vhb5u0hhp1dk0tv   \_ mysql.2  mysql  ip-10-0-0-151.ec2.internal  Shutdown       Failed 4 seconds ago       "task: non-zero exit (1)"
5654ep0r0dc0bt0wxfmumz2p9   \_ mysql.2  mysql  ip-10-0-0-151.ec2.internal  Shutdown       Failed 48 seconds ago      "task: non-zero exit (1)"
9qdgbaoclaavx3xyf7snxrqsx   \_ mysql.2  mysql  ip-10-0-0-151.ec2.internal  Shutdown       Failed about a minute ago  "task: non-zero exit (1)"
e92rywiuhta16x9fklbyt9wsa   \_ mysql.2  mysql  ip-10-0-0-151.ec2.internal  Shutdown       Failed 2 minutes ago       "task: non-zero exit (1)"
1lkutagd2q8owxir45s3v5t13  mysql.3      mysql  ip-10-0-0-28.ec2.internal   Ready          Ready 1 seconds ago        
0ijsfgq4lh3txy3zq8x5m7wub   \_ mysql.3  mysql  ip-10-0-0-28.ec2.internal   Shutdown       Failed 1 seconds ago       "task: non-zero exit (1)"
dmzqxqhl8yn3tp4dy67nvxspx   \_ mysql.3  mysql  ip-10-0-0-28.ec2.internal   Shutdown       Failed 46 seconds ago      "task: non-zero exit (1)"
cvdvz0r19ldoqup8q2u2fslig   \_ mysql.3  mysql  ip-10-0-0-28.ec2.internal   Shutdown       Failed about a minute ago  "task: non-zero exit (1)"
clf4tttizwgiue21k3i772u0t   \_ mysql.3  mysql  ip-10-0-0-28.ec2.internal   Shutdown       Failed 2 minutes ago       "task: non-zero exit (1)"
```

The containers also keep getting started and shutdown.

**Describe the results you expected:**

The service should not get created and indicate a failure. The service tasks and containers  not getting   started stably is expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
core@ip-10-0-0-35 ~ $ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Thu Feb  2 02:27:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Thu Feb  2 02:27:34 2017
 OS/Arch:      linux/amd64
core@ip-10-0-0-35 ~ $ 


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CoreOS instances on EC2. Swarm cluster with 1 manager and 2 worker nodes.

**Comment by thaJeztah** [comment]
I'm not able to reproduce the problem on docker 17.03, using both the `mysql` example you provided, and a simple `nginx` service;

```
$ docker service create \
  --name foo \
  --reserve-cpu 1 --limit-cpu .5 --reserve-memory  256mb --limit-memory 128mb \
 nginx:alpine
```

Perhaps I misunderstood your description, and you think it should be prevented (even though it doesn't make services fail). While I agree that reserving more than is actually _limited_ to, isn't very useful, I don't think it should be _prevented_

Are you still able to reproduce this on the current version of docker? (17.03 at time of writing)?

**Comment by dvohra** [comment]
Tested on docker 17.03 the `mysql `example and the `nginx` example. Even though the `mysql `service gets created initially, it fails. 

_Perhaps I misunderstood your description, and you think it should be prevented (even though it doesn't make services fail)._

It _doesn't_ make `mysql` service fail or it  _does_? Because the `mysql` service does fail. Preventing would be suitable so that services with reserve resources exceeding limits do not get created. 

The `nginx` service does not fail. The `docker service create` commands are the same as posted previously:

```
docker service create \
  --name foo \
  --reserve-cpu 1 --limit-cpu .5 --reserve-memory  256mb --limit-memory 
128mb \
 nginx:alpine

docker service create \
  --env MYSQL_ROOT_PASSWORD='mysql'\
  --replicas 1 \
  --name mysql \
  --reserve-cpu 1 --limit-cpu .5 --reserve-memory  256mb --limit-memory 
128mb \
 mysql

```

**Comment by thaJeztah** [comment]
For me, the mysql service started, and afaics, it remained running. 128MB may be low though, so possibly it just went over that limit and failed? Does it work if you remove the reservation?

**Comment by dvohra** [comment]
The only limiting factor without the reserves and limits being verified is the node capacity. But, how could 256 MB be reserved if the limit is 128mb?  How are the limits settings being used?

For your information, used the Docker for AWS.
https://docs.docker.com/docker-for-aws/

_For me, the mysql service started, and afaics, it remained running._ 
Did the service remain running for at least 4-5 minutes? The service does keep running for 1-2 minutes but fails. Not retested yet. But, what is to be re-tested? That the limits set have no bearing on the resource reserved?

**Comment by dvohra** [comment]
`128MB may be low though, so possibly it just went over that limit and failed? `

But, the limit is not being used for any setting, or should the preceding statement be 
256MB may be low though for `mysql `but not for `nginx`, so possibly it just went over that limit and failed?

**Comment by dvohra** [comment]
With `nginx` and `mysql` as test images the following is noted with both `nginx` and `mysql`.

-Not setting the reserves (whether limits are set or not and whether limits exceed node capacity) schedules the service task.

The following is noted with `nginx` only.

-If reserve exceeds the limit but is within the node capacity the service task gets scheduled and does not fail.
-If reserve exceeds the limit and exceeds  the node capacity the service task is put in Pending.

The following is noted for `mysql` only.

-A consistent scheduling is not noted. As an example, the following service gets scheduled without service task failing.

```
docker service create \
  --env MYSQL_ROOT_PASSWORD='mysql'\
  --replicas 1 \
  --name mysql \
  --reserve-cpu .5 --limit-cpu .5 --reserve-memory  256mb --limit-memory 256mb \
 mysql
```

The following services gets scheduled but fail.

```
docker service create \
  --env MYSQL_ROOT_PASSWORD='mysql'\
  --replicas 1 \
  --name mysql \
  --reserve-cpu .5  --limit-cpu .4  --reserve-memory  256mb --limit-memory 128mb \
 mysql


docker service create \
  --env MYSQL_ROOT_PASSWORD='mysql'\
  --replicas 1 \
  --name mysql \
  --reserve-cpu .5  --reserve-memory  256mb --limit-memory 128mb \
 mysql
```

**Comment by dvohra** [comment]
_the mysql service started, and afaics, it remained running._ 

What OS and Docker configuration is used? Is resource reserves < resource limits implementation supposed to be platform  specific. Does the `mysql` service stay running on Docker for AWS also?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
