### ISSUE TITLE
docker logs should be able to provide some amount of logs regardless of 3rd party logging driver

### ISSUE THREAD

**Issue by dhiltgen** [moby/moby#30887]
**Description**

When users configure a 3rd party logging driver, typically `docker logs` is unable to report any log output from existing containers.  This makes it difficult to troubleshoot problems without having to go into the weeds of the specific 3rd party logging system to extract the logs.

We should find some way to expose some amount of historical logging information from containers regardless of what the logging configuration is, so we can rely on `docker logs` producing output.

Depending on the chosen model, we might want to expose a knob the user can tweak to control how much logging history is stored when a 3rd party driver that doesn't support read.

**Comment by thaJeztah** [comment]
Related discussion for AWS logs; https://github.com/docker/docker/issues/30691

**Comment by dperny** [comment]
Relevant to my interests but outside of my skillset and priorities.

**Comment by jwulf** [comment]
A Docker log driver middleware driver would be useful - then you could connect multiple drivers to it.

**Comment by jwulf** [comment]
Doesn't look hard to write a logging driver that combines json-log with whatever else you are using: https://github.com/moby/moby/tree/master/daemon/logger

Here's a lower orbit way - an alpine container uses json-log and listens for GELF logging from your containers, and prints it to stdout. And it forwards your log to whatever log consumer you use.

I think I'll do that first. I did something like that previously: https://github.com/jwulf/Gandelf

**Comment by BarnumD** [comment]
Agree. We should either be able to have logging go to multiple logging drivers or it should `|tee` (as on linux) both the primary json driver a secondary driver.

**Comment by dbsanfte** [comment]
Glaring omission here, using a logging driver should never break `docker logs`.

**Comment by cpuguy83** [comment]
The latest Docker EE engine (18.03.1-ee-1) supports `docker logs` for any selected logging driver, btw.

**Comment by rajkumar49** [comment]
hi @cpuguy83 , i am unable to use AWS Logs driver with Docker version 18.03.1-ce, build 9ee9f40. 
**getting ERROR :** 
ubuntu@ip-172-xxxx:~$ docker inspect 7cf86xxxxx       | grep log
                "Type": "**awslogs**",
                    "awslogs-group": "test-log-group",
                    "awslogs-region": "us-east-1"
ubuntu@ip-172-xxxx:~$ docker logs 7cf861xxxxx        
**Error response from daemon: configured logging driver does not support reading**

also, i have AWS IAM policy which allows the user account to put logs in the available log group in AWS Cloudwatch.
please help

**Comment by cpuguy83** [comment]
@rajkumar49 The feature is only available in docker-ee, no docker-ce.

**Comment by hinorashi** [comment]
hail docker-ee! 🦝

**Comment by thaJeztah** [comment]
The docker-er feature was open-sourced in https://github.com/moby/moby/pull/40543, which will be in the next release.

Closing this issue

**Comment by kluisi** [comment]
@thaJeztah Thanks for your work in getting this open sourced for docker-ce. We really rely on this function and were wondering if there were any plans for the next release yet (I assume this fix will be 19.03.14).

**Comment by cpuguy83** [comment]
@kluisi No, this will be in Docker 20.

**Comment by CodePint** [comment]
@kluisi 

I am not sure what your use case is, but there is a beta build available which released last month: ```docker-20.10.0-beta1.tgz```
I obviously wouldn't recommend this for production use, but i'm happily using it with docker logs and fluentd log driver for my development machine and personal projects without issue (painless installation, no configuration changes).

Could be useful to you for development/testing purposes if nothing else? 

Test

> Test

> In preparation for a new year-month release, a branch is created from the master branch with format YY.mm when the milestones desired by Docker for the release have achieved feature-complete. Pre-releases such as betas and release candidates are conducted from their respective release branches. Patch releases and the corresponding pre-releases are performed from within the corresponding release branch.

Binaries: https://download.docker.com/linux/static/test/x86_64/docker-20.10.0-beta1.tgz
Binary install guide: https://docs.docker.com/engine/install/binaries/
