### ISSUE TITLE
Socket file issue inside docker

### ISSUE THREAD

**Issue by mitzkia** [moby/moby#30908]
**Description**

I have a small Dockerfile and a script.sh file. I found an "interesting" issue when I build the Dockerfile. Briefly: inside Dockerfile the script.sh creates a socket file, and after it I check the type of the file, if it is a socket or not. First I check it from the script.sh file (from where it created), it shows it is a socket. After that I check it again with the same command, but from the Dockerfile and it shows it is a regular file. I have also tried with other base image (ubuntu:latest), and the result was the same. Can it be a bug, or I miss something? Thanks a lot. I have already added this issue to stackoverflow, but did not get answered yet. 
http://stackoverflow.com/questions/40635032/socket-file-issue-inside-docker

**Steps to reproduce the issue:**
Build the following minimal Dockerfile:

Dockerfile content

```
FROM centos:latest
COPY script.sh /script.sh
RUN ./script.sh
RUN ls -la /tmp/somesocket
```

script.sh file content

```
#!/bin/bash -x
python -c 'import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('\''/tmp/somesocket'\'')'
ls -la /tmp/somesocket
```

Produce the following build log:

```
$ docker build --no-cache=True -t centos_socket_test . -f Dockerfile
Sending build context to Docker daemon 3.072 kB
Step 1/4 : FROM centos:latest
 ---> 67591570dd29
Step 2/4 : COPY script.sh /script.sh
 ---> 804be4da26b3
Removing intermediate container eb0d0f59fb1e
Step 3/4 : RUN ./script.sh
 ---> Running in 3a203ca656af
+ python -c 'import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('\''/tmp/somesocket'\'')'
+ ls -la /tmp/somesocket
srwxr-xr-x 1 root root 0 Feb 10 10:06 /tmp/somesocket
 ---> 9b5a6a5d2f4e
Removing intermediate container 3a203ca656af
Step 4/4 : RUN ls -la /tmp/somesocket
 ---> Running in 99fda3c14eed
-rwxr-xr-x 1 root root 0 Feb 10 10:06 /tmp/somesocket
 ---> 4da3f5191529
Removing intermediate container 99fda3c14eed
Successfully built 4da3f5191529
```

**Describe the results you expected:**
My expected result would be to display the same result for `/tmp/somesocket` -> the file type is  socket, not a regural file.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:57:21 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 123
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: tristram
ID: 37DR:ACV4:RISO:VRBA:47BJ:UNBV:CFWJ:FRDL:O2A6:PSOT:N5HK:LJG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanks a lot.

**Comment by justincormack** [comment]
This may be related to https://github.com/docker/docker/issues/12080 although this happens with aufs and overlay. It is also possible it is related to some other part of the stack though, would need looking at.

Is this causing you an issue? There is not much point in having socket files written into the image, as they need to be recreated by the server each time anyway.

**Comment by mitzkia** [comment]
Thanks for making attention on the other issue: #12080. I will check it. 

We found this issue when we install syslog-ng inside a container, and we want to use it's syslog-ng-ctl socket file, but we can not because it was not a socket, but a regular file. 

In syslog-ng case we saw the same as I earlier described: if we install and start syslog-ng with Dockerfile instructions we can not use syslog-ng-ctl socket file, but when we install and start it from a script file it works.

**Comment by mitzkia** [comment]
Should I create other reproduction steps with docker for syslog-ng?

**Comment by cpuguy83** [comment]
You can't commit a socket to the filesystem, though.
This just looks like improper usage.

**Comment by mitzkia** [comment]
@cpuguy83 Thanks for your answer. 
In this case this issue can be close, but before it can I ask a reference for this working mode (can't commit a socket to the filesystem)? Where can I read about it?
Thanks a lot.

**Comment by justincormack** [comment]
@cpuguy83 I know its quite useless, but is it specifically blocked? It is weird it just turns up as a regular file. Pipes are fine...

**Comment by cpuguy83** [comment]
That's a great question. AFIACT nothing is explicitly blocking it.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
