### ISSUE TITLE
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

### ISSUE THREAD

**Issue by nebrass** [moby/moby#30925]
**Description**

I have a fresh installation of Docker for Mac 1.13.1.
I was applying the beginner tutorial, the voting app chapter: [https://github.com/docker/labs/blob/master/beginner/chapters/votingapp.md#31-deploying-the-app](https://github.com/docker/labs/blob/master/beginner/chapters/votingapp.md#31-deploying-the-app). When I tried the command: 
```
docker stack deploy --compose-file docker-stack.yml vote
```
I got this error:
```
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Steps to reproduce the issue:**

1. git clone https://github.com/docker/example-voting-app.git
2. cd example-voting-app
3. docker swarm init
4. docker stack deploy --compose-file docker-stack.yml vote

then you will get this error:
```
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Expected to have:**

```
Creating network vote_frontend
Creating network vote_backend
Creating network vote_default
Creating service vote_vote
Creating service vote_result
Creating service vote_worker
Creating service vote_redis
Creating service vote_db
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ch9ui0mvg97rcmhv6gvc0td99
 Is Manager: true
 ClusterID: l1qo1y737o1837azuyhnz0m23
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: DCF3:USNC:K2NZ:SRI5:F3J5:KVE7:7A4T:YICD:M5QM:AC2E:GWHU:KH43
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 130
 System Time: 2017-02-11T08:47:42.142764219Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thank you !

**Comment by ksachdev1** [comment]
is there a workaround for this issue? I am hitting it quite often. It happens sometimes and sometimes it does not.

**Comment by xeor** [comment]
I'm getting the same error trying to deploy a stack with a single service for testing.
Getting `Mar 04 00:29:22 d1 dockerd[313]: time="2017-03-04T00:29:22.170075788+01:00" level=error msg="Handler for POST /v1.26/networks/create returned error: rpc error: code = 4 desc = context deadline exceeded"` in the logs.

The same thing is happening from mac, and from the dockerd node itself (running docker 1.13 on arch).

From mac:

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3727
 Built:        Sun Feb 12 02:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

How can we provide more relevant debug info for this issue?

**Comment by bargemb** [comment]
same issue on Docker for Windows

**Comment by cpuguy83** [comment]
ping @docker/core-swarmkit-maintainers

**Comment by aaronlehmann** [comment]
Could be related to registry timeouts (#31427)

**Comment by dperny** [comment]
This is related to #29987. Specifically, our error reporting for failures kind of sucks. It's in my queue to fix, just sort of low priority right now. That wouldn't fix this problem but it would make it a lot easier for everyone involved to figure out what's going on.

**Comment by saizcorbe** [comment]
I had the same issue on mac doing the vote tutorial (https://docs.docker.com/engine/getstarted-voting-app/deploy-app/#deploy-the-app):
`Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false`
I had ssh sessions on the manager and the worker and got the error when executing `docker stack services vote` on the manager console.
I closed both ssh sessions and run the docker commands form the host console `$(docker-machine env manager)`.
This fixed the error for me.

**Comment by nebrass** [comment]
This issue does not occur no more. 
Thank you.

**Comment by azstate** [comment]
I am facing the same issue on azure VMs

**Comment by wintersommer** [comment]
me too
