### ISSUE TITLE
Use encrypted client certificate to connect to a docker host

### ISSUE THREAD

**Issue by NilsRenaud** [moby/moby#30935]
**Description**

I followed this tutorial from Docker to set up a secure way to communicate with a docker daemon : https://docs.docker.com/engine/security/https/

But I wanted to use an encrypted client private key instead of the unencrypted one. When I tried to launch a docker command (such as "docker ps") I got the error :

> Could not load X509 key pair: crypto/tls: failed to parse private key. Make sure the key is not encrypted.

This message is clear. But why can't I use encrypted client key ? Is that a bug ?

**Steps to reproduce the issue:**
Just follow the tutorial here :  https://docs.docker.com/engine/security/https/
But instead of generating simple client private key without passphrase, use this command : 

> openssl genrsa -aes256 -out ca-key.pem 4096

**Describe the results you received:**
> $ docker ps
> Could not load X509 key pair: crypto/tls: failed to parse private key. Make sure the key is not encrypted.

**Describe the results you expected:**

Something like : "enter your passphrase"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 290
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-9:1-1974-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.015 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.1 GB
 Metadata Space Used: 14.53 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB
Name: xxx
ID: ED7R:A7Y2:JXCY:J2UD:ENZM:WS5C:TT4Y:3NLI:ZHRV:NNWS:ANBE:EOVR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Not related.

**Comment by drsirmrpresidentfathercharles** [comment]
X509 can be decrypted using the crypto/x509 module, and it isn't currently in [go-connections/tlsconfig](https://github.com/docker/go-connections/blob/master/tlsconfig/config.go#L101).

**Comment by cyli** [comment]
@thaJeztah It's not currently supported yet, but we could add support for in either go-connections or the docker CLI.

**Comment by thaJeztah** [comment]
I was discussing with @cyli on Slack, and we're ok with this feature. If someone
wants to contribute, that'd be cool (I'll apply the "intermediate" label).

For the actual implementation, we'd still need some discussion, but here's from our conversation;

> I don't think the actual implementation is hard, but maybe spec-cing out where
> things live and who has the responsibility for what should probably be worked
> out. The docker-cli should be the one to ask for the password probably - could
> make use of the credential helper library too in order to do so for instance,
> keys in notary are encrypted similar to the tls keys, and notary takes a
> function which "gets" the password for you - it's implemented in docker here:
> https://github.com/docker/docker/blob/3a1279393faf78632bf169619d407e584da84b66/cli/trust/trust.go#L176-L201

**Comment by adshmh** [comment]
#dibs 
Could I give this a try? Perhaps I can start with a PR on go-connections?

**Comment by thaJeztah** [comment]
It's ok to make the changes to the vendored go-connections as part of a PR here so that we can review the whole change. The "vendor" CI check will then fail, but that's ok. After all looks ok, open a PR to go-connections to get it "upstream". 

Does that work for you?

**Comment by adshmh** [comment]
Yes, that seems a much better approach. Thank you. 
I will submit a PR here then.

**Comment by matthewbarr** [comment]
Q: What would this look like on Docker for the Mac? 

Could we use the Mac keychain for the password?     This could be mitigated on the Mac by using the keychain stored client certs directly, as talked about it: https://github.com/docker/for-mac/issues/1320
@ijc25  mentioned that they created an internal feature request.

**Comment by rmmcnulty9** [comment]
This might be related but I am unable to use an encrypted cert with my private Docker registry. I followed the steps [here](https://docs.docker.com/engine/security/certificates/) and when I try to login I get `Error response from daemon: tls: failed to parse private key`. My workaround is to decrypt my key but that is not ideal.

**Comment by dc70184** [comment]
When can Docker support encrypted private key in $HOME/.docker/key.pem? This is a very important feature for us. Thanks.

**Comment by thaJeztah** [comment]
@dc70184 this should now be supported (since docker 17.05) as the associated pull request was merged; https://github.com/moby/moby/pull/31364

I'll go ahead and close this, but let me know if it isn't working as expected

**Comment by rmmcnulty9** [comment]
@thaJeztah I am still seeing my issue on version 17.09.0-ce. Should Docker also support decrypting private keys in `/etc/docker/certs.d/my_registry_name/`?

**Comment by thaJeztah** [comment]
@rmmcnulty9 this issue was for the client connecting to the daemon; for the daemon I'm not sure it would make a lot of sense to implement, as it would mean the daemon can only be started interactively (start daemon; enter passphrase), or it would read the password from a file (which sounds like a bad idea as well). You're welcome to open an issue for it though, or if you have thoughts/suggestions for that.

**Comment by matthewbarr** [comment]
On the mac, it would be nice to pull the certificate from the Keychain.  Or the password from the keychain, at the least.     docker/for-mac#1320

**Comment by thaJeztah** [comment]
@matthewbarr can you open an issue for that in the docker for mac issue tracker? https://github.com/docker/for-mac/issues

**Comment by matthewbarr** [comment]
It's already open.  Been in triage since Jun 20th 2017.

**Comment by matthewbarr** [comment]
docker/for-mac#1757
