### ISSUE TITLE
Insufficient system resources exist to complete the requested service - during container creation

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#30950]
Hello there,

We already faced two times with this issues. Docker Daemon started to response to all `run` commands with following error:

```
C:\Program Files\docker\docker.exe: Error response from daemon: container d8648209598d2a48d6c6606a002f4c57bd12aec0f9a56d1668f2e8e1ab4ee236 encountered an error during CreateContainer: failure in a Windows system call: Insufficient system resources exist to complete the requested service. (0x5aa) extra info: {"SystemType":"Container","Name":"d8648209598d2a48d6c6606a002f4c57bd12aec0f9a56d1668f2e8e1ab4ee236","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{124984ac-edfd-11e6-a95d-dfb989422bed}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"E:\\docker_storage_1_13\\windowsfilter\\d8648209598d2a48d6c6606a002f4c57bd12aec0f9a56d1668f2e8e1ab4ee236","Layers":[{"ID":"a52cbe57-40b9-5ea6-af7f-3bbc3e82ffce","Path":"E:\\docker_storage_1_13\\windowsfilter\\afdec39615c3a4eca30e66cee7bad56c3069d863b260b3acc778389c7284287a"},{"ID":"636c30a3-6723-53e7-a419-2b53283931f3","Path":"E:\\docker_storage_1_13\\windowsfilter\\462466dfdee409ada51816edd7d8682a5ac64801c8c0d6217fb78d858f800d67"},{"ID":"78e1aeaf-b965-5389-af80-026036883bda","Path":"E:\\docker_storage_1_13\\windowsfilter\\d07c4480eedd0c1ef42fc14dd20c4bf996fd296f7665bcc4322ac4c5d0d596b8"},{"ID":"b3e31417-b9c0-5e49-ab05-1b7b22451477","Path":"E:\\docker_storage_1_13\\windowsfilter\\3ad77b613cc147008770d9ad9063651b0f1cdd7bec258f3941266273427f1b50"},{"ID":"346ad798-610a-5641-badf-ab499efd1185","Path":"E:\\docker_storage_1_13\\windowsfilter\\41d52565e6ade542cb2910c4b552d5ae3806fd6b6cc93cf5e5d026c7d4941d75"}],"HostName":"d8648209598d","MappedDirectories":[],"HvPartition":false,"EndpointList":["40d9a847-a491-4ca2-a084-822cd4a5b95f"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.
```

Although resource utilization was quite low - about 5% for CPU and 10% for memory. So it is not clear about what kind of resources this error. May be some registry size or processes/ threads limits? There were running about 150 containers.

Moreover after 30-60 minutes the whole server started to be unresponsive so we just could reboot the server from AWS console.

We were able to catch Docker daemon stack trace which can be downloaded from [here](https://drive.google.com/drive/folders/0B40Br_ddPHjqLVdyeTNHdlV4OTA)

I do not know how exactly to reproduce the issue but most likely we will face this issue again so I appreciate if you can advise what other information we can collect for helping you to reproduce the issue.

Following outputs, unfortunately, were gathered few minutes ago when Docker daemon worked fine.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 187
 Running: 146
 Paused: 0
 Stopped: 41
Images: 747
Server Version: 1.13.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 64
Total Memory: 976 GiB
Name: WIN-B737EJJT7B8
ID: 62EZ:P3MP:SQ3U:3UET:3JAP:QLAU:X2O4:E5NA:7WAH:BUGN:CAQT:VZ5V
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 1243
 System Time: 2017-02-12T15:53:07.2124207-05:00
 EventsListeners: 0
Username: aureadockerservice
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is AWS x1.x32large instance.

**Comment by cpuguy83** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
That's coming from the platform rather than docker per se. Can you enable analytic logs for Hyper-V-Compute and save the event file once you hit another failure?

**Comment by jhowardmsft** [comment]
More info needed - see above and https://github.com/docker/docker/issues/30605#issuecomment-286153099. Particularly the HCS tracing part.

**Comment by olljanat** [comment]
FYI. One of our servers ended up to state that it gives same error for all the time when I try to start any containers on it.

I was able repeat error also with runhcs.exe which means that it have no anything to do to with Docker so I created issue of it to Microsoft/hcsshim#437

**Comment by jhowardmsft** [comment]
@olljanat I've reached out to CSS internally, but without the HCS tracing from either yourself or @georgyturevich  as requested, there's nothing we can do to progress this here. Hence closing this issue . Please progress with your Microsoft support contacts if this continues to be an issue.

**Comment by Raja51** [comment]
In my case, some of the containers were in created state but not in exit state. even prune did not cleaned up this containers. i have explicitly stopped the containers and it resolved my issue.
