### ISSUE TITLE
Docker Swarm Mode recreated containers distribution

### ISSUE THREAD

**Issue by pszczekutowicz** [moby/moby#30981]
**Description**

During heave development of application build with around 20 services running in Docker Swarm Mode I discovered that with time almost all services are located on only one node. Cluster is build on top of 3 nodes (leader and two managers) with Docker Engine 1.13.1 and team is using it as development environment automatically managed by our CI service. Environment is located in AWS.

When services are created for the first time containers are distributed on all three nodes quite evenly. During development when services are frequently updated, restarted and are failing with time containers are more and more relocating to one of nodes (usually last one)

Scenarios reproducing this behavior using VirtualBox/Vagrant:

**Steps to reproduce:**
1. Create cluster with 3 nodes
2. execute: docker service create --name timer --replicas 9 alpine sleep 10

**Current behavior:**
For the first time containers are distributed evenly on all nodes. After 20 - 30 second one can notice that containers will not be distributed evenly.

Another example:

**Steps to reproduce:**
1. Create cluster with 3 nodes
2. execute: docker service create --name ping --replicas 9 alpine ping www.docker.com
3. on node 1 execute (and repeat 2 or 3 times): docker ps -q | xargs -r docker stop
4. on node 2 execute (and repeat 2 or 3 times): docker ps -q | xargs -r docker stop

**Current behavior:**
After step 2 there will be 9 container distributed evenly on 3 nodes (3 container per node). After step 4 all containers will be located on node 3.

When service is scaled up and down all containers are created on node 3.

When service is removed and created again containers are discovered evenly. 

**Expected behavior (both above scenarios):**
Containers are distributed evenly all the time (desired state).

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
I think you may be seeing a new feature of swarm mode that temporarily avoids rescheduling containers on nodes that have recently experienced a string of failures in a row. The goal is to avoid continuously trying to reschedule a container on a faulty node. After a few failed attempts, a different node is preferred even if it's running more containers. You can read more about this change here: https://github.com/docker/swarmkit/pull/1552

The `docker ps -q | xargs -r docker stop` in your example would certainly simulate a faulty node where containers fail soon after being started.

If you find yourself in a situation where containers are not fairly distributed throughout the cluster, running `docker service update --force <servicename>` will schedule and start a new set of containers. Note that you may need to wait a few minutes to avoid the faulty node detection logic.

**Comment by pszczekutowicz** [comment]
Thank you for your answer. 

In current configuration we have all nodes in exactly same configuration (EC2 t2.medium) prepared with Ansible so I'm pretty sure that there is no differences between them. I did not mentioned that all services running on our development environment have only 1 replicas. So there is 20 different services.

Because nodes are not balanced equally services are killing nodes. Actually this is happening right now and I just executed `docker service update --force <servicename>`. So it did not helped. I scaled all services 

Is there any way to reset state of any node's failures manually? Maintenance team may diagnose the problem, fixed it  and now they want to somehow manually reset its state of failures. How to do it?

If container exited with status code 0. It is still treated as failed?

**Comment by aaronlehmann** [comment]
On the managers, do you see any log messages like this?

`underweighting node <node ID> for service <service ID> because it experienced 5 failures or rejections within 300 seconds`

That would confirm or disconfirm that the failure monitoring feature is involved.

> Is there any way to reset state of any node's failures manually? Maintenance team may diagnose the problem, fixed it and now they want to somehow manually reset its state of failures. How to do it?

Recreating the service would do it, or triggering a leader failover (by restarting the lead manager, for example). But there's no way to directly reset it.

> If container exited with status code 0. It is still treated as failed?

No, it should not be.

**Comment by thaJeztah** [comment]
ping @pszczekutowicz ^^

**Comment by pszczekutowicz** [comment]
> On the managers, do you see any log messages like this?
No, I do not.

**Comment by pszczekutowicz** [comment]
@aaronlehmann Can you help with following question: will node be marked as faulty if service will handle signal and exit with none zero status code like 128 + signal number (130 for SIGINT and 143 for SIGTERM)?

**Comment by aaronlehmann** [comment]
That situation would count as a failure, but the node would only be marked potentially faulty if it happens 5 times within 5 minutes.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
