### ISSUE TITLE
[swarm] get errors about lost leader from daemon  

### ISSUE THREAD

**Issue by yuexiao-wang** [moby/moby#31027]
**Description**
There are 3 manager nodes which are all reachable in my swarm.  I used ansible  to run some docker service create. In a node，Some service are created successfully, but one service ( random global service ) is created  failed.  

**Steps to reproduce the issue:**
1.  swam init 
2.  swam join (total 3 manager nodes )
3.  use ansible  to run some docker service create.

**Describe the results you received:**

The error from docker daemon is as follows:
Error response from daemon: rpc error: code = 2 desc = raft: failed to process the request:    node lost leader status

Some log in docker.log:
time="2017-02-13T14:42:38.281509334+08:00" level=info msg="5692ad0219730292 became follower at term 0"
time="2017-02-13T14:42:38.281550814+08:00" level=info msg="newRaft 5692ad0219730292 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"
time="2017-02-13T14:42:38.281571007+08:00" level=info msg="5692ad0219730292 became follower at term 1"
time="2017-02-13T14:42:38.299348081+08:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=192.168.2.13 Adv-addr=192.168.2.13 Remote-addr =192.168.2.15"
time="2017-02-13T14:42:38.302723411+08:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=192.168.2.13 Adv-addr=192.168.2.13 Remote-addr =192.168.2.15"
time="2017-02-13T14:42:38.302818404+08:00" level=info msg="Gossip cluster hostname host-192-168-2-13-ca5efdfdc4d9"
^[[34mINFO^[[0m[0000] Firewalld running: false

time="2017-02-13T14:42:39.195749201+08:00" level=info msg="5692ad0219730292 [term: 1] received a MsgHeartbeat message with higher term from 731fcf8acf819fb9 [term: 2]"
time="2017-02-13T14:42:39.195818937+08:00" level=info msg="5692ad0219730292 became follower at term 2"
time="2017-02-13T14:42:39.195839329+08:00" level=info msg="raft.node: 5692ad0219730292 elected leader 731fcf8acf819fb9 at term 2"

time="2017-02-13T14:47:16.238439110+08:00" level=info msg="5692ad0219730292 is starting a new election at term 2"
time="2017-02-13T14:47:16.238498959+08:00" level=info msg="5692ad0219730292 became candidate at term 3"
time="2017-02-13T14:47:16.238518152+08:00" level=info msg="5692ad0219730292 received vote from 5692ad0219730292 at term 3"
time="2017-02-13T14:47:16.238540722+08:00" level=info msg="5692ad0219730292 [logterm: 2, index: 63] sent vote request to 731fcf8acf819fb9 at term 3"
time="2017-02-13T14:47:16.238563305+08:00" level=info msg="5692ad0219730292 [logterm: 2, index: 63] sent vote request to db1b6ef567a6a52 at term 3"
time="2017-02-13T14:47:16.238588359+08:00" level=info msg="raft.node: 5692ad0219730292 lost leader 731fcf8acf819fb9 at term 3"
time="2017-02-13T14:47:16.420986170+08:00" level=info msg="5692ad0219730292 [term: 3] ignored a MsgHeartbeat message with lower term from 731fcf8acf819fb9 [term: 2]"
time="2017-02-13T14:47:16.421041676+08:00" level=info msg="5692ad0219730292 [term: 3] ignored a MsgApp message with lower term from 731fcf8acf819fb9 [term: 2]"
time="2017-02-13T14:47:16.443105052+08:00" level=info msg="5692ad0219730292 received vote rejection from 731fcf8acf819fb9 at term 3" 
time="2017-02-13T14:47:16.443133250+08:00" level=info msg="5692ad0219730292 [quorum:2] has received 1 votes and 1 vote rejections"
time="2017-02-13T14:47:16.444548848+08:00" level=error msg="agent: session failed" error="rpc error: code = 13 desc = transport is closing" module=agent
time="2017-02-13T14:47:16.454387976+08:00" level=info msg="5692ad0219730292 received vote rejection from db1b6ef567a6a52 at term 3"
time="2017-02-13T14:47:16.454411443+08:00" level=info msg="5692ad0219730292 [quorum:2] has received 1 votes and 2 vote rejections"
time="2017-02-13T14:47:16.454442516+08:00" level=info msg="5692ad0219730292 became follower at term 3"
time="2017-02-13T14:47:16.517385723+08:00" level=error msg="agent: session failed" error="rpc error: code = 8 desc = more than one redirect to leader from: [192.168.2.13:45690]" module=agent
time="2017-02-13T14:47:16.772756510+08:00" level=error msg="agent: session failed" error="rpc error: code = 8 desc = more than one redirect to leader from: [192.168.2.13:45692]" module=agent
time="2017-02-13T14:47:16.943345692+08:00" level=error msg="agent: session failed" error="rpc error: code = 8 desc = more than one redirect to leader from: [192.168.2.13:35814]" module=agent
time="2017-02-13T14:47:18.315974545+08:00" level=error msg="agent: session failed" error="rpc error: code = 8 desc = more than one redirect to leader from: [192.168.2.13:55288]" module=agent
time="2017-02-13T14:47:19.531539999+08:00" level=info msg="5692ad0219730292 [term: 3] received a MsgVote message with higher term from db1b6ef567a6a52 [term: 4]"
time="2017-02-13T14:47:19.531606389+08:00" level=info msg="5692ad0219730292 became follower at term 4"
time="2017-02-13T14:47:19.531637326+08:00" level=info msg="5692ad0219730292 [logterm: 2, index: 63, vote: 0] voted for db1b6ef567a6a52 [logterm: 2, index: 64] at term 4"
time="2017-02-13T14:47:19.542337477+08:00" level=info msg="raft.node: 5692ad0219730292 elected leader db1b6ef567a6a52 at term 4"
time="2017-02-13T14:47:20.118057634+08:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=1vfxukbcnjjakpnbtycj2fiin
time="2017-02-13T14:47:20.118253885+08:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=51s5v09jslb1na2zb88jvbtse

**Output of `docker version`:**
v1.12.3
```
The node which all services are created successfully
# docker node list
ID                           HOSTNAME           STATUS  AVAILABILITY  MANAGER STATUS
6sjax8i4kgd0yqywzypo4jk9n    host-192-168-2-15  Ready   Active        Reachable
9vqoosal798vkzw9jqyh8s101    host-192-168-2-14  Ready   Active        Leader
d9509faizwuc2dnyt33yfw96s *  host-192-168-2-13  Ready   Active        Reachable

The node which one service ( random global service ) is created  failed: 
:~# docker node ls
ID                           HOSTNAME           STATUS  AVAILABILITY  MANAGER STATUS
6sjax8i4kgd0yqywzypo4jk9n    host-192-168-2-15  Ready   Active        Reachable
9vqoosal798vkzw9jqyh8s101    host-192-168-2-14  Ready   Active        Leader
d9509faizwuc2dnyt33yfw96s *  host-192-168-2-13  Ready   Active        Reachable


**Output of `docker info`:**
# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 80
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 4fmt5s6m4oyw6vgo1l3yj9883
 Is Manager: true
 ClusterID: 8wbscu28xxyzs5bafc26co2e1
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.8
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: host-192-168-1-62
ID: WIWO:PYNI:O2L7:UPA3:UIF5:5P5S:IALU:S5CI:R6XM:ZKDM:CYAE:B3P7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by yuexiao-wang** [comment]
@thaJeztah @allencloud

**Comment by fntlnz** [comment]
@yuexiao-wang  have you tried with a newer version of the engine ? You could try with 1.13.1 but if you need to stay in 1.12.x you can try with 1.12.6 - tons of improvements have been made.
Also can you verify that the all needed ports are open between nodes ? (See: https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-protocols-and-ports-between-the-hosts)

**Comment by yuexiao-wang** [comment]
1. Ports are open between nodes。In a node, one service are failed, but other services created successfully, 

2. Why does node lost leader when network is available ? It takes 3s to elect a new leader between nodes.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
