### ISSUE TITLE
Dockerfile FROM does not work with credsStore auth

### ISSUE THREAD

**Issue by russellwstanley** [moby/moby#31039]
**Description**

when building an image from a dockerfile, the FROM command does not respect the credsStore auth defined in ~/.docker/config

**Steps to reproduce the issue:**
1. upload a private image to docker hub (myrepo/privateimage:latest)
2. create a credsStore that serves out the credentials to access this image
3. remove all hard coded auth from ~/.docker/config.json and add the "credsStore" line
3. verify that you can pull the image with "docker pull myrepo/privateimage:latest"
4. write a Dockerfile that contains a single line "FROM myrepo/privateimage:latest"
5. run docker build . 

you will get an error like this

Sending build context to Docker daemon 2.048 kB
Step 1/1 : FROM myrepo/privateimage:latest
repository myrepo/privateimage not found: does not exist or no pull access

**Describe the results you expected:**

docker should pull the image and build a new image with the Dockerfile

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.13.1
```

**Output of `docker info`:**

```

Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 67
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: russell-workstation
ID: WTKG:PMKH:ZBQK:Q4OB:3X5J:RG53:XLRY:H5HP:SYVY:HNZY:2U2B:GIMJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 16:04 Desktop, physical

**Comment by thaJeztah** [comment]
Can you try

- updating the credentials helper to the latest version: https://github.com/docker/docker-credential-helpers/releases
- after that, logging out (`docker logout`) and logging in again?

**Comment by bwalding** [comment]
I can confirm this is a problem in my environment too - Ubuntu 16.04 - `Docker version 17.03.0-ce, build 60ccb22`

I don't think this is related to ECR - as the ECR credsStore helper isn't called using `docker build`.

## Dockerfile

```
FROM XXXX.dkr.ecr.us-east-1.amazonaws.com/repo:latest
RUN "ls"
```

## docker build - does not authenticate (it doesn't even try)
The credsStore is an ECR login system - but the wrapper defined in credsStore isn't even called in this scenario.

````
$ docker build .
Sending build context to Docker daemon 31.23 kB
Step 1/2 : FROM XXXX.dkr.ecr.us-east-1.amazonaws.com/repo:latest
Pulling repository XXXX.dkr.ecr.us-east-1.amazonaws.com/repo
unauthorized: authentication required
````

## docker pull - working authentication
````
$ docker pull FROM XXXX.dkr.ecr.us-east-1.amazonaws.com/repo:latest
latest: Pulling from repo
````

**Comment by alexchavez** [comment]
I have this issue as well. `docker pull $REGISTRY/$IMAGE:$VERSION` works but when my Dockerfile contains `FROM $REGISTRY/$IMAGE:$VERSION`, running `docker build .` fails, where `$REGISTRY` is an AWS registry.

I tried updating https://github.com/docker/docker-credential-helpers/releases to latest as @thaJeztah suggested. After logging out or deleting `~/.docker/config.json` and logging back in:

```
$ cat ~/.docker/config.json
{
	"auths": {
		"<private registry>": {}
	},
	"credsStore": "osxkeychain"
}

$ docker build .
Sending build context to Docker daemon 102.4 kB
...
unauthorized: authentication required
```

Removing the `credsStore` entry and logging back in allows `docker build .` to run successfully:

```
{
	"auths": {
		"<private registry>": {
			"auth": "<token>"
		}
	}
}
```

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: JR3E:Z7X3:WICM:NRY2:SMTG:WGKI:4BLA:WNSC:3Y26:MJAS:M3RB:ZF6F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 28
 System Time: 2017-04-13T16:27:49.174905177Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
ping @vdemeester @simonferquel PTAL

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
