### ISSUE TITLE
Docker Logs skipping/missing application logs

### ISSUE THREAD

**Issue by calamari-** [moby/moby#31058]
Docker logs are missing studout from java application. We have apps logs to mesos logs which show log lines that are missing in docker logs.

**Steps to reproduce the issue:**
1. Start up a mesos cluster
2. Run a docker java app
3. Compare the logs in docker logs vs mesos logs

1. vdiff the two log files uploaded to see how docker is missing logs lines compared to mesos logs (application logs)

**Describe the results you received:**
Docker logs indeed miss the log lines captured in mesos logs

**Describe the results you expected:**
Since they are both attaching to the std out of the container and getting the application logs, docker logs should be same as mesos logs for application.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 19
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-202:2-444596515-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.445 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.93 GB
 Metadata Space Used: 12.93 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.135 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.5 GiB
Name: hostname
ID: WCAD:AG3J:WEG3:INVH:I7BO:WHLZ:3S5L:KB73:DSCO:YXB7:JZP5:PABW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: proxy-address
Https Proxy: proxy-address
No Proxy: proxy-address
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, Mesos
[docker-mesos-logs.zip](https://github.com/docker/docker/files/778303/docker-mesos-logs.zip)

**Comment by bsarraf** [comment]
I have the same issue, can we get some traction to this issue.

**Comment by cpuguy83** [comment]
Really need more detail.
How are you running your containers? What exactly are you running?

Logs cannot really be missed unless there's some issue writing to disk.

**Comment by calamari-** [comment]
The containers are being run using marathon scheduler, on AWS EC2 m4.4xlarge instances, the app being run are just different java apps, the logs are written to the attached SSD EBS, so I doubt its issues with writing to the disk, is there any log you would need?

**Comment by cpuguy83** [comment]
The docker logs may indicate errors for the missing logs.

**Comment by jim-minter** [comment]
I think this could be a journald driver / journald interaction issue.  With the above, and journald.conf RateLimitIntervalSec=, RateLimitBurst= set to their defaults, it seems pretty straightforward to trigger journald rate limiting, resulting in (effectively undetectable?) holes in the output of `docker logs`.

Example:

# rpm -q docker
docker-1.12.6-6.gitae7d637.fc25.x86_64
# docker info | grep 'Logging Driver'
Logging Driver: journald
# docker run --name=test busybox sh -c 'for i in `seq 1 3000`; do echo $i; done' | wc -l
3000
# docker logs test | wc -l
2495
# journalctl | grep Suppressed | tail -1
Apr 20 14:44:58 t540p systemd-journald[817]: Suppressed 504 messages from /system.slice/docker.service

(presumably there's an off-by-one somewhere in journald too)

@calamari-, @bsarraf does this match what you're seeing at all? (If not, apologies for the noise and I'll open a separate issue for my problem)

AFAICS, all containers seem to be lumped into one bucket for the purposes of journald rate limiting, so multiple containers make log loss more likely, and one container can effectively DoS its neighbours' logs by being noisy.

I somewhat think that container logs shouldn't actually be being suppressed at all, but clearly disabling journald rate limiting on docker hosts isn't the right answer either.

If this is the issue, as a solution it'd be nice to find a way for different container logs to end up in different rate-limiting buckets in journald, and/or find a way to disable journald rate-limiting for container logs.

**Comment by calamari-** [comment]
I have two environments, one with journald and the other as json logging, I see the issue in both cases

**Comment by Yajo** [comment]
Quoting from `man journald.conf`: 

> When packages need to customize the configuration, they can install configuration snippets in /usr/lib/systemd/*.conf.d/.

Maybe the Docker package should add a configuration there to avoid missing logs by default.

**Comment by prblm** [comment]
Hi team!
 
We faced the same problem.
Some of the entries in docker container logs are missing.
Docker container logs are managed by journald driver.
journald driver has the following settings as GitHub recommended:

>  RateLimitIntervalSec=0
>  RateLimitBurst=0

**Output of docker version**

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**docker info**

```
Containers: 69
 Running: 45
 Paused: 0
 Stopped: 24
Images: 49
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: q537gx9tdks4isramyau27sis
 Is Manager: true
 ClusterID: a0bp34qsqiw6afiu3vg9afmpf
 Managers: 2
 Nodes: 2
 Default Address Pool: xxx.xxx.xxx.xxx:xxxx/x
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: xxx.xxx.xxx.xxx:xxxx
 Manager Addresses:
  xxx.xxx.xxx.xxx:xxxx
  xxx.xxx.xxx.xxx:xxxx
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.701GiB
Name: xxx
ID: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:xxxx without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: API is accessible on http://0.0.0.0:xxxx without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
```

**Filesystem info**

```
Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/centos_xxx-root   45G   21G   22G  50% /
devtmpfs                              1.9G     0  1.9G   0% /dev
tmpfs                                 1.9G     0  1.9G   0% /dev/shm
tmpfs                                 1.9G  904M  992M  48% /run
tmpfs                                 1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda1                             976M  153M  756M  17% /boot
tmpfs                                 380M     0  380M   0% /run/user/451604129
```

**Full log at the problematic timestamp**
[problem_service_full_logs.txt.zip](https://github.com/moby/moby/files/3115843/problem_service_full_logs.txt.zip)

Below you can see two screen shots where I have marked in color entries which were missing (red is missing, green is exists):

![problem_service_logs_colorized](https://user-images.githubusercontent.com/35695498/56719700-56a2cd80-6752-11e9-85b6-c0cec3ee33bb.jpg)

![TSMSC_kibana_full_logs_colorized](https://user-images.githubusercontent.com/35695498/56719725-61f5f900-6752-11e9-95eb-3d86a9c1ae08.jpg)

Please advise how to fix it.
Thank in advance!

**Comment by JonasT** [comment]
I have the same issue with docker `1.13.1` as shipped on Fedora right now.

Long log lines simply are skipped, they never appear. I use `logging.debug()` so no journalctl, syslogd or anything else inside the container involved, it's just plain stdout/stderr...

**Comment by JonasT** [comment]
I forgot to mention, I use docker default logs with no custom settings at all. (not even log rotation right now) And I am checking via `docker logs <container_id>`

**Comment by v-borovikov** [comment]
Same issue here.

`
$ docker version 
Client: Docker Engine - Community 
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
`

`
$ docker info    
Client: 
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.4
 Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.1.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.666GiB
 Name: host
 ID: K5QR:NVWW:6EEY:VLAR:PNXK:5UPE:LVCP:END7:24KX:UPVO:HVY7:YB3T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

We have postfix+dovecot+opendkim+various monitoring tools running on the same host.
I've checked logs after tuning journald config. It seems that logs from postfix beening missed sometimes. One of our monitoring tool waits for a log message about email have been sent. For some reason these log messages are lost. Postfix uses default syslog logging.

**Comment by zhulinwei** [comment]
I meet the same problem.

**Comment by sam-thibault** [comment]
This appears to be the same issue as [#35643](https://github.com/moby/moby/issues/35653).  This issue is also stale.  I will close it.  If you still encounter this issue please create a new issue.
