### ISSUE TITLE
'make all' on v1.13.1 fails for aarch64 

### ISSUE THREAD

**Issue by docbobo** [moby/moby#31061]
**Description**

Running ´make all´ for v1.13.1 on an aarch64 fails.

**Steps to reproduce the issue:**
1. Run ´make all´.
2.
3.

**Describe the results you received:**

```
[...]

Step 28 : RUN ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	aarch64/buildpack-deps:jessie@sha256:6aa1d6910791b7ac78265fd0798e5abd6cb3f27ae992f6f960f6c303ec9535f2 	aarch64/busybox:latest@sha256:b23a6a37cf269dff6e46d2473b6e227afa42b037e6d23435f1d2bc40fc8c2828 	aarch64/debian:jessie@sha256:4be74a41a7c70ebe887b634b11ffe516cf4fcd56864a54941e56bb49883c3170 	aarch64/hello-world:latest@sha256:65a4a158587b307bb02db4de41b836addb0c35175bdc801367b1ac1ddeb9afda
 ---> Using cache
 ---> 466385f0fe9e
Step 29 : COPY hack/dockerfile/binaries-commits /tmp/binaries-commits
 ---> Using cache
 ---> d6043b27b781
Step 30 : COPY hack/dockerfile/install-binaries.sh /tmp/install-binaries.sh
 ---> Using cache
 ---> 2c9b9fff778f
Step 31 : RUN /tmp/install-binaries.sh tomlv vndr runc containerd tini proxy
 ---> Using cache
 ---> 58ede6f9207d
Step 32 : ENTRYPOINT hack/dind
 ---> Using cache
 ---> 8393d964a3e1
Step 33 : COPY . /go/src/github.com/docker/docker
 ---> d70bf62cba06
Removing intermediate container d8cdbc411901
Successfully built d70bf62cba06
docker run --rm -i --privileged -e BUILD_APT_MIRROR -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_ARGS -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER=aufs -e DOCKER_INCREMENTAL_BINARY -e DOCKER_PORT -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY -e http_proxy -e https_proxy -e no_proxy -v "/root/docker/bundles:/go/src/github.com/docker/docker/bundles"  -t "docker-dev:HEAD" bash -c 'hack/validate/default && hack/make.sh'
Congratulations!  All commits are properly signed with the DCO!
Congratulations! Seccomp profile generation is done correctly.
Congratulations!  All Go source files are properly formatted.
/go/src/github.com/docker/docker/hack/validate/lint: line 12: golint: command not found
Makefile:78: recipe for target 'all' failed
make: *** [all] Error 127
```

**Describe the results you expected:**

Docker is properly build on aarch64.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/arm64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 66
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: aarch64
CPUs: 96
Total Memory: 125.9 GiB
Name: docker-builder-aarch64.local.lan
ID: UB4Q:2AMT:QRJ4:ADHH:KDX7:4ZJP:TD26:QQB6:QL3N:25GQ:AEGR:XXXI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Run on hardware hosted at Packet.

**Comment by tophj-ibm** [comment]
Looks like the aarch64 dockerfile isn't installing golint at all. 

Can you try adding this to Dockerfile.aarch64 and then running 'make validate'? https://github.com/tophj-ibm/docker/commit/12a8a916fd790c10e167aba6cb385801ff717519

If that works I'll go ahead and submit it, I just don't have an aarch64 machine to test it on.

**Comment by docbobo** [comment]
@tophj-ibm I did make a few changes in the meantime - similar to yours - and they worked. However, there are more changes required (e.g. in man/Dockerfile.aarch64 because it doesn't build with golang-1.6 anymore). Okay if I create a PR in the next days?

**Comment by tophj-ibm** [comment]
@docbobo yes of course! Let me know if you need any help

**Comment by docbobo** [comment]
Can you have a look at https://github.com/docbobo/docker/commit/2616e2066a68afa55ed1d75d052f60b620556c3c? I still had issues when attempting to run `make dep` on `master`, but the same changes worked on `v1.13.1`.

**Comment by tophj-ibm** [comment]
Can you post the error you are getting on master?

**Comment by tophj-ibm** [comment]
Also there is a current PR up for aarch64 debian:jessie support here #30168, although at the moment I'm not sure if it is going to get in because they haven't figured out a good way to install go.

**Comment by docbobo** [comment]
Yes, the golang issue kept me busy for quite a while. As it turns out, there is a golang-1.6-go package on jessie-backports. This seems to be a similar approach to the one taken with ubuntu:trusty. The only difference being that backports needs to be added to the sources list.

**Comment by docbobo** [comment]
I'll need to run another build to provide the error messages, btw.

**Comment by tophj-ibm** [comment]
That's fine, there are a lot of things that could have gone wrong. Also just FYI if you don't know, there should be a test.log in bundles/latest/build-deb

**Comment by docbobo** [comment]
Thanks, @tophj-ibm. I did notice that file but failed to copy it from the machine that I used to build. And the VM has ceased to exist since my last master build. But I just started a new attempt.

Do you think the jessie-backports approach is a viable solution to the problem described above?

**Comment by tophj-ibm** [comment]
@docbobo it sounds reasonable, I would definitely mention it in the thread I linked.

**Comment by docbobo** [comment]
The rebuild actually worked. I'll create the PR.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
