### ISSUE TITLE
Getty on `/dev/console`?

### ISSUE THREAD

**Issue by piranna** [moby/moby#31078]
**Description**

When using a [`getty`-like command](https://github.com/NodeOS/node-bin-getty) on `/dev/console` I can't be able to set it as the controlling TTY. Is that not possible? Is there another alternative? All the examples I've found so far just exec `bash` or whatever other thing directly on `/dev/console`...

**Comment by thaJeztah** [comment]
Can you provide a full example, and what you expected to happen, and what actually happened?

**Comment by crosbymichael** [comment]
This should be fixed by #33007  

When you run `tty`, `/dev/console` will no longer be returned and you will get the correct `/dev/pts/{0..9}` terminal where things like getty will work.  Let me know if you still run into it.
