### ISSUE TITLE
`--label-file` weird "unwanted" behavior ?

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#31087]
While refactoring, I stumbled upon a weird behavior : `--label-file` on `docker run` command behave **exactly** like `--environment-file`. This means, if there is a *placeholder* (i.e. a simple key, no `=` sign, no value), it will get the value from the environment variable.

```bash
$ cat labelfil
foo=bar
bar
$ env bar=baz docker run --name foo -d --label-file=labelfile busybox top
# […)
$ docker inspect --format="{{ .Config.Labels }}" foo
map[bar:baz foo:bar]
```

I'm not sure if this is a *wanted* feature or just *happened to be that way* because of the code.

/cc @docker/core-maintainers

**Comment by thaJeztah** [comment]
I'm not aware of that being added as a _feature_, so that looks like a bug to me, possibly because it happened to use the same parsing logic.

ping @duglin ?

**Comment by duglin** [comment]
From looking at the docs for "docker run", I found this:
```
$ docker run -l my-label --label com.example.foo=bar ubuntu bash

The my-label key doesn’t specify a value so the label defaults to an empty string(""). 
```

so it looks like `bar` is supposed to be empty and if so then yea I agree, it sounds like a bug.  But we should probably get someone like @rhdan to weight-in since I think he had a hand in adding label support.

**Comment by thaJeztah** [comment]
No those were only the SELinux labels, not these, so, yes, it's a bug
