### ISSUE TITLE
Windows service discovery does not work consistently

### ISSUE THREAD

**Issue by drnybble** [moby/moby#31093]
Related to the functionality introduced in https://github.com/docker/docker/pull/25987

**Description**
pinging a container by name does not always work in Windows containers. I have not yet found a consistent pattern but sometimes doing 'ping [container-name]' works and sometimes it fails. But I have never seen it fail if I include "ping [container-name]" as the command to execute when launching the container (rather than going into PowerShell).

**Steps to reproduce the issue:**
This command always seems to work:
  docker run --rm -it --name testing microsoft/windowsservercore ping testing
Instead do this:
  docker run --rm -it --name testing microsoft/windowsservercore
Then inside the container:
  ping testing
Usually it will always fail, but sometimes it will always work. If it works, exit the container, run the command and try again. It will fail.
Note that "nslookup testing" always seem to work though.

**Describe the results you received:**
See above

**Describe the results you expected:**
Pinging by the container's alias should always work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   fa5e097
 Built:        Fri Jan 27 17:05:28 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\Administrator> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 470
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8 GiB
Name: WIN-U9UU27TK2FQ
ID: HOYH:CLDY:C2SF:SJJN:VEN6:H2CS:FECI:QKIM:WA3K:3PJX:2QPE:F443
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Server 2016 VM running under VirtualBox.

**Comment by drnybble** [comment]
Pinging @msabansal as requested.

**Comment by msabansal** [comment]
Ok this gives me the hint that this is an image issue. We had a fix in DNS client to enable this. The images need to be updated for everything to work properly. Let me look for commands on how we can confirm the updated images

**Comment by friism** [comment]
@drnybble can you check that your WS2016 system is updated and that you've pulled the latest version of microsoft/windowsservercore?

**Comment by drnybble** [comment]
My Server2016 system is up-to-date. I have the latest microsoft/windowsservercore image (just confirmed).

**Comment by msabansal** [comment]
Can you please execute this command in the container: 

 [System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Windows\system32\dnsrslvr.dll") | fl *

**Comment by drnybble** [comment]
PS C:\> [System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Windows\System32\dnsrslvr.dll") | fl *


FileVersionRaw     : 10.0.14393.0
ProductVersionRaw  : 10.0.14393.0
Comments           :
CompanyName        : Microsoft Corporation
FileBuildPart      : 14393
FileDescription    : DNS Caching Resolver Service
FileMajorPart      : 10
FileMinorPart      : 0
FileName           : C:\Windows\System32\dnsrslvr.dll
FilePrivatePart    : 0
FileVersion        : 10.0.14393.0 (rs1_release.160715-1616)
InternalName       : dnsrslvr.dll
IsDebug            : False
IsPatched          : False
IsPrivateBuild     : False
IsPreRelease       : False
IsSpecialBuild     : False
Language           : English (United States)
LegalCopyright     : ? Microsoft Corporation. All rights reserved.
LegalTrademarks    :
OriginalFilename   : dnsrslvr.dll.mui
PrivateBuild       :
ProductBuildPart   : 14393
ProductMajorPart   : 10
ProductMinorPart   : 0
ProductName        : Microsoft? Windows? Operating System
ProductPrivatePart : 0
ProductVersion     : 10.0.14393.0
SpecialBuild       :

**Comment by msabansal** [comment]
@drnybble This file version looks old. A simpler command would have been to just list images using docker images
Please see if docker pull microsoft/windowsservercore fixes the issue

**Comment by drnybble** [comment]
I have pulled the latest microsoft/windowsservercore. Doing 'docker image inspect microsoft/windowsservercore' shows an OsVersion of 10.0.14393.693.

**Comment by msabansal** [comment]
@drnybble. My bad. I just verified that this file doesn't need an updated. Just having an updated dnsapi.dll is good. This image has the right binaries. Can you please check if appending . to the file works reliably for you?

**Comment by msabansal** [comment]
@drnybble I have tried to reproduce this for a few hours now but haven't had success for some reason.

Also please see if disabling firewall has any impact on this 
NetSh Advfirewall set allprofiles state off

**Comment by drnybble** [comment]
Firewall off. 
Tried this ten times:
  docker run --rm -it --name testing microsoft/windowsservercore ping testing
Success every time.
Tried this ten times:
  docker run --rm -it --name testing microsoft/windowsservercore powershell ping testing
Failed every time.

The powershell invocation is slower - - maybe it is a race condition.
Dot after the name makes no difference.

**Comment by msabansal** [comment]
@drnybble Can you please check if doing this solves the issue? 

 New-NetFirewallRule -Protocol UDP -LocalPort 53 -Name dns -DisplayName dns -Action Allow

Also what happens when you do:

Get-ContainerNetwork | Remove-ContainerNetwork -Force
Restart-Service docker

and try again

**Comment by msabansal** [comment]
Also does adding a sleep and then trying fixes the issue? Please try this
1..15 | % { ping testing -n 1; sleep 5; }
ipconfig /all

and share the result

**Comment by msabansal** [comment]
@drnybble Also I would love to see what is happening on the system. Can you please capture the following traces for me from the host? (use cmd)

netsh trace start  globallevel=5 provider=microsoft-windows-winnat level=5 provider=Microsoft-Windows-TCPIP level=5 report=di capture=yes

**Comment by drnybble** [comment]
[docker_issue_31093.zip](https://github.com/docker/docker/files/790592/docker_issue_31093.zip)

Attached a zip with all the requested information. I included two WireShark captures from the identical command issued one after the other:
  docker run --rm --name pinger microsoft/windowsservercore ping pinger

The first one succeeded, the second one failed. From what I can see in WireShark no DNS query was made to the Docker DNS server in the second instance.

**Comment by drnybble** [comment]
[nslookup_ping.zip](https://github.com/docker/docker/files/790606/nslookup_ping.zip)
Here is another one from inside a container launched like this:
  docker run --rm --name pinger microsoft/windowsservercore
I did **nslookup** followed by **ping pinger**
nslookup issues successful DNS queries. ping issues LLMNR queries over IPv6 that seem to not return.

If I try again when it is failing I see a DNS query and response to IPv4 address 172.30.144.1 and no LLMNR traffic.

**Comment by drnybble** [comment]
OK I found something that seems pretty consistent. This works:
  docker run --rm -it --name pinger microsoft/windowsservercore powershell { sleep 5; ping pinger}
This fails:
  docker run --rm -it --name pinger microsoft/windowsservercore powershell { ping pinger}

Here are the wireshark captures for these two scenarios.

[docker_issue_31093_ps_wireshark.zip](https://github.com/docker/docker/files/790674/docker_issue_31093_ps_wireshark.zip)

**Comment by friism** [comment]
@msabansal this seems really similar to the thing I saw with the Musicstore app.

@drnybble Maybe try this: https://github.com/aspnet/MusicStore/pull/713/files#diff-88a07c86b29f14008bf60577094d57d6R6

**Comment by drnybble** [comment]
@friism I created an image with your temporary workaround and no longer can reproduce the issue.

**Comment by msabansal** [comment]
@drnybble There was a typo in the patch we released to fix the issue :( 

> C:>reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /s
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters
> ServerPriorityTimeLimit**y** REG_DWORD 0x0
> ServiceDll REG_EXPAND_SZ %SystemRoot%\System32\dnsrslvr.dll
> ServiceDllUnloadOnStop REG_DWORD 0x1

Looking on how to get an update with the fix.

**Comment by jonashackt** [comment]
@drnybble already mentioned, this workaround inside your Dockerfile will resolve the issue (same as https://github.com/docker/for-win/issues/500):
```
# Temporary workaround for Windows DNS client weirdness
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
```

**Comment by JMesser81** [comment]
This issue should now be fixed with the most recent April KB update (https://support.microsoft.com/en-us/help/4015217). Could someone please confirm so we can close?

**Comment by drnybble** [comment]
I can confirm that with the latest microsoft/windowsservercore the registry key name is now correct.
PS C:\> reg query HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters
    ServerPriorityTimeLimit    REG_DWORD    0x0
    ServiceDll    REG_EXPAND_SZ    %SystemRoot%\System32\dnsrslvr.dll
    ServiceDllUnloadOnStop    REG_DWORD    0x1

**Comment by thaJeztah** [comment]
Thanks for confirming @drnybble! Let me go ahead and close this issue, but feel free to continue the conversation if needed 👍
