### ISSUE TITLE
Creating a service hangs existing services

### ISSUE THREAD

**Issue by shorero** [moby/moby#31090]
**Description**
EXISTING SERVICES HANG WHEN A NEW ONE IS CREATED.

Environment:
  * Windows hosts
  * Two VMs (8GB RAM), each with Centos 7 installed. Following characteristics are 
     the same on the two VMs
  * The two VMs form a single swarm. Each VM is a manager.
  * Docker 1.13.1, build 092cba3
  * Image storage uses devicemapper storage driver to a 31G thin pool, about 90% free
  * Container persisted storage uses a replicated Glusterfs file system visible on both VMs
  * selinux is disabled (doesn't play nice with Glusterfs-based container persisted storage)
  * firewalld is running but is not the problem as far as I can tell.
  * Each defined container is pinned to a single VM (non-routable IP addresses on the VMs mean,
    as far as I can tell, that the exposed service ports exist only on the VM running the service).
  * Defined services include a registry. I'm pulling the registry catalog every 15 seconds or so as a 
    "tripwire" so I'll know when the services get bollixed. Other two services are a nexus (using
    sonatype/nexus3:latest) and a gitolite (using a custom image based on Centos 7).

All services are up and running: I can pull the catalog from the registry, pull versions from gitolite, and access the nexus web front end. As soon as I install another service (jenkins, if you care, but I doubt if the exact image has anything to do with the problem), all the existing services stop responding: the trip wire stops reporting the catalog, a git pull hangs, and I can't get to nexus). To get things working again, I rescale the existing services to zero and back to 1.

I can provide logs if you care. However, there's nothing obvious (to me at least) in any of the container logs or in the VM's /var/log/messages file. 

**Steps to reproduce the issue:**
1. Start with a working collection of services
2. Create a new service "docker service create ..."
3. Note that the existing services are hosed
4. Cycle the services by scaling to zero and then to 1
5. Note that all services work, including the new service (#2 above)

**Describe the results you received:**
Existing services stop responding immediately (as far as I can tell) when a new service is defined. I didn't check carefully to see if the new service worked (out of the box).

**Describe the results you expected:**
Existing services shouldn't be affected by introduction of a new one.

**Additional information you deem important (e.g. issue happens only occasionally):**
This behavior is completely reproducable.

**Output of `docker version`:**

```
[shore@docker-1]$ docker --version
Docker version 1.13.1, build 092cba3

```

**Output of `docker info`:**

```
[shore@docker-1 02-gitolite]$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: pool-docker
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 3.288 GB
 Data Space Total: 33.29 GB
 Data Space Available: 30 GB
 Metadata Space Used: 3.973 MB
 Metadata Space Total: 163.6 MB
 Metadata Space Available: 159.6 MB
 Thin Pool Minimum Free Space: 3.329 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ix77ue2cgizs73xdwxnoulk8v
 Is Manager: true
 ClusterID: jw87b697uk8d7kxwp5bq1fm8i
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.10.1
 Manager Addresses:
  192.168.10.1:2377
  192.168.10.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64 GiB
Name: docker-1.local
ID: U2FS:M554:CW6W:6HON:JAP3:7XGP:USGZ:PXCL:JIHH:WRLC:OVMP:7URG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
See Environment above

**Comment by thaJeztah** [comment]
Are you able to provide an (as simple as possible) case to reproduce the issue?

**Comment by shorero** [comment]
I'll give it a shot, but I won't be able to do anything for a couple of
days. Will let you know.

**Comment by thaJeztah** [comment]
No worries, thanks in advance!

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
