### ISSUE TITLE
Docker NIC adapter shall not register DNS name with DNS server

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#31098]
### Expected behavior
Checkbox on HNS Internal NIC for DNS registration shall be unchecked
### Actual behavior
Box is checked
### Information
HNS adapter shall have automatic DNS registration disabled. This setting registers private docker IP with Active Directory DNS and causing problems for internal communications

### Steps to reproduce the behavior

![image](https://cloud.githubusercontent.com/assets/13176884/23034303/04a5043e-f441-11e6-909f-3253e30435d0.png)
![image](https://cloud.githubusercontent.com/assets/13176884/23034359/30969724-f441-11e6-8ec8-9851f6c128d0.png)

**Comment by thaJeztah** [comment]
ping @msabansal PTAL
