### ISSUE TITLE
unknown flag: --filter for system prune command

### ISSUE THREAD

**Issue by eredi93** [moby/moby#31122]
from the doc https://docs.docker.com/engine/reference/commandline/system_prune/ the flag `--filter` is available. how is that i get `unknown flag` ?
```
[ec2-user@ntrc-producton-workrs ~]$ docker system prune -f --filter "until=60m"
unknown flag: --filter
See 'docker system prune --help'.
[ec2-user@ntrc-producton-workrs ~]$ docker -v
Docker version 1.13.1, build 092cba3
```

**Comment by AkihiroSuda** [comment]
It is available on master (1.14 aka 17.04)
https://github.com/docker/docker/pull/29226

**Comment by cpuguy83** [comment]
ping @mstanleyjones  Seems a doc got through that should not have?

**Comment by vieux** [comment]
ping @johndmulhausen

**Comment by thaJeztah** [comment]
Looks like that part is copied from master in this repository, because it's not in the 1.13.x branch https://github.com/docker/docker/blob/1.13.x/docs/reference/commandline/system_prune.md

**Comment by twooster** [comment]
Still a problem with Docker 0.17.6-ce:

```sh
# docker system prune --filter until=24h
WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all networks not used by at least one container
        - all dangling images
Are you sure you want to continue? [y/N] y
Error response from daemon: Invalid filter 'until'
# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Looks like it's a different error; the original error reportedwas 

```
unknown flag: --filter
```

Which was expected, given that the `--filter` option was not yet in Docker 1.13.1


The error you're seeing is;

```
Error response from daemon: Invalid filter 'until'
```

That's a bug; I had a look at the behaviour and the issue is that all resources (containers, images, networks) support filtering by `until` _except_ volumes. The `docker system prune` sequentially calls the various prune commands, and when it calls the `docker volume prune` endpoint, an error is returned by the daemon, and pruning stops;

```
DEBU[1185] Calling POST /v1.30/containers/prune?filters=%7B%22label%22%3A%7B%22label.foo%3D%3Dbar%22%3Atrue%7D%2C%22until%22%3A%7B%2224h%22%3Atrue%7D%7D
DEBU[1185] Calling POST /v1.30/volumes/prune?filters=%7B%22label%22%3A%7B%22label.foo%3D%3Dbar%22%3Atrue%7D%2C%22until%22%3A%7B%2224h%22%3Atrue%7D%7D
ERRO[1185] Handler for POST /v1.30/volumes/prune returned error: Invalid filter 'until'
Error response from daemon: Invalid filter 'until'
```

Let me open an issue in the Docker CLI issue tracker, where the faulty code lives

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/issues/310 for tracking
