### ISSUE TITLE
broken docker configuration for enabling tcp binding

### ISSUE THREAD

**Issue by ssbarnea** [moby/moby#31127]
The current documentation from https://docs.docker.com/engine/admin/ is confusing because it gives wrong information as an example.

For start  it specifies `-H fd://` param which was removed, preventing the service from loading.

Also it gives bad-and-incomplete example of enabling a TLS connection without even generating certificates and even the paths are incorrect `/var/docker` not existing, correct location being `/var/lib/docker`.

Here is one simplified example that works:
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D -H tcp://127.0.0.1:2375
```

This does not use TLS but at least is one example that works, and for localhost only connection using non TLS is even better.

**Comment by cpuguy83** [comment]
I do not see any such example in the docs you linked.
`/var/docker` is an example location... since these are your certs you'd provide the path.

From what I can see everything in the doc looks correct and all are setting up TLS.
The only one that shows `fd://` is the centos one, which I believe should still work. `fd://` support was only removed from ubuntu/debian.

**Comment by ssbarnea** [comment]
I checked Fedora and I can assure youthat the fd:// does not work. Also giving an incomplete example is confusing. Invalid path and no info about how to generat certificates is not a good idea, as I said before it would have been better to ignore the TLS params instead of giving full info.

**Comment by cpuguy83** [comment]
@ssbarnea We definitely do not want to show setting up docker in an insecure manner.

**Comment by cpuguy83** [comment]
So maybe just some extra doc info on tls setup (doesn't have to be thorough).
Perhaps not making the path `/var/docker` would be less confusing... `/var/my-ssl-certs` or something may be better.

Can you open an issue on github.com/docker/docker.github.io?

**Comment by catinthesky** [comment]
@cpuguy83 ,   the fd:// not working also on centos too, when installed with RPM package, no corresponding kind of docker-tcp.socket setting up correctly.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
