### ISSUE TITLE
opensuse 13.2 is Discontinued

### ISSUE THREAD

**Issue by vieux** [moby/moby#31139]
OpenSuse 13.2 was discontinued on Jan 17th.

I was looking into adding the Dockerfile for OpenSuse 42.2 but I'm having trouble since the `selinux-policy` doesn't appear to exists on `42.2`

See:

```
$docker run -it  opensuse:13.2 zypper search selinux
S | Name                    | Summary                                                    | Type
--+-------------------------+------------------------------------------------------------+--------
  | libselinux-devel        | Development Include Files and Libraries for SELinux        | package
  | libselinux-devel-static | Static development Include Files and Libraries for SELinux | package
i | libselinux1             | SELinux library and simple utilities                       | package
  | libselinux1-32bit       | SELinux library and simple utilities                       | package
  | python-selinux          | SELinux library and simple utilities                       | package
  | ruby-selinux            | SELinux library and simple utilities                       | package
  | selinux-doc             | SELinux documentation                                      | package
  | selinux-policy          | SELinux policy configuration                               | package
  | selinux-policy-devel    | SELinux policy devel                                       | package
  | selinux-policy-doc      | SELinux policy documentation                               | package
  | selinux-policy-minimum  | SELinux minimum base policy                                | package
  | selinux-policy-mls      | SELinux mls base policy                                    | package
  | selinux-policy-targeted | SELinux targeted base policy                               | package
  | selinux-tools           | SELinux library and simple utilities                       | package
```

```
$docker run -it  opensuse:42.2 zypper search selinux
S | Name                    | Summary                                           | Type
--+-------------------------+---------------------------------------------------+--------
  | libselinux-devel        | Development files for the SELinux runtime library | package
  | libselinux-devel-static | Static archives for the SELinux runtime           | package
i | libselinux1             | SELinux runtime library                           | package
  | libselinux1-32bit       | SELinux runtime library                           | package
  | python-selinux          | Python bindings for the SELinux runtime library   | package
  | ruby-selinux            | Ruby bindings for the SELinux runtime library     | package
  | selinux-doc             | SELinux documentation                             | package
  | selinux-tools           | SELinux command-line utilities                    | package
```

Any help on how to fix it would be appreciated /cc @justincormack @cpuguy83 @andrewhsu @tboerger

**Comment by tboerger** [comment]
@flavio @cyphar

**Comment by vieux** [comment]
we have a release coming up soon, and we'd love to support the newest version of OpenSuse. @flavio @cyphar we could use your help :)

**Comment by cyphar** [comment]
@vieux Sorry, can you clarify what you mean by "adding the Dockerfile for openSUSE 42.2"?  Are you talking about the official library or something else?

**Comment by cyphar** [comment]
Ah, okay I understand what you mean. You're talking about auto-generated openSUSE Dockerfiles used to build `rpm`s.

I'm not sure why `selinux-policy` is missing from Leap 42.2 -- it *is* available in [Leap 42.1](https://build.opensuse.org/package/show/openSUSE:Leap:42.1/selinux-policy) as well as [Factory](https://build.opensuse.org/package/show/openSUSE:Factory/selinux-policy). I've sent an email to `opensuse-factory@opensuse.org` to see why this has happened.

**Comment by vieux** [comment]
@cyphar thank you

**Comment by vieux** [comment]
@cyphar any update ?

**Comment by cyphar** [comment]
@vieux It looks like it was having build issues so it wasn't included in Leap 42.2 (though it was in 42.1). Can you explain why it is required -- IIRC the way SELinux is implemented for Docker/runC is on an opportunistic (not build-time) basis.

Also, note that SUSE based distros (AFAIK) generally use AppArmor rather than SELinux as the primary ACL mechanism.

**Comment by vieux** [comment]
@cyphar I'm just trying to run the [script](https://github.com/docker/docker/blob/master/contrib/builder/rpm/amd64/generate.sh#L96) we use to generate the Dockerfiles on 42.2

Looks like we assume rpm -> selinux and deb -> apparmor

/cc @andrewhsu

**Comment by cyphar** [comment]
But `selinux-policy` doesn't really matter from the Docker side because it's not necessary for building SELinux support -- you only need `libselinux-devel` to build Docker and `libselinux` to run Docker. `selinux-policy` effectively is the host policy for the entire system -- why does Docker's build process need this in order to build the RPM?

We've been shipping Docker as part of openSUSE for a long time, and AFAIK we've never needed anything like this.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
