### ISSUE TITLE
Global service unable to pull image on recently orphaned node blocked access to gitlab.com for entire workplace

### ISSUE THREAD

**Issue by richardgoater** [moby/moby#31156]
Although the fallout of this incident can be attributed to misfortune, I think it does highlight either a bug or some unfavourable default behaviour in swarm mode.

Last week I noticed one our nodes in a 3-node swarm mode cluster had lost contact. I rejoined the node but the single global service was still stuck at 2/3 replicas. I thought I needed to redeploy the service so tried to pull the latest stack configuration, only to receive a 403 Forbidden from gitlab.com. My workplace enforces the use of a web proxy for outbound traffic so I thought something must have gone wrong with it and got on with other things, the service was still up after all.

When access to gitlab.com had not returned for three days, other teams started to raise concerns (As everyone on-site must go through the proxy, so everyone was blocked from using gitlab.com). I got in contact with gitlab support, who told me that docker registry pulls failing basic auth were triggering rack::attack bans (after their recent issue with spammers). I then realised that I had only logged in to registry.gitlab.com on one node and I deployed the stack using `--with-registry-auth`. So it seems that the orphaned node had lost its credentials, and once reunited it proceeded to hammer registry.gitlab.com so hard as to trigger a ban, and may have continued to do so indefinitely.

I don't know if this is intended behaviour or not.

**Steps to reproduce the issue:**
1. Create a stack on a swarm mode cluster containing a global service using a private image, from a node authenticated with the registry, using the `--with-registry-auth` option.
2. Disconnect and reconnect a second node, which is not authenticated with the registry.
3. Check your network traffic.

**Describe the results you received:**
The service remains unable to start but continues to retry, even though it has no hope of succeeding.

**Describe the results you expected:**
I would expect the service to give up, possibly at the first attempt, as this class of failure is non-recoverable and requires manual intervention.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: k4sglctyf3282n5zryv089obd
 Is Manager: true
 ClusterID: 3fnk6wi91a5xsq561fv9r8gbr
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 49.13 GiB
ID: XXRU:3CFO:7M5F:IJGW:GRPQ:J2CB:B2FD:A2QO:KODH:EOGR:VAJA:C37F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual machines behind a corporate firewall and outbound proxy.

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
First, sorry to hear that this caused problems for you!

> Steps to reproduce the issue:

> Create a stack on a swarm mode cluster containing a global service using a private image, from a node authenticated with the registry, using the --with-registry-auth option.
Disconnect and reconnect a second node, which is not authenticated with the registry.
Check your network traffic.
Describe the results you received:
The service remains unable to start but continues to retry, even though it has no hope of succeeding.

Unless this is something specific to GitLab, there isn't really a concept of authenticating a node with the registry. The registry credentials are stored as part of the service definition, and in general any node that executes the service should be able to use those credentials. It's certainly possible to publish incorrect or outdated credentials, or to forget to include the credentials (for example, by skipping `--with-registry-auth`), and this can lead to the kind of situation you described.

> Describe the results you expected:
> I would expect the service to give up, possibly at the first attempt, as this class of failure is non-recoverable and requires manual intervention.

By default, the orchestrator will try to restart failed tasks periodically. While authentication failures are sometimes unrecoverable, they can also be due to temporary problems on the registry side, which may eventually be corrected. The default time interval between restarts is 5 seconds, but I can see that this might be quite aggressive in some situations, and in those cases it would be a good idea to adjust the parameter using `--restart-delay`. It's also possible to set up the service so that failed tasks are never restarted, using `--restart-condition none`.

**Comment by richardgoater** [comment]
Dear @aaronlehmann, thanks very much for your reply, really interesting to know that the credentials are stored with the service. In that case, I wonder what could have gone wrong as 2/3 tasks in the service were fine?

I see your point about the registry, I will see if I can make use of `--restart-delay` and `--restart-condition` in future.

**Comment by richardgoater** [comment]
Unfortunately I must report that this issue occurred again for me today, again triggering a ban from gitlab.com. All three nodes in the swarm were logged in to the registry before any action was taken, whereupon an issue (specifically, changing a service from `global` to `replicated`) caused `docker stack deploy` to fail, which caused a re-occurrence of the authentication problem. It still feels like a bug to me.

**Comment by thaJeztah** [comment]
When updating the service from, did you pass `--with-registry-auth` during `docker stack deploy` to update the credentials? I don't know what authentication mechanism gitlab uses, but if it's using expiring sessions, it's possible that the credentials that were stored expired.

**Comment by richardgoater** [comment]
@thaJeztah fairly certain I passed `--with-registry-auth`. Gitlab uses http basic auth on the registry so I assume it's the username/password that's being stored.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
