### ISSUE TITLE
Add available filters for cli - docker --help, or any other command parameters

### ISSUE THREAD

**Issue by krasi-georgiev** [moby/moby#31151]
Would it be useful to add the available filters for each command in the docker cli help 

the online api documentation shows them , but not the cli

https://docs.docker.com/engine/api/v1.25/

I tried adding them , but the help page gets too big and hard to read so maybe there is a better way?

the only thing that comes to my mind is implementing --help for the parameters as well

docker containers --filter --help

**Comment by krasi-georgiev** [comment]
After a short discussion it seems that the proposal is rejected by the cobra package maintainer.
https://github.com/spf13/cobra/issues/392

read from https://github.com/spf13/cobra/issues/392#issuecomment-285391155

@thaJeztah  could you please comment about @spf13 's suggestion

**Comment by thaJeztah** [comment]
I don't think adding a sub-sub command will be possible / a workable solution. We _do_ have a PR merged that now properly wraps the output (without the columns getting messed up) in https://github.com/docker/docker/pull/28751, so having multi-line help messages for flags _could_ be possible.

Another option that has been discussed at some point is to use a similar approach as `git` uses, i.e. print the _man page_ when `--help` is called.

This would probably be a big change to make, and I'm not sure how easily this can be achieved.

ping @dnephin @duglin any thoughts?

**Comment by krasi-georgiev** [comment]
@thaJeztah I tried adding all filters , but they are so many that the page gets way too big.

is there any issue or a pull request or a discussion to convert to man pages ?

**Comment by thaJeztah** [comment]
I don't think there's an issue for that proposal - feel free to open one for discussion (also to see if it's technically possible / worth doing)

**Comment by krasi-georgiev** [comment]
@thaJeztah why not use this issue to gather comments? 
I don't know who should we ping.
