### ISSUE TITLE
mkimage-arch.sh failing on armv6h (RPi B+)

### ISSUE THREAD

**Issue by BalzySte** [moby/moby#31166]
Building a docker image on a Raspberry B+ running itself Arch Linux ARM, I encountered a bug preventing packages download from repos (Error 404).

The issue is at line 63, in the sed pattern:
```bash
sed "s/Architecture = armv/Architecture = armv${version}h/g" './mkimage-archarm-pacman.conf' > "${PACMAN_CONF}"
```
which produces as an output the following line
`Architecture = armv6h6h`

As a quick workaround I changed line 63 into
```bash
sed "s/Architecture = armv.*/Architecture = armv${version}h/g" './mkimage-archarm-pacman.conf' > "${PACMAN_CONF}"
```
I'm not proposing a commit since I'm not sure whether this fix breaks the script for other arm architectures or not.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
