### ISSUE TITLE
`docker run -h` doesn't change hostname in /etc/sysconfig/network

### ISSUE THREAD

**Issue by yabhinav** [moby/moby#31199]
**When you run docker image with `-h` it doesn't change hostname property in the /etc/sysconfig/network but changes only /etc/hosts file**

**Steps to reproduce the issue:**
1. Run docker centos:6 image with option `-h testlab.example.com`
2. Execute `hostname` command to verify if hostname was set properly by run
3. Check `/etc/hosts` and `/etc/sysconfig/network` for hostname and domain

**Describe the results you received:**
```
MacBook-Pro:ansible-role-ipaserver abhinav$ docker run --detach -h testlab.example.com --volume="${PWD}":/etc/ansible/roles/role_under_test:ro centos:7 "/sbin/init" > "${container_id}"
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "cat /etc/sysconfig/network " 
# Created by anaconda
MacBook-Pro:ansible-role-ipaserver abhinav$ docker stop $(docker ps -a -q)
b02499b6acd4
MacBook-Pro:ansible-role-ipaserver abhinav$ docker rm $(docker ps -a -q)
b02499b6acd4
MacBook-Pro:ansible-role-ipaserver abhinav$ docker run --detach -h testlab.example.com --volume="${PWD}":/etc/ansible/roles/role_under_test:ro centos:6 "/sbin/init" > "${container_id}"
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "cat /etc/sysconfig/network " 
NETWORKING=yes
HOSTNAME=localhost.localdomain
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "hostname -f " 
testlab.example.com
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "hostname -d " 
example.com
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "hostname -s " 
testlab
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "hostname testlab.example.com " 
hostname: you must be root to change the host name
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "sudo hostname testlab.example.com " 
bash: sudo: command not found
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "cat /etc/hosts " 
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	testlab.example.com
```
As you can see above `/etc/sysconfig/network` still hold old hostname while `/etc/hosts` updated with hostname for centos6 image while centos7 doesn't have old hostname and hence no conflict.

Certain installation scripts read hostname from `/etc/sysconfig/network` and hence might cause issues with hostname verification.

**Describe the results you expected:**
```
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec --tty "$(cat ${container_id})" bash -c "cat /etc/sysconfig/network " 
NETWORKING=yes
HOSTNAME=testlab.example.com
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens when isa-server-install command is run on Ubuntu host and docker centos6 image
while macOS host and docker centos6 doesn't produce the same issue strangely. might have to do with docket configuration too. Nevertheless setting proper hostname in `/etc/sysconfig/network` with `docker run -h ` should solve the issue on all platforms

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 52
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934 GiB
Name: moby
ID: SHLW:MS4Q:QKAT:ZX3Y:Q4EN:7YJB:V53C:KQEZ:V257:3N62:M6AI:FM22
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 30
 System Time: 2017-02-20T18:55:48.999954363Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Same issue is replicable in the Travis build run on Google Cloud Engine

Refer :- https://s3.amazonaws.com/archive.travis-ci.org/jobs/203125220/log.txt

ansible_facts give proper hostname but when running the IPA-server-install there is a hostname mismatch since `/etc/sysconfig/network` has invalid old hostname

**Comment by yabhinav** [comment]
Temporary fix or workaround is to create you DockerFile

```
# Pull Base OS image
FROM centos:6
RUN sed --in-place '/HOSTNAME/d' /etc/sysconfig/network
```

**Comment by cpuguy83** [comment]
This is a rhel/centos specific thing for setting desired state of network config.
I do not think it is Docker's responsibility to set these kinds of files as they are specific to the distro, and how the distro would normally initialize it's networking.

ping @aboch WDYT?

**Comment by yabhinav** [comment]
Shouldn't the `docker run -it -h <hostname.domain.com>` be setting up the hostname for the distribution.

In RHEL it is handled with `/etc/hosts` and  `/etc/sysconfig/network`
In Debian it is handed under /etc/hostname

Most of the google suggestion mention setting hostname  in both `/etc/hosts` and `/etc/sysconfig/network`  and some ask to use hostnamectl hostname <hostname.domain.com>, while others say hostname <hostname.domain.com> will do it temporarily.

The [documentation](https://docs.docker.com/engine/reference/commandline/run/) says `--hostname, -h ` will set the container hostname so shouldn't it be handling it properly across all version of images released ?

**Comment by cpuguy83** [comment]
@yabhinav The hostname is not set in `/etc/sysconfig/network`. Again this is a file read by the network subsystem in centos/rhel to set up networking on restart.

Following this logic docker should also add network configuration for the interfaces it to the container here as well.

Docker interacts with the Linux kernel to perform these operations.
For instance, setting the hostname is done by calling the `sethostname(2)` system call.

**Comment by yabhinav** [comment]
as per my understanding `docker -h ` gets the new IP and  sets `/etc/host` with 

```
172.xx.xx.xx hostname.domain.com
```

but it actually should be setting 

```
172.xx.xx.xx   hostname.domain.com   hostname
```

so when we run the commands : 
```
$ hostname -f 
hostname.domain.com
$ hostname -d
domain.com
$ hostname -s
hostname

```

Anyway as a work around I have removed the following in the docker file with `RUN sed`
``HOSTNAME=local.localdomain`` 
So assuming this is a bug provided by centos6 docker image. Is there any docker run option that sets the network config because when ipaserver is being installed the installation scripts might be looking at network config  to check if there is hostname match with what is provided during setup as an option.

If it is not implemented can it be done in future versions wheneverr docker sets the network configuration inline with hostname or perform a  init.d/network or service network restart  after hostname is set!!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
