### ISSUE TITLE
Swarm mode templating support

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#31218]
Currently, swarm mode support templating for the following elements :

- Hostname
- Mounts
- Environment variables

We might want to extend this support in the future, and this issue is to track that. Based on the comments, we'll keep this list up-to-dated and will track implementation of it.

- [ ] constraints ?
- [ ] network ?
- [ ] labels (label, container-label) ?

**Comment by aaronlehmann** [comment]
Linking https://github.com/docker/swarmkit/pull/2133

**Comment by olljanat** [comment]
@vdemeester @thaJeztah docker/swarmkit#2133 have been merged long time ago so this probably can be closed?

**Comment by vdemeester** [comment]
I think we can close yes :upside_down_face:
