### ISSUE TITLE
[tests] cli unit tests

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#31217]
This issue is to keep track of unit test for the cli (i.e. `cli/commands` package and sub-packages).

- [ ] bundlefile
- [ ] checkpoint
- [ ] container
- [x] formatter
- [x] idresolver @adshmh
- [ ] image @icapurro #32248 
- [ ] inspect
- [ ] network
- [x] node
- [ ] plugin @adshmh 
- [ ] prune
- [ ] registry
- [x] secret @adshmh 
- [ ] service
- [ ] stack @adshmh 
- [x] swarm
- [ ] system
- [ ] task
- [x] volume (https://github.com/docker/docker/pull/31124)

The `swarm`, `node` and `volume` packages are example on how to write those tests (but they probably can be enhance, and enhancement are always welcome ).

- In order to write tests for these, you'll have to create more builder (`cli/internal/test/builders`) for objects that are not yet there.
- You can also use `golden` files (see examples)
- For each of these package, there is some integration tests (in `integration-cli`) that could be removed. I tried to mark them when I saw them, but it's not complete yet. I'll try to update this issue with a list of integration test that could be gone for each packages.

**Comment by adshmh** [comment]
#dibs on stack unit tests.

**Comment by adshmh** [comment]
#dibs on cil/command/secret unit tests.
@vdemeester I am working on all the commands in 'secret' package as a single commit. Should I change to a separate PR for each command?

**Comment by vdemeester** [comment]
@adshmh depends on how you feel. Should be ok in one PR 😉

**Comment by adshmh** [comment]
#dibs on idresolver

**Comment by adshmh** [comment]
#dibs on cli/command/plugin

**Comment by vdemeester** [comment]
Now that `docker/cli` is moved away from the repository, see https://github.com/docker/cli/issues/37 to follow updates on this 😉
