### ISSUE TITLE
Add/Manage user-specified metadata (i.e. labels) to stacks

### ISSUE THREAD

**Issue by vovimayhem** [moby/moby#31229]
I've been watching lately a lot of stuff (videos & such) about big companies using a microservices-oriented architecture. I unavoidingly ended watching Petter Måhlén's ["Modeling Microservices at Spotify"](https://clusterhq.com/2016/03/22/microservices-spotify-petter-mahlen/) talk.

Thinking about how Docker (with swarm mode, etc) could allow us to build applications and tools similar to the Spotify's System-Z app... Is there on the roadmap any way to leverage the metadata (i.e. labels) I've seen you guys use on the swarm "stack" objects (and related objects such as services, etc) to enable us to display a list of stacks, and save/retrieve custom metadata said application could interpret as domain models, or some other data that helps us understand what each stack does & how they relate to others?

**Comment by thaJeztah** [comment]
stacks are currently a client-side implementation; the  docker CLI reads the stack or docker-compose file, and based on that definition, creates a network, services, volumes etc. Each component is given a label to relate it to a specific stack, which allows the client to (e.g.) list all stacks (`docker stack ls`), and services that belong to that stack (`docker stack services`).

As a user, you can set similar labels (`docker service create --label=org.foo.mylabel=myvalue` or `--container-label=org.foo.mylabel=myvalue`).

Perhaps you could add a concrete example of what functionality you'd like to see added?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
