### ISSUE TITLE
Swarm mode with mode=host and port is already in use by service on another host.

### ISSUE THREAD

**Issue by tlvenn** [moby/moby#31249]
Hi,

I am using docker swarm mode (1.13) and I have 2 services A and B.
Both services publish ports using exclusively `mode=host` and both services have placement constraint on a different server.

Now the issue is that both services listen of port 443. Once the first service starts, the second is failing to start with the following error:

`Error response from daemon: rpc error: code = 3 desc = port '443' is already in use by service 'A' (pjo2sx4wx3apaejqhgevpkvqs)`

I am guessing there is a check somewhere that does not take into account that service A is using `mode=host` and so it's not mutually exclusive to run services on the same port anymore as far as the services are not running on the same host.

docker version
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by aboch** [comment]
> I am guessing there is a check somewhere that does not take into account that service A is using mode=host

Right. [checkPortConflicts()](https://github.com/docker/swarmkit/blob/master/manager/controlapi/service.go#L359)  must be changed to take that into account.

**Comment by ginjo** [comment]
I also tripped over this issue. Same scenario as the OP (also docker 1.13). I'm trying to publish a service port with ```mod=host```, on a single worker node. However once the port has been published on the manager node, I get the port-already-in-use error. I'm looking for workarounds, other than manually starting up the service with ```docker run```, but not finding anything yet.

**Comment by bhdrk** [comment]
I have same issue.

**Comment by ginjo** [comment]
Any updates on this? I tried version 17.04.0-dev, build 3fe2730, but I'm still getting port-in-use error. Happy to help if there's anything I can do...

**Comment by winstonk** [comment]
Ditto. Just had this issue today when trying to use `--constraint node==`. Running `Docker version 17.03.0-ce, build 60ccb22` on DigitalOcean.

**Comment by tlvenn** [comment]
@thaJeztah any chance to get someone from Docker assigned to this issue ? As pointed out by @aboch , the function that need to be patched is [checkPortConflicts()](https://github.com/docker/swarmkit/blob/master/manager/controlapi/service.go#L359)

**Comment by erinnovations** [comment]
+1, same issue here

**Comment by ilp1995** [comment]
+1, some issue here too!!!
FATA[0010] The following required ports are already in use on your host - 443.

**Comment by aaronlehmann** [comment]
Opened https://github.com/docker/swarmkit/pull/2177 for this

**Comment by ginjo** [comment]
Ok newb question here. I see that this issue appears to be fixed in swarmkit - very exciting! Is there a way I can try the fix in docker swarm-mode? I downloaded the latest docker master binaries, however I don't think swarmkit fixes are merged in yet. Or... is swarmkit a separate binary that needs to be updated along with docker? Sorry, I'm a little confused as to how swarmkit fits in with docker.
Thanks!

**Comment by thaJeztah** [comment]
@ginjo swarmkit is used as a package/component in this repository and source files are vendored in; see https://github.com/moby/moby/pull/33170 which pulls in the changes that fixed this issue

It las not merge yet

**Comment by ginjo** [comment]
@thaJeztah Thanks, that makes perfect sense.

**Comment by aaronlehmann** [comment]
@ginjo: It has been merged now.

**Comment by meyskens** [comment]
Has anybody got this to work? I rebuilt from the master and still have the error. I only deployed the dev version to one host. Should I deploy to all?

**Comment by ginjo** [comment]
Yes, works great using master binaries from 5/22  👍

**Comment by Goram** [comment]
Will this come in 17.0.6 and when?

**Comment by aaronlehmann** [comment]
Yes, it will be part of the 17.06 release, which is currently near the end of the release candidate phase.

**Comment by seffyroff** [comment]
I see the same issue, running docker engine 17.11 on a worker and 17.12 on master.  Swarm has a service (portainer:amd64)  deployed on port 9000(ingress), and I wish to deploy a service (portainer:arm64) to a specific node using constraint engine.labels.arch == arm64 and port 9000 host network.  Is this expected to work?  Should I change the service running on ingress to host networking too?

**Comment by ryancastle** [comment]
Using `stop-first` in the deployment config is apparently fairly important to prevent dead-locks on the port when using host most. Service updates will fail with `host-mode port already in use on 1 node` when `start-first` is used. 

```
    ports:
      - { published: 21, target: 21, mode: host }
    deploy:
      mode: global
      update_config:
        order: stop-first
```
