### ISSUE TITLE
docker-engine 1.12.6, 1.13.0, 1.13.1 blocks DHCP

### ISSUE THREAD

**Issue by cynici** [moby/moby#31245]
**Description**

On a docker host (Ubuntu trusty) running several containers, I also run a libvirt VM. The VM is configured to use bridged networking to obtain its address via DHCP directly from the LAN.

This setup has been working perfectly until I upgraded docker-engine from version 1.12.5 to any of these:
* 1.12.6
* 1.13.0
* 1.13.1

**Steps to reproduce the issue:**
1. Upgrade docker-engine and reboot

**Describe the results you received:**
1. On startup, the VM fails to obtain DHCP address from the LAN.

**Describe the results you expected:**
This setup works in all earlier versions of docker-engine including 1.12.5.

**Additional information you deem important (e.g. issue happens only occasionally):**
Problem is repeatable and consistent

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 19
 Running: 9
 Paused: 0
 Stopped: 10
Images: 486
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 559
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-110-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.88 GiB
Name: XXXXX
ID: 6FLK:F2FB:NGJ6:FSLF:EEOL:DRJA:FADC:FKHY:XNNH:O6MW:HMLE:KIFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM bridged networking setup https://wiki.ubuntu.com/KvmWithBridge

**Comment by cpuguy83** [comment]
How is dhcp being achieved?
1.12.6 is a security fix only, I would not expect this to cause any issues with dhcp.
Does it work again if you downgrade to 1.12.5 on the same host?

**Comment by cynici** [comment]
As soon as I downgrade to 1.12.5, the libvirt VM immediately manage to obtain DHCP lease directly from the LAN as before.

I have tried using 1.13.0 and 1.13.1, both of them exhibited the same problem as 1.12.6

In libvirt bridged networking setup, the VM shares the same network interface card as the docker host.

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by sanimej** [comment]
@cynici Can you try to capture the DHCP traffic with docker 1.12.5 and 1.12.6 and see if there is any difference ?

**Comment by cynici** [comment]
@sanimej I did that now. The DHCP requests successfully leave the VM and arrive at the DHCP server on the LAN. But, the replies from the DHCP server are dropped at the docker host so the VM never receive any and gave up at some point.

**Comment by wenjianhn** [comment]
@cynici 
#28257 introduced a fix which switched the default iptables FORWARDING policy to DROP.

Could you paste the output of the following command? 

> sudo iptables-save -c

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
