### ISSUE TITLE
Does docker swarm networking support vxlan traffic over ipv6?

### ISSUE THREAD

**Issue by jonathan-kosgei** [moby/moby#31268]
Does docker swarm networking support vxlan traffic over ipv6?

I'd like to implement purely ipv6 networking.

**Comment by aboch** [comment]
No, at the moment it does not.

**Comment by jonathan-kosgei** [comment]
@aboch how soon might it be possible?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
