### ISSUE TITLE
Huge latency to connect webapp to docker mysql container

### ISSUE THREAD

**Issue by Pierpaolo1992** [moby/moby#31285]
**Description**

Hi, sorry if i post here, probably here you support only bug, but i've written also on StackOverflow and Docker Forum but i've found no solution to my problem. So.. sorry for the question.

I'm trying to port my web-app created on Windows, using Hibernate, XAMPP for Apache tomcat and mysql server, to Linux, using Docker. After i've done the following steps, The first feature of my web.app is login/register form: On Windows all works perfectly, but with container there is latency about tens of minutes.. and sometime there is also 500 http error!!

**Steps to reproduce the issue:**
1. `docker run -d --name mysql-phpmyadmin -p 127.0.0.1:8686:80 -p 127.0.0.1:3306:3306 grzesiekb/mysql-phpmyadmin` 

2. `docker run -d -p 8484:8080 -p 8007:8009 --name tomcat8-linked --link mysql-phpmyadmin:mysqlphp tomcat:8.0-jre8`  and then deploy under webapps/ folder my warfile

3. This is my hibernate.cfg.xml

```
<!DOCTYPE hibernate-configuration PUBLIC
        "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
        "http://www.hibernate.org/dtd/hibernate-configuration-3.0.dtd">

<hibernate-configuration>
        <session-factory>

<!-- queste configurazioni sono per il testing in locale  -->
<property name="connection.driver_class">com.mysql.jdbc.Driver</property>
<property name="connection.url">jdbc:mysql://mysqlphp:3306/at_db</property>

<property name="hibernate.connection.username">root</property>
<property name="connection.password">mysql_pass</property>


<!-- JDBC connection pool (use the built-in) -->
<property name="connection.pool_size">1</property>

<!-- SQL dialect -->
<property name="dialect">org.hibernate.dialect.MySQLDialect</property>
<!-- Enable Hibernate's automatic session context management -->
<property name="current_session_context_class">thread</property>
<!-- Disable the second-level cache -->
<property name="cache.provider_class">org.hibernate.cache.NoCacheProvider</property>

<property name="show_sql">false</property>
<!--<property name="hibernate.hbm2ddl.auto">create-drop</property>  se al posto di update metto create, mi cancella il db e lo rifa -->
<property name="hbm2ddl.auto">update</property>
                <!-- Entity -->

<mapping class="com.ATBoscoCastellano.Entity.ClientUser" />
<mapping class="com.ATBoscoCastellano.Entity.GenericUser" />
<mapping class="com.ATBoscoCastellano.SessionManagement.SessionToken" />
<mapping class="com.ATBoscoCastellano.Entity.Post" />
<!-- <mapping class="it.boscus.StarFoods.entity.ExampleEmbeddableIDClass2" /> -->


        </session-factory>
</hibernate-configuration>
```
4. This is my mysql-phpmyadmin : 
```
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.
[client]
port            = 3306
socket          = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.
[mysqld_safe]
socket          = /var/run/mysqld/mysqld.sock
nice            = 0

[mysqld]
#
# * Basic Settings
#
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address = 0.0.0.0
#
# * Fine Tuning
#
key_buffer              = 16M
max_allowed_packet      = 16M
thread_stack            = 192K
thread_cache_size       = 8
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched
myisam-recover         = BACKUP
#max_connections        = 100
#table_cache            = 64
#thread_concurrency     = 10
#
# * Query Cache Configuration
#
query_cache_limit       = 1M
query_cache_size        = 16M
#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
general_log_file        = /var/log/mysql/mysql.log
general_log             = 1
#
# Error log - should be very few entries.
#
log_error = /var/log/mysql/error.log
#
# Here you can see queries with especially long duration
#slow_query_log_file = /var/log/mysql/mysql-slow.log
#slow_query_log      = 1
#long_query_time = 2
#log_queries_not_using_indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id              = 1
#log_bin                        = /var/log/mysql/mysql-bin.log
expire_logs_days        = 10
max_binlog_size         = 100M
#binlog_do_db           = include_database_name
#binlog_ignore_db       = include_database_name

# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem


[mysqldump]
quick
quote-names
max_allowed_packet      = 16M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer              = 16M

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#
!includedir /etc/mysql/conf.d/
```
5. By default, this mysql container only allows connection from localhost: for allowing connections from everywhere, i've done:

```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
 FLUSH PRIVILEGES;
```

Then i've imported my dql dump via phpmyadmin

**Describe the results you received:**

Huge latency, related to i don't know which problem. Probably it's a DNS problem related to Docker network.

**Describe the results you expected:**

Connection to the db immediately, like in Windows using XAMPP

**Output of `docker version`:**

```
Docker version 1.13.1, build 092cba3

```

**Output of `docker info`:**

```
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-63-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6 GiB
Name: pignasecca
ID: CWUK:ZGGS:XY7A:FJFS:UD4S:NX5P:AI5S:CMDO:KOMC:EDGI:GEB4:BOGQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by TristanCP** [comment]
You should try to make your setup as standard as possible to avoid bugs due to non-standard practice.

* Use official or at least popular images (with millions of pulls) instead of your mysql-phpmyadmin with a hundred pulls : 
  * https://hub.docker.com/search/?isAutomated=0&isOfficial=1&page=1&pullCount=0&q=mysql
  * https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=phpmyadmin

* I'm not sure why you declare ip with host port and container port, maybe don't do this if it's not necessary
* Don't use --link since it's [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), create a bridge network and run each container with --network my-bridge-network.

**Comment by Pierpaolo1992** [comment]
Thanks for your answer, @TristanCP . I've tried with this new mysql container:
`docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=pass -p 3307:3306 -d mysql`

then this one for phpmyadmin:
`docker run': docker run --name myadmin -d --link some-mysql:mysql -p 8686:80 phpmyadmin/phpmyadmin`

I've given value "0.0.0.0" to bind_address in mysql config file;
then i created a bridge docker network, i've attached tomcat and mysql containers; then, in the hibernate.cfg.xml file, i've pointed to <mysql_container_ip>:3306/at_db  with user "root" and password "pass". But the problem remains!

**Comment by thaJeztah** [comment]
Some things to take into account;

- Do not _publish_ ports unless you want them to be accessible externally (i.e., don't `-p ...`). Publishing ports is _not_ needed for containers to communicate with each other on the internal docker network
- If you want containers to be able to communicate with each other, they need to be in the same network. Docker networks provide a "sandbox" that limits access to other containers on the same network
- to narrow down what's causing the latency, bring your test-case down to the absolute minimum, i.e., try using different ways to check latency instead of using tomcat

For example;

create a network
```bash
docker network create my-net
```

run a mysql container on that network, and give it a name (`my-db`) other containers on the same network can now connect to that container using `my-db` as hostname. As explained above, there's no need to _publish_ ports.

```bash
docker run -d --network my-net --name my-db -e MYSQL_ROOT_PASSWORD=pass mysql
```

Run another container on the same network and check if the connection has the same latency issue you have with the tomcat container

```bash
docker run --rm --network my-net busybox ping my-db
PING my-db (172.23.0.2): 56 data bytes
64 bytes from 172.23.0.2: seq=0 ttl=64 time=0.109 ms
64 bytes from 172.23.0.2: seq=1 ttl=64 time=0.075 ms
^C
--- my-db ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.092/0.109 ms
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
