### ISSUE TITLE
Huge container log

### ISSUE THREAD

**Issue by ptroff** [moby/moby#31308]
**Description**
Docker starts to send empty lines to container log after upgrade from 1.3.0 to 1.3.1.
It happens with only one container running asterisk. It was built on my own Dockerfile to copy asterisk config into container.

Container log in /var/lib/docker/... after asterisk service starts fills with 
`{"log":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000......\u0000","stream":"stdout","time":"2017-02-14T17:47:42.312998462Z"}`
It grow up to gigs for one hour.
I run image with command
`docker run --net=host -d --name asterisk --rm asterisk:0.2`
I found that if I add -t to command, image runs normal without any problems.
`docker run --net=host -d -t --name asterisk --rm asterisk:0.2`

**Steps to reproduce the issue:**
1. Install Docker 1.3
2. Build asterisk image
`docker build -t asterisk:0.2 --rm -f Dockerfile.asterisk .`
3. Run it
`docker run --net=host -d --name asterisk --rm asterisk:0.2`
All is OK
4. Now upgrade Docker to 1.3.1 and reboot
5. Run again
`docker run --net=host -d --name asterisk --rm asterisk:0.2`
6. Look at quickly growing log: /var/lib/docker/containers/<container>/<container>-json.log

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 38
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 72
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: SCQX001
ID: HSPH:EO43:MPJA:7B3L:I7EO:4WCE:ZV4F:UAHK:WG3B:JYP5:NEXH:3NNV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

[Dockerfile.asterisk.txt](https://github.com/docker/docker/files/797815/Dockerfile.asterisk.txt)

**Comment by unclejack** [comment]
This issue is related to asterisk itself. https://github.com/moby/moby/issues/21181 is related.

It seems this is related to asterisk itself which prints those empty lines when it doesn't run in a tty. We'd see the issue with other software as well if it had been a bug.

**Comment by thaJeztah** [comment]
Closing as this doesn't appear to be a bug in our code
