### ISSUE TITLE
Docker Build Image fails with 'NOT FOUND' executing download-frozen-image-v2.sh

### ISSUE THREAD

**Issue by srikanteswartalluri** [moby/moby#31320]
I am seeing the same issue as  #21528

 ---> b348bdd9bdd8
Step 47/53 : COPY contrib/download-frozen-image-v2.sh /go/src/github.com/docker/docker/contrib/
 ---> Using cache
 ---> e2d156503b4b
Step 48/53 : RUN ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	buildpack-deps:jessie@sha256:25785f89240fbcdd8a74bdaf30dd5599a9523882c6dfc567f2e9ef7cf6f79db6 	busybox:latest@sha256:e4f93f6ed15a0cdd342f5aae387886fba0ab98af0a102da6276eaf24d6e6ade0 	debian:jessie@sha256:f968f10b4b523737e253a97eac59b0d1420b5c19b69928d35801a6373ffe330e 	hello-world:latest@sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
 ---> Running in bbe4c55245fa
: No such file or directory
The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	buildpack-deps:jessie@sha256:25785f89240fbcdd8a74bdaf30dd5599a9523882c6dfc567f2e9ef7cf6f79db6 	busybox:latest@sha256:e4f93f6ed15a0cdd342f5aae387886fba0ab98af0a102da6276eaf24d6e6ade0 	debian:jessie@sha256:f968f10b4b523737e253a97eac59b0d1420b5c19b69928d35801a6373ffe330e 	hello-world:latest@sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7' returned a non-zero code: 127
make: *** [build] Error 127

**Comment by srikanteswartalluri** [comment]
docker-machine --version
docker-machine version 0.9.0, build 15fd4c7
Stalluri-MBP13:docker srikanteswararaotalluri$ docker --version
Docker version 17.03.0-ce-rc1, build ce07fb6
Stalluri-MBP13:docker srikanteswararaotalluri$

**Comment by thaJeztah** [comment]
@srikanteswartalluri can you add the output of `docker info` and `docker version` (not `--version`)?

**Comment by thaJeztah** [comment]
Also, can you check if docker didn't run out of disk space? This should do;

```
docker run --rm busybox sh -c 'df -h'
```

**Comment by srikanteswartalluri** [comment]
@thaJeztah , Please find the output of 'docker version' and 'docker info'

Stalluri-MBP13:~ srikanteswararaotalluri$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.11-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: QHFC:JO6V:ELNW:CSS4:GXO3:Z4TQ:5XEU:NKOA:3TMA:ZHWT:J3N5:C4LB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-02-28T11:38:18.173644384Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Stalluri-MBP13:~ srikanteswararaotalluri$ docker version
Client:
 Version:      17.03.0-ce-rc1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce-rc1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
Stalluri-MBP13:~ srikanteswararaotalluri$

**Comment by srikanteswartalluri** [comment]
@thaJeztah , there is no problem with disk space. I was literally following the instructions provided here @ https://docs.docker.com/opensource/project/set-up-dev-env/ . Is this document up to date?

Stalluri-MBP13:~ srikanteswararaotalluri$ docker run --rm busybox sh -c 'df -h'
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
4b0bc1c4050b: Pull complete
Digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
Status: Downloaded newer image for busybox:latest
Filesystem                Size      Used Available Use% Mounted on
overlay                  62.7G      1.3G     58.2G   2% /
tmpfs                   999.5M         0    999.5M   0% /dev
tmpfs                   999.5M         0    999.5M   0% /sys/fs/cgroup
/dev/vda1                62.7G      1.3G     58.2G   2% /etc/resolv.conf
/dev/vda1                62.7G      1.3G     58.2G   2% /etc/hostname
/dev/vda1                62.7G      1.3G     58.2G   2% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   999.5M         0    999.5M   0% /proc/kcore
tmpfs                   999.5M         0    999.5M   0% /proc/timer_list
tmpfs                   999.5M         0    999.5M   0% /proc/sched_debug
tmpfs                   999.5M         0    999.5M   0% /sys/firmware

**Comment by thaJeztah** [comment]
I just tried on a comparable setup, but was not able to reproduce the issue; these are the steps I used;

- checked out the docker/docker repository
- ran;

    make BIND_DIR=. binary shell

Can you check if your git repository is "clean" (`git status`), and if the line endings of the script are correct?

**Comment by srikanteswartalluri** [comment]
@thaJeztah 
Thanks for helping.
Following helped me to go ahead.
srikanteswararaotalluri@Stalluri-MBP13:~/github/docker$ dos2unix  contrib/download-frozen-image-v2.sh
dos2unix: converting file contrib/download-frozen-image-v2.sh to Unix format...
