### ISSUE TITLE
Multi-architecture support in Swarm mode

### ISSUE THREAD

**Issue by nishanttotla** [moby/moby#31348]
This issue tracks work on adding **automatic multi-arch support** to Swarm mode. In other words, for services that run images with fat manifests, tasks will be scheduled on only those nodes which can actually run the image.

### What does this give us?
The ability to automatically schedule service tasks on nodes that are capable of running them, without having to do do it manually.

### How to do it?
The proposed way of achieving this works in two steps:
1. The daemon looks at the manifest of the service image. If it is a fat manifest, the platform information is pulled out and passed to the Swarm manager.
2. The manager uses a platform filter to filter out nodes that cannot support a given image.

A proposal SwarmKit PR to implement the second step is here: https://github.com/docker/swarmkit/pull/1981

Here's a little more detail about the specifics:
- `service create` -- the daemon pulls manifest at the time it pulls image digest. If this is a fat manifest, then platform information is extracted and passed on to the Swarm manager. If there is no platform information to pass, the Swarm manager does not enable the platform filter
  - A pertinent question is whether we will allow the user to pass platform information in the future.
-  `service update` -- this is a little more involved, because we don't want to unnecessarily poll the registry to get the manifest.
  - In cases where the `--image` is not supplied with `service update`, we don't need to do anything, because we just assume that the image and all its platform-related requirements stay the same.
  - If the user does update the image, and it is required to reach the registry to obtain the digest, then we also get platform information, since we're reaching the registry anyway.
  - The interesting case is when the digest is provided (say by the user). Right now, we will not contact the registry in such a situation. For platform information, we do know at the manager level whether the digest of the new service spec is different from the existing one. If it isn't different, we don't need to do anything. If there is a change, then we want to contact the registry to get platform information. The only difference is that before, the user could update the service by providing a new digest, and skip the registry lookup, whereas now it would entail the registry lookup.

### What will it cost?
The only cost is an addition registry round-trip during `service create` and sometimes during `service update`. While in my tests, this cost has been minimal, it is something to be aware of.

**Comment by thaJeztah** [comment]
Wondering;
- Should there be a way to _specify_ which architecture you want a service to run on? For example, if a fat manifest has both `arm` and `amd64`, and I want to force using `amd64`, am i able to do so? Or would that be an exercise for the user (setting labels on the node, and using that as a constraint)
- Would there be a need to "pin" to an architecture upon deployment. i.e.; if I deploy my service, and tasks get re-scheduled, should Swarm prefer nodes with the same architecture, or would that be fully random? (switching to a different architecture _should not_ make a difference, but are there cases where a different architecture gives a different behavior?)
- Continuing on the above; are there cases where (e.g.) persistent data is not architecture-agnostic? Thinking of a case where a service writes data to a distributed volume, and the task is re-scheduled on another architecture (but using the same distributed volume)

**Comment by clnperez** [comment]
Thanks for the tag @thaJeztah! 

Here are my thoughts, though I'm not professing to be a swarm expert.

* For omissions, if your fat manifest has two architectures for one image, I think you would be forced to create an arch-specific node constraints for your service -- and if you don't want to do that, just make your own fat manifest and take out (or split out/duplicate one image). Since a fat manifest is so lightweight, that should be pretty simple.
* For pinning, that sounds more like a "preference" than a hard pin. Swarm does already have arch-specific constraints you can set. But if you just wanted to prefer one arch over another, that sounds like a cool swarm feature in  that I don't think (?) exists. Different architectures could definitely make a difference, esp if you have specific configurations you've set up on one kind of platform but you'd be willing to sacrifice your tuning if you run out of your high-perf nodes.
* I do think you could have a scenario where data could be an issue (e.g. s390 is BE). I think that's something you'd want to handle outside of swarm, or using constraints.

**Comment by nishanttotla** [comment]
Those are very good questions, @thaJeztah, and here's what I learned based on a brief chat with @friism. I'll let him add more clarifications.
- There might be value in allowing the user to specify which architecture. To what extent to allow it, and how to deal with it will have to be figured out, but this is more relevant in the next two points.
- It's generally not the best idea to have a cross-platform service (correct me if I'm wrong here). Whether we let the manager decide which arch to prefer, or we allow the user to input a (soft or hard) specification, it's something to think about.
- Continuing on the above case, we probably want to "pin" a service that has volumes etc. to a certain platform. How this would work practically, with nodes joining or leaving the Swarm is a question we must answer.

All said and done, I suppose this is not a use case that most users will encounter, so making the best possible assumptions should be okay.

WDYT @thaJeztah @clnperez @friism @aluzzardi ?

**Comment by duglin** [comment]
@thaJeztah wrote:
> Should there be a way to specify which architecture you want a service to run on?

I think you can do this today with the current filtering mechanisms - we do it in some of our stuff.

**Comment by clnperez** [comment]
@nishanttotla, as for "It's generally not the best idea to have a cross-platform service (correct me if I'm wrong here)," I could think of a few scenarios where you'd want this:
- A multi-arch CI setup where everything should run the same and pass the same functional or interoperability tests.
- A service such as an agent (for management, logging, heartbeats, or any of a number of things) that runs on all nodes in a swarm. There may be other platform-specific services created for the same swarm.

**Comment by friism** [comment]
@clnperez I think those are excellent examples, I hadn't thought about them. They're a little specialized though, and I think in the general case, having tasks for a particular service bounce back and forth on nodes with different architectures and operating systems might cause problems.

> However, I don't think anyone running an heterogenous swarm, with both windows and linux, nodes would want docker service create redis to cause tasks to be scheduled alternatingly on both windows and linux nodes. Even with a linux-only swarm with mixed ARM/x86 I suspect that could be a problem because redis running on different architectures might behave differently.

 - https://github.com/docker/swarmkit/pull/1981#issuecomment-283837150

**Comment by nishanttotla** [comment]
I think based on the above comments, here's how I'd summarize:
- The first problem to solve is that a task that can't run on a node should not be scheduled there, period. And it would be ideal to do this automatically (because we have this information already, so why not use it?)
- If a task can run on multiple platforms, and they exist on the cluster, then the user should be allowed to specify what platform they want it to run on, in which case we don't bother with any automation, and just use what the user wants. (@duglin you mentioned that you do this already in some of your stuff. Can you share more details?)
- For services such as logging etc. that must run across multiple platforms, there are no problems because that happens even now anyway, and going forward, lack of platform constraints would continue to mean the same thing.

**Comment by duglin** [comment]
we have cases where we start a `--mode=global` service, where the image is for s390x, and then specify on the service's constraints `node.platform.os==linux node.platform.arch==s390x`.

**Comment by thaJeztah** [comment]
@duglin looks like `platform` is not documented for constraints; https://github.com/docker/docker/blob/v17.03.0-ce/docs/reference/commandline/service_create.md#specify-service-constraints---constraint

**Comment by duglin** [comment]
no comment on that - all I know is that it seems to work :-)

**Comment by thaJeztah** [comment]
Heh, yes, I wasn't aware of that, so if it does, it should probably be documented :smile:

ping @aaronlehmann @aluzzardi any other options we missed in the documentation? ^^

**Comment by aaronlehmann** [comment]
These are documented in swarmkit's `README.md`.

I think they were added in a commit to a swarmkit, and there was no corresponding commit elsewhere to update the docs.

The only other constraint I see which is not documented is `node.ip`.

For reference, this is where all constraints are defined: https://github.com/docker/swarmkit/blob/master/manager/constraint/constraint.go#L107

**Comment by nishanttotla** [comment]
I think it's alright to close this issue now?

cc @thaJeztah

**Comment by thaJeztah** [comment]
@nishanttotla I see https://github.com/moby/moby/issues/31897 linked to this one and still open; is that a requirement for this feature?

**Comment by nishanttotla** [comment]
@thaJeztah I don't think #31897 is directly related to the content of this issue, although that issue should probably fall under the same umbrella of multi-arch support.

**Comment by thaJeztah** [comment]
Alright, let's close this one then 👍
