### ISSUE TITLE
Docker Active but Create Container failed with error and sandbox: failed to get link by name 

### ISSUE THREAD

**Issue by khanasif2** [moby/moby#31376]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
[root@host4 ~]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
[root@host4 ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.5 GiB
Name: host4.forum-asia.org
ID: PRDX:Z62V:H3GQ:JED4:6DX7:6WUM:MESG:OIGP:UMNR:5KUD:SJBA:RJAQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
[root@host4 ~]# systemctl status docker
* docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-DeviceMapper.conf, overlay.conf
   Active: active (running) since Fri 2017-02-24 01:34:28 EST; 3 days ago
     Docs: https://docs.docker.com
 Main PID: 1978 (dockerd)
    Tasks: 33
   Memory: 1.6G
      CPU: 9min 38.993s
   CGroup: /system.slice/docker.service
           |-1978 dockerd -H fd:// --storage-driver=overlay
           `-1994 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
```

```
Feb 24 04:41:31 host4.forum-asia.org docker[1978]: time="2017-02-24T04:41:31.297360981-05:00" level=error msg="Handler for POST /v1.26/containers/4e56dd84d1bb1c7409aeb981-05:00" level=error msg="Handler for POST /v1.26/containers/4e56dd84d1bb1c7409aeb68903861668f038121022faee129f13fdeb50132c1c/start returned error: oci runtime errorb68903861668f038121022faee129f13fdeb50132c1c/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334:r: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , st: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T04:41:31-05:00\\\\\\\" level=fatal msg=\\\\\\\"failedtderr: time=\\\\\\\"2017-02-24T04:41:31-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth1244ecc to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth1244ecc\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 05:18:43 host4.forum-asia.org docker[1978]: time="2017-02-24T05:18:43.738201024-05:00" level=error msg="containerd: start container" error="oci runtime error: c024-05:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth37c231b to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface veth37c231b to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth37c231b\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n" id=fa72791194cf7a14c56574140d7a0c13891743ad0f247a1aa892a15f84c8bd75
Feb 24 05:18:43 host4.forum-asia.org docker[1978]: time="2017-02-24T05:18:43.738866291-05:00" level=error msg="Create container failed with error: oci runtime error: c291-05:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth37c231b to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface veth37c231b to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth37c231b\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 05:18:43 host4.forum-asia.org docker[1978]: time="2017-02-24T05:18:43.805603927-05:00" level=error msg="Handler for POST /v1.26/containers/fa72791194cf7a14c5657927-05:00" level=error msg="Handler for POST /v1.26/containers/fa72791194cf7a14c56574140d7a0c13891743ad0f247a1aa892a15f84c8bd75/start returned error: oci runtime error74140d7a0c13891743ad0f247a1aa892a15f84c8bd75/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334:r: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , st: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failedtderr: time=\\\\\\\"2017-02-24T05:18:43-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth37c231b to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth37c231b\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 05:58:07 host4.forum-asia.org docker[1978]: time="2017-02-24T05:58:07.750970037-05:00" level=error msg="containerd: start container" error="oci runtime error: c037-05:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth015786e to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface veth015786e to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth015786e\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n" id=39029be3210e181c62b5307a67d6373c8aeec5ebfb76245102d2b2e004458201
Feb 24 05:58:07 host4.forum-asia.org docker[1978]: time="2017-02-24T05:58:07.751882224-05:00" level=error msg="Create container failed with error: oci runtime error: c224-05:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth015786e to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface veth015786e to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth015786e\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 05:58:07 host4.forum-asia.org docker[1978]: time="2017-02-24T05:58:07.809538870-05:00" level=error msg="Handler for POST /v1.26/containers/39029be3210e181c62b53870-05:00" level=error msg="Handler for POST /v1.26/containers/39029be3210e181c62b5307a67d6373c8aeec5ebfb76245102d2b2e004458201/start returned error: oci runtime error307a67d6373c8aeec5ebfb76245102d2b2e004458201/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334:r: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , st: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failedtderr: time=\\\\\\\"2017-02-24T05:58:07-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth015786e to sandbox: failed to get link by name \\\\\\\\\\\\\\\"veth015786e\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 06:11:13 host4.forum-asia.org docker[1978]: time="2017-02-24T06:11:13.881401676-05:00" level=error msg="containerd: start container" error="oci runtime error: c676-05:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface vethd71bb15 to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface vethd71bb15 to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vethd71bb15\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n" id=840bd2119a0a445da813edf3faa7617d5d34e53d6f02f5776bad22577eaf7a04
Feb 24 06:11:13 host4.forum-asia.org docker[1978]: time="2017-02-24T06:11:13.882214966-05:00" level=error msg="Create container failed with error: oci runtime error: c966-05:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: rucontainer_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderunning prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed torr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface vethd71bb15 to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vo add interface vethd71bb15 to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vethd71bb15\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
Feb 24 06:11:13 host4.forum-asia.org docker[1978]: time="2017-02-24T06:11:13.933383878-05:00" level=error msg="Handler for POST /v1.26/containers/840bd2119a0a445da813e878-05:00" level=error msg="Handler for POST /v1.26/containers/840bd2119a0a445da813edf3faa7617d5d34e53d6f02f5776bad22577eaf7a04/start returned error: oci runtime erroredf3faa7617d5d34e53d6f02f5776bad22577eaf7a04/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334:r: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , st: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failedtderr: time=\\\\\\\"2017-02-24T06:11:13-05:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface vethd71bb15 to sandbox: failed to get link by name \\\\\\\\\\\\\\\"vethd71bb15\\\\\\\\\\\\\\\": Link not found\\\\\\\" \\\\n\\\"\"\n"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
[root@host4 ~]# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

[root@host4 ~]# uname -r
4.4.0-64-generic

[root@host4 ~]# docker -v
Docker version 1.13.1, build 092cba3
```

```
[root@host4 ~]# docker run hello-world
container_linux.go:247: starting container process caused "process_linux.go:334:                                                                          running prestart hook 0 caused \"error running hook: exit status 1, stdout: , s                                                                         tderr: time=\\\"2017-02-27T06:05:58-05:00\\\" level=fatal msg=\\\"failed to add                                                                          interface veth407fa9e to sandbox: failed to get link by name \\\\\\\"veth407fa9e                                                                         \\\\\\\": Link not found\\\" \\n\""
docker: Error response from daemon: oci runtime error: container_linux.go:247: s                                                                         tarting container process caused "process_linux.go:334: running prestart hook 0                                                                          caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2017-02-2                                                                         7T06:05:58-05:00\\\" level=fatal msg=\\\"failed to add interface veth407fa9e to                                                                          sandbox: failed to get link by name \\\\\\\"veth407fa9e\\\\\\\": Link not found\                                                                         \\" \\n\"".
ERRO[0000] error getting events from daemon: net/http: request canceled
```

**Comment by khanasif2** [comment]
any update? regarding this issue

**Comment by phpmypython** [comment]
currently experiencing the same issue. any updates?

**Comment by aboch** [comment]
Anything interesting in the kernel logs or in the audit.log if present  (/var/log/audit/audit.log or  /var/log/audit.log) about that specific veth interface ?

**Comment by phpmypython** [comment]
This is the output of the kern.log when trying to run the hello-world image.

```Mar  3 13:41:57 ust-mi-lin-prod-1 kernel: [  670.645720] aufs au_opts_verify:1597:dockerd[2829]: dirperm1 breaks the protection by the permission bits on the lower branch
Mar  3 13:41:57 ust-mi-lin-prod-1 kernel: [  670.685753] aufs au_opts_verify:1597:dockerd[2829]: dirperm1 breaks the protection by the permission bits on the lower branch
Mar  3 13:41:57 ust-mi-lin-prod-1 kernel: [  670.728727] aufs au_opts_verify:1597:dockerd[2829]: dirperm1 breaks the protection by the permission bits on the lower branch
Mar  3 13:41:57 ust-mi-lin-prod-1 kernel: [  670.729705] device veth5e732a0 entered promiscuous mode
Mar  3 13:41:57 ust-mi-lin-prod-1 kernel: [  670.751340] eth6: renamed from vethb6cfe24```

**Comment by khanasif2** [comment]
kern.log
Feb 27 06:05:58 host4 kernel: [276474.962697] device veth12d79b4 entered promiscuous mode
Feb 27 06:05:58 host4 kernel: [276474.966397] eth24: renamed from veth407fa9e

**Comment by khanasif2** [comment]
@abouch @thaJeztah ? still waiting for your reply and for some solution

**Comment by aboch** [comment]
It is very strange because 

```
failed to add interface veth407fa9e to sandbox: failed to get link by name "veth407fa9e": Link not found
```

comes either from https://github.com/docker/docker/blob/v1.13.1/vendor/github.com/docker/libnetwork/osl/interface_linux.go#L267 
or from https://github.com/docker/docker/blob/v1.13.1/vendor/github.com/docker/libnetwork/osl/interface_linux.go#L288

but we know that https://github.com/docker/docker/blob/v1.13.1/vendor/github.com/docker/libnetwork/osl/interface_linux.go#L297 
was succesfully executed because of the kernel log:
```
Feb 27 06:05:58 host4 kernel: [276474.966397] eth24: renamed from veth407fa9e
```

**Comment by khanasif2** [comment]
I have reinstall dockers and now when I check the docker status, it is active like before but have some different errors

 level=error msg="Handler for POST /v1.27/containers/c6115296a328cf44a4b1c02c9fad93743726ea9ecc3a483638d9cd5b8665a666/start returned error: oci runtime error
046-04:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
980-04:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
423-04:00" level=error msg="Handler for POST /v1.27/containers/cc4beba0717a085261d23dfd8a1ed349dc0e613824ffd716724695f35e2fff15/start returned error: oci runtime error
468-04:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
715-04:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
071-04:00" level=error msg="Handler for POST /v1.27/containers/bfa78a010088742a0a109bce8421a52c9c20996924fab76479c37fdc72f99c62/start returned error: oci runtime error
346-04:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
136-04:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: ru
598-04:00" level=error msg="Handler for POST /v1.27/containers/743ad960f20543255be014106b5a6a196aa6936d19c88e1397c7ea6419895b32/start returned error: oci runtime error

**Comment by khanasif2** [comment]
[root@host4 ~]# docker run hello-world
container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2017-04-03T06:08:21-04:00\\\" level=fatal msg=\\\"failed to add interface vethc3d8318 to sandbox: failed to get link by name \\\\\\\"vethc3d8318\\\\\\\": Link not found\\\" \\n\""
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 0 caused \"error running hook: exit status 1, stdout: , stderr: time=\\\"2017-04-03T06:08:21-04:00\\\" level=fatal msg=\\\"failed to add interface vethc3d8318 to sandbox: failed to get link by name \\\\\\\"vethc3d8318\\\\\\\": Link not found\\\" \\n\"".
ERRO[0000] error getting events from daemon: net/http: request canceled

**Comment by khanasif2** [comment]
I am still unable to run the Container? @abouch @thaJeztah ?

[root@host4 ~]# sudo docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.5 GiB
Name: host4.forum-asia.org
ID: PRDX:Z62V:H3GQ:JED4:6DX7:6WUM:MESG:OIGP:UMNR:5KUD:SJBA:RJAQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by khanasif2** [comment]
When I run this command

sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=host4\\.nextcloud-forum-asia\\.org' --restart always --cap-add MKNOD collabora/code

I get following error

86a7345401dc231475118925ec31cc61e042d0a4b620c41a6bad8d117862443f
docker: Error response from daemon: containerd: container not started.

**Comment by khanasif2** [comment]
[root@host4 ~]# journalctl -f -u docker.service
-- Logs begin at Thu 2017-04-06 06:38:40 EDT. --
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.502310090-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/86a7345401dc231475118925ec31cc61e042d0a4b620c41a6bad8d117862443f/shm: invalid argument"
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.523745560-04:00" level=error msg="Failed to start container 86a7345401dc231475118925ec31cc61e042d0a4b620c41a6bad8d117862443f: driver failed programming external connectivity on endpoint compassionate_turing (bcc777ea768d2cdbc62b79adfde6fbe20457b4ad91a6877f0336e94a14abeaef): Bind for 127.0.0.1:9980 failed: port is already allocated"
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.588953604-04:00" level=error msg="containerd: start container" error="containerd: container not started" id=46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.589718214-04:00" level=error msg="Create container failed with error: containerd: container not started"
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.655411847-04:00" level=error msg="Failed to start container 46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338: containerd: container not started"
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.655444290-04:00" level=info msg="Loading containers: done."
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.655487289-04:00" level=info msg="Daemon has completed initialization"
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.655499068-04:00" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
Apr 06 23:12:43 host4.forum-asia.org dockerd[16863]: time="2017-04-06T23:12:43.661204507-04:00" level=info msg="API listen on /var/run/docker.sock"
Apr 06 23:12:43 host4.forum-asia.org systemd[1]: Started Docker Application Container Engine.

**Comment by khanasif2** [comment]
[root@host4 ~]# systemctl status docker
* docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-DeviceMapper.conf, overlay.conf, override.conf
   Active: active (running) since Fri 2017-04-07 03:02:28 EDT; 7min ago
     Docs: https://docs.docker.com
 Main PID: 8271 (dockerd)
    Tasks: 27
   Memory: 22.3M
      CPU: 414ms
   CGroup: /system.slice/docker.service
           |-8271 /usr/bin/dockerd -H fd://
           `-8278 containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime runc



1392-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338/shm: invalid argument"
6396-04:00" level=error msg="Failed to start container 46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338: driver failed programming external connectivity on endpoint fervent_snyder (9458fae3b80bd7b55706fdc75ba7cf90611fa94f65f39dc05ca318c769bf09f0): Bind for 127.0.0.1:9980 failed: port is already allocated"
9489-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/9a1b18f4b3aebd0cda52f8150c765b5d91dd5dc855697d1605fb7fdf74866018/shm: invalid argument"
5489-04:00" level=error msg="Failed to start container 9a1b18f4b3aebd0cda52f8150c765b5d91dd5dc855697d1605fb7fdf74866018: driver failed programming external connectivity on endpoint ecstatic_ramanujan (94adada427d941addc6a68a6465274340f5fe79504c35cfda8a637c2a6e8df15): Bind for 127.0.0.1:9980 failed: port is already allocated"
0111-04:00" level=error msg="Failed to start container 86a7345401dc231475118925ec31cc61e042d0a4b620c41a6bad8d117862443f: containerd: container not started"
3670-04:00" level=info msg="Loading containers: done."
9614-04:00" level=info msg="Daemon has completed initialization"
5285-04:00" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
7100-04:00" level=info msg="API listen on /var/run/docker.sock"
Apr 07 03:02:28 host4.forum-asia.org systemd[1]: Started Docker Application Container Engine.

**Comment by khanasif2** [comment]
CGroup: /system.slice/docker.service
           |-8271 /usr/bin/dockerd -H fd://
           `-8278 containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime runc



1392-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338/shm: invalid argument"
6396-04:00" level=error msg="Failed to start container 46b7d2b15d493d3385f1c6d295b14b636ea16f4e6b1b3d508b6c5dd48bf1a338: driver failed programming external connectivity on endpoint fervent_snyder (9458fae3b80bd7b55706fdc75ba7cf90611fa94f65f39dc05ca318c769bf09f0): Bind for 127.0.0.1:9980 failed: port is already allocated"
9489-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/9a1b18f4b3aebd0cda52f8150c765b5d91dd5dc855697d1605fb7fdf74866018/shm: invalid argument"
5489-04:00" level=error msg="Failed to start container 9a1b18f4b3aebd0cda52f8150c765b5d91dd5dc855697d1605fb7fdf74866018: driver failed programming external connectivity on endpoint ecstatic_ramanujan (94adada427d941addc6a68a6465274340f5fe79504c35cfda8a637c2a6e8df15): Bind for 127.0.0.1:9980 failed: port is already allocated"
0111-04:00" level=error msg="Failed to start container 86a7345401dc231475118925ec31cc61e042d0a4b620c41a6bad8d117862443f: containerd: container not started"
3670-04:00" level=info msg="Loading containers: done."
9614-04:00" level=info msg="Daemon has completed initialization"
5285-04:00" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
7100-04:00" level=info msg="API listen on /var/run/docker.sock"
Apr 07 03:02:28 host4.forum-asia.org systemd[1]: Started Docker Application Container Engine.

**Comment by thaJeztah** [comment]
Hm, you have a different version of docker installed now, correct? (was 1.13.1, now 1.12.6)

This looks to be the problem;

> Bind for 127.0.0.1:9980 failed: port is already allocated"

Is something else listening on that port? Also; do you have any stopped containers on the host? Have you tried if removing those containers helps?

**Comment by khanasif2** [comment]
I have removed all those stopped containers and now in docker status it shows 

nerd.sock --shim containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime runc

61130-04:00" level=info msg="libcontainerd: new containerd process, pid: 10487"
76315-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
29162-04:00" level=info msg="Loading containers: start."
14342-04:00" level=info msg="Firewalld running: false"
08892-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
93266-04:00" level=info msg="Loading containers: done."
31258-04:00" level=info msg="Daemon has completed initialization"
40354-04:00" level=info msg="Docker daemon" commit=78d1802 graphdriver=overlay version=1.12.6
67210-04:00" level=info msg="API listen on /var/run/docker.sock"
er Engine.

**Comment by khanasif2** [comment]
perviously I had installed docker-engine but now I have installed docker.io

still no luck to run container

**Comment by khanasif2** [comment]
[root@host4 ~]# sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=host4\\.nextcloud-forum-asia\\.org' --restart always --cap-add MKNOD collabora/code
09becabfc7a9af43b37ce0bfadff945484fb12912825a6215003e943c4fde628
docker: Error response from daemon: containerd: container not started.

**Comment by khanasif2** [comment]
Finally I managed to run everthing but cannot open the doc file, error details are mentioned below:

I have Set up NextCloud Server on Ubuntu 16.04 with Apache, MariaDB and PHP7, I already have these settings  
 
    # Main websocket
  ProxyPassMatch "/lool/(.*)/ws$" wss://127.0.0.1:9980/lool/$1/ws nocanon

but still I am getting this error

Well, this is embarrassing, we cannot connect to your document. Please try again.

Wrong WOPISrc, usage: WOPISrc=valid encoded URI, or file_path, usage: file_path=/path/to/doc/

In My Docker Logs I am only getting this following error:

wsd-00026-25124 06:07:05.542798 [ client_ws_003b ] ERR  ClientRequestHandler::handleClientRequest: Exception: Invalid URI.| wsd/LOOLWSD.cpp:1245
wsd-00026-0030 06:07:07.603192 [ client_ws_003c ] ERR  ClientRequestHandler::handleClientRequest: Exception: Invalid URI.| wsd/LOOLWSD.cpp:1245

can anyone help @thaJeztah @aboch @GordonTheTurtle  ?
