### ISSUE TITLE
[Question] Can we manually stop a rolling update for a service?

### ISSUE THREAD

**Issue by allencloud** [moby/moby#31374]
Hi, All,

Can we manually stop a rolling update for a service?

Out of business concern, sometimes we need to stop a rolling update action manually, since we can not define every failure case in code.

Then when rolling update stopped, maybe after several hours, we need to consider whether to continue the rolling update or roll back. It is still a command sent to the service.

**Comment by aaronlehmann** [comment]
I don't think it's possible today. The concept sounds similar to https://github.com/docker/swarmkit/pull/1950. Perhaps it would be a good idea to mention this use case over there.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
