### ISSUE TITLE
Undocumented field in `GET /info` response

### ISSUE THREAD

**Issue by brb** [moby/moby#31386]
**Description**

The Docker API reference https://docs.docker.com/engine/api/v1.26/ does not document the `Swarm` field which is returned in a response of `GET /v1.26/info`. In addition, the field is included in [the Go client type definitions](https://godoc.org/github.com/docker/docker/api/types#Info).

Is it safe to use the undocumented field in client applications?

**Comment by cpuguy83** [comment]
I would never rely on something that is undocumented... that said it's likely just undocumented because no one documented it.

@thaJeztah ?

**Comment by brb** [comment]
Any update on this?

**Comment by thaJeztah** [comment]
I think the addition of that information was missed in the documentation, but ping @vieux @aluzzardi @aaronlehmann to be sure

**Comment by aaronlehmann** [comment]
We should fix the documentation to cover this field.

**Comment by thaJeztah** [comment]
@brb are you interested in contributing and opening a PR to add the missing field to the swagger file? https://github.com/docker/docker/blob/master/api/swagger.yaml. Instructions for previewing the documentation can be found in the readme; https://github.com/docker/docker/blob/master/api/README.md

**Comment by thaJeztah** [comment]
- fixed by https://github.com/moby/moby/commit/18b23067be82054a6384fc5934ecbb0276d1862b / https://github.com/moby/moby/pull/34485

https://docs.docker.com/reference/api/engine/version/v1.47/#tag/System/operation/SystemInfo

![Image](https://github.com/user-attachments/assets/ed412964-57bf-46b3-bb40-98b52716f17e)
