### ISSUE TITLE
Windows support for Swarm

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#31400]
Tracker issue for Swarm on Windows

- #31348: Multi-architecture support in Swarm mode /cc @nishanttotla 
- #29738: Secrets support /cc @johnstep

Please let me know if we're missing other pieces.

/cc @friism @mgoelzer @vsaraswat

**Comment by vsaraswat** [comment]
+ @dhiltgen

**Comment by caleblloyd** [comment]
Both of your issues that are being tracked here are closed.  Does this mean that Swarm on Windows will work in 17.06-ce?

**Comment by friism** [comment]
@caleblloyd yes, swarm-mode with Windows (and also mixed Linux/Windows swarms) have worked for a couple of months. Docker 17.06 will be the first stable release that fully supports this, but you can start experimenting with 17.03 or with the 17.06 release candidates already.

@aluzzardi @thaJeztah I think this issue can be closed.

**Comment by caleblloyd** [comment]
@friism thanks.  Will routing mesh work on Windows in 17.06-ce, or are we still waiting for a Windows update on that?

**Comment by friism** [comment]
@caleblloyd that'll require changes to Windows. Docker Inc. (and other vendors I'm sure) do provide ingress routing options that'll work across Linux and Windows swarms.

**Comment by thaJeztah** [comment]
Okay, let me close this one 👍
