### ISSUE TITLE
add-apt-repository fails on Raspbian (Jessie)

### ISSUE THREAD

**Issue by adriel** [moby/moby#31405]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Following the install steps at the [docker install instructions page](https://docs.docker.com/engine/installation/linux/debian/) fails at step 3.
However, Docker installs fine when using `curl -sSL get.docker.com | sh`

**Steps to reproduce the issue:**
1. Clean install of Raspbian Jessie lite 2017-02-16 from the [official source](https://www.raspberrypi.org/downloads/raspbian/).
2. Follow the [install steps for Debian Stretch (Raspbian)](https://docs.docker.com/engine/installation/linux/debian/)
3. At step 3, try running the Rasbian specific code: (`lsb_release -cs` returns "jessie")

```
sudo add-apt-repository \
  "deb https://apt.dockerproject.org/repo/ \
  raspbian-$(lsb_release -cs) \
  main"
```

4. You get error.

**Describe the results you received:**
```
pi@pi:~ $ sudo add-apt-repository \
>   "deb https://apt.dockerproject.org/repo/ \
>   raspbian-$(lsb_release -cs) \
>   main"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
pi@pi:~ $ lsb_release -cs
jessie
```

**Describe the results you expected:**
For the `add-apt-repository` command to succeed, and finish installing Docker.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on a brand new Raspberry Pi 3 Model B
I also had this same issue come up on one of my other Raspberry Pi's, can't remember if it was the first gen or another 3rd gen I have, but didn't have time to debug then.

**Edit:** Typo fix

**Comment by chepurko** [comment]
I can confirm the same exact issue.

**Comment by thaJeztah** [comment]
Looks like you're using the `debian` not `raspbian` instructions;

```
sudo add-apt-repository \
>        "deb https://apt.dockerproject.org/repo/ \
>        debian-$(lsb_release -cs) \
>        main"
Traceback (most

**Comment by chepurko** [comment]
I think that bit was a typo. Here's the output for the Raspbian instructions:
```
sudo add-apt-repository \
>        "deb https://apt.dockerproject.org/repo/ \
>        raspbian-$(lsb_release -cs) \
>        main"
[sudo] password for chep: 
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

**Comment by adriel** [comment]
Yeah sorry, @chepurko is right, somehow I managed to paste in the wrong code, I've corrected my original post. (which is the same as what @chepurko is getting).

**Comment by chepurko** [comment]
Are these on East coast AWS servers by chance? https://status.aws.amazon.com/?tag=b0c55-20

**Comment by chepurko** [comment]
I've managed to work around this by directly adding `/etc/apt/sources.list.d/docker.list` with `deb https://apt.dockerproject.org/repo/ debian-jessie main` in it. Don't know whether the error with `add-apt-repository` command is a bug with `software-properties-common` or repo issue or what...

**Comment by alexellis** [comment]
I wonder if this is due to the S3 outage? I installed Docker on the brand new PiZeroW yesterday with no issues.. then today I'm also getting failures, 503 etc from the Docker/Raspbian mirrors.

**Comment by chepurko** [comment]
@alexellis That's what I thought but the repo link itself works and I was able to install the repo and `docker-engine` by adding the `.list` file manually with the `raspbian-jessie` repo.

There was a type btw in my last post. It's actually `...raspbian-jessie main`

**Comment by DieterReuter** [comment]
I just tried to use the mentioned install steps above and I can clearly reproduce this issues on the latest Raspbian Jessie LITE version.
```
sudo add-apt-repository \
>        "deb https://apt.dockerproject.org/repo/ \
>        raspbian-$(lsb_release -cs) \
>        main"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

So, there seems to be some wrong or missing instructions in the docu section.

**Comment by DieterReuter** [comment]
Normally I'm installing Docker with the following command on Raspbian Jessie (and LITE), which is therefore my recommended way:
```
curl -sSL https://get.docker.com | sh
```

This works w/o any issues!

**Comment by chepurko** [comment]
@DieterReuter that works. So not sure what the point is of leaving up broken instructions.

**Comment by alexellis** [comment]
> So not sure what the point is of leaving up broken instructions.

I don't believe that these instructions are meant to be used with a Raspberry Pi.

@chepurko has got Docker installed now. @thaJeztah what's the next step? Document this is not for a Raspberry Pi/fix (maybe pinging Tianon?) or close issue?

**Comment by chepurko** [comment]
Yeah I have it installed now by manually adding the repo.

**Comment by troyfontaine** [comment]
@alexellis I believe that it is better for the community if the correct documentation is provided for those running Raspbian-the documentation alludes to it being provided on this [page](https://docs.docker.com/engine/installation/linux/debian/) but then never mentions it again.  It also specifically provides only one example for amd64.  A better solution would be to either a) provide a warning that the instructions after removing previous versions of docker are only for AMD64 and then provide a section for Raspbian or b) remove mentions of Raspbian from the page and call it out at the beginning and link to a page specifically for Raspbian that mentions using the get.docker.com script as it is the only functioning method of adding the repositories using the old apt.docker.com url as they don't appear to have been added to download.docker.com.

**Comment by jastev** [comment]
Also, https://docs.docker.com/engine/installation/linux/raspbian redirects to https://docs.docker.com/engine/installation/linux/debian, so it would appear that the debian page is intended to provide instructions for raspberry pi.

**Comment by thaJeztah** [comment]
ping @andrewhsu @mstanleyjones could you have a look? IIRC, armhf packages are now published for `docker-ce`, but only for `debian`, `ubuntu`. Raspbian packages (for `docker-engine`) are only in the https://apt.dockerproject.org repo?

**Comment by DavidAntliff** [comment]
Now that `curl -sSL https://get.docker.com | sh` is deprecated on Raspbian, what's the alternative? The documentation still mentions this method. I haven't been able to find any official announcement or roadmap for this deprecation either.

**Comment by alexellis** [comment]
See my issues which are tracking this - https://github.com/alexellis/docker-arm/issues

Docker CE is on hold until at least 17.08 - so you must use 17.05 if you want a fully-working installation. The binaries will go into Jessie or Stretch. If you really want latest it means rebuilding from scratch and adding in the Moby PR mentioned in the repo above.

**Comment by bernietai** [comment]
On RPI3 with Raspbian Stretch, I had to manually add to "/etc/apt/sources.list": 

`deb https://apt.dockerproject.org/repo/ debian-stretch main`
then running
`curl -sSL https://get.docker.com | sh`
worked for me

**Comment by thaJeztah** [comment]
The `apt.dockerproject.org` repository should no longer be used; the last version of docker published there was Docker 17.05, which reached EOL, and has known vulnerabilities (http://apt.dockerproject.org/repo/pool/main/d/docker-engine/)

Raspbian Jessie is no longer a supported distro; the last release of Docker for raspbian Jessie is 18.06.1 (and can be found in the download.docker.com repository; https://download.docker.com/linux/raspbian/dists/jessie/pool/stable/)

**Comment by dmp42** [comment]
Bump.
Same problem with stretch on download.docker.com
cc @seemethere

**Comment by thaJeztah** [comment]
@dmp42 raspbian or debian? https://download.docker.com/linux/debian/dists/stretch/pool/stable/arm64/

**Comment by dmp42** [comment]
@thaJeztah raspbian

**Comment by thaJeztah** [comment]
I think raspbian needs to use the debian repo (no packages in the raspbian channel https://download.docker.com/linux/raspbian/dists/stretch/pool/stable/arm64/)

The docs mention using the install script instead (which I think sets up using that repo); can you try if that works?

    curl -sSL https://get.docker.com | sh

**Comment by dmp42** [comment]
There are valid armhf packages, and manually adding this:

```deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable```

to sources.list will work as expected.

(which is also what get.docker.com is doing).

The issue here really is with `add-apt-repository`.

As for the docs, they mention both add-apt and get.docker.com in the debian section as supported for raspbian.

https://docs.docker.com/install/linux/docker-ce/debian/

Either way, it's not like a huge deal if you know your way around.

It's just weird / inconvenient that add-apt would not work for raspbian/armhf.

**Comment by thaJeztah** [comment]
Ah, you're right, was looking at arm64; armhf is present https://download.docker.com/linux/raspbian/dists/stretch/pool/stable/armhf/

I don't have an arm device, so had to go by the docs mentioning the convenience script

![D0807FB9-3628-4407-8124-659E08C1079F](https://user-images.githubusercontent.com/1804568/59393990-4389a280-8d7e-11e9-8b8f-50a016ce3828.jpeg)

**Comment by dmp42** [comment]
Yep, you are right (as always!), I missed that part in the docs.

**Comment by seemethere** [comment]
This can probably be closed now? @thaJeztah
