### ISSUE TITLE
OCI Runtime Error when 'userns-remap' enabled

### ISSUE THREAD

**Issue by justyns** [moby/moby#31432]
This is a clone of https://github.com/docker/docker/issues/31037 since I do not have permissions to re-open that issue.  Feel free to re-open it and close this one.

I'm running into the same issue as well.  Docker 1.13.1 on CentOS 7.2.1511.   I only get the error message whenever I set `userns-remap` to `default` in `/etc/docker/daemon.json`.  Without that option, containers run fine.

I also don't see any memory/allocation errors in dmesg.  The error looks the same otherwise though:

```
Feb 21 11:44:40 docker-1c360884 dockerd[3143]: time="2017-02-21T11:44:40.982416811-06:00" level=error msg="Handler for POST /v1.26/containers/6f716a8bcdb8a8098c1b04f82f4a7c7127f21bf667fdb457f04ac0a394f6a904/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:245: running exec setns process for init caused \\\"exit status 29\\\"\"\n"
```

Any other ideas? Rebooting does not solve the issue so far.

**Comment by thaJeztah** [comment]
ping @estesp

**Comment by liyaka** [comment]
I have the same issue on RedHat 7.3 with 1.13.1, build 092cba3 when setting `userns-remap` in docker daemon command.
Without it works fine.

**Comment by estesp** [comment]
Are you sure you have user namespaces enabled on CentOS/RHEL? See [this guide](https://github.com/procszoo/procszoo/wiki/How-to-enable-%22user%22-namespace-in-RHEL7-and-CentOS7%3F) for an easy way to enable it if you haven't already.

**Comment by liyaka** [comment]
I did:
`sudo grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"`
and then reboot
But still get the same error trying to run a container

**Comment by estesp** [comment]
Hmm, so I don't have a CentOS or RHEL system at the moment, so maybe you can try and do an `strace` to get the next level of detail on this error.  From `/usr/include/asm-generic/errno-base.h` error 29 is an illegal seek, but not sure what that would be in reference to without more detail.  Can you also provide the output of `docker info` so we can see which storage driver is in use and any other pertinent information?

You might have luck getting an strace on `runc` with my script here: https://github.com/estesp/utils/tree/master/strace-runc

If that isn't possible for you, then I'll need to find a CentOS or RHEL system to see if I can reproduce.

**Comment by justyns** [comment]
@estesp I'll try and get this to you today or tomorrow, thanks!

**Comment by liyaka** [comment]
`docker info`
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: thetaray-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.586 GB
 Data Space Total: 214.7 GB
 Data Space Available: 213.2 GB
 Metadata Space Used: 827.4 kB
 Metadata Space Total: 3.221 GB
 Metadata Space Available: 3.22 GB
 Thin Pool Minimum Free Space: 21.47 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.5 GiB
Name:xxx
ID: ZDWR:J5C2:PZSZ:T2DF:26ZS:Z3IK:E6XB:VZ6C:6H3F:DETA:RK5V:45CQ
Docker Root Dir: /var/lib/docker/1000.1000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 xxx:5000
 127.0.0.0/8
Live Restore Enabled: false

**Comment by liyaka** [comment]
@estesp Any more info that can help you to investigate this one? It's quite a blocker for me at the moment...

**Comment by estesp** [comment]
@liyaka I have updated my CentOS test VM to 7.3, and my kernel and devicemapper library versions match exactly to your `docker info`. I notice the original reporter also was using overlay, so tried overlay as well. I cannot get an error with user namespaces enabled with either backend driver. :(

Unless I can find a reproduction scenario, I will need either you or the original reporter to try and capture an strace of the failing scenario so I can see what is generating the error that comes back through the OCI runtime. We could also try mocking up a `runc` configuration that would match what Docker is generating + a simple root filesystem and see if we can recreate directly with `runc` to make the strace capture easier.

**Comment by liyaka** [comment]
OK, found the problem - 
`sudo grubby --args="user_namespace.enable=1" --update-kernel=**"$(grubby --default-kernel)"**` didn't work, but running:
`sudo grubby --args="user_namespace.enable=1" --update-kernel=**$(grubby --default-kernel)**` 
worker fine (+ reboot of cause)
Thank you for your support!

**Comment by estesp** [comment]
@justyns: given @liyaka corrected her issue with getting userns enabled properly, and I can't reproduce on a CentOS image with userns enabled in the kernel boot, can you verify if you have user namespaces enabled and re-check?

One easy validation is to `cat /proc/cmdline` and check that `user_namespace.enable=1` is in the booted kernel's command line parameters.

**Comment by wesleyclawson** [comment]
I have this error as well on a Ubuntu 16.04 after enabling the default userns-remap.

`docker@Docker:~$ docker run hello-world
container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/231072.231072/aufs/mnt/56376da46c66a786ffef98b588ce03dd5890b63d9e8ce94186a7293cb5bbd2e2\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/lxcfs/controllers/memory/docker/40bddcfab152fb05cbc477be580d62147b0f677f3f17d3213273c6cfcb8a3a3e: permission denied\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/231072.231072/aufs/mnt/56376da46c66a786ffef98b588ce03dd5890b63d9e8ce94186a7293cb5bbd2e2\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/lxcfs/controllers/memory/docker/40bddcfab152fb05cbc477be580d62147b0f677f3f17d3213273c6cfcb8a3a3e: permission denied\\\"\"".
ERRO[0000] error waiting for container: context canceled
`

Any more information on this bug?

**Comment by estesp** [comment]
@wesleyclawson this issue is related to a RH-enablement of user namespaces issue. It looks like you are hitting the issue discussed in #24834. Is your 16.04 installation fully up to date? The latest lxcfs package corrects this problem. You can also look at the gist of mine referenced in the other issue for more detail.

**Comment by wesleyclawson** [comment]
@estesp I'll read over that issue and try some things out. I thought everything was up to date - but tomorrow I'll apt update and upgrade just to double check. 

Will report back with results tomorrow AM.

**Comment by thaJeztah** [comment]
let me close this issue, as the original issue seems to be resolved, and went stale. Feel free to open a new issue with details if you still suspect there's a bug @wesleyclawson
