### ISSUE TITLE
response from daemon: re-exec error: exit status 1: output: archive/tar: invalid tar header, when try to create Image after restore database

### ISSUE THREAD

**Issue by MarcelJoedicke** [moby/moby#31444]
Windows Server Container, regular Docker version (when Install Docker), and newest docker Version

**Description**

 Created a SQL Server 2012 Image, Create a Container from it, restore a database and can't Create a new Image from that, because I get the error response from daemon: re-exec error: exit status 1: output: archive/tar: invalid tar header

**Steps to reproduce the issue:**
1. Create an MS SQL Server Image
2. Create Container from it
3. Restore database
4. Try to create a new Image from it

**Describe the results you received:**
Error - response from daemon: re-exec error: exit status 1: output: archive/tar: invalid tar header

**Describe the results you expected:**
It creates an Images with the restored DB

**Additional information you deem important (e.g. issue happens only occasionally):**
Did work for one DB, did not work for another

**Output of `docker version`:**
atm 17.03.0-ce-rc1
tried 1.12... before (std version)
```
(paste your output here)
```

**Output of `docker info`:**
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 87
Server Version: 17.03.0-ce-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.96 GiB
Name: win2016
ID: YBUD:H2PC:GX5P:IFNI:LNVN:LOCE:UIJR:NERA:WDUC:CVHR:PKIH:643M
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare-Metal

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL

**Comment by johnstep** [comment]
@MarcelJoedicke How are you creating the initial SQL Server image? Do you have a sample, failing database you can share? Thanks!

**Comment by MarcelJoedicke** [comment]
Hello Johnstep,

The inital SQL Server is created by first install dotnet3.5 (as described in the MS Dockerfile), and then using this parameters to install the SQL Server: 
<PathToSQLInstaller>\setup.exe /Q /IACCEPTSQLSERVERLICENSETERMS=True /ACTION=Install /FEATURES=SQLEngine,Replication,FullText,IS,DREPLAY_CTLR,DREPLAY_CLT /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /AGTSVCACCOUNT="NT AUTHORITY\System" /SQLSVCACCOUNT="NT AUTHORITY\System" /ISSVCACCOUNT="NT Service\MsDtsServer110" /AGTSVCSTARTUPTYPE="Automatic" /SQLSVCSTARTUPTYPE="Automatic" /ISSVCStartupType="Automatic" /CLTSTARTUPTYPE="Automatic" /CTLRSTARTUPTYPE="Automatic" /SECURITYMODE=SQL /SAPWD="CantProvideThePassword" /TCPENABLED=1 /NPENABLED=1.

Also tried it with the "official" dotnet-framework:3.5 Image.
Unfortunately, I can't provide the DB Backup to you, sorry. But I can provide that we have 2 DB Backups which are quite similar, one with 4GB, and one with 14,6GB. Creating the Image when restoring the 4GB Backup works without any issues. Creating the Image restoring the 14,6GB Backup throws the error. We also have a completely different DB Backup with 335MB which works without any issues. Might it be possible, that it has something to do with the size of the Backup? Because the smaller Backups work and the 14,6GB backup don't? They are restored exactly the same way.

However, we also created an Image from a folder with 40GB on data without any issues. So size also can't be the problem. If you have more questions or need something, please feel free to ask. I provide (what I'm allowed to.) :-).

Greetings,
Marcel

**Comment by thaJeztah** [comment]
ping @johnstep ^^

**Comment by jhowardmsft** [comment]
Can you send me a link to the database you can share which fails and exact instructions on how to repro? My email is on my GH page.

**Comment by MarcelJoedicke** [comment]
Ok, I get one step closer. The issue has nothing to do with the database itself.
The issue occur, because the mdf file of the database is >10GB. When you create a single Achieve with 10 GB (Example split a bigger file), you will get the same issue, when you try to create an Image from that. Is there any ways to support single files that are bigger to create the Containe Image?

**Comment by thaJeztah** [comment]
Not a solution, but are you adding the data to the image itself? Generally, it's recommended to keep stateful data out of the container's filesystem (and image), and use a _volume_ to store the data. I'm not sure how much overhead the `windowsfilter` graph driver has, but for some Linux graph drivers, the CoW / Layered filesystem used for the container can have a big impact on performance of the database.

**Comment by MarcelJoedicke** [comment]
Hi thaJeztah,
Thanks, yes, but it in this case I need the data inside the Container. We do some tests, so we have to be able to roll the whole system back if something goes wrong. When it would be outside, we would have to copy the files all the time, if something goes wrong to roll back.

Greetings Marcel

**Comment by viniciusxyz** [comment]
Any updates to the problem? I'm having the same error, it follows docker info:

Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 1
Server Version: 17.06.2-ee-15
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2248.amd64fre.rs1_release.180427-1804)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.89GiB
Name: AUTKSVRH10
ID: QJEV: UXTP: RJVJ: 4MS2: M777: BSNM: CILP: Z62Y: 5UQJ: UMSY: C5CP: BLK7
Docker Root Dir: C: \ ProgramData \ docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 140.1.254.10:5000
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MaxDobbelstein** [comment]
same here. docker info output: 

Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 18.09.0
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.345)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.9GiB
Name: PC-Dobbelstein
ID: ATFO:EZMW:VFBT:XLJE:MGYB:J737:A4BU:AWRQ:HBBZ:NFZI:5K7L:SMPD
Docker Root Dir: D:\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 52
 System Time: 2018-11-22T18:11:00.5566803+01:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 192.168.0.124:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
