### ISSUE TITLE
stopping docker.service takes 1min 30sec if containers are still running

### ISSUE THREAD

**Issue by runcom** [moby/moby#31459]
In order to explain and understand what happens when systemd stops the docker service
- either during shutdown or when a system administrator uses 'systemctl' - let's take
a look at the following example from a test system.
```
  # pwd
  /sys/fs/cgroup/systemd/system.slice/docker.service

  # ps --forest -opid,ppid,command `cat cgroup.procs` | cut -b-72
    PID  PPID COMMAND
   1150     1 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libe
   1477  1150  \_ /usr/bin/docker-containerd-current -l unix:///var/run/do
.->3594  1477      \_ /usr/bin/docker-containerd-shim-current af4852e4705e
|  3675  1477      \_ /usr/bin/docker-containerd-shim-current f2f4b8f221bf
|  3744  1477      \_ /usr/bin/docker-containerd-shim-current 4d00159d2ab4
|  3821  1477      \_ /usr/bin/docker-containerd-shim-current 4975e00f9815
|  3901  1477      \_ /usr/bin/docker-containerd-shim-current 01259fd89d50
|  3971  1477      \_ /usr/bin/docker-containerd-shim-current b26cfc6eacfc
|  4164  1477      \_ /usr/bin/docker-containerd-shim-current 699557f35b13
|  4245  1477      \_ /usr/bin/docker-containerd-shim-current efc870e68dbd
|  4335  1477      \_ /usr/bin/docker-containerd-shim-current fb20b2b72940
|  4435  1477      \_ /usr/bin/docker-containerd-shim-current 1a1939e09407
|
| # docker inspect --format='{{.State.Pid}}' `docker ps -q` | \
| > while read pid
| > do
| >       ps --no-headers -oppid,pid,comm $pid
| > done | sort -nk1
'--3594  3619 pod
   3675  3691 pod
   3744  3761 pod
   3821  3838 kube-apiserver
   3901  3930 kube-controller
   3971  3988 kube-scheduler
   4164  4184 pod
   4245  4263 pod
   4335  4352 sh
   4435  4452 sh
```
Ten containers are running on this system. For each of these containers, there is
a 'shim' process that sits between containerd and the container's primary process,
for example: containerd (PID 1477) - shim (PID 3594) - pod (PID 3619)

dockerd, containerd and all shim processes are in the same systemd control group.
The following parameters define the behavior of systemd when it stops the service.
```
  # systemctl show docker.service | grep -e Kill -e TimeoutStopUSec
  TimeoutStopUSec=1min 30s
  KillMode=control-group
  KillSignal=15
```
First, systemd sends SIGTERM (signal 15) to each process in the 'docker.service'
control group. Note that this only effects dockerd, containerd and shim processes
(the primary processes of the containers do not receive this signal from systemd).
Next, systemd waits for one minute and 30 seconds until it finally sends SIGKILL
to each of the remaining processes in the control group.

- dockerd and containerd contain code to handle SIGTERM
- the shim code does not handle SIGTERM (the signal is being ignored)

[Side note: From the perspective of the Linux kernel, all of these processes have
a handler for SIGTERM. However, this is a generic handler in Go language runtime.
'application code' such as dockerd or containerd or shim can establish a 'channel'
through which it can receive notifications about signals that have been delivered
to the process and can take appropriate action at the 'application level'.]

The problem is that dockerd and containerd do not clean up the shim processes and
the shim processes are ignoring SIGTERM, so systemd waits until the timeout period
(1 minute and 30 seconds) has expired until it finally kills the shim processes.
This delay occurs during each shutdown of the test system.
```
  [  *** ] A stop job is running for Docker Ap...ner Engine (1min 25s / 1min 30s)
```
So the question is:

  Why are dockerd and containerd unable to clean up the shim processes ?

The Shutdown() function in daemon/daemon.go gets invoked after dockerd receives
a SIGTERM signal. dockerd is started with the -D option to enable debug logging
at lines 672, 677, 679 and 685.
```
  657 func (daemon *Daemon) Shutdown() error {
   :
  664         if daemon.configStore.LiveRestore && daemon.containers != nil {
  665                 // check if there are any running containers, if none we should do some cleanup
  666                 if ls, err := daemon.Containers(&types.ContainerListOptions{}); len(ls) != 0 || err != nil {
  667                         return nil
  668                 }
  669         }
  670 
  671         if daemon.containers != nil {
  672                 logrus.Debug("starting clean shutdown of all containers...")
  673                 daemon.containers.ApplyAll(func(c *container.Container) {
   :
  677                         logrus.Debugf("stopping %s", c.ID)
  678                         if err := daemon.shutdownContainer(c); err != nil {
  679                                 logrus.Errorf("Stop container error: %v", err)
  680                                 return
  681                         }
   :
  685                         logrus.Debugf("container stopped %s", c.ID)
  686                 })
  687         }
   :
  705 }
```
However, there are no debug logs from this function in /var/log/messages for example,
after 'systemctl restart docker.service'. This means that the code at lines 672 - 686
is not being executed. The reason for this is:

- there are running containers

- 'daemon.configStore.LiveRestore' is true (enabled via config file)
```
  # cat /etc/docker/daemon.json
  {
      "live-restore": true
  }
```
Thus the function returns at line 667 without stopping any containers. Note that
dockerd would stop a container by sending a request to containerd, so in order to
stop all containers it is necessary that both processes (dockerd and containerd)
are running. However, due to 'KillMode=control-group' both processes receive the
SIGTERM signal from systemd roughly at the same time, so containerd may terminate
before or while dockerd is sending the requests to stop the containers. In other
words, even if 'live-restore' would be set to false it is still very likely that
dockerd would fail to stop the containers. Setting 'KillMode=mixed' mitigates the
problem because with this mode systemd sends SIGTERM only to the first process in
the group - i.e. to dockerd (note that dockerd is the parent of containerd).

The problem does not occur with the following changes applied to the config files:
```
  # gendiff /etc/docker .orig
  diff -up /etc/docker/daemon.json.orig /etc/docker/daemon.json
  --- /etc/docker/daemon.json.orig	2017-01-11 23:49:24.000000000 +0100
  +++ /etc/docker/daemon.json	2017-02-16 23:16:46.739000000 +0100
  @@ -1,3 +1,3 @@
   {
  -    "live-restore": true
  +    "live-restore": false
   }

  # gendiff /usr/lib/systemd/system .orig
  diff -up /usr/lib/systemd/system/docker.service.orig /usr/lib/systemd/system/docker.service
  --- /usr/lib/systemd/system/docker.service.orig	2017-01-11 23:49:24.000000000 +0100
  +++ /usr/lib/systemd/system/docker.service	2017-02-17 11:41:22.192000000 +0100
  @@ -33,6 +33,7 @@ LimitCORE=infinity
   TimeoutStartSec=0
   Restart=on-abnormal
   MountFlags=slave
  +KillMode=mixed
 
   [Install]
   WantedBy=multi-user.target
```
Note that the above changes are not meant to be a proposal for a solution. They are
merely for verification of the preceding analysis. Here's an example of log entries
during 'systemctl restart docker.service' if those changes are applied:
```
# grep \
> -e "starting clean shutdown of all containers..." \
> -e "stopping " \
> -e "container stopped" \
> /var/log/messages
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140374885+01:00" level=debug msg="starting clean shutdown of all containers..."
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140461027+01:00" level=debug msg="stopping ce7b703e9abcf93d76bcc072c289550d309550d8d99ba706c2dc77fd4d6a9633"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140663241+01:00" level=debug msg="stopping 0e3f0382c0aefa7f2ace18cf3d4b355087a3580750110638f1d1759d0dab5f0e"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140694808+01:00" level=debug msg="stopping 8a72e253da337920ecd8ea36a0b7ba4863a4e8bd3a1a5943d32f219bfa73db76"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140766128+01:00" level=debug msg="stopping 48d117dc7a25294518c2e0902e5342727b68779c7029283a62c9e3e3f6344062"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140803194+01:00" level=debug msg="stopping 9402399fef49c04deda3c94544805e0d7692d423435823101b56cb97e990c240"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140837343+01:00" level=debug msg="stopping 6e89346e74b2543d7b6d2744021e246a16e9bb4d2bd53a7ec527329ec286f32e"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140867505+01:00" level=debug msg="stopping 0d70b301c1dc2a52b42bc84d709ad70c50237a0f2cdade4b555af0baf08c865e"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140915884+01:00" level=debug msg="stopping 2ce9093374cfda675db5390cfdfb951089f28ccafeb0ab27cd6b0c107f36c95d"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.140960970+01:00" level=debug msg="stopping 258a6409fc226f78e776196d4ddd0114ed2437603286a12f01975732cae81905"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.141001491+01:00" level=debug msg="stopping 1643c721c0fc0b365ddb075faf3df55b0657cb9d0c5a3957f9a7212212e6c057"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.554516805+01:00" level=debug msg="container stopped 0d70b301c1dc2a52b42bc84d709ad70c50237a0f2cdade4b555af0baf08c865e"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.620723972+01:00" level=debug msg="container stopped 9402399fef49c04deda3c94544805e0d7692d423435823101b56cb97e990c240"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.709296031+01:00" level=debug msg="container stopped 258a6409fc226f78e776196d4ddd0114ed2437603286a12f01975732cae81905"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.777448306+01:00" level=debug msg="container stopped 6e89346e74b2543d7b6d2744021e246a16e9bb4d2bd53a7ec527329ec286f32e"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.844419649+01:00" level=debug msg="container stopped 2ce9093374cfda675db5390cfdfb951089f28ccafeb0ab27cd6b0c107f36c95d"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.889016813+01:00" level=debug msg="container stopped 48d117dc7a25294518c2e0902e5342727b68779c7029283a62c9e3e3f6344062"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.941090772+01:00" level=debug msg="container stopped 8a72e253da337920ecd8ea36a0b7ba4863a4e8bd3a1a5943d32f219bfa73db76"
Feb 17 19:48:48 rhel7vm dockerd-current: time="2017-02-17T19:48:48.995922951+01:00" level=debug msg="container stopped ce7b703e9abcf93d76bcc072c289550d309550d8d99ba706c2dc77fd4d6a9633"
Feb 17 19:48:58 rhel7vm dockerd-current: time="2017-02-17T19:48:58.264466240+01:00" level=debug msg="container stopped 0e3f0382c0aefa7f2ace18cf3d4b355087a3580750110638f1d1759d0dab5f0e"
Feb 17 19:48:58 rhel7vm dockerd-current: time="2017-02-17T19:48:58.411899759+01:00" level=debug msg="container stopped 1643c721c0fc0b365ddb075faf3df55b0657cb9d0c5a3957f9a7212212e6c057"
```

**Comment by runcom** [comment]
@crosbymichael @mrunalp @mlaventure @cpuguy83 @tonistiigi PTAL

**Comment by tonistiigi** [comment]
@runcom What is setting the `KillMode=control-group`? The default value should be `process`. https://github.com/docker/docker/blob/v1.13.1/contrib/init/systemd/docker.service#L25-L26

**Comment by runcom** [comment]
@tonistiigi I believe systemd, using that as a default (?)

**Comment by crosbymichael** [comment]
It should be killmode process, don't use the default.  Our service file accounts for this and is correct

**Comment by runcom** [comment]
Right, that's one of the issue I guess. The other issue is around "Shutdown" and live restore enabled also

**Comment by crosbymichael** [comment]
Naw, that does not matter when you set the right killmode, docker handles the rest

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by jasonbrooks** [comment]
I tried adding `KillMode=process`, and while this makes docker quick to stop, the container's processes keep running -- this isn't intended, right? This is with 1.12.6 on centos atomic host.

**Comment by thaJeztah** [comment]
@runcom is this issue resolved with the correct configuration of the unit-file?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
