### ISSUE TITLE
don't make /var/lib/docker/devicemapper/* MS_PRIVATE

### ISSUE THREAD

**Issue by giuseppe** [moby/moby#31489]
I am unable to use the live-restore feature when I run the Docker daemon in its own mount namespace.

The reason is that `/var/lib/docker/devicemapper/*` is remounted as `MS_PRIVATE` as soon as the Docker daemon starts so anything mounted by the daemon under `/var/lib/docker/devicemapper/*` won't be propagated to the host.  When the Docker daemon restarts, obviously it is unable to find these mount points as it will be running in a different mount namespace.

Is there anything that can be done to not use `MS_PRIVATE` for `/var/lib/docker/devicemapper/*`?  What sort of issues are expected if we don't remount it to `MS_PRIVATE`?

**Comment by runcom** [comment]
I remember something about that being needed for bind mounts like /dev and such, @rhvgoyal could you take a look at this?

**Comment by thaJeztah** [comment]
related to https://github.com/docker/docker/pull/22806 ?

**Comment by rhvgoyal** [comment]
I think there might be some unpleasant surprises if you remove it.

One thing is that its a safety net that docker mounts are not propagating into other mount namespaces. Otherwise removal of containers or cleaning of mount points will become even harder.

In the past people had raised some performance concerns also due to various mount propagation overhead. I don't have details though.

It also provides saftey net that nothing propagates into /var/lib/docker/devmapper/. Otherwise with -shared volumes feature it should be possible to pass in a directory in /var/lib/docker/ as source and then further mounts from containers will show up there. In the past I think @cpuguy83 did not want that kind of thing to happen.

**Comment by giuseppe** [comment]
@thaJeztah yes exactly!  I would still like though to be able to use a different namespace.  The current behaviour is to limit Docker to run in the host mount namespace.

@rhvgoyal the last issue seems to be related to the way the new mount `/var/lib/docker/` is created?  If you don't want mount to get propagated there, it should not be set to `MS_SHARED`.

**Comment by rhvgoyal** [comment]
/var/lib/docker/ is not a mount point right? /var/lib/docker/devmapper/ is and its private by default to rule out the possibility of things propagating in or out by default.

If /var/lib/docker/devmapper is not a mount point, then default propagation properties will depend on properties of parent mount which will be system root (/). And in fedora and centos and other distributions it is shared by default.

**Comment by cpuguy83** [comment]
Generally its more about mounts propagating to other namespaces making it difficult to clean up on exit.
Newer kernels handle this much better (3.16+?, I can't remember the version), where at least in Docker's namespace we can do a lazy unmount and clean up naturally, where as in older kernels the lazy unmount will still return `EBUSY` if it's still mounted in another namespace.

**Comment by thaJeztah** [comment]
PR opened here; https://github.com/docker/docker/pull/31490

**Comment by giuseppe** [comment]
right, `/var/lib/docker/devicemapper/`is.  It is remounted to MS_PRIVATE in any case, even if it already existing, so there is no way to change this behaviour as it is now.

@cpuguy83 yes, that is fixed in linux 3.15+ which is quite old and it is probably going to be addressed in RHEL as well, so I bet the clean up on exit problem should not be a problem

**Comment by rhvgoyal** [comment]
lazy unmount does not fail if mount is busy in another namespace. But directory removal will fail if that directory is unmounted on in another mount namespace (with older kernels)

**Comment by giuseppe** [comment]
so beside not supporting old kernels (3.14 was released almost 3 years go) there should not be any blocker issue in dropping the MS_PRIVATE bits?  That looks like good news for running Docker in its own namespace and support live-restore.

**Comment by rhvgoyal** [comment]
I am not sure what problem you are trying to solve. So if problem is that you want to see mount points from previous run, you need to run docker daemon in host mount namespace. The very reason we try to run docker daemon in another namespace is that we dont want these mount points to become visible in other namespace.

**Comment by rhvgoyal** [comment]
BTW, why --live-restore needs to find old mount points. Why can't we save some metadata about the containers we leave running and try to find them upon reastart. If need be, create more mount points in your current mount namespace. That way we don't rely on finding mount points from previous run.

**Comment by giuseppe** [comment]
That is needed when you try to do "docker exec $CONTAINER ..." after you restart Docker.  Since the container was launched in the old mount namespace that is now not accessible, runc fails in this way:
```
[pid 17899] chdir("/run/docker/libcontainerd/23e8ed9bac60d52d9f5fecf694b15f3bbf6a0c84f18dc57bbc9005b61ba0914e") = 0
[pid 17904] chdir("/var/lib/docker/devicemapper/mnt/8e67a6553dbe35711a70d8d759f0a174445565b55b09d32eefc2ac8dc6c78019/rootfs") = -1 ENOENT (No such file or directory)
```

**Comment by giuseppe** [comment]
I can see that containerd:master is already managing exec directly from the shim process.  For `v0.2.x`, this quick hack patch fixes the issue for me.  Would something like this make sense?

```
diff --git a/runtime/container.go b/runtime/container.go
index 2e9e663..1c10f3b 100644
--- a/runtime/container.go
+++ b/runtime/container.go
@@ -445,10 +445,16 @@ func (c *container) Exec(ctx context.Context, pid string, pspec specs.ProcessSpe
                        c.RemoveProcess(pid)
                }
        }()
-       cmd := exec.Command(c.shim,
-               c.id, c.bundle, c.runtime,
+
+       ppid, err := readProcStatField(c.processes[InitProcessID].SystemPid(), 4)
+       if err != nil {
+               return nil, fmt.Errorf("could not check process ppid: %v", err)
+       }
+
+       cmd := exec.Command(
+               "nsenter", "-C", "-F", "-r/", fmt.Sprintf("--wd=%s", processRoot), "-m", "-u", "-i", "-n", "-p", "-t", ppid,
+               c.shim, c.id, c.bundle, c.runtime,
        )
-       cmd.Dir = processRoot
        cmd.SysProcAttr = &syscall.SysProcAttr{
                Setpgid: true,
        }
```

@crosbymichael
