### ISSUE TITLE
Error starting daemon: layer does not exist

### ISSUE THREAD

**Issue by yuexiao-wang** [moby/moby#31506]
**Description**
Docker daemon start failed after hard restart VM. The error from docker daemon happens as follows:

    An error occurred trying to connect: Get     http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer

It is same issue as #17846   
(docker is installed from package( .deb ), not upgrade)

**Steps to reproduce the issue:**
1.  Docker works fine
2.  Restart hard VMs as instances on Openstack
3.  Docker daemon starts failed and an error occurred trying to connect

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue happens many times.

**Output of `docker version`:**
The information from working fine VM:
# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**
The information from working fine VM:
# docker info
Containers: 99
 Running: 43
 Paused: 0
 Stopped: 56
Images: 31
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 506
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: b2c4izvupzfu4dyakk7qvsr18
 Is Manager: true
 ClusterID: 7lhyeqjembm6b1biqjechbdw8
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 222.0.0.31
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: paas-controller-2
ID: WIWO:PYNI:O2L7:UPA3:UIF5:5P5S:IALU:S5CI:R6XM:ZKDM:CYAE:B3P7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 111.0.0.44:6666
 10.67.18.252:33377
 127.0.0.0/8
```
(paste your output here)
```
/Error starting daemon
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
time="2017-03-02T16:58:18.388377654+08:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2017-03-02T16:58:18.395665894+08:00" level=info msg="libcontainerd: new containerd process, pid: 1618"
/var/run/docker.sock is up
time="2017-03-02T16:58:23.736035837+08:00" level=fatal msg="Error starting daemon: layer does not exist"
/var/run/docker.sock is up                                                          1,1           Top
time="2017-03-02T20:17:23.483789100+08:00" level=info msg="libcontainerd: new containerd process, pid: 29342"
time="2017-03-02T20:17:24.644047536+08:00" level=fatal msg="Error starting daemon: layer does not exist"
/var/run/docker.sock is up
time="2017-03-02T20:17:24.679384215+08:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2017-03-02T20:17:24.680197925+08:00" level=info msg="libcontainerd: new containerd process, pid: 29493"
time="2017-03-02T20:17:25.832031845+08:00" level=fatal msg="Error starting daemon: layer does not exist"
/var/run/docker.sock is up

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack

**Comment by yuexiao-wang** [comment]
@thaJeztah PTAL

**Comment by yuexiao-wang** [comment]
local-kv.zip cannot be attached as follows:

    We don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

If you need this file, may be I can send it to you by email.

**Comment by AkihiroSuda** [comment]
> time="2017-03-02T20:17:25.832031845+08:00" level=fatal msg="Error starting daemon: layer does not exist"

Seems fixed in 1.13
https://github.com/docker/docker/pull/25806

**Comment by yuexiao-wang** [comment]
OK, I will check it and thank you very much

**Comment by yuexiao-wang** [comment]
@AkihiroSuda  #25806 only use for Windows, but this error occurred on ubuntu 14.04.  VMs were restarted hard  as an instance on Openstack,. not reboot on VMs.

**Comment by AkihiroSuda** [comment]
oh, sorry

**Comment by AkihiroSuda** [comment]
I changed the title of this issue as above for ease of finding

**Comment by cyphar** [comment]
@yuexiao-wang Can you see if applying c37bd10f8cfc4cb6df5513881eed53e6c5f0be09 fixes it? Note that this won't fix the actual `/var/lib/docker` corruption but it should stop it from happening in the future. See #32170 for more info.

**Comment by tuwid** [comment]
same with centos 7.6

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
