### ISSUE TITLE
Docker for Windows 17.03.0-ce pull and login issue

### ISSUE THREAD

**Issue by Kemyke** [moby/moby#31519]
Description

Getting a time-out when running docker login to our private repository or even running docker run hello-world command.
Issue is happening on Windows 10 Version 1511 with the new docker 17.03.0-ce

Steps to reproduce the issue:

Run docker run hello-world

Describe the results you received:

` net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).docker.io/v2`

Describe the results you expected:

I expect to be able to login to our private repository or pull any public images.

Additional information you deem important (e.g. issue happens only occasionally):

This issue is only happening on the machines with the new docker version. Machines with version 1.13.1 can login to the private repo and can pull any images.

Output of docker version:

Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true

Output of docker info:

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.941 GiB
Name: moby
ID: NLOI:6EEV:FTFV:OQFY:KOLR:FUE3:YMDE:62IL:P5N7:6UOG:VVWQ:YNVK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 21
 System Time: 2017-03-03T14:32:43.9787914Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
ping @dave-tucker @rneugeba PTAL

**Comment by cpuguy83** [comment]
Can you upload a diagnostic report from the "Diagnose & Feedback" on the docker menu, then comment with the diagnostic ID here?

**Comment by Kemyke** [comment]
Done.
78B7D9C9-5E60-47ED-9EA8-D8BC9A59FBBD/2017-03-03_17-11-13

**Comment by djs55** [comment]
@Kemyke thanks very much for uploading the diagnostics.

Looking in the DNS logs I see you have 3 servers configured: 2 have addresses 128.*.*.* and 1 has address 10.0.0.13. The logs show responses from 128.*.*.* but none from 10.0.0.13. Unfortunately the default timeout is 5s which seems to be too long for the VM -- the logs show the VM gives up and tries again at the same time as the response is finally returned.

Do you know if the `10.0.0.13` DNS server should be reachable? Is it part of a VPN configuration? If so, does the DNS work if the VPN is brought up?

**Comment by Kemyke** [comment]
The 10.0.0.13 address is our Azure DNS which is connected to our network as a site to site VPN which is managed by our firewall. 
I am quite sure that we have no problems with our DNS servers because as soon as i downgrade to 1.13.1 everything works as expected.

**Comment by Kemyke** [comment]
The new 17.03.0-ce-win1 version also reproduce this issue.

**Comment by akashbeuria** [comment]
Can you please point out what might be the problem?

3F04D2D2-2819-4887-8018-9CA695E11D68/2017-03-07_20-33-24

**Comment by Kemyke** [comment]
Do you have any idea what is wrong with the DNS? If I use the 8.8.8.8, then I can download images. 
But in this case, the networking between containers produces some strange errors. The container with host network type tries to access some strange IP on the 53 port and fails to resolve 'localhost'.

**Comment by Kemyke** [comment]
Do you have any update on this. It is not even fixed in 17.03.1-ce-win5, so we are stucked with 1.13.1.

How can i help you to to trace down this bug?

**Comment by djs55** [comment]
@Kemyke Sorry for the delay. The latest version of the DNS forwarder should better cope when some upstream servers drop requests or are offline. Could you try the latest Docker for Windows CE edge ([Version 17.05.0-ce-win9 (11965)](https://download.docker.com/win/edge/11965/InstallDocker.msi)) and upload a fresh diagnostic if it fails?

**Comment by Kemyke** [comment]
I've just tried the latest stable (17.03.1-ce-win10) version and it also contains this bug.  
But the 17.05 is working fine for me, thanks Dave. When will be a stable version released from 17.05 @djs55, do you have any planned date?
Thanks!

**Comment by djs55** [comment]
@Kemyke thanks for the quick feedback! The next stable version should be `17.06` which should be released in June. I believe the first RC is due next week.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
