### ISSUE TITLE
volume name conflict when docker volume create with plugin driver in swarm

### ISSUE THREAD

**Issue by sitamet** [moby/moby#31526]
**Description**

`docker volume create` with plugin driver checks for name conflicts in the `volumestore` of its daemon.

When working with a volume plugin ready to work in a swarm cluster we should ask to the volume plugin api.

**Steps to reproduce the issue:**

System: swarm mode with 2 nodes
Story:
1. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`
2. `node1:~# docker run -it -v wp000test_db:/data --volume-driver=wetopi/rbd busybox ls /data`
3. `node2:~# docker volume  rm wp000test_db`
4. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`

**Describe the results you received:**
```
node1:~# ...
Error response from daemon: A volume named wp000test_db already exists. Choose a different volume name.
```

**Describe the results you expected:**
node1 should be able to create the volume.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@dk1w:~# docker info
Containers: 14
 Running: 10
 Paused: 0
 Stopped: 4
Images: 86
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 346
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local glusterfs
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 4krjjm1sqzo0oqinm1adyobj6
 Is Manager: false
 Node Address: 192.168.100.211
 Manager Addresses:
  192.168.100.201:2377
  192.168.100.202:2377
  192.168.100.203:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.823 GiB
Name: dk1w
ID: P47W:G5YP:VCE6:S2IB:JWXR:WBGV:ZMUN:4DG6:GB3K:VP4C:5QNB:MO7M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sitamet
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 registry.service.wetopi.priv
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional details:**

Where in the docker code this happens:

[https://github.com/docker/docker/blob/v17.03.0-ce/daemon/create.go#L232](https://github.com/docker/docker/blob/v17.03.0-ce/daemon/create.go#L232)

```go
// VolumeCreate creates a volume with the specified name, driver, and opts
// This is called directly from the Engine API
func (daemon *Daemon) VolumeCreate(name, driverName string, opts, labels map[string]string) (*types.Volume, error) {
	if name == "" {
		name = stringid.GenerateNonCryptoID()
	}

	v, err := daemon.volumes.Create(name, driverName, opts, labels)
	if err != nil {
		if volumestore.IsNameConflict(err) {
			return nil, fmt.Errorf("A volume named %s already exists. Choose a different volume name.", name)
		}
		return nil, err
	}
```

**Comment by cpuguy83** [comment]
step2 is not removing the container, as such the `docker volume rm` would be unsuccessful.

**Comment by cpuguy83** [comment]
Also can you please provide the full `docker info` output?

**Comment by cpuguy83** [comment]
Also can you send `SIGUSR1` to the effected daemon, then in the logs there will be a reference to a file for daemon data. Can you post that?

Note the data data dump will dump all the data in the daemon so if there are any unencrypted secrets stored you may want to filter out everything except for the data structure for the volume store.

**Comment by sitamet** [comment]
@cpuguy83 step2 does not remove the container, On purpose.
A plugin volume managing cluster-wide storage, in our case [Docker volume plugin for RBD](https://github.com/wetopi/docker-volume-rbd) ,
creation and destroy can occur on any node. It's common that docker service (swarm) starts containers in one node and on failure moves to another node without removing the failed containers

**Comment by cpuguy83** [comment]
@sitamet Any chance you could get that daemon data dump?

**Comment by sitamet** [comment]
`SIGUSR1`

daemon datastructure dump node1:
[node1_dk1m_daemon-data-2017-03-13T172057+0100.log.txt](https://github.com/docker/docker/files/838902/node1_dk1m_daemon-data-2017-03-13T172057.0100.log.txt)

daemon datastructure dump node2:
[node2_dk1w_daemon-data-2017-03-13T172110+0100.log.txt](https://github.com/docker/docker/files/838904/node2_dk1w_daemon-data-2017-03-13T172110.0100.log.txt)

**Comment by cpuguy83** [comment]
Sadly the daemon is not propagating errors from the volume store in this case...
See https://github.com/docker/docker/blob/master/volume/store/store.go#L331-L347
This is most likely where it's coming from.

Is this a v2 plugin?

**Comment by sitamet** [comment]
@cpuguy83  yes this is a v2 plugin

**Comment by sitamet** [comment]
The key is in step 3:

Failing Story path:
1. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`
2. `node1:~# docker run -it -v wp000test_db:/data --volume-driver=wetopi/rbd busybox ls /data`
3. `node2:~# docker volume  rm wp000test_db`
4. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`

Success Story path:
1. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`
2. `node1:~# docker run -it -v wp000test_db:/data --volume-driver=wetopi/rbd busybox ls /data`
3. `node1:~# docker volume  rm -f wp000test_db`
4. `node1:~# docker volume create -d wetopi/rbd -o pool=rbd -o size=1024 wp000test_db`

**Comment by cpuguy83** [comment]
I think I see the problem.
@sitamet Would you be able to test a patch?

**Comment by cpuguy83** [comment]
#32268 will give more details on the actual error that is happening. Right now the error is obfuscated.
If you can try that we may get better visibility into why this is failing.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
