### ISSUE TITLE
"Architecture" missing in image manifest in DfW

### ISSUE THREAD

**Issue by pdevine** [moby/moby#31528]
**Description**

`docker inspect` on a windows image isn't including the architecture.

<img width="896" alt="screen shot 2017-03-02 at 3 46 01 pm" src="https://cloud.githubusercontent.com/assets/75239/23563242/ae4eff2a-fffa-11e6-9b1e-08a7c76f5627.png">

This was seen with the `microsoft/windowsservercore` and `microsoft/nanoserver` images.

**Steps to reproduce the issue:**
1. Install DfW
2. Turn on Windows native containers 
3. docker pull microsoft/nanoserver
4. docker inspect microsoft/nanoserver

**Output of `docker version`:**
<img width="1031" alt="screen shot 2017-03-03 at 10 21 34 am" src="https://cloud.githubusercontent.com/assets/75239/23563376/513b022e-fffb-11e6-8c05-a4001a5756e8.png">

**Output of `docker info`:**
<img width="896" alt="screen shot 2017-03-03 at 10 23 00 am" src="https://cloud.githubusercontent.com/assets/75239/23563418/7564e2f0-fffb-11e6-9fb2-5da07f32c5df.png">

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running in a VMware Fusion 8.5 Virtual Machine w/ Windows 10.

**Comment by thaJeztah** [comment]
ping @johnstep PTAL if this is specific to those images or if the field is not set during build

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.

**Comment by pdevine** [comment]
I don't have a windows machine to even test this out anymore :-D
