### ISSUE TITLE
credsStore, D4M and sibling containers

### ISSUE THREAD

**Issue by taiidani** [moby/moby#31537]
In the most recent release of Docker for Mac (`17.03.0-ce-mac1`) the location where Docker ID credentials were stored changed from the `.docker/config.json` file to the OSX keychain by implementing  a `credsStore` option of `osxkeychain`.

This is great! But breaks scenarios where that file is being bind-mounted into a sibling container -- without the credentials the container cannot access the same private repositories as the host.

**Steps to reproduce the issue:**
1.
```
docker login
```
2.
```
docker run --rm \
    -v $HOME/.docker:/root/.docker \
     -v /var/run/docker.sock:/var/run/docker.sock \
    docker:17.03.0-ce docker pull private/repo:tag
```

**Describe the results you received:**

```
Error response from daemon: repository private/repo not found: does not exist or no pull access
```

**Describe the results you expected:**

```
tag: Pulling from private/repo
b3e1c725a85f: Already exists
4daad8bdde31: Already exists
63fe8c0068a8: Already exists
etc.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Currently the behavior can be hacked by logging in, then removing the `credsStore` line entirely and logging in a second time. If you logout though, or delete your `config.json` file, the macOS keychain is again used on subsequent logins.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by taiidani** [comment]
An option proposed in the Docker Slack #general channel was to have the `config.json` file able to be explicitly set to storing credentials again. Something like:
```
"credsStore": "file"
```

While this does not place the credentials in the more secure keychain, it does allow for sibling container scenarios to work again.

**Comment by jeanlaurent** [comment]
Thanks for your feedback @taiidani. We will provide some way of opting-out of secure credstore in an upcoming release of Docker for Mac.

**Comment by taiidani** [comment]
Given that the latest Edge release has the ability to opt-out of the keychain storage, I'd call this issue resolved. Thanks for the solve!
