### ISSUE TITLE
Overlay encryption - problem with a mix of internal hosts behind same firewall that need to communicate with external resources

### ISSUE THREAD

**Issue by ventz** [moby/moby#31583]
This is a follow up of: https://github.com/docker/docker/issues/30727 (see bottom 3-4 posts), but to an issue that has a slightly different angle and was discovered in 17.03.0-ce.

## Short Summary:
If you have 2+ hosts (let's call them A and B), specifically in the same datacenter, behind the same firewall, and they have to connect to a swarm host (C) outside of the datacenter (thus via PUBLIC IP, and thus hosts A and B need to use public IPs), the encrypted overlay does not work.

In this scenario, host A and host B can communicate with C, and host C can communicate with A and B. But host A cannot communicate with B, and B cannot communicate with A.

The main reason for this seems to be due to the hosts relying on the remote source packet for the ESP rather than the --advertise-addr. See @aboch for more information.

## Longer Summary and Details:
This means that if you have:
```
HOST A = 10.10.101.11 = 1.2.3.4 [same datacenter as B, behind same firewall]
HOST B = 10.10.102.11 = 5.6.7.8 [same datacenter as A, behind same firewall]
HOST C = 192.168.100.11 = 9.10.11.12 [different datacenter than A+B] 
```

If you try to swarm join A + B, you can use the 10.10.101 and 10.10.102 subnets:
```
# Swarm init on host A
docker swarm init --advertise-addr 10.10.11.101

and

# Swarm join on host B
docker swarm join --token $TOKEN  10.10.11.101:2377 --advertise-addr 10.10.12.11
```

Everything works as expected. Everything is within the datacenter (or VPC in aws) and there are no issues.

However, if you need to add C, you can't since you only used the private IPs.

So now, you can:

```
# Swarm init on host A
docker swarm init --advertise-addr 1.2.3.4 --listen-addr 10.10.101.11:2377

# Swarm join on host B
docker swarm join --token $token \
--advertise-addr 5.6.7.8 --listen-addr 10.10.102.11:2377 1.2.3.4:2377

# Swarm join on host C
# Not relevant to the issue
```

Now however the issue is that you are advertising public IPs 1.2.3.4 and 5.6.7.8, but since the hosts are behind the same firewall (one interface for public IPs + another interface for private IPs), even when A (10.10.101.11) wants to talk to B by specifying B's public IP (5.6.7.8), B sees the traffic coming from A's private IP (10.10.101.11).

This prevents a customer joining local resources with remote resources, where the local resources contain more than 1 system.

NOTE: If you test this in AWS, you will not see the issue because Amazon routes internal VPC IPs as external using pvlans between datacenters/pods, and even within a single VPC when using external IPs.

**Comment by thaJeztah** [comment]
ping @aboch

**Comment by aboch** [comment]
Yes, cross-datacenter overlay encryption works under assumption that when --advertise-address is set to the host public IP, all the nodes, even the ones in same DC, will communicate via the public IP, by means of the 1-to-1 NAT, like it happens in AWS.

```
     HOST 1                                                          HOST 2
PRI1-->PUB2  ==> (1-to-1 NAT) ==> PUB1-->PUB2 ==> (1-to-1 NAT)  ==> PUB1-->PRI2
PRI1<--PUB2 <==  (1-to-1 NAT) <== PUB1<--PUB2 <== (1-to-1 NAT)  <== PUB1<--PRI2
```

**Comment by aboch** [comment]
One way to get this working seamlessly, is to relax the incoming RX SA to only match on the dst IP (local private IP). But we need to evaluate the security implications of that.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
