### ISSUE TITLE
1.13.1: Memory Restrictions not works to Virtual Memory

### ISSUE THREAD

**Issue by westsouthnight** [moby/moby#31594]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

We currently have service which works on dotnetcore. In one component, which we use for http service works inside container for that service, possible have a memory leak (https://github.com/aspnet/KestrelHttpServer/issues/1266). We want to set restrictions to that docker container for prevent consume by container all available virtual memory. 

**Steps to reproduce the issue:**
1. Create dotnetcore app with KestrelHTTPservice core component
2. Run container with memory restrictions.
3. See to top/htop/free for get that result

![screen_shot_2017-03-06_at_18_08_22](https://cloud.githubusercontent.com/assets/17825649/23645570/e10510a0-031d-11e7-9b58-ba5bc2446910.png)

**Describe the results you received:**

Restrictions to container memory not works

**Describe the results you expected:**

Restrictions to container memory works

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 20
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 177
 Dirperm1 Supported: true
Logging Driver: fluentd
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.5 GiB
Name: stand-1-test-1.example.com
ID: 7YSW:IOVS:L5KT:2SO2:CD22:GXVL:GNXY:CBOR:LJPU:AYGI:W2IR:HHLU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: devevote
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tiborvass** [comment]
@westsouthnight can you please be more specific in the commands you used so we can try to reproduce the issue?

**Comment by westsouthnight** [comment]
@tiborvass what more information you need? I can provide all necessary information. As example, You can get any very high ram used application, and try to set memory limit. (Example we use ElasticSearch and our service on dotnetcore, and see same situation) If by default that service, want to get some VIRT memory - like 5-20 Gb, but you set restrictions, restrictions not works. 

We see that issue one week ago, when deploy to production service with ram leak. After we set restrictions and no see expected result. After that we create that issue. In investigation of problem, as example, we see our ElasticSearch in test environment have same situation - when we up container we set restrictions to 2 GB of the RAM, but currently service consumed more then 5.7 Gb of VIRT RAM.

You can see that on screens below.

![screen_shot_2017-03-09_at_15_28_10](https://cloud.githubusercontent.com/assets/17825649/23750566/9feb6d18-04de-11e7-81f7-95b0d76fb4ae.png)

![screen_shot_2017-03-09_at_15_31_03](https://cloud.githubusercontent.com/assets/17825649/23750571/a48537b4-04de-11e7-9727-8f0456bc9780.png)

**Comment by thaJeztah** [comment]
Did you only set `--memory` or also `--memory-swap`, from the [Limit a container's resources - memory](https://docs.docker.com/engine/admin/resource_constraints/) documentation;

> If (`--memory-swap` is) unset, and `--memory` is set, the container can use twice as much swap as the `--memory` setting, if the host container has swap memory configured. For instance, if `--memory="300m"` and `--memory-swap` is not set, the container can use 300m of memory and 600m of swap.

Combine that with ([taken from this site](http://mugurel.sumanariu.ro/linux/the-difference-among-virt-res-and-shr-in-top-output/));

> `VIRT` stands for the virtual size of a process, which is the sum of memory it is actually using, memory it has mapped into itself (for instance the video card’s RAM for the X server), files on disk that have been mapped into it (most notably shared libraries), and memory shared with other processes. `VIRT` represents how much memory the program is able to access at the present moment.


Setting a limit of `--memory=2G`, the total amount of memory would be 6G (2G memory + 4G swap), which would show under `VIRT`.

**Comment by westsouthnight** [comment]
@thaJeztah i'm try set 2G in all settings to run our service - its not works

**Comment by thaJeztah** [comment]
Just to be sure, can you run the `test-config.sh` script? https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by westsouthnight** [comment]
@thaJeztah 5 min...

**Comment by westsouthnight** [comment]
@thaJeztah http://pastebin.com/Sb8zYBzT

**Comment by thaJeztah** [comment]
Ok, so;

```
 (cgroup swap accounting is currently not enabled, you can enable it by setting boot option "swapaccount=1")
```

Which means that processes can use unlimited swap (which is part of `VIRT`, per my earlier comment)

**Comment by thaJeztah** [comment]
See this issue for some hints on enabling it https://github.com/docker/docker/issues/4250

**Comment by westsouthnight** [comment]
@thaJeztah thanks, don't know about this, we will be try!

**Comment by westsouthnight** [comment]
@thaJeztah i test this, but steel not works. service consume 20Gb...

**Comment by westsouthnight** [comment]
![screen_shot_2017-03-09_at_17_44_23](https://cloud.githubusercontent.com/assets/17825649/23755552/cf3da85c-04f1-11e7-9825-d2b96ecfb53b.png)
![screen_shot_2017-03-09_at_17_44_30](https://cloud.githubusercontent.com/assets/17825649/23755554/cf418d46-04f1-11e7-9357-4e39a0d574b0.png)
![screen_shot_2017-03-09_at_17_38_01](https://cloud.githubusercontent.com/assets/17825649/23755551/cf3d5780-04f1-11e7-9588-33e6fffd4e41.png)
![screen_shot_2017-03-09_at_17_37_51](https://cloud.githubusercontent.com/assets/17825649/23755550/cf3a6228-04f1-11e7-90a1-6bbff1bb0750.png)
![screen_shot_2017-03-09_at_17_37_51__2_](https://cloud.githubusercontent.com/assets/17825649/23755553/cf3e5e3c-04f1-11e7-9394-7ebd2ba4e9ba.png)

**Comment by westsouthnight** [comment]
Dear @thaJeztah & @tiborvass any ideas?

**Comment by thaJeztah** [comment]
It looks a bit like https://github.com/docker/docker/issues/15020, but it should be limited by the kernel if `--memory-swap` and `--memory` is set. What values did you use for those, and what does `docker inspect <container id> | grep Memory` show?

**Comment by westsouthnight** [comment]
@thaJeztah if i correct understand you, for work restrictions should be set to two options memory-swap & memory. I try to set only that values to 2Gb, and see in ``` docker inspect <container id> | grep Memory ``` 

https://cloud.githubusercontent.com/assets/17825649/23755550/cf3a6228-04f1-11e7-90a1-6bbff1bb0750.png

**Comment by westsouthnight** [comment]
@thaJeztah if need you can write to me in telegram, and i show via shard screen all available all what you want to see for proof.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
