### ISSUE TITLE
Dynamic AUTH in swarm mode

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#31601]
Currently, dockerd itself supports a "single" and "static" way to protect /run/docker.sock using a tlskey file. But it is not suitable for swarm.

Just like swarm token has its expired time, tlskey should also have, especially when the key has been exposed to public.

"single" means the key takes effect for only 1 node, thus, swarm cluster requires people to update key on each of active swarm nodes once the key is changed.

"static" indicates we have to restart all daemons once the key is changed to apply for changes.

Taking advantage of built-in etcd storage, Swarm node should record a key-value pair in it which enables a "non-single" way to solve the problem. For example, assume there are 5 swarm nodes, post a request to 1 node about to change the password, swarm stores the new password, and then all other swarm nodes will get the updated automatically. Besides, all swarm nodes needn't restart to apply for changes if we provide standard WWW-Auth like Basic-Auth.

**Comment by ghostplant** [comment]
The solution is simple, which is just to reserve a key/value item to store a salted password value. Every swarm node reads this distributed shared value and verifies requests.

**Comment by cpuguy83** [comment]
I'm  not sure I understand the request.

The docker http socket is protected either by fs permissions (unix socket), or TLS keys (TCP).

Swarm communications are all protected with mutual tls auth, each node has a cryptographic identity. TLS keys are rotated automatically on a configurable interval.

**Comment by ghostplant** [comment]
@cpuguy83 
I mean the authorization requirement of client posting a request to swarm via docker socket (either a network socket or a unix socket). If we want only authorized clients to communicate with docker daemon, he or she must own either a private keyfile or a password, once it requires to get updated, there should be a way to solve the problem above in cluster environment. For example, something like:

`root@machine-1# curl -u docker:hello1 --unix-socket /run/docker.sock -X POST -F 'user=docker' -F 'passwd=hello2' http:/swarm/authorization`
`(Updated)`

`root@machine-1# curl -u docker:hello1 --unix-socket /run/docker.sock http:/services`
`(AUTH Failed)`

`root@machine-1# curl -u docker:hello2 --unix-socket /run/docker.sock http:/services`
`(Okay..)`

`root@machine-2# curl -u docker:hello2 --unix-socket /run/docker.sock http:/services`
`(Okay..)`

**Comment by ghostplant** [comment]
Since docker daemon can provide API server over SSL, so I think adding extra Basic AUTH is not only simple but also secure enough. In addition, Basic AUTH will be also easy for testing tools like curl and all existing HTTP libraries (nginx/apache/tornado/..) to fully support and forwarding.

**Comment by diogomonica** [comment]
You can already do this with Authorization Plugins in Docker.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
