### ISSUE TITLE
Service logs hang after daemon restart

### ISSUE THREAD

**Issue by dperny** [moby/moby#31625]
Creating this issue for my own tracking purposes. Please assign me to it. It's going on my TODO list.

**Description**
If you stop the docker daemon, when you restart it, getting logs for services that were running when you stopped it hangs.

**Steps to reproduce the issue:**
1. `make shell`
2. Build and start docker in docker.
3. Start a service. Check the that it outputs logs
4. stop the docker in docker daemon.
5. Rebuild and start docker in docker.
6. Logs are output, but hang.

**Describe the results you received:**
Logs hang open, waiting for new data.

**Describe the results you expected:**
Logs should finish streaming and "hang up" instead of leaving the stream open.

**Additional information you deem important (e.g. issue happens only occasionally):**
Does not appear occur with Swarmkit binaries, which means something about Docker itself that's causing trouble. 

**Output of `docker version`:**

This has the latest swarmkit master vendored locally.
```
Client:
 Version:      17.04.0-dev
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   dev
 Built:        Tue Mar  7 23:25:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-dev
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   dev
 Built:        Tue Mar  7 23:25:01 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by dperny** [comment]
It's something wonky with non-running tasks 🤔 . I'm digging right now.

**Comment by dperny** [comment]
Hangs when the container for a task has been totally removed from the Docker daemon. (`docker rm` or similar)

**Comment by thaJeztah** [comment]
@dperny this is resolved by https://github.com/moby/moby/pull/33006, correct?

**Comment by dperny** [comment]
Yes, sorry.
