### ISSUE TITLE
Latest version of Dcoker Version 17.03.0-ce-mac2 (15654) breaks awsebcli

### ISSUE THREAD

**Issue by ronaldfenner** [moby/moby#31633]
After upgrading to Dcoker Version 17.03.0-ce-mac2 (15654) I got this message:
ERROR: Dependency conflict: an older version of the 'docker-py' package is polluting the namespace. Run the following command to remedy the issue:
pip uninstall docker docker-py; pip install docker
I run the command and docker compose then runs, however we are also using the awsebcli tool to deploy to elastic beanstalk and that ends up bring the command line tool.
If i then run pip install --upgrade awsebcli it fixes the command line tool and breaks docker again.

I've submitted a support request on this to AWS but I thought I'd surface this here as well so that your aware that it broke the AWS command line tool which is probably used to also deploy to AWS docker container service as well.

I'm using Python 2.7 on Mac OS X 10.11.6

**Comment by ronaldfenner** [comment]
AWS responded and opened a Ticket with the elastic beanstalk team. Hopefully they'll resolve it soon.

**Comment by thaJeztah** [comment]
Thanks for the update!

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
