### ISSUE TITLE
when live-restore is enabled and docker daemon is restarted, some of the iptables rules are duplicated

### ISSUE THREAD

**Issue by piontec** [moby/moby#31647]
**Description**
When live-restore (did not test without live-restore, though) is enabled and docker daemon is restarted, some of the iptables rules are duplicated. 

As a result, xtables_lock is getting harder to acquire, all docker operations are slowing down and performance (especially restart time) sinks.

**Steps to reproduce the issue:**
1. Run a lot of containers with forwarded ports
2. Enable live-restore and debug in dockerd
3. Restart dockerd, check rules in iptables

**Describe the results you received:**
I dumped all the rules in nat POSTROUTING after a few dockerd restarts with live-restore. We had 516 rules at the beginning, all of them unique. After some time and few restarts, we have 7587	rules, but only 805 are unique - the rest are duplicates.

We're removing the duplicates with a script that looks for duplicates and removes them with `/sbin/iptables -t nat -D POSTROUTING -p $proto --dport $dport -s $src -d $dst -j $action`

**Describe the results you expected:**

Have just 1 rule per port in the table.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens after each restart.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3-cs4
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   65c6c4c
 Built:        Fri Nov 11 16:23:03 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3-cs4
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   65c6c4c
 Built:        Fri Nov 11 16:23:03 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 237
 Running: 224
 Paused: 0
 Stopped: 13
Images: 751
Server Version: 1.12.3-cs4
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3785
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 2753
 Goroutines: 3010
 System Time: 2017-03-08T13:20:50.96366142Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, ubuntu 16.04, x1.32xlarge instance

**Comment by thaJeztah** [comment]
ping @sanimej

**Comment by aboch** [comment]
I think this is a duplicate of #27063
This was fixed by docker/libnetwork/pull/1485

**Comment by thaJeztah** [comment]
@piontec are you able to confirm if this is resolved for you on 1.13 CS (or 17.03) version?

**Comment by piontec** [comment]
We had really bad experience with 1.13, we don't want to upgrade to that version. Maybe 17.03, once we confirm with tests that it's stability is simillar to 1.12.3-cs4. I will update the ticket when we upgrade.

**Comment by piontec** [comment]
This is not happening since we upgraded to 17.03 EE.

**Comment by bklau** [comment]
@thaJeztah @piontec  Can Docker SwarmMode co-exist with --live-restore option?.
I read this "https://docs.docker.com/engine/admin/live-restore/#live-restore-upon-restart" as

"Live restore and swarm mode
The live restore option is not compatible with Docker Engine swarm mode. When the Docker Engine runs in swarm mode, the orchestration feature manages tasks and keeps containers running according to a service specification.".

Pls advised. I intent to use Docker 17.03.1

**Comment by thaJeztah** [comment]
@bklau correct; they're both largely resolving a similar problem: with swarm mode services, tasks are rescheduled to another node if a daemon goes down (for a longer period), a short restart will keep those services/tasks on the same node.

live-restore keeps the containers running, but does result in network interruption.

**Comment by bklau** [comment]
@thaJeztah @piontec : it seems that a restart of the daemon takes longer than anticipated. In order of 5mins. I  only have 2-3 containers. This can't be right. I used 17.03.1. Have you seen this behaviour??

**Comment by thaJeztah** [comment]
I have not seen this myself, but depends on "what" takes that long;

- if you have a huge amount of images on the host, this may take time (there's a check performed if images have to be migrated to a different format)
- is shutting down taking time, or starting up? 
- anything useful in the logs?

There's many things that can play a role; 5 minutes is a very long time, but perhaps there's an explanation. Discussing this in an unrelated issue is not the best place though; if you suspect there's a bug, please open an issue, otherwise feel free to ping me on Slack, or open a topic on forums,docker.com

**Comment by bklau** [comment]
@thaJeztah : I updated to Docker 17.03.6 and the problem went away. here's how to repro it:
1.  Run a  container
2. Stop the Docker daemon: sudo systemctl stop docker (This stops  immediately, almost)
3. Check that the container is still running (docker ps) and in state "Host Down"
4. Restart the daemon : sudo systemctl start docker ( This takes a long time with 17.03.1)
5. Check container is in "running" state : docker ps
