### ISSUE TITLE
Docker network doesn't remove removed containers

### ISSUE THREAD

**Issue by groyee** [moby/moby#31643]
docker version:

Client:
 Version:      1.13.1
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.5
 API version:  1.22 (minimum version )
 Go version:   go1.5.4
 Git commit:   27968ed
 Built:        Thu Aug 18 23:10:29 UTC 2016
 OS/Arch:      linux/amd64
 Experimental: false

docker info
[docker_info.txt](https://github.com/docker/docker/files/827459/docker_info.txt)

docker network doesn't remove containers. Please see attached image:

![screen shot 2017-03-08 at 13 45 44](https://cloud.githubusercontent.com/assets/194016/23702814/9304341a-0405-11e7-9741-ca18f6cae6e2.png)

As you can see it shows that useralerts containers are part of the network while they don't exist anymore. Forcing disconnect doesn't' work either.

**Comment by thaJeztah** [comment]
I see you're running swarm "standalone" and a combination of daemon versions (1.12.6, 1.13.0 and 1.13.1), wonder if the combination of versions could play a role here.

Are you using an external k/v store or the swarm-mode overlay networks (using the `--attachable` option)?

If you try disconnecting endpoints using the `EndpointID` instead of the container-name, does that work?

**Comment by groyee** [comment]
I am using external k/v store and a standalone swarm.

I don't think this is related to versioning. It is true that some of the hosts running a newer version of docker.  However in the above scenario only the useralerts hosts, swarm and the consul play a role and they all running the same version:

![screen shot 2017-03-08 at 14 42 28](https://cloud.githubusercontent.com/assets/194016/23704473/d2c124b6-040d-11e7-9920-c942bdb8ba67.png)

Removing by EndpointID results in the same error message.

**Comment by thaJeztah** [comment]
overlay networks with external k/v stores was disabled and removed; closing this ticket
