### ISSUE TITLE
Can't run validation scripts using only Docker remote API dependency

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#31673]
```
make validate
...
fatal: Not a git repository (or any of the parent directories): .git
make: *** [validate] Error 128
```

@vdemeester @thaJeztah

**Comment by vdemeester** [comment]
hum it shouldn't happen with `make` 😱 … I'll take a look

**Comment by vdemeester** [comment]
@tonistiigi when does this happen ? (on master I can't reproduce 😓)

**Comment by vdemeester** [comment]
it can happen if you're targeting a remote daemon though (as it bind-mount the `.git` folder for `validate`)

**Comment by tonistiigi** [comment]
@vdemeester Yes, that's what I meant by "only Docker remote API".

**Comment by vdemeester** [comment]
ahah, didn't read correctly the title of the issue :sweat_smile:

**Comment by tonistiigi** [comment]
@vdemeester Why was this closed?

**Comment by vdemeester** [comment]
I don't think we're going to fix that in the near future (and with the moby split, etc..) I feel this going to be fixed another way.

I'm ok to re-open and wait for something like https://forums.mobyproject.org/t/proposal-split-containerize-hack-validate/32 fixing it though :wink:

**Comment by tonistiigi** [comment]
I'm not sure how https://forums.mobyproject.org/t/proposal-split-containerize-hack-validate/32 could fix it as it uses volumes as well(at least for the syntax proposed, validator image itself could probably be used without them as well).

**Comment by vdemeester** [comment]
Hum right… what I meant is that with the split into each components, each one will handle this on their own.
