### ISSUE TITLE
docker push failed when content trust using notary is set

### ISSUE THREAD

**Issue by chunglam1999** [moby/moby#31670]
OS Centos7
docker-engine-1.13.1-1.el7.centos.x86_64
docker-registry-0.6.8-8.el7.noarch
notary v0.4.3

export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=https://127.0.0.1:4443
**Description**
docker push failed when content trust using notary is set with error:
[0025] sign called with 1/1 required keys           
DEBU[0025] No yubikey found, using alternative key storage: no library found 
DEBU[0025] sign called with 0/0 required keys           
Finished initializing "localhost:5000/notary043_signer"
Failed to sign "localhost:5000/notary043_signer":latest - no hashes specified for target ""
no hashes specified for target ""
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
checking the targets.json (not signed), the 'hashes' is missing.
{"signed":{"_type":"Targets","delegations":{"keys":{},"roles":[]},"expires":"2020-03-07T12:51:17.46356214-08:00","targets":{},"version":1},"signatures":[{"keyid":"32514c18857300546ea3cefeeb1dea31bfcb59c1ea3bf4b4d4a4f86bc8002134","method":"ecdsa","sig":"Ba1wCYL2NKOyQyV/adoybStbMCJ2JmMMAded7OuRkHyhcaBOeq2N/BOM88xwCDjhkbWTHcAV73XR7UFTf0Nyyg=="}]}

**Steps to reproduce the issue:**
1.export DOCKER_CONTENT_TRUST=1
2. export DOCKER_CONTENT_TRUST_SERVER=https://127.0.0.1:4443
3. systemctl start docker
4.systemctl start docker-registry
5.for notary: 'docker-compose up'
6. docker pull hello-world
7. docker tag hello-world localhost:5000/hello-world
8. docker push localhost:5000/hello-world:latest
9. config.json:
{
        "trust_dir" : "~/.notary/trust",
        "remote_server": {
                "url": "https://localhost:4443",
                "root_ca": "/root/notary-0.4.3/fixtures/root-ca.crt"
        }
}

**Describe the results you received:**
Failed to sign "localhost:5000/notary043_signer":latest - no hashes specified for target ""
no hashes specified for target ""

**Describe the results you expected:**
should be successful and return the key for 'docker push'

**Additional information you deem important (e.g. issue happens only occasionally):**
always
**Output of `docker version`:**
[root@localhost .notary]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
(paste your output here)
```

**Output of `docker info`:**
[root@localhost .notary]# docker info
Containers: 11
 Running: 6
 Paused: 0
 Stopped: 5
Images: 26
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-251:0-1385386-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.858 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39 GB
 Metadata Space Used: 4.985 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Operating System: Centos 7
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.466 GiB
Name: localhost.localdomain
ID: AXPM:IDPE:W6QQ:GFYM:WWWC:NZUZ:IQLI:EWJF:KW4J:VGSI:ZAUI:Z7RN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @cyli @endophage

**Comment by endophage** [comment]
This looks like it might be related to a similar error we saw in DDC. It seems like maybe something has changed in 1.13 in how the image name string, i.e. `localhost:5000/hello-world:latest` is parsed and communicated over the engine API?

**Comment by riyazdf** [comment]
@endophage: hm that could be a possible cause since it seems to pick up `""` as the target (tag)

@chunglam1999: could you please post the full debug logs for `DOCKER_CONTENT_TRUST=1 docker push localhost:5000/hello-world:latest`?
