### ISSUE TITLE
Network Aliases can be duplicated in service spec but cannot in compose yaml; and cannot be updated with different order 

### ISSUE THREAD

**Issue by pacoxu** [moby/moby#31691]
problems and steps to reproduce:
1. I can create service with duplicate aliases like
`{Target: "qmx102g5pm9qyytv3dntkbgj3", Aliases: ["2048", "dao2048", "dao2048", "dao-2048"]}
`
2. In docker compose, duplicate aliases are not supported.
```
version: '3'
services:
  abc:
    image:nginx:latest
    ports:
      - 80
    networks:
      test:
        aliases:
        - abcd
        - abcd
```
the stack deploy log
```
root@dce177:~/nginx# docker stack deploy abc --compose-file docker-compose.yml
services.abc.networks.test.aliases array items must be unique
```

3. When I run deploy stack with compose, the network aliases are same as before and are only de-duplicated. If not, I will get error like ''.
`{Target: "qmx102g5pm9qyytv3dntkbgj3", Aliases: ["2048", "dao2048", "dao-2048"]}`
`"rpc error: code = 2 desc = changing network in service is not supported"`

4. When I test the update service API, the network aliases order must be as before. If not, I will get error like ''.
`"rpc error: code = 2 desc = changing network in service is not supported"`
`{Target: "qmx102g5pm9qyytv3dntkbgj3", Aliases: ["2048", "dao2048", "dao-2048", "dao2048",]}`

How to fix this? I'm not sure and below are my suggestions
- current service update logic uses reflect.DeepEqual() and we may change it to compare each aliases lists.
- we may use unique set instead of array[] for aliases. 
- just de-dup aliases list when creating or updating service and compare the ordered list with reflect.DeepEqual().

```
root@dce177:~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Thanks.

**Comment by dnephin** [comment]
How were you able to create the service with duplicate aliases? You should get the error "services.abc.networks.test.aliases array items must be unique"

**Comment by yongtang** [comment]
@pacoxu I think you created the service through docker remote API?

In that case, the compose behavior you described seems to be about right. Aliases should be unique and updating a network with different list of alias will return an error, as technically the network spec has been changed and updating network is not implemented yet. 

The docker remote API for service creation does not check for uniqueness of the alias list. I think that is something that could be addressed.

For the order of the alias list, I think we could leave the order alone and require that the order be maintained when service is updated. Would like to hear opinions on this issue though.

**Comment by pacoxu** [comment]
@dnephin,  as @yongtang  thought, I use remote API and I am using docker 17.03.0-ce. I cannot find way to create service with aliases and never get the error. Do you mean to add a validation during service creating?

> 
![image](https://cloud.githubusercontent.com/assets/2010320/24001120/3c7d6280-0a98-11e7-8b3e-8ad12ec15518.png)


@yongtang As the CLI supports to deploy stack now and this would be a problem later and we need to figure out a way to solve this.
