### ISSUE TITLE
Enhancement: option to use only msg.Line as payload

### ISSUE THREAD

**Issue by sascha-andres** [moby/moby#31726]
Reason for the enhancement: Logentries has powerful query operations when using JSON. For applications written with that capabilities in mind wrapping the JSON formatted log into a de-serialized go struct makes life a bit harder.

Proposal for the enhancement: add logentries-line-only=true and pass then msg.Line only

**Comment by thaJeztah** [comment]
Closing because this was implemented in https://github.com/moby/moby/pull/31727, which is included in Docker 17.09 and up
