### ISSUE TITLE
[REQUEST] multiple feature requests

### ISSUE THREAD

**Issue by babatundebusari** [moby/moby#31747]
1. **Have a way to bundle multiple COPY and ADD commands just like it works for RUN command**
e.g 

```
ADD file1.txt /files/file.txt && \
        folder1/files2.txt /files/file2.txt && \
        file3.txt /files/file3/file.txt

```
same for copy

```
COPY file1.txt /files/file.txt && \
        folder1/files2.txt /files/file2.txt && \
        file3.txt /files/file3/file.txt

```

2. **Multiple ARG and ENV commands as well**
e.g
```
ARG DB_HOST1, DB_HOST2, DB_USER1, DB_USER2
ENV DB_HOST1 dbhost1.example.com, DB_HOST2 dbhost2.example.com, DB_USER1 user1, DB_USER2 user2
```

3. **Allow multiple use of --build-arg at build time as well**

`docker build --build-arg DB_HOST1=dbhost1.example.com, DB_HOST2=dbhost2.example.com, DB_USER1=user1, DB_USER2=user2 ...`
Thanks!!!

**Comment by duglin** [comment]
You can do the ENV today: `ENV foo1=bar1 foo2=bar2 ...`
While I understand the specifying multiple ARGs on the same line would be nice, putting them on different lines won't create layers so it shouldn't impact your build sizes.

**Comment by aelrazek** [comment]
#dibs

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
