### ISSUE TITLE
Proxy Mode for Swarm Worker Node

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#31762]
'docker node/services' doesn't work for Docker swarm workers which belongs to a current design.
However, every swarm worker is able to look up the address of swarm managers. So I think swarm worker should proxy this request to a random swarm manager (just like what etcd does), thus, making 'docker node/services' work for swarm worker nodes.

**Comment by furkanmustafa** [comment]
it feels like the "worker" nodes are not trusted to access the swarm managers, workers only do what they're told to do.

But it could show us whey it already knows, I was expecting at least;

```
# docker node inspect self
(information about local swarm worker node)

# docker service ls
(information about services scheduled only to this worker)
```

**Comment by ghostplant** [comment]
Current swarm worker is just like a node who known nothing about the self status in a swarm cluster.

As for trusted consideration, I think only if swarm can provide swarm AUTH (https://github.com/docker/docker/issues/31601), can we saftly allow swarm workers to proxy manager API.

**Comment by ghostplant** [comment]
Assume we have 100 swarm nodes, and we want every node to be able to update swarm via API.

If proxy mode is not enabled, we need to join all of them as managers, thus, the performance of built-in etcd will be extremely poor.

**Comment by thaJeztah** [comment]
Can you explain the use case? Why would you want every worker to be able to control the swarm? This is by design; you only have a number of trusted managers are able to control the swarm, workers don't have this privilege and are only used to handle loads (run the service), but not allowed to control the swarm

**Comment by ghostplant** [comment]
One question is what the maximum number of swarm manages can be joined together?

Since they need to SYNC global store between every pair, it is not recommended for too many managers to be joined together (smaller than 9 managers is a good choice).

So if each swarm node is needed to handle the swarm status, all of they must be joined as manager, even if there are 100 swarm node.

**Comment by ghostplant** [comment]
Proxy mode is a solution that doesn't increase the load of SYNC global store and provide more manager-like swarm node.

**Comment by thaJeztah** [comment]
> So if each swarm node is needed to handle the swarm status, all of them must be joined as managers, even if there are 100 swarm nodes.

You still haven't explained the use case

**Comment by ghostplant** [comment]
The use case is for hundreds of thousands of node to form a large-scale swarm cluster, we are usually not expecting at most 9 swarm nodes have the access to control the swarm status.

**Comment by thaJeztah** [comment]
But why do you need to have "manager" access on all nodes? The manager is your "control" point for managing the swarm; what is your use case to give _every_ node manager permissions / access?

**Comment by ghostplant** [comment]
Firstly, I don't think proxy for the swarm manager API means to give permissions to control swarm, which is mainly because swarm is without a global AUTH protection at the moment.

Secondly, I think the design of current worker role is necessary because there are use cases that a worker is from private resources which is untrusted, so the role of worker is also needed.

Apart from the design of manager and worker, there is another role "fake manager" between them two, who works actually the same as a worker but with proxy manager service enabled, so the API interfaces it provides is fully as same as a real manager provides in a transparent way. Without this role, the architecture of swarm is fixed and centralized only. For a service provider who has a plenty of nodes without untrusted one, they might choose either "manager" or "fake manager" for each node to make it non-centralized since each of their nodes is symmetrical with each other and they don't want to shrink functions for most the nodes (due to as worker), especially when they need to swap roles between manager and worker that makes all clients connecting a previous manager address to change to connecting a new address.

Proxy mode was applied in etcd in the past to enlarge the scale of node number to support fully non-centralized etcd services, and I think the use case and reason of it might be the same. At least for me, I just want to build a swarm cluster with all managers (maybe including fake ones) and make all clients related to it not to update communication target every time even if each node is potential to be promoted and demoted.

**Comment by diogomonica** [comment]
We're thinking about providing this use-case through`host-view`, `host-control`, `swarm-view` and `swarm-control` entitlements. @aluzzardi has a few ideas on how to mount the right socket in the container, and proxy it to the managers transparently in the case of `swarm-*`

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
