### ISSUE TITLE
Container failes to read host shared files from local drives

### ISSUE THREAD

**Issue by asolopovas** [moby/moby#31766]
Hi, 

I am using docker for fullstack development. Basically I run lemp stack https://github.com/asolopovas/lyndock, and Nodejs+Gulp+browsersync+webpack to compile my scss and babel js files. Development files are stored locally on my windows machine, and they are shared across docker containers. All compilations happen on my windows host. The problem that I have is that after files compiled they become unavailable temporarily inside the container and nginx throws an error when I try to access newly compiled file via browser.

```
The localhost page isn’t working

localhost unexpectedly closed the connection.
ERR_CONTENT_LENGTH_MISMATCH
```

I fill that this issue https://github.com/laradock/laradock/issues/615 is caused by the same problem that I am having.

I tried completely rebuilding all container, reset docker to defaults share folder again, but still face the same issue

**Steps to reproduce the issue:**
1. I have spent a bit of time and created this repository to illustrate the problem https://github.com/asolopovas/docker_problem
2. After running init.cmd with administrator privileges it will add domain.dev and mariadb hosts to system/hosts file in order to load up then it will loadup browsersync that will be avail on http://localhost:3000
3. Then you should try to go to \vhosts\domain.com\wp-content\themes\twentysixteen\resources\assets\sass\app.scss and try to comment and comment out imports and see how application behaves in the devtools
4. If you open http://domain.dev or  and try to access http://domain.dev/wp-content/themes/twentysixteen/public/css/app.css it will be throwing the same error with message 
5. Your will need Node.js, Yarn and Composer installed to run the depository I compiled
https://nodejs.org/dist/v7.7.2/node-v7.7.2-x64.msi
https://yarnpkg.com/latest.msi
https://getcomposer.org/Composer-Setup.exe

```
The domain.dev page isn’t working

domain.dev unexpectedly closed the connection.
ERR_CONTENT_LENGTH_MISMATCH
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 37
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: REWW:OF45:THEA:M46E:NXYE:M6S2:UFLZ:OTIW:E5GM:PHYJ:I7HB:77DD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 74
 Goroutines: 81
 System Time: 2017-03-12T18:45:25.3363807Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
this one is really old now and the reproduction repository has been removed (https://github.com/asolopovas/docker_problem), so closing
