### ISSUE TITLE
No route to host dependending on target container network

### ISSUE THREAD

**Issue by maxdebayser** [moby/moby#31789]
I have a container that needs to access services on the same machine provided by other containers. Some of these containers use the default network bridge and I can connect without problems to their exposed port via the machine's public IP (no localhost access). Some other containers are inside a docker network, and from another machine I can access the ports they expose to the external interface. However, I can't access these from another container on the same machine, I get "no route to host", which doesn't make sense, since it is the same host.

Container A -> public IP -> Container B (default bridge) -> Works
Container A -> public IP -> Container C (docker network) -> "no route to host"

I don't understand how docker's firewall rules interfere with this since in both cases I'm connecting to an exposed port on the external network interface. If I run "Container A" with host networking the issue goes away.

My docker version is 1.10.3, I'm running on Fedora 23

**Comment by thaJeztah** [comment]
can you add the full output of `docker version` and `docker info`?

**Comment by maxdebayser** [comment]
$docker info

Containers: 32
 Running: 24
 Paused: 0
 Stopped: 8
Images: 538
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 16
Total Memory: 251.9 GiB
Name: myhost
ID: 4IV4:IP7Y:GW4A:ZPNR:PFFL:ARHH:BNAT:YDPZ:5FGL:XNPE:B24Y:BPV6
Registries: docker.io (secure)

$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-45.gite03ddb8.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-45.gite03ddb8.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64

**Comment by thaJeztah** [comment]
If looks like you're running the Red Hat fork of Docker (https://github.com/projectatomic/docker/commit/e03ddb80cc2e3244b70052ec38d29cf526444c59), which contains a [_lot_ of changes compared to the official packages](https://github.com/docker/docker/compare/v1.10.3...projectatomic:e03ddb80cc2e3244b70052ec38d29cf526444c59). Are are you able to reproduce the issue on the current version? https://docs.docker.com/engine/installation/linux/centos/

**Comment by antoinetran** [comment]
We experienced the same issue. We use docker-engine 1.11.2 and CentOs 7. The thing is that iptables open ports with docker in forwarding table, but not in INPUT table. As a workaround, we had to open a specific rule in iptables/firewalld. The fix is that docker put a rule both in INPUT and FORWARD table.

**Comment by getvivekv** [comment]
I think we are also getting this error when docker 17.05 with swarm mode/overlay. A container is not able to communicate to another container

**Comment by antoinetran** [comment]
The fix is supposed to be in 17.06, not in 17.05.

**Comment by wedtm** [comment]
Do you have the specific commit/changelog item that mentions this in 17.06? Would be nice to track down the root cause.

**Comment by antoinetran** [comment]
Oh sorry, I though this was another issue.

**Comment by SebastianStehle** [comment]
I have a similar problem. I have two containers: Nginx as reverse proxy and a asp.net core app. The Asp.net Core App needs to make requests to itself using the public host name. But it fails and when I try to make a request with the public ip or the hostname it returns "No route to host".

curl localhost works fine. I can also reach the service from outside.

**Comment by zhiyuli** [comment]
Same issue. Worked it around by manually adding rules in INPUT table as it is suggested here by others.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
