### ISSUE TITLE
Swarm worker node unable to join Swarm Manager node

### ISSUE THREAD

**Issue by vivekkrdubey** [moby/moby#31810]
Docker Swarm Init - Docker Host IP1
-------------------------------------------

docker swarm init --advertise-addr IP1:PORT1 -
To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-2zofuhvi2js1pgpdidmp1zr9wb4sm9izxyemdw5x2kh64fvr2c-cq4cmes99t6luajmajvvtbdaw \
    IP1:PORT1

Docker Swarm Worker Node - IP2
------------------------------------
docker swarm join --token SWMTKN-1-41vyxfb6fa2h2q3p9cm3ybubhr5tja7unkz0fkwaxfr1cd8rav-d6onninmqa6hx55v8d1o36v86 IP1:PORT1

**Error response from daemon: rpc error: code = 13 desc = connection error: desc = "transport: remote error: tls: handshake failure"**

NW connectivity is fine and Swarm Manager node has been set with --tlsverify or any TLS certificates

**Comment by ripcurld0** [comment]
@vivekkrdubey -- so if I understood correctly there was a connectivity problem between the manager and the node that caused that error message. Right?

**Comment by thaJeztah** [comment]
Can you provide more information about how those nodes are running? Are they running bare-metal, in the cloud, in VM's? In the same network or different locations? Have you checked if the log files show anything useful?

**Comment by thaJeztah** [comment]
It may also be worth checking if clocks are in sync for those nodes (to exclude possibilities)

**Comment by aluzzardi** [comment]
@vivekkrdubey Could you include the engine logs as well? You typically can fetch them using `journalctl -u docker.service` IIRC if using systemd.

**Comment by vivekkrdubey** [comment]
Thanks for your comments.
The nodes are running on AWS REDHAT Linux VMs without any delay in clock-sync.
Just to update you all,
I have just started learning Docker and only installed 2 standalone Docker Hosts as per Linux installation instructions with both of these nodes have Docker Daemon running.
Now, I have not setup any TLS certs yet on any of these nodes and error {which is generated when Swarm worker node attempts to join Swarm Manager(running without TLS enabled)} clearly mentions 
**Error response from daemon: rpc error: code = 13 desc = connection error: desc = "transport: remote error: tls: handshake failure"**

So does this mean that I have to setup TLS certs in order for the Swarm Nodes to join Manager.
If yes, then help me understand that if IP2(assuming to-be worker ) and IP1(Manager) are participating nodes in the Swarm cluster, then how shall I set up TLS certs on both nodes so that Worker Node can join. 
**Is it simple case of assuming IP2 as Client and IP1 as Server and following the steps mentioned in**
https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl

Any suggestion would be helpful.

Thanks
vivek

**Comment by thaJeztah** [comment]
Those steps are to protect the API if you want to remotely connect to the API over HTTP.

For nodes to join the swarm, docker automatically generates/manages certificates, there should be no need to follow those steps for this to work (see https://docs.docker.com/engine/swarm/how-swarm-mode-works/pki/ for more information about key management in Swarm mode)

**Comment by vivekkrdubey** [comment]
@thaJeztah  : I agree as I am reading more and understanding it.
however , my new observations perhaps suggests that Worker Node is unable to connect Advertised Address on Manager Node.
So I added another attribute (--listener-add) while starting swarm on Manager Node.
and when I use listener-addr while joining the cluster (from Worker Node) it joins successfully. 
Although, not sure if the above solution is right one, but the same does not work if I try to join as Manager from Worker node using manager's token.

Any Idea, why Advertised Address is not working

**Comment by WahidSyed** [comment]
Hi All,

I'm also getting the same error but with a slight change in the error description.
Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable.
This is exactly after I initiated my SWARM in the Manager node and trying to add my worker node at the CLI not using the shell script.

Please help me around as I need to group multiple worker nodes to this Manager.

Thank You!
Syed.

**Comment by DracotMolver** [comment]
I'm facing the same issue with VM in Hyper V. (I did start docker-machine with `docker swarm init`)

* Docker version
`Docker version 17.09.0-ce, build afdb6d4`
* Docker info
```log
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: DHBM:VCCQ:QX4H:2CZC:OKU2:PB4Y:W6UB:MJFV:G2HN:YN6I:UMGD:TWBT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 25
 System Time: 2017-11-08T19:14:33.8140824Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* Docker machine ls
```log
NAME    ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER        ERRORS
myvm1   -        hyperv   Running   tcp://IP.69:2376           v17.10.0-ce
myvm2   -        hyperv   Running   tcp://IP.70:2376           v17.10.0-ce
```
* Docker node ls

```log
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
fe8q0ztmfle0v4jwmxvwnva5v *   moby                Ready               Active              Leader
```

I'm following the  [Docker tutorial](https://docs.docker.com/get-started/part4/#create-a-cluster)

VM
![screenshot_1](https://user-images.githubusercontent.com/13334764/32569906-53e2537c-c4a1-11e7-963f-aa70270812a1.png)

**Comment by Dekado** [comment]
Same issue like DracotMolver. Cannot walk through tutorial =(

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
