### ISSUE TITLE
Markdown API docs: NetworkingConfig not described

### ISSUE THREAD

**Issue by johnflavin** [moby/moby#31821]
The markdown API docs are missing any description for the `NetworkingConfig` object that is included in the config to create a container. This object is included in the example JSON that gets POSTed to `/containers/create` in the 1.22, 1.23, and 1.24 docs, but is not mentioned in the following "JSON Parameters" section. In particular, its child object `EndpointsConfig` is not fully defined.

This issue only affects the older markdown API docs. The objects mentioned above are defined in more detail in `api/swagger.yaml`. For the most part, the various places in the swagger description of the API that accept or produce information about networks refer to `#/definitions/EndpointSettings`.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and we're using a swagger file now for the API docs
