### ISSUE TITLE
Windows: not possible to extend LSA in container?

### ISSUE THREAD

**Issue by erik-am** [moby/moby#31876]
In Windows it's possible to extend the Authentication Mechanisms used by the Local Security Authority (LSA) by adding a DLL to this registry key: `SYSTEM\CurrentControlSet\Control\Lsa`.

According to the [Windows documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378339(v=vs.85).aspx):
> When the computer system is started, the Local Security Authority (LSA) automatically loads all registered security support provider/authentication package (SSP/AP) DLLs into its process space. 

There is a Windows port of OpenSSH that makes use of this principle. 

Now there are issues with running this OpenSSH port inside a Windows Docker container, see https://github.com/PowerShell/Win32-OpenSSH/issues/378

After debugging it turns out that `ssh-lsa.dll`, which has been added to `SYSTEM\CurrentControlSet\Control\Lsa`, is not loaded.
Normally loading of the LSA dll's is forced by restarting the computer, but restarting the Docker container does not trigger the same behaviour.

Any ideas if extending the list of LSA DLL's could work in a Docker container? And how to trigger a reload of LSA in a Docker container?

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft ptal

**Comment by jhowardmsft** [comment]
@patricklang can you follow up with the right folks

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
