### ISSUE TITLE
why containers can not connect to parent host?

### ISSUE THREAD

**Issue by wallishuang** [moby/moby#31873]
This has already perplexed me for a long time...
In swarm mode,  docker1(manager node) , docker2(worker node), docker3(worker node)
Containers of docker1 and docker2 are work well,  but all containers of docker3 can not connect to the docker3 host ip and docker3 connect itself fine. anybody know why?

# ## docker3 connect itself response successful...
`[root@docker3 ~]# curl http://172.20.2.31:8763/health
{"description":"Spring Cloud Eureka Discovery Client","status":"UP","discoveryComposite":{"description":"Spring Cloud Eureka Discovery Client","status":"UP","discoveryClient":{"description":"Spring Cloud Eureka Discovery Client","status":"UP","services":["demo-statistics-service","demo-authority-service","demo-account-service","demo-registry","demo-gateway","demo-notification-service"]},"eureka":{"description":"Remote status from Eureka server","status":"UP","applications":{"DEMO-STATISTICS-SERVICE":1,"DEMO-SPRING-BOOT-ADMIN":0,"DEMO-AUTHORITY-SERVICE":2,"DEMO-ACCOUNT-SERVICE":2,"DEMO-REGISTRY":3,"DEMO-GATEWAY":1,"DEMO-NOTIFICATION-SERVICE":1}}},"diskSpace":{"status":"UP","total":10725883904,"free":9965465600,"threshold":10485760},"refreshScope":{"status":"UP"},"configServer":{"status":"UP","propertySources":["https://github.com/wallishuang/spring-cloud-setting/application.yml"]},"hystrix":{"status":"UP"}}
`

# ##The container of docker3 host can not connect to docker3 ip
```
root@94ddd41f5d2f:/# curl http://172.20.2.31:8763/health
curl: (7) Failed to connect to 172.20.2.31 port 8763: Connection timed out
root@94ddd41f5d2f:/# 
```

__

Hello @gianarb  , more docker info is following... if you wanna know other information, please tell me, thax~~~~

```
Containers: 16
 Running: 2
 Paused: 0
 Stopped: 14
Images: 14
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-202766553-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.737 GB
 Data Space Total: 107.4 GB
 Data Space Available: 46.02 GB
 Metadata Space Used: 6.205 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: active
 NodeID: c23qh5eqgxsbxjlhm6ftpkf3k
 Is Manager: false
 Node Address: 172.20.2.31
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.51 GiB
Name: docker3
ID: 4OXT:4AXI:MMZA:4CDR:I42U:OWNM:FFA4:QNRD:MJVS:24AK:3OFE:PP7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```
_

I found the docker0 was DOWN, is it causing the problem? if so, anybody know  how to turn it UP?

```
61: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:8c:74:c2:81 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by gianarb** [comment]
Hello @wallishuang thanks for your report.
Can you paste some information about which version of docker you are running and the docker info form the master?

Thanks

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
