### ISSUE TITLE
docker ps / ps -a are locked

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#31921]
When I run a stack with multiple services, the `docker ps(-a)` command is locked
Why the command is locked ?

**Comment by thaJeztah** [comment]
Can you please provide the information that's requested in the issue template? (`docker version`, `docker info`, steps to reproduce, daemon logs that may provide more information)
https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by sylvainmouquet** [comment]
**Steps to reproduce the issue:**

1. Create a file stack.yml

```
version: "3"

services:

  nginx:
    image: nginx:latest
```

2. Deploy the stack
`docker deploy -c stack.yml STACK`

3. Scale the service
`docker service scale STACK_nginx=10`

4. Check the lock time with running 3 times this command :
`time docker ps`

```
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                  PORTS               NAMES
a385f9511bf8        nginx@sha256:52a189e49c0c797cfc5cbfe578c68c225d160fb13a42954144b29af3fe4fe335   "nginx -g 'daemon ..."   18 seconds ago      Up Less than a second   80/tcp, 443/tcp     STACK_nginx.4.q4tl3hcea8mfwk9frv6j4aecx
ba07505e1cf3        nginx@sha256:52a189e49c0c797cfc5cbfe578c68c225d160fb13a42954144b29af3fe4fe335   "nginx -g 'daemon ..."   18 seconds ago      Up Less than a second   80/tcp, 443/tcp     STACK_nginx.1.mv0twzkcf8epnvthjd822noy0

real	0m15.442s
user	0m0.008s
sys	0m0.007s
```

**Result :  15 seconds**

5. After all containers are created the time is quick :
`time docker ps`
real	0m0.023s
user	0m0.009s
sys	0m0.009s

**Comment by sylvainmouquet** [comment]
I close this issue the lock is more the fact that there is a delay for docker to create containers
