### ISSUE TITLE
docker --restart=always -p changes port with each restart

### ISSUE THREAD

**Issue by ceecko** [moby/moby#31926]
**Description**
When a container uses `--restart=always -p` the port changes with every automatic restart. This was not the case with `v1.13` - is this intentional?

**Steps to reproduce the issue:**
1. `docker run --restart=always -p 8000 debian:jessie sleep 2`
2. Run `docker ps` a couple times to check the assigned port

**Describe the results you received:**
The port changes with every restart

**Describe the results you expected:**
The port should probably stay the same

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 43
 Running: 38
 Paused: 0
 Stopped: 5
Images: 27
Server Version: 17.03.0-ce
Storage Driver: devicemapper
 Pool Name: data-docker_thin
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 14.39 GB
 Data Space Total: 96.64 GB
 Data Space Available: 82.25 GB
 Metadata Space Used: 21.34 MB
 Metadata Space Total: 536.9 MB
 Metadata Space Available: 515.5 MB
 Thin Pool Minimum Free Space: 9.664 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.305 GiB
Name: us-1
ID: 6UKZ:VSEG:Z6FX:3A7K:YS6F:HUMA:HWFR:7D3L:IZIG:OVT4:33FA:GNDN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by aboch** [comment]
Not aware of any changes that could have created this. But I see the problem too.

**Comment by wenjianhn** [comment]
Introduced by docker/docker/pull/12927
Let me fix it.

**Comment by wenjianhn** [comment]
I am not sure if this is a bug.
If not, I will add a unit test for the feature.

It help avoid sending port updates to consuming services. I don't know if 
this is a common use case. 

@aboch What do you think of it?

**Comment by aboch** [comment]
@wenjianhn Thanks for looking into this.

Submitter says the problem did not happen with v1.13 image. The port allocator change you mentioned happened more than a year before that.
 
This is strange. I think we should look somewhere else, I think in 1.13 and before the dynamically allocated port was somehow preserved and then requested explicitly.

**Comment by ceecko** [comment]
Any news?

**Comment by wenjianhn** [comment]
@ceecko could you verify that v1.13 works as expected?

In my test, it doesn't.

```
INFO[0002] Docker daemon                                 commit=bf9ad6a graphdriver=overlay2 version=1.13.1
INFO[0002] API listen on /var/run/docker.sock           

root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# docker run --restart=always -p 8000 debian:jessie sleep 2
ERRO[0016] Handler for POST /v1.26/containers/create returned error: No such image: debian:jessie 
Unable to find image 'debian:jessie' locally
jessie: Pulling from library/debian
9f0706ba7422: Pull complete 
Digest: sha256:4bc62f74d246e8428be8dd3833461ba2cfd135064aed4001f3c12b87a011e30c
Status: Downloaded newer image for debian:jessie
root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# 
root@df6417e12a9c:/go/src/github.com/docker/docker# ps aux|grep debian
root      6776  0.0  0.0  11132   992 pts/0    S+   23:33   0:00 grep debian
root@df6417e12a9c:/go/src/github.com/docker/docker# docker run --restart=always -p 8000 debian:jessie sleep 2
root@df6417e12a9c:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                         PORTS                     NAMES
097967fe9fb9        debian:jessie       "sleep 2"           4 seconds ago       Up Less than a second          0.0.0.0:32776->8000/tcp   pensive_euclid
202f5190439e        debian:jessie       "sleep 2"           30 seconds ago      Restarting (0) 5 seconds ago                             hardcore_gates
root@df6417e12a9c:/go/src/github.com/docker/docker# docker run --restart=always -p 8000 debian:jessie sleep 2
root@df6417e12a9c:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                         PORTS                     NAMES
2b2ea8a599d5        debian:jessie       "sleep 2"           4 seconds ago       Up Less than a second          0.0.0.0:32782->8000/tcp   peaceful_hugle
097967fe9fb9        debian:jessie       "sleep 2"           14 seconds ago      Up Less than a second          0.0.0.0:32781->8000/tcp   pensive_euclid
202f5190439e        debian:jessie       "sleep 2"           40 seconds ago      Restarting (0) 4 seconds ago                             hardcore_gates

```

**Comment by wenjianhn** [comment]
ceecko, could verify that v1.13 works as expected?

In my test, it doesn't.

```
INFO[0001] Docker daemon                                 commit=bf9ad6a graphdriver=overlay2 version=1.13.1
INFO[0001] API listen on /var/run/docker.sock           

root@4ae409ba4a18:/go/src/github.com/docker/docker# docker run --restart=always -p 8000 debian:jessie sleep 2
ERRO[0009] Handler for POST /v1.26/containers/create returned error: No such image: debian:jessie 
Unable to find image 'debian:jessie' locally
jessie: Pulling from library/debian
9f0706ba7422: Pull complete 
Digest: sha256:4bc62f74d246e8428be8dd3833461ba2cfd135064aed4001f3c12b87a011e30c
Status: Downloaded newer image for debian:jessie
root@4ae409ba4a18:/go/src/github.com/docker/docker# 
root@4ae409ba4a18:/go/src/github.com/docker/docker# 
root@4ae409ba4a18:/go/src/github.com/docker/docker# 
root@4ae409ba4a18:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS                     NAMES
6cf940b1e0bf        debian:jessie       "sleep 2"           9 seconds ago       Up Less than a second   0.0.0.0:32771->8000/tcp   quizzical_curran
root@4ae409ba4a18:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                                  PORTS               NAMES
6cf940b1e0bf        debian:jessie       "sleep 2"           15 seconds ago      Restarting (0) Less than a second ago                       quizzical_curran
root@4ae409ba4a18:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS                     NAMES
6cf940b1e0bf        debian:jessie       "sleep 2"           22 seconds ago      Up Less than a second   0.0.0.0:32774->8000/tcp   quizzical_curran
root@4ae409ba4a18:/go/src/github.com/docker/docker# 
...
root@4ae409ba4a18:/go/src/github.com/docker/docker# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS                     NAMES
6cf940b1e0bf        debian:jessie       "sleep 2"           About a minute ago   Up 1 second         0.0.0.0:32777->8000/tcp   quizzical_curran


```

**Comment by ceecko** [comment]
@wenjianhn I just checked and v1.13 does not work as expected, but v1.12.0 does.

**Comment by jlbutler** [comment]
I'm just cleaning up bugs that we are tracking... Is this actually a bug?

-p publishes the container port to the range of ports available; without using the 'host' portion of the 'host:guest' publish mapping, it lands on an available port within that ephemeral range. Setting restart=always simply automates the restart of a container. Without the host port specified, it seems to me that with each restart, it could land on a different host port without it being a bug as relates to current documentation.

@aboch @fcrisciani @cpuguy83 what do you think?

**Comment by ceecko** [comment]
@jlbutler it's not a bug per se. It's a change in behavior which I'm not sure if it was intentional. The side effect is that whenever a container is restarted, the port changes and in case there's a load balancer in front of the containers, its config needs to be updated to reflect the new container's port. This results in frequent updates of configs which depend on the containers' configuration.

The functionality of docker is not affected though.

**Comment by jlbutler** [comment]
Isn't the workaround for such an issue to specify a host port?

**Comment by ceecko** [comment]
Specifying a host port introduces additional overhead in terms of keeping track of the available ports on the server. When containers are started and stopped the scheduler needs to pick an available port, assign it to a container and avoid any race conditions.

It's easier to let docker decide about the ports and just work with whatever port has been assigned.
v1.12 tried its best not to change the port during restarts (if it was still available) which in turn was close to specifying a static host port.

**Comment by fcrisciani** [comment]
@jlbutler did you try: `docker run --restart=always -p 8000:<port that you want not to change> debian:jessie sleep 2` that way the port that you specify will never change

**Comment by jlbutler** [comment]
@fcrisciani I don't have an issue, rather that's what I suggested to be the correct way to work around the issues indicated above :)

@ceecko Fair enough. It's worth looking into, I just didn't find it to be something I'd consider a bug... it seems we agree there. Thanks!

**Comment by fcrisciani** [comment]
In general I would expect from docker the same as using an ephemeral port. If the user let docker decide, that will need to fetch from the inspect the port allocated. If instead there is a need for a specific port then you need to have it explicitly specified.

**Comment by ceecko** [comment]
@fcrisciani I agree. However when the app is restarted and the port changes, you need to inspect the port allocated and if it has changed update load balancers/proxy/etc. configs which rely on the port. This creates unnecessary overhead. Making docker keep the same port as before (if possible) removes this overhead.

**Comment by fcrisciani** [comment]
@ceecko keep in mind that with the previous logic is 2 or more containers are restarting the port number assigned to the new instance would be totally non deterministic, so if you don't revalidate the port assigned you will be in trouble because the ports can potentially ends up swapped between containers.

**Comment by ceecko** [comment]
@fcrisciani that makes sense since the port may not be available anymore. We update the configs only in case the port has changed which saves config reloads if it hasn't.

**Comment by ripcurld0** [comment]
@ceecko @fcrisciani 
I think we should say something about it in the [documents](https://docs.docker.com/engine/reference/run/#restart-policies-restart). WDYT?

**Comment by ceecko** [comment]
@ripcurld0 I think it would be beneficial for the others since we've discovered by ourselves that the port may change.

**Comment by ripcurld0** [comment]
calling #dibs 
I will be working on this

**Comment by ceecko** [comment]
@ripcurld0 I think it would make sense to update the behavior of port allocation during restart as well. What do you think?
