### ISSUE TITLE
docker daemon occasionally can not give a quick response for log read request with --since parameter

### ISSUE THREAD

**Issue by haveatry** [moby/moby#31935]
**Description**

When using container logs API to get logs with --since parameter, the client could get a quick response from docker daemon at most of times. However, if the total log size becomes big, it is usually hard to get a quick response from docker daemon. As a result, it occasionally leads to connection down because of no response from daemon for long time. 

I read the source code logic and tried to understand the root cause. Here is the existing code logic.
At first, it builds one logical concatenation ReadSeeker based on all the logs files under the container log path, then it will decode all the log records in sequence, and check whether the log generated time is after the --since parameter. In the end, it will send the log that meets the --since parameter to the client.

I find a workaround to solve this issue, but it needs a little enhancement in the docker daemon code logic.  The workaround is as the following:
1. set --log-opt max-size to a small size, for example, 5m

2. Based on the real need, set --log-opt max-file to one reasonable number.

3. Before building the logic concatenation ReadSeeker, make code change to only select files whose mtime is later than the --since parameter. This could help reduce the range of total log records and let the docker daemon to give a quick response to client.

**Steps to reproduce the issue:**
1.Run a container to generate enough logs, the more, the better. In my test, the total log size is around 400M
2.Using the following command to verify how long to get a response from docker daemon. Please specify a relatively late timestamp to the since parameter. For a extreme case, you could specify a latest timestamp of all the logs to the --since parameter.
date;docker logs --since=xxxxx [container_id] > test.log 2>&1;date

**Describe the results you received:**
It needs a long time to get a docker daemon response using container logs API

**Describe the results you expected:**
I expect to reduce the response time as much as possible.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
v1.9.1

This issue also exists in the latest version of docker.

**Output of `docker info`:**

Containers: 25
Images: 592
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-252:17-2883585-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 15.39 GB
 Data Space Total: 107.4 GB
 Data Space Available: 70.19 GB
 Metadata Space Used: 26.43 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /root/data01/devicemapper/devicemapper/data
 Metadata loop file: /root/data01/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 15.52 GiB
Name: kube-node80
ID: WDUM:UWWH:5XWF:3M37:MQR3:QCDX:NDTY:L5IW:HEJU:6R2H:KI3Y:3UNC
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by fntlnz** [comment]
@haveatry Do you still have the issue with a more recent version?

Also would like to suggest you to take advantage of the journald logging driver (https://docs.docker.com/engine/admin/logging/journald/) which has been introduced since 1.7 if I'm not wrong

**few advantages (a very subsubsub-set)**
- logs life is not determined by container life
- you can filter by *indexes* like container name, id etc..
- it's already in your system

**Comment by haveatry** [comment]
@fntlnz I have not verified this with a more recent version. However, I checked the logic of the latest docker source code. It is the same as v1.9.1. So, I think the behavior would be the same. I could check this in the latest version if it is necessary.

Thanks for your good suggestion. I would consider using journald logging driver in our product.

**Comment by haveatry** [comment]
@fntlnz Here is my code change for the issue.
https://github.com/docker/docker/compare/master...haveatry:31935-fix-slow-response

**Comment by thaJeztah** [comment]
@haveatry feel free to open a pull request to discuss the change

**Comment by haveatry** [comment]
@thaJeztah Thanks for your response, I will send out the pull request as soon as possible

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
