### ISSUE TITLE
docker suddenly stops working in swarm mode due to high memory consumption

### ISSUE THREAD

**Issue by soar** [moby/moby#31942]
**Description**

I have 3 managers in my swarm: `dmgr-01`, `dmgr-02` and `dmgr-03`. I always execute all commands on `dmgr-01` and it was the leader in swarm. But today I've got following output for `docker service ls` command:

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable                         
SIGABRT: abort                                                                               
PC=0x7f7bc6596067 m=0                                                                        
                                                                                             
goroutine 0 [idle]:                                                                          
                                                                                             
goroutine 1 [running]:                                                                       
runtime.systemstack_switch()                                                                 
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420020768 sp=0xc420020760            
runtime.main()                                                                               
        /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200207c0 sp=0xc420020768          
runtime.goexit()                                                                             
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200207c8 sp=0xc4200207c0      
                                                                                             
goroutine 17 [syscall, locked to thread]:                                                    
runtime.goexit()                                                                             
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1                                      
                                                                                             
rax    0x0                                                                                   
rbx    0x7f7bc6907708                                                                        
rcx    0xffffffffffffffff                                                                    
rdx    0x6                                                                                   
rdi    0x3daf                                                                                
rsi    0x3daf                                                                                
rbp    0xc5a91e                                                                              
rsp    0x7ffe234fb208                                                                        
r8     0xa                                                                                   
r9     0x7f7bc6f47740                                                                        
r10    0x8                                                                                   
r11    0x206                                                                                 
r12    0x1bcd050                                                                             
r13    0xf3                                                                                  
r14    0x30                                                                                  
r15    0x3                                                                                   
rip    0x7f7bc6596067                                                                        
rflags 0x206                                                                                 
cs     0x33                                                                                  
fs     0x0                                                                                   
gs     0x0                                                                                   
```

And now in `docker node ls` I see:

```
ID                           HOSTNAME                  STATUS  AVAILABILITY  MANAGER STATUS
50qxe43jjlwltuwzgem8cwwsa *  dmgr-02                   Ready   Active        Leader
hzykzxzh9jmn5mimj02awr42i    dmgr-01                   Ready   Active        Reachable
wiczce0ey8wzr9zaivlyfgm0f    dmgr-03                   Ready   Active        Reachable
```

So `dmgr-01` stops working and drops leadership in swarm. Also my monitoring tells me, that opened ports flapped on that node.

**Additional information:**

I looked through my logs on problem node - and found `out of memory` errors. But you should note, that all my manager nodes have 2 GB of RAM and containers running here consume about 200-300 MB - there are only `nginx` and `consul` processes. In normal state I have `free -m`:

```
             total       used       free     shared    buffers     cached 
Mem:          2010        350       1659          0         19        173 
-/+ buffers/cache:        157       1852                                  
Swap:            0          0          0                                  
```

My cluster has 10 nodes and about 70 docker services. So, I think any `out of memory` errors can be caused only by memory leak in docker engine.

**Output of `docker version`:**

```
Client:                                      
 Version:      17.03.0-ce                    
 API version:  1.26                          
 Go version:   go1.7.5                       
 Git commit:   60ccb22                       
 Built:        Thu Feb 23 10:53:29 2017      
 OS/Arch:      linux/amd64                   
                                             
Server:                                      
 Version:      17.03.0-ce                    
 API version:  1.26 (minimum version 1.12)   
 Go version:   go1.7.5                       
 Git commit:   60ccb22                       
 Built:        Thu Feb 23 10:53:29 2017      
 OS/Arch:      linux/amd64                   
 Experimental: false                         
```

**Output of `docker info`:**

```
Containers: 8                  
 Running: 1                    
 Paused: 0                     
 Stopped: 7                    
Images: 10                     
Server Version: 17.03.0-ce     
Storage Driver: aufs                                             
 Root Dir: /var/lib/docker/aufs                                  
 Backing Filesystem: extfs                                       
 Dirs: 54                                                        
 Dirperm1 Supported: true                                        
Logging Driver: json-file                                        
Cgroup Driver: cgroupfs                                          
Plugins:                                                         
 Volume: local                                                   
 Network: bridge host macvlan null overlay                       
Swarm: active                                                    
 NodeID: hzykzxzh9jmn5mimj02awr42i                               
 Is Manager: true                                                
 ClusterID: hqvohft3etj4ajnkgubbnjwzp                            
 Managers: 3                                                     
 Nodes: 15                                                       
 Orchestration:                                                  
  Task History Retention Limit: 5                                
 Raft:                                                           
  Snapshot Interval: 10000                                       
  Number of Old Snapshots to Retain: 0                           
  Heartbeat Tick: 1                                              
  Election Tick: 3                                               
 Dispatcher:                                                     
  Heartbeat Period: 5 seconds                                    
 CA Configuration:                                               
  Expiry Duration: 3 months                                      
 Node Address: <IP of dmgr-01 here>                                 
 Manager Addresses:                                              
  <IP of dmgr-01 here>:2377                                           
  <IP of dmgr-02 here>:2377                                            
  <IP of dmgr-03 here>:2377                                            
Runtimes: runc                                                   
Default Runtime: runc                                            
Init Binary: docker-init                                         
containerd version: 977c511eda0925a723debdc94d09459af49d082a     
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70           
init version: 949e6fa                                            
Kernel Version: 3.16.0-4-amd64                                   
Operating System: Debian GNU/Linux 8 (jessie)                    
OSType: linux                                                    
Architecture: x86_64                                             
CPUs: 2                                                          
Total Memory: 1.963 GiB                                          
Name: dmgr-01                                                    
ID: VUNH:H6FP:CO4N:O6VB:CFCG:4T32:JQQV:SIS3:UGT7:V2FK:46VS:PRKZ  
Docker Root Dir: /var/lib/docker                                 
Debug Mode (client): false                                       
Debug Mode (server): false                                       
Username: filiatixbot                                            
Registry: https://index.docker.io/v1/                            
WARNING: No memory limit support                                 
WARNING: No swap limit support                                   
WARNING: No kernel memory limit support                          
WARNING: No oom kill disable support                             
WARNING: No cpu cfs quota support                                
WARNING: No cpu cfs period support                               
Experimental: false                                              
Insecure Registries:                                             
 127.0.0.0/8                                                     
Live Restore Enabled: false                                      
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I use virtual server on DigitalOcean.

**Comment by thaJeztah** [comment]
> I looked through my logs on problem node - and found out of memory errors. But you should note, that all my manager nodes have 2 GB of RAM and containers running here consume about 200-300 MB - there are only nginx and consul processes.
> My cluster has 10 nodes and about 70 docker services. So, I think any out of memory errors can be caused only by memory leak in docker engine

You're making quite an assumption there. Let's not jump to conclusions without having tried to understand what happened. Do you have any system and daemon logs of that machine around that time?

> containers running here consume about 200-300 MB

If the managers themselves also run containers, take in to account that when a service is updated, and tasks are re-scheduled, it's possible that more containers are deployed on that manager, and more memory is used. It can be a good choice to set managers to `availability=drain` so that the only thing they do is _manage_ the swarm, and not run containers; to prevent managers running out of resources.

Also take into account that the default `json-logs` logging driver does not automatically rotate or limit log-file size. It's recommended to set the `--max-file` and `--max-size` options to prevent log files growing unlimited; https://docs.docker.com/engine/admin/logging/overview/#json-file

Are all nodes running on the same configuration and distro? From the output of your `docker info`;

```
WARNING: No swap limit support                                   
WARNING: No kernel memory limit support                          
WARNING: No oom kill disable support                             
WARNING: No cpu cfs quota support                                
WARNING: No cpu cfs period support    
```

The first to warnings show that the kernel doesn't support memory limiting. This means that containers running on that machine cannot be limited in the amount of memory they use; as a result, it's possible that (for whatever reason), any container can consume all the available memory of the machine.

Depending on your situation, 2GB can be "ok" to run docker, but managers can require more memory during rescheduling and when making decisions. If during that time more containers were scheduled on that node, it _is_ possible it just ran out of memory because of those extra containers.

Without more details / logs / information, that's very hard to tell.

**Comment by soar** [comment]
> Do you have any system and daemon logs of that machine around that time?

Yes. Here they are: https://gist.github.com/soar/e271dc8368ea23f28aa83dadc06d3410

1. [These](https://gist.github.com/soar/e271dc8368ea23f28aa83dadc06d3410#file-syslog1-log) messages were repeated over 3000 times
2. [This block](https://gist.github.com/soar/e271dc8368ea23f28aa83dadc06d3410#file-syslog3-log) I see twice
3. And [here is](https://gist.github.com/soar/e271dc8368ea23f28aa83dadc06d3410#file-syslog4-log) crash traceback.

> If the managers themselves also run containers, take in to account that when a service is updated, and tasks are re-scheduled, it's possible that more containers are deployed on that manager, and more memory is used.

I know this, but containers running on managers are not restarted very often. Here is `docker ps` from another manager in that cluster (`dmgr-02`):

```
CONTAINER ID        IMAGE                                                                                           COMMAND                  CREATED             STATUS              PORTS                                      NAMES
29757d35f77e        consul:latest                                                                                   "docker-entrypoint..."   12 days ago         Up 12 days                                                     consul
05e431a312d2        hubcompanyname/balancer@sha256:359c8ee7346780195c1599bb47e7523546aa34b7c120c571a0d9d80f0811277e "nginx.sh start"         13 days ago         Up 13 days          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   balancer.50qxe43jjlwltuwzgem8cwwsa.ddkekvv8syp9z3pmvr10xyjfg
```

Another services don't run on managers due to placement constraints.

> Also take into account that the default json-logs logging driver does not automatically rotate or limit log-file size.

Both services running on manager nodes are set up to log to remote GELF server (it is ELK in swarm but on another node):

```
                "LogDriver": {
                    "Name": "gelf",
                    "Options": {
                        "gelf-address": "udp://localhost:12201",
                        "tag": "balancer"
                    }
                },
```

> It's recommended to set the --max-file and --max-size options to prevent log files growing unlimited

Thank you for useful advise!

> Are all nodes running on the same configuration and distro?

Yes, it is Debian Jessie:

```
Linux dmgr-01 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
Linux dmgr-02 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
Is there anything in the logs _before_ that? Those log entries seems to all be _because_ it ran out of memory; interested to find our what _lead_ to it running out of memory.

There's this issue; https://github.com/docker/docker/issues/29282 which can be related to using the GELF driver, if the connection is slow / interrupted

**Comment by soar** [comment]
There is one line just before crash:

```
Mar 20 06:59:18 dmgr-01 dockerd[4882]: time="2017-03-20T06:59:18.404561606Z" level=error msg="Failed to log msg \"<IP-ADDR-HERE> - - [20/Mar/2017:06:59:18 +0000] \\\"OPTIONS /brand/19/api HTTP/1.1\\\" 200 221 \\\"/brands/19/technical\\\" \\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36\\\" \\\"-\\\"\" for logger gelf: gelf: cannot send GELF message: write udp 127.0.0.1:47503->127.0.0.1:12201: write: connection refused"
```

**Comment by thaJeztah** [comment]
Ok, so it looks like GELF was unable to send logs, possibly leading to it buffering messages until it's able to send them.

ping @mariussturm @cpuguy83 any ideas / suggestions?

**Comment by soar** [comment]
Please note, that my logstash (listening for GELF on `localhost:12201`) was restarted at ~00:00 UTC:

```
# docker service ps logstash
ID            NAME            IMAGE                                      NODE                 DESIRED STATE  CURRENT STATE          ERROR                             PORTS
30e7uf2xa1u3  logstash.1      docker.elastic.co/logstash/logstash:5.0.2  dwrk-service-elk-01  Running        Running 12 hours ago                                     
n0wbv7w3wbe8   \_ logstash.1  docker.elastic.co/logstash/logstash:5.0.2  dwrk-service-elk-01  Shutdown       Shutdown 12 hours ago                                    
ktxie624eglu   \_ logstash.1  docker.elastic.co/logstash/logstash:5.0.2  dwrk-service-elk-01  Shutdown       Shutdown 36 hours ago   
```

but docker crashed after ~6 hours after this.

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/docker/docker/issues/8795 ? (although when updating a service, new containers are created, not an existing container restarted); not too familiar with that issue to say anything sensible, so let me leave that to others to say if it's related or not

**Comment by mariussturm** [comment]
The GELF log driver is sending via UDP so it will not buffer anything when the endpoint is down. It's just sending messages out and will forget about it. When you turn it off, is it stable then?

**Comment by mariussturm** [comment]
@soar how many log messages per second are we talking about? Could you also try to disable GELF compression completely?

**Comment by soar** [comment]
@mariussturm 

![image](https://cloud.githubusercontent.com/assets/30570/24102352/54905d7a-0d84-11e7-8feb-5d53d7571c56.png)

![image](https://cloud.githubusercontent.com/assets/30570/24101800/5aa3e38c-0d82-11e7-8693-fb4dd0823e69.png)

**Comment by aluzzardi** [comment]
@thaJeztah Any idea if this is swarm or container runtime related?

**Comment by thaJeztah** [comment]
@aluzzardi not sure; there's the issue I linked above (https://github.com/docker/docker/issues/29282) which relates to compression - I see @mariussturm also mentioned that.

**Comment by ms1111** [comment]
I'm also seeing a leak with 17.03.0-ce on Ubuntu 16.04 in a couple of different swarms. In one swarm, the virtual size of dockerd on one of the workers grows to many tens of gigabytes until the system runs out of memory. (The resident size doesn't grow much - stays under 1 GB.)

In the other swarm, it's the master where dockerd grows.

Both of these swarms only have a single master. I haven't seen the issue in other swarms with multiple masters yet.

I'm using the gelf logging driver for individual containers, but the master doesn't run any containers so gelf isn't involved there.

I've turned on debug mode following the instructions at https://success.docker.com/KBase/How_do_I_enable_%22debug%22_logging_of_the_Docker_daemon%3F. It looks like I can get go pprof working following https://gist.github.com/kolyshkin/bd25e9de97954b330d8a. What should I be looking for?

**Comment by ms1111** [comment]
The swarms where I was seeing this, with 17.03.0-ce and 17.03.1-ce, had a service that was continually restarting due to misconfiguration in the container, with a published ingress port. Removing the service works around the issue.

I'm not sure exactly what was going on - the VmData size of the dockerd process on the master was continually growing, up to 8.2 GB after about 7 hours, on a system with 2 GB RAM and lots of free swap. The VmRSS stayed pretty much constant.

Looking at the pprof MemStats output, Alloc and HeapAlloc were fairly constant and HeapReleased was showing that Go was releasing memory to the OS.

**Comment by soar** [comment]
Today I've faced this problem again. My logstash service have had a problems - and I've restarted it. After this, when GELF-target port became closed, Docker Daemon on all manager nodes started to eat my RAM with speed about 10-15 MB/min. And after this all cluster became unreacheable - overlay network died and containers stopped to answer.

**Comment by cpuguy83** [comment]
@soar Do you have some more detail? Are you running services on your managers? What kind of buffer do you set on the gelf driver?

**Comment by soar** [comment]
@cpuguy83 all information is in my first post of this thread, I kept all versions.

> Are you running services on your managers?

Only `nginx` container, with which I normally have about 1.5 GB of free RAM. And also it doesn't produce too many logs. All log traffic goes between worker nodes.

> What kind of buffer do you set on the gelf driver?

I didn't find any option about buffer here - https://docs.docker.com/engine/admin/logging/overview/#gelf - so I've changed only `gelf-address` setting, all others are default.

**Comment by thaJeztah** [comment]
@soar the default for  "compression-type" is `gzip` but is known to cause high memory consumption and performance issues with high amounts of logging; can you try if setting it to `none` helps for your situation?

Keep in mind that changing the option on the daemon will not change settings for existing containers (the logging options are immutable for running containers)

**Comment by thaJeztah** [comment]
I'm editing the title, because as far as I can see there's no "memory leaking" here, but high memory consumption, which is slightly different :smile:

**Comment by ms1111** [comment]
Ah, there may be separate issues tangled here - the GELF one, as in #29282, which is triggered by GELF buffering; and the one I described above, which is triggered by frequent container restarts within the swarm.

**Comment by soar** [comment]
Maybe I've done something wrong, but when I've changed command to:

```bash
--log-driver=gelf --log-opt "gelf-address"="udp://localhost:12201" --log-opt "tag"="mock" --log-opt "gelf-compression-type"="none"
```

It doesn't work at all now, I don't see anything in my ELK.

**Comment by polinchw** [comment]
I've seen this same error scaling a docker swarm up then down.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
