### ISSUE TITLE
Executing `pstack` in host to inspect docker container's process will always kill contrainer's process 

### ISSUE THREAD

**Issue by backyes** [moby/moby#31945]
What's the  reason about killing contrainer process instead of showing pstack output.  And, what's the best way to do pstack for container process. 

Thanks.

**Comment by thaJeztah** [comment]
I'm not able to reproduce

```
ps auxf

[...]
root      6369  0.0  0.2 150660  4664 ?        Sl   12:59   0:00      \_ docker-containerd-shim 850940fad8c0780d4ec567399f17f930ca6dd59720a2c061ce73c14df723e878 /var/run/docker/libcontainerd/850940fad8c0780d4ec567399f17f930ca6dd59720a2c061ce73c14df723e878 docker-runc
root      6415  0.0  0.2  31872  4660 ?        Ss   12:59   0:00          \_ nginx: master process nginx -g daemon off;
syslog    6436  0.0  0.1  32260  3112 ?        S    12:59   0:00              \_ nginx: worker process
```

```bash
$ pstack 6415

6415: nginx: master process nginx -g daemon off;
(No symbols found)
crawl: Input/output error
Error tracing through process 6415
0x7fb25cafd3a6: ????

$ pstack 6436

6436: nginx: worker process
(No symbols found)
0x7fb25cbb0be3: ????

$ ps auxf

[..]
root      6369  0.0  0.2 150660  4664 ?        Sl   12:59   0:00      \_ docker-containerd-shim 850940fad8c0780d4ec567399f17f930ca6dd59720a2c061ce73c14df723e878 /var/run/docker/libcontainerd/850940fad8c0780d4ec567399f17f930ca6dd59720a2c061ce73c14df723e878 docker-runc
root      6415  0.0  0.2  31872  4660 ?        Ss   12:59   0:00          \_ nginx: master process nginx -g daemon off;
syslog    6436  0.0  0.1  32260  3112 ?        S    12:59   0:00              \_ nginx: worker process
```

Can you;

- add the information that was requested in the issue template when you opened this issue? (output of `docker version`, output of `docker info`
- show the exact steps to reproduce

> And, what's the best way to do pstack for container process.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
