### ISSUE TITLE
slow response from docker daemon for log request with --tail parameter for jsonfile log driver

### ISSUE THREAD

**Issue by haveatry** [moby/moby#31968]
**Description**

When executing the docker logs command with a little bigger --tail parameter, for example, 100000,  it will need around 2 minutes to get the whole response result in my test environment. The following is my test result.

[root@kube-node80 ~]# date;docker logs -t=true --tail=100000 ab8e412c37eb5d  > test.log 2>&1;date
Fri Mar 17 17:32:30 CST 2017
Fri Mar 17 17:34:23 CST 2017

I checked the code logic, this could be improved by enlarged the blockSize in the following link. Currently, it is hard coded as 1024. I tried with 10240 and 32768, and made the same test. I listed all the test results here, we could find that the same request consumed much less time as its value is enlarged.
So could we enlarge the blockSize, or let it configurable?
https://sourcegraph.com/github.com/docker/docker@58ccdfe00c4e47f1f1d3aabff40189c3aea64b65/-/blob/pkg/tailfile/tailfile.go#L12:7-12:16

-----------------------------------------------------------------------------------------------------------------
blockSize=1k
[root@kube-node80 ~]# date;docker logs -t=true --tail=100000 ab8e412c37eb5d  > test.log 2>&1;date
Fri Mar 17 17:32:30 CST 2017
Fri Mar 17 17:34:23 CST 2017

-------------------------------------------------------------------------------------------------------------------
blockSize=10k
[root@kube-node80 ~]# date;docker logs -t=true --tail=100000 c76b9481028cdf0b  > test.log 2>&1;date
Fri Mar 17 17:53:07 CST 2017
Fri Mar 17 17:53:19 CST 2017

------------------------------------------------------------------------------------------------------------------
blockSize=32K
[root@kube-node80 ~]# date;docker logs -t=true --tail=100000 3e82f16be274443b  > test.log 2>&1;date
Fri Mar 17 18:07:40 CST 2017
Fri Mar 17 18:07:45 CST 2017
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
v1.9.1
This issue should also exist in the latest version of docker.

**Output of `docker info`:**
Containers: 25
Images: 592
Server Version: 1.9.1
Storage Driver: devicemapper
Pool Name: docker-252:17-2883585-pool
Pool Blocksize: 65.54 kB
Base Device Size: 107.4 GB
Backing Filesystem:
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 15.39 GB
Data Space Total: 107.4 GB
Data Space Available: 70.19 GB
Metadata Space Used: 26.43 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.121 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /root/data01/devicemapper/devicemapper/data
Metadata loop file: /root/data01/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 15.52 GiB
Name: kube-node80
ID: WDUM:UWWH:5XWF:3M37:MQR3:QCDX:NDTY:L5IW:HEJU:6R2H:KI3Y:3UNC
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @LK4D4 @cpuguy83

**Comment by cpuguy83** [comment]
Even with a larger block size, holding 100000 loglines in memory is not ideal.
What's the use case for this?

**Comment by shaynewang** [comment]
I believe https://github.com/docker/docker/pull/28203 fixes this problem

**Comment by thaJeztah** [comment]
@haveatry can you try if this is resolved by https://github.com/docker/docker/pull/28203 (which is part of the current 17.03 release?)

**Comment by haveatry** [comment]
@thaJeztah @shaynewang I will have a try to verify this. Even if this is resolved by #28203, it could also be enhanced by enlarging the blockSize or by doubling the buffer size as @shaynewang has described as the following Step#5. I find that #28203 does not really doubling the size of of the buffer, it only increases the buffer size by one blockSize for each read. Could you please share your idea on this?

- How I did it
0. if the filesize is smaller than the buffer then load the whole file into memory goto 6
1.Changed the reading the last n lines algorithm to:
2.seek the starting position for a buffer size block from EOF
3.count the number of "\n"'s
4.if number of eol is larger than n then return
**5.if not then double the size of the buffer then go back to 1.**
6.take the last n line of buffered file and return

**Comment by shaynewang** [comment]
@haveatry the commit message was from the first commit of that PR. Later I realized the slow read due to reading EOF at each read into the buffer. As the log file could be written at the time of reading so constantly looking for EOF may not be what we want. Please let us know if the patch had solved your problem. And you are always welcome to submit a PR for the enhancement. :)

**Comment by haveatry** [comment]
@shaynewang I verified with your fix today, it did not solve my problem. I submitted one PR(#32229) to fix this issue.

**Comment by cpuguy83** [comment]
This at least should be much more efficient now.
We still have a 1024 byte block size, but reading is much more efficient and we are no longer storing tailed log messages in memory (they are streamed along with the live stream).
I do not think we want to make the block sizes configurable as this can very easily end up causing an OOM in the daemon.

Additionally there is a new logger added, the "local" logger which does not need to worry about block sizes since the message delineation is much more clear and requires very little actual parsing.
This should allow you to choose any number of messages to tail without incurring any extra overhead.

These should both be available in the docker 18.09 release.
Closing this now. Thanks! 👼 🙇

**Comment by cpuguy83** [comment]
Referenced changes are here: https://github.com/moby/moby/pull/37092
