### ISSUE TITLE
docker logs -f <containerID> fails when container rotates log file

### ISSUE THREAD

**Issue by paddie** [moby/moby#32038]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Using `docker logs -f <containerID>` to follow the output logs of a container seems to stop after a while, and sooner if the `--log-opt max-size` is set to a low value. What we've seen in live production systems, is that only the first log-file is properly followed, but the second it rotates, the `docker logs -f` command stops tracking the file. Maybe a fsnotify is not being triggered correctly?

**Steps to reproduce the issue:**
1. execute the following command to execute a docker container with a small max-size:
    ```bash
    docker run -d --log-driver=json-file --log-opt max-size=1k alpine /bin/ash -c 'while true; do echo "hit CTRL+C to exit"; sleep 1; done'
    ```
2. Follow the container logs using the follow command:

    ```
    docker logs -f <containerID>
    ```

**Describe the results you received:**
The log output stops after around 10-12 lines and never pick up again, even though the container keeps echoing.

**Describe the results you expected:**
The logs should either keep going or stop (and close the stream) after the json-file was rotated.

**Additional information you deem important (e.g. issue happens only occasionally):**

This has been observed on both Docker 1.12.6 in Amazon ECS and locally running the version described below using `docker version/info`.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 101
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: TP72:QUAN:KOBL:NK7N:LTOZ:6NRW:NQPN:GH7K:HZD6:QDDE:GSZJ:GSQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-03-23T13:07:49.418835015Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: trustpilotdockerhub
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
`Docker for Mac` and `AWS ECS`

**Comment by cpuguy83** [comment]
Seems to be related to when there is no retention of the log.

If you set `--log-opt max-file=2` the problem doesn't occur.

**Comment by paddie** [comment]
So, is this an issue, or is this simply something that is expected? It seems unexpected that is just suddenly stops without either throwing an error or closing the channel.

We are using the docker logs API through the Go api to gather the logs of containers in a way the current logging drivers don't allow us to. So, while this is a problem with the cli, it's something we are experiencing at the api level as well.

Interestingly, after reviewing the production settings on ECS on docker 1.12.6, we are setting the `--log-opt max-file=2` attribute, so at least for 1.12.6 it doesn't seem to have any effect.

**Comment by cpuguy83** [comment]
@paddie 1.12.6 has broken behavior in general that is fixed in 1.13 (https://github.com/docker/docker/commit/84e60a7e10278e3acd2b783d0e6955dc5198b57c).

I'd say the issue you are seeing is a bug, but is a bit of an edge case since it's weird to not retain some of the logs.

**Comment by paddie** [comment]
@cpuguy83 for the 1.12.6 issue, is there an approach you could recommend to work around the issue? Maybe time-out after a bit of in-activity on the io.Reader?

**Comment by paddie** [comment]
@cpuguy83 I agree though, so I'm assuming that if you don't specify the max-file it defaults to 0? Is that a sensible default?

**Comment by paddie** [comment]
@cpuguy83 I've talked with our guys, and we'll attempt to bump docker to 1.13.x soonish to get around this. Thank you for your time!

**Comment by cpuguy83** [comment]
@paddie Please use 17.03 which is a continuation of the 1.13.x line just with the new versioning scheme.

**Comment by wedneyyuri** [comment]
@cpuguy83 We are using docker 1.12.6 inside Elastic Beanstalk (Single Container Docker), using a greater value in `max-size` and `max-file=2` will work around the issue?

**Comment by cpuguy83** [comment]
@wedneyyuri No idea.
1.12 does have some other issues with rotations.

**Comment by wedneyyuri** [comment]
@cpuguy83 Thanks, looks like `tail -f /var/lib/docker/containers/<containerId>/<containerId>-json.log` is the best work around for now.

**Comment by hunterchris** [comment]
@wedneyyuri that will not fix the issue. I have the same setup and I'm hitting similar problems; setting `max-size` and `max-files` is not properly rotating the `/var/lib/docker/containers/<container_id>/<container_id>-json.log`

**Comment by wedneyyuri** [comment]
Hi @hunterchris, maybe it's a docker version issue. It's working for us in production.

**Comment by wedneyyuri** [comment]
It's ugly but temporarily solved our problem, also a filebeat service is running in our machines to capture logs from `/var/log/custom-application/current/*.log`

You can check our gist here: https://gist.github.com/wedneyyuri/9020e18b3cc79115420bd61cfa7a994a

**Comment by paddie** [comment]
I'm closing this one again since we've not seen the issue in some time.

**Comment by nelsonfassis** [comment]
I have this issue on 17.03-2 but not consistently. Some container logs grows indefinitely ignoring rotation. Right now, I have the 10mb max-size and 5 max-file on my /etc/docker/daemon.json and one of my containers have a log file of 20GB (and growing.)

**Comment by cpuguy83** [comment]
@nelsonfassis `/etc/docker/daemon.json` sets the default logging options, but does not affect already existing containers.

**Comment by nelsonfassis** [comment]
@cpuguy83 I know, but I use Kubernetes and deleted pods to confirm, still don't work.
Setting the rotation on the ExecStart did the trick, but as I didn't notice the issue before, I had logs growing up to 30gb and crashing nodes. 
/etc/docker/daemon.json worked to change my logs that were as journalctl before to json, but the rotation was completely ignored. I would say it is a bug but I already 'fixed' my cluster and can't provide much more information to open a bug.
