### ISSUE TITLE
Swarm internal service discovery with ports

### ISSUE THREAD

**Issue by oleg-filiutsich** [moby/moby#32039]
**Description**

**Steps to reproduce the issue:**
1. Create swarm in swarm mode
2.  in swarm master:
```
$ docker network create \
  --driver overlay \
  --subnet 10.0.9.0/24 \
  --opt encrypted \
  my-network

$ docker service create \
  --replicas 3 \
  --name my-web \
  --network my-network \
  nginx

$ docker service create \
  --name my-busybox \
  --network my-network \
  busybox \
  sleep 3000

$ docker exec -it my-busybox.1.1dok2cmx2mln5hbqve8ilnair /bin/sh
$ nslookup my-web
# good
$ telnet my-web 443
# error
$ telnet my-web 80
# error
```

3.

**Describe the results you received:**
Error in requests to ports 80 and 443

**Describe the results you expected:**
The service have some no 80 ports.
I want have connect from swarm (internal swarl overlay network) to swarm service dns name (or Vip IP) and custom port (not from swarm manager IP).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Server Version: 1.13.1                                                                                                                                                     [22/173]
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: m1tu28hojg477cr9qewf0k84j
 Is Manager: true
 ClusterID: o0ae4l3rq1d8kvt8kgmvsr0zm
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.1.1.70
 Manager Addresses:
  10.1.1.70:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: mm-swarm-master
ID: XCOF:TC6Q:JIB2:VFGF:NXFY:WP4K:JHZC:3AN5:52YO:HAQI:N7O5:BQ6A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 registry.moneyman.ru:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by oleg-filiutsich** [comment]
I found in docker swarm mode docs 
```
Use swarm mode service discovery

By default, when you create a service attached to a network, the swarm assigns the service a VIP. The VIP maps to a DNS alias based upon the service name. Containers on the network share DNS mappings for the service via gossip so any container on the network can access the service via its service name.

You don’t need to expose service-specific ports to make the service available to other services on the same overlay network. The swarm’s internal load balancer automatically distributes requests to the service VIP among the active tasks.
```
If my docker service have 2 or more exposed ports then how to connect to specific port via Vip IP?

**Comment by cpuguy83** [comment]
@oleg-filiutsich I suspect the issue is with the encrypted option you have set, this has other networking requirements.

Specifically IP protocol 50 must be open on your firewall to allow ESP traffic.
Note this is protocol 50, but TCP/UDP port 50.
You may also need UDP port 500.

**Comment by Gelio** [comment]
I have a similar problem with _nginx_ and _php:fpm_ containers running inside a Docker Swarm. I use nginx's _fastcgi_pass_ to handle PHP:
```
    location ~ [^/]\.php(/|$) {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass app-phpfpm:9000;
    }
```

_app-phpfpm_ is my PHP service name (from _docker-compose.yml_). Often when deploying a swarm the nginx container will fall into an endless loop of restarting due to:
```
2017/03/23 14:08:58 [emerg] 1#1: host not found in upstream "app-phpfpm" in /etc/nginx/conf.d/default.conf:17 nginx: [emerg] host not found in upstream "app-phpfpm" in /etc/nginx/conf.d/default.conf:17
```
I then need to remove the stack and redeploy it a few times before it starts working properly.

I've noticed, that sometimes swarm's service names are not "registered" as valid hostnames inside containers. When doing `docker inspect gbc_app-phpfpm` there clearly is an alias for `app-phpfpm`, so it should work, but it does not, unfortunately.

I didn't specify network explicitly, the default one created by docker swarm is used.

I believe your problem is related to mine, so I thought I would share my experiences.

**Comment by cpuguy83** [comment]
@Gelio These are not related. The original poster is having issues with traffic flowing across the network, you are having DNS related issues. Can you open a new issue with exact repro steps?

Thanks!

**Comment by thaJeztah** [comment]
Does it work if you don't specify the "encrypted" option and subnet when creating the overlay network?

Also note that the default nginx configuration is not using port 443, only port 80

**Comment by thaJeztah** [comment]
ugh; sorry for the double post; the comments above didn't show yet for me :blush:

**Comment by oleg-filiutsich** [comment]
I try again with jenkins alpine image for test on port 8080.
All work fine in encrypted and no encrypted network.
```
$ docker network rm my-network

$ docker network create \
  --driver overlay \
  --opt encrypted \
  my-network

# EXPOSE ports 8080 50000
$ docker service create \
  --name jenkins \
  --network my-network \
  jenkins:alpine

$ docker service create \
  --name my-busybox \
  --network my-network \
  busybox \
  sleep 30000

$ docker exec -it my-busybox.<id> sh
$ nslookup jenkins
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      jenkins
Address 1: 10.0.2.2
$ wget -O- http://jenkins:8080/login?from=%2F
<got content>

$ telnet jenkins 8080
Connection closed by foreign host
# Just for test
$ telnet jenkins 8084
telnet: can't connect to remote host (10.0.2.2): Connection refused

````

**Comment by oleg-filiutsich** [comment]
@Gelio 
I found interesting feature.
I run docker service web-app in overlay net
I run busybox docker service in the net.
I connected to busybox and run 'ping web-app' all works fine. (I not stop check ping)
Then I kill web-app service pings still working fine o_0, but web-service not working.

**Comment by cpuguy83** [comment]
@oleg-filiutsich How are you killing the webapp service?

**Comment by oleg-filiutsich** [comment]
Yes.
docker service rm web-app

**Comment by cpuguy83** [comment]
@oleg-filiutsich Is this on the same system reported above or on a dev machine (like docker4mac)?

Ping @sanimej 
I'm not sure what happens to the VIP when the service is removed.
Since `ping` only resolves once you'd still be hitting the same VIP I believe.

**Comment by oleg-filiutsich** [comment]
@cpuguy83 It's runed on ubuntu 16 os.

**Comment by oleg-filiutsich** [comment]
@cpuguy83 It's runed on ubuntu 16 os.
