### ISSUE TITLE
Container working just through direct IP instead of hostname in Linux

### ISSUE THREAD

**Issue by victorpavlenko** [moby/moby#32050]
**Description**
Site in container works normally. But through IP. Not through hostname.

**Steps to reproduce the issue:**
1. Create working container.
2. Check that it;s working through IP.
3. Add string "127.0.0.1 hostname" in hosts.
4. Check that "ping hostname" working normally.
5. Check that hostname in any browser not working. Even after reboot. Even when hosts files contains identically strings in container and docker host.

**Describe the results you received:**
hostname not working in browsers. But everything's works through IP.

**Describe the results you expected:**
Everything's works through hostname in browsers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-41-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796 GiB
Name: pc-linux
ID: PBV5:TOE6:2O5T:C7YG:GONP:SPSK:IVK2:YYGP:AEN3:HAYT:VOUK:QK7A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've checked troubleshoot for linux. Everything's OK.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
