### ISSUE TITLE
The trustKeyPath used to store key.json file should be configurable

### ISSUE THREAD

**Issue by rogaha** [moby/moby#32135]
**Description**
The `trustKeyPath` (https://github.com/docker/docker/blob/bbce24997c7a31454edd1d3d979823582bcdd95d/daemon/config/config.go) should be configurable and ideally in stored by default in `/var/lib/docker` (`/etc/docker` might be read-only).  Currently it's using the `hardcoded` path located in https://github.com/vdemeester/docker/blob/46ec4c1ae2700ed638072fd7fb326afc10eded20/cmd/dockerd/daemon_unix.go#L47-L47.

/cc @thaJeztah @justincormack

**Comment by rogaha** [comment]
it's worth mentioning that there is no documentation for it at all.

**Comment by thaJeztah** [comment]
I've been looking at the key.json, and was actually wondering if we need it at all; IIRC; other than showing an `ID` in the output of `docker info`, is it used anywhere else? (had a todo for myself to remove it)

ping @dmcgowan, who knows most about libtrust

**Comment by rogaha** [comment]
thanks @vdemeester for your help on tracking this issue down. @thaJeztah it would be great if we could rely on that engine `ID`, it would prevent us from having to handle it by ourselves. It helps us to keep track of the `engines` within a `swarm cluster`.

**Comment by thaJeztah** [comment]
Hm, i'm not sure this is the actual ID that's used in Swarm mode though - IIRC, the ID in docker info is just a leftover from the intention to use libtrust for authenticating a client/daemon connection. SwarmKit uses a different cryptographic identity afaik

**Comment by rogaha** [comment]
@thaJeztah I would prefer to avoid `swarm` specific IDs as we can have engines that are not part of a swarm.

**Comment by dmcgowan** [comment]
@thaJeztah agreed we don't need this key file anymore. If we still need it for `ID` compatibility we could migrate the file to the graph directory but just store the `ID` in a file rather than the whole key. If we are not using the key for signing anything then it is pointless. As part of that a different way for generating new IDs could be added. I believe from previous discussions, we still need an ID generation apart from the swarm ID allocation.

**Comment by rogaha** [comment]
@dmcgowan I think it would be very helpful to have such `ID` handled by the `engine` it self. Even if it's not used to `sign` images, do you think you can modify it to store only the `ID` in the `graph` directory?

**Comment by thaJeztah** [comment]
@rogaha would you expect the ID to be preserved if someone "wipes" `/var/lib/docker`, or to be re-generated? (alternatively, storing in `/etc/docker` could be an option)

**Comment by rogaha** [comment]
@thaJeztah I would expect the `ID` to be regenerated if the `/var/lib/docker` is wiped out.
