### ISSUE TITLE
Direct LVM consumes 3-4 times more space than overlay?

### ISSUE THREAD

**Issue by carlpett** [moby/moby#32141]
**Description**
We have been having issues with `overlay` on a few machines, where it would not properly clean up after containers exited. Today, we thought we'd try switching to Direct LVM instead and see if that works better for us (we have a fair bit of container churn, so according to the docs lvm would be better).

Previously we've been running a dedicated xfs partition of 100G mounted on /var/lib/docker, which has typically lasted two-three weeks before the filesystem leak fills it up enough that we need to manually clear it.

After setting up thinpool according to the docs, with a 100G lv for data and 5G for metadata, we started docker. The partition filled up before we'd even started all the containers that we're running previous to the operation. After some thinking, we shrunk the block size from 512K (what is recommended in the docs) to 64K (the default). That allowed us to at least start everything. But now, about 1,5 hours later, we're almost at 100G usage again. I've increased the LV to 200G as a precaution, but it seems clear that the disk usage is vastly higher than on overlayfs.

**Additional information you deem important (e.g. issue happens only occasionally):**
systemd unit excerpt:
`ExecStart=/usr/bin/dockerd --storage-driver devicemapper --storage-opt dm.thinpooldev=/dev/mapper/vgsys-lv_docker_data --storage-opt dm.use_deferred_removal=true --log-level=warn --icc=false --dns 10.36.22.4`

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 337
 Running: 79
 Paused: 0
 Stopped: 258
Images: 192
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vgsys-lv_docker_data
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 91.55 GB
 Data Space Total: 214.7 GB
 Data Space Available: 123.2 GB
 Metadata Space Used: 90.98 MB
 Metadata Space Total: 5.369 GB
 Metadata Space Available: 5.278 GB
 Thin Pool Minimum Free Space: 21.47 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.6 GiB
Name: <hostname>
ID: EN6G:CCWK:HULE:U6BP:HYZG:PDAL:COLB:72VA:OHHB:N57P:PWCA:4ZDQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical node

**Comment by cpuguy83** [comment]
Switching drivers here isn't going to make rm errors go away.

It would be better to get to the bottom of why you are seeing errors on removal leading to dirs not being cleaned up.

You mention you were using `overlay`. Are you sure this is out of space vs out of inodes?

**Comment by carlpett** [comment]
Yes, a proper solution to that problem would of course be better. However, I think that would be better resolved in a separate issue, I think this issue should be treated on its own. We've switched back to overlay so that we don't run out of disk over the night, so I'll collect some data and report a new issue about that tomorrow.

**Comment by rhvgoyal** [comment]
Right. Figuring out why container removal fails and fixing that is the way to go.

**Comment by carlpett** [comment]
Was away all this week, but I'll be checking on the overlay stuff next week. But regarding LVM - is it expected that it would require so much more space? It does seem to make it less suitable for just about anything at larger scale, costwise?

**Comment by rhvgoyal** [comment]
when you say space, you mean space on disk?

I think that lvm might be more space efficient (especially when block size is small say 64K). Reason being that devicemapper implements COW in terms of blocks while overlay implements it at file level. So if there are significant number of files which are bigger than 64K and a single page is being written, overlay will copy up whole file while devicemapper will unshare one block.

So I will be surprised to know that in terms of disk space usage, lvm is less efficient.

**Comment by carlpett** [comment]
Yes. The recommended setting in the documentation is 512K. After filling 100G _very_ quickly, we changed to 64K (the minimum, and the default), and we got a bit further.

But yes, 100G overlay storage seems about 3-4x "more efficient" than 100G of LVM, as measured in the number of images we could pull.

**Comment by rom-stratoscale** [comment]
Any update on this one? What is strange is well in devicemapper behavior, is once I run docker inspect -s CONTAINER / docker ps -s - lvm keep on growing and will not reduce. Any explanation for that?

**Comment by cpuguy83** [comment]
@rom-stratoscale Sounds like your containers are writing to disk.

**Comment by rom-stratoscale** [comment]
@cpuguy83 nope. The most i/o intensive container wrote 350K :) All the rest write top 3K. 
All the containers are api services that works with DB, and even the logs they write to host mounted directory.

**Comment by cpuguy83** [comment]
@rom-stratoscale  How are you verifying this? If size is increasing on `docker ps -s`, then the rw layer in the container is being written to.

**Comment by cpuguy83** [comment]
btw, `docker ps -s` walks the file tree of the container to calculate the size.

**Comment by rom-stratoscale** [comment]
@cpuguy83 I used few methods (I believe that lead to the same behaviour)
1. docker ps -s
2. docker inspect -s CONTAINER-NAME  | grep SizeRw"
3. docker commit CONTAINER-NAME; docker history CONTAINER-NAME

**Comment by rom-stratoscale** [comment]
@cpuguy83 any idea what am I missing?

**Comment by cpuguy83** [comment]
@rom-stratoscale As I said, if the size being reported is increasing, then something is writing to disk in the container.

**Comment by rom-stratoscale** [comment]
@cpuguy83 the size which is increasing is the one which is reported by 'docker info' or 'lvs'
docker ps -s is constant

**Comment by cpuguy83** [comment]
@rom-stratoscale Can you post the output of `docker info`?

**Comment by rom-stratoscale** [comment]
@cpuguy83 sure. Thanks for your help

[root@stratonode_c1n0 ~]# docker info
Containers: 22
 Running: 6
 Paused: 0
 Stopped: 16
Images: 41
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: inaugurator-docker_thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 23.41 GB
 Data Space Total: 26.84 GB
 Data Space Available: 3.43 GB
 Metadata Space Used: 12.15 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.062 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.31 GiB
Name: stratonode_c1n0.node.strato
ID: A7OF:UHVX:WJ2Q:AVJ3:Z6VE:OTTC:XV2W:CVL6:4IQL:7PE7:F55N:MWVX

**Comment by cpuguy83** [comment]
@rom-stratoscale It's pretty hard to debug with such an old version of Docker.
Is the rest of your system up to date?
What is in `docker ps -a` and `docker images -a`?

**Comment by rom-stratoscale** [comment]
@cpuguy83 

[root@stratonode_c1n0 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                                                        COMMAND                  CREATED             STATUS                     PORTS               NAMES
2f30b2a01451        docker-registry.service.strato:1818/staging/maestro-data-reporter:fc1ce3c62415b1b36996dee0b9b109888b4e5892   "data-reporter"          2 days ago          Created                                        maestro-data-reporter.service.strato
848ffbaeefea        docker-registry.service.strato:1818/staging/maestro-tunnel-client:fc1ce3c62415b1b36996dee0b9b109888b4e5892   "tunnel-client"          2 days ago          Exited (2) 2 days ago                          maestro-tunnel-client.service.strato
2e9ebe202aa0        docker-registry.service.strato:1818/staging/quotas-manager:abe334e2f428b9315e22a8426755595c7bcfa29d          "quotas-manager"         3 days ago          Exited (137) 3 days ago                        quotas-manager.service.strato
d690fcbd43f0        docker-registry.service.strato:1818/staging/flower:f2e8f7ee4ad7aa03743edd4920bfe84d7a0abcee                  "flower --broker=pyam"   3 days ago          Exited (0) 3 days ago                          flower.service.strato
739398ade3b4        docker-registry.service.strato:1818/staging/credit-manager:81d8c2b55eff6648d89fc8ec018d4a9d5f4e52ef          "main"                   3 days ago          Exited (2) 3 days ago                          credit-manager.service.strato
fd8c18ea5f54        docker-registry.service.strato:1818/staging/conversions:94e06969e778a3e4aabf2f6bf2e3ad0fbae8f207             "uwsgi --yaml /etc/st"   3 days ago          Exited (137) 3 days ago                        conversions.service.strato
9a8521918358        docker-registry.service.strato:1818/staging/nginx:137c54e092b83f2f0cceb5fdc0fcdfbbf7c5ab39                   "/bin/sh -c 'nginx -g"   3 days ago          Up 3 days                                      nginx.service.strato
4674957b027f        nate/dockviz                                                                                                 "/dockviz images -t"     2 weeks ago         Created                                        furious_bell
e3ad0ea3aee5        nate/dockviz                                                                                                 "/dockviz images --do"   2 weeks ago         Exited (0) 2 weeks ago                         mad_swartz
c110395cae6d        docker-registry.service.strato:1818/staging/servicesgw:c4fcbf4f95c666059b94718f944f9abd84e2a8ec              "/bin/sh -c /usr/bin/"   2 weeks ago         Up 2 weeks                                     servicesgw.service.strato
c56fafbfdcb1        docker-registry.service.strato:1818/staging/ec2-manager:9968db38cd7e040536486de2dc591c0ad30fc88c             "/bin/sh -c 'exec ec2"   2 weeks ago         Exited (137) 2 weeks ago                       ec2-manager.service.strato
0596b5565f13        docker-registry.service.strato:1818/staging/ec2-api:1b9fe69b137545a3740edf2dcb5bbe27333cccdd                 "/bin/sh -c /docker-e"   2 weeks ago         Exited (137) 2 weeks ago                       ec2-api.service.strato
2704a1196bc6        docker-registry.service.strato:1818/staging/redis:7ac9cb34877b8ae690b3d2c7a6fd360538f5e432                   "redis-server /etc/re"   2 weeks ago         Up 2 weeks                                     redis.service.strato
70b83fa22559        docker-registry.service.strato:1818/staging/vms-monitor:99ada8239983cada44449958197b2a56dd64b5c7             "/bin/sh -c /usr/bin/"   2 weeks ago         Exited (137) 2 weeks ago                       vms-monitor.service.strato
180bef9704e2        docker-registry.service.strato:1818/staging/gcm:a56d169a2ef8e3e86df26c9491a7317182c1282e                     "/bin/sh -c 'salt-mas"   2 weeks ago         Exited (0) 2 weeks ago                         gcm.service.strato
982ca1a81879        docker-registry.service.strato:1818/staging/dbs-manager:f0827d60c89943880e1c45009ae1778048994a7a             "/entrypoint.py"         2 weeks ago         Exited (137) 2 weeks ago                       dbs-manager.service.strato
341848c00136        docker-registry.service.strato:1818/staging/vm-manager:960aec5ecdc5c06582ea67a05422ccb2f9acc416              "uwsgi --yaml /usr/sh"   2 weeks ago         Exited (137) 2 weeks ago                       vm-manager.service.strato
cfc8d770e9d2        docker-registry.service.strato:1818/staging/mancala-copyservice:5f47f6d74631e820e558369b9d1bd325da0da913     "/bin/sh -c /usr/bin/"   2 weeks ago         Exited (137) 2 weeks ago                       mancala-copyservice.service.strato
f95d8c4af01b        docker-registry.service.strato:1818/staging/identity-manager:ec29a6a1c6a8679035098c12420a25b1bb9c9cd2        "uwsgi --yaml /usr/sh"   2 weeks ago         Exited (137) 2 weeks ago                       identity-manager.service.strato
006fbdd68c9a        docker-registry.service.strato:1818/staging/events-agent:5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a            "python /usr/lib/pyth"   2 weeks ago         Up 2 weeks                                     events-agent.service.strato
4e050094a847        docker-registry.service.strato:1818/staging/nodedapi:afc63de2d188141b5e21ca03e493fe4abb42b98b                "/usr/bin/uwsgi --gev"   2 weeks ago         Up 2 weeks                                     nodedapi.service.strato
595cf9af04a1        docker-registry.service.strato:1818/staging/configurator:f7af12b8272b0b746b7958b696e66ff8de8864e3            "/bin/sh -c 'exec con"   2 weeks ago         Up 2 weeks                                     configurator.service.strato
[


[root@stratonode_c1n0 ~]# docker images -a
REPOSITORY                                                            TAG                                        IMAGE ID            CREATED             SIZE
rackattack-nas.dc1:5000/maestro/events-reporter                       55785bd                                    206bc748218f        2 weeks ago         24.18 MB
rackattack-nas.dc1:5000/maestro/events-reporter                       0f9be75                                    96627146e9ea        2 weeks ago         24.18 MB
docker-registry.service.strato:1818/staging/gcm                       a56d169a2ef8e3e86df26c9491a7317182c1282e   0e73a71aebf8        3 weeks ago         916.9 MB
rackattack-nas.dc1:5000/staging/gcm                                   a56d169a2ef8e3e86df26c9491a7317182c1282e   0e73a71aebf8        3 weeks ago         916.9 MB
docker-registry.service.strato:1818/staging/conversions               94e06969e778a3e4aabf2f6bf2e3ad0fbae8f207   c252e377418b        3 weeks ago         1.32 GB
rackattack-nas.dc1:5000/staging/conversions                           94e06969e778a3e4aabf2f6bf2e3ad0fbae8f207   c252e377418b        3 weeks ago         1.32 GB
docker-registry.service.strato:1818/staging/kubernetes-manager        ece4b9ee9ea65a9e4b86f51bb399ebce2433bc56   a7a961683013        3 weeks ago         847.5 MB
rackattack-nas.dc1:5000/staging/kubernetes-manager                    ece4b9ee9ea65a9e4b86f51bb399ebce2433bc56   a7a961683013        3 weeks ago         847.5 MB
docker-registry.service.strato:1818/staging/identity-manager          ec29a6a1c6a8679035098c12420a25b1bb9c9cd2   d350edc75747        3 weeks ago         898.8 MB
rackattack-nas.dc1:5000/staging/identity-manager                      ec29a6a1c6a8679035098c12420a25b1bb9c9cd2   d350edc75747        3 weeks ago         898.8 MB
docker-registry.service.strato:1818/staging/dbs-manager               f0827d60c89943880e1c45009ae1778048994a7a   4b6223c74196        3 weeks ago         851.2 MB
rackattack-nas.dc1:5000/staging/dbs-manager                           f0827d60c89943880e1c45009ae1778048994a7a   4b6223c74196        3 weeks ago         851.2 MB
docker-registry.service.strato:1818/staging/events-agent              5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   4dffdffc3a36        3 weeks ago         829.9 MB
rackattack-nas.dc1:5000/staging/events-agent                          5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   4dffdffc3a36        3 weeks ago         829.9 MB
docker-registry.service.strato:1818/staging/alarms-engine             5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   f95093531fac        3 weeks ago         983.3 MB
rackattack-nas.dc1:5000/staging/alarms-engine                         5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   f95093531fac        3 weeks ago         983.3 MB
docker-registry.service.strato:1818/staging/alarms-service            5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   a1f16d54560d        3 weeks ago         970.4 MB
rackattack-nas.dc1:5000/staging/alarms-service                        5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   a1f16d54560d        3 weeks ago         970.4 MB
docker-registry.service.strato:1818/staging/events-service            5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   5cb7a40f22f4        3 weeks ago         959.3 MB
rackattack-nas.dc1:5000/staging/events-service                        5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   5cb7a40f22f4        3 weeks ago         959.3 MB
docker-registry.service.strato:1818/staging/metrics-service           5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   fa17cb904511        3 weeks ago         831.7 MB
rackattack-nas.dc1:5000/staging/metrics-service                       5ea5cea71c4b9cc154ac9b79b1ed800ca13dc19a   fa17cb904511        3 weeks ago         831.7 MB
docker-registry.service.strato:1818/staging/maestro-tunnel-client     fc1ce3c62415b1b36996dee0b9b109888b4e5892   d9a1dc4cd8dc        3 weeks ago         19.93 MB
rackattack-nas.dc1:5000/staging/maestro-tunnel-client                 fc1ce3c62415b1b36996dee0b9b109888b4e5892   d9a1dc4cd8dc        3 weeks ago         19.93 MB
docker-registry.service.strato:1818/staging/maestro-events-reporter   fc1ce3c62415b1b36996dee0b9b109888b4e5892   754ff7a35c1a        3 weeks ago         24.69 MB
rackattack-nas.dc1:5000/staging/maestro-events-reporter               fc1ce3c62415b1b36996dee0b9b109888b4e5892   754ff7a35c1a        3 weeks ago         24.69 MB
docker-registry.service.strato:1818/staging/maestro-data-reporter     fc1ce3c62415b1b36996dee0b9b109888b4e5892   12a2dbd6d9d3        3 weeks ago         21.25 MB
rackattack-nas.dc1:5000/staging/maestro-data-reporter                 fc1ce3c62415b1b36996dee0b9b109888b4e5892   12a2dbd6d9d3        3 weeks ago         21.25 MB
docker-registry.service.strato:1818/staging/maestro-auth              fc1ce3c62415b1b36996dee0b9b109888b4e5892   f53dde11fca5        3 weeks ago         17.6 MB
rackattack-nas.dc1:5000/staging/maestro-auth                          fc1ce3c62415b1b36996dee0b9b109888b4e5892   f53dde11fca5        3 weeks ago         17.6 MB
docker-registry.service.strato:1818/staging/strato-kapacitor          a082e278751f6c68b85ce54af19ac2d484cc63e4   428241259bc6        3 weeks ago         889.9 MB
rackattack-nas.dc1:5000/staging/strato-kapacitor                      a082e278751f6c68b85ce54af19ac2d484cc63e4   428241259bc6        3 weeks ago         889.9 MB
docker-registry.service.strato:1818/staging/updatemanagerapi          afc63de2d188141b5e21ca03e493fe4abb42b98b   71fd91e8d580        3 weeks ago         1.095 GB
rackattack-nas.dc1:5000/staging/updatemanagerapi                      afc63de2d188141b5e21ca03e493fe4abb42b98b   71fd91e8d580        3 weeks ago         1.095 GB
docker-registry.service.strato:1818/staging/nodedapi                  afc63de2d188141b5e21ca03e493fe4abb42b98b   f424f7153c65        3 weeks ago         924.5 MB
rackattack-nas.dc1:5000/staging/nodedapi                              afc63de2d188141b5e21ca03e493fe4abb42b98b   f424f7153c65        3 weeks ago         924.5 MB
docker-registry.service.strato:1818/staging/mancala-copyservice       5f47f6d74631e820e558369b9d1bd325da0da913   87c43c0723d5        3 weeks ago         1.404 GB
rackattack-nas.dc1:5000/staging/mancala-copyservice                   5f47f6d74631e820e558369b9d1bd325da0da913   87c43c0723d5        3 weeks ago         1.404 GB
docker-registry.service.strato:1818/staging/credit-manager            81d8c2b55eff6648d89fc8ec018d4a9d5f4e52ef   33d83e6cdd0d        3 weeks ago         28.09 MB
rackattack-nas.dc1:5000/staging/credit-manager                        81d8c2b55eff6648d89fc8ec018d4a9d5f4e52ef   33d83e6cdd0d        3 weeks ago         28.09 MB
docker-registry.service.strato:1818/staging/vms-monitor               99ada8239983cada44449958197b2a56dd64b5c7   b75bdc74d74c        3 weeks ago         812.8 MB
rackattack-nas.dc1:5000/staging/vms-monitor                           99ada8239983cada44449958197b2a56dd64b5c7   b75bdc74d74c        3 weeks ago         812.8 MB
docker-registry.service.strato:1818/staging/ec2-api                   1b9fe69b137545a3740edf2dcb5bbe27333cccdd   ca2fe3d14494        3 weeks ago         924.3 MB
rackattack-nas.dc1:5000/staging/ec2-api                               1b9fe69b137545a3740edf2dcb5bbe27333cccdd   ca2fe3d14494        3 weeks ago         924.3 MB
docker-registry.service.strato:1818/staging/vm-manager                960aec5ecdc5c06582ea67a05422ccb2f9acc416   4b3cca84434b        3 weeks ago         852.7 MB
rackattack-nas.dc1:5000/staging/vm-manager                            960aec5ecdc5c06582ea67a05422ccb2f9acc416   4b3cca84434b        3 weeks ago         852.7 MB
docker-registry.service.strato:1818/staging/ui-backend                0898b72680236ee2fd5c4e9ec2da22fb997205b5   361fa1883fcc        3 weeks ago         1.386 GB
rackattack-nas.dc1:5000/staging/ui-backend                            0898b72680236ee2fd5c4e9ec2da22fb997205b5   361fa1883fcc        3 weeks ago         1.386 GB
docker-registry.service.strato:1818/staging/flower                    f2e8f7ee4ad7aa03743edd4920bfe84d7a0abcee   603d5d18b5b8        3 weeks ago         804.7 MB
rackattack-nas.dc1:5000/staging/flower                                f2e8f7ee4ad7aa03743edd4920bfe84d7a0abcee   603d5d18b5b8        3 weeks ago         804.7 MB
docker-registry.service.strato:1818/staging/quotas-manager            abe334e2f428b9315e22a8426755595c7bcfa29d   7503192918fd        4 weeks ago         798.8 MB
rackattack-nas.dc1:5000/staging/quotas-manager                        abe334e2f428b9315e22a8426755595c7bcfa29d   7503192918fd        4 weeks ago         798.8 MB
docker-registry.service.strato:1818/staging/registry                  6b4152d86bd9d80d901b3b359aacda3ab74a95d6   7568a9f38bf7        4 weeks ago         358 MB
rackattack-nas.dc1:5000/staging/registry                              6b4152d86bd9d80d901b3b359aacda3ab74a95d6   7568a9f38bf7        4 weeks ago         358 MB
docker-registry.service.strato:1818/staging/redis                     7ac9cb34877b8ae690b3d2c7a6fd360538f5e432   9ac31278393d        4 weeks ago         946.3 MB
rackattack-nas.dc1:5000/staging/redis                                 7ac9cb34877b8ae690b3d2c7a6fd360538f5e432   9ac31278393d        4 weeks ago         946.3 MB
docker-registry.service.strato:1818/staging/rediscale-monitor         7ac9cb34877b8ae690b3d2c7a6fd360538f5e432   330f20ed6713        4 weeks ago         814.9 MB
rackattack-nas.dc1:5000/staging/rediscale-monitor                     7ac9cb34877b8ae690b3d2c7a6fd360538f5e432   330f20ed6713        4 weeks ago         814.9 MB
docker-registry.service.strato:1818/staging/configurator              f7af12b8272b0b746b7958b696e66ff8de8864e3   69c8c1f82b8c        4 weeks ago         784 MB
rackattack-nas.dc1:5000/staging/configurator                          f7af12b8272b0b746b7958b696e66ff8de8864e3   69c8c1f82b8c        4 weeks ago         784 MB
docker-registry.service.strato:1818/staging/stratonet-frontend        2b3f65ca10099844e85026734cff83ef9d4876ef   84f4b71e9758        5 weeks ago         836.4 MB
rackattack-nas.dc1:5000/staging/stratonet-frontend                    2b3f65ca10099844e85026734cff83ef9d4876ef   84f4b71e9758        5 weeks ago         836.4 MB
docker-registry.service.strato:1818/staging/nginx                     137c54e092b83f2f0cceb5fdc0fcdfbbf7c5ab39   1e02ca26b9d5        5 weeks ago         823 MB
rackattack-nas.dc1:5000/staging/nginx                                 137c54e092b83f2f0cceb5fdc0fcdfbbf7c5ab39   1e02ca26b9d5        5 weeks ago         823 MB
docker-registry.service.strato:1818/staging/dr-manager                5cdf82ed39019355d11dd24956aac08bcd40fa38   ffc8aa7e8a39        6 weeks ago         831.8 MB
rackattack-nas.dc1:5000/staging/dr-manager                            5cdf82ed39019355d11dd24956aac08bcd40fa38   ffc8aa7e8a39        6 weeks ago         831.8 MB
docker-registry.service.strato:1818/staging/ec2-manager               9968db38cd7e040536486de2dc591c0ad30fc88c   5c1f0ec4f88a        7 weeks ago         791.7 MB
rackattack-nas.dc1:5000/staging/ec2-manager                           9968db38cd7e040536486de2dc591c0ad30fc88c   5c1f0ec4f88a        7 weeks ago         791.7 MB
docker-registry.service.strato:1818/staging/app-catalog               efe332741f8059997326ac91bb3a09d01a4a4b42   529be47c60fe        7 weeks ago         920.4 MB
rackattack-nas.dc1:5000/staging/app-catalog                           efe332741f8059997326ac91bb3a09d01a4a4b42   529be47c60fe        7 weeks ago         920.4 MB
docker-registry.service.strato:1818/staging/servicesgw                c4fcbf4f95c666059b94718f944f9abd84e2a8ec   e1b2bdfd5ce3        8 weeks ago         748 MB
rackattack-nas.dc1:5000/staging/servicesgw                            c4fcbf4f95c666059b94718f944f9abd84e2a8ec   e1b2bdfd5ce3        8 weeks ago         748 MB
docker-registry.service.strato:1818/staging/cluster-joiner            a1babfb5af0c34728c95c634715e122b78776ab3   0bad81bb6baa        3 months ago        767 MB
rackattack-nas.dc1:5000/staging/cluster-joiner                        a1babfb5af0c34728c95c634715e122b78776ab3   0bad81bb6baa        3 months ago        767 MB
docker-registry.service.strato:1818/staging/maestro-gotty             fc1ce3c62415b1b36996dee0b9b109888b4e5892   fbf4fee2970a        3 months ago        229.4 MB
rackattack-nas.dc1:5000/staging/maestro-gotty                         fc1ce3c62415b1b36996dee0b9b109888b4e5892   fbf4fee2970a        3 months ago        229.4 MB
docker-registry.service.strato:1818/staging/sagittarius-api           e644206e18fa8f6cf0a7050c122d79caf188f135   c629e47ed9db        4 months ago        824.7 MB
rackattack-nas.dc1:5000/staging/sagittarius-api                       e644206e18fa8f6cf0a7050c122d79caf188f135   c629e47ed9db        4 months ago        824.7 MB
nate/dockviz                                                          latest                                     4ea294712533        4 months ago        7.333 MB

**Comment by cpuguy83** [comment]
@rom-stratoscale The space used in `docker info` seems to reflect pretty much what you have in images.

**Comment by rom-stratoscale** [comment]
@cpuguy83 I know. The question is why running docker inspect -s / docker ps -s make the total capacity to grow.

**Comment by cpuguy83** [comment]
> make the total capacity to grow.

What is "total capacity" referring to here?

**Comment by rhvgoyal** [comment]
So "-s" displays size of container. How do we calculate size of container? I am wondering if we are accessing file system, and that somehow updates access time, that means change of metadata and that means unsharing of some blocks and that means using more space in thin pool? Just thinking loud.

**Comment by cpuguy83** [comment]
It does an lstat on everything in the rwlayer.

**Comment by rom-stratoscale** [comment]
@cpuguy83 total capacity: lvs | grep thin_pool or docker info | grep 'Data Space Used'

**Comment by cpuguy83** [comment]
@rom-stratoscale Thanks I am able to reproduce this.

**Comment by rom-stratoscale** [comment]
@cpuguy83 so you think it's a bug? Weren't you aware of such behavior?

**Comment by cpuguy83** [comment]
@rom-stratoscale Yes it seems like a bug, just not where at what level.
If you remove a container, the extra space utilization caused by the `docker ps -s` *from* that container will be cleaned up as well.

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637
