### ISSUE TITLE
[RFC] API error handling

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#32144]
Basically https://github.com/docker/docker/blob/master/api/server/httputils/errors.go#L52 has gone on far too long.

To replace this, we've tried a couple of different approaches which were pretty disastrous:

- errcode, which while there's nothing wrong with the errcode package, we used it horribly wrong and for the wrong reasons.
- HTTP errors package - https://github.com/docker/docker/blob/master/api/errors/errors.go#L13

errcode was a neat concept but in practice was misused and made the entire codebase just became absolutely horrible to work on where as before the horribleness was contained to just the API layer.

This lead to the http errors package currently in use for certain cases. This also seems like an "ok" thing, but in practice is also not really used correctly and generally more of a shortcut to correct error handling. We end up with low-level bits worried about HTTP status codes.

We need to standardize on a way to handle errors in the API. This potentially needs to be regardless of how the request came in (HTTP, GRPC, or even a direct function call...e.g. cluster->daemon).

The goal of good error handling is that the caller knows, or at least knows how to find out, the class of error that occurred so that the error can be dealt with appropriately. This is true of function calls and it is true across the "remote" API barrier.

### Goals

- API backends (e.g. `daemon`) should ideally not be concerned with HTTP.
- API clients should be able to read a returned error and be able to know *what* an error is.
- Reduce the cognitive overhead in trying to determine how to return an error
i. Example, what status code? (400, 409, 422, 412)
ii. How do I get the API to produce that status code I expect?
iii. How would non-remote API callers handle my error?
- Ensure status codes don't change because of either a change to the error text, or hopefully even a change to the low-level error type.

The way I see it there are really two ways to deal with this (in no particular order):

### Error class defined in common API package

This means in the API package we define several error classes like so (psuedo-code):

```go
package api

type Error interface {
    error
    NotFound() bool
    // other fn's for conflict, invalid arg, etc
}

type apiError struct { 
    err error
    notFound bool
    conflict bool
    invalidArg bool
}

func (e *apiError) Error() string { return e.err.Error() }
func (e *apiError) NotFound() bool { return e.notFound }

func NewNotFoundError(err error) Error {
    return &apiError{err: err, notFound: true}
}
```

From here the HTTP layer can determine both the error message and the class of error (not found) and the status code to return.

This approach is similar to the current approach we have except it's moving the http handling to the http layer and non-http code can just deal with this error type.

Another slight alternative but generally the same thing to this would be to use the well defined grpc error codes instead of defining our own. This could fit in well since part of the daemon is already using grpc anyway.

### Define error handling interfaces on backends

In this method, backends would be required to define a set of functions for error handling:

Example:

```go
package api

type ErrorInspector interface {
    IsNotFound(error) bool
    IsConflict(error) bool
    IsInvalidArgument(error) bool
}
```

```go
package container // container router

import "github.com/docker/docker/api"

type ContainerBackend interface {
    CreateContainer(...) error
    DeleteContainer(...) error
    api.ErrorInspector
}

func(r *containerRouter) getContainer(w http.ResponseWriter, req *http.Request) error {
    err := r.backend.DeleteContainer(...)
    if err != nil {
        if r.backend.IsNotFound(err) {
           // make an HTTP 404
       }
       // make an HTTP 500 probably
    }

    // normal
}
```

Writing out the above it seems a little risky since it requires the router to know the failure-modes of the backend. Maybe could be cleaned up a bit.

Interested in your thoughts, other alternatives, etc.

ping @docker/core-engine-maintainers

**Comment by aaronlehmann** [comment]
Both of these proposals are a bit rigid, in that there is some interface that needs to be satisfied completely, either by the errors themselves or the error inspectors exposed by the backends. I think there would be some maintenance challenges; for example, adding new classifications of errors would require updating every concrete type that implements the error interface, or every error inspector.

I think it's better to define narrow interfaces for each particular type of error, for example:

```go
type NotFoundError interface {
        error
        NotFound()
}
```

Then all you need to do to mark an error as a "not found" error is add a `NotFound` method on its type.

An error can potentially implement more than one interface, and it's up to the `api` package to define precedence rules.

It also makes sense to support the `causer` interface from `github.com/pkg/errors`. Then, if an error is wrapped, information about the type of error is not lost.

```go
type causer interface {
        Cause() error
}

for err != nil {
        switch err.(type) {
        case NotFound:
                // treat as not found error
                return errTypeNotFound
        case InvalidArgument:
                // treat as invalid argument error
                return errTypeInvalidArg
        ...
        case causer:
                err = err.(causer).Cause()
        default:
                return errTypeUnknown
        }
}
```

**Comment by cpuguy83** [comment]
@aaronlehmann Thanks! Agree that's kind of what I was envisioning but it didn't make it to the demo code.

**Comment by AkihiroSuda** [comment]
WDYT about introducing a JSON object?

e.g.
```json
{
  "errorID": "com.docker.error.engine.volume.notfound",
  "resourceNotFound": true,
  "volume": "blah",
  "message": "volume \"blah\" not found",
  "from": {"file": "github.com/docker/docker/foo/bar.go", "line": 42},
  "cause": {
    "errorID": "com.docker.error.engine....",
  }
}
```

Pro: can be easily transported between multiple API subsystems (REST, gRPC, stdout/stderrr)
Con: complicated

**Comment by cpuguy83** [comment]
@AkihiroSuda The good news is, we already return a json object, currently with only a "message" field.

**Comment by dnephin** [comment]
A json message is great, but we still need to return a proper HTTP status code, so I don't think that completely solves the problem. The json message body should be just for additional details about the error, not categorizing the error.

**Comment by thaJeztah** [comment]
ping @jlhawn I just heard you are working on similar things for DDC, perhaps you can add your input?

**Comment by thaJeztah** [comment]
Being discussed in the maintainers meeting to pick two/three status codes;

- 2xx - success
- 4xx - failure

And have the JSON contain the error that needs to be handled

**Comment by stevvooe** [comment]
@cpuguy83 I'd like to see use properly use the `errcode` package but we also need to follow @aaronlehmann's suggestion in https://github.com/docker/docker/issues/32144#issuecomment-289537578. The problem with the original `errcode` attempts was that they tried to embed status codes _deep_ in the daemon models, when that mapping should be purview of the http controllers.

@AkihiroSuda https://github.com/docker/docker/issues/32144#issuecomment-289642318 purposes much of what the errcode package already provides.
