### ISSUE TITLE
docker container showing up on port that was not published

### ISSUE THREAD

**Issue by dskow** [moby/moby#32201]
**Description**

I had two containers running on a host server both exposing port 8080.  They were mapped to two different ports 8081 and 8088 they were both set to "--restart="always" option and the "--net=host" was not used.  The 8081 was a Jenkins and the 8088 was a tomcat. After starting the service they both were working fine on the correct ports.  A month later (after several host server reboots) the services were not on the correct ports. The service that should have showed up on port 8081 was on 8088 and the one that was suppose to be on port 8088 was not found anywhere.  The host is running on Ubuntu 16.04.  The jenkins is jenkins:alpine and the tomcat is tomcat:9-jre8-alpine

**Steps to reproduce the issue:**

This was seen only once and is not known how to recreate it at this time.

1.  Run jenkins on 8081 and tomcat on 8088
2.  Restart the host server a few times.
3.  Go to a browser and check for jenkins.

**Describe the results you received:**

Jenkins showed up on 8088 instead of 8081.  Tomcat could not be found.  After docker stop and docker start commands, the problem went away.

**Describe the results you expected:**

Jenkins on 8081. Tomcat on port 8088

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 70
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 1krdjrv1jpog6ykozdr0f5f4y
 Is Manager: true
 ClusterID: 2jjb2g5o3ua2kjt6pf3plv8to
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.20.50
 Manager Addresses:
  10.10.20.50:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-67-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 5.827 GiB
Name: Servertest
ID: LTFK:OMBP:J42O:7MIU:PEB3:4OB5:JOIL:XPSS:BR3R:KFY5:BKVI:NIMS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Do you still have access to logs around the time it went wrong? Anything useful in there?

**Comment by dskow** [comment]
I have redone the system, but I did manage to capture the docker log for the jenkins container before that.  Here is the jenkins docker log.  I see that the container time is in UTC and the host is EST.
[https://gist.github.com/dskow/4536e703be64ef9fadafbd05ff7024c5](url)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
