### ISSUE TITLE
docker commands stop working until service docker restart

### ISSUE THREAD

**Issue by AnthonyWC** [moby/moby#32214]
**Description**

docker commands & docker containers become unresponsive
 
**Steps to reproduce the issue:**
Unsure; but initially symptoms were getting "Compose error "HTTP request took too long to complete" when running some docker-compose commands; however docker containers themselves are already unresponsive.

**Describe the results you received:**
See: https://github.com/docker/compose/issues/3633

```
ubuntu@ip-172-17-0-146:~/docker/prometheus$ docker-compose restart prometheus 
Restarting prometheus_prometheus_1 ... 

ERROR: for prometheus_prometheus_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

docker-compose & docker command initially worked but degraded to non-working condition:

Unresponsive commands:
ubuntu@ip-172-17-0-146:~/docker/prometheus$ docker ps
^C

```

**Additional information you deem important (e.g. issue happens only occasionally):**
1st encounter of this issue; memory usage at the host itself was ~ 75%; after service docker restart & restarting containers in docker-compose; it is ~ 25

See result of prometheus monitoring before and after service docker restart: 
sum(container_memory_rss{name=~".+"}) by (name)
![image](https://cloud.githubusercontent.com/assets/6215805/24476687/4a36fbfc-14a2-11e7-968a-cebecdce3223.png)

**Various Output**

```
ubuntu@ip-172-17-0-146:~/docker/prometheus$ lsb_release -a                                                       [884/6703]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

ubuntu@ip-172-17-0-146:~/docker/prometheus$ docker-compose version
docker-compose version 1.11.0, build 6de1806
docker-py version: 2.0.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
ubuntu@ip-172-17-0-146:~/docker/prometheus$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

ubuntu@ip-172-17-0-146:~/docker/prometheus$ docker info
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 174
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2

(before restart docker daemon)
ubuntu@ip-172-17-0-146:~/docker/prometheus$ df -i
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
udev            504131     390 503741    1% /dev
tmpfs           505620     689 504931    1% /run
/dev/xvda1     1310720 1213539  97181   93% /
tmpfs           505620       1 505619    1% /dev/shm
tmpfs           505620       3 505617    1% /run/lock
tmpfs           505620      16 505604    1% /sys/fs/cgroup
tmpfs           505625       4 505621    1% /run/user/1000
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS/t2.medium/4G RAM

**Comment by sharklhl** [comment]
i also find this problm  when my docker work on Ubuntu 14.04

**Comment by Fak3** [comment]
I have similar error on openSUSE 42.2
```
linux-1zpk:/home/u1 # docker -v
Docker version 1.12.6, build 78d1802
linux-1zpk:/home/u1 # uname -a
Linux linux-1zpk 4.10.1-5.gf764d42-default #1 SMP PREEMPT Tue Mar 7 09:29:19 UTC 2017 (f764d42) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
When you get an unresponsive daemon, can you send `SIGUSR1` to the dockerd process and collect the stack dump from the logs?

**Comment by cpuguy83** [comment]
Also, can you explain what you are running inside the containers?

**Comment by AnthonyWC** [comment]
I was running mainly prometheus + grafana; prometheus is the container that seems to have the memory leak.  But can a memory leak container causes docker itself to fail?

**Comment by cpuguy83** [comment]
Once a system runs out of memory anything can happen.

**Comment by armand1m** [comment]
I'm running through this issue either in a project I'm currently working. We have a docker-compose.yml that runs 4 services and this error happens most of the time when I need to stop all the services and recreate them, while recreating the services. This happens both on Docker for Mac at latest version and using Docker CE on a Ubuntu, both with 12gb of ram.

**Comment by thaJeztah** [comment]
closing as this one went stale

**Comment by lu-li-xin** [comment]
Has this problem been solved？
