### ISSUE TITLE
/var/lib/docker/aufs shares partition with other directory

### ISSUE THREAD

**Issue by FreeSlave** [moby/moby#32226]
When I installed Debian on my computer, I gave separate partition for /var directory.
After I installed docker "/var/lib/docker/aufs" partition appeared, but it shares the same device with /var

```
mount | grep sdb7
/dev/sdb7 on /var type ext4 (rw,relatime,data=ordered)
/dev/sdb7 on /var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
```

I guess this is the reason why /var directory does not appear in the list of available media in file managers and gnome-disk-utility, while /var/lib/docker/aufs does (i.e. it overlaps the former)

The directory itself is still available via file system hierarchy.

Also during shutdown I see message something like "Failed to unmount /var".

If I uninstall docker-engine, /var appears as it should. If then I install docker-engine again, /var/lib/docker/aufs overlaps /var again.

**Comment by cpuguy83** [comment]
This is most likely because we re-mount `/var/lib/docker/aufs` to make it private.
During shutdown are you shutting down docker?

**Comment by FreeSlave** [comment]
I think I figured out the circumstances. I see "Failed unmounting /var." message during shutdown when there's some running container (detached).
Docker is started as service, so I think systemd must shutdown it. Here's log, regarding docker:

```
Apr 06 15:44:26 debian dockerd[2485]: time="2017-04-06T15:44:26.480794088+03:00" level=info msg="Container 0da01038704b7427799519a919768b2ae827f962e823517039c421de5a3c796b failed to exit within 10 seconds of signal 15 - using the force"
Apr 06 15:44:26 debian kernel: docker0: port 1(vetha6495c4) entered disabled state
Apr 06 15:44:26 debian kernel: docker0: port 1(vetha6495c4) entered disabled state
Apr 06 15:44:26 debian kernel: device vetha6495c4 left promiscuous mode
Apr 06 15:44:26 debian kernel: docker0: port 1(vetha6495c4) entered disabled state
Apr 06 15:44:26 debian systemd[1]: Unmounted /run/docker/netns/507f118259eb.
Apr 06 15:44:26 debian systemd[1]: Unmounted /var/lib/docker/containers/0da01038704b7427799519a919768b2ae827f962e823517039c421de5a3c796b/shm.
Apr 06 15:44:26 debian systemd[1]: Unmounted /var/lib/docker/aufs/mnt/2590fbe6e537276f8d8d396dcb014f1c449659a176d43510dcc145fcdcf32697.
Apr 06 15:44:27 debian systemd[1]: Unmounted /var/lib/docker/aufs.
Apr 06 15:44:27 debian dockerd[2485]: time="2017-04-06T15:44:27.330585833+03:00" level=info msg="stopping containerd after receiving terminated"
Apr 06 15:44:28 debian systemd[1]: Stopped Docker Application Container Engine.
```

Then later about /var:

```
Apr 06 15:45:58 debian systemd[1]: var.mount: Mount process exited, code=exited status=32
Apr 06 15:45:58 debian systemd[1]: Failed unmounting /var.
```

**Comment by cpuguy83** [comment]
If docker is shutdown how can there be a running container?
You may also need to customize docker.service to make sure it's not started until after `/var` is mounted.

**Comment by FreeSlave** [comment]
You can see from the first line that container exits by force.

**Comment by FreeSlave** [comment]
According to the startup log, docker is started way after /var is mounted.

**Comment by cpuguy83** [comment]
If you stop Docker, and then manually `umount /var` what happens?

**Comment by FreeSlave** [comment]
$ docker run -d ...
$ sudo service docker stop
$ sudo umount /var
```
umount: /var: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
```
$ mount | grep /var
```
/dev/sdb7 on /var type ext4 (rw,relatime,data=ordered)
/dev/sdb7 on /var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /var/lib/docker/aufs/mnt/6c06071c09395e2dd8c75456e2a7a521b46f1a64fefee8db10f01790f4a864ef type aufs (rw,relatime,si=ee45d78075afe79f,dio,dirperm1)
shm on /var/lib/docker/containers/8aefeafcfd1b7f533f31a29958cfef360a0de8708a519321afc45ae81190623e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```

$ systemctl status docker
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2017-04-07 14:39:36 MSK; 3min 30s ago
     Docs: https://docs.docker.com
 Main PID: 2565 (code=killed, signal=KILL)

Apr 07 14:39:13 debian dockerd[2565]: time="2017-04-07T14:39:13.477526001+03:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Apr 07 14:39:13 debian dockerd[2565]: time="2017-04-07T14:39:13.802089432+03:00" level=error msg="containerd: notify OOM events" error="cgroup path for memory not found"
Apr 07 14:39:26 debian systemd[1]: Stopping Docker Application Container Engine...
Apr 07 14:39:26 debian dockerd[2565]: time="2017-04-07T14:39:26.398180974+03:00" level=info msg="Processing signal 'terminated'"
Apr 07 14:39:36 debian dockerd[2565]: time="2017-04-07T14:39:36.398842210+03:00" level=info msg="Container 8aefeafcfd1b7f533f31a29958cfef360a0de8708a519321afc45ae81190623e failed to exit within 10 seconds of signal 15 - using the force"
Apr 07 14:39:36 debian systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
Apr 07 14:39:36 debian systemd[1]: docker.service: Main process exited, code=killed, status=9/KILL
Apr 07 14:39:36 debian systemd[1]: Stopped Docker Application Container Engine.
Apr 07 14:39:36 debian systemd[1]: docker.service: Unit entered failed state.
Apr 07 14:39:36 debian systemd[1]: docker.service: Failed with result 'signal'.
```

**Comment by FreeSlave** [comment]
If I don't start container before, /var/lib/docker/aufs is unmounted on "service docker stop" as it should.

**Comment by cpuguy83** [comment]
@FreeSlave I bet this is due to a 10s default timeout for killing the docker service.
You could increase this to account for containers that don't shutdown properly.
Docker itself uses a 10s timeout for sending SIGKILL to a container that's not responding to SIGTERM. If systemd has a default 10s timeout to SIGKILL dockerd, this could interfere with unmounting the aufs dir.

Ideally the container in question would be fixed to respond to `SIGTERM`.
Note that many processes, when run as PID1, do not use default signal handlers.

But also to ensure the the aufs dir is unmounted on shutdown, you could add:

```
ExecStopPost=/bin/sh -c 'umount /var/lib/docker/aufs/* && umount /var/lib/docker/aufs'
```

It's been awhile since I've messed around with systemd units, not sure if that syntax works, but the idea is that the command will run after the service is stopped.

**Comment by FreeSlave** [comment]
What do you mean by "he container in question would be fixed"?
Process itself has signal handlers for SIGTERM and SIGINT, but in-container app does not receive them by sending these signals with "docker kill" command.
Should I fork the app process from some other so it will not have pid 1?

**Comment by cpuguy83** [comment]
@FreeSlave Is the container process being run in a shell, such as `sh -c '<binary>`?

**Comment by FreeSlave** [comment]
Oh, it runs like "CMD service redis-server start && ./gamewatcher", so already in shell, therefore process itself can't have pid = 1. I even added output of getpid to be sure and it's not 1.

**Comment by FreeSlave** [comment]
I replaced it with "CMD service redis-server start && exec ./gamewatcher", not it exits by TERM signal. Will see later how it will behave on shutdown.

**Comment by FreeSlave** [comment]
"Failed to unmount /var" still happens even with ExecStopPost you provided.
I'll try to make virtual machine to replicate issue.

**Comment by FreeSlave** [comment]
I just realized that /var can't be unmounted because of journald wriring to /var/log/journal. But I remember that this message could happen before I enabled  shutdown journaling.
Now I'm looking for alternative way to see shutdown messages.

**Comment by AkihiroSuda** [comment]
AUFS was deprecated in 19.03: https://github.com/docker/cli/pull/1484/files
