### ISSUE TITLE
Error Pulling the Docker Image

### ISSUE THREAD

**Issue by sandeep540** [moby/moby#32257]
Hi All,

I am trying to pull a docker Image, But I am getting the below message. The same was working before 3 weeks for another docker images

OS: CentOS7

[root@WWPLMS107 ~]# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

**docker pull selenium/standalone-firefox-debug**

_error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/77/771e0485dbffc41a571384d14cd81ea71b99b143574411a98f5ba1a99d645dbd/data?Expires=1490957768&Signature=VPRQ~hC9GXxdTCAm9PpwThRYiZH6FlRzyK~oyzfv63GhiWlA~pxr3vnU-s78rXt7WiOquSGVc-b6my2VhwHONmZdUwrGRjJ6iy~nL2FiD6AkGpsMrxJBRYKDHrQFFTDbLQaXdXoUMP-o01706Sybc09wWlpsdc6lIay2LZ0GEUA_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.222.190.252:443: i/o timeout_

**Comment by thaJeztah** [comment]
This is working for me, but the error message looks like an issue with Docker Hub (or cloud front having issues); can you pull other images?

**Comment by laptevn** [comment]
The same for MacOS and recent Docker version.
Login/pull/push are finished with timeout.
This issue happens on weekends. It seems Docker Hub is not fully available on weekend.
On working days it starts working. The last time it worked was yesterday noon. Since yesterday evening timeout happens.

**Comment by thaJeztah** [comment]
@laptevn weekend or not should not make a difference; both pull were from the same location, same network? if you keep having that problem, could you try contacting support@docker.com? Docker Hub / Infra is really a different team, and not related to the source code in this repository

**Comment by laptevn** [comment]
@thaJeztah 
I tried different locations, tried Docker restarting/resetting/reinstalling and even tried different Mac OS versions :-)
The only useful thing I found is that timeout happens on weekend usually.
I will try to reach support.
Thanks.

**Comment by laptevn** [comment]
No response from support. But Docker Edge version doesn't have this problem.

**Comment by thaJeztah** [comment]
I'm going ahead and close this issue, but if you encounter this, please add the output of;

```
dig dseasb33srnrn.cloudfront.net
```

and 

```
dig dseasb33srnrn.cloudfront.net 8.8.8.8
```

(running on the host where the docker daemon runs) which would help to find what your local DNS returns for these.
