### ISSUE TITLE
Connect to Docker host from container

### ISSUE THREAD

**Issue by Telokis** [moby/moby#32277]
#1143 and #8395 are closed but not resolved.
Not a single of the workarounds found there has been working for me. (No joke, I've tried a lot of them)

I do need a way to connect to a service running on my host from within a container. I don't want a hacky workaround, this is not reliable. I want an effective solution working for Windows and Linux at least.

This may be link to that : even though I can access the internet from within my container (using wget, for example), I can't access my own host ip. It keeps hanging indefinitely an doesn't show anything.
I tried a lot of different ways but none worked.

Docker version:
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Docker info:

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 37
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-914044-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.049 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.394 GB
 Metadata Space Used: 4.719 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.59 GiB
Name: ***
ID: 63DC:SOQW:AGBN:HEQ4:47CR:E6BB:KL5W:SBQX:YLVY:GLT7:3VBI:6WA4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ninetainedo
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

* Went inside a container (any container, using exec or `/bin/bash` directly)
* Tried to curl/wget/telnet `mydomain.com` (tried multiple ports and multiple "services" (not only web))
* Domain is resolved but container doesn't connect to it.
* Domain is (obviously) working fine when I access it from anything other than a container.

This works fine when I try it on my local machine.

**Comment by Telokis** [comment]
How do we get an answer here?

**Comment by cpuguy83** [comment]
On >= 1.13, you need to set the daemon option `ip-forward=true`

**Comment by Telokis** [comment]
@cpuguy83 Thanks for the answer!
How do I do that? I don't even remember starting the daemon myself.

**Comment by cpuguy83** [comment]
@Telokis Probably the best way is to create a file @ `/etc/docker/daemon.json` with the contents:
```json
{
    "ip-forward": true
}
```

Then `systemctl restart docker`

**Comment by Telokis** [comment]
@cpuguy83 Just did it but it doesn't work either. I'd like to point out that `curl mydomain.com` doesn't work. Even without using the docker ip or anything special. I just cannot contact my server from inside a container

**Comment by cpuguy83** [comment]
Have you run tcpdump to see where the packets are falling flat?

**Comment by Telokis** [comment]
No, I didn't know this tool. How am I supposed to proceed?

**Comment by emudojo** [comment]
same thing here, I´m running gitlab in the host, and then the container hangs when cloning from it... frustrating, tried with ip'forward and got the same result

**Comment by Telokis** [comment]
@cpuguy Could it be an issue related to iptables? Mine are very restrictives that might be the reason?

**Comment by cpuguy83** [comment]
It can be any number of things, I'd recommend setting up tcpdump so you can watch the packets and see where they are being dropped.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
