### ISSUE TITLE
Why rfc5424&rfc5424micro return messages contains two tags?

### ISSUE THREAD

**Issue by adaiguoguo** [moby/moby#32294]
**Description**
Why rfc5424&rfc5424micro return messages contains two **tags** ?
[code in master](https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L83)

**Steps to reproduce the issue:**
`
tcpdump -nnvvXSs 1514 -i lo port 514
`

**Describe the results you received:**
Two tags
`
 Msg: 1 2017-04-01T17:41:05.616647+08:00 a.vm {taskid:aa,version:} 1787791 {taskid:aa,version:} PING www.baidu.com (115.239.211.112): 56 data bytes\0x0d\0x0a
`

**Describe the results you expected:**
Just one enough.
`
Msg: 1 2017-04-01T17:41:05.616647+08:00 a.vm {taskid:aa,version:} 1787791 PING www.baidu.com (115.239.211.112): 56 data bytes\0x0d\0x0a
`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22-unsupported
 Built:        Tue Mar 21 05:40:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22-unsupported
 Built:        Tue Mar 21 05:40:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 30
Server Version: 17.03.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:2-526428-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 53.69 GB
 Backing Filesystem: xfs
 Data file: /dev/vg/docker-data
 Metadata file: /dev/vg/docker-metadata
 Data Space Used: 14.55 GB
 Data Space Total: 1.057 TB
 Data Space Available: 1.042 TB
 Metadata Space Used: 107.3 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 16.94 GB
 Thin Pool Minimum Free Space: 105.7 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 62.76 GiB
Name: adca-mesos-20.vm
ID: V6CT:HCVU:IAIZ:7IGE:TQQO:ZVXB:4COD:3CPT:NF7N:MDPC:466V:H2MD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by fntlnz** [comment]
If you look at the [ABNF reference](https://tools.ietf.org/html/rfc5424#section-6) in syslog's RFC in the header section, this part

```
TIMESTAMP SP HOSTNAME SP APP-NAME SP PROCID SP MSGID
```

that can be mapped with your line as:

```
                TIMESTAMP SP HOSTNAME SP APP-NAME SP PROCID SP MSGID
                    +          +             +           |        +
                    |          |             |           |        |
                    |          |             |           |        |
       +------------+          +----+        |           +----+   +---------+
       ^                            v        v                v             v
2017-04-01T17:41:05.616647+08:00 a.vm {taskid:aa,version:} 1787791 {taskid:aa,version:}

```

Where `SP` is the space (`%d32`).

Said that, looking into the source code looks like that the `rfc5242` formatters are actually named `rfc5424microformatterWithAppNameAsTag` and `rfc5424formatterWithAppNameAsTag`, this particular format has been adopted to be bc with  [rfc 3146](https://tools.ietf.org/html/rfc3164) - probably we can find some other value to fill `APP-NAME` instead of the tag but this is the way in which this is currently implemented

**Comment by adaiguoguo** [comment]
@fntlnz Thank you for all your assistance.I suggest put **CONTAINER ID** to fill APP-NAME.
