### ISSUE TITLE
[OpenVZ] Cannot start docker

### ISSUE THREAD

**Issue by qwerty2000** [moby/moby#32334]
I've installed Docker on a VPS with Centos 7 according to the guide on docker.com. However, I cannot start docker. I receive the following message:

● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-04-04 00:57:55 CEST; 3min 35s ago
     Docs: https://docs.docker.com
  Process: 3520 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 3520 (code=exited, status=1/FAILURE)

.... level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
..... level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
..... level=info msg="Graph migration to content-addressability took 0.00 seconds"
..... level=warning msg="Your kernel does not support oom control"
..... level=warning msg="Your kernel does not support memory swappiness"
.... level=warning msg="Your kernel does not support kernel memory limit"
.... level=warning msg="Unable to find cpu cgroup in mounts"
.... level=warning msg="Unable to find cpuset cgroup in mounts"
..... level=warning msg="mountpoint for pids not found"
.... vps-.......nl dockerd[3520]: Error starting daemon: Devices cgroup isn't mounted

Uname:

Linux vps-...........nl 3.10.0-042stab117.16 #1 SMP Fri Sep 9 21:57:19 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

Any suggestions to fix it? 

Thx in advance!

**Comment by AkihiroSuda** [comment]
The environment seems OpenVZ. See https://openvz.org/Docker_inside_CT

Note that Docker upstream does not support OpenVZ. 
If you have a further question, I suggest asking to OpenVZ community.

**Comment by unclejack** [comment]
As @AkihiroSuda has stated above, the Docker project doesn't support OpenVZ. This is something to be discussed with the OpenVZ project.

I'll close this now since there's nothing actionable in this issue. Please feel free to comment and to continue the discussion.
