### ISSUE TITLE
--init-path does not seem to work.

### ISSUE THREAD

**Issue by andyneff** [moby/moby#32355]
While using `--init` works and execute tini 0.13.0. However, I cannot figure out how to use --init-path to change the init binary used.

**Steps to reproduce the issue:**
1. docker run -it --rm --init --init-path=/usr/local/bin/tini  --entrypoint=bash krallin/ubuntu-tini
2. /proc/1/exe -h

**Describe the results you received:**

    exe (tini version 0.13.0 - git.949e6fa)

**Describe the results you expected:**

    tini (tini version 0.13.2 - git.79016ec)

**Additional information you deem important (e.g. issue happens only occasionally):**

I also tries pointing --init-path to a path on the host as suggested on krallin/tini#81, and that did not help either.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
I think the `--init-path` option was intended to be a daemon-only flag, but became added to `docker run` and `docker create` because the location in the code where it is used both by the `dockerd` CLI and the `docker run` CLI.

Can you try if you set the init-path through either the `--init-path` flag on `dockerd`, or through the [`daemon.json` configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file);

```json
{"init-path":"/foo/bar/baz/docker-init"}
```

We should probably remove the flag from `docker create` and `docker run`

/cc @runcom

**Comment by runcom** [comment]
thanks for the ping @thaJeztah I'll look into this

**Comment by runcom** [comment]
> We should probably remove the flag from docker create and docker run

not sure why we would though?

**Comment by justincormack** [comment]
It is weird specifying a path on the client that refers to a server path,
as the install path could vary, i think it was only intended to be daemon
config.

**Comment by runcom** [comment]
> It is weird specifying a path on the client that refers to a server path,
> as the install path could vary, i think it was only intended to be daemon
> config.

well, yeah, the intention was to be daemon only indeed - I can remove the client side stuff of init[-path] if we all agree.

**Comment by thaJeztah** [comment]
> not sure why we would though?

IIUC, the daemon flag was added to allow for the `docker-init` binary to be in a different location (which was a use-case), but not sure we should have added it to `docker run`, `docker create` (specify a different "init" per container)

If it has been broken all this time, and not intended to be there, perhaps removing is best.

**Comment by andyneff** [comment]
I agree with @justincormack, if we specify a server path in `docker create`/`docker run`, it is weird. 

Originally, it just seemed natural when using `docker run` that `--init-path` would be specifying a path in container's path for the init binary. So maybe if we do keep it, we'd make it a path in the container instead for `docker create` and `docker run`, but leave it as a path for the server for `dockerd`?

Of course if all think that shouldn't be allowed, I'd agree with @thaJeztah then.

**Comment by runcom** [comment]
@thaJeztah @justincormack is it ok if I go ahead and remove the client stuff for `--init[-path]` then?

**Comment by justincormack** [comment]
@andyneff if the `init` is already in the container you can just use it as your `entrypoint` you dont need special options.

@runcom yes, I would.
