### ISSUE TITLE
Stack compose version 3.2 on swarm mode

### ISSUE THREAD

**Issue by stingus** [moby/moby#32353]
When using `docker deploy` with a 3.2 compose version, it fails with "unsupported Compose file version: 3.2". I could not find any docs (especially on https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix) on the required docker version to use the 3.2 compose.

**Steps to reproduce the issue:**
1. Create a compose file with version 3.2:
```
# compose-v32.yml
version: '3.2'
  services:
    myservice:
    ...
```
2. Run `docker deploy -c compose-v32.yml mystack

**Describe the results you received:**
unsupported Compose file version: 3.2

**Describe the results you expected:**
Created myservice

**Output of `docker version`:**
```
Client:
Version:      17.03.1-ce
API version:  1.27
Go version:   go1.7.5
Git commit:   c6d412e
Built:        Fri Mar 24 00:00:50 2017
OS/Arch:      linux/amd64

Server:
Version:      17.03.1-ce
API version:  1.27 (minimum version 1.12)
Go version:   go1.7.5
Git commit:   c6d412e
Built:        Fri Mar 24 00:00:50 2017
OS/Arch:      linux/amd64
Experimental: true
```
**Output of `docker info`:**
```
Containers: 5
Running: 4
Paused: 0
Stopped: 1
Images: 6
Server Version: 17.03.1-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host ipvlan macvlan null overlay
Swarm: active
NodeID: mlc7uzdsvcnxkzi32437xybuv
Is Manager: true
ClusterID: 6xjp4en70m49rkgt1u2jzo1fe
Managers: 1
Nodes: 2
Orchestration:
 Task History Retention Limit: 5
Raft:
 Snapshot Interval: 10000
 Number of Old Snapshots to Retain: 0
 Heartbeat Tick: 1
 Election Tick: 3
Dispatcher:
 Heartbeat Period: 5 seconds
CA Configuration:
 Expiry Duration: 3 months
Node Address: 10.99.0.9
Manager Addresses:
 10.99.0.9:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
seccomp
 Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.354 GiB
Name: swarm-manager000000
ID: YLGP:ANHJ:ODKD:DZXG:YOG3:XA2Y:VVLK:LZ2M:N2NS:7PCF:STL5:DKVL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 276
Goroutines: 372
System Time: 2017-04-04T14:33:05.635698193Z
EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Swarm Mode running on Azure Container Services.

**Comment by vdemeester** [comment]
I think the docs needs update because, if I'm not mistaken, compose file version `3.2` is supported by docker `17.04` and later.
/cc @thaJeztah @dnephin 👼

**Comment by fvilers** [comment]
Can someone confirm @vdemeester's answer?

**Comment by thaJeztah** [comment]
Correct, docker 17.03.1 only supports the 3.0 and 3.1 docker-compose file schema; https://github.com/moby/moby/blob/v17.03.1-ce/cli/compose/schema/bindata.go#L3-L4

Docker 17.04.0 added the 3.2 schema;
https://github.com/moby/moby/blob/v17.04.0-ce/cli/compose/schema/bindata.go#L3-L5

And Docker 17.06 adds the 3.3 schema;
https://github.com/docker/docker-ce/blob/v17.06.0-ce-rc5/components/cli/cli/compose/schema/bindata.go#L3-L6

**Comment by thaJeztah** [comment]
Opened a pull request to address the documentation: https://github.com/docker/docker.github.io/issues/3721
