### ISSUE TITLE
Interactive docker service scale

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32368]
Following up on @sirlatrom's comment 
https://github.com/docker/docker/pull/31144#issuecomment-291461132,
we do have interactive `service create` and `service update` commands (https://github.com/docker/docker/pull/31144) but not `service scale`.

We should consider supporting scale as well.

This is somewhat related to https://github.com/docker/docker/issues/32367 since `scale` supports multiple services (e.g. `scale web=5 db=2`), therefore we should provide per-service overall status rather than per-task.

/cc @aaronlehmann @thaJeztah

**Comment by thaJeztah** [comment]
Implemented in https://github.com/docker/cli/issues/243
