### ISSUE TITLE
Suppress installer.sh AUFS warning if overlay2 is available

### ISSUE THREAD

**Issue by callahad** [moby/moby#32361]
**Description**

Installing Docker on Linode via the `curl https://get.docker.com/ | sh` method [warns about missing AUFS support](https://github.com/docker/docker/blob/9f17b97820912001a1bf7fd827a65b0298b4dd1f/hack/install.sh#L428-L449). However, the Linode-supplied kernel *does* have the `overlay` module, and thus Docker's `overlay2` storage driver is used by default.

As `overlay2` seems to be the successor to AUFS, perhaps this warning should be suppressed when it's available?

**Steps to reproduce the issue:**
1. Create new Ubuntu 16.04 LTS or Debian 8 Stable VPS on Linode
2. As root, run `wget -nv -O - https://get.docker.com/ | sh`

**Describe the results you received:**

```
Warning: current kernel is not supported by the linux-image-extra-virtual
 package.  We have no AUFS support.  Consider installing the packages
 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
```

**Describe the results you expected:**

Installation without warnings.

**Comment by thaJeztah** [comment]
We already changed the instructions to make it a ["recommendation" for Ubuntu 14.04]( https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404) only, so yes, if we can detect overlay(2) is supported, I'd be :+1: to don't show that message.

Are you interested in opening a pull request to make those changes to the script (to hide if an alternative is supported); also, I think the script should _skip_ installing aufs in those cases.

**Comment by callahad** [comment]
I'm not sure what a good way to detect support would be, in Linode's environment. Each VPS is running under KVM with a shared kernel, so `modprobe`, `lsmod`, and `modinfo` all fail to return any information. I *do* see a `/sys/module/overlay/` directory, maybe its presence is sufficient if `modprobe overlay` fails? Other ideas?

**Comment by thaJeztah** [comment]
This is what the `check-config.sh` script does; https://github.com/docker/docker/blob/master/contrib/check-config.sh#L328-L331, which (following the script) calls https://github.com/docker/docker/blob/master/contrib/check-config.sh#L16-L38

But we should also scope that warning to only ubuntu 14.04 I guess (per the discussion above). Does that help?

**Comment by callahad** [comment]
That helps. I don't have the bandwidth to address this in the near future, but those are excellent pointers for whomever does. :)

The TL;DR is: Look for `CONFIG_OVERLAY_FS=y` or `CONFIG_OVERLAY_FS=m` in the first file to exist of `/proc/config.gz`,	`/boot/config-$(uname -r)`, `/usr/src/linux-$(uname -r)/.config`, and `/usr/src/linux/.config`

**Comment by justincormack** [comment]
Actually that is not a good way to do it as the module information is not a good source. You can just look for `overlay` in `/proc/filesystems` though. To detect `overlay2` support you need to check the kernel version too.

**Comment by thaJeztah** [comment]
@justincormack should the check config script be updated as well? Or different kind of check?

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
