### ISSUE TITLE
docker stack deploy an URL

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32366]
This is very low priority, but it would be pretty cool to be able to run:

```
$ docker stack deploy mystack -c https://raw.github.com/.../docker-compose.yml
```

/cc @vieux @dnephin @thaJeztah

**Comment by AkihiroSuda** [comment]
IIUC there is a plan to add `docker bundle pull`.
Does this issue relate to `docker bundle pull`?

https://github.com/docker/docker/issues/26876

**Comment by thaJeztah** [comment]
This works for me if you're running bash;

```bash
docker stack deploy -c<(curl -fsSL https://raw.githubusercontent.com/docker/compose/master/tests/fixtures/v3-full/docker-compose.yml) foo
```

(the compose file seems to be invalid, but it works :D)

**Comment by cpuguy83** [comment]
lol, the new `curl | bash`

**Comment by thaJeztah** [comment]
@cpuguy83 yup, it is, but t.b.h. we'd have the same if `-c` accepts an URL; perhaps it's best to _not_ have this as a feature, to encourage people to _download_ first before blindly deploying something from an URL (well, unless there's Notary in use)

**Comment by AkihiroSuda** [comment]
I suppose this issue is closable, as this issue is about CLI.

If this is still problem, could you reopen at docker/cli repo?
