### ISSUE TITLE
Synchronous (interactive) docker stack deploy 

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32367]
Since we now do support synchronous and interactive service creation using `-d=false` (added in #31144), we should probably support the same in docker stack deploy.

The output would be slightly different:
While for services we should the progress of every single task, for stacks we'd display the overall progress of each service.

/cc @aaronlehmann @dnephin @vieux

**Comment by sirlatrom** [comment]
I recall someone in the #swarm Slack channel mentioned `docker stack rm` as another candidate for a `--detach=false` flag, as they experienced `stack rm` followed 'too fast' by `stack deploy` would race for the creation/removal of networks, possibly other stack resources.

**Comment by soumyadipDe** [comment]
+1..

**Comment by aluzzardi** [comment]
/cc @aaronlehmann

Kinda thinking we should probably provide these options directly from the
client. It would make testing much easier

/cc @dperny

(We'd need something like a status channel for the CLI to display all the
magic)

**Comment by FrenchBen** [comment]
Bump to adding `--detach` as a flag for `docker stack deploy`

**Comment by dnephin** [comment]
Closing this issue as a duplicate of https://github.com/docker/cli/issues/373 , this will be implemented in docker/cli
