### ISSUE TITLE
Future request for command like "docker system status"

### ISSUE THREAD

**Issue by Alessar** [moby/moby#32371]
Sometimes when docker try doing many operations (build containers or download images) looks like docker has stoped and doing nothing (and responces from docker service have very long time).  
There is comand ```docker system events``` which shows log of events which already happend. But if current operation is very long I cannot say it continues or docker stoped due to something failures.  
So it will be good if some command will appear like ```docker system status``` or ```docker system current``` which can show current operation and their status and approxymately percent of execution.  
For example: ```Downloading image name:tag. 45% completed``` or ```Build container name. Current build step 4 of 11```. So in that case I can invoke this command in 5 minutes and can see that downloading image completed on 50% and I can understand that docker is working and I need to patiently wait.

**Comment by cpuguy83** [comment]
Yep, would be pretty cool.
This is not a small/easy task, though.

**Comment by thaJeztah** [comment]
- related https://github.com/moby/moby/issues/45434

Let me close this ticket for now, as it looks like it went stale.
