### ISSUE TITLE
README for hack folder

### ISSUE THREAD

**Issue by Puneeth-n** [moby/moby#32373]
There are several scripts in the [hack folder](https://github.com/docker/docker/tree/master/hack). It definitely deserves a good README 😄

**Comment by thaJeztah** [comment]
Don't think we've come around to that :sweat_smile:, but contributions for this are welcome :+1:

**Comment by JunoJunho** [comment]
I also think that we need this document.
If anyone can give me a cool hint, I can do this.

**Comment by thaJeztah** [comment]
Heh, it's probably best to go through the top-level directories and see what they do / what they're used for (some of them have a README), and make a short summary

**Comment by abhishek7** [comment]
@JunoJunho please let me know if you're already working on this. Would love to give this a try, or a helping hand if I can :)

**Comment by JunoJunho** [comment]
@abhishek7 I think it would be better you try this document. :)

**Comment by abhishek7** [comment]
Thank you @JunoJunho, will give it a try and keep everyone updated!

#dibs

**Comment by abhishek7** [comment]
Just opened a PR here: https://github.com/docker/docker/pull/32637

I'm more than happy to continue to refine with additional iterations; wanted to show this to everyone as there is always room for improvement.

A couple of things to note:
- A handful of the scripts have tons of documentation, would we want to trim this down a bit in this PR? Maybe a separate issue could be raised under the exp/beginner label?
- As I was reading through some of the scripts, it appears that we could clean a few of them up. Perhaps another issue for this as well?

**Comment by gbraad** [comment]
Surely believe more information is needed, but I put some of my comments on the PR #32730 . If you have any further questions, let me know.

Note: BTW, next time you would not have to create a new branch... you could actually use `git push --force` to update the contents of the current PR branch. Again, if you need some help, just let me know. :-)

**Comment by abhishek7** [comment]
Updated the PR based on the review. Feedback always appreciated.

**Comment by krasi-georgiev** [comment]
not sure if the workflow has changed a lot but I did a quick video 1 month ago to help new contributors for a quick step by step 
https://youtu.be/8bic_Wtv8ZI

hopefully now with the Moby breakdown the process becomes  with less plumbing and hacking scripts

**Comment by abhishek7** [comment]
@krasi-georgiev thanks, I'll take a look at this sometime tomorrow.

Currently facing the below issue with the build:

`20:35:00 ----------------------------------------------------------------------
20:35:00 FAIL: check_test.go:355: DockerSwarmSuite.TearDownTest
20:35:00 
20:35:00 unmount of /tmp/docker-execroot/d70a7903e7522/netns failed: invalid argument
20:35:00 unmount of /tmp/docker-execroot/d70a7903e7522/netns failed: no such file or directory
20:35:00 check_test.go:360:
20:35:00     d.Stop(c)
20:35:00 daemon/daemon.go:392:
20:35:00     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
20:35:00 ... Error: Error while stopping the daemon d0315b6972c63 : exit status 2
20:35:00 
20:35:00 
20:35:00 ----------------------------------------------------------------------`

**Comment by abhishek7** [comment]
Looks like this was already merged: https://github.com/moby/moby/pull/32730 

Shall we close this issue since it has been resolved?

**Comment by thaJeztah** [comment]
Yes, this can be closed now that https://github.com/moby/moby/pull/32730 was merged. Thanks @abhishek7 !
