### ISSUE TITLE
Host became unreachable after "docker swarm leave --force" and "docker node ls"

### ISSUE THREAD

**Issue by y2kenny** [moby/moby#32389]
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I created a 3 node swarm with init and join then I tried destroying the swarm.  I first issued swarm leave on the worker and then issued swarm leave --force on the manager.  The manager host became unreachable after "docker swarm leave --force" and "docker node ls".  I got disconnected after the node ls but I am not sure if that's because of the node ls or just a delayed effect of the leave --force.

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: atlvelksp02
ID: F6LE:AEBG:RZOT:QULN:4BMF:RQUP:HCAH:5BDS:NFFP:MKQC:CQZ3:IDQU
Docker Root Dir: /data/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
do you still have daemon logs available from the time that this happened?

**Comment by y2kenny** [comment]
Unfortunately not, we have rebooted the machine.  (Unless there are other ways to find the log?)

**Comment by thaJeztah** [comment]
they're probably still around if you view them with `journalctl -u docker.service` (or `journalctl -xu docker.service` IIRC that one makes sure they're not truncated)

**Comment by y2kenny** [comment]
Um... I only see the start up log with those commands.  I will come back if I run into this again.

**Comment by kevinobriendotca** [comment]
Just hit this as well.  Lucky it's on an Oracle x5-2 with ILOM or I'd be walking to the DC.

[root@gateway-appliance docker]# docker swarm leave
Error response from daemon: You are attempting to leave the swarm on a node that is participating as a manager. Removing the last manager erases all current state of the swarm. Use `--force` to ignore this message.
[root@gateway-appliance docker]# docker swarm leave --force

After that I can't even SSH into the box.  Then the box crashed and rebooted.  BRUTAL.

# last
root     pts/0        10.7.42.100      Wed Sep  6 11:18   still logged in   
reboot   system boot  3.10.0-514.26.2. Wed Sep  6 11:09 - 11:21  (00:11)    
root     pts/0        10.7.42.100      Wed Sep  6 10:08 - crash  (01:01)

No logs from before the crash.

# journalctl -xu docker.service

-- Logs begin at Wed 2017-09-06 11:09:35 PDT, end at Wed 2017-09-06 11:20:01 PDT. --
Sep 06 11:09:52 gateway-appliance systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Sep 06 11:09:52 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:52.839500319-07:00" level=warning msg="libcontainerd: makeUpgradeProof could not open /var/run/docker/
Sep 06 11:09:52 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:52.855621807-07:00" level=info msg="libcontainerd: new containerd process, pid: 2408"
Sep 06 11:09:53 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:53.896993273-07:00" level=info msg="[graphdriver] using prior storage driver: overlay"
Sep 06 11:09:53 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:53.986553486-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Sep 06 11:09:53 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:53.987779728-07:00" level=info msg="Loading containers: start."
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.375998797-07:00" level=info msg="Removing stale sandbox ingress_sbox (ingress-sbox)"
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.411687234-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.474173787-07:00" level=info msg="Loading containers: done."
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.679012598-07:00" level=info msg="Listening for connections" addr="[::]:2377" module=node node.id=s5
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.679016272-07:00" level=info msg="Listening for local connections" addr="/var/run/docker/swarm/contr
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.979930408-07:00" level=info msg="49945538934b3d62 became follower at term 2" module=raft node.id=s5
Sep 06 11:09:54 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:54.979992105-07:00" level=info msg="newRaft 49945538934b3d62 [peers: [], term: 2, commit: 468, applied
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.081730264-07:00" level=info msg="49945538934b3d62 is starting a new election at term 2" module=raft
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.081804122-07:00" level=info msg="49945538934b3d62 became candidate at term 3" module=raft node.id=s
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.081823972-07:00" level=info msg="49945538934b3d62 received MsgVoteResp from 49945538934b3d62 at ter
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.081847792-07:00" level=info msg="49945538934b3d62 became leader at term 3" module=raft node.id=s56m
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.081859036-07:00" level=info msg="raft.node: 49945538934b3d62 elected leader 49945538934b3d62 at ter
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.082355515-07:00" level=error msg="failed to create predefined network bridge" error="name conflicts
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.082392312-07:00" level=error msg="failed to create predefined network host" error="name conflicts w
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.786868876-07:00" level=info msg="Daemon has completed initialization"
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.786913120-07:00" level=info msg="Docker daemon" commit=874a737 graphdriver=overlay version=17.06.1-
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.786913459-07:00" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=10.7.
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.787000964-07:00" level=info msg="Gossip cluster hostname gateway-appliance-3e4818c4211a"
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.788737513-07:00" level=info msg="Node gateway-appliance-3e4818c4211a/10.7.42.32, joined gossip clus
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.788827670-07:00" level=info msg="Node gateway-appliance-3e4818c4211a/10.7.42.32, added to nodes lis
Sep 06 11:09:55 gateway-appliance dockerd[1416]: time="2017-09-06T11:09:55.800989707-07:00" level=info msg="API listen on /var/run/docker.sock"
Sep 06 11:09:55 gateway-appliance systemd[1]: Started Docker Application Container Engine.
-- Subject: Unit docker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished starting up.
-- 
-- The start-up result is done.

**Comment by ozlevka-ericom** [comment]
+1
Only kill to daemon is free from trap

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
