### ISSUE TITLE
detect markdown deadlinks on CI

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#32394]
For example, hyperlink for ["Docker build with --squash argument"](https://github.com/docker/docker/blob/bd811aa4fde8632197c96ca3a7af039789768107/experimental/docker-build-with-squash.md) is broken: https://github.com/docker/docker/blob/bd811aa4fde8632197c96ca3a7af039789768107/experimental/README.md

Can we detect such deadlinks on CI?

**Comment by prertik** [comment]
fixed it.

**Comment by thaJeztah** [comment]
We had this, but with the docs being split over this repo and the docker.github.io repo, I don't think it's possible anymore

**Comment by AkihiroSuda** [comment]
I agree we cannot verify everything, but can we still verify deadlinks for local files?

**Comment by aashutoshrathi** [comment]
So we can't update this link ? 😕 
@thaJeztah

**Comment by AkihiroSuda** [comment]
closing, as most docs are no longer part of this repo
