### ISSUE TITLE
How to increase disk storage made available to containers?

### ISSUE THREAD

**Issue by michipili** [moby/moby#32408]
**Description**

On my system fresh containers see a base device storage size of about 10G. How can I change this size? I am using the devicemapper backend.

I eventually figured it out but I'll document my **Solution** below. The **docker** team will probably add useful comments to this.

**Solution**

The two relevant bits of documentation  are, first from [the User guide](https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/#related-information):

> With devicemapper the high level process for creating images is as follows:
> 
> The devicemapper storage driver creates a thin pool.
> 
> The pool is created from block devices or loop mounted sparse files (more on this later).
> 
> Next it creates a base device.
> 
> A base device is a thin device with a filesystem. You can see which filesystem is in use by running the docker info command and checking the Backing filesystem value.
> 
> Each new image (and image layer) is a snapshot of this base device.
> 
> These are thin provisioned copy-on-write snapshots. This means that they are initially empty and only consume space from the pool when data is written to them.

and second, this excerpt from [dockerd](https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options) documentation:

> **dm.basesize**
> 
> Specifies the size to use when creating the base device, which limits the size of images and containers. The default value is 10G. Note, thin devices are inherently “sparse”, so a 10G device which is mostly empty doesn’t use 10 GB of space on the pool. However, the filesystem will use more space for the empty case the larger the device is.
> 
> The base device size can be increased at daemon restart which will allow all future images and containers (based on those new images) to be of the new base device size.

Therefore in order, to grant containers access to, say, 200G of storage space we need to

1. Arrange to that the *dockerd* is started with `--storage-opt dm.basesize=200G`
2. Ensure that the container that need to access that much space is created from an image that has been created (e.g. pulled) after that setting being active. (Which is IMHO a rather non-obvious point.)

On a freshly configured machine, modifying the *dockerd* setting alone will do, but in other situations, the local docker image library might need to be brushed up.

**Reproduction scenario**

1. Arrange to that the *dockerd* is started with `--storage-opt dm.basesize=200G`
2. Restart the docker daemon
3. Validate your change with `docker run -it --rm debian:jessie df -h /`  This displays 10G, reflecting the previous setting for *dm.basesize* as for when the *debian:jessie* image has been created.
4. Delete `debian:jessie` and repull it
3. Validate your change with `docker run -it --rm debian:jessie df -h /` This displays 200G, the expected value.

**Output of `docker version`:**

```
Docker version 1.12.6, build 7392c3b/1.12.6
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 193.3 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 564.1 MB
 Data Space Total: 238.3 GB
 Data Space Available: 237.7 GB
 Metadata Space Used: 307.2 kB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 24.86 MB
 Thin Pool Minimum Free Space: 23.83 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.41-36.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.862 GiB
Name: ip-172-16-0-215
ID: QKW2:JORB:Q5NL:S4OA:GLAS:VWHJ:7NLU:YLCE:HMEL:RLNY:5XAH:MPRO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: XXXXXXXX
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by johnsushant** [comment]
"Ensure that the container that need to access that much space is created from an image that has been created (e.g. pulled) after that setting being active. (Which is IMHO a rather non-obvious point.)"

Thank you very much for writing this. You're a lifesaver. Wasted quite sometime before I stumbled upon point 2 of your post.

**Comment by thaJeztah** [comment]
If you’re on a recent kernel, using the overlay2 storage driver would be a good alternative as well, as it doesn’t have this limitation, and doesn’t require special setup/configuration

**Comment by zeigerpuppy** [comment]
thanks for this tip, it's really not obvious!
