### ISSUE TITLE
Stopping docker logs with CTRL-C while it’s still printing output kills stdout for the container

### ISSUE THREAD

**Issue by praoreo** [moby/moby#32445]
If we use docker logs to view the logs of a container, and the container is outputting a lot of logs, and we kill docker logs with CTRL-C while it’s still printing output, we see that it kills stdout for the container.

This issue is seen with docker-engine version of 1.13.1-0~ubuntu-xenial.

Steps to reproduce the issue.

1) Start docker container as below.
	docker run -t -i ubuntu:14.04 /bin/bash
	
2) Execute the below with in the container so that it starts outputting data into stdout.
	/bin/bash -c i=0; while true; do echo "$i: $(date)"; i=$((i+1)); done
	
3) In another terminal do the following.
	docker logs <above_container_id>
	
4) Hit Ctrl-C in the console while docker logs in step 3 is outputting data.
5) Repeat step 3 and step 4 couple of times and you will see at one point that docker will stop logging data into stdout.

Has any one faced similar issue while using docker? Is their any solution for the issue? 
This issue is not seen in 1.12.6 docker version.

**Comment by cpuguy83** [comment]
Thanks for reporting, this is already fixed in 17.03 (which is what 1.13.2 would have been).
Can you try with 17.03.1?

**Comment by skamenetskiy** [comment]
Can reproduce in 17.09.1-ce

**Comment by simon-s9** [comment]
No, sorry. Mine is a bit different, `CTRL+C` doesn't work on `docker service logs --follow ...`. Guess it should be another ticket.

**Comment by thaJeztah** [comment]
Not able to reproduce that as well;

```bash
$ docker service create --name foo busybox sh -c 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); done' 


$ docker service logs --follow foo
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10504: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10505: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10506: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10507: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10508: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10509: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10510: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10511: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10512: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10513: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10514: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10515: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10516: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10517: Thu Dec 21 13:44:28 UTC 2017
foo.1.z6z9licwsuqg@linuxkit-025000000001    | 10518: Thu Dec 21 13:44:28 UTC 2017
^C
```

**Comment by skamenetskiy** [comment]
@thaJeztah maybe there's something wrong with my env. I'll double check and get back to you with more details.

Thanks

**Comment by maksimyugai** [comment]
Same problem: can't stop docker logs -f nginx by Ctrl+C.

Docker version 17.05.0-ce, build 89658be

**Comment by thaJeztah** [comment]
@maksimyugai Docker 17.05 is really old, reached EOL nearly 3 years ago, and has known critical vulnerabilities (including container escapes which could give `root` access to your host). I _highly_ recommend upgrading to a current version.

I just tried reproducing the issue on Docker 19.03.5, and was not able to (both the `docker logs -f` and `docker service logs` cases), but was not able to reproduce the issue.

I'll close this ticket, but if you're able to reproduce on a current version of Docker, feel free to open a _new_ ticket with the details requested in the issue template, including exact steps to reproduce.
