### ISSUE TITLE
Support updating pids-limit in docker update

### ISSUE THREAD

**Issue by tswift242** [moby/moby#32443]
**Description**

```docker update``` does not seem to support pids-limit. At the moment, my particular use case is working around https://github.com/docker/docker/issues/32442. Using ```docker update``` after restoring a container seems like the perfect workaround. While this works great for some of the cgroup limits I set, pids-limit is not supported. I imagine there could be other use cases as well.

**Steps to reproduce the issue:**
1. docker run --name test -d --rm ubuntu:14.04 /bin/bash -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 5; done'
2. docker update --pids-limit=1000 test

**Describe the results you received:**
unknown flag: --pids-limit
See 'docker update --help'.

**Describe the results you expected:**
Should be able to update pids-limit of running container.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.10.5-041005-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.94 GiB
Name: ip-10-97-3-17
ID: G3FR:5WAN:LTDA:O5EK:HAOA:3RJG:JKU5:HBDD:TTG5:GASD:PLMB:CFIK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by snowsky** [comment]
got same issue with 1.13

**Comment by thaJeztah** [comment]
@snowsky this is a feature request, not a bug report, so it's expected to not be there on any version released so far
