### ISSUE TITLE
Proposal: Independent RUN command in Dockerfile

### ISSUE THREAD

**Issue by Piping** [moby/moby#32454]
**Description**

Is there a way to RUN each command independently rather than re-execute simply because the order of RUN command is changed in docker file?

**Describe the results you received:**

For example, `RUN wget url-one` and  `RUN wget url-two`, apparently those two lines does not depend on each other as far as for the one who wrote the Dockerfile, but docker will re-download everything if the order changed. This becomes a big problem when the run command is time consuming, such as build compiler from source code. 

**Describe the results you expected:**

Is that possible to run a command independently in a Docker file that is only depend on base image rather than previous command?? So the layer can be cached and reused.

**Comment by AkihiroSuda** [comment]
`apparently those two lines does not depend on each other` is not apparent without knowledge about `wget`.

Instead, dependency could be expressed using multi-stage Dockerfile
https://github.com/docker/docker/pull/31257

```dockerfile
FROM busybox AS foo-one
RUN wget url-one

FROM busybox AS foo-two
RUN wget url-two

# main depends on foo-one and foo-two;
# no dependency between foo-one and foo-two
FROM busybox AS main
COPY --from=foo-one /url-one /url-one
COPY --from=foo-two /url-two /url-two
```

**Comment by Piping** [comment]
@AkihiroSuda The Point here is that programmer knows it is safe and can be run independently. So docker should allow programmer to have choice to do so with some keywords??

**Comment by thaJeztah** [comment]
I'm not sure the current implementation would allow this easily, i.e., the "cache" is still a chain, so swapping those lines will automatically create a new "path" in the cache/history.

**Comment by thaJeztah** [comment]
Let's close this; some cases could be solved through multi-stage builds (assuming there's no dependency at all between them) and `COPY --link`
