### ISSUE TITLE
Need to prevent one host user accessing container launched by another user

### ISSUE THREAD

**Issue by yashgt** [moby/moby#32459]
If a user named user1 logs in to the host and launches a container, the container is hosted by the docker engine. The user1 need not be in any special group or a sudo user. While issuing the docker run command user1 may provide -u switch to let the process within the container run as a non-root user.

Now if user2 does a docker ps and sees the container started by user1, he can docker exec into the container without using -u and get root access of the container.

This needs to be prevented.

1. Login to the Host as user1
2. Run the command : docker run busybox
3. Login as user2 on another terminal
4. Enlist the containers started by all users using : docker ps
5. Connect to the container started by user1 using: docker exec -it bash
6. Kill the process in the conatiner

The container started by user1 was killed by user2.

The docker engine should provide a way to:
Prevent user2 from firstly seeing the containers started by other users.
Even if user2 gets to know the container ID, he should not be allowed to exec into the container started by user1.

This is on docker 1.13.

**Comment by cpuguy83** [comment]
> The user1 need not be in any special group or a sudo user

This is not true unless you've setup Docker in an insecure manner.
By default docker listens on a unix socket such that only the root user and users in the `docker` group are able to access the socket.

Please see https://docs.docker.com/engine/extend/plugins_authorization/
Authorization plugins allow fined grained control of API access.

**Comment by thaJeztah** [comment]
I think what's requested here, is "multi-tenant" support in the docker daemon (i.e., user 1 can start a container, but user 2 cannot see, or manage that container).

This is not something that's currently supported, although (for example) Docker DataCenter (part of Docker EE "standard") has role based access control, and may be worth having a look at.

**Comment by yashgt** [comment]
@cpuguy83 . I read the steps at https://docs.docker.com/learn/ as well as rest of the documentation. The docs no longer state that a docker group is needed and all users wanting to access docker commands should be part of the group.

**Comment by cpuguy83** [comment]
@yashgt I'm not sure what you are asking for here?

**Comment by yashgt** [comment]
@cpuguy83 As per your comment, a user needs to be in the docker group to be able to access docker. However, I am not able to find any current documentation of docker engine that states that a docker group needs to be created and users need to be added under the docker group.

**Comment by thaJeztah** [comment]
The instructions can be found here; https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user. However, that configuration is only required if you connect to the daemon through the socket, if connecting through a tcp-connection, it may not be needed.

I'm not really sure how this relates to your original question though; keep in mind that the _daemon_ always runs as "root", and any container created through the remote API (which is what the CLI does), is not "owned" by a particular user.

**Comment by yashgt** [comment]
@thaJeztah The documentation says: The docker daemon binds to a Unix socket instead of a TCP port.
If this is the case, all users on the host should have been forced to either be in the docker group or work using sudo. But in my case, any user, is being able to use the docker commands. I am not sure where and how I need to configure docker engine to listen on the socket.

This is related to the original issue because I want my containers to be safe and avoid any unprivileged user connecting to them. This is my second best option compared to a setup where we can have multi-tenant docker engine.

**Comment by thaJeztah** [comment]
@yashgt you did not provide any information about your setup;

- full output of `docker version`
- output of `docker info`

> But in my case, any user, is being able to use the docker commands.

- What's the ownership and permissions of the socket (`/var/run/docker.sock`)?
- Are any custom daemon options set (either through a `daemon.json` configuration file or a custom unit-file)?

**Comment by dewang-agrawal** [comment]
Docker version:
![docker version](https://cloud.githubusercontent.com/assets/23662828/25087520/3215d274-238d-11e7-97a2-33bbe8f359db.PNG)
Docker info:
![docker info 1](https://cloud.githubusercontent.com/assets/23662828/25087529/375d5c5c-238d-11e7-9f5c-66f891ea8675.PNG)
![docker info 2](https://cloud.githubusercontent.com/assets/23662828/25087537/3bbf5836-238d-11e7-8a1f-cdc365565421.PNG)

The owner of file /var/run/docker.sock is root with permission 660.

And we have changed the root of docker runtime i.e. dockerd -g /xfs100.

**Comment by thaJeztah** [comment]
> The owner of file /var/run/docker.sock is root with permission 660.

What group is it owned by? From the above, only root, and users in the same group should have access to that socket?

**Comment by dewang-agrawal** [comment]
docker.sock is owned by root group

**Comment by dewang-agrawal** [comment]
all the users where member of root group and docker.sock file was also owned by root group.

**Comment by bacTlink** [comment]
This is quite a problem.
It is reasonable that user1 and user2 can both run docker and they can only access the containers start by themselves.
I am now running a web server container and I have no right to prevent other users from using docker. But I definitely don't want anyone stop my container.
Is there any solution now?

**Comment by thaJeztah** [comment]
Not with the core functionality of the Moby/Docker Engine; multi-tenant support and user-management / role-based access control is out of scope for this repository, but platforms , such as Docker Enterprise Edition provide that functionality

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
