### ISSUE TITLE
Authorization plugin is not triggered

### ISSUE THREAD

**Issue by artsf** [moby/moby#32489]
I built a sample plugin using "github.com/docker/go-plugins-helpers/authorization" package.
See https://github.com/artsf/docker-auth-test and it is not getting triggered.
Plugin builds, created and enabled OK, but then it just doesn't work at all.
It does not produce any stdout output and does not block any images from running.

Did I miss anything?

OS:
Mac OS X 10.11.6 (build: 15G1421)

Go:
go version go1.8 darwin/amd64

Docker:
Docker version 17.03.1-ce, build c6d412e

Docker UI:
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

Diagnostics:
```
Docker for Mac: version: 17.03.1-ce-mac5 (b18e2a50c)
macOS: version 10.11.6 (build: 15G1421)
logs: /tmp/2439AFEC-179A-4471-9766-DEEE420D4146/20170405-165618.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

**Comment by artsf** [comment]
This is a blocker for us :(

**Comment by artsf** [comment]
I think the bug is mislabeled: in case of CentOS 7 the plugin doesn't even start (`docker enable` does not make plugin enabled)

**Comment by thaJeztah** [comment]
I think there's a couple of issues that may be at hand here;

- first of all, it seems you're _building_ the plugin on your Mac. As a result, the binary that's built is a _mac_ binary, not a linux binary, and it will fail to start when installed (the docker _daemon_ is running on Linux). You can consider building the plugin inside a container, and have it write the binary that's produced to a bind-mounted directory on your host (or use `docker cp` to copy the binary out of the container and onto your host.
- there's an issue with _disabling_ authz plugins in docker 17.03; see https://github.com/docker/docker/issues/31836

**Comment by artsf** [comment]
I updated the go compiler to compile for Linux and it still doesn't work.
What else did I miss? Why compiling in a container so different?

**Comment by thaJeztah** [comment]
If you build in a container, you're building on a Linux system, which _could_ make a difference (compared to cross compiling). If you put the binary that you built in a container, and try to manually run it, does it work?

**Comment by artsf** [comment]
The way I made it work is I compile in Linux (as you are suggesting) AND I copy all files of ArchLinux to the plugin. This is so weird, why plugins can't be just a docker image?

**Comment by thaJeztah** [comment]
Plugins can be distributed as docker images, but have to be built first; https://github.com/moby/moby/blob/v17.05.0-ce/docs/reference/commandline/plugin_push.md

> The way I made it work is I compile in Linux (as you are suggesting)

It's a bit unfortunate that these extra steps are needed, but the point is that you're developing a _linux_ plugin for it to run in Docker, not a macOS plugin. Perhaps there's ways to make this easier.

> AND I copy all files of ArchLinux to the plugin

Can you explain what files you had to copy to the plugin?

> The way I made it work

So you managed to get it working in the end?

**Comment by artsf** [comment]
I followed the working example from here: https://github.com/vieux/docker-volume-sshfs/blob/master/Makefile#L25 to copy ALL files from Alpine OS: https://github.com/vieux/docker-volume-sshfs/blob/master/Dockerfile#L1

Yes, https://github.com/vieux/docker-volume-sshfs was the example of a working plugin which was the base of an authz plugin which worked. However, issues still stay for this ticket:

1. Can't compile image for Linux on Mac (although advertised as if you could for Golang, looks like a Golang issue);
2. You MUST copy ALL files from your base OS (Alpine in my case) to the plugin's rootfs folder. You can't build on top of the Alpine image - it is NOT supported. Neither you can avoid copying all OS files.

Additionally, the plugin is treated as a different entity and NOT an image. You can't push it, you must do `plugin push` which is not supported by Artifactory.

**Comment by salzig** [comment]
I've a similar problem. The Plugin is enabled and reachable via unix socket, also there is some starting log messages visible in the daemon logs. 

```
$ docker plugin ls
ID                  NAME                DESCRIPTION            ENABLED
6b56cbf5ffa2        auster:latest       Auster (Auth) Plugin   true
```

```
curl --unix-socket /run/docker/plugins/6b56cbf5…/auster.sock http://docker/Plugin.Activate
{"Implements": ["authz"]}
```

but i can't see docker using it. Is it still required to add `--authorization-plugin` to the daemon additionally?

**Comment by salzig** [comment]
A short test shows that after adding `--authorization-plugin` to the docker daemon configuration, the daemon starts to communicate with the authorization plugin. But disabling the plugin, dosen't stop dockerd from trying to authorize using that plugin, which fails. 

Shouldn't it be enough to enable/disable docker auth plugins?

**Comment by thaJeztah** [comment]
> But disabling the plugin, dosen't stop dockerd from trying to authorize using that plugin.

@salzig what version of docker are you running? I think there was a fix for that in docker 17.05; https://github.com/moby/moby/pull/31930

**Comment by salzig** [comment]
@thaJeztah had that problem with an xhyve based machine locally. Tried it with a new (17.05) one, and it works.

**Comment by salzig** [comment]
but reenabling is still not possible? How is upgrading supposed to work?

**Comment by thaJeztah** [comment]
Looks like the questions here are answered, so I'll close this issue
