### ISSUE TITLE
Unexpected changes to formatting of human-readable resource values

### ISSUE THREAD

**Issue by nmeyerhans** [moby/moby#32499]
**Description**

Docker 17.04.0 introduces an unexpected change to the human-readable formatting of capacity numbers as reported by `docker info`. In 17.03.1 CE and earlier, values in `docker info` output have a space between the number and the unit, e.g. `990.8 MiB`. Starting with 17.04.0, the space separating the number from the unit has been removed, e.g. `990.8MiB`. This can potentially break scripts or monitoring systems that attempt to parse these values.

On systems using the `devicemapper` storage driver, this change impacts both the `docker info` command output as well as the JSON-formatted output of the `info` API call. All API versions are impacted by this.

**Steps to reproduce the issue:**
The simplest way to reproduce this is by looking at the `Total Memory` line in the `docker info` output.

1. Launch two Fedora instances on AWS.
2. Install docker per https://docs.docker.com/engine/installation/linux/fedora/
  1. Set up one VM with "edge" enabled and ensure that docker 17.04.0-ce is installed.
  2. Set up the other VM without "edge", such that docker 17.03.1-ce is installed.
3. Run `sudo docker info | grep 'Total Mem'` on both machines and compare the output. The 17.03.1-ce host will report something similar to `Total Memory: 990.8 MiB` while the 17.04.0-ce host will report something similar to `Total Memory: 990.8MiB`

**Describe the results you received:**

The 17.03.1-ce host will report something similar to `Total Memory: 990.8 MiB` while the 17.04.0-ce host will report something similar to `Total Memory: 990.8MiB`

**Describe the results you expected:**

I expected the numbers to use the same format.

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem is present (and probably most troublesome) in the JSON output of the `info` API call when reporting the details of the `devicemapper` storage driver on systems where that's the driver in use. This is most likely cause problems since the JSON output is expected to be machine-readable and code may need to be updated to cope with the change. For example:

*Docker 17.03.1-ce:*
```
[fedora@ip-172-31-17-31 ~]$ sudo curl -s --unix-socket /var/run/docker.sock http://v1.23/info | jq '.DriverStatus[7]'
[
  "Data Space Total",
  "23.35 GB"
]
```
versus *Docker 17.04.0-ce*
```[fedora@ip-172-31-22-191 ~]$ sudo curl -s --unix-socket /var/run/docker.sock http://v1.23/info | jq '.DriverStatus[7]'
[
  "Data Space Total",
  "23.35GB"
]
```

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 19:14:52 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 19:14:52 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 240.4MB
 Data Space Total: 23.35GB
 Data Space Available: 23.11GB
 Metadata Space Used: 241.7kB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 24.92MB
 Thin Pool Minimum Free Space: 2.335GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.7-300.fc25.x86_64
Operating System: Fedora 25 (Cloud Edition)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.8MiB
Name: ip-172-31-22-191.us-west-2.compute.internal
ID: HUUL:3PDU:ZNVM:KITY:BZUS:46OC:43HS:K6XW:EGJ3:ND4P:UGDI:MUQM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by nmeyerhans** [comment]
Looks like this originates with https://github.com/moby/moby/issues/30271 and the corresponding PR.

I'm not sure the full impact of that change was considered before merging it. While it's nice to have similar output to other tools, it is a user visible change that has the potential to break downstream tools. I can accept that changing the CLI output is considered acceptable, but this also changed API output for all versions of the `info` API. That's much less desirable.

**Comment by friism** [comment]
I agree that this is unfortunate.

The values in question are returned by the devicemapper driver and are part of unstructured, optional data that graph drivers may (or may not) return for `docker info`. The values are not part of the documented, "stable" API output. This is covered in the API docs:

> The API uses an open schema model, which means server may add extra properties to responses.

 - https://docs.docker.com/engine/api/v1.29/#section/Versioning

I agree Docker should be more disciplined about documenting details like this, and about making clear what parts of the API come with what guarantees.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
