### ISSUE TITLE
One link is dead in README.md

### ISSUE THREAD

**Issue by JunoJunho** [moby/moby#32508]
**Description**

One link in README.md file in the root directory of docker repository.
In [the getting the development builds section](https://github.com/docker/docker#getting-the-development-builds) , link "docs.master.dockerproject.org." is dead.

**Describe the results you received:**
Link is dead

**Describe the results you expected:**
I think this link should be linked to docs.master.dockerproject main page.

**Comment by JunoJunho** [comment]
If it is a problem, then I will try to fix this one :)

**Comment by JunoJunho** [comment]
I think this link (docs.master.dockerproject.org) is dead

In the dockerproject master [link](https://dockerproject.org/), it tells us above link is the master documentation, but the response is DNS_PROBE_FINISHED_NXDOMAIN.

I think it would be good to redirect this link to [this link](https://github.com/docker/docker/tree/master/docs) or [this repo](https://github.com/docker/docker.github.io). Which one is more appropriate?

**Comment by JunoJunho** [comment]
ping @AkihiroSuda

**Comment by xdev31** [comment]
We can close this issue :)
