### ISSUE TITLE
mount/umount external usb hard disk on host doesn't take effect in container.

### ISSUE THREAD

**Issue by d0u9** [moby/moby#32512]
I recently setup a Samba server in docker container, and want to share videos and music from an external usb hard disk. I run the container as:

    docker run -d --name samba -p 139:139 -p 445:445 -v /media/usb:/smb_share samba

Obviously, the usb hard disk is mounted on `/media/usb`.

Everything is fine until I umounted the usb driver from host. I noticed that the contents of dir `/smb` in the container is still remaining which I even can modify. Then, I mounted the usb hard disk back, created some files new in `/smb` in the container, inspect the `/media/usb` dir on the host, and nothing changed. All the modifications to the `/smb` dir after a remount take no effect. 

So, how could I sync the dirs between container and host after the usb is mounted and umounted.

Best regards.

---

Supplement info:

Host OS: centos 7
Docker version: 17.03.0-ce, build 3a232c8

Reproduce procedure:

1. Mount external usb hard disk to host via `mount /dev/sdb1 /media/usb`, the file system of the usb disk is xfs.
2. Run container, `docker run -d --name samba -p 139:139 -p 445:445 -v /media/usb:/smb_share samba`, the samba image is build locally. it just starts a samba server and shares the `/smb` dir to samba users.
3. Mount this samba volume on another computer. make some changes on the files in samba shred folder.
4. Unmount the usb hard disk from host, `umount /dev/sdb1`. (It is weird that the host os doesn't warn me that the usb disk is busy)
5. Remount the samba volume on another computer, and all the files are still there. nothing is affected by the umounting of external usb disk.

**Comment by cpuguy83** [comment]
Can you please add all the information requested in the issue template?

Is this docker on Linux (assuming given the path).
How is Docker started? (e.g. systemd, sysvinit, etc).

**Comment by d0u9** [comment]
@cpuguy83 Sorry for my incomplete  commit. I have append the supplement info to the original post.

**Comment by cpuguy83** [comment]
@d0u9 Can you paste the output of `docker version` and `docker info`?

Are you starting docker with systemd? Can you paste the unit file?

**Comment by d0u9** [comment]
@cpuguy83 
docker version:

```
 Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
docker info:

```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 237
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local local-persist
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.7 MiB
Name: localhost
ID: PDFL:5NAJ:IUMB:5CHY:J2LH:5MDF:6DOC:P5VF:V6S3:MZWG:IFJU:3EOB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I installed docker according to the instruction of [docker official documentation](https://store.docker.com/editions/community/docker-ce-server-centos?tab=description), So on Cent OS 7, docker is managed via systemd. 

The systemd unit file is default, I paste it here below:

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target firewalld.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by cpuguy83** [comment]
Have you tried using slave mount propagation?

```
 -v /media/usb:/smb_share:slave
```

**Comment by cpuguy83** [comment]
😢 This used to be in the container docs...

Looks like we have some on the `service create` docs.
https://docs.docker.com/edge//engine/reference/commandline/service_create/#bind-propagation

**Comment by cpuguy83** [comment]
`slave` basically means the mountpoint in the container will receive updated mounts from the host.

**Comment by d0u9** [comment]
Thanks for your patients. @cpuguy83
