### ISSUE TITLE
Windows Container (Hyper-V) not respecting Timezone in Dockerfile

### ISSUE THREAD

**Issue by bemayr** [moby/moby#32518]
**Description**
When I create a Windows Container using a Dockerfile I want to set the timezone to UTC to provide a consistent environment across multiple machines. The container takes the timezone of the host-system regardless of what is specified in the Dockerfile. It seems that the timezone-information is passed into the container at startup. If I run the command in the container and check afterwards the timezone is set correctly.

**Steps to reproduce the issue:**
1. Create Dockerfile as following:
```Docker
FROM microsoft/aspnet
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN Set-TimeZone -id "UTC" # set time zone to UTC
ENTRYPOINT ["powershell"]
```
2. Build and run container with -it switch
3. Execute `Get-TimeZone` in Powershell

**Describe the results you received:**
```shell
Id                         : W. Europe Standard Time
DisplayName                : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
StandardName               : W. Europe Standard Time
DaylightName               : W. Europe Daylight Time
BaseUtcOffset              : 01:00:00
SupportsDaylightSavingTime : True
```

**Describe the results you expected:**
```shell
Id                         : UTC
DisplayName                : (UTC) Coordinated Universal Time
StandardName               : Coordinated Universal Time
DaylightName               : Coordinated Universal Time
BaseUtcOffset              : 00:00:00
SupportsDaylightSavingTime : False
```

**Additional information you deem important (e.g. issue happens only occasionally):**
- I am using the Windows Hyper-V Containers on Windows 10 to create dev-time containers.
- I tried setting the time with `tzutil` too, which makes no difference.
- Maybe this issue is somehow related to #30587. 

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 26
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.89 GiB
Name: PC-03
ID: UPNA:ZVOM:KMDZ:B4PP:WYTX:QKBJ:EVQB:INKJ:HZSO:CKJM:PY6Q:MFSM
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 18
 System Time: 2017-04-11T11:15:28.632328Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thank you very much!

**Comment by friism** [comment]
cc @PatrickLang @johnstep

**Comment by johnstep** [comment]
I think it probably is related to #30587, changing the time zone in the utility VM.

**Comment by thaJeztah** [comment]
This should be resolved in the Windows 1709 update https://github.com/moby/moby/issues/30587#issuecomment-317519142

**Comment by Labrat02** [comment]
It should be.. but was it???

**Comment by thaJeztah** [comment]
@Labrat02 did you try?

**Comment by StuartSmith** [comment]
I tried to run the Power shell command to set my docker host time zone

#Change the timezone on the to UTC
RUN Set-TimeZone -id "UTC" 

It failed with the following
Set-TimeZone : Access is denied
At line:1 char:1
+ Set-TimeZone -id UTC # set time zone to UTC
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Set-TimeZone], Win32Exception
    + FullyQualifiedErrorId : SetTimeZoneFailed,Microsoft.PowerShell.Commands.
   SetTimeZoneCommand

windows version 1803 the docker container that is being built references microsoft/aspnet:4.7.2 the version windows version from docker is 1803 as well.

**Comment by andrew-morgalla** [comment]
Getting the same access denied when I try to set the time within the container too. references the microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803 image.

**Comment by StuartSmith** [comment]
I was thinking this was a permission issue for example if you run
whoami  /priv you receive a list of permissions 

SeTimeZonePrivilege is disabled

SeTimeZonePrivilege                       Change the time zone                                               Disabled

So I created a Command let that changes this permission

SeTimeZonePrivilege                       Change the time zone                                               Enabled

Still the I am unable to update the time zone
