### ISSUE TITLE
Cleaning up Dockerhost with containers left in "Created" or "up x days/hours"

### ISSUE THREAD

**Issue by guylifestyle3** [moby/moby#32527]
I have a situation in which containers are left in "Created" or "up x days".  How can I exit containers that have been left in created state for more than x hours or x days?  This is happening because I use jenkins and when sometimes after the docker jobs are used it is left in created state and not exited.

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
b0ac3cb44d28        sample          "/bin/sh -c 'dbus-dae"   Up 4 days        Created                                     small_montalcini
3f90470decd1        sample          "/bin/sh -c 'dbus-dae"   10 hours ago        Created                                     hungry_noyce
5a816b31a129        sample          "/bin/sh -c 'dbus-dae"   10 hours ago        Created                                     trusting_davinci

I tried this and it doesn't like "Created" status.  I assume I have to stop it and then do rm on it.
docker ps --filter "status=Created" | grep 'Up 4 days' | awk '{print $1}' | xargs --no-run-if-empty docker stop >/dev/null 2>&1
Error response from daemon: Unrecognised filter value for status: Created

docker ps --filter "status=Created" | grep 'Up 4 days' | awk '{print $1}' | xargs --no-run-if-empty docker rm >/dev/null 2>&1
Error response from daemon: Unrecognised filter value for status: Created

I just do docker stop $(docker ps -q) and then followed by docker rm ...

**Comment by 46472761** [comment]
JAMES LACONIA DAVIS
46472761
TRIPLE ELITE
REQUESTING PAYMENT.OFFERED.  $ 3,000,000,000,000.00

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.

**Comment by bsousaa** [comment]
note that the filter should be lowercase i.e. "status=created". More details in the [docs](https://docs.docker.com/engine/reference/commandline/ps/#status).
