### ISSUE TITLE
daemon.json with default-ulimits rejected

### ISSUE THREAD

**Issue by dsheets** [moby/moby#32528]
**Description**

Putting `{ "default-ulimits": {} }` in `daemon.json` results in `dockerd` failing to start and logging

```
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: default-ulimits
```

**Steps to reproduce the issue:**
1. Edit `daemon.json` to contain `{ "default-ulimits": {} }`
2. Start `dockerd`

**Describe the results you received:**

`dockerd` does not start and complains that `default-ulimits` is unknown.

**Describe the results you expected:**

`dockerd` starts.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue seems very strange to me as it appears to be tested in [daemon/config/config_unix_test.go](https://github.com/docker/docker/blob/f3a8886d8890d6797a568ab316baf9400ee2e1e1/daemon/config/config_unix_test.go#L23-L29). I see the same error in the logs when I use exactly the configuration in that test so I'm not certain what/if/how that test is passing.

It looks like [daemon/config/config.go line 404](https://github.com/docker/docker/blob/f3a8886d8890d6797a568ab316baf9400ee2e1e1/daemon/config/config.go#L404) is the source of the error message and [lines 386-397](https://github.com/docker/docker/blob/f3a8886d8890d6797a568ab316baf9400ee2e1e1/daemon/config/config.go#L386-L397) are supposed to have handled the case where the config option (`default-ulimits`) and the command line argument (`--default-ulimit`) differ except `opts.UlimitOpt` does not appear to fulfill `opts.NamedOption` and does not appear to ever have. Even more strangely, this seems to have worked in the past and I can't find any obvious changes in the relevant files that would have broken this.

I would also expect other issue reports regarding this and so I'm strongly considering the possibility that I've done something wrong. If I have done something wrong, I believe this is a usability problem 
and still constitutes a bug.

There appears to be a history of problems with this configuration field:
 * #29385
 * #22309
 * #25566

This issue was originally reported at docker/for-mac#1513.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 06:06:36 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.19-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: LBRL:MJIS:5WS3:NVTP:MYHG:DD54:XVPJ:CQN6:TWVY:XL4Y:WPDX:PKAD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-04-11T15:17:48.302951361Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: dsheets
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Also tried on 1.13.0, build 49bf474f9 on Debian Linux:

```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474f9
 Built:        Tue Jan 17 09:52:33 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474f9
 Built:        Tue Jan 17 09:52:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 500
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-8913512-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 44.5 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39.98 GB
 Metadata Space Used: 41.22 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.106 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.127 (2016-06-11)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.3.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.699 GiB
Name: debussy
ID: ECNR:42Z2:ZJ2R:LKMC:ZQDL:JQLC:YHMP:XO6Z:M53C:CC3J:DSGX:VGQ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: yallop
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by allencloud** [comment]
Thanks @thaJeztah 
I will take a look asap.

**Comment by allencloud** [comment]
> opts.UlimitOpt does not appear to fulfill opts.NamedOption

What you said is totally reasonable. @dsheets 

It seems that `UlimitOpt` did not implement the function `Name()`, so we cannot regard it implement the interface, then it will be treated as an unknown key.

> Even more strangely, this seems to have worked in the past and I can't find any obvious changes in the relevant files that would have broken this.

I feel strange, too. But I have not traverse everywhere yet. 

Opened a pr https://github.com/docker/docker/pull/32547 to fix it, but still WIP.
