### ISSUE TITLE
download.docker.com redirects to HTTPS (not compatible with caching proxy)

### ISSUE THREAD

**Issue by arthur-tacca** [moby/moby#32554]
Previously, part of my procedure for setting up Docker on a new machine was to follow the [usual instructions](https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository) but change "https:" to "http:". It doesn't make any sense to use an encrypted channel for installing packages: It doesn't have any advantages because there's no need to keep your package downloads secret, and if a man-in-the-middle tampers with the package it will be discovered when apt verifies its signature. But it does have a critical disadvantage: it prevents caching (e.g. using [apt-cacher-ng](https://www.unix-ag.uni-kl.de/~bloch/acng/)). 

When I tried this on a new (virtual) machine recently, I got the following error when running `apt-get update`:

    Err http://download.docker.com trust/stable Translation-en
      Bad header line

It seems that `download.docker.com` does not support raw HTTP at all; any unencrypted requests are redirected to HTTPS, which causes the above error when `apt` is using an HTTP proxy. I notice that the old `apt.dockerproject.org` server still works and doesn't have this problem, but since the installation instructions don't refer to it I'm worried that sooner or later it will be retired. Could `download.docker.com` please be fixed so that it respects unencrypted downloads?

**Comment by cpuguy83** [comment]
ping @andrewhsu

**Comment by NoahO** [comment]
I have this problem also:

As part of my systems testing I spin up and destroy many docker boxes a day through Ansible. This is from my dev laptop, so I run the virtual machines through a squid proxy so that even if I'm on slow wifi, the build process is fast. This breaks my workflow significantly.

**Comment by n4ss** [comment]
Isn't adding:

`PassThroughPattern: download\.docker\.com`

to your `/etc/apt-cacher-ng/acng.conf` possible ?

**Comment by NoahO** [comment]
@n4ss that will exclude it from being cached (pass through only) which doesn't help me cache it.

**Comment by bsousaa** [comment]
I wonder if this use case is still valid today. Let me close it for now. Feel free to comment and we can re-open if needed.
