### ISSUE TITLE
docker servcie ps <service_name> lists all instances of services with names starting with service_name

### ISSUE THREAD

**Issue by fhauptmann** [moby/moby#32556]
**Description**

On Docker 1.17.04 "docker service ps <service_name>" not only lists all instaces of the service named <service_name> but additionally lists all services with names starting with <service_name>. 

**Steps to reproduce the issue:**
1. Create a docker swarm
2. Login to a swarm manager
3. $ docker service ps app_partner

**Describe the results you received:**
$ sudo docker service ps "app_partner"
ID                  NAME                    IMAGE                                                   NODE                                     DESIRED STATE       CURRENT STATE             ERROR               PORTS
hhip3olcnga3        app_partner-data.1      lop-ueb-docker-01:15000/partner-data:17.56.90b0b6d      dockerhost-06.mydomain   Running             Running 34 minutes ago
o35af2w7gf2s        app_partner-prozess.1   lop-ueb-docker-01:15000/partner-prozess:17.25.48bb90b   dockerhost-07..mydomain   Running             Running 38 minutes ago
zesd22nicdc2        app_partner-data.1      lop-ueb-docker-01:15000/partner-data:17.55.f8f6f23      dockerhost-06..mydomain   Shutdown            Shutdown 34 minutes ago
zll16gs64ris        app_partner-suche.1     lop-ueb-docker-01:15000/partner-suche:17.42.a5d2592     dockerhost-07..mydomain   Running             Running 21 hours ago
ldorwz8fup88        app_partner-prozess.1   lop-ueb-docker-01:15000/partner-prozess:17.24.48bb90b   dockerhost-05..mydomain   Shutdown            Shutdown 38 minutes ago
wu0n4fbbch24        app_partner-data.1      lop-ueb-docker-01:15000/partner-data:17.54.f8f6f23      dockerhost-06..mydomain   Shutdown            Shutdown 39 minutes ago

**Describe the results you expected:**
$ docker --version
Docker version 1.13.1, build 092cba3

$ sudo docker service ps app_partner
Error: No such service: app_partner

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 17.04.0-ce, build 4845c56

**Output of `docker info`:**

Containers: 22
 Running: 13
 Paused: 0
 Stopped: 9
Images: 23
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: buc0o3zmn249mi513g9hbpm27
 Is Manager: true
 ClusterID: pkof2yjm986ej2f76liebg5vt
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: X.X.1.115
 Manager Addresses:
  X.X.1.115:2377
  X.X.1.116:2377
  X.X.1.117:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: dockerhost-05.mydomain
ID: E2U6:M6ET:CP6Q:GQMF:4YRH:A6YV:E6QK:POST:BA5L:KONL:XPPD:3JUB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry-01:15000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual Machine is running on OpenStack.

**Comment by cpuguy83** [comment]
ping @thaJeztah

**Comment by kinghuang** [comment]
I'm also having the same problem. Pull request #25234 added the option to have multiple service IDs on `docker service ps`. The implementation changed the service lookup from using `ServiceInspectWithRaw` to get an exact service to do a prefix searches against all services. This is causing the behaviour change.

**Comment by dvusboy** [comment]
Here's my experience. The following output has been redacted a bit, but I try to keep the length and pattern identical to the actual output:

```
# docker ps -a
CONTAINER ID        IMAGE                                                                                COMMAND             CREATED             STATUS                  PORTS               NAMES
74c9cccc0e34        registry.rnd.vsn.local/pamc/redactd-abcdefgh:123-456-789-abcde-fghijklmnopq-123456   "/bin/true"         2 days ago          Exited (0) 2 days ago                       pamcredactdabcdefgh_123456789abcdefghijklmnopq123456
6549ff827328        registry.rnd.vsn.local/pamc/redactd-abcdefgh:123-456-789-abcde-fghijklmnopq          "/bin/true"         2 days ago          Exited (0) 2 days ago                       pamcredactdabcdefgh_123456789abcdefghijklmnopq
```

Now try using `--filter`:

```
# docker ps -f name=pamcredactdabcdefgh_123456789abcdefghijklmnopq123456 -f status=exited
CONTAINER ID        IMAGE                                                                                COMMAND             CREATED             STATUS                  PORTS               NAMES
74c9cccc0e34        registry.rnd.vsn.local/pamc/redactd-abcdefgh:123-456-789-abcde-fghijklmnopq-123456   "/bin/true"         2 days ago          Exited (0) 2 days ago                       pamcredactdabcdefgh_123456789abcdefghijklmnopq123456
```

And if I try the filter with the shorter name:

```
# docker ps -f name=pamcredactdabcdefgh_123456789abcdefghijklmnopq -f status=exited
CONTAINER ID        IMAGE                                                                                COMMAND             CREATED             STATUS                  PORTS               NAMES
74c9cccc0e34        registry.rnd.vsn.local/pamc/redactd-abcdefgh:123-456-789-abcde-fghijklmnopq-123456   "/bin/true"         2 days ago          Exited (0) 2 days ago                       pamcredactdabcdefgh_123456789abcdefghijklmnopq123456
6549ff827328        registry.rnd.vsn.local/pamc/redactd-abcdefgh:123-456-789-abcde-fghijklmnopq          "/bin/true"         2 days ago          Exited (0) 2 days ago                       pamcredactdabcdefgh_123456789abcdefghijklmnopq
```

Version:

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

The same is true for `17.05.0-ce-rc1`. So, if the `--filter name=...` is not an exact match, can we have a way to request exact-match? Something like, `--exact-filter name=...`? At the least, this behaviour is unexpected and not really documented.

**Comment by thaJeztah** [comment]
> So, if the --filter name=... is not an exact match, can we have a way to request exact-match?

Afaik, all filters match by prefix, so that's not unexpected (having a way to express a "matching" pattern has come up though, and would probably be a good addition at some point); that's a separate topic from the one being discussed here though.

The issue being reported here looks like a bug; `docker service ps <service-name>` should produce an error if `<service-name>` is ambiguous; we _do_ allow matching by _ID_ prefix though (to support printing a service's tasks by the _short_ ID)

**Comment by kinghuang** [comment]
@thaJeztah Yes, I believe this is a bug introduced in #25234. It changed `docker service ps`'s implementation to get services by filtering, which produces the filter style prefix matches now seen.

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/issues/32800 to address this issue

**Comment by dnephin** [comment]
fixed in https://github.com/docker/cli/pull/72
