### ISSUE TITLE
Adding a {{.Node.Hostname}} placeholder for when creating services with templates

### ISSUE THREAD

**Issue by jonathan-kosgei** [moby/moby#32561]
Hi,

It'd be really great to have the additional `{{.Node.Hostname}}` placeholder for when creating services with templates.

Consider the following usecase;

I create the following mongo service to configure a mongo replicaset
```
docker service create \
--name mongo \
--replicas 3 \
--network mongo \
--mount type=volume,src="{{.Service.Name}}-{{.Task.Slot}}",dst=/data/,volume-driver=ebs \
mongo:3.4.3 bash -c "mongod --replSet zipgo-rs0 --journal"
```

I'm using a template to create a new AWS EBS volume of name `{{.Service.Name}}-{{.Task.Slot}}`  for each task, the service is global meaning that a single task will be scheduled to each node. `{{.Task.Slot}}` gives a truncated version of the node id in swarm, which is clever (replicated services will have an index as the slot eg, 1,2,3 etc).

However if I'm running a 3 container replicaset in production and one of the nodes goes offline, and say a new one is created and is automatically joined to the swarm, a new task will be scheduled there to that node and a new volume will be created (new node, new swarmid). Herein lies the problem. A 100Gi volume that has data is leaked and a new blank 100Gi volume is created and has to start replicating data from the other nodes.

You could pass a `--snapshot-id` in the `--mount` options but that'll still be used to create a new volume. You'll still have a leaked 100Gi volume full of production data that has been leaked.

Solution:
An easy way to solve this would be if it was possible to pass the node's hostname as a placeholder. They are predictable and can be set manually, they'll be different for each node/task and will persist when the swarm id of a node changes. To clarify on that, if you `docker swarm leave` and then you rejoin, or your node crashes and you have to rejoin it to the cluster, you can still bring it up with the previous node's hostname and that way when a task is scheduled there it will find that the `{{.Service.Name}}-{{.Node.Hostname}}` volume already exists. 
No volumes will be leaked, no lags, or heavy iops to replicate hundreds of Gb of data to a new volume, unless you're adding new nodes intentionally.

**Comment by eyz** [comment]
This would be especially useful if global-scoped volumes are not used. Otherwise, for global-scoped volumes, the task name and slot ID is probably sufficient, from my findings.

**Comment by thaJeztah** [comment]
This works on master, and will be included in the upcoming Docker 17.10 release;

```bash
$ hostname testing123

$ docker service create \
--name foo \
--mount type=volume,src="{{.Node.Hostname}}-{{.Task.Slot}}",dst=/data/ \
nginx:alpine


$ docker volume ls

DRIVER              VOLUME NAME
local               testing123-1
```

Also see https://github.com/docker/swarmkit/issues/1951, and https://github.com/moby/moby/pull/34686

**Comment by svscorp** [comment]
Also checked

in docker-compose:
````
    environment:
      NAME: "node-{{.Node.Hostname}}"
````

container inspect on a node::
````
        "Config": {
            "Env": [
                "NAME=node-swarm-1",
             ]
         ]
````

Thank you for your work, guys!

**Comment by eugenepark1** [comment]
Is there a documentation on all of the available attributes associated with {{.Node.<attr>}} syntax?

**Comment by Morlinest** [comment]
@eugenepark1 I think https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates is answer.

**Comment by artisticcheese** [comment]
Which version of docker is required? I'm trying to run on 17.10.0-ee-preview and it fails with error below

```
PS C:\Users\cloudadmin> docker service update --hostname="{{.Node.HostName}}-{{.Service.Name}}" iis2
Error response from daemon: rpc error: code = InvalidArgument desc = expanding hostname failed: template: expansion:1:7: executing "expansion" at <.Node.HostName>: can't evaluate field HostNam
e in type struct { ID string; Hostname string; Platform template.Platform }
```

**Comment by artisticcheese** [comment]
Can I safely substitutue Docker EE 17.10 with Docker CE 17.10? I'm trying to use docker routing mesh in windows which requires Docker EE 17.10-preview.

**Comment by thaJeztah** [comment]
Other than Docker for Windows (desktop), no CE recent packages are published for Windows server.

**Comment by artisticcheese** [comment]
So when we will see latest EE for Windows Server? Last one is 17.06 and was released in August 2017

**Comment by thaJeztah** [comment]
Current EE release is 17.06, and still actively maintained. Nightly / builds from Moby master can be found at https://master.dockerproject.org, but meant for testing only.
