### ISSUE TITLE
Documentation: Cannot run hello-world container on Raspberry Pi

### ISSUE THREAD

**Issue by DeeJay** [moby/moby#32565]
Consciously referring to Issue #29617, now Closed.

There *is* (in my humble opinion) an issue here.

It is a documentation issue.

Following https://docs.docker.com/engine/getstarted/step_one/#step-3-verify-your-installation, at Step 3, sub-step 2, the command provided is

docker run hello-world

Nothing there indicates that there might be anything platform/architecture dependent.

This is in Verify your Installation. It is therefore likely to be followed verbatim by relatively uninformed potential users who might reasonably assume that a basic test should Just Work.

In fact the result is this:
pi@rpi2b ~ $ docker run hello-world
standard_init_linux.go:178: exec user process caused "exec format error"

The resulting error message is not handled in the linked 'Troubleshooting' section of the tutorial.

The workaround is
pi@rpi2b ~ $ docker run armhf/hello-world

Hello from Docker on armhf!
This message shows that your installation appears to be working correctly.

**Comment by ChangeTheCode** [comment]
I have the same problem with Docker on my Raspberry:
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm
 Experimental: false

I'm just able to run "docker run armhf/hello-world" 
Result: 
Hello from Docker on armhf!
This message shows that your installation appears to be working correctly.

Has anybody a solution for this problem?

**Comment by alexellis** [comment]
This may be addressed in the future through the use of multi-platform images. For now I wonder what @mstanleyjones thinks of adding a footnote RE: ARM? Myself, @justincormack and @thaJeztah have seen quite a number of issues like this one opened. If we could do something with the documentation it should see a drop in these types of questions/issues?

Something like:

> If you're using an ARM or Raspberry Pi device use armhf/hello-world instead.

I know there *are* other architectures but his one is especially popular.

**Comment by alexellis** [comment]
@DeeJay can you update the title since this appears to be re: documentation rather than a Moby bug?

**Comment by alexellis** [comment]
@thaJeztah where are we with this issue? Should we close due to inactivity? @DeeJay any thoughts?

**Comment by alexellis** [comment]
Derek add label: status/more-info-needed

**Comment by thaJeztah** [comment]
The `hello-world` image (and other official images) is now multi-arch; https://hub.docker.com/_/hello-world/, so I think we can close this one, but feel free to comment @DeeJay 

<img width="731" alt="screen shot 2017-12-04 at 17 50 15" src="https://user-images.githubusercontent.com/1804568/33585934-ade8c48a-d91b-11e7-86a3-7f7e6a3cec5d.png">
