### ISSUE TITLE
macvlan: network not found error approximately every 8th "docker-compose up" command

### ISSUE THREAD

**Issue by mkilchhofer** [moby/moby#32572]
Hi there

I already reported an issue in docker/compose, but they told me to report it here.
https://github.com/docker/compose/issues/4717

**Description**
We use macvlan as a 2nd network in a docker container to connect it to the physical network.
Mostly it works fine, but approximately every 8th "docker-compose up" command fails with this message:

```
(...)
Creating default_orion_1
Creating default_pegasus_1

ERROR: for broho  Cannot start service broho: driver failed revoking external connectivity on endpoint default_broho_1 (4aed7b1bb508a07d3daf074901d011778a153460c1c87a238f2f4d4c08a7519d): network not found: 1e320a2ba090ea6f6b563c421ecc3eda121aa3065cd32c52dc74fb42851d23d6
Encountered errors while bringing up the project.
```

**Steps to reproduce the issue:**
0. define networks of docker-compose.yaml project
```
networks:
  default:
    external:
      name: isa-docker
  vehicle:
    external:
      name: isa-vehicle
```
1. define networks of service broho in docker-compose.yaml
```
    networks:
      - default
      - vehicle
```
2. all services in this compose project have no networks specified - so they will use the default network

**Describe the results you received:**
see error described in description

**Describe the results you expected:**
The project should start, all container connects to the default network and the container "broho" should have an additional network with macvlan.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tested this with this bash script (pseudo code):
```
$ docker-compose down
$ docker-compose up
$ sleep 120
```
Tested ~800 times, and approximately 100 times, the error described above occurred.

**Output of `docker version`:**
```
[root@eddie027 ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64
``` 

**Output of `docker info`:**
```
(paste your output here)
```

Is there something I can test to help debugging?
When I remove 'networks' from service 'broho' in the file docker-compose.yaml, and connect this container by "docker network connect isa-vehicle default_broho_1" after compose started the container, it works fine.

**Comment by aboch** [comment]
You might be hitting the issue fixed by @pooya in docker/libnetwork/pull/1480
If you can try with docker 1.13.x, that version will contain the fix.

The failure is in fact reported by the network driver when asked to remove the external connectivity for that network endpoint on that network. He responds he does not know that network.

**Comment by mkilchhofer** [comment]
I installed the 'docker-latest' package on our rhel7.3 lab system.
(docker-latest: 1.13.1-4, https://access.redhat.com/articles/2317361)

I started a little script that executes every 5mins during the Easter break:
```
echo `date`" - compose down"
docker-compose down
sleep 10

echo `date`" - compose up -d"
docker-compose up -d
sleep 300
```
I will update this case by no later than Tuesday. :-)

**Comment by mkilchhofer** [comment]
Good news!
After some initial difficulties with disk space (no space left), the test script executed 957 times without any network error.


# notes about disk space
I noticed that docker does not delete created volumes after "docker-compose down" or "docker rm some-container".
After I delete a container I would expect, "docker volume ls" should not list something.
**--> Is this a normal behavior?**

# "known" device mapper issues
Since we use RHEL7 we also have to use device mapper. With docker 1.13 (at least the one from the redhat repo "rhel-7-server-extras-rpms") we still have a lot of issues with device mapper and privileged containers:

````
ERROR: for pegasus  Cannot start service pegasus: linux runtime spec devices: lstat /dev/dm-13: no such file or directory

(...)

ERROR: for pegasus  Cannot start service pegasus: linux runtime spec devices: lstat /dev/mapper/docker-253:0-3294-05d568952f0cb8eba395e25bd32d61a0275063e788be891e4e5a1beb0f1b8947: no such file or directory

````

But there are also errors like this:
````
ERROR: for storage  Cannot start service storage: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: \\\"\"\n"
````
(storage is a redis container without special permissions or privileged)

**Comment by thaJeztah** [comment]
> I noticed that docker does not delete created volumes after "docker-compose down" or "docker rm some-container".

This is by design; volumes are designed to persist after you removed a container, because volumes contain _statefull_ data (e.g. your database, uploads, or whatever should not be destroyed when the container is destroyed)

You can remove volumes as well when using `docker-compose down -v`

**Comment by mkilchhofer** [comment]
Thanks you @thaJeztah (and also @shin-).
Since this bug here is fixed as described above, I now close this issue.

I opened a new issue for the devmapper issue here: https://github.com/moby/moby/issues/32699

I will observe the "oci runtime error" for a time. Maybe I then open an issue for that.
