### ISSUE TITLE
Improvements to yaml-docs-gen target

### ISSUE THREAD

**Issue by mistyhacks** [moby/moby#32573]
- Use a umask to make sure that the bundle files are written out with write permissions by the user who ran `make yaml docs-gen`
- Filter out deprecated flags from the output (such as `--email` flag to `docker login`. it is confusing to users when it doesn't show up in `--help` but does show up in our reference. See https://github.com/docker/docker.github.io/issues/2534.

**Comment by thaJeztah** [comment]
This code now lives in the https://github.com/docker/cli repository, and I think some improvements were made already
