### ISSUE TITLE
Support rollback options in stack deploy

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#32585]
#31108 made it possible to control rollback parameters separately from update parameters. It added a set of `--rollback-*` options mirroring the `--update-*` options. These parameters should also be supported in compose files.

This PR also added a new failure action called "rollback". This value should be supported for the `failure_action` key in compose files if it isn't already.

cc @dnephin

**Comment by stevelacy** [comment]
Is there a current way to "update" an existing docker stack service with the rollback options?
Attempting to update an existing service only seems to add the rollback option for that update.

**Comment by vdemeester** [comment]
Closing in favor of https://github.com/docker/cli/issues/141

**Comment by germantellezv** [comment]
is there a way to specify rollback_config con docker-compose file of docker stack?
