### ISSUE TITLE
Support update-order/rollback-order in stack deploy

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#32586]
#30261 added `--update-order` and `--rollback-order` flags. We should add equivalents to the compose file schema.

cc @dnephin

**Comment by sirlatrom** [comment]
@aaronlehmann @dnephin Is there a chance this could be assigned an expected milestone / compose file format version?

**Comment by akalipetis** [comment]
This will most probably be part of version 3.4, see docker/cli#346

**Comment by aaronlehmann** [comment]
Closing in favor of https://github.com/docker/cli/issues/346
