### ISSUE TITLE
IP Forwarding in bridge mode not possible without ip6tables support

### ISSUE THREAD

**Issue by wrridgwa** [moby/moby#32605]
**Description**
Pinging from within a bridge container to a machine outside of the host should be possible with IPv6. I set up the docker daemon with 
`docker daemon --ip-forward=true --iptables=true --ipv6 --fixed-cidr-v6="2001:db8:1::/64"`

I can ping6 from within the container to the host IPv6 address and from the host IPv6 to the outside IPv6 address. But I can't ping6 from within the container to the outside IPv6 address. I believe this is not allowable because there is currently no ip6tables support in Docker.  This functionality is currently available with IPv4.

**Steps to reproduce the issue:**
1. Configure IPv6 address on host machine: `ip addr add 2000::36 dev eth1`
2. Configure IPv6 address on outside machine: `ip addr add 2000::6 dev eth1`
3. On host machine `docker daemon --ip-forward=true --iptables=true --ipv6 --fixed-cidr-v6="2001:db8:1::/64"`
4. On host machine `docker run ....` (Container id = dfd294e34e33)
5. Shell into container `docker exec -it dfd294e34e33 /bin/bash`
6. Within container `ping6 2000::6`

**Describe the results you received:**
```root@dfd294e34e33:/# ping6 2000::3
PING 2000::3(2000::3) 56 data bytes
^C
--- 2000::3 ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10000ms
```

**Describe the results you expected:**
Should see no packet loss and all of the packets received.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
Images: 14
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 3.871 GiB
Name: debian
ID: DS3W:ISVZ:2ALA:OVTA:USOK:DODS:QU54:ZJOQ:EXHT:XCKE:XJSS:DRMG
WARNING: No memory limit support
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Both the Host machine and the outside machine are VirtualBox VMs and using a `host-only adapter` with a 2000::1/64 network.

**Comment by wrridgwa** [comment]
I am working on a Docker patch for this. What are the next steps I should take?

**Comment by estesp** [comment]
ping @mavenugo; I haven't played with IPv6 and the engine for quite some time..any ideas here or any required setup to get "out" from container -> internet via IPv6? @wrridgwa assumes there is missing `ip6tables` support here, similar to how `iptables` is used for IPv4 capabilities, but I thought I had this working a long time ago.

**Comment by wrridgwa** [comment]
@estesp Any word on this?

**Comment by wrridgwa** [comment]
@estesp We figured out what exactly was happening with this issue. There is no iptables `nat` support for IPv6. This page explains the implementation that is needed: http://www.revsys.com/writings/quicktips/nat.html

Without the [nat masquerading](https://www.centos.org/docs/5/html/5.1/Deployment_Guide/postrouting-ipmasquerading.html) outside devices wouldn't be able to respond to the containers packets.

**Comment by wrridgwa** [comment]
This issue is seen here: https://github.com/docker/libnetwork/issues/1183

**Comment by wrridgwa** [comment]
Improving --ip_masq to also do IPv6 would be the solution.

**Comment by wrridgwa** [comment]
@mavenugo Is this on the Docker radar? Are their plans to bring in this kind of IPv6 support?

**Comment by wrridgwa** [comment]
Ah, this other ticket covers my concern: https://github.com/moby/moby/issues/25407

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale; also this PR was merged, which may be of use;

- https://github.com/moby/moby/pull/41622
