### ISSUE TITLE
permission denied setting IPv6 address on tun/tap on 17.04+

### ISSUE THREAD

**Issue by bprodoehl** [moby/moby#32619]
**Description**

Starting with the 17.04 release, I can't set an IPv6 address on a tun/tap adapter from within a container.  I get ```SIOCSIFADDR: Permission denied```.  With 17.03.1 all the way back to 1.12, the same steps work fine, so this looks like a regression in 17.04 and the 17.05 rc1.

**Steps to reproduce the issue:**
1. Install the docker daemon with basic working IPv6 on Ubuntu 14.04 or Debian 8.
2. Run a container that has ip baked in, like ubuntu:14.04, either in privileged mode, or with --cap-add NET_ADMIN --device=/dev/net/tun
3. Run the following script, to try to create a tap adapter and add a local IPv6 address to it:
```
#!/bin/bash
set -eu

ip tuntap add mode tap br0p0
ifconfig br0p0 inet6 add fda7:576d:ac1a::1/48
```

**Describe the results you received:**
The tap device is created, but setting the address on it, either with ifconfig or ip, fails with "Permission denied".  Setting an IPv4 address on it works just fine.

**Describe the results you expected:**
With 17.03.1 and earlier, the script completes without error and the tap adapter gets the proper IPv6 address.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens on Ubuntu systems with AppArmor and also Debian systems without AppArmor.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:50:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:50:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 7
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.9.15-x86_64-linode81
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.95GiB
Name: li1029-103
ID: OT47:PKI6:MWM7:YA7N:C5U2:WEB7:BQPX:LVAW:X2RW:ZFLY:KNOD:UKCI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've mostly been testing this on Linode.

**Comment by aboch** [comment]
IPv6 is now enabled per-interface basis on the container. See #20569.

**Comment by prasincs** [comment]
This is happening in Ubuntu 14.04 too with the same setup. I tried running dockerd with `--ipv6=true` and `--fixed-cidr-v6` options but it's still returning the same error

```
ip tuntap add mode tun
root@a2f605a3adf8:/go# ip addr add dev tun0 fd28:49be:758:7653:3cb1:6d:230c:60/64
RTNETLINK answers: Permission denied
```

You can try the following too 

```
sudo docker run --privileged --rm golang:1.8 sh -c "go get github.com/prasincs/docker-netlink-issue/... && exec docker-netlink-issue"
```

I tried with specifically setting `NET_ADMIN` too to no avail

More details are in github.com/prasincs/docker-netlink-issue if it's useful to test.

**Comment by bprodoehl** [comment]
I think you need to unset disable_ipv6 with sysctl inside the container, but I haven't tried yet.

**Comment by prasincs** [comment]
@bprodoehl this seems to have worked

```
sudo docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged --rm golang:1.8 sh -c "go get github.com/prasincs/docker-netlink-issue/... && exec docker-netlink-issue"
```

**Comment by Deshke** [comment]
what i wrote in https://github.com/moby/moby/issues/20569#issuecomment-297257699

**Comment by bprodoehl** [comment]
@aboch Thanks for the pointer. I think this can be closed.  Hopefully there's enough in here to get caught by search engines for anyone else similarly confused.
