### ISSUE TITLE
Decompress layer immediately after downloaded

### ISSUE THREAD

**Issue by uoryon** [moby/moby#32618]
I found that docker downloads the layers concurrently, but decompress it one by one. And it only to decompress until all layers are downloaded. If the image is too large , the process will be too long.

Could docker decompress layer immediately after downloaded and add some parallelism? It can save little time for pulling image.

**Comment by tonistiigi** [comment]
Most storage drivers are snapshot based and the data can't be extracted to them before the parent snapshot has been completed.

**Comment by cpuguy83** [comment]
Yeah, this can't really be done since the layers need to be created in order.

Closing but feel free to discuss. 👼
