### ISSUE TITLE
docker stack restart option is ignored

### ISSUE THREAD

**Issue by aleskurlovich** [moby/moby#32623]
**Steps to reproduce the issue:**
1. Create next Dockerfile in "test" directory:

   FROM debian
   CMD echo "test"

2. Go to "test" directory and execute next command (build image): "docker build -t test:latest ."
3. Create docker stack file with name "docker-cloud.yml":

   version: "3"
   services:
    test:
       image: test:latest

4. Execute next command: "docker stack deploy -c docker-cloud.yml services"
5. Wait several seconds and execute "docker ps -a".

**Expected**:
One exited container "test:latest" because default restart option value is "no" according [documentation](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#restart).

**Actual**:
Several exited containers with "test:latest" tag.

**Docker version**:
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false`

**Docker info**:
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 06qm3mlo2dtnnrt0lebbfqkiz
 Is Manager: true
 ClusterID: yonkvlxzljjjztpxzcuc3fnrn
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: ...
 Manager Addresses:
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.695 GiB
Name: q4de3csye47
ID: 2FXY:XP3H:UWFL:3R7U:CF5H:THXJ:XC5K:SZTS:U4LV:AY7D:3JNV:FOJF
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: ...
Https Proxy: ...
No Proxy: ...
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 ...
 127.0.0.0/8
Live Restore Enabled: false

**Comment by vdemeester** [comment]
@aleskurlovich The reference links is for Docker cloud "defaults" (https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/). It is not the case when you use `docker stack deploy`, the defaults are the same as swarm mode — and in swarm mode, the default is restart `always`. If you want to make sure it does not restart, you shouldn't rely on defaults value but be explicit about it.

That being said, it feels a little bit confusing having https://docs.docker.com/compose/compose-file/ and https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/ — and we might need to update documentation to be more clear 👼

**Comment by aleskurlovich** [comment]
Thank you! I use right documentation and it works.

**Comment by mstanleyjones** [comment]
@londoncalling do you think the Compose docs could be improved?

**Comment by londoncalling** [comment]
@mstanleyjones probably yes. I'll look at this now.

**Comment by londoncalling** [comment]
@pkennedyr @KickingTheTV @ManoMarks 
Can you all scan through the discussion in this issue? 

The gist of it is confusion between the definition for [`restart` in the Cloud stack YAML reference here](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#restart), and [`restart` policy settings in Compose file v3 here](https://docs.docker.com/compose/compose-file/#restartpolicy). 

@aleskurlovich needed the latter, which worked after he tried it.

The larger issue is confusion between the two files I think. I have several questions:
1. Does the Cloud stack YAML need updates per the latest Compose v3 file (or are they completely independent?
2. Should we include several notes in Cloud stack YAMl to redirect users to the latest Compose file? (Both at the top of the file, and at each config option?)
3. Is there further confusion that could result from competing concepts of Cloud stack YAML and `docker-stack.yml` (a type of Compose file for v3)? If so, what's the best way to address this?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
