### ISSUE TITLE
Container in swarm mode overlay network encounter dns resolve time out with embedded DNS 

### ISSUE THREAD

**Issue by dengqingpei1990** [moby/moby#32622]
**Description**
Hi guys :) 
    Recently I have made a simple test about monitoring docker container. The stack is cadvisor+node-exporter+prometheus+alertmanager.  I deployed these containers via a docker stack file. All these software are ran as a swarm service, so that  cantainers can communicate with each other via its service name.  At first everythings work ok but a few warnings occur on prometheus's container log:

```
time="2017-04-14T07:25:19Z" level=warning msg="DNS resolution failed." name=tasks.cadvisor reason="read udp 127.0.0.1:45630->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:19Z" level=warning msg="DNS resolution failed." name=tasks.node-exporter reason="read udp 127.0.0.1:48316->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:19Z" level=warning msg="DNS resolution failed." name=tasks.prometheus reason="read udp 127.0.0.1:39631->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:29Z" level=warning msg="DNS resolution failed." name=tasks.prometheus reason="read udp 127.0.0.1:42653->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:29Z" level=warning msg="DNS resolution failed." name=tasks.cadvisor reason="read udp 127.0.0.1:36685->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:29Z" level=warning msg="DNS resolution failed." name=tasks.node-exporter reason="read udp 127.0.0.1:41867->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:39Z" level=warning msg="DNS resolution failed." name=tasks.node-exporter reason="read udp 127.0.0.1:55311->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:39Z" level=warning msg="DNS resolution failed." name=tasks.cadvisor reason="read udp 127.0.0.1:52426->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3 
time="2017-04-14T07:25:39Z" level=warning msg="DNS resolution failed." name=tasks.prometheus reason="read udp 127.0.0.1:35912->127.0.0.11:53: i/o timeout" server=127.0.0.11 source="dns.go:190" suffix=server3
```

I think I have to make a simple explaination about my promethues's config.

```yaml
scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090
      refresh_interval: 10s
  
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
      refresh_interval: 10s
```

Promethues uses swarm mode overlay network's embedded DNS to resolve container's ip address. How did the timeout happen? It confuses me a lot. Then I make a alerting test, an error occur again:
```
time="2017-04-14T07:25:47Z" level=error msg="Error sending alerts: context deadline exceeded" alertmanager="http://alertmanager:9093/api/v1/alerts" count=1 source="notifier.go:335"`
Prom can't call alertmanager's api via  http://alertmanager:9093/api/v1/alerts.
I turn on the debug mode on docker daemon and I find these:
`Apr 14 15:26:11 docker dockerd: time="2017-04-14T15:26:11.108217591+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:47230->192.168.1.254:53: i/o timeout"
Apr 14 15:26:11 docker dockerd: time="2017-04-14T15:26:11.108267891+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:45828->192.168.1.254:53: i/o timeout"
Apr 14 15:26:11 docker dockerd: time="2017-04-14T15:26:11.108284283+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:56587->192.168.1.254:53: i/o timeout"
Apr 14 15:26:11 docker dockerd: time="2017-04-14T15:26:11.826414174+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:33293->192.168.1.254:53: i/o timeout"
Apr 14 15:26:11 docker dockerd: time="2017-04-14T15:26:11.826447632+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:52251->192.168.1.254:53: i/o timeout"
Apr 14 15:26:12 docker dockerd: time="2017-04-14T15:26:12.826119287+08:00" level=debug msg="Name To resolve: alertmanager.server3."
Apr 14 15:26:12 docker dockerd: time="2017-04-14T15:26:12.826185179+08:00" level=debug msg="Name To resolve: alertmanager.server3."
Apr 14 15:26:12 docker dockerd: time="2017-04-14T15:26:12.826240412+08:00" level=debug msg="Query alertmanager.server3.[28] from 172.18.0.4:48971, forwarding to udp:192.168.1.254"
Apr 14 15:26:12 docker dockerd: time="2017-04-14T15:26:12.826260127+08:00" level=debug msg="Query alertmanager.server3.[1] from 172.18.0.4:60110, forwarding to udp:192.168.1.254"
Apr 14 15:26:16 docker dockerd: time="2017-04-14T15:26:16.830991069+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:48971->192.168.1.254:53: i/o timeout"
Apr 14 15:26:16 docker dockerd: time="2017-04-14T15:26:16.831051638+08:00" level=debug msg="Read from DNS server failed, read udp 172.18.0.4:60110->192.168.1.254:53: i/o timeout"
```

Why docker resolve container ip using the host's /etc/resolve config? Embedded DNS didn't work?

**Steps to reproduce the issue:**
1.deploy a docker stack about cadvisor+node-exporter+prometheus+alertmanager.
2.catch warnnings and errors about embedded DNS .

**Describe the results you received:**
dns reosolve timeout

**Describe the results you expected:**
everything work fine

**Additional information you deem important (e.g. issue happens only occasionally):**
ipv6 is forbidden on both host and docker daemon.
I  try adding --dns=192.168.1.254(local dns server) flags to dockerd command to avoid the China's Great Firewall's impact but still not work.
**Output of `docker version`:**

```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: hxcu969e0pa6ytz21xcf6l6ti
 Is Manager: false
 Node Address: 192.168.1.206
 Manager Addresses:
  192.168.1.203:2377
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.796GiB
Name: docker.server3
ID: UFZO:FLQJ:LI3S:WK7H:YIM2:R3ED:HF4Z:I24E:JF7V:XPFC:2SUG:E34I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 85
 Goroutines: 161
 System Time: 2017-04-14T16:24:17.315255907+08:00
 EventsListeners: 5
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://116bfaee.m.daocloud.io/
Live Restore Enabled: false
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox

**Comment by dengqingpei1990** [comment]
Additional:
I get into the prometheus's container and ping tasks.alertmanager, it's OK. 
/prometheus # ping tasks.alertmanager
PING tasks.alertmanager (172.14.0.15): 56 data bytes
64 bytes from 172.14.0.15: seq=0 ttl=64 time=0.099 ms
64 bytes from 172.14.0.15: seq=1 ttl=64 time=0.072 ms
64 bytes from 172.14.0.15: seq=2 ttl=64 time=0.069 ms
64 bytes from 172.14.0.15: seq=3 ttl=64 time=0.073 ms
64 bytes from 172.14.0.15: seq=4 ttl=64 time=0.067 ms
^C
--- tasks.alertmanager ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.067/0.076/0.099 ms
But nslookup tasks.alertmanager takes  very long time to get resaults.
/prometheus # nslookup tasks.alertmanager
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      tasks.alertmanager
Address 1: 172.14.0.15 jk_alertmanager.1.wjj28l6yjyo19dx5ppaucbr3b.jk_monitoring

**Comment by thaJeztah** [comment]
I see mention of `suffix=server3` in your first comment; is that configured as a search domain on your host?

> Hi guys :)

Please keep in mind that it's not just "guys" in this community 😃 👍

**Comment by dengqingpei1990** [comment]
@thaJeztah  Yes, my host's hostname is docker.server3.
Sorry about my habitually words. I am new here and I will pay attention to that.

**Comment by thaJeztah** [comment]
ping @sanimej any thoughts?

**Comment by dengqingpei1990** [comment]
I resolve this problem by removing '**search server3**' in host's /etc/resolv.conf which is the suffix of my host's hostname and is added after installing Centos 7 automatically.
    
It seems that swarm mode embedded dns server look up both tasks.\<service name\> and task.\<service name\>.server3, 

When embedded dns server can't resolve task.\<service name\>.server3, forwarding it to the host. Host also can't resolve it because of the Inappropriate hostname. So dns resolve timeout occurs, and impacting alertmanager's API calling.

Is there anything docker can do to avoid this? I think this is a common problem of us docker users. I will close this issue otherwise. @thaJeztah
