### ISSUE TITLE
--network-add during service update doesnt allocate VIP from the newly attached network

### ISSUE THREAD

**Issue by abhinandanpb** [moby/moby#32629]
Version: 17.05
Mode: Swarm mode

Steps to Reproduce
1) sudo docker network create -d overlay --subnet 10.1.1.0/24 net1 
2) sudo docker network create -d overlay --subnet 11.1.1.0/24 net2
3) sudo docker service create --name srv1 --network net1 nginx
4) sudo docker service update srv1 --network-add net2

Issue observed:
After service update I don't see VIP from net2 allocated. Now if I update the service by removing the network net1. I don't see the VIP from net1 being deallocated as well.

**Comment by thaJeztah** [comment]
ping @aboch PTAL

**Comment by cirocosta** [comment]
So probably @abhinandanpb  could confirm if it has been fixed since https://github.com/docker/swarmkit/pull/2139 ?

**Comment by abhinandanpb** [comment]
@cirocosta yes its been fixed starting 17.05.
