### ISSUE TITLE
Docker push to remote registry consumes local devicemapper storage capacity

### ISSUE THREAD

**Issue by romfreiman** [moby/moby#32644]
Once I push to remote registry an images which does not exists there, for an unknown reason the local thinpool capacity shrink.

Not sure why does it happen - I do see 
[Sun Apr 16 13:27:21 2017] XFS (dm-48): Unmounting Filesystem
[Sun Apr 16 13:27:22 2017] XFS (dm-48): Mounting V4 Filesystem
[Sun Apr 16 13:27:22 2017] XFS (dm-48): Ending clean mount
[Sun Apr 16 13:27:24 2017] XFS (dm-48): Unmounting Filesystem
in dmesg - so I guess docker is doing something on the local storage.

Would like to get an explanation. What am I missing?

[root@stratonode0 ~]# docker info
Containers: 34
 Running: 34
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: inaugurator-docker_thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 25.96 GB
 Data Space Total: 26.84 GB
 Data Space Available: 878.7 MB
 Metadata Space Used: 13.75 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.06 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.32 GiB
Name: XXXX
ID: 4AS5:G6YJ:YQUT:T3CC:PG4B:2BLJ:ZKH5:GJEM:BJHC:P6FO:C2SU:ZDG5

**Comment by thaJeztah** [comment]
I guess this is because each image layer is mounted and compressed before it's being pushed

**Comment by rom-stratoscale** [comment]
@thaJeztah compressed in the thinpool? but once it pushed, shouldnt the storage space be freed?

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637
