### ISSUE TITLE
REST API Swagger representation cannot be loaded with SwaggerUI

### ISSUE THREAD

**Issue by arun-gupta** [moby/moby#32649]
Docker REST API 1.27 cannot be loaded with the SwaggerUI. It gives the error:

```
{
"messages": [
"attribute definitions.RestartPolicy.default is not of type `string`"
]
}
```

The error can be seen at https://online.swagger.io/validator/debug?url=https://docs.docker.com/engine/api/v1.27/swagger.yaml.

**Comment by jgallen23** [comment]
Same with the newest API version

**Comment by thaJeztah** [comment]
I opened https://github.com/moby/moby/pull/34247 which looks to resolve the issue; I think it's find to omit the default there, but let me know if there's an issue in removing it
