### ISSUE TITLE
Deploy voting app fail

### ISSUE THREAD

**Issue by robin820224** [moby/moby#32650]
I am trying to deploy vote app follow the "Define and deploy your app" doc, I found that the visualizer service running fail, please look at error log:

docker@manager:~$ docker stack services vote
ID                  NAME                MODE                REPLICAS            IMAGE
70eica7mb9t6        vote_visualizer     replicated          0/1                 dockersamples/visualizer:stable
d7tlk7pefjcb        vote_redis          replicated          2/2                 redis:alpine
fra06tc0zua2        vote_vote           replicated          2/2                 dockersamples/examplevotingapp_vote:before
s00pn1fxk2yq        vote_db             replicated          1/1                 postgres:9.4
tf33au4reqrk        vote_result         replicated          1/1                 dockersamples/examplevotingapp_result:before
yqul1lto2wep        vote_worker         replicated          1/1                 dockersamples/examplevotingapp_worker:latest

docker@manager:~$ docker stack ps --no-trunc vote
ID                          NAME                    IMAGE                                                                                                     NODE                DESIRED STATE       CURRENT STATE                     ERROR               PORTS
ic9cfj8znpy2peqpk6pjy9jkn   vote_visualizer.1       dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5   manager             Running             Starting less than a second ago        
151h36rcfkeh9o52p8pdqlmyo    \_ vote_visualizer.1   dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5   manager             Shutdown            Failed 5 seconds ago              "starting container failed: oci runtime error: container_linux.go:247: starting container process caused "exec: \"npm\": executable file not found in $PATH"
"
oz8a5sopspmvvathllls2m3sy    \_ vote_visualizer.1   dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5   manager             Shutdown            Failed 12 seconds ago   "starting container failed: oci runtime error: container_linux.go:247: starting container process caused "exec: \"npm\": executable file not found in $PATH"
"
drsvfok0bf734ap4erovvf6aw    \_ vote_visualizer.1   dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5   manager             Shutdown            Failed 18 seconds ago   "starting container failed: oci runtime error: container_linux.go:247: starting container process caused "exec: \"npm\": executable file not found in $PATH"
"
5m8hcq8i8uefaniw3e9a5mtgo    \_ vote_visualizer.1   dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5   manager             Shutdown            Failed 24 seconds ago   "starting container failed: oci runtime error: container_linux.go:247: starting container process caused "exec: \"npm\": executable file not found in $PATH"
"
6oo5ceqlxpbrxvvcdth8edqyn   vote_redis.1        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   worker              Running             Running about an hour ago     
wd1b0sc0070jja627pzc2o8ji    \_ vote_redis.1    redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (1)"
z8zjxn6ry1zebvp6f08pn39kh   vote_result.1       dockersamples/examplevotingapp_result:before@sha256:83b568996e930c292a6ae5187fda84dd6568a19d97cdb933720be15c757b7463   manager             Running             Running about an hour ago     
5lx1f33j9a0k8iqzbvjblhcg0   vote_vote.1         dockersamples/examplevotingapp_vote:before@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6     manager             Running             Running about an hour ago     
z44y07il4vtf37oe1fsnwep5o   vote_db.1           postgres:9.4@sha256:83a05c1cc6e75bc24795690d54dd259c757db19a0885890a661cf0d1899ea237                                   manager             Running             Running about an hour ago     
2cqxm1cjfu6xgvv0lh73umsd3   vote_redis.1        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   worker              Shutdown            Failed about an hour ago    "task: non-zero exit (255)"
tbk18x8oaxqo6lf485qdk628w   vote_worker.1       dockersamples/examplevotingapp_worker:latest@sha256:55753a7b7872d3e2eb47f146c53899c41dcbe259d54e24b3da730b9acbff50a1   manager             Running             Running 45 minutes ago        
i5d1h9j3bmsttvpyxbqphni0b   vote_result.1       dockersamples/examplevotingapp_result:before@sha256:83b568996e930c292a6ae5187fda84dd6568a19d97cdb933720be15c757b7463   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (255)"
nue6jf0nkitn8xe32pan0ywgo   vote_redis.2        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   worker              Running             Running about an hour ago     
33xou9lbs3vvtgkx3ovu56mx0    \_ vote_redis.2    redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (1)"
nzwy04mnbad4166mj90ugbnpy    \_ vote_redis.2    redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (1)"
wvdc59w82i3iunw1oq1hbm30n    \_ vote_redis.2    redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (1)"
jgkywpbj237aj2b14kav2pamx   vote_vote.2         dockersamples/examplevotingapp_vote:before@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6     manager             Running             Running about an hour ago     
0trj5vqwo5g4hhqssz0q7ew23    \_ vote_vote.2     dockersamples/examplevotingapp_vote:before@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6     worker              Shutdown            Failed about an hour ago    "task: non-zero exit (255)"
xf6am2gn3qllqvpiw3bqsntxu   vote_redis.2        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Shutdown            Failed about an hour ago    "task: non-zero exit (1)"

**Comment by thaJeztah** [comment]
please provide the information that was requested in the issue template (at least `docker version` and `docker info` https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md, otherwise there's not a lot to go on

**Comment by robin820224** [comment]
docker@manager:~$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64


docker@manager:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: tknztfz8hz2xsfx9onczw5kg9
 Is Manager: true
 ClusterID: 6iqvynqumklkceddeqhj51fwi
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.101
 Manager Addresses:
  192.168.99.101:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: manager
ID: CTLA:3NRO:NG37:NIDR:3O6R:7ND4:ECBF:E2DS:DG5Z:RH42:3ALK:Q6UM
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 369
 System Time: 2017-04-17T08:32:42.697074084Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by robin820224** [comment]
I have recreated manager and worker node, and then deploy vote app again. It seems that vote servers were not normal.


docker@manager:~$ docker stack services vote
ID                  NAME                MODE                REPLICAS            IMAGE
fxa00dhugi3x        vote_visualizer     replicated          0/1                 dockersamples/visualizer:stable
gqzshgpl6f9d        vote_vote           replicated          0/2                 dockersamples/examplevotingapp_vote:before
k553hfm1oklb        vote_worker         replicated          0/1                 dockersamples/examplevotingapp_worker:latest
kr5n5ta7tnrj        vote_redis          replicated          0/2                 redis:alpine
pxn8jh88ze6w        vote_db             replicated          0/1                 postgres:9.4
r43g03s09066        vote_result         replicated          1/1                 dockersamples/examplevotingapp_result:before

docker@manager:~$ docker stack ps --no-trunc vote
ID                          NAME                IMAGE                                                                                                                  NODE                DESIRED STATE       CURRENT STATE              ERROR               PORTS
uyyx5v6abvbigg430tyy66z6l   vote_vote.1         dockersamples/examplevotingapp_vote:before@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6     worker              Running             Preparing 12 minutes ago      
n1kadwojffd94v9jpp844zei8   vote_db.1           postgres:9.4@sha256:83a05c1cc6e75bc24795690d54dd259c757db19a0885890a661cf0d1899ea237                                   manager             Running             Preparing 12 minutes ago      
014x1b5l7ses7ss4nl4xvrk3b   vote_redis.1        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   worker              Running             Preparing 12 minutes ago      
px8d0nrho817ozwoj4lhrub42   vote_visualizer.1   dockersamples/visualizer:stable@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5                manager             Running             Preparing 12 minutes ago      
flub7owk4k6qcv5s6wtlnetwe   vote_worker.1       dockersamples/examplevotingapp_worker:latest@sha256:55753a7b7872d3e2eb47f146c53899c41dcbe259d54e24b3da730b9acbff50a1   manager             Running             Preparing 13 minutes ago      
nourzk6c198vmh1cmk3fdg42i   vote_result.1       dockersamples/examplevotingapp_result:before@sha256:83b568996e930c292a6ae5187fda84dd6568a19d97cdb933720be15c757b7463   manager             Running             Running 6 minutes ago         
f5w2cgxbfihn6nr4ab771tgyf   vote_vote.2         dockersamples/examplevotingapp_vote:before@sha256:8e64b18b2c87de902f2b72321c89b4af4e2b942d76d0b772532ff27ec4c6ebf6     manager             Running             Preparing 12 minutes ago      
jheg2rq8370a2ghd759e3yfw0   vote_redis.2        redis:alpine@sha256:9cd405cd1ec1410eaab064a1383d0d8854d1eef74a54e1e4a92fb4ec7bdc3ee7                                   manager             Running             Preparing 12 minutes ago      

docker@manager:~$ netstat -ant | grep 5000

**Comment by unclejack** [comment]
Please keep in mind this issue tracker is meant to be used for tracking bugs, feature requests and pull requests. This isn't meant to be a general support forum.

https://forums.docker.com/ should be used for general support issues. Please post there to get help with specific applications. I'll close this issue now.
