### ISSUE TITLE
dpkg: dependency problems prevent configuration of nvidia-docker:  nvidia-docker depends on docker-engine (>= 1.9.0) | docker-ce | docker-ee

### ISSUE THREAD

**Issue by tianke0711** [moby/moby#32676]
I want to install the docker on the ubuntu(16.04) server with the instruction from this site:(https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository). After I run this command: udo apt-get install \
>     apt-transport-https \
>     ca-certificates \
>     curl \
>     software-properties-common

there is error: I found that the error as following is shown every time, thanks for your guys help.

 (dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0) | docker-ce | docker-ee; however:
  Package docker-engine is not installed.
  Package docker-ce is not configured yet.
  Package docker-ee is not installed.)

$ sudo apt-get install \
>     apt-transport-https \
>     ca-certificates \
>     curl \
>     software-properties-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.19).
curl is already the newest version (7.47.0-1ubuntu2.2).
software-properties-common is already the newest version (0.96.20.5).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up docker-ce (17.03.1~ce-0~ubuntu-xenial) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-04-18 10:11:32 JST; 4ms ago
     Docs: https://docs.docker.com
  Process: 18254 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 18254 (code=exited, status=1/FAILURE)

Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal systemd[1]: Starting Docker Application Container Engine...
Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal dockerd[18254]: Error starting daemon: pid file found, ensure docker is not running or...r.pid
Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal systemd[1]: Failed to start Docker Application Container Engine.
Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal systemd[1]: docker.service: Unit entered failed state.
Apr 18 10:11:32 NVIDIA2.cs179idcfcloud.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of nvidia-docker:
 nvidia-docker depends on docker-engine (>= 1.9.0) | docker-ce | docker-ee; however:
  Package docker-engine is not installed.
  Package docker-ce is not configured yet.
  Package docker-ee is not installed.

dpkg: error processing package nvidia-docker (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 docker-ce
 nvidia-docker

**Comment by tianke0711** [comment]
I have solved. Firstly restart the ubuntu server with linux, and run the command : apt-get -f install(this command is suggested by the error information), then I install the docker-engine by the following site(https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04). then install nvidia-docker, it works!

**Comment by unclejack** [comment]
I'll close this because the issue has been fixed.
