### ISSUE TITLE
Error starting daemon: error while opening volume store metadata database: invalid argument

### ISSUE THREAD

**Issue by Git-Rajkumar** [moby/moby#32680]
I have install docker in centos 7 vagrant machine. its installed ,but when start the docker its throw  **Error starting daemon: error while opening volume store metadata database: invalid argument**

Vagrant File:

Vagrant.configure("2") do |config|

	 
	  config.vm.box = "centos7"

	  #config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"

	  config.ssh.username = "vagrant"
	  config.vm.hostname = "test.mobi"
	  config.ssh.forward_agent = "true"
	  config.vm.network "private_network", ip: "192.168.56.70"
	  config.vm.network "public_network", ip: "192.168.1.50"
	  config.vm.provider :virtualbox do |vb|
	    vb.customize ["modifyvm", :id, "--memory", "2048"]
	  end
	  
	  config.vm.synced_folder "./data", "/vagrant", type:"virtualbox"

	end

**Kernal version:**  3.10.0-229.el7.x86_64

 
**docker version:**

    Client:
     Version:      17.04.0-ce
     API version:  1.28
     Go version:   go1.7.5
     Git commit:   4845c56
     Built:        Mon Apr  3 18:01:50 2017
     OS/Arch:      linux/amd64
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

 Start docker below command:

  **dockerd -g   /vagrant/docker** 

**Log Report:**

    # dockerd -g /vagrant/docker
    INFO[0000] libcontainerd: new containerd process, pid: 6086 
    WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
    WARN[0001] overlay: the backing nfs filesystem is formatted without d_type support, which leads to incorrect behavior. Running without d_type support will no longer be supported in Docker 17.12. 
    Error starting daemon: error while opening volume store metadata database: invalid argument
       
**/vagrant** is mounted folder via vagrant  with in the mount point, I created **docker**  folder the  then used to started docker for store docker files , is there any issue?,  Docker can access host machine folder via docker?.

**reference:**

https://imagebin.ca/v/3JSxqIpYpX0F

Suggest me what is the issue? how to fix this?.

**Comment by aaronlehmann** [comment]
ping @ehazlett @cpuguy83

**Comment by cpuguy83** [comment]
Using shared storage to run Docker is generally unsupported.
In the case of this error we are using boltdb to store volume metadata (as are other parts of Docker) and it is likely unable to mmap the file on the virtual box shared folder.

For reference here's some other reported issues for the exact issue: https://github.com/boltdb/bolt/issues/272

I would also expect that whatever driver used for container storage would fail horribly on vboxfs.

**Comment by thaJeztah** [comment]
Following the discussion above, I'm closing this issue because this is not a supported setup
