### ISSUE TITLE
http api /networks containers always empty

### ISSUE THREAD

**Issue by Grisu118** [moby/moby#32686]
**Description**
The http endpoint `GET /networks` always returns an empty containers list. If requesting a single network, with `GET /networks/<network>` the containers are shown. 

**Steps to reproduce the issue:**
1. Run `curl --unix-socket /var/run/docker.sock http:/v1.28/networks`

**Describe the results you received:**
Returns the following output: https://gist.github.com/Grisu118/1a15ea9a2abb6b04f45eb911a2f1c7f7#file-networks-json

**Describe the results you expected:**
I expect the output contains a container list like the /networks/development request:
https://gist.github.com/Grisu118/1a15ea9a2abb6b04f45eb911a2f1c7f7#file-networks_development-json

**Additional information you deem important (e.g. issue happens only occasionally):**
Worked in 13.x (don't know the exact version which was running before reboot)

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.3
 Git commit:   4845c56
 Built:        Wed Apr 12 22:57:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4845c56
 Built:        Wed Apr 12 22:57:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 28
 Running: 25
 Paused: 0
 Stopped: 3
Images: 37
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.9-coreos
Operating System: Container Linux by CoreOS 1381.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.68GiB
Name: test01
ID: NDXW:B2RO:4U2N:CQRG:P7QK:DT53:DNTE:GH3A:N7IZ:2MSK:HHXC:MRTU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by pitkley** [comment]
If I understand [this comment](https://github.com/moby/moby/blob/7936a962dc5f0f97fa2195c9497bc6e21e13fc2e/api/server/router/network/network_routes.go#L66-L69) correctly, this is (unfortunately?) the expected behaviour starting with API 1.28 (which should map to release 17.04).

If you want detailed information for a single network, you'll have to request it directly using `/networks/<name>`.

**Comment by Grisu118** [comment]
Thanks for the link to the comment, I didn't looked at the code. But in this case api description page should be corrected: https://docs.docker.com/engine/api/v1.28/#operation/NetworkList

**Comment by pitkley** [comment]
I agree, this definitely should be documented somewhere (other than the [API changelog](https://github.com/moby/moby/blob/7936a962dc5f0f97fa2195c9497bc6e21e13fc2e/docs/api/version-history.md#v128-api-changes)), although I am not sure the link you provided would be the right place.

This is something where the maintainers have to chime in though. /cc @thaJeztah
