### ISSUE TITLE
Get real-time stdout from a docker container on a remotely executed command

### ISSUE THREAD

**Issue by ISuckAtPython** [moby/moby#32690]
**Description**

I am trying to get the **real time stdout** from a command I am running in a docker container. However, I need to do this from a remote command run from another host.

When I am on the docker host I can run my docker command with `-it` and get the real time output I need. However, I **have** this constraint where I have to run the command remotely making the previous solution useless. I cannot use `-t` because it runs a pseudo terminal based on $TERM which doesn't exist with the remote command because there is no terminal at all.

I have also tried running the docker command with `-d` to run it in the background and `docker logs -f <container>` but the output is still given all at once at the end of the process.

Any solutions or advice is appreciated.

**Steps to reproduce the issue:**
1. Run remote command  `ssh user@host <docker command with -it>`
2. Error returned: `cannot enable tty mode on non tty input`
3.

**Describe the results you received:**
Error returned: `cannot enable tty mode on non tty input`

**Describe the results you expected:**
Container to run with real time output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 44
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /apps/docker/aufs
 Backing Filesystem: extfs
 Dirs: 376
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.908 GiB
Name: ---
ID: ---
Http Proxy: ---
Https Proxy: ---
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hosts are all VMs

**Comment by cpuguy83** [comment]
Remote or local it does not matter.

Only use `-t` when you need a terminal. If you don't need a terminal, don't use it.
Only use `-i` if you need to copy something to the stdin of the process to be run into the container.

By default `docker run echo hello` will stay attached to the stdout of the container. 

`docker logs -f ` will stream everything that the container has done since the beginning of time and stay attached until you cancel it or the container stops.

If all you need to do is capture stdout, you don't need any extra flags, for example:
```
$ docker run busybox echo hello
hello
```

This is streamed live from the container.

**Comment by ISuckAtPython** [comment]
Thanks for your insight you are right when I have done normal cmd tests the stdout is in real time. However, I am running a python script in this container and it seems to only provide real time stdout when I run the script in a terminal. Running in a container it prints all at once at the end, this may be more of a python problem.

**Comment by danechitoaie** [comment]
@ISuckAtPython Try to add some `sys.stdout.flush()` to your script after you output data and see how it goes. My guess is your output is just buffered.

**Comment by ISuckAtPython** [comment]
Yea you were right

**Comment by cpuguy83** [comment]
Awesome, thanks all!
