### ISSUE TITLE
Cannot start service, lstat /dev/dm-*: no such file or directory

### ISSUE THREAD

**Issue by mkilchhofer** [moby/moby#32699]
**Description**
Over and over again we have issues with privileged containers and devmapper on our rhel7 systems.
Red Hat told us, that this is a known bug. I also found some information about this here: https://github.com/moby/moby/issues/14048

Is there something we can do? We need privileged container, to mount the /dev from the host system to the container. We do this to achieve plug-and-play (hotplug) feature from usb devices (usb-serial).

**Steps to reproduce the issue:**
1. add a service to docker-compose.yaml which has `privileged: true`
2. do some `docker-compose down` and `docker-compose up`

**Describe the results you received:**
````
ERROR: for pegasus  Cannot start service pegasus: linux runtime spec devices: lstat /dev/dm-13: no such file or directory

(...)

ERROR: for pegasus  Cannot start service pegasus: linux runtime spec devices: lstat /dev/mapper/docker-253:0-3294-05d568952f0cb8eba395e25bd32d61a0275063e788be891e4e5a1beb0f1b8947: no such file or directory

````

**Describe the results you expected:**
We expect the same result as on the non-privileged containers: they should start.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens only occasionally. To examine this bug here: https://github.com/moby/moby/issues/32572 I ran into this issue in 49 of 957 times (`docker-compose down; sleep 10; docker-compose up; sleep 300`)

**Output of `docker version`:**
Please note: we see this on all our rhel7 systems with docker 1.9, 1.10, 1.12 and still with docker 1.13, it doesn't matter.

```
[root@eddie027 default]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-common-1.12.6-16.el7.x86_64
 Go version:      go1.7.4
 Git commit:      6774275/1.13.1
 Built:           Tue Mar 21 14:06:29 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-common-1.12.6-16.el7.x86_64
 Go version:      go1.7.4
 Git commit:      6774275/1.13.1
 Built:           Tue Mar 21 14:06:29 2017
 OS/Arch:         linux/amd64
 Experimental:    false
[root@eddie027 default]#
```

**Output of `docker info`:**

```
[root@eddie027 default]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 33
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: rhel-docker--latest--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 17.67 GB
 Data Space Total: 33.44 GB
 Data Space Available: 15.77 GB
 Metadata Space Used: 13.92 MB
 Metadata Space Total: 255.9 MB
 Metadata Space Available: 241.9 MB
 Thin Pool Minimum Free Space: 3.343 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.524 GiB
Name: eddie027.pnet.ch
ID: KN2E:NRWA:HB3W:KIIR:M6GZ:WIXA:GINL:LWF5:HDG5:XT64:IOMC:LMEN
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 26
 System Time: 2017-04-18T21:49:35.546762887+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
[root@eddie027 default]#
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
rhel7.3, physical installation on a single node, docker-latest rpm package

**Comment by agunnerson-ibm** [comment]
This is the same as #32667. There's a race condition in runc that has been fixed upstream, but not merged into the docker repo yet. If you build your own RPMs, you can easily include the patch into your packages.

**Comment by mkilchhofer** [comment]
I reported this to Red Hat. They built us a test package based on docker-1.12 which should include this fix.

I now started my little script again, to validate if this fixes this issue.

**Comment by thaJeztah** [comment]
Adding to the 17.06 milestone, per https://github.com/moby/moby/issues/32667#issuecomment-297153642

**Comment by mkilchhofer** [comment]
The test package from Red Hat mentioned in the comment above https://github.com/moby/moby/issues/32699#issuecomment-297130106 works as expected.

**Comment by thaJeztah** [comment]
pull request for moving runc to master / 1.0-rc is here; https://github.com/moby/moby/pull/33007

**Comment by mlaventure** [comment]
Closing via #33007
