### ISSUE TITLE
vndr makes it impossible to use Docker packages from the outside

### ISSUE THREAD

**Issue by pzduniak** [moby/moby#32709]
I vendor `github.com/opencontainers/go-digest` on my own in order to generate custom images. I need to use the `"github.com/docker/docker/image/v1".CreateID` method to generate a layer and it is impossible, because due to the fact that `vndr` is used over something that flattens dependencies I get the following error:

```
demo.go:10: cannot use i.parent (type "mypath/vendor/github.com/opencontainers/go-digest".Digest) as type "mypath/vendor/github.com/docker/docker/vendor/github.com/opencontainers/go-digest".Digest in argument to v1.CreateID
```

From my perspective the natural solution seems to be to use a non-hipster vendoring tool that handles such cases.

I know this is a duplicate, but this is a pressing issue that has to be solved if you want to break the monolith. The `docker pull` command is broken for us and we have to reimplement the image fetching in our project. Unfortunately this issue prevents us from doing that.

**Comment by vdemeester** [comment]
@pzduniak the current solution is to strip/remove nested vendor (i.e. removing `vendor/github.com/docker/docker/vendor` folder) — just like `vndr` does 👼. And I'm pretty sure quite a lot of other vendoring tool handle this (I know `glide` does).

But It's not really specific to `docker/docker` really, but for *any* golang project that check source in whatever the vendoring tool is used. I know it can be frustrating…

> From my perspective the natural solution seems to be to use a non-hipster vendoring tool that handles such cases.

Trying not being rude, but I really don't see why `vndr` should be call a "hipster vendoring tool", I just don't get the *hipster* adjective here. It's just a simple vendoring tool that does the work we want it to do, nothing more.

**Comment by pzduniak** [comment]
>due to the fact that vndr is used over something that flattens dependencies 

By that I meant that I am pretty sure that the mechanisms of `vndr` are breaking flattening functionality (and by hipster I meant that it seems that only Docker projects are using it). In fact I had an environment variable set that disabled vendor directory flattening in the versioning manager that I use. Oops, my bad!
