### ISSUE TITLE
Intermittent "oci runtime error" when using ContainerExecAttach

### ISSUE THREAD

**Issue by olovpe** [moby/moby#32702]
**Description**
I'm writing an application that uses the docker api to start and run commands in containers, using the golang api. When using ContainerExecCreate and ContainerExecAttach I get different results when running the same code, either it hangs when reading, or some oci runtime error.

**Steps to reproduce the issue:**
1. Start a container using ContainerStart, do not attach
2. Create an exec command in the container
3. Start and Attach to the exec process

**Describe the results you received:**
I get four types of results,
1. Client hangs when copying from HijackedResponse
2. Client runs, but no output is received
2. time="2017-04-19T02:42:31.891021017Z" level=error msg="Error running exec in container: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec f
ailed: container_linux.go:247: starting container process caused \\\"process_linux.go:92: setting oom score caused "write /proc/24410/oom_score_adj: invalid argume
nt
3. rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:83: executing setns process caused \\\"exit status 16\\\"\"\n"

These are the options I use when starting the container:
{\"AttachStderr\":false,\"AttachStdin\":false,\"AttachStdout\":false,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":null,\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":null,\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":null,\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":null,\"NetworkMode\":\"\",\"OomKillDisable\":null,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"reg.i.strikingly.com/bobcat:develop_a6b13ff\",\"Labels\":null,\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":null,\"WorkingDir\":\"\"}"

These are the options I use when attaching:
{\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"ls\"],\"Detach\":false,\"DetachKeys\":\"\",\"Env\":[\"FOO=bar\"],\"Privileged\":false,\"Tty\":true,\"User\":\"root\"}

When the client is hanging, I get the following stacktrace from the server:
goroutine 22 [running]:
main.dumpStacks()
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:102 +0x98
main.setupDumpSt
acksTrap.func1(0xc820132600)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:114 +0x5e
created by main.setupDumpStacksTrap
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292
d9eca8/containerd/main.go:116 +0x13f

goroutine 1 [chan receive, 30 minutes]:
main.daemon(0xc82016e3c0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:191 +0x9d2
main.main.func2(0xc82016e3c0)

\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:150 +0x25
github.com/codegangsta/cli.(*App).Run(0xc82016e280, 0xc82000a270, 0xd, 0xd, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457
815ee76b7e5dd2a01292d9eca8/vendor/src/github.com/codegangsta/cli/app.go:192 +0x117d
main.main()
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:154 +0x320

goroutine 17 [syscall, 30 minutes, locked to thre
ad]:
runtime.goexit()
\t/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x7fc866051078)
\t/usr/lib/golang/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
\t/usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18\
ncreated by os/signal.init.1
\t/usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [IO wait, 5 minutes]:
net.runtime_pollWait(0x7fc8648186e8, 0x72, 0xc82022c000)
\t/usr/lib/golang/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82000c220, 0
x72, 0x0, 0x0)
\t/usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82000c220, 0x0, 0x0)
\t/usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82000c1c0, 0xc82022c000, 0x8000, 0x8000, 0x0, 0x7fc866051050, 0xc82001202
8)
\t/usr/lib/golang/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200203a8, 0xc82022c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
\t/usr/lib/golang/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820056360)
\t/usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Read
er).Read(0xc820056360, 0xc8201000f8, 0x9, 0x9, 0x0, 0x0, 0x0)
\t/usr/lib/golang/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fc8660559e0, 0xc820056360, 0xc8201000f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
\t/usr/lib/golang/src/io/io.go:297 +0xe6
io.ReadFull(0x7fc8660559e0
, 0xc820056360, 0xc8201000f8, 0x9, 0x9, 0xc820001680, 0x0, 0x0)
\t/usr/lib/golang/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8201000f8, 0x9, 0x9, 0x7fc8660559e0, 0xc820056360, 0x20000000, 0x0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/cont
ainerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201000c0, 0x0, 0x0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/
vendor/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820139bf0, 0x0, 0x0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/tra
nsport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc82005a120, 0xc820139c80)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/transport/http2_server.g
o:243 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc8201ba090, 0x7fc866055a30, 0xc82005a120)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:350 +0x159
google.golang.org/g
rpc.(*Server).serveNewHTTP2Transport(0xc8201ba090, 0x7fc866055930, 0xc8200203a8, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:337 +0x49d
google.golang.org/grpc.(*Server)
.handleRawConn(0xc8201ba090, 0x7fc866055930, 0xc8200203a8)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf654578
15ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:314 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:286 +0x372

goroutine 19 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0xfc4000)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/github.com/rcrowley/go-metrics/meter.go:221 +0x4b
created by github.com/rcrowley/go-metrics.NewMeter
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/github.com/rcrowley/go-metrics/meter.go:40 +0x154

goroutine 21 [select, 30 minutes, locked to thread]:
runtime.gopark(0xbae678, 0xc820018728, 0xaad448, 0x6, 0x18, 0x2)
\t/usr/lib/golang/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820018728, 0x0, 0x18)
\t/usr/lib/golang/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820018728)
\t/usr/lib/golang/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
\t/usr/lib/golang/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
\t/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

goroutine 23 [syscall, 5 minutes]:
syscall.Syscall6(0xe8, 0x3, 0xc8200328b8, 0x80, 0xffffffffffffffff, 0x0, 0x0, 0x9ca9c0, 0xc820482220, 0x4d6434)
\t/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x3, 0xc8200328b8, 0x80, 0x80, 0xffffffffffffffff, 0xc82011aae8, 0x0, 0x0)
\t/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:365 +0x89
github.com/docker/containerd/archutils.EpollWait(0x3, 0xc8200328b8, 0x80, 0x80, 0xffffffffffffffff, 0x1, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/archutils/epoll.go:21 +0x58
github.com/docker/containerd/supervisor.(*Monitor).start(0xc8201ac6f0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/monitor_linux.go:93 +0xcb
created by github.com/docker/containerd/supervisor.NewMonitor
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/monitor_linux.go:24 +0x194

goroutine 24 [chan receive, 5 minutes]:
github.com/docker/containerd/supervisor.eventLogger.func1(0xc8201dc000, 0xc8201200f0, 0xc820132ea0, 0x1f4, 0xc82011b310, 0xc82011d780, 0x33)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:81 +0x13e
created by github.com/docker/containerd/supervisor.eventLogger
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:120 +0x161

goroutine 25 [chan receive, 5 minutes]:
github.com/docker/containerd/supervisor.(*Supervisor).exitHandler(0xc8201dc000)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:296 +0x5c
created by github.com/docker/containerd/supervisor.New
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:50 +0x3fc

goroutine 26 [chan receive, 30 minutes]:
github.com/docker/containerd/supervisor.(*Supervisor).oomHandler(0xc8201dc000)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:305 +0x5c
created by github.com/docker/containerd/supervisor.New
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:51 +0x41e

goroutine 27 [chan receive, 5 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b350)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 28 [chan receive, 30 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b360)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 29 [chan receive, 30 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b370)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 30 [chan receive, 22 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b380)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 31 [chan receive, 22 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b390)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 32 [chan receive, 13 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b3a0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 33 [chan receive, 13 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b3b0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 34 [chan receive, 9 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b3c0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 35 [chan receive, 9 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b3d0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 36 [chan receive, 7 minutes]:
github.com/docker/containerd/supervisor.(*worker).Start(0xc82011b3e0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/worker.go:42 +0xb1
created by main.daemon
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:176 +0x6bb

goroutine 37 [chan receive, 5 minutes]:
github.com/docker/containerd/supervisor.(*Supervisor).Start.func1(0xc8201dc000)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:276 +0x58
created by github.com/docker/containerd/supervisor.(*Supervisor).Start
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/supervisor/supervisor.go:279 +0x439

goroutine 38 [IO wait, 30 minutes]:
net.runtime_pollWait(0x7fc8648187a8, 0x72, 0x0)
\t/usr/lib/golang/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820186840, 0x72, 0x0, 0x0)
\t/usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820186840, 0x0, 0x0)
\t/usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201867e0, 0x0, 0x7fc864818980, 0xc8200fdee0)
\t/usr/lib/golang/src/net/fd_unix.go:426 +0x27c
net.(*UnixListener).AcceptUnix(0xc820165e00, 0xc82003de48, 0x0, 0x0)
\t/usr/lib/golang/src/net/unixsock_posix.go:305 +0x53
net.(*UnixListener).Accept(0xc820165e00, 0x0, 0x0, 0x0, 0x0)
\t/usr/lib/golang/src/net/unixsock_posix.go:315 +0x41
google.golang.org/grpc.(*Server).Serve(0xc8201ba090, 0x7fc864817800, 0xc820165e00, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:277 +0x1b5
main.startServer.func1(0xc82011d947, 0x34, 0xc8201ba090, 0x7fc864817800, 0xc820165e00)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:220 +0x132
created by main.startServer
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/containerd/main.go:223 +0x347

goroutine 10 [select, 30 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc82005a120)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/transport/http2_server.go:652 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/transport/http2_server.go:134 +0x84f

goroutine 39 [chan receive, 5 minutes]:
github.com/docker/containerd/api/grpc/server.(*apiServer).Events(0xc820120110, 0xc820244040, 0x7fc864818d70, 0xc82011b6f0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/api/grpc/server/server.go:328 +0x264
github.com/docker/containerd/api/grpc/types._API_Events_Handler(0xa753e0, 0xc820120110, 0x7fc864818c50, 0xc820122680, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/_build/src/github.com/docker/containerd/api/grpc/types/api.pb.go:1253 +0x175
google.golang.org/grpc.(*Server).processStreamingRPC(0xc8201ba090, 0x7fc866055a30, 0xc82005a120, 0xc8201341c0, 0xc820165e40, 0xfa27e0, 0xc8201acff0, 0x0, 0x0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:602 +0x47a
google.golang.org/grpc.(*Server).handleStream(0xc8201ba090, 0x7fc866055a30, 0xc82005a120, 0xc8201341c0, 0xc8201acff0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:686 +0x114e
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82012ca70, 0xc8201ba090, 0x7fc866055a30, 0xc82005a120, 0xc8201341c0)
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:348 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
\t/builddir/build/BUILD/docker-1.12.6/containerd-2a5e70cbf65457815ee76b7e5dd2a01292d9eca8/vendor/src/google.golang.org/grpc/server.go:349 +0x9a

**Describe the results you expected:**
Running the command and getting the output on a HijackedResponse reader

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Tue Mar  7 20:34:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Tue Mar  7 20:34:04 2017
 OS/Arch:      linux/amd64
```
(paste your output here)
```

**Output of `docker info`:**
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 94
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 14.37 GB
 Data Space Total: 306 GB
 Data Space Available: 291.6 GB
 Metadata Space Used: 4.837 MB
 Metadata Space Total: 3.217 GB
 Metadata Space Available: 3.212 GB
 Thin Pool Minimum Free Space: 30.6 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.41-35.53.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.8 GiB
Name: ip-10-200-1-5
ID: D5CF:65CN:ULWW:SE5N:FREC:6JI3:S5ED:W6V3:BCKF:35UR:QBP2:XGNG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 93
 System Time: 2017-04-19T03:07:08.684198936Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
NAME="Amazon Linux AMI"
VERSION="2016.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.09"
PRETTY_NAME="Amazon Linux AMI 2016.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
