### ISSUE TITLE
"hello-world" doesn't work on Raspberry Pi

### ISSUE THREAD

**Issue by NonCreature0714** [moby/moby#32705]
**Description**
Simply put, ```$ sudo docker run hello-world``` doesn't work on Raspberry Pi becuase the hello-world container is not armhf.

**Steps to reproduce the issue:**
1. Try running ```$ sudo docker run hello-world``` on Raspbian (I have a Raspberry Pi 3.)
2. Watch it fail

**Describe the results you received:**
I receive an error message: 
>``` standard_init_linux.go:178: exec user process caused "exec format error" ```

**Describe the results you expected:**
I expected to see the usual "hello-world" response, especially since it seems there is a base armhf container available.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens every time.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.50-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.5MiB
Name: raspi
ID: S432:YNOU:2KH3:GGLE:I6GK:5ZTI:4JCE:2D5S:L5UM:4GF4:F3ZP:EWA5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: noncreature0714
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
`armhf/hello-world`

Closing as this is not an issue.
There is a similar issue about updating the docs to hint that `hello-world` is x86-64 only.
