### ISSUE TITLE
I cannot deploy any template....

### ISSUE THREAD

**Issue by akdj** [moby/moby#32706]
In fact, I built an image with fabric8, Jenkins, in my project named Application, then it created automatically a new project named application-staging. 

Then I tried to deploy in this staging project, a MongoDB persistent template and a MySQL persistent template that I found on Openshift Origin platform. 
For that, I created firstly persistent volumes, and when I deployed these two templates, theses volumes are bound. So I thought all steps are done perfectly. 

However, it displayed that the MongoDB persistent deployment and MySQL persistent deployment are failed. 

![failed_19042017](https://cloud.githubusercontent.com/assets/4325679/25169215/7d596a2a-24e6-11e7-8dbb-05439de6d4d8.PNG)

when I checked pods, the MongoDB-deploy pod and MySQL-deploy pod were running, but the two others pods(with random tail-names) MongoDB-xxxxx and MySQL-xxxxx showed "Err image pull" or "Image pull back off" messages....  
![failed2_19042017](https://cloud.githubusercontent.com/assets/4325679/25169228/915907c4-24e6-11e7-84ef-b99134daf9a0.PNG)

![failed3_19042017](https://cloud.githubusercontent.com/assets/4325679/25169237/96b3cc68-24e6-11e7-9b85-bd91d3768dea.PNG)

I don't know in which step I made a mistake.

I am using : 
openshift origin v1.2.1   1.el7
docker  v1.12.6 11.el7.centos
kubernetes v1.5.2  0.2.gitc55cf2b.el7
fabric8 v2.2.26

**Comment by cpuguy83** [comment]
These error messages are not from Docker (at least not directly).
Please open an issue with openshift.
