### ISSUE TITLE
Is there any way to prevent people get inside docker?

### ISSUE THREAD

**Issue by kanezch** [moby/moby#32710]
we need to deploy a docker in my client's environment, inside of it  the source code is written by nodejs, which is plain text, and we don't want the client see the source code.
I know one can get inside a docker by Command like "docker exec" without any password, so I was wondering if there is any way to prevent my client get my source code even he has the root account, can we just set a password that only known by ourselves? 
3ks

**Comment by AkihiroSuda** [comment]
No.  You need to use some obfuscator or switch to other languages for that purpose

**Comment by thaJeztah** [comment]
Correct; if you ship the code, users can simply extract the files from the image (so they don't event have to _run_ the image or exec into the container.

I'll close this issue because I think the question is answered, but feel free to continue the discussion
