### ISSUE TITLE
dockerd consuming very high memory ~ 12GB and growing.

### ISSUE THREAD

**Issue by Eshakk** [moby/moby#32728]
**Description**

This is happening after a containerd crash and only some containers are unresponsive. `docker stats` are not showing any values. We have 10 containers running at any given point in time.

I have attached logs after sending SIGUSR1 to dockerd. Please let me know if you need anything else.

I have also attached pmap output to see actual memory usage of dockerd process.

```
ps -aux --sort -rss | less       

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      1809  4.3 19.8 27267880 12299520 ?   Ssl  Apr15 287:01 dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock --bip={ip} --log-driver=json-file --log-opt max-size=16m --log-opt max-file=3 --selinux-enabled
```

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Fri Mar 31 02:09:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Fri Mar 31 02:09:07 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.16-coreos-r1
Operating System: Container Linux by CoreOS 1298.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 46
Total Memory: 58.98 GiB
Name: ace-mfusion1-sjc.cisco.com
ID: XW6K:MQM5:SLJ5:57JF:C52N:G6J4:FT3R:NGAP:7NBC:KVF3:MHYM:GEWH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

[dockerd_sigusr1.txt](https://github.com/moby/moby/files/938917/dockerd_sigusr1.txt)

[dockerd_pmap_XX.txt](https://github.com/moby/moby/files/938918/dockerd_pmap_XX.txt)

**Comment by baillieny** [comment]
I'm seeing the same symptoms (not using swarm)

docker info
Containers: 68
 Running: 19
 Paused: 0
 Stopped: 49
Images: 85
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-rancher
Operating System: RancherOS v1.0.0
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 15.67 GiB
Name: DEVDC1MMAX14
ID: BJAD:JZTL:WXKZ:6SJH:AMOL:4457:NKS7:QOJL:MF3W:K4BY:FYEB:I2QM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 137
 Goroutines: 119
 System Time: 2017-05-31T01:41:15.74976683Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker-mirror.docker.tattsgroup.com/
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
Similar issue was reported in https://github.com/moby/moby/issues/32711; there's some instructions there to obtain more debugging information

/cc @unclejack

**Comment by unclejack** [comment]
I'll close this now. I'm not convinced this isn't the same issue as #32711 or one of the other goroutine leaks which have been fixed already.

Please feel free to comment if you can provide the bits of information the same way they were provided on #32711.
