### ISSUE TITLE
Docker Windows - Could not read CA certificates

### ISSUE THREAD

**Issue by ZukkyBaig** [moby/moby#32726]
Hi,

Problem: Trying to start Docker client I get the following error:

> 
> "could not read CA certificate "C:\\WINDOWS\\system32\\config\\systemprofile\\.docker\\ca.pem": open C:\WINDOWS\system32\config\systemprofile\.docker\ca.pem: The system cannot find the file specified.
> 
>    at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
>    at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)"

I have tried absolutely everything to no avail. I have tried installing docker-machine, changing DockerNAT switches, uninstalling Docker, uninstalling Hyper-V, installing edge release, stable release, tried generating CA certificates using different tools, yet, I still receive the above error.

Can you please help me, I have no idea what else I can do.

**Comment by ZukkyBaig** [comment]
Diagnostic ID: C3F03BCC-CD83-428B-B902-32CAAE6A7CE9/2017-04-19_23-41-15

**Comment by thaJeztah** [comment]
Looks like this is an issue with Docker for Windows; if you're still having this issue, can you report this in the Docker for Windows issue tracker? https://github.com/docker/for-win/issues

I'll close the issue here
