### ISSUE TITLE
too many links error

### ISSUE THREAD

**Issue by lipg** [moby/moby#32732]
Docker build command error, using the docker rmi $(docker images - q) after good, but after some time, errors will appear again.

like:
/data/docker/runtime/overlay/49d96405b7d1ab2cc1c9f815347cf9716c3088b2db10ca3d36a894948b1e1a5c/root/var/lib/yum/yumdb/p/cf1f195f6bf8d654d694b941ead72c4c51798536-pcre-8.32-15.el7_2.1-x86_64/checksum_type /data/docker/runtime/overlay/1044d44c019cdd45df59c6df727dfef476decdc976477ab1124c0a0bf5735e10/tmproot559734426/var/lib/yum/yumdb/p/cf1f195f6bf8d654d694b941ead72c4c51798536-pcre-8.32-15.el7_2.1-x86_64/checksum_type: too many links

<img width="894" alt="error" src="https://cloud.githubusercontent.com/assets/7782635/25211712/2619ff30-25b9-11e7-9cc6-42a384af0dcb.png">

df -iTh:

<img width="707" alt="filesystem" src="https://cloud.githubusercontent.com/assets/7782635/25211706/1669c566-25b9-11e7-846a-287afc0bceb2.png">

Docker Info:
Containers: 21
 Running: 3
 Paused: 0
 Stopped: 18
Images: 1264
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.53 GiB
Name: cloud-ci
ID: E36C:XAF5:Q2MV:I2PG:YGSA:3K4Q:5ODN:7BE7:SYWF:22DJ:WO5Z:G346
Docker Root Dir: /data/docker/runtime
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by cpuguy83** [comment]
Can you describe what these images look like?
`too many links` would seem to imply that you've hit the 65k max that the kernel allows.

Note that with `overlay` docker has to create hardlinks to each object in the lower layer.
Most users tend to hit a limit on inodes before hitting any other kernel limits but it seems like you have *lots* of inodes (and are using lots).

**Comment by lipg** [comment]
I'm sorry, I don't know how to provide more information, please teach me。
but my project is based on a Centos image.And I don't have so many images, how can have so many links?
The same build cache will there be new layer? not be a layer? And will not be deleted?

**Comment by cpuguy83** [comment]
@lipg For each file that exists in an image layer, a hardlink will be created in the next layer.

**Comment by cpuguy83** [comment]
I would suggest trying the `overlay2` driver, but note you will not be able to access images/containers created with `overlay` unless you switch back.

**Comment by GeekWolfBoy** [comment]
原因及处理： 当没有设置 --disable-legacy-registry 时，硬连接数占满也会抛上面的错，如果设置了该参数，抛出来的应该是 too many links。在 EXT4 文件系统上，单个文件的 Hard link 数的上限是 65535，有哪个文件会做这么多硬链接呢？就有这么一种巧合，Centos 7 下 yum 每个安装的软件都有个 checksum_type，以硬链接的方式存在，我们的一个镜像大概 140+ 硬链接，而镜像文件系统 OverlayFS 也会对这个文件进行硬链接，所以单个主机基于centos 7的镜像大概也就容纳 400+。处理方式是清理镜像，也可以在基础镜像中破坏硬链接。检测方式 find 查找到一个 checksum_type 文件，再 stat 查看 Links 数。
referencement：https://blog.xiaoyunlong.com/2017/04/22/docker-troubles/

**Comment by unclejack** [comment]
The number of images seems pretty high: `Images: 1264`. This is most likely one of the reasons why that error is encountered.

As @cpuguy83 has already suggested, the overlay2 storage driver would help avoid this in the future for new deployments.

The unneeded images can be cleaned up to avoid the issue for this setup. The command `docker image prune` will help clean up old images which aren't tagged.

I'll close this issue now. Multiple solutions have been provided. Please feel free to comment if you have any other questions. There's no need to open another issue.

**Comment by chestack** [comment]
cd  /var/lib/docker/overlay
for d in `find ./ -name "yumdb" -type d`; do rm -rf $d; done

**Comment by jchendsny** [comment]
chestack commented on Dec 22, 2017 >> worked for me

**Comment by harryge00** [comment]
I wonder if overlay2 can solve this problem and why?
