### ISSUE TITLE
Swarm Mode: Docker Overlay network occasionally stop working

### ISSUE THREAD

**Issue by muhammadwaheed** [moby/moby#32738]
**Description**

I am running  docker swarm cluster on Ubuntu 14.04.5 LTS with Kernel Version: 4.4.0-66-generic.I have 3 nodes in the  swarm cluster(two workers, one master) hosted on DigitalOcean. I have created a swarm using the following command:
docker stack deploy -c docker-compose.yml app
All the services successfully started as expected. Containers are up and running over the swarm overlay app_default network.I have tested the functionality of app, initially it was working fine but after sometime request start hanging and request timeout. I continously monitored the services and tail the docker daemon log ,all services were up and there was no error log  that relate to  this issue.
I wanted to mention as well, if i remove the stack and deploy again.Everything will work for short period of time but after sometime requests timeout randomly.

**Steps to reproduce the issue:**
1. Deploy the swarm stack using: docker stack deploy -c docker-compose.yml app
2. Make sure all the services up and replicated
3. overlay swarm network app_default created  on all nodes and all the containers attached to this network
4. After sometime requests randomly timeout.

**Describe the results you received:**
Request timeout randomly

**Describe the results you expected:**
I expected 0% request timeout and request should response back with valid status code.

**Additional information you deem important (e.g. issue happens only occasionally):**
Intermittently happens.I was able to ping/curl the containers when this issue occurred. I am running all swarm node in same DigitalOcean region.
**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: wp6iodt7zb0y64gytv0oixmus
 Is Manager: true
 ClusterID: u76sbtb388mypn1bcjs4zrjeb
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: swarm-01
ID: K7XN:2IOB:IEL7:OPU5:N4FJ:TS3J:FEZE:XCRO:CFFM:O2H5:FD4N:RZDC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxx
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Output of `docker network inspect my-network`:**

```
[
    {
        "Name": "my-network",
        "Id": "0kvlo5g2xtudt0kg2mt8ll9mu",
        "Created": "2017-04-19T07:48:44.587949277Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Containers": {
            "162544cafca3c639440760464806ca3906fbc9a9f9e27361029b33e156435f1e": {
                "Name": "app_rabbit.1.ta41hjabwjwta5zv9ng8ahrj0",
                "EndpointID": "8b4c84d853f700f28fa169a8f69dfa072a0b326fbfb866895bffbbcbe07dfecc",
                "MacAddress": "02:42:0a:00:01:0a",
                "IPv4Address": "10.0.1.10/24",
                "IPv6Address": ""
            },
            "ce893165b2e8b11e98e837100bd54a0535bb9f315f4686466d6d617b48e24128": {
                "Name": "app_app.1.bdk17oh2tubm5gnrae1wx4abv",
                "EndpointID": "e11fe72edf7682627e88c605ce1b57ca201634af5b90a572077f81c42695a7d8",
                "MacAddress": "02:42:0a:00:01:11",
                "IPv4Address": "10.0.1.17/24",
                "IPv6Address": ""
            },
            "d59d7ec0d4ab2029ae86705bca31a25349a43a2244c66814b04de7d8b15b3a71": {
                "Name": "app_worker.1.oayvn6dop0tbrteubriknrha2",
                "EndpointID": "12e7fd96c44a764c5bb3019572141f9f783f23b79c6ddb24f95e3982216edae0",
                "MacAddress": "02:42:0a:00:01:0b",
                "IPv4Address": "10.0.1.11/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "swarm-01-0f0a52901058",
                "IP": "x.x.x.x"
            },
            {
                "Name": "swarm-02-81973dee7ab9",
                "IP": "x.x.x.x"
            },
            {
                "Name": "swarm-03-7767a47e66ce",
                "IP": "x.x.x.x"
            }
        ]
    }
]
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
3-node Swarm Mode cluster (3 ubuntu 14.04.5 LTS  VMs on DigitalOcean)

**Comment by Fank** [comment]
@muhammadwaheed It looks line its related to #32195

**Comment by Paxxi** [comment]
We are also seeing this behavior, running 3 nodes on Ubuntu 16.04 on digital ocean. Intermittently one or more nodes start reporting unreachable hosts and sometimes without anything logged it seems routing to a container fails. 

Have experienced it with 1.13, 17.03 and 17.04

**Comment by Fank** [comment]
@muhammadwaheed could you show the log from syslog, during the request timeout? from all nodes, there could be some usefull information.

**Comment by muhammadwaheed** [comment]
@Fank 
Thanks for your prompt response. please see the following gist link for syslog from all  nodes.
Manager node
https://gist.github.com/muhammadwaheed/12a5c849727de2913aa7f9c87bad39b5
worker1 node
https://gist.github.com/muhammadwaheed/21066c92efb73ffd95baa8067aa19e13
worker2 node
https://gist.github.com/muhammadwaheed/5fd49e7eff833497ddd35401af56cb70

**Comment by vkozlovski** [comment]
Hi @Fank.

I had the same problem. The reason was in virtual IP address (VIP) and It is enabled by default. I turned off the VIP everywhere and the problems with the network connection stopped.

To disable to use the virtual IP address, you must start the services with the following option `--endpoint-mode dnsrr`. For example:
```
$ docker service create \
  --replicas 3 \
  --name my-dnsrr-service \
  --network my-network \
  --endpoint-mode dnsrr \
  nginx
```

If you can't use this option to start your services (for example, you start them with `docker-stack.yml`), then you can access to your services by name: `tasks.my-service` (not `my-service`). In this case you will not be used virtual ip address. 

From the documentation:
```
$ nslookup my-service

Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      my-service
Address 1: 10.0.9.2 ip-10-0-9-2.us-west-2.compute.internal
```

`10.0.9.2` - it is virtual ip address.

and:

```
$ nslookup tasks.my-service

Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      tasks.my-service
Address 1: 10.0.9.4 my-web.2.6b3q2qbjveo4zauc6xig7au10.my-network
Address 2: 10.0.9.3 my-web.1.63s86gf6a0ms34mvboniev7bs.my-network
Address 3: 10.0.9.5 my-web.3.66u2hcrz0miqpc8h0y0f3v7aw.my-network
```

`10.0.9.4`, `10.0.9.3` and `10.0.9.5` - These are "real" ip addresses of containers with your services.

For more information read this https://docs.docker.com/engine/swarm/networking/#use-dns-round-robin-for-a-service

**Comment by oeuftete** [comment]
I think this is still an issue.  I've never been able to use `vip` endpoint mode with our Swarm Mode stack configuration... just now have confirmed the same problem using 18.03.  It always will run fine immediately, but after somewhere around 20-30 minutes, some connections no longer pass information, though they show as established when looking at connections with `ss`/`netstat`.

Using`dnsrr` endpoint mode as suggested above solves the problem.  Any suggestions on how to provide information to help get to the bottom of this?

**Comment by fcrisciani** [comment]
@oeuftete conntrack timeout is 15min, so if the connection remains idle for more than that the conntrack entry is deleted and the connection has to be established from scratch. The solution is to enable tcp keepalive to keep long standing connection fresh from conntrack point of view

**Comment by robvelor** [comment]
@oeuftete Check this https://success.docker.com/article/ipvs-connection-timeout-issue

**Comment by tartemov** [comment]
I have some similar issue - some container doesn't see another container or can't connect to container service. I've founded some overlaps IP (for my service and internal lb-service) in network info from different nodes:

`[root@sel-kno-app02 artemov]# docker network inspect d7dyqz1jpt71
[
    {
        "Name": "dev01-mon",
        "Id": "d7dyqz1jpt71ycscbh8fe5q37",
        "Created": "2020-10-20T09:16:15.346448337Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.34.0/24",
                    "Gateway": "10.0.34.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "b78a15e9bb36bcdb7ec0c60bdee087c248ff4c57007013bcaf49cb6ebdebacf2": {
                "Name": "dev01_backend.1.xogtd2v74lm1rmf0o5ykw97z1",
                "EndpointID": "11e5be8c40a351ac96ef46805a43ec105d08fd7138e16fd150e2f631408c33c0",
                "MacAddress": "02:42:0a:00:22:28",
                "IPv4Address": "10.0.34.40/24",
                "IPv6Address": ""
            },
            "cce03cc7b8e756e7dcd89ae66d6fb0ecbaccb52f00104fc97119eba70a1b3583": {
                "Name": "dev01_redis-ha-exporter.1.m58stakiurz0irieuvgtaiu91",
                "EndpointID": "386e73533b4fa1fea94f07f566c03311f0279ef4082ce90a65cf48bd2836d2da",
                "MacAddress": "02:42:0a:00:22:0c",
                "IPv4Address": "10.0.34.12/24",
                "IPv6Address": ""
            },
            "lb-dev01-mon": {
                "Name": "dev01-mon-endpoint",
                "EndpointID": "5c4ee473546c516021698cf4fbf123aab72ae9e5c19ecba34d1ff0b01d12a896",
                "MacAddress": "02:42:0a:00:22:08",
                "IPv4Address": "10.0.34.8/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4130"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "5771667d314d",
                "IP": "192.168.142.7"
            },
            {
                "Name": "e124c9f495c7",
                "IP": "192.168.142.9"
            },
            {
                "Name": "2b4c6667205c",
                "IP": "192.168.142.12"
            },
            {
                "Name": "1104fc21cc37",
                "IP": "192.168.142.13"
            },
            {
                "Name": "3722a18a83ad",
                "IP": "192.168.142.8"
            },
            {
                "Name": "7d6fc113966b",
                "IP": "192.168.142.15"
            }
        ]
    }
]`

another node:
`[root@sel-kno-app01 artemov]# docker network inspect d7dyqz1jpt71
[
    {
        "Name": "dev01-mon",
        "Id": "d7dyqz1jpt71ycscbh8fe5q37",
        "Created": "2020-10-20T09:05:57.170856895Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.34.0/24",
                    "Gateway": "10.0.34.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "3c1253b5379d98c74096abc67e03c5916de07cdd440dc6228c14fe841ac1012d": {
                "Name": "dev01_integration-journal.1.wtmky7nf2hqqjbuyhdh8nuuel",
                "EndpointID": "3158a3a48b42d9b7a3eb7d73386db7688b6eef473b3eb216565179ee5df0e974",
                "MacAddress": "02:42:0a:00:22:08",
                "IPv4Address": "10.0.34.8/24",
                "IPv6Address": ""
            },
            "9f5372b97c48fa27763193b91cda08ca2f5327542bb22304bfa67e1a4ea82ae5": {
                "Name": "mon_prometheus.1.34k7inwv123ps4ld9dkb098o9",
                "EndpointID": "8143e4b749e230f82210ce4f3e2c53ec70e6c2e6b44e4fb75bd5f4fc0442b90a",
                "MacAddress": "02:42:0a:00:22:12",
                "IPv4Address": "10.0.34.18/24",
                "IPv6Address": ""
            },
            "lb-dev01-mon": {
                "Name": "dev01-mon-endpoint",
                "EndpointID": "d32fdc13e10f5ce29b25684a7aa2c56806c409abb57397802aed734d61d46419",
                "MacAddress": "02:42:0a:00:22:02",
                "IPv4Address": "10.0.34.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4130"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "e124c9f495c7",
                "IP": "192.168.142.9"
            },
            {
                "Name": "5771667d314d",
                "IP": "192.168.142.7"
            },
            {
                "Name": "2b4c6667205c",
                "IP": "192.168.142.12"
            },
            {
                "Name": "1104fc21cc37",
                "IP": "192.168.142.13"
            },
            {
                "Name": "7d6fc113966b",
                "IP": "192.168.142.15"
            },
            {
                "Name": "3722a18a83ad",
                "IP": "192.168.142.8"
            }
        ]
    }
]`

IP 10.0.34.8 overlaps for integration_journal service and some lb- service.
When I try to connect to my service from different containers some connections failed, some connected successfully   
`
[root@d94f82e5513d /]# telnet 10.0.34.8 8085
Trying 10.0.34.8...
telnet: connect to address 10.0.34.8: Connection refused

[root@fd01fa4f1a72 /]# telnet 10.0.34.8 8085
Trying 10.0.34.8...
Connected to 10.0.34.8.
Escape character is '^]'.
`

Seems that these overlapping IP issue broke connectivity for service.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
