### ISSUE TITLE
Disable credsStore?

### ISSUE THREAD

**Issue by olalonde** [moby/moby#32733]
I'm trying to follow the following instructions for K8s: https://kubernetes.io/docs/concepts/containers/images/#bypassing-kubectl-create-secrets

However, I'm not able to complete the instructions because my docker config looks like this:

```json
{
        "auths": {
                "MY_AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com": {}
        },
        "credsStore": "osxkeychain"
}
```

I was wondering if it was possible to disable the credsStore and inside get docker login to use the old style config file?

**Comment by thaJeztah** [comment]
If you remove the "credstore" entry, it should use the old mechanism

**Comment by olalonde** [comment]
I've tried deleting `~/.docker/config.json` removing the `credsStore` key and setting it to false but no matter what, it keeps giving me the same end result.

**Comment by thaJeztah** [comment]
@olalonde can you report that in the Docker for Mac issue tracker? https://github.com/docker/for-mac/issues

I'll close the issue here because it's specific to docker for mac, but feel free to continue the conversation

**Comment by faucherb94** [comment]
This is not a mac specific issue. If you have a docker credential helper installed (e.g. `docker-credential-osxkeychain` or `docker-credential-pass`), docker will __always__ use it, even if you remove the `credsStore` field from config.json, even if you delete config.json. The only way I've found around this is rename all of your `docker-credential-<service>` to something else so docker doesn't recognize it has any credential helpers installed, then docker will save your creds unencrypted in config.json.
