### ISSUE TITLE
Change image tag to digest is the right way in swarm mode ?

### ISSUE THREAD

**Issue by xianlubird** [moby/moby#32736]
**Description**
When I use `docker service create nginx:1.7` to create a service, docker will change my image name from `nginx:1.7` to `nginx@sha256:xxxxxxxxxx` style.  Then when I run `docker images`, I can not find tag 1.7 image.

**Steps to reproduce the issue:**
1. docker service create nginx:1.7
2. docker images

**Describe the results you received:**
docker images have no tag.

**Describe the results you expected:**
```
// pin image by digest
if os.Getenv("DOCKER_SERVICE_PREFER_OFFLINE_IMAGE") != "1" {
	digestImage, err := c.imageWithDigestString(ctx, newCtnr.Image, authConfig)
	if err != nil {
		logrus.Warnf("unable to pin image %s to digest: %s", newCtnr.Image, err.Error())
		// warning in the client response should be concise
		resp.Warnings = append(resp.Warnings, digestWarning(newCtnr.Image))
	} else if newCtnr.Image != digestImage {
		logrus.Debugf("pinning image %s by digest: %s", newCtnr.Image, digestImage)
		newCtnr.Image = digestImage
	} else {
		logrus.Debugf("updating service using supplied digest reference %s", newCtnr.Image)
	}
}
```
 From code, I find that there's a env to control this,. Is it a right way to change tag to digest when creating service ?

**Comment by nishanttotla** [comment]
@xianlubird check this issue: https://github.com/moby/moby/issues/31656

Currently, the lack of a tag is an issue with `docker/distribution` not creating local tags. The ENV var is only for test purposes, and not recommended.

Starting with 17.06, you'll be able to control whether or not the image should be resolved to digest using a CLI flag.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.


For the original question; yes it's intentional to pin the services by digest; that way it's guaranteed that all instances run the same version of the image.
