### ISSUE TITLE
The requested URL returned error: 416 Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by jhabdas** [moby/moby#32757]
Sorry, your issue template started giving me a headache. Here's the problem:

```
sudo yum-config-manager   --add-repo     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
https://download.docker.com/linux/centos/docker-ce.repo: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 416 Requested Range Not Satisfiable"
Trying other mirror.
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 416 Requested Range Not Satisfiable"
```

Occurred while trying to follow https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository. Not sure what's going on there.

```
uname -r
2.6.32-696.1.1.el6.x86_64
```

https://forums.docker.com/t/cannot-install-docker-on-amazon-linux/28917

**Comment by fntlnz** [comment]
From the kernel verison and from el6 I guess that you're using centos 6.

CentOS 6 and kernel 2.6.x are not supported.

On the kernel side you need at least 3.10 and on the OS side CentOS 7.

**Comment by dakab1** [comment]
Same issue with kernel 3.10. Please help?
[root@dte1 nodes]# sudo yum-config-manager \
>     --add-repo \
>     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
https://download.docker.com/linux/centos/docker-ce.repo: [Errno 14] HTTPS Error 416 - Requested Range Not Satisfiable
Trying other mirror.
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] HTTPS Error 416 - Requested Range Not Satisfiable
[root@dte1 nodes]# uname -r
3.10.0-327.36.3.el7.x86_64

**Comment by fntlnz** [comment]
@dakab1 do you keep having this problem?

**Comment by jhabdas** [comment]
Reopening as it seems this issue is still present for some individuals. It's in mod hands now.

**Comment by dileep55** [comment]
This seems to be an issue that I am facing centos7 with kernel 3.10.0-327.36.1.el7.x86_64

**Comment by 20priya6** [comment]
Is there a solution yet for this problem?
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/dockr-ce.repo
Loaded plugins: fastestmirror, langpacks
adding repo from: https://download.docker.com/linux/centos/dockr-ce.repo
grabbing file https://download.docker.com/linux/centos/dockr-ce.repo to /etc/yum.repos.d/dockr-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/dockr-ce.repo to file /etc/yum.repos.d/dockr-ce.repo: [Errno 14] HTTPS Error 404 - Not Found

**Comment by thaJeztah** [comment]
You have a typo in your URL (dockr-ce instead of docker-ce)

**Comment by jhabdas** [comment]
can anyone confirm the typo mentioned?

**Comment by drlipingliu** [comment]
Same issue with Kernel 4.15. CentOS 6.9

sudo yum-config-manager \
>     --add-repo \
>     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
https://download.docker.com/linux/centos/docker-ce.repo: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 416 Requested Range Not Satisfiable"
Trying other mirror.
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 416 Requested Range Not Satisfiable"

uname -r
4.15.4-1.el6.elrepo.x86_64

**Comment by thaJeztah** [comment]
Even if CentOS 6 wouldn’t fail there; there are no packages for CentOS 6

**Comment by milkpirate** [comment]
Had similar problems. I this is related to having enabled the resume option in curl. When the whole file already exists, curl tries to request a range/portion/chunk that the server can not deliver:

```
*  SSL certificate verify ok.
} [5 bytes data]
> GET /somefile HTTP/1.1
> Host: somehost
> Range: bytes=243501230-                      <=== unsupported range
> User-Agent: curl/7.58.0
> Accept: */*
```
