### ISSUE TITLE
Windows Server Docker Daemon 17.05-dev fails to start with error - HNS failed with error : Object Exists

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#32750]
**Description**

After upgrading manually Docker Daemon from 1.13.1-cs1 to 17.05-dev it worked about 15-20 minutes and then stopped. And then we could not start Docker service again. Last error message I see is 

```
fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : {Object Exists} An attempt was made to create an object and the object name already existed. 
```

**Steps to reproduce the issue:**

We upgraded manually Docker Daemon from 1.13.1-cs1 to 17.05-dev using similar steps:

```
Stop-Service docker
Stop-Service vmcompute
Get-ContainerNetwork | Remove-ContainerNetwork -Force

cd C:\Users\Administrator\Downloads\
$dockerFile = "docker-17.05.0-dev.zip"
Invoke-WebRequest "https://master.dockerproject.org/windows/amd64/$dockerFile" -OutFile "$dockerFile" -UseBasicParsing
mv "C:\Program Files\docker\" "C:\Program Files\docker_orig\"; 
Expand-Archive -Path "$dockerFile" -DestinationPath $env:ProgramFiles

Start-Service docker; 
```

New version started fine at the begining. We could start by `docker start ...` one of the container. A start fas failed with error:
```
docker : Error response from daemon: container 85b7ba02eac3056a33efcad6aa4cd101984caf19e2464443f4c3ea4024369146 encountered an error during CreateContainer: failure in a Windows system call: Cannot create a file when that file already 
exists.
```
We did not pay attention to it and waited an owner of the container for correct redeploy (stop/rm/run). 
 
After some time (10-15 minute) Docker Daemon stoped for some unknown reason. I see following logs:
```
4/14/2017 10:18:25 AM debug: Stopping service: <nil>
4/14/2017 10:18:25 AM debug: Clean shutdown succeeded
4/14/2017 10:18:25 AM debug: start clean shutdown of all containers with a 15 seconds timeout...
```

Then we could not start Docker service again and only saw error message which I pasted in the description. 

**Additional information you deem important (e.g. issue happens only occasionally):**

We tried to reboot server - it did not help. We removed and instaled back the Windows feature 'containers'. It also did not help. Docker service still was not able to start.

I have this server now and can provide some extra information for you.

Following outputs were taken from test lab server from fresh upgraded Docker host
**Output of `docker version`:**

```
Client:
 Version:      17.05.0-dev
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   1a8206c
 Built:        Tue Apr 11 20:53:03 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-dev
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   1a8206c
 Built:        Tue Apr 11 20:53:03 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 28
 Running: 3
 Paused: 0
 Stopped: 25
Images: 644
Server Version: 17.05.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 32GiB
Name: EC2ACOR-U5O3C87
ID: VJVM:VK5U:VMUA:YB6Z:V325:MPQE:OTLH:CG46:OJA3:5UHQ:G6EE:UXQT
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 37
 System Time: 2017-04-20T20:02:08.6862089Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

On the original server we have following `docker version` output as we could note start Docker Daemon:
```
Client:
 Version:      17.05.0-dev
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   1a8206c
 Built:        Tue Apr 11 20:53:03 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.29/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated
 to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The server was an ASW m4.16xlarge instance.

Thanks!

**Comment by friism** [comment]
@georgyturevich is there a reason you run (what I assume is) a build from off the master branch? Could you try an RC: https://github.com/moby/moby/releases/tag/v17.05.0-ce-rc1

Also, have you updated to the latest Windows update set? It might be a networking problem, so you could test that by running with `--net none` and see if that still bricks the deamon.

See this: https://github.com/moby/moby/issues/32595#issuecomment-295310855

I'll try to reproduce too.

**Comment by friism** [comment]
@georgyturevich will Docker stop working even if you don't run any containers? If not, is there are simple set of reproducible steps I can run?

**Comment by georgyturevich** [comment]
@friism HI Michael,

Unfortunately, it is kind of random bug. I tested an upgrade to 17.05 twice (before fail and after fail to reproduce) and both were fine. Containers were started and working fine. But the testing was on the test machines. I think, we will to install 17.05 RC and monitor it again.

One thing I see on the crashed instance is when I run dockerd and getting this error
```
PS C:\Users\Administrator> dockerd -g E:\docker_storage_1_13\ --config-file=E:\docker_storage_1_13\config\daemon.json -D
...
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : {Object Exists} An attempt was made to create an object and the object name already existed.
```
I also see following Error message in Event-Log for 'Microsoft-Windows-Host-Network-Service' provider
```
HNS-Network-Create :- 
 Network id = '{be251d5c-964c-4331-a146-ef0d05b2ef60}'.
 Network type = 'NAT'.
  Result code = '0x800702BA'. 
```
but `Get-NetNat` and `Get-ContainerNetwork` return empty result. May be it is HNS in corrupted state?

**Comment by friism** [comment]
Hm, that suggests networking problem. If you manage to mess up another instance, try to see if this can fix the problem: https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking

cc @kallie-b @jmesser81

**Comment by biiiipy** [comment]
I have the same problem on physical Windows 10 Anniversary with v17.05.0-ce-rc1.

**Comment by nikoo56** [comment]
Please help. I am getting this error when I switch to Windows Container:

Docker daemon failed with message:
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to get endpoints from store: failed to decode endpoint IPv4 address () after json unmarshal: invalid CIDR address:

I have created transparent network as well and I have deleted them but I think I mess something with my networking. I tried all the above but I am still getting this error.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
