### ISSUE TITLE
Docker daemon restart failed with live-restore enabled

### ISSUE THREAD

**Issue by piontec** [moby/moby#32762]
**Description**

Docker daemon was restarted when `live-restore` was enabled. The restart failed, as `containerd` was constantly crashing and restarting. To resolve the situation, a full restart of all docker services and containers was required.

**Steps to reproduce the issue:**
1. Run docker with live-restore and few hundreds of containers
2. Restart docker service `systemctl restart docker`

**Describe the results you received:**
Dockerd couldn't start, most probably because containerd was crashing when trying to restore containers. Please see attached log file.
[docker.txt](https://github.com/moby/moby/files/946933/docker.txt)
This was going on for a long time (about 30min) producing tons of repeating log messages. After that time, we performed a host restart. After that, docker and all containers got back to normal.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 01:24:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 01:24:21 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 428
 Running: 354
 Paused: 0
 Stopped: 74
Images: 1685
Server Version: 17.03.0-ee-1
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4513
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 2904
 Goroutines: 2267
 System Time: 2017-04-21T11:41:10.803856118Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* ubuntu 16.04
* AWS x32.xlarge instance
* kernel: 4.4.0-72-generic #93-Ubuntu SMP

**Comment by piontec** [comment]
Similar to #31074

**Comment by cpuguy83** [comment]
Isn't this exactly caused by @31074? Shouldn't upgrading to 17.03.1 fix this?
Thanks!

**Comment by piontec** [comment]
we upgraded to 17.03.1, we'll let you know if we run again into this issue

**Comment by bklau** [comment]
@piontec Did you run into restarting daemon taking a long time after you upgrade to 17.03.1? thx

**Comment by piontec** [comment]
We're still having issues when restarting dockerd, but this time no crashes, so probably a different issue
