### ISSUE TITLE
NaiveDiffDriver does not use the block-level COW facility of storage backends efficiently

### ISSUE THREAD

**Issue by lxgr** [moby/moby#32769]
Based on the implementations of the existing block-level storage driver implementations I've checked (ZFS, btrfs and devmapper), it seems that they all use NaiveDiffDriver to implement ApplyDiff. Doesn't this effectively negate the benefits of having block-level data sharing between layers?

This could also explain [this observation](https://groups.google.com/forum/#!topic/docker-user/KCj0cokrOeM) (block-level sharing works for newly created layers using `docker commit`, but does not for images created using Dockerfiles.

Am I missing something, or could these storage backends benefit from a smarter implementation of ApplyDiff that attempts to write only the differing blocks and not the entire files?

**Comment by jjobi** [comment]
See https://github.com/moby/moby/issues/31953

**Comment by unclejack** [comment]
I'll close this in favor of #31953. There's no point in keeping both issues open.

Please continue to discuss on that issue.
