### ISSUE TITLE
using the -v option causes   oci runtime error: container_linux.go:247: starting container process caused "exec: \"-v\": executable file not found in $PATH".

### ISSUE THREAD

**Issue by naskokam** [moby/moby#32778]
On my MacOS Sierra, running Docker CE for Mac (Edge; but also tried Stable and same thing happens), when I do `docker run -ti centos`, everything works fine.  But when I add the -v option, like in `docker run -ti centos -v /Users/xxx/Downloads:/mnt`, I get the error message:
`docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"-v\": executable file not found in $PATH".`

**Comment by cpuguy83** [comment]
`-v` needs to be before `centos`.
Anything that is after the image name becomes part of the command that is run in the container.

**Comment by naskokam** [comment]
Oops
Thanks!
