### ISSUE TITLE
Container on host network

### ISSUE THREAD

**Issue by sburnwal** [moby/moby#32776]
I have a question: I have a linux host that has 2 NIC interfaces - eth0 on 192.168.10.x/24 and eth1 on 10.0.1.x/24 network. I started docker daemon without any --bip setting and it put the docker0 bridge on 172.17.x.x/16 network. Now when I run container with --net=host option, the container does not have any specific IP and as per the doc, it is on host network.

I want to know which network the container is in 192.168.10.x or 10.0.1.x or 172.17.x.x ?

**Comment by mavenugo** [comment]
@sburnwal if you use `--net=host`, then the container is placed in the host network namespace and hence the container has access to all the host network interfaces. so to your question, 

> I want to know which network the container is in 192.168.10.x or 10.0.1.x or 172.17.x.x ?

The answer is all of the above.

A simplistic way to think about from a networking standpoint would be : any container running with `--net=host` will act like any other regular linux process that runs natively on the host which has access to all the host interfaces.

**Comment by sburnwal** [comment]
OK, thanks for quick reply!
