### ISSUE TITLE
FR: docker volume cd <VOLUME>

### ISSUE THREAD

**Issue by Warchant** [moby/moby#32770]
## Feature request

I think it would be nice to have a cli for `cd` into docker volume mounpuint (from host), like:
```bash
$ pwd
/tmp
$ docker volume ls
local    vol1
$ docker volume inspect vol1
[
    {
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/vol1/_data",
        "Name": "vol1",
        "Options": {},
        "Scope": "local"
    }
]
$ docker volume cd vol1
$ pwd
/var/lib/docker/volumes/vol1/_data
```

For local volumes it is useful. I am just wondering, will it work for any other type of volumes?

**Comment by cpuguy83** [comment]
I don't think it will work at all unless you are actually on the host with the volumes.
Meanwhile you can `docker run -v <name>:/data -w /data busybox`.

**Comment by AkihiroSuda** [comment]
cd is shell builtin.
This proposal is technically impossible

**Comment by ripcurld0** [comment]
Can't we determine whether the client and the daemon are running on the same machine?
If so, we may do that in that case otherwise display a message saying this doesn't work in the current setup.

WDYT? 💭

**Comment by cpuguy83** [comment]
This is not something that makes sense for the Docker API.
If you are on the same system you can `cd` yourself by looking at the path returned from `inspect`.
