### ISSUE TITLE
Docker Linux + Java: Issues on Garbage Collecting cause Memory Leak and OOM

### ISSUE THREAD

**Issue by loretoparisi** [moby/moby#32788]
We are running a CPU intensive task in Java on Docker using [DeepLearning4J](https://github.com/deeplearning4j/deeplearning4j) on Docker.

The jar is started with with the env `ENV MALLOC_ARENA_MAX 4`.
We have tried different JVM setup like

```
-Xmx10000m -XX:+UseParallelGC -XX:-UseGCOverheadLimit
```

and

```
-XX:+UseG1GC -Xms1000m -Xmx10000 -XX:MaxMetaspaceSize=2000m
```

The task execution slows down and at some point a OOM is raised

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "VectorCalculationsThread 10"
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
```

During the execution a lot of swap memory usage has been reported

```
total        used        free      shared  buff/cache   available
Mem:          15984        8498        6017           2        1468        7095
Swap:         16323        2722       13601
```

Now, different issue related to JAVA and Docker have been reported alredy in **"growing reported docker container virtual memory size with java processes"** in https://github.com/moby/moby/issues/15020 and **"Memory leakage in Docker"** https://github.com/moby/moby/issues/31676, and again **"Unexpected OOM kills inside a container"** in https://github.com/moby/moby/issues/24887

There are several reports on Stackoverflow that describes OOM issues, memory leak at run time, etc, all related to Docker+Java, and not referring to a specific Java library.

The detailed description of this issue is referenced in the DL4J issue tracking here https://github.com/deeplearning4j/nd4j/issues/1785

**Host info**

```
Ubuntu version: Release: 16.04
Deeplearning4j version 0.8.0
```

**Docker info:**
```
docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 132
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 300
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.61GiB
Name: ubuntu-docker
ID: xxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxxx
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support
```

**Docker Version**
```
 docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by cpuguy83** [comment]
https://developers.redhat.com/blog/2017/03/14/java-inside-docker/ is a really good read for handling *some* issues with java using more memory than expected.

It looks like the linked issue found some problem with the logic in DeepLearning4J and is now closed.
Are we good to close this?

Thanks!

**Comment by loretoparisi** [comment]
@cpuguy83 Yes, we confirm that, despite of there is not a "clear overview" of the docker/java/linux state about OOM, etc, in this specific case we had a issue with the library, that was fixed by the author, so definitively closing this right now, thanks for the support!

**Comment by sauraahu** [comment]
What was solution, we have similar issue.?

**Comment by loretoparisi** [comment]
@sauraahu in my cause the issue was a memory leak caused by the library (DL4J), plus the fact that without a explicit memory management configuration to the JVM within docker, the JVM raised the OOM. 
The solution was thererfore:

- A fix of the memory leak in the java source code of the library;
-For the JVM8, the parameters setup was `Xmx10000m -XX:+UseParallelGC -XX:-UseGCOverheadLimit`
