### ISSUE TITLE
move docker stack command to the API or Client

### ISSUE THREAD

**Issue by marwan-at-work** [moby/moby#32781]
It would be very helpful if `docker stack COMMAND` did its logic not inside the CLI, but rather on the Client or on the API.

This would make integration with other tools much better, because you can just use the API and not have to switch between an SDK and shell commands.

Any good reason not to do that?

thanks : )

docker version:

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

docker info:
```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 122
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: QI6M:5L7Q:2EL3:OOB5:4ZHV:Z5OF:QDWN:KUD3:J2ND:C4WM:MBOS:N6IS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 78
 System Time: 2017-04-22T20:15:34.575559217Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by LavieX** [comment]
👍

**Comment by thaJeztah** [comment]
I think this is still on the roadmap (see https://github.com/moby/moby/issues/26876), but no ETA yet

ping @mgoelzer perhaps you know more?

**Comment by AkihiroSuda** [comment]
@thaJeztah @mgoelzer 

Can we add this issue to "Splitting Moby & Docker" github project?

I'm not sure about the current plan toward bundles, but it might contain "product" parts?

**Comment by dnephin** [comment]
Most of the logic is already in this package: https://github.com/docker/cli/tree/master/cli/compose

There's not much that is still in the `cli/command/stack` package.

**Comment by thaJeztah** [comment]
Let's close this one per https://github.com/moby/moby/issues/32781#issuecomment-312320293, and https://github.com/moby/moby/issues/26876 for tracking additional changes
