### ISSUE TITLE
 Error response from daemon: Get https://xxxxx.com/v1/users/ : x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rohitgkk** [moby/moby#32785]
**Description**

I have setup private docker secure registry V2 which is exposed outside using Nginx.
docker login is successful  to the registry, including push/pull of images from local docker host.
However, docker login from remote docker host is failing with the following error:

**Error response from daemon: Get https://xxxxx.com/v1/users/: x509: certificate signed by unknown authority**

** Operating System: Ubuntu 14.04.5 LTS**

_**Workaround I found**_ 

Modify /etc/default/docker file and add line DOCKER_OPTS="--insecure-registry xxxxx.com" then I am able to login to docker registry from remote docker host successfully.

**Steps to reproduce the issue:**
1. Setup docker registry V2 on docker host (lets name it as A) with https access by providing certificates. Then expose the registry to the outside world using Nginx.

2. Now try to login to docker registry using command docker login <REGISTRY_URL> from another docker host (Lets name it as B) then docker host B will throw error Error response from daemon: Get https://xxxxx.com/v1/users/: x509: certificate signed by unknown authority

**Actual Result:**

Error response from daemon: Get https://xxxxx.com/v1/users/: x509: certificate signed by unknown authority

**Expected Result:**

Login succeeded

**Question**

**There are several issues raised for this problem but none of them have been addressed properly. The workaround mentioned was temporary fix and the real issue still stands OPEN - My question is why we are forced to set --insecure-registry flag when it is a secure registry?**

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:08 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 31
 Running: 6
 Paused: 0
 Stopped: 25
Images: 38
Server Version: 17.04.0-ce
Storage Driver: btrfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-112-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.861GiB
Name: XYZ
ID: DXYB:BUYH:W2H2:H2CV:A6YR:LGSE:IWGY:NTZO:ZF2T:CAQU:EVIK:RAQG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional details :**
PLEASE DON'T CLOSE THIS ISSUE UNTIL THERE IS A PROPER FIX NOT WORKAROUND.

**Comment by fntlnz** [comment]
you are mentioning the fact that on the local machine you are able to login and do all the stuff but the same doesn't happen from a remote machine when the registry is exposed via nginx.

This is because you haven't setup nginx to provide a valid **and trusted** tls handshake for that domain.

So if you have a self signed certificate you have to add it to the trusted sources on the remote machine, otherwise docker will complain about the fact that the certificate cannot be trusted.

**Comment by rohitgkk** [comment]
@fntlnz Thanks a lot. This issue got resolved.

Resolution:
https://www.nginx.com/blog/nginx-https-101-ssl-basics-getting-started/

http://nginx.org/en/docs/http/configuring_https_servers.html
