### ISSUE TITLE
firewalld.service is dead, but the iptables rules of docker works

### ISSUE THREAD

**Issue by fanhaozzu** [moby/moby#32782]
os: centos7

systemctl status firewalld：
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

but i find the iptables works:
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 38090 -j DNAT --to-destination 172.17.0.2:8090
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 9002 -j DNAT --to-destination 172.17.0.2:9002
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 9001 -j DNAT --to-destination 172.17.0.2:9001
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 9003 -j DNAT --to-destination 172.17.0.2:9000
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8090 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9002 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9001 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9000 -j ACCEPT

That's why? who can explain this

**Comment by fanhaozzu** [comment]
。。。。。

**Comment by programmerq** [comment]
firewalld is a project that sets up iptables rules in the kernel. Docker also sets up iptables rules. There is no requirement to have firewalld, ufw, docker, nor any other application running for the kernel iptables subsystem to be loaded and active.

**Comment by fanhaozzu** [comment]
thank. you. very. much
