### ISSUE TITLE
Need the ability to dump a fully popluated daemon.json for a given platform

### ISSUE THREAD

**Issue by mdlinville** [moby/moby#32796]
**Description**

We have some example `daemon.json` output in https://docs.docker.com/engine/reference/commandline/dockerd/#windows-configuration-file and https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file and they are out of date. Rather than trying to keep them up to date by hand, it makes sense to provide a way to dump them, or to **allow the user to dump an example one themselves** so we could just document how to do that, instead of even having examples..

Original issue: https://github.com/docker/docker.github.io/issues/2768

cc/ @tiborvass for the suggestion of automation, and @briantd the OP

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
