### ISSUE TITLE
Windows: docker run -it is broken on master

### ISSUE THREAD

**Issue by jhowardmsft** [moby/moby#32799]
Looks like it was regressed by https://github.com/moby/moby/pull/32248, b2551c619d30f163c3ab8c9ee53cdb09bfbeaa55

@icapurro FYI. 

You now get "The Parameter is incorrect" when trying `docker run -it --rm microsoft/nanoserver cmd`

**Comment by dnephin** [comment]
Looks like the problem is that `SetRawTerminal()` needs to be different for OutputStream and not on CommonStream

**Comment by icapurro** [comment]
I just see this. Thanks @vdemeester for fixing it :rocket:
