### ISSUE TITLE
Quick adding of contains with networks leads to unresponsive application 

### ISSUE THREAD

**Issue by aangelov-vmware** [moby/moby#32790]
Output of docker version:

Client:
Version: 17.04.0-ce
API version: 1.28
Go version: go1.7.3
Git commit: 4845c56
Built: Wed Apr 12 22:57:26 2017
OS/Arch: linux/amd64

Server:
Version: 17.04.0-ce
API version: 1.28 (minimum version 1.12)
Go version: go1.7.3
Git commit: 4845c56
Built: Wed Apr 12 22:57:26 2017
OS/Arch: linux/amd64
Experimental: false

Output of docker info:

Containers: 1
Running: 1
Paused: 0
Stopped: 0
Images: 9
Server Version: 17.04.0-ce
Storage Driver: overlay
Backing Filesystem: extfs
Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
seccomp
Profile: default
selinux
Kernel Version: 4.10.9-coreos
Operating System: Container Linux by CoreOS 1381.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.801GiB
Name: localhost
ID: CHN4:C27I:SBMP:BLYX:6HA3:GGJE:CR2U:LNTD:3SW5:Z6PZ:FEZ2:TTYH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false

Steps to reproduce the issue:
1.Create a network.
2.Create a container using this network(kitematic/hello-world-nginx:latest).
3.Repeat quickly steps 1 and 2 several times.
4.Call the applications in those containers. Some of the calls never complete.

Note. If we add delay between the creation of network/container couples, the problem do not appear.

Here is a script which reproduce the issue.

#!/bin/bash

echo ------------------------------------------------------------------------
echo  -------------------------- cleaning ---------------------------------
echo ------------------------------------------------------------------------
docker rm -fv $(docker ps -a -q) ; docker network rm $(docker network list -q)
echo ------------------------------------------------------------------------
echo  -------------------------- provisioning ---------------------------------
echo ------------------------------------------------------------------------

docker network create network_name_1
docker run -P -d --net network_name_1  --name container_name_1 kitematic/hello-world-nginx:latest
vote_host_port_1=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_1)

#sleep 1

docker network create network_name_2
docker run -P -d --net network_name_2  --name container_name_2 kitematic/hello-world-nginx:latest
vote_host_port_2=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_2)

#sleep 1

docker network create network_name_3
docker run -P -d --net network_name_3  --name container_name_3 kitematic/hello-world-nginx:latest
vote_host_port_3=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_3)

#sleep 1

docker network create network_name_4
docker run -P -d --net network_name_4  --name container_name_4 kitematic/hello-world-nginx:latest
vote_host_port_4=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_4)

#sleep 1

docker network create network_name_5
docker run -P -d --net network_name_5  --name container_name_5 kitematic/hello-world-nginx:latest
vote_host_port_5=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_5)

#sleep 1

docker network create network_name_6
docker run -P -d --net network_name_6  --name container_name_6 kitematic/hello-world-nginx:latest
vote_host_port_6=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_6)

#sleep 1

docker network create network_name_7
docker run -P -d --net network_name_7  --name container_name_7 kitematic/hello-world-nginx:latest
vote_host_port_7=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' container_name_7)

echo Waiting 20 seconds the application to start.
sleep 20
echo ------------------------------------------------------------------------
echo  -------------------------- ping  ---------------------------------
echo ------------------------------------------------------------------------
echo ping http://localhost:$vote_host_port_1
curl -sL -o /dev/null http://localhost:$vote_host_port_1
echo
echo ping http://localhost:$vote_host_port_2
curl -sL -o /dev/null http://localhost:$vote_host_port_2
echo
echo ping http://localhost:$vote_host_port_3
curl -sL -o /dev/null http://localhost:$vote_host_port_3
echo
echo ping http://localhost:$vote_host_port_4
curl -sL -o /dev/null http://localhost:$vote_host_port_4
echo
echo ping http://localhost:$vote_host_port_5
curl -sL -o /dev/null http://localhost:$vote_host_port_5
echo
echo ping http://localhost:$vote_host_port_6
curl -sL -o /dev/null http://localhost:$vote_host_port_6
echo
echo ping http://localhost:$vote_host_port_7
curl -sL -o /dev/null http://localhost:$vote_host_port_7
echo

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
