### ISSUE TITLE
Bind mount of 'non-existent' host directories for v2 plugins fails.

### ISSUE THREAD

**Issue by adityadani** [moby/moby#32795]
**Description**
I am working on a volume plugin (v2) for Docker.

Traditionally our plugin runs as a docker container, and I am porting it to also work as a plugin. We do a couple of bind mounts of the host directories into the container. However in case of plugins, if the host directory does not exist the plugin fails to start. 

In case of a container`docker run` handles this and creates those directories and the bind mount succeeds. 

By using non-existent directories, we are able to export config data from our plugin (/container) onto the host.

**Describe the results you received:**

Following is the error I get when I run `docker plugin enable`

```
Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/etc/pwx\\\" to rootfs \\\"/var/lib/docker/plugins/764d5fe6585f439abb157ebeb88050d07e3785c863a005330607aeea12861324/rootfs\\\" at \\\"/etc/pwx\\\" caused \\\"stat /etc/pwx: no such file or directory\\\"\""
```

Here `/etc/pwx` is the host directory which does not exist.

**Describe the results you expected:**

Currently in order for the plugin to work, we have to pre-create empty directories on the host and then do a `docker plugin install` or `docker plugin enable`. 

`docker plugin enable` should succeed without pre-creating host directories which are bind mounted into the plugin.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 18
 Running: 17
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:3-8652283-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.218 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.2 GB
 Metadata Space Used: 5.046 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.785 GiB
Name: k8s-master
ID: LAFP:FY7B:HNPR:BMXI:3HK7:G3JT:TRU2:2AOY:LWMN:RUKT:CYI3:RSZ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: adityadani
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Machine, Linux  3.10.0-327.22.2.el7.x86_64, CentOS

**Comment by cpuguy83** [comment]
-1 on this.
Nothing should be auto-creating host paths (especially `docker run`).
In this case we should understand the reasoning behind bind-mounting `/etc/pwx` into the plugin.

The plugin model already supports configuration via args/env vars. Why the extra directory?

**Comment by cpuguy83** [comment]
ping @anusha-ragunathan

**Comment by anusha-ragunathan** [comment]
Yes, plugins will not create host directories.

Most likely they need the extra dir `/etc/pwx` to be bind mounted, because that's how the legacy plugin-as-a-container worked. If that's the case, using pluginv2 you can use plugin `config` https://github.com/moby/moby/blob/488ad693c0bc6ca6d2b0c0c9b467255fcccc023f/docs/reference/commandline/plugin_set.md.

**Comment by anusha-ragunathan** [comment]
Not an issue, working as designed
