### ISSUE TITLE
Container restart will take 20s when rootfs device is unmounted

### ISSUE THREAD

**Issue by maxim28** [moby/moby#32835]
**Description**
- we found a issue that container restart will take 20s to finish when this container's rootfs device(graph driver using device mapper) is not mounted.
- it can be reproduced every time i restart the container.

**Steps to reproduce the issue:**
1. if one container's rootfs device is not mounted like below ( i don't know how it happened, maybe something wrong happened when docker try to unmount the device)
    - correct output of lsblk for docker using device mapper will be:
`├─docker-8:1-6558376-f9265bc0e0086cb83f17b3cf6aa358e6cabb3df24136b6f12613dfb74d5793dd (dm-25) 252:25   0    10G  0 dm   /var/lib/docker/devicemapper/mnt/f9265bc0e0086cb`
    - here is what i got:
`├─docker-8:1-6558376-f9265bc0e0086cb83f17b3cf6aa358e6cabb3df24136b6f12613dfb74d5793dd (dm-25) 252:25   0    10G  0 dm`
2. when i try to restart this container with -t 0, it will take 20s to finish
3. when i try to restart it again, it will also take 20s to finish

**Additional information you deem important (e.g. issue happens only occasionally):**
1. when i investigate the code of container restart, i found a strange logic:
```
func (daemon *Daemon) containerRestart(container *container.Container, seconds int) error {
	// Avoid unnecessarily unmounting and then directly mounting
	// the container when the container stops and then starts
	// again
	if err := daemon.Mount(container); err == nil {
		defer daemon.Unmount(container)
	}

	if container.IsRunning() {
		// set AutoRemove flag to false before stop so the container won't be
		// removed during restart process
		autoRemove := container.HostConfig.AutoRemove

		container.HostConfig.AutoRemove = false
		err := daemon.containerStop(container, seconds)
		// restore AutoRemove irrespective of whether the stop worked or not
		container.HostConfig.AutoRemove = autoRemove
		// containerStop will write HostConfig to disk, we shall restore AutoRemove
		// in disk too
		if toDiskErr := container.ToDiskLocking(); toDiskErr != nil {
			logrus.Errorf("Write container to disk error: %v", toDiskErr)
		}

		if err != nil {
			return err
		}
	}

	if err := daemon.containerStart(container, "", "", true); err != nil {
		return err
	}

	daemon.LogContainerEvent(container, "restart")
	return nil
}
```
2. so if the device is not mounted, docker will try to mount the device at first and stop and start the container, and unmount the device finally? and here is the logic in unmount, which will unmount the device and deactivate the device:
```
func (devices *DeviceSet) UnmountDevice(hash, mountPath string) error {
	logrus.Debugf("devmapper: UnmountDevice START(hash=%s)", hash)
	defer logrus.Debugf("devmapper: UnmountDevice END(hash=%s)", hash)

	info, err := devices.lookupDeviceWithLock(hash)
	if err != nil {
		return err
	}

	info.lock.Lock()
	defer info.lock.Unlock()

	devices.Lock()
	defer devices.Unlock()

	logrus.Debugf("devmapper: Unmount(%s)", mountPath)
	if err := syscall.Unmount(mountPath, syscall.MNT_DETACH); err != nil {
		return err
	}
	logrus.Debug("devmapper: Unmount done")

	if err := devices.deactivateDevice(info); err != nil {
		return err
	}

	return nil
}
```
3. and here is the logic of deactivateDevice:
```
unc (devices *DeviceSet) deactivateDevice(info *devInfo) error {
	logrus.Debugf("devmapper: deactivateDevice START(%s)", info.Hash)
	defer logrus.Debugf("devmapper: deactivateDevice END(%s)", info.Hash)

	devinfo, err := devicemapper.GetInfo(info.Name())
	if err != nil {
		return err
	}

	if devinfo.Exists == 0 {
		return nil
	}

	if devices.deferredRemove {
		if err := devicemapper.RemoveDeviceDeferred(info.Name()); err != nil {
			return err
		}
	} else {
		if err := devices.removeDevice(info.Name()); err != nil {
			return err
		}
	}
	return nil
}
```
4. the deactivateDevice logic will remove the device, but according to the previous logic, the device is still be used by container process and cannot be removed,  which will wait 20s and return. after that, the device still exists and unmounted, so the next restart will take 20s again:
```
func (devices *DeviceSet) removeDevice(devname string) error {
	var err error

	logrus.Debugf("devmapper: removeDevice START(%s)", devname)
	defer logrus.Debugf("devmapper: removeDevice END(%s)", devname)

	for i := 0; i < 200; i++ {
		err = devicemapper.RemoveDevice(devname)
		if err == nil {
			break
		}
		if err != devicemapper.ErrBusy {
			return err
		}

		// If we see EBUSY it may be a transient error,
		// sleep a bit a retry a few times.
		devices.Unlock()
		time.Sleep(100 * time.Millisecond)
		devices.Lock()
	}

	return err
}
```

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   663a615
 Built:        Mon Feb 27 20:21:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   663a615
 Built:        Tue Feb 28 15:59:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 21
 Running: 18
 Paused: 0
 Stopped: 3
Images: 45
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 26.55 GB
 Data Space Total: 456.1 GB
 Data Space Available: 429.5 GB
 Metadata Space Used: 9.327 MB
 Metadata Space Total: 4.798 GB
 Metadata Space Available: 4.789 GB
 Thin Pool Minimum Free Space: 45.61 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 3fed9627f123f31686a1a321521054a168a19d92
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.6.6-040606-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.8 GiB
Name: xq18
ID: XRQ2:Z5ZR:R22M:JZA3:ITVP:NCDI:POU3:VU7N:QNTN:JKLW:XA56:Y2IX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 117
 Goroutines: 100
 System Time: 2017-04-26T11:40:38.396548565+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 registry.qcos.qbox.me
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhvgoyal** [comment]
I think following logic is horribly broken.

	// Avoid unnecessarily unmounting and then directly mounting
	// the container when the container stops and then starts
	// again
	if err := daemon.Mount(container); err == nil {
		defer daemon.Unmount(container)
	}

First of all, if container is not running, doing this will just have unnecessary mounting done. I don't know who is going to unmount that.

Secondly, I don't understand that why you are running into 20 second delay. If daemon.Mount() has already been done, that will bump up the reference count of mount and deactivate device will not be called at all when we are trying to stop container.

// Put unmounts a device and removes it.
func (d *Driver) Put(id string) error {
        mp := path.Join(d.home, "mnt", id)
        if count := d.ctr.Decrement(mp); count > 0 {
                return nil
        }
        err := d.DeviceSet.UnmountDevice(id, mp)
        if err != nil {
                logrus.Errorf("devmapper: Error unmounting device %s: %s", id, err)
        }
        return err
}

I would say try to narrow down the problem a little bit more.

**Comment by maxim28** [comment]
Hi, rhvgoyal, according to my understanding of the code, the 20 second delay may be caused by following assumptions:
1. if the device is not mounted, so the daemon.Mount() will succeed with no error and increment the ref count by 1 ( now ref count is 1)
2. since mount's error is nil, the defer daemon.Unmount will be called. Before daemon.Unmount is called, stop and start container will be called in advance. i don't see any deactivate device logic in containerStop function
3. finally, daemon.Unmount will be called with the driver Put function, which will decrement the ref count by 1 ( now ref count is 0), so it will not return nil but continue callingDeviceSet UnmountDevice, so the 20 second delay will happen

**Comment by thaJeztah** [comment]
devicemapper was deprecated and removed. 
Let me close this ticket for now, as it looks like it went stale.
