### ISSUE TITLE
Docker not working on system restart (using custom directory using graph option)

### ISSUE THREAD

**Issue by abhaymittal** [moby/moby#32832]
**Description**

**Steps to reproduce the issue:**
1. Install docker
2. Edit `/etc/docker/daemon.json` and change it to:
```
{
    "graph":"/mnt/lindata/docker/"
}
```
(`/mnt/lindata/docker/` is the custom directory on an ext4 partition3)

3. download and try running an image `sudo docker run -it ubuntu bash`. It should be successful. Also try `sudo docker images` to make sure the image is listed

4. Restart the system

5. Try running `sudo docker images`. There will be no images listed.

6. Try running the same image you downloaded previously. `sudo docker run -it ubuntu bash`. It should give an output like:
```
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
Digest: sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028
Status: Downloaded newer image for ubuntu:latest
docker: Error response from daemon: layer does not exist.
```

7. Stop docker using `systemctl stop docker`

8. Start docker again using `systemctl start docker`

**Describe the results you received:**

Docker fails and `systemctl status docker` produces the log:

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-04-25 20:51:12 EDT; 4s ago
     Docs: https://docs.docker.com
  Process: 3935 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 3935 (code=exited, status=1/FAILURE)

Apr 25 20:51:11 abmittal-linux systemd[1]: Starting Docker Application Container Engine...
Apr 25 20:51:11 abmittal-linux dockerd[3935]: time="2017-04-25T20:51:11.868005519-04:00" level=info msg="libcontainerd: new containerd process, pid: 3952"
Apr 25 20:51:12 abmittal-linux dockerd[3935]: Error starting daemon: error initializing graphdriver: invalid argument
Apr 25 20:51:12 abmittal-linux systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 20:51:12 abmittal-linux systemd[1]: Failed to start Docker Application Container Engine.
Apr 25 20:51:12 abmittal-linux systemd[1]: docker.service: Unit entered failed state.
Apr 25 20:51:12 abmittal-linux systemd[1]: docker.service: Failed with result 'exit-code'.

```

**Describe the results you expected:**
Docker should be able to run.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have tried both aufs and overlay drivers. 
Also, docker works once if i change the directory in config but then on restart again has the same problem.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-49-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.71 GiB
Name: abmittal-linux
ID: ZDDI:G63A:WP2V:XJC4:53MA:EVJQ:7P7Q:XJDI:UGVR:I6AI:EZLY:JX4U
Docker Root Dir: /mnt/lindata/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 LTS (physical machine)

**Comment by thaJeztah** [comment]
Could it be the custom partition is not  mounted before the docker service is started?

**Comment by thaJeztah** [comment]
I don't see this being a bug in docker, most likely an issue in the setup (as mentioned; check if the partition/filesystem is mounted before the daemon starts). I'll go ahead and close this issue, but feel free to continue the conversation

Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by abhaymittal** [comment]
Yes the partition is mounted. I have tried re installing several times and also tried creating configuring with systemd (mentioned [here](https://docs.docker.com/engine/admin/systemd/) and the method posted on the [forums](https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169). All of these methods lead to the same issue and I am not able to debug what is wrong.

**Comment by abhaymittal** [comment]
Thank you for indicating that mounting may be the issue. Though I had auto mounts turned on, I did not know that they are also run as a service and the docker daemon could have ran before that. I fixed the issue by having mount first.

**Comment by thaJeztah** [comment]
Thanks for reporting back; good to hear the issue was resolved 👍
