### ISSUE TITLE
Excute ' docker rmi ' spend a lot of time

### ISSUE THREAD

**Issue by houkk** [moby/moby#32833]
Excute ' docker rmi ' spend a lot of time. (spend 11 min, 9 images about 2.5 G)

**Steps to reproduce the issue:**

0. 9 images about 2.5 G
1. redhat 7.0,  install docker 1.8.2 
2. 'docker rmi' spend a lot of time
3. upgrade docker to 1.13.1
4. still spend a lot of time

**Describe the results you received:**
Excute ' docker rmi ' spend a lot of time. 

**Describe the results you expected:**

spend normal time when excuting 'docker rmi'

**Additional information you deem important (e.g. issue happens only occasionally):**

Redhat: 7.0
kernel: 3.10.0-123.el7.x86_64

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 138
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-34290153-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.9 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.166 GB
 Metadata Space Used: 8.077 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.0 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.704 GiB
Name: localhost.localdomain
ID: 26DT:AB62:HIWU:DCAJ:Y6GJ:3QZN:ZFND:LJZY:75PM:IWBZ:OOZM:4NWU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox(4.3.36) and physical machine

**Comment by thaJeztah** [comment]
Running devicemapper with loopback devices is known to be very slow, and one of the reasons the warning is printed;

```
WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

11 minutes is a long time, so there may be other issues at hand, but I'd really recommend read the documentation on devicemapper performance https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#device-mapper-and-docker-performance, and configure devicemapper to use direct-lvm (https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-docker-with-devicemapper), or try using a different storage driver, such as overlay2/overlay, which should be supported by the Red Hat kernel

**Comment by thaJeztah** [comment]
Also note that 1.13.1 is not the latest release of docker; consider updating to docker 17.03.1 (stable channel), which uses the new version scheme, and is what 1.13.2 would have been

**Comment by thaJeztah** [comment]
devicemapper was deprecated and removed. 
Let me close this ticket for now, as it looks like it went stale.
