### ISSUE TITLE
docker and networkmanager

### ISSUE THREAD

**Issue by ghost** [moby/moby#32836]
Hello, this is in reference to docker's interaction with NetworkManager.

NetworkManager replaces /etc/resolv.conf with a symbolic link to /var/run/NetworkManager/resolv.conf

Because of this, if the computer is started with no internet connection, the docker daemon will run but images cannot be launched since the daemon cannot find /etc/resolv.conf

On the one hand, this could be considered a NetworkManager issue. On the other, it is pretty frustrating to go somewhere with no internet connection, turn on your computer and discover docker doesn't run.

My fix on the NetworkManager side is to add the following to /etc/NetworkManager/NetworkManager.conf

`rc-manager=file`

delete the symbolic link /etc/resolv.conf and reboot with a network connection running. More options here:

https://developer.gnome.org/NetworkManager/unstable/NetworkManager.conf.html

**Comment by sdfoley** [comment]
Tried using the --dns switch with docker run and still get the following error:

`docker: Error response from daemon: open /etc/resolv.conf: no such file or directory.`

**Comment by thaJeztah** [comment]
Yes, NetworkManager is known to cause issues; we cannot make these changes when installing docker though, but perhaps this comment helps others. Overall it's recommended to disable NetworkManager if possible.
