### ISSUE TITLE
Unable to use PF_RING inside docker containers running with cap_add: NET_ADMIN

### ISSUE THREAD

**Issue by shreyans4** [moby/moby#32847]
**Description**
We use PF_RING inside docker containers to implement high speed packet capture from the host's
ethernet interfaces. The host has the PF_RING dynamic kernel modules loaded but the containers no longer can attach to those interfaces in docker-engine 17.04.0. This used to work until 1.13.1 release of docker-engine with NET_ADMIN cap_add permissions. Things still work in 17.04.0 if we set the privileged: true but that is not something we can enable in our production environments.

I am attaching the docker-compose yml files and the Dockerfile to build and start the containers.

[Dockerfile.centos.txt](https://github.com/moby/moby/files/959210/Dockerfile.centos.txt)
[Dockerfile.ubuntu.txt](https://github.com/moby/moby/files/959212/Dockerfile.ubuntu.txt)
[pfsensor-centos.yml.txt](https://github.com/moby/moby/files/959209/pfsensor-centos.yml.txt)
[pfsensor-ubuntu.yml.txt](https://github.com/moby/moby/files/959211/pfsensor-ubuntu.yml.txt)

Also, adding the steps to setup the host environment. These are pretty standard pf_ring setup steps listed at http://packages.ntop.org/centos-stable/.

We use a standard tool called pfcount to demonstrate the problem. The pfcount tool uses PF_RING to attach to the eth0 interface and prints out the summary stats from that interface. In docker version 1.13.1 and earlier, things seem to work as expected but it stopped working in the newer versions of docker.

**Steps to reproduce the issue:**
Here are the instructions to setup the host and build the docker imags

0. Add epel repository to support DKMS
```
      rpm -Uvh http://dl.fedoraproject.org/pub/epel/7Server/x86_64/e/epel-release-7-9.noarch.rpm
```
1. Install PF_RING on the Redhat 7.3 docker host using the steps outlined in http://packages.ntop.org/centos-stable/
```
      yum -y update
      yum -y install wget kernel-devel-`uname -r`
      cd /etc/yum.repos.d/
      wget http://packages.ntop.org/centos-stable/ntop.repo -O ntop.repo
      wget http://packages.ntop.org/centos-stable/epel-7.repo -O epel.repo
      yum erase zeromq3
      yum clean all
      yum -y update
      yum -y install pfring n2disk nprobe ntopng ntopng-data cent
```
2. Start PF_RING
```
     /etc/init.d/pf_ring start
```
3. Install docker
```
      curl -sSL https://get.docker.com | sh
      systemctl start docker.service
      systemctl enable docker.service
```
4. Install docker-compose
```
      curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
```
5. Build pfsensor using the attached pfsensor.yml
```
      docker-compose -f pfsensor-ubuntu.yml build
```
6. Start the docker container
```
      docker-compose -f pfsensor-ubuntu.yml up -d
```
**Describe the results you received:**

Start the docker container
```
[ec2-user@ip-10-3-21-106 ~]$ docker-compose -f pfsensor-ubuntu.yml up -d
Creating ec2user_pfsensor_1
```

The docker container immediately quits after starting
```
[ec2-user@ip-10-3-21-106 ~]$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS PORTS               NAMES
3c644d6c886c        pfsensor.ubuntu     "/bin/sh -c /usr/b..."   5 seconds ago       Exited (255) 4 seconds ago                       ec2user_pfsensor_1


[ec2-user@ip-10-3-21-106 ~]$ docker logs ec2user_pfsensor_1
pfring_open error [No such device] (pf_ring not loaded or interface eth0 is down ?)
```

The lsmod output for pf_ring indicates there are 0 processes attached to that module.
```
[ec2-user@ip-10-3-21-106 ~]$ lsmod | grep pf
pf_ring              1234009  0
```

**Describe the results you expected:**
Start the docker container
```
[ec2-user@ip-10-3-21-106 ~]$ docker-compose -f pfsensor-ubuntu.yml up -d
Creating ec2user_pfsensor_1
```

The container should continue to run
```
[ec2-user@ip-10-3-22-135 pfring]$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS PORTS               NAMES
f86175c464a2        pfsensor.ubuntu     "/bin/sh -c /usr/b..."   About a minute ago   Up About a minute                       pfring_pfsensor_1


[ec2-user@ip-10-3-22-135 pfring]$ docker logs pfring_pfsensor_1
error reading link speed on eth0
Dumping statistics on /proc/net/pf_ring/stats/27810-eth0.1
=========================
Absolute Stats: [4 pkts total][0 pkts dropped][0.0% dropped]
[4 pkts rcvd][512 bytes rcvd]
=========================

=========================
Absolute Stats: [32 pkts total][0 pkts dropped][0.0% dropped]
[32 pkts rcvd][4'040 bytes rcvd][31.99 pkt/sec][0.03 Mbit/sec]
=========================
Actual Stats: [28 pkts rcvd][1'000.19 ms][27.99 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [32 pkts total][0 pkts dropped][0.0% dropped]
[32 pkts rcvd][4'040 bytes rcvd][16.00 pkt/sec][0.02 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.18 ms][0.00 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [44 pkts total][0 pkts dropped][0.0% dropped]
[44 pkts rcvd][5'416 bytes rcvd][14.66 pkt/sec][0.01 Mbit/sec]
=========================
Actual Stats: [12 pkts rcvd][1'000.16 ms][12.00 pps][0.00 Gbps]
```

The lsmod output for pf_ring indicates there are 2 processes attached to that module.
```
[ec2-user@ip-10-3-21-106 ~]$ lsmod | grep pf
pf_ring              1234009  2
```

Version of docker where things worked as expected
```
[ec2-user@ip-10-3-21-106 ~]$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue started happening starting docker 17.x onwards. Things work as expected in 1.13.1 and earlier versions of docker. Also, when we use privileged mode instead of cap_add: NET_ADMIN, things seem to work fine in 17.04.0 as well.

We tried with ubuntu:16.04 and Centos:latest as the base image inside the container (Dockerfiles attached) and they had the exact same behaviors. 

**Output of `docker version`:**

```
[ec2-user@ip-10-3-21-106 ~]$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[ec2-user@ip-10-3-21-106 ~]$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.451GiB
Name: ip-10-3-21-106.us-west-2.compute.internal
ID: 5QRR:W3VX:KYJ5:LDMO:26EH:BBPP:YXQD:33HF:LXUC:Z3UX:LGXJ:NQB7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We used AWS instance with the following specs:
  - Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type - ami-6f68cf0f
  - t2.medium
  - 10GB SSD

**Comment by shreyans4** [comment]
This has been tagged as 1.13, but the issue is really in 17.0.

**Comment by nakedible-p** [comment]
@shreyans4 test adding `--security-opt seccomp:unconfined` to running the container. If it works after that, then your problem is the same as mine.

**Comment by shreyans4** [comment]
Thanks @nakedible-p. It did fix the problem for me too. Looks like we're running into the same issue.

**Comment by justincormack** [comment]
Can you test in 17.06 release candidate, I think this may have been changed
already.

**Comment by shreyans4** [comment]
It tried the 17.06 released yesterday and it does fix the problem.

**Comment by shreyans4** [comment]
I tried 17.06 released yesterday and it does fix the problem.

**Comment by thaJeztah** [comment]
Thanks! Looks like this is resolved, so I'll close the issue
