### ISSUE TITLE
Using git clone in a Dockerfile Produces empty working directory

### ISSUE THREAD

**Issue by stalinkay** [moby/moby#32855]
**Description**

I have created a Dockerfile that uses `git clone …`. I build this Dockerfile using docker-compose everything seems to work till I invoke command from the docker-compose.yml file. What am I doing wrong? I'm trying to do this on our staging server using docker-machine. Including ls -a in the command shows the working directory is empty.

**Dockerfile**

    FROM joomla
    RUN apt-get update && apt-get -y upgrade && apt-get install -y git-all && apt-get clean
    ENV workdir /var/www/html
    WORKDIR $workdir
    ADD uploads.ini /usr/local/etc/php/conf.d/uploads.ini
    ADD id_rsa /root/.ssh/id_rsa
    RUN chmod 400 /root/.ssh/id_rsa && ssh-keyscan -T 60 github.com >> /root/.ssh/known_hosts && git clone git@github.com:user/repo.git .

**docker-compose.yml**

    version: "2"
    services:
      joomla:
        build:
          context: .
        links:
          - joomladb:mysql
        ports:
          - 80:80
        command: bash -c "pwd && ls -a && cat configuration-docker.sh && chmod +x ./configuration-docker.sh && ./configuration-docker.sh && /entrypoint.sh apache2-foreground"
        environment:
          MYSQL_PORT_3306_TCP: 3306
          JOOMLA_DB_HOST: joomladb
          JOOMLA_DB_PASSWORD: "root"
          JOOMLA_DB_USER: "root"
          JOOMLA_DB_NAME: "database"
          COMPOSE_HTTP_TIMEOUT: 3600 # set timeout to 1 hour to prevent premature ssh timeout
        restart: always
        depends_on:
          - joomladb
    
      joomladb:
        image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "database"

**Steps to reproduce the issue:**
1. Create a Dockerfile and docker-compose.yml as created above
2. `eval $(docker-machine env remote)`
3. `docker-compose build --no-cache && docker-compose up`

**Describe the results you received:**
Everything would seem to have worked but the Entrypoint command fails. `ls -a` lists . and .. and that's it. I suspect that this might be caused by the size of the git project 1.2 Gb.

**Describe the results you expected:**
I expected the working directory to contain my cloned project. If I git clone in the command in the docker-compose.yml file everything works.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
lient:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
ontainers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 71
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 88
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.765 GiB
Name: *************.ca
ID: DC4K:UUQW:RCTH:S7HA:CZGO:OXD7:R6QT:XTHN:LL7W:XUZR:3AAC:LP4G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: *********
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
It's because `/var/www/html` is marked as a volume in the parent image (`joomla`).
This means the directory is not persisted with the image.

I do not see why this would need to be a volume unless data is expected to change.
I'd recommend opening an issue with https://github.com/joomla/docker-joomla.
