### ISSUE TITLE
Create a place for async community communication

### ISSUE THREAD

**Issue by vieux** [moby/moby#32861]
Currently we use #moby-project on  dockercommunity.slack.com for coordination, even though it’s good for synchronous communication, it’s not the best for async communication. 

Redis uses a subreddit, might be a good idea.

**Comment by AkihiroSuda** [comment]
why not just use github?

**Comment by thaJeztah** [comment]
The problem with GitHub was that it doesn't work very well with longer discussions, at which point it quickly becomes a "mess".

I'm not entirely sure about reddit; t.b.h., wasn't really impressed, and don't know if it offers much more than GitHub (other than up/downvoting topics).

Would discourse work? I think we use it for forums.docker.com, but we could set up a similar one for mobyproject?

**Comment by thaJeztah** [comment]
Also; wondering if mobyproject should have its own Slack, as the target audience is different than Docker _users_ / Docker community

**Comment by alexellis** [comment]
Ideally not another slack community. People can opt into / out of channels right?

**Comment by AkihiroSuda** [comment]
Separate slack would mitigate 10k message limitation :+1:

**Comment by krasi-georgiev** [comment]
what do you think about www.matrix.org - open source decentralised messaging server.
might allow some customisation for a  workflow that will work for everyone and help with the separation.
www.riot.im - build on top of matrix

**Comment by cpuguy83** [comment]
@krasi-georgiev I could be mistaken, but that seems more focused on synchronous communication.

**Comment by alexellis** [comment]
We have Community Slack, Dockercon Slack and I guess Docker Inc have Docker Slack too. Is adding another community the right answer? If so, what about a paid one for the limited amount of people who would join to discuss hacking on Moby?

**Comment by krasi-georgiev** [comment]
@cpuguy83 yes I misread the issue title.

Still looks a very nice open source platform  with voice and video which  is often very useful. 

I haven't used it but seems very similar to slack and promises some nice integration with irc and other messaging platforms.

I think it also supports Permanent links to messages.

**Comment by AkihiroSuda** [comment]
I prefer text communication for recording purpose

**Comment by krasi-georgiev** [comment]
I think for code and proposal discussions missing the @user,#issue is a big drawback so whatever it is should be well integrated with github issues and pr

**Comment by thaJeztah** [comment]
I created a playground for groups.io; https://moby-test.groups.io/g/main

Current things I noticed;

- Navigation isn't very polished
- Looks like it's not possible to `@` mention people
- Haven't found a "notifications" / "unread" messages overview yet (possibly it's there)
- Moderation is enforced for first-time posters, which is "ok" but may be an issue if there's many people subscribing
- Haven't found a way to import/export data yet

There's some nice things to look into;

- subgroups is a good thing (allows creating separate groups per component); e.g. created a "builder" subgroup https://moby-test.groups.io/g/builder
- there's an option for _polls_, which may be nice to vote on proposals (e.g. https://moby-test.groups.io/g/builder/topic/use_or_don_t_use/4976582?p=,,,20,0,0,0&ct=1::Relevance,,%23poll,20,2,0,4976582,ct=1)
- "hashtags" allow for adding some structure/organization of topics

Some other features that may come in handy (although we may have to decide if we _want_ to use all those features);
- there's an option to create "chats" (synchronous communication), although that obviously overlaps with Slack https://moby-test.groups.io/g/main/chat/245
- there's a calendar to create events
- a custom "database" feature; https://moby-test.groups.io/g/main/table?id=1017
- a wiki https://moby-test.groups.io/g/main/wiki/home

So lots of features, but usability is a bit lacking IMO

**Comment by krasi-georgiev** [comment]
@thaJeztah I was also looking at `confluence`  videos and it also looks powerful but the gui looks a bit old school.

it seems that they offer it for free for open source projects and looks like it integrates ok with jira (their issues tracker) which on another hand can use git

**Comment by thaJeztah** [comment]
Confluence is used by Docker internally, but I too am always confused by the interface. Still considering discourse as an option (http://www.discourse.org); can either be a "hosted" solution, or run on our own infrastructure https://hub.docker.com/r/discourse/discourse/)

**Comment by krasi-georgiev** [comment]
@thaJeztah yes that looks nice it is what the forum is built on 
haven't been there much so someone else should comment if it is any better than github.

I like that it is open source so  maybe it can be integrated  with the github issues,pr and mentions
I find these the most useful features.

for proposals  discussion `polls` are great but seems that discourse also supports that.

**Comment by thaJeztah** [comment]
Yes, discourse is definitely more polished, so perhaps we should set up a test discourse to see if we like it.

**Comment by krasi-georgiev** [comment]
@thaJeztah this is what the forums.docker.com uses so everyone should be familiar with  it.

**Comment by krasi-georgiev** [comment]
@thaJeztah , @vieux should we make a list with must and nice to have features for the replacement?

There aren't so many options, but having the list will help to make a decision I think.

**Comment by alexellis** [comment]
-1 for Confluence.. unless your version supports articles in Markdown (without the clunky "insert markdown" plugin?

**Comment by johnmark** [comment]
My experience:

Discourse is pretty good for async Q&A. The first time I used it was in lieu of a mailing list (talk.manageiq.org) 

mailman3 + hyperkitty can be a good compromise for those who want/need/insist on a mailing list, while still presenting a relatively modern web forum interface. 

If I had to pick, it would be Discourse. 

Confluence makes me cry.

**Comment by johnmark** [comment]
Also, if you grow tired of Slack, there's always mattermost - https://about.mattermost.com/

**Comment by thaJeztah** [comment]
I created a voting form for this; let yourself be heard :)

https://docs.google.com/forms/d/e/1FAIpQLSfbPf5YEhVxKfy41y9MmFANG7StIkucGKJv9tNE8GfLVCZHyw/viewform?usp=sf_link

**Comment by fntlnz** [comment]
@thaJeztah when's the expiration date of the poll ?

**Comment by thaJeztah** [comment]
@fntlnz we'll have a look at the results in tomorrow's stand-up, but we'll evaluate after a while (couple of months?) if needed

**Comment by duglin** [comment]
I'd be kind of curious to know what issues people have run into with Docker's use of github over the past number of years that the other alternatives do better?  One of the nice things I like about using github has nothing to do with the mechanism itself, rather all of the information about the project is kept in either in issues or PRs - not some other web site. It makes it a lot easier to find things.

**Comment by AkihiroSuda** [comment]
Now https://forums.mobyproject.org/ is ready (thank you @thaJeztah )

TODO
- E-mail activation URL (http://) can result in `["BAD CSRF"]` error. This can be resolved by using https:// instead of http://
- Investigate whether we can mitigate "Post must be at least 20 characters" limitation

**Comment by thaJeztah** [comment]
Thanks @AkihiroSuda - yes, I'll have to contact Discourse to check why HSTS isn't configured

**Comment by thaJeztah** [comment]
We also need to define categories for the forum; thinking of

- category per component (the "kits" etc)
- project organization / architecture category

**Comment by andrewhsu** [comment]
@thaJeztah do we perhaps desire github login for discourse? https://meta.discourse.org/t/configuring-github-login-for-discourse/13745

**Comment by thaJeztah** [comment]
@andrewhsu yes, that's definitely something we should enable; we got the forum running late yesterday, so didn't look into all available configuration options

**Comment by thaJeztah** [comment]
GitHub authentication is enabled now

**Comment by alexellis** [comment]
@thaJeztah I saw a thread about vote for async comms.. did that happen already?

**Comment by cpuguy83** [comment]
@alexellis Yes. We decided to use https://forums.mobyproject.org, which is using Discourse.
You can enable mailing-list mode in the user preferences in Discourse if that's the style you like.

**Comment by thaJeztah** [comment]
HSTS should be enabled now;

> Sorry about that, when we enable HTTPS we do it in 2 phases, we usually just turn it on first, let people fix up various login methods and then turn on HSTS. For new forums this makes less sense. Anyway, HSTS ahoy and enabled on mobyproject!!!

**Comment by thaJeztah** [comment]
I'm closing this issue; the forum is up and running, and other than some configuration changes needed, this is done.
