### ISSUE TITLE
Design questions: multi-stage builds and related subjects

### ISSUE THREAD

**Issue by loicgelle** [moby/moby#32868]
This issue to discuss about the design of certain very useful recent features / proposals about multi-stage builds. See #32507, #32063, #32100, #31257

I can see the need for running commands into a virtual context that relies on files generated by a previous build, or copying files from another image. Currently, to do this, many people basically use `docker cp`or shared folders and `COPY` statements, resulting in difficult orchestration between different stages of a build.

I think using multiple `FROM` statements into a Dockerfile just reduces the readability of the image build process and internalizes the orchestration instead of making it really easier. What makes Docker really attractive is precisely the Dockerfiles that are simple and describe a linear build process: one base image, several build commands, sometimes a runtime command. Adding features should try to preserve as much as possible this kind of implicit guidelines.

I prefer opening a separate issue because the subject involves many different features that are actively being developed. I hope that we can discuss about the higher-level design of this set of features here.

@tonistiigi

**Comment by tonistiigi** [comment]
Multi-stage build update is fully backward compatible. If you liked doing `docker cp` between builder invocations you can continue to do so. In fact, multiple `FROM` statements is not a new concept and were present in previous versions as well.

The amount of positive feedback we've had for this feature really doesn't match your view here. Multi-stage builds is an advanced feature so it is more complex than some other commands. More advanced features are something that users have been asking from us. I admit that when `Dockerfile` syntax was first created this use case was not probably considered, otoh the benefits of not breaking anything by developing a new format and its simplicity to be included as current workflow are much more important in this case.

The design for the proposal is discussed in the issues you listed, I would add #32904, #32550 . The process is open and community driven so there isn't a fixed general design. Some of these proposals will likely be implemented and some never will. I do admit it would be good to have a place that gathers all the builder related proposals and current development state. I'll think how this could be done.

**Comment by loicgelle** [comment]
The question is not whether people like doing `docker cp`or not. I think that we agree upon the fact that people usually find this orchestration burdensome and want to get rid of it.

Do people actually find the multiple `FROM` statements concept interesting because of the possibilities it offers or for style reasons? I think allowing multiple `FROM` is both really interesting in terms of features and dangerous because you do not keep separate things that should be kept separate (at least I think so).

Maybe we can try to implement the same set of features while keeping Dockerfiles separate, or at least extend them so that people can choose whatever "style" they prefer for their Dockerfiles...?

**Comment by andrerom** [comment]
@tonistiigi One thing we see as a limitation is that we would like to share a build stage / artifact between several prod images. Aka build stage for application, then pull out different pieces of that result to app image, web image, db image, binary image and so on.

Currently we do this by running several different commands, but if somehow we can have multi stage builds as part of the composition of the full stack, instead of just per image like now, that might also better fit with what @loicgelle is conceptually getting at.

**Comment by cpuguy83** [comment]
@andrerom Can you explain more? Maybe an example?

**Comment by andrerom** [comment]
@cpuguy83 Unsure if that will help or make it worse :)
php app, consisting of app(php-fpm), web(nginx), db(mariadb), varnish, solr/elastic, and volume for binary files to share between instances of app containers.

Building app with demo install which consists of some things besides the code itself:
- static assets, to be placed in nginx image
- database dump, to be placed or provided to db image somehow on boot up
- dynamic assets / binaries (images/files), to place in volume
- config for nginx, solr, db, varnish.. which in some cases get's generated during build based on misc variables

Some of these things should probably be done by app image, but others like config at least needs to be build into the different containers. And static assets is a bit question mark also, it does not change at run time, so would make sense to build it into web image.

**Comment by dnephin** [comment]
@andrerom Yes! These are use cases that I've been thinking about for a while. What we really need is to support a DAG (#32550), which will address some of these cases. Multi stage build with `--target=stagename` makes some progress in that direction as well.

Any case that requires a "run" to happen is probably outside the scope of the builder. I've been calling these cases "project tasks", which I see as a superset of build tasks. If you're interested I have been prototyping support for these use cases in a tool called [dobi](https://dnephin.github.io/dobi/). Slowly many of the features that dobi enabled are making themselves into the builder (for example dobi supported something like multi stage builds using bind mounts). 

There are examples of how to use dobi to solve some of the cases you mention under examples: https://github.com/dnephin/dobi/tree/master/examples

**Comment by tonistiigi** [comment]
@andrerom For the build tasks to share resources they should be combined into same Dockerfile and built with `--target`. As @dnephin commented, this isn't efficient yet as the execution is still linear instead of leveraging the DAG definition. If you are not a fan of big files I proposed https://github.com/moby/moby/pull/12749#issuecomment-289237698 as a possibility to allow different code organization. Also, note that build stages default to images. So you can use your other images in `--from` values. If they are not part of the same Dockerfile it is your responsibility to make sure they are up to date.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
