### ISSUE TITLE
Setup a short url for go pkgs

### ISSUE THREAD

**Issue by vieux** [moby/moby#32862]
We need to update the `docker/docker` imports in the code, but instead of using `moby/moby` let’s use a custom url so if we need to refactor, it won’t have such a big impact on external projects.

`go.mo.by/*` seems like a good candidate.

**Comment by ehazlett** [comment]
I can help with this if needed.

**Comment by andrewhsu** [comment]
I can see how if this dns is up and redirecting and the golang code in `moby/moby` (as of right now) is refactored to use the `go.mo.by` that it would facilitate the bigger step of #32871 . So, should this item be resolved as a hard dependency before #32871 is executed?

**Comment by amirmc** [comment]
What risks or issues are we potentially opening ourselves up to by using a `.by` domain?  It's Belarus and the rules are apparently at http://cctld.by — but I don't speak Russian :)

**Comment by thaJeztah** [comment]
@toli @LK4D4 perhaps you have thoughts, input? ^^

**Comment by amirmc** [comment]
+ @chanezon in case he has thoughts (I'm not sure who got the domain in the first place).

**Comment by alexellis** [comment]
Is a vanilla domain out of the question? moby.org etc?

**Comment by thaJeztah** [comment]
Yes; discussing on Slack; we think that using `mo.by` may be a risk. It's a nice URL, and can be used for other purposes (e.g. short URLs for social media or whatever), but may not be the best choice for something that needs to be _stable_

**Comment by toli** [comment]
if you are considering `mo.by` - that's already taken by some person over the Bay Bridge in Orinda, in 415 area code :)
```
Moby
US
Orinda
+14157472692
priley@gmail.com
```
it got registered originally in 2007 and expires this August, unless renewed.
i'm not well-versed in reading T&C for domain registrars, is there anything specific you want me to check? 
and anything other than `mo.by`?

**Comment by amirmc** [comment]
> if you are considering `mo.by` - that's already taken by some person

Oh, from the way it was being discussed I thought we already had this.  Since we don't, I think the specific discussion about `.by` doesn't matter.  We should use something we have :)

**Comment by thaJeztah** [comment]
I don't think there's plans to work on this; closing
