### ISSUE TITLE
Add better `getting started` to mobyproject.org

### ISSUE THREAD

**Issue by vieux** [moby/moby#32869]
Today moby tool lives at https://github.com/moby/tool 
It will be moved to this repo in the future (see https://github.com/moby/moby/issues/32859)

We should setup a short URL to be able to go get the tool no matter where it lives, so we can improve the  `getting started` section on mobyproject.org

should we use `go get go.mo.by/cmd/moby` ?

**Comment by thaJeztah** [comment]
- closing in favor of https://github.com/moby/moby/issues/32863
