### ISSUE TITLE
Update references of dockerproject.org 

### ISSUE THREAD

**Issue by vieux** [moby/moby#32860]
All the services hosted at *.dockerproject.org should be moved to *.mobyproject.org

**Comment by ehazlett** [comment]
I can work on this.

**Comment by thaJeztah** [comment]
From the top of my head, there's:

- apt.dockerproject.org and yum.dockerproject.org; which are kept for legacy docker releases; I don't think we should move those, as they distribute docker releases
- master.dockerproject.org is being replaced by nightly builds (this needs to be communicated though); at some point, we should deprecate that site
- https://dockerproject.org already redirects to https://mobyproject.org

closing this one, as I think we should be set, but let me know if I missed some

**Comment by thaJeztah** [comment]
There's some remaining references in the code that we could remove/update; https://github.com/moby/moby/search?utf8=✓&q=dockerproject.org&type=
