### ISSUE TITLE
TCP Connection dropped and packet loss

### ISSUE THREAD

**Issue by olegsavelos** [moby/moby#32885]
I am experimenting with docker on Windows Server 2016 (Google Cloud) and having some strange problems with TCP connections.
After container receive some average load of traffic TCP connections start to get dropped.
I have also tried debugging the traffic with HTTP Web API calls and what happens is strange.
On the side of the container data is received and served back to the caller but the caller (e.g web browser) never receives any data.

The system running docker have a static IP and container is bound to 0.0.0.0 address so there is no NAT in between. When running same process outside docker as a normal application the behaviour is not occurring.

Docker version

Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false

**Comment by friism** [comment]
Can you create a sample app that reproduces the problem (maybe it's just `microsoft/iis`) and post it along with instructions for reproducing here? Please also post instance size and type, and any other info that might be relevant.

**Comment by olegsavelos** [comment]
Well you can pull any of those https://hub.docker.com/r/gizmopowered/gizmoservice/tags/
To reproduce the problem you would need to make few api calls to container process.
Perhaps it would be easier if i made the container to go into this problematic state and provided you RDP credentials to the machine for debugging ?

**Comment by olegsavelos** [comment]
I am not sure if it could be of any help but it seems that problem appears when the response size sent from docker process exceed some size (cant be exact on that)
In case of TCP socket the client side gets connection reset, in case of HTTP Web API calls no response ever received on client.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
