### ISSUE TITLE
Docker Linux + Java: more then 100.000 open file descriptors created

### ISSUE THREAD

**Issue by couderhans** [moby/moby#32891]
**Description**

Running a java based server like activemq or glassfish in a docker container,
creates during start up, more then 700 000 file descriptors on the host, which stay open.

(For the glassfish container, this is the basic container before the deployment of application modules.)

**Steps to reproduce the issue:**
1. Docker pull and run rmohr/activemq:5.14.3
2. or pull and run flurdy/oracle-java7:latest
3. Run lsof | wc -l as root 

**Describe the results you received:**

root@OUR-HOST:/home/user# lsof | wc -l
727459

**Describe the results you expected:**

root@OUR-HOST:/home/user# lsof | wc -l
4529
(When containers activemq and glassfish are stopped)

**Additional information you deem important (e.g. issue happens only occasionally):**
Running jconsole against activemq or glassfish show only around 230 threads running.
Which is consistent with threads running on os level:

For example:
Our glassfish server has pid 2127
/proc/2127/task# = number of threads in jvm

But when checking the number of open file descriptors for that particular pid
root@DU-RTB-MPM3:~# lsof | grep 2127 | wc -l
474226 open file descriptors

It seems to have created file descriptors for threads which don't exist any more,
for ex: sudo lsof | grep 2127 results to tens of thousands of lines like:
java       2127  2516      gfish  833r      REG               0,48    36585       2470 /opt/glassfish3/glassfish/modules/javax.security.auth.message.jar
java       2127  2516      gfish  834r      REG               0,48    40914       2568 /opt/glassfish3/glassfish/modules/javax.security.jacc.jar

Task or thread id 2516 does not exist any more, can not be found in /proc/2127 

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 211
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: DU-RTB-MPM3
ID: 73XK:QZTT:D476:R5AX:DZHP:7MXF:AY4H:HOPQ:D6T7:54Z3:WMCM:UDKA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host: Ubuntu server 16.04 LTS (running in vsphere)

top - 13:09:22 up 23:20,  2 users,  load average: 0.03, 0.08, 0.17
Tasks: 180 total,   1 running, 179 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.5 us,  1.0 sy,  0.0 ni, 94.3 id,  0.7 wa,  0.0 hi,  0.5 si,  0.0 st
KiB Mem :  8175304 total,   438668 free,  3870276 used,  3866360 buff/cache
KiB Swap:  1044476 total,  1023940 free,    20536 used.  3803732 avail Mem

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
