### ISSUE TITLE
/etc/fstab from container not taken into account upon container restart - how to solve it? 

### ISSUE THREAD

**Issue by hashedvalue** [moby/moby#32890]
Hi All.

I am currently using a set of privileged glusterfs containers inside which I am starting gluster daemons. Through shared mountspaces mount done in the container is propagated to the host so no glusterfs client is needed on the host.

I run the container with a volume "_-v /data:/host_" and

_CMD /usr/sbin/glusterd -N -p /var/run/glusterd.pid_

and then I perform manually inside the container:

_#mount.glusterfs IP:/gluster_volume /host/gluster_volume_

and as a result I have gluster share mounted in /data/gluster_volume on the host thanks to mount event propagation. Additionally I put inside container:

#echo "IP:/gluster_volume /host/gluster_volume glusterfs defaults,_netdev 0 0" >> /etc/fstab

but the problem is that after restart /etc/fstab as far as I see is not taken into consideration and I have to manually mount the share inside the container.

Is this expected behaviour? Are there any ways to use /etc/fstab during start of the container?

**Comment by cpuguy83** [comment]
> Is this expected behaviour?

Yes. Docker starts 1 process in the container it's up to you to setup what you need.

> Are there any ways to use /etc/fstab during start of the container?

This file is generally read at system boot by by the init system (e.g. systemd) and performs the mounts.
The same thing could be done here.

Closing as this is not really an issue, but feel free to discuss.

**Comment by MirkoTV** [comment]
Hey, @hashedvalue did you fixed this in some way?
