### ISSUE TITLE
Missing unmount request for a volume on docker stop after using docker cp

### ISSUE THREAD

**Issue by pshahzeb** [moby/moby#32907]
**Description**

Docker doesn’t send the unmount request to the managed plugin during docker stop if docker stop is issued after using docker cp on a container.

**Steps to reproduce the issue:**
0. Pre-reqs: VMWare ESX with a Docker host VM inside. (Ubuntu 14.04.4 LTS) and docker-volume-vsphere VIB installed.
1. Install managed plugin See here https://github.com/vmware/docker-volume-vsphere#installation-instructions
2. docker volume create -d vsphere --name volume1
3. docker run -it --volume-driver=vsphere -v volume1:/vol1 --name bb busybox
4. (Inside container) touch /vol1/temp.txt
(Separate terminal)
5. docker cp bb:/vol1/temp.txt /tmp/
6. docker stop bb

**Describe the results you received:**
When docker run is issued, a mount request is received on the managed plugin.
When docker cp is issued, a mount and an unmount request is received on the managed plugin.
When docker stop is issued, no unmount request is received on managed plugin.

**Describe the results you expected:**
I expect to receive an unmount request for the docker stop command above.
(Note: if I skip docker cp (step 5) above, I see an unmount request on plugin side from docker on docker stop (step 6))
**Logs**
Results based on following logs of managed plugin since the plugin logs every mount and unmount request received.
Initially.
```
2017-04-27 17:25:56.341223418 -0700 PDT [INFO] Plugin options - port=1019
2017-04-27 17:25:56.341233131 -0700 PDT [INFO] Getting volume data from unix:///var/run/docker.sock
2017-04-27 17:25:56.527318226 -0700 PDT [INFO] Discovered 0 volumes in use.
2017-04-27 17:25:56.527342319 -0700 PDT [INFO] Docker VMDK plugin started mock_esx=false version="vSphere Volume Driver v0.4" port=1019
2017-04-27 17:25:56.527587657 -0700 PDT [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock"
```
After step 2 (docker volume create -d vsphere --name volume1)
```
2017-04-27 17:26:37.797641938 -0700 PDT [INFO] Attaching volume and creating filesystem fstype=ext4 name=volume1
2017-04-27 17:26:40.101610451 -0700 PDT [INFO] Volume and filesystem created name=volume1 fstype=ext4
```
After step 3 (docker run -it --volume-driver=vsphere -v volume1:/vol1 --name bb busybox)
```
2017-04-27 17:27:29.624606967 -0700 PDT [INFO] Mounting volume name=volume1
2017-04-27 17:29:54.486091123 -0700 PDT [INFO] Mounting volume name=volume1
```
No log after step 4
After step 5 (docker cp bb:/vol1/temp.txt /tmp/)
```
2017-04-27 17:29:54.486213491 -0700 PDT [INFO] Already mounted, skipping mount. name=volume1 refcount=2
2017-04-27 17:29:54.509863275 -0700 PDT [INFO] Unmounting Volume name=volume1
2017-04-27 17:29:54.509895835 -0700 PDT [INFO] Still in use, skipping unmount request. name=volume1 refcount=1
```
No log after step 6(docker stop bb) i.e. no unmount request.

docker log (Nothing interesting)
```
time="2017-04-27T17:25:56.509411102-07:00" level=info msg="API listen on /var/run/docker.sock"
time="2017-04-27T17:25:56.509475898-07:00" level=info msg="API listen on [::]:2375"
time="2017-04-27T17:26:51.677994114-07:00" level=error msg="plugin not found"
time="2017-04-27T17:27:23.655694581-07:00" level=error msg="Handler for POST /v1.27/containers/create returned error: No such image: busybox:latest"
time="2017-04-27T17:29:10.212115613-07:00" level=error msg="plugin not found"
time="2017-04-27T17:30:24.952272196-07:00" level=info msg="Container a4340483f0aa0c5ae35cba73b83adf175842d55b4bd87861aa004fbba670b961 failed to exit within 10 seconds of signal 15 - using the force"
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This can be reproduced consistently.
Seems like this should be reproducible with any third party volume managed plugin.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: sc-rdops-vm02-dhcp-52-237
ID: NINK:HV2F:IRM2:6JJU:XBVA:DW7J:CV5S:OARB:J4UL:O7S3:4LBA:7AVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare ESXi 6.5
Ubuntu 14.04.4 LTS under ESXi

//CC @pdhamdhere @MattAtTTU

**Comment by cpuguy83** [comment]
Thanks, I see the problem. Not sure how to fix yet.

**Comment by cpuguy83** [comment]
Yeah, the way this is setup with `docker cp` is totally wrong.

**Comment by cpuguy83** [comment]
Ok, please test #32909

Thanks!
