### ISSUE TITLE
Add support for node availability of unschedulable along with drain.

### ISSUE THREAD

**Issue by HuffMoody** [moby/moby#32901]
It would be useful if we could mark node availability as unschedulable. This would operate very similarly to what drain does by not allowing any new containers to be scheduled on that node, but does not do the second step of stopping all currently running containers.

This becomes particularly handy with cluster (auto) scale down where we could allow a long running container to finish executing (with `--restart-condition none`) then once all containers have finished on that node, issue a `docker node rm`.  With just drain alone, we are forced to restart that task on another node just to prepare to scale down the node it is already running on.

**Comment by thaJeztah** [comment]
Isn't this what "availability=pause" does?

**Comment by HuffMoody** [comment]
It was my understanding that "availablity=pause" issues a `docker pause` which would effectively pause the running containers.  I'm thinking more along the lines of keep the containers running but do not allow any new tasks to be scheduled on that node.

**Comment by cpuguy83** [comment]
From the docs: (https://docs.docker.com/engine/swarm/manage-nodes/#list-nodes)

> Pause means the scheduler doesn’t assign new tasks to the node, but existing tasks remain running.

**Comment by HuffMoody** [comment]
Yes you are absolutely right, I had got the impression somewhere that it had actually paused the running containers but it seems to work as needed.

My apologies.

**Comment by cpuguy83** [comment]
No problem at all. Thanks!
