### ISSUE TITLE
Dockerfile apt-get -Y switches stopped working

### ISSUE THREAD

**Issue by mikkokotila** [moby/moby#32913]
After no issues to do around 50 builds, suddenly the -Y switch for apt-get installs in my Dockerfile stopped working. 

```
Step 6/26 : RUN apt-get install git -Y
 ---> Running in 31398495b5b5
E: Command line option 'Y' [from -Y] is not understood in combination with the other options.
The command '/bin/sh -c apt-get install git -Y' returned a non-zero code: 100
```
The end result is that it seems that I can no longer build the container.

**Output of `docker version`:**

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**

Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 27
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934 GiB
Name: moby
ID: 6KMU:FTUO:3DXO:PCCH:WTCQ:BTVP:VY4P:G4XM:SB3H:S2KO:ILBN:HGAE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-04-28T11:28:43.500952229Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by mikkokotila** [comment]
UPDATE: strangely enough when I move the position of the -y switch to between apt-get and install as opposed to being last in the line, it works again :) So for me this is resolved, but looks like something might be off somewhere else.

**Comment by cpuguy83** [comment]
This is not a docker issue.
There error is coming from `apt-get`

Thanks for reporting.
Closing, but feel free to discuss. 👼

**Comment by mikkokotila** [comment]
Yea, I know. That's the strange thing here. Yesterday we have two man working on this, doing many builds with one Dockerfile. Then today the error, and fix is to move the -y. I had never seen any behavior like this, and while I can't of course prove it has something to do with the fact that yesterday was also the first day I started with Docker and that such issue had been reported at least some years ago to be associated with Docker based on a quick search...well I can't really say more :)
