### ISSUE TITLE
How to set `kernel.mem` with `--sysctl`

### ISSUE THREAD

**Issue by Karsten1987** [moby/moby#32911]
**Description**

I wanted to set the `kernel.mem` values via `--sysctl` and I wonder how the command line argument looks like

**Steps to reproduce the issue:**
1. docker run --privileged --shm-size=1G --sysctl kernel.shmmax=1073741824 --sysctl kernel.sem=250 32000 100 1024
2. docker run --privileged --shm-size=1G --sysctl kernel.shmmax=1073741824 --sysctl kernel.sem="250 32000 100 1024"

**Describe the results you expected:**
If I afterwards print "sysctl -a", I want to have the property set as specified above. I see that `/dev/shm` has the given size of 1G and the `kernel.shmmax` variable is correctly set. I don't know how to specify `kernel.mem` though. According to documentation it is currently supported.

**Output of `docker version`:**

```
Client:
Version:      1.12.3
API version:  1.24
Go version:   go1.6.3
Git commit:   6b644ec
Built:        Wed Oct 26 21:44:32 2016
OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1629
Running: 1
Paused: 0
Stopped: 1628
Images: 2175
Server Version: 1.12.3
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 4948
Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-100-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.676 GiB
Docker Root Dir: /var/lib/docker
```

**Comment by cpuguy83** [comment]
Setting `kernel.sem` is working here.

**Comment by cpuguy83** [comment]
Are you getting the values from the host instead?
Can you paste the output of `docker info`?

**Comment by Karsten1987** [comment]
Updated the original description with the docker info output.

> Setting kernel.sem is working here.

Can you provide some details on how to invoke `docker run` with `kernel.sem` values set? My struggle is the actual command line syntax.

**Comment by cpuguy83** [comment]
Just as you have it.

**Comment by Karsten1987** [comment]
OK, I just double checked and `kernel.sem="250 32000 100 1024"` with quotes around the parameters does work. 
Sorry for the noise, but thanks a lot for the quick support.
