### ISSUE TITLE
`docker swarm init` stuck if vm has less than 1024MB of memory

### ISSUE THREAD

**Issue by fleava** [moby/moby#32932]
**Description**
On a local machine running macOS, the command `docker swarm init` run inside a VirtualBox machine simply gets stuck and does nothing. This happens if the swarm master's machine has less than 1024MB of memory(fails with 512, but works with 1024, not sure if a value in between works)

**Steps to reproduce the issue:**
1. Create a vm with `docker-machine`
```
  docker-machine create \
    --driver virtualbox \
    --virtualbox-memory 512 \
    --virtualbox-disk-size 1000 \
    --engine-label purpose=backend \
    manager1
```
2. SSH into machine to init a swarm `docker-machine ssh manager1`
3. Run `docker swarm` command `docker swarm init --advertise-addr 11.22.33.44`
4. Nothing is shown, it simply gets stuck and does nothing

**Describe the results you received:**
Nothing

**Describe the results you expected:**
docker should explicitly warn user about insufficient memory of the host machine

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: r9hy8pjfghocewews2eqkhwph
 Is Manager: true
 ClusterID: 2bd3ag9gnbv3is2kjta53ndm7
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.112
 Manager Addresses:
  192.168.99.112:2377
  192.168.99.113:2377
  192.168.99.114:2377
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: manager1
ID: TRTY:6JQR:WHAF:CYY2:UMS3:NDRF:WEO4:VKFO:ELUM:7MLI:Z4HE:TAIF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 53
 Goroutines: 199
 System Time: 2017-04-29T07:55:09.145548961Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 purpose=backend
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
`VirtualBox` run on `macOS`

**Comment by aaronlehmann** [comment]
After I run `docker swarm init`, I see the Docker daemn using about 30 MB of memory (resident set size). It doesn't seem appreciably different from the amount of memory it used before `docker swarm init`.

How much free memory does the virtual machine have before running `docker swarm init`? After running the command, does `free` show that memory is exhausted? Does the Docker daemon log show anything that might explain the hang?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
