### ISSUE TITLE
Metrics naming conventions

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32948]
A couple of metrics we have are not following Prometheus naming conventions.

Since they're still experimental, we can fix those:
```
$ curl http://localhost:3000/metrics | promtool check-metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  155k  100  155k    0     0  9472k      0 --:--:-- --:--:-- --:--:-- 9692k
engine_daemon_events_subscribers_total: non-counter metrics should not have "_total" suffix
http_request_duration_microseconds: use base unit "seconds" instead of "microseconds"
```

/cc @crosbymichael  @juliusv @thaJeztah

**Comment by juliusv** [comment]
Note that `http_request_duration_microseconds` originates in the Prometheus Go client library and needs to be fixed there. AFAIR we want to fix it there (the `microseconds` metric got added early on before we had solid conventions), but want to lump the change together with other breaking changes. @beorn7 knows the plan for that better.

**Comment by beorn7** [comment]
The metric comes from the deprecated [InstrumentHandler](https://godoc.org/github.com/prometheus/client_golang/prometheus#InstrumentHandler).

The new and recommended tooling for instrumenting HTTP handlers are already included in head of client_golang, see the [promhttp package](https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp), functions starting `InstrumentHandler...` . (They are not in a release, but if you vendor the current head, you'll get them.)

**Comment by thaJeztah** [comment]
@aluzzardi did you want to take this one yourself?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
