### ISSUE TITLE
 x509: certificate is valid for 127.0.0.1 not

### ISSUE THREAD

**Issue by ShriramK** [moby/moby#32956]
**Steps to reproduce the issue:**
1. Create machine using the https://docs.docker.com/machine/drivers/hyper-v on Windows 10 Pro
2.  docker-machine env <machinename>
3.

**Describe the results you received:**

C:\WINDOWS\system32>docker-machine env <machinename>
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "<ip>:2376": x509: certificate is valid for 127.0.0.1, not <ip>
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

**Describe the results you expected:**
As shown https://docs.docker.com/machine/drivers/hyper-v

**Additional information you deem important (e.g. issue happens only occasionally):**

docker-machine ssh <machinename> works

Version 17.03.1-ce-win5 (10743)
Channel: stable
b18e2a5

**Output of `docker version`:**

```
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
Containers: 351
 Running: 0
 Paused: 0
 Stopped: 351
Images: 191
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 936
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 5RYX:JTWR:52NC:5P2J:JDUG:WTIP:YJ57:45KX:4NME:4BIT:ZD26:SUEJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
![dockersshregeneratecertsissue1](https://cloud.githubusercontent.com/assets/780653/25609801/69e0b55e-2f3e-11e7-81a0-950c31144f5b.png)

**Comment by ShriramK** [comment]
looks like similar issue's resolved in https://github.com/docker/machine/issues/531 
@ehazlett 
could this https://forums.docker.com/t/docker-machine-generic-driver-to-remote-host-using-ssh/4360/2
help ?

**Comment by friism** [comment]
Can you please re-open this on the docker-machine project issue tracker?

https://github.com/docker/machine

**Comment by ShriramK** [comment]
Thanks @friism  
I've re-opened it on the docker-machine project issue tracker as issue [4092](https://github.com/docker/machine/issues/4092)
