### ISSUE TITLE
BUG: docker-compose same port maping tcp/udp - only first row is mapped

### ISSUE THREAD

**Issue by mnuic** [moby/moby#32958]
In docker-compose file when exposing same port as udp and tcp, only the first row (port) is mapped, second is ignored.

**Steps to reproduce the issue:**
1. Define ports tcp and udp (example on container consul)
```
    ports:
    - 8301:8301/tcp
    - 8301:8301/udp
```
2. docker compose up -d consul
3. check docker inspect consul
```
                "8301/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8301"
                    }
                ],
                "8301/udp": null,
```
**Describe the results you received:**
Port 8301/tcp is OK (as docker inspect is shown), but port 8301/udp is not (it's defined as null)

**Describe the results you expected:**

Both udp and tcp ports shoud be exposed and not null. Checking iptables on host

iptables -L | grep 8301
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8301

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker --version
Docker version 17.04.0-ce, build 4845c56
```

**Output of `docker info`:**

```
docker info
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.858GiB
Name: HOST_NAME
ID: 6MHE:R62Q:TQKJ:D3IW:5I5F:ZKS3:NYLA:PBBH:Z5UE:GOJV:XMGZ:PIMM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 registry.XYZ.xyz
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
If you change the order, first port/udp, second port/tcp, then the first row port/udp will be exposed. Tried restarting the docker engine and host, firewall is disabled, security disabled, nothing works.

**Comment by mnuic** [comment]
Solution is:
```
    - 8301/tcp:8301/tcp
    - 8301/udp:8301/udp
```

**Comment by JPvRiel** [comment]
@mnuic how did the above work? A fairly recent version of compose (1.16.0):

```
ERROR: The Compose file '...syslog.yml' is invalid because:
services.rsyslog.ports is invalid: Invalid port "514/udp:514/udp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

Doesn't seem to accept the protocol specification twice.

**Comment by mnuic** [comment]
Try “514:514/udp”

**Comment by JPvRiel** [comment]
@mnuic thanks, I did try. No luck. I need to test further with latest versions of docker compose and docker.

Given this in the service definition for docker compose: 

```
    ports:
      - 514:514
      - 514:514/udp
      - 2514:2514
      - 6514:6514
      - 7514:7514
      - 8514:8514
```

When I run docker ps, I see `0.0.0.0:2514->2514/tcp, 0.0.0.0:6514->6514/tcp, 0.0.0.0:7514->7514/tcp, 514/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:8514->8514/tcp   rsyslog` in the output. When I run inspect, I see:

```
  "NetworkSettings": {
...
    "Ports": {
                "2514/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32775"
                    }
                ],
                "514/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "514"
                    }
                ],
                "514/udp": null,
                "6514/tcp": [
...
```
...
   ports:
      - 514:514/udp
      - 514:514
```

As well as `["514:514/udp", "514:514/tcp"]` and my experience is that docker 1.12 (as shipped with CentOS/RHEL) has this bug...

**Comment by mnuic** [comment]
Which version/format of compose are you using, 2.x, 3.x?

**Comment by JPvRiel** [comment]
> Which version/format of compose are you using, 2.x, 3.x?

Using compose file format v2.1, but also noticed an older version of compose v.1.13.0 was bundled into the base OS platform we test on...

I can't reproduce this bug with a newer version of docker engine or compose, and it seems it might be very isolated to the CentOS extras repo build of docker. So my instance of this bug should rather be addressed at the CentOS repo maintainer for the docker package - if I had the time to test further.

Tried to reproduce the exact issue on my dev box (Ubuntu), also with docker engine 1.12.6 and the same compose version (v.1.13.0), but it opened and exposed/binded all ports correctly. The issue seen on the test environment (CentOS) also has docker engine 1.12.6 and compose v.1.13.0. The only difference being build numbers for docker and the base OS. 

On Ubuntu:

```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

On CentOS:

```
# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64
```

So at this point, stumped and hopefully upgrading docker engine on CentOS from extra's repo with current/v1.12 to latest/1.13.

P.S. testing with the command `docker-compose -f docker-compose.test.yml up -d` and expecting all ports listed in the compose to be correctly bound and exposed on host via docker creating appropriate DNAT rules (as checked via `iptables-save`)
