### ISSUE TITLE
Adding an option to `docker build` to export the hash of the build context

### ISSUE THREAD

**Issue by samoht** [moby/moby#32963]
With https://github.com/moby/moby/pull/32406 it will be possible to export the **image** hash into a file when using `docker build`. This is great to use in scripts to see both the log outputs and to get the image ID but it is sometime not enough for build scripts.

In [linuxkit](https://github.com/linuxkit/linuxkit) we would like to tag the resulting image with the hash of the sources used to built it. To do this, we used to [hash](https://github.com/linuxkit/linuxkit/blob/master/projects/miragesdk/src/Makefile#L19-L23) the sources manually -- [now](https://github.com/linuxkit/linuxkit/blob/master/kernel/Makefile#L14) we are taking the Git subtree as a less error-prone approximation. I think it would be a great addition to `docker build` if that hash of the sources would be computed automatically so it could be used as a tag for fully reproducible builds. 

For instance:

```
docker build --bidfile=build.id .
```
which would put the hash of the **build context** into `build.id`.

**Comment by tonistiigi** [comment]
Design LGTM if linuxkit will start using this.

Some alternatives would be to allow `docker build -t foo:%BUILDID%` but that would also need a way to find this tag for pushing(maybe `push -a` like we have for `pull`). Or `docker inspect -f '{{.BuildID}}` but that would only work for locally built images.

Could you describe better what how the buildid would be computed? Is it cache ID of whole context + Dockerfile data. Or would we determine what files are actually used by the builder, or preprocess Dockerfile(build definition) to remove unused build stages. Also, I think ID with these properties could be calculated based on `inspect` output, basically you need to hash the history array from there.

@dnephin @duglin

**Comment by justincormack** [comment]
We always use all the files in the context in LinuxKit, and don't use
docker ignore, which is why git tree hash is our current choice.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
