### ISSUE TITLE
Windows Server containers cannot access other containers' unpublished ports

### ISSUE THREAD

**Issue by sixeyed** [moby/moby#32969]
**Description**

Containers in the same NAT network on Windows can't access exposed ports on other containers, unless they have been published to the host. This seems to be an issue with the overlay networking update (KB4015217). Previously Windows containers could access other containers' ports without having to publish them.

**Steps to reproduce the issue:**

On a Windows Server 2016 machine with all the latest updates installed, run `docker-compose up` for this compose file:

```
version: '3'

services:
  
  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
```

**Describe the results you received:**

Kibana fails to connect to Elasticsearch. The container IP address resolves correctly, but can;t access port `9200`:

```
PS> docker exec elton_kibana_1 ping elasticsearch

Pinging elasticsearch [172.30.167.207] with 32 bytes of data:
Reply from 172.30.167.207: bytes=32 time<1ms TTL=128
Reply from 172.30.167.207: bytes=32 time<1ms TTL=128
Reply from 172.30.167.207: bytes=32 time<1ms TTL=128
Reply from 172.30.167.207: bytes=32 time<1ms TTL=128

Ping statistics for 172.30.167.207:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

PS> docker exec elton_kibana_1 powershell iwr -usebasicparsing http://elasticsearch:9200
iwr : An error occurred while sending the request.
At line:1 char:1
+ iwr -usebasicparsing http://elasticsearch:9200
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...1.14393.100
   0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand
```

**Describe the results you expected:**

Port `9200` is not published on the Elasticsearch container, but it is exposed in the image. Both containers are on the same network, so Kibana should be able to reach Elasticsearch without the port being published on the host.

If you publish port `9200` in the Elasticsearch definition in the compose file, then everything works correctly, the Kibana container can connect to Elasticsearch and you can run the `ping` and `iwr` commands successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

This does not seem to be a Docker regression - I've tried with 17.03, 17.04 and 17.05 on the same Windows VM with the same result. But this was working correctly in February - before KB4015217 - when I ran [this demo](https://github.com/sixeyed/presentations/blob/master/docker-london/docker-windows-state-union/docker-compose.yml), with multiple connected containers, with only the public ports published.

**Output of `docker version`:**

```
PS> docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Wed Apr 12 19:43:25 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Wed Apr 12 19:43:25 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
PS> docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.05.0-ce-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7GiB
Name: win-docker-test
ID: O7JS:WDLQ:X5PC:D34G:RB5C:AZJ2:6XD3:IICI:HXUO:7OUH:ZUB2:6YSO
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VM, based on image 'Windows Server 2016 Datacenter with Containers'. Installed all Windows updates, and tried different Docker versions.

**Comment by kallie-b** [comment]
@sixeyed -- we believe this is an issue with firewall rules. I'm sparking an investigation internally.

**Comment by kallie-b** [comment]
@sixeyed -- pinging you again to make sure you receive the edit of my last reply :)

**Comment by sixeyed** [comment]
@kallie-b thanks, I will reproduce and send you the logs.

**Comment by friism** [comment]
@sixeyed did you get a chance to dig out logs?

**Comment by sixeyed** [comment]
@friism I can no longer recreate this on Docker `17.05.0-ce` with latest Windows updates on 10 or Server 2016. Either the Docker update or a Windows update fixed it - not sure which, but containers can access unpublished ports now. Thanks for the logging info @kallie-b, I'm sure that will be useful.
