### ISSUE TITLE
No way to specify "--pid=host" equivalent in docker managed plugins config.json 

### ISSUE THREAD

**Issue by taherv** [moby/moby#32973]
**Description**

We are writing a managed volume plugin for Docker. Our plugin intends to run commands/binaries from the host's mount namespace. This is achieved by running the host binary via nsenter, requiring the managed volume plugin to run in the host's pid namespace. However, there is nothing in the config.json format to specify the equivalent of "--pid-host". There is a "--network=host", but no way to configure the plugin to run in the host's pid namespace. Please add this option.

**Comment by taherv** [comment]
@tiborvass Your input on this is greatly appreciated.

**Comment by taherv** [comment]
@patrick-east

**Comment by anusha-ragunathan** [comment]
plugin config indeed has `pidhost` (boolean). It was added in 17.05. 
https://github.com/moby/moby/blob/master/docs/extend/config.md#config-field-descriptions

**Comment by taherv** [comment]
Documentation for the config fields is not updated ... reopening this bug.

**Comment by thaJeztah** [comment]
@taherv 17.05 is not yet released so the docs are not published yet

**Comment by taherv** [comment]
Ok ! Ill wait then ... :) Thank you !
