### ISSUE TITLE
Add support for --read-only in stack deploy

### ISSUE THREAD

**Issue by diogomonica** [moby/moby#32994]
**Description**
Currently it is not possible to deploy a service with `docker stack deploy` that ends up running containers with a read-only filesystem.

We should add support for it.

**Comment by thaJeztah** [comment]
ping @dnephin @vdemeester PTAL

**Comment by dnephin** [comment]
SGTM. As we add flags to the docker cli they should be added to the latest version of the Compose file

**Comment by vdemeester** [comment]
Closing as docker/cli#73 is merged 😉
