### ISSUE TITLE
docker-network connectivity issues between containers in external overlay network

### ISSUE THREAD

**Issue by lievendp** [moby/moby#32990]
Description:
Containers in an overlay network have intermittent network connectivity issues which can be seen using ping and health checks (consul http health check in our case)
The containers can be on the same host even.

**Steps to reproduce the issue:**
1. start the container stack (consul, registrator, consul-template, haproxy and the backend tomcat server), connect to the same overlay network.
2. run ping in container consul over the overlay network to container serverbackend (or from any other of the containers in the overlay network) sit back and wait, ping will give a couple timeouts.
Also, more frequently, scriptedly run http check every 5 seconds, using curl and put response wait <2s which is plenty for service on same host in different container to respond: it will fail (returning code 000 instead of 200) and generally this will happen multiple short times over the timespan of 5 minutes.

**Describe the results you received:**
timeouts in ping and http health check failing, ip monitor showing stale entries on the overlay network clients for short durations.
It seems that often there are ip's in the overlay network which shouldn't exist (no container having those) This doesn't change after deleting overlay network, removing all data from the external KV (consul) and recreating overlay etc.

**Describe the results you expected:**
never timeouts on ping
never http health check fail
no network trouble stale entries (mac)

**Additional information you deem important (e.g. issue happens only occasionally):**
- stopped all containers, deleted overlay network, deleted external KV (consul) datadir, stopped docker on all hosts and restarted from zero with the same results. (cuts in the network)
- running "ip monitor" in the container shows stale entries in the overlay network, even showing eth0 interface fail in the container (the interface linked to the overlay network)
- also seeing the following error in docker logs:
level=error msg="could not resolve peer \"10.0.0.16\": timed out resolving peer by querying the cluster"
the ip is in the range of the overlay but there's no container linked to it whatsoever
the cluster is on a totally different ip-range (options)

**Output of `docker version`:**

```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:53:45 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:53:45 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 19
 Running: 17
 Paused: 0
 Stopped: 2
Images: 34
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 13.72 GB
 Data Space Total: 16.11 GB
 Data Space Available: 2.383 GB
 Metadata Space Used: 4.702 MB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 28.85 MB
 Thin Pool Minimum Free Space: 1.611 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null host bridge
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 15.51 GiB
Name: <hostname>
ID: <ID>
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): false
Http Proxy:
Https Proxy:
No Proxy:
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: consul://127.0.0.1:9500
Cluster Advertise: <LAN-IP-ADDRESS>:2376
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware esx hosts

**Comment by cpuguy83** [comment]
I would recommend to upgrade to at least 17.03 as there are numerous fixes to networking and other bits, especially in swarm mode.

Closing since there are numerous other issues open regarding network timeouts on the overlay driver in addition to what's already been fixed since 1.12.x.
Here's a (rough) list of open items related to timeouts on swarm networking: https://github.com/moby/moby/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20network%20timeout%20label%3Aarea%2Fswarm%20label%3Aarea%2Fnetworking%20timeout

Thanks! 👼
