### ISSUE TITLE
Adding format utility functions for creating services with templates

### ISSUE THREAD

**Issue by shanewholloway** [moby/moby#33000]
**Feature Request**

I am finding the support for [creating services using templates](https://github.com/moby/moby/blob/master/docs/reference/commandline/service_create.md#create-services-using-templates) useful for our deployment scenarios. Thank you!

I'd like to be able to be able to use Docker's standard [format command and log output functions](https://docs.docker.com/engine/admin/formatting/), specifically `json`, to pass environment variables. I'm currently doing a very explicit:

```
SWARM_SERVICE={"service": { "ID":"{{.Service.ID}}", "Name": "{{.Service.Name}}", "Labels": "{{js .Service.Labels}}" }}
```

With support for the standard formatting functions, this would be nicely concise as:

```
SWARM_SERVICE={"service": {{json .Service}} }
```

**Comment by thaJeztah** [comment]
Can you explain a bit more in detail how this would be used? Is this to _create_ new services based on a template, or to define a default format for (e.g.) `docker service ls`?

If the last, you can define default formats in `~/.docker/config.json`, see https://docs.docker.com/engine/reference/commandline/cli/#configuration-files

**Comment by shanewholloway** [comment]
I'm using the templates in concert with `docker stack deploy` and docker-compose files to allow my custom services to be aware of their cluster configuration — the name of the service it is part of, which service slot it is, which swarm node it exists on, etc…

Without a `json` formatting function, either I have to write a Go data parser, or I have to explicitly list each nested item I want as in the example above.  It gets tedious across many service definitions in the docker-compose v3 file, distracting from more important configuration details.

I'm using the service template defined environment variables to enable self-configuring clusters and self-nominating database masters (e.g. when Service.Slot == "1").

**Comment by thaJeztah** [comment]
Sounds like you're looking for an introspection API, something like https://github.com/moby/moby/pull/26331 ?

**Comment by shanewholloway** [comment]
The introspection API would address my use cases, yes.

That said, the ability to use the same Go Template formatting functions/tools in both the Docker CLI and the Swarm environment variables would be a pleasant consistency.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
