### ISSUE TITLE
docker 1.12.6 devicemapper has side effect on mount output?

### ISSUE THREAD

**Issue by hce137** [moby/moby#33013]
**Description**
Hi,
I have set devicemapper direct-lvm mode as instructions at [docker docs](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production). 

When the docker service started, I checked `mount` output, here are the strange lines
```
# mount | grep LVMroot
/dev/mapper/rhel-LVMroot on / type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/rhel-LVMroot on /var/lib/docker/devicemapper type xfs (rw,relatime,attr2,inode64,noquota)
```
FYI, logical volume LVMroot was mounted to / as the os is initialized.

But, the contents in /var/lib/docker/devicemapper appear to be correct. If I umount /var/lib/docker/devicemapper, it doesn't break anything. 

If I manually mount /dev/mapper/rhel-LVMroot to /var/lib/docker/devicemapper, as you imagine, the whole staffs at / now are able to be seen at var/lib/docker/devicemapper.

Tried with loopfile mode, this issue still exists.
I tried again with docker 1.10.3, I didn't see this strange issue, so I guess this has something to do with docker 1.12.6.

any thoughts?

**Additional environment details (AWS, VirtualBox, physical, etc.):**
### docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: rhel-thinpool
 Pool Blocksize: 131.1 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 12.98 MB
 Data Space Total: 160.7 GB
 Data Space Available: 160.7 GB
 Metadata Space Used: 352.3 kB
 Metadata Space Total: 79.69 MB
 Metadata Space Available: 79.34 MB
 Thin Pool Minimum Free Space: 16.07 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 62.76 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by fntlnz** [comment]
Can you post the output of this command?

```
lvs -o+seg_monitor
```

**Comment by fntlnz** [comment]
Also  a `df 'h` would be useful. Mind that the devicemapper direct-lvm needs a configured volume group to create the logicaL volumes .
Also the output of `lsblk` would be useful

**Comment by hce137** [comment]
@fntlnz , thanks for reply. I understand the thin volume that I created sitting on the same volume group with others might be a problem source, so I set docker to use loopfile mode, but the problem persist.

```
# lvs -o+seg_monitor
  LV       VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Monitor
  LVMhome  rhel -wi-ao----   5.00g
  LVMroot  rhel -wi-ao----  20.00g
  LVMswap1 rhel -wi-ao----   4.00g
  LVMswap2 rhel -wi-ao----   4.00g
  LVMtmp   rhel -wi-ao----   5.00g
  thinpool rhel twi-a-tz-- 149.67g             0.01   0.44                             monitored
```

```
# df -h
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/rhel-LVMroot   20G  3.2G   17G  16% /
devtmpfs                   32G     0   32G   0% /dev
tmpfs                      32G   12K   32G   1% /dev/shm
tmpfs                      32G  193M   32G   1% /run
tmpfs                      32G     0   32G   0% /sys/fs/cgroup
/dev/vda1                1014M  132M  883M  13% /boot
/dev/mapper/rhel-LVMtmp   5.0G   33M  5.0G   1% /tmp
/dev/mapper/rhel-LVMhome  5.0G  360M  4.7G   8% /home
tmpfs                     6.3G     0  6.3G   0% /run/user/0
```

```
# lsblk
NAME                    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda                     252:0    0   720G  0 disk
├─vda1                  252:1    0     1G  0 part /boot
├─vda2                  252:2    0    68G  0 part
│ ├─rhel-LVMroot        253:0    0    20G  0 lvm  /
│ ├─rhel-LVMswap1       253:1    0     4G  0 lvm  [SWAP]
│ ├─rhel-LVMswap2       253:2    0     4G  0 lvm  [SWAP]
│ ├─rhel-LVMhome        253:3    0     5G  0 lvm  /home
│ ├─rhel-LVMtmp         253:4    0     5G  0 lvm  /tmp
│ └─rhel-thinpool_tmeta 253:5    0    76M  0 lvm
│   └─rhel-thinpool     253:7    0 149.7G  0 lvm
└─vda3                  252:3    0   651G  0 part
  └─rhel-thinpool_tdata 253:6    0 149.7G  0 lvm
    └─rhel-thinpool     253:7    0 149.7G  0 lvm
```

**Comment by cpuguy83** [comment]
What's the actual issue?

/var/lib/docker/devmapper is re-mounted to set mount propagation to private to prevent docker mounts leaking into containers.

**Comment by hce137** [comment]
@cpuguy83 
After googling "mount propagation" and reading the [first result](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) it returns, I kind of understand what you said, "prevent docker mounts leaking into containers".

What I don't understand is that the same LV is mounted at two points, "/" and "/var/lib/docker/devicemapper", but `ls /` and `ls /var/lib/docker/devicemapper` gives different output. Maybe I misunderstand some features that 'mount' provides. Would you please shed more light on this? Thanks

**Comment by cpuguy83** [comment]
@hce137 Because `/var/lib/docker/devicemapper` is still on the same mount.

What happens is essentially this:

```
# mount --bind /var/lib/docker/devicemapper /var/lib/docker/devicemapper
# mount --make-private /var/lib/docker/devicemapper
```

So `/var/lib/docker/devicemapper` is still indeed sitting on /dev/mapper/rhel-LVMroot, just that it's bind-mounted to itself so that `--make-private` will work.

**Comment by hce137** [comment]
@cpuguy83 Thank you so much! Now it makes sense to me.

**Comment by cpuguy83** [comment]
Cool, thanks @hce137!
