### ISSUE TITLE
Panic on 17.03.1-ce [invalid memory address || daemon/container.go]

### ISSUE THREAD

**Issue by skapin** [moby/moby#33018]
**Description**
When I do a service docker start It fail on start.
 It was working well 1-2 weeks ago.

There is some output log
**systemctl status docker.service**
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since jeu. 2017-05-04 13:42:49 UTC; 1min 59s ago
     Docs: https://docs.docker.com
  Process: 2077 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=2)
 Main PID: 2077 (code=exited, status=2)

mai 04 13:42:49 odroid dockerd[2077]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC
mai 04 13:42:49 odroid dockerd[2077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github
mai 04 13:42:49 odroid dockerd[2077]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(
mai 04 13:42:49 odroid dockerd[2077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github
mai 04 13:42:49 odroid dockerd[2077]: main.main()
mai 04 13:42:49 odroid dockerd[2077]:         /usr/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/d
mai 04 13:42:49 odroid systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
mai 04 13:42:49 odroid systemd[1]: Failed to start Docker Application Container Engine.
mai 04 13:42:49 odroid systemd[1]: docker.service: Unit entered failed state.
mai 04 13:42:49 odroid systemd[1]: docker.service: Failed with result 'exit-code'.
```

And, log when i start docker tought command directly :  
```
odroid@odroid:~$ sudo /usr/bin/dockerd
INFO[0000] libcontainerd: new containerd process, pid: 3316 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
INFO[0001] [graphdriver] using prior storage driver: aufs 
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] mountpoint for pids not found                
INFO[0001] Loading containers: start.                   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x21 pc=0x15ba90]

goroutine 1 [running]:
panic(0x125bfe0, 0x11e0c010)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
github.com/docker/docker/daemon.(*Daemon).Register(0x121ba000, 0x12084700, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:93 +0x24
github.com/docker/docker/daemon.(*Daemon).restore(0x121ba000, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:167 +0x1198
github.com/docker/docker/daemon.NewDaemon(0x120eca00, 0x1b5cd28, 0x121410c0, 0x1b55150, 0x12136580, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:710 +0x28c4
main.(*DaemonCli).start(0x1213b860, 0x1213b800, 0x13c104b, 0x17, 0x120eca00, 0x12131530, 0x11e87bd0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/daemon.go:263 +0x1384
main.runDaemon(0x101c00, 0x13c104b, 0x17, 0x120eca00, 0x12131530, 0x11e87bd0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:86 +0x168
main.newDaemonCommand.func1(0x12111d40, 0x1b8c1d4, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6c
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x12111d40, 0x11e6e0c8, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x4d0
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12111d40, 0x12111d40, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x3c4
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0x12111d40, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x28
main.main()
	/usr/src/docker/.gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:106 +0x13c
odroid@odroid:~$
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**System:** Linux odroid 3.10.103-124 #1 SMP PREEMPT Tue Oct 11 11:51:06 UTC 2016 armv7l armv7l armv7l GNU/Linux
**Os:** Ubuntu Xenial for ARMHF

**Output of `docker version`:**

```
odroid@odroid:~$ sudo docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:18:59 2017
 OS/Arch:      linux/arm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

@cpuguy83 here we are. Thanks a lot

**Comment by cpuguy83** [comment]
The offending line is:
```
c.Config.OpenStdin
```

Where at this point it is not possible for `c` to be nil, and I do not know how `Config` could ever be nil.
Something definitely seems off.

Any details on the container configurations you have on disk?

**Comment by floion** [comment]
Getting the same issue on docker 1.10.3

Jun 16 07:49:16 ac66c91 docker[1958]: ..panic: runtime error: invalid memory address or nil pointer dereference
Jun 16 07:49:16 ac66c91 docker[1958]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x29 pc=0x133d5c]
Jun 16 07:49:16 ac66c91 docker[1958]: goroutine 1 [running]:
Jun 16 07:49:16 ac66c91 docker[1958]: panic(0xc3bdb8, 0x1151e008)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/panic.go:500 +0x33c
Jun 16 07:49:16 ac66c91 docker[1958]: github.com/docker/docker/daemon.(*Daemon).Register(0x11588f00, 0x11567260, 0x0, 0x0)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds//build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/daemon/daemon.go:222 +0x2c
Jun 16 07:49:16 ac66c91 docker[1958]: github.com/docker/docker/daemon.(*Daemon).restore(0x11588f00, 0x0, 0x0)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/daemon/daemon.go:304 +0x1004
Jun 16 07:49:16 ac66c91 docker[1958]: github.com/docker/docker/daemon.NewDaemon(0x1158bc80, 0x11559198, 0x0, 0x0, 0x0)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/daemon/daemon.go:809 +0x246c
Jun 16 07:49:16 ac66c91 docker[1958]: main.(*DaemonCli).CmdDaemon(0x119fef10, 0x11564010, 0x7, 0x8, 0x0, 0x0)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/docker/daemon.go:252 +0x113c
Jun 16 07:49:16 ac66c91 docker[1958]: reflect.callMethod(0x116cd1a0, 0x119afe20)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/reflect/val  ue.go:630 +0x1ac
Jun 16 07:49:16 ac66c91 docker[1958]: reflect.methodValueCall(0x11564010, 0x7, 0x8, 0x1, 0x116cd1a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/reflect/asm  _arm.s:29 +0x38
Jun 16 07:49:16 ac66c91 docker[1958]: github.com/docker/docker/cli.(*Cli).Run(0x116ccfc0, 0x11564008, 0x8, 0x9, 0x0, 0x0)
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x2c4
Jun 16 07:49:16 ac66c91 docker[1958]: main.main()
Jun 16 07:49:16 ac66c91 docker[1958]:         /home/florin/builds/build/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/docker/1.10.3+gi  t20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/docker/docker.go:63 +0x2d4

**Comment by floion** [comment]
The offending line is again
`` if container.Config.OpenStdin {"
 from:

func (daemon *Daemon) Register(container *container.Container) {
        // Attach to stdout and stderr
        if container.Config.OpenStdin {
                container.NewInputPipes()
        } else {
                container.NewNopInputPipe()
        }

        daemon.containers.Add(container.ID, container)
        daemon.idIndex.Add(container.ID)

**Comment by floion** [comment]
Forgot to mention this is using aufs storage driver.

**Comment by thaJeztah** [comment]
@floion it's a custom build for armhf/armv7?

**Comment by floion** [comment]
Yes @thaJeztah

**Comment by thaJeztah** [comment]
Thanks; it helps getting a bit of context.

Perhaps it's possible to get the on-disk configuration (json) of the offending container?

**Comment by floion** [comment]
Hm, I get this when trying to start the docker daemon. Prior to this there were containers running but how could I tell which of them is causing this?

**Comment by floion** [comment]
Is there anything else we could to debug this?

**Comment by petrosagg** [comment]
@thaJeztah got some more information on @floion's issue (we're colleagues). Here is the on-disk configuration:

config.v2.json:

```json
{
  "State": {
    "Running": false,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "RemovalInProgress": false,
    "Dead": false,
    "Pid": 0,
    "ExitCode": 0,
    "Error": "",
    "StartedAt": "0001-01-01T00:00:00Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
  },
  "ID": "aa7f29cfd2de5e6f3e99773015eb35025b9cb57907fc4c30b53d7da4a6e35b6b",
  "Created": "0001-01-01T00:00:00Z",
  "Path": "",
  "Args": null,
  "Config": null,
  "Image": "",
  "NetworkSettings": null,
  "LogPath": "",
  "Name": "/pensive_bose",
  "Driver": "",
  "MountLabel": "",
  "ProcessLabel": "",
  "RestartCount": 0,
  "HasBeenStartedBefore": false,
  "HasBeenManuallyStopped": false,
  "MountPoints": {},
  "AppArmorProfile": "",
  "HostnamePath": "",
  "HostsPath": "",
  "ShmPath": "",
  "ResolvConfPath": "",
  "SeccompProfile": ""
}
```

hostconfig.json:

```json
{
  "Binds": [
    "/resin-data/123:/data",
    "/tmp/resin-supervisor/123:/tmp/resin",
    "/lib/modules:/lib/modules",
    "/lib/firmware:/lib/firmware",
    "/run/dbus:/host/run/dbus"
  ],
  "ContainerIDFile": "",
  "LogConfig": {
    "Type": "",
    "Config": null
  },
  "NetworkMode": "host",
  "PortBindings": {},
  "RestartPolicy": {
    "Name": "always",
    "MaximumRetryCount": 0
  },
  "VolumeDriver": "",
  "VolumesFrom": null,
  "CapAdd": null,
  "CapDrop": null,
  "Dns": [],
  "DnsOptions": [],
  "DnsSearch": [],
  "ExtraHosts": null,
  "GroupAdd": null,
  "IpcMode": "",
  "Links": [],
  "OomScoreAdj": 0,
  "PidMode": "",
  "Privileged": true,
  "PublishAllPorts": false,
  "ReadonlyRootfs": false,
  "SecurityOpt": null,
  "UTSMode": "",
  "ShmSize": 67108864,
  "ConsoleSize": [
    0,
    0
  ],
  "Isolation": "",
  "CpuShares": 0,
  "CgroupParent": "",
  "BlkioWeight": 0,
  "BlkioWeightDevice": null,
  "BlkioDeviceReadBps": null,
  "BlkioDeviceWriteBps": null,
  "BlkioDeviceReadIOps": null,
  "BlkioDeviceWriteIOps": null,
  "CpuPeriod": 0,
  "CpuQuota": 0,
  "CpusetCpus": "",
  "CpusetMems": "",
  "Devices": null,
  "KernelMemory": 0,
  "Memory": 0,
  "MemoryReservation": 0,
  "MemorySwap": 0,
  "MemorySwappiness": -1,
  "OomKillDisable": false,
  "PidsLimit": 0,
  "Ulimits": null
}
```

There are a few interesting and baffling things here. First, the configs are fully written to disk, the JSON is not half written. `hostconfig.json` is correct, having the correct bind mounts and restart policies. We create this container using `docker create` and sometime later we start it.

The config.v2.json on the other hand is as if the serialiser got an empty struct. Even the `Created` field is initialised to 0, but this value is set [very early in the creation process](https://github.com/moby/moby/blob/17.03.x/daemon/container.go#L128-L129):

```golang
	base := daemon.newBaseContainer(id)
	base.Created = time.Now().UTC()
```

Initially I was suspecting data races being the issue for Config. But the fact that Created is also 0 eliminates it?

I've inspected all the paths I could find to try and see if there is an execution path that will cause `container.ToDisk` to be called on an uninitialised container but couldn't find one. But I still have no idea how the correct hostconfig.json ended up there..

**Comment by AkihiroSuda** [comment]
Should have been fixed in recent versions.
