### ISSUE TITLE
Locale prompt when running mkImage for ubuntu docker image

### ISSUE THREAD

**Issue by jerishsd** [moby/moby#33011]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**Description**

Prompt for locale selection when trying to build ubuntu docker

**Steps to reproduce the issue:**
1. Clone moby latest
2. cd contrib
3. sudo ./mkimage.sh -t junk/ubuntu1 debootstrap --include=ubuntu-minimal --components=main,universe xenial

(Note change - "xenial")

**Describe the results you received:**

Saw the following in the console with a prompt to select locale (Expectation is for that to be automated)

Fetched 31.1 MB in 10s (2878 kB/s)                                                                                                              
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_CA:en",
	LC_ALL = (unset),
	LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Extracting templates from packages: 100%
Preconfiguring packages ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
locale: Cannot set LC_CTYPE to default locale: No such file or directory

**Describe the results you expected:**

No prompt should be provided to user.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue reproduces consistently

**Output of `docker version`:**
docker -v
Docker version 17.03.1-ce, build c6d412e

(paste your output here)
```

**Output of `docker info`:**

Containers: 28
 Running: 10
 Paused: 0
 Stopped: 18
Images: 8
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 70
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.843 GiB
Name: gb-xenial64-03-May-17-Wed-04-14-15-UTC
ID: EUOZ:VW7M:2IMO:XLQD:ZEZC:MP2Z:BYDG:K7RV:B7WR:NEJL:NN5M:JUQR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Within Virtualbox

**Comment by jerishsd** [comment]
Trying after setting export LC_ALL="en_US.UTF-8" ...

**Comment by jerishsd** [comment]
Works after the export.   Is this an issue, or can be closed ? Will wait for a feedback before closing it ...

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
