### ISSUE TITLE
docker service stats 

### ISSUE THREAD

**Issue by cristhianbicca** [moby/moby#33024]
Anyone know if there is anything being done to query the statistics of a service?

So do we have the docker stats container today?

**Comment by vovimayhem** [comment]
Something about the metrics stuff, maybe?

**Comment by thaJeztah** [comment]
The `docker stats` functionality (as-is) won't be ported to services; work is still in progress on adding more metrics, and eventually using those to drive `docker stats` (or equivalent); also see https://github.com/moby/moby/issues/27307

**Comment by thaJeztah** [comment]
Let me close this issue in favour of https://github.com/moby/moby/issues/27307, which is the discussion on using prometheus metrics for this
