### ISSUE TITLE
HEALTHCHECK fails due to "invalid environment"

### ISSUE THREAD

**Issue by bparker98** [moby/moby#33021]
**Description**

In #31491 a change was made to bring environment variables into a HEALTHCHECK. However, proper checking is not done and if you have an environment variable without a value you get the following error:

```
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"invalid environment 'FOOBAR'\"\n"
```

In the file daemon/container.go: (https://github.com/moby/moby/blob/17.04.x/daemon/container.go#L240) there is a call to opts.ValidateEnv() call to ensure that no bad environment variables are passed down to the container. This should be done in daemon/health.go (https://github.com/moby/moby/blob/17.04.x/daemon/health.go#L81) in order to prevent health checks from failing when there is no value for an environment variable.

This is a problem from 17.03.1 onward.

This is preventing us from upgrading to the latest version of docker-ce, and a quick fix would be appreciated!

**Steps to reproduce the issue:**
1. Create an image with this Dockerfile
```
FROM alpine:latest
HEALTHCHECK --interval=5s --timeout=5s --retries=5 CMD /bin/sh -c "sleep 1"
ENTRYPOINT /bin/sh -c "sleep 600"
```
And build it
`docker build -t env_test .`

2. Run the container with the -e parameter

`docker run -e FOOBAR env_test`

3. See that the container never becomes healthy with `docker ps`

**Describe the results you received:**

The container never becomes healthy when viewing it with `docker ps` and the docker logs contain the following lines:
```
May 04 10:50:23 cake dockerd[7933]: time="2017-05-04T10:50:23.949217373-06:00" level=warning msg="Health check for container ce3525412a4a1b31cfb9de8ae8055cb1e9606635f24a6eb0726ec4ece03c3c90 error: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"invalid environment 'FOOBAR'\"\n"
```

**Describe the results you expected:**
The healthcheck would pass and the container would become healthy.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 548
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1354
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ckkq4hik2h150qnxm238w7ik6
 Is Manager: true
 ClusterID: 17gwd1qpd0rtyvdzwbvi810i7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.19.9.98
 Manager Addresses:
  172.19.9.98:2377
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 22.51GiB
Name: cake
ID: A4YB:3DTQ:L64X:TUHB:FZKK:NYL6:YW62:HCEX:SH3S:VKWM:B65H:ZTQ7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04

**Comment by ripcurld0** [comment]
@bparker98 
If I understood correctly even though `FOOBAR` is "invalid environment" it has nothing to do with the health-check command and thus the `HEALTH` status should be `healthy`.

Did I get it right?

**Comment by ripcurld0** [comment]
@bparker98 OK I guess I know how to fix this.
Calling #dibs
