### ISSUE TITLE
Docs: engine API delete unused volumes should not mention `filters`

### ISSUE THREAD

**Issue by londoncalling** [moby/moby#33026]
### Documentation Problem Description

Per @gdevillele , the API reference topic [Delete unused volumes](https://docs.docker.com/engine/api/v1.28/#operation/VolumePrune) mentions a `filters` query parameter, but doesn’t mention any supported argument (because there isn’t any). This doesn’t make sense, we should not mention this “filters” parameter.

### Where Found

[Delete unused volumes](https://docs.docker.com/engine/api/v1.28/#operation/VolumePrune) in the API reference docs. 

### About the docs

Currently, the  API docs source lives here in the `moby/moby` codebase, not in the docs repository https://github.com/docker/docker.github.io. 

@thaJeztah need guidance on how we will deal with the relationship between `moby/moby` and the docs repository going forward. I don't have permissions to assign issues, but I suggest assigning to @mstanleyjones ?

### Reviewers

@gdevillele @johndmulhausen @thaJeztah

**Comment by cpuguy83** [comment]
Yes, it seem this should only be on v1.29 API (17.05).

**Comment by thaJeztah** [comment]
Yup, have two PR's upcoming, hold on

**Comment by thaJeztah** [comment]
@gdevillele opened https://github.com/moby/moby/issues/33028 and https://github.com/moby/moby/issues/33029
