### ISSUE TITLE
Volume owner is reset after changing user id and use "USER" directive

### ISSUE THREAD

**Issue by metal3d** [moby/moby#33027]
**Steps to reproduce the issue:**
1. Create a dockerfile where you create a user with ID 1001, create a directory /opt/vol and set owner to that user, then declare /opt/vol as VOLUME
2. Create a second dockerfile, remove user 1001, recreate one and set its id to 1000, change owner of /opt/vol to that owner.
3. list owner, you'll see 1000:1000 for /opt/vol
3. set "USER 1000" 
4. and list "/opt/vol", the owner is now 1001 instead of 1000

**Describe the results you expected:**

I expect that declared volume should keep correct owner after set USER to a new user.

If I remove the "VOLUME" declaration from the first docker file, owner is correctly set.

Here the 2 dockerfile you can use:

```dockerfile
# baseimage/Dockerfile
FROM alpine

RUN set -xe; \
    adduser -D -u 1001 -g 1001 default; \
    mkdir -p /opt/vol; \
    chown default:default /opt/vol; \
    echo "=== base image before USER directive ===";\
    ls -la /opt

VOLUME /opt/vol
USER default

RUN set -xe; \
    echo "=== base image after USER directive ==="; \
    ls -la /opt
```
I create docker "bug-image-base" like this:

```
docker build -t bug-image-base baseimage
```
I see:

```
Step 1/5 : FROM alpine
 ---> 4a415e366388
Step 2/5 : RUN set -xe;     adduser -D -u 1001 -g 10001 default;     mkdir -p /opt/vol;     chown default:default /opt/vol;     echo "=== base image before USER directive ===";    ls -la /opt
 ---> Running in eef03f12cdd7
+ adduser -D -u 1001 -g 10001 default
+ mkdir -p /opt/vol
+ chown default:default /opt/vol
+ echo === base image before USER directive ===
+ ls -la /opt
=== base image before USER directive ===
total 0
drwxr-xr-x    3 root     root            17 May  4 20:58 .
drwxr-xr-x   19 root     root           217 May  4 20:58 ..
drwxr-xr-x    2 default  default          6 May  4 20:58 vol
 ---> 3a7d6ae536bc
Removing intermediate container eef03f12cdd7
Step 3/5 : VOLUME /opt/vol
 ---> Running in a44b1401e78d
 ---> 2f88a463fdf0
Removing intermediate container a44b1401e78d
Step 4/5 : USER default
 ---> Running in 4bb1458a0c1d
 ---> abc7b2e26e01
Removing intermediate container 4bb1458a0c1d
Step 5/5 : RUN set -xe;     echo "=== base image after USER directive ===";     ls -la /opt
 ---> Running in 9fabbd8cbaa5
+ echo === base image after USER directive ===
=== base image after USER directive ===
+ ls -la /opt
total 4
drwxr-xr-x    3 root     root            17 May  4 20:58 .
drwxr-xr-x   19 root     root           217 May  4 20:58 ..
drwxr-xr-x    2 default  default       4096 May  4 20:58 vol
 ---> a46b40c290a8
Removing intermediate container 9fabbd8cbaa5
Successfully built a46b40c290a8
```

Now, a second dockerfile to override user:

```dockerfile
FROM bug-image-base

USER root
RUN set -xe;\
    deluser default; \
    adduser -D -u 1000 -g 1000 default; \
    chown default:default /opt/vol; \
    echo "=== before USER directive ===";\
    ls -la /opt


USER default

RUN set -xe; \
    echo "=== after USER directive ===";\
    ls -la /opt

```
Build

```
docker build -t bug-image-extended extended/
```

And the error is now visible:

```
Step 1/5 : FROM bug-image-base
 ---> a46b40c290a8
Step 2/5 : USER root
 ---> Using cache
 ---> 8c0c12af103f
Step 3/5 : RUN set -xe;    deluser default;     adduser -D -u 1000 -g 1000 default;     chown default:default /opt/vol;     echo "=== before USER directive ===";    ls -la /opt
 ---> Running in 499c9a23244a
+ deluser default
deluser: can't find default in /etc/group
+ adduser -D -u 1000 -g 1000 default
+ chown default:default /opt/vol
=== before USER directive ===
+ echo === before USER directive ===
+ ls -la /opt
total 4
drwxr-xr-x    3 root     root            17 May  4 20:58 .
drwxr-xr-x   19 root     root           217 May  4 21:00 ..
drwxr-xr-x    2 default  default       4096 May  4 21:00 vol
 ---> 52fed2eacbdd
Removing intermediate container 499c9a23244a
Step 4/5 : USER default
 ---> Running in a65a321eefd8
 ---> 03a8d1ab31a9
Removing intermediate container a65a321eefd8
Step 5/5 : RUN set -xe;     echo "=== after USER directive ===";    ls -la /opt
 ---> Running in b1b3cc094239
=== after USER directive ===
+ echo === after USER directive ===
+ ls -la /opt
total 4
drwxr-xr-x    3 root     root            17 May  4 20:58 .
drwxr-xr-x   19 root     root           217 May  4 21:00 ..
drwxr-xr-x    2 1001     1001          4096 May  4 21:00 vol
 ---> 723c8eab8f92
Removing intermediate container b1b3cc094239
```

You now see that owner is "1001" instead of "1000". 

Try to remove "VOLUME" directive from the first dockerfile, rebuild everything, and /op/vol has now the correct uid "1000:1000" (default:default).

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:06:13 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:06:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 114
 Running: 0
 Paused: 0
 Stopped: 114
Images: 763
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:2-6160467-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 54.34GB
 Data Space Total: 107.4GB
 Data Space Available: 53.04GB
 Metadata Space Used: 72.21MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.075GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.13-200.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.715GiB
Name: iidor.dhcp.lyon.intranet
ID: D7OR:2UCC:U5DS:3D5T:4VRA:QTYW:DS2U:TG7R:Q34R:AEPS:LWYH:YHP4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: metal3d
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.30.0.0/16
 192.168.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 25, x64

**Comment by cpuguy83** [comment]
This is expected based on how the `VOLUME` directive works.
The VOLUME is created at runtime (for each new container in the build).
The ownership will be based on whatever the directory in the image is at the time of volume creation.

Changing properties on a `VOLUME`'d dir during a build is not supported since the dir is being mounted in when the container is started.

Best advice, don't use `VOLUME`, or use it only at the end of a Dockerfile.

**Comment by metal3d** [comment]
I'm sorry but this is not a solution.

The problem is very important and breaks the ability to let developpers working with "volume-from" option. Even if I set VOLUME at the end of the Dockerfile.

For example, here, we're using docker-compose with a dockerfile that extends a base image (php-fpm). To be able to write on /var/www/html, a "user.compose.yml" adds build-args:
- _UID => user id of the developer
- _GID => user gid of the developer

That changes "default" user in the container to set uid and gid. Now, developers can mount "./src" to /var/www/html and write inside. But... There is, for example, a "var" volume in /var/www/html/var that should be persistent. And many more ! (cache, configuration, storage, and so on...)

So it's declared as VOLUME to let a second container, or named volume, to store them. 

That's important to let "VOLUME" instruction to be able to set:
- volume-from without listing the entire volumes to mount
- let our production server scripts to detect that volumes and prepare persistent volumes (and backups) without to write them one by one
- adapt docker command lines without declare volumes to mount one by one

At this time, that breaks the possibility to write on volumes, because the USER with id 1000 **cannot write on volumes**, and it's not acceptable to list the entire volumes one by one in command line or in docker-compose volumes directive.

I don't know where it's documented that the "VOLUME" is expected to be owned by the "base user id", documentation says that VOLUME declares a directory that may be shared to other containers and automatically detected by "volume-from". 

If the containerds that handles the volume cannot give the right to the second to write on, how to do ?

**Comment by metal3d** [comment]
Same problem here: #7198

**Comment by cpuguy83** [comment]
@metal3d The volume will take on the permissions/ownership of the dir in the image (if the volume is empty). You can chown it at runtime.

But effectively any changes you do in a *build* to a directory that has been marked as a `VOLUME` will not be persisted to the image. This is by definition of what a volume is.

**Comment by metal3d** [comment]
I can't change owner at runtime because owner is not set to the final user.
