### ISSUE TITLE
Usability issue with moving from legacy volume plugin to managed volume plugin.

### ISSUE THREAD

**Issue by taherv** [moby/moby#33031]
**Description**

We strive to provide a very user friendly experience to consumers of docker volume plugins. Some work needs to be done when docker users move from a docker legacy plugin to a docker managed volume plugin.
 
**Steps to reproduce the issue:**
1. Create a legacy volume plugin and call is "myplugin"
2. Create a volume "testvolume" using this driver. The command to use is : 
```
docker volume create --driver=myplugin testvolume
```
3. Now install the new managed plugin, give it the same alias as the legacy plugin name
```
docker plugin install myplugin:1.0 --alias myplugin
```
4. Kill the old plugin, and restart docker.
5. List the volume.
```
docker volume ls
```
6. The output now shows that the driver for this volume is "myplugin:latest"

This is a usability issue. It would be nice if the managed plugin name was exactly the same as the alias name ("myplugin") in this example, so that docker users can use "myplugin" as the driver name in their docker commands irrespective of the type of plugin (legacy/managed) in use.

**Comment by taherv** [comment]
@patrick-east

**Comment by thaJeztah** [comment]
Not at my computer right now, but wouldn't the `--alias` option on `docker plugin install` help for doing this? https://github.com/moby/moby/blob/52df69f00d966904ba230dc2e3a0646cc52b7688/docs/reference/commandline/plugin_install.md

/cc @cpuguy83

**Comment by thaJeztah** [comment]
oh, nevermind, I see you're using that already (so far for reading on my phone, lol)

**Comment by cpuguy83** [comment]
Users can still use "myplugin", there is not need to add ":latest"

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
