### ISSUE TITLE
dockerd high cpu, docker ps slow to return, lots of exited containers

### ISSUE THREAD

**Issue by jonchiu** [moby/moby#33036]
**Description**
`docker ps` hangs for a while (30s or longer)

`top` shows `dockerd` cpu usage sustained 150%+

`docker info` shows large number of exited containers.

Bouncing docker seems to fix the issue. Removing exited containers also seems to have fix the issue. Why do large number of exited containers cause high cpu? Is there a way to force garbage collection if it exceeds some max number of exited containers?

Logs show:
```
May 04 23:12:29 ip-172-20-109-75 dockerd[1024]: time="2017-05-04T23:12:29.090640150Z" level=error msg="Handler for GET /v1.24/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
May 04 23:12:29 ip-172-20-109-75 dockerd[1024]: http: multiple response.WriteHeader calls
```

**Steps to reproduce the issue:**
1. Not 100% sure, but it appears that having a large number of exited containers is causing dockerd to act up.

**Describe the results you received:**
The cpu utilization is > 100%, `docker ps` should returns slowly. containers not responsive.

**Describe the results you expected:**
Should have < 10% cpu utilization, `docker ps` should return quickly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 531
 Running: 7
 Paused: 0
 Stopped: 524
Images: 26
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.41-k8s
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.95 GiB
Name: 172-20-109-75
ID: LM5E:OGZ4:AEUL:VT2E:V3RN:4JRH:2VOS:GFN6:T3YC:N75E:MHVT:YYPG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running kubernetes 1.6.2 on AWS.

Stacktrace attached.
[ip-172-20-109-75-dockerd-stacktrace.txt](https://github.com/moby/moby/files/978288/ip-172-20-109-75-dockerd-stacktrace.txt)

**Comment by cpuguy83** [comment]
There doesn't seem to be much out of the ordinary here other than you've got many things waiting on an available thread to actually run.

Something as simple as this is just waiting on CPU:
```
goroutine 628161 [runnable]:
strconv.quoteWith(0xc8222c3180, 0x9b, 0xc823000022, 0x0, 0x0)
/usr/local/go/src/strconv/quote.go:17 +0x7d
strconv.Quote(0xc8222c3180, 0x9b, 0x0, 0x0)
/usr/local/go/src/strconv/quote.go:93 +0x46
fmt.(*fmt).fmt_q(0xc8230c41f8, 0xc8222c3180, 0x9b)
/usr/local/go/src/fmt/format.go:378 +0x174
fmt.(*pp).fmtString(0xc8230c41a0, 0xc8222c3180, 0x9b, 0xc800000071)
/usr/local/go/src/fmt/print.go:527 +0x9e
fmt.(*pp).printArg(0xc8230c41a0, 0x16df8e0, 0xc823212b60, 0x71, 0x0, 0x0)
/usr/local/go/src/fmt/print.go:797 +0xd95
fmt.(*pp).doPrintf(0xc8230c41a0, 0x1ebc450, 0x16, 0xc823406878, 0x1, 0x1)
/usr/local/go/src/fmt/print.go:1238 +0x1dcd
fmt.Sprintf(0x1ebc450, 0x16, 0xc823406878, 0x1, 0x1, 0x0, 0x0)
/usr/local/go/src/fmt/print.go:203 +0x6f
fmt.Errorf(0x1ebc450, 0x16, 0xc823406878, 0x1, 0x1, 0x0, 0x0)
/usr/local/go/src/fmt/print.go:212 +0x65
github.com/docker/docker/image/v1.ValidateID(0xc8222c3180, 0x9b, 0x0, 0x0)
```

And other threads waiting for a lock to release, which is stuck because this thread is waiting on some CPU time:

```
goroutine 628160 [runnable]:
os.fillFileStatFromSys(0xc8230c4340, 0xc82264e120, 0x58)
/usr/local/go/src/os/stat_linux.go:12
os.Stat(0xc82264e120, 0x58, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/os/file_unix.go:173 +0x1af
github.com/docker/docker/daemon/graphdriver/overlay.(*Driver).Get(0xc82000ed70, 0xc8219fe240, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/overlay/overlay.go:332 +0xbd
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).Get(0xc820136140, 0xc8219fe240, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
<autogenerated>:30 +0xa6
github.com/docker/docker/daemon/graphdriver/overlay.(*naiveDiffDriverWithApply).Get(0xc8204a67a0, 0xc8219fe240, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
<autogenerated>:19 +0xa6
github.com/docker/docker/layer.(*referencedRWLayer).Mount(0xc820027910, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/src/docker/.gopath/src/github.com/docker/docker/layer/mounted_layer.go:96 +0x9f
github.com/docker/docker/daemon.(*Daemon).Mount(0xc8204ac000, 0xc8224c3680, 0x0, 0x0)
```

It looks like you are running a list operation with the `size` parameter, which is very expensive (more expensive the more containers you are listing). This could easily be the culprit.


> GET /v1.24/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe

This error is in the logs presumably because someone ran a `docker ps` and then interrupted it.  Since cancellation is not supported on `docker ps` the daemon still attempted to send the response back to the client, and the client was gone (broken pipe).

**Comment by jonchiu** [comment]
Thanks, sounds like we just need to do some GC then? Is there optimization in a more recent release that would make the list operation less expensive?

**Comment by cpuguy83** [comment]
@jonchiu Don't use `--size`
This has to enumerate every container's RW layer to calculate the size.

**Comment by cpuguy83** [comment]
Closing since this ultimately looks like an issue with using `--size` on docker ps with lots of containers.

Feel free to discuss here, or let me know if you think I've come to the wrong conclusion.
Thanks! 🙇

**Comment by jonchiu** [comment]
Thanks @cpuguy83, unfortunately a 3rd party monitoring agent is calling it so we'll have to figure out how to work around this!
