### ISSUE TITLE
About who is the creating container's grpc receiver?

### ISSUE THREAD

**Issue by xiajohnnyxia** [moby/moby#33046]
sry for my ask, It's not a issue.i just sth didn't understand when i was debug the source codes in version 17.05.I want to know which server receives the grpc request. I dont understand the annotation on those codes.I am following the container to create.And the last code as follows:

/vendor/google.golang.org/grpc/call.go

```
stream, err = sendRequest(ctx, cc.dopts.codec, cc.dopts.cp, callHdr, t, args, topts)
		if err != nil {
			if put != nil {
				put()
				put = nil
			}
			// Retry a non-failfast RPC when
			// i) there is a connection error; or
			// ii) the server started to drain before this RPC was initiated.
			if _, ok := err.(transport.ConnectionError); ok || err == transport.ErrStreamDrain {
				if c.failFast {
					return toRPCErr(err)
				}
				continue
			}
			return toRPCErr(err)
		}
		err = recvResponse(cc.dopts, t, &c, stream, reply)

```

which server receives **sendRequest**,and the data i get like this:

```
		args:


method: /types.API/CreateContainer ,
  ,
   args: id:"bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957" 
   bundlePath:"/var/run/docker/libcontainerd/bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957" 
   stdin:"/var/run/docker/libcontainerd/bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957/init-stdin" 
   stdout:"/var/run/docker/libcontainerd/bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957/init-stdout" 
   stderr:"/var/run/docker/libcontainerd/bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957/init-stderr" 
   runtime:"docker-runc" 
   checkpointDir:"/var/lib/docker/containers/bbf7814a380066482e8e90baa326a6307f5299b1045a40768b9ac4088a966957/checkpoints"  
  , 
opts: []
```

but i cant find any using with **/types.API/CreateContainer**.

**Comment by cpuguy83** [comment]
This is going to containerd (github.com/containerd/containerd).

Closing as this isn't really an issue.
Please if you have questions like this hop on the forums or community slack and we can help out there.

**Comment by xiajohnnyxia** [comment]
i have post it in stackoverflow,but less people to answer.so any way to get some help for me thank you.

i find /types.API/CreateContainer. in this file:
/src/github.com/docker/docker/vendor/github.com/docker/containerd/api/grpc/types/api.pb.go

but no usages found in all places.

**Comment by cpuguy83** [comment]
Probably StackOverflow isn't the right place since containerd/docker internals knowledge is fairly niche.
But definitely community slack (dockercommunity.slack.com)

**Comment by xiajohnnyxia** [comment]
I have not  an @docker.com email in this community yet.Can you give me a invitation?

**Comment by cpuguy83** [comment]
https://community.docker.com/registrations/groups/4316 for the registration form.
Sorry if it's a bit much, they want to make sure people signing up are really interested since slack has caps on number of members.

**Comment by xiajohnnyxia** [comment]
I have not  an @docker.com email in this community yet.Can you give me a invitation?

**Comment by xiajohnnyxia** [comment]
i have been sent and is awaiting approval.

**Comment by xiajohnnyxia** [comment]
How long they need to approval or can you tell me the code's specific location?i am waitting for it.

**Comment by cpuguy83** [comment]
I'm sorry I don't really have much insight into the approval, and am not intimately familiar with containerd.

I believe all the containerd interactions that docker does are in `/libcontainerd`.
