### ISSUE TITLE
VOLUME Dockerfile instruction not working for Windows containers

### ISSUE THREAD

**Issue by friism** [moby/moby#33051]
Windows 10 Hyper-V containers, Docker version `17.05.0-ce-rc1`.

```
Step 5/14 : VOLUME d:
 ---> Running in fce33cc98654
 ---> c32627924b6a
Removing intermediate container fce33cc98654
Step 6/14 : RUN New-Item -Path d:\samples\MusicStore -Type Directory
 ---> Running in 57a7cfae129d
Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.
New-Item : Cannot find drive. A drive with the name 'd' does not exist.
```

I'm interested in this to work around the limitation where you can't volume mount a directory on top of an non-empty directory on the c-drive: https://github.com/moby/moby/issues/20127#issuecomment-294392128

cc @jhowardmsft

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft

**Comment by jmlane** [comment]
As a workaround, using the `cmd` shell will show that volume mounted on D: as desired. There's something with Powershell failing to create a PSDrive for any non-system-drive volumes: #35299

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
