### ISSUE TITLE
Can't join nodes to swarm

### ISSUE THREAD

**Issue by lancemind** [moby/moby#33058]
**Description**

I tried to add two more nodes to my cluster today but was unable.  Tailing the logs on the manager I'm seeing repeated errors around signing CSRs, not only for new hosts but existing hosts as well.

Here is the command I used to attempt to join and the error output I received:
docker swarm join --token SWMTKN-1-myswar-token ip-172-31-111-44:2377
Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.

Here is the output from the manager when attempting to join a node:
May  5 21:19:20 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:20.957402483Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=v0fe5c2k12q2xmfrz8w9z8qh9
May  5 21:19:20 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:20.969958967Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=v0fe5c2k12q2xmfrz8w9z8qh9
May  5 21:19:25 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:25.965591070Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=onwc3zuixpoueea867ngmimwp
May  5 21:19:25 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:25.971488348Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=onwc3zuixpoueea867ngmimwp
May  5 21:19:30 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:30.973659274Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=x0oi1gr1l8gbrvuptuk420bfs
May  5 21:19:30 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:30.977000776Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=x0oi1gr1l8gbrvuptuk420bfs
May  5 21:19:40 ip-172-31-111-44 dockerd[23517]: time="2017-05-05T21:19:40.249609898Z" level=error msg="failed to sign CSR" error="no valid signer found" method="(*Server).signNodeCert" module=ca node.id=x0oi1gr1l8gbrvuptuk420bfs

After attempting to join one node, three new nodes now appear in node ls with an unknown state.
root@ip-172-31-111-174:/home/lance# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
80awzbjskvj7u8xwrj0jjgph5     ip-172-31-112-207   Ready               Active              Reachable
80taczhfa2hyfll7px10au0qn     ip-172-31-113-85    Ready               Active
c60gaydy84caqv00f0k7t06z1     ip-172-31-113-146   Ready               Active              Reachable
hk58kc9hu42bnpc6b1r9gkxw1 *   ip-172-31-111-174   Ready               Active              Reachable
ku289nnwy4sajlufqpnalv6jj     ip-172-31-112-5     Ready               Active              Reachable
lgqnkj8ey4mt5d4mugxd6diog     ip-172-31-111-36    Ready               Active
o7g8a9c9klzky6q7oa4po64aw     ip-172-31-111-44    Ready               Active              Leader
onwc3zuixpoueea867ngmimwp                         Unknown             Active
p2wu1tz2pq8zwqqcelc72znmd     ip-172-31-112-14    Ready               Active
qi11kmml51szyshn12zqu55nk     ip-172-31-111-74    Ready               Active
ta54no3rjdanp3sma7lf7xh0e     ip-172-31-113-60    Ready               Active
v0fe5c2k12q2xmfrz8w9z8qh9                         Unknown             Active
x0oi1gr1l8gbrvuptuk420bfs                         Unknown             Active

I've attached logs from two of my managers.

[5-5-dockerd-172-31-111-44.gz](https://github.com/moby/moby/files/980384/5-5-dockerd-172-31-111-44.gz)
[5-5-dockerd-172-31-111-174.gz](https://github.com/moby/moby/files/980383/5-5-dockerd-172-31-111-174.gz)

**Steps to reproduce the issue:**
1. docker swarm join --token mytoken host:2377
2. Wait for timeout
3.

**Describe the results you received:**
Timeout on node that's trying to join, CSR errors in manager logs.

**Describe the results you expected:**
New nodes in my cluster

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:57:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:57:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:57:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 19:57:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@ip-172-31-111-44:/home/lance# docker info
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 22
Server Version: 17.05.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: o7g8a9c9klzky6q7oa4po64aw
 Is Manager: true
 ClusterID: cqu8g3e6njaf7tb3etjdj1ebs
 Managers: 5
 Nodes: 13
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.111.44
 Manager Addresses:
  172.31.111.174:2377
  172.31.111.44:2377
  172.31.112.207:2377
  172.31.112.5:2377
  172.31.113.146:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795GiB
Name: ip-172-31-111-44
ID: XZU5:FVPB:JWCA:RATJ:WXBP:QSZM:GB5M:UDH4:6FKC:XR5Y:EAM4:HINZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: userminddeployer
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Nodes are all EC2 instances spun up via autoscaling groups.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
