### ISSUE TITLE
Metrics namespacing

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#33056]
This is a continuation of the discussion from #29554 

Some time was spent when metrics were first implemented on namespacing for metrics, including some helpers for consistent naming across projects (github.com/docker/go-metrics).

We now need to make sure the naming we have selected works well.
Ideally this works well for both the engine/daemon monolith, as well as moby (monolith broken into microservices).

Note that these metrics should be treated like any other API and any change to an existing metric would be considered a breaking API change once metrics are no longer experimental.

ping @stevvooe @crosbymichael @rogaha @alfred-landrum

**Comment by bsousaa** [comment]
@cpuguy83 do we need to keep this open as a tracking issue?
