### ISSUE TITLE
docker build shows a warning for predefined ARG variables

### ISSUE THREAD

**Issue by jeverling** [moby/moby#33067]
**Description**

I get a warning like `[Warning] One or more build-args [https_proxy] were not consumed` for variables that are predefined according to https://docs.docker.com/engine/reference/builder/#arg

**Steps to reproduce the issue:**
1. Create a minimal Dockerfile like this:

```
FROM busybox
ARG http_proxy
RUN env
```

2. Build this Dockerfile, passing `http_proxy` and `https_proxy`:

```
docker build --build-arg http_proxy=http_proxy --build-arg https_proxy=https_proxy -t deleteme .
```

**Describe the results you received:**

I got a warning

```
    [Warning] One or more build-args [https_proxy] were not consumed
```

despite `https_proxy` being one of the predefined ARG variables, and it being actually set in the build env. 

**Describe the results you expected:**

I don't expect to see a warning for predefined ARG variables

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by dnephin** [comment]
I think this broke here: https://github.com/moby/moby/pull/31257/files#diff-8145809cef82b62e31a5fce12cd7240aR333.

I'll prepare a fix tomorrow
