### ISSUE TITLE
Question, docker exec on swarm mode

### ISSUE THREAD

**Issue by guillemsola** [moby/moby#33066]
It seems than with newer API (1.27) the ContainerID is not available anymore as suggested by https://github.com/moby/moby/issues/25871 

```docker inspect -f "{{.Status.ContainerStatus.ContainerID}}" <task_id>```

Therefore is not possible to exec, for instance a bash session to a container anymore?

**Comment by guillemsola** [comment]
To rationalize a bit more the use case I understand that with Docker Swarm mode everything has this meaning of service with the idea of equal clients.

I still see use cases where a hybrid scenario may be required as not all the applications are ready for this.

For instance I have a mix of node API that I can easily scale in a swarm but to stress them I need to use JMeter where the master needs to explicitly know the available workers by IP. Here common use case is to execute the master passing as parameter each worker node.

Formerly to achieve this with docker, ssh into master container to launch the test was a common case.

So IMO the Swarm Mode is still too restrictive and we won't be able to maintain a single docker infrastructure, which makes everything more complex. The old swarm was not cool in the sense of service but allowed more flexibility in cases where the docker desired state still cannot fulfill all the requirements.

**Comment by cpuguy83** [comment]
On 17.05:

```
$ docker inspect -f "{{.Status.ContainerStatus.ContainerID}}" o76c2rad8ozp                                                 )git:(move_the_monolith
270c95d7723a747aa6e09300369b5f784489c26015f7a053fb7f95854e6f2f13
```
---

By the way, I think there is likely a better way to handle what you want.
Instead you can create a separate service attached to the same network that runs your jmeter stuff. It can lookup the IP of individual tasks with `tasks.<service_name>`

**Comment by guillemsola** [comment]
Very good point @cpuguy83 !!!

I'm struggling with getting from the master the ```task.<service_name>``` for all the instances of service

I have realised that my problem is that the container is gone so that is not possible to do an exec on an stopped container

```
ID                  NAME                MODE                REPLICAS            IMAGE                                    PORTS
agc60a1oev8s        myjm_master         replicated          0/1                 ajeetraina/apache-jmeter-master:latest   *:0->60000/tcp
```
So it makes completely sense to split the service in two pieces and start the master container once I know the IP of slaves 

thanks!

**Comment by cpuguy83** [comment]
Are we good to close this?

**Comment by guillemsola** [comment]
Not sure if this is the best way to get the container names but it seems I can try with it

```docker inspect -f 'myjm_slave.{{.NodeID}}.{{.ID}}' $(docker service ps myjm_slave -q)```

In any way we are good to close this 😄

**Comment by cpuguy83** [comment]
Thanks!
