### ISSUE TITLE
W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/wily/stable/binary-amd64/Packages  HttpError404

### ISSUE THREAD

**Issue by xiaocairush** [moby/moby#33064]
**Description**

**Steps to reproduce the issue:**
```
sudo apt-get remove docker docker-engine
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
```

**Describe the results you received:**
W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/wily/stable/binary-amd64/Packages  HttpError404

**Describe the results you expected:**
```sudo apt-get update``` should succeed to fetch https://download.docker.com/linux/ubuntu/dists/wily/stable/binary-amd64/Packages

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Comment by cpuguy83** [comment]
Wily went EOL in July 2016. As such we don't provide new packages for it (and haven't since it's EOL).

Sorry. 😇
