### ISSUE TITLE
docker stack deploy "loses" volumes

### ISSUE THREAD

**Issue by jamshid** [moby/moby#33080]
**Description**

It seems `volumes` on a service are not preserved across runs of `docker stack deploy`s? Deploying a yml like this results in lost data because volumes are not necessarily preserved when you scale the service then deploy an updated image.
```
  elasticsearch:
    volumes:
      - "/usr/share/elasticsearch/data"
    image: myesimage
    ports:
      - 9200:9200
```
This is a *major* difference from `docker-compose` behavior and should be mentioned in https://docs.docker.com/compose/compose-file/#not-supported-for-docker-stack-deploy.

**Steps to reproduce the issue:**

1. `docker stack deploy -c docker-compose.yml esstack`
2. `docker service scale esstack_elasticsearch=3`
3. Rebuild image "myesimage" and run step 1 command -- you cluster will be red instead of green.

**Describe the results you received:**

The service is restarted with containers (tasks?) missing data (fresh volumes).

**Describe the results you expected:**

Services should be restarted as containers on specific nodes so that volumes are never lost. 
If another volume driver needs to be specific when using Swarm (https://github.com/CWSpear/local-persist ?), please document.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Just upgraded client and server hoping it would fix this but it does not.
```
17.05.0-ce
```

**Output of `docker info`:**
Dropped down to a single-node docker swarm for easier testing:
```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 100
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ost7tjc37b0bnhjlhappdoiqp
 Is Manager: false
 Node Address: 192.168.2.62
 Manager Addresses:
  192.168.2.61:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: 62
ID: 6LMS:NXVP:QWWT:AOPJ:DCIE:YMD4:VCJA:6V7M:IA2V:T3NE:DYY3:QRHZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 192.168.2.61:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Yes, this is expected. Volumes here are really "mounts", and you haven't tied to the mount to a particular volume.

**Comment by thaJeztah** [comment]
The reason this happens is that you don't specify a _source_ for the volume, only the "target" inside the container. As a result, an anonymous volume is created for each task backing the service. Anonymous volumes are not persisted after the container it is attached to is removed.

Also keep in mind that when using services, that the tasks (containers) backing the service can be deployed on _any_ node in the swarm, which may be a different node each time the service is updated.

If you want your data to persist, use a _named_ volume, and make sure to use a volume driver that is multi-host aware, so that the data can be accessed from any node or, alternatively, set constraints on the service so that its tasks are deployed on a node that has the volume present.

**Comment by thaJeztah** [comment]
I don't think there's a bug at hand here, so I'll close the issue, but feel free to continue the conversation 👍

**Comment by jamshid** [comment]
Thanks. So I need to use one of these (legacy?!) plugins, that is swarm/cluster/multi-node aware?

https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

I think https://github.com/moby/moby/issues/31152#issuecomment-280857744 describes what I want (per-replica persistent volumes?), but I don't understand if it's possible (since 1.13?) or still waiting on features.

If there is an easy, batteries-included way to do what I want, _please_ point me to docs or a blog. If not, please let me know before I go down a volume driver rabbit hole.

I don't think "named" volumes help, since I want each replica of the service to have their own, not use a single shared volume.

Anyway, this seems like a significant omission from https://docs.docker.com/compose/compose-file/#not-supported-for-docker-stack-deploy so I'll file a docs bug.
