### ISSUE TITLE
Migrating ASP.NET MVC to Windows Container, can't get IIS to push detailed errors. Only getting 500 server errors.

### ISSUE THREAD

**Issue by KevinVording** [moby/moby#33082]
**Description**
I'm trying to get a few of our older projects running in Windows Containers as part of my internship. I've now stumbled upon an issue I haven't been able to solve for 2 weeks. I have a project in a repository that's a replica of a large site that's running in production. The code will run fine when running in debug mode in Visual Studio. However if I publish the site and build an image from it, the container from said image will only give me a 500 response when accessing its ip in a (any) browser, Internal Server Error, with no additional information. 

Is there a way to get IIS in a container to output detailed errors? My webconfig containers both customErrors=Off and errorMode=Detailed.

**Steps to reproduce the issue:**
Im currently only trying to get proper errors so I can see the root of the problem.
1. Any MVC project perhaps with an edited webconfig to purposely get a 500 error.
2. 
3. 

**Describe the results you received:**
500 - Internal server error.

**Describe the results you expected:**
The websites home page.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried this with both the Docker Tools for Visual Studio and with creating my own Dockerfile and creating everything from the command line. Same output.

**Dockerfile:**
```
FROM microsoft/aspnet

COPY PublishOutput/ /inetpub/wwwroot
```

I've also tried the microsoft/iis image, same result. 

I've tried checking container logs, no information given.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.89 GiB
Name: 2TM8202
ID: FW6Z:J7SM:XONM:IGYL:CTQM:KGCX:QRPZ:V7HB:6YSY:ZY47:QM7U:VMP7
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2017-05-08T08:51:35.644585+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Just a local machine, running the app in Visual Studio 2017.

**Comment by cpuguy83** [comment]
Hi, thanks for reporting.
This does not seem like a Docker issue.
Can you report to Microsoft on https://github.com/microsoft/iis-docker/issues ?

Thanks!
