### ISSUE TITLE
Memberlist version incompatibility between 17.06(master) and 17.05

### ISSUE THREAD

**Issue by mavenugo** [moby/moby#33091]
https://github.com/moby/moby/pull/32902 brought in the memberlist update to `0.1.0` for 17.06 (master) which has updated the ProtocolVersionMax to 5.
This issue is opened to make sure libnetwork sets the correct protocol version while initializing the memberlist in networkdb.

**Comment by mavenugo** [comment]
ping @fcrisciani

**Comment by mlaventure** [comment]
Closing via #1747

**Comment by mlaventure** [comment]
Oups, too early :)
