### ISSUE TITLE
Healthcheck consumes a lot of CPU with Windows Server containers

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#33096]
Hello,

I created a Docker image with a simple Python Flask web application which can response to http-request with configurable sleep time.
```
def hello_world():
    out = strftime("%Y-%m-%d %H:%M:%S", gmtime())
    out = out + '; Flask Dockerized; Sleeping: ' + os.environ['WEB_SLEEP_TIME'] + ' second(s) ... '

    sleep(float(os.environ['WEB_SLEEP_TIME']))
    
    out = out + strftime("%Y-%m-%d %H:%M:%S", gmtime())

    return out
```

This image also has a healtcheck with interval/timeout and retries attributes.

```
HEALTHCHECK --interval=30s --timeout=6s --retries=3 CMD powershell.exe -executionpolicy bypass -nologo -noprofile c:\app\healthcheck.ps1
```

where `healthcheck.ps1` is a check of http request 

```
try {
    curl http://localhost:5000/ -UseBasicParsing
    Write-Output 0
}
catch {
    Write-Output 1
}
```

I pushed this image to `georgyturevich/win_healthcheck:healthcheck_win_flask`. Full code you can find there https://github.com/georgyturevich/win_healthcheck/tree/master/image

I tried to perform three experiments:
1. Run 120 containers without healtch (--no-healthcheck)

```
1..120 | foreach {
    echo "$(date): Starting $_";
    docker run -d -l "win_healthcheck=true" -e "WEB_SLEEP_TIME=0" --no-healthcheck georgyturevich/win_healthcheck:healthcheck_win_flask
    echo "$(date): Started $_. Sleeping ...";
}
```

2. Run 120 containers with enabled healtcheck timeout (8 sec) lower then web page sleep time (10 seconds). So all containers were unhealthy and Docker Daemon tried to exec health check 1 times each 30 seconds.

```
1..120 | foreach {
    echo "$(date): Starting $_";
    docker run -d -l "win_healthcheck=true" -e "WEB_SLEEP_TIME=10" --health-timeout 8s georgyturevich/win_healthcheck:healthcheck_win_flask
    echo "$(date): Started $_. Sleeping ...";
}
```

3. Run 120 containers with long healtcheck timeout (60 sec). So all containers were healthy and Docker Daemon tried to exec health check only 1 times each 60 seconds.
```
1..120 | foreach {
    echo "$(date): Starting $_";
    docker run -d -l "win_healthcheck=true" -e "WEB_SLEEP_TIME=0" --health-timeout 60s --health-interval 60s georgyturevich/win_healthcheck:healthcheck_win_flask
    echo "$(date): Started $_. Sleeping ...";
}
```

After all containers were started I got following constant CPU consumption:
1. Without healtcheck: 2-7% (avg 3.68%)
2. Unhealthy case with short health check timeout: 23-100% (avg ~ 87%)
3. Healthy case with long timeout and interval: 23-96% (avg ~ 56%)

This is a server with 64 virtual CPU cores and 256Gb of Memory. I would say that the load from 2nd and 3d cases is very small, and must not create such big CPU consumption.

Thanks!

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 142
 Running: 120
 Paused: 0
 Stopped: 22
Images: 875
Server Version: 17.05.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 64
Total Memory: 256GiB
Name: EC2..skiped..C87
ID: VJVM:..skiped..:G6EE:UXQT
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 1249
 System Time: 2017-05-08T21:40:06.265291Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is AWS m4.16xlarge instance

**Comment by friism** [comment]
cc @jhowardmsft @PatrickLang

**Comment by georgyturevich** [comment]
The same behaviour I see inside Azure instance (Standard DS3 v2 Promo (4 cores, 14 GB memory)) with last Windows updates. 20 containers run by 2nd way are consuming 100% CPU of the instance

**Comment by artisticcheese** [comment]
Заебаться, открыто с Мая месяца и они только проснулись

**Comment by chrisvanderpennen** [comment]
Try running `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ngen.exe update` in one of the affected containers and see if it resolves the issue.  Unfortunately this doesn't help nanoserver containers, which seem to also have the same cpu spike launching PowerShell but no way to precompile it.

I also have no idea if that's safe to run as a build step, unfortunately.  I've got 20 odd images being built from a mix of nanoserver and server core, and I'm probably going to wind up copying curl into all of them to do basic http health checks.

**Comment by artisticcheese** [comment]
I don't think it has anything to do with precompile since issue is not evident in manually running the same `HEALTHCHECK` directive directly on console when logged into container

**Comment by artisticcheese** [comment]
I completely removed all the code from HEALTHECK and all I do is return 0 and 100% CPU still evident. Looks like just launching powershell on it's own causing 100% CPU and not the actual code.

**Comment by chrisvanderpennen** [comment]
Are you using PowerShell or CMD as your shell when you try it
interactively?  If you're using PowerShell you've already paid the startup
cost launching the shell with docker exec, and executing the script is
basically free in comparison.

**Comment by artisticcheese** [comment]
You are right, it's price of instantiating powershell which causing slowdown. Issue with high CPU utilization is result of new powershell instance being instantiate and not actual script itself. This is obviously a big issue since it prevents effectively use of powershell inside `HEALTHCHECK` or I would say any interpretive language.

**Comment by chrisvanderpennen** [comment]
When I was digging into this for https://github.com/Microsoft/dotnet-framework-docker/issues/25 I found running `ngen` in the container dropped the PowerShell launch cost down to about 250ms or so and apparently mostly I/O rather than CPU.  Like I said above, I just don't know if it's safe to bake precompiled .NET assemblies into a container image or if I'm going to wind up baking extended instruction sets that may not exist on the hosts running the images.

**Comment by artisticcheese** [comment]
I'm not fully understanding how .NET compilation works, but would not compiled assemblies be cached on file system for subsequent reuse after initial instantiation?

**Comment by artisticcheese** [comment]
I run "ngen.exe update" and it did not do anything. It does produce following ouput on repeated runs, not sure what that means and wether that's what's prevents powershell high CPU utilization

```
Failed to load the runtime. (Exception from HRESULT: 0x80131700). Assembly Microsoft.PowerShell.Commands.Management, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=31bf3856ad364e35, processorArchitec
ture=msil requires version v2.0.50727 of the runtime to run.
```

**Comment by chrisvanderpennen** [comment]
Ah.  Sorry I forgot it has a `/verbose` argument.  Doing that spits out about 900kb of logs to the effect of "hey I just compiled native images for the entire .net framework".

**Comment by artisticcheese** [comment]
This did not fix issue for me though

**Comment by richlander** [comment]
FYI: I am looking into fixing this.

**Comment by artisticcheese** [comment]
What this fix will be shipped as part of? Will all windows based images have this fixed (like IIS image for example)?

**Comment by richlander** [comment]
microsoft/dotnet-framework was fixed today. microsoft/aspnet and microsoft/wcf both FROM this image (directly or indirectly).

microsoft/windowsservercore was not yet fixed. That is still coming. microsoft/IIS FROMs this image.

As a stop-gap, you can apply the same fix into your own images that I put into microsoft/dotnet-framework.

Major apologies for this.

**Comment by georgyturevich** [comment]
@richlander Hi Rich,

Thank for the patch! I have testes my test cases described in the issue and CPU graphs look a lot better. They just have short CPU spikes to 100% but no long high CPU average load as was before.

Could you clarify a bit. If I want to fix in my custom image based on `windowsservercore` core, am I correct that I need to install .NET framework and run `ngen update`

**Comment by richlander** [comment]
@georgyturevich See: https://github.com/dotnet/announcements/issues/33

**Comment by artisticcheese** [comment]
Was latest servercoreimage fixed?

**Comment by artisticcheese** [comment]
This needs to be closed as fixed. I bite a bullet and moved to .NET image instead of building my images from servercore and CPU utilization graph of my container is below after the fix and before the fix. Night and day obviously.
![image](https://user-images.githubusercontent.com/13176884/34222730-232ef724-e582-11e7-8fac-34dabf2810c6.png)

**Comment by thaJeztah** [comment]
Thanks @artisticcheese let me go ahead and close this issue.

@georgyturevich feel free to comment after I closed if there's still an issue outstanding :+1:

**Comment by artisticcheese** [comment]
Issue seems to be back with 2019 images

![image](https://user-images.githubusercontent.com/13176884/50579089-554a3f80-0e07-11e9-91a1-c8b083889342.png)
