### ISSUE TITLE
Any simple way of creating a bridged network interface?

### ISSUE THREAD

**Issue by ericcurtin** [moby/moby#33104]
**Description**

In my use case, I have to use a specific port on each of my containers
because of firewall issues. In VirtualBox if I wanted a unique IP
address for each of my VMs I would create a bridged network interface
on each one, it would get a dhcp ip and that would be it. Any simple
way of doing something very similar using docker containers? I am
running Ubuntu 14.04 aarch64 containers on a openSUSE 42.2 aarch64
host.

**Describe the results you expected:**

I expect there to be a simple way of running multiple docker
containers, each getting their own dhcp ip address

**Output of `docker version`:**

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.1
 Git commit:   78d1802
 Built:        Mon Jan 23 12:39:41 2017
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.1
 Git commit:   78d1802
 Built:        Mon Jan 23 12:39:41 2017
 OS/Arch:      linux/arm64

**Output of `docker info`:**

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-179:2-257661-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 921.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 10.72 GB
 Metadata Space Used: 1.688 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2015-05-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.49-16-default
Operating System: openSUSE Leap 42.2
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 785.2 MiB
Name: linux.suse
ID: 2REX:PUEF:EJ46:AGRK:LLFI:DKI7:RPUC:L3MR:AU2Y:DCI3:MXY7:LCFI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://web-proxy.corp.hp.com:8080/
Username: curtine
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Host is raspberry pi 3.

**Comment by cpuguy83** [comment]
DHCP is not very simple.

However, every container that Docker creates (unless otherwise specified) will get a bridge device and assigned an IP address from a pool managed by Docker.

**Comment by ericcurtin** [comment]
Yeah, I'm aware of the 172.17.0.x addresses docker assigns to the containers. I need an externally accessible addresses on each container so I can use port x on every container, due to a firewall condition that is out of my control. Maybe this is a use case for VMs over containers as it will just work, I can use x86_64 over aarch64, we support both.

**Comment by cpuguy83** [comment]
@ericcurtin  Anything is externally available as long as it's routable (hint: setup static routes and this becomes really simple).
In addition you can use `-p` to forward ports from the VM IP to the container IP.
These are the simplest options. 

Additionally you can use macvlan to give an IP on the host network to a container, but I don't think DHCP is supported in this case.

**Comment by ericcurtin** [comment]
I'm stuck with dhcp I'm afraid, I am using port forwarding already on a single container, but that's the issue I can only port forward port x once. I have to use port x on the host I cannot use a different port. Corporate IT policies have me restricted to using just port x.

**Comment by thaJeztah** [comment]
IIRC someone tried implementing a DHCP IPAM plugin @erikh didn't you try to do so?

**Comment by ericcurtin** [comment]
This looks like what you are talking about @thaJeztah:

https://github.com/erikh/dhcpd

I see this repo hasn't been updated in quite a while...

@erikh should I respect your warning in the repo?

`toolkit to play with docker and DHCP. don't use this unless you know about it already.`

Or do I risk exploding/setting on fire this $60 raspberry pi kit I am using! :)

**Comment by erikh** [comment]
Haha. It was an experiment. I'm on vacation this week, but I could fix it
late next week if you want.

**Comment by ericcurtin** [comment]
@erikh that would be great! I'm sure many would be interested in this. It would definitely solve this problem for me. I might play around with it myself, but I've never written a line of golang so may not get very far. 

Considering there is just 200 lines or so of code in this, maybe it's the perfect opportunity to get my hands dirty and learn some golang.

**Comment by erikh** [comment]
Works for me! Please feel free to email me at my first name @ my last name
.org if you have any questions!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
