### ISSUE TITLE
cpio: cap_set_file issue on rsh install on centos 7 docker

### ISSUE THREAD

**Issue by ivinpolosony** [moby/moby#33106]
**Description**

**Steps to reproduce the issue:**
1. docker run -it centos bash 
2. yum install rsh 

**Describe the results you received:**
rsh-0.17-76.el7_1.1.x86_64.rpm                                                                                                                                                              |  54 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : rsh-0.17-76.el7_1.1.x86_64                                                                                                                                                                      1/1 
Error unpacking rpm package rsh-0.17-76.el7_1.1.x86_64
error: unpacking of archive failed on file /usr/bin/rcp;5911a4d9: cpio: cap_set_file

**Describe the results you expected:**
Package not installed. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 28
 Running: 4
 Paused: 0
 Stopped: 24
Images: 69
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 167
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: z0rfzkl59ruzbmgwl4wy6628t
 Is Manager: false
 Node Address: 192.158.77.15
 Manager Addresses:
  192.158.76.215:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 63.05GiB
Name: dub-vcd-vms197
ID: WDGD:YHRX:NJDF:7AKG:WNDL:OCX4:DQ5Z:HBTQ:ONWD:PLHE:UZPK:XMQO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 dub-vcd-vms166:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
