### ISSUE TITLE
Builder skips changed files on COPY or ADD and uses cache

### ISSUE THREAD

**Issue by plebowski** [moby/moby#33107]
**DESCRIPTION**
Builder skips changed files on COPY or ADD unless adding a new file or changing dockerfile

**Steps to reproduce the issue:**
1. Install docker on Windows Server 2016
2. Run a build with dockerfile copying/adding a directory to a container
3. Change something in one of the files in the source folder
4. Run the same build again and notice docker used cache not including changes made in step 3

**Describe the results you received:**
Docker skipped changes in the source folder and used cached resources.

**Describe the results you expected:**
Expected docker not to use cache on the copy/add step when changes were made in sources folder.

**Additional information you deem important (e.g. issue happens only occasionally):**
Originaly i stumbled upon this problem while testing VSTS integration with docker. When i had whole environment ready (agent with docker, docker host and a repository) i noticed that application that i deployed on Windows Server 2016 didn't want to work. When i checked everything i noticed that no changes are being made on neext builds after the initial one UNLESS i change something in the dockerfile (like changing copy to add) or add new files to the sources (then the build noticed changes and properly rebuilded the step). If you look at vsts docker page in the comments on 3/29/2017 theres a user who has exact same issue https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.docker.

Another weird thing worth mentioning is that originaly this error occured to me at version 1.12 beta which came from Windows Server role installation. When i updated to current version 17.03.1 nothing has changed.

**Output of `docker version`:**

```
Docker version 17.03.1-ee-3, build 3fcee33
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 23
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: *******
ID: QKZX:YNWS:EK57:L2W3:QXK5:6K2E:LWMB:RPVH:SLD6:AARX:WA55:M6LP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: *********
Registry: https://**************
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016

**Comment by thaJeztah** [comment]
Can you provide an example Dockerfile to reproduce the issue? Is the Dockerfile (or the base image you're using) using a `VOLUME`?

**Comment by plebowski** [comment]
No, im not using volume. The dockerfile is very simple and i pasted it below :
```
FROM microsoft/windowsservercore 

# Install ASP.NET
RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45

EXPOSE 8081
COPY /source c:/site/
RUN powershell New-Website -Name 'site' \
                -Port 8081 -PhysicalPath 'c:\site'  \
                -ApplicationPool '.NET v4.5'
```

**Comment by thaJeztah** [comment]
ping @friism @johnstep PTAL

**Comment by friism** [comment]
I cannot reproduce this. @plebowski can you reproduce the problem on your local machine? If not, please open an issue with the VSTS people.

```
C:\code\repros\build-cache
λ  cat .\source\test.txt
foo bar
C:\code\repros\build-cache
λ  docker build -t test .
Sending build context to Docker daemon  3.584kB
Step 1/5 : FROM microsoft/windowsservercore
 ---> 4f222178c921
Step 2/5 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 46b18ae068eb
Step 3/5 : RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45
 ---> Using cache
 ---> e9ea0943e9f8
Step 4/5 : COPY /source c:/site/
 ---> Using cache
 ---> 40f54ba4f034
Step 5/5 : RUN powershell New-Website -Name 'site'                -Port 8081 -PhysicalPath 'c:\site'                 -ApplicationPool '.NET v4.5'
 ---> Using cache
 ---> 197bc63f8a1b
Successfully built 197bc63f8a1b
Successfully tagged test:latest
C:\code\repros\build-cache
λ  add-content .\source\test.txt "kapow"
C:\code\repros\build-cache
λ  docker build -t test .
Sending build context to Docker daemon  3.584kB
Step 1/5 : FROM microsoft/windowsservercore
 ---> 4f222178c921
Step 2/5 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 46b18ae068eb
Step 3/5 : RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45
 ---> Using cache
 ---> e9ea0943e9f8
Step 4/5 : COPY /source c:/site/
 ---> d7c87f01a64a
Removing intermediate container b3a12ffbee9a
Step 5/5 : RUN powershell New-Website -Name 'site'                -Port 8081 -PhysicalPath 'c:\site'                 -ApplicationPool '.NET v4.5'
 ---> Running in 748a1821e3f5

Name             ID   State      Physical Path                  Bindings
----             --   -----      -------------                  --------
site             8374 Started    c:\site                        http *:8081:
                 4792
                 1


 ---> 6ccedc9aeda1
Removing intermediate container 748a1821e3f5
Successfully built 6ccedc9aeda1
Successfully tagged test:latest
```

**Comment by plebowski** [comment]
Well its not the VSTS issue because as I mentioned I tried to do the same as you did and i got the cached results : 

```
C:\source>docker build -f C:/source/dockerfile C:\source
Sending build context to Docker daemon 1.901 MB
Step 1/8 : FROM microsoft/windowsservercore
 ---> 4d83c32ad497
Step 2/8 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 94cfcd0f5030
Step 3/8 : RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45
 ---> Using cache
 ---> 4a05fc03fb1b
Step 4/8 : EXPOSE 8081
 ---> Using cache
 ---> 0fcad666e487
Step 5/8 : RUN powershell Remove-Website -Name 'Default Web Site'
 ---> Using cache
 ---> e3c65b6267ac
Step 6/8 : RUN powershell md c:\
 ---> Using cache
 ---> 43606b150e95
Step 7/8 : RUN powershell New-Website -Name 'app'                 -Port 8081 -PhysicalPath 'c:\app'                  -ApplicationPool '.NET v4.5'
 ---> Using cache
 ---> ecf12893d49b
Step 8/8 : COPY app c:\app
 ---> Using cache
 ---> 0576d77de17a
Successfully built 0576d77de17a

PS C:\source> add-content ./app/somefile.aspx.cs "TEST"
PS C:\source> exit

C:\source>docker build -f C:/source/dockerfile C:\source
Sending build context to Docker daemon 1.901 MB
Step 1/8 : FROM microsoft/windowsservercore
 ---> 4d83c32ad497
Step 2/8 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 94cfcd0f5030
Step 3/8 : RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45
 ---> Using cache
 ---> 4a05fc03fb1b
Step 4/8 : EXPOSE 8081
 ---> Using cache
 ---> 0fcad666e487
Step 5/8 : RUN powershell Remove-Website -Name 'Default Web Site'
 ---> Using cache
 ---> e3c65b6267ac
Step 6/8 : RUN powershell md c:\app
 ---> Using cache
 ---> 43606b150e95
Step 7/8 : RUN powershell New-Website -Name 'app'                 -Port 8081 -PhysicalPath 'c:\app'                  -ApplicationPool '.NET v4.5'
 ---> Using cache
 ---> ecf12893d49b
Step 8/8 : COPY app c:\app
 ---> Using cache
 ---> 0576d77de17a
Successfully built 0576d77de17a
```
``

Event when i try to alter the sources from add-content and run the build again my docker for some reason is not picking up the changes. Maybe this is OS related or something? As i mentioned im trying to do this on Windows Server 2016.

**Comment by plebowski** [comment]
Okay i think i might figured it out. Error was that my source folder was called APP (uppercased) and i used app (lowercased) in my dockerfile. After i changed that to uppercased APP docker engine started to notice my changes and not using cache after change as intended. I think there should be an error message for that because it should either register the name correctly or not. What do you think?

**Comment by thaJeztah** [comment]
ping @tonistiigi @jhowardmsft PTAL ^^

**Comment by simonferquel** [comment]
@thaJeztah I can have a look at it on my next "builder" day (Thursday).

**Comment by tonistiigi** [comment]
It should be this case https://github.com/moby/moby/blob/master/builder/remotecontext/tarsum.go#L115 . I added the comment last time I changed it because not handling that error seemed weird to me but I didn't know if it would break something. I think we should return error there, and maybe for the windows case normalize the casing.

**Comment by tonistiigi** [comment]
https://github.com/moby/moby/commit/e0ef11a4c2c6789e08b61df082b5b9aa70898e7a#diff-c3f8345b44d40e8f17b80bcbce453719R61 @tiborvass do you remember any other case than empty path that can be just detected with string comparison?

**Comment by tiborvass** [comment]
@tonistiigi sorry just saw this. Off the top of my head, no I don't remember. But after checking the code, it seems like it would be the case again if the normalized cleanPath matches no any entry's `path.Clean`'d name in the tarsum. cleanPath normalization is done with `filepath.Clean("/"+path)` + followsymlinks. So what if path starts with `../` ? Or something funky with symlinks, but sorry I don't have a specific answer :S

**Comment by thaJeztah** [comment]
What's the status on this one? Is someone looking into this?

**Comment by pbering** [comment]
Anyone has a workaround for this?

**Comment by tallandtree** [comment]
I've seen this sometimes as well, but it's difficult to reproduce. I made a small change to one of the files and the image is not being rebuilt (only using cache). Then I made another small change to the same file and the image is being rebuilt from the COPY step on. Sorry I can't produce something reproducible, but it did happen.

**Comment by tonistiigi** [comment]
Can anyone confirm if this is still an issue in master, with the fix for https://github.com/moby/moby/issues/34260 ?

**Comment by jhowardmsft** [comment]
This seems OK on master (c307e0ce49d63d1b1f479560955dca3956f005ec). My local "APP" directory is upper-cased, whereas in the dockerfile (reused essentially the example above)

First using a cached build, no changes on the host:
```
PS E:\docker\build\33107> docker build .
Sending build context to Docker daemon  4.608kB
Step 1/9 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/9 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 5f198bff6181
Step 3/9 : EXPOSE 8081
 ---> Using cache
 ---> 13136ee1ffd5
Step 4/9 : RUN powershell Remove-Website -Name 'Default Web Site'
 ---> Using cache
 ---> c55942a02555
Step 5/9 : RUN powershell md c:\app
 ---> Using cache
 ---> 7765d010dfe1
Step 6/9 : RUN powershell New-Website -Name 'app' -Port 8081 -PhysicalPath 'c:\app'
 ---> Using cache
 ---> a6428cd501f2
Step 7/9 : COPY app c:\app
 ---> Using cache
 ---> e7c570008ad6
Step 8/9 : RUN dir c:\
 ---> Using cache
 ---> 79e346e38f66
Step 9/9 : RUN dir c:\app
 ---> Using cache
 ---> 64dc8889578b
Successfully built 64dc8889578b
```
Add a file locally to the `APP` subdirectory:
```
PS E:\docker\build\33107> add-content .\app\addedfile.aspx.cs "TEST"
```

And build again - the cache isn't used at step 7, and step 9 shows `addedfile.aspx.cs` in the container.
```
PS E:\docker\build\33107> docker build .
Sending build context to Docker daemon  5.632kB
Step 1/9 : FROM microsoft/windowsservercore
 ---> 511077485562
Step 2/9 : RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
 ---> Using cache
 ---> 5f198bff6181
Step 3/9 : EXPOSE 8081
 ---> Using cache
 ---> 13136ee1ffd5
Step 4/9 : RUN powershell Remove-Website -Name 'Default Web Site'
 ---> Using cache
 ---> c55942a02555
Step 5/9 : RUN powershell md c:\app
 ---> Using cache
 ---> 7765d010dfe1
Step 6/9 : RUN powershell New-Website -Name 'app' -Port 8081 -PhysicalPath 'c:\app'
 ---> Using cache
 ---> a6428cd501f2
Step 7/9 : COPY app c:\app
 ---> 34af0844efb2
Step 8/9 : RUN dir c:\
 ---> Running in 5d9a718261ae
 Volume in drive C has no label.
 Volume Serial Number is AAB5-8A76

 Directory of c:\

11/28/2017  02:48 PM    <DIR>          app
11/28/2017  02:45 PM    <DIR>          inetpub
09/29/2017  09:34 AM             1,894 License.txt
09/29/2017  04:28 AM    <DIR>          PerfLogs
09/29/2017  09:36 AM    <DIR>          Program Files
09/29/2017  04:28 AM    <DIR>          Program Files (x86)
09/29/2017  09:37 AM    <DIR>          Users
11/28/2017  02:45 PM    <DIR>          Windows
               1 File(s)          1,894 bytes
               7 Dir(s)  21,291,868,160 bytes free
Removing intermediate container 5d9a718261ae
 ---> f68984dfc3f3
Step 9/9 : RUN dir c:\app
 ---> Running in c7858e8c171d
 Volume in drive C has no label.
 Volume Serial Number is AAB5-8A76

 Directory of c:\app

11/28/2017  02:48 PM    <DIR>          .
11/28/2017  02:48 PM    <DIR>          ..
11/28/2017  02:48 PM                 6 addedfile.aspx.cs
11/28/2017  02:47 PM                 6 somefile.aspx.cs
11/28/2017  02:43 PM               296 test.txt
               3 File(s)            308 bytes
               2 Dir(s)  21,291,278,336 bytes free
Removing intermediate container c7858e8c171d
 ---> a789ab0ac147
Successfully built a789ab0ac147
PS E:\docker\build\33107> dir app


    Directory: E:\docker\build\33107\app


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/28/2017   2:48 PM              6 addedfile.aspx.cs
-a----       11/28/2017   2:47 PM              6 somefile.aspx.cs
-a----       11/28/2017   2:43 PM            296 test.txt
```

Here's my dockerfile:
```
PS E:\docker\build\33107> type dockerfile
# escape=`
FROM microsoft/windowsservercore
RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
EXPOSE 8081
RUN powershell Remove-Website -Name 'Default Web Site'
RUN powershell md c:\app
RUN powershell New-Website -Name 'app' -Port 8081 -PhysicalPath 'c:\app'
COPY app c:\app
RUN dir c:\
RUN dir c:\app
PS E:\docker\build\33107>
```

And the view from the host:
```
PS E:\docker\build\33107> dir


    Directory: E:\docker\build\33107


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/28/2017   2:48 PM                APP
-a----       11/28/2017   2:46 PM            337 dockerfile


PS E:\docker\build\33107>
```

**Comment by jhowardmsft** [comment]
Oh, maybe I spoke too soon. Editing a file in the `APP` directory didn't cause a cache break. Will investigate that.

**Comment by jhowardmsft** [comment]
Figured out the bug, but not sure of the fix quite yet (to also be LCOW compatible as well). It is when the host filesystem is not case-sensitive, the GetFile() function of `FileInfoSums` in `pkg\tarsum\fileinfosums.go` never matches as it's comparing (for example) `APP/test.txt` to `app/test.txt` and never hits. Proved a complete hack-of-a-fix (not PR'able) simply by adding a strings.ToLower in that function and changes to a file in the `APP\\` directory are breaking the cache as would be expected. Will figure out a better fix.

**Comment by schollii** [comment]
I'm getting this right now on Ubuntu 18.04 so it's not only case insensitivity of host OS that can cause this.

**Comment by yell0w4x** [comment]
+1 onn Ubuntu 18.04 and CoreOS 1911.3.0

**Comment by basickarl** [comment]
I'm running:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

I have the following in my Dockerfile: 
```
# Copy source files
COPY . /opt/www
```

I change some of the files, and yet, it still uses the cached layer. So it's not checking to see if the checksum has changed for the files.

**Comment by thaJeztah** [comment]
@basickarl if you have minimal reproduction steps, can you open a new ticket with those exact steps? Also be sure to check if (e.g.) there's no `.dockerignore` in use that may cause certain files to be ignored.

**Comment by james-sullivan** [comment]
I'm still having this issue as well

**Comment by bmll-henri** [comment]
I am getting this issue intermittently

**Comment by thaJeztah** [comment]
I'm locking the conversation on this ticket. The issue in this ticket was resolved 4 years ago, so if you are running into issues around this, they could be either unrelated, or a regression.

If you think there's a bug; open a new ticket instead, but make sure to provide the information that's requested in the issue template when you create the ticket (at least `docker version` and `docker info`); in addition;

- include information that may be relevant (are you building with BuildKit enabled (`DOCKER_BUILDKIT=-1`), or are you using the classic builder? Does the issue reproduce on both?)
- be sure to check if (e.g.) there's no `.dockerignore` in use that may cause certain files to be ignored.
- try to provide a minimal example to reproduce the issue (but exact steps to reproduce)
- make sure your reproduction steps do not depend on images or source code that's private (otherwise maintainers won't be able to use it to reproduce the issue).
