### ISSUE TITLE
Build from URL/tar archive: certificate signed by unknown authority

### ISSUE THREAD

**Issue by stour** [moby/moby#33113]
I'm trying to build an image from a TAR archive obtained from my GitLab server.
 
**Step to reproduce the issue:**
`docker build https://my-gitlab.com/user/repository/archive.tar?ref=MY-BRANCH`

**Describe the results you received:**
```
unable to prepare context: unable to download remote context https://my-gitlab.com/user/repository/archive.tar?ref=MY-BRANCH: Get https://my-gitlab.com/user/repository/archive.tar?ref=MY-BRANCH: x509: certificate signed by unknown authority
```

**Describe the results you expected:**
Build process starting.

**Additional information you deem important:**
I configured the CA certificate of `my-gitlab.com` in `/etc/docker/certs.d/my-gitlab.com/ca.crt` and restarted my Docker daemon but I'm still getting the same issue.

I had a look at [remote.go](https://github.com/moby/moby/blob/master/builder/remotecontext/remote.go#L33) and [httputils.go](https://github.com/moby/moby/blob/master/pkg/httputils/httputils.go#L20) where the error originates and it seems to me that there is no way to set the TLS configuration for the HTTP client (to either [skip CA certificate verification](http://stackoverflow.com/questions/12122159/golang-how-to-do-a-https-request-with-bad-certificate/12122718#12122718) or [set up a certificate](https://gist.github.com/michaljemala/d6f4e01c4834bf47a9c4#file-tls-client-go-L36-L39)).

**Are the certificates set in `/etc/docker/certs.d/*/ca.crt` supposed to work in this case ?**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 100
Server Version: 17.04.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:5-24657-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 40.42GB
 Data Space Total: 107.4GB
 Data Space Available: 21.23GB
 Metadata Space Used: 22.84MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.125GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.52GiB
Name: my-server
ID: NYC2:4HQQ:5DCP:J43I:5GH5:4LKB:IBFE:QFJA:CD4Y:YCFA:ZDST:V3WY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: localhost,127.0.0.1
Username: dmartins73
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ripcurld0** [comment]
@stour did you try to run this without using `https`:
```
 docker build http://my-gitlab.com/user/repository/archive.tar?ref=MY-BRANCH
```

Did that work?

**Comment by stour** [comment]
@ripcurld0 my GitLab server is configured for HTTPS only so this redirects to HTTPS and fails with the same error as previously described.

It seems that the HTTP client used by the `docker build` command is not configured with the TLS certificate that I put in `/etc/docker/certs.d/my-gitlab.com/ca.crt`.

**Comment by ripcurld0** [comment]
@stour from what I know `docker build` doesn't use any TLS configuration when downloading the file from URL as seen [here](https://github.com/docker/cli/blob/master/cli/command/image/build/context.go#L192-L194).

**Comment by stour** [comment]
So it means that I cannot download a file from an HTTPS server that has for instance a self-signed TLS certificate ?

**Comment by ripcurld0** [comment]
@stour Right now yes. There is a way to fix that though. It shouldn't be a problem.
@thaJeztah can I work on this?

**Comment by china-qd** [comment]
i meet this problem too. i solved by:
```
echo -n | openssl s_client -showcerts -connect **index.docker.io**:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >> /etc/ssl/certs/ca-certificates.crt
update-ca-trust
systemctl restart docker
```

**Comment by thaJeztah** [comment]
Discussing this with @tonistiigi in the maintainers meeting, and adding your custom certificates to your machine should probably resolve this problem (or of course use, e.g. letsencrypt to use a proper certificate).

We think this is too much of a corner-case, and we'd like to prevent re-implementing curl as part of the client, so for that reason I'm closing this issue, but thanks for reporting, and feel free to discuss 👍
