### ISSUE TITLE
Can't able to install Docker in Ubuntu

### ISSUE THREAD

**Issue by docvel** [moby/moby#33121]
Hi all,

        i've followed all the instructions well in dockers- ubuntu .

 still get the below error 

```
$ sudo apt-get install https://apt.dockerproject.org/repo/dists/ubuntu-xenial/InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package https://apt.dockerproject.org/repo/dists/ubuntu-xenial
E: Couldn't find any package by glob 'https://apt.dockerproject.org/repo/dists/ubuntu-xenial'
E: Couldn't find any package by regex 'https://apt.dockerproject.org/repo/dists/ubuntu-xenial'
```

For Docker-EE had used various url suggested in forum, But still faces the same error. :-(.

Thanks in Advance

**Comment by thaJeztah** [comment]
What architecture are you installing on? Can you add the output of `uname -a`, and the output of

```
cat /etc/apt/sources.list | grep docker
```

and

```
cat /etc/apt/sources.list.d/docker.list
```

Are you trying to install `docker ee` or `docker ce`?

**Comment by thaJeztah** [comment]
Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by docvel** [comment]
Hi , Thanks for the reply.
Yes. Trying to install docker-ee and followed the instructions 

https://docs.docker.com/engine/installation/linux/ubuntu/
-----------------------------------------------------------------------------------------------------------------
mani@mani-VirtualBox:~$ uname -a
Linux mani-VirtualBox 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
mani@mani-VirtualBox:~$ cat /etc/apt/sources.list | grep docker
deb [arch=amd64] <https://store.docker.com/editions/enterprise/docker-ee-server-ubuntu?tab=description> xenial stable-17.03
# deb-src [arch=amd64] <https://store.docker.com/editions/enterprise/docker-ee-server-ubuntu?tab=description> xenial stable-17.03
mani@mani-VirtualBox:~$ cat /etc/apt/sources.list.d/docker.list
cat: /etc/apt/sources.list.d/docker.list: No such file or directory
mani@mani-VirtualBox:~$ cd /etc/apt/sources.list.d/
mani@mani-VirtualBox:/etc/apt/sources.list.d$ ll
total 8
drwxr-xr-x 2 root root 4096 Apr 14  2016 ./
drwxr-xr-x 6 root root 4096 May  9 23:56 ../
-----------------------------------------------------------------------------------------------------------------------
Thanks.

**Comment by thaJeztah** [comment]
@docvel That URL doesn't look right. The instructions mention;

> Copy the URL from the field labeled Copy and paste this URL to download your Edition.

You need to go to your subscriptions page; https://store.docker.com/?overlay=subscriptions

<img width="1135" alt="screen shot 2017-05-10 at 12 09 52" src="https://cloud.githubusercontent.com/assets/1804568/25893903/12dfe1c0-357a-11e7-9be7-f66dac963904.png">

Click the "Setup button"

And copy the URL;

<img width="1144" alt="screen shot 2017-05-10 at 12 10 08" src="https://cloud.githubusercontent.com/assets/1804568/25893931/2d5c803a-357a-11e7-940d-8d128fe7688f.png">


The URL looks something like;

    https://storebits.docker.com/ee/ubuntu/sub-<some-unique-code-here>

The `/etc/apt/sources.list` file then needs to look like this;

```
deb [arch=amd64] https://storebits.docker.com/ee/ubuntu/sub-<some-unique-code-here> xenial stable-17.03
# deb-src [arch=amd64] https://storebits.docker.com/ee/ubuntu/sub-<some-unique-code-here> xenial stable-17.03
```

**Comment by thaJeztah** [comment]
Let me close this issue, because I don't think there's a bug here, but we can continue the conversation

**Comment by docvel** [comment]
Hi Sebaastian ,

                     Thanks for your reply. It works perfect. Will come
back at you if have any issues/questions instead of raising issues in
github. thanks again.


regards
s Mani.

**Comment by thaJeztah** [comment]
Perfect! Good to hear it worked!
