### ISSUE TITLE
Error messages returned by API should not refer to CLI flags/options

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#33138]
Some error messages returned by the daemon / API are referring to CLI flags not being valid, for example;

- [runconfig/hostconfig_windows.go#L34](https://github.com/moby/moby/blob/4af3389d43d93f50d9b4fa217de148ec45abf8cb/runconfig/hostconfig_windows.go#L34)
- [hostconfig_windows.go#L49](https://github.com/moby/moby/blob/4af3389d43d93f50d9b4fa217de148ec45abf8cb/runconfig/hostconfig_windows.go#L49)

Given that these are returned by the API, not the CLI, and we cannot assume that the _docker_ CLI is used as a client (it can be any (API) client), we should make these messages more generic and have them refer to the API-option that is not supported, not the CLI flag.

**Comment by sbko** [comment]
#dibs

**Comment by thaJeztah** [comment]
Thanks @sbko  - note that the files I linked above are just examples, there's probably quite some more. Let me know if you need help with creating the pull request 👍
