### ISSUE TITLE
`docker ps -a` appears to hang, sometimes takes 30 minutes to return.

### ISSUE THREAD

**Issue by suridge** [moby/moby#33136]
**Description**
`docker ps -a` appears to hang, sometimes takes 30 minutes to return. This is not always reproducible, and most often happens once the system has been running for a while (days/weeks). I've seen a number of similar issues raised, but I cannot be sure if this is the same issue. I'll attach the docker stacktrace, that perhaps someone clever can tell me what it means.

**Steps to reproduce the issue:**
1. I'm running 10 container on a single host. The containers are started using `docker-compose version 1.11.2, build dfed245`. 
2. The container images have `HEALTHCHECK`s defined.
3. Leave the containers running for a few days / weeks.
3. Try running `docker ps -a`

**Describe the results you received:**
- `docker ps -a` does not return, it appears to hang.
- I once left the command running, it took 30 minutes to return.

**Describe the results you expected:**
- The command should return in a reasonable time.

**Additional information you deem important (e.g. issue happens only occasionally):**
- docker stack trace here https://gist.github.com/suridge/359eac53dd79b9122f9db5d3fe90e59a
- when the system becomes unresponsive I see these log messages:
  - `Health check error: rpc error: code = 4 desc = context deadline exceeded`
  - possibly #31487?

**Output of `docker version`:**

```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 33
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-202870555-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.86 GB
 Data Space Total: 107.4 GB
 Data Space Available: 27.65 GB
 Metadata Space Used: 16.43 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.64 GiB
Name: ASM-KC-1
ID: KSVS:MOWY:YJ5R:PTKZ:PBEY:JJLP:2TNJ:IJGH:QHID:KY4C:Y5SK:BO4T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Looks like it may be stuck waiting for a response from containerd.
This is most likely fixed (as there have been many fixes in this regard, especially around healthchecks) in a newer version of Docker.

Are you able to test with an official docker build?

**Comment by suridge** [comment]
*Are you able to test with an official docker build?*
Do you mean instead of the RedHat (`docker-1.12.6-11.el7.x86_64`) version? I may be able to try it, but since my steps to reproduce are not exactly conclusive, I may not know for sure if the problem is fixed or not.

Are you able to glean anything from the stacktrace that may help in reproducing the problem? Do you think healthchecks are an important factor? Perhaps increase the frequency of the check? Anything else I should collect if the issue happens again?

**Comment by cpuguy83** [comment]
@suridge My guess would indeed be healthchecks.

**Comment by suridge** [comment]
Update: Just to let you know, that since disabling the `HEALTHCHECK` in our images, we have not seen this issue happen again. 

I will enable the `HEALTHCHECK` again once a new version of docker is available in the RedHat repositories. Does anyone know where I might find information on the release cycles for the RedHat version?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
