### ISSUE TITLE
container MemorySwappiness do not  inherited from the host machine

### ISSUE THREAD

**Issue by davidstack** [moby/moby#33158]
when i create container without MemorySwappiness  ,the default container memoryswappiness is -1.i find this code
`if hostConfig.MemorySwappiness == nil {
		defaultSwappiness := int64(-1)
		hostConfig.MemorySwappiness = &defaultSwappiness
	}`
but i see the MemorySwappiness should inherited from the host machine in this doc:https://docs.docker.com/engine/admin/resource_constraints/#memory-swappiness-details

shoud we change this docs? or change the default value of  MemorySwappiness  to another value?

**Comment by vvoland** [comment]
Should be fixed by https://github.com/moby/moby/pull/33898
