### ISSUE TITLE
Docker pull not using already pulled base image

### ISSUE THREAD

**Issue by cancan101** [moby/moby#33155]
**Description**
Docker pull (from private registry) seems to pull all layers even though most of them should be pre-pulled.
I have pre-baked an AMI with:
```
$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
tensorflow/tensorflow     1.1.0-devel-gpu     1300f9fcdba9        2 weeks ago         3.48GB
tensorflow/tensorflow     1.0.1-devel-gpu     3933652b8f5d        2 months ago        3.41GB
```
I then have an image that is `FROM tensorflow/tensorflow:1.0.1-devel-gpu` which I build (on a different machine) and then push to a private registry.
When I pull this image now, it seems to pull all the layers, not just the diffs to my image has. If I `docker inspect` the various images I see a fair bit of overlap under `Layers`.

**Steps to reproduce the issue:**
1. Build ami with base docker image
2. build docker (on another machine) and push to registry
3. pull image

**Describe the results you received:**
Many large layers pulled

**Describe the results you expected:**
Only the incremental layers get pulled.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happens first pull on the machine. Other pulls don't pull all the layers, even after doing `docker rmi`. The first pull shows a large number of layers as {`Waiting`, `Extracting`, `Download complete`}. When I then `docker rmi`, ~8 layers are marked as `Deleted`. A subsequent pull on the same box then only shows ~8 layers `Extracting` (far less than before).

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1016-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 486.7MiB
Name: node002
ID: EIXS:3553:J77I:BZU5:6TGA:73KO:UX2E:7IBL:M6TH:YUAS:TTXU:JZ3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 master:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on AWS.

**Comment by thaJeztah** [comment]
I tried to reproduce this issue by starting a local registry, building an image `FROM some-image`, pushing it to that registry, and removing the image that was built, then pulling it again did not lead to pulling all the layers

> Other pulls don't pull all the layers, even after doing `docker rmi`

With "other pulls", do you mean "other pulls of the same image after it was pulled once", or "any other pull (of other images)"?

Some questions/things that spring in mind;

- Are you only seeing this behaviour with this particular image, or any image?
- You built your image using `FROM tensorflow/tensorflow:1.0.1-devel-gpu` on another machine. Have you verified that that machine has _exactly_ the same version of the `tensorflow/tensorflow:1.0.1-devel-gpu` than is present in the AMI? Tags _are_ mutable, so are not a guarantee it's the same version of the image; you can use an immutable identifier instead (`FROM tensorflow/tensorflow@sha256:xyz`). You can find the matching version through `docker image ls --digests`, and look in the `DIGEST` column
- What kind of (and version) registry is used? Is this the Docker Open Source registry (https://docs.docker.com/registry/deploying/), or a different one?
- Are you seeing the same behaviour if you push the image (or a test-image) to Docker Hub?

**Comment by cancan101** [comment]
Just to make sure I am clear on the steps to reproduce:

On computer `A` pull base image `b`. On computer `B` build image `i` that is based on `b` and push to registry (yes I am using the docker Open Source registry).

Then do a pull of image `i` from computer `A`. This seems to pull all of the layers including what should already be pulled in `b`. You need two computers here. The issue doesn't come up if you remove images after pulling, etc.

**Comment by thaJeztah** [comment]
Just tried, but wasn't able to reproduce;

Server A:

```bash
$ docker pull nginx:alpine

alpine: Pulling from library/nginx
627beaf3eaaf: Already exists
d7d23baed7e7: Pull complete
7ded693c7a29: Pull complete
6856facfdc93: Pull complete
Digest: sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
Status: Downloaded newer image for nginx:alpine
```

Server B:

```
$ docker build -t <my-registry>:5000/repro-33155 -<<EOF
FROM nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
RUN echo "foo" > /bar
EOF
```

Check the layers of both `nginx` and my new image;

```bash
$ docker inspect --format '{{json .RootFS.Layers}}' nginx:alpine | jq .
[
  "sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2",
  "sha256:63128ffc1f407e6c85693ca2be30d27ebd0ad276e8d990521b7efa42d9dbfcf9",
  "sha256:fc837ba6bcd5c52b8d364a1dac35c28fad8e023e9fb282ba6f8cad0e44b74d57",
  "sha256:5163b989650192d7cf8e43b2264533b204276746e426c4e4e01501ded938728c"
]

$ docker inspect --format '{{json .RootFS.Layers}}' <my-registry>:5000/repro-33155 | jq .
[
  "sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2",
  "sha256:63128ffc1f407e6c85693ca2be30d27ebd0ad276e8d990521b7efa42d9dbfcf9",
  "sha256:fc837ba6bcd5c52b8d364a1dac35c28fad8e023e9fb282ba6f8cad0e44b74d57",
  "sha256:5163b989650192d7cf8e43b2264533b204276746e426c4e4e01501ded938728c",
  "sha256:5765b298788091f25920b783532d65e0b8628e360c8b501601cc3e5d90611a99"
]
```


$ docker push <my-registry>:5000/repro-33155

```

Server A:

```bash
$ docker pull <my-registry>:5000/repro-33155
Using default tag: latest
latest: Pulling from repro-33155
ec37562cf8fa: Already exists
d7d23baed7e7: Already exists
7ded693c7a29: Already exists
6856facfdc93: Already exists
a092bdc52773: Pull complete
Digest: sha256:8f2a33b45b2e16d07a5685f25e73d0a2137d66beb651098c36cddfdbad36b66c
Status: Downloaded newer image for 178.62.206.86:5000/repro-33155:latest
```

**Comment by cancan101** [comment]
I just did what you did and saw the issue I reported. Is your A totally virgin?
```
alex@node001:~$ docker pull nginx:alpine
alpine: Pulling from library/nginx
Digest: sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
Status: Image is up to date for nginx:alpine
alex@node001:~$ docker pull master:5000/repro-33155:latest
latest: Pulling from repro-33155
ec37562cf8fa: Pull complete
d7d23baed7e7: Pull complete
7ded693c7a29: Pull complete
6856facfdc93: Pull complete
ad26dc8dd685: Pull complete
Digest: sha256:1028712f2f0401e99842a00fadb48aba3b909f341597e283c88d07a30eaa36e2
Status: Downloaded newer image for master:5000/repro-33155:latest
```

Full log:
```
alex@master:~$ docker build -t <my-registry>:5000/repro-33155 -<<EOF
> FROM nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
> RUN echo "foo" > /bar
> EOF
-bash: my-registry: No such file or directory
alex@master:~$ docker build -t master:5000/repro-33155 -<<EOF
FROM nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
RUN echo "foo" > /bar
EOF

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f: Pulling from library/nginx
627beaf3eaaf: Pull complete
d7d23baed7e7: Pull complete
7ded693c7a29: Pull complete
6856facfdc93: Pull complete
Digest: sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
Status: Downloaded newer image for nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
 ---> 5a35015d93e9
Step 2/2 : RUN echo "foo" > /bar
 ---> Running in 94f26bf2cbde
 ---> 40384a62b0e3
Removing intermediate container 94f26bf2cbde
Successfully built 40384a62b0e3
Successfully tagged master:5000/repro-33155:latest

alex@master:~$ docker pull nginx:alpine
alpine: Pulling from library/nginx
Digest: sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
Status: Downloaded newer image for nginx:alpine

alex@master:~$ docker inspect --format '{{json .RootFS.Layers}}' nginx:alpine
["sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2","sha256:63128ffc1f407e6c85693ca2be30d27ebd0ad276e8d990521b7efa42d9dbfcf9","sha256:fc837ba6bcd5c52b8d364a1dac35c28fad8e023e9fb282ba6f8cad0e44b74d57","sha256:5163b989650192d7cf8e43b2264533b204276746e426c4e4e01501ded938728c"]

alex@master:~$ docker inspect --format '{{json .RootFS.Layers}}' master:5000/repro-33155:latest
["sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2","sha256:63128ffc1f407e6c85693ca2be30d27ebd0ad276e8d990521b7efa42d9dbfcf9","sha256:fc837ba6bcd5c52b8d364a1dac35c28fad8e023e9fb282ba6f8cad0e44b74d57","sha256:5163b989650192d7cf8e43b2264533b204276746e426c4e4e01501ded938728c","sha256:a77989896d4f7c4484c9891014aaf925dec28b1300888ebbeba80529b2d151e3"]

alex@master:~$ docker push master:5000/repro-33155:latest
The push refers to a repository [master:5000/repro-33155]
a77989896d4f: Pushed
5163b9896501: Pushed
fc837ba6bcd5: Pushed
63128ffc1f40: Pushed
23b9c7b43573: Pushed
latest: digest: sha256:1028712f2f0401e99842a00fadb48aba3b909f341597e283c88d07a30eaa36e2 size: 1360
```

**Comment by cancan101** [comment]
@thaJeztah Anything that I can gather to help out here?

**Comment by aaronlehmann** [comment]
Did the AMI have the base images pulled from a registry, or loaded from a file with `docker load`?

There is a mapping between compressed layer digests and uncompressed layer digests. This mapping would not be populated unless the image was pulled from a registry.

It's also not guaranteed that the machine that pushes the derivative image would compress the layers in a byte-for-byte identical way to how the base image's layers were compressed. So it's possible the compressed versions have different digests, and the machine that already has the base layers needs to download them again because it has not seen those compressed digests.

**Comment by cancan101** [comment]
The AMI had the base images pulled from a registry. 

Is there any way to verify / check this:?
> it's possible the compressed versions have different digests,

**Comment by aaronlehmann** [comment]
> what about the example above with nginx / alpine? You can see what I pasted.

Just took a closer look at that.

I'm curious what registry software (and version) you're running. The latest version of the image manifest format isn't supported by all registries, so Docker may fall back to an earlier version of the manifest format. If this is the case, you would see a warning in the daemon logs: `failed to upload schema2 manifest`.

I wouldn't normally expect the manifest version to make a difference here, but it could be a possible explanation for why you and @thaJeztah see different behavior.

**Comment by cancan101** [comment]
I am using the `registry` from docker:
```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
registry                  2                   136c8b16df20        6 weeks ago         33.2MB
```

**Comment by aaronlehmann** [comment]
I took a closer look at the example with `nginx:alpine`. It looks like the compressed blob digest of the first layer changed from `627beaf3eaaf...` to `ec37562cf8fa...`.

My interpretation is that `nginx:alpine` was built using a different build of Docker than the one that produced the base layer it was built from. As I mentioned above, details of compression can change from version to version. When `nginx:alpine` was pushed to Docker Hub, it reused the base layer artifact instead of pushing a new one, so this base layer retains its original compression.

When you build an image and push it to your own registry, there are no matching blobs on that registry to reuse, so Docker will compress and upload one. This gets compressed with the "new" compressor, and in this case it seems like it doesn't match the original image on Hub.

I'd recommend pushing tensorflow to your private registry, and pre-pulling that as part of the pre-baked AMI. This should work around the compression of layers tensorflow on Hub being different from compression of those layers when they are pushed to your private registry.

**Comment by cancan101** [comment]
Yikes. Are there any other flags, etc that can be used to get around this? I would prefer to not need to have my AMI building process have access to my private registry.

**Comment by aaronlehmann** [comment]
No, unfortunately we don't guarantee that a push to a different registry will result in the same compressed blob hashes as existed before.

I suppose you could set up a second registry and push there, or a less locked down area of the current private registry.

**Comment by cancan101** [comment]
It there any way to pre-seed my own registry with the blobs on Docker Hub so that the hashes will match?

Alternatively is there some way to trick / instruct Docker to realize on pull that the local cache (set of puled images) has the layers that it needs?

**Comment by aaronlehmann** [comment]
> Alternatively is there some way to trick / instruct Docker to realize on pull that the local cache (set of puled images) has the layers that it needs?

I suppose you could mess with these cache associations, though I'd hesitate to recommend it.

There are files in `/var/lib/docker/image/<graphdriver>/distribution/diffid-by-digest/sha256` with compressed layer hashes as their names, and LayerID values as their contents (with no newline at the end of the file). I expect that creating files here would work. Probably the easiest way to populate them is to copy the full set from a machine that pulled from (or pushed to) the private registry.

**Comment by cancan101** [comment]
Copying over those files to a new machine did work in avoiding the extra pulls. Is there no way to solve this problem on the image build / push side or by seeding the registry?

**Comment by cancan101** [comment]
Or some way to have the push to the private registry to use the layers as they were originally compressed.

**Comment by aaronlehmann** [comment]
It's definitely possible, but I don't know of any straightforward way to do it. You would need to manually download the blobs from Hub and upload them to your private registry using the registry API. Googling, I found this script: https://gist.github.com/jlhawn/8f218e7c0b14c941c41f. Possibly you could adapt it to pull then push, instead of pushing first and then pulling. You can find the compressed blob hashes by looking at the filenames in `diffid-by-digest` whose contents correspond to the `RootFS.Layers` values.

**Comment by thaJeztah** [comment]
closing, as this went stale, but this will improve with the containerd image-store integration, which persists all artifacts that were pulled
