### ISSUE TITLE
docker/docker/cli references

### ISSUE THREAD

**Issue by vito-c** [moby/moby#33153]
I'm sure there are more places referencing the old code path. Here is an example I found.
https://github.com/moby/moby/blob/master/man/generate.go#L10-L11

**Comment by vdemeester** [comment]
@vito-c thanks for the report. The man page generation is moving (part of it) in `docker/cli` so these might go away (maybe not for `dockerd` right away though)

/cc @dnephin @tiborvass

**Comment by dnephin** [comment]
Yup, PR is open for this fix: https://github.com/docker/cli/pull/68

These will be fixed as we find them. Unless we turn this issue into a tracking issue with a list of the old references, I think we can close it.

**Comment by thaJeztah** [comment]
Yes, I think we can close this for now, as we are aware that this needs to be updated along the way

Thanks @vito-c !
