### ISSUE TITLE
Unable to build from hash without pulling image first

### ISSUE THREAD

**Issue by MagnusS** [moby/moby#33165]
**Description**

Unable to build image from image hash in Dockerfile without pulling the image first. Build fails with `manifest verification failed for digest...`

**Steps to reproduce the issue:**
Dockerfile:
```
FROM alpine:edge@sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
```

If the image doesn't exist locally I can't build it:
```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM alpine:edge@sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
edge: Pulling from library/alpine
manifest verification failed for digest sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
```
... but if I run `docker pull` first it works:
```
$ docker pull alpine:edge@sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd: Pulling from library/alpine
71c5a0cc58e4: Pull complete
Digest: sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
Status: Downloaded newer image for alpine@sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd

$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM alpine:edge@sha256:99588bc8883c955c157d18fc3eaa4a3c1400c223e6c7cabca5f600a3e9f8d5cd
 ---> 8914de95a28d
Successfully built 8914de95a28d
```

**Describe the results you expected:**

`docker build .` should succeed even if the image didn't exist locally.

**Additional information you deem important (e.g. issue happens only occasionally):**

Not sure if relevant, but if I set `DOCKER_CONTENT_TRUST=1` then `docker build .` will build the image, but it looks like it pulls a different version than the specified hash.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
(D4M edge 17.05.0-ce-mac9)

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: JL2K:5EC4:JX5F:OQRG:I4EN:6AAE:YBKB:WD62:TJQX:QGHU:YS75:R2NQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 28
 System Time: 2017-05-11T14:50:56.430792365Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by justincormack** [comment]
Does it work with alpine@sha256:... without the tag as well? The tag plus
hash form is less common and may need more tests added.

**Comment by MagnusS** [comment]
@justincormack yes, build seems to work as expected if I use `FROM alpine@sha256:...` instead.

**Comment by avsm** [comment]
What's the use of adding the tag if the sha256 is included as well?  Seems the tag and a hash should be an either/or for selecting the image to use.

**Comment by tonistiigi** [comment]
@dmcgowan I think you added some cases for this as part of the reference pkg changes recently. Probably this gets normalized in cli or api layer instead of the pull code, so builder doesn't pass these checks but not very familiar with it.

It is also bug if dct replaces this reference. It should be ignored if the user has specified the sha. Probably not the same root cause so maybe need to track them differently.

**Comment by tonistiigi** [comment]
@avsm The current behavior on pull is to ignore the tag, but users can use it as a human-readable hint.
