### ISSUE TITLE
default net looses connectivity after creating 2nd network

### ISSUE THREAD

**Issue by bebehei** [moby/moby#33168]
## Description

After creating a 2nd network on the hosts' main network device, the default network is not able to communicate beyond its own subnet anymore.

### Steps to reproduce the issue:

The host's main network configuration is done via a bridge. The default route for the host runs over `br1`:

```
# /etc/network/interfaces
auto br1
iface br1 inet dhcp
  bridge_ports enp4s0
  bridge_stp off
```

Until here, it works fine. Full communication to the outside world is possible.

Some of my docker-containers have to get their own IP-addresses from our main network. So I declare a 2nd network, which uses a subrange of the bridge `br1`:

```
docker network create \
        -d=bridge \
        --subnet "192.168.0.1/24" \
        --ip-range "192.168.0.128/25" \
        --gateway "192.168.0.2" \
        -o com.docker.network.bridge.enable_ip_masquerade=true \
        -o com.docker.network.bridge.enable_icc=true \
        -o com.docker.network.bridge.name="br1" \
        --aux-address DefaultGatewayIPv4="192.168.0.1" \
        full_exposure
```

After this, the hassle starts. Here is a good example to illustrate it via ping:
1. start a container on default network
1. run ping 8.8.8.8
1. in parallel:
    - create the network: ping seqs stop
    - remove the network: ping seqs go on

```
$ docker run --rm -ti ubuntu
root@a0420e64ed4e:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=45 time=13.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=45 time=13.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=45 time=13.3 ms # <- here I run docker network create [...]

# seq 4-7 missing

# Now, I run docker network rm full_exposure

64 bytes from 8.8.8.8: icmp_seq=8 ttl=45 time=13.3 ms # <- and pinging works fine
64 bytes from 8.8.8.8: icmp_seq=9 ttl=45 time=13.3 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=45 time=13.3 ms
^C
--- 8.8.8.8 ping statistics ---
10 packets transmitted, 6 received, 40% packet loss, time 9039ms
rtt min/avg/max/mdev = 13.310/13.363/13.544/0.157 ms
```

### Describe the results you expected:

The first network should not cut off the second network.

## The issue in atomic form

After creating the second network, some iptables-rules get added. Here is the hazard:

```
$ iptables -S
[...]
-A DOCKER-ISOLATION -i docker0 -o br1 -j DROP
-A DOCKER-ISOLATION -i br1 -o docker0 -j DROP
[...]
```

While `br1` is the main interface for the whole host, `docker0` is prohibited to communicate with. And therefore any container using the default network.

# The fix

My temporary workaround is to manually remove those lines. But this is not 100% correct.

The general fix should be, that in the case, where a docker network is created on the hosts' default bridge, all other networks should only drop packages from one direction. The direction docker0 -> br1 should stay intact.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-77-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73GiB
Name: meyer
ID: UPT4:O2EA:DMZ5:TEWL:6KYR:DT5F:ANKR:RCAB:HNNG:3FW3:YS34:I65I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by bebehei** [comment]
I also have to add, that this is related to #27056. For some reasons it's quite similar, but I don't understand why.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
