### ISSUE TITLE
Getting advanced traffic shaping with tc and containers to work

### ISSUE THREAD

**Issue by mlafeldt** [moby/moby#33162]
**Description**

Hey,

We're trying to do traffic shaping with [tc](http://man7.org/linux/man-pages/man8/tc.8.html) and Docker containers in order to simulate different network conditions.

We're using `--net=container:x` to impact traffic of specific containers. While it's possible to shape all outgoing traffic via [tc-netem](http://man7.org/linux/man-pages/man8/tc-netem.8.html), trying to configure more advanced filters, e.g. to only impact specific ports or IP addresses, results in all traffic getting lost.

(With `--net=host`, `tc` works as expected. However, that's affecting the entire host, of course.)

We'd really like to do more advanced traffic shaping with containers and are looking for help to get it working.

**Steps to reproduce the issue:**

Start `alpine` container and run ping in it:

```
docker run -it --rm --name alpine alpine /bin/sh
ping google.com
```

Slow down all outgoing traffic of container:

```
docker run --rm --cap-add NET_ADMIN --net=container:alpine gaiadocker/iproute2 qdisc add dev eth0 root netem delay 3000ms
```

Remove the delay again:

```
docker run --rm --cap-add NET_ADMIN --net=container:alpine gaiadocker/iproute2 qdisc del dev eth0 root netem
```

So far so good. Affecting all outgoing traffic works as expected.

However, as soon as we add our own qdisc in order to create more advanced filters with `tc`, the container can no longer send any pings to the outside world.

```
# Create qdisc. This is where ping inside the alpine container stops reporting anything.
docker run --rm --cap-add NET_ADMIN --net=container:alpine gaiadocker/iproute2 qdisc add dev eth0 root handle 1: htb

# Meant to block all DNS traffic. No effect since the previous command already "blocks" all traffic.
docker run --rm --cap-add NET_ADMIN --net=container:alpine gaiadocker/iproute2 filter add dev eth0 parent 1: protocol ip prio 2 u32 match ip dport 53 0xffff police mtu 1 drop
```

After removing the qdisc, ping is working again:

```
$ docker run --rm --cap-add NET_ADMIN --net=container:alpine gaiadocker/iproute2 qdisc del dev eth0 root handle 1:
```

I also tried shaping traffic from outside the container via its veth interace. However, the result was the same.

Again, I want to make clear that all of this works fine with host networking (`--net=host`), e.g. with the `enp0s3` interface in a Vagrant VM.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 992.2MiB
Name: gremlin-1
ID: FSIH:NUVF:OTVA:GW6I:MD4O:E7KS:2JPJ:5JP3:7VKD:TU7D:HKO2:OSRT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Vagrant 1.9.3
- VirtualBox 5.0.20

**Comment by scareything** [comment]
I'm seeing this also. I am able to add the htb disc to a container's interface without dropping packets, if I set the direct_qlen:

    $ tc qdisc add dev eth0 root handle 1: htb default 30 direct_qlen 1000

However classes and/or filters aren't working. All packets that match my filters are dropped instead of being applied to the class:

    $ tc class add dev eth0 parent 1: classid 1:1 htb rate 5mbps
    $ tc filter add dev eth0 protocol ip parent 1:0 prio 1 u32 match ip dst 10.0.3.111/32 match ip dport 5435 0xffff flowid 1:1
    $ tc -s -d qdisc show dev eth0
    qdisc htb 1: root refcnt 2 r2q 10 default 30 direct_packets_stat 18109924 ver 3.17 direct_qlen 1000
    Sent 48206931669 bytes 48060128 pkt (dropped 227, overlimits 0 requeues 0)
    backlog 0b 0p requeues 0
    $ tc -s -d qdisc show dev eth0
    qdisc htb 1: root refcnt 2 r2q 10 default 30 direct_packets_stat 18294244 ver 3.17 direct_qlen 1000
    Sent 48812778498 bytes 48626372 pkt (dropped 266, overlimits 0 requeues 0)
    backlog 0b 0p requeues 0

**Comment by mlafeldt** [comment]
We found out that virtual devices run without a qdisc attached by default ([for performance reasons](https://bugzilla.redhat.com/show_bug.cgi?id=1152231)).

By setting the queue length manually either before calling tc (e.g. `ip link set eth0 qlen 1000`) or when adding the qdisc (`tc qdisc ... direct_qlen 1000`), we were able to get traffic shaping to work. 🎉
