### ISSUE TITLE
logs request will make daemon raising a error when container stopped

### ISSUE THREAD

**Issue by CMGS** [moby/moby#33172]
**Description**

if a container stopped and you had a request or use cli command to get it's logs, you will see "level=error msg="Error closing logger: invalid argument"" in daemon's log.

**Steps to reproduce the issue:**

1. start a container, make sure it use json-file log driver.
2. start a request or use cli command to get it logs.
3. stop the container

**Describe the results you received:**

in daemon's log, I got 
```c2-docker-31.ricebook.link dockerd[11491]: time="2017-05-12T16:07:47.376078508+08:00" level=error msg="Error closing logger: invalid argument"```

**Describe the results you expected:**

nothing

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge calico host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.64-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: c2-docker-31.ricebook.link
ID: CHYZ:J7RJ:SVRT:FLUT:TXN5:77S5:JFNJ:V2E4:WB3X:LMX3:ZJ3F:4XKK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Cluster Store: etcd://127.0.0.1:2379
Insecure Registries:
 hub.ricebook.net
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by aaronlehmann** [comment]
ping @dperny

**Comment by dperny** [comment]
@CMGS To confirm what I'm thinking: There is an error message in the daemon logs, but there is no crash, degradation, or other ill-effects from this, right? 

(For contributors: this is on container logs, not service logs.)

**Comment by CMGS** [comment]
@dperny yes, however if you start lots short-lifetime containers to do some data analysis and get logs from remote logs API then the daemon logs will full of this error message. I don't think it is a **bug**, but too annoying

**Comment by thaJeztah** [comment]
@cpuguy83 something like this perhaps?

```patch
diff --git a/daemon/logger/loggerutils/rotatefilewriter.go b/daemon/logger/loggerutils/rotatefilewriter.go
index 99e0964ae..0646cf5b3 100644
--- a/daemon/logger/loggerutils/rotatefilewriter.go
+++ b/daemon/logger/loggerutils/rotatefilewriter.go
@@ -120,5 +120,9 @@ func (w *RotateFileWriter) NotifyRotateEvict(sub chan interface{}) {

 // Close closes underlying file and signals all readers to stop.
 func (w *RotateFileWriter) Close() error {
-       return w.f.Close()
+       err := w.f.Close()
+       if err == os.ErrInvalid {
+               return nil
+       }
+       return err
 }
```

**Comment by cpuguy83** [comment]
I would move that check to where the log happens... or just not log a close error.

**Comment by cpuguy83** [comment]
`Close()` should also lock here and can probably just return without attempting a close if it's already been closed.
