### ISSUE TITLE
Issue 26371 happening in mac again

### ISSUE THREAD

**Issue by prabhakm** [moby/moby#33186]
I am having the same problem mentioned in issue https://github.com/moby/moby/issues/26371. 
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

Any help to resolve?

**Comment by thaJeztah** [comment]
Tried reproducing this on docker 19.03;

```
docker run --rm -d --log-driver=fluentd nginx:alpine
28371605d2796e8c884608dae31477601302f6aa65d4fec5060748003d655263
docker: Error response from daemon: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused.
```

```
docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Note that the `--rm` option in current docker versions will remove the container immediately, so also trying without `--rm`; after that checking if `nginx` is running as a process;

```
docker run -d --log-driver=fluentd nginx:alpine

ps -auxf | grep nginx
(no result)
```
