### ISSUE TITLE
Docker stack deploy creates external volumes if they do not already exist

### ISSUE THREAD

**Issue by briantd** [moby/moby#33181]
**Description**

Running `docker stack deploy -c <stackfile>` on a stackfile with external volumes results in the creation of those volumes.

**Steps to reproduce the issue:**
1. Confirm named-volume does NOT exist (i.e. `docker volume ls`)
2. Prepare a stackfile with a service using an externally declared named-volume (i.e. `external: true`)
3. Deploy stackfile and observe the creation of a local named-volume

```
$ docker volume ls
DRIVER              VOLUME NAME

$ cat dc-test-external-exits.yml
version: "3.1"
services:
  aservice:
    image: busybox
    volumes:
      - test-vol:/tmp:z
volumes:
  test-vol:
    external: true

$ docker stack deploy -c dc-test-external-exits.yml myapp
Creating network myapp_default
Creating service myapp_aservice

$ docker volume ls
DRIVER              VOLUME NAME
local               test-vol
```

**Describe the results you received:**
`docker stack deploy` invocation succeeds; external named-volume created using local driver on nodes where the service was deployed.

**Describe the results you expected:**
`docker stack deploy` invocation fails with a message explaining the external named-volume could not be found.

Failing when external **volumes** are missing would be consistent with how external **networks** and external **secrets** are handled.

For example...
```
swarm-manager000000:~$ docker stack deploy -c dc-test-external-network-exits.yml myapp
network "myextnet" is declared as external, but could not be found. You need to create the network before the stack is deployed (with overlay driver)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Related -- this behavior is inconsistent with the documentation.  I filed a separate issue there --> https://github.com/docker/docker.github.io/issues/3141

**Output of `docker version`:**

```
swarm-manager000000:~$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
swarm-manager000000:~$ docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: h35071xklgf3x0cmpoh8wk2z0
 Is Manager: true
 ClusterID: k859559qob9bdrm7j3vrcj9j3
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.6
 Manager Addresses:
  10.0.0.6:2377
  10.0.0.7:2377
  10.0.0.8:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.19-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.794GiB
Name: swarm-manager000000
ID: HJ5Y:V7C3:WFMA:BDYO:A3K3:5L2P:J5EK:ZILC:NO7O:VO7R:XI2D:KMJ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 89
 Goroutines: 170
 System Time: 2017-05-12T19:27:44.773838769Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This has been tested using Docker Azure.

**Comment by dnephin** [comment]
I think there is an issue for this already. This is a limitation of swarm mode. There is no way to check if a volume exists. The only way to create a swarm mode volume is to specify the volume information in the service, and there's no way to say "Don't create it, just mount it".

**Comment by briantd** [comment]
@dnephin I'm happy to link this issue if one is already open.  Just wanted to point out that the existing behavior is inconsistent with other external types and what is stated in the documentation.

**Comment by cghislai** [comment]
#29976

**Comment by thaJeztah** [comment]
Thanks @cghislai that's indeed the issue; let me close this one as it's a duplicate
