### ISSUE TITLE
Problem Refactor Package from Docker Client to Moby Client

### ISSUE THREAD

**Issue by bxcodec** [moby/moby#33196]
**Description**

I'm using docker client in golang, to get list of images in my docker engine. 

**Steps to reproduce the issue:**
1. Trying to get Image List
 with : 
```go
import  "github.com/moby/moby/client"
//DockerClient is *client.Client type
images,err :=  DockerClient.ImageList(ctx, types.ImageListOptions{})
```

**Describe the results you received:**
```bash
cannot use "github.com/moby/moby/api/types".ImageListOptions literal (type "github.com/moby/moby/api/types".ImageListOptions) as type "github.com/docker/docker/api/types".ImageListOptions in argument to DockerClient.ImageList
```

**Describe the results you expected:**
No Error on compiling.

**Comment by thaJeztah** [comment]
I think you currently still need to use `github.com/docker/docker/client` for the import, because not all references have been renamed in the source-code (leading to packages being imported twice); could you give that a try?

**Comment by cpuguy83** [comment]
Yes, please continue to use `github.com/docker/docker` as an import path.
I do not think `github.com/moby/moby` will ever be a valid path for the HTTP client.

**Comment by cpuguy83** [comment]
Closing since this is basically as expected, but feel free to comment if you still have an issue.
Thanks!
