### ISSUE TITLE
Build fails on missing libzfs-dev

### ISSUE THREAD

**Issue by mmariani** [moby/moby#33194]
Building from either makefile or dockerfile breaks while looking for a missing deb package.

To reproduce:

`$ docker build -t docker https://github.com/moby/moby.git#v17.05.0-ce
`
(or master branch)

```
[...]
Building dependency tree...
E: Unable to locate package libzfs-dev
The command '/bin/sh -c apt-get update && apt-get install -y 	apparmor 	apt-utils 	aufs-tools 	automake 	bash-completion 	binutils-mingw-w64 	bsdmainutils btrfs-tools 	build-essential 	clang 	cmake 	createrepo 	curl 	dpkg-sig 	gcc-mingw-w64 	git 	iptables 	jq 	less 	libapparmor-dev 	libcap-dev 	libltdl-dev 	libnl-3-dev 	libprotobuf-c0-dev 	libprotobuf-dev 	libsystemd-journal-dev 	libtool 	libzfs-dev 	mercurial 	net-tools 	pkg-config 	protobuf-compiler 	protobuf-c-compiler 	python-dev 	python-mock 	python-pip 	python-websocket 	tar 	ubuntu-zfs 	vim 	vim-common 	xfsprogs 	zip 	--no-install-recommends 	&& pip install awscli==1.10.15' returned a non-zero code: 100
```

**Comment by thaJeztah** [comment]
Ironically, trying to reproduce this, but when spinning up a new DigitalOcean droplet, I'm getting 404's on some of their mirrors

```
W: The repository 'http://mirrors.digitalocean.com/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://mirrors.digitalocean.com/ubuntu xenial-updates Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://mirrors.digitalocean.com/ubuntu xenial-backports Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/xenial/main/source/Sources  404  Not Found [IP: 103.253.144.50 80]
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/xenial-updates/main/source/Sources  404  Not Found [IP: 103.253.144.50 80]
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/xenial-backports/main/source/Sources  404  Not Found [IP: 103.253.144.50 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by mmariani** [comment]
I stopped looking when I could not install the debian packages zfs-linux, zfs-dkms to replace ubuntu-zfs... Last year zfs has supposedly landed on jessie but I'm missing something.

**Comment by thaJeztah** [comment]
I can confirm I get the same error; `libzfs-dev` seems to be missing now in the debian repos for some reason, which is odd as this dependency has been there for three years https://github.com/moby/moby/commit/d5151ca8ab5d90300839c8572cb96577de4d6233

**Comment by thaJeztah** [comment]
^^ That change was when we still used `ubuntu` as base image, but for the last year, `debian:jessie` was used without issues

**Comment by justincormack** [comment]
@thaJeztah that commit you point to is `FROM ubuntu`. I don't believe Debian has ever had zfs...

**Comment by thaJeztah** [comment]
@justincormack it has been in the dockerfile ever since (even when we switched to jessie) https://github.com/moby/moby/commit/f27b5dda4afc0b0a278eb5379d17dfc3533c5397

Should it be `libzfslinux-dev` ? https://packages.debian.org/jessie-backports/libzfslinux-dev

**Comment by justincormack** [comment]
Ah

```
# Add zfs ppa
COPY keys/launchpad-ppa-zfs.asc /go/src/github.com/docker/docker/keys/
RUN apt-key add /go/src/github.com/docker/docker/keys/launchpad-ppa-zfs.asc
RUN echo deb http://ppa.launchpad.net/zfs-native/stable/ubuntu trusty main > /etc/apt/sources.list.d/zfs.list
```

we were adding a trusty ppa for get zfs for Debian. I assume it broke.

**Comment by justincormack** [comment]
I don't think we should have this at all...

**Comment by barnettZQG** [comment]
I met the same problem.
Start in 1.12.6 version I compile error, using the latest version of the "ZFS ppa" source from Dokerfile is still wrong.

**Comment by thaJeztah** [comment]
Yes, It looks like that PPA was updated yesterday, and something is missing or not configured correctly?

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/33197 to remove it from the Dockerfile
