### ISSUE TITLE
Swarm Load-Balancing Not Publishing Ports

### ISSUE THREAD

**Issue by daviddyball** [moby/moby#33205]
**Description**

My production swarm cluster is no longer publishing ports for services. Looking at the `iptables` output on the manager nodes shows no mention of ports that should now be published.

**Steps to reproduce the issue:**
1. Publish a service with an exposed port 
    ```
    docker service create --publish 80:80 --name test-service nginx:latest
    ```
2. The service should get created and port `80` should be available on the cluster nodes and route correctly to the node running the service

**Describe the results you received:**
The port is unavailable on any node in the cluster (including the node running the service)
    ```
    ~$ curl http://localhost:9000/
    curl: (7) Failed to connect to localhost port 9000: Connection refused
    ```

**Describe the results you expected:**
The port should be published correctly and be accessible both internally and externally

**Additional information you deem important (e.g. issue happens only occasionally):**
The service I'm trying to publish the port for is running on one of the manager nodes. It is here that I enabled debug logging and saw a *lot* of output like this (which periodically repeats):
```
dockerd[14756]: time="2017-05-15T17:27:02.026342007Z" level=debug msg="memberlist: Failed to join 
192.168.30.145: dial tcp 192.168.30.145:7946: i/o timeout"
```

The thing is that `192.168.30.145` isn't an IP address of one of my nodes **or** one of the managers. Where could it be coming from?

Output of `iptables -nL`
```
root@ip-192-168-20-49:~# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain DOCKER-INGRESS (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9200
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED tcp spt:9200
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5601
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED tcp spt:5601
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9999
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED tcp spt:9999
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

Output of `iptables -nL -t nat`
```
root@ip-192-168-20-49:~# iptables -t nat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match src-type LOCAL
MASQUERADE  all  --  172.18.0.0/16        0.0.0.0/0           
MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:9000

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-INGRESS (2 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9200 to:172.18.0.3:9200
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5601 to:172.18.0.3:5601
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9999 to:172.18.0.3:9999
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.528GB
 Data Space Total: 12.23GB
 Data Space Available: 10.71GB
 Metadata Space Used: 598kB
 Metadata Space Total: 125.8MB
 Metadata Space Available: 125.2MB
 Thin Pool Minimum Free Space: 1.223GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: bedxt3bk643gzc3zuqna81vcv
 Is Manager: true
 ClusterID: dp6ymfu05oshxsffn91ci6xcj
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.20.49
 Manager Addresses:
  192.168.20.49:2377
  192.168.21.13:2377
  192.168.22.139:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-192-168-20-49
ID: 63ML:JF46:WEB7:KTWC:4GMF:BMUG:IFBW:OEES:DWGH:2QG4:LU4F:EQVC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 139
 Goroutines: 295
 System Time: 2017-05-15T17:31:32.547441252Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
 com.amazon.aws.ec2.instance-type=t2.small
 com.amazon.aws.ec2.availability-zone=eu-west-1a
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS EC2 via auto-scaling groups

**Comment by cpuguy83** [comment]
In your example you have a curl to port 9000.
I assume this is a typo given the command you ran should have it on port 80?

Also are you certain the service is running?

> 192.168.30.145 isn't an IP address of one of my nodes 

Each node has a "listen" address and a "advertise" address. The "listen" address is the address that the swarm node API actually listens on/binds to. The "advertise" address is the address that the node reports itself as to other members of the swarm, which other nodes will use to communicate back over. These are picked automatically when you add the node to the cluster (or init a new cluster) if it's easy to tell what interface it should be listening on.
This address needs to be stable.
You can manually specify both the listen address and the advertise address.
Could it be that a bad address was picked or that an IP changed along the way?

**Comment by daviddyball** [comment]
Hi @cpuguy83,

Yes, `9000` was a typo. I do have a service running on that port that had the same issue though. `exec`ing into the service container and doing a local curl inside returns content fine.

Are the advertise and listen addresses on the managers modifiable, or do I need to demote+remove+re-add them?

Being EC2, there is a chance the nodes have changed IP, but it isn't a usual case. IPs should remain for the lifetime of the instances. I'll recycle the managers 1-by-1 so that everything has a fresh config and correct addresses for listen and advertise. Being a production cluster, I have to be careful, otherwise I'd just trash the whole thing and start fresh!

**Comment by cpuguy83** [comment]
@daviddyball I think you would have to demote/remove and then re-add. We just don't have support for changing addresses for now.

**Comment by daviddyball** [comment]
Thanks. I'll report back once I do the re-jigg.

**Comment by daviddyball** [comment]
So, this didn't go so well at all. I replaced two of the 3 manager nodes with new instances (each ensuring that they pass `--listen-addr` and `--advertise-addr` correctly pointing to their EC2 Local IPv4 addresses).

When it came time to do the third one, the whole cluster locked up and got stuck in an election loop and no commands could run at all on any of the instances (`context deadline exceeded`). Logs bellow:

```
time="2017-05-16T13:04:45.531574761Z" level=info msg="4195bb5204738e53 is starting a new election at term 403" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:45.531983251Z" level=info msg="4195bb5204738e53 became candidate at term 404" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:45.532167850Z" level=info msg="4195bb5204738e53 received MsgVoteResp from 4195bb5204738e53 at term 404" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:45.532350234Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 7c981d5357910904 at term 404" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:45.532526411Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 76eb7936e2257d94 at term 404" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:48.531609757Z" level=info msg="4195bb5204738e53 is starting a new election at term 404" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:48.532034500Z" level=info msg="4195bb5204738e53 became candidate at term 405" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:48.532223505Z" level=info msg="4195bb5204738e53 received MsgVoteResp from 4195bb5204738e53 at term 405" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:48.532396443Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 7c981d5357910904 at term 405" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:48.532566131Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 76eb7936e2257d94 at term 405" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.531676529Z" level=info msg="4195bb5204738e53 is starting a new election at term 405" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.532087052Z" level=info msg="4195bb5204738e53 became candidate at term 406" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.532254621Z" level=info msg="4195bb5204738e53 received MsgVoteResp from 4195bb5204738e53 at term 406" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.532412970Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 76eb7936e2257d94 at term 406" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.532568361Z" level=info msg="4195bb5204738e53 [logterm: 291, index: 1623673] sent MsgVote request to 7c981d5357910904 at term 406" module=raft node.id=hs9uaimzkmodbl07lslselpea
time="2017-05-16T13:04:53.836154954Z" level=error msg="agent: session failed" error="session initiation timed out" module="node/agent" node.id=hs9uaimzkmodbl07lslselpea
```

The good news (I guess) is that I now have a clean cluster with correct `*-addr` options specified.... the bad news was that my production systems were affected pretty severely by this random lock-up

**Comment by cpuguy83** [comment]
@daviddyball eek!
One thing to keep in mind, you'll want to wait to remove a node until after the new node is online, this way you can keep consensus.
If you only have two nodes and take one down you won't have consensus anymore.

Also in case this ever happens you can use `docker swarm init --force-new-cluster` to start a new cluster with the same state.

Can you explain what procedure you used to change the nodes?

**Comment by daviddyball** [comment]
Hi @cpuguy83, I did all nodes one-by-one and waited until I had 3 in the cluster before I took any more out. `docker node ls` always shower 3 managers before I took one out of the cluster, which is why the lock-up was so unexpected.

The process​ was:
1. Terminate one node via EC2 console
2. Wait for the replacement to come into service
3. Login to the new node and check it's listed as a manager under `docker node ls`
4. Rinse & Repeat for all nodes

Except when the second node was in service and it came time to remove the last of the three original cluster managers, the cluster locked up.

I wasn't aware that `--force-new-cluster` maintained state! Does that include all service definitions?

Now that the cluster is hopefully in a stable state, I'll try making published services again and see if the load-balancing problem persists.

**Comment by cpuguy83** [comment]
> Does that include all service definitions?

Yep. Everything that the manager knows about.

**Comment by daviddyball** [comment]
Damn... I'll remember that for next time!

**Comment by thaJeztah** [comment]
Let me close this issue, because the issue looks to be resolved (for now), but feel free to leave a comment if you have a way to reproduce 👍

**Comment by daviddyball** [comment]
No, this isn't resolved. I still can't create load-balanced services at all!

**Comment by thaJeztah** [comment]
:cry: I'll reopen

**Comment by daviddyball** [comment]
@thaJeztah I have to apologise.... it works fine.... the service was dead and I can only assume that the healthcheck mech was preventing anything from routing to the dead services. 100% my fault and 100% user error :-(

**Comment by thaJeztah** [comment]
Haha, no worries!

**Comment by destebanm** [comment]
We are running 3 managers node swarm (17.06.2) in EC2, with a global service. This service publishes the 8080 port to the ingress network with `--publish 8080:8080`. It works fine. If I run `iptables -t nat -L -n | grep 8080` in whichever node I get:
`DNAT tcp -- 0.0.0.0/0 0.0.0.0/0 tcp dpt:8080 to:172.18.0.2:8080`

If we remove two nodes at the same time, the service continues working on only one node, but it works.

We run docker node ls in the healthy node we get The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online. This is expected. So the only solution is to run a `docker swarm init --force-new-cluster --listen-addr $PRIVATE_IP:2377 --advertise-addr $PRIVATE_IP:2377`

Now is when the issue arises: it seems that service starts without problems (HEALTHCHECK of the container is passed) but the thing is that it does not publish the port to the ingress network. We checked by doing` iptables -t nat -L -n | grep 8080` and not getting any result.

This causes that our service is not available to listen in 8080
Any help to avoid that?

Thanks!

**Comment by destebanm** [comment]
I have opened this issue #34987 instead of using this closed one.

**Comment by thaJeztah** [comment]
Thanks!
