### ISSUE TITLE
Windows Docker Images stopped working as of today 5/15

### ISSUE THREAD

**Issue by choochford** [moby/moby#33210]
```
<--PS C:\Windows\system32> docker run -i microsoft/dotnet-framework:3.5
Unable to find image 'microsoft/dotnet-framework:3.5' locally
3.5: Pulling from microsoft/dotnet-framework
3889bb8d808b: Pull complete
6d4d50238ed1: Pull complete
19ac9e1607cd: Pull complete
86302cb497a1: Pull complete
Digest: sha256:7aa4a006b3ac9d51ea06ca42739cd029dbf2661b519a431ad262bd51275fd619
Status: Downloaded newer image for microsoft/dotnet-framework:3.5
C:\Program Files\Docker\docker.exe: Error response from daemon: container bcb52f2c6753087fda7521a23c543f1f33a48914c3b2ee
2a6b7dd80ff70c466a encountered an error during CreateContainer: failure in a Windows system call: Incorrect function. (0
x1) extra info: {"SystemType":"Container","Name":"bcb52f2c6753087fda7521a23c543f1f33a48914c3b2ee2a6b7dd80ff70c466a","Own
er":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{ed323ee3-39a6-11e7-9676-000c291eee2d}","IgnoreFlushesDuringBoot
":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\bcb52f2c6753087fda7521a23c543f1f33a48914c3b2ee2a6b7dd8
0ff70c466a","Layers":[{"ID":"d6036c81-5c04-5068-9dc1-0b544c5ab2e4","Path":"C:\\ProgramData\\docker\\windowsfilter\\62641
d3c7f63bbafdccc9859d5f5aaf3fde76538b9e30fb3580689f0f880d46f"},{"ID":"7e364718-13c9-5a7c-a1d3-a395e33d3320","Path":"C:\\P
rogramData\\docker\\windowsfilter\\1be6f0614b85626e3ec8d5a1cd6124755b75e65c7404b77773ef55f3ae713ec6"},{"ID":"5ac77583-da
3f-520c-b131-e9c6fb677b99","Path":"C:\\ProgramData\\docker\\windowsfilter\\ccda3460d899696d9ad76d327190d372c3f1e086cf140
dcb5dccd6d4a8f9e7ff"},{"ID":"60391f3d-ce8a-5640-97e1-8c8d651f9d80","Path":"C:\\ProgramData\\docker\\windowsfilter\\ad4e6
30f0145b0a050f73069128388a33582c6882e095bdda47bc0f06d3f36b8"}],"HostName":"bcb52f2c6753","MappedDirectories":[],"HvParti
tion":false,"EndpointList":["5eb7b5c0-deb9-4227-875e-acd60ecb96bc"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.-->
```

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Also provide the exact version of Windows you're running if this is not visible in the output of `docker info`

**Comment by choochford** [comment]
Docker Version:
PS C:\Windows\system32> docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Windows\system32>
Docker info:
PS C:\Windows\system32> Docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: ALM-DEV-OPS
ID: OCRB:YNWC:M6HQ:JACI:S23S:4J62:ORDB:S4NM:RXJO:D6RJ:C5PV:XZ4W
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: choochford
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Windows Version:
PS C:\Windows\system32> [System.Environment]::OSVersion.Version
Windows 2016 server
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

Steps to reproduce
Run:  docker run -i microsoft/dotnet-framework:3.5

got this error only change was a upgrade to Windows 2016 server

C:\Program Files\Docker\docker.exe: Error response from daemon: container 95169b71c20d9f38b67618b24cd36d0d424f2d29ba2e62
16a07e8640f41a3246 encountered an error during CreateContainer: failure in a Windows system call: Incorrect function. (0
x1) extra info: {"SystemType":"Container","Name":"95169b71c20d9f38b67618b24cd36d0d424f2d29ba2e6216a07e8640f41a3246","Own
er":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{ed323ee3-39a6-11e7-9676-000c291eee2d}","IgnoreFlushesDuringBoot
":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\95169b71c20d9f38b67618b24cd36d0d424f2d29ba2e6216a07e86
40f41a3246","Layers":[{"ID":"d6036c81-5c04-5068-9dc1-0b544c5ab2e4","Path":"C:\\ProgramData\\docker\\windowsfilter\\62641
d3c7f63bbafdccc9859d5f5aaf3fde76538b9e30fb3580689f0f880d46f"},{"ID":"7e364718-13c9-5a7c-a1d3-a395e33d3320","Path":"C:\\P
rogramData\\docker\\windowsfilter\\1be6f0614b85626e3ec8d5a1cd6124755b75e65c7404b77773ef55f3ae713ec6"},{"ID":"5ac77583-da
3f-520c-b131-e9c6fb677b99","Path":"C:\\ProgramData\\docker\\windowsfilter\\ccda3460d899696d9ad76d327190d372c3f1e086cf140
dcb5dccd6d4a8f9e7ff"},{"ID":"60391f3d-ce8a-5640-97e1-8c8d651f9d80","Path":"C:\\ProgramData\\docker\\windowsfilter\\ad4e6
30f0145b0a050f73069128388a33582c6882e095bdda47bc0f06d3f36b8"}],"HostName":"95169b71c20d","MappedDirectories":[],"HvParti
tion":false,"EndpointList":["8cf15cae-8324-4e82-bc72-e561652496ba"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Comment by thaJeztah** [comment]
> got this error only change was a upgrade to Windows 2016 server

@friism @jstarks anything known about that? ^^

**Comment by S-YOU** [comment]
Just wondering what OS was before Windows 2016 server :)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
