### ISSUE TITLE
swarm mode: Task becomes unavailable in case of newer image in the registry

### ISSUE THREAD

**Issue by ascora** [moby/moby#33219]
**Description**

We got a docker swarm cluster running with 5 nodes - all on _v17.05.0-ce_.
For maintenance we marked a node as _docker node update --availability=drain node2_
All tasks where restarted on other nodes. 1 Task failed:
`no suuch image: registry:8444/group/gapi:latest@sha256:c15597d3...`
We then did a _docker service rm_ ... and a _docker service create_ and he task came up again. However, this time with
`registry:8444/group/gapi:latest@sha256:a9a8020ba...`

So I assume that the image has been rebuild in the registry under the latest tag and the old one with the old sha256 was replaced with a newer version.

However, why was docker failing instead of simply re-downloading the new `:latest` version? And how can we avoid that the task becomes unavailable in the future?

**Steps to reproduce the issue:**
1. re-build an image under the latest tag for a running container
2. drain a node

**Describe the results you received:**
Task became unavailable

**Describe the results you expected:**
New image downloaded and task started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
> So I assume that the image has been rebuild in the registry under the latest tag and the old one with the old sha256 was replaced with a newer version.

That would be very odd. The `@sha256` is an "immutable identifier"; a registry never deletes images, unless you manually [perform garbage collection](https://docs.docker.com/registry/garbage-collection/). _tags_ (such as `:latest`) can be overwritten, but the `@sha256` would persist after that. What kind of registry are you running?

> However, why was docker failing instead of simply re-downloading the new :latest version?

When deploying a service, and you did not specify an immutable identifier for the service's image (which is the recommended approach, as it puts you in control over _which_ version of the image you tested and want to deploy), docker resolves the tag you provided (e.g. `foobar:latest`) to its "digest" (immutable identifier). Doing so makes sure the _every_ instance ("task") of the service runs _exactly_ the same version of the image, which prevents unexpected behaviour (e.g. some tasks updated to a different version with different software running in it). If resolution _fails_ (e.g. the image was not found in a registry), docker will fall back to using the raw `image:tag` for the service.

After deploying, the digest is never updated, unless you _force_ an update (`docker service update --image foobar:latest --force <myservice>`)


> And how can we avoid that the task becomes unavailable in the future?

The first thing I'd be interested in is how the image with that digest could disappear from your registry;

- what registry are you running? The [docker open source registry](https://github.com/docker/distribution) (and what version), or a different registry?
- did you re-deploy the registry with fresh images?
- did you perform a garbage collect?

As mentioned above, you could force updating the image version using the steps I described (and have docker re-resolve the immutable digest)

**Comment by ascora** [comment]
We did indeed perform a  garbage collect about 2 days before. 

Unfortunately, I'm not sure if the service was started before or after the garbage collect. 

> what registry are you running? The docker open source registry (and what version), or a different registry?

We're using the Registry that is included in the latest GitLab. Invoking it returns:
# registry --version
registry github.com/docker/distribution v2.4.1

> did you re-deploy the registry with fresh images?

Yes.

> did you perform a garbage collect?

Yes. 

From your text above I assume that the service was started before the garbage collect and that the image was removed from the registry meaning that it could not be found when  the task failed.

Best regards,

Sven

**Comment by thaJeztah** [comment]
Thanks for the additional information.

> From your text above I assume that the service was started before the garbage collect and that the image was removed from the registry meaning that it could not be found when the task failed.

Yes, that sounds plausible indeed.

Based on the above, I don't see this as a bug, so I'll go ahead and close this, but feel free to continue the conversation 👍
