### ISSUE TITLE
shim error: while running docker run on xfs backingfs and overlay2 driver on master branch

### ISSUE THREAD

**Issue by imkin** [moby/moby#33243]
**Description**

I built the master branch and ran docker run -it ubuntu bash and I see the following error.

**Steps to reproduce the issue:**
1. Run make on master.
2. start docker daemon with --graph configured for a disk with xfs filesystem. and choose --storage-driver as overlay2
```
/mywork/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock --graph=/mywork/vfs --storage-driver=overlay2
```
3. 
```
docker run -it ubuntu bash
```

**Describe the results you received:**

```docker: Error response from daemon: shim error: json: cannot unmarshal object into Go value of type []string.```
**Describe the results you expected:**
Enter the bash of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
Used multiple versions of docker cli and it failed always with the dockerd on the master.
User multiple versions of docker cli and it always passed with 17.05.x branch dockerd.
**Output of `docker version`:**

```
Client:
 Version:      unknown-version
 API version:  1.30
 Go version:   go1.7.4
 Git commit:   dee8e6a
 Built:        Wed May 17 09:11:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   77c972884
 Built:        Wed May 17 08:57:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Fri Mar 31 02:35:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   77c972884
 Built:        Wed May 17 08:57:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 32
 Running: 0
 Paused: 0
 Stopped: 32
Images: 2
Server Version: 17.06.0-dev
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8ef7df579710405c4bb6e0812495671002ce08e0
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f (expected: 992a5be178a62e026f4069f443c6164912adbf09)
init version: N/A (expected: )
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.4-coreos-r1
Operating System: Container Linux by CoreOS 1367.5.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.792GiB
Name: coreos
ID: ENQG:VV7C:4IMI:VT2X:ILSI:P75J:ICG2:QW4M:W7XU:BKQ5:OJ3H:IEH2
Docker Root Dir: /mywork/vfs
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Coreos alpha

**Comment by thaJeztah** [comment]
Looks like you're running an incorrect version of runc (https://github.com/opencontainers/runc/commit/9df8b306d01f59d3a8029be411de015b7304dd8f instead of https://github.com/opencontainers/runc/commit/992a5be178a62e026f4069f443c6164912adbf09);

```
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f (expected: 992a5be178a62e026f4069f443c6164912adbf09)
```

The master branch switched to the 1.0-rc version of runc and containerd in https://github.com/moby/moby/pull/33007, so runc needs to match those versions

**Comment by thaJeztah** [comment]
I'll close this issue, because this looks to be due to an incorrect version of runc being used, but feel free to continue the discussion,  or ping me on the docker community slack channel
