### ISSUE TITLE
[17.07] prepare building for Fedora 26

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#33247]
Timing is awkward (again), but Fedora 26 will be released during the ~~17.06~~ 17.07 release, which means that people will upgrade / install Fedora 26 and will expect packages to be available :smile:

Current release date for Fedora 26 is set on [~~June 13, 2017~~ July 4th, 2017](https://fedoraproject.org/wiki/Releases/26/Schedule) (although it was shifted a couple of times)

**Also note:**
[Fedora 24 will be maintained until 1 month after the release of Fedora 26])(https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle#Maintenance_Schedule).

Official (beta) images for Fedora 26 are [not yet available on Docker Hub](https://hub.docker.com/_/fedora/) so we may have to build a temporary image for testing while it's not been released yet, like we did for Docker 1.13 / 17.03; https://github.com/moby/moby/issues/27500

ping @andrewhsu @runcom

**Comment by seemethere** [comment]
Relates to https://github.com/docker/for-linux/issues/35

**Comment by mmi-rperez** [comment]
@thaJeztah What's the status of this? Fedora 26 is out!

**Comment by seemethere** [comment]
Relates to https://github.com/docker/docker-ce-packaging/pull/31

@mmi-rperez ^

**Comment by seemethere** [comment]
Repo is officially up for fedora 26:

https://download.docker.com/linux/fedora/26/

@thaJeztah

**Comment by reypm** [comment]
@thaJeztah @seemethere so repo is officially up but ....

```bash
$ sudo dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo

$ sudo dnf config-manager --set-enabled docker-ce-edge

$ sudo dnf makecache fast
dnf makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer') => docs should be updated such option does not exists anymore "apparently"

$ sudo dnf update
Docker CE Stable - x86_64                                                                                                                                                          1.0 kB/s | 257  B     00:00    
Docker CE Edge - x86_64                                                                                                                                                            1.0 kB/s | 257  B     00:00    
Last metadata expiration check: 0:00:00 ago on Tue 15 Aug 2017 10:25:20 PM EDT.
Dependencies resolved.
Nothing to do.
Complete!

$ sudo dnf install docker-ce
Last metadata expiration check: 0:00:09 ago on Tue 15 Aug 2017 10:25:20 PM EDT.
No package docker-ce available.
Error: Unable to find a match
```

From [here](https://github.com/moby/moby/issues/34178):

```bash
$ curl -fsSL get.docker.com -o get-docker.sh
$ sed -i -E 's/(makecache) fast/\1/' get-docker.sh
$ chmod +x get-docker.sh 
$ sh get-docker.sh 
Executing docker install script, commit: 29533f9
get-docker.sh: line 442: [: TwentySix: integer expression expected
+ sudo -E sh -c 'dnf install -y -q dnf-plugins-core'
+ sudo -E sh -c 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/fedora/docker-ce.repo
+ '[' edge '!=' stable ']'
+ echo 'Info: Enabling channel '\''edge'\'' for docker-ce repo'
Info: Enabling channel 'edge' for docker-ce repo
+ sudo -E sh -c 'dnf config-manager --set-enabled docker-ce-edge'
+ sudo -E sh -c 'dnf makecache'
Last metadata expiration check: 0:00:00 ago on Tue 15 Aug 2017 10:27:45 PM EDT.
Metadata cache created.
+ sudo -E sh -c 'dnf install -y -q docker-ce'

$ sudo dnf install docker-ce
Last metadata expiration check: 0:00:15 ago on Tue 15 Aug 2017 10:27:45 PM EDT.
No package docker-ce available.
Error: Unable to find a match
```

Am I missing something here?

**Comment by IOAyman** [comment]
@reypm, Long story short, there has not been a build for Fedora 26, yet!  
See #34312.


## Work-around
You can use the Fedora 25 builds until the official builds for 26 are done.

This add a temporary repository pointing to the right packages location:
```bash
sudo cat > /etc/yum.repos.d/docker-ce-temp.repo << EOF
[docker-ce-tmp]
name=Docker CE Stable (TEMP) - $basearch
baseurl=https://download.docker.com/linux/fedora/25/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/fedora/gpg
EOF
```

_**Remember to delete it once the 26 builds are available.**_

**Comment by seemethere** [comment]
@IOAyman @reypm Fully aware Fedora 26 packages are not in the `stable` or `edge` channels. You can look for it in the `test` channel.

I personally recommend using the install script:
```shell
curl -fsSL test.docker.com | sh
```

**Comment by IOAyman** [comment]
@seemethere, I've seen the RCs. Right now, I prefer stable packages cuz I don't want to experience any misbehavior.

Thanks though :)

**Comment by seemethere** [comment]
Packages just went live for [17.07.0-ce](https://github.com/docker/docker-ce/releases/tag/v17.07.0-ce) for Fedora 26, this should be closed! ping @thaJeztah

**Comment by IOAyman** [comment]
@seemethere, ETA for the [stable](https://download.docker.com/linux/fedora/26/x86_64/stable/Packages/) repo?

**Comment by seemethere** [comment]
@IOAyman, 17.07 is not a stable release, the next stable release will occur for 17.09!

**Comment by jalberto** [comment]
so we have 17.07 but not 17.06 (stable version)?

**Comment by thaJeztah** [comment]
Docker packages for fedora 26 and 27 are now on https://download.docker.com/linux/fedora/, and the packaging scripts now live in https://github.com/docker/docker-ce-packaging, so closing this issue here
