### ISSUE TITLE
go get github.com/moby/moby/client is failing

### ISSUE THREAD

**Issue by ishantt** [moby/moby#33245]
**Description**

go get github.com/moby/moby/client is failing. This was working yesterday.

**Steps to reproduce the issue:**
1. go get github.com/moby/moby/client

**Describe the results you received:**

> ishant@ishant:~/gospace/src/github.com$ go get github.com/moby/moby/client
>  github.com/moby/moby/client
> moby/moby/client/config_create.go:12: undefined: types.ConfigCreateResponse
> moby/moby/client/config_create.go:12: undefined: swarm.ConfigSpec
> moby/moby/client/config_inspect.go:14: undefined: swarm.Config
> moby/moby/client/config_list.go:14: undefined: swarm.Config
> moby/moby/client/config_list.go:14: undefined: types.ConfigListOptions
> moby/moby/client/config_update.go:12: undefined: swarm.ConfigSpec
> moby/moby/client/container_wait.go:28: undefined: container.WaitCondition
> moby/moby/client/distribution_inspect.go:12: undefined: registry.DistributionInspect
> moby/moby/client/interface.go:184: undefined: swarm.Config
> moby/moby/client/interface.go:184: undefined: types.ConfigListOptions
> moby/moby/client/interface.go:184: too many errors
>

**Comment by aaronlehmann** [comment]
> `go get github.com/docker/docker/client`

Probably needs to be `go get -u github.com/docker/docker/client`

**Comment by ishantt** [comment]
@thaJeztah @aaronlehmann Thanks for the help.  go get -u github.com/docker/docker/client works for me.

**Comment by cpuguy83** [comment]
>  it still hangs today

What does this mean? This issue was never about hanging.
Hanging would more likely be some configuration issue on your system/network.

<details>

```
$ docker run -it --rm golang:1.10
root@0aeabbc9c5ec:/go# go get -u -v github.com/docker/docker/client
github.com/docker/docker (download)
github.com/docker/docker/api
github.com/docker/docker/api/types/events
github.com/docker/docker/api/types/versions
github.com/docker/docker/vendor/github.com/opencontainers/go-digest
github.com/docker/docker/api/types/blkiodev
github.com/docker/docker/api/types/mount
github.com/docker/docker/api/types/strslice
github.com/docker/docker/vendor/github.com/docker/go-connections/nat
github.com/docker/docker/vendor/github.com/docker/go-units
github.com/docker/docker/api/types/filters
github.com/docker/docker/vendor/github.com/docker/distribution/digestset
github.com/docker/docker/errdefs
github.com/docker/docker/api/types/container
github.com/docker/docker/vendor/github.com/docker/distribution/reference
github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go
github.com/docker/docker/api/types/network
github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1
github.com/docker/docker/vendor/github.com/gogo/protobuf/proto
github.com/docker/docker/api/types/registry
github.com/docker/docker/api/types/image
github.com/docker/docker/api/types/time
github.com/docker/docker/vendor/golang.org/x/net/internal/socks
github.com/docker/docker/vendor/github.com/pkg/errors
github.com/docker/docker/vendor/golang.org/x/net/context
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp
github.com/docker/docker/vendor/github.com/docker/go-connections/tlsconfig
github.com/docker/docker/vendor/golang.org/x/net/proxy
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets
github.com/docker/docker/api/types/swarm/runtime
github.com/docker/docker/api/types/swarm
github.com/docker/docker/api/types
github.com/docker/docker/api/types/volume
github.com/docker/docker/client
root@0aeabbc9c5ec:/go#
```

</details>

**Comment by cpuguy83** [comment]
@davidkhala Are you sure it's not actually downloading? This repo is large with a lot of history.

I doubt there would be another issue open.

**Comment by davidkhala** [comment]
@cpuguy83 Thanks for you reminds and you are correct, I do see the size of `.git` directory grows along time. And I have measured a totally 3 minutes is required in my network environment.

**Comment by leslie-qiwa** [comment]
Today, when I ran `go get github.com/moby/moby/client`
```
 $ go get github.com/moby/moby/client
can't load package: package github.com/moby/moby/client: code in directory /go/src/github.com/moby/moby/client expects import "github.com/docker/docker/client"
```
For the sample code like
```
package main

import (
        "github.com/moby/moby/api/types"
        "github.com/sirupsen/logrus"
)

func main() {
        logrus.Println(types.ContainerListOptions{})
}
```
It has error `main.go:4:2: code in directory /go/src/github.com/moby/moby/api/types expects import "github.com/docker/docker/api/types"`

We used to use `gitHub.com/docker/docker/...`, but today when we update mod with `GO111MODULE=on go mod vendor`, it starts generating 'go: github.com/Sirupsen/logrus@v1.4.1: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"', which seems like many related posts. I thought move to `moby/moby` may solve it, but seems like it has this issue.

**Comment by thaJeztah** [comment]
`go modules` unfortunately gets confused by old tags in this repository, and therefore will pick the latest tag it finds that "looks like semver". To prevent that from happening, you'll have to specify a pseudo version in your go.mod, and specify the commit you want to vendor. You can find an example in the BuildKit repository; https://github.com/moby/buildkit/blob/ac18391f2b29c73e0c87cafea8cb63e0c3ac6501/go.mod#L12

**Comment by leslie-qiwa** [comment]
Thanks for the quick reply! Seems like you are right. Below simple fix solves my issue.

Just side question, should we migrate to `moby/moby` or still use existing `docker/docker` APIs?

```
--- a/go.mod
+++ b/go.mod
@@ -85,9 +85,10 @@ require (
-       github.com/sirupsen/logrus v1.0.6 // indirect
+       github.com/sirupsen/logrus v1.0.6
```

**Comment by thaJeztah** [comment]
> Below simple fix solves my issue.

The fix will likely only "taper over" the problem, as I think you'd still be using the old (1.13) codebase, but only forcing use of the new version of logrus.

> should we migrate to moby/moby or still use existing docker/docker APIs?

You ned to use docker/docker for the imports

**Comment by leslie-qiwa** [comment]
Thanks for the reply. It is clear for me.

**Comment by RexG** [comment]
> @cpuguy83 Thanks for you reminds and you are correct, I do see the size of `.git` directory grows along time. And I have measured a totally 3 minutes is required in my network environment.

Thanks @davidkhala , same issue for me; have to be patient next time..

**Comment by theonlineaid** [comment]
We resolve the `undefined: types.ContainerListOptions` issue in Go, which often arises from using an incompatible Docker SDK version, follow these steps:

1. **Update the Docker SDK**: First, make sure you’re using a Docker SDK version that includes `ContainerListOptions`. To update the SDK to the latest version, run:
   ```bash
   go get -u github.com/docker/docker/api@latest
   ```
   This will pull the latest compatible SDK version with `ContainerListOptions` available.

2. **Use a Specific Version if Needed**: If the latest version doesn’t work for your project, you can install a stable, known compatible version, such as:
   ```bash
   go get github.com/docker/docker/api@v20.10.22
   ```
   This command installs a specific SDK version with the required `ContainerListOptions` type.

3. **Run `go mod tidy` to Clean Dependencies**: Once the SDK is updated, use:
   ```bash
   go mod tidy
   ```
   This command will remove any unused imports from `go.mod` and `go.sum`, add any missing ones, and ensure your project’s dependencies are in order.

After completing these steps, try running your code again. This should resolve the `undefined: types.ContainerListOptions` error, allowing Go to recognize and use `ContainerListOptions`.
