### ISSUE TITLE
docker run: GCE n1-standard-64 apparently slower than n1-standard-1

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#33254]
**Description**

GCE `n1-standard-64` (64 vCPUs, 240GB RAM) is apparently slower than `n1-standard-1` (1 vCPU, 3.75GB RAM).

Haven't tested other IaaSes nor bare metal, but I believe the issue shouldn't be specific to GCE.
So let me report the issue here 😅 

**Steps to reproduce the issue:**

Create Docker Machines with Docker Machine v0.11.0:
```
$ docker-machine create --google-machine-type n1-standard-1 --engine-storage-driver overlay2 tmp-n1-standard-1-overlay2
$ docker-machine create --google-machine-type n1-standard-64 --engine-storage-driver overlay2 tmp-n1-standard-64-overlay2
$ docker-machine create --google-machine-type n1-standard-1 --engine-storage-driver aufs tmp-n1-standard-1-aufs
$ docker-machine create --google-machine-type n1-standard-64 --engine-storage-driver aufs tmp-n1-standard-64-aufs
```

As of writing, Docker Machine creates Ubuntu 16.04.1 (kernel 4.4.0-51-generic) instances, with Docker 17.05.0-ce.

Then SSH into each of these instances, and execute the following script:

```bash
#!/bin/bash
TIMES=100

IMAGE=busybox
TIMELOG=TIMES=$TIMES,$(docker info --format Name={{.Name}},Driver={{.Driver}}).log
TIMEFORMAT=%R

docker inspect $IMAGE 2>&1 > /dev/null || docker pull $IMAGE
rm -f $TIMELOG
for f in $(seq 1 $TIMES);do
    echo -n "Test $f of $TIMES: "
    { time docker run --rm $IMAGE true; } 2>&1 | tee -a $TIMELOG
done
```

It is important _not_ to execute Docker client against remote daemon, so that network bandwidth won't affect the result.

**Describe the results you received:**

Raw data:  [test.zip](https://github.com/moby/moby/files/1008393/test.zip)

Host | Mean (seconds) | Median | Min | Max | Q3
--- | --- | --- | --- | --- | ---
`tmp-n1-standard-1-overlay2` | 0.27581 | 0.271 |  0.24 |   0.338 |  0.28225
`tmp-n1-standard-64-overlay2` | 0.53849 | 0.54 |   0.462 |  0.592 |  0.55925
`tmp-n1-standard-1-aufs` | 0.27533 | 0.275 |  0.257  | 0.309 |  0.28025
`tmp-n1-standard-64-aufs` | 0.5672 | 0.564  | 0.511 |  0.637 |  0.58475

Needless to do statistical hypothesis testing, `n1-standard-64` is apparently slower than `n1-standard-1`, for both `overlay2` and `aufs`.

So the issue seems unrelated to filesystems. (Or both `overlay2` and `aufs` are affected)

Not sure Docker issue, kernel issue, or GCE issue yet.

**Describe the results you expected:**

`n1-standard-64` should not be slower than `n1-standard-1`.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue might be important for a case where a bunch of containers are created & destroyed very frequently. (e.g. FaaS)

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

(on `tmp-n1-standard-1-overlay2`)

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-51-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613GiB
Name: tmp-n1-standard-1-overlay2
ID: G2QM:TIWW:BNSG:MOTW:RDNI:MGYZ:5E4Z:QZYV:A6KA:XVTU:GIE6:75ZN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=google
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- GCE region:`asia-northeast1-a`
- Reported CPU type in GCE console: "Intel Broadwell"
- GCE Disk type: "Standard persistent disk"

**Comment by thaJeztah** [comment]
@AkihiroSuda related to https://github.com/golang/go/issues/15395 and https://github.com/moby/moby/issues/25259 ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
