### ISSUE TITLE
Zsh completion for "docker run" doesn't treat "--volume" same as "-v"

### ISSUE THREAD

**Issue by FranklinYu** [moby/moby#33258]
### Description

[Docker completion for Zsh](https://github.com/moby/moby/blob/master/contrib/completion/zsh/_docker) doesn't work correctly when `--volume` is involved. `-v` works as expected.

### Steps to reproduce
1. Prepare some images (pull, build, and so on)
2. In Zsh `docker run --volume $HOME:/foobar` and a space.
3. Hit <kbd>Tab ⇥</kbd>.

### The results I received
I saw all the files and folders in current directory.

### The results I expected
I shall see all my images, as what I see with `docker run -v $HOME:/foobar`.

### Output of `docker version`

```text
Docker version 17.05.0-ce, build 89658bed64
```

### Output of `docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.10.13-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.776GiB
Name: Theia
ID: G5JJ:WVNE:W4QA:N27D:3FLF:PNUQ:MTIT:UC7G:FFJL:SE65:T2O5:UBGE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Additional environment details

I'm not using Oh-My-Zsh or any other third-party Zsh tools; only the settings that come with Zsh.

**Comment by thaJeztah** [comment]
ping @sdurrheimer PTAL

**Comment by franklinyu** [comment]
Any updates?

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it. The completion script are now maintained in https://github.com/docker/cli.
