### ISSUE TITLE
duplicate /dev/shm mounts being added when performing restart.

### ISSUE THREAD

**Issue by jrivera-px** [moby/moby#33256]
**Description**
Additional /dev/shm mounts are being added for each when the container is restarted.   This only seems to occur when using using a shared mounts.  

**Steps to reproduce the issue:**
1.  Start busybox container in daemon mode with shared mount and restart=always option:
 
sudo /usr/bin/docker run --restart=always --name bshell -d -v /dev:/dev -v /tmp/common:/common:shared busybox;

**Describe the results you received:**

Query mounts on the existing system and see the additional /dev/shm mounts being added as the busybox container exits and restarts (count increases):

while [ 1 ]; do mount | egrep '/dev/shm'; mount | egrep '/dev/shm'| wc -l; echo "----"; sleep 1; done 

**Describe the results you expected:**
Only 1 /dev/shm should be present and reused.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: centos73-1
ID: DVIC:JIGZ:URLP:IMVW:EUKA:VYXX:AM7H:Y22G:TWTX:7FRF:5XDP:IYCQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox instance.

**Comment by thaJeztah** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
I cannot reproduce this on moby linux (docker4mac) (kernel 4.9), but can on centos (kernel 3.10).

**Comment by cpuguy83** [comment]
It might actually be happening because the root mount on centos is shared.
So when you `-v /dev:/dev` and the container's `/dev/shm` is mounted, it's making it back into the host.

**Comment by thaJeztah** [comment]
@cpuguy83 would changing to `slave` resolve this issue? https://github.com/moby/moby/pull/31490

**Comment by cpuguy83** [comment]
Actually I think #32851 would resolve this for people with a shared root mount.
Would be helpful if someone can test with 17.06-rc1.

**Comment by harsh-px** [comment]
We can try it out. When can we get hold of 17.06-rc1? I don't it in the releases right now.

**Comment by cpuguy83** [comment]
@harsh-px rc2 is already out!

**Comment by ssboisen** [comment]
Just tested on 17.06-rc2 and I were NOT able to reproduce the problem reported by @harsh-px - on 17.05.0-ce I could reproduce it.
