### ISSUE TITLE
Ingress network from older versions is erroneously removed on `docker network prune`

### ISSUE THREAD

**Issue by dperny** [moby/moby#33259]
**Description**

Doing `docker network prune` removes the ingress network if it is not currently being used, and it was created on an older version.

**Steps to reproduce the issue:**
<strike>
1. `docker network prune`
2. try to create service that uses ingress network
</strike>

See below: https://github.com/moby/moby/issues/33259#issuecomment-302252274

**Describe the results you received:**

Ingress network is gone

**Describe the results you expected:**

Ingress network should not be deleted.

[I don't know what I expected](http://i0.kym-cdn.com/photos/images/newsfeed/000/617/851/56d.gif)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1197
Server Version: 17.05.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1008
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: wymf3aau8jhl8rnbwajou3421
 Is Manager: true
 ClusterID: u77uiync8qrec2zvbnbzf0iv7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.21-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: IJDB:XKO7:BYSL:RIBX:DN3F:VFCX:6BUA:QZA3:WZXA:ALWV:PKDQ:7FC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 257
 System Time: 2017-05-17T21:57:04.327922388Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: dperny
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac

**Comment by thaJeztah** [comment]
Odd, it looks like there's something in place to prevent this, but apparently doesn't actually do.. 
https://github.com/moby/moby/blob/d6b16508253df96c89025c9ecbd0698f2d909ee7/daemon/prune.go#L364-L367

@dperny perhaps you're interested in giving it a quick look yourself?

**Comment by dperny** [comment]
I can't reproduce now. Maybe there was some weird hold-over stuff from an older version.

**Comment by dperny** [comment]
Here is my guess for what happened:

My laptop has been a swarm cluster for many moons, possibly before the change adding the `Ingress` bool to the `NetworkResource` struct in `api/types/types.go`. I think that maybe this old network from the beforetimes may have had that flag set to false, and so, when I pruned old networks, the ingress network got nuked. This is my best guess as to how this could have happened, but I don't have any data to back it up, it's just rough speculation.

**Comment by thaJeztah** [comment]
Sounds plausible; I think that's something we should address somehow, because upgrading from a previous version is something we need to take into account. Perhaps we should hard-code the `ingress` name here

Alternatively, have an upgrade step (loop through networks, and if no network has the `Ingress` boolean set to true, then pick the network named `ingress` and set `Ingress` to true for that one?)

This makes up for a good test for our e2e suite though :)

**Comment by thaJeztah** [comment]
@sanimej ^^ wdyt?

**Comment by dperny** [comment]
Reproduction steps, using docker in docker:

1.) Check out 17.03.x
2.) Build and start docker daemon.
3.) `docker swarm init`. 
4.) Verify that `ingress` exists
5.) Stop docker.
6.) Check out 17.05.x. Build and start.
7.) Verify that ingress is still there, docker is still in swarm mode
8.) `docker network prune`.
9.) `Ingress` is deleted

Of note: `docker network inspect` on the upgraded ingress network yields this:
```json
[
    {
        "Name": "ingress",
        "Id": "bhiyuapcxjm4tw0tchh4wo9ad",
        "Created": "2017-05-17T22:40:34.461750382Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": true,
        "Containers": {
            "ingress-sbox": {
                "Name": "ingress-endpoint",
                "EndpointID": "3c49927286eca9358b0b20ceee47965fa4a00e5c57c9479b6c6adc1ee655b4ce",
                "MacAddress": "02:42:0a:ff:00:03",
                "IPv4Address": "10.255.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4096"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "50d1256118b6-829fe15ccd1e",
                "IP": "172.17.0.2"
            }
        ]
    }
]
```

Which indicates that the network is an ingress network. However, it is still deleted on `docker network prune`.

**Comment by dperny** [comment]
Updated the title to reflect the true problem.

**Comment by thaJeztah** [comment]
Thanks for investigating; so we should debug why it's skipping that check; adding a priority label to this one, because people _will_ hit this if they have a cronjob cleaning up things; we should fix during feature/code-freeze

**Comment by dperny** [comment]
The tricky part, that I don't understand, is why does the network inspect show that

```
"Ingress": true
```

but then when the prune runs, `nw.Ingress` is for some reason false?
