### ISSUE TITLE
Splunk logging driver should have an option to directly limit POST size

### ISSUE THREAD

**Issue by nickperry** [moby/moby#33268]
**Description**

The Splunk logging driver currently has 4 tunables for coalescing behaviour -
 SPLUNK_LOGGING_DRIVER_POST_MESSAGES_FREQUENCY, SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE, SPLUNK_LOGGING_DRIVER_BUFFER_MAX and SPLUNK_LOGGING_DRIVER_CHANNEL_SIZE.

None of the above give a direct way of impedance matching against the server side HEC limits.conf tunable 
[http_input]
max_content_length

This can make it difficult to avoid getting 413 responses and disrupting the services. I do not particularly want to accept the Splunk 6.5+ 800MB of max_content_length. Our site currently enforces 10MB (a 10x increase on the Splunk 6.4 default).

It would be useful to add an additional paramater SPLUNK_LOGGING_DRIVER_POST_SIZE_MAX. I am unsure how feasible this is and how it would interact with GZIP compression.

**Steps to reproduce the issue:**
1. Set max_content_length on HEC to a value x.
2. Flush log lines in a docker container at a size and rate that causes a POST of size > x. It will be necessary to make the lines suitably large such that you exceed x within the SPLUNK_LOGGING_DRIVER_POST_MESSAGES_FREQUENCY window (default 5s) and without breaching SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE.
3. Monitor Docker daemon logs for the 413 error.

**Describe the results you received:**
HTTP 413 errors

**Comment by nickperry** [comment]
I would also be interested in an option to configure how 413s are handled, so a container owner could elect to accept loss of the log data instead of blocking the application. The 413 response would still be logged to the Docker daemon log so they could be alerted to the fact they are losing logs.

**Comment by cpuguy83** [comment]
Looking at the code I'm wondering why `SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE` isn't want you need here?

If you are ok with dropping logs then you should look at the option `--log-opt mode=non-blocking` which works with any log driver.

**Comment by nickperry** [comment]
SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE is described as 'How many messages driver should wait before sending them in one batch'. The length of each message is not fixed so the byte length of the resulting batch in can vary massively.

**Comment by cpuguy83** [comment]
@nickperry The absolute max size of any message is 16K.

**Comment by cpuguy83** [comment]
So the splunk driver sends the queued messages over once the batch size is met, or once the max buffer size is reached.
However, it seems like this code might be improved by checking for max buffer size here: https://github.com/moby/moby/blob/master/daemon/logger/splunk/splunk.go#L402

**Comment by nickperry** [comment]
@cpuguy83 am I right in thinking the Splunk driver doesn't act upon the partial flag?

**Comment by outcoldman** [comment]
@nickperry that is correct, it does not handle `partial` flag. That means that maximum batch size is limited by `SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZE * 16k`, where `16k` is the maximum log message line, chunked by docker core. As I recall the only driver which handles `Partial` flag is the `json-files`. For all other drivers, which work over the network it is not trivial to solve that, especially in consistent way.
If you need more guarantees - the best way is to use `json-files` with forwarder.

**Comment by nickperry** [comment]
Thanks @outcoldman @cpuguy83. Considering the addition of --log-opt mode=non-blocking and now understanding the SPLUNK_LOGGING_DRIVER_POST_MESSAGES_BATCH_SIZEx16KB upper bound, I am happy with the situation.
