### ISSUE TITLE
Error Log Entry Not an Error

### ISSUE THREAD

**Issue by erikbgithub** [moby/moby#33265]
**Description**

Most of my log messages in journalctl for docker look like this:
```
May 17 14:03:52 ubuntu dockerd[1218]: time="2017-05-17T14:03:52.516696535+02:00" level=error msg="Handler for POST /v1.24/containers/f40060df67ef8e41b57d7b77dd6cb332fdaa1766a11b286b7d02a6542698f913/stop returned error: Container f40060df67ef8e41b57d7b77dd6cb332fdaa1766a11b28 is already stopped"
```

**Steps to reproduce the issue:**
1. Use Ubuntu 16.04
2. Install Kubernetes with kubeadm
3. `journalctl -l -u docker`

**Describe the results you received:**
The message implies that kubernetes calls a docker API method "stop" on an object that is either already stopped or non existant any more. This situation is logged as an *error*.

**Describe the results you expected:**
Docker runs perfectly (I presume from the info I'm given). It's just that someone calls the API to achieve something that they already achieved. I expected to not see this at all, or see it as a warning or debug message. An *error* means that dockerd is dying or barely avoided dying and needs something to get fixed immediately.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 40
 Running: 27
 Paused: 0
 Stopped: 13
Images: 18
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-51-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.84 GiB
Name: ubuntu
ID: 5R2P:HRWW:CZ3Q:4SMI:YACY:3GUS:KQGW:H4BG:ALD5:SNLZ:46B3:RTYS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy:8080/
Https Proxy: http://proxy:8080/
No Proxy: <lots of company internal exceptions>
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Proxy in company network, but that can already be seen in `docker info`

**Comment by thaJeztah** [comment]
I think this is (partially) fixed by https://github.com/moby/moby/pull/46213

Let me close this ticket for now, as it looks like it went stale.
