### ISSUE TITLE
Clair configuration:failed to load configuration: could not load configuration: no database source specified 

### ISSUE THREAD

**Issue by liuyihe111** [moby/moby#33288]
**Description**
I want to use Docker to install Clair on CentOS 7 , and my configuration steps as follows: 

**Steps to reproduce the issue:**
1.$docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
2.$ mkdir /root/clair_config
$ curl -L https://raw.githubusercontent.com/coreos/clair/master/config.example.yaml -o /root/clair_config/config.yaml
vim /root/clair_config/config.yaml
changes this line : source: postgresql://postgres:mysecretpassword@postgres:5432?sslmode=disable
3$.docker run -d --name clair-test --link some-postgres:postgres -p 6060-6061:6060-6061 -v /root/clair_config:/config quay.io/coreos/clair -config=/config/config.yaml
Then I checked the log of this container clair-test, but return the errors as follow :
**Describe the results you received:**
2017-05-19 02:58:53.972239 C | main: failed to load configuration: could not load configuration: no database source specified

**Describe the results you expected:**
I want to know the reason of this results, and what to do to solve this problem?

**Output of `docker version`:**

[root@master ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

**Output of `docker info`:**
[root@master ~]# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-51842483-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.615 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.64 GB
 Metadata Space Used: 3.023 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 976.5 MiB
Name: master
ID: SCUG:B3JW:GD7X:EKOO:TSD4:DPJA:MVGU:BS3C:GSV7:5RGO:6P2H:LG4I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 registry:5000
 127.0.0.0/8
Registries: docker.io (secure)

**Comment by cpuguy83** [comment]
Hello,

This is the issue tracker for issues with docker. It's not well suited for support, and particularly support for applications outside of the scope of Docker itself.
I suggest checking out either the [Docker forums](https://forums.docker.com), or the community slack.

Closing since this isn't really a Docker issue.
Thanks! 🙇
