### ISSUE TITLE
enhancement: docker stack rm should ask for confirmation

### ISSUE THREAD

**Issue by palmerabollo** [moby/moby#33282]
**Description**

`docker stack rm` is a destructive operation that doesn't ask for confirmation. This is error prone.
This command should ask for confirmation and, perhaps, include a `--force` flag for those who do not want to see the confirmation prompt (ex. a script).

**Output of `docker version`:**

```
Docker version 17.05.0-ce-rc1, build 2878a85
```

**Comment by ripcurld0** [comment]
it seems legit but related to docker/cli.
WDYT @thaJeztah ?

**Comment by ripcurld0** [comment]
I guess I can work on this.
calling #dibs

**Comment by thaJeztah** [comment]
Oh, I thought I left a comment (I must've forgotten to send it); I understand where you're coming from, on the other hand, both `docker-compose down` (i.e. when not using `docker stack`), services themselves, or other docker commands (`docker service rm`, `docker service scale`, `docker image rm`, `docker volume rm`) don't ask for confirmation, so I wonder if we should make an exception for this one.

Note that `docker stack rm` does remove _services_, but keeps named volumes around (given that those contain stageful data)

**Comment by thaJeztah** [comment]
Closing this for now, per the discussion on https://github.com/docker/cli/issues/125
