### ISSUE TITLE
Ports are not published successfully to all hosts in the cluster

### ISSUE THREAD

**Issue by minhkct** [moby/moby#33287]
**Description**

- I setup Swarm cluster which has 1 leader and 1 worker node. 

- Created several services using docker stack (docker compose). Each service has 1 replica. Each service has 2 published ports: For example, service A 8443 => 10100, 9718 => 10101, service B 8443 => 10200, 9718 => 10201

- When the stack is deployed, I expected routing mesh should work which mean I can access to hostA or hostB with the same port and it should return the response. If I have 10 services, most of services work perfectly but not all. For some services, i was able to access the service at one host only not both which means routing mesh didn't work perfectly. 

- Every time I restart the stack, it can happen to different service. It doesn't always happen to some specific service.

**Steps to reproduce the issue:**
1. Setup swarm cluster which has 1 leader and 1 worker node
2. Start 10 services by using $sudo docker stack deploy... (or even when using $sudo docker service create... to start individual services)

**Describe the results you received:**
For few services, for example, serviceA, I was able to access https://hostA.com:10101, but failed in access https://hostB.com:10101

**Describe the results you expected:**
I should be able to access all services when using hostA.com or hostB.com with the service's published port. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:09:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 20:09:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 200
Server Version: 17.03.1-ee-3
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: sd65p0ikt7z19y6brw43gkp41
 Is Manager: true
 ClusterID: i2v7ugmb5z68pu4s3qwry255x
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.150.107
 Manager Addresses:
  192.168.150.107:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.686 GiB
Name: evsqtdoce101.sequentsw.com
ID: 2FFB:NXAJ:CMN4:44HF:5TDX:7E4W:MMXP:3YAU:QD66:MUGI:MJJK:U2PH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 105
 Goroutines: 205
 System Time: 2017-05-19T01:36:35.717130232Z
 EventsListeners: 5
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
-bash-4.2$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

-bash-4.2$ ls -la /boot
total 195244
dr-xr-xr-x.  3 root root     4096 May  3 17:35 .
dr-xr-xr-x. 20 root root     4096 May  3 17:35 ..
-rw-r--r--   1 root root   137701 Feb 20 07:48 config-3.10.0-514.10.2.el7.x86_64
-rw-r--r--   1 root root   137701 Mar 10 18:30 config-3.10.0-514.16.1.el7.x86_64
-rw-r--r--.  1 root root   137696 Oct 19  2016 config-3.10.0-514.el7.x86_64
drwx------.  6 root root      146 May  3 17:14 grub2
-rw-------.  1 root root 50831521 Apr 18 19:03 initramfs-0-rescue-2f7f213e37d04dd9b188e401e5b05ea0.img
-rw-------   1 root root 20137563 Apr 18 19:17 initramfs-3.10.0-514.10.2.el7.x86_64.img
-rw-------   1 root root 18531171 Apr 18 19:19 initramfs-3.10.0-514.10.2.el7.x86_64kdump.img
-rw-------   1 root root 20325397 May  3 17:14 initramfs-3.10.0-514.16.1.el7.x86_64.img
-rw-------   1 root root 18614400 May  3 17:35 initramfs-3.10.0-514.16.1.el7.x86_64kdump.img
-rw-------   1 root root 20139371 Apr 18 19:17 initramfs-3.10.0-514.el7.x86_64.img
-rw-------   1 root root 18519929 Apr 18 19:06 initramfs-3.10.0-514.el7.x86_64kdump.img
-rw-r--r--.  1 root root   612534 Apr 18 19:01 initrd-plymouth.img
-rw-r--r--   1 root root   277969 Feb 20 07:51 symvers-3.10.0-514.10.2.el7.x86_64.gz
-rw-r--r--   1 root root   277943 Mar 10 18:35 symvers-3.10.0-514.16.1.el7.x86_64.gz
-rw-r--r--.  1 root root   277953 Oct 19  2016 symvers-3.10.0-514.el7.x86_64.gz
-rw-------   1 root root  3112473 Feb 20 07:48 System.map-3.10.0-514.10.2.el7.x86_64
-rw-------   1 root root  3113648 Mar 10 18:30 System.map-3.10.0-514.16.1.el7.x86_64
-rw-------.  1 root root  3113253 Oct 19  2016 System.map-3.10.0-514.el7.x86_64
-rwxr-xr-x.  1 root root  5391264 Apr 18 19:03 vmlinuz-0-rescue-2f7f213e37d04dd9b188e401e5b05ea0
-rwxr-xr-x   1 root root  5391456 Feb 20 07:48 vmlinuz-3.10.0-514.10.2.el7.x86_64
-rw-r--r--   1 root root      171 Feb 20 07:48 .vmlinuz-3.10.0-514.10.2.el7.x86_64.hmac
-rwxr-xr-x   1 root root  5394272 Mar 10 18:30 vmlinuz-3.10.0-514.16.1.el7.x86_64
-rw-r--r--   1 root root      171 Mar 10 18:30 .vmlinuz-3.10.0-514.16.1.el7.x86_64.hmac
-rwxr-xr-x.  1 root root  5391264 Oct 19  2016 vmlinuz-3.10.0-514.el7.x86_64
-rw-r--r--.  1 root root      166 Oct 19  2016 .vmlinuz-3.10.0-514.el7.x86_64.hmac

**Comment by minhkct** [comment]
I tried stopping firewall and restart docker but it didn't help. 
I also tried turning on debug mode and found some info:

`May 19 00:59:04 evsqtdoce101 audispd: node=evsqtdoce101.sequentsw.com type=EOE msg=audit(1495155544.993:6045):
May 19 00:59:06 evsqtdoce101 audispd: node=evsqtdoce101.sequentsw.com type=NETFILTER_CFG msg=audit(1495155546.603:6046): table=filter family=2 entries=56
May 19 00:59:06 evsqtdoce101 dockerd: time="2017-05-19T00:59:06.605480792Z" level=error msg="Failed to add ingress: setting up rule failed, [-I DOCKER-INGRESS -m state -p tcp --sport 10601 --state ESTABLISHED,RELATED -j ACCEPT]: do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted\n (<nil>)"
May 19 00:59:06 evsqtdoce101 audispd: node=evsqtdoce101.sequentsw.com type=SYSCALL msg=audit(1495155546.603:6046): arch=c000003e syscall=54 success=yes exit=0 a0=4 a1=0 a2=40 a3=124cef0 ite`

**Comment by minhkct** [comment]
Before switching to Docker EE, i used CS Docker Engine 1.13.1 (RHEL 7.x and CentOS 7) and had the same issue. I thought it's about version problem so tried using Docker EE but nothing changed.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
