### ISSUE TITLE
Creating a service with http routing mesh via CLI, the network (ucp-hrm) is not attached 

### ISSUE THREAD

**Issue by bizdevxyz** [moby/moby#33283]
**Description**
When trying to create a service with http routing mesh via CLI, the network (ucp-hrm) is not attached or visible in the UI. However running docker service inspect shows the network there. You are not able to modify the service due to network not being available. If you create the service via the UI it functions properly as expected.

**Steps to reproduce the issue:**
1. Enable HTTP routing mesh (HRM). 
2. Via the CLI, create a new service, referencing ucp-hrm as the network.
3. Check the newly created service via the UI, you will see the network is not attached and there are errors on the first page

**Describe the results you received:**
Service is created and ucp-hrm is not attached

**Describe the results you expected:**
Service is created with ucp-hrm attached

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently

**Output of `docker version`:**
```
[root@ucp1 ~]# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**
```
[root@ucp1 ~]# docker info
Containers: 14
 Running: 11
 Paused: 0
 Stopped: 3
Images: 16
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: johowob89hymgyx3djr0t3n77
 Is Manager: true
 ClusterID: l8ozvzflis83mu5j4icu96df6
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://192.168.0.89:12381/api/v1/cfssl/sign
 Node Address: 192.168.0.89
 Manager Addresses:
  192.168.0.89:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.924GiB
Name: ucp1.localdomain
ID: 5I23:XL4J:73Y5:QUNW:RV5Q:5V44:CIBW:5OTP:VFIM:Z2JE:IDXV:4SA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7.3x VMs running on physical

**Comment by thaJeztah** [comment]
> the network (ucp-hrm) is not attached or visible in the UI

With the UI, you mean Docker Data Center / UCP?

If so, and you have an active support license, please open a ticket through support (support@docker.com), as Docker Data Center is not an open-source product, and support not handled through this issue tracker.

Be aware though, that Docker Data Center is only supported when running on Docker Enterprise Edition (EE), and it looks like you're running on a Community Edition "edge" release

**Comment by parrisvarney** [comment]
Is the HTTP routing mesh (HRM) functionality only available through UCP dashboard, or can it be enabled via Community Edition?

**Comment by thaJeztah** [comment]
@parrisvarney yes the HTTP routing mesh is part of the commercial offerings / UCP; see https://docs.docker.com/datacenter/ucp/2.1/guides/user/services/use-domain-names-to-access-services/, not available in Docker CE itself.

I'm closing this issue because there's nothing actionable here
