### ISSUE TITLE
DockerSwarmSuite.TestSwarmClusterEventsSecret is failing

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#33285]
Seen failing on  https://github.com/moby/moby/pull/33280 (https://jenkins.dockerproject.org/job/Docker-PRs/42925/console) and https://github.com/moby/moby/pull/33261 (https://jenkins.dockerproject.org/job/Docker-PRs-s390x/2994/console)

```
23:59:44 ----------------------------------------------------------------------
23:59:44 FAIL: docker_cli_swarm_test.go:2197: DockerSwarmSuite.TestSwarmClusterEventsSecret
23:59:44 
23:59:44 [d5ecaf060bb69] waiting for daemon to start
23:59:44 [d5ecaf060bb69] daemon started
23:59:44 
23:59:44 docker_cli_swarm_test.go:2219:
23:59:44     c.Assert(out, checker.Contains, "secret remove "+id)
23:59:44 ... obtained string = ""
23:59:44 ... substring string = "secret remove ofztf6uqeeepgtsnyntmz6ebt"
23:59:44 
23:59:44 [d5ecaf060bb69] exiting daemon
23:59:58 
23:59:58 ----------------------------------------------------------------------
```

ping @dongluochen

**Comment by dongluochen** [comment]
I think it's a race condition. The swarm events are generated by collecting raft store changes thru Watch API. The processing of raft changes is independent of the real change in store. While the command has been done, the events could be delayed. 

The fix should be to wait for the events with several retries. I'll prepare a PR.

**Comment by dmp42** [comment]
@mavenugo is this a blocker?

**Comment by dongluochen** [comment]
The event function should be all right. This is just a test problem. I'll get a PR by tomorrow.

**Comment by mavenugo** [comment]
@dmp42 no. this isnt a blocker.

**Comment by dongluochen** [comment]
@thaJeztah I think #33307 is ready for merge.
