### ISSUE TITLE
Cannot resolve DNS of host within windows container

### ISSUE THREAD

**Issue by JacobPoldenValtech** [moby/moby#33297]
**Description**
When trying to ping a website eg "google.com" within a container, an error is returned indicating the inability to connect. When using an IP address, a connection can be made.

**Steps to reproduce the issue:**
1. docker run -it microsoft/windowsservercore
2. ping google.com

Response back from the command is as follows: "Ping request could not find host google.com"

**docker version**

Docker version:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true

**docker info**

Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 2
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.83 GiB
Name: VTUKJacob
ID: GKHU:UROZ:PG47:JZBO:SA42:XTUS:25ER:ZXGH:JRHH:G6M6:P6JV:RYSO
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 18
 System Time: 2017-05-19T11:31:14.4403536+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
ping @msabansal

**Comment by riverar** [comment]
The issue title doesn't jive with the steps, but sounds like it may be related to an issue I also reported (DNS on the container host machine)

https://social.msdn.microsoft.com/Forums/en-US/784f27d5-5014-42c8-9ecc-d8d900ec5ecc/are-there-known-winnat-issues-with-containertohost-communication?forum=windowscontainers

**Comment by JacobPoldenValtech** [comment]
Turns out this issue was down to McAfee blocking the requests from the subnet
