### ISSUE TITLE
Container does not use the dns cache even I use host network mode

### ISSUE THREAD

**Issue by mikeshi80** [moby/moby#33298]
**Description**
I installed nscd on my host machine, and when I start some container with host network mode, I found the process in my  container does not use the dns cache, but resolve from my dnsmasq every time.

**Steps to reproduce the issue:**
1. Install the nscd service on the host machine.
2. Start the container with host network mode, and start the process which need resolve domain name.

**Describe the results you received:**

The process resolve domain name every request, not use the nscd cache. And it made the dnsmasq CPU usage very high, also impact the performance of the process.

**Describe the results you expected:**
The process does not resolve every time from dnsmasq service, but using cache.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
root@ops02:/home/cops/fluentd_01# docker info
Containers: 540
 Running: 24
 Paused: 0
 Stopped: 516
Images: 466
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2933
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 31.31 GiB
Name: ops02.corp.cootek.com
ID: I5BY:SUVC:KJDB:VJIK:MOZG:5ANH:456Q:UDSI:MWSD:ZIDO:FLSM:VGEI
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ubuntu 14.04, physical

**Comment by thaJeztah** [comment]
Docker 1.11 is over a year old, and no longer maintained. Are you still having this issue on the current release?

**Comment by mikeshi80** [comment]
OK, I resolve this problem, if you bind the host /var/run/nscd/socket file to the container, the container will use the socket automatically.

**Comment by thaJeztah** [comment]
Thanks for the update, let me go ahead and close this then :)
