### ISSUE TITLE
It takes about 1 minute to get response from a service deploy using swarm mode

### ISSUE THREAD

**Issue by tifayuki** [moby/moby#33309]
**Description**

we have a service deployed in all swarm manager nodes using global mode with port `2376:2376` published. At some point, it starts to take about 1 minute to get response from the service. We have redeployed the service many times with different version, but the problem is there.

To narrow down the issue, I tried the following steps:
1) Try to update the service with image `dockercloud/hello-world` (to make sure it is not the error in our application)
2) Since `dockercloud/hello-world` expose port `80` instead of `2376`, I tried to republish the port `2376` to `80` by doing updates with `--publish-rm 2376` and `--publish-add 2376:80`
3) Now, requests are processed without any significant delay. 
4) Try to update the service back with its original image
5) Update the service with `--publish-rm 2376` and then with `--publish-add 2376:2376`
6) Now, the requests are processed with no delay. Problem solved.
* Note I also checked the application log in my service that it received the request like 1 minute after the request was sent.

To me, it was like:
1) The problem happens only on this swarm. All other swarms(could be hundreds of) don't have such an issue.
2) Try to deploy different versions of my application image doesn't help
3) Remove the published port and re-publish it again seem like a workaround to fix the issue
4) Looks like this is an swarm network issue

**Steps to reproduce the issue:**
Cannot reproduce it, but will post more information if it happens again.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:34:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:34:06 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 13
 Running: 8
 Paused: 0
 Stopped: 5
Images: 13
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 4055bcvl0juoi7kjcwssar6s0
 Is Manager: true
 ClusterID: h8wpp7vlvfnqjlbdqf6j65fct
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.25.153
 Manager Addresses:
  172.31.21.118:2377
  172.31.25.153:2377
  172.31.8.165:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.11-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.67 GiB
Name: ip-172-31-25-153.us-west-1.compute.internal
ID: 7CQ6:SRAF:JIE3:XWEU:OA5X:GMZW:JKCV:G6FZ:TGCR:OEMW:EW3Z:VG4M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 327
 Goroutines: 1208
 System Time: 2017-05-19T21:15:54.571378899Z
 EventsListeners: 3
Username: fermayo
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=us-west-1
 availability_zone=us-west-1c
 instance_type=m3.medium
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is docker for AWS with 3 manages and 3 workers. Running about 7 weeks.

**Comment by tifayuki** [comment]
cc @fermayo @jmwong @bernardopericacho ^^

**Comment by dongluochen** [comment]
> it starts to take about 1 minute to get response from the service

I think this could server taking too long to respond, or TCP retransmit behavior due to network loss. TCP retransmit interval grows exponentially like 1s, 3s, 6s, 12s, 24s. That may explain the long delay in responding. When you have a repro, taking a network dump on client and server may provide useful information on where the problem is.

**Comment by fermayo** [comment]
I'm seeing this from time to time in one of my swarms. It seems a problem with the network configuration of the service. Only by doing `--publish-rm` and `--publish-add` I could get it fully working again. Forcing update of the service with `update --force`, or updating environment variables with `--env-add` and `--env-rm`, did not help at all, which might help troubleshooting the root cause.

We did lose a manager, which might have caused this, but I don't have currently a set of steps to reproduce the problem.

**Comment by thaJeztah** [comment]
closing because this went stale, but ping me if you have more information as requested above
