### ISSUE TITLE
Proposal: add route in docker api to call sysctl

### ISSUE THREAD

**Issue by aya** [moby/moby#33318]
**Description**

Add support to update sysctl values on linux systems.

**Background**

Some docker images (elasticsearch5) cannot run on fresh linux systems without tweaking the sysctls (vm.max_map_count).

It requires a privileged user running this kind of command before starting the container.

```bash
$ sudo sysctl -w vm.max_map_count=262144
```

**Rationale**

We can achieve this with tools like ansible but it applies to all VMs in a cluster while the specific docker images may not run on all those VMs.

A better way would be to be able to customise sysctl values through the docker API, allowing docker users to update a sysctl value on a specific host before running a specific image.

**Proposal**

The docker system command would allow to update some sysctl values.

We may need to restrict the values that docker users would be able to update through this command with a list of included/excluded set of values.

**Comment by cpuguy83** [comment]
This would really run afoul of the API design.

However you can do:
`docker run --privileged --rm debian sysctl -w vm.max_map_count=262144`

**Comment by aya** [comment]
Sorry, I did not look at the API design before submitting.
But I like your suggestion, thanks for the tip !
