### ISSUE TITLE
Docker URL

### ISSUE THREAD

**Issue by manilkumar** [moby/moby#33333]
What is docker URL in jenkins?

**Comment by thaJeztah** [comment]
I'm not really sure I understand what you're asking. Could you be a bit more specific?


Also keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by pandrew** [comment]
> What is docker URL in jenkins?

It is documented in the project directory. Please use the search bar at the top.

**Comment by AkihiroSuda** [comment]
Seems we can close this?

**Comment by thaJeztah** [comment]
yes lets close
