### ISSUE TITLE
--health-start-period value isn't shown when pretty inspecting service

### ISSUE THREAD

**Issue by vide** [moby/moby#33331]
**Description**

When I set the `--health-start-period` in a service, I cannot see the set value using `docker service inspect --pretty`, 

**Steps to reproduce the issue:**
1. `docker service update foo --health-start-period 2m`
2. `docker service inspect --pretty foo | grep -i health`

**Describe the results you received:**

No results while looking for an "Health Start Period value"

**Describe the results you expected:**

I think this is an important value that should appear in the prettified output too by default. I'm aware that the whole JSON inspect output carries indeed this info under
```
                "ContainerSpec": {
                    "Healthcheck": {
                        "StartPeriod": 120000000000
                    },
```

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Looks like this is a change that has to be made in the `docker/cli` repository now (where the CLI now lives), something similar to https://github.com/docker/cli/pull/89

Could you reopen this issue in that repository? Perhaps you're interested in contributing and opening a pull request (you can use the pull request I linked to for reference)

**Comment by vide** [comment]
@thaJeztah I'm not that expert in Go but maybe I'll try to implement it by myself. In the meanwhile, I'll open an issue under docker/cli (I guess GitHub doesn't support moving issues between projects)

**Comment by vide** [comment]
Created https://github.com/docker/cli/issues/117

**Comment by thaJeztah** [comment]
> I guess GitHub doesn't support moving issues between projects

Unfortunately not, no. I really wish it did

Thanks so much for reopening there; with the introduction of the Moby project, some components are being split into their own repository, so bear with us. 

> I'm not that expert in Go but maybe I'll try to implement it by myself.

No worries! I'm sure someone else is interested in working on it if you don't manage to do it. It looked like a nice way to get familiar with Go, so if you want to work on it, and need help, let us know as well; feel free to ping a maintainer on the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community)) 👍
