### ISSUE TITLE
Docker kill hangs when using different STOPSIGNAL and restart policy ALWAYS

### ISSUE THREAD

**Issue by dmitrykuzmenkov** [moby/moby#33334]
**Description**

When you define --stop-signal to SIGTERM (it could be SIGINT or whatever not default SIGKILL) and --restart always policy and use `docker kill` on that container `docker kill` does not exit and hangs forever but container killed and started again.

**Steps to reproduce the issue:**
1. `docker run --restart always --stop-signal SIGTERM --name test.stopsignal -it centos:7 python -m SimpleHTTPServer 8000`
2. `docker kill test.stopsignal`
3. Last command hangs forever while real container was killed and started again.

All works fine with stop signal redefined and no --restart always argument

**Describe the results you received:**

Docker kill does not exit

**Describe the results you expected:**

Docker kill exit on success not hangs

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems so the problem is in backend.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 65
 Running: 52
 Paused: 0
 Stopped: 13
Images: 1152
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: zoob0
ID: NPQZ:ZGE6:CQTV:545M:FUHJ:X763:HE5U:XJF7:TAQZ:63ER:X6OU:XER5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by dmitrykuzmenkov** [comment]
There is very strange logic in this commit: https://github.com/moby/moby/commit/d2e64247e6dfd3257a7d015890aa2f168ff643a0

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Comment by cpuguy83** [comment]
It shouldn't even be hitting that logic. Looking at this.

**Comment by cpuguy83** [comment]
Ok I see where it's hitting that logic. Indeed very confusing.
