### ISSUE TITLE
Docker stack "--force-recreate" in swarm mode 

### ISSUE THREAD

**Issue by viveky4d4v** [moby/moby#33332]
Is it possible to do a force recreation of containers using compose file in docker swarm mode ?
It can be helpful if we are testing our containers consistently in swarm mode . If the container dies during the testing etc , we can simply recreate them with single command like how it works in docker compose . 
Currently i have to remove the stack first & then deploy it again - 

`docker stack deploy -c stg-sm-deploy-compose.yml --with-registry-auth MY-APP`
`docker stack rm MY-APP`
`docker stack deploy -c stg-sm-deploy-compose.yml --with-registry-auth MY-APP`

Above 3 commands can be replaced by - 

`docker stack deploy -c stg-sm-deploy-compose.yml --with-registry-auth MY-APP --force-recreate`

**Comment by thaJeztah** [comment]
> If the container dies during the testing etc

Can you tell what happens in that situation? When using swarm mode services, a failing container should automatically be replaced with a new one to take its place

**Comment by viveky4d4v** [comment]
We can force re-create a particular service defined in the compose file in swarm mode -

Get service name -

`$ docker service ls`

Force-update/recreate it -

`$ docker service update --force MY-APP_nginx`

Where "nginx" is the service name defined in compose file & MY-APP is the name of the stack 

Closing this now . "docker service" command helped !

**Comment by viveky4d4v** [comment]
@thaJeztah - It won't start/recreate the new container if the container exits with a status 0 . Let's say if i just get into the container & do a "pkill nginx " , in this case container exits with a status 0 & no  re-creation is performed even when we deploy it again using "docker stack deploy" . We have to remove the stack & re-create it .

**Comment by dongluochen** [comment]
@viveky4d4v Normally service conciliation will recreate an exited container, unless restart policy prevents it from happening. Can you do a `docker service ls`, `docker service ps $SERVICE`, `docker service inspect $SERVICE_NAME` after you `do a "pkill nginx"`? And can you show your stack file?

**Comment by viveky4d4v** [comment]
@dongluochen  - 

Restart policy in compose file v3 - 

      restart_policy:
        condition: on-failure

service ls - 

    ID                  NAME                MODE                REPLICAS            
    ptwu7dpdl0ad        MY-APP_led        global              3/3                 logentries/docker-logentries:latest
    sohqla2l3rhv        MY-APP_nginx      global              2/2                 prd-nginx-sm:v1

service inspect - 


                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Global": {}
            },


service ps  -
       ID                  NAME                                       IMAGE                                         NODE                DESIRED STATE       CURRENT STATE               ERROR                       PORTS
       qnxbzjkswdki        MY-APP_nginx.jsi2foy1t4rcvjjl4iw8j8k1n   prd-nginx- sm:v1   stg-cheerios-02     Running             Running about an hour ago                               
       itchjzvqfvvk        MY-APP_nginx.bsdzklm6ji5szz0o9yqvjbznf   prd-nginx-sm:v1   stg-cheerios-03     Shutdown            Complete 55 seconds ago                                 
       nhe69yq30qk4        MY-APP_nginx.n5crm29jowz4yymycmokd3ix7    prd-nginx-sm:v1   stg-cheerios-01     Running             Running about an  hour ago                               


So the desired state changes to shutdown after "pkill nginx" & being in global mode it reduces the count from 3 to 2 . You can see the other service in global mode has 3 replicas . 

Am i  missing something in restart-policy ?

**Comment by dongluochen** [comment]
The container is not recreated because the restart condition is `on-failure`. In this case your container exits with 0 so it's not a failure. If you set the `--restart-condition` to `any`, the container will be recreated. 
`--restart-condition	 	Restart when condition is met (none, on-failure, or any)`

Do you set `--restart-condition` in compose file? Or it's the default setting?

**Comment by viveky4d4v** [comment]
@dongluochen - My BAD, i didn't do enough search prior to asking for a help !

        restart_policy:
          condition: any

condition "any" works like a charm . Yes , i am using it in the compose file .
