### ISSUE TITLE
Feature request: Hide service and node from docker service logs

### ISSUE THREAD

**Issue by rpofuk** [moby/moby#33349]
**Description**

docker service logs are sometimes hard to read. It would be better if service name and node name are optional. i.e flag --no-source (Not to show 

i.e.
docker service logs rcp_rcp-frontend  --no-task-ids --no-source

Would not show task-id and &lt;service&gt;.&lt;slot&gt;@&lt;node&gt; also

**Output of docker version:**

Docker version 17.05.0-ce

**Comment by thaJeztah** [comment]
Given that a `|` separator is output after the service-id/host, this should be easy to do with some basic linux commands, something like;

```bash
docker service logs -f <my-service> 2>&1 | cut -f2 -d "|"
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
