### ISSUE TITLE
Replace the engine ID fingerprint with an UUID

### ISSUE THREAD

**Issue by rogaha** [moby/moby#33356]
**Description**

Currently the `engine ID` shown in `docker info` is the `fingerprint ID` used to `sign` the deprecated `manifest schema v1`. The key signature and finger on these manifests are not checked or used any longer for security, deprecated by notary. So, given this context, we could: 

1) Generate ephemeral `fingerprint` keys to push the `v1` manifests
2) Replace the current `engine ID` with an `UUID` generated once

**Suggested format**

**Location**: `<docker_storage_directory>/engine_uuid`

```
/var/lib/docker # cat engine_uuid
0df9fdce-f163-41f0-92bb-d0df29dd79bc
/var/lib/docker #
```

/cc @dmp42 @friism

**Comment by thaJeztah** [comment]
Sounds good to me; do we have to wait until we have fully removed v1 support (docker 17.12)?

**Comment by rogaha** [comment]
@thaJeztah yep, I think so.

**Comment by rogaha** [comment]
@thaJeztah we don't need to wait if we generate ephemeral `fingerprint` keys instead.
