### ISSUE TITLE
Use casbin as the authorization mechanism (or plugin) for Docker Swarm Mode

### ISSUE THREAD

**Issue by hsluoyz** [moby/moby#33354]
Hi, I'm the author of [Casbin](https://github.com/casbin/casbin). It is a Go authorization library that supports access control models like ACL, RBAC, ABAC. Details can be found at: https://github.com/casbin/casbin

I have developed a Docker engine authorization plugin named [casbin-authz-plugin](https://github.com/casbin/casbin-authz-plugin) based on Casbin, and I want to make one for Docker Swarm Mode too, because access control for a multi-tenant clustering system is more important than a single host.

However, I didn't find any information or code that shows Docker Swarm Mode has any authorization mechanism. So I think there's still no authorization for now. So what is the suggested way to develop the authorization for Docker Swarm Mode? Will there be [an plugin mechanism like what Docker Engine does](https://github.com/docker/go-plugins-helpers/tree/master/authorization)? Or only a hard-coded authorization mechanism will be developed?

If there's no shaped design, I'm also happy to hear any progress or related discussion about this topic. Thanks!

**Comment by cpuguy83** [comment]
@hsluoyz All swarm interaction must happen through the API, as such authz plugins would get swarm-bound requests like any other API request.

**Comment by thaJeztah** [comment]
Let me close this issue, because this is not really a bug-report, but feel free to continue the conversation 👍
