### ISSUE TITLE
Multi-Stage Build does not remove base image

### ISSUE THREAD

**Issue by tabiul** [moby/moby#33366]
**Description**
When using docker multi-stage build the base image is not removed

**Steps to reproduce the issue:**
1. Create a Docker file that uses the multi-stage build feature
2. Check `docker images` and you can see the base image is still there

**Describe the results you received:**
The base image is still there 

**Describe the results you expected:**
I would expect the base image to be removed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 47
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-80-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.533GiB
Name: tabiulvm
ID: LZ45:EW3W:5REJ:QNDD:IVQO:6UKD:JXDU:7GZE:YV62:BJB3:2ULY:5D4I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
If the base image is removed then so is the build cache.
I think this is working as intended.

**Comment by tabiul** [comment]
So if I want the base image to be removed then I should use `--no-cache` ?

**Comment by cpuguy83** [comment]
`--no-cache` means to build and ignore the cache.
If you really need to clean this up, then I'd suggest something like:
```
docker build --target=<base target> -t <img>:<base> .
docker build --target=<main target> -t <image>:<main> .
docker rmi <image>:<base> .
```

**Comment by tabiul** [comment]
If I do these, does it not negate the purpose of multi-stage build in some sense. Before multi-stage build a shell script would do something like that and clean up. Multi-stage build is supposed to remove the need for shell script and extra Dockerfile.

**Comment by thaJeztah** [comment]
The goal of the multi stage build is that it allows you to build a final image that contains only the files that are needed to run the image.

Removing the base image and intermediate layers would be similar to (when not using docker) removing all your source files after you built a binary, which is usually not what you want

**Comment by tabiul** [comment]
In reality the previous image is useless as it contains a compiled code that is no longer required when you want to compile the next version. If the previous image can still be used I can understand the reason for it be there. Anyway I am closing this issue as I understand this is expected behaviour
