### ISSUE TITLE
event matching using controllers should filter by name and ID

### ISSUE THREAD

**Issue by yastij** [moby/moby#33371]
**Description** in `moby/daemon/cluster/executor/container/controller.go` the func ` matchevent(event events.Message) ` matches events using the following condition : 

``` go 
	if event.Actor.Attributes["name"] != r.adapter.container.name() {
		return false
	}
```
we should also filter using ID matching

**Comment by thaJeztah** [comment]
It looks like there's a TODO for this two lines above; https://github.com/moby/moby/blob/cfdf84d5d04c8ee656e5c4ad3db993c258e52674/daemon/cluster/executor/container/controller.go#L568

```go
func (r *controller) matchevent(event events.Message) bool {
	if event.Type != events.ContainerEventType {
		return false
	}

	// TODO(stevvooe): Filter based on ID matching, in addition to name.

	// Make sure the events are for this container.
	if event.Actor.Attributes["name"] != r.adapter.container.name() {
		return false
	}

	return true
}
```

Perhaps you're interested in contributing and opening a pull request to make these changes?

**Comment by yastij** [comment]
sure, will submit a PR after working hours :)

**Comment by thaJeztah** [comment]
Thanks!

**Comment by yastij** [comment]
@thaJeztah - can you PTAL when you have some time, thanks !
