### ISSUE TITLE
Volume plugin in moby loses propagated mount

### ISSUE THREAD

**Issue by caervs** [moby/moby#33378]
**Description**

When installing our own volume plugin on identical Docker4AWS nodes some nodes will fail to respect the `propagatedMount` attribute of the plugin config. This means that we cannot mount volumes created with our plugin into other containers. The plugin will successfully create a directory and mount volume but because the mounts aren't propagated docker cannot see the directory and docker container creation fails with

```
~ $ docker run -it --rm -v testfoobar2:/tf2 alpine sh
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/docker/plugins/a2c16140511959dc4e55298040a97f0b64841a0e774fd4b36795fe2b097f4234/rootfs/mounts/testfoobar2\\\" to rootfs \\\"/var/lib/docker/overlay2/806dd00248e8d884c9c3b3c8fbcc706faf538ce8028c062a4aedafd3361dfe43/merged\\\" at \\\"/tf2\\\" caused \\\"stat /var/lib/docker/plugins/a2c16140511959dc4e55298040a97f0b64841a0e774fd4b36795fe2b097f4234/rootfs/mounts/testfoobar2: no such file or directory\\\"\"".
ERRO[0000] error getting events from daemon: context canceled
~ $
```

**Steps to reproduce the issue:**
1. Create a Docker4AWS cluster
2. Install our plugin (please contact me for more details)
3. Find a node that is exhibiting this behavior (not deterministic)

**Describe the results you received:**

There are some stark differences between the mounts that exist on the two nodes, first in the sheer number of processes that have access to the mounts:

```
$ docker run -it --rm -v /proc:/hostproc alpine sh -c "grep 'plugins' /hostproc/*/mountinfo | cut -f 3 -d '/' | sort | uniq | wc"
      105       105       424
```

on the successful node and

```
docker run -it --rm -v /proc:/hostproc alpine sh -c "grep 'plugins' /hostproc/*/mountinfo | cut -f 3 -d '/' | sort | uniq | wc"
        1         1         6
```

on the failing one (the one process is the plugin process) and in with the mounts look like. The failing mounts to `/lib/docker/*` where as the successful also has mounts to `/var/lib/docker`. I’m guessing `/lib/docker` is on the host and is mounted as `/var/lib/docker` in the container that runs the docker daemon.

**Describe the results you expected:**

To be able to mount the volume into the container

**Additional information you deem important (e.g. issue happens only occasionally):**

See above

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:34:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:34:06 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker4AWS

cc @cpuguy83 @fermayo @vdemeester

**Comment by cpuguy83** [comment]
I think #33422 fixes this, if we can test it out.

**Comment by thaJeztah** [comment]
ping @aluzzardi - possible candidate for the e2e test suite

**Comment by fermayo** [comment]
I have tested this in Docker4Mac `17.06.0-rc2-ce-mac14` and is no longer an issue 👍 
cc @caervs @cpuguy83

**Comment by cpuguy83** [comment]
woot... talk about a 🤦‍♂️ issue.

**Comment by caervs** [comment]
Yup. We haven't had a repeat of the issue in our cluster for a few days now. Nice work, @cpuguy83!
