### ISSUE TITLE
getSwarm assumes that we have always one cluster

### ISSUE THREAD

**Issue by yastij** [moby/moby#33372]
**Description** in `moby/daemon/cluster/helpers.go`  : 

```go
func getSwarm(ctx context.Context, c swarmapi.ControlClient) (*swarmapi.Cluster, error) {
	rl, err := c.ListClusters(ctx, &swarmapi.ListClustersRequest{})
	if err != nil {
		return nil, err
	}

	if len(rl.Clusters) == 0 {
		return nil, errors.NewRequestNotFoundError(errNoSwarm)
	}

	// TODO: assume one cluster only
	return rl.Clusters[0], nil
}

```
as states the comment it assumes that `ListClustersResponse` will always contain a cluster array with only one element. 
as a result inspect and update (under `moby/daemon/cluster/swarm.go`) are being impacted with this assumption/limitation.

**Comment by thaJeztah** [comment]
Can you expand in what way they're impacted?

**Comment by yastij** [comment]
```go
func (c *Cluster) Inspect() (types.Swarm, error) {
	var swarm *swarmapi.Cluster
	if err := c.lockedManagerAction(func(ctx context.Context, state nodeState) error {
		s, err := getSwarm(ctx, state.controlClient)
		if err != nil {
			return err
		}
		swarm = s
		return nil
	}); err != nil {
		return types.Swarm{}, err
	}
	return convert.SwarmFromGRPC(*swarm), nil
}
```
inspect only considers `*swarmapi.Cluster` returned by `getSwarm` which is cluster[0].
but what if ListCluster call (cf. getSwarm function code) returns a `ListClustersResponse` containing more than one cluster ?

**Comment by thaJeztah** [comment]
Swarm mode currently only supports a single swarm/cluster, so I don't think that would happen; that's why I was wondering if there was a condition under which that would be a problem

**Comment by yastij** [comment]
maybe we can start working on this one so that it will be ready for multi-cluster support, plus don't think that it will break something.
we can juste filter by swarm.ID for updates for example ?

**Comment by thaJeztah** [comment]
I don't see much value in modifying this utility function while multi-cluster support is not there yet. Discussion on multi-cluster support should probably first take place in the https://github.com/docker/swarmkit repository

**Comment by thaJeztah** [comment]
If we have all the information to return the correct one, it could be done (updating this function), just wondering if it's needed right now

**Comment by yastij** [comment]
any on-going discussion on how will multi-cluster will be implemented ? (found only [docker/swarmkit#301](https://github.com/docker/swarmkit/issues/301) and [2084](https://github.com/docker/swarmkit/issues/2084) ) ?

**Comment by thaJeztah** [comment]
Not sure if there's a separate discussion, but feel free to join in on those!

**Comment by thaJeztah** [comment]
Are you okay with me closing this issue for now, or did you want to work on changing this function?

**Comment by yastij** [comment]
not specially, but maybe we should keep it open to track it and then work on it when have something on swarmkit ? but if you want we I'm not against closing it

**Comment by thaJeztah** [comment]
It looks like there's a TODO, and I assume it will automatically be picked up when multi cluster is worked on, so let's close for now. Thanks!
