### ISSUE TITLE
`Permission denied` when trying to access volume while selinux-enabled=true

### ISSUE THREAD

**Issue by MohdAhmad** [moby/moby#33389]
**Description**
With selinux enabled on the host and for the docker daemon, I get a `permission denied` when trying to access the volume. Propagated mount for the volume plugin is set to `/var/lib/test`.  Running the container with `--security-opt=label:disable` resolves the issue. How can I get around this without disabling selinux?

**Steps to reproduce the issue:**
1. Enable selinux on the host
2. Start docker with selinux enabled
3. Launch the nutanix volume plugin
4. Create a volume
5. Mount the volume to a container

**Describe the results you received:**
I get a `Permission denied` for all read write operations inside the directory.

**Describe the results you expected:**
To be able to read write files in the volume.

**Output of `docker version`:**
The issue is seen with 
```
Docker version:
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      6774275/1.13.1
 Built:           Wed Apr 19 12:52:58 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      6774275/1.13.1
 Built:           Wed Apr 19 12:52:58 2017
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-101045825-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 755.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 50.46 GB
 Metadata Space Used: 1.475 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker-latest/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker-latest/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 7.62 GiB
Name: localhost.localdomain
ID: ZVKZ:BOWZ:GX7Y:EINA:F6RZ:CGJB:22ML:BNMI:2FIL:ZRMS:QYMS:RCQC
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): false
Username: mohdahmad
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
From syslogs when container created with the volume mounted
```kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)```

From syslogs when running `ls` inside the directory.
```localhost journal: ls: cannot open directory '.': Permission denied#015```

From docker logs when runnign `ls` inside the directory.
``` [55B blob data]
[57B blob data]
[49B blob data]```

**Comment by cpuguy83** [comment]
Support for selinux labeling is going to depend heavily on the volume driver.
That said, can you try with Docker 17.05? There were some fixes to selinux labeling for certain cases that may resolve your issue.

**Comment by jcmcken** [comment]
I've tried 17.09 and 17.12 and running with SELinux in permissive mode and still have this issue. Mounting the volumes with ``:z`` or ``:Z`` relabels everything, but doesn't resolve the issue. Only setting ``selinux-enabled`` to ``false`` seems to fix the issue. I see no SELinux AVCs in my audit logs. Overall, very strange behavior.

**Comment by cpuguy83** [comment]
@jcmcken If the labels on your host dir are wrong, then you won't be able to access them in the container. This is what the `z` and `Z` options are for. There is no way around it, it's how selinux works.
If you want to mount a host dir, you need to make sure it has the proper selinux labels to be able to be accessed from a container.

I'm going to close this since there were some fixes for volumes getting proper selinux labels, but other than that being able to actually set the label is dependent on the underlying storage actually supporting it (e.g. a volume backed by nfs would fail unless the nfs server supports selinux).
