### ISSUE TITLE
volume driver: unable to mount when file exists in the image

### ISSUE THREAD

**Issue by wzhliang** [moby/moby#33395]
**Description**

Volume driver gets `readdirent: not a directory` when trying to mount a file that tries to override an existing file in the container.
I have the simplest volume driver here: https://github.com/wzhliang/docker-volume-simple/blob/master/main.go
it does nothing more than returning a existing file path on the host to the daemon. When mounting it to `/etc/nginx/nginx.conf` results in the above error.

**Steps to reproduce the issue:**
1. Build the very simple  from here https://github.com/wzhliang/docker-volume-simple
2. Run the volume driver with `./simple`
3. Try to bring up the service with `docker-compose up` that mounts like `volume_name:/etc/nginx/nginx.conf` 

**Describe the results you received:**
volumes is created by the container cannot be created:

    ERROR: for nginx  Cannot create container for service nginx: readdirent: not a directory
    ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**

volumes and containers are created successfully. Inside the container, `/etc/nginx/nginx.conf` should have the content of the file on the host rather than what's in the image. This is what I got when doing `docker run -v /path/to/hostfile:/etc/nginx/nginx.conf nginx`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@wliang-VirtualBox:~/go/src/conf_agent/nginx# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local myvolume
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.1-041001-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.1 MiB
Name: wliang-VirtualBox
ID: JVXE:CRIL:3UQK:UFNC:EHYR:PDMQ:YYXD:DFUR:QR6Q:6UKG:JCMC:V7UG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 16.04 and 17.04 running on VirtualBox

**Comment by cpuguy83** [comment]
This happens because `/path/to/hostfile` is not a file, it's a directory.

**Comment by wzhliang** [comment]
@cpuguy83 It's actually the reverse. It is a file and docker is expecting a directory.

**Comment by cpuguy83** [comment]
@wzhliang Then it must already be a directory in the container.

**Comment by cpuguy83** [comment]
Sorry, re-reading it, I realize this is not related to `-v /foo:/bar` behavior but rather the behavior of the volume driver. What happens if use use the `:nocopy` option with the `volume_name:/etc/nginx/nginx.conf`?

**Comment by wzhliang** [comment]
@cpuguy83 Thanks! The `nocopy` flag did the trick. Could you explain why?

**Comment by cpuguy83** [comment]
@wzhliang Because the default behavior is to attempt to read the container path and copy that into the volume (if the volume is empty), assuming that the container path is a dir.

You may want to look at the `config` object we are introducing in 17.06 to handle passing around config files to containers.
