### ISSUE TITLE
Improve documentation on ulimit option

### ISSUE THREAD

**Issue by gasparch** [moby/moby#33406]
**Description**

Docker and Docker-Compose documentations do not make clear what are the valid values of ulimit options for Docker.

**Steps to reproduce the issue:**
1. Read Docker documentation
2. Struggle to find correct option names. 

**Describe the results you received:**

Google finds just a few places where possible options are listed - https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Ulimit.html 
Looking on code - turns out it is incomplete and [any valid `setrlimit` option](https://linux.die.net/man/2/setrlimit) can be passed into `ulimits`

**Describe the results you expected:**

List of possible options or reference to example (setting list of file descriptiors, max memory, max cpu usage, etc)

**Comment by rheinwein** [comment]
Thanks @gasparch. I see you've already opened https://github.com/docker/docker.github.io/issues/3416 in the docs repo, which is the correct place for that type of issue. To that point, I'll close this one.
