### ISSUE TITLE
can not assign tcp port to docker 

### ISSUE THREAD

**Issue by halavehzadeh** [moby/moby#33417]
**Description**
need to  redirect docker from socket port to TCP port ,when I issue below command 
docker -H 192.168.0.133:2375 -d &
i got 
"unknown shorthand flag: 'd' in -d"
I'm using Ubuntu 16.04 and dicker version is "Docker version 17.05.0-ce"

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
`dockerd -H tcp://192.168.0.133:2375`

You should secure this with a TLS cert as anyone with access to the IP address/port will have full root access to the system.

Also please be mindful that the issue tracker is not for general support.
Check out https://forums.docker.com.

Thanks!

**Comment by halavehzadeh** [comment]
thanks it was work ,hope that old command is not work in new Ubuntu .i tested and work perfectly
