### ISSUE TITLE
Empty IdentityToken when calling /auth using cURL API on Docker 17.05

### ISSUE THREAD

**Issue by rdlf0** [moby/moby#33429]
**Description**

When trying to authenticate through the API via cURL request, calling /auth returns `Status: Login Succeeded` and an empty `IdentityToken`.

**Steps to reproduce the issue:**
1. Call this:
```
curl --unix-socket /var/run/docker.sock -X POST http:/auth --data '{"username": "my_username", "password": "my_secret_password", "serveraddress": "myserver.dockeraddress.com"}'
```

**Describe the results you received:**
`{"IdentityToken":"","Status":"Login Succeeded"}`

**Describe the results you expected:**
`{"IdentityToken":"someIdentityToken","Status":"Login Succeeded"}`

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens every time. Can't get it working.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 53
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 92
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.609GiB
Name: hans
ID: AIQ4:OYGK:GH5C:TRQI:34ZC:DMGO:HTII:EDOY:F65B:RAVX:EHHB:OLW7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical personal machine

**Comment by DeliangFan** [comment]
I'm fixing it now.

**Comment by thaJeztah** [comment]
This endpoint authenticates to your registry (see https://github.com/moby/moby/blob/271b1f27563b18a125b89d2d2629246213dbfd96/registry/auth.go#L132-L180). What kind of registry are you running on `myserver.dockeraddress.com`? Is it behind a front-end proxy (e.g. nginx)? Does it support authentication?

@aaronlehmann @dmcgowan should an empty `IdentityToken` qualify as "failed to login", or is that the reponsibility of the registry / authentication service to return a proper error code?

**Comment by rdlf0** [comment]
@thaJeztah Making a direct POST HTTP request to the server on its web address (https://mysampleserver.com/auth) returns a token. I'm able to login through the CLI, using `docker login mysampleserver.com`, too.

**Comment by dmcgowan** [comment]
@rdlf0 are you sure the registry you are using supports identity tokens? Login will not return the short lived access token used to verify credentials.

**Comment by thaJeztah** [comment]
Ah, actually, I was looking at the code, and IIUC, the token is only fetched during actual pulling of the image (because they are short-lived tokens) correct?
https://github.com/moby/moby/blob/f2614f2107c838d014d31b806e3b8a9f1395cb2b/vendor/github.com/docker/distribution/registry/client/transport/transport.go#L50-L72

**Comment by dmcgowan** [comment]
@thaJeztah login uses that same transport to grab a token without scope and checks it against the `/v2/` endpoint to verify the credentials are valid. You are correct about it being short lived, and therefore not something returned by login.

We do have a specification for using actual oauth2 refresh tokens and it is supported by Docker through the `IdentityToken` field. A registry auth server must implement the specification though in order to get that value returned from login. See https://docs.docker.com/registry/spec/auth/oauth/

**Comment by thaJeztah** [comment]
@rdlf0 I think your question is answered, so let me go ahead and close this issue, but feel free to continue the conversation if you need more information
