### ISSUE TITLE
Documentation does not indicate that X-Registry-Auth base64 encoding must be URL-safe

### ISSUE THREAD

**Issue by krallin** [moby/moby#33434]
**Description**

The documentation does not indicate that the encoding for `X-Registry-Auth` should be URL-safe, but [the underlying code expects such encoding](https://github.com/moby/moby/blob/4bf8714fac11e95e835cf78eb15ba5a518c67c4b/api/server/router/image/image_routes.go#L98-L107).

This is particular problematic on image pulls, where Docker will silently ignore the header if it's improperly encoded. This also makes the issue hard to troubleshoot: many valid auth headers will encode identically with URL-safe and unsafe encodings.

**Steps to reproduce the issue:**

1. Use a library that uses regular base64 encoding for the X-Registry-Auth header, e.g. https://github.com/swipely/docker-api
2. Use a username and password that cause the X-Registry-Auth to contain URL-unsafe characters, such as `/`.
3. Try to pull and image that requires authentication.

**Describe the results you received:**

Pull fails with "image not found".

**Describe the results you expected:**

Docker throws an error (that'd be great), or more realistically the documentation indicates which encoding should have been used so I have an authoritative reference when I make a PR to fix the
client library 😄 

Thanks!

**Comment by platy** [comment]
"This encoding ... should not be referred to as only "base64"."
https://tools.ietf.org/html/rfc4648#section-5

https://docs.docker.com/engine/api/v1.31/#section/Authentication
