### ISSUE TITLE
Swarm mode rollback service with rollback flags "other flags may not be combined with --rollback"

### ISSUE THREAD

**Issue by dengqingpei1990** [moby/moby#33444]
**Description**

When I try to rollback swarm mode service with --rollback-order flag, An error occur.
`$ docker service update --rollback --rollback-order start-first myapp`
`other flags may not be combined with --rollback`
**Steps to reproduce the issue:**
1.Create a docker service "docker service create --name myapp myapp:1.0"
2.Update service with a new version of image "docker service update --image myapp:2.0"
3.Rollback service with --rollback-order flag "docker service update  --rollback --rollback-order start-first myapp"

**Describe the results you received:**
Show me an error as follows:
`other flags may not be combined with --rollback`

**Describe the results you expected:**
Rollback service using "start-first" strategy.

**Additional information you deem important (e.g. issue happens only occasionally):**
I put --detach=true flag with docker service update --rollback. This error occurs too, either with other rollback flags.
**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 3y3osp51qibkdu6gs27ululwt
 Is Manager: true
 ClusterID: vu3nklnujqqjohp57a01676nu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.112
 Manager Addresses:
  192.168.1.112:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.636GiB
Name: dev.knms.com
ID: FHKD:DPEQ:IQVD:OWFZ:R7OB:EFTS:PUPR:C3XO:SMMY:4V6A:VZN4:LTLG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://q6nn9k1g.mirror.aliyuncs.com/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local VirtualBox

**Comment by thaJeztah** [comment]
This is by design; the `--rollback` option rolls back the service to the previous definition. Combining that with other flags effectively would be combining a rollback with an update, so you would not end up with the previous (known to work) service definition, but with a _new_ definition; possibly introducing issues.

Having said the above, I wonder if we should have a rollback _command_ instead of a rollback _flag_ to make it less confusing (`docker service rollback <servicename>`)

ping @aaronlehmann wdyt?

(i'll close this issue for housekeeping; because it's not a bug, but feel free to continue the conversation)

**Comment by dengqingpei1990** [comment]
OK. I read the new docker docs just now. And I find some new description said that "Finally, in Docker 17.04 and higher, --rollback cannot be used in conjunction with other flags to docker service update." which I don't see on the previous doc.

I agree with your idea of Adding a service rollback subcommand to swarm mode.  In my case, I write some CI/CD script using "docker service update" command  with --rollback flags to rollback service.  Because of my interest on new features of swarm mode.  I update docker from 17.03 to 17.05 and then I find my script don't work. 

The other thing confuse me is that the new --detach flag. With out specifying this flag will show me a message:
 `Since --detach=false was not specified, tasks will be updated in the background.
In a future release, --detach=false will become the default.`

I do not want the “update progress bar“ interrupt my service rollback job script. So I realize I have to set --detach=true to make this script compatible with new default settings. But as I say in "Additional information you deem important", --detach flag can't set with --rollback flag either. Am I misunderstanding something? Or a missing part of --rollback flag? @thaJeztah

**Comment by thaJeztah** [comment]
> --detach flag can't set with --rollback flag either.

That looks like a bug, let me open an issue for that

**Comment by vce-xx** [comment]
Shouldn't "docker stack deploy" offer the --detach flag as well for consistency ?

**Comment by thaJeztah** [comment]
@vce-xx that's a separate discussion; see this issue, which is proposing that: https://github.com/moby/moby/issues/32367
