### ISSUE TITLE
COPY and ADD should honor USER

### ISSUE THREAD

**Issue by italomaia** [moby/moby#33457]
Files COPYed or ADDed to a container should honor the current user permissions. If this behavior is not preserved, one would have to create a new layer just to change permissions to a sensible value.

**Comment by italomaia** [comment]
Example:

```
RUN groupadd -g 1000 me \
  && useradd -m -d /home/me -r -u 1000 -g me me
WORKDIR /home/me
COPY root_file.txt .
USER me
COPY user_file.txt .
RUN ls -lh
```

I should get two entries:
root_file.txt (with root owner)
user_file.txt (with me owner)

**Comment by rheinwein** [comment]
Hi @italomaia -- it seems like the issue you've submitted is being discussed in another issue already: https://github.com/moby/moby/issues/30110. I'll close this, and feel free to add a comment or subscribe to the issue that's open.
