### ISSUE TITLE
Improve error when attempting to `docker load` Linux image into Windows daemon (and vice-versa)

### ISSUE THREAD

**Issue by friism** [moby/moby#33460]
**Description**

The error message when `docker load` a Linux image into a Windows daemon is not good. We have better errors when doing `docker pull`, this should also be used with `docker load`

**Steps to reproduce the issue:**

```
// in Linux mode

C:\code\tmp
λ  docker save -o busybox.tar busybox

// switch to Windows mode
C:\code\tmp
λ  docker load -i .\busybox.tar
4ac76077f2c7: Loading layer [==================================================>]  1.309MB/1.309MB
re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\e1326ccc3c57714a86a728faa72e5b4fd3005b95f118f630713c7dfa038b45d1: The system cannot find the path specified.
```

**Describe the results you received:**

```
re-exec error: exit status 1: output: ProcessBaseLayer 
```

**Describe the results you expected:**

```
Error: Cannot load Linux image on Windows
```

(or something like that)

**Output of `docker version`:**

17.06 RC.

cc @dhiltgen @johnstep @jhowardmsft

**Comment by johnstep** [comment]
This error comes from HCS. We can fix this by checking the image OS before calling HCS.

**Comment by thaJeztah** [comment]
@johnstep will that conflict with LCOW?

**Comment by jhowardmsft** [comment]
Probably but I can fix that when I start working on load next week. IOW go ahead.

**Comment by friism** [comment]
I think this is fixed here: https://github.com/moby/moby/pull/33647 - @thaJeztah recommend closing this one if @johnstep is ok

**Comment by thaJeztah** [comment]
Yup, think we can close this

**Comment by floriancastelain** [comment]
Encountered this error today.
My image was built on Ubuntu 18, it is extracted on windows server 2016 standard.

`ProcessBaseLayer C:\ProgramData\docker\windowsfilter\fc85688e67dd692c808cb3af0157a73e3fe885c1b990c14e6518f89ccf6bffbc: The system cannot find the path specified.`
