### ISSUE TITLE
docker can not delete endpoint when allocateNetwork fail

### ISSUE THREAD

**Issue by Ace-Tang** [moby/moby#33470]
**Description**

when allocate network for a new container,  after CreateEndpoint in daemon/containers_operations.go,  docker will call ep.Join to join sandbox,  in sbJoin function, according to logic now, it will update endpoint's sandbox info in datastore, if any step fail(in my position, it fails at allocate ports), it just set ep.sandboxID = "", but bot update this info into datastore. 

update endpoint info with sanbox in function sbJoin
```
if err = n.getController().updateToStore(ep); err != nil {
         return err
  }

```

set ep.sandboxID="" in function sbJoin after any step fails
```
defer func() {
       if err != nil {
            ep.Lock()
            ep.sandboxID = ""
            ep.Unlock()
        }
  }()
```

**Describe the results you received:**
in my  test-integration-cli, this problem cause stale endpoint leave in datastore.
for eg, a container named fail got this problem, and leave  endpoint info in datastore,  when i want to create a container with name fail, it will got this error
```
Error response from daemon: service endpoint with name fail already exists
```

**my fix:**

i modify my code in function sbJoin , it will fix my problem
```
defer func() {
       if err != nil {
            ep.Lock()
            ep.sandboxID = ""
            ep.Unlock()
+          if err := n.getController().updateToStore(ep); err != nil {
+               log.Warnf("updateToStore failed: %v", err)
           }
        }
  }()
```
I wonder if i am right , can someone help me

**Output of `docker version`:**
i do some modify in my docker, but allocate network logic not have lots different with moby

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
