### ISSUE TITLE
[Proposal] Enhance local logging / remote logging

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#33475]
## Background on logging

A long long time ago, docker only supported one method of logging for containers. This is now affectionately known as `jsonfilelog`. There was no support for logging to external services (be it remote endpoints or a local out of process service like journald).

The json logger itself also had many performance related issues: excessive memory allocations, slow (reflection-based) json marshalling, and leaking resources. It also did not support log rotation, which means that every container's log file would just grow unbounded and no (good) way to rotate it without data loss. 

Because of this we introduced the ability to disable logging as well as the concept of logging drivers and slowly started adding new loggers for external services (syslog, journald, cloudwatch, etc).

The performance issues have been partially dealt with (see the hack that is pkg/jsonlog) and of course resource leaking dealt with. Log rotation support added (but not enabled by default). 

At this point most everything is great with logging... unless you need to run `docker logs`, since only jsonfilelog and journald support reading logs. For this reason many people just use the built-in json logger and consume the logs API to ingest into another service.

### Dual-logging
Always have containers log to a local logger that supports reading if/when the user selected log driver does not support reads in addition to the selected logger. This will allow users to have a consistent experience regardless of the logging driver selected.

**This is not allowing users to specify two(or multiple) log drivers, but rather to log locally in addition to the user specified log driver**

An issue with this...the json logger still has some performance issues... json marshalling is slow and still makes several allocations (I think around 3) per log entry, and can potentially use up loads of disk-space unexpectedly.

### Replace jsonfilelog

For this reason, I also propose replacing the jsonfilelog driver with a new driver: `local`.
`jsonfilelog` is tied to json. We've tweaked the hell out of logging to json for container logs but it's still not ideal (for performance reasons) and really awful/fragile code.

The `local` logger would, like jsonfilelog, log to a local file, but would not be tied to any particular encoding format. This is possible by encoding the version/format into the top of each log file. This can be a binary encoded version, with the version corresponding to the version of the driver's encoding format (this could encapsulate both changes to the underlying encoding itself as well as major changes to log data). Doing this on each file allows Docker to support mixed versions for a single container.

Version 1 of this format would be encoded as protobuf following the same format as used for logging plugins: https://github.com/moby/moby/tree/master/api/types/plugins/logdriver.

This encoding format does not require any allocations and requires far less CPU than json.
Another plus is the protobuf format uses something like 1/3-1/2 less space (in my tests) on disk compared to the same output in json.

The new driver should also have sensible defaults for rotation (i.e. rotate by default) and rotated files should also be compressed (by default) to further save space on disk.
When a container is only logged locally the sensible thing to do is to not ever remove log data (unless specified), but when logging to external services it should be ok to clean out older files.

### Make `local` the default

Ideally this new `local` log driver would become the default logger since it should be better in absolutely every way than `jsonfilelog`. `jsonfilelog` should then be deprecated, and eventually removed.

Some problems here may be with users who are directly accessing container log files, expecting a particular format, place on disk, etc... this sucks... but ultimately on-disk state is not part of our API and people should not be messing around in there.... if they are, they should expect to be easily broken between versions.

 - [x] Implement new local logger - #37092
- [ ] Implement dual logging

**Comment by bkauf** [comment]
I am absolutely in favor of deprecating JSON style logs and am in agreement with the above dual log strategy. As for the new format lets look to how other enterprise companies implement logging and not attempt to reinvent the wheel:
 
VMware
https://pubs.vmware.com/vsphere-50/index.jsp?
topic=%2Fcom.vmware.wssdk.pg.doc_50%2FPG_ChA_Diagnostics.19.3.html

PCF
https://docs.pivotal.io/pivotalcf/1-10/devguide/deploy-apps/streaming-logs.html

**Comment by thaJeztah** [comment]
Also related: https://github.com/moby/moby/issues/17910

**Comment by cpuguy83** [comment]
@bkauf re: format, there is. I reinventing here. We're using the same format being used for plugins which is incredibly effificent and meant for machine reading.

**Comment by justincormack** [comment]
Sounds good, although I do want to be able to totally disable logging, for
the use case where my container just exists to be part of a Unix pipeline
and writes megabytes of output.

**Comment by cpuguy83** [comment]
One of these days I'll stop commenting from mobile... "There is nothing being reinvented here"

**Comment by cpuguy83** [comment]
Working on compression handling here: https://github.com/moby/moby/pull/29932

**Comment by ekristen** [comment]
Big +1 from me.  It's crucial to keep all my logs centralized (I use Splunk) but at the same time, for ease of debugging quickly and allowing developers to simply see logs, the use of `docker log` still needs to work.

**Comment by zh99998** [comment]
@ekristen exactly same problem for me.
It's hard to debug after enable Splunk log.

**Comment by ekristen** [comment]
@zh99998 I wrote this plugin, if you want to give it a shot. https://github.com/ekristen/docker-plugin-multilogger I'm still doing some robust testing on it, but it allows for logging to splunk and the local filesystem.

**Comment by zh99998** [comment]
I find that query Splunk seems be more easier and no risk.

doing such a query can get logs realtime, like `docker logs -f`
```
curl -k --insecure -u admin:xxxxx https://192.168.16.23:8089/servicesNS/admin/search/search/jobs/export -d search="search source=nginx" -d output_mode=raw -d search_mode=realtime
```
it can be make shorter by a script or alias in bash.

**Comment by zh99998** [comment]
I made a simple bash script for it.
```bash
#!/bin/bash

while getopts "t:f" arg #选项后面的冒号表示该选项需要参数
do
    case $arg in
        t)
            HEAD=$OPTARG
            ;;
        f)
            REALTIME=true
            ;;
        *)
            echo "Usage: log [-t num] [-f] source"
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))
SOURCE=$1

if [ -z "${SOURCE}" ]
then
    echo "Usage: log [-t num] [-f] source"
    exit 1
fi

if [ -n "${HEAD}" ]
then
    curl -k --insecure -u admin:*** https://192.168.16.23:8089/servicesNS/admin/search/search/jobs/export -d output_mode=raw -d search="search source=${SOURCE} | head ${HEAD}"
else
    curl -k --insecure -u admin:*** https://192.168.16.23:8089/servicesNS/admin/search/search/jobs/export -d output_mode=raw -d search="search source=${SOURCE}"
fi

if [ "${REALTIME}" = "true" ]
then
    curl -k --insecure -u admin:*** https://192.168.16.23:8089/servicesNS/admin/search/search/jobs/export -d output_mode=raw -d search="search source=${SOURCE}" -d search_mode=realtime
fi
```

**Comment by anusha-ragunathan** [comment]
Proposal LGTM

**Comment by cpuguy83** [comment]
This is completed.

On master drivers which do not support reads will have an additional local buffer which can be disabled.

**Comment by shane-axiom** [comment]
@cpuguy83 Thanks for all the work on this! Can you clarify at a high level what was implemented from the propsal?

Based on the current documentation, it seems like:

* Dual-logging - [implemented, but enterprise only](https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers), will this be the case going forward?
* Replace jsonfilelog - done, with `local` driver, seems to appear starting in docs starting with [v18.09](https://docs.docker.com/v18.09/config/containers/logging/configure/#supported-logging-drivers)
* Make local the default - as of [v19.03](https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers) `json-file` is still the default logging driver, any plans to change this?

Thanks!

**Comment by cpuguy83** [comment]
> Dual-logging - implemented, but enterprise only, will this be the case going forward?

This was upstreamed by Mirantis: https://github.com/moby/moby/pull/40543

> Make local the default - as of v19.03 json-file is still the default logging driver, any plans to change this?

Sorry, we did not change the default logger and likely will not for some time b/c of higher level tools (k8s) depending on it.
Admins can change the default by setting it in /etc/docker/daemon.json

**Comment by shane-axiom** [comment]
Very nice, thanks! Really important work here.
