### ISSUE TITLE
client.ContainerLogs() documentation says nothing about the in-band data in the io.Reader

### ISSUE THREAD

**Issue by bartgrantham** [moby/moby#33486]
The [documentation on godoc for client.ContainerLogs()](https://godoc.org/github.com/moby/moby/client#Client.ContainerLogs) doesn't include any information, not even a warning, about the 8-byte tokens included in the bytes returned by the io.Reader.

This log format utterly violates the principle of least surprise, which makes the lack of documentation particularly bad.  Since Go was specifically designed with channels and multiple return values to avoid this kind of in-band signalling, I really don't understand why this is designed this way.  But it's probably too late to change without significant backwards compatibility breakage, so I guess the most I can ask is for the documentation to be updated to give developers a heads-up about this misfeature.

Whenever documentation does get written, it's important to note that you don't get one header + data per call to Read(), you get a buffer that has _one or more_ header+data chunks.  So you have to fully parse the buffers the io.Reader serves up, not just the first 8 bytes.

And if anyone stumbles across this issue and wants to wrap the docker not-quite-an-io.Reader io.Reader, here's my quick hack of a solution:

```
type dockerLogWrapper struct {
    stream io.Reader
}

func (w dockerLogWrapper) Read(b []byte) (n int, err error) {
    buf := make([]byte, len(b))
    m, err := w.stream.Read(buf)
    switch {
        case m == 0 : return
        case m > 0 && m < 8:
            return 0, fmt.Errorf("malformed header in docker stream")
        default:
            cur := 0
            for {
                if cur >= m {  break  }
                i := int(binary.BigEndian.Uint32(buf[cur+4:cur+8]))
                copy(b[n:], buf[cur+8:cur+8+i])
                cur += i+8
                n += i
            }
    }
    return
}
```

Use it like so:

```
    out, err = cli.ContainerLogs(ctx, r.ID, types.ContainerLogsOptions{ShowStdout: true})
    safe_reader := dockerLogWrapper{stream:out}
    // and now you can Read() from safe_reader normally
```

keywords: log, corrupt, stdout, stderr, unicode, binary, extra bytes

**Comment by cpuguy83** [comment]
This is included in the API docs here, under "Stream Format" (which is linked to from the logs API doc): https://docs.docker.com/engine/api/v1.28/#operation/ContainerAttach

The interface of `io.Reader` is `Read([]byte) (int, error)`.
This interface does not make any assumptions about the data being copied to the passed in buffer.
You have to know the format of the data coming out and parse it accordingly.

If you want to read only the header (assuming you are at the beginning of a stream) you would need to do something like so:

```go
out, _ : cli.ContainerLogs(...)
headerBuf := make([]byte, 8)
io.ReadFull(out, headerBuf)

logLine := make([]byte, int(binary.BigEndian.Uint32(headerBuf)))
io.ReadFull(out, logLine)
```

There's also a utility package to handle this for you: https://github.com/moby/moby/blob/master/pkg/stdcopy/stdcopy.go#L94

The reason for the 8-byte header is the stream is multiplexed with stdout and stderr from the container, and the client should be able to split those streams back out.

Maybe the client lib should handle this for you, as I don't know why anyone would need to the raw stream? But changing the package API is not the nicest thing to do either and so far the client lib is a very thin wrapper over the HTTP endpoints.

I do agree it would be helpful to document the stream format in the client lib docstring.

**Comment by thaJeztah** [comment]
@bartgrantham would you be interested in opening a pull-request to update the documentation in the client lib?

**Comment by cpuguy83** [comment]
I opened #33494 to address this.

**Comment by bartgrantham** [comment]
@cpuguy83, I eventually found the documentation you pointed out, but if a user is already looking at Go API documentation I wouldn't expect to look at the HTTP API docs for answers.

Your code will work if you're consuming the log but it won't if you want to pass the io.Reader to something downstream that expects to be able to simply Read().  Also, the buffer the caller passes to Read() can come back with _multiple frames_ (header + payload) of data, which is another bit of unexpected behavior.

I wish I had found that StdCopy utility before I went down my path.  Although, where would be a good place to put a pointer to that where someone hacking away in Go would be likely to find it?  In godoc?

@thaJeztah, I appreciate the sentiment ("stop cursing the darkness and light a candle"), but I'm super underwater on a project right now and I won't be able to get around to it.  I already burned many hours of time I didn't have to wrangle a solution to this.

**Comment by cpuguy83** [comment]
@bartgrantham 

> Also, the buffer the caller passes to Read() can come back with multiple frames (header + payload) of data

This is not the concern of an `io.Reader`. Readers are supposed to copy `len(buf)` to the passed in buffer (if it's available).
The real problem is the stream format was not documented on the function so you have no idea of knowing that it's not just a stream of bytes directly from the container.

What if the io.Reader was streaming json? You'd have to know that the stream format is json and how json is delimited in order to parse the stream. Same thing here really, just an unfamiliar format and a client lib function that was not well documented.

In any case, I opened a PR to add the relevant information. Thanks for reporting!

**Comment by bartgrantham** [comment]
> What if the io.Reader was streaming json? You'd have to know that the stream format is json and how json is delimited in order to parse the stream. Same thing here really, just an unfamiliar format and a client lib function that was not well documented.

I disagree, this isn't like that at all.  This is like expecting json _and getting something else_.  I thought I knew exactly what to expect and what my downstream code was consuming, but that's not what I got.

Oh well.  Live and learn.
