### ISSUE TITLE
docker exec without `Env` support

### ISSUE THREAD

**Issue by Colstuwjx** [moby/moby#33487]
As I known, the `docker exec` execution is almost same to `docker run`, as the libcontainerd will always create a new process to do that.

But, in the [ExecConfig](https://github.com/moby/moby/blob/master/api/types/configs.go#L52), there is 
 an Env config, which said support to override some ExecEnv, sadly it actually doesn't work.

Could someone have a look?
Thanks.

**Comment by shishir-a412ed** [comment]
@Colstuwjx Can you give an example (set of instructions) to reproduce this ?

**Comment by thaJeztah** [comment]
Providing environment variables in `docker exec` was added in docker 1.13 (see https://github.com/moby/moby/pull/24594); what version of docker are you using?

Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by Colstuwjx** [comment]
Sorry about the confuse...
I've been tested OK on `17.05.0-ce` and things work well.

Thanks for your help!

**Comment by thaJeztah** [comment]
good to hear it works, you're welcome!
