### ISSUE TITLE
Reopen: docker cp gives 'operation not permitted' but does still copy file

### ISSUE THREAD

**Issue by erxian** [moby/moby#33490]
Hi all,
     When I do "docker cp" as a root user, the copy succeeds but the lchown afterward still fails and exports:
```
Error response from daemon: Error processing tar file(exit status 1): lchown /test.sh: operation not permitted
```
The same problem will reproduce in "kubectl cp", which output is:
```
tar: test.sh: Cannot change ownership to uid 0, gid 0: Operation not permitted
tar: Exiting with failure status due to previous error
```
After checking docker issues, I find it's a long-standing problem locates in https://github.com/moby/moby/issues/3986 https://github.com/moby/moby/issues/4130 

So I wonder why docker cp gives 'operation not permitted' but does still copy file, and how to fix it.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

```

**Comment by thaJeztah** [comment]
Can you

- post the output of `docker info` as well?
- provide exact steps to reproduce the issue?

I'm trying to reproduce on 17.06, but don't see this issue;

Trying to copy a directory tree from an image;

```bash
$ docker run -d --name foo nginx:alpine
$ docker cp foo:/usr/share/nginx here-copied

$ tree here-copied/
here-copied/
└── html
    ├── 50x.html
    └── index.html

1 directory, 2 files
```


Using the steps from https://github.com/moby/moby/issues/4130#issuecomment-35793729

```bash
$ docker run -dit --name foo2 ubuntu

$ docker cp foo2:/bin/bash $(pwd)/bash

$ ls -la
total 1028
drwxr-xr-x 3 root root    4096 Jun  2 10:59 .
drwx------ 7 root root    4096 Jun  2 10:56 ..
-rwxr-xr-x 1 root root 1037528 Jun 24  2016 bash
drwxr-xr-x 3 root root    4096 May 30 17:15 here-copied
```
