### ISSUE TITLE
GELF Driver does not support TCP

### ISSUE THREAD

**Issue by ghislainbourgeois** [moby/moby#33495]
**Description**

The GELF Log driver does not currently support the TCP transport. In some cases, TCP would be more appropriate. 

It is currently not supported directly by go-gelf, but there is currently a pull request (https://github.com/Graylog2/go-gelf/pull/9) that adds TCP support. 

I am currently working on a pull request that will enable the TCP transport once the go-gelf PR is merged.

**Comment by ghislainbourgeois** [comment]
#dibs

**Comment by thaJeztah** [comment]
Related issue; https://github.com/moby/moby/issues/29871

**Comment by shpall** [comment]
Is there any news? https://github.com/Graylog2/go-gelf/pull/9 was merged.

Thanks!

**Comment by ghislainbourgeois** [comment]
I have been busy on other things, I am starting work on this issue this week. I expect to have something to review by end of week.

**Comment by ksrb** [comment]
Hi just wondering if anyone knows when this change would be released?

Been trying to figure it out but it looks like it 9 weeks at minimum?

Related links:
- https://github.com/moby/moby/blob/master/project/RELEASE-PROCESS.md#release-cycle
- https://github.com/moby/moby/milestone/69
- https://forums.docker.com/t/docker-17-03-0-ce-quaterly-or-monthly/29201
