### ISSUE TITLE
v1.28/services/{id} endpoint missing some information

### ISSUE THREAD

**Issue by cghislai** [moby/moby#33506]
Using Docker version 17.05.0-ce, build 89658be, I can see the new service spec UpdateConfig and RollbackConfig using `docker service inpspect`.
However, despite what is stated in the API docs, those objects are not present in the json returned by the GET /v1.28/service/{id} endpoint.

Below are the different output for the same service:
<details><summary>docker inspect output</summary>
<pre>
root@hosta:/home/cghislai# docker inspect slwksjopffpyist8s6377ptis
[
    {
        "ID": "slwksjopffpyist8s6377ptis",
        "Version": {
            "Index": 415670
        },
        "CreatedAt": "2017-04-11T22:50:08.710756004Z",
        "UpdatedAt": "2017-06-03T14:40:58.679541888Z",
        "Spec": {
            "Name": "proxy_apache2",
            "Labels": {
                "com.docker.stack.namespace": "proxy"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "hosta:5000/valuya/proxy:swarm-merge-2@sha256:055b78822db9b3c119a0705e594d4d692583a46cbfd455b4d3d568feabf8015d",
                    "Labels": {
                        "com.docker.stack.namespace": "proxy"
                    },
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "proxy_config",
                            "Target": "/etc/apache2",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "proxy_logs",
                            "Target": "/var/log",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "proxy_webroot",
                            "Target": "/var/www/html",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "letsencrypt-certificates",
                            "Target": "/etc/letsencrypt",
                            "VolumeOptions": {}
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {
                        "MemoryBytes": 1073741824
                    }
                },
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Constraints": [
                        "node.labels.role.proxy == true"
                    ]
                },
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "Networks": [
                {
                    "Target": "jqij1df2j8ouj9vbxonssp5a3",
                    "Aliases": [
                        "apache2"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 443,
                        "PublishedPort": 443,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "PreviousSpec": {
            "Name": "proxy_apache2",
            "Labels": {
                "com.docker.stack.namespace": "proxy"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "hosta:5000/valuya/proxy:swarm-merge-2@sha256:055b78822db9b3c119a0705e594d4d692583a46cbfd455b4d3d568feabf8015d",
                    "Labels": {
                        "com.docker.stack.namespace": "proxy"
                    },
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "proxy_config",
                            "Target": "/etc/apache2",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "proxy_logs",
                            "Target": "/var/log",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "proxy_webroot",
                            "Target": "/var/www/html",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "proxy"
                                }
                            }
                        },
                        {
                            "Type": "volume",
                            "Source": "letsencrypt-certificates",
                            "Target": "/etc/letsencrypt",
                            "VolumeOptions": {}
                        }
                    ]
                },
                "Resources": {
                    "Limits": {
                        "MemoryBytes": 1073741824
                    }
                },
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Constraints": [
                        "node.labels.role.proxy == true"
                    ]
                },
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "jqij1df2j8ouj9vbxonssp5a3",
                    "Aliases": [
                        "apache2"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 443,
                        "PublishedPort": 443,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 443,
                        "PublishedPort": 443,
                        "PublishMode": "ingress"
                    },
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 80,
                    "PublishMode": "ingress"
                },
                {
                    "Protocol": "tcp",
                    "TargetPort": 443,
                    "PublishedPort": 443,
                    "PublishMode": "ingress"
                },
                {
                    "Protocol": "tcp",
                    "TargetPort": 5000,
                    "PublishedPort": 5000,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "wyzjnl9m9atethbyevoiynxuj",
                    "Addr": "10.255.0.4/16"
                },
                {
                    "NetworkID": "jqij1df2j8ouj9vbxonssp5a3",
                    "Addr": "10.0.0.2/24"
                }
            ]
        }
    }
]
</pre>
</details>

<details><summary>API response body</summary>
<pre>
root@hosta:/home/cghislai# curl -sG http://localhost:4242/v1.28/services/slwksjopffpyist8s6377ptis | python -m json.tool
{
    "CreatedAt": "2017-04-11T22:50:08.710756004Z",
    "Endpoint": {
        "Ports": [
            {
                "Protocol": "tcp",
                "PublishMode": "ingress",
                "PublishedPort": 80,
                "TargetPort": 80
            },
            {
                "Protocol": "tcp",
                "PublishMode": "ingress",
                "PublishedPort": 443,
                "TargetPort": 443
            },
            {
                "Protocol": "tcp",
                "PublishMode": "ingress",
                "PublishedPort": 5000,
                "TargetPort": 5000
            }
        ],
        "Spec": {
            "Mode": "vip",
            "Ports": [
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 80,
                    "TargetPort": 80
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 443,
                    "TargetPort": 443
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 5000,
                    "TargetPort": 5000
                }
            ]
        },
        "VirtualIPs": [
            {
                "Addr": "10.255.0.4/16",
                "NetworkID": "wyzjnl9m9atethbyevoiynxuj"
            },
            {
                "Addr": "10.0.0.2/24",
                "NetworkID": "jqij1df2j8ouj9vbxonssp5a3"
            }
        ]
    },
    "ID": "slwksjopffpyist8s6377ptis",
    "PreviousSpec": {
        "EndpointSpec": {
            "Mode": "vip",
            "Ports": [
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 80,
                    "TargetPort": 80
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 443,
                    "TargetPort": 443
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 5000,
                    "TargetPort": 5000
                }
            ]
        },
        "Labels": {
            "com.docker.stack.namespace": "proxy"
        },
        "Mode": {
            "Replicated": {
                "Replicas": 1
            }
        },
        "Name": "proxy_apache2",
        "Networks": [
            {
                "Aliases": [
                    "apache2"
                ],
                "Target": "jqij1df2j8ouj9vbxonssp5a3"
            }
        ],
        "TaskTemplate": {
            "ContainerSpec": {
                "Image": "hosta:5000/valuya/proxy:swarm-merge-2@sha256:055b78822db9b3c119a0705e594d4d692583a46cbfd455b4d3d568feabf8015d",
                "Labels": {
                    "com.docker.stack.namespace": "proxy"
                },
                "Mounts": [
                    {
                        "Source": "proxy_config",
                        "Target": "/etc/apache2",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "proxy_logs",
                        "Target": "/var/log",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "proxy_webroot",
                        "Target": "/var/www/html",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "letsencrypt-certificates",
                        "Target": "/etc/letsencrypt",
                        "Type": "volume",
                        "VolumeOptions": {}
                    }
                ]
            },
            "ForceUpdate": 0,
            "Placement": {
                "Constraints": [
                    "node.labels.role.proxy == true"
                ]
            },
            "Resources": {
                "Limits": {
                    "MemoryBytes": 1073741824
                }
            },
            "RestartPolicy": {
                "Condition": "on-failure",
                "MaxAttempts": 0
            }
        }
    },
    "Spec": {
        "EndpointSpec": {
            "Mode": "vip",
            "Ports": [
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 80,
                    "TargetPort": 80
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 443,
                    "TargetPort": 443
                },
                {
                    "Protocol": "tcp",
                    "PublishMode": "ingress",
                    "PublishedPort": 5000,
                    "TargetPort": 5000
                }
            ]
        },
        "Labels": {
            "com.docker.stack.namespace": "proxy"
        },
        "Mode": {
            "Replicated": {
                "Replicas": 1
            }
        },
        "Name": "proxy_apache2",
        "Networks": [
            {
                "Aliases": [
                    "apache2"
                ],
                "Target": "jqij1df2j8ouj9vbxonssp5a3"
            }
        ],
        "TaskTemplate": {
            "ContainerSpec": {
                "Image": "hosta:5000/valuya/proxy:swarm-merge-2@sha256:055b78822db9b3c119a0705e594d4d692583a46cbfd455b4d3d568feabf8015d",
                "Labels": {
                    "com.docker.stack.namespace": "proxy"
                },
                "Mounts": [
                    {
                        "Source": "proxy_config",
                        "Target": "/etc/apache2",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "proxy_logs",
                        "Target": "/var/log",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "proxy_webroot",
                        "Target": "/var/www/html",
                        "Type": "volume",
                        "VolumeOptions": {
                            "Labels": {
                                "com.docker.stack.namespace": "proxy"
                            }
                        }
                    },
                    {
                        "Source": "letsencrypt-certificates",
                        "Target": "/etc/letsencrypt",
                        "Type": "volume",
                        "VolumeOptions": {}
                    }
                ]
            },
            "ForceUpdate": 0,
            "Placement": {
                "Constraints": [
                    "node.labels.role.proxy == true"
                ]
            },
            "Resources": {
                "Limits": {
                    "MemoryBytes": 1073741824
                }
            },
            "RestartPolicy": {
                "Condition": "on-failure",
                "MaxAttempts": 0
            }
        }
    },
    "UpdatedAt": "2017-06-03T14:40:58.679541888Z",
    "Version": {
        "Index": 415670
    }
}
</pre>
</details>

**Comment by cghislai** [comment]
which makes me think, where does `docker inspect` get this information from?

**Comment by thaJeztah** [comment]
If you did not specify custom values for these properties, those are the default values; docker 17.05 added an `insertDefaults` query parameter that allows you to have the daemon return those values when inspecting the service, e.g, see https://github.com/moby/moby/blob/df4ca50805baa1d1488d811e82125f607c8daa09/integration-cli/docker_api_swarm_service_test.go#L63

**Comment by cghislai** [comment]
Thanks I must have missed it. I guess it is only a matter of updating the API docs then.
I open another issue for that
