### ISSUE TITLE
Feature request: ability to specify retries for ADD with HTTP URL in Dockerfile

### ISSUE THREAD

**Issue by alex** [moby/moby#33514]
**Description**

The `ADD` command in a `Dockerfile` can take an HTTP(S) url, in which case moby will attempt to fetch the file and place it in the container. Due to the internet being horrible and unreliable, this means `Dockerfile`s which use this feature will ocassionally fail to build.

This could be mitigated by supporting retry policies of some sort. I don't feel strongly as to whether this should be configurable, or simply a default behavior (e.g. "Try up to 3 times, with exponential backoff between each attempt).

**Comment by cpuguy83** [comment]
I'm not sure if retires is right at this level since the builder has no real knowledge of the service being connected to.
Meanwhile the process running the build *can* trigger a restart and it will pick up exactly where it left off.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
