### ISSUE TITLE
API docs: query parameters missing for the GET /services/{id} endpoint

### ISSUE THREAD

**Issue by cghislai** [moby/moby#33515]
As seen there: https://github.com/moby/moby/blob/df4ca50805baa1d1488d811e82125f607c8daa09/integration-cli/docker_api_swarm_service_test.go#L63,
there is an `insertDefaults` query parameter not stated in the docs.

**Comment by ripcurld0** [comment]
call #dibs

**Comment by thaJeztah** [comment]
The property is actually already documented; see https://github.com/moby/moby/blame/d192db0d9350222d2b8bb6eba8525b04c3be7d61/api/swagger.yaml#L7730 (added as part of https://github.com/moby/moby/pull/32284), however, the documentation on docs.docker.com looks to only have full documentation for the "stable" channel/releases, so currently shows the API docs for 17.03.0, not 17.05 (edge) release.

There has been some discussion about that in the past, but perhaps it's best to open an issue in the docs repository; https://github.com/docker/docker.github.io/issues

**Comment by cghislai** [comment]
My bad I was looking at v1.28. This is actually already documented on docs.docker.com there: https://docs.docker.com/engine/api/v1.29/#operation/ServiceInspect

**Comment by thaJeztah** [comment]
Oh perfect! Thanks!
