### ISSUE TITLE
Filesystem layer verification failure with recent docker server

### ISSUE THREAD

**Issue by alfred-landrum** [moby/moby#33527]
I see a filesystem layer verification failure with recent docker server that is not present in 17.05. Specifically, in the `python:2.7` image, the `sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621` layer always fails.

A linux machine running from source:
```
root@vagrant:/home/vagrant#  docker pull python:2.7
2.7: Pulling from library/python
10a267c67f42: Already exists
fb5937da9414: Pull complete
9021b2326a1e: Pull complete
dbed9b09434e: Verifying Checksum
ea8a37f15161: Download complete
117a88c1a69a: Download complete
ed4ea3db1258: Download complete
35b9d3537ead: Download complete
filesystem layer verification failed for digest sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621
root@vagrant:/home/vagrant# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   e925820-unsupported
 Built:        Fri May 26 19:45:34 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

A mac running on the edge channel:
```
$ docker pull python:2.7
2.7: Pulling from library/python
10a267c67f42: Already exists
fb5937da9414: Pull complete
9021b2326a1e: Pull complete
dbed9b09434e: Verifying Checksum
ea8a37f15161: Download complete
117a88c1a69a: Download complete
ed4ea3db1258: Download complete
35b9d3537ead: Download complete
filesystem layer verification failed for digest sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621
(env) [alfred@alfred-laptop:~/src/go/src/github.com/docker/saas-mega/tools/hub-boss]
$ docker version
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:00:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by alfred-landrum** [comment]
Confirming it works with 17.03.1-ce:
```
$ docker pull python:2.7
2.7: Pulling from library/python
10a267c67f42: Pull complete
fb5937da9414: Pull complete
9021b2326a1e: Pull complete
dbed9b09434e: Pull complete
ea8a37f15161: Pull complete
117a88c1a69a: Pull complete
ed4ea3db1258: Pull complete
35b9d3537ead: Pull complete
Digest: sha256:2b1e4bad5c8805ca22f964cf14d3f5a16568787a5a1d6f84ec1c4b7d7ebc87ed
Status: Downloaded newer image for python:2.7
(env) [alfred@alfred-laptop:~/src/go/src/github.com/docker/saas-mega/tools/hub-boss]
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
The same is not visible with 17.05?

ping @tonistiigi @dmcgowan PTAL

marking this a P0 until we fully triaged

**Comment by thaJeztah** [comment]
fwiw, I'm not able to reproduce on my machine, but some base layers were already present in my case

```
docker pull python:2.7
2.7: Pulling from library/python
10a267c67f42: Already exists
fb5937da9414: Already exists
9021b2326a1e: Already exists
dbed9b09434e: Already exists
ea8a37f15161: Already exists
117a88c1a69a: Pull complete
ed4ea3db1258: Pull complete
35b9d3537ead: Pull complete
Digest: sha256:2b1e4bad5c8805ca22f964cf14d3f5a16568787a5a1d6f84ec1c4b7d7ebc87ed
Status: Downloaded newer image for python:2.7
```

**Comment by thaJeztah** [comment]
Interesting;

```
docker pull python@sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621
Error response from daemon: manifest for python@sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621 not found
```

**Comment by dmcgowan** [comment]
```
docker pull python@sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621
Error response from daemon: manifest for python@sha256:dbed9b09434efb583eb5f23173bf2aadb578cbfe2516e26226e3f7e458fac621 not found
```

Cannot pull a layer like that, the hash must refer to a manifest.

I also was no able to reproduce and I did not have the base layers already. Can you post the docker daemon logs during the failure? Also maybe try with a different graph driver and see if you reproduce it the same.

**Comment by thaJeztah** [comment]
Oh, thanks; yes, I misread, thought it was the digest for the manifest that was printed, but it's for a layer

**Comment by alfred-landrum** [comment]
I just re-installed edge (17.06.0-ce-rc1) on my mac, and I can't reproduce the error now either. :| If I can dig up the logs, I'll post them.

**Comment by drnybble** [comment]
I recently updated the Docker engine on our build machine to 
We have begun to see "filesystem layer verification failed for digest" failures when pulling images from our private registry. Any changes in this area?

Here is the log from the push of the image:

`15:02:27 The push refers to a repository [pa-docker:5000/planninganalytics/prism-proxy]
15:02:27 e2bed7908fd4: Preparing
15:02:27 6267c938fee5: Preparing
15:02:27 b1c085f5d5c7: Preparing
15:02:27 530be28824b6: Preparing
15:02:27 01c22c1b1931: Preparing
15:02:27 619b60371581: Preparing
15:02:27 1bbb3e0f6ae1: Preparing
15:02:27 ad9b27d6c34a: Preparing
15:02:27 9553d5289a80: Preparing
15:02:27 2c40c66f7667: Preparing
15:02:27 619b60371581: Waiting
15:02:27 1bbb3e0f6ae1: Waiting
15:02:27 ad9b27d6c34a: Waiting
15:02:27 9553d5289a80: Waiting
15:02:27 2c40c66f7667: Waiting
15:02:27 b1c085f5d5c7: Layer already exists
15:02:27 01c22c1b1931: Layer already exists
15:02:27 530be28824b6: Layer already exists
15:02:27 6267c938fee5: Layer already exists
15:02:28 1bbb3e0f6ae1: Layer already exists
15:02:28 9553d5289a80: Layer already exists
15:02:28 ad9b27d6c34a: Layer already exists
15:02:28 619b60371581: Layer already exists
15:02:29 2c40c66f7667: Layer already exists
15:02:39 e2bed7908fd4: Pushed
15:02:48 1.0.2721: digest: sha256:03c91028aca5f0fa5cfc0cdacf3128f2a3f92705925aaebdfcacc5da4d8689d2 size: 2408
15:02:48 Pushed pa-docker:5000/planninganalytics/prism-proxy:1.0.2721`

Here is the log of the failed pull:

`ca093528@duv-pa-jenkins1:~$ docker pull pa-docker:5000/planninganalytics/prism-proxy:1.0.2721
1.0.2721: Pulling from planninganalytics/prism-proxy
ad74af05f5a2: Downloading [=======>                                           ]   8.11MB/52.61MB
d0e2eed21380: Downloading [===============>                                   ]  9.142MB/28.69MB
3d7d0c8041ba: Download complete
394225d44fd6: Download complete
04b3864405e8: Download complete
1c1136797ed2: Download complete
3ad55ce3b004: Download complete
5a587abf6100: Download complete
19492dd77a1b: Download complete
e973cd34bdbe: Verifying Checksum
filesystem layer verification failed for digest sha256:e973cd34bdbee28e004d8dda17e85afbbb5df1920da7c1e8c95ee2cec9ddf075
`

**Comment by thaJeztah** [comment]
@drnybble could you open a new issue with details (requested details about your docker version, but also your registry, because you're using a local registry; does the registry show anything in the logs? how is it configured? Are you having the same problem pulling images from Docker Hub? Is it just with a specific image?)

**Comment by drnybble** [comment]
We are using registry:2 with redis:latest backed by Softlayer ObjectStore.
I have poked around the ObjectStore database and found that the 'data' file at this path is empty:

docker-registry/files/docker/registry/v2/blobs/sha256/e9/e973cd34bdbee28e004d8dda17e85afbbb5df1920da7c1e8c95ee2cec9ddf075

This makes me suspect a problem in the ObjectStore driver for registry or maybe ObjectStore itself (i.e., an upload that says it succeeded didn't really succeed).

**Comment by thaJeztah** [comment]
@drnybble if you suspect there's a bug, please open a new issue, that prevents possibly unrelated issues from being conflated 👍
