### ISSUE TITLE
Docker Swarm mode on Windows Containers: If --limit-cpu is specified the service does not get created.

### ISSUE THREAD

**Issue by stackempty** [moby/moby#33538]
**Description**

In docker swarm mode on windows containers, if --limit-cpu is specified the service does not get created. fails with "invalid option: Windows does not support CPUPeriod"

**Steps to reproduce the issue:**
1. Setup windows containers and swarm using the guides here https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode
2. Create a service on docker on windows with the command below.
``` 
docker service create --name iis --limit-cpu=0.25 microsoft/iis
```
3. View service details with 
```
docker service ps --no-trunc
```

**Describe the results you received:**

Service tasks do not get started.

```
C:\docker>docker service ps --no-trunc iis
ID                         NAME       IMAGE                                                                                         NODE           DESIRED STATE  CURRENT STATE           ERROR                                                 PORTS
zu114ig61kg7536jr4ubm2gtq  iis.1      microsoft/iis:latest@sha256:33903108e73e114f1c11c08292a9712dd9ae0020fae5175e616e9f2cb2011cb7  docker-win-02  Ready          Rejected 2 seconds ago  "invalid option: Windows does not support CPUPeriod"
twipa9qaydh80veqslr4xnh9w   \_ iis.1  microsoft/iis:latest@sha256:33903108e73e114f1c11c08292a9712dd9ae0020fae5175e616e9f2cb2011cb7  docker-win-02  Shutdown       Rejected 7 seconds ago  "invalid option: Windows does not support CPUPeriod"
o3ndl4ylo6ha9686e8ys80ipt   \_ iis.1  microsoft/iis:latest@sha256:33903108e73e114f1c11c08292a9712dd9ae0020fae5175e616e9f2cb2011cb7  docker-win-01  Shutdown       Rejected 8 seconds ago  "invalid option: Windows does not support CPUPeriod"

```

**Describe the results you expected:**

The service should get started with proper limits applied.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
WindowsContainers running in a VMWare VM.

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft @jstarks PTAL

**Comment by thaJeztah** [comment]
I don't have a Windows daemon running, but when using `--limit-cpu` on Linux, this request is created;

```json
{
  "EndpointSpec": {},
  "Mode": {
    "Replicated": {}
  },
  "Name": "web",
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Image": "nginx:alpine"
    },
    "ForceUpdate": 0,
    "Placement": {},
    "Resources": {
      "Limits": {
        "NanoCPUs": 250000000
      },
      "Reservations": {}
    },
    "RestartPolicy": {}
  },
  "UpdateConfig": {
    "FailureAction": "pause",
    "MaxFailureRatio": 0,
    "Parallelism": 1
  }
}
```


Which is converted to a container-config, and in when inspecting the container/task started, `CpuPeriod` and `CpuQuota` are both set;

```
"CpuPeriod": 100000,
"CpuQuota": 25000,
```

Which looks to be done in; [`containerconfig.resources()`](https://github.com/moby/moby/blob/v17.03.1-ce/daemon/cluster/executor/container/container.go#L399-L422), which in turn is called by
-> [`containerconfig.hostConfig()`](https://github.com/moby/moby/blob/v17.03.1-ce/daemon/cluster/executor/container/container.go#L336-L372)
-> [`containerAdapter.create()`](https://github.com/moby/moby/blob/v17.03.1-ce/daemon/cluster/executor/container/adapter.go#L218-L226)
-> [`controller.Prepare()`](https://github.com/moby/moby/blob/v17.03.1-ce/daemon/cluster/executor/container/controller.go#L152-L163)
-> Called by [SwarmKit agent](https://github.com/moby/moby/blob/v17.03.1-ce/vendor/github.com/docker/swarmkit/agent/exec/controller.go#L307-L312)


From what I can see, there's no Windows specific path followed there, resulting in the same options being set for Windows and Linux containers.

**Comment by thaJeztah** [comment]
Ok, so the interesting bit is that `docker run -cpus=0.25` does not perform a conversion to `CpuPeriod` / `CpuQuota` - inspecting the container shows only `"NanoCpus": 250000000`, and both `CpuPeriod` and `CpuQuota` are `0` (for a Linux container)

**Comment by riker09** [comment]
I am affected by this.

```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

docker-compose.yml
```
version: '3.3'
services
  db:
    image: microsoft/mssql-server-windows-express
    environment:
      - "ACCEPT_EULA=Y"
      - "sa_password=<SUPERSECRETPW>"
      resources:
        limits:
          cpus: '0.80'
          memory: 4G
```

docker service ps dmforce --no-trunc
```
ID                          NAME                 IMAGE                                                                                                                         NODE                DESIRED STATE       CURRENT STATE             ERROR                                                  PORTS
nv9mh1q1x1eq1an4f6eggtapz   myproject_db.1         microsoft/mssql-server-windows-express:latest@sha256:0e8a87f22ad414a7c6a4b30122812e3d66043c8a6541aaed2ecf73020ffd8767         MYHOSTNAME          Ready               Rejected 2 seconds ago    "invalid option: Windows does not support CPUPeriod"
oe6sz3nyzttntudvdpcdc035k    \_ myproject_db.1     microsoft/mssql-server-windows-express:latest@sha256:0e8a87f22ad414a7c6a4b30122812e3d66043c8a6541aaed2ecf73020ffd8767         MYHOSTNAME          Shutdown            Rejected 4 seconds ago    "invalid option: Windows does not support CPUPeriod"
yainov2w58v2ms4bhtqziaviy    \_ myproject_db.1     microsoft/mssql-server-windows-express:latest@sha256:0e8a87f22ad414a7c6a4b30122812e3d66043c8a6541aaed2ecf73020ffd8767         MYHOSTNAME          Shutdown            Rejected 12 seconds ago   "invalid option: Windows does not support CPUPeriod"
fyowtbnuib8xo607e91xsnaeg    \_ myproject_db.1     microsoft/mssql-server-windows-express:latest@sha256:0e8a87f22ad414a7c6a4b30122812e3d66043c8a6541aaed2ecf73020ffd8767         MYHOSTNAME          Shutdown            Rejected 14 seconds ago   "invalid option: Windows does not support CPUPeriod"
gnhsf0nwkunm5g7v49iij9ihs    \_ myproject_db.1     microsoft/mssql-server-windows-express:latest@sha256:0e8a87f22ad414a7c6a4b30122812e3d66043c8a6541aaed2ecf73020ffd8767         MYHOSTNAME          Shutdown            Rejected 22 seconds ago   "invalid option: Windows does not support CPUPeriod"
```

**Comment by IAPOLINARIO** [comment]
Hey guys,
Any update on this issue? Is there a different way to deploy in a swarm mode setting the CPU limitation for Windows Containers? 

I'm getting the same error as @riker09 and @stackempty.

**Comment by abjinugu** [comment]
it has been more than a year now.. 👎

**Comment by dougouk** [comment]
I'm also affected by this. Any updates?

**Comment by karlholbrook** [comment]
If it is not possible to limit the cpu usage of a windows container using a docker stack file then swarm is no use to me. I will wait for windows container support in kubernetes, which I believe will be released very soon. 
So disappointing.
