### ISSUE TITLE
Container won't build on 2016, but builds on windows 10.

### ISSUE THREAD

**Issue by gregpakes** [moby/moby#33532]
Referencing issue: docker/for-win#791

I have created a relatively simple dockerfile, which works fine on Windows 10 (hyper-v), but fails to build on windows 2016 (**both in hyperv and process isolation**).

The error is when I attempt to delete a directory.  On Windows 10 it removes the folder fine, on Windows 2016, I get the following error:

> Remove-Item : Cannot remove item C:\xxxx\xxxx: There are no more files.

The command that fails is:

> RUN Remove-Item $env:root_path -recurse -force

I have spent a long time looking into this and I really don't think it's a general powershell issue.  I think it is something about docker on windows 2016 causing this issue.  The error "there are no more files", seems to be very rare.  Google barely returns anything for it.  The issue also exists if I try and use RMDIR directly rather than Remove-Item.

The dockerfile in questions is below:

```
FROM microsoft/iis

LABEL maintainer "Greg Pakes"

SHELL ["powershell", "-command"]

ENV ROOT_PATH 'c:\DummyPath'


# Root Application Creation
RUN $rootApplicationPath = Join-Path $env:Root_Path 'Site\Root'; \
	New-Item -Path $rootApplicationPath -ItemType Directory -Force | Out-Null;
	
RUN Remove-Item $env:root_path -recurse -force
```

**Information**

Windows 2016

`docker version`

```
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

`docker info`

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 84
Server Version: 17.03.0-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: az-tfs-agent
ID: 5EFA:46HH:VGJX:7S6P:EMTE:A4W2:KCJB:XF4I:EO6F:IHBE:KVWU:5JMU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Windows 10

`docker version`

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

`docker info`

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 99
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.82 GiB
Name: iSAMS-LAP-GREG3
ID: H5EZ:EK42:BS6Y:FC3X:TRWA:YDP5:5RCT:ZZ3U:VJ7K:GTOC:C4Y5:ZDXK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 103
 System Time: 2017-06-06T09:01:57.9176756+10:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by friism** [comment]
cc @jhowardmsft

**Comment by thaJeztah** [comment]
Can you also provide the information asked for in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue?

- provide the output of `docker version`
- provide the output of `docker info`

**Comment by gregpakes** [comment]
@thaJeztah Updated the original post

**Comment by thaJeztah** [comment]
Thanks!

**Comment by richardgavel** [comment]
From your issue in docker/for-win, it sounds like you are mounting a directory from the host into the Docker container. I have, unsuccessfully, been working on a Docker container where there is file manipulation of the mounted directory with various issues, as well...Access denied, File in use, etc. This is for a CI server, and I do not get these issues when I copy the files into the container from the mount and run the same process. So it seems like the issue related to volume mounting. Note, my issues are with Win 10 (so hyper-v containers).

**Comment by gregpakes** [comment]
@richardgavel - So the end result for this container is exactly as you describe.  But the dockerfile above fails to build and there is no folder mapping involved, so I don't see how it can be related.

**Comment by Jazun713** [comment]
Seeing this same thing with 17.03 and 17.06.ee

I've tried remove-item, [System.IO.Directory]::Delete and gci path | remove-item with the same result.

We've also tried to wrap the command with logic:
RUN "if ((gci 'C:\vs_studio2015').Count -ne 0) {[System.IO.Directory]::Delete('c:\vs_studio2015', $true)} else {Write-Host 'Aint no files'}"

I get: 
Exception calling "Delete" with "2" argument(s): "There are no more files.
or:
Remove-Item : Cannot remove item C:\vs_studio2015\OfflineCache\feeds\latest:
There are no more files.

**Comment by shangyuwang** [comment]
Do we have a solution for this? I run into the same issue when trying to delete a directory inside a Windows container hosted on Windows 2016.
System.IO.IOException: There are no more files.

**Comment by jhowardmsft** [comment]
I can verify that it's a platform bug, not a docker bug and repro this on RS1, but not on an RS5 (soon to be released Windows Server 2019 aka "1809").  I haven't validated on RS4/1803 though. At this point, if it's critical this needs a backport, there would need to be a paid support case opened with Microsoft for further investigation. (No, I don't know what the actual platform fix was - a huge amount has changed since RS1 to today.). The workaround is to, on Windows Server, use `--isolation=hyperv` for the build step (Windows Server runs containers by default with process isolation, Windows 10 runs containers by default with Hyper-V isolation, and is the only mode it supports). For this reason, there's nothing that can be done here, so closing this issue.

**Comment by helzgate** [comment]
Just for others that land here because of Google... I had this "There are no more files" error because I was trying to delete in a seperate run layer than my previous run command where I extracted the files.  After I moved my delete command to the same run stage my extract was in, everything worked fine.
