### ISSUE TITLE
[17.06-rc1] Network inspect is showing containers when `docker ps -a` does not show any containers. Experiencing other issues as well potentially related to or cause by this

### ISSUE THREAD

**Issue by shivmpatel12** [moby/moby#33530]
**Description**

When I do `docker network inspect <network name>` it shows running containers, but when I do `docker ps -a` it doesn't show any containers. Possibly because of this I cannot remove the network since I always get back `Error response from daemon: network <network name> id <network id> has active endpoints`. 

Additionally, whenever I try creating new services using `docker service create -e "VIRTUAL_HOST=http://*:80/hello" -e SERVICE_PORTS=80 --network <network name> --name hello-world1 dockercloud/hello-world` the service randomly fails to deploy containers giving back error `starting container failed: Address already in use"

Another possible related issue is me trying to create and add service to the current network and getting `Error response from daemon: network server-proxy-network not found`. But then when I try to remove the same network I get `Error response from daemon: network server-proxy-network id luc33yj6ivd71i1j0pw8nsgnd has active endpoints`

**Steps to reproduce the issue:**
1. Initialize new swarm
2. Create network with `docker network create <network name> --driver overlay`
3. Use `docker service create -e "VIRTUAL_HOST=http://*:80/hello" -e SERVICE_PORTS=80 --network <network name> dockercloud/hello-world` to add services and `docker service rm <service name>` to remove services
4. After checking the network I now see inconsistencies, and get the errors described above when I try to make services.

**Describe the results you received:**
I expected would get that the new services I tried to create have 0/1 replicas and upon inspection I see that the service failed to deploy a container with the error from above. 

**Describe the results you expected:**
I expected to be able to create new services that deployed containers. Also I expected to not see any containers in the network when typing `docker ps -a` does not return any containers. I expected to be able to add a service to a network that exists.

**Additional information you deem important (e.g. issue happens only occasionally):**
Unsure if this is relevant but before I noticed the issue I used `lsof -ti:8080 | xargs kill -9` to reset the port since I was getting error `bind: Address already in use` when trying to use the port

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:00:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: lgd0t04ke9dsx5k41z4yn4eht
 Is Manager: true
 ClusterID: nd7etdrcv66turyvd97c1ac48
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 992a5be178a62e026f4069f443c6164912adbf09
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.30-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 6GMO:KCER:SQTK:DFXE:QSMT:WCEC:FEB5:JU4G:G54S:E27K:TNY7:ZLPY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 211
 System Time: 2017-06-05T20:59:09.73386406Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by amitripshtos** [comment]
Happens to me also today, docker network inspect shows the container, while ps -a does not.
In addition I can see that docker-proxy listens to my port, while nobody actually using it.

Only restart of docker service solves that issue (which is problematic in production)

**Comment by thaJeztah** [comment]
ping @fcrisciani any information that would help debugging?

**Comment by thaJeztah** [comment]
ping @fcrisciani is this resolved through https://github.com/docker/libnetwork/pull/1878 ?

**Comment by fcrisciani** [comment]
@thaJeztah don't think that PR addresses this case

**Comment by scottbelden** [comment]
I saw this today with docker version 17.05.0-ce. Has it been resolved in a newer version of docker?
