### ISSUE TITLE
Docker with Traefik running inside swarm manager as a service is not able to redirect requests to services that are in the same overlay network outside from the manager to other service in worker nodes.

### ISSUE THREAD

**Issue by gdeverlant** [moby/moby#33531]
Please see this ticket for further details description https://github.com/hypriot/image-builder-odroid-c1/issues/42

**Comment by thaJeztah** [comment]
Looking at the linked discussion, networking within the same node is working, but not between nodes? In that case, it sounds that overlay networking is not working, which may be due to a configuration of the kernel, or because ports are not open between the nodes.

Can you simplify the steps to reproduce, to take traefik out of the equation? e.g. if you;

```
docker network create -d overlay testnet

docker service create --name web --network testnet --replicas=3 nginx:alpine
```

Is network traffic possible between the containers backing that service (running on different nodes?)

**Comment by gdeverlant** [comment]
iptables **manager node**

```
$ sudo iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2377
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7946
ACCEPT     udp  --  anywhere             anywhere             udp dpt:7946
ACCEPT     udp  --  anywhere             anywhere             udp dpt:4789
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2375
```

iptables **worker node**

```
$ sudo iptables -L INPUT --line-number
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7946
2    ACCEPT     udp  --  anywhere             anywhere             udp dpt:7946
3    ACCEPT     udp  --  anywhere             anywhere             udp dpt:4789
4    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2375
5    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2377
```

**Comment by gdeverlant** [comment]
simple test with whoami armhf version

```
docker network create -d overlay testnet

docker service create -d --name whoami --network testnet --replicas=2 -p 80:8000 --constraint node.labels.arch==arm32 hypriot/rpi-whoami
```

access url : **[](http://cluster.publicvm.com/)**

Browser always returns the same id : 

![image](https://cloud.githubusercontent.com/assets/26530975/26810655/3668b1aa-4a6d-11e7-9832-37b936f1ed15.png)

**Comment by gdeverlant** [comment]
Please check the following test: https://github.com/hypriot/image-builder-odroid-c1/issues/42#issuecomment-306555636

**Comment by thaJeztah** [comment]
Looking at https://github.com/hypriot/image-builder-odroid-c1/issues/43#issuecomment-306680711 this may be a kernel issue on your system, but perhaps @StefanScherer or @alexellis can fill me in

**Comment by gdeverlant** [comment]
I hope that someone is going to help with this one 👍

**Comment by gdeverlant** [comment]
@thaJeztah Could it be that it is a VXLAN driver bug? Is it possible to update the VXLAN driver to a more recent one and if YES how to do so?

**Comment by gdeverlant** [comment]
This problem dissapeared when I upgraded my kernel to 4.12 mainline.

It is definitely a kernel problem.
