### ISSUE TITLE
Windows Hyper-V behind Proxy can't pull any image

### ISSUE THREAD

**Issue by erikbgithub** [moby/moby#33543]
**Description**

I have installed a fresh latest docker on my windows in hyper-v. A simple `docker pull nginx` lists the files it needs to pull from the internet, but doesn't pull them. Sometimes it starts to download one (the output changes from <hash> to `[>   ]`, sometimes it says something like `restarting in x seconds`). Then nothing. No Timeout, no Error, no Logs, nothing.

**Steps to reproduce the issue:**
1. Use Windows 10
2. Have a proxy, for instance at `http:proxy:8080`
3. (optionally) use your own DNS server to resolve `proxy` (this got me one hickup further before hanging).

**Describe the results you received:**

Hanging output:

```
PS C:\WINDOWS\system32> docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
ff3d52d8f55f: Pulling fs layer
226f4ec56ba3: Retrying in 1 second
53d7dd52b97d: Download complete
```

**Describe the results you expected:**

It pulls the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.941 GiB
Name: moby
ID: 2R6T:5F4H:YJGJ:XGNZ:M4BI:QCDB:EUSH:5LTU:RANC:QURS:YWOX:AIUA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 22
 System Time: 2017-06-07T08:32:46.1613507Z
 EventsListeners: 0
Http Proxy: http://proxy:8080
Https Proxy: http://proxy:8080
No Proxy: localhost,127.0.0.1,my.corp
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

See above: Win 10, http://proxy:8080, dns server to resolve "proxy" and possible other local links like the local docker registry.

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue;

Also provide the output of `docker info`

How did you configure your daemon to use the proxy? Is it configured through `HTTP_PROXY` environment variables? Looking at the output of `docker info`, you're running Linux containers (not native windows containers); what configuration did you set in the configuration panel? https://docs.docker.com/docker-for-windows/#proxies

This issue may be specific to Docker for Windows, in which case it's better reported in that issue tracker (https://github.com/docker/for-win/issues)

**Comment by erikbgithub** [comment]
Thanks for looking into this issue @thaJeztah 

Actually I'm using the template, it's just quite confusing when it's not formatted, so I missed that there is a separate `docker version` and `docker info` part. I've updated the content and will reference it in an issue at the `for-win` side.

**Comment by thaJeztah** [comment]
closing, as this went stale
