### ISSUE TITLE
Restart Policies on Windows Containers still not working on server reboot

### ISSUE THREAD

**Issue by drnybble** [moby/moby#33542]
**Description**

Defect https://github.com/moby/moby/issues/27544 describes a problem where the Docker service does not have a dependency on ConDrv and this causes containers to not start on a system reboot.

Although that issue is Closed the problem does not appear to be fixed.

**Steps to reproduce the issue:**
1. Follow the steps at https://store.docker.com/editions/enterprise/docker-ee-server-windows to install Docker for Windows 2016:

Install-Module -Name DockerMsftProvider -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force
Restart-Computer -Force

2. Check the service configuration: Open a CMD prompt and type sc.exe qc docker

3. Check Dependencies, it should show ConDrv

**Describe the results you received:**

Dependencies is blank. Confirmed on multiple systems.

**Describe the results you expected:**

Dependencies includes ConDrv.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\Administrator>
```

**Output of `docker info`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\Administrator> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 171
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: WIN-MJSFDPF05F4
ID: TWMY:IFT5:SD65:U72L:6TEM:UKYA:KDMS:JQC3:VQKN:7UGR:57IB:G23Q
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
@darrenstahlmsft

**Comment by drnybble** [comment]
Pinging @darrenstahlmsft as requested

**Comment by darrenstahlmsft** [comment]
Thanks @drnybble!

For a workaround, you can use:

```
sc.exe config docker depends= ConDrv
```

OR

```
dockerd.exe --unregister-service
dockerd.exe --register-service
```

Can you check if either of these fix the problem for you?

I suspect this is a result of the installer registering the service without using `dockerd.exe --register-service` but instead using its own service registration. I'm contacting the internal Microsoft folks who maintain this.

As a side note. This dependency is only necessary in RS1 builds (14393, your build, is RS1 and as such should have this dependency). Builds newer than 14393 do not need this dependency as it is in the platform.

**Comment by drnybble** [comment]
If you unregister & register the service as you describe, the ConDrv dependency is in place. So it seems that following the instructions on the Docker Store is the problem.

**Comment by drnybble** [comment]
@darrenstahlmsft Any updates? People are still installing broken Docker setups on Windows.

**Comment by drnybble** [comment]
Workaround above should be:
sc.exe config docker depend=ConDrv

**Comment by jhowardmsft** [comment]
@taylorb-microsoft - ^^ is that you?

**Comment by drnybble** [comment]
Still not fixed....

**Comment by jhowardmsft** [comment]
Fixed by https://github.com/OneGet/MicrosoftDockerProvider/pull/54. Closing.
