### ISSUE TITLE
deploy insecure docker registry on a host who's port 443 is binded by other program lead to push failure

### ISSUE THREAD

**Issue by silenceshell** [moby/moby#33564]
**Description**

**Steps to reproduce the issue:**
1. deploy a program which binds port 443
2. install docker, and add '--insecure-registry mydomain.com'  and restart docker service
2. deploy docker registry:2, use port 80:5000(insecure registry is enough for my env)
3. try to push an image to the registry.

**Describe the results you received:**

```
docker push mydomain.com/x/centos:7.2.1511
The push refers to a repository [mydomain/x/centos]
c411e76031a4: Preparing 
Error: Status 405 trying to push repository x/centos: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for the URL /v1/repositories/x/centos/.</p>\n</body></html>\n"
```

```
747 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.132150136+08:00" level=debug msg="Calling POST /v1.24/images/mydomain.com/x/centos/push?tag=7.2.1511"
748 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.132345310+08:00" level=debug msg="Trying to push mydomain.com/x/centos to https://mydomain.com v2"
749 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.139081136+08:00" level=debug msg="Pushing repository: mydomain.com/x/centos:7.2.1511"
750 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.139480476+08:00" level=debug msg="Pushing layer: sha256:c411e76031a46fb5cf1651ce87b9efea48d151705808582ab32b208b885cb800
    "
751 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.144883760+08:00" level=error msg="Upload failed: error parsing HTTP 404 response body: invalid character '<' looking for
     beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested UR
    L /v2/x/centos/blobs/uploads/ was not found on this server.</p>\\n</body></html>\\n\""
752 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.145081815+08:00" level=error msg="Attempting next endpoint for push after error: error parsing HTTP 404 response body: i
    nvalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not 
    Found</h1>\\n<p>The requested URL /v2/x/centos/blobs/uploads/ was not found on this server.</p>\\n</body></html>\\n\""
753 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.145145073+08:00" level=debug msg="Skipping non-TLS endpoint http://mydomain.com for host/port that appears to use
    TLS"
754 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.145169721+08:00" level=debug msg="Trying to push mydomain.com/x/centos to https://mydomain.com v1"
755 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.145291510+08:00" level=debug msg="attempting v1 ping for registry endpoint https://mydomain.com/v1/"
756 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150299673+08:00" level=debug msg="Error unmarshalling the _ping PingResult: invalid character '<' looking for beginning 
    of value"
757 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150317668+08:00" level=debug msg="PingResult.Version: \"\""
758 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150325587+08:00" level=debug msg="Registry standalone header: ''"
759 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150330576+08:00" level=debug msg="PingResult.Standalone: true"
760 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150336454+08:00" level=debug msg="Endpoint https://mydomain.com/v1/ is eligible for private registry. Enabling dec
    orator."
761 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150632015+08:00" level=debug msg="Pushing ID: feac5e0dfdb25597c61e19bf3c0a51bb865e7ba5e210eaca66648c02e0ff0d61 with Tag:
     7.2.1511"
762 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150658286+08:00" level=debug msg="[registry] PUT https://mydomain.com/v1/repositories/x/centos/"
763 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.150664010+08:00" level=debug msg="Image list pushed to index:\n[{\"id\":\"feac5e0dfdb25597c61e19bf3c0a51bb865e7ba5e210ea
    ca66648c02e0ff0d61\",\"Tag\":\"7.2.1511\"}]"
764 Jun  7 17:04:35 start dockerd[26596]: time="2017-06-07T17:04:35.155386007+08:00" level=error msg="Not continuing with push after error: Error: Status 405 trying to push repository dtdr
    eam/centos: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>405 Method Not Allowed</title>\\n</head><body>\\n<h1>Method Not Allowed</h1>\\n<p>The req
    uested method PUT is not allowed for the URL /v1/repositories/x/centos/.</p>\\n</body></html>\\n\""
```

**Describe the results you expected:**

I added the '--insecure-registry' parameter to docker daemon, so I expected it to use `http://` other than `https://`

If I didnot deploy the program which bind port 443, `docker push` works well. Docker client use `https://` for the first time, and the registry host will return an ICMP unreachable package to the docker client immedietaly, and the docker client will continue to use `http://` to push image to registry.

But If port 443 is binded, no ICMP unreachable package was received, and tls transport DOES works, except different protocals and docker client push to `https://` registry failed. But docker client think this host/port is using TLS(transportOK), and add it to map `confirmedTLSRegistries`. After that, docker client just skip `http://` because `Skipping non-TLS endpoint %s for host/port that appears to use TLS`.

I think docker should check whether this host/port is mentioned in `--insecure-registry`, if so, do not put it to `confirmedTLSRegistries`, and allow it to use `http://` to push images.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 13
Running: 0
Paused: 0
Stopped: 13
Images: 56
Server Version: 1.12.6
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 121
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: start
ID: RSSY:MRNB:OIWT:7LRN:HU75:37U4:4KND:7S5Y:TPJK:JW2T:QGC2:TEQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 14
Goroutines: 22
System Time: 2017-06-07T17:11:50.006834718+08:00
EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
mydomain.com
127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by thaJeztah** [comment]
Insecure registries will still attempt;

- connecting over TLS
- if TLS is enabled, but no valid certificate; communicate over TLS with that certificate
- if no TLS is enabled, fall back to non-TLS

Since you did not specify a port in your registry, docker will use the default ports for the above (443, then 80); does it work if you specify your registry _including_ the port (`docker push mydomain.com:80/......`)?

Having said the above; I'd really discourage running a registry without TLS enabled.

**Comment by silenceshell** [comment]
It didnot work. 

```
docker push mydomain.com:80/x/centos:7.2.1511
The push refers to a repository [mydomain.com:80/x/centos]
Get https://mydomain.com:80/v1/_ping: http: server gave HTTP response to HTTPS client
```

Here is debugging log.

```
838 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.930829814+08:00" level=debug msg="Calling POST /v1.24/images/mydomain.com:80/x/centos/push?tag=7.2.1511"
839 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.930995037+08:00" level=debug msg="hostDir: /etc/docker/certs.d/mydomain.com:80"
840 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.931011692+08:00" level=debug msg="hostDir: /etc/docker/certs.d/mydomain.com:80"
841 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.931038004+08:00" level=debug msg="Trying to push mydomain.com:80/x/centos to https://mydomain.com:80 v
    2"
842 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.932366102+08:00" level=debug msg="Error getting v2 registry: Get https://mydomain.com:80/v2/: http: server gave HT
    TP response to HTTPS client"
843 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.932393557+08:00" level=error msg="Attempting next endpoint for push after error: Get https://mydomain.com:80/v2/: 
    http: server gave HTTP response to HTTPS client"
844 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.932408867+08:00" level=debug msg="Trying to push mydomain.com:80/x/centos to https://mydomain.com:80 v
    1"
845 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.932420950+08:00" level=debug msg="hostDir: /etc/docker/certs.d/mydomain.com:80"
846 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.932475282+08:00" level=debug msg="attempting v1 ping for registry endpoint https://mydomain.com:80/v1/"
847 Jun  7 18:53:06 start dockerd[26596]: time="2017-06-07T18:53:06.933465107+08:00" level=error msg="Attempting next endpoint for push after error: Get https://mydomain.com:80/v1/_p
    ing: http: server gave HTTP response to HTTPS client"
```

Docker DOES try to use port 80, but in the previous step which used port 443, docker marked the host(mydomain.com) as using TLS(but wrong). So the `http://` (port 80) endpoint is **skipped**.

distribution/push.go

```go
func Push(ctx context.Context, ref reference.Named, imagePushConfig *ImagePushConfig) error {
...
	var (
...
		// confirmedTLSRegistries is a map indicating which registries
		// are known to be using TLS. There should never be a plaintext
		// retry for any of these.
		confirmedTLSRegistries = make(map[string]struct{})
	)

	for _, endpoint := range endpoints {
...
		if endpoint.URL.Scheme != "https" {    //~~~ HERE SKIPED ~~~
			if _, confirmedTLS := confirmedTLSRegistries[endpoint.URL.Host]; confirmedTLS {
				logrus.Debugf("Skipping non-TLS endpoint %s for host/port that appears to use TLS", endpoint.URL)
				continue
			}
		}

		pusher, err := NewPusher(ref, endpoint, repoInfo, imagePushConfig)
		if err != nil {
			lastErr = err
			continue
		}
		if err := pusher.Push(ctx); err != nil {
			// Was this push cancelled? If so, don't try to fall
			// back.
			select {
			case <-ctx.Done():
			default:     //~~~~ HERE ADDED ~~~~
				if fallbackErr, ok := err.(fallbackError); ok {
					confirmedV2 = confirmedV2 || fallbackErr.confirmedV2
					if fallbackErr.transportOK && endpoint.URL.Scheme == "https" {
						confirmedTLSRegistries[endpoint.URL.Host] = struct{}{}
					}
					err = fallbackErr.err
					lastErr = err
					logrus.Infof("Attempting next endpoint for push after error: %v", err)
					continue
				}
			}
```

BTW, in version 1.10.3, docker works fine in this situation, because there is no `confirmedTLSRegistries`. It just failed on port 443 and continue pushing on port 80. I found this problem when I upgrade docker from 1.10.3 to 1.12.6.

**Comment by thaJeztah** [comment]
> but in the previous step which used port 443, docker marked the host(mydomain.com) as using TLS(but wrong).

In your last output, port 443 is never used, so I don't think the problem is there.

I _do_ see this being logged;

```
hostDir: /etc/docker/certs.d/mydomain.com:80
```

Do you have a certificate in that directory? What happens if you remove or rename that directory, and restart the daemon?

**Comment by silenceshell** [comment]
There is noting in `/etc/docker/certs.d/`.

> msg="Trying to push mydomain.com:80/x/centos to https://mydomain.com:80 v2"

The `https://mydomain.com:80` means, Docker client connected sever's port 443. Am I right?

I also captured tcp packages. Docker client connected port 443 on server, BUT the server is not docker registry, it is my another service, noting related to registry. 

![packages](http://7xir15.com1.z0.glb.clouddn.com/Screenshot%20from%202017-06-07%2019-49-12.png)

It should continued to connect port 80 on server, but it did not. I have show you the code why it refused to connect `http://`.

**Comment by thaJeztah** [comment]
> The https://mydomain.com:80 means, Docker client connected sever's port 443. Am I right?

It should connect to port 80 there, but using a TLS connection, which fails (expectedly), given the error message that follows;

```
server gave HTTP response to HTTPS client
```

However, looking at the `hostDir: /etc/docker/certs.d/mydomain.com:80` message; that message is only output if the daemon does not treat the registry as an insecure registry; see [registry/registry.go#L34-L40](https://github.com/moby/moby/blob/66a5e34cc4a0bdf654010211baa2070bbe38ba3c/registry/registry.go#L34-L40);

```go
if isSecure && CertsDir != "" {
	hostDir := filepath.Join(CertsDir, cleanPath(hostname))
	logrus.Debugf("hostDir: %s", hostDir)
	if err := ReadCertsDirectory(tlsConfig, hostDir); err != nil {
		return nil, err
	}
}
```

I see your daemon is configured using `mydomain.com` as insecure registry, not `mydomain.com:80`. I don't think docker does "matching", i.e. `mydomain.com` is not automatically matched to `mydomain.com`; therefore it doesn't pick up that registry as insecure, so doesn't fall back to `http://` afterwards.

If insecure registries is enabled, it will continue attempting `http://` after all `https://` endpoints failed; Here's the output on a 17.06 daemon (which does not attempt v1 connections, so logs are slightly shorter);

```
level=debug msg="Calling POST /v1.30/images/nginx:alpine/tag?repo=localhost%3A80%2Ffoobar&tag=latest"
level=debug msg="Calling GET /_ping"
level=debug msg="Calling POST /v1.30/images/localhost:80/foobar/push?tag="
level=debug msg="Trying to push localhost:80/foobar to https://localhost:80 v2"
level=debug msg="Error getting v2 registry: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"
level=info msg="Attempting next endpoint for push after error: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"
level=debug msg="Trying to push localhost:80/foobar to http://localhost:80 v2"
level=debug msg="Pushing repository: localhost:80/foobar:latest"
```

**Comment by silenceshell** [comment]
> level=debug msg="Error getting v2 registry: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"
level=info msg="Attempting next endpoint for push after error: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"

This is the key. 

- In your environment, Docker client(`https://`) tried to connect port 443, but there is only a `http://` server, so docker client got an transport error, while `fallbackErr.transportOK` is still false, so docker client will continue to connect port 80.
- In my envrionment, there is a server listening on port 443 which is not docker registry, so when docker client(`https://`) tried to connect port 443, they did have an interaction. Here is my log:

```
level=debug msg="Calling POST /v1.24/images/mydomain.com/x/centos/push?tag=7.2.1511"
level=debug msg="Trying to push mydomain.com/x/centos to https://mydomain.com v2"
level=debug msg="Pushing repository: mydomain.com/x/centos:7.2.1511"
level=debug msg="Pushing layer: sha256:c411e76031a46fb5cf1651ce87b9efea48d151705808582ab32b208b885cb800"
level=error msg="Upload failed: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested URL /v2/x/centos/blobs/uploads/ was not found on this server.</p>\\n</body></html>\\n\""
level=error msg="Attempting next endpoint for push after error: error parsing HTTP 404response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested URL /v2/x/centos/blobs/uploads/ was not found on this server.</p>\\n</body></html>\\n\""
```
But the server does understand docker client, so docker client failed to push images.
I guess in this situation `fallbackErr.transportOK` is set to true, so the host is putted in jail `confirmedTLSRegistries`, and won't fall back to `http://`.

```go
		if endpoint.URL.Scheme != "https" {
			if _, confirmedTLS := confirmedTLSRegistries[endpoint.URL.Host]; confirmedTLS {
				logrus.Debugf("Skipping non-TLS endpoint %s for host/port that appears to use TLS", endpoint.URL)
				continue
			}
		}
...
					if fallbackErr.transportOK && endpoint.URL.Scheme == "https" {
						confirmedTLSRegistries[endpoint.URL.Host] = struct{}{}
					}
```

I think if a host is `inseucre-registry`, docker should not put it in `confirmedTLSRegistries`, even transport is ok.

**Comment by thaJeztah** [comment]
> In your environment, Docker client(https://) tried to connect port 443, but there is only a http:// server, so docker client got an transport error, while fallbackErr.transportOK is still false, so docker client will continue to connect port 80.

No, docker does not try to connect to port 443, because port 80 is explicitly included. It only tries to connect to port 80 (first using https:// then using http://)

I just started a simple nginx server that's configured on port 443 (tls). When pushing **without** specifying port `80`, this is what happens (I stripped timestamps for readability);

```
msg="Calling GET /_ping"
msg="Calling POST /v1.30/images/localhost/test/push?tag="
msg="Trying to push localhost/test to https://localhost v2"
msg="Error getting v2 registry: Get https://localhost/v2/: net/http: TLS handshake timeout"
msg="Attempting next endpoint for push after error: Get https://localhost/v2/: net/http: TLS handshake timeout"
msg="Trying to push localhost/test to http://localhost v2"
msg="Pushing repository: localhost/test:latest"
msg="Checking for presence of layer sha256:c0de73ac99683640bc8f8de5cda9e0e2fc97fe53d78c9fd60ea69b31303efbc9 (sha256:bd4b2003aa95476960707817a2c050b9496759e2d9038056d44a8d1bf37a38dd) in localhost/test"
msg="Pushing layer: sha256:c0de73ac99683640bc8f8de5cda9e0e2fc97fe53d78c9fd60ea69b31303efbc9"
msg="Assembling tar data for cf9b5807e34fee624682a218880383e8802623241d0614325b3b9c161fd08e03"
msg="uploaded layer sha256:c0de73ac99683640bc8f8de5cda9e0e2fc97fe53d78c9fd60ea69b31303efbc9 (sha256:bd4b2003aa95476960707817a2c050b9496759e2d9038056d44a8d1bf37a38dd), 701102 bytes"
```

Docker attempts to connect to `https://`, using the default port (`443`), if that fails, it attempts `http://` (using the default port `80`); these ports are used because no port is specified.

However, when pushing to `localhost:80`, port 443 is not even attempted;

```
msg="Calling GET /_ping"
msg="Calling POST /v1.30/images/localhost:80/test/push?tag="
msg="Trying to push localhost:80/test to https://localhost:80 v2"
msg="Error getting v2 registry: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"
msg="Attempting next endpoint for push after error: Get https://localhost:80/v2/: http: server gave HTTP response to HTTPS client"
msg="Trying to push localhost:80/test to http://localhost:80 v2"
msg="Pushing repository: localhost:80/test:latest"
msg="Checking for presence of layer sha256:98c944e98de8d35097100ff70a31083ec57704be0991a92c51700465e4544d08 (sha256:78445dd45222097f5f8d5a16e48dc19c4ca162dcdb80010ab6f1ccfc7e2c0fa3) in localhost:80/test"
msg="Pushing layer: sha256:98c944e98de8d35097100ff70a31083ec57704be0991a92c51700465e4544d08"
msg="Assembling tar data for b8b9640ef09b77bb20d98c0f4a5eaceff253ba935e9aab22a498937a75f37f26"
msg="uploaded layer sha256:98c944e98de8d35097100ff70a31083ec57704be0991a92c51700465e4544d08 (sha256:7bfb4b00f941620d75de8a501115365c1ff839d9c9a16fa1ca2cf7bd0b4b778c), 979 bytes"
```

Here, docker attempts to connect using `https://` - using port `80`, then if TLS fails, it continues trying to use `http://` - again using port `80`, which succeeds, and push is successful.

Because this is `localhost`, "insecure registry" is automatically enabled; in your case you need to configure the daemon to use `yourdomain.com:80` as insecure registry, and also _push_ to `yourdomain.com:80`

**Comment by silenceshell** [comment]
It is freeipa which listened on port 443.
Maybe Nginx server is different from freeipa, because I find that in your log, docker client just connected port 443 timeout and returned, so `transportOK` remained false.

```
func (p *v2Pusher) Push(ctx context.Context) (err error) {
	p.pushState.remoteLayers = make(map[layer.DiffID]distribution.Descriptor)

	p.repo, p.pushState.confirmedV2, err = NewV2Repository(ctx, p.repoInfo, p.endpoint, p.config.MetaHeaders, p.config.AuthConfig, "push", "pull")
	if err != nil {
		logrus.Debugf("Error getting v2 registry: %v", err)   //return here
		return err
	}

	if err = p.pushV2Repository(ctx); err != nil {
		if continueOnError(err) {
			return fallbackError{
				err:         err,
				confirmedV2: p.pushState.confirmedV2,
				transportOK: true,
			}
		}
	}
	return err
}
```

You can check those logs in my last post, `Upload failed:` means there was no timeout, and docker client `pushV2Repository` and set `transportOK` to true. I think if the server is freeipa, TLS won't fail(I am not familiar with TLS) but protocol communication will fail, and get `HTTP 404`.

**Comment by thaJeztah** [comment]
Please look at the _second_ example. The first example is if the `docker push` is performed _without specifying the port_. Doing so is the actual problem because docker is gonna "guess".

The reason it stops and doesn't attempt to connect over non-TLS, is that the daemon is not configured to see the registry as "insecure"; see my earlier comment: those log-lines _only appear_ if the daemon does not see your registry to be insecure: https://github.com/moby/moby/issues/33564#issuecomment-306779163

**Comment by silenceshell** [comment]
Is there any way to work without specifying the port 80? Adding ':80' is a little annoying.
If no, I will shutdown the freeipa who binds port 443 as a workaround.

**Comment by thaJeztah** [comment]
I don't think there is currently. Alternatively you can run a front-end proxy on `:443`, that forwards the `/v2/` and `_ping` paths to your registry; that way you also don't need to specify the registry as `insecure` as TLS will then be used.

I will have to check/ask why this behaviour changed, but I _suspect_ this is to prevent unwanted fallbacks to http if a registry _does_ support https

**Comment by silenceshell** [comment]
Thanks @thaJeztah

**Comment by Jamlee** [comment]
try to create a dummy TSL config for triggering docker failover . it work for me.
![image](https://user-images.githubusercontent.com/5196641/78322730-27235480-75a2-11ea-861c-0379fc72ab9c.png)

https://docs.docker.com/registry/insecure/
![image](https://user-images.githubusercontent.com/5196641/78322845-75d0ee80-75a2-11ea-90f8-40566892e185.png)
