### ISSUE TITLE
Not all unit tests use Testify assert methods

### ISSUE THREAD

**Issue by tpot** [moby/moby#33579]
**Description**

As mentioned at the very end of pull request #33481 I volunteered to convert unit tests to use Testify assert methods instead of "if" statements and t.Fatal() method calls.

Currently there are a lot of tests of the form

    if blah, err := Something(); err != nil {
        t.Fatal("Something bad happened")
    }

This can be converted to 

    import "github.com/stretchr/testify/assert"
    blah, err := Something()
    assert.NoError(err)

There are a bunch of other Testify assertion methods that do other checks.

A quick grep through the source show that there are 3486 calls to t.Fatal() and it's friend t.Fatal() in 293 files so this process might happen over time in batches.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
n/a
```

**Output of `docker info`:**

```
n/a
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vdemeester** [comment]
I'm not a huge fan of that — i.e. using `testify` when writtin new unit test why not, changing all the existing one, just for the sake of it, meh.

**Comment by tpot** [comment]
Surely the testing files needs refactoring love as much as the rest of the codebase!

**Comment by thaJeztah** [comment]
Let's close this one, and update tests when the test is updated (or new tests are added)
