### ISSUE TITLE
Docker daemon error /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory

### ISSUE THREAD

**Issue by rj919** [moby/moby#33594]
**Description**

Whenever I attempt to run a container, Docker throws the following oci runtime error:
`applying cgroup configuration for process caused "open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory"`

When I examine the folder with ```ls /sys/fs/cgroup/cpuset/docker```, I do indeed find that there is no cpuset.cpus file in that directory and for some reason I am not able to create one either.

I attempted to fix this problem by following the [instructions in this comment](https://github.com/moby/moby/issues/29018#issuecomment-264384572), but it was unable to resolve the error.

It should be noted that I am running the docker daemon using ```sudo dockerd``` on ubuntu inside ChromeOS using the crouton package.

**Full Error:**
```
$ docker run hello-world
container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\""
ERRO[0117] containerd: start container                   error=oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\""
 id=21c7e9671a386407a2f4f0e35d355320498d04d3745d6628c2d0ec574f33f346
ERRO[0117] Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\""
 
ERRO[0117] Handler for POST /v1.27/containers/21c7e9671a386407a2f4f0e35d355320498d04d3745d6628c2d0ec574f33f346/start returned error: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\""
 
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\"".
```
**Output of `docker version`:**

```
$ docker --version
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.18.0-13985-g8bf2eb2
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.805 GiB
Name: localhost
ID: Q6GH:K7CX:FSGS:HAI5:57UP:MA7V:GU4N:G5I2:3NRC:KO2Q:H3RO:5OKM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpuset support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `docker-runc --version`:**
```
$ docker-runc --version
runc version 1.0.0-rc2
commit: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
spec: 1.0.0-rc2-dev
```

**Output of `mount`:**
```
$ mount
/mnt/stateful_partition/crouton/chroots/xenial on / type ecryptfs (rw,relatime,seclabel,ecryptfs_fnek_sig=fe933cc5a0aadb08,ecryptfs_sig=c6402b232e067c2d,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,relatime,seclabel,size=1992812k,nr_inodes=498203,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
shmfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel)
tmp on /tmp type tmpfs (rw,nosuid,nodev,relatime,seclabel)
none on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,seclabel,size=398956k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=5120k)
run on /var/host/dbus type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
run on /var/host/shill type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
/dev/mapper/encstateful on /var/host/timezone type ext4 (rw,nosuid,nodev,noexec,relatime,seclabel,discard,commit=600,data=ordered)
/dev/dm-0 on /lib/modules/3.18.0-13985-g8bf2eb2 type ext2 (ro,relatime,seclabel)
run on /var/host/udev type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
run on /var/host/cras type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
run on /var/host/chrome type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
media on /var/host/media type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel)
/home/.shadow/50e1258928131654ff16786b14ce29ac24e473e8/vault on /home/rcj1492/Downloads type ecryptfs (rw,nosuid,nodev,relatime,seclabel,ecryptfs_sig=25e3b3ec692a83f9,ecryptfs_fnek_sig=4d526b4cadeb1dff,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
none on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime,seclabel,gid=605,mode=750)
none on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix)
none on /sys/fs/selinux type tmpfs (ro,relatime,seclabel)
tmpfs on /sys/class/drm type tmpfs (rw,nosuid,noexec,relatime,seclabel,size=398956k,mode=755)
tmpfs on /dev/dri type tmpfs (rw,nosuid,noexec,relatime,seclabel,size=398956k,mode=755)
```

**Output of `uname -a`:**
```
Linux localhost 3.18.0-13985-g8bf2eb2 #1 SMP PREEMPT Wed May 17 18:03:44 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by justincormack** [comment]
I guess the kernel may not have support for that cgroup. It would be nice
to work around it.

**Comment by jpivarski** [comment]
I have exactly the same problem, also on Ubuntu inside ChromeOS.

**Comment by bpstrngr** [comment]
it's still around, seems peculiar to ChromeOS. 
There exists a /sys/fs/cgroup/cpuset/docker/cpuset 
so the missing cpuset.cpus shouldn't be so alien to the kernel. 
I tried manually touching a cpuset.cpus, and got Permission denied 
so I reckon there's something about cgroup privileges that restricts docker.

**Comment by rj919** [comment]
I also ran into the permission denied issue.

However, since installing GalliumOS on a second partition, I have not run into any problems running docker. Although Chromebooks require that linux distros be built from the ChromeOS kernal, unlike crouton, Gallium operates in its own environment. As a result, it is likely that this problem is tied to how Crouton handles mounting virtual devices which in turn relies upon how ChromeOS handles mounting. So, it is unlikely that this bug can be solved without compiling a new kernel based off of ChromeOS... which essentially would operate like Gallium.
https://arnoldthebat.co.uk/wordpress/chromiumos-special-builds/

So, even though this is still an open problem, I'm going to close it and recommend using GalliumOS.

**Comment by dragon788** [comment]
I believe the solution is to either [compile a custom kernel for ChromeOS](https://gist.github.com/christianbundy/ba62890a7c2f8128bcbb) (which gets blown away on every update unless you build your own ChromiumOS and handle updates from your own Omaha server) or try using rkt per [another comment](https://github.com/moby/moby/issues/1863#issuecomment-292717966).

**Comment by thaJeztah** [comment]
Looks like that would needs something of a fallback mechanism in [pkg/sysinfo](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/pkg/sysinfo/sysinfo_linux.go#L201-L226), changes to the [containerd/cgroups package](https://github.com/containerd/cgroups/blob/07683a668a6c20f509112ea932da7e4ca98c7c3f/cpuset.go#L89-L97), and to [runc / libcontainer](https://github.com/opencontainers/runc/blob/18cd7e06f709750d76a97f690a5b0d5023c52108/libcontainer/cgroups/fs/cpuset.go#L32-L44) (also some [tests to be updated](https://github.com/moby/moby/blob/c8f9e14b500b1b2e23e79c52ded0aee05579d9bc/integration-cli/docker_cli_run_unix_test.go#L546-L566))

**Comment by roytoo** [comment]
A fix to support both "cpusets." prefixed and non-prefixed was accepted and merged back on April 24, 2018:
https://chromium-review.googlesource.com/c/chromiumos/chromite/+/1023372/

I haven't yet figured out how to determine if it has been scheduled for inclusion an upcoming release.

**Comment by stealthybox** [comment]
I'm working on this -- thanks for the detailed pointers @thaJeztah

**Comment by 120dev** [comment]
this save my day :)

 1. sudo dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
 2. sudo dnf -y install docker-ce
 3. sudo groupadd docker && sudo usermod -aG docker $USER
 4. sudo gedit /etc/default/grub
 5. GRUB_CMDLINE_LINUX add the parameter : systemd.unified_cgroup_hierarchy=0
 6. sudo grub2-mkconfig reboot

**Comment by ccallahan** [comment]
I hate to be that guy who resurrects a dead issue, but in case anyone like me is having issues on Fedora 31, Red Hat is tracking ticket [RHBZ#1746355](https://bugzilla.redhat.com/show_bug.cgi?id=1746355) where for all intents and purposes Docker is borked unless you follow the steps up above from @120dev. I was spinning in circles for an hour until I loaded up Bugzilla and took a gander on that.

**Comment by thaJeztah** [comment]
@ccallahan see https://github.com/moby/moby/issues/40360

**Comment by ccallahan** [comment]
Thanks boss!
