### ISSUE TITLE
Unable to share drives when Windows 10 has no admin password set

### ISSUE THREAD

**Issue by amackintosh** [moby/moby#33618]
**Description**
When setting Shared Drives on Windows10, if the Computer has no admin password set, it is impossible to share drives because the 'OK Button' is disabled until you enter characters.

**Steps to reproduce the issue:**
1. Install Windows 10
2. Set Admin password to null
3. Install Docker
4. Right click system tray icon
5. Select Settings
6. Click Shared Drives tab
7. Select checkbox to enable sharing on C:\
8. Press Apply Button

**Actual results:** 'Enter admin credentials dialog' loads and the Submit Button is disabled until you enter characters, but this machine has no admin password, so it is impossible to submit correct credentials. I had to go into Control Panel and define a password for this machine in order to enable Drive Sharing.

This user flow was oversighted. You could call it a security feature, but I call it extremely confusing UX with lack of feedback. I do not want a password on this machine.

**Expected results:** Submit Button should allow the user to submit "" (null) password, or it should detect the machine has no password and allow drives to be shared, or the Docker UI for Drive Sharing should include information about why no password is illegal to warrant disabled Submit Button. That or Windows 10 itself allows the dialog to load in this manner, which is even more sad given that it can see the user has no password set.

I have attached an image of the view.

![docker](https://user-images.githubusercontent.com/25964567/26995098-bad221e2-4d1f-11e7-98ef-151e87cee2d1.png)

**Comment by thaJeztah** [comment]
This is specific to Docker for Windows; Could you reopen this in the Docker for Windows issue tracker? https://github.com/docker/for-win/issues

Please check if there's no existing issue tracking this, and check if there's mention of this in the troubleshooting section https://docs.docker.com/docker-for-windows/troubleshoot/

I'll close the issue here, but feel free to continue the conversation
