### ISSUE TITLE
Task reallocation doesnt happen on resource exhaustion in swarm mode 

### ISSUE THREAD

**Issue by abhi** [moby/moby#33619]
With a 3 node setup 1 manager and 2 worker nodes. I have 2 services created with 20 replicas eash on a overlay network (/16). If the manager node cuts of from the cluster and rejoins all 20 replicas from both services are not running

**Steps to reproduce the issue:**
1. docker network create docknet -d overlay --subnet 50.1.1.0/26
2. docker service create --name s1 --network docknet --replicas 20 alpine sleep 90000
3. docker service create --name s2 --network docknet --replicas 20 alpine sleep 90000
4. On node 1 (manager) bring down control interface and bring it back up. 

**Describe the results you received:**
```
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
biud0wfxg8nv        s2                  replicated          13/20               alpine              
ca7g84i024z2        s1                  replicated          13/20               alpine              
```

**Describe the results you expected:**
```
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
biud0wfxg8nv        s2                  replicated          20/20               alpine              
ca7g84i024z2        s1                  replicated          20/20               alpine              
```
**Additional information you deem important (e.g. issue happens only occasionally):**
Happens all the time

**Output of `docker version`:**
```
17.06 rc2
```

**Comment by thaJeztah** [comment]
Can you add the full output of `docker version` and `docker info`, as well as relevant daemon logs (preferably in debug mode)?
