### ISSUE TITLE
Race condition reading from secrets

### ISSUE THREAD

**Issue by Syntaxide** [moby/moby#33614]
**Description**

I have a container that I start via compose. This container uses secrets. If I attempt to read from the secret immediately, I run into file-not-found errors. If I wait a few seconds before reading from the /run/secrets/blah file, the file open/read succeeds.

**Steps to reproduce the issue:**
1. Create dockerfile with one service, that reads from secrets.
2. Have service immediately open/read the secrets file.
3. Encounter error
4. Add some delay (10 seconds) before reading file
5. Restart service, observe correct behavior

**Describe the results you received:**
Secrets are unavailable at container start

**Describe the results you expected:**
Secrets should be immediately available.

**Additional information you deem important (e.g. issue happens only occasionally):**
I encounter this error about 30% of the time when running without the delay.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 72
 Running: 2
 Paused: 0
 Stopped: 70
Images: 2332
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2514
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
ID: PXLW:QPTX:NNDR:Q7KA:522F:ZNZK:A3LE:PF46:AJNN:EZR2:MXM5:ZCAW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Encountered both on physical machines and aws.

**Comment by thaJeztah** [comment]
Is this deployed using `docker-compose` or `docker service deploy`?

**Comment by Syntaxide** [comment]
I've encountered this more frequently during development (with `docker-compose`), but have also seen it through a `docker service deploy`.

**Comment by thaJeztah** [comment]
Interesting; the reason I was asking is because `docker-compose` basically "imitates" secrets by simply using a bind-mount of a local file (i.e. the secrets API that's used for `docker service deploy` is not used).

Given the above, I wonder if it's a race in _mounts_ in general; are you seeing the same problem if the service attempts to directly access a file from inside a volume?

**Comment by fntlnz** [comment]
Tried to reproduce with the following configuration:

Secret (file generated with: `openssl rand -out sample.txt -base64 $(( 2**10 * 2/4 ))`

```
d012cCiBdqAJZh2drja3NZ9FFTDxaXa36mQiQUm360Oz/kUTr5BPqaYcRwIZucYi
xPyefJY9fwwRpiqfjCC/83Mo3OrEo+j+/l9OjMJWdps20VCqfHKqG3st+15tYjWw
BXIYhbtRaE7KtsiCRPvy8XuZjBVStH6Pfpzrk/Ptc79mqc71yAt+Fnirea+pXck0
2yvw/NVQXaih3d72EpWwpONWZHFMWS+Z96PIKnPvNHdZdm8lEKocFOWMcKL+imtF
vjbuMbDerFqZYtBDgKgA5JnQSQJ49zbQZQCd7VxJY9kjXouU9BF4O0g7VzjBNRa2
DnTW6JKY/cI9TnEwrc8zEERtJSdbQBm4xNbuoKimfCpFGX3tIr6gGObTWTDk77LP
lytol74XBSvv0Ku/xUVtf8+Wo7Wu0C3Igl8IgdnOYLawkO9uFnJPuAVoLByzlVpm
xgIDpwNeGiXFSldgdGAm0XpunXXZ1pHdkJ+n5dsf3eLdcSen/b7q8De/8Z/iQDfD
HoRTNtmkqpvZaRcXMybYi1fWh+LeUtNDag7lIXgs0yVqrejhBbNMaFJTIbRmF6VK
B3oYsU2xL8K7Z9adPw5kUBPAItHpkZSx7D0S8zPKes6Pu5u6KW/T7pjOLJargQTQ
+VzbEcCBTqr/tAdeBYkgxnvAdkT+lTMo3RHQWDvnduI=
```

`dcoker-compose.yml`
```
version: "3.2"

services:
  prova:
    image: alpine
    command: "sh -c 'cat /run/secrets/mysecret'"
    secrets:
      - mysecret
secrets:
   mysecret:
     file: secret_file.txt
```

Tried both starting it with a plain compose or with the stack deploy command. Even tried with tens of containers reading the same secret, no race condition here.

@Syntaxide  Can you post an example of your compose file?

**Comment by thaJeztah** [comment]
closing, as this went stale
