### ISSUE TITLE
Network traffic from container does not work upon docker host reboot - docker 17.03.0-ce

### ISSUE THREAD

**Issue by mlcooper** [moby/moby#33615]
**Description**
When I reboot my docker host, my container does start automatically, but if I attach to the container and try to ping or nslookup anything (ping a host outside the container) everything times out.

I can fix this by exiting the container and issuing `service docker restart` on the docker host.

This feels like a race condition; like my docker container is coming up before networking on the docker host is ready.

RHEL7 - kernel `3.10.0-514.21.1.el7.x86_64`
docker-engine - `17.03.0.ce-1.el7.centos`
```
[root@foo docker]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```
```
docker-engine-selinux.noarch      17.05.0.ce-1.el7.centos
```
**Steps to reproduce the issue:**
1.  Assume in the container it is resolving names via nslookup properly
2.  Reboot docker host with `reboot` command
3.  Go into docker container and try to resolve either external or internal dns names.  It fails with
```
;; connection timed out; no servers could be reached
```
Or try to `ping` another server internal to our network.  Ping fails.
Note that at this time the docker host can resolve external/internal names via `nslookup` without a problem, as well as ping other servers.
4. Issue the command from the host `service docker restart`
5. Go into docker container and try to resolve anything with `nslookup`.  It now resolves without issue with `ping`ing other servers and `nslookup`

**Describe the results you received:**
As described above, docker container cannot resolve dns names after a reboot, or ping/reach other endpoints outside of the container, until `service docker restart` is issued on the docker host.

**Describe the results you expected:**
Reboot docker host, go into docker container and `nslookup` and `ping` should be able to resolve names/ping endpoints without a problem.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
[root@foo ~]# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
[root@foo ~]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.828 GiB
Name: qk2taedocker01
ID: E2XC:6FN4:MI4Z:ONXT:AO32:MBJL:JAUB:M6IY:N7UV:WRZT:A2S3:VMTJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker host is a VM in VMware

**Comment by thaJeztah** [comment]
Just to be sure, can you try updating to the latest patch release of 17.03 (currently 17.03.1)?

**Comment by thaJeztah** [comment]
Also, do the system and/or daemon logs show anything useful?

**Comment by mlcooper** [comment]
Nothing interesting in `/var/log/messages` which is where I believe the docker daemon logs everything.  In fact, I even seen the network interfaces get setup before my docker container starts.

I haven't yet tried updating to 17.03.1, however:

I altered the `After` line in `/etc/systemd/system/docker.service` from `After=network.target` to `After=network-online.target`, and when I reboot the host, networking now works from within my container (ping/nslookup) _without_ me having to restart the docker service host the host.

I'm not certain if that's a good long term solution, but it appears to work.

**Comment by thaJeztah** [comment]
That change should be fine; it's what's used for docker 17.04 and up as well, and can indeed solve situations where the network interface takes longer to come up;
https://github.com/moby/moby/blob/v17.04.0-ce/contrib/init/systemd/docker.service

Just be sure to revert manual changes before updating to a newer version of docker, otherwise other changes to the unit file may be skipped during the update process

If this resolved your issue, I think we should close this issue, if that's fine with you

**Comment by mlcooper** [comment]
Thanks for your information about 17.04 and up.  I will look to upgrade my environment.
