### ISSUE TITLE
Fix 'sirupsen/logrus' import statements

### ISSUE THREAD

**Issue by XenoPhex** [moby/moby#33641]
**Description**
We are currently importing the `pkg/term` package and we're having import path casing issues due to `sirupsen/logrus`. It appears that everything in this project is using the package name `Sirupsen/logrus` instead of `sirupsen/logrus` as is suggested by [the readme](https://github.com/sirupsen/logrus/blob/master/README.md):

> **Seeing weird case-sensitive problems?** Unfortunately, the author failed to realize the consequences of renaming to lower-case. Due to the Go package environment, this caused issues. Regretfully, there's no turning back now. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

**Steps to Reproduce**:
1. import/vendor `github.com/moby/moby/pkg/term`
1. import/vendor `github.com/sirupsen/logrus`
1. call both in your project
1. run `go fmt`

**Describe the results you received:**

```
can't load package: package code.cloudfoundry.org/cli/vendor/github.com/Sirupsen/logrus/examples/hook: case-insensitive import collision: "code.cloudfoundry.org/cli/vendor/github.com/Sirupsen/logrus" and "code.cloudfoundry.org/cli/vendor/github.com/sirupsen/logrus"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This appeared on our OSX CI environment where the file system was case insensitive. Probably would have happened on our windows CI environment too, but we fixed it on OSX first.

## Status

- [x] Initial import rename : #34272 @dmcgowan 
- [ ] Update `vendor.conf` with upstream instead of private forks
  - [x] https://github.com/docker/libnetwork
  - [ ] https://github.com/containerd/containerd
  - [ ] https://github.com/docker/swarmkit
  - [ ] https://github.com/opencontainers/runc
  - [x] https://github.com/Microsoft/opengcs
  - [ ] https://github.com/moby/buildkit

**Comment by lussn** [comment]
Hi @XenoPhex , as I see, I'm doing the same steps as you. I saw your PR in the Azure lib and I also need the import updates here. Are you going to create a PR here? If not, I'll create one today. Cheers! :)

**Comment by thaJeztah** [comment]
If we make this change, we probably need to do it across the board, to prevent (e.g.) SwarmKit vendoring it as `sirupsen/logrus` and Moby as `Sirupsen/logrus`

**Comment by lussn** [comment]
Good point @thaJeztah , and probably other dependencies are using the uppercase, I have to take a look. Seems that it isn't a quick fix, we need to coordinate with the other dependencies owners and with the moby/moby users.

**Comment by thaJeztah** [comment]
Yes, this sounds like something that needs to be coordinated (I'm not sure what the net effect would be of having the duplicate imports, but it _would_ be problematic for people checking out the code on a non case-sensitive filesystem, as the directories would be merged)

/cc @stevvooe @vdemeester any ideas?

**Comment by AkihiroSuda** [comment]
Can we consider forking logrus?

**Comment by thaJeztah** [comment]
If it's just about the naming, I don't think we should. Some of our maintainers (including @stevvooe) already have commit access to logrus upstream, and help maintaining it, so no reason there.

It's a pain, but probably one that we have to go through

**Comment by XenoPhex** [comment]
I was planning on PRing all necessary components the other day, but I didn't realize how big the change was (as @thaJeztah said, if done properly, it's a pretty big change across the board). This is something that would be easier to coordinate across all the docker/moby packages for someone who had commit access. Thus the github issue.

**Comment by stevvooe** [comment]
@thaJeztah We tried to fix it just by changing everyone to use `sirupsen/logrus` but a vocal minority were unable to make the change. I'm perfectly fine moving to the lowercase version of the import path. It is a two second fix if everyone uses the lowercase version.

**Comment by AkihiroSuda** [comment]
If we are going to migrate Sirupsen to sirupsen, "2-phase" migration might be useful to avoid import collision?
- Phase 1: Create `moby/tmp-logrus-fork` as a temporary friendly fork, and migrate `Sirupsen/logrus` -> `moby/tmp-logrus-fork` across all related repos
- Phase 2: `moby/tmp-logrus-fork` -> `sirupsen/logrus`, and deprecate `moby/tmp-logrus-fork`


Another opinion is to ask sirupsen to move `sirupsen/logrus` to `<some-org-repo>/logrus`, but not sure he is interested in. https://github.com/sirupsen/logrus/issues/525 (Also, it might cause another issue under some circumstances?)

**Comment by stevvooe** [comment]
@AkihiroSuda Just make them lowercase and fix the projects that break. This would have been fixed in one go, last year, when the project changed if people had just fixed it, rather than complaining about build time breaks. Let's not stretch this out any longer. It doesn't require a feat of engineering to achieve.

**Comment by AkihiroSuda** [comment]
OK, but some repos vendors each other cyclically, so we need to look into carefully whether we can technically open PRs in one go.

Also, it might be good to announce the schedule before working on this, so that 3rd party repos can follow the changes.

**Comment by stevvooe** [comment]
@AkihiroSuda 

```
while broken; do
  perl -i -pne 's|Sirupsen|sirupsen|g` **/*.go
done
```

Really, this is _extremely_ easy to fix. A few builds break in the interim, but it is not the end of the world. It is an `O(1)` break.

**Comment by 23doors** [comment]
Any update on that? When vendor stripping is needed, this is currently making even older versions no longer functional. E.g. when using docker/docker/client package with glide. And without vendor stripping you end up with vendor hell for context package. I must say that for a pretty new language, juggling dependencies feels just terrible. But this is not docker-related remark.

Anyway, seems that docker/docker and docker/go-connections are affected. Not sure about other repos.

**Comment by cpuguy83** [comment]
> Anyway, seems that docker/docker and docker/go-connections

Ugh... we should not ever be logging in go-connections.

**Comment by owenhaynes** [comment]
Why  should we have a direct dependency on logrus. Should this not be interfaced out so any logging system can be used.

**Comment by stevvooe** [comment]
@owenhaynes This is for the internal logging within docker's code base. This has nothing to do with user logging.

**Comment by owenhaynes** [comment]
But it does when a user wants use the client code in there own product, they get a transiant dependency on logrus at the moment. 

We use the new dep vender tool which is pretty good at removing not needed transiant dependencies so the client code is depending on some files which require logrus

**Comment by vdemeester** [comment]
@owenhaynes if you depends only on `client` and `api` package you shouldn't need it. If it's the case, then yeah, we need to fix that (but let's not divert too much of the original topic of this issue 👼)

**Comment by owenhaynes** [comment]
@vdemeester @stevvooe Shell i raise a new ticket for this to remove logrus from client, and api packages?

**Comment by vdemeester** [comment]
@owenhaynes please do 👼 🙏 😉 👍

**Comment by vdemeester** [comment]
(note that so far, I think it's because of `github.com/docker/docker/api` and `github.com/docker/docker/pkg/system`)

**Comment by stevvooe** [comment]
@owenhaynes It would be best to file another ticket. It sounds like you are having issues with interoperating with logrus. There are ways to adapt it to other logging systems. We have successfully redirected logrus into grpc/glog and vice versa, so there are ways around it.

As far as this issue goes, this is about a bunch of engineers getting together and figuring out how to make a large `S` into a little `s`. :hammer: :hamster:

**Comment by darrenstahlmsft** [comment]
Bump on this. Eventually some dependencies are going to need to update and force a move here. I think this should happen sooner rather than later.

**Comment by gephaest** [comment]
When this will be fixed?

**Comment by mcandre** [comment]
We could fix this faster by forking any laggard dependencies and updating their logrus references manually

**Comment by vdemeester** [comment]
@XenoPhex I'll update the description of the issue to keep track of all the work yet to be done for considering this one completely fixed 👼

**Comment by X4mp** [comment]
@thaJeztah  @stevvooe what's the status of this issue? We urge to get the fix upstream with a release to update our glide version pinning.

**Comment by AkihiroSuda** [comment]
@X4mp

Isn't it already fixed?: https://github.com/moby/moby/search?utf8=%E2%9C%93&q=sirupsen%2Flogrus&type=

**Comment by X4mp** [comment]
@AkihiroSuda yes, but not released. 17.05 still uses Sirupsen/logrus.

**Comment by AkihiroSuda** [comment]
Please use git commit hash , as currently there is no "release" in Moby.
(Discussed in some other github issue, but no progress yet afaik)

**Comment by X4mp** [comment]
Ok thx :) 👍

**Comment by thaJeztah** [comment]
Note that if you're looking for _Docker_ releases, you can find those in https://github.com/docker/docker-ce (vendoring from that repo won't be possible though, as it bundles various components)
