### ISSUE TITLE
Error response from daemon: rpc error: code = 2 desc = raft: failed to process the request: node lost leader status

### ISSUE THREAD

**Issue by chaitu0292** [moby/moby#33643]
ours is a cluster of 11 machines and we have 3 manager nodes.Till date its fine but today we started seeing rpc error.
_Error response from daemon: rpc error: code = 2 desc = raft: failed to process the request: node lost leader status_

Environment:
centos 7
Client:
Version: 17.03.1-ce
API version: 1.27
Go version: go1.7.5
Git commit: c6d412e
Built: Mon Mar 27 17:05:44 2017
OS/Arch: linux/amd64
Server:
Version: 17.03.1-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: c6d412e
Built: Mon Mar 27 17:05:44 2017
OS/Arch: linux/amd64
Experimental: false

**Comment by thaJeztah** [comment]
Looks like you posted twice; I left some information on your other issue; https://github.com/moby/moby/issues/33631#issuecomment-307816556
