### ISSUE TITLE
how to compile the source software, I want to debug the code

### ISSUE THREAD

**Issue by y123456yz** [moby/moby#33669]
@nishanttotla 

how to compile the source software, I want to debug the code
can you help me

thanks

**Comment by thaJeztah** [comment]
If you want to build current master, the easiest way is to do so in a build-container (assuming you have docker installed on your computer);

check out the repository, then

```bash
make BIND_DIR=. shell
```

This builds the container, and gives you a shell inside it.

Then, inside the container, compile;

```bash
hack/make.sh binary
```

And install, and start the daemon (inside the container);

```bash
make install

dockerd --debug
```


This starts the daemon in the foreground, and you see its logs

Then start another session inside the container, e.g., using `docker exec`

```bash
docker exec -it <name or id if the build container> bash
```

From where you can run docker commands.

You can also find instructions in our contributors guide;
https://docs.docker.com/opensource/project/set-up-dev-env/


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

For these questions, Slack may be easiest, feel free to join the #moby-project channel on the community slack if you have questions 👍

**Comment by y123456yz** [comment]
@thaJeztah

centos7 compile error.

[root@localhost docker]# make BIND_DIR=. shell
Makefile:108: The docker client CLI has moved to github.com/docker/cli. By default, it is built from the git sha specified in hack/dockerfile/binaries-commits. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

docker build   -t "docker-dev:master" -f "Dockerfile" .
Sending build context to Docker daemon 33.24 MB
Step 1 : FROM debian:jessie
 ---> a25c1eed1c6f
Step 2 : ARG APT_MIRROR=deb.debian.org
 ---> Using cache
 ---> a2eb6d9831d7
Step 3 : RUN sed -ri "s/(httpredir|deb).debian.org/$APT_MIRROR/g" /etc/apt/sources.list
 ---> Using cache
 ---> 8b86ed84b4c6
Step 4 : RUN apt-get update && apt-get install -y       apparmor        apt-utils       aufs-tools      automake        bash-completion         binutils-mingw-w64      bsdmainutils    btrfs-tools     build-essential         clang   cmake       createrepo      curl    dpkg-sig        gcc-mingw-w64   git     iptables        jq      less    libapparmor-dev         libcap-dev      libltdl-dev     libnl-3-dev     libprotobuf-c0-dev      libprotobuf-dev         libsystemd-journal-dev      libtool         mercurial       net-tools       pkg-config      protobuf-compiler       protobuf-c-compiler     python-dev      python-mock     python-pip      python-websocket        tar     vim     vim-common      xfsprogs    zip     --no-install-recommends         && pip install awscli==1.10.15
 ---> Running in cc4d251a58c4
Ign http://security.debian.org jessie/updates InRelease
Ign http://deb.debian.org jessie InRelease
Err http://security.debian.org jessie/updates Release.gpg
  Connection failed [IP: 133.242.99.74 80]
Ign http://security.debian.org jessie/updates Release
Ign http://deb.debian.org jessie-updates InRelease
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://deb.debian.org jessie Release.gpg
  Connection failed [IP: 128.31.0.62 80]
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates Release.gpg
  Connection failed [IP: 149.20.4.15 80]
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  Connection failed [IP: 133.242.99.74 80]
Ign http://deb.debian.org jessie Release
Ign http://deb.debian.org jessie-updates Release
Err http://deb.debian.org jessie/main amd64 Packages
  Connection failed [IP: 128.31.0.62 80]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  Connection failed [IP: 149.20.4.15 80]
W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Connection failed [IP: 133.242.99.74 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Connection failed [IP: 128.31.0.62 80]

W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  Connection failed [IP: 133.242.99.74 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Connection failed [IP: 149.20.4.15 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  Connection failed [IP: 128.31.0.62 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  Connection failed [IP: 149.20.4.15 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y    apparmor        apt-utils       aufs-tools      automake        bash-completion         binutils-mingw-w64      bsdmainutils    btrfs-tools     build-essential         clang       cmake   createrepo      curl    dpkg-sig        gcc-mingw-w64   git     iptables        jq      less    libapparmor-dev         libcap-dev      libltdl-dev     libnl-3-dev     libprotobuf-c0-dev      libprotobuf-dev         libsystemd-journal-dev      libtool         mercurial       net-tools       pkg-config      protobuf-compiler       protobuf-c-compiler     python-dev      python-mock     python-pip      python-websocket        tar     vim     vim-common xfsprogs         zip     --no-install-recommends         && pip install awscli==1.10.15' returned a non-zero code: 100
make: *** [build] Error 100


@thaJeztah
can you help me.

**Comment by unclejack** [comment]
@y123456yz Are you behind the GFW? If that's the case, the errors are most likely caused by the GFW. This isn't something we can help with.

**Comment by y123456yz** [comment]
@unclejack 
but  curl comand is ok when I use curl. as follwing:
[root@localhost docker]# curl  http://security.debian.org/dists/jessie/updates/Release.gpg 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABCAAGBQJZRm4YAAoJEJ1tj2vIV8kG5D8QAJrp6rGRGM8FpHsXC8cxjV1V
zfezp6r0LYRgovhE/xFV/VxxCfH+CZTH+cY1tsv0LukCzpJdGBMAr70Zms1/TsVA
1zfhmShvOREB19U//+Bi08GJsfYCrDiqDG8uSaJzr1qqs8EFUwdoNOFZSDl0UZ/K
oZP+hFO5SEXAkANRytRWlm60zPFsa3snaQnDvogvcd3TN8k4wlEA4wi9sVLGP9Sm
CIyWYx9NpnZvZp0LwAqkoNrAfaZW/TWNXiyuBYwjY/oSBYHUvJCrwchkp6IGDpdq
5N7OBlGlBOK/j5yHKlgXsXdodGfQxG4KKJ1Db/C8lpkifcfFksuWSw7+M++0MDie
MRxTBtelgVpA7RlC53C4MIt3xrVkwG4jJDaclZa0Z5R9dJQJ0RvXKOjF59so0Kp1
xm+fRAXw1zK3rwnh0nAcKJ69lc0Q2WEBo9/dFpV5lqgEefhdh8gPKwg1mh23Wdq5
oGdXMSIxylJSrJF73ySQi8n+5k+l93g9ffhRI7N4KuuH0P3DbQ6O8j+jwpOj273X
uOzthIECI5nngDI91ZGDzKi/RmwMshDQFN0Hx/WkoxP7+0zFz2LU2PNbFzBeGlYY
ESysugxKULZSfGKyUYApnzeiaHhUMK1sv8WVu7tLLJNmX2geZ2ub0V+fIu2yNKSq
drB4VmdxczNU6FsJeET0iQIcBAABCAAGBQJZRm4YAAoJEItIrWJGklVT5D8QAK4T
sADqKa7MurCCctpa67AQop8qKC133Za43Jcn2oV1g+hmGcrEK29qA4pMN8qupStu
1Njgbp3EegEbsPsWSLXZB4mBwFCMHjvSc8eQ14PntoYsKvFnRaDRPaxkbpMXBizi
Q4wcOeaNjj2MYbSqqOShbzUne0hY6uAnG2UZSvDt/MG72MpnWZmmCFbkwfIevDlb
VX8fQwBY6tiUujK0VrWW7wIfdjjLmKntL2OglU+q8Dx93jnUUqPN0rtoRoVr44xh
rHOoC7bICUyhHi7bq1LmI7LvNmaSrdDF6/10WxNz0gx8mRppPJc52KG8F8xm8bXo
wj8GH75JQJmHxqHJbgVeTcnin1AmNInOsDUGcyVIYAxJVju6KnOwXfR9V4aXqa03
XRkgWNciZGcqc97RWbXGjrdn1hqtHRPKjDCHrG8+XIKfdkNTVqGrzWT5gMs86GEo
49IoeZ8UR4/Os/5gClEXpt08tywg2F6/cUVoRBJEPf7TNAsaNV7d1QUdQ0wtjliQ
YTHnzaEVETWlkfCGJr8NNRvYCLJKI2JD1RCdnFpNe2jAgodrUulavshrY1Er7HhG
d4mv1Jb8x9wBk7nuyFN8hgqghD/bhBZeOAJM+E7ttBlNE+2pm1okZGlOE6ALMj6A
S0lFdAViiJoCkg7Rw6N/0jaQzYU+AYe6lVoiFh5Q
=U+gB
-----END PGP SIGNATURE-----
[root@localhost docker]#

**Comment by AEGQ** [comment]
@y123456yz     _**may be it will help :)**_ 

**1、Using mirrors.aliyun.com for apt:**

> COPY ./sources.list /etc/apt/sources.list

reference:
http://mirrors.aliyun.com/help/debian

**2、Using mirrors.tuna.tsinghua.edu.cn for pip**
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple docker-pycreds==0.2.1 \

reference:
https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

**3、Download by hand and copy into image for other packages which you may download failed!**
> COPY ./go1.8.3.linux-amd64.tar.gz /tmp/go1.8.3.linux-amd64.tar.gz
> RUN    tar -xzC /usr/local -f /tmp/go1.8.3.linux-amd64.tar.gz

> COPY ./MacOSX10.11.sdk.tar.xz /tmp/MacOSX10.11.sdk.tar.xz
> ...
>  && cp /tmp/MacOSX10.11.sdk.tar.xz /osxcross/tarballs \

**Comment by y123456yz** [comment]
@AEGQ 
my os is centos7, not debian.


so, your method not work.
thanks again.

**Comment by Dayanand-Chinchure** [comment]
cd repos/moby-fork/

make BIND_DIR=. shell

Failed every time. Need to replace the line "ARG APT_MIRROR=deb.debain.org" with "ARG APT_MIRROR=128.30.2.26" in Dockerfile. 

Error : In the container , sources.list is with the deb.debian.org mirro. May be because of name resolution it is not working.

Hope this is the right way to get it work
