### ISSUE TITLE
*some* swarm mode ports are broken after a reboot

### ISSUE THREAD

**Issue by bdeluca** [moby/moby#33671]
**Description**
Make a lost of swarm services on a single swarm master. 
Reboot the swarm master. 
Some service ports are not mapped back correctly. 

**Steps to reproduce the issue:**
Its complicated, our production environment is not simple. This is 100% example guaranteed to fail
1. create a few services. (here is a script)
```
#!/bin/bash
counter=0
total=20
while true; do
  if [[ "$counter" -gt "$total" ]]; then
       exit 1
  else
	let port=5000+$counter
    docker service create --name example$port --constraint node.role==manager --publish $port:$port andytinycat/ncat ncat --sh-exec "echo OK" -k -l $port
  fi
  let counter++
done
```
2. Run this script to test all ports are open and services are working correctly. 
```
 #!/bin/bash
counter=0
total=20
while true; do
  if [[ "$counter" -gt "$total" ]]; then
       exit 1
  else
	let port=5000+$counter
	echo $port
    netcat localhost $port
	
  fi
  let counter++
done
```
You should see a list of ports and then OK messages like this
5000
OK
5001
OK

3. reboot the machine
4. wait .......
5. run the check script again
you might need to try 3-5 once or twice (but with this many services your sure to get a hit)

ports will be missing. 

**Describe the results you received:**
some ports are not mapped correctly 

inspecting stuff I see crazy  

>docker service inspect example5010
            "VirtualIPs": [
                {
                    "NetworkID": "faueit9vus4zyh0tepl79s5u2",
                    "Addr": "10.255.0.23/16"
                }
            ]
> docker net inspect ingress
            "6cd109e57117d413f2970e54a9000b30e49da9bd88c60c7fd5ade6844f772c62": {
                "Name": "example5010.1.kizq9mhaelq9vbg160cqq263i",
                "EndpointID": "025f52e29cb6848a1faf924d5f824480a522405d800deaaf963fc842d5a8d541",
                "MacAddress": "02:42:0a:ff:00:07",
                "IPv4Address": "10.255.0.7/16",
                "IPv6Address": ""
            },

**Describe the results you expected:**
I expect all ports to be mapped correctly. 

**Additional information you deem important (e.g. issue happens only occasionally):**
this happens on some some services some times, but if you have enough services it happens every time

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 26
 Running: 21
 Paused: 0
 Stopped: 5
Images: 9
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 100
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: zcmjrhreylxrdm447bzj1e18u
 Is Manager: true
 ClusterID: x4u8mmef8akulzj0q7eddxmou
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.67.200.7
 Manager Addresses:
  10.67.200.7:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842GiB
Name: dev-master
ID: RQBH:L3SY:FYCS:V7GE:HD74:KYPK:S23N:NESF:CTSO:MSVB:GMUK:5NK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by kimpearce** [comment]
Same result here Ben,

```
root@dl380-g6-01:~# ./create.sh 
4oft3kjmiquq3qgc8p84tw2ca
39fqploo0vxw7of0xuokib558
rt3d9ep2myf6z0lei44kmgzjv
p2zvjp7me2jj130n499xslx8b
raida4zp6eyg33t2tmdt3hpqa
rlaaobc2ii958q546f5590487
9ff0edx6xayimcum07i4r0lgh
5lmbsaz9y1yc6qmgmx5ckgvsh
llnv4nsjmt2x7amar9wyegxf7
unvehw3ya9klqe0zfujbd2qrt
d811i937lor2b3uy4khu9y329
rszff64n3bncom1m0s1ubnb88
vupwfpcwpvzj9uwx1u3vdi2e1
cvtusas33wl5lby10fm3lnk0h
j3gab2icu2f952fxufo6jokvc
tgobexw2dpkm5ei84wr7atyll
i0k89atye8u6v1wv74v0ios2r
fzk6d804llaep2j7dwhxb8m4u
62mfvn3krcsu84k46cyvugyr8
ds9k0bog0qz39fq0bbvsqup78
vcjoinvz607urirzko7z8qy5q
root@dl380-g6-01:~# ./check.sh 
7000
OK
7001
OK
7002
OK
7003
OK
7004
OK
7005
OK
7006
OK
7007
OK
7008
OK
7009
OK
7010
OK
7011
OK
7012
OK
7013
OK
7014
OK
7015
OK
7016
OK
7017
OK
7018
OK
7019
OK
7020
OK
root@dl380-g6-01:~# reboot
```
...and a good 10 minutes after just one reboot:

```
root@dl380-g6-01:~# ./check.sh 
7000
OK
7001
OK
7002
OK
7003
OK
7004
OK
7005
7006
OK
7007
7008
OK
7009
OK
7010
OK
7011
OK
7012
OK
7013
OK
7014
OK
7015
OK
7016
OK
7017
OK
7018
OK
7019
7020
```

**Comment by bdeluca** [comment]
also tested with 
Docker version 17.06.0-ce-rc3, build 7953dbc

So I originally discovered this whilst doing failure tests, but you can just
> systemctl stop docker
> systemctl start docker

 and cause it.

**Comment by bdeluca** [comment]
also tested with same behavour
ocker version 17.06.0-ce-rc4, build 29fcd5d

**Comment by thaJeztah** [comment]
ping @sanimej @fcrisciani PTAL

**Comment by bdeluca** [comment]
*bump*

**Comment by alexsandro-xpt** [comment]
After the 17.06.0 release, this problem is happening yet?

**Comment by bdeluca** [comment]
Yes still happens

**Comment by sanimej** [comment]
@bdeluca Description says its seen in a single node cluster. Is that just for a simple recreate or you see it only with a single node cluster ?

**Comment by bdeluca** [comment]
Just for a simple recreation.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
