### ISSUE TITLE
Unexpected behavior from healthcheck

### ISSUE THREAD

**Issue by omerh** [moby/moby#33676]
I am doing some test on health check in swarm or docker stand alone

My Dockerfile is this:
```
FROM ubuntu
COPY . /
HEALTHCHECK --interval=10s --timeout=3s CMD curl -f http://localhost:9000/ || exit 1
CMD [ "bash" , "start.sh" ]
```

start.sh script is:
```
#!/bin/bash
sudo apt-get update
apt-get install nc -y
sleep 40
nc -vvlnp 9000 >/dev/null
```

This simulate an application that takes 40 sec to start.
The container starts and fails after 39 seconds.
I expect that the docker engine will keep the container in starting until the first healthy check returns. 
So health check will be relevant for application that starts slow (Java/Rails...) and once starts health check returns fast  

I suggest to add to health check switch --terminate
So proper health check will be as follows:
 
```
HEALTHCHECK --interval=10s --timeout=3s --terminate=4m CMD curl -f http://localhost:9000/ || exit 1
```

Current status is that we cant use health check properly in short intervals on long starting applications

**Comment by thaJeztah** [comment]
This is implemented through the `--health-start-period` option in docker 17.05 and up, see https://github.com/moby/moby/pull/28938 (which implemented this), and https://github.com/moby/moby/issues/26498, https://github.com/moby/moby/issues/26664

The health start period allows you to set a duration in which the health-checks still _run_ but don't mark the container "unhealthy". This gives containers that need (e.g.) initialisation the first time they run.

I'm closing this, because this is implemented, but feel free to continue the conversation.

**Comment by omerh** [comment]
Ok, Thanks.
Can you point where does it documented, because I've missed it.

**Comment by thaJeztah** [comment]
The flag itself is documented in the command-line reference for the "edge" releases;
https://docs.docker.com/edge/engine/reference/commandline/run/

And additional information in the builder reference, although it looks like that isn't published on docs.docker.com for edge releases https://github.com/docker/cli/blob/5bf86c198488c7f78f2ffd05a8a2441f719d3b98/docs/reference/builder.md#healthcheck

I agree that we should have some more in-depth information/examples about health checks in general (what they are, when to use, how to use them, and what effects they have); let me open an issue in the docs repository for tracking that

**Comment by thaJeztah** [comment]
Oh, just realised I already did https://github.com/docker/docker.github.io/issues/3282

**Comment by omerh** [comment]
I know that this is closed, but I am on a fresh install of docker-ce 17.06
I dont have --health-start-period available.
was it missing in the release?
