### ISSUE TITLE
Handling of Bash Functions inside User Environment at Docker Container Startup

### ISSUE THREAD

**Issue by ghost** [moby/moby#33677]
**Description**

User environment on my client platform contains the declaration of a couple of Bash functions that come from the Lmod Environmental Modules System (https://www.tacc.utexas.edu/research-development/tacc-projects/lmod):
```
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
BASH_FUNC_ml()=() {  eval $($LMOD_DIR/ml_cmd "$@")
BASH_FUNC_module()=() {  eval $($LMOD_CMD bash "$@");
```

These functions are not properly handled by Docker when instantiating a container.
The error message is the following:
```
docker: poorly formatted environment: variable '[ $? ' has white spaces.
See 'docker run --help'.
```

This issue is in some way related to this one: https://github.com/moby/moby/issues/16608

**Steps to reproduce the issue:**
1. Install Lmod Environmental Modules System
2. Source Lmod environment
3. Instantiate a Docker container

**Describe the results you received:**

Docker container doesn't start and the following error message is issued:
```
docker: poorly formatted environment: variable '[ $? ' has white spaces.
See 'docker run --help'.
```

**Describe the results you expected:**

Proper startup of the Docker container.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Wed Mar 22 19:08:48 2017
 OS/Arch:      linux/ppc64le

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Wed Mar 22 19:08:48 2017
 OS/Arch:      linux/ppc64le
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Kernel Version: 3.10.0-514.21.1.el7.ppc64le
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: ppc64le
CPUs: 160
Total Memory: 123.7 GiB
Name: ouessantm01
ID: WRKJ:ZHVJ:A7VB:QDXT:UDK3:DTS5:BSWS:HFHR:EVJK:GLA7:ZFD6:ADKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 xcatpwr-adm:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
