### ISSUE TITLE
containerConfig.id() should return container id if available

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#33679]
Within the executor, the `id()` method on `containerConfig` only returns the correct id when using the attachment runtime. This has the danger of making others believe that the id for a target container is always available.

Please see https://github.com/moby/moby/blob/master/daemon/cluster/executor/container/container.go#L92.

Identified this when reviewing #33377. This PR would have never worked.

**Comment by yastij** [comment]
@stevvooe - time to work on this one.

**Comment by stevvooe** [comment]
@yastij I think this one can just have a rename to make it clear that it is the id of the network attachment container target.

**Comment by yastij** [comment]
@stevvooe to be closed when you have time

**Comment by thaJeztah** [comment]
let me do so; fixed by https://github.com/moby/moby/issues/34076 :+1:
