### ISSUE TITLE
can not successfully install docker-ce on ubuntu 16.04 ? why ,Can you help me?

### ISSUE THREAD

**Issue by whxloveyrh** [moby/moby#33689]
root@instance-4u1z1xql:~# apt install docker-ce 

ERROR INFO:

Jun 15 17:56:40 instance-4u1z1xql dockerd[31531]: time="2017-06-15T17:56:40.289072089+08:00" level=info msg="libcontainerd: new containerd process, pid: 31539"
Jun 15 17:56:41 instance-4u1z1xql kernel: aufs: disagrees about version of symbol module_layout
Jun 15 17:56:41 instance-4u1z1xql dockerd[31531]: time="2017-06-15T17:56:41.299671154+08:00" level=error msg="'overlay' not found as a supported filesystem on this host. Jun 15 17:56:41 instance-4u1z1xql kernel: overlay: disagrees about version of symbol module_layout
Jun 15 17:56:41 instance-4u1z1xql dockerd[31531]: time="2017-06-15T17:56:41.301776138+08:00" level=error msg="'overlay' not found as a supported filesystem on this host. Jun 15 17:56:41 instance-4u1z1xql kernel: overlay: disagrees about version of symbol module_layout
Jun 15 17:56:41 instance-4u1z1xql kernel: libcrc32c: disagrees about version of symbol module_layout
Jun 15 17:56:41 instance-4u1z1xql kernel: device-mapper: table: 252:0: thin-pool: unknown target type
Jun 15 17:56:41 instance-4u1z1xql kernel: device-mapper: ioctl: error adding target to table
Jun 15 17:56:41 instance-4u1z1xql dockerd[31531]: Error starting daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_runJun 15 17:56:41 instance-4u1z1xql systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 15 17:56:41 instance-4u1z1xql systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by amitkumarj441** [comment]
@whxloveyrh DId you removed the previous version of docker?

It seems like your system ports are busy, do check `docker ps -a`, below is the process to install docker community edition :
1. Remove previous version of docker and docker engine
    `$ sudo apt-get remove docker docker-engine`
2. Allow apt to use repo over https
    `$ sudo apt-get install
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common`
3. Add Docker official's GPG Key
    `$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`
4. Setting up stable repository
    `$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"`

   ` $(lsb_release -cs)`

   Above command returns the name of Ubuntu distribution like "Xenial"

5. Install Docker
    `$ sudo apt-get update`
    `$ sudo apt-get install docker-ce`

**Comment by whxloveyrh** [comment]
@amitkumarj441 
root@instance-4u1z1xql:~# <font color="red">docker</font>
The program 'docker' is currently not installed. You can install it by typing:
apt install docker.io
root@instance-4u1z1xql:~# <font color="red">apt remove docker docker-engine</font>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'docker-engine' is not installed, so not removed
Package 'docker' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  aufs-tools cgroupfs-mount linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic sbsigntool
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 94 not upgraded.
root@instance-4u1z1xql:~# <font color="red">apt install apt-transport-https cat</font>
catch     catcodec  catdoc    catdvi    catfish   catkin    
root@instance-4u1z1xql:~# <font color="red">apt install apt-transport-https ca-certificates curl software-properties-common </font>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.20).
curl is already the newest version (7.47.0-1ubuntu2.2).
software-properties-common is already the newest version (0.96.20.7).
The following packages were automatically installed and are no longer required:
  aufs-tools cgroupfs-mount linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic sbsigntool
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 94 not upgraded.
root@instance-4u1z1xql:~# <font color="red">curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key ad
d -</font>
OK
root@instance-4u1z1xql:~# <font color="red">apt-key fingerprint 0EBFCD88</font>
pub   4096R/0EBFCD88 2017-02-22
      Key fingerprint = 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
uid                  Docker Release (CE deb) <docker@docker.com>
sub   4096R/F273FCD8 2017-02-22

root@instance-4u1z1xql:~# <font color="red">add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    $(lsb_release -cs) \
>    stable"</font>
root@instance-4u1z1xql:~# lsb_release -cs
xenial
root@instance-4u1z1xql:~# apt update
Hit:1 http://mirrors.baidubce.com/ubuntu xenial InRelease
Hit:2 http://mirrors.baidubce.com/ubuntu xenial-updates InRelease
Hit:3 http://mirrors.baidubce.com/ubuntu xenial-security InRelease
Hit:4 https://download.docker.com/linux/ubuntu xenial InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
94 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@instance-4u1z1xql:~# <font color="red">apt install docker-ce </font>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic sbsigntool
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  docker-ce
0 upgraded, 1 newly installed, 0 to remove and 94 not upgraded.
Need to get 0 B/19.3 MB of archives.
After this operation, 89.0 MB of additional disk space will be used.
Selecting previously unselected package docker-ce.
(Reading database ... 114802 files and directories currently installed.)
Preparing to unpack .../docker-ce_17.03.1~ce-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce (17.03.1~ce-0~ubuntu-xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu13) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up docker-ce (17.03.1~ce-0~ubuntu-xenial) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@instance-4u1z1xql:~#

**Comment by thaJeztah** [comment]
This looks suspicious;

```
libcrc32c: disagrees about version of symbol module_layout
```

(also see https://unix.stackexchange.com/questions/125624/unable-to-load-module-disagrees-about-version-of-symbol-module-layout)

Are you running on a custom kernel version? The default kernel that ships with Ubuntu 16.04 should support overlay and overlay2 out of the box; if this fails there may be something wrong there.

You can try running the `check-config.sh` script to see if things are not configured correctly in your kernel (although it's possible it doesn't pick up all issues); https://github.com/moby/moby/blob/master/contrib/check-config.sh

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

The issue reported here looks like a problem with your environment. I'm closing this issue for that reason, but feel free to continue the conversation 👍

**Comment by hannut** [comment]
Ubuntu needs to have the "hwe" variant kernel installed (linux-generic-hwe-16.04). if the machine (or template) was originally installed with original 16.04-lts installation media the machine has the original 4.4 -version kernel in use. There is no mention about this on the official docker-ce installation instructions :)

**Comment by bor8** [comment]
The same problem applies to German Strato customers: Virtual servers at Strato have their own kernel, which does not support Docker: https://www.strato.de/faq/article/2427/Welche-Server-und-Betriebssysteme-bei-STRATO-sind-Docker-ready.html

**Comment by dkarapanos** [comment]
apt-get install libltdl7

**Comment by fertiland** [comment]
= solution = 
apt-get remove docker-ce
rm /etc/docker/*

= error logs =

root@master:/# apt-get install docker-ce=17.03.3~ce-0~ubuntu-xenial
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker-ce is already the newest version (17.03.3~ce-0~ubuntu-xenial).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up docker-ce (17.03.3~ce-0~ubuntu-xenial) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce

**Comment by muncha** [comment]
I had some similar errors that were a result of my VPN interfering with docker creating network interfaces. Turning off my VPN made it work.

**Comment by nicknesh** [comment]
In my case - missing  path to `/usr/sbin` - postinst script searches for `groupadd`, but it is not in PATH.

**Comment by xiaoliuzi** [comment]
> apt-get remove docker-ce
rm /etc/docker/*

It works!  Thank @fertiland !!
