### ISSUE TITLE
Clock drift in Docker for Mac

### ISSUE THREAD

**Issue by mcandre** [moby/moby#33697]
The clock in Docker for Mac gets out of sync with the host clock, after maybe a few weeks of uptime. When this happens, many different applications report SignatureExpired and similar errors about the drift.

Docker: 17.03.1-ce-mac12 (17661)
macOS: 10.12.5 (16F73)

Mitigation: Restart Docker for Mac every few days or so.

**Comment by cpuguy83** [comment]
This is fixed in the latest edge release (17.05). See https://github.com/docker/for-mac/issues/17#issuecomment-300734810

Thanks for reporting.
