### ISSUE TITLE
Template {.Service.Name} placeholder is not honored in compose-file hostname

### ISSUE THREAD

**Issue by mostolog** [moby/moby#33699]
**Description**

Deployed container **hostname does not honor template expected value**, as described in: https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates

**Steps to reproduce the issue:**
1.Create a stack.yaml
```
version: '3'
services:
  nginx:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    hostname: '{{.Service.Name}}'
    image: 'nginx:1.13.0'
    ports:
      - 80:80
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
```
2. Deploy the stack
> docker stack deploy --compose-file stack.yaml test

3. Browse the running tasks
```
> docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
627d6809d5b0        nginx:1.13.0                        "nginx -g 'daemon ..."   29 seconds ago      Up 28 seconds       80/tcp   
```

4. Print the hostname or login to the container to see the hostname

> docker exec -it 627d6809d5b0 hostname
test_nginx

> docker exec -it 627d6809d5b0 bash
root@test_nginx:/#

**Describe the results you received:**

Container is named **test_nginx**

**Describe the results you expected:**

Container should be named **nginx**

**Additional information you deem important (e.g. issue happens only occasionally):**

This might be problematic to https://github.com/docker/compose/issues/4475 -> https://github.com/docker/compose/issues/229

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: o6ax5ex63j24xb670wrkdw9la
 Is Manager: true
 ClusterID: wa2ceofyt5ofwb5bdpqo17lml
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 1.2.3.1
 Manager Addresses:
  1.2.3.1:2377
  1.2.3.2:2377
  1.2.3.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.851GiB
Name: host
ID: QDIZ:HAH6:OAJS:DUI6:K2TI:TH6W:JVKH:PKRD:X66K:HQK3:265E:IDNS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

CC: @stevvooe @thaJeztah

**Comment by mostolog** [comment]
Ping!?

**Comment by cpuguy83** [comment]
This is the nature of stack deploy. The stack is named `test`, so services get named `test_<compose_service>`

**Comment by cpuguy83** [comment]
Maybe the stack implementation could handle this...

**Comment by cpuguy83** [comment]
ping @dnephin

**Comment by dnephin** [comment]
This looks like it's working correctly. The service name is `test_nginx`. Maybe if stacks were a server-side concept there would be a template value that could be used here.

**Comment by mostolog** [comment]
IMHO as the service **IS** nginx, running within a stack, it shouldn't contain stack name.

Externally it should be identified by stack_nginx, but internally it shouldn't be aware of stack name!

What about deploying multiple stacks instances?
> stack deploy --compose-file stack.yml stack1
> stack deploy --compose-file stack.yml stack2

It makes no sense to hardcode "stack1_nginx" within nginx service (in stack.yml) but "nginx"

I think {{.Service.Name}} shall return service name (without stack), while {{.Stack.Name}} might return the stack name, allowing us to concat.
Otherwise...is there any way to get nginx instead of stack_nginx?

If won't fix, please feel free to close.

**Comment by cpuguy83** [comment]
@mostolog The service within the stack is nginx, but it's still within a stack.
The stack implementation could read the template and apply it's own scoped details... but I'm not sure that's a great move.

**Comment by Battleborn69** [comment]
Greed & Picks old system going out the window self destructed itself

**Comment by mostolog** [comment]
Well...my 2cent was to have both variables {{.Stack.Name}} and {{.Service.Name}} available, and IMHO it would be "easy to guess" how they work and use them accordingly.

This could also match the DNS proposal to resolve names locally and globally:
    name=nginx
    stackname=stack.nginx
    swarmname=cluster.stack.name

When are **service names** referenced outside of stack??

**Comment by dnephin** [comment]
We could store the unscoped service name in a label, which I believe would let you use the label to accomplish what you want.

**Comment by thaJeztah** [comment]
continued in https://github.com/docker/cli/issues/612
