### ISSUE TITLE
Containers fail to mount volumes using linked folders on restart

### ISSUE THREAD

**Issue by Nicholas-Abbott** [moby/moby#33709]
**Description**
When creating a data volume container it is possible to link this folder to a location on the host machine so you can modify or access these files without having to go through the docker container to do so. Normally this works perfectly but if the containers are set to restart automatically when the host machine restarts or you restart the docker client the containers fail to mount the linked volume and therefore fail to start.

**Steps to reproduce the [issue:**]
(https://docs.docker.com/engine/tutorials/dockervolumes/#creating-and-mounting-a-data-volume-container)
1. Create a folder to act as volume e.g. `C:\Users\<username>\storage`
1. Create a data volume container using a linked folder:
`docker create -v /c/Users/<username>/storage:/dbdata --name dbstore training/postgres /bin/true`
2. Mount the volume in another container that will always restart:
`docker run -d --volumes-from dbstore --name db1 --restart=always training/postgres`
3. Restart docker or the host machine

**Describe the results you received:**
Every container attempting to mount the volume attempts to restart but fails with this error in its log:
`container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/c/Users/<username>/storage\\\" to rootfs \\\"/var/lib/docker/overlay2/7fd6786cef2650ffb4596b58e5f31045ee2b91df3fbd1cdb90468c1f897f7247/merged\\\" at \\\"/dbdata\\\" caused \\\"stat /c/Users/<username>/storage: no such file or directory\\\"\""`

**Describe the results you expected:**
Each container to restart successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
Once docker is running you can manually start every container without issue even if they attempted to restart during the boot process and failed. This only occurs during the docker boot process. This happens with all images, not just postgres.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: IYPN:RS7T:AX5C:3DY6:GYQI:4EYW:ZQ76:3XGG:TYIT:5NCB:KXNB:CEBB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 26
 System Time: 2017-06-15T22:05:11.2889767Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This has been tested on multiple host machines running Windows 10

**Comment by thaJeztah** [comment]
Looks like this is an issue with Docker for Windows, which has its own issue tracker; if you're still running into this, could you open an issue in the Docker for Windows issue tracker? https://github.com/docker/for-win/issues

I'll close the issue here, but feel free to comment
