### ISSUE TITLE
[Feature]Add Total  diskspace and Total diskspace still available/used info

### ISSUE THREAD

**Issue by bklau** [moby/moby#33703]
Currently neither 'docker info' nor 'docker node inspect' returns any info related to the diskspace allocated to docker daemon( /var/lib/docker):

1. Total diskspace allocated
2. Total available/used.

This makes it difficult to schedule  containers to nodes that  have sufficient diskspaces at the risk of getting "disk quota exceeded" error message.

**Comment by allencloud** [comment]
Can command `docker system df` satisfy you?

like : 
```
root@ip-172-31-23-42:~# docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              47                  4                   12.2GB              11.85GB (97%)
Containers          13                  0                   153.3MB             153.3MB (100%)
Local Volumes       10                  1                   215.6MB             215.6MB (100%)
```

**Comment by bklau** [comment]
@allencloud   I'm trying to use the Docker Remote API to ascertain the best node to schedule my containers on by determining if there are enough diskspace for them. There are few salient points about 'docker system df' that you mentioned above:
1. It's based on a single node  you choose to run the system command on. I need to know all the diskspaces per node so that i can select the 'best one' to schedule my containers on via 'constraint' filter.

2. It shows the disk usage by the various entities and how much can be reclaimed, presumably via 'docker system prune' or equivalents of 'docker image/container/volume prune' This doesn't help becuase it doesn't tell how much diskspace is still available.

This feature request above relates to showing the total diskspace allocated for docker to use
and amount still available/has been used. This info can be added to 'docker info' and 'docker node inspect <node_XYX>' because:

**1. 'docker info'** 
 returns a list of node info if either swarm standalone or swarm mode is used where
└ Reserved CPUs and └ Reserved Memory shows how much memories are allocated and how much used.  Can the same can be done for diskspace ??
=================================
$ docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: swarm/1.2.6
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 2
 node1: 10.245.1.21:2375
  └ ID: NU2P:WY7M:Q2IY:HXIK:WVLW:MLLG:R3L3:VHGN:5SR2:GUDO:OXVG:45TI
  └ Status: Healthy
  └ Containers: 2 (2 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0.5 / 1
  └ Reserved Memory: 0.8 GiB / 1.018 GiB
  └ Labels: availability-zone=az-1, kernelversion=4.8.6-201.fc24.x86_64, operatingsystem=Fedora 24 (Twenty Four), storagedriver=btrfs
  └ UpdatedAt: 2017-06-16T18:16:10Z
  └ ServerVersion: 1.12.2
 node2: 10.245.1.11:2375
  └ ID: ZK7L:MHDZ:2YRN:CHJ3:4XOB:3TSZ:YM54:RW5B:GHNE:DARC:7VCK:F6ST
  └ Status: Healthy
  └ Containers: 2 (2 Running, 0 Paused, 0 Stopped)
  **└ Reserved CPUs: 1/ 2
  └ Reserved Memory: 1.1GiB / 2.051 GiB**
  └ Labels: availability-zone=az-1, kernelversion=4.8.6-201.fc24.x86_64, operatingsystem=Fedora 24 (Twenty Four), storagedriver=btrfs
  └ UpdatedAt: 2017-06-16T18:16:23Z
  └ ServerVersion: 1.12.2
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Kernel Version: 4.8.6-201.fc24.x86_64
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 3.069GiB
Name: controller
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false
======================

**2. 'docker node inspect'** 
$ docker node inspect --pretty self
ID:                     e216jshn25ckzbvmwlnh5jr3g
Hostname:               swarm-manager
Joined at:              2016-06-16 22:52:44.9910662 +0000 utc
Status:
 State:                 Ready
 Availability:          Active
 Address:               172.17.0.2
Manager Status:
 Address:               172.17.0.2:2377
 Raft Status:           Reachable
 Leader:                Yes
Platform:
 Operating System:      linux
 Architecture:          x86_64
**Resources:
 CPUs:                  4
 Memory:                7.704 GiB**
Plugins:
  Network:              overlay, bridge, null, host, overlay
  Volume:               local
Engine Version:         1.12.0

**Comment by thaJeztah** [comment]
Related https://github.com/moby/moby/issues/34440

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
