### ISSUE TITLE
'--compress', '-f -' and context do not play along

### ISSUE THREAD

**Issue by RomanSaveljev** [moby/moby#33706]
**Description**

Docker build fails.
A command like this will fail:

```
docker build -t xxx -f - --compress . <Dockerfile
```

**Steps to reproduce the issue:**
1. My `Dockerfile` has a single `FROM alpine` statement
2. There is no other files in the context (`.`) folder
3. Run `docker build --verbose -t xxx -f - --compress . <Dockerfile`

**Describe the results you received:**

```
$ docker build -t xxx -f - --compress . <Dockerfile
Sending build context to Docker daemon 

error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=.dockerfile.894e5d7100166c80399a&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=xxx&target=&ulimits=null: unexpected EOF
```

**Describe the results you expected:**

Successful build

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1018
 Running: 0
 Paused: 0
 Stopped: 1018
Images: 8576
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5187
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.6MiB
Name: systest-tools-releases-bot
ID: MJ4N:O2KV:ZZXR:FHNU:TY6U:D57G:OKMV:KB2O:QLU4:DGYZ:MVLF:T336
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker engine runs in AWS node

**Comment by thaJeztah** [comment]
Is this only if there's no other files in the build context, or also if there are other files?

Tangential to this; if you're building against a local daemon, I'd recommend not using the `--compress` option; in most cases (especially on a local daemon), using that flag will actuallly give you worse performance.

**Comment by ripcurld0** [comment]
@RomanSaveljev I'm a bit confused regarding the command line arguments:
```
docker build --verbose -t xxx -f - --compress . <Dockerfile
```

1) `--verbose` is not a valid flag in `docker-build` (at least not in version 17.05)
2) you are using the `-f` switch but you don't specify the name of the Dockerfile
3) the `--compress` should have been before the `-` not after
4) on one hand you want to build the image according to `Dockerfile` in your current working directory but on the other hand you want pass it through the `stdin`.

Can you please fix the command line?

Thanks. 🌵

**Comment by RomanSaveljev** [comment]
@ripcurld0 thanks, I removed the `--verbose` from the command.. No idea how it made it there

If you look a bit more carefully, you will spot a single `-` between `-f` and `--compress` in my example.

@thaJeztah I am aware of compression implications. I have reported against reduced usecases. I typically use remote docker engines. The issue reproduces also with other files in the context.

**Comment by thaJeztah** [comment]
Thanks for the additional information, and reproduction steps. I was able to reproduce this on 17.06.0-rc4;

```bash
$ mkdir repro-33706 && cd repro-33706
$ echo "FROM busybox" > Dockerfile
$ touch foo bar baz
```

With `--compress`

```bash
$ docker build -t repro-33706 -f - --compress . <Dockerfile
Sending build context to Docker daemon

error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.30/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=.dockerfile.f92440440ad6bc42e6af&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=repro-33706&target=&ulimits=null: unexpected EOF
```

Without `--compress`;

```bash
$ docker build -t repro-33706 -f - . <Dockerfile
Sending build context to Docker daemon  3.597kB
Step 1/1 : FROM busybox
 ---> 7968321274dc
Successfully built 7968321274dc
Successfully tagged repro-33706:latest
```

ping @dsheets @tonistiigi PTAL

**Comment by tonistiigi** [comment]
@thaJeztah What's the process for cli issues, should this move to `docker/cli`?

**Comment by thaJeztah** [comment]
@RomanSaveljev discussing this with @tonistiigi  - and this looks to be a client-side issue. I reopened the issue here; https://github.com/docker/cli/issues/212, and will close this one.

Thanks for reporting, and feel free to comment after I closed 👍
