### ISSUE TITLE
Docker excessive disk space usage

### ISSUE THREAD

**Issue by jycr753** [moby/moby#33718]
**Description**
Docker keeps using disk space after removing all images, containers and volumes.
.....

**Steps to reproduce the issue:**
1. Create a basic [docker-compose](https://github.com/harshjv/docker-laravel/blob/master/docker-compose.yml) file for php development 
2. `docker-compose up -d --build`
3. `docker-compose down`
4. `docker rmi $(docker images -a -q) --force`
5. `docker rm $(docker ps -a -f status=exited -q)`
6. `docker volume rm ... ...`

**Describe the results you received:**
So when I look for what is actually being saved by docker I do get the right output, I have nothing right now:
```

> $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

> $ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

> $ docker volume ls
DRIVER              VOLUME NAME

```
**Describe the results you expected:**
So far so good, but when I go into the real storage of my docker installation this still relatively big. I would have expected this to be a lot smaller when I have nothing in my docker.

<img width="503" alt="screen shot 2017-06-16 at 10 03 05 pm" src="https://user-images.githubusercontent.com/1929689/27243233-396aa22e-52e1-11e7-96ee-1aebc69974b2.png">
 
**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: 5ANU:4BSB:W6H3:MOQU:PE42:2E5N:JJDA:OKE5:A6Z2:JR4X:DV6F:NEAB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-06-16T20:18:10.452975998Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting; this is an issue specific to Docker for Mac; see the issue here; https://github.com/docker/for-mac/issues/371 for more information and background

I'll close this issue, because this is not something that can be resolved in this repository, but feel free to comment after I closed 👍
