### ISSUE TITLE
Build Feature: Allow for temporary build layers, which are not included in the resulting container.

### ISSUE THREAD

**Issue by trickkiste** [moby/moby#33716]
Sometimes during a build, one introduces layers, which occupy a lot of space, but are not needed in the final container. This might be a source directory for example.

With the introduction of a TEMPORARY flag, one could mark such layers to not be included in the final container.

The Dockerfile would look like this for example
```
...
TEMPORARY COPY . /usr/src/app/
TEMPORARY RUN cd /usr/src/app && npm run build
RUN cp -a /usr/src/app/build /srv/app
WORKDIR /srv/app
CMD ["node app.js"]
```

The layers resulting from the COPY and the first RUN command (prefixed with TEMPORARY) would then not be used when a container is assembled and will therefore also not be uploaded to the registry on `docker push`.

A lot of things, we are now doing in a rather complicated manner in our build scripts, in order to keep the size of the image down, could then be written in a much more verbose way!

**Comment by thaJeztah** [comment]
Have you tried the multi-stage builds that are now supported in docker? I think they provide what you're asking for

**Comment by trickkiste** [comment]
No, I have not heard about them yet.
I will try.

Still, this feature seems like a lot of value for not a reasonable amount
of effort, so I hope you will consider it even though.

My best Regards,
Markus

--

Markus Kienast - CEO
<mark@sfe.tv>mark@trickkiste.at
+43699180 84401

Trickkiste KG
Löhrgasse 19/29
1150 Wien
Austria / Europe

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http://trickkiste.at

2017-06-16 19:39 GMT+02:00 Sebastiaan van Stijn <notifications@github.com>:

**Comment by thaJeztah** [comment]
The builder is a complex system, especially due to content addressable store, reproducibility, and caching; things may seem "easy" to implement, but can be very complex 


Having said that, I think the multi stage build is what you're looking for.

**Comment by thaJeztah** [comment]
I think this is resolved through a combination of multi-stage builds and the `RUN --mount` option that's provided buildkit (which is now the default builder)
