### ISSUE TITLE
Allow setting MAC address in network connect

### ISSUE THREAD

**Issue by LuisPiedra** [moby/moby#33715]
Allow setting mac-address when using network connect. Currently it is possible to do so when running a container, but when more than one network is needed, network connect is the only way.

It seems it is supported in Docker Engine API, at least fron 1.25 (https://docs.docker.com/engine/api/v1.25/#operation/NetworkConnect), but it's not included in the CLI

**Steps to reproduce the issue:**
```
1. docker create --name my_container ubuntu:16.04 /bin/bash -c "cat /sys/class/net/eth0/address" 
2. docker network connect --mac-address="92:20:de:b0:6b:62" my_net my_container
```

**Describe the results you received:**
```
unknown flag: --mac-address
See 'docker network connect --help'.
```

**Describe the results you expected:**
```
# docker start --ai my_container
> 92:20:de:b0:6b:62
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by PMExtra** [comment]
Any update?

**Comment by Kiuber** [comment]
Any update?

**Comment by LuisPiedra** [comment]
Closed because inactivity
