### ISSUE TITLE
Add volume to stopped conainer

### ISSUE THREAD

**Issue by rivaros** [moby/moby#33717]
Have a situation when I need to add/remove volumes from existing container (recreating container is OK, no need to have it in runtime).

Imagine running container A with mapped volumes v1 and v2.
Need to add v3 to it but I know nothing about currently mapped volumes.

So I stop container and then start it with -v "somepath":/v3, but then a problem - I loose v1 and v2. 

Can it be started with existing volumes (plus a new one).

**Comment by programmerq** [comment]
You can always create a container, and specify the same volumes that another container already has. There are two simple ways to do this:

* Use `--volumes-from`:

```docker run -v /path1:/v1 -v namedvolume2:/v2 --name existingcontainer ...```

followed by:

```docker run -v /somepath:/v3 --volumes-from existingcontainer ...```

* Inspect the existing container, and enumerate the volumes that it has. Specify those same volumes when you create a new container. This gives you more flexibility (for example, if you only wanted to grab `/v2` but not `/v1`):

```docker inspect existingcontainer```

Look for the "Mounts" section, and you will see all the attached volumes for a given container.

You can take those, and write your own. If there is a "Name" key for a given amount, that means it is a named or anonymous volume, and you should see the corresponding Name if you do a `docker volume ls` .
