### ISSUE TITLE
docker stack ps --filter option should be "desired-state" and not "desired-stat" as in documentation

### ISSUE THREAD

**Issue by dvohra** [moby/moby#33720]
The `docker stack ps --filter` option should be "desired-state" and not "desired-stat" as in documentation.
https://docs.docker.com/engine/reference/commandline/stack_ps/#extended-description

**Steps to reproduce the issue:**
1.Create a Swarm mode
2.Create a Stack
3.List stack containers with `docker stack ps --filter desired-stat=running`

`desired-stat` is not a filter

A list of running containers in the stack.

**Additional information you deem important (e.g. issue happens only occasionally):**
A documentation bug. 

Docker 17.03

**Output of `docker info`:**

Not relevant as the bug is in the documentation. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for AWS Stable used to create Swarm.

**Comment by yuexiao-wang** [comment]
@thaJeztah @albers  
Documentation is updated in docker.github.io. This issue can be closed

**Comment by dvohra** [comment]
Thanks @yuexiao-wang.

**Comment by thaJeztah** [comment]
Thanks! closing this one
