### ISSUE TITLE
GraphDriver plugin Diff not called

### ISSUE THREAD

**Issue by EnacheB** [moby/moby#33734]
**Description**

Graphdriver plugins do not implement DiffGetterDriver, so they cannot provide a specialized tar stream via Diff.

I'm writing a GraphDriver plugin that stores all images in shared storage and passes identifiers for these images instead of their layer data. Unfortunately, Diff is never called, so I don't have any control over what data is being passed around. 

After reading through some of the layer and graphdriver code, I think the cause is that the [graphdriver plugin proxy](https://github.com/moby/moby/blob/master/daemon/graphdriver/proxy.go) does not implement the DiffGetterDriver interface, so the daemon doesn't use it to get diffs.

DiffGetterDriver declaration: https://github.com/moby/moby/blob/master/daemon/graphdriver/driver.go#L134

If statement deciding whether to use the naive diff or the plugin's diff: https://github.com/moby/moby/blob/master/layer/layer_store.go#L682

**Steps to reproduce the issue:**
1. Create GraphDriver plugin using go-plugin-helpers
2. Put print statement in Diff method
3. `docker push` an image

**Describe the results you received:**
Diff does not get called, only Get and Put

**Describe the results you expected:**
Diff gets called on the layers

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens while running the graphdriver plugin on `dockerd --experimental -s mygraphdriver`

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: purestorage-graphdriver-plugin:1.0-4e4d130-dirty
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.9 GiB
Name: r66a-33
ID: F4IW:TCMP:LLKL:R5PX:Z77Q:JWWD:2P5A:5M6T:AJS2:GXNA:D6HK:N53P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 31
 System Time: 2017-06-19T13:48:42.146848441-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 r66a-32:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is on a kvm virtual machine.

**Comment by cpuguy83** [comment]
Starting in 17.05(?) docker now calls a `Capabilities` endpoint on the plugin which can return if it can reproduce exact diffs... https://github.com/moby/moby/blob/master/daemon/graphdriver/driver.go#L123

Does this work for you?

**Comment by EnacheB** [comment]
Yup, that was our problem. Thanks!
