### ISSUE TITLE
swarm manager and workers not communicating with each other

### ISSUE THREAD

**Issue by ksachdev1** [moby/moby#33737]
**Description**
I have been using docker swarm for few months on both Cent OS 7.2 and 7.3. Since last few weeks. I have started running into a problem that occurs quite often and sometimes almost always. I created a CenOS OVA with my docker images on it and in swarm manager node. After that I wrote a script which would make this standalone node move itself out of manager mode and would join a new manager given the token and the ip of the new manager node.  The firewall is disabled.

**Steps to reproduce the issue:**
1. I would deploy OVA and create a standalone Master node.
2. I would use the same OVA and deploy another standalone master node, execute my script and make this node as worker1 and join the Master that was created in step 1
3. I would deploy OVA the third time and make this node worker2 and join the Master. 

**Describe the results you received:**
The docker service stack that I had deployed already while creating the OVA is on master node and when workers join, the swarm sometimes moves them on workers which is normal. However, the port forwarding never worked on this setup until all 3 nodes were rebooted. 

Another similar issue observed was that on the worker I did "iptables -F", restarted the docker daemon thinking this will make port forwarding go through but it did not happen. In fact the worker was shown as down on master until the worker was rebooted. 

When master went down and came up, it was not able to see the workers until the workers were rebooted. 

I am pasting the output of docker version below
Client:
Version: 17.05.0-ce
API version: 1.29
Go version: go1.7.5
Git commit: 89658be
Built: Thu May 4 22:06:25 2017
OS/Arch: linux/amd64

Server:
Version: 17.05.0-ce
API version: 1.29 (minimum version 1.12)
Go version: go1.7.5
Git commit: 89658be
Built: Thu May 4 22:06:25 2017
OS/Arch: linux/amd64
Experimental: false

How do I debug this issue. We are going to go in production soon and this has become a major blocker for us.

**Comment by thaJeztah** [comment]
Are you still running into this issue on the current stable release (17.06 or 17.09)?

**Comment by ksachdev1** [comment]
This issue happens sporadically. For the time being we were trying to skirt around it. I am still fairly positive, that if we create ova with already created swarm cluster, this problem will happen. I am not certain what logs you require for this.

**Comment by thaJeztah** [comment]
If I understand correctly, you're creating a VM / snapshotting the master, and create workers from that state? Before doing so, do you cleanup the `/var/lib/docker` directory (and the `/var/lib/docker/swarm` directory?)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
