### ISSUE TITLE
Office doesn't work inside Container - Windows Server Container

### ISSUE THREAD

**Issue by mjoedicke** [moby/moby#33744]
**Description**

**Steps to reproduce the issue:**
1. Steps to reproduce can be found here: https://social.msdn.microsoft.com/Forums/de-DE/411089ad-3085-4250-945f-3afd678afc74/error-failed-to-load-dll-coffice2013propluswwosetupdll-errorcode-1260x7e-when-install?forum=windowscontainers
2.
3.

**Describe the results you received:**
Error: Failed to load DLL: C:\Install\Office2010proproduction\ProPlus.WW\OSETUP.DLL ErrorCode: 126(0x7e).

**Describe the results you expected:**
Running Office exports in our main application

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Version:      17.05.0-ce
API version:  1.29
Go version:   go1.7.5
Git commit:   89658be
Built:        Fri May  5 15:36:11 2017
OS/Arch:      windows/amd64

erver:
Version:      17.05.0-ce
API version:  1.29 (minimum version 1.24)
Go version:   go1.7.5
Git commit:   89658be
Built:        Fri May  5 15:36:11 2017
OS/Arch:      windows/amd64
Experimental: falseContainers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 106
Server Version: 17.05.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.96GiB
Name: win2016
ID: KXLN:3NFP:YUPA:G642:EM46:5BTA:Y6ON:PVVL:XL3C:QSKD:3PZD:ZLC5
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by unclejack** [comment]
@jhowardmsft: Do you happen to know anything about this?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
