### ISSUE TITLE
/var/lib/docker/devicemapper/mnt/<id>/  is empty!

### ISSUE THREAD

**Issue by JoshuaAndrew** [moby/moby#33741]
1>  Why are there so many empty directories, and when should they be empty?
[root@ceph-2 mnt]# pwd
/var/lib/docker/devicemapper/mnt
[root@ceph-2 mnt]# tree -L 2
.
|-- 01ef7193dbfd9c1df67cfde333b6e1d02b16b396109201cff12b3fca7b85e409
|   |-- id
|   `-- rootfs
|-- 01ef7193dbfd9c1df67cfde333b6e1d02b16b396109201cff12b3fca7b85e409-init
|-- 09a8dda574ed0b8c25d0435cf9d063f18ac21791ae1b65cc6e47aa7c218f7399
|-- 0a2d19ceee990ce220ac6a2f0066a5e98712ec9e551189a2563ac749ecc3e4a5
|-- 0cf0fb3a081c025ebcd14d7d9a69647399c19a71f9dfe83791c798098e01867c
|-- 10c87ef5efd5d6fe63b396b6e27f324f8da8fac8b6553108a29e5670f6cb538f
|-- 18898ee721d8eb1c11bf3a0292628164f83b3acfb8628922ec7df118f7d86ad8
|-- 18898ee721d8eb1c11bf3a0292628164f83b3acfb8628922ec7df118f7d86ad8-init
|-- 24c2b909bfa6e9eabc6761173ff1e7cc6d7cf47e7eae4b2ad01cd0a208ceaa84
|-- 251f6cd02731fea0a706bffac1548a7fb4fec6a7379e8306ad6d1aae82cebdde
|-- 292ec2a095290166cc88dbea5184846de22d1568268bffb16ccff9da406f042d
|-- 2cdc82714c71974f1fcf49d3f2b4b560bc3e19f99a4cdfe0e9aa948441b3d40f
|   |-- id
|   `-- rootfs
|-- 2cdc82714c71974f1fcf49d3f2b4b560bc3e19f99a4cdfe0e9aa948441b3d40f-init
|-- 2ea16719f7ed651e35eb3784b6f166bca5f7566435b149c7c103b36c46e87653
|-- 35ad5ca8edd12330a52223e905adca80a37cc11b188b9fc0a8ebc373473a6acf
|-- 37a5baf7cec749b9c96bb2eb0df6332164a081b3c3889c0c5091edaa4cd4d99f
|-- 405a0844a0bff5b88b61e4c4ee2ee3c4f2aa732c02dada2d85198a9f69adffa3
|-- 4578fc56df17b55174c9fa48edd3f4284bee2067dd0b2b1edb809f4bfc1c6896
|-- 4aac94d1270e14a547398653d3fdf49785fe18b0a74b0cfe53d6814679644f84
|-- 5363b6887014bf188cd7e8faa33ae7edeff3693a49d856f9deef1c2251c888c2
|-- 5363b6887014bf188cd7e8faa33ae7edeff3693a49d856f9deef1c2251c888c2-init
|-- 5e07071a1fce2c5831d960501b6d58d3097481e307eca926de440ddc93df6e82
|-- 6a1e58bac5ec8309a9b9717140b2106e9f3f573e31aa4fa0bf735b633a1f38f3
|   |-- id
|   `-- rootfs
|-- 6a1e58bac5ec8309a9b9717140b2106e9f3f573e31aa4fa0bf735b633a1f38f3-init
|-- 6b777fa5df20b61672f9265f64f44859d79abcc6d7b6df2c59f06c9b787db5ca
|-- 6b777fa5df20b61672f9265f64f44859d79abcc6d7b6df2c59f06c9b787db5ca-init
|-- 6d37e508e8718988138d88ffb39692d7251e9c8010319ff3a6084246749ed065
|-- 6d37e508e8718988138d88ffb39692d7251e9c8010319ff3a6084246749ed065-init
|-- 6f85d0d9fddffd18e813ad48aafb182af8b62df2e5dac6084fbc74d216fc6404
|   |-- id
|   `-- rootfs
|-- 6f85d0d9fddffd18e813ad48aafb182af8b62df2e5dac6084fbc74d216fc6404-init
|-- 82b1506e4f8e93b7e4ca8653b0ad3692ee9cb88b096aaf60467fcb4c4c6d4137
|   |-- id
|   `-- rootfs
|-- 82b1506e4f8e93b7e4ca8653b0ad3692ee9cb88b096aaf60467fcb4c4c6d4137-init
|-- 82f792784cd7a63b215d11656c45d885fd6d553d3a26e79ec90a5e18a9f6a010
|-- 96b3a1ada6b946ee1d29006cde4c5c72e74ddde5f4b38279bc213a56f9249e95
|-- 99d91e5b468a29589f513a3c71d4f561f85d09ecc02bdc78d22c6da8aa1e77b7
|-- 9a0e1c154f609b5ac40f8fa71748e388d93ef5d03805881c70ab877ae75c57f2
|-- a70addb90d3a2175e1c46e37ff35169ccc810cdf12aa95bf23f5756077a32629
|-- a896293a56eda1a06c781fa3565091336fd53c67dd0eeacfca0aba8ce8bd01c4
|   |-- id
|   `-- rootfs
|-- a896293a56eda1a06c781fa3565091336fd53c67dd0eeacfca0aba8ce8bd01c4-init
|-- a902c15873404d6d9bee3158e9e9c83e6f9aa221a42bca8234b673d095b50646
|-- af37841f598a88029aa761b8d82973fe30bcc0db5e6ccd2b96522f74a690ca8d
|-- bcc061324a40d7270219b0878e4722ca91f4dee3f7572b836f20425fe8ae783d
|-- c13e5cc435d7657e3b7976a1c4b7a9ee6deff1a231702b9ace1c45a536b04e07
|   |-- id
|   `-- rootfs
|-- c13e5cc435d7657e3b7976a1c4b7a9ee6deff1a231702b9ace1c45a536b04e07-init
|-- c1863d2772b1e302f000d39e1236d37ef6fe2f1b1b87064c608f7647ea49c812
|-- c279cbdeac62dd932f2342c977f7f3e1d3a15d52fb26e37cd80e45de6b70095d
|-- cc80587b95daa3b935d4dd168bf5775fe8077830ae77b0801767a2f9a140aad8
|   |-- id
|   `-- rootfs
|-- cc80587b95daa3b935d4dd168bf5775fe8077830ae77b0801767a2f9a140aad8-init
|-- d3d771eec6262a13d7d7d3bf7593b614aab0a19e6800ce855c4c90107207bb1d
|-- d5bad5f8de02f65df408cfb1122b34953453fe6cc85899cae3d9a4ec05ea119f
|-- d7eea8f0419958aec3c7ca8f743c1acd61536a24528b13110e262576b6a8226c
|-- dec7dc1051b9d332ec2a6ec2d2e36de0aa0149c682035b8dfd799bba871fcb85
|   |-- id
|   `-- rootfs
|-- dec7dc1051b9d332ec2a6ec2d2e36de0aa0149c682035b8dfd799bba871fcb85-init
|-- e48a840840a93a30ebcda0dcddb0dbdbe72ccc1258434f7c99b726b24c7c2deb
|-- e48a840840a93a30ebcda0dcddb0dbdbe72ccc1258434f7c99b726b24c7c2deb-init
|-- e5c78fbdc1465401f86825236f1ace82c17d1411b3824410ea55e2912d6ba100
|-- e5c78fbdc1465401f86825236f1ace82c17d1411b3824410ea55e2912d6ba100-init
|-- ed86ed91c6f1eefaf76b2907e659ae07bb48636f224a16c1a208cd892b35d115
|-- fb0655f1f423d342924053409f21ea711dc2fc8d4764ccb7be1fae2f13cb04a4
`-- fdd83ee616a854e55f18f9fb3173321754a8b147b7b5d11b02991fb990002487

2> docker version
[root@ceph-2 mnt]# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
Could be a couple of reasons.
Do you have containers running with any of these IDs?

What does your init script look like? The mount namespace that  Docker is using could be private such that you won't see anything there while in the host mount namespace.

**Comment by thaJeztah** [comment]
closing as this went stale

**Comment by sjeeva** [comment]
I am seeing same issue on 
Server:
 Version:      17.03.2-ce
