### ISSUE TITLE
Cannot restart container, cause by "endpoint create on GW Network failed: service endpoint with name gateway_xxx already exists"

### ISSUE THREAD

**Issue by BSWANG** [moby/moby#33756]
**Description**
Cannot restart container, cause by "endpoint create on GW Network failed: service endpoint with name gateway_xxx already exists"

**Steps to reproduce the issue:**
1. restart a running container.

**Additional information you deem important (e.g. issue happens only occasionally):**
issue happens only occasionally

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by BSWANG** [comment]
Similar to #23302 , but this issue is the `docker_gwbridge` network, not depends the remote KV or `swarm mode` raft store.

**Comment by BSWANG** [comment]
When the endpoint have port-mapping, the node can not reuse the port until `service docker stop; rm -fr /var/lib/docker/network/files/local-kv.db ; service docker start`.

**Comment by antoinetran** [comment]
Issue reproduced in 17.06-ce. Sometime we have to delete endpoint from the Key Value store (Zookeeper in our case), sometime we have to stop the machine where local-kv.db contains the ghost endpoint, then restart docker.

**Comment by antoinetran** [comment]
I don't know if relevant, but we have 3 SwarmManager (classic mode 1.2.6), with 3 zookeeper 3.4.10. In zookeeper logs, we have logs like:

> 2017-08-10 08:07:26,833 [myid:2] - INFO  [ProcessThread(sid:2 cport:-1)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x35dc762ae1f000c type:create cxid:0x1ff7d9 zxid:0x2200010414 txntype:-1 reqpath:n/a Error Path:/docker/network/v1.0/endpoint Error:KeeperErrorCode = NodeExists for /docker/network/v1.0/endpoint

> 2017-08-10 08:08:49,972 [myid:2] - INFO  [ProcessThread(sid:2 cport:-1)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x25dc762c820000d type:setData cxid:0x220a4d zxid:0x220001051b txntype:-1 reqpath:n/a Error Path:/docker/network/v1.0/endpoint_count/4dd9660354e18e0ffc0fe4ef14133a60d9ddae161415739863343fe093224c5f Error:KeeperErrorCode = BadVersion for /docker/network/v1.0/endpoint_count/4dd9660354e18e0ffc0fe4ef14133a60d9ddae161415739863343fe093224c5f

**Comment by thaJeztah** [comment]
@antoinetran the external k/v store (classic swarm) uses different mechanisms so your case is likely not related.

@BSWANG you mention "restarting a container" is that container started manually, or part of a service?

**Comment by antoinetran** [comment]
@thaJeztah : what makes you think the author is using Swarm mode or Swarm classic mode?

**Comment by antoinetran** [comment]
I will add more info for Swarm Classic. If the author says this is for Swarm mode, I will create another issue.

Swarm classic 1.2.7 might solve this issue: see https://github.com/docker/swarm/issues/2750 .

**Comment by BSWANG** [comment]
@thaJeztah @antoinetran This issue‘s endpoint is the docker_gwbridge endpoint. It will store into local-kv blobdb database. Not the overlay endpoint in external kv.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
