### ISSUE TITLE
unable to launch nginx localhost after starting the webserver

### ISSUE THREAD

**Issue by gobinathchinnannan** [moby/moby#33758]
**Description**
Unable to launch nginx localhost after starting the webserver

**Steps to reproduce the issue:**
1. docker pull nginx:1.12.0 in Windows Docker ToolBox
2. docker run -it -d -p 8080:80 nginx:1.12.0
3. Launch the localhost in browser (http://localhost:8080)
4. Even i tried curl command from Docker Host and getting error "Connection refused"
              $ curl http://localhost:8080
                 curl: (7) Failed to connect to localhost port 8080: Connection refused

**Describe the results you received:**
Hmmm.can't reach this page

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment]
@gobinathchinnannan please provide `docker version` and `docker info` to get all the needed details to resolve this issue.

Thanks

**Comment by gobinathchinnannan** [comment]
![image](https://user-images.githubusercontent.com/29590290/27895301-69c5f7b6-61d7-11e7-9a77-1e563f9fe6c6.png)
![image](https://user-images.githubusercontent.com/29590290/27895313-846bd252-61d7-11e7-8327-417c0ab7ca07.png)

**Comment by ripcurld0** [comment]
@gobinathchinnannan the Docker host is installed on a virtual machine that has a different IP address. Thus, you can't access the nginx server by going to localhost:8080. 

For example, in the following image, it is specified that the Docker host IP address is 192.168.59.103
![windows toolbox](https://docs.docker.com/toolbox/images/b2d_shell.png)
So you will have to curl to http://192.168.59.103:8080 to access nginx.

For more information, I suggest you to read [this document](https://docs.docker.com/toolbox/toolbox_install_windows/#step-1-check-your-version).

Thanks.

@thaJeztah tag this as a question and close it. 🍡

**Comment by thaJeztah** [comment]
Ah, thanks, yes that looks about right 👍 

I'll close this issue, but feel free to continue the conversation

**Comment by ayush5588** [comment]
@boaz0 Thank you for your solution. It worked for me. 
For finding docker host ip address -> 
**$ docker-machine ip default**

**Comment by pramodSanga** [comment]
@ayush5588 thanks bro. Your command worked for me.
