### ISSUE TITLE
Docker Swarm inoperable after reboot

### ISSUE THREAD

**Issue by drnybble** [moby/moby#33769]
**Description**

**Steps to reproduce the issue:**
Using Docker Toolbox, run the Docker Quickstart Terminal to create the default VM.
Create a network for the swarm.
`docker network create swarmnet`
Create two Docker-in-Docker containers to act as managers:
```
docker run -d --privileged --network swarmnet --restart=always --hostname m2 --name m2 docker:dind
docker run -d --privileged --network swarmnet --restart=always --hostname m3 --name m3 docker:dind
```
Initialize the swarm with the host VM acting as manager 1.
`docker swarm init --advertise-addr 172.18.0.1`
Generate the manager token:
`TOKEN=$(docker swarm join-token manager -q)`
Join m2 and m3 to the swarm:
`docker exec m2 docker swarm join --token $TOKEN 172.18.0.1:2377`
`docker exec m3 docker swarm join --token $TOKEN 172.18.0.1:2377`
Review the swarm with `docker node ls` it is fully functional.
Now restart with `docker-machine restart default`.

**Describe the results you received:**
Try to issue `docker node ls` you get an error:
`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded`
Look at the container logs of m2 or m3, it repeats this sort of log entry over and over:
```
time="2017-06-21T14:31:05.523308162Z" level=error msg="agent: session failed" error="session initiation timed out" module="node/agent" node.id=kxw2l1gxugzl3bvp17v9suh5z
time="2017-06-21T14:31:06.187988018Z" level=error msg="received message intended for raft_id 3abe0b6995cafc8f" from=3abac9c5aae60ee9 method="(*Node).ProcessRaftMessage" raft_id=797a2c17e4b1b031
time="2017-06-21T14:31:07.489332113Z" level=info msg="797a2c17e4b1b031 is starting a new election at term 118" module=raft node.id=kxw2l1gxugzl3bvp17v9suh5z
time="2017-06-21T14:31:07.489399342Z" level=info msg="797a2c17e4b1b031 became candidate at term 119" module=raft node.id=kxw2l1gxugzl3bvp17v9suh5z
time="2017-06-21T14:31:07.489418626Z" level=info msg="797a2c17e4b1b031 received MsgVoteResp from 797a2c17e4b1b031 at term 119" module=raft node.id=kxw2l1gxugzl3bvp17v9suh5z
time="2017-06-21T14:31:07.489436788Z" level=info msg="797a2c17e4b1b031 [logterm: 3, index: 26] sent MsgVote request to 3abac9c5aae60ee9 at term 119" module=raft node.id=kxw2l1gxugzl3bvp17v9suh5z
time="2017-06-21T14:31:07.489453833Z" level=info msg="797a2c17e4b1b031 [logterm: 3, index: 26] sent MsgVote request to 3abe0b6995cafc8f at term 119" module=raft node.id=kxw2l1gxugzl3bvp17v9suh5z
```

**Describe the results you expected:**
Swarm is still functional after reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**
On another occasion, m3 shows the "Ready" state but m2 remained "Down".

**Output of `docker version`:**

```
docker@default:~$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
docker@default:~$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: pending
 NodeID: qj40bf1f9fmtneb5cs9va11cc
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 Node Address: 172.18.0.1
 Manager Addresses:
  172.18.0.1:2377
  172.18.0.2:2377
  172.18.0.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.66-boot2docker
Operating System: Boot2Docker 17.05.0-ce (TCL 7.2); HEAD : 5ed2840 - Fri May  5 21:04:09 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: default
ID: KVVL:UHKF:CI7I:BAUT:WEH5:X5TS:MSVE:EPB4:NAIZ:SMNE:KPBB:XLMN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 57
 Goroutines: 109
 System Time: 2017-06-21T14:34:47.674510094Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
As described above, the 'default' VM from Docker Toolbox.
I am not so concerned about whether Swarm works robustly with dind but that this failure may indicate some general problem related to timing or something that could affect any Swarm.

**Comment by cpuguy83** [comment]
This seems like it's working as expected.
When you reboot, you are taking down all managers as such quorum is lost.

Ping @aaronlehmann in case I'm off here.

**Comment by aaronlehmann** [comment]
I would expect the cluster to become operable again after the nodes reboot.

Do the VMs have dynamic IP addresses? If rebooting changes the IP, it would make the managers unable to find each other after the reboot.

**Comment by cpuguy83** [comment]
This is one VM running swarm in a container. So it's also not guaranteed to get the previous IP address again once the container is restarted.

**Comment by drnybble** [comment]
Bingo! Seems that the containers on the 'swarmnet' network must swap IPs on reboot. I changed them to have a fixed IP using the --ip parameter to docker run and all is good. Note that the VM is the gateway for the 'swarmnet' network so it always has 172.18.0.1. Closing.......
