### ISSUE TITLE
Docker f. Windows 17.03.1-ce ignores Registry Mirrors setting

### ISSUE THREAD

**Issue by stefan-schilling** [moby/moby#33766]
**Description**
We have a company private Docker Repo (Nexus3), which shall act as a local Docker cache (+ company internal Docker images repo).
It works smoothly using
docker pull maven-repository3.company:5000/wasa-epa:6.4.11

Now, I don't want people to always type in the repository address, since it is error prone compared to set it up once.
Therefore, I added a "registry-mirrors" and "insecure-registries" (it uses a self-signed certificate) configuration option using Docker - Settings - Daemon.
Sadly, I get the following output:

C:\Users\stsc>docker pull wasa-eap:6.4.11-0
Error response from daemon: repository wasa-eap not found: does not exist or no pull access

C:\Users\stsc>

I have not been able to convince Docker of printing the URLs being used.

**Steps to reproduce the issue:**
1. ensure, pulling from private repository works using docker pull COMPANY_REPO/image
2. add registry-mirrors setting using Docker - Settings - Daemon (add insecure-registries setting, if need due to a self-signed certificate)
3. try to pull another image from the same private repository using docker pull image

**Describe the results you received:**
Image cannot be pulled from private repository when omiting the private repository's url

**Describe the results you expected:**
1. Image is pulled from the private repository since the private repository's url is provided as a registry-mirror
2. docker provides the URLs used for pulling (requires providing --verbose flag - I know, this is a different story)

**Additional information you deem important (e.g. issue happens only occasionally):**
not at the moment

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 242
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 168
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.837 GiB
Name: moby
ID: OKZB:JBCD:BX55:D3LZ:Q4KT:CYSU:OGSA:7N5Q:YRS3:JI5C:UT7C:GKY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-06-21T09:40:07.6902799Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 maven-repository3.company:5000
 127.0.0.0/8
Registry Mirrors:
 maven-repository3.company
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker runs on a German-speaking Windows 10 pro, installed on the machines hardware (no VM).

**Comment by friism** [comment]
Thanks for reporting!

Could I ask you to please open an issue on the Docker for Windows issue tracker? https://github.com/docker/for-win/issues

**Comment by stefan-schilling** [comment]
Opened Docker for Windows issue [#842](https://github.com/docker/for-win/issues/842).

**Comment by thaJeztah** [comment]
Thanks for reporting! Let me close the issue here, in favour of https://github.com/docker/for-win/issues/842
