### ISSUE TITLE
Docker: cannot comunicate outside when run container with --net=none and configure net manually

### ISSUE THREAD

**Issue by diegoluo** [moby/moby#33765]
## Brief desc
I started a container with --net=none, and configured its network manually.
!!! It cannot communicate outside the host but ping works.
The following lists the operations and issue step by step,

## IP addresses of the environment
Gateway:     10.90.241.1    (there is no GW for 172.16.3.* network)
Host:           10.90.241.202     172.16.3.202
Container:   10.90.241.203     172.16.3.203

## Command to run the container
[root@localhost ~]# docker run --privileged --name DCPA -it --net=none -v /home/diego/docker-vcc-workdir/vcc-dc-pa/vcc-dc-pa-log:/vcc/log arris/emp/vcc:vtest3

#### configure eth0 of the container
[root@localhost ~]# sudo brctl addbr br0
[root@localhost ~]# sudo ip link set br0 up
[root@localhost ~]# sudo ip addr add 10.90.241.202/24 dev br0; \
> sudo ip addr del 10.90.241.202/24 dev enp1s0f0; \
> sudo brctl addif br0 enp1s0f0; \
> sudo ip route del default; \
> sudo ip route add default via 10.90.241.1 dev br0
[root@localhost ~]# pid=$(sudo docker inspect --format '{{ .State.Pid }}' DCPA)
[root@localhost ~]# sudo mkdir -p /var/run/netns
[root@localhost ~]# sudo ln -s /proc/$pid/ns/net /var/run/netns/$pid
[root@localhost ~]# sudo ip link add veth-a0 type veth peer name veth-b0
[root@localhost ~]# sudo brctl addif br0 veth-a0
[root@localhost ~]# sudo ip link set veth-a0 up
[root@localhost ~]# sudo ip link set veth-b0 netns $pid
[root@localhost ~]# sudo ip netns exec $pid ip link set dev veth-b0 name eth0
[root@localhost ~]# sudo ip netns exec $pid ip link set eth0 up
[root@localhost ~]# sudo ip netns exec $pid ip addr add 10.90.241.203/24 dev eth0
[root@localhost ~]# sudo ip netns exec $pid ip route add default via 10.90.241.1

#### configure eth1 of the container
[root@localhost ~]# sudo brctl addbr br1
[root@localhost ~]# sudo ip link set br1 up
[root@localhost ~]# sudo ip addr add 172.16.3.202/24 dev br1; \
> sudo ip addr del 172.16.3.202/24 dev enp1s0f1; \
> sudo brctl addif br1 enp1s0f1
[root@localhost ~]# pid=$(sudo docker inspect --format '{{ .State.Pid }}' DCPA)
[root@localhost ~]# sudo ip link add veth-a1 type veth peer name veth-b1
[root@localhost ~]# sudo brctl addif br1 veth-a1
[root@localhost ~]# sudo ip link set veth-a1 up
[root@localhost ~]# sudo ip link set veth-b1 netns $pid
[root@localhost ~]# sudo ip netns exec $pid ip link set dev veth-b1 name eth1
[root@localhost ~]# sudo ip netns exec $pid ip link set eth1 up
[root@localhost ~]# sudo ip netns exec $pid ip addr add 172.16.3.203/24 dev eth1

## check ip and route in the container
-sh-3.2# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
29: eth0@if30: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue qlen 1000
    link/ether 4a:78:ef:3a:51:0e brd ff:ff:ff:ff:ff:ff
    inet 10.90.241.203/24 scope global eth0
       valid_lft forever preferred_lft forever
31: eth1@if32: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue qlen 1000
    link/ether 76:1c:13:05:61:b6 brd ff:ff:ff:ff:ff:ff
    inet 172.16.3.203/24 scope global eth1
       valid_lft forever preferred_lft forever
-sh-3.2# 
-sh-3.2# ip route
default via 10.90.241.1 dev eth0 
10.90.241.0/24 dev eth0  scope link 
172.16.3.0/24 dev eth1  proto kernel  scope link  src 172.16.3.203 
-sh-3.2# 

## other operation failed including ssh
-sh-3.2# ping 10.90.241.20
PING 10.90.241.20 (10.90.241.20) 56(84) bytes of data.
64 bytes from 10.90.241.20: icmp_seq=1 ttl=64 time=0.237 ms
64 bytes from 10.90.241.20: icmp_seq=2 ttl=64 time=0.222 ms
^C
--- 10.90.241.20 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.222/0.229/0.237/0.016 ms
-sh-3.2# 
-sh-3.2# ssh 10.90.241.20    
ssh: connect to host 10.90.241.20 port 22: No route to host
-sh-3.2# 
-sh-3.2# ssh 10.90.241.202
root@10.90.241.202's password: 

## issue desc
It seems that configured eth0 and eth1 manually successfully to the container. But the container's route doesn't work.
Can you help on it?
Appreciated.

**Comment by cpuguy83** [comment]
Since this doesn't look like an actual docker issue I'm going to close.
Please use forums.docker.com or the community slack for troubleshooting issues like this.

Thanks.

btw, did you make sure to enable ipv4 forwarding and the neccessary masquerading and forward rules to iptables?
