### ISSUE TITLE
Can't set `--dns` if using `--network`

### ISSUE THREAD

**Issue by monokal** [moby/moby#33777]
**Description**
When running a container, `--dns` is overridden in favour of Docker's own DNS server (127.0.0.11) if using the `--network` argument.

**Steps to reproduce the issue:**
```
docker run --rm -ti --privileged --dns 172.15.140.101 --dns 172.15.140.100 --network=kitchen_push centos:centos7 cat /etc/resolv.conf
```

**Describe the results you received:**
```
search ...omitted...
nameserver 127.0.0.11
options ndots:0
```

**Describe the results you expected:**
```
search ...omitted...
nameserver 172.15.140.101
nameserver 172.15.140.100
```

**Output of `docker version`:**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: FBMX:PT24:VMCH:Q5YL:KYWX:J54T:BKAS:DKJX:LVHY:MABF:3UJL:WRKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 36
 System Time: 2017-06-22T07:27:26.703723875Z
 EventsListeners: 1
Username: monokal
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac.

# Reason it's required
The reason I need to set custom nameservers while connected to a Docker network is because I'm testing Chef cookbooks, one of which overwrites the `/etc/resolv.conf` file. I need Docker to enforce that `127.0.0.11` and an additional internal nameserver are used. So in this case, I'd want to be able to...
```
docker run --rm -ti --privileged --dns 127.0.0.11 --dns 172.15.140.100 --network=kitchen_push centos:centos7 /bin/bash
```
...so I can resolve other containers on the `kitchen_push` network, and resolve outside addresses.

**Comment by cpuguy83** [comment]
Did you test that the expected DNS name is actually not available?

**Comment by monokal** [comment]
Yup, I suspected that Docker may be doing some magic and using 127.0.0.11 then adding my alternative nameservers and recursors in the backend, but it doesn't seem to be the case.

**Comment by monokal** [comment]
Closing as it was an issue with the 60211 > 53 NAT rule being missing.
