### ISSUE TITLE
Package docker-engine missing in Debian Stretch/Jessie sources aarch64(arm64)

### ISSUE THREAD

**Issue by gdeverlant** [moby/moby#33783]
Impossible to install docker-engine from apt-get in Jessie/Stretch.

**Comment by thaJeztah** [comment]
Correct there are no aarch64 packages yet, this is still being worked on, and may arrive at some point.

I'm closing this issue because this is expected, but feel free to continue the conversation

**Comment by douglasmiranda** [comment]
@gdeverlant It's no so hard to make deb for jessie aarch, try: https://github.com/docker/docker-ce-packaging/pull/35#issuecomment-318973778
