### ISSUE TITLE
Docker overlay network connectivity issue because of incorrect fdb entries..

### ISSUE THREAD

**Issue by sanimej** [moby/moby#33789]
In swarm mode overlay network events are sent between cluster nodes using gossip protocol.

When scaling services up and down or deploy/rm of multiple services tasks can move around between nodes. When a task gets scheduled on a node it could be using an IP of as task that just went down on a remote node. So the add event gets processed before the earlier delete event. When the delete event does arrive, since the current mapping for the task IP has changed the cleanup is not happening correctly and leading to connectivity issues in overlay network.

This is more likely to happen in AWS or other cloud infra because of the longer gossip propagation delay in such deployments.

**Comment by thaJeztah** [comment]
ping @fcrisciani @abhi

**Comment by abhi** [comment]
@thaJeztah this should be fixed now

**Comment by thaJeztah** [comment]
@abhi thanks! Let me close
