### ISSUE TITLE
Strange terminal behaviour inside docker

### ISSUE THREAD

**Issue by cromat** [moby/moby#33794]
When I exec to /bin/bash inside docker (docker exec -ti container /bin/bash) and search recursive for a command, sometimes terminal starts to behave strange and everything messes up like in picture.
After that I have to exit from container and exec in again.
![selection_017](https://user-images.githubusercontent.com/3780307/27479588-cb3eb540-5814-11e7-8b19-301644edc2fc.png)

**Comment by nodakai** [comment]
Ctrl-P/Ctrl-N behave strangely in my case and it's annoying to navigate through the shell history. It's possible that we are troubled by the same issue.

**Comment by cromat** [comment]
I have also noticed that navigating through history with up key sometimes reproduces this behaviour.

**Comment by jjlin** [comment]
I frequently have terminal issues that seem to come down to Docker not figuring out what the right terminal size is initially. This seems to happen only on a fresh terminal. (This may or may not be what's causing your issue.) For example:

```bash
$ docker exec -it foo /bin/bash
foo@649fb21d747c:~$ stty size
0 0
foo@649fb21d747c:~$ reset -w
foo@649fb21d747c:~$ stty size
24 80
foo@649fb21d747c:~$ # Now resize the terminal to get a SIGWINCH.
foo@649fb21d747c:~$ stty size
69 208
foo@649fb21d747c:~$ exit
exit
$ docker exec -it foo /bin/bash # Try it again.
foo@649fb21d747c:~$ stty size
69 208
foo@649fb21d747c:~$ # Doesn't happen anymore for this session.
```

**Comment by cromat** [comment]
I have found out that this bug is due to terminal width and height parameters which sometimes is not provided to container with docker exec command

You can read more about it in this issue: #10341 

I have resolved this bug this way: docker exec -it container_name /bin/bash -c "export COLUMNS=`tput cols`; export LINES=`tput lines`; exec bash"

You can also put this command in a script and provide container name as parameter and create alias like docker-exec

**Comment by PhilT** [comment]
Thanks @cromat! This solved an issue I was having using Docker for Windows in Bash on Windows where the output wasn't wide enough due to it not having a proper TTY. It looks like your backticks got formatted into code so here is the line again:

    docker exec -t container_name /bin/bash -c "export COLUMNS=`tput cols`; export LINES=`tput lines`; exec bash"

**Comment by iamsoorena** [comment]
for anyone coming here looking for an answer, you can find it [here](https://stackoverflow.com/a/49281526/5284370)

**Comment by borisdev** [comment]
Thanks @PhilT. 

This is what worked for me.

`docker exec -it  container_name sh -c "stty rows 50 && stty cols 150 && bash"`

**Comment by ricardordb** [comment]
Thanks! That solved mine too!

**Comment by Yugloocamai** [comment]
After trying a dozen solutions @PhilT 's was the only one that worked

**Comment by eigood** [comment]
```shelldocker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -ti localdev_control_1 bash`

**Comment by gitgaatachal** [comment]
@eigood's solution worked like charm at the first try...

**Comment by tzaspy** [comment]
I use ubuntu with gnome. Usually I resize the window and the issue is resolved itself.
Resizing in gnome is `Ctrl+Super+(Down Arrow)` and then `Ctrl+Super+(Up Arrow)`

**Comment by N4M3Z** [comment]
@eigood Thank you for the correct solution. Why doesn't Docker just do this?

**Comment by stephaneeybert** [comment]
@PhilT @cromat In my case I do need the `-i` option as in `-it` instead of just the `-t` option.

**Comment by romulo1984** [comment]
I created an alias to make my life easier.
```shell
alias dexec='docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -ti $1'
```
Eg.:
```shell
dexec containername_service_1 bash
```

**Comment by thaJeztah** [comment]
@romulo1984 what version of docker are you running? this should be fixed in the current version

**Comment by romulo1984** [comment]
@thaJeztah `17.12.0-ce`

**Comment by romulo1984** [comment]
@thaJeztah thanks.

**Comment by fkoester** [comment]
I can confirm this issue is resolved with Docker 18.06.

**Comment by Grazfather** [comment]
@nodakai I have the same issue as you: I don't have issues with width or anything, but Docker something won't redraw. Specifically, if I use ctrl-p and ctrl-n to scroll through bash history (which is my habit) it doesn't redraw. If I use the arrow keys, it does.

Did you manage to find a way around this issue?

**Comment by wasosa** [comment]
@Grazfather I think that's a different issue. I think the issue there is that the key sequence to detach from a container is `C-p C-q`, so docker sees your `C-p` and is waiting for the `C-q` in order to detach. I haven't actually tried, but it could be that using `--detach-keys=` could help.

**Comment by dramzy** [comment]
> for anyone coming here looking for an answer, you can find it [here on stackoverflow](https://stackoverflow.com/a/49281526/5284370)

The answer linked to here is the best solution imo because other solutions don't work when you switch users inside the container assuming you want the new user's environment which will wipe out the LINES and COLUMNS environment variables.

**Comment by gaopeiliang** [comment]
I use xshell exec in docker ..

![image](https://user-images.githubusercontent.com/11383058/50536132-207e8400-0b8c-11e9-837b-818fe832c898.png)

when I resize the xshell window ...
![image](https://user-images.githubusercontent.com/11383058/50536146-4c016e80-0b8c-11e9-8486-a67ced41d771.png)

exec tty size reset correctly ...  anyone know this why , and how xshell do it ...  I worked at lower docker version

![image](https://user-images.githubusercontent.com/11383058/50536166-810dc100-0b8c-11e9-9053-0842beb0bcf5.png)

**Comment by frops** [comment]
Docker-compose example to solve this problem:
```
version: '3'
services:
    php:
        container_name: cmg-php
        hostname: "docker-stand"
        build:
            context: ./
        environment:
            - COLUMNS=`tput cols`
            - LINES=`tput lines`
```

Focus on environment. @cromat thanks!

**Comment by thaJeztah** [comment]
Should definitely be improved in 18.06 and up, but there are still some cases where the resize may need to be retriggered (you can do so by resizing your terminal window); there's a pull request that adds a retry-loop for those cases, but it's not merged yet; https://github.com/docker/cli/pull/1529

I'd consider setting `COLUMNS` and `LINES` a workaround for some situations, but not something to keep in your environment

**Comment by mviereck** [comment]
I found the bug is still present if running with `--tty` and without `--interactive`.
Example to reproduce:
```
FROM debian
RUN apt-get update
RUN apt-get install sl
CMD /usr/games/sl
```
Command with broken output / wrong terminal size:
`docker run --rm --tty slimage`

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/1529 is not yet in `Docker 18.09

**Comment by nidash** [comment]
expected to be fixed in 19.03.0 (10th July 2019)

**Comment by thaJeztah** [comment]
It was back ported to Docker CLI 18.09.5 through https://github.com/docker/cli/pull/1775

**Comment by moralrebuild** [comment]
still presents in the latest Mac OS when compile openwrt with command: 
  make menuconfig
```
docker version

	Client: Docker Engine - Community
	 Version:           19.03.1
	 API version:       1.40
	 Go version:        go1.12.5
	 Git commit:        74b1e89
	 Built:             Thu Jul 25 21:18:17 2019
	 OS/Arch:           darwin/amd64
	 Experimental:      false

	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.1
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.12.5
	  Git commit:       74b1e89
	  Built:            Thu Jul 25 21:17:52 2019
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          v1.2.6
	  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
	 runc:
	  Version:          1.0.0-rc8
	  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683
docker version

	Client: Docker Engine - Community
	 Version:           19.03.1
	 API version:       1.40
	 Go version:        go1.12.5
	 Git commit:        74b1e89
	 Built:             Thu Jul 25 21:18:17 2019
	 OS/Arch:           darwin/amd64
	 Experimental:      false

	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.1
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.12.5
	  Git commit:       74b1e89
	  Built:            Thu Jul 25 21:17:52 2019
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          v1.2.6
	  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
	 runc:
	  Version:          1.0.0-rc8
	  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683
```

**Comment by aminnairi** [comment]
I made myself a portable VIM configuration with all my fancy plugins for style and linting/fixing. Until I came up with @cromat solution I always had layout issues with VIM + NERDTree. Now it works well. Just made myself an alias (function, I like functions but same thing here).

```console
$ vi ~/.zshrc
```

```zsh

function vim {
    docker run --env LINES=$(tput lines) --env COLUMNS=$(tput cols) # ... 
}
```

**Comment by acataluddi** [comment]
If the detection of the windows size fails in a BASH script and you're getting the default `80` columns, try the following:

```bash
docker exec -e COLUMNS="$(stty size | awk '{print $2}')" -e LINES="$(stty size | awk '{print $1}')" \
       -it container //bin/bash
```

Regards,
Adriano C.
