### ISSUE TITLE
Docker for mac freezes at startup on mac os 10.13

### ISSUE THREAD

**Issue by StoneGod** [moby/moby#33791]
**Description**

Docker for mac freezes at startup on mac os 10.13
 
mac os 10.13 (17A291j) (beta 2)

**Steps to reproduce the issue:**
1. Download last version docker for mac 
2. Run app
3. Then it's freezes

**Comment by unclejack** [comment]
Please open an issue on this repository: https://github.com/docker/for-mac

I'll close this now since it's not something which can be addressed in this repository's code.
