### ISSUE TITLE
Cannot reference multi-arch tag for arm architecture on Windows running Linux Containers

### ISSUE THREAD

**Issue by MichaelSimons** [moby/moby#33797]
**Description**

I am using the multi-arch feature in order to have a common tag between windows 64, linux 64, and arm 32.  On Windows running Docker in Linux containers mode, I cannot figure out how to target the arm 32 image via the multi-arch tag.

**Details:**
I have the following multi-arch tag

```
root@7148be09e0f4:/repo# manifest-tool inspect msimons/dotnet-nightly:2.0-runtime
Name:   msimons/dotnet-nightly:2.0-runtime (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:8e3458f372e925742a9ace17d3c3bd37356faca88914926c903e886e7dc95890
 * Contains 3 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:42cb2263de1ecb56352e9a9d9142ed8636241e059e93b08476c0f1a226e187cb
1  Mfst Length: 1163
1     Platform:
1           -      OS: linux
1           - OS Vers:
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant:
1           - Feature:
1     # Layers: 4
         layer 1: digest = sha256:c75480ad9aafadef6c7faf829ede40cf2fa990c9308d6cd354d53041b01a7cda
         layer 2: digest = sha256:979e4502ccd2dc4e103a6a52764fb1c475aff4e583fb72516c8ee3cdf296d412
         layer 3: digest = sha256:5c5be0b27440ca9e66a4105a7d9984e8dd6e472f02e4e963b0ae9c27b618b3f9
         layer 4: digest = sha256:8ce80331c1131c53ccd1e54be219899e05d559386e1bdcd40206f016b46ae56b

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:3bb42660bdc3730d229ad37d3e92d9385a295e149fed94e630e5e3f282a01aa1
2  Mfst Length: 1163
2     Platform:
2           -      OS: linux
2           - OS Vers:
2           - OS Feat: []
2           -    Arch: arm
2           - Variant: armv7
2           - Feature:
2     # Layers: 4
         layer 1: digest = sha256:60a2bd54ee143ba98d83bab0a23ff51ddd2b916d4a162c42d99166a213ebfff8
         layer 2: digest = sha256:fa256dbbce76e2523fd5cea11aba9d21d9f85f5862d3d9d51a8b073fca7c30ce
         layer 3: digest = sha256:03f6c65c8eec2861b6d7d6a13c8dbcd3963777ce38ebe003acbb8f06ab81656c
         layer 4: digest = sha256:2a8ef2ae9713cdb19fa6244a1da0ed23f69e74172989671a8c3c5a1730a417be

3    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
3       Digest: sha256:2721aaae8943ce48a59e1a561f0e1b13c79a0b5cd31d905f11de0a15e5865a45
3  Mfst Length: 2193
3     Platform:
3           -      OS: windows
3           - OS Vers: 10.0.14393.1358
3           - OS Feat: []
3           -    Arch: amd64
3           - Variant:
3           - Feature:
3     # Layers: 8
         layer 1: digest = sha256:bce2fbc256ea437a87dadac2f69aabd25bed4f56255549090056c1131fad0277
         layer 2: digest = sha256:6330793656b1565cd8b5d5c1e2a736a351dec39f7250daf31eb91e3a76cc872b
         layer 3: digest = sha256:08a6f342df3b1f66578843f5a8e650b080904454d8d799d52ee02e110e39567c
         layer 4: digest = sha256:31470bd606079a505932b98af38b5ffebb095fa41dddd479320b76c416a2e468
         layer 5: digest = sha256:c5662c5e7543e41212882329a8cefcaf935dba28b62eb2d9b0b71fac5305ff3f
         layer 6: digest = sha256:ad5db39ddd52f9b41ea632ebf7a689d309673a3c096090e35e5469cf99f50c2b
         layer 7: digest = sha256:c1e1676e6d734b75150d65ab5040210662aa44ece894866be520a8a84617576a
         layer 8: digest = sha256:a1c310fae99ce6305bd64dd9916adac5201d5f27602bbea9db42e9a364b0f297
```

I would like users to be able to build a Dockerfile on Windows which is linux arm 32 specific that utilizes the multi-arch tag

```
FROM msimons/dotnet-nightly:2.0-runtime
# RUN some command/logic that is arm specific
```

When I build this on an arm device it works as expected.  However when built on Windows it picks the linux AMD 64 base image.  I would like to be able to build this Dockerfile in ARM mode.  I realize this can be done if I target the underlying ARM image but that defeats the purpose IMO of having the multi-arch tags.

Another variant of this scenario is if someone wants to `docker run` a multi-arch tag on a Windows machine but target a linux platform other than that of the host machine. 

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 157
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: TRIT:FBQM:MAFQ:XXW3:H77N:ZQFS:RMDH:YQKE:UDXO:TUBD:3GDR:XNMX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 36
 System Time: 2017-06-23T14:05:53.716269Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
Related to #33759.  This is something @richlander and I encountered while experimenting with how the [.NET Core](https://hub.docker.com/r/microsoft/dotnet/) project can support arm32v7 Docker images.

**Comment by friism** [comment]
Maybe I'm misunderstanding, but if you're asking how to build and run a 32bit ARM image in Docker for Windows, then the answer is that you cannot. When using Docker for Windows (in Linux mode), Docker will pick the x86-64 image because that's the architecture and OS family that's supported.

> Another variant of this scenario is if someone wants to docker run a multi-arch tag on a Windows machine but target a linux platform other than that of the host machine.

What is your question? Note that images are _only_ multi-arch in the registry. As soon as you do `docker pull`, the image that materializes on your host is specific to the OS and arch of that host. Docker doesn't pull the components for other architectures or OS's.

**Comment by tianon** [comment]
If you just want to reference it (regardless of whether you can actually run it on the current platform), I think referencing it by the digest of the individual image is probably the only way (`docker pull` doesn't have a way to specify architecture), which thus requires a tool such as `manifest-tool inspect` (or `docker manifest inspect` from https://github.com/docker/cli/pull/138), since the tag only references the full manifest list.

**Comment by MichaelSimons** [comment]
@friism
>Maybe I'm misunderstanding, but if you're asking how to build and run a 32bit ARM image in Docker for Windows, then the answer is that you cannot. When using Docker for Windows (in Linux mode), Docker will pick the x86-64 image because that's the architecture and OS family that's supported.

This surprises me as it appears to work today.  Is this not doing what I think it is?
```
PS F:\> docker run arm32v7/debian:stretch arch
armv7l
```

If this is supported, then the piece that seems absent is that way to specify the Docker architecture either at the command level or at the `mode` level (e.g. Linux amd64 mode vs Linux arm32 mode).  But as @tianon pointed out, there isn't a way to specify this.

**Comment by friism** [comment]
@MichaelSimons I had forgotten that Docker for Mac and Windows ships qemu and facilities for running ARM images. This is not really documented and is a vestige or early betas.

**Comment by justincormack** [comment]
It is documented see https://docs.docker.com/docker-for-mac/multi-arch/ and we intend to continue to support it while it is useful. It is easier to get hold of native hardware now that has good build performance though so we may deprecate it at some point.

I do think we may need some way to specify tag, as eg we use the same machines to build arm32 and arm64 images, and we don't really want to have to run a 32 bit Docker binary for the 32 bit builds.

**Comment by richlander** [comment]
Small note ... our next step will be arm64-based images. As @justincormack suggests, we'll want to build arm64 and arm32 on the same arm64 machine if we're unable to build on x64. We're much more likely to find arm64 and x64 machines in racks than arm32.

**Comment by thaJeztah** [comment]
I think this should be resolved now, when using the --platform flag on  various commands, you can override the default selection
