### ISSUE TITLE
Unable to update stack via compose file when secrets change

### ISSUE THREAD

**Issue by aldencolerain** [moby/moby#33808]
**Description**
When trying to re-deploy/update a stack via a compose file with secrets.  The deploy fails.

**Steps to reproduce the issue:**
1. Create a docker compose file with secrets from a file
2. Deploy
3. Change secrets
4. Redeploy

**Describe the results you received:**
Error response from daemon: rpc error: code = 3 desc = only updates to Labels are allowed

**Describe the results you expected:**
Successful update of the stack services and secrets.  If I remove and redploy the stack or remove the secrets from the compose file everything works fine.

**Additional information you deem important (e.g. issue happens only occasionally):**
compose file v3.2

**Output of `docker version`:**
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
ubuntu@ip-172-31-27-53:~/soma$ docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 11
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: y3bcyfu8txxt72j396jnyh29f
 Is Manager: true
 ClusterID: dfdk1vjnw3aesfgnyk7gryjw8
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.27.53
 Manager Addresses:
  172.31.27.53:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1013-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.303GiB
Name: ip-172-31-27-53
ID: 4OWQ:LZYO:J7K4:GG5U:4IB6:WK36:DYQT:TSOI:YB5H:4U5H:QKUA:GZVD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 Instance

**Comment by aldencolerain** [comment]
I guess because secrets are immutable this kind of makes sense whats going on.  It might be better to have a clearer error message at bare minimum, but in the long term I guess I expect it to remove those secrets, add them back, then restart containers that depend on them?  I keep wanting to use secrets for API keys etc. but they keep making things difficult.  Am I missing the use case?

**Comment by dnephin** [comment]
Error messages were improved in https://github.com/docker/cli/pull/145

Yes, secrets are immutable, so this is working as designed. I think you have to update the name of the secret when you change the file contents. A change like https://github.com/docker/cli/issues/274 would make that easier (I think). That way the internal compose file reference to the secret wouldn't need to change, but the `name:` of the secret could change when you change the data.

**Comment by starcorder** [comment]
Just out of curiosity and before I open an issue: My use case is to use LE certs as secrets which get updated every three months. I don't know a more elegant solution than to use secrets, so the certs are shared to all servers. With this restriction that secret are immutable I don't know of any other solution how to share same certs with all my servers (syncing file systems adds complexity). All servers need those certs in case they get an update request from LE.

**Comment by vguna** [comment]
I ran into this today as well. Why is this different from any other option? If I want to change a secret, it should do it. Why isn't that possible? I'm the MASTER ;)!

**Comment by Eoan242** [comment]
I'm getting this same error when making changes to a file listed in configs (I don't even use secrets)?
> Error response from daemon: rpc error: code = 3 desc = only updates to Labels are allowed

**Comment by effective-microservices** [comment]
Having the same with using configs.
It should be perfectly fine to update configs and redeploy the stack (Docker version 17.06.2-ce, build cec0b72)

**Comment by parrisvarney** [comment]
I am experiencing this same issue with configs as well (not just secrets).

Temporary workaround is to manually remove the existing stack before redeploying.  `docker stack rm {stack name}`

**Comment by aldencolerain** [comment]
Instead of removing the stack and deploying, all we do now is when we update a secret, we change secret name to reflect a new version so from say production_v1 to production_v2 in the compose file (both in the secrets section and in the service section).  But we still mount it to the same file as before, so its actually not a big deal.  When we update the secret, we just update the compose file to reflect the new version, its actually ended up being helpful on occasion.

**Comment by jamiejackson** [comment]
@aldencolerain could you show a simple before and after compose snippet? I'm not clear on the workaround you're describing.

**Comment by hackel** [comment]
Wouldn't you just update the name key?  e.g.
```yml
secrets:
  redis_secret:
    name: redis_secret_v1
    file: ./my_secret.txt
```
Unfortunately this becomes a real pain when compose files are checked into version control.  Another problem with this is that the stack name no longer gets prepended to the secret name, which means you can't use the same compose file for different environments (with different secrets for each environment) without more trickery.  I still feel like I must be missing a big piece of this puzzle.

**Comment by Jitsusama** [comment]
Yeah @hackel; that's why I end up resorting to changing the name of the secret key itself both at the definition site and the usage site. It's a pain, but at least my configuration is portable.

It would be nice if the immutability of a secret/config was maintained by a version flag combined with its name, or by a hash of its content. That way the user experience would be improved, while still maintaining the old copies for easy back-tracking if you need to roll back changes.

**Comment by jamiejackson** [comment]
https://github.com/moby/moby/issues/29882
