### ISSUE TITLE
Multiple syslog-address for syslog logging

### ISSUE THREAD

**Issue by hostingnuggets** [moby/moby#33819]
Hello,

I would have a feature request for docker which would be to have the possibility for the syslog logging driver to log to more than one syslog server for a docker container. Ideally I would run the container like that:

```docker run --log-driver syslog --log-opt syslog-address=udp://1.2.3.4:514 --log-opt syslog-address=udp://5.6.7.8:514 alpine echo hello world```

As you can see I would be logging here to 2 different syslog servers at the same time using twice the `syslog-address` log option.

Cheers

**Comment by cpuguy83** [comment]
I do not think this is something we should support.
This can be accomplished by proxying the syslog messages to multiple backends.

**Comment by thaJeztah** [comment]
I agree, this feels feature-creepy, and could be resolved with external solutions as mentioned.

I'll go ahead and close this issue for now, but feel free to continue the conversation
