### ISSUE TITLE
Security issues of Docker for Windows

### ISSUE THREAD

**Issue by xmjiao** [moby/moby#33817]
**Description**
I found that `Docker on Windows` by default saves the images and data volumes in a shared public folder `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx`. This is a major security hole because all the images and data of a user can be accessed and modified by other Docker users on the same Windows computer without realizing it. 

I would strongly recommend changing the default location for the `Image and Volume VHD Location` to a private folder `C:\Users\UserName\Documents\Hyper-V\Virtual Hard Disks`.

**Steps to reproduce the issue:**

1. Install Docker CE for Windows
2. Create Docker images and data volumes in one user account.
3. Log out and log in another user account. You can then start Docker with the images and data volume of the other user.

**Describe the results you received:**
One user can see and change the data of another user. This is a security hole. By default, the images and data volumes (especially the data volumes) should be protected.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.915 GiB
Name: moby
ID: PCQ4:4ZGT:LK5A:JLLK:DSFT:LUJH:E34P:DPGO:7HVG:AIWV:LDZ2:5T7B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 23
 System Time: 2017-06-24T23:45:32.4006914Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by AkihiroSuda** [comment]
Please report the issue to https://github.com/docker/for-win ?

Let me close this, because this is not an issue of Moby

**Comment by friism** [comment]
@xmjiao This is the default location of hyper-v images on Windows. Also note that the Docker install is global to the machine. This is the same behavior as when `dockerd` is running natively on Windows.
