### ISSUE TITLE
[Docker multistage] Docker multistage copy doesn't wait for npm build frontend

### ISSUE THREAD

**Issue by vazham** [moby/moby#33825]
**Description**
Docker multistage copy doesn't wait for npm(or yarn) build frontend.

I'm using Docker multistage for building frontend(Angular 4 + Webpack).
My project looks like [this project](https://github.com/AngularClass/angular-starter).
This is my [Dockerfile](https://gist.github.com/vazham/4e4e7d9db450d83673a7f09f5f9c3e0c) to do it.
On Docker 17.05 all worked good. On current Docker version(17.06.0-ce-rc5-win16 (12604)) this file fails on last `COPY` row. Looks like Docker don't wait for result of `CMD yarn build:dev` and tries to copy unpresented folder.

**Steps to reproduce the issue:**
1. `git clone git@github.com:AngularClass/angular-starter.git`
2. Copy `Dockerfile` from https://gist.github.com/vazham/4e4e7d9db450d83673a7f09f5f9c3e0c
3. Run `docker build -t frontend:dev .`
4. Get error

**Describe the results you received:**
```COPY failed: stat /var/lib/docker/overlay2/efbf924157e82a817ef24a15934bca087dd409f3ac15c8c3f0b6ad9d8a28231c/merged/tmp/src/app/dist: no such file or directory```

**Describe the results you expected:**
Successful copying files and run nginx container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:13:29 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce-rc5
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:18:21 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 49
 System Time: 2017-06-26T14:46:19.3744653Z
 EventsListeners: 0
Http Proxy: remote-proxy:8080
Https Proxy: remote-proxy:8080
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Windows 10 x64

**Comment by vdemeester** [comment]
@vazham `CMD` is not run during build, it just sets the command to run when starting a container from this image. See https://docs.docker.com/engine/reference/builder/#cmd

**Comment by vazham** [comment]
@vdemeester How then i can something like `COPY --from=buildContainer /tmp/src/app/dist/ /usr/share/nginx/html` to run it when start container image? I didn't find any other commands co copy folder that supports docker multistage path that has params like `--from=buildContainer`.

**Comment by y3ti** [comment]
@vazham I think that your `Dockerfile` should looks like this:

```
# Serve the app
RUN yarn build:dev

# Builds a Docker to deliver dist/
FROM nginx:alpine
COPY --from=buildContainer /tmp/src/app/dist/ /usr/share/nginx/html
```

`CMD` is not run during build process as @vdemeester wrote.

**Comment by thaJeztah** [comment]
Yes, I don't see a bug here; looks like a misunderstanding of the Dockerfile commands; I'm closing this issue, but feel free to continue the conversation
