### ISSUE TITLE
Enable DCT by default options

### ISSUE THREAD

**Issue by gambol99** [moby/moby#33833]
It isn't immediately clear how to enabled DCT on a host, the only solution to enable appears to be via the command line option --disable-content-trust or the environment variable DOCKER_CONTENT_TRUST, is there no way of informing the docker daemon to enable trusted images only and to use an on-premise notary server on https://some_url

**Comment by AkihiroSuda** [comment]
duplicate: https://github.com/moby/moby/issues/19128
