### ISSUE TITLE
One container deadlock caused docker command hang

### ISSUE THREAD

**Issue by gyliu513** [moby/moby#33870]
**Description**

**Steps to reproduce the issue:**
1.  Start two containers on host
2. One container deadlocked
3. Use `docker stop` to stop the deadlocked container
4. The deadlock container cannot be stopped
5. `docker ps`, `docker images`, `docker events` hang
6. `docker inspect <cid>` works for another container but hang for the deadlock container
7. `docker logs <cid>` also works for another container but hang for the deadlock container

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

![image](https://user-images.githubusercontent.com/4461983/27668995-ea2afaf8-5cb6-11e7-9474-a0f3bd3caeae.png)

**Output of `docker info`:**

```
hang, and no output
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
![image](https://user-images.githubusercontent.com/4461983/27669011-0255ce1e-5cb7-11e7-94cf-42269e983505.png)

**Comment by gyliu513** [comment]
I think that the deadlock container should not impact other containers, there should be some options can enable me filter out the problematic containers and make the API call works.

**Comment by ripcurld0** [comment]
@gyliu513 this is a very old version of Docker.
Can you reproduce it on a newer version such as `17.03`?

**Comment by thaJeztah** [comment]
Yes, docker 1.6.2 is [over 2,5 years old](https://github.com/moby/moby/releases/tag/v1.6.2) and no longer maintained. Lots of improvements have been made since, and additional improvements have been made in the engine (https://github.com/moby/moby/pull/31273) that will be included in docker 17.07 

Given that we no longer maintain that version, I'm closing this issue, but feel free to continue the conversation

**Comment by gyliu513** [comment]
Thanks @thaJeztah and @ripcurld0 , the problem of https://github.com/moby/moby/issues/28183 is exactly what I'm struggling. OK, will try to upgrade docker.
