### ISSUE TITLE
17.06 Changelogs

### ISSUE THREAD

**Issue by Silex** [moby/moby#33874]
I cannot see a 17.06 version at https://github.com/moby/moby/releases nor in https://github.com/moby/moby/blob/master/CHANGELOG.md

Where has this information gone now?

**Comment by llitfkitfk** [comment]
https://docs.docker.com/release-notes/docker-ce/#17060-ce-2017-06-28

**Comment by sandersaares** [comment]
I will reuse this issue in a "Where have the releases gone" context to add to the topic. Namely, I used to use the Releases for getting the binaries (docker.exe and such). If there are no more releases, where can the raw binaries now be obtained from? (I just want the zip and exe files, no installers or anything like that)

**Comment by vdemeester** [comment]
@sandersaares `docker` releases now happens in `docker/docker-ce` repository : https://github.com/docker/docker-ce/releases. 
/cc @andrewhsu @tiborvass @thaJeztah for the link to binaries (zip & co) but I think it's here : https://download.docker.com/

**Comment by Silex** [comment]
Alright, thanks :+1:
