### ISSUE TITLE
cloudstor.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by eon01** [moby/moby#33879]
**Description**

```
Error response from daemon: dial unix /run/docker/plugins/a282bb25c0b93b58f42777da69924a5709b7a16ec633440e1544d90775c742d8/cloudstor.sock: connect: no such file or directory
```

**Steps to reproduce the issue:**
After installing cloudstor plugin (in a swarm manager):

```
docker plugin install --grant-all-permissions docker4x/cloudstor:aws-v1.13.1-beta18 CLOUD_PLATFORM=AWS EFS_ID_REGULAR=fs-fe0bcxxx  DEBUG=1
```

I wanted to activate it:

```
docker plugin enable docker4x/cloudstor:aws-v1.13.1-beta18
``` 

I've got this error:

```
Error response from daemon: dial unix /run/docker/plugins/a282bb25c0b93b58f42777da69924a5709b7a16ec633440e1544d90775c742d8/cloudstor.sock: connect: no such file or directory
```

**Describe the results you received:**

```
ID                  NAME                                    DESCRIPTION                       ENABLED
a282bb25c0b9        docker4x/cloudstor:aws-v1.13.1-beta18   cloud storage plugin for Docker   false
```

**Describe the results you expected:**

```
ID                  NAME                                    DESCRIPTION                       ENABLED
a282bb25c0b9        docker4x/cloudstor:aws-v1.13.1-beta18   cloud storage plugin for Docker   true
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: g5du2ax8bs10co68lekxonjxf
 Is Manager: true
 ClusterID: k1g5bzhvd0p0334ivcjicnt2f
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.59.219
 Manager Addresses:
  10.0.59.219:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1020-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-10-0-59-219
ID: K5KO:D6H7:WCWG:N2M5:AEM7:YVCB:DHSP:5WKL:4BC5:Z2CG:IVUH:YHQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using a single AWS EC2 small instance to create a manager (for testing purposes).

**Comment by ddebroy** [comment]
@eon01 The tag you used is rather old. Can you please try `17.06.0-ce-aws1` instead of `aws-v1.13.1-beta18`? The CLI needs to be:

```docker plugin install --alias cloudstor:aws --grant-all-permissions docker4x/cloudstor:17.06.0-ce-aws1 CLOUD_PLATFORM=AWS EFS_ID_REGULAR=$EFS_ID_REGULAR EFS_ID_MAXIO=$EFS_ID_MAXIO AWS_REGION=$AWS_REGION AWS_STACK_ID=$STACK_ID DEBUG=1```

$STACK_ID is typically a MD5 hash of the CloudFormation stack ID set up by AWS but it can be any common string used by all nodes of the swarm. eg `myswarm5`. $AWS_REGION needs to be set to the region you are testing on. eg `us-west-2`. You also need to make sure all necessary IAM permissions are available to the node for EBS volume manipulations (if you are interested in EBS backed volumes). These include:  "ec2:CreateTags", "ec2:AttachVolume", "ec2:DetachVolume", "ec2:CreateVolume", "ec2:DeleteVolume", "ec2:DescribeVolumes", "ec2:DescribeVolumeStatus", "ec2:CreateSnapshot", "ec2:DeleteSnapshot", "ec2:DescribeSnapshots".

**Comment by thaJeztah** [comment]
ping @eon01 is this still an issue with the hints @ddebroy gave above?

**Comment by RehanSaeed** [comment]
I also recieve this error from the cloudstor plugin when trying to enable it. Not sure if this is a moby issue or a Cloudstor issue. I've raised https://github.com/docker/for-aws/issues/85 over on the Docker for AWS repository already.

**Comment by ddebroy** [comment]
@RehanSaeed let's continue the discussion in https://github.com/docker/for-aws/issues/85 . Your issue based on the logs does not have anything to do with Moby/Moby and most likely has something to do with the network configuration in the AWS VPC where you are deploying.

**Comment by eon01** [comment]
@thaJeztah @ddebroy Thanks.  
I stopped working on this project for the moment but if I am not mistaken this didn't resolve my problem. I will keep you posted.

**Comment by thaJeztah** [comment]
I'm closing this issue here in favour of https://github.com/docker/for-aws/issues/85 so that the discussion doesn't diverge 👍
