### ISSUE TITLE
Dockerd can not restart when use containerize v1 plugins.

### ISSUE THREAD

**Issue by BSWANG** [moby/moby#33871]
**Description**

When use containerize v1 plugins， docker daemon hang infinitely on checking plugin connection. 

**Steps to reproduce the issue:**
1. Install plugin with docker container.
2.Starting containers with the plugin's resource such as volume, network, etc.
3.Restart the docker daemon.

**Describe the results you received:**
Docker daemon cannot start. And hang infinitely on checking plugin connection.

**Describe the results you expected:**
Docker daemon will start finally, regardless of the plugin state.

**Additional information you deem important (e.g. issue happens only occasionally):**

#### The Docker daemon start log:

```
Jun 29 12:18:35 acs019 dockerd[10185]: time="2017-06-29T12:18:35.137629887+08:00" level=info msg="20
17/06/29 12:18:35 [INFO] serf: EventMemberJoin: acs019 192.168.199.19\n"
Jun 29 12:18:35 acs019 dockerd[10185]: time="2017-06-29T12:18:35.139371627+08:00" level=info msg="20
17/06/29 12:18:35 [INFO] serf: EventMemberJoin: dfarm30 192.168.199.30\n"
Jun 29 12:18:35 acs019 dockerd[10185]: time="2017-06-29T12:18:35.139559538+08:00" level=info msg="20
17/06/29 12:18:35 [INFO] serf: EventMemberJoin: acs018 192.168.199.18\n"
Jun 29 12:18:35 acs019 dockerd[10185]: time="2017-06-29T12:18:35.795476339+08:00" level=info msg="De
fault bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used
 to set a preferred IP address"
Jun 29 12:18:36 acs019 dockerd[10185]: time="2017-06-29T12:18:36.594206721+08:00" level=warning msg=
"Unable to locate plugin: calico-ipam, retrying in 1s"
Jun 29 12:18:36 acs019 dockerd[10185]: time="2017-06-29T12:18:36.598575069+08:00" level=warning msg=
"Unable to locate plugin: calico-ipam, retrying in 1s"
Jun 29 12:18:36 acs019 dockerd[10185]: time="2017-06-29T12:18:36.621041902+08:00" level=warning msg=
"Unable to locate plugin: calico-ipam, retrying in 1s"
Jun 29 12:18:36 acs019 dockerd[10185]: time="2017-06-29T12:18:36.624609524+08:00" level=warning msg=
"Unable to locate plugin: calico-ipam, retrying in 1s"
Jun 29 12:18:36 acs019 dockerd[10185]: time="2017-06-29T12:18:36.630924253+08:00" level=warning msg=
"Unable to locate plugin: calico-ipam, retrying in 1s"
```

#### How to walk around it 

1. Set the daemon to "live-restore" mode.
2. Restart docker daemon. Then the docker daemon will started successfully, finally restart the plugin container, since those plugin depends on the "/var/run/docker.sock" mount which has been changed after docker daemon restart.
3. Start the containers depends on the plugins.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   8968bcd
 Built:        Fri May 26 08:01:13 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   8968bcd
 Built:        Fri May 26 08:01:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local ossfs acd nas
 Network: bridge calico host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-82-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 37.32 GiB
Name: acs019
ID: UUSW:J4P5:CEMR:Y6XW:M5O2:JF4D:QJDB:CGFR:JWIF:MYXM:UY7B:2JGY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I think this is a known limitation of v1 plugins relying on the docker socket; I don't think this will be addressed, now that the v2 plugins are replacing this functionality

but /cc @cpuguy83 for input

**Comment by BSWANG** [comment]
@thaJeztah In previous version of docker, the docker daemon will check the plugin, if plugin fail to response in 16s, the docker daemon will give up checking finally and startup. But docker in `17.03.1-ce` version hang infinitely.

**Comment by cpuguy83** [comment]
I see you have logs with the `retrying 1s`, do you have more logs?

**Comment by BSWANG** [comment]
@cpuguy83 I meet this issue again. I have add the full log to gist:
https://gist.githubusercontent.com/BSWANG/6dff9f0f220ffad0db4e793eaba95892/raw/f658d476a178b4cdd6e2369a77628b650281db22/plugin%2520v1%2520docker%2520start%2520hang

**Comment by cpuguy83** [comment]
@BSWANG Are you sure this is not just going really slowly?

**Comment by BSWANG** [comment]
Not just going slowly. I wait for several hours, and the docker hang infinitely.

**Comment by cpuguy83** [comment]
@BSWANG Can you send SIGUSR1 to the stuck daemon and collect the stack trace from the logs?

**Comment by BSWANG** [comment]
@cpuguy83 Oh, the `stackdump` goroutine not start. So can not get the stack trace by SIGUSR1.

**Comment by BSWANG** [comment]
The stackdump: https://gist.github.com/BSWANG/8f4b86531dffd484f173d7606cd45431

**Comment by cpuguy83** [comment]
@BSWANG It looks stuck making an http request to the plugin. Did the plugin receive the request but not respond yet?

**Comment by cpuguy83** [comment]
We could hardcode a request timeout here to make sure this doesn't happen, but it seems like the plugin itself is deadlocked.
Is the plugin trying to call back into dockerd?

**Comment by BSWANG** [comment]
@cpuguy83 Thanks, I will push a PR to set the `plugin`'s http client with 10s timeout. Do you have some suggestion?

**Comment by cpuguy83** [comment]
@BSWANG I worry about such a timeout since requests could legitimately take much longer.

**Comment by BSWANG** [comment]
I tested the driver's unix-socket file when daemon get stuck. The stuck url `/Plugin.Activate` can be access. Not the deadlock in plugin.

![image](https://user-images.githubusercontent.com/3598874/28354307-04c0169c-6c92-11e7-858e-6c8ff6acd677.png)

**Comment by BSWANG** [comment]
I tested set the timeout when check the plugin active. The docker daemon restart successful.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
