### ISSUE TITLE
[aufs] overlayfs backed mounts error

### ISSUE THREAD

**Issue by kvaps** [moby/moby#33881]
**Description**

**Steps to reproduce the issue:**
1. mount overlay to `/`
2. mount ext4 for to `/data`
3. Run dockerd with `--data-root /data/docker`
4. Stop dockerd
5. Check mount `cat /proc/mount` (You will see that aufs is not unmounted, and that it somehow uses overlayfs partition instead ext4)
```
tmpfs /cow tmpfs rw,relatime,mode=755 0 0
overlay / overlay rw,relatime,lowerdir=/rofs,upperdir=/cow/up,workdir=/cow/work 0 0
overlay /data/docker/aufs overlay rw,relatime,lowerdir=/rofs,upperdir=/cow/up,workdir=/cow/work 0 0
(output is shorted)
```
5. Try to dockerd with `--data-root /data/docker` (You will recieve the error here)
```
Error starting daemon: error initializing graphdriver: invalid argument
```

**Describe the results you received:**
- The docker data stores in `aufs` backed by `overlay` partition that backed by `tmp`.
- The partition is not unmounted after dockerd is stop
- Docker can not start again

**Describe the results you expected:**
- Data stores in `aufs` backed by `ext4`.
- Docker is normally start again

**Additional information you deem important (e.g. issue happens only occasionally):**

- Adding `data.mount` into systemd `Requires=` section is not helps.

- For me this issue is fully solved by switching from `aufs` to `overlay` driver.
   For todo this, just add the `--storage-driver overlay` key.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:** (Please pay attention to `Backing Filesystem` it's `overlayfs`)
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: overlayfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.35GiB
Name: m3c2
ID: 66BZ:Q2GB:PLYX:7IJI:R4YO:SYNX:LZXR:EPL7:K7PG:DZSQ:KABG:YIJR
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, ltsp node

**Comment by cpuguy83** [comment]
Forgive me, but I don't see anything mounted to `/data`.

You see `/data/docker/aufs` as overlay because docker does the equivalent of `mount --bind /data/docker /data/docker && mount --make-private /data/docker/aufs` in order to protect mounts for the graphdriver.
So, docker is not creating an overlay mount here, it's doing a bind-mount to itself so it can make everything underneath private. Since `/data/docker/aufs` is on an overlay it shows up as overlay in the mount table.

> Error starting daemon: error initializing graphdriver: invalid argument

This error is likely from the aufs driver attempting to mount aufs on top of overlay which is currently at `/data/docker/aufs` which is not supported by aufs.

**Comment by kvaps** [comment]
Sorry, this is just my mistake by copy&paste, so this string is should be there:
```
/dev/nvme0n1 /data ext4 rw,relatime,data=ordered 0 0
```
But for now, I have tried to reproduce this issue, and I wasn't success. Maybe something updated since I created issue.
So I close issue, if some one will have this error, please reopen it.

**Comment by cpuguy83** [comment]
@kvaps Thanks!
