### ISSUE TITLE
swarm mode + (--net=host)

### ISSUE THREAD

**Issue by groyee** [moby/moby#33896]
We used to work with the old standalone swarm. We had many issues with the overlay network that were never fixed by the docker team so we gave up on the overlay network and configured most of the hosts with --net=host.

We are now considering to move to the new swarm mode. It looks like --net=host is not supported anymore?

Is it possible to deploy services with the new swarm mode with a **host network** and not overlay or bridge?

**Comment by anonymuse** [comment]
Hi @groyee, have you considered using [the Macvlan driver](https://docs.docker.com/engine/userguide/networking/get-started-macvlan/) to meet your use case? You'd need to use DHCP or similar for IPAM, and I believe #32981 addresses this question.

Also, https://github.com/docker/swarmkit/issues/989.

**Comment by cpuguy83** [comment]
In 17.06 you can do `--network=host` on service create.

Closing since this is supported.
Thanks!

**Comment by groyee** [comment]
Too bad it is not possible to install 17.06

**Comment by cpuguy83** [comment]
@groyee Why? Is there something I can help with? Feel free to ping me on the community slack, too.

**Comment by groyee** [comment]
Thanks!

When you install 17.06 on Ubuntu you get:

_`docker daemon` is not supported on Linux. Please run `dockerd` directly

**Comment by cpuguy83** [comment]
@groyee I believe this is an issue with docker-machine, there's an update pending for it.

**Comment by groyee** [comment]
OK. I will wait then.

Thank You.

**Comment by better88** [comment]
waiting add to compose-file

**Comment by Toshik** [comment]
Using that option ```--network=host``` on service creation with Docket 17.06 causes service cannot be started:

```container cannot be disconnected from host network or connected to host network```

**Comment by thaJeztah** [comment]
@Toshik when using `--network=host`, the `-p` / `--publish` option cannot be used; if the container is running in the host's network, ports don't have to be published, because they're automatically accessible

**Comment by rdxmb** [comment]
works with 
Docker version 17.07.0-ce, build 8784753

**Comment by eddytruyen** [comment]
I have a follow-up question. When you create a service with --network=host, no Service IP is generated, right? 
However, is the service's name still registered as a DNS record. If so, is the DNS record an A record with a list of worker IP addresses or an SRV record with a list of WorkerIPAddresses:HostPorts? 

I haven't tried it myself. I thought asking it here will give me a quicker answer.
