### ISSUE TITLE
Windows 10 docker commands fail

### ISSUE THREAD

**Issue by Raffa50** [moby/moby#33895]
Hello today i've updated docker and when I run a command ex: docker info, docker images
I get:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/version: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by vdemeester** [comment]
cc @jhowardmsft @johnstep

**Comment by friism** [comment]
@Raffa50 I assume you're using Docker for Windows? If so, your user now has to be in the `docker-users` group. See the release notes and a related discussion:

 * https://docs.docker.com/docker-for-windows/release-notes/#docker-communityedition-17060-ce-win18-2017-06-28-stable
 * https://github.com/docker/for-win/issues/785

**Comment by Raffa50** [comment]
Yes Windows 10, I've found a solution:
run cmd as administrator, but first it worked even with no admin (the windows console)

**Comment by thaJeztah** [comment]
Given that this issue is specific to Docker for Windows, which is not maintained in this repository, and there's already issues in the Docker for Windows issue tracker on this subject, I'll closed the issue here
