### ISSUE TITLE
Docker stats refresh

### ISSUE THREAD

**Issue by ylavoie** [moby/moby#33900]
**Description**

Docker stats does great for monitoring images. The list shown is calculated upon starting the monitoring and doesn't add new running images or substract stopped ones.

**Steps to reproduce the issue:**
1. run docker stats
2. kill or start a new image

**Describe the results you received:**

Observe that killed images date id replaced by '--' but new images aren't added to the list

**Describe the results you expected:**

Refreshed list with actual running images

**Output of `docker version`:**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 67
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.0-rc7
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.608GiB
Name: nameserver
ID: 3THI:2BKX:JERV:VW27:LI2P:POKD:I5NE:4AOB:RPZE:EUXK:ISRZ:F52Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by cpuguy83** [comment]
Confirmed, though I see everything zeroed out vs `--`.

**Comment by ripcurld0** [comment]
@ylavoie @cpuguy83 what do you mean by saying "kill or start a new image"?

**Comment by ylavoie** [comment]
When I kill a running container, stats replaces the data with `--`. I was expecting that line to be removed but get something like:
> CONTAINER              CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
> hub                    0.47%               117.3MiB / 150MiB   78.18%              118MB / 153MB       27.9MB / 438kB      54
> lsmb                   --                  -- / --             --                  --                  --                  --
> nginx                  --                  -- / --             --                  --                  --                  --
> postgres               --                  -- / --             --                  --                  --                  --
When I run a new container, nginx, for example, I would expect it to show up in the list without having to restart `docker stats`

**Comment by ripcurld0** [comment]
I'm closing this in favor of #34193
