### ISSUE TITLE
Creating container fails with invalid IP address for add-host

### ISSUE THREAD

**Issue by goloroden** [moby/moby#33912]
I have written a software that controls Docker by using its REST API.

For months, it worked perfectly. Now I am having issues, since I updated from Docker for Mac 17.03 to Docker for Mac 17.06. If I create a virtual machine with Docker 17.03 using docker-machine, everything works as expected. So apparently between 17.03 and 17.06 something has changed.

The error message that I get is:

> Failed to create container chat-broker. Error response from daemon: invalid IP address in add-host: ""

What's strange about this, is that I nowhere try to set the `add-host` option for the `chat-broker` container.

Do you have any idea of what might cause this issue, and how I could get around this?

**Comment by goloroden** [comment]
PS: The same behavior happens in 17.05 on Ubuntu. So there must have been a change in the API which causes this behavior between 17.03 and 17.05. Any ideas?

**Comment by goloroden** [comment]
Okay, we found it. This was an issue with out code, not Docker. Sorry for the trouble.

**Comment by asbaghel08** [comment]
what was the issue in code ? I am getting the same error

**Comment by goloroden** [comment]
@asbaghel08 I'm really sorry, but I can't remember … it's almost five years ago (and yes, it would have been nice if I had mentioned the solution back then).
