### ISSUE TITLE
No connectivity between instances running on different nodes

### ISSUE THREAD

**Issue by saabeilin** [moby/moby#33917]
**Description**

Instances running on different nodes in a swarm on the same overlay network cannot access each other.

**Steps to reproduce the issue:**
(facing this in production, did not try to reproduce in dev/staging)
1. Create a swarm spanning a few nodes
2. Create an overlay network
3. Instances running on different nodes do not reach each other; instances on the same node perform well.

**Describe the results you received:**
`curl http://service-name:service-port` times out if the instances are on different nodes.

**Describe the results you expected:**
`curl http://service-name:service-port` always works :)

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
robot@geo2:~$ docker info
Containers: 19
 Running: 7
 Paused: 0
 Stopped: 12
Images: 59
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 295
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: jme5xqjecv38v9ykpjo33hput
 Is Manager: false
 Node Address: SECRET
 Manager Addresses:
  SECRET:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 126.1GiB
Name: geo2
ID: 7EPZ:GUJL:KC6C:7Z6J:4MJC:C2EK:I4XX:64S5:HJ6H:LI5S:FQ3Y:MFN7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: saabeilin
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
3x nodes - Linode KVM, Debian 9, kernel 4.9
1 node - physical server, Debian 8, kernel 3.16

Additional info: it was working fine on Docker 17.3 but we decided to upgrade to 17.6 because of resolver/VIP issues and got into much more serious issues :-/

P.S. `docker network inspect` shows other peers.

**Comment by saabeilin** [comment]
@GordonTheTurtle What other information should I collect/provide in order to understand what's happening?

**Comment by saabeilin** [comment]
The problem disappeared without any obvious reason :-D

**Comment by thaJeztah** [comment]
Let me close this issue, but feel free to comment if you're able to reproduce, and have logs
