### ISSUE TITLE
Invalid checksum yum install 

### ISSUE THREAD

**Issue by cscetbon** [moby/moby#33919]
** Description **

yum install fails in container because of invalid checksum

Steps to reproduce the issue:

It fails on 17.06.0-ce-mac18 see https://pastebin.com/Va7XbHER
It doesn't fail on Linux with aufs. 

** Describe the results you received: **
Rpmdb checksum is invalid: dCDPT(pkg checksums): openssl.x86_64 1:1.0.1e-60.el7_3.1 - u

** Describe the results you expected: **
Successful install

** Output of docker version: **

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

Output of docker info:

Containers: 62
 Running: 0
 Paused: 0
 Stopped: 62
Images: 7
Server Version: 17.06.0-ce
**Storage Driver: overlay2**
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: SGHK:B7ZZ:UDQO:JJCA:B6RX:BPEE:GI7N:MQ52:ZQOB:FB24:VLV3:TBBK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2017-07-02T05:30:00.262497971Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by AkihiroSuda** [comment]
Seems `yum-plugin-ovl` not installed?

**Comment by cscetbon** [comment]
There is no version available on that distribution .. I use that dockerfile https://github.com/danielwhatmuff/zappa/blob/master/Dockerfile

**Comment by AkihiroSuda** [comment]
`touch /var/lib/rpm/*` before `yum install` might work (related: https://github.com/moby/moby/issues/10180)

**Comment by thaJeztah** [comment]
Have you reported this with the image author? It's a known issue that RPM doesn't play well with overlay file systems, and the ovl plugin was created for that by the RPM developers.

Unfortunately there's not much that we can do here (there's still development going on on overlay in the kernel, so possibly this will enhance in future)

I'll close this issue for the above reason, but feel free to continue the conversation
