### ISSUE TITLE
[Proposal] Move 'contrib/syntax' to its own repository

### ISSUE THREAD

**Issue by stolho** [moby/moby#33928]
Hi,

wanted to ask, wouldn't it make sense to move `contrib/syntax` to its own separate repository? The thing is that current `moby\moby` repository is 89 MB. Where the `contrib\syntax` is just 10.5 KB. So for editors like vim huge plugins are around 2 MB, which is more exclusion. Plus most of the updates of the repository are not related to syntax at all. So when you run `:PlugInstall` or `:PlugUpdate` with `vim-plug` it takes more time to process the whole `moby\moby` repository.

Best,
Stanislav

**Comment by AkihiroSuda** [comment]
vim plugin was removed from this repo: https://github.com/moby/moby/pull/40354
