### ISSUE TITLE
docker daemon dead

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#33927]
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

run 20 container in host. docker ps ,wait 5 mins ,no response.

**Comment by timchenxiaoyu** [comment]
systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since 一 2017-07-03 10:14:37 CST; 8h ago
     Docs: https://docs.docker.com
 Main PID: 11460 (dockerd)

**Comment by cpuguy83** [comment]
Note that 1.12.6 is no longer supported, you should upgrade to 17.06.
But in any case, can you please send `SIGUSR1` to the dockerd process and collect the stack trace from the logs?

This will help pinpoint what is causing it to get stuck.

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
