### ISSUE TITLE
Can configure --cpu-quota bigger than --cpu-period ?

### ISSUE THREAD

**Issue by lvfan21** [moby/moby#33937]
I am trying use --cpu-quota and --cpu-period together, per my understanding, --cpu-period should be bigger than --cpu-quota, so I do following testing:

[root@localhost ~]# docker run -it --cpu-period 20000 --cpu-quota 40000 ubuntu:14.04 
root@aeec94baa243:/# cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us 
40000
root@aeec94baa243:/# cat /sys/fs/cgroup/cpu/cpu.cfs_period_us 
20000
root@aeec94baa243:/# 

from the test result, it was successful.

**Comment by albamc** [comment]
Cpu quota / period is the value for one CPU core. So, if you have multiple CPU cores on your server (almost), it is possible to set a higher quota than peirod.

**Comment by lvfan21** [comment]
only one cpu core in my machine, and it was successful to configure quota bigger than preriod:
[root@localhost ~]# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
stepping	: 2
microcode	: 0x19
cpu MHz		: 2394.866
cache size	: 6144 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips	: 4789.73
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

[root@localhost ~]#

**Comment by lvfan21** [comment]
@albamc

**Comment by albamc** [comment]
@lvfan21 
Umm... The quota is how much CPU resources are available for a certain period of time, and if all of the CPU resources are used within that period, scheduling is disabled so that the CPU can no longer be used until the next period. So if you set more cpu time than period, I think you can use cpu time as period. (quota is just limitation)

**Comment by cpuguy83** [comment]
Closing since this isn't really an issue, but feel free to continue the discussion.
