### ISSUE TITLE
Cannot build with labels in quotes.

### ISSUE THREAD

**Issue by bweston92** [moby/moby#33943]
**Description**

Using 17.06 I cannot build my Dockerfile that has quotes around labels, however I cannot find this in any changelogs.

**Steps to reproduce the issue:**
1. Use label statement with quotes in your Dockerfile i.e: `LABEL "traefik.enable=true"`
2. Attempt to build the Dockerfile

**Describe the results you received:**

Docker 17.06 (building with compose)
```
ERROR: Service 'test' failed to build: failed to process "\"traefik.enable": unexpected end of statement while looking for matching double-quote 
```

**Describe the results you expected:**

Docker 17.05
```
Sending build context to Docker daemon  44.54kB
Step 1/2 : FROM debian
 ---> a2ff708b7413
Step 2/2 : LABEL "traefik.enable true"
 ---> Running in a8440ca588eb
 ---> 5b6ad4d12fa2
Removing intermediate container a8440ca588eb
Successfully built 5b6ad4d12fa2
Successfully tagged test:latest
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87 
```

**Output of `docker info`:**

```
Containers: 37
 Running: 20
 Paused: 0
 Stopped: 17
Images: 1010
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1110
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.507GiB
Name: lindesk1
ID: ZW36:HZLG:SVJD:MPJN:TVQU:R7KG:PTVP:IQWJ:QHRA:OBEY:KXVD:KNHN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: legalweb
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false 
```

**Comment by kabobbob** [comment]
It appears an update was made on how LABELS are noted:

https://docs.docker.com/engine/reference/builder/#label

**Comment by bweston92** [comment]
Ok but in a minor version?

Surly that is a breaking change.

**Comment by ripcurld0** [comment]
I am closing this but feel free to continue the conversation.

**Comment by kabobbob** [comment]
I would agree that it is a breaking change. That said, I'm not sure when this change occurred. My work has been such that I haven't needed to build an image in a while.

**Comment by thaJeztah** [comment]
This change was a result of https://github.com/moby/moby/pull/32328, which fixes part of https://github.com/moby/moby/issues/32140. While this is a change in validation, the previously accepted value was not valid; from the [documentation](https://docs.docker.com/engine/reference/builder/#label), so people relying on this have been relying on a bug in the validation;

> ## LABEL
>
>     LABEL <key>=<value> <key>=<value> <key>=<value> ...
>
>The `LABEL` instruction adds metadata to an image. A `LABEL` is a
>key-value pair. To include spaces within a `LABEL` value, use quotes and
>backslashes as you would in command-line parsing.

I'm not sure if a fallback mechanism would be possible to both fix the parsing of quotes in values, and keep this old behaviour (or if that's desirable)

ping @duglin @tianon @tonistiigi any thoughts? ^^

**Comment by bweston92** [comment]
It's done now so no need to go back I suppose. Should of been documented
somewhere on the change list as I couldn't find anything.
