### ISSUE TITLE
Plugin Addr path is stripped when called

### ISSUE THREAD

**Issue by hjdr4** [moby/moby#33947]
**Description**

When having a plugin with Addr like http://localhost:1234/plugin, the plugin is called without /plugin.

**Steps to reproduce the issue:**
1. Declare a dummy plugin: 
```echo "{\"Name\":\"dummy\",\"Addr\":\"http://localhost:1234/dummy\"}" > /etc/docker/plugins/dummy.json```
2. Create a dummy volume: ```docker volume create --driver=dummy --name=dummy```

**Describe the results you received:**
Error response from daemon: create dummy: Error looking up volume plugin dummy: legacy plugin: Post http://localhost:1234/Plugin.Activate: dial tcp 127.0.0.1:1234 : getsockopt: connection refused

**Describe the results you expected:**
Plugin is called like http://localhost:1234/dummy/Plugin.Activate

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

I have tested with a real plugin behind, it's not called as it should.
Also, the documentation https://docs.docker.com/engine/extend/plugin_api/#plugin-discovery indicates paths are supported.

**Comment by thaJeztah** [comment]
Does this work if you use `tcp://` instead of `http://` ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
