### ISSUE TITLE
[Windows] 'docker info' doesn't accept '--format' when issued through CMD, works fine through Powershell

### ISSUE THREAD

**Issue by witsec** [moby/moby#33959]
This works fine on Powershell:
> docker info --format '{{ json .Swarm }}'
> 
> {"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null}
> 

But doesn't on CMD:
> docker info --format '{{ json .Swarm }}'
> 
> "docker info" accepts no argument(s).
> See 'docker info --help'.
> 
> Usage:  docker info [OPTIONS]
> 
> Display system-wide information

A "docker version" returns the exact same information:
> Client:
>  Version:      17.06.0-dev
>  API version:  1.31
>  Go version:   go1.8.3
>  Git commit:   edfc89f
>  Built:        Thu Jun 22 00:16:32 2017
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      17.06.0-dev
>  API version:  1.31 (minimum version 1.24)
>  Go version:   go1.8.3
>  Git commit:   930e689
>  Built:        Thu Jun 22 00:41:34 2017
>  OS/Arch:      windows/amd64
>  Experimental: false

I tried this on both Windows Server 2016 Standard and Windows Server 2016 Core.

Any ideas?

**Comment by thaJeztah** [comment]
ping @johnstep @friism PTAL

**Comment by friism** [comment]
cmd.exe doesn't treat `''` as a way to create a single string: https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q

Use double quote instead, it works:

```
Microsoft Windows [Version 10.0.16237.1001]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\friism>docker info --format "{{ json .Swarm }}"
{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null}
```

**Comment by witsec** [comment]
Ahh.. that's it! Thanks for the insight, that's gonna help.
