### ISSUE TITLE
Docker binary releases no longer available

### ISSUE THREAD

**Issue by lox** [moby/moby#33951]
I've just noticed (with horror):

https://github.com/moby/moby/releases/tag/v17.05.0-ce

> Note: those packages won't be updated for the next releases. Get Docker CE from Docker Store

and now `https://get.docker.com/builds/Linux/x86_64/docker-17.06.0-ce.tgz`returns a 403 error. 

This is a pretty epic breakage of convention. It's going to break a lot of people's things. Is there some more thinking / rationale about why this was done?

The link to the "community store" is to https://store.docker.com/search?type=edition&offering=community, which shows no mention of which one of these things might lead to the binary release. The [binaries page](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/) still suggests that binaries will be available from the GitHub releases.

**Comment by lox** [comment]
Seems like there are some binaries in https://download.docker.com/linux/static/stable/x86_64/, but not the latest 17.06.3-ce.

**Comment by AkihiroSuda** [comment]
cc @andrewhsu @vieux

**Comment by lox** [comment]
Looks like I misread releases, my comment above is incorrect, the latest is 17.06.0-ce, which is available from the URL I mentioned, but not the one linked everywhere else.

**Comment by thaJeztah** [comment]
with the split between the Moby project, and he Docker products, the moby repository is now an upstream for Docker. Releases are now created from the https://github.com/docker/docker-ce/releases repository.

Packages and static builds can be found on https://download.docker.com and https://store.docker.com

**Comment by lox** [comment]
Could you point out specifically where the binaries are downloaded from please @thaJeztah?

**Comment by thaJeztah** [comment]
The link you mentioned above is the right location for x86 static binaries; deb and rpm packages can also be found on download.docker.com, or following the instructions on https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/ (that link is for Ubuntu, but you'll find other distros in the menu)

Alternatively, use the express install script on https://get.docker.com, which automates setup, but may not be suitable for production if additional configuration is required

**Comment by lox** [comment]
Where would be better to file my above bug btw?

**Comment by thaJeztah** [comment]
What's the bug? Old packages are still on the old location, but new packages are available on a new location

**Comment by lox** [comment]
https://docs.docker.com/engine/installation/linux/docker-ce/binaries/ links to the Moby release notes for the binaries.

**Comment by lox** [comment]
Which no longer have binaries, they are pointed to in the store, which doesn't contain them.

**Comment by thaJeztah** [comment]
Ah! Sorry, missed that part; I think they temporarily changed that link, because download.docker.com was not browsable yet; you can report issues with the documentation using the "request docs changes" button on that page, or open a pull request using the "edit this page" button

**Comment by lox** [comment]
How about the part where the releases page points to a non-existent binary release in the store?

**Comment by thaJeztah** [comment]
> Get Docker CE from Docker Store

I don't see a mention of "binary release"?

**Comment by lox** [comment]
How would you suggest that as a user I figure out where to download the
binary release from? Say for Amazon Linux?

**Comment by lox** [comment]
> I don't see a mention of "binary release"?

Right, isn't that the point?

**Comment by lox** [comment]
Seems like old links that used to work now no-longer work too: https://download.docker.com/linux/static/stable/x86_64/docker-17.05.0-ce.tgz for instance.

**Comment by claygriffiths** [comment]
FWIW some binaries are here but it's missing Darwin and it's only from `master`: https://master.dockerproject.org/

**Comment by cpuguy83** [comment]
@lox We've never provided binaries for Amazon Linux.
If you want static binaries, there is the downloads.docker.com link above.

The issue looks like the docs are just pointing to the wrong place?

**Comment by lox** [comment]
You did at one point ;) And then when you stopped you could at least find the binaries via the Releases page. Now you've got to look two different places, and ignore all references to the Docker Store. 

Isn't it reasonably clear that this is lousy UX?

**Comment by lox** [comment]
Why not just keep providing the binaries via the releases page? That is where everyone looks.

**Comment by andrewhsu** [comment]
@lox we're missing links to point people to the static binaries, apologies for that. We'll work to get them up on the [docs page](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/).

In the meantime, all the static binaries for the 17.06.0 release can be found at the new location:
* https://download.docker.com/linux/static/
* https://download.docker.com/mac/static/
* https://download.docker.com/win/static/

The release page for docker/docker-ce really represents the source code. There is more consideration for the user than downloading the static binaries such as prerequisites, security, and upgrading. All of which is more suited for the documentation site than the release page notes.

To bridge the connection between the source release and the binaries to install to get the release, I've updated the release page notes at the bottom with an **Installation** section to link to the docs: https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce

In the future, feel free to file issues about the docker-ce product in the issue-only tracker for docker products for linux: https://github.com/docker/for-linux

**Comment by AkihiroSuda** [comment]
Can we create a "fake" release that only contains "Please refer to https://github.com/docker/docker-ce/releases for recent Docker product releases", so that people visiting https://github.com/moby/moby/releases can easily find latest Docker product release information?

**Comment by thaJeztah** [comment]
> Can we create a "fake" Moby release

LOL, I sent my self this as a reminder a while back, having the same thought:
<img width="601" alt="screen shot 2017-07-10 at 20 44 49" src="https://user-images.githubusercontent.com/1804568/28050156-c99c428a-65b0-11e7-832e-9c65074f0873.png">

The tricky bit there is that 17.03.x is still being maintained, thus there may be another tag after that. Also I'd have to check if there's auto-builds attached to this repo, etc.

**Comment by sandersaares** [comment]
I recall downloading the .deb files from https://download.docker.com/linux/ubuntu/dists/xenial/edge/ but I do not see them there anymore. Are releases still available for download in .deb format?

**Comment by thaJeztah** [comment]
@sandersaares try the `pool` directory; that's where the `.deb` files are in the repository; https://download.docker.com/linux/ubuntu/dists/xenial/pool/

**Comment by sandersaares** [comment]
Perfect. Thanks!

**Comment by lox** [comment]
Might be worth removing the Releases section on https://github.com/moby/moby/wiki. It's the first google hit for "docker releases".

**Comment by lox** [comment]
Might it be worth removing the releases area of moby entirely @thaJeztah?

**Comment by thaJeztah** [comment]
> Might be worth removing the Releases section on https://github.com/moby/moby/wiki. It's the first google hit for "docker releases".

Removing the wiki was indeed being discussed a while back (after backing it up - cloning it). It's odd though why Google picked it as a snippet

> Might it be worth removing the releases area of moby entirely @thaJeztah?

No, we can't remove tagged releases

**Comment by lox** [comment]
Fair enough. I guess I'll close this one out!

**Comment by ljani** [comment]
Where can I find recent binaries of the Windows client (for example the `docker.exe` of the v17.12.0-ce`? [`download.docker.com`](https://download.docker.com/win/static/stable/x86_64/) is horribly outdated.

**Comment by cpuguy83** [comment]
@ljani Please ask on github.com/docker/for-win

Thanks!

**Comment by ljani** [comment]
@cpuguy83 Sure. The thing is that the issue has been raised there many times, eg. https://github.com/docker/for-win/issues/1599 https://github.com/docker/for-win/issues/1460, without any reply. I thought I would poke you guys here, if you had any idea. Thanks though.

**Comment by cpuguy83** [comment]
AFAIK there is only the Docker For Windows release and whatever comes with Windows Server.

**Comment by sandersaares** [comment]
There used to be regular builds here: https://download.docker.com/win/static/edge/x86_64/

I think these were used by Docker for Windows. These updates stopped after a while, howeever (last file October 18). Does this means Docker for Windows is not being updated anymore?

**Comment by Drewster727** [comment]
@thaJeztah any idea where we can get the latest for win server?
https://github.com/docker/for-win/issues/1460#issuecomment-631753670

**Comment by thaJeztah** [comment]
You can install docker engine enterprise edition; license is included with Windows Server; https://docs.docker.com/ee/docker-ee/windows/docker-ee/

**Comment by Drewster727** [comment]
thanks @thaJeztah but if you look closely on that doc, it still references 19.03.5:
https://docs.docker.com/ee/docker-ee/windows/docker-ee/#use-a-script-to-install-docker-engine---enterprise

How do we get latest? e.g. 19.03.8 / 19.03.9

**Comment by thaJeztah** [comment]
Sorry, can't answer that; the EE Engine is now part of Mirantis, and I'm no longer involved in those builds.

**Comment by Drewster727** [comment]
@thaJeztah what if we want just the docker-ce bin files? like the raw docker.exe and dockerd.exe for those newer versions?
Seems kinda hacky to me to have to strip them out of the docker desktop program files...
