### ISSUE TITLE
[question] how to deal partial success in prune API?

### ISSUE THREAD

**Issue by allencloud** [moby/moby#33957]
Hi, All, 

I found that in prune API, for partial success docker daemon directly returns 500, while I think we could improve this.

Here is an example:

A user has 10 unused images, and he sends an image prune API request. If docker daemon succeeds in removing 5 unused images, and fails to remove the others, what should docker daemon return for the client request?

Current Docker Daemon's response:

Docker Daemon directly responses with a 500 error, and ignore the 5 images which have already been removed. And the 5 removed images' space size cannot be passed to the client side.

I think the is a partial success case. For the successful part, the corresponding data is still important for user, thus I think we need to make docker daemon will transfer the data to client side? Then what kind of status code is reasonable? 200, 500, 207?

ping @stevvooe @mlaventure

**Comment by mlaventure** [comment]
Yes, when implementing prune I wanted that data to be available, but after a bit of research, I realized it'd require quite a bit of refactoring as if an error is returned, the data is completely ignored.

One solution may be not to return an error to the HTTP handler but include it as part of the response when we did manage to clean at least something.

**Comment by allencloud** [comment]
Yeah, the first thing comes to my mind is to add a filed `Warnings` to the response. PruneReport and to return a status code of 200.

WDYT? @mlaventure

**Comment by mlaventure** [comment]
@allencloud actually, looking at the code, it's mostly correct.

The warnings are logged in the daemon logs, which I think is sufficient for such an operation as a prune.

What need to be changed is:
  - when the context is cancelled, only return the response struct and not the context.Err as presently
  - In `VolumesPrune` changing this [return](https://github.com/moby/moby/blob/master/daemon/prune.go#L146) to a continue will do the trick.
  -  remove this [return](https://github.com/moby/moby/blob/master/daemon/prune.go#L307) would have the same effect

And that should make it so there's always an answer.

WDYT?

**Comment by allencloud** [comment]
@mlaventure The overall idea is totally reasonable for me. While I cannot quite follow this one:

> In VolumesPrune changing this [return](https://github.com/moby/moby/blob/master/daemon/prune.go#L146) to a continue will do the trick.

Since the context is cancelled in pruneVols, traverseLocalVolumes will return an error, and we need to judge if this is a cancelled error, and return the report without error.

**Comment by mlaventure** [comment]
@allencloud you totally right, I didn't read the code correctly, there's not even a loop there! :sweat_smile:
