### ISSUE TITLE
docker system prune not giving me back disk space

### ISSUE THREAD

**Issue by asmeurer** [moby/moby#33968]
I am running out of disk space on my Mac since installing Docker and building some images, and trying to get it back. The command `docker system prune` claims to be freeing a lot of space, but I never see a dime of it. For example:

```
$ df -h
Filesystem                          Size   Used  Avail Capacity  iused      ifree %iused  Mounted on
/dev/disk1                         465Gi  461Gi  3.4Gi   100%  7312433 4287654846    0%   /
...
$ docker system prune
WARNING! This will remove:
	- all stopped containers
	- all volumes not used by at least one container
	- all networks not used by at least one container
	- all dangling images
Are you sure you want to continue? [y/N] y
Deleted Containers:
3e18cb34fa61b75192f5d9ca0e7d897869a418cbd7f140590d90c0e4b7d1945d
4b03e4908c1a1a1b131f9fedc8e6b155836cb25ff05a0d0a23de3b3338535e7a

Total reclaimed space: 4.562GB
$ df -h
Filesystem                          Size   Used  Avail Capacity  iused      ifree %iused  Mounted on
/dev/disk1                         465Gi  461Gi  3.4Gi   100%  7312432 4287654847    0%   /
...
```

Previously a prune command claimed to free 30GB, which I never saw.

Am I misunderstanding what `docker system prune` does (maybe it needs better messaging?), or is this a bug?

How do I tell how much space docker should be taking up? `docker images -a` lists a bunch of images with sizes that add up to 90GB, but my `~/Library/Containers/com.docker.docker` (as far as I can tell, this is where the containers are stored) is only about 46GB.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 3OGQ:BG4J:4ATX:DSQQ:BJ3W:UK3X:RUSN:ZODI:GBOR:DAZX:4365:57R7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 43
 System Time: 2017-07-05T23:18:12.867494657Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I am on macOS 10.12.6.

**Comment by thaJeztah** [comment]
Thanks for reporting; this is an issue specific to Docker for Mac, and being discussed here; https://github.com/docker/for-mac/issues/371

I'll close this issue, because the code doing the `system prune` is working correctly, so there's nothing to be fixed in this repository

Feel free to comment after I closed, if you need more information 👍

**Comment by idchlife** [comment]
docker system prune centos 7.0 does not give free space also

docker version 18.03.1-ce, build 9ee9f40

after I'm doing docker system prune it's too showing space it's freed (sometimes many gb, like in 1 hour it showed that freed 30gb only after 3 rebuilds), but no space actually freed.

**Comment by bia-bucur** [comment]
I'm having the same trouble when using `docker system prune` in an Ubuntu 18.04 virtual machine.

**Comment by thaJeztah** [comment]
@bia-bucur did you check the space inside the VM or on the host? If you checked on the host, it's possible that the VM's virtual disk doesn't (immediately) reclaim disk space, which is not something docker can change
