### ISSUE TITLE
docker run failed with sshfs plugin

### ISSUE THREAD

**Issue by hanwei1990** [moby/moby#33981]
**Description**
 I just flow the step in https://docs.docker.com/engine/reference/commandline/plugin_upgrade/#examples,
and get the error.

**Steps to reproduce the issue:**
1. docker plugin install vieux/sshfs DEBUG=1
2. docker volume create -d vieux/sshfs:latest -o sshcmd=root@192.168.200.85:/tmp -o password=123456 sshvolume
3. docker run -it -v sshvolume:/data alpine sh -c "touch /data/hello"

**Describe the results you received:**
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/plugins/98bc5ded75818e8b766ceca9310bfe28ccf863c83d3e77ac1aef9084ecbd4cf2/rootfs/mnt/volumes/28219cfff17b3be03b2b39602cd81f3c\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/178af9045f80ebe7324e7874c2de92679bd67d31f13c3ca977e088d7e13715e4\\\" at \\\"/data\\\" caused \\\"stat /var/lib/docker/plugins/98bc5ded75818e8b766ceca9310bfe28ccf863c83d3e77ac1aef9084ecbd4cf2/rootfs/mnt/volumes/28219cfff17b3be03b2b39602cd81f3c: value too large for defined data type\\\"\"".

**Describe the results you expected:**
 It should has no output.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
root@host-192-168-200-84:~# docker -v
Docker version 17.06.0-ce, build 02c1d87

**Output of `docker info`:**
root@host-192-168-200-84:~# docker info
Containers: 10
 Running: 5
 Paused: 0
 Stopped: 5
Images: 9
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: sqgf36wtz4h2fgpufwwy54jf8
 Is Manager: true
 ClusterID: el11k8ra4wlggryk90rrz6ntw
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.200.84
 Manager Addresses:
  192.168.200.84:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: host-192-168-200-84
ID: Z3T5:PCP7:JE7C:W3TR:VE55:EKLI:6WCL:WNO3:E2OJ:A5QD:YSDK:LBIP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by gary-cowell** [comment]
have same problem. I chose vieux/sshfs as a sample for helping me work through creating a volume plugin of my own, but it won't deploy. I get the same error,  also same OS, Ubuntu 16.04.

I note from my SSH server that a connection attempt is made to the SSH server, and it authenticates, before throwing this error.

**Comment by thaJeztah** [comment]
The error is printed by libcontainer/RunC; https://github.com/opencontainers/runc/blob/2d41c047c83e09a6d61d464906feb2a2f3c52aa4/libcontainer/rootfs_linux.go#L57, but originating from this function, which is rather large https://github.com/opencontainers/runc/blob/2d41c047c83e09a6d61d464906feb2a2f3c52aa4/libcontainer/rootfs_linux.go#L153-L335


ping @vieux any ideas?

ping @tiborvass could this be related to the runtime-spec issues we found?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
