### ISSUE TITLE
How to vendor docker 17.06.0-ce?

### ISSUE THREAD

**Issue by bquenin** [moby/moby#33989]
Hi, I'm working on a project relying on docker and I'd like to vendor the code corresponding to the docker `17.06.0-ce` version so that we're in sync with the official release.
It seems that there's no tag anymore on this project (`moby/moby`), however, looking at the `docker/docker-ce` repository, I didn't see the commit hash that was used to build the docker 17.06.0-ce release.
What do you recommend regarding vendor now? I'm fine using a commit hash, however, I'm not sure which one I'm supposed to use.

**Comment by andrewhsu** [comment]
@bquenin the commit hash for the docker-ce 17.06.0 release is `02c1d87` and is tagged as [v17.06.0-ce](https://github.com/docker/docker-ce/tree/v17.06.0-ce). There is also a github release page for the tag when the release goes out: https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce

**Comment by bquenin** [comment]
@andrewhsu Thanks for your reply. I noticed the tag on the `docker/docker-ce` repository. However, this is not the repository I use for vendoring, I use the `moby/moby` one. Hence my question on how to get the corresponding commit hash for the `moby/moby` repository.

**Comment by tiborvass** [comment]
@bquenin thanks for opening the issue. We'll work on a fix that works for everyone. Out of curiosity, which vendoring tool are you using?

**Comment by bquenin** [comment]
@tiborvass thanks!
We're currently using `glide` but we're going to move to `vndr` soon.

**Comment by tiborvass** [comment]
@bquenin Awesome, I love vndr too :) will keep you posted.

**Comment by ndegory** [comment]
@tiborvass, just in case, do you know the moby/moby sha that matches docker-ce 17.06? that would be a workaround until we have a better solution.

**Comment by cpuguy83** [comment]
@ndegory There isn't one, which is the major issue since docker/docker-ce has backported patches that came after the branch was cut from moby/moby.

**Comment by vdemeester** [comment]
Yeah, we had the same problem when updating `docker` deps on traefik (see https://github.com/containous/traefik/pull/1823). Tried to use commits from `moby/moby` and `docker/cli` that works together but we need a better solution for that 👼

**Comment by tiborvass** [comment]
Solution for right now: manually clone docker/docker-ce at the desired branch and put the `components/engine` directory to `vendor/github.com/docker/docker`.

**Comment by fntlnz** [comment]
FTR Some discussion is going on here too: https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/79

**Comment by Namsulee** [comment]
Hi guys  I am the same issue. I want to use v17.06.1-ce in my vendor but glide is not able to update the version due to the similar reason. Like I you said I can take the version from github.com/docker/docker-ce but I need the same place to update. Is it processing so far or is there a
Other way to tackle? If I am wrong please correct me.!

**Comment by ekristen** [comment]
Same problem here. Any progress on a solution?

**Comment by Zalgo2462** [comment]
Any news on this front? Should we simply point our vendoring tools at https://github.com/docker/docker-ce/tree/master/components/engine/client for vendoring tagged versions of the client API?

**Comment by aduermael** [comment]
Test test test test

**Comment by cpuguy83** [comment]
`github.com/docker/engine` is now an official repository that will be tagged with the docker release on the correct commits.

It's still not absolutely perfect since the packages are `github.com/docker/docker`, which itself redirects to moby/moby.... but at least you can get a client with the right commits (starting with the 18.06 releases... currently rc1 and rc2 are tagged).

**Comment by rc979** [comment]
@cpuguy83: thanks! how can we get this to work despite the redirect? Any workaround you can share?

**Comment by cpuguy83** [comment]
@rc979 This depends on your vending technique.

**Comment by rc979** [comment]
Do you have an example you could show for dep illustrating how one could
use the github.com/docker/engine repo despite the redirect? Thanks!

**Comment by cpuguy83** [comment]
@rc979 
From the `dep` docs:
```
[[constraint]]
  # Required: the root import path of the project being constrained.
  name = "github.com/user/project"
  # Recommended: the version constraint to enforce for the project.
  # Note that only one of "branch", "version" or "revision" can be specified.
  version = "1.0.0"
  branch = "master"
  revision = "abc123"

  # Optional: an alternate location (URL or import path) for the project's source.
  source = "https://github.com/myfork/package.git"

  # Optional: metadata about the constraint or override that could be used by other independent systems
  [metadata]
  key1 = "value that convey data to other systems"
  system1-data = "value that is used by a system"
  system2-data = "value that is used by another system"
```

**Comment by deviantony** [comment]
@rc979 This is how I was able to vendor the latest release of docker via `dep`:

```
# Unable to pin this package to a specific version as repository versions
# are not valid semver: https://github.com/moby/moby/issues/37281
[[constraint]]
  name = "github.com/docker/docker"
  # This repository allows us to have a track of recent releases (tags not available in moby/moby)
  # https://github.com/moby/moby/issues/33989#issuecomment-403873249
  source = "https://github.com/docker/engine.git"
  # This revision points to release v18.06.1-ce
  revision = "320063a2ad06a1d8ada61c94c29dbe44e2d87473"

# For some reason, the vendored Docker dependencies are using a specific version of
# the distribution package.
# Found via: https://github.com/moby/moby/blob/master/vendor.conf#L67
[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"
```

**Comment by AkihiroSuda** [comment]
Can we close this issue now?
