### ISSUE TITLE
get.docker.com typo

### ISSUE THREAD

**Issue by Silex** [moby/moby#33985]
Where is the install script located? When viewing https://get.docker.com we see this:

```
# NOTE: Make sure to verify the contents of the script
#       you downloaded matches the contents of install.sh
#       located at https://github.com/docker/docker-install
#       before executing.
```

https://github.com/docker/docker-install does not exist.

**Comment by cpuguy83** [comment]
Thanks for reporting. The repo was left private but is now public. Can you verify and close if all is good?

Thanks!

**Comment by thaJeztah** [comment]
Yes, thanks for reporting; it took a bit longer to make the repository public, but should be all set now.

I'll close this issue, but feel free to continue the conversation 👍

**Comment by Silex** [comment]
Alright :+1:
