### ISSUE TITLE
Long living TCP connection without traffic are dropped after 15 minutes when service is running in swarm

### ISSUE THREAD

**Issue by sasavilic** [moby/moby#34006]
**Description**

I have one service running that takes long time to complete task. After switching to docker, we experienced same strange behavior: 

 1. Client sends request (HTTP/SOAP) 
 2. Server takes long time to process request (20 minutes) 
 3. Server sends response 
 4. Client does not get response and still waits

My first thought was NAT, because docker internally uses private IP range. So I have implemented two scripts, one acting as server and one as client. Client sends request with number X, and server waits X seconds before sending response. Fairly simple. I was able to determine, that if server waits longer then 900 seconds, its response is dropped. 

What me confuses, is that in meantime I have been watching NAT with conntrack: 

    $ while true; do echo $(date) ' - ' $(conntrack -L -p tcp --dport 55500 2>/dev/null); sleep 1; done
    Fri Jul 7 09:42:54 UTC 2017  -  tcp 6 431049 ESTABLISHED src=10.66.122.31 dst=10.66.122.160 sport=59018 dport=55500 src=172.18.0.2 dst=10.66.122.31 sport=55500 dport=59018 [ASSURED] mark=0 secctx=system_u:object_r:unlabeled_t :s0 use=1
    Fri Jul 7 09:42:55 UTC 2017  -  tcp 6 431048 ESTABLISHED src=10.66.122.31 dst=10.66.122.160 sport=59018 dport=55500 src=172.18.0.2 dst=10.66.122.31 sport=55500 dport=59018 [ASSURED] mark=0 secctx=system_u:object_r:unlabeled_t :s0 use=1
    Fri Jul 7 09:42:56 UTC 2017  -  tcp 6 431047 ESTABLISHED src=10.66.122.31 dst=10.66.122.160 sport=59018 dport=55500 src=172.18.0.2 dst=10.66.122.31 sport=55500 dport=59018 [ASSURED] mark=0 secctx=system_u:object_r:unlabeled_t :s0 use=1
    Fri Jul 7 09:42:57 UTC 2017  -  tcp 6 431046 ESTABLISHED src=10.66.122.31 dst=10.66.122.160 sport=59018 dport=55500 src=172.18.0.2 dst=10.66.122.31 sport=55500 dport=59018 [ASSURED] mark=0 secctx=system_u:object_r:unlabeled_t :s0 use=1

This was first case when my service was running as docker service (`docker service create`). 

When I repeated same tests, but this time running image *locally* with `docker run` instead of `docker service create` I **wasn't able to reproduce same behavior**! Why?

**Steps to reproduce the issue:**
1. Create docker image with server.py as entry point (see below for code example)
2. Run server.py in docker (as docker service (`docker service create -p 55500:8080 ...`)
3. Run client.py on same host (`./client.py http://localhost:55500`)
4. Observe timeout
5. Run server.py in docker, but this time *localy* (`docker run -p 55500:8080 ...`)
6. Run client.py on same host (`./client.py http://localhost:55500`)
7. Observe timeout

**Describe the results you received:**
Timeout after 900 seconds.

**Describe the results you expected:**
No timeout. I have healthy TCP connection and IMHO it shouldn't be dropped after 15 minutes. 

**Output of `docker version`:**

```Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Output of `docker info`:**

```Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 332
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 304
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 8ar564651hrpf8zrp7ebdus5d
 Is Manager: true
 ClusterID: vzj71j6xvfkoj8knlt1so3l8l
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: sasa
ID: YHZT:6GWO:2Y2E:BXZV:SZU3:ZYYK:TJSN:MPKC:ZAYR:6KMH:OWO5:PEKL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
**server.py**
```#!/usr/bin/python

import BaseHTTPServer
import re
import time
import logging


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
LOG = logging.getLogger()


class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_GET(self):
        data = 'OK'
        m = re.match(r'^/*(\d+)', self.path)
        if m is None:
            self.send_response(400, 'Bad Request')
            self.end_headers()
        else:
            sleeptime = int(m.group(1))
            LOG.info("Sleeping for %s seconds ...", sleeptime)
            time.sleep(sleeptime)
            LOG.info("Sending response")
            self.send_response(200, 'OK')
            self.send_header('Content-Type', 'text/plain')
            self.send_header('Content-Length', len(data))
            self.end_headers()
            self.wfile.write(data)
            self.wfile.close()


LOG.info("Starting server at %s", 8080)
server_address = ('', 8080)
httpd = BaseHTTPServer.HTTPServer(server_address, Handler)
httpd.serve_forever()
```

**client.py**
```#!/usr/bin/python

import urllib2
import argparse
import socket
import logging


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
LOG = logging.getLogger()


parser = argparse.ArgumentParser()
parser.add_argument("url")
opts = parser.parse_args()


min_time = 1.0
max_time = 7200.0
test_time = min_time
test_time = 960

while min_time < max_time:
    LOG.info("test_time=%s, min_time=%s, max_time=%s", test_time, min_time, max_time)
    timeout = False
    final_url = "%s/%s" % (opts.url, test_time)
    try:
        response = urllib2.urlopen(final_url, timeout=test_time + 5)
        LOG.info("Got response")
        response.close()
    except socket.timeout:
        LOG.info("Got timeout!")
        timeout = True

    if timeout:
        max_time = test_time
    else:
        min_time = test_time

    test_time *= 2
    if test_time > max_time:
        test_time = (max_time + min_time) / 2.0

LOG.info("NAT expire timer is %s seconds!", max_time)
```

**Comment by thaJeztah** [comment]
Thanks for reporting; I think this is a duplicate of https://github.com/moby/moby/issues/33685, could you have a look if that looks indeed the same, and if so, close this issue? There's also this issue, which may be related https://github.com/moby/moby/issues/29655

**Comment by sasavilic** [comment]
I looks very similar to #33685, but not to #29655. I could though still be different bug, but let's close it for now.

**Comment by thaJeztah** [comment]
Thanks!
