### ISSUE TITLE
Resetting restart policy state

### ISSUE THREAD

**Issue by sean-fabri** [moby/moby#34007]
I am setting the --restart-max-attempts to 1 on the docker service create command.

Behaviour is:
- I kill the container, and a new one comes up. This is fine.
- I kill the new one and the service stays "shutdown". This is also fine.
- I perform a manual restart docker service update --force 
- If I kill the container now I don't get my restart attempts back and the service stays shutdown. It seems the only way of resetting the attempted restarts is by removing and adding the service.

Should service update reset the attempted restarts? Or should there be a "--restart-reset-window" option? There is a --restart-window option but I understand this to be the time period to enforce the restart policy rather than the time period to reset restart policy state.

**Comment by sean-fabri** [comment]
May be related to https://github.com/docker/swarmkit/pull/2290

**Comment by thaJeztah** [comment]
ping @aaronlehmann PTAL

**Comment by aaronlehmann** [comment]
I agree that this is not the right behavior. The restart count should be reset when the service spec is updated. Now that swarmkit has the concept of "spec version", this would be relatively easy to implement.

**Comment by aaronlehmann** [comment]
I've opened https://github.com/docker/swarmkit/pull/2304 to fix this.

**Comment by ripcurld0** [comment]
@aaronlehmann can we close this issue?

**Comment by aaronlehmann** [comment]
It looks like that change has not been vendored yet.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as fixed.
