### ISSUE TITLE
Cannot install on 17.04: error: maximum authentication attempts exceeded for root from

### ISSUE THREAD

**Issue by nullpixel** [moby/moby#34014]
**Description**

I cannot installer docker on Ubuntu 17.04, using the https://get.docker.com method. It fails with 
```
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-07-07 17:10:13 UTC; 3ms ago
     Docs: https://docs.docker.com
  Process: 23722 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 23722 (code=exited, status=1/FAILURE)

Jul 07 17:10:13 systemd[1]: Failed to start Docker Application Container Engine.
```

And running `journalctl -xe` gives: 

```
Jul 07 17:10:21 applebetas sshd[23570]: Failed password for root from 59.63.188.3 port 40497 ssh2
Jul 07 17:10:21 applebetas sshd[23570]: error: maximum authentication attempts exceeded for root from 59.63.188.3 port 40497 ssh2 [preauth]
Jul 07 17:10:21 applebetas sshd[23570]: Disconnecting: Too many authentication failures [preauth]
Jul 07 17:10:21 applebetas sshd[23570]: PAM 5 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost= user=root
Jul 07 17:10:21 applebetas sshd[23570]: PAM service(sshd) ignoring max retries; 6 > 3
```

**Steps to reproduce the issue:**
1. Installer docker on ubuntu 17.04

**Describe the results you received:**

Docker does not install.

**Describe the results you expected:**

Docker installs. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VPS hosted on OVH

**Comment by thaJeztah** [comment]
These messages are from `sshd`, and indicate someone attempted to log in to your server using SSH, I don't see what the relation would be with docker; the install script does not use `ssh`

Do the logs contain anything for the `docker` service? That's what you should be looking for

**Comment by nullpixel** [comment]
These are inside the docker container, which is what baffled me!

**Comment by thaJeztah** [comment]
Which container? You mention docker doesn't start, so which container are the messages from? What is running in the container?

**Comment by nullpixel** [comment]
Oh, sorry. It was late and I didn't read the errors right. Yeah, it errors on install, but not with the output I posted - I pasted the wrong thing, which I guess is why you got confused.

I'll update the errors later.

**Comment by nullpixel** [comment]
Fixed it now -- had an outdated kernel, although docker did not make it obvious

**Comment by thaJeztah** [comment]
Good to hear! Ah, yes I think we had issues before with the custom kernels that OVH uses :disappointed:

**Comment by nullpixel** [comment]
Yeah, it was a pain to update
