### ISSUE TITLE
Swarm: overlay network encryption degradation from 17.03.1-ce-aws1 to 17.06.0-ce-aws1

### ISSUE THREAD

**Issue by ValeryNo** [moby/moby#34015]
**Description**

We use multiple Docker Swarm clusters and doing weekly updates.
A week ago we provisioned a new cluster using same method like before )docker swarm aws cloud formation template) and started facing connectivity issues between containers on this particular cluster.

_Working cluster versions:_
Docker for AWS 1.13.0 (1)
Docker for AWS 17.03.1-ce-aws1

_Broken:_
Stable: Docker CE for AWS 17.06.0-ce (17.06.0-ce-aws1)
Beta: Docker CE for AWS 17.06.0-ce-rc5 (17.06.0-ce-rc5-aws1)

Our containers execute ```nc -z "$HOST" "$PORT"``` commands for all dependencies on a startup and those commands started randomly hanging without ever returning results even when dependency is successfully running.

The problem is floating. Different containers are not being resolved every time we try to re-deploy. One time it can be web server not being able to access port of redis, another time proxy server can't see web ui server etc. We have total of 13 services and it's enough to trigger that problem every single time we tried to deploy (over 20 attempts in last week)

In our setup we have 3 overlay networks backend, frontend and auth with multiple services attached to them. 

The issue is resolved if:
1. I completely remove those networks from compose file
or 
2. Turn off encryption option on those networks

**Steps to reproduce the issue:**
1. Define a complex docker compose file with a lot of services, let's say 10+
2. Define a few overlay networks with encryption on:
Example:
```
networks:
  frontend:
    driver: overlay
    driver_opts:
      encrypted: "true"
  backend:
    driver: overlay
    driver_opts:
      encrypted: "true"
  auth-private:
    driver: overlay
    driver_opts:
      encrypted: "true"
```
3. Assign those networks to different services. Make some using multiple networks.
4. Provision AWS Swarm cluster using latest stable or beta cloud formation scripts
5. Deploy docker stack from compose file on the cluster
6. Login into a few containers and try to see if other containers are accessible by their designated ports via ```nc -z "$HOST" "$PORT"``` command. Or you can use curl / wget

**Describe the results you received:**
DNS names of other services are being resolved fine, but some services attached to the same network are inaccessible though nc/curl/wget. Which ones is inconsistent. On some deployment it happens only between 2 containers, in some to 4+.

It was working fine in 17.03.1-ce-aws1

We started having problems only after provisioning a new cluster with 17.06.0-ce-aws1. Same issue in latest beta - 17.06.0-ce-rc5-aws1

**Describe the results you expected:**
Consistent connectivity between containers on the same network is expected. All containers on the same network should be able to access others through their published ports.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue is resolved if we turn off docker's networks encryption or only use default overlay networks without defining our own & attaching services to them.

**Output of `docker version`:**
We also tried on stable 17.06.0-ce-aws1
```
Client:
 Version:      17.06.0-ce-rc5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:09:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc5
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:18:21 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.06.0-ce-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: x4608q7nul0ufdtl7711e6c0i
 Is Manager: true
 ClusterID: xgxnhdj7q8ilbbgdz12p91i10
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.31.33.142
 Manager Addresses:
  172.31.33.142:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951GiB
Name: ip-172-31-33-142.us-west-2.compute.internal
ID: XG33:VJES:UK54:SSFY:Z5DG:M5V6:JTHT:V4VU:E3BZ:3V6L:5R2F:HNCQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 155
 Goroutines: 282
 System Time: 2017-07-07T17:27:37.288124626Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=us-west-2
 availability_zone=us-west-2c
 instance_type=t2.small
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS.
Our base docker images have not changed in last couple of months. So the version of base docker containers is not likely a problem.

**Comment by ValeryNo** [comment]
We have 5 clusters, 4 of which work fine (<= 17.03.1-ce-aws1) and 1 of them (on the newer version) has 100% reproducing rate for this problem. 

I realize that this issue could be a tough one to reproduce by a synthetic test and totally open to give access to show this issue in our test environment. We have implemented scripts which run before main app inside of container starts and validates that other services which a starting application depends on are up and running. That makes it much easier to see when such problem occur.

**Comment by thaJeztah** [comment]
thanks for reporting; is there anything in the logs that could provide some more details?

ping @kencochrane @fcrisciani PTAL

**Comment by kencochrane** [comment]
@ValeryNo thanks for the report.

I wonder if it is something in the 17.06 engine or something with changes we made with docker for aws. It seems like it is might be an engine problem, but not 100% sure yet.

Any way to test with docker for aws 17.05 and 17.04 to see if the problem is present in those versions? This will help us track down where the problem was introduced, and narrow down the scope a bit.

**17.05 template:**
http://editions-us-east-1.s3.amazonaws.com/aws/edge/17.05.0/Docker.tmpl

**17.04 template:**
http://editions-us-east-1.s3.amazonaws.com/aws/edge/17.04.0/Docker.tmpl

/cc @mavenugo

**Comment by sanimej** [comment]
@kencochrane Is there a kernel version change in docker for aws between 17.03 and 17.06 ?

Between kernel versions 4.4 and 4.8 there seems to be a regression in the IPSec encryption performance, https://github.com/moby/moby/issues/33133#issuecomment-303314026

**Comment by kencochrane** [comment]
Kernel is 4.9.31

**Comment by siavash9000** [comment]
I have the same problem with the generic driver on Scaleways virtual servers. After a docker update to 17.06.0-ce several services do not find each other anymore, which breaks my application. Some services can be found, but for example my central mongodb instance is not found anymore.

**Comment by siavash9000** [comment]
The problem exists in the last 3 docker releaes. I could work around the problem by avoiding to place services on nodes explicitly by using hostnames, like this:

```
myservice:
image: myimage:latest
deploy:
      placement:
        constraints:
          - "node.hostname == node4"
```

I did placed multiple services like mongodb on fixed nodes of the cluster to ease the mgmt. of the data volumes for the moment. Dont know why but this caused somehow problems with the reachability  of services in the swarm.

**Comment by madmax88** [comment]
On Docker for AWS 17.06 I have this issue.

I've done some debugging, because I thought that this could be related to my setup. Since I am running an identical compose file on a single-node cluster without issues, I believe that this is a bug. What I've found is that:
(1) NSLookup succeeds between services, even if they can't connect
(2) Services running on *some* hosts _are_ able to connect to others
(3) On the hosts where services aren't able to connect, a traceroute call to the other services times out. On the hosts where services do connect, traceroute does 1 hop
(4) This problem usually happens to workers. I haven't observed it yet with managers. Even if no other worker can connect to a service running on another worker, a manager has been able to. 

If you all need more information about this, I'd be happy to help.

**Comment by ddingel** [comment]
IIUC my issue [swarm overlay network connection loss](https://github.com/moby/moby/issues/34549) might be related to this one. As soon as I encrypt the overlay network I measure connection loss with my jmeter configuration.

That is with 17.06 on VMWare with centos 7.3 and the centos kernel.
I will try to reproduce this issue with docker 17.03.

**Comment by ddingel** [comment]
Within an additional environment I am able to reproduce this issue for:
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

as well as for:
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by FrenchBen** [comment]
@ddingel are you able to share the compose file that you used to replicate the issue?

**Comment by ddingel** [comment]
@FrenchBen sure:
*with encryption* 
```
version: '3.0'

networks:
  default:
    driver_opts:
      encrypted: 'true'

services:
  nginx:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: nginx

  jmeter:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: myJmeter
```
*without encryption*:
```
version: '3.0'

networks:
  default:

services:
  nginx:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: nginx

  jmeter:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: myJmeter
```

I posted the Dockerfile and JMeter configuration in the other issue.

**Comment by ddingel** [comment]
Holy Kernel Update. Just for fun I tried to reproduce my issue with ubuntu 16.04.3 and the latest centos, and failed.
So in between 3.10.0-327.4.5.el7.x86_64 and 3.10.0-514.10.2.el7.x86_64 is a bug fix, which fixes this bug, at least for me. The kernel.spec also indicates that such bug fix was backported.

**Comment by justincormack** [comment]
@ddingel have you got a link to the spec change? Will help to be able to see which commit this was in case other kernels get the issue.

Will close as resolved upstream; anyone seeing this issue should upgrade their kernel...

**Comment by ddingel** [comment]
@justincormack not sure if the initial issue is based on a kernel bug as well, as they used a 4.9 kernel...

So here is the centos kernel spec https://git.centos.org/blob/rpms!kernel.git/bd67aeec633a0686d3b9458cc46e29034505caca/SPECS!kernel.spec
If you prefer raw: https://raw.githubusercontent.com/clearos/kernel/clear7/SPECS/kernel.spec

You can take a look at the changes between
* Thu Oct 29 2015 Rafael Aquini <aquini@redhat.com> [3.10.0-327.el7]
and
* Mon Jan 30 2017 Frantisek Hrbata <fhrbata@hrbata.com> [3.10.0-514.10.1.el7]

Grepping for xfrm might leading into the right area.
