### ISSUE TITLE
Wiki page for Moby Project Summit Resources

### ISSUE THREAD

**Issue by abinashmeher999** [moby/moby#34024]
Recently I stumbled upon https://europe-2017.dockercon.com/moby-project-summit/ webpage.

The talks mentioned in the section **'Past sessions from the Moby Project summit'** can serve as excellent starting points for people looking to dive deep into the architecture in order to contribute. When I was looking through the repo I couldn't find any wiki pages with resources like these. It would be great to have a wiki page that lists the past talks in Moby Project Summit and also is kept upto date with the future talks.

Can I go ahead and create one?

**Comment by thaJeztah** [comment]
This (moby/moby) repository is just one of the components of the Moby project, so I wonder if it's the best place for this.

We could create a section on the website, and there's the forums of course; pull requests for the website can be opened in this repo https://github.com/moby/mobywebsite

ping @vieux @chanezon wdyt?

**Comment by chanezon** [comment]
@thaJeztah @vieux yes we should definitely use the website for that.
@abinashmeher999 you can find detailed reports on the first 2 Moby summits on the Moby blog, which is part of the website: https://github.com/moby/mobywebsite/blob/master/docs/blog/_posts/2017-06-26-moby-summit-recap.md and https://github.com/moby/mobywebsite/blob/master/docs/blog/_posts/2017-05-11-moby-summit-report.md
It would make sense to maybe create a page on Moby website with links to these reports. PRs are welcome:-)

**Comment by thaJeztah** [comment]
Let me close the issue here; but feel free to continue the discussion; if you need more information, don't hesitate to ping me on the Docker Community Slack

**Comment by abinashmeher999** [comment]
@thaJeztah @chanezon 
Thanks for the links and the pointers! I will continue this on the mobywebsite repo then.

**Comment by thaJeztah** [comment]
Perfect, thanks!

**Comment by chanezon** [comment]
@abinashmeher999 I created the page on the website, now you can send PRs for the next summit agenda:-)

https://github.com/moby/mobywebsite/commit/5f9b39c311b0835179ee7684c1e16fa6fa62f14b

**Comment by abinashmeher999** [comment]
@chanezon I wondering how to structure all the links. This helps. Thanks again! 😄
