### ISSUE TITLE
Provide a way for volume plugins to set/change labels on a volume.

### ISSUE THREAD

**Issue by taherv** [moby/moby#34025]
Currently, `docker volume create` supports setting of arbitrary metdata (called labels) on a docker volume. It would be nice if a volume plugin could (during the creation process) be able to return a set of labels that can be set on the volume.

Use case  

1. Docker volume users can use any set of "options" during `docker volume create`. Some of these options may have featuresets enabled on a volume (e.g. -o encrypt=true). Others might have configuration (e.g. -o mirrored-copies=3). Later in the volume lifecycle, it helps to see what bells-and-whistles are enabled. Labels are a nice way to see this, if a plugin can set them. Without that, users either have to set labels on their own or record their `docker volume create` options somewhere to recall.

2. Docker storage API is not there yet, but plugin vendors already support snapshots. Labels that highlight volume relationships are another use case (.e.g Labels that highlight volumeA was a snapshot of volumeB). Again, users can set these manually, but it is just one more step a human has to do, and can be error prone !

**Comment by taherv** [comment]
The proposal is to add more metadata in the response to "VolumeDriver.Create" and then percolating that metadata via a "Labels()" method volume.Volume interface. Finally, in VolumeStore::create, fetching the labels from volume.Volume and shoving it in volume.volumeMetaData. The last step is where user specified labels and plugin's labels would be merged.

**Comment by taherv** [comment]
@tiborvass pinging you for your thoughts.

**Comment by cpuguy83** [comment]
Plugins already have a way to return arbitrary data about a particular volume, and options are already stored and output the the user.

I don't think we need to allow this change.

**Comment by taherv** [comment]
>> return arbitrary data.
Do you mean the "Status" field in the Get API ?

Thanks for your prompt response !

**Comment by cpuguy83** [comment]
> Do you mean the "Status" field in the Get API ?

Yep

**Comment by taherv** [comment]
Kinda agree with @cpuguy83 although I still think "labels" are better from usability standpoint.
Closing this issue ...
