### ISSUE TITLE
Child process standard out logging weird behavior

### ISSUE THREAD

**Issue by shaunwarman** [moby/moby#34026]
**Description**
https://github.com/shaunwarman/docker-child-proc

I have a simple nodejs script that spawns a child process and runs `ping google.com`. If I run this locally outside of container it runs fine with expected stdout logging every second or so. Within the container it seems the child pid logs standard output maybe once a minute or so.

**Steps to reproduce the issue:**
https://github.com/shaunwarman/docker-child-proc

**Describe the results you received:**
Common `ping` output every second.

**Describe the results you expected:**
`stdout` from child process is happening about once every minute.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 181
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: BIDK:ZIOT:7HVA:RVXM:R4BW:YZ5A:BN3T:W42W:YTCW:3ULS:CGM2:CWDD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 39
 System Time: 2017-07-08T23:22:58.461423036Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Did you resolve your issue?

**Comment by shaunwarman** [comment]
FWIW it seems to be docker-node related. Here's some additional info via strace if you want to take a peek. Maybe you have an idea?
https://github.com/nodejs/docker-node/issues/453

**Comment by WorldofDataScience** [comment]
Any progress on this? I am trying to run:

// call any python scripts
var spawn = require("child_process").spawn;
var process = spawn("python",["test.py", function_args]);

process.stdout.on("data", function (data){
.....

But process.stdout.on will not run. It seems like Docker cannot pick up any output that is written to stdout.

**Comment by shaunwarman** [comment]
AFAIK, it was specific to [`nodejs`](https://github.com/nodejs/docker-node) images. Looks like no follow up in https://github.com/nodejs/docker-node/issues/453 - using [alpine-node](https://github.com/mhart/alpine-node) related images or creating your own with whatever base image should work fine.
