### ISSUE TITLE
Swarm overlay network fails on startup for one node

### ISSUE THREAD

**Issue by drnybble** [moby/moby#34039]
**Description**

I have built a 3 node swarm cluster as follows:
m1 - Centos VM
m2 - docker:dind container
m3 - docker:dind container

The containers have static IP addresses.

So note that m2 and m3 are configured the same. I restarted my Centos VM and found that the container on m3 was not able to talk to the container on m2.

m2 container's IP: 10.0.0.3; VIP: 10.0.0.4
m3 container's IP: 10.0.0.5; VIP: 10.0.0.6

From m2 I can ping m3's IP or VIP
From m3 I can ping m2's IP but NOT its VIP
I get the error:
root@cockroachdb-3:/cockroach# ping 10.0.0.4
PING 10.0.0.4 (10.0.0.4): 56 data bytes
92 bytes from cockroachdb-3 (10.0.0.5): Destination Host Unreachable

**Steps to reproduce the issue:**
Not sure other than I restarted my swarm.

**Describe the results you received:**
Traffic routing appears to have failed but only in one direction (m3 -> m2).

**Describe the results you expected:**
Swarm starts up and networking works.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: y26ve4afofzbzzqdsv6z71r54
 Is Manager: false
 Node Address: 172.20.0.103
 Manager Addresses:
  172.20.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Alpine Linux v3.6 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: m3
ID: 4UEE:RGNQ:MKWX:GCSD:ZRBV:LDOF:54BM:4YRZ:EMVN:H7NS:KJXC:QTH4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 7 VM running under VirtualBox.
Swarm built using this and two docker:dind containers (slightly customized to rm -f /var/run/docker.pid and /var/run/docker/libcontainerd/docker-containerd.pid in the dockerd-entrypoint.sh file so it will start up properly -- would be nice if dind included this!!).

I will leave my VM in this condition, please let me know what further diagnostics or information I should collect.

**Comment by cpuguy83** [comment]
ping @sanimej

**Comment by omerh** [comment]
I'm am having a similar issue with overly network connectivity.
All is running on Ubuntu 16.04

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
