### ISSUE TITLE
recommendation docker system prune not interactive

### ISSUE THREAD

**Issue by lanmingle** [moby/moby#34037]
ci pipeline eg : 

docker build -t xxx-cache

docker build --cache-from xxx-cache --squash -t xxx

docker system prune -y 

or

docker image prune -y

**Comment by cpuguy83** [comment]
Does `docker system prune --force` do what you need?

**Comment by cpuguy83** [comment]
Closing because we already have an option for non-interactive, but please feel free to comment if you think this is not enough.

Thanks!
