### ISSUE TITLE
Update builder.md to state that the first instruction does not have to be a FROM

### ISSUE THREAD

**Issue by rcjsuen** [moby/moby#34031]
At the moment, the Dockerfile reference states the following:

> A Dockerfile must start with a `FROM` instruction.

However, this has since been changed because:

> FROM instructions support variables that are declared by any ARG instructions that occur before the first FROM.

The `docs/reference/builder.md` file should be updated to reflect this change.

**Comment by thaJeztah** [comment]
I think this is mentioned (looking at [docs/reference/builder.md](https://github.com/docker/cli/blob/4f3a8aecad56cf27191004b40aa2cd6a42fc9ce6/docs/reference/builder.md));

```markdown
The `FROM` instruction initializes a new build stage and sets the 
[*Base Image*](glossary.md#base-image) for subsequent instructions. As such, a 
valid `Dockerfile` must start with a `FROM` instruction. The image can be
any valid image – it is especially easy to start by **pulling an image** from 
the [*Public Repositories*](https://docs.docker.com/engine/tutorials/dockerrepos/).

- `ARG` is the only instruction that may precede `FROM` in the `Dockerfile`.
  See [Understand how ARG and FROM interact](#understand-how-arg-and-from-interact).
```

and

```markdown
Docker runs instructions in a `Dockerfile` in order. A `Dockerfile` **must
start with a \`FROM\` instruction**. The `FROM` instruction specifies the [*Base
Image*](glossary.md#base-image) from which you are building. `FROM` may only be
preceded by one or more `ARG` instructions, which declare arguments that are used
in `FROM` lines in the `Dockerfile`.
```

But perhaps the wording can be improved; if you have suggestions, would you be interested in opening a pull request in the docker/cli repository? The file is located here; https://github.com/docker/cli/blob/master/docs/reference/builder.md

**Comment by rcjsuen** [comment]
You are right, it is indeed mentioned. I don't know how I overlooked this.

Sorry for the bother. :(
