### ISSUE TITLE
docker stack deploy --compose-file /dev/stdin is broken in 17.06

### ISSUE THREAD

**Issue by mmariani** [moby/moby#34036]
Hello,

I find it useful to render my stack specification files from templates, therefore I deploy them with:

`p2 -t stack.yml | docker stack deploy --with-registry-auth --prune --compose-file /dev/stdin stackname
`

With the release of 17.06, I noticed that Docker subsequently looks for files in /dev/:

`open /dev/config.monitoring: no such file or directory
`

Now, I am aware that this may be the right thing to do - look for relative paths from the compose file location - but I'd like a way to provide it as standard input.

Would a PR to implement "--compose-file -" be accepted ?

Thanks

**Comment by AkihiroSuda** [comment]
I think this proposal should be moved to https://github.com/docker/cli, as stack is implemented on CLI side.
I'd suggest using "-" for stdin (as in `docker build -`)

**Comment by thaJeztah** [comment]
ping @dnephin

**Comment by dnephin** [comment]
Yes, `--compile-file -` would be great. Thanks

**Comment by thaJeztah** [comment]
This was implemented in https://github.com/docker/cli/pull/347,  and should be part of docker 17.09 and up
