### ISSUE TITLE
Can´t specify memory limit in docker run and docker compose

### ISSUE THREAD

**Issue by simonkulessa** [moby/moby#34046]
Hi there,

when trying to start a container via:

docker run --name nginx-test -d -m 1g nginx (or -m 1024000000 etc..)

and when starting with docker-compose (with mem_limit option, the same config works on ubuntu 16.04) 

I get the following error:

docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"\"".

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 25
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-53369346-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.405GB
 Data Space Total: 107.4GB
 Data Space Available: 8.176GB
 Metadata Space Used: 2.552MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64GiB
Name: vm61105.psmanaged.com
ID: ZA2I:YTG3:5A6V:6WHG:TR6Q:Z632:BBNK:ZXB2:IO3D:UFTU:EMEG:GDH7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 (latest) virtual machine in VMWare Cloud environment.

I couldn´t find anything on google  - maybe this is a known issue?

Regards
Simon

**Comment by cpuguy83** [comment]
Hello, this is a known issue on 17.06 due to a bug in the older centos kernel. This should be cleared up if you update to the latest patch level (`-514`).

Alternatively we will also be releasing a fix with 17.06.1 (https://github.com/docker/docker-ce/pull/102)

**Comment by simonkulessa** [comment]
Hello,
thanks for your quick answer - just updated the kernel to -514 and it works. I´m quite ashamed, that I didn´t find this :(

**Comment by cpuguy83** [comment]
No worries, we definitely broke something in 17.06!

**Comment by brucejee** [comment]
I also met this problem, kernel version is not 3.10.0-514.el7.x86_64, and fix with sudo yum update kernel.
You can use this command to test:
[root@mesos-node1 ~]# docker run -itd --name test1 nginx
It output container id.
[root@mesos-node1 ~]# docker run -itd --name test2 -m 20m nginx
This command output error message as follows:
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"read init-p: connection reset by peer\"".

Docker version 17.07.0-ce, build 8784753
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)

**Comment by cpuguy83** [comment]
ping @tiborvass Did 17.07 get the updated runc? Was this conn reset error one that we saw?

**Comment by cpuguy83** [comment]
@brucejee At this point, it'd be good to start up a new issue as it may be unrelated and this one is already closed for awhile.

Thanks!

**Comment by brucejee** [comment]
@cpuguy83 ok，I will open an new issue for tracking this problem.
