### ISSUE TITLE
contrib/completion/bash/docker removed

### ISSUE THREAD

**Issue by Tha-Robert** [moby/moby#34041]
**Description**
The file: contrib/completion/bash/docker has been removed and is used by alot of scripting in cloud environments to enable docker completion.

Like in CoreOS setup:
<code>
toolbox dnf -y install bash-completion wget && toolbox wget 
  https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker -O 
  /usr/share/bash-completion/completions/docker && toolbox cp /usr/share/bash-completion 
  /media/root/var/ -R && source /var/bash-completion/bash_completion
</code>
Its also used and referred to in some of the files still in the repo like:
hack/make/.build-deb/docker-engine.bash-completion

**Steps to reproduce the issue:**
`wget https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker` 

**Describe the results you received:**
File not there!

**Describe the results you expected:**
File should be there :)

**Additional information you deem important (e.g. issue happens only occasionally):**
NA

**Output of `docker version`:**
NA

**Output of `docker info`:**
NA

**Additional environment details (AWS, VirtualBox, physical, etc.):**
NA

**Comment by cpuguy83** [comment]
The scripts now live in https://github.com/docker/cli/tree/master/contrib/completion

Thanks!

**Comment by Tha-Robert** [comment]
Thx alot!
Name changes ftw ;-)

Just remember to remove or update the references in this git also to reflect the change.

//R

**Comment by thaJeztah** [comment]
It's also best to pin the script to use the same version as the docker version installed, for example, using the 17.03.2-ce tag, would have prevented the script from breaking; https://raw.githubusercontent.com/moby/moby/v17.03.2-ce/contrib/completion/bash/docker

If you install from the `.deb` or `.rpm` packages, the completion scripts are included, and already installed
