### ISSUE TITLE
[question] Is it duplicated that network has both destroy and remove events?

### ISSUE THREAD

**Issue by allencloud** [moby/moby#34054]
Hi, All, 

I found that in docker-17.06, we have two kinds of events when we remove a network.

`remove` and `destroy` are both events for network, the previous one is for legacy network removal and the latter one is for swarm scope network removal which is introduce in PR https://github.com/moby/moby/pull/32421

I think it is duplicate for us to have `remove` and `destroy`. Does anybody else keep the same opinion?

@dongluochen @aaronlehmann @thaJeztah @vdemeester

**Comment by thaJeztah** [comment]
ping @fcrisciani @sanimej PTAL

**Comment by allencloud** [comment]
and friendly ping @fcrisciani @sanimej again. ☀️ 🍉

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
