### ISSUE TITLE
The Amazon CloudFront distribution is configured to block access from your country

### ISSUE THREAD

**Issue by ArthurArslanaliev** [moby/moby#34058]
We are having issue with downloading Docker distribution from our Kiev (Ukraine) office. It says that "The Amazon CloudFront distribution is configured to block access from your country". 

Link: https://download.docker.com/linux/ubuntu/gpg

<img width="304" alt="screen shot 2017-07-11 at 16 36 43" src="https://user-images.githubusercontent.com/4873282/28070916-26d508aa-6657-11e7-8310-30b41a0e1e9c.png">

Was that an intentional change? Could someone elaborate on this?

Thanks in advance.

**Comment by Ed-88** [comment]
curl -I https://download.docker.com
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Tue, 11 Jul 2017 13:40:14 GMT
Content-Type: text/html
Content-Length: 622
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 b0c1028ac1da2bf7c9c2147888569a4f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: Aa3ZpgWVEOhSsRZVA232fedAdOg25B7BXb3TSLw6jIgsvoqime15vA==

**Comment by excieve** [comment]
Same trouble here, also when accessing anything on `download.docker.com` from Ukraine.

**Comment by WriterIP** [comment]
same one

**Comment by dchaplinsky** [comment]
Same here

**Comment by syadykin** [comment]
+1

**Comment by thaJeztah** [comment]
This is an issue with Docker's infrastructure, and unrelated to the open source project, please discuss on https://github.com/docker/for-linux/issues/57. I'll close and lock the discussion here to prevent the discussion from diverging
