### ISSUE TITLE
download.docker.com forbidden from Ukraine

### ISSUE THREAD

**Issue by uriinf** [moby/moby#34052]
Hi,
look the subject.
```bash
curl -I https://download.docker.com/
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Tue, 11 Jul 2017 09:01:59 GMT
Content-Type: text/html
Content-Length: 622
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 5b83b7f41cf6a5b3815ee5eeddf3bdae.cloudfront.net (CloudFront)
X-Amz-Cf-Id: uZfjL9tMbZEFjXcrPpHvtTtijws9eL9Kf6so2YDAb16sQZ7itmqTNA==
```
[http://r.h-t.co/en/1/78f998e8-1666-e711-9125-0003ff73517a
![screenshot from 2017-07-11 12-04-32](https://user-images.githubusercontent.com/18531314/28060856-3126db4c-6631-11e7-82bc-950b5dc40487.png)
](url)

**Comment by ujenmr** [comment]
I have same issue 
test-kitchen output:
```
       ca-certificates is already the newest version (20160104ubuntu1).
       apt-transport-https is already the newest version (1.2.20).
       curl is already the newest version (7.47.0-1ubuntu2.2).
       software-properties-common is already the newest version (0.96.20.7).
       0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
       STDERR: + sh -c apt-get update
       + sh -c apt-get install -y -q apt-transport-https ca-certificates curl software-properties-common
       + sh -c apt-key add -
       + curl -fsSl https://download.docker.com/linux/ubuntu/gpg
       curl: (22) The requested URL returned error: 403 Forbidden
       gpg: no valid OpenPGP data found.
       ---- End output of curl -sSL https://get.docker.com/ | sh ----
       Ran curl -sSL https://get.docker.com/ | sh returned 2
       [2017-07-11T09:02:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-07-11T09:02:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by romulko** [comment]
as a workaround, you can use a proxy site to access content - https://www.proxysite.com/

**Comment by justincormack** [comment]
Closing this as unrelated to the open source project, please discuss on https://github.com/docker/for-linux/issues/57

**Comment by illucent** [comment]
"false positive" -  I've installed docker-ce today successfully from Ukraine 
```
curl -I https://download.docker.com
HTTP/2 200 
content-type: text/html
content-length: 395
date: Sun, 09 Jul 2017 15:10:50 GMT
last-modified: Thu, 08 Jun 2017 23:16:26 GMT
x-amz-version-id: Tefd8BW3.oQMm4QJo6vf7NEy7pnRXnw3
etag: "3ebc781f7e64be45c7c3cc72def5f85d"
server: AmazonS3
x-cache: RefreshHit from cloudfront
via: 1.1 1617f8bb348c173b7002e26d4d35f91a.cloudfront.net (CloudFront)
x-amz-cf-id: cjj_C8oXqqN46ftGrn6cKzAbnLkahhMFeaC-gSsmpKExLhiM6887KQ==
```

**Comment by SirEdvin** [comment]
@illucent Well, I still have issue

**Comment by illucent** [comment]
from Ukraine 100% (volia ISP) and firewall enabled (i mean some ports and protocols are blocked and/or filtered)

**Comment by Ed-88** [comment]
curl -I https://download.docker.com
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Tue, 11 Jul 2017 13:40:14 GMT
Content-Type: text/html
Content-Length: 622
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 b0c1028ac1da2bf7c9c2147888569a4f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: Aa3ZpgWVEOhSsRZVA232fedAdOg25B7BXb3TSLw6jIgsvoqime15vA==

**Comment by 31H0B1eV** [comment]
curl -I https://download.docker.com
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Tue, 11 Jul 2017 14:48:57 GMT
Content-Type: text/html
Content-Length: 622
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 017ee4b2e5ba6b7a7dd1443f39b6e832.cloudfront.net (CloudFront)
X-Amz-Cf-Id: ocoqImTl3CgMdQX8--Eh3H-jINAyYyq402u8mwfT1w_1n-LkJpIApA==

**Comment by thaJeztah** [comment]
please continue in https://github.com/docker/for-linux/issues/57, not here 

 https://github.com/moby/moby/issues/34052#issuecomment-314426890
