### ISSUE TITLE
ERROR: for web Cannot start service web: oci runtime error: container_linux.go:262: starting container process caused exec: \"run.sh\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by Barukimang** [moby/moby#34059]
**Description**
After succesfully creating a build using Docker Quickstart Terminal on Windows 10 Home Edition, it doesn't run using the docker-compose up command. Docker cannot find run.sh while there are two of these files in the image. Thought it might have to do with line-endings, so changed these files from Windows to Unix endings, but that did not help. Your help is appreciated!

**Comment by matthewharwood** [comment]
First time user of docker and getting this same problem.
Windows 10
Version 17.06.2-ce-win27 (13194)
Channel: stable
428bd6c

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
