### ISSUE TITLE
Cannot change default storage size

### ISSUE THREAD

**Issue by RustyCZ** [moby/moby#34074]
On Windows 10 I tried to change the default storage size of containers by configuring daemon.json and adding an option "storage-opts": ["size=50G"]. This does not have any effect. 

When I execute `docker run microsoft/nanoserver powershell -c get-psdrive` I would expect to have a C drive with 50G instead it has default 20G. When I specify storage-opt for individual docker run it works. However this is not a solution for me because I need to have more disk space during a build process.

docker version:
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false

**Comment by darrenstahlmsft** [comment]
#dibs
