### ISSUE TITLE
Problem with configure the docker storage driver based on docker docs

### ISSUE THREAD

**Issue by AgainstWind** [moby/moby#34075]
i want to change the devicemapper from loop-lvm to direct-lvm.
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/
--------------------------------------------------------------------------------------------------------
my env: centos7.3, docker 1.12.6
configuration procedure:
```
#!/bin/bash
## allocation a independent disk "/dev/vdb" for  docker
dev_name='/dev/vdb'
yum -y -q install lvm2
echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
pvcreate ${dev_name}
vgcreate docker ${dev_name}
lvcreate --wipesignatures y -n thinpool docker -l 95%VG
lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
cat <<'_EOF' >/etc/lvm/profile/docker-thinpool.profile
activation {
    thin_pool_autoextend_threshold=80
    thin_pool_autoextend_percent=20
}
_EOF
lvchange --metadataprofile docker-thinpool docker/thinpool
echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
lvs -o+seg_monitor
echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
cat <<'_EOF'
```

```
# mkdir /var/lib/docker.bk
# mv /var/lib/docker/* /var/lib/docker.bk
# vim /etc/docker/daemon.json
{
    "storage-driver": "devicemapper",
    "storage-opts": [
        "dm.thinpooldev=/dev/mapper/docker-thinpool",
        "dm.use_deferred_removal=true",
        "dm.use_deferred_deletion=true"
    ]
}
```

```
[root@localhost ~]# systemctl daemon-reload && systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[root@localhost ~]# journalctl -xe
Jul 13 20:25:03 localhost systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Jul 13 20:25:03 localhost dockerd-current[38532]: time="2017-07-13T20:25:03.605643841+08:00" level=info msg="l
Jul 13 20:25:04 localhost dockerd-current[38532]: time="2017-07-13T20:25:04.627276988+08:00" level=fatal msg="
Jul 13 20:25:04 localhost systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 13 20:25:04 localhost systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Jul 13 20:25:04 localhost systemd[1]: Dependency failed for Run docker-cleanup every hour.
-- Subject: Unit docker-cleanup.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker-cleanup.timer has failed.
-- 
-- The result is dependency.
Jul 13 20:25:04 localhost systemd[1]: Job docker-cleanup.timer/start failed with result 'dependency'.
Jul 13 20:25:04 localhost systemd[1]: Unit docker.service entered failed state.
Jul 13 20:25:04 localhost systemd[1]: docker.service failed.
Jul 13 20:25:04 localhost polkitd[10734]: Unregistered Authentication Agent for unix-process:38493:743339 (sys
```

**Comment by cpuguy83** [comment]
I hope you don't mind, I've updated your comment for readability.

**Comment by cpuguy83** [comment]
Can you please provide the logs from the docker daemon? `journalctl -fu docker`

**Comment by AgainstWind** [comment]
---------------------docker--start--log--------------------------
[root@localhost ~]# journalctl -fu docker
-- Logs begin at Thu 2017-07-13 18:21:10 CST. --
Jul 13 20:25:04 localhost systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 20:25:04 localhost systemd[1]: Unit docker.service entered failed state.
Jul 13 20:25:04 localhost systemd[1]: docker.service failed.
Jul 14 09:15:57 localhost systemd[1]: Starting Docker Application Container Engine...
Jul 14 09:15:57 localhost dockerd-current[45254]: time="2017-07-14T09:15:57.426490730+08:00" level=info msg="libcontainerd: new containerd process, pid: 45257"
Jul 14 09:15:58 localhost dockerd-current[45254]: time="2017-07-14T09:15:58.459297751+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devmapper: Unknown option dm.directlvm_device\n"
Jul 14 09:15:58 localhost systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 14 09:15:58 localhost systemd[1]: Failed to start Docker Application Container Engine.
Jul 14 09:15:58 localhost systemd[1]: Unit docker.service entered failed state.
Jul 14 09:15:58 localhost systemd[1]: docker.service failed.

**Comment by cpuguy83** [comment]
> "Error starting daemon: error initializing graphdriver: devmapper: Unknown option dm.directlvm_device\n"

This option is only available in 17.06. Is this still in your `/etc/docker/daemon.json`? It wasn't listed above.

**Comment by AgainstWind** [comment]
i firget add ‘dm.directlvm_device’ to daemon.json.
but i have success congfigured the storage driver with docker-storage-up：
`# cat <<EOF > /etc/sysconfig/docker-storage-setup
DEVS=/dev/sdb
VG=docker-vg
EOF`

thank you!

**Comment by cpuguy83** [comment]
Great!
