### ISSUE TITLE
Cannot Start Containers on Windows Server 2016

### ISSUE THREAD

**Issue by ericzhou123** [moby/moby#34079]
**Description**
Docker on my Windows Server 2016 machine cannot start containers. I have tested this for microsoft/aspnet and microsoft/mssql-server-windows. Docker seems to be able to create the containers perfectly fine, but fails to run them. Specifically, docker gives me an error during "docker start" commands. Starting these same images works perfectly fine on my Windows 10 machine.

**Steps to reproduce the issue:**
1. docker pull microsoft/aspnet
2. docker create microsoft/aspnet
3. docker start (container ID)

**Describe the results you received:**
`Error response from daemon: container bd858f0d4448b6428be567c4a2b64b45f7a0e4ac3b479c6beeab757ac191b169 encountered an er
ror during CreateContainer: failure in a Windows system call: Element not found. (0x490) extra info: {"SystemType":"Cont
ainer","Name":"bd858f0d4448b6428be567c4a2b64b45f7a0e4ac3b479c6beeab757ac191b169","Owner":"docker","IsDummy":false,"Volum
ePath":"\\\\?\\Volume{b7983f8c-55bd-11e7-841e-f8b156bc9351}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\Progr
amData\\docker\\windowsfilter\\bd858f0d4448b6428be567c4a2b64b45f7a0e4ac3b479c6beeab757ac191b169","Layers":[{"ID":"b5c8c7
3d-eff3-57c7-bff1-f1d4073bbef7","Path":"C:\\ProgramData\\docker\\windowsfilter\\60d3572c773b1c0dfda2874d367061db6977a14a
060bfc0fdc4e82c915a903ad"},{"ID":"d5bd8536-fb9d-554f-9f6d-5856b9630abc","Path":"C:\\ProgramData\\docker\\windowsfilter\\
b87c6cdf8cfd668a93f739e3463ef70b648d3890950039a05d3fc739df2f793a"},{"ID":"421a3770-2362-5784-9ec0-1dd44d1d4fb9","Path":"
C:\\ProgramData\\docker\\windowsfilter\\d818e7cc446bd289e63a27b1e2e888596debc8cbd8f9fa3fde20af0e34dfad0c"},{"ID":"2fd0b1
ab-382c-5061-b183-caa0c414950c","Path":"C:\\ProgramData\\docker\\windowsfilter\\92864f0984610682ec5266b1cd392703903b0938
d3f56c4e45a41e3e68eba7b3"},{"ID":"edd8c25f-23a4-57f7-9fe4-e4a5b04fb0d3","Path":"C:\\ProgramData\\docker\\windowsfilter\\
f2b3a5ca2b22facbb01d7549cd883a7672049b28eff07b706badcf98decc2810"},{"ID":"ef06bb1f-0c71-55ac-bdef-44478e51eedf","Path":"
C:\\ProgramData\\docker\\windowsfilter\\a4249620176b3d282bdc19762627a0d302cd4f92f7476ef957e2d33ac15e199c"},{"ID":"f23ab4
e6-af41-5b5f-8f44-f3ff2533b3bc","Path":"C:\\ProgramData\\docker\\windowsfilter\\dc033f526af9ed03c4212020ee3700203f2f577b
434ba8abeec3e507e0743d76"},{"ID":"d24edea0-c12b-5b18-9246-16181b747878","Path":"C:\\ProgramData\\docker\\windowsfilter\\
6404acd8d50ed583b2b1583091ddf6e1625eef5786c689397c3061e2bd857e96"},{"ID":"cbddc510-0019-55a5-a73e-e87e75b6a4bb","Path":"
C:\\ProgramData\\docker\\windowsfilter\\aa62fed1812479f863cfd476429ef956730f8f2f42bc46c87e9fa29293494614"}],"HostName":"
bd858f0d4448","MappedDirectories":[],"HvPartition":false,"EndpointList":["2c8836ed-5896-42f0-8ac8-3c3456490eb5"],"Servic
ing":false,"AllowUnqualifiedDNSQuery":true}
Error: failed to start containers: bd`

**Describe the results you expected:**
Container starts

**Additional information you deem important (e.g. issue happens only occasionally)

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 63.95 GiB
Name: slb-hrqzh02
ID: ZPXK:5Q7R:VWH2:URYI:34MF:SXSE:X4KX:W42O:XD76:24HE:H466:2JUL
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Connected to physical Windows Server 2016 machine using remote desktop connection. Installed docker following the instructions from this website: https://docs.docker.com/engine/installation/windows/docker-ee/

**Comment by friism** [comment]
Just out of curiosity, does `docker run microsoft/aspnet` work? It would also be good to know if the host has been modified, for example to disable IPv6 or similar.

**Comment by ericzhou123** [comment]
Thanks for the quick reply! Unfortunately, `docker run microsoft/aspnet` fails with the same error as `docker start`. To my knowledge, the host hasn't been modified, but is there a way I could get you proof of this?

**Comment by ericzhou123** [comment]
Here is additional information about the error event from Computer Management:

"The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

Note: Yesterday I uninstalled and reinstalled docker as an attempted fix to the problem, but there was no effect.

**Comment by jameshcovington** [comment]
any updates on this issue? I'm just getting started with windows containers and am getting the same error on Windows 2016 DataCenter.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
