### ISSUE TITLE
use golang builtin package "context" to replace "golang.org/x/net/context" 

### ISSUE THREAD

**Issue by allencloud** [moby/moby#34090]
Hi, All, 

We know that currently docker can use context to record the context between client and daemon and the execution between functions. This brings lots of value to the project.

While in the code side, I have a proposal that use the builtin package "context" instead of "golang.org/x/net/context". There is reason that package context has been one part of the builtin package of golang runtime, and using it directly could reduce the cost of maintaining external packages.

However, we still need to be aware of the shortcomings, one of them is that the vendored package in moby project, they mostly dependent on the legacy package "golang.org/x/net/context".

**Comment by cpuguy83** [comment]
GRPC still requires x/net/context.

Additionally we have tended to support older go versions for packagers where distros typically have golang 1.6.x only at the moment.
