### ISSUE TITLE
Docker stop doesn't stop the docker container

### ISSUE THREAD

**Issue by rohitsakala** [moby/moby#34097]
<img width="1431" alt="screen shot 2017-07-13 at 11 09 13 pm" src="https://user-images.githubusercontent.com/8402361/28179954-391029d4-6821-11e7-9fb1-da56572830e7.png">
**Description**

Hi,

I issued docker stop command on a container and it didn't stop. It stills shows in the docker ps command. Basically I noticed that the docker-proxy hangs on the port 8082.

**Steps to reproduce the issue:**
1. Run a docker container
2. Stop it using docker stop containerid
3. Run docker ps and it still shows it as running.

**Describe the results you received:**
The docker ps command still shows the container as running.

**Describe the results you expected:**
I would expect the container to close.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:1-35909492-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.935 GB
 Data Space Total: 107.4 GB
 Data Space Available: 60.87 GB
 Metadata Space Used: 8.061 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.305 GiB
Name: gce-opnfv-sandbox-fbrockners
ID: OGTI:EGLD:WHN6:6QZ3:N5AO:OIGL:6VA2:KS4T:EFLF:R54X:6KBE:I635
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
looks like this was opened by accident, so I'll close, but let me know if you're still editing

**Comment by rohitsakala** [comment]
@thaJeztah I edited my issue. Can you please open it ?

**Comment by thaJeztah** [comment]
sure thing!

**Comment by rohitsakala** [comment]
Hi, also please refer to this issue. 
https://github.com/moby/moby/issues/7856.
Especially the comment by  amalaowala. The same error is occuring with me too. The docker-proxy is hanging on the port.

**Comment by allencloud** [comment]
Can you reproduce such kind of situation every time by the sequence you provided? @rohitsakala

**Comment by rohitsakala** [comment]
@allencloud No, not all the time. Only few times like after some 10 days ?every 10 15 days. 

FYI,

My case is very similar to the comment by amalaowala in https://github.com/moby/moby/issues/7856

**Comment by thaJeztah** [comment]
The comment by amalaowala describes the docker _proxy_ to be left around, after the container was removed, that's different from what you're describing

After you tried to stop the container, was the container's process still running, or was the container stopped but still _showing_ as running? i.e.;

If you inspect the container, what does its "state" look like?

```
$ docker inspect -f '{{json .State}}'  my-container

{
  "Status": "running",
  "Running": true,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 2856,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2017-07-15T15:37:56.085838596Z",
  "FinishedAt": "0001-01-01T00:00:00Z"
}
```

Is the container's `pid` still running? 

```bash
ps auxf | grep 2856

2856 root       0:00 nginx: master process nginx -g daemon off;
3629 root       0:00 grep 2856
```


Do the daemon / system logs show anything useful?

**Comment by rohitsakala** [comment]
Hi @thaJeztah , the problem is connected to her comment, as I immediately checked the port on which the container previously bind to. The docker-proxy was still listening on the port. So, I guess because of this the docker stop command didn't work. 

I restarted the docker, so I cannot give more info on that. I faced the problem which amalaowala was mentioning previously also. But since it is repeating, I created an issue here.

**Comment by rohitsakala** [comment]
Hello, any update on this ? 

Thanks :)

**Comment by duraki** [comment]
I'm also getting this on latest stable: `Version 17.09.0-ce-mac35 (19611)`

Inspect:

```sh
$ docker inspect -f '{{json .State}}'  my-container

{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":3354,"ExitCode":0,"Error":"","StartedAt":"2017-10-27T07:47:54.452495051Z","FinishedAt":"207-10-27T07:34:46.554002919Z"}
```

All other containers stopped successfully. The above container is based on nginx image.

Although greping PID was to no avail so it seems background job is completed.

```sh
$ ps aux | grep 3354
```

**Comment by thaJeztah** [comment]
@duraki are you running that on your Mac, or inside the VM where the daemon runs?

**Comment by duraki** [comment]
@thaJeztah 

I'm on Mac without VM so natively. If you need any other info let me know.

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
@duraki Sorry, I wasn't clear: I meant if you tried to run the `ps aux | grep` on your mac, because that process-id is the ID of the process inside the VM, so won't be found on your Mac

**Comment by mkokho** [comment]
hello @thaJeztah 
We do have the same issue. I have debug log from the docker daemon, hope this will clarify some things! Also, it happens quite frequently. If you need more details, please ask.  

0) Issue: `docker stop` does not remove container from the output of `docker ps`
```
[ec2-user@ip-10-205-230-228 ~]$ docker ps | grep 18229deae6a7
18229deae6a7        062294638970.dkr.ecr.ap-southeast-2.amazonaws.com/journey:145              "java -jar app.jar..."   10 hours ago        Up 10 hours         0.0.0.0:32881->8080/tcp, 0.0.0.0:32880->8081/tcp   ecs-dev-journey-101-journey-eee6aaa39cf1f594bc01
[ec2-user@ip-10-205-230-228 ~]$ docker stop 18229deae6a7
18229deae6a7
[ec2-user@ip-10-205-230-228 ~]$ docker ps | grep 18229deae6a7
18229deae6a7        062294638970.dkr.ecr.ap-southeast-2.amazonaws.com/journey:145              "java -jar app.jar..."   10 hours ago        Up 10 hours         0.0.0.0:32881->8080/tcp, 0.0.0.0:32880->8081/tcp   ecs-dev-journey-101-journey-eee6aaa39cf1f594bc01
```

1) I run `docker ps`, here is the output [docker_ps.log](https://github.com/moby/moby/files/1511618/docker_ps.log). Two containers are identical: 551a3d590617 and 18229deae6a7, but the former one replies to http requests, while the later does not. See the ports mapping in the [docker_ps.log](https://github.com/moby/moby/files/1511618/docker_ps.log)
```
[ec2-user@ip-10-205-230-228 ~]$ curl localhost:32883
{"code":404,"message":"HTTP 404 Not Found"}
[ec2-user@ip-10-205-230-228 ~]$ curl localhost:32881
curl: (56) Recv failure: Connection reset by peer
```

2) I run `docker inspect` for both containers: alive container [docker_inspect_551a3d590617.log](https://github.com/moby/moby/files/1511629/docker_inspect_551a3d590617.log), ghost container [docker_inspect_18229deae6a7.log](https://github.com/moby/moby/files/1511630/docker_inspect_18229deae6a7.log). The process for the live container exists, while the process for the ghost container does not exists
```
[ec2-user@ip-10-205-230-228 ~]$ docker inspect -f '{{json .State}}'  551a3d590617
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":28574,"ExitCode":0,"Error":"","StartedAt":"2017-11-28T15:13:58.324505345Z","FinishedAt":"0001-01-01T00:00:00Z"}
[ec2-user@ip-10-205-230-228 ~]$ ps auxf | grep 28574
ec2-user  5532  0.0  0.1 110468  2004 pts/0    S+   09:43   0:00              \_ grep --color=auto 28574
1000     28574  0.2 21.9 2214348 223268 ?      Ssl  04:13   0:41  |       \_ java -jar app.jar server etc/test.yml
[ec2-user@ip-10-205-230-228 ~]$ docker inspect -f '{{json .State}}' 18229deae6a7
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":4977,"ExitCode":0,"Error":"","StartedAt":"2017-11-28T10:26:07.523573265Z","FinishedAt":"0001-01-01T00:00:00Z"}
[ec2-user@ip-10-205-230-228 ~]$ ps auxf | grep 4977
ec2-user 15395  0.0  0.2 110468  2080 pts/0    S+   10:14   0:00              \_ grep --color=auto 4977
```

3) Output of the `docker info`: [docker_info.log](https://github.com/moby/moby/files/1511641/docker_info.log)

4) Debug log of the docker daemon since the beginning of the EC2 instance: [docker.log](https://github.com/moby/moby/files/1511646/docker.log)

**Comment by thaJeztah** [comment]
@mkokho some things that stand out from your `docker info` output;

- Docker CE 17.03.2 is an outdated version of docker; 17.03 reached EOL in July, and is no longer maintained
- Amazon Linux is not a supported distro; I'm aware there are packages for Amazon Linux, but those are built my AWS, and not managed/supported in this repository; opening a ticket with AWS may be the best approach for issues with those packages

**Comment by mkokho** [comment]
thanks @thaJeztah, appreciate your help!

**Comment by shelley2403** [comment]
@mkokho I have the same issue. Were you able to find out what's wrong?

**Comment by duraki** [comment]
@shelley2403 please give us output of the following commands:

`docker info`, `docker logs your-container` (after stop try) & `docker inspect -f '{{json .State}}'  your-container`

**Comment by TomDePauw** [comment]
Hello, we have the same problem. I think its related to disk space running out for a short period.

I am running docker in a vm.

`docker inspect -f '{{json .State}}' da43013cb1b7_da43013cb1b7_airflow_webserver_1
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":7890,"ExitCode":0,"Error":"","StartedAt":"2018-02-02T11:10:38.286341575Z","FinishedAt":"2018-02-02T11:10:36.48694282Z","Health":{"Status":"healthy","FailingStreak":0,"Log":[{"Start":"2018-02-02T06:07:59.045129345-05:00","End":"2018-02-02T06:08:03.117929152-05:00","ExitCode":-1,"Output":"rpc error: code = 14 desc = grpc: the connection is unavailable"},{"Start":"2018-02-02T06:08:33.218817556-05:00","End":"2018-02-02T06:09:04.435619844-05:00","ExitCode":-1,"Output":"Health check exceeded timeout (30s)"},{"Start":"2018-02-02T06:09:39.999299726-05:00","End":"2018-02-02T06:09:53.150565773-05:00","ExitCode":-1,"Output":"rpc error: code = 13 desc = transport is closing"},{"Start":"2018-02-02T06:10:23.347975308-05:00","End":"2018-02-02T06:10:26.947259165-05:00","ExitCode":-1,"Output":"rpc error: code = 14 desc = grpc: the connection is unavailable"},{"Start":"2018-02-02T06:11:08.341467181-05:00","End":"2018-02-02T06:11:09.225563029-05:00","ExitCode":0,"Output":""}]}}`

`docker info
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1000MiB
Name: debian
ID: WIOX:QDCD:KJOJ:U5JP:WBCE:OM3O:NTWR:UCSZ:DNAI:4254:ABJ3:QPO2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support`

**Comment by orodbhen** [comment]
I'm seeing this as well. 

- CentOS 7.5
- Docker 18.03

Using `top -u <container user>` to watch the processes from the host, I see that the processes have all exited, but the container hangs and is finally killed after a timeout of 20 seconds. Even the kill can take an addition 20-30 seconds to complete.

This happens whether I use `docker stop -t 20` or `docker kill -s TERM` and then `docker kill`.

**Comment by thaJeztah** [comment]
That may be expected; if the container's process doesn't handle signals, it won't exit on `SIGTERM`, after which the daemon waits 10 seconds, and forcibly kill the container with `SIGKILL`;

From the documentation;

> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL.

For example; a container running `/bin/sh`;

```
$ docker run -dit --name test busybox
d336ef58834402284369ae1f2202ed991c4781c402bb933111e1259ea2dbe17b
$ bash-4.4$ docker stop test
# after 10+ seconds:
test
```

Logs show this;

```
time="2018-07-13T14:41:38.582612708Z" level=debug msg="Calling POST /v1.37/containers/test/stop"
time="2018-07-13T14:41:38.582715505Z" level=debug msg="Sending kill signal 15 to container d336ef58834402284369ae1f2202ed991c4781c402bb933111e1259ea2dbe17b"
time="2018-07-13T14:41:48.569460835Z" level=info msg="Container d336ef58834402284369ae1f2202ed991c4781c402bb933111e1259ea2dbe17b failed to exit within 10 seconds of signal 15 - using the force"
time="2018-07-13T14:41:48.569546787Z" level=debug msg="Sending kill signal 9 to container d336ef58834402284369ae1f2202ed991c4781c402bb933111e1259ea2dbe17b"
time="2018-07-13T14:41:48Z" level=debug msg="event published" module="containerd/events" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit 
```

**Comment by orodbhen** [comment]
The main container does handle the signal, and successfully stops all processes running in the container.  As noted above, I've set the grace period to 20 seconds, instead the default 10. I tried setting it to 6, though, with no improvement. The container took as much as 1.5 minutes to stop after receiving the KILL signal. All running processes had already stopped, though, so of course the KILL signal would have had no effect. Clearly Docker is doing something else after all processes have exited.

**Comment by thaJeztah** [comment]
What do the daemon logs show (in debug mode)? Not much to tell without more information; if you have a way to reproduce; it's best to open a new ticket with details

**Comment by mytvpro** [comment]
wow this is still a thing?

**Comment by edmundadjei** [comment]
I also have this issue, but I suspect it might be an OS scheduling issue as opposed to something to do with just "docker".
I think even if docker exits the container process, it can still take a while for the OS to schedule the reap to ensure the container not longer shows up in docker ps

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
