### ISSUE TITLE
Docker secret shall overwrite files if they already exists on file system

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#34100]
**Description**

When service is created with secret and file at the location of the secret already present on system then secrets will not copy over and fail

**Steps to reproduce the issue:**
1. Put files into container image where secret supposed to be located
2. Create service and point secret to the same location
3. Container when started will not have secrets mounted in desired location since location on file system inside container already have file

**Describe the results you received:**
Error mounting secret into that location

**Describe the results you expected:**
Supposed to overwrite the file in location with secret

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 16
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: pzsmh1s9vuezsewkrlz9953g8
 Is Manager: false
 Node Address: 10.45.122.51
 Manager Addresses:
  10.45.122.87:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1358.amd64fre.rs1_release.170602-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: CONTAINERHOST1
ID: M2VJ:VZZE:2CUJ:XLD7:6TTB:UUSA:RTPR:7MPV:HDSE:V6QX:KKDI:PBE4
Docker Root Dir: E:\images
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by friism** [comment]
cc @johnstep

**Comment by johnstep** [comment]
This works on Linux because a file can be bind-mounted over an existing file, but the same does not work on Windows when creating a hard link, as we do for secrets. You can still mount the secret on Windows, either in the default location (`$env:ProgramData\Docker\secrets`) or in a custom location where a file does not exist. I will look into having Docker delete the file before creating the hard link.

**Comment by artisticcheese** [comment]
Yes, please check if you can remove file forcibly. This will greatly simplify deployments at least in my docker implementation architecture.

**Comment by thaJeztah** [comment]
Deleting the file may be troublesome; someone committing a container to an image will loose the original file; so perhaps it should be optional

**Comment by artisticcheese** [comment]
Yes, whatever works but there shall be an option to forcefully remove user variables  by secret. This will work beatifully with QA/DEV process where creating secrets on local machine which is not part of swarm is not possible and will allow proper DEV/QA process with reliable/reproducible results when deployed in production.

**Comment by dperetti** [comment]
I expected this to work like configs. Configs overwrite the files, right ? Why not secrets ?
