### ISSUE TITLE
what makes "du -x" (--one-file-system) not working?

### ISSUE THREAD

**Issue by c0b** [moby/moby#34125]
many GNU utils (du, tar, and etc) support a `--one-file-system` argument to not cross file-system mounting point, it's convenient because we're counting disk usage statistics (`du -xsh /`) or make a tarball of the root filesystem (`tar --one-file-system -cf /mnt/another-disk/rootfs.tar / `), we want to skip the virtual filesystem mounting points (like /proc /sys ...);

```console
➸ du --help | grep -- -x
  -x, --one-file-system    skip directories on different file systems
➸ tar --help | grep -- --one-file-system
      --one-file-system      stay in local file system when creating archive
```

but this `-x` seems not working within docker container: it's hard to tell how much disk usage does root-fs really consumes, `disk -xsh /` gives wrong number, but `du -sh /` may include other volume mounts,

```console
$ docker run -it --rm ubuntu
root@4b9222edcd27:/# \du -xsh /usr
2.1M	/usr
root@4b9222edcd27:/# \du -sh /usr
58M	/usr
root@11f496e2e2a2:/# \du -sh /   
du: cannot access '/proc/13/task/13/fd/4': No such file or directory
du: cannot access '/proc/13/task/13/fdinfo/4': No such file or directory
du: cannot access '/proc/13/fd/3': No such file or directory
du: cannot access '/proc/13/fdinfo/3': No such file or directory
107M	/
root@11f496e2e2a2:/# \du -xsh /
2.7M	/

root@11f496e2e2a2:/# \du -a /usr | sort -n | tail
3672	/usr/share/doc
4452	/usr/lib/x86_64-linux-gnu/perl-base
5920	/usr/share/man
6512	/usr/lib/x86_64-linux-gnu/gconv
9148	/usr/share/locale
16032	/usr/bin
16912	/usr/lib/x86_64-linux-gnu
19952	/usr/lib
21592	/usr/share
59316	/usr

root@11f496e2e2a2:/# \du -xsh /usr/lib/x86_64-linux-gnu
408K	/usr/lib/x86_64-linux-gnu
root@11f496e2e2a2:/# \du -sh /usr/lib/x86_64-linux-gnu
17M	/usr/lib/x86_64-linux-gnu
```

vs. on a regular Linux, when we're sure there's no mounting point under /usr, this command with `-x` or without `-x` gives same result:

```console
➸ \du -xa /usr | sort -n | tail
289601	/usr/bin
289612	/usr/share/gimp
289612	/usr/share/gimp/2.0
289760	/usr/lib/libreoffice
305558	/usr/share/libreoffice/help
318549	/usr/share/libreoffice
643462	/usr/lib/x86_64-linux-gnu
1448827	/usr/lib
1922022	/usr/share
3766118	/usr
➸ \du -a /usr | sort -n | tail
289601	/usr/bin
289612	/usr/share/gimp
289612	/usr/share/gimp/2.0
289760	/usr/lib/libreoffice
305558	/usr/share/libreoffice/help
318549	/usr/share/libreoffice
643462	/usr/lib/x86_64-linux-gnu
1448827	/usr/lib
1922022	/usr/share
3766118	/usr
```

I suspect it's the overlay2 related but not very sure

```docker info
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
```

BTW: looking at /proc/mounts from the container it looks somewhere implemented very wrong, why does `proc` mounted so many times? on `/proc/bus /proc/fs /proc/irq /proc/sys` ? a regular Linux host has only one proc type mounted at /proc

```
root@11f496e2e2a2:/# grep /proc /proc/mounts
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
```

**Comment by cpuguy83** [comment]
This is a bug in overlayfs.
If you google `overlayfs "du -x"` you'll see a bunch of patches being submitted to fix it in the kernel.

From https://patchwork.kernel.org/patch/9695891/

> Due to the different bdev values for dir and non-dir inodes, when executing
the command du -x on an overlay mount, the result is wrong because non-dirs
are not accounted for in the overlay bdev usage.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
