### ISSUE TITLE
Unable to pull with corporate proxy

### ISSUE THREAD

**Issue by adawada** [moby/moby#34138]
Hi, I am using the command: docker pull hello-world,It showing me the error:  dial tcp: lookup index.docker.io on 127.0.1.1:53: no such host.I am behind the coorporate proxies.Before running this command i am setting the proxies export http_proxy=http://abc.com:8080 export https_proxy=https://abc.com:8080.Using the Ubuntu version 16.04.

**Comment by cpuguy83** [comment]
The error seems to be that it's trying to resolve the DNS address from localhost:

> dial tcp: lookup index.docker.io on 127.0.1.1:53

Please check your `/etc/resolv.conf` as it looks like docker is unable to connect to the local resolver.

Also please follow the normal issue template when submitted issues.
I've updated the issue to move all the content from the title into the issue.

Thanks.

**Comment by wenjianhn** [comment]
@adawada maybe you didn't correctly config the http proxy.

See
https://docs.docker.com/engine/admin/systemd/

**Comment by thaJeztah** [comment]
Based on the information in this issue, this looks to be a configuration issue, not a bug at hand here.

I'll close the issue for housekeeping, but feel free to continue the conversation 👍
