### ISSUE TITLE
NPM support - working with symlinks

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#34145]
Because `node_modules` is a directory commonly found in the build context - it would be nice if Docker could work with symlinks, since symlinks are common within `node_modules`.

This following issue was originally filed with NPM, but ultimately it's an issue with Docker - Docker cannot copy symlinks to the container. What Docker should do is copy the actual files which the symlinks point to:

https://github.com/npm/npm/issues/14325#issuecomment-315836458

**Comment by ethanrubio** [comment]
Are there any viable work arounds for this issue at the moment?

**Comment by ORESoftware** [comment]
@ethanrubio no, Docker doesn't work with symlinks :(

the best solutions seem to involve

1. using rsync to move share files in multiple locations
2. copying dockerfile to root of project, then the build context will be available to it. I personally am copying the real dockerfile, to the root of the project and using a UUID as the filename, then deleting the UUID when I am done building the image.

**Comment by cpuguy83** [comment]
I see your point, but also there is a very good case to copy a symlink as is.

**Comment by bsousaa** [comment]
It looks like this issue is stale. If this still apply please open an issue in the [buildx repo](https://github.com/docker/buildx).
