### ISSUE TITLE
Docker service update --image "could not accessed on a registry to record its digest"

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#34153]
Hello,

I use docker swarm with 
```
docker -v
Docker version 17.06.0-ce, build 02c1d87
```

My swarm is composed only of one node : 
`docker node ls
2c9zrmt995p3kxn0qi4sg2xyu *   ${nodeName}        Ready               Active              Leader
`

When i run docker service update --image i have this error :
```
docker service update --image=${REGISTRY}:5000/${IMAGE}:latest ${serviceName}
image ${REGISTRY}:5000/${IMAGE}:latest could not be accessed on a registry to record
its digest. Each node will access ${REGISTRY}:5000/${IMAGE}:latest independently,
possibly leading to different nodes running different
versions of the image.
{serviceName}
Since --detach=false was not specified, tasks will be updated in the background.
In a future release, --detach=false will become the default. 
```

The file /home/${USER}/.docker/config.json exists and contains the auth for the container.
When i run docker images, i see docker has been able to download images automatically for others services. 
I think the difference is for this service i have downloaded manually the image and after i have create the service.

**Comment by sylvainmouquet** [comment]
In the same style, docker service has downloaded an image of 5 days ago but there is a new image every day. 
`${REGISTRY}:5000/${IMAGENAME}       <none>              c4dad25bfd4a        5 days ago          1.2GB`

**Comment by thaJeztah** [comment]
When updating services that need credentials to pull the image, you need to pass `--with-registry-auth`. Images pulled for a service take a different path than a regular `docker pull`, because the actual `pull` is performed on each node in the swarm where an instance is deployed. To pull an image, the swarm cluster needs to have the credentials stored (so that the credentials can be passed on to the node it performs the pull on).

Even though the "node" in this case is your _local_ node, swarm takes the same approach (otherwise it would only be able to pull the image on the local node, but not on any of the other nodes).

Setting the `--with-registry-auth` option passes your locally stored credentials to the daemon, and stores them in the raft store. After that, the image digest is resolved (using those credentials), and the image is pulled on the node that the task is scheduled on (again, using the credentials that were stored in the service).

Can you confirm if passing `--with-registry-auth` makes the problem go away?

**Comment by sylvainmouquet** [comment]
Ok i have not set --with-registry-auth in the command line but why the image downloaded by the service is not the last version ?

**Comment by thaJeztah** [comment]
> but why the image downloaded by the service is not the last version ?

If the service failed to connect to the registry, it didn't resolve the latest digest, so uses any image with the specified `image:tag` that was already present on the host. Based on your description, `docker service update` did not pull a new image at all.

Also be aware that when updating the image without changing `image:tag`, the service may not _update_ the definition (i.e., re-resolve the image), unless `--force` is set (but I'd have to double check).

**Comment by sylvainmouquet** [comment]
Yes it's true i have already gone this scenarios but this time i have installed our application on a new virtual machine. We have a script which is in charge to deploy the application. It runs 4 docker stacks with the command line `docker stack deploy --with-registry-auth...`. I use this script on another environnement which deploy every night our application and for this environnement i have one manager and 2 workers. The manager does not host containers.
With this same script i have deployed the same application but this time the images was not the latest. 
Docker service has downloaded images but not the latest version. I am sure that the image has 
 been downloaded  by docker service because the version is defined to `<none>`.

I use docker stack deploy and the option `--force` is not present to this command. [https://docs.docker.com/engine/reference/commandline/stack_deploy/](https://docs.docker.com/engine/reference/commandline/stack_deploy/)
Do you have a solution to force the downloading of the latest version every time with `docker stack deploy`?

**Comment by thaJeztah** [comment]
For `docker stack deploy`, there's a `--resolve-image=always` option, but IIRC, that's the default, so it should resolve the latest image (given that it has the right credentials); 

> With this same script i have deployed the same application but this time the images was not the latest. Docker service has downloaded images but not the latest version. 

What user does the script run as, and is that use logged in? If the script runs as a different user, it will look in _that_ user's home directory for the credentials

**Comment by sylvainmouquet** [comment]
I use the same user.

**Comment by sylvainmouquet** [comment]
same bug here [https://github.com/moby/moby/issues/34299](https://github.com/moby/moby/issues/34299)

**Comment by DBLaci** [comment]
No #34299 is not the same. The problem I write there is not because of inaccessibility of private registry images.

**Comment by sylvainmouquet** [comment]
I close this post i will open a new with more information if the problem occurs agin

**Comment by jeremydr2** [comment]
FWIW, I get this error following the get started tutorial as well, on part 3: https://docs.docker.com/get-started/part3/#scale-the-app

I deploy the initial 5 replicas of the hello-world container, and then (following the tutorial) I change the replicas value in `docker-compose.yml`  and then rerun the command `docker stack deploy -c docker-compose.yml getstartedlab` which says that it should do an in-place update without needing to bring down the old deployment. The number of replicas does change correctly, but it still outputs

Updating service getstarted_web (id: w4zlxsy862cxo7h5dkwuluttr)
image jeremydr2/get-started:part2 could not be accessed on a registry to record
its digest. Each node will access jeremydr2/get-started:part2 independently,
possibly leading to different nodes running different
versions of the image.

Note that this does NOT happen if I have a clean swarm before deployment, it only occurs if I try to redeploy.

I have successfully signed in with `docker login` and including `--with-registry-auth` or `--resolve-image=always` does not change this. I am using the default public docker registry, "Docker version 17.06.2-ce, build cec0b72" on a "CentOS Linux release 7.2.1511 (Core)" VM.

**Comment by XLMBuildManager** [comment]
@majstrooker I'm having the same issue.

**Comment by trajano** [comment]
@majstrooker @XLMBuildManager does it still deploy correctly even with that message?

**Comment by trajano** [comment]
Actually something is really borky with Sonatype Nexus and docker there, I am not sure which part itself is broken, but I didn't have any issues with `registry:2`

**Comment by TomerFi** [comment]
> When updating services that need credentials to pull the image, you need to pass `--with-registry-auth`.

That solved if for me `docker stack deploy --with-registry-auth`.
Although, I don't recall having to add this flag in previous versions.

**Comment by harrier-lcc** [comment]
I encounter this problem when first switch auth credentials (`docker login`) and then update a stack using `docker stack deploy`. It seems that when doing update on existing service, it do not use the new credentials, even with `--with-registry-auth`.

It only works when I update the stack via `docker stack rm` and then `docker stack deploy` (with `--with registry-auth` it once again.

**Comment by gurleensethi** [comment]
@majstrooker I am using github registry and facing the same issue. Initial Deployment is successfull but anything after that I get the error:

```
image <image_url> could not be accessed on a registry to recordits digest. Each node will access <image_url> independently,possibly leading to different nodes running differentversions of the image.
```

Did you find any solution?

**Comment by thaJeztah** [comment]
@gurleensethi that's a known issue with GitHub's registry. The GitHub image registry currently isn't compliant with the registry specification and doesn't implement all options, see https://github.com/containerd/containerd/issues/3291#issuecomment-579804848

**Comment by clarkbw** [comment]
> that's a known issue with GitHub's registry. The GitHub image registry currently isn't compliant with the registry specification and doesn't implement all options

FYI, for those that find this via search. The [GitHub Container Registry](https://docs.github.com/en/packages/getting-started-with-github-container-registry/about-github-container-registry) https://ghcr.io/ is compliant with the spec and this should work correctly when connecting to `ghcr.io` but won't work when trying with `docker.pkg.github.com`.

**Comment by ivanduka** [comment]
So in case someone still struggles with this issue despite using `--with-registry-auth`, it's probably because you are using `sudo -E` to preserve environmental variables. This leads to Docker not having access to root's home folder with docker credentials, but your non-root user's home directory. The solution is to use `sudo su` and do everything as root. Otherwise, for every env variable you have to use `sudo --preserve-env=YOUR_VARIABLE1 --preserve-env=YOUR_VARIABLE2...`, which is tedious.

**Comment by blindlobstar** [comment]
> @majstrooker I am using github registry and facing the same issue. Initial Deployment is successful but anything after that I get the error:
> 
> ```
> image <image_url> could not be accessed on a registry to record its digest. 
> 
> Each node will access <image_url> independently, possibly leading to different nodes running different versions of the image.
> ```
> 
> Did you find any solution?

Same error. Is there any solution after a year

**Comment by thaJeztah** [comment]
@blindlobstar if you're using `docker.pkg.github.com`, consider changing to `ghcr.io`. I don't think `docker.pkg.github.com` is gonna be fixed. Other than that, you may try to use the `--no-resolve-image` option, but you'll have to make sure that you use unique tags if an updated version of the image must be deployed (to prevent possibly outdated images if they're already available on a node).

See related discussions on https://github.com/moby/moby/issues/41687 and https://github.com/docker/cli/pull/2872

**Comment by blindlobstar** [comment]
> @blindlobstar if you're using `docker.pkg.github.com`, consider changing to `ghcr.io`. I don't think `docker.pkg.github.com` is gonna be fixed. Other than that, you may try to use the `--no-resolve-image` option, but you'll have to make sure that you use unique tags if an updated version of the image must be deployed (to prevent possibly outdated images if they're already available on a node).
> 
> See related discussions on #41687 and [docker/cli#2872](https://github.com/docker/cli/pull/2872)

Thank you for answer, but I am using ACR (Azure Container Regestry). I already try to use github.sha as version, but still get same error

**Comment by clarkbw** [comment]
> but won't work when trying with `docker.pkg.github.com`

Update to this. The GitHub team is in the process of migrating all `docker.pkg.github.com` users in the background. When the migration is finished `docker.pkg.github.com` and `ghcr.io` will be the same service with the same type of responses and only different domains.

**Comment by thaJeztah** [comment]
Thanks for the update @clarkbw !

**Comment by Houssem12-ai** [comment]
@thaJeztah thanks a lot 
adding --with-registry-auth solves my issue

**Comment by Ishu1998** [comment]
Any Solution yet ?
--with-registry-auth   doesn't solve my problem.

**Comment by Houssem12-ai** [comment]
@Ishu1998 
have you checked that you are connected to the dockerhub account ?

**Comment by antonio-kim-1994** [comment]
> Any Solution yet ? --with-registry-auth doesn't solve my problem.  

I solved my problem with checking connection to my private registry as @Houssem12-ai said. I guess In order to deploy services through docker stack, both the worker node and the master node must have the auth to the registry. This is because, apart from the worker node downloading the image independently from the private registry, it seems that the master node needs access to determine the image received by the worker node. You can check the auth at $HOME/.docker/config.json.

**Comment by aol-nnov** [comment]
> master node needs same auth to determine the image downloaded by the worker node

I've double-checked auth in the config.json (file is identical on both nodes) and yet I have the same warning during the following command

```
docker service update --with-registry-auth --force --image my_gitlab_private_registry/img service_name
image my_gitlab_private_registry/img:latest could not be accessed on a registry to record
its digest. Each node will access my_gitlab_private_registry/img:latest independently,
possibly leading to different nodes running different
versions of the image.

service_name
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged 
```

To make things happen as expected I have to log in to each worker node and issue `docker image pull my_gitlab_private_registry/img` command beforehand.

Pulling images manually makes me really sad. :(
