### ISSUE TITLE
could not resolve address of member ID

### ISSUE THREAD

**Issue by trafle73** [moby/moby#34160]
Hello,
**Description**

I'm facing a weird issue with swarm, and would like to have some assistance on that one.
I've added in a swarm of 3 managers (version 17.03) a new host as a worker with no issue.
After that a VMware rollback has been done on that worker after an upgrade in debian stretch (was for a test).
The rollback seems have broken something in my swarm.

No data available from the swarm --> Error: rpc error: code = 4 desc = context deadline exceeded

I have not the ability to delete and create the swarm again as it is currently in use with some services.

**Steps to reproduce the issue:**
1. Add host as a worker into a swarm (Debian 8.8)
2. VWmare snapshot on that host
3. Upgrade Debian 9 stretch
4. Rollback on the snapshot
5. Promote Worker to Manager or add new host as manager

**Describe the results you received:**
Now when I want to promote the worker as a manager, or even add a new host to my swarm as a manager, I've got that on my logs every seconds :

```
Jul 18 14:23:51 docker-5 dockerd[710]: time="2017-07-18T14:23:51.286450834+02:00" level=warning msg="sending message to an unrecognized member ID 5c9f1beef700d602" raft_id=6b9c136b96a2f655
Jul 18 14:23:51 docker-5 dockerd[710]: time="2017-07-18T14:23:51.286554667+02:00" level=error msg="could not resolve address of member ID 5c9f1beef700d602" error="rpc error: code = 9 desc = grpc: the client connection is closing" raft_id=6b9c136b96a2f655
```

The "could not resolve address of member ID 5c9f1beef700d602" is the same ID on both of the host that I Try to add as a manager into my swarm. But I could not find to what it is related

When I add them, it's taking time, like if somehting was in timeout and then end normally. But I could not use any of the swarm command on those 2 managers.

**Describe the results you expected:**

Have a responding and working new manager in my Swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**
```
Swarm: active
NodeID: yhpvwcm60oko20leg9z7vieop
Error: rpc error: code = 4 desc = context deadline exceeded
Is Manager: true
ClusterID:
Managers: 0
Nodes: 0
Orchestration:
Task History Retention Limit: 0
Raft:
Snapshot Interval: 0
Heartbeat Tick: 0
Election Tick: 0
Dispatcher:
Heartbeat Period: Less than a second
CA Configuration:
Expiry Duration: Less than a second
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare

Many thanks !

Best regards,

Trafle73

**Comment by trafle73** [comment]
Quick thing, when I do "docker node ls" from a working manager : 
ID                           HOSTNAME       STATUS  AVAILABILITY  MANAGER STATUS
7x2fy0t5np1jh3ci5k44kd8qg *  docker-2  Ready   Active        Reachable
svb7d2odjpv2r705e5vekl2tg    docker-1  Ready   Active        Reachable
u5d4jn84svak6qmszs1609uwu    docker-3  Ready   Active        Leader
yhpvwcm60oko20leg9z7vieop    docker-5  Ready   Active        Unreachable

It is shown as unreachable for the "Manager Status"

**Comment by thaJeztah** [comment]
Did the IP-address of the node change? Swarm doesn't currently support dynamic IP-addresses

**Comment by trafle73** [comment]
No the IP address was not changed as it is a static one. 
It's even doing the same error if I deploy a new host from scratch and add it to the swarm.
In both cases it is static IP address.

**Comment by thaJeztah** [comment]
Are you using the `--advertise-addr` option when initialising, and joining the swarm?

**Comment by trafle73** [comment]
When I'm joining the swarm I'm using the command `docker swarm join-token manager` to generate the command that I have to enter to my new node.
For what I'm seeing in the file docker-state.json on my working manager, the "advertise-addr" filed is empty.
When the swarm ha been initiated, it was with the following command : 
`docker swarm init`

So I am not using this option when initialising or joining the swarm

For the record, each of my working nodes only have one static IP address each

**Comment by thaJeztah** [comment]
There have been issues with (e.g.) DigitalOcean, where a single interface had multiple IP addresses assigned, but this may not be the case in your situation.


perhaps @sanimej or @fcrisciani has some suggestions for debugging

**Comment by trafle73** [comment]
I can confirm that my host only have one IP address on their interface.

Is there any way to clean the ID 5c9f1beef700d602 which sound to be the one causing troubles or to find to what is it related to make it work again ?

**Comment by trafle73** [comment]
I thin I found something.
If I deploy a new host in Debian 9, then install docker 17.06 (**not 17.03**) then I add it to the swarm, I have the same error message for like 1 minute. But then just after there is an info message about joining event to docker-3 an then error disappear and the new manager is working !!

```
> Jul 20 09:55:37 zeus-docker-7 dockerd[11342]: time="2017-07-20T09:55:37.070588240+02:00" level=warning msg="sending message MsgHeartbeatResp to an unrecognized member ID 5c9f1beef700d602"
> Jul 20 09:55:37 zeus-docker-7 dockerd[11342]: time="2017-07-20T09:55:37.084299932+02:00" level=warning msg="sending message MsgAppResp to an unrecognized member ID 5c9f1beef700d602"
> Jul 20 09:55:42 zeus-docker-7 dockerd[11342]: time="2017-07-20T09:55:42.602175337+02:00" level=info msg="Node join event for docker-3-b8cf4833d1de/172.20.60.54"
```

 
I've done that test 3 times each time it is doing the same, error stops as soon as the "Node join event for docker-3" message is logged.

**That works only with 17.06.**

So I guess the ID 5c9f1beef700d602 is linked to docker-3 but could not find where.

**Comment by thaJeztah** [comment]
> Is there any way to clean the ID 5c9f1beef700d602 which sound to be the one causing troubles or to find to what is it related to make it work again ?

To remove a node;

- run `docker node rm <node-id>` from a manager
- run `docker swarm leave` on the node itself (which makes the node itself leave swarm mode, and cleanup swarm state data)

> I've done that test 3 times each time it is doing the same, error stops as soon as the "Node join event for docker-3" message is logged.

Hm, could it be those messages are because the managers did not yet reach consensus on the node being joined as a manager? (message is coming from [swarmkit/manager/state/raft/transport/transport.go#L133-L149](https://github.com/moby/moby/blob/99119fcafa41fb8c95e67b225a3da2902ce0e959/vendor/github.com/docker/swarmkit/manager/state/raft/transport/transport.go#L133-L149) - some description on that message is [documented in the etcd docs](https://github.com/moby/moby/blob/99119fcafa41fb8c95e67b225a3da2902ce0e959/vendor/github.com/coreos/etcd/raft/doc.go#L280-L286) )

For your original problem description;

> Rollback on the snapshot

This could possibly lead to issues; For example, Swarm automatically rotates certificates; rolling back _one node_ to an earlier snapshot could mean that the node will use certificates that are rotated. Also not sure what happens if you roll back to an older version of the raft store.

**Comment by sanimej** [comment]
@thaJeztah This looks like an issue in the raft communication after the rollback. cc @aaronlehmann @aluzzardi

**Comment by trafle73** [comment]
It is not an Node ID so I cannot delete that from the swarm. I don't know to what is related this ID 5c9f1beef700d602 I couldn't find it anywhere. 
@thaJeztah The node being join as manager in 17.03 constantly logs those errors without ever joining a host event after minutes/hours at the contrary of 17.06. I guess something changed on that side. Regarding what you send it sound to be a Raft ID which is not reachable/corrupted in raft process. But where can I clean this ID up ? Is it possible ?

@thaJeztah @sanimej thanks for the explanation on the swarm / raft.
 I guess raft does not deal with snapshot rollback yes as my problem starts from here. Do you know if it is solvable ?

Thanks

**Comment by aaronlehmann** [comment]
> The rollback seems have broken something in my swarm.

It's not surprising that rolling back a VM snapshot would cause problems in a swarm. This has been known to cause panics in managers, because the state of the world changes underneath them them. I would recommend against doing this.

**Comment by extrail** [comment]
Any update on this?
I'm encountering the same issue with 17.09.
Is there a way to cleanup the stale raft ID?

**Comment by Gabology** [comment]
We are also seeing this same issue, attempting to add different nodes as managers is causing connection issues between them and the rest of the cluster, these are the messages that are showing up in the dockerd logs:

```
Mar 12 12:07:46 swarm-manager-j4lm dockerd[2683]: time="2018-03-12T12:07:46.219591209Z" level=warning msg="sending message MsgHeartbeatResp to an unrecognized member ID 7939feb97a1b42d1"
```

**Comment by marech** [comment]
Had exactly same issue, promoted/joined swarm as manager was successful but couldn't execute any swarm command and got in  logs

```
level=warning msg="sending message MsgHeartbeatResp to an unrecognized member ID 2c513ac915352fd9"
level=warning msg="ignored message MsgHeartbeatResp to unknown peer 2c513ac915352fd9" error="failed to resolve peer: failed to find longest active peer"
```


Even tho i managed to find workaround - on existing manager created random overlay network  and deleted it after
`docker network create --driver overlay dummy`
`docker network rm dummy`

And after some time error disappeared, but every time i'm trying to join new manager had same issue.

References: [1](https://success.docker.com/article/ucp-agent-flapping-during-manager-join)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
