### ISSUE TITLE
Swarm/mesh workaround: add option "service create --mesh=false : option

### ISSUE THREAD

**Issue by jefflill** [moby/moby#34161]
Some folks (including me) seem to be having serious problems with the routing mesh/ingress network (for example, see #32195 and #34136).  These are apparent, in stable releases **17.03.0-ce**, **17.03.2-ce**, and **17.06.0-ce"".  I haven't tried the other intermediate edge releases.

I'm going to try to workaround this by manually deploying my ingress services to all nodes as a simple container.  Unfortunately, containers don't support secrets, so this means I'll need to modify the containers to accept secrets as environment variables.  I'll also need to manually roll out container updates.

It would be nice if the `docker service create` command had an option that disabled the routing mesh feature, something like:

&nbsp;&nbsp;&nbsp;&nbsp;`docker service create --mesh=false -mode global --publish 80:80` ...

This would simply expose the service port on the docker host machine and disable the fancy networking.  Then we could use a combination of the `mode` and `constraint` to control where our ingress services actually run.  This would mean that we'd still get the other advantages of services (secrets, scheduling, updates,...)

Mesh routing is a fantastic feature, but it really needs to be airtight.  It's been a year+ since 1.12 introduced this and I'm not sure it's ever been stable.

**Comment by thaJeztah** [comment]
This is already possible with `host-mode` publishing;


```bash
docker service create \
  --publish mode=host,target=80,published=80,protocol=tcp \
  --name=web \
  --mode=global \
  nginx:alpine
```

host-mode publishing publishes container's ports directly to the host, skipping the ingress network (thus the routing mesh)

**Comment by jefflill** [comment]
YAY!  Learn something new every day!

**Comment by thaJeztah** [comment]
Docs can be found here; https://docs.docker.com/engine/swarm/services/#publish-ports, but may be a bit hard to find, so I just opened https://github.com/docker/docker.github.io/issues/3913 to request better docs (contributions welcome 😄 )

**Comment by thaJeztah** [comment]
Docs can be found here; https://docs.docker.com/engine/swarm/services/#publish-ports, but may be a bit hard to find, so I just opened https://github.com/docker/docker.github.io/issues/3913 to request better docs (contributions welcome 😄 )

**Comment by jefflill** [comment]
A follow-up note for future generations:

I was finally able to fix the original ingress network problem by reducing the ingress network MTU from it's default value of 1500 to **1492** bytes.  This problem happens when the Docker nodes are hosted as virtual machines by hypervisors like Hyper-V and XenServer.  I'm guessing that the Docker ingress network works like this:

1. Ingress network MTU defaults to 1500 bytes
2. Ingress network actually reports its MTU to the attached containers as 8 bytes less (the size of a VXLAN header), so 1492 bytes.
3. Ingress network will add an 8-byte VXLAN header to each packet routed through, so the maximum size of a packet will be 1492+8=1500 bytes.  These will route on most LANs.
4. But when the Docker hosts are running as VMs on Hyper-V or XenServer, another 8-byte VXLAN header is added and now the maximum packet size is 1508, which is to big for most LANs.
5. I'm guessing that the packet *no-fragment* flag must be set so the ingress network must send an ICMP packet back to the source requesting that it split to packet and that these are lost or cause enough delay that we see random seeming timeouts.

I haven't actually confirmed the theory above, but changing MTU to 1492 fixed my problem.

Here's the script I used to recreate the **ingress** network.  Note that I needed to a a bit of delay between removing and recreating it to give the Docker a chance to actually delete the thing.  The subnet and gateway settings below match the Docker defaults.

```
# Delete the [ingress] network.

docker network rm ingress << EOF
y
EOF

# Give the network a chance to actually be deleted.

sleep 10

# Recreate the [ingress] network with the new settings.

docker network create \
   --driver overlay \
   --ingress \
   --subnet=10.255.0.0/16 \
   --gateway=10.255.0.1 \
   --opt com.docker.network.mtu=1492 \
   ingress
```

**Comment by thaJeztah** [comment]
For containers, the MTU is set to 1450; https://github.com/docker/libnetwork/blob/5d113d19f93b14b7b6a2b2d1f2fc1a2c1b6f9b0d/drivers/overlay/joinleave.go#L67-L70

```go
	// Set the container interface and its peer MTU to 1450 to allow
	// for 50 bytes vxlan encap (inner eth header(14) + outer IP(20) +
	// outer UDP(8) + vxlan header(8))
	mtu := n.maxMTU()
```

For the ingressnetwork, no option is set explicitly; https://github.com/moby/moby/blob/cf72051c3746fa60d7e7995c0342eaca91f07bfd/daemon/network.go#L202-L224 https://github.com/moby/moby/blob/cf72051c3746fa60d7e7995c0342eaca91f07bfd/daemon/network.go#L293-L384, in which case I think `maxMTU()` will also be used.

**Comment by jefflill** [comment]
Interesting.  I just read this guys experience with this in August here:

https://medium.com/@sylwit/how-we-spent-a-full-day-figuring-out-a-mtu-issue-with-docker-4d81fdfe2caf

...and I've been playing around with Docker's `daemon.json` file by setting **mtu=1492** and redeployed a Docker Swarm.

The documentation for MTU [here](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) says: *Set the containers network MTU*.  I inspected the **ingress** and a couple other networks I created and they all report **MTU=1492**.  So I'm betting this might be the best way to configure the MTU because it will ensure that any networks created after swarm setup (e.g. via Docker Stacks) will also get the new MTU by default.
