### ISSUE TITLE
Install script does not work on Fedora 26

### ISSUE THREAD

**Issue by Tcharl** [moby/moby#34178]
The command sh -c 'dnf makecache fast' used in the installation script does not work anymore on Fedora 26.

Here's the error:
dnf makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer')
The line on the script downloaded when using the installation method 'curl -sSL https://get.docker.com/ | sh' contains '$sh_c "$pkg_manager makecache fast"'

I'm new to docker, also in the community, so sorry if I'm wrong posting this message here.

Regards,

**Comment by hamidnazari** [comment]
@Tcharl to get you going,

```
curl -fsSL get.docker.com -o get-docker.sh
sed -i -E 's/(makecache) fast/\1/' get-docker.sh
sh get-docker.sh
```

**Comment by Tcharl** [comment]
Hi @hamidnazari ,

Thank you for the tips!
But that is kind of hard to ammend when using Opscode Chef third party docker cookbook ;-).

Best regards

**Comment by thaJeztah** [comment]
There currently are no packages yet for Fedora 26, which may be part of the problem, however, if there's an issue with the install script; could you report this in this repository: https://github.com/docker/docker-install/issues ?

**Comment by Tcharl** [comment]
Ok, thank you, the issue is already filled ^^. This was the docker second git repo I put the issue on!

**Comment by thaJeztah** [comment]
Looks like this was also reported in the https://github.com/docker/docker-install repository, where this script is maintained; https://github.com/docker/docker-install/issues/16

Let me close this issue here, because the other issue is already tracking this
