### ISSUE TITLE
Inconsistent layer checksum after multi-stage build

### ISSUE THREAD

**Issue by loicgelle** [moby/moby#34189]
**Description**

I am trying to perform reproducible builds in Docker containers and I would like to use the layer checksums of the produced image as a proof of reproducibility. But when building the same image twice in a row using the same Dockerfile, I end up having two different checksums where I would expect a unique one.

**Files to reproduce the issue:**

Clone the git repo: `https://github.com/loicgelle/docker-bug-files`

**Steps to reproduce the issue:**

1) `docker build -t demo-base . -f Dockerfile.base`
2) `docker build -t demo-musl-build . -f Dockerfile.musl-build`
3) `docker build -t demo-musl-libs . -f Dockerfile.musl-release-libs`
4) `docker build -t demo-musl-headers . -f Dockerfile.musl-release-headers`
5) `docker build -t demo-ncurses-build . -f Dockerfile.ncurses-build`

Then perform two different releases in a row:

1) `docker build -t demo-ncurses-release-headers-1 . -f Dockerfile.ncurses-release-headers --no-cache`
2) `docker build -t demo-ncurses-release-headers-2 . -f Dockerfile.ncurses-release-headers --no-cache`

Then compare the outputs of `docker inspect demo-ncurses-release-headers-1` and `docker inspect demo-ncurses-release-headers-2`.

**Results:**

The image only has one layer corresponding to the last `COPY` statement, which is fine. But the hashes for the two layers are different, I would expect them to be identical.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 363
 Running: 1
 Paused: 0
 Stopped: 362
Images: 11655
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.854GiB
Name: moby
ID: H4KC:E32G:U7U2:RFMA:KJKV:BISY:5PPE:I6JS:EFOC:IPTQ:QWZZ:RZ7T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 33
 System Time: 2017-07-19T16:54:59.866998923Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I suspect due to `mkdir` creating a different creation date, thus the metadata being different. I do recall a discussion about fixating the date/time (or excluding the time entirely from the calculation.

Ping @tonistiigi

**Comment by loicgelle** [comment]
@thaJeztah You're right, my example is not consistent and touching the directories as well fixes the problem. But I have a problem with a similar build workflow, although I change every modification and last access time in the Dockerfiles. Let me try to reproduce using the simplest possible example.

**Comment by loicgelle** [comment]
@thaJeztah @tonistiigi The example has been updated.

**Comment by loicgelle** [comment]
Did you manage to reproduce the issue? If it is verified, I would consider it as being serious.

**Comment by thaJeztah** [comment]
Sorry, haven't had time yet; possibly @tonistiigi is able to have a quick peek, he's more familiar with these parts, and may be able to tell if this is expected or not (but I know he's busy as well :sweat_smile:

**Comment by loicgelle** [comment]
@thaJeztah No worries! I know my example is quite complex but I did not manage to isolate the problem more than that...

**Comment by tonistiigi** [comment]
@loicgelle Problem is that one of the files you are copying (ncurses.h) is a symlink and the fixed time does not get set on it. Change https://github.com/loicgelle/docker-bug-files/blob/master/Dockerfile.ncurses-release-headers#L7 to `touch -h -t ...` and it should work fine.

**Comment by loicgelle** [comment]
@tonistiigi What a weird issue... Thank you so much Tonis, I should have checked my image contents more carefully. Actually I did checksum verifications, and I was reassured by the fact that the checksum logged for the `COPY` instruction in the image history was consistent across the builds (how do you explain that btw?)

You've been very helpful 👍

**Comment by tonistiigi** [comment]
@loicgelle The hash shown in `history` is used for the build cache. It ignores some values like modification time(and has some other edge case issues that make it not suitable for this kind of check) that are not stable when repeatedly invoking the builder. The easiest way to get the artifact that makes up the hash shown in the `image inspect` is to `docker save` the image and take `sha256` of the layer file inside that tar.

**Comment by thaJeztah** [comment]
Oh, wow, never would've thought of that!

Does it work with that approach?

**Comment by loicgelle** [comment]
@tonistiigi I indeed tried to hash the layer tar :)

@thaJeztah What are you talking about?

**Comment by loicgelle** [comment]
More generally speaking, wouldn't it be nice to have direct access to an indicator (just like the hash shown for `COPY`) that reflects the contents of an image rather than things like runtime information (access and modification time for example) ?

I have the feeling that Docker is being used more and more like a builder (which is consistent with LinuxKit packages and multi-stage builds feature). Would be nice to have a difference between images that are built to be run and more "static" images that are just files.

**Comment by loicgelle** [comment]
Well solved for me anyway. I close this one.
