### ISSUE TITLE
Pull from library/* sometimes fails when in VPC with S3 endpoints.

### ISSUE THREAD

**Issue by jdnurmi** [moby/moby#34185]
**Description**
NB: This is probably not a _bug_, but a request for documentation.

Occasionally, when pulling "library/*" images from nodes within my VPC, I'll get back what appears to be an S3 caused error a la:

```
docker --debug -l debug pull rabbitmq:3-management
3-management: Pulling from library/rabbitmq
e6e142a99202: Pulling fs layer 
5391967c36ff: Pulling fs layer 
575d2e799d0d: Pulling fs layer 
99074ba2b6d8: Waiting 
b77cecce51ce: Waiting 
e381a5c8d5a8: Waiting 
b31bd0e6cc5f: Waiting 
bbf17e7efd42: Waiting 
3f9d0b7d7b6d: Waiting 
96be941057b8: Waiting 
ee78f74158ff: Waiting 
599042c234d3: Waiting 
bb8f2d58865d: Waiting 
47d3d59f0d46: Waiting 
error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>835EB39A43ACC922</RequestId><HostId>pomMsqh5F0wbqpEP37Z5x64GE8lC4H/kxWWR9Kta4zOKJVu87hnd3R7ZiR7VM8WtvULKEp0uYbI=</HostId></Error>"
```

This did not _always_ happen, and never happens with things pulled from my internal registry --but happens often enough and my environment is customized enough I had a hypothesis I wanted to put past you:

Does the official docker hub use S3 as a backend, and does it issue redirects to S3? (Both sensible things to do, but...)

As it happens, the VPC my instances run in uses [VPC endpoints](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html) - with a very restricted policy - so a canonical S3 redirection could potentially get denied by the VPC endpoint firewall.

**Steps to reproduce the issue:**
1. Create a trial AWS account with new VPC, add S3 VPC endpoint to VPC.
2. Attach routes to endpoint, attach a deny-all policy to S3 endpoint (I used us-east-1, but that may not matter)
2. Attempt to pull a new image from the library.
3. 

**Describe the results you received:**

See above

**Describe the results you expected:**

Success, or documentation of what bucket(s) I need to grant permission to if you'll be using direct-to-S3 redirects - or at least enough debugging to know what URL is giving the 403, as S3 error messages are too terse to be informative without that context.

**Additional information you deem important (e.g. issue happens only occasionally):**

A workaround is of course to never use library/* when using a restrictive S3 endpoint (copy all images inward by some process, and rely solely on your own registry) - but it'd be nice to be able to just tweak my ACL's a little bit (and not have to do a GetObject on * permission, since that's wider than I want!)

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64```

**Output of `docker info`:**

```
Containers: 10
 Running: 4
 Paused: 0
 Stopped: 6
Images: 15
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.8.11-coreos-r1
Operating System: CoreOS 1248.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: **ELIDED**
ID: R5O3:WIXX:SX6K:VMHV:2NZO:RVYT:PSQC:3KTZ:WYM4:TR5G:ZQZE:X7OA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker via ECS on CoreOS on AWS/EC2 in a VPC, and the green grass grew all around all around...

**Comment by thaJeztah** [comment]
Thanks for asking; I think various backends are used for downloading the image-layers, and yes, one of them may be S3. You're right that redirects are used, and after authenticating with a short-lived token, clients are redirected to the download URL (see this bash script that can be used to download images without using docker; https://github.com/moby/moby/blob/4bbdc0b8f7b2faa3354738c300cfedb2b77c7316/contrib/download-frozen-image-v2.sh#L59-L79)

I don't have the full details though, and this is really a question for the team managing Docker Hub, which is separate from the project maintained in this repository. If you need more information could you contact support@docker.com ? Perhaps they're able to help you further.

I'll close this issue here, because this is out of scope for this issue tracker, but feel free to continue the conversation

**Comment by SvenDowideit** [comment]
@thaJeztah are there any updates? it looks like one of our RancherOS users hit this with Docker 17.03-ce

**Comment by thaJeztah** [comment]
@SvenDowideit I don't think there's a published list of buckets used by Docker Hub; @jdnurmi did you inform with Docker Hub support - did they give you that information?

**Comment by jdnurmi** [comment]
tbh, I isolated my jenkins nodes to a subnet that isn't subject to the VPC endpoint rules;  Not a great end solution, but since there wasn't any official documentation, I didn't want to play guess-and-change, and the only things I have that need to reach into random buckets are my builds.

I _did_ open a ticket with AWS asking for logging on VPC endpoints or advanced IAM solutions to grant external signatures through the endpoint, but haven't heard back from them.

**Comment by thaJeztah** [comment]
I put out this question on our internal slack, perhaps someone there is able to answer, I'll post here if they get back to me

**Comment by garceri** [comment]
The following policy which is not fully resteictive was causing the issue as reported on 
```{https://github.com/rancher/os/issues/2032
    "Version": "2012-10-17",
    "Id": "Policy1415115909152",
    "Statement": [
        {
            "Sid": "Access-to-specific-VPCE-only",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::demobucket-demo",
                "arn:aws:s3:::demobucket-demo/*"
            ],
            "Condition": {
                "StringNotEquals": {
                    "aws:sourceVpce": "vpce-05945f6c"
                }
            }
        }
    ]
}```
