### ISSUE TITLE
[Feature Request] Make Moby's container export/import OCI compliant 

### ISSUE THREAD

**Issue by c4milo** [moby/moby#34187]
I was surprised to find out I lost all my environment variables when I Docker exported and imported a container. It would be really useful and friendlier with the community to support OCI specs in order to retain the metadata defined in the Dockerfile.

**Comment by AkihiroSuda** [comment]
See https://github.com/moby/moby/pull/33355 (though save/load rather than import/export)

**Comment by thaJeztah** [comment]
Yes this is a duplicate of https://github.com/moby/moby/issues/25779, so let me close this one :+1:
