### ISSUE TITLE
`modify_ldt` syscall fail and crash with `seccomp:unconfined` or even `privileged` options

### ISSUE THREAD

**Issue by fklingler** [moby/moby#34184]
**Description**

I'm trying to launch a Unity ([unity3d.com](http://unity3d.com)) script inside a docker container.  

Everything works well on our development machines using Docker for Windows. But when the container is run on our linux server, I get this error:

```
UnityShaderCompiler: /home/builduser/buildslave/unity/build/Editor/Tools/Wodka/wodka_PELoader.cpp:936: const char* PESetupFS(): Assertion `0 == syscall(123, 1, &e, sizeof(e))' failed.
```

The syscall fails and it crashes the process. It is apparently the `modify_ldt` syscall.

I'm not the only one who had this problem, someone else posted on the Unity forums here: https://forum.unity3d.com/threads/building-asset-bundles-on-an-ubuntu-docker-container.462845/  
I'm the user "fklingler-mitm" on this thread.
A Unity Linux developer answered that about this issue:
> Wodka is a PE loader for hosting the direct3d shader compiler library. 
The syscall is creating a local descriptor entry that we need; the failure of the assertion means that creating the entry failed.
This seems to be related to docker's security profiles - searching the web, I see a bunch of security-related discussion around this feature.

So, I tried some things :
- I tried using the `seccomp:unconfined` security option
- I tried using the `apparmor:unconfined` security option
- I tried adding `cap-add=ALL`
- I tried running the container in `privileged` mode

Nothing changed the situation, the error was still here in all cases.

Do you have any idea of what I could do to fix this?
Thanks a lot!

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 112
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.38-std-1
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859GiB
Name: scw-audet-IX
ID: VEMX:5YUW:HFHU:4NXE:NG2B:NPOW:ZWXZ:ITQB:OPWX:UNMK:U3LC:5IJ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server

**Comment by justincormack** [comment]
The default seccomp profile allows `modify_ldt` so that is not blocking it. Are you able to run the program directly on the host? There was a CVE with `modify_ldt` not long ago, and as it is very rarely used it may have been disabled by Ubuntu at a guess.  If you can find the kernel config (in `/boot/config-..` you can check if ` CONFIG_MODIFY_LDT_SYSCALL` is set. It is becoming standard to not set it.

**Comment by fklingler** [comment]
I have `CONFIG_MODIFY_LDT_SYSCALL=y` in the `/boot/config-..` of my host.

It is not easy for me to try this on the host directly since I need to install a lot of packages on my server that is almost in production, notably some GUI packages that are necessary for Unity3D, and I really prefer to have all of this isolated.
I will try to do it though, maybe by replicating in some way my server kernel configuration on a VM.

**Comment by justincormack** [comment]
Hmm, thats really strange. I really can't think of any reason thats Docker related that would block it. Hmm, unless somehow Ubuntu disable it with apparmor, did you try running with `--security-opt apparmor=unconfined`?

**Comment by fklingler** [comment]
Yes I tried it, or more precisely with the docker-compose option like this:

```
security_opt:
  - apparmor:unconfined
```

**Comment by fklingler** [comment]
For confirmation, I only need to recreate the containers when I change the security options like that? I don't need to rebuild the image?

**Comment by justincormack** [comment]
No, those are just runtime changes. It does seem most likely it is a host issue, but it is very odd as I cannot see any documentation about this.

**Comment by fklingler** [comment]
I just did this test:
- I created a Ubuntu VM on Hyper-V
- Installed same version of docker
- Built and ran my containers

And.. everything is working great on this configuration. This indeed seems to be a host problem.

Do you think the syscall is directly blocked in some way on the host? I don't really know what to look for now...

**Comment by fklingler** [comment]
I must correct myself

>I have `CONFIG_MODIFY_LDT_SYSCALL=y `in the `/boot/config-..` of my host.

Even though this was true, this was apparently not the file used for my kernel config. It is a little bit customized by my server host provider, and this config line is not set on the config file that is used.
So this is the problem, the syscall is just not available on my host.

I will now see with my server provider on how to change this option.

Thanks for the help!

**Comment by justincormack** [comment]
Ok, well glad thats cleared up!

@ijc thats another reason why Debian should enable `/proc/config.gz` as it is much more reliable for diagnostics.

**Comment by ijc** [comment]
To request a kernel config change please run `reportbug kernel` on any Debian system/container (or you can do it manually with a properly formatted mail to submit@bugs.debian.org per https://www.debian.org/Bugs/Reporting).

**Comment by ijc** [comment]
Actually probably not much point given https://wiki.debian.org/KernelFAQ#line-46, although perhaps the thinking has changed since 2009.

Note that it wouldn't have helped here anyway since it wasn't a Debian kernel which was running. I suspect that the specific `/boot/config-$(uname -r)` (as opposed to `/boot/config-*`) either wouldn't have existed or would have corresponded to the running kernel, if it existed and didn't correspond then the service provider has done something _very_ confusing and I'd recommend filing a bug with them.

**Comment by fklingler** [comment]
The file I had to read to learn my real config was indeed `/proc/config.gz`.

**Comment by rubentorresbonet** [comment]
I also have this issue. Did you find any way of fixing this?

**Comment by baid86** [comment]
I also had the similar issue. adding --privileged option solved the issue for me.
