### ISSUE TITLE
Macvlan swarm IPAM Config erased

### ISSUE THREAD

**Issue by luli74** [moby/moby#34203]
Hello
**Description**

I'm facing an issue with a Macvlan network scoped for the swarm.
When i create the network and inspect it on every manager the configuration is as expected.
But if i try to create a service that use this network the IPAM config is erased.

**Steps to reproduce the issue:**
1. Create a Macvlan network with --scope swarm
` docker network  create  -d macvlan     --subnet=192.168.0.0/24     --gateway=192.168.0.254   --ip-range=192.168.0.64/30  -o parent=eth2.250 --scope swarm macvlan250`
2. Create a service using this network
`docker service create --name nginx-macvlan-swarm --replicas 3 --network macvlan250 nginx`

**Describe the results you received:**
`"Subnet": "172.19.0.0/16",
 "Gateway": "172.19.0.1"`

**Describe the results you expected:**
`"Subnet": "192.168.0.0/24",
                    "IPRange": "192.168.0.64/32",
                    "Gateway": "192.168.0.250"`

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 4
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 Is Manager: true
 Managers: 3
 Nodes: 3
 Node Address: 192.168.0.55
 Manager Addresses:
  192.168.0.55:2377
  192.168.0.56:2377
  192.168.0.57:2377

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian9

**Comment by thaJeztah** [comment]
I _think_ you may have to use the `--config-only` option for this (see https://github.com/moby/moby/pull/32981), because these networks are always node-local, so use the configuration for each host.

ping @mavenugo could you have a look?

**Comment by luli74** [comment]
Thanks.
