### ISSUE TITLE
Can't use swarm-mode services with host network

### ISSUE THREAD

**Issue by joaofnfernandes** [moby/moby#34215]
From what I can understand, #32981 introduced support for using swarm services with node-local networks. The PR also says that I should be able to use the default `bridge` and `host` networks with swarm services, but this doesn't seem to be the case.

**Steps to reproduce the issue**
```
docker service create --name wp --network host --publish target=80,published=8000 wordpress
```

**Expected:** I can access Wordpress using `<node-ip>:8000`
**Got:** Tasks fail with

```
docker inspect <task-id>

...
"Status": {
            "Timestamp": "2017-07-21T17:23:38.219092375Z",
            "State": "rejected",
            "Message": "preparing",
            "Err": "container cannot be disconnected from host network or connected to host network",
            "ContainerStatus": {
                "ContainerID": "331f624c80cb7f34d1f9573194f15c5dd4c8d8dd0ddf70516920252b551b534e"
            },
            "PortStatus": {}
        },
...

```

### Docker version

This is clean machine provisioned by `docker-machine`

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### Docker info

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 1
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: mplq7mvdxo2k5ddxcug171h8o
 Is Manager: true
 ClusterID: obh130rscpe9uga028ee4fb0p
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.764GiB
Name: node-1
ID: BCTP:K7UM:3ONV:7LWJ:YVPQ:GP3F:L6LC:CMT5:7FXY:GNYM:QBE2:NZ3D
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 142
 System Time: 2017-07-21T17:28:08.410379034Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 localhost
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by joaofnfernandes** [comment]
Closing this as a non-issue. The right command is
```
docker service create --name wp --publish mode=host,target=80,published=8000 wordpress
```

**Comment by thaJeztah** [comment]
Actually, `--network host` is also supported now, but can't be used in combination with `--publish` / `-p`. With `--network=host`, there's no need to publish ports, because the container is part of the host's network namespace

**Comment by thaJeztah** [comment]
We should probably improve the error message and/or make these options "conflict"

**Comment by joonas-fi** [comment]
@thaJeztah I just landed here because I accidentally kept trying to publish port when I changed from an overlay network to host networking. Running `18.09.7` and got the OP's error msg.

**Comment by thaJeztah** [comment]
> @thaJeztah I just landed here because I accidentally kept trying to publish port when I changed from an overlay network to host networking. Running 18.09.7 and got the OP's error msg.

Yes, publishing ports is not possible when using `host` networking, because the container won't have its own networking namespace and directly uses the host's network stack (and IP-address); see my comment higher up.

Looks like I never created a ticket to suggest improving the error, so I just created one: https://github.com/moby/moby/issues/40306

**Comment by joonas-fi** [comment]
@thaJeztah  yeah I knew that, sorry I realize my messaging was unclear on my intent. Thanks for responding with grace despite my seeming ignorance.

What I meant to say is "I encountered this same error, maybe the error message should be improved - is there update on the progress?".

Thanks for nudging this forward :)
