### ISSUE TITLE
 Transition /var/run/docker.sock out of moby-core

### ISSUE THREAD

**Issue by mavenugo** [moby/moby#34228]
Based on the project discussions under
https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/57,
Moby Core aims to remove all dependencies on Docker products and Docker trademark. This is important for criteria 1: clarify the relationship to Docker. 

```
Moby Core should plan to get rid of /var/run/docker.sock to clarify thast Moby Core is not Docker.
Of course this should be done gradually, and managed carefully to provide continuity to users.
Consider this a call for volunteers to propose a docker.sock transition plan.
```

**Comment by AkihiroSuda** [comment]
Is this still on roadmap?

cc @thaJeztah @cpuguy83 @andrewhsu @tiborvass

**Comment by thaJeztah** [comment]
Also relates to https://github.com/moby/moby/pull/34226

**Comment by cpuguy83** [comment]
Closing this since this is not something we are going to proceed with at this time.
