### ISSUE TITLE
/proc/pid/cgroup file be changed? why

### ISSUE THREAD

**Issue by y123456yz** [moby/moby#34220]
my docker was started through systemd,
cgroup as following:
[xxx@fd-xxx-xxx~]$ cat /proc/30115/cgroup 
10:perf_event:/docker/c8cef9e2ff114e429cb845559c4a0dff
9:cpuset:/docker/c8cef9e2ff114e429cb845559c4a0dff
8:net_cls:/docker/c8cef9e2ff114e429cb845559c4a0dff
7:devices:/docker/c8cef9e2ff114e429cb845559c4a0dff
6:hugetlb:/docker/c8cef9e2ff114e429cb845559c4a0dff
5:blkio:/docker/c8cef9e2ff114e429cb845559c4a0dff
4:memory:/docker/c8cef9e2ff114e429cb845559c4a0dff
3:cpuacct,cpu:/docker/c8cef9e2ff114e429cb845559c4a0dff
2:freezer:/docker/c8cef9e2ff114e429cb845559c4a0dff
1:name=systemd:/user.slice/user-52321.slice/session-128207.scope

After a period of time， changed as folloing:
[xxx@fd-xxx-slave21 ~]$ cat /proc/30115/cgroup 
10:perf_event:/docker/c8cef9e2ff114e429cb845559c4a0dff
9:cpuset:/docker/c8cef9e2ff114e429cb845559c4a0dff
8:net_cls:/docker/c8cef9e2ff114e429cb845559c4a0dff
7:devices:/user.slice
6:hugetlb:/docker/c8cef9e2ff114e429cb845559c4a0dff
5:blkio:/user.slice
4:memory:/user.slice
3:cpuacct,cpu:/user.slice
2:freezer:/docker/c8cef9e2ff114e429cb845559c4a0dff
1:name=systemd:/user.slice/user-52321.slice/session-128207.scope

systemd version:
[xxx~]$ rpm -qa | grep systemd
systemd-sysv-219-30.el7.x86_64
oci-systemd-hook-0.1.4-4.git41491a3.el7.x86_64
systemd-libs-219-30.el7.x86_64
systemd-219-30.el7.x86_64
systemd-devel-219-30.el7.x86_64
systemd-python-219-30.el7.x86_64

my linux os is centos-7, kernel version:3.10

I use systemd'service to start docker, when the process run, the /proc/pid/cgroup file was changed after a period time, why?
I never restart the docker service.

can you help me? who change the cgroup tasks file?

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. You mention "after some time"; were containers started/stopped in between, other things done on the host? etc.
- Do you have any daemon options/flags set?

**Comment by y123456yz** [comment]
@thaJeztah

[root@xxxxxx]# docker-init  --version
tini version 0.13.0 - git.949e6fa


In my docker.service config-file:
Delegate=false

what's the real effect of Delegate?


thanks

**Comment by y123456yz** [comment]
I don't stop docker, only run docker one time.

**Comment by thaJeztah** [comment]
You're not providing the information that's needed, and adding more questions

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by y123456yz** [comment]
@thaJeztah 

thanks
the following can resolve my question:
https://lists.freedesktop.org/archives/systemd-devel/2016-May/036572.html

thaJeztah, thanks again.
I close the issue.
