### ISSUE TITLE
Rename final built binaries to moby-core-*

### ISSUE THREAD

**Issue by mavenugo** [moby/moby#34222]
Based on the project discussions under 
https://forums.mobyproject.org/t/topic-find-a-good-and-non-confusing-home-for-the-remaining-monolith/37/54

and following the guidance (from the above thread),

```
The BINARY names must share a common prefix, like docker binaries today.

The BINARY names must not require renaming in downstream distros. Specifically Docker CE should ship the binaries under the same names. This means there will be no "dockerd" in Docker CE.

The BINARY names should allow for individual binaries to appear or disappear from one version to the next. In other words binary names should be considered implementation details of the project.
```

The binaries that are built in this moby-core project must be renamed to reflect a more appropriate  name :

```
binary names: moby-core-server , moby-core-init, moby-core-containerd, moby-core-proxy
```

**Comment by mavenugo** [comment]
Addressed by https://github.com/moby/moby/pull/34226

**Comment by AkihiroSuda** [comment]
Is this still on plan? At least not `priority/P1`?

@tiborvass  @cpuguy83 @thaJeztah

**Comment by cpuguy83** [comment]
Closing this since this is not something we are going to proceed with at this time.
