### ISSUE TITLE
Read only filesystem creating services with secrets

### ISSUE THREAD

**Issue by wmartins** [moby/moby#34236]
**Description**

In swarm mode, when I create a new service that has a secret attached, the container never gets up due to "read-only file system".

**Steps to reproduce the issue:**
1. Create a secret (`echo "This is a secret" | docker secret create my_secret_data -`)
2. Create a service using the secret created at `1` (`docker service create --name test --secret my_secret_data nginx:1.13.3`)
3. Check if container is running (`watch docker service ps test`)

**Describe the results you received:**
Instead of having the container up, it's always being shutdown.

If I run ` docker inspect $( docker service ps -q test )`, then I get:

```
"Status": {
	"Timestamp": "2017-07-24T17:04:36.594972392Z",
	"State": "failed",
	"Message": "starting",
	"Err": "starting container failed: RemoveSecretsPath failed: remove /var/lib/docker-latest/containers/a5c17c5ac989e00ff33e1b30f0b57f076359a30b702b316818257544a8a40b3e/secrets/my_secret_data: read-only file system",
	"ContainerStatus": {
		"ContainerID": "a5c17c5ac989e00ff33e1b30f0b57f076359a30b702b316818257544a8a40b3e",
		"ExitCode": 128
	},
	"PortStatus": {}
},
```

**Describe the results you expected:**

I expected the container to be up and running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.7.6
 Git commit:      b303bf6/1.13.1
 Built:           Mon Jun 19 21:38:04 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.7.6
 Git commit:      b303bf6/1.13.1
 Built:           Mon Jun 19 21:38:04 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**

(I removed the ips in the output)

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: active
 NodeID: zqv0r9etlvxdust58wfa0e9v9
 Is Manager: false
 Node Address: ADDRESS
 Manager Addresses:
  ADDRESS
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker-latest/seccomp.json
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: Red Hat
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 5.42 GiB
Name: HOSTNAME
ID: CWJ7:HYXP:5OJK:IR6F:AHHG:7GTB:DN4C:AKFV:B4XH:PEZ2:PD2O:3ILL
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running this on Red Hat on SoftLayer (http://www.softlayer.com/). I'm running using the `docker-latest` version (https://access.redhat.com/articles/2317361).

---

Anyone else had this kind of problem?

If I opened this issue in the wrong place or if you need any other information, please let me know!

**Comment by thaJeztah** [comment]
You're running the Red Hat fork of Docker, which contains tons of modifications from the official packages; are you also seeing this problem when running the official packages? https://docs.docker.com/engine/installation/

**Comment by wmartins** [comment]
@thaJeztah, I just installed `docker-ce` (v17.06.0-ce) and now everything looks fine.

Just to know, are there any concerns running "non Red Hat" versions in "production" when using Red Hat?

Thank you!

**Comment by thaJeztah** [comment]
I don't see what concerns there should be running the official version instead of a fork 😇.  the Red Hat fork contains functional changes that were not accepted upstream, and actual caused a lot of headaches

**Comment by wmartins** [comment]
@thaJeztah, yeah, I'm asking more because our infrastructure team will ask us about why we're not using the "recommended" (from Red Hat packages) docker version. I'll reference this issue to them, just in case!

**Comment by thaJeztah** [comment]
Sure!

Let me close this issue as it looks to be resolved, but feel free to continue the conversation

**Comment by shykes** [comment]
@wmartins the packages distributed by Red Hat are heavily patched, supposedly to "add value", but in practice they are mostly hacks to work around problems in their legacy OS without concern for the integrity of the platform, or long-term maintenance. Red Hat patches routinely introduce stability issues and even security vulnerabilities. Several CVEs attributed to Docker are in fact introduced by Red Hat's fork.

Red Hat has done such a terrible job at distributing Docker that we are considering changed to the trademark policy to limit the damage they cause.

**Comment by wmartins** [comment]
@shykes, that's so sad. I'll definitely spread this information to our teams here.

Thank you for your awesome explanation!

**Comment by runcom** [comment]
> @wmartins the packages distributed by Red Hat are heavily patched, supposedly to "add value", but in practice they are mostly hacks to work around problems in their legacy OS without concern for the integrity of the platform, or long-term maintenance. Red Hat patches routinely introduce stability issues and even security vulnerabilities. Several CVEs attributed to Docker are in fact introduced by Red Hat's fork.

Our security response team analyzed the CVE databases to see if there was any validity to your last statement "Several CVEs attributed to Docker are in fact introduced by Red Hat's fork". The security response team went through the usual sources (our databases, Docker's, cvedetails.com, cve.circl.lu, etc etc) and checked every Docker related CVE. They weren't able to find a single CVE that Projectatomic patched version of Docker introduced. If you know of any CVEs in our patched version please tell us so that we can get them fixed and reviewed by the Security Response team. If there are none, we request this message to be removed.

**Comment by johannges** [comment]
> Our security response team analyzed the CVE databases to see if there was any validity to your last statement "Several CVEs attributed to Docker are in fact introduced by Red Hat's fork". The security response team went through the usual sources (our databases, Docker's, cvedetails.com, cve.circl.lu, etc etc) and checked every Docker related CVE. They weren't able to find a single CVE that Projectatomic patched version of Docker introduced. If you know of any CVEs in our patched version please tell us so that we can get them fixed and reviewed by the Security Response team. If there are none, we request this message to be removed.

It would still be nice if this issue would be resolved in the Red Hat Docker Version.
We are using Version:
> Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)

Is there a Red Hat Version where the issue is resolved?

**Comment by timothyjmtan** [comment]
+1 to the above query. I am also experiencing the same issue as OP and unable to find a solution moving forward. Is there a workaround to use, or a Red Hat version where the original issue is resolved?

**Comment by thaJeztah** [comment]
@timothyjmtan either install the official Docker package using the instructions in the Documentation https://docs.docker.com/install/, or open a support ticket with Red Hat

**Comment by AhmedAnwarM** [comment]
Did anyone find a fix for this issue? I'm also using Red Hat's docker distribution and I have the same issue...

My 'docker version' command output is below

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-203.git0be3e21.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Tue Oct 27 11:31:12 2020
 OS/Arch:         linux/amd64
 
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-203.git0be3e21.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      0be3e21/1.13.1
 Built:           Tue Oct 27 11:31:12 2020
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by wmartins** [comment]
Hey @AhmedAnwarM, in my case, I just gave up using the Red Hat's distribution and installed docker engine manually. I don't know if that's a possibility for you, but in my case it fixed the problem.
