### ISSUE TITLE
Docker Build returns Error code 100

### ISSUE THREAD

**Issue by SayaniDey1** [moby/moby#34230]
**Description**

I am trying to create a Docker for SoapUI. The Dockerfile being the following:

```Dockerfile
FROM tibco/bwce:latest

MAINTAINER tibco

#  Version
ENV SOAPUI_VERSION 5.3.0

COPY Rest.xml /opt/bin/Rest.xml

RUN chmod +x /opt/bin/Rest.xml

# Download and unarchive SoapUI
RUN  apt-get update && apt-get install -y --force-yes wget && rm -rf /var/lib/apt/lists/*
RUN wget https://www.dropbox.com/s/shz5d3b8ppvw150/SoapUI-x64-5.3.0.sh?dl=0

# Set working directory
WORKDIR /opt/bin

# Set environment
ENV PATH ${PATH}:/opt/SoapUI/bin

EXPOSE 3000
#CMD["/opt/bin/Rest.xml"]
```

At `step 6: RUN  apt-get update && apt-get install -y --force-yes wget && rm -rf /var/lib/apt/lists/*` It is showing error. Kindly Help me solve this issue. :) 

The XML file used is as follows:

<?xml version="1.0" encoding="UTF-8"?>
<con:soapui-project id="d4f0816d-1cde-4797-a134-77a49a43d099" activeEnvironment="Default" name="REST Project 1" resourceRoot="" soapui-version="5.3.0" abortOnError="false" runType="SEQUENTIAL" xmlns:con="http://eviware.com/soapui/config"><con:settings/><con:interface xsi:type="con:RestService" id="1c79b0af-dc7e-4e76-8bad-7a3bbd91d7b4" wadlVersion="http://wadl.dev.java.net/2009/02" name="http://10.0.2.15:9620" type="rest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:settings/><con:definitionCache type="TEXT" rootPart=""/><con:endpoints><con:endpoint>http://10.0.2.15:9620</con:endpoint></con:endpoints><con:resource name="Customer" path="/getdetails/customer" id="2b14e707-67c9-419c-84e1-4fef6e532eac"><con:settings/><con:parameters><con:parameter><con:name>gsm_number</con:name><con:value>9987654321</con:value><con:style>QUERY</con:style><con:default>9987654321</con:default><con:path xsi:nil="true"/><con:description xsi:nil="true"/></con:parameter></con:parameters><con:method name="Customer 1" id="e6a240ff-7a35-4820-b880-3f618db5d85f" method="GET"><con:settings/><con:parameters/><con:representation type="FAULT"><con:mediaType>text/html;charset=ISO-8859-1</con:mediaType><con:status>400</con:status><con:params/><con:element>html</con:element></con:representation><con:representation type="RESPONSE"><con:mediaType xsi:nil="true"/><con:status>0</con:status><con:params/><con:element>data</con:element></con:representation><con:representation type="RESPONSE"><con:mediaType>application/json;charset=UTF-8</con:mediaType><con:status>200</con:status><con:params/><con:element xmlns:cus="http://10.0.2.15/getdetails/customer">cus:Response</con:element></con:representation><con:representation type="FAULT"><con:mediaType>text/plain</con:mediaType><con:status>500</con:status><con:params/><con:element>data</con:element></con:representation><con:request name="Request 1" id="9d57e9f4-ae54-4dd4-921f-9c96ed397de4" mediaType="application/json"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;entry key="Accept" value="application/json" xmlns="http://eviware.com/soapui/config"/></con:setting></con:settings><con:endpoint>http://tibco.local:9620</con:endpoint><con:request/><con:originalUri>http://10.0.2.15/getdetails/customer</con:originalUri><con:credentials><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters/><con:parameterOrder><con:entry>gsm_number</con:entry></con:parameterOrder></con:request></con:method></con:resource></con:interface><con:testSuite id="e6077c55-4fa4-4435-8976-eadeb1b68a30" name="TestSuite 1"><con:settings/><con:runType>SEQUENTIAL</con:runType><con:testCase id="7b1da7ec-72f0-4857-b6c7-b2244a9f8ade" failOnError="true" failTestCaseOnErrors="true" keepSession="false" maxResults="0" name="TestCase 1" searchProperties="true"><con:settings/><con:testStep type="restrequest" name="Good Data" id="4f379948-4195-472a-9d5d-91ee6c633c60"><con:settings/><con:config service="http://10.0.2.15:9620" resourcePath="/getdetails/customer" methodName="Customer 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:restRequest name="REST Request" id="9d57e9f4-ae54-4dd4-921f-9c96ed397de4" mediaType="application/json"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;entry key="Accept" value="application/json" xmlns="http://eviware.com/soapui/config"/></con:setting></con:settings><con:endpoint>http://10.0.2.15:9620</con:endpoint><con:request/><con:originalUri>http://10.0.2.15/getdetails/customer</con:originalUri><con:assertion type="Valid HTTP Status Codes" id="2990776b-c73a-4427-9f30-c21d53681032" name="Valid HTTP Status Codes"><con:configuration><codes>500</codes></con:configuration></con:assertion><con:credentials><con:username/><con:password/><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters><entry key="gsm_number" value="0000" xmlns="http://eviware.com/soapui/config"/></con:parameters><con:parameterOrder><con:entry>gsm_number</con:entry></con:parameterOrder></con:restRequest></con:config></con:testStep><con:testStep type="restrequest" name="Bad Data" id="24ddbeac-958a-47f4-9b5d-e0248b9fb83e"><con:settings/><con:config service="http://10.0.2.15:9620" resourcePath="/getdetails/customer" methodName="Customer 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:restRequest name="Bad Data" id="9d57e9f4-ae54-4dd4-921f-9c96ed397de4" mediaType="application/json"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;entry key="Accept" value="application/json" xmlns="http://eviware.com/soapui/config"/></con:setting></con:settings><con:endpoint>http://10.0.2.15:9620</con:endpoint><con:request/><con:originalUri>http://10.0.2.15/getdetails/customer</con:originalUri><con:assertion type="Invalid HTTP Status Codes" id="bae01ebe-2ad6-4c3d-8635-5bb686bf40f7" name="Invalid HTTP Status Codes"><con:configuration><codes>500, 400</codes></con:configuration></con:assertion><con:assertion type="JsonPath Match" id="3f7f2aa8-6c69-4598-9dcc-bed5248dac39" name="First"><con:configuration><path>$.CustomerDetail[:1].First_Name</path><content>[Henry]</content><allowWildcards>false</allowWildcards><ignoreNamspaceDifferences>false</ignoreNamspaceDifferences><ignoreComments>false</ignoreComments></con:configuration></con:assertion><con:assertion type="JsonPath Match" id="3f7f2aa8-6c69-4598-9dcc-bed5248dac39" name="LastName"><con:configuration><path>$.CustomerDetail[:1].Last_Name</path><content>[Andrew]</content><allowWildcards>false</allowWildcards><ignoreNamspaceDifferences>false</ignoreNamspaceDifferences><ignoreComments>false</ignoreComments></con:configuration></con:assertion><con:credentials><con:username/><con:password/><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters><entry key="gsm_number" value="9987654321" xmlns="http://eviware.com/soapui/config"/></con:parameters><con:parameterOrder><con:entry>gsm_number</con:entry></con:parameterOrder></con:restRequest></con:config></con:testStep><con:properties/></con:testCase><con:properties/></con:testSuite><con:properties/><con:wssContainer/><con:oAuth2ProfileContainer/><con:oAuth1ProfileContainer/><con:sensitiveInformation/></con:soapui-project>

**Steps to reproduce the issue:**
1.docker build -t rest . 

**Describe the results you received:**
[root@tibco Soap-ing]# docker build -t rest .
Sending build context to Docker daemon  9.216kB
Step 1/10 : FROM tibco/bwce:latest
 ---> 9c8245fefeca
Step 2/10 : MAINTAINER tibco
 ---> Using cache
 ---> bebdfef8b85f
Step 3/10 : ENV SOAPUI_VERSION 5.3.0
 ---> Using cache
 ---> 52da46652b37
Step 4/10 : COPY Rest.xml /opt/bin/Rest.xml
 ---> Using cache
 ---> 513ac0aa43d6
Step 5/10 : RUN chmod +x /opt/bin/Rest.xml
 ---> Using cache
 ---> 4dbd0a783038
Step 6/10 : RUN apt-get update && apt-get install -y --force-yes wget && rm -rf /var/lib/apt/lists/*
 ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
 ---> Running in 2d251ad256d1
Err http://deb.debian.org jessie InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org jessie Release.gpg
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  ca-certificates libffi6 libgmp10 libgnutls-deb0-28 libhogweed2 libicu52
  libidn11 libnettle4 libp11-kit0 libpsl0 libtasn1-6 openssl
Suggested packages:
  gnutls-bin
The following NEW packages will be installed:
  ca-certificates libffi6 libgmp10 libgnutls-deb0-28 libhogweed2 libicu52
  libidn11 libnettle4 libp11-kit0 libpsl0 libtasn1-6 openssl wget
0 upgraded, 13 newly installed, 0 to remove and 1 not upgraded.
Need to get 9748 kB of archives.
After this operation, 35.6 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libffi6 libtasn1-6 libgnutls-deb0-28
Err http://security.debian.org/ jessie/updates/main libffi6 amd64 3.1-2+deb8u1
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org/debian/ jessie/main libgmp10 amd64 2:6.0.0+dfsg-6
  Temporary failure resolving 'deb.debian.org'
Err http://security.debian.org/ jessie/updates/main libtasn1-6 amd64 4.2-3+deb8u3
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org/debian/ jessie/main libnettle4 amd64 2.7.1-5+deb8u2
  Temporary failure resolving 'deb.debian.org'
Err http://security.debian.org/ jessie/updates/main libgnutls-deb0-28 amd64 3.3.8-6+deb8u6
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org/debian/ jessie/main libhogweed2 amd64 2.7.1-5+deb8u2
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main libp11-kit0 amd64 0.20.7-1
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main libidn11 amd64 1.29-1+deb8u2
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main libicu52 amd64 52.1-8+deb8u5
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main libpsl0 amd64 0.5.1-1
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main wget amd64 1.16-1+deb8u2
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main openssl amd64 1.0.1t-1+deb8u6
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org/debian/ jessie/main ca-certificates all 20141019+deb8u3
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gmp/libgmp10_6.0.0+dfsg-6_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/n/nettle/libnettle4_2.7.1-5+deb8u2_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/n/nettle/libhogweed2_2.7.1-5+deb8u2_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/libf/libffi/libffi6_3.1-2+deb8u1_amd64.deb  Temporary failure resolving 'security.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/p11-kit/libp11-kit0_0.20.7-1_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/libt/libtasn1-6/libtasn1-6_4.2-3+deb8u3_amd64.deb  Temporary failure resolving 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/g/gnutls28/libgnutls-deb0-28_3.3.8-6+deb8u6_amd64.deb  Temporary failure resolving 'security.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/libi/libidn/libidn11_1.29-1+deb8u2_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/i/icu/libicu52_52.1-8+deb8u5_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/libp/libpsl/libpsl0_0.5.1-1_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/w/wget/wget_1.16-1+deb8u2_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openssl/openssl_1.0.1t-1+deb8u6_amd64.deb  Temporary failure resolving 'deb.debian.org'

E: Failed to fetch http://deb.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20141019+deb8u3_all.deb  Temporary failure resolving 'deb.debian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y --force-yes wget && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[root@tibco Soap-ing]# docker run -it --rm debian:jessie apt-get update
WARNING: IPv4 forwarding is disabled. Networking will not work.
Err http://deb.debian.org jessie InRelease                           
  
Err http://security.debian.org jessie/updates InRelease              
  
Err http://deb.debian.org jessie-updates InRelease                   
  
Err http://security.debian.org jessie/updates Release.gpg            
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org jessie Release.gpg
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done    
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by tonistiigi** [comment]
This doesn't look like builder specific but general lack of networking because IP forwarding is disabled. You can try `docker build --net=host` to use host networking instead. If you don't know why your system would not allow networking start by posting `docker info` in here.

**Comment by thaJeztah** [comment]
closing because this went stale
