### ISSUE TITLE
Overlay network doesn't resolve service names *randomly

### ISSUE THREAD

**Issue by japrogramer** [moby/moby#34240]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
-->

Sometimes for whatever reason i can no longer ping my services by their names from within my containers.

**Steps to reproduce the issue:**
1. It randomly start happening.
2.
3.

**Describe the results you received:**
My apps stop working, I depend on name resolution in many scripts at entry point and also 
for the service encapsulated in the containers.

**Describe the results you expected:**
It usually works, but when this bug shows up i have tried this steps but the problem persists between restarting the docker daemon. 
```
docker stack rm website
docker swarm leave --force
sudo systemctl stop docker.service
sudo systemctl start docker.service
docker swarm init --force-new-cluster
```
So that got me thinking that if i deleted the /docker/swarm directory maybe the problem would go away
so this are the steps i than took and after wards name resolution started working again.
```
docker stack rm website
docker swarm leave --force
sudo systemctl stop docker.service
sudo sh -c "rm -fR /docker/swarm"
sudo systemctl start docker.service
docker swarm init --force-new-cluster
```
So even tho i have found a `solution` I really don't think this should be happening especially when i pass the flag --force-new-cluster
The draw back of my solution, is that i loose all my secrets and conf stored by docker 👎 
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version                                                                Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Sat Jul  8 22:56:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 17.06.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.11.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: wnuybka35u415a3673pkxbdpq
 Is Manager: true
 ClusterID: ib98cpu9lck696156wonlcpsl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.0.102
 Manager Addresses:
  192.168.0.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.9-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.758GiB
Name: The_Black_Knight
ID: SV34:IXUH:FWPN:RJOY:AH3Y:XW6D:4GCM:MFVA:M57K:IQQW:S55Z:JXZE
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by caiges** [comment]
I'm also running into this issue. Having all nodes leave the swarm, re-init the swarm and finally have the nodes join allows services to resolve each other. I'm also running the same version of Docker but on AWS.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
