### ISSUE TITLE
Failing healthcheck produces no logfile entry in Docker swarm

### ISSUE THREAD

**Issue by synergiator** [moby/moby#34254]
We use Docker Swarm with about a couple of dozens of containers and with Spark we have a strange behaviour that workers get SIGTERM signal. We consider that this because of failing healtchcheck or some other reason. So, on disabling healthcheck it happens too.

We are anyway quite sure that this SIGTERM comes from Docker.

```
Jul 26 10:58:07 host dockerd[3931]: time="2017-07-26T10:58:07.396665258+02:00" level=error msg="Handler for GET /v1.22/volumes/dbd393598f21945b5d4b42131471580198890954873a2560ef65ce03e1f24a76 returned error: get dbd393598f2194
Jul 26 10:58:11 host dockerd[3931]: time="2017-07-26T10:58:11.223446887+02:00" level=error msg="Error closing logger: invalid argument"
Jul 26 10:58:11 host dockerd[3931]: time="2017-07-26T10:58:11.284294384+02:00" level=error msg="Could not delete service state for endpoint dev01_spark-worker.1.rvw9wtz22vu3ky3muhi2igyq5 from cluster: cannot delete entry as th
Jul 26 10:58:11 host dockerd[3931]: time="2017-07-26T10:58:11.575931413+02:00" level=error msg="fatal task error" error="task: non-zero exit (143): dockerexec: unhealthy container" module="node/agent/taskmanager" task.id=rvw9w
Jul 26 10:58:17 host dockerd[3931]: time="2017-07-26T10:58:17+02:00" level=info msg="Firewalld running: false"

```

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
