### ISSUE TITLE
Add logging driver for Azure Log Analytics (part of OMS)

### ISSUE THREAD

**Issue by heaths** [moby/moby#34257]
Similar to other log drivers available with docker and dockerd, a group of us would like to contribute a logging driver for OMS that pumps messages from containers into OMS. We already have a good start.

Reading through _CONTRIBUTING.md_ we wanted to get this on the radar and have any discussions as needed prior to our initial PR. We want to contribute this into moby so its readily available and also because separate plugin modules are not yet supported on Windows (at least in the stable releases of Docker).

Current log driver inputs are merely the workspace ID (aka customer ID) and shared key (either primary or secondary key). Similar to the splunk driver we are batching messages and are considering supporting options for tweaking batch sizes. The current driver also puts messages back in the queue to support `docker logs`.

**Comment by cpuguy83** [comment]
I would prefer to have this implemented as a plugin rather than in the core.

**Comment by cpuguy83** [comment]
https://github.com/docker/cli/blob/master/docs/extend/plugins_logging.md

**Comment by darobs** [comment]
We considered other possibilities along with making a logging driver plugin. 
 
The benefits we found to having a builtin logging driver:
 
1. Immediate availability. 

It gives the user the option to have logging available without any additional installation needed.  All the end user needs is to set two values from OMS to start logging to the service.

2. Plugin support for Windows.

In my own project we're investing into container technology and are committed to Windows support. This logging driver gets us and all other customers the Windows support needed now.

3. Logging options per container.

Our project wants to support per container logging options (not all containers on a host). I didn't see it - does this option exist for a logging plugin?

**Comment by thaJeztah** [comment]
Logging plugins provide the same functionality as built in drivers, thus per container logs; daemon logs are using the systems functionality so are separate from that

**Comment by heaths** [comment]
Understood, but Docker for Windows does not support plugins currently. The _omslogs_ driver - much like the _awslogs_ driver - communicates over REST APIs so it is not tied to any operating system. We have successfully tested this on linux and Windows hosts using linux and Windows containers.

**Comment by ddebroy** [comment]
Do logger plugins work right now for Windows hosts?

**Comment by ddebroy** [comment]
@heaths I was curious what is the work involved here. Is the log driver for OMS going to be a port of the fluentd based https://github.com/Microsoft/OMS-Agent-for-Linux but specifically geared towards collecting container logs? 

Are the REST APIs that you refer to above documented somewhere?

**Comment by heaths** [comment]
@ddebroy see https://github.com/heaths/moby/tree/omslogs/daemon/logger/omslogs. It borrows some concepts more from the _splunk_ driver in terms of batching messages, but uses a REST client we wrote that is currently included (again, like _splunk_, though we separated ours out for easy replacement if Azure will pick it up as a separate library).

We're also curious if every commit has to be signed off, or at least just the branch HEAD prior to a PR. We're not in the habit of signing off on commits and forgot a couple of times. We can squash but I was hoping to preserve the contribution history unless the project would prefer PRs are squashed anyway.

**Comment by thaJeztah** [comment]
> We're also curious if every commit has to be signed off

every commit that's part of the pull request has to be signed off, otherwise CI will fail, however vendored code doesn't have to be signed off; it does need a suitable license though (vendored dependencies)

**Comment by ddebroy** [comment]
Thanks for the pointer @heaths. A couple of concerns:
1. The OMS `sharedKey` is a secret. When configuring OMS logging, keeping this secret around in plain text in daemon.json or in the container parameter `--log-opt` is potentially insecure. In case of AWS/GCP, IAM roles is a decent workaround for this (when the docker host is running in the respective cloud). Is there something similar in Azure for OMS/Logging that will allow the admin to not reveal the secret key? I believe plugins (will) have support for swarm secrets that may help here if the secret key is the only option to create the OMS client.

2. The endpoint URL: `ods.opinsights.azure.com` should be made configurable so that different Azure environments like Azure Government, Azure Stack, etc. could be supported. For Gov, the endpoint appears to be: `ods.opinsights.azure.us`

**Comment by ddebroy** [comment]
Another interesting datapoint: the fluentD plugin (which is already baked in to Docker engine today) can be used to achieve the same original purpose by using a fluentD output plugin that sends logs to OMS. For example: https://github.com/yokawasa/fluent-plugin-azure-loganalytics / https://rubygems.org/gems/fluent-plugin-azure-loganalytics

The fluentD plugin solution does seem to have the drawback of having to configure the OMS `key` in plaintext in the configuration.

**Comment by heaths** [comment]
Seems fluentd is not stable on Windows, which does not make it a likely candidate for the stated goal of running on Windows hosts: https://www.fluentd.org/download

**Comment by friism** [comment]
@cpuguy83 @thaJeztah since there's no way to run logging plugins on Windows hosts yet, do you think it might make sense to accept more baked-in log drivers, at least if they're applicable to Windows (like this one might be).

**Comment by heaths** [comment]
Anything more changes or discussion needed here?

**Comment by cpuguy83** [comment]
I'd still prefer not to add another in-tree driver.
If we need to make more changes to docker to support plugins on Windows then we should.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
