### ISSUE TITLE
Why is `/proc/[pid]/maps` can not be accessed by root

### ISSUE THREAD

**Issue by SamSaffron** [moby/moby#34262]
I am trying to debug a memory issue and noticing something weird. 

I have a process created by non-root inside my container. `adduser` to create it. 

It has access to `/proc/[pid]/maps`... however, root can not access it and gets an access denied. 

Simple repro is 

```
docker run -it --rm ubuntu
% adduser bob
% su bob
% sleep 100&
% ps aux (find process)
% cat /proc/[pid]/maps (works)
% exit 
% cat /proc/[pid]/maps (does not work)
```

Why is this happening? Do I need to launch my container in privileged mode?

**Comment by justincormack** [comment]
Please can you give the requested details when opening an issue, or it
makes it very difficult to help.

It is probably apparmor denying that, try disabling it when running the
container.

**Comment by SamSaffron** [comment]
Possible, thing is even if I sorted this I would still be stuck not being able to attach to the process, so I guess you can just close this for now and I can live with running containers that I need to debug in --privileged mode
