### ISSUE TITLE
Unsuccessful push to Docker Hub: unexpected end of JSON input

### ISSUE THREAD

**Issue by dgencare** [moby/moby#34267]
I have one large image that I cant successful push to docker hub. All others smaller images push with no problems. All output bellow is from a fresh Ubuntu 16.04 install on bare metal hardware.

Error in the log:
\level=error msg="Upload failed: error parsing HTTP 403 response body: unexpected end of JSON input: """
level=info msg="Attempting next endpoint for push after error: error parsing HTTP 403 response body: unexpected end of JSON input: """

docker version
Client:
Version: 17.06.0-ce
API version: 1.30
Go version: go1.8.3
Git commit: 02c1d87
Built: Fri Jun 23 21:23:31 2017
OS/Arch: linux/amd64

Server:
Version: 17.06.0-ce
API version: 1.30 (minimum version 1.12)
Go version: go1.8.3
Git commit: 02c1d87
Built: Fri Jun 23 21:19:04 2017
OS/Arch: linux/amd64
Experimental: false

docker info
Containers: 5
Running: 0
Paused: 0
Stopped: 5
Images: 17
Server Version: 17.06.0-ce
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 27
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.10.0-27-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name: ns526323.ip-149-56-16.net
ID: FBIS:EA3L:MT6G:O3WG:VM7L:R4H2:2GKD:XEMR:2OGO:2FJO:457G:4YPN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dgencare
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support

uname -a
Linux ns526323.ip-149-56-16.net 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Could you try contacting support@docker.com with details about the image you're pushing, and which repository/account you're pushing to? The error looks to be due to a 403 error (access denied) coming from Docker Hub

Just to be sure;

- you are not behind a proxy?
- if this is a private repository; you did not reach the maximum amount of private repositories for your plan/account?

**Comment by dgencare** [comment]
- There is no proxy.

- This is a private repository but I still have 20 open slots.
> Private Repositories:Using 30 of 50

**Comment by thaJeztah** [comment]
Hm, ok; I do recall (long time ago) an issue around image layers larger than 5GB, but the Docker Hub support team should be able to help you with that. So, yes, I'd definitely recommend contacting them ; if there's an issue on Hub's side they can probably obtain more information from the logs

**Comment by dgencare** [comment]
The total image size is about 80 gigs and I believe the largest layer is around 37 gigs.

Thanks for help. I've sent an email to support. Hopefully there will be some easy fix for this.

**Comment by thaJeztah** [comment]
Wow, that is one _huge_ image

Let me close this issue for now, but keep me posted
