### ISSUE TITLE
Swarm mode manager (default overlay network) not reachable from worker node

### ISSUE THREAD

**Issue by dvohra** [moby/moby#34266]
**Description**

A Swarm mode (default `overlay` network) manager node is not reachable from worker node.

**Steps to reproduce the issue:**
1.Create a Swarm on Docker for AWS (1 manager and 2 worker nodes)
2.Create a Docker service (a `tutum/hello-world` service or other service) with 3 replicas, which has one task on each node
3.From bash shell of a Docker container for the service task on worker node ping IP address of a Docker container for the service task on manager node. 

**Describe the results you received:**

```
root@152b83241e6b:/# ping 172.17.0.6
PING 172.17.0.6 (172.17.0.6): 56 data bytes
92 bytes from 152b83241e6b (172.17.0.5): Destination Host Unreachable
92 bytes from 152b83241e6b (172.17.0.5): Destination Host Unreachable
92 bytes from 152b83241e6b (172.17.0.5): Destination Host Unreachable
92 bytes from 152b83241e6b (172.17.0.5): Destination Host Unreachable
^C--- 172.17.0.6 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
```

**Describe the results you expected:**
The same result as for connecting from one worker node to another worker node or from manager node to worker node. 
```
root@152b83241e6b:/# ping 172.17.0.5
PING 172.17.0.5 (172.17.0.5): 56 data bytes
64 bytes from 172.17.0.5: icmp_seq=0 ttl=64 time=0.040 ms
64 bytes from 172.17.0.5: icmp_seq=1 ttl=64 time=0.059 ms
64 bytes from 172.17.0.5: icmp_seq=2 ttl=64 time=0.050 ms
64 bytes from 172.17.0.5: icmp_seq=3 ttl=64 time=0.053 ms
64 bytes from 172.17.0.5: icmp_seq=4 ttl=64 time=0.051 ms
64 bytes from 172.17.0.5: icmp_seq=5 ttl=64 time=0.051 ms
64 bytes from 172.17.0.5: icmp_seq=6 ttl=64 time=0.047 ms
^C--- 172.17.0.5 ping statistics ---
7 packets transmitted, 7 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.040/0.050/0.059/0.000 ms

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
~ $ docker --version 
Docker version 17.06.0-ce, build 02c1d87

```

**Output of `docker info`:**

```
~ $ docker info
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 6
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: tb5agvzbi0rupq7b83tk00cx3
 Is Manager: true
 ClusterID: iwl5krvm1tqy62dxgwyf9lqlz
 Managers: 1
 Nodes: 3

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for AWS Stable CE
If a custom overlay network is created with `--driver overlay`  and a service created in the network, the worker nodes are able to connect (ping) manager node.

**Comment by dvohra** [comment]
Seems like the Docker for AWS Swarm networking is different from a Swarm mode initialized from a standalone Docker Engine. Also getting another issue with Docker for Swarm networking. 
https://github.com/docker/for-aws/issues/78

**Comment by dvohra** [comment]
Issue is not just for Docker for AWS but also applies for Swarm initialized on 3 CoreOS instances.
```
```

core@ip-172-30-2-163 ~ $ docker --version
Docker version 1.12.6, build a82d35e

core@ip-172-30-2-163 ~ $ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active

```

1. Create a Service in default Swarm network.
core@ip-172-30-2-7 ~ $ docker service create \
>   --env MYSQL_ROOT_PASSWORD='mysql'\
>   --replicas 3 \
>   --name mysql \
>  mysql
42nyazksad09kkxe1rf0hvtdj

```
2. Create a standalone Docker container.
```
core@ip-172-30-2-7 ~ $ docker run --name mysqldb  -itd  -e MYSQL_DATABASE='mysqldb' -e MYSQL_USER='mysql' -e MYSQL_PASSWORD='mysql' -e MYSQL_ALLOW_EMPTY_PASSWORD='no' -e MYSQL_ROOT_PASSWORD='mysql' mysql
ef964596c0bdbd6f9ae0d4c24f8cbf5068e42d1354f9d52a8f82d570a8461169

```

3. List Docker containers for the service and standalone.
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ef964596c0bd        mysql               "docker-entrypoint.sh"   4 seconds ago       Up 3 seconds        3306/tcp            mysqldb
af47fd62d693        mysql:latest        "docker-entrypoint.sh"   4 minutes ago       Up 4 minutes        3306/tcp            mysql.1.3d8nvc8kgtvkuxxrvf2w3l6au

```

4. Ping Standalone container from Docker service container and vice versa.

**Comment by dvohra** [comment]
Issue does not apply to Swarm initialized on CoreOS instances.

**Comment by thaJeztah** [comment]
Be sure to also try using something different than ping; ping is "special" and can be blocked (or in case of virtual ip's not always supported cross-host)

**Comment by dvohra** [comment]
Seems to be a Docker for AWS specific setting for `ingress` because a custom `overlay` network on Docker for AWS does connect from worker node to manager node.

**Comment by dvohra** [comment]
Another difference between `ingress` on CoreOS and Docker for AWS is that the IP Addresses of the Docker containers in a service in `ingress` default network are the same for CoreOS Swarm mode and different for Docker for AWS Swarm.  Is any requirement specified on the IP addresses of the Docker containers in a service in `ingress` network?

**Comment by thaJeztah** [comment]
The _ingress_ network is only for the routing mesh / ingress traffic, i.e. not to be used as a regular network connection between tasks / services. Services are automatically connected to the ingress network when publishing a port, and containers for those services should not be automatically accessible to other services (apart from the ports that are published). If the CoreOS package allows the ingress network to be used for normal communication, that sounds like an issue

What version of docker are you running on CoreOS? Is it using a different networking driver?

> Is any requirement specified on the IP addresses of the Docker containers in a service in ingress network? For a custom overlay network service containers have different IP Addresses on CoreOS Swarm also.

The IP address pools by default are picked from a set of possible ranges; if docker detects the range is already in use, it picks a different range. Note that on modern kernels, the overlay networks are allowed to overlap with the underlay network (it's in a separate networking namespace, so multiple networks can have the same IP-addresses)

Be aware that there are no official Docker packages for CoreOS, so there may be differences in their version

**Comment by dvohra** [comment]
> The ingress network is only for the routing mesh / ingress traffic, i.e. not to be used as a regular network connection between tasks / services. 
Which suggests Docker for AWS `ingress` is configured fine and CoreOS ingress is not.

> What version of docker are you running on CoreOS? Is it using a different networking driver?
`docker --version` and `docker info` output is in an earlier post.

**Comment by dvohra** [comment]
If `ingress` is not for regular network connectivity, why is a Docker container in default `docker0` network able to ping a Docker container in the default Swarm overlay network `ingress`  and vice versa?  Refer https://github.com/moby/moby/issues/34269 which is not CoreOS specific but also applies to Docker for AWS. Is `ingress` network designed for _ingress_ connectivity but other connectivity not excluded by design?

**Comment by thaJeztah** [comment]
@dvohra services are only connected to the ingress network when a port is published; if no port is published, and no explicit network is set, containers (including those backing a service) default to the default (`bridge`) network, so will be in the same network as containers started with `docker run` on the same host.

I brought this up recently, and we're discussing if that behaviour should be changed.

**Comment by thaJeztah** [comment]
Also; (I see docker 1.12.6 in your other issue - if that's the version of docker on CoreOS, I think the ingress network still allowed regular traffic in that version; this changed in a later version)

**Comment by dvohra** [comment]
> Also; (I see docker 1.12.6 in your other issue - if that's the version of docker on CoreOS, I think the ingress network still allowed regular traffic in that version; this changed in a later version)

Docker for AWS which has Docker 1.17.x does not have regular traffic for `ingress` and Host is unreachable from worker node to manager node connectivity.

**Comment by dvohra** [comment]
services are only connected to the ingress network when a port is published; if no port is published, and no explicit network is set, containers (including those backing a service) default to the default (bridge) network, so will be in the same network as containers started with docker run on the same host.

The `docker run` command does not accept the `--network` option to connect to a Swarm network. A Docker container started with `docker run` shouldn't be able to connect to a Swarm network either. But as indicated in the other issue https://github.com/moby/moby/issues/34269  network connectivity is available between default network and Swarm overlay network.

**Comment by thaJeztah** [comment]
The service is created without a network specified; therefore the containers backing it will use the `bridge` network, similar to containers started with `docker run`;

```
docker service create \
   --env MYSQL_ROOT_PASSWORD='mysql'\
   --replicas 1 \
   --name mysql \
  mysql
```

**Comment by dvohra** [comment]
For a Docker service in an overlay network, not able to connect to a Docker container in the default network. But, the ingress routing mesh (network) is available for each service regardless of whether a custom overlay network is specified.  "If you do not specify a port, the swarm manager assigns the service a port in the 30000-32767 range." Should a service container be accessible other than on the ingress network. Shouldn't a default overlay network be created for services? Several load balancers are provisioned for a service, regardless:

-Ingress load balancer for balancing load among service tasks
-Internal load balancer for balancing load among different services
-Provision for an external load balancer to balance load among nodes

**Comment by dvohra** [comment]
> services are only connected to the ingress network when a port is published; if no port is published, and no explicit network is set, containers (_including those backing a service_) default to the default (bridge) network,

But isn't a port created automatically by the Swarm manager for a service?

**Comment by thaJeztah** [comment]
No; a port is not assigned if you do not have the `-p` / `--publish` flag set. (In addition, services require setting up the mapped port, no random port mapping)

**Comment by dvohra** [comment]
What does the "The swarm manager can automatically assign the service a PublishedPort or you can configure a PublishedPort for the service. You can specify any unused port. If you do not specify a port, the swarm manager assigns the service a port in the 30000-32767 range." refer to in the Load Balancing section.
https://docs.docker.com/engine/swarm/key-concepts/#load-balancing

Not mentioned that it assumes the `-p` or `--publish` option to be set.

**Comment by thaJeztah** [comment]
Looks like the documentation is incorrect there; services don't support `-p <port>` or `-P`; both source (container) port and host port must be specified when using the `-p` / `--publish` option (also see https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish)

Could you open an issue in the docs issue tracker for this? https://github.com/docker/docker.github.io/issues

**Comment by dvohra** [comment]
What precisely is the issue? Seems to be a contradiction in the following 1. and 2. documentation references:

1. No **Default** column value or value range is specified in the `docker service create` command documentation.
https://docs.docker.com/engine/reference/commandline/service_create/

2. The Load Balancing indicates "The swarm manager can automatically assign the service a PublishedPort or you can configure a PublishedPort for the service. You can specify any unused port. If you do not specify a port, the swarm manager assigns the service a port in the 30000-32767 range."

https://docs.docker.com/engine/swarm/key-concepts/#load-balancing

The following command should expose a port on the host in the range of 30000-32767 on the host according to 2. in which the Docker image `mysql` exposes port 3306 on the Docker container by default.

```
docker service create \
   --env MYSQL_ROOT_PASSWORD='mysql'\
   --replicas 1 \
   -p \
   --name mysql \
  mysql
```

> Looks like the documentation is incorrect there; services don't support -p <port> or -P; both source (container) port and host port must be specified when using the `-p` / `--publish` option 

What is assumed in the preceding statement is that a port is exposed on the container as specified in a `Dockerfile` `EXPOSE` instruction and the `-p `option without a arg exposes a port in the range of 30000-32767.

**Comment by dvohra** [comment]
Some test results on Docker for AWS.
### List Swarm nodes.

```
~ $ docker node ls
ID                            HOSTNAME                        STATUS              AVAILABILITY        MANAGER STATUS
ijl5yax9z8tjbejwd5mury9z7     ip-172-31-35-44.ec2.internal    Ready               Active              
iywzrok7m8vbsewtelk4u5i20 *   ip-172-31-47-203.ec2.internal   Ready               Active              Leader
tlpesakssj51fbhr4dd14uvdu     ip-172-31-14-234.ec2.internal   Ready               Active            
```  

### Docker version

```
~ $ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

### Docker Info

```
~ $ docker info
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iywzrok7m8vbsewtelk4u5i20
 Is Manager: true

```

### docker service create --help

```
~ $ docker service create --help
Usage:	docker service create [OPTIONS] IMAGE [COMMAND] [ARG...]
Create a new service
Options:
  -p, --publish port                       Publish a port as a node port

```

### Specify -p without <port>

```
~ $ docker service create \
>   --name hello-world \
>   -p \
>   --replicas 3 \
>   tutum/hello-world
invalid argument "--replicas" for p: Invalid containerPort: --replicas
See 'docker service create --help'.
```

### Specify -p <port>

```
~ $ docker service create \
>   --name hello-world \
>   -p 8080\
>   --replicas 3 \
>   tutum/hello-world
ah1ttggqv8gyco81p0q7wjbk7
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
~ $ docker service ps hello-world 
ID                  NAME                IMAGE                      NODE                            DESIRED STATE       CURRENT STATE            ERROR               PORTS
9adpdx1quwyf        hello-world.1       tutum/hello-world:latest   ip-172-31-47-203.ec2.internal   Running             Running 13 seconds ago                       
rx4uqir1jlix        hello-world.2       tutum/hello-world:latest   ip-172-31-35-44.ec2.internal    Running             Running 12 seconds ago                       
wpdnvyq76rhp        hello-world.3       tutum/hello-world:latest   ip-172-31-14-234.ec2.internal   Running             Running 13 seconds ago                       
~ $ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                      PORTS
ah1ttggqv8gy        hello-world         replicated          3/3                 tutum/hello-world:latest   *:0->8080/tcp
```

### Specify -p <host port>:<container port>

```
~ $ docker service rm hello-world
hello-world
~ $ docker service create \
>   --name hello-world \
>   -p 8080:80\
>   --replicas 3 \
>   tutum/hello-world
l76ukzrctq22mn97dmg0oatup
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
~ $ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                      PORTS
l76ukzrctq22        hello-world         replicated          3/3                 tutum/hello-world:latest   *:8080->80/tcp
~ $ docker service ps hello-world
ID                  NAME                IMAGE                      NODE                            DESIRED STATE       CURRENT STATE            ERROR               PORTS
5ownzdjdt1yu        hello-world.1       tutum/hello-world:latest   ip-172-31-14-234.ec2.internal   Running             Running 33 seconds ago                       
csgofrbrznhq        hello-world.2       tutum/hello-world:latest   ip-172-31-47-203.ec2.internal   Running             Running 33 seconds ago                       
sctlt9rvn571        hello-world.3       tutum/hello-world:latest   ip-172-31-35-44.ec2.internal    Running             Running 32 seconds ago                       
~ $ 
```

**Comment by dvohra** [comment]
Based on test result the statement  "The swarm manager can automatically assign the service a PublishedPort or you can configure a PublishedPort for the service. You can specify any unused port. If you do not specify a port, the swarm manager assigns the service a port in the 30000-32767 range."
is not valid as no port is assigned automatically by Swarm manager.

https://docs.docker.com/engine/swarm/key-concepts/#load-balancing

Also not valid is 

> services don't support -p <port> or -P; both source (container) port and host port must be specified when using the -p / --publish option

**Comment by thaJeztah** [comment]
Apologies, you're right, just defining the container-port _is_ supported, so this is valid;

```
docker service create -p 80 --name my-service nginx:alpine
```

(docker automatically assigns a port in the `30000-32767` range)

But the `-P` / `--publish-all` option is not available for services, nor does the swarm manager automatically assign a published port if no `-p` / `--publish` option is set.

**Comment by dvohra** [comment]
Still no port is automatically exposed on the host.
1. Create service.
```
~ $ docker service create -p 80 --name my-service nginx:alpine
erljel5yh9qu98t49fg68z2ut
```

2. List service. The port 80 is exposed on the host with mapping `*:0->80/tcp`.
```
~ $ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
erljel5yh9qu        my-service          replicated          1/1                 nginx:alpine        *:0->80/tcp

```

3. Target port is 80.

```
~ $ docker service inspect my-service
[
    {
        "ID": "erljel5yh9qu98t49fg68z2ut",
        "Version": {
            "Index": 25
        },
        "CreatedAt": "2017-07-31T16:52:56.03042479Z",
        "UpdatedAt": "2017-07-31T16:52:56.031623421Z",
        "Spec": {
            "Name": "my-service",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:alpine@sha256:24a27241f0450b465f9e9deb30628c524aa81a1aa6936daa41ef7c4345515272",
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 30000,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "twwtljmenngnehzo0nd5h8ps5",
                    "Addr": "10.255.0.5/16"
                }
            ]
        }
    }
]
~ $ 


```

**Comment by dvohra** [comment]
> just defining the container-port is supported

The port 80 is the target port on the host and not the container port.

**Comment by thaJeztah** [comment]
`PublishedPort` is the "host" port, `TargetPort` is the "container" port; so in the above output; `http://<docker-host>:30000` should connect to the service


The `*:0->80/tcp` looks like a bug in the presentation; could you open an issue for that in the https://github.com/docker/cli/issues issue tracker?

**Comment by dvohra** [comment]
> (docker automatically assigns a port in the 30000-32767 range)

But the host port is not listed. Or, is it assumed to be  30000?

**Comment by thaJeztah** [comment]
There's two sections in there - the `Spec` shows what's defined in the service definition. The `Ports` section shows the active config; that section shows `PublishedPort": 30000,`

**Comment by dvohra** [comment]
Thanks @thaJeztah.

**Comment by dvohra** [comment]
Not a bug, but Docker for AWS LoadBalancer (LB) should map default LB port to Instance Port as 30000:30000 instead of the default 7:7.

![loadbalancerport](https://user-images.githubusercontent.com/3654431/28799059-cf1df50e-75fb-11e7-846e-7b1b654f90b1.jpg)

Though a service could be exposed at any port in the range 30000-32767, if only one service is created the port would most likely be 30000.

**Comment by thaJeztah** [comment]
for presentation of the port, I opened https://github.com/docker/cli/issues/402, and a proposed fix in https://github.com/docker/cli/pull/404

> Not a bug, but Docker for AWS LoadBalancer (LB) should map default LB port to Instance Port as 30000:30000 instead of the default 7:7.

For the AWS configuration, I'll have to defer to @kencochrane (or someone else on the Docker for AWS team), because I'm not fully up to speed on that product 😅

**Comment by dvohra** [comment]
Apologies, could not verify earlier if the service is being exposed automatically as the `http://<LB DNS>:30000` was not invoking the service, which is because the `<LB Port>:<Instance Port>` mapping is `7:7` instead of `30000:30000`.

In summary, could the following issues be confirmed?

1. The `<LB Port>:<Instance Port>` mapping for a Docker for AWS service should be `30000:30000` instead of `7:7`.

2. The `docker service create` documentation should include the args if any in the command options to distinguish between command options that require an arg such as the `-p` option and the options that provide a default value for an option.

3. The section **Publish service ports externally to the swarm (-p, –publish)** 
(https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish) has the port order reversed.

`docker service create --publish <TARGET-PORT>:<SERVICE-PORT> nginx`

Should be:

`docker service create --publish <SERVICE-PORT>:<TARGET-PORT> nginx`

or:

`docker service create --publish <PUBLISHED-PORT>:<TARGET-PORT> nginx
`
4. The scope of a service being the swarm a service should be created in a _default overlay network_ even if the service does not expose a port on the host, instead of the `bridge` network.

**Comment by thaJeztah** [comment]
> The section Publish service ports externally to the swarm (-p, –publish)
(https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish) has the port order reversed.

Hm, terminology is a bit troublesome yes, however `<SERVICE-PORT>` is correct(ish). Running;

```
docker service create -p 8080:80 nginx:alpine
```

Port `8080` is the port on which the service is accessible externally, and `80` is the port that the service's containers are listening on. But I agree that we should be consistent (I'm not really happy with the `TargetPort` / `PublishedPort` naming, but I guess that ship has sailed)

**Comment by kencochrane** [comment]
@dvohra The port 7 mapping is always there, and it is needed to fix a bug with the ELB healthcheck, once AWS fixes the healthcheck, we will be able to remove that. If you are not seeing port 30000 getting exposed, it isn't because of port 7.

If the service port is automatically assigned to the service by docker, it will not be added to the ELB. We only add ports that are explicitly set as published, so that people who don't want them exposed, don't get surprised, when they are exposed publicly when they didn't want them too be.

**Comment by dvohra** [comment]
@thaJeztah.
The port terminology should be:
```
docker service create \
  --name <SERVICE-NAME> \
  --publish <PUBLISHED-PORT>:<TARGET-PORT> \
  <IMAGE>
```

as at https://docs.docker.com/engine/swarm/ingress/

The following is a reverse ordered ports.

`docker service create --publish <TARGET-PORT>:<SERVICE-PORT> nginx
`

**Comment by dvohra** [comment]
Thanks @kencochrane. The range of ports for a LB is 1-65535, but the range of port for a service is 30000-32767, which makes a port setting of 7:7 fine for LB but not for Docker service. Being a Docker for AWS LB setting LB port to 7 is definitely not suitable.

**Comment by kencochrane** [comment]
@dvohra sorry I'm not sure what you are saying by "Being a Docker for AWS LB setting LB port to 7 is definitely not suitable." can you explain why it is not suitable?

**Comment by dvohra** [comment]
With _LB Port:Instance Port_ as `7:7` would imply the Docker service is exposed on port 7 on host.A Docker service could not expose on port 7 on host if port is set automatically.

**Comment by kencochrane** [comment]
@dvohra that is correct, and that is why we are using it. It isn't for docker, it is because there is a bug in the way ELB works, and we need to have at least 1 listener or else the health checks fail. This is just a temporary fix until the bug in ELB is fixed, and then it will be removed.

**Comment by dvohra** [comment]
Is the bug that the ELB listener needs to be on port 7? or, is the bug that at least one listener is required? If the latter the one listener should be on port 30000.

**Comment by kencochrane** [comment]
@dvohra The ELB needs to have at least one listener, so we hard code one on port 7, so that it won't conflict with other peoples services. If we put it on port 30000 then it could conflict with someone's service who wants to be running on port 30000. If they have a service deployed and using port 30000, and they don't want that port to be exposed, it will be a surprise to them if we had that port open when they are not expecting it to be.

**Comment by dvohra** [comment]
The ELB is created for each service and may be modified if required. If 30000 is used create the ELB on 30001. 

Without any Docker services running:
1. Create a Docker service
2. Test on http://<ELB DNS>:30000
3. Service not invoked

If other Docker services are running assign port 30001 or some other port chosen incrementally from the available ports in the range 30000-32767.

**Comment by thaJeztah** [comment]
@dvohra `Create a Docker service` - does the service publish a port? (`-p` / `--publish`)?

**Comment by dvohra** [comment]
Not explicitly but implicitly, as has been sorted out in the preceding discussion.

`docker service create -p 80 nginx:alpine`

The service gets exposed on port 30000 on the host, and on Docker for AWS the expected ELB port is 30000 (or incrementally available port) mapped to instance/s port 30000,  but the ELB port is 7 mapped to instance/s port 7. What is the significance of port 7 is any?

**Comment by thaJeztah** [comment]
@dvohra looks like that is due to https://github.com/moby/moby/issues/34266#issuecomment-319408014

> If the service port is automatically assigned to the service by docker, it will not be added to the ELB. We only add ports that are explicitly set as published, so that people who don't want them exposed, don't get surprised, when they are exposed publicly when they didn't want them too be.

**Comment by kencochrane** [comment]
@dvohra once again, ignore port 7, it doesn't matter, it isn't related to this issue.  The reason why you port 30000 it isn't added to the ELB is because of what @thaJeztah just pointed out. You need to explicitly add publish the port with your service, or else we will not add it to the ELB.

**Comment by dvohra** [comment]
> If the service port is automatically assigned to the service by docker, it will not be added to the ELB. We only add ports that are explicitly set as published, so that people who don't want them exposed, don't get surprised, when they are exposed publicly when they didn't want them too be.

But, isn't the ELB created automatically too without user input of whether an ELB should be created or not. Other than modifying the port on the ELB Listener the service is already exposed publically.

**Comment by dvohra** [comment]
@kencochrane Fine, thanks.

**Comment by kencochrane** [comment]
The ELB is a shared resource across all services in the stack. People can connect to the ELB, but by default there are no ports exposed (minus port 7 which was described above). So if anyone hits the ELB it will not return anything. The service runs in a private network inside of the VPC, the only way for outside (public) traffic to access the service is to publish a port in the service, which will add a listener to the ELB, and allow someone on the outside to access the published port, through the ELB.

**Comment by dvohra** [comment]
Thanks @kencochrane. The ELB is created and a user exposes selected ports on the ELB Listeners. Thanks for the clarification.

**Comment by dvohra** [comment]
> Create a Docker service - does the service publish a port? (-p / --publish)?

Even when port is published explicitly the ELB port is 7:7. But, @kencochrane has emphasized enough that it is designed to be such. Thanks.

**Comment by thaJeztah** [comment]
Yes, but the `7:7` ELB is not used for forwarding traffic to that service, when publishing the service's port (e.g. `-p 8080:80`) another port will be added, routing to the service

**Comment by dvohra** [comment]
> another port will be added, routing to the service

Will be added by user? Because it is not configured in LB.
