### ISSUE TITLE
Container that failed creation prevents creating new container with the same name

### ISSUE THREAD

**Issue by shin-** [moby/moby#34270]
**Description**

A seemingly non-existent (previously removed?) container prevents a new container from being created with the same name.
```
$ docker create --name composetest_db_1 busybox
Error response from daemon: Conflict. The container name "/composetest_db_1" is already in use by container "f7d0040ec93b85f749109e150d744e347984ea082d183a1c506aa6ccd4e70d00". You have to remove (or rename) that container to be able to reuse that name.
$ docker inspect f7d00
[]
Error: No such object: f7d00
```

**Steps to reproduce the issue:**
1. (Run docker/compose test suite -- I do not know yet if it's a specific sequence of instructions that causes the issue to arise, but the test suite seems to exhibit it 100% of the time)
2. Run `docker create --name composetest_db_1 busybox`

**Describe the results you received:**

An error occurs claiming the name is already in use by another container. When trying to inspect said container, the resource can not be found.

**Describe the results you expected:**

The container is created normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 03:46:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce-rc1
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 03:45:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 383
Server Version: 17.07.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 617
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.499GiB
Name: yuna
ID: YZQG:AKYJ:JQXJ:CEHT:62DP:PMWA:S43W:5X47:SSOE:UXGG:XHWS:555F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

Ubuntu 16.04 LTS Desktop

**Comment by vieux** [comment]
@vdemeester can you please take a look at this one ?

**Comment by shin-** [comment]
More info:

- No trace of the conflicting container in /var/lib/docker/containers
```
# ls /var/lib/docker/containers/
2502ade222c11e76e0782c549af61f19eed539ed919801729ebfe848661c2465
f61679ad44c2bc079d7acee4a7319a6c6a0d6be5d34c16169c705d2233897e24
```

- Restarting the daemon clears up the issue
```
# sudo service docker restart
# docker create --name composetest_db_1 busybox
0ad3b10ef6760b0b9f8977782decb8cf6be2109b9c02f755c17e8b08a20379bf
```

**Comment by vieux** [comment]
maybe related to https://github.com/moby/moby/pull/33886 ? /cc @aaronlehmann

**Comment by thaJeztah** [comment]
Does compose use rename? If so, this may be related as well https://github.com/moby/moby/pull/33940

Looks like we should cherry pick that anyway; @vieux can you open an issue for cherry picking?

**Comment by thaJeztah** [comment]
actually, may already be in 17.07 (based on the date)

**Comment by shin-** [comment]
Debug logs, if it helps: https://gist.github.com/shin-/affad1b952bb82fc4b26b0f48829b1cf

@thaJeztah I'm almost 100% sure we don't.

**Comment by aaronlehmann** [comment]
I couldn't reproduce this by deleting or renaming containers with a conflicting name.

I think there's a good chance it's related to #33886 somehow, but I'm not sure.


I noticed this message in the log:

```
time="2017-07-26T16:18:56.444918817-07:00" level=error msg="Handler for POST /v1.30/containers/create returned error: --storage-opt is not supported for aufs" 
```

I wonder if the name gets reserved when trying to create this container, and isn't released when the creation fails?

**Comment by shin-** [comment]
@aaronlehmann Yes, I think you're onto something, I was just able to isolate the issue to our storage_opt test.

Here's a full repro case:
```
$ docker create --storage-opt size=1G --name test23 busybox
Error response from daemon: --storage-opt is not supported for aufs
$ docker create --name test23 busybox
Error response from daemon: Conflict. The container name "/test23" is already in use by container "9a18c83f2fb1f37ced79ab4ae0985bdde57a87fbba55863d5485c0e052994b8f". You have to remove (or rename) that container to be able to reuse that name.
$ docker inspect 9a18
[]
Error: No such object: 9a18
```

**Comment by aaronlehmann** [comment]
Okay, makes sense. It looks like this code path reaches `(*memDB).Delete`. Originally this had no error checking and just deleted whatever it could, but during the review process I got asked to add error checking and transaction rollback on error. Ironically, it causes the problem because the container doesn't exist at this point.

**Comment by aaronlehmann** [comment]
#34274
