### ISSUE TITLE
Build - ANY command COPY ADD or mapping gives an error

### ISSUE THREAD

**Issue by UKSoft66** [moby/moby#34288]
This error is around a bit longer, e.g. issue #27233 and many more.

Anyway, all the solutions bring nothing in my case cos building fails EVERY time when COPY ADD or a mapping via Docker exec -v is involved in the Dockerfile. Hundreds of tries and not even one success.
Every Dockerfile from the repository fails if it contain these commands.

All path are relative to the build context, some errors I can prevent with having ADD/COPY before RUN commands but that is just a workaround for shorter files, actually I try to build the official PHP
https://github.com/docker-library/php/blob/ddc7084c8a78ea12f0cfdceff7d03c5a530b787e/7.1/apache/Dockerfile
and that Dockerfile has >250 lines with an severe amount of directory actions, how shall I reorder that w/o being a Linux-crack?

What can I do to get that running? I read for a week EVERY article I could find about this issue, tried hundreds of builds, soon as there is a folder access like COPY ADD or a mapping via Docker exec -v comes the error. How can it even be that your Software has such bugs? (obviously not fully handled since 2 years?)

AGAIN: I tried ALL the tips out there and the only thing that works a bit is having ADD / COPY before RUN commands, but that is not always possible. All path ARE relative with the build context as root.
Every build w/o those commands works perfect. Resetting the service doesent help either, nor anything else mentioned in those articles.
So please save your and my time and do not repeat that, this must be something else.

INFOS: 
- running on Debian or Win10 makes NO difference.
- Docker 17.05.0-ce

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

> What can I do to get that running? I read for a week EVERY article I could find about this issue, tried hundreds of builds, soon as there is a folder access like COPY ADD or a mapping via Docker exec -v comes the error. 

What error message do you get?

> or a mapping via `docker exec -v`

The `docker exec` command does not have a `-v` option; what exactly are you trying to do?

> How can it even be that your Software has such bugs? (obviously not fully handled since 2 years?)

Without the information requested, we won't be able to determine if there's a bug, or if it's something in your environment. 

> So please save your and my time and do not repeat that, this must be something else.

Again; you didn't provide steps to reproduce, nor the error you're seeing. No reason to leave a message like this.


Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by UKSoft66** [comment]
## docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false



## docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 46
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.469GiB
Name: debian
ID: DDXA:EM6T:6RB3:3GAY:RUVH:R6ML:6KZ4:QSTP:XLBD:WQTL:ATCU:UPJI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

### Exact steps are -as written above- that I can not build ANY Dockerfile that contains COPY ADD or any path mapping.
**Direct example: Building the original PHP container from Docker Hub**
https://github.com/docker-library/php/blob/ddc7084c8a78ea12f0cfdceff7d03c5a530b787e/7.1/apache/Dockerfile

### I wrote _docker exec -v_ but exec does not have -v parameter, I meant **docker run -v**, surely everyone made that logical bridge as run is the only other container-executing command where a path mapping makes sense?

If I take out all commands that refers to any path on the host all works fine. 
But including any off the ADD COPY or any path mapping via "docker **run** -it -v /Hostpath/:/containerpath/ [container-id] bash" throws an error which is 
**"no such file or directory"** on COPY / ADD and 
**"The command [...] returned a non-cero code"** (wich is mosttly 127) on other commands 
like this (starts at line 153 (shortend)
_RUN set -xe \
    [...]
    && docker-php-source extract \_
The extract command in folder docker-php-source throws the error.
( Note that the folder exists as sub folder of the building folder so is in the correct build context )

As I also mentioned placing ADD / COPY before RUN helps, in that Dockerfile I put line 151  "COPY docker-php-source /usr/local/bin/" nearly on top and there it works, but there are lot of other directory commands in that file and I have no idea how to rewrite that cos I am not a Linux crack.

**If it is a path mapping the error is restricted access** on the guest system, 
but entering the container shows me that folder and file have 755 so all should be fine. (Besides that it is already not logical to think that the directories in the container can even have wrong permissions cos first the container works with root access and second then it would work for no one, not just me)

And last not least, while searching the net for this I saw lots of users with actual versions of docker facing the same problem
-----------------------------------------------------------------------------------------------------------
### @thaJeztah  (and thx for responding)
_ME: So please save your and my time and do not repeat that, this must be something else.
YOU: Again; you didn't provide steps to reproduce, nor the error you're seeing. No reason to leave a message like this._

Sorry if that sounded rude. Point is when I ask someone I already tried all that I could find in the net. If I dont write that there will be lots of responds saying all that stuff again, from "restart service" to "place ADD before RUN" and so on. This simply wastes time as I tested all and nothing works.

Besides, I provided the steps as **EVERY time when COPY ADD or a mapping via Docker exec -v is involved in the Dockerfile** does explain it completely, doesent it? (And the error message is surely not 404 Forbidden).
Docker info and version wont show anything of interest and all the other stuff I write here is nothing than redundant data, explaining that sentence a bit closer.

Also I do not understand how it can be some problem in the environment as docker is meant and developed  to be placed in whatever environment to run w/o environment specific options?
Anyway, OS is:
**Windows 10 Pro x64 2017 (up to date), CPU AMD A8-7600, 4GB RAM
or Debian Jessie in Virtualbox VM
To install Docker on Linux I use a script:**
### compiled from https://docs.docker.com/engine/installation/linux/debian/#/debian-jessie-80-64-bit

sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install apt-transport-https ca-certificates -y

sudo sh -c "echo deb https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list"
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

sudo apt-get update
sudo apt-cache policy docker-engine
sudo apt-get install docker-engine -y

sudo service docker start
sudo docker run hello-world

sudo group add docker
sudo groupadd docker
sudo gpasswd -a $USER docker
sudo service docker restart

this seems to work fine?

**Comment by UKSoft66** [comment]
Dunno why it says closed, sorry.

**Comment by thaJeztah** [comment]
I'm not sure how `docker run -v` would relate to building a Dockerfile.

Assuming your steps to build the dockerfile are;

1. clone the repository 

```
git clone https://github.com/docker-library/php.git
```

2. go to the right directory for the dockerfile version you want to build

```
cd 7.1/apache
```

3. build the Dockerfile

```
docker build -t my-php .
```

What error do you get?

**Comment by UKSoft66** [comment]
Well docker run -v of course not for building a container but to connect to one and map a folder to it for keeping changes in e.g. config files or html pages or whatever. Sorry that I havent wrote "_error on COPY/ADD in Dockerfiles OR when trying to connect to a container and mapping a local folder via docker run -v_" cos that is too long for the header and I assume that those programmers who reading and answering here have enough logic to see that "docker run -v" is linked to the header where it says "**or mapping**".?

Anyway, with that manual it works.

So the point is I need to clone everything first? 
That git-cloning I have not seen in any youtube video, I do not see it on the dockersite and nowwhere else.
All explanations are like
- create directory
- create dockerfile (mostly copy it from docker hub)
- docker build -t <containername> .
- docker run -t -v hostdir:containerdir # thats the mapping

And that works fine... except the mapping in the run command and as long as no add, copy in the Dockerfile.

So what makes the difference there and why is no one explaining that, guess most people do not need to do that?

**Comment by UKSoft66** [comment]
On trying the same with nginx I get error

E: Unable to locate package libcrypt11
E: Unable to locate package libjpeg8
The command '/bin/sh -c apt-get update [...]' returned a non-zero code: 100

**Comment by thaJeztah** [comment]
> That git-cloning I have not seen in any youtube video, I do not see it on the dockersite and nowwhere else.

A Dockerfile is similar to a Makefile; it contains instructions to build artefacts (in Docker's case; a Docker image) from the source-files in a repository. Running a Makefile (or Dockerfile) _without_ having the source-files that it needs to run won't work.

You can find more information about building your own images in the Dockerfile reference https://docs.docker.com/engine/reference/builder/, and the "develop" section in the documentation; https://docs.docker.com/develop/

The repository for the official PHP image (https://github.com/docker-library/php) is intended for use by the maintainers of the official image. This repository is usually not used by end-users to build the image themselves (instead, use the image from Docker Hub, which is maintained by the official image maintainers, signed, and scanned for vulnerabilities)

I'm closing this issue, because I don't see a bug here. If you think the documentation for building images can be improved, feel free to open an issue in the documentation issue tracker (https://github.com/docker/docker.github.io/issues) or the issue tracker for the official PHP image; https://github.com/docker-library/php
