### ISSUE TITLE
oci runtime error with when 'userns-remap'

### ISSUE THREAD

**Issue by wesleyclawson** [moby/moby#34284]
**Description**

When trying to spin up a new container I receive this error message:

```
docker@Docker:/$ docker run hello-world
container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/231072.231072/aufs/mnt/6078d29c3d448fff64c02710c0d060bd95b81b4104fc071fc0f1aa8273e2fc71\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/lxcfs/controllers/memory/docker/1f5068ec7544c0508619af52812ebf15e67cb4ee2165ec136aad1608a60c23c0: permission denied\\\"\""
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/231072.231072/aufs/mnt/6078d29c3d448fff64c02710c0d060bd95b81b4104fc071fc0f1aa8273e2fc71\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/lxcfs/controllers/memory/docker/1f5068ec7544c0508619af52812ebf15e67cb4ee2165ec136aad1608a60c23c0: permission denied\\\"\"".
ERRO[0000] error waiting for container: context canceled
```

 I am testing out using the 'userns-remap' function of docker and am using the default value in the daemon json file `"userns-remap": "default"`. My Ubuntu 16.04 is up to date, and I'm unsure of what to try next as older fixes from previous bug reports have not done the trick. 

**Steps to reproduce the issue:**
1. Install docker-ce
2. Create/Edit `/etc/docker/daemon.json` with

```json
{
  "userns-remap": "default"
}
```

3. Restart Docker
4. run `docker run hello-world` or `sudo docker run hello-world`

**Describe the results you received:**

I get that oci error everytime the script is run. I've checked all of the user namespace files and everything seems to be in order. 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 1
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/231072.231072/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: Docker
ID: 2PM3:VICR:SC5H:UVGP:67RK:BKKC:TFFW:U4HF:4ACK:GJAO:U4RM:2HWC
Docker Root Dir: /var/lib/docker/231072.231072
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is running in a VMware environment with an updated/upgraded Ubuntu 16.04. When userns-remap isn't being used, docker works fine.

**Comment by thaJeztah** [comment]
Thanks for reporting this looks like a duplicate of https://github.com/moby/moby/issues/24834 and https://github.com/moby/moby/issues/31432#issuecomment-318163095, which is an issue with lxc; make sure to update your kernel and distro to the latest version.

I'm closing this issue, because this is not a bug in docker, but feel free to comment after I closed or if you're still able to reproduce on a fully up-to-date system 👍

**Comment by wesleyclawson** [comment]
@thaJeztah I saw those and commented in the thread (I'm the author of [#31432 (comment)](https://github.com/moby/moby/issues/31432#issuecomment-318163095)). 

I do have the latest lxcfs and still have this error so I thought it would be appropriate to start another issue. If I need to post in a different location I understand.

```
docker@Docker:~$ sudo apt-get install lxcfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
lxcfs is already the newest version (2.0.7-0ubuntu1~16.04.2).
```

**Comment by thaJeztah** [comment]
I can reopen, but I'm not sure this is something that can be fixed in docker; have you tried updating your kernel as well (4.4.0-31 looks quite old; I have 4.4.0-83-generic running on my machines)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
