### ISSUE TITLE
DeviceMapper (direct-lvm) regression in Docker 17.07-rc1

### ISSUE THREAD

**Issue by marcosnils** [moby/moby#34298]
Just updated from 17.06.1 to 17.07-rc1 and getting DM errors when trying to start the daemon now

```
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 442170         
DEBU[0001] [graphdriver] trying provided driver: devicemapper 
DEBU[0001] devicemapper: driver version is 4.34.0       
DEBU[0001] Cleaning up old mountid : start.             
Error starting daemon: error initializing graphdriver: devmapper: Deferred removal can not be enabled as libdm does not support it
```

Docker version:

```
Client:
 Version:      17.07.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 20:49:31 2017
 OS/Arch:      linux/amd64
```

```
Linux ip-10-0-1-154 4.4.0-1026-aws #35-Ubuntu SMP Thu Jul 20 21:59:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

This us running in ubuntu 16.04 with latest upgrades. Asking @justincormack seems like this might be a regression

**Comment by justincormack** [comment]
What libdm version do you have installed?

**Comment by marcosnils** [comment]
It's on the first snippet 4.34.0

**Comment by justincormack** [comment]
cc @dmcgowan

**Comment by marcosnils** [comment]
FWIW just built with `libdm_no_deferred_remove` buildtag and engine started.

**Comment by thaJeztah** [comment]
ping @cpuguy83 @rhvgoyal

**Comment by cpuguy83** [comment]
@marcosnils What options are you passing in?

**Comment by marcosnils** [comment]
```
{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.thinpooldev=/dev/mapper/docker-thinpool",
    "dm.use_deferred_removal=true",
    "dm.use_deferred_deletion=true"
  ]
}
```
As suggested in the DM documentation page https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

**Comment by rhvgoyal** [comment]
So was deferred removal previously enabled? If not, that means your library is not new enough to support deferred removal and it did not work even with previous version. In that case its not a regression?

**Comment by marcosnils** [comment]
Yes, this is the same config I was using in 16.04. That's why I consider it as a regression.

**Comment by rhvgoyal** [comment]
If you build with `libdm_no_deferred_remove` tag and then use same config, then still docker will fail. Because it will still say that can't remove deferred removal. 

So to start docker engine, you need to change your config and recompiling with a different tag should not be the solution.

Can you run "strings libdevmapper.so" on your system and grep for deferred. And see if symbol `dm_task_deferred_remove` shows up. First thing I want to know if library is new enough to support deferred removal or not.

**Comment by marcosnils** [comment]
> If you build with libdm_no_deferred_remove tag and then use same config, then still docker will fail. Because it will still say that can't remove deferred removal.

That was't the case. I re-built with libdm_no_deferred_remove and keeping the same config it worked.

**Comment by marcosnils** [comment]
> Can you run "strings libdevmapper.so" on your system and grep for deferred. And see if symbol dm_task_deferred_remove shows up. First thing I want to know if library is new enough to support deferred removal or not.

root@ip-10-0-1-154:/lib# strings ./x86_64-linux-gnu/libdevmapper.so.1.02.1 | grep deferred
dm_task_deferred_remove
dm_task_get_info_with_deferred_remove


> So to start docker engine, you need to change your config and recompiling with a different tag should not be the solution.

As I said in the issue description, I didn't change anything in the configuration from 17.06 to 17.07 just replaced the binaries downloaded from https://download.docker.com/. Those didn't work because of the DM error described. I re-compiled using that build tag and then the engine started **without** any configurarion change,

**Comment by rhvgoyal** [comment]
So library does support deferred removal. While it is not making sense, only explanation I can think is that docker is built with tag `libdm_no_deferred_remove` and hence it will fail if I try to enable deferred removal. But if I recompile docker without that tag, it should have capability to enable deferred removal.

But this seems to be opposite to what you are explaining. So I am not sure what's going on.

**Comment by marcosnils** [comment]
> So library does support deferred removal.

Yes, and even though the library supports it, docker seems to check this kind of weird: https://github.com/moby/moby/blob/cc5914c908690c94f8c9a42081d1b50f74f20424/daemon/graphdriver/devmapper/deviceset.go#L1495-L1498

Seems like checking for the DM version is incorrect?

**Comment by rhvgoyal** [comment]
That's kernel dm driver version check. For library, code just checks for variable `devicemapper.LibraryDeferredRemovalSupport`. This is set by package devicemapper based on whether docker was compiled with tag `libdm_no_deferred_remove` or not. 

So based on symptoms you are seeing, I suspect that docker has been compiled with this tag which compiles in `devmapper_wrapper_no_deferred_remove.go` and that means `LibraryDeferredRemovalSupport=false` and that means any attempt to enable deferred removal will fail with errror message saying library does not have capability.

**Comment by justincormack** [comment]
Which binaries did you use?

**Comment by marcosnils** [comment]
https://download.docker.com/linux/static/test/x86_64/

**Comment by cpuguy83** [comment]
You can't use the static build with devmapper.

**Comment by marcosnils** [comment]
:man_facepalming: seems reasonable. Haven't tried building the dynamically linked binaries. I guess we can close this, right?

**Comment by cpuguy83** [comment]
Seems so, but if you can test with a dynbinary, that'd be helpful. The deb should be up in the test channel if I'm not mistaken.

**Comment by marcosnils** [comment]
Just confirmed this works.

**Comment by kolyshkin** [comment]
The only thing to add is, static dockerd build uses very old libdevmapper that does not support deferred removal. This version of libdevmapper comes from lvm2-2.02.103 sources, added by commit d11f75b50 back in Nov 2013 and never updated since. Surely, this might not be the only issue preventing static build from working with dm deferred remove...

**Comment by thaJeztah** [comment]
would it be worth updating that version?

**Comment by kolyshkin** [comment]
> would it be worth updating that version?
PRO: will fix the problem of non-working deferred removal
CON: might introduce other bugs

I'd say let's try it. I'll check it locally and send a pull request.

**Comment by y123456yz** [comment]
@marcosnils  
what's the linux release for compile docker code.
I compile lvm2 for static library( make device-mapper) failed.
I can not get the libdevmapper.a，so compile docker failed


how you do for compiling the docker code, can you tell me what's you linux release and what's steps to compile docker?

this is the problem that I meet ,can you help me?
https://github.com/moby/moby/issues/34865
