### ISSUE TITLE
with --privileged and  -v /dev:/dev usb device is not detected

### ISSUE THREAD

**Issue by ecopty** [moby/moby#34290]
**Description**

I have a special usb device, that cannot be mounted in the container even when running with --privileged and  -v /dev:/dev , if plugged after container is run
**Steps to reproduce the issue:**
1.sudo docker create -it  --privileged  -v /dev:/dev -v /etc/apt/apt.conf:/etc/apt/apt.conf:ro  myimage:3 bash
2. connect device to host
3. try to open device 

**Describe the results you received:**
device can be opened 

**Describe the results you expected:**
although device show in lsusb, it cannot be opened

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.6, build 78d1802

```

**Output of `docker info`:**

```
Containers: 12
 Running: 2
 Paused: 0
 Stopped: 10
Images: 25
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-36-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.61 GiB
Name: eman-build
ID: BAX5:MWJE:JGJF:YOPP:HVYF:2HX3:WWDQ:F7ZD:SWW4:ZIJA:4XFZ:2SQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.sc.intel.com:911/
Https Proxy: https://proxy.sc.intel.com:911/
No Proxy: localhost,.intel.com,127.0.0.0/8,172.16.0.0/20,192.168.0.0/16,10.0.0.0/8
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vdemeester** [comment]
cc @mlaventure

**Comment by thaJeztah** [comment]
does it work if you use `-v /dev:/dev:shared`, or `-v /dev:/dev:slave` ?

**Comment by mlaventure** [comment]
`1.12.6` is EOL, you should really upgrade.

This works correctly for me on, `17.06`.

There shouldn't be a need to make the mount as shared or slave as the device created are not mounts themselves. `-v /dev:/dev` is a bind mount, so every file operation within `/dev` should be visible in the container.

Are you sure the device correctly appears within the host?

**Comment by thaJeztah** [comment]
closing because this went stale. There's also some discussion in https://github.com/moby/moby/issues/27807
