### ISSUE TITLE
[Feature request] container live migration

### ISSUE THREAD

**Issue by wenjianhn** [moby/moby#34295]
**Description**
Support migrating a running container to another host.

Related to #12995

I created a demo.
https://asciinema.org/a/3pnUXsSLz9SLTgl4nASYakVJQ

**Comment by thaJeztah** [comment]
docker does support checkpoint and restore as experimental feature, but active development is taking place in containerd; eventually, docker will move to use containerd 1.0 as runtime engine, e.g. https://github.com/containerd/containerd/issues/787

**Comment by wenjianhn** [comment]
@thaJeztah thanks. I will take a look at containerd first.
