### ISSUE TITLE
how to make container to receive upd traffic from a static host

### ISSUE THREAD

**Issue by eshengit** [moby/moby#34305]
Description
Docker version 17.04.0-ce, build 4845c56

**Steps to reproduce the issue:**
1. docker run -it --rm  krallin/centos-tini /bin/bash
2. yum install nc 
3. nc -vu $MY_STATIC_HOST 2001 

**Describe the results you received:**
in docker, the connection just hanging, 
in my laptop it works fine. 
3 gives me 
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif (null)
	src $SRC port $PORT
	dst $MY_STATIC_HOST port 2001
	rank info not available

Connection to $MY_STATIC_HOST port 2001 [udp/wizard] succeeded!

I believe the $SRC:$PORT  for may not working in docker since the $SRC:$PORT are not really docker host's ip and port. 
how to work around this issue?

**Comment by ripcurld0** [comment]
Does adding `--net=host` to `docker run` resolve this?

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by eshengit** [comment]
I interpreted nc output wrong. the udp connection is working fine in docker. close this issue.
