### ISSUE TITLE
Docker Image build doesn't provide % of build completion or in pending. 

### ISSUE THREAD

**Issue by vkothama** [moby/moby#34303]
While building Docker images using Dockerfile, command output doesn't display the % of progress. It would be nice to have, so that user will know the actual build progress. Discussed this issue during the MTA workshop. 

**Steps to reproduce the issue:**
1. Use docker image build command to build any docker image. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
17.03.2--ee.5
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I'm not sure this can be done; the builder currently will show which _step_ of a dockerfile is running, but providing more information than that is fairly impossible;

- steps can be in the build cache, in which case the step would take little time to complete 
- if a step is not in the cache; docker won't have any clue how long the step will take (e.g. a `RUN` statement could be compiling software - how long does this take? How many shell instructions are in the `RUN` command?

Could you provide some more information what kind of progress information you'd like to see, a bit more in detail?

**Comment by vkothama** [comment]
We build Docker Image using the Docker file with a set of given instructions with required packages. So there should be a way, you can monitor the image build progress either by checking disk image space within docker kernel,etc.. I am really not sure how to build this feature, but It's very meaningful to have build progress displayed in the CLI output. This will be useful in case of any network issues.

**Comment by thaJeztah** [comment]
Monitoring disk space is not the issue; it's that docker doesn't know the "progress"; for example, imagine a line like this;

    RUN apt-get update && apt-get install -y some-package

Docker doesn't know what packages (and dependencies)will be installed, if caches needed to be updated, what the size is of those packages, and how long it takes to install

**Comment by thaJeztah** [comment]
I'm closing this issue because this is not something we can implement. The builder does show the build-step, which is the best that can be done with the information available to the builder;

```
Sending build context to Docker daemon  22.14MB
Step 1/5 : FROM debian
 ---> 874e27b628fd
Step 2/5 : ARG uid=1001
 ---> Using cache
 ---> 7b6d6ba0483a
Step 3/5 : ARG gid=51
 ---> Using cache
 ---> 0000376fd64e
Step 4/5 : RUN addgroup --gid $gid mygroup  && adduser --disabled-password --gecos "" --no-create-home --uid $uid --gid $gid myuser
 ---> Running in 72456ae1bcbc
```
