### ISSUE TITLE
"docker run --net,--pid,--ipc" to a container is invalid after rename and restart

### ISSUE THREAD

**Issue by ChenMin46** [moby/moby#34307]
**Description**

**Steps to reproduce the issue:**
1.docker run -tid --name=test0 ubuntu bash
2.docker run -tid --name=test1 --net=container:test0 ubuntu bash
3.docker rename test0 test2
4.docker restart test1

**Describe the results you received:**
Error response from daemon: Cannot restart container test1: No such container: test0

When replace the "--net" to "--pid" or "--ipc" will get :
Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/test3/restart: EOF

**Describe the results you expected:**
test1 restart succuss

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
**Output of `docker info`:**

```
Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 60
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.639GiB
Name: 16
ID: 5PRJ:JAJY:H6IP:OBMF:7QQ6:AQJ2:JHGD:KOHN:K4PZ:ETTR:JPUA:KZ2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 95
 Goroutines: 128
 System Time: 2017-07-30T02:26:57.040522467+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 demoregistry.dataman-inc.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by yastij** [comment]
@ripcurld0 - is anyone working on this one ?

**Comment by ripcurld0** [comment]
I have started to working on it, it seems like we need to convert from the connected container name to its ID.

Do you want to take it?

**Comment by ChenMin46** [comment]
Yes，I am working on it too， will give a PR ASAP.

**Comment by ripcurld0** [comment]
OK, so I guess @ChenMin46 called #dibs on this.
Good luck.
