### ISSUE TITLE
How to push image to the arm64v8

### ISSUE THREAD

**Issue by longquan7** [moby/moby#34318]
I was building an image on the arm64 system.
Now, I want to push it to the official-images of the arm64v8, but the arm64v8 is official, so how to do.
The official-images of the arm64v8 link:https://hub.docker.com/u/arm64v8/

**Comment by ripcurld0** [comment]
@longquan7 it depends whether Docker would like to support and maintain that image.
Can you provide the Dockerfile or any information about that image?

Anyway, you are always welcome to create a DockerHub credentials and push it under that namespace.

@yosifkit PTAL

**Comment by longquan7** [comment]
@ripcurld0 I can provide the Dockerfile, because this image is based on the image of the X86 system.
@yosifkit

**Comment by thaJeztah** [comment]
When pushing to Docker Hub, you can only push to repositories that you own, or have write access to; if you want to push an image for your personal use, you'd have to push it to your own username (`myusername/myimage:tag`).

If you have feedback for the official images, please open an issue in that issue tracker; more information on the multi-arch images can be found here; https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by thaJeztah** [comment]
I see you already opened an issue in the issue tracker for the official images; https://github.com/docker-library/official-images/issues/3255, so let me close this one here, as there's nothing that can be done in this repository
