### ISSUE TITLE
docker-ce-stable Fedora repository empty

### ISSUE THREAD

**Issue by IOAyman** [moby/moby#34312]
**Description**
I am setting up Docker on a machine running Fedora 26, but I'm surprised the [repository] is completely empty!

The [docs] point out the Fedora [repository file] to setup where the latest Docker packages should be found, but when trying to install Docker there are no `docker-ce` packages.  
There's only the `docker`package from the `fedora` repository but that is too old (`docker-1.13.1-19.git27e468e.fc26.src.rpm`).

I also have noticed that the OS requirements in the [docs] are Fedora 24 or 25, no 26 mentioned!

I was wondering why there haven't been a build for Fedora 26?

[repository]: https://download.docker.com/linux/fedora/26/x86_64/stable/Packages/
[docs]: https://docs.docker.com/engine/installation/linux/docker-ce/fedora/#install-using-the-repository
[repository file]: https://download.docker.com/linux/fedora/docker-ce.repo
**Steps to reproduce the issue:**
1. Same steps for setting up `docker-ce-stable` the repository as described in the [docs].
2. `sudo dnf --repo docker-ce-stable list available`

**Describe the results you received:**
Empty list.

**Describe the results you expected:**
Expected docker-ce-* packages

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 26 x64

**Comment by thaJeztah** [comment]
Fedora 26 was not yet released when docker 17.06 was released so there were no packages built for that. The docs are correct, and state which versions of Fedora are currently supported

I opened a tracking issue for this a whole back, so let me close this one in favor of https://github.com/moby/moby/issues/33247

**Comment by ripcurld0** [comment]
@thaJeztah oops sorry didn't see that. Thanks.

**Comment by IOAyman** [comment]
@thaJaztah, Thanks for clarifying.
