### ISSUE TITLE
pkg/signal: has docker-specific error messages

### ISSUE THREAD

**Issue by stevvooe** [moby/moby#34334]
https://github.com/moby/moby/blob/master/pkg/signal/trap.go#L18 import logrus and creates very daemon-specific error messages. If this is in `pkg`, it should not be specific to docker/moby and should not import the logger.

Let's get `logrus` removed from this package.

cc @Random-Liu

**Comment by yuexiao-wang** [comment]
I agree with it.
I send a PR to remove logrus and use fmt.Println instead of logrus.Info

**Comment by Random-Liu** [comment]
Make sense to me! Thanks for filing the issue! :)
