### ISSUE TITLE
pulled docker image missing files

### ISSUE THREAD

**Issue by huang475** [moby/moby#34348]
**Description**

I'm using gitlab-ci-runner to build and push my docker images to my private registry. But the image I pushed and pulled are different. Several files are missing in the pulled image but exist in the pushed image. I don't think it's easy to reproduce. When I use another machine to run the gitlab-ci-runner everything works fine.

here are my dockerfile
```
FROM node:8.1.3-alpine

RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main/" > /etc/apk/repositories

RUN apk add tzdata curl python make g++ --no-cache \
 && rm /etc/localtime \
 && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /data/apps/graphql-api

COPY package.json package-lock.json .npmrc /data/apps/graphql-api/
RUN npm install

COPY . /data/apps/graphql-api/

RUN mkdir -p /data/apps/graphql-api/build/logs \
 && mkdir -p /data/apps/graphql-api/logs \
 && npm run build:prod

HEALTHCHECK --interval=10s --timeout=1s --retries=3 \
  CMD curl -fs http://localhost:9090/ping || exit 0

EXPOSE 9090

CMD [ "node", "build/server/index.js"]
```

The missed files are some files installed by npm. I can only find one example now, but there are several files missing: 
`node_modules/source-map-support/node_modules/source-map/lib/source-map-generator`

**Steps to reproduce the issue:**
1. on the build machine: docker build -t my.registry/my-repo:#git-commit-hash .
2. on the build machine: docker push my.registry/my-repo:#git-commit-hash
3. on the target machine: docker pull my.registry/my-repo:#git-commit-hash
4. on the target machine: docker run my.registry/my-repo:#git-commit-hash

**Describe the results you received:**
app failed to start, report some file missing.

**Describe the results you expected:**
app should start normally.(And it's true when image is built on my mac or any other machine).

**Additional information you deem important (e.g. issue happens only occasionally):**
It only happens on one particular machine, and that machine have built lots of images for this project.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 51
 Running: 1
 Paused: 0
 Stopped: 50
Images: 114
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-18787642-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.995GB
 Data Space Total: 107.4GB
 Data Space Available: 97.38GB
 Metadata Space Used: 14.29MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.133GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: pending
 NodeID: 2gxu3g460e2bzl9p4khkyjmsl
 Is Manager: false
 Node Address: 10.0.1.50
 Manager Addresses:
  10.0.1.50:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.451GiB
Name: ip-10-0-1-50.cn-north-1.compute.internal
ID: IDLL:2UNQ:GDNU:XLCN:VQ5R:U42J:A653:2UOM:JGRK:6NXX:DB5B:3RTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS
image is build through another image: docker:1.13.1-git

**Comment by DavidWittman** [comment]
@huang475 I'm experiencing a similar issue, and I think I've correlated it to having something to do with really long filenames (as npm tends to produce) and newer versions of the Docker daemon (I've only verified on 17.06). Specifically, in my case, all paths which are > 100 characters are getting chomped and put in the root of the filesystem.

**Comment by huang475** [comment]
@DavidWittman you are right, I checked another long-name-file, and it's missing too. Thanks, I will close this issue and follow #29360 instead.
