### ISSUE TITLE
Is it possible to manage docker containers on premises as well as on Microsoft Azure Container service under one docker Swarm Cluster?

### ISSUE THREAD

**Issue by qasim9641** [moby/moby#34341]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Ask Microsoft?

Closing since this is not an issue or something we can even answer on this repo, sorry.
