### ISSUE TITLE
node status abnormal through repeated promote/demote

### ISSUE THREAD

**Issue by ityangchen** [moby/moby#34350]
**Description**

In a cluster of 3 nodes(node1, node2, node3)
on node1 ,repeated promote/demote node2 node3
then node3`s status  is abnormal

**Steps to reproduce the issue:**
1. on node1
node-1:~ # docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
4pkyvphwujyd9eiasxllrg22h     node-3              Ready               Active              
i3d1uc7nac3149txzxv0g6ige *   node-1              Ready               Active              Leader
q3xwcjtpub4qr0o1g7o4uluuy     node-2              Ready               Active              Reachable
node-1:~ # cat promote.sh 
#!/bin/bash

for i in $(seq 1 100)
do
echo "promoting-------------"
docker node promote $1 $2
echo "promote done"
sleep 1
docker node ls
sleep 1
echo "demoting--------------"
docker node demote $1 $2
echo "demote done"
sleep 1
docker node ls
sleep 1
done
node-1:~ # ./promote.sh node-2 node-3

**Describe the results you received:**
node-1:~ # docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
4pkyvphwujyd9eiasxllrg22h     node-3              Ready               Active              
i3d1uc7nac3149txzxv0g6ige *   node-1              Ready               Active              Leader
q3xwcjtpub4qr0o1g7o4uluuy     node-2              Ready               Active              Reachable
node-1:~ # docker node inspect node-3 | more
[
    {
        "ID": "4pkyvphwujyd9eiasxllrg22h",
        "Version": {
            "Index": 221
        },
        "CreatedAt": "2017-08-01T08:12:14.174342953Z",
        "UpdatedAt": "2017-08-01T08:18:55.556527191Z",
        "Spec": {
            "Labels": {},
            "Role": "manager",
            "Availability": "active"
        },
node-3:~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.1-ce-rc1
Storage Driver: devicemapper
 Pool Name: docker-8:1-1312375-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2MB
 Data Space Total: 107.4GB
 Data Space Available: 29.79GB
 Metadata Space Used: 725kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 4pkyvphwujyd9eiasxllrg22h
 Error: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 9.41.140.87
 Manager Addresses:
  9.41.139.209:2377
  9.41.139.235:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 501000483991fdfb84af4aaea773d38491747855
runc version: c515e9a9f0662491ccae2b2abe9fc6a505b935f9
init version: e940168
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.49.58.52.x86_64
Operating System: EulerOS 2.0 (SP2)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.594GiB
Name: node-3
ID: SGCB:4EGQ:2MFZ:2GVM:4Z6B:3KOO:NTFT:YST2:V3DW:3MRX:K4ZS:QFRH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 111
 System Time: 2017-08-01T08:23:20.697927651Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Describe the results you expected:**
the output of "docker node ls  "  "docker  node  inspect node-3" should be consistent.
node3`s MANAGER STATUS does not match the output of "docker  node  inspect node-3"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
node-1:~ # docker version
Client:
 Version:      17.06.1-ce-rc1
 EulerVersion: 17.06.0.1
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   8d77886
 Built:        Tue Aug  1 08:00:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce-rc1
 EulerVersion: 17.06.0.1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8d77886
 Built:        Tue Aug  1 07:59:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
(paste your output here)
```

**Output of `docker info`:**
node-3:~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.1-ce-rc1
Storage Driver: devicemapper
 Pool Name: docker-8:1-1312375-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2MB
 Data Space Total: 107.4GB
 Data Space Available: 29.79GB
 Metadata Space Used: 725kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 4pkyvphwujyd9eiasxllrg22h
 Error: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 9.41.140.87
 Manager Addresses:
  9.41.139.209:2377
  9.41.139.235:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 501000483991fdfb84af4aaea773d38491747855
runc version: c515e9a9f0662491ccae2b2abe9fc6a505b935f9
init version: e940168
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.49.58.52.x86_64
Operating System: EulerOS 2.0 (SP2)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.594GiB
Name: node-3
ID: SGCB:4EGQ:2MFZ:2GVM:4Z6B:3KOO:NTFT:YST2:V3DW:3MRX:K4ZS:QFRH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 111
 System Time: 2017-08-01T08:23:20.697927651Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ityangchen** [comment]
etcd/raft/node.go,  I  added some debug  log.

when node-3 was abnormal, alway printed  "test-ycl etcd-raft-run-0", without "test-ycl etcd-raft-run-1"

func (n *node) run(r *raft) {

	for {
		if advancec != nil {
			readyc = nil
		} else {
			r.logger.Infof("test-ycl etcd-raft-run-0")
			
			rd = newReady(r, prevSoftSt, prevHardSt)
			if rd.containsUpdates() {
				readyc = n.readyc
			} else {
				readyc = nil
			}
		}


		select {

		case m := <-propc:

		case m := <-n.recvc:

		case cc := <-n.confc:

		case <-n.tickc:
			
		case readyc <- rd:
			r.logger.Infof("test-ycl etcd-raft-run-1")

		case <-advancec:

		case c := <-n.status:
			
		case <-n.stop:

		}
	}
}

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
