### ISSUE TITLE
Swarm - Stack Deploy Error - "No such image: ..."

### ISSUE THREAD

**Issue by coditori** [moby/moby#34351]
Any time I deployed to a stack it just available on manager node not worker! (both are pysical machines)

sudo docker node ls
```
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
jstd3fuet5mn1v0ddv4g104dz *   ma                  Ready               Active              Leader
taekdd7w134detpmzzdqvhec5     laptop-138          Ready               Active
```

docker-compose-yml
```
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: nginx
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
```

after running "sudo docker stack deploy -c docker-compose.yml st-0801-1417"
sudo docker stack ps st-0801-1417
```
ID                  NAME                     IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR                           PORTS
imcuq9ylr5qq        st-0801-1417_web.1       nginx               ma                  Running             Running 3 minutes ago                                    
jh9y5vkz22yx         \_ st-0801-1417_web.1   nginx               laptop-138          Shutdown            Rejected 2 minutes ago   "No such image: nginx:latest"   
2t6uxaaqwksv         \_ st-0801-1417_web.1   nginx               laptop-138          Shutdown            Rejected 2 minutes ago   "No such image: nginx:latest"   
9qz6efcr57q7        st-0801-1417_web.2       nginx               ma                  Running             Running 3 minutes ago                                    
rlffnlts210q        st-0801-1417_web.3       nginx               ma                  Running             Running 3 minutes ago                                    
wipjojcckla3         \_ st-0801-1417_web.3   nginx               laptop-138          Shutdown            Rejected 2 minutes ago   "No such image: nginx:latest"   
gc0k18l01w8y         \_ st-0801-1417_web.3   nginx               laptop-138          Shutdown            Rejected 2 minutes ago   "No such image: nginx:latest"   
3p7bhprvj8hq        st-0801-1417_web.4       nginx               ma                  Running             Running 3 minutes ago                                    
s88t2hjnizqu        st-0801-1417_web.5       nginx               ma                  Running             Running 3 minutes ago                                    
ybqr3xm2ez4a         \_ st-0801-1417_web.5   nginx               laptop-138          Shutdown            Rejected 2 minutes ago   "No such image: nginx:latest"   

```
There is no image in worker side and can not serve application from workers!

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by massoudAfrashteh** [comment]
docker version
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Wed Jul 26 18:03:33 2017
 OS/Arch:      linux/amd64
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/version: dial unix /var/run/docker.sock: connect: permission denied
```
$ docker info
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/info: dial unix /var/run/docker.sock: connect: permission denied
[ma@mass]: ~>$ sudo docker info
[sudo] password for ma: 
Containers: 40
 Running: 6
 Paused: 0
 Stopped: 34
Images: 35
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: b5by42c4hq7he9zh1w45lu4dz
 Is Manager: true
 ClusterID: nmwyalzl1n28myk8bhg1rzrnk
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.30.1.158
 Manager Addresses:
  172.30.1.158:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-1-lts
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.57GiB
Name: mass
ID: MHLT:R42O:K2DN:TEDB:7PC5:VWQ3:DDMV:2BHY:REGT:BKKI:H5YQ:QZ5O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: massoudafrashteh
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Vacant0mens** [comment]
Any update on this? This issue has been around for two months, and I'm having the same problem with one (only one) of my swarm nodes on 17.06.2-ee-4.

**Comment by je-al** [comment]
I'm also experiencing this issue (haven't quite pin-pointed what could be causing it), but it only ever happens with public (docker's public registry / hub.docker.com) images...

**Comment by oeddyo** [comment]
same here


> [ec2-user@ip-10-0-1-81 ~]$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Nov 10 00:50:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   402dd4a/17.06.2-ce
 Built:        Fri Nov 10 00:51:08 2017
 OS/Arch:      linux/amd64
 Experimental: false





> Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 2.597GB
 Data Space Total: 23.33GB
 Data Space Available: 20.73GB
 Metadata Space Used: 1.54MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 23.63MB
 Thin Pool Minimum Free Space: 2.333GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: jq1p120bio3u3lhdawxjiva0l
 Is Manager: true
 ClusterID: xh43kyurnb5jmzvkp5t59zxrt
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.1.81
 Manager Addresses:
  10.0.1.81:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.62-21.56.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86GiB
Name: ip-10-0-1-81
ID: WPI4:USE6:4CKH:TBBP:NVTJ:ZS6Z:FYQU:WKPD:NYZQ:RMYQ:3Z2E:6VUW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ajardan** [comment]
We also have this issue with 

Docker version 17.09.0-ce, build afdb6d4

in a 7 node swarm cluster. Only one node is able to fetch images from the private registry, even though --with-registry-auth is specified during service deploy and it worked before

**Comment by Zogg** [comment]
Same here.

Docker Version
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 762.8 MB
 Data Space Total: 212.4 GB
 Data Space Available: 211.6 GB
 Metadata Space Used: 499.7 kB
 Metadata Space Total: 218.1 MB
 Metadata Space Available: 217.6 MB
 Thin Pool Minimum Free Space: 21.24 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: m2xw70o21rje5ci3pckeqtkqx
 Is Manager: true
 ClusterID: y1dzuxffwkq300qc3968j4dxt
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.135.***.***
 Manager Addresses:
  10.135.***.***:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.43-17.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.798 GiB
Name: ip-**-***-***-***
ID: PZ3F:TRXE:HPJJ:S6TR:D5ZN:FRSK:2JMW:V3R6:5LFH:F7JL:IZZH:I2FO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 nexus.****.net:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ajardan** [comment]
After some more troubleshooting we found out Docker Swarm was not the root cause.

Gitlab changed their permissions for the CI tokens, so only the node where the service was deployed to had permission to pull the image.

With a valid, permanent token, the cluster was able to pull and deploy the image correctly. So if you are using Gitlab, you might want to check this.

**Comment by tblake84** [comment]
I am seeing this issue with a private repo right now.  I am using docker swarm on a RPi cluster and stack deploy pulls the image successfully to the master node (I am only running 2/6 nodes right now) and node2 throws the "No such image" error.

`Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ln72kipwwn7kqtgatyu6h1ihu
 Is Manager: true
 ClusterID: cq2fzf8f8ywzxq3vdz0gg1scu
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.0.2
 Manager Addresses:
  10.0.0.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.80-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 927.3MiB
Name: bramble01
ID: 5OQ5:FICR:IVKD:K2BK:SPRU:WH42:JAY4:QKMU:RGDR:IJOO:KDLL:6IUN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
`

**Comment by tblake84** [comment]
Just confirmed.  I am seeing this issue with both a locally created registry and AWS ECR registries when attempting 'docker stack deploy'.

**Comment by v7lin** [comment]
I have same question.

````
  blog:
    image: registry.${SERVER_DOMAIN:-localhost}/haitanyule/blog:latest
#    ports:
#      - 80
    networks:
      - traefik_net
    environment:
      - TZ=${TIME_ZONE}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.port=80"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.rule=Host:blog.${SERVER_DOMAIN:-localhost}"
````

shell
````
docker stack deploy -c <(docker-compose -f docker-compose-swarm-services.yml config) services
````

portainer
````
No such image: registry.haitanyule.com/haitanyule/blog:latest
````

docker version
````
[root@centos dev-ops]# docker -v
Docker version 18.09.0, build 4d60db4
````

**Comment by thaJeztah** [comment]
Looks like you're trying to deploy an image from a registry that requires authentication.

Make sure that you use `--with-registry-auth` when deploying, because the swarm node that the service is deployed on won't have access to the credentials that you have stored locally. This even applies when the node is "local", as it's the _cli_ that keeps the credentials, the _daemon_ doesn't have access to them, unless you send the credentials to the daemon.

```bash
docker pull registry.haitanyule.com/haitanyule/blog:latest
Error response from daemon: Get https://registry.haitanyule.com/v2/haitanyule/blog/manifests/latest: no basic auth credentials
```

**Comment by v7lin** [comment]
> 看起来您正在尝试从需要身份验证的注册表部署映像。
> 
> 确保`--with-registry-auth`在部署时使用，因为部署服务的swarm节点将无法访问您本地存储的凭据。这甚至适用于节点是“本地”的情况，因为它是保存凭据的_cli_，_守护程序_无权访问它们，除非您将凭据发送到守护程序。
> 
> ```shell
> docker pull registry.haitanyule.com/haitanyule/blog:latest
> 来自守护程序的错误响应：获取https://registry.haitanyule.com/v2/haitanyule/blog/manifests/latest：没有基本身份验证凭据
> ```

I have logged in
````
[root@centos dev-ops]# docker login registry.haitanyule.com
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
````

**Comment by superhero** [comment]
@thaJeztah having the same problem here, I can solve the problem by manually going to the worker and run `docker pull username/imagename` ... then it works for some reason.

the deploy process we use is however not cli based, it uses the docker http api. When inspecting the docs there, I have troubles finding any such flag: `with-registry-auth` or similar.

If you know how to, pls let me know.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
