### ISSUE TITLE
Allow overlay2 on 7.4 kernel 3.10.0-693.el7.x86_64 or higher?

### ISSUE THREAD

**Issue by clemenko** [moby/moby#34368]
Allow the uses of overlay2 in the 3.10.0-693.el7.x86_64 kernel now that Redhat officially supports it?

https://github.com/moby/moby/blob/1009e6a40b295187e038b67e184e9c0384d95538/daemon/graphdriver/overlay2/overlay.go#L136-L141

**Steps to reproduce the issue:**
1. Install docker-ce 17.0.6 on rhel 7.4
2. `echo -e "{ \"storage-driver\": \"overlay2\" }" > /etc/docker/daemon.json; systemctl restart docker`

**Describe the results you received:**
Docker should restart.

**Describe the results you expected:**
Docker doesn't support overlay2 on rhel 7.4.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

[root@rhel74 ~]# docker -v
Docker version 17.06.0-ce

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware fusion. also tested on aws.

**Comment by chanwit** [comment]
You can override the kernel check with `--storage-opts overlay2.override_kernel_check=true`.

Ref: https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver

**Comment by clemenko** [comment]
This issue for changing the default behavior and not require the `--storage-opts`.

**Comment by thaJeztah** [comment]
I think there's a couple of options;

through packaging;

- use a different unit file for RHEL7 and CentOS7 rpm's that has the `--storage-opt  overlay2.override_kernel_check=true` set by default
- add a drop-in unit file that's installed by the RHEL/CentOS packages (similar to above)

changing the check in the daemon;

- add a compile-time option that disables the check; we can set that when compiling binaries for RHEL/CentOS
- add a very specific kernel-version check that allows overlay2 to be used on `kernel 3.10-<suffix>`

For the kernel check, I think technically the `-suffix` is not part of the kernel's versioning, so this could cause issues with other distros running kernel 3.10

Overall, a vanilla 3.10 kernel is way too old to run docker in a sensible way, so perhaps this is no concern

- Ubuntu 14.04 runs at least kernel 3.13 (they are promoting the Xenial kernels, which is 4.x)
- Debian Wheezy ships with 3.2 by default, which is not supported, so needs to be upgraded  to a newer version, but kernels < 3.16 (IIRC) don't support overlay at all, so I guess that's ok

**Comment by thaJeztah** [comment]
ping @dmcgowan wdyt?

**Comment by clemenko** [comment]
My vote is a better kernel check internal to the engine!

**Comment by dmcgowan** [comment]
I think the pattern we have mostly been following here is just testing for the functionality. We don't do too many of these on `Init` but it wouldn't be unreasonable to check for it on Init to detect whether it is supported. The check would only need to be done on older kernels when the `overlay2.override_kernel_check` is not provided.

**Comment by thaJeztah** [comment]
Discussing this in the maintainers meeting with @cpuguy83 and @tianon 

- standard kernels < 3.18 don't support overlay (thus no overlay2 as well), so that shouldn't be a problem
- if we detect a kernel < 3.18 that _does_ support overlay, we likely have a RHEL kernel, in which case we can do the detection that @dmcgowan suggested. This will probably be slow, but only an issue when starting the daemon

We were ok with adding this detection for that case; @dmcgowan are you able to work on that, or have any hints what would be needed (if someone else wants to work on it)?

**Comment by dmcgowan** [comment]
@thaJeztah the hint would be looking at how we detect overlay features in https://github.com/moby/moby/blob/master/daemon/graphdriver/overlay2/check.go. This is not a difficult change, but I think it is better left to someone who has easy access to a RHEL environment to test on. If someone can provide me access to one I don't mind working on it.
