### ISSUE TITLE
Impossible to pull some public images

### ISSUE THREAD

**Issue by MatMaul** [moby/moby#34365]
I get 401 when trying to get some layers on a public image. Doesn't happen all the time, but at least one on 2 times...
cf here:
https://github.com/docker/hub-feedback/issues/1103

I can't launch clusters since some days because of that and it took me a while to figure out.
Please have a look because having a critical piece of infra like that not working reliably and fixed in a timely manner is really not cool.
In the meantime I am switching to another registry...

**Comment by thaJeztah** [comment]
Can you contact support@docker.com ? If this is an issue with Docker Hub, there's not much that can be done in this repository.

Closing this issue, but feel free to continue the conversation

**Comment by MatMaul** [comment]
Yes I know but it was to get some attention... I'll send a mail thanks. There is no IRC anymore right ?

**Comment by thaJeztah** [comment]
The Docker Hub team is not on IRC, only the open source projects are (well, mainly the Docker Community Slack now)

**Comment by zidad** [comment]
I just got the same issue:

ERROR: Get https://registry-1.docker.io/v2/mobz/elasticsearch-head/manifests/5: unauthorized: incorrect username or password

Client:                                               
 Version:      17.06.1-ce                             
 API version:  1.30                                   
 Go version:   go1.8.3                                
 Git commit:   874a737                                
 Built:        Thu Aug 17 22:48:20 2017               
 OS/Arch:      windows/amd64                          
                                                      
Server:                                               
 Version:      17.06.1-ce                             
 API version:  1.30 (minimum version 1.12)            
 Go version:   go1.8.3                                
 Git commit:   874a737                                
 Built:        Thu Aug 17 22:54:55 2017               
 OS/Arch:      linux/amd64                            
 Experimental: true
