### ISSUE TITLE
Docker builder documentation doesn't talk about TCP/UDP in EXPOSE

### ISSUE THREAD

**Issue by rcjsuen** [moby/moby#34373]
I was looking at [`dispatchers.go`](https://github.com/moby/moby/blob/f577caff19d486d8d01443507d891cb1b0891cdc/builder/dockerfile/dispatchers.go#L689-L693) today when I realized that you can actually specify `tcp` or `udp` when you use the `EXPOSE` instruction.

This isn't mentioned at all in the [Dockerfile reference for `EXPOSE`](https://docs.docker.com/engine/reference/builder/#expose). Is this intentional?

**Comment by thaJeztah** [comment]
I don't think this is intentional; perhaps you're interested in contributing and open a pull request to update that page of the documentation? The  source file used to generate that page can be found in the docker/cli repository; https://github.com/docker/cli/blob/master/docs/reference/builder.md

**Comment by rubensfig** [comment]
Hey, I am interested in contributing to this issue.

**Comment by mstanleyjones** [comment]
This issue is actually mis-filed and should have been raised against `docker/cli` but the PR is in the right place, so let's just close this here.
