### ISSUE TITLE
Overlay network does not work unless restart docker

### ISSUE THREAD

**Issue by antoinetran** [moby/moby#34388]
**Description**
With CentOs 7.3, Docker 17.06, firewalld, Swarm image (1.2.6 classic mode). A container in a overlay network cannot ping another container in another host. But it can resolve its IP.

**Steps to reproduce the issue:**
1.Install docker
2.Deploy Swarm nodes and manager(s)
3.Deploy some containers in overlay network
4.Some random hosts are impacted: all containers from these hosts cannot ping (but can resolve) any Swarm services.
5.If there is no error in step 4, stop all containers, remove them, uninstall docker, and redo from step 1.

**Describe the results you received:**
`systemctl restart docker` is a workaround, it reenables network.

**Describe the results you expected:**
The ping works.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 28
 Running: 19
 Paused: 0
 Stopped: 9
Images: 48
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: vg_docker-lv_thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 31.75GB
 Data Space Total: 3.389TB
 Data Space Available: 3.357TB
 Metadata Space Used: 13.59MB
 Metadata Space Total: 16.98GB
 Metadata Space Available: 16.96GB
 Thin Pool Minimum Free Space: 338.9GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.6GiB
Name: fl2pdck-s01.l2pf.fac.mtg
ID: JUF7:YEHS:K6FJ:XFKT:CD3Q:HSIQ:24UD:LHAK:6JHS:IOJK:QHJK:PCLK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.node=dockerhost
Experimental: false
Cluster Store: zk://fl2pdck-s01:2181,fl2psto-s01:2181,fl2psto-s02:2181
Cluster Advertise: 10.4.117.10:2375
Insecure Registries:
 fl2pdck-s01.l2pf.fac.mtg:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `docker -H swarm-manager:4000 info`:**

```
Containers: 90
 Running: 74
 Paused: 0
 Stopped: 16
Images: 336
Server Version: swarm/1.2.6
Role: replica
Primary: 10.4.117.21:4000
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 8
 fl2pdck-s01.l2pf.fac.mtg: fl2pdck-s01:2375
  └ ID: JUF7:YEHS:K6FJ:XFKT:CD3Q:HSIQ:24UD:LHAK:6JHS:IOJK:QHJK:PCLK
  └ Status: Healthy
  └ Containers: 28 (19 Running, 0 Paused, 9 Stopped)
  └ Reserved CPUs: 14 / 58
  └ Reserved Memory: 68 GiB / 264.2 GiB
  └ Labels: com.docker.node=dockerhost, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:56:29Z
  └ ServerVersion: 17.06.0-ce
 fl2pdck-s02.l2pf.fac.mtg: fl2pdck-s02:2375
  └ ID: BKBV:OLC2:367G:WD7H:BPE3:PIP3:IN4N:KUPK:XUMC:X5BM:WOMK:ONEO
  └ Status: Healthy
  └ Containers: 29 (24 Running, 0 Paused, 5 Stopped)
  └ Reserved CPUs: 16 / 58
  └ Reserved Memory: 44 GiB / 264.2 GiB
  └ Labels: com.docker.node=dockerhost, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:56:35Z
  └ ServerVersion: 17.06.0-ce
 fl2ppro-s01.l2pf.fac.mtg: fl2ppro-s01:2375
  └ ID: 2ZR7:BT7A:2Q32:JH6B:OHY3:AOP7:33TK:H4ZU:ECQT:CIJN:DUFS:ZHCC
  └ Status: Healthy
  └ Containers: 5 (5 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 2 / 58
  └ Reserved Memory: 6 GiB / 131.9 GiB
  └ Labels: com.docker.node=processing, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:56:47Z
  └ ServerVersion: 17.06.0-ce
 fl2ppro-s02.l2pf.fac.mtg: fl2ppro-s02:2375
  └ ID: 4DYO:FLDI:GQ6C:PC6J:O63F:P66K:PASH:5MAY:XMWJ:4HUL:3KFK:GCYZ
  └ Status: Healthy
  └ Containers: 5 (3 Running, 0 Paused, 2 Stopped)
  └ Reserved CPUs: 0 / 58
  └ Reserved Memory: 0 B / 131.9 GiB
  └ Labels: com.docker.node=processing, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:57:02Z
  └ ServerVersion: 17.06.0-ce
 fl2ppro-s03.l2pf.fac.mtg: fl2ppro-s03:2375
  └ ID: 4MFM:ORO2:AEZF:3MIX:6KZ6:UUKJ:C543:IBLG:ZHDT:LRAW:G42K:7JIQ
  └ Status: Healthy
  └ Containers: 4 (4 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 58
  └ Reserved Memory: 0 B / 131.9 GiB
  └ Labels: com.docker.node=processing, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:56:58Z
  └ ServerVersion: 17.06.0-ce
 fl2ppro-s04.l2pf.fac.mtg: fl2ppro-s04:2375
  └ ID: GNYB:3EO7:Z4SZ:PO6S:B4OB:S6OY:Y3EN:X4XJ:Z5NA:TC5X:M65H:RCIF
  └ Status: Healthy
  └ Containers: 5 (5 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 2 / 58
  └ Reserved Memory: 6 GiB / 131.9 GiB
  └ Labels: com.docker.node=processing, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:57:00Z
  └ ServerVersion: 17.06.0-ce
 fl2psto-s01.l2pf.fac.mtg: fl2psto-s01:2375
  └ ID: RFJX:MRIG:33JO:532Z:AIWN:S4AY:HP4E:OAU2:MM5E:DPTP:5RAV:WVB3
  └ Status: Healthy
  └ Containers: 7 (7 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 42
  └ Reserved Memory: 0 B / 98.84 GiB
  └ Labels: com.docker.node=storage, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:57:00Z
  └ ServerVersion: 17.06.0-ce
 fl2psto-s02.l2pf.fac.mtg: fl2psto-s02:2375
  └ ID: QAUX:43YR:XY4U:6YAS:5VVR:7UHK:4L7E:KMCD:NM5A:HLPP:GB4B:NPIX
  └ Status: Healthy
  └ Containers: 7 (7 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 42
  └ Reserved Memory: 0 B / 98.84 GiB
  └ Labels: com.docker.node=storage, kernelversion=3.10.0-514.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2017-08-03T11:56:50Z
  └ ServerVersion: 17.06.0-ce
Plugins: 
 Volume: 
 Network: 
 Log: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 432
Total Memory: 1.224TiB
Name: 32eae23c1ec7
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machines.

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by antoinetran** [comment]
@thaJeztah , related to docker version and docker info, I will provide them in a few minutes, when my team is ready. Related to the reproduction test, it is a very random bug, but I will try to put more information.

**Comment by thaJeztah** [comment]
One thing that may play a role here is `firewalld` - if `firewalld` reloaded firewall rules after docker was started, chances are it removed all the rules that docker created

**Comment by antoinetran** [comment]
I tried the following commands as root to see the impact of firewalld:
`firewall-cmd --reload`
`firewall-cmd --add-port 55555/tcp --zone public`
`firewall-cmd --add-port 55555/tcp --zone public --permanent`
`firewall-cmd --reload`
`systemctl restart firewalld`
`systemctl stop firewalld`

Each time, I tried to ping from a container, a Swarm service and a machine. But it still work. I tried all these in a physical Swarm cluster, and a Swarm cluster in VM.

**Comment by antoinetran** [comment]
I couldn't upload > 3MO of message files, so I put them here https://files.fm/down.php?i=v8fxmfv4&n=message.zip. These contain a copy of /var/log/messages, one from a OK machine, one from a KO machine.

**Comment by antoinetran** [comment]
Ok, here are more info. We encountered this issue one more time today. It happens this time on one container only, that could hardly ping any other services. There are lots lots of packets drop. We disabled firewalld (`systemctl stop firewalld`) in 2 machines, it didn't change anything. In another container in the same machine, there is no problem. We had to restart the container to have it working again.

**Comment by mploschiavo** [comment]
is there any solution to this issue?  I see this same behavior.   What should I look for?  Firewalls are disabled/not installed.  I have docker swarm with multiple vms.  On VM1, I have multiple containers, container A and B.  On vm2, I have container C.  From container A, I can ping container C.  From container A, I cannot access container C port 5672 (rabbitmq).  From container B on same VM1,  I can ping Container C and amble to access container C port 5672.   Behavior is intermittent.  I restart the container and then it works for some period of time.  This happens randomly to all my containers with different technologies.

**Comment by antoinetran** [comment]
After two years of buggy overlay network, we removed overlay from our project. Impossible to use in production, nor in dev. Try to upgrade OS + docker + swarm image (if you use swarm classic). Good luck.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  If you encounter this issue on a current engine release, please open a new issue.
