### ISSUE TITLE
Windows Docker Swarm - container-to-container across nodes does not work

### ISSUE THREAD

**Issue by philieu** [moby/moby#34387]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
I have a docker swarm with 2 Windows Server 2016 VM.
Containers running in one node in the swarm can NOT reach containers running in another node using the IP assigned by the overlay network.
Communication between containers in the same node works.

**Steps to reproduce the issue:**
  1. "Docker swarm init " in one windows server machine
  2. "Docker swarm join " in another windows server machine
  3. Confirmed cluster is up and running using "docker node ls"
  4. Create overlay network using "docker network create --driver overlay my-overlay"
  5. Create service test1: "docker service create --name test1 --network my-overlay microsoft/aspnet:4.6.2"
  6. Create service test2: "docker service create --name test2 --network my-overlay microsoft/aspnet:4.6.2"
  7. Confirmed that containers of test1 and test2 are running in different node.
  8. Note down the IP of container of service test2 (for example 10.0.0.3).
  9. Docker exec container of test1: docker exec -it <id> powershell
  10. curl http://10.0.0.3 => "**Unable to connect to the remote server**"
  11. ping 10.0.0.3 => "**Request timed out**"

**Additional information you deem important (e.g. issue happens only occasionally):**
  - Windows Server 2016 patched to the latest update in July 2017.
  - Docker 17.06 CE
  - Two VMs running using VirtualBox, managed by vagrant
Also tested with docker-17.3-ee with the same result.

**Output of `docker info`:**

```
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: zfluw77tojdyx8z7wvt7inyy6
 Is Manager: true
 ClusterID: ai90v1aht595kso5xtvegra8x
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.42.2
 Manager Addresses:
  172.16.42.2:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1480.amd64fre.rs1_release.170706-2004)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3GiB
Name: windows01
ID: 4TFU:JW3G:2JT6:IH4E:TTE5:JLBF:MVZA:2LA7:SX4Q:KGOB:C6MM:L75M
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant, VirtualBox (1 NAT and 1 Host-Only adapter)

**Comment by rickbutton** [comment]
I am also having this exact issue. Any ideas? Fully patched Windows Server 2016
