### ISSUE TITLE
fix sirupsen/logrus dep case sensitivity

### ISSUE THREAD

**Issue by chrisdostert** [moby/moby#34391]
sirupsen/logrus is referenced as Sirupsen/logrus (uppercase S). This breaks many package managers as the package has been more recently published as sirupsen/logrus (lowercase s), leading to conflicts. 

The fix is to simply update the pkg reference to the new lowercase based name

## Reference: 
https://github.com/sirupsen/logrus/issues/553
https://github.com/golang/dep/issues/797

**Comment by klingtnet** [comment]
Why is this closed without a comment? The import path to use is `github.com/sirupsen/logrus` and not `.../Sirupsen/logrus` anymore.

**Comment by vdemeester** [comment]
@klingtnet I think @chrisdostert did see that it was a duplicate issue from https://github.com/moby/moby/issues/33641 👼

**Comment by klingtnet** [comment]
@vdemeester Thanks!
