### ISSUE TITLE
Secret already exists when deploying via docker stack

### ISSUE THREAD

**Issue by je-al** [moby/moby#34403]
(I'm not sure if this is the right place to report this...)
Deploying by using the `docker stack` sub-command, using the `-c` option, yields an error message of the form `Error response from daemon: Error response from daemon: rpc error: code = 6 desc = secret XXX already exists`, when as the message says, the secret already existed (because the stack had been previously deployed), thus negating the possibility of using it for updates.

Docker versions:
```
Client:
 Version:      17.04.0-ce
 API version:  1.26 (downgraded from 1.28)
 Go version:   go1.7.5
 Git commit:   78d1802
 Built:        Sun Jul 30 13:28:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.1.4
 API version:  1.27 (minimum version 1.20)
 Go version:   go1.7.4
 Git commit:   10e6c44
 Built:        Thu May  4 22:49:35 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

While the underlying versions are (I'm using Docker for AWS):
```
Client:
 Version:      17.03.1-ee-2
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   ad495cb
 Built:        Tue Mar 28 19:10:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ee-2
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ad495cb
 Built:        Tue Mar 28 19:10:44 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
Are you updating the value of the secret in your case? Secrets are immutable, hence trying to update the value of a secrets may trigger this error

**Comment by je-al** [comment]
@thaJeztah I'm not modifying their "content" files, so I'd think I'm not.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
