### ISSUE TITLE
Please clarify the version release policy

### ISSUE THREAD

**Issue by eli-b** [moby/moby#34418]
Version 17.03.0 was documented to be the first in a monthly release cycle.
Since then, there was a May release but no April, June or July release.
Am I looking for releases in the wrong place?

Please don't view this as a complaint.
It would just be helpful if you could clarify the version release policy, so expectations are well-managed.

**Comment by thaJeztah** [comment]
The new release cycle consists of "stable" (quarterly) and "edge" (monthly) releases; docker 17.03 and 17.06 are quarterly releases, and found in the stable channel, [17.04](https://github.com/moby/moby/releases/tag/v17.04.0-ce) and [17.05](https://github.com/moby/moby/releases/tag/v17.05.0-ce) are found in the "edge" channel. Together with the new release cycle, new apt/yum repositories were also introduced, which hosts the `docker-ce` packages, and can be found at https://download.docker.com, where you'll find both the _edge_ (e.g. https://download.docker.com/linux/ubuntu/dists/xenial/pool/edge/amd64/) and  _stable_ (e.g. https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/) release channels.

If you're looking for releases on GitHub; With the introduction of the Moby project, releases are now built from the https://github.com/docker/docker-ce repository (see the releases page there https://github.com/docker/docker-ce/releases). Docker CE is composed of several components (CLI, "engine") this repository forms the "engine" component in Docker's releases; https://github.com/docker/docker-ce/tree/master/components/engine

Does this answer your question?

**Comment by eli-b** [comment]
Thanks @thaJeztah, that's very helpful. I really was looking for releases on this GitHub project.

Version 17.03.0's documentation at https://github.com/moby/moby/releases/tag/v17.03.0-ce should probably be improved so people know where to look for future versions.
