### ISSUE TITLE
Docker swarm cluster  REPLICAS 0/1

### ISSUE THREAD

**Issue by karthick0070** [moby/moby#34417]
I have created 2 windows 2016 VMs with container services and installed docker.  I have created my sample web server using windows server core  image and named as web server using docker file.  if i run 
`Docker run -it webserver`   i can access the running webserver. So i started installing Swarm cluster i have created network and services using my own image ( webserver).  but these is not running it throwing some error.  Below are the details
i have used the below command to create services and network

```
# Create an overlay network 
C:\> docker network create --driver=overlay <NETWORKNAME>
```

` docker service create --name site --endpoint-mode dnsrr --publish mode=host,target=8000 --network winnet --constraint 'node.labels.os==windows' webserver`

C:\Users\Administrator>docker service ps site
.os==windows' webserver
C:\Users\Administrator>docker service ps site
ID            NAME        IMAGE             NODE             DESIRED STATE  CURRENT STATE            ERROR                             PORTS
fctwh0m61vdq  site.1      webserver:latest  WIN-NGCG1EF8Q2E  Running        Starting 45 seconds ago
l90rlq7yz6c0   \_ site.1  webserver:latest  WIN-NGCG1EF8Q2E  Shutdown       Failed 53 seconds ago    "starting container failed: co…"
neysybdecy0v   \_ site.1  webserver:latest  WIN-NGCG1EF8Q2E  Shutdown       Failed 3 minutes ago     "starting container failed: co…"
xecfidph7iyy   \_ site.1  webserver:latest  WIN-NGCG1EF8Q2E  Shutdown       Failed 5 minutes ago     "starting container failed: co…"
out16fj1q913   \_ site.1  webserver:latest  WIN-NGCG1EF8Q2E  Shutdown       Failed 7 minutes ago     "starting container failed: co…"
ckn3ba8t73ar  site.3      webserver:latest  WIN-GF8BN4SIBQE  Running        Starting 18 seconds ago
pdpwsq20phzn   \_ site.3  webserver:latest  WIN-GF8BN4SIBQE  Shutdown       Failed 25 seconds ago    "starting container failed: co…"
ib2m7uzhnghh   \_ site.3  webserver:latest  WIN-GF8BN4SIBQE  Shutdown       Failed 2 minutes ago     "starting container failed: co…"
v6qph3v6qx5h   \_ site.3  webserver:latest  WIN-GF8BN4SIBQE  Shutdown       Failed 4 minutes ago     "starting container failed: co…"
tga64plhn6u5   \_ site.3  webserver:latest  WIN-GF8BN4SIBQE  Shutdown       Failed 5 minutes ago     "starting container failed: co…"

C:\Users\Administrator>docker service ls
ID            NAME  MODE        REPLICAS  IMAGE
xh5g1xpndjdg  site  replicated  0/2       webserver:latest

```
docker inspect l90rlq7yz6c0

      "Slot": 1,
        "NodeID": "xc8o80wq2domhwda4xh4ovxwr",
        "Status": {
            "Timestamp": "2017-08-07T06:37:22.4187441Z",
  

>           "State": "failed",
>             "Message": "starting",
>             "Err": "starting container failed: container 746bc44c9252ed579b8c266866e9470312aa89522ef20d0ea9a51c6e7c10a144 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {\"ApplicationName\":\"\",\"CommandLine\":\"top\",\"User\":\"\",\"WorkingDirectory\":\"C:\\\\\",\"Environment\"

:{},\"EmulateConsole\":false,\"CreateStdInPipe\":true,\"CreateStdOutPipe\":true,\"CreateStdErrPipe\":true,\"ConsoleSize\":[0,0]}",
            "ContainerStatus": {
                "ContainerID": "746bc44c9252ed579b8c266866e9470312aa89522ef20d0ea9a51c6e7c10a144",
                "ExitCode": 127
            },
            "PortStatus": {}
        },
        "DesiredState": "shutdown",

```
============================================================
C:\Users\Administrator>docker info
Containers: 13
 Running: 2
 Paused: 0
 Stopped: 11
Images: 5
Server Version: 17.03.0-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: active
 NodeID: xc8o80wq2domhwda4xh4ovxwr
 Is Manager: true
 ClusterID: umonkgidx00chrf82fiah9n33
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.233.131
 Manager Addresses:
  192.168.233.131:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1480.amd64fre.rs1_release.170706-2004)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.999 GiB
Name: WIN-NGCG1EF8Q2E
ID: EAT6:KLZD:BQAY:TXGV:4LR4:POTH:3VSJ:OEQO:TBAN:L322:QFNC:4V3J
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: fals

**Comment by friism** [comment]
Can you run the container with just `docker run webserver`? That's going to make debugging faster and simpler than scheduling services.

It looks you're trying to run `top` which is not a Windows command.

**Comment by karthick0070** [comment]
yes, i can access the web server if i run docker run webserver ... even without top also the same error

**Comment by karthick0070** [comment]
any hep or advice on this

**Comment by karthick0070** [comment]
this is the issue with my own image.. but i downloaded from Microsoft with iis microsoft/iis.  that image is running fine ...

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
