### ISSUE TITLE
Cannot mount volumes outside /home path -- read-only file system

### ISSUE THREAD

**Issue by konopik** [moby/moby#34427]
**Description**

Cannot mount volumes located on different mount points than /home

I can mount volumes in the /home path:

`docker run -i -t -v /home/bigdata/tmp/:/test  ubuntu`

but not volumes outside this path:

`docker run -i -t -v /mnt/bigdata/tmp/:/test  ubuntu`

The mount options are identical for both paths:

results of: `mount | grep sdb3`

`/dev/sdb3 on /home/bigdata type ext4 (rw,relatime,data=ordered)`
`/dev/sdb3 on /mnt/bigdata type ext4 (rw,relatime,data=ordered)`

**Steps to reproduce the issue:**
1. Run docker container with a volume on a path outside /home, e.g. `docker run -i -t -v /mnt/bigdata/tmp/:/test  ubuntu`
2. The following error is produced: `docker: Error response from daemon: error while creating mount source path '/mnt/bigdata/tmp': mkdir /mnt/bigdata: read-only file system.`
3. The same error occurs when a volume is created with the `docker volume create` command.

**Describe the results you received:**

`docker: Error response from daemon: error while creating mount source path '/mnt/bigdata/tmp': mkdir /mnt/bigdata: read-only file system.`

**Describe the results you expected:**

Creating a container with mounted volume on a path outside the /home path.

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens all the time. Even with apparmor disabled with the following options: `--security-opt apparmor=unconfined` and `--privileged`.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   -snap-6d8af6a
 Built:        Thu Jun 29 22:50:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: cfb82a876ecc11b5ca0977d1733adbe58599088a)
runc version: N/A (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-30-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.84GiB
Name: Skola
ID: MZKU:NTSS:P3VX:YL6C:WOQH:PAXY:ZTTM:I7UV:TGEB:O7C6:P5KP:UKFM
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 25
 System Time: 2017-08-07T18:30:35.112381853+02:00
 EventsListeners: 0
Username: konopik
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
A physical machine running:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

**Comment by thaJeztah** [comment]
This looks odd;

```
containerd version:  (expected: cfb82a876ecc11b5ca0977d1733adbe58599088a)
runc version: N/A (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
```

Did you install docker from the `.deb` packages? Is the daemon started using the standard systemd unit?

**Comment by konopik** [comment]
Dear Sebastiaan,

Thanks. I have used the following procedure: `https://askubuntu.com/a/909915`

Is it incorrect?

**Comment by thaJeztah** [comment]
Yes, that information is outdated; ubuntu zesty is now supported, and packages available; see the installation manual: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

If you want all the installation steps to be done "automatically", you can also use the installation script at https://get.docker.com/

**Comment by konopik** [comment]
YES, now, it works correctly.

I have uninstalled and purged the docker from the system, removed the source and then proceeded according to the link you have provided me. Now, everything works correctly.

**Comment by thaJeztah** [comment]
Perfect! Let me close this issue as it doesn't seem to be a bug then :+1:

**Comment by PaulDubar** [comment]
Hi,

I am having this issue myself right now on this setup

My setup is on Ubuntu 18.04.1 LTS

Client:
Version: 18.06.1-ce
API version: 1.38
Go version: go1.10.4
Git commit: e68fc7a
Built: Mon Oct 1 14:25:31 2018
OS/Arch: linux/amd64
Experimental: false

Server:
Engine:
Version: 18.06.1-ce
API version: 1.38 (minimum version 1.12)
Go version: go1.10.4
Git commit: e68fc7a
Built: Mon Oct 1 14:25:33 2018
OS/Arch: linux/amd64
Experimental: false

pauld@nas01:~$ docker info
Containers: 2
Running: 2
Paused: 0
Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: aufs
Root Dir: /var/snap/docker/common/var-lib-docker/aufs
Backing Filesystem: extfs
Dirs: 22
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.53GiB
Name: nas01
ID: VBWG:KG3H:M7IZ:CTXP:43ZL:GFDN:A2CI:3HTJ:CSOA:YWF4:MXOR:NMSX
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 41
Goroutines: 58
System Time: 2018-10-31T02:40:30.077914945Z
EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

docker was installed as part of a fresh host OS installation.

**Comment by oskargargas** [comment]
I have exact same problem as @PaulDubar. Ubuntu LTS 18.04 w/ docker as part of OS installation. When I try mount path in /mnt I run into above problems

**Comment by PaulDubar** [comment]
Deinstall the snap version of docker amd install the "proper" release from docker and you should be ok. 
It has resulted in me avoiding anything "snap" now.

**Comment by Mikhail-msft** [comment]
I hit this issue by using "ubuntu software" to install the docker. Uninstalling through "ubuntu software" and re-installing using official steps helped https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

**Comment by Alex-Kharkov-71** [comment]
Hello.
Encountered same issue on my server:

```
homeserver:/home# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.2 LTS
Release:	24.04
Codename:	noble
```
```
homeserver:/home# docker --version
Docker version 28.1.1, build 4eba377
```
```
homeserver:/home# docker info
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 27.5.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-26-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 94.34GiB
 Name: blade-homeserver
 ID: e91f7516-c8a5-4056-8d2a-1175c16be2c6
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

docker-ce installed via this [procedure:](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

**Comment by Alex-Kharkov-71** [comment]
Reinstalled.
Now work as expected.
Thank you.
