### ISSUE TITLE
use udev rules behavior when running in container with --priviledges

### ISSUE THREAD

**Issue by muahao** [moby/moby#34429]
**Description**
Firstly I want say , I am not really want to modify /dev/random 's access in product , This is just a test to verify when systemd running in moby  , udev 's rules in /etc/udev/rules.d/xxxx 's behavior

**Steps to reproduce the issue:**

## start a containerA with no --priviledge

```
[root@physicalhost /home/ahao.mah]
#docker run -d --net host reg.docker.xxxxx.com/mybase/centos7u2:latest
36cc8f6759294b2b2900b313c4f978737b11671b7ab2cc185e69fba3f6a9d10c

[root@containerA /home/ahao.mah]
#docker exec -it 36cc8f6759294b2b2900b313c4f978737b11671b7ab2cc185e69fba3f6a9d10c bash
```

modify udev rules  in containerA :

```
[root@containerA /]
#cat  /etc/udev/rules.d/70-test_random.rules
KERNEL=="random",  GROUP="root", MODE="0665", OPTIONS="last_rule"
```

restart this containerA:

```
[root@physicalhost /home/ahao.mah]
#docker restart 36cc8f675929
36cc8f675929
```
containerA's  /dev/random still 0666 ,but not 0665

```
[root@containerA /]
#ll /dev/random
crw-rw-rw- 1 root root 1, 8 Aug  8 11:34 /dev/random
```
At this moment I do not know  why /etc/udev/rules.d/xxx rules is invalid in a no --priviledges container?

## start a containerB with --priviledge

```
[root@physicalhost /home/ahao.mah]
#docker run -d --net host --privileged reg.docker.xxxxx.com/mybase/centos7u2:latest

[root@containerB /home/ahao.mah]
#docker exec -it 1853437e8d2ea7018475b2328a10f1625da8b0c667941d69d912598325dc830d bash
```

Now containerB's /dev/random default access  is also 0666,but I want to modify containerB's /dev/random access to 0660, then I need to use udev rules in /etc/udev/rules.d/xxx

```
[root@containerB /]
#ll /dev/random
crw-rw-rw- 1 root root 1, 8 Aug  8 11:40 /dev/random

[root@containerB /]
#vim /etc/udev/rules.d/70-test_random.rules
KERNEL=="random",  GROUP="root", MODE="0660", OPTIONS="last_rule"
```

Now physicalhost's /dev/random default access  is also 0666,but I modify physical's /dev/random access to 0777

```
[root@physicalhost /]
#cat /etc/udev/rules.d/70-test_random.rules
#KERNEL=="random",  GROUP="root", MODE="0777", OPTIONS="last_rule"

[root@physicalhost /]
#ll /dev/random
#crw-rw-rw- 1 root root 1, 8 Aug  8 11:40 /dev/random

```

restart containerB:

```
[root@physicalhost /home/ahao.mah]
#docker restart 1853437e8d2e
1853437e8d2e
```

both containerB's /dev/random and physicalhost's /dev/access is changed!

```
[root@containerB /]
#ll /dev/random
crw-rw---- 1 root root 1, 8 Aug  8 11:41 /dev/random

[root@physicalhost /home/ahao.mah]
#ll /dev/random
crwxrwxrwx 1 root root 1, 8 Aug  8 11:43 /dev/random
```

Q1:  why only use --priviledges container's /etc/udev/rules.d/xxx   is valid ?
Q2:  when I start use --priviledges , why container restart will modify phycalhost's /dev/xxx access and use physicalhost's  /etc/udev/rules.d/xxx  rules

**Describe the results you expected:**

My views:

1. I think this relate to systemd running in docker  priv
2. when running with --priviledges , systemd running in docker should not modify physicalhost's /dev/xxx access by /etc/udev/rules.d/xxx
3. when running with no --priviledges , systemd running in docker should can  modify container's /dev/xxx access by /etc/udev/rules.d/xxx
**Describe the results you received:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
#docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   eea9beb BUILDTIME:2017-04-28 11:20:04
 Built:        Fri Apr 28 03:19:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   eea9beb BUILDTIME:2017-04-28 11:20:04
 Built:        Fri Apr 28 03:19:33 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
#docker info
Containers: 43
 Running: 3
 Paused: 0
 Stopped: 40
Images: 15
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local tmpfs alilocal
 Network: host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
It looks like you're running a custom build of docker (I cannot find commit eea9beb in this repository), and you did not provide;

- What distro you're running on
- What is modified in your build?
- Any information about the image you're running (`reg.docker.xxxxx.com/mybase/centos7u2:latest`) - what's running in that container?

Also, docker 1.12.6 is outdated and no longer supported

> when running with --priviledges , systemd running in docker should not modify physicalhost's /dev/xxx access by /etc/udev/rules.d/xxx

When running with `--privileged`;

- various host-devices are writable inside the container; https://github.com/moby/moby/blob/v1.12.6/daemon/oci_linux.go#L84-L98 (list of devices; https://github.com/moby/moby/blob/v1.12.6/vendor/src/github.com/opencontainers/runc/libcontainer/devices/devices_unix.go#L64-L102)
- all capabilities are granted https://github.com/moby/moby/blob/v1.12.6/daemon/oci_linux.go#L219-L221
- https://github.com/moby/moby/blob/v1.12.6/daemon/oci_linux.go#L552-L563
- cgroups are writable https://github.com/moby/moby/blob/v1.12.6/daemon/oci_linux.go#L565-L573
- AppArmor is disabled https://github.com/moby/moby/blob/v1.12.6/daemon/oci_linux.go#L691-L693

Effectively, running with `--privileged`, disables all protection that containers provide, so, yes, it's possible modifications are made on the host

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by thaJeztah** [comment]
closing because this went stale
