### ISSUE TITLE
docker system prune triggers semaphore leaks in device mapper

### ISSUE THREAD

**Issue by jaloren** [moby/moby#34422]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

I have configured docker engine storage layer to be device mapper with a docker thin pool. To guard against large consumption of disk space, I run docker system prune in a cron at regular intervals. Within less then 24 hours, docker can no longer pull down images or create containers. 

While issue #33603 describes similar symptoms and the root cause may be the same, I have seen this leak happen in a matter of hours and my issue is the inability to create containers/pull images down -- not restart the service.

If i run the following command:
```
dmsetup udevcomplete_all
```

Then docker is able to pull down images and create containers again. 

**Steps to reproduce the issue:**
Perform the following on a centos 7.3 linux vm, where devmapper is the storage layer.

1. in one window, run the following in a watch. This will allow you to see the growth of semaphore arrays. 
`ipcs -s | tail -n +5 | wc -l`
2. create a docker compose file that starts and runs 10 containers. It doesn't matter what they do. I had each service simply run a bash with a sleep of 600 seconds.
3. create the following shell script and run it for 10 minutes:
```
while [ 1 -eq 1 ];do
   docker-compose up -d
   docker-compose down
   docker system prune -a --force
done
```

Note that if I modify the shell script like so, then I see no growth in the number of semaphores

```
while [ 1 -eq 1 ];do
   docker-compose up -d
   docker-compose down --rmi all --volumes --remove-orphans
   docker system prune -a --force
done
```

**Describe the results you received:**

When i run a docker run or a docker pull, the operations fail with the following error:

```
devicemapper: Can't set cookie dm_task_set_cookie failed"
```

**Describe the results you expected:**

docker pull and docker run should complete successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens every 12 hours or less. I was able to make the problem go away by no longer running docker system prune in an automated fashion via cron. In other words, when i run docker system prune, I ensure that no other docker operations are being run at the same time. This seems to indicate that system prune is not safe to run concurrently with other docker operations that affect the docker storage layer.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 854.6MB
 Data Space Total: 30.6GB
 Data Space Available: 29.74GB
 Metadata Space Used: 397.3kB
 Metadata Space Total: 318.8MB
 Metadata Space Available: 318.4MB
 Thin Pool Minimum Free Space: 3.06GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.671GiB
ID: RK6L:TK4Y:PV7W:OEPY:OB5J:MLKL:DDBR:LAIZ:UCNL:QHNF:BPLZ:RHCZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

docker is running in a VM within a vcenter hypervisor. I am running centos 7.3 in the vm. Here is uname output.
```
3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

docker-compose version
```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by thaJeztah** [comment]
ping @cpuguy83 @rhvgoyal @moypray  PTAL

**Comment by moypray** [comment]
@thaJeztah   It is a duplicate issue of https://github.com/moby/moby/issues/33603

But I don't find a good solution to solve it in docker or lvm2.

**Comment by jaloren** [comment]
@moypray, do you think is PR may fix the root problem:

docker/docker-ce#200

**Comment by moypray** [comment]
@jaloren  Yes, this PR is very helpful and necessary to this issue. And could fix most of the semaphore 
 leak.

But, maybe docker got OOMed or killed after `task.run` and before calling `udevwait()` , this is no solution against it.

This backport PR is fine, we need backport it.

**Comment by thaJeztah** [comment]
@jaloren is this still an issue for you on docker 17.06.2 (which contains the linked PR)?

**Comment by thaJeztah** [comment]
closing, as this one went stale, and probably is resolved
