### ISSUE TITLE
IIS sometimes fails to start in a container, error 0x80070020 (sharing violation)

### ISSUE THREAD

**Issue by sandersaares** [moby/moby#34420]
**Description**

Occasionally, IIS in the microsoft/aspnet:4.7-windowsservercore image fails to start serving a website. I realize this might just be a defect in the image but since Windows container networking is fairly fragile at the best of times, I suspect it is more of a Windows container networking issue.

**Steps to reproduce the issue:**

1. Start a container with the `microsoft/aspnet:4.7-windowsservercore` image. Provide a fixed IP address, e.g. `--ip 172.16.30.13`
2. Attempt to access port 80 of the container directly from the host, using the container's IP address.

**Describe the results you received:**

Around 1-10% of the time, the web server does not start and no connection to port 80 can be established.

**Describe the results you expected:**

The IIS default web page opens up every single time.

**Additional information you deem important (e.g. issue happens only occasionally):**

Also reproduces with `4.6.2-windowsservercore` tag.

The issue was found in automated tests that tear down and rebuild the same container often, on the same IP address.

The Application event log contains the following entry:

```
EventID            : 2269
MachineName        : 3f681bc9c1c0
Data               : {2, 0, 7, 128}
Index              : 56
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : The worker process for app pool 'DefaultAppPool', PID='1832', failed to initialize the http.sys communication when asked to start processing http requests and therefore will be considered ill by W3SVC and
                     terminated.  The data field contains the error number.
Source             : W3SVC-WP
ReplacementStrings : {DefaultAppPool, 1832}
InstanceId         : 3221227741
TimeGenerated      : 8/7/2017 1:10:29 PM
TimeWritten        : 8/7/2017 1:10:29 PM
UserName           :
Site               :
Container          :
```

From what I can tell, the error code in the Data field is 0x80070020, for which I found:

> The error code 0x80070020 translates to ERROR_SHARING_VIOLATION (The process cannot access the file because it is being used by another process.)
>
> This issue may occur if TCP port 80 and/or 443 is grabbed by a different service.

Though that does not seem to explain the behavior.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.65GiB
Name: Waldrop
ID: UOPJ:UN6T:234J:YUJ7:H74G:UN6P:UCQT:5H5U:HVNX:OQSI:FNDQ:7NLI
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduces both on physical Windows 10 and Azure VM with Windows 2016 (same Docker version used).

**Comment by thaJeztah** [comment]
ping @msabansal @friism PTAL

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
