### ISSUE TITLE
Extending subnet of overlay network without killing services?

### ISSUE THREAD

**Issue by SvenAbels** [moby/moby#34446]
**Description**
We created an overlay network in docker swarm mode:

```
docker network create \
  --driver overlay \
  web
```

This system is now in production with >100 services and we now got the problem that all new containers stay in the NEW state as we have been running out of VIPs. Using ```docker network inspect web``` I saw that 
```"Subnet": "10.0.0.0/24"``` inside the IPAM-Config part. I assume that this means that the network only has 255 IPs. Probably we should have used 
```
docker network create \
  --driver overlay \
  --subnet=10.0.0.0/16 \
  web
```

I assume that we could stop all services, delete the network and re-create it. However, now we already got all services running so we want to avoid this. **Can we somehow extend our network without stopping and restarting each service in the swarm manually?**

**Output of `docker version`:**

```
17.05
```

**Comment by sanimej** [comment]
@SvenAbels Assuming you don't have assumptions about the network name in the app, you can create a overlay network with a bigger subnet and do a `service update network-add` to attach the tasks to the new network followed by a `service update network-rm` to disconnect from the old network.

**Comment by SvenAbels** [comment]
@sanimej: That's good, thanks a lot for the tip. But is there no way to re-define the network without dastroying it and creating a new one?

**Comment by sanimej** [comment]
@SvenAbels Networks are immutable currently. There is no option to update the network's properties.
