### ISSUE TITLE
Windows daemons should report disk space

### ISSUE THREAD

**Issue by wsong** [moby/moby#34440]
**Description**

On Linux daemons, we can get the amount of disk space available in `/var/lib/docker` by either running `df -h` inside a container (I believe this is the case for overlay FS systems) or by running `docker info` (I believe this is the case for devicemapper). In Windows, however, disk space checks inside containers do not correspond to the host machine's disk space, and `docker info` does not contain any disk space info.

It'd be nice to add something like this for Windows so that we can get a node's disk usage through the Docker API.

**Comment by thaJeztah** [comment]
Actually; looks like a duplicate of https://github.com/moby/moby/issues/33703, please continue over there
