### ISSUE TITLE
quotactl(2) is not whitelisted when granting CAP_SYS_ADMIN using the default seccomp profile

### ISSUE THREAD

**Issue by pmoust** [moby/moby#34444]
`quotactl` syscall is not allowed even when granting `CAP_SYS_ADMIN` using the default seccomp profile.

**Steps to reproduce the issue:**
1. Run a container with xfstools with `CAP_SYS_ADMIN` and `CAP_SYS_PTRACE`
2. In the container `strace xfs_quota` trying to alter quotas in a project
3. repeat the above with SecurityOpt `"seccomp:unconfined"`

**Describe the results you received:**
Error calling `quotactl` initially whereas with `"seccomp:unconfined"` the command succeeds

**Describe the results you expected:**
Be allowed to call `quotactl` since `CAP_SYS_ADMIN` is granted.

**Comment by justincormack** [comment]
What is the use case for setting quotas in a container?

**Comment by pmoust** [comment]
We are managing a fleet VMs acting as docker hosts where we host stateful services and we enforce XFS quotas in a dynamic fashion.

One would expect granting `CAP_SYS_ADMIN` using to the worker that is handling the update of xfs quotas to also grant `quotacl` but it doesn't.

Checking the [documentation](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile) on what the default seccomp profile blocks and are in touch with `CAP_SYS_ADMIN` realm (like `mount`,`bpf`, `quotacl`, etc) it is mentioned that they are blocked by default, gated by `CAP_SYS_ADMIN`. This is true for other, but not for `quotacl`.

**Comment by justincormack** [comment]
ok seems reasonable (I don't think I intentionally left it off originally).
