### ISSUE TITLE
Feature Reqest: make default container and host names shorter

### ISSUE THREAD

**Issue by leonsoft** [moby/moby#34457]
**Description**
I'm not sure how default container names generated today. I think this is a hard but thankless job. I'd prefer to use simple short names such as h1, h2, or c1, c2 etc **by default** as it's easier to remember and type.

**Comment by yummypeng** [comment]
These names are combined with two words which randomly chosen from two arrays. If you think these names are too long to remember, you can use `--name` to specify a simple name you like.

For example:
```
# docker run -tid --name c1 ubuntu
95227e6695c8c20337ec41f62e3a7412be9dd5ab00f9d210a251d80a0a6d7066
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
95227e6695c8        ubuntu              "/bin/bash"         2 seconds ago       Up 1 second                             c1
```

**Comment by leonsoft** [comment]
I meant default name. Anyway, minor issue, not important.

**Comment by cpuguy83** [comment]
Note you can use partial matching against the ID so long as the result is non-ambiguous.

Closing.
