### ISSUE TITLE
how to use go test to run docker integration-cli test cases without gcc ?

### ISSUE THREAD

**Issue by lvfan21** [moby/moby#34456]
I have a test ENV that can't install yum, can't install gcc. When I running integration-cli  test cases, some err as following raised:
+ go test -check.f DockerSuite.TestApiClientVersionNewerThanServer -check.v -check.timeout=5m -timeout=360m github.com/docker/docker/integration-cli
**# runtime/cgo
exec: "gcc": executable file not found in $PATH**
FAIL	_/mnt/docker/integration-cli [build failed]

it was failed when using gcc to compile runtime/cgo, so can I skip this step and copy a complied cgo.a from another linux machine ? 
thanks!

**Comment by ripcurld0** [comment]
@lvfan21 can you explain again how did you build the image and how did you enter to the container?
I'm guessing you want to run docker inside a container, right?

**Comment by lvfan21** [comment]
@ripcurld0 I run docker not in a container but in a linux host. In my test, I didn't build any images, but copy .tar packages from another machine and then use command 'docker load --input *.tar' to generate images.

**Comment by ripcurld0** [comment]
Hey @lvfan21,

Can you elaborate more about what you're trying to do and from where or how you got that tar file?
I am not sure I understood the whole process.

Thanks 😀

**Comment by thaJeztah** [comment]
closing because this went stale
