### ISSUE TITLE
Untruncate invalid image names

### ISSUE THREAD

**Issue by 1605200517** [moby/moby#34467]
In this bug report I allow myself to omit the formalities because the bug appears to be very obvious.

- if there is invalid image to use for a stack service, docker stack ps would report:

No such image: xxxxx/yyyy...

However I consider that truncating the image name can be a big problem because for longer organization name part, you wouldn't see the actual image name. Is ist possible to configure or just take out the truncation? It does not go away even if --format is used to print *only* the Error column. (see attached screenshot)

![image](https://user-images.githubusercontent.com/1834666/29129463-25f49be4-7d27-11e7-93f0-0e0bd96c7d79.png)

**Comment by thaJeztah** [comment]
Try using the `--no-trunc` option;

```bash
$ docker stack ps --help

Usage:	docker stack ps [OPTIONS] STACK

List the tasks in the stack

Options:
  -f, --filter filter   Filter output based on conditions provided
      --format string   Pretty-print tasks using a Go template
      --help            Print usage
      --no-resolve      Do not map IDs to Names
      --no-trunc        Do not truncate output
  -q, --quiet           Only display task IDs
```

Example:

```bash
$ cat > docker-compose.yml <<EOF
version: "3"
services:
  foo:
    image: "nosuchimage-with-a-really-long-name-that-does-not-fit:really"
EOF

$ docker stack deploy -c docker-compose.yml repro-34467

$ docker stack ps --no-trunc repro-34467

ID                          NAME                    IMAGE                                                          NODE                DESIRED STATE       CURRENT STATE            ERROR                                                                           PORTS
hxmbjm1n6lglgusg6uucltxdo   repro-34467_foo.1       nosuchimage-with-a-really-long-name-that-does-not-fit:really   moby                Ready               Preparing 1 second ago
z5p6vr7mkm0qu1zefz76lqyig    \_ repro-34467_foo.1   nosuchimage-with-a-really-long-name-that-does-not-fit:really   moby                Shutdown            Rejected 1 second ago    "No such image: nosuchimage-with-a-really-long-name-that-does-not-fit:really"
```

**Comment by thaJeztah** [comment]
closing, because I don't think anything needs to be fixed, but feel free to continue the conversation

**Comment by 1605200517** [comment]
@thaJeztah  I really have to apologize for missing the --no-trunc option!

**Comment by thaJeztah** [comment]
No worries, glad it helped!
