### ISSUE TITLE
Cluster of 3 manager can't survive failure of 1 manager

### ISSUE THREAD

**Issue by sasavilic** [moby/moby#34466]
**Description**

We have a cluster of 4 nodes, from which 3 nodes are managers. 

I have noticed that under heavy load / too much memory usage, one of the managers gets unresponsive. But the real problem is that other two managers are not able to continue, although they 
should be. I was able to reproduce it by preventing communication of one node to other two nodes. On all three nodes, I get following error:

`Error response from daemon: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.`

It is understandable that I get this message on node that has communication severed from other nodes, but shouldn't other managers be able to continue? After all, they 2 are still majority.

**Steps to reproduce the issue:**
1. Make a cluster with 4 nodes
2. Out of 4 nodes, select 3 and make them managers
3. On one of the managers, go and disable communication to other two
```
$ ipset create blacklist hash:ip hashsize 4096
$ iptables -I INPUT -m set --match-set blacklist src -j DROP
$ iptables -I FORWARD -m set --match-set blacklist src -j DROP
$ docker node ls
$ ipset add blacklist $(dig +short node02)
$ ipset add blacklist $(dig +short node03)
```
4. Go on each manager and try few times `docker node ls`

**Describe the results you received:**
On all three nodes: `Error response from daemon: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.`

**Describe the results you expected:**
On two _healthy_ nodes, I expected something like
```
ID                            HOSTNAME                      STATUS              AVAILABILITY        MANAGER STATUS
2huw5xp6ga1c5k1o8us61pmzy     node04                        Ready               Active              
8e7bux0pkgqf8r0pbi6ego10m *   node03                        Ready               Active              Reachable
c1foj7ruz9i0ydr5b7hcciz68     node02                        Ready               Active              Leader
wmy8bqr0ujo8ruwjcirnmtx6s     node01                        Ready               Active              Unreachable
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 19
 Running: 4
 Paused: 0
 Stopped: 15
Images: 146
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 20.32GB
 Data Space Total: 59.4GB
 Data Space Available: 39.07GB
 Metadata Space Used: 15.87MB
 Metadata Space Total: 625MB
 Metadata Space Available: 609.1MB
 Thin Pool Minimum Free Space: 5.939GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 8e7bux0pkgqf8r0pbi6ego10m
 Is Manager: true
 ClusterID: eppe00x80cfpgu0q05sovv2rl
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.66.122.160
 Manager Addresses:
  10.66.122.158:2377
  10.66.122.159:2377
  10.66.122.159:2377
  10.66.122.160:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.25GiB
Name: <<Name removed>>
ID: TQBB:Q3KN:DERK:3IHM:NDUW:HB5D:ZD2R:5GYJ:HNML:H73P:I4JH:FG3E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 VMs running on Hyper-V.

**Comment by sasavilic** [comment]
I have noticed that one particular node is listed twice as manager. Demoting/promoting that node didn't help up get rid of duplicate entry. 

After rebuilding cluster, the problem is gone.

I am note sure how we got duplicate entry for manager there, but I can remember that we has once issue because we cloned VM without regenerating new docker.key. We removed nodes, regenerated new key and added back nodes, but it looks like that damage has already been done.

You can close this issue if you like.

**Comment by cpuguy83** [comment]
Thanks for following up.
Yes what you mentioned could cause duplicates, or also making a node leave and then re-join can also give a duplicate entry (this is intentional as it now has a new identity).
