### ISSUE TITLE
Cannot access exposed ports from container on same host 

### ISSUE THREAD

**Issue by cookandy** [moby/moby#34473]
**Description**

Exposed ports (`0.0.0.0`) are unreachable from docker containers on same machine.

**Steps to reproduce the issue:**
1. `docker run -it -p 5000:5000 busybox nc -lp 5000`
2. I can now use `nc` to confirm the connection works from some machine `nc <PUBLIC_IP> 5000`
3. However, trying to access the public interface from another container on the same machine does not work `docker run -it busybox nc <PUBLIC_IP> 5000`

**Describe the results you expected:**

nc should have connected on port 5000 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue; it looks like you didn't report the output of `docker info`, which contains information about the distro and kernel version you're running on.

Also note that docker 1.12.4 is EOL and no longer maintained; are you seeing the same issue on the current version of docker? (17.06 at time of writing)?

**Comment by cookandy** [comment]
@thaJeztah apologies for the missed information.  I just tried this issue again in docker `17.06` with the same results

**Docker version**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Docker info**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: docker-2gb-sfo1-01
ID: SC2B:CMY6:ZYOJ:ETQR:QCND:RYKJ:L5VB:3HZT:B3LN:6XII:TLP5:QMQD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by antoinetran** [comment]
I have this issue too. Swarm image 1.2.6 and docker-ce-17.06.0, CentOs 7.3. I know there are other issue that this duplicate but I couldn't find them anymore.

Workaround: create a firewall rule in INPUT for this port.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
