### ISSUE TITLE
`docker events --until` has confusing behavior

### ISSUE THREAD

**Issue by yummypeng** [moby/moby#34475]
This PR https://github.com/moby/moby/pull/13165 allows duration strings as `--since/--until`, but I can't find any example of `docker events --until`. From the help infomation of `docker events`, I suppose that `docker events --until 10m` will stream events for 10 minutes then stop streaming. But actually, it returns immediately without any output.

After diging into codes, I find that the duration will be subtracted from `time.Now()`, that is to say, docker waits for -10 minutes in this scenario, that's why it returns immediately without any output. Then I try `docker events --until -10m` and it works as what I expected.

Maybe it's intended behavior because @ahmetb has already answered this question in his PR:
![image](https://user-images.githubusercontent.com/20569488/29160624-902086b8-7de5-11e7-959b-4514b34075f0.png)

But I still think it's confusing, `until` means do something up to some time, right?

**Comment by ripcurld0** [comment]
@yummypeng the [docs](https://docs.docker.com/engine/reference/commandline/events/) has some [concrete examples](https://docs.docker.com/engine/reference/commandline/events/#filter-events-by-time) about using `since` but I guess we could mention some with `until`.

**Comment by ahmetb** [comment]
It's meant to be used together with `--since`. 

For example if you want to query events that occurred in the past 10 hours, and exclude the past hour:

    docker events --since 10h --until 1h
