### ISSUE TITLE
docker history --human=false does not impact CreatedAt

### ISSUE THREAD

**Issue by brimworks** [moby/moby#34489]
**Description**

Output of `docker history --human=false` changed which breaks anyone relying on the expected ISO8601 time format.

**Steps to reproduce the issue:**
1. Pull an image, for example: `docker pull alpine`
2. Run `docker history` with the `--human=false` flag as documented here:
   https://docs.docker.com/engine/reference/commandline/history/#description
   For example:
```
docker history -H=false --format='{{ json . }}' alpine | jq
{
  "Comment": "",
  "CreatedAt": "6 weeks",
  "CreatedBy": "/bin/sh -c #(nop)  CMD [\"/bin/sh\"]",
  "CreatedSince": "6 weeks ago",
  "ID": "7328f6f8b418",
  "Size": "0"
}
{
  "Comment": "",
  "CreatedAt": "6 weeks",
  "CreatedBy": "/bin/sh -c #(nop) ADD file:4583e12bf5caec4...",
  "CreatedSince": "6 weeks ago",
  "ID": "<missing>",
  "Size": "3965955"
}
```

**Describe the results you received:**

The CreatedAt field was a "human readable" relative time.

**Describe the results you expected:**

Expected CreatedAt to be in iso8601 time format.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker --version
Docker version 17.07.0-ce-rc2, build 36ce605
```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
 Log:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Init Binary:
containerd version:
runc version:
init version:
Kernel Version: 4.4.14-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9MiB
Name: minikube
ID: L5FQ:F2GI:4OAE:NHIG:VOPC:M3XK:2JGI:44YG:5KQU:YFEN:4J57:I73K
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2017-08-11T23:33:19.066842707Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

DOCKER_HOST is pointing at a minikube instance running an older version of docker, although this detail is not relevant since this issue happens when talking to a new version of docker engine too.

**Comment by ripcurld0** [comment]
Thanks so much @brimworks however this bug is related to [Docker CLI](https://github.com/docker/cli).
I am going to close this and open a new issue there.
🍻

**Comment by brimworks** [comment]
Thanks! I was unsure of where this bug should be filed.

**Comment by ripcurld0** [comment]
@brimworks 🥇  That's OK. I wasn't sure too as it wasn't obvious. 
Thank you so much for opening this issue, though.
