### ISSUE TITLE
Docker service inspect with go template - isset function not found

### ISSUE THREAD

**Issue by tomaszglinski** [moby/moby#34483]
Kind of continuation of the https://github.com/moby/moby/issues/24218:

I would like to list published ports, but the template needs to be resistent also to case when there is no port published at all. To do this, I need to check whether `"Ports"` section exists, and `isset `looks like the way to do this:

`docker service inspect -f '{{ if (isset .Spec.EndpointSpec "Ports") }}{{with index .Spec.EndpointSpec.Ports 0}}{{.PublishedPort}}{{end}}{{end}}' testservice`

But the result is:

> Status: Template parsing error: template: :1: function "isset" not defined, Code: 64

What's going on??

**Comment by lukahartwig** [comment]
Go does not have  a built-in `isset` function. But you could just do 
```
docker service inspect -f '{{ range .Spec.EndpointSpec.Ports }}{{ .PublishedPort }} {{ end }}' testservice
```
If `Ports` is empty `range` will just return nothing (see https://golang.org/pkg/text/template/#hdr-Actions).

**Comment by thaJeztah** [comment]
Yes, this doesn't look like a bug to me; perhaps sime examples should be added to the documentation.

Closing this, but feel free to continue the conversation

**Comment by tomaszglinski** [comment]
My bad, it works indeed. I must have confused commands. Sorry for trouble

**Comment by thaJeztah** [comment]
No worries, glad you got it working!
