### ISSUE TITLE
Do you have support to pass arguments to Shell Script through docker run

### ISSUE THREAD

**Issue by bailantaotao** [moby/moby#34480]
I can do the following thing in docker 

with script in file.sh
```
#!/bin/bash
echo Your container args are: "$@"
```

and this Dockerfile
```
FROM ubuntu:14.04
COPY ./file.sh /
ENTRYPOINT ["/file.sh"]
```

now, i can pass arguments to shell script:
```
% docker build -t test .
% docker run test hello world
Your container args are: hello world
```

but how i to do in `moby API` ?

I cannot find any way to pass arguments(like hello world) in `container.HostConfig` .
or May be i missing something?

**Comment by kinghuang** [comment]
What's being called "arguments" here is actually the command. API-wise, it's specified in `.Cmd`. It's not part of `.HostConfig`.

**Comment by bailantaotao** [comment]
@kinghuang Thanks, the problem can be solved by `.Cmd`
