### ISSUE TITLE
Migrate integration-cli-on-swarm to integration-on-swarm

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#34491]
Currently, `integration-cli-on-swarm` does not execute non-CLI tests under the `integration` directory.

No need to hurry, as the `integration` directory contains only a few tests ATM.

Tasks:
- s/integration-cli-on-swarm/integration-on-swarm/
- hack/integration-on-swarm/host: Enumerate tests under the `integration` directory
- hack/integration-on-swarm/agent/worker: Support tests that are not `go-check` suites

#dibs

**Comment by thaJeztah** [comment]
I guess this one can be closed now that integration-cli-on-swarm was removed in https://github.com/moby/moby/pull/39294
