### ISSUE TITLE
Example on how to pull an image specifying RegistryAuth

### ISSUE THREAD

**Issue by thalesfsp** [moby/moby#34503]
### Problem

Pull an image from a private repo using the Golang SDK and specifying RegistryAuth.

More info:

Using: Golang SDK
Function: `.ImagePull()`
Repository Type: private
Repository Host: `private.repo.io:4567` // address scrumbled
Image: `private.repo.io:4567/companyName/consul:testing` // name scrumbled
Docker CLI: working properly
Have spent time on Google, SO, and etc? Yes

Trying this:

```
// Copied from source code
func basicAuth(username, password string) string {
  auth := username + ":" + password
  return base64.StdEncoding.EncodeToString([]byte(auth))
}

func main() {
  _, err := dockerEngine.ImagePull(context.Background(), "private.repo.io:4567/companyName/consul:testing", types.ImagePullOptions{
    RegistryAuth: "Basic " + basicAuth("usernameHere", "personalToken"), // user has 2AF enabled
  })

  if err != nil {
    log.Fatal(err)
  }
}
```

and I get this:

```
Error response from daemon: Get https://private.repo.io:4567/v2/companyName/consul/manifests/testing: denied: access forbidden
exit status 1
```

CLI is perfect working - using the same credentials - so docker `pull private.repo.io:4567/companyName/consul:testing` just works.

### the output of `docker version`

```
$docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### the output of `docker info`

```
$docker info
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: RCFD:KBH7:X7QQ:PSLI:6R46:OGCZ:6LEN:H53W:YANR:NOLB:2IEK:7CMW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 37
 System Time: 2017-08-14T16:25:18.799602529Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### the output of `~/.docker/config.json`

```
$cat ~/.docker/config.json
{
  "auths" : {
    "https://private.repo.io:4567" : {

    },
    "private.repo.io:4567" : {

    }
  },
  "credsStore" : "osxkeychain"
}
```

Thanks!

**Comment by ripcurld0** [comment]
@thalesfsp can you explain what is the problem? is it related to the docs?

**Comment by thalesfsp** [comment]
@ripcurld0 Thanks for your fast response, incredible! I'm just trying it:

```
func basicAuth(username, password string) string {
	auth := username + ":" + password
	return base64.StdEncoding.EncodeToString([]byte(auth))
}

_, err := dockerEngine.ImagePull(ctx, "private.repo.io:4567/companyName/consul:testing", types.ImagePullOptions{
		RegistryAuth: "Basic " + basicAuth("usernameHere", "personalToken"), // user has 2AF enabled
	})

	if err != nil {
		log.Fatal(err)
	}
```

and I get:

```
Error response from daemon: Get https://private.repo.io:4567/v2/companyName/consul/manifests/testing: denied: access forbidden
exit status 1
```

**Comment by ripcurld0** [comment]
Reading the comment
https://github.com/moby/moby/blob/07227a1227e1cdecdd89060d98bf67d0f49503e6/api/types/client.go#L227-L232

> RegistryAuth is the base64 encoded credentials for the registry
Which means `Basic` should not be included.

Let me know if it worked.

**Comment by AkihiroSuda** [comment]
See https://github.com/docker/cli/pull/227

**Comment by thalesfsp** [comment]
@ripcurld0 @AkihiroSuda Removed `"Basic "`, still not working. Thanks!

**Comment by thalesfsp** [comment]
@ripcurld0 @AkihiroSuda Removed `"Basic "`, still not working. Thanks!

**Comment by hasufell** [comment]
Same here. Either the function is broken or the documentation is wrong.

**Comment by aengelas** [comment]
I'm still unable to make this work with an ECR registry from AWS. Clear documentation is definitely needed.

**Comment by robmccoll** [comment]
This is a little crazy. To clarify @hasufell 's comment, this is what worked for me today:
```
jsonBytes, _ := json.Marshal(map[string]string{
   "username":  "my username goes here",
   "password": "my password goes here"
})

opts := &types.ImagePullOptions{
   RegistryAuth: base64.StdEncoding.EncodeToString(jsonBytes)
}
```

**Comment by zbysir** [comment]
> This is a little crazy. To clarify @hasufell 's comment, this is what worked for me today:
> 
> ```go
> jsonBytes, _ := json.Marshal(map[string]string{
>    "username":  "my username goes here",
>    "password": "my password goes here"
> })
> 
> opts := &types.ImagePullOptions{
>    RegistryAuth: base64.StdEncoding.EncodeToString(jsonBytes)
> }
> ```

It's clarify and worked. Thx.

**Comment by sahana-tm** [comment]
> I'm still unable to make this work with an ECR registry from AWS. Clear documentation is definitely needed.

Even i am not able to pull image from  AWS ECR , Can anyone tell me how to solve authentication issue in GO lang?

**Comment by avinashnarra** [comment]
even i am also not able to pull from ecr

**Comment by sagia-inneractive** [comment]
The following snippet seems to work using aws sdk and docker sdk for ecr logins - 
```	
        token := *tokenRequest.AuthorizationData[0].AuthorizationToken //token from ecr.GetAuthorizationToken
	parsedToken, e := base64.StdEncoding.DecodeString(token)
	if e != nil {
		panic(e)
	}	
	parts := strings.Split(parsedToken, ":")
	authConfig := types.AuthConfig{
		Username: parts[0],
		Password: parts[1],
	}
	encodedJSON, err := json.Marshal(authConfig)
	if err != nil {
		panic(err)
	}
	authStr := base64.URLEncoding.EncodeToString(encodedJSON)
```

**Comment by jacquayj** [comment]
> The following snippet seems to work using aws sdk and docker sdk for ecr logins -
> 
> ```
>         token := *tokenRequest.AuthorizationData[0].AuthorizationToken //token from ecr.GetAuthorizationToken
> 	parsedToken, e := base64.StdEncoding.DecodeString(token)
> 	if e != nil {
> 		panic(e)
> 	}	
> 	parts := strings.Split(parsedToken, ":")
> 	authConfig := types.AuthConfig{
> 		Username: parts[0],
> 		Password: parts[1],
> 	}
> 	encodedJSON, err := json.Marshal(authConfig)
> 	if err != nil {
> 		panic(err)
> 	}
> 	authStr := base64.URLEncoding.EncodeToString(encodedJSON)
> ```

Thanks for this snippet @sagia-inneractive, you rock!
