### ISSUE TITLE
dockerd seems stuck in un-initialized state; docker cannot communicate with dockerd

### ISSUE THREAD

**Issue by jacoba51** [moby/moby#34505]
**Description**
I am trying to integrate docker in a custom-installed CentOS7.3.
I installed docker-ce-17.06.0.ce and it's dependent packages on my system.
When I try to start docker with 'systemctl start docker', the command does not return,
and I see the following is ps:

```
admin     2046  1900  0 16:29 pts/0    S+     0:00  |   |       \_ systemctl start docker
admin     2047  2046  0 16:29 pts/0    S+     0:00  |   |           \_ /usr/bin/systemd-tty-ask-password-agent --watch
admin     2048  2046  0 16:29 pts/0    Z+     0:00  |   |           \_ [systemctl] <defunct>
```

and I see that dockerd and docker-containerd are running.

However any docker command, like 'docker info' is stuck.
Strace shows that the command is waiting on a futex.

When I run dockerd in debug mode I see the following:

```
DEBU[0000] Warning: could not change group /var/run/docker.sock to docker: Group docker not found 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] libcontainerd: new containerd process, pid: 3557 
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=2 memory=3770 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 27090          
DEBU[0001] [zfs] zfs command is not available: exec: "zfs": executable file not found in $PATH 
DEBU[0001] devicemapper: driver version is 4.33.0       
DEBU[0001] devmapper: Generated prefix: docker-8:9-344162 
DEBU[0001] devmapper: Checking for existence of the pool docker-8:9-344162-pool 
DEBU[0001] devmapper: Pool doesn't exist. Creating it.  
DEBU[0001] devmapper: Creating loopback file /var/lib/docker/devicemapper/devicemapper/data for device-manage use 
DEBU[0001] devmapper: Creating loopback file /var/lib/docker/devicemapper/devicemapper/metadata for device-manage use 
DEBU[0003] libcontainerd: containerd connection state change: READY 
```

The only suspicious hint is from this kernel message:

```
device-mapper: thin: Data device (loop0) discard unsupported: Disabling discard passdown. 
```

Any leads on how to debug this will be highly appreciated

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical
kernel 3.10.0-327.36.3

**Comment by ripcurld0** [comment]
@jacoba51 can you please copy paste the full output of `docker version` and `docker info`?

Thanks.

**Comment by jacoba51** [comment]
The version is indicated above. The command 'docker info' does not return ...

**Comment by jacoba51** [comment]
Apparently my custom installation has some essential device-mapper files missing.
Now its working.

**Comment by trenner02** [comment]
@jacoba51 You don't happen to remember which files those were that were missing, do you?  I'm running into the exact same problem...

**Comment by jacoba51** [comment]
It was either from the package device-mapper or device-mapper-lib, I can't remember which.
Check the content of these packages on www.rpmfind.net and see if any file is missing from your installation.
