### ISSUE TITLE
Cannot locate specified Dockerfile when filename contains dot

### ISSUE THREAD

**Issue by whitecolor** [moby/moby#34519]
If Dockerfile file contains dot in a name build fails with `Error response from daemon: Cannot locate specified Dockerfile`

```
--> docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

![image](https://user-images.githubusercontent.com/736697/29315903-13ecfc72-81df-11e7-883c-7484274b50e4.png)

Both files are in place:
![image](https://user-images.githubusercontent.com/736697/29315911-1d371bb4-81df-11e7-8a36-6a4dfda62d2b.png)

**Comment by cpuguy83** [comment]
Do you have permissions on the dotted file?

I can't reproduce. We use files with dots in them in this repo for each architecture with no problem.

**Comment by whitecolor** [comment]
Ah I forgot to close the issue. There was a problem with .dokerignore file.
