### ISSUE TITLE
[DOC] Logs' API protocol

### ISSUE THREAD

**Issue by nathan-K-** [moby/moby#34517]
Hi !

I'm writing a tool (in Python) to get the logs from any containers through the Docker Engine's HTTP API.

After reading [the doc](https://docs.docker.com/engine/api/v1.30/), and trying to implement something, I founded that the protocol used seems to be different from the one for Attach, it seems to be :

```{\xFF}\r\n{\xFF}{datas}```

Where the first hex number is the size of the message, and the second one seems to be (empirical deduction) the number of bytes that are supposed to be ignored before the start of the actual payload (so the log).
And it seems to work, for some containers at least ...

**EDIT** : The second seems to be the number of bytes that are supposed to be ignored IF the container has ```tty: false```, otherwise, it seems to be the start of the log **END of the edit**

With one strange deduction : if ```\x07``` is found, then it overrides the second {\xFF} size, and the message starts after this value...

Am I missing a part of the documentation, or am I not using the HTTP API in a wrong way ?

Thanks for your time,

**NB** : The protocol above seems to be specific for the logs endpoint, it's not working for the events' endpoint.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ripcurld0** [comment]
@nathan-K- can you copy-paste `docker inspect <container-name>` here? I think it's because `tty` is set to false on that container.

**Comment by nathan-K-** [comment]
Well, it was working on my consul container, which has ```tty: false```, here is the output of ```docker inspect``` :

(To be honest, my issue was more about the protocol used)

```
[
    {
        "Id": "4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934",
        "Created": "2017-08-15T07:32:48.004174435Z",
        "Path": "/bin/start",
        "Args": [
            "-server",
            "-bootstrap",
            "-ui-dir",
            "/ui"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 12647,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-08-15T07:32:48.402043096Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:09ea64205e553163a9d7790c9688cff73e3dc2439a8382021a2b2223545f01ff",
        "ResolvConfPath": "/var/lib/docker/containers/4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934/hostname",
        "HostsPath": "/var/lib/docker/containers/4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934/hosts",
        "LogPath": "/var/lib/docker/containers/4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934/4c5c80bf8f277629076609c341f4c10b8440698eb61116061f6491a3c6fa5934-json.log",
        "Name": "/kind_hopper",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "53/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "8600"
                    }
                ],
                "8400/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8400"
                    }
                ],
                "8500/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8500"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "437622974b4e76b4d01ac52af1c352562087677766ea1354637af965859141cf",
                "Source": "/var/lib/docker/volumes/437622974b4e76b4d01ac52af1c352562087677766ea1354637af965859141cf/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "node1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {},
                "8300/tcp": {},
                "8301/tcp": {},
                "8301/udp": {},
                "8302/tcp": {},
                "8302/udp": {},
                "8400/tcp": {},
                "8500/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SHELL=/bin/bash"
            ],
            "Cmd": [
                "-server",
                "-bootstrap",
                "-ui-dir",
                "/ui"
            ],
            "Image": "progrium/consul",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/start"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b96a61e121028470ff6be2451998dae585932115c910429d64004977885443a4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "53/tcp": null,
                "53/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8600"
                    }
                ],
                "8300/tcp": null,
                "8301/tcp": null,
                "8301/udp": null,
                "8302/tcp": null,
                "8302/udp": null,
                "8400/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8400"
                    }
                ],
                "8500/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8500"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b96a61e12102",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "a07e26630d56ca185755eef3953fbc6a273b2ef08898950a9c1fd9df1a8b7f30",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "630f0355969716a8a5ae6251a3b4ed3b126c9622b01fb908083f47e1db3d08bf",
                    "EndpointID": "a07e26630d56ca185755eef3953fbc6a273b2ef08898950a9c1fd9df1a8b7f30",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

```

**Comment by thaJeztah** [comment]
Looks like there's currently an issue with the API docs on docs.docker.com, but the description of the [stream format in the exec endpoint]( https://github.com/moby/moby/blob/7120976d74195a60334c688a061270a4d95f9aeb/api/swagger.yaml#L4342-L4374) should match what the logs endpoint returns. There is a difference between containers running with, or without a TTY though (in case of a TTY attached, the stream is a raw stream from the container);

> ### Stream format
> 
> 
> When the TTY setting is disabled in [`POST
> /containers/create`](#operation/ContainerCreate), the stream over the hijacked
> connected is multiplexed to separate out `stdout` and `stderr`. The stream
> consists of a series of frames, each containing a header and a payload.
> 
> The header contains the information which the stream writes (`stdout` or
> `stderr`). It also contains the size of the associated frame encoded in the
> last four bytes (`uint32`).
> 
> It is encoded on the first eight bytes like this:
> 
> 
> ```go
> header := [8]byte{STREAM_TYPE, 0, 0, 0, SIZE1, SIZE2, SIZE3, SIZE4}
> ```
> 
> 
> `STREAM_TYPE` can be:
> 
> 
> - 0: `stdin` (is written on `stdout`)
> - 1: `stdout`
> - 2: `stderr`
> 
> 
> `SIZE1, SIZE2, SIZE3, SIZE4` are the four bytes of the `uint32` size encoded as
> big endian.
> 
> 
> Following the header is the payload, which is the specified number of bytes of
> `STREAM_TYPE`.
> 
> 
> The simplest way to implement this protocol is the following:
> 
> 
> 1. Read 8 bytes.
> 2. Choose `stdout` or `stderr` depending on the first byte.
> 3. Extract the frame size from the last four bytes.
> 4. Read the extracted size and output it on the correct output.
> 5. Goto 1.
> 
> 
> ### Stream format when using a TTY
> 
> 
> When the TTY setting is enabled in [`POST
> /containers/create`](#operation/ContainerCreate), the stream is not
> multiplexed. The data exchanged over the hijacked connection is simply the raw
> data from the process PTY and client's `stdin`.

**Comment by nathan-K-** [comment]
Yes,
Now I got it, something is missing : (I'm talking about ```logs```, didn't check for the others)
Before the header, there is a size in hex, and ```\r\n```, (eg ```7c\r\n```), it is useful when there is ```tty:true```, as in this case there is no header.
But it's also here when ```tty: false```, which is consistent, but because of that, the first 8 bytes are not the full header.

some examples, with the same container (consul) :
## Tty : false
```4f\r\n\x01\x00\x00\x00\x00\x00\x00G    2017/08/10 07:35:38 [INFO] serf: EventMemberJoin: node1 172.17.0.2\n```
Here we have the 8 bytes header : ```\x01 \x00 \x00 \x00 \x00 \x00 \x00 G``` after a ```4f\r\n```

### Tty : true
```4c\r\n    2017/08/15 12:05:33 [INFO] serf: EventMemberJoin: node1.dc1 172.17.0.2\r\n\r\n```
There is no header here.

Btw, it appears that sometimes, a few bytes are missing from the beginning of the logs, for example I've founded this from time to time :
```ll now stream in as it occurs:\n\r\n9```
which very probable come from : ```==> Log data will now stream in as it occurs:``` (also from Consul)

**Comment by thaJeztah** [comment]
Ah, yes; what you're seeing is due to "Chunked Encoding"; here's a nice [answer on StackOverflow](https://stackoverflow.com/a/4930152/1811501); 

> With chunked encoding there will be no Content-Length header. So after you've read the headers and the pair of CRLFs that mark the end of the headers, you're ready to read the first chunk. Each chunk payload is preceded by its own mini-header - the length in hex followed by CRLF. And there's another CRLF after the payload, before the next chunk's mini-header. A chunk can also be followed by some optional trailers. The end of the message is indicated by a zero-length chunk.

You can find the definitive details in the HTTP RFC, [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6.1).

**Comment by nathan-K-** [comment]
Maybe it could be a good time saver to put a word on it in the doc ;) (I guess if someone will use the API at this level, he might go through this)

**Comment by thaJeztah** [comment]
Yes, I agree it should be mentioned for those endpoints that use chunked encoding (although it's not really part of the API, in that any HTTP client should automatically handle chunked encoding, so wondering why that doesn't work in your case). Looks like this is a limitation of wsgi; https://github.com/pallets/flask/issues/367 ?


I'm working on improvements in the API docs, and can add a mention after https://github.com/moby/moby/pull/34485 is merged. I see the old markdown docs mentioned the "chunked" header at least; https://github.com/moby/moby/blame/ff4f700f74450018f36d014f3cde0ff1b9c17fb3/docs/api/v1.24.md#L2488 which is not documented in the Swagger specs

**Comment by nathan-K-** [comment]
That's because I'm using a "raw" socket on the upgraded connection, so without any HTTP client doing the work,

Anyways, I guess this issue can be closed :)

**Comment by nathan-K-** [comment]
Well, maybe the self-assignement won't work if it is closed ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
