### ISSUE TITLE
docker api explorer broken with 502

### ISSUE THREAD

**Issue by seriousben** [moby/moby#34525]
**Description**
https://docs.docker.com/engine/api/v1.30/ returns a 502 right now.

<img width="876" alt="screen shot 2017-08-15 at 12 29 42 pm" src="https://user-images.githubusercontent.com/6145422/29325480-d4e36a94-81b5-11e7-8637-377b44ce8842.png">

**Comment by thaJeztah** [comment]
I think there was an issue with some of the servers; looks to be working again now, so closing

If you see this again; please report in the issue tracker for the documentation;

https://github.com/docker/docker.github.io

**Comment by seriousben** [comment]
Thanks opened https://github.com/docker/docker.github.io/issues/4203 - I still see the problem which is a bit strange.

**Comment by thaJeztah** [comment]
Thanks! I know they're looking into it, but don't know what the current status is :smile:
