### ISSUE TITLE
Add --init options to `service create` 

### ISSUE THREAD

**Issue by denverdino** [moby/moby#34529]
Add optional init flag to `service create` for init feature since Docker v1.13

The PR in Swarmkit is docker/swarmkit#2350

Related to  moby/moby#25303

**Comment by thaJeztah** [comment]
Looks like  was vendored in this repository; https://github.com/moby/moby/blob/3b8d36d0646137c4315cfa12df0dcd49b584d22a/vendor/github.com/docker/swarmkit/api/specs.proto#L297-L300

**Comment by thaJeztah** [comment]
Implemented through https://github.com/docker/cli/pull/479, https://github.com/docker/cli/pull/1129, which are part of Docker 18.06 and up
