### ISSUE TITLE
SwarmKit has "lost" a node

### ISSUE THREAD

**Issue by omg-a-bear** [moby/moby#34521]
I'm having some troubles with one of my docker swarm clusters, where it seems like I have lost one of my worker nodes. The swarm contains three master nodes, and two additional worker nodes. The worker node in question reports as "Reachable" but as soon a service is deployed at this machine, it's unreachable from other parts of the network - as long as I don't explicitly asks via worker node IP + service port. It seems like the routing mesh can't find the service in question (or any other service deployed to the same machine).

The problem is not reproducible though, I have two identical clusters (one for test and one for production) and the test cluster works as expected.

At the moment I'm draining the specific node, to stop services from being deployed to the machine. I have removed the node from the cluster and joined it again, to no avail. The problem persists.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Unreachable worker node.

**Describe the results you expected:**
Reachable worker node.

**Additional information you deem important (e.g. issue happens only occasionally):**
The docker log is full of messages like `Aug 15 11:34:28.663441 worker-1 dockerd[1200]: time="2017-08-15T11:34:28.663249980Z" level=error msg="Failed to join memberlist [10.0.1.12] on retry: 1 error(s) occurred:\n\n* Failed to join 10.0.1.12: EOF"`

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 34
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: izouvsaviwgmk3lbfrh9cb97n
 Is Manager: false
 Node Address: 10.0.1.28
 Manager Addresses:
  10.0.1.11:2377
  10.0.1.12:2377
  10.0.1.21:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804GiB
Name: worker-1
ID: SFNT:2XSK:RKZK:KSAI:2IXM:G6YT:VN3A:NSHO:4UD5:T2UK:LLAC:YAFN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The cluster(s) are running on Azure, but not through ACS but on separate virtual machines.

**Comment by cpuguy83** [comment]
Do you have some details on the service which is being deployed that's causing it to bust?
Also the use of `10.0.x.x` for node IP's seems a possible culprit since the overlay network defaults to 10.x.x.x subnets.

**Comment by thaJeztah** [comment]
closing because no more information was provided
