### ISSUE TITLE
Docker on Windows 2016 -- 'Container Enable ICC' firewall rule not working

### ISSUE THREAD

**Issue by drnybble** [moby/moby#34526]
**Description**

When a container is created on the default nat network a firewall rule is created:

  Container Enable ICC - 43a34e0b-f72f-4dfe-92c3-abce316f2cc0

The rule doesn't seem to work. My container cannot connect to a port bound to the gateway IP (i.e., a process running on the host bound to 0.0.0.0).

**Steps to reproduce the issue:**
1. Create a container that tries to connect to a port on the host that is bound to the gateway IP

**Describe the results you received:**
Fails to connect-- if you have firewall logging turned on you can see the packet is dropped:
2017-08-15 11:34:12 DROP TCP 192.168.106.36 192.168.96.1 49206 12354 48 S 2951853498 0 8192 - - - RECEIVE

**Describe the results you expected:**
Container is able to connect to a port bound to the gateway IP.

**Additional information you deem important (e.g. issue happens only occasionally):**
Something is wrong with this firewall rule.
If I edit the rule, go to the "Scope" tab, toggle the "Remote IP address" setting to "Any IP address" and then back to "These IP addresses" (i.e., I have changed **nothing**) and click OK it will now work.
Alternatively, just create an identical firewall rule to the one automatically created and it will work.

**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      17.03.2-ee-5
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.2-ee-5
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      17.03.2-ee-5
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.2-ee-5
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Users\Administrator> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 17.03.2-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1593.amd64fre.rs1_release.170731-1934)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: WIN-SE6QQLDMG76
ID: EBEH:OYT4:6URO:5GBQ:2R2U:YWZK:BQJU:GKAE:PZLP:SR26:7ULT:4WDM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Freshly installed Server 2016, latest updates applied, VM running under VirtualBox.

**Comment by drnybble** [comment]
FYI a colleague independently confirmed this behaviour -- you edit the Container ICC firewall rule, make it "dirty" by toggling something and click OK -- rule now permits traffic to the gateway IP.

**Comment by thaJeztah** [comment]
ping @johnstep @friism @msabansal PTAL

**Comment by msabansal** [comment]
@drnybble  For talking to gateway we need to unblocks ports on that interface. ICC was only supposed to work for inter container communication.

**Comment by msabansal** [comment]
ping @JMesser81

**Comment by thaJeztah** [comment]
>  ICC was only supposed to work for inter container communication.

that's correct yes; `--icc=false` only blocks container-container traffic on the default bridge network on Linux. Containers can still access any port that's published (as publishing makes ports public), even if `--icc=false`.

Also, when using a custom network (`docker network create foo`), and containers are attached to such a network, `--icc` does not affect those; when using custom networks, attaching or detaching containers to a network determines if containers are allowed to communicate.

(I'm not too familiar with the Windows network stack, so just adding the above to verify if the behaviour is the same on Windows 😅 )

**Comment by drnybble** [comment]
OK so maybe the rule is working as expected. Below are the firewall rule definitions. The one automatically created by Docker includes an "IF={....}" property. This is lost if the rule is updated in any way in the Properties pane. I am guessing that the firewall rule is working as intended but that the Windows Firewall UI doesn't preserve the IF property. 

So the conclusion is that access to the gateway IP must be explicitly opened on the firewall, and don't edit these firewall rules in any way or they might change in undesirable ways!

Before clicking "Apply" in Properties pane:
v2.24|Action=Allow|Active=TRUE|Dir=In|RA4=172.28.224.0/255.255.240.0|IF={5BAE0AFC-184F-434E-8638-F419D5CED945}|Name=Container Enable ICC - 4cce4302-3f6c-4974-8d38-ef0004b66a1f|Desc=Container Enable ICC - 4cce4302-3f6c-4974-8d38-ef0004b66a1f|

After clicking "Apply" in Properties pane:
v2.26|Action=Allow|Active=TRUE|Dir=In|RA4=172.28.224.0/255.255.240.0|Name=Container Enable ICC - 4cce4302-3f6c-4974-8d38-ef0004b66a1f|Desc=Container Enable ICC - 4cce4302-3f6c-4974-8d38-ef0004b66a1f|
