### ISSUE TITLE
logspout giving access logs to graylog but not application logs 

### ISSUE THREAD

**Issue by lalitprasanth** [moby/moby#34537]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
I'm just going to close this.
If you want to post more details we can re-open.

Please fill out the entire issue template.
As it is I have no idea how/why this relates to docker/moby, or even what issue you are actually having.
