### ISSUE TITLE
After removing managed volume plugin and reinstalling it dockerd still picks the earlier plugin's socket

### ISSUE THREAD

**Issue by govint** [moby/moby#34545]
I'm testing with different versions of a managed volume plugin and seeing the below issue.
1. Install plugin via docker plugin install <volume plugin name>
1. Create a volume using this volume plugin
1. Run a container using this volume
1. Run docker plugin rm -f <plugin id>
1. Stop container
1. Try running the container with the same volume and it reports error as expected.
1. Re-install the same volume plugin (repeat step 1).
1. Again try running the container with the same volume
1. Docker reports a "no such file or directory for the socket" and interestingly is listing the ID of the plugin the first time it was installed.

**Steps to reproduce the issue:**
1.docker run -it --rm -v upvol1:/mnt busybox
2.docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
99802ba70b7b        XYZ:latest    XYZ    true

3.docker plugin rm -f 99802ba70b7b
99802ba70b7b

4. docker run -it --rm -v upvol1:/mnt busybox
docker: Error response from daemon: create upvol1: found reference to volume 'upvol1' in driver 'XYZ:latest', but got an error while checking the driver: error while checking if volume "upvol1" exists in driver "XYZ:latest": Error looking up volume plugin XYZ:latest: legacy plugin: plugin not found: volume name must be unique.

5. docker plugin install --grant-all-permissions --alias XYZ   XYZ:latest (reinstall the plugin)

6. docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
dc56520225a4        XYZ:latest    XYZ   true

7. ls -l /run/docker/plugins/dc56520225a4123f5127817479cdb5eebf1c7af8a55639ff545d5e1ce7db5866/
total 0
srw-rw---- 1 root root 0 Aug 17 08:08 XYZ.sock

8. docker run -it --rm -v upvol1:/mnt busybox
docker: Error response from daemon: error while mounting volume '/vol/docker/plugins/99802ba70b7b318fcb473faf442a910d0bca841488d4f73eb8ed49397e02ad05/rootfs': Post http://%2Frun%2Fdocker%2Fplugins%2F99802ba70b7b318fcb473faf442a910d0bca841488d4f73eb8ed49397e02ad05%2FXYZ.sock/VolumeDriver.Mount: dial unix /run/docker/plugins/99802ba70b7b318fcb473faf442a910d0bca841488d4f73eb8ed49397e02ad05/XYZ.sock: connect: no such file or directory.

In step 8 docker is reportedly using the plugin dir that corresponds to the ID of the same plugin the first time it was installed (and removed).  Step 7 clearly shows the path where the plugin has created the socket its listening on, the second time it was installed.

**Describe the results you received:**

Docker daemon seems to be keeping the plugin reference from the earlier instance (removed) of the plugin.

**Describe the results you expected:**

All details of the earlier instance of the plugin should have been removed. But looks like the daemon is somehow keeping the plugin ref. even after removal

**Additional information you deem important (e.g. issue happens only occasionally):**

Doesn't always happen but once it does it repeats till docker daemon is restarted

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.1
 Git commit:   092cba3
 Built:        Fri May  5 02:08:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   092cba3
 Built:        Fri May  5 02:08:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: 949e6fa
Kernel Version: 4.4.41-1.ph1-esx
Operating System: Photon/Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: photon-machine
ID: 2Q5G:SA3X:ZREW:SPWJ:NLSY:4I66:RZEE:D7CP:XNEX:4UUA:WAJC:T3XS
Docker Root Dir: /vol/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
This is expected behavior. Volumes are tied to the plugin ID, not the name.
If you want to change the version of a plugin you should use `docker plugin upgrade`.

**Comment by govint** [comment]
@cpuguy83 , does this apply even when the plugin is removed (docker plugin rm) and a new version installed. Is docker restart the only way to get the volume usable.

**Comment by cpuguy83** [comment]
@govint When the plugin is removed the resources referencing it will be essentially abandoned since the ID will no longer exist. If this works on a daemon restart I'd be a little surprised, though maybe the functionality changed a bit after the 1.13 release.

**Comment by thaJeztah** [comment]
@cpuguy83 looks like this issue is resolved; would this need an update to the documentation?

**Comment by shuklanirdesh82** [comment]
We are observing this issue with docker 17.06, please refere https://github.com/vmware/docker-volume-vsphere/issues/1984 for more information.

As mentioned in https://github.com/moby/moby/issues/34545#issuecomment-323072605, we have tried using `docker plugin upgrade` and outcome is the same (see https://github.com/vmware/docker-volume-vsphere/issues/1984#issuecomment-344065961 for the docker logs)

can you please tell by when will this fix be available?

/CC @govint @bteichner

**Comment by cpuguy83** [comment]
@shuklanirdesh82 I don't follow how `docker plugin upgrade` has anything to do with it. The logs seem to indicate that there was an error when bringing the plugin back up.

`docker plugin upgrade` does not change the ID of the plugin.

**Comment by cpuguy83** [comment]
I'm going to close this for housekeeping as `docker plugin upgrade` is meant to deal with this particular issue, but feel free to discuss. Thanks! 👼 🙇

**Comment by govint** [comment]
@shuklanirdesh82 can you post the logs that show the failure when using _docker plugin upgrade_. To be sure that the same issue is reproducing in all cases (preferably on the current Docker version).

**Comment by tbouvet** [comment]
@govint I have a similar problem with plugin install/remove.
Some error messages appear in the docker daemon logs : 
```
Jan 03 14:29:24 host1 dockerd[3284]: time="2018-01-03T14:29:24.420038033+01:00" level=error msg="plugin not found"
Jan 03 14:29:13 host1 dockerd[3284]: time="2018-01-03T14:29:13.164583309+01:00" level=error msg="plugin not found"
```
Here is my issue : [Plugin not found](https://github.com/NetApp/netappdvp/issues/114 )

I try restart docker but no effect.
So I don't know how to remove this message.
Do you have some idea please ?
