### ISSUE TITLE
Feature Request: Display only exited/ stopped containers

### ISSUE THREAD

**Issue by dglib** [moby/moby#34553]
**Description**
I'd like a "docker ps -x" or some flag that will only display stopped or exited containers. When you have a large number of running containers and you wish to quickly compare/ or view it against exited containers. Having this option might make sense versus parsing through docker ps -a, ie the full list.

**Describe the results you expected:**
"docker ps -x" = display only exited containers.

**Comment by thaJeztah** [comment]
This is already supported; look for the `--filter` options in the documentation https://docs.docker.com/engine/reference/commandline/ps/#filtering

For example;

Only exited or running containers:
```bash
docker ps --filter status=exited

docker ps --filter status=running
```

Closing this, because this is already implemented, but feel free to continue the conversation
