### ISSUE TITLE
Serial port unavailable under Windows even with --privileged flag

### ISSUE THREAD

**Issue by sieben** [moby/moby#34559]
**Description**

I got a device that talk over serial port. On Unix it shows up as a /dev/ttyUSB0, on Windows as a COM.
I would like to be able to talk to this serial device from a container running on top of Docker for Windows.

**Steps to reproduce the issue:**
1. Connect something that talk over a USB serial port to your Windows machine 
2. docker run -it --privileged ubuntu ls /dev

**Describe the results you received:**

- There is no ttyUSB0

**Describe the results you expected:**

There should be a ttyUSB0 showing up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 973.8MiB
Name: moby
ID: TMWG:M7LS:5PG2:EZ4E:37KI:UGHT:OJIR:AVKU:V42E:GVNL:2GR4:QNJW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2017-08-18T09:09:52.1702444Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by sieben** [comment]
@zonyl

**Comment by friism** [comment]
Sorry, this is not currently support.

@thaJeztah this is a Docker for Windows issue (lives on https://github.com/docker/for-win)

**Comment by thaJeztah** [comment]
Yes, this issue is due to the wat Docker for Windows runs; the daemon (and containers) run in a VM, which does not have direct access to the hardware.

Can you reopen this in the Docker for Windows issue tracker (https://github.com/docker/for-win) If no issue exists yet?

**Comment by sieben** [comment]
This issue was moved here: https://github.com/docker/for-win/issues/1018

**Comment by thaJeztah** [comment]
Thanks!
