### ISSUE TITLE
Debian 9 frozen in a build process

### ISSUE THREAD

**Issue by lourenci** [moby/moby#34555]
I am an user of the docker-ce and debian. Sometimes, in a build's image process, my system frozen completely. I cannot even to move my mouse pointer.The only way to recover the system's normal state is forcing a power down with the physical button. This problems seems to happen just with debian 9.x. I already used the docker with debian 8 with no problems.

I cannot reproduce this error. It occurs randomly. It is not in a specific build process.

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 48
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.708GiB
Name: heineken
ID: PWDK:CB2H:N6PK:CHYH:NNDX:I6RH:R57A:M5ZQ:3KMW:VCSA:QZVX:6UZK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Is there anything in the logs showing? 

Also I notice you're using overlay2, and I seem to recall there was an issue with the default configuration of debian 9 which could cause issues (of course not sure if it is related in any way); https://github.com/moby/moby/issues/33733 / https://github.com/moby/moby/pull/34342

With the current information in this issue, there's not much that can be looked into, so any information and reproduction steps would be welcome to verify if it's generally reproducible, or an issue in your setup.

**Comment by thaJeztah** [comment]
closing; this one went stale
