### ISSUE TITLE
Cant Load Docker Image on VM

### ISSUE THREAD

**Issue by UdhavPawar** [moby/moby#34566]
**Description**

**Steps to reproduce the issue:**
1. Create a CentOS Virtual Machine. I am using Cloud Manager on which I created this Centos 7 VM using an official CentOS 7 template.
2. Create or use any existing saved docker image. I am using xxxxx.tar saved image file.
3. Try to load the image using the command, docker load <  xxxxx.tar.

**Describe the results you received:**
I am not able to load the Image. Neither I can see any running docker containers or images.
The error received: ```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.31/images/load?quiet=0: dial unix /var/run/docker.sock: connect: permission denied```
 

**Describe the results you expected:**
It should be able to Load the saved docker Image. So, when we do the 'docker images', it should list the loaded running image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-ce-rc3
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   665d244
 Built:        Thu Aug 17 00:57:20 2017
 OS/Arch:      linux/amd64
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.31/version: dial unix /var/run/docker.sock: connect: permission denied

```

**Output of `docker info`:**

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.31/info: dial unix /var/run/docker.sock: connect: permission denied
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am using a CentOS 7 VM, on which I have copied the saved docker image, which I am not able to load.

**Comment by erikh** [comment]
you don't have permission to use docker on that host. check the perms on /var/run/docker.sock and make sure your user has right to access it.

**Comment by cpuguy83** [comment]
Yep, as @erikh mentioned, you don't have permissions to access the socket.
Try with `sudo`.
Note that you can add your user to the `docker` group (and relogin) to not require the use of sudo.
