### ISSUE TITLE
Docker Compose "images" prints the registry port in the wrong column

### ISSUE THREAD

**Issue by AnthonyMastrean** [moby/moby#34586]
I was told this was a problem in the core API and to re-post the issue here (from https://github.com/docker/compose/issues/5062)

----

If I have a Docker image reference including a registry host name and port

```
example.com:8443/example
```

It's not displayed properly in the images table

```
$ docker-compose images
   Container         Repository       Tag         Image Id       Size
----------------------------------------------------------------------
example_example_1   example.com   8443/example   abcdef123456   173 MB
```

**Comment by tossmilestone** [comment]
@AnthonyMastrean I have found this is no a moby bug, please look at the [PR](https://github.com/docker/compose/pull/5130)

**Comment by shin-** [comment]
@thaJeztah This is fixed in Compose - issue can be closed :+1:

**Comment by thaJeztah** [comment]
Thanks! closing
