### ISSUE TITLE
Docker's btrfs graph driver eliminates the existing quota controls

### ISSUE THREAD

**Issue by tothfabian** [moby/moby#34593]
**Description**

**Steps to reproduce the issue:**
1. Install Linux using btfs root (I use arch linux)
2. enable btrfs quotas
```
btrfs quota enable /
```
3. Create a btrfs subvolume
```
btrfs subvolume create /sub1
```
4. check quota
```
btrfs qgroup show -f -re /sub1 
qgroupid         rfer         excl     max_rfer     max_excl 
--------         ----         ----     --------     -------- 
0/265        16.00KiB     16.00KiB         none         none
```
5. set a limit for the new subvolume
```
btrfs qgroup limit 10M 0/265 /
```
6. check quota
```
btrfs qgroup show -f -re /sub1 
qgroupid         rfer         excl     max_rfer     max_excl 
--------         ----         ----     --------     -------- 
0/265        16.00KiB     16.00KiB     10.00MiB         none 
```
=> You see the limit is set!

7. install docker
8. run any docker container (e.g busybox)
```
docker run -ti busybox
```
9. check quota
```
btrfs qgroup show -f -re /sub1 
qgroupid         rfer         excl     max_rfer     max_excl 
--------         ----         ----     --------     -------- 
0/265        16.00KiB     16.00KiB     10.00MiB         none 
```
=> All seems still fine up to here.
10. reboot the system
11. check quota
```
btrfs qgroup show -f -re /sub1
ERROR: can't list qgroups: quotas not enabled
```
=> Quota support is gone.
12. re-enable quota to see what it does
```
btrfs quota enable /
```
13. check quotas
```
btrfs qgroup show -f -re /sub1
qgroupid         rfer         excl     max_rfer     max_excl 
--------         ----         ----     --------     -------- 
0/265        16.00KiB     16.00KiB         none         none
```
=> The previously set quota is gone!

**Describe the results you received:**
When using docker on a btrfs volume where quotas are enabled and certain limits on certain qgroups are set the btrfs volume gets corrupted in a way that seems unrecoverable as soon as you start the first container. This behavior does not show immediately but after a reboot the quotas are disabled and the qgroup limits are gone. I found no other way to recover from that state except to reformat the btrfs volume.

**Describe the results you expected:**
When using docker on a btrfs volume where the quotas are enabled and certain limits on certain qgroups are set those should be retained and still be there after a reboot of the system.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Wed Jul 26 18:03:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Wed Jul 26 20:03:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.11.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.686GiB
Name: peregrin
ID: WGK4:K2IQ:GTX5:JMQQ:45EB:T3MU:OA62:TIUD:VIMX:VV3P:OISY:IRC6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Code**
We tried to track it down in the code and found this section:
https://github.com/moby/moby/blob/361a473121f2cd4e688a3bb71fbeff00aaf674d7/daemon/graphdriver/btrfs/btrfs.go#L367-L368
It looks like the btrfs graph driver tries to enable/disable the quotas on a subvolume base. But this does not seem to be possible. https://github.com/torvalds/linux/blob/8c27cb3566762613a23c080e3db7d0501af9a787/fs/btrfs/qgroup.c#L946-L988

By the way, the procedure subvolEnableQuota() has the same issue.

**Comment by PegasusHNU** [comment]
Docker

**Comment by thaJeztah** [comment]
ping @yongtang @cyphar PTAL

**Comment by awerlang** [comment]
> When using docker on a btrfs volume where quotas are enabled and certain limits on certain qgroups are set the btrfs volume gets corrupted in a way that seems unrecoverable as soon as you start the first container.

That's alarming. I don't see how though.

> It looks like the btrfs storage backend tries to enable/disable the quotas on a subvolume base. 

```
$ man btrfs quota
```
> BTRFS-QUOTA(8)                                                                                         Btrfs Manual                                                                                         BTRFS-QUOTA(8)
> 
> NAME
>        btrfs-quota - control the global quota status of a btrfs filesystem

If docker is still doing this (it seems so), this must be fixed, or at least documented. The implementation clearly misses how quotas work on btrfs. BTW, docker-bench-security recommends an exclusive disk partition.

Original issue: https://github.com/docker/for-linux/issues/78
