### ISSUE TITLE
Does docker static binary has any limitation?

### ISSUE THREAD

**Issue by wpeng102** [moby/moby#34595]
Docker provides a static binary installation(https://docs.docker.com/engine/installation/linux/docker-ce/binaries/), does it has any limitation is use?

**Comment by cpuguy83** [comment]
It can't use devicemapper.
It can't read logs using the journald log driver.

**Comment by wpeng102** [comment]
@cpuguy83 , thanks.
For the storage diver, does it mean except devicemapper, the static binary can support other storage diver list on https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ee-and-cs-engine?
Is there any document describe this for static docker?

**Comment by cpuguy83** [comment]
The two things I listed are the only two known problems.
Other storage drivers should be fine.

**Comment by wpeng102** [comment]
@cpuguy83  Thanks for your answer.
