### ISSUE TITLE
Missing mount entries after plugin disable in docker 17.06

### ISSUE THREAD

**Issue by pshahzeb** [moby/moby#34603]
**Description**
Mount entries from /proc/mounts are missing after a plugin disable for a volume that is attached to a running container.

**Steps to reproduce the issue:**
0. Pre-reqs: VMWare ESX with a Docker host VM inside. (Ubuntu 14.04.4 LTS) and docker-volume-vsphere VIB installed.

1. docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:15
2. docker volume create -d vsphere --name vol1
3. docker run -it -v vol1:/data alpine
4. 
```
root@sc-rdops-vm02-dhcp-52-237:~# cat /proc/mounts
...
/var/lib/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/propagated-mount ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/disk/by-uuid/66a21986-55c4-4ede-a2d9-37d30aa41a8e /var/lib/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/rootfs/mnt/vmdk ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /var/lib/docker/aufs/mnt/5e96ad0e3f1ccf2af97de5dfeb533703dbad07772f0f6c941a552287694ccd48 aufs rw,relatime,si=f8a499961122193a,dio,dirperm1 0 0
shm /var/lib/docker/containers/be6520ae7bd4a160bf190c86ef81875040e092860cc4db3723014bd7913be04c/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0 /var/lib/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/rootfs/mnt/vmdk/vol1@sharedvmfs-0 ext4 rw,relatime,data=ordered 0 0
/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0 /var/lib/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/propagated-mount/vol1@sharedvmfs-0 ext4 rw,relatime,data=ordered 0 0
nsfs /run/docker/netns/f3e57ee340eb nsfs rw 0 0
```
5. docker plugin disable -f vsphere
6. 
```
root@sc-rdops-vm02-dhcp-52-237:~# cat /proc/mounts
...
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,name=systemd 0 0
/dev/disk/by-uuid/66a21986-55c4-4ede-a2d9-37d30aa41a8e /var/lib/docker/plugins ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/disk/by-uuid/66a21986-55c4-4ede-a2d9-37d30aa41a8e /var/lib/docker/aufs ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /var/lib/docker/aufs/mnt/5e96ad0e3f1ccf2af97de5dfeb533703dbad07772f0f6c941a552287694ccd48 aufs rw,relatime,si=f8a499961122193a,dio,dirperm1 0 0
shm /var/lib/docker/containers/be6520ae7bd4a160bf190c86ef81875040e092860cc4db3723014bd7913be04c/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/f3e57ee340eb nsfs rw 0 0
```
**Describe the results you received:**
The entries for the volume that is still attached to a container are gone, 
/var/lib/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/rootfs/mnt/vmdk/vol1@sharedvmfs-0

 are gone from /proc/mounts

**Describe the results you expected:**
I expect the entries to be present. This behavior is with 17.06 and not with 17.03.

**Additional information you deem important (e.g. issue happens only occasionally):**
This behavior breaks the recovery story in our plugin.
We need to disable the plugin before upgrade. But with docker 17.06 and a container running, the recovery is broken and subsequently there is a failure to re-enable the plugin.

The subsequent plugin upgrade passes after the steps above.
```
docker plugin upgrade vsphere:latest vmware/docker-volume-vsphere:0.16
Upgrading plugin vsphere:latest from vmware/docker-volume-vsphere:latest to vmware/docker-volume-vsphere:0.16
Plugin images do not match, are you sure? [y/N] y
Plugin "vmware/docker-volume-vsphere:0.16" is requesting the following privileges:
 - mount: [/dev]
 - mount: [/var/run]
 - mount: [/etc]
 - mount: [/var/log]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
0.16: Pulling from vmware/docker-volume-vsphere
1d54a760dc2a: Download complete
Digest: sha256:5281d47506740ee927001ea5fc16d8584ed7fc04de0fb25969f0b11eb3243345
Status: Downloaded newer image for vmware/docker-volume-vsphere:0.16
Upgraded plugin vsphere:latest to vmware/docker-volume-vsphere:0.16
```
But enabling the plugin fails (the reason being vsphere plugin recovery timed out)
root@sc-rdops-vm02-dhcp-52-237:~# docker plugin enable vsphere:latest
Error response from daemon: dial unix /run/docker/plugins/f6702ec7bd851ccc90b7cef679c2b5dd59675ef050ba4ea031803d467a069e73/vsphere.sock: connect: no such file or directory

Because of #32525, the upgrade should have failed due to active mounts?

**Output of `docker version`:**

```
root@sc-rdops-vm02-dhcp-52-237:~# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
root@sc-rdops-vm02-dhcp-52-237:~# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@sc-rdops-vm02-dhcp-52-237:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86GiB
Name: sc-rdops-vm02-dhcp-52-237
ID: NINK:HV2F:IRM2:6JJU:XBVA:DW7J:CV5S:OARB:J4UL:O7S3:4LBA:7AVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 43
 System Time: 2017-08-22T16:51:15.586619735-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware ESX host.
Ubuntu 14.04.4 LTS under ESXi 6.5

@msterin @pdhamdhere @govint @shuklanirdesh82 @tusharnt

**Comment by pshahzeb** [comment]
Given this behavior, what is the assumption during a plugin upgrade? Is it expected that there won't be containers running during plugin upgrade?
What is the recommended way to do a plugin upgrade? Not have containers running  during the plugin upgrade?

**Comment by cpuguy83** [comment]
The mounts are gone because the plugin was cleaned up.
But note that mounts are namespaced. The mount should still exist in the running container which should have a private rootfs.

I'm curious you say this is with 17.06. Is that implying that you don't have the same issue in 17.03?

**Comment by pshahzeb** [comment]
Nope we didn't have this issue with 17.03

**Comment by cpuguy83** [comment]
Can you explain what the main issue is since containers should still have the mount active in their mount ns?

**Comment by pshahzeb** [comment]
thanks @cpuguy83 

> Can you explain what the main issue is since containers should still have the mount active in their mount ns?

Yes containers have mounts active.

The main issue is about the mounts gone (no entries in /proc/mounts/) after plugin disable.
> The mounts are gone because the plugin was cleaned up.

Is this always valid for plugin disable? Could you please explain why cleanup mounts on disable?

While enabling vsphere plugin after an upgrade, the recovery logic in vsphere plugin is broken due to missing mounts. Given the missing entries, plugin ends up assuming the volumes aren't mounted and issues a mount again.

This is only valid in case of active containers  during upgrade. Is it recommended to not have active containers during a plugin upgrade?

**Comment by cpuguy83** [comment]
> Is this always valid for plugin disable? Could you please explain why cleanup mounts on disable?

Because we can't really leave mounts lying round on plugin disable. If the plugin is disabled, it should be considered inactive.

> Given the missing entries, plugin ends up assuming the volumes aren't mounted and issues a mount again.

I"m not sure why this would break things.
But in any case, shouldn't the plugin rely on Docker to tell it what it needs? Have you observed a case where this doesn't work out?

> Is it recommended to not have active containers during a plugin upgrade?

It's definitely more predictable to not have any active containers during upgrade. That said, this doesn't look like an issue of active containers, but rather of an incorrect assumption that there is a problem with the mounts when the plugin comes back up.

**Comment by msterin** [comment]
> Because we can't really leave mounts lying round on plugin disable. If the plugin is disabled, it should be considered inactive.

It really depends.

In vSphere case, the plugin is only on the management path. It is responsible for refcounting requests from Docker, attaching/detaching virtual disks to/from VM and mounting/ unmounting related /dev/disk/by-path/... in the guest OS (aka Docker host). 

The plugin is *not* on the IO path, so *if plugin is down for any reason, the container IO is uninterrupted*. When plugin starts up (after a crash, or a disable. or whatever), it interrogates Docker for containers which use vSphere volumes, analyzes Linux mounts (that's where we bluntly use /proc/mounts) and fully recovers internal refcounters and the likes. The end results - customers can update plugin without service interruption. Or the plugin can crash and be restarted without service interruption. Etc. 

unfortunately 17.06 breaks it, at least for upgrade. Can we introduce something in plugin config to ask docker NOT to do this ?  Any other suggestions ? 

> That said, this doesn't look like an issue of active containers, but rather of an incorrect assumption that there is a problem with the mounts when the plugin comes back up.

Can you elaborate on this - what is the correct assumption about bind mounts and about the actual device FS mount ? 
Are you saying the actual device stays mounted after plugin disable ? 
What is the state of the mounted devices when the plugin comes back ?

**Comment by cpuguy83** [comment]
@msterin The device would stay mounted in the container(s) mount namespace after plugin disable.

**Comment by pshahzeb** [comment]
Thanks for the insight @cpuguy83 
We took care of it in the plugin.
