### ISSUE TITLE
API documentation on `Memory` and `MemorySwap`  host config parameters needs improving

### ISSUE THREAD

**Issue by delcypher** [moby/moby#34607]
**Description**

The `Memory` and `MemorySwap` Docker API host config parameter documentation is pretty bare bones.

```
Memory | integer
Memory limit in bytes.
```

```
MemorySwap | integer <int64>Total memory limit (memory + swap). Set as -1 to enable unlimited swap.
```

There is more documentation on the `--memory` and `--memory-swap` flags at https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory but it is unclear whether these correspond directly to the `Memory` and `MemorySwap` (i.e. they have the same restrictions).

Even from this documentation. It is not at all clear how one would configure a container to not use swap at all which is what I wanted to do. An initial guess would be to set something like `--memory 1g` and `--memory-swap 1g` to allow 1GiB of memory and no swap space (without reading the documentation) but my reading of the [current documentation](https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory) suggests that this will be treated as if `--memory-swap` was not set.

This isn't very intuitive behaviour. It isn't clear to me at all why this restriction is in place. [Older versions of the Docker API docs](https://docs.docker.com/engine/api/v1.24/#31-containers) say
this about the `MemorySwap` parameter (which I believe corresponds to `--memory-swap`).

```
Total memory limit (memory + swap); set -1 to enable unlimited swap. You must use this with memory and make the swap value larger than memory.
```

but newer versions of the API docs don't say `You must use this with memory and make the swap value larger than memory`.

I can't see anything documented about cgroup's `memory.memsw.limit_in_bytes` and `memory.memsw.limit_in_bytes` parameters that says they can't be set to the same value.

**Comment by delcypher** [comment]
This is related to https://github.com/docker/docker.github.io/issues/4335

**Comment by cpuguy83** [comment]
Closing this one since there isn't a need to have two issues with the same thing, and docs are ultimately not handled in this repo.
Thanks!
