### ISSUE TITLE
Unable to bind container port to host machine

### ISSUE THREAD

**Issue by vaibhav-gadgil-sp** [moby/moby#34619]
Environment:

Host machine: 
Windows server 2016

docker version:
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64
 Experimental: false

I have pulled Microsoft dotnet framework image from docker hub:
docker image ls
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
microsoft/dotnet-framework   4.7                 038914e36f1e        2 weeks ago         11.2 GB

Now I am trying to run the container using this image id. 

I am able to start the container with the following command:
docker run --name test -t 038914e36f1e

But when I am trying to bind the host port with this container, it's failing with the following error:

docker run -d -p 80:5050 --name test -t 038914e36f1e
19c817a6de04b16736dbe23c221c8a7a023c5b916be1f31792cd5f7b4c235f04
C:\Program Files\Docker\docker.exe: Error response from daemon: failed to create endpoint test on network nat: HNS failed with error : Unspecified error.

I want to make my container accessible from outside world.
Needs input on how I can resolve this issue.

**Comment by friism** [comment]
Please update to the latest version of Docker (17.06.1): https://docs.docker.com/engine/installation/windows/docker-ee/#update-docker-ee

You might also want to try the networking cleanup script: https://docs.docker.com/engine/installation/windows/docker-ee/#update-docker-ee

cc @kallie-b

**Comment by georgyturevich** [comment]
Hi @vaibhav-gadgil-sp 

We also face sometime with this recurring issue.

Usually following sequence of Powershell commands helps us to sort out the issue
```
Stop-Service docker 
Get-ContainerNetwork | Remove-ContainerNetwork
Start-Service docker 
```

We are working with MS Support team on it in order to understand a root cause of it.

**Comment by thaJeztah** [comment]
@vaibhav-gadgil-sp are you still having this issue on the current release? Did the information above help you resolve our problem?

**Comment by thaJeztah** [comment]
Closing as this went stale
