### ISSUE TITLE
Docker has no garbage collection.

### ISSUE THREAD

**Issue by joeyhub** [moby/moby#34634]
Even after removing all containers, images and volumes I still find data in /var/lib/docker. This is largely in aufs. Even when containers are removed volumes also still seem to persist. This makes docker virtually unusable as it quickly uses up tremendous amounts of space.

There often no way around this but to remove the entire directory and reinstall the docker package.

**Comment by cpuguy83** [comment]
There is a regression in 17.06.1 with the AUFS driver where some of the data is not removed.
You can find this under `/var/lib/docker/aufs` in the `diff` directory, there are likely a bunch of directories with the suffix `-removing`.

These can be safely removed manually.
17.06.2 will resolve this. Until then I'd recommend either using the overlay2 driver or reverting back to 17.06.0.
