### ISSUE TITLE
Add --init support to docker stacks (and docker-compose v3)

### ISSUE THREAD

**Issue by Tim15** [moby/moby#34639]
Related to docker/compose#4805.

Should be the same or similar to the format in compose v2: https://docs.docker.com/compose/compose-file/compose-file-v2/#init
e.g.
```
version: '3'
services:
  web:
    image: alpine:latest
    init: true
```
I would assume this requires an addition to `docker service create`, because an `--init` option is not present in docker version `17.06`, although it may be present in the API, just not in the CLI yet.

If someone would point me at the right files/directories I would happy to give this a shot.

P.S. sorry to bother everyone with a low-priority issue. I know you've got a lot to do to split up docker right now. I'm very excited about building components to extend docker. (like a component for managing GPUs to run ML in containers).

**Comment by cpuguy83** [comment]
Closing since this is a dup of https://github.com/docker/cli/issues/51 and the compose format lives over there.
Thanks!

**Comment by thaJeztah** [comment]
Compose file support was implemented in https://github.com/docker/cli/pull/1129, which completes a long chain of PR's to implement this feature :tada:
