### ISSUE TITLE
unable to keep container as daemon by using -d flag or running /bin/bash in container

### ISSUE THREAD

**Issue by jongwu** [moby/moby#34630]
**Description**

**Steps to reproduce the issue:**
```
root@jiawu02:/# docker run -d --name ubu ubuntu:14.04 /bin/bash
b6248750fbee706180e5ae6803ffd20c457c8638ab17b87e3d816975d3d5893e
```

**Describe the results you received:**
```
root@jiawu02:/# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Describe the results you expected:**

I can keep container running before by those method, but I can not do that these days.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

root@jiawu02:/home/wu/gerrit# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
root@jiawu02:/home/wu/gerrit# docker info
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 57
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-32-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.087GiB
Name: jiawu02
ID: VZB2:7JTS:LQRZ:T5QR:L5WK:WGZB:2CDG:7UAS:UE62:QGQL:DB3A:6FQS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment]
@jongwu I think you need to specify `-it` in addition to `-d` because `bash` needs a `tty`:

```
docker run -dit --name ubu ubuntu:14.04 /bin/bash
```

**Comment by cpuguy83** [comment]
Yep, need `-t`.
