### ISSUE TITLE
Client can't resolve digest on service create

### ISSUE THREAD

**Issue by pankajred** [moby/moby#34640]
i'm using docker swarm . at master node when i type this command (docker service create --replicas=2 --name mywebserver apache).. i got this error(image apache could not be accessed on a registry to record its digest. Each node will access apache independently, possibly leading to different nodes running different versions of the image.) how to resolve this ..!!

**Comment by Maryom** [comment]
Hi,
Did you find a solution ? I got the same error.

**Comment by cpuguy83** [comment]
The client (docker CLI) tries to resolve the digest of the image by contacting the registry.
If it's not able to then it just sends the image that you specified as is.
Likewise when creating the service on the manager. It tries to resolve the digest if it didn't already include a digest.

So it seems like you are having an issue reaching the registry.

**Comment by Maryom** [comment]
Thanks for your replay.
This is the error I got:
```
image mongo:latest could not be accessed on a registry to record
its digest. Each node will access mongo:latest independently,
possibly leading to different nodes running different
versions of the image.
```
Do you have you have any idea how to solve it ? or have to solve the issue to reach registry ?

**Comment by cpuguy83** [comment]
Can you pull an image? Are you going through some proxy?

**Comment by Maryom** [comment]
No I can't pull any image :(

Are you going through some proxy?
I don't know, How can I know? Could you please guide me.

**Comment by cpuguy83** [comment]
I'm going to close this since it doesn't look like there's an issue here.
Unfortunately I really can't troubleshoot your internet connection to the DockerHub services.

**Comment by Maryom** [comment]
Ok thanks.
