### ISSUE TITLE
How to add smoother authentication at port 2375

### ISSUE THREAD

**Issue by jianzzz** [moby/moby#34648]
As we know, 2375 is not safe in production environment, and  we are recommended to use certificate . However, if we run docker in a cluster and use ip but not domain to attach each host machine, we should produce server.key and server.crt for each machine(i.g. echo subjectAltName = IP:host-ip > extfile.cnf)， it will increase operation and maintenance costs if cluster members change frequently. 
Can we use any other smoother authentication?

**Comment by AkihiroSuda** [comment]
My PR for using SSH: https://github.com/docker/go-connections/pull/39 (under design discussion)

**Comment by jianzzz** [comment]
Does it support docker 1.12.x ?

**Comment by jianzzz** [comment]
@AkihiroSuda How to use in docker 1.12.x

**Comment by thaJeztah** [comment]
let me close this one because there's already an issue tracking that effort in https://github.com/moby/moby/issues/31871
