### ISSUE TITLE
Debian Repository: missing sources

### ISSUE THREAD

**Issue by Hoeze** [moby/moby#34646]
The package sources are still missing in the Debian repository.

When putting the following line to my sources.list:
`deb-src [arch=amd64] https://download.docker.com/linux/debian stretch stable`
I get the following error message:
> Reading package lists... Done
> E: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/InRelease  Unable to find expected entry 'stable/source/Sources' in Release file (Wrong sources.list entry or malformed file)

See also #30547

**Comment by cpuguy83** [comment]
ping @andrewhsu

**Comment by Hoeze** [comment]
Any updates on this?

**Comment by neolectron** [comment]
+1

**Comment by Hoeze** [comment]
Will this ever be fixed or do we have to live with a pig in a poke?

**Comment by bsousaa** [comment]
We currently have no intent to publish source packages. But you can download sources from this repo. You can have a look at this repo: https://github.com/docker/docker-ce-packaging to see how packages are built.
