### ISSUE TITLE
long execution time for "docker info" command

### ISSUE THREAD

**Issue by haveatry** [moby/moby#34649]
**Hello,
When I execute "docker info" command in my linux server, it will used more than one second from time to time.  The server is used for testing, it does not take real work load. There is no such problem when executing "docker ps" or "docker info" command. Is there any suggestion for debugging such issue?**

**Steps to reproduce the issue:**
[root@docker04 docker]# time docker info
Containers: 42
 Running: 30
 Paused: 0
 Stopped: 12
Images: 65
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 14.09 GB
 Data Space Total: 5.701 TB
 Data Space Available: 5.687 TB
 Metadata Space Used: 9.515 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.97 GB
 Thin Pool Minimum Free Space: 570.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 32
Total Memory: 251.8 GiB
Name: docker04
ID: OZVQ:UR53:7NHK:P6XF:VWJK:4OAT:CCNW:PK4U:SPKS:OKPQ:DSIQ:ATOD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 hub.xxxx:5000
 127.0.0.0/8
Registries: docker.io (secure)

**real	0m1.297s
user	0m0.017s
sys	0m0.015s**

**Output of `docker version`:**

```
[root@docker04 docker]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
[root@docker04 docker]# docker info
Containers: 41
 Running: 30
 Paused: 0
 Stopped: 11
Images: 65
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 14.08 GB
 Data Space Total: 5.701 TB
 Data Space Available: 5.687 TB
 Metadata Space Used: 9.507 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.97 GB
 Thin Pool Minimum Free Space: 570.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 32
Total Memory: 251.8 GiB
Name: docker04
ID: OZVQ:UR53:7NHK:P6XF:VWJK:4OAT:CCNW:PK4U:SPKS:OKPQ:DSIQ:ATOD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 hub.xxxx:5000
 127.0.0.0/8
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[root@docker04 docker]# uname -a
Linux docker04 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@docker04 docker]#  cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)

**Comment by ripcurld0** [comment]
Closing this as this is an old version of Docker and since then there were many bug fixes.
