### ISSUE TITLE
overlay network is not working between gce (google compute engine) and other hosts from different data centers

### ISSUE THREAD

**Issue by dottgonzo** [moby/moby#34647]
this is the configuration of the node on gce (before join it on swarm)

Output of docker version:

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Output of docker info:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951GiB
Name: manager
ID: LRKQ:UWEC:BCSX:SWTP:BWM5:BDM4:O2EY:ELSO:T3WV:PFRP:ZKJ7:7EDZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

I've 4 VPS on 4 different datacenter/cloud service.
1 is a scaleway vps in France
1 is a scaleway vps in Amsterdam
1 is a hetzner vps in Germany
1 is a compute engine from google cloud platform

all 4 are configured with same os, same docker repo and docker version as the one on gce (ubuntu xenial, docker 17.06.1-ce)

when i join it all toghether and test some services, i've noticed that the overlay network is totally unstable on the node located on gce (i can't understand why with some service sometime works and for other not works at all), but the swarm works perfect on other nodes. If i remove the gce vm, the swarm became stable as my expectations.

of course i've used the advertise-addr on swarm init and swarm join.

To be sure that the firewall is not blocking some port, i've opened all the tcp and udp ports on gce, but i still continue to not be able to use the overlay network as expected.
I've also tried to initialize the overlay network by a subnet and try different subnets, as the 10.0.9.0/24, or others)

I'm missing something? If you need more details (as the network inspect) i will retry to swarm the gce instance and test for you what you need.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
