### ISSUE TITLE
complie of mobi project and create tar.gz or debian

### ISSUE THREAD

**Issue by challa** [moby/moby#34659]
Sorry is not bug,

I am looking for a setup/steps to compile moby and create executables in tar.gz or debian format.
could some one point out any documentation/blog on how to do this.

Thanks in advance.

**Comment by vrothberg** [comment]
`$ make tgz` and `$ make deb` should do the desired tasks.

**Comment by cpuguy83** [comment]
Yep, check out the Makefile.
Thanks!
