### ISSUE TITLE
Docker hangs Version 17.06.1-ce-mac24 (18950)

### ISSUE THREAD

**Issue by hardikgw** [moby/moby#34650]
**Description**

**Steps to reproduce the issue:**
1. Update docker to latest Version 17.06.1-ce-mac24 (18950)
2. Reset all settings to factory settings
3. Run docker-compose up OR docker-compose build after pulling required images for an existing project

**Describe the results you received:**
Docker hangs

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Version 17.06.1-ce-mac24 (18950)

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment]
Couldn't reproduce this. Can you share some of your settings and the compose file?

**Comment by hardikgw** [comment]
DockerCompose file is [here](https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/docker-compose.yml) 
https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/docker-compose.yml

Justl tried uninstall and reinstall docker, still hangs!

**Comment by cpuguy83** [comment]
Yes, this needs more detail.
Also, please open on github.com/docker/for-mac and if it ends up being a moby issue we can deal with it at that point. Thanks!

Also, what exactly is hanging? Was docker hung before you did the compose-up?

**Comment by hardikgw** [comment]
Opened https://github.com/docker/for-mac/issues/2007 

Again... > docker-compose up  ... hangs!
