### ISSUE TITLE
UCP 2.2.0 doesn't allow delete of volume drivers

### ISSUE THREAD

**Issue by bandeep-px** [moby/moby#34664]
**Description**
UCP 2.2.0 doesn't allow delete of volume drivers, it says no such volume

**Steps to reproduce the issue:**
1. create a volume using portworx pxd as driver from Volume menu
2. Select the volume and go to Actions
3. Remove the volume and confirm the message

**Describe the results you received:**

UCP  says ""No such volume" although volume are there
**Describe the results you expected:**

It should delete the volume

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```
[root@vm4 ~]# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@vm4 ~]# 

**Output of `docker info`:**

```
(paste your output here)
```
[root@vm4 ~]# docker info
Containers: 14
 Running: 12
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 17.06.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local pxd
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: g7vkq9kap8ixd4rd63hxjgko1
 Is Manager: true
 ClusterID: 2i1eqzlnojzhyp5v6u5rtd8gk
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
  External CAs:
    cfssl: https://70.0.34.174:12381/api/v1/cfssl/sign
 Root Rotation In Progress: false
 Node Address: 70.0.34.174
 Manager Addresses:
  70.0.34.174:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.656GiB
Name: vm4
ID: TM5H:UED2:SMHN:WDBX:AG2F:TD47:6Q2L:N6JN:S5NE:HVS4:SEMJ:23DF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: wilkins
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-ip6tables is disabled
[root@vm4 ~]# 
**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual Box
![ucp-2 1 4](https://user-images.githubusercontent.com/26777009/29834879-f961b6e2-8ca4-11e7-8b56-b429ea7ef0ec.jpg)

**Comment by bandeep-px** [comment]
Another issue, is when create service , in the resources tab, existing volume is not showing the volume created.

**Comment by cpuguy83** [comment]
ping @vsaraswat

**Comment by kcrawley** [comment]
i believe i'm experiencing a similar issue with netappdvp, i'm unable to remove volumes remotely or via API. i must be on a manager node.

**Comment by thaJeztah** [comment]
Thanks for reporting, but unfortunately there's nothing that can be done in this repository, because Docker UCP is not maintained here.

Can you report this through customer support for UCP?

**Comment by bandeep-px** [comment]
Sure Could you please give the link to report

**Comment by thaJeztah** [comment]
Should probably be support@docker.com

**Comment by thaJeztah** [comment]
I see the team is working on a fix for this (but no information which release it will end up in)
