### ISSUE TITLE
docker 17.06.1-ce cant connect to 172.17.0.1 and to IP of underlying host 

### ISSUE THREAD

**Issue by slawekgh** [moby/moby#34677]
docker 17.06.1-ce 
container (alpine:latest) cannot connect to 172.17.0.1 and to main IP of hardware host (192.168.43.197) 
I also checked for centos container and ubuntu container 

I have only 2 containers on machine: 
```
# docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
93a7083bf3d8        alpine               "tail -f /dev/null"      8 minutes ago       Up 8 minutes                                 priceless_lalande
0bd6ad4892d0        nginx                "nginx -g 'daemon ..."   9 minutes ago       Up 9 minutes        0.0.0.0:8080->80/tcp     heuristic_noether
```
from alpine container: 
```
# curl 172.17.0.1:8080
curl: (7) Failed to connect to 172.17.0.1 port 8080: Host is unreachable

 # curl 192.168.43.197:8080
curl: (7) Failed to connect to 192.168.43.197 port 8080: Host is unreachable
```
from another container on another host everything works fine:
```
# curl 192.168.43.197:8080
[...]
<title>Welcome to nginx!</title>
[...]
```

**Comment by slawekgh** [comment]
+1

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
