### ISSUE TITLE
docker-ce-17.06.1.ce-1: can not remove network

### ISSUE THREAD

**Issue by gabrielfsousa** [moby/moby#34678]
```
[root@docker01 yum.repos.d]# docker network rm macvlan9
Error response from daemon: configuration network "macvlan9" is in use
```

the macvlan9 isnt in use

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
