### ISSUE TITLE
Feature request: Make json files diffable

### ISSUE THREAD

**Issue by johndmulhausen** [moby/moby#34673]
Migrated from https://github.com/docker/docker.github.io/issues/4300

If I want to add a line in in /etc/docker/daemon.json, then I have to change the old last line, too. Before:
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay"
}
```
After:
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay",
        "fixed-cidr": "10.20.0.0/16"
}
```
See the comma I had to insert just to make json happy? On a "diff" output I see 2 changed lines, even though only a single option has been added. This leads to merge conflicts with your favorite version control system.

I'd love to write 
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay",
}
```
right from the start.

**Comment by cpuguy83** [comment]
This is invalid json.

I don't think it's worth it to support this.

**Comment by vrothberg** [comment]
> This is invalid json.

That's correct. The grammar on http://www.json.org illustrates that `members` can only terminate with `pair`, which is composed of `string : value` (no following comma). So there's not much that can be done.

**Comment by AkihiroSuda** [comment]
@vrothberg Lots of external JSON tools reject trailing commas.

If we want to do this, we should rather support toml, which also supports adding comments.

**Comment by vrothberg** [comment]
> If we want to do this, we should rather support toml, which also supports adding comments.

@AkihiroSuda That's an interesting idea. How could such a change be realized? Default to toml and (automatically) transform json to toml?

**Comment by AkihiroSuda** [comment]
If `config.toml` exists the daemon should use that, otherwise fallback to `config.json`.
Translation stuff seems unneeded.

**Comment by ripcurld0** [comment]
calling #dibs

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
