### ISSUE TITLE
Error starting daemon: couldn't create plugin manager: error setting plugin manager root to private: invalid argument

### ISSUE THREAD

**Issue by yeison** [moby/moby#34680]
**Description**

**Steps to reproduce the issue:**
1. Copy docker graph root from /var/lib/docker to a new HD
2. Update daemon.json configuration to point graph to new location
3. Start dockerd

**Describe the results you received:**
```
error starting daemon: couldn't create plugin manager: error setting plugin manager root to private: invalid argument
```

**Describe the results you expected:**
Docker daemon should've started without issues

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at tcp://0.0.0.0:2376. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at tcp://0.0.0.0:2376. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by insertjokehere** [comment]
I'm having the same issue. @yeison did you find a work-around?

**Comment by insertjokehere** [comment]
Rebooting the host fixed this for me

**Comment by yeison** [comment]
I  didn't try to reboot.  I went back to using the default location of the docker graph.  It wasn't an ideal solution but at least I can run my dockerd

**Comment by brightdroid** [comment]
I've the same problem on ubuntu 16.04.3, my `/etc/docker/daemon.json`:
```yaml
{
"dns": ["192.168.0.2"],
"data-root": "/srv/docker"
}
```
`/srv/docker` is a LV with ext4

Installed package:
```
# dpkg -s docker-ce
Package: docker-ce
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 94104
Maintainer: Docker <support@docker.com>
Architecture: amd64
Version: 17.06.1~ce-0~ubuntu
...
```

**Comment by danesjr** [comment]
Currently have the same problem.
going back to using /var/lib/docker works 
rebooting didn't do anything

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init

**Comment by pavel-jurasek-joincoup-com** [comment]
Fixed by updating system packages **yum update** no need for reboot or anything.

**Comment by thaJeztah** [comment]
Is `/mnt/file_server/docker/` actually mounted when the daemon starts? What kind of filesystem is on it? Does it work if you use the default (`/var/lib/docker`) location?

**Comment by pavel-jurasek-joincoup-com** [comment]
@thaJeztah @aliarshad9691 we fix this by downgrading platform to docker-ce-stable then it worked without problem.

in EC2 instance we have this in post_launch.sh

```
mkdir /var/lib/docker || :
mkfs -t xfs -n ftype=1 /dev/xvdd
mount -t xfs /dev/xvdd /mnt
systemctl stop docker
mv /var/lib/docker/* /mnt
umount /mnt
mount -t xfs /dev/xvdd /var/lib/docker

echo "UUID=$(blkid -s UUID -o value /dev/xvdd) /var/lib/docker xfs defaults 0 0" >> /etc/fstab
```

**Comment by thaJeztah** [comment]
@pavel-jurasek-joincoup-com can you provide the output of `docker version` and `docker info` for the versions of docker that _worked_ and the version that _didn't_ work?

**Comment by pavel-jurasek-joincoup-com** [comment]
@thaJeztah 

What do not work:
docker-ce-17.07.0

What works:
docker-ce-17.06.2

**Comment by tschf** [comment]
I just updated and got this error. 

Version

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

My daemon.json looks like:

```
{
    "debug": true,
    "data-root": "/home/trent/docker_images",
    "storage-driver": "devicemapper"
}
```

```
DEBU[2017-10-01T21:22:31.338045140-04:00] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[2017-10-01T21:22:31.338546638-04:00] libcontainerd: new containerd process, pid: 16811 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=1048576
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=11674 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[2017-10-01T21:22:31.839209263-04:00] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
DEBU[2017-10-01T21:22:32.339081473-04:00] libcontainerd: containerd health check returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
WARN[2017-10-01T21:22:32.340568470-04:00] failed to rename /home/trent/docker_images/tmp for background deletion: rename /home/trent/docker_images/tmp /home/trent/docker_images/tmp-old: file exists. Deleting synchronously 
DEBU[2017-10-01T21:22:32.340784690-04:00] Using default logging driver json-file       
DEBU[2017-10-01T21:22:32.340831172-04:00] Golang's threads limit set to 83700          
DEBU[2017-10-01T21:22:32.342768857-04:00] Cleaning up old mountid : start.             
Error starting daemon: couldn't create plugin manager: error setting plugin manager root to private: invalid argument
```

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Presumably you should get the same error from devicemapper in this case if the plugin manager wasn't doing the same thing.

What's in the mount table?

What happens if you stop docker and then:
```
mount --bind /var/lib/docker/plugins /var/lib/docker/plugins
mount --make-private /var/lib/docker/plugins
```

Does the last command succeed?

**Comment by tschf** [comment]
Thanks for the tips.

I just tried again starting docker but that error is not longer propping up.

**Comment by Faqa** [comment]
Have encountered this issue, in my case it was because I was trying to use the root of a disk as the data-root. The moment I changed data-root from "/mnt/docker_lib" to "/mnt/docker_lib/inner", this error disappeared.

**Comment by jonathan-kosgei** [comment]
@thaJeztah I'm running into this repeatedly with ubuntu 16.04 and docker 17.11.0-ce.

I'm mounting a volume to /mnt/docker and setting that as the data root
```
{
"graph": "/mnt/docker"
}
```
On several different servers after a reboot, I'm unable to `docker-compose up -d` the services that were running prior to the reboot
```
ERROR: Service 'kinesis-log-ingestor' failed to build: failed to get layer for image sha256:053cde6e8953ebd834df8f6382e68be83adb39bfc063e40b0fc61b4b333938f1: layer does not exist
```
I get the following error from `journalctl -xe -u docker`

```
Error starting daemon: couldn't create plugin manager: error setting plugin manager root to private: invalid argument
```

**Comment by jonathan-kosgei** [comment]
I was able to fix this by rebooting, stopping docker, mounting the volume, starting docker

**Comment by thaJeztah** [comment]
If `/mnt/docker` is not mounted before docker is started, then that would definitely produce weird errors yes

**Comment by shakaran** [comment]
For other coming here from google, this is what I discover in my audit in a VPS with CentOS 7.4:

```
# mount --make-private /var/lib/docker/plugins
mount: none is write-protected, mounting read-only
mount: cannot mount none read-only
```

```
# grep docker /etc/fstab 
UUID= /var/lib/docker xfs defaults 0 0
```

So folder _/var/lib/docker/plugins_ would be mount as write permissions, but actually it refuses to mount only as read-only

```
# dmesg | grep docker
[3785615.463271] audit: type=1400 audit(1515451857.439:760): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default-cgns" name="/var/lib/docker/plugins/" pid=44245 comm="dockerd" flags="rw, private"
```

So apparmor deny the mount since it is a container based in LXC

**Comment by cpuguy83** [comment]
This should be fixed by #35829 which will stop using the private mount, but also note we use private mounts, unbindable mounts, etc in other places (or may in the future).

**Comment by amundra2016** [comment]
For me the solution came out is to mount volume `/var/run/docker.sock` into the container while starting it, that is run `docker run -d -v "/var/run/docker.sock:/var/run/docker.sock:rw" <image>`

**Comment by fossum** [comment]
If using Proxmox, [this site](https://www.solaris-cookbook.eu/virtualisation/proxmox/proxmox-lxc-running-docker-inside-container/) had the fix for me.

**Comment by cpuguy83** [comment]
This is fixed on master.
Thanks!

**Comment by prabhakar-pal** [comment]
Is it possible to give the commit id so that we know which docker version has this fix?

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/pull/35829 specifically https://github.com/moby/moby/pull/35829/commits/37d7b7ddc332541f516d0c41d9ad30b28f2d3e22
