### ISSUE TITLE
Using Node:8 image (should be Debian) installing /etc/lsb_release

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#34688]
I have this command in my Dockerfile:

```docker
FROM node:8
RUN ... # there is more stuff here omitted for brevity
RUN sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable"
```

this gives me an error:

```
Step 8/39 : RUN sudo add-apt-repository        "deb [arch=amd64] https://download.docker.com/linux/debian        $(lsb_release -cs)        stable"
 ---> Running in a1e480c001dd
/bin/sh: 1: lsb_release: not found

```

I also tried using `/etc/lsb_release`, and I get the same thing.

`/bin/sh: 1: /etc/lsb_release: not found`

any help much appreciated - ultimately I just want to install Docker within a Docker container - that's what I am attempting to do here.

**Comment by AkihiroSuda** [comment]
You just need to apt install lsb-release
