### ISSUE TITLE
Less UDP throughput with --net=host

### ISSUE THREAD

**Issue by BastianHofmann** [moby/moby#34690]
I'm comparing performance of a simple UDP server in multiple Docker setups to analyse network performance of Docker. The UDP server has one socket listening on port 319 and socket sending the packets back (through different interface). The throughput of the Docker container without --net=host is higher. Does someone have an explanation?

**Steps to reproduce the issue:**
1. Start bastianhofmann/reflector:latest once with --net=host, once without
2. Send UDP packets to 10.0.1.1:319
3. Count received packets

**Describe the results you received:**

Higher throughput of the server running in container with it's own network namespace.

**Describe the results you expected:**

The server running in a container with --net=host should have a higher throughput, since the packets do not have to be forwarded through the Docker network bridge (also no NAT, port forwarding)

**Additional information you deem important (e.g. issue happens only occasionally):**

I ran the tests multiple times and the output is deterministic. The packets are 64 Bytes in size, if bigger packets are used (1514 Byte) the container with --net=host is faster.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-0:22-44120-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 739.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 7.271 GB
 Metadata Space Used: 1.29 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-1-grml-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65 GiB
Name: narva
ID: 4GCX:VQAO:TT7D:FXQG:32H5:DE5S:QXYO:EG6M:DB7V:PNOE:PSE4:TENK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical server; Intel(R) Xeon(R) CPU E3-1230 V2 processor; Intel 82599ES NICs

**Comment by cpuguy83** [comment]
How was the test performed? From an external host?
How many iptables rules does it need to jump through before the packet reaches the host interface?

**Comment by BastianHofmann** [comment]
@cpuguy83 The packets are generated and sent to the SUT from another server (using the MoonGen packet generator https://github.com/emmericp/MoonGen). The packets are received on one interface and sent back to the load generator on another. The second sending interface is added to the network namespace of the container. Outgoing packets do not go through the Docker network. The schematic shows the traffic flow through the SUT.

[bridge_setup.pdf](https://github.com/moby/moby/files/1267167/bridge_setup.pdf)

There are no iptables added before Docker is installed (empty system). Only Dockers iptable rules need to be checked.

**Comment by cpuguy83** [comment]
> The second sending interface is added to the network namespace of the container
What does this mean?
There's some other interface that you are adding to the host when using `--net=host` and to the container NS when using normal container networking?

What is the MTU on the host interface and on the container interface?
Ultimately, when using `--net=host` the only thing docker does is *not* setup a network namespace.

**Comment by BastianHofmann** [comment]
@cpuguy83 guessing the MTU is 1500, but I have to check to make sure. Will take a few minutes.

I know that no network namespace is created. That's why the outcome is so confusing.

**Comment by BastianHofmann** [comment]
@cpuguy83 all interfaces have MTU 1500

**Comment by BastianHofmann** [comment]
This is a graph of the recorded throughputs. I'd expect the same or similar throughputs for native and Docker net-host setups.

[alt_rx_total_packets.pdf](https://github.com/moby/moby/files/1267316/alt_rx_total_packets.pdf)

**Comment by BastianHofmann** [comment]
For anyone stumbling across this. Most of the performance hit came from installing Docker itself. Docker installs iptable rules and runs background tasks, which have implications on performance. Also try setting the --privileged flag when creating the container (access to some devices may require capability checks, which also impact performance).
