### ISSUE TITLE
Stack rollback on failure

### ISSUE THREAD

**Issue by dedalusj** [moby/moby#34712]
Stack updates should support rollback of the entire stack in cases where some of the service update fails.

Currently the docker stack deploy command offers the ability to automatically rollback failing service via the `deploy -> update_config -> failure_action` configuration but the rollback action is applied on a service by service basis.

If only some of the services fails during an update the above behaviour will rollback the failing services but update the healthy ones leaving the stack in an inconsistent state.

Furthermore the stack update is done non-interactively meaning that the only way to detect inconsistent state after an update is to actively monitor the state of all services in the stack and try to reconcile it with their respective desired state.

**Comment by thaJeztah** [comment]
could you reopen this issue in the https://github.com/docker/cli repository? Stacks are implemented client side, and that where the code lives for that
