### ISSUE TITLE
Network option "com.docker.network.windowsshim.dnssuffix" is lost on daemon restart

### ISSUE THREAD

**Issue by riverar** [moby/moby#34716]
**Description**

After creating a `transparent` network with option `com.docker.network.windowsshim.dnssuffix` set, restart of the Docker service results in the option being lost, requiring network rebuild.

**Steps to reproduce the issue:**
1. Create network: `docker network create -d transparent -o com.docker.network.windowsshim.dnssuffix=test.local`
2. Verify DNS suffix is set: `docker network inspect test`
3. Restart the Docker service
4. Verify DNS suffix is missing: `docker network inspect test`

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-ce-rc1
 API version:  1.30 (downgraded from 1.31)
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 05:19:44 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ee-1
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   4dd6e94
 Built:        Sat Aug 12 02:14:08 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 123
Server Version: 17.06.1-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1593.amd64fre.rs1_release.170731-1934)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.95GiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2017-09-03T22:22:19.9439329-07:00
 EventsListeners: 0
Username: withinrafael
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
cc: @jhowardmsft @PatrickLang @neilpeterson @msabansal

**Comment by msabansal** [comment]
@riverar This is a management layer issue in how networks are repopulated in networks. The networks still retain the dnssuffix and new containers will still have the proper dnssuffix. Its just that they are not visible in docker network inspect.

**Comment by riverar** [comment]
@msabansal Thanks, this behavior breaks docker-compose scenarios (thinks the network options have changed and refuses to continue until recreated). Just heads up.

**Comment by msabansal** [comment]
@riverar Didn't know this. Will get this fixed soon.

**Comment by thaJeztah** [comment]
@msabansal can this one be closed now that https://github.com/moby/moby/issues/35563 was merged?

**Comment by msabansal** [comment]
Yes. Thanks

**Comment by thaJeztah** [comment]
Thanks! Closing because this is resolved by https://github.com/moby/moby/pull/35563

**Comment by riverar** [comment]
Is there a Docker-EE (Windows Server) target for this hotfix? Doesn't seem to be in yet.

**Comment by friism** [comment]
@riverar we're working on figuring that out - stay tuned

**Comment by riverar** [comment]
@friism Any updates? Seems a little premature to close the issue.

**Comment by carlfischer1** [comment]
@riverar should be in the next Docker EE engine patch release, eta mid-March
