### ISSUE TITLE
Splunk logging error

### ISSUE THREAD

**Issue by adityacs** [moby/moby#34710]
Splunk logging is enabled for swarm services. Logging is working as expected. However, we see error as below in docker daemon logs frequently.

`Post https://172.18.2.161:8088/services/collector/event/1.0: EOF"`

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:32:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:23:12 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2

**Comment by thaJeztah** [comment]
Wonder if this is a duplicate of https://github.com/moby/moby/issues/34749 / https://github.com/moby/moby/pull/34520

Are you using the "raw" mode logging option?

**Comment by adityacs** [comment]
@thaJeztah I am using "inline" option and I have tags.

**Comment by adityacs** [comment]
@thaJeztah Closing this as this becomes very old issue.
