### ISSUE TITLE
Error "cannot use s.Rdev (type int32) as type uint64 in argument to major" on MacOS

### ISSUE THREAD

**Issue by ndrewnee** [moby/moby#34726]
**Description**
Hi, I found that after [this commit](https://github.com/moby/moby/commit/2f5f0af3fdb7e9ee607a0e178dbe2af6e10cccf4#diff-3e48818ad9b0be8b26f6c130f28759a6R53) I cannot build package `github.com/moby/moby/pkg/archive` on MacOS. On line https://github.com/moby/moby/blob/9b4a616e4b3819ef062780b5fd854616be2c22bb/pkg/archive/archive_unix.go#L53 was removed type conversion of `s.Rdev` to `uint64`. It works great on Linux because `s.Rdev` is `uint64` on it, but on MacOS `s.Rdev` has type `int32`. See https://golang.org/src/syscall/ztypes_darwin_arm64.go#72

**Steps to reproduce the issue:**
1. Go to `pkg/archive`
2. Run `go build`

**Describe the results you received:**
```
./archive_unix.go:53:32: cannot use s.Rdev (type int32) as type uint64 in argument to major
./archive_unix.go:54:32: cannot use s.Rdev (type int32) as type uint64 in argument to minor
```

**My environment**
```
uname -a
Darwin Andrews-MacBook-Air.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ndrewnee/Projects/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/wm4dp9t56wl8x87qv51k0xnr0000gn/T/go-build843481590=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by yongtang** [comment]
Fixed by #34745
