### ISSUE TITLE
[Feature Request] Set network for build in docker-compose yaml

### ISSUE THREAD

**Issue by TheWolfNL** [moby/moby#34723]
Currently the --network option is available for `docker build`, It would be nice if it were also available for `docker-compose` through the yaml file.
In the yaml there is already a `build` section, my suggestion would be to add `network:`.

Related PR of initial feature
https://github.com/moby/moby/pull/27702

**Comment by thaJeztah** [comment]
Can you open this issue in the Docker Compose issue tracker? This would have to be implemented there: https://github.com/docker/compose/issues 

Let me close the issue here for housekeeping but feel free to continue the conversation
