### ISSUE TITLE
DNS lookups from a service container on a swarm overlay network without external connectivity

### ISSUE THREAD

**Issue by pboers1988** [moby/moby#34747]
**Description**

We are are experiencing performance issues on a database due to the fact that it attempts to do DNS lookups on an external server. However I was under the assumption that the internal DNS resolver of the swarm (127.0.0.11) would proxy the request to the external resolvers

**Steps to reproduce the issue:**
1. Create an overlay network with with Internal": true,
2. Attach a number of services to the network. They will be able to communicate without any issues (for example ping <servicename> from within container)
3. ping goolge.com from within a service container will result in the following log entries:

Sep  6 17:19:09 swarm-01-auto-prd dockerd: time="2017-09-06T17:19:09.352879070+02:00" level=warning msg="Connect failed: dial udp XXXXXXXXXX:53: connect: network is unreachable"

**Describe the results you received:**

Timeouts on the DNS request which causes a slow database

**Describe the results you expected:**
Proxied name resolution and no internet connectivity. This means that the Swarm resolver should respond with the google.com DNS entry.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@swarm-01-auto-prd ~]# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[root@swarm-01-auto-prd ~]# docker info
Containers: 17
 Running: 8
 Paused: 0
 Stopped: 9
Images: 64
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local local-persist
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 8f82814bulxehabaruib3hgqq
 Is Manager: true
 ClusterID: 3db8429osad9t5rn1bw3nqn66
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: xxxxxxx
 Manager Addresses:
  xxxxxxx:2377
  1xxxxxxx:2377
  xxxxxxx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.695GiB
Name: swarm-01-auto-prd.xxxxx
ID: 76TJ:KPFC:P4xxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I wonder if this was actually by design, to prevent those services from (indirectly) having external communication through DNS requests

ping @mavenugo you probably know

**Comment by sctse999** [comment]
Not sure whether this is related but go check this out.

https://github.com/moby/moby/issues/27399
