### ISSUE TITLE
Splunk logger not transmitting log data when tag is empty

### ISSUE THREAD

**Issue by JWEdwards-TCS** [moby/moby#34749]
**Description**
Running Docker with the Splunk log driver in raw mode and tag="" I don't see any data in Splunk from my application.

daemon/logger/splunk/splunk.go implies tag="" will cause the tag to be omitted and log entries will be sent to Splunk.

If I set tag="-" or some other string the logs from my application are visible in Splunk with the tag prefix.

**Steps to reproduce the issue:**
1. Have a docker image which sends some data to stdout
2. 
```
docker run --rm --log-driver=splunk \
--log-opt splunk-format=raw \
--log-opt splunk-index=lab \
--log-opt splunk-insecureskipverify=true \
--log-opt splunk-source="test" \
--log-opt splunk-token=<my splunk token>\
--log-opt splunk-url=<my splunk url> \
--log-opt tag="" \
 <imageId>
```

**Describe the results you received:**
I see logs from my application appearing in stdout.
I do not see any of those appearing in splunk

**Describe the results you expected:**
I expect Splunk to contain an exact replica of the content of stdout

**Additional information you deem important (e.g. issue happens only occasionally):**
Using 
--log-opt tag="-" \
I see entries in Splunk with the prefix "- ".

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: VSP6:DTQJ:CRIQ:JSTP:QETN:HCXZ:CHD3:YTPB:P7ZO:6DNQ:M5SE:UPWO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 31
 System Time: 2017-09-06T16:33:17.602339091Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting; it looks like this is being addressed in https://github.com/moby/moby/pull/34520,  which also contains some more information on this problem
