### ISSUE TITLE
docker compose not work with proxy

### ISSUE THREAD

**Issue by xpoveda** [moby/moby#34753]
Hi, I have ubuntu xenial 16.04.03 and the latest version of docker and docker-compose.

```
ubuntu@ubuntu:~$ docker --version
Docker version 17.06.1-ce, build 874a737

ubuntu@ubuntu:~$ docker-compose --version
docker-compose version 1.16.0, build ea60ca1

```
In my home I have this configuration and all ok (executing and build new images)
In my job I work with proxy and the execution of docker images imported from docker hub is perfect but the construction of images return error.

I have configure the proxy for docker

```
ubuntu@ubuntu:~$ systemctl show --property=Environment docker
Environment=HTTP_PROXY=http://USER:PASSWORD@PROXY_URL:PROXY_PORT/ NO_PROXY=localhost,127.0.0.1 HTTPS_PROXY=https://USER:PASSWORD@PROXY_URL:PROXY_PORT/
```

And another elements for configuration of all system 

https://gist.github.com/xpoveda/423ad0cc2c89b16bdc03937566c488cb

but the docker build not works

```
root@ubuntu:/home/ubuntu/misproyectos/PiggyMetrics# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
```
return error of accessing to debian repo.

```

root@ubuntu:/home/ubuntu/misproyectos/PiggyMetrics# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
Building statistics-mongodb
Step 1/6 : FROM mongo:3
 ---> b39de1d79a53
Step 2/6 : MAINTAINER Alexander Lukyanchikov <sqshq@sqshq.com>
 ---> Using cache
 ---> 58e4554d5e96
Step 3/6 : ADD init.sh /init.sh
 ---> Using cache
 ---> dcc72465a51c
Step 4/6 : ADD ./dump /
 ---> Using cache
 ---> 02e36b66a761
Step 5/6 : RUN chmod +x /init.sh &&  apt-get update && apt-get dist-upgrade -y &&  apt-get install psmisc -y -q &&  apt-get autoremove -y && apt-get clean &&  rm -rf /var/cache/* && rm -rf /var/lib/apt/lists/*
 ---> Running in 71755b8ca78b
Err http://deb.debian.org jessie InRelease

Err http://security.debian.org jessie/updates InRelease

Err http://repo.mongodb.org jessie/mongodb-org/3.4 InRelease

```

Here I have gist with generating new image ok without proxy.
https://gist.github.com/xpoveda/609724e0a1457190c75a732f6c88eab8

Any idea for add the proxy information and docker build (or docker-compose) works ok?

Thanks so much!!

Xavier.

**Comment by wenjianhn** [comment]
Use the --build-arg flag.
https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg

And you may also need to set the dns. e.g.

> $ cat /etc/systemd/system/docker.service.d/dns.conf 
> [Service]
> ExecStart=
> ExecStart=/usr/bin/dockerd --dns $internal_dns_ip
>

**Comment by xpoveda** [comment]
Hi Jacob, the issue is in docker-compose
```

root@ubuntu:/home/ubuntu/misproyectos/PiggyMetrics# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
Building statistics-mongodb
Step 1/6 : FROM mongo:3
 ---> b39de1d79a53
Step 2/6 : MAINTAINER Alexander Lukyanchikov <sqshq@sqshq.com>
 ---> Using cache
 ---> 58e4554d5e96
Step 3/6 : ADD init.sh /init.sh
 ---> Using cache
 ---> dcc72465a51c
Step 4/6 : ADD ./dump /
 ---> Using cache
 ---> 02e36b66a761
Step 5/6 : RUN chmod +x /init.sh &&  apt-get update && apt-get dist-upgrade -y &&  apt-get install psmisc -y -q &&  apt-get autoremove -y && apt-get clean &&  rm -rf /var/cache/* && rm -rf /var/lib/apt/lists/*
 ---> Running in 71755b8ca78b
Err http://deb.debian.org jessie InRelease

Err http://security.debian.org jessie/updates InRelease

Err http://repo.mongodb.org jessie/mongodb-org/3.4 InRelease
```

**Comment by thaJeztah** [comment]
The proxy that is specified in the systemd unit file only is used for networking of the daemon itself, but is not inherited by containers (including containers used during build).

If you need to use the same proxy inside the container, provide the proxy configuration as a build-arg (as @wenjianhn mentioned) during build, e.g.:

```
docker build --build-arg HTTP_PROXY=http://USER:PASSWORD@PROXY_URL:PROXY_PORT .
```



I don't think there's a bug at hand here, so I'll close this issue, but feel free to continue the conversation
