### ISSUE TITLE
Running Docker container gives "exec format error" after reset the instance on Google Cloud Platform

### ISSUE THREAD

**Issue by kewu1992** [moby/moby#34760]
**Description**

Running Docker container gives "exec format error" after reset the instance on Google Cloud Platform

**Steps to reproduce the issue:**
1. Starting an ubuntu instance on Google Cloud Platform:
`gcloud compute instances create test-ubuntu --image ubuntu-1404-trusty-v20170831  --image-project ubuntu-os-cloud`
2. SSH to the instance:
`gcloud compute ssh test-ubuntu`
3. (inside the instance) Install Docker:
`curl -fsSL get.docker.com -o get-docker.sh`
`sudo sh get-docker.sh`
4. Run a container:
`sudo docker run --rm busybox echo hello world`
5. (outside the instance or GCP pantheon console) Reset the instance:
 `gcloud compute instances reset test-ubuntu`
6. SSH to the instance again
`gcloud compute ssh test-ubuntu`:
7. (inside the instance) Run the same container again, the error will show up:
`sudo docker run --rm busybox echo hello world`

**Describe the results you received:**
Running container failed with the message:
standard_init_linux.go:187: exec user process caused "exec format error"

**Describe the results you expected:**
Running container should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue exists for a long time. Our guess for the root cause is that after pulling the image, Docker doesn't flush the image to disk timely. So after the ungracefully instance reset, Docker leaves file system a corrupted state. The demonstration of this is that if you run one more command `sync` before step (5) above, there is no error.

**Output of `docker version`:**

Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:43:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613GiB
Name: test-ubuntu
ID: ZVEB:JWTW:HOUM:RI5A:LJWV:CQ7T:PEX6:7RPP:6JKM:K4UI:WFX4:3BWB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This happens on Google Cloud Platform, I haven't tried on other environments. But my guess is any environment that can hard reboot instance/OS can reproduce the problem.

**Comment by AkihiroSuda** [comment]
Is this related to AUFS?
Is this reproducible if you use overlay2 or devicemapper?

**Comment by kewu1992** [comment]
I confirmed that it is reproducible using overlay2. But it seems not reproducible with devicemapper.

**Comment by tvalentyn** [comment]
Does anyone know, what is the status of this issue?

**Comment by Glydric22** [comment]
i had this error right now with docker image deployed in google cloud run

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
