### ISSUE TITLE
Docker daemon fails to start with userns-remap option

### ISSUE THREAD

**Issue by the-nw1-group** [moby/moby#34764]
**Description:**
The docker daemon fails to start when I added the userns remap option with the following error:
```
Sep 07 11:44:17 <host> dockerd[17567]: Error during uid lookup for "\"testuser": getent unable to find entry "\"testuser" in passwd database
```
Even though the user is present in `/etc/passwd`, and `getent` returns the following:
```
$ getent passwd testuser
testuser:x:10007:10007:testuser for user remap:/dev/null:/usr/sbin/nologin
```

**Steps to reproduce the issue:**
1. add user with `sudo useradd -s /usr/sbin/nologin -M -d /dev/null -c "testuser for user remap" testuser`
2. add to both `/etc/subgid` and `/etc/subuid`:
```
testuser:231072:65536
```
3. modify docker daemon start up to include `--userns-remap="testuser:testuser"`
4. reload daemon configuration `sudo systemctl daemon-reload`
5. start docker daemon `sudo systemctl start docker`

**Describe the results you received:**
Docker daemon fails to start with
```
Sep 07 11:44:17 <host> dockerd[17567]: Error during uid lookup for "\"testuser": getent unable to find entry "\"testuser" in passwd database
```

**Describe the results you expected:**
Docker daemon starts

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
(with --userns-remap option removed):
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
(with --userns-remap option removed):
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-204660330-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.68GB
 Data Space Total: 107.4GB
 Data Space Available: 104.7GB
 Metadata Space Used: 6.226MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.141GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702GiB
Name: vm-pe-tst00
ID: YGKS:SQHV:RS6U:26F5:FU3O:A5A5:YDYG:NUGF:K7CC:7SJ5:RYXC:MSKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ uname -a
Linux <host> 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
I've also tried with "real" users (i.e. those with a login shell, and home directory), but that also fails in the same manner

**Comment by thaJeztah** [comment]
If you specified these options in a systemd unit file; Does it work if you remove the quotes around `testuser:testuser`?

**Comment by the-nw1-group** [comment]
Thanks - that seems to be working. Can't think why I didn't try that myself.

**Comment by thaJeztah** [comment]
Great that it worked! It's a bit confusing, but the reason for that is that on the command line, the shell takes care of removing the quotes, whereas in a unit file, no shell is involved, so the quotes are passed as part of the value.

Great to hear it's resolved:+1:

**Comment by ndubbala** [comment]
> If you specified these options in a systemd unit file; Does it work if you remove the quotes around `testuser:testuser`?

How to place in systemd unit file ?

**Comment by ndubbala** [comment]
I am getting below error actually :

Error during gid lookup for "appadm": getent unable to find entry "appadm" in group database

**Comment by ndubbala** [comment]
> I am getting below error actually :
> 
> Error during gid lookup for "appadm": getent unable to find entry "appadm" in group database
> 
> Could you please let me know how docker namespaces works ?

Issue is resolved after creating appadm group.
