### ISSUE TITLE
Docker daemon becomes defunct after repeating "Waiting for /var/run/docker.sock", and upstart can't restart

### ISSUE THREAD

**Issue by davidxia** [moby/moby#34768]
On a percentage of our hosts we experience the docker daemon entering a defunct state and Upstart is unable to start a new instance of the process because it thinks the old one is still running. We've found no way to clean up the defunct process besides restarting the instance.

This is on Ubuntu 14.04 with kernel 3.16.0-77-generic and docker version 1.12.3. We’ve upgraded some hosts to docker 17.05.0 and 17.06.0 and see the same problems there.

We run the same OS/kernel/docker packages on bare metal environment and also Google Compute Engine, and we only ever seem to see this problem on GCE. On GCE we run a custom built machine image.

Unlike https://github.com/moby/moby/issues/5618, we never actually see the kernel crash. We do see output in dmesg like `unregister_netdevice: waiting for ... to become free` however. 

```
sudo dmesg 
...

[91882.997802] unregister_netdevice: waiting for veth5896f99 to become free. Usage count = 1
[91893.093827] unregister_netdevice: waiting for veth5896f99 to become free. Usage count = 1
[91903.185827] unregister_netdevice: waiting for veth5896f99 to become free. Usage count = 1
```

**Steps to reproduce the issue:**

We can't reliably reproduce. A container or the daemon shutting down triggers the issue, like when we deploy a new version of an image. We noticed the daemon's logs print "Waiting for /var/run/docker.sock" over and over when shutting down, e.g.:

```
time="2017-08-23T15:32:01.826264736Z" level=info msg="Processing signal 'terminated'"
time="2017-08-23T15:32:01.826473336Z" level=debug msg="starting clean shutdown of all containers..."
...
time="2017-08-23T15:32:16.826620649Z" level=error msg="Force shutdown daemon"
time="2017-08-23T15:32:16.826749312Z" level=debug msg="libcontainerd: containerd connection state change: SHUTDOWN"
INFO[603925] stopping containerd after receiving terminated
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
```

This led us to think that https://github.com/moby/moby/issues/9605 might be the cause, since we were running 1.12.3 at the time, but we have tried newer versions like 17.05.0 but still see the same behavior.

We’ve tried to collect stacktraces from the daemon as mentioned in #9605 with `sudo kill -SIGUSR1 $(pidof dockerd)` but it  doesn't work on defunct dockerd processes.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 58.73 GiB
Name: my-host
ID: WW7H:M3AM:6Q3Q:O6P2:N6K3:2GCM:WBVR:UBMV:BEHK:JYAG:BSK7:M5IZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

Our docker configuration via upstart looks like the following:

```
/usr/bin/dockerd -H=unix:///var/run/docker.sock -H=tcp://127.0.0.1:2375 -H=tcp://10.99.0.1:2375 -b=mybridge0 --dns=10.99.0.1 --dns-search=... --log-level=debug --storage-driver=aufs --raw-logs
```

“mybridge0” is a custom bridge interface we have created on 10.99.0.1 with a netmask of 255.255.255.0.

**What other ways can I debug what's causing this? What other logs can I provide?**

**Comment by davidxia** [comment]
cc @mattnworb @caipre @mavenraven

**Comment by jdelamar** [comment]
Just starting seeing this issue as well. Running docker on Debian Stretch, different docker version. 

Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by davidxia** [comment]
Closing as dupe of https://github.com/moby/moby/issues/5618#issuecomment-318681443

**Comment by davidxia** [comment]
May be related: https://bugzilla.kernel.org/show_bug.cgi?id=81211
