### ISSUE TITLE
Can´t specify memory limit in docker run for docker version 17.07.0-ce, build 8784753

### ISSUE THREAD

**Issue by brucejee** [moby/moby#34776]
When docker run with memory limit, it output oci runtime error. I found related thread [here](https://github.com/moby/moby/issues/34046), and update kernel version to 3.10.0-514.el7.x86_64, and then fix this problem.
You can use these commands to determine if your problem is the case:
```
[root@mesos-node1 ~]# docker run -itd --name test1 nginx
It output container id.
[root@mesos-node1 ~]# docker run -itd --name test2 -m 20m nginx
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused "read init-p: connection reset by peer"".
```

My docker and kernel version as follows:
> Docker version 17.07.0-ce, build 8784753
> Kernel Version: 3.10.0-123.el7.x86_64
> Operating System: CentOS Linux 7 (Core)

@cpuguy83 @tiborvass I post a new issue here, thanks for your quick answer.

**Comment by thaJeztah** [comment]
This error was also mentioned here: https://github.com/opencontainers/runc/issues/1547

@cyphar @crosbymichael any thoughts?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
