### ISSUE TITLE
Dockerfile CMD doesn't understand ARG variables

### ISSUE THREAD

**Issue by dejayc** [moby/moby#34772]
Similar to #5509.

I want to be able to say the following, without relying upon environment variables:

```
ARG PATH=/var/run/nowhere
CMD cat ${PATH}
```

I would like the following consequences of `CMD` to occur:

- `docker inspect container | grep -A5 Cmd` would reveal:
   ```
   "Cmd": [
       "/bin/bash",
       "-c",
       "cat /var/run/nowhere"
   ]
   ```
- No matter what environment variable PATH is present at runtime, it won't interfere with my intended CMD.
- I can craft indirect variable interpolation:
   ```
   ARG COMMAND="echo 'Hello, ${USER}'"
   CMD ${COMMAND}
   ```

**Comment by thaJeztah** [comment]
This is a duplicate of https://github.com/moby/moby/issues/18492 - environment vars in `CMD` and `ENTRYPOINT` are evaluated at runtime; changing that would be a huge breaking change so not something that can be done (see https://github.com/moby/moby/issues/18492#issuecomment-317495201).

Closing for the reason above, but happy to provide more information if needed

**Comment by dejayc** [comment]
@thaJeztah - ARG variables are evaluated at build time.  Are they not considered build-time variables, but rather run-time environment variables?  If so, for what purpose?

I propose ARG variables have their values injected into each Dockerfile directive at build time.  E.g.:

```
ARG NAME=happy-cat
USER ${NAME}
CMD echo Hello, ${NAME}
```

gets translated into:
```
USER happy-cat
CMD echo Hello, happy-cat
```

Each ARG variable should have its value search-and-replaced into any subsequent instance of ARG appearing within a Dockerfile directive.

For circumstances when an ENV variable is defined with the same name as an ARG variable, all subsequent references to the variable should be treated as an ENV reference, not ARG reference:

```
ARG NAME=happy-cat
USER ${NAME}
CMD echo Hello, ${NAME}

ENV NAME=${NAME}
CMD echo Hello, ${NAME}
```

gets translated into:
```
USER happy-cat
CMD echo Hello, happy-cat

ENV NAME=happy-cat
CMD echo Hello, ${NAME}
```

Does this clarify the request?

**Comment by thaJeztah** [comment]
`ARG` sets build time environment variables; its not a templating feature; what you're describing is a templating engine, which could easily be done outside of docker, and could even be a simple shell command, like below:

```bash
export NAME=happy-cat

docker build . -f -<<EOF
FROM alpine
USER ${NAME}
CMD echo Hello, ${NAME}

ENV NAME=${NAME}
CMD echo Hello, ${NAME}
EOF
```

**Comment by dejayc** [comment]
@thaJeztah thanks for the explanation.  Is there a particular reason why ARG is implemented via environment variables?

I understand how easy it is to build a templating solution for pre-parsing Dockerfiles.  My point is, do you really want to make each and every advanced Docker user need to do that, when instead, build-time arguments could instead just be implemented the right way?

**Comment by thaJeztah** [comment]
They were implemented like that because there was a need to be able to specify environment variables at build time, without those environment variables being baked in the image at runtime; for example, to set `HTTP_PROXY` during build because the build environment requires a proxy; such environment variables are obviously no use to the person _running_ the image, hence should not be persisted in the image

**Comment by dejayc** [comment]
@thaJeztah, what do you think of my proposal that ARG variables _not_ be treated like ENV variables unless there is as subsequent ENV definition with the same name?

> For circumstances when an ENV variable is defined with the same name as an ARG variable, all subsequent references to the variable should be treated as an ENV reference, not ARG reference:

```
ARG NAME=happy-cat
ENV NAME=${NAME}
CMD echo Hello, ${NAME}
```

That would allow Dockerfile authors to make the determination as to whether build-time directives be influenced by environment variables or not.

If you're afraid of existing Dockerfiles breaking, maybe this new functionality could be enabled via a flag to `docker build`.

**Comment by thaJeztah** [comment]
In the `HTTP_PROXY` example, that needs to be present as an environment variable, but should _not_ be baked into an image, so `ENV HTTP_PROXY=$HTTP_PROXY` would result in baking it into the image, which is exactly _not_ what `ARG` was designed for.

I really think these things belong in a preprocessor

**Comment by dejayc** [comment]
@thaJeztah I greatly appreciate your patience in explaining your point of view.  I still feel like either I don't understand how ARG works, or you're not understanding my proposal.

Let's use HTTP_PROXY as an example.

**Scenario 1:** Dockerfile author wants to set HTTP_PROXY during build time, but does not want that value to be baked into the layer.

```
ARG HTTP_PROXY=http://127.0.0.1:80
CMD curl https://www.docker.com/
```

gets translated into the following at build time:
```
export HTTP_PROXY=http://127.0.0.1:80
curl https://www.docker.com/
```

and gets translated into the following at run time:
```
curl https://www.docker.com/
```

**Scenario 2:** Dockerfile author wants to set HTTP_PROXY during build time, and wants HTTP_PROXY to also be hard-coded into the layer for run-time:

```
ARG HTTP_PROXY=http://127.0.0.1:80
CMD HTTP_PROXY="${HTTP_PROXY}" curl https://www.docker.com/
```

gets translated into the following at build time:
```
export HTTP_PROXY=http://127.0.0.1:80
HTTP_PROXY="http://127.0.0.1:80" curl https://www.docker.com/
```

and gets translated into the following at run time:
```
HTTP_PROXY="http://127.0.0.1:80" curl https://www.docker.com/
```

**Scenario 3:** Dockerfile author wants to set HTTP_PROXY during build time, and wants HTTP_PROXY to be overridden by the user during run-time:

```
ARG HTTP_PROXY=http://127.0.0.1:80
ENV HTTP_PROXY=${HTTP_PROXY}
CMD curl https://www.docker.com/
```

gets translated into the following at build time:
```
export HTTP_PROXY=http://127.0.0.1:80
curl https://www.docker.com/
```

and gets translated into the following at run time:
```
export HTTP_PROXY=http://127.0.0.1:80
curl https://www.docker.com/
```

Am I either completely misunderstanding how ARG and ENV work?  Am I missing some dramatic edge case here?  This seems like a reasonable approach towards removing the need for templating engines.

_As an aside:_ One of my pet peeves with almost every "DevOps" tool out there is that they all claim to make managing some specific digital artifact much easier, while simultaneously needing some _other_ solution to make managing the _tool_ easy.  So we now have Docker to make managing a container easy, but need another tool to make managing Docker easier.  I feel like it's a never-ending cycle of implementing one solution to manage another solution, under the guise of saving time and effort.

**Comment by psigen** [comment]
I agree with https://github.com/moby/moby/issues/34772#issuecomment-330384294.

I don't really understand why
```
ARG MY_URI=http://127.0.0.1:80
RUN curl ${MY_URI}
```
and
```
ARG MY_URI=http://127.0.0.1:80
CMD ["curl", "${MY_URI}"]
```
should have wildly different interpolation rules when they are both processed within the same engine at build-time. It seems like the `CMD` can be interpolated using exactly the same rules as are applied to `RUN` commands, except that the result would be baked into the image's `CMD` or `ENTRYPOINT` instead of being evaluated immediately.  If the value isn't supposed to be interpolated immediately, it can be escaped _in the same way that `RUN` commands are escaped to deal with this very issue_.

I completely understand that this might simply be something the `moby` team does not want to do because it is hard or would break backwards compatibility, but it seems like arguing against a preprocessor that clearly already exists and is used with a consistent set of semantics for directives other than `CMD` and `ENTRYPOINT` is a bit of a red herring?

**Comment by thaJeztah** [comment]
> I don't really understand why
>
>    ARG MY_URI=http://127.0.0.1:80
>    RUN curl ${MY_URI}
> and
>
>    ARG MY_URI=http://127.0.0.1:80
>    CMD ["curl", "${MY_URI}"]

They both follow the same rules; the variables are evaluated when the `RUN` / `CMD` is executed; which for `RUN` is during build, and `CMD` when the image is run. The second example (`CMD ["....`) uses JSON notation though, so there's no shell to evaluate the environment variable.

**Comment by psigen** [comment]
Ok, I put together a more concrete example to understand your point:
```
FROM alpine
ARG TESTVAR=foo

# If a command is interpolated inside the shell, then it should get a value
# of "bar".  If it is being interpolated outside the shell, it will have a value
# of "foo" because the interpolation has replaced the variable already.
RUN export TESTVAR=bar && echo "RUN testvar=${TESTVAR}"
CMD export TESTVAR=bar && echo "CMD testvar=${TESTVAR}"
```
```
RUN testvar=bar
CMD testvar=bar
```
Short version: both `echo` statements print `bar`.  So I think I understand that now, the interpolation is actually being performed implicitly by setting the `ARG` values into the shell environment during each specific RUN command.

However, the same interpolation happens on the `WORKDIR` command, which has no shell AFAIK:

```
FROM alpine
ARG TESTVAR=foo

WORKDIR ${TESTVAR}
RUN echo "WORKDIR=`pwd`"
```
```
WORKDIR=/foo
```
So what mechanism is performing the interpolation in these non-shell commands?

**Comment by dejayc** [comment]
> So what mechanism is performing the interpolation in the non-shell Dockerfile directives?

The world will never know.

**Comment by saites** [comment]
So, how does all this work with HEALTHCHECK?

I fear I already know the answer.

**Comment by jayarjo** [comment]
@saites what is the answer?

**Comment by dejayc** [comment]
> @saites what is the answer?

Please check back in a few years.  Docker should be developer-friendly by then.

**Comment by rqueraud** [comment]
Using `exec` in the CMD instruction, as suggested from [this stackexchange answer](https://unix.stackexchange.com/a/196053/178755), of the Dockerfile without brackets, I am able to benefit from the environment variable and the signals interception:
```bash
CMD exec node index.js --myoption ${MY_ENV_VARIABLE}
```

**Comment by kebian** [comment]
Disappointed that this issue has been seemingly abandoned.

**Comment by S-S-X** [comment]
> Please check back in a few years. Docker should be developer-friendly by then.

So, I guess few years passed by now. Any news regarding developer friendliness and maybe even some news about possible build time ARG expansion or similar?

**Comment by dejayc** [comment]
> So, I guess few years passed by now. Any news regarding developer friendliness and maybe even some news about possible build time ARG expansion or similar?

I guess that depends on your definition of "few years" 🤣

**Comment by albertodiazdorado-tng** [comment]
So did someone figure out what's the proper way of doing this without a hack?

```yaml
CDM ["node", "index.js", "--port=$PORT"]
```

?

**Comment by psigen** [comment]
For any zombie listeners, I think this discussion has moved to:
https://github.com/moby/buildkit/issues/4881
