### ISSUE TITLE
Allow anonymous volumes to be deleted automatically

### ISSUE THREAD

**Issue by dejayc** [moby/moby#34774]
`docker run --rm` provides a convenient mechanism to allow containers to be deleted automatically upon termination.

`docker rm -v container` provides a convenient mechanism to delete a container and its anonymous volume.

Please combine these features into a new `docker run` parameter that allows `docker rm -v` to be executed automatically upon termination of any `docker run --rm` container.

For example:

`docker run --rm-v`

Presently, culling of abandoned anonymous volumes is accomplished through the following hackish-type recipe:

`docker volume rm $(docker volume ls -f dangling=true -q)`

**Comment by thaJeztah** [comment]
What version of docker are you running? If I'm not mistaken, anonymous volumes are already removed automatically when using `docker run --rm ...`

**Comment by dejayc** [comment]
`Docker version 17.06.0-ce, build 02c1d87`

**Comment by cpuguy83** [comment]
`docker run --rm` does automatically remove anonymous volumes.

**Comment by dejayc** [comment]
Closing, thanks.
