### ISSUE TITLE
Please update moby package imports paths

### ISSUE THREAD

**Issue by influx6** [moby/moby#34778]
## Issue
According to your documentation page https://docs.docker.com/engine/api/#api-example example, the moby package import paths is to be used, but the code currently has not being updated, meaning there will be alot of confusion whether to stick to moby or revert back to docker based import paths, please would appreciate if the import paths for the project were update to reflect the naming change.

Language: Go

**Comment by cpuguy83** [comment]
Where does the docs mention moby?

Anyway, this is on the TODO list here: https://github.com/moby/moby/issues/35115
Closing as I don't see any moby references in the docker docs and this is covered by the referenced issue.

Thanks!
