### ISSUE TITLE
define the bridge name in the host

### ISSUE THREAD

**Issue by yankunsam** [moby/moby#34798]
when create a network by “docker create -d bridgenetwork”, is there an option to define the same name in host , like “ifconfig docker0". For now, docker assign like this “br-network_id”.

**Comment by ripcurld0** [comment]
@yankunsam can you explain more your question. I am not sure I understand it.

Thanks.

**Comment by yongtang** [comment]
@yankunsam Is this what you want?
```
 docker network create -d bridge -o com.docker.network.bridge.name=br0 network
```

**Comment by thaJeztah** [comment]
I think @yongtang's comment answers this question; given that this isn't a bug, I'll close this issue, but feel free to continue the conversation
