### ISSUE TITLE
Docker daemon error on joining swarm node - could not find local IP address - unknown network

### ISSUE THREAD

**Issue by synergiator** [moby/moby#34794]
Consider the following setup:

Three hosts are in the same (wifi) network, *all of them* using Docker ce 17.09:

- Hosts A,B,C - Debian 9 (Stretch)
- Host D - Windows 10

Then, the following has worked:

- Init swarm on A and join with B and C

 
The following is however not working:

- Join swarm at D (Windows 10) as worker with token issued from A

Error:
```
Error response from daemon: could not find local IP address: 
dial udp: address udp/2377​: network is unreachable
```

Honestly, I have even no idea how to interpret this message. Maybe this is due to network setup - but how to debug that, or what preconditions to look for? 

Any ideas?..

For example what have found out so far:

- ssh from the problematic Windows host to all other three works
- swarm init on the Windows host with advertising its IP and port 2377 does not display the system to listen on the port 2377 (why?)

**Comment by thaJeztah** [comment]
Are all nodes updated to 17.06.2? Also, did you initialize the swarm with `--advertise-addr` or without?

**Comment by 1605200517** [comment]
@thaJeztah - yes, same Docker versions, init was with --advertise-addr

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
