### ISSUE TITLE
Architecture field in Image manifest file

### ISSUE THREAD

**Issue by f2hex** [moby/moby#34803]
I am trying to figure out if the Architecture field in the Docker image manifest file is related to the target system (where the image should run) or is the architecture of the system where the image was built.
Any clear explanation?
Here is an example, I built (from sources) the `portainer/portainer:arm` image that should run on a ARM board. The `RepoTags` properly reports a the tag with the arm destination system: `portainer/portainer:arm`, in the same image manifest there is also the **Architecture** field that is set to `amd64` (it has been set using the architecture of the machine where the build was created).  This is a dump of the HTTP query response after the `docker image inspect`:
```
........HTTP/1.1 200 OK
Api-Version: 1.31
Content-Type: application/json
Docker-Experimental: true
Ostype: linux
Server: Docker/17.07.0-ce (linux)
Date: Mon, 11 Sep 2017 05:30:43 GMT
Transfer-Encoding: chunked

{"Id":"sha256:bf6413147822135e49c7bd5b4e0e9d3b7db7d0f46ca8b781ca2af7db357b5165","RepoTags":["portainer/portainer:arm"],"RepoDigests":["portainer/portainer@sha256:8293a4d4bf98786df2993df10d3875b721948d1944952bb4947cfb87d2
136efc"],"Parent":"","Comment":"","Created":"2017-01-06T20:54:54.512386505Z","Container":"2e1c4fe6a319a7508519b0d9b85c6e2b03a5df9348fcd261c4fbbfe441704d21","ContainerConfig":{"Hostname":"e30253796536","Domainname":"","Us
er":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"9000/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
n"],"Cmd":["/bin/sh","-c","#(nop) ","ENTRYPOINT [\"/portainer\"]"],"Image":"sha256:7bd7f1b1ca00ea4fe3ad504c07a3961331bcffedcaff8c601baadf2c76a02fcc","Volumes":{"/data":{}},"WorkingDir":"/","Entrypoint":["/portainer"],"On
Build":[],"Labels":{}},"DockerVersion":"1.12.5","Author":"","Config":{"Hostname":"e30253796536","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"9000/tcp":{}},"Tty"
:false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":null,"Image":"sha256:7bd7f1b1ca00ea4fe3ad504c07a3961331bcffedcaff8c601baadf2c76a02fcc","Volumes
":{"/data":{}},"WorkingDir":"/","Entrypoint":["/portainer"],"OnBuild":[],"Labels":{}},"Architecture":"amd64","Os":"linux","Size":8861828,"VirtualSize":8861828,"GraphDriver":{"Data":{"LowerDir":"/mnt/datapad/docker/overla
y2/83f40d8340fcb43d1949cebc3e9f5f50acc86c4efb0fd54bcbc1f221f70e6a5d/diff:/mnt/datapad/docker/overlay2/1b1a02f116680146ccb573748f2e63adc58ec9259970b7839a9b65d32f237317/diff","MergedDir":"/mnt/datapad/docker/overlay2/e1ee5
579380dd8beb6c562ad7e9107d2ca221780718be6516e54bccde3b38bdb/merged","UpperDir":"/mnt/datapad/docker/overlay2/e1ee5579380dd8beb6c562ad7e9107d2ca221780718be6516e54bccde3b38bdb/diff","WorkDir":"/mnt/datapad/docker/overlay2/
e1ee5579380dd8beb6c562ad7e9107d2ca221780718be6516e54bccde3b38bdb/work"},"Name":"overlay2"},"RootFS":{"Type":"layers","Layers":["sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef","sha256:0cfde93eba7dc40c3d407865005de61b6d291e5f50f13dcf3fddb431d9670061","sha256:ebb5dd56a983064a9476acca681a954bf6ee5c84b8673481d064d9861b64d51e"]},"Metadata":{"LastTagTime":"0001-01-01T00:00:00Z"}}
```
In the [Docker documentation of the image manifest v2](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list-field-descriptions) it is written: _The architecture field specifies the CPU architecture, for example amd64 or ppc64le_, so I assume that it should be target platform - am I right?
If so in that case the **Architecture** field should contains `armv7l`, `arm64` or `aarch64` instead of `amd64`...

**Comment by eugene-xie** [comment]
Architecture field should be the target target platform. Because as [OCI specifies](https://github.com/opencontainers/image-spec/blob/v1.0.0/image-index.md):
**Platform object**
This OPTIONAL property _describes the minimum runtime requirements of the image_. This property SHOULD be present if its target is platform-specific.
- **architecture**  string
This REQUIRED property specifies the CPU architecture. Image indexes SHOULD use, and implementations SHOULD understand, values listed in the Go Language document for GOARCH.

**Comment by f2hex** [comment]
Thanks @eugene-x. Then I think there is a problem in many builds that are created using a cross-platform approach where the **Architecture** field is set automatically by the build process.
