### ISSUE TITLE
Ubuntu16.04: docker-ce installation fails

### ISSUE THREAD

**Issue by ra9hur** [moby/moby#34813]
**Description**
I recently re-installed docker-ce. To test installation, the pull request for "Hello-world" fails.

**Steps to reproduce the issue:**
1. This issue is occurring on Ubuntu 16.04 native OS
2. Uninstalled previous docker version
3. Removed contents in /var/lib/docker
4. Uninstalled virtual box
5. Upgraded nvidia driver from 375 to 381.22
6. Installed docker-ce
7. Now, tesing pull request for "Hello-world" fails.

**Describe the results you received:**

Get an error:
$ sudo docker run hello-world
- Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b04784fba78d: Pulling fs layer 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/1815c82652c03bfd8644afda26fb184f2ed891d921b20a0703b46768f9755c57/data?Expires=1505174465&Signature=I9vmKzYvWSxdmnZ7V-IXIfyuvZnF6ylD2MvGQaTB5FeI7QJjefw4jVjTvdwMQcYfO~23XZK9JM0NfPfjdyQN6YYZ8ks2CEnCg2AJWaS6BPyyxsn6gXozWJklrkZ9zgB5oA8dUO5ElHV5njMPnexz9I-d9c2YN4uyHWH3bB2Z51s_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 218.248.255.164:443: i/o timeout.

**Describe the results you expected:**
- Should have downloaded hello-world image

**Additional information you deem important (e.g. issue happens only occasionally):**

- I was able to pull images 3 days back with previous installation

Output of docker version:

$ sudo docker version

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

Output of docker info:

$ sudo docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.765GiB
Name: raghu-Inspiron-3542
ID: UMKC:HM6T:HKZO:PG4L:GHBM:GSNF:JF7K:QI37:KDPO:DQVV:2KAB:ENO7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ra9hur
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

Output of dig:

$ dig dseasb33srnrn.cloudfront.net 8.8.8.8

; <<>> DiG 9.10.3-P4-Ubuntu <<>> dseasb33srnrn.cloudfront.net 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7038
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dseasb33srnrn.cloudfront.net.	IN	A

;; ANSWER SECTION:
dseasb33srnrn.cloudfront.net. 3600 IN	CNAME	bsnlrpz.
bsnlrpz.		3600	IN	A	218.248.255.164

;; AUTHORITY SECTION:
rpz.blist.org.		3600	IN	SOA	bangalorerdns1.bsnl.co.in.rpz.blist.org. hostmaster.bangalorerdns1.bsnl.co.in.rpz.blist.org. 2017090106 10800 3600 604800 86400

;; Query time: 26 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Sep 12 05:41:01 IST 2017
;; MSG SIZE  rcvd: 169

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38385
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;8.8.8.8.			IN	A

;; ANSWER SECTION:
8.8.8.8.		0	IN	A	8.8.8.8

;; Query time: 0 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Sep 12 05:41:01 IST 2017
;; MSG SIZE  rcvd: 52

**Additional environment details (AWS, VirtualBox, physical, etc.):**

1. VirtualBox-5.1 is uninstalled
2. This is a home laptop and it is not behind proxy. Assume exporting http proxy, https proxy are not relevant
3. Checked ip link. MTU values are 1500 by default
4. Have set mtu probing to 1. $ sudo sysctl -w net.ipv4.tcp_mtu_probing=1
5. Updated /etc/resolv.conf to have "nameserver 8.8.8.8" in first line

6. https link from error output does not work from the browser
    - https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/1815c82652c03bfd8644afda26fb184f2ed891d921b20a0703b46768f9755c57/data?Expires=1505174465&Signature=I9vmKzYvWSxdmnZ7V-IXIfyuvZnF6ylD2MvGQaTB5FeI7QJjefw4jVjTvdwMQcYfO~23XZK9JM0NfPfjdyQN6YYZ8ks2CEnCg2AJWaS6BPyyxsn6gXozWJklrkZ9zgB5oA8dUO5ElHV5njMPnexz9I-d9c2YN4uyHWH3bB2Z51s_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q

7. Tried accessing the above link from Windows 8.1 on the same laptop from a browser and it does not get through.

8. Referred https://github.com/moby/moby/issues/32257. Have sent a mail to docker hub  support team, but no response

I am stuck with this, for the last 3 days. Need your help to resolve this.

**Comment by jirawat001** [comment]
follow #33930

**Comment by ra9hur** [comment]
Thanks for your suggestions.

As recommended in 33930, tried specific versions of dockers (latest as well older ones) 
- 17.06, 17.05, 17.03, 1.13.1-0. The i/o time-out issue still comes up.

**Comment by ra9hur** [comment]
On the internet, all suggestions are leading to DNS fix. Tried applying  DNS fix as in the below link:
https://robinwinslow.uk/2016/06/23/fix-docker-networking-dns/#the-permanent-system-wide-fix

The Issue still shows up. 
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b04784fba78d: Pulling fs layer 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/1815c82652c03bfd8644afda26fb184f2ed891d921b20a0703b46768f9755c57/data?Expires=1505219427&Signature=L5cFNuSxBrz4eLIMH~SwoihbMNLz2JMweEqKt5Oc3rOoQoFsMwO1~Ppj~kti2r1YNAzrit0G~BZqp0LnSTs79p0AkZwacwddCMCzF4zBnaC7n8T5ud0~euiVPiep9on2UUbcULb-QkKKWjZTGFrlX5w9RgPKnc6sYVvMLXpUpVE_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 218.248.255.164:443: i/o timeout.

So, it is able to reach out to docker-hub, but times out. MTU value is by default 1500. Have tried setting this to 1000.

Have even tried -stop-timeout set to 120 seconds.

None of these helps.

**Comment by ra9hur** [comment]
If I do a curl from cmd prompt, get this error:
$ curl -v https://dseasb33srnrn.cloudfront.net:443
* Rebuilt URL to: https://dseasb33srnrn.cloudfront.net:443/
*   Trying 218.248.255.164...
* connect to 218.248.255.164 port 443 failed: Connection timed out
* Failed to connect to dseasb33srnrn.cloudfront.net port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to dseasb33srnrn.cloudfront.net port 443: Connection timed out

However, curl requests to docker.io works fine.
curl -v https://index.docker.io:443

I am assuming that the download site is down. Is there a secondary site that I can use?
If yes, how to initiate the pull request? OR while doing the build?

**Comment by thaJeztah** [comment]
218.248.255.164 looks like a completely different range than what I'm getting (but may be location specific); 

```
nslookup dseasb33srnrn.cloudfront.net
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.90
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.205
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.169
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.65
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.193
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.78
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.34
Name:	dseasb33srnrn.cloudfront.net
Address: 52.222.174.121
```

What does `nslookup dseasb33srnrn.cloudfront.net` give you? And what if you use 8.8.8.8 as DNS (`nslookup dseasb33srnrn.cloudfront.net 8.8.8.8`)?

**Comment by ra9hur** [comment]
Thanks for your suggestion. I temporarily used 8.8.8.8 as DNS by editing /etc/resolv.conf and got this working. Changes get reset once I reboot the system and that is a different problem.

This issue can be closed.

**Comment by thaJeztah** [comment]
Thanks! Good to hear that worked
