### ISSUE TITLE
Docker freezes while extracting on raspberry pi

### ISSUE THREAD

**Issue by lucaszanella** [moby/moby#34822]
```
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM resin/rpi-raspbian:latest
latest: Pulling from resin/rpi-raspbian
1e57cb80dcc0: Extracting [=============================>                     ]  29.36MB/49.32MB
98069a3d3b36: Download complete 
8ee805aa5cd9: Download complete 
e63d6eeb293a: Download complete 
e1d087c6415e: Download complete 
368f18263cdb: Download complete 
a900ba4d1a38: Download complete 
a75ec9bc76d2: Download complete 
1fe2c1f0f0bd: Download complete 
089435aeea34: Download complete
```

Then it hangs forever. SSH becomes unresponsive and I have to ask for someone to restart the board. Is there a way I can debug and find if its a problem with my raspberry, or is it really a problem on docker? I've did `curl -sSL https://get.docker.com | sh` yesterday so I have the latest possible docker on raspberry

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`

("latest possible version" is no longer true after a new release was done :smile:)

If you have more information about the type of raspberry you installed on, that may be useful as well.

/cc @alexellis

**Comment by lucaszanella** [comment]
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false


Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.9.48-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 927.3MiB
Name: raspberrypi
ID: 73DT:3NOH:OUZQ:CBT7:IEMH:VU7G:HUQM:YN6W:YEAB:3UU7:MJF7:5J5J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support

(the stopped container is a hello world, not related to the one I'm trying to extract now)

**Comment by lucaszanella** [comment]
I forgot to say that the hello world image was not extracted from anywhere, It simply runned. Every image I try to extract makes the raspberry freeze. Its running on raspbian, the raspberry is the model B

**Comment by lucaszanella** [comment]
Problem solved: turns out the power supply was not enough and the raspberry turned all the lights off in the extraction time, but did not reboot. I replaced by a 2A power supply and it worked. (simple tar extraction, however, have not frozen the raspberry with the older power supply)

**Comment by thaJeztah** [comment]
Ha! Yes that's something I wouldn't have thought of.

Good to hear it's resolved :+1:
