### ISSUE TITLE
Swarm 17.07.0 unable to join nodes

### ISSUE THREAD

**Issue by pouicr** [moby/moby#34825]
**Description**

Hi, 

Upgrade from docker-ce 17.06.2 to docker-ce-17.07.0 break my cluster.
My manager is up and running but worker (or manager) nodes cannot join it.

**Steps to reproduce the issue:**
1. install docker-ce-17.07.0 on 2 VMs (say M and W)
2. run `docker swarm init --advertise-addr=<M_public_ip>:2377` on M (get the worker join command)
3. run the join command on W

**Describe the results you received:**

`Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable`

**Describe the results you expected:**

`This node joined a swarm as a worker.`

**Additional information you deem important (e.g. issue happens only occasionally):**

I used a Terrafom+Ansible that was successfully ran many time to create clusters. 
It even appears on an existing cluster after upgrading to 17.07.0

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:43:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.07.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: eqt38cc9zdy5i15yflndsj0ze
 Is Manager: true
 ClusterID: u7yvqf60ew3r1n867bjstz2bh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.90.251.200
 Manager Addresses:
  10.90.251.200:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: swarm-mode-latest-master-0
ID: W4TM:QHM2:MWD4:52SK:XMIM:TJA5:2NCX:4WAB:77C5:TF66:WVKX:XGTD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://some-proxy:3128
Https Proxy: http://some-proxy:3128
No Proxy: localhost,172.17.42.1,.sock
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The swarm mode cluster run on KVM VMs

**Comment by thaJeztah** [comment]
Can you run other commands successfully on that worker node? The `the connection is unavailable` is quite generic, and may also indicate a connection problem with containerd.

Do the logs of the worker-node show anything useful (preferably in debug mode)?

**Comment by pouicr** [comment]
I cannot try right now but I guess it is possible since the manager node can deploy stacks.
Moreover I experienced the same issue while trying to update a 3 master cluster (17.06.2): updating one master in 17.07.0 make it appears as "down" from the 2 others master.

Best regards

**Comment by pouicr** [comment]
here is the worker node log when I try to join:

```
Sep 13 09:29:55 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:55.128769697+02:00" level=debug msg="Calling GET /_ping"
Sep 13 09:29:55 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:55.133210892+02:00" level=debug msg="Calling GET /_ping"
Sep 13 09:29:55 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:55.135908829+02:00" level=debug msg="Calling POST /v1.31/swarm/join"
Sep 13 09:29:55 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:55.136755661+02:00" level=debug msg="form data: {\"AdvertiseAddr\":\"\",\"Availability\":\"\",\"DataPathAddr\":\"\",\"JoinToken\":\"*****\",\"ListenAddr\":\"0.0.0.0:2377\",\"RemoteAddrs\":[\"10.90.251.200:2377\"]}"
Sep 13 09:29:55 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:55.236455609+02:00" level=error msg="failed to retrieve remote root CA certificate" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable" module=node
Sep 13 09:29:57 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:57.243206124+02:00" level=error msg="failed to retrieve remote root CA certificate" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable" module=node
Sep 13 09:29:59 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:29:59.249661398+02:00" level=error msg="failed to retrieve remote root CA certificate" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable" module=node
Sep 13 09:30:01 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:30:01.257467305+02:00" level=error msg="failed to retrieve remote root CA certificate" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable" module=node
Sep 13 09:30:01 swarm-mode-latest-slave-1 systemd: Started Session 167 of user root.
Sep 13 09:30:01 swarm-mode-latest-slave-1 systemd: Starting Session 167 of user root.
Sep 13 09:30:03 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:30:03.263950698+02:00" level=error msg="failed to retrieve remote root CA certificate" error="rpc error: code = Unavailable desc = grpc: the connection is unavailable" module=node
Sep 13 09:30:05 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:30:05.264275246+02:00" level=error msg="cluster exited with error: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
Sep 13 09:30:05 swarm-mode-latest-slave-1 dockerd: time="2017-09-13T09:30:05.264681565+02:00" level=error msg="Handler for POST /v1.31/swarm/join returned error: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
```


I have no issue running other `docker` commands (run, pull...)

Regards

**Comment by thaJeztah** [comment]
@dperny @aluzzardi @nishanttotla any ideas?

**Comment by nishanttotla** [comment]
Is it that the Docker API isn't exposed on the address provided with the join command?

**Comment by pouicr** [comment]
Looks good on the master side:

```
[root@swarm-mode-latest-master-0 ~]# netstat -peanut | grep docker
tcp6       0      0 :::2375                 :::*                    LISTEN      0          37825      13337/dockerd       
tcp6       0      0 :::2377                 :::*                    LISTEN      0          53367      13337/dockerd       
tcp6       0      0 :::7946                 :::*                    LISTEN      0          53384      13337/dockerd       
udp6       0      0 :::7946                 :::*                                0          53385      13337/dockerd  
```

**Comment by pouicr** [comment]
(wrong button...)
From slave:
```
[root@swarm-mode-latest-slave-1 ~]# telnet 10.90.251.200 2377
Trying 10.90.251.200...
Connected to 10.90.251.200.
Escape character is '^]'.
```

**Comment by pouicr** [comment]
My environment have proxy constraints, is there any changes regarding host communication?
Not many people seems to react here... probably environment related?

**Comment by pouicr** [comment]
Proxy issue...
While it wasn't needed in version < 17.07.0, it is now required to configure daemon proxy according your infra. Adding master ip in no_proxy (docker daemon service) fix the issue.

**Comment by Leslie-Fang** [comment]
Thanks a lot. I have encountered the same problem. Edit the /etc/systemd/system/docker.service.d/http-proxy file, and add the manage node's ip into the no_proxy would solve the problem.

**Comment by thaJeztah** [comment]
> While it wasn't needed in version < 17.07.0, it is now required to configure daemon proxy according your infra.

@pouicr do you have more information on this? I'm not aware (but possibly missed a change) that this behaviour was deliberately modified in 17.07; if so, we should look into that (could've been a bug-fix, but needs a mention somewhere then in that case)

**Comment by pouicr** [comment]
Hi, 
Sorry no more information... Just a fact we've noticed.
I am interesting to know more...
It is a bit more painful for automation (but probably mandatory for some infra?)

**Comment by Remigius2011** [comment]
same here when upgrading from 17.06.2-ce to 17.09.0-ce (new stable version that just arrived today and sneaked in via my ansible scripts) - adding the hosts mutually to their NO_PROXY environment fixed the issue.

**Comment by Remigius2011** [comment]
in any case, having to add all potential swarm participant nodes mutually to their NO_PROXY environment variable just lets me ansible some more...

**Comment by sathieu** [comment]
Can somebody point to what was changed?

**Comment by thaJeztah** [comment]
Possibly related to gRPC upstream now supporting proxies; https://github.com/grpc/grpc-go/commit/955c867061e3b1a5b8f6f07d1efcf1b69af043d8

**Comment by kleptog** [comment]
Is this issue going to be fixed? Because this means that if you want to add a new master to a swarm you have to restart all the other master nodes to update their no_proxy list (no_proxy cannot use wild-cards). Which is really very annoying.

To be concrete: in the Docker daemon a http_proxy variable was set because a proxy is needed to access the DockerRegistry. This unexpectedly caused all internal gRPC traffic to go via the outgoing proxy, causing much mayhem.  If you know the IP of your future nodes upfront you can mitigate it a bit, but it is very annoying.

AFAICS gRPC support the concept of a "proxy mapper" which would allow Docker control whether the proxy is used or not, and thus automatically exclude other nodes.

**Comment by Remigius2011** [comment]
I agree with @kleptog . This problem basically makes a swarm cluster static if it's behind a proxy, which eliminates several quite useful features (elasticity etc.).

**Comment by sathieu** [comment]
Plus the no_proxy variable doesn't accept network+mask (i.e 10.20.2.0/24) or network wildcards (10.20.3.*). See https://golang.org/src/net/http/transport.go?s=9950:10007#L1210. This is per no_proxy spec.

**Comment by kylejw1** [comment]
This issue is affecting my cluster as well - and all related bugs I can find are marked closed.  Is this functionality going to be left as is?

**Comment by thaJeztah** [comment]
@kylejw1 see https://github.com/docker/swarmkit/pull/2419

**Comment by kylejw1** [comment]
Thank you, I missed that.

**Comment by geigev** [comment]
I am still experiencing this issue in 17.11 (https://github.com/docker/docker-ce/tree/17.11). Isn't this version supposed to contain a fix for this?

**Comment by thaJeztah** [comment]
Which release candidate? rc1, rc2 or rc3?

**Comment by geigev** [comment]
@thaJeztah thanks for quick response, rc3

**Comment by tanweer-ali** [comment]
I don't have a proxy between my manager and worker.

manager ip: 192.168.2.103
worker ip : 192.168.2.102

I ssh in to the worker from the manager node and issue the swarm join command: 

docker swarm join --token SWMTKN-1-578xkqwthbmkn7fnegmtx4pn73h0wh5qgvzw03gb50xmg1t0qu-a1k7myosfu4zkruw7y1x81l1k 192.168.2.103:2377

**Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable**

How to fix this? 
Can't understand how you guys solved this after following this thread???

Please help

**Comment by daniel347x** [comment]
Just a quick comment to mention that I've now lost 30 hours trying to overcome this problem (running both manager and worker as VirtualBox v5.2.6r120293) - it would be helpful to have a comment indicating how to overcome this.

**Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable**

Sadly, my work is at a standstill, but I'll keep on' fightin...

**Comment by jasonodonnell** [comment]
I fixed this on CentOS7 by adding firewalld rules:

```bash
sudo firewall-cmd --add-port=2376/tcp --permanent  
sudo firewall-cmd --add-port=2377/tcp --permanent  
sudo firewall-cmd --add-port=7946/tcp --permanent  
sudo firewall-cmd --add-port=7946/udp --permanent  
sudo firewall-cmd --add-port=4789/udp --permanent
sudo systemctl restart firewalld
```

**Comment by fanjieqi** [comment]
Hey guys, I just init the swarm in my current mac, which have the same issue with you.
```
$ docker swarm init --advertise-addr 192.168.99.100
```
If I create a manager1 firstly, then ssh into it and init the swarm, it works.
```
$ docker-machine create manager1
$ docker-machine ip manager1
\# 192.168.99.104
$ docker-machine ssh manager1

docker@manager1:~$ docker swarm init --advertise-addr 192.168.99.104
```

Now, I create a worker1, then ssh into it and join it to the swarm cluster, it works perfectly.
```
$ docker-machine create -d virtualbox worker1
$ docker-machine ssh worker1

docker@worker1:~$ docker swarm join --token SWMTKN-1-1s06e6ubid2axcj3h9bo06smlj32jhqp74pj1wkmflb3f0x5pi-cde5dm1xdzo3eum3s7lrj96aa 192.168.99.104:2377
```

So, the problem is that we might not init the swarm in our current macos, but in a manager we create.

I've published this post on [Docker forum](https://forums.docker.com/t/swarm-init-issue/28667/9#post_9).

**Comment by Boopathiraj** [comment]
I use docker Version 1.13.1 and VMs are based on OracleVMbox
I faced the same trouble when join the worker to master. Error is "Error response from daemon: rpc error: code = Unavailable desc = grpc: the connection is unavailable"

Firstly, I disabled firewalls, disabled selinux ad finally diasabling IPV6 helped.
