### ISSUE TITLE
same dockerfile produces 1.2gb / 3.4gb images on different boxes 

### ISSUE THREAD

**Issue by liweys** [moby/moby#34830]
**Description**

I have a dockerfile which contains jdk8+hadoop+spark+some libs. The built image size is 1.2gb which is reasonable.

I copied the binaries and the dockerfile to another machine. The built image size becomes 3.4gb this time!

Everything is the same, why the size is different so much, any advice?

**Comment by liweys** [comment]
I resolved the issue. A tar.gz file changed to a new version, though still a bit strange as the new gz file is only 100M bigger than the older, the image size increased 2g.

**Comment by thaJeztah** [comment]
You may want to check the installed version on the machine that created the big image; there was a bug in docker 17.06.0 that extracted local TAR files when using `ADD` (fixed in 17.06.1 and up)
