### ISSUE TITLE
local container cant use a swarm network

### ISSUE THREAD

**Issue by gabrielfsousa** [moby/moby#34839]
version: 17.06.1-ce
how a local container uses a swarm network ?

i have this error:

> docker: Error response from daemon: Could not attach to network my-s: rpc error: code = 7 desc = network my-s not manually attachable

my-s is my overlay searm network

**Comment by wershlak** [comment]
Swarm networks aren't locally attachable by default. `docker network inspect <network> | grep -i attach` will show false. Use `--attachable` when you create the network and you should be able to attach a local container.

**Comment by thaJeztah** [comment]
Thanks for answering @wershlak - that's indeed correct; to allow regular containers to attach to a swarm-scoped network, you need to create the network with `--attachable`.

I'm closing this issue because it's not a bug, but feel free to continue the conversation
