### ISSUE TITLE
Assert error on 17.06.2-ce

### ISSUE THREAD

**Issue by mtucker502** [moby/moby#34840]
Docker daemon keeps restarting. I see this assert error in the logs.

/var/run/docker.sock is up
time="2017-09-13T14:48:45.034921032-04:00" level=info msg="libcontainerd: new containerd process, pid: 15919"
time="2017-09-13T14:48:46.042117255-04:00" level=info msg="[graphdriver] using prior storage driver: aufs"
time="2017-09-13T14:48:46.089100852-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-09-13T14:48:46.089275930-04:00" level=warning msg="Your kernel does not support swap memory limit"
time="2017-09-13T14:48:46.089322864-04:00" level=warning msg="Your kernel does not support cgroup rt period"
time="2017-09-13T14:48:46.089348821-04:00" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2017-09-13T14:48:46.089424806-04:00" level=warning msg="mountpoint for pids not found"
time="2017-09-13T14:48:46.089632077-04:00" level=info msg="Loading containers: start."
panic: assertion failed: write: circular dependency occurred

goroutine 1 [running]:
github.com/docker/docker/vendor/github.com/boltdb/bolt._assert(0xc42087f100, 0x1a4027d, 0x23, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:1026 +0xf6
github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).write(0xc4203fe4d0, 0xc42087f000)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:226 +0x3ad
github.com/docker/docker/vendor/github.com/boltdb/bolt.(*node).spill(0xc4203fe4d0, 0xc42024a3d8, 0xa)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/node.go:378 +0x28f
github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc42060c8d8, 0x891f963, 0x2673f80)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/bucket.go:571 +0x17b
github.com/docker/docker/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc42060c8c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/docker/docker/vendor/github.com/boltdb/bolt.(*DB).Update(0xc42008f4a0, 0xc42024a7c8, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/boltdb/bolt/db.go:602 +0xf7
github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicPut(0xc420236050, 0xc4203fe3f0, 0x64, 0xc42047a910, 0xb, 0x40, 0x0, 0x0, 0xc42011e000, 0x0, ...)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:402 +0x259
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic(0xc420057f80, 0x262de80, 0xc42087a4e0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:415 +0x266
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).updateToStore(0xc420440300, 0x262de80, 0xc42087a4e0, 0xc4204d3d40, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:237 +0x9a
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0xc420440300, 0x1a028ce, 0x4, 0x1a028b2, 0x4, 0xc4205440c0, 0x40, 0xc42000e0c8, 0x1, 0x1, ...)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:824 +0x459
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc420094480, 0xc42038d200, 0xc420595800, 0xc420094480, 0xc4202888b0, 0xc420595800, 0xc4205957d0)
        /go/src/github.com/docker/docker/daemon/daemon_unix.go:748 +0x60e
github.com/docker/docker/daemon.(*Daemon).restore(0xc420094480, 0x2609e40, 0xc420094480)
        /go/src/github.com/docker/docker/daemon/daemon.go:288 +0x777
github.com/docker/docker/daemon.NewDaemon(0xc42038d200, 0x262ed00, 0xc4204552b0, 0x261b200, 0xc42044d6c0, 0xc42010c5a0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:747 +0x2116
main.(*DaemonCli).start(0xc42045a960, 0x0, 0x1a25828, 0x17, 0xc42038d200, 0xc4204450c0, 0xc4200eb290, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:214 +0x1223
main.runDaemon(0x0, 0x1a25828, 0x17, 0xc42038d200, 0xc4204450c0, 0xc4200eb290, 0x1, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x8c
main.newDaemonCommand.func1(0xc420353d40, 0xc420454d30, 0x0, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x6f
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420353d40, 0xc42000c130, 0x1, 0x1, 0xc420353d40, 0xc42000c130)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420353d40, 0x17cdda0, 0x1, 0xc420454cc0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420353d40, 0xc420454cc0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0xe6

I did not see any one else report this issue.

**Comment by mtucker502** [comment]
Reinstalling docker-ce had no effect.
I uninstalled docker-ce, deleted /var/lib/docker and then installed docker-ce.

Now the docker daemon at least is starting. Now I need to find a way to move the containers over.

**Comment by mtucker502** [comment]
I moved back the original /var/lib/docker directory and deleted /var/lib/docker/network/files/local-kv.db and docker runs.

So it seems something in local-kv.db is causing the crash. I've saved the file but for now am just rebuilding my containers that have port mappings.

**Comment by thaJeztah** [comment]
can you post the output of `docker version` and `docker info` ? Anything in the system logs before this error occurred?

ping @fcrisciani any ideas? would that local-kv.db file be of interest to see what happened?

**Comment by asryanserg** [comment]
> I moved back the original /var/lib/docker directory and deleted /var/lib/docker/network/files/local-kv.db and docker runs.
> 
> So it seems something in local-kv.db is causing the crash. I've saved the file but for now am just rebuilding my containers that have port mappings.



> I moved back the original /var/lib/docker directory and deleted /var/lib/docker/network/files/local-kv.db and docker runs.
> 
> So it seems something in local-kv.db is causing the crash. I've saved the file but for now am just rebuilding my containers that have port mappings.

Removing local-kv.db resolved the issue and without any problems with containers

**Comment by thaJeztah** [comment]
closing for housekeeping; docker 17.06-ce reached eol

**Comment by ascillato** [comment]
Hi,

I know this is an old issue, but I want to ask for a feature request on this. I have latest docker-ce installed on a raspberry pi 3 and I had a power drop while it was starting and this exact issue happened to me. By removing **local-kv.db** resolved the issue and without any problems with containers.

My feature request is that in case of docker can't start because of:
`panic: assertion failed: write: circular dependency occurred`
can the start up routine remove the **local-kv.db** and try to start over?

Can be this done? It would make the system even more reliable. Thanks.

**Comment by rdlmda** [comment]
Had the same issue on 19.03.12, build 48a66213fe
Removing local-kv.db also resolved the issue for me

**Comment by 529279917** [comment]
I had the same issue, can not got any more info. In the end I resolved it bu removing local-kv.db.
