### ISSUE TITLE
docker pull window 10 image make error

### ISSUE THREAD

**Issue by Myeongjoon** [moby/moby#34848]
Host OS : window 10 (new surface pro)
Docker image OS : window nanoserver.
To build window image followed this microsoft [link](https://docs.microsoft.com/ko-kr/virtualization/windowscontainers/quick-start/quick-start-windows-10).
But `docker pull microsoft/nanoserver` command returned this error.

> C:\Users\joon8\Desktop>docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
5cd49617cf50: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\4e7ba26ae694140a43b3e923a8c2191998af75bdc982c9237bd2fd31f5647d91: The parameter is incorrect.

I think I followed official docs well.
Is there any solution?

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by Myeongjoon** [comment]
- `docker version` output 
 

> Client:
>  Version:      17.06.2-ce
>  API version:  1.30
>  Go version:   go1.8.3
>  Git commit:   cec0b72
>  Built:        Tue Sep  5 19:57:19 2017
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      17.06.2-ce
>  API version:  1.30 (minimum version 1.24)
>  Go version:   go1.8.3
>  Git commit:   cec0b72
>  Built:        Tue Sep  5 19:59:47 2017
>  OS/Arch:      windows/amd64
>  Experimental: true
 - `docker info` output

> C:\windows\system32>docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 17.06.2-ce
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd json-file logentries splunk syslog
> Swarm: inactive
> Default Isolation: hyperv
> Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
> Operating System: Windows 10 Pro
> OSType: windows
> Architecture: x86_64
> CPUs: 4
> Total Memory: 15.93GiB
> Name: DESKTOP-UI3N44R
> ID: ACDB:DWLY:EUBA:LLJU:LF3N:RLR6:5YWM:UTLP:CL5K:WNSR:JTG6:5S5K
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: -1
>  Goroutines: 19
>  System Time: 2017-09-19T13:12:35.1051411+09:00
>  EventsListeners: 0
> Registry: https://index.docker.io/v1/
> Experimental: true
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by Myeongjoon** [comment]
**step to reproduce error**
 - install docker in docker [homepage](https://www.docker.com/) 
 - Start hyper-V and reboot.
 - `docker pull microsoft/nanoserver` and this make erorr.

**purpose**
 - To set up docker window develop environment(container).
 - I want contribute docker. So I followed [set up for developement on windows](https://docs.docker.com/opensource/project/software-req-win/#3-git) and It need window container.

**Comment by Myeongjoon** [comment]
BitLocker is active.
As mentioned in  https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/355#issuecomment-275418795, deactivated vaccine and error disappeared.

>C:\windows\system32>docker pull microsoft/nanoserver
> Using default tag: latest
> latest: Pulling from microsoft/nanoserver
> bce2fbc256ea: Pull complete
> 5cd49617cf50: Pull complete
> Digest: sha256:8b4ab2db6fd93063b50233a17fc0084015a3fcc774d7b17528bb4baf97aa7949
> Status: Downloaded newer image for microsoft/nanoserver:latest

Thank you.

**Comment by thaJeztah** [comment]
You're welcome!
