### ISSUE TITLE
Debian Buster release missing

### ISSUE THREAD

**Issue by drasko** [moby/moby#34854]
Current Debian Testing is codenamed Buster. It is missing from install distros here: https://download.docker.com/linux/debian/dists/

**Comment by thaJeztah** [comment]
Yes we should probably start building for buster in the next release, now that stretch is the new stable. I opened a pull request here: https://github.com/docker/docker-ce-packaging/pull/50

**Comment by thaJeztah** [comment]
Let me close this one in favour of https://github.com/docker/for-linux/issues/102, as this is a docker issue, not moby
