### ISSUE TITLE
Overlay network connection problem

### ISSUE THREAD

**Issue by shawnlsa** [moby/moby#34853]
**Description**

We have two machine (A and B) joined the same cluster, and we create an overlay network in the machine. When we quickly stop and start containers joined the overlay in A and B, we met the connection problem.

**Steps to reproduce the issue:**
machine A：
docker network create -d overlay test_ovl
docker run -itd --name c1 --net test_ovl alpine /bin/sh 

machine B：
docker run -itd --name c2 --net test_ovl alpine /bin/sh 

A：
docker exec -it c1 ping -c3 c2

B:
docker stop c2

A:
docker run -itd --name c3 --net test_ovl alpine /bin/sh 
docker exec -it c1 ping -c3 c3

**Describe the results you received:**
The last step "docker exec -it c1 ping -c3 c3",  c1 **can not** ping c3 immediatly.

**Describe the results you expected:**
The last step "docker exec -it c1 ping -c3 c3",  c1 should ping c3 successfully immediatly.

**Additional information you deem important (e.g. issue happens only occasionally):**
After generally 5 minutes, c1 can ping c3 successfully.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Can you make sure to update to the current version (stable 17.06.2, or edge 17.07)? Docker 17.06 contains a lot of fixes for networking, and 17.05 is EOL, and no longer maintained

**Comment by shawnlsa** [comment]
Docker 17.06 fix the problem, thanks!

**Comment by thaJeztah** [comment]
Perfect!
