### ISSUE TITLE
Out of memory on windows container,

### ISSUE THREAD

**Issue by JaxLgj** [moby/moby#34860]
**Steps to reproduce the issue:**
1. Run docker for windows.
2. Switch to windows containers.
3. Run container.

**Describe the results you received:**

OutOfMemoryException
![result](https://user-images.githubusercontent.com/24977009/30467888-6387e8ac-9a1a-11e7-98bc-db9d34ba5e91.PNG)

**Describe the results you expected:**
No exception.

**Additional information you deem important **
Here is my code:
`static void Main(string[] args)
        {
            int count = 2048 * 1024;
            List<byte[]> list = new List<byte[]>(count);
            for (int i = 0; i < count; i++)
            {
                list.Add(new byte[1024]);
                Console.WriteLine((long)(i + 1) / 1024 + "MB");
            }
            Console.WriteLine(list.Count);
            Console.ReadLine();
        }`
**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:47 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
C:\Users\111>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.06.2-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.903GiB
Name: DESKTOP-8HO8BQH
ID: EGP5:UGMM:HTWN:LI3W:KRCA:UJA4:WJL3:R2JP:4KHA:VXUG:52L7:XYOT
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 38
 System Time: 2017-09-15T13:34:32.1201138+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Please provide the exact steps to reproduce and what happened; is the container killed, the host? Is the error occurring inside the container or on the host? How is the container started, and what image is used to run the container?

**Comment by riverar** [comment]
@JaxLgj I can't reproduce this. What version of .NET did you target? The information @thaJeztah asked for is required too.

**Comment by JaxLgj** [comment]
@riverar Thanks and I have resolved this problem, use "-m 2G" when I run that image. I think switch to windows containers, the default memory is 1G.

**Comment by thaJeztah** [comment]
Looks like this was resolved then
