### ISSUE TITLE
Missing bridge network details with docker swarm and stack deploy

### ISSUE THREAD

**Issue by davidhiendl** [moby/moby#34871]
**Description**
When deploying a Swarm (built-in) service via `docker stack deploy -c docker-compose.yml somestackname` the resulting service containers do not contain any information on the docker `bridge` network despite receiving a bridge network IP.
However when creating the service with `docker service create ...` the containers do have the bridge network details.

**Steps to reproduce the issue:**
1. Put node into swarm mode
2. Create `docker-compose.yml` file, example:
```yml
version: '3.3'

services:

    server:
        image: nginx
        ports:
          - "80:80"
        networks:
          - net
        deploy:
            mode: replicated
            replicas: 1

networks:
    net:
        driver: overlay
```
3. Deploy file: `docker stack deploy -c docker-compose.yml some-stack-name`
4. `docker inspect ...` the resulting containers

**Describe the results you received:**
A list of the container networks, **without** the bridge network properly listed and information on it provided.
This is despite the container actually receiving and IP address (checked via `docker exec ...` and `ip addr`) 
```json
      "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "98b0ec4128dde1641b3a1997bcfccb5ccd154f745fb25bc0aac39ef5764323f5",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/98b0ec4128dd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ingress": {
                    "IPAMConfig": {
                        "IPv4Address": "10.255.0.15"
                    },
                    "Links": null,
                    "Aliases": [
                        "50c3d87ef23a"
                    ],
                    "NetworkID": "la2e20f73a0ms1t4qrokd1im7",
                    "EndpointID": "6ccf97a8dfd7e44826e7576c6fc179d17cd15271e6c802dad56456dca58165cd",
                    "Gateway": "",
                    "IPAddress": "10.255.0.15",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:ff:00:0f",
                    "DriverOpts": null
                },
                "mysql_net": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.0.8"
                    },
                    "Links": null,
                    "Aliases": [
                        "50c3d87ef23a"
                    ],
                    "NetworkID": "zrdezpx2fm1kdglwsd7d3qtnf",
                    "EndpointID": "08ffb3f6d233c02750ec5a07711f7839eb8862aeff80c1fc879b4ea294da1374",
                    "Gateway": "",
                    "IPAddress": "10.0.0.8",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:08",
                    "DriverOpts": null
                }
            }
        }
```

**Describe the results you expected:**
The network being properly registered and it's address and other information being provided.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happend to me **only** when using `docker stack deploy ...`, when using `docker service create --name testnginx nginx` the docker inspect command correctly contains all information for the bridge and lists it as a network.

**Output of `docker version`:**
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:58:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 13
 Running: 9
 Paused: 0
 Stopped: 4
Images: 61
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local local-persist
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: <<removed>>
 Is Manager: true
 ClusterID: <<removed>>
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.99.0.10
 Manager Addresses:
  10.99.0.10:2377
  10.99.0.11:2377
  10.99.0.12:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8GiB
Name: <<<removed>>
ID: <<<removed>>>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: <<<removed>>>
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Vultr nodes
- Debian Stretch

**Possible Workaround:**
As I require the containers to properly list their `bridge` network for my monitoring agent to automatically discover their IP address and connect to them I've simply added the following to my compose files:
```yml
...
services:
  someservice:
    networks:
    - net
    - bridge
...
networks:
  bridge:
    external: true
```

**Comment by BretFisher** [comment]
I'm not sure what your asking @davidhiendl, in your first example the service will get a eth and IP on the overlay default network (ingress), not bridge which isn't a default for swarm. Are you wanting to use the default swarm-wide overlay network?

**Comment by davidhiendl** [comment]
@BretFisher My point is that the behavior is inconsistent. When creating with `docker stack create -c docker-compose.yml` the bridge is not assigned. When creating the same service with `docker service create ...` it is assigned.

**Comment by BretFisher** [comment]
It would help to see the exact commands you're running for creating the service and network, then show `ip addr` and `inspect` info... then do the same details for stack. From what I can tell in OP not all those details are shown. I'm trying to recreate your scenario.

**Comment by davidhiendl** [comment]
You are right, the problem is somewhat difficult to reproduce. I've tested this again on an other swarm just now and it did *not* show the same inconsistency. That got my curious so I tested it on all 5 of my current swarms and I even created a new test swarm. None of them except the first one I originally experienced the problem with a few days ago attach the bridge network in any case (which is expected behavior .

However that one swarm behaves inconsistently (just checked again).

Here is what I used:
```bash
docker network create --driver overlay test-nginx_net
docker service create \
    --replicas 1 \
    -p 1234:1234 \
    --network test-nginx_net \
    --name test-nginx_server \
    nginx 
```

and with compose: `docker stack deploy -c docker-compose test-nginx`:
```yaml
version: '3.3'

services:

    server:
        image: nginx
        networks:
          - net
        ports:
          - "1234:1234"

networks:
    net:
        driver: overlay
```

**Comment by davidhiendl** [comment]
I've dismantled and completely reset the swarm that was having this issue (`rm -rf /var/lib/docker`) and now it seems to act correctly: It does not attach the `bridge` network anymore. Still unclear what caused this issue as it was setup with the same Ansible script used to re-build it and the other nodes.

@BretFisher Should I close this? As it apparently was an anomaly.

**Comment by BretFisher** [comment]
If you can't recreate it on another system then I'd say close, and if it
shows back up you can always come back :)

**Comment by thaJeztah** [comment]
let me go ahead and close for now, but feel free to continue the conversation; thanks!
