### ISSUE TITLE
Documentation issue - docker: Error response from daemon: driver failed programming external connectivity on endpoint redis

### ISSUE THREAD

**Issue by rajcspsg** [moby/moby#34873]
**Description**

Looks like documentation for docker network is outdated.
Trying to learn docker network using the examples provided [here](https://docs.docker.com/engine/userguide/networking/work-with-networks/#link-containers-without-using-user-defined-networks).

**Steps to reproduce the issue:**
1.create docker network 
    `$ docker network create -o "com.docker.network.bridge.host_binding_ipv4"="172.23.0.1" my-network`
    bf64e40499c8c1644c8ed3b743f25dc72866ae81294cec92d86e216fbb9a0ab5

2. inspect the network.

    `$ docker network inspect my-network`

```
[
    {
        "Name": "my-network",
        "Id": "bf64e40499c8c1644c8ed3b743f25dc72866ae81294cec92d86e216fbb9a0ab5",
        "Created": "2017-09-16T23:48:31.063263608-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.host_binding_ipv4": "172.23.0.1"
        },
        "Labels": {}
    }
]
```

3. run redis in this network

    `$ docker run -d -P --name redis --network my-network redis`

```
Unable to find image 'redis:latest' locally
latest: Pulling from library/redis
065132d9f705: Pull complete 
fc32c7d9b0f4: Pull complete 
ad60cc6fa431: Pull complete 
b21c99d8cf03: Pull complete 
357908014789: Pull complete 
e27e1cb0ca43: Pull complete 
Digest: sha256:fe77356e6e8d5c5200b9800e50ae71147efdc446a3cc4f601c607fbfd218015e
Status: Downloaded newer image for redis:latest
f103a6542e50ecd5bb257b9c68214537f1392069d94ddfbf19416af3e54cc640
docker: Error response from daemon: driver failed programming external connectivity on endpoint redis (1339918305c70f9e6416a5d499b5f6b8691450c9a3d310c8f7c3495c34a931ee): Error starting userland proxy: listen tcp 172.23.0.1:32777: bind: cannot assign requested address.
```

**Describe the results you received:**

docker should be able to run redis successfully in provided network.

**Describe the results you expected:**

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint redis (1339918305c70f9e6416a5d499b5f6b8691450c9a3d310c8f7c3495c34a931ee): Error starting userland proxy: listen tcp 172.23.0.1:32777: bind: cannot assign requested address.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:31:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce-rc1
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:33:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 21
Server Version: 17.09.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.9-300.fc26.x86_64
Operating System: Fedora 26 (Twenty Six)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.794GiB
Name: localhost.localdomain
ID: R3ET:HF5C:ILYK:S46A:5OYO:E67Z:GACB:AFJE:5V7G:EY3V:GBMX:IPTB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical - Fedora 26

**Comment by thaJeztah** [comment]
I think additional information is needed there; I guess that the specified IP-address must be available on the [docker0 bridge](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/)

@fntlnz I'm bad at this; would you be able to have a look? 😊

**Comment by fntlnz** [comment]
@rajcspsg It does not work because you're trying to do is to bind ports to a **not existing** interface on the host.

The example in the documentation is showing that with the `docker network create -o "com.docker.network.bridge.host_binding_ipv4"="172.23.0.1" my-network` command you can create a network that will assign ip addresses to the underlying containers using the IPAM class resulting from your docker inspect `172.18.0.0/16`.

The IP address it uses for port binding `172.23.0.1` is the actual ip address that will be used to nat exposed ports, in your case the `-P` flag exposes all the ports, so you should get a similar behavior than doing an underlay network with macvlan or ipvlan.

However the ip address `172.23.0.1` is just an example and in your case does not correspond to a real ipv4 address in the host.

The documentation in this case has *no ways to know the address* you want to use since it doesn't know your network configuration outside anything managed by docker itself.

In fact it states:

```
The following example uses -o to bind to a specific IP address when binding ports, then uses docker network inspect to inspect the network, and finally attaches a new container to the new network.
```

A possible improvement could be to transform that sentence to something like:

```diff
+ The following example uses -o to bind to a specific IP address available on the host when binding ports, then uses docker
- The following example uses -o to bind to a specific IP address when binding ports, then uses docker 
network inspect to inspect the network, and finally attaches a new container to the new network.
+ Please note that the ip address used in the example, `172.23.0.1` is an actual ip address available on a network interface in the host.
```
