### ISSUE TITLE
awslogs driver doesn't handle Partial messages

### ISSUE THREAD

**Issue by jahkeup** [moby/moby#34887]
**Description**

When log lines exceed the internal copier buffer size of [16K](https://github.com/moby/moby/blob/5c10698d5c5223f9cb49704124be592e3d39d0df/daemon/logger/copier.go#L13), the copier chunks the message and flags the message as a Partial line and expects that the log driver would perform any necessary work to reassemble. The awslogs driver does not have this capability today and treats each message, regardless of Partial status, as an entire line. I propose we introduce one of the following solutions:

1. Partial handling in the awslogs driver and buffer the line internally up to CloudWatch Logs' limits.

2. Sized Loggers that may indicate a different buffer size is desired by the backing log driver so that larger lines may be delivered to the driver without chunking.

Solution 1 (#34889) maintains the current copier behavior wherein the drivers must reconstruct log lines as appropriate to their uses. Each line is buffered in the driver and uses an expanding slice up to its maximum (which is enforced and handled correctly already).

Solution 2 (#34888) allows the driver to indicate to the copier that a larger buffer should be used. This enables the driver to perform less partial line reconstruction work without granting unbounded memory consumption and leads to a smaller number of buffer allocations needed.

**Steps to reproduce the issue:**

1. Log a long log line (>16K bytes) to the awslogs driver (using it as [documented](https://docs.docker.com/engine/admin/logging/awslogs/)).
2. Check CloudWatch Logs and see multiple entries for the single long line.

**Describe the results you received:**

When logging a line longer than the logger buffer size of 16K, the line is split into chunks of 16K.

**Describe the results you expected:** 

I expected to see a single line as a single event up to the [CloudWatch Logs service limit](https://github.com/moby/moby/blob/5c10698d5c5223f9cb49704124be592e3d39d0df/daemon/logger/awslogs/cloudwatchlogs.go#L46) for the event payload.

**Additional information you deem important (e.g. issue happens only
occasionally):**

This behavior still remains in the `github.com/moby/moby/daemon/logger/awslogs` package today and both solutions were recently rebased.

**Output of `docker version`:**

Using development instance to swap out daemons, this is from [master](https://github.com/moby/moby/commit/c5c0702a4d523071b3e41a13c233b6ec9e261b06) :

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   c5c0702a4
 Built:        Mon Sep 18 19:16:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

Using development instance to swap out daemons, this is from [master](https://github.com/moby/moby/commit/c5c0702a4d523071b3e41a13c233b6ec9e261b06) :

```
Containers: 30
 Running: 5
 Paused: 0
 Stopped: 25
Images: 2
Server Version: 17.06.0-dev
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 1.35GB
 Data Space Total: 23.35GB
 Data Space Available: 22GB
 Metadata Space Used: 1.528MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 23.64MB
 Thin Pool Minimum Free Space: 2.335GB
 Udev Sync Supported: false
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 1c81e2a794c6e26a4c650142ae8893c47f619764
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.43-17.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: ip-172-31-29-173
ID: JXKV:VXGJ:UNDH:T6GD:S4I2:VKY7:S5Q7:7ZPM:BZ7R:4EH3:K4BR:HY7A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 Instance: t2.small

**Comment by samuelkarp** [comment]
My preference is Solution 2 (https://github.com/moby/moby/pull/34888) as it avoids additional copying and avoids complicating the logger implementation even more.

**Comment by gsn-wtorla** [comment]
Is there an ETA for a fix for this? Due to large Java stack errors, we're running into the 16k boundary and it has been causing issues for us. Thank you

**Comment by jahkeup** [comment]
@gsn-wtorla we're undergoing code review in #34888
