### ISSUE TITLE
corrupted double-linked list: Apache2 process exits

### ISSUE THREAD

**Issue by benjaminpick** [moby/moby#34885]
**Description**
Since some weeks, at seemingly random intervals, these errors appear in the log and the generated HTML page is empty (blank page) or incomplete:

```
server_1        | *** Error in `apache2': corrupted double-linked list: 0x00000027ee302850 ***
server_1        | 172.17.0.1 - - [18/Sep/2017:12:55:56 +0000] "GET /index.php?id=533 HTTP/1.1" 200 5240 "-" "Mozilla/5.0 etc."
server_1        | [Mon Sep 18 12:55:57.169811 2017] [core:notice] [pid 1] AH00051: child pid 26 exit signal Aborted (6), possible coredump in /etc/apache2

```

I have also seen sometimes:
```
*** Error in `apache2': munmap_chunk(): invalid pointer: 0x00000074221ba4e0 ***
```

There was a similar issue here: https://github.com/moby/moby/issues/30433 but in my case, it is not  dockerd that crashes.
I have seen the same error ( *** Error in `php': corrupted double-linked list: ) sometimes when calling the php-binary inside the container.

**Steps to reproduce the issue:**
Hard to reproduce. However it always appears when I 
1. flush all typo3 caches and
2. call a certain page. 
This is highly CPU and memory intensive.

I am using this image:
https://github.com/benjaminpick/docker-php-apache-base
with this docker-compose.yml:
https://gist.github.com/benjaminpick/99d30cfa2be6a5b711ff8c1d5844f3c8

I have tried updating docker, apache/php without success. On the production system, the same pages render fine.

**Describe the results you received:**
Wait some seconds, then see a page where a part of the HTML has not been generated.

**Describe the results you expected:**
Wait some seconds, then see the correct page.

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 169
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.764GiB
Name: 
ID: ZNHX:G5GQ:A5Z5:EXVN:6FJJ:47VM:IMKR:A5ES:6SSU:5OEV:PZ3X:TCPV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Can you help me to find the root cause of this?
If you have any idea how to generate more relevant debug output, let me know.

**Comment by fntlnz** [comment]
That sounds like a memory corruption at php side, to verify that I would run the httpd binary under valgrind:
```
 valgrind --tool=memcheck --num-callers=30 --log-file=httpd.log /your/path/to/httpd -X
```

If the server has any memory error it will certainly appear in the `httpd.log` file.

Before than running valgrind against the httpd binary against `httpd` check if it has been stripped.

**Comment by benjaminpick** [comment]
Thanks for the tip - indeed downgrading the PHP version made this error go away. So probably this is not a docker issue, I will try to do as you said and file a bug at the PHP tracker eventually. Closing this for now.
