### ISSUE TITLE
[Q] docker service create --update-monitor includes --stop-grace-period?

### ISSUE THREAD

**Issue by destebanm** [moby/moby#34883]
Hi!

Should the --update-monitor be greater than --stop-grace-period to monitorize the update process?

I mean, does --update-monitor time start counting while task is shutting down or it starts to count when the new task is starting?

Thanks!

**Comment by thaJeztah** [comment]
/cc @aaronlehmann @mstanleyjones 

haven't dived into this yet, but we may want to document the sequence somewhere

**Comment by aaronlehmann** [comment]
It starts counting when the new task is starting.

**Comment by destebanm** [comment]
@aaronlehmann Thanks!
