### ISSUE TITLE
Support container stopping in Swarm mode (for Serverless)

### ISSUE THREAD

**Issue by jovizhangwei** [moby/moby#34892]
Hi,

As we known, serverless is quite valuable for many cloud customers, and container stopping is a key  functionality in serverless implementation, in order to restart container faster when new request comes in.

If we want make swarm mode to lifting serverless, we need make service to be a one shot container by setting "--restart-condition none", but this is not enough, we still need a mechanism to stop container in service layer, not just create and remove.

Big thanks to any ideas on this issue.

**Comment by cpuguy83** [comment]
`docker scale <service>=0`?

**Comment by jovizhangwei** [comment]
@cpuguy83  I tried command "docker scale <service>=0", and then scaled the service to 1, but the container restarted with a new container, it's totally different with "docker stop"

We've seen many Serverless implementation depends on container stopping functionality, it's really good if swarm mode would have this feature.

**Comment by cpuguy83** [comment]
Swarm will always give you a new container. Task states go one direction by design.
