### ISSUE TITLE
build docker-ce 17.06 on s390x RHEL failed.

### ISSUE THREAD

**Issue by wpeng102** [moby/moby#34905]
I want build a docker-ce 17.06 (code from https://github.com/docker/docker-ce/tree/17.06) dynamic binary on s390x,  but meet several issues. 

1) when I run **make rpm** under docker-ce, meet the following build error.
docker build -t rpmbuild-centos-7/s390x -f centos-7/Dockerfile.s390x centos-7
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/test/docker-ce/components/packaging/rpm/centos-7/Dockerfile.s390x: no such file or directory

2) when I run **make rpm** under  docker-ce/components/engine dir, meet the following error:

---> Making bundle: build-rpm (in bundles/17.06.2-ce/build-rpm)
Using test binary docker
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/17.06.2-ce/build-rpm/docker.sock --storage-driver devicemapper --pidfile bundles/17.06.2-ce/build-rpm/docker.pid --userland-proxy=true
...........................................................
error: daemon at unix:///go/src/github.com/docker/docker/bundles/17.06.2-ce/build-rpm/docker.sock fails to 'docker version':
Client:
 Version:      unknown-version
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/s390x
Cannot connect to the Docker daemon at unix:///go/src/github.com/docker/docker/bundles/17.06.2-ce/build-rpm/docker.sock. Is the docker daemon running?
---> Making bundle: .integration-daemon-stop (in bundles/17.06.2-ce/build-rpm)

**Comment by wpeng102** [comment]
I only build out dockerd,  it need link libapparmor.so.1.  But the dockerd from official package does not need link that library.  Does any one can share the reason?

**Comment by wpeng102** [comment]
append more information:

check bundles/latest/build-rpm/docker.log

time="2017-09-20T08:43:23.677421427Z" level=debug msg="[graphdriver] trying provided driver: devicemapper" 
time="2017-09-20T08:43:23.677992296Z" level=debug msg="devicemapper: driver version is 4.33.0" 
time="2017-09-20T08:43:23.678017558Z" level=error msg="devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a more recent version of libdevmapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options" 
time="2017-09-20T08:43:23.678812671Z" level=debug msg="Cleaning up old mountid : start." 
Error starting daemon: error initializing graphdriver: driver not supported


append docker info on my host:

[root@platcon1 engine]# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 56
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:4-1586034-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.89GB
 Data Space Total: 107.4GB
 Data Space Available: 3.874GB
 Metadata Space Used: 18.45MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.129GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.10.0-327.36.1.el7.s390x
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: s390x
CPUs: 2
Total Memory: 7.693GiB
Name: platcon1
ID: N62S:YVLH:B5BI:GR6A:FCIJ:ONNK:FY3H:RGGX:XRAJ:AHG2:UBVM:35UK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

**Comment by thaJeztah** [comment]
You need the top-level `make rpm` in the docker/docker-ce repository, but s390x builds (and the scripts to build those rpm's) are currently only part of Docker EE, so the Dockerfiles and scripts to build those are not in the Docker CE repository, which is a private repository. You can add your own Dockerfile for s390x in the directory structure to try and build for s390x

**Comment by AkihiroSuda** [comment]
Support for s390x was dropped after release of 18.06: https://download.docker.com/linux/static/stable/s390x/
