### ISSUE TITLE
docker daemon appears to be stuck, docker ps, docker info hanging

### ISSUE THREAD

**Issue by JennyLawrance** [moby/moby#34901]
Docker daemon appears to be stuck.
Docker commands such as docker info, docker ps, docker run, docker logs all appear to get stuck.

**Steps to reproduce the issue:**
We launch customer configured docker images, the docker daemon appears to get stuck occasionally.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens occasionally.

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**
```
Command gets stuck.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure service running containers.

Detailed logs:
journalctl -u docker.service
http://jlawnotes.azurewebsites.net/daemonlogs.txt

utput of kill -SIGUSR1 on docker daemon
data:
http://jlawnotes.azurewebsites.net/daemon-data_log.txt

output of kill -SIGUSR1 on docker daemon
stacks:
http://jlawnotes.azurewebsites.net/goroutine_stacks_log.txt

The issue appears similar to https://github.com/moby/moby/issues/30437, but I checked the call stacks in the output to the one referenced, and feel that it is different.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
