### ISSUE TITLE
The description for Event ID 1 from source docker cannot be found. 

### ISSUE THREAD

**Issue by asmi85** [moby/moby#34917]
Hello, I am trying to a create a docker swarm cluster on windows server 16. I initiallized the swarm manager, but when i tried to run docker swarm join on docker worker. I keep on seeing 

 ```
The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

cluster exited with error: rpc error: code = 4 desc = context deadline exceeded
``` 

Do anyone knows this ?

**Comment by ameyag** [comment]
The error pertaining to event ID not been found is pertaining to Eventing Issue. It seems that WS2016 doesn't have docker event log hive `HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker`

Please set up with the hive with following cmdlet and restart so that the swarm join error is descriptive:

```
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker" /v CustomSource /t REG_DWORD /d 0x1 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker" /v TypesSupported /t REG_DWORD /d 0x7 /f
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\docker" /v EventMessageFile /t REG_SZ /d "C:\Program Files\Docker\dockerd.exe" /f
```

**Comment by thaJeztah** [comment]
Thanks @ameyag 


let me close this ticket, because the underlying error;

```
cluster exited with error: rpc error: code = 4 desc = context deadline exceeded
```

Is quite generic, and can have many causes; this ticket is quite old and doesn't have additional information to make it actionable
