### ISSUE TITLE
Failure to install container role on Windows results in utterly unhelpful error message

### ISSUE THREAD

**Issue by carlfischer1** [moby/moby#34920]
Docker on Windows Server 2016 requires the Hyper-V and Container roles to be installed. If the Container role is not installed the error message in the debug logs is a failure in a HNS (Host Networking Service) call and provides no clue that the Container role is missing.

**Steps to reproduce the issue:**
1. Install a WS2016 machine/VM
2. Install the Hyper-V role (`Add-WindowsFeature -Name Containers`
3. Install Docker (https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server or https://docs.docker.com/engine/installation/windows/docker-ee/)

**Describe the results you received:**
dockerd starts and runs normally

**Describe the results you expected:**
dockerd fails to start with the following message in the debug log:
`Error starting daemon: Error initializing network controller: hnsCall failed in Win32: Class not registered (0x800040154)`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Doesn't run in this case, but I was using `17.10.0-ee-preview-1`, commit `139fcd3`

**Output of `docker info`:**

Doesn't run in this case

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VMs
Per @dineshgovindasamy there is no check for the Container role being present

**Comment by thaJeztah** [comment]
ping @msabanal @friism
