### ISSUE TITLE
Support for mounting images on host, make changes on host, and commit changes as new image.

### ISSUE THREAD

**Issue by pauldotknopf** [moby/moby#34931]
Something like this has already been discussed [here](https://github.com/moby/moby/issues/18701), but I would like to bring it up again as I have found a new use case for it.

So, about my use case. I'd like to build an immutable Arch Linux image for all my machines. I'd like to build my images (gaming/development/children) using the layering model of Docker. I will have a script that exports a layer to a squashfs for ```/``` booting on bare-metal, with a ```tempfs``` overlayed for immutable, but writable changes during a boot session.

When creating a new layer, I'd like to mount a Docker image on my host, make my changes, and create a new Docker image (with inherited layers preserved).

I will be deploying these Docker images to my registry for history/backup/rollback support and sharing the images across my machines in different regions.

I have no intention of ever running any Docker images I create, but I'd like to leverage the image/layering/registry features it provides.

So, is it possible?

If not, I will have to run a container with the image I intend to inherit from, access the mounted file system (/var/lib/docker/somewhere...), and then commit the container changes in a new image. Rinse repeat for other layers.

**Comment by thaJeztah** [comment]
I still don't see this belonging in the core functionality of this project; more something to be implemented in an external tool, so -1 from my side.

/cc @unclejack @runcom

**Comment by unclejack** [comment]
This can be achieved through `docker build`. The images can be exported on the host and new layers can be produced through the process described above.

Once the tarballs with the changes to be made are available, they can be added via `docker build` using the `ADD` instruction which would extract the tarballs.

**Comment by thaJeztah** [comment]
I'll go ahead and close this one, but feel free to continue the discussion
