### ISSUE TITLE
Flaky test DockerSuite.TestUpdateKernelMemoryUninitialized

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#34938]
Seen failing here https://jenkins.dockerproject.org/job/Docker-PRs-s390x/5858/consoleFull

FAIL: docker_cli_update_unix_test.go:139: DockerSuite.TestUpdateKernelMemoryUninitialized
19:34:08 
19:34:08 docker_cli_update_unix_test.go:149:
19:34:08     c.Assert(err, check.NotNil)
19:34:08 ... value = nil
19:34:08 
19:34:09 
19:34:09 ----------------------------------------------------------------------

**Comment by tophj-ibm** [comment]
There seems to be something wrong with the checkKernelVersion as this node is greater than 4.6 and should be hitting the other case

**Comment by thaJeztah** [comment]
@tophj-ibm Should we add some debugging lines to that, or do you have easy access to a machine to test that code on?

**Comment by tophj-ibm** [comment]
I'm attempting to debug it on my z machine but not having much luck. I'll submit a test PR so I can run it against the CI machine

**Comment by thaJeztah** [comment]
Thanks! I looked at the code, but nothing stood really out, so indeed curious where it broke
