### ISSUE TITLE
Docker can't find private image then it can

### ISSUE THREAD

**Issue by andy9775** [moby/moby#34942]
**Description**
I'm having an issue launching a compose based stack. Using `docker stack deploy...` I'm starting a stack running on docker swarm in AWS. When executing `docker stack ps <name>` I see multiple attempts to launch each service with each failing to find the image. This happens for a few minutes until the services start working at random. The image comes from a private repo hosted on docker hub and I'm using `--with-registry-auth` to start the service. The same thing happens when updating a service via `docker service update ...` - it fails and retries for 1-2 minutes then it starts working randomly.

**Steps to reproduce the issue:**
1. Create a private docker image
2. setup a docker swarm on AWS via cloud.docker.com
3. create a docker compose file for your image(s)
4. start the service via:
```
docker stack deploy <stack_name> \
  --with-registry-auth \
  --compose-file ./docker-cloud.yml
```
5. Optionally update a running service using:
```
docker service update \
  --with-registry-auth \
  --image <image_name> \
  <service_name>
```

**Describe the results you received:**
When executing `docker stack ps <stack_name>` the output displays failed attempts to start or update a service. The message states that the image cannot be found. After 1-2 mnutes (and multiple failures) the service starts/updates as expected.

The issues isn't that it doesn't work at all - it fails for a while then it starts up. 

**Describe the results you expected:**
The service should start/update without failure

**Additional information you deem important (e.g. issue happens only occasionally):**
I've been tracking this over the past few months and it's gotten more and more frequent. It used to fail to find some images, but now it fails to find any private image. 
**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 32
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: j6y092qiccidx5hz1kqwwq7w0
 Is Manager: true
 ClusterID: qgtwvsqfmx7czsu8lmaf1e4qn
 Managers: 3
 Nodes: 10
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.23.51
 Manager Addresses:
  172.31.1.61:2377
  172.31.23.51:2377
  172.31.35.126:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951 GiB
Name: ip-172-31-23-51.eu-west-1.compute.internal
ID: M22B:VU64:GR33:BNZL:XBYS:TVQV:VZHZ:BWFU:RRFC:MJ7M:I6VK:GDQL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 138
 Goroutines: 360
 System Time: 2017-09-22T14:58:59.017182157Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 region=eu-west-1
 availability_zone=eu-west-1b
 instance_type=t2.small
 node_type=manager
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running docker swarm set up through cloud.docker.com on AWS

**Comment by thaJeztah** [comment]
When you `docker stack deploy` (or `docker service create` / `docker service update`), docker will check for the latest version of the image you specified, and pull that version of the image on each host that the service is deployed. When starting that container, the image may not be present on that host, in which case a message is printed ("image cannot be found"), at which point the image will be pulled.

Pulling the image may take some time, depending on how big the image is, and networking speed on the host. After pulling is complete, the service is started.

The delay you're seeing is that image downloading/pulling has not completed yet.

**Comment by andy9775** [comment]
That makes sense, but is it normal for it fail and re-attempt multiple times? I'll see multiple containers start and fail rather than just one or two. I'd expect it to try and pull the image and if it's not available to wait to download and then restart the container or kill the container, wait for the image and then re-try and not just try-fail-try-fail... until the image has downloaded. How will this impact the `max_failure_ratio` or `max_attempts`?
(this could, of course, be a feature/improvement).

Further, if I force the update without changing the image the same issue occurs. If the image hasn't changed it should be available on the node and the container should just restart no?

**Comment by thaJeztah** [comment]
I think the fail may be used to trigger the pull, but I don't know the exact implementation (@nishanttotla may be able to fill me in on this).

> Further, if I force the update without changing the image the same issue occurs. If the image hasn't changed it should be available on the node and the container should just restart no?

Updating a service spins up new tasks (containers); those may be ending up on a node that does not yet have the correct version of the image; but perhaps you'd be able to verify that by watching which nodes the tasks end on to exclude there's a bug at hand

**Comment by andy9775** [comment]
> Updating a service spins up new tasks (containers); those may be ending up on a node that does not yet have the correct version of the image; but perhaps you'd be able to verify that by watching which nodes the tasks end on to exclude there's a bug at hand

Sure thing. Next time I run an update I'll keep track of which node the service was running on, which nodes it failed on and which node it ended up on.

**Comment by thaJeztah** [comment]
Thanks! Let me close this issue for housekeeping, but feel free to comment if you have more information

**Comment by andy9775** [comment]
hey @thaJeztah unfortunately I haven't had a chance to update the service however I am facing another (related) issue.

My stack consists of 5 service 1 of which is dependent on the other 4. When starting the swarm the 4 service fail to find the image for a few minutes again (it's been getting longer and longer lately) however they eventually startup. The final service attempts to start after the others start running and it faces the same issue (No such image: ...) however I've been waiting for up to an hour without the last service starting.

I've also attempted to stop the stack and start it up again with the same results. The docker status page isn't reporting any issues nor is the twitter account
