### ISSUE TITLE
docker info enhancement - specify Plugins *in use*

### ISSUE THREAD

**Issue by gnomestar** [moby/moby#34949]
Currently, `docker info` lists out all plugins currently available, whether embedded drivers or plugin pulled to the environment in the newer format. 

```
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay store/weaveworks/net-plugin:2.0.1
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
```

*Problem statement*
Output of this command doesn't specify which plugin is actually configured and in use in the environment. This makes for a less targeted support/debugging understanding.

*Solution*
Create additional output option of `docker info` which specifies the plugin in use.

**Comment by cpuguy83** [comment]
I definitely don't think `docker info` is the right place to put this information.
`docker plugin inspect` could show if it's in use or not...

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
