### ISSUE TITLE
docker info command doesn't list new logging plugins

### ISSUE THREAD

**Issue by gnomestar** [moby/moby#34950]
Currently, `docker info` lists out all plugins currently available, whether embedded drivers or plugin pulled to the environment in the newer format. 

```
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay store/weaveworks/net-plugin:2.0.1
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
```

*Problem statement*
Output of this command shows a Network plugin which has been pulled from Docker Store. However, it is not showing a logging plugin, similarly pulled from Docker Store, as available.

*Solution*
Ensure that logging plugins are visible in the environment. 

Note that this plugin from Sumo Logic was installed to validate this functionality -- 
https://store.docker.com/plugins/sumologic-logging-plugin

**Comment by ripcurld0** [comment]
@gnomestar I think this problem is not related to Docker.
In order to be displayed as a plugin, the plugin itself needs to [register](https://github.com/moby/moby/blob/master/daemon/logger/factory.go#L102-L104). You can see for example how syslog [does it](https://github.com/moby/moby/blob/master/daemon/logger/syslog/syslog.go#L57).

@thaJeztah WDYT?

**Comment by thaJeztah** [comment]
I think there's a difference here between built-in drivers, and (v2) plugins; let me /cc @cpuguy83  @anusha-ragunathan here, who are more familiar with this part

**Comment by cpuguy83** [comment]
Oh boy, I can't remember if this is supposed to be listed or not...

**Comment by anusha-ragunathan** [comment]
v1 plugins are supposed to be listed as part of `docker info`
v2 plugins are supposed to be listed only as part of `docker plugin ls`. 

An exception to this behavior is network plugins and they decided to be listed in both places! 

So, in this case Sumo logic plugin v2 logging driver not being listed in `docker info` is expected.

**Comment by thaJeztah** [comment]
@anusha-ragunathan should we make the output more clear on this (e.g. print it as "legacy plugins", or remove the network plugins from this list?)

**Comment by anusha-ragunathan** [comment]
Network pluginsv2 had some problems removing themselves from this list. That's why we decided to leave it as-is. For now, lets leave it as-is. If we see more confusion around this, then lets revisit
