### ISSUE TITLE
Add --timeout argument to docker service scale

### ISSUE THREAD

**Issue by qweeze** [moby/moby#34963]
When scaling service down with `docker service scale` a task is being killed after 1 second.
Is it possible to make this timeout configurable, same as in `docker-compose scale --timeout`?

**Comment by thaJeztah** [comment]
This should already work if you use the `--stop-grace-period` option (or [`stop_grace_period`](https://docs.docker.com/compose/compose-file/#stop_grace_period) in the docker compose file);

For example:

Create a service with a grace period of 30 seconds; this service is running `sh`, which is known to ignore a graceful "stop" signal:

```bash
$ docker service create --stop-grace-period=30s -t --replicas=2 --name shellie busybox
```

Scale the service:

```bash
$ docker service scale shellie=1
```

And notice that there's still two instances running:

```bash
$ docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
eeecfb6015f7        busybox:latest      "sh"                     About a minute ago   Up About a minute                       shellie.1.uvv48xa7duj1rtmbwgpknovy9
be890da334ca        busybox:latest      "sh"                     About a minute ago   Up About a minute                       shellie.2.spizkr8l8p3h3mejal7gl4jre
```


After 30 seconds, the second instance will be killed.


```bash
$ docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
be890da334ca        busybox:latest      "sh"                     About a minute ago   Up About a minute                       shellie.2.spizkr8l8p3h3mejal7gl4jre
```


I _do_ notice there seems to be a bug in `docker service ps`; after scaling the service to `1`, `docker service ps` _immediately_ shows just a single task (even though there are still two tasks running). I'll open a separate issue for that and link it here.


Does the above address your use case, or is there something still missing?

**Comment by qweeze** [comment]
Yes, that's exactly what I was looking for, thanks a lot.
