### ISSUE TITLE
Embedded DNS quits resolving - `nslookup google.com $DOCKER_GW_IP` = SERVFAIL

### ISSUE THREAD

**Issue by colinmollenhour** [moby/moby#34972]
**Description**

On a few occasions now I have had some nodes where the Docker embedded DNS server suddenly stops working causing DNS resolution within the containers to fail. The issue is not with a particular container but rather the entire host.

**Steps to reproduce the issue:**

```
~ # DOCKER_GW_IP=$(ip route list dev docker0 | awk '/src/{print $7}')
~ # nslookup google.com $DOCKER_GW_IP
```

**Describe the results you received:**

```
Server:         172.17.43.1
Address:        172.17.43.1#53

** server can't find google.com: SERVFAIL
```

**Describe the results you expected:**

```
Server:         172.17.43.1
Address:        172.17.43.1#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.216.142
```

**Additional information you deem important:**

This initially is not an issue but after some period of days or weeks it suddenly stops working. Restarting the entire Docker service does *not* fix it.

Unbound is installed for local DNS resolution and listening on localhost. The `/etc/resolv.conf` file looks like this:

```
domain ec2.internal
search ec2.internal
nameserver 127.0.0.1
```

And DNS resolution against unbound works:

```
~ # nslookup google.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.5.238
```

The issue still persists when using an external nameserver in the host's `/etc/resolv.conf`:

```
~ # cat /etc/resolv.conf
nameserver 8.8.8.8
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.674GiB
Name: web17
ID: ZYKQ:ILAA:X6LP:DK2H:FYZ4:GCIQ:TZJS:S7ZD:VX37:4Y55:MNDL:A37R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 region=amazon-nva
 role=proxy
 store=ammoforsale
Experimental: false
Insecure Registries:
 10.81.128.0/17
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details:**

Currently this is occurring on an AWS instance but it was previously on non-AWS instances as well. Kontena is used for scheduling but this issue is not specific to any containers as the test is performed from the host directly against the Docker interface IP.

**Comment by thaJeztah** [comment]
Just to exclude possibilities; are you seeing the same on 17.06.2 as well (there's been some fixes in [17.06.1 and 17.06.2](https://github.com/docker/docker-ce/compare/v17.06.0-ce...v17.06.2-ce), not sure if anything in this area was included)

**Comment by colinmollenhour** [comment]
I installed 17.06.2 and the problem persists after restarting Docker service.

**Comment by thaJeztah** [comment]
ping @fcrisciani have you seen this before?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
