### ISSUE TITLE
ersion

### ISSUE THREAD

**Issue by Shanky2304** [moby/moby#34984]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment]
Seems to be a mistake. Closing.

**Comment by Shanky2304** [comment]
My apologies I have no clue when that happened.
