### ISSUE TITLE
Windows: docker logs -f does not work

### ISSUE THREAD

**Issue by xinyanmsft** [moby/moby#34980]
OS: Windows Server 2016 1607 (Build 14393.1613)
docker: 17.06.1-ee-1 build 4dd6e94, timestamp 8/16/2017

Running Windows containers, based from python:2.7-windowsservercore

Issue: the '-f' mode in docker logs -f does not work. Running 'docker logs -f <container Id>' will print out the container logs up to that point without following newly generated messages.

**Comment by thaJeztah** [comment]
ping @friism @johnstep PTAL

**Comment by friism** [comment]
I think this is a dupe: https://github.com/moby/moby/issues/30046

**Comment by thaJeztah** [comment]
Good catch; yes, that looks like the same issue. Thanks!

Let me close this one
