### ISSUE TITLE
IPv6 issue on container startup.

### ISSUE THREAD

**Issue by challa** [moby/moby#34995]
Hi

We have migrated docker demon from 1.12.3 to docker v17.0.6-ce (https://github.com/docker/docker-ce/releases/tag/v17.06.1-ce),  while start of the container i see below two logs in my log file.  
We have set --ipv6=false while starting for the demon.  
Our container are working fine despite the error  we need to know what  the impact of this error and how can we avoid it.   

time="2017-09-26T11:19:39.233454789Z" level=warning msg="Failed to disable IPv6 on all interfaces on network namespace \"/var/vcap/data/docker/netns/bc4f7b5ec4ff\": reexec to set IPv6 failed: exit status 4"

time="2017-09-26T11:19:42Z" level=error msg="failed to disable IPv6 forwarding for container's interface all: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory"

Thanks
Srinivas

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
