### ISSUE TITLE
Docker swarm network unstable and intermittently unresponsive

### ISSUE THREAD

**Issue by stefanthorpe** [moby/moby#35009]
# Problem
Docker services have intermittent connectivity to underlying containers. The containers just appear unresponsive. 
This problem has been replicated across a number of different container types, from the official WordPress and Nginx to our own internal app. For simplicity, I’ll focus on examples using the latest official Nginx build.

To test the responsiveness of the service I’m using curl and the following shell command:
```
for i in {1..10}; do curl localhost;done
```
This loops 10 times each time curling the localhost.

Within a container(via docker exec) this results in 10 quick solid responses.

On any one of the master nodes, the same command results in only 1 or 2 complete responses. 
The same is true external. (Obviously replaced localhost with Public IP here.)
The above indicates that the issue is somewhere in the network layer of docker swarm.

Example output from master node loop:
```
curl: (7) Failed to connect to localhost port 80: Connection timed out
curl: (7) Failed to connect to localhost port 80: Connection timed out
curl: (7) Failed to connect to localhost port 80: Connection timed out
curl: (7) Failed to connect to localhost port 80: Connection timed out
<body>
<body>
curl: (7) Failed to connect to localhost port 80: Connection timed out
curl: (7) Failed to connect to localhost port 80: Connection timed out
```

* Note running the container as a single docker run command works just fine.

# Current Config

Infrastructure 
3 Node cluster all nodes set to master, each node t2.medium
2 x 10.x.x.x/24, in 2 AZ’s within 1 AWS region.
An EC2 load balancer is in front of the 3 nodes.
Docker Config
DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"

Docker Info Output
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: t3lmhfli9046pdar869nxe964
 Is Manager: true
 ClusterID: t1dboha0n9n86grb75yror4oc
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.0.2.177
 Manager Addresses:
  10.0.1.98:2377
  10.0.2.177:2377
  10.0.2.58:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-128-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: ip-10-0-2-177
ID: GBHS:SSZ3:CNC4:FGGP:XZRB:FOO7:ENDB:Q7BJ:Y3TU:Z6XA:R5X7:RNX5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Docker Service Inspect Output:
```
[
    {
        "ID": "jkjglazrpc30wcz2g0m70gqcy",
        "Version": {
            "Index": 31
        },
        "CreatedAt": "2017-09-28T04:08:28.568569506Z",
        "UpdatedAt": "2017-09-28T04:08:28.57188832Z",
        "Spec": {
            "Name": "helloworld-1506571428",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest",
                    "Env": [
                        "APP_ENV=Production",
                        "DEPLOYEDAT=2017-09-28 04:08:28"
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 5
                }
            },
            "UpdateConfig": {
                "Parallelism": 2,
                "Delay": 30,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "Networks": [
                {
                    "Target": "weyz72hgv18cfqzgx94hdmcip"
                }
            ],
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Name": "4272bfd1-d50f-4834-9d67-72a2fab05773",
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Name": "4272bfd1-d50f-4834-9d67-72a2fab05773",
                        "Protocol": "tcp",
                        "TargetPort": 80,
                        "PublishedPort": 80,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Name": "4272bfd1-d50f-4834-9d67-72a2fab05773",
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 80,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "j1jnzwiju1zx6xqbne81b87x7",
                    "Addr": "10.255.0.5/16"
                },
                {
                    "NetworkID": "weyz72hgv18cfqzgx94hdmcip",
                    "Addr": "17.0.0.2/16"
                }
            ]
        }
    }
]
```

Docker version:
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by vide** [comment]
@stefanthorpe can you repeat the test with siege (https://www.joedog.org/siege-home/) and more importantly, try once again on the same machine with no swarm involved (local container exposing its port), to see if you have the same issues or it works as expected?
I'm asking because that's what I'm seeing right now in my docker installation: high concurrency load (generated with siege) against plain docker container: good throughput; the same with a container running under Swarm: very bad performances. I was going to open a new issue but this looks like the one I'm seeing.

**Comment by vide** [comment]
This issue is  a total blocker for me and for deploying Swarm in production. This is a graph of how response time changed after switching a component in our architecture from Swarm to plain docker, on the same exact hosts
![Swarm-vs-docker-response-time](https://user-images.githubusercontent.com/270267/31074449-020b8cc8-a771-11e7-9b62-32cb24ac6d0b.png)

I think I'll start moving to Kubernetes

**Comment by stefanthorpe** [comment]
Had to reconfigure my port mappings in my security groups. However, I also isolated data traffic to a separate port when initializing swarm. @vide Cisco also has a network plugin that could help, it leverages etcd but that is pretty straightforward to set up a cluster.

**Comment by vide** [comment]
@stefanthorpe what do you mean with 

> I also isolated data traffic to a separate port when initializing swarm

?

**Comment by stefanthorpe** [comment]
Apologies for the slow reply.

Try seting --data-path-addr string           Address or interface to use for data path traffic (format: <ip|interface>) when running swarm init.
