### ISSUE TITLE
swarm update paused with error "No such image"

### ISSUE THREAD

**Issue by Cas-pian** [moby/moby#35014]
**Description**

Sometimes, When I update the swarm service, the service paused for early error of a container, and the status of that container is "No such image", than I check the docker daemon log, the real problem is something like this: "pulling image failed! error:  net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", I'm sure the image exist.

**Steps to reproduce the issue:**
1.create a swarm service with multi instances.
2.update the service with a new image

**Describe the results you received:**
Continue update even if pull image time

**Describe the results you expected:**
Update paused after trying twice of  pulling image from private registry.

**Additional information you deem important (e.g. issue happens only occasionally):**
sometimes, network related. But the pause of updating should not be the right option.

**Output of `docker version`:**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**
Containers: 20
 Running: 6
 Paused: 0
 Stopped: 14
Images: 42
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /opt/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 175
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xiscachfjk9w6swv0ea991l7d
 Is Manager: true
 ClusterID: w1kwa1ozfefgg1mvifhlut1ah
 Managers: 5
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
  x.x.x.x:2377
  x.x.x.x:2377
  x.x.x.x:2377
  x.x.x.x:2377
Runtimes: runc

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine with ubuntu 16.04.1  linux 4.4.0-31-generic installed

**Comment by Cas-pian** [comment]
Swarm servcie udpate paused unexpectedly, I'm sure the image exist, just timeout, why not retry but pause the updating progress?
@thaJeztah Any suggestion? Thanks!

**Comment by cpuguy83** [comment]
The update would be paused (meaning it won't try to rollout to more replicas), but the service itself would be trying to reconcile the desired state with the actual state until it is satisfied.

**Comment by Cas-pian** [comment]
But, as I have tested, the update won't resumed, and the state is alwalys pause.
Yesterday I hit this problem again, this is the state of my service now (never continue update for 22h):  
![image](https://user-images.githubusercontent.com/5690854/31807245-98b1847a-b59f-11e7-8275-6dba48f8643d.png)

**Comment by cpuguy83** [comment]
@Cas-pian It won't unpause automatically.
If you want it to force start again you can issue `docker service update <service>` with no options.

**Comment by cpuguy83** [comment]
Alternatively you can `docker service update --rollback <service>`

**Comment by Cas-pian** [comment]
@cpuguy83 Thanks for you reply!
I know we can update it by execute the `service update` again, but seems it's a network issue which should not pause the update progress, but retry pulling image should be the option.

**Comment by sev3ryn** [comment]
I'm facing the same issue - time from time I have to redeploy service multiple times because on one of the nodes pull image fails and service is rolled back 

docker daemon logs looks like this:
```
level=error msg="Not continuing with pull after error: error pulling image configuration: Get https://myregistry.osa:5000/v2/best/proxy-production/blobs/sha256:dbe5bfa4e6ad83fae2123bc8a0dc21d8c430416361d0ddcebcd7686b97d97cd3: dial tcp 10.120.0.4:5000: i/o timeout"
pulling image failed" error="error pulling image configuration: Get https://myregistry.osa:5000/v2/best/proxy-production/blobs/sha256:dbe5bfa4e6ad83fae2123bc8a0dc21d8c430416361d0ddcebcd7686b97d97cd3: dial tcp 10.120.0.4:5000: i/o timeout" module=node/agent/taskmanager node.id=bv7ub7ficidiq2eb7kvvxczpf service.id=cy12pdbtjpmfk9yv8evn5fdhm task.id=pit9woq4gqu6azd4ui8gn65fp
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
