### ISSUE TITLE
Windows: Possible HNS regression: Does not error on duplicate port mappings in RS3 builds

### ISSUE THREAD

**Issue by jhowardmsft** [moby/moby#35023]
@msabansal As per offline email, opening issue here. I'll temporarily disable the test (TestRunAttachFailedNoLeak - https://github.com/moby/moby/blob/master/integration-cli/docker_cli_run_test.go#L4012-L4036) to bring up RS3 CI pending further investigation.

RS1:
```
docker run --rm -p 8000:8000 microsoft/windowsservercore cmd /s /c exit 0
e:\go\src\github.com\docker\cli\binary\docker.exe: Error response from daemon: failed to create endpoint pedantic_lovelace on network nat: HNS failed with error : The object already exists

```

RS3:
```
docker run -d --name=test -p 8000:8000 microsoft/windowsservercore powershell sleep 600
docker run --rm -p 8000:8000 microsoft/windowsservercore cmd /s /c exit 0
```

@johnstep FYI

**Comment by jhowardmsft** [comment]
@msabansal Do you know if this was serviced? Or fixed in RS4?

**Comment by thaJeztah** [comment]
ping @msabansal

**Comment by msabansal** [comment]
I fixed it for RS4 but not sure if this was moved to RS3. I will check.

**Comment by msabansal** [comment]
This was fixed as MSFT:14083260 on 10/31/2017

**Comment by thaJeztah** [comment]
@msabansal that's part of RS3?

**Comment by msabansal** [comment]
Yes it should have been released as a bugfix back in November/December (i think).

**Comment by thaJeztah** [comment]
Perfect, thanks! I'll go ahead and close this
