### ISSUE TITLE
No error thrown on a force removal of a volume that does not exist

### ISSUE THREAD

**Issue by sterchelen** [moby/moby#35049]
**Description**

While working on the #34953 , I saw that when we force to remove a volume that does not exist, no error is thrown. 

**Steps to reproduce the issue:**
1. `docker volume rm -f nonexist`

**Describe the results you received:**
I received a confirmation with the name of the supposed deleted volume.
`nonexist`

**Describe the results you expected:**
I'm expecting this result: `Error response from daemon: get nonexist: no such volume`

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 82
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 5SCO:LMBC:VVOK:RQ6F:DEAL:H4HK:3Z3B:P2LU:SHL5:DCC6:KEGH:XKAV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-10-01T07:19:12.4358433Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by sterchelen** [comment]
#dibs

If this behavior is confirmed as an issue, I've partly fixed it on #34953 ... Thanks to the usage of the `VolumeRm` function that throw an error if it does not exists whether or not we are forcing the removal.
It remains to fix the following integration test --> `TestVolumeCLIRmForceUsage`.

@thaJeztah could I add on the same commit message all the issues that are fixed ?

**Comment by thaJeztah** [comment]
This may actually be by design; when force deleting it's ok to ignore the error; also see https://github.com/docker/cli/issues/394

**Comment by thaJeztah** [comment]
Basically, it's modelled after Linux `rm -f`

http://man7.org/linux/man-pages/man1/rm.1.html#top_of_page

```
-f, --force
              ignore nonexistent files and arguments, never prompt

**Comment by sterchelen** [comment]
Good to know. @thaJeztah We should add more information to the `-f` option ?

Actually we have this output for `docker volume rm --help`:
```
  -f, --force   Force the removal of one or more volumes
```

**Comment by sterchelen** [comment]
No response from @thaJeztah , closing it!
