### ISSUE TITLE
ReadOnlyRootFs causes /dev tmpfs to be mounted in ro mode

### ISSUE THREAD

**Issue by khimaros** [moby/moby#35041]
**Description**

Using `ReadOnlyRootFs` causes /dev to be mounted as readonly (though /dev/pts and /dev/shm do not suffer the same fate). This breaks rsyslogd, which wants to create its socket at /dev/log.

I've attempted a few workarounds, including a manual rw tmpfs mount at /dev (which works, but wipes out the devpts mount at /dev/pts) -- I can then bind mount /dev/pts:/dev/pts, but I'm displeased with the security implications of this.

This seems to be the code which is responsible for populating the mount table: https://github.com/moby/moby/blob/a5f9783c930834b8e6035fb0ad9c22fd4bbfc355/daemon/oci_linux.go#L582

**Steps to reproduce the issue:**

```
$ docker run --rm -it --read-only debian:stable bash -c 'mount | grep "on /dev/pts type"'
```

**Describe the results you received:**

By default, /dev is mounted rw:

```
$ docker run --rm -it debian:stable bash -c 'mount | grep "on /dev type"'
tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
```

Using `--read-only`, /dev/pts is still mounted rw:

```
$ docker run --rm -it --read-only debian:stable bash -c 'mount | grep "on /dev/pts type"'
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
```

However, /dev is mounted ro:

```
$ docker run --rm -it --read-only debian:stable bash -c 'mount | grep "on /dev type"'
tmpfs on /dev type tmpfs (ro,mode=755) 
```

When we manually create a rw tmpfs on /dev, we lose the /dev/pts mount entirely: 

```
$ docker run --rm -it --read-only --tmpfs=/dev:rw,dev debian:stable bash -c 'mount | grep "on /dev/pts type"'
**EMPTY OUTPUT**
```

**Describe the results you expected:**

```
$ docker run --rm -it --read-only debian:stable bash -c 'mount | grep "on /dev type"'
tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
```

**or**

```
$ docker run --rm -it --read-only --tmpfs=/dev:rw,dev debian:stable bash -c 'mount | grep "on /dev/pts type"'
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by sllawap** [comment]
Similar symptom to #15938, though that bug seems to have gone stale.

**Comment by justincormack** [comment]
This is intentional in order to lock down the container filesystem - I think it is really a bug in `rsyslogd` even though that has historically been the location of the log socket, it should correctly be in `/run` as that is for temporary sockets like that.

**Comment by khimaros** [comment]
@justincormack thank you for the response. I think it is more than just a bug in rsyslog -- libc's `syslog(3)` expects the syslog daemon to create that device node.

Any idea why a manual tmpfs mount at /dev shadows /dev/pts? If that problem were solved, I would have a satisfactory workaround.

**Comment by thaJeztah** [comment]
Manually mounting a tmpfs mounts an empty tmpfs device at `/dev‘, so yes, I think that would be expected

**Comment by thaJeztah** [comment]
new pull request / discussion here: https://github.com/moby/moby/pull/35344
