### ISSUE TITLE
Add --clone flag to COPY command

### ISSUE THREAD

**Issue by lukasmalkmus** [moby/moby#35047]
This is a **feature request**. I try to keep it as simple as possible, but don't hesitate to ask if something is unclear.

I'm using docker *multi-stage builds* to build my go binaries and create small sized containers. To get the code from my local filesystem into the build environment, I'm using two commands (assuming `WORKDIR` is set correctly, etc.):

```bash
COPY . /tmp/code/myproject
RUN git clone /tmp/code/myproject .
```

I prefer this method, because I only want code which is under version control in my build environment. Example: When using GRPC, I'm not keeping the generated code under version control. I explicitly want the build env to generate the GRPC code from the `*.proto` definitions before building the go binaries.

I suggest to add a `--clone` flag (or `--git`?) to the `COPY` command, which modifies its behaviour. Instead of copying from the local filesystem, it performs a `git clone`.

Please provide me with some feedback.

**Comment by nathanleclaire** [comment]
If `RUN git clone` is working perfectly fine, and you don't end up with any intermediate build steps anyway due to the multi-stage build, why add a new flag?

**Comment by lukasmalkmus** [comment]
While I understand, that the use of `--chown` is way more common, I could also question the existence of the `--chown` flag for the `COPY` and `ADD` commands using your argument. 

In the end, adding a `--clone` flag to `COPY` would do two things:
1. Shorten the example given above into one command, instead of `COPY` and `RUN`
2. Remove the need of installing `git`, which is at least an extra command

Sure, installing `git` is trivial when using an `alpine` image for example, but can get a bit trickier when dealing with `scratch` images. The `--clone` flag would eliminate those worries.

**Comment by fntlnz** [comment]
@lukasmalkmus Thanks for opening this issue, it's always important to reason on possible things and different ideas.

Here's what I think:

The `git` use case is very different than the `chown` use case.
Doing a `chown` is really just an OS call to the `chown` syscall (https://github.com/moby/moby/blob/a5f9783c930834b8e6035fb0ad9c22fd4bbfc355/builder/dockerfile/copy_unix.go#L42)

Instead doing a git clone would require a complete set of git client feature to be ported in Go and then in moby itself.

Far from the implementation details, I also think that what you want to do can be achieved in an elegant way using multi stage builds like:

```Dockerfile
FROM alpine:edge as builder
RUN apk update
RUN apk add git
RUN git clone https://your.server/repo.git
# suppose that it's it has the ldflags to be statically compiled
RUN gcc -o program main.c 

FROM scratch
COPY --from=builder /program /program
ENTRYPOINT ["/program"]
```

This would create an image that has only program and nothing else.
This is why multi stage builds exists after all, to allow you to create a final image without having to install build dependencies and things that generally you don't want in the final image.

**Comment by lukasmalkmus** [comment]
Right, I was a bit naive when comparing a `git clone` to `chown`. The features introduced by this new flag would probably not justify the implementation costs you mentioned.

**Comment by fntlnz** [comment]
Don’t worry it’s useful to see how different people see and understand the features. The other thing is that this is not just future effort in maintaining the git clone itself but i the plethora of new things that it would request like support for svn, cvs, hg and the others. I’m closing this now but feel free to add more reasoning to the subject by continuing the discussion.

**Comment by lukasmalkmus** [comment]
Oh no worries here, I think I learned something today :)
