### ISSUE TITLE
docker ps -f should return nonzero exit status for no matches

### ISSUE THREAD

**Issue by tripleee** [moby/moby#35057]
**Description**

For programmatically checking whether a container is running, I would expect

```
docker ps -q -f name=foobar
```

to return a nonzero exit status if no running container matching the filter was found.

**Steps to reproduce the issue:**
1. Run a container, say `docker run --name foobar --rm mycontainer`
2. Check for its existence with `docker ps -q -f name=foobar && echo yes`
3. Stop the container
4 Check for its existence again; observe that exit status is still zero, in spite of no output

**Describe the results you received:**

Command exit status is zero, indicating success.

**Describe the results you expected:**

Command exit status should be nonzero to indicate failure to match.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker --version
Docker version 17.06.2-ce, build cec0b72
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 139
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: IWAM:QARS:YQWX:F7HX:KZSD:7HFN:UDTG:ZLF4:LSX7:CGPD:ZEQN:ZSKP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 31
 System Time: 2017-10-02T08:50:24.949181594Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on a Mac, but the behavior should obviosly be platform-independent.

There are probably many other Docker commands which should be properly scriptable.

I was surprised that I could not find an open duplicate of this bug; sorry if this has already been requested.

**Comment by tripleee** [comment]
Tangentially, see also https://stackoverflow.com/a/46522196/874188 for a bit of background and context.

**Comment by thaJeztah** [comment]
I think there was a discussion around it, but cannot find the issue where the discussion was on; this could be seen as a different interpretation of the result; i.e. "filter was successful (but returned an empty list)" vs "filter was invalid / the command was unsuccessful".

**Comment by tripleee** [comment]
If you need to distinguish, you can use e.g. exit code 1 for "filter was successful but returned nothing" and a higher number for "parse error in filter expression".

If there is a better approach for driving Docker programmatically, what would that be?

**Comment by cpuguy83** [comment]
Why not rewrite this to something like this?
```bash
for app in "$@"; do
    for i in $(docker ps -q -f name="$app"); do
        docker stop "$app"
    done
done
```

Or

```bash
args=()
for i in "$@"; do
	args+=("-f name=$i")
done

for i in $(docker ps -q ${args[@]}); do
        docker stop $i
done
```

Or simply in this case:
```
docker stop $@ 2>/dev/null
```
Would also work.

I think it's a bit weird to return a non-zero exit code for an empty list.

**Comment by vdemeester** [comment]
This is by design, the filter worked and resulted in an empty list, it cannot really be seen as an error. 

I'm going to close that issue, but feel free to re-open a new one in https://github.com/docker/cli (the cli code moved there a while ago) if you feel it's the wrong decision. Thanks 👼 😉

**Comment by tripleee** [comment]
The workarounds above are okay for "I need to stop this image if it is running" but there are related use cases like "I need to start this image if it is not running" for which you cannot simply run the command just in case.

The use of exit codes to communicate the presence of results is well-established; compare to how `grep` and `diff` return a nonzero exit code for no matches (`grep`) or when there are differences (`diff`), precisely so that you do not have to resort to the brittle practice of comparing against empty output (or more generally output which might be intended for human consumption, and/or change between versions, and/or be localized). Using a lower number exit code for "command succeeded but didn't produce anything" is a common practice, though I don't think I can find a written recommendation.

(Sorry for taking so long to revisit; I am just adding these comments to tie up some dangling loose ends.)

FWIW the double quotes around `"$@"` are significant, and should basically never be omitted.  If you specifically want the shell to split the arguments on whitespace and expand wildcards, you probably want `$*` instead.
