### ISSUE TITLE
What I did Apply xfs project quota for overlay storage driver.

### ISSUE THREAD

**Issue by abc985** [moby/moby#35053]
- What I did
Apply xfs project quota for overlay storage driver.
Basically it's same work for #24771 Xfs quota PR but I applied to overlay instead of overlay2
I planed to improve this PR and apply overlay2 too but better PR (#24771) is already summited...

- How I did it
Set xfs project quota to container's overlay storage root directory.
Use projectquota.go in #24771 and apply it to overlay driver.
The --storage-opt size=#(m/g) options to set a limit for containers.

- Known issues
This quota only applied to container's upper layer and file changes which made by container itself.
XFS quota doesn't allow hardlink across quota boundries. so basic ApplyDiff() hardlink operation is changed.

if source/destination directories are same quota boundries or no quota --> hardlink file
if source/destination directories are different quota boundries --> copy file
XFS project id is not deleted when quota is deleted by overlay driver (ex. container rm).
And there's no way to figure out current project id is used in another place.
So, If you want to create unique project id, set a project id to home directory of overlay for it. (use it to minimum project id for quota)
- How to verify it

basic operation
# mount | grep xfs

**Comment by thaJeztah** [comment]
Looks like a spam issue, so closing
