### ISSUE TITLE
Stack Trace when running any docker commands - Containers can't start

### ISSUE THREAD

**Issue by Vacant0mens** [moby/moby#35061]
**Description**
I first noticed it when I tried to run the command `docker stack services [stack]`. I got a list of services, and then a stack trace from Go. It also comes up any time I run any `docker` command (like `docker version`). Even after restarting the Docker service, it'll give me the results of the command, and then this:
```
Exception 0xe06d7363 0x19930520 0xc0424cb390 0x7ffe20dc3c58
PC=0x7ffe20dc3c58


goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x10b
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 4 [syscall, locked to thread]:
syscall.Syscall6(0x7ffe23906bf0, 0x5, 0x33c, 0xc04207ff9c, 0xc04207ffa0, 0xc04207ffa8, 0xffffffff, 0x0, 0xc04207ff50, 0x4038dd, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x33c, 0xc04207ff9c, 0xc04207ffa0, 0xc04207ffa8, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:103 +0xc6
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x33c)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:146 +0x82
created by github.com/docker/cli/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:66 +0x87

goroutine 5 [select]:
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc04240cc60, 0xc04232b800, 0xc04240cc80, 0x0, 0x1377ac0, 0x1370590, 0x1377ac0, 0x1370590, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:174 +0x33e
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc04240cc60, 0xc0423d1000, 0x1000, 0x1000, 0xc042081a48, 0x451b10, 0xc04201a000)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:212 +0x121
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc0424153a0, 0xc0423d1000, 0x1000, 0x1000, 0xc0421c1920, 0xc042010ff0, 0xc042081be5)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/pipe.go:122 +0x63
net/http.(*persistConn).Read(0xc042391e60, 0xc0423d1000, 0x1000, 0x1000, 0x4, 0x44fa60, 0xc0421c1920)
        /usr/local/go/src/net/http/transport.go:1316 +0x152
bufio.(*Reader).fill(0xc04242e2a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x11e
bufio.(*Reader).Peek(0xc04242e2a0, 0x1, 0xc042081be5, 0x1, 0x0, 0xc04242e300, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x6e
net/http.(*persistConn).readLoop(0xc042391e60)
        /usr/local/go/src/net/http/transport.go:1474 +0x19d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa3c

goroutine 6 [select]:
net/http.(*persistConn).writeLoop(0xc042391e60)
        /usr/local/go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa61

goroutine 21 [select]:
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc042052900, 0xc0423cbb60, 0xc042052920, 0x0, 0x1377ac0, 0x1370590, 0x1377ac0, 0x1370590, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:174 +0x33e
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc042052900, 0xc04237b000, 0x1000, 0x1000, 0xc042433a48, 0x451b10, 0xc04201a000)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:212 +0x121
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc042450200, 0xc04237b000, 0x1000, 0x1000, 0xc04244b200, 0xc042010f50, 0xc042433be5)
        /go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/pipe.go:122 +0x63
net/http.(*persistConn).Read(0xc042331560, 0xc04237b000, 0x1000, 0x1000, 0x4, 0x44fa60, 0xc04244b200)
        /usr/local/go/src/net/http/transport.go:1316 +0x152
bufio.(*Reader).fill(0xc04244b080)
        /usr/local/go/src/bufio/bufio.go:97 +0x11e
bufio.(*Reader).Peek(0xc04244b080, 0x1, 0xc042433be5, 0x1, 0x0, 0xc0421c0360, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x6e
net/http.(*persistConn).readLoop(0xc042331560)
        /usr/local/go/src/net/http/transport.go:1474 +0x19d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa3c

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc042331560)
        /usr/local/go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa61
rax     0x17515c0
rbx     0x191
rcx     0xc0424cab00
rdi     0xc0424cb488
rsi     0x7ffdfa4be4e0
rbp     0xc0424cb230
rsp     0xc0424cb0f0
r8      0x700000003
r9      0x10
r10     0x3fffffffe
r11     0x0
r12     0x0
r13     0x17f0340
r14     0xc0424cb390
r15     0x17cb7e0
rip     0x7ffe20dc3c58
rflags  0x202
cs      0x33
fs      0x53
gs      0x2b
```
**Additional information you deem important (e.g. issue happens only occasionally):**
Running Docker in Swarm Mode with 4 nodes that have 2 NIC's each.
Running two stacks with 10+ services each.
No individual containers, nothing running on the Nat network.

**Output of `docker version`:**

```
Client:
 Version:      17.06.1-ee-2
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:16:53 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ee-2
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:25:53 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 54
 Running: 12
 Paused: 0
 Stopped: 42
Images: 39
Server Version: 17.06.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: arlmn5hbfe03ertpwqwgegpf6
 Error: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 10.0.1.230
 Manager Addresses:
  10.0.1.230:2377
  10.0.3.150:2377
  10.0.3.157:2377
  10.0.3.169:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4GiB
Name: GPSDAZ-IB
ID: Z2CZ:S4X7:UK55:STYT:INYK:MQID:DIHM:WY7Y:M7X3:6FBB:GC36:F3YW
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 gpsovermindlcl:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
all nodes are VM's running in VMware vSphere with 2 virtual processors and 4gb of ram. All nodes are Windows Server 2016 Core. They should all be identical except for the services that they're running.

From another node in the same swarm, all manager nodes are labeled as `Reachable` and `Active`.
The above `docker info` command was run on one of the two affected nodes. Other nodes show this node as reachable and active.

The two affected nodes are running the Windows Service with the following method of registering...
`dockerd --register-service --insecure-registry [registryserver] --data-root "E:\Docker" -H tcp://0.0.0.0:2380 -H npipe:////./pipe/docker_engine`

**Comment by thaJeztah** [comment]
If I'm not mistaken, the latest version of docker-ee is 17.06-ee-3 (not sure about the exact version string, but it ends with `-3`); can you try if that resolves the issue?

**Comment by Vacant0mens** [comment]
Ran this commands:

`Install-Package -Update docker -ProviderName DockerMsftProvider`
and
`Install-Package docker -ProviderName DockerMsftProvider -Force`

It said 17.06-ee-2 was the latest.

**Comment by thaJeztah** [comment]
ping @friism could you have a look?

**Comment by friism** [comment]
@Vacant0mens please remove the Microsoft installer and use the one we provide:

```
Unregister-PackageSource -ProviderName DockerMsftProvider -Name DockerDefault
uninstall-module DockerMsftProvider
```

Then use our provider: https://docs.docker.com/engine/installation/windows/docker-ee/#install-docker-ee

**Comment by Vacant0mens** [comment]
Updated docker to 17.06.1-ee-3

Still throwing the same stack trace.

**Comment by Vacant0mens** [comment]
i changed the service parameters, does it look right?

`dockerd --register-service --insecure-registry [registryserver] --data-root "E:\Docker" -H tcp://0.0.0.0:2380 -H npipe://`

**Comment by Vacant0mens** [comment]
`docker container` commands don't respond.

**Comment by Vacant0mens** [comment]
ping @friism

**Comment by Vacant0mens** [comment]
If it helps, I had the API exposed on the two affected machines, and I was querying it with Python to get container statistics and service settings/info. Not sure why that would cause this, but any insight would be appreciated.

**Comment by friism** [comment]
@Vacant0mens can you provide steps for us to reproduce the problem? Does the problem still occur if you don't run the python scripts?

**Comment by Vacant0mens** [comment]
It's not a very easy thing to track. My scripts just do GET's for container stats and service info from the API with the 'requests' module/class. There's no actual impact to Docker aside from that. It just pulls the stats/info with a url and then parses/filters/calculates the data on the python-side to keep the processing off the Docker host, then sends a json block to elasticsearch for indexing.

It wasn't having any problems that I could see so I left it running over the weekend. When I came back it had stopped and when I restarted it, it threw errors about not connecting to the Docker hosts. After a couple tries I looked at the server and found that stack trace.

The python queries are the only difference between the broken ones and the working ones, but my code shouldn't have done anything but pull stats and info, or thrown an error. It's basically the python equivalent to PowerShell's Invoke-RestMethod -Method GET .

**Comment by friism** [comment]
@Vacant0mens can you share a script that reproduces the problem?

**Comment by Vacant0mens** [comment]
The way I wrote it it's not really a script. It's more like an un-compiled service. But yes, I'll post what I can first thing in the morning.

**Comment by Vacant0mens** [comment]
I'm thinking the `--data-root` option is the thing keeping the error around after the uninstall/reinstall. Does anyone else think the same thing?

**Comment by thaJeztah** [comment]
Is there something different with the `E:` drive than with your `C:` drive? Different type of filesystem? Remote disk?

**Comment by Vacant0mens** [comment]
Just separate from the OS disk. That's how we have all of our servers set up here. The C:\ is pretty much only for the OS and minimal installed programs. All of the in-house software gets run/hosted from the E:\ That and we didn't want to take up all the space on the C:\ with images and stuff that build up over time.

**Comment by Vacant0mens** [comment]
the `ElasticsearchClient.py` class:
https://pastebin.com/NMfLdrdr

the `ContainerInfo.py` class:
https://pastebin.com/zAiRDc2M

the `ServiceInfo.py` class:
https://pastebin.com/YaU08VDW

and the `ApiClient.py` class:
https://pastebin.com/9NicG1pG

I'm sure it'll be clear once you start looking, but the ElasticsearchClient calls ContainerInfo and ServiceInfo, and those two call ApiClient. Both `ElasticsearchClient.services()` and `ElasticsearchClient.containers()` methods run in parallel from the `ElasticsearchClient.__init__()` method. 

The `ApiClient.get_from_api()` class should be the only one that's ever used. The only time `ApiClient.post_to_api()` is used is setting the service replicas, but that is never called in the ElasticsearchClient class, and that's the only thing I've been running in the last week or two.

**Comment by Vacant0mens** [comment]
Based on the fact that I uninstalled and reinstalled, I feel like it might be a corrupted image or container somewhere. But since all the synchronous/container commands won't respond, I can't run a `docker [container|image] prune` to confirm that.

**Comment by Vacant0mens** [comment]
containers created by services created by stacks are throwing this error:
`HNS failed with error : The system cannot find the file specified.`

@friism any word yet?

**Comment by friism** [comment]
@Vacant0mens while we're happy to try and help here, the most reliable way to get prompt support for Docker EE running on Windows Server is to open a ticket with Microsoft support. I'll try to take a look too, when I get a chance.

**Comment by Vacant0mens** [comment]
Do they support Docker directly? because this problem looks like a Docker-related problem rather than a problem with Windows. I just don't want them to say "we don't support Docker. Feel free to open an issue on github".

And if it *is* a Docker-related problem, it seems to be a pretty glaring bug. If it's not, could someone at least point me in the right direction? A Go stack trace doesn't help me that much.

**Comment by friism** [comment]
> Microsoft will provide Windows Server 2016 customers enterprise support for CS Docker Engine, backed by Docker, Inc

 - https://blog.docker.com/2016/09/docker-microsoft-partnership/

(CS Docker Engine is now called Docker Enterprise Edition, and that's what you're running)

**Comment by Vacant0mens** [comment]
I did some digging. This script may have been running when the problem started. But it may not have. I don't have a solid timeline, so this is kind of a guess.

https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/windows-server-container-tools/ServiceAccounts/CredentialSpec.psm1

**Comment by Vacant0mens** [comment]
@friism and @thaJeztah 

After opening a ticket with Microsoft, they came back after a couple weeks and told me that 'WebCompanion' (or some kind of malware with the same name) was causing the problem. I looked into the server a bit and ran traces on the running processes using Procmon (from sysinternals suite), and I found that a program that we installed for testing called *dynatrace* was running along side some of our other services. Looks like we installed it around the same time that I was testing things with my python program. We uninstalled the program, rebooted, and the problems disappeared!

_Hopefully anyone using Dynatrace and Docker on the same machine can come and see this solution (however unlikely the case is)._

It seems Dynatrace was blocking or intercepting the confirm/success response from the DockerAPI.

Glad I got it cleared up!

**Comment by thaJeztah** [comment]
That's good news! Thanks for the update :+1:

**Comment by friism** [comment]
@Vacant0mens if you're a Dynatrace customer and if you haven't already, can I ask you to get in touch with Dynatrace to make sure they're aware of this problem?

**Comment by Vacant0mens** [comment]
I'll see what I can do.
