### ISSUE TITLE
No log driver named 'gelf' is registered on Docker for Windows

### ISSUE THREAD

**Issue by mle-ii** [moby/moby#35062]
### Expected behavior
Specifying gelf as the log-driver should use that plugin for sending logs to gelf and should then send log data to the IP:PORT specified.

### Actual behavior
Both using the option in the docker run command and via the daemon.json config file don't work and report something like the following:

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: logger: no log driver named 'gelf' is registered.
> See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

### Information
```
Version: 17.09.0-ce-win31 (13514)
Channel: edge
Sha1: ff8d09a22918de4afe37795cbcaadd1c4da5cd9c
Started on: 2017/09/29 11:16:24.755
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
```

The docs seem to imply that this driver is supported on Windows and I've seen various folks report their docker info logs that seem to indicate that they have it as well.
https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers
https://docs.docker.com/engine/admin/logging/gelf/#usage

From `docker info` it is not listed.
```
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
```

### Steps to reproduce the behavior

  1.  `docker run -i --log-driver=gelf --log-opt gelf-address=udp://127.0.0.1:12345 microsoft/powershell:nanoserver powershell`

###  More info:
This issue was originally reported on the for-win repo but turns out it's an issue here as gelf is not a compiled component for the Windows version.  With the info from Michael and an additional change I mentioned in the issue thread, I was able to get gelf running on Docker for Windows.  Though I do admit I don't know enough about Docker or Moby to be sure that the changes I made are the right ones nor if there are any other component.

Here is the issue I originally reported.
https://github.com/docker/for-win/issues/1143

**Comment by thaJeztah** [comment]
Thanks for reporting; I see the log driver is indeed not compiled on Windows (it's marked as "unsupported" https://github.com/moby/moby/blob/master/daemon/logger/plugin_unsupported.go#L1), but not sure if that's because it's not supported, or just never tested.

ping @cpuguy83 perhaps you know?

**Comment by cpuguy83** [comment]
I can't really think of a reason why other than maybe there was no `_windows.go` file before.

**Comment by thaJeztah** [comment]
@mle-ii would you like to give it a go, and make the changes (I saw in the linked issue you tried doing so)?

**Comment by mle-ii** [comment]
Yes, I pulled down the code, made the changes outlined in the other thread, built it on the container supplied and it worked.  

Yesterday, I figured out why graylog wasn't getting the messages, I was sending the logs to the syslog server and when I sent it to the server that accepts gelf it worked.

I can try to make a PR, but as I mentioned earlier I know little about Moby and even less about Go so I will definitely need someone there with more expertise to verify the changes.

**Comment by thaJeztah** [comment]
No worries; if you run into issues, just ping one of the maintainers 👍 or if you want a more direct chat; feel free to send a message on the  [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))

**Comment by thaJeztah** [comment]
looks this can be closed now that https://github.com/moby/moby/pull/35073 was merged

**Comment by caokennedy** [comment]
Similar issue: 
I was using Docker Community Edition successfully with 
`docker run --log-driver gelf --log-opt gelf-address=udp://<server name>:12201` sending logs to ELK via gelf. 
When I switched to Docker Enterprise Edition and run the same image I get the error `Error response from daemon: logger: no log driver named 'gelf' is registered. ` I have updated the docker daemon.json to include `"log-driver": "gelf"` and when I add   ```
"log-opts": {
    "gelf-address": "udp://<server name>:12201"

```
as suggested here https://docs.docker.com/config/containers/logging/gelf/, the docker engine does not start.

The Logging Driver is now registered as Gelf, however the error `Error response from daemon: logger: no log driver named 'gelf' is registered. ` persists. 

Does anyone know how to register the gelf driver or is it incompatible with Docker Enterprise Edition?

**Comment by thaJeztah** [comment]
@caokennedy Depends on which version of Enterprise Edition you're running; Windows support for Gelf was implemented in https://github.com/moby/moby/pull/35073, which was merged after the 17.06 codebase, so it's not yet in 17.06-ee, but is in 18.03-ee; You can install Docker 18.03-ee, which should have this feature.

**Comment by caokennedy** [comment]
@thaJeztah Hi, do you have a download link or further information on docker 18.03-ee? Looking to install it but haven't found it anywhere. Thanks!

**Comment by thaJeztah** [comment]
@caokennedy https://store.docker.com/editions/enterprise/docker-ee-server-windows, and installation instructions; https://docs.docker.com/install/windows/docker-ee/. And this section in the installation instructions shows how to find specific versions; https://docs.docker.com/install/windows/docker-ee/#install-a-specific-version

**Comment by caokennedy** [comment]
Sweet, thanks @thaJeztah !
