### ISSUE TITLE
real-time scheduler of docker 'failed to write 95000 to cpu.rt_runtime_us

### ISSUE THREAD

**Issue by Dan23** [moby/moby#35066]
Hello,

Following up with 
https://github.com/moby/moby/issues/31411 and 
https://github.com/moby/moby/pull/31827 

I am running on RedHat 7.3 with Docker version 17.05. It seems my So I was trying to do a  docker run --it --cpu-rt-runtime=95000 --ulimit rtprio=99 --cap-add=sys_nice debian:jessie but of course i get the error mentioned:
failed to write 95000 to cpu.rt_runtime_us etc

My configurations:
[root@ims2042 ~]# sysctl kernel.sched_rt_period_us
kernel.sched_rt_period_us = 1000000
[root@ims2042 ~]# sysctl kernel.sched_rt_runtime_us
kernel.sched_rt_runtime_us = 950000

So I check my parent cgroups but they don’t exist:
cat /sys/fs/cgroup/cpu.rt_period_us
cat /sys/fs/cgroup/cpu.rt_runtime_us
cat /sys/fs/cgroup/docker/cpu.rt_period_us
cat /sys/fs/cgroup/docker/cpu.rt_runtime_us

Does anyone know how i may set them to a default value to get RT Scheduler to work. My kernel returns the default values and I have CONFIG_RT_GROUP_SCHED enabled. 

This two commands returns 0:
cat /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.rt_runtime_us
cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/cpu.rt_runtime_us

whereas cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/Grouptest/cpu.rt_runtime_us returns No such file or directory.

Justin Cormac advised me to open this issue as he assumed PR https://github.com/moby/moby/pull/31827 was suppose to address this.

Thanks

**Comment by matchge** [comment]
I have seen the same issue on my testing environment, 
```
"process_linux.go:279: applying cgroup configuration for process caused \\"failed to write 950000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/docker/95bcf726dd404e56b8703f40c70254ac4475585160397a954d4f82cb1cecfece/cpu.rt_runtime_us: invalid argument\\"": unknown")',))
```
My system configuration is:
```
[root@node0101 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@node0101 ~]# uname -a
Linux node0101 3.10.0-862.9.1.el7.ppc64le #1 SMP Wed Jun 27 08:33:42 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
[root@node0101 ~]# docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	fd05fcd
 Built:	Tue Apr 24 08:08:08 2018
 OS/Arch:	linux/ppc64le
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fd05fcd
  Built:	Tue Apr 24 08:10:46 2018
  OS/Arch:	linux/ppc64le
  Experimental:	false
```
and this is the current configurations on the system:
```
[root@node0101 ~]# cat /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.rt_runtime_us
950000
[root@node0101 ~]# cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/cpu.rt_runtime_us
950000
[root@node0101 ~]# cat /sys/fs/cgroup/cpu,cpuacct/cpu.rt_runtime_us 
950000
```
After set the configuration, I have restart docker daemon, but the following parameters are still showing 0 from `docker inspect <container>`
```
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
```

**Comment by venkatavadrevu** [comment]
I have seen this error as well on CoreOS:

`/run/torcx/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 950000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/docker/f0d5b5d00a775819c30681884dc908fa8daa5ab9edc2ac28c5c6de332c675fa7/cpu.rt_runtime_us: invalid argument\"": unknown`

CoreOS details:
```
mfusion@sai_dev_machine ~ $ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.4.0
VERSION_ID=2023.4.0
BUILD_ID=2019-02-26-0032
PRETTY_NAME="Container Linux by CoreOS 2023.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
Docker Details:
```
mfusion@sai_dev_machine ~ $ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
mfusion@sai_dev_machine ~ $ zcat /proc/config.gz | grep CONFIG_RT_GROUP_SCHED
CONFIG_RT_GROUP_SCHED=y

mfusion@sai_dev_machine ~ $ sysctl kernel.sched_rt_runtime_us
kernel.sched_rt_runtime_us = 950000

mfusion@sai_dev_machine ~ $ sysctl kernel.sched_rt_period_us
kernel.sched_rt_period_us = 1000000

mfusion@sai_dev_machine ~ $ cat /sys/fs/cgroup/cpu,cpuacct/cpu.rt_runtime_us
950000

mfusion@sai_dev_machine ~ $ cat /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.rt_runtime_us
950000

mfusion@sai_dev_machine ~ $ cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/cpu.rt_period_us 
1000000

mfusion@sai_dev_machine ~ $ cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/cpu.rt_runtime_us 
0

mfusion@sai_dev_machine ~ $ docker run -it --cpu-rt-runtime=950000  --ulimit rtprio=99  --cap-add=sys_nice debian:jessie

/run/torcx/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 950000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/docker/f0d5b5d00a775819c30681884dc908fa8daa5ab9edc2ac28c5c6de332c675fa7/cpu.rt_runtime_us: invalid argument\"": unknown.
```

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
