### ISSUE TITLE
docker-inspect doesn't contain the image id seen in `docker images` - please add .ContainerConfig.ImageId member or similar

### ISSUE THREAD

**Issue by JonasT** [moby/moby#35065]
The `docker inspect` output for a container doesn't contain the image id seen in `docker images` the container is currently based on. It appears to list various hashes (e.g. `.ContainerConfig.Image` and the filesystem hashes) related to the image, but not the actual image id as listed in `docker images`. 

Since this can be crucial to check if a certain version is deployed, I propose to add .ContainerConfig.ImageId member which actually has the image id exactly as seen in `docker images`.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 23
 Running: 17
 Paused: 0
 Stopped: 6
Images: 246
Server Version: 17.09.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.9.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-33-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951GiB
Name: Ubuntu-1704-zesty-64-minimal
ID: KJSS:OJX4:ZIBM:4LRJ:ZRB5:VTJS:T2W4:M6IJ:JIB3:OPM4:TP63:L75G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical with docker-compose in a KVM machine

**Comment by JonasT** [comment]
Nevermind, I missed it since it seems unintuitively `.Id` is actually the image id and `.Container` the container id - but I suppose too much people rely on the output so you can't change it now.. however, if you ever get a chance to, this would certainly be worth changing to rename `Id` to `Image` `Container` to `Id` since that makes a lot more sense.

**Comment by thaJeztah** [comment]
It depends what you're inspecting, but indeed, `ID` is the image ID when inspecting an image; the container information is from the container that was used to build the image

**Comment by JonasT** [comment]
Ah. Yea I just noticed this too after man page reading: the problem isn't the unintuitive members, but rather that the image and container have the same name and I inspected the image unintentionally. That makes a lot more sense :smile: classic user mistake 😆

**Comment by thaJeztah** [comment]
Ah. yes, happened to me as well.

To be sure you get the right object (container, image, volume), either use (e.g.) `docker container inspect ...`, or `docker inspect --type=..`

**Comment by JonasT** [comment]
@thaJeztah thanks, very useful to know for the future :heart:
