### ISSUE TITLE
'Value too large for defined data type' when the bind mount is on xfs filesystem

### ISSUE THREAD

**Issue by wildy** [moby/moby#35071]
I've recently updated an ancient Debian Wheezy system with Docker CE 17.03 (17.09 has this bug too) and a kernel from debian backports.

Previously, this system was running Debian wheezy with stock 3.2.0 kernel and Docker 1.4.1 pulled from Ubuntu repositories.

This has been running stably for months, until I decided to update Docker to a recent version. Then I noticed that our CI system couldn't finish builds with the following error message:

cc1plus: error: .: Value too large for defined data type

Our build directories resided in a bind mount, and after 2 days of troubleshooting I have finally pinpointed it to be filesystem related, we only saw it when the host's bind directory resided on XFS.
With the host's directory on ext4 the builds finished normally.

Sadly, it would take a lot of time to convert everything to ext4 as this environment is quite large.

**Steps to reproduce the issue:**
1. Make an XFS filesystem
2. Start a docker container with a bind mount residing on XFS
3. Try to compile a Qt project in this directory

**Describe the results you received:**
Compiler exits with the following error: cc1plus: error: .: Value too large for defined data type

**Describe the results you expected:**
Compiler exits normally, finishes build

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.03.2-ce, build f5ec1e2
```

**Output of `docker info`:**

```
Containers: 26
 Running: 4
 Paused: 0
 Stopped: 22
Images: 410
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /usr/local/docker/aufs
 Backing Filesystem: xfs
 Dirs: 659
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.46 GiB
Name: qtbuild03.int.smlabs.net
ID: BDR2:W6VH:EXHB:RGPM:ZSB5:K5V6:JQ2H:2UIF:PJZK:IORT:5FR6:UYAR
Docker Root Dir: /usr/local/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.65.9.25:5000
 docker.int.smlabs.net:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by cpuguy83** [comment]
Can you give exact commands?

**Comment by cpuguy83** [comment]
Also did you only upgrade docker or was the kernel also updated?

**Comment by wildy** [comment]
@cpuguy83 as I said, yes, I upgraded the kernel from stock Debian 3.2.0 to the backported 3.16.0 which is needed for modern Docker to work.
The exact commands would be difficult, since this is invoked from a build system which builds one of our in-house projects. I thought it could have related to large file support, but a) there's no large (>2GB) files involved and I could run the large file tests properly on this filesystem (see https://github.com/moby/moby/issues/11700 - I've ran the tests and it passed.)

**Comment by thaJeztah** [comment]
Doing a bit of Googling, looks like the same error can occur due to a large _number_ of files (not filesize); e.g. https://stackoverflow.com/questions/2438890/cc1plus-error-include-value-too-large-for-defined-data-type-when-compiling-wi

This bug makes mention of a fix; https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44116

**Comment by wildy** [comment]
@thaJeztah thank you. This toolchain used gcc-4.5.3, so we've accidentally hit the very same bug you mentioned.

**Comment by thaJeztah** [comment]
Perfect! Good to hear it's resolved 👍
