### ISSUE TITLE
Slow speeds pushing and pulling large layers

### ISSUE THREAD

**Issue by robertoandrade** [moby/moby#35074]
**Description**

I noticed that both my build server and my clients when trying to build/push and pull an image that has some large layers (ie: 20GB) take a ridiculous amount of time if it doesn't get stuck, very different from some 100MBs layers I've seen images being pushed and pulled. I'm using a private repo but noticed other people have issues either with private repos or Docker Hub, as per: https://github.com/moby/moby/issues/13309 for instance.

**Steps to reproduce the issue:**
1. Build an image that has a large layer (in the GBs) and push to a repo (my 100GB image took 4h to be pushed to a private repo on a T1 line connection)
2. On a different client try pulling the image (all layers get pulled quite fast, but some of my 20GB layers download fast in the beginning and when they get to 3GB they all freeze).

**Describe the results you received:**

Long times pushing and long times to freezing during pulls.

**Describe the results you expected:**

Fast push and fast pull speeds.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 7
Total Memory: 11.71GiB
Name: moby
ID: EGOK:6WEO:BHFP:QNKI:UCSZ:QGYM:N4LX:3OKR:NPHQ:UVXH:NUYF:MF2M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 93
 System Time: 2017-10-03T20:44:40.185211779Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Jenkins pushing to Artifactory Docker Reposity on Private Data Center vs Macbook Pro running Docker for Mac pulling from Artifactory Docker Registry on Private Data Center on a 18Mbps connection.

**Comment by robertoandrade** [comment]
I noticed on my last attempt that the `hyperkit` process was pegged at a certain amount of memory (15GB virtual - I changed my docker config to allocate 12GB to my "VM"):

![image](https://user-images.githubusercontent.com/318969/31150796-fcd2f596-a862-11e7-90b7-746d33a2a5d9.png)

and my docker pull was stuck at 15GB coincidentally?

```
933352d6069a: Downloading [=================================>                 ]  15.69GB/23.48GB
```

**Comment by robertoandrade** [comment]
Do I need to have enough memory allocated in order to pull a big enough layer? my layers are 23GB but I only have 16GB of RAM, is that a known limitation of the engine?

**Comment by thaJeztah** [comment]
ping @stevvooe @n4ss PTAL

**Comment by stevvooe** [comment]
@robertoandrade No, you shouldn't need that much ram to pull a layer. Your problem sounds like something wrong with docker for mac. Please file an issue in https://github.com/docker/for-mac/issues.

There are other issues already open for problems with large layers, which we are working on, but this seems like an issue with docker for mac.

**Comment by thaJeztah** [comment]
Let me close this issue here, but feel free to continue the conversation

**Comment by robertoandrade** [comment]
I had mentioned this issue in docker/for-mac#1221 so will follow up there.
