### ISSUE TITLE
Windows Daemon utilizes C:\Windows\Temp and does not respect DOCKER_TMPDIR

### ISSUE THREAD

**Issue by ryansimmen** [moby/moby#35076]
**Description**
Pulling images on Windows copies temporary files to C:\Windows\Temp instead of data-root\tmp.  Also the daemon does not respect DOCKER_TMPDIR if it's been defined.  When the data-root path has changed to a different drive other than the OS drive this causes unnecessary space consumption on the OS drive and significant delays when pulling large images due to expensive move operations.

**Steps to reproduce the issue:**
1. Install Docker for Windows
2. Pull a large image
3. Observe disk activity via Resource Monitor

**Describe the results you received:**
Daemon utilizes the Temp directory under C:\Windows and does not respect DOCKER_TMPDIR if it exists.

**Describe the results you expected:**
Daemon should utilize the tmp directory under data-root and respect DOCKER_TMPDIR if it exists.

**Output of `docker version`:**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true

**Output of `docker info`:**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 31.9GiB
Name: ryansim
ID: CJ5H:7BDH:CGC7:74DQ:234U:GTGK:WXBN:YLTH:ZW3W:64JJ:3XLW:72SV
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2017-10-03T17:22:01.4342297-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Machine

**Comment by friism** [comment]
cc @darrenstahlmsft

**Comment by darrenstahlmsft** [comment]
This is caused by https://github.com/Microsoft/hcsshim. It currently does not support specifying a temp dir to use during layer extraction, but instead uses the Windows default. I'm currently working on some changes to the layer writer interface, and I'll keep this in mind during the redo.

For now, you can work around this by setting the environment variable TMP to the temp directory you want to use.
