### ISSUE TITLE
Swarm mode in 17.09.0-ce not replace completed/failed tasks as designed (#35080)

### ISSUE THREAD

**Issue by ErezPasternak** [moby/moby#35083]
Since issue #35080 was closed, i open this in order to get more info

All functionality should be as documented. We trust and use documentation as well.
If you think that it's not bug so please fix documentation with exception on this situation.
Some thing like: "restart_policy should be great from zero"
But you can't broke functionality without any description or warning...
17.06 work and 17.09 not... Some warning or breaking changes document must be provided...

We have an interesting use case, this why we have this configuration

Beside "normal" services we need a special one, the best way to describe it is a disposable one time usage container

This container can be in 3 stats , Ready ( so it can be used by a single remote user ) , in Use , Removed ( after usage is done )
In order to have good performance , we are making sure that we will always at least X containers in Ready stat, and they are used, we issue a service scale command to get more containers ( Container Pool Management )
We need to have between 10 and 10K containers on this type , this led us to use Swarm due to the multi machine support.

For this logic, we have set the restart-policy: none , and the container itself once done is exiting, and until the last Docker version, this exited container Task was remove as well, so a scale command after this case worked,

With the new version , while swarm show for example 25/30 , a scale command to 30 does not start 5 new containers, it seems that Swarm see 25 containers and 30 tasks
If you have a different way to handle such use case, please share

**Comment by thaJeztah** [comment]
Let's not open duplicate issues; I'll reopen https://github.com/moby/moby/issues/35080 for discussion
