### ISSUE TITLE
Spread tasks over a swarm cluster regarding CPU reservation on each node

### ISSUE THREAD

**Issue by jvigour** [moby/moby#35097]
**Description**

Willing to spread some tasks over a swarm cluster, I would like to get the following behavior : when a new task is up to be scheduled, the chosen node is the one where the least amount of CPUs is reserved. So i use the `--reserve-cpu` parameter when I create my services but the spread strategy is defined to schedule the next task on the node where the lowest number of tasks are running, isn't it ? But it does not matter of the already reserved CPUs on a node while the number of available CPUs is greater than the number of CPUs requested by the next task. 
So my request is to know if there is a way to make the scheduler choose the node where the least amount of CPUs is reserved instead of choosing the one where the lowest number of tasks are running ?

**Steps to reproduce the issue:**
1. Create a swarm cluster with 4 nodes containing 16 CPUs each one
2. Create 3 services without reserving some resources
```
docker service create --name nginx-01 --replicas 1 nginx
docker service create --name mydb --replicas 1 mongo:3.5.10
docker service create --name mybackend --replicas 1 mybackendImageName
```
3. Create 4 services by specifying a CPU reservation for each one
```
docker service create --name myprocess --reserve-cpu 8 --replicas 1 myProcessImageName
docker service create --name myprocess2 --reserve-cpu 8 --replicas 1 myProcessImageName
docker service create --name myprocess3 --reserve-cpu 8 --replicas 1 myProcessImageName
docker service create --name myprocess4 --reserve-cpu 8 --replicas 1 myProcessImageName
```

**Describe the results you received:**

- On the Node 1, the replicas of **myprocess** and **myprocess2** are running
- On the Node 2, the replicas of **nginx-01** and **myprocess3** are running
- On the Node 3, the replicas of **mydb** and **myprocess4** are running"
- On the Node 4, the replica of **mybackend** is running

**Describe the results you expected:**

For example a spread of the replicas like this:
- On the Node 1, the replica of **myprocess**
- On the Node 2, the replicas of **nginx-01** and **myprocess2**
- On the Node 3, the replicas of **mydb** and **myprocess3**
- On the Node 4, the replica of **mybackend** and **myprocess4**

**Additional information you deem important (e.g. issue happens only occasionally):**
Definitely if I reserve 9 CPUs for each **myprocess** service, the replicas are spread as I expect because the scheduler does not allow to run 2 tasks requiring 9 CPUs each one on the same node.

**Output of `docker version`:**

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: cifs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: c26xt8qyaf2ozap43dv83ov0b
 Is Manager: true
 ClusterID: u1phbzj4t37l87jeon4a3v72g
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.30.8.34
 Manager Addresses:
  172.30.8.34:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 3.857GiB
Name: swarmmanager
ID: IGMG:DTNH:RZX6:SZOG:DT2X:TH4B:KVM4:ST4F:FNQU:YJDK:AYNH:MXBR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My cluster nodes are some VMs running on KVM

**Comment by omerh** [comment]
I think that max container per host option can be a great feature.
I have a service that its CPU usage range is 0% - 100% 
Last stack deploy swarm decided to put all 4 containers on the same host. 
When there was no work everything was OK.
Than the service got work, and containers got work and host got 100% CPU and eventually got stuck.

A spread rule will help

**Comment by thaJeztah** [comment]
Yes, I think there's definitely improvements that can be made in this area; make the scheduling more customisable (in this case, for example, it may be the _desired_ result to pack as many services as possible on a node before going to the next one - but for others it may not be), perhaps being able to configure the order in which resources are considered when scheduling (e.g. "memory > cpu > networking > number-of-tasks").

There's a proposal in SwarmKit for adding support for plugins; https://github.com/docker/swarmkit/issues/2130 (I _think_ there's another issue, but I cannot find it right now).

This is something that needs to be implemented in SwarmKit, before it can be added to this repository; perhaps it would be best to reopen this issue in that repository for discussion.

**Comment by jvigour** [comment]
Thanks for the feedback.
Indeed, a possibility of customizing the criteria order to spread the tasks over the nodes would be a nice feature. It would enable a more efficient spread of services requiring a huge amount of resources and others services

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
