### ISSUE TITLE
Launching multiple instances of the same service with different container names in d.c. no longer works

### ISSUE THREAD

**Issue by bjonen** [moby/moby#35098]
In the latest version of docker we can no longer create multiple instances of the same service when only the container name differs. 

We have the following workflow: Each developer clones the repo to his personal home drive. We use environment variables to alter the `container_name` in docker-compose. This still works but in the most recent version the new container named `${user2}_myservice` is spawned but the old container `${user1}_myservice` gets killed with exit code 143. 

Please see my stackoverflow question for more details. 

https://stackoverflow.com/questions/46582219/docker-compose-start-service-from-same-docker-compose-file-using-env-vars-to-al

**Output of `docker version`:**
```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**
```
Containers: 18
 Running: 10
 Paused: 0
 Stopped: 8
Images: 223
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 107.4GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 202.4GB
 Data Space Total: 522.3GB
 Data Space Available: 319.9GB
 Metadata Space Used: 25.77MB
 Metadata Space Total: 5.495GB
 Metadata Space Available: 5.469GB
 Thin Pool Minimum Free Space: 52.23GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 125.7GiB
Name: EADL0114
ID: HVP3:FUFH:XYJF:TBTJ:BNFC:HHTV:FOVO:2P5V:ZPWB:XHQU:XGIC:7JTH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
This sounds like a problem for github.com/docker/compose ?

**Comment by bjonen** [comment]
I thought so too and downgraded back to docker-compose 1.13. The problem persisted however. We upgraded both docker and docker-compose recently, that's why I figured the problem must be connected to docker-engine somehow.

**Comment by thaJeztah** [comment]
If I'm not mistaken, docker compose now also tracks containers through labels, instead of just the name. if you inspect that container, you'll see some labels are added to the container to keep track of it belonging to the same stack.

```bash
docker inspect test_myservice -f '{{json .Config.Labels}}' | jq .
{
  "com.docker.compose.config-hash": "4fd9fdce182794c06b8d39f17f4ca7531cd577a1d6ad1972082b67abdd0a7f84",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "repro35098",
  "com.docker.compose.service": "myservice",
  "com.docker.compose.version": "1.16.1",
  "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>"
}
```

However, if both `userA` and `userB` deploy their compose file _on the same machine_ and with _the same project name_, those stacks will conflict. Instead of manually naming the container, the best solution is to use a different project name when deploying (that's why containers are "namespaced" (prefixed with the project name) when deploying with docker compose).

**Comment by bjonen** [comment]
The problem with using `project name` is that I don't see a way how to set it consistently in a multi-user, multi-project context. I can set it in .env of the project, but then it is not user specific. Using environment variables in .env is not possible. We could do
```
PROJECT_NAME=${user}_proj docker-compose. up proj
```
on the command line but that's really not very handy. 

I think there should be an easy way to make a container user-specific. Using `container_name` was really handy for this. 

If this is really a docker-compose issue, then I am happy to move it. I am just a bit surprised because as I said initially, I tested with different versions of docker-compose and the problem appeared with all of them.

**Comment by bjonen** [comment]
So we found the following workaround. We set `PROJECT_NAME` to be the username on login of the user on the host. Then we extend the service name in our docker-compose.yml files to be `proj_service`, thereby avoiding any conflicts between identical service names across projects. You can close the issue if you like. Thanks for the discussion!

**Comment by justincormack** [comment]
This is a compose issue, so I am going to close it here - please reopen in docker/compose.
