### ISSUE TITLE
--cpuset-cpus is not reflecting the desired behaviour

### ISSUE THREAD

**Issue by thefragmenter** [moby/moby#35119]
**Description**
I'm trying to restrict the number of cores visible to the container. The --cpuset-cpus is not reflecting the desired behavior inside the container. Is this the proper use of that parameter? If not, how to restrict the number of cores seen inside the container? I tried all combinations of the parameter
--cpuset-cpus="0"
--cpuset-cpus="0-1"
--cpuset-cpus="0,2"

**Steps to reproduce the issue:**
```docker run -it --cpuset-cpus=0 ubuntu:latest grep processor /proc/cpuinfo | wc -l```

**Describe the results you received:**
4

**Describe the results you expected:**
1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 99
 Running: 1
 Paused: 0
 Stopped: 98
Images: 11
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 236
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-33-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: ubuntu
ID: ZWPR:ZIYP:SSQG:SCN6:IWCV:UAZE:NVUD:K4WN:VRYS:CZUY:ZZ34:L7PI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 17.04 in VMWare

Output of uname -a
```
Linux ubuntu 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
This option sets the  `cpuset.cpu` cgroup for the containers process; which binds the processes to use the specified CPUs (see the kernel documentation on the cpusets cgroup; https://github.com/torvalds/linux/blob/master/Documentation/cgroup-v1/cpusets.txt).

However, `/prod/cpuinfo` and `/proc/meminfo` (probably others) are not taking namespaces into account, thus always show the information from the host, see https://fabiokung.com/2014/03/13/memory-inside-linux-containers/, https://github.com/moby/moby/issues/20688, https://github.com/opencontainers/runc/issues/400

This is a limitation of the kernel, thus not something that can be fixed in this repository.

I'm closing this issue for housekeeping but feel free to continue the conversation

**Comment by harish2704** [comment]
@thaJeztah 

> This is a limitation of the kernel, thus not something that can be fixed in this repository.

But, projects like LXC are solving this by providing separate fuse-based alternatives for procfs  ( see https://github.com/lxc/lxcfs ).
`lxcfs` even have documentation on how to fix this issue for docker ( see https://github.com/lxc/lxcfs#using-with-docker ).

**Comment by felipecrs** [comment]
FWIW: https://github.com/felipecrs/cgroup-scripts
