### ISSUE TITLE
[17.10-rc1] Build containers not being removed after failing build

### ISSUE THREAD

**Issue by shin-** [moby/moby#35116]
**Description**

A failing `docker build` now preserves all intermediary build containers, while previous versions removed them.

**Steps to reproduce the issue:**
1. Create failing `Dockerfile`:
```
FROM busybox:latest
LABEL com.docker.compose.test_image=true
LABEL com.docker.compose.test_failing_image=true
RUN exit 1

```
2. Run `docker build --no-cache . | grep "Running in" | cut -d' ' -f5 | xargs docker inspect | grep '"Id"'`
3. Note how all 3 containers have been preserved.

**Describe the results you received:**

Build containers remained

**Describe the results you expected:**

Build containers are removed
```
$ ~/engines/docker-1.10.2 build --no-cache . | grep "Running in" | cut -d' ' -f5 | xargs ~/engines/docker-1.10.2 inspect
Error: No such image or container: 1ce422fe7da2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This error also affects Compose (https://github.com/docker/compose/issues/5242), so it's not a CLI bug.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.10.0-ce-rc1
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   d866876
 Built:        Wed Oct  4 21:45:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce-rc1
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   d866876
 Built:        Wed Oct  4 21:44:33 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 372
Server Version: 17.10.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 446
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.499GiB
Name: yuna
ID: YZQG:AKYJ:JQXJ:CEHT:62DP:PMWA:S43W:5X47:SSOE:UXGG:XHWS:555F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by dnephin** [comment]
cc @tonistiigi @simonferquel

**Comment by tonistiigi** [comment]
@simonferquel This seems to have changed in https://github.com/moby/moby/pull/33492/files#diff-8145809cef82b62e31a5fce12cd7240aR340 . Also, I don't remember if there was a reason for doing the deletion in the end for a successful run instead of after every command. If there wasn't any, we should return to the old behavior.

**Comment by simonferquel** [comment]
@tonistiigi I think it was mostly in for sake of simplicity (eliminating many `if option.Remove{...}` occurences and having it only once).
I'll submit a fix based on defer to have both simplicity (removing all once and for all steps) and making sure it happens on every error paths.

**Comment by thaJeztah** [comment]
This only happens in 17.10 or also in 17.09?

**Comment by simonferquel** [comment]
Hmm from CLI code, I get the following documented behavior:
flags.BoolVar(&options.rm, "rm", true, "Remove intermediate containers after a successful build")
flags.BoolVar(&options.forceRm, "force-rm", false, "Always remove intermediate containers")

So I suppose this issue is in fact the right documented behavior. However, force-rm is not correctly implemented.

**Comment by vdemeester** [comment]
On 17.07, only the last one (i.e. the one that failed) is preserved 

```
λ docker build --no-cache . | grep "Running in" | cut -d' ' -f5 | xargs docker inspect | grep '"Id"'
The command '/bin/sh -c exit 1' returned a non-zero code: 1
Error: No such object: 46e8d734e976
Error: No such object: bd014a956e50
        "Id": "fc15b1076774e2a4893cc81b1a3f8f489c7e77b370b35da6d289111b708a04fd",
```

**Comment by simonferquel** [comment]
My understanding is that rm has the scope of a particular dockerfile command: even if the build fail, intermediate containers of successful steps are still removed. the comment on the cli flag might be slightly improved then.
