### ISSUE TITLE
Unable to create a swarm on Docker for Windows with two physical Windows machines.

### ISSUE THREAD

**Issue by farhankamalkhan** [moby/moby#35110]
**Description**

Unable to create a swarm on Docker for Windows with two physical Windows machines. 

**Steps to reproduce the issue:**
1. Initialize a swarm using the following command `docker swarm init --advertise-addr $SYSTEM_IP:4250 --listen-addr $SYSTEM_IP:4250`
2. Get the Manager token using the command `docker swarm join-token manager` or  `docker swarm join-token worker` 
3. On a separate system attempt to join the swarm using the command `docker swarm join --token $MANAGER_TOKEN $SYSTEM_IP:4250 --advertise-addr $SYSTEM2_IP:4251 --listen-addr $SYSTEM2_IP:4251` or `docker swarm join --token $WORKER_TOKEN $SYSTEM_IP:4250 --advertise-addr $SYSTEM2_IP:4251 --listen-addr $SYSTEM2_IP:4251`

**Describe the results you received:**
The following error is returned by the docker daemon: `Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.` Upon attempting to join the swarm again the following message is displayed `Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.`

The following results are with respect to attempting to join with the manager token.

Upon listing the nodes from system1 only one node is displayed
````
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
vjo69oncqs2tioqehu272omah *   LTP-DEV-UZAIR       Ready               Active              Leader
````

Upon listing the nodes from system2 the following error is displayed:
````
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
````

**Describe the results you expected:**
System2 should have joined the swarm either as a worker node or a manager node according to the token provided.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
`Docker version 17.09.0-ce, build 02c1d87` on both systems.

**Output of `docker info`:**

```
On System1:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: vjo69oncqs2tioqehu272omah
 Is Manager: true
 ClusterID: nte4wc5foqvxye6m9bikynq6r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.16.168
 Manager Addresses:
  172.16.16.168:4250
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.61GiB
Name: LTP-DEV-UZAIR
ID: FGNP:B2ZF:C3QB:RBVI:KEXR:66IF:EQE3:5XNX:4G2M:5CVS:T2MG:PNC2
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 133
 System Time: 2017-10-06T17:42:12.4255643+05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

On System2:
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 46
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: error
 NodeID:
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: false
 Node Address: 172.16.0.150
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.921GiB
Name: DESKTOP-3GEEPIM
ID: DLDW:ECOD:Q2IM:RIK4:A5R6:EEY3:LGI6:VOHB:NY4C:5OKN:4SVF:OGOC
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 40
 System Time: 2017-10-06T17:43:07.3055226+05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Please let me know if any additional information is required.**

**Comment by friism** [comment]
Are you using Windows Server or Windows 10? If on Windows Server, please use the EE install instructions.

Here are some instructions on running Swarm on Windows 10: https://stefanscherer.github.io/docker-swarm-mode-windows10/

You might have to open firewalls or similar to allow communication between the nodes.
