### ISSUE TITLE
Swam Mode: Healthchecks with large intervals make task unavailable after restarting

### ISSUE THREAD

**Issue by SvenAbels** [moby/moby#35126]
We are using docker swarm mode. In our dockerfile we added a healthcheck:

```
HEALTHCHECK --interval=20m --timeout=45s --start-period=10s CMD curl -f http://localhost/check.php || exit 1
```

The health check (check.php) runs several complex things so we only want to run it every 20 minutes. However, with the description above, when we start the service (docker service create ...) it looks like the service stays in " Starting 3 minutes ago" mode until the first 20 min are passed. Consequently, we cannot reach the full service for 20 minutes after restarting because docker swarm does not route any traffic to it as it's in "starting" mode.

I assume that the service only moves to "running" when the first health check is passed but if we reduce the interval, then the check will happen too often as it's very complex.

What can we do? 
Maybe we can ask docker swarm to start routing traffic to the service without waiting for the first check for 20 minutes? Or maybe there is an "initial interval" for the first check that we can specify somehow?

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 17:16:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 17:16:07 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by rdxmb** [comment]
@SvenAbels this https://github.com/moby/moby/issues/33410 should change the behavior in your setup
