### ISSUE TITLE
Error response from daemon: open 

### ISSUE THREAD

**Issue by lxzh** [moby/moby#35148]
`docker save -o wx356312_tf.tar wx356312_tf:latest`
Error response from daemon: open /var/lib/docker/overlay2/dc31e35980f8d37cb3d2eca91aafd6244dfb0d077edf594dedbcf35ab0f5825f/merged/home/train/train-00001-of-00002: no such file or directory

**Comment by AkihiroSuda** [comment]
Please fill the issue template: https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by thaJeztah** [comment]
Closing as this went stale
