### ISSUE TITLE
Docker no longer rejects API requests with version greater than daemon maximum

### ISSUE THREAD

**Issue by samuelkarp** [moby/moby#35145]
**Description**

Docker stopped rejecting API requests with version numbers greater than the maximum version supported by the daemon. This happened in https://github.com/moby/moby/commit/e98e4a71110fd33852bb755a9b8b4ebc9df904db#diff-14051df1b5de1608aaba3a983f2a87e3 as part of https://github.com/moby/moby/pull/27745 and has affected every version of Docker since 1.13.0.

This change breaks the capability detection logic used by the Amazon ECS agent. The Amazon ECS agent is designed to work with all Docker versions >= 1.5.0, and we enable or disable features depending on the capabilities of the Docker version used. We use Remote API version as we expected this to be more stable than the daemon version; the daemon version has gone through a few changes since we started (roughly semver-like to year-month plus edition). We currently call the `/_ping` API with a range of different versions to discover which API versions are supported by the Docker daemon, but this change makes it so that every request with an API version >= 1.12 will result in success. This is causing incorrect behavior where features are being enabled with incompatible Docker versions; see https://github.com/aws/amazon-ecs-agent/issues/1008 .

In https://docs.docker.com/engine/api/version-history/#v125-api-changes , I see a note about a new header returned that specifies the maximum API version of the daemon. However, I do not see a note about the change in behavior to start accepting requests that have a specified version greater than the maximum.

**Steps to reproduce the issue:**
Run `curl --verbose --unix-socket /var/run/docker.sock http://localhost/v9999.9999/_ping`

**Describe the results you received:**
On Docker versions prior to 1.13.0, you'll see an HTTP 400 with an error message "client is newer than server"
On Docker versions 1.13.0 or greater, you'll see an HTTP 200 OK.

**Describe the results you expected:**
I expected all versions of Docker to reject the API call because the specified API version was too new.

**Comment by thaJeztah** [comment]
Thanks for reporting! I agree that this should still produce an error; reading back the review on https://github.com/moby/moby/pull/27745, I cannot find a reason for removing this check (I see the check for API versions that are _older_ than what's supported is still there). Possibly because the implementation for version negotiation changed during review.

I opened a pull request to address this: https://github.com/moby/moby/pull/35150

**Comment by ripcurld0** [comment]
@thaJeztah I am closing this since #35150 was merged.

**Comment by thaJeztah** [comment]
Thanks! Forgot the fixes xyz
