### ISSUE TITLE
cross build and architecture labeling

### ISSUE THREAD

**Issue by vielmetti** [moby/moby#35158]
[This will be updated as details appear.]

Under certain (all?) circumstances, cross building an image on one architecture for another results in an image that's labelled for the wrong architecture.  This is noted in Swarm, specifically at https://github.com/docker/swarmkit/issues/2401#issuecomment-335489826 .

There, @justincormack notes

> Currently there is no way to label something as a different architecture if you cross build it. That missing feature is a moby/moby issue rather than a swarmkit one (not sure if there is an existing issue).

The impact is that if you run one of these cross-built images that Swarm will fail to schedule it, as "no suitable node available for task". 

An example image that fails in this way is this one:

```
ed$ docker run --rm mplatform/mquery luxas/prometheus-arm64:v1.5.2
Manifest List: No
 Supports: amd64/linux
```

which is built from https://github.com/luxas/kubeadm-workshop/blob/master/images/prometheus/Makefile

Tracking the larger issue at https://github.com/docker/swarmkit/issues/2401

**Comment by justincormack** [comment]
All cross builds are mislabeled I believe, not some. There is no way to say "I am building this image for a different architecture than I am running". 

cc @stevvooe

**Comment by craigham** [comment]
@vielmetti if you are looking for a temporary workaround, you can use the manifest tool mentioned in the blog post comment to update the image manifest to indicate that it is to run on a platform other than the build servers architecture.  I have incorporated it into my CI on Shippable and it works fine.

https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/#comment-3551354550

**Comment by stevvooe** [comment]
If the image isn't tagged with a specific platform in the manifest list, we resolve the OS/Architecture from the image configuration, which just grabs the GOOS/GOARCH values.

**Comment by vielmetti** [comment]
Could the problem be here?

https://github.com/docker/swarmkit/blob/28f91d87bd3f75fd039dbb9be49bfd2381019261/manager/scheduler/filter.go#L288

where there's normalization for `x86_64` but not the corresponding normalization for `aarch64` -> `arm64` ? cc @cpuguy83 

```
func (f *PlatformFilter) platformEqual(imgPlatform, nodePlatform api.Platform) bool {
	// normalize "x86_64" architectures to "amd64"
	if imgPlatform.Architecture == "x86_64" {
		imgPlatform.Architecture = "amd64"
	}
	if nodePlatform.Architecture == "x86_64" {
		nodePlatform.Architecture = "amd64"
	}

	if (imgPlatform.Architecture == "" || imgPlatform.Architecture == nodePlatform.Architecture) && (imgPlatform.OS == "" || imgPlatform.OS == nodePlatform.OS) {
		return true
	}
	return false
}
```

**Comment by nishanttotla** [comment]
@vielmetti at the time, we didn't consider `aarch64` to be part of this normalization. I think we could do it, if this is uniformly reflected across go builds. Someone would have to confirm this though.

**Comment by vielmetti** [comment]
https://github.com/docker/swarmkit/pull/2411 is a patch that is working for us.

**Comment by vielmetti** [comment]
@nishanttotla - which versions of Go do you need to look at, and what do you need to look at with them? There's a Ubuntu PPA that has several versions installed that would be straightforward to validate against.

**Comment by nishanttotla** [comment]
@vielmetti that the patch is working makes sense. The thing you're normalizing (`aarch64` to `arm64`) is `imgPlatform` and `nodePlatform`. The former comes from the image manifest, and the latter is reported by the node using a `docker info` call. The question is, why are these two different to begin with, and is there no way that can be fixed at the source? If not, only then does normalization make sense.

**Comment by vielmetti** [comment]
It's worth noting that on my Mac I get this from `docker info`:
```
$ docker info | grep ^Arch
Architecture: x86_64
```
So there's some normalization that is going on for that platform already.

**Comment by vielmetti** [comment]
Also this:

```
$ docker node inspect self | jq .[].Description.Platform.Architecture
"x86_64"
```

**Comment by vielmetti** [comment]
I'm pretty sure that Platform.Architecture is set here:

https://github.com/docker/docker-ce/blob/master/components/engine/pkg/parsers/kernel/uname_linux.go

You could make a good argument that the mapping should happen here so that the Platform.Architecture namespace is congruent with the container type namespace.

**Comment by alexellis** [comment]
Derek add label: platform/arm

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
