### ISSUE TITLE
Proposal: Add --from support to ADD command

### ISSUE THREAD

**Issue by wmnnd** [moby/moby#35169]
Hey there,

the `ADD` and `COPY` command are, according to [this comment in builder/dockerfile/dispatchers.go](builder/dockerfile/dispatchers.go) the same – except for additional remote and tar handling in `ADD`.

Since the introduction of multi-stage builds, this isn’t true anymore. Now `COPY` has one feature that `ADD` doesn’t have: Taking a file from another build stage/context.

Because I find the automatic tar handling of `ADD` to be rather convenient, I propose to make the `--from` flag available for `ADD` as well. I would also be willing to create a PR for it.

What do you think?

**Comment by thaJeztah** [comment]
Would uncompressing the tar in a separate build stage, and then `COPY --from` the uncompressed files resolve your use case? 

One reason for the implementation of multi-stage builds is to prevent more "magic" to be added in the builder; for example, there have been requests for `ADD` supporting different type of compressions etc; with multi-stage builds, those can be handled in an intermediate build-stage (so no longer relying on the Go implementation of any compression algorithm).

**Comment by wmnnd** [comment]
Thank you for your response.

This is actually the approach I’m using right now. I was more concerned about consistency and clarity of intention rather than actually finding a way to unpack an archive :smile: 

If the omission of `--from` from the `ADD` command was intentional, maybe this could be mentioned in the docs.

Does this also mean that `ADD` might be be deprecated eventually?

**Comment by thaJeztah** [comment]
> If the omission of `--from` from the `ADD` command was intentional, maybe this could be mentioned in the docs.

I'm not against adding a note in the documentation; we should be careful though, as documenting what's "not supported in this command, but is supported by another command" could be a sliding slope 😅 

> Does this also mean that `ADD` might be be deprecated eventually?

No, it won't be deprecated. It _was_ marked deprecated at some point, but with the amount of Dockerfiles using the `ADD` command, it cannot be removed. We are very conservative adding new features to `ADD` though.

I just noticed there's another issue already tracking this feature request, which has more discussion on this topic; https://github.com/moby/moby/issues/33811

Let me close this issue to prevent the discussion from diverging; feel free to participate in the other issue. I'm updating that issues title (I'l copy the title from this one) to be a bit easier to find.
