### ISSUE TITLE
on-failure restart-policy leads to start-on-boot

### ISSUE THREAD

**Issue by leberknecht** [moby/moby#35166]
**Description**

A container with "on-failure" policy is not re-started after stopped via `docker stop` (or `docker-compose stop`), which makes sense, but is re-started whenever the docker service daemon is started. So it looks like the "stopped from docker" is treated as non-zero exit code when the daemon is spawned. Not sure if this is a bug, but for me it was unexpected, i would expect "container is booted when the daemon starts" only for "always" restart-policy, and i expected that a "failure" is only found when the container-command creates a non-zero exit code, not when the container is stopped by the daemon. 

**Steps to reproduce the issue:**
1. start a container with `--restart on-failure` 
2. stop the container 
3. ensure that it is stopped and stays stopped (=not restarted)
4. restart docker service daemon
5. now the service is running (but it shouldnt)

```bash
% docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% docker run --restart on-failure -d busybox ping google.com
fa9e9592800b5ac54937f493b9a83e8f4cd8857e4f325c2640dd9c0a652e4c35
% docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
fa9e9592800b        busybox             "ping google.com"   2 seconds ago       Up 2 seconds                            tender_bardeen
% docker inspect fa9e9592800b | jq '.[0].HostConfig.RestartPolicy'
{
  "Name": "on-failure",
  "MaximumRetryCount": 0
}
% docker stop fa9e9592800b
fa9e9592800b
% docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% sudo service docker restart
% docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
fa9e9592800b        busybox             "ping google.com"   48 seconds ago      Up 2 seconds                            tender_bardeen
```

**Describe the results you received:**
Service is not auto-restarted after `docker stop` but _is_ auto-restarted after `sudo service docker restart`, which is unexpected (as "stopped by docker" should either be treated as non-zero exit or not, but not "zero when freshly stopped, but non-zero when the daemon is started"

**Describe the results you expected:**
container stays stopped after daemon (re)start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 655
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1050
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.67GiB
Name: delf-desktop
ID: HEZP:FTXC:YB7F:BXHS:UGL6:SXVM:L3RR:OA74:KCZC:UESA:55BO:TRAN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dtonder
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by leberknecht** [comment]
Hm, maybe this refs #20853

**Comment by leberknecht** [comment]
I guess changing
```go
	case rm.policy.IsOnFailure():
            [...]
	}
```
to
```go
	case rm.policy.IsOnFailure() && !hasBeenManuallyStopped:
            [...]
	}
```
in `restartmanager.go:ShouldRestart` would fix this, but it looks a little bit like this was actually intended behavior..?

**Comment by thaJeztah** [comment]
This is the expected behaviour; the daemon does not keep track of the previous state when restarting; manually stopping a container stops the daemon monitoring the container, but upon restart any container with a restart policy (other then `unless-stopped`) will be started again. Also see https://github.com/moby/moby/pull/15348, and https://github.com/moby/moby/issues/11008

**Comment by leberknecht** [comment]
I see! Ok then, will close this one. Sorry for bringing the topic up again!

**Comment by thaJeztah** [comment]
No worries!

**Comment by Exagone313** [comment]
You said that `the daemon does not keep track of the previous state when restarting` but for containers that got sigkilled when docker daemon stopped (took too long to stop), it saves the failure and restart it on boot, which is unexpected.
