### ISSUE TITLE
I still get zombie processes which do not get reaped even when using --init flag

### ISSUE THREAD

**Issue by hahne** [moby/moby#35160]
**Description**
I still get zombie processes which do not get reaped even when using --init flag. E.g.
`nvidia-docker run --init --privileged --dns=<address> --dns-search=<address> -d -P -p <ssh port>:22 -p <port>:5000  --name <container name> <image name>`

**Steps to reproduce the issue:**
It happens more or less randomly and can not easily be reproduced

**Describe the results you received:**
The docker container is not functional anymore. If one container is affected by zombie processes, soon afterwards zombie processes appear in other containers. Containers can not be stopped or killed and a server restart is needed.

**Describe the results you expected:**
Having an init process, I would expect that zombie processes get reaped.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 32
 Running: 1
 Paused: 0
 Stopped: 31
Images: 729
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 503.8GiB
Name: delisv0120
ID: 7XM4:KAH4:ETPA:PTNT:BTWU:BM25:7PUB:DVLW:DLQA:X5I2:AG63:FMLB
Docker Root Dir: /mnt/sdc1/docker-data
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://172.20.22.26:80
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Supermicro server D20x-M4-GB-8xGPU with 2x Intel Xeon E5-2640 v4 CPUs, 4x NVIDIA GeForce GTX 1080 Ti

**Comment by thaJeztah** [comment]
This could be related to nvidia-docker; have you reported with them as well?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
