### ISSUE TITLE
Ports doesn't get published on swarm master node with `docker stack deploy`

### ISSUE THREAD

**Issue by kimjuny** [moby/moby#35162]
**Description**

Ports doesn't get published on swarm master node with `docker stack deploy`

**Steps to reproduce the issue:**

1. build image

`docker build -t 10.31.207.156:5000/nginx .`

2. push image

`docker push 10.31.207.156:5000/nginx`

3. start service

`docker stack deploy -c compose.yml nginx`

**Describe the results you received:**

When running `curl -XGET http://localhost:9999` both in swarm master and slave:

1. I got `timeout` in swarm master

2. I got `index.html` output in slave

**Describe the results you expected:**

Getting `index.html` both in swarm master and slave when running `curl -XGET http://localhost:9999`

**Additional information you deem important (e.g. issue happens only occasionally):**

dockerfile

```dockerfile
FROM registry.docker-cn.com/library/nginx

COPY . /usr/share/nginx/html
```

compose.yml

```yml
version: '3'

services:
  nginx:
    image: 10.31.207.156:5000/nginx
    ports:
      - 9999:80
```

index.html

```html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div>Hello World</div>
  </body>
</html>
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 31
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 37mcbua84uf0sou6j942t7akt
 Is Manager: true
 ClusterID: nxip0twqugzzdms1yqs66vv47
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.31.207.156
 Manager Addresses:
  10.31.207.156:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639GiB
Name: iZuf6b5a58lep9igt3jojsZ
ID: 2N7B:2TST:QDDV:4HQ5:ILEY:BW45:YNXF:2JCF:P7XV:SUBG:T3KM:MXSJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.31.207.156:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Ali Cloud
- CentOS 7.3

**Comment by thaJeztah** [comment]
Which node is the container running on? Is it running on the master or on the worker node? (in other words: is the service only accessible from the host it is running on, or only accessible from the node it is _not_ running on?

**Comment by kimjuny** [comment]
@thaJeztah Only accessible from the node it is running on.

**Comment by thaJeztah** [comment]
That sounds like overlay networking isn't working;

- when initializing the swarm, did you set the `--advertise-addr` option when running `docker swarm init`?
- have you verified if all the required ports and protocols are open between nodes? (see https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts)

**Comment by kimjuny** [comment]
@thaJeztah Okay, I can confirm it's the second problem. It works, thanks. I'm closing this now.

**Comment by thaJeztah** [comment]
perfect! glad to hear it's resolved 👍
