### ISSUE TITLE
client.ContainerInspect() fails - wrong type for ContainerJSON.Platform (string instead of v1.Platform)

### ISSUE THREAD

**Issue by miko** [moby/moby#35175]
**Description**
client.ContainerInspect() fails after  commit:
d98ecf2d6... LCOW: API change JSON header to string POST parameter

with error:
json: cannot unmarshal string into Go struct field ContainerJSON.Platform of type v1.Platform

**Steps to reproduce the issue:**
1. Compile sample program from https://github.com/moby/moby/blob/master/client/README.md, adding a line within the loop like:
ci, err := cli.ContainerInspect(context.Background(), container.ID)
if err != nil { panic(err) }
2. Run it - it will panic with the above mentioned error
3. As a workaround: cd ~/go/src/github.com/docker/docker; git checkout d98ecf2d6cdad7dae65868398440cfdc855e5263
Then recompile and rerun - there will be no error.

**Describe the results you received:**
json: cannot unmarshal string into Go struct field ContainerJSON.Platform of type v1.Platform

**Describe the results you expected:**
Inspect info for a container returned.

**Additional information you deem important (e.g. issue happens only occasionally):**
Worked before commit d98ecf2d6cdad7dae65868398440cfdc855e5263. The commit did not update Platform parameter for docker/client

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.9
 Git commit:   afdb6d44a8
 Built:        Thu Oct  5 09:58:52 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   afdb6d44a8
 Built:        Thu Oct  5 09:59:07 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Will be fixed by https://github.com/moby/moby/pull/35144 (once merged)
