### ISSUE TITLE
Variabilise install-binaries.sh

### ISSUE THREAD

**Issue by flaccid** [moby/moby#35188]
https://github.com/moby/moby/blob/master/hack/dockerfile/install-binaries.sh

It would be good if the env vars in were externalise into something like a env file, but more importantly can we put things like the repo URLs into the env file so that people that are building docker can source that file to know which repositories to checkout e.g. the repo for some of these keeps changing from upstream (opencontainers) to the docker fork and back.

**Comment by cpuguy83** [comment]
I ended up refactoring this for #355100 - https://github.com/moby/moby/pull/35100/files#diff-b41c527aef1c24dce680f9588971f2c2

**Comment by flaccid** [comment]
@cpuguy83 correct me if I'm wrong, not sure how it helps this issue e.g. the repo URLs are still hardcoded in script and not variables (https://github.com/moby/moby/blob/ed082152f6e7c6c7c7fbf2bc777ba1ae88cb9073/hack/dockerfile/install-binaries.sh).

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
