### ISSUE TITLE
--log-opt max-size=50m doesn't have any effect on the logs generated by the image

### ISSUE THREAD

**Issue by oguzy** [moby/moby#35185]
**Description**

At my Alpine based images,which are running java and tomcat on them are producing json logs. Although i added an option to docker opts as --log-opt max-size=50m, still the generated logs are getting bigger.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker --version
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-8655686-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/vg_docker/lv_data
 Metadata file: /dev/vg_docker/lv_metadata
 Data Space Used: 1.558GB
 Data Space Total: 13.95GB
 Data Space Available: 12.4GB
 Metadata Space Used: 2.92MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 1.395GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69GiB
Name: aslapiptmc30.host.foo.net
ID: N4QH:PN2M:4TMB:O7PI:5G4G:MAIM:VVSK:RJXN:TSCQ:HS7B:HVRO:SGXC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker-registry-prod.app.foo.net:5000
 oslcntprgs01.host.foo.net:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

# du -shc *
513M    5a4146acc86c43751b595001ad5fda49c675a070f9a03b581ff7b929536fef57
40K     d8aa41cd2e93f541380279e03310007116f63239bcdf6b33f3f64f73df64c00b
0       e75bdb7076fd0b1badb91105a6768115e966c0c565ec00104f3e1c11e88d8906
513M    total

```

docker inspect 
https://gist.github.com/oguzy/c3bfd9e79f1b5e2cc2e865a25bdc92f2

```
# tail -n20 5a4146acc86c43751b595001ad5fda49c675a070f9a03b581ff7b929536fef57/5a4146acc86c43751b595001ad5fda49c675a070f9a03b581ff7b929536fef57-json.log 
{"log":"url=http://ap-api-java.pool.foo.net:8080/gbay/segmentations/seller/list?sellerId=xxxxx\r\n","stream":"stdout","time":"2017-10-13T04:49:09.984635498Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:09.984641017Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:09.984644454Z"}
{"log":"2017-10-13 07:49:09,983 - ltId=dba51f00a4a44fcd sRId=8695920 RESP\r\n","stream":"stdout","time":"2017-10-13T04:49:09.984647843Z"}
{"log":"body=Not logged.\r\n","stream":"stdout","time":"2017-10-13T04:49:09.984651629Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:09.98465526Z"}
{"log":"2017-10-13 07:49:09,985 - ltId=b981b5683b0d40ac RESP\r\n","stream":"stdout","time":"2017-10-13T04:49:09.985610461Z"}
{"log":"body=Not logged.\r\n","stream":"stdout","time":"2017-10-13T04:49:09.985634948Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:09.985638818Z"}
{"log":"2017-10-13 07:49:10,035 - ltId=e16f14a979624ea3 GET REQ\r\n","stream":"stdout","time":"2017-10-13T04:49:10.035723428Z"}
{"log":"url=http://ap-api-java.pool.foo.net:8080/gbay/categories/bcdd/specs\r\n","stream":"stdout","time":"2017-10-13T04:49:10.035740425Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:10.035744398Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:10.035746989Z"}
{"log":"2017-10-13 07:49:10,039 - ltId=928f8119c6f24e4e sRId=1624138 sHName=dukkanlar.foo.com sIP=172.17.100.4 sEnv=prod rip=66.249.76.50 GET REQ\r\n","stream":"stdout","time":"2017-10-13T04:49:10.039615926Z"}
{"log":"url=http://ap-api-java.pool.foo.net:8080/gbay/users/list?memberIdList=1006776818\r\n","stream":"stdout","time":"2017-10-13T04:49:10.0396301Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:10.039634249Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:10.039637009Z"}
{"log":"2017-10-13 07:49:10,039 - ltId=e16f14a979624ea3 RESP\r\n","stream":"stdout","time":"2017-10-13T04:49:10.040048527Z"}
{"log":"body=Not logged.\r\n","stream":"stdout","time":"2017-10-13T04:49:10.040056326Z"}
{"log":"\r\n","stream":"stdout","time":"2017-10-13T04:49:10.040059159Z"}
```

**Comment by cpuguy83** [comment]
How are you setting this?
The inspect output shows no option set:

```json
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
             },
```

Note that changing the option on the daemon does not change the configuration of existing containers but rather the default value when creating new containers.

**Comment by Me-ion** [comment]
Having the same issue. I've set the max-size and max-file options in the daemon.json file, restarted the docker daemon, deleted all containers and images, recreated the containers. But when I do inspect them, the "Config" is empty as in @cpuguy83 comment above. Logs increase beyond the max size and no rotation happens. The daemon is using the daemon.json for sure when reloaded:
`Jan 09 23:27:44 ip-172-30-1-152 dockerd[1238]: time="2018-01-09T23:27:44.154709582Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json"` **daemon.json contetnts:**
`{
  "log-driver": "json-file",
  "log-opts": {"max-size": "10m", "max-file": "3"}
}`
**Output of docker info:**
`Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 47
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 168
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1044-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.91GiB
Name: ip-172-30-104-142
ID: PS4E:VXQE:EGW2:UH5A:NFRJ:2HCN:JNMA:BGDZ:K5SR:GDW5:DGEP:PQWM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support`
**Output of docker version:**
`Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false`

**Comment by cpuguy83** [comment]
This is working as expected.
The daemon option only changes the default value for *new*. Containers that are existing will keep their existing configuration, which may be unconfigured.

**Comment by avi-kalar** [comment]
I have the same issue, can you please tell me when the log rotation is cleaned up, I have the following config set from my container 

          `"LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "5",
                    "max-size": "100m"
                }
            }`

and my log size is above 400 MB right now, but the logging hasn't kicked in.

**Comment by mironnn** [comment]
Any updates? Have the same issue
