### ISSUE TITLE
[Feature Request] - Pull images to swarm nodes during service update

### ISSUE THREAD

**Issue by tkeeler33** [moby/moby#35193]
# Issue
When a swarm mode container fails and the service is scheduled on another node, the service will go to a `preparing` state while the image is downloaded. The service will be unavailable until the image is downloaded and container starts. For large images this can create significant downtime while the image is being downloaded. 

# Workaround
- As a workaround, manually pulling images to each node that the service may failover to will alleviate the issue.

# Potential Solution
- Allow a swarm/stack service option to pull the image to N nodes during the service creation/update. This will allow nodes to be better prepared for a task in the event a service fails.

**Comment by drnybble** [comment]
This may also avoid having a single point of failure if you are running a private registry.
The scenario is that the private registry is running on a swarm node; if that node fails and tasks are rescheduled to other nodes, if those nodes have never pulled the image they will not succeed.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
