### ISSUE TITLE
Docker Daemon can not start containers as it does not dismount VHDs after a stopping of Windows Service

### ISSUE THREAD

**Issue by georgyturevich** [moby/moby#35208]
Hello,

I can not start container after a restart of Docker Daemon on Windows Server 2016 whene it runs tens of containers. I see following error `Error response from daemon: hcsshim::ActivateLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=... flavour=1`. Most likely it is because Docker Daemon (or vmcompute?) did not dismount virtual disks. Will explain it bellow.

**Steps to reproduce the issue:**
1. Run Docker daemon in debug state

```
Stop-Service docker;
dockerd --unregister-service;
dockerd -D --register-service;
Start-Service docker;
```

2. Run a Powershell snippet which starts 50 containers and then stops Docker Windows servce

```
date;`
for ($i=0; $i -le 50; $i++) {`
	$cname = "test_iis$i"; `
	docker stop $cname; `
	docker rm $cname; `
	$ExtPort = 10000 + $i;`
	docker run -d --name $cname -p $ExtPort`:80 microsoft/iis ping -t localhost; `
}
date;
Stop-Service docker;
date;
```

Output
```
Friday, October 13, 2017 5:53:06 PM
... Starting containers
Friday, October 13, 2017 5:59:50 PM
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
WARNING: Waiting for service 'Docker Engine (docker)' to stop...
Friday, October 13, 2017 6:00:06 PM
```

Attaching EventLogs during this period and father experiments.

If you run following commands then you see that a lot of VHDs related to Docker were not dismounted:

```
> Get-Disk | ? {$_.Location -like "*docker*"} | ft *
DiskNumber PartitionStyle ProvisioningType OperationalStatus HealthStatus BusType             UniqueIdFormat OfflineReason ObjectId
---------- -------------- ---------------- ----------------- ------------ -------             -------------- ------------- --------
         1 GPT            Thin             Online            Healthy      File Backed Virtual FCPH Name                    {1}\\EC2AMAZ-V4RG8E1\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{03cac108-addc-11e7-a96d-806e6f6e6963}:DI:\\?\scsi#disk&ven_...
         2 GPT            Thin             Online            Healthy      File Backed Virtual FCPH Name                    {1}\\EC2AMAZ-V4RG8E1\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{03cac108-addc-11e7-a96d-806e6f6e6963}:DI:\\?\scsi#disk&ven_...
         3 GPT            Thin             Online            Healthy      File Backed Virtual FCPH Name                    {1}\\EC2AMAZ-V4RG8E1\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{03cac108-addc-11e7-a96d-806e6f6e6963}:DI:\\?\scsi#disk&ven_...
```

**Describe the results you received:**

Start Docker Windows service, try to start all stopped containers
```
Start-Service docker;
docker start $(docker ps -aq);
```
And you will see a error for most containers `Error response from daemon: hcsshim::ActivateLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=... flavour=1`

**Describe the results you expected:**

I expected that all containers started without errors

If you stop Docker Windows service, dismount all related vhds, start the service, and start all containers then all containers will be started fine:
```
Stop-Service docker;
Get-Disk | ? {$_.Location -like "*docker*"} | foreach { Write-Host "Dismounting" $_.Location };
Start-Service docker;
docker start $(docker ps -aq)
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 51
 Running: 0
 Paused: 0
 Stopped: 51
Images: 1
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: EC2AMAZ-V4RG8E1
ID: VZIV:QABT:63VB:KUOW:4FOR:BTTB:QULZ:U7KS:CIZK:QWTU:63SI:65EG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-10-14T19:44:25.7000074Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I also was able to reproduce this issue on Docker 17.06.2-ee-3 .

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is m4.xlarge AWS instance with 16Gb memory and 4 CPUs

Thanks!

**Comment by georgyturevich** [comment]
@friism Hi Michael,

Could you have a look at this issue?

I just checked and was able to reproduce it with starting Azure "Standard D4s v3" (4 vcpus, 16 GB memory) instance too.

**Comment by friism** [comment]
@georgyturevich for prompt support, please open a support ticket with Microsoft support. Docker EE on Windows Server is supported by Microsoft, and they can escalate to Docker as needed.

**Comment by georgyturevich** [comment]
@friism Hi Michael,

I found that Docker Daemon `shutdown-timeout` can solve the issue. When I set it to 60s then `Stop-Service docker` took about 20 second, I did not have any dismounted VHDs and I saw following messages in the Application EventLog

```
debug: Stopping service: <nil>
debug: Clean shutdown succeeded
```

With default shutdown-timeout (15s?) `Stop-Service docker` takes about 15-16 seconds, after that I always see a lot of dismounted VHDs and see these two messages in the Application EventLog

```
debug: Stopping service: <nil>
Error: Force shutdown daemon
```

**Comment by thaJeztah** [comment]
Sounds like the issue that's resolved by https://github.com/moby/moby/pull/35184 (which would make this a duplicate/related to https://github.com/moby/moby/issues/29392)

/cc @darrenstahlmsft

**Comment by darrenstahlmsft** [comment]
Yeah, this looks like a dup of https://github.com/moby/moby/issues/29392

The referenced PR is just a mitigation for now, doing exactly what @georgyturevich is doing (increasing shutdown timeout)

**Comment by thaJeztah** [comment]
Thank you @darrenstahlmsft 

@georgyturevich let me close this one to prevent the discussion from diverging, but welcoming you to participate in the discussion on https://github.com/moby/moby/issues/29392 (you can subscribe to that issue to keep posted on updates 👍 )

**Comment by martencassel** [comment]
Neither "docker rm or the docker system prune" commands will dismount-vhd disks after 
a machine reset or crash.

**Comment by AbsolutelyFreeWeb** [comment]
I have exit code 4294967295

and it fails to start with the same error message:
`DockerDo : Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)`
