### ISSUE TITLE
Flaky Test: TestRunSlowStdoutConsumer

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#35215]
Made a new one at it's been over a year since the last one was closed for inactivity, also the failure looks slightly different. Seen failing on ppc64le: https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/6471/consoleFull

```
11:28:26 ----------------------------------------------------------------------
11:28:26 FAIL: docker_cli_run_test.go:2238: DockerSuite.TestRunSlowStdoutConsumer
11:28:26 
11:28:26 docker_cli_run_test.go:2259:
11:28:26     c.Fatalf("Expected %d, got %d", expected, n)
11:28:26 ... Error: Expected 4096000, got 0
11:28:26 
11:28:27 
11:28:27 ----------------------------------------------------------------------
```

**Comment by tophj-ibm** [comment]
some of the ci nodes are downloading a newer version of busybox instead of the frozen one, which is causing 2 other tests to also fail. I think that has something to do with it.

**Comment by thaJeztah** [comment]
Should we rewrite the tests to use a specific version / digest?

**Comment by tophj-ibm** [comment]
I don't think so, they should be using the frozen ones, and if they aren't then I want to find out where because they shouldn't be re-pulling anything. Other failing tests for ref:

DockerSuite.TestBuildLastModified, this is failing because it is trying to run `ls -le` where the `-e` flag isn't supported in busybox:latest, but it is in frozen busybox. I can rewrite this test to use stat, but I want to find this issue first. related #30890

DockerRegistrySuite.TestListImagesWithDigests, this is failing a busybox comparison check. busybox should have a tag and no digest listed, but in this case it is just showing busybox:latest.

I can also only seem to recreate this on our 14.04 CI nodes, and only when running all the tests. When run in isolation they all pass.

**Comment by tophj-ibm** [comment]
well this is probably the issue.
```
-- PASS: TestAuthZPluginAllowRequest (28.55s)
	daemon.go:285: [dba3eacfd6179] waiting for daemon to start
	daemon.go:317: [dba3eacfd6179] daemon started
	daemon.go:275: [dba3eacfd6179] exiting daemon
	clean.go:108: Removing image sha256:eab32b0925a6fa0cb42e95f4536ae16b7fa12979049041905ebf365df0c9cd4d
	clean.go:108: Removing image sha256:795757152ad2800209169959556ee52d0b221716b33c7170c8963356ad00ec0a
	clean.go:108: Removing image sha256:66298341bdaae294f9648b0692c885555b0631ca5b93b81aeea4d1a046dcb96d
	clean.go:108: Removing image sha256:907f9c0650afb1f9c891f43058806aca59d7cece87d23140b446d329a6742fbb
	clean.go:108: Removing image sha256:e6b65cb7e172ae6d193a1ab6a38bbfc29e9240516c56ddbd4040cb403c80d362
	clean.go:108: Removing image sha256:233ef922ccc53b87b53185017d9d4e103788ee9be6bd76f5c83c33fa5309394c
	clean.go:114: Removing image ppc64le/busybox:latest
	clean.go:114: Removing image ppc64le/buildpack-deps:jessie
```
