### ISSUE TITLE
`docker inspect` return with the value `/containerName` to the key `Name`

### ISSUE THREAD

**Issue by jshachm** [moby/moby#35225]
**Description**

When I try to get the `docker inspect` return value with key `Name` . I find the container Name begin with a `/` . I want to  know the purpose why the `/` should be used. 
**Steps to reproduce the issue:**
1. docker inspect -f {{.Name}} Container

**Describe the results you received:**
```
[root@localhost ~]# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
db90da532ed0        busybox             "sh"                About an hour ago   Up About an hour                        romantic_hoover
5328362867fe        busybox             "sh"                6 hours ago         Up 6 hours                              child
f8f26abb705b        busybox             "sh"                6 hours ago         Up 6 hours                              parent
[root@localhost ~]# docker inspect -f {{.Name}} db90
/romantic_hoover
```
**Describe the results you expected:**
`romantic_hoover`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@compute-node ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64


```

**Output of `docker info`:**

```
Containers: 108
 Running: 0
 Paused: 0
 Stopped: 108
Images: 90
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-8:19-6443363485-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 817.3 GB
 Data Space Total: 1.288 TB
 Data Space Available: 471.2 GB
 Metadata Space Used: 469.3 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.678 GB
 Thin Pool Minimum Free Space: 128.8 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: journald
Cgroup Driver: systemd

```

**Comment by jshachm** [comment]
ping @rhatdan

**Comment by ripcurld0** [comment]
Hi @jshachm 
Actually I think there is an open issue about removing the "/" from the beginning of containers names. @thaJeztah maybe you know what I'm talking about.

Thanks.

**Comment by thaJeztah** [comment]
Yes, the leading slash is there for historical reasons (mainly because of the legacy container-linking); there was a PR once to remove it, but I think it wasn't possible at the time, but things changed, so possibly it's possible now.

Let me search for the issue dealing with this when I get back to a computer (walking around DockerCon right now)

**Comment by jshachm** [comment]
@thaJeztah @ripcurld0  Thank you very much for the reponse. It will make a lot of  convenience to remove the slash. And have a nice time in DockerCon!

**Comment by jshachm** [comment]
#18524 Maybe you guys mean this PR. I found it in the closed PRs.

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/issues/29997

**Comment by thaJeztah** [comment]
Ah, yes, https://github.com/moby/moby/issues/29997 is tracking this @jshachm let's continue in https://github.com/moby/moby/issues/29997 (which also has relevant older discussions/issues linked)
