### ISSUE TITLE
Docker consumes far more disk space than reported by "docker system df" and is not capable of cleaning it up

### ISSUE THREAD

**Issue by sandersaares** [moby/moby#35238]
**Description**

I discovered that C:\ProgramData\docker takes up most of my 128 GB disk even though `docker system df` says Docker only consumes 17 GB.

Monitoring data indicates a gradual decrease in available disk space on the server.

![image](https://user-images.githubusercontent.com/9914262/31709222-02f90120-b3fa-11e7-8157-8178aa176393.png)

**Steps to reproduce the issue:**

Unknown.

**Additional information:**

![image](https://user-images.githubusercontent.com/9914262/31710208-05763334-b3fd-11e7-809e-7a05a3662fa2.png)

Inaccurate folder size stats:

![image](https://user-images.githubusercontent.com/9914262/31710108-bd0692e2-b3fc-11e7-8c2a-81db21191d61.png)

Obviously the numbers above are inaccurate as I only have a 128 GB disk and Docker uses file linking extensively in its storage. But by process of elimination I can say the space could not be taken up by anything else - all other data on the server takes up less than 50% of the disk (which Windows reports as full).

```
PS C:\Windows\system32> docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              4                   1                   16.92GB             14.28GB (84%)
Containers          1                   1                   0B                  0B
Local Volumes       0                   0                   0B                  0B
```

```
PS C:\Windows\system32> docker images --all
REPOSITORY                                                     TAG                 IMAGE ID            CREATED             SIZE
microsoft/windowsservercore                                    latest              ce27208ad678        7 days ago          10.4GB
xxx                    latest              6d398db55ad2        2 months ago        11.6GB
yyy                    latest              2dbfe4aebff3        2 months ago        11.2GB
zzz   <none>              1d47afed8833        3 months ago        10.3GB
```

```
PS C:\Windows\system32> docker ps -a
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS               NAMES
72a5fc0b9537        1d47afed8833        "cmd /S /C C:\\Base..."   2 months ago        Up 4 weeks                              zzz
```

I see the following in the event log at around the time that an "update all base images" script runs nightly, updating Windows images and some custom base images:

```
hcsshim::DestroyLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=fb3ffdceff8a611f163e9fd28667b3a0289ad77e0d2354998f3a0d1ade51d802-removing flavour=1

Failed to DestroyLayer fb3ffdceff8a611f163e9fd28667b3a0289ad77e0d2354998f3a0d1ade51d802: hcsshim::DestroyLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=fb3ffdceff8a611f163e9fd28667b3a0289ad77e0d2354998f3a0d1ade51d802-removing flavour=1
```

Theyory: failed image downloads eating up disk space and not being included in accounting?

`docker image prune -a` deleted some of the images that were not used but did not free up significant disk space (less than a GB according to Explorer, though Docker itself reported 6.6 GB freed).

I am just going to go and manually delete C:\ProgramData\docker right now so I can continue to use the server.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.05.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.999GiB
Name: vsts-dkr-agt-win
ID: Y5PE:LS7I:ZOMH:CHMC:UW6C:JGEN:TUKE:ZLGT:U6BG:SMYZ:BMHF:LFRC
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Random VM on premise.

**Comment by sandersaares** [comment]
80+ GB was freed after using docker-ci-zap to get rid of the windowfilter directory.

**Comment by thaJeztah** [comment]
Be aware that container logs are not included in the output of `docker system df`, so if you have containers that do a lot of logging, you use the default `json-file` logging driver, and don't have the "max-size" or "max-files" logging options set (hence, no log rotation); log files can consume a lot of space.


I also would recommend updating your version of docker; docker 17.05 has reached end of life in June, and there have been many changes since (including bugfixes in this area)

**Comment by sandersaares** [comment]
First attempt to repro on Windows 1709 with Docker 17.10 showed good result - no unexpected data. I will continue to explore to see if more nontrivial scenarios than what I tried still remain problematic.

**Comment by thaJeztah** [comment]
Thanks for the update; I'll close this issue for now, but feel free to comment if you're still running into this problem
