### ISSUE TITLE
Docker stack naming convention

### ISSUE THREAD

**Issue by robertofabrizi** [moby/moby#35241]
**Description**

Dear Docker developers,
I was wondering if you’d reconsider the current naming convention for services deployed via docker stack (or at least support passing a different naming strategy as an argument).

Currently, deploying a stack named demo will start services called demo_service1, demo_service2, etc.

The problem is, demo_service1 is actually the URL at which that service can be reached by demo_service2, and vice versa, per docker swarm routing policy (which is awesome, btw).

Sadly though, underscores in hostnames are NOT a good idea, as documented in multiple places, and consequently in many programming languages, Java 8 included, parsing an url with an _ in it fails.

Thank you,
Best regards,
Roberto

**Steps to reproduce the issue:**
1. Start any stack via docker stack command

**Describe the results you received:**
The services started via docker stack have a name (and therefore the dns name) line stackname_servicename

**Describe the results you expected:**
-

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens every time as it's according to the specifications

**Output of `docker version`:**
Any

**Output of `docker info`:**
Any

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Any

**Comment by fntlnz** [comment]
Closing since the internal DNS already addresses this issue by resolving both the name containing the stack name and the spefici name of the service. This works because different stacks are given different separated networks.

I'm closing but feel free to discuss in case you need any clarification.

**Comment by robertofabrizi** [comment]
So silly of me, thanks Lorenzo, you've been of great help!

**Comment by fntlnz** [comment]
@robertofabrizi thank you for opening this, can be helpful for people with the same doubt.
