### ISSUE TITLE
Windows Images are incompatible between Windows Server 2016 and Windows Server 1709

### ISSUE THREAD

**Issue by caleblloyd** [moby/moby#35247]
Docker in Windows Server 1709 is not able to run containers with `--isolation process` built against `microsoft/windowsservercore` or `microsoft/nanoserver` that were built for Windows 10 / Windows Server 2016:

![windows-images-not-portable](https://user-images.githubusercontent.com/2414837/31743651-d2d6e36a-b429-11e7-9fe3-990bf7cc33ce.png)

Images built with a mismatched `windowsservercore` or `nanoserver` base fail with the error:

```
The operating system of the container does not match the operating system of the host
```

This issue can be worked around by using `--isolation hyperv`.  It is still a huge problem for the following reasons:

1. Windows images are not portable between mismatched Windows Server versions without Hyper-V Isolation
2. Hyper-V Isolation requires nested virtualization support from the Hypervisor or Cloud Provider
3. This will naturally lead to an explosion of image tags, of which the end user will have to research in-depth to figure out if a tag is supported on their Windows Server platform

Microsoft did not announce this breakage that I'm aware of.  They have given no guidance on whether this is a one-time break, or if it will be recurring.  Will it break again once Windows Server 1803 is released, causing a mass rebuild of all Windows Images every six months?

In most cases, Linux Images are inter-operable on hosts with a minimum kernel version.  Windows Images should be the same way.

I understand that this is no fault of the moby project, but the community needs an official stance from Microsoft on what to expect with Windows Image compatibility going forward.

Related Reading:
- [Windows Server Semi-Annual Channel overview](https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview)
- [Windows Server, version 1709 available for download](https://blogs.technet.microsoft.com/windowsserver/2017/10/17/windows-server-version-1709-available-for-download/)
- [Container Images are now out for Windows Server Version 1709](https://blogs.technet.microsoft.com/virtualization/2017/10/18/container-images-are-now-out-for-windows-server-version-1709/)

**Comment by fntlnz** [comment]
@jhowardmsft PTAL

**Comment by sandersaares** [comment]
This does appear to be documented at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Comment by friism** [comment]
Yeah, unfortunately this is not a bug. I'm trying to get assorted Microsoft teams to adopt manifest lists to make this a bit more seamless: https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/

**Comment by caleblloyd** [comment]
Given the circumstances, I feel like it might be best to make `--isolation hyperv` the engine default on Windows Server.  This would lead to a more familiar experience where images work across host versions.

It would also lead people to discover that they need Hyper-V support in their architecture early on, instead of discovering that they need it the first time they go to upgrade.

**Comment by jhowardmsft** [comment]
There are lots of people trying to figure out the right solution, stay tuned.

**Comment by isanych** [comment]
On windows insider server 1709 16278 I cannot run microsoft/nanoserver:1709 (or any other image I've tried). Hyper v isolation require nested virtualization and should be less efficient than oricess isolation.

**Comment by friism** [comment]
@isanych `16278` is an intermediate insider build. The GA kernel build number for Windows 10 Fall Creators Update and Windows 1709 is `16299`.

**Comment by isanych** [comment]
@friism I understand that, but there is no evaluation for Windows 1709, so I'm using insider build. I was trying to make a point that there is no container compatibility at all. Not just between 2016 and 1709, but also between different builds of 1709 too.

**Comment by friism** [comment]
> there is no container compatibility at all

That's correct!

**Comment by Vacant0mens** [comment]
I've run into this too. 
Apparently `isolation: hyperv` is not allowed in Stack? @friism , Is that by design? Seems like that should be available, unless you're avoiding throwing errors in mixed-platform environments...?

**Comment by friism** [comment]
@Vacant0mens it's just because noone's gotten around to getting it in: https://github.com/moby/moby/issues/31616#issuecomment-342176326

cc @moscowrage @simonferquel

**Comment by olljanat** [comment]
@jhowardmsft now when you allow users to use process isolation mode on Win 10 it would be nice also to look if we can have also at least one version backward compatibility for Windows images? E.g. run 1803 images on 1809.That would make migration process much simpler for users.

**Comment by thaJeztah** [comment]
@olljanat unfortunately (afaik) the issue is not so much the Windows _images_, but Windows itself not being backward compatible.

**Comment by olljanat** [comment]
@thaJeztah afaik code on https://github.com/Microsoft/hcsshim/blob/master/container.go#L67-L79 sends *os.version* value which it can found from manifest to [HCS](https://blogs.technet.microsoft.com/virtualization/2017/01/27/introducing-the-host-compute-service-hcs/) gets response:
> The operating system of the container does not match the operating system of the host.

But is that limitation really needed or is it there just in case?

I understand that it was needed when Windows Server 2016 was released and assumption was that earliest Windows Server 2019 will be next version. But now when there is also semi-annual channel for servers maybe that decision should be reconsidered?

**Comment by thaJeztah** [comment]
> But is that limitation really needed or is it there just in case?

Unfortunately, yes, it's needed. (hoping I'm describing it correct, as I'm not 100% in on the nitty-gritty details), but Windows does not (yet) have a stable kernel API (as is the case for Linux), therefore images based on Windows version X wont' be able to run on a host that's running Windows version Y. (Unless Hyper-V isolation is used, which will use a VM for the container).

**Comment by olljanat** [comment]
@thaJeztah OK. Thanks for information.

For everyone who are facing this issue, I found to way build Docker images for Win 2016, 1709 and 1803 using single Windows Server, version 1803 machine with process isolation mode. I described that process to [olljanat/multi-win-version-aspnet](https://github.com/olljanat/multi-win-version-aspnet)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
