### ISSUE TITLE
panic: interface conversion: http2.Frame is *http2.UnknownFrame, not *http2.HeadersFrame

### ISSUE THREAD

**Issue by ekho** [moby/moby#35259]
**Description**

Sometimes (once every two days or several times a day) docker daemon stops working with message `panic: interface conversion: http2.Frame is *http2.UnknownFrame, not *http2.HeadersFrame` in log

**Steps to reproduce the issue:**
1. Use openstack hosted vm
2. Install docker on vm
3. Run elasticsearch/kibana container from official images
4. Wait day or two
5. Attempt to create, start, or delete containers. 

**Describe the results you received:**
Once the error occurs, docker is unable to create, start, or delete containers. 

**Describe the results you expected:**
Docker to continue working. Ability to manipulate containers. Docker to recover from an error state.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker installed on openstack hosted vm. I think the problem is somewhere in the openstack. But I do not know where to look for the problem. If I understand what the docker reacts to, I can fix it.

Same installation on vmware vm works fine! 

**Output of `docker version`:**

```
(i will paste it here after weekend)
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: /etc/docker-latest/seccomp.json
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 31.26 GiB
Name: domt-el-01.vm.mos.cloud.mycompany.ru
ID: 5TOW:IEU5:TW3M:ZY2C:QTEB:QJ6Z:WFGP:LVDY:VXFT:DZQN:I4GO:HTII
Docker Root Dir: /u01/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- self-hosted openstack
- vm in openstack
- rhel7.3 in vm
- docker 1.13.1 installed with `yum install docker-latest`
- changed `graph` location
- systemctl status docker-latest
```
● docker-latest.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker-latest.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-10-18 12:14:15 MSK; 44min ago
     Docs: http://docs.docker.com
 Main PID: 3487 (dockerd-latest)
   Memory: 23.0M
   CGroup: /system.slice/docker-latest.service
           ├─3487 /usr/bin/dockerd-latest --add-runtime docker-runc=/usr/libexec/docker/docker-runc-latest --default-runtime=docker-runc --authorization-plugin=rhel-push-plugin --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-latest --seccomp-profile=/etc/docker-latest/seccomp.json --config-file=/etc/docker-latest/daemon.json --selinux-enabled
           ├─3503 /usr/bin/docker-containerd-latest -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc --runtime-args --systemd-cgroup=true
           ├─5976 /usr/libexec/docker/docker-proxy-latest -proto tcp -host-ip 0.0.0.0 -host-port 9300 -container-ip 172.18.0.2 -container-port 9300
           ├─5987 /usr/libexec/docker/docker-proxy-latest -proto tcp -host-ip 0.0.0.0 -host-port 9200 -container-ip 172.18.0.2 -container-port 9200
           └─5992 /usr/bin/docker-containerd-shim-latest 1c5c327e0b88bd3bdc138eb7b689fc576d29a9cf3ae88706a32494159846025d /var/run/docker/libcontainerd/1c5c327e0b88bd3bdc138eb7b689fc576d29a9cf3ae88706a32494159846025d /usr/libexec/docker/docker-runc-latest
```
- daemon.json
```json
{
   "insecure-registries":[],
   "log-driver":"journald",
   "graph":"/u01/var/lib/docker",
   "signature-verification":false,
   "log-level":"info",
   "storage-driver":"overlay",
   "live-restore":true
}
```
- /var/log/messages with error message and trace log https://gist.github.com/ekho/7c01e22897a807defa5ca1340672626e

**Comment by thaJeztah** [comment]
It looks like you're running the Red Hat fork of Docker, which contains a large amount of modifications from the official version; we won't be able to help you with that version, as it's not maintained here (you can open a ticket with Red Hat). Keep in mind that Docker 1.13.x has reached end of life, and is no longer maintained.

I'm closing this issue because of the above, but feel free to comment after I closed.

**Comment by ekho** [comment]
I'm not asking to fix docker. I ask you to tell me where I should to look for the problem.

**Comment by thaJeztah** [comment]
The GitHub issue tracker is not the right location for that, and not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)
