### ISSUE TITLE
Add Artful dist for Ubuntu

### ISSUE THREAD

**Issue by imaia** [moby/moby#35254]
Ubuntu 17.10, artful, launched today, but docker cannot be installed for it from repo.

https://download.docker.com/linux/ubuntu/dists/artful is not available.

**Comment by fntlnz** [comment]
Hi @imaia , thanks for reporting. This project does not handle packaging related to the downstream projects. Can you please report in https://github.com/docker/docker-ce-packaging ? Thank you.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker-ce-packaging/pull/55

**Comment by imaia** [comment]
I can, @fntlnz Thanks
