### ISSUE TITLE
unable to use bridge network in docker swarm to access host

### ISSUE THREAD

**Issue by danhaywood** [moby/moby#35262]
**Description**

I'm trying to use the bridge network in a docker swarm to access a service on the host, but cannot.

In trying to solve my issue, I came across an existing ticket https://github.com/moby/moby/issues/32957#issuecomment-312858586

and followed suggestion by @cpuguy83 .  While what he suggested worked for that case (and the ticket was therefore closed), it fails for me.  
 

**Steps to reproduce the issue:**

As per @cpuguy83 's suggestion:

<pre>
$ cat test.yml
version: "3.3"

services:
  test:
    image: busybox
    command: top
    networks:
      - bridge

networks:
  bridge:
    external:
      name: bridge

$ docker stack deploy -c test.yml test
</pre>

**Describe the results you received:**

I get the error:

<pre>
network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"
</pre>

**Describe the results you expected:**

Was hoping this would let me connect to that network.

**Additional information you deem important (e.g. issue happens only occasionally):**

When I run `docker network ls`, I see:

```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
68d2263f870e        bridge              bridge              local
a00a5d9be1ee        docker_gwbridge     bridge              local
c08e94cfc37f        host                host                local
quswu6tdfkqi        ingress             overlay             swarm
ae3d21344142        none                null                local
```

So, the error I'm seeing does kind-of make sense: bridge scope is indeed "local and not "swarm".  In which case my issue may instead be simply: *how do I configure "bridge" to have a scope of swarm* (or how do I set up an equivalent network to accomplish the same)?

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 10
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: w94atrsj1w74lkebioh24rjbl
 Is Manager: true
 ClusterID: 4bhnw7ehztltyha6hsxx4sxrt
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: UYLU:I5AH:BGCF:HZDU:35B2:4UXH:CJPQ:MMY7:DPFA:72YB:ARYB:JLRR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 142
 System Time: 2017-10-20T11:01:57.9707453Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 Pro.

**Comment by friism** [comment]
Are you trying to access a service on the Windows host? In that case, just use `docker.for.win.localhost`:  https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17060-ce-win18-2017-06-28-stable

**Comment by danhaywood** [comment]
Yes, that is what I'm trying to do... have a webapp in a Tomcat container access SQL Express on the Windows host.

I'll try out `docker.for.win.localhost` and report back.

Is the approach I was trying to take, of using the `bridge` network to, well, to bridge out, fundamentally wrong, though?

**Comment by imriss** [comment]
I am facing similar error of "local" instead of "swarm". The `VM` is `Ubuntu16.04` managed by `Vagrant` with `Virtualbox` as the provider on a `Windows 10` machine.

I an following the solution proposed [here](https://github.com/moby/moby/issues/15086#issuecomment-337501603) to expose client's IP to the containers. 

The `network create` command used:
`docker network create -d bridge --subnet 192.168.10.0/24 --gateway 192.168.10.1 dockernet
`

**Comment by danhaywood** [comment]
As per https://github.com/moby/moby/issues/32957#issuecomment-342774757, it seems that the network must be created first, and it's not valid to use bridge network.

create the network:

    docker network create -d overlay testservice

with a stack file:

```` yml
version: "3.3"

services:
  test:
    image: busybox
    command: top
    networks:
      - testservice

networks:
  testservice:
    external:
      name: testservice
````

and run using:

    docker stack deploy -c test.yml teststack

This works for me on Docker version 17.09.0-ce, build afdb6d4.

 I guess some documentation could be improved, but otherwise I'm gonna close this ticket.
