### ISSUE TITLE
tmpfs-size not working for service mount

### ISSUE THREAD

**Issue by EliSnow** [moby/moby#35271]
Using tmpfs as a workaround for #26714, no longer seems to work.

I used the following command to start a service with a tmpfs mount on `/dev/shm`:

```
docker service create \
  --name tmpfstest \
  --mount type=tmpfs,dst=/dev/shm,tmpfs-size=1000000000 \
  --tty \
  debian:stretch-slim cat
```

This worked as of Docker 17.06.2, but there appears to be a regression and starting at least with 17.09-rc1 (I tested it with 17.09 and 17.10 as well) it no longer works.

Using `df -k /dev/shm` I get the following output on new versions of Docker:

```
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs              65536     4     65532   1% /dev/shm
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I don't think it matters for this issue, but this was all tested in boot2docker VirtualBox VM.

**Comment by fractalawareness** [comment]
Same here. Is there another workaround?

**Comment by EliSnow** [comment]
I am not aware of a workaround. I had to move manually roll my dev VMs back to 17.06.2

**Comment by thaJeztah** [comment]
It looks to be specific to the default (`/dev/shm`) location. Using another location for the tmpfs seems to work;

```bash
docker service create \
 --name tmpfstest \
 --mount type=tmpfs,dst=/foo,tmpfs-size=1000000000 \
 --tty \
 alpine sh
```

Inside the container;

```
/ # df -k /foo
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                   976564         0    976564   0% /foo
```

Wonder if it's a runtime issue (`containerd` or `runc`)

**Comment by thaJeztah** [comment]
Discussing internally; this should not be a containerd or runc issue, so I'll have to dig into what changed between these versions

**Comment by kolyshkin** [comment]
Reproduced with `docker run --mount type=tmpfs,dst=/dev/shm,tmpfs-size=100 -it --rm --ipc none alpine df /dev/shm`

A workaround (using `docker run`) would be to use `--ipc=private --shm-size=NNNNN` which is essentially the same as above.

@EliSnow @fractalawareness may I ask what is the reason for you to have own /dev/shm mount?

**Comment by thaJeztah** [comment]
@kolyshkin IIRC, `--shm-size` is not supported for services, so this was the approach to do the same for services

**Comment by kolyshkin** [comment]
@thaJeztah I thought maybe the reason is to avoid a bind mount from the host (i.e. same as `--ipc private`).

Anyway, I'll send a PR soon

**Comment by bzcnsh** [comment]
Hi, just to clarify. this tempfs, /dev/shm feature is for memory based temporary file system, not a form of IPC?
the IPC keyword is not supported by "docker stack deploy" as of compose file version 3.5, so I am looking for alternatives and came across this.

**Comment by thaJeztah** [comment]
@bzcnsh correct, it's just a tmpfs.


Looking at this issue, this should now be resolved through https://github.com/moby/moby/pull/35316

testing on Docker 17.12:

```bash
docker service create \
  --name tmpfstest \
  --mount type=tmpfs,dst=/dev/shm,tmpfs-size=1M \
  --tty \
  debian:stretch-slim cat
```

```bash
docker exec de558eab0023 df -h /dev/shm

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.0M     0  1.0M   0% /dev/shm
```

**Comment by bzcnsh** [comment]
@thaJeztah thank you!
