### ISSUE TITLE
From a metric/monitoring perspective, how exactly does container CPU load relate to host CPU load?

### ISSUE THREAD

**Issue by juliohm1978** [moby/moby#35282]
I'm using Docker 17 on one my servers to run a number of applications.

```
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

For clarity, there are no orchestrators deployed; no Docker Swar, no Kubernetes. Given the small number of apps (35 containers in total), I'm orchestrating containers manually using docker-compose or simply `docker run`.

Among the apps, I have a cAdvisor/Prometheus/Grafana stack that serves to monitor my one-host-cluster. Recently, I noticed a strange behavior while manually configuring `--cpu` and `--memory` for every individual container.

Initially, I ran some tests by giving most containers a very small ammount of CPU shares: `--cpu "0.5"`. Everything came up normally until I looked at the history of CPU load on the host. Even though it had plenty of CPU resources unused, the host reported absurd CPU loads, as high as 50 ou 80.

Obviously, my containers were starving. It seems that each one reported a high CPU load and, from the host's perspective, the kernel seems to be adding all of them together. Only after adjusting container cpus to a resonable size (i.e. `--cpu 2` per container) the host load went back to normal.

So, my question: Is this expected behavior? Looking at the host CPU load, am I actually looking at the sum of the load of all containers?

**Comment by thaJeztah** [comment]
Can you provide the output of `docker info` as well, and the exact steps you're using; you mention using `--cpu`; did you mean `--cpus` ? `--cpu-shares`? Specifying `--cpus 0.5` for 35 containers will give a total amount of 17 CPUs to be available to those containers

**Comment by juliohm1978** [comment]
Should `docker info` be done on the host under stress? Or can I just take it now with cpus already adjusted?

**Comment by juliohm1978** [comment]
To complete the answer:

I was using `docker run --cpu "0.5" --memory 200m ...` and similar parameters to most containers.

**Comment by thaJeztah** [comment]
There is no `--cpu` flag on `docker run` (did you mean `--cpus` ?)

**Comment by juliohm1978** [comment]
Yes, my bad. `docker run --cpus` is what I meant.

**Comment by ripcurld0** [comment]
Closing this issue.
Thank you @juliohm1978
