### ISSUE TITLE
Some container's memory usage stats via CLI and API are different

### ISSUE THREAD

**Issue by ZigmunD** [moby/moby#35295]
**Description**
```
zigmund@docker-w2.alanls.kz.prod:~$ docker stats ab86906e5296 --no-stream 
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
ab86906e5296        39.98%              2.996GiB / 6GiB     49.94%              315GB / 319GB       39.5GB / 12.3kB     2165
zigmund@docker-w2.alanls.kz.prod:~$ curl localhost:2375/containers/ab86906e5296/stats?stream=false -s | jq '.memory_stats.usage/1024/1024/1024' 
4.955738067626953
```

**Steps to reproduce the issue:**
1. Query stats via CLI
2. Query stats via API
3. See the difference

**Describe the results you received:**
Memory usage stats via CLI and API are different

**Describe the results you expected:**
Memory usage stats via CLI and API are same

**Additional information you deem important (e.g. issue happens only occasionally):**
At the time only containers based on yandex/clickhouse-server are affected. Other container's stats are same via CLI and API.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 27
 Running: 21
 Paused: 0
 Stopped: 6
Images: 11
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xyavkf8h8b0135qgjv3fzl7o6
 Is Manager: false
 Node Address: 10.33.243.12
 Manager Addresses:
  10.33.243.1:2377
  10.33.243.2:2377
  10.33.243.3:2377
  10.33.243.4:2377
  10.33.243.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.0-14-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.794GiB
Name: docker-w2
ID: E3DU:HI77:WAWR:UHTP:DN7J:7GL7:XSY7:6RCL:R7UK:FQDW:KXWT:ZPHE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Proxmox VM, Ubuntu 16.04.3 LTS

**Comment by cpuguy83** [comment]
Here is how the CLI calculates memory:

```
// calculateMemUsageUnixNoCache calculate memory usage of the container.
// Page cache is intentionally excluded to avoid misinterpretation of the output.
func calculateMemUsageUnixNoCache(mem types.MemoryStats) float64 {
	return float64(mem.Usage - mem.Stats["cache"])
}
```

**Comment by ZigmunD** [comment]
@cpuguy83 well, I think that API output should be exactly the sameas CLI.

**Comment by cpuguy83** [comment]
@ZigmunD Why? The API provides tons more detail than the CLI does.

**Comment by ZigmunD** [comment]
@cpuguy83 because it is same metric in CLI and API? MEM USAGE == memory_stats.usage?
Or just change the name of metric in CLI or API to exclude misunderstanding?

**Comment by cpuguy83** [comment]
The API leaves up to the client to interpret. The Docker CLI has decided to represent the actual memory usage without the page cache included.

**Comment by ZigmunD** [comment]
@cpuguy83 that is not obvious. Metric names in CLI and API are same, but values are different.

**Comment by ZigmunD** [comment]
I can and will change logic in my client, but...

**Comment by ZigmunD** [comment]
```
// Page cache is intentionally excluded to avoid misinterpretation of the output.
```
Why don't you do the same with API?

**Comment by cpuguy83** [comment]
Because the API provides all the data, the total memory charged to the particular cgroup as well as the page cache in use by the cgroup.
The stats themselves are pretty low-level from the cgroup data (on Linux).

**Comment by ZigmunD** [comment]
Then it should be documented.
Again. Metric names are same in CLI and API, but values are not.

https://docs.docker.com/engine/reference/commandline/stats/
https://docs.docker.com/engine/api/v1.32/#operation/ContainerStats
Nothing about that.

**Comment by cpuguy83** [comment]
docker/cli#641

**Comment by ZigmunD** [comment]
Thanks!
