### ISSUE TITLE
Unable to mount new drive in container

### ISSUE THREAD

**Issue by sprutton1** [moby/moby#35299]
**Description**

Per this [forum post](https://forums.docker.com/t/unable-to-mount-new-drive-in-container-anymore/40326). @jhowardmsft 
A drive that I create in a Windows container using the --volume command and specifying a single drive letter is not accessible as of the 17.09+ version of Docker for Windows.

**Steps to reproduce the issue:**
1. Use Windows containers
2. Run ```docker run -it -v m: microsoft/windowsservercore powershell```

**Describe the results you received:**
```Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.``` in the shell. I am unable to access the m:\ drive in the container. 

**Describe the results you expected:**
The m:\ drive should be created and accessible in the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
If I inspect the drive using ```fsutil fsinfo driveType m:```, I get the following:
```m: - Remote/Network Drive```

Running the same command on 17.06, I get the following:
```m: - Fixed Drive```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-1700)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.89GiB
Name: DEV-029758
ID: FCMU:6LOG:3OZG:AWLE:VWAA:35NK:R4ET:OW7V:IVXD:ZDQI:CCSX:QJE7
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2017-10-25T15:48:12.8979543-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jhowardmsft** [comment]
Is `m:` the local drive or the container target drive? Certainly this works:

```
PS C:\> docker run --rm -v c:\baseimages:d: microsoft/nanoserver cmd /s /c dir d:\

 Directory of d:\

10/19/2017  10:04 AM    <DIR>          .
10/19/2017  10:04 AM    <DIR>          ..
09/23/2017  04:11 AM     2,264,214,316 CBaseOs_rs3_release_16299.0.170922-1354_amd64fre_ServerDatacenterCore_en-us.tar.gz
09/29/2017  10:54 AM     2,274,300,585 CBaseOs_rs3_release_16299.15.170928-1534_amd64fre_ServerDatacenterCore_en-us.tar.gz
09/29/2017  01:45 PM        81,042,432 nanoserver.tar
09/29/2017  01:45 PM     2,274,303,488 windowsservercore.tar
               4 File(s)  6,893,860,821 bytes
               2 Dir(s)  101,717,868,544 bytes free
PS C:\>
```

**Comment by sprutton1** [comment]
```m:``` is the container target drive. 

Your example works, but if I try to use PowerShell to do the same thing, I get the Initialization error and the drive is not found. So, maybe this is a problem with Powershell being unable to mount the volume correctly. This happens on both nano and servercore.

```
C:\ > docker run --rm -v c:\baseimages:d: microsoft/nanoserver powershell ls d:
Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.
ls : Cannot find drive. A drive with the name 'd' does not exist.
At line:1 char:1
+ ls d:
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (d:String) [Get-ChildItem], Driv
   eNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetC
   hildItemCommand

C:\ >
```

**Comment by sprutton1** [comment]
Looking into this further, I believe that it is an issue with Docker for Windows and not specific to version 17.09. The 17.06 version where this works for me was on a Server 2016 box. My 17.09 version is on Windows 10 using Docker for Windows. We were able to recreate the issue on a Windows 10 box using Docker for Windows version 17.06.

**Comment by jmlane** [comment]
I was able to reproduce this issue error on Windows 10 v1709 with Docker for Windows 17.12.0-ce.

`docker run -it -v d: microsoft/windowsservercore powershell` will start the container, load powershell, and error with:
> Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.

As @sprutton1 mentioned, `fsutil` will report a remote/network drive with corresponding to the volume bind.

If you use the `cmd` shell, the volume is available on D: as you would expect.

You *can* mount the volume to the system drive (C:) without a problem. Changing the volume mount destination path to a directory on a non-system-drive results in the same error and inaccessible volume.

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
