### ISSUE TITLE
LCOW: how to set ulimit on lcow 

### ISSUE THREAD

**Issue by mlmeyers** [moby/moby#35298]
**Description**

After updating to lcow (17.10.0-ce, build f4ffd25) I started to encounter errors when running several linux containers in regards to the ulimits being set to default 1024. I attempted to update my compose file but receive an error stating it is not supported on windows, also tried updates in the daemon.json file. At current I am not able to find a way to increase ulimits on windows.

**Steps to reproduce the issue:**
1. update a compose file for ulimits

 ulimits:
      nofile:
        soft: 32000
        hard: 40000

update deamon.json with: 

 "default-ulimits": {
		"nofile": {
			"Name": "nofile",
			"Hard": 40000,
			"Soft": 30000
		}
	}

I also tried with: 

"default-ulimit": {
		"nofile": {
			"Name": "nofile",
			"Hard": 40000,
			"Soft": 30000
		}
	}

**Describe the results you received:**

Using compose.yml:

Invalid option: Windows does not support Ulimits

Using defaults-ulimits:

The following directives don't match any configuration option: default-ulimits

Using defaults-ulimit:

The following directives don't match any configuration option: nofile

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.10.0-ce, build f4ffd25
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.10.0-ce
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.84GiB
Name: LAPTOP-82U8ONK8
ID: JUA6:R5B4:27H4:GSAO:PKWO:GME2:K24S:FNA2:LI6N:KFN5:6FJI:F2RV
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2017-10-25T13:52:51.4575925-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL

**Comment by jhowardmsft** [comment]
Many things remain unimplemented in LCOW, this being one of them.

**Comment by friism** [comment]
@jhowardmsft would it be possible to warn or error in case un-supported options are passed?

**Comment by jhowardmsft** [comment]
@friism Well yes, but lets get more important functionality merged first. Such as https://github.com/moby/moby/pull/34859 and others backed up behind it first.

**Comment by nekenk1** [comment]
+1

**Comment by ArnabKalita** [comment]
Hello all, has this feature been implemented yet ? Do we expect to see this feature implemented in the newer versions of Docker in the future ?

**Comment by gomez34** [comment]
Hello all, has this feature been implemented yet ?

**Comment by oshz** [comment]
Hi, any luck with this?

**Comment by eriksimonic** [comment]
+1

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
