### ISSUE TITLE
Devicemapper fails on bonnie++ test

### ISSUE THREAD

**Issue by delfer** [moby/moby#35309]
**Description**

Devicemapper fails on bonnie++ test when using >4Gb / >8Gb files (bonnie uses disk=2*RAM)

**Steps to reproduce the issue:**
1. Configure docker to use devicemapper (no care loop or thinpool)
2. Run `docker run -ti ariarijp/bonnie -d /tmp -u root`

**Describe the results you received:**
```
Using uid:0, gid:0.
Writing a byte at a time...done
Writing intelligently...Can't write block.: No such file or directory
Can't write block 1277407.
```

**Describe the results you expected:**
_Test results._

**Additional information you deem important (e.g. issue happens only occasionally):**
Overlay, overlay2, aufs, btrfs, zfs, vfs, host direcory works. devicemapper - not.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 1
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 91.11GB
 Data Space Total: 130.6GB
 Data Space Available: 39.45GB
 Metadata Space Used: 6.033MB
 Metadata Space Total: 1.372GB
 Metadata Space Available: 1.366GB
 Thin Pool Minimum Free Space: 13.06GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: loadtest
ID: N6HT:CHLJ:545Y:NGOT:HGXV:NK7W:ZEP3:DZWG:CH5N:D2TV:OKLR:F5LV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM in VMware ESXi, 5.5.0, 2068190

_/etc/docker/daemon.json_
```
{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.directlvm_device=/dev/sdb"
  ]
}
```

_Dockerfile_
```
FROM ubuntu:14.04
MAINTAINER Takuya Arita <takuya.arita@gmail.com>

# Install Dependencies
RUN apt-get update && apt-get install -y bonnie++

# Run bonnie++
ENTRYPOINT ["bonnie++"]
```

**Another attempts**
`docker run -ti --memory=4G ariarijp/bonnie -r 4096 -d /tmp -u root` **works** 4Gb RAM 8Gb files
`docker run -ti --memory=5G ariarijp/bonnie -r 5120 -d /tmp -u root` **not works** 5Gb RAM 10GB files
`docker run -ti --memory=4G ariarijp/bonnie -r 4096 -s 9977 -d /tmp -u root` **works** 4Gb RAM 9977Mb files
`docker run -ti --memory=4G ariarijp/bonnie -r 4096 -s 9978 -d /tmp -u root` **not works** 4Gb RAM 9978Mb files (it varies +- megabyte)

**Comment by thaJeztah** [comment]
Sounds like you're trying to write more than is available in the created device;

    Base Device Size: 10.74GB

You can specify a different size in the storage options for devicemapper

**Comment by thaJeztah** [comment]
However, if you're doing a lot of writing, it's best to define a volume for the location where writes happen; there's a big performance penalty when doing many writes to copy-on-write filesystems

**Comment by delfer** [comment]
@thaJeztah you are right. The problem is in `Base Device Size`.
The following config works fine
```
{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.directlvm_device=/dev/sdb",
    "dm.basesize=40G"
  ]
}
```
I've found this solution on https://forums.docker.com/t/increase-container-volume-disk-size/1652/7
But I can't see any information on https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

**Comment by thaJeztah** [comment]
Good to hear that worked! Hm, yes, the option itself is documented in https://docs.docker.com/engine/reference/commandline/dockerd/#options-per-storage-driver, but I agree it would be good to document it in the user guide.

Could you open an issue (or even better, a pull request :smile:) in the documentation repository for that? 
https://github.com/docker/docker.github.io

**Comment by thaJeztah** [comment]
When documenting, we should make sure to also mention there's a performance impact (at least I recall there was one); because initialising the device takes longer IIRC)

**Comment by thaJeztah** [comment]
Let me close this issue for housekeeping, but if you could post a link here to the issue you opened in the docs repository, that would be great!
