### ISSUE TITLE
Error grabbing logs: EOF

### ISSUE THREAD

**Issue by whitecolor** [moby/moby#35319]
OS: Windows 10 WSL (Ubuntu)
Docker for windows: Version 17.09.0-ce-win33 (13620)
Compose `1.17.0-rc1` / `1.16.1` (installed on WSL)

When starting containers **periodically** get the error `Error grabbing logs: EOF`
![image](https://user-images.githubusercontent.com/736697/31863834-1a03b5f2-b708-11e7-912b-97b0c1bc381c.png)

The command is run: `docker-compose logs --tail 10 --follow [services]`

Seems like an issue with `tail` flag. Don't know if it is a duplicate.

Issue is also described here:
https://github.com/docker/for-win/issues/1235

**Comment by thaJeztah** [comment]
I see there's already an active discussion on that issue, let's close this one for now to not let the discussion diverge.

**Comment by whitecolor** [comment]
@thaJeztah can you point out the discussion, for me to track it.

**Comment by thaJeztah** [comment]
@whitecolor the other issue you opened i docker/for-win

**Comment by luckygoodness** [comment]
no need

**Comment by philipp22** [comment]
The same error occurred for me when I tried to start a container that was relying on a non-existent network. Could this be the case for you?

**Comment by whitecolor** [comment]
> container that was relying on a non-existent network

What you mean by `non-existent network`? After I get an error next time I restart the container and get logs it works ok.

**Comment by philipp22** [comment]
I ran the container with the --network flag, specifying a network that did not exist. However, if it works for you after restarting the container your problem is likely to be a different one.

**Comment by thaJeztah** [comment]
Sounds like this may be fixed through https://github.com/moby/moby/pull/36305 (it's not in a release yet)
