### ISSUE TITLE
`docker restart -t` with negative input time return different results after change the backend

### ISSUE THREAD

**Issue by jshachm** [moby/moby#35311]
**Description**
After the PR #32237, we have changed the Container Wait Backend. However, this pr leads some different behavior to `docker restart -t` 

**Steps to reproduce the issue:**
1. `docker restart -t -100  $containerID` in the early version 1.11.2 
     `docker` will wait utils container to  exit elegantly
2. `docker restart -t -100  $containerID` in the latest version 17.x
      `docker` will stop the containerd immediately.

**Describe the results you expected:**

As the code code annotation before the PR:
```
container/state.go

//WaitStop waits until state is stopped. If state already stopped it returns
//immediately. If you want wait forever you must supply negative timeout.
//Returns exit code, that was passed to SetStopped
```

**Code check:**

The reason why the difference happens lays in the function realization of `wait`

Before the PR, negative timeout is handled by `wait`  func:
```
func wait(waitChan <-chan struct{}, timeout time.Duration) error {
	if timeout < 0 {
		<-waitChan
		return nil
	}
	select {
	case <-time.After(timeout):
		return fmt.Errorf("Timed out: %v", timeout)
	case <-waitChan:
		return nil
	}
}
```
negative restart timeout will be hold on until elegantly exit.

After the PR, we use `context.WithTimeout` to realize the `Wait` func:
```
func WithDeadline(parent Context, deadline time.Time) (Context, CancelFunc) {
	if cur, ok := parent.Deadline(); ok && cur.Before(deadline) {
		// The current deadline is already sooner than the new one.
		return WithCancel(parent)
	}
	c := &timerCtx{
		cancelCtx: newCancelCtx(parent),
		deadline:  deadline,
	}
	propagateCancel(parent, c)
	d := time.Until(deadline)
	if d <= 0 {
		c.cancel(true, DeadlineExceeded) // deadline has already passed
		return c, func() { c.cancel(true, Canceled) }
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.err == nil {
		c.timer = time.AfterFunc(d, func() {
			c.cancel(true, DeadlineExceeded)
		})
	}
	return c, func() { c.cancel(true, Canceled) }
}

```
Negative restart timeout will be returned immediately.

I want to know if this is a bug due to the PR #32237 ? 
AND If this is a bug ,maybe I can fix it.

**Comment by jshachm** [comment]
ping @theadactyl  @cpuguy83 @ripcurld0 @tonistiigi

**Comment by jshachm** [comment]
@cpuguy83 Any idea？

**Comment by thaJeztah** [comment]
ping @kolyshkin @jlhawn PTAL
