### ISSUE TITLE
'docker service update --host-add' does not update existing host entry

### ISSUE THREAD

**Issue by renskiy** [moby/moby#35325]
`docker service update` with `--host-add host:new-ip` option does not replace existing host IP, but instead adds new record with new IP. I expect that service update will replace 'host:old-ip' by 'host:new-ip'.

Docker version
```
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:03:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Steps to reproduce
1. Create service with 'foo:127.0.0.1' host mapping:
```
$ docker service create --name my-service --host foo:127.0.0.1 nginx:alpine
aw24vyvlgp7aiaf9g5sstfyes
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged
```
2. Change IP for host 'foo':
```
$ docker service update --host-add foo:127.0.0.2 my-service
my-service
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged
```
3. Check hosts mapping:
```
$ docker service inspect --format '{{.Spec.TaskTemplate.ContainerSpec.Hosts}}' my-service
[127.0.0.1 foo 127.0.0.2 foo]
```

**Comment by thaJeztah** [comment]
Thanks for reporting, but this is the expected behaviour; host-entries do not have to be unique in an `/etc/hosts` file, take for example the [hosts(5) ](http://man7.org/linux/man-pages/man5/hosts.5.html)  man-page, having both the IPv4 and IPv6 address for localhost:

```
# The following lines are desirable for IPv4 capable hosts
127.0.0.1       localhost

# 127.0.1.1 is often used for the FQDN of the machine
127.0.1.1       thishost.mydomain.org  thishost
192.168.1.10    foo.mydomain.org       foo
192.168.1.13    bar.mydomain.org       bar
146.82.138.7    master.debian.org      master
209.237.226.90  www.opensource.org

# The following lines are desirable for IPv6 capable hosts
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

Depending on the [configuration in `/etc/host.conf`](http://man7.org/linux/man-pages/man5/host.conf.5.html), the _first_ IP-address, or _all_ IP-addresses are returned when looking up a hostname:

```
       multi  Valid values are on and off.  If set to on, the resolver
              library will return all valid addresses for a host that
              appears in the /etc/hosts file, instead of only the first.
              This is off by default, as it may cause a substantial
              performance loss at sites with large hosts files.
```

To replace a host entry, you'll have to `--host-rm` first, before adding the new entry;

```bash
$ docker service create --name my-service --host foo:127.0.0.1 nginx:alpine
$ docker service update --host-rm foo:127.0.0.1 my-service
$ docker service update --host-add foo:127.0.0.2 my-service
$ docker service inspect --format '{{.Spec.TaskTemplate.ContainerSpec.Hosts}}' my-service
[127.0.0.2 foo]
```

Having said the above; When writing that example, I noticed there's an issue with `--host-rm`/`--host-add`;

```bash
$ docker service create --name my-service --host foo:127.0.0.1  --host foo:127.0.0.2 --host foo:127.0.0.3 nginx:alpine

$ docker service inspect --format '{{.Spec.TaskTemplate.ContainerSpec.Hosts}}' my-service
[127.0.0.1 foo 127.0.0.2 foo 127.0.0.3 foo]
```

It looks like `--host-rm` only takes the `hostname` into account, and removes all entries, whereas it should be specific and only remove a specific entry;
```bash
$ docker service update --host-rm foo:127.0.0.1 my-service
$ docker service inspect --format '{{.Spec.TaskTemplate.ContainerSpec.Hosts}}' my-service
[]
```

 I'll open an issue/pull request to address that
 
 After that is fixed, you should be able to combine `--host-rm` and `--host-add` in a single `docker service update`;

```bash
$ docker service update --host-rm foo:127.0.0.1 --host-add foo:127.0.0.2 my-service
```

Or remove all entries for a host by omitting the `:<ip-address>` part:

```bash
$ docker service update --host-rm foo myservice
```

I also noticed that the `--host-add` flag's description is a misleading, as it will not **update** an entry:

```none
--host-add    Add or update a custom host-to-IP mapping (host:ip)
```

I'll open a separate PR for that.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/pull/648 for the flag description

**Comment by renskiy** [comment]
@thaJeztah thanks

**Comment by renskiy** [comment]
@thaJeztah what about secrets? How can I remove particular secret from two where both of secrets have same `SecretName`/`SecretID` but different `File.Name`?

**Comment by thaJeztah** [comment]
For secrets (and configs), `--secret-rm` currently works by name/id. I originally thought this was a bug, but it's actually something that can be enhanced: for now, you'd have to re-add the secret if you want to just replace (or remove) one of them, but in future we can add an option to be more specific (i.e. `--secret-rm foo` will remove all occurrences of the secret, whereas `--secret-rm source=foo,target=/path/one` will only remove the entry for the secret that was mounted at `/path/one`). You can find the discussion in https://github.com/moby/moby/issues/28956, and https://github.com/moby/moby/issues/28956#issuecomment-263752908 explains that enhancement.

A quick status update: I'm currently playing around with fixing the `--host-rm` functionality, but it's a bit more complicated. The reason for this is that, even though the CLI does not support this, the Swarm Service definition allows a host-entry to have both a canonical host-name and aliases (modelled after the format that's used in `/etc/hosts`), i.e. 

    127.0.0.3 canonical-hostname alias1 alias2 alias3
    127.0.0.4 canonical-hostname2 alias2

I've started with writing some unit-tests, and am working on writing up code to make those tests pass, and allow (e.g.) `--host-rm alias2` to remove the `alias2` entry from that line, and `--host-rm alias2:127.0.0.4` to only remove the alias from the second entry.

I should check the specs for `/etc/hosts` if this is the correct approach as well (but it's a nice task for the weekend :smile:)

**Comment by renskiy** [comment]
@thaJeztah thanks again! Wish you nice weekend! 😄

**Comment by luckygoodness** [comment]
and you too but am in need can you help me

**Comment by thaJeztah** [comment]
Ugh spam bot; already reported that account, and removed the comment
