### ISSUE TITLE
docker top api doesn't behave like ps -ef as is documented

### ISSUE THREAD

**Issue by fwanggg** [moby/moby#35322]
**Description**
`docker top <containerID>` should by default return same result as if you are doing `ps -ef` in the container. This is documented, say V1.24 docker API.
https://docs.docker.com/engine/api/v1.24/
"Query parameters:

ps_args – ps arguments to use (e.g., aux), defaults to -ef"

**Steps to reproduce the issue:**
1. download minishift and start minishift
2. minishift ssh to VM
3. docker top on any runnning container

**Describe the results you received:**

```docker@minishift:~$ docker top c37
PID                 USER                COMMAND
6475                tc                  {standalone.sh} /bin/sh /wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
6647                tc                  java -D[Standalone] -server -XX:+UseParallelGC -Xms40m -Xmx256m -XX:+AggressiveOpts -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dorg.apache.tomcat.util.LOW_MEMORY=true -DOPENSHIFT_APP_UUID= -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Djboss.node.name=fan-wildfly-2-twhnd -Djgroups.bind_addr=0.0.0.0 -Dorg.apache.coyote.http11.Http11Protocol.COMPRESSION=on -Dorg.jboss.boot.log.file=/wildfly/standalone/log/server.log -Dlogging.configuration=file:/wildfly/standalone/configuration/logging.properties -jar /wildfly/jboss-modules.jar -mp /wildfly/provided_modules:/wildfly/modules org.jboss.as.standalone -Djboss.home.dir=/wildfly -Djboss.server.base.dir=/wildfly/standalone -b 0.0.0.0 -bmanagement 0.0.0.0
```

**Describe the results you expected:**

```
bash-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 16:14 ?        00:00:00 /bin/sh /wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
default    163     1  4 16:14 ?        00:09:44 java -D[Standalone] -server -XX:+UseParallelGC -Xms40m -Xmx256m -XX:+AggressiveOpts -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:Ad
```
**Additional information you deem important (e.g. issue happens only occasionally):**
always reproducible
**Output of `docker version`:**

```
docker@minishift:~$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
docker@minishift:~$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
docker@minishift:~$ docker info
Containers: 28
 Running: 11
 Paused: 0
 Stopped: 17
Images: 14
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-boot2docker
Operating System: Minishift Boot2Docker ISO Version: 1.2.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: minishift
ID: W6TJ:ZWT4:ZPGW:AMOZ:QN3G:OLO5:S566:CGEZ:ZVFP:XRXM:EZXZ:ALUR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 95
 Goroutines: 86
 System Time: 2017-10-27T20:10:00.566488403Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=kvm
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
openshift(minishift)

**Comment by cpuguy83** [comment]
`docker top` is actually execing `ps` on the docker host.
If the host doesn't support `ef` then `docker top` will not support it.

**Comment by 2erowf** [comment]
Both the host and container supports "ps -ef"
I've attached ps -ef result in container in "Describe the results you expected:" section of the bug report.
Here is the ps -ef result in host:
root      1312     1  1 07:25 ?        00:08:20 /usr/local/bin/dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=kvm --insecure-registry 172.30.0.0/16 --tlsverify --tlscacert
root      1320  1312  0 07:25 ?        00:00:33 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --sta
root      1672  1320  0 07:25 ?        00:00:04 docker-containerd-shim ab32cc03d1ae0f1caa7e79605d240c6b26ce0a2bb8ffb02018fc4cf7bbe96f6d /var/run/docker/libcontainerd/ab32cc03d1ae0f1caa7e79605d240c6b26ce0a

ps -ef always return 7 titles, but docker top returns 3 titles(PPID,PID,COMMAND).

Can you please point me to the code where docker top is responded?

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/blob/master/daemon/top_unix.go#L120
