### ISSUE TITLE
Docker daemon fails to start of events.log is corrupted

### ISSUE THREAD

**Issue by rom-stratoscale** [moby/moby#35331]
Hey,

Running node crash scenarios with docker daemon version 17.03.2-ce.
The crash is performed using 'echo c > /proc/sysrq-trigger' command.

Sometimes, after the node reboots, docker daemon fails to start.
Tried to run it manually and got the following error:

[root@stratonode1 ~]# strace -s 2000 -o ./docker.log /usr/bin/dockerd
INFO[0000] libcontainerd: new containerd process, pid: 27558 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0000] invalid character '\x00' looking for beginning of value 
INFO[0001] libcontainerd: new containerd process, pid: 27592 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0000] invalid character '\x00' looking for beginning of value 

Then using strace ( strace -s 2000 -o ./docker.log -f /usr/bin/dockerd
[events.log](https://github.com/moby/moby/files/1424931/events.log)
[docker.log](https://github.com/moby/moby/files/1424932/docker.log)

 ) I looked into what the daemon tries to do and from where he gets the '\x00' values.
Apparently, it happened to be 

28285 openat(AT_FDCWD, "/var/run/docker/libcontainerd/containerd/events.log", O_RDONLY|O_CLOEXEC) = 6

Looking into the file, I did see that it's corrupted (caused during node crash of course):
{"id":"34a5cfaa4c9578719e24f1cd24556608c415db7d4e68257971a61ab570a56663","type":"start-container","timestamp":"2017-10-29T08:22:28.459115157Z"}
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

After removing the file, docker spawned successfully.

I would expect that if the event log is corrupted, it would not affect docker ability to spawn.

Thanks,
Rom

Attached the events log file and strace output.

More info: 

[root@stratonode0 ~]# uname -a
Linux stratonode0.node.strato 3.10.0-514.10.2.el7.x86_64 #1 SMP Mon Jun 19 15:39:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@stratonode0 ~]# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

[root@stratonode0 ~]# docker info
Containers: 80
 Running: 79
 Paused: 0
 Stopped: 1
Images: 60
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: inaugurator-docker_thinpool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 21.61 GB
 Data Space Total: 26.84 GB
 Data Space Available: 5.235 GB
 Metadata Space Used: 77.82 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 995.9 MB
 Thin Pool Minimum Free Space: 2.684 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.strato0004.eac14abc4738.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.32 GiB
Name: stratonode0.node.strato
ID: 3YYK:M7S6:OPSU:2BOU:HDCE:TRMR:IZNW:634K:PXAY:DJRS:VDDL:LPEA
Docker Root Dir: /mnt/containers/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 maestro-proxy.service.strato:7656
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
Looks like this file is written and read by containerd; have you opened an issue in that repository as well? https://github.com/containerd/containerd/issues

**Comment by rom-stratoscale** [comment]
@thaJeztah  nope. Should I? Or there is an option for cross reference?

**Comment by thaJeztah** [comment]
Making sure that writes are atomic would have to be handled by containerd, so it's probably good to open an issue there

**Comment by rom-stratoscale** [comment]
@thaJeztah sure. np. So this one will be ignored?

**Comment by thaJeztah** [comment]
This would have to be fixed in the containerd repository, so it would have to be fixed there, before the version that's used in docker can be updated.

_However_ , docker 17.11 and up use the containerd 1.0 branch; following the discussion on https://github.com/containerd/containerd/issues/1699#issuecomment-340597663, this problem should no longer occur on that version/branch.

In addition, Docker 17.03-CE (community edition) has reached EOL, so won't be receiving updates (Docker 17.03-EE (enterprise edition) is still maintained though).

**Comment by stevvooe** [comment]
@thaJeztah This is presumably a problem in all pre-1.0 uses of containerd. Are we still backporting fixes to those versions? This would be like 17.06, 17.09, etc.

**Comment by thaJeztah** [comment]
@stevvooe 17.09-CE is still supported, but overall critical fixes (P0/P1) only afaik

**Comment by rom-stratoscale** [comment]
@thaJeztah sure, thanks.
Anyhow, I think it's worth documenting here a work around we applied in the systemd service file ( I guess it's relevant for those who dont rely on containerd events logs) :

ExecStartPre=-/usr/bin/bash -c '/bin/mv -v /var/run/docker/libcontainerd/containerd/events.log /var/run/docker/libcontainerd/containerd/events.log.$$(date +"%%Y%%m%%d-%%H%%M%%S")'
