### ISSUE TITLE
TestDaemonUserNamespaceRootSetting fails on RHEL 7.4

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#35336]
On RHEL 7.4 this usernamepsace test fails with an error from runc "exit status 40". It looks like the setns process just fails for some reason.

The CI machine does have user namespace enabled and /proc/sys/user/max_user_namespaces set to a high number.

Might be completely unrelated, but one thing I noticed is on RHEL if I `unshare -rm` I get EPERM... or `unshare -r && unshare -m` also EPERM. This seems to work just fine on other kernels.

<details>

```
21:07:06 ----------------------------------------------------------------------
21:07:06 FAIL: docker_cli_userns_test.go:24: DockerDaemonSuite.TestDaemonUserNamespaceRootSetting
21:07:06 
21:07:06 [d181ed338bc75] waiting for daemon to start
21:07:06 [d181ed338bc75] daemon started
21:07:06 
21:07:06 docker_cli_userns_test.go:50:
21:07:06     c.Assert(err, checker.IsNil, check.Commentf("Output: %s", out))
21:07:06 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc422049360), Stderr:[]uint8(nil)} ("exit status 125")
21:07:06 ... Output: 6601d2350aa7aecbcaa27a4cf2b47d76872c01bccd81aca2ce47370f021a43c0
21:07:06 /usr/local/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:295: starting container process caused "process_linux.go:302: running exec setns process for init caused \"exit status 40\"": unknown.
21:07:06 
21:07:06 
21:07:06 [d181ed338bc75] exiting daemon
21:07:08 
21:07:08 ----------------------------------------------------------------------
```

</details>

**Comment by cpuguy83** [comment]
Ping @rhatdan @runcom in case you have any insight here.

**Comment by rhatdan** [comment]
We don't intend on supporting User Namespace on RHEL7 until 7.5.  There are some problems that need to be back ported to the RHEL kernel for User Namespace support.

I think there was a second thing that needed to be set to get User Namespace to run on RHEL 7.4 besides the max_user_namespaces.  @rhvgoyal WDYT?

**Comment by rhvgoyal** [comment]
Right, docker still has issues with user namespaces in RHEL7.4. We don't allow unprivileged user namespace to own mount namespace yet and that fails simple things like clone(NEW_USERNS | NEW_NEWNS).

There is a unsupported way to test it though. One can pass kernel command line option `namespace.unpriv_enable=1`. But again, this is totally unsupported at this point of time and is there just to do some testing and debugging.

**Comment by cpuguy83** [comment]
Thanks! The CI has been updated to add the kernel option so at least the test passes.
