### ISSUE TITLE
unexpected behave with create partition of host disk

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#35340]
I want to create partition of host disk in docker to do test, but it fail to create two partitions.
I use -v to mount this disk as `-v /dev/vdb:/dev/vdb`.
I find use `lsblk` can find the partition but with `ls` can not which means the new partition can not reached by container.
Then i try to mount all `/dev` to `/dea` in container but still failed.
I do not find related docs so that i am not sure it is a bug or a not supported feather or my wrong action.

My env is as below:
```
[root@skydata_003 makeimage]# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 28
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-1009778822-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 53.69GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.042GB
 Data Space Total: 1.074TB
 Data Space Available: 475.8GB
 Metadata Space Used: 5.444MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.142GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.26GiB
Name: skydata_003
ID: 3FMA:CIIC:S4WS:UKGO:PVTU:FENF:2TWV:HQZS:VMFE:6HLT:ICDP:52TW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.20.38
 127.0.0.0/8
Live Restore Enabled: false
```
```
[root@003 makeimage]# uname -a
Linux skydata_003 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@003 makeimage]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

**Comment by thaJeztah** [comment]
If `/dev/vdb` is mounted on the host, you can use `-v /path-where-its-mounted:/container-path` to mount a host directory. There's also a `--device` option on `docker run` if you want to give a container access to a device.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by daixiang0** [comment]
Thanks, it helps.I also want to get some knowledge about difference between -v and --device.

**Comment by thaJeztah** [comment]
You can find more information on the `--device` feature in the pull-request that implemented it; https://github.com/moby/moby/pull/6134 and https://github.com/moby/moby/pull/6961 (and documentation PR's; https://github.com/moby/moby/pull/7931, https://github.com/moby/moby/pull/8465).

The `-v <hostpath>:<container-path>` flag (or `--mount type=bind,src=<hostpath>,target=<container-path>` simply bind-mounts a directory from the host into the container.

**Comment by thaJeztah** [comment]
Let me close this issue, because this isn't a bug, but fee free to comment after that
