### ISSUE TITLE
docker stats showing 0 for blkio values

### ISSUE THREAD

**Issue by bitprim-phabricator** [moby/moby#35352]
**docker stats reporting all values for blk_io as zero**

**Steps to reproduce the issue:**
1.Launch Container producing I/O to disk
2. run docker stats <container_id>

**Describe the results you received:**
Block IO values reported as 0

**Describe the results you expected:**
Block IO values should be correct

**Additional information you deem important (e.g. issue happens only occasionally):**
Checked values under /sys/fs/cgroup/blkio/docker/<container_id> they are 0 as well

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.3-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 125.9GiB
Name: ovh-libbitcoin-test
ID: S2R3:AGG5:CSVV:XNJJ:EJA5:BN2C:WMM3:KK7R:UL43:7AIX:HQYF:IX6F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Server 12 CPU 128 GB RAM

**Comment by thaJeztah** [comment]
> Checked values under `/sys/fs/cgroup/blkio/docker/<container_id>` they are 0 as well

So, wondering if this is a docker bug then; docker (through containerd / runc) reports the information it retrieves from the kernel; https://github.com/containerd/containerd/blob/17901fafa06cba7b68ccdaf4bba83bbcb20b0db9/metrics/cgroups/blkio.go#L13-L105 https://github.com/opencontainers/runc/blob/52454cf90807727923b375afd7d84ac8fd523959/libcontainer/cgroups/fs/blkio.go#L115-L237

Can you try running the check-config script as well, to see if anything stands out on your system? https://github.com/moby/moby/blob/master/contrib/check-config.sh

**Comment by bitprim-phabricator** [comment]
You were right, i had added the `cgroup_enable=memory swapaccount=1` options to `/etc/default/grub` file and updated grub, but when i upgraded the kernel these changes were apparently lost, `check__config.sh` pointed out the issue.
Now i got the stats to work, but i have a container that uses a vey large memory mapped file, is it normal for BLKIO stats to be 0 in that case ? If i run `iostat` on the host i see almost 50MB/s traffic on the disk.

**Comment by thaJeztah** [comment]
Hm, I don't know actually. If that's due to swapping, I can imagine it not being accounted for the container's BLKIO (because it's not the container's process itself doing the writing).


> when i upgraded the kernel these changes were apparently lost, check__config.sh pointed out the issue.

Curious; when using `docker info` were these warnings printed?

https://github.com/docker/cli/blob/c0d004f7cf11d7340b3b522380d9cdbf86437617/cli/command/system/info.go#L228-L233

**Comment by thaJeztah** [comment]
let me close this issue for housekeeping, but feel free to continue the conversation

**Comment by bitprim-phabricator** [comment]
@thaJeztah nope, no warnings after adding these parameters to the kernel boot command line, i don't think they were printed when i obtained the `docker info` report attached above.

**Comment by VinkDong** [comment]
I am confused at what BLOCK I/O means, in my opinion, if me down a 10M file in container it should increase 10M but it has no change

my docker info 

```bash
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 17.07.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6MiB
Name: vink
ID: MHFO:OLBC:VOAZ:6PR2:4L73:ZBHY:TER2:XZBK:FYZO:I56L:EBVY:WTIY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I test by the following command

```bash
# docker run -ti alpine sh 
# wget http://212.183.159.230/20MB.zip
```

then `NET I/O` value is
```
21.1MB / 119kB
```

but `BLOCK I/O` value is 

```
0B / 0B
```
