### ISSUE TITLE
can not create volume use glusterfs

### ISSUE THREAD

**Issue by zhengqisong** [moby/moby#35356]
[root@test80 gfsmnt2]# docker volume create --driver local --opt type=glusterfs --opt device=10.0.2.81:models --name foo5
foo5
[root@test80 gfsmnt2]# 
[root@test80 gfsmnt2]# docker run -it -v foo5:/world  --name gluster_test mongdb:3.4.1 bash
/usr/bin/docker-current: Error response from daemon: no such device.

-------------------
use mount can success in host test80 .
mount -t glusterfs 10.0.2.81:models /opt/gfsmnt2/

[root@test80 gfsmnt2]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

**Comment by zhengqisong** [comment]
[root@test80 gfsmnt2]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

**Comment by cpuguy83** [comment]
This is expected. GlusterFS is a user-space filesystem. This requires a running FUSE daemon and is not a simple `mount(2)` syscall. You won't be able to use the local volume driver to mount a FUSE fs.

Closing as this is working as expected, but feel free to comment. 🙇 👼
