### ISSUE TITLE
Docker cannot be run at all

### ISSUE THREAD

**Issue by cowlinator** [moby/moby#35372]
--------------
BUG REPORT 
--------------

**Description**

I cannot run docker at all.

**Steps to reproduce the issue:**

Upon installing docker, `docker info` stated that the daemon is not running.
`/etc/docker/daemon.json` does not exist.
Upon running `dockerd`, it states that a pid file is found.
`ps axf | grep docker | grep -v grep` did find results (dockerd and containerd), so I kill both processes, and verified that they were killed, and then delete the pid file.
Now running `dockerd` results in no errors.

So next I killed `dockerd`.
Next I tried starting the docker daemon with both `sudo service docker restart` and with `sudo systemctl restart docker`.
But after each of these `docker info` stated that the daemon is not running.
I verified that `docker.service` and `docker.socket` were enabled with `systemctl list-unit-files | grep docker`.
Then I restarted the machine, thinking that the services will auto-start.
Upon logging in, `ps axf | grep docker | grep -v grep` did find results (dockerd and containerd).
However, `docker info` still states that no daemon is running.

Next, I tried to start the daemon manually.
I disabled the services, stopped the services, ensured the processes were killed, and deleted the pid file.
Now keep in mind, that I'm using this machine via ssh, so I only have one terminal.
So first I try running `nohup dockerd &`. But `docker info` reports no daemon.
So I kill the process and try `nohup docker daemon -H tcp://localhost:2375 -H unix:///var/run/docker.sock &`. But `docker info` reports no daemon.

So I try reinstalling docker with `apt-get remove docker.io`, `apt-get purge --auto-remove docker.io` (which nukes `/var/lib/docker`), and then `apt-get install docker.io`.
And then I repeat all of the above steps with no improvement.

**Describe the results you received:**

I cannot run docker.

**Describe the results you expected:**

I expect to run docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens 100% of the time on one (VM) machine.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Additional environment details (AWS, VirtualBox, physical, etc.):**

`lsb_release -a` shows that I have Ubuntu 16.04.2.  This is a VM.

**Comment by fntlnz** [comment]
If everything is running and you get that error the only things that comes in mind is that you're using the client with a user that is not in the docker group. Try `sudo docker info`

**Comment by thaJeztah** [comment]
@cowlinator you may want to switch to the official Docker packages as well to get an up-to-date version of docker; the docker.io package is a package that's maintained by Ubuntu, and 1.12.6 is quite outdated. You can find installation instructions for ubuntu here; https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is a support question, not a bug-report, but feel free to continue the conversation (just closing for housekeeping :smile:)

**Comment by cowlinator** [comment]
@thaJeztah, Thank you for the info about docker.io being obsolete.  I will post this type of issue in the forums in the future.  

Is there any way to mark docker.io as obsolete?  It was not clear to me at all that it was.

**Comment by thaJeztah** [comment]
Well, it's a package that's maintained by the Ubuntu packagers. While it's possible that they backport changes, the upstream (official) version of docker 1.12.6 is no longer maintained.

If you want the packages maintained by docker, use those from download.docker.com
