### ISSUE TITLE
The service published ports are not published in my docker swarm.

### ISSUE THREAD

**Issue by yellowiscool** [moby/moby#35380]
**Description**

Hei, I just updated to docker swarm cluster to 17.10.0-ce and all my services ports are not published anymore. When creating a new service, it is not published as well.

**Steps to reproduce the issue:**
1. `docker service create -p 7777:80 --name nginx-test-service nginx`
2. `curl http://127.0.0.1:7777/`

**Describe the results you received:**

`Failed to connect to localhost port 7777: Connection refused`

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:03:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 60
 Running: 13
 Paused: 0
 Stopped: 47
Images: 733
Server Version: 17.10.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1586
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 0vyd402jbbodbke13os0it3v5
 Is Manager: true
 ClusterID: c9w8yeookbcev7wja70fufm4s
 Managers: 5
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.6
 Manager Addresses:
  192.168.1.21:2377
  192.168.1.23:2377
  192.168.1.41:2377
  192.168.1.43:2377
  192.168.1.6:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.64GiB
Name: swarm-master
ID: IOS2:WWFW:2WTT:VALW:HYDB:A4N4:FT7N:MHQB:B6XI:RCFA:A4ZK:W6IZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bmorin
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
 sin.region=no-oslo-1
 sin.color=black
 sin.storage=ssd
 sin.cpu=amd
 sin.performances=meh
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It's a small SWARM cluster of 7 physical nodes. I have the same results on all nodes. I tried to scale up and down, to run the actual container on different nodes… No difference.

**Comment by thaJeztah** [comment]
Anything in the logs that stands out? Perhaps you can also check if the iptables rules look ok (and if you see changes being made to iptables).

Does it make a difference if you try to connect using the external IP address of a node (instead of `localhost`)?

**Comment by yellowiscool** [comment]
Sorry I don't have time to play a lot with iptables right now so I went back to docker 17.09.0. Using the external IP didn't help.

If I'm alone having this issue, I will spend some time maybe next week.

**Comment by thaJeztah** [comment]
Let me close for now, but if you have more information available, feel free to comment

**Comment by sightseeker** [comment]
I also experienced the same problem after the upgrade from 17.03 to 17.10.
However, if that swarm init again I succeeded.

This is the command executed at that time.
* `docker swarm leave --force`
* `docker swarm init`
