### ISSUE TITLE
Expose SubSecondPrecision config option for fluentd logging driver

### ISSUE THREAD

**Issue by crazysaem** [moby/moby#35384]
fluentd v0.14.22 stable has been [released](https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released), which [supports sub second precision](https://docs.fluentd.org/v0.12/articles/faq#i-have-millisecond-timestamp-log-but-fluentd-drops-subsecond.-why?) for logs.

[fluent-logger-golang](https://github.com/fluent/fluent-logger-golang) already has an option to enable this called `defaultSubSecondPrecision`; created in May via this PR: https://github.com/fluent/fluent-logger-golang/pull/49

Since this package is used by the docker fluentd logger under the hood, it could be exposed here: https://github.com/moby/moby/blob/4bc5a5765288c797bb6989a9e08938b5327236dc/daemon/logger/fluentd/fluentd.go#L120

**Comment by ripcurld0** [comment]
@crazysaem would you like to work on that?

**Comment by crazysaem** [comment]
Sure! But I can only start working on it at the end of next week.
(If someone else already started working on it in the meantime, please let me know).

**Comment by dungeonmaster18** [comment]
Hi, I am new here. I would like to take this. Also if I can little guidance how can I start on this it will be great. Thanks

**Comment by ripcurld0** [comment]
Thank @dungeonmaster18 
Closing this.
