### ISSUE TITLE
/dev should be mounted as "noexec"

### ISSUE THREAD

**Issue by n4ss** [moby/moby#35397]
`/dev` doesn't have the `noexec` mount option: https://github.com/moby/moby/blob/2613c3d53cee46d8e0dc8e1aba83686f259985e4/oci/defaults.go#L81

Being a _system_ `tmpfs` with `RW` rights, it'd be better to have no execution rights there.

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/pull/29296


cc @justincormack

**Comment by AkihiroSuda** [comment]
@n4ss @justincormack What's current status?

**Comment by thaJeztah** [comment]
closing per https://github.com/moby/moby/pull/29296#comment-270090219, and discussion on Slack
