### ISSUE TITLE
Docker randomly takes several seconds to create container

### ISSUE THREAD

**Issue by etamponi** [moby/moby#35396]
**Description**

We run docker 1.12.2 on a few machines on AWS. Each machine runs around 50-80 containers at a time, and we cycle containers every few minutes (so in an interval of 1 minute, it might happen that around 30-50 containers are started and 30-50 containers are stopped).

Some times, in an apparently random way, `docker create` takes an incredible amount of time to start... it's typically below 500ms, but it happens to take 20 seconds, or even more than 200 seconds! Often, while this happens, Docker does not even respond to SIGUSR1 to get the stack dump. I've finally managed to get at least one of these dumps, so I can finally open this bug report.

An additional information that might be useful is that the docker image we are using is around 7GB.

**Steps to reproduce the issue:**
The issue does not show on staging, which has exactly the same configuration as production. The only difference is in the number of containers running and being started/stopped.

1. Have around 30-40 containers being started and stopped every minute, and around 50 containers running at any given time 
2. Wait for `docker create` to take more than 2 seconds

**Describe the results you received:**

Calls to /containers/create took way more than 1 second, peaking at 400 seconds.

**Describe the results you expected:**

/containers/create should always take less than 1 second.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue seems to be bound to a high number of containers running or being started/stopped.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 68
 Running: 42
 Paused: 0
 Stopped: 26
Images: 49
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/362144.362144/aufs
 Backing Filesystem: extfs
 Dirs: 201
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1035-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.94 GiB
Name: docker-worker-0A0AE4
ID: Y6F5:6TOM:GODA:KBVI:MERE:4KU3:FOQ2:JAEV:XUU5:UKTK:SNBM:PBTZ
Docker Root Dir: /var/lib/docker/362144.362144
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 185
 Goroutines: 279
 System Time: 2017-11-03T10:40:32.014475118Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We run on AWS, specifically r4.xlarge instances.

You can find a sample stack dump attached.
[stack.txt](https://github.com/moby/moby/files/1440758/stack.txt)

**Comment by etamponi** [comment]
Another stack trace, this time `/containers/create` took 56.94 seconds. The stack trace was taken after 2 seconds from the call to `/containers/create`.
[stack.txt](https://github.com/moby/moby/files/1440874/stack.txt)

**Comment by cpuguy83** [comment]
In both stack traces this appears to be stuck in a syscall to unmount an aufs mount from some other container.
Have you looked at other things on the system that could be slowing this down?

**Comment by thaJeztah** [comment]
Also be aware that docker 1.12 has reached end of life (if you cannot update to a newer release, I _do_ recommend updating to at least 1.12.6, because older versions have a critical vulnerability in RunC; docker 1.12.6 ships with an updated version of runc to address this https://github.com/moby/moby/releases/tag/v1.12.6)

**Comment by etamponi** [comment]
I am now updating docker on all instances to 17.09, and using the overlay2 driver instead of aufs. If I understood correctly, this is the suggested configuration/version so far.

**Comment by etamponi** [comment]
@cpuguy83 I looked at every possible thing: load averages, disk io, cpu usage, network usage... it's completely random. It makes much sense that it is connected with a problem with unmounting an aufs layer though, so I am hoping using overlay2 and an updated docker version will improve things.

**Comment by etamponi** [comment]
Just confirmed that upgrading Docker to 17.09 and replacing the storage with overlay2 didn't solve the issue.

I'm attaching a few stack traces taken while `/containers/create` was taking too long.

[goroutine-stacks-2017-11-04T144707Z.log](https://github.com/moby/moby/files/1443269/goroutine-stacks-2017-11-04T144707Z.log)
[goroutine-stacks-2017-11-04T144721Z.log](https://github.com/moby/moby/files/1443272/goroutine-stacks-2017-11-04T144721Z.log)
[goroutine-stacks-2017-11-04T144758Z.log](https://github.com/moby/moby/files/1443275/goroutine-stacks-2017-11-04T144758Z.log)

**Comment by etamponi** [comment]
It looks like the `postContainersCreate` route is stuck on a `Fsync` call in every stack trace I've collected so far. Is it possible to get the name of the file that docker is trying to sync from the information in the stack trace?

**Comment by cpuguy83** [comment]
You'd have to follow the stack trace into the code.
If fsync is taking a long time it sounds like either disk io or a failing disk.

**Comment by thaJeztah** [comment]
From one of the traces; 
```
goroutine 1828 [syscall]:
syscall.Syscall(0x4a, 0x35, 0x0, 0x0, 0x171a3e0, 0x6, 0xc42001d968)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fsync(0x35, 0x10, 0x970738)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:492 +0x4a
os.(*File).Sync(0xc42010c2c0, 0x1b4a0c0, 0xc4223d0ef8)
	/usr/local/go/src/os/file_posix.go:121 +0x5b
github.com/docker/docker/pkg/ioutils.(*atomicFileWriter).Close(0xc420931410, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/ioutils/fswriters.go:68 +0x81
github.com/docker/docker/container.(*Container).WriteHostConfig(0xc420d1e240, 0xc422139800, 0x0, 0x0)
	/go/src/github.com/docker/docker/container/container.go:259 +0x2f6
github.com/docker/docker/daemon.(*Daemon).registerLinks(0xc4203e2200, 0xc420d1e240, 0xc420f03000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:1199 +0x3d3
github.com/docker/docker/daemon.(*Daemon).setHostConfig(0xc4203e2200, 0xc420d1e240, 0xc420f03000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:221 +0xce
github.com/docker/docker/daemon.(*Daemon).create(0xc4203e2200, 0xc421423ab3, 0x24, 0xc42167be00, 0xc420f03000, 0x0, 0x0, 0x1abc009, 0x5, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/create.go:169 +0x544
github.com/docker/docker/daemon.(*Daemon).containerCreate(0xc4203e2200, 0xc421423ab3, 0x24, 0xc42167be00, 0xc420f03000, 0x0, 0x0, 0x1abc009, 0x5, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/create.go:70 +0x1fa
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc4203e2200, 0xc421423ab3, 0x24, 0xc42167be00, 0xc420f03000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/create.go:33 +0xa1
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc420208940, 0x7f032190a520, 0xc4208a2150, 0x2747180, 0xc421514c40, 0xc422452a00, 0xc420953ad0, 0x1abbd57, 0x5)
```

You'll see that the `Fsync` is from the part where the container's configuration is written to disk (in `WriteHostConfig()`https://github.com/moby/moby/blob/7848b8beb9d38a98a78b75f78e05f8d2255f9dfe/container/container.go#L241-L269)


But yes, this looks like a possible issue with the disk (being slow / busy)

**Comment by etamponi** [comment]
The disk is a 50GB gp2, I don't know if that matters. Nothing seems to
fail, because the host keeps working fine after the slowdown. Following the
stack trace, it looks like the HostConfig file (hostconfig.json) is what
gets blocked. So what I am trying to do now is mounting the ContainerRoot
(/var/lib/docker/containers) as a tmpfs volume. Let's see what happens when
the kernel tries to sync a file that's only in ram :P

Il 05 nov 2017 13:32, "Sebastiaan van Stijn" <notifications@github.com> ha
scritto:

**Comment by etamponi** [comment]
So, I confirm that mounting a tmpfs directory on /var/lib/docker/containers fixes this slowness issue.

Under heavy utilization, though, I still see `postContainersCreate` waiting too long on other things (specifically, I think, on getting a lock to add a write layer on top of the container image).

Is it really necessary to lock on adding layers? Isn't the kernel supposed to handle that for us correctly?

If it is necessary, would it be a solution if I generate slightly different images (which might differ only for the last layer) and use them cyclically to avoid or reduce the risk of a lock?

Thank you for all your help!!!

**Comment by cpuguy83** [comment]
@etamponi It's more about the internal state. But I'd bet the issue is that once again hitting issues with the filesystem causing other lock requests to block.

**Comment by etamponi** [comment]
Things seem to have improved after switching to EBS optimized instances, but we still see some random hiccup (way less frequent though).

I'd say we can consider this closed, but I have another question: is there any reference document that says what's the best way to deploy Docker on AWS? I mean, in particular:

- what are the best instance types?
- what's the best filesystem for the system drive?
- what's the best storage configuration: EBS optimized? Instance storage? Provisioned IOPS?

Thanks again to everyone!

**Comment by steaksauce-** [comment]
@etamponi 
I know it's been a while, but to answer your questions: it all depends on the type of work load.

You can probably do some testing on various instance types, file systems, and storage configs. I am totally open to hearing the findings in your scenario.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
