### ISSUE TITLE
Suggestions for issue to work on

### ISSUE THREAD

**Issue by summergirl21** [moby/moby#35409]
I’m talking a college class on Virtualization, as part of the class we need to contribute to an open source project. We have two people working on this and about a month to complete the project.

We’re looking for something that would take us about 20-40 hours to complete. We both have a good amount of systems programing experience but no experience with any Docker/moby code base.

We’ve looked through a bunch of issues on moby and Docker repos but are having a hard time figuring out what would be useful and a good scale project to complete. Any suggestions on a good project/issue to work on would be greatly appreciated!!

**Comment by sandersaares** [comment]
Just off the top of my head: cross-platform interoperability. It is a topic that could probably fill the time and is sufficiently basic enough to get done in that time.

For example, I mean things like being able to use both / and \ in paths given to the Docker. Right now there are plenty of places where it assumes either one or the other but not both. In a multiplatform world this is nonsense. You can find such instances in both the CLI client and the Dockerfile processing code for sure. I imagine multiplatform issues might also be good low-hanging fruit elsewhere in the pipeline.

**Comment by AkihiroSuda** [comment]
Just my personal thoughts:

- Although out of the scope of Moby, the 300ms+ spin lock delay in the network namespace in the Linux kernel looks like one of the most important issue in the Linux container ecosystem. https://www.slideshare.net/PhilEstes/bucketbench-benchmarking-container-runtime-performance/10 (needs feasibility investigation)
- I'm not sure there is a GitHub issue on Moby repo, but supporting rootless containers ( https://rootlesscontaine.rs ) seems very useful. This is already implemented on runc but not implemented on containerd side and on Moby side. The first step would be on containerd side, but the change won't be merged until containerd v1.0 GA

**Comment by AkihiroSuda** [comment]
@thaJeztah Any thoughts? :smile:

**Comment by AkihiroSuda** [comment]
I guess this is closable now, but feel free to ping me to reopen if needed
