### ISSUE TITLE
Docker swarm ip addr 0.0.0.0

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#35437]
Hello,

I have 3 managers with docker swarm : 
```
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

When i inspect each node i have : 

1. 
       "Status": {
            "State": "ready",
            "Addr": "10.99.9.10"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.99.9.10:2377"
        }

2.
        "Status": {
            "State": "ready",
            "Addr": "0.0.0.0"
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "Addr": "10.99.9.11:2377"
        }

3.
        "Status": {
            "State": "ready",
            "Addr": "10.99.9.12"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.99.9.12:2377"
        }

In another environnement with 3 managers i have 

```
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

1.
        "Status": {
            "State": "ready",
            "Addr": "10.99.8.10"
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "Addr": "10.99.8.10:2377"
        }

2.
        "Status": {
            "State": "ready",
            "Addr": "10.99.8.11"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.99.8.11:2377"
        }

3.
        "Status": {
            "State": "ready",
            "Addr": "10.99.8.12"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.99.8.12:2377"
        }

Why in the first environnement the ip addr of the second node is 0.0.0.0 ?

@fcrisciani

**Comment by sylvainmouquet** [comment]
Else i demote and promote the second node of the first env and now i have : 

```
$ docker node demote
        "Status": {
            "State": "ready",
            "Addr": "10.99.9.11"
        }
```

```
$ docker node promote
        "Status": {
            "State": "ready",
            "Addr": "10.99.9.11"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.99.9.11:2377"
        }
```

**Comment by thaJeztah** [comment]
Hm, not sure;

- was the first environment created with Docker 17.10 originally, or created with an older version of docker and later updated?
- was the swarm initialised with an `--advertise-addr` and/or `--listen-addr`?
- the node that showed `0.0.0.0` was that the node that the `docker node inspect` was run from (i.e. was it the "local" node that showed this information)?

**Comment by sylvainmouquet** [comment]
1) It's a new install with docker 17.10 installed from scratch
2) The docker swarm is initialized with : 
`$ docker swarm init`
and in others managers :
`$ docker swarm join-token manager`
3) from the node 1

**Comment by thaJeztah** [comment]
So, I think (will have to dig in SwarmKit to be 100% sure) for a local node, the node will look at the listen-address (which will me `0.0.0.0` by default); for other nodes, it'll show the _known_ address at which the node is reachable (the IP-address from which it joined).

Now, when demoting the node from another manager, and promoting it; it's now registered using the IP-address that was known in the other manager.

Do you see the same happening if you specify an `--advertise-addr`?

**Comment by sylvainmouquet** [comment]
Well i dont know why but the node2 is now with ip 0.0.0.0... I have not changed anything on the platform
I run docker node inspect in the 3 nodes and the result is the same for the second node  : 

```
        "Status": {
            "State": "ready",
            "Addr": "0.0.0.0"
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "Addr": "10.99.9.11:2377"
        }
```
The second node is the leader
```
$ docker node ls
ID                            HOSTNAME             STATUS              AVAILABILITY        MANAGER STATUS
w0zzhtoohyt14e8percyiqifx *   nod1   Ready               Active              Reachable
dkm3cidp3m8lxqb2pbf6kx36n nod2   Ready               Active              Leader
w94uypstm8tgp17ka2397afxn  nod3   Ready               Active              Reachable
```

**Comment by sylvainmouquet** [comment]
I have demote and promote the node2 to get the IP

The docker daemon returns lot of logs with node join event :
`$ journalctl -fu docker.service`

```
nov. 08 13:20:28 nod2 dockerd[9006]: time="2017-11-08T13:20:28.460441812+01:00" level=info msg="Node join event for 0584b24cc930/10.99.9.10"
nov. 08 13:20:28 nod2 dockerd[9006]: time="2017-11-08T13:20:28.460514447+01:00" level=info msg="Node join event for ba5f4f6015c7/10.99.9.11"
nov. 08 13:20:29 nod2 dockerd[9006]: time="2017-11-08T13:20:29.114346602+01:00" level=info msg="Node join event for 3f14d853979b/10.99.9.12"
```

**Comment by sylvainmouquet** [comment]
And now the node2 has been promoted to be the new leader with ip 0.0.0.0.

**Comment by sylvainmouquet** [comment]
I have reinstalled with : 
`$ docker swarm init --advertise-addr 10.99.9.10`

The installation is ok, the IP are correct for all nodes

Next i try to demote the node1.
now i have
```
$ docker node ls
ID                            HOSTNAME             STATUS              AVAILABILITY        MANAGER STATUS
knyjthtmbbfm072u0n05d3muy     nod1   Ready               Active
frt8otnp2b1tkgko3726n2b74     nod2   Ready               Active              Leader
zcy9b6g81ke9gb3ummlw1w2kx *   nod3   Ready               Active              Reachable
```

and node2 ip : 
```
        "Status": {
            "State": "ready",
            "Addr": "0.0.0.0"
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "Addr": "10.99.9.11:2377"
        }

```

**Comment by sabareeshkkanan** [comment]
I am experiencing same thing. I just added new node and getting ip address as 0.0.0.0

**Comment by dperetti** [comment]
Same here:
```bash
docker node inspect `docker node ls -q`
```
... and the leader is said to have `"Addr": "0.0.0.0"`  like  @sylvainmouquet .
This annoying for inspection scripts !

**Comment by ymatsiuk** [comment]
Reproducible on:
```
Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

with `docker node demote <current_leader>` and checking `docker node inspect <new_leader>` afterwards.

**Comment by clude** [comment]
meet the same issue

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

if the new_leader is not the original leader , the addr will shows 0.0.0.0. 
if the original master gets back as leader , the addr will shows right ip.

**Comment by cowai** [comment]
Is there a workaround for this?

**Comment by danielvrog** [comment]
```Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
Newly elected leader getting Addr 0.0.0.0

```
 "Status": {
            "State": "ready",
            "Addr": "0.0.0.0"
        },
        "ManagerStatus": {
            "Leader": true,
            "Reachability": "reachable",
            "Addr": "x.x.x.x:2377"
        }
```

**Comment by Wolfium** [comment]
I suffered same issue and only workaround was:

from any master:
  * drain that node
  * remove it from the swarm

from the node itself:
  * leave swarm
  * restart docker engine (just in case)

from any master:
  * get swarm token join

from the node:

  * rejoin the node

Intermittent http 504 issues from traefik proxy and internal services working again as expected
Hope that is helps

**Comment by penguinn** [comment]
why dont solve this bug? 
if the new_leader is not the original leader , the addr shows 0.0.0.0.

**Comment by SachinJanani** [comment]
We are also experiencing the same issue is there any workaround for this?

**Comment by agccie** [comment]
Was there a docker fix for this that i missed?  I only see ansible updates to use ManagerStatus[Addr] instead of Status[Addr]. 

Thanks,

**Comment by MrAlfabet** [comment]
I'm having the same issue. "EngineVersion": "18.09.0". Clean install.

**Comment by MrAlfabet** [comment]
I'm having the same issue. "EngineVersion": "18.09.0" on a raspberry pi cluster with 3 nodes.

**Comment by thaJeztah** [comment]
I don't think this was fixed yet.

@dperny I think I saw this come up in a discussion recently; do you know if there's any progress in root causing this?

(I'll reopen for now)

**Comment by jchorier** [comment]
same issue into docker 19.09.6. any workaround ?

**Comment by dperny** [comment]
So, here's the deal with `Status.Addr` vs `ManagerStatus.Addr`:

`Status.Addr` uses the gRPC library to determine the address of a given node as viewed by the manager. This means, for example, if a worker node was behind a proxy, it would give the proxy's address as `Status.Addr`, even if the worker itself didn't "know" it was behind a proxy. 

For `ManagerStatus.Addr`, the address given is the advertise address of the manager, as may have been set with `--advertise-addr` when doing `init` or `join`. The advertise address _must_ be correct, because that's the address that the other managers know to connect to this manager at.

I suspect that `Status.Addr` is `0.0.0.0` because the worker node parts of a node acting as a manager connect to the manager not over TCP, but over a Unix socket, and this probably doesn't work with address detection. I'd have to go dig in the code to figure out why, but I suspect it's primarily a problem on the leader, and should probably stop being a problem on leadership change...

**Comment by dperny** [comment]
If you need to affirmatively know the canonical address at which to connect to a given node, I recommend not using `Status.Addr` _or_ `ManagerStatus.Addr`, actually. I would instead recommend setting a label on the node or engine with the node's address. This way, you even allow, for example, configurations where you connect to the node through a different interface than what the cluster uses for control traffic.

**Comment by dimandzhi** [comment]
@jchorier, if by workaround you mean a method to get a valid IP of each node , then I can suggest this snippet:
```go
var node swarm.Node = ... // retrive info
var nodeIP string
if node.ManagerStatus != nil {
	nodeIP = strings.SplitN(node.ManagerStatus.Addr, ":", 2)[0]
} else {
	nodeIP = node.Status.Addr
}
```
@dperny did explain why this works, but putting it in other words gives this logic: `ManagerStatus.Addr` is always correct (but available for managers), `Status.Addr` (always available) is always correct for worker nodes (correct me on this) and `Status.Addr` not always correct for manager nodes. So basically you should try to get `Addr` from `ManagerStatus` and fallback to `Status`.
**Notice**: I been using this for almost a year, but only from manager nodes. So correct me on "*`Status.Addr` being correct for workers*".

**Comment by dperny** [comment]
`Status.Addr` is _correct for worker nodes if the worker node connects directly to the manager_.

It's a known deficiency which I have seen people encounter where the workers's connection to the manager passes through some kind of proxy or NAT, and this causes `Status.Addr` to appear to be incorrect.

This is a limitation of the address detection, which uses the source IP address of the connection.

**Comment by xinfengliu** [comment]
If there's no proxy or NAT between the nodes, here's a **workaround**:
- Stop the docker daemon on the leader node with `.Status.Addr 0.0.0.0`. 
- Fill in `AdvertiseAddr` with correct node IP in `/var/lib/docker/swarm/docker-state.json`
- Start the docker daemon
- Do above for other manager nodes.

**Observations**:
Normally for the first node (i.e. the original leader) in swarmkit cluster, `LocalAddr` and `AdvertiseAddr` in `/var/lib/docker/swarm/docker-state.json` are not empty. After a new node joins the swarm cluster, `LocalAddr` and `AdvertiseAddr` are empty for the new node, that's fine. But when the original leader node loses its leadership, `docker node inspect` will show `.Status.Addr 0.0.0.0` for the new leader.  

**Speculations**
`.Status.Addr` comes from `RemoteAddr` in`ca.RemoteNodeInfo` object which is associated with swarmkit `Session()` gRPC stream context (see `nodeIPFromContext()` in swarmkit `manager/dispatcher/dispatcher.go`). For leader node itself, `handleRequestLocally` (see swarmkit `manager/manager.go`) will be called and the `RemoteAddr` is actually from `AdvertiseAddr` or `ListenAddr` in `/var/lib/docker/swarm/docker-state.json`. For later joined node, by default `AdvertiseAddr` is empty, `ListenAddr` is `0.0.0.0:2377`, so `.Status.Addr 0.0.0.0` is seen.

**Comment by cpoetter** [comment]
I still have the same problem with **Ubuntu 18.04.4 LTS** and **Docker 19.03.6**. 

However, if I add _all_ nodes, even worker nodes, with `docker swarm join --advertise-addr ...` before I promote a worker to be a manager, `Status.Addr` is correct for me even after the leader changes.

**Comment by rafaelreis-r** [comment]
I'm having that with latest docker and Ubuntu Server 20.04.

**Comment by webchi** [comment]
> I'm having that with latest docker and Ubuntu Server 20.04.

I know that feel bro. Same with 20.10

**Comment by fightforlife** [comment]
Just happend to me. Also newest docker ce on ubuntu 20.10

**Comment by a-nych** [comment]
Having the same issue on Docker 20.10.7

**Comment by kolonuk** [comment]
What is wrong with having another ip address that lists either the ManagerStatus.Addr or Status.Addr, which ever is not 0.0.0.0.

Something like Status.HostAddr?

**Comment by seqwait** [comment]
why dont solve this bug?

**Comment by liuxuc63** [comment]
I meet the bug too. 
I hope the great docker team can resolve it!
Thanks.

**Comment by diabelb** [comment]
I can confirm the same bug on docker 20.10.20. It's still not fixed.

**Comment by dimandzhi** [comment]
As @cpoetter and @dperny noted, I've also noticed that using `--advertise-addr` flag in both `docker swarm init` and `docker swarm join` commands is preventing this issue. It is as if this flag must be mandatory. But I suspect that's not the solution since there is an option to change the network interface on the host. I don't think there is a safe way to determine correct address from code. Maybe this flag should at least be available for an update through `docker node update` or something?

**Comment by dperny** [comment]
So, basically, [digging into the history,](https://github.com/moby/moby/issues/24017) when we first added this issue, we knew it would be error prone and have unexpected behaviors. It's provided as a convenience, but the limitations (mostly, not working well on managers) are well-known from this thread. I'm suggesting we close this issue as a wont-fix, so that people finding this understand it's a limitation of the implementation, and not a bug.

**Comment by RensTillmann** [comment]
@dperny just to confirm, do you mean that as long as `ManagerStatus.Addr` has correct private IP but `Status.Addr` equals 0.0.0.0 it's okay and you don't have to worry? Or should I rejoin it with the flag `--advertise-addr` to solve this?

**Comment by platinumnh** [comment]
same issue, dont have a real resolution yet
