### ISSUE TITLE
can not access new partition in container

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#35444]
**Description**

I want to create new partition in container and use them.

**Steps to reproduce the issue:**
1. use `--device=` to mount a disk
```
docker run --privileged -d --device=/dev/vde:/dev/vde centos
```
2. use `parted` to create a new data partition
```
[root@cdba144bc679 ~]# lsblk                                              
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-2: failed to get device path
lsblk: dm-3: failed to get device path
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0  116G  0 disk 
├─vda1 253:1    0   52G  0 part /etc/hosts
└─vda2 253:2    0   64G  0 part 
vdb    253:16   0  400G  0 disk 
vdc    253:32   0  100G  0 disk 
vdd    253:48   0   10G  0 disk 
vde    253:64   0   10G  0 disk 
vdf    253:80   0   10G  0 disk 
vdg    253:96   0   10G  0 disk 
[root@cdba144bc679 ~]# parted -s /dev/vdg  mklabel gpt mkpart 1 ext4 1 2M
```

**Describe the results you received:**
With `lsblk`, i can view this new partition, but with `ls` i can not access
```
[root@cdba144bc679 ~]# lsblk 
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-0: failed to get device path
lsblk: dm-1: failed to get device path
lsblk: dm-2: failed to get device path
lsblk: dm-3: failed to get device path
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    253:0    0  116G  0 disk 
├─vda1 253:1    0   52G  0 part /etc/hosts
└─vda2 253:2    0   64G  0 part 
vdb    253:16   0  400G  0 disk 
vdc    253:32   0  100G  0 disk 
vdd    253:48   0   10G  0 disk 
vde    253:64   0   10G  0 disk 
vdf    253:80   0   10G  0 disk 
vdg    253:96   0   10G  0 disk 
└─vdg1 253:97   0    1M  0 part 
[root@cdba144bc679 ~]# ll /dev/vdg*
brw-rw---- 1 root disk 253, 96 Nov  9 02:31 /dev/vdg
```

**Describe the results you expected:**

I want to access the new partition like the host:
```
[root@test ~]# ll /dev/vdg*
brw-rw---- 1 root disk 253, 96 11月  9 10:19 /dev/vdg
brw-rw---- 1 root disk 253, 97 11月  9 10:31 /dev/vdg1
````

**Additional information you deem important (e.g. issue happens only occasionally):**
Also  about  `dm-0 failed to get`, is it normal?

**Output of `docker version`:**
```
17.09.0-ce
```

**Output of `docker info`:**

```
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 64.42GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 10.55GB
 Data Space Total: 408GB
 Data Space Available: 397.5GB
 Metadata Space Used: 2.372MB
 Metadata Space Total: 4.291GB
 Metadata Space Available: 4.288GB
 Thin Pool Minimum Free Space: 4.08GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.26GiB
Name: skydata_003
ID: YBGB:T3ON:6WC3:JKSL:VEZG:6SDY:H2L6:H2QH:HWAI:5VHT:6WUK:JP54
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
> I want to access the new partition like the host:

Likely due to mount propagation; see https://github.com/moby/moby/issues/13700, https://github.com/moby/moby/issues/13376#issuecomment-119200971, but perhaps @cpuguy83 can give a quick answer

> Also about `dm-0` failed to get, is it normal?

I guess those are filesystems of other containers, so in a different namespace (thus not accessible)


This is not really a standard use-case for containers, as they are designed to provide _isolation_, attempting to have the containers break that isolation can likely give unpredictable results.

**Comment by daixiang0** [comment]
Thanks, i find `–device-cgroup-rule` option. But i have some question about it(refer the [doc](https://docs.docker.com/edge/engine/reference/commandline/create/#initialize-volumes)):
- the example is character device, does it support block device like a disk in my case?
- what does the `rmw` mean, is it default or need to change?

Maybe the doc need to add some detail usage.

Also, i has tested with `docker run --privileged --device-cgroup-rule='b 253:* rmw' centos`, but after `parted`, the new partition still can not access. If anything wrong, please tell me, thanks again for your help!

**Comment by daixiang0** [comment]
ping @cpuguy83, could you teach me more detail about it?

**Comment by cpuguy83** [comment]
@daixiang0 I believe you'll have to run mknod in the container.

**Comment by daixiang0** [comment]
Do you mean this option is only useful to `mknod` ? 
All i want is to create and access new partition in the container.

**Comment by daixiang0** [comment]
ping @cpuguy83  could help me?
