### ISSUE TITLE
ENV in multi-stage builds are not isolated as expected

### ISSUE THREAD

**Issue by arel** [moby/moby#35443]
**Description**

I notice that`ENV` variables set in build-stages _not involved_ in building a particular build target still affect the unrelated target.

**Steps to reproduce the issue:**
1. Consider the following Dockerfile:

```Dockerfile
FROM alpine as mother

ENV WHO_AM_I="I'm the Mother, of course"
CMD echo "\"${WHO_AM_I},\" said the Mother."

FROM mother as son

ENV WHO_AM_I="I'm the Son, of course"
CMD echo "\"${WHO_AM_I},\" said the Son."

FROM mother as daughter

# ENV WHO_AM_I="I'm the Daughter, of course"
CMD echo "\"${WHO_AM_I},\" said the Daughter."
```

What should the environment variable `WHO_AM_I` be for the _Daughter?_

2. Build each of the build targets

```bash
docker build -t mother --target mother .
docker build -t son --target son .
docker build -t daughter --target daughter .
```
3. Run each of the build targets

```bash
docker run --rm -it mother
docker run --rm -it son
docker run --rm -it daughter
```

**Describe the results you received:**

```bash
$ docker run --rm -it mother
"I'm the Mother, of course," said the Mother.

$ docker run --rm -it son
"I'm the Son, of course," said the Son.

$ docker run --rm -it daughter
"I'm the Son, of course," said the Daughter.
```

In addition, whether or not _Mother_ sets `WHO_AM_I` the _Daughter_ always says she's the _Son_, even though the _Daughter_ inherits only from the _Mother_ and not the _Son_. 

**Describe the results you expected:**

I would expect that either the _Daughter_ would say _"Mother"_, because that's what was defined in her parent, or that `WHO_AM_I` would be unset.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 423
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.71GiB
Name: moby
ID: I2EJ:XLLN:7B3Y:P5SW:BTSE:WURC:BYDL:PVGL:KACC:XJH4:PZCD:25NX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 31
 System Time: 2017-11-09T01:34:38.467558326Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Docker for Mac.

**Comment by thaJeztah** [comment]
ping @tonistiigi PTAL

**Comment by dnephin** [comment]
I was able to reproduce this issue with all versions of Docker that support multi-stage builds (17.05, 06, 07, 09, 10)

**Comment by tonistiigi** [comment]
The issue is that `copyRunConfig()` https://github.com/moby/moby/blob/a4bdb304e29f21661e8ef398dbaeb8188aa0f46a/builder/dockerfile/internals.go#L388 is misleading as it is actually only creating a shallow copy and env dispatcher would replace the value in place if previous value was already set https://github.com/moby/moby/blob/a4bdb304e29f21661e8ef398dbaeb8188aa0f46a/builder/dockerfile/dispatchers.go#L50 . 

For example even modification like this would cause it to not appear:

```
FROM alpine as mother

ENV WHO_AM_I="I'm the Mother, of course"
CMD echo "\"${WHO_AM_I},\" said the Mother."

FROM mother as son
ENV foo=bar foo2=bar foo3=bar
ENV WHO_AM_I="I'm the Son, of course"
CMD echo "\"${WHO_AM_I},\" said the Son."

FROM mother as daughter
# ENV WHO_AM_I="I'm the Daughter, of course"
CMD echo "\"${WHO_AM_I},\" said the Daughter."
```

I guess making `copyRunConfig()` make a deep clone is safer fix in here that changing the dispatchers to not modify values in place. wdyt @dnephin 

> I was able to reproduce this issue with all versions of Docker that support multi-stage builds (17.05, 06, 07, 09, 10)

At least buildkit seems to work fine.

**Comment by dnephin** [comment]
Deep copy sounds appropriate to me
