### ISSUE TITLE
"docker run --tmpfs /dev/shm" fails with "Duplicate mount point"

### ISSUE THREAD

**Issue by kolyshkin** [moby/moby#35455]
(Originally reported here: https://github.com/moby/moby/issues/6758#issuecomment-342939512)

It is not possible to add a /dev/shm mount using `--tmpfs` flag: 
> $ docker run --tmpfs /dev/shm busybox sh
> docker: Error response from daemon: linux mounts: Duplicate mount point '/dev/shm'.

The reason is, /dev/shm mount is added to the list of mounts twice, by `TmpfsMounts()` and by `IpcMounts()`.

## Known workarounds

1. Use `--ipc none` together with `--tmpfs` (if supported).
2. Use `--mount` instead of `--tmpfs`

## Versions

This is reproducible on docker-ce-17.03 as well as docker-ce-17.11. Judging by the comments in https://github.com/moby/moby/issues/6758 is was working in some version, but following the commits I can't see it was working.

**Comment by thaJeztah** [comment]
Fixed by https://github.com/moby/moby/pull/35467
