### ISSUE TITLE
Docker update notification does not use correct browser for showing more info

### ISSUE THREAD

**Issue by jtnord** [moby/moby#35461]
**Description**

When docker notifies you there is an update you have links to web pages shown in the dialog.

However clicking on any link does not honour the default browser configured for the system but launches IE.

**Steps to reproduce the issue:**

1. Install Chrome
2. Set Chrome as your default browser
3. Install docker (`17.11.0-ce-rc2-win37 (13978)`)
4. wait until you are prompted that there are updates avaialble
5. in the release notes follow one of the links (e.g. one of the bug fixes)

**Describe the results you received:**

* IE is opened at the URL of the link (e.g https://github.com/docker/for-win/issues/953)

**Describe the results you expected:**

* The default browser (chrome) should be opened at the given URL.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce-rc2
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:08:18 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce-rc2
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   d7062e5
 Built:        Wed Nov  1 22:18:42 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
not needed
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Can you open this issue in the Docker for Windows issue tracker (https://github.com/docker/for-win/issues) ? This looks like an issue with Docker's products,  not the Moby project in this repository. Thanks!
