### ISSUE TITLE
FEATURE REQUEST: Support progress report when no TTY is available.

### ISSUE THREAD

**Issue by erikhakansson** [moby/moby#35460]
Currently, Docker build suppresses progress output when running in a script, e.g. when triggered from Maven.
This is sane since otherwise the output would be garbled and weird.

However, it would be nice to have at least SOME output.

For example, I several times per day build a docker image with a build context of about 2 gigabytes. When building manually, I get a progress report for the "Sending build context..." part, but when running through Maven (which will automatically supply relevant --build-args) I get no output at all until the context is sent.

It would be nice to have at least something, like an output every 5% or so. 
The same goes for docker pull and any other progress report.

Thanks!

**Comment by AkihiroSuda** [comment]
This request should be discussed in github.com/docker/cli

**Comment by erikhakansson** [comment]
ah, sorry. thanks for pointing me in the right direction!

Should I close this issue?

**Comment by thaJeztah** [comment]
Yes, that's probably best; let me close.

If you can post a link to the new issue here, that'd be helpful for people following the discussion

**Comment by erikhakansson** [comment]
I've opened up an issue on docker/cli:

https://github.com/docker/cli/issues/688
