### ISSUE TITLE
docker: Error response from daemon: error creating overlay mount to /devops02/DockerRoot/vm-docker-01/overlay2/62b057ffa638ddf9395aa75fbb7ba3c2d9c8d3c244e0f04e3d71db263c55824a-init/merged: invalid argument.

### ISSUE THREAD

**Issue by kazh000** [moby/moby#35476]
**Description**
I use last version of docker package for debian 9 with default settings. When docker's root directory is on local filesystem then docker works fine. When I use remote directory mounted by NFS I get error message "docker: Error response from daemon: error creating overlay mount to /devops03/vm-docker-01/overlay2/df6119fcb1d199baf968c2f703acd74bcb6700c97ed455e345e4bc820f1d7799-init/merged: invalid argument."
I tested ext4 and xfs as backing nfs filesystems. xfs is formated with d_type option. The error message is the same for both filesystems. I use nfs version 3 because nfs4 don't understand d_type.

**Steps to reproduce the issue:**
1. Install debian 9
2. Install last docker from package
3. mount remote filesystem by nfs version 3
4. Start docker with root directory pointed to sub-directory of remote filesystem
5. docker -v run hello-world

**Describe the results you received:**
# docker -v run hello-world
docker: Error response from daemon: error creating overlay mount to /devops03/vm-docker-01/overlay2/df6119fcb1d199baf968c2f703acd74bcb6700c97ed455e345e4bc820f1d7799-init/merged: invalid argument.
See 'docker run --help'.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: nfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8GiB
Name: vm-docker-01
ID: YEXG:TRQ5:36WS:WPFU:IR2E:YI7V:MU7N:52JT:6752:N4M3:TP2Y:5EP4
Docker Root Dir: /devops03/vm-docker-01
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 28
 System Time: 2017-11-13T14:17:57.583993493+03:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

# cat /etc/docker/daemon.json
{
  "debug": true,
  "data-root": "/devops03/vm-docker-01"
}

mount output:
systemd-1 on /devops03 type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10297)
salomer2:/devops03 on /devops03 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.73.1.42,mountvers=3,mountport=58101,mountproto=udp,local_lock=none,addr=10.73.1.42)
salomer2:/devops03/vm-docker-01/plugins on /devops03/vm-docker-01/plugins type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.73.1.42,mountvers=3,mountport=58101,mountproto=udp,local_lock=none,addr=10.73.1.42)
salomer2:/devops03/vm-docker-01/overlay2 on /devops03/vm-docker-01/overlay2 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.73.1.42,mountvers=3,mountport=58101,mountproto=udp,local_lock=none,addr=10.73.1.42)

**Comment by kazh000** [comment]
daemon.log:
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.949847051+03:00" level=debug msg="Calling GET /_ping"
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.953235391+03:00" level=debug msg="Calling POST /v1.32/containers/create"
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.953851531+03:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"hello-world\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.966280555+03:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: error creating overlay mount to /devops03/vm-docker-01/overlay2/b493788d38ca842f43978bc8fde8d5942cbd0cfceb36637846db5c825f11446c-init/merged: invalid argument" error_type="*errors.errorString" module=api
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.966549163+03:00" level=error msg="Handler for POST /v1.32/containers/create returned error: error creating overlay mount to /devops03/vm-docker-01/overlay2/b493788d38ca842f43978bc8fde8d5942cbd0cfceb36637846db5c825f11446c-init/merged: invalid argument"
Nov 13 14:33:10 vm-docker-01 dockerd[2848]: time="2017-11-13T14:33:10.966784350+03:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: error creating overlay mount to /devops03/vm-docker-01/overlay2/b493788d38ca842f43978bc8fde8d5942cbd0cfceb36637846db5c825f11446c-init/merged: invalid argument" error_type="*errors.errorString" module=api

**Comment by thaJeztah** [comment]
AFAIK, nfs is not supported for this (only local xfs and ext4 is supported), so this may be expected

/cc @cpuguy83 who may be able to give some more factual information around this.

**Comment by cpuguy83** [comment]
From https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt:

> The lower filesystem can be any filesystem supported by Linux and does
> not need to be writable.  The lower filesystem can even be another
> overlayfs.  The upper filesystem will normally be writable and if it
> is it must support the creation of trusted.* extended attributes, and
> must provide valid d_type in readdir responses, so NFS is not suitable.

Closing since this is working as expected.

**Comment by cpuguy83** [comment]
Maybe we can detect nfs and error out early, though?

**Comment by thaJeztah** [comment]
Yes, should definitely do that if the kernel won't support it

**Comment by thaJeztah** [comment]
Working on a PR

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/35483

**Comment by kazh000** [comment]
As far as I understand recently NFS become suitable for overlayfs https://lwn.net/Articles/736677/ but it requires very fresh kernel.
