### ISSUE TITLE
Response MIME type for streaming endpoints in API spec is incorrect

### ISSUE THREAD

**Issue by masaeedu** [moby/moby#35471]
The [Swagger spec](https://github.com/moby/moby/blob/a21654c/api/swagger.yaml) for endpoints like [`/images/create`](https://github.com/moby/moby/blob/a21654c/api/swagger.yaml#L6246) advertise a `produces` MIME type of `"application/json"`. In reality, the endpoint produces line delimited JSON, which is not valid JSON per se, and for which an appropriate MIME type might be [`"application/x-ndjson"`](http://ndjson.org/).

Differentiating such endpoints from regular `application/json` endpoints will allow consumers such as codegenerators to generate suitable client implementations for handling the streaming output, instead of just trying to parse the response as JSON and exploding.

**Comment by ibnesayeed** [comment]
Related #16230.
