### ISSUE TITLE
Named volume. Docker copy permissions from container to host on mounting.

### ISSUE THREAD

**Issue by igorbarkowsky** [moby/moby#35486]
**Description**

When creating container with bind of named volumes, docker copy permissions (mode, owner, group) from container's destination point to volume's source directory.

**Steps to reproduce the issue:**
```
$ cd ~ && mkdir test1 && chmod 775 test1
$ docker volume create --name myvol1 --opt type=none --opt device=/home/user/test1 --opt o=bind
myvol1
$ stat -c "%a %u:%g" test1
775 1000:1000
$ docker run -it --name testphp1 --user 1000:1000 -v myvol1:/var/www/html php:fpm stat -c "%a %u:%g" /var/www/html
755 0:0
```

**Describe the results you received:**
```
stat -c "%a %u:%g" test1
755 0:0
```

**Describe the results you expected:**
```
stat -c "%a %u:%g" test1
775 1000:1000
```

I expect that docker have been respects permissions of src dir.

**Additional information you deem important (e.g. issue happens only occasionally):**

Compare with mapping host directory (correct works with perissions, copy from src to dst):
```
$ cd ~ && mkdir test2 && chmod 775 test2
$ docker run -it --name testphp2 --user 1000:1000 -v /home/user/test2:/var/www/html php:fpm stat -c "%a %u:%g" /var/www/html
775 1000:1000
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 105
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-deepin13-amd64
Operating System: Deepin 15
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.62GiB
Name: power
ID: 4LFN:AD6J:WUSN:QIBE:SHIT:WA6U:T5IE:Q3RP:LS5A:BC7I:2X56:SJA4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This buggy behavior i've got on different linux environments.

**Comment by cpuguy83** [comment]
@igorbarkowsky This is expected behavior of volumes. If you want to use a bind why not just bind normally? `-v /foo:/bar`.

You can also disable this copying with `-v foo:/bar:nocopy`

**Comment by igorbarkowsky** [comment]
@cpuguy83 thank you for advicing "nocopy" option. With nocopy - works fine, top directory of volume not changing permissions now, neither after create nor after re-create:)

I dont want use host-dir mounting, its only for local development.
Named volumes more flexible. I can store my sources whenever i want. Volumes has names. Volume with name AwsSiteStorage more descriptional than /home/user/mounts/aws/balblabla/u17463/public_hml, for example.

**Comment by thaJeztah** [comment]
Looks like this question was answered, so I go ahead and close, but feel free to continue the conversation
