### ISSUE TITLE
How to set cpus or cgroup to its default status ? 

### ISSUE THREAD

**Issue by bjwswang** [moby/moby#35487]
**Description**

I was trying to adjust cgroup for our docker containers . By using "docker update --cpus=0.5 ${container_id}" , I changed the cpu limitation successfully . Then I wanted to set cpus to the default configurations.. Anyone knows how to do this ? 
**Steps to reproduce the issue:**
Suppose this is not a issue  , just need help on how to set it back .. 

1 ) update cpus : 
         docker update --cpus=0.5 ${container_id}
2) set it back to default (don't know if it is effective, pls tell me ...): 
    I tried : 
          docker update --cpu-quota=-1 ${container_id}
   Because I was doing some stress tests on containers , I was hoping that by setting cpus back to default    I can reduce our steal time of this container ... but failed  . So I was wondering maybe I failed at setting cpus  back to default. 
          

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker + qemu+ kvm

**Comment by HatakeSR** [comment]
@yongtang  Could you help me ? Thanks !

**Comment by yongtang** [comment]
@HatakeSR nanocpus is not a linux native concept so it is really translated to cpu-quota + cpu-period. 
You may need to reset both cpu-quota and cpu-period. It is not possible to `reset` nanocpus at the moment (I am thinking it might be possible to add this feature).

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
