### ISSUE TITLE
-p or --publish flags are silently ignored on containers with --net host

### ISSUE THREAD

**Issue by mistyhacks** [moby/moby#35500]
If you try to create a service with `--net host` and `-p ...`, you get an error. However, if you do the same with a standalone container, the `-p` is silently ignored. This is confusing and probably a bug.

cc/ @thaJeztah

**Comment by thaJeztah** [comment]
Thanks!

ping @mavenugo wdyt? I was thinking of this recently, and silently ignoring the `-p` option may lead to the conclusion that the flag actually does something, whereas it does not actually do anything with `--network=host`.

Printing a warning (not an error) would probably be a good thing for that
