### ISSUE TITLE
Docker Swarm Breaks Private Interface

### ISSUE THREAD

**Issue by geigev** [moby/moby#35515]
**Description**
Swarm  seems to cause the private networking interface to fail for manager nodes when docker is restarted.

**Steps to reproduce the issue:**
1. Initalize a swarm across multiple vps's on their **private interface** (eth1). I used digitalocean.
2. Deploy a few random services using `docker stack deploy --with-registry-auth --compose-file docker-compose.yml app`
~~3. Wait an unknown period of time (Not sure what exactly causes the issue. Might be related to joining new nodes to the swarm, or updating the stack)~~
3. Restart docker several times until you encounter what is described below

**Describe the results you received:**
Nodes already in the swarm can continue to communicate, but new nodes cannot join the swarm, or even ping the manager node on private interface (can still ping public interface). Worker nodes seem like they can still ping nodes outside the swarm on the same network.

**Describe the results you expected:**
The private vps network to continue functioning normally -- new nodes can join the swarm and vps on the same network can ping the manager node

**Additional information you deem important (e.g. issue happens only occasionally):**
The eth1 interface seems to "disappear", or rather "turn into" a virtual interface. When things are working properly `ifconfig -a` on the manager node returns
```
eth1      Link encap:Ethernet  HWaddr a2:d7:ca:06:c4:ef  
          inet addr:10.137.16.80  Bcast:10.137.255.255  Mask:255.255.0.0
          inet6 addr: fe80::a0d7:caff:fe06:c4ef/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1093 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1059 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:329085 (329.0 KB)  TX bytes:290315 (290.3 KB)
```

When the network stops working properly, `ifconfig -a` no longer displays the eth1 interface and instead  displays a new interface that looks like this
```
veth8615ca5 Link encap:Ethernet  HWaddr a2:d7:ca:06:c4:ef  
          inet addr:10.137.16.80  Bcast:10.137.255.255  Mask:255.255.0.0
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:499 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:27944 (27.9 KB)  TX bytes:2314 (2.3 KB)
```

The only way I can get the private network working again on the manager (in general not just for swarm) is to completely remove the stack and reboot the server. Once both of these steps are completed, I again see the eth1 interface displayed normally and the manager node can communicate properly on its private interfaces

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce-rc3
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   5b4af4f
 Built:        Wed Nov  8 03:09:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce-rc3
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   5b4af4f
 Built:        Wed Nov  8 03:08:21 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 29
 Running: 9
 Paused: 0
 Stopped: 20
Images: 6
Server Version: 17.11.0-ce-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: j2n5bljbla1ai8og1c6ixv6v0
 Is Manager: true
 ClusterID: lwl5qrvlzrbrw7e494niesf77
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.137.16.80
 Manager Addresses:
  10.137.16.80:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: staging
ID: VPYU:DVYP:RG37:26WC:QL3Z:WMNO:KLZB:4IO7:CJ3W:SXT6:PSAT:T5VY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on DigitalOcean using their private network and cloud firewalls

**Comment by geigev** [comment]
This issue also happens on previous versions of docker (17.09 and 17.10). I think it might be related to https://github.com/moby/moby/issues/16572. It seems like when docker restart brings down the networks it renames the digitalocean eth1 interface to vethxxx breaking the private network on the server.

**Comment by cpuguy83** [comment]
Are you using NetworkManager by chance?

**Comment by geigev** [comment]
@cpuguy83 
Ty for response; I am **not** using NetworkManager

**Comment by geigev** [comment]
I spent some time looking at the syslog and I think I found where it happens. Here is the section where I believe the name change occurs.
```
Nov 17 23:40:10 staging systemd[1]: sys-subsystem-net-devices-eth1.device: Dev sys-subsystem-net-devices-eth1.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:04.0/virtio1/net/eth1 and /sys/devices/pci0000:00/0000:00:04.0/virtio1/net/veth1ac6779
Nov 17 23:40:10 staging systemd[2110]: sys-subsystem-net-devices-eth1.device: Dev sys-subsystem-net-devices-eth1.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:04.0/virtio1/net/eth1 and /sys/devices/pci0000:00/0000:00:04.0/virtio1/net/veth1ac6779
Nov 17 23:40:10 staging kernel: [ 4067.036964] virtio_net virtio1 veth1ac6779: renamed from eth1
```

From these logs it appears that eth1 changes to veth1ac6779. This makes sense given that ifconfig stops displaying eth1 and instead displays veth1ac6779 i.e
```
veth1ac6779 Link encap:Ethernet  HWaddr a2:d7:ca:06:c4:ef  
          inet addr:10.137.16.80  Bcast:10.137.255.255  Mask:255.255.0.0
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:578 (578.0 B)
```


You can find the relevant logs in their entirety here https://pastebin.com/Jzik3VFD. I pasted the logs from the first to the last time the problematic interface, veth1ac6779, is mentioned.

**Comment by svscorp** [comment]
> It seems like when docker restart brings down the networks it renames the digitalocean eth1 interface to vethxxx breaking the private network on the server.

@geigev exactly. experiencing the same issue on-premise (RHEL 7.3).

**Comment by geigev** [comment]
@svscorp I experience the exact same problem in 17.11.0-ce-rc4

**Comment by svscorp** [comment]
ping @fcrisciani @thaJeztah @vieux @mavenugo Isn't it a P0/1 as well? It appears in 17.10 (here there is a tag only 17.11) and confirmed with multiple users having the issue.

**Comment by geigev** [comment]
I renamed the `eth1` interface to `doeth1` and can no longer reproduce this issue.
@svscorp don't know if this is a reasonable workaround for you, but you might want to give it a shot.

**Comment by mavenugo** [comment]
@svscorp @geigev @pradipd We looked into the issue and found that the changes introduced in https://github.com/moby/moby/pull/34674 caused this issue. In short, the id for the new `lb-sandbox` is the same and during race condition the Sandbox was reused in libnetwork. When the sandbox was reused by an create and delete Sandbox calls, it resulted in the Sandbox's `eth1` corrupting the host namespace's eth1 resulting in this issue.

Fortunately, @pradipd pushed a change https://github.com/moby/moby/pull/35422 (which is currently under review) addressed this issue automatically. We are working actively to get this fix in for 17.12.

**Comment by mavenugo** [comment]
@geigev can you pls confirm if you are seeing this in 17.09 ? pls pass on the `docker version` for confirmation.
If you are able to see the same issue, then we have to identify what the root-cause for 17.09 is. But from our analysis (cc @fcrisciani ) this is introduced by https://github.com/moby/moby/pull/34674 which is introduced in 17.10.

**Comment by geigev** [comment]
@mavenugo thanks for following up. I was mistaken about 17.09 in my previous comment: I cannot actually reproduce the issue there -- sorry if it caused any confusion. I can only produce the issue in 17.10 and 17.11

**Comment by fcrisciani** [comment]
@geigev thanks for confirming, that is in line with the patch mentioned above, so the fix in place should be enough

**Comment by thaJeztah** [comment]
This is resolved through https://github.com/moby/moby/pull/35422, which is merged in master and will be included in the next Docker release as well
