### ISSUE TITLE
No volumes present but still docker throwing - volume name must be unique

### ISSUE THREAD

**Issue by piyush-nimbalkar** [moby/moby#35513]
**Description**

Had a docker volume which was deleted using the go docker client (docker/docker/client) after the container exited. The volume was removed using the force = false.

client.VolumeRemove(context.Background(), "my_vol_name", false)

```
docker volume ls
DRIVER              VOLUME NAME
```

```
docker volume create --driver pxd my_vol_name
Error response from daemon: create my_vol_name: found references to volume 'my_vol_name' in driver 'pxd' but the volume was not found in the driver -- you may need to remove containers referencing this volume or force remove the volume to re-create it: volume name must be unique
```
The volume driver also does not have the volume. Rather the POST call from create does not even come the volume driver.

Based on the above message, tried "force" removing the volume and creating again, it fails with the same message.
```
docker volume rm --force my_vol_name
my_vol_name

docker volume create --driver pxd my_vol_name
Error response from daemon: create my_vol_name: found references to volume 'my_vol_name' in driver 'pxd' but the volume was not found in the driver -- you may need to remove containers referencing this volume or force remove the volume to re-create it: volume name must be unique
```

Few questions here:
- Should the volume delete (without force) operation pass if an exited container has its reference? In this case it passed and vanished from `docker volume ls` as well.
- Now if we try to create volume with the same name, looking that it is not present in the list, shouldn't it pass?
- At least after doing a force delete (not sure what it does, if the volume is not present in list), should we be able to create the volume with same name?

It does let me create a local volume with the same name though.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local pxd
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: a1.dcos
ID: PWYA:S7Y4:DRMT:P6OW:M27H:AZKH:ZSOF:SIQ3:IX7S:E35H:YMEK:LBGZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a VirtualBox VM

**Comment by thaJeztah** [comment]
Docker 17.05 is not an up to date version of docker and has reached end of life in June; are you still able to reproduce this on a current version of docker?

**Comment by piyush-nimbalkar** [comment]
17.09.0-ce seems to not have this issue.
Thanks for informing @thaJeztah!

**Comment by thaJeztah** [comment]
Good to hear it's resolved :+1:

**Comment by gcommit** [comment]
Hello, i found the same issue on Ubuntu 16.04 when restarting a container: 

```
host-$ dpkg -l | grep docker
ii  docker-ce                            18.03.1~ce-0~ubuntu

```
docker: Error response from daemon: create my-container: found references to volume 'my-container' in driver 'rbd' but the volume was not found in the driver -- you may need to remove containers referencing this volume or force remove the volume to re-create it: volume name must be unique.

Quick fix: 
```
host-$ docker volume ls
DRIVER              VOLUME NAME
rbd                 my-container

host-$ docker volume rm my-container
Error: No such volume: my-container
```

-> start the container and it is up and running again...
