### ISSUE TITLE
tail -f does not print appended data

### ISSUE THREAD

**Issue by zhaixigui** [moby/moby#35523]
`tail -f /test.log` command executed in the container, /test.log is appended data, `tail -f` no response, does not print out the additional data.
termination `tail -f` command, you can see all of the content using the cat command (containing just additional data).
in addition: 
  not only the /test.log file, all text files are like this.
  this problem is rare

**Steps to reproduce the issue:**
 A console:
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# echo $(date) >> /test.log`
`[root@xingyun-gateway-399915342-dh3wg /]# `

Another console:
`[root@xingyun-gateway-399915342-dh3wg /]# tail -f test.log`
`Thu Nov 16 17:59:35 CST 2017`
``

**Output of  `/etc/centos-release`:**
CentOS Linux release 7.2.1511 (Core)

**Output of `docker version`:**
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**
Containers: 67
 Running: 40
 Paused: 0
 Stopped: 27
Images: 39
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.6GiB
Name: bjdfkjy-46-125.qbos.com
ID: CPR5:L2WP:HROU:5MXO:GERI:LG6T:AHSS:LOXD:LY6K:FPUT:ACGL:UA6Z
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 reg.qianbao-inc.com
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by shaynewang** [comment]
Hi @zhaixigui, how are you testing the `tail -f` feature? It works for me when I tested in the same container using the same tmux session. It also worked when I run in the same container like so: `docker exec -it <container-id> /bin/bash`. I see you have the same host name but are you running `tail -f` and append in the same container(not from `docker run -it ...`)?

**Comment by zhaixigui** [comment]
@shaynewang  the `tailf` and `tail -f` are the same

**Comment by cpuguy83** [comment]
Likely something to do with:

> WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Reformat the filesystem with ftype=1 to enable d_type support.

**Comment by cpuguy83** [comment]
But also that kernel is unsupported and should be updated.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
