### ISSUE TITLE
Docker compose volume type=tmpfs doesn't copy

### ISSUE THREAD

**Issue by rsdrsd** [moby/moby#35546]
My Dockerfile looks like this:
```
RUN mkdir -p /tmpfs/www/public && chown nginx:nginx /tmpfs/www/public 
VOLUME /tmpfs
```
Now I deploy the stack using a docker-compose.yml which contains the following:
```
www:
  volumes:
    - type: tmpfs
      target: /tmpfs
```
I'd expect that since I created `/tmpfs/www/public` in the `Dockerfile` that the created dirs would be visible, but the /tmpfs dir is empty.

**Docker version**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by boite** [comment]
I'm having a similar problem using a docker service and trying to mount `/var/run` as a tmpfs. The `/var/run/named` dir is present in the image, but not initially present in the container.  The dir appears only when the tmpfs is remounted.

Image (named "bind"):-
```
FROM alpine
RUN apk add --no-cache bind
VOLUME ["/etc/bind", "/var/bind"]
EXPOSE 53
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "named"]
```

Service:-

```sh
docker service create --name bind --publish 53:53/tcp --publish 53:53/udp \
  --replicas 1 --config source=bind_named.conf,target=/etc/bind/named.conf \
  --mount type=tmpfs,target=/var/run,tmpfs-mode=1777 \
  --mount type=tmpfs,target=/tmp \
  --mount type=volume,source=bind_etc-bind,target=/etc/bind \
  --mount type=volume,source=bind_var-bind,target=/var/bind \
  --detach=true bind
```

Inspect the container's fs:-
```sh
docker exec $(docker ps --filter name=bind -q) ls -al /var/run
total 4
drwxr-xr-x    2 root     root            40 Nov 27 17:15 .
drwxr-xr-x    1 root     root          4096 Nov 26 22:21 ..
```

Remount `/var/run`:-
```sh
docker service update --mount-rm /var/run \
  --mount-add type=tmpfs,target=/var/run,tmpfs-mode=1777
  bind
```

`/var/run/named` appears:-
```sh
docker exec $(docker ps --filter name=bind -q) ls -al /var/run/named
total 16
drwxrwx---    2 root     named         4096 Nov 27 17:16 .
drwxr-xr-x    3 root     root          4096 Nov 27 17:16 ..
-rw-r--r--    1 named    named            2 Nov 27 17:16 named.pid
-rw-------    1 named    named          102 Nov 27 17:16 session.key
```

It's entirely possible I'm doing something wrong!

**Comment by cpuguy83** [comment]
@rsdrsd This is expected behavior. Data is only copied for type=volume.

@boite this looks like a different problem. Note that the example you provided is not a recount. It's updating the service configuration which triggers the existing task (container) to be killed and a new one to replace it with the updated template.

Can you provide.... Maybe in a separate issue... The service inspect output before and after the change as well as the container inspect output before/after the change?

**Comment by rsdrsd** [comment]
How can I create a tmpfs with some folders in it then?

2017-11-28 15:15 GMT+01:00 Brian Goff <notifications@github.com>:

**Comment by cpuguy83** [comment]
@rsdrsd There is no way to do this. It would have to be done as a callback from runc since the tmpfs will be tied to the container lifecycle.

**Comment by rsdrsd** [comment]
Can’t I create some pre defined tmpfs folders with certain permissions in another way?

What is runc?

Verstuurd vanaf mijn iPhone

**Comment by mterron** [comment]
@cpuguy83 so how is tmpfs supposed to be used as non-root then?

**Comment by mterron** [comment]
Replying to @rsdrsd , myself and anyone else that is stuck with this:
You create a tmpfs mount for each directory you need with the following syntax:
`docker run --tmpfs /run/dir1:mode=770,uid=2000 --tmpfs /run/dir2:mode=770,uid=3000`

**Comment by rectalogic** [comment]
Aren't pre and post-mount callbacks used to copy existing contents into the tmpfs? This PR made me think it should work, but doesn't seem to.
https://github.com/moby/moby/pull/13212

**Comment by cpuguy83** [comment]
@rectalogic No, it's not doing anything like that. There was a PR merged at some point but was reverted because it broke things, particularly because it was using the `tar` command which is not standard across distros.
