### ISSUE TITLE
Docker health_status event not getting generated on Windows Server version 1709

### ISSUE THREAD

**Issue by harahma** [moby/moby#35551]
**Description**

I have a simple container with HEALTHCHECK enabled. The HEALTHCHECK script alternates between exit code 0 and 1 which causes the container to keep switching between healthy and unhealthy state. The docker is expected to generate health_status event as the container switches its health state. However docker is generating the health_status event only once after the container runs. Invoking 'docker inspect' command on container does show alternating health state.  

**Steps to reproduce the issue:**
1. Download the Dockerfile package [ContainerHealthCheck.zip](https://github.com/moby/moby/files/1488596/ContainerHealthCheck.zip) and unzip it.
2. Change directory to the unzipped folder and build the image using: docker build -t healthcheckimage:v1 .
3. Open another cmd window and start listening to docker health_status events using: docker events --filter "event=health_status"
4. Run the container using: docker run -d --name healthcheckcontainer healthcheckimage:v1
5. Wait for 30 secs.
6. Inspect health of container by running: 'docker inspect --format="{{json .State.Health}}" healthcheckcontainer'. You will see alternating exit code from health check script.
7. Look at the window listening to docker health_status event. It has only one health_status event.

**Describe the results you received:**
Listening to docker health_status event using 'docker events --filter "event=health_status"' only report single event.

```
2017-11-20T09:18:45.215939500-08:00 container health_status: healthy a52979e9e91534461544d456e352d34760f1420ae0eb2b21f167264fab0ac85d (image=healthcheckimage:v1, name=healthcheckcontainer)
```
Inspecting the health of container using `docker inspect --format="{{json .State.Health}}" healthcheckcontainer` does show alternating exit codes from health script.

```
{
"Status":"healthy",
"FailingStreak":1,
"Log": [
{
  "Start":"2017-11-20T09:19:42.907675-08:00",
  "End":"2017-11-20T09:19:44.7636395-08:00",
  "ExitCode":1,
  "Output":"Exit value read from file is 1\n"
},
{
  "Start":"2017-11-20T09:19:54.7638035-08:00",
  "End":"2017-11-20T09:19:56.6727694-08:00",
  "ExitCode":0,
  "Output":"Exit value read from file is 0\n"
},
{
  "Start":"2017-11-20T09:20:06.6729948-08:00",
  "End":"2017-11-20T09:20:08.5159382-08:00",
  "ExitCode":1,
  "Output":"Exit value read from file is 1\n"
},
{
  "Start":"2017-11-20T09:20:18.5160883-08:00",
  "End":"2017-11-20T09:20:20.413042-08:00",
  "ExitCode":0,
  "Output":"Exit value read from file is 0\n"},
{
  "Start":"2017-11-20T09:20:30.4133838-08:00",
  "End":"2017-11-20T09:20:32.2773822-08:00",
  "ExitCode":1,
  "Output":"Exit value read from file is 1\n"
}
]}
```

**Describe the results you expected:**
Docker should have reported multiple alternating health_status event for the container as we can see from inspecting the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:51:36 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-5
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:54:07 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.2-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 2.476GiB
Name: rahman-winserver
ID: R2UD:TXRT:PGLR:BTWC:YQRS:JAXB:ALFM:OYF5:ZL3G:H3WP:XUK3:DPRW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows version 1709 (OS Build 16299.15)

**Comment by thaJeztah** [comment]
ping @johnstep

**Comment by harahma** [comment]
I found the issue. It is with my health script logic. Docker internally retries the health script three times if it exits with exit code 1 before reporting the health. My health script logic was not taking this into account.

@thaJeztah  Please close this thread. Apologies for the inconvenience.
