### ISSUE TITLE
Container crash provoked a 132 error code (128 + 4 (Illegal Instruction)) on the container whenever I try to launch it again

### ISSUE THREAD

**Issue by ArvsIndrarys** [moby/moby#35556]
**Description**

Hi, I have some problem that I didn't manage to investigate on :

- I have an image that I built on armv7 that works on several rpis
- it was on running on a rasp, all it does is calling a golang program (binay execution : /myprogram )
- It encountered an error of type concurrent write on map that made the program crash
- The container was then blocked on a restarting (132) loop ; I investigated and 132 means 128 + 4. I mean 128 : container exit code and 4 : linux signal for Illegal Instruction ( http://www.manpages.info/linux/signal.7.html )
- From then on, I can't start that container back. I tried with `docker-compose down` then `docker-compose up -d` but it always fails with the `Restarting (132)` message
- And another time with `docker-compose down`, `sudo service docker stop`, `sudo service docker start` and back to `docker-compose up`
- I checked the image ID and pulled it on another raspberry and it launches perfectly.

So is there a way to reset docker on the failing rasp so as not to provoke that error? Or to ensure the container will start the way it does without having an Illegal Instruction code?

And I don't know how to provoke that issue consistently, I just had a go fatal error inside the container.  

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false

```
It the same version on the other rpi.  

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 4.4.50-hypriotos-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 861.9MiB
Name: hyper3
ID: DWAX:R3XN:MGCM:YTBP:MXH4:M7QO:K75X:4G2Z:JS56:IFBO:AJSX:Q5BZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dolanor
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ uname -a
Linux hyper3 4.4.50-hypriotos-v7+ #1 SMP PREEMPT Sun Mar 19 14:11:54 UTC 2017 armv7l GNU/Linux
```

**Comment by ArvsIndrarys** [comment]
I solved the problem by removing the image then re-pulling it.
Still the problem shown is strange, I let you close this when needed.

**Comment by thaJeztah** [comment]
Thanks for the update; let me close this indeed, but feel free to comment if you have more info

**Comment by dimitrovs** [comment]
> I solved the problem by removing the image then re-pulling it.

That's not really solving the problem, that's working round the problem! I have the exact same issue now with Docker version 17.12.1-ce, build 7390fc6 . It should be re-opened and investigated properly.
