### ISSUE TITLE
Expose traffic metrics that on a service or a service VIP

### ISSUE THREAD

**Issue by omerh** [moby/moby#35558]
Is there a way to get some network metrics of a service vip

- Request per second coming to the published port to the service VIP
- Response time of all nodes routing in traffic to the overlay network
- Response time of all nodes that actually runs the tasks (containers)

Am I missing it ? (Also checked it with cAdvisor and docker metrics)
I see packets metrics, network in/out bytes metrics, network action metrics...

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
