### ISSUE TITLE
Services stuck in UpdateStatus State of 'updating' for hours

### ISSUE THREAD

**Issue by WillNye** [moby/moby#35564]
#### Around 1 of 4 releases I encounter an issue where none of the services in our stack will update to the latest images. If I run docker service ls or docker service inspect it shows the correct image but if I run docker ps it will show the old image is being used an that a new container was never spun up. I'm running 3 nodes, each on their own physical host. I drained and pruned each node to make sure that wasn't part of the problem and even manually pulled the images on each node. Here is an example of this. 

```

Service Mode:	Replicated
 Replicas:	3
UpdateStatus:
 State:		updating
 Started:	11 minutes ago
 Message:	update in progress
Placement:
UpdateConfig:
 Parallelism:	2
 Delay:		10s
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first

```
**But running docker ps I can see it didn't update**
`"gunicorn -w 3 -t ..."   39 hours ago        Up 39 hours `

**Version**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

Also note that;

- docker 17.06 community edition has reached end of life
- if you cannot update to the current release (current stable is 17.09); at least make sure you update to the latest patch release for 17.06 (17.06.2)

**Comment by taiidani** [comment]
Possibly related, and happening on Docker 18.05 -- https://github.com/moby/moby/issues/37493

**Comment by thaJeztah** [comment]
closing, as this one went stale
