### ISSUE TITLE
Can specify the installation path of the built binaries?

### ISSUE THREAD

**Issue by arm64b** [moby/moby#35566]
**Description**
Currently, when I tried to `make install` the moby binaries after `make binary`, the installation path is hardcoded to `/usr/local/bin`, but in that path, I can't startup the docker daemon with `systemctl start docker` in my ubuntu 16.04 environment. I would like have a shortcut like this:
`make install --prefix=/usr/bin`
Then all the binaries will be copied into `/usr/bin/` path.

**Steps to reproduce the issue:**
1.
`make binary`
2.
`make install`
3.
`systemctl stop docker`
`systemctl start docker`

**Describe the results you received:**
The new built docker daemon can not be stood up

**Describe the results you expected:**
`systemctl start docker` will spawn a new docker daemon with the latest built binaries.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      unknown-version
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   e4940cb
 Built:        Fri Oct 27 10:08:49 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.06.0-dev
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   074b1fc
 Built:        Fri Oct 27 09:31:58 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 39
 Running: 3
 Paused: 0
 Stopped: 36
Images: 994
Server Version: 17.06.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: v1.0.0-beta.2-53-g992280e8 (expected: 992280e8e265f491f7a624ab82f3e238be086e49)
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.20
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: aarch64
CPUs: 64
Total Memory: 125.6GiB
Name: entos-huawei-d05
ID: X4QW:BJJZ:3MVW:GKDT:7YHJ:NNTZ:GV24:JI3Y:CNIL:CXGQ:Y2FP:UJEM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: arm64b
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All above operations are based on a physical AArch64 machine with ubuntu 16.04.

**Comment by arm64b** [comment]
I don't know if there's some method that can get the goal or this approach doesn't make sense for some unknown (at least for me) reason :)

**Comment by thaJeztah** [comment]
ping @tianon @cpuguy83 wdyt?

**Comment by cpuguy83** [comment]
That's fine. Can add a `PREFIX` variable that you pass through like `make PREFIX=/usr/bin install`

**Comment by arm64b** [comment]
@cpuguy83  Cool. Thanks @thaJeztah 👍
