### ISSUE TITLE
PortBindings in swagger definition is an Map[Object], API actually uses Map[Array]

### ISSUE THREAD

**Issue by ndeloof** [moby/moby#35577]
**Description**

`HostConfig` in swagger spec declares PortBindings as an object with Map/Dictionary properties https://github.com/moby/moby/blob/master/api/swagger.yaml#L608
Nested tuple object (HostIp, HostPort) is declared here as an Object, but the API actually returns an array (see https://groups.google.com/forum/#!topic/docker-dev/Ydz6-YcaSG0 if you wonder why)

**Steps to reproduce the issue:**
1. generate model form swagger spec.
2. use it to inspect a container
3. 

**Describe the results you received:**

`Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1402 path $.HostConfig.PortBindings.`

**Describe the results you expected:**

inspect response object mapped

**Output of `docker version`:**

```
Server:
 Version:      17.11.0-ce-rc3
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   5b4af4f
 Built:        Wed Nov  8 03:09:46 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm using swagger-codegen to generate java model : https://github.com/Dockins/jocker/blob/master/pom.xml#L55

**Comment by ndeloof** [comment]
it sounds to me using a `$ref: "#/definitions/PortMap"` to define `PortBindings` would just fix this

**Comment by thaJeztah** [comment]
Yes, look like it returns a `map[Port][]PortBinding{}`

```
    "PortBindings": {
      "80/tcp": [
        {
          "HostIp": "",
          "HostPort": "123"
        },
        {
          "HostIp": "",
          "HostPort": "456"
        }
      ]
    },
```

https://github.com/moby/moby/blob/master/api/types/container/host_config.go#L363
https://github.com/moby/moby/blob/master/vendor/github.com/docker/go-connections/nat/nat.go#L16-L25

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/35578 to fix this
