### ISSUE TITLE
Container has been removed, but its read-write layer and according mounting point stays.

### ISSUE THREAD

**Issue by YuxiJin-tobeyjin** [moby/moby#35571]
**Description**

After performing "docker commit" to a running container. Stop and remove this container,its read-write layer and according mounting point stays. I've tride some times,this problem is reproducible.

**Steps to reproduce the issue:**
1.Use "docker run" to run a container and record its id as  {container-id}；
2.Use “cat /var/lib/docker/image/overlay2/layerdb/mounts/ {container-id}***/mounts-id” to get the read-write layer id ,record this id as {rw-layerid}；
3.Locate the read-write layer's directory in /var/lib/docker/overlay2/ {rw-layerid};
4.Get the according mount point by run "mount |grep {rw-layerid}";
5.Use "docker exec {container-id}" to enter the container and make some changes，such as touch a new file；
6.Run docker commit {container-id}；
7.Run docker stop  {container-id}；
8.Run docker rm {container-id}.
9.Check the  read-write layer's directory and its mount point.

**Describe the results you received:**
Container has been removed ,but the read-write layer directory and the according mounting point belongs to this container stays.

**Describe the results you expected:**
The read-write layer directory and the according mounting point belongs to this container should be removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
```

**Output of `docker info`:**

```
Containers: 13
 Running: 9
 Paused: 0
 Stopped: 4
Images: 64
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System:
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639 GiB
Name: x-vm
ID: 72BV:RCH5:XXAK:HTPS:QGNA:Z7AH:7Q5S:PTTU:R6XO:JJFV:XKCC:3QTO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy:
Https Proxy: 
Registry: https://index.docker.io/v1/
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld0** [comment]
@YuxiJin-tobeyjin `docker-1.12` is no longer supported.

Since version `1.12` there were many bug fixes regarding the storage driver.
Do you mind updating docker to a newer version such as `17-09` and confirm this bug?

Thanks.

**Comment by YuxiJin-tobeyjin** [comment]
@ripcurld0 ， I‘ve tried on17-03,everything is fine.
I will close this issue.Many thanks.
