### ISSUE TITLE
Docker died with "fatal error: concurrent map writes" msg

### ISSUE THREAD

**Issue by ZigmunD** [moby/moby#35590]
**Description**

Docker daemon (worker node of swarm) died with "fatal error: concurrent map writes" msg in log.

**Steps to reproduce the issue:**
1. Form swarm cluster of few 17.11 docker nodes.
2. Deploy some services (~50)
2. ???
3. One docker worker died with "fatal error: concurrent map writes" msg.

Don't know if it is reproducable.

**Describe the results you received:**
Dead docker.

**Describe the results you expected:**
Alive docker.

**Additional information you deem important (e.g. issue happens only occasionally):**
Fresh swarm of 3 managers and 4 worker of new 17.11. Worked for an about 2 hours and then one docker died.

See complete log: https://gist.github.com/ZigmunD/424f942ef1430ad20d0c96a4a92d185d

Will add info if it will happen again.

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 29
 Running: 29
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: tzt6kbbtbpds5yeyuquc16ghs
 Is Manager: false
 Node Address: 10.9.243.11
 Manager Addresses:
  10.9.243.1:2377
  10.9.243.2:2377
  10.9.243.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-17-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.54GiB
Name: docker-w1.alahd.kz.dev
ID: XJE5:WC67:W6FI:XPY6:JR2K:E5FP:URAB:AXY4:MSH4:5VI5:S26N:FMQE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04.3 LTS 4.13.0-17-generic VM on Proxmox 5.

**Comment by ZigmunD** [comment]
Dup of https://github.com/moby/moby/issues/35588

My fault, sorry.

**Comment by thaJeztah** [comment]
duplicate of https://github.com/moby/moby/issues/35575, which is tracking this issue

Thanks for reporting 👍 please subscribe to that issue to stay informed of updates

**Comment by thaJeztah** [comment]
Scrap my last comment; different trace :blush:
