### ISSUE TITLE
dll's are missing in the windowsservercoreimage

### ISSUE THREAD

**Issue by vasankurgit** [moby/moby#35608]
Hi, i was trying to run ffmpeg in the windows server core container.
ffmpeg installes correctly but when i try to run, it returns no output and error.
Which works fine in the base image.
Reason:-
avicap32.dll and msvfw32.dll, dependency of ffmpeg, are missing in container.

**Comment by AkihiroSuda** [comment]
This *may* work: https://social.technet.microsoft.com/Forums/windowsserver/en-US/251af965-0db2-436e-b0f1-67e6b91ba527/avicap32dll-install-on-server-core-2008-r2?forum=winservercore

I'm closing this issue, since not specific to moby.
