### ISSUE TITLE
Console width / height unusable on Windows 10 FCU using edge 17.11

### ISSUE THREAD

**Issue by bgelens** [moby/moby#35616]
**Description**

I'm running Docker on Windows 10 Fall creator update (1709) build 16299.64 (non insider) in Windows native mode (without VM). I'm using both LCOW and WCOW and both modes have the same issue as the console width / height are so far off that it becomes almost unusable. This happens when starting a container with interactive terminal and connecting it to PowerShell or bash process. It doesn't seem to happen with cmd.exe.

**Steps to reproduce the issue:**
1. docker run -it microsoft/windowsservercore:1709 powershell

**Describe the results you received:**
When running with powershell, the input is cut of half way. (see image below)

**Describe the results you expected:**
When running with cmd, the input is not cut half way (see image below). I would expect powershell to behave the same.

![tweeten-1511814250264](https://user-images.githubusercontent.com/10071039/33287860-5ed59cb2-d3ba-11e7-9c06-de8270438241.jpg)

**Additional information you deem important (e.g. issue happens only occasionally):**

When switched to LCOW and connecting to bash, the same thing happens only this time, when the end is reached, the line starts to be overwritten from the start.

```
docker run -it azuresdk/azure-cli-python bash
```

![bash](https://user-images.githubusercontent.com/10071039/33288013-ffd2d878-d3ba-11e7-9d70-0f85393c55e6.gif)

Also in LCOW, when connecting to PowerShell Core 6, I have different behavior where the line is echoed when it reaches the end.

```
docker run -it microsoft/powershell pwsh
```

![tweeten-1511814309488](https://user-images.githubusercontent.com/10071039/33288027-1556be62-d3bb-11e7-868e-5b0ff9f304d8.jpg)

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:30:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:34:19 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info WCOW`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.11.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88GiB
Name: DESKTOP-NGL9IH4
ID: FENY:QCL6:V4G7:RAND:44J6:JVJA:AMX4:7OPX:EHBO:TU3D:Y44O:4ZMI
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 37
 System Time: 2017-11-27T21:32:59.8049349+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `docker info LCOW`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.11.0-ce
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88GiB
Name: DESKTOP-NGL9IH4
ID: FENY:QCL6:V4G7:RAND:44J6:JVJA:AMX4:7OPX:EHBO:TU3D:Y44O:4ZMI
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2017-11-27T21:34:17.7752844+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jhowardmsft** [comment]
Looking

**Comment by jhowardmsft** [comment]
@bgelens Thanks for reporting. Found the cause. Fix submitted in https://github.com/moby/moby/pull/35631
