### ISSUE TITLE
Docker load: generate unique ID or tag

### ISSUE THREAD

**Issue by vrothberg** [moby/moby#35625]
`docker load` attempts to load a specified tar archive and will use an existing tag in case the layers/hashes are identical to an already present image. It is not possible to change that behavior in order to get a unique tag or ID - neither on the CLI nor the API.

This is a feature request to add this or a similar functionality in order to make `docker load` usable in automation.

The lack of generating a unique ID with `docker load` is currently causing issues in `containerdiff` (see https://github.com/GoogleCloudPlatform/container-diff/pull/149#discussion_r153408770) where a tar archive must be loaded for some analyses and the image must be removed afterwards. However, as we're not sure if the loaded image has been present before, a blind removal is not an option. A 100% complete workaround isn't possible as locking the daemon isn't possible (neither an option). Notice that the described issue doesn't occur with `docker import` due to different semantics and the flat filesystem.  However, even if I `docker import` the same tar archive multiple times in a row, docker will always give a new ID.

**Comment by thaJeztah** [comment]
The difference here, is that with `docker load`, you're loading an existing repository from a tar, including it's manifests. With `docker import`, you're creating a new image from a rootfs that you pass as a tar. In the `docker import` case, a new manifest is created, which means the metadata inside that manifest will differ with each import, leading to a new ID.

I'm not sure how this would have to be resolved, because the whole reason for `docker load` is to restore exactly what was in the archive, and restore the repository that you're loading.

/cc @tonistiigi @aaronlehmann

**Comment by vrothberg** [comment]
@thaJeztah Thanks a lot for looking into this. The API for `docker load` seems to be quite locked (https://godoc.org/github.com/moby/moby/client#Client.ImageLoad) as there's no struct in the arguments that we could easily extend, so I understand it's not as easy as one might wish. Having a boolean switch to indicate generating a new, unique ID would be optimal.

However, from a user's perspective, there is no way to figure out if the image of the newly loaded tar was present prior to `docker load`. All attempts to work around that by, for instance, looking at image metadata will run into a race condition with the other (potential) users of the client. In case of a name conflict, the already present image will be renamed but renaming it back to its initial tag would then be a race condition.

**Comment by tonistiigi** [comment]
You should save the image with a unique tag. Then loading it to a system that already has the image will just add one extra tag. And removing the image by the tag just untags it and leaves the original image in place.

**Comment by vrothberg** [comment]
@tonistiigi Unfortunately, this would run into similar issues as at the time of loading the tar, the previously unique tag might have already been taken. The only way I see to avoid such naming conflicts is in the daemon, and thus in `docker load` as this is *the* critical section of the code and workflow.

An intermediate solution, for now, is to reserve the `containerdiff` namespace to have partial control over the tags. To avoid concurrent tagging of other processes, we need to use a file-system lock. It's far from ideal, but the only way to make sure not to change existing images.

If I may rephrase the description and break it down to the core of the problem: there is no way to load a tar archive without changing/breaking other images, and this is a crucial requirement for our use case.

**Comment by vrothberg** [comment]
@tonistiigi @aaronlehmann @thaJeztah How shall we proceed? Are you interested in such an extension? Otherwise, feel free to close the issue.

**Comment by thaJeztah** [comment]
Would it be sufficient if the load API returned the image-ID? i.e.;

```bash
$ docker image load -i bla.tar 
loaded image hello-world:latest
image ID: sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7
```

Now tag that image with a unique tag;

```bash
$ docker image tag f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7 hello-world:bbab7aea12314343892be3088c73aec6346cf312efe5c663f699f6c473e8e4e3
```

(now, do some scanning/processing of the image)


And remove the image:

```bash
$ docker image rm hello-world:bbab7aea12314343892be3088c73aec6346cf312efe5c663f699f6c473e8e4e3
Untagged: hello-world:bbab7aea12314343892be3088c73aec6346cf312efe5c663f699f6c473e8e4e3
```

Which will either _remove_ the image if this was the last tag, or _untag_ if there are still other tags referring to the same image.

**Comment by vrothberg** [comment]
@thaJeztah I think that would be a big step forward, but one problem we encountered with `container-diff` was that `docker load` untags an already present image with the same tag (as in the tar's manifest), see below:

```bash
  docker load -i os423.tar                                                                               
726237ad5159: Loading layer  111.8MB/111.8MB
Loaded image: opensuse:42.3

  docker run --rm opensuse:42.3 cat /etc/os-release                                                      
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

  docker load -i alpine.tar 
The image opensuse:42.3 already exists, renaming the old one with ID sha256:ecb6d0d596fc43d3dddd8e9ae1d8f9a057d351969ac3da3379ea300ea5e0f0d5 to empty string
Loaded image: opensuse:42.3

  docker run --rm opensuse:42.3 cat /etc/os-release                                                      
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
````

If `docker load` wouldn't untag the previous image *but* return the digest, the issue would be solved.

**Comment by thaJeztah** [comment]
A tag is (like in Git) a reference to a sha. Asking docker to load an image tells it to put the tag on the image that was loaded.


If you're not interested in the tag (from your description, you're not, but just need something unique), you can save the image _without_ the tag;


```bash
$ docker image pull hello-world

Using default tag: latest
latest: Pulling from library/hello-world
ca4f61b1923c: Pull complete 
Digest: sha256:66ef312bbac49c39a89aa9bcc3cb4f3c9e7de3788c944158df3ee0176d32b751
Status: Downloaded newer image for hello-world:latest
```

```bash
$ docker image tag hello-world hello-foo

$ docker image ls --no-trunc

REPOSITORY          TAG                 IMAGE ID                                                                  CREATED             SIZE
hello-foo           latest              sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7   8 weeks ago         1.85kB
hello-world         latest              sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7   8 weeks ago         1.85kB
```

Now, instead of saving the image (by `image:tag`) use the image ID as reference;

```bash
$ docker image save f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7 > f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7.tar
```

Loading that image will only load the image, but not tag it:

```bash
$ docker image load -i f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7.tar 

Loaded image ID: sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7
```

So existing images are not affected:

```bash
$ docker image ls --no-trunc

REPOSITORY          TAG                 IMAGE ID                                                                  CREATED             SIZE
hello-foo           latest              sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7   8 weeks ago         1.85kB
hello-world         latest              sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7   8 weeks ago         1.85kB
```

And you can run use it by image ID (or create a new, unique tag);

```bash
$ docker run --rm f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7

Hello from Docker!
This message shows that your installation appears to be working correctly.

...
```

**Comment by vrothberg** [comment]
@thaJeztah Thanks a lot for the detailed explanation and your time!

In the specific use-case of `container-diff`, the integrity of tags is a key requirement in the sense that no tag should be changed without the explicit consent of the user. Please excuse if I wasn't clear about that. I understand that there are ways to avoid the issue I mentioned but the problem persists that a user cannot control the tag when loading an archive. There are ways to avoid that proactively as you have demonstrated above, but there are no means to protect after the fact (i.e., when loading an archive that the user didn't generate but downloaded).

I believe that it's more common to reference images via tags than via the specific digests, so I would argue that the option to tell the daemon to load an archive without tagging the image would be a useful extension as it preserves the integrity of tags. It's perfectly fine to work around the mentioned issue as a single user via the command line as images can be re-tagged but it's getting really hairy in automation with concurrent accesses to the daemon where the integrity of tags plays a key role.

`docker pull` supports that in a way already as an image can be pulled via its digest without being tagged afterwards. Having a similar way for loading would be great.

**Comment by vrothberg** [comment]
Closing as there doesn't seem to interest from upstream, unfortunately.
