### ISSUE TITLE
with volume plugin, cant mount device to container directly

### ISSUE THREAD

**Issue by keyolk** [moby/moby#35635]
Sorry if this is duplicated.

Using volume plugin, 
seems there is no proper way to mount device to container directly without mounting it on host.

When I use NFS with docker plugin([netshare](https://github.com/ContainX/docker-volume-netshare)),
I found that its NFS usage counted by host basis,
and I need to mount the NFS within containers network namespace.

Writing own NFS driver,
I saw there is interface like

- VolumeDriver.Mount
- VolumeDriver.Path

but at the time when the mount handler called,
there is no way to find which container requested the volume.

I assume that using the volume plugin, it acts like
1. plugin mounts volume on host
2. dockerd deliver it to container using bind mount

I have questions about the following.
- Is there a way to mount volume to container directly (without mounting on host)?
- Is there a reason why there is some restriction ?

**Comment by cpuguy83** [comment]
> Is there a way to mount volume to container directly (without mounting on host)?

Not as part of the API. You could enter the container's NS after it's started, but currently there is no way to do this before the container is started.

> Is there a reason why there is some restriction ?

Just the way it's designed. You'll find this works the same way on kube as well. Plugin mounts to a specified host path and then kube bindmounts to container.

We could potentially support a raw mount type that would just inject the mount options into runc... not sure if mounts are setup in the new network NS or not, though.

Example, in the container's spec that gets sent to runc to create there is a list of mounts that are passed through that are basically literally mount options which get passed to the mount syscall.

We could do something like `--mount type=raw,source=<device>,target=<container target>,raw-opts=<opts>` where anything that is `type=raw` would be passed directly to runc.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
