### ISSUE TITLE
docker-containerd version seems to be old in docker CE and docker engine 1.13.1 onwards

### ISSUE THREAD

**Issue by msavlani** [moby/moby#35646]
@mlaventure @thaJeztah 

I was checking few issues related to docker ps hung and came across #26374
It seems in docker 1.12.2 this was fixed by bumping docker-containerd to version 0.2.4 as per #26374 and below PR was submitted by you.
https://github.com/containerd/containerd/pull/321/files

I verified that is correct in docker 1.12.6 as well.

## Docker 1.12.6
$ /usr/bin/dockerd --version
Docker version 1.12.6, build 78d1802
$ /usr/bin/docker-containerd -version
containerd version **0.2.4** commit: 2a5e70cbf65457815ee76b7e5dd2a01292d9eca8

But if check version for this from docker 1.13.1 onwards i see it went back to 0.2.3
Please see below -

## Docker 1.13.1
$ /usr/bin/dockerd --version
Docker version 1.13.1, build 092cba3
$ /usr/bin/docker-containerd -version
containerd version **0.2.3** commit: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1

## Docker 17.05.0-ce
$ usr/bin/dockerd --version
Docker version 17.05.0-ce, build 89658be
$ usr/bin/docker-containerd -version
containerd version **0.2.3** commit: 9048e5e50717ea4497b757314bad98ea3763c145

## Docker 17.09.0-ce
$  usr/bin/dockerd --version
Docker version 17.09.0-ce, build afdb6d4
$ usr/bin/docker-containerd -version
containerd version **0.2.3** commit: 06b9cb35161009dcb7123345749fef02f7cea8e0

Is it alarming or this checks are incorrect from myside ?

**Comment by msavlani** [comment]
@cpuguy83 Any comments you can throw on this one ?

**Comment by thaJeztah** [comment]
I think the differences here are that for some patch releases following 1.12, containerd was built from the https://github.com/docker/containerd fork, e.g. see https://github.com/moby/moby/commit/0311ed7b1cb701a2dfa32e28f34c7f702c98c8c1. On that fork, there's some branches in which fixes were cherry-picked

I'm not sure where your `0.2.3` tag comes from; for Docker 17.03, 17.06 you'll find [tags in the containerd repository](https://github.com/containerd/containerd/releases?after=v1.0.0-alpha1), for example;

https://github.com/containerd/containerd/releases/tag/v0.2.8 (commit: https://github.com/containerd/containerd/commit/9048e5e50717ea4497b757314bad98ea3763c145) used by Docker 17.05

https://github.com/containerd/containerd/releases/tag/v0.2.9 (commit: https://github.com/containerd/containerd/commit/cfb82a876ecc11b5ca0977d1733adbe58599088a) used by Docker 17.06

GitHub doesn't really like comparing though, so it's a bit hard to tell the difference just from these URL's

Docker 17.09  <--> Docker 1.12.6
https://github.com/containerd/containerd/compare/06b9cb35161009dcb7123345749fef02f7cea8e0...2a5e70cbf65457815ee76b7e5dd2a01292d9eca8

Docker 1.12.6 <--> Docker 17.09
https://github.com/containerd/containerd/compare/2a5e70cbf65457815ee76b7e5dd2a01292d9eca8...06b9cb35161009dcb7123345749fef02f7cea8e0

Note that starting with Docker 17.11, Docker uses the Containerd 1.0 branch, and at some point in future may start using packages built by the ContainerD project / distros (which is being worked on)
