### ISSUE TITLE
Files leaking to other images in a multi-stage build

### ISSUE THREAD

**Issue by vlk-charles** [moby/moby#35641]
**Description**

Files can leak from one image to a different one in a multi-stage build process. I was able to isolate the bug to the following minimalist case.

**Steps to reproduce the issue:**
1. `echo 'This file should only appear in the first image.' >afile`
2. `echo 'This file should only appear in the second image.' >bfile`
3. Save this `Dockerfile`:
```
FROM alpine
WORKDIR /root
COPY afile .

FROM alpine
WORKDIR /root
COPY bfile .
```
4. `docker build .`
5. `docker run --rm <second image> ls`

**Describe the results you received:**

```
afile
bfile
```

**Describe the results you expected:**

```
bfile
```

**Additional information you deem important (e.g. issue happens only occasionally):**
The bug is consistent on this machine but is not present on a different virtual server with CentOS 7, XFS, and devicemapper.

As can be seen from the log, the `WORKDIR` instruction is cached:
```
Sending build context to Docker daemon  4.096kB
Step 1/6 : FROM alpine
 ---> 665ffb03bfae
Step 2/6 : WORKDIR /root
 ---> 24e2272aca94
Removing intermediate container ebdaacce5267
Step 3/6 : COPY afile .
 ---> 9507351e2ff4
Step 4/6 : FROM alpine
 ---> 665ffb03bfae
Step 5/6 : WORKDIR /root
 ---> Using cache
 ---> 24e2272aca94
Step 6/6 : COPY bfile .
 ---> b7a5fa8bdc29
Successfully built b7a5fa8bdc29
```

`ls` lists no files on the common intermediate layer (24e2272aca94).

If I add another unique no-op instruction before the `COPY` to break the caching at that layer:
```
FROM alpine
WORKDIR /root
RUN echo no-op layer 1
COPY afile .

FROM alpine
WORKDIR /root
RUN echo no-op layer 2
COPY bfile .
```
, the files are where they should be. I will be using this approach as a work-around for now.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 190
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 25.51GiB
Name: ubuntu1
ID: ZSC7:3VAV:U3JD:XIUN:OLEV:HS2T:GTYX:RE6E:WQHC:4CDB:WGWI:IQKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This on a physical server. `/etc/docker/daemon.json` only contains:
```
{
"storage-driver": "overlay2"
}
```

**Comment by tonistiigi** [comment]
Looks same as https://github.com/docker/for-linux/issues/135 . @dnephin Did you have time to look into it?

**Comment by flx42** [comment]
As mentioned in https://github.com/docker/for-linux/issues/135. The best workaround is indeed to add a no-op `WORKDIR .` layer before the `COPY`.

With @cliffwoolley we stumbled into a similar problem while creating multi-stage builds for our deep learning images, here's a small repro:
```
FROM alpine as base

FROM base as build
COPY Dockerfile /tmp/Dockerfile

FROM base
COPY --from=build /etc/os-release /tmp/os-release
CMD ["cat", "/tmp/Dockerfile"]
```

@tonistiigi: can you double-check if it's indeed the same issue? I'm not 100% sure since our case doesn't match what you mention in https://github.com/docker/for-linux/issues/135#issuecomment-341860769:
> The next copy reuses the mount for the destination target because it was also used in the COPY in first stage. 

This Dockerfile in this issue copies both files to `/root`, and https://github.com/docker/for-linux/issues/135 copies both files to `/usr/src/app`, but that's not the case with my Dockerfile above.

**Comment by vlk-charles** [comment]
Just retested this on 17.12. Still happens.

**Comment by jsm174** [comment]
I'm seeing this same issue - 17.09.1-ce-mac42 (21090)

```
FROM node:carbon AS base
WORKDIR /usr/src/app
COPY package*.json ./
COPY index.js .

FROM base AS builder
COPY webpack.common.js .
COPY webpack.prod.js .
COPY src ./src
RUN npm install --only=production
RUN cp -R node_modules prod_node_modules
RUN npm install
RUN npm run build

FROM base
COPY --from=builder /usr/src/app/prod_node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
ENV NODE_ENV production
EXPOSE 8080
CMD node index.js
```

When I launch a shell in the container:

```
docker exec -it 1226335d91f5 /bin/bash
root@1226335d91f5:/usr/src/app# ls
dist  index.js	node_modules  package-lock.json  package.json  webpack.common.js webpack.prod.js
```

I'm assuming I should not be seeing the webpack*.js files.

**Comment by vlk-charles** [comment]
@jsm174 Yes, seems you should not be able to see them, unless it is the `CMD` creating them. You can make sure it is not the `CMD`:
```
docker run --rm <image> ls
```
Adding something like `RUN true` between `FROM base` and the `COPY`s in the final stage should work around it.
