### ISSUE TITLE
Feature request: Add a docker stack inspect command

### ISSUE THREAD

**Issue by vce-xx** [moby/moby#35648]
This is a request for a docker stack inspect command.
The command would return the stack yml definition (maybe with resolved parameter values).
(This would be consistent with "docker-cloud stack inspect" and would help moving from Docker Cloud to Docker Swarm).

**Comment by ripcurld0** [comment]
@vce-xx thanks for your interest in the project.
Can you elaborate more what information it will display or at least a link to "docker-cloud stack inspect" information.

Thanks.

**Comment by vce-xx** [comment]
There are "docker-cloud stack inspect" and "docker-cloud stack export".

What I was looking for is the equivalent of "docker-cloud stack export" which returns a yaml file and is documented there : https://docs.docker.com/apidocs/docker-cloud/#export-an-existing-stack

`docker-cloud stack export --help
usage: docker-cloud stack export [-h] [-f FILE] identifier

Export the stack from Docker Cloud

positional arguments:
  identifier            UUID or name of the stack

optional arguments:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  the name of the file to export to`

This exports the yaml stack definition to a file.

I am also looking for a equivalent of "docker-cloud stack inspect" is useful to get a status on my running stacks and is documented there : https://docs.docker.com/apidocs/docker-cloud/#get-an-existing-stack

`docker-cloud stack inspect --help
usage: docker-cloud stack inspect [-h] identifier [identifier ...]

Inspect a stack

positional arguments:
  identifier  stack's UUID (either long or short) or name

optional arguments:
  -h, --help  show this help message and exit`

`Example:
docker-cloud stack inspect xwiki
{
  "current_num_containers": 2,
  "name": "wiki",
  "synchronized": true,
  "destroyed_datetime": null,
  "uuid": "xxx",
  "state": "Running",
  "services": [
    "/api/app/v1/xxx/service/xxx/",
    "/api/app/v1/xxx/service/xxx/"
  ],
  "deployed_datetime": "Fri, 30 Jun 2017 13:37:03 +0000",
  "nickname": "wiki",
  "dockercloud_action_uri": "",
  "resource_uri": "/api/app/v1/xxx/stack/xxx/"
}`

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now. Given that `docker stack` is implemented in the docker cli (not the daemon), this would likely have to be implemented there
