### ISSUE TITLE
DIND container stuck/in zombie state when killed with paused containers

### ISSUE THREAD

**Issue by yrivardmulrooney** [moby/moby#35643]
**Description**

When running a docker in docker setup, if we have a paused container (paused via docker pause) in the innermost docker daemon and the docker in docker container is killed via SIGKILL (either via docker kill, or by timing out when using docker stop), the dind container get stuck in a limbo state where it's still considered running by the docker daemon, but the main process is dead. The only processes that seem to still be inside when running a docker top are the containers that were paused (docker-shim & container process). It also looks like we can't directly SIGKILL those processes, so we're stuck with a dind container that doesn't work and can't be restarted except by rebooting the top level docker daemon.

**Steps to reproduce the issue:**
1. Start a docker in docker container
2. Run any container inside the dind container (I tested with busybox)
3. Pause the container in the dind container
4. Use docker kill on the dind container

**Describe the results you received:**
Docker kill hangs, the dind container stays running with stuck processes

**Describe the results you expected:**
Dind container terminates and wipes all child processes

**Additional information you deem important (e.g. issue happens only occasionally):**
Tested with multiple docker version (both top level and dind version): 17.03.2-ce, 17.06.2-ce, 17.09.0-ce. Tested on ubuntu 14.04 and 16.04 (most tests were on 14.04 though).

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 77
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-135-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: ndev-dpm84
ID: 3W5V:J2RT:BAHG:R27C:DXAB:XFYI:W6KM:TYEI:4K3L:2WD6:C6NS:FO6S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running in AWS

**Comment by mlaventure** [comment]
Probably happens because the parent can't be fully reaped until all its children are, and since the container is paused that cannot occur. Forcing an unpause via the cgroup should unblock it (e.g. `echo THAWED > /sys/fs/cgroup/freezer/docker/<dind-id>/docker/<paused-container>/freezer.state`)

The only solution would be for docker to manually check if the container has children recursively and force thaw them. I'm thinking this may be better done in `runc` though (cc @crosbymichael)

**Comment by yrivardmulrooney** [comment]
I can confirm that forcing the unpause via the cgroup with the command above fixes the issue and allows the dind container to exit properly.

**Comment by tianon** [comment]
Does stopping the inner daemon via SIGTERM (so that it can gracefully shut
down as opposed to the SIGKILL being used here) work?  Does Docker
unfreeze/kill these containers during shutdown?

**Comment by yrivardmulrooney** [comment]
Yes, stopping the inner daemon via SIGTERM works fine, it's only an issue when forcefully killing the container via docker kill or if docker stop times out and in turn tries to SIGKILL it.

**Comment by cpuguy83** [comment]
This makes sense, since you can't send a signal to a paused process.
On daemon shutdown we actually send the signal and then unpause the container which causes the signal to be sent as soon as the container is unpaused.

For this to succeed, the runtime will need to cleanup any frozen processes within the container.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
