### ISSUE TITLE
Sending SIGKILL to a docker run process in interactive mode does not stop the container

### ISSUE THREAD

**Issue by DesktopMan** [moby/moby#35647]
**Description**

I am trying to timeout an interactive docker session using _timeout_ as there is no timeout option in docker itself.

**Steps to reproduce the issue:**

1. timeout --signal=SIGKILL 5 docker run --rm -it alpine /bin/sh
2. Wait 5 seconds

**Describe the results you received:**

Interactive session closes but the container is still running in the background. 

**Describe the results you expected:**

I would expect the container to be stopped (and removed in the example above due to --rm).

**Output of `docker version`:**

```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 20
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 80
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.729GiB
ID: ID4U:FCSW:GD7L:RFHA:3H3D:EYMU:DNX4:B26W:5J7J:5XNT:L7DP:NDFF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
This is because `SIGKILL` is sent to the docker CLI which is forced to exit. Processes are unable to react to receiving a `SIGKILL`.
For any other signal this would work so long as you don't use `-t`, which disables signal-proxying.

Closing since this is behaving as expected.
Thanks!

**Comment by DesktopMan** [comment]
So I removed -t as you suggested, and here are my results:

* timeout -s TERM 1 docker run --rm alpine sleep 5
Does not exit when the timeout occurs.
* timeout -s SIGINT 1 docker run --rm alpine sleep 5
Does not exit when the timeout occurs.

Which signal is supposed to work?

**Comment by cpuguy83** [comment]
@DesktopMan There's more to this...

1. sleep will sleep for the full 5 seconds as it does not process signals
2. Many programs drop default signal handlers when run as PID 1... including `/bin/sh`.

If you run this with the `--init` option, it will exit when the signal is sent.

**Comment by DesktopMan** [comment]
Ah I see, that was the detail I was missing. Thanks!
