### ISSUE TITLE
Windows 2016 Dockerfile mkdir hangs

### ISSUE THREAD

**Issue by goffinf** [moby/moby#35654]
**Description**

Building a simple image from microsoft/windowsservercore:10.0.14393.1884 when the instruction RUN mkdir is attempted the build hangs (sometimes indefinitely until I kill the docker process). It leaves behind a stopped container which cannot (easily) be removed.

**Steps to reproduce the issue:**

Using this Dockerfile

FROM microsoft/windowsservercore:10.0.14393.1884
ENV WINDOWS_IMAGE_VERSION=10.0.14393

RUN mkdir C:\BuildAgent
WORKDIR C:/BuildAgent
COPY ./Start.* ./

CMD ["Start.cmd"]

PS> docker build -t myname/myimage:1.0.0 .

-or-

PS> docker-compose build  (service name: agent)

**Describe the results you received:**

```
Sending build context to Docker daemon 7.168kb
Step 1/6 : FROM microsoft/windowsservercore:10.0.14393.1884
 ---> edc711fca788
Step 2/6 : ENV WINDOWS_IMAGE_VERSION=10.0.14393
 ---> using cache
 ---> dd687b78fa50
Step 3/6 : RUN mkdir C:\BuildAgent
 ---> Running in 606f07612c55
```
--- HANGS HERE ---

```
PS> docker container ls -a      (sometimes this command will hang also)

CONTAINER ID   IMAGE               COMMAND                   CREATED              STATUS 
606f07612c55    dd687b78fa50   "cmd /S /C 'mkdir ..."     37 minutes ago    Dead
```

There are occasions where it will actually return with a failure something like this (note: this was run as docker-compose build  pointing to the same Dockerfile as above for the service 'agent') : 

Also note that the Docker service is running under a domain account (in the local administrators group) called svc_digital_docker

```
Service 'agent' failed to build: re-exec error: exit status 1: .... msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\\\?\\C:\\ProgramData\\docker\\\windowsfilter\\421565d169ebb.... flavour=1 folder=C:\\Users\\svc_digital_docker\\AppData\\Local\\Temp\\hcs377512887"
```

In the Event Log I have seen : 

```
Error running exec in container: invalid container 606f07612c55...
```
and also ...

```
driver error deleting endpoint jovial_hawking : HNS failed with error: Unspecified error

hcsshim::ExportLayer failed in WIn32: The process cannot access the file because it is being used by another process (ox20) layerId=606f07612c55... flavour=1 folder=C:\Users\svc_digital_docker\AppData\Local\Temp\hcs377512887
```

Attempting to remove the container : 

```
docker container rm -f 606f07612c55    

Error response from daemon driver "windowsfilter" failed to remove root filesystem for 606f07612c55....  rename C:\ProgramData\docker\windowsfilter\606f07612c55...  C:\ProgramData\docker\windowsfilter\606f07612c55...-removing: Access is denied     

```

While the build is in a 'hung' state :  

```
PS> Get-Disk

Number   Friendly Name      Serial Number  Health Status    Operation Status   Total Size   Partition Style
0              AWS PVDISK         0000                  Healthy             Online                   150GB        MBR
1              Msft Virtual Disk                             Healthy             Online                     20GB       GPT
```

**Describe the results you expected:**

A successful build image

**Additional information you deem important (e.g. issue happens only occasionally):**

Have run this successfully on a local Windows 2016 DC VM

Only seems to happen on AWS

Have tried changing the account for the Docker service to LSA - same behaviour

**Output of `docker version`:**

```
Client:
  Version:          17.06.2-ee-6
  API Version:    1.30
  Go version:     go1.8.3
  Git commit:    e75fdb8
  Built:              Mon Nov 27 22:46:09  2017
  OS/Arch:        windows/amd64

Server:
  Version:          17.06.2-ee-6
  API Version:    1.30 (minimum version 1.24)
  Go version:     go1.8.3
  Git commit:    e75fdb8
  Built:              Mon Nov 27 22:46:09  2017
  OS/Arch:        windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
Images: 4
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
  Windows:
Logging Driver: json-file
Plugins:
  Volume: local
  Network: l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1480.amd64fre.rs1_release.170706-2004)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPIs: 2
Total Memory: 4GiB
Name: EC2AMAZ-xxxxxxxx
ID: XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: xxxxxx
Https Proxy: xxxxx
No Proxy: xxxxx
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
  127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS
EC2 instance size: t2:medium
Docker service runs under a domain account (in the local Administrators group) - svc_digital_docker
Have tried configuring the service with the LSA account - same behaviour
AV software: Trend 9.x

**Comment by friism** [comment]
Can you reproduce the problem outside of AWS? (eg. on your desktop or on an on-prem machine).

You might also want to try a larger instance size, and try removing, disabling or adding an exception for the antivirus software to see if that helps.

Ultimately, you should probably also open an issue with AWS and/or Microsoft. Docker EE support in Windows Server is handled by Microsoft (who can escalate to Docker if needed).

**Comment by goffinf** [comment]
Thx Michael,

If I run the same docker build on a local VirtualBox VM it works fine.

Yeah the instance size is relatively small for Windows and normally I would go for an M4.large or 2x but while I was testing and spinning up lots of instances for short periods I was using. t2.medium just to keep the costs down a bit (per second charging doesn’t apply here). Anyway I will give that a go.

The base AMI that I have to use has some additional hardening (applied to the AWS marketplace image) which is mandated by our CISO although I can get some exceptions if I need them, it really a matter of targeting where.

Actually iro docker version we are using 17.09.0ce (I was just trying EE to see if that made any difference). v17.09.0ce exhibits the same behaviour as does 17.06.2ce

To rule out the account used for the docker service, I built a new AMI leaving that owned by the Local System Account. Again, no change.

The error messages are much the same : 

The system cannot find the path specified ... pointing to a layer under ProgramData\docker\windowsfilter\container-id ... folder=C:\Windows\Temp\hcs185646867

Event log shows the same errors and also a warning : 

driver error deleting endpoint eager_rosalind : HNS failed with error: Unspecified error.

One useful pointer, which made me think it might be a permissions error is, if I do a Docker build without the mkdir it completes successfully ???

Any further thoughts much appreciated.

Fraser.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
