### ISSUE TITLE
docker logs get lost when using journald log driver

### ISSUE THREAD

**Issue by jinuxstyle** [moby/moby#35653]
**Description**

**Steps to reproduce the issue:**
The fast method to reproduce is creating a container with log driver journald and image busybox and echo 100 logs per second.
```
$ name=systemd-logs; docker rm -f $name; docker run -d --name $name --log-driver journald busybox sh -c 'i=0;while true; do echo ["$i"]: $(date); sleep 0.01; let i+=1; done'; docker logs -f $name
```
**Describe the results you received:**
The docker logs -f command hangs after hundreds of lines of logs printed and resumes after a while, but logs lost in the middle.

**Describe the results you expected:**
There should be no loss of logs.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Actually, I think this may be journald itself dropping logs due to rate limiting (see https://www.rootusers.com/how-to-change-log-rate-limiting-in-linux/)

Closing as a duplicate of https://github.com/moby/moby/issues/31058, but feel free to comment

**Comment by jinuxstyle** [comment]
Right. It's caused by the default journald rate limiting. Thank you!

**Comment by thaJeztah** [comment]
Good to hear it's resolved :+1:
