### ISSUE TITLE
"func (cli *Client) ContainerRemove(ctx context.Context, containerID string, options types.ContainerRemoveOptions) error" containerID parameter should rename to containerName

### ISSUE THREAD

**Issue by JanKari** [moby/moby#35666]
**Description**
When I use client library's "ContainerRemov " to remove a container,I set the containerID with container's id, But the container is not removed without any errors.
when I set the containerID parameter with container's name, the container is deleted successfuly.
so I suggest to rename containerID parameter to containerName, or this will mislead somebody to set this parameter with container'id.

Thanks!

**Comment by ripcurld0** [comment]
@JanKari can you share your code with us, please?
I couldn't reproduce this problem on my computer.

**Comment by thaJeztah** [comment]
Closing as this went stale
