### ISSUE TITLE
Add node Hostname to system labels

### ISSUE THREAD

**Issue by antongocode** [moby/moby#35667]
With the addition of .Node.Hostname to available templating variables #34686 it should be trivial to add more node information to the system labels of each contianer. At a minimum, adding the node hostname will simplify debugging certain system issues a lot.

I don't mind submitting a PR for this, but would just like to get some feedback or possible objections.

**Comment by thaJeztah** [comment]
What exactly do you mean with "system labels"? Also, could you explain the use case a bit more in-depth, perhaps some example as to what you'd expect?

**Comment by antongocode** [comment]
The following labels get added to every container on startup and prefixed with `com.docker.swarm`:
```
daemon/cluster/executor/container/container.go

system = map[string]string{
    "task":          "", // mark as cluster task
    "task.id":       c.task.ID,
    "task.name":     c.name(),
    "node.id":       c.task.NodeID,
    "service.id":    c.task.ServiceID,
    "service.name":  c.task.ServiceAnnotations.Name,
}
```
In the code it's referred to as "system labels".

My use case is finding the machine that the container is running on. Since the node id is already provided I can use it to do a lookup for the node hostname using `docker node ls`, but this can become rather tedious when debugging.

With the change in #34686 more node information is injected in the container config and it should be simple to just extract the node hostname from there and add it to the labels.

**Comment by thaJeztah** [comment]
The potential problem I see is that hostname can be updated for a running node, whereas node-ID is immutable.

Is there a reason `docker service ps` doesn't work for your use-case?

**Comment by antongocode** [comment]
I was thinking along those lines as well, but since the hostname is now exposed through templating and will be set at startup, I'm inclined to think that argument might be slightly moot. Perhaps worthwhile revisiting, but it does seem like an inconsistent approach to exclude this change on those grounds.

Our main use case is actually using the value as a prometheus metric label. [cadvisor](https://github.com/google/cadvisor) exposes all the instance labels as prometheus labels. From what I could see it doesn't have additional configuration, so this would be the solution.

**Comment by thaJeztah** [comment]
Closing per the above; I think this can be addressed with templating
