### ISSUE TITLE
LCOW: parse of /etc/resolv.conf failed

### ISSUE THREAD

**Issue by AlekseyMartynov** [moby/moby#35669]
Using https://github.com/linuxkit/lcow#setup
Server Version: master-dockerproject-2017-11-30

```
docker run --rm -ti ubuntu bash
apt-get update
apt-get install dnsutils iputils-ping
```

/etc/resolv.conf has an entry with 2 IPs separated by space which Ubuntu cannot parse

```
cat /etc/resolv.conf
nameserver 172.28.64.1
nameserver XX.XX.XX.XX YY.YY.YY.YY
search corp.example.com
```

(XX.XX.XX.XX and YY.YY.YY.YY are LAN DNS servers)

```
nslookup any
nslookup: parse of /etc/resolv.conf failed
```

**Comment by thaJeztah** [comment]
How are those DNS servers setup? If DNS servers are provided on the daemon, or on `docker run` (through the `--dns` flag), each DNS is written to its own line; https://github.com/docker/libnetwork/blob/43f00b74d70e10dcf6adcceb8ead360e10ed49ca/resolvconf/resolvconf.go#L235-L239

```bash
$ docker run --rm --dns=8.8.8.8 --dns=8.8.4.4  alpine cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Trying to pass an invalid IP-address as `--dns` will produce an error;

```bash
$ docker run --rm --dns="8.8.8.8 8.8.4.4"  alpine cat /etc/resolv.conf
invalid argument "8.8.8.8 8.8.4.4" for "--dns" flag: 8.8.8.8 8.8.4.4 is not an ip address
See 'docker run --help'.
```


However, if no DNS options are provided, a copy of the `/etc/resolv.conf` from the host is used for the container;

```bash 
$ docker run --rm alpine cat /etc/resolv.conf
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain docker.com
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
```

The following bind-mounts the host into the container, and checks the host's `/etc/resolv.conf`, which matches the above output:

```bash
$ docker run --rm -v /:/host alpine cat /host/etc/resolv.conf
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain docker.com
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
```

Based on the above, I don't think this is a bug in the moby code-base, but an incorrectly formatted `/etc/resolv.conf` on the host;

What does `/etc/resolv.conf` on the host look like?

**Comment by AlekseyMartynov** [comment]
@thaJeztah 
The issue is about the new "Linux Containers on Windows" mode of Docker for Windows. The host is Windows machine, so there's no /etc/resolv.conf on the host.

**Comment by friism** [comment]
@AlekseyMartynov since this is LCOW-related, consider opening an issue here: https://github.com/Microsoft/opengcs/issues
