### ISSUE TITLE
[Build] File deletion does not work in userns enabled engine

### ISSUE THREAD

**Issue by zibok** [moby/moby#35709]
**Description**

In docker with userns-remap option activated, removing a file from a previous layer is not taken into account. In syslog, we find errors like:

```
Can't add file /var/lib/docker/500000.500000/overlay2/xxxx/diff/path/to/file to tar: Host ID 0 cannot be mapped to a container ID
```

**Steps to reproduce the issue:**
1. Run docker with `--user-remap=default`
2. Use the Dockerfile
```
FROM busybox

RUN echo "foo" > /bar

RUN rm -f /bar

RUN ls -la /bar
```
3. `docker build --cache .`

**Describe the results you received:**

You will see the last step still shows /bar exists

In syslog, you find a:
```
msg="Can't add file /var/lib/docker/500000.500000/overlay2/ae3d56600bb897918129265a43f0b54a7693d190ce1a4d8ab333787673c41dd0/diff/bar to tar: Host ID 0 cannot be mapped to a container ID"
```

**Describe the results you expected:**

/bar should not be visible in the last layer

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue is reproductible

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 47
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 492.4MiB
Name: stretch
ID: HJSC:OKNJ:FNOI:2G52:OYNL:KULV:C3P5:W5YC:Y4NX:LH2C:QZVB:SQCN
Docker Root Dir: /var/lib/docker/500000.500000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproductible on a vagrant box running Debian 9

**Comment by zibok** [comment]
Also reproduced on Docker 17.11.0-ce

**Comment by thaJeztah** [comment]
ping @estesp

**Comment by estesp** [comment]
Hmm..I can reproduce. The whiteout (deletion) marker file is being treated as a regular file instead of being ignored from what I can tell, and so instead of applying the deletion when assembling the layers, you get a failed to map ID, so the deletion isn't applied (leaving the file as if it was still there). Surprised this hasn't been hit before, or maybe some other change caused this and there isn't a test? I'll have to dig a bit more

**Comment by estesp** [comment]
A bit more detail: this is `bar` as you would expect after being created:
```
drwxr-xr-x 3 165536 165536 4096 Dec  8 19:20 .
drwx------ 5 165536 165536 4096 Dec  8 19:20 ..
-rw-r--r-- 1 165536 165536    0 Dec  8 19:20 bar
```

To debug I'm not using a `Dockerfile` but running a container, executing the command, then using `docker commit` to act like build layers; then running the next committed image (layer) to test; after removing bar and committing, the layer becomes:
```
drwxr-xr-x 3 165536 165536 4096 Dec  8 19:23 .
drwx------ 5 165536 165536 4096 Dec  8 19:22 ..
c--------- 1 root   root   0, 0 Dec  8 19:23 bar
```

And that's the issue; as it's owned by `0:0` the ID mapping code will fail, producing the log message in the original report.

**Comment by thaJeztah** [comment]
@estesp marking as bug?

**Comment by keyolk** [comment]
seems it is duplicated issue, https://github.com/moby/moby/issues/32919

**Comment by keyolk** [comment]
container in userns, 
all root owned file shoud be mapped another id.
but seems in this case
whiteouted file's uid/gid doesnt mapped with remapped id.
so, it failed to convert id between host<->container.

**Comment by estesp** [comment]
Correct; the problem is finding where whiteout files are getting 0-owned instead of ownership set to remapped root uid/gid. It appears to be an overlay2 specific issue as I don't see any claim that it happens with overlay or aufs.

**Comment by keyolk** [comment]
seems if the files is whiteout, 
it should skip remapping its ID
https://github.com/moby/moby/blob/master/pkg/archive/archive.go#L462

**Comment by estesp** [comment]
@keyolk this seems like a reasonable fix; can you create a PR from your branch? If not I can cherry-pick it into a PR myself and you will be the committer on the patch
