### ISSUE TITLE
docker event for exec_die

### ISSUE THREAD

**Issue by ndeloof** [moby/moby#35702]
**Description**

As a container terminate by itself (main PID 1 process complete) an `container die` event is reported with exit code. 
As an exec process completes, docker inspect do report updated `ExecIDs` set but no event is logged. As a result, one only can monitor exec completion by polling. An `container exec_die` event would allow an asynchronous implementation.

My actual use case is to run build processes in an existing containers from a Jenkins plugin. I'd like to avoid polling this container for exec completion.

**Steps to reproduce the issue:**
1. run `docker event`
2. start a container with `sleep 100`
3. run docker exec ID echo hello

**Describe the results you received:**

logged events:
- container exec_create
- container exec_start
- container die

**Describe the results you expected:**

logged events:
- container exec_create
- container exec_start
- container exec_die
- container die

**Comment by thaJeztah** [comment]
Discussing this in the maintainers meeting, and we think adding these events make sense.

There is some discussion around order of events for `container die` and `container exec_die` (weren't sure if they can guaranteed to arrive in the correct order); that may need some research.

Are you interested in implementing this?

**Comment by ndeloof** [comment]
Yes, thanks !

**Comment by ndeloof** [comment]
I'm not worried about the arrival order, could just be documented not to be guaranteed if there's a risk for some race condition.
For my own use-case I just need some way to know an exec completed without polling.

**Comment by ndeloof** [comment]
https://github.com/moby/moby/pull/35744
