### ISSUE TITLE
RFC: enable AuthZ on the unix socket

### ISSUE THREAD

**Issue by xvello** [moby/moby#35711]
As the Datadog agent needs to list and inspect containers, images and volumes for monitoring, we currently connect to the `/var/run/docker.sock` unix socket. Although the monitoring entrypoints are stable and expose enough data, exposing the docker socket to the agent comes with a security risk: an attacker could use it to stop containers, run malicious ones and even get `root` access on the host. Although we are currently working on getting all the information we need via the orchestrator, we want to support all orchestrators, including Swarm and vanilla Docker.

We have been investigating [the AuthZ system](https://docs.docker.com/engine/extend/plugins_authorization/), with Twislock's third-party [AuthZ plugin](https://github.com/twistlock/authz) for RBAC filtering. Unfortunately, as the unix listener does not currently have TLS enabled, all requests via the unix socket fail because no user is authenticated. This is unacceptable to most of our clients as either they rely on the unix socket for adminitration or they use an orchestrator that require access to the socket. This is why we investigated how to improve on the current situation. In this RFC I'd like to discuss two solutions we could contribute:

## "Easy" solution: enable HTTPS on the unix socket

We could patch [the uds listener](https://github.com/docker/go-connections/blob/master/sockets/unix_socket.go) to wrap its traffic in TLS like [the tcp listener](https://github.com/docker/go-connections/blob/master/sockets/tcp_socket.go#L17) does.

This would re-enable the unix socket, as long as we configure the docker CLI and the orchestrators to provide a valid client certificate. This has two drawbacks:

- if the user does not already have a PKI for their cluster, setting one up can be a significant hurdle
- we'd need to test (and probably patch) all orchestrators to support HTTPS over `unix://` traffic

## Preferred solution: authenticate using the `UCred` information

When listening on a unix socket, a process can use the [`SO_PEERCRED`](http://man7.org/linux/man-pages/man7/socket.7.html) option, which makes the kernel transmit the client process' credentials. From this `UnixCredentials` struct, the server can get the PID, UID and GID of the process:

```go
type Ucred struct {
    Pid int32
    Uid uint32
    Gid uint32
}
```

While on other unices the credentials are passed by the client and verified by the kernel, on Linux the credentials are injected by the kernel, hence very secure. Several server applications ([mysql](https://dev.mysql.com/doc/refman/5.5/en/socket-pluggable-authentication.html), [pgsql](https://www.postgresql.org/docs/9.1/static/auth-methods.html#AUTH-PEER) for example) implement this as an authentication method.

[We already use](https://github.com/DataDog/datadog-agent/blob/master/pkg/dogstatsd/listeners/uds_linux.go) its datagram equivalent `SO_PASSCRED` to retrieve the `PID` of incoming statsd metric packets and tag metrics with the relevant container tags, so we know handling this in Go is pretty simple.

If we implement this, no change will be required on the client side, they will continue using HTTP over UDS on `/var/run/docker.sock`. The docker daemon will:

- retrieve the peer UID on new connections
- lookup `/etc/passwd` and fetch the unix username
- pass `unix:username` (or `unix:UID` if no match is found) to the AuthZ system
- the AuthZ will need no change and will lookup this user in their configuration. Prefixing the username would allow both this method and TLS client certs to coexist without collisions.

Whitelisting `unix:root` will allow orchestrators and the docker CLI to function as normal, then we'd provide limited RBACs for our `dd-agent` user, that only allow read-only endpoints. This might also open new use cases, like providing limited `docker ps` / `docker stats` access to all local users.

We are willing to contribute the code necessary to make that viable, but we prefer to discuss with maintainers and contributors before starting the implementation.

What do you think?

**Comment by thaJeztah** [comment]
ping @n4ss @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
We have discussed this before and decided to not implement authN in moby and leave it to wrappers to implement.

> As the Datadog agent needs to list and inspect containers, images and volumes for monitoring

This looks like a good use-case to focus on. What are we missing from the metrics endpoint that needs to be added so that we don't need to give control to monitoring processes?

**Comment by xvello** [comment]
Thanks for your feedback. When talking about the metrics endpoint, are you talking about the new `/metrics` prometheus endpoint?

We collect performance metrics directly from the kernel cgroup accounting system, to support the widest range of docker versions. Container info we retrieve from the docker socket is mostly metadata from the inspect, including:

- container labels, image name, envvars for [metric tagging](https://github.com/DataDog/datadog-agent/blob/master/pkg/tagger/collectors/docker_extract.go)
- container IP and ports for [autodiscovery](https://docs.datadoghq.com/guides/autodiscovery/)
- attached networks to tag container net metrics per network name

We also collect:
- events
- container logs for [our new logs product](https://www.datadoghq.com/blog/announcing-logs/)

Some of this information (including labels/envvars) is considered sensitive information by many clients and should not be exposed on an un-authenticated endpoint though.

**Comment by xvello** [comment]
Hi @thaJeztah @cpuguy83 , what do you think about our metadata collection needs? Would they fit in the scope of the new endpoint, or should we continue the discussion on this?

**Comment by justincormack** [comment]
I think allowing TLS on unix domain sockets makes sense. I don't like `PEERCRED` as it is not portable, and adds a whole different class of users totally orthogonal to the existing ones, so anyone using auth now would have to rewrite their filters, and it would be very error prone, as essentially you have two different types of user based on connection method.

**Comment by unshare** [comment]
As for me, peer authentication makes sense. AuthZ already calls for such an orthogonality:
```
{
    "User":              "The user identification",
    "UserAuthNMethod":   "The authentication method used",
    .........
}
```
As far as I can see, `UserAuthNMethod` is always `TLS` now. But the API is already ready for such an enhancement.

Using peer authentication allows the end-user to take advantage of all the OpenSSH and PAM flexibility.
Peer authentication is also _very_ useful in the light of SSH connection support in Docker CLI (upcoming in 18.09): moby/moby#31871, docker/cli#1014.

**Comment by unshare** [comment]
@justincormack just in case

**Comment by mpalmer** [comment]
I, for one, would *love* to see `SO_PEERCRED` used to provide Unix user information for local socket connections.  I don't understand what is meant by

> We have discussed this before and decided to not implement authN in moby

because that ship has sailed -- you've already implemented authn via TLS, so why not provide it for local connections too?

If we've got to implement a wrapper for local access, that means maintaining two completely separate authz systems -- one for local access via the Docker CLI (a wrapper script) and an AuthZ plugin for remote access.

TLS over Unix socket would be a bit of a pest, too -- having to maintain certs on servers just so people can prove who they are when there's already a perfectly cromulent method of proving identity available to use...
