### ISSUE TITLE
Support a STOP/PAUSE directive similar to ENTRYPOINT or CMD in dockerfile

### ISSUE THREAD

**Issue by govint** [moby/moby#35715]
**Description**
When a container is running and actively using a volume to persist data, stopping the container seems to kill the app running in it. The application stops abruptly and the state of the data is unknown. The container app needs to perform recovery on being restarted to bring its data to a sane state. The _docker stop_ command description indicates SIGTERM is sent to the process on stop. The issues with this approach are:Every app is required to set up a handler just to handle a stop event and to bring its data to a sane state before exiting. Even this isn't guaranteed if the app is unable to complete its exit in time before docker issues a SIGKILL.

This issue is to request adding a STOP/PAUSE directive in the dockerfile so developers have the flexibility to add entry points in their app that will allow control for the app over how its stopped/paused - allowing the app to maintain data in a sane state before it exits.

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
The application needs to be able to complete its exit formalities and ensure data persisted in its volume is sane before it exits.

**Additional information you deem important (e.g. issue happens only occasionally):**
None.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 17
 Running: 11
 Paused: 0
 Stopped: 6
Images: 20
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /vol/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 2lg225uqlj8qfv7b9qcfghlny
 Is Manager: true
 ClusterID: p6gss81s1olwcj02cxmtxiek6
 Managers: 2
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
  External CAs:
    cfssl: https://10.160.10.252:12381/api/v1/cfssl/sign
    cfssl: https://10.160.61.207:12381/api/v1/cfssl/sign
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.160.61.207
 Manager Addresses:
  10.160.10.252:2377
  10.160.61.207:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86GiB
Name: sc-rdops-vm02-dhcp-52-237
ID: NINK:HV2F:IRM2:6JJU:XBVA:DW7J:CV5S:OARB:J4UL:O7S3:4LBA:7AVE
Docker Root Dir: /vol/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Aren't linux signals designed for just this reason? I.e., sending a (stop) signal to a process instructs that process to perform the actions needed to terminate

If the default `SIGTERM` is not the correct signal for the process to exit cleanly, an alternative signal can be set using the [`STOPSIGNAL`](https://docs.docker.com/engine/reference/builder/#stopsignal) Dockerfile instruction, or using the `--stop-signal` option on `docker run` / `docker create`.

A default stop-timeout can also be set using ` --stop-timeout`

**Comment by govint** [comment]
Is it expected every app that's deployed as a container implement logic to use signal handling?. A STOP/PAUSE directive in the dockerfile seems more elegant and easily customizable by a user. Especially,  to change how an app can be stopped vs. doing a code change in the app to use a different signal handler in the app code. Using a signal to stop the containered app should be a last resort (as today) if the STOP request to app doesn't work.

**Comment by cpuguy83** [comment]
@govint signals are how linux asks a process to stop.
Running a script to stop a process will still end up sending SIGTERM (or SIGINT, SIGKILL) to the main process.
Given that the image builder is in control of what actually gets started, they can implement start/stop scripts as part of some init process in the container (or even use systemd. in the container... but there are most definitely more appropriate alternatives).

For pause, one of the intents of pause is to not give the process a chance to react to being paused, as such signals are not even used for this.

**Comment by mterron** [comment]
@govint  you might want to look at Joyent's [containerpilot](https://www.joyent.com/containerpilot)

**Comment by govint** [comment]
My only concern with handling signals in the app is having to build platform specific handling to terminate the app. It's best if the app could be notified to exit via a stop entry-point that the app defines and use a signal as a _force_ option.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
