### ISSUE TITLE
Permissions for /etc/resolv.conf different if  loop-lvm or direct-lvm is used

### ISSUE THREAD

**Issue by rmohammed-xtime** [moby/moby#35722]
**Description**
The permissions of the /etc/resolv.conf are 644 if the loop-lvm is used.
The permissions of the /etc/resolv.conf are 640 if the direct-lvm is used.

**Steps to reproduce the issue:**
1. Check the permission of /etc/resolv.conf on host machine
2. Run dockerd with devicemapper and loop-lvm
3. Examine permissions of /etc/resolv.conf when running a container
4. Run dockerd with devicemapper and direct-lvm
5. Examine permissions of /etc/resolv.conf when running a container

# ll /etc/resolv.conf
-rw-r--r--. 1 root root 95 Oct 25 13:19 /etc/resolv.conf
# ps -ef | grep dockerd
root     31709     1  1 10:41 ?        00:00:00 /usr/bin/dockerd --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 --storage-driver=devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt=dm.use_deferred_removal=true
# docker run busybox ls -l /etc/resolv.conf
-rw-r-----    1 root     root            95 Dec  6 18:41 /etc/resolv.conf

# ps -ef | grep dockerd
root      5931     1  0 10:32 ?        00:00:00 /usr/bin/dockerd --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 --storage-driver=devicemapper
# docker run busybox ls -l /etc/resolv.conf
-rw-r--r--    1 root     root            95 Dec  6 18:42 /etc/resolv.conf

**Describe the results you expected:**
I expect the /etc/resolv.conf permissions to be 644 - match the permissions on the host machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
[root@kubmasrn-01sc8 common]# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-519760-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 27.85 MB
 Data Space Total: 107.4 GB
 Data Space Available: 46.89 GB
 Metadata Space Used: 602.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 9.599 GiB
Name: kubmasrn-01sc8
ID: CMDE:Q6H2:ZFHX:ODGS:B2ZB:ESJN:KKCF:TLFB:C3HB:4RIZ:LGBS:XDPP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
[root@kubminrn-01sc8 common]# docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 19
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 9.805 GB
 Data Space Total: 61.2 GB
 Data Space Available: 51.39 GB
 Metadata Space Used: 5.644 MB
 Metadata Space Total: 641.7 MB
 Metadata Space Available: 636.1 MB
 Thin Pool Minimum Free Space: 6.119 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 9.599 GiB
Name: kubminrn-01sc8
ID: NYB2:AR63:HMTV:UP2D:YVIA:KW2H:GMYU:FEAK:LZR5:MEO5:272D:DOSR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.4.1708 (Core)
Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kolyshkin** [comment]
/etc/resolv.conf is created on the host and is bind-mounted to a container (and so permissions from the host files are used). Please check the permissions on the host:
```
# ls -l /var/lib/docker/containers/$ID/resolv.conf
```

One reason for different permission can be different umask value when starting the daemon.

**Comment by rmohammed-xtime** [comment]
Thanks for the comment.

I'm able to reproduce this on the same machine switching between loop-lvm and direct-lvm and starting the daemon the same way:
# ls -al /etc/resolv.conf
-rw-r--r--. 1 root root 95 Oct 25 13:19 /etc/resolv.conf
# getfacl /etc/resolv.conf
getfacl: Removing leading '/' from absolute path names
# file: etc/resolv.conf
# owner: root
# group: root
user::rw-
group::r--
other::r--

With loop-lvm:
# ls -l /var/lib/docker/containers/5a0f2abdd3cb494ec6f3fbddd60eb578f26ebe290208f706e5303a2f83dd314c/resolv.conf
-rw-r--r--. 1 root root 95 Dec  6 12:47 /var/lib/docker/containers/5a0f2abdd3cb494ec6f3fbddd60eb578f26ebe290208f706e5303a2f83dd314c/resolv.conf

With direct-lvm:
# ls -l /var/lib/docker/containers/d41d9c615948e103197dda8df614f921de92bf3c1311c0034f00572c10181b39/resolv.conf
-rw-r-----+ 1 root root 95 Dec  6 12:49 /var/lib/docker/containers/d41d9c615948e103197dda8df614f921de92bf3c1311c0034f00572c10181b39/resolv.conf

**Comment by rmohammed-xtime** [comment]
@kolyshkin 

Thanks again for your comment.

The issue as you said was a permission issue but on /var/lib/docker:
getfacl /var/lib/docker/containers
getfacl: Removing leading '/' from absolute path names
# file: var/lib/docker/containers
# owner: root
# group: root
user::rwx
group::---
group:td-agent:r-x
mask::r-x
other::---
default:user::rwx
default:group::---
default:group:td-agent:r-x
default:mask::r-x
default:other::---

The default other was not set so setting default "other" fixed the issue
setfacl -R -d -m o::rx /var/lib/docker
# docker run busybox ls -l /etc/resolv.conf
-rw-r--r--    1 root     root            95 Dec  6 21:15 /etc/resolv.conf
# ls -al /var/lib/docker/containers/06cdb4ba9f951b1981d93cdc56a93a1234dd2e83ef8e1f0b0f59a478fc3a0709/resolv.conf
-rw-r--r--+ 1 root root 95 Dec  6 13:15 /var/lib/docker/containers/06cdb4ba9f951b1981d93cdc56a93a1234dd2e83ef8e1f0b0f59a478fc3a0709/resolv.conf
