### ISSUE TITLE
Test for Mesosphere

### ISSUE THREAD

**Issue by alexellis** [moby/moby#35736]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
Derek close

**Comment by thaJeztah** [comment]
:tada:

**Comment by alexellis** [comment]
Derek reopen

**Comment by alexellis** [comment]
Derek set title: Demo of Derek

**Comment by alexellis** [comment]
@thaJeztah this is what edit title looks like.

**Comment by thaJeztah** [comment]
Derek set title: Hello Captains

**Comment by ripcurld0** [comment]
@alexellis that's awesome!

**Comment by alexellis** [comment]
@ripcurld0 thanks! If you'd like to try out Derek on an organisation or repo - or to suggest Derek for another project, let me know. alex@openfaas.com
