### ISSUE TITLE
`docker login` using `--password-stdin` doesn't work with typed passwords.

### ISSUE THREAD

**Issue by LukeusMaximus** [moby/moby#35746]
**Description**
Using `docker login --username <username> --password-stdin <registry-address>` has some weird behaviour in how stdin is used by Docker.

**Steps to reproduce the issue:**
1. Use the login command `docker login --username <username> --password-stdin <registry-address>`, prompt now waits for a password to be typed.
2. Type a password and hit enter.

**Describe the results you received:**
Prompt hangs infinitely, awaiting more input.

**Describe the results you expected:**
`docker login` prints "Login Succeeded" and exits.

**Additional information you deem important (e.g. issue happens only occasionally):**
Pressing Ctrl-D to send an EOF to stdin results in the correct behaviour. It seems --password-stdin only works if your password is in a file.

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 47
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 229
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: luke-thinkpad
ID: JIYB:V3WA:TB4U:7QDB:S7Y4:2R2U:7XLY:C4LK:W4GL:2DFT:CZZ3:24LJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on laptop. No special setup of particular note.

**Comment by thaJeztah** [comment]
That's the expected behavior: the `--password-stdin` option is to provide the password non-interactively (i.e., by piping it in); if you want to integrative enter the password, just skip that flag. There's no need for the `--username` option as well in that case; just:

    docker login <registry address>

or if you're logging in to docker hub:

    docker login


and docker will prompt for a username and password

**Comment by LukeusMaximus** [comment]
Ah, it wasn't clear that you could do that from the help page.

**Comment by jbarwick** [comment]
if you do this:
docker login -u username --password-stdin<enter>
mypassword<^Z><enter>

that is <enter> - press the enter key
and is <^Z> - press control-Z

Then it will work just fine.  WHATEVER YOU TYPE will be the password until the End-Of-File marker has been set or the STDIN handle has been closed.  control-Z closes the input handle.
