### ISSUE TITLE
Restarting dockerd causes IPv6 networking to be deconfigured in all containers

### ISSUE THREAD

**Issue by mpalmer** [moby/moby#35757]
**Description**

When `dockerd` is restarted, and the `--live-restore=true` flag is in use, existing containers are not restarted (good!), but any IPv6 networking configuration the containers have is completely destroyed (bad!).  A restart of the container is required to reinstate IPv6 networking.

**Steps to reproduce the issue:**

1. Install the latest version of Docker (`curl https://get.docker.com | sh`).  I used an Ubuntu 14.04.5 x64 Digital Ocean droplet for my reproduction test, as it is fairly close to our production environment.
2. Set `DOCKER_OPTS` in `/etc/default/docker` to something like

        DOCKER_OPTS="--ipv6 --fixed-cidr-v6=2001:db8::/64 -s aufs --bip 172.17.0.1/16 --log-opt max-size=1m --log-opt max-file=2 --live-restore=true --raw-logs"

3. Restart docker with `service docker restart`
4. Create a container:

        # docker run -dit --name test busybox sh

5. Verify that it does, in fact, have some IPv6ness going on:

        # docker exec test ip -6 ad sh
        1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
            inet6 ::1/128 scope host 
               valid_lft forever preferred_lft forever
        10: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
            inet6 2001:db8::242:ac11:2/64 scope global flags 02 
               valid_lft forever preferred_lft forever
            inet6 fe80::42:acff:fe11:2/64 scope link 
               valid_lft forever preferred_lft forever
        # docker exec test ip -6 ro sh
        2001:db8::/64 dev eth0  metric 256 
        fe80::/64 dev eth0  metric 256 
        default via 2001:db8::1 dev eth0  metric 1024 
        unreachable default dev lo  metric -1  error -101
        ff00::/8 dev eth0  metric 256 
        unreachable default dev lo  metric -1  error -101

6. Restart docker:

        # service docker restart

7. Verify that the container didn't restart:

        # docker ps
        CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
        70e3de2aed43        busybox             "sh"                About a minute ago   Up About a minute                       test

8. Check IPv6 networking:

        # docker exec test ip -6 ad sh
        # docker exec test ip -6 ro sh
        unreachable default dev lo  metric -1  error -101
        unreachable default dev lo  metric -1  error -101

**Describe the results you received:**

None of my containers had IPv6 networking until they were manually restarted.

**Describe the results you expected:**

My containers had IPv6 networking, without needing to restart.

**Output of `docker version`:**

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:10 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-135-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.9MiB
Name: docker-fuckup-test
ID: AQLH:V7FG:MRUD:7DD2:VVAA:JX5F:RRQS:4X4H:ZOEP:XE3N:EOWI:X37U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This reproduction was carried out in a DigitalOcean droplet created just now from the Ubuntu 14.04.5 x64 base image, running the above Docker version.  Our production environment, in which this problem manifested itself, is Ubuntu 14.04.5 running on bare metal, on Docker 17.06.2-ce (commit `cec0b72`).  We had previously upgraded from Docker 1.12, so the problem could have been introduced anywhere between 1.12 and 17.06.2-ce.

**Comment by coding-horror** [comment]
This was the proximate cause of a four hour all-site outage on our hosting platform, so I would appreciate it if someone from the Docker team could prioritize this bug. It caused us to lose customers.

**Comment by ripcurld0** [comment]
I think I may know why.
@mpalmer can you give the daemon logs at the time you reloaded/restarted dockerd?

Sorry for the inconvenience, 
Thanks.

**Comment by mpalmer** [comment]
Here is the debug-level log of everything that was captured by upstart during the restart process: [docker_restart.log](https://github.com/moby/moby/files/1547334/docker_restart.log).  Hope it's enlightening.

**Comment by ripcurld0** [comment]
@mpalmer thank you so much for this.
I thought the problem was related to my change here: https://github.com/moby/moby/commit/0f8119a87dc301e9543c45c416d6b4545da1fc46
However `service docker restart` sends `TERM` signal rather `HUP`, which means `docker` doesn't reload but being stopped and re-executed again

Nevertheless, looking at the logs, it seems like the flags you specified are set.
Unfortunately, I think the container is not reachable because it is restored before the network which causing this problem.

I will update you when I have new news.
Thanks.

**Comment by SamSaffron** [comment]
@ripcurld0  any news here?

**Comment by selansen** [comment]
I fixed the issue. Merging my PR into upstream on the way.
Thanks.

**Comment by ripcurld0** [comment]
thanks @selansen for fixing the problem.
