### ISSUE TITLE
How to use systemd in a container?

### ISSUE THREAD

**Issue by KeithTt** [moby/moby#35756]
OS version: Debian Stretch
Docker version: 17.06.2-ce

Is it possible?

Mount `/sys/fs/cgroup` to the container?

**Comment by cpuguy83** [comment]
This ought to help.
http://bfy.tw/FVHE

Closing this as it is not an issue. In the future, please help keep our issue tracker clean by only posting issues here.
You can use forums.docker.com, #docker on IRC, or the docker community slack to get answers to questions.

Thanks!
