### ISSUE TITLE
Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden

### ISSUE THREAD

**Issue by Salman888** [moby/moby#35760]
RUN apt-get update && apt-get install -yqq mysql-server-5.5 libmysqlclient18 libmysqlclient-dev
 ---> Running in f96a3d8a7d38
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:3 http://ppa.launchpad.net trusty InRelease [20.8 kB]
Ign http://ppa.launchpad.net trusty InRelease
Ign http://ppa.launchpad.net trusty InRelease
Get:4 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:5 http://ppa.launchpad.net trusty Release.gpg [316 B]
Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]
Ign http://ppa.launchpad.net trusty Release.gpg
Get:7 http://ppa.launchpad.net trusty Release [15.1 kB]
Ign http://ppa.launchpad.net trusty Release
Get:8 http://archive.ubuntu.com trusty-updates/main Sources [409 kB]
Err http://ppa.launchpad.net trusty/main amd64 Packages

Err http://ppa.launchpad.net trusty/main amd64 Packages

Err http://ppa.launchpad.net trusty/main amd64 Packages

Get:9 http://archive.ubuntu.com trusty-updates/restricted Sources [6322 B]
Err http://ppa.launchpad.net trusty/main amd64 Packages

Get:10 http://archive.ubuntu.com trusty-updates/universe Sources [195 kB]
Err http://ppa.launchpad.net trusty/main amd64 Packages
  403  Forbidden
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1043 kB]
Get:12 http://ppa.launchpad.net trusty/main amd64 Packages [7796 B]
Get:13 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [17.2 kB]
Get:14 http://ppa.launchpad.net trusty/main amd64 Packages [756 B]
Get:15 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [436 kB]
Get:16 http://archive.ubuntu.com trusty-security/main Sources [147 kB]
Get:17 http://archive.ubuntu.com trusty-security/restricted Sources [4931 B]
Get:18 http://archive.ubuntu.com trusty-security/universe Sources [67.2 kB]
Get:19 http://archive.ubuntu.com trusty-security/multiverse Sources [3195 B]
Get:20 http://archive.ubuntu.com trusty-security/main amd64 Packages [696 kB]
Get:21 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.1 kB]
Get:22 http://archive.ubuntu.com trusty-security/universe amd64 Packages [198 kB]
Get:23 http://archive.ubuntu.com trusty-security/multiverse amd64 Packages [4795 B]
Get:24 http://archive.ubuntu.com trusty/main Sources [1064 kB]
Get:25 https://oss-binaries.phusionpassenger.com trusty InRelease
Ign https://oss-binaries.phusionpassenger.com trusty InRelease
Get:26 http://archive.ubuntu.com trusty/restricted Sources [5433 B]
Get:27 http://archive.ubuntu.com trusty/universe Sources [6399 kB]
Get:28 https://oss-binaries.phusionpassenger.com trusty Release
Get:29 https://oss-binaries.phusionpassenger.com trusty/main amd64 Packages
Get:30 http://archive.ubuntu.com trusty/main amd64 Packages [1350 kB]
Get:31 http://archive.ubuntu.com trusty/restricted amd64 Packages [13.0 kB]
Get:32 http://archive.ubuntu.com trusty/universe amd64 Packages [5859 kB]
Fetched 18.3 MB in 5s (3208 kB/s)
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden

E: Some index files failed to download. They have been ignored, or old ones used instead.
2017/12/11 10:15:07 The command [/bin/sh -c apt-get update && apt-get install -yqq mysql-server-5.5 libmysqlclient18 libmysqlclient-dev] returned a non-zero code: 100

When I am trying to build a new image using "sudo docker build --tag tagname --no-cache ." then this error occured.

Docker Version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a

Docker info
Containers: 9
Images: 154
Storage Driver: devicemapper
 Pool Name: docker-253:1-131270-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 6690.1 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 10.8 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.13.0-35-generic
WARNING: No swap limit support

**Comment by Salman888** [comment]
And the same error occured in 
Docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

Docker info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.697GiB
Name: ubuntu-desktop
ID: MASU:2SLL:NVKJ:WTYQ:UUTP:QX7X:IUTJ:QYUO:5IWG:NAPC:YOST:UULO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by ripcurld0** [comment]
It looks like a problem with the launchpad.
Trying to visit http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages myself gave the "Forbiden" error.

**Comment by cpuguy83** [comment]
This is not a docker issue. Closing.
Feel free to discuss here, though. 👼

**Comment by Salman888** [comment]
@cpuguy83 this error occured during docker image building and when I tried apt-get update in system then  its working fine.

**Comment by ripcurld0** [comment]
@Salman888 could be because you are using a different `etc/apt/apt.conf` file.

**Comment by Salman888** [comment]
@cpuguy83 can you please suggest me correct etc/apt/apt.conf file

**Comment by cpuguy83** [comment]
@Salman888 there's no much I can do here other than suggest some troubleshooting steps.
If you are getting 403 Forbidden that means you are hitting some endpoint and it's giving you that response. At this point it is out of Docker's hands.

Are you going through some proxy that you need to authenticate with?
Is your DNS configured correctly?
Does it work if you run it in a container with `--net=host`?
