### ISSUE TITLE
DNS queries to private DNS servers times out in Docker but not on host

### ISSUE THREAD

**Issue by tomelliff** [moby/moby#35764]
**Description**
We have a VPN into an AWS VPC that from the office is managed by a router that also handles DHCP. From our office we are able to resolve things in our Route53 private zone by using `docker run --dns 172.31.0.2 tutum/dnsutils dig foo.internal`. We've also set this as a default in `/etc/docker/daemon.json` and it works nicely for everything we need.

However, from out of the office, our VPN clients are given DHCP settings from the VPN tunnel (the VPN endpoint pushes these out by setting `config name-server|address|netmask` in the iked.conf). These clients can then resolve `foo.internal` directly with dig showing that the DHCP DNS server is being used but running `docker run --dns 172.31.0.2 tutum/dnsutils dig foo.internal` from these machines gives us:
```
$ docker run --dns 172.31.0.2 tutum/dnsutils dig foo.internal

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> foo.internal
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I'm not sure why the host would be able to resolve things using the specified DNS servers but our Docker containers simply timeout when being forced to use the same DNS servers.

I'm not sure if it's related but I noticed that `nmcli device show | grep -i dns` from the working setup (with the VPN and DHCP configured by the router) shows the 172.31.0.2 address as expected but running the same on the non-working setup (with the VPN client getting DHCP configuration directly) shows a 192.168.1.1 address which comes from the wireless access point I was using with that machine.

I've checked and the traffic from both setups is being correctly NATed so that it appears to originate from the VPN instance in the VPC which would otherwise explain the timeouts to the VPC local R53 endpoint (but wouldn't explain why it works outside of Docker). The same thing happens if I point Docker DNS to an instance running dnsmasq that forwards all requests to the VPC local R53 endpoint (which then doesn't require traffic to be NATed).

**Steps to reproduce the issue:**
I have no idea how to minimally reproduce this issue short of asking people to create a VPN into an AWS VPC and set the DHCP options to the VPC local Route53 endpoint (and also NAT traffic behind the VPN endpoint so you have access to the VPC local endpoint).

If you can do that then run (assuming your VPC begins at 172.31.0.0, otherwise update to the .2 address of the range provided for the VPC):
```
docker run --dns 172.31.0.2 tutum/dnsutils dig www.google.com
```

**Describe the results you received:**
```
$ docker run --dns 172.31.0.2 tutum/dnsutils dig www.google.com

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> foo.internal
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Describe the results you expected:**
This is what I get on working setup:
```
$ docker run --dns 172.31.0.2 tutum/dnsutils dig www.google.com

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51211
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		22	IN	A	108.177.98.147
www.google.com.		22	IN	A	108.177.98.99
www.google.com.		22	IN	A	108.177.98.103
www.google.com.		22	IN	A	108.177.98.104
www.google.com.		22	IN	A	108.177.98.105
www.google.com.		22	IN	A	108.177.98.106

;; Query time: 17 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Mon Dec 11 15:27:55 UTC 2017
;; MSG SIZE  rcvd: 139
```

**Output of `docker version`:**
Running same version of Docker on both machines:
```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**
working setup:
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 351
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 757
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38GiB
Name: tom
ID: JMTH:6BUV:52BI:WAAO:2OUX:UKML:AI7L:2J36:OWDD:JZVQ:WLJW:NR3H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
non-working setup:
```
Containers: 14
Running: 0
Paused: 0
Stopped: 14
Images: 9
Server Version: 17.09.0-ce
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 59
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
apparmor
seccomp
 Profile: default
Kernel Version: 4.10.0-37-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38GiB
Name: workshop2
ID: CJWQ:Y7QG:VFOU:HOSW:6EKN:JEUE:MLNT:KID7:D63R:DKJL:PGFY:7Q4P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
