### ISSUE TITLE
introduce header to document docker.raw-stream is multiplexed or raw tty

### ISSUE THREAD

**Issue by ndeloof** [moby/moby#35761]
**Description**

Docker attach API do use `application/vnd.docker.raw-stream` content type, which has two implementations:
- multiplexed stdout/stderr streams
- raw tty output

from API response there's no way (afaict) to determine which one is used
I suggest a header is introduced to document which mode is being used

**Steps to reproduce the issue:**
1. ask a friend to create a container, setting tty= to a random value kept secret
2. invoke containers/{id}/attach
3. try to guess the raw.stream format in use

**Describe the results you received:**

have to try parsing a multiplexed frame, then admit I was wrong.

**Describe the results you expected:**

simple way to determine the parsing logic to use

**Comment by cpuguy83** [comment]
Inspect first then attach?
Really I guess this should have been designed with different content types...

**Comment by ndeloof** [comment]
running inspect is indeed the sole option I have found os far, so will rely on this in the meantime, but sounds to me this could be addressed to avoid this in a future release.
