### ISSUE TITLE
Feature: Custom source value for Splunk logger

### ISSUE THREAD

**Issue by fritzdj** [moby/moby#35776]
In our environment, we want to set the source value as the tag value using the "raw" format. i.e. Take this scenario:
source= http:LMB_app_Docker_AWS_prod
tag = compassionate_wing/77d485fa6ee70223229a4c71b8540134b210ddc678557272f18909a0593f121e
line = hello splunk

We want the entry to look like this:
![image](https://user-images.githubusercontent.com/6536947/33892769-a8689ffa-df27-11e7-9954-489125decff3.png)

We think the best approach would be to modify the Splunk logger to be able to pass in a template for the source value (similar to tag). We would then make sure there was nothing set for the prefix. Thoughts?

NOTE: We did create a custom plugin to try this out, but are running into issues forcing the daemon to use this due to the following issue: https://github.com/moby/moby/issues/35553

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan

**Comment by fritzdj** [comment]
@anusha-ragunathan does this make sense? Any alternate recommendation? We are attempting to make this change on our side first and test this out.

**Comment by anusha-ragunathan** [comment]
Overriding the source of a log message is not something we want in moby by default. 

Also, I dont understand your usecase enough to know why tags wont suffice. Tags (and env) are meant to solve this exact problem.

**Comment by fritzdj** [comment]
Closing this for now. We really need to be able to create our own logging plugin. This is blocked by #35553.
