### ISSUE TITLE
Raise a warning when using an env file containing variable names with unallowed characters

### ISSUE THREAD

**Issue by CodingSpiderFox** [moby/moby#35787]
I created a .env file with the following contents

```
variable=value
variable2=value2
user-a-name=test
```

Obviously, the "user-a-name" variable name is not valid because it contains a dash/hypen/whatever you call it.

Then I ran `docker run --env-file myfile.env my-container-image`. The user-a-name of course could not be set because the variable name is invalid.

I want docker to output a warning on STDOUT/STDERR (whatever is the suitable stream) when I have chosen an invalid variable name in my .env file

**Comment by thaJeztah** [comment]
Thanks for suggesting! 

We actually added validation for this at some point (https://github.com/moby/moby/pull/13694), but the answer is not that simple; even though `user-a-name` may not be "valid", the shell may actually accept it, and just set it:

```bash
$ docker run --env-file myfile.env busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=e4824496f319
variable=value
variable2=value2
user-a-name=test
HOME=/root
```

Some software actually _relies_ on invalid environment variables (see https://github.com/moby/moby/issues/16585), and the [IEEE Std 1003.1 standard mentions](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html);

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. **Other characters may be permitted by an implementation; applications shall tolerate the presence of such names**. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications.

So for that reason, we removed validation, and made it the responsibility of the container to decide how to handle environment variables.

I'm closing this issue for the reason above, but feel free to continue the conversation 👍
