### ISSUE TITLE
CentOS 7.4 & Docker 17.09.1-ce with User Namespaces fails with nsenter: failed to unshare namespaces: Operation not permitted

### ISSUE THREAD

**Issue by stefanlasiewski** [moby/moby#35806]
**Description**

I installed a new CentOS 7.4 test system using Vagrant so that I could test User Namespaces. I believe I have enabled everything correctly. However, Docker fails to start any container with the error "nsenter: failed to unshare namespaces: Operation not permitted". See the full error below.

This worked a couple weeks ago with CentOS 7.3, repeatedly. It doesn't work now, with CentOS 7.4.

This looks similar to #34011 , but that issue was closed in July and was caused by a misconfiguration of the kernel. My kernel should be configured correctly and is different from that issue, so I'm opening a new ticket.

**Steps to reproduce the issue:**

1. Install CentOS 7.4.1708
2. Install Docker 17.09.1-ce per https://docs.docker.com/engine/installation/linux/docker-ce/centos/
3. Activate User Namespaces, and configure Docker to use them:

* Add the user_namespace.enable=1 option to the kernel (vmlinuz*) command line.

```
    grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
```

* Add a value to the user.max_user_namespaces kernel tuneable so it is set permanently as follows:

```
    echo "user.max_user_namespaces=15076" >> /etc/sysctl.conf
```

* Assign users and groups to be mapped by user namespaces. 

```
    echo dockremap:808080:1000 >> /etc/subuid
    echo dockremap:808080:1000 >> /etc/subgid
```

* Enable namespaces for Docker by adding this to /etc/docker/daemon.json:

```
{
	"userns-remap": "default"
}
```

* Reboot the system and verify

**Alternately, if you run Vagrant & VirtualBox, you can quickly replicate this way**

```
git clone https://github.com/stefanlasiewski/vagrant-centos-docker.git 
cd vagrant-centos-docker/
vagrant up
vagrant ssh
[vagrant@localhost ~]$ sudo bash /vagrant/enable-user-namespaces.sh
[vagrant@localhost ~]$ reboot

vagrant ssh
[vagrant@localhost ~]$ sudo docker run hello-world
```

**Describe the results you received:**

Docker repeatedly fails for any container with errors like "nsenter: failed to unshare namespaces: Operation not permitted".

```
[vagrant@localhost ~]$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Pull complete 
Digest: sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
Status: Downloaded newer image for hello-world:latest
nsenter: failed to unshare namespaces: Operation not permitted
container_linux.go:265: starting container process caused "process_linux.go:270: running exec setns process for init caused \"exit status 34\""
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:270: running exec setns process for init caused \"exit status 34\"".
[vagrant@localhost ~]$
```

**Describe the results you expected:**

I expect all containers to start, and run with the Subordinate UID/GID from /etc/subuid & /etc/subgid

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4MiB
Name: localhost.localdomain
ID: CHAK:UIKY:GYUX:DPJX:QRSF:BCCT:OKF5:BM5U:MTN6:2YFX:YP5J:HY4E
Docker Root Dir: /var/lib/docker/808080.808080
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox VM installed using Vagrant.

```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
[root@localhost ~]#
```

The Kernel was started with Namespaces enabled:

```
[root@localhost ~]# cat /proc/cmdline |grep --color  user_namespace.enable
BOOT_IMAGE=/vmlinuz-3.10.0-693.5.2.el7.x86_64 root=/dev/mapper/VolGroup00-LogVol00 ro no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 crashkernel=auto rd.lvm.lv=VolGroup00/LogVol00 rd.lvm.lv=VolGroup00/LogVol01 rhgb quiet user_namespace.enable=1
[root@localhost ~]#
```

Docker appears to be configured to use User Namespaces:

```
[vagrant@localhost ~]$ curl --silent -O https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
[vagrant@localhost ~]$ bash ./check-config.sh | grep CONFIG_USER_NS
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
- CONFIG_USER_NS: enabled
[vagrant@localhost ~]$

[root@localhost ~]# sudo docker info |grep --after-context=3 "Security Options"
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Security Options:
 seccomp
  Profile: default
 userns
[root@localhost ~]#
```

Contents of /etc/docker/daemon.json:

```
{
	"userns-remap": "default"
}
```

**Comment by cpuguy83** [comment]
user namespaces are not supported on CentOS and RHEL when used in conjunction with a mount namespace, unfortunately.

**Comment by stefanlasiewski** [comment]
@cpuguy83 : Could you elaborate on that some more? The [RHEL 7.4 release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.4_release_notes/index#BZ1340238) say "Full support for user name spaces". But you're saying that this full support still doesn't work well?

I've read that historically, user namespaces & mount namespaces have been historically problematic. Just trying to wrap my head around the current state of CentOS 7.4.

**Comment by stefanlasiewski** [comment]
Well, here's one answer to my question, from [Getting Started with Containers: 1.7.4. User namespaces options](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/get_started_with_docker_formatted_container_images):

> Note
> 
> The user namespaces kernel feature is fully supported (generally available) in RHEL 7.4. However, the specific implementation of user namespaces related to the docker service is identified as a technology preview while Red Hat locks down a few security issues associated with non-root user mounts.

**Comment by stefanlasiewski** [comment]
Ah! I found what happened.

I determined that simply using 

The correct flag to pass to the Kernel, on CentOS 7.4, is `namespace.unpriv_enable=1` not `user_namespace.enable=1`. The latter is mentioned in various blogs, but [Getting Started with Containers: 1.7.4. User namespaces options](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/get_started_with_docker_formatted_container_images) says `namespace.unpriv_enable=1`, and that works for me:

```
[root@localhost ~]# grubby --args="namespace.unpriv_enable=1" --update-kernel="$(grubby --default-kernel)"
[root@localhost ~]# reboot
```

Re connect to the node, and re-verify:

```
[root@localhost ~]# cat /proc/cmdline |grep --color  namespace
BOOT_IMAGE=/vmlinuz-3.10.0-693.5.2.el7.x86_64 root=/dev/mapper/VolGroup00-LogVol00 ro no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 crashkernel=auto rd.lvm.lv=VolGroup00/LogVol00 rd.lvm.lv=VolGroup00/LogVol01 rhgb quiet namespace.unpriv_enable=1
[root@localhost ~]#
[root@localhost ~]# bash ./check-config.sh | grep CONFIG_USER_NS
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
- CONFIG_USER_NS: enabled
[root@localhost ~]# sudo docker info |grep --after-context=3 "Security Options"
Security Options:
 seccomp
  Profile: default
 userns
[root@localhost ~]#
```

And finally, *test*:

```
[root@localhost ~]# docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

[root@localhost ~]#
```

**Comment by stefanlasiewski** [comment]
However, according to https://discuss.linuxcontainers.org/t/centos-7-kernel-514-693-cannot-start-any-nodes-after-update/641/16 both `user_namespace.enable=1 namespace.unpriv_enable=1` may be needed.

**Comment by cpuguy83** [comment]
Yep, see https://github.com/moby/moby/issues/35336

Thanks!

**Comment by odg0318** [comment]
@stefanlasiewski  Thanks! You reduce my cost.

**Comment by odg0318** [comment]
@stefanlasiewski Thanks a lot. You reduce my costs.

**Comment by zizu1985** [comment]
In Centos 7.5 & 7.4 I had to additionally set kernel parameter user.max_user_namespaces to value above 0.
