### ISSUE TITLE
DNS query for unexisting SRV record times out

### ISSUE THREAD

**Issue by lodrantl** [moby/moby#35801]
**Description**

If you specifically request a unexisting SRV record from internal docker DNS server, it will take 20s to timeout.

**Steps to reproduce the issue:**
1.  Create a custom docker network `docker network create dnstest`
2.  Start a container on a custom docker network `docker run -it --network=dnstest azukiapp/dig sh `
3.  Dig for a SRV record without domain `dig SRV unexistent`

**Describe the results you received:**
The command takes 20 s to timeout and show the following message:
> ; <<>> DiG 9.10.3-P3 <<>> SRV unexistent
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached

**Describe the results you expected:**
Expected something like the result of  `dig SRV unexistent.com`, which resolves instantly:

> ; <<>> DiG 9.10.3-P3 <<>> SRV unexistent.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56968
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 65494
> ;; QUESTION SECTION:
> ;unexistent.com.			IN	SRV
> 
> ;; Query time: 47 msec
> ;; SERVER: 127.0.0.11#53(127.0.0.11)
> ;; WHEN: Thu Dec 14 11:17:30 UTC 2017
> ;; MSG SIZE  rcvd: 42

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

> Client:
>  Version:      17.09.1-ce
>  API version:  1.32
>  Go version:   go1.8.3
>  Git commit:   19e2cf6
>  Built:        Thu Dec  7 22:24:28 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.09.1-ce
>  API version:  1.32 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   19e2cf6
>  Built:        Thu Dec  7 22:23:07 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

**Output of `docker info`:**

> Containers: 12
>  Running: 0
>  Paused: 0
>  Stopped: 12
> Images: 123
> Server Version: 17.09.1-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
> runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.13.0-17-generic
> Operating System: Ubuntu 17.10
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.644GiB
> Name: zlatko
> ID: DWRT:2AUS:LZUI:WFXF:3V7J:NDJD:CORK:2LQS:FVOM:CHIW:H4C2:GZT4
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support
>

**Comment by thaJeztah** [comment]
ping @ddebroy

**Comment by ddebroy** [comment]
I tried the repro steps above in `17.12.0-ce`: spun up a fresh ubuntu container on a new network. When trying `dig SRV unexistent` it returns with NXDOMAIN in less than a second:

```
root@f81a7d431439:/# time dig SRV unexistent

; <<>> DiG 9.10.3-P4-Ubuntu <<>> SRV unexistent
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56532
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;unexistent.			IN	SRV

;; AUTHORITY SECTION:
.			60	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2018011001 1800 900 604800 86400

;; Query time: 80 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Thu Jan 11 00:23:54 UTC 2018
;; MSG SIZE  rcvd: 114


real	0m0.089s
user	0m0.004s
sys	0m0.004s
```

@lodrantl can you check if you are getting a consistent repro in 17.12.0 ce?

**Comment by Umkus** [comment]
Same issue here on `17.12.0-ce-mac45 (21669)`

```
docker network create dnstest && docker run -it --network=dnstest azukiapp/dig time dig SRV blah
c16a55afe78d8025c366e56f479a078bf959bbe361653aecb6b7f24188aa8849

; <<>> DiG 9.10.3-P3 <<>> SRV blah
;; global options: +cmd
;; connection timed out; no servers could be reached
Command exited with non-zero status 9
real	0m 15.01s
user	0m 0.00s
sys	0m 0.00s
```
Also reproducing with `library/ubuntu:latest`.
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```
macOS, **corporate network**.
Using docker-compose for the affected use case taking 20 seconds.

**Comment by thaJeztah** [comment]
@lodrantl if you put the daemon in debug mode, what do the logs show?

To enable debug mode; create a `/etc/docker/daemon.json` file (if it doesn't exist yet), and add the `"debug":true` option. The file needs to be valid JSON, so if you didn't have other options set yet, it should look something like this:

```json
{"debug":true}
```

After that, reload the daemon configuration;

```bash
systemctl reload docker
```

After attempting your reproduction case, you should see log-entries like below (and those may give an indication where the delay is);

```
Jan 26 17:59:11 ubuntu-s-1vcpu-1gb-ams3-01 dockerd[5386]: time="2018-01-26T17:59:11.940560316Z" level=debug msg="Service name To resolve: unexistent."
Jan 26 17:59:11 ubuntu-s-1vcpu-1gb-ams3-01 dockerd[5386]: time="2018-01-26T17:59:11.941885344Z" level=debug msg="[resolver] query unexistent. (SRV) from 172.19.0.2:48310, forwarding to udp:67.207.67.3"
Jan 26 17:59:11 ubuntu-s-1vcpu-1gb-ams3-01 dockerd[5386]: time="2018-01-26T17:59:11.944950890Z" level=debug msg="[resolver] external DNS udp:67.207.67.3 did not return any SRV records for \"unexistent.\""
```

**Comment by lodrantl** [comment]
This is the relevant log output:
`jan 28 16:07:00 dock2 dockerd[19435]: time="2018-01-28T16:07:00.806482961+01:00" level=debug msg="Service name To resolve: unexistent."
jan 28 16:07:00 dock2 dockerd[19435]: time="2018-01-28T16:07:00.806589911+01:00" level=debug msg="[resolver] query unexistent. (SRV) from 127.0.0.1:42476, forwarding to udp:127.0.0.53"
jan 28 16:07:04 dock2 dockerd[19435]: time="2018-01-28T16:07:04.806693709+01:00" level=debug msg="[resolver] read from DNS server failed, read udp 127.0.0.1:42476->127.0.0.53:53: i/o timeout"
`

**Comment by thaJeztah** [comment]
Thanks for testing that; let me go ahead and close this issue, but feel free to continue the conversation
