### ISSUE TITLE
network fails on worker node

### ISSUE THREAD

**Issue by baobeimm** [moby/moby#35804]
We have a swarm cluster with about 60 workers and 3 managers. One worker started to having issues with routing mesh and can't access any other services in the swarm. docker node ls shows the node as active but on the node itself we see errors like

Dec 14 02:43:42 ip-192-168-49-196 dockerd: time="2017-12-14T02:43:42.140813409-05:00" level=error msg="network arrow_cloud_internal remove failed: unknown network arrow_cloud_internal id tq365un1laf40exi4oglmxd2j" module="node/agent" node.id=71yluonbhp2vr2o69ebce2xlf

Dec 14 02:43:42 ip-192-168-49-196 dockerd: time="2017-12-14T02:43:42.140832840-05:00" level=error msg="remove task failed" error="unknown network arrow_cloud_internal id tq365un1laf40exi4oglmxd2j" module="node/agent" node.id=71yluonbhp2vr2o69ebce2xlf task.id=m2az9nzf3gbhhl2yn3sdxpzuf

We tried to restart the docker and force the node to leave swarm and rejoin. Nothing helped. 

**Steps to reproduce the issue:**
docker swarm with docker 17.06.0

**Describe the results you received:**
the particular work has issues with swarm network
Dec 14 02:43:42 ip-192-168-49-196 dockerd: time="2017-12-14T02:43:42.140813409-05:00" level=error msg="network arrow_cloud_internal remove failed: unknown network arrow_cloud_internal id tq365un1laf40exi4oglmxd2j" module="node/agent" node.id=71yluonbhp2vr2o69ebce2xlf

Dec 14 02:43:42 ip-192-168-49-196 dockerd: time="2017-12-14T02:43:42.140832840-05:00" level=error msg="remove task failed" error="unknown network arrow_cloud_internal id tq365un1laf40exi4oglmxd2j" module="node/agent" node.id=71yluonbhp2vr2o69ebce2xlf task.id=m2az9nzf3gbhhl2yn3sdxpzuf

**Describe the results you expected:**
The worker should not have network issue

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happened on one worker and we had to terminate it

**Output of `docker version`:**

```
Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 25weqpwlix4g11uxyw44441vn
 Is Manager: false
 Node Address: 192.168.2.117
 Manager Addresses:
  192.168.121.244:2377
  192.168.68.49:2377
  192.168.76.39:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.517GiB
Name: service_others-ip-192-168-2-117
ID: LY5Q:LYRW:ZLMT:O24A:5M2R:VXVI:UUR5:NP56:R6CP:LFHH:HU5O:KHYY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 arrow_cloud_haproxy=true
 HOST_IP=192.168.2.117
 SSH_HOST_IP=192.168.2.117
 INSTANCE_ID=i-0e3475e1349ecb3f7
Experimental: false
Insecure Registries:
 registry.service.docker.swarm:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
