### ISSUE TITLE
vfs graphdriver fails to initialize due to projectquota

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#35815]
**Description**

A failure to setup the project quota can make the vfs driver fail to initialize and abort daemon startup.

**Steps to reproduce the issue:**
1. Start daemon with vfs driver backed by osxfs

**Describe the results you received:**

> Error starting daemon: error initializing graphdriver: Failed to mknod /go/src/github.com/docker/docker/bundles/test-integration/d6bcf6de610e9/root/vfs/backingFsBlockDev: function not implemented

**Describe the results you expected:**

Daemon should start even though the project quota setup failed

**Comment by thaJeztah** [comment]
ping @sargun

**Comment by sargun** [comment]
I'll push a fix for this ~Next Week. Away from computer this week.

**Comment by thaJeztah** [comment]
Thanks in advance! If someone else starts working on it before that, Ill try to ping you on that PR :smile:
