### ISSUE TITLE
can not use pip to install with ">="

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#35813]
I want to use `pip` to install some pkgs in Dockerfile:
```
RUN pip3.6 install pyspark>=2.2.0 psycopg2>=2.7.3.2 pandas>=0.21.1
```
But i found it woukd generate below file under root dir:
```
bash-4.2# ls
=0.21.1  =2.2.0  =2.7.3.2  bin	boot  dev  etc	home  lib  lib64  media  mnt  opt  proc  root  run  sbin  skydata  srv	sys  tmp  usr  var
```

It does not work as expected.

Does it do not support or i use wrong usage?

**Comment by AkihiroSuda** [comment]
Not specific to Docker, you need to escape or quote  > symbol
