### ISSUE TITLE
Cannot pull image when there are live containers

### ISSUE THREAD

**Issue by tg123** [moby/moby#35836]
**Description**

Cannot `pull` image when there is live containers

docker pull `myimage` failed 

**Steps to reproduce the issue:**
1. docker run -d myimage:latest (base on 16299.64)
2. update myimage:latest in registry (base on 16299.125)
3. docker pull myimage

**Describe the results you received:**

```
20b79afe7b94: Download complete
e526cb6361c6: Download complete
76bc730fbf7a: Download complete
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\e324ea40f5379474e4e5615f137da6179d67d32602a5820884c26999e45fbedd\UtilityVM\Files\Windows\WinSxS\amd64_microsoft-windows-bcrypt-dll_31bf3856ad364e35_10.0.16299.15_none_1178bf5f608a1bb9\bcrypt.dll: Access is denied.
```

**Describe the results you expected:**

update image success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.06.2-ee-5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:51:36 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-5
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:54:07 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16GiB
Name: -------
ID: 36CP:YUYX:V53Q:FRDZ:QY7X:R35D:W44T:L2SC:HJVS:WD3H:B6LW:G7D5
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This is an issue with Docker EE, which is usually not handled in this issue tracker; primary support for Docker EE on Windows Server is handled by Microsoft, but can be escalated to Docker support.

I see you work for Microsoft; could you open an issue internally, or if you already did so, open one through Docker Support?

I'll close the issue here, but feel free to continue the conversation
