### ISSUE TITLE
Health check no longer uses the container's working directory

### ISSUE THREAD

**Issue by MarkusMattinen** [moby/moby#35843]
**Description**

Previously if a working directory was defined for a container, health checks would also use that as their working directory. This is no longer the case with v17.12.0-ce-rc3. Health checks now ignore the working directory configuration and just use `/` as their working directory.

**Steps to reproduce the issue:**
1. `docker run -d -w /tmp --name health_check_test --health-cmd pwd --health-interval 5s busybox tail -f /dev/null`
2. `sleep 6 && docker inspect --format '{{ (index (.State.Health.Log) 0).Output }}' health_check_test`

The result is also the same if the working directory and health check are defined at the image level instead of at the container level.

**Describe the results you received:**
Health check uses working directory `/`.

**Describe the results you expected:**
Health check should use working directory `/tmp` as defined in the container configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**
Health check uses the correct working directory at least in v17.11.0-ce.

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce-rc3
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	80c8033
 Built:	Thu Dec 14 00:39:46 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce-rc3
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	80c8033
  Built:	Thu Dec 14 00:45:43 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 637
Server Version: 17.12.0-ce-rc3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: RQDH:HHCP:TGAI:HZ2P:ATR2:KY3M:X3MS:52Y6:FKRB:LBBU:GARN:O4ON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 70
 System Time: 2017-12-20T11:35:55.352479601Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker on Mac

**Comment by thaJeztah** [comment]
Suspecting this may be related to https://github.com/moby/moby/pull/35661

ping @ndeloof PTAL

**Comment by ndeloof** [comment]
ouch
