### ISSUE TITLE
Swarm starts with syslog driver but no messages show up in the syslog service and no logging errors are reported by the docker daemon

### ISSUE THREAD

**Issue by chairbender** [moby/moby#35855]
**Description**
Here's a simple compose file to demonstrate the issue:
````
version: "3.3"

services:
  syslog:
    image: bobrik/syslog-ng
    ports:
      - "514:514"
  webservice:
    image: tomcat:8.5.13-jre8-alpine
    ports:
          - "8080:8080"
    depends_on:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:514
        syslog-facility: daemon
        tag: "{{.Name}}/{{.ID}}"
````

How this setup is supposed to work is that the syslog container starts first and exposes a TCP syslog service on port 514. Any messages that reach this port will show up inside the syslog container under /var/log/syslog-ng/. The webservice container is configured to use the syslog logging driver to send syslog messages to this service.

**Steps to reproduce the issue:**
1. Start the above compose file using `docker-compose up -d`
2. `docker exec -it <syslog_container> sh`
3. `ls /var/log/syslog-ng`. Verify that there are folders underneath this directory. This indicates that the logs are being received from the webservice container. If you drill down, you can see the actual messages.
4. Now try the same thing, but using swarm: `docker stack deploy <file> test`
5. Use `docker stack ps` to verify that the containers start and don't complain about failing to connect to the syslog service.
6. Now sh into the syslog container and check the log directory (as in step 2 and 3). It will be empty, indicating that _no logs were received by the service_, despite the fact that the webservice container generates quite a few log messages on startup.
7. Using Postman or some other method, issue a POST request with a JSON body to localhost:514.
8. Check the log directory again. You should see some stuff under it, indicating that the POST was received.

**Describe the results you received:**
Swarm behavior did not match compose. No logs showed up in /var/log/syslog-ng on startup, indicating that docker's syslog driver did not succeed in delivering the log messages to the syslog container. Furthermore, despite failing to deliver logs to the syslog service, it did not report any errors with log delivery. I don't see any error messages in the Docker daemon indicating a problem.

By manually sending a POST, we verified that there is not anything wrong with the syslog-ng container. The only thing that seems to be wrong here is that log messages are not being sent by the docker daemon using the syslog driver from the webservice container.

**Describe the results you expected:**
Swarm behavior should match compose. We should see messages in /var/log/syslog-ng on startup inside the syslog container. If the syslog driver fails to connect to the syslog service, it should fail to start the webservice container and should report an error. I've confirmed that it actually does this when you point it at a nonexistent syslog service. But for some reason, it doesn't report any error here.

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 245
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: m266ltb2iqxwlicmkrkzie7r7
 Is Manager: true
 ClusterID: tu8qjibypuo83s8zzpxgwwfdd
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.554GiB
Name: moby
ID: AWNV:GZTQ:SCEU:5JGV:R4ED:PWJD:S5NY:T6TI:HEE2:3R2L:WDOF:DSO5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 181
 System Time: 2017-12-21T02:00:44.283533Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've reproduced this issue on Docker for AWS as well as Docker for Windows.

**Comment by cpuguy83** [comment]
Note that swarm does not support "depends_on".
Are you sure that the tomcat service is actually running and running on the same node?

**Comment by chairbender** [comment]
@cpuguy83 re: depends_on - good to know. Perhaps I should handle this in a separate swarm.

re: running on the same node - yes. If you just run that compose file yourself on your local machine (using swarm with only one node on your local), you can reproduce the issue.

Also, swarm uses ingress mesh routing, correct? So if I have the docker daemon sending logs to "localhost:514", that means it's going to send the request to the correct container regardless of where it's running. "localhost" in the context of the docker logging driver, as far as I understand it, should refer to the node itself rather than any individual container. So the request will hit the mesh and will get sent to the appropriate node. Did I misunderstand something (I'm going off what's written here: https://docs.docker.com/engine/swarm/ingress/)?

**Comment by cpuguy83** [comment]
I'm not sure with the usage of localhost there.

**Comment by chairbender** [comment]
What is it going to take to get progress on this? I provided a process to very easily and quickly reproduce this.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
