### ISSUE TITLE
Unable to run containers with LCOW on Windows 10 17063

### ISSUE THREAD

**Issue by AaronFriel** [moby/moby#35854]
**Description**

Docker run fails on Windows 10 17063 with an error like the following:

```> docker run -it --rm hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Extracting [==================================================>]     985B/985B
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: failed to start service utility VM (applydiff 8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba): container 8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba_svm encountered an error during CreateContainer: failure in a Windows system call: Not enough memory resources are available to complete this operation. (0xe) extra info: {"SystemType":"container","Name":"8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true,"MappedVirtualDisks":[{"HostPath":"C:\\ProgramData\\Docker\\lcow\\lcow\\scratch\\8b4eeacde0dc4072a5918229fbb1f72220a52e3b5467d2231850e18e841162ba.vhdx","ContainerPath":"/tmp/scratch","CreateInUtilityVM":true,"AttachOnly":false}]}.
```

I have 30+ GB of free memory, so I suspect this error is incorrect.

**Steps to reproduce the issue:**
1. Install Windows 10 insider build 17063
2. ???
3. `docker run -it --rm hello-world`

**Describe the results you received:**

An error containing the string "failure in a Windows system call: Not enough memory resources are available to complete this operation."

**Describe the results you expected:**

No error.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have the following optional features installed which may impact the bug:

* Containers
* Hyper-V
* Windows Defender Application Guard

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce-rc3
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    80c8033
 Built: Thu Dec 14 00:39:41 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc3
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   80c8033
  Built:        Thu Dec 14 00:49:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.12.0-ce-rc3
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17063 (17063.1000.amd64fre.rs_prerelease.171213-1610)
Operating System: Windows 10 Enterprise Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 47.89GiB
Name: Ziggurat
ID: TK72:ZTYN:PHJI:GSHZ:KAUW:LJKJ:VSBI:E7JO:WT33:YIKJ:VCQL:XMXA
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 28
 System Time: 2017-12-20T17:50:44.268761-06:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: Windows 10 Enterprise
CPU: Core i7-6700k (no overclock)
Memory: 48GB

**Comment by friism** [comment]
cc @jhowardmsft @patricklang

**Comment by t3mulligan** [comment]
Windows 10 16299.125 by hanging on _extraction_ like below:
`PS C:\Windows\system32> docker run -it --rm hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Extracting [==================================================>]     985B/985B
`

Nearly identical issue.

**Docker Info**
`Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce-rc3
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro N
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 31.93GiB
Name: DESKTOP-PB8BSJT
ID: FYMN:A56X:GVQ2:SYPR:5DP5:WSOF:BYZC:JYAZ:7CZE:TEP5:2L6E:SNTU
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2017-12-20T22:01:22.8453628-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Docker Version**
`Client:
 Version:       17.12.0-ce-rc3
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    80c8033
 Built: Thu Dec 14 00:39:41 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc3
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   80c8033
  Built:        Thu Dec 14 00:49:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
`
**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: Windows 10 Pro N
CPU: Ryzen 1700x
Memory: 32GB

A diagnostic was uploaded with id: 8266360E-AA7F-4B89-BCBC-F7B31750D887/2017-12-20_22-00-25

**Comment by jonstelly** [comment]
Getting the same trying to pull `selenium/standalone-chrome`.  It downloads all the layers, gets stuck extracting the first layer (at 47.76MB/47.76MB) for a few minutes, then fails with:

```
failed to register layer: failed to start service utility VM (applydiff aff5253bacb2040f9e374be7f22c199d7b531a10e5c3bfff490aeee4ab325b5b):
  container aff5253bacb2040f9e374be7f22c199d7b531a10e5c3bfff490aeee4ab325b5b_svm encountered an error during CreateContainer: failure in a Windows system call: Not enough memory resources are available to complete this operation. (0xe)
  extra info:
 {"SystemType":"container","Name":"aff5253bacb2040f9e374be7f22c199d7b531a10e5c3bfff490aeee4ab325b5b_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true}
```

Windows 17063

```
Client:
 Version:       17.12.0-ce-rc4
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    6a2c058
 Built: Wed Dec 20 15:53:56 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc4
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   6a2c058
  Built:        Wed Dec 20 16:04:19 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by aaronpowell** [comment]
Can also confirm with my Surface Pro4.

`docker version`

```
C:\_Projects
λ  docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
C:\_Projects
λ  docker pull node:latest
latest: Pulling from library/node
f49cf87b52c1: Extracting [==================================================>]   52.6MB/52.6MB
7b491c575b06: Download complete
b313b08bab3b: Download complete
51d6678c3f0e: Download complete
da59faba155b: Download complete
7f84ea62c1fd: Download complete
1ae6c7e5e8c9: Download complete
7c07b0a5c6a6: Download complete
failed to register layer: failed to start service utility VM (applydiff 499ffa244c8cbde288d3f5899c913533a72558b80a14f5589dd5e479056ee744): container 499ffa244c8cbde288d3f5899c913533a72558b80a14f5589dd5e479056ee744_svm encountered an error during CreateContainer: failure in a Windows system call: Not enough memory resources are available to complete this operation. (0xe) extra info: {"SystemType":"container","Name":"499ffa244c8cbde288d3f5899c913533a72558b80a14f5589dd5e479056ee744_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"bootx64.efi"},"ContainerType":"linux","TerminateOnLastHandleClosed":true,"MappedVirtualDisks":[{"HostPath":"C:\\ProgramData\\Docker\\lcow\\lcow\\scratch\\499ffa244c8cbde288d3f5899c913533a72558b80a14f5589dd5e479056ee744.vhdx","ContainerPath":"/tmp/scratch","CreateInUtilityVM":true,"AttachOnly":false}]}
C:\_Projects
λ  docker version
Client:
 Version:       17.12.0-ce-rc4
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    6a2c058
 Built: Wed Dec 20 15:53:56 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc4
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   6a2c058
  Built:        Wed Dec 20 16:04:19 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

`systeminfo`

```
C:\_Projects
λ  systeminfo

Host Name:                 DESKTOP-TL7V7C6
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.17063 N/A Build 17063
```

**Comment by aaronpowell** [comment]
For the record I can't swap off LCOW, it errors when I uncheck that option in settings ("Unable to create File System image"), but the context menu in the system tray had `Switch to Windows Containers` listed, and I can switch to them.

**Comment by jstacoder** [comment]
I’m stuck with the “not enough memory” error also, can’t get past it

**Comment by jhowardmsft** [comment]
This is a known bug in insider builds. A fix is supposedly being checked into Windows today, but it may take a couple of flights before it is resolved in public builds [Internal ref VSO#15063222]

**Comment by PatrickLang** [comment]
I'm working on getting this added to the known issues list: https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install-insiderplat_pc/known-issues-in-windows-insider-build-17063/f4bc51b1-c540-44d9-b138-fc76b7be860d?auth=1

Workaround is to disable LCOW for now if you hit this.. When we have a fix in a later build we'll get it included in the release notes.

**Comment by PatrickLang** [comment]
Correction - update is live on that link
**Attention developers:** Build 17063 has an issue running Linux containers with Docker Community Edition for Windows (edge) on many machines. The docker pull or docker run commands will fail with an error “Not enough memory resources are available to complete this operation”. We’re working on a fix for an upcoming Windows Insider build but you can work around the problem now with these steps:
1. Be sure “Docker for Windows” is running, then right-click the whale icon in the notification area and choose “settings”.
2. On the General tab, uncheck “Enable Linux containers on Windows”.
3. Next a dialog “Switch to Standard mode (Linux VM / Windows daemon” will pop up. Click OK.
4. Wait for the whale icon to turn white.

**Comment by aaronpowell** [comment]
@PatrickLang I've been unable to disable LCOW, it fails to start the Moby VM ("Unable to create File System Image").

I haven't logged an issue here (it's submitted a number of issues through the Docker error reporting mechanism though) as I thought it's more related to Hyper-V than Docker.

**Comment by PatrickLang** [comment]
If you can't switch modes, probably best to start a thread at https://forums.docker.com/c/docker-for-windows

**Comment by taylorb-microsoft** [comment]
The fix should be in any build 17078 or greater, I am currently installing such a build to personally verify.

**Comment by thaJeztah** [comment]
Thanks! Let me know if this is ready to close

**Comment by SonicGD** [comment]
Build 17083 released with fix:

> We fixed an issue with Linux containers on Windows using Docker Community Edition for Windows (edge) on many machines. The docker pull or docker run commands will fail with an error “Not enough memory resources are available to complete this operation”.

https://blogs.windows.com/windowsexperience/2018/01/24/announcing-windows-10-insider-preview-build-17083-for-pc/#oKVCjBkohh2sLdVS.97

**Comment by aaronpowell** [comment]
Can confirm - Just updated to 17083 and to the Docker CE Edge build and it's working

**Comment by thaJeztah** [comment]
Thanks! I'll close this issue 👍

**Comment by Farham0** [comment]
docker is in basic mode , Double check if doucker is running on advance mode
