### ISSUE TITLE
404 Page Not Found Error - docker stack config reference document

### ISSUE THREAD

**Issue by ajeetraina** [moby/moby#35872]
**Description**

The link for `docker stack config` listed under "Related commands" at the end of page under URL -
 https://github.com/docker/cli/blob/master/docs/reference/commandline/deploy.md returns 404 page error.

**Steps to reproduce the issue:**
1. Go to https://github.com/docker/cli/blob/master/docs/reference/commandline/deploy.md
2. Scroll to the end of the page section "Related Commands"
3. Click on the first link - https://github.com/docker/cli/blob/master/docs/reference/commandline/stack_config.md
4. It shows 404 page not found error

**Describe the results you received:**

The page reports 404 error 

**Describe the results you expected:**

The page should display reference to `docker stack config` command.

**Comment by thaJeztah** [comment]
Hm, looks like a copy/paste error :smile:, I assume this was meant to be referring  to `docker-compose config` (https://docs.docker.com/compose/reference/config/), but the Markdown you linked to is not used directly (the command-line reference is generated from a YAML file), so let me open a PR to just remove it

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/765
