### ISSUE TITLE
Error while restart docker and try to run dockerd on xenila ubuntu server 16.04 LTS

### ISSUE THREAD

**Issue by ithub1994** [moby/moby#35871]
root@i-agjzqo93:/# systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
root@i-agjzqo93:/# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2017-12-25 20:33:23 CST; 9s ago
     Docs: https://docs.docker.com
  Process: 11471 ExecStart=/usr/bin/dockerd -H fd:// tcp://0.0.0.0:2376 (code=exited, status=1/FAIL
 Main PID: 11471 (code=exited, status=1/FAILURE)

Dec 25 20:33:23 i-agjzqo93 dockerd[11471]:   -v, --version                                 Print ve
Dec 25 20:33:23 i-agjzqo93 dockerd[11471]:                                                 and quit
Dec 25 20:33:23 i-agjzqo93 dockerd[11471]: Run 'dockerd COMMAND --help' for more information on a c
Dec 25 20:33:23 i-agjzqo93 systemd[1]: Failed to start Docker Application Container Engine.
Dec 25 20:33:23 i-agjzqo93 systemd[1]: docker.service: Unit entered failed state.
Dec 25 20:33:23 i-agjzqo93 systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 25 20:33:23 i-agjzqo93 systemd[1]: docker.service: Service hold-off time over, scheduling resta
Dec 25 20:33:23 i-agjzqo93 systemd[1]: Stopped Docker Application Container Engine.
Dec 25 20:33:23 i-agjzqo93 systemd[1]: docker.service: Start request repeated too quickly.
Dec 25 20:33:23 i-agjzqo93 systemd[1]: Failed to start Docker Application Container Engine.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
