### ISSUE TITLE
Docker on windows

### ISSUE THREAD

**Issue by sharathj007** [moby/moby#35883]
Description
Unable to switch the docker to Linux container on Windows server 2016, i have installed the windows docker community edition in my one of the Virtual Machine. I am badly struck up with this issue from couple of months, any solution provided here will be very much helpful.
Thank you in advance.

InSpec and Platform Version
Docker version installed:
Docker Community Edition Version 17.09.0-ce-win33(13620)

Replication Case
Steps to reproduce the issue
. Install the Docker Community Edition Version 17.09.0-ce-win33(13620) in windows server 2016 in virtual machine.
. Run the docker
. Right click on the docker and switch to Linux Containers.

Possible Solutions
Windows 2010, which switch to Linux containers is working as expected, the issue seems to be with the virtual machine on Windows server 2016

Stacktrace
Please find the Error while switching to the linux containers
The operation has timed out.
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by ripcurld0** [comment]
@thaJeztah should we move this to https://github.com/docker/for-win?

**Comment by thaJeztah** [comment]
Yes, this would be more suited for the https://github.com/docker/for-win issue tracker, but even there;

>  Install the Docker Community Edition Version 17.09.0-ce-win33(13620) in windows server 2016 in virtual machine.


From the [installation documentation](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install)

> ##  What to know before you install
> 
> If your system does not meet the requirements to run Docker for Windows, you can install
> [Docker Toolbox](/toolbox/overview.md), which uses Oracle Virtual Box instead of
> Hyper-V.
> 
> * **README FIRST for Docker Toolbox and Docker Machine users**: Docker for Windows requires Microsoft Hyper-V to run.  The Docker for Windows installer will enable Hyper-V for you, if needed, and restart your machine. After Hyper-V is
> enabled, VirtualBox will no longer work, but any VirtualBox VM images will
> remain. VirtualBox VMs created with `docker-machine` (including the `default`
> one typically created during Toolbox install) will no longer start. These VMs
> cannot be used side-by-side with Docker for Windows. However, you can still use
> `docker-machine` to manage remote VMs.
> <p />
> * Virtualization must be enabled. Typically, virtualization is enabled by default. (Note that this is different from having Hyper-V enabled.) For more
> detail see [Virtualization must be
> enabled](troubleshoot.md#virtualization-must-be-enabled) in Troubleshooting.
> <p />
> * <b>The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later)</b>. In the future we will support more versions of Windows 10.
> <p />
> * Containers and images created with Docker for Windows are shared between all user accounts on machines where it is installed. This is because all
> Windows accounts will use the same VM to build and run containers. In the
> future, Docker for Windows will better isolate user content.
> <p />
> * <b>Nested virtualization scenarios, such as running Docker for Windows on a VMWare or Parallels instance, might work, but come with no guarantees (i.e., not officially supported)</b>. For more information, see [Running Docker for Windows in nested virtualization scenarios](troubleshoot.md#running-docker-for-windows-in-nested-virtualization-scenarios)
> <p />
> * **What the Docker for Windows install includes**: The installation provides [Docker Engine](/engine/userguide/), Docker CLI client, [Docker Compose](/compose/overview.md), [Docker Machine](/machine/overview.md), and [Kitematic](/kitematic/userguide.md).


So looks like running inside a VM, and on Windows Server 2016 is not officially supported, so may (or may not work).


I'm closing this issue here, because this is an issue for Docker for Windows, which is handled in https://github.com/docker/for-win, but feel free to continue the conversation
