### ISSUE TITLE
Improve failure feedback of docker and dependent systemd units

### ISSUE THREAD

**Issue by krichter722** [moby/moby#35882]
**Description**
If docker fails to start and thus the `systemd` unit `docker.service` or `docker.socket` enter the failed state there's no information in the `systemd` output nor pointer to information for the user to investigate the issue. Output like

```
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.service has finished shutting down.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.socket has finished shutting down.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.socket has begun shutting down.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.socket has begun starting up.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: docker.service: Start request repeated too quickly.
Dez 27 03:01:00 richter-Lenovo-IdeaPad-Z500 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
```

contains zero information which a non-docker-developer can use to investigate the problem (ok, `Start request repeated too quickly.` gives a clue, but it's nothing compared to `Docker failed because the socket is occupied` which is nothing compared to `Docker couldn't start because socket on port x is occupied` which is nothing compared to `Docker couldn't start because socket on port x (configured in file/variable y) is occupied` - you get the idea).

This, by the way, results in the pretty high number and rate of redundancy of docker start failure posts on forums reachable by search engines all basically starting with the same issue description.

Please note that this is not a support request. In an ideal world I just had to update to the version fixing this issue and be able to solve the problem intuitively based on `systemd` output of log files referenced in it.

I'm using Docker 17.11.0-ce, build 1caf76c on Ubuntu 17.10.

**Comment by thaJeztah** [comment]
That's really systemd printing those errors, and not providing more information. The "Start request repeated too quickly." error is coming from systemd as well, and if you google for that string, you'll find many examples (also not printing any additional information).

The docker daemon most likely logs additional errors, but those are not printed by systemd, and you'll have to dig in the logs to find those errors (`journalctl ......`). See, e.g. https://superuser.com/a/1074637/207301

I'm closing this issue, because I don't think this is an issue we can fix, but feel free to continue the conversation

**Comment by krichter722** [comment]
Some `systemd` units manage to reveal failure reasons in `systemctl status` which is very intuitive. However, you're right that one has to dig into `systemd` a bit in order to be able to work with services controlled by it (still light years better than shell scripts). The magical command is `journalctl -u [unit name]`, i.e. `journalctl -u docker.service` (alternatives sketched at https://unix.stackexchange.com/questions/20399/view-stdout-stderr-of-systemd-service).

**Comment by thaJeztah** [comment]
> Some systemd units manage to reveal failure reasons in systemctl status which is very intuitive

If you know of a way to get the error message from the logs there, I'm interested (as it would help the maintainers a lot as well, not having to ask "can you check the logs"), but yes, overall, using `journalctl` to fetch the logs is usually needed to get the desired information.
