### ISSUE TITLE
Go Templates and Parsing Errors When Hyphen is Used

### ISSUE THREAD

**Issue by ossie-git** [moby/moby#35886]
Hi,

A lot of examples use a hyphen (-) in the network name.  For example, the following example is taken from here - https://docs.docker.com/engine/reference/commandline/network_create/#extended-description

```
$ docker network create -d overlay my-multihost-network
```

The problem is if you want to then use a --format to extract a value using a Go template.  For example:

```
docker container inspect --format='{{.NetworkSettings.Networks.my-multihost-network.IPAddress}}' f5
```

results in:

```
Template parsing error: template: :1: bad character U+002D '-'
```

while there are no problems extracting the value if it was simply mymultihostnetwork.

```
docker container inspect --format='{{.NetworkSettings.Networks.mymultihostnetwork.IPAddress}}' f5
10.0.1.9
```

I think either the Go template processing should handle this correctly or the documentation should recommend not using hyphens for network names

The above is all on Docker 17.12

```
$ docker version
Client:
 Version:       17.12.0-ce-rc2
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    f9cde63
 Built: Tue Dec 12 06:38:26 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce-rc2
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   f9cde63
  Built:        Tue Dec 12 06:45:30 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by cpuguy83** [comment]
I think `'{{ $network := index .NetworkSettings.Networks "my-multihost-network" }}{{ $network.IPAddress}}'` would work.

**Comment by cpuguy83** [comment]
Closing since this is pretty much expected and there are go-template methods to deal specifically with maps for this reason.
If you feel like this could use some extra documentation (perhaps an example just like above?) maybe you can add it in https://github.com/docker/docker.github.io ?

Thanks! 🙇
