### ISSUE TITLE
Add security capability for reading GPIO

### ISSUE THREAD

**Issue by pdevine** [moby/moby#35909]
**Description**

The GPIO pins on the raspberry pi get mapped into `/proc/device-tree/soc/ranges` and `/dev/gpiomem`.  If you want to access them inside of a container, you currently have to use `--privileged` mode, which is sub-optimal because it includes many other permissions.  Unfortunately none of the other current security capabilities are sufficient to get access.

**Comment by kolyshkin** [comment]
> none of the other current security capabilities

Do you mean `--cap-add` option? Those are the capabilities of the Linux kernel, not Docker -- and if you want to add such a capability, it is to be added to the kernel.

I think one possible solution to your case is to use SELinux -- have you tried that?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
