### ISSUE TITLE
fluentd log driver can't talk to host fluentd

### ISSUE THREAD

**Issue by yangmillstheory** [moby/moby#35903]
**Description**

Containers run with fluentd log driver can't talk to host fluentd process.

**Steps to reproduce the issue:**
1. `gem install fluentd`
2. Create a `test.conf` fluentd config file:
```
  <source>
    type forward
    port 24224
    bind 0.0.0.0
  </source>
  <match *.*>
    type stdout
  </match>
```
3. `fluentd -c test.conf`
4. `docker run --log-driver=fluentd ubuntu echo "Hello Fluentd"`

**Describe the results you received:**
```
👌 ~/c/test
(i) docker run --log-driver=fluentd ubuntu echo "Hello Fluentd"
docker: Error response from daemon: failed to initialize logging driver: dial tcp 127.0.0.1:24224: getsockopt: connection refused.
```

**Describe the results you expected:**

This actually works against a fluentd container:
```
👌 ~/c/test
(i) docker run -d -p 24224:24224 -v `pwd`/logs:/fluentd/log fluent/fluentd
c1384786a0f59a5d7e9be6797e6407c4153a853a5c834ab6ae1f69a6af44feaf
```

```
❗ ~/c/test
(i) docker run --log-driver=fluentd ubuntu echo "Hello Fluentd"
Hello Fluentd
👌 ~/c/test
(i) tail -1 logs/data.20171229.b56182387f5ac100d.log
20171229T233654+0000    0447d28ef1e3    {"container_id":"0447d28ef1e384bad21584b0dc53db90db0cdcf7cf942c36cd8d2fb88b180b54","container_name":"/optimistic_jennings","source":"stdout","log":"Hello Fluentd"}
```

So I'd expect the below.

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproducible.

**Output of `docker version`:**

```
❗ ~/c/2/tentacles [6f3b899] (feature/LIMS-143-fix-oserror)
(n) docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 62
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: BF2K:42V7:QZYS:QWDY:ZPFJ:B5JB:JEX4:PALD:W2PB:5WHU:AIU7:V4EH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 36
 System Time: 2017-12-30T01:22:12.36553575Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on a Mac, but it happens in an EC2 instance with a custom AMI as well. Not sure about the Docker version there.

**Comment by cpuguy83** [comment]
I'm assuming fluentd is running on the Mac?
If so you'll need to specify the IP address of the mac host.
Docker on the mac is running inside a VM with it's own networking, so it's trying to connect to 127.0.0.1 in the VM and wouldn't be able to reach 127.0.0.1 on the mac.

Closing since this is working as expected, but feel free to discuss.
Thanks! 🙇 👼

**Comment by yangmillstheory** [comment]
Thanks Brian. What other platforms can this be expected to occur for, as it
works fine on our EC2 instances? If there's a small finite list or a way to
test, would you take a PR to update the fluentd driver docs?

**Comment by cpuguy83** [comment]
@yangmillstheory It seems more like a misconception on the docker4mac implementation than an issue with the fluentd docs. This would be an issue for any driver in this case.

**Comment by yangmillstheory** [comment]
That's true, this is about a container accessing a host-bound service. From the [docs](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds), I think using `docker.for.mac.localhost` might work (haven't tried it).

>The Mac has a changing IP address (or none if you have no network access). From 17.06 onwards our recommendation is to connect to the special Mac-only DNS name docker.for.mac.localhost which will resolve to the internal IP address used by the host.
