### ISSUE TITLE
Docker 1.12.6 json-log is not rotated 

### ISSUE THREAD

**Issue by Asher-Shoshan** [moby/moby#35921]
RHEL 7.3
Docker 1.12.6
Kubernetes 1.8
in /etc/docker/damon.json:
{ "log-driver": "json-file", "log-opts": { "max-size": "1m", "max-file" : "1000" } }
But when Kubernetes starts a new container log is not rotated.  i.e. above is not respected.
Inspecting the container shows:
docker inspect --format '{{ json .HostConfig.LogConfig }}' fedbaa6ab0552b7a9fe4bafeebcf82505b46a7b4a43add264693958b4f044f23
---> 
{"Type":"json-file","Config":{}}

**Comment by thaJeztah** [comment]
Is the default applied if you manually start a container? (`docker run ... ` something)?

**Comment by Asher-Shoshan** [comment]
No.. Same behavior as with "kubectl run ..."

**Comment by thaJeztah** [comment]
I'm not able to reproduce;


```bash
$ mkdir /etc/docker
$ echo '{ "log-driver": "json-file", "log-opts": { "max-size": "1m", "max-file" : "1000" } }' > /etc/docker/daemon.json
$ dockerd
```


Then, start a container;

```bash
$ docker run -d nginx:alpine
Unable to find image 'nginx:alpine' locally
alpine: Pulling from library/nginx
128191993b8a: Pull complete 
eb7d4e7a5a24: Pull complete 
7bf750ac70e1: Pull complete 
3313627c7838: Pull complete 
Digest: sha256:40e95eef5082a5b26c5fd9441bd7ee6bcda1bb5f9fbf7a4a1ef9b2b0f88d5c43
Status: Downloaded newer image for nginx:alpine
81c9c4daa7dac440f445da086dcbc347d57d641c5e474c03b1da4615e406dc3a
```

and inspect;

```bash
$ docker inspect --format '{{ json .HostConfig.LogConfig }}'  81c9c4daa7dac440
f445da086dcbc347d57d641c5e474c03b1da4615e406d
{"Type":"json-file","Config":{"max-file":"1000","max-size":"1m"}}
```


How is the daemon started? Do you have any custom configuration options on the daemon (e.g. set in a systemd unit file?)

Are you running the official docker packages, or running the Red Hat fork of docker?


Note that docker 1.12 has reached end of life in March of last year, thus is no longer maintained, and doesn't receive any updates; there are known vulnerabilities in that version, so I really would recommend updating to a current version of Docker

**Comment by Asher-Shoshan** [comment]
Hi,
RU using /etc/sysconfig/docker file?
I think this file overrides the /etc/docker/damon.json file;
Will try either remove the option from 1st file or add the options as well - looks  like damon.json is being  ignored/overridden..
Installed Docker from RedHat repos.

**Comment by thaJeztah** [comment]
The `/etc/sysconfig/docker` is not used in the official packages, only in the Red Hat fork of Docker.

I'd recommend considering to use the official Docker packages instead; there's a lot of changes made in the Red Hat fork of Docker, and quite some issues have been reported here, that turned out to be caused by those changes.

Following the discussion above, I don't think there's bug at hand here, and the version of Docker you have installed is not maintained here, so I'll go ahead and close this issue, but feel free to continue the conversation.

**Comment by Asher-Shoshan** [comment]
I did some more tests, and the damon.json is indeed overridden by /etc/sysconfig/docker.
Added the log-opt lines there, and now the inspect shows the desired values...
From where should I update the installation?

**Comment by thaJeztah** [comment]
You can use the installation instructions from the docs; https://docs.docker.com/engine/installation/linux/docker-ce/centos/, that's for CentOS (should probably work), but RHEL is officially only supported on the Enterprise Edition of Docker https://docs.docker.com/engine/installation/linux/docker-ee/rhel/ (which requires a subscription, but you can get a trial version)

**Comment by Asher-Shoshan** [comment]
Thanks,
Docker-ce is not working with kubernetes....
So what Rhel (+subscription to redhat) users should do?

**Comment by thaJeztah** [comment]
docker ce should work fine with kubernetes, but I guess that Red Hat's packages lock you in in their Docker version
