### ISSUE TITLE
Call docker api ContainerAttach to a stopped container, read Stdout will block forever.

### ISSUE THREAD

**Issue by wangyun** [moby/moby#35948]
**Description**

Call docker api ContainerAttach，to a stopped container, then read from the returned resp.Reader, it will block forever.

**Steps to reproduce the issue:**
1. docker run -it --name="test" ubuntu /bin/bash
2. exit container.
3. set ContainerAttachOptions's Logs,Stream,Stdout and Stderr to true, and containerName to "test", call client api ContainerAttach

**Describe the results you received:**

The returned err is nil, then read from resp.Reader in loop, it returns the std logs from the stopped container, then blocks forever on reader.Read

**Describe the results you expected:**

If call ContainerAttach to a stopped container, return some error like the docker cli do:
"You cannot attach to a stopped container, start it first"

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by wangyun** [comment]
And if attach to a running container, after the container stop,
reader.Read will return.

**Comment by thaJeztah** [comment]
I think this may be by design; does it show output if you start the container?

**Comment by wangyun** [comment]
Ah, you are right!
I run 'docker start -i test'
the reader.Read continues to read out the container's output.
Thank you!

**Comment by wangyun** [comment]
But I think the behavior is still a little strange.
Because I cannot know if the attached container is stopped or not.
And if I exit container now, the reader.Read will get io.EOF.
which I think is inconsistent with the design.

**Comment by thaJeztah** [comment]
Great! So, yes, IIRC, this is to allow (re)attaching to a container before its started.

Let me close this issue, because this doesn't look like a bug, but feel free to continue the conversation :+1:

**Comment by wangyun** [comment]
Ah, I see it now, I can attach before start the container the first time. 
Thank you.
