### ISSUE TITLE
Does auto run the func New() method ?

### ISSUE THREAD

**Issue by wangxf1987** [moby/moby#35944]
**Steps to reproduce the issue:**
1.  I found func New() in the most go file.
2. Does auto run the func New() method, and the New is not a import key in golang.
3. I put a fmt method, the message was print.
4. So where is the implementation entry for this method?

**Describe the results you received:**
This a not bug, So there is empty.

**Describe the results you expected:**
This a not bug, So there is empty.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
docker-ce 1706

**Comment by cpuguy83** [comment]
You'd have to be more specific.
But no, `New()` is never auto-run. `New()` functions are generally helpers for constructing an object when an empty `foo{}` is not useful or is otherwise error-prone for configuring properly.
