### ISSUE TITLE
How to init the memory.store method ?

### ISSUE THREAD

**Issue by wangxf1987** [moby/moby#35945]
**Steps to reproduce the issue:**
1. I want to use the store method and check tasks,
`s.View(func(tx store.ReadTx) {`
		`a_tasks, a_err = store.FindTasks(tx, store.All)`
	`})`
	`if a_err != nil {`
		`return errors.Wrap(a_err, "error listing all tasks in store while trying to allocate task")`
`}`
2. but above code that need to init store, how can i do init method?
    Get a raftnode?

**Comment by cpuguy83** [comment]
Can you provide some more context? I'm not sure exactly what you are asking.
The swarmkit store interface is not exposed over the swarmkit API, so there is no access to it directly from inside the moby code.

However it does expose an API to list and filter tasks.

**Comment by wangxf1987** [comment]
Thx @cpuguy83 ,
I access the memory store in the github.com/docker/swarmkit/manager/allocator/networkallcator/networkallcator.go, and modified func AllocateTask(). Code show as below:
`var (
		s       *store.MemoryStore
		a_tasks []*api.Task
		a_err   error
		//m_config manager.Config
	)
	s.View(func(tx store.ReadTx) {
		a_tasks, a_err = store.FindTasks(tx, store.All)
	})
	if a_err != nil {
		return errors.Wrap(a_err, "error listing all tasks in store while trying to allocate task")
	}`
If want to access to memory store, It's have to init the config about the raft node information.
So How can i init the config?

**Comment by thaJeztah** [comment]
This code is coming from the SwarmKit dependency; I see you opened the same question in that repository (https://github.com/docker/swarmkit/issues/2481), so let's close the issue here.

Note that the Docker Community Slack channel may be better suited for such questions, as the issue tracker is meant for bug-reports and feature requests
