### ISSUE TITLE
Failed to start docker on an Amazon linux machine

### ISSUE THREAD

**Issue by avitheavi** [moby/moby#35952]
Hi, I am using an Amazon linux machine (p2).

I have installed this docker version: 
    Client:
     Version:      17.03.2-ce
     API version:  1.27
    Go version:   go1.7.5
    Git commit:   7392c3b/17.03.2-ce
    Built:        Wed Aug  9 22:45:09 2017
   OS/Arch:      linux/amd64

I'm not sure, but I think the issue started after killing a screen which ran some docker container

I'm experiencing this error:

    sudo docker ps
   
Gives:

    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

And:
    
    sudo service docker status

Gives:
    
    docker dead but subsys locked

I have tried both:
  
    sudo rm -rf /var/run/docker
    sudo rm /var/run/docker.*

I have also tried 
    
    sudo service docker start/stop

And to reboot the machine.

**Comment by thaJeztah** [comment]
Amazon Linux is not a supported distro; there's no official packages for Amazon linux (although I think Amazon has some packages for it, but those are not official, and support for those goes through Amazon).

Closing because of the above, but feel free to comment after I closed
