### ISSUE TITLE
Document that CopyFromContainer returns a TAR io.Reader

### ISSUE THREAD

**Issue by emil2k** [moby/moby#35956]
It is not quite clear from this documentation that you are getting a **TAR** reader:

https://github.com/moby/moby/blob/16a1736b9b93e44c898f95d670bbaf20a558103d/client/container_copy.go#L61-L62

For comparison, `CopyToContainer` explicitly mentions this:

https://github.com/moby/moby/blob/16a1736b9b93e44c898f95d670bbaf20a558103d/client/container_copy.go#L32-L33

**Comment by yongtang** [comment]
Added PR #35958 for that.
