### ISSUE TITLE
Networking related bugs in the latest busybox image on x86?

### ISSUE THREAD

**Issue by arm64b** [moby/moby#35963]
**Description**
Since the PR #35929 always makes the test case `TestDockerNetworkInternalMode` failed on amd64 and arm{32,64} platforms, so I decide to dig into what the root cause is. After some investigation, I found an interesting scenario:
For the latest busybox 1.27, the `ping` command between 2 busybox container daemons will not succeed. See the below steps for more detail.

**Steps to reproduce the issue:**
1.  pull the 1.27.2 busybox images with `docker pull busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0`, the image id is `6ad733544a63`
2. pull the 1.26 busybox images with `docker pull busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f`, the image id is `00f017a8c2a6` 
3. According to the testing steps in  `TestDockerNetworkInternalMode`, I input below commands:
3.a  `docker network create --driver=bridge --internal internal`
3.b  Launch 4 busybox docker daemons:
```
      `docker run -d --net=internal --name=first-1.27 6ad733544a63 top`
      `docker run -d --net=internal --name=second-1.27 6ad733544a63 top`
      `docker run -d --net=internal --name=first-1.26  00f017a8c2a6 top`
      `docker run -d --net=internal --name=second-1.26  00f017a8c2a6 top`
```
3.c  `ping` between 2 daemons (both are the same version of busybox):
```
# docker exec second-1.26 ping -c1 first-1.26
PING first2 (172.18.0.6): 56 data bytes
64 bytes from 172.18.0.6: seq=0 ttl=64 time=0.069 ms
--- first2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss

# docker exec second-1.27 ping -c1 first-1.27
ping: bad address 'first-1.27'
```
**Describe the results you received:**
`ping` command fails between 2 busybox damons with 1.27 version

**Describe the results you expected:**
`ping` command should be success between 2 busybox damons with 1.27 version like version 1.26 is. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-dev
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   2eac0bb7
 Built:        Thu Jul 20 06:11:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      dev
 API version:  1.36 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   d4240db
 Built:        Tue Jan  9 06:52:01 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 73
Server Version: dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.7
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.66GiB
Name: dennis-ws
ID: RNF4:PMNH:GSJ7:ATEN:PHVN:D5OE:RHLD:HCR5:XLKB:7IKW:DDXB:3OZ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: arm64b
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks! Interesting ...

**Comment by arm64b** [comment]
Just test on AArch64 platform with the same steps, this issue doesn't show 😵

**Comment by arm64b** [comment]
output of `strace` for v1.26:
```
[snip]
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
setsockopt(5, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(5, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4086653040, u64=139637768413296}}) = 0
getsockname(5, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(5, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
write(5, "POST /v1.31/exec/2d07804ed143a9c"..., 430) = 430
read(5, 0xc420478000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x13ec990, FUTEX_WAIT, 0, NULL)   = 0
epoll_wait(4, [{EPOLLOUT, {u32=4086653040, u64=139637768413296}}], 128, 0) = 1
futex(0x13ec990, FUTEX_WAIT, 0, NULLPING first (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.055 ms
```

output of `strace` for v1.27:
```
[snip]
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
setsockopt(5, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(5, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=355033936, u64=140587519533904}}) = 0
getsockname(5, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(5, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
write(5, "POST /v1.31/exec/b6a4ef4df5a87e7"..., 431) = 431
read(5, 0xc420465000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x13ec990, FUTEX_WAIT, 0, NULL)   = 0
epoll_wait(4, [{EPOLLOUT, {u32=355033936, u64=140587519533904}}], 128, 0) = 1
futex(0x13ec990, FUTEX_WAIT, 0, NULLping: bad address 'first1'
)   = 0
[snip]
```

Seems the latest ping code has bug on linux/amd machine...

**Comment by thaJeztah** [comment]
That strace won't give much information, as it's a strace of the docker cli, not the busybox binary

**Comment by arm64b** [comment]
Hello @thaJeztah  Right, so today I try to bisect the busybox git repo...
But would you pls help to force rebuild `powerpc` and `z` node for #35929 , since I found that these 2 machine don't take actual action at all 😃

**Comment by thaJeztah** [comment]
Sure! Let me restart those 👍

**Comment by tophj-ibm** [comment]
interesting, gave this a test on docker4mac (amd64) and it works as intended with both 1.27 and 1.28

**Comment by arm64b** [comment]
@tophj-ibm Yes, I just test it on my macOS/amd64 system, it works for both 1.27 and 1.28, so basically now we can narrow down this issue to **linux/amd64** system

**Comment by arm64b** [comment]
Hello @thaJeztah , can I bother you to restart the `powerpc` node for that PR again before dnephin can take another look? Since I found your time slot is a little bit close with me, hahaha~

**Comment by thaJeztah** [comment]
Well, I'm often in the `UTC++` timeslot :joy:


done!

**Comment by arm64b** [comment]
Your so quick response is always appreciated, sincerely I'd like to invite you to have a drink ☕️  when you travel here some day 😂😂

**Comment by thaJeztah** [comment]
Thanks! Never been to your area; let me book a flight and try if "getting a cup of coffee" on my expense form is accepted :joy:
