### ISSUE TITLE
Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error

### ISSUE THREAD

**Issue by ohmerhe** [moby/moby#35972]
**Steps to reproduce the issue:**
1. just start `docker run hello-world`
2. 

**Describe the results you received:**

docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/262f67d9beb653ac60b1c7cb3b2e183d7595b4a4a93f0dcfb0ce689a588cedcd/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown.
ERRO[0000] error waiting for container: context canceled

**Describe the results you expected:**

run success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 2
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-1231531-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.127GB
 Data Space Total: 107.4GB
 Data Space Available: 49.91GB
 Metadata Space Used: 1.974MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: N/A (expected: b2567b37d7b75eb4cf325b77297b140ea686ce8f)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: gerrit-android-apigateway-dev001-bjdxt9ssd.qiyi.virtual
ID: 2NZJ:NXOY:3V7L:RUNL:3LFA:NN4Z:LECB:5SPK:U7FJ:3QMH:KTAQ:DTIH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux gerrit-android-apigateway-dev001-bjdxt9ssd.qiyi.virtual 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.1.1503 (Core)

**Comment by thaJeztah** [comment]
You're running an obsolete version of CentOS.

CentOS uses a rolling release model, which means that when CentOS 7.2 was released, CentOS 7.1 became obsolete. Docker only is able to support the current version of CentOS (which is 7.4 at this time of writing); see the [installation docs](https://docs.docker.com/engine/installation/linux/docker-ce/centos/#prerequisites);

> To install Docker CE, you need a maintained version of CentOS 7. Archived versions aren’t supported or tested.

closing this issue, because this version of CentOS is too old, and no longer supported, but feel free to continue the conversation

**Comment by Kopei** [comment]
I have the same problem. Installing an older docker-ce should work.
```
cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 

yum install docker-ce-17.06.1.ce
systemctl start docker
docker pull nginx
```

**Comment by juliocarrera-amgen** [comment]
I was running Docker 1.7.1 without a problem. But upgrading to 1.13 causes this problem. And I'm running RHEL not CentOS.

**Comment by thaJeztah** [comment]
What version of RHEL? If you're running RHEL 6, then Docker 1.7.1 is the last version that supports RHEL 6 (and the 2.6 kernel). Docker 1.7.1 is highly insecure by now, and has known vulnerabilities

**Comment by juliocarrera-amgen** [comment]
It was RHEL 6.7 (Santiago). We'll upgrade to 7.1 (Maipo). Thanks!

**Comment by thaJeztah** [comment]
7.1 is still pretty old; there have been various improvements in the RHEL kernels in 7.4 that resolve issues with mounts etc, but at least it's better than RHEL 6

**Comment by juliocarrera-amgen** [comment]
Sounds good. Thanks for the suggestion!

Julio C Carrera

[images]
Digital Integration & Predictive Technologies (DIPT) │Process Development
T: 617.444.5461 | C: 508-333-3993

Want to know more about the DIPT team?
Check out the Digital Integration and Predictive Technologies<https://amgen.sharepoint.com/sites/DIPT/SitePages/default.aspx> site. ​​

**Comment by yivo** [comment]
`CentOS Linux release 7.4.1708 (Core)`
`Docker version 17.12.1-ce, build 7390fc6`

Having the same issue.

**Comment by joeyhub** [comment]
I'm getting this with Docker version 18.03.1-ce

However in my case it's when performing parallel builds.

When I switch them back to serial I don't see this problem.

This makes me think when the docker build process finishes it doesn't actually finish.

This is for parallel but other people could also have issues with a similar cause if docker never really finished for reasons beyond temporal leaving internals in a weird state.

**Comment by DebugXYZ** [comment]
CentOS Linux release 7.5.1804 (Core) & Docker version 18.06.1-ce, build e68fc7a

Same issue, any background on this?

**Comment by lromor** [comment]
Same issue on Gentoo (which is not supported but still...)
linux kernel version: 4.14.65-gentoo
docker version: 18.03.1-ce

**Comment by rcrane** [comment]
I had this:

```
sudo docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: 
starting container process caused "process_linux.go:402: container init caused
 \"process_linux.go:385: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd
 (deleted): no such file or directory\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

A simple `sudo service docker restart` (Ubuntu) helped.

**Comment by pascalandy** [comment]
I had the same issue. This is like a fatal error for Docker. Running `sudo service docker restart` is not enough here. Have to reboot.

**Comment by samip5** [comment]
Same problem.

CentOS Linux release 7.6.1810 (Core)
Docker version 18.09.3, build 774a1f4

**Comment by pascalandy** [comment]
This bug forced me to scrap all my server and restart from scratch. All good since 2 months.

**Comment by samip5** [comment]
> This bug forced me to scrap all my server and restart from scratch. All good since 2 months.

Unfortunately, it's not an option. Running cPanel on the server.

**Comment by ramab1988** [comment]
```ln -s /usr/bin/nvidia-container-toolkit /usr/bin/nvidia-container-runtime-hook```
Solved the problem for me

**Comment by User881-cmd** [comment]
I am facing the same error while running the command: docker run hello-world

docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d20cdc5ed8350f63b5463d7170e1751e964eb2eb767c5e6517043c9019224ab8/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown.
ERRO[0000] error waiting for container: context canceled


NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (i586)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"

Please suggest!

**Comment by thaJeztah** [comment]
Different error, and potentially a corrupted container (perhaps a container that was not fully removed). However, it looks like you're running a version of docker that was built and packages by SUSE; those packages may have modifications and different configuration than the upstream official builds, so I'd contact SUSE support if you suspect a bug;

```
BUG_REPORT_URL="https://bugs.opensuse.org"
