### ISSUE TITLE
Docker restarts after upgrading latest kernel version

### ISSUE THREAD

**Issue by sbopi** [moby/moby#35985]
**Description**

For "Meltdown and Spectre patch", we are upgrading kernel version from 4.8.3 to 4.14.12. 
Docker verion used 17.05.0-ce.
After kernel upgrade, docker goes to hung state intermittently. We have multiple nodes in our cluster, few node docker is running for 19 hrs... few node docker restarts continuously

**Steps to reproduce the issue:**
1. Upgrade kernel version from 4.8.3 to 4.14.12
2. Verify docker status. dockerd output "hung"
3. 

**Describe the results you received:**
dockerd output "hung"

**Describe the results you expected:**
docker status running

**Additional information you deem important (e.g. issue happens only occasionally):**
issue happens intermittently

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:80-50331713-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.979GB
 Data Space Total: 107.4GB
 Data Space Available: 28.17GB
 Metadata Space Used: 14.66MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.133GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.12-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.299GiB
Name: prodmint19-edge-1
ID: 3HKN:6HEH:QYKM:7TNU:RC4E:TWA3:BSA4:EDHP:QPDM:O6JI:HMCG:LF2D
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 docker-registry.service.local:5040
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Do you have any logs from the daemon?
Please also note that 4.14 isn't really a supported kernel on CentOS and this could cause all kinds of issues, especially around devicemapper support, selinux, etc.

**Comment by sbopi** [comment]
Attached output of journalctl -u docker.service. I do not see /var/log/daemon.log in my node. Could you provide me the path of the file you are looking for if you do not need this output.

[journalctl.txt](https://github.com/moby/moby/files/1624418/journalctl.txt)

**Comment by cpuguy83** [comment]
This does not look like `journalctl -u docker.service` but rather the whole system.
Can you verify?

**Comment by dentaku65** [comment]
Hi,
same here. Upgrading to kernel 4.14.12 the docker daemon won't load. Ubuntu server 16.04

Journalctl: https://pastebin.com/zGEfxsYx

**Comment by cpuguy83** [comment]
```
Jan 12 14:55:14 kaiamt01 dockerd[1424]: time="2018-01-12T14:55:14.783764268+01:00" level=error msg="[graphdriver] prior storage driver aufs failed: driver not supported"
Jan 12 14:55:14 kaiamt01 dockerd[1424]: Error starting daemon: error initializing graphdriver: driver not supported
```

You are missing the aufs kernel module after upgrading, so docker can't start.
You'll either need to load those kernel module or specify a different driver.

**Comment by dentaku65** [comment]
Thx cpuguy83!

**Comment by sbopi** [comment]
Thanks cpuguy83

Updates:
1. Certainly we had all required modules and issue is not same as dentaku65 reported.
2. We upgraded to docker 17.12 (from 17.05) + overlay2 (from devicemapper) is stable now.

**Comment by cpuguy83** [comment]
@sbopi Thanks for reporting back!
I'm going to close this as any issue is most likely due to the system changes and not with docker or it's internal state.

Thanks again! 🙇
