### ISSUE TITLE
Plugin not found message in daemon log

### ISSUE THREAD

**Issue by tbouvet** [moby/moby#35992]
**Description**

After installing a plugin (netapp/ndvp), some repetitive error messages appear in the daemon log.

```
Jan 12 09:44:00 host1 dockerd[14753]: time="2018-01-12T09:44:00.014410367+01:00" level=error msg="plugin not found"
Jan 12 09:43:55 host1 dockerd[14753]: time="2018-01-12T09:43:55.798532970+01:00" level=error msg="plugin not found"
Jan 12 09:43:18 host1 dockerd[14753]: time="2018-01-12T09:43:18.554964465+01:00" level=error msg="plugin not found"
Jan 12 09:43:10 host1 dockerd[14753]: time="2018-01-12T09:43:10.415306479+01:00" level=error msg="plugin not found"
Jan 12 09:43:01 host1 dockerd[14753]: time="2018-01-12T09:43:01.650009043+01:00" level=error msg="plugin not found"
Jan 12 09:42:29 host1 dockerd[14753]: time="2018-01-12T09:42:29.129704504+01:00" level=error msg="plugin not found"
Jan 12 09:42:26 host1 dockerd[14753]: time="2018-01-12T09:42:26.203150845+01:00" level=error msg="plugin not found"
Jan 12 09:42:08 host1 dockerd[14753]: time="2018-01-12T09:42:08.936892945+01:00" level=error msg="plugin not found"
Jan 12 09:41:57 host1 dockerd[14753]: time="2018-01-12T09:41:57.008843300+01:00" level=error msg="plugin not found"
```

**Steps to reproduce the issue:**
1. Install netapp/ndvp plugin ( http://netappdvp.readthedocs.io/en/latest/install/host_config.html )
2. journalctl -u docker.service

**Describe the results you received:**
```
Jan 12 09:44:00 host1 dockerd[14753]: time="2018-01-12T09:44:00.014410367+01:00" level=error msg="plugin not found"
Jan 12 09:43:55 host1 dockerd[14753]: time="2018-01-12T09:43:55.798532970+01:00" level=error msg="plugin not found"
Jan 12 09:43:18 host1 dockerd[14753]: time="2018-01-12T09:43:18.554964465+01:00" level=error msg="plugin not found"
Jan 12 09:43:10 host1 dockerd[14753]: time="2018-01-12T09:43:10.415306479+01:00" level=error msg="plugin not found"
Jan 12 09:43:01 host1 dockerd[14753]: time="2018-01-12T09:43:01.650009043+01:00" level=error msg="plugin not found"
Jan 12 09:42:29 host1 dockerd[14753]: time="2018-01-12T09:42:29.129704504+01:00" level=error msg="plugin not found"
Jan 12 09:42:26 host1 dockerd[14753]: time="2018-01-12T09:42:26.203150845+01:00" level=error msg="plugin not found"
Jan 12 09:42:08 host1 dockerd[14753]: time="2018-01-12T09:42:08.936892945+01:00" level=error msg="plugin not found"
Jan 12 09:41:57 host1 dockerd[14753]: time="2018-01-12T09:41:57.008843300+01:00" level=error msg="plugin not found"
```

**Describe the results you expected:**
No error in the log

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: host1
ID: MIFR:GSOU:P4FI:ZIFY:FTD6:BZ4M:U6KV:NDX2:W3VV:J6AM:MYIQ:POSN
Docker Root Dir: /var/lib/docker/100000.100000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: etcd://localhost:2379
Cluster Advertise: 192.168.1.29:2376
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://myregistry.com/
Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu VM:
```
Linux host1 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan

**Comment by anusha-ragunathan** [comment]
Engine 17.12.0-ce is legacy plugin model. Are we still supporting that @thaJeztah ?

**Comment by cpuguy83** [comment]
@anusha-ragunathan Perhaps you are thinking 1.12?

**Comment by thaJeztah** [comment]
The message either comes from here; https://github.com/moby/moby/blob/c492e76d13a61b13815475d1a6393ab1da1db5c8/plugin/backend_linux.go#L522-L532

or 

https://github.com/moby/moby/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/plugins/discovery.go#L60-L85

**Comment by anusha-ragunathan** [comment]
@tbouvet : Can you explain when you get the error? Were you able to install the plugin and create volumes at some point in time? 

Lets verify that the plugin socket is alive and functional. There should be a docket file (ending in .sock) for netapp nDVP under `/run/docker/plugins`. Locate that. Then issue a curl request against it and report results. You can follow this debug info https://github.com/docker/docker-ce/blob/e947e4d4f1a55589a3eb4f049f51ddeddaf8c2da/components/cli/docs/extend/index.md#debugging-plugins

**Comment by anusha-ragunathan** [comment]
@cpuguy83 : You are right!

**Comment by tbouvet** [comment]
@anusha-ragunathan I have this error after having installed the plugin. And this error is repetitive. Every 20/30 seconds this error appear.

Yes I have a socket file `netapp.sock ` in `/run/docker/plugins/<plugin-id>`.

For your information, I use user-namespace and it's the last version of docker-engine (`17.12.0-ce`)

```
curl -H "Content-Type: application/json" -XPOST -d '{}' --unix-socket /var/run/docker/plugins/272f8cfc9315938611811c9a6724544c6e7705f56396983b33373d7c78de0167/netapp.sock http:/VolumeDriver.List
{"Mountpoint":"","Err":"","Volumes":[{"Name":"portainer_data","Mountpoint":"","Status":null},{"Name":"samplevol","Mountpoint":"","Status":null}],"Volume":null,"Capabilities":{"Scope":""}}
```

**Comment by anusha-ragunathan** [comment]
@tbouvet : I need debug logs of the docker daemon. You can enable debugging like [so](http://success.docker.com/article/How_do_I_enable_'debug'_logging_of_the_Docker_daemon)

Few more questions:
- Are you able to create volumes despite the error?
- Is the plugin in an enabled state? What's the output of `docker plugin ls`?
- Did the netapp plugin work with previous versions of docker? 
- Can you try other tags of the netapp plugin? https://hub.docker.com/r/netapp/ndvp-plugin/tags/
`17.07` was released 6 months back. Can you try `17.04` and `17.10` and report results?

**Comment by tbouvet** [comment]
@anusha-ragunathan Here are the answers:
- Yes I can create and use volume
- The plugin is enable:
```
ID                  NAME                DESCRIPTION                          ENABLED
92b7a0434a74        netapp:latest       nDVP - NetApp Docker Volume Plugin   true
```
- I have the same problem with a previous version of docker (`17.09`)
- I have tried with `17.04`, same problem. I try with `17.10 `but for the moment I can not start the plugin. I'm looking for the problem.
- For the debug log, I only have:
```
Jan 18 12:35:38 host1 dockerd[32135]: time="2018-01-18T12:35:38.398015207+01:00" level=debug msg="Calling GET /v1.30/volumes"
Jan 18 12:35:38 host1 dockerd[32135]: time="2018-01-18T12:35:38.398146613+01:00" level=error msg="plugin not found"
```

**Comment by anusha-ragunathan** [comment]
Given that you can create volumes with the netapp plugin is good. It is possible that the error is due to a different plugin, most likely a stale legacy plugin. 

What are the contents of the plugin runRootDir, `/run/docker/plugins` (not `/run/docker/plugins/<pluginID>` like earlier)? Are there any .sock, .spec or .json files in here? Are there other pluginID dirs, other than the netapp pluginID directory?

**Comment by tbouvet** [comment]
@anusha-ragunathan I only have this plugin in my machine. And so no files in `/run/docker/plugins`. And this error message appear only when I have installed this plugin.

**Comment by thaJeztah** [comment]
We should improve that error and (if possible) include information about _which_ plugin was not found (but looks like the error is currently in an exported var, so we should check if the _literal_ error message is used for application logic)

**Comment by tbouvet** [comment]
@anusha-ragunathan FYI same problem with `17.10 `version

**Comment by RemyCH** [comment]
For info the message can be remove by 👎 
- adding a symbolic link  /var/run/docker/plugins/netapp.sock -> /var/run/docker/plugins/rf123121fdqisdi123123/netapp.sock

 Where rf123121fdqisdi123123 is the id of your netshare plugin. BTW YOU SHOULD NOT DO IT, as it will make the netapp plugin having some other error.
 But the intesting point is that docker engine seems to stop complaining about "plugin not found".
 
 Does it mean that somewhere in the code, docker engine is waiting for a default patch for socket, and don't dig into plugin_id directory ?

**Comment by ntap-rippy** [comment]
I did some digging too.  

This appears whenever a 'docker volume ls' occurs.

This line of code is generating the message:
https://github.com/moby/moby/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/plugins/discovery.go#L84

I changed that line to the following, recompiled docker, and now have more info in my log:
>return nil, errors.New(fmt.Sprintf("plugin not found; name: %s, socketsPath %v, socketpaths: %v, specsPaths: %v", name, socketsPath, socketpaths, specsPaths))
>
>Jan 24 19:37:55 docker dockerd[17117]: time="2018-01-24T19:37:55.919907270Z" level=error msg="plugin not found; name: netapp, socketsPath /run/docker/plugins, socketpaths: [/run/docker/plugins/netapp.sock /run/docker/plugins/netapp/netapp.sock], specsPaths: [/etc/docker/plugins /usr/lib/docker/plugins]"


Note, the actual sock file is in a different location than being checked above (go-plugin-helpers is used to create this btw):

>root@docker:/# find /run/docker/plugins | grep netapp.sock
>/run/docker/plugins/9a9dc6f23baae43a3e45b2f6093ae8e7e1b7630fb2b08d38ba7bdb2bc7ea3933/netapp.sock

Looks like Docker's underlying Scan() logic which finds the plugin is different than the Plugin() logic which is used to get info about the plugin.

Scan() walks the filesystem looking for a socket file:
https://github.com/moby/moby/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/plugins/discovery.go#L31-L41

Plugin() however only checks 2 locations and doesn't walk the filesystem:
https://github.com/moby/moby/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/plugins/discovery.go#L126-L131

**Comment by cpuguy83** [comment]
@ntap-rippy What does the (v2) plugin config look like?

**Comment by ntap-rippy** [comment]
@cpuguy83 https://github.com/NetApp/netappdvp/blob/master/contrib/docker/plugin/plugin.json

**Comment by ntap-rippy** [comment]
I am seeing the same error message behavior in the logs with the vieux/docker-volume-sshfs reference plugin installed (and nothing else, just it):
https://github.com/vieux/docker-volume-sshfs

My modified docker demon emits this when I do a "docker volume ls" with it installed.

> Jan 25 01:20:58 docker dockerd[17117]: time="2018-01-25T01:20:58.184265800Z" level=error msg="plugin not found; name: sshfs, socketsPath /run/docker/plugins, socketpaths: [/run/docker/plugins/sshfs.sock /run/docker/plugins/sshfs/sshfs.sock], specsPaths: [/etc/docker/plugins /usr/lib/docker/plugins]"

**Comment by cpuguy83** [comment]
I'm curious why the v1 plugin scanner would find these plugins such that it would try and load them. This should not be happening.
What is the contents of these socket paths and spec paths?

**Comment by ntap-rippy** [comment]
Using the docker-volume-sshfs plugin, since anyone can easily install and reproduce this and see the same behavior.  Of course, you'd need to change the line as I did above to get the extra debugging output I added to my docker engine.

```bash
# docker plugin install vieux/sshfs DEBUG=1
Plugin "vieux/sshfs" is requesting the following privileges:
 - network: [host]
 - mount: [/var/lib/docker/plugins/]
 - mount: []
 - device: [/dev/fuse]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from vieux/sshfs
2381f72027fc: Download complete 
Digest: sha256:72c8cfd1a6eb02e6db4928e27705f9b141a2a0d7f4257f069ce8bd813784b558
Status: Downloaded newer image for vieux/sshfs:latest
Installed plugin vieux/sshfs

# docker volume ls
DRIVER              VOLUME NAME
local               dockerdev-go-pkg-cache-gopath
local               dockerdev-go-pkg-cache-goroot-linux_amd64
local               dockerdev-go-pkg-cache-goroot-linux_amd64_netgo

# journalctl -xe | grep -i "plugin not found"
Jan 25 01:20:58 docker dockerd[17117]: time="2018-01-25T01:20:58.184265800Z" level=error msg="plugin not found; name: sshfs, socketsPath /run/docker/plugins, socketpaths: [/run/docker/plugins/sshfs.sock /run/docker/plugins/sshfs/sshfs.sock], specsPaths: [/etc/docker/plugins /usr/lib/docker/plugins]"

# find /run/docker/plugins                                                                                                                                                                                 
/run/docker/plugins
/run/docker/plugins/5e3cb486c34b7285630b5d9d4aeaa6494af2950b19c70279c61ca1a719a05dc1
/run/docker/plugins/5e3cb486c34b7285630b5d9d4aeaa6494af2950b19c70279c61ca1a719a05dc1/sshfs.sock
/run/docker/plugins/runtime-root
/run/docker/plugins/runtime-root/plugins.moby
/run/docker/plugins/runtime-root/plugins.moby/5e3cb486c34b7285630b5d9d4aeaa6494af2950b19c70279c61ca1a719a05dc1
/run/docker/plugins/runtime-root/plugins.moby/5e3cb486c34b7285630b5d9d4aeaa6494af2950b19c70279c61ca1a719a05dc1/state.json

# ls -l /run/docker/plugins/sshfs.sock
ls: cannot access '/run/docker/plugins/sshfs.sock': No such file or directory

# ls -l /run/docker/plugins/sshfs/sshfs.sock
ls: cannot access '/run/docker/plugins/sshfs/sshfs.sock': No such file or directory

# ls -l /etc/docker/plugins
total 0

# ls -l /usr/lib/docker/plugins
ls: cannot access '/usr/lib/docker/plugins': No such file or directory
```

**Comment by cpuguy83** [comment]
I see the problem... we souldn't be doing a `filepath.Walk` here.

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/pull/36119 should fix this.
The error is benign as the code path is only exercised when using the volume list API, and effectively nothing is happening since it can't find the plugin (since it's not a valid v1 plugin path).

**Comment by MohanNagendraKumar** [comment]
Error response from daemon: create sample_vol: Error looking up volume plugin hpe: legacy plugin: plugin not found
  This is the error when i try create a volume

**Comment by thaJeztah** [comment]
@MohanNagendraKumar that sounds like a possibly valid error; do you have either an existing volume that uses the `hpe` volume driver plugin, or are you trying to use the `hpe` volume driver plugin but it's not installed / enabled? (https://store.docker.com/plugins/hpe-3par-docker-volume-plugin)
