### ISSUE TITLE
Cannot exec -it into container 

### ISSUE THREAD

**Issue by d8888** [moby/moby#35997]
**Description**
Cannot perform "docker exec <container_id> -it bash", will get following error message:

`oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"-it\\\": executable file not found in $PATH\"\n`

**Steps to reproduce the issue:**
1. No error when docker is freshly installed.
2. After performing "docker kill" and "docker rm" on same arbitrary container, the problem shows up
3. After the problem shows up for first time, all subsequent "docker exec \<container\> -it <command>" always fail, for every \<container\> and every \<command\>, such as:
`docker exec <container_id> -it bash`
`docker exec <container_id> -it ls`
`docker exec <container_id> -it pwd`
`docker exec <container_id_2> -it bash`

4. Removing -it switch will make docker exec work, such as:
`docker exec <container_id> ls`
`docker exec <container_id> pwd`
`docker exec <container_id_2> ls`

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: ubuntu
ID: ZG25:KUIC:ZOFW:JXVD:SYRC:27B3:WLXE:XVS3:SKUC:MMON:77SH:S3TU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Host information: Ubuntu server 16.04.3 LTS in Oracle VirtualBox
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
**Docker debug log**
Following is attachment of docker debug log obtained by "journalctl -u docker.service"
[debuglog.txt](https://github.com/moby/moby/files/1625895/debuglog.txt)

** Update 01 **
1. restarting docker service or rebooting VM doesn't work, the only thing that work is reverting VM to earlier state
2. (About log file) docker debug mode is already enabled using /etc/docker/daemon.json

**Comment by cpuguy83** [comment]
"-it" goes before the container. After the container you need to put the command.

Thanks!

**Comment by d8888** [comment]
Thanks for kind help and sorry for novice mistake

**Comment by cpuguy83** [comment]
No worries!
