### ISSUE TITLE
How can we set net.ipv4.tcp_rmem/net.ipv4.tcp_wmem for containers in a swarm?

### ISSUE THREAD

**Issue by sbrattla** [moby/moby#35993]
We are seeing a lot of lost packets between 172.18.0.2 (on the docker_gwbrigde) and a memcached container. The 172.18.0.2 belongs to the ingress-sbox container.

Quite a bit of traffic goes through 172.18.0.2, and right now we suspect that `net.ipv4.tcp_rmem` and `net.ipv4.tcp_wmem` are too low. On the host, the default max was about 6MB which is far to low for the traffic being shuffled through this server.

I fail to see how we can change these settings for containers. From what I can read, Docker inherits the default settings when a container starts. That is, not the host settings, but the default settings. However, I'd really like to be proven wrong on this one.

Is there any way we can adjust `net.ipv4.tcp_wmem` or `net.ipv4.tcp_rmem` for Docker containers?

**Comment by cpuguy83** [comment]
It is not currently possible to change these via the API. One would have to exec into the container and update manually.
We are hoping to expose these configurations in the [entitlements API](https://github.com/moby/moby/issues/32801) #32801

I'm going to close this here, but feel free to discuss.
Thanks! 👼

**Comment by sbrattla** [comment]
@cpuguy83 how do we exec into the ingress-sbox container to update? I can't see how I should be able to make any modifications in that box, and even less how those changes would persist over time?

**Comment by cpuguy83** [comment]
@sbrattla Ah, I didn't pick up on the ingress part... this would not be handled by entitlements.
To configure kernel values on the ingress network you'll need to use either nsenter or iproute2 (or some other custom tooling).

With nsenter you can do `nsenter --net=/run/docker/netns/ingress_sbox` and just change the values as normal.
For iproute2, you'll need to bindmount /run/docker/netns/ingress_sbox to /run/netns/ingress_sbox and then you can do `ip netns exec ingress_sbox <command>`

Let me re-open, because indeed there doesn't seem to be a way to persist sysctl changes for the ingress network without some host job that does this on startup.

ping @fcrisciani

**Comment by sbrattla** [comment]
@cpuguy83 have I understood it correctly if I say that `net.ipv4.tcp_wmem` and `net.ipv4.tcp_rmem` can not be set for network namespaces?

This simple test fails :

```
docker run --sysctl net.ipv4.tcp_rmem=1 ubuntu:16.04 sysctl net.ipv4.tcp_rmem
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"open /proc/sys/net/ipv4/tcp_rmem: no such file or directory\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by cpuguy83** [comment]
@sbrattla This is dependent on the values that are available for the kernel. Docker (or runc, technically) is just setting the values in the proc filesystem, which is all provided by the kernel.

But indeed using `--sysctl` is how you would set the value for that specific container (or any container that shares the same network namespace).

**Comment by cpuguy83** [comment]
And indeed, it looks like those values are not namespaced... so you should be able to set it on the host and have it work for everything.

**Comment by sbrattla** [comment]
@cpuguy83 it seems that support for namspacing those variables [are on it's way](https://github.com/torvalds/linux/commit/356d1833b638bd465672aefeb71def3ab93fc17d), but until then we'll set it on the host. And as I understand it from you, these settings on the host should also apply to the containers.

**Comment by cpuguy83** [comment]
Yes, changing these on the host will change it for everything on the host until they are namespaced.

**Comment by sbrattla** [comment]
@cpuguy83 thanks for your help. I'll close this one as you've answered my question about how to set the variables in question.
