### ISSUE TITLE
cannot found cgroup mount destination

### ISSUE THREAD

**Issue by waotzi** [moby/moby#36016]
When i try to start an image i get the error:
```
Error response from daemon: cgroups: cannot found cgroup mount destination: unknown
```

i use void linux 64 bit

**Comment by mohitrajvardhan17** [comment]
Please let us know below mentioned details:
1. output of "docker version"
2. output of "docker info"
3. output of "uname -a"
4. The command you are trying to run
5. output of "docker image inspect [IMAGE_ID]"

**Comment by spaceywolfi** [comment]
1)
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   v17.11.0-ce
 Built:        Tue Nov 28 17:25:15 2017
 OS/Arch:      linux/amd64
 Experimental: false

2)
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 3
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.15_1
Operating System: void
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.584GiB
Name: omega
ID: R77L:ANHI:RBLQ:TZX5:BVCK:WMBU:IRGF:TMPI:G6DD:VUBD:DCMD:B5QB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

3)
Linux omega 4.13.15_1 #1 SMP PREEMPT Tue Nov 21 10:20:50 UTC 2017 x86_64 GNU/Linux

4) docker run -it node

5) this error happens with pretty much an image, the output of one of these images such as node is:
[
    {
        "Id": "sha256:c888d933885cd2b6ee630d31dc64104d0f5c402bbb9893acd50f8bb4bd285dfb",
        "RepoTags": [
            "node:latest"
        ],
        "RepoDigests": [
            "node@sha256:30f98963fd361b0241db107e68da88a1ebed0561e3ecc7bf221586901863e4b1"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-01-11T00:14:48.294649389Z",
        "Container": "6869d8e19b460976aced0c1eddfada6b59b08fe6ee74d363719e51c25fc82d18",
        "ContainerConfig": {
            "Hostname": "6869d8e19b46",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=9.4.0",
                "YARN_VERSION=1.3.2"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"node\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:613b20d380d175a92a6e8dbef307a677f3c8a7792e387b542da3307de0f5d34d",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.06.2-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=9.4.0",
                "YARN_VERSION=1.3.2"
            ],
            "Cmd": [
                "node"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:613b20d380d175a92a6e8dbef307a677f3c8a7792e387b542da3307de0f5d34d",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 676340940,
        "VirtualSize": 676340940,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/2c418b02404991456e777d3643375b2a2a59b65f00a6e79b271402cc3215cf1d/diff:/var/lib/docker/overlay2/ac7a875073dea2866e8c4eb16022bff39f1c6ab84ea9ac34ba4853a4451c0c36/diff:/var/lib/docker/overlay2/54fbc9b9ada2a57a0563046c3d7b070208f33b17b5635cf8828a0b530cc5b15b/diff:/var/lib/docker/overlay2/5c00c5d8e56b2d41f319b1ceacf4593b932716c665ac1acdd139c982da6b6b79/diff:/var/lib/docker/overlay2/bf97cba8f279e078f1a50f62049f526396c5891d0a50ab38e4f216561056ed15/diff:/var/lib/docker/overlay2/986071d88349a068a69e1da2e0d6132ec3f472ec24607b1afa185ed1802b34b9/diff:/var/lib/docker/overlay2/b9443707374a2250c1480626fe1b0281318d893d0a850d4604a8515410f5ce10/diff",
                "MergedDir": "/var/lib/docker/overlay2/27bbd97ca835944b38c8583435778b71272ea2be1e402a6fe9e4fa47fdf42080/merged",
                "UpperDir": "/var/lib/docker/overlay2/27bbd97ca835944b38c8583435778b71272ea2be1e402a6fe9e4fa47fdf42080/diff",
                "WorkDir": "/var/lib/docker/overlay2/27bbd97ca835944b38c8583435778b71272ea2be1e402a6fe9e4fa47fdf42080/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4bcdffd70da292293d059d2435c7056711fab2655f8b74f48ad0abe042b63687",
                "sha256:b9914afd042f489b84cfafa104175dd764d2ceeeef523e99b43044d8b224fdd0",
                "sha256:06b8d020c11b32eac35be52aab5197fe4c679f37dbb9bcd5a4342cee00a92199",
                "sha256:8fe6d5dcea4516a681465ce7eddd485ac2800fe4408d19ab447cfed1095f0149",
                "sha256:d4141af68ac4c5ac9d49ad35dc3ddcd0b2bd3c1af0729dde8e3413cb30fc76e4",
                "sha256:50599c766115e3c8e0c82f2344debe529f6995e990e33529254dbb013760cb56",
                "sha256:818281c5d4fb14c1e68a127ec363e1015d7f468dbfcc688c87fcd920fd19fe34",
                "sha256:cbe2c090ad213ddfdbf102974d9aef248f780a62f078293c4e3559582365cb27"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by jovrum** [comment]
Seems to be related to this: https://github.com/voidlinux/void-packages/issues/9811

**Comment by karlkfi** [comment]
Same error reported here: https://github.com/docker/for-linux/issues/219

**Comment by CpuID** [comment]
Hitting this issue now, seems to be twice in a day (reboot in between):

```
$ docker run -it --rm alpine:3.6 sh
docker: Error response from daemon: cgroups: cannot found cgroup mount destination: unknown.
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:	Mon Mar  5 20:42:27 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	402dd4a/17.12.0-ce
  Built:	Mon Mar  5 20:43:34 2018
  OS/Arch:	linux/amd64
  Experimental:	false
$ uname -a
Linux REDACTED 4.9.77-31.58.amzn1.x86_64 #1 SMP Thu Jan 18 22:15:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ docker info
Containers: 67
 Running: 10
 Paused: 0
 Stopped: 57
Images: 7457
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.77-31.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.22GiB
Name: REDACTED
ID: KOAA:6XDY:XI73:6BRO:RQLZ:ZJBW:6EBH:TCUS:JMT4:J4LA:POHH:6MLE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
$ docker image inspect alpine:3.6
[
    {
        "Id": "sha256:77144d8c6bdce9b97b6d5a900f1ab85da325fe8a0d1b0ba0bbff2609befa2dda",
        "RepoTags": [
            "alpine:3.6"
        ],
        "RepoDigests": [
            "alpine@sha256:3d44fa76c2c83ed9296e4508b436ff583397cac0f4bad85c2b4ecc193ddb5106"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-01-09T21:10:38.538173323Z",
        "Container": "2efef3010ea8e148e2906bc68e304f224ed30b1c7d93027957efc59ccd4b2f36",
        "ContainerConfig": {
            "Hostname": "2efef3010ea8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/sh\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:c963e0070003538e0fa6107eaff4effc05d11d9d01d7628c6a2ea21610fa8907",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "17.06.2-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:c963e0070003538e0fa6107eaff4effc05d11d9d01d7628c6a2ea21610fa8907",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 3965926,
        "VirtualSize": 3965926,
        "GraphDriver": {
            "Data": {
                "MergedDir": "/var/lib/docker/overlay2/08b1515eb8d6d6f0b61209659d53ee50b7586618696930ef685217f5f631354f/merged",
                "UpperDir": "/var/lib/docker/overlay2/08b1515eb8d6d6f0b61209659d53ee50b7586618696930ef685217f5f631354f/diff",
                "WorkDir": "/var/lib/docker/overlay2/08b1515eb8d6d6f0b61209659d53ee50b7586618696930ef685217f5f631354f/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:9dfa40a0da3b1a8a7c34abc596d81ede2dba4ecd5c0a7211086d6685da1ce6ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by jkbaseer** [comment]
Having the same issue too for last few days. 

Docker version
`Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
`

Docker info
`Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 15
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: SQSY:V7AZ:YNUU:C7UX:BQK5:GDQG:74X2:MGXM:FVL3:GBRM:CWBA:ZNHS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 39
 System Time: 2018-03-21T13:52:22.226945838Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`


output
`Darwin JK-Sierra.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

4. COMMAND am trying to do 
**mup deploy**


**Did anyone found the solution already ?**

**Comment by dinar-dalvi** [comment]
Same problem here

**Comment by dinar-dalvi** [comment]
Temp fix is 
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd

**Comment by jkbaseer** [comment]
Thanks a lot Dinar. Which exact location I should be doing this command? 

In my server or at the local meteor app folder or anywhere at my location?

**Comment by jimmy-rich** [comment]
@dinar-dalvi 

http://prntscr.com/ive2ma

Not works for me :( !

Thanks,

**Comment by dinar-dalvi** [comment]
I ran these on the vm that was causing the issue. Finally i decided to rebuild the vm and re-deploy docker and compose 1.20. After this no issues at all.

**Comment by jimmy-rich** [comment]
@dinar-dalvi 

Rebuild and use 1.20 Docker ?

**Comment by duyngq** [comment]
Work with temp solution as @dinar-dalvi. But, reboot will lose those configs. Need:
1. Force run those scripts at boot. OR
2. put the mount point in fstab.

This issue happens to everyone but there is no fix, :)

**Comment by dinar-dalvi** [comment]
I have mentioned my permanent fix earlier. Finally i decided to rebuild the vm and re-deploy docker and docker-compose 1.20. After this no issues at all.

**Comment by KillianKemps** [comment]
Hello, to fix this I installed the `cgroupfs-mount` package on the host.
For the context, I use Docker in Docker (in AWS CodeBuild) and I installed this package on the first Docker host because it had this issue using the other Docker container.

**Comment by obayesshelton** [comment]
Hi all,

I just had a very similar issue. I was on Azure, encrypted an OS disk and could see the disk but docker-compose would not run as I was mounting the host to the guest. I restarted the VM and it re-mounted the disk and it works again. I don't want to say it but turning it on and off might work in some cases. _Always worth a try_

**Comment by bsousaa** [comment]
This sounds like a packaging/OS issue. There is nothing we can do here.
