### ISSUE TITLE
Cannot mount tmpfs volumes on docker4mac

### ISSUE THREAD

**Issue by jsharpe** [moby/moby#36017]
**Description**

tmpfs volumes created via docker-compose fail to mount.

**Steps to reproduce the issue:**
1. create a container from docker-compose with a volume of type tmpfs

**Describe the results you received:**

ERROR: for app  Cannot start service app: Mounts denied: 
The paths /code/node_modules and /code/site-static and /code/bundles
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.

**Additional information you deem important (e.g. issue happens only occasionally):**

mount is defined in an override file rather than the main docker-compose file. Using version 3.2 of docker-compose file.

**Output of `docker version`:**

Docker version 17.12.0-ce, build c97c6d6

**Comment by thaJeztah** [comment]
Looks like you're trying to bind-mount a path from your host that's not shared with the Docker VM by default; Have you checked the link in that error message?

> By default, you can share files in `/Users/`, `/Volumes/`, `/private/`, and `/tmp` directly. To add or remove directory trees that are exported to Docker, use the File sharing tab in Docker preferences whale menu -> Preferences -> File sharing. (See [Preferences.](https://docs.docker.com/docker-for-mac/#preferences))

> All other paths used in -v bind mounts are sourced from the Moby Linux VM running the Docker containers, so arguments such as `-v /var/run/docker.sock:/var/run/docker.sock` should work as expected. If a macOS path is not shared and does not exist in the VM, an attempt to bind mount it will fail rather than create it in the VM. Paths that already exist in the VM and contain files are reserved by Docker and cannot be exported from macOS.

If that's not working as expected, please open an issue in the Docker for Mac issue tracker instead (https://github.com/docker/for-mac/issues)

I'm closing the issue here, because this doesn't look like a bug, or if there's a bug, it's specific to Docker for Mac, which is not maintained in this repository.

**Comment by jsharpe** [comment]
No I'm not trying to bind-mount a path from the host - I'm trying to specify that certain paths within the container should be tmpfs volumes because I'm bind mounting /code and want certain directories inside it to be ephemeral i.e. not be synced back to host. I'll open an issue in the docker for mac tracker as this used to work.

**Comment by thaJeztah** [comment]
What does your compose-file look like? This looks to work for me;

```yaml
version: "3.2"
services:
  app:
    image: nginx:alpine
    volumes:
      - type: tmpfs
        target: /code/node_modules
```

```bash
docker stack deploy -c docker-compose.yml foo 

Creating network foo_default
Creating service foo_app
```

```bash
docker service inspect --pretty foo_app

ID:		b6pmje49ns6fyzg3v3w6dnmxh
Name:		foo_app
Labels:
 com.docker.stack.image=nginx:alpine
 com.docker.stack.namespace=foo
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		nginx:alpine@sha256:c8ff0187cc75e1f5002c7ca9841cb191d33c4080f38140b9d6f07902ababbe66
Mounts:
  Target = /code/node_modules
   Source = 
   ReadOnly = false
   Type = tmpfs
Resources:
Networks: foo_default 
Endpoint Mode:	vip
```

**Comment by jsharpe** [comment]
Pretty much the same as you have created it, except I have a host mapped volume mounted at /code as well but that doesn't seem to make a difference. Interestingly it works with docker stack deploy but not docker-compose up.

**Comment by thaJeztah** [comment]
If it does not work with `docker-compose up`, then it may be a bug in Docker Compose

**Comment by jsharpe** [comment]
I'm inclined to agree. I've also seem the error manifest itself as a backtrace in docker-compose:
ERROR: for app  'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 959, in up
  File "compose/project.py", line 479, in up
  File "compose/parallel.py", line 80, in parallel_execute
AttributeError: 'NoneType' object has no attribute 'get'
Failed to execute script docker-compose

**Comment by thaJeztah** [comment]
Yes, may be worth opening an issue in https://github.com/docker/compose/issues
