### ISSUE TITLE
running px4 on rpi3 caused standard_init_linux.go:195: exec user process caused exec format error

### ISSUE THREAD

**Issue by jedichen121** [moby/moby#36022]
**Description**

I tried to run the px4 autopilot in a container on raspberry pi 3. However, every time I tried to build it shows 
`standard_init_linux.go:195: exec user process caused "exec format error"
`
I installed docker on raspbian using the convenience script and downloaded the source code for px4 from their official website. I tried to build it using the provided helper script. https://dev.px4.io/en/test_and_ci/docker.html

**Steps to reproduce the issue:** 
just following the guide on px4 official website
1. mkdir src
2. cd src
3. git clone https://github.com/PX4/Firmware.git
4. cd Firmware
5. sudo ./Tools/docker_run.sh 'make posix_rpi_native'

The command 'make posix_rpi_native' is for rpi native build, which can be found here. https://dev.px4.io/en/setup/building_px4.html

**Describe the results you received:**

The output of the command is:
```
guessing PX4_DOCKER_REPO based on input
PX4_DOCKER_REPO: px4io/px4-dev-raspi:2017-12-30
standard_init_linux.go:195: exec user process caused "exec format error"
```

**Describe the results you expected:**
I hope the build can finish with success. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Running `docker images` it shows the correct container has been downloaded:

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
px4io/px4-dev-base        latest              0787831f3c53        12 days ago         695MB
px4io/px4-dev-raspi       2017-12-30          67f37542d7bf        2 weeks ago         969MB
python                    2.7-slim            957faace74fa        4 weeks ago         124MB
hello-world               latest              75280d40a50b        7 weeks ago         1.69kB
px4io/px4-dev-nuttx       2017-10-23          eb7bfffbcfb0        2 months ago        1.17GB
```

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:25:15 2018
 OS/Arch:	linux/arm
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:21:22 2018
  OS/Arch:	linux/arm
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 11
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.65-rt57-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 927.3MiB
Name: raspberrypi
ID: L2SN:3DEE:FHCX:K3SA:DMHD:3KLR:Z4TE:UB4R:GMZM:VYTW:STDS:LOPG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jedichen121
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by arm64b** [comment]
Your system is linux/arm, but the `px4io/px4-dev-raspi` image is linux/amd64, so "exec format error" 👺

**Comment by thaJeztah** [comment]
Yup that won't work if the image is for a different architecture.


Let me go ahead and close this issue, but feel free to continue the conversation :+1:

**Comment by jedichen121** [comment]
Hi Dennis, thank you for pointing out the problem. But can you tell me how did you find out the `px4io/px4-dev-raspi` is for amd64? From its Dockerfile all I can find is it is based on `px4io/px4-dev-base`, which is based on `ubuntu:xenial`. But `ubuntu:xenial` supports `arm32v7`. Thank you very much.

**Comment by arm64b** [comment]
Hello @jedichen121 you can either `docker inspect px4io/px4-dev-raspi | grep Architecture` or `docker manifest inspect px4io/px4-dev-raspi` to find the arch information for those images 😄
