### ISSUE TITLE
Dockerfile "ENV <key> <value>" unexpectedly removes quotes

### ISSUE THREAD

**Issue by JoshuaSjoding** [moby/moby#36027]
**Description**

When using `ENV` in the form `ENV <key> <value>` both single and double quotes are being
stripped from `<value>`.

According to [the documentation](https://docs.docker.com/engine/reference/builder/#env):

> The `ENV` instruction has two forms. The first form, `ENV <key> <value>`, will set a single variable to a value. The entire string after the first space will be treated as the `<value>` - including characters such as spaces and quotes.

I'm seeing double and single quotes being stripped from entries such as these:

```
ENV DQUOTE One "two two" three four
ENV SQUOTE One 'two two' three four
```

Backslashes are also being interpreted:

```
ENV SBACKSLASH One two\ two three four
ENV DBACKSLASH One two\\ two three four
```

**Steps to reproduce the issue:**

1. `git clone git@github.com:gentlemanautomaton/docker-env-quote-test.git`
2. `cd docker-env-quote-test`
3. `docker build -t gentlemanautomaton/docker-env-quote-test:latest .`
4. `docker inspect gentlemanautomaton/docker-env-quote-test:latest`

**Describe the results you received:**

```
"Env": [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
	"DQUOTE=One two two three four",
	"SQUOTE=One two two three four",
	"SBACKSLASH=One two two three four",
	"DBACKSLASH=One two\\ two three four",
	"BACKTICK=One `two two` three four"
],
```

**Describe the results you expected:**

```
"Env": [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
	"DQUOTE=One \"two two\" three four",
	"SQUOTE=One 'two two' three four",
	"SBACKSLASH=One two\\ two three four",
	"DBACKSLASH=One two\\\\ two three four",
	"BACKTICK=One `two two` three four"
],
```

**Additional information you deem important (e.g. issue happens only occasionally):**

In the hope that it's useful, I created a test `Dockerfile` for reproduction in this repo:

* https://github.com/gentlemanautomaton/docker-env-quote-test

**Output of `docker version`:**

```
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:13:21 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:11:47 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 361
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-25-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.47GiB
Name: REDACTED
ID: SVWR:PGRT:4NZT:KVIT:DVBE:EKDI:GG2T:46U2:5PEW:X4UL:LGQZ:SEL4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The test was performed with `docker-ce` running on physical hardware.

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like something is a bit greedy parsing those; perhaps the code that also does env-var expansion?

ping @duglin @simonferquel PTAL

**Comment by yongtang** [comment]
Added a PR #36037 for the fix.

**Comment by dnephin** [comment]
I think the results you received are correct. The value of ENV is interpreted by the shell, so if you want quotes they need to be escaped or double quotes in single quotes.

**Comment by JoshuaSjoding** [comment]
> I think the results you received are correct. The value of ENV is interpreted by the shell, so if you want quotes they need to be escaped or double quotes in single quotes.
> 
> However, it does look like we need to correct the docs here https://docs.docker.com/engine/reference/builder/#env

Ah, so the only intended difference between the first and second forms is support for multiple declarations? Certainly the docs need to be updated if that's the case.

My [use case](https://github.com/gentlemanautomaton/cmdhook/tree/ff0488cd07f6ceaa7a27c14523cdfda9f3001a5b), which is admittedly esoteric, would have benefitted from the old rules. In [this example](https://github.com/scjalliance/asterisk/blob/d9c1c50607c8cf95eb868e783f5655363e1e3b1c/release/standard/Dockerfile#L59) you can see I'm using the second form; it's just more of a pain to get the quotes in quotes in quotes correct.

**Comment by thaJeztah** [comment]
I seemed to recall this was actually the behaviour (i.e., `ENV` just taking anything as value, no parsing/handling at all). Trying to see if this changed, I built this image in various docker versions;

```
docker build -t foo -<<'EOF'
FROM scratch
ENV DQUOTE One "two two" three four
ENV SQUOTE One 'two two' three four
ENV SBACKSLASH One two\ two three four
ENV DBACKSLASH One two\\ two three four
EOF
```

Here's the result;

docker 1.7:

```
"Env": [
    "DQUOTE=One two two three four",
    "SQUOTE=One two two three four",
    "SBACKSLASH=One two two three four",
    "DBACKSLASH=One two\\ two three four"
],
```

docker 1.6

```
"Env": [
    "DQUOTE=One two two three four",
    "SQUOTE=One two two three four",
    "SBACKSLASH=One two two three four",
    "DBACKSLASH=One two\\ two three four"
],
```


docker 1.5.0

```
"Env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "DQUOTE=One \"two two\" three four",
    "SQUOTE=One 'two two' three four",
    "SBACKSLASH=One two\\ two three four",
    "DBACKSLASH=One two\\\\ two three four"
],
```

docker 1.4.1


```
"Env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "DQUOTE=One \"two two\" three four",
    "SQUOTE=One 'two two' three four",
    "SBACKSLASH=One two\\ two three four",
    "DBACKSLASH=One two\\\\ two three four"
],
```


docker 1.3.3

```
"Env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "DQUOTE=One \"two two\" three four",
    "SQUOTE=One 'two two' three four",
    "SBACKSLASH=One two\\ two three four",
    "DBACKSLASH=One two\\\\ two three four"
],
```

So, looks like this behaviour changed between docker 1.5.0 and 1.6; possibly to make it act more like how environment variables are set in a shell (but still a change).

1.6 is a long time ago, so I agree we should not change back the behaviour, but better update the docs.
