### ISSUE TITLE
Question, how safe is dockerd with an unexpected SIGKILL?

### ISSUE THREAD

**Issue by pauldotknopf** [moby/moby#36023]
1. What if an image is being pulled from DockerHub?
2. What about layers?
2. What if a ```docker commit``` is in mid-execution?

How are things kept transactional, if at all?

**Comment by cpuguy83** [comment]
@pauldotknopf There's always the likelihood that something is not transactional, and certainly I know of a couple of minor things as is today.

> What if an image is being pulled from DockerHub?

The actual ingestion into the layer store is transactional, however there could be a potential for leaked data such that there could be a new graphdriver layer created with partial data in it, but this would go unused, or potentially there could be partial layer blobs on disk in `/var/lib/docker/tmp`.

**note**: layers are stored based on their content address (this is the "layer store") and then extracted into the graphdriver, if extraction fails or is incomplete then the layer is never actually ingested into the layer store.

> What about layers?

See above answer

> What if a docker commit is in mid-execution?

In this case, an interrupted `pull` and `commit` would yield the same result as it's basically the same operation, just that the source of the data is different.

**Comment by cpuguy83** [comment]
I'm going to close this since it's not really an issue.

For questions like this it may be easier to answer via the community slack or something other than the bug tracker.
Thanks! 😇
