### ISSUE TITLE
docker exec does not terminate process

### ISSUE THREAD

**Issue by vglushak** [moby/moby#36029]
**Description**

After update to 17.12.0-ce-mac47 (21805) version, `docker exec -t` doesn't terminate container's process.

**Steps to reproduce the issue:**
1. Run `docker exec -t <img> ps`

**Describe the results you received:**
It displays list of processes but does not close the session. 

**Describe the results you expected:**
Process should be terminated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 14.67GiB
Name: linuxkit-025000000001
ID: AWH6:LQFH:CR2X:GNQJ:RFHM:EXIL:7CVX:C7C5:2GCS:GSBA:FVLC:J75F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 69
 System Time: 2018-01-16T13:16:07.032469044Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local macbook.
 System Version:	macOS 10.13.2 (17C88)
  Kernel Version:	Darwin 17.3.0
  Boot Volume:	Macintosh HDD

**Comment by ripcurld0** [comment]
Failed to reproduce it on `Fedora:27`, `Docker 17.12.0-ce`.
@thaJeztah should we move it to https://github.com/docker/for-mac?

**Comment by thaJeztah** [comment]
I'm not able to reproduce on Docker for Mac as well (but admittedly, I'm on Docker for Mac 18.01-dev)

**Comment by ripcurld0** [comment]
@vglushak can you provide more description.
What do you mean by "not terminate process"? Is `docker exec -t ...` hanging?

Thanks.

**Comment by vglushak** [comment]
@ripcurld0  - correct - it's hanging. Process doesn't finish.
