### ISSUE TITLE
***/v1/_ping: Forbidden port during private registry deployment

### ISSUE THREAD

**Issue by Davidrjx** [moby/moby#36046]
**Description**

when pushing sample image into local private registry,
(1) at this time, console immediately output "Get https://my_custome_domain:5000/v1/_ping: Forbidden port"
(2）curl verification output "curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol", that seemed version compatibility issue by curl https://my_custome_domain:5000/v1/_ping
"" 

**Steps to reproduce the issue:**
1. refer to tutorial from https://docs.docker.com/registry/insecure/#use-self-signed-certificates
2.  direct to "Use self-signed certificates" section
3. test push image to the registry

**Describe the results you expected:**
pushing and pulling image normally from the local private registry

**Additional information you deem important (e.g. issue happens only occasionally):**
 multiple attempts from registry image with different versions(2,2.6), some kind of errors occurred:
(1)
![image](https://user-images.githubusercontent.com/4284791/35077829-1012419a-fc3a-11e7-9418-00c0b98b4203.png)
(2)
![image](https://user-images.githubusercontent.com/4284791/35077840-17b4eda8-fc3a-11e7-9a0d-26a4ac03321c.png)
(3) here currently issued error as a third

otherwise, also  i had issued (2) at https://github.com/docker/distribution where @stevvooe mentioned that v1 is not supported for that i was not very clear

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 79
 Running: 26
 Paused: 0
 Stopped: 53
Images: 33
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.8 GiB
Name: hostname
ID: BUFZ:Z7DA:TKQY:C2MY:QRD7:GSEB:SQUJ:PFXS:YL3L:EOAB:JCUX:P7T5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://****:port/
Https Proxy: http://***:port/
No Proxy: localhost,***,m1empwb1.mirror.aliyuncs.com,docker.io,registry.cn-hangzhou.aliyuncs.com
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
unknown

**Comment by Erically** [comment]
helo,resolve this problem?

**Comment by krichter722** [comment]
I experienced with problem with 19.03.5 on Windows and an upgrade to 20.10.9 fixed the problem. I guess the versions and OS don't really matter, 19.03.5 was 2 years old at the time of the issue and CA chain can break over time. That's why updates are released and recommended to be installed.

**Comment by Davidrjx** [comment]
@krichter722 nice and thanks

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
