### ISSUE TITLE
docker stack deploy from Travis aborts with EOF error

### ISSUE THREAD

**Issue by mklinke** [moby/moby#36041]
**Description**

We are running a build job on Travis CI to deploy a stack to a Docker swarm running on hosted servers and connected to Docker Cloud. Before each deployment, the job removes the existing stack and sleeps for 5 seconds to wait for the "cleanup" within the swarm.

**Steps to reproduce the issue:**
The build job does the following things and has a few variables for reasons of security and dynamic deployment of different branches: 

0. `docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u $DOCKER_USER -p $DOCKER_PW $DOCKER_SWARM`
1. `DOCKER_HOST=tcp://127.0.0.1:32768 docker stack rm $BRANCH`
2. `sleep 5;`
3. `DOCKER_HOST=tcp://127.0.0.1:32768 docker stack deploy -c $STACK_FILE --with-registry-auth $BRANCH`

**Describe the results you received:**

```
5.73s$ docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u $DOCKER_USER -p $DOCKER_PW $DOCKER_SWARM
Unable to find image 'dockercloud/client:latest' locally
latest: Pulling from dockercloud/client
90f4dba627d6: Pulling fs layer
9ce3e514b7fa: Pulling fs layer
ca5f3b3b0b8e: Pulling fs layer
19aaa36bba7a: Pulling fs layer
19aaa36bba7a: Waiting
90f4dba627d6: Download complete
9ce3e514b7fa: Verifying Checksum
9ce3e514b7fa: Download complete
ca5f3b3b0b8e: Verifying Checksum
ca5f3b3b0b8e: Download complete
90f4dba627d6: Pull complete
19aaa36bba7a: Verifying Checksum
19aaa36bba7a: Download complete
9ce3e514b7fa: Pull complete
ca5f3b3b0b8e: Pull complete
19aaa36bba7a: Pull complete
Digest: sha256:82aecd2129328607804855503ec5407c337aba33b0baa0a2f82adaae73eb1cc7
Status: Downloaded newer image for dockercloud/client:latest
=> You can now start using the swarm xyz by executing:
	export DOCKER_HOST=tcp://127.0.0.1:32768
The command "docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u $DOCKER_USER -p $DOCKER_PW $DOCKER_SWARM" exited with 0.
12.03s$ DOCKER_HOST=tcp://127.0.0.1:32768 docker stack rm $BRANCH
Removing service [... currently 14 services]
The command "DOCKER_HOST=tcp://127.0.0.1:32768 docker stack rm $BRANCH" exited with 0.
5.01s$ sleep 5;
The command "sleep 5;" exited with 0.
45.94s$ DOCKER_HOST=tcp://127.0.0.1:32768 docker stack deploy -c $STACK_FILE --with-registry-auth $BRANCH
Creating network develop_default
Creating service [10 or 11 of the 14 services are created before the following message occurs...]
failed to create service develop_someservice: error during connect: Post http://127.0.0.1:32768/v1.32/services/create: EOF
```

**Describe the results you expected:**
I'd expect all services to be created as usual. The error does not occur when I execute the same commands from a terminal on my machine.

**Additional information you deem important (e.g. issue happens only occasionally):**
It seems to be working better with a clean swarm and becomes worse with multiple stacks/repeated deployment.

**Output of `docker version`:**
Travis: docker-ce (18.01.0~ce-0~ubuntu)
Docker Swarm Node:
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
````

**Output of `docker info`:**
(Didn't deem info from Travis important but can add it if requested.)
Docker Swarm Node:
```
Containers: 6030
 Running: 19
 Paused: 0
 Stopped: 6011
Images: 191
Server Version: 17.09.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12612
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 9yf2i4u0g4t3xucbc23sskw4l
 Is Manager: true
 ClusterID: 1yjg9zwx44ykzz4xxa5n3n2ap
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 1
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 188.68.34.232
 Manager Addresses:
  185.183.157.146:2377
  188.68.34.232:2377
  37.120.185.24:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73GiB
Name: v22017084873852584
ID: BHUF:4454:QQPM:FUV7:WN2I:TQH4:ZHFR:2NVT:FVLP:B5LY:GKFR:Y3W5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mklinkexavo
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Can you get logs from the daemon?

**Comment by mklinke** [comment]
@cpuguy83 Before I start looking for how to access all the logs, which ones would be most helpful? Are there logs on the client or just the ones from one or all of the swarm nodes?

**Comment by cpuguy83** [comment]
Just the node you connect to that got the EOF.

**Comment by mklinke** [comment]
AFAIK, I am not connecting to a specific node directly, rather the dockercloud client connects with the Docker Cloud that is again connected to the swarm. The swarm consists of three nodes all of them being  both manager and worker nodes. I'll try to grab the logs of the nodes the next time I see the error. The logs are pretty huge and I couldn't see a direct relation myself.

**Comment by cpuguy83** [comment]
Oh right... so it could be even the dockercloud client that's messing up.... which is much more plausible in my experience with that...

**Comment by mklinke** [comment]
@cpuguy83 I see, do you have any more pointers on how to continue investigating this issue? Any logs from the dockercloud/client maybe? So I'd probably have to look at the logs of the respective container in the Travis job...

**Comment by cpuguy83** [comment]
Yes, logs from the client (and potentially the server) would hopefully point at something good.

**Comment by mklinke** [comment]
Please see [here](https://www.dropbox.com/s/e4660uozqvs37xz/docker-swarm-logs.zip?dl=0) for the server logs (link is valid for 7 days). The issue happened at around 11 AM. Couldn't get hold of the client logs yet...

**Comment by mklinke** [comment]
The logs of the client-proxy are not too verbose... I just had travis output the logs after the (failing) docker stack deploy call: 
```
$ DOCKER_HOST=tcp://127.0.0.1:32768 docker stack deploy -c $STACK_FILE --with-registry-auth $BRANCH
Creating network develop_default
Creating service develop_doc
Creating service develop_eventlog
Creating service develop_xps-proxy
Creating service develop_inventory
Creating service develop_elasticsearch1
Creating service develop_web
Creating service develop_request
Creating service develop_excelimport
Creating service develop_notification
Creating service develop_elasticpublisher
Creating service develop_messagequeue
Creating service develop_masterdata
Creating service develop_auth
Creating service develop_execution
failed to create service develop_execution: error during connect: Post http://127.0.0.1:32768/v1.35/services/create: EOF
The command "DOCKER_HOST=tcp://127.0.0.1:32768 docker stack deploy -c $STACK_FILE --with-registry-auth $BRANCH" exited with 1.

$ docker logs client_proxy_xavoteam_netcup
INFO[0000] Listens to tcp socket: :2375                 
INFO[0064] error copying request to target: http: invalid Read on closed Body 
```

**Comment by mklinke** [comment]
Additionally, we see https://github.com/moby/moby/issues/31169 as soon as this error occurs. It happens when deploying from Travis via the dockercloud-client. It does not happen when performing the same stack deploy command from the Docker for Windows command line.

**Comment by thaJeztah** [comment]
@mklinke are you still having this issue?

**Comment by thaJeztah** [comment]
closing, as this one went stale
