### ISSUE TITLE
docker exec hangs instead of exiting

### ISSUE THREAD

**Issue by lukemarsden** [moby/moby#36048]
## Symptom

I have some docker-in-docker containers (based on [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster)) as part of a CI system where, with Docker 17.12-ce:

```
$ docker exec -ti <container> echo hello
hello
<hang>
```

By `<hang>`, I mean that control is not returned to the original terminal. This in turn causes our CI to hang.

## Reproducibility

This started happening after tens of such containers were created, run and destroyed.

Once the system gets into this state, it does not recover, i.e. further `docker exec`s into affected containers will hang in a similar way.

The same `docker exec` on the same setup on Docker 17.06-ce does not cause hangs, which seems to be working more reliably.

## Context

This is on Ubuntu 17.10 on a fast dedicated server from OVH.

I downgraded the system which was experiencing this issue to Docker 17.06, which is now in production as a CI runner, so it will be a bit of work to reproduce it (would have to set up a brand new machine and try to reproduce the issue there).

cc @justincormack who requested this issue

**Comment by lukemarsden** [comment]
Possibly related to https://github.com/moby/moby/issues/36010?

**Comment by ripcurld0** [comment]
I think it's actually a duplication of #36029

**Comment by justincormack** [comment]
@lukemarsden can you `strace` and see if it is blocked on same `openat` as #36010?
