### ISSUE TITLE
dns resolver not work inside container after restart

### ISSUE THREAD

**Issue by jinuxstyle** [moby/moby#36057]
The issue is about dns resolver on user-defined networks. The embedded dns resolver could not work after containers running for a while and restarted. It's a critical and annoying issue in our use case. I already posted the issue on libnetwork community, but received no response yet. Hope posting here could draw more attention for this issue.

For full description of this issue, please open: https://github.com/docker/libnetwork/issues/2049

**Comment by cpuguy83** [comment]
Closing here since there seems to be some discussion on the libnetwork issue now.

Note that your version of Docker is relatively old and there have been lots of fixes with networking and discovery since.

Thanks!
