### ISSUE TITLE
Docker builds hanging / stuck

### ISSUE THREAD

**Issue by jamesongithub** [moby/moby#36067]
**Description**
Seeing a log of docker builds hanging getting stuck on our build servers. Usually we have to abort the build and retry to finish. I'd say it occurs like 30-40% of the time.

**Steps to reproduce the issue:**
1. Build dockerfiles 

**Describe the results you received:**
Docker builds hangs at random steps in the docker files.

**Describe the results you expected:**
Not hangs / stuck. Should be some progression

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1038-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.44GiB
Name: REDACT
ID:REDACT
Docker Root Dir: REDACT
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
You have new mail in /var/mail/root
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          10.30    0.00    1.62    1.15    0.06   86.87

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
xvda             51.79       339.41       130.52 1016225952  390792820
xvdf             59.48       312.86      2475.48  936718978 7411742899
xvdg             58.64       305.83      2461.55  915688216 7370052656
xvdh              6.40        36.41        45.53  109020183  136306212
md0             258.44       618.69      4937.03 1852392345 14781795439
dm-0            228.80       618.69      4937.03 1852389639 14781795308
```

![screen shot 2018-01-19 at 4 03 59 pm](https://user-images.githubusercontent.com/4452738/35177175-659a6734-fd32-11e7-925f-b906605909c2.png)
![screen shot 2018-01-19 at 4 04 24 pm](https://user-images.githubusercontent.com/4452738/35177189-7427ce9a-fd32-11e7-9949-0c9e6536b123.png)
![screen shot 2018-01-19 at 4 04 31 pm](https://user-images.githubusercontent.com/4452738/35177194-77326c76-fd32-11e7-869d-2debb148c24d.png)

[goroutine-stacks-2018-01-19T195425Z.log](https://github.com/moby/moby/files/1648304/goroutine-stacks-2018-01-19T195425Z.log)
[goroutine-stacks-2018-01-19T195504Z.log](https://github.com/moby/moby/files/1648305/goroutine-stacks-2018-01-19T195504Z.log)
[goroutine-stacks-2018-01-19T235743Z.log](https://github.com/moby/moby/files/1648306/goroutine-stacks-2018-01-19T235743Z.log)

**Comment by jamesongithub** [comment]
any idea @cpuguy83? we used to see this issue on devmapper, but somehow it's back on even on overlay2.

@thaJeztah is there any troubleshooting we can do? or some kind of workaround?

**Comment by cpuguy83** [comment]
We're tracking an issue with runc that has cropped up recently... the bug *should* have been there forever but it's only recently surfaced... could be due to recent kernel changes.

This patch appears to resolve it (if indeed this is what you are hitting): https://github.com/opencontainers/runc/pull/1698

Looks like all 3 of your goroutine stacks are waiting for the I/O streams from an attach to close.

**Comment by cpuguy83** [comment]
Not sure if you are up for putting in a patched runc to test, but it may help.

**Comment by jamesongithub** [comment]
If it helps, will give it a shot. Not familiar w/ docker enough on how to use the patch.

We're just using the standard ubuntu package install. Is it just compile runc with the patch and symlink it as `docker-runc`. Will it work with 17.06?

**Comment by cpuguy83** [comment]
🤞 That should do it.

**Comment by cpuguy83** [comment]
At least for a test, anyway.

**Comment by dazinator** [comment]
Sorry I can't be of much use but just wanted to say I am seeing this a lot with out docker builds on a team city build agent, running on windows server core. The appears to finish its last step successfully, but hangs at that point.

**Comment by thaJeztah** [comment]
@dazinator native Windows containers don't use runc as runtime, so what you're seeing is very likely a different issue; feel free to open a new ticket though if you have more details (logs, steps to reproduce, details about your setup).

**Comment by thaJeztah** [comment]
@jamesongithub  looks like this issue went stale; also note that Docker 17.06 CE reached end of life in September last year; current versions of Docker should have the patch that was discussed above, so if you're still running into this, it may be worth trying a current version of Docker (also; for build - Docker 18.06 has experimental support for buildkit; which is really great, and worth a spin!)

I'll close this issue because of the above, but feel free to continue the conversation
