### ISSUE TITLE
How to Install docker when there is no overlayFS

### ISSUE THREAD

**Issue by heinrich-k** [moby/moby#36062]
I run ubuntu in a virtual server environment provided to me by my hoster.
Docker fails to start as a service, due to the error:
level=error msg="'overlay' not found as a supported filesyst
level=error msg="'overlay' not found as a supported filesyst
level=info msg="Graph migration to content-addressability to
level=warning msg="Your kernel does not support oom control"
level=warning msg="Your kernel does not support memory swapp
level=warning msg="Your kernel does not support kernel memor
level=warning msg="Unable to find cpu cgroup in mounts"
level=warning msg="Unable to find cpuset cgroup in mounts"

My guess is, that this is due to the fact, that the server is a virtual one. 
So, where would I find a way to disable dockers need for OverlayFS?
Or is it essential ?

**Comment by AkihiroSuda** [comment]
You could use `--storage-driver vfs`, but note that your "virtual server environment" (I suppose OpenVZ) is unlikely to be supported.

If you are using OpenVZ, this page might be useful: https://openvz.org/Docker_inside_CT_vz7
