### ISSUE TITLE
Update API docs to show that /containers/{id}/kill returns HTTP 409

### ISSUE THREAD

**Issue by joaofnfernandes** [moby/moby#36068]
**Description**

The [API docs](https://docs.docker.com/engine/api/v1.35/#operation/ContainerKill) for `containers/{id}/kill` say that this endpoint returns one of there HTTP error codes: 204, 404, 500.

But if you try to invoke this endpoint on a container with `exited` status, the API returns HTTP 409.

**Steps to reproduce the issue:**

```
# Container is created and exits. Then we try to send it a signal
curl --unix-socket /var/run/docker.sock -X POST http://localhost/containers/"$(docker run -d alpine echo 'hello'; sleep 1)"/kill -I


HTTP/1.1 409 Conflict
Api-Version: 1.32
Content-Length: 193
Content-Type: application/json
Date: Sat, 20 Jan 2018 00:48:13 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/17.09.1-ce (linux)
```

**Describe the results you expected:**
Expected this HTTP error code to be documented in the API docs.

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by shutefan** [comment]
@joaofnfernandes Thanks for creating the issue in the correct repository! I've opened a PR.
