### ISSUE TITLE
unauthorized: authentication required 

### ISSUE THREAD

**Issue by eliassal** [moby/moby#36071]
**Description**

I have docker on win10 since 1a nd a half year which was working fine. Since 1 week, whenever I try something like 
`docker pull microsoft/aspnet, I get
`

> Sending build context to Docker daemon  24.06kB
> Step 1/7 : FROM microsoft/aspnet
> latest: Pulling from microsoft/aspnet
> 3889bb8d808b: Downloading [=====>                                             ]    446MB/4.07GB
> 449343c9d7e2: Downloading [=================>                                 ]  445.9MB/1.304GB
> ccd8f322a2de: Download complete
> 5358f1f8c04f: Download complete
> ....
> ...
> b53cc298d0b7: Waiting
> **unauthorized: authentication required**
> 
> 

I opened a thread at https://github.com/Microsoft/aspnet-docker/issues/86#issuecomment-358993520
By the end of the day, we discovered that it is related to docker itself. We all think that Docker for windows is corrupt and I think personally that it is related to the several updates since 1 year. I did a new fresh Docker for win10 setup on a nother machine and everything went through so we are sure that the issue has nothing to do with the image. Any idea why this is happening.
In any case, while waiting for a réponse, I will remove and reinstall

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by eliassal** [comment]
I did a clean setup, removed Docker for windows, deleted all related data, reinstalled getting the exact same error.
Any idea please

**Comment by eliassal** [comment]
Doing 

> docker pull microsoft/nanoserver


works fine without any issue

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
