### ISSUE TITLE
Move MobyLinuxVM.vhdx to another drive

### ISSUE THREAD

**Issue by eliassal** [moby/moby#36073]
Is it possible to move MobyLinuxVM.vhdx to another drive, I clicked on settings > Advanced, changed to a new directory on a another drive, clicked apply, Docker for windows revert back to 

> C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx

**Steps to reproduce the issue:**
1.Right Click the whale, chose advanced
2.browse to another directory, for example E:\docker
3.Hit apply
4. Docker for windows revert back to the 1st directory and starts

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Looks like this is a feature request for Docker for Windows, which has its own issue tracker; can you reopen this over there? https://github.com/docker/for-win/issues

I'll close this issue here

**Comment by eliassal** [comment]
Done
