### ISSUE TITLE
The created time is null while inspect the network

### ISSUE THREAD

**Issue by wangxf1987** [moby/moby#36083]
**Description**
The created time is null while inspect the network

**Steps to reproduce the issue:**
1.  Create Macvlan network config -> pass
2. Create Network network -> pass
3. Inspect the network and the created time is null

**Describe the results you received:**
The created time is null while inspect the network

**Describe the results you expected:**
The created time is normal while inspect the network

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Server Version: 17.06.0-ce.5.sn
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.06.0-ce.5.sn
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: 10.47.3.252:5000/macvlan-plugin:1.0.0 bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: pwwuc2xkn63o7w57d66c89vbk
 Is Manager: true
 ClusterID: cvqvvb9jzimz4zhmbe3t8e5wl
 Managers: 3
 Nodes: 21
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.47.0.1
 Manager Addresses:
  10.47.0.1:2377
  10.47.0.2:2377
  10.47.0.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6GiB
Name: xzds01m010047000001
ID: QHUA:UF5V:M7BZ:MOZS:JPYQ:MSFN:MDQY:HDAF:XHVF:JMYK:JU5C:N3PK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.37.210.4:5000
 10.47.3.252:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by yongtang** [comment]
@wangxf1987 I played with the current master branch but was not able to reproduce. Would you mind sharing your detailed steps for the issue you encounter?

**Comment by wangxf1987** [comment]
@yongtang yes, I'd like to. The docker engine version is 17.06.01, and we use the macvlan network.
** Steps **
1. Create network using the follow command:
    `#docker network create -d macvlan \`
    `--subnet 192.168.188.0/24 \`
   `--gateway 192.168.188.254 \`
`--ip-range 192.168.188.0/24 \`
`--scope swarm \`
`-o parent=eth0.3809 \`
`test_net`

2. Restart the docker service
`systemctl restart docker`

3. Check the network information
`docker network inspect <network-id>`

4. and the result that show the timestamp is zero.

**Comment by yongtang** [comment]
Added a PR #36095 for the fix.
