### ISSUE TITLE
Allow bind mounting to container's root (/)

### ISSUE THREAD

**Issue by mitar** [moby/moby#36082]
I would like to request a new feature. Currently, if I try to mount (type bind) a directory to a root (`/`) of a container, I get an error that I cannot do that. But I find this a very useful approach to move legacy virtual machines and OpenVZ containers to Docker. I can just copy their contents to a directory on a host and then mount it into an [empty Docker image](https://hub.docker.com/r/tozd/empty/). I use `/sbin/init` as a command and the old legacy system starts.

I know that this work well because currently I mounted each top-level directory separately. But this is error prone and unnecessary. It would be great if I could mount one directory to a root.

I understand that this diminishes a lot of things Docker ecosystem provides, but it is a great way to transition slowly legacy systems into Docker infrastructure.

**Comment by cpuguy83** [comment]
Why not build an image?

**Comment by mitar** [comment]
Because I would like that any changes anywhere inside the container are preserved in the mounted host directory. With image, if there are any changes, and container gets recreated, those changes will be lost.

**Comment by cpuguy83** [comment]
And volumes for the changes?

**Comment by mitar** [comment]
The point is that changes can be done anywhere, even in the root of the container. This is how system was designed before. It is for porting legacy systems which are not really maintained and which can potentially write anywhere.

**Comment by cpuguy83** [comment]
Then this is not a container. What's the purpose of a container that is not doing anything?

You can achieve isolation via other means.

**Comment by mitar** [comment]
I described that in the initial description of this feature request. This allows one to reuse the Docker infrastructure to migrate legacy systems.

> What's the purpose of a container that is not doing anything?

What do you mean it is not doing anything? It is isolating a legacy system in a standard way, looking from the outside. I can move the root volume and empty image anywhere and run it as a container and it just works.

There is only this artificial limitation of not being able to mount to `/` which is making this complicated.

**Comment by cpuguy83** [comment]
> Yes, but this is not how one would expect to use Docker container

You also aren't expected to provide your own rootfs :)

Removing this restriction from volumes is definitely a no go as at this point it's not a volume.
It sounds like what you really want to do is to tell docker to use some host path as a rootfs instead of an image. But again you can build an image from that rootfs to deal with this.

**Comment by mitar** [comment]
Ah, you are right. One should be able to define also `VOLUME /` then. :-)

But I thought Docker added `--mount` to extend what volumes provided. You can also `--mount` things which are not described as a volume, and also files, which are not directories (and volumes).

So there seems to already be a way to mount more than just volumes. So why not also allow mounting `/`?

**Comment by cpuguy83** [comment]
@mitar `--mount` didn't add any new functionality, just better defined and more predictable functionality.

**Comment by mitar** [comment]
You cannot mount a file into a Docker container using `--volume`. Maybe internally this was already possible before.

**Comment by cpuguy83** [comment]
> You cannot mount a file into a Docker container using --volume. Maybe internally this was already possible before.

You can, it just must exist on the host, otherwise docker will create a directory.
Otherwise we'd never be able to do `-v /var/run/docker.sock:/var/run/docker.sock`.

**Comment by mitar** [comment]
Hm, you are right. I got confused here. Thanks.

Anyway, I know this is a change, this is why it is a feature request. I think it makes it easier for us a lot. It works great for us having manually mounting each top-level directory. This is why I am bringing it up.

Wouldn't this be a completely backwards compatible change?

**Comment by cpuguy83** [comment]
> Wouldn't this be a completely backwards compatible change?

It's not a question of backwards compatibility, it's a question of design and support.
Hacking the functionality into bind mounts is just not right.

You mentioned that if you use an image and persist data into a container you don't get the normal expected workflow of containers... however I'd argue that the proposal is even much less the normal workflow.

**Comment by mitar** [comment]
> You mentioned that if you use an image and persist data into a container you don't get the normal expected workflow of containers

I do not get a normal flow for somebody maintaining our Docker infrastructure who just has to keep containers running. They then have to specially care about this particular container to never erase them.

> however I'd argue that the proposal is even much less the normal workflow.

It is same workflow for somebody running the container (run this image, mount this data at this path). Only how the container is designed by an author is slightly different (empty image, all image in one volume).

**Comment by thaJeztah** [comment]
I'll close this ticket, as I don't think we'll be implementing this, but perhaps you can achieve this by manually setting up your rootfs, and using runc.
