### ISSUE TITLE
docker filter error

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#36098]
docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

 docker ps --filter volume=/var/lib/docker/volumes/a603827705e42f1204ebd4ecce8d5e6cf3690423801fdd33c8fe3ecc23aaad33/_data
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

no respose!

docker inspect
{
                "Type": "volume",
                "Name": "a603827705e42f1204ebd4ecce8d5e6cf3690423801fdd33c8fe3ecc23aaad33",
                "Source": "/var/lib/docker/volumes/a603827705e42f1204ebd4ecce8d5e6cf3690423801fdd33c8fe3ecc23aaad33/_data",
                "Destination": "/opt/cni",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }

I guess maybe _data (Underline) lead to this err

**Comment by yongtang** [comment]
@timchenxiaoyu The version `1.13.0` is about 1 year old and there are many changes in volume management part. Have you tried to update to the latest versions? Also can you share the detailed `reproducible` steps about the issue you encountered?

**Comment by vdemeester** [comment]
@timchenxiaoyu I think the volume filtering is based on the name/id of the volume and not it's full path

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
