### ISSUE TITLE
Support in Docker Swarm for Apache Spark 2.3+ scheduling

### ISSUE THREAD

**Issue by sandys** [moby/moby#36101]
From Apache Spark 2.3 onwards, there is native support built in for scheduling based on docker. This is natively built for kubernetes, but the infrastructure leverages resources at the docker VM level. 

https://github.com/apache/spark/blob/master/docs/running-on-kubernetes.md

It would be awesome if Docker Swarm can also build support for acting as a spark scheduler. Since the rest of our infrastructure is on Swarm, we would want to continue to build spark on top of swarm rather than adopting kubernetes just for spark.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
