### ISSUE TITLE
Update copyright dates

### ISSUE THREAD

**Issue by thecodeboy** [moby/moby#36106]
Hello! The copyright dates in the license files need to be updated. May I create a pull request for the same?

Also, is the copyright holder still `Docker, Inc.` or should I change it to `Moby Project`.

**Comment by thaJeztah** [comment]
Yes, AFAIU, copyright year is not a requirement (but there are parties that disagreed with that, and recommend to still add a year). I think it's common to use the _start_ date as year for the copyright though.

I'd have to ask around to see if we can change the copyright holder to the "Moby authors" (e.g.)

**Comment by thecodeboy** [comment]
Kubernetes decided to keep the vanilla license without modifications. Here's the commit. https://5ly.me/P3C

**Comment by thaJeztah** [comment]
Yes, that's because that section in the License is actually a template that you can use to apply the license to files. Using that would require every file to have the license/notice added, e.g., see https://github.com/containerd/containerd/pull/2108
