### ISSUE TITLE
docker build auto pass proxy env vars

### ISSUE THREAD

**Issue by ericcurtin** [moby/moby#36102]
I have three env vars which can be different depending on the host I am on

ENV http_proxy
ENV https_proxy
ENV ftp_proxy

I need these env vars automatically passed from the docker host for building on hosts that require proxies set to access yum/apt repos. But on my automated build on docker hub I don't need the proxy.

This is a related issue but the suggested alternative solution doesn't solve it. This is a docker build-time issue, rather than a docker run-time one:

https://github.com/moby/moby/issues/22412

**Comment by cpuguy83** [comment]
@ericcurtin See `--build-arg` -- https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg

Thanks!

**Comment by ericcurtin** [comment]
Pity I've to type ~200 chars on my bash CLI to achieve this everytime. I've about 10 wrapper scripts I need in order to use docker efficiently. I can live with it, but it's not ideal.

**Comment by thaJeztah** [comment]
@ericcurtin on Docker 17.07 and up, you can set default proxy settings in the CLI configuration file (`~/.docker/config.json`) those settings will be applied both when starting a container (`docker run`) and during `docker build` (they will be automatically passed as `--build-arg`). This was implemented in this PR; https://github.com/docker/cli/pull/93 (also: https://github.com/moby/moby/pull/32966).

Having a similar configuration on the _daemon_ side is still being considered; see https://github.com/moby/moby/issues/30323 (contributions welcome)

**Comment by ericcurtin** [comment]
Thanks @thaJeztah sounds like exactly what I need!
