### ISSUE TITLE
False caching with docker:build from tar

### ISSUE THREAD

**Issue by guillaumerose** [moby/moby#36122]
**Description**

When creating a tarball by hand for docker build, if the path is in parent directory, build cache is never invalidated.

**Steps to reproduce the issue:**
1. Create a directory structure like this [parent.zip](https://github.com/moby/moby/files/1667460/parent.zip) : 
```
$ tree
.
├── build.json
└── child
    ├── Dockerfile
    └── Makefile
$  cat build.json
version1
$  cat child/Dockerfile
FROM alpine
COPY build.json /
RUN cat build.json
$ cat child/Makefile
all:
	tar cf - Dockerfile ../build.json | docker build -t child -
``` 
2. Run `make`
3. Change version in build.json
4.  Run `make`. There is a cache hit.

**Describe the results you received:**

The cache is used and the file not changed for the following steps

**Describe the results you expected:**

The file should not be cached.

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 41
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: K4IU:BYEJ:55LM:S3GN:MGG4:EWRW:BR2O:I5Z6:XB6K:WIMS:IMXT:STSK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 40
 System Time: 2018-01-26T10:41:17.898620973Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac

**Comment by guillaumerose** [comment]
Using gnutar, it works. Probably because of `gtar: Removing leading `../' from member names`

**Comment by thaJeztah** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
Not sure if we consider it expected. We could validate the tar and produce an error though for this case. The caching in the current version is based on tar headers and if it doesn't find the file I believe the behavior is to just uses its path. Changing the open code would not fix the actual issue as the tar headers would still be different and create a cache miss between different tars that extract in a similar way. Buildkit uses a different cache checksum scheme.

**Comment by guillaumerose** [comment]
Strangely, the COPY works perfectly. It's a little bit misleading. Should it fail?

**Comment by tonistiigi** [comment]
Yes, the ux definitely isn't great. The difference is that cache is based on tar data but copy works on the extracted files and there is protection from files not leaking out of parent on extraction.

**Comment by guillaumerose** [comment]
Thanks!
