### ISSUE TITLE
Failed to start Docker daemon  when configure a registry-mirror  address

### ISSUE THREAD

**Issue by hongxiaolu** [moby/moby#36128]
**Description**

When I configure a registry-mirror  address, Docker daemon does not work properly，as shown in the figure：

<img width="500" alt="1111111111111111" src="https://user-images.githubusercontent.com/20707603/35481897-a4c609e0-0467-11e8-9b2e-fb2fe246f031.png">
<img width="1110" alt="22222222222222" src="https://user-images.githubusercontent.com/20707603/35481900-a911403c-0467-11e8-921a-c340463279b3.png">

**Steps to reproduce the issue:**

1.Add a a registry-mirror address

2.Click    Apply & Restart

**Describe the results you received:**

Failed to start Docker daemon  when using a registry-mirror

**Describe the results you expected:**

The early version of the version is no problem, It can run normally，and it's going to be a problem after the latest one or two upgrades.

**Temporary solution:**

Add configuration parameters directly to Advance, instead of adding in Basic. As shown in the figure：

<img width="500" alt="444444444444444" src="https://user-images.githubusercontent.com/20707603/35482050-385a04de-046a-11e8-841e-23af348a5b1a.png">
<img width="500" alt="55555555555" src="https://user-images.githubusercontent.com/20707603/35482052-3bdfb20c-046a-11e8-808c-548ea4d127c2.png">
<img width="512" alt="666666666" src="https://user-images.githubusercontent.com/20707603/35482057-5af565ba-046a-11e8-9332-6ce15464bf75.png">

**Additional information you deem important (e.g. issue happens only occasionally):**

**Dokcer Version**

hongxiaoludeMacBook-Pro:~ hongxiaolu$ docker info 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: W43K:YHY3:ATS4:XQP4:PBJD:UB6Q:MZWY:IPVX:4QN2:YCUW:4FMW:3C6H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 39
 System Time: 2018-01-28T12:05:02.719832548Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**OS Version**

hongxiaoludeMacBook-Pro:~ hongxiaolu$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212
hongxiaoludeMacBook-Pro:~ hongxiaolu$

**Comment by thaJeztah** [comment]
This could be an issue with Docker for Mac; can you reopen this issue in the Docker for Mac issue tracker instead? https://github.com/docker/for-mac/issues


I’ll close the issue here, but feel free to comment after I closed
