### ISSUE TITLE
Task API: Task.Status.ContainerStatus does not report ExitCode

### ISSUE THREAD

**Issue by johnflavin** [moby/moby#36139]
**Description**

The `/tasks` and `/tasks/{id}` APIs return `Task` objects that, according to the `swagger.yaml`, are supposed to contain the container's exit code. See [line 2855](https://github.com/moby/moby/blob/master/api/swagger.yaml#L2855).
```yaml
Task:
  ...
  Status:
    ...
    ContainerStatus:
    type: "object"
    properties:
      ContainerID:
        type: "string"
      PID:
        type: "integer"
      ExitCode:
        type: "integer"
```

 But when you requests one of these `Task` objects the exit code is never populated, even when the container has exited and has an exit code.

**Steps to reproduce the issue:**
1. Run a swarm of one node, or perform the last step on the node where the task runs.
2. Make a test service, which will just start a task that finishes and does not restart.
```
$ serviceId=$(docker service create --detach --replicas 1 --restart-condition none --name task_test busybox:latest echo hello world)
```
3. Get the task status. We do this with `curl` using the API because, as far as I know, there is no way to interact with tasks via the CLI.
```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/tasks?filters=%7B%22service%22%3A+%5B%22task_test%22%5D%7D | jq '.[].Status'
{
  "Timestamp": "2018-01-29T19:55:28.958524039Z",
  "State": "complete",
  "Message": "finished",
  "ContainerStatus": {
    "ContainerID": "04fe9d0f5b2aa199508c3a9d1fc5108bb3f9f9a47479174c164ef7c5b49ee724"
  },
  "PortStatus": {}
}
```
Note that the task is `complete`, but the `ContainerStatus` has no exit code.
4. Verify that the container itself has an exit code. First we get the task again to pull out the container id.
```
$ containerId=$(curl -s --unix-socket /var/run/docker.sock http://localhost/tasks?filters=%7B%22service%22%3A+%5B%22task_test%22%5D%7D | jq -r '.[].Status.ContainerStatus.ContainerID')
```
Then we check the container's status. Again, if you have a swarm with multiple nodes, run this on the node where the task ran.
```
$ docker inspect --format '{{json .State }}' $containerId | jq
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2018-01-29T19:55:28.26385155Z",
  "FinishedAt": "2018-01-29T19:55:28.385514471Z"
}
```
Note the `ExitCode` is `0`.

**Describe the results you received:**
The task has a `complete` status, but no information about the container's exit code.

**Describe the results you expected:**
A `complete` task should report the exit code of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce-rc1
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	5e1d90a
 Built:	Thu Jan 25 00:33:50 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc1
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	5e1d90a
  Built:	Thu Jan 25 00:40:43 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 18.02.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: paoa35fkot3u4m5pc6gf4p04n
 Is Manager: true
 ClusterID: w5jav4f7bbbt0ov0z8v56yhra
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 6LP3:ZF5H:DENT:W3UQ:IPCO:J34X:PEDJ:4JZI:RZM7:RPE7:NNAW:T2LC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 162
 System Time: 2018-01-29T20:14:05.085046356Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for mac

**Comment by yongtang** [comment]
I think the issue is that `json:",omitempty"` are annotated to `ContainerID`, `PID`, and `ExitCode`. If `PID` or `ExitCode` is `0` then it will not show up in JSON output:
https://github.com/moby/moby/blob/39bcaee47b8a284a46b761afe218ba7deda0d482/api/types/swarm/task.go#L134-L143


One way I can think of addressing the issue, is to have `ContainerStatus` as a pointer and remove `json:",omitempty"` from `ContainerID`, `PID`, and `ExitCode`. In this way, if ContainerStatus is not present, then the whole block will not show up, instead of `ContainerID` (non `""`) with no `PID`/`ExitCode` (`0`)

/cc @thaJeztah

**Comment by yongtang** [comment]
Added PR #36150 for the fix.
