### ISSUE TITLE
api/swagger.yaml does not contain "orphaned" as a TaskState

### ISSUE THREAD

**Issue by EugeneScully** [moby/moby#36142]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

I have a Docker task in the "orphaned" state. The Docker API is correctly reporting that the task is "orphaned". 

This state is missing from the "swagger.yaml" file, so some clients using the Docker API throw an exception because they don't recognise this state

The Docker Swarm documentation lists this state:
https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/

The Docker API document says that it is not a valid TaskState:
https://docs.docker.com/engine/api/v1.35/#operation/TaskInspect
(Probably because it is generated from the swagger file?) 

**Steps to reproduce the issue:**
1. Have an orphaned Docker Task - I'm not sure how to create an orphaned task
2. Call the /TaskInspect operation on the Docker API

**Describe the results you received:**
A non-valid value of "orphaned" was received in the TaskState

**Describe the results you expected:**
api/swagger.yml should contain **"orphaned"** as a valid value

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Output of `docker version`:**

```
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:11:05 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:09:37 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xx Removed xx
 Is Manager: true
 ClusterID: xx Removed xx
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.0.4
 Manager Addresses:
  xx Removed xx
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: master1
ID: xx Removed xx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: spgcontrols
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by yongtang** [comment]
Added PR 36146 for the fix.
