### ISSUE TITLE
Move builders/dockerfile/shell_parser.go into builders/dockerfile/parser

### ISSUE THREAD

**Issue by r2d4** [moby/moby#36154]
I'd like to move `shell_parser.go` and its test files `shell_parser_test.go` and `wordsTest` from the package `builders/dockerfile` to `builders/dockerfile/parser` so that it can be vendored without grabbing all the dependencies from `builders/dockerfile`.  The file has no other dependencies than the standard library, so it can be moved easily.  

If this sounds alright, I can go ahead and make the change.

https://github.com/moby/moby/blob/master/builder/dockerfile/shell_parser.go

**Comment by vdemeester** [comment]
cc @tonistiigi @dnephin

**Comment by dnephin** [comment]
SGTM, `builder/dockerfile/parser` exists and has a few dependencies. Maybe move it to `builder/dockerfile/shell` ?
