### ISSUE TITLE
lost LAN connection after installing docker-ce on Ubuntu

### ISSUE THREAD

**Issue by diegoquintanav** [moby/moby#36153]
Connection to internet is lost after installing docker-ce following the instructions from https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Steps to reproduce the issue:**
1. Follow the instructions from https://docs.docker.com/install/linux/docker-ce/ubuntu/
2. After doing `sudo apt-get install docker-ce`, LAN internet connection is lost
3. `/etc/resolv.conf` is now displaying a single nameserver at 127.0.1.1.I've managed to fix this by doing
 *   Changing it to 8.8.8.8 gets me on internet, but after a reboot this defaults back at 127.0.1.1
 *   Commenting out `dns=dnsmasq` in `/etc/ NetworkManager/NetworkManager.conf` as stated in https://askubuntu.com/questions/783650/problem-with-dns-in-the-latest-kubuntu-16-04-update. If I reinstall docker this modification persist but it does not solve the problem.

**Describe the results you received:**

Can't  browse the internet or ping any address. 

**Describe the results you expected:**

I was expecting the opposite, i.e. expecting my connection to work as usual. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I believe this is a bug of Ubuntu as far as I've read, but docker triggers this behaviour somehow. I believe this is not a common issue and that it should be documented.

**Output of `docker version`:**

```
Docker version 17.12.0-ce, build c97c6d6
```

**Output of `docker info`:**

```
diego@envy:~$ docker info
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 9
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 10.72GiB
Name: envy
ID: LOXY:SPFK:OA7T:RRNN:HDTN:5TTC:MGH2:NPVG:ZZ4P:BJ6B:JS3C:KBVZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bluesmonk
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

output of `cat /etc/*release`

```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

and of `uname -a`

```
uname -a
Linux envy 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by diegoquintanav** [comment]
As I've stated before, it seems this is an Ubuntu issue. Some workarounds are mentioned here https://unix.stackexchange.com/questions/128220/how-do-i-set-my-dns-when-resolv-conf-is-being-overwritten/163506#163506

Once again, the reason of this gh Issue is that docker triggers this behaviour and it seems it is very common.

**Comment by wargun02** [comment]
Me too. Encountered this issue with Ubuntu 16.

**Comment by wargun02** [comment]
Seems that by editing /etc/NetworkManager/NetworkManager.conf and comment out the line
```dns=dnsmasq```

restart...seems to work for me.

**Comment by diegoquintanav** [comment]
Can someone at least provide some explanation of why this is happening? I think it is necessary.

**Comment by thaJeztah** [comment]
The reason that the DNS is being overwritten is that NetworkManager is active, and configured to use dnsmasq. NetworkManager most likely listens for network-interfaces to change on your machine, and is known to work badly in combination with network interfaces being added/removed in other namespaces (e.g. every container that's started gets its own network-namespace; NetworkManager may not understand this, and tries to manage networking inside the container, and failing).

**Comment by diegoquintanav** [comment]
@thaJeztah I think I understand. But I am left with some questions:

1.  Why is that when the `network-manager` fails to manage network interfaces in the "host" machine (i.e. where docker is installed), it defaults or breaks the current configuration?
2.  What are some alternatives to the `network-manager` that don't mess up with the dns configuration and the docker installation?
3.  Don't you believe some workaround ought to be documented somewhere? (is it already?). I would gladly do it but I don't know how to solve it. At the moment of writing this I can either uninstall docker or add the google dns at runtime using a non-graceful hack.

**Comment by diegoquintanav** [comment]
I'm the one actually that suggested that solution in my first comment. After reinstalling docker it does not work anymore.

**Comment by diegoquintanav** [comment]
Now using a fresh 18.04 installation, the `dnsmasq` is not present in the `NetworkManager.conf` file out of the box, making that answer invalid. 

Refer to this thread in SO https://stackoverflow.com/questions/51105875/internet-connection-not-working-networkmanager-not-working-after-installing-dock

Sorry to reactivate this, but what is a clean way to make this work without having to hardcode a dns address or deactivating NetworkManager?

**Comment by arsenal-2004** [comment]
@diegoquintanav Did you find a solution to this problem? I have the same issue with Ubuntu 16.04.

**Comment by alete89** [comment]
this also happen in debian stretch with mate, which also uses network-manager. `/etc/resolv.conf` is overriden with `nameserver 127.0.0.1`

**Comment by diegoquintanav** [comment]
@arsenal-2004 The problem in my case was that the docker interface was intercepting requests to the DNS server in my corporate network. If you happen to be in the same scenario, the solution was to edit `/etc/docker/daemon.json` with

```bash
{
  "bip": "172.31.0.1/16"
}
```
here, `bip` is a network that is apart i.e. it is isolated from my corporate network. Restart the docker daemon with `sudo service docker restart` and you should have internet again.

old containers should have still networks related to the old interface, so ideally you'd want to

1. stop all containers
2. prune all networks
3. relaunch containers with `--force-recreate` parameter

see the full explanation in https://superuser.com/questions/1336567/installing-docker-ce-in-ubuntu-18-04-breaks-internet-connectivity-of-host

**Comment by YuriyGavrilov** [comment]
> @arsenal-2004 The problem in my case was that the docker interface was intercepting requests to the DNS server in my corporate network. If you happen to be in the same scenario, the solution was to edit `/etc/docker/daemon.json` with
> 
> ```shell
> {
>   "bip": "172.31.0.1/16"
> }
> ```
> 
> here, `bip` is a network that is apart i.e. it is isolated from my corporate network. Note that this may work with another network in your case. Restart the docker daemon with `sudo service docker restart` and you should have internet again.
> 
> old containers should still have networks related to the old interface, so ideally you'd want to
> 
> 1. stop all containers
> 2. prune all networks
> 3. relaunch containers with `--force-recreate` parameter
> 
> see the full explanation in https://superuser.com/questions/1336567/installing-docker-ce-in-ubuntu-18-04-breaks-internet-connectivity-of-host

This is solve problem for me on Astra Linux. Thanks @diegoquintanav
