### ISSUE TITLE
docker logs command "leaks" extra bytes after exit in the shell

### ISSUE THREAD

**Issue by sofianinho** [moby/moby#36175]
Hello everyone,

**Description**
I noticed a minor glitch in the docker logs command when using the shell inside an ubuntu container. From what I can tell, it has to do with the bash UI of the "apt" command.  

**Steps to reproduce the issue:**
1. Start an ubuntu:16.04 container with bash: `docker run -it ubuntu:16.04 bash`
2. Use tha "apt" command, especially the upgrade or install command in order to force the appearance of the progress bar.
3. On another shell use the "docker logs CONTAINER_ID" to see the logs of this container.

**Describe the results you received:**
Extra bytes would leak into the next command on your bash. For example, here are bytes I've seen on mine 
```
2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c2R11;rgb:2727/2828/22221;4402;0c
```
To confirm that this is "apt", I run extra commands and then limited my "docker logs" outputby using the "--tail " subcommand. If I give it enough lines to reach the apt results, it would leak this extra bytes as it returns. I tried it on my machine using different terminal applications: Tilix, Terminator, Gnome-terminal (all with bash and sh), same result.

**Describe the results you expected:**
The command would leave an empty command on the next line.

**Additional information you deem important (e.g. issue happens only occasionally):**
The first time I've noticed this was on a container where Kafka was running in detached mode. I thought the bytes leaking was related to kafka, but upon trying to reproduce it seems to be related to the "apt" command as I limited the output using the "--tail" subcommand.

**Output of `docker version`:**
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

**Output of `docker info`:**
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 405
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 720
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: rh30cxuh6fwltn1rdizrcvo0i
 Is Manager: true
 ClusterID: rmjqtu9o9wclci6ui8b7tipzh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.17
 Manager Addresses:
  192.168.1.17:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-lowlatency
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.09GiB
Name: PoCRANaaS-1
ID: 2XYS:S6WW:R75F:VFOL:OU6J:IOVM:QFBH:DKEE:62MN:TWKY:PRYM:SDN7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by dragon788** [comment]
Does the `apt-get` command cause the same leakage?

**Comment by sofianinho** [comment]
@dragon788 The short answer is no, only with `apt`. 
Slightly longer answer. I checked by installing dummy packages with "apt-get" with the default apt.conf.d config from official ubuntu:16.04 image, running docker logs (nothing unusual) and then using the same with `apt` and the leaking I described. But as soon as I changed the `apt-get` as follows:
```
echo -e 'Dpkg::Progress-Fancy "1";\nAPT::Color "1";' > /etc/apt/apt.conf.d/99fancy
```
and re-run the `apt-get` commands, I had the same result as in `apt`. So it seems to be related to these parameters as they are enabled by default with the apt command.

**Comment by thaJeztah** [comment]
I suspect that the issue here is that the container is run with `-it` (TTY attached), which may affect the software running inside the container (to use pretty printing), and the `docker logs` command printing that output verbatim, including the terminal escape sequences to control colouring.

I don't think there's a bug at hand here, but feel free to continue the conversation.
