### ISSUE TITLE
Service does not update on change in volume

### ISSUE THREAD

**Issue by macmackiewicz** [moby/moby#36180]
**Description**
In swarm mode, changes in files mounted through a volume are not being served by a service, even though they are present inside the container.

**Steps to reproduce the issue:**
1. Run docker in swarm mode
2. Create docker-compose.yml, e.g.:
```
version: '3.5'
services:
  app:
    image: app
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
```

3. Place application code in the same directory as docker-compose.yml, in my case it's a node app, like:
```
const express = require('express')
const app = express()

app.get('/', (req, res) => res.status(200).send('OK'))
app.listen(3000)
```

4. Deploy stack with `docker stack deploy -c docker-compose.yml test`.
5. Edit application code on host (e.g. change `send('OK')` to `send('OK!!!')`).

**Describe the results you received:**
Querying `localhost:3000` returns an unchanged response.  

**Describe the results you expected:**
Querying `localhost:3000` would return a response that reflects changes applied on host to the application's code.

**Additional information you deem important (e.g. issue happens only occasionally):**
Changes are visible when entering the container through `docker exec`.

Sometimes after inspecting the code inside the container with vim and saving the file without any further changes, the service started serving desired changes, but it did not happen every time.

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 109
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 7iexkbn0al6un4zrx2udov494
 Is Manager: true
 ClusterID: qj7clvzceh3ghvvozvtlok6y9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: GN6V:DHXB:IHDR:HJYG:7JZN:WIXX:PNNH:I6XW:RP2T:PH57:JQ4M:ORQ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 165
 System Time: 2018-02-01T23:18:50.394266276Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by cghislai** [comment]
you seem to build a docker image for that service, can you post Dockerfile?
It seems to me your container process (the node application) needs to be restarted to run the new code, just like it would do locally. Are you sure a new task/container is created when required?
You can force docker to create new task by updating the service:
`docker service update --force <service_name>`

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
