### ISSUE TITLE
docker pull of image built on 18.02 fails on 17.06

### ISSUE THREAD

**Issue by pdebruin** [moby/moby#36184]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Using Docker for Windows Edge I built a new asp.net core app on nanoserver. Pushed to Docker Hub. Pull on Windows Server 2016 results in an error.  

**Steps to reproduce the issue:**
On Windows Server 2016: docker pull pdebruin/aspcoremvc1802
or to also build the image 
1. on D4W git clone https://github.com/pdebruin/aspnetcoremvc.git (or dotnet new mvc and add the  dockerfile)
2. docker build . -t <dockerhubid>/aspnetcoremvc1802
3. docker push <dockerhubid>/aspnetcoremvc1802
4. On WS2016 docker pull <dockerhubid>/aspnetcoremvc1802

**Describe the results you received:**
When I pull it to WS2016 I get an error when the first layer is almost done extracting: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\6faec334f4ba8d55ae5707f2456e474ee6086307e502463bbb64820951f7ee53\UtilityVM: The system cannot find the path specified.

**Describe the results you expected:**
docker pull should just work (or if it requires a different engine it should say so)

**Additional information you deem important (e.g. issue happens only occasionally):**
I can reproduce on another WS2016: Just pull pdebruin/aspcoremvc1802. The exact same build on a 17.06 machine works fine anywhere else.

**Output of `docker version`:**
D4W Win10
```
Client:
 Version:       18.02.0-ce-rc1
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    5e1d90a
 Built: Thu Jan 25 00:34:00 2018
 OS/Arch:       windows/amd64
 Experimental:  true
 Orchestrator:  kubernetes

Server:
 Engine:
  Version:      18.02.0-ce-rc1
  API version:  1.36 (minimum version 1.24)
  Go version:   go1.9.3
  Git commit:   5e1d90a
  Built:        Thu Jan 25 00:47:42 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 18.02.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.93GiB
Name: DESKTOP-49LCHD9
ID: KZRK:ZMLF:BN5U:OXYU:BRUB:EPCG:FLN4:EKH6:V6H4:6BBG:TWH5:JVAC
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2018-02-02T09:21:14.2276791+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 dtrlb-k3o7y3fv3kvgm.westeurope.cloudapp.azure.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `docker version`:**
WS2016
```
Client:
 Version:      17.06.1-ee-2
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:16:53 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ee-2
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:25:53 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 55
Server Version: 17.06.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5GiB
Name: pieterd-vsts
ID: M6TN:V5PO:2Q2S:DEP7:BY4P:PBZ3:PNHV:3I7M:NX3D:JHZ6:XGNL:Y727
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 dtrlb-k3o7y3fv3kvgm.westeurope.cloudapp.azure.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
D4W on Windows 10 physical.
WS2016 physical and another on Azure.

**Comment by GaProgMan** [comment]
I'm facing the same issue with a clean install of Azure's Windows Server 2016 with Containers.

Here is the output for `docker info` on the VM (where I'm attempting to pull and consume an image):

```
PS > docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2007.amd64fre.rs1_release.171231-1800)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14GiB
Name: <redacted>
ID: RQOR:VXVI:6QDD:J4WP:HMGJ:ZM6U:MF4T:3VYN:ZZNM:2HGO:S2ZJ:S33A
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

And here is the output of the same command, when run on my local machine (where I created the image):

```
PS > docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 32
Server Version: 18.02.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 11.96GiB
Name: <redacted>
ID: ASUG:OXLN:APM3:7AJE:JYYM:2QJP:PS4G:4Y7P:73DI:XX6D:IMI6:KDCW
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2018-02-14T16:13:18.9220664Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by GaProgMan** [comment]
Interestingly, when I created a completely different image on a third machine (this time, running `17.12.0-ce`), and attempt to pull that with my Azure VM (same as previous message), I get the same error.

Here is the output of `docker info` on the new machine:

```
docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 17.12.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.96GiB
Name: <redacted>
ID: VNSU:YGRD:DRYX:6PRO:72RQ:PZNQ:YJH3:6HVK:U5U2:X2FH:2JMM:GIB4
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2018-02-14T16:55:20.1613357Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by johnstep** [comment]
This is easy to reproduce and does not seem specific to Docker for Windows or Docker 18.02, but occurs when building on Windows Server 1709 and pulling on Windows Server 2016. Investigating...

**Comment by jhowardmsft** [comment]
Ping @darrenstahlmsft

**Comment by darrenstahlmsft** [comment]
More generally, this error is seen when pulling a 1709 nanoserver base image on a host that doesn't support 1709 images (Windows Server 2016). The simplest repro case is `docker pull microsoft/nanoserver:1709` on a Windows Server 2016 host.

If you want to run the same image on both Windows Server 2016 (or Windows 10 14393) and Windows Server 1709 (or Windows 10 Fall Creators Update), the image should be based on microsoft/windowsservercore:latest or microsoft/nanoserver:latest, rather than a 1709 tag, and when run on the Windows Server 1709 host, it should be run using `--isolation=hyperv`.

That said, the daemon should block this and provide a better error message when the image being pulled is not supported on the host (in this case, even hyperv isolation will not run 1709 images on Windows Server 2016).

**Comment by thaJeztah** [comment]
> in this case, even hyperv isolation will not run 1709 images on Windows Server 2016

I wasn't aware that was the case; wasn't hyperv isolation meant to work around the compatibility issue?

**Comment by darrenstahlmsft** [comment]
@thaJeztah The compatibility guarantee (for current versions of Windows at least) is that older images will work on newer hosts, but newer images are not guaranteed to work on older hosts.

**Comment by jhowardmsft** [comment]
I'm coding up a fix to give a correct error message...

**Comment by thaJeztah** [comment]
> older images will work on newer hosts, but newer images are not guaranteed to work on older hosts.

Oh, right, makes sense

**Comment by pdebruin** [comment]
On WS2016 (17.06.2-ee-6) I can actually pull the base image (microsoft/aspnetcore:2.0.5). https://github.com/pdebruin/aspnetcoremvc/blob/master/Dockerfile Adding the ASP.NET Core app with D4W (18.02 CE) makes it incompatible. So it does not look Windows 17.09 related to me.

**Comment by GaProgMan** [comment]
This is what I was seeing too, @pdebruin. My dockerfile was the same the one you linked to.

I changed my dockerfile to the following:

``` 
# Build image
FROM microsoft/dotnet:2.0.5-sdk-2.1.4-nanoserver-sac2016 AS builder
# do build steps

#App image
FROM microsoft/aspnetcore:2.0.5-nanoserver-sac2016
WORKDIR /app
ENV ASPNETCORE_URLS http://+:5000
EXPOSE 5000
COPY --from=builder /sln/dist .
ENTRYPOINT ["dotnet", "app.dll"]
```

After pushing this dockerfile to my container repo, I was able to pull and extract it on my Windows Server 2016 VM using `docker pull ...`

I could also run it without issues (with a standard `docker run ...`), I guess I need to be more picky with the base images that I choose.

**Comment by darrenstahlmsft** [comment]
@pdebruin What you're seeing is a result of multi-manifested images. `microsoft/aspnet:2.0.5` has multiple versions of the image uploaded to the same tag. When you pull the image directly on WS2016, it is downloading the WS2016 version (notice the the first layer in the extraction list is, as of writing this, `bce2fbc256ea`, which is `microsoft/nanoserver:latest`), but when you download it on a 1709 host, you're downloading the 1709 version (first layer is `407ada6e90de` which is `microsoft/nanoserver:1709`). The resulting built image in the repro steps cannot change its underlying layers based on the host it is being pulled on, so it attempts to download the 1709 base image, and fails.

@johnstep @jhowardmsft This is an odd result of multi-manifested Windows image versions that I don't think we considered. To prevent the failure at pull time on the WS2016 host, we can block image pulls of incompatible images, but we can't prevent image owners from adding a 1709 image to an existing WS2016 image that would cause scenarios like this (building on 1709, running on WS2016) to start to fail unexpectedly. Maybe the guidance should be to only multi-manifest different Windows versions on the latest tag, and keep other tags to single version?

**Comment by darrenstahlmsft** [comment]
I spoke to @jhowardmsft offline regarding the above. We're not super concerned about my comments of only using multi-manifested image versions on `latest`, as we don't think many (if any) existing tags are getting a multi-manifested images added to them, except for latest, which is not expected to be used in prod, but it's something we should keep in mind.

**Comment by jhowardmsft** [comment]
Submitted https://github.com/moby/moby/pull/36327
