### ISSUE TITLE
Attachable overlay network is not available to Swarm worker nodes

### ISSUE THREAD

**Issue by mback2k** [moby/moby#36197]
**Description**

As described by @thaJeztah in the following post, I tried to create an attachable overlay network which should be available to non-swarm containers on all nodes that are part of the Swarm-mode cluster:
https://github.com/moby/moby/issues/30013#issuecomment-292339333

Unfortunately as pointed out by @thaJeztah in the following post, it seems like the overlay network is only available on manager nodes, and not worker nodes:
https://github.com/moby/moby/issues/30013#issuecomment-292351109

**Steps to reproduce the issue:**
1. Create docker Swarm-mode cluster consisting of at least 2 manager and 2 worker node.
2. Run `docker network create --opt encrypted --driver overlay --attachable --scope global --subnet 10.9.9.0/24 --gateway 10.9.9.1 testnet` on one of the manager nodes.
3. Run `docker network ls` on all nodes and see that the network only exists on the manager nodes, not the worker nodes.

**Describe the results you received:**

Trying to use `docker run` or `docker-compose` with the network on the worker nodes will fail, since it is not available:
`Parameter error: network named testnet could not be found. Does it exist?`

**Describe the results you expected:**

I would expect the network to be available on all nodes, since it should be attachable for all non-swarm containers in the whole cluster.

**Output of `docker version` on all nodes:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:54 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ...
 Is Manager: true
 ClusterID: ...
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.1.1
 Manager Addresses:
  10.0.1.1:2377
  10.0.2.1:2377
  10.0.3.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.74GiB
Name: bgd
ID: ...
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The nodes are running in KVM-based virtual machines.

**Comment by fcrisciani** [comment]
@mback2k not seeing it on the workers is normal, because is getting deployed only when used. Int he case of a docker run with a network that is attachable if the network does not exist locally is re routed to the manager that will find it.

**Comment by mback2k** [comment]
@fcrisciani If it is re-routed to the manager that will find it, why do I get the error "Parameter error: network named testnet could not be found. Does it exist?"?

**Comment by fcrisciani** [comment]
@mback2k can you confirm which command shows this error message?
`Parameter error: network named testnet could not be found. Does it exist?` I grep for it on the docker repo and I did not find any match. I also tried your steps on 18.02-ce and I was not able to repro.

**Comment by mback2k** [comment]
Actually it seems like my issue is caused by using Ansible. It use the ansible docker_container module to deploy individual containers onto my systems and this is what happens:

```
Traceback (most recent call last):
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 2124, in <module>
    main()
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 2119, in main
    cm = ContainerManager(client)
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 1751, in __init__
    self.parameters = TaskParameters(client)
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 794, in __init__
    self.published_ports = self._parse_publish_ports()
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 1015, in _parse_publish_ports
    default_ip = self.default_host_ip
  File \"/tmp/ansible_V1KBpP/ansible_module_docker_container.py\", line 998, in default_host_ip
    network = self.client.inspect_network(net['name'])
  File \"/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py\", line 34, in wrapper
    return f(self, *args, **kwargs)
  File \"/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py\", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File \"/usr/local/lib/python2.7/dist-packages/docker/api/network.py\", line 216, in inspect_network
    return self._result(res, json=True)
  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 228, in _result
    self._raise_for_status(response)
  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File \"/usr/local/lib/python2.7/dist-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found (\"network testnet not found\")
```

Running `docker run` manually indeed works. So this seems to be an issue with the implementation in Ansible.

**Comment by mback2k** [comment]
Since Ansible seems to depend on the network meta data being available, would it be possible to have yet unused, but attachable networks show up in the API and `docker network ls` on worker nodes? That would probably solve the interop issues with Ansible and other tools.

**Comment by mback2k** [comment]
@fcrisciani okay, that totally makes sense and should stay as is for security reasons.
