### ISSUE TITLE
I cannot connect the service's exposed port in docker swarm mode (docker in docker)

### ISSUE THREAD

**Issue by ilovemath** [moby/moby#36200]
**Description**
when i run a nginx service in a docker swarm which is running in another docker, i cannot connect the exposed port

**Steps to reproduce the issue:**
1. create docker swarm cluster consisting of 1 manager and 2 worker nodes.
2. create an nginx service which listening on port 8080, using the following cmd

> docker service create --name test -p 8080:8080 --replicas=3 -d $my_registry_ip/nginx

3. curl localhost:8080 both in docker host and the nginx container

**Describe the results you received:**
1. in docker host, i got
 ```
curl: (7) Failed to connect to localhost port 8080: Connection refused
```
2. in the nginx container, i got 
```
 2018/02/05 10:07:03 [error] 39#39: *10 directory index of "/www/" is forbidden, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
127.0.0.1 - - [05/Feb/2018:10:07:03 +0800] "GET / HTTP/1.1" 403 162 "-" "curl/7.57.0" "-"
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Describe the results you expected:**
   in docker host, i should get the same result with what i got in the nginx container.

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.2
 Git commit:   ba9946cf23
 Built:        Tue Nov 21 12:38:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   v17.10.0-ce
 Built:        Tue Nov 21 12:37:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 62
Server Version: 17.10.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.13.2
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: uuqiz1hiv3y12j27psk662ota
 Is Manager: true
 ClusterID: t7sadugvgpq34h3w2kd7kha74
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.18.0.2
 Manager Addresses:
  172.18.0.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.4.27-2-default
Operating System: Alpine Linux v3.7 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.937GiB
Name: manager
ID: J233:H4YV:4UKM:2XZO:HZZM:DJ5E:C7ND:7AE3:EILH:I4WG:3AKY:X4YP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.18.0.2
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The swarm are running in another docker which is running under virtualbox

**Comment by BretFisher** [comment]
If you're running docker-in-docker (DIND) then when you say "host" what layer are you referring to?

Host (Layer 1) -> Virtualbox Alpine (Layer 2) -> Docker (Layer 3) -> DIND (Layer 4)

**Comment by ilovemath** [comment]
Host (win10, Layer1) -> Virtualbox (openSuse, Layer2) ->Docker(Alpine, Layer3)->Docker(Alpine,Layer4)
The docker host is the Layer3 and the nginx container is the Layer4.

**Comment by BretFisher** [comment]
I suggest trying a supported Linux distro in your Virtualbox. You can see the list under Docker CE at store.docker.com.

Also realize that if you want ports accessible on Layer 2 then you need to publish all ports on Layer 3 that you publish in Layer 4, depending on how you do the networking in Layer 3/4.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
