### ISSUE TITLE
Enhancement: automatic scheduling of Manager Roles

### ISSUE THREAD

**Issue by foxxxyben** [moby/moby#36207]
Hello All,

I have been working on an enhancement to the Manager core for the following:

**Use Case:**
An existing cluster of authenticated Nodes, many with Placement tags for scheduling Services via spread according to user Preferences. Docker can automatically maintain a set of 37 Cowsay replica container Services spread across my availability zones, but if one of my Manager Nodes fails at 3AM then human intervention is required to select an appropriate Node for Role change. I would like to specify a Replica Set of, say, 5 Manager Roles, and have replacement, authenticated Worker Nodes promoted to Manager automatically promoted to Manager in the event of failure of one of the Replicas.

**My Solution**
I added a roleScheduler feature that allows the user _to specify a Replica Set of, say, 5 Manager Roles, and have replacement, authenticated Worker Nodes promoted to Manager automatically promoted to Manager in the event of failure of one of the Replicas._ I used as much of the underlying API definitions and Orchestrator/Scheduler/Dispatcher logic as possible to make the user interaction as similar to regular Replicated Service definitions as possible; a new ** RoleManagerService** Mode was made available to allow the user to:

1. Define the desired number of Manager Replicas to maintain;
2. Define Placement Constraint and spread Preferences to determine how Managers are distributed across network topology.

roleScheduler does not directly alter Node.Role; it only sets DesiredRole and delegates Role management authority to the existing role_manager.go. Regardless of user-defined Constraints the primary eligibility requirement is that SwarmKit's existing subsystems can change the Role to Manager, so all of the underlying security features of Node registration & authentication and anything else I wouldn't go near are left unmodified and enforced.

Please have a look at [https://github.com/foxxxyben/swarmkit](https://github.com/foxxxyben/swarmkit) for more details in README.md. I have run and passed my unit tests, but not any integration tests as I don't actually have a ginormous cluster to really run it on. Please keep in mind I named my file rolescheduler.go because helloworld.go is overused.

Thanks,
-Ben

**Comment by thaJeztah** [comment]
I see you opened a PR in SwarmKit, that's being discussed https://github.com/docker/swarmkit/pull/2502. Let me close this one for now to prevent the discussion from taking place at two locations
