### ISSUE TITLE
"privileged mode is incompatible with user namespaces" message is unhelpful

### ISSUE THREAD

**Issue by nicbou** [moby/moby#36208]
As a knowledgeable-but-not-expert user, I recently got this message:

> ERROR: for containername  Cannot create container for service containername: privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode

My first reaction was ["what the **** does this mean?"](https://media.giphy.com/media/kF0ClnIcSBiDe/giphy.gif).

This ticket documents how an average user (senior-ish software engineer, uses docker at work and at home) solved this problem using this error message and Google.

I take full responsibility for my incompetence, but there are many more of my kind, and the humane thing to do is to guide them towards a solution. **We need a better error message.** I hope that ticket makes a strong case for a better error message and better documentation to support it.

## Context

I updated docker recently. Then things something stopped working, and this error message was the only hint I got. I don't understand any of the concept it mentions, or which steps to take in order to fix my problem.

## Fixing the issue

When you are knee-deep in complex issues all day, you can easily forget how the average user sees things, so I wrote down my thought process down while I fixed the issue so you could understand my perspective as an end user.

1. What the f- does this mean? This worked yesterday! (at this point, I'm already 3 levels deep on a completely different issue)
2. What's privileged mode? What are user name spaces?
3. What does "running the container in the host namespace" mean? *What am I supposed to do?*
4. Maybe if I try to run it without sudo... nope.
5. *Googles the error message*
6. "Introduction to User Namespaces in Docker Engine" ([link](https://success.docker.com/article/Introduction_to_User_Namespaces_in_Docker_Engine))
7. "A namespace wraps a global system resource in an abstraction that makes it appear to the processes within...". Nope, can't understand any of that.
8. I'm halfway through that page, and I'm still no closer to a useful explanation. What is this? What does any of this even mean? Why doesn't it work anymore?
9. *Googles the error message again*
10. Okay, so according to [this article](https://luppeng.wordpress.com/2016/07/04/docker-user-namespaces/), it seems to be a way to prevent a docker root user to do nasty stuff on the host machine. Why didn't they tell me that in step 6?
11. "--userns-remap=default" can allegedly fix this. Nope, can't just add it to `docker-compose up`.
12. `userns_mode: "host"` apparently disables that. All I need to do is bump the docker-compose version to 2.1
13. "2.1" is not a valid version, for some reason that is completely unexplained by this generic error message. I'm using the latest version of docker and docker-compose, which is why I'm getting the errors above in the first place
14. (at this point, I should state that I am slowly losing my cool)
14. Oh, it seems like this feature was added in a version that's not available on the docker PPA. Time to update docker-compose to an unreleased version to fix a problem in a released version. [This page](https://github.com/docker/compose/releases) helped me.
15. "docker-compose version 1.19.0-rc3". Sweet, it's working!
16. Aaaaand it works. I don't know why it works, but it works, and that's enough for one day.

All of this, including creating the ticket and finding the Office Space gif took me about 1.5 hours. I believe a more appropriate error message and documentation page could have reduced that to a few minutes. I apologize for the odd format of this ticket, but I hope it's still helpful.

**Comment by thaJeztah** [comment]
Both "privileged" and "user namespaces" are not options that are set by default; enabling these options requires you to understand why you set those options; if you were running an example docker instruction (or docker compose file), I'd recommend understanding what's in the file. Docker has many options, some of which allows you to do powerful (but dangerous) things; e.g. it's possible to set options that give a container full root access to the host (the `privileged` option is one of those).

User namespaces are an advanced option that help improve security, but do require a good understanding of the advantages _and_ limitations (for example, user namespaces prevents container processes from accessing files on the host, so if you _want_ to give access, it'll require some additional work to make this possible). Also see the documentation on user namespaces (which includes a section on limitations); https://docs.docker.com/engine/security/userns-remap/

> Oh, it seems like this feature was added in a version that's not available on the docker PPA

Can you elaborate? The 2.1 compose file format was added a long time ago (I think Docker Compose 1.10, which was release January last year).

**Comment by nicbou** [comment]
> Both "privileged" and "user namespaces" are not options that are set by default

I understand and agree, but neither the error message nor the documentation manage to break down these concepts in an approachable way. I made a genuine attempt at understanding them, but the documentation was comically cryptic.

I read the link you have provided, and it suffers from the same problem: they are impossible to understand for an average docker user. I need [MathIsFun](https://www.mathsisfun.com/algebra/matrix-introduction.html), not [Wikipedia](https://en.wikipedia.org/wiki/Matrix_\(mathematics\)). I'm not dumb, just overwhelmed.

> The 2.1 compose file format was added a long time ago

That's entirely possible. I didn't update docker in a while. That's my fault. In any case, the latest version wasn't available on Ubuntu 16.04, even after updating the PPA. I just downloaded the latest version from the releases page of this repo.

**Comment by thaJeztah** [comment]
> I understand and agree, but neither the error message nor the documentation manage to break down these concepts in an approachable way.

Yes, the docs could use some refinement. The best way forward for that is to open a ticket in the documentation repository; the easiest way to do so is using the `Request docs changes` link that you find on that page in the docs.

>  the latest version wasn't available on Ubuntu 16.04, even after updating the PPA

Docker Compose is not currently in our apt/yum repositories, and is only distributed using the releases page on GitHub. Possibly you previously installed a distro package, and those may not be updated frequently.

Given that this issue is mainly about the Docker documentation (which is not maintained in this repository), I'll close the issue here, but feel free to continue the conversation 👍

**Comment by ainar-g** [comment]
For people coming to this issue, clicking the link “Introduction to User Namespaces in Docker Engine” in the OP, and getting redirected to Docker's main page, here is an archived version: https://web.archive.org/web/20200615015118if_/https://success.docker.com/article/introduction-to-user-namespaces-in-docker-engine.

**Comment by thaJeztah** [comment]
Yes, that website was mostly around Docker Enterprise, and is no longer up, but if there's information you think should be restored from that page (to be included in https://docs.docker.com/engine/security/userns-remap/), let us know 👍
