### ISSUE TITLE
Send email with a backtrace / log when restart policy kicks in

### ISSUE THREAD

**Issue by alexandernst** [moby/moby#36216]
It would be very helpful if the restart policy settings had a configurable email to which the last `N` lines of the log would be sent in case of a restart (crash).

**Comment by thaJeztah** [comment]
Thanks for your suggestion, but this is out of scope of what the daemon should be doing; you could setup some external tool that uses the docker event API, and based on certain events sends out emails

I’ll close this issue because this is out of scope, but feel free to discuss

**Comment by alexandernst** [comment]
@thaJeztah I disagree. Docker's daemon already has the capability of monitoring for crashes and restarting containers. Sending emails from Docker's code would take a very small amount of code, and will greatly benefit everyone seeking for such capability. 

The alternative, as you said,  is to create some external tool that would do polling on Docker's API, waiting for the right event. That has a lot of disadvantages, the main one being that it won't have the visibility that it would have if it lived inside Docker (as an option), but also that it would require extra steps in order to have such a basic feature (sending alerts to an email).

**Comment by cpuguy83** [comment]
This argument can beade for every feature request.
But it's really not in scope for Docker to send emails.

By the way, events is not an API that you have to poll and is made just for such use cases.

**Comment by alexandernst** [comment]
Ok, fair enough. Can you at least point me to the exact message that I should subscribe to?

**Comment by thaJeztah** [comment]
Going through the events API (https://docs.docker.com/engine/api/v1.35/#operation/SystemEvents) and evens CLI reference https://docs.docker.com/engine/reference/commandline/events/ would be a good start.
