### ISSUE TITLE
Can not run setpriv command inside a container

### ISSUE THREAD

**Issue by vladimirtiukhtin** [moby/moby#36210]
**Description**

Can not run setpriv command inside a container. Getting:
```
# setpriv --euid=test id
setpriv: failed to parse euid: 'test'
```

**Steps to reproduce the issue:**
1. docker run -ti centos
2. useradd test
3. setpriv --euid=test id

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	486a48d270
 Built:	Fri Dec 29 12:13:10 2017
 OS/Arch:	linux/amd64
 Experimental:	false

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	486a48d270
  Built:	Fri Dec 29 12:13:27 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by thaJeztah** [comment]
Error seems to be coming from https://github.com/karelzak/util-linux/blob/fd777151bf71eb8e2238a24e20efa8ce132e74e9/sys-utils/setpriv.c#L788-L793 -> https://github.com/karelzak/util-linux/blob/fd777151bf71eb8e2238a24e20efa8ce132e74e9/sys-utils/setpriv.c#L646-L655


When using UID instead a username, this seems to work;

```
 id test
uid=1000(test) gid=1000(test) groups=1000(test)

setpriv --euid 1000 id
uid=0(root) gid=0(root) euid=1000(test) groups=0(root)
```

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
