### ISSUE TITLE
[18.02.0] Swarm service cannot attach to host network - "only one instance of "host" network is allowed"

### ISSUE THREAD

**Issue by albers** [moby/moby#36247]
According to the [compose file docs](https://docs.docker.com/compose/compose-file/#host-or-none), this fragment should create a swarm service whose instances are connected to the host`s network:

```yaml
services:
  web:
    ...
    networks:
      hostnet: {}

networks:
  hostnet:
    external:
      name: host
```

This used to work for me up to Docker 18.01.0-ce:
```bash
user@docker4:~$ cat hostnet.yml
version: '3.4'

services:
  web:
    image: nginx
    networks:
      hostnet: {}

networks:
  hostnet:
    external:
      name: host
user@docker4:~$ docker stack deploy -c hostnet.yml hostnet
Creating service hostnet_web
user@docker4:~$ docker service ps hostnet_web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
ekh2x9fiftwn        hostnet_web.1       nginx:latest        docker4             Running             Running 10 seconds ago
```
WIth Docker 18.02.0, deployment fails with *only one instance of \"host\" network is allowed"*:
```bash
user@docker4:~$ docker stack deploy -c hostnet.yml hostnet
Creating service hostnet_web
user@docker4:~$ docker service ps hostnet_web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR                              PORTS
tbrwxomncmxh        hostnet_web.1       nginx:latest        docker4             Ready               Rejected 2 seconds ago   "only one instance of "host" n…"
5wfft46phw7n         \_ hostnet_web.1   nginx:latest        docker4             Shutdown            Rejected 7 seconds ago   "only one instance of "host" n…"
o95qdlf4w029         \_ hostnet_web.1   nginx:latest        docker4             Shutdown            Rejected 8 seconds ago   "only one instance of "host" n…"
```
Log output:

    ERRO[2018-02-08T15:46:59.635485455+01:00] fatal task error   error="only one instance of \"host\" network is allowed" module=node/agent/taskmanager node.id=[...] task.id=[...]

<details>
  <summary>Output of `docker version`</summary>

```
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:16:33 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:15:05 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

</details>

<details>
  <summary>Output of `docker info`</summary>

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 133
Server Version: 18.02.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 222
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 5tgj049z74d8bigq4osjujr1b
 Is Manager: true
 ClusterID: oy18buvxbbqb00libidep5kx9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.1.51
 Manager Addresses:
  10.0.1.51:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.72GiB
Name: docker4
ID: BHDU:YEDX:7NMN:QIHK:PFXZ:MWOX:5WZF:FZTK:3RDE:GAEY:U7L2:NP72
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Both command sequences were issued on the same box, a Ubuntu 16.04 LTS running on VMware workstation. Same behaviour on a three-node swarm cluster.

**Comment by faelwar** [comment]
I facing the same problem on 18.02

**Comment by a0s** [comment]
Look like it try to create "new"  host network, not attach to exists! I facing the same problem on 18.02 too. Its broke registrator service for me

**Comment by vdemeester** [comment]
Easily reproductible : 

```
docker service create --network=host nginx
2ye9810ncjqtdqugm2vj9u6vx
overall progress: 0 out of 1 tasks
1/1: only one instance of "host" network is allowed
```

We need to fix that cc @thaJeztah @vieux

**Comment by Stephan-Walter** [comment]
I face the same problem since today.  The update-engine service of my CoreOS run this night and since then I am no longer able to start any service, that require the host network interface.

Since this is a pre-defined I am not able to remove it, what at the end kill my whole Swarm cluster...

From my point of view it is important to fix this problem as fast as possible, since I don't know any solution for the problem now.

Has somebody fixed the problem yet? For example with a downgrade? Or is the only possible solution to reinstall everything?

Regards

PS:


docker network rm host
Error response from daemon: host is a pre-defined network and cannot be removed

**Comment by faelwar** [comment]
I found a workaround where I set the port of my service to host mode and it solved my problem, I hope it can also help you.

**Comment by thaJeztah** [comment]
Host mode publishing is not the same as `--network=host` though.

Looks like this was a regression introduced in https://github.com/moby/moby/pull/30897. Pull request to fix this is being worked on in https://github.com/moby/moby/pull/36316.

**Comment by Stephan-Walter** [comment]
Ok, I solved my problem with the unwanted CoreOS update.

Just follow the instructions at https://coreos.com/os/docs/latest/manual-rollbacks.html

**Comment by albers** [comment]
I can confirm that the issue is fixed in [18.03.0-ce-rc2](https://github.com/docker/docker-ce/releases/tag/v18.03.0-ce-rc2). Thanks @selansen :heart:

**Comment by thaJeztah** [comment]
Great! Thanks for confirming!

**Comment by Stephan-Walter** [comment]
Thx.

I will test it, when a new CoreOS release is available.
