### ISSUE TITLE
Default seccomp profile whitelists `quotactl` on master but has not been ported in release branches.

### ISSUE THREAD

**Issue by pmoust** [moby/moby#36248]
**Description**
https://github.com/moby/moby/pull/34445  added `quotactl(2)` in the default seccomp profile and has been merged on master, however this hasn't been ported in release branches.

**Steps to reproduce the issue:**
```
 ~/elastic/moby   master  git remote -v
origin	git@github.com:pmoust/moby.git (fetch)
origin	git@github.com:pmoust/moby.git (push)
upstream	git@github.com:moby/moby.git (fetch)
upstream	git@github.com:moby/moby.git (push)
 ~/elastic/moby   master  git branch -r --contains bbb401
  upstream/master
 ~/elastic/moby   master  git branch -r --contains cf6e1c5
  origin/f-seccomp-quotacl
  upstream/master
```

**Comment by cpuguy83** [comment]
This is expected, moby doesn't have "releases" except for old release from the docker/docker days.
Releases are handled in github.com/docker/docker-ce.... unfortunately a simply "--contains" won't work on that repo as commits are re-written... but I'd expect this to be in 17.09+ given it was merged in August.

Thanks!

**Comment by pmoust** [comment]
Thanks for the quick response @cpuguy83 - could you point me to the docs describing the release process?

**Comment by cpuguy83** [comment]
https://github.com/docker/docker-ce/blob/master/README.md has some details at least to the branching mechanics.
https://docs.docker.com/install/#time-based-release-schedule for schedule and what goes into what.... not sure if these are what you are looking for.

**Comment by pmoust** [comment]
That's exactly it, my google-fu was failing.
