### ISSUE TITLE
Non-blocking logging causes container LogPath to be an empty string

### ISSUE THREAD

**Issue by mnussbaum** [moby/moby#36255]
**Description**

The container `LogPath` is set to an empty string when the non-blocking logging mode is enabled.

I believe the problem can be traced to [this line](https://github.com/moby/moby/blob/master/container/container.go#L978), when non-blocking logging is enabled the cast at the linked line fails since the logger will be a `RingLogger` and not a `JSONFileLogger`. The logger is set to be a `RingLogger` [here](https://github.com/moby/moby/blob/master/container/container.go#L409). When the cast fails the `LogPath` is silently not set on the container.

**Steps to reproduce the issue:**
1.  `docker run --name test-log-path --log-opt mode=non-blocking -d debian sleep 100000`
2. `docker inspect test-log-path | grep LogPath`
3. Observe `LogPath` set to an empty string

**Describe the results you received:**

`docker inspect` shows `LogPath` set to an empty string.

**Describe the results you expected:**

I expected `LogPath` to look something like `/var/lib/docker/containers/a48d04bbad7e3624152a48e99212257dc86d065e8470324d7722003d8427a682/a48d04bbad7e3624152a48e99212257dc86d065e8470324d7722003d8427a682-json.log`.

**Additional info:**

I noticed this issue because Kubernetes relies on the `LogPath` output to make `kubectl logs` work. As it stands `kubectl logs` is incompatible with Docker's non-blocking logging due to this bug. 

**Output of `docker version`:**

```
Client:                                    
 Version:       17.12.0-ce                 
 API version:   1.35                       
 Go version:    go1.9.2                    
 Git commit:    c97c6d6                    
 Built: Wed Dec 27 20:12:56 2017           
 OS/Arch:       linux/amd64                
                                           
Server:                                    
 Engine:                                   
  Version:      17.12.0-ce                 
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2                    
  Git commit:   c97c6d6                    
  Built:        Wed Dec 27 20:11:32 2017   
  OS/Arch:      linux/amd64                
  Experimental: false                      
```

**Output of `docker info`:**

```
Containers: 22
 Running: 3
 Paused: 0
 Stopped: 19
Images: 982
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-667606-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 20.82GB
 Data Space Total: 107.4GB
 Data Space Available: 14.44GB
 Metadata Space Used: 44.35MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.103GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.71GiB
Name: mnussbaum
ID: WAMT:RW3C:A65N:HFQU:KJIZ:L3XE:UTG7:CRMO:54QJ:YC56:I7SS:Z7WK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by thaJeztah** [comment]
Are you interested in contributing, and opening a pull request to fix this?

**Comment by mnussbaum** [comment]
@thaJeztah indeed interested, just opened the PR at https://github.com/moby/moby/pull/36272!

**Comment by lsylvain** [comment]
It appears that the fix has been checked and no issues have found.  I really need this fix.  Hope it is merged to the master and released soon.
