### ISSUE TITLE
different behaviour in different OS

### ISSUE THREAD

**Issue by vhp1360** [moby/moby#36287]
**Description**

I have one container Image and Import it in 3 different OS : 1-Fedora26, 2-CentOS7 and 3-Ubuntu14
and I got different behaviour of container in all of them.

**Steps to reproduce the issue:**
1. docker run -dit -p 80:80 onlyoffice/documentserver [/bin/bash]
2. try http://IP:80
3. in fedora worked, in centos show message due /etc/hosts permission, in ubuntu show message due postgresql config file problem.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
in Fedora
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.4
 Git commit:      584d391/1.13.1
 Built:           Thu Nov 23 21:40:58 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.4
 Git commit:      584d391/1.13.1
 Built:           Thu Nov 23 21:40:58 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```
in CentOS
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
in ubuntu
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-8:5-9961618-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 96.64 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.9 GB
 Data Space Total: 107.4 GB
 Data Space Available: 95.47 GB
 Metadata Space Used: 9.396 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /home/Docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /home/Docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.14.16-200.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 15.36 GiB
Name: vhp110.domain1001
ID: QBVB:6QD3:K7VE:OOZV:ZUCO:6SLV:2PNF:C7SR:CESM:DNRR:RCOG:SGIQ
Docker Root Dir: /home/Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure)
```
in CentOS
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 33
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:2-19461498655-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 60.07GB
 Data Space Total: 107.4GB
 Data Space Available: 47.3GB
 Metadata Space Used: 66.59MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.081GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 62.64GiB
Name: cloud.shomara.ir
ID: RGUX:UPWF:F3HW:H2M2:CWX5:57A3:BJJS:GTVZ:PFED:FVUK:LPHL:CQPP
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
and ubuntu
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 90
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-139-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.89GiB
Name: shomara
ID: 2KCG:DEDP:B4M5:LQCX:DJSL:547T:4M5T:ARZJ:DPOG:OGIR:HEA2:YE3O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: vhp1360
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

I'm wondering if any one let me know the reason?

thanks.

**Comment by cpuguy83** [comment]
Can you provide the error messages?

Also note that all these versions of docker are quite out of date.

**Comment by eivantsov** [comment]
@vhp1360 please edit your issue with log errors

**Comment by vhp1360** [comment]
great, you are here too :smile:
actually, it did not generate any errors, but when I connect to container and run main command `/app/onlyoffice/run-document-server.sh` I got below:
> * Starting PostgreSQL 9.3 database server                                                                                                                                       * The PostgreSQL server failed to start. Please check the log output:
2018-02-13 07:33:45 UTC LOG:  could not translate host name "localhost", service "5432" to address: Name or service not known
2018-02-13 07:33:45 UTC WARNING:  could not create listen socket for "localhost"
2018-02-13 07:33:45 UTC FATAL:  could not create any TCP/IP sockets
>                                                                                                                                                                         > [fail]
 * Starting message broker rabbitmq-server                                                                                                                                       * message broker already running
>                                                                                                                                                                         > [ OK ]
Starting redis-server: redis-server.
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
^C
 
on centos and on Ubuntu:
> mv: cannot stat ‘/etc/postgresql/9.3/main/postgresql.conf’: No such file or directory
mv: cannot stat ‘/etc/postgresql/9.3/main/pg_hba.conf’: No such file or directory
Creating new cluster 9.3/main ...
  config /etc/postgresql/9.3/main
  data   /var/lib/postgresql/9.3/main
  locale en_US.UTF-8
initdb: could not access directory "/var/lib/postgresql/9.3/main": Permission denied
Error: initdb failed
 * No PostgreSQL clusters exist; see "man pg_createcluster"
 * Starting message broker rabbitmq-server                                       * message broker already running
                                                                         [ OK ]
Starting redis-server: redis-server.
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Network is unreachable
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Network is unreachable
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
^C

**Comment by eivantsov** [comment]
@vhp1360 `/app/onlyoffice/run-document-server.sh` what's in this script?

Please be more specific. 
0. Your OS
1. Start command
2. Output from this command

**Comment by vhp1360** [comment]
I update previous, is it OK?

**Comment by eivantsov** [comment]
@vhp1360 you are some image with some script inside. I don't know anything about it, sorry.

**Comment by vhp1360** [comment]
thanks for your quick replay.
no, one image in three OS.
kindly let me give more explain:
I tried to install [OnlyOffice add](https://github.com/ONLYOFFICE/DocumentServer) in my laptop with fedora26 OS, so tried `docker run -dit -p 80:80 onlyoffice/documentserver /bin/bash`, so container pulled and run, so I browse _http://localhost:80_ and find the server is run.
OK!
so I export it with `docker export ...`, so import it in my Centos7 Server with `docker import ... `,
so tried `docker run -dit -p 80:80 onlyoffice/documentserver /bin/bash` it is ok but when I browse _http://localhost:80_ on centos7 server it showed connection refused, so I login to container by `docker exec ....` and tried to find the reason, OK!
in this step I read the [OnlyOffice Docker File](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/Dockerfile) to find which command should I run to find a problem. as you may find in this file the last line provides `/app/onlyoffice/run-document-server.sh` script to run up all needed services, OK!
but when I run that I faced those errors that I sent before. 
is it clear?

**Comment by eivantsov** [comment]
@vhp1360 I don't see a single line about Eclipse Che here. 

You will get support if you installed Che as per docs - https://www.eclipse.org/che/docs/6/che/docs/docker-single-user.html

**Comment by vhp1360** [comment]
OK! you are right, but I faced the same issue in che container, I test that in ubuntu and centos.
in each of them, I faced a different error, but I could not recognize the issue. but when I work on OnlyOffice I found this.
I tried open this issue for docker team and I found this repo in docker site.
I guessed the Che issue and Onlyffice issue are related to this issue, am I right?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
