### ISSUE TITLE
Command hangs in 17.12/18.02: docker stats

### ISSUE THREAD

**Issue by instantlinux** [moby/moby#36281]
**Description**
After update from 17.09-ce to 17.12.0-ce, _docker stats_ command becomes non-responsive under certain conditions.

**Steps to reproduce the issue:**
1. Set up 3-node swarm with 17.12
2. Start / stop a few services
3. At some point the docker stats command will quit working and stay that way until the affected node is restarted

**Describe the results you received:**
Hang with no output and no log entries

**Describe the results you expected:**
Normal stats of containers.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens to 1 or 2 of my nodes within minutes, every time I restart, but I can't find a specific smoking-gun root cause

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 65
 Running: 20
 Paused: 0
 Stopped: 45
Images: 228
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: data01-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 29.24GB
 Data Space Total: 55.92GB
 Data Space Available: 26.67GB
 Metadata Space Used: 11.92MB
 Metadata Space Total: 104.9MB
 Metadata Space Available: 92.94MB
 Thin Pool Minimum Free Space: 5.592GB
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: g42vocuxnflr78u4r2t2x3j9u
 Is Manager: true
 ClusterID: 48s4nkfptgk54do81dxqz58ny
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.2.64
 Manager Addresses:
  192.168.2.64:2377
  192.168.2.69:2377
  192.168.2.79:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.12-041112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.17GiB
Name: mckinley
ID: MMF5:RQRZ:FSDA:BPDP:TFA2:UDE5:HWRA:6DIH:GEBL:WX3U:6A2P:P6G5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
# uname -a
Linux mckinley 4.11.12-041112-generic #201707210350 SMP Fri Jul 21 07:53:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
{noformat}

**Comment by sorenhansendk** [comment]
Your problems sounds like this one. Docker is not responsive on some commands - i think you need to upgrade docker-ce to the latest version (18.02): https://github.com/moby/moby/issues/35933

**Comment by instantlinux** [comment]
Upgraded to 18.02. Still happens just as often.
```
$ docker stats
  (wait, never finishes)
^C
richb@mckinley:~$ docker version
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by instantlinux** [comment]
One more upgrade, to 18.03.0-ce (stable): same symptom but here's a slight twist: I'd reduced the number of manager nodes from 3 to 1 for the past month to determine whether manager clustering is related to my swarms instability (it really isn't), so 2 days after I upgrade from 18.02 to 18.03 I invoked _docker node promote_ to bring manager count back up to 3.

Bam, that's what triggered this _docker stats_ hang this time.

**Comment by djonnala** [comment]
We are not using docker swarm but are using another orchestrator to deploy containers onto the servers. We face the same issue, the command "docker stats" hangs without any output. It is only resolved when we restart the docker service. @instantlinux did you find any root cause to this issue? 

Docker Version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by lwimmer** [comment]
We also see this happening with `docker stats` sometimes. We are deploying with docker swarm.

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
