### ISSUE TITLE
Can not disable journald logging

### ISSUE THREAD

**Issue by Vladimir-csp** [moby/moby#36286]
I can not disable logging to journald.

**Steps to reproduce the issue:**
1. set log-driver to "json-file" in daemon.json
2. restart docker service
3. check `journalctl -f`

**Describe the results you received:**
messages from containers are still logged into journal

**Describe the results you expected:**
messages from containers are not being logged into journal

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker-ce 17.12.0-ce on CentOS 7

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, CentOS 7

**Comment by cpuguy83** [comment]
This is expected.
They daemon config only sets the default for new containers. Once a container is created the logging driver does not change.
