### ISSUE TITLE
docker pull full layer of image even base image already on the host

### ISSUE THREAD

**Issue by xujihui1985** [moby/moby#36309]
when pull image from our on-premise registry on a host that has already pulled base image, it still perform a full download even there is only one layer different, the interesting is when I delete the derived image then pull again, it will only pull the difference

**Steps to reproduce the issue:**
1. pull base image, build a new image base on that base image and push to registry
2. on a brand new host, pull the base image first, then pull the newly created image

**Describe the results you received:**
it pull all layers even base image has already on the host
this is inspect from base image
![image](https://user-images.githubusercontent.com/1619030/36186262-ea901204-1178-11e8-9c42-0ae48163d549.png)

this is inspect from derived image 
![image](https://user-images.githubusercontent.com/1619030/36186269-f5cfbfb6-1178-11e8-8e68-2f38102a16af.png)

there is only on layer difference

![image](https://user-images.githubusercontent.com/1619030/36186399-ca32d586-1179-11e8-8398-bf1cb80b8a66.png)

when I delete the derived image, it will only delete the difference

![image](https://user-images.githubusercontent.com/1619030/36186627-2cf135d6-117b-11e8-8e92-0cecccd55bcb.png)

then pull again

![image](https://user-images.githubusercontent.com/1619030/36186635-44c2c4f4-117b-11e8-85fb-f3138b953291.png)

that's obvious that most of the layers are identical, and shared by both base and derived image.

**Describe the results you expected:**
only pull diff layers

**Additional information you deem important (e.g. issue happens only occasionally):**
the base image and derived image are pushed to registry by two different account

**Output of `docker version`:**

```
Docker version 1.11.1
```

**Output of `docker info`:**

```
Containers: 12
 Running: 8
 Paused: 0
 Stopped: 4
Images: 127
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.71 GiB
Name: srmbuffer010210212101.ztt
ID: 3PZ4:7DWX:4TPZ:A4FV:MZT5:W5EM:TZYA:45OC:PQXG:M4QZ:MVHK:45XT
Docker Root Dir: /home/acs/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Live Restore Enabled: true
```

**Comment by xujihui1985** [comment]
after some investigation, I have some clue on this.

1. when push to remote registry, docker will check if the layer could be mount from remote registry from `v2metadata-by-diffid/sha256/diffID`

2. when I push to registry without login, it will failed to push the layer to registry, so the `metadata-by-diffid` will be deleted by this code
![image](https://user-images.githubusercontent.com/1619030/36781352-9a4a2850-1cb0-11e8-97ab-52c7c59e2903.png)

3. then I login again and push to registry, it can not find the remote registry to mount, so it repackage the layer.tar, and push to registry. 

everything is fine until the base image was pushed on a old version of docker (with old version of golang) and derived image was pushed on a new version of docker.
https://github.com/golang/go/blob/c9517b1ffe7c99a3fd2a748fab51645bd674ad75/src/compress/gzip/gzip.go#L159
https://github.com/golang/go/blob/cba4b416719f7019ecc01a02d8efbf0c9c0e5df9/src/compress/gzip/gzip.go#L157
with old version of golang, it will attach current timestamp to the header of gzip, so, when I push the image on a new version of docker, the sha256 of gziped layer was changed, this can be confirmed by
the content of gzip 
![image](https://user-images.githubusercontent.com/1619030/36781588-3f16ce56-1cb1-11e8-9195-547db6e29b8d.png)

**Comment by thaJeztah** [comment]
ping @dmcgowan @stevvooe PTAL

**Comment by dmcgowan** [comment]
This is a tough one. The metadata which is mentioned is not guaranteed to exist and gets cleaned up rather aggressively in this case to prevent caching more metadata than might be used. Login error tends to be a good indicator that the cache value is no good, but in this case where there was no login information at all then removal should probably be prevented.

**Comment by xujihui1985** [comment]
what about fail early if user hasn't login? before push the layer, if authconfig is empty which means no login, then fail the push loudly?

**Comment by dmcgowan** [comment]
@xujihui1985 it might not be a suggested configuration, but registries are not required to have authentication for push. This is common for local setups or might be legitimately used inside some environments.

**Comment by xujihui1985** [comment]
@dmcgowan right, when failed to push to register, check the error and `if (it is auth error && authconfig is empty)` then log and do nothing?

**Comment by xujihui1985** [comment]
@dmcgowan I would like to send my first contribute to this awesome project if you think this is needed to be fixed

**Comment by xujihui1985** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
> if you think this is needed to be fixed

I think this should be fixed. I agree with your suggestion, we shouldn't clear out the cached value if it was an auth error and no auth was provided.

**Comment by xujihui1985** [comment]
@dmcgowan  I have send a PR for you to review, glad to hear your reply
