### ISSUE TITLE
Swarm very sensitive to transient network issues

### ISSUE THREAD

**Issue by markvr** [moby/moby#36311]
I'm not sure if this is a bug or feature request!

**Description**

Summary:  Can Swarm be configured with a minimum heartbeat timeout before a node is marked as failed?

We run Swarms on Azure, and occasionally swarm detects a node as failed and restarts all the tasks elsewhere which is quite disruptive.

The underlying reasons for the failed heartbeat are being investigated (possibly caused by the Azure networking, or the VM being moved between Azure hosts), but as a diagnostic we also ping all the nodes every sec from the managers, and each time the worker only drops a few pings, which is about <5sec offline.  This seems to be long enough for Swarm to mark the node as failed.

Obviously there is a balance between quickly detecting a genuinely failed node, and over reacting to a transient issue.   We would like to adjust the sensitivity to allow nodes more time to recover before they are marked as failed.

I can't see any [settings](https://docs.docker.com/engine/reference/commandline/dockerd/) for this.

**Steps to reproduce the issue:**
Run a Swarm in a situation where there are brief networking issues of < 5sec

**Describe the results you received:**
Nodes are very quickly marked as failed.

**Describe the results you expected:**
Swarm to be more tolerant of transient failures.

**Additional information you deem important (e.g. issue happens only occasionally):**
logs:

```
Worker
Feb 14 00:03:48 npt-prod-wrk000001 dockerd[830]: time="2018-02-14T00:03:48.005409561Z" level=error msg="agent: session failed" error="rpc error: code = 4 desc = context deadline exceeded" module="node
Feb 14 00:03:50 npt-prod-wrk000001 dockerd[830]: time="2018-02-14T00:03:50.775602528Z" level=info msg="memberlist: Suspect npt-prod-mgr000002-0e0c32933e67 has failed, no acks received"
Feb 14 00:03:53 npt-prod-wrk000001 dockerd[830]: time="2018-02-14T00:03:53.011134792Z" level=error msg="agent: session failed" error="session initiation timed out" module="node/agent" node.id=3j6cafbg
Feb 14 00:03:58 npt-prod-wrk000001 dockerd[830]: time="2018-02-14T00:03:58.047990575Z" level=error msg="agent: session failed" error="session initiation timed out" module="node/agent" node.id=3j6cafbg
Feb 14 00:04:01 npt-prod-wrk000001 dockerd[830]: time="2018-02-14T00:04:01.277757556Z" level=info msg="memberlist: Suspect npt-prod-mgr000001-0d4dae99916c has failed, no acks received"


Manager
Feb 14 00:03:55 npt-prod-mgr000000 dockerd[805]: time="2018-02-14T00:03:55.295714219Z" level=info msg="memberlist: Suspect npt-prod-wrk000001-4038a9562c48 has failed, no acks received"
Feb 14 00:03:57 npt-prod-mgr000000 dockerd[805]: time="2018-02-14T00:03:57.393511983Z" level=info msg="Node npt-prod-wrk000001-4038a9562c48/10.240.4.8, left gossip cluster"
```

**Output of `docker version`:**

```
[root@npt-prod-wrk000001 neptune]# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
[root@npt-prod-wrk000001 neptune]# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@npt-prod-wrk000001 neptune]# docker info
Containers: 27
 Running: 2
 Paused: 0
 Stopped: 25
Images: 20
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 3j6cafbgq6beinjono48to09k
 Is Manager: false
 Node Address: 10.240.4.8
 Manager Addresses:
  10.240.4.4:2377
  10.240.4.6:2377
  10.240.4.7:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.797GiB
Name: npt-prod-wrk000001
ID: AN5Z:XL64:3P3B:NCFL:USGO:UQYJ:YEP4:65EU:E3NS:PQ7U:TKNV:ZFLB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure

**Comment by cpuguy83** [comment]
I believe you want `docker swarm update --dispatcher-heartbeat <duration>`, which defaults to 5s.

**Comment by markvr** [comment]
Ah yes!  I've dome some testing with changing that and it seems to do the job.  I read loads of (long!) github issues about swarm problems and nowhere did I find that mentioned.   thanks!

**Comment by cpuguy83** [comment]
Awesome, glad it worked!

**Comment by thaJeztah** [comment]
@markvr It looks like the documentation doesn't really describe the purpose of this option, other than:

[Swarm init reference](https://docs.docker.com/engine/reference/commandline/swarm_init/#usage)

> `--dispatcher-heartbeat`
> This flag sets the frequency with which nodes are told to use as a period to report their health.

[UCP trouble shooting](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-node-messages/#ucp-node-states) briefly mentions heartbeat issues (may not be related to this option);

> "Unhealthy UCP Controller: node is unreachable"
> Other manager nodes of the cluster have not received a heartbeat message from the affected node within a predetermined timeout. This usually indicates that there’s either a temporary or permanent interruption in the network link to that manager node. Ensure the underlying networking infrastructure is operational, and contact support if the symptom persists.


Could you perhaps open an issue in the documentation issue tracker (https://github.com/docker/docker.github.io/issues)? (Or perhaps you're interested in contributing, and opening a PR to the documentation? Could possibly go into this page: https://docs.docker.com/engine/swarm/admin_guide/#distribute-manager-nodes)

**Comment by markvr** [comment]
I'm of course happy to open an issue in the docs tracker, I'm afraid  I wouldn't feel confident about being correct enough to write a PR.  

It would help to have this option highlighted in the docs, because a number of the issues I read about swarm seemed to involve nodes being transiently "unreliable" and the swarm possibly overreacting.

My issue was with the worker nodes, I don't know if the same docs would apply to the managers.  

thanks for the help!

**Comment by thaJeztah** [comment]
Yes, some explanation about "when", and "why" to change the default value would definitely make sense to add 👍
