### ISSUE TITLE
Auth plugins recieve empty request bodies when content-type of request contains charset.

### ISSUE THREAD

**Issue by nathanburrell** [moby/moby#36317]
If you submit a request to create a container (POST /containers/create) with a specific content type (Content-Type: application/json; charset=utf-8), than an empty request body is forwarded to the auth plugin, effectively not allowing the auth plugin to verify the request (if said auth plugin uses the body to perform authentication).

The bug is in how the auth plugin handler API determines whether or not to send the body to auth plugins (specifically on line 156 of https://github.com/moby/moby/blob/master/pkg/authorization/authz.go).

The check does a straight string comparison of the content-type with the hard coded string "application/json". This should also be able to handle charsets as specified in https://www.w3.org/International/articles/http-charset/index.

Other parts of the docker code base ([httputils.CheckJson](https://github.com/moby/moby/blob/master/api/server/httputils/httputils.go ) or using golangs  [mime.ParseMediaType](https://golang.org/pkg/mime/)) already perform different logic to verify the content-type header succesfully, this line of code should be modified to perform the same (or similar) logic.

Steps to reproduce:
1. Install the debug auth plugin I created to demonstrate this (it simply logs the content length, content type and the length of the body).

https://bitbucket.org/nburrell/authz/src/master/

2. Post the following request to docker (note the content-type is simply **"application/json"**) and note the length of the body being the same as the content length in the request:

`curl -X POST -H 'Content-Type: application/json' -d '{"ExposedPorts":{"9324/tcp":{}},"HostConfig":{"Binds":["/opt/atlassian/pipelines/agent/build/application/src/test/resources/elasticmq.conf:/elasticmq.conf"],"PortBindings":{"9324/tcp":[{"HostPort":"9324"}]},"VolumesFrom":[]},"Image":"graze/sqs-local","Labels":{"dmp.coordinates":"com.atlassian.pipelines:agent-service-application:2.449-SNAPSHOT"},"Volumes":{"/elasticmq.conf":{}}}' http://localhost:2375/v1.18/containers/create
`

3. Post the following request to docker (note the content-type in this one is **"application/json; charset=utf-8"**) and note the length of the body being 0, even though the content length is correct:

`curl -X POST -H 'Content-Type: application/json; charset=utf-8' -d '{"ExposedPorts":{"9324/tcp":{}},"HostConfig":{"Binds":["/opt/atlassian/pipelines/agent/build/application/src/test/resources/elasticmq.conf:/elasticmq.conf"],"PortBindings":{"9324/tcp":[{"HostPort":"9324"}]},"VolumesFrom":[]},"Image":"graze/sqs-local","Labels":{"dmp.coordinates":"com.atlassian.pipelines:agent-service-application:2.449-SNAPSHOT"},"Volumes":{"/elasticmq.conf":{}}}' http://localhost:2375/v1.18/containers/create
`

Also note the docker client isnt affected by this as it always sets the content-type to "application/json" however other docker clients such as [fabric8io/docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) include the charset and thus cannot interact with the docker daemon that uses auth plugins correctly.

**Comment by LautaroJayat** [comment]
I think this was fixed in
https://github.com/moby/moby/pull/36778

The diff is here: https://github.com/moby/moby/commit/6ac73d34e4d8f2b6303f0ed49b58d0a92c19c6f1#diff-4fba707264ab4bc4865e42234a95bb4a749e2e28b1156ced9e225f4a8920e320R156-R162

This issue can be closed :)
