### ISSUE TITLE
Docker fatal error if one of the containers have no more memory

### ISSUE THREAD

**Issue by jpdeplaix** [moby/moby#36324]
**Description & Steps to reproduce the issue:**

I'm using docker on an ARM64 cluster with 32Go of RAM.
If there is no more memory available, the docker container(s) will crash with the following error message:
```ERRO[13582] error waiting for container: unexpected EOF```

Now if I try to avoid this error by using the swap using ```--memory-swap -1``` on all ```docker build``` and ```docker run``` processes, it works well.

Now, if I try to spawn a docker container without ```--memory-swap -1``` (for instance by just building something on the side) while being in a state where there is no more memory the ```docker build``` process will crash with:
```docker: Error response from daemon: connection error: desc = "transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout".```

And now I can't spawn any more containers without running into the timeout error above, even with the memory-swap on. The only way I found to exit this state is to reboot the machine, sadly.

**Describe the results you received:**

Can't spawn any more containers (or even most of the docker subcommands) without running into the timeout error message.

**Describe the results you expected:**

A state where I can run docker subcommands without an error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:07:05 2017
 OS/Arch:	linux/arm64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:05:10 2017
  OS/Arch:	linux/arm64
  Experimental:	false
```

**Comment by thaJeztah** [comment]
Wonder if this is the same issue as https://github.com/moby/moby/issues/36002; i.e. if the host ran out of memory and the kernel killed containerd

**Comment by jpdeplaix** [comment]
I just noticed that the fix has been released in 17.12.1.
I'm trying right now, I'll let you know if anything going wrong or I'll close this issue if the issue is really fixed.

**Comment by jpdeplaix** [comment]
Looks like it's fixed. Thanks a lot !

**Comment by thaJeztah** [comment]
Whoop, good to hear!

**Comment by Hockery** [comment]
I have rebooted my ubuntu system. then everything is ok.
