### ISSUE TITLE
Docker uses all CPU resources when Ubuntu comes from disk-suspension (restore hibernation)

### ISSUE THREAD

**Issue by asfernandes** [moby/moby#36347]
Docker version 17.12.0-ce, build c97c6d6

On this day I didn't even used docker:

```
top output:

  PID USUÁRIO  PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                     
 1645 root      20   0  807636  31948  12052 S 243,7  0,2  60:23.87 dockerd                                                                                                                                                                                                     
```

```
docker info:

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 78
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65GiB
Name: cheetah
ID: MNIK:QOEN:FBBJ:TS33:W5YV:ESH5:X3FG:XFZ2:4QMV:TX5W:DOE6:YMT2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Would you be able to collect information where the CPU is used? If possible, could you send a `SIGUSR1` to the `dockerd` and `docker-containerd` processes, which would write a stack-dump to the logs. Possibly this requires the daemon to be in debug mode

**Comment by gasparhugoricardo** [comment]
Hi!

Also experiencing problems with CPU usage. It started a couple of weeks ago and I can't seem to overcome the issue. The only thing I've been doing is restarting docker, but I can't do this in a production environment...

top output:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11316 root      20   0  590060  42848   9168 S 120.3  0.5 215:58.95 dockerd

Docker info:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64GiB
Name: *****************
ID: KRHN:NM5P:MYAN:OQZP:SORJ:A6AW:G35X:S3QD:WCR2:MFTA:IB5A:IZYM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by H4ndl3** [comment]
I'm having the same problem. Hopefully these logs help @thaJeztah.
[strace_dockerd.log](https://github.com/moby/moby/files/1786519/strace_dockerd.log)
[stackdump_docker-containerd.log](https://github.com/moby/moby/files/1786520/stackdump_docker-containerd.log)
[stackdump_dockerd.log](https://github.com/moby/moby/files/1786521/stackdump_dockerd.log)

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  I you encounter this issue on a current engine release, please open a new issue.
