### ISSUE TITLE
Mac OS: ext4 docker volume mount not observed

### ISSUE THREAD

**Issue by getkub** [moby/moby#36345]
MAC OS (high sierra) : volume creation not observing ext4 filesystem

**Steps to reproduce the issue:**

- Step 1 : Create volumes with type=ext4 
```
docker volume create --driver local --opt type=ext4 --opt device=/tmp/splunk/etc --opt o=bind --name=opt_splunk_etc
docker volume create --driver local --opt type=ext4 --opt device=/tmp/splunk/var --opt o=bind --name=opt_splunk_var
```

- Step 2 : Ensure the volumes are created and inspect it to be ext4

```
docker volume ls
docker volume inspect opt_splunk_etc opt_splunk_var
```

- Step 3 : Map the internal Splunk directories to these filesystem using busybox
`docker run --name vsplunk -v opt_splunk_etc:/opt/splunk/etc -v opt_splunk_var:/opt/splunk/var busybox
`
- Step 4 : Now run splunk as a container. 
`docker run --hostname splunk --name splunk --volumes-from=vsplunk -p 8000:8000 -e "SPLUNK_START_ARGS=--accept-license" splunk/splunk:latest`

All these steps work perfectly in Linux OS

**Describe the results you received:**
When I start the application, it detects that the filesystem is NOT ext4. Splunk normally supports most of filesystem but not APFS

`homePath='/opt/splunk/var/lib/splunk/audit/db' of index=_audit on unusable filesystem.
`
**Describe the results you expected:**
Expected the filesystem to be ext4 format, so application (Splunk) starts normally.  Also if I disable strict checks from Splunk (`OPTIMISTIC_ABOUT_FILE_LOCKING = 1`)  it works perfectly. So something is telling Splunk that the filesystem is not yet ext4

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
Total Memory: 1.952GiB
Name: linuxkit-025000000001

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Setting "type=ext4" is not really doing anything. I bind mount takes a file/for inode and mounts it to a other location. It can't set a filesystem type.

I'm a little surprised this doesn't give an "invalid argument" error from the kernel... But perhaps the codepath for bind mounts ignores the type param.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
