### ISSUE TITLE
TestExecResizeImmediatelyAfterExecStart ignores all errors except EOF

### ISSUE THREAD

**Issue by dnephin** [moby/moby#36354]
https://github.com/moby/moby/blob/733ed2ddd3c621dadafbb74feb7b80d20fd3fd6f/integration-cli/docker_api_exec_resize_test.go#L68-L79

This test should be rewritten to test the success case of resize after start, instead of a specific regression that is unlikely to happen ever again.

**Comment by thaJeztah** [comment]
fixed by https://github.com/moby/moby/pull/37172
