### ISSUE TITLE
With loopback storage engine, loop devices make corrupted FSes

### ISSUE THREAD

**Issue by rlpowell** [moby/moby#36356]
**Description**

In a --privileged=true docker using the loopback storage engine, file-backed filesystems become corrupted when the system running docker is on more recent kernels.

**Steps to reproduce the issue:**
1.  Be on a system running 4.1.12-94.5.7.el7uek or earlier (yes, I know it's UEK, but that's all I've got access to; I expect it'll be the same with any kernel of similar vintage; it does *not* happen on 4.1.12-94.3.8.el7uek , or any earlier kernel I've tested)
2.  Launch docker with: sudo docker run -i -t --privileged=true --name=bad-fs-test oraclelinux:7.4 /bin/bash
3.  Inside said docker, run the following script:

—————
#!/bin/bash

yum install -y e2fsprogs

for num in $(seq 0 32)
do
        mknod /dev/loop$num b 7 $num
        chmod 644 /dev/loop$num
done

umount /tmp/test_fs_crap_mnt1
rm -rf /tmp/test_fs_crap /tmp/test_fs_crap_mnt1 /tmp/test_fs_crap_workdir
mkdir /tmp/test_fs_crap /tmp/test_fs_crap_mnt1 /tmp/test_fs_crap_workdir

touch /tmp/test_fs_crap/file
for num in $(seq 1 100)
do
        echo 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' >>/tmp/test_fs_crap/file
done

for num in $(seq 1 100)
do
        cp /tmp/test_fs_crap/file /tmp/test_fs_crap/file.$num
done

dd if=/dev/zero of=/tmp/test_fs_crap_workdir/rootfs.img bs=1M count=512
dev=$(losetup --find --show /tmp/test_fs_crap_workdir/rootfs.img)
mkfs.ext4 -L Anaconda -b 1024 -m 0 $dev
mount $dev /tmp/test_fs_crap_mnt1
cp -a /tmp/test_fs_crap /tmp/test_fs_crap_mnt1
echo "INITIAL RUN BAD FILES (should be none):"
md5sum /tmp/test_fs_crap_mnt1/test_fs_crap/* | grep -v 1c6476f2621cf8e36a8d2b8e6abea999 | wc -l
umount /tmp/test_fs_crap_mnt1
losetup --detach $dev
sync

for num in $(seq 1 10)
do
        mount -o loop /tmp/test_fs_crap_workdir/rootfs.img /tmp/test_fs_crap_mnt1
        echo "RUN NUMBER $num BAD FILES:"
        md5sum /tmp/test_fs_crap_mnt1/test_fs_crap/* | grep -v 1c6476f2621cf8e36a8d2b8e6abea999
        umount /tmp/test_fs_crap_mnt1
        sync
        sleep 2
done

—————

**Describe the results you received:**

Every mount of the file system except the first is corrupt in semi-random ways.

**Describe the results you expected:**

No corruption.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was discovered because I was using docker to build boot images for PXE.

It does *not* happen on the overlay2 storage engine.  It does not happen on a 2.6 kernel.  It *does* happen on at least 3 wildly different versions of docker, so I don't think that's relevant.

I have *no idea* if this is actually a docker problem, or a kernel problem, or what, but if you run the same script *outside* of docker, it's fine, so this seemed like a good place to start.

**Output of `docker info`:**

```
$ sudo docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-249:0-786639-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.822GB
 Data Space Total: 107.4GB
 Data Space Available: 104.6GB
 Metadata Space Used: 2.036MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-94.5.7.el7uek.x86_64
Operating System: Oracle Linux Server 7.4
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.5GiB
Name: [snip]
ID: [snip]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
[snip]
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker is running on physical hardware running Oracle Enterprise Linux 6.

**Comment by rlpowell** [comment]
Example output, by the way:

```
RUN NUMBER 9 BAD FILES:
be06776c2a48ffedf0e01172fa0e9c5f  /tmp/test_fs_crap_mnt1/test_fs_crap/file.12
be06776c2a48ffedf0e01172fa0e9c5f  /tmp/test_fs_crap_mnt1/test_fs_crap/file.28
be06776c2a48ffedf0e01172fa0e9c5f  /tmp/test_fs_crap_mnt1/test_fs_crap/file.44
be06776c2a48ffedf0e01172fa0e9c5f  /tmp/test_fs_crap_mnt1/test_fs_crap/file.60
a0b4970959fc907b2fd95870cc00a155  /tmp/test_fs_crap_mnt1/test_fs_crap/file.76
9639744db484d652d3c204f1454d996b  /tmp/test_fs_crap_mnt1/test_fs_crap/file.92
```

Those lines represent places where the script-generated files, which consist of only lines with the letter "a" in them, instead of looking correct look like this:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a~C^A^@k^H^@r^^@t^D^@}^H^@n^F^@t^E^@}^H^@x�^B|^C^@~C^@^@}       ^@|     ^@d^@^@k^H^@r~@^@Pn^@^@|        ^@r^O^C|        ^@d^B^@^Yd^D^@k^B^@r^O^C|       ^@d^E^@d^F^@!}
^@|
^@d^G^@k^B^@r�^Ad^C^@}^K^@|^B^@j^G^@d^H^@~C^A^@r^H^AxA^@|^C^@~C^@^@}^L^@|^L^@d^@^@k^H^@r[34m^@t^H^@d       ^@~B^B^@n^@^@|^L^@d
^@k^B^@r�^@Pn^@^@|^K^@|^L^@^W}^K^@q[34m^@n^@^@|^K^@s^Z^At^H^@d^K^@~B^B^@n^@^@y(^@t ^@|^K^@~C^A^@}^M^@|^M^@d^B^@k^@^@rA^At^H^@d^L^@~B^B^@n^@^@WnW^@^Dt
^@k
^@r~[^A^A^A^At^K^@|^K^@~C^A^@sj^At^H^@d^M^@~B^B^@n^@^@y^Q^@|^A^@j^L^@|^K^@^Y}^M^@Wq~\^A^Dt^M^@k
```

**Comment by AkihiroSuda** [comment]
@rhvgoyal @cyphar PTAL?

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637
