### ISSUE TITLE
Question: How to build an image using the API and a git repository?

### ISSUE THREAD

**Issue by deviantony** [moby/moby#36398]
Hiya there, did not find any existing issue about this.

Checking the documentation of the ImageBuild operation (https://docs.docker.com/engine/api/v1.34/#operation/ImageBuild), it looks like you can specify an URI to a Git repository via the `remote` parameter.

> A Git repository URI or HTTP/HTTPS context URI. If the URI points to a single text file, the file’s contents are placed into a file called Dockerfile and the image is built from that file. If the URI points to a tarball, the file is downloaded by the daemon and the contents therein used as the context for the build. If the URI points to a tarball and the dockerfile parameter is also specified, there must be a file with the corresponding path inside the tarball.

Although it's only specified at the beginning of this sentence and no other details are provided.

When trying to execute a HTTP request with that parameter pointing to a Git repository containing a Dockerfile, I'm getting an error. Is that possible at all or is it just an error in the docs?

Request example:

```
Request URL: <DOCKER_API>/build?dockerfile=base%2FDockerfile&remote=https:%2F%2Fgithub.com%2Fportainer%2Fdocker-images&t=testimage:test
```

Using the following parameters:

```
t=testimage:test
remote=https://github.com/portainer/docker-images
dockerfile=base/Dockerfile
```

Response:

```
{"message":"error detecting content type for remote https://github.com/portainer/docker-images: unsupported Content-Type \"text/html; charset=utf-8\""}
```

**Comment by cpuguy83** [comment]
This looks like it is  because you have it a URL to a web page rather than the actual git repository.
I don't remember off the top of my head if this works, but... You'll want to get the URL from the "clone repo" section on the GitHub page.

**Comment by deviantony** [comment]
Indeed, using `remote=https://github.com/portainer/docker-images.git` instead of `remote=https://github.com/portainer/docker-images` actually works. Thanks for the answer !
