### ISSUE TITLE
docker bridge IP disappears after docker service is stopped

### ISSUE THREAD

**Issue by Vishant0031** [moby/moby#36403]
In previous of docker(< 1.12.6) the docker bridge IP persists even after docker service.

```
===================================================================
~ $ docker -v
Docker version 1.11.2, build bac3bae
~ $ ip a show dev cbr0
8: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:18:77:37:b6:f3 brd ff:ff:ff:ff:ff:ff
    **inet 10.109.31.193/26 brd 10.109.31.255 scope global cbr0**
       valid_lft forever preferred_lft forever
    inet6 fe80::3027:25ff:fec1:e767/64 scope link 
       valid_lft forever preferred_lft forever
~ $ systemctl status docker|grep Active
   Active: active (running) since Sat 2018-02-24 14:51:49 UTC; 1h 4min ago

~ $ cat /etc/systemd/system/docker.service.d/03-docker_param_fix.conf
[Service]
Environment="DOCKER_OPTS=-b cbr0 --fixed-cidr=10.109.31.193/26    --log-opt max-size=1536m --log-opt max-file=5 --iptables=false"
~ $ 
~ $ sudo systemctl stop docker
~ $ ip a show dev cbr0
8: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:18:77:37:b6:f3 brd ff:ff:ff:ff:ff:ff
    **inet 10.109.31.193/26 brd 10.109.31.255 scope global cbr0**
       valid_lft forever preferred_lft forever
    inet6 fe80::3027:25ff:fec1:e767/64 scope link 
       valid_lft forever preferred_lft forever
===================================================================
```

While in docker version 1.12.6 and  17.09.0-ce, the docker bridge IP disappears after docker service is stopped.

```
===================================================================
 # docker -v
Docker version 17.09.0-ce, build afdb6d4

#  systemctl status docker|grep Active
   Active: active (running) since Sat 2018-02-24 16:03:52 UTC; 1min 53s ago

# ip a show dev cbr0
33810: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:a8:42:0a:37:48 brd ff:ff:ff:ff:ff:ff
    **inet 10.1.16.193/26 brd 10.1.16.255 scope global cbr0**
       valid_lft forever preferred_lft forever
    inet6 fe80::b094:edff:fe3e:720a/64 scope link 
       valid_lft forever preferred_lft forever
 # cat /etc/systemd/system/docker.service.d/03-docker_param_fix.conf
[Service]
Environment="DOCKER_OPTS=-b cbr0 --fixed-cidr=10.1.16.193/26   --iptables=false --log-opt max-size=1536m --log-opt max-file=5"

# systemctl stop docker
#  systemctl status docker|grep Active
   Active: inactive (dead) since Sat 2018-02-24 16:07:23 UTC; 20s ago

 # ip a show dev cbr0 **<======= the IP on cbr0 is disappeared.**
33810: cbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 02:a8:42:0a:37:48 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b094:edff:fe3e:720a/64 scope link 
       valid_lft forever preferred_lft forever
===================================================================
```

**Comment by thaJeztah** [comment]
I think this has been a bugfix; if docker created the bridge, it also cleans up the bridge it created. If you create your own bridge in advance, and tell docker to use it, docker will not cleanup that bridge (see https://github.com/docker/libnetwork/pull/1301).

Can you describe the problem this is causing you?

**Comment by Vishant0031** [comment]
@thaJeztah 
(>>this has been a bugfix)
you mean the behavior of docker bridge I reported here is a expected?

As we can see, as per my configuration there is custom bridge created, cbr0. with its own cidr defined.

**Comment by Vishant0031** [comment]
@thaJeztah 
I did not understand the issue docker/libnetwork#1301
it seems in the issue libnetwork#1301, there is an overlay bridge network created (docker network create). But in my case the bridge is used by docker daemon to start the docker service.

**Comment by Vishant0031** [comment]
After I start docker again, docker containers have 172.x IP (the default IP range) though the docker cidr is set as --fixed-cidr=10.109.31.193/26 .

~$ systemctl status docker|grep Active
   Active: active (running) since Sat 2018-02-24 17:15:15 UTC; 11min ago

~$ ip a show dev cbr0
33810: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:a8:42:0a:37:48 brd ff:ff:ff:ff:ff:ff
    inet 10.1.16.193/26 brd 10.1.16.255 scope global cbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::b094:edff:fe3e:720a/64 scope link 
       valid_lft forever preferred_lft forever

~$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "9aaad596101a17118c197a75782320b5ece58028d66e1deeb1d16450b75bdad1",
        "Created": "2018-02-24T17:15:08.143625319Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    **"Subnet": "172.17.0.0/16",
                    "IPRange": "10.1.16.192/26",
                    "Gateway": "172.17.16.192"**
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "cbr0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

**Comment by Vishant0031** [comment]
@thaJeztah 
also , in previous version of docker, the custom bridge does not get deleted with stop/start of docker.
as we can see cbr0 state above (the actual bug report with out put from docker <1.12)

**Comment by thaJeztah** [comment]
> After I start docker again, docker containers have 172.x IP (the default IP range) though the docker cidr is set as --fixed-cidr=10.109.31.193/26 . Following is detailed command output, you can see docker bridge subnet is set to 172.x "Subnet": "172.17.0.0/16" but the subnet is set to 10.x IP.

Was this different in < 1.12? Not sure if that setting was intended to configure the other options, or only to restrict the range within the subnet. I'd have to check that with the networking team.


> also , in previous version of docker, the custom bridge does not get deleted with stop/start of docker. as we can see cbr0 state above (the actual bug report with out put from docker <1.12)

Trying to reproduce this (creating a [custom bridge](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/build-bridges/))

Stop docker

```
systemctl stop docker
```

Create custom bridge

```
ip link add name foobridge0 type bridge
ip addr add 192.168.5.1/24 dev foobridge0
ip link set dev foobridge0 up
```

Check the bridge configuration:

```
ip addr show foobridge0
4: foobridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether a2:53:21:bc:7a:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.1/24 scope global foobridge0
       valid_lft forever preferred_lft forever
    inet6 fe80::a053:21ff:febc:7a00/64 scope link 
       valid_lft forever preferred_lft forever
```

Configure the daemon to use this bridge, and start the daemon:

```
mkdir -p /etc/docker
echo '{"bridge": "foobridge0"}' > /etc/docker/daemon.json
systemctl start docker
```

Check the bridge's IP addres

```
ip addr show foobridge0
4: foobridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether a2:53:21:bc:7a:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.1/24 scope global foobridge0
       valid_lft forever preferred_lft forever
    inet6 fe80::a053:21ff:febc:7a00/64 scope link 
       valid_lft forever preferred_lft forever
```

And the configuration of the default "bridge" network:

```
docker network inspect bridge --format '{{json .IPAM.Config}}'
[{"Subnet":"192.168.5.0/24","Gateway":"192.168.5.1"}]
```


Stop the daemon:

```
systemctl stop docker
```

And check the bridge:

```
ip addr show foobridge0
4: foobridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether a2:53:21:bc:7a:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.1/24 scope global foobridge0
       valid_lft forever preferred_lft forever
    inet6 fe80::a053:21ff:febc:7a00/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by Vishant0031** [comment]
@thaJeztah 
in the above steps to create the bridge, I do another step of setting the mac address using command:
ip link set <bridge-if> addr <my mac address>
(ip link set cbr0 addr 02:a8:42:0a:27:b7)
 
if you set specifically the mac address to the docker bridge interface this issue if seen always.

**Comment by Vishant0031** [comment]
@thaJeztah 
-It seems like docker (or mostly the libnetwork) is unsetting the IP parameters on the docker bridge.
This is not ok atleast when the docker bridge was created by the user.

-Another related issue here is, restart of docker creates docker0 default bridge but it does not uses it.

-When the docker is started again, the IPAM configuration is completely broken, with docker using default subnet of 172.x and ignores the  user defined --fixed-cidr input argument.
docker network inspect bridge --format '{{json .IPAM.Config}}'
[{"Subnet":"172.17.0.0/16","IPRange":"10.1.15.192/26","Gateway":"172.17.15.192"}]


Overall, it seems docker v17.x is unstable release of docker.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
