### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish. could translate your text documents

### ISSUE THREAD

**Issue by UlisesTJ** [moby/moby#36404]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for you offer @UlisesTJ - translation/localization has been discussed in the past, but we decided to keep everything in English only for now. Reason for this is that all the code itself is in English, and we wouldn’t have the bandwidth to maintain translations in multiple languages.

I’ll close this issue, but thanks again, and feel free to continue the conversation
