### ISSUE TITLE
Dockerfile: use build-args to allow overriding binary-commits (and more)

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#36412]
https://github.com/moby/moby/pull/35100 rewrite the Dockerfile to use multi-stage builds

To make the Dockerfile more flexible (e.g. to test a different version of `containerd` or the Docker CLI), a suggestion was made to use build-args for various options; https://github.com/moby/moby/pull/35100#discussion_r170151654

labeling as "beginner", but some knowledge about the Dockerfile may come in handy :)

**Comment by adrielldagasuan** [comment]
@thaJeztah Do we have a list of various options that we want to offer aside from those mentioned?

**Comment by jmartin84** [comment]
I'll try my hand at this if no one is currently working on it.

**Comment by eladm26** [comment]
Hi!
Is anyone on it? can I take it?
