### ISSUE TITLE
Unify Dockerfiles for all architectures

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#36411]
https://github.com/moby/moby/pull/35100 rewrote the Dockerfile to use multi-stage builds. We should:

- Try to use a single Dockerfile instead of one per architecture (now that multi-arch is a thing)
- If not possible (yet); sync the other architectures to use multi-stage as well

Labeling this "beginner", but some knowledge about the Dockerfile may be handy :)

**Comment by Sh4d1** [comment]
Hey!

I'd like to give it a try. However I did not found any good post about multi arch Dockerfile. Do you have any good link ? 

Cheers

**Comment by thaJeztah** [comment]
Oh! This was actually done already very recently in this PR: https://github.com/moby/moby/pull/36546

So, looks like we can close this :blush:
