### ISSUE TITLE
docker start hangs

### ISSUE THREAD

**Issue by gavrmike** [moby/moby#36410]
Hello! 

I have a strange bug. Sometimes `docker` does not allow me to start any container. I type `docker run --rm -it ubuntu bash` and this command hangs forever. It may be any other image or command, but it hangs forever. `docker ps` shows that container in status created. `ps auxf` lookes like

```
root     43278  0.0  0.0   7260  3784 ?        Sl   14:25   0:00  |   \_ docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d5fa4650aee9ccf24f886ba8efe1c4ccdcee0d6bfbdaf68e88343fc7fdc30ae0 -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/bin/docker-containerd -runtime-root /var/run/docker/runtime-runc -systemd-cgroup
root     43287  0.0  0.0 675784 14504 ?        Sl   14:25   0:00  |       \_ docker-runc --root /var/run/docker/runtime-runc/moby --log /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d5fa4650aee9ccf24f886ba8efe1c4ccdcee0d6bfbdaf68e88343fc7fdc30ae0/log.json --log-format json --systemd-cgroup create --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d5fa4650aee9ccf24f886ba8efe1c4ccdcee0d6bfbdaf68e88343fc7fdc30ae0 --pid-file /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d5fa4650aee9ccf24f886ba8efe1c4ccdcee0d6bfbdaf68e88343fc7fdc30ae0/init.pid d5fa4650aee9ccf24f886ba8efe1c4ccdcee0d6bfbdaf68e88343fc7fdc30ae0
```

it happens after i start 15 containers and after while (it may be 5 minutes or hour or day) docker start hangs. I think the problem is in `docker-runc`, but it is only hypothesis. I dont know how to diagnosis details, why it happens and what to do with it. I can cure `docker` only by restart server (`service docker restart` also hangs, but if i kill all hangs containers `pkill -9 docker-containerd-shim`, service  docker restart works). Other containers(not new), which is still running, could be used for exec command.

`docker -v `: `Docker version 17.12.0-ce, build c97c6d6`

`docker-runc -v`: `runc version 1.0.0-rc4+dev commit: b2567b37d7b75eb4cf325b77297b140ea686ce8f spec: 1.0.0`

`lsb-release -a`:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

`uname -a`:`Linux cs30192 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`uname -r`: `4.4.0-62-generic`

I have installed docker by command  `apt-get install docker-ce` few days ago.

I will be very grateful for any help!

**Comment by thaJeztah** [comment]
This could be related to an issue in runc (see https://github.com/moby/moby/pull/36097), which was affected by recent distro patches for Meltdown and Spectre.

**Comment by gavrmike** [comment]
Does i correctly understand you, that if it relates to that issue and i downgrade docker to previous version, my hangs will disappear?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
