### ISSUE TITLE
`docker` not completely removed

### ISSUE THREAD

**Issue by rayriffy** [moby/moby#36423]
**Description**

I trying to installing `docker-ce` on CentOS 7 by following [docs](https://docs.docker.com/install/linux/docker-ce/centos/#uninstall-old-versions) and there's two problems (?)

- After `sudo yum remove docker docker-common docker-selinux docker-engine`, yum remove `docker-1.11.2` but when I execute `docker --version`. I got response that docker is on version 1.13.1 and I can still use **all** docker command as normal
- Trying to ignore this and replacing with `docker-ce` by installing from rpm packages. I cannot start `docker.service` because `level=error msg="containerd did not exit successfully" error="exit status 1" module=libcontainerd`

**Steps to reproduce the issue:**
1. `yum install docker`
2. `sudo yum remove docker docker-common docker-selinux docker-engine`
3. `rm -rf /var/lib/docker`
4. `rm -rf /etc/docker`
5. `docker --version`

**Describe the results you received:**
`
[root@caffeDNN ~]# docker --version
Docker version 1.13.1, build 092cba3

`

**Describe the results you expected:**
`
[root@caffeDNN ~]# docker --version
-bash: docker: command not found
`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@caffeDNN ~]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

**Disclaimer**: because all docker command can still using but `docker.service` is gone. So, I manually run `dockerd` to get all results

```
[root@caffeDNN ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.639 GiB
Name: caffeDNN.cs.mwit.ac.th
ID: FLZT:NF5Y:HRQL:3GL4:SX2X:AGGQ:ILKC:R4NZ:5D7X:WAPH:FAAK:BZUV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: rayriffy
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on VMware ESXi 5.5

**Comment by thaJeztah** [comment]
Can you try if uninstalling `docker-latest`works?

**Comment by rayriffy** [comment]
`No Match for argument: docker-latest`
I think it's time to do a fresh install for my OS

**Comment by thaJeztah** [comment]
Perhaps there's some other package (CentOS has quite a few variations of them). I just opened a PR for the documentation, as I noticed the `docker-latest` package was not in the installation instructions. https://github.com/docker/docker.github.io/pull/6092

Given that this is either an issue in the documentation, or packaging, I'll close the issue here, but feel free to continue the conversation (just closing because non of those are maintained in this repository :smile:)
