### ISSUE TITLE
Docker hangs to commands, can run only docker version

### ISSUE THREAD

**Issue by usdin** [moby/moby#36432]
**Description**
We are using docker in Jenkins CICD pipeline. Docker daemon stops responding after sometime, like in 1-2 hours. After restarting it starts to respond but after running and removing few containers it hangs again. 

**Steps to reproduce the issue:**
1. Start docker. 
2. Create and delete some containers.

**Describe the results you received:**
Docker daemon stopped responding.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
`docker info` doesn't respond.

**Additional environment details**
Centos 7, 3.10.0-514.2.2.el7.x86_64

**Go-Stack trace**
https://gist.github.com/usdin/4005aad17818578a56370c13e238e9b1

**Stack trace**
``` 
#0  0x0000000000463c23 in runtime.futex ()
#1  0x000000000042d102 in runtime.futexsleep ()
#2  0x0000000000cb7890 in __bss_start ()
#3  0x0000000000000000 in ?? () 
```

**Comment by thaJeztah** [comment]
Docker 17.05 reached EOL in June of last year, and is no longer maintained; closing this issue because of that, but feel free to open a new issue if you're still seeing this on a current release
