### ISSUE TITLE
Docker 18.03 Linux based images built using LCOW can't be deployed to registries

### ISSUE THREAD

**Issue by artiomchi** [moby/moby#36458]
**Description**
Bringing this from docker/for-win#1769, was told by @carlfischer1 that it should be reported here intead.. Hey! 😄 

So I've narrowed this down to as small an example as I could. I created a small hello world repo here: https://github.com/artiomchi/HelloWorld

When building the app using a linux image, while running 18.03 in Windows Container mode, the image builds successfully and can be started locally. But it fails when trying to deploy it to a remote registry.

The top layer will fail to push immediately, and will enter a "Retrying" loop with an ever increasing delay. It will finally give up with an error

**Steps to reproduce the issue:**

I have a simple repository that I used to reproduce it on several machines.
```powershell
git clone https://github.com/artiomchi/HelloWorld.git
cd HelloWorld/HelloWorld
docker build --rm -f Dockerfile-lin-alpine -t helloworld:alpine . --no-cache
docker tag helloworld:alpine artiomchi/helloworld:alpine
docker push artiomchi/helloworld:alpine
```

**Describe the results you received:**
The top layer retries multiple times, until eventually gives up with the following:
```powershell
PS D:\Development\HelloWorld\HelloWorld> docker push artiomchi/helloworld:alpine
The push refers to repository [docker.io/artiomchi/helloworld]
d140feb78cc6: Pushing [==================================================>]  262.7kB/262.7kB
154dc7e00f30: Layer already exists
c5de6b3aa838: Layer already exists
9dfa40a0da3b: Layer already exists
open \tmp\8797231b7737236ea8608ab3f7e63846a37cbfea164db833fbbbce80f392fceb-mount\app\HelloWorld.deps.json: The system cannot find the path specified.
```

**Describe the results you expected:**
`docker push ` should successfully push the image to the docker registry

**Additional information you deem important (e.g. issue happens only occasionally):**
This only happens when running linux builds in Windows Container mode. When I switch docker to run in Linux Container mode (uses the Hyper-V VM), the build and publish succeed.

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 98
Server Version: 18.03.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 15.93GiB
Name: FlexLabs-Rog
ID: AOEB:4SFW:5ZHH:SEF6:BLKG:UBKZ:4ADD:RAQR:SF6T:E752:64KZ:ZVWV
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2018-03-01T19:34:01.1776121Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Windows 10 with the 1709 Fall creator's update

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep @salah-khan

**Comment by jhowardmsft** [comment]
Yeah, this doesn't surprise me. I'll add it to my list of LCOW work still outstanding.

**Comment by stalb** [comment]
Some bug as in docker/for-win#1370

Can be reproduced with just the following dockerfile:
> FROM busybox
> RUN echo test >  test.txt 

No problem to build or use the image, but pushing it to a repository fails

Bulding is ok:

> docker build --platform linux  --pull -t stalb/essai  .
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM busybox
> latest: Pulling from library/busybox
> d070b8ef96fc: Pull complete
> Digest: sha256:2107a35b58593c58ec5f4e8f2c4a70d195321078aebfadfbfb223a2ff4a4ed21
> Status: Downloaded newer image for busybox:latest
>  ---> f6e427c148a7
> Step 2/2 : RUN echo test >  test.txt
>  ---> Running in d4fe92922db3
> Removing intermediate container d4fe92922db3
>  ---> 84384b7d92d4
> Successfully built 84384b7d92d4
> Successfully tagged stalb/essai:latest

But pushing the image fails (1st layer is ok, because its 'already on the dockerhub repository, but the 2nd layer with text.txt file fails):



> docker push  stalb/essai
> The push refers to repository [docker.io/stalb/essai]
> 939a6c7b33cb: Pushing [==================================================>]  262.7kB/262.7kB
> c5183829c43c: Layer already exists
> open \tmp\6d658de181bfcead8e03d0b29ab695bf9418361101aa91626ec0699b89956585-mount\test.txt: Le chemin d’accès spécifié est introuvable.

**Comment by jonstelly** [comment]
I doubt this adds much more information, but just in case:

```
docker pull --platform=linux alpine
docker tag alpine myregistry/alpine
docker push myregistry/alpine
```

Is enough to repro for me:

```
Z:\> docker push myregistry/alpine
The push refers to repository [myregistry/alpine]
cd7100a72410: Pushing [==================================================>]  6.554MB/6.554MB
open \tmp\3e0265f33c1ac0720a40badaa17a839e6385270280845fe054f9031341d239a0-mount\bin\busybox: The system cannot find the path specified.
```

**Comment by stalb** [comment]
I don't have this problem anymore with docker version 18.05.0-ce-win67 (18263)

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by thaJeztah** [comment]
could others confirm this is resolved in 18.05?

**Comment by yusuf-gunaydin** [comment]
I can confirm that it works with the latest codes.

**Comment by ormico** [comment]
This is a issue for me on Windows Server 2016 1709. I don't believe Docker EE v 18.05 is available on Windows Server yet.

**Comment by thaJeztah** [comment]
Only Docker EE is supported on Windows server, but LCOW is an experimental feature (and still feature incomplete), and experimental features are not supported on EE

**Comment by ormico** [comment]
I'm running 17.10.0-ee preview and it does build the linux containers. just won't push them. was my understanding this was using LCOW since I don't see a Hyper-V VM. 
Thanks for the info.

**Comment by jhowardmsft** [comment]
> anything left to be done, or good to close? Do you know which PR fixed this?

@thaJeztah I suspect https://github.com/moby/moby/pull/36599#issuecomment-379049268

**Comment by thaJeztah** [comment]
> I'm running 17.10.0-ee preview and it does build the linux containers. just won't push them. was my understanding this was using LCOW since I don't see a Hyper-V VM.
Thanks for the info.

Yes 17.10 is an older release than 18.05, so won't have the patch. Given that 17.10 was a one-off preview, and LCOW is still experimental, that patch will unlikely be back ported to that version

> @thaJeztah I suspect #36599 (comment)

Ah, yes, I recall the discussion on that one that it was also related to `docker push`; let me close this issue as this looks to be fixed in the current releases.

**Comment by solvingj** [comment]
FYI, `docker push` of Linux images on Windows still fails with the versions below.  Both pushed all their small layers extremely slowly, but successfully, and then ultimately failed on pushing the biggest layers (200+mb) after several retries. 

centos image fails with this error: 
`svm.runProcess: command cat /tmp/d2/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/setuptools/command/launcher manifest.xml failed with exit code 1`

ubuntu image fails with this error: 


Typically 

```
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
```

```
Client: Docker Engine - Enterprise
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        1578dcadd2
 Built:             05/04/2019 02:34:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       1578dcadd2
  Built:            05/04/2019 02:32:24
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by starcraft66** [comment]
I'm still experiencing this issue on Windows 10 with Docker Desktop 2.1.0.0 (Docker Engine 19.03.1) with experimental features and LCOW. Windows images push without a hitch but Linux images push very slowly and large layers just outright fail in the middle of the transfer.

**Comment by solvingj** [comment]
i was able to push successfully now with: 
`Docker version 19.03.0-rc2, build f97efcc`

**Comment by darrens280** [comment]
Still an issue:
- Windows Server 2022 (21H2) running Linux containers...
- Docker 17.10.0-ee-preview-3
- $env:LCOW_SUPPORTED=1

Linux containers unable to push to private Azure Container Registry, with `System cannot find the file specified` (eg. `hello-world:linux`)

- Can successfully PULL Linux image from public Docker Registry to local Azure VM.
- Can successfully PULL Linux image from Azure Private Registry to local Azure VM.
- Can successfully IMPORT Linux image from public Docker Registry into Azure Container Registry
- Unable to PUSH Linux image from local Azure VM to private Azure Container Registry.

If performing upgrade of Docker using: `Install-Package -Name Docker -ProviderName DockerMsftProvider -Force -Verbose`, and restarting the Docker service, this effectively switches the local Azure VM into Windows Container mode, and can now successfully PUSH & PULL from Azure Container Registry (but only Windows container images)
