### ISSUE TITLE
LCOW: docker run --user seems to be ignored

### ISSUE THREAD

**Issue by rn** [moby/moby#36469]
When running
```
docker run --platform linux --user postgres --rm alpine:3.7 id
```
on LCOW I get:
```
uid=0(root) gid=0(root)
```
while on other systems I get:
```
uid=70(postgres) gid=70(postgres)
```
Note, the user `postgres` does exist in `alpine:3.7`

This is with todays master build and a LinuxKit based LCOW (though that shouldn't matter)
```
PS> docker version
Client:
 Version:       master-dockerproject-2018-03-01
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c26f37c0
 Built: Thu Mar  1 23:50:56 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      master-dockerproject-2018-03-01
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   7459e4c
  Built:        Thu Mar  1 23:58:02 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by vdemeester** [comment]
cc @jhowardmsft

**Comment by jhowardmsft** [comment]
Yes, known. Most of the "advanced" (basically pretty much everything) flags are not hooked up in LCOW yet.

**Comment by jhowardmsft** [comment]
`--cap-add` was added in https://github.com/moby/moby/pull/37294.

**Comment by tbertenshaw** [comment]
is this also true that --platform is ignored?
if i run 
` docker run -it --platform linux hello-world`  
on Win 2019 LCOW (experimental flag set) I get the same result as 
` docker run -it --platform smurf hello-world`

which is  output containing
`The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (windows-amd64, nanoserver-1809)`

**Comment by jhowardmsft** [comment]
@tbertenshaw - Please open a new issue rather than confusing an existing one with completely different subject matter. However, I tried today with `--platform smurf` using moby master (can download binaries from master.dockerproject.org, although I built locally) and it failed as expected. As I say, please open a new issue if this repros on master for you, and ensure you include the full repro steps along with output of `docker info` and `docker version` and any other relevant info.

**Comment by maxwellb** [comment]
For the time being, when building I wound up adding `sudo -u user` in front of my RUN commands

**Comment by Ivers07** [comment]
I'm also having this issue when trying to run a kibana image on a Windows OS host with LCOW.

```PS
PS C:\Windows\system32> docker run -p 5601:5601 docker.elastic.co/kibana/kibana:7.3.0
Kibana should not be run as root.  Use --allow-root to continue.
```
for security reasons Kibana stops allowing running a root by default. LCOW ignore any values i specify using -u e.g.
``` PS
PS C:\Windows\system32> docker run -u kibana -p 5601:5601 docker.elastic.co/kibana/kibana:7.3.0 whoami
root
```
As it's a 3rd party image I'm not sure how i can specifiy the ```sudo -u``` before kibana starts. @maxwellb can you give any more detail about how I could apply that?

For now I've had to use the apps ability to override but this won't be suitable for Production.

**Comment by WiMills** [comment]
Having the same issue, neither USER in the Dockerfile or --user works. Is there any timeline of when this will be implemented, if at all?
