### ISSUE TITLE
get a wrong output when attach a container

### ISSUE THREAD

**Issue by frankLife** [moby/moby#36477]
**Description**
`docker exec -it docker_container_id /bin/sh` to attach a container displays wrong stdout when terminal window has a small height on mac
Iterm2:
![image](https://user-images.githubusercontent.com/5081884/36931190-c7bcbfd6-1eeb-11e8-9428-3f75376f1013.png)

mac terminal: 

![image](https://user-images.githubusercontent.com/5081884/36931239-de9ca49a-1eec-11e8-87a2-606d672dea86.png)

**Steps to reproduce the issue:**
1. run `docker exec -it docker_container_id /bin/sh` in a small height terminal window
2. run vim a file which the lines of content beyond the height(row)

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/5081884/36931190-c7bcbfd6-1eeb-11e8-9428-3f75376f1013.png)
 a vim wrong output that can't be operated

**Describe the results you expected:**
![image](https://user-images.githubusercontent.com/5081884/36931229-8d38e0aa-1eec-11e8-9c1e-b909b2508487.png)

a right vim output

**Additional information you deem important (e.g. issue happens only occasionally):**
Sometimes it will works correctly.

**Output of `docker version`:**

```
17.12.0-ce
```

**Output of `docker info`:**

```
Containers: 27
 Running: 2
 Paused: 0
 Stopped: 25
Images: 33
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: WGPS:RS5V:453Q:24YG:4QXJ:OBEG:3O5X:HXGS:TYYK:UZOX:FKVY:XJEQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 44
 Goroutines: 59
 System Time: 2018-03-03T06:07:08.758847562Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://c1jslt50.mirror.aliyuncs.com/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I suspect this is a duplicate of https://github.com/moby/moby/issues/35407 - if you think it is, could you close this issue, so that the discussion doesn't diverge?

(you can try if the output works correctly after resizing the Window; if it does, then it's definitely the same issue :smile:)

**Comment by frankLife** [comment]
Yes, you are right. when I resize the terminal window, the output display looks right.I will close this issue and subscribe the #35407. 

Thanks 😃

**Comment by thaJeztah** [comment]
Thanks for confirming!
