### ISSUE TITLE
docker dind image fails to start occasionally. (about 0.1% failure rate)

### ISSUE THREAD

**Issue by mkleint** [moby/moby#36485]
**Description**

We started getting random, rare failures on docker:17-dind, docker:stable-dind container startups within our kubernetes CI build pipeline. The first occurence of the problem we have logged is January 19th. Since then we've got about 100 such failures,  25 in the last week. To get that into perspective, we likely ran 40k builds with dind images. Not sure if all 40k were run with the above mentioned version, but all the failures we know of ran with those versions. 

Our current environment is kubernetes cluster with CoreOS 1576.5.0, Kernel 4.14.11 , Docker 12.06 on the individual nodes.

I'm not entirely expecting you to find the bug from my description, but I would love some advice on how to get more information out of the docker daemon to narrow down the culprit.

**Steps to reproduce the issue:**

I don't really have steps to reproduce, what we have is kube pod definition that has 2 containers, one where the build runs and one for the dind container, the dind one is run with privileged mode on and with -storage-driver overlay2 parameter.

We send the container logs to splunk so I do have stats on the various messages that the docker daemon prints out.

This message shows up 40k times in the last week, that's likely the total number of builds with dind unless some very old versions don't print the message
<img width="1660" alt="screen shot 2018-03-05 at 14 44 00" src="https://user-images.githubusercontent.com/178549/36956724-fd8a42a2-2083-11e8-9029-ddc54586c398.png">

Similarly this message shows up in about the same amount of cases, slightly less.
<img width="1664" alt="screen shot 2018-03-05 at 14 44 21" src="https://user-images.githubusercontent.com/178549/36956723-fd591b78-2083-11e8-92ea-4ad65351f0ab.png">

these 2 message show up when we end up with the error, about 40 times in the last 7 days. So the failure rate is 0.1%

<img width="1668" alt="screen shot 2018-03-05 at 14 45 12" src="https://user-images.githubusercontent.com/178549/36956721-fcf65b96-2083-11e8-9d89-5a914af9fe7d.png">
<img width="1666" alt="screen shot 2018-03-05 at 14 44 32" src="https://user-images.githubusercontent.com/178549/36956722-fd27d91e-2083-11e8-86c2-7c541deb0052.png">

**Describe the results you received:**

when the docker daemon crashes, Kubernetes "AfterStart" hook fails with various messages like:
1. oci runtime error: exec failed: cannot exec a container that has run and stopped
2. error: rpc error: code = Unknown desc = container not running (dind)
3. rpc error: code = 13 desc = invalid header field value \\\"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\\\\\"process_linux.go:258: applying cgroup configuration for process caused \\\\\\\\\\\\\\\"failed to set memory.kmem.limit_in_bytes, because either tasks have already joined this cgroup or it has children

these indicate that the daemon crashed very fast.

**Describe the results you expected:**

docker daemon should always startup, if not fail with descriptive message in the logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

yeah, very rare but with the number of builds we do, it happens multiple times a day.

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

kubernetes cluster with CoreOS 1576.5.0, Kernel 4.14.11 , Docker 12.06 on the individual nodes running in AWS on m4.10xlarge instances.

**Comment by mkleint** [comment]
sample output of the docker daemon when the error happens.

[sample_output.txt](https://github.com/moby/moby/files/1779457/sample_output.txt)

**Comment by mkleint** [comment]
there seems to be a strong correlation between message 
"level=info msg="containerd successfully booted in 30.341532s" module=containerd" where containerd starts longer than 20s and the failure. but some failures don't have the message at all.
what would make the containerd process start that long?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
