### ISSUE TITLE
Overlay network obscurity: Asking for info on how to provide more info

### ISSUE THREAD

**Issue by retardtank** [moby/moby#36488]
We're running a few different swarms on bare-metal hosts and different physical networks.

Occasionally, we run into somewhat obscure conditions on the docker overlay network, often at a deploy when a swarm service container is updated. This usually manifests itself by two containers ips being pingable between each other on the overlay network, but actual traffic between them seems completely stuck/hanging. Nothing out of the ordinary seems to be appearing in kernel or docker logs.

The fix is usually easy, by restarting the affected container. And (though unfortunately from a debugging perspective) does not happen that very often. However, still happening somewhat randomly, over time it's starting to become a growing concern.

Any suggestions on how to further debug this, or what other data/info could be collected to help resolving this?

Bellow docker info is from the host where it last occurred, but we've also had this happening on other versions such as 17.05 (and probably earlier), other host distros such as Debian, and on completely different physical networks.

**Steps to reproduce the issue:**
1. Unfortunately, too random really, but usually when updating the swarm

Below binaries are the official statically linked versions.

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 110
 Running: 18
 Paused: 0
 Stopped: 92
Images: 1974
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: uig6jxtt5zzbphsdxhy71vjbg
 Is Manager: true
 ClusterID: n1i8mqgrfnx59ztdtffugs3wl
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.1.224
 Manager Addresses:
  10.0.1.224:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.104
Operating System: Alpine Linux v3.6
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.21GiB
Name: nxt3
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username:
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
