### ISSUE TITLE
filters api does not support exclude syntax， but api doc imply they are supported

### ISSUE THREAD

**Issue by levin-du** [moby/moby#36495]
**Description**
filters api does not support exclude syntax， but api doc imply they are supported.
source code: https://github.com/moby/moby/blob/master/api/types/filters/parse.go,
and the api doc: https://docs.docker.com/engine/api/v1.34/#operation/NetworkPrune.

**Steps to reproduce the issue:**
EMPTY

**Describe the results you received:**
EMPTY

**Describe the results you expected:**
EMPTY

**Additional information you deem important (e.g. issue happens only occasionally):**
EMPTY

**Output of `docker version`:**
EMPTY

**Output of `docker info`:**
EMPTY

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
The exclude syntax for prune is handled here; https://github.com/moby/moby/blob/6cb75dd5b61f438b026572aca0c191c7d2fb7694/daemon/prune.go#L299-L311

**Comment by thaJeztah** [comment]
Closing this, because this doesn't look to be an issue, but feel free to continue the conversation 👍
