### ISSUE TITLE
starting a container read-only with IPC private mounts /dev/shm read-only

### ISSUE THREAD

**Issue by lysandef** [moby/moby#36503]
**Description**

When starting a container with --read-only and --ipc private, /dev/shm will be mounted read-only and not useable.

A private Shared-Memory read-only does not make any sense. Is is the same as having no Shared-Memory at all.

If I want a private Shared-Memory read-only I would just use --ipc none

**Steps to reproduce the issue:**
1. docker run -ti --rm --ipc private --read-only alpine grep shm /proc/mounts

**Describe the results you received:**

```
$ docker run -ti --rm --ipc private --read-only alpine grep shm /proc/mounts
shm /dev/shm tmpfs ro,nosuid,nodev,noexec,relatime,size=65536k 0 0
```

**Describe the results you expected:**

/dev/shm should be mounted read-write, even when the root-filesystem is mounted read-only.

**Additional information you deem important (e.g. issue happens only occasionally):**

When starting a container with --read-only and --ipc shareable , it works as expected:

```
$ docker run -ti --rm --ipc shareable --read-only alpine grep shm /proc/mounts
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
```

**Output of `docker version`:**

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:21 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:15:56 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.957GiB
Name: debian
ID: MH7G:5ZET:BLMA:BPCQ:N54E:D63Y:EE4X:57KZ:DUPR:U3LL:6NTB:QLYE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: 
HTTPS Proxy: 
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox on Linux

**Comment by thaJeztah** [comment]
ping @kolyshkin @justincormack PTAL

**Comment by kolyshkin** [comment]
The slightly more general question is what to do when --ipc XXX is used with --read-only. These compos should be reviewed and checked. Let's take a look.

1. --read-only --ipc shareable

IMO it should be mounted read-write on the host, read-only inside the container.

2. --read-only --ipc container:NNN

Mounting /dev/shm read-only is fine I guess (the idea is "I want to look what other container is having in there).

3. --read-only --ipc host

Ditto.

4. --read-only --ipc none

Trivial case, no mount -- no questions.

4. --read-only --ipc private

This is the case of this bug.

As it is private it might make sense to have this case as an exception and mount /dev/shm as rw despite the `--read-only` flag given (otherwise empty and read-only private /dev/shm mount does not make any sense).

From the other side, `--read-only` does indeed mean read only; if so, why should we make an exception and allow something writable?

Or should we treat `--ipc private` as a request to have a writable mount? If yes, what about other `--ipc MODE` variants above, should they be writable as well?

It's not easy to decide; need more opinions and reasons.

**Comment by kolyshkin** [comment]
One more factoid: `--tmpfs` mounts are read-write despite the `--read-only` flag given, so maybe `--ipc` should follow.

**Comment by kolyshkin** [comment]
(despite the proposed PR I would still love some thoughts and opinions)

**Comment by lysandef** [comment]
according to the documentation --read-only mounts the root-fs read-only, not everything (like /proc or /sys)

My use-case is the following:
I like to start containers with --read-only to make sure, that no data within the container is changed, except in mounted volumes and tmpfs mounts. This is for security-reasons and to force developers to adapt their applications to not write just anywhere but in specific paths (e.g. /run for non-persistent data and /data for persistent data)

This works very good for normal applications, but for a container with e.g. a postgresql database I need /dev/shm writable but still want the root-fs read-only. For such a container I only need a private shared-memory but it needs to be writeable.

I still think --read-only should only follow the current documentation and only mount the root-fs read-only and leave everything else as is.

**Comment by thaJeztah** [comment]
Related discussions in https://github.com/moby/moby/pull/35344 and https://github.com/moby/moby/issues/35041


Actually, also found an older discussion about  `/dev/shm`  _not_ being read-only;

- https://github.com/moby/moby/issues/28639  "/dev/shm is not mounted ro when --read-only is used" 
- https://github.com/moby/moby/pull/28823 "add a test for ensuring the behavior of read-only /dev/shm"

**Comment by kolyshkin** [comment]
OK as per https://github.com/moby/moby/issues/28639#issuecomment-261880822 `--read-only` should not affect IPC, and it looks like it does (for the `--ipc private` case).

**Comment by kolyshkin** [comment]
Proposed fix is now ready in its full glory, together with the unit test: https://github.com/moby/moby/pull/36526
