### ISSUE TITLE
container connect to other host is not OK

### ISSUE THREAD

**Issue by mushixun** [moby/moby#36525]
I execute telnet command in container to test other host port 8080,but not OK,then I execute same telnet command on the container's host,the test is OK,when I restart the host,all of the test is OK.

docker version:
![image](https://user-images.githubusercontent.com/10143373/37128052-5ba1ef94-22b3-11e8-8403-cded077c0ce3.png)

docker info:
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:1-4194308-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.013 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103.4 GB
 Metadata Space Used: 6.57 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 78.51 GiB
Name: vd30dcos67
ID: MZSJ:CPUI:MXHK:K37K:MCW5:3AKN:VDBL:RPO3:BVIB:TFZO:SKM2:SZ7Q
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8

**Comment by ripcurld** [comment]
docker version `1.12` is no longer supported.
can you upgrade `docker` on your host and try again?

**Comment by mushixun** [comment]
Thanks for you answer,the save problam is happen on docker 17.12，the diffrent with docker 1.12.5 is docker 17.12 don't need to restart host,only to restart docker daemon is all OK。

**Comment by ripcurld** [comment]
I am afraid we need more details:
 * `docker inspect` of the container
 * `docker run` command
 * the telnet command
 * anything that helps us to reproduce this error
Thanks.

**Comment by thaJeztah** [comment]
closing, as this one went stale
