### ISSUE TITLE
[Feature Request] Make LogFile permissions configurable

### ISSUE THREAD

**Issue by yolken-stripe** [moby/moby#36521]
#### Description
We're writing a custom log driver which uses the `LogFile` struct defined in https://github.com/moby/moby/blob/master/daemon/logger/loggerutils/logfile.go. By default, this creates all log files with the permissions `0640`; unfortunately, this doesn't work with our Splunk setup, so we'd like to make the permissions configurable instead of hard-coded.

I will file an associated pull request soon.

**Comment by thaJeztah** [comment]
Could you provide more information about the Splunk setup? Is there a reason for not using the Splunk logging driver?

IIUC, that part of the code is used for the jsonfile logging-driver; those files are not intended for external consumption, hence the permissions being restricted.

**Comment by kolyshkin** [comment]
Can you please shed some light on what problem are you trying to solve exactly? Like, what permissions are you aiming to have and why?

**Comment by thaJeztah** [comment]
Thanks for the added information; yes, after discussing the PR we gathered you used that code as an import (sorry, initially thought you wanted to change the permissions for the default JSON-file logging driver).

One note to add to the change, is that on Windows, setting those permissions basically would be a no-op, but that's the current situation as well (just now being configurable)

**Comment by yolken-stripe** [comment]
Yup, this is just for our plugin, not for the default json-file driver. Thanks!

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/36523 was merged, so let me close this one
