### ISSUE TITLE
LCOW: create new file using touch in monted volume fails

### ISSUE THREAD

**Issue by stalb** [moby/moby#36531]
**Description:**
Using  `touch` to create a new file in a mounted volume in a docker LCOW container fails with the following error : `touch: setting times of '/volume/xxx.txt': Permission denied`

**Steps to reproduce the issue:**
1. run a lcow debian container with a mounted volume
 >docker run --platform linux -v volume:/volume --rm -ti  debian
2. create a new empty file in the volume using `touch`
>touch /volume/xxx.txt

**Describe the results you received:**
The file is created but the command fails with 
>touch: setting times of '/volume/xxx.txt': Permission denied

**Describe the results you expected:**
File should be created without error

**Additional information you deem important (e.g. issue happens only occasionally):**
I have the problem with debian and ubutu container, but not with busybox or alpine.

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  true
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.891GiB
Name: ASUS_ST
ID: P2M6:HIL5:MKMA:OJRJ:CEU7:OWT6:UXWF:DEVZ:ZYTE:CTDE:CWQV:W4I6
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-03-08T11:16:00.4362345+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by adulescentulus** [comment]
I can reproduce this issue running the very same docker version.
**But** running alpine linux 
> docker run --platform linux -v volume:/volume --rm -ti alpine

it works
> touch /volume/xxx.txt

But there is another weird thing and I think it also relates to this lcow mounting issue:
Regardless which image I use, I cannot acquire a file lock on mounted volumes
> flock -n /volume/xxx.txt echo success

Resulting in
> flock: Not supported

This makes lcow useless and I need to switch back to hyper-v

**Comment by adulescentulus** [comment]
Does anyone feel responsible for this? Will there be any fixes? In [this](https://github.com/docker/for-win/issues/1386) issue I learned that it is a problem with windows' 9p file system server, which I didn't know to exist

**Comment by KevM** [comment]
I was hoping **Windows 10 1803** would fix this but confirmed that it does not.

**Comment by thaJeztah** [comment]
ping @gupta-ak @jhowardmsft

**Comment by stalb** [comment]
I don't have this problem anymore with docker version 18.05.0-ce-win67 (18263)
So I think we can close this issue...

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by thaJeztah** [comment]
Thanks! Okay, let's close
