### ISSUE TITLE
docker stack should inform the user that `env_file` is ignored

### ISSUE THREAD

**Issue by SvenDowideit** [moby/moby#36542]
considering #29133 , it would be good if `docker stack deploy -c compose.yml something` identified _all_ keys that it isn't using.

That way, users that read the docs, or inherit an existing docker-compose system are not impacted by silent hidden failures.

aka - UX !

@dnephin @thaJeztah @londoncalling

**Comment by thaJeztah** [comment]
Oh, hai! :wave:

Could you reopen this in https://github.com/docker/cli ? That’s where the stack deploy code lives

**Comment by dnephin** [comment]
`env_file` is not ignored. `stack deploy` does warn on all keys that aren't used. That issue is about loading a `.env` file from the working directory to populate the environment used to interpolate variables in the compose file.

**Comment by londoncalling** [comment]
Well, now I'm completely immersed in the story of #29133  :-)

**Comment by bsousaa** [comment]
Closing in favour of #29133.
