### ISSUE TITLE
Flaky test TestServiceWithPredefinedNetwork

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#36547]
This test was added recently in https://github.com/moby/moby/pull/36316, but is failing on a lot of PR's with:

```
13:46:02 --- FAIL: TestServiceWithPredefinedNetwork (12.36s)
13:46:02 	daemon.go:283: [d47ab7ceb5568] waiting for daemon to start
13:46:02 	daemon.go:315: [d47ab7ceb5568] daemon started
13:46:02 	service_test.go:52: timeout hit after 10s: task count at 1 waiting for 0
13:46:02 	daemon.go:273: [d47ab7ceb5568] exiting daemon
13:46:02 FAIL
```

Failure is in the teardown of the test; https://github.com/moby/moby/blob/0b0af855ae28698f8e3dc97cdc2a46e714ce6b6a/integration/network/service_test.go#L52

/cc @selansen

**Comment by kolyshkin** [comment]
I just found this PR: https://github.com/moby/moby/pull/36551, looks like it addresses the issue
