### ISSUE TITLE
No way to specify arch in docker {run,pull,build}

### ISSUE THREAD

**Issue by kolyshkin** [moby/moby#36552]
**Description**

Before the addition of manifests and multiarch docker hub images, a trivial way to specify an architecture was something like `ppc64le/ubuntu:xenial`. Now the architecture is chosen automatically (based on golang `runtime.GOARCH`), but there absolutely is no way to change or specify it.

Linux kernel binfmt_misc feature, together with e.g. QEMU (or some other emulator), provide a way to run a container image using a different architecture. For example, on any recent Debian or Ubuntu x86_64, as root:

```
mkdir xxx && cd xxx
apt install qemu-user-static
# this step might be optional
test -f /proc/sys/fs/binfmt_misc/aarch64 || echo ':aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-aarch64-static:' > /proc/sys/fs/binfmt_misc/register
cp /usr/bin/qemu-aarch64-static .
cat << EOF > Dockerfile
FROM arm64v8/ubuntu:bionic
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
EOF
docker build -t ubuntu-qemu .
```

Once the image is built, you can test it:
```
uname -a
Linux kd 4.14.23+ #46 SMP Fri Mar 2 10:31:35 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

docker run ubuntu-qemu uname -a
Linux b0a309929288 4.14.23+ #46 SMP Fri Mar 2 10:31:35 PST 2018 aarch64 aarch64 aarch64 GNU/Linux
```

Now, if I am to use multiarch support, there is no way to tell docker the image architecture. i.e. both docker build with a Dockerfile containing `FROM ubuntu` and `docker pull ubuntu` will always pull image of the architecture under which the docker binary was built (i.e. `runtime.GOARCH`).

The other problem is resulting image architecture (also assumed to be `runtime.GOARCH`) is wrong:
```
docker image inspect ubuntu-qemu | grep Arch
        "Architecture": "amd64",
```

**Comment by tkurki** [comment]
It looks like the image architecture is specified as the underlying architecture of the docker host running the build:
```
cat << EOF > Dockerfile
FROM arm32v6/alpine:3.7
CMD ["sh", "-c" , "uname -a"]
EOF
docker build -t test .
docker run -it --rm test &&\
docker inspect test:latest | grep Architecture
```
On OS X:
```
Linux 8d04d4e3cf2b 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 armv7l Linux
        "Architecture": "amd64",
```
An armv7 (stretch on RPi3):
```
Linux 745a2449b716 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l Linux
        "Architecture": "arm",
```

**Comment by kolyshkin** [comment]
> is specified as the underlying architecture of the docker host running the build

Nope; It's actually slightly worse: an architecture used to build the dockerd is used, hardcoded (to runtime.GOARCH) during build time.

```
$ setarch i686
$ uname -a
Linux kd 4.14.23+ #46 SMP Fri Mar 2 10:31:35 PST 2018 i686 i686 i686 GNU/Linux
$ cat << EOF > Dockerfile
FROM arm32v6/alpine:3.7
CMD ["sh", "-c" , "uname -a"]
EOF
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM arm32v6/alpine:3.7
 ---> fdf451efac74
Step 2/2 : CMD ["sh", "-c" , "uname -a"]
 ---> Using cache
 ---> 0fb368c56941
Successfully built 0fb368c56941
Successfully tagged test:latest
$ docker inspect test:latest | grep Architecture
        "Architecture": "amd64",
$ 
```

I am not quite sure how to properly solve it though. For one thing, `docker build` can call `uname(2)` from inside the container context, and then normalize the output to match the golang's runtime.GOARCH values (e.g. convert `x86_64` to `amd64', `armv7` to `arm`, `aarch64` to `arm64` etc.), but it might not work in all the cases...

For `docker pull/run` as well as `build`, I'd like to have a flag to explicitly specify the architecture.

**Comment by thaJeztah** [comment]
Possibly this could use the `--platform` option (e.g. `--platform=windows/arm` `--platform=linux/ppc64le` ?

**Comment by arm64b** [comment]
@kolyshkin  if you pull the `arm32v6/alpine:3.7` in the Dockerfile and build it on another arch like `amd64`, you can't run the built docker image on `amd64`: `standard_init_linux.go:195: exec user process caused "exec format error"`, but the `docker inspect` does show the image is `linux/amd64`, what's your expectation in this case? you just want to get `linux/arm` from the image and not run it, right?

**Comment by kolyshkin** [comment]
> what's your expectation in this case? you just want to get linux/arm from the image and not run it, right?

This would probably be saner, yes.

**Comment by lenaschimmel** [comment]
I just want to mention that the same problem also affects cross-building using [the approach from resin.io](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/) or the [refined approach from monsonnl](https://github.com/monsonnl/qemu-wrap-build-files).

To make things clear for myself and maybe also for others, I don't think that PR  #36816 really solves this. That PR seems to use the explicitly specified arch info form the base image, but If I want to start with a base image that already uses manifest lists, there is still no way to specify which arch I want to use.

By looking at the mentioned PRs, I found the experimental `--platform` switch, which should solve this. As far as I understand, the current implementation [rejects every non-empty arch string](https://github.com/moby/moby/pull/36881/commits/a7491cf9a269e87650ea81dd763498ab75d34aab#diff-830015187dfbdcc9f33847dcbdf05deeL20) until #36881 is merged, right?

**Comment by arm64b** [comment]
@lenaschimmel 

> To make things clear for myself and maybe also for others, I don't think that PR #36816 really solves this. 

Correct!

> As far as I understand, the current implementation rejects every non-empty arch string until #36881 is merged, right?

Current implementation doesn't support `arch` which means the `--platform` essentially is an "OS" string, since it's based on a temp function, so only limited `OSes` can be specified to march the run time OS.

Though PR #36881 has a saner way to validate this, but there's still some gaps to support cross-building in server side. So as summary: the current implementation will reject every non-empty arch string until #36881 merged, but the `--platform` doesn't have real effect in the final generated image.

**Comment by rmoriz** [comment]
I'm also affected by this because of cross-compilation of images using the QEMU approach. 

I've a dirty workaround in place that exports the built image to disk, changes the architecture values in its json files, then importing everything back into docker before pushing it to the registry

https://github.com/rmoriz/multiarch-test/blob/master/hooks/build#L34

(that repo also shows how to to let docker hub autobuild do everything for you)

**Comment by julialongtin** [comment]
I'm also running into this. using qemu to compile docker images for my raspberry PIs.

**Comment by i3laze** [comment]
I'm running aarch64 which int fact arm64 and suffer from aarch64 not listed in manifests.

**Comment by wohali** [comment]
After following a chain of PRs from here (#36681 -> #37346 -> #37350 -> https://github.com/docker/cli/pull/2003/files#diff-4fc21624aa5dadd153e2780910da7c7dR594) I see this is now mostly solved, but it's really unclear how to use it to build cross-architecture images.

To use the new `docker build --platform=<arch>` you need to [enable experimental features in the daemon](https://github.com/moby/moby/issues/30585#issuecomment-280822231). Unless I'm doing something wrong, though, this seems to amount to just an environment variable that gets set (`BUILDPLATFORM` vs. `TARGETPLATFORM`). I guess if you just want to pass arguments to GNU automake's configure such as `--build` and `--host`, then copy built binaries out of the container, it's useful.

Specifying a platform inside of a Dockerfile in the same way, i.e. `FROM --platform=linux/aarch64 debian:stretch` seems to do the same thing, and doesn't force running an `aarch64` version of `debian:stretch`. Boo.

**BUT!** With Docker 19.03, https://docs.docker.com/buildx/working-with-buildx/ gave me a working solution from a **non-platform-specific** Docker file in minutes:

```
docker buildx create --platform linux/ppc64le --name buildx_ppc64le
docker buildx use happy_clarke   # or whatever it tells you
docker buildx build --platform=linux/ppc64le ...
```

The constructed image is exactly what I wanted - a `ppc64le` container with the correct binaries. *Neat!* It even seems like you can specify multiple architectures and it'll build the manifest correctly for you, though I've not tried this yet.

Hope this helps someone else out there.

**Comment by guysoft** [comment]
> To use the new `--platform=<arch>` flag you need to [enable experimental features in the daemon](https://github.com/moby/moby/issues/30585#issuecomment-280822231).

This works locally, but on docker hub you get:
Unexpected error
Encountered error: 400 Client Error: Bad Request ("Dockerfile parse error line 15: Unknown flag: platform")

Which means you can't use this where it counts - dockerhub

**Comment by shaoxp** [comment]
there is a similar issue when building Windows based docker image. i am not sure it is the same with issue here. I want to share here to get some possible insight or solution. if it is not suitable here, please let me know or just remove this comment.

my Windows K8S node is using Windows Server 2019. which means that i could using base image of 1809 as following.
`FROM mcr.microsoft.com/windows/servercore:1809-amd64`

when build the docker image on my local Windows10 system, it will failed with error following.

> a Windows version 10.0.17763-based image is incompatible with a 10.0.15063 host

acutally, the docker image is aiming to run on correct Windows server 2019 instead of my local Win10. i am trying to figure out how to let docker ignore the restriction to let me build out the image.

Thanks.

**Comment by thaJeztah** [comment]
@shaoxp I think that issue is related, but slightly different. In your case, is the daemon running with Hyper-V isolation, or with process isolation? Might be worth opening a separate ticket for that with details; with Hyper-V isolation, having a non-matching kernel version should be supported, but with process-isolation, there is no guarantee for it to work.

**Comment by shaoxp** [comment]
Thanks, @thaJeztah. A sperate issue is opened. 

I tried with hyperv isolation option, it fails with the same error. if there is any info, please discuss in the new issue.

**Comment by pojntfx** [comment]
I have found that with a very simple Dockerfile like this:

```dockerfile
FROM debian

RUN uname -a
```

It is possible to force the architecture when building it, but only if the `--pull` flag is specified (otherwise the cached image for the "wrong" architecture is being used):

```bash
pojntfx@workstation-20c819232ee4402f89602c7d457f6861:/tmp/test % uname -a
Linux workstation-20c819232ee4402f89602c7d457f6861 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pojntfx@workstation-20c819232ee4402f89602c7d457f6861:/tmp/test % docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian
 ---> 67e34c1c9477
Step 2/2 : RUN uname -a
 ---> Running in 4757f4e47d68
Linux 4757f4e47d68 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 x86_64 GNU/Linux
Removing intermediate container 4757f4e47d68
 ---> 51dcb59be3df
Successfully built 51dcb59be3df
pojntfx@workstation-20c819232ee4402f89602c7d457f6861:/tmp/test % docker build --platform arm .       
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian
 ---> 67e34c1c9477
Step 2/2 : RUN uname -a
 ---> Using cache
 ---> 51dcb59be3df
Successfully built 51dcb59be3df
pojntfx@workstation-20c819232ee4402f89602c7d457f6861:/tmp/test % docker build --platform arm --pull .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian
latest: Pulling from library/debian
Digest: sha256:79f0b1682af1a6a29ff63182c8103027f4de98b22d8fb50040e9c4bb13e3de78
Status: Downloaded newer image for debian:latest
 ---> b6efee0ab4f5
Step 2/2 : RUN uname -a
 ---> Running in ea5316e6d7cb
Linux ea5316e6d7cb 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 armv7l GNU/Linux
Removing intermediate container ea5316e6d7cb
 ---> 1f11de1719f4
Successfully built 1f11de1719f4
```

**Comment by julialongtin** [comment]
Running into this a year later, yet again. can this be fixed soon, please?

**Comment by cpuguy83** [comment]
I'm not sure I'm following this issue.
run/build/pull all support platform (in experimental mode anyway) where you can specify arch.

Additionally, based on my experience and I admit I may be missing something, the `FROM --platform` also works and does not just set some vars as is claimed above.

```terminal
$ docker run --rm --platform=arm64 buildpack-deps dpkg-architecture
DEB_BUILD_ARCH=arm64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=arm64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=aarch64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=aarch64-linux-gnu
DEB_BUILD_MULTIARCH=aarch64-linux-gnu
DEB_HOST_ARCH=arm64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=arm64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=aarch64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=aarch64-linux-gnu
DEB_HOST_MULTIARCH=aarch64-linux-gnu
DEB_TARGET_ARCH=arm64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=arm64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=aarch64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=aarch64-linux-gnu
DEB_TARGET_MULTIARCH=aarch64-linux-gnu
```

**Comment by cpuguy83** [comment]
The biggest issue with pull/run, I think, is that the arch is not checked if the image tag already exists on the system.

**Comment by Lewiscowles1986** [comment]
seems to not be uname aware, which might be a blessing as much as a problem.

Raspberry Pi 4 ships with 32-bit OS. Activating 64-bit mode is 64-bit kernel running 32-bit userland

Docker install after switching to 64-bit mode installs 32-bit docker, which then cannot run 64-bit docker images (easily). But... also Golang executables won't run and I am unsure why. `uname -m` reports `aarch64` so there must be missing core libraries. Ugh

**Comment by guysoft** [comment]
@Lewiscowles1986 That is the same reason I have been hitting this. But any cross-arch building and multiarch build might have this issue in some way.

**Comment by Lewiscowles1986** [comment]
Totally, it's activating enough of the 64-bit userland, and then using an override for docker as seems to be documented here. I could use one of the dedicated docker images, but those are not made or supported by upstream so I try to avoid random vendors.

**Comment by cpuguy83** [comment]
We recently merged changes that adds a new parameter to the container create API for the target platform.

This resolves the issue where you may already have a tagged image but it's for another arch.

It's still not a perfect solution, though, since docker's reference store (how it stores image tags), is not multi arch aware, so a tag can only reference a single image.
With the above patch, the tag is reference is updated since the tag can only reference one image (and therefore arch).

**Comment by wohali** [comment]
@cpuguy83 That sounds like a step in the right direction, thanks! Can you link to the parameter / documentation?

**Comment by thaJeztah** [comment]
> Can you link to the parameter / documentation?

cli changes were merged in https://github.com/docker/cli/pull/2551, and corresponding API changes in https://github.com/moby/moby/pull/40725

**Comment by thaJeztah** [comment]
This is implemented for various commands now (there may still be more, but let's create separate tickets for those if needed)
