### ISSUE TITLE
Feature request: docker stack deploy pass environment variables via cli options 

### ISSUE THREAD

**Issue by dhanvi** [moby/moby#36554]
Few people might have a use case to pass environment variables with a flag like -e.

`docker stack deploy -c file.yml -e name=value stack_name`

Labels: area/cli kind/feature

**Comment by AkihiroSuda** [comment]
CLI is out of the scope of this repo.
Please refer to https://github.com/docker/cli

**Comment by dhanvi** [comment]
This issue was moved to docker/cli#939
