### ISSUE TITLE
Support V2 plugins on Windows

### ISSUE THREAD

**Issue by likevi-MSFT** [moby/moby#36566]
Description:
Currently V2 plugins is not supported on Windows. In order to support V2 plugins on Windows, we need support for named pipes created on host to work in a container. Enabling support for V2 plugins will enable log driver plugins on Windows.

More details are required. @cpuguy83

**Comment by thaJeztah** [comment]
Actually, looks like there's an existing issue already; https://github.com/moby/moby/issues/34410

Let me close this one to keep things in a single place 👍
