### ISSUE TITLE
Make docker daemon not translate error message from registry

### ISSUE THREAD

**Issue by molian6** [moby/moby#36565]
**Description**

Is it possible for docker deamon to not translate error messages returned by registry?
For all pull request 403 error, docker daemon always translate it into error message like following: "pull access denied for somerepo/someproject/someimage, repository does not exist or may require 'docker login'"
We want deamon to not translate the error message our registry service returned, so that we can customize our error message to provide clearer content.

FYI for push request, I believe deamon does not translate any error messages.

**Steps to reproduce the issue:**
1. Client make a pull request 
2. Our registry service returned some error message with error code 403

**Describe the results you received:**
The client got the error "pull access denied for somerepo/someproject/someimage, repository does not exist or may require 'docker login'"

**Describe the results you expected:**
The client got the error message our registry returned

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.91GiB
Name: molian-glinux.kir.corp.google.com
ID: TCMM:JH7Y:22YX:YHRE:KB7P:EHRO:2VIY:YTMO:PJQP:QHEP:6VJH:QGOA
Docker Root Dir: /usr/local/google/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 25
 System Time: 2018-03-12T10:45:11.541509347-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by kevinmdavis** [comment]
Is this a change that would likely be accepted? If so, I can make the pull request.

I believe the error message is being constructed in [distribution/errors.go](https://github.com/moby/moby/blob/b7b6b6929c6436145bd12e6fef7efb7d01fa170b/distribution/errors.go#L71), which also has access to the error returned by the registry.

**Comment by thaJeztah** [comment]
Perhaps it could be changed to;

```go
return errors.Wrap(fmt.Sprintf("pull access denied for %s, repository does not exist or may require 'docker login'", reference.FamiliarName(e.ref)), err)
```

That way both the "friendly" error and the original error are preserved

@kevinmdavis If you're up to it, feel free to open a pull-request with that change. I _would_ still like to get feedback from other maintainers (so no 100% guarantee it get's accepted), but in my experience, having a PR open makes that discussion easier (maintainers can build it, give it a spin, and verify it does the right thing)

**Comment by thaJeztah** [comment]
whoops, my example code was incorrect; updated
