### ISSUE TITLE
Memory leak with authorization plugins

### ISSUE THREAD

**Issue by runcom** [moby/moby#36576]
**Description**

**Steps to reproduce the issue:**
1. enable any authorization plugin
2. docker cp container:/ /local/root
3. watch the OOM (which causes docker to restart)

- craete a vm with 2G RAM and no swap

use this reproducer:

```
#!/bin/bash
set -xeuo pipefail

docker run --detach --name cnt docker.io/openshift/origin:v3.7.1 sleep infinity || true
for i in $(seq 10); do
  docker cp cnt:/ /tmp/oc-usr
done
```

**Describe the results you received:**

OOM panic

```
github.com/docker/docker/pkg/authorization.(*responseModifier).Write(0xc4229c9000, 0xc422248000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
/builddir/build/BUILD/docker-774336db27bb8931c1705e47781b3842d290c968/_build/src/github.com/docker/docker/pkg/authorization/response.go:124 +0x125 fp=0xc4202c73f0 sp=0xc4202c7388
```

**Describe the results you expected:**

no OOM

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
latest
```

**Output of `docker info`:**

```
latest
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

if you disable the authorization plugin, no oom happening

@cpuguy83

**Comment by runcom** [comment]
`responseModifier.Write` is actuall copying the whole response (which could be a huge tar) to the internal `body` before flushing it to the actual response

**Comment by evanphx** [comment]
This is a super real issue. RHEL ships with an authorization plugin by default and any using of `docker cp` causes a huge memory ballooning!

**Comment by runcom** [comment]
> This is a super real issue. RHEL ships with an authorization plugin by default and any using of docker cp causes a huge memory ballooning!

this is already fixed in RHEL/Fedora

**Comment by blalor** [comment]
When was it released in RHEL @runcom ?

**Comment by runcom** [comment]
It's going to be, it's fixed, we need to wait for the release

**Comment by evanphx** [comment]
@runcom is that commit public? I only see https://github.com/projectatomic/docker/commit/aacbc4ba57c17927b4088bfc8e227ef4368f8a84 which is related but not the same.

**Comment by evanphx** [comment]
Ah! I reread responseWriter#Flush and realize now that it calls #FlushAll, which will empty the internal responseWriterr buffer.

Great! Thanks so much! It's strange that I just hit this bug and you just fixed it! I think it's existed for years?

**Comment by runcom** [comment]
> Great! Thanks so much! It's strange that I just hit this bug and you just fixed it! I think it's existed for years?

likely :)

**Comment by petems** [comment]
@runcom Reading through https://access.redhat.com/articles/2317361, my understanding is that this change been backported to `docker-latest`, but not `docker` right?
