### ISSUE TITLE
Bind docker socket using lcow

### ISSUE THREAD

**Issue by jbellmore** [moby/moby#36574]
**Description**

Unable to bind docker socket from host into child container when using docker for windows with LCOW enabled (with --platform=Linux flag set).

I am not sure if this should be expected to work or not but I am trying to bind the docker socket from my host mahine into a newly started container to be able to build and use docker containers from inside of the container. I am aware of the security issues around this, this is being run on single use disposable VM's for a CI build so that should be a non-issue.

I am able to successfully bind the socket, as described in the article below, if I have docker for windows set to use Linux Containers, but if I set it to use Windows containes and pass the platform flag in I get the following:

`Error response from daemon: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock'.`

http://blog.teracy.com/2017/09/11/how-to-use-docker-in-docker-dind-and-docker-outside-of-docker-dood-for-local-ci-testing/

I have also tried to bind to the named pipe but that gave the following error:

`Linux containers on Windows do not support named pipe mounts.`

Is this something that should (or would int he future) work? I'm not sure if there was a change to the socket handling in the switch to LinuxKit and maybe there is just a different path I need to use?

**Steps to reproduce the issue:**
1. Install docker for windows (edge version)
2. Ensure "switch to windows containers" is completed
3. Run `docker run --platform=linux --rm -it -v //var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/bash teracy/ubuntu:16.04-dind-17.06.0-ce`

**Describe the results you received:**
Error response from daemon: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock'.

**Describe the results you expected:**
An interactive bash prompt inside of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
This works successfully if I do the "switch to Linux containers option"

**Output of `docker version`:**

Client:
 Version:       18.03.0-ce-rc1
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:04 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   c160c73
  Built:        Thu Feb 22 02:41:20 2018
  OS/Arch:      windows/amd64
  Experimental: true

**Output of `docker info`:**

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 51
Server Version: 18.03.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.888GiB
Name: DESKTOP-QNLB0HU
ID: I2HY:L6WW:7SXV:6WBZ:PTNU:MGBN:53W5:6QHA:PBPB:3QOR:OJZT:G46Z
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-03-13T08:20:43.5565689-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Pro - 1709 build 16299.248

**Comment by stalb** [comment]
Docker windows doesn't use unix socket but named pipe `npipe:////./pipe/docker_engine`.
With linux container option it works because in this case the docker daemon run in a full virtualized linux instance (which uses a unix socket...).
What you can do is to use a tcp socket instead: if the lcow container has access to this tcp socket, it will b able to control the windows docker daemon.

**Comment by thaJeztah** [comment]
Yes, this is currently expected; LCOW is also still experimental, and not yet feature complete.

I’ll close this issue for now, but feel free to continue the conversation

**Comment by edrevo** [comment]
Are there any plans to add support for the scenario that @jbellmore describes? Or is that a non-supported scenario?

**Comment by edrevo** [comment]
Yes, I understand that LCOW uses a named pipe. I am wondering if providing an easy way of using a docker client from a linux container on LCOW is part of LCOW's roadmap (maybe with a solution similar to https://github.com/jstarks/npiperelay ?)

**Comment by fayep** [comment]
I used to open the insecure docker socket but then moved to using socat and npiperelay under wsl.  It effectively gives me an automatic /var/run/docker.sock in wsl which works as expected. It would be great if we could access the socket either by bind mounting npipe:////.pipe/docker_engine:/var/run/docker.sock or having the docker daemon interpret a request to mount /var/run/docker.sock:/var/run/docker.sock appropriately for least surprise and most convenience respectively.

**Comment by edrevo** [comment]
@fayep, have you managed to chare the docker.sock file in WSL with a container? I've tried it but I get `invalid volume specification: '/var/run/docker.sock:/var/run/docker.sock:ro'`

**Comment by tracker1** [comment]
I'm with @fayep on this one... `-v /var/run/docker.sock:/var/run/docker.soc` works with docker desktop, the same behavior would be really nice with LCOW.  Also, it would be nice if `-v npipe:////.pipe/docker_engine:/var/run/docker.sock` or `-v "npipe:////.pipe/docker_engine":/var/run/docker.sock` worked as well.

@fayep do you have a blog article describing how to setup socat so that it can be passed to containers?  Or, do you have to start it, and then run the containers from LSW?
