### ISSUE TITLE
Cannot create overlay network through remote API

### ISSUE THREAD

**Issue by izanagi1995** [moby/moby#36602]
**Description**

When a docker daemon is connected to external k/v store, the creation of an overlay network should work without any probem but when I try to create one with the Golang SDK (see code below), it fails with the message : `Error response from daemon: datastore for scope "global" is not initialized`

When doing the exact same process but passing the corresponding command through ssh, it does work.

**Steps to reproduce the issue:**
1. Connect to a Docker daemon with the Golang SDK.
2. Try to create an overlay network with the following code
```golang
response, err := konduktorDocker.NetworkCreate(context.Background(), "mikrodock-overlay", types.NetworkCreate{
	Driver:     "overlay",
})
```
3. An error is returned

**Describe the results you received:**

The error is `Error response from daemon: datastore for scope "global" is not initialized`
**Describe the results you expected:**

No errors should be returned as the datastore condition is fullfilled.

**Additional information you deem important (e.g. issue happens only occasionally):**

As said above, doing the same process with the SSH command is working fine : `docker network create -d overlay mikroverlay`

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: konduktor
ID: DPUY:BG4I:5DEE:AR4S:TGIF:LW5Q:L4QD:KXJB:6GNK:RPAZ:AJ7B:W75D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Cluster Store: consul://HIDDEN_FOR_SECURITY
Cluster Advertise: HIDDEN_FOR_SECURITY:2376
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running this on Droplets from DigitalOcean

**Comment by cpuguy83** [comment]
Can you provide more details? Are you sure you are hitting the same docker instance?
The docker CLI is just using the same HTTP API.

**Comment by izanagi1995** [comment]
I was hitting another instance... Thank you for pointing this out ! I promise that I will never code again at 1AM :joy:
