### ISSUE TITLE
#36519 causes daemon to continually spin CPU

### ISSUE THREAD

**Issue by jhowardmsft** [moby/moby#36608]
https://github.com/moby/moby/pull/36519 changed daemon/stats/collector.go so that `Run()` sits in a tight loop spinning the CPU. Just starting the docker daemon is enough, no client operations needed

It spins as follows:

```
1	for {
		// it does not make sense in the first iteration,
		// but saves allocations in further iterations
2		pairs = pairs[:0]

3		s.m.Lock()
4		for container, publisher := range s.publishers {
			// copy pointers here to release the lock ASAP
			pairs = append(pairs, publishersPair{container, publisher})
		}
5		s.m.Unlock()
6		if len(pairs) == 0 {
7			continue --> 1
		}
```

@stevvooe  @thaJeztah

**Comment by thaJeztah** [comment]
Guess we need a `time.Sleep(s.interval)` here; https://github.com/moby/moby/blob/623b1a5c3c7d6b4d6d5943b64bd9ae6a7813786e/daemon/stats/collector.go#L104-L106 and here https://github.com/moby/moby/blob/623b1a5c3c7d6b4d6d5943b64bd9ae6a7813786e/daemon/stats/collector.go#L109-L112

Alternatively, put the `time.Sleep(s.interval)` at the start of the loop

**Comment by stevvooe** [comment]
Is there any error logged? The difference here is that it can fail for each pair. What is the actual error preventing the sampling of cpu usage?

**Comment by stevvooe** [comment]
Ok, I see. There needs to be a sleep after the continue when no stats are being sampled.

**Comment by thaJeztah** [comment]
I'll open a PR, putting the sleep at the start (discussing with @stevvooe on slack)

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/36609
