### ISSUE TITLE
flaky test integration-cli/DockerSuite.TestPostContainersAttach()

### ISSUE THREAD

**Issue by kolyshkin** [moby/moby#36611]
Looking at recent PRs CI, there are a few failures like this:

```
11:03:32 
11:03:32 ----------------------------------------------------------------------
11:03:32 FAIL: docker_api_attach_test.go:98: DockerSuite.TestPostContainersAttach
11:03:32 
11:03:32 docker_api_attach_test.go:211:
11:03:32     c.Assert(actualStdout.Bytes(), checker.DeepEquals, []byte("hello\nsuccess"), check.Commentf("Attach didn't return the expected data from stdout"))
11:03:32 ... obtained []uint8 = []byte{0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73}
11:03:32 ... expected []uint8 = []byte{0x68, 0x65, 0x6c, 0x6c, 0x6f, 0xa, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73}
11:03:32 ... Attach didn't return the expected data from stdout
11:03:32 
```

in particular:
* https://github.com/moby/moby/pull/36606 on **z** ([logs](https://jenkins.dockerproject.org/job/Docker-PRs-s390x/8958/console))
* https://github.com/moby/moby/pull/36609 on **powerpc** ([logs](https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/9025/console))
* https://github.com/moby/moby/pull/36594 on **z** ([logs](https://jenkins.dockerproject.org/job/Docker-PRs-s390x/8960/console))

**Comment by ncdc** [comment]
This sounds like something has regressed w.r.t. attach+logs. The test is confirming this flow:

1. Start container
1. Container writes some data to stdout
1. Attach to container with logs=true
1. Write data to stdin of attach
1. The output from attach should have the data written from step 2 (thus verifying logs=true) and from step 4 (verifying data emitted post-attach)

Is it possible the data from step 2 is somehow not yet written/available?

**Comment by thaJeztah** [comment]
Commented on the PR, but wondering if there could be a relation with https://github.com/moby/moby/pull/36517, which was merged recently

**Comment by kolyshkin** [comment]
> Is it possible the data from step 2 is somehow not yet written/available?

Well, `echo` is obviously executed before `cat`, and I can't think of a scenario in which `echo` output would appear later than the one from `cat`. So _maybe_ this failure reveals a real bug.

**Comment by kolyshkin** [comment]
OK, one difference is `io.ReadFull()` reads the exact predefined amount of bytes (the size of the buffer passed), while the `StdCopy()` reads until `EOF` (which apparently it never gets as stdin is closed later) or until timeout (which happens in a second and which should be ignored by the test.

**Comment by anusha-ragunathan** [comment]
One more failure https://jenkins.dockerproject.org/job/Docker-PRs/48603/console

**Comment by kolyshkin** [comment]
This was presumably fixed by https://github.com/moby/moby/pull/36663. Let's reopen if we'll see more failures.
