### ISSUE TITLE
Docker pull - Access is denied.

### ISSUE THREAD

**Issue by TBurda** [moby/moby#36618]
A few months ago I pull image (microsoft/windowsservercore:1709) and created several images using the dockerfile. If I pull a new image (microsoft/windowsservercore:1709), I get error:

```
docker pull microsoft/windowsservercore:1709

PS C:\Docker\Images> docker pull microsoft/windowsservercore:1709
1709: Pulling from microsoft/windowsservercore
5847a47b8593: Already exists
85f53e48ded4: Extracting [=================================================> ]  744.8MB/745MB
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\6e8bd47c51704e55c1b3cafab3adda65f00e1ba4ac9fa663ef4224814c0d08b1\UtilityVM\Files\Windows\WinSxS\amd64_microsoft-windows-a..ence-inventory-core_31bf3856ad364e35_10.0.16299.15_none_81bfff856a844456\aepic.dll: Access is denied.
```

### Information
OS: Windows server 1709
Docker: 17.06.2-ee-6

### Steps to reproduce the behavior
1. docker pull microsoft/windowsservercore:1709
2. docker build (My image)
3. docker save (My image)
4. docker rmi
5. microsoft/windowsservercore:1709
6. docker load
7. (My image)
8. docker run (My image)
9. docker pull
10. microsoft/windowsservercore:1709 !!Only if image is updated - Docker Hub!!

**Comment by thaJeztah** [comment]
ping @PatrickLang @jhowardmsft

**Comment by PatrickLang** [comment]
This is probably the same as https://github.com/moby/moby/issues/36092

**Comment by thaJeztah** [comment]
Ah, yes, let me close this one in favor of https://github.com/moby/moby/issues/36092
