### ISSUE TITLE
Special characters in filenames of shared volumes are replaced with ?? (e.g. German umlauts)

### ISSUE THREAD

**Issue by Milania1** [moby/moby#36616]
**Description**

When shared volumes containing filenames with non-ASCI characters (e.g. German umlauts: üöä) are used, then these filenames are not displayed correctly. Instead, every special character is replaced by two `??`.

Note: this issue is also [reported in the docker/for-win repository](https://github.com/docker/for-win/issues/986#issuecomment-372392192) and currently closed due to its age. However, since the issue is not only related to Windows (and still exists), I re-report it here as well.

**Steps to reproduce the issue:**
1. Prepare a folder which serves as shared volume and place a file in it (here in the home directory):
```
~$ mkdir docker-test
~$ cd docker-test
~/docker-test$ touch test-öäü.txt
~/docker-test$ ls
test-öäü.txt
```
2. Create a container and mount a shared volume to the previously created folder:
```
~/docker-test$ sudo docker run -it -v ~/docker-test:/docker_filename-issue ubuntu
root@0a56a09c3a30:/# ls
bin   dev                    etc   lib    media  opt   root  sbin  sys  usr
boot  docker_filename-issue  home  lib64  mnt    proc  run   srv   tmp  var
root@0a56a09c3a30:/# cd docker_filename-issue/
root@0a56a09c3a30:/docker_filename-issue# ls
test-??????.txt
```

**Describe the results you received:**
The filename is not correctly displayed.

**Describe the results you expected:**
Would be awesome if filenames with special characters could be used :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:38 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:09 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-37-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: mila-VirtualBox
ID: QL4H:DFKR:SBQ5:6U6J:MG2I:BFF7:QC4M:IUBD:GGYS:ZPY6:BBKB:B4JG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested in VirtualBox and on Windows 10 version 1709 (build number 16299.248).

**Comment by cpuguy83** [comment]
This doesn't seem like anything to do with Docker.
Have you set the locale correctly in the container?

**Comment by Milania1** [comment]
OMG, how stupid of me not to think about locales...

Indeed, after [setting the correct locale](https://stackoverflow.com/a/38553499/2762258) the issue is resolved and the filename displayed correctly.

Some issues are really resolved fast if the right person is asked^^. Thanks a lot!

**Comment by cpuguy83** [comment]
Sweet, glad it's resolved!
