### ISSUE TITLE
docker bridge conflicts with external private ip address range despite configuration to use another range

### ISSUE THREAD

**Issue by drocsid** [moby/moby#36619]
Docker bridge configuration conflicts with private address range, setting configuration to another CIDR still creates networking conflicts.

I'm using `Docker version 17.12.0-ce, build c97c6d6`

I've set `/etc/docker/daemon.json` like :

```{
  "bip": "192.168.1.5/24",
  "fixed-cidr": "192.168.1.5/25" }
```

based on the reference https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/

I'm running `debian sid`

When I start docker I see 3 interfaces created: `ip addr`

```
17: br-3b0a9f7b8311: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:83:02:91:49 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-3b0a9f7b8311
       valid_lft forever preferred_lft forever
18: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:ce:94:59:89 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.5/24 brd 192.168.1.255 scope global docker0
       valid_lft forever preferred_lft forever
19: br-df98860c1f51: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d2:aa:90:64 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-df98860c1f51
       valid_lft forever preferred_lft forever```

`docker0` seems to have the `bip` specified in the config:  `192.168.1.5`


But the related bridge interfaces that are created when docker starts have a `172` range which conflicts with an internal private network which I'm using. 

Why aren't the related `br-` interfaces using the `fixed-cidr` range?

In case anybody asks `brctl show`:

```bridge name    bridge id        STP enabled    interfaces
br-3b0a9f7b8311        8000.0242b66f16e9    no        
br-df98860c1f51        8000.024216a3ed19    no        
docker0        8000.02426f66d702    no```    

**Steps to reproduce the issue:**
1. Set configuration in /etc/docker/daemon.json to not allow bridge in 172 address range


**Describe the results you received:**

bridge interfaces in conflicting 172 address range

**Describe the results you expected:**

not allow bridge interfaces in conflicting 172 address range

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**



```
Docker version 17.12.0-ce, build c97c6d6
```

**Output of `docker info`:**

```
docker info
Containers: 27
 Running: 0
 Paused: 0
 Stopped: 27
Images: 152
Server Version: 17.12.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-2-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.38GiB
Name: M00974055
ID: DEH3:RDHW:EAB7:IKGV:NO4X:ITUB:MM5T:AQEN:ZYAU:6W5M:N2RQ:UOYF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
> Set configuration in /etc/docker/daemon.json to not allow bridge in 172 address range

Can you provide the exact steps, exact configuration you're using?

Also see  [How do I configure the default bridge (docker0) network for Docker Engine to a different subnet?](https://success.docker.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet), [Configure the default bridge network](https://docs.docker.com/network/bridge/#configure-the-default-bridge-network), 
https://github.com/moby/moby/issues/36403#issuecomment-368892546, and  (creating a [custom bridge](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/build-bridges/))

**Comment by drocsid** [comment]
From https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/

I am currently setting:

```
cat /etc/docker/daemon.json 
{
  "bip": "192.168.1.5/24",
  "fixed-cidr": "192.168.1.5/25",
  "fixed-cidr-v6": "2001:db8::/64",
  "mtu": 1500
}
```

**Comment by drocsid** [comment]
@thaJeztah sorry if there are some formatting issues in my bug report. I also reported this in the #docker-networking slack channel. Please have a look if you can.

**Comment by drocsid** [comment]
@thaJeztah Do you happen to know why the 2 additional `br-*` interfaces are created when starting docker? These are the ones which conflict with my private network.

**Comment by thaJeztah** [comment]
do you have existing networks? I suspect switching the bridge may not be possible after networks are created, as docker stores configuration of those networks

(not sure, but this could explain those)

**Comment by drocsid** [comment]
Not sure what you mean by existing networks. What I do is delete all the bridge interfaces and `docker0` and the `br-` interfaces are created when docker launches. The `br` interfaces seem to not allow me to locally resolve `172.XX.XXX.XX` addresses that I could otherwise. This is blocking my use of docker as a development tool...

**Comment by thaJeztah** [comment]
I see you have 27 running containers; if those containers were created before you changed the configuration, those containers likely were attached to a network (`docker network ls` should show those networks); changing the configuration does not change the definition of existing networks, so if the daemon starts, it will create interfaces for those networks

**Comment by drocsid** [comment]
I will look at the `network` and `stopped` containers on monday. Thanks!

**Comment by drocsid** [comment]
I had a look. Didn't realize a stopped container would create network configuration on starting the docker daemon. `docker network prune` was all that was needed to remove the conflicting networks. My bad. Thanks for pointing this out.

**Comment by thaJeztah** [comment]
Good to hear it worked 👍
