### ISSUE TITLE
They're close, but "docker.for.mac.host.*" and "docker.for.win.*" should be better

### ISSUE THREAD

**Issue by atrauzzi** [moby/moby#36625]
When running Docker for Windows and Docker for macOS, we get these handy aliases like `docker.for.mac.localhost`, `docker.for.mac.internal`, `docker.for.win.localhost` and `docker.for.win.internal`.

Unfortunately, when my projects are being worked on between macOS and Windows, someone has to go changing any of these host names for the specific platform they're on, despite the premise of the two being the same!  The fact that these two things that accomplish the exact same outcome are named differently is unhelpful.

Is there any way we can get a new convention like `docker.internal` and `docker.localhost`? Would it also be possible to simply have them resolve `localhost` when used on Linux which obviously doesn't have the extra layer going on?

The name of the game here is that I need my containers to have a consistent way to reference not the VM, but the actual physical hardware they're running on. Bonus points if it's a consistent IP address so that I can configure my own DNS aliases!

Moreover, would it be possible either with or without my suggested change to get all these magic hostnames documented somewhere? They seem to be rather un-googleable and largely defined by anecdotal knowledge rather than being clearly offered.

**Comment by thaJeztah** [comment]
This is a feature on docker for desktop (Docker for Windows, Docker for Mac), and not part of the code that's being maintained in this repository. Could you open ticket for this in either the Docker for Windows (https://github.com/docker/for-win/issues) or Docker for Mac (https://github.com/docker/for-mac/issues) issue tracker?

I'll close the issue here, but feel free to continue the conversation

**Comment by thaJeztah** [comment]
For the documentation: I think it's documented under the "I want to connect from a container to a service on the host" heading in the documentation https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds, but perhaps it should be hightlighted more; it's best to open a ticket for that in the documentation issue tracker; https://github.com/docker/docker.github.io/issues

**Comment by atrauzzi** [comment]
Awesome, I'll definitely do so.  Thanks for the pointers 😉
