### ISSUE TITLE
Creating FIFO Files in user namespace?

### ISSUE THREAD

**Issue by rhatdan** [moby/moby#36622]
Readying through the copy.go code in daemon/graphdriver/copy/copy.go
I see these lines:

```		
               case os.ModeSocket:
			if rsystem.RunningInUserNS() {
				// cannot create a device if running in user namespace
				return nil
			}
			if err := unix.Mkfifo(dstPath, stat.Mode); err != nil {
				return err
			}

		case os.ModeDevice:
			if err := unix.Mknod(dstPath, stat.Mode, int(stat.Rdev)); err != nil {
				return err
			}
```
The comment about running in a userns indicates that you can not create a device in a user namespace?  Is this just a problem with making fifo files?  Should it also cover the devices being mknod in ModeDevice?

I was searching for some place that says you can't create devices or fifo files in a user namespace, but I have not found anything?

**Comment by thaJeztah** [comment]
This was added in https://github.com/moby/moby/commit/617c352e9225b1d598e893aa5f89a8863808e4f2 (https://github.com/moby/moby/pull/20902 / https://github.com/moby/moby/pull/25672)


ping @hallyn @estesp PTAL
