### ISSUE TITLE
FROM ARG FROM ARG doesn't behave as expected with multi-stage builds

### ISSUE THREAD

**Issue by frebib** [moby/moby#36623]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Minimum (non) working example:

```Dockerfile
FROM alpine as step1
ARG VERSION=1.0

FROM alpine
ARG VERSION
RUN echo VERSION: ${VERSION}
LABEL org.label-schema.version=${VERSION}
```

**Steps to reproduce the issue:**
1. See example above
2. Build container
3. Observe

**Describe the results you received:**
The RUN statement on line 6 prints no version

**Describe the results you expected:**
The second `ARG VERSION` command should pull the argument through to the second build stage however it does not. We seem to think that this should be the expected behaviour, given what the documentation says about scope: https://docs.docker.com/engine/reference/builder/#scope

I noticed this comment, following a PR and discussion about a similar issue, speculating that this is intended behaviour https://github.com/moby/moby/issues/34008#issuecomment-313693172

Related? https://github.com/moby/moby/issues/34008

It seems to us like this should work as per the example above passing through the argument to the RUN and LABEL steps after the second FROM.

Can we get some clarification on what the intended behaviour should be? Cheers :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 1.957GiB
Name: DockerDev
ID: S4XC:BSNL:QRC6:YYRD:XI7P:VCXH:EVI7:PLNT:TGPI:6ORE:YWQ7:CGW2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: adamant
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Output of `docker info`:**

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.4
 Git commit:	fc4de447b5
 Built:	Tue Feb 13 15:28:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:14:59 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
This seems to behave exactly as documented in scope.

The arg must be defined in each build stage you want to use it in, and that goes along with the default value of it for that stage.

**Comment by frebib** [comment]
So are you saying there is no method of defining a build argument and having it persist across ~~multiple~~ all build stages?

**Comment by frebib** [comment]
I just tried the following:

```Dockerfile
ARG TEST="this is a test"

FROM alpine
ARG TEST
RUN echo $TEST                             # prints "this is a test"

FROM alpine
ARG TEST
RUN echo $TEST                             # prints "this is a test"
```

which produces the expected results of printing `this is a test` in both stages.
I was misinterpreting how the scope worked originally.

An example such as the following better demonstrates the scope of these ARGuments:
```Dockerfile
frebib@frebib-PC /t/tmp.O7b3EecqcZ> cat Dockerfile                          
ARG TEST="this is a test"

FROM alpine
ARG TEST="new value 1"
RUN echo $TEST                             # prints "new value 1"

FROM alpine
ARG TEST
RUN echo $TEST                             # prints "this is a test"
```

where the second ARG, after the first FROM overrides the first ARG where the scope is within the FROM block. The second ARG has no override therefore defaults to the value set in the parent scope.

This answers my question and seems to be working as intended. Thanks for the help

**Comment by cpuguy83** [comment]
Thanks!
