### ISSUE TITLE
Bind mounts from Windows Subsystem for Linux cause an error

### ISSUE THREAD

**Issue by atrauzzi** [moby/moby#36624]
I've done some cursory searching around and people seem to have reported success with starting containers *without* bind-mounts.  But it seems like as soon as that becomes a requirement, the trail goes cold.

I have my env configured with `DOCKER_HOST=localhost:2375` at all times so that my SFL environment is pointed to what's running in Hyper-V.

I have a simple compose file that has the following bind mounts configured:

```
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf"
      - "./resources/nginx.default.conf:/etc/nginx/conf.d/default.conf"
```

Here's what I get when I try to do `docker-compose up`:
```
Creating proxy ... error

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/Users/atrauzzi/Development/org/home/resources/nginx.conf
\\\" to rootfs \\\"/var/lib/docker/overlay2/bce858e220f7eb485dac80f0ce11e8615b44d350cf16ebe7ee1a816e8540e045/merged\\\" at \\\"/var/lib/docker/overlay2/bce858e220f7eb485dac80f0ce11e8615b44d350cf16ebe7ee1a816e8540e045/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\
\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/Users/atrauzzi/Development/org/home/resources/nginx.conf
\\\" to rootfs \\\"/var/lib/docker/overlay2/bce858e220f7eb485dac80f0ce11e8615b44d350cf16ebe7ee1a816e8540e045/merged\\\" at \\\"/var/lib/docker/overlay2/bce858e220f7eb485dac80f0ce11e8615b44d350cf16ebe7ee1a816e8540e045/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\
\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

Most likely thing that comes to mind is that the paths being resolved by `docker-compose` in SFL vs. where paths actually are for what's going on with Docker for Windows are totally different. Unfortunately I have no idea what I could do to tell Docker for Windows to fiddle with the paths, or to tell `docker-compose` to hand them off a certain way...

cc. @bitcrazed

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.
