### ISSUE TITLE
Edge cases when reloading dockerd

### ISSUE THREAD

**Issue by guillaumerose** [moby/moby#36632]
**Description**

Sending HUP signal to dockerd doesn't reload properly the configuration. It mixes the previous one and the new one. 

**Steps to reproduce the issue:**
1. Start docker with daemon.json ```{
  "debug" : true,
  "experimental" : false
}```
2. Edit daemon.json ```{
  "debug" : true,
  "experimental" : true
}```
3. Reload `pkill -HUP dockerd`
4. `docker version` shows experimental false

Other case: 

1. Start docker with daemon.json ```{
  "debug" : true,
  "experimental" : false
}```
2. Edit daemon.json ```{
  "debug" : true,
  "insecure-registries" : [
    "foobar"
  ],
  "experimental" : true
}```
3. Reload `pkill -HUP dockerd`
4. `docker info` shows foobar, it's ok
5. Edit daemon.json ```{
  "debug" : true,
  "experimental" : true
}```
6. Reload `pkill -HUP dockerd`
4. `docker info` still show foobar

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce-rc3
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	e730959
 Built:	Thu Mar  8 20:12:09 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	kubernetes

Server:
 Engine:
  Version:	18.03.0-ce-rc3
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	e730959
  Built:	Thu Mar  8 20:20:22 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All done with macOS inside Docker for Mac VM.

**Comment by daeMOn63** [comment]
Made a quick check here and found here: https://github.com/moby/moby/blob/6cb75dd5b61f438b026572aca0c191c7d2fb7694/daemon/reload.go#L12-L24 that not all configuration keys are reloadable (ie: experimental). I don't know yet if this is expected or not. 

But for insecure-registries there is something missing I guess. I tested updating this
https://github.com/moby/moby/blob/6cb75dd5b61f438b026572aca0c191c7d2fb7694/daemon/reload.go#L250-L255

with
```go
	} else {
               daemon.configStore.InsecureRegistries = nil
        }
```
which properly update the config when some keys get removed.

I can set this to other existing keys if needed. But for the unsupported keys I'd need confirmation if this is on purpose or if must be added.

**Comment by guillaumerose** [comment]
In Docker for Mac, when the user changes the daemon.json, the VM is completely restarted. It takes a lot of time both for the user and our CI. I would like to simply do a reload on the daemon. As a start, I can just restart the daemon.

Partial reload seems to be a weird behavior. At least an error log should appear (or remove the signal. As a sysadmin, I find it really misleading).

**Comment by thaJeztah** [comment]
I think we can simplify the reload case; let me open a PR for that.

w.r.t. not reloading properties that cannot be live-reloaded; we should probably refuse reloading the configuration altogether. I can have a look at that separately.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
