### ISSUE TITLE
Bind mount on container start

### ISSUE THREAD

**Issue by antoinetran** [moby/moby#36634]
**Description**

This is about the bind mount behavior: 

> Note: When creating bind mounts, using the long syntax requires the referenced folder to be created beforehand. Using the short syntax creates the folder on the fly if it doesn’t exist. See the bind mounts documentation for more information.

(source [here](https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax))

What works:

    When submitting to Swarm a docker-compose.yml with a service with bind mount, docker-compose refuses to run the service if the source directory does not exist.
    If the container is started with the source directory mounted, if I stop the service, and remove the directory, the container cannot start again, complaining about missing directory.

What does not work:

    If I stop the docker daemon, and remove the directory, then restart docker, then the container start and recreates the directori(es)!

**Steps to reproduce the issue:**
1. Creates a given directory in host (I did that with a MooseFs mount)
2. Starts a container with docker-compose up -d command and with a bind mount in the directory in compose V2.3, and with restart policy set to unless_stopped
3. Stops docker daemon.
4. Removes the given directory (MooseFs umount)
5. Starts deamon docker.

**Describe the results you received:**
The container has started and docker has created empty directories by itself. The application of course crashes because of missing files.

**Describe the results you expected:**
The container should be always restarting as long as the directories is not started and should not creates the directories by itself.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
> sudo docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 78
Server Version: 17.12.1-ce
Storage Driver: devicemapper
 Pool Name: docker-252:1-305205681-pool
 Pool Blocksize: 65.54kB
 Thin Pool Minimum Free Space: 10.74GB                                                                                                                                                                                           [22/1951]
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: dev-node-005...............
ID: VSBQ:AQU6:WY2U:PJ7Z:BJAS:IVOK:T5KK:KWW4:7UU3:GEAO:6XR4:6QUH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.node=processing
Experimental: false
Cluster Store: zk://dev-node-003:2181,dev-node-007:2181,dev-node-008:2181
Cluster Advertise: 10.0.1.25:2375
Insecure Registries:
 [XXXXXXXXXXXX]:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Almost all latest: docker-ce-17.12.1-ce / CentOs 7.4.1708 / docker-compose 1.19.0 / compose ref 2.3 / Swarm classic 1.2.8.

**Comment by antoinetran** [comment]
#35833

**Comment by thaJeztah** [comment]
I think this was fixed by https://github.com/moby/moby/pull/35833 indeed
