### ISSUE TITLE
Review winresources autogenerated package

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#36652]
The winresources package is only referenced in [cmd/dockerd/docker_windows.go](https://github.com/moby/moby/blob/250193387c98a4ad69a6591d5fe5a39c1409ffba/cmd/dockerd/docker_windows.go#L4), which is an empty file after https://github.com/moby/moby/commit/250193387c98a4ad69a6591d5fe5a39c1409ffba (https://github.com/moby/moby/pull/36243) was merged.

It looks like that import is still needed to embed the icon and manifest into the binary (in which case, at least a "do not remove" comment should be added). 

- if only the [`rsrc_` things are needed](https://github.com/moby/moby/blob/250193387c98a4ad69a6591d5fe5a39c1409ffba/hack/make/.go-autogen.ps1#L76-L83), should that import be changed to `github.com/docker/docker/autogen/winresources` (without `docker` / `dockerd`) and content of the [`docker`, `dockerd` directories](https://github.com/moby/moby/blob/250193387c98a4ad69a6591d5fe5a39c1409ffba/hack/make/.go-autogen.ps1#L58-L62) be moved one directory "up"? (as is done in the docker CLI [docker/cli repository](https://github.com/docker/cli/search?utf8=✓&q=winresources&type=))

We should also review what's in the `winresources` 

- there's a [docker.exe.manifest](https://github.com/moby/moby/blob/fd935ee63db31e73b5ee5594644e04b959ead374/hack/make/.resources-windows/docker.exe.manifest);
   - is a similar manifest needed for `dockerd.exe`, or should it be removed? 
   - should this manifest be added in the packaging repository https://github.com/docker/docker-ce-packaging ?
 - does the file need updating for newer versions of Windows?
- the [docker.ico](https://github.com/moby/moby/blob/fd935ee63db31e73b5ee5594644e04b959ead374/hack/make/.resources-windows/docker.ico) and [docker.png](https://github.com/moby/moby/blob/fd935ee63db31e73b5ee5594644e04b959ead374/hack/make/.resources-windows/docker.png) logo's are outdated (see https://www.docker.com/brand-guidelines for the current version of the logo)

- Resources (in this repository); https://github.com/moby/moby/tree/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/hack/make/.resources-windows
- Resources (moved to the CLI repository); https://github.com/docker/cli/tree/ae1618713f83e7da07317d579d0675f578de22fa/scripts/winresources

ping @FSHA who should be able to assist with the correct logos

ping @salah-khan @jhowardmsft @simonferquel, who probably are more familiar with this :smile:

**Comment by jhowardmsft** [comment]
> The winresources package is only referenced in cmd/dockerd/docker_windows.go, which is an empty file after 2501933 (#36243) was merged.

It doesn't matter which file the import goes into, but it must be in at least one _windows.go file.

> It looks like that import is still needed to embed the icon and manifest into the binary

Correct. Unless manifested, it will not report or act on the correct version information, and the daemon would think it's running on 8 (possibly 8.1, need to check MSDN docs).

> We should also review what's in the winresources

This is autogenerated at compile time through .go-autogen.ps1 (or the equivalent for cross compilation).



> is a similar manifest needed for dockerd.exe, or should it be removed?

Absolutely must NOT be removed. The daemon will not work. Client, possibly, depends if takes actions depending on Windows version, it which case it is required.

**Comment by thaJeztah** [comment]
> This is autogenerated at compile time through .go-autogen.ps1 (or the equivalent for cross compilation).

Ah, yes, meant "what goes into the autogenerated package" (logos, manifest), sorry for the confusion there.

> No. Still the same for RS5 builds.

✅ thanks

> Up to you guys, but it certainly must stay in the moby/moby repo in order to be able to build a working binary out of that repo.

Makes sense, probably best to keep it here then for now

@jhowardmsft For the logos: do you know if there's a specific format/version/specific requirements? I'd like to update them with a more up-to-date version, so if there's specific requirements, I can forward those to the design team so that they can create a new version.

**Comment by jhowardmsft** [comment]
> @jhowardmsft For the logos: do you know if there's a specific format/version/specific requirements? I'd like to update them with a more up-to-date version, so if there's specific requirements, I can forward those to the design team so that they can create a new version.

I don't think there are hard requirements. There's probably something on MSDN documenting what is acceptable for hi-resolution screens, but I haven't specifically looked.

**Comment by johnstep** [comment]
From looking at the MSDN guidelines, and several Windows executables, I recommend the following formats for the icon resource, all 32-bit color: 256x256 PNG, 48x48 BMP, 32x32 BMP, and 16x16 BMP.

All sizes below 256x256 must be in BMP format, and only one icon 256x256 or larger will be used. The full set also includes 64x64, 40x40, 24x24, and 20x20, but those are not important, and Microsoft does not even author them for many built-in Windows executables.

**Comment by johnstep** [comment]
This icon will not be seen often since this is not the application icon used by Docker for Windows. It can be seen in Task Manager, or if a user browses to the directory in Explorer, or if a user runs dockerd.exe directly (not as a service) on Windows Server. Perhaps we should consider removing this icon altogether.

**Comment by FSHA** [comment]
Hello all, from product design: Just to make sure I follow correctly, this thread is asking for a Windows Native Icon for the OS.

Adding, changing for removing iconography that directly correlates to the brand or product aesthetic should follow our brand guidelines. I would suggest using whatever imagery is there currently, and opening the larger thread of rebranding the Windows product. Right now there are currently images and illustrations that correspond to illustrations done years ago. If there is another graphical technique introduced into the system, this will result in a fragmented experience for our users, and an unstable brand tactic. I support the idea of changing the iconography and imagery in the Product, however we should to that as a full sweep, not one image at at time.

@Raphaelbouchard for visibility

**Comment by thaJeztah** [comment]
@FSHA the current binaries already have a logo (I think that’s the only branding left in this repository); but the logo is outdated, so either the logo should be removed (possibly replaced with a “Moby” icon, or we should update it to the current version

**Comment by FSHA** [comment]
@thaJeztah Are you suggesting the Windows Desktop experience has ZERO illustrations, icons or graphics that reflect legacy branding in the entire UI, from first time user experience to fully acclimated into the system?

**Comment by thaJeztah** [comment]
@FSHA "Docker for Windows" has, but that's not open source, and not built from this repository (the configuration panel, installer, etc)

**Comment by FSHA** [comment]
@thaJeztah gotchya! Maybe a quick chat? Pardon my disconnect, I am not following the context! I will followup offline :)
