### ISSUE TITLE
Duplicated import of vendored package "go-connections/nat", when using "api/types/container" as a library

### ISSUE THREAD

**Issue by otiai10** [moby/moby#36664]
Hi, I really appreciate **docker** which helps me a lot everyday to build tools for bio-informatics, by using `docker/docker` as a go library. (e.g. [daap](https://github.com/otiai10/daap)). Docker is now a decisive tool to assure reproducibility of gene analytics or any other academical analytics workflows.

# Background

When I use `api/types/container` and want to configure `PortMap`, I have to import `github.com/docker/go-connections/nat` like this

```go
package mypackage

import (
	// ... many thins omitted

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/go-connections/nat"
)

func FooBarCreate(ctx context.Context) error {
	client, _ := createClient()
	_, err = client.ContainerCreate(
		ctx,
		&container.Config{/* omitted */},
		&container.HostConfig{
			PortBindings: nat.PortMap{
				// ...
			},
		},
		&network.NetworkingConfig{/* omitted */},
		"foobar",
	)
	return err
}
```

# Problem

The code above raises the following compile error

> cannot use "github.com/docker/go-connections/nat".PortMap literal (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value

This is because

1. `github.com/docker/docker/api/types/container` imports and uses the vendored `github.com/docker/go-connections/nat`
2. It's necessary to use the "nat" package to configure port bindings of the container
3. The "nat" package imported by the application is from standard `$GOPATH`, on the other hand, the required "nat" package is the vendored "nat" (`github.com/docker/docker/vendor/github.com/docker/go-connections/nat`)
4. → **Types unmatched!**

# Solution and Suggestion

This problem happens just because 3rd party application have to import "nat" by itself. Therefore this problem can be escaped if "container" package can provide **types of the vendored "nat" package** in behalf of standard imported "nat" package.

Fortunately, there is already made function in "nat" package which can accept primitive type and covert it to struct under "nat": https://github.com/docker/go-connections/blob/master/nat/nat.go#L124-L150

# Pull request

~~comes soon below~~
#36665

**Comment by thaJeztah** [comment]
Commented on the pr; https://github.com/moby/moby/pull/36665#issuecomment-375233320

**Comment by otiai10** [comment]
Thank you. Let's discuss on #36665

**Comment by vdemeester** [comment]
@otiai10 This is probably because you're using `go get` on your project, and it gets `github.com/docker/go-connections` and `github.com/docker/docker` without removing the `vendor` folder in `docker/docker`… thus it creates this error (see https://github.com/peterbourgon/wtf …)

To fix that you can either :
- Use a packaging system with your project, [`golang/dep`](https://github.com/golang/dep) is a good start I think
- Remove by end the `vendor` folder from `docker/docker` (sthg like `rm -R $GOPATH/src/github.com/docker/docker/vendor`) — not sure it will work correctly though.

**Comment by otiai10** [comment]
> without removing the vendor folder in docker/docker

Definitely. Thank you. I'm trying to strip `vendor` and flatten all the dependencies.

I'm gonna close this issue.
Can I close #36665 as well?

**Comment by vdemeester** [comment]
@otiai10 yes :angel:
