### ISSUE TITLE
Stack deploy fails silently due to read-only filesystem

### ISSUE THREAD

**Issue by dtakken** [moby/moby#36669]
**Description**

I use a docker stack that defines a top-level named volume for sharing read-only data among several services. To this end, the volume is mounted as a read-only volume in a couple of services (say on /var/www/app). These containers in turn bind mount host directories inside this read-only named volume (say on /var/www/app/plugins/test). These bind mounts are also read-only. When I attempt to use `docker stack deploy` to run it, the containers are not started and no warnings or errors appear on the terminal. In the docker logs, the following fatal error appears:

```
time="2018-03-22T11:30:38.499987235+01:00" level=error msg="fatal task error" error="starting container failed: oci runtime error: container_linux.go:265: starting container process caused \"process_linux.go:368: container init caused \\"rootfs_linux.go:57: mounting \\\\"/home/user/development/app/plugins/test\\\\" to rootfs \\\\"/var/lib/docker/btrfs/subvolumes/13c8f5f496c5a8f61096c83a466dbe76c05fe760c5b80b6e0629718c56ef227d\\\\" at \\\\"/var/lib/docker/btrfs/subvolumes/13c8f5f496c5a8f61096c83a466dbe76c05fe760c5b80b6e0629718c56ef227d/var/www/app/plugins/test\\\\" caused \\\\"mkdir /var/lib/docker/btrfs/subvolumes/13c8f5f496c5a8f61096c83a466dbe76c05fe760c5b80b6e0629718c56ef227d/var/www/app/plugins/test: read-only file system\\\\"\\"\"
```

When I remove the read-only option from the named volume mount, the containers start normally.

**Steps to reproduce the issue:**

1. Create a docker-compose.yml that defines a top-level volume and a service that:
  - mounts the volume read-only
  - bind mounts a host directory on a subdirectory of the mounted volume.
2. Use docker stack deploy to run it

**Describe the results you received:**

Deploy appears to execute normally but the containers do not start. The above fatal task error appears in the docker logs.

**Describe the results you expected:**

The containers should start normally. Or, at the very least, the docker client should generate an error.

**Additional information you deem important (e.g. issue happens only occasionally):**

Strangely, when I replace the read-only named volume with a read-only bind mount (which will still cause bind-mounts to be created inside another mounted read-only volume), the containers start normally. 

Apparently, there is a difference in how read-only mounts are handled between named volumes and bind mounts. It seems like mounting volumes inside other read-only mounted volumes is broken for named volumes.

I cannot remember running into this problem when doing the exact same thing using `docker run` and the `--volumes-from` option, before I moved to docker stack.

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Tue Feb 13 12:00:00 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Tue Feb 13 12:00:00 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 27
 Running: 10
 Paused: 0
 Stopped: 17
Images: 386
Server Version: 17.09.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.15
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: t4t3wzngk8gnfrp530b46fk0r
 Is Manager: true
 ClusterID: no0czt9qe005o6fgzizi48ex7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: oci runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: N/A (expected: )
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.8-1-default
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.45GiB
Name: thinkpad.local
ID: O4DM:S7C5:KSX4:7SCF:BCPW:BFSP:AGAH:G2KR:XIAV:7SVF:QIT4:ABC3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.0/16
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker runs on a physical machine.

**Comment by cpuguy83** [comment]
Can you supply an actual stack file that we can look at?also note that the swarm API's are async, so you have to check the status of the stack with "docker stack ps"

**Comment by thaJeztah** [comment]
closing, because more information is needed, but happy to reopen once provided
