### ISSUE TITLE
Feature request: add AWS Kinesis Stream as logging option for docker

### ISSUE THREAD

**Issue by Constantin07** [moby/moby#36668]
This is a feature request for adding support in docker of AWS Kinesis Streams.
This will allow to use scalable Kinesis as a "buffer" and avoid losing logs when the ingestion agent is not available (down) for some reason.

**Comment by thaJeztah** [comment]
Now that it's possible to implement logging-drivers as a plugin (https://docs.docker.com/engine/extend/), we prefer not to add more logging-drivers in the core functionality of docker; having the driver as a plugin allows upgrading the logging-driver without having to update the docker daemon, so makes it a lot more flexible.

I'll close this issue for that reason, but feel free to discuss
