### ISSUE TITLE
Block/disallow --net=host (host networking) on Mac OS

### ISSUE THREAD

**Issue by vhosakot** [moby/moby#36666]
**Description**

https://docs.docker.com/network/network-tutorial-host/ says:
> The host networking driver only works on Linux hosts, and is not supported on Docker for Mac

`--net=host` (host networking) does not work on Mac as it is not supported on Mac. https://forums.docker.com/t/should-docker-run-net-host-work/14215 also says that `--net=host` is not supported on Mac.

Hence, `--net=host` should be blocked/disallowed on Mac and an error like `--net=host (host networking) is not supported on Mac` should be displayed if `--net=host` is used on Mac. This way, users on Mac know that `--net=host` is not supported on Mac and will not waste time debugging host networking issues on Mac.

**Steps to reproduce the issue:**
1. Run any docker container with `--net=host` (host networking) on Mac.
    ```
    docker run -d --name docker-nginx --net=host -p 80:80 nginx
    ```
2. Check if the container's port can be accessed on the Mac host.
    ```
    $ curl localhost:80
    curl: (7) Failed to connect to localhost port 80: Connection refused
    ```

**Describe the results you received:**

Not able to access the container's port on the Mac host when `--net=host` is used on Mac.

**Describe the results you expected:**
```
$ docker run -d --name docker-nginx --net=host -p 80:80 nginx
ERROR: --net=host (host networking) is not supported on Mac.
```

**Additional information you deem important:**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: QWYO:HNLA:VPRN:ZTTG:YUNW:CO37:BWYB:L4Z5:CFDY:JC3H:A6DD:RQDM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 49
 System Time: 2018-03-22T04:19:59.058199778Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

Mac OS Sierra (version 10.12.6)

**Comment by AkihiroSuda** [comment]
Please propose this to https://github.com/docker/for-mac

**Comment by vhosakot** [comment]
Thanks for the suggestion @AkihiroSuda. I've opened https://github.com/docker/for-mac/issues/2716. I think fixing this issue makes user experience better on Mac as I've seen people spending lots of time debugging host networking (`--net=host`) issues on Mac.
