### ISSUE TITLE
WORKDIR creates directories as root instead of USER

### ISSUE THREAD

**Issue by Crazor** [moby/moby#36677]
**Description**
If I use USER to switch to a non-root user I added, directories created by WORKDIR are owned by root.

**Steps to reproduce the issue:**
```
cat <<EOF > Dockerfile
FROM alpine:latest
RUN adduser -S someone
USER someone
WORKDIR /test
RUN touch file
EOF
docker build .
```

**Describe the results you received:**
```
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM alpine:latest
 ---> 3fd9065eaf02
Step 2/5 : RUN adduser -S someone
 ---> Running in d1b5335d7d2b
Removing intermediate container d1b5335d7d2b
 ---> 6331753145ea
Step 3/5 : USER someone
 ---> Running in 6fc3e580f73f
Removing intermediate container 6fc3e580f73f
 ---> e287cc668fd4
Step 4/5 : WORKDIR /test
Removing intermediate container a5d76637e175
 ---> ec5080edf02c
Step 5/5 : RUN touch file
 ---> Running in 4d6f86d33ac9
touch: file: Permission denied
The command '/bin/sh -c touch file' returned a non-zero code: 1
```

**Describe the results you expected:**
I would expect the WORKDIR command to create a directory owned by the current USER.

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:09 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:36 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 12                                                      
 Running: 0                                                         
 Paused: 0                                                          
 Stopped: 12                                                        
Images: 9                                                           
Server Version: 18.03.0-ce                                          
Storage Driver: btrfs                                               
 Build Version: Btrfs v4.12                                         
 Library Version: 102                                               
Logging Driver: json-file                                           
Cgroup Driver: cgroupfs                                             
Plugins:                                                            
 Volume: local                                                      
 Network: bridge host ipvlan macvlan null overlay                   
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog                                                           
Swarm: inactive                                                     
Runtimes: runc                                                      
Default Runtime: runc                                               
Init Binary: docker-init                                            
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c        
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871              
init version: 949e6fa                                               
Security Options:                                                   
 apparmor                                                           
 seccomp                                                            
  Profile: default                                                  
Kernel Version: 4.13.0-37-generic                                   
Operating System: Ubuntu 17.10                                      
OSType: linux                                                       
Architecture: x86_64                                                
CPUs: 4                                                             
Total Memory: 15.37GiB                                              
Name: tachi                                                         
ID: RMAS:MPHW:4AUS:Q2OT:Y6JB:OAP4:A52N:DTDB:OBAX:KU2H:GBYP:HUIH     
Docker Root Dir: /var/lib/docker                                    
Debug Mode (client): false                                          
Debug Mode (server): false                                          
Registry: https://index.docker.io/v1/                               
Labels:                                                             
Experimental: true                                                  
Insecure Registries:                                                
 127.0.0.0/8                                                        
Live Restore Enabled: false                                         

WARNING: No swap limit support
```

**Comment by vdemeester** [comment]
cc @thaJeztah @tonistiigi @dnephin

**Comment by thaJeztah** [comment]
Correct; this has always been the case (similar to `ADD` and `COPY` also working as `root`); the recommendation is to not rely on workdir "magically" creating a directory, but creating the directory up-front with the right permissions and ownership.

You can find a recent discussion on this here; https://github.com/moby/moby/issues/36408

**Comment by Crazor** [comment]
I'm aware of the workaround possibilities. IMHO `WORKDIR` is more readable than `RUN mkdir test && chown user: test && cd test`, which is why I noticed this in the first place. Also it's kind of surprising what `WORKDIR` isn't influenced by `USER`. Since `USER` changes the user for `RUN`, `CMD` and `ENTRYPOINT` and `WORKDIR` changes the `cwd` for `RUN`, `CMD`, `ENTRYPOINT`, `COPY` and `ADD`, one would think that `USER` also changes the user for `WORKDIR`...

**Comment by thaJeztah** [comment]
> WORKDIR is more readable than RUN mkdir test && chown user: test && cd test

Only the `mkdir test` step would be needed; after that, you can use `WORKDIR /test`

I personally think that `WORKDIR` should not have automatically created directories; there's too much magic involved there, and there's many corner-cases where automatically changing ownership could  (e.g.; should `WORKDIR /foo/bar/baz` create all of `/foo`, `/foo/bar` and `/foo/bar/baz` with that owner, or only the last (`/baz`) directory? What if some of those directories already exist: should they be `chown`'d? What permissions should be set? `700`? `755` (and should it follow the `umask` that's set in the container, or use a fixed one, for constency? )


The problem at least is that we can't change the default behaviour of `WORKDIR`, because it would be a breaking change, and `WORKDIR --chown=myuser:mygroup /somedirectory` may not be much cleaner than `RUN mkdir /somedirectory`

**Comment by y3ti** [comment]
@thaJeztah thank you for edge-case example. I think that `WORKDIR /directory` should work the same way as `mkdir -p` in bash shell plus change the current working directory:

```
mkdir -p /directory
cd /directory
```

> should `WORKDIR /foo/bar/baz` create all of `/foo`, `/foo/bar` and `/foo/bar/baz` with that owner, or only the last (`/baz`) directory?

Yes, it should. This will work the same way as `mkdir -p /foo/bar/baz`

> What if some of those directories already exist: should they be chown'd?

No, it shouldn't. The same way as `mkdir -p` works:

```
# create a directory as a root
$ sudo mkdir directory

# directory is owned by root
$ ls -lh
total 0
drwxr-xr-x  2 root  staff    64B Jul  4 00:30 directory

# try to create a directory as a non-root user. 
$ mkdir -p directory

# the directory exists, so nothing happens
$ ls -lh
total 0
drwxr-xr-x  2 root  staff    64B Jul  4 00:30 directory

$ cd directory
```

> What permissions should be set? 700? 755 (and should it follow the umask that's set in the container, or use a fixed one, for constency? )

The same permissions as will be set by `sh -c "mkdir -p directory"`

**Comment by petr-motejlek** [comment]
Any chance we could actually "fix" `WORKDIR` by giving it `--chown` in the same fashion as `COPY` has it? I have recently posted about this in a related issue in Buildah: https://github.com/containers/buildah/issues/2323#issuecomment-629185595

Since `WORKDIR` already supports the directory creation, I think it would only make sense to make it work similarly to COPY. By giving it `--chown`, and retaining the original behavior of defaulting to root/root for the ownership, this would make it work very similar to `COPY`.

(I trully believe `WORKDIR` should have originally been only used simiarly to `EXPOSE` or `VOLUME`, ie metadata only, but that's not the case, sadly).

**Comment by thaJeztah** [comment]
> (I trully believe WORKDIR should have originally been only used simiarly to EXPOSE or VOLUME, ie metadata only, but that's not the case, sadly).

I agree. I'm not sure if we should dig ourselves in deeper though (by expanding options), and instead keep the recommendation to create the directory before setting the workdir.

@tonistiigi @tiborvass @AkihiroSuda any thoughts?

**Comment by thaJeztah** [comment]
It looks like this issue has been fixed in BuildKit (the next generation builder) enabled (`DOCKER_BUILDKIT=1`); https://github.com/moby/buildkit/pull/1002


With the example Dockerfile (I added a `RUN ls -ld /test`)


With BuildKit disabled (`DOCKER_BUILDKIT=0`), the build fails;

```bash
DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -<<'EOF'
FROM alpine:latest
RUN adduser -S someone
USER someone
WORKDIR /test
RUN ls -ld /test
RUN touch file
EOF

Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM alpine:latest
 ---> 14119a10abf4
Step 2/6 : RUN adduser -S someone
 ---> Running in 62aec89c54b4
Removing intermediate container 62aec89c54b4
 ---> ec2b00bc28ce
Step 3/6 : USER someone
 ---> Running in 10e8796ed0fa
Removing intermediate container 10e8796ed0fa
 ---> 8bf801ad051a
Step 4/6 : WORKDIR /test
 ---> Running in d6424a372918
Removing intermediate container d6424a372918
 ---> befdde4dece0
Step 5/6 : RUN ls -ld /test
 ---> Running in 796d9387da1f
drwxr-xr-x    2 root     root          4096 Nov  2 11:33 /test
Removing intermediate container 796d9387da1f
 ---> 7fa885b585cb
Step 6/6 : RUN touch file
 ---> Running in c47943b6801c
touch: file: Permission denied
The command '/bin/sh -c touch file' returned a non-zero code: 1
```

With BuildKit enabled, the directory is owned by `someone`, and the build completes successfully;

```bash
DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -<<'EOF'
FROM alpine:latest
RUN adduser -S someone
USER someone
WORKDIR /test
RUN ls -ld /test
RUN touch file
EOF


#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 138B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/alpine:latest
#4 CACHED

#5 [2/5] RUN adduser -S someone
#5 DONE 0.3s

#6 [3/5] WORKDIR /test
#6 DONE 0.0s

#7 [4/5] RUN ls -ld /test
#7 0.218 drwxr-xr-x    2 someone  nogroup       4096 Nov  2 11:32 /test
#7 DONE 0.2s

#8 [5/5] RUN touch file
#8 DONE 0.4s

#9 exporting to image
#9 exporting layers 0.0s done
#9 writing image sha256:53c7186acabaefbfc4b239e04ec08005f7e9fe4f850059719b4b409724ee96a3 done
#9 DONE 0.0s
```


The classic (non-buildkit) build is currently in "maintenance" mode, with the intent to use BuildKit as a default (it's already the default on Docker Desktop), so I'm not sure this will also be fixed for the classic builder.

**Comment by thaJeztah** [comment]
Let me close this ticket per the above, but feel free to continue the conversation.
