### ISSUE TITLE
"Removal In Progress" not always properly reset on container rm

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#36679]
Some people are reporting that in some cases when a container rm fails (for whatever reason, common thing seems to be in layer removal) the "Removal In Progress" flag is not reset.

https://github.com/docker/for-linux/issues/124#issuecomment-374589894 has multiple reports of this, though the issue itself was more focused on the actual removal error... this issue I'm bringing up here is about how apparently the flag is not reset properly.

There is also an interesting case here: https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/8998/console

**Comment by bsousaa** [comment]
@cpuguy83 is this still relevant?

**Comment by cpuguy83** [comment]
I haven't seen anyone mention this in forever nor have I seen it in CI, so I'm going to assume its ok to close at this point.
