### ISSUE TITLE
don't close the write connection on docker attac

### ISSUE THREAD

**Issue by Licenser** [moby/moby#36673]
I would ask that docker attach not closes the right side of the connection. This is a rather uncommon practice with makes it incredibly hard to implement API compatible services as not many libraries support this kind of behaviour. 

To underline this point: `hijack.go` Line 83 copies out a function from the library it uses for SSL as not even the libraries used by docker itself implement this behavior. 

```
// We need to copy Go's implementation of tls.Dial (pkg/cryptor/tls/tls.go) in
// order to return our custom tlsClientCon struct which holds both the tls.Conn
// object _and_ its underlying raw connection. The rationale for this is that
// we need to be able to close the write end of the connection when attaching,
// which tls.Conn does not provide.
```

https://github.com/docker/engine-api/blob/4290f40c056686fcaa5c9caf02eac1dde9315adf/client/hijack.go#L83

**Comment by cpuguy83** [comment]
The go tls conn does support `CloseWrite`, now: https://golang.org/pkg/crypto/tls/#Conn.CloseWrite

Do you have an example where this is a problem?
Also note that the `engine-api` repo is not maintained.

**Comment by cpuguy83** [comment]
We close the write side of the pipe to signal that we're done sending but can still receive.

**Comment by Licenser** [comment]
Yes but why, I don't think any HTTP request does that, i.e. what is the gain over handeling it like a normal HTTP request?

**Comment by cpuguy83** [comment]
It's not a normal HTTP request, which is what the hijack does.
The "hijack" is forgoing the http framing and using the raw connection.

**Comment by Licenser** [comment]
Yes I noticed that, but it doesn't answer why? Or is the the reasoning to make it not compatible with HTTP?

**Comment by cpuguy83** [comment]
For bi-directional streams.

**Comment by Licenser** [comment]
How is a half-open connection required for bi-directional streams?

**Comment by cpuguy83** [comment]
I explained this above?

We close the write side when the client is done sending but the daemon may not be done.
If we just close the connection there will be data loss.

**Comment by Licenser** [comment]
I think I don't manage to phrase my question correctly. Why not always use a full connection? It would make compatibility easier.

**Comment by cpuguy83** [comment]
It allows the daemon to free up resources and potentially even decide to close the whole thing down.

**Comment by Licenser** [comment]
I give up on this question, thank you for your help.
