### ISSUE TITLE
LCOW: bind mounting host case sensitivity (possibly WSL related)

### ISSUE THREAD

**Issue by rn** [moby/moby#36681]
Somewhat similar to https://github.com/moby/moby/issues/36613 but different, I have a directory called: `C:\Users\rneugeba\Desktop\lcow\tests\cases\900_perf\100_volume\020_single_dir\060_write_5000_files_512B`. Note it has mixed case. Everything under `C:\Users\rneugeba\Desktop\lcow` is actually a git repository which I have checked out/created with WSL but it lives on the normal non-WSL part of the filesystem.

If I volume mount this directory, I get an error:
```
C:\Users\rneugeba\Desktop\docker\docker.exe: Error response from daemon: invalid volume specification: 'C:\Users\rneugeba\Desktop\lcow\tests\cases\900_perf\100_volume\020_single_dir\060_write_5000_files_512B:/script': invalid mount config for type "bind": bind mount source path does not exist: c:\users\rneugeba\desktop\lcow\tests\cases\900_perf\100_volume\020_single_dir\060_write_5000_files_512b.
```

I have many other cases where the change in capitalisation for  `C:\Users\rneugeba\Desktop` does not matter, so this might be a file attribute thing related to WSL and the way this is handled in docker.

I'm on Windows 10 Pro Insider build 17120.rs4 and latest master (as of today):
```
Client:
 Version:       0.0.0-dev
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    a6d23543
 Built: Thu Mar 22 23:38:20 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      0.0.0-dev
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   766d9ed
  Built:        Thu Mar 22 23:45:34 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

/cc @jstarks @jhowardmsft

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
