### ISSUE TITLE
container getting stuck

### ISSUE THREAD

**Issue by RajeetN** [moby/moby#36680]
We are running into an issue where containers are sometimes getting stuck in starting state (Health check) and once they get stuck no operations can be performed via docker on them. Docker inspect, exec, stop all hang. Even rm -f gets stuck and we have to reboot the node to fix the issue.
The healthcheck is pretty basic:

"Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "wget --quiet --spider --tries=1 http://127.0.0.1:9001/ || exit 1"
                ],
                "Interval": 30000000000,
                "Timeout": 5000000000,
                "StartPeriod": 120000000000
            }

**Output of `docker info`:**

Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.779GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
Live Restore Enabled: false

WARNING: No swap limit support

How do we further investigate to root cause this issue?

Thanks!

**Comment by thaJeztah** [comment]
could you try updating to 17.12.1 or 18.03, and tell if you’re still able to reproduce this?

**Comment by olljanat** [comment]
ping @RajeetN

**Comment by olljanat** [comment]
Derek add label: version/unsupported

**Comment by olljanat** [comment]
Derek remove label: version/unsupported

**Comment by thaJeztah** [comment]
Let's close, because this one went stale
