### ISSUE TITLE
Docker for Mac `no_proxy` not honored

### ISSUE THREAD

**Issue by niothiel** [moby/moby#36705]
**Description**

Since the introduction of the transparent proxy, it seems like the Docker For Mac proxy settings are
broken. If Docker For Mac is configured to have a manual proxy that includes `no_proxy` directives, the transparent proxy fails to obey them when any container requests the data.

I believe this is due to an inherent limitation in the way DNS name resolution works that may be an oversight in the transparent proxy implementation. If a docker container that has no proxy settings configured tries to connect to a URL like `pypi.python.org`, it will first resolve the DNS name to some public ip (`1.2.3.4` for example) then tries to connect to that IP directly. The transparent proxy seems like it has no way of picking this up and issues a `CONNECT 1.2.3.4` request to the configured proxy, even though `pypi.python.org` may have been configured as a proxy exemption in the Docker for Mac settings. I believe it doesn't pick this up due to it seeing only that a TCP connection to port 80/443 is being made, but it doesn't know the underlying DNS name for this operation so the Docker For Mac settings are being ignored due to lack of information (that is, the actual request the proxy sees is `1.2.3.4` instead of `pypi.python.org`).

This is a big limitation as the DNS names resolve to varying different IPs in a cloud-based environment, and including all possible IPs in the `no_proxy` variable is prohibitive. I believe the above information is accurate based on my packet-tracing efforts (specifically the transparently-proxied `CONNECT {host}` requests).

**Steps to reproduce the issue:**
1. Configure Docker for Mac to use a proxy server and put `pypi.python.org` into the no_proxy portion.
2. Start up a docker container with no proxy settings configured.
3. Run `curl pypi.python.org` while packet-capturing the traffic

**Describe the results you received:**
A `CONNECT` request being made to the proxy with the literal IP that `pypi.python.org` resolved to, even though it has been specified in the Docker for Mac settings as not using the proxy.

**Describe the results you expected:**
Observe a direct connection from the docker container to `pypi.python.org` via a packet-capture of the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

Nothing of note here.

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true

```

**Output of `docker info`:**

```
Containers: 65
 Running: 1
 Paused: 0
 Stopped: 64
Images: 99
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TQV2:WS54:ICKU:MGKD:3W2J:MYGP:VNWE:4MPH:UTMD:PVFA:K544:XVQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 56
 System Time: 2018-03-27T00:31:28.819051691Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Standard Docker for Mac installation, configured with an authenticated corporate proxy.

**Comment by AkihiroSuda** [comment]
Please report this to https://github.com/docker/for-mac/issues
