### ISSUE TITLE
Support msgpack for API.

### ISSUE THREAD

**Issue by joeyhub** [moby/moby#36713]
Using the accept header is shouldn't be hard to provide msgpack. It'll be ten times faster/lower latency and most implementations support streaming out of the box which is not the case with JSON.

**Comment by cpuguy83** [comment]
I do not think we will be providing msgpack support.
There have been discussions of a "2.0" API leveraging protobufs.

Closing since I do not think msgpack is going to happen, but feel free to discuss.
Thanks! 😇 🙇
