### ISSUE TITLE
docker logs --follow hangs

### ISSUE THREAD

**Issue by dhirschfeld** [moby/moby#36718]
**Description**
As the title says `docker logs -f $containerId` prints the current log output then hangs forever.

**Steps to reproduce the issue:**
```powershell
docker logs -f $(docker run -d microsoft/windowsservercore:1709 ping -t google.com)
```

**Describe the results you received:**
```
PS C:\> docker logs -f $(docker run -d microsoft/windowsservercore:1709 ping -t google.com)

Pinging google.com [172.217.25.46] with 32 bytes of data:
Reply from 172.217.25.46: bytes=32 time=16ms TTL=52
<-- HANG HERE FOREVER -->
```

**Describe the results you expected:**
I expected the output of ping to be continually printed to the console stdout.

<details>
<summary>
<b>Output of <tt>docker version</tt>:</b>
</summary>

```
Client:
 Version:       master-dockerproject-2018-03-18
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    a5bd2973
 Built: Sun Mar 18 23:51:15 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      master-dockerproject-2018-03-18
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   72ba7f5
  Built:        Sun Mar 18 23:58:38 2018
  OS/Arch:      windows/amd64
  Experimental: false
```
</details>
<br>
<details>
<summary>
<b>Output of <tt>docker info</tt>:</b>
</summary>

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 49
Server Version: master-dockerproject-2018-03-18
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Datacenter Version 1709 (OS Build 16299.309)
OSType: windows
Architecture: x86_64
CPUs: 40
Total Memory: 255.9GiB
Name: DC1THWN01
ID: LPJW:MQ7R:OOYP:3FRK:VUR2:U3MI:VU4V:CB3N:HTLF:ZEQB:BFCW:73UT
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: dhirschfeld
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
</details>

**Comment by dhirschfeld** [comment]
ping! Anyone able to repro this?

**Comment by malpower** [comment]
why you use '-f' argument?

**Comment by dhirschfeld** [comment]
I want to continuously *follow* the output of the process inside the container (in this case ping).

i.e. I want the output to be continuously updated in real-time as the process displays it. This is so I can monitor the progress of the process inside the container

**Comment by avikivity** [comment]
Seems to work in moby-engine-18.06.0-2.ce.git0ffa825.fc29.x86_64.

**Comment by avikivity** [comment]
(I did reproduce it in older docker versions)

**Comment by dhirschfeld** [comment]
Thanks for the follow up @avikivity! I'll confirm and close if I can no longer reproduce...

**Comment by dhirschfeld** [comment]
Yeah, works for me now.

I'm glad someone fixed the bug. It would be nice if issues opened by users (with easy repros) were actually acknowledged by the maintainers, but I'll take the fix...

**Comment by avikivity** [comment]
It's back in moby-engine-18.09.8
