### ISSUE TITLE
mount paths on windows only work for the C: volume

### ISSUE THREAD

**Issue by arnead** [moby/moby#36717]
With the latest update (Version 18.03.0-ce-win59 (16762) the following does no longer work:
 docker run --mount type=bind,source=/d,target=/konbel-src -
it docker/image/name /bin/bash

Instead only paths starting with /c are supported

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
 Error response from daemon: invalid mount config for type "bind": bind source path does not exist.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
 docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
From your output (Windows client, Linux daemon), I suspect this was either Docker Desktop, or Docker Toolbox (boot2docker), both of which may need additional drives to be configured before they can be accessed through bind-mounts.


Let me close this ticket for now, as it looks like it went stale.
