### ISSUE TITLE
Volume mount case sensitivity and duplication

### ISSUE THREAD

**Issue by bzier** [moby/moby#36716]
Copied from `docker/for-win` [issue](https://github.com/docker/for-win/issues/1273). They closed and suggested opening an issue here. This appears that it may be similar to #36613 & #36681, except this is regarding Windows containers (not LCOW).

As far as I know this is still an issue. I don't have the ability to repro it on the machine I'm using at the moment, but will re-test as soon as I can and post back here.

----

### Expected behavior
Mounting a volume to a path as a part of `docker run` should take precedence over a volume being 'exposed' or created as a result of the Dockerfile.

### Actual behavior
The path specified is case-sensitive (despite Windows being case-insensitive) resulting in two volumes being mounted to the same path within the container, one which was created with a unique ID as a result of the specification in the Dockerfile, one which was named as a part of the `docker run` command.

### Information

  - a reproducible case if this is a bug, Dockerfiles FTW
    using the Dockerfile for TeamCity [here](https://github.com/JetBrains/teamcity-docker-minimal-agent/blob/master/windowsservercore-1709/Dockerfile)
    line 17 is specified as `VOLUME C:/BuildAgent/conf`
    the (generalized) run command is:
    ```
    docker run -dit 
        --name SomeName
        -e SERVER_URL="https://teamCityServer:9999/"
        -e AGENT_NAME="SomeName"
        --mount source="my-custom-volume-name",target=C:\BuildAgent\conf
        repo/custom-team-city-image:1.0.0
    ```

  - host distribution and version (Windows version, build number, etc)
    `Docker version 17.06.1-ee-1, build 4dd6e94`
    ```
    Windows Server 2016 Datacenter
    ------------------------------
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    10     0      14393  0
    ```

### Steps to reproduce the behavior

  1. Expose a `VOLUME` in the Dockerfile using mixed-case (e.g. `VOLUME C:/BuildAgent/conf`) (also worth noting, in this case forward-slashes are used, but that may or may not make a difference)
  2. Run a container from the image specifying a named volume mount to the same location as specified above using the same case (e.g. `--mount source="my-custom-volume-name",target=C:\BuildAgent\conf`) (also worth noting, in this case back-slashes were used, but that may or may not make a difference)
  3. Run `docker volume ls` and note that two volumes were created, one with the name specified in step 2, and one with a unique ID
  4. Run `docker inspect <container ID>` to see the two mounts both pointing to the same container path; however, also note that the case of the generated mount is now all lower-case (also, the destination path back-slashes are escaped):
```
"Mounts": [
    {
        [...]
        "Destination": "C:\\BuildAgent\\conf",
        [...]
        "Destination": "c:\\buildagent\\conf",
        [...]
    }
]
```

Please feel free to let me know if you need any more information, or a more specific example. I haven't reproduced this outside of the context mentioned above, but I believe it would be fairly easy to do an isolated repro. If that would be helpful, please let me know.

**Comment by mback2k** [comment]
I encountered the same issue with `17.10.0-ee-preview-3`.

Dockerfile declares the following volume:
```
VOLUME C:\Buildbot
```

Using it in the following way with Docker stack **breaks** with the error message "The request is not supported." (0x32):

```
volumes:
 - slave-windows:C:\Buildbot
```

Only with all lower-case path it **works** as desired:

```
volumes:
 - slave-windows:c:\buildbot
```

**Comment by drnybble** [comment]
Docker 18.09.4

On Windows 2016 if you use uppercase in the target, the container runs but it writes to the anonymous volume, not the named volume.

On Windows 2019 if you use uppercase in the target, the container fails to start with this error:
```
Error response from daemon: CreateComputeSystem a59150e1dffca5784d5fbc3280826f8b25576f64883d69e1f07410e8fbbb7a66: The request is not supported.
(extra info: {"SystemType":"Container","Name":"a59150e1dffca5784d5fbc3280826f8b25576f64883d69e1f07410e8fbbb7a66","Owner":"docker","VolumePath":"\\\\?\\Volume{d335b2f7-9c89-402e-a98e-bd7aa5e6b5d0}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\a59150e1dffca5784d5fbc3280826f8b25576f64883d69e1f07410e8fbbb7a66","Layers":[{"ID":"29deec2a-e829-5a52-a512-754babb4612d","Path":"C:\\ProgramData\\docker\\windowsfilter\\503f9af629cfa5dce2c2085d617a45f75b7ba550bc9b8388ec580afe1660fe6f"},{"ID":"3c9809a1-6491-56da-8e20-5ec51a7a429f","Path":"C:\\ProgramData\\docker\\windowsfilter\\0b5e65add5c4fac7ad5cdf5c9648ecd77cb86d9de70eada1d2abc1b352b68dcb"},{"ID":"4b9e534c-fb9b-5e51-9933-4fb0b2bb97f0","Path":"C:\\ProgramData\\docker\\windowsfilter\\3c5983e65f00d57cb97f4dbeeba268894fec02d6171ad6b60d20ef21b6523f92"}],"HostName":"a59150e1dffc","MappedDirectories":[{"HostPath":"C:\\ProgramData\\docker\\volumes\\my_volume_test\\_data","ContainerPath":"C:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\docker\\volumes\\cb5d4aec9a9a901ce03ee45ea495e8ce49c6bacff0dbf83514afce3179a3d85e\\_data","ContainerPath":"c:\\data","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["13EBB48D-F299-4E4D-94BB-385848B1A86C"],"AllowUnqualifiedDNSQuery":true}).
```

**Comment by thaJeztah** [comment]
ping @jhowardmsft ptal

**Comment by thaJeztah** [comment]
Looks like this duplicates https://github.com/moby/moby/issues/36716
