### ISSUE TITLE
Events node down not sended everytime - 18.03.0-ce

### ISSUE THREAD

**Issue by omauger** [moby/moby#36729]
I have a swarm with 3 managers and 1 worker.
When I stop service with command: `service docker stop` on a manager not leader I receive the event node update with state.new down but sometimes I don't have the event and when I do command : `docker node ls` I have the node unreachable but status stay ready :
```
root@node3:/home/vagrant# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
x9w5ca7dr6rvc3hm17y1wcibn     node1               Ready               Active              Unreachable         18.03.0-ce
ve1jjbcn68pnidhvkya6x8twe     node2               Ready               Active              Leader              18.03.0-ce
l01nwnkrgmtmy12alvybtu5wr *   node3               Ready               Active              Reachable           18.03.0-ce
n0i1jko9emiy9dij920d5f57p     node4               Ready               Active                                  18.03.0-ce
```

When I stop service docker on leader node, the event is never send and the leader change but the status of the node stay Ready.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
