### ISSUE TITLE
Shared folder 'Users' is unavailable on Mac/Parallels after 18.03.0 upgrade

### ISSUE THREAD

**Issue by ancillaryfactory** [moby/moby#36723]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
When creating a Docker Machine on a Mac with the Parallels driver using 18.03.0-RC3 or later, the host /Users folder is not mounted, preventing any volumes from being mounted in a container. 

**Steps to reproduce the issue:**
1. Create a new Docker Machine
2. During machine creation, shown the following:
```
(test.local) Creating SSH key...
(test.local) Creating Parallels Desktop VM...
(test.local) Starting Parallels Desktop VM...
(test.local) Waiting for VM to come online...
(test.local) Shared folder 'Users' is unavailable. Skipping mount to VM...   <-- See Here
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
```

**Describe the results you received:**
If I ssh into the Docker Machine, the Mac's /Users folder has not been mounted. After my container is created by Docker Compose, I get an `Are you trying to mount a directory onto a file (or vice-versa)?` error when the container is started.

**Describe the results you expected:**
Files in the Mac's /Users folder should be available to the Docker Machine. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Using the Docker Parallels driver (installed by Brew). As a workaround, I can force an older version using the following: 

```
docker-machine create 
   --driver=parallels
   --parallels-boot2docker url=https://github.com/boot2docker/boot2docker/releases/download/v18.02.0-ce/boot2docker.iso
   test.local
```

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.33 (downgraded from 1.37)
 Go version:	go1.10
 Git commit:	0520e24
 Built:	unknown-buildtime
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.10.0-ce
  API version:	1.33 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	f4ffd25
  Built:	Tue Oct 17 19:05:23 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.89-boot2docker
Operating System: Boot2Docker 18.03.0-ce (TCL 8.2.1); HEAD : 404ee40 - Thu Mar 22 17:12:23 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.813GiB
Name: test.local
ID: B3V5:JXAB:VR37:X5NQ:UEYN:TBK7:ESNE:OFJA:MXRF:LOUW:AJ3Z:K7HV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=parallels
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* MacOS High Sierra 10.13.3
* Parallels Desktop 13.3.0 (43321)
* docker-machine version 0.14.0, build 89b8332
* docker-compose version 1.20.1, build unknown

**Comment by AkihiroSuda** [comment]
Please report to https://github.com/docker/machine
