### ISSUE TITLE
`integration` package is not ran on the windowsRS1 CI

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#36748]
A while back (after the cli split actually), the `integration` folder was created to create new integration test suites (based on `testing`, simpler, smaller and using only the API.

The different CI scripts were updated to take those into account **except the windows** one. We have to update the [windows CI scripts](https://github.com/jhowardmsft/docker-w2wCIScripts) to also run those.

cc @jhowardmsft @johnstep 

(on a side note, it would make it way easier if those were directly on this repository)

**Comment by jhowardmsft** [comment]
I started on this a little while ago - some of the tests don't actually work/weren't ported to Windows correctly. https://github.com/Microsoft/docker/tree/jjh/enable-integration. I'm not sure this is necessarily P1 though ;)

**Comment by vdemeester** [comment]
@jhowardmsft made it P1 to make sure we work on that next week — I can help with fixing the tests that don't run on the `windowsRS1` :wink:, it's just that the `powershell` in the CI (jenkins) is a bit obscure to me :angel:. If you have an update to that script that would enable that, I can duplicate the CI job to fix tests before using it on the PR job :angel:

**Comment by jhowardmsft** [comment]
I have a partial bit of it working in branch jjh/integration in the CI scripts repo. I can't recall exactly how far I got, but the first step was to rename integration to integrationcli. This all needs to be plumbed through in Invoke-DockerCI too. I unfortunately have no time to work on this for the next few weeks as I have some RS5 deliverables to focus on.

**Comment by vdemeester** [comment]
@jhowardmsft ok, fair enough, I'll dig into the repo next week and try to enhance my Powershell knowledge to help on that :wink:
