### ISSUE TITLE
New service type for swarm mode

### ISSUE THREAD

**Issue by softcombiz** [moby/moby#36757]
How about implement a new service type for swarm mode
type: failover
replicas: only one
and all options from "docker run" as --ip  --cap-add etc.
And if use macvlan + distributed file system such as ceph can be implemented failover migration for monolithic app for which the license is assigned to ip address.

**Comment by thaJeztah** [comment]
Not sure I fully understand what you're requesting; could you add more information what this service type would do? Perhaps some examples, and what you envision the UX to look like?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
