### ISSUE TITLE
Can wrong OS family error be identified to improve the error message?

### ISSUE THREAD

**Issue by kasper3** [moby/moby#36773]
On Windows, if docker is set to 'Windows container', and we try to run a Linux box, we get:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: open \\.\pipe\docker_engine_windows
: The system cannot find the file specified.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

Can the reason be identified and user is instead (or additionally) alerted with:

> Please right-click docker icon in system tray and click 'Switch to Linux container...' in context menu

This sounds very GUI-centric, right? So perhaps we can introduce a command like `docker switch <os-family>`, so the direction for user works for both GUI and headless (win server core) scenarios.

**Comment by AkihiroSuda** [comment]
+1, but could you suggest this to https://github.com/docker/for-win/issues ?

**Comment by AkihiroSuda** [comment]
or maybe https://github.com/docker/cli (cc @thaJeztah ^^)
