### ISSUE TITLE
Docker containers hang on close

### ISSUE THREAD

**Issue by connectedway** [moby/moby#36800]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

docker rm occasionally will fail to remove/kill a container and the container will be left in an unusable state.

This appears to have been reported before but all bug reports appear to have been closed without resolution.

We are using docker version 1.12.5

I have a simple docker container that users systemd as the init system.  Normally containers come up and shutdown fine and can be used for real work.  Occasionally, docker rm leaves the container in a odd state where the container cannot be killed, nor can it be re-run.  The entire Docker daemon needs to be restarted which is not a workaround for us.

**Steps to reproduce the issue:**
1. run a script:
for i in `seq 1 1000`;
do
    docker run -d --privileged --network=bridge --name=myname mycontainer
    sleep 1
    docker kill -s "SIGRTMIN+5" myname
    docker wait myname
    docker rm myname
done
2.  After around 50 iterations or less, the script will hang in the docker wait

**Describe the results you received:**

Upon analysis, all processes that had been part of the container appear to have been exited.  There do not appear to be any zombie processes or anything else running within the container's context

   CGroup: /
           ├─init.scope
           │ └─1 /sbin/init
           └─system.slice
             ├─systemd-timesyncd.service
             │ └─3016 /lib/systemd/systemd-timesyncd
             ├─dbus.service
             │ └─3036 /usr/bin/dbus-daemon --system --address=systemd: --n
ofork --nopidfile --systemd-activation
             ├─docker.service
             │ ├─3352 dockerd -H fd:// -g /var/lib/docker --registry-mirro
r=http://localhost:5000 --insecure-registry=http://localhost:5000 --raw-logs --b
ip=172.18.0.1/16
             │ └─5045 docker-containerd -l unix:///var/run/docker/libconta
inerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0
--start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtim
e docker-runc
             ├─slreset.service
             │ └─3079 /usr/bin/slreset**Describe the results you expected:**

You can see from above, there are no child processes of process 5045.  A "ps" command also proves this to be the case.  Yet:

root@myhost:~# docker ps
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
02e46d1a6b77        mycontainer   "/sbin/init"        21 hours ago        Up 21 hours                             myname

Shows it as running.  

A "docker kill myname" will provide:

# docker kill onecell-rpi0
onecell-rpi0

But a docker ps following this still shows it as running.

A "docker rm myname" will provide:
myhost:~# docker rm myname
Error response from daemon: You cannot remove a running container 02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032. Stop the container before attempting removal or use -f

A "docker rm -f myname" will provide:
root@myhost:~# docker rm -f myname
Error response from daemon: Unable to remove filesystem for 02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032: remove /var/lib/docker/containers/02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032/shm: device or resource busy**Additional information you deem important (e.g. issue happens only occasionally):**

Yet the "docker rm -f" appears to have removed the name because a subsequent docker ps -a will
show no containers.  Yet, there is still a container filesystem in:

root@ngrp-p1b-es2:~# ls /var/lib/docker/containers/
02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032

(ps, nothing else is running on this system).

So a subsequent attempt to run the container with the original name will fail:

root@myhost:~# docker run -d --privileged --network=bridge --name=myname mycontainer
04d01705d847722bea32e1b9dc836a490aa2a3de33dbfc682b5d2875db2b4f1a
docker: Error response from daemon: service endpoint with name myname already exists.

Thinking that maybe it's because there is a file in the filesystem that is still open, I did a search of all open file descriptors for all processes.  There are a number of json log files in the container directory (there are more of these):

l-wx------    1 root     root            64 Nov 28 16:09 19 -> /var/lib/docker/c
ontainers/02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032/02e46
d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032-json.log (deleted)
lrwx------    1 root     root            64 Nov 28 16:09 8 -> /var/lib/docker/vo
lumes/metadata.db
l-wx------    1 root     root            64 Nov 28 16:09 19 -> /var/lib/docker/c
ontainers/02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032/02e46
d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032-json.log (deleted)
lrwx------    1 root     root            64 Nov 28 16:09 8 -> /var/lib/docker/vo
lumes/metadata.db
l-wx------    1 root     root            64 Nov 28 16:09 19 -> /var/lib/docker/c
ontainers/02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032/02e46
d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032-json.log (deleted)
lrwx------    1 root     root            64 Nov 28 16:09 8 -> /var/lib/docker/vo
lumes/metadata.db
l-wx------    1 root     root            64 Nov 27 17:54 19 -> /var/lib/docker/c
ontainers/02e46d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032/02e46
d1a6b77be309d85b660ea1fdf120fa26c79bccb3963c9f5821502c5c032-json.log (deleted)
lrwx------    1 root     root            64 Nov 27 17:54 8 -> /var/lib/docker/vo
lumes/metadata.db /var/lib/docker/containers

So, now the question is, would the presence of these files cause the container to not get cleaned up and does anyone know why these files may exist and why are they marked (deleted) yet still exist?

Your help is appreciated.

**Output of `docker info`:**

```
root@ngrp-p1b-es2:/proc# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.5
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.9.0-xilinx-v2017.1
Operating System: Poky (Yocto Project Reference Distro) 2.2.2 (morty)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 975 MiB
Name: myhost
ID: EBRU:KTOP:E44R:Z6EP:4C7K:2P5H:OAS2:A24P:S7O7:SSHG:T2PJ:XKVY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 http://localhost:5000
 127.0.0.0/8```

**Comment by cpuguy83** [comment]
Can you please try on a recent version of Docker? 1.12 is very old and not support. There have been several fixes in logging around deadlocks, so please give it a go.

I'm going to close this because it's reported against 1.12, but feel free to discuss.
Thanks!
