### ISSUE TITLE
Questions about the GitHub issues.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [moby/moby#36807]
I wanted to ask a few things about the "issue" issues.

1- Please don't take this wrong. I appreciate all your hard work. However, most of the issues don't get much attention. I understand that this is a popular project and people open lots of issues. Most of these issues are being closed as spams, duplicates, questions, or redirections to other repos. You are spending time to look at these issues. The time spent here should be spent on the actual issues and/or development. How can this be improved? Dedicating a person from company for this job? Requesting help from the community to coordinate the issues?

2- The Windows side of the issues has some blackboxness as some bugs are caused by the platform. Communication for these bugs has to go through the Microsoft employees here and that doesn't work well. Surely, these employees are not postmen, they have their own work. So, how to improve communication with Microsoft for these issues?

3- There are quite a few spam issues with empty template content. Most of these seems like opened while the developer was executing a command. Titles look like the parts of the cmd or bash commands. Is this caused by a tool or an IDE of some sorts? How to prevent these issues? 

4- There are over 3000 open issues. Probably some are fixed, some are obsolete, and some are still valid. As this number is getting increased, it is getting harder to keep track of them. Again, can this be prevented with the help of the community? (There are open issues that are almost 5 years old.)

**Comment by sandersaares** [comment]
I would also like to just understand more how the Moby/Docker authors use this repository's issue list. What is its intended usage? How does its mission compare to various related repositories like Docker/for-X and microsoft/hcsshim and libcontainer and ...

I can attest to a lot of issues going ignored, yet at the same time some others get responses so I always hover between "I should report this" and "naah, it will just be ignored". Having more insight into what the authors of the software expect would be helpful.

**Comment by yusuf-gunaydin** [comment]
Looks like this is ignored, too. :disappointed:

**Comment by cpuguy83** [comment]
Also, I appreciate the feedback here. Please keep in mind it can easily take a week (or more) to get to a high priority bug... Assuming that an issue is ignored because it hasn't been commented on in a week is a bit over the top.

I saw this when it came in, as I know others did. I saw it again in my notifications on each comment.
It takes a non-insignificant amount of time to think about and write a response to an issue like this.

**Comment by cpuguy83** [comment]
If you have a big, please report it, bit do try and see if an issue is already open for it... I know this can be hard to do, and GH search sucks (Google often has better results for GH issues).

Also please make sure you are on a recent/supported version.
If you are using RedHat's fraken-Docker then it should probably be reported to RedHat as they are using a very old release and have a bunch of extra things that can (and do) cause things to go haywire (OCI hooks, plugins, etc).
