### ISSUE TITLE
More separation from docker please

### ISSUE THREAD

**Issue by gertcuykens** [moby/moby#36813]
The moby engine works really wel for me and has a clear separation of tasks
You have: 
- LAYER0 build run (Dockerfile)
- LAYER1 volumes networks secrets configs
- LAYER2 services (docker-compose.yml)
- LAYER3 swarm (deployment infrastructure)

I can also put it inline more or less with kubernetes where service can be looked as service pods, and swarm as kubelets. Makes me happy to have this clear component overview.

What doesn't make me happy is that docker-compose making it all very confusing, blurring and mixing up layers. It has its own `docker-compose images` separate from `docker images` that drives me insane. To make it worse their is this experimental `docker-compose bundle` thing that in my eyes is a step backward and confuses my brain constantly asking the question, but why?

Can we go all the way please and make sure docker-compose doesn't influence swarm development. That docker wants to have its own legacy composer fine. But I see docker-compose as something that needs to be surgically removed from the container eco system permanently

**Comment by cpuguy83** [comment]
docker compose and "docker stack" are not part of this project and are completely client driven features.
See https://github.com/docker/compose and https://github.com/docker/cli

Closing but feel free to discuss.

**Comment by gertcuykens** [comment]
Fair enough if you make sure the "docker clients" don't dictate the moby client features

https://github.com/moby/moby/tree/master/client
https://github.com/moby/moby/blob/master/client/service_create.go

I think we need a thin moby cli client repo then just to make sure the docker client doesn't hold back moby development.

Let docker deal with the enterprise folks, and make sure moby can focus on a collaborate open source container eco system. Right now the docker clients can potentially take moby hostage. You know perfectly well, noway docker compose isn't going to get dropped anytime soon because their are paying enterprise customers not going to be happy about it :P 

We need a separate moby client to clean up the compose mess.

**Comment by cpuguy83** [comment]
They don't dictate Moby features, that is a Moby client. A service in Moby is not the same thing as a sevice in compose.

**Comment by cpuguy83** [comment]
If you want a pure container runtime, see https://www.github.com/containerd/containerd

**Comment by gertcuykens** [comment]
hmm don't know enough about containerd but i have a feeling it going to be missing allot of Moby features and even harder to setup then Kubernetes

**Comment by cpuguy83** [comment]
@gertcuykens 

The moby client is the client which interacts with the moby API. It is very thin and does not do anything except help build an perform an HTTP request to the configured host.

The moby client is used by both the docker CLI, meanwhile docker compose uses a python library called docker-py.
The Docker CLI happens to take a compose file and convert that into API's provided swarm API's.
The compose format tends to add support for most of the relevant fields which are available on the API.

If you have a particular issue with docker-compose, which is a tool for local development, it should go in that repo.
Moby does not use or understand the compose format in any way.

**Comment by gertcuykens** [comment]
Ok you convinced me it's separated enough from the docker cli clients, thx. I will try to collaborate on the cli repo's if we really need the compose tool.
