### ISSUE TITLE
 hcsshim::PrepareLayer failed in Win32: The parameter is incorrect

### ISSUE THREAD

**Issue by mgolois** [moby/moby#36831]
Is this a bug or am I missing something?
When I run `docker-compose build` I get this error:

```
Building webapplication1
Step 1/17 : FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
 ---> 7f9d7dc1860e
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> dd80e4a90ee4
Step 3/17 : EXPOSE 80
 ---> Using cache
 ---> 61d4c528d49e
Step 4/17 : FROM microsoft/aspnetcore-build:2.0-nanoserver-sac2016 AS build
 ---> 1f96313b74e3
Step 5/17 : WORKDIR /src
ERROR: Service 'webapplication1' failed to build: hcsshim::PrepareLayer failed in Win32: The parameter is incorrect. (0x57) layerId=a96bac7ce3ed61f622fc7ec84113221af4ee9a24d792b8a0c7785c6b316c3512 flavour=1
```

docker version:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: false
```
docker info:
```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 18.03.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.2125.amd64fre.rs1_release.180301-2139)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.85GiB
Name: myComputerName
ID: JBIL:ZT3U:37LT:YMJA:5LDM:PGM7:L7PN:DDVF:HSDN:VI6S:TS72:A67K
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-04-11T10:56:44.0030666-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by ziilok** [comment]
I'm getting same issue when trying to build build tools by [microsoft docs ](https://docs.microsoft.com/ru-ru/visualstudio/install/build-tools-container?view=vs-2019)

**Comment by thaJeztah** [comment]
Did you configure the daemon to allow using a bigger size for the container's filesystems?

**Comment by ziilok** [comment]
Yes. I have configured deamon according tutorial:
```json
{
  "storage-opts": [
    "size=127G"
  ]
}
```
also i changed data-root.
```json
{
  "data-root": "E:/ProgramData/Docker"
}
```

In my case build process crashes after SHELL ["cmd", "/S", "/C"].

**Comment by ilnar20** [comment]
I had the same issue. It started to happen when I updated Windows 10 to 1903. And yes, deleting storage-opts in daemon configuration solved it

**Comment by ziilok** [comment]
@ilnar20 thank you! It's working now.

**Comment by antonkhelou** [comment]
After upgrading to 1903, I couldn't build anything. The only thing that fixed it was removing the `storage-ops`. Thanks!

**Comment by jbolduan** [comment]
> After upgrading to 1903, I couldn't build anything. The only thing that fixed it was removing the `storage-ops`. Thanks!

@antonkhelou what kind of operations are you doing in your dockerfile?  I'm curious why your image builds but mine fails even though I don't have storage-opts defined in my daemon.json file.

**Comment by thaJeztah** [comment]
For those running into this; if you have a custom storage location configured; could you try if things work if you disable Windows defender, or exclude the location? https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security

**Comment by Silvenga** [comment]
Same problem, just adding my setup to maybe help.

**Dockerfile**
```
# escape=`

FROM mcr.microsoft.com/dotnet/core/sdk AS netCore

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS final

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

USER ContainerAdministrator

## Install NetCore
COPY --from=netCore ["/Program Files/dotnet", "/Program Files/dotnet"]
RUN setx /M PATH "%PATH%;C:\Program Files\dotnet"
ENV DOTNET_RUNNING_IN_CONTAINER=true `
    DOTNET_USE_POLLING_FILE_WATCHER=true
RUN dotnet help

CMD ["powershell", "-Command", "Start-Sleep -Seconds 600;"]
```

**daemon.json**
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "storage-opts": [
    "size=120GB"
  ]
}
```

**Command**
```
docker build -f Dockerfile -t tag context\directory
```
**Output**
```
Sending build context to Docker daemon   2.56kB
Step 1/9 : FROM mcr.microsoft.com/dotnet/core/sdk AS netCore
 ---> 934c0f87cce6
Step 2/9 : FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS final
 ---> c4bed5a1e5d5
Step 3/9 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in e4b4e38ebd78
hcsshim::PrepareLayer failed in Win32: The parameter is incorrect. (0x57) path=C:\ProgramData\Docker\windowsfilter\e4b4e38ebd782cb01a3c145086d35e100b4471106aab11b8631da1f768ea7e59
```

Windows Defender is excluded from the docker directory.

**Comment by thaJeztah** [comment]
Thank you! So looks like the "size" storage driver option is broken in Windows 1903, or do other storage options trigger the problem as well?

I'm not on Windows myself, but can start looking for changes in the hcsshim codebase that might give some clues

**Comment by antonkhelou** [comment]
@jbolduan  pretty basic stuff. even something like `RUN mkdir ...` wouldn't work.

@Silvenga remove the `storage_opts` from your `daemon.json` and try again.

**Comment by Silvenga** [comment]
@antonkhelou yep, that's what I've had to do. Unfortunately, some of my images can get larger than the default size. I'll just have to use 1809 server to handle that.

@thaJeztah it looks like `size` is the only option supported with Windows containers. I could try windows `lcow` options, but I would need to get setup on my dev machine.

**Comment by jbolduan** [comment]
Here's my setup as well in case there's something that might help identify the root cause.

**DockerFile**
```
ARG TAG=ltsc2016
FROM mcr.microsoft.com/windows/servercore:$TAG

WORKDIR /pester

ADD . /pester

CMD powershell.exe .\Build\build.ps1

```

**daemon.json**
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false
}
```

**dockerbuild.ps1** (Script used to execute docker build commands)
```
docker build -t umn-activedirectory .

docker run umn-activedirectory
```

**Console Output from docker build command**
```
Sending build context to Docker daemon  783.4kB
Step 1/5 : ARG TAG=ltsc2016
Step 2/5 : FROM mcr.microsoft.com/windows/servercore:$TAG
 ---> 5df67de47444
Step 3/5 : WORKDIR /pester
 ---> Running in 43014a0cadd1
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)
```

**Comment by madhana-arumugam** [comment]
@thaJeztah Did you manage to find anything?
I am hit with the same issue, i.e. you can't change the base image size either through daemon.json or using the docker run --storage-opt size=30G using the server core image 1903.

**Comment by isanych** [comment]
For containers which need more space than available by default I'm mapping directory from host into container and use this directory for big stuff - not the best workaround, but it helps me to wait for docker 19.03 release which is hopefully will happen any day now.

**Comment by tehho** [comment]
Docker 19.03.0 is now out but I still get the same error.

Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /image/
```

Powershell to update storage-opt to >20G disk size.
```
net stop docker
./dockerd.exe --unregistrer-service
./dockerd.exe --register-service --storage-opt size=22G
net start docker
docker build .
```
This gives error: 
```
hcsshim::PrepareLayer - failed failed in Win32: The parameter is incorrect. (0x57).
```
But a docker run -it --rm docker-test powershell -c "Get-PSDrive" gives:
```
Name           Used (GB)     Free (GB) Provider      Root                                                                                                    CurrentLocation

----           ---------     --------- --------      ----                                                                                                    --------------- 
Alias                                  Alias
C                   0.15         21.73 FileSystem    C:\                                                                                                               image

Cert                                   Certificate   \
Env                                    Environment
Function                               Function
HKCU                                   Registry      HKEY_CURRENT_USER
HKLM                                   Registry      HKEY_LOCAL_MACHINE
Variable                               Variable
WSMan                                  WSMan
```

Seems that docker build does not listen to storage-opt or some other setting needs to be placed. 

Anyone have a suggestion?

**Comment by beowulfdk** [comment]
@tehho 

I have Server Version: 19.03.0-rc2 installed and just removed the storage-opts from the daemon.json. 
Since then everything seems to run fine

**Comment by tehho** [comment]
@beowulfdk 
Yes i get it working without storage-opts aswell, but i need more disk since vs2019 install takes about 40 GB :(
Trying to build a build agent for azure devops using aks as hostware but right now vs2019 is the blocking component for finishing.

**Comment by vonders** [comment]
I had to create it initially as a base (blank) dockerfile with the storage-opts and then remove the storage-opts to progress with the actual commands needed

**Comment by galeone** [comment]
Are there any updates on this?

I'm currently using Windows 10 - 1903 in the host, and I must create a windows container with a storage size of about 200GB (needed to contain a game engine). So I have my docker (version 19.03.2) configuration configured as:

```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "graph": "D:\\ProgramData\\Docker",
  "storage-opts": [
    "size=200G"
  ]
}
```

Of course, when I try to build the image, I got the error

```
csshim::PrepareLayer - failed failed in Win32: The parameter is incorrect. (0x57)
```

I cannot use the workaround of removing the "storage-opts" line since I do really need 200GB (I tried, but while building the image it goes out of space and the build fails).

What should I do?

**Comment by scyto** [comment]
I was trying to run a docker build for a windows container containing only an EXPOSE command - it failed, seems the first dockerfile directive fails no matter what it is.

Uninstalling stable 2.1.4.0 and installing 2.1.4.0 edge fixed the issue (switching to edge was not possible via the UI).

I am on windows insider Build 19002.vb_releases.191919-1436

**Comment by scyto** [comment]
i found it seems there was this crappy driver installed, disabling 'StorLib bus (virtual storages support)' hidden device in device manager fixed it.
https://github.com/Stannieman/audacity-with-asio-builder/issues/5

**Comment by Abassina** [comment]
Still having the same issue. I do need more than 20 GB storage. Can anyone help?

**Comment by Abassina** [comment]
> Still having the same issue. I do need more than 20 GB storage. Can anyone help?

I could solve this Problem. See this workaround to solve it too: https://forums.docker.com/t/manage-host-disk-volume-size/37438

**Comment by Silvenga** [comment]
@Abassina 

> I could solve this Problem. See this workaround to solve it too: https://forums.docker.com/t/manage-host-disk-volume-size/37438

That workaround looks to be for Linux containers running on Windows, this issue is about Windows containers, which use a different isolation technology. Resizing MobyLinux won't help here.

**Comment by heaths** [comment]
With the latest update to Docker 19.03.5 the following worked for me (`dir` reported ~120GB drive):
```
docker run -it --rm --storage-opt "size=120GB" mcr.microsoft.com/windows/servercore:ltsc2019
```

**Comment by vient** [comment]
Experiencing the same error on latest Windows Server 1909 (18363.592) and latest Docker Desktop Stable 2.1.0.5 (40693).

Command `docker build .` fails on the second step from Dockerfile, whatever it is. Error message is `hcsshim::PrepareLayer - failed failed in Win32: The parameter is incorrect. (0x57)`

Steps to reproduce: I installed clean Windows Server 1909, updated it, disabled Defender, uninstalled OneDrive, then installed Docker and tried to build an image.

I want to note that starting a Hyper-V container does not work either — it throws an error "The virtual machine or container exited unexpectedly. (0xc0370106).`

What I also want to note is that previously I got it working somehow on the same machine... but I can't reproduce it after OS reinstall.

**Comment by lionelquirynen** [comment]
Having the same issue with custom storage options and running docker compose, if I remove the storage opt, I get this error  failed to build: hcsshim::PrepareLayer - failed failed in Win32: The system cannot find the path specified. (0x3), anyone would have an idea how to solve this?

**Comment by noemu** [comment]
Same Bug: Docker Engine v19.03.5 , Docker Desktop 2.2, Windows 10 1909 (18363.592)

I need the storage-opts to install visual studio (27GB)

It happens in the last image build step

**Comment by thaJeztah** [comment]
the fix for this will be in docker engine 19.03.6, which hasn't been released yet (but will be soon); after that's released, it will be included in a future release of Docker Desktop for Windows

**Comment by djarvis** [comment]
Just to chime in, I was trying to deploy a swarm of windows containers on my desktop here and it kept failing and recreating the containers ad infinitum.  A docker stack ps showed

```
starting container failed: hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)
```

This only happened when I defined and consumed secrets in my YAML file.  When I removed those it worked OK.  

But I finally remembered this thread and figured it was of the same nature, and I did have OneDrive installed and running.  When I removed that, it start working with the secrets.

**Comment by isanych** [comment]
19.03.6 was released 18 days ago on github, soon after that it was released for linux, but it still nothing for windows :(

**Comment by thaJeztah** [comment]
There were issues with the containerd version included in 19.03.6, so changed had to be partially reverted. 19.03.7 is being worked on, after which a new version can be included in a release of Docker Desktop for Windows.

**Comment by isanych** [comment]
The same question about 19.03.7 - linux version updated, but neither https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json nor https://download.docker.com/components/engine/windows-server/index.json have it, 19.03.5 is latest in both DockerMsftProvider and DockerProvider.

**Comment by ebalders** [comment]
@thaJeztah Is there an ETA on 19.03.7 for Windows? As @isanych mentioned, there is nothing on those package feeds yet, or on the release notes page: https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by thaJeztah** [comment]
Not sure when the next release for Docker Desktop is scheduled

**Comment by isanych** [comment]
I'm still not able to specify size on windows 2004 with docker 19.03.8
```
docker run --rm mcr.microsoft.com/windows/nanoserver:1909 cmd /c dir
docker: Error response from daemon: container 57d0f371782d386023dd7b36a78e21969023544be69abd65485dc1bd2cbbc22b encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).
```

**Comment by TBBle** [comment]
@isanych That's probably a different issue, it's reporting a different error code.

First guess is that it's because you're running a 19.09 container on a 2004 host. Try

```raw
docker run --rm mcr.microsoft.com/windows/nanoserver:2004 cmd /c dir
```

and if that works, then it's unrelated to this one.

If that fails, and taking `storage-opts` out of your Docker daemon configuration doesn't fix it, then it's not this issue either, and you'll be better-off opening a new bug report, since this issue is currently marked as resolved.
