### ISSUE TITLE
Can't find night builds.

### ISSUE THREAD

**Issue by vitaliy-leschenko** [moby/moby#36836]
**Description**
https://master.dockerproject.com/ have no new builds starts from 2018-03-20.

**Steps to reproduce the issue:**
1. Open https://master.dockerproject.com/
2. Looking for new builds..

**Describe the results you received:**
No new builds.

**Describe the results you expected:**
Have new builds.

**Comment by cpuguy83** [comment]
Thanks, I'm not sure if stopping the nightly build at that location was intentional. I'll check.
There are now nightly built packages, though.

```
curl -fsSL http://get.docker.com | CHANNEL=nightly sh
```

**Comment by cpuguy83** [comment]
Looks like the build is just failing. The docker release team is looking at it.
Thanks!

**Comment by seemethere** [comment]
@vitaliy-leschenko Looks like there's a bug in the packaging script for master.dockerproject.org, I'll look into it but the preferred way of installing nightly builds is now with `get.docker.com` as @cpuguy83 has already highlighted.

If you're in need of static binaries you can get them at:

https://download.docker.com/linux/static/nightly/

**Comment by seemethere** [comment]
Should be fixed now :+1:

**Comment by cpuguy83** [comment]
Thanks!

**Comment by vitaliy-leschenko** [comment]
Thanks
