### ISSUE TITLE
No Service Events in Production Swarm

### ISSUE THREAD

**Issue by michaelkrog** [moby/moby#36834]
**Description**
I am trying to listen for service events(create, update, delete) in the swarm

**Steps to reproduce the issue:**
1. Run `docker event --filter "scope=swarm"` in one console
2. Run `docker service create --name hello hello-world` in another console

**Describe the results you received:**
I receive no events when doing this in our production cluster with 3 master and 2 workers, no matter which node I check for events on.

```
$ docker events --filter "scope=swarm"
(No output)
```

On my develop machine(a 1 node swarm) I do however get the events I expect:
```
$ docker events --filter "scope=swarm"
2018-04-12T09:37:03.983138118+02:00 service create b3yjvhe1v6bxzsxumd8ia43fh (name=hello)
2018-04-12T09:37:24.811839478+02:00 service remove b3yjvhe1v6bxzsxumd8ia43fh (name=hello)
```

**Describe the results you expected:**
I expected events about the service to be received.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happens in our production environment.

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 899
 Running: 12
 Paused: 0
 Stopped: 887
Images: 280
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2409
 Dirperm1 Supported: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: fia8k180v3zlerr6zct851eh2
 Is Manager: true
 ClusterID: x07pr4f5kqlp63w7iq8ongvsn
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.201.0.11
 Manager Addresses:
  10.201.0.11:2377
  10.201.0.12:2377
  10.201.0.13:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: engine01.codezoo.dk
ID: SIRC:Z5VT:MSC5:UVOO:QWD5:RAHK:U3P2:HNXM:EM7Z:THIN:SC2R:5LUO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 in VMWare.

**Comment by michaelkrog** [comment]
Related to #36797

**Comment by cpuguy83** [comment]
@michaelkrog Can you get a goroutine stack dump by chance?

```
curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2
```

Probably needs to be done on the leader.

**Comment by michaelkrog** [comment]
Yes of course.

Created a [gist here](https://gist.github.com/michaelkrog/d6371167d32949bc50a6f00a8e6c5c4b)

**Comment by michaelkrog** [comment]
I just upgraded all aster and slaves to 18.03.1 and that brought back events.

(I also did when I tried downgrading to 17.12, but only for a few days)

**Comment by vce-xx** [comment]
Hello @michaelkrog 
I am having the same issue with Docker for AWS stable in 18.03.0. And this issue showed up on previous releases too : ["docker events" not showing service events #101](https://github.com/docker/for-linux/issues/101)  with 17.07
You said that downgrading to 17.12 brought back the service events but only for a few days.
How is it going after a few weeks having upgraded to 18.03.1 ? Do you consider 18.03.1 has a stable correction ?

**Comment by Mohitsharma44** [comment]
@michaelkrog You got success by just upgrading the docker server to v18.03.01-ce? I'm running the same version for quite some time on the manager and all the nodes. My use case now requires me to monitor some events being fired from a swarm node but I cannot seem to find them in `docker events` run on the manager.
I thought I should begin asking by you since you have had success.

### Swarm Manager:
*docker version*
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

### Swarm Node 1 (same for all)
*docker version*
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

> I do have experimental set to true since Im scraping the information for a prometheus monitoring server

**Comment by Mohitsharma44** [comment]
Yikes! Looks like the events were getting triggered but **not** for services that get rebalanced in case the worker node goes down (my interest). It only gets triggered when a service is updated, *force*fully. 
I couldn't find an issue elswhere about this. Maybe it needs a bug report of its own.
