### ISSUE TITLE
Issues with execve blocking in seccomp profile 

### ISSUE THREAD

**Issue by dstiliadis** [moby/moby#36830]
**Description**
When creating a custom seccomp profile with execve blocked, the daemon never returns (hangs) after attempting to start the container, and the blocked container cannot be removed. In versions before 1.8.03.0-ce the docker ps command would also hang after that. Not sure if other APIs are affected as well. 

**Steps to reproduce the issue:**
1. Create a custom seccomp profile in a file 
```
{
   "defaultAction":"SCMP_ACT_ALLOW",
   "syscalls":[
      {
         "names":[
            "execve"
         ],
         "action":"SCMP_ACT_KILL",
         "args":[

         ],
         "comment":"",
         "includes":{

         },
         "excludes":{
         }
      }
   ]
}
```
2. Start a  container using this profile: 
```
docker run --security-opt seccomp=/home/ubuntu/file -d nginx
```

**Describe the results you received:**

At this point, the docker command will never return.

In 1.17, docker ps will also hang. In 1.18 docker ps will not hang, however removing/stopping
the container will hang.  

At this point there is no way to kill the container other than killing the docker-runc command manually or restarting the docker daemon. 

**Describe the results you expected:**
Ideally the execve blocking should start after the container is started since it is supposed
to apply to the processes after that. I suspect that this might not be possible. In this case, the 
API should block such an action and provide an error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953GiB
Name: 
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by neersighted** [comment]
This is currently by design of [`seccomp(2)`](https://man7.org/linux/man-pages/man2/seccomp.2.html); the thing that spawns your process must install the filter program on itself, and must allow `execve(2)` so that children in the process tree inherit the profile.

If you block `execve(2)`, not only can the child process (your entrypoint) not be started, but the seccomp profile could not be inherited, even if the entrypoint could somehow be invoked.

---

If you want to be more restrictive with regard to what syscalls are allowed (e.g. no `execve(2)`) inside the container (just like you would without containers), you should invoke `seccomp(2)` yourself, instead of trying to control things from the container runtime level.
