### ISSUE TITLE
Unhelpful Errors when in the wrong "mode"

### ISSUE THREAD

**Issue by jasonbivins** [moby/moby#36857]
Expected behavior
If I'm in Windows container mode, and I pull a Linux container - it should tell me that I need to switch modes
The same if I'm in Linux mode and run a windows container

Actual behavior
If I try to run a Linux container in Windows mode - it gives me a Manifest error that doesn't really help or explain the problem
`C:\Users\DockerJ>docker run -it alpine Unable to find image 'alpine:latest' locally latest: Pulling from library/alpine docker: no matching manifest for windows/amd64 in the manifest list entries. See 'docker run --help'.`

If I try to run Windows containers in Linux mode it tells me what the actual problem is, but this could be made clearer
`C:\Users\DockerJ>docker run -it microsoft/nanoserver Unable to find image 'microsoft/nanoserver:latest' locally latest: Pulling from microsoft/nanoserver bce2fbc256ea: Pulling fs layer 83eec61707e8: Downloading docker: image operating system "windows" cannot be used on this platform. See 'docker run --help'.
`
Information
reported on For-Win
docker/for-win#1911

**Comment by jasonbivins** [comment]
https://github.com/docker/for-win/issues/1949

**Comment by kasper3** [comment]
@jasonbivins thanks! It was originally reported at https://github.com/moby/moby/issues/36773.
@jhowardmsft, @thaJeztah, is this something that can be caught by docker runtime and user gets some sane error message?

**Comment by thaJeztah** [comment]
"Friendly error message" is generated here; and _seems_ to take into account both Windows on Linux and Linux on Windows; https://github.com/moby/moby/blob/3e1505e3e671d35636f7818dc1f41e4a4d429620/distribution/config.go#L159-L165

Possibly that function is not reached, and the error occurs before that

Is this on LCOW, or "Linux" (Moby VM)

**Comment by jhowardmsft** [comment]
This will be much better when https://github.com/moby/moby/pull/36418 gets merged

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
