### ISSUE TITLE
upgrade compose 1  to 3

### ISSUE THREAD

**Issue by lagaree** [moby/moby#36870]
help me to convert from ver 1 to 3 
#######################################
fingerboard:
  image: xivoxc/fingerboard:${XIVOCC_TAG}.${XIVOCC_DIST}

  restart: always
kibana_volumes:
  image: xivoxc/kibana_volume:latest

  restart: always
nginx:
  image: xivoxc/xivoxc_nginx:${XIVOCC_TAG}.${XIVOCC_DIST}

  ports:
  - 80:80
  - 443:443
  - 8443:8443

  links:
  - elasticsearch
  - xuc
  - xucmgt

  extra_hosts:
  - "xivo_host:${XIVO_HOST}"

  volumes_from:
  - kibana_volumes
  - fingerboard

  volumes:
  - /etc/docker/nginx/ssl:/etc/nginx/ssl

  restart: always

**Comment by cpuguy83** [comment]
@lagaree Please ask questions like this in the various help forums.
There's the community slack, #docker on freenode IRC, and forums.docker.com

Thanks!
