### ISSUE TITLE
how to manage my swarm cluster? i wana to make some update in my apache package in my swam cluser

### ISSUE THREAD

**Issue by linuxmishra** [moby/moby#36899]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Closing as this is not an issue and the question is not well defined enough to even give an answer here.

Please ask questions on one of the community forums, such as the community slack, #docker on freenode, or forums.docker.com.
Thanks!
