### ISSUE TITLE
Broken Pipe errors are seen when an in use log driver plugin get killed

### ISSUE THREAD

**Issue by fivesheep** [moby/moby#36929]
**Description**

Ideally, when a logdriver plugin get killed for some reason, oom for example, the stdout/stderr stream of a container which uses the plugin shall be blocked until the logdriver plugin gets recovered, or just fail fast. However, this is not the behavior of the current logdriver plugin implementation, when a logdriver plugin crashed, if any container is streaming logs to this plugin,  the container will keep running without blocking, 'Broken pipe' errors can be seen from docker engine logs which indicates there's unexpected data loss.  

**Steps to reproduce the issue:**
1. Set up a docker logdriver plugin to use, with the following script
```
#!/bin/sh
git clone git@github.com:cpuguy83/docker-log-driver-test.git
cd docker-log-driver-test
# fix the broken dependency by removing two lines of code
sed -i '/msg.Partial/d' driver.go
docker build -f Dockerfile.build . -t test-log-driver
docker run --name tmp test-log-driver:latest
mkdir -p plugin/rootfs
cp config.json plugin
docker export tmp | tar x -C plugin/rootfs
docker plugin create test-driver ./plugin
docker plugin set test-driver:latest LOG_LEVEL=debug
docker plugin enable test-driver:latest
```
2. Start a docker container with this logdriver
```
docker run  --name test-log-driver --rm --log-driver test-driver:latest alpine /bin/sh -c 'for i in `seq 1 10000`; do echo "log item $i"; sleep 1; done'
```
3. On a different terminal, identify the process id of the logdriver application on the host
```
> ps aux  | grep docker-log-driver
# some thing like below can be seen
root     25588  0.0  0.0 283988 11144 ?        Ssl  Apr13   0:01 /usr/bin/docker-log-driver
```
then kill this process with SIGKILL. 

**Describe the results you received:**
Open journalctl to check logs
```
 journalctl -f
```
error message with Broken Pipe like the following can be seen
```
Apr 13 04:23:27 hostname dockerd[1247]: time="2018-04-13T04:23:27.602363175-07:00" level=error msg="Failed to log msg \"\" for logger test-driver:latest: write /proc/self/fd/40: broken pipe"
Apr 13 04:23:27 hostname dockerd[1247]: time="2018-04-13T04:23:27.604785825-07:00" level=error msg="Failed to log msg \"\" for logger test-driver:latest: write /proc/self/fd/40: broken pipe"
Apr 13 04:23:27 hostname dockerd[1247]: time="2018-04-13T04:23:27.607369644-07:00" level=error msg="Failed to log msg \"\" for logger test-driver:latest: write /proc/self/fd/40: broken pipe"
```

And the container is still running

**Describe the results you expected:**
Shall not see broken pipe errors from docker-engine side.  Since this is a toy log driver plugin, it did not have any recovery functionality. In this case container logs shall be just blocked which behaviors like downstream is down.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 8
 Running: 2
 Paused: 0
 Stopped: 6
Images: 53
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 233
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.59GiB
Name: poincare
ID: BAWE:EBZ7:W5PE:KYAZ:7APE:VEOC:QOYO:GS37:D75R:NVTD:2D22:KCTE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: fivesheep
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Potential solution**

When open a fifo for write from [plugin.go](https://github.com/moby/moby/blob/53683bd8326b988977650337ee43b281d2830076/daemon/logger/plugin.go#L72),  it shall also open the same fifo in read mode at the same time. I was able to simulate this behavior by using an external python script to open the pipe in read mode but not reading any data, and this additional dummy reader won't cause any issue to the actual reader. The same solution can be seen in [containerd](https://github.com/containerd/containerd/blob/209a7fc3e4a32ef71a8c7b50c68fc8398415badf/linux/proc/io.go#L86-L110)

**Comment by cpuguy83** [comment]
Opened https://github.com/moby/moby/pull/37028
