### ISSUE TITLE
does docker events reliable?

### ISSUE THREAD

**Issue by better0332** [moby/moby#36928]
does docker events reliable or may drop some events? I use docker events API(`func (cli *Client) Events(ctx context.Context, options types.EventsOptions) (<-chan events.Message, <-chan error)`) to get stream, but consume event a little slow.

**Comment by bsousaa** [comment]
There is a chance events are dropped in case you don't drain/consume them. We may improve [documentation](https://docs.docker.com/engine/reference/commandline/events/#description) to be more clear about that.
