### ISSUE TITLE
Bump bundled tini version to 0.18.0

### ISSUE THREAD

**Issue by Yajo** [moby/moby#36943]
**Update to tini 0.18.0**

tini 0.18.0 includes a fix for https://github.com/krallin/tini/issues/100, which is quite important in terms of management, since it means you basically don't need to include an init anymore in most cases.

It'd be great if it is included in the next docker release.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:27:27 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:31:15 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 29
 Running: 6
 Paused: 0
 Stopped: 23
Images: 407
Server Version: 18.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.15.17-300.fc27.x86_64
Operating System: Fedora 27 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.63GiB
Name: yajolap.yajodomain
ID: KUBN:F7JL:URX6:HO55:R3L2:SCUU:IWVY:EZ2O:F53G:WHTO:3G4D:R4YU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, fedora.

**Comment by thaJeztah** [comment]
Updating to a current version sounds ok to me

> since it means you basically don't need to include an init anymore in most cases.

Not sure I fully grasp that comment: you'd still need `--init`; do you mean: no init inside the container itself (in addition to / instead of the bundled `tini`)?


Reading https://github.com/krallin/tini/pull/16; should the `-g` option be set by default, or would that cause issues in situation where the immediate child would properly deal with reaping its children?

**Comment by thaJeztah** [comment]
Opened a PR: https://github.com/moby/moby/pull/36946
