### ISSUE TITLE
There is a political mistake.

### ISSUE THREAD

**Issue by magic-chenyang** [moby/moby#36957]
When I visit this website https://events.docker.com/chapters/, I found that Hong Kong and Taiwan nationality is not of Chinese nationality, I hope that officials can lay emphasis on this problem, I as docker technology of heavy users, some suggestion to you.

**Comment by thaJeztah** [comment]
ping @vcoisne who manages that site?

**Comment by thaJeztah** [comment]
Let me close the issue here, because that website is not managed in this repository, but I forwarded the question internally. Thanks for reporting; also feel free to continue the conversation after I closed
