### ISSUE TITLE
SIZE column in docker ls has inconsistent formating.

### ISSUE THREAD

**Issue by joeyhub** [moby/moby#36976]
I have one images that's quite close to a GB and it shows: 1e+03MB

All of the other images are alright it's just one that shows like this.

**Comment by thaJeztah** [comment]
Can you  provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`

**Comment by thaJeztah** [comment]
Closing because no information was added, but happy to reopen once it's there
