### ISSUE TITLE
macvlan device node is not created on host by docker command

### ISSUE THREAD

**Issue by 3ronco** [moby/moby#36972]
Using:
`docker network create -d bridge ...` results in a routable device node created on the host like eg: _docker0_, _docker1_, ...

When trying the same thing with the `-d macvlan` driver arg specified, no device node is created at all although the network is listed when using `docker network ls`

When using `docker network create ...` i would expect the same result regardless of the driver used. Instead you can go around by creating the _macvlan_ device node manually eg. using `ip` or a definition in `/etc/network/interfaces` which can be quite buggy as the subnet, gateway, ... args specified need to match on both ends.
I don't know if there's a reason in the different behavior but even if so it would be nice to give a hint to the user as the current scheme is really confusing. I've spent a lot of time trying to create a _macvlan_ with `docker network create ...` and was wondering why it's not listed using `ip link`.

I've tried the same operation on two independent docker installs on different hosts. The effect is the same.

Docker version 18.03.1-ce, build 9ee9f40
Debian Linux 4.15.0-3-amd64 x86_64

**Comment by thaJeztah** [comment]
ping @mavenugo @fcrisciani PTAL

**Comment by cpuguy83** [comment]
For macvlan there is no device to create. Macvlan uses the specified, already existing interface.

**Comment by 3ronco** [comment]
Indeed it uses an existing interface like a physical nic added to a bridge 
and like a bridge it uses a new device node (eg: macvlan0@eth0)
Please read some of the basics about macvlan devices before posting.

**Comment by cpuguy83** [comment]
@3ronco 

Interfaces are created at runtime and are bound to the specified host interface. There is no need to have an additional interface in the host namespace. Example using iproute2:


```bash
ip netns add test
ip link add macvlan0 link ens3 type macvlan mode bridge
ip link set macvlan0 netns test
```

At that point, the interface in the netns `test` needs to be configured with an IP address, but it is bound to `ens3`
You will not be able to ping the macvlan0 interface from the host namespace, but it will be accessible to others on the network, including if you make yet another interface in another netns.

**Comment by 3ronco** [comment]
Ok, that's the way to do it manually. Now when you add a macvlan device it appears in your link list:

```
me@host:~/# ip link add macvlan0 link ens3 type macvlan mode bridge
me@host:~/# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: macvlan0@ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
```

The question is why isn't this created when i use:

`docker network create -d macvlan macvlan0`

It's even listed:
```
me@host:~/# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
xxxxxxxxxxxx        bridge              bridge              local
xxxxxxxxxxxx        host                host                local
xxxxxxxxxxxx        macvlan0            macvlan             local
xxxxxxxxxxxx        none                null                local
```

Now i have a network config created in docker without the corresponding interface which needs to be created manually?

On the other hand when i create an 'ordinary' bridge:

```
me@host:~/# docker network create -d bridge docker1
me@host:~/# ip a
[...]
5: br-51efd0426373: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-51efd0426373
       valid_lft forever preferred_lft forever
```
even with IPs and a route preconfigured. I agree that's not necessarily needed for a macvlan interface but nevertheless possible.

By the way (offtopic)
It would be nice if the bridge name used when creating a new network would relate to the interface name.
Calling a network _docker*_ and getting a bridge device called _br-xxxxxxxxxxxx_ gets inconvenient when using multiple bridges as you don't know which bridge device relates to which network name and using:

`me@host:~/# docker network create dockerX -o com.docker.network.bridge.name=dockerX`

is somehow unhandy.

**Comment by cpuguy83** [comment]
https://docs.docker.com/network/macvlan/

This explains what is happening. Macvlans must bind to a real interface.
You can specify a sub-interface to use as well.

With bridge networks you are creating a whole new network. With macvlans
you are attaching to an exidting, real network.

**Comment by 3ronco** [comment]
Pinning it on the term _network_ makes things easy :-)
But no, a macvlan device sitting on a physical interface can be a single endpoint but doesn't have to be, it can be used as a bridge too. I've used another page with similar infos on https://docs.docker.com/network/network-tutorial-macvlan which clearly says:

> Goal
> 
> The goal of these tutorials is to set up a **bridged macvlan network** and attach a container to it, ...

Now please, try the tutorial described there in a VM and tell me that it works.

By the way, the chapter called *Bridge example* is faulty:

> You can use docker network ls and docker network inspect *pub_net* commands to verify that the network exists and is a macvlan network.

pub_net == my-macvlan-net?

**Comment by cpuguy83** [comment]
The "bridged" part is specifically this section: https://docs.docker.com/network/network-tutorial-macvlan/#8021q-trunked-bridge-example

This still needs to bind to a real interface, however it does create the bridge interface on the host in the form that you specifed it...
e.g. `--opt parent=eth0.10` will bridge eth0 and you will get a new interface on the host called `eth0.10`.

**Comment by 3ronco** [comment]
No, it's two examples of different scenarios using a macvlan bridge. Anyway, thanks for your efforts.
