### ISSUE TITLE
LCOW: No terminal for older linux distros on docker for windows

### ISSUE THREAD

**Issue by isanych** [moby/moby#36984]
**Description**

Bash scripts are not working in centos 5 & 6 on docker for windows in windows containers mode, the same commands work fine in centos 7. Simplified sample (there is no output of bash -c "echo 1" in centos 6):
```
>docker run --rm --platform=linux centos:6 echo 1
1
>docker run --rm --platform=linux centos:6 bash -c "echo 1"
>docker run --rm --platform=linux -ti centos:6 bash -c "echo 1"
>docker run --rm --platform=linux centos:7 echo 1
1
>docker run --rm --platform=linux centos:7 bash -c "echo 1"
1
```
The same commands working fine in docker for windows linux containers mode and docker for linux.

**Steps to reproduce the issue:**
Run any bash script or try to run bash interactively in centos 6 on docker for windows

**Describe the results you received:**
bash scripts and not executed silently, no output from bash commands

**Describe the results you expected:**
bash scripts are executed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 18.03.1-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows: 
 LCOW: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17650 (17650.1001.amd64fre.rs_prerelease.180414-2140)
Operating System: Windows Server Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.89GiB
Name: igor
ID: 55ZS:67O5:56QT:IRZD:X35D:AIC5:6RH5:ERKK:NARX:L6OU:COI7:PQ3N
Docker Root Dir: E:\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 d.a
 docker-proxy.a
 docker.a
 127.0.0.0/8
Registry Mirrors:
 http://docker-proxy.a/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Windows Server 2019 Insider

**Comment by isanych** [comment]
The same result on latest edge build:
```
> docker version
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:57:53 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:07:01 2018
  OS/Arch:      windows/amd64
  Experimental: true

> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 18.05.0-ce-rc1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17650 (17650.1001.amd64fre.rs_prerelease.180414-2140)
Operating System: Windows Server Standard Version 1803 (OS Build 17650.1001)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.89GiB
Name: igor
ID: 55ZS:67O5:56QT:IRZD:X35D:AIC5:6RH5:ERKK:NARX:L6OU:COI7:PQ3N
Docker Root Dir: E:\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 d.a
 docker-proxy.a
 docker.a
 127.0.0.0/8
Registry Mirrors:
 http://docker-proxy.a/
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Wondering if this could be related to https://github.com/docker/for-linux/issues/58 / https://github.com/moby/moby/issues/34301 (`vsyscall=emulate` configuration in the kernel)

Note that LCOW (Linux Containers on Windows) is still an experimental feature, and not feature complete; there are still many things not yet implemented (both in Docker, and in Windows) 


ping @jhowardmsft PTAL

**Comment by joostmeijles** [comment]
Since update to 2.0.0.0-win81 (29211) interactive tty is no longer working (it was working fine before) me.

Is that same issue?

**Comment by thaJeztah** [comment]
@joostmeijles on any base image or only old distro versions (the `centos:6` image mentioned)?

Also;

- are you only seeing this on Linux images or Windows images as well?
- only when using experimental LCOW, or also when using the default (non-LCOW) linux runtime?

**Comment by joostmeijles** [comment]
With LCOW:
- older does not work: `docker run --rm -it --platform=linux centos:6 bash`
- newer does work: `docker run --rm -it --platform=linux centos:7 bash`

With Linux Containers mode (using Docker for Windows) both work fine.

**Comment by thaJeztah** [comment]
Looks like the same issue then, yes. FWIW, the "LCOW" feature will likely get a major overhaul, with the Windows runtime being rewritten in the containerd project. LCOW is still experimental, and there are still (quite some) corner-cases that may not work, or have not (yet) been fully implemented.

**Comment by thaJeztah** [comment]
> What is the timeline for the major overhaul?

Don't have a timeline for this (perhaps @jhowardmsft has more information on that); first step would be to make the migration to containerd as a runtime (and complete the migration of dockerd to use containerd's image management).

Having said the above; if someone is able to root-cause the problem for this, and finds a fix, then of course contributions are welcome.

**Comment by joostmeijles** [comment]
Please note that the by me observed behavior started to occur since the latest stable release 2.0.0.0-win78.
I didn't have the problems with version 18.06.1-ce-win73.

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
