### ISSUE TITLE
All docker commands hang on latest centos AMI and latest docker-ce stable

### ISSUE THREAD

**Issue by lyptt** [moby/moby#36999]
**Description**

Docker seems to be failing to do pretty much anything on my centos install. I'm running the latest centos AMI available, and the latest stable docker.

`docker ps` hangs, `docker info` hangs, none of my containers appear to be doing much of anything.

**Steps to reproduce the issue:**
1. Fire up a centos AMI
2. Install docker-ce

**Describe the results you received:**
Any docker command hangs

**Describe the results you expected:**
Docker commands to work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Nothing, it hangs

**Output of `docker info`:**
Nothing, it hangs

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, latest centos AMI

**Comment by cpuguy83** [comment]
Can you provide some logs?

Also a goroutine stack trace: 

```
curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutines?debug=2
```

**Comment by tizki** [comment]
I have a similar issue, i'm using

- docker  18.03.0-ce
- centos 7 3.10.0-693.21.1.el7.x86_64
the server is a part of nomad cluster. nomad client version Nomad v0.7.0
storage driver is devicemapper

symptoms are:
* from time to time the process hangs and cannot accept allocations from nomad. when you try to do 
docker ps / docker version / docker info, it just hangs and doesn't response.
I also tried to grab the log as @cpuguy83  suggested above, but that also was unresponsive.
* different issue, but perhaps related - sometimes docker fails to stop containers, and they stay as zombie containers.

the last entries in the journalctl for docker service are:

> May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821694744Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3b4ea7c832ad70f2d9cdf8720f5c595f5e43f0adf0127aefa537d60f170814"
> May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821744857Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3b4ea7c832ad70f2d9cdf8720f5c595f5e43f0adf0127aefa537d60f170814-init"
> May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821791652Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3f74a35ad234243ccc5a878ead900b11c4b7f45f691ba662d14fc01973c7c5"

(note: https://github.com/moby/moby/issues/36010 sounds similar)

**Comment by cpuguy83** [comment]
@tizki It sounds like docker is not up yet.

**Comment by cpuguy83** [comment]
I'm going to close this for housekeeping purposes due to no response from the OP. Can re-open if we get more details.

Thanks!

**Comment by tizki** [comment]
> It sounds like docker is not up yet.
docker is definitely up.

> Can re-open if we get more details.
what details do you need?

**Comment by devannair777** [comment]
I got similar situation for centos 8 .Its most likely a versioning problem for containerd.io. Try uninstalling your current containerd.io and install containerd.io v1.2.2-3.el7
