### ISSUE TITLE
Very slow Network between containers in overlay network in Swarm when DNS entry is not given.

### ISSUE THREAD

**Issue by ashit07** [moby/moby#36998]
**Description**

I am facing an issue where the communication between the containers is very slow.
Ping from 1 container to another using service name is taking about 15 secs. However, if I use IP it takes about 2 secs. But we want to use service name and not IP.

We are using overlay network for our swarm setup.
We do not have anything in our hosts /etc/resolv.conf and we want to keep it that way.
Inside containers /etc/resolv.conf contains docker default entries (127.0.0.11).

I am able to reproduce the issue in multiple machines also (just remove everything from /etc/resolv.conf file and redeploy the swarm stack), but not sure how to solve it without giving entries in /etc/resolv.conf file.
If I add entries to hosts /etc/resolv.conf, ping from one container to another happens in milli-seconds. But I need to solve it without giving any external dns entry in /etc/resolv.conf.

**Steps to reproduce the issue:**
1. Remove entries from /etc/resolv.conf from your host.
2. Bring up docker swarm stack with multiple containers.
3. Go into any one container and try to ping another container using service name.

**Describe the results you received:**
ping takes about 14-15 secs.

**Describe the results you expected:**
ping should take milli-seconds.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue is reproducable easily.

**Output of `docker version`:**

```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**

```
[root@machine1 ~]# docker info
Containers: 24
 Running: 10
 Paused: 0
 Stopped: 14
Images: 48
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-335599337-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 20.56GB
 Data Space Total: 107.4GB
 Data Space Available: 54.33GB
 Metadata Space Used: 30MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.117GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: dn7r5zjtv00sb3ow1clwfmb5r
 Is Manager: true
 ClusterID: c8vhlaz2no7tuvbs9n37uvwpw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.101.116.291
 Manager Addresses:
  10.101.116.291:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: machine1
ID: 5DSG:I3EU:SUDR:BCFV:IQWF:SAQ5:3PHM:HHUB:IT76:AUVT:LRDF:6FZD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by bsousaa** [comment]
I'm closing this issue in the absence of reproducing steps. Feel free to comment and we can reopen.
