### ISSUE TITLE
Publishing container ports in Windows Server 2019 does not work

### ISSUE THREAD

**Issue by natalieparellano** [moby/moby#36990]
**Description**

Publishing a container port in Windows Server 2019 does not work. We expect that a listening process running inside a container can be made available on the host IP address via Docker's `-p` flag. However, when doing this with the Windows Server 2019 technical preview, connecting to the published port does not work.

**Steps to reproduce the issue:**
1. `docker run -d -p 40000:8080 microsoft/windowsservercore-insider:10.0.17650.1001 powershell -command '$l = [system.net.sockets.tcplistener]8080; $l.start(); sleep(10000)'`
2. `test-netconnection -computername <host ip address> -port 40000`
3. Network connection test fails

**Describe the results you received:**
We noticed in the latest technical preview of Windows Server 2019 that container ports cannot be published to the host. This behavior used to work just fine in Windows Server 1709.

Note that testing the connection to the container IP and port works just fine -- so we know that there is a listening process. Just the publishing fails to work.

**Describe the results you expected:**
We expect that publishing a port will allow container processes to be reached from the host's IP address.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently.

**Output of `docker version`:**

```
Client:
 Version:      master-dockerproject-2018-05-01
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f42c66bd
 Built:        Tue May  1 23:50:33 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      master-dockerproject-2018-05-01
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   fe2d3a1
  Built:        Tue May  1 23:59:43 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: master-dockerproject-2018-05-01
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17650 (17650.1001.amd64fre.rs_prerelease.180414-2140)
Operating System: Windows Server Standard Version 1803 (OS Build 17650.1001)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.999GiB
Name: WIN-FAPQVPA02FA
ID: 5PHV:N4QL:BHCU:E74V:QCXB:3KCK:54PG:M6VA:JWNW:RB2W:6QL7:5RUE
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: pivotalgreenhouse
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
ping @msabansal @jhowardmsft @johnstep PTAL

**Comment by msabansal** [comment]
@natalieparellano This is a known issue. We are following up on this and trying to resolve this ASAP. I didn't know that this bug shipped.  Thank you for reporting.

**Comment by johnstep** [comment]
@msabansal Is there a workaround?

**Comment by msabansal** [comment]
@johnstep  Unfortunately I am not aware of a workaround. I am going to follow up and see what can be done

**Comment by mhoran** [comment]
This looks to still be an issue in the latest 2019 build, 17666.

**Comment by msabansal** [comment]
@mhoran We are working on root causing this. We should have an answer soon.

**Comment by JMesser81** [comment]
@daschott please take a look

**Comment by dineshgovindasamy** [comment]
@mhoran @natalieparellano could you please confirm that remote host accessing the port mapping works? i.e from another host can you use the target Host IP: port and it works?

**Comment by natalieparellano** [comment]
@dineshgovindasamy we confirmed that this works when trying to access from a remote host

cc @mhoran @ajgokhale

**Comment by daschott** [comment]
@natalieparellano This issue has been fixed and a PR has been checked in. I will update you once it makes its way to an Insider build that is available.

**Comment by mhoran** [comment]
This issue does look to be resolved in build 17733.

```
PS C:\Users\Administrator> test-netconnection -computername 172.16.175.128 -port 40000


ComputerName     : 172.16.175.128
RemoteAddress    : 172.16.175.128
RemotePort       : 40000
InterfaceAlias   : Ethernet0
SourceAddress    : 172.16.175.128
TcpTestSucceeded : True
```

Note that testing Windows Server Containers is a bit cumbersome at the moment due to #37625, and we can't run our automated test suite until that issue is resolved.

**Comment by daschott** [comment]
Apologies for the delay, it turns out that we [switched branches when this was released](https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/#BsG3J9L6dkiHdDGJ.97).

**Comment by daschott** [comment]
@natalieparellano is this issue still active or can it be closed?

**Comment by yaelharel** [comment]
Hi @daschott, we've just tested it and it looks like it's working for `mcr.microsoft.com/windows/servercore:ltsc2019`.
Thank you for your help!
