### ISSUE TITLE
Run process without network inside container

### ISSUE THREAD

**Issue by hpbieker** [moby/moby#37005]
I am working on an application that runs various python scripts provided by the users. I would like to run these scripts in a sandboxes environment without network acccess, but the parent process needs access to network in order to retrieve instructions on which scripts to run and where to put the results.

Would it be possible for Docker Swarm to provide a way to run a sandboxed command inside a container?

Unfortunately, the sand boxing I have found requires access to create a new namespace or to profile an application. None of these are allowed in Docker Swarm. The last resort is to give the container access to /var/lib/docker.socket so it can run the command inside a new container, but that is like giving away the master key I the process.

**Comment by cpuguy83** [comment]
This is not currently possible.

It might be interesting if you could run these as separate containers on the same network but with different network policy applied to each.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
