### ISSUE TITLE
Export BuildArgs type

### ISSUE THREAD

**Issue by priyawadhwa** [moby/moby#37015]
Exporting [buildArgs](https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/builder/dockerfile/buildargs.go#L25) would be really useful for implementing the ARG command in [kaniko](https://github.com/GoogleContainerTools/kaniko)

**Comment by thaJeztah** [comment]
closing, as this was done in https://github.com/moby/moby/pull/37016 (thanks!)
