### ISSUE TITLE
Hang issues with the container-related commands.

### ISSUE THREAD

**Issue by Lynzabo** [moby/moby#37013]
**Description**

Hang issues with the container-related commands.For example command `docker ps`, `docker run`, `docker log`, but `docker info`, `docker images`, etc. are available

**Steps to reproduce the issue:**
1.The Docker daemon has been running for a few days. I have found that the commands related to container operations are not used, and other commands are normal.
2. Let's use the command docker ps as an example:

**Describe the results you received:**

Docker daemon becomes unresponsive.

**Describe the results you expected:**

Display all running containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 56
 Running: 30
 Paused: 0
 Stopped: 26
Images: 452
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42GiB
Name: vm10-1-10-29.ksc.com
ID: WJBG:4G7O:URCY:FD72:GIRQ:CHLZ:OMJN:REVM:IVBJ:MY2C:ZPHP:QPWC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 421
 Goroutines: 444
 System Time: 2018-05-07T19:16:02.461741426+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```
**The Dcocker daemon stack dump**
[goroutine-stacks-2018-05-07T172946+0800.log](https://github.com/moby/moby/files/1979631/goroutine-stacks-2018-05-07T172946.0800.log)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by cpuguy83** [comment]
This version of Docker is out of support.
The deadlock is occurring while waiting for containerd to respond to a request.
Containerd since Docker 17.12 is completely rewritten.

Closing since there's nothing really to troubleshoot here.
