### ISSUE TITLE
Unable to find binary/docker in /bundles

### ISSUE THREAD

**Issue by bcgshyam** [moby/moby#37021]
**Description**

Docker Noob here. I am trying to build a docker binary and following [this](http://oyvindsk.com/writing/docker-build-from-source) link. However, after doing `make binary`, I end up with `bundles/binary-daemon/dockerd-dev` instead of `bundles/<version>-dev/binary/docker-<version>-dev`. I am using Docker-CE 18.03, which is not the same as the one in the link(but I guess the procedure is same). Why am I getting a `dockerd` instead of `docker`? Or if that is the intended output, how do I run docker commands like docker run, docker info etc using the new binary? 
**Steps to reproduce the issue:**
1. git clone https://github.com/docker/docker.git
2. cd docker 
3. make binary

**Describe the results you received:**
Created binary: bundles/binary-daemon/dockerd-dev

**Describe the results you expected:**
Created binary: bundles/< version >-dev/binary/docker-< version >-dev

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens always. 

**Output of `docker version`:**
(before using the new binary)
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 79
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-39-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.83GiB
Name: ubuntu
ID: VSRU:CVYT:B6HQ:CABK:BHFQ:BNRD:PA52:R4C7:L7GK:PDOA:OA3N:XQO7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://web-proxy.ind.hp.com:8080/
HTTPS Proxy: https://web-proxy.ind.hp.com:8080
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running Ubuntu 16.04 on VMware Workstation.

**Comment by AkihiroSuda** [comment]
CLI was moved to https://github.com/docker/cli

**Comment by bcgshyam** [comment]
@AkihiroSuda didn't get you..what exactly has to be done?

**Comment by AkihiroSuda** [comment]
@bcgshyam 

* `make binary` with https://github.com/docker/docker.git produces daemon-side stuff (dockerd, docker-containerd, docker-containerd-shim, docker-runc, docker-init, docker-proxy)
* `make -f docker.Makefile binary` with https://github.com/docker/cli produces client-stuff (docker)

You will need both daemon-side and client-side stuff.

**Comment by bcgshyam** [comment]
So I need to `make -f docker.Makefile binary` first in docker/cli before doing `make binary` in docker?

**Comment by AkihiroSuda** [comment]
can be done in arbitrary order

**Comment by bcgshyam** [comment]
should the cli in https://github.com/docker/docker.git be replaced with https://github.com/docker/cli?
