### ISSUE TITLE
mkimage does not support ubuntu hardy debootstrap

### ISSUE THREAD

**Issue by dabrain34** [moby/moby#37020]
Ubuntu 16.04 amd64

**Steps to reproduce the issue:**
1. sudo ./mkimage.sh -d "../../" debootstrap --verbose --variant=minbase --components=main,universe --include=iproute,gpgv --arch=i386 hardy http://old-releases.ubuntu.com//ubuntu/

**Describe the results you received:**
E: Syntax error /etc/apt/apt.conf.d/docker-autoremove-suggests:16: Extra junk after value

**Describe the results you expected:**

A working image

**Additional information you deem important (e.g. issue happens only occasionally):**

If i comment out block at line 158 then i'm getting the next error:

E: Syntax error /etc/apt/apt.conf.d/docker-clean:12: Extra junk after value

**Output of `docker version`:**

```
18.03.1-ce
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tianon** [comment]
Indeed, this is (unfortunately) expected for such old releases as Ubuntu Hardy (8.04).

Over in [debuerreotype](https://github.com/debuerreotype/debuerreotype) there's some accounting for this done for older Debian releases (https://github.com/debuerreotype/debuerreotype/pull/24, especially the changes to `scripts/debuerreotype-minimizing-config` which compare the APT version directly) that might be usable to create a tarball for Hardy.

You can also adapt the existing `mkimage/debootstrap` script in your local copy by removing the configuration sections for all of `docker-archive`, `docker-autoremove-suggests`, `docker-clean`, `docker-gzip-indexes`, and `docker-no-languages`.

**Comment by tianon** [comment]
Yeah, I don't think it makes sense for us to maintain extra code to handle many deprecated distribution releases here, sorry.

You could also simply use `debootstrap` (the tool itself that this script wraps) directly.

**Comment by dabrain34** [comment]
Yes i understand, I just attach my diff here maybe it can help someone... All generated apt conf files arent supported by hardy.

diff --git a/contrib/mkimage/debootstrap b/contrib/mkimage/debootstrap
index 9f7d898..e71c4cc 100755
--- a/contrib/mkimage/debootstrap
+++ b/contrib/mkimage/debootstrap
@@ -103,7 +103,7 @@ if strings "$rootfsDir/usr/bin/dpkg" | grep -q unsafe-io; then
 	EOF
 fi
 
-if [ -d "$rootfsDir/etc/apt/apt.conf.d" ]; then
+if [ -d "$rootfsDir/etc/apt/apt.conf.d" && "$suite" != "hardy"]; then
 	# _keep_ us lean by effectively running "apt-get clean" after every install
 	aptGetClean='"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true";'
 	echo >&2 "+ cat > '$rootfsDir/etc/apt/apt.conf.d/docker-clean'"
