### ISSUE TITLE
Consistent error when pulling image from Docker Hub - failed to register layer: re-exec error

### ISSUE THREAD

**Issue by sanderdegroot** [moby/moby#37025]
**Description**
I am trying to pull the following image:
https://hub.docker.com/r/sdegrootvertafore/eventstoretcpmock/

I am unable to pull this image using either the command `docker pull sdegrootvertafore/eventstoretcpmock:insecuretcp` or using `docker stack deploy` (referencing a docker-compose file that has a service made up of the aforementioned image and tag). The image is a .NET framework application and uses Visual Studio's auto-generated Dockerfile, using microsoft/dotnet-framework:4.7.1 as the base (FROM) image.

**Steps to reproduce the issue:**
Create a Docker swarm with one manager node and two worker nodes (I don't think the swarm setup is relevant here but I'm including it for completeness' sake). On the manager node, run `docker pull sdegrootvertafore/eventstoretcpmock:insecuretcp`.

**Describe the results you received:**
I consistently get the following output from `docker pull sdegrootvertafore/eventstoretcpmock:insecuretcp`:
```
C:\Docker>docker pull sdegrootvertafore/eventstoretcpmock:insecuretcp
insecuretcp: Pulling from sdegrootvertafore/eventstoretcpmock
5847a47b8593: Pull complete
2dd7b93d509d: Pull complete
497f381a4df7: Extracting [==================================================>]  365.8MB/365.8MB
9bb93d8edb07: Download complete
9765413ead31: Download complete
0b591b375fc9: Download complete
0a3062b30f3b: Download complete
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\1605fc950a83a10583a15edbace9ccc18f7841382e5d884f19a814c5ff231c21\Files\Windows\System32\LogFiles\Scm\SCM.EVM: The system cannot find the file specified.
```

Interestingly, the file `C:\Windows\System32\LogFiles\Scm\SCM.EVM` does exist on disk on the machine on which I am trying to pull the image.

**Describe the results you expected:**
Docker pull succeeds and the image is listed when running `docker image ls`.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently with this particular image - I have never been able to pull it and I've only seen this error when pulling this particular image.

**Output of `docker version`:**

```
Client:
 Version:       17.06.2-ee-8
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    4e8ed51
 Built: Fri Mar 30 01:37:46 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-8
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   4e8ed51
  Built:        Fri Mar 30 01:47:12 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.2-ee-8
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: active
 NodeID: va0sqjsc6jhslvx4o0zjfqtzh
 Is Manager: true
 ClusterID: v0un3rkekb0tmi10ule700gaq
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.139.47
 Manager Addresses:
  192.168.139.47:2377
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1794.amd64fre.rs1_release.171008-1615)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.96GiB
Name: ATL-QAKBLAZINA
ID: GYAV:K2VM:JRDE:R2SC:WV2X:XKJL:BFXX:IX7N:APEB:MNJS:VC7S:KPU4
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine running Windows Server 2016 Standard 10.0.14393 Build 14393. Docker is using Windows containers.

**Comment by sanderdegroot** [comment]
I tried saving and loading the image using `docker save` and `docker load` but the same error is occurring.

**Comment by filipkral** [comment]
Hi, I also get this error when I try to pull a custom image from our private container registry. The image is based on `microsoft/dotnet-framework:4.7.1`
Note, `C:\Windows\System32\LogFiles\Scm\SCM.EVM` exists too.
But unfortunately I cannot see the resulting image if I `docker image ls` after the pull.

I am running this in Windows Server 2016 Datacenter as part of Azure Batch Account.
Any advice would be much appreciated.

**Comment by jhowardmsft** [comment]
This was fixed in EE-9. Just need to update.
