### ISSUE TITLE
overlay2: unknown option dm.basesize

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#37039]
I use `oveylay2` to start docker daemon with below config:
```
{
       "hosts":["unix:///var/run/docker.sock", "tcp://0.0.0.0:5555"],
       "storage-driver": "overlay2",
       "storage-opts": [
               "overlay2.override_kernel_check=true",
               "dm.thinp_percent=95",
               "dm.thinp_metapercent=1",
               "dm.thinp_autoextend_threshold=80",
               "dm.thinp_autoextend_percent=20",
               "dm.basesize=20G"
               ]
       "live-restore": true
}
```
found that all dm options can not be supported by `overlay2` like below:
```
DEBU[2018-05-11T16:19:03.592882940+08:00] [graphdriver] trying provided driver: overlay2 
DEBU[2018-05-11T16:19:03.603796476+08:00] Cleaning up old mountid : start.             
Error starting daemon: error initializing graphdriver: overlay2: unknown option dm.thinp_percent
```

If i change to use `overlay`, all is ok.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

I check the [doc](https://docs.docker.com/engine/reference/commandline/dockerd/), do not find which storage driver support or not.

**Comment by AkihiroSuda** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#options-per-storage-driver

> Options for devicemapper are prefixed with dm

**Comment by AkihiroSuda** [comment]
Neither `overlay` or `overlay2` supports dm-specific options.
Probably `overlay` is just ignoring dm-specific options.

**Comment by daixiang0** [comment]
I know. 
@AkihiroSuda  last question, how can i set basesize with `overlay2`?

**Comment by AkihiroSuda** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/

> overlay2.size
> Sets the default max size of the container. It is supported only when the backing fs is xfs and mounted with pquota mount option. Under these conditions the user can pass any size less then the backing fs size.

**Comment by thaJeztah** [comment]
I think the bug here is that the `overlay` storage driver silently ignores options it doesn't know; we should likely add a check there as well

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/37040 to prevent the overlay storage driver from silently ignoring these options
