### ISSUE TITLE
Inability to use bind mounts if source is on /

### ISSUE THREAD

**Issue by kolyshkin** [moby/moby#37032]
1. When running a recent version of docker-ce, it is not possible to create a bind mount for a directory which is on / (i.e. a root mount point):

> docker run -ti -v /var/lib/kubelet:/dummy:shared,z ubuntu /bin/bash
> docker: Error response from daemon: linux mounts: Could not find source mount of /var/lib/kubelet.

2. There is a warning on daemon start (reported https://github.com/docker/for-linux/issues/290#issuecomment-386625728):

> 5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29.592148011+08:00" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir=/var/lib/docker error="error getting daemon root's parent mount: Could not find source mount of /var/lib/docker"

**Comment by kolyshkin** [comment]
The cause is commit 871c95724.

**Comment by kolyshkin** [comment]
fix: https://github.com/moby/moby/pull/37031

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/37031 was merged

**Comment by Arau** [comment]
Hi,

I experienced an error mounting a volume with a rshared flag that would be explained by this issue. Besides, the error message matches with the commits mentioned in here. It is happening on the release 18.05.0-ce, but NOT on 18.04.0-ce.

However, the error occurs mounting a different dir than /, and I'd like to double check with you that the fix also applies. 


**Version**
```
root@storageos-1:~# docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Context**
```
vagrant@storageos-1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Example**
```
vagrant@storageos-1:~$ docker run -it -v /var/lib/storageos:/var/tmp:rshared busybox sh -c /bin/date
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
f70adabe43c0: Pull complete 
Digest: sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64
Status: Downloaded newer image for busybox:latest
docker: Error response from daemon: linux mounts: Could not find source mount of /var/lib/storageos.
```

Using the previous release, working example:
```
vagrant@storageos-2:~$ docker version
Client:
 Version:	18.04.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	3d479c0
 Built:	Tue Apr 10 18:20:32 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.04.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	3d479c0
  Built:	Tue Apr 10 18:18:40 2018
  OS/Arch:	linux/amd64
  Experimental:	false
vagrant@storageos-2:~$ docker run -it -v /var/lib/storageos:/var/tmp:rshared busybox sh -c /bin/date
Fri May 11 15:38:04 UTC 2018
```

**Comment by cpuguy83** [comment]
@Arau Thanks, the fix for the issue was merged into master this morning.

**Comment by kolyshkin** [comment]
For those suffering from the issue, a quick workaround is to bind mount the directory on the host to itself:
```
# docker run -ti -v /var/lib/kubelet:/dummy:shared,z ubuntu /bin/bash
docker: Error response from daemon: linux mounts: Could not find source mount of /var/lib/kubelet.
# mount --bind /var/lib/kubelet /var/lib/kubelet
# docker run -ti -v /var/lib/kubelet:/dummy:shared,z ubuntu /bin/bash
root@984f30b36d51:/#
```
