### ISSUE TITLE
Volume autodiscovery not inheriting cloudstor options when created with docker compose

### ISSUE THREAD

**Issue by kevinlisota** [moby/moby#37053]
We run docker on two VM's (Not using swarm mode). The docker containers are brought up using Docker Compose.

Docker Compose file defines two volumes using the cloudstor:azure driver, defining options like share name, uid and gid. The mount points for those volumes inside the container are also defined in docker-compose.yml.

Running docker-compose to bring up the container on the first VM is successful. Volumes are created and mounted.

Any subsequest VMs seem to be using the new volume autodiscovery, and the volumes are visible on each one.

Running docker compose on any subsequent VM's brings up the following error.

```
Configuration for volume uploads-production specifies “filemode” driver_opt 436, but a volume with the same name uses a different “filemode” driver_opt (None). If you wish to use the new configuration, please remove the existing volume “nginx-php_uploads-production” first:
$ docker volume rm nginx-php_uploads-production
```

Further inspection of the auto-discovered volumes shows that they have not inherited the options settings defined on the original volume on VM#1.

```
[
{
“CreatedAt”: “0001-01-01T00:00:00Z”,
“Driver”: “cloudstor:azure”,
“Labels”: null,
“Mountpoint”: “/mnt/cloudstor/nginx-php_uploads-production”,
“Name”: “nginx-php_uploads-production”,
“Options”: null,
“Scope”: “local”
}
]
```
Stumped here. How can I share a persistent file share across two VM's running Docker? This used to work flawlessly.

Docker version is 18.03.1-ce. Docker compose is 1.21.0. docker-compose.yml is version 3.6

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
