### ISSUE TITLE
docker hangs for all commands

### ISSUE THREAD

**Issue by tizki** [moby/moby#37066]
I have the following issue:
i'm using

- docker 18.03.0-ce
- centos 7 3.10.0-693.21.1.el7.x86_64
- the server is a part of nomad cluster. nomad client version Nomad v0.7.0
- storage driver is devicemapper

symptoms are:

- from  time to time the process hangs and cannot accept allocations from nomad. when you try to do
docker ps / docker version / docker info, it just hangs and doesn't response.
I also tried to grab the log with `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutines?debug=2`, but that also was unresponsive.
`ps -ef | grep docker` returns a few processes. when killing the docker-containerd-shim processes, docker returns to be responsive
- different  issue, but perhaps related - sometimes docker fails to stop containers, and they stay as zombie containers.
the last entries in the journalctl for docker service are:

```
May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821694744Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3b4ea7c832ad70f2d9cdf8720f5c595f5e43f0adf0127aefa537d60f170814"
May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821744857Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3b4ea7c832ad70f2d9cdf8720f5c595f5e43f0adf0127aefa537d60f170814-init"
May 14 08:42:28 myhost.com dockerd[5827]: time="2018-05-14T08:42:28.821791652Z" level=debug msg="devmapper: Loading data for file /var/lib/docker/devicemapper/metadata/bd3f74a35ad234243ccc5a878ead900b11c4b7f45f691ba662d14fc01973c7c5"
```

(note: #36010 sounds similar, re-opened #36999)

**Comment by thaJeztah** [comment]
Can you try updating to 18.03.1?

**Comment by tizki** [comment]
I can, but is there any relevant fix?

**Comment by cpuguy83** [comment]
Same answer as before. It looks like dockerd is not up and running (ie servering the API) yet and is instead going through each layer stored in devicemapper.

How long has it been doing this?
What is the contents of /var/lib/docker/devicemapper?

**Comment by tizki** [comment]
> Same answer as before. It looks like dockerd is not up and running (ie servering the API) yet and is instead going through each layer stored in devicemapper.
if that is the case, what cause it to stop? 

> How long has it been doing this?
it's not always, happens from time to time on each host, in the past few months. 

> What is the contents of /var/lib/docker/devicemapper?
it contains 2 directories:
metadata
mnt
which contain the containers data and metadata

**Comment by cpuguy83** [comment]
@tizki Would have to see the logs to know for sure. Could even be a crash.

**Comment by tizki** [comment]
@cpuguy83 which logs? 
tell me what data do you need and how to retrieve it.

**Comment by cpuguy83** [comment]
@tizki Docker daemon logs. Assuming you are using systemd... `journalctl -u docker`

**Comment by tizki** [comment]
happened again, see docker log here: https://gist.github.com/tizki/ab1cbf78e234ab4e985afcb4dc8a43d7
and currently running docker processes (ps -ef | grep docker | grep -v grep): https://gist.github.com/tizki/e5202bcbef18cb898cad4c955407c9b5

**Comment by tizki** [comment]
that's a symptom, no one stopped docker.

**Comment by cpuguy83** [comment]
@tizki The first entry is from systemd saying that a request was made to stop the engine.
The 2nd entry is from the engine saying it received SIGTERM.

**Comment by tizki** [comment]
@cpuguy83 I Understand that it was stopped, but it wasn't made by a person.
I'm the only one that uses those machine, and I use to sleep at those hours 😃 
so for some reason it got to a state were it stopped.
IMO it's related to devicemapper and it's configuration, but i'm not sure.

**Comment by tizki** [comment]
same case, different  host. this time I copied the whole docker service log:

**Comment by cpuguy83** [comment]
This is a different case than the original. The originally was literally shutdown.
This is a panic:

```
May 17 15:12:14 myHost10 dockerd[3460]: panic: send on closed channel
May 17 15:12:14 myHost10 dockerd[3460]: goroutine 42443140 [running]:
May 17 15:12:14 myHost10 dockerd[3460]: github.com/docker/docker/pkg/progress.chanOutput.WriteProgress(0xc46f225da0, 0xc481c199a7, 0xc, 0x0, 0x0, 0x55afcd8b25c3, 0xa, 0x10828, 0x10828, 0x0, ...)
May 17 15:12:14 myHost10 dockerd[3460]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progress.go:42 +0x68
May 17 15:12:14 myHost10 dockerd[3460]: github.com/docker/docker/pkg/progress.(*Reader).updateProgress(0xc474f53200, 0xc44c494001)
May 17 15:12:14 myHost10 dockerd[3460]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progressreader.go:64 +0xec
May 17 15:12:14 myHost10 dockerd[3460]: github.com/docker/docker/pkg/progress.(*Reader).Read(0xc474f53200, 0xc44c494000, 0x8000, 0x8000, 0x8000, 0x828, 0x0)
May 17 15:12:14 myHost10 dockerd[3460]: /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progressreader.go:45 +0xda
May 17 15:12:14 myHost10 dockerd[3460]: bufio.(*Reader).fill(0xc474f53260)
May 17 15:12:14 myHost10 dockerd[3460]: 	/usr/local/go/src/bufio/bufio.go:97 +0x11c
May 17 15:12:14 myHost10 dockerd[3460]: bufio.(*Reader).WriteTo(0xc474f53260, 0x55afcee4eb20, 0xc42000f4b8, 0x7fc54c07e3a8, 0xc474f53260, 0xc434e0d901)
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/bufio/bufio.go:491 +0x10f
May 17 15:12:14 myHost10 dockerd[3460]: io.copyBuffer(0x55afcee4eb20, 0xc42000f4b8, 0x55afcee48ae0, 0xc474f53260, 0x0, 0x0, 0x0, 0xc434e0d9e0, 0x55afccdfa1f1, 0x1)
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/io/io.go:382 +0x30c
May 17 15:12:14 myHost10 dockerd[3460]: io.Copy(0x55afcee4eb20, 0xc42000f4b8, 0x55afcee48ae0, 0xc474f53260, 0x0, 0x0, 0x0)
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/io/io.go:362 +0x6a
May 17 15:12:14 myHost10 dockerd[3460]: os/exec.(*Cmd).stdin.func1(0x55afcc442dda, 0x55afce3a0fe8)
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/os/exec/exec.go:219 +0x57
May 17 15:12:14 myHost10 dockerd[3460]: os/exec.(*Cmd).Start.func1(0xc432ea4b00, 0xc448a55660)
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/os/exec/exec.go:380 +0x29
May 17 15:12:14 myHost10 dockerd[3460]: created by os/exec.(*Cmd).Start
May 17 15:12:14 myHost10 dockerd[3460]: /usr/local/go/src/os/exec/exec.go:379 +0x648
```

This is likely triggered because of the code path caused by the devmapper error, but not really a devmapper issue (outside of the fact that it looks like you are out of space).

The fix for the panic will not be trivial, unfortunately.

**Comment by cpuguy83** [comment]
Docker doesn't accept API requests when it's restarting.
If, for instance, you can't get any of the debug endpoints, then this means
the daemon isn't actually fully up. There is no way that these would
deadlock outside of bad issues on the system.

The panic is caused by the devicemapper device becoming full and not being
able to procede, meanwhile the image pull is trying to extract a layer
asyncronously from this devicemapper error which casues a send on a closed
channel.

**Comment by tizki** [comment]
anyway to prevent it?
perhaps using overlay2 instead?

**Comment by cpuguy83** [comment]
Either way you'll end up running out of space, just that overlay sits on top of your root filesystem rather than on some other block device.
Are you cleaning up stale images and containers from the system?

**Comment by tizki** [comment]
yes, I'm cleaning with `docker system prune -a -f`

**Comment by tizki** [comment]
I switched to overlay 2, it took a while, but I got another docker crash (?)
see dump:
https://gist.github.com/tizki/4da6abe541a79db7af630926a9146ff0
docker service log (attached):
[dockerServiceJun05.log](https://github.com/moby/moby/files/2075415/dockerServiceJun05.log)
it seems that it crashed somewhere around:

> Jun 05 04:27:27 myHost.com dockerd[46331]: time="2018-06-05T04:27:27.620139977Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
Jun 05 04:27:28 myHost.com systemd[1]: Starting Docker Application Container Engine...
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28.241736577Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28.243850145Z" level=info msg="libcontainerd: started new docker-containerd process" pid=60774
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28Z" level=info msg="starting containerd" module=containerd revision=cfd04396dc68220d1cecbe686a6cc3aa5ce3667c version=v1.0.2
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1
Jun 05 04:27:28 myHost.com dockerd[60763]: time="2018-06-05T04:27:28Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
Jun 05 14:02:39 myHost.com dockerd[60763]: time="2018-06-05T14:02:39.524133060Z" level=info msg="Processing signal 'quit'"

>

**Comment by thaJeztah** [comment]
`Processing signal 'quit'` - looks like something send containerd a shutdown; you mention a crash, is there anything that points to a crash in your logs?

**Comment by tizki** [comment]
perhaps crash is not the right term in that case. i'm trying to find what cause it to quit.
it seems that it started to create a container at 04:27:09, and then quit 3 seconds after. (and no, nobody did kill -9 or something like this)

**Comment by zhonglin6666** [comment]
@thaJeztah
Now, docker run and docker kill  not work，but old containers can be exec to login in, but can not be kill and  stop.
Server Version: 17.12.1-ce
Storage Driver: overlay2
Backing Filesystem: xfs

maybe can not get lock，found in docker/docker/container/state.go
// IsRunning returns whether the running flag is set. Used by Container to check whether a container is running.
```
func (s *State) IsRunning() bool {
	s.Lock()
	res := s.Running
	s.Unlock()
	return res
}
```

with curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2 

```
goroutine 68254647 [semacquire, 1385 minutes]:
sync.runtime_SemacquireMutex(0xc421004e04, 0x2788900)
    /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc421004e00)
    /usr/local/go/src/sync/mutex.go:134 +0xee
github.com/docker/docker/container.(*State).IsRunning(0xc421004e00, 0xc426bdd5d8)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/container/state.go:250 +0x2d
github.com/docker/docker/daemon.(*Daemon).Kill(0xc420260000, 0xc4201a0480, 0x0, 0x0)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/kill.go:124 +0x4e
github.com/docker/docker/daemon.(*Daemon).ContainerKill(0xc420260000, 0xc42dc3f1d7, 0xc, 0x9, 0x0, 0x8a00000002910b00)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/kill.go:52 +0x83
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersKill(0xc420b4bfc0, 0x7f85ac36f560, 0xc42e5df2c0, 0x38b7d00, 0xc42e28bea0, 0xc42e396700, 0xc42e5df230, 0x2a4e3dd, 0x5)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:210 +0xed
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersKill)-fm(0x7f85ac36f560, 0xc42e5df2c0, 0x38b7d00, 0xc42e28bea0, 0xc42e396700, 0xc42e5df230, 0x7f85ac36f560, 0xc42e5df2c0)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:62 +0x69
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x7f85ac36f560, 0xc42e5df2c0, 0x38b7d00, 0xc42e28bea0, 0xc42e396700, 0xc42e5df230, 0x7f85ac36f560, 0xc42e5df2c0)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f85ac36f560, 0xc42e5df290, 0x38b7d00, 0xc42e28bea0, 0xc42e396700, 0xc42e5df230, 0xa002e94a160, 0x40)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:62 +0x423
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f85ac36f560, 0xc42e5df290, 0x38b7d00, 0xc42e28bea0, 0xc42e396700, 0xc42e5df230, 0x7f85ac36f560, 0xc42e5df290)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x83b
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x38b7d00, 0xc42e28bea0, 0xc42e396700)
    /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/api/server/server.go:137 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc4207db8c0, 0x38b7d00, 0xc42e28bea0, 0xc42e396700)

```

**Comment by thaJeztah** [comment]
Make sure to run a current version of Docker; Docker 17.12 reached EOL early 2018, and is no longer maintained. Also that version has known vulnerabilities (including container escapes)

**Comment by thaJeztah** [comment]
Closing as this went stale
