### ISSUE TITLE
Internal DNS does not working at Windows Server 1803 cotnainers in swarm mode. Services can't resolve name of other services.

### ISSUE THREAD

**Issue by vitaliy-leschenko** [moby/moby#37085]
### Information
  - Windows Version: Windows Server 1803 (10.0.17134.48) (Windows Server 1709 have no this issue)
  - Docker Version: master-dockerproject-2018-05-14

### Expected behavior
Any services in some network must be able to resolve IP of other services.

### Actual behavior
Services can't resovle IP of other services.

### Steps to reproduce the behavior

 1. init swarm
 2. create overlay network N
 3. create service A into network N
 4. create service B into network N
 5. try to ping any host of B from any host of A by IP - OK.
 6. try to ping any host of A from any host of B by IP - OK.
 7. try to ping B from any host of A by name - fail (can't resolve IP).
 8. try to ping A from any host of B by name - fail (can't resolve IP).

### Full Log
```
PS C:\> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
ot4jzcvlmq5w        ingress             overlay             swarm
d6294b92606f        nat                 nat                 local
a4d7fe669a64        none                null                local
5kdgg1b15p6z        testnet             overlay             swarm
PS C:\> docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                              PORTS
6d2gkkbkoq70        test1               replicated          1/1                 microsoft/windowsservercore:1803
oh7csoyplmqy        test2               replicated          1/1                 microsoft/windowsservercore:1803
PS C:\> docker service inspect --format="{{range .Endpoint.VirtualIPs}}{{.Addr}}{{end}}" test1
10.0.2.3/24
PS C:\> docker service inspect --format="{{range .Endpoint.VirtualIPs}}{{.Addr}}{{end}}" test2
10.0.2.5/24
PS C:\> docker ps
CONTAINER ID        IMAGE                              COMMAND               CREATED             STATUS              PORTS               NAMES
cb8d23e60d32        microsoft/windowsservercore:1803   "ping -t localhost"   5 minutes ago       Up 5 minutes                            test2.1.u0fqhifumtaz6hpdxwparkngn
93f9cfad9f66        microsoft/windowsservercore:1803   "ping -t localhost"   6 minutes ago       Up 5 minutes                            test1.1.trmxn03hrd7341xuwjzbpw1tv
PS C:\> docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" cb8d23e60d32
10.0.2.12
PS C:\> docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" 93f9cfad9f66
10.0.2.8
PS C:\> docker exec cb8d23e60d32 ping 10.0.2.8

Pinging 10.0.2.8 with 32 bytes of data:
Reply from 10.0.2.8: bytes=32 time=1ms TTL=128
Reply from 10.0.2.8: bytes=32 time<1ms TTL=128
Reply from 10.0.2.8: bytes=32 time<1ms TTL=128
Reply from 10.0.2.8: bytes=32 time<1ms TTL=128

Ping statistics for 10.0.2.8:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms
PS C:\> docker exec cb8d23e60d32 ping test1
Ping request could not find host test1. Please check the name and try again.
PS C:\> docker exec 93f9cfad9f66 ping 10.0.2.12

Pinging 10.0.2.12 with 32 bytes of data:
Reply from 10.0.2.12: bytes=32 time<1ms TTL=128
Reply from 10.0.2.12: bytes=32 time<1ms TTL=128
Reply from 10.0.2.12: bytes=32 time<1ms TTL=128
Reply from 10.0.2.12: bytes=32 time<1ms TTL=128

Ping statistics for 10.0.2.12:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
PS C:\> docker exec 93f9cfad9f66 ping test2
Ping request could not find host test2. Please check the name and try again.
PS C:\>
```

**Comment by vitaliy-leschenko** [comment]
This issue is not reproduced at Windows Server 1709 RTM and Windows Server Insider 10.0.17666.1000.
But reproduced at Windows Server 1803 only.

**Comment by Heidern** [comment]
I'm able to reproduce this issue as well.

**Comment by thaJeztah** [comment]
ping @msabansal @jhowardmsft @johnstep PTAL

**Comment by CassandraWin** [comment]
I have exactly the same issue on my Windows 10 1803. Any news on it?

**Comment by vitaliy-leschenko** [comment]
Unfortunatelly, no.

**Comment by pbering** [comment]
I have it working also on 1803 with setting the DNS cache like so: https://github.com/sitecoreops/sitecore-images/blob/a3920e8f15c950a6e7d1c85e85094a99502f2af2/images/9.0.2%20rev.%20180604/windowsservercore-1803/sitecore-base/Dockerfile#L24. Haven't tried without...

**Comment by thaJeztah** [comment]
ping @johnstep PTAL

**Comment by ollypom** [comment]
Hey @thaJeztah @vitaliy-leschenko, this is a known issue with a KB here: https://success.docker.com/article/swarm-internal-dns-is-inaccessible-on-windows-server-1803

**Comment by avinhan** [comment]
Hi @ollypom, thank you for sharing that article. I had the same issues with 1803 server. Once I opened the DNS port (UDP/53), service discovery works as expected (VIP mode). Tested in Azure with a 3 node Windows server 1803 cluster.

**Comment by daschott** [comment]
@vitaliy-leschenko can you try the following on 1803 as a workaround:
New-NetFirewallRule -DisplayName "Swarm DNS" -Direction Inbound -Action Allow -Protocol UDP -LocalPort 53

New-NetFirewallRule -DisplayName "Swarm DNS" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 53

This workaround is not needed on Windows Server 2019 and above.

**Comment by vitaliy-leschenko** [comment]
This commands are solving the problem.

С уважением, Виталий.

________________________________

**Comment by daschott** [comment]
Can we close the issue?

**Comment by vitaliy-leschenko** [comment]
@daschott, I think so. WS1803 is going to end of life (because 18 months is out). All newer server does not have this issue. Thank you.
