### ISSUE TITLE
r stop volume

### ISSUE THREAD

**Issue by jakubhnilicka** [moby/moby#37082]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jakubhnilicka** [comment]
Sorry, I don't know, how it happend.

**Comment by thaJeztah** [comment]
Haha, no worries; it's the GitHub keyboard shortcuts; https://help.github.com/articles/using-keyboard-shortcuts/

`c` creates a new issue; press enter and it's there 

It happens a lot :joy:
