### ISSUE TITLE
Setup dev environment, error running (make BIND_DIR=. shell)

### ISSUE THREAD

**Issue by ramiissat** [moby/moby#37099]
My development environment as follows:
1- Host system: Windows 10
2- Vmware 14
3- Virtual machine running Ubuntu 16.04.4 Desktop

I followed the instructions listed in (https://github.com/moby/moby/tree/master/docs/contributing).
When I reach the step (4) [make BIND_DIR=. shell] of (Task 2. Start a development container) at page (https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md)
The result shows a strange IP address (192.168.73.133) which belongs to my LAN, and I can ping it successfully.
How to solve?

I get the following error result:

Step 7/93 : RUN apt-get update && apt-get install -y    libnet-dev  libprotobuf-c0-dev  libprotobuf-dev     libnl-3-dev     libcap-dev  protobuf-compiler   protobuf-c-compiler     python-protobuf     && mkdir -p /usr/src/criu   && curl -sSL https://github.com/checkpoint-restore/criu/archive/v${CRIU_VERSION}.tar.gz | tar -C /usr/src/criu/ -xz --strip-components=1    && cd /usr/src/criu     && make     && make PREFIX=/build/ install-criu
 ---> Running in eaebaa402397
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9530 kB]

Get:6 http://192.168.73.133/security.debian.org/debian-security stretch/updates/main amd64 Packages [435 kB]

Err:6 http://192.168.73.133/security.debian.org/debian-security stretch/updates/main amd64 Packages
  Writing more data than expected (458752 > 435275)
  Hashes of expected file:
   - Filesize:435275 [weak]
   - SHA256:28223bbb7f9e6357e278ec140afaf6e8358021034d288388c6cdac697f6fefae
   - SHA1:ef18203c032ed1fe9c573560aad3923c982ee316 [weak]
   - MD5Sum:7668a706b73eb836864a8d57bdf9532e [weak]
  Release file created at: Wed, 16 May 2018 21:03:07 +0000

Get:7 http://192.168.73.133/deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
Fetched 9847 kB in 16s (606 kB/s)
Reading package lists...

E: Failed to fetch http://192.168.73.133/security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages.gz  Writing more data than expected (458752 > 435275)
   Hashes of expected file:
    - Filesize:435275 [weak]
    - SHA256:28223bbb7f9e6357e278ec140afaf6e8358021034d288388c6cdac697f6fefae
    - SHA1:ef18203c032ed1fe9c573560aad3923c982ee316 [weak]
    - MD5Sum:7668a706b73eb836864a8d57bdf9532e [weak]
   Release file created at: Wed, 16 May 2018 21:03:07 +0000

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y    libnet-dev  libprotobuf-c0-dev  libprotobuf-dev     libnl-3-dev     libcap-dev  protobuf-compiler   protobuf-c-compiler     python-protobuf     && mkdir -p /usr/src/criu   && curl -sSL https://github.com/checkpoint-restore/criu/archive/v${CRIU_VERSION}.tar.gz | tar -C /usr/src/criu/ -xz --strip-components=1    && cd /usr/src/criu     && make     && make PREFIX=/build/ install-criu' returned a non-zero code: 100
Makefile:124: recipe for target 'build' failed
make: *** [build] Error 100

**Comment by thaJeztah** [comment]
Is 192.168.73.133 configured as a proxy perhaps?

**Comment by thaJeztah** [comment]
Is 192.168.73.133 configured as a proxy perhaps?

**Comment by ramiissat** [comment]
No, there is no proxy at all,
But recently,
I tried to block this IP (192.168.73.133) by firewall on the first level host (windows), the command ended successfully without complaining of the existing IP (192.168.73.133).
Does this make any sense or add any useful information to make a clean build?

Here is a part of the output shows IP (192.168.73.133) and the success message at the end:

Step 7/93 : RUN apt-get update && apt-get install -y 	libnet-dev 	libprotobuf-c0-dev 	libprotobuf-dev 	libnl-3-dev 	libcap-dev 	protobuf-compiler 	protobuf-c-compiler 	python-protobuf 	&& mkdir -p /usr/src/criu 	&& curl -sSL https://github.com/checkpoint-restore/criu/archive/v${CRIU_VERSION}.tar.gz | tar -C /usr/src/criu/ -xz --strip-components=1 	&& cd /usr/src/criu 	&& make 	&& make PREFIX=/build/ install-criu
 ---> Running in dbf13a78fe52
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Ign:5 http://192.168.73.133/security.debian.org/debian-security stretch/updates/main amd64 Packages
Get:6 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Ign:7 http://192.168.73.133/deb.debian.org/debian stretch-updates/main amd64 Packages
Get:7 http://192.168.73.133/deb.debian.org/debian stretch-updates/main amd64 Packages [11.0 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
Get:5 http://192.168.73.133/security.debian.org/debian-security stretch/updates/main amd64 Packages [350 kB]
Fetched 10.2 MB in 17s (596 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libnet1 libnl-3-200 libprotobuf-c1 libprotobuf-lite10 libprotobuf10
  libprotoc10 python-pkg-resources zlib1g-dev
Suggested packages:
  manpages-dev python-setuptools
The following NEW packages will be installed:
  libcap-dev libnet1 libnet1-dev libnl-3-200 libnl-3-dev libprotobuf-c-dev
  libprotobuf-c1 libprotobuf-dev libprotobuf-lite10 libprotobuf10 libprotoc10
  protobuf-c-compiler protobuf-compiler python-pkg-resources python-protobuf
  zlib1g-dev
0 upgraded, 16 newly installed, 0 to remove and 3 not upgraded.
...
...
...
Successfully built fb456a4bcf5f
Successfully tagged docker-dev:my-test

**Comment by thaJeztah** [comment]
Strange, no I haven't seen this; only thing that comes to mind is the `BUILD_APT_MIRROR ` and `APT_MIRROR ` variable; we added that so that it's possible to set a mirror for package repositories; see

https://github.com/moby/moby/blob/1b7fe816e86f21a968410fca7a0cb9302c386f84/Makefile#L89-L90

and

https://github.com/moby/moby/blob/17b039cb4901fc0a37c409ebfdf4f3b2fcec4409/Dockerfile.simple#L10-L12

**Comment by ramiissat** [comment]
I have added the command (RUN echo "1-$APT_MIRROR, 2-$BUILD_APT_MIRROR, 3-$DOCKER_BUILD_APT_MIRROR") before the apt-get call [Step 7/93],
I've got the output:
1-deb.debian.org, 2-, 3-

**Comment by thaJeztah** [comment]
Just to check, I just purged my local image cache, and rebuilt my dev container; but everything works as expected;

```
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [440 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
Fetched 10.3 MB in 2s (4461 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libnet1 libnl-3-200 libprotobuf-c1 libprotobuf-lite10 libprotobuf10
  libprotoc10 python-pkg-resources zlib1g-dev
Suggested packages:
  manpages-dev python-setuptools
The following NEW packages will be installed:
  libcap-dev libnet1 libnet1-dev libnl-3-200 libnl-3-dev libprotobuf-c-dev
  libprotobuf-c1 libprotobuf-dev libprotobuf-lite10 libprotobuf10 libprotoc10
  protobuf-c-compiler protobuf-compiler python-pkg-resources python-protobuf
  zlib1g-dev
0 upgraded, 16 newly installed, 0 to remove and 8 not upgraded.
Need to get 3602 kB of archives.
After this operation, 18.9 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 libnet1 amd64 1.1.6+dfsg-3 [60.4 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libcap-dev amd64 1:2.25-1 [29.4 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 libnet1-dev amd64 1.1.6+dfsg-3 [118 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 libnl-3-200 amd64 3.2.27-2 [61.5 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 libnl-3-dev amd64 3.2.27-2 [96.2 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 libprotobuf-c1 amd64 1.2.1-2 [25.0 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 libprotobuf-c-dev amd64 1.2.1-2 [32.5 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 zlib1g-dev amd64 1:1.2.8.dfsg-5 [205 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 libprotobuf10 amd64 3.0.0-9 [681 kB]
Get:10 http://deb.debian.org/debian stretch/main amd64 libprotobuf-lite10 amd64 3.0.0-9 [125 kB]
Get:11 http://deb.debian.org/debian stretch/main amd64 libprotobuf-dev amd64 3.0.0-9 [954 kB]
Get:12 http://deb.debian.org/debian stretch/main amd64 libprotoc10 amd64 3.0.0-9 [626 kB]
Get:13 http://deb.debian.org/debian stretch/main amd64 protobuf-c-compiler amd64 1.2.1-2 [78.4 kB]
Get:14 http://deb.debian.org/debian stretch/main amd64 protobuf-compiler amd64 3.0.0-9 [52.8 kB]
Get:15 http://deb.debian.org/debian stretch/main amd64 python-pkg-resources all 33.1.1-1 [166 kB]
Get:16 http://deb.debian.org/debian stretch/main amd64 python-protobuf amd64 3.0.0-9 [292 kB]
```

**Comment by thaJeztah** [comment]
Actually; looking at those URLs again


That looks pretty much as if `apt-cacher` / `apt-cacher-ng` is installed somewhere; see https://github.com/Efreak/apt-cacher-ng;

```
       From the client side, apt-cacher-ng can be used as a drop-in
       replacement for apt-cacher. The same rules apply, e.g. Debian/Ubuntu
       users should EITHER:

        -  Specify the caching machine as HTTP Proxy for APT, e.g.
           putting a line like the following into a file like
           /etc/apt/apt.conf.d/02proxy:

             Acquire::http { Proxy "http://CacheServerIp:3142"; };

       OR:

        -  Replace all mirror hostnames with cachinghost/hostname in
           sources.list, so

             deb http://ftp.uni-kl.de/debian etch main

           should now become:

             deb http://192.168.0.17:3142/ftp.uni-kl.de/debian etch main

        (assuming that CacheServerIp is 192.168.0.17 and the service port
       is 3142) .
```

**Comment by thaJeztah** [comment]
Yes, it won't be installed in the image; what environment are you in? Is this on your home network? A corporate network?

**Comment by ramiissat** [comment]
It's the university network.
I've mentioned in my first post that I can ping this address.

Do you think there is a cache service hosted there?
But, shouldn't the image be configured to use it?

**Comment by thaJeztah** [comment]
> Do you think there is a cache service hosted there?

I start to suspect that's the case yes

> But, shouldn't the image be configured to use it?

Yes, that surprised me a bit, I thought that was needed; _unless_ the network would intercept the traffic, and issue a redirect;

What happens if you try accessing those repositories with cURL? 

```
curl -v http://security.debian.org/debian-security/
```

Also worth trying what happens if you specify a different DNS for the daemon (e.g. if the University's DNS points `security.debian.org` to their own mirror. You can do this through a `daemon.json` configuration file;

- create a `/etc/docker/daemon.json` file inside the VM (where the docker daemon runs)
- in that file, set the DNS option, for example, to use Google's DNS: `{"dns": ["8.8.8.8"]}`
- (re) start the docker daemon (`systemctl restart docker.service`)

(see [this section in the documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) for more details)

**Comment by ramiissat** [comment]
curl returned normal output (HTTP/1.1 200 OK)
and nothing changed when I set DNS for docker.

Recently, I've taken a snapshot of my current system (Ubuntu VM) for farther investigations, and recreated the whole environment stack.
When I've reached the step (make BIND_DIR=. shell), the same address (192.168.73.133) appeared in apt-get output, but the new thing that it continued without complaining.
I still can ping that address from both Ubuntu and Windows.

But now, the development environment works as described.

**Comment by thaJeztah** [comment]
> But now, the development environment works as described.
 
That's good news! Still don't have an idea where that redirect came from, but happy to hear it's working now.

Let me go ahead and close this issue; but feel free to continue the conversation
