### ISSUE TITLE
Flaky test: TestContainerAPITop

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#37109]
Seen this fail a few times; 

https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/9921/console

- https://github.com/moby/moby/pull/32268#issuecomment-291645360
- https://github.com/moby/moby/pull/36511#issuecomment-382216564
- https://github.com/moby/moby/pull/37106#issuecomment-390403351

```
11:31:27 FAIL: docker_api_containers_test.go:435: DockerSuite.TestContainerAPITop
11:31:27 
11:31:27 docker_api_containers_test.go:453:
11:31:27     c.Assert(top.Processes[0][10], checker.Equals, "/bin/sh -c top")
11:31:27 ... obtained string = "top"
11:31:27 ... expected string = "/bin/sh -c top"
11:31:27 
```

**Comment by arm64b** [comment]
Interesting! From the logic of the testing code, seems the `docker top` will spawn a new process named `top` inside the container? But I can't see that with below command sequences:
```
root@huawei-d05:~# docker run -d busybox /bin/sleep 5m
77af274af8c4deb29a65b32afae3b659b1065a4ef113d965a8de75f10ef64dcd
root@huawei-d05:~# docker top 77af274af8c4deb29a65b32afae3b659b1065a4ef113d965a8de75f10ef64dcd aux
USER                PID                 %CPU                %MEM                VSZ                 RSS                 TTY                 STAT                START               TIME                COMMAND
root                22553               0.1                 0.0                 1264                4                   ?                   Ss                  17:07               0:00                /bin/sleep 5m
```

**Comment by kolyshkin** [comment]
I took a look, I think I know there this is coming from.

The test expects two processes in the output:
1. `/bin/sh -c top`
2. `top`
in the given order.

`ps aux` output is sorted by PID, and so since the `top` is a child of `/bin/sh -c top` it has a higher PID and will come second... unless the PIDs on the system are exhausted and the PID rollover happens, in which case `top` PID will be lower than that of `/bin/sh`.

I'll send a patch.

PS `docker top` implementation appears to be very inefficient, running `ps` for all the processes in the system and then filtering those belonging to a particular container :( but that's a separate issue of course.

**Comment by arm64b** [comment]
> The test expects two processes in the output:
/bin/sh -c top
top
in the given order.

I am wondering why the `docker top` command can't see the `top` process just as my previous comment shows...

**Comment by thaJeztah** [comment]
Oh! I see: the container itself is started with top as well in the test 

     out, _ := dockerCmd(c, "run", "-d", "busybox", "/bin/sh", "-c", "top")

Looks like you started it with "sleep"; 

    docker run -d busybox /bin/sleep 5m

**Comment by thaJeztah** [comment]
oh, never mind: interpreted it as "don't see it _twice_" but it doesn't show at all in the sleep case?

**Comment by arm64b** [comment]
@thaJeztah 

I am wondering why I can see only one process: `/bin/sleep 5m` with `docker top` command, according to the logic of the test, I should see 2 processes: `/bin/sleep 5m` and `top`, right?

**Comment by kolyshkin** [comment]
> From the logic of the testing code, seems the docker top will spawn a new process named top inside the container?

No. `docker top` is implemented via `ps` run on the host.

In this test case we run sh which asked to run top, so we see sh and top.
