### ISSUE TITLE
No containers starting on restarting docker service

### ISSUE THREAD

**Issue by retardtank** [moby/moby#37118]
**Description**

**Steps to reproduce the issue:**
1. Stop dockerd service
2. Start dockerd service
3. Run `docker ps`

**Describe the results you received:**
No containers running.

**Describe the results you expected:**
Containers running.

**Output of `docker version`:**

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:13:43 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:20:43 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8213
 Running: 0
 Paused: 0
 Stopped: 8213
Images: 332
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: keh577kjaph7jiol8rjnn5tke
 Is Manager: true
 ClusterID: wbw5arjoyuy9oh7jnc7ywtkku
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.1.221
 Manager Addresses:
  10.0.1.221:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.30
Operating System: Alpine Linux v3.7
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.25GiB
Name: nxt1
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 57
 Goroutines: 529
 System Time: 2018-05-21T16:05:39.698871909+02:00
 EventsListeners: 0
Username: 
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, official statically linked docker binary, kernel 4.14.30

Log of dockerd output:
[docker.log.zip](https://github.com/moby/moby/files/2022878/docker.log.zip)

**Comment by retardtank** [comment]
No, they all start as a part of a swarm/stack, and will usually always start when docker does. I suspect though, from looking at the log attached, it had to do with that some network or interface could not be created.

**Comment by stffabi** [comment]
I haven't yet taken a look into your logs, but probably you are also seeing #37087

**Comment by retardtank** [comment]
Not sure really, more like:
```
level=error msg="fatal task error" error="starting container failed: subnet sandbox join failed for \"10.0.0.0/24\": error creating vxlan interface: file exists" module=node/agent/taskmanager node.id=keh577kjaph7jiol8rjnn5tke service.id=hsv67ykujkrjw8gdlt2g6q73l task.id=or5we4kaenlnyrwqo5cgpf5o5
```

**Comment by thaJeztah** [comment]
The vxlan error Could possibly be related to https://github.com/moby/moby/issues/36743

**Comment by retardtank** [comment]
I recently ran into the same behaviour on a different machine, more or less same spec as above but kernel version 4.14.67 and docker 18.03.1. While docker was stopped, I noticed that, on that particular machine, an interface named vx-001001-w6gpg would show up. If I simply just removed that interface prior to starting docker again, everything would startup fine...If it helps in any way...

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  If you encounter this issue on a current engine release, please open a new issue.
