### ISSUE TITLE
failed to retrieve OCI runtime container pid:

### ISSUE THREAD

**Issue by farooqte96** [moby/moby#37122]
Hi I tested docker checkpoint-restore feature on docker-ee-17.06 version. It works fine there. But i have to replace that with docker-ce-18.03 because nvidia-docker didn't support docker ee version. Now i am facing issue in checkpointing and restoring containers in docker-ce. Docker checkpoint creates a checkpoint but doesn't stop the container and also doesn't list the created checkpoints. Then there is also error when try to retsore container from checkpointed image.
Can anybody suggest how i can use nvidia-docker with docker-ee or how to properly checkpoint & restore in docker-ce version.

docker version Output:
Client:
Version: 18.03.1-ce
API version: 1.37
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:17:20 2018
OS/Arch: linux/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: 18.03.1-ce
API version: 1.37 (minimum version 1.12)
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:15:30 2018
OS/Arch: linux/amd64
Experimental: true

vrone@vrone:~$ docker checkpoint create looper2 checkpoint2
checkpoint2

vrone@vrone:~$ docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES

592f0043ff04 busybox "/bin/sh -c 'i=0; wh…" 38 seconds ago Up 37 seconds looper2

vrone@vrone:~$docker checkpoint ls looper2
Error response from daemon: open /var/lib/docker/containers/592f0043ff04726e74899d226bf7d71371c4bc74f8d4c7451e8b02c7ce301f1f/checkpoints/checkpoint2/config.json: no such file or directory

vrone@vrone:~docker start --checkpoint=checkpoint2 looper-clone
Error response from daemon: failed to retrieve OCI runtime container pid: open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/1329a2058912a11262917a223e8adddec83ce86d8164bc0069ed0c3a6c7dfe7f/init.pid: no such file or directory: unknown

**Comment by avagin** [comment]
It looks like a dup of https://github.com/moby/moby/issues/35691

**Comment by cpuguy83** [comment]
Yep, thanks!
