### ISSUE TITLE
No connection could be made because the target  machine actively refused it.

### ISSUE THREAD

**Issue by john612** [moby/moby#37127]
I am trying to pull the hello-world container and I receive the following error: PS C:\Windows\System32\WindowsPowerShell\v1.0> docker pull tutum/hello-world
Using default tag: latest
docker : Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 35.169.231.249:443: connectex: No connection could be made because the target 
machine actively refused it.
At line:1 char:1
+ docker pull tutum/hello-world
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...ely refused it.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

The version information is
PS C:\Windows\System32\WindowsPowerShell\v1.0> docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

I am running windows 10 with Hyper V enabled.  Please let me know what is causing the issue. I have been working on this for some time and have tried all the posts I have seen and nothing seems to resolve the issue.

**Comment by john612** [comment]
If I click the link https://registry-1.docker.io/v2/  I receive the following 

errors |  
-- | --
0 |  
code | "UNAUTHORIZED"
message | "authentication required"
detail | null

**Comment by john612** [comment]
No i get the following 
H:\>docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: Bad Request

**Comment by manishtomar** [comment]
@john612 If you've `curl` and `jq` on windows installed can you try 
```
curl https://registry-1.docker.io/v2/library/hello-world/manifests/latest -H "Authorization: Bearer $(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/hello-world:pull" | jq -r .token)"
```
This should print manifest in JSON format. If it works then I suspect dockerd is having trouble talking to registry for some reason.

@thaJeztah Since this is not really a moby issue, should this be moved to https://github.com/docker/hub-feedback/?

**Comment by thaJeztah** [comment]
@manishtomar yes, perhaps; thought it wouldn't hurt keeping it open for a bit, in case it was an intermittent issue

**Comment by john612** [comment]
Moby is another issue. If I try to run linux docker wont even start

**Comment by arpitjindal97** [comment]
Install `curl` by following [these](https://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-windows#16216825) steps

Download `jq` from [here](https://github.com/stedolan/jq/releases) and add it's path to PATH variable

Then try the command. It should print some json

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
