### ISSUE TITLE
LCOW feature request: Custom file permissions on volume mounts for LCOW

### ISSUE THREAD

**Issue by Ageraluon** [moby/moby#37158]
The largest limitation that I am facing using (non-LCOW) Docker for windows is that all files mounted to the moby vm via a volume are assigned UID 0 : GID 0 755 unix file permissions, which cannot be changed.
Since many linux docker projects involve processes that need file permissions to be changed, these projects cannot be run on a windows host without severe modifications - examples are the standard apache server, nextcloud or gitlab which change file permissions to special users created in the container and fail if they are not able to do so.

In (https://github.com/docker/for-win/issues/2042), it was mentioned that while standard Docker for Windows uses CIFS mounts that are quite inflexible, the LCOW way of mounting host files into containers using 9p might have the potential to allow for much more flexible mapping. Is this correct, and is there any support for creating volume mounts with custom uid/gid/permission sets on the roadmap for LCOW development? 

Thank you for any insight into this issue!

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
