### ISSUE TITLE
Build output between 17.06 and 18.06 differs for COPY step

### ISSUE THREAD

**Issue by chris-crone** [moby/moby#37164]
**Description**
Build output when copying a file differs between 17.06 and 18.06, see: https://github.com/docker/cli/pull/1064#discussion_r189900011.

**Steps to reproduce the issue:**

```bash
$ cd image
$ ls
Dockerfile something
$ cat Dockerfile
FROM alpine
COPY something /
$ docker build -t copy .
```
1. Build Dockerfile that contains `COPY` using 17.06 engine
2. Build Dockerfile that contains `COPY` using 18.06 engine

**Describe the results you received:**
17.06:
```bash
$ docker build -t copy .
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : COPY something /
 ---> 577b61f8471b
Removing intermediate container 86ec5fc54328
Successfully built 577b61f8471b
Successfully tagged copy:latest
```

18.06:
```bash
$ docker build -t copy .
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : COPY something /
 ---> 93321d321367
Successfully built 93321d321367
Successfully tagged copy:latest
```

**Describe the results you expected:**
18.06 output should contain the "Removing intermediate container" line.

**Additional information you deem important (e.g. issue happens only occasionally):**

Believe this is present in 18.03 too.

**Comment by thaJeztah** [comment]
Just leaving this here, in case it's a useful train of thoughts; I wonder if we use the "autoremove" option nowadays for the intermediate containers (instead of manually removing)

**Comment by chris-crone** [comment]
This change was intentional, closing: https://github.com/moby/moby/pull/37189#issuecomment-393901093
