### ISSUE TITLE
Incorrect caching with LCOW and multi-stage build

### ISSUE THREAD

**Issue by davidpendraykalibrate** [moby/moby#37168]
**Description**

When I copy from files from one stage to another, this step is being incorrectly cached when running a linux container in Windows container mode (LCOW). If I switch to linux containers, the cache is correctly invalidated.

**Steps to reproduce the issue:**
1. Switch to windows containers mode
2. Clone ``https://github.com/davidpendraykalibrate/DockerTest``
3. Change directory into DockerTest
3. Run ``make build``
4. Change "test2" to "test3" in ProjectPath/Program.cs
5. Run ``make build`` again

**Describe the results you received:**
Step 10/10 says "Using cache"

**Describe the results you expected:**
Step 10/10 should not say "Using cache" (because step 6 and step 7 did not use cache)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 79
Server Version: 18.05.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.48)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88GiB
Name: NBMAN1887
ID: K3EC:JPHI:ZBJ2:PQW7:TTKH:ZAJU:S464:HSK3:OXMC:NAQU:DKPA:HXJL
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2018-05-29T12:13:33.1765784+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @salah-khan @johnstep

**Comment by jhowardmsft** [comment]
@davidpendraykalibrate I've fixed a few bugs around LCOW, and pretty sure this one is no longer an issue. Please re-open when using latest binaries if it still repros.
