### ISSUE TITLE
feature request: `docker volume backup` command

### ISSUE THREAD

**Issue by isLishude** [moby/moby#37162]
How to  backup or restore a volume?

The way from [Docker doc](https://docs.docker.com/storage/volumes/#backup-a-container)

![image](https://user-images.githubusercontent.com/24730006/40591700-81a97548-6248-11e8-8983-6d5344f71b24.png)

So many steps to do for backuping and restoring,why not `docker volume backup` or `docker volume restore`

**Comment by islishude** [comment]
Hi, @minecraftchest1  you can file an new issue if you need it.

I don't want to receive the update any more.

**Comment by thaJeztah** [comment]
There's various other tickets (some still open) for this, so let me lock this one.
