### ISSUE TITLE
pkg/urlutil.IsGitURL: add gitlab.com, bitbucket.org, ...?

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#37173]
https://github.com/moby/moby/blob/65bd038fc5e47ed37d2702cbdd6ce484d320380b/pkg/urlutil/urlutil.go#L13

discussed in https://github.com/moby/buildkit/pull/416#discussion_r191599027

cc @tonistiigi

**Comment by AkihiroSuda** [comment]
related code for `go get`: https://github.com/golang/go/blob/1102616c772c262175f5ba5f12d6b574d0ad9101/src/cmd/go/internal/get/vcs.go#L966 (not sure why gitlab is omitted though)

**Comment by AkihiroSuda** [comment]
I set `exp/beginner` on this issue, but probably we need to discuss whether we want to add more ones or freeze the current spec, before opening a PR.

cc @thaJeztah

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/37174 to make this more clear from a code perspective 🤗
