### ISSUE TITLE
Refactoring code in /client/client.go

### ISSUE THREAD

**Issue by etalamante** [moby/moby#37185]
Hello, I am new to Open Source and want to start collaborating with this project. 

On the [client.go](https://github.com/moby/moby/blob/master/client/client.go) file, since line 372 located on `ParseHostURL` method declaration, before returning the parsed URL, it checks if the address is tcp. It checks it with an if statement using the variables `basePath, proto, addr`

```
var basePath string
proto, addr := protoAddrParts[0], protoAddrParts[1]
if proto == "tcp" {
	parsed, err := url.Parse("tcp://" + addr)
	if err != nil {
		return nil, err
	}
	addr = parsed.Host
	basePath = parsed.Path
}
return &url.URL{
	Scheme: proto,
	Host:   addr,
	Path:   basePath,
}, nil
```

The `basePath` is the problem, because if the address is not tcp, the variable is not initialized and is passed to the return object as field.

So I want to make a PR refactoring this block of code, by setting up that if statement to use optional statements with the definition of the 3 variables and passing those parsed if the address is tcp, and for every other case, pass only `proto` and `addr` to the fields.

I opened this issue to get orientation if the refactor is worth by you and get feedback if not.

**Comment by thaJeztah** [comment]
Closing this per  https://github.com/moby/moby/pull/37187#issuecomment-410001238
