### ISSUE TITLE
get.docker.com certificate is expired

### ISSUE THREAD

**Issue by fkautz** [moby/moby#37198]
get.docker.com web certificate expired June 2 and is now returning errors when users attempt to install via `curl https://get.docker.com | sh`

**Comment by darkpixel** [comment]
Ha!  You beat me to reporting it by 9 minutes. :)

**Comment by AkihiroSuda** [comment]
I think this should be discussed in the Docker repo: https://github.com/docker/for-linux/issues/328 

Maybe we should lock this issue?

**Comment by seemethere** [comment]
Everything should be back to normal now!

```
❯ curl -IL https://get.docker.com
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 13847
Connection: keep-alive
Date: Tue, 01 May 2018 09:04:13 GMT
Last-Modified: Wed, 25 Apr 2018 18:23:19 GMT
x-amz-version-id: ml2j3ltSM9mIqVYIUvRNPGiOd6iyo4kH
ETag: "41587a5e3b3cdfdec2580853361f8b63"
Server: AmazonS3
Age: 34398
X-Cache: Hit from cloudfront
Via: 1.1 ff09df097f823b2834408d17e9779d62.cloudfront.net (CloudFront)
X-Amz-Cf-Id: kagB7fPfnDDU6GtqWe2ldjxpIvWu2uy2LK_4Sgepy-4Csf8ChO0cKw==
```

**Comment by thaJeztah** [comment]
Thanks for the update! Closing this issue
