### ISSUE TITLE
docker swarm ERROR: failed to ptrace(ATTACH)

### ISSUE THREAD

**Issue by 13428282016** [moby/moby#37196]
docker swarm caush ERROR: failed to ptrace(ATTACH) in php-fpm slow log, I know --cap-add can solve this problem  ,but this option dont support in swarm.how to fix it

**Comment by AkihiroSuda** [comment]
This requires `--cap-add SYS_PTRACE` to be implemented.

Let me close this as a dup of https://github.com/moby/moby/issues/25885
