### ISSUE TITLE
Not able to run .sh file inside windows docker container

### ISSUE THREAD

**Issue by Jayesh-Acellere** [moby/moby#37205]
I have built image on top of microsoft/windowsservercore using dockerfile on Windows 10 machine. Docker image is created successfully. I need to run .sh file after logging into windows container. However i am not able to run any .sh file. If i run .sh file, nothing happens.

c:\WorkSpace\dbscripts>bash init_db.sh

c:\WorkSpace\dbscripts>
bash is present on container as Git is installed.

c:\WorkSpace\dbscripts>where bash
c:\git\bin\bash.exe
Is there any way by which i can run .sh files inside windows container ?

C:\Users\Jayesh>docker version
Client:
Version: 18.03.1-ce
API version: 1.37
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:12:48 2018
OS/Arch: windows/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: 18.03.1-ce
API version: 1.37 (minimum version 1.24)
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:21:42 2018
OS/Arch: windows/amd64
Experimental: true

**Comment by luenix** [comment]
By "nothing happens", do you mean that the script's exit code is 0 yet the script does nothing?

If you haven't already, please add `set -eux` ([ss64.com docs on `set`](https://ss64.com/bash/set.html)) at the beginning of your shell script then try the execution again.  Additionally, you may find value in ruling out whether or not the shell script functions as expected when run on a bare-bones host.  Lastly, you might want to verify that the execution bit is enabled for the script (`chmod +x ./init_db.sh`).

**Comment by Jayesh-Acellere** [comment]
Please note this .sh file i am trying to run on Windows container where container os is windowsservercore. 

So no question of execution bit. My main concern is can we run bash scripts on windowsservercore container ? By default bash is not present. I have installed git and it comes with bash.exe .

**Comment by CJCombrink** [comment]
I had the same issue trying to run `sh` in a windows container using git bash installation (completely unrelated to moby but perhaps it might help):

I had to do the following: https://github.com/Alexpux/MSYS2-packages/issues/1239#issuecomment-387110316

Copy the folder and run from there
```
PS > xcopy /S C:\Git C:\Git_Copy
PS > C:\Git_Copy\usr\bin\sh.exe --version > v.txt
PS > type v.txt
```
As mentioned in that thread, the output gets lost somewhere in the container, thus sending it to a text file.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
