### ISSUE TITLE
arm64 support in the Docker official document

### ISSUE THREAD

**Issue by arm64b** [moby/moby#37217]
Hello @thaJeztah , recently some persons ask me why `docker-ce` only supports `armhf` while not `arm64`, they point me to the linker here: https://docs.docker.com/install/linux/docker-ce/ubuntu/

So would you pls keep an eye on this and help to update the official document adding `arm64` support section?

**Comment by jaswdr** [comment]
@arm64b not all latest Ubuntu versions has docker in `arm64` architecture supported (for example "artful" doesn't has a official arm64 bin, see [this](https://download.docker.com/linux/ubuntu/dists/artful/stable/) link), so they cann't put this in the docs, but of course you can use for yourself, buiding from source but is everything for your own risk.

**Comment by thaJeztah** [comment]
The packaging scripts used for Docker CE are in https://github.com/docker/docker-ce-packaging. arm64 for some distros was added in https://github.com/docker/docker-ce-packaging/pull/35 (perhaps there were some follow-ups); it's possible however, that it was added for more distros but only available in the "edge" channel, and not yet in the "stable" (currently: Docker CE 18.03) versions

**Comment by thaJeztah** [comment]
To check what's available for 18.03; the packaging scripts are pulled into the docker-ce repository as  "packaging" component; https://github.com/docker/docker-ce/tree/18.03/components/packaging

**Comment by thaJeztah** [comment]
This should all be done now
