### ISSUE TITLE
vpnkit.exe consumes too much memory

### ISSUE THREAD

**Issue by trinhpham** [moby/moby#37219]
**Description**
vpnkit.exe consumes too much memory
![image](https://user-images.githubusercontent.com/9128061/41027570-90286b0a-69a1-11e8-8e1f-b9b7b437008d.png)

**Steps to reproduce the issue:**
1. Use Docker container to build some big C++ projects (QT, OpenCV,...). The Docker container uses volume to map source code from physical folder of the host machine.

**Describe the results you received:**
vpnkit.exe consumes too much memory
![image](https://user-images.githubusercontent.com/9128061/41027570-90286b0a-69a1-11e8-8e1f-b9b7b437008d.png)

**Describe the results you expected:**
vpnkit.exe shouldn't eat up to Gigabytes of memory

**Output of `docker version`:**
```PowerShell
PS C:\Users\trinh.pham> docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
**Output of `docker info`:**
```PowerShell
PS C:\Users\trinh.pham> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155da76573
ID: TDY3:A4MI:GGGJ:U3RY:XWWP:JL2H:JVRY:L7AF:L3GL:XZBW:3TI2:ALL5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 51
 System Time: 2018-06-06T08:49:26.7417247Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 [MASKED]:8888
 [MASKED]:8889
 127.0.0.0/8
Registry Mirrors:
 https://[MASKED]:8888/
Live Restore Enabled: false
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Pro x64 Version 1709 (16299.309)

**Comment by djs55** [comment]
This is a duplicate of https://github.com/moby/vpnkit/issues/371

There is a fix in the current development version which will be included in the next edge release. If you'd like to try the fix a little early, then there are instructions for upgrading the current edge release here: https://github.com/moby/vpnkit/issues/371#issuecomment-390248401

**Comment by trinhpham** [comment]
This is duplicated to https://github.com/docker/for-win/issues/2087
