### ISSUE TITLE
Feature Request: Set runtime in a Dockerfile

### ISSUE THREAD

**Issue by bribroder** [moby/moby#37216]
Hi there,

I'm using the nvidia-docker 2.0 runtime to work with GPUs from within a container:
https://github.com/NVIDIA/nvidia-docker

Unfortunately, building images which rely on the runtime is tricky right now... The nvidia-docker repo actually documents this in their wiki:

>Default runtime
>
>The default runtime used by the Docker® Engine is runc, our runtime can become the default one by configuring the docker daemon with --default-runtime=nvidia. Doing so will remove the need to add the --runtime=nvidia argument to docker run. It is also the only way to have GPU access during docker build. 

The nvidia runtime not only provides GPU access, it overlays the libcuda file into the container, which is necessary for building things like Tensorflow. So it seems like there is a good case for making runtime-setting during builds easier. An alternative to changing the default runtime is to run a base container and then commit the container as an image after building the necessary libraries, but obviously that is a little unpleasant.

Is it possible to set the runtime in a dockerfile, perhaps as the first line?
```RUNTIME nvidia```

**Comment by thaJeztah** [comment]
I don't think adding an instruction in the Dockerfile is the right approach, having a `--runtime` option on `docker build` would probably more likely be accepted.

@tonistiigi wdyt?

**Comment by AkihiroSuda** [comment]
I think having LABELs makes sense

LABEL org.mobyproject.runtime.recommended=nvidia

or

LABEL org.mobyproject.gpuvendors=nvidia

**Comment by umarcor** [comment]
> I don't think adding an instruction in the Dockerfile is the right approach, having a `--runtime` option on `docker build` would probably more likely be accepted.

Is there already any issue requesting this feature (support for option `--runtime` on `docker build`) or should I open a new one? I've been searching for any, but I couldn't find.

**Comment by AkihiroSuda** [comment]
Could you open an issue in https://github.com/moby/buildkit ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
