### ISSUE TITLE
flag provided but not defined: --oom-score-adj

### ISSUE THREAD

**Issue by yongbuyanqiDK** [moby/moby#37218]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker command:
sudo docker run -e CATTLE_AGENT_IP="10.101.107.38"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher agent http://10.101.107.38:8888/v1/scripts/4F408DA7884CF576B18F:1514678400000:yzmIeFnlHMzC0UTRwB7WNo6LEz8

Docker version:
$sudo docker info
Containers: 1
Images: 77
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: lxc-0.6.8.8
Logging Driver: json-file
Kernel Version: 2.6.32-220.23.2.ali878.el6.x86_64
Operating System: Alibaba Group Enterprise Linux Server release 6.2 (DogTag)
CPUs: 4
AllocCPU: [2 2 2 2]
Total Memory: 7.811 GiB
Name: e010101107038.zmf
ID: GXOS:KZBP:PDWT:D5CW:XGWS:LCRQ:G3HL:VDRD:DWZP:H4NT:4JKK:HT4F
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2018-06-06T11:17:50.444339833+08:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /home/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 SN=c824e4d3-b4a5-490a-957c-59da4f6269a0

**Comment by thaJeztah** [comment]
docker 1.9.1 is a very old version of docker that has reached end of life a long time ago. Also kernel 2.6 is too old to run a current version of docker, so I recommend upgrading both your system, and docker version.

I'll have to close this issue because of the above, but feel free to continue the conversation
