### ISSUE TITLE
docker ps hang

### ISSUE THREAD

**Issue by weiwei04** [moby/moby#37221]
**Description**

docker ps hangs forever, and docker inspect some container also hangs forever.

**Steps to reproduce the issue:**
None

**Describe the results you received:**

docker ps hang forever

use `docker-runc list` I can find 1 container in `create` state, and `docker inspect` this `create` state container will also cause `docker inspect` hang

`docker-runc state` the `create` state container
```
{
  "ociVersion": "1.0.0-rc2-dev",
  "id": "bd03d5ffc924523fcc3834f0a875d939e2cffcb37f29173f8c1acb8e79c47430",
  "pid": 23314,
  "status": "created",
  "bundle": "/run/docker/libcontainerd/bd03d5ffc924523fcc3834f0a875d939e2cffcb37f29173f8c1acb8e79c47430",
  "rootfs": "/data0/docker/overlay2/83f225dcade802b77ae582e6960208ddcd6cbcc8e6369c781d9053dc4a7923ba/merged",
  "created": "2018-06-06T14:53:10.293050714Z"
}
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

this docker is used by kubelet

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 20
 Running: 11
 Paused: 0
 Stopped: 9
Images: 49
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.131-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: kube-node-0.corp.com
ID: 45V7:62GR:YWTX:Q3ZP:7OMH:BDRB:6KVA:B4RN:MVIT:NOXM:XUX6:WTFO
Docker Root Dir: /data0/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zq-david-wang** [comment]
https://github.com/containerd/containerd/issues/1882

The bug should be fixed in containerd 1.02 and above.

**Comment by thaJeztah** [comment]
Docker 17.03.2 has reached end of life in June last year, and hasn't been maintained since; I recommend upgrading to a currently supported version (which also has an updated version of containerd).

I'm closing this issue because of the above, but feel free to continue the conversation

**Comment by weiwei04** [comment]
1. The cases is identical with https://github.com/coreos/bugs/issues/2320, just curious why would this happen.

2. And the cases is different with https://github.com/moby/moby/issues/36010, as in that case, the runc start is hang at try to [read exec.fifo](https://github.com/moby/moby/issues/36010#issuecomment-359119775), in our case the runc init is hang at 

```
openat(4, "exec.fifo", O_WRONLY|O_CLOEXEC
```

waiting for a runc start cmd.

I'll look into myself, anyway thanks @zq-david-wang  your help :)
