### ISSUE TITLE
kernel:unregister_netdevice: waiting for eth0 to become free. Usage count = 1

### ISSUE THREAD

**Issue by pshizhsysu** [moby/moby#37222]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When deleting a pod in k8s cluster, it got stuck in state "Terminating" for long. The host pod located in kept printing error message as follows:

```
kernel:unregister_netdevice: waiting for eth0 to become free. Usage count = 1
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)
```

- Kernel (e.g. `uname -a`):

```
$ uname -a
Linux k2n2 4.4.128-1.el7.elrepo.x86_64 #1 SMP Sat Apr 14 06:57:19 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:

k8s: rpm
docker-engine: rpm

- Docker

version: docker-engine-1.12.6
graph: overlay2
backend-filesystem: xfs(ftype=1)

- Others:

we use calico as network plugin
calico-version: 3.0

**Comment by AkihiroSuda** [comment]
Seems duplicate: https://github.com/moby/moby/issues/5618
