### ISSUE TITLE
Missing APT packages for Ubuntu Bionic

### ISSUE THREAD

**Issue by remram44** [moby/moby#37247]
Your APT repository for Ubuntu Bionic (released 2 months ago) is empty: https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages (compare with Artful: https://download.docker.com/linux/ubuntu/dists/artful/stable/binary-amd64/Packages)

This means that following your installation instructions here doesn't work (`lsb_release -cs` is `bionic`): https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository and that people who updated to Bionic are not receiving updates.

**Comment by blling** [comment]
Could not install docker-ce on ubuntu 18.04 LTS, any solution?

**Comment by blling** [comment]
I install docke-ce 18.1.0 though the binary for now, hope they could fix it as soon as they can:)

**Comment by thaJeztah** [comment]
Docker 18.05 and up are available for Ubuntu 18.04 bionic; 18.05 is in the "edge" release channel, so if you switch to / add the edge release channel, you'll be able to install; https://download.docker.com/linux/ubuntu/dists/bionic/pool/edge/amd64/

**Comment by remram44** [comment]
But Ubuntu 18.04 has now been released. It is a Long-Term-Supported version that people will run on production machines. Why are only 'edge' packages available there?

Why is the 'stable' release channel not available for the latest Ubuntu distribution?

**Comment by thaJeztah** [comment]
Current policy is that new distros or distro-versions are not added to existing Docker CE releases; Ubuntu 18.04 was released after Docker 18.03 became available.

**Comment by remram44** [comment]
That is a very surprising policy that means that users are reliant on your release frequency to be able to install Docker at all. For example, Bionic users have been unable to install stable Docker for 2 months (since distro release).

I really think you might want to revise that policy. What if Docker (or moby, whatever) goes without a release for longer? I am sure it is more convenient to not update the repos, but the fact is that they are broken for extended periods of time, policy or not.

At the very least, if you insist on not creating Docker packages between releases, you can just copy the one from the previous distro (copy Artful package to Bionic repo). That will work most of the time, and also alert users that something is wrong when they try to install/update, rather than disable updates altogether or pretend that no docker-ce package ever existed at all.

**Comment by remram44** [comment]
Also update your doc to state that Ubuntu (current release) is not supported by Docker yet. Own up to your policy! This will save your users headaches, which should be the goal of documentation.

**Comment by thaJeztah** [comment]
I see packages for Bionic (https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/),  as well as Eoan (https://download.docker.com/linux/ubuntu/dists/eoan/pool/stable/amd64/) are now present, so closing this one.
