### ISSUE TITLE
Proposal: container property that indicates docker-compose file from what container was run

### ISSUE THREAD

**Issue by pavelsr** [moby/moby#37257]
It could be useful when transfering docker containers between different hosts - allow to save docker-compose file to not lose env variables, network settings etc without need to make new image via `docker commit`

**Comment by jaswdr** [comment]
@pavelsr for me it's not really clear what you mean, can you add more details?

if you want to transfer containers you can use the `docker save` option, but you say something about changes, so you can create a `Dockerfile` file that has everything that you need and produce the docker image, see this [doc](https://docs.docker.com/develop/develop-images/baseimages/#create-a-simple-parent-image-using-scratch), hopefully this help

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
