### ISSUE TITLE
ARG requires use shell syntax

### ISSUE THREAD

**Issue by eiximenis** [moby/moby#37268]
To use a build argument declared using ARG you have to use the shell syntax of the image that is being built.
This is unfortunate as makes harder to use a single Dockerfile to create both based Windows and Linux images.

**Steps to reproduce the issue:**

Here is a Dockerfile sample that tries to run a custom shell script to install NodeJs in a Docker image:

```
ARG NODE_SCRIPT=/docker-scripts/linux/install-node.sh
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS sdk-with-node
ARG NODE_SCRIPT
WORKDIR /docker-scripts
COPY docker-scripts/ .
RUN ${NODE_SCRIPT}
```

The `COPY docker-scripts/ .` copies both scripts (windows & linux) to install NodeJs. Using a build argument we could choose to run either one or the another.

But this is not possible because under linux we have to use `RUN ${NODE_SCRIPT}` and in Windows the syntax is `RUN %NODE_SCRIPT%`, so you receive an error:

```
Step 9/21 : RUN ${NODE_SCRIPT}
 ---> Running in 454146ab0e37
'${NODE_SCRIPT}' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Service 'webspa' failed to build: The command 'cmd /S /C ${NODE_SCRIPT}' returned a non-zero code: 1
```

As this is a build argument, known in build time, I think Docker should give a way yo substitute it, and pass the known value down to the shell that is running the image.

**Output of `docker version`:**

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:29:00 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 34
 Running: 0
 Paused: 0
 Stopped: 34
Images: 172
Server Version: 18.05.0-ce
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.48)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.88GiB
Name: UFOBOT2-V1
ID: P5YA:5HWL:VYW7:AMDT:ZO7E:3Z53:5N7T:NZME:KQ3E:PX2N:3CBQ:ZX4K
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 34
 System Time: 2018-06-12T11:53:23.5901549+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tmcgee123** [comment]
I found that this occurs because the ARG is replaced with an empty value after the FROM statement.

For example, this will return an empty value when printing out $NODE_ENV

````
ARG NODE_ENV=development
FROM someimage
RUN echo $NODE_ENV
````

With this example, printing out $NODE_ENV will maintain the ARG appropriately for later statements (use build arg or default).

````
ARG NODE_ENV=development
FROM someimage
ARG NODE_ENV=development
RUN echo $NODE_ENV
````

I have not found a way to prevent duplicating the ARG statement.

**Comment by thaJeztah** [comment]
`ARG` is scoped per build-stage; so, in your example:


```Dockerfile
# Before first FROM - so "global" scope 
ARG SOME_ARG=default-value

# the FROM line itself is in the "global" scope
FROM foo:${SOME_ARG} AS stageone

# We're now inside the "stageone" build-stage / scope
# SOME_ARG is not accessible in this scope, unless declared as an arg
# so this will be empty:
RUN echo $SOME_ARG

FROM someimage AS stagetwo

# Declare SOME_ARG here; if no value is set, it will inherit the default
ARG SOME_ARG

# This will print "default-value" (unless overridden by `--build-arg SOME_ARG=myvalue`
RUN echo $SOME_ARG

FROM someimage AS stagethree

# Declare SOME_ARG in stagethree; this time set a default value for this stage
ARG SOME_ARG=mydefault

# This will print "mydefault" (unless overridden by `--build-arg SOME_ARG=myvalue`
RUN echo $SOME_ARG
```

**Comment by thaJeztah** [comment]
I think the reason it may not work in the `microsoft/dotnet` case may be that expansion of `ARG` in a `RUN` instruction is handled by the shell.

So, the `RUN` line in the Dockerfile below;

```Dockerfile
FROM someimage
ARG SOME_ARG=foo
RUN echo $SOME_ARG
```

is equivalent to

```bash
SOME_ARG=foo echo $SOME_ARG
```

I think that image may be using `PowerShell`, so to interpolate the environment-variable, you may need to use `PowerShell` syntax

**Comment by masaeedu** [comment]
@thaJeztah Why is the expansion of ARG in a RUN instruction handled by the shell? Can't it be templated by the Dockerfile?

**Comment by thaJeztah** [comment]
> Can't the shell arguments in the RUN directive be templated by Docker before executing the build step?

No, that would be a breaking change, and would defeat important use-cases for build-args. Build-args were implemented deliberately as environment variables, for example, to use them for `HTTP_PROXY` environment variables during build, without those being persisted in the image. This also means that an `ARG` can be used without it appearing in the `RUN` line in the Dockerfile itself (e.g. `RUN ./some-script.sh`, where `some-script.sh` uses the build-arg).

**Comment by thaJeztah** [comment]
Looking at the discussion and examples above, I don't think there's a bug at hand here, so I'll close this ticket, but feel free to continue the conversation
