### ISSUE TITLE
how to attach the stdin to docker container inputStream by docker client on golang

### ISSUE THREAD

**Issue by vaptu** [moby/moby#37261]
### Env
* os: macos 10.13.4
* docker version : Docker version 18.03.1-ce, build 9ee9f40

### Descrption
* The Main package : [https://github.com/moby/moby/tree/master/client][1]

* My hope the result:
```shell
Interactive shell

php > echo 1;
1
php > 
```

* In fact the result:
```shell
Interaction shell

php > echo 1;


```

Does not seem to be expected to be sent to the container's input stream。

this my code :
[https://gist.github.com/vaptu/10c4c624c6af414f2d41a093ba55300c][2]

How do i do ? 

Thank you very much!

  [1]: https://github.com/moby/moby/tree/master/client
  [2]: https://gist.github.com/vaptu/10c4c624c6af414f2d41a093ba55300c

**Comment by thaJeztah** [comment]
I'd recommend having a look at the docker cli, for example https://github.com/docker/cli/blob/master/cli/command/container/attach.go

**Comment by vaptu** [comment]
thanks
