### ISSUE TITLE
new feature --add automatic user exposing 

### ISSUE THREAD

**Issue by publicocean0** [moby/moby#37260]
for solving in elegant way the problem of same user in volume mounted with container folder ... 
docker solve automatic the problem: add a instruction USER <username> for exposing a user in this way the user have the same id automatically in the host and in the container. In the host will be generated a user docker_<username>. In this way you can also exposing multiple users .

**Comment by thaJeztah** [comment]
It's not entirely clear to me what this feature would do; can you add a bit more information? Perhaps a full example what you think this feature should look like, what it does, and what problem you're trying to solve?

**Comment by publicocean0** [comment]
i m working in docker for few days but i saw it can be a problem when you mount a volume because the user permission inside container can be different in the host (there is no user in the host, different id, ....). All ways for solving it it is a bit cabled in the code. it seams not a generic solution. 
So maybe it is necessary to add a simple solution in docker for solving in more simple generic way this possible problem.

**Comment by thaJeztah** [comment]
I think this is a duplicate / closely related to https://github.com/moby/moby/issues/2259. Let me close this one in favor of that ticket
