### ISSUE TITLE
Sloppy vendoring of docker-distribution

### ISSUE THREAD

**Issue by onlyjob** [moby/moby#37272]
[docker/distribution](https://github.com/docker/distribution/releases) is [semantically versioned](https://semver.org/) library and standalone daemon.

It must be vendored by release tag instead of random commit: 
https://github.com/moby/moby/blob/master/vendor.conf#L68

**Comment by thaJeztah** [comment]
While the distribution repository does releases for the whole product, there's no requirement to also use tagged versions of the packages in that repository.

Using a specific commit is standard practice for go vendoring, so I don't see a specific need to change this; you're welcome to open a PR though to update the vendored package to a tagged release of that release contains all the changes that are needed in this repository

**Comment by onlyjob** [comment]
Relying on semantic versions of dependencies should be a policy.

Docker's abomination of good versioning practices is shocking.

What you call "standard practice" is actually an incompetence regretfully proliferated in Golang community.

The need for proper versioning is not specific but really a best practice. Do you understand what versioning is for? Read https://semver.org/ will you please?

Proper versioning would be very useful to Docker maintainers in downstream GNU/Linux distibutions.

Also please re-open this issue and keep it opened until fixed.

**Comment by thaJeztah** [comment]
I'm aware of SemVer; a single repository can publish multiple Go packages though, not all following the same versioning; this is not a Docker / Moby abomination. 

As mentioned; feel free to open a pull request if there's a specific reason to change the version of the package that's vendored

**Comment by onlyjob** [comment]
I have no time or motivation to fix that nonsense. This is not the only issue of a kind so even if I had a chance to fix it, unfortunately it wouldn't stop the bad practice...

I would much appreciate if you could fix vendoring in accordance to your own vendoring policy.

  https://github.com/moby/moby/blob/master/VENDORING.md

I merely ask to comply with your own policy, specifically with "Vendoring using tags" part.
This is important and this ticket exposes real problem.
