### ISSUE TITLE
Offline form

### ISSUE THREAD

**Issue by swethaiyappan** [moby/moby#37274]
Is there a docker offline version? I am new to this please help me out.

**Comment by thaJeztah** [comment]
You can download RPM and deb packages from https://download.docker.com if you need to install in an airgapped environment; is that what you meant?

**Comment by thaJeztah** [comment]
Could not reliably determine the server's fully qualified domain name

That's a configuration issue if the apache server, but just a warning; is the container actually failing to start?

**Comment by swethaiyappan** [comment]
it just  crashes my cmd everytime i try to run the built image and system totally gets hanged up.I need a solution to this because all my projects are based on php and i couldn't run it but the image is built successfully.

**Comment by swethaiyappan** [comment]
sorry about the lack of information. I am using docker tool box in windows 10 Home.My docker version is 18.03.0-ce, build 0520e24302
My php code is
<?php
$n=$_GET["id"];
mysql_connect("localhost","root","") or die (mysql_error());
mysql_select_db("details") or die (mysql_error());
$sq="select age from names where name='$n'";
$ss=mysql_query($sq) or die(mysql_error());
$num=mysql_num_rows($ss);
if($num==1)
{
while($row=mysql_fetch_array($ss))
{
	$a=$row['age'];

	
	echo"<table ><tr>Age </tr><tr><td>$a</td></tr></table>";
}}
else
{}
?>



<form method=get action=fetch.php>
NAME<input type=text name=id>

<input type=submit value=submit>
</form>


My "Dockerfile" is

FROM php:7.0-apache
COPY . /var/www/html/
EXPOSE 80
CMD echo "ServerName localhost" >> /etc/apache2/apache2.conf
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]


My php code is running fine when tested in localhost directly but when built as image in docker and when attempted to run it says the following:

C:\Windows\System32\php-docker>docker run testphp
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Jun 13 06:20:13.853432 2018] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.25 (Debian) PHP/7.0.30 configured -- resuming normal operations
[Wed Jun 13 06:20:13.855146 2018] [core:notice] [pid 7] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

It will be so helpful if you assist me solve this issue.

**Comment by swethaiyappan** [comment]
My php code:
<?php
$n=$_GET["id"];
mysql_connect("localhost","root","") or die (mysql_error());
mysql_select_db("details") or die (mysql_error());
$sq="select age from names where name='$n'";
$ss=mysql_query($sq) or die(mysql_error());
$num=mysql_num_rows($ss);
if($num==1)
{
while($row=mysql_fetch_array($ss))
{
	$a=$row['age'];

	
	echo"<table ><tr>Age </tr><tr><td>$a</td></tr></table>";
}}
else
{}
?>



<form method=get action=fetch.php>
NAME<input type=text name=id>

<input type=submit value=submit>
</form>

**Comment by swethaiyappan** [comment]
Can any one help me fix this issue please?
