### ISSUE TITLE
Add ability to only build the stages that the target stage depends on

### ISSUE THREAD

**Issue by tristanpemble** [moby/moby#37297]
Given the following Dockerfile:

```dockerfile
FROM busybox AS hello
RUN sleep 15
RUN echo "hello," > /hello.txt

FROM busybox AS world
RUN echo "world!" > /world.txt

FROM busybox AS final
COPY --from=hello /hello.txt /hello.txt
COPY --from=world /world.txt /world.txt
RUN cat /hello.txt && cat /world.txt
```

If I run `docker build --target=world .`, I will be forced to wait for 15 seconds while the `hello` stage is built. I am in a situation where all I really want is to extract that stage without any unneeded stages before it.

An option like `--target-only` would allow Docker to only build the `world` stage (and any other stages it depends on, which is none in this example) and discard `hello` and `final`, since there are no dependencies between them.

**Comment by tristanpemble** [comment]
Another example:

```dockerfile
FROM ubuntu AS build
# ... build the project

FROM ubuntu AS debug
# ... install debug tooling

FROM alpine AS release
COPY --from=build # ...
```

In development, I might want to `--target=debug` to give myself a debug environment to poke around on my built project. However, when building/releasing my production image, I don't want to even bother with the debug stage -- what's the point? It has no impact on the final stage. Being able to skip it would help speed everything up, and I think with proper dependency resolution, `--target-only` would also solve for this use case.

**Comment by thaJeztah** [comment]
Thanks for suggesting! This is actually implemented now with the integration of BuildKit (see this pull request: https://github.com/moby/moby/pull/37151)

BuildKit integration will initially be released as an experimental feature (so won't be used by default, and has to be enabled through a configuration option), and will be part of the upcoming 18.06 release (nightly builds from are already available from download.docker.com in the "nightly" channel.

Let me go ahead and close this issue, but feel free to continue the conversation, and if you give this feature a spin: we welcome feedback if you happen to run into issues :+1:
