### ISSUE TITLE
"unexpected EOF" upon "docker commit" of SQL container

### ISSUE THREAD

**Issue by robertmiles3** [moby/moby#37305]
I am attempting to build a pre-populated `microsoft/mssql-server-linux` container with a backup already restored inside. I start up a base container, restore the backup inside the container, then attempt a `docker commit` in order to save the pre-populated container to an image. However, every time I try it fails with...

```Error response from daemon: Error processing tar file(exit status 1): unexpected EOF```

I do NOT get this error when attempting this on docker stable, but I DO get it every single time on docker edge (18.05.0-ce-mac67 (25042)). Maybe it has something to do with edge using raw files instead of the old qcow2?

FWIW, I have plenty of space inside my docker setup (used about 20GB of 200GB image size, attempting to commit container with ~40GB).

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
