### ISSUE TITLE
Is there any bad effect to shut down the journal of docker filesystem with the param --storage-opt "dm.mkfsarg=-O ^has_journal"

### ISSUE THREAD

**Issue by edgar1992** [moby/moby#37317]
when docker thinpool is full,  I find some containers' filesystem become readonly. However, with the param  `--storage-opt "dm.mkfsarg=-O ^has_journal"` containers no longer become readonly when thinpool is full. But I'm not sure if there is any bad effect to add the param `--storage-opt "dm.mkfsarg=-O ^has_journal"`. Do you have any explanation of this param? THX

**Comment by cpuguy83** [comment]
This option disables the filesystem journal on ext2/3/4. So basially it would mean the container FS has no journal which could lead to data corruption in some cases (like power failure).

Note this is a parameter sent directly to mkfs.

**Comment by edgar1992** [comment]
In cases (like power failure), I think containers are stopped and restart will create new container FS. I wonder whether journal is needed in container FS ?

**Comment by cpuguy83** [comment]
Containers do not get a new fs, and likewise for volumes.

**Comment by edgar1992** [comment]
@cpuguy83 
I still cannot understand when will the journal be used to repair container FS if the container keeps running and never be stopped? (I use docker with k8s, I think once a pod is stopped a new pod will be created, so  there is no need to restart a container)

**Comment by cpuguy83** [comment]
The power failure case is the primary case.

**Comment by cpuguy83** [comment]
Or similar scenarios like a kernel panic.
