### ISSUE TITLE
Can't load "insecure-registries" in daemon.json

### ISSUE THREAD

**Issue by JhoneWangQ** [moby/moby#37321]
**Description**

After modifying daemon.json to add the insecure-registries configuration item to configure the private repository, restarting docker fails

**Steps to reproduce the issue:**
1. Create /etc/docker/daemon.json:
 { "insecure-registries":["10.10.10.1:5000"] }
2.Reload daemon: systemctl daemon-reload
3.Restart docker:systemctl restart docker

then I received following error message：
Jun 21 14:09:17 build-xxx systemd[1]: Starting Docker Application Container Engine...
Jun 21 14:09:17 build-xxx docker-current[120346]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: insecure-registries
Jun 21 14:09:17 build-xxx systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 21 14:09:17 build-xxx systemd[1]: Failed to start Docker Application Container Engine.
Jun 21 14:09:17 build-xxx systemd[1]: Unit docker.service entered failed state.
Jun 21 14:09:17 build-xxx systemd[1]: docker.service failed.

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
#docker info
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 1
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-143604851-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 324.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 44.56 GB
 Metadata Space Used: 1.212 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 7.127 GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Looks like you're running a very old version of the Red Hat fork of Docker (and an obsolete version of CentOS 7).

Docker 1.10 was released more than two years ago, and reached end of life in April 2016

I recommend upgrading your version of CentOS, and Docker (the version you're running has known vulnerabilities); instructions for installing a current version of the official Docker packages can be found here;  https://docs.docker.com/install/linux/docker-ce/centos/

Closing this issue, because of the above, but feel free to continue the conversation

**Comment by JhoneWangQ** [comment]
Thanks for your advise, after updating the version of Docker, it can run normally
