### ISSUE TITLE
Can't launch Jenkins with --platform switch: "cannot download image with operating system "linux" when requesting "windows"."

### ISSUE THREAD

**Issue by SetTrend** [moby/moby#37330]
### Description

I'm running a Windows 10x64 1803 guest OS in VMware Workstation (host: also Windows 10x64 1803).

My VM is set-up to fully support Hyper-V (see [this Microsoft Wiki article](http://social.technet.microsoft.com/wiki/contents/articles/22283.how-to-install-hyper-v-on-vmware-workstation-10.aspx)).

Docker for Windows is set-up with Experimental Features enabled and configured to utilize Windows containers.

When I try to pull/run a Jenkins container by runng the following `Docker` command:

```
docker run -p 8080:8080 jenkinsci/blueocean --platform=linux
```
... I get this error message:

```
cannot download image with operating system "linux" when requesting "windows".
```

### Steps to reproduce the issue:

![docker version](https://user-images.githubusercontent.com/9283914/41775335-cf380b28-7623-11e8-99c5-cab877958554.png)

![docker experimental enabled](https://user-images.githubusercontent.com/9283914/41775339-d318b4f4-7623-11e8-9bc2-fd2e670eafcb.png)

![docker error](https://user-images.githubusercontent.com/9283914/41775409-148d438c-7624-11e8-97f2-6bd7a72c2836.png)

### Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

### Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.1-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.999GiB
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2018-06-22T13:57:34.192805+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Additional environment details (AWS, VirtualBox, physical, etc.):
Hypervisor on host OS (`Windows 10x64, 1803`):
```
  VMware® Workstation 14 Pro
  14.1.2 build-8497320
```

Guest OS: `Windows 10x64, 1803`

### Referenced issues:
#33850
https://github.com/docker/for-win/issues/267

**Comment by thaJeztah** [comment]
does it work if you put `--platform=linux` _before_ the image name? Putting it after the image results in it being passed as arguments for the container itself

**Comment by thaJeztah** [comment]
Based on the above, I don't think there's a bug here, so I'll close this issue, but feel free to continue the conversation

**Comment by SetTrend** [comment]
@thaJeztah : 👍 

Excellent! Gee, my fault 😊

Thanks for pointing me to the right direction!

**Comment by thaJeztah** [comment]
You're welcome! It's easy to miss if you have a lot of flags; you're definitely not the first one accidentally putting one in the wrong position :smile:
