### ISSUE TITLE
No TERM signal in simple perl application, no graceful shutdown

### ISSUE THREAD

**Issue by jonny64** [moby/moby#37341]
**Description**

Moving to docker this fcgi daemon https://github.com/do-/dia.pm/blob/master/Dia/Server/fork.pm
Service restart takes 10 seconds.
Cant debug signal handling via prints
Here is narrowed down case:

**Steps to reproduce the issue:**
1. create signal.pl 

> #!/usr/bin/perl
> 
> use strict;
> use warnings;
> 
> warn 'started OK ';
> 
> $SIG{INT} = $SIG{TERM} = $SIG{HUP} = \&signal_handler;
> 
> warn 'replaced signals OK ';
> 
> sub signal_handler
> {
>     my $signal = shift;
>     warn localtime() . " GOT $signal\n";
> };
> 
> while(1)
> {
>   sleep(1);
> }
and docker.compose.yml

> version: '3'
> services:
>   back:
>     build:
>       context: "./"
>       dockerfile: signal.dockerfile
>     ports:
>      - 11000

2. run docker-compose logs -f in separate window
3. run 

> docker-compose up -d --build --force-recreate
> docker-compose up -d --build --force-recreate

4. observe docker-compose logs -f 

**Describe the results you received:**
```
 docker-compose logs -f
Attaching to signal_back_1
back_1  | started OK  at /var/projects/signal/signal.pl line 6.
back_1  | replaced signals OK  at /var/projects/signal/signal.pl line 10.
signal_back_1 exited with code 137
```
exit code 137 = 129 + 9 KILL

**Describe the results you expected:**
Where is SIGTERM?
Why there is no observable attempt to handle TERM signal?
It should show as

```
docker-compose logs -f
Attaching to signal_back_1
back_1  | started OK  at /var/projects/signal/signal.pl line 6.
back_1  | replaced signals OK  at /var/projects/signal/signal.pl line 10.
back_1  | Mon Jun 25 14:00:56 2018 GOT TERM
signal_back_1 exited with code 137
```
**Additional information you deem important (e.g. issue happens only occasionally):**

perl signal.pl behaves OK: if I run ```kill -9 <pid of signal.pl>``` it prints GOT TERM

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 245
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.843GiB
Name: vm-mgruzdev
ID: 76P7:FOZV:K7YM:FEEP:5HWW:7UFQ:XBLM:VWBV:OVAX:G56P:HTXK:VCGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 srv-docker.cheby.local:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
debian box in VirtualBox, docker-ce engine

**Comment by jonny64** [comment]
here is signal.dockerfile

```
FROM debian:stable

RUN mkdir -p /var/projects/signal

ADD ./signal.pl /var/projects/signal/signal.pl

WORKDIR /var/projects/signal/

CMD /usr/bin/perl /var/projects/signal/signal.pl

EXPOSE 11000

```

**Comment by cpuguy83** [comment]
When CMD is defined in this way, the actual generated command looks like `/bin/sh -c "/usr/bin/perl /var/projects/signal/signal.pl".

Because `/bin/sh` is running as PID 1 it drops all default signal handlers and as such is not forwarding signals to perl.

Suggestion:

```Dockerfile
ENTRYPOINT ["/usr/bin/perl"]
CMD ["/var/projects/signal/signal.pl"]
```

This will make sure that perl is run as PID 1 instead of /bin/sh and is more "correct"... HOWEVER perl may still choose to drop default signal handlers when run as PID 1 (I'm not sure about this... but many things do).

The full solution would be to either ensure perl has signal handlers setup even when run as PID 1 (by setting up your own signal handlers... or testing perl as PID 1)
Alternatively you can run the container with `--init`, which runs [tini](https://github.com/krallin/tini) as PID 1 which is designed as a proper PID 1 for container use cases. Tini will properly reap zombies and forward signals to the  process you told to run (which from your example is perl).

**Comment by jonny64** [comment]
thanks, seems this way works OK

ENTRYPOINT ["/usr/bin/perl"]
CMD ["/var/projects/signal/signal.pl"]
back_1  | Wed Jul  4 07:38:32 2018 GOT TERM

will try on full case

cant use --init in docker-compose file

**Comment by cpuguy83** [comment]
Excellent! Going to close this one since there doesn't seem to be an issue, but please feel free to discuss here.

Thanks!
