### ISSUE TITLE
Removing docker error: Overlay2 Device or resource busy (docker 1.13.1-cs9)

### ISSUE THREAD

**Issue by bamb00** [moby/moby#37367]
**Description**

**Steps to reproduce the issue:**
1. Install docker 1.13.1-cs9 on CentOS 7.4
2. Install Kubernetes v1.9.5 allow all k8s pods in running state
3. Uninstall kubernetes and uninstall docker

**Describe the results you received:**

       "rmtree failed: [Errno 16] Device or resource busy: '/var/lib/docker/overlay2/d231286471a3c96c633a4e337f1592bce79                                           
4bc146ba439f7b928e16199a9da5a-init/merged'"}

**Describe the results you expected:**

Should not get the Device or resource busy error because docker 1.13.1-cs9 + CentOS 7.4 kernel  have the may_detach_mounts set at 1.
 
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
        Client:
	 Version:      1.13.1-cs9
	 API version:  1.27
	 Go version:   go1.7.5
	 Git commit:   1bc62a2
	 Built:        Wed Dec 13 20:56:37 2017
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.13.1-cs9
	 API version:  1.27 (minimum version 1.12)
	 Go version:   go1.7.5
	 Git commit:   1bc62a2
	 Built:        Wed Dec 13 20:56:37 2017
	 OS/Arch:      linux/amd64
	 Experimental: false
```

**Output of `docker info`:**

```
        Containers: 34
	 Running: 21
	 Paused: 0
	 Stopped: 13
	Images: 13
	Server Version: 1.13.1-cs9
	Storage Driver: overlay2
	 Backing Filesystem: xfs
	 Supports d_type: true
	 Native Overlay Diff: true
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: bridge host macvlan null overlay
	Swarm: inactive
	Runtimes: runc
	Default Runtime: runc
	Init Binary: docker-init
	containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
	runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
	init version: 949e6fa
	Security Options:
	 seccomp
	  Profile: default
	Kernel Version: 3.10.0-862.3.3.el7.x86_64
	Operating System: CentOS Linux 7 (Core)
	OSType: linux
	Architecture: x86_64
	CPUs: 32
	Total Memory: 62.76 GiB
	Name: kkambhat-master-01
	ID: YK6K:LYGP:ETFK:7KPU:DOLX:PO4B:37VG:NZUW:QV3U:MTJ5:XFZ6:LVTZ
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): false
	Http Proxy: http://proxy-wsa.esl.cisco.com:80
	Https Proxy: http://proxy-wsa.esl.cisco.com:80
	Registry: https://index.docker.io/v1/
	Experimental: false
	Insecure Registries:
	 127.0.0.0/8
	Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7.4, 7.5
https://docs.docker.com/cs-engine/1.13/release-notes/#cs-engine-1131-cs9-2017-12-13

**Comment by cpuguy83** [comment]
These errors are completely resolved in newer versions of Docker... there are several things involved here.

Please report issues on the cs-engine to Docker support.
Closing because this is not an issue in moby.
Thanks! 🙇 😇

**Comment by bamb00** [comment]
@cpuguy83 Where is the correct place to submit this issue?

**Comment by cpuguy83** [comment]
When you pay for cs-engine you are really paying for support from Docker Inc.
