### ISSUE TITLE
msi installer not working for docker windows container

### ISSUE THREAD

**Issue by Shivani-Bansal** [moby/moby#37387]
I have an msi installer of some custom .net application.
My requirement is to install that application in docker windows container.
I am running a powershell shell scipt in my docker container with below 2 lines:

$argList = '/i SPPA-M3000.msi /qn /l*v "C:\Temp\shiftlog.log"';
Start-Process "msiexec.exe" -ArgumentList $argList -PassThru -Wait;

where SPPA-M3000.msi is the msi of custom application need to be installed.

This script works in normal windows but it's not working in a docker container for windows.

When I run this script, it starts but I do not get the control back in powershell(of container where i am running this script).

I checked the logs...and saw nothig is happening after:
InstallShield 11:23:40: Initializing Engine
InstallShield 11:23:43: Done Initializing...
InstallShield 11:23:43: Registering Msi Server...

I am checking the logs at C:\Temp\shiftlog.log (file which I have mentioned in the command).
Do I need to check some other logs also.If yes,where?

I posted the same issue under docker/for-win.
Someone suggested it's  Windows daemon issue, so I should post it here.
Can someone please help me with this.

diagnostic-Id:D01EDAE6-B753-4483-9F24-5B4B774FC882/2018-07-03_08-27-14
I am using microsoft/aspnet as my base image

docker version :
Client:
Version: 18.03.1-ce
API version: 1.37
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:12:48 2018
OS/Arch: windows/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: 18.03.1-ce
API version: 1.37 (minimum version 1.24)
Go version: go1.9.5
Git commit: 9ee9f40
Built: Thu Apr 26 07:21:42 2018
OS/Arch: windows/amd64
Experimental: false

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
