### ISSUE TITLE
Question: What is the standard method of confining a process inside Docker using Apparmor?

### ISSUE THREAD

**Issue by ShikharJ** [moby/moby#37397]
I wish to run a script inside my docker image, but I was thinking whether there was a way of confining the script within the docker image, as normally one does using `Apparmor` on a system?

**Comment by cpuguy83** [comment]
Docker provides its own apparmor profile. You can also provide your own with the "--security-opt" flag.

Closing since this is not really an issue, but feel free to discuss.

**Comment by ShikharJ** [comment]
@cpuguy83 I understand that docker has that capability. What I wish to know, is that let's say I have a script inside my docker image. Is there a way of restricting what that script can/cannot access, through apparmor? Since I know about `docker-default`, is there a way of placing a custom profile on a directory/script that is existing inside a docker image?

**Comment by cpuguy83** [comment]
@ShikharJ I don't have a suitable system readily available to test... but I would suggest trying to do something (relatively) simple like firing up an Nginx container that loads the Nginx profile which should be provided by the `apparmor-profiles` package.

**Comment by ShikharJ** [comment]
@cpuguy83 I think there has been a misunderstanding. I'll give an example:
```
#include <tunables/global>


profile docker-profiler {
  #include <abstractions/base>

  file,

  deny /bin/** mwkl,
  deny /boot/** mrwklx,
  deny /dev/** mrwklx,
  deny /etc/** mwklx,
  deny /home/** mrwklx,
  deny /lib/** wklx,
  deny /lib64/** mrwklx,
  deny /media/** mrwklx,
  deny /mnt/** mrwklx,
  deny /opt/** mrwklx,
  deny /proc/** mwklx,
  deny /root/** mwklx,
  deny /sbin/** mrwklx,
  deny /srv/** mrwklx,
  deny /tmp/** mrwklx,
  deny /sys/** mrwklx,
  deny /usr/** wkl,

  audit /** rw,

  deny /bin/dash mrwklx,
  deny /bin/sh mrwklx,
  deny /usr/bin/top mrwklx,

  deny mount,

  deny @{PROC}/sysrq-trigger mrwklx,
  deny @{PROC}/mem mrwklx,
  deny @{PROC}/kmem mrwklx,
  deny @{PROC}/kcore mrwklx,

  /home/example/sample.sh Cx -> sample,
  profile sample {
    #include <abstractions/base>
    #include <abstractions/bash>

    /bin/bash ix,
    /dev/tty rw,
    /example/out_cpp w,
    /example/out_java w,
    /example/out_python w,
    /example/test_cpp r,
    /example/test_java r,
    /example/test_python r,
    /example/a.out mr,
    /example/sample.sh r,
    /tmp/** w,
    /usr/bin/python2.7 mr,
    /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java mr,
  }
}
```
Let's say I have the above profile. Now when I load it in `--security-opt`, I wish the permissions to change whenever `./sample.sh` script is run inside the docker image, so that whatever that script accesses (and what is doesn't need), can be restricted further. Is there a way of doing this?

**Comment by cpuguy83** [comment]
@ShikharJ There is nothing that docker is going to do to help this. The only thing it does is let you provide your own profile.
I'm not sure if these can be restricted further once in the container.
