### ISSUE TITLE
docker-crashing again and again 

### ISSUE THREAD

**Issue by jyoti-designworxz** [moby/moby#37405]
I have been trying to setup a project on my local system in which instructions have been given to use docker commands, but unfortunately whenever i try to use the command sudo docker-compose up the containers exit with the following errors:
npm ERR! code ELIFECYCLE
npm ERR! errno1
etc..

I have tried removing the node-modules and re running the docker-compose command also have tried force-recreate option with docker compose but nothing seems to help me out from this mess.
Please help 
TIA

**Comment by johnharris85** [comment]
It's going to be pretty difficult to diagnose with the minimal information provided. Please can you include your Dockerfile and your docker-compose file at least? Also the output of `docker version` and `docker info` please?

**Comment by thaJeztah** [comment]
I'd also recommend searching for the `ELIFECYCLE ` error; Google showed me some results; https://www.google.com/search?q=elifecycle+npm+docker

the error may indicate a permission issue; https://stackoverflow.com/a/30749119/1811501


This one looks interesting; https://github.com/sass/node-sass/issues/2031

**Comment by AkihiroSuda** [comment]
Closable?
