### ISSUE TITLE
Installation of Moby fails on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by erwindemoel** [moby/moby#37414]
I just received my brand new Raspberry Pi Zero W:
https://www.raspberrypi.org/products/raspberry-pi-zero-w/

To start with, I installed NOOBS on it:
https://www.raspberrypi.org/downloads/noobs/

My goal is to connect it to my Azure IoT Hub, so I'm trying to install Azure IoT Edge on it using this tutorial:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm

Unfortunately I get an error when I run the first command in the tutorial:
```
# Download and install the moby-engine
curl -L https://aka.ms/moby-engine-armhf-latest -o moby_engine.deb && sudo dpkg -i ./moby_engine.deb
```

The following error occurs:
```
pi@raspberrypi:~ $ sudo curl -L https://aka.ms/moby-engine-armhf-latest -o moby_engine.deb && sudo dpkg -i ./moby_engine.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    644      0 --:--:-- --:--:-- --:--:--   647
100 15.4M  100 15.4M    0     0  1157k      0  0:00:13  0:00:13 --:--:-- 1314k
(Reading database ... 115462 files and directories currently installed.)
Preparing to unpack ./moby_engine.deb ...
Unpacking moby-engine (1.0.0-1) over (1.0.0-1) ...
Setting up moby-engine (1.0.0-1) ...
Job for docker.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status docker.service" and "journalctl -xe" for details.
docker.service couldn't start.
```

The command "systemctl status docker.service" gives me the following:
```
pi@raspberrypi:~ $ systemctl status docker.service
 docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Sun 2018-07-08 10:11:02 CEST; 4s ago
     Docs: https://docs.docker.com
  Process: 1734 ExecStart=/usr/bin/dockerd -H fd:// (code=dumped, signal=SEGV)
 Main PID: 1734 (code=dumped, signal=SEGV)
      CPU: 278ms

Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
Jul 08 10:11:02 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 08 10:11:02 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
Jul 08 10:11:02 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
```

The command "journalctl -xe" gives me the following:
```
-- Unit docker.socket has begun starting up.
Jul 08 10:11:02 raspberrypi systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
Jul 08 10:11:02 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.socket: Unit entered failed state.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 10:11:02 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
```

I would really appreciate some help, thank you!

**Comment by thaJeztah** [comment]
It's worth trying to check the full logs for the `docker.engine` service, which will likely show more information.

I didn't know those packages existed; those look to be built, and supported by Azure; I would recommend opening a support ticket there

**Comment by erwindemoel** [comment]
Hi thaJeztah, what command can I use to review those logs?

**Comment by thaJeztah** [comment]
Typing from my phone, but I think

    journalctl -u docker.service

Should give you non-truncated output 

Here's a nice tutorial on that https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

**Comment by thaJeztah** [comment]
But I couldn't find a repository in the Azure org on GitHub, so don't know what source it was built from and if they carry specific modifications to the source

**Comment by erwindemoel** [comment]
This is what I get:
```
pi@raspberrypi:~ $ journalctl -u docker.service
-- Logs begin at Thu 2016-11-03 18:16:44 CET, end at Sun 2018-07-08 11:10:41 CEST. --
Jul 08 11:06:22 raspberrypi systemd[1]: Starting Docker Application Container Engine...
Jul 08 11:06:25 raspberrypi systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
Jul 08 11:06:25 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 11:06:25 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 11:06:25 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
Jul 08 11:06:25 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 08 11:06:25 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
Jul 08 11:06:25 raspberrypi systemd[1]: Starting Docker Application Container Engine...
Jul 08 11:06:29 raspberrypi systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
Jul 08 11:06:29 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 11:06:29 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 11:06:29 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
Jul 08 11:06:29 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 08 11:06:29 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
Jul 08 11:06:29 raspberrypi systemd[1]: Starting Docker Application Container Engine...
Jul 08 11:06:33 raspberrypi systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
Jul 08 11:06:33 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 11:06:33 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 11:06:33 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
Jul 08 11:06:34 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 08 11:06:34 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
Jul 08 11:06:34 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
Jul 08 11:06:34 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Jul 08 11:06:34 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Jul 08 11:06:34 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
```

That doesn't give much more information unfortunately.

**Comment by thaJeztah** [comment]
Nope; it's segvaulting: could be a faulty build, or not matching your hardware, or.... (insert options here)

Don't think I can help you here, sorry

**Comment by erwindemoel** [comment]
That's unfortunate, anyone else who might be able to help?

**Comment by thaJeztah** [comment]
Azure support; they know what's in that package, and how it's build. Looks like it's closed source (at least, can't find a repository where it's built from)

**Comment by erwindemoel** [comment]
Thanks, I opened a new issue here:
https://github.com/Azure/iotedge/issues/12

**Comment by reloxx13** [comment]
so, im not using azure and get the same error on my rasbian pi zero w.

> pi@Pi0W-01:~ $ journalctl -u docker
> -- Logs begin at Wed 2018-11-28 20:35:54 CET, end at Wed 2018-11-28 20:40:04 CET. --
> Nov 28 20:36:03 Pi0W-01 systemd[1]: Starting Docker Application Container Engine...
> Nov 28 20:36:08 Pi0W-01 systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 20:39:41 Pi0W-01 systemd[1]: Starting Docker Application Container Engine...
> Nov 28 20:39:42 Pi0W-01 systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 20:39:55 Pi0W-01 systemd[1]: Starting Docker Application Container Engine...
> Nov 28 20:39:59 Pi0W-01 systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
> Nov 28 20:39:59 Pi0W-01 systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 20:39:59 Pi0W-01 systemd[1]: docker.service: Unit entered failed state.
> Nov 28 20:39:59 Pi0W-01 systemd[1]: docker.service: Failed with result 'core-dump'.
> Nov 28 20:39:59 Pi0W-01 systemd[1]: Starting Docker Application Container Engine...
> Nov 28 20:40:00 Pi0W-01 systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
> Nov 28 20:40:00 Pi0W-01 systemd[1]: Failed to start Docker Application Container Engine.
> Nov 28 20:40:00 Pi0W-01 systemd[1]: docker.service: Unit entered failed state.
> Nov 28 20:40:00 Pi0W-01 systemd[1]: docker.service: Failed with result 'core-dump'.
> Nov 28 20:40:02 Pi0W-01 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
> Nov 28 20:40:02 Pi0W-01 systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 20:40:02 Pi0W-01 systemd[1]: Starting Docker Application Container Engine...
> Nov 28 20:40:04 Pi0W-01 systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
> Nov 28 20:40:04 Pi0W-01 systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 20:40:04 Pi0W-01 systemd[1]: docker.service: Unit entered failed state.
> Nov 28 20:40:04 Pi0W-01 systemd[1]: docker.service: Failed with result 'core-dump'.
>

**Comment by thaJeztah** [comment]
@reloxx13 you're likely running into https://github.com/moby/moby/issues/38175

**Comment by reloxx13** [comment]
yep i found it after more googling and issue lookups :D
but i had somuch tabs open and closed i did not find this issue again.

downgraded back and it started.

now the docker image i would like to run just crashes with a "restarting (139)", 139 is a segment fault as well i found out, but i could not find any other logs.

but this is another story :p
