### ISSUE TITLE
client package build failed

### ISSUE THREAD

**Issue by lixianyang** [moby/moby#37447]
**Description**
In my golang project, I used moby/client package. It build failed, because:

```golang
var _ APIClient = &Client{}
```
Client BuildCancel use golang.org/x/net/context
```golang
package client // import "github.com/docker/docker/client"

import (
	"net/url"

	"golang.org/x/net/context"
)

// BuildCancel requests the daemon to cancel ongoing build request
func (cli *Client) BuildCancel(ctx context.Context, id string) error {
	query := url.Values{}
	query.Set("id", id)

	serverResp, err := cli.post(ctx, "/build/cancel", query, nil, nil)
	if err != nil {
		return err
	}
	defer ensureReaderClosed(serverResp)

	return nil
}
```
APIClient BuildCancel use standard context package in client/interface.go

so ... 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for spotting this!

What version of Go are you using? "golang.org/x/net/context" is an alias for "context", so this _should_ work on current versions of go.

We did switch to use "context" everywhere though, so let me open a PR to update this one; it likely slipped through after we changed

**Comment by thaJeztah** [comment]
oh, almost forgot; here's the PR; https://github.com/moby/moby/pull/37449
