### ISSUE TITLE
Buildkit: mistakes in syntax container can lead to dockerd panic

### ISSUE THREAD

**Issue by guillaumerose** [moby/moby#37473]
**Description**

I'm trying to write a buildkit frontend to be use in Dockerfile with `syntax`. While playing with it, at some point, I get: 

**Describe the results you received:**

```
2018-07-16T15:00:56Z docker-ce panic: invalid dispatch: return leaving incoming open
2018-07-16T15:00:56Z docker-ce 
2018-07-16T15:00:56Z docker-ce goroutine 820 [running]:
2018-07-16T15:00:56Z docker-ce github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc4203caee0, 0xc420b190e0)
2018-07-16T15:00:56Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:173 +0xdd4
2018-07-16T15:00:56Z docker-ce github.com/docker/docker/vendor/github.com/moby/buildkit/solver.(*scheduler).loop(0xc4203caee0)
2018-07-16T15:00:56Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:97 +0x163
2018-07-16T15:00:56Z docker-ce created by github.com/docker/docker/vendor/github.com/moby/buildkit/solver.newScheduler
2018-07-16T15:00:56Z docker-ce 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/solver/scheduler.go:28 +0x1d7
```

**Output of `docker version`:**

```
Client:
 Version:      18.06.0-ce-rc3
 API version:  1.38
 Go version:   go1.10.3
 Git commit:   cbfa3d9
 Built:        Thu Jul 12 05:15:46 2018
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Engine:
  Version:      18.06.0-ce-rc3
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   cbfa3d9
  Built:        Thu Jul 12 05:26:13 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by tonistiigi** [comment]
@guillaumerose Can you post a reproducer case please?

**Comment by guillaumerose** [comment]
```Dockerfile
# syntax = guillaumerose/buggyfrontend:latest
web applicationdesigner/nginx
back applicationdesigner/express
db applicationdesigner/mysql
```

and the command: `DOCKER_BUILDKIT=1 docker build -t app .`

The context doesn't matter. The frontend is clearly not right and the output graph is somewhat wrong.

**Comment by tonistiigi** [comment]
@guillaumerose 

I keep getting 

```
time="2018-07-19T05:47:05Z" level=error msg="fatal error: rpc error: code = Unknown desc = objec
t required"
panic: rpc error: code = Unknown desc = object required

goroutine 1 [running]:
main.main()
	/go/src/github.com/docker/applicationdesigner/cmd/frontend/main.go:30 +0xcf
```

with your example but no daemon side panic. Ran it more than a hundred times in a loop.

**Comment by ijc** [comment]
I have, very occasionally (like 2-3 times ever), gotten buildkitd into a state where it ends up with this "return leaving incoming open" symptom. It seemed like it was a state that the daemon got into which, once entered, would then keep happening regardless of the input. Restarting the buildkit backend (I'm using standalone buildkitd, I can't remember if I had to nuke the state dir too) makes it go away and you can then run the exact same builds that were failing before.

I've unfortunately never managed to identify what I was doing which caused the daemon to enter this state, in general it was when I was developing various llb graphs (probably buggy ones). When I've seen this I've initially thought it was my fault so I'd go and mutate the LLB in various ways until I realised it was a backend issue, at which point I've lost the original state which triggered it.

@guillaumerose does your repro work for you from a completely clean slate? I'm not sure where the integrated buildkit keeps it's state, but perhaps take a copy before resetting...

**Comment by guillaumerose** [comment]
@ijc is right, starting from a clean state, it doesn't occur anymore.

**Comment by tonistiigi** [comment]
Closing in favor of #37603 . We managed to get a scheduler trace there.
