### ISSUE TITLE
docker cannot work error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json?all=1: read unix @->/var/run/docker.sock: read: connection reset by peer

### ISSUE THREAD

**Issue by niningxi** [moby/moby#37488]
Description

docker cannot work now,but it used to work well,and commd(eg. docker ps -a ; docker start; dockerd ..etc all useless)

Describe the results you received:
docker ps -a
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json?all=1: read unix @->/var/run/docker.sock: read: connection reset by peer

root@Node1:/home/nxni# dockerd
INFO[2018-07-18T18:33:31.372379394+08:00] libcontainerd: started new docker-containerd process  pid=8934
INFO[0000] starting containerd                           module=containerd revision=773c489c9c1b21a6d78b5c538cd395416ec50f88 version=v1.0.3
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[2018-07-18T18:34:06.373691154+08:00] daemon didn't stop within 15 secs, killing it  module=libcontainerd pid=8934
Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout

Describe the results you expected:
docker working

Additional information you deem important (e.g. issue happens only occasionally):
after reinstall ,the docker still work

Output of docker version:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Output of docker info:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Additional environment details (AWS, VirtualBox, physical, etc.):

**Comment by thaJeztah** [comment]
Looks like containerd doesn't want to start; What distro and distro-version are you running on? (also, kernel version (`uname -a`))?

Is there anything in the logs that shows what happened?

**Comment by matthsena** [comment]
You can try apply **these commands:** 

`sudo service docker stop && \
  sudo rm -rf /var/lib/docker && \
  sudo service docker start
`

**Comment by thaJeztah** [comment]
closing, as this went stale
