### ISSUE TITLE
Swarm service updates stop mid-rollout

### ISSUE THREAD

**Issue by taiidani** [moby/moby#37493]
**Description**

When deploying new versions of a stack (image update only, and we almost exclusively use Stacks) the service(s) will begin to roll out, then halt mid-way with no indication of why it stopped.

* The `ps` output and logs do not indicate that this was `failure_action` behavior.
* The `inspect` output shows the service(s) stuck at "update in progress"
* Further updates to the service(s) (such as a `--force --detach-false --update-failure-action=continue`) exhibit the same behavior, restarting 1-2 containers and then freezing.

Removing the service(s) and recreating from scratch appears to resolve the behavior but some services have shown regressions and are showing it again.

**Steps to reproduce the issue:**

1. `docker stack deploy --prune service_name` a stack with only an update to the image tag.
2. Observe in `ps` that 1-2 replicas restart under the desired image, but no additional replicas roll out.
3. Observe in `inspect` that the service status is frozen at "update in progress".

**Describe the results you received:**

A partial deployment of the updated service(s).

**Describe the results you expected:**

A complete rollout (or rollback) of the new image tag for the service(s).

**Additional information you deem important (e.g. issue happens only occasionally):**

Full output of various troubleshooting attempts:

`ps` output:
```
$ sudo docker service ps api_app
ID                  NAME                IMAGE                                                                              NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
je1jzrpuiu5o        api_app.1           vacasa/api:feature-connect-213-separatetripprotectiondatawhencreatingreservation   ip-10-62-130-221    Running             Running 25 hours ago
xr6ixema5cws         \_ api_app.1       vacasa/api:feature-owner-527-update-common                                         ip-10-62-130-221    Shutdown            Shutdown 25 hours ago
rsnglgd0myav         \_ api_app.1       vacasa/api:feature-fm-83                                                           ip-10-62-131-223    Shutdown            Shutdown 5 days ago
rxccj80wg8jz         \_ api_app.1       vacasa/api:feature-owner-443-use-checkout-date-for-upcoming-reservations           ip-10-62-129-76     Shutdown            Shutdown 5 days ago
wunn3b9qg3x1         \_ api_app.1       vacasa/api:feature-owner-483-return-bad-request                                    ip-10-62-131-137    Shutdown            Shutdown 4 weeks ago
sz4ajn19ga48        api_app.2           vacasa/api:feature-owner-547_fixdefaultcontractforinactiveunit                     ip-10-62-131-223    Running             Running 5 days ago
w7z7bcphlplh         \_ api_app.2       vacasa/api:feature-fm-83                                                           ip-10-62-131-93     Shutdown            Shutdown 5 days ago
y87by84grnk6         \_ api_app.2       vacasa/api:feature-fm-108-rm_db_exception_logging                                  ip-10-62-131-93     Shutdown            Shutdown 5 days ago
yen7vjdkjwxu         \_ api_app.2       vacasa/api:feature-owner-496-confirmation-elock-code                               ip-10-62-131-93     Shutdown            Shutdown 5 days ago
wi92dbipfwn6         \_ api_app.2       vacasa/api:latest                                                                  ip-10-62-131-93     Shutdown            Shutdown 5 days ago
1l6t8kinmzyc        api_app.3           vacasa/api:feature-docker-compose-18-05                                            ip-10-62-131-93     Running             Running 27 hours ago
ypmup10yyp9y         \_ api_app.3       vacasa/api:feature-owner-527-update-common                                         ip-10-62-130-221    Shutdown            Shutdown 5 days ago
uf4zbyn3la2q         \_ api_app.3       vacasa/api:feature-fm-83                                                           ip-10-62-129-76     Shutdown            Shutdown 5 days ago
wo9k470jfp5r         \_ api_app.3       vacasa/api:feature-fm-117-updatecommontoversion65                                  ip-10-62-129-154    Shutdown            Shutdown 5 days ago
xo59pdqdngc1         \_ api_app.3       vacasa/api:feature-owner-496-confirmation-elock-code                               ip-10-62-131-223    Shutdown            Shutdown 5 days ago
```

`inspect` output
```
$ sudo docker service inspect api_app --pretty

ID:             fkkgoct67hlhyz42afulstzx3
Name:           api_app
Labels:
 com.docker.stack.image=vacasa/api:feature-connect-213-separatetripprotectiondatawhencreatingreservation
 com.docker.stack.namespace=api
 traefik.docker.network=front
 traefik.frontend.rule=Host:<redacted>
 traefik.port=80
Service Mode:   Replicated
 Replicas:      3
UpdateStatus:
 State:         updating
 Started:       25 hours ago
 Message:       update in progress
Placement:
 Constraints:   [engine.labels.scope == public]
UpdateConfig:
 Parallelism:   1
 Delay:         3s
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         vacasa/api:feature-connect-213-separatetripprotectiondatawhencreatingreservation@sha256:c937dd5c1f3339e59b5a3f3b8e8eceaad2f72e6ed4f82989b70146b1c3de2b82
 Env:           <redacted>
Resources:
 Reservations:
  Memory:       256MiB
 Limits:
  Memory:       1.25GiB
Networks: front
Endpoint Mode:  vip
Ports:
 PublishedPort = 16661
  Protocol = tcp
  TargetPort = 80
  PublishMode = ingress
```

Possibly related `dockerd` log entry. Note that an `inspect` on the two mentioned task IDs did not succeed.
```
Jul 18 17:52:47 swarm-docker-m01-live dockerd[964]: time="2018-07-18T17:52:47.642148702Z" level=error msg="update failed" error="task timybazu7v0jfj9z3jqj490iw not found while trying to shut it down" module=node node.id=rz842ar2zodc7kc6riejh1ynl task.id=mojbod4z5uk7kmo6wg8ffms2x
```

**Output of `docker version`:**

```
$ sudo docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
$ sudo docker info
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: rz842ar2zodc7kc6riejh1ynl
 Is Manager: true
 ClusterID: zxp0ywegqhrvvm32vx0eklsyd
 Managers: 7
 Nodes: 33
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.62.128.7
 Manager Addresses:
  10.62.128.10:2377
  10.62.128.24:2377
  10.62.128.27:2377
  10.62.128.41:2377
  10.62.128.46:2377
  10.62.128.7:2377
  10.62.128.9:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1011-aws
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.94GiB
Name: swarm-docker-m01-live
ID: FAG2:5WIT:XA3W:FDQZ:HV35:MBL5:TLVH:RT4U:MUBU:2CT4:G2Q4:X2JF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We are working to get output from a `stack` rollout where `failure_action` is "continue" or "rollback" to eliminate that as a possible problem. Will add that to the issue once gathered.

**Comment by ajardan** [comment]
I've seen the same behavior after the upgrade from 18.03.1-ce to 18.06.0-ce

**Comment by taiidani** [comment]
Possibly related: https://github.com/moby/moby/issues/35564

**Comment by thaJeztah** [comment]
@taiidani thanks for reporting; does this happen with any image, or only with a specific image? (also would be great if you could confirm if this is reproducible with `docker service create` / `docker service update` to take `docker stack` handling out of the equation)

**Comment by taiidani** [comment]
We've seen it happen with a number of our different services, some of which have alpine:3.7+PHP7 and others with ubuntu:16.04+PHP5. Healthchecks differ as well -- some have a simple `curl http://localhost/ping` and others have no healthchecks at all.

---

So far we've seen it occur multiple times in both our Staging and Production 18.05 clusters, but it's difficult to reproduce. Once the services get stuck in `update in progress` status then they will consistently show the problem regardless of `stack/service` commands executed upon them until they are `rm`'ed and recreated.

We haven't been able to push a service into the stuck state using raw `service create/update`, although those tests have been manual.

I've been working with our deployment team to add `failure_action: continue` to all the service definitions and then `rm`+recreating them. To date any services we've done that to haven't regressed, but at least one service that we _didn't_ add `failure_action` to ended up regressing about 5 deployments later.

**Comment by taiidani** [comment]
I've been able to get a limited case able to reproduce, but it's still sporadic. I also haven't been successful in transferring the case to a fully scripted CLI action.

1. Install [Portainer](https://github.com/portainer/portainer) - I used v1.18.1
2. Deploy the stack definition below with name of "freeze-test" and a TAG env var of "latest".
3. Rapidly redeploy the stack with a TAG env var of "1.15".
4. Wait a while for the deployment, then run `sudo docker service inspect freeze-test_app --format "{{.UpdateStatus}}"`. It should be stuck on `update in progress` and stay there indefinitely.
5. `sudo docker service update --image nginx:latest freeze-test_app`. If the service is stuck then the update will get through two or three replicas and then halt, never finishing.

The stack definition I used:
```yml
version: '3.3'

services:
  app:
    image: nginx:${TAG:-latest}
    deploy:
      replicas: 5
```

You might have to repeat step 3 a couple times with different TAG values before it gets stuck.

**Comment by matzegebbe** [comment]
Is there a workaround for that? Our applications on the test cluster hangs.

I am using Server Version: 18.06.0-ce. Even recreating the services does not help. I cant see any error messages. I also pulled the image on all nodes manually

``
Service Mode:	Replicated
 Replicas:	1
UpdateStatus:
 State:		updating
 Started:	12 hours ago
 Message:	update in progress

ID                  NAME                 IMAGE                                                           NODE                        DESIRED STATE       CURRENT STATE             ERROR                              PORTS
wnfeyrnk69cn        hexadmin_app.1       repository.xxx.net:8080/xxx/hps/hexmatrix:2.0.4-170                               Running             New 12 hours ago

**Comment by davidcpires** [comment]
We updated our server to 18.06.0-ce and experienced the same issue. Recreating the services does not work for long and the only option is to restart all nodes after every update.

Besides that we are seeing some global replicas with less containers than it should have. Using `docker service ls` those global replicas show 2 containers of 2, on a 3 nodes swarm, for example. Restarting the nodes fix it, but only until the next update (intermittent).

**Comment by taiidani** [comment]
Ah, that reminds me of another note to add — for the service update portion it appears as though if we “docker stop” or “docker kill” the tasks that never updated, they will get recreated using the correct image.

It will still freeze again the next time we update the service, but we’ve used this manual solution a couple times for services with low container counts rather than recreating the whole service.

**Comment by lbguilherme** [comment]
I could reproduce it on a production environment with raw docker service update. Subsequent updates have the same problem and a service with many replicas can end up with 3 or 4 different versions. My updates are changing the image (the nodes need to pull it from a private registry). Every individual update seemed to worked. But at so é point it stops trying, as described.

**Comment by wfelipew** [comment]
We updated our servers from 18.03.01-ce to 18.06.0-ce and experienced the same issue.

**Comment by matzegebbe** [comment]
Are you able to test the 18.06.1-ce? I cant find something in the changelog.

**Comment by cgoeller** [comment]
Same issue here with 18.06.0-ce

**Comment by davidgibbons** [comment]
I'm having the same issue 
```UpdateStatus:
 State:		updating
 Started:	About an hour ago
 Message:	update in progress
```

Looking at the PS output it seems up and running however:
```./docker_cmd.sh dev service ps hub_rails
ID                  NAME                IMAGE  NODE         DESIRED STATE       CURRENT STATE
k8ewqc1ykko1      rails.1         xxx:a589a39   i-0618d39d   Running    Running about an hour ago
jbjivfz5uz9r      rails.2         xxx:a589a39   i-0c2449e3   Running    Running about an hour ago
hxetqhilgdnr      rails.3         xxx:a589a39   i-07c1018b   Running    Running about an hour ago
```

**Comment by drozzy** [comment]
I wasted days on this... before I found this issue.

Yes please I'm running 18.06.0-ce, build 0ffa825

**Comment by lwimmer** [comment]
I'm experiencing the same issue. It seems to be fixed with the manager nodes upgraded to `18.06.1-ce-rc2`, although I did only a few short tests yet.

**Comment by drozzy** [comment]
Just an update - reverting from `18.06.0-ce` to `18.03.1~ce-0~ubuntu` made it work.

**Comment by davidgibbons** [comment]
@lwimmer You still finding it fixed with 18.06.1-ce-rc2? We updated on monday and are still encountering it.

**Comment by lwimmer** [comment]
@davidgibbons It seems to be fixed for us with `18.06.1-ce`.
We still haven't tested very thoroughly but we didn't see this weird behavior yet.

**Comment by lwimmer** [comment]
We have not seen this issue again since the update to `18.06.1-ce`. For us this problem is definitely solved now.

**Comment by thaJeztah** [comment]
Let me go ahead and close this ticket

**Comment by taiidani** [comment]
We just upgraded our Staging cluster to 18.06.1-ce on Wednesday and Production last night. All services that were previously showing the deployment bug behavior appear to all be rolling out consistently again.

Thanks, all!

**Comment by thaJeztah** [comment]
Thanks for confirming @taiidani - that's good news 👍
