### ISSUE TITLE
Creating a new image from scratch without any entrypoint

### ISSUE THREAD

**Issue by ankit4aug** [moby/moby#37503]
Hi,
I am trying to create a image which just have lot of config files in it. I thought I will create a image from scratch and then will copy all the files to a directory. While starting the container I will use mount to mount a volume and then that volume can be used by all different containers to get the config.

Here is my Dockerfile
```
FROM scratch

ADD configurations /configurations
```

And here is the docker run command
docker run --mount source=config,target=/configurations $image

When I am trying to start the image I am getting 
 Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"\": executable file not found in $PATH".

Is it possible to have a container wihtout any entrypoint command?
~

**Comment by cpuguy83** [comment]
You could certainly create one but you couldn't start it, which would make it useless.
There is no container if there is no command to run.

Closing since this is not an issue.
