### ISSUE TITLE
Additional property deployment_strategy is not allowed

### ISSUE THREAD

**Issue by luochen1990** [moby/moby#37501]
**Description**

property deployment_strategy is not allowed in `version: '3.5'` stack.yaml file. but this property is described [here](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#deployment_strategy)

**Steps to reproduce the issue:**
1. vi swarm.yaml
2. add ` deployment_strategy: high_availability` into some service
3. re deploy

**Describe the results you received:**

the following message is printed: 
`deployment_strategy Additional property deployment_strategy is not allowed`

**Describe the results you expected:**

deploy successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:13:43 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 55
 Running: 24
 Paused: 0
 Stopped: 31
Images: 40
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: p99rdegat5p43ingck55rw69b
 Is Manager: true
 ClusterID: r1efjb18oip4txtgir62wj74w
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.240.193.107
 Manager Addresses:
  10.240.193.107:2377
  10.240.193.108:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.youdata.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.17GiB
Name: ydqa1
ID: WAOS:ALJT:NCIS:SGMP:EUGY:3VZ3:I6W2:AVV4:CEE3:SJ4N:5YAT:EZNB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by exic** [comment]
Also on Server Version: 18.03.1-ce.

**Comment by vdemeester** [comment]
Hi @luochen1990 @exic, as describe in the link (`Docker Cloud stack file YAML reference`) : 

> A stack file is a file in YAML format that defines one or more services, similar to a docker-compose.yml file for Docker Compose but with a few extensions.

Those extensions are (or were in the case of cloud), specific to *Docker Cloud*, and thus do not work on `docker/compose` or `docker` cli. If this is a feature request for `docker/compose` it should be on the [compose issue track](https://github.com/docker/compose).

**Comment by thaJeztah** [comment]
Yes; this doesn't seem to be a bug (but due to the Docker Cloud YAML being confused with the Docker Compose YAML); let me go ahead and close, but feel free to continue the conversation

**Comment by luochen1990** [comment]
And I'm still wondering , is there some similar configuration which makes HA possible in docker swarm mode?
