### ISSUE TITLE
Can't delete folder created by myself

### ISSUE THREAD

**Issue by jcabrerazuniga** [moby/moby#37509]
Within a running docker container I am trying to erase a folder I created. However, the OS seems to find that some files are not able to be deleted. During the deletion process it says something like can not find file for several files supposed to be within the folder I am trying to delete. Is there a way to repair this?

I tried:

fsck -f /MyFolder fsck from util-linux 2.27.1 e2fsck 1.42.13 (17-May-2015) fsck.ext2: Is a directory while trying to open /MyFolder

The superblock could not be read or does not describe a valid ext2/ext3/ext4 filesystem. If the device is valid and it really contains an ext2/ext3/ext4 filesystem (and not swap or ufs or something else), then the superblock is corrupt, and you might try running e2fsck with an alternate superblock: e2fsck -b 8193 or e2fsck -b 32768

OTHER error messages:

rm: cannot remove 'MyFolder/webpack.config.js': No such file or directory
rm: cannot remove 'MyFolder/webpack.config.js.bck2': No such file or directory
rm: cannot remove 'MyFolder/webpack.config.js.bck3': No such file or directory

I also noticed that within the MyFolder a lot of size 0 files with names that match the ones it says it can not remove exist. I am trying and trying to delete the folder but it is impossible.

I am using:
FROM ubuntu:16.04
MAINTAINER Jose

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by thaJeztah** [comment]
Closing as this went stale
