### ISSUE TITLE
Parallel make fails. make -j<any number above 1>

### ISSUE THREAD

**Issue by Nadav-Ruskin** [moby/moby#37511]
**Description**
Parallel make fails on WSL (the command `make -j<any number above 1>`).

**Steps to reproduce the issue:**
Currently I am only able to replicate this issue on proprietary projects.

**Describe the results you received:**
Random errors regarding not finding files. Sometimes missing headers, sometimes missing archive files at link time.

**Describe the results you expected:**
`make -j<any number above 1>` doesn't fail.

**Additional information you deem important (e.g. issue happens only occasionally):**
Errors are random.

**Output of `docker version`:**
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 205
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.8GiB
Name: linuxkit-00155dafa100
ID: XRPX:H3W5:3WE7:QW4N:P7DR:RECF:QXCS:HU74:WTZL:JUFH:ABSD:DMOS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 51
 System Time: 2018-07-22T11:00:04.511269Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running Ubuntu 18.04 under WSL, Windows version Microsoft Windows [Version 10.0.17134.165]
I filed a bug report on WSL itself too: https://github.com/Microsoft/WSL/issues/3384#issuecomment-405525074

**Comment by cpuguy83** [comment]
Is "make" being run inside docker, or is it just making use of it?

**Comment by Nadav-Ruskin** [comment]
It is run inside a container.

**Comment by Nadav-Ruskin** [comment]
From https://github.com/Microsoft/WSL/issues/3384#issuecomment-406871214 👍 

>[make -j9] happens inside the container. WSL is not truly involved since running Docker Linux containers on Windows 10 is achieved technically by running a minimal Linux VM using Hyper-V.
The Docker installed in WSL is just the client application that tells the Docker for Windows engine to create the container and execute make -j9 inside.

**Comment by cpuguy83** [comment]
This only fails in Docker? Are you sure the container has everything it needs?

In general, once the process is started Docker is out of the loop as well. It's just a process running on a Linux system.

**Comment by Nadav-Ruskin** [comment]
I have only experienced this on docker. The container must have everything it needs, otherwise `make -j1` would not work. It happens both on my colleague's machine and mine, both have different hardware.
Please consult the WSL thread for further detail.

**Comment by thaJeztah** [comment]
Could this be due to copy-on-write / overlay filesystem?

**Comment by Nadav-Ruskin** [comment]
Is that a question for me? If so, I have no idea. What does that mean?

**Comment by thaJeztah** [comment]
More a general observation; containers use a copy-on-write filesystem (on Docker for Mac / Docker for Windows that's `overlayfs` by default (through the `overlay2` storage driver)); while this generally works ok (other than copy-on-write having a performance impact when doing lots of writes), overlayfs is not fully POSIX compliant, which can affect certain software relying on behavior that's slightly different on overlayfs; some details can be found here; https://docs.docker.com/storage/storagedriver/overlayfs-driver/#limitations-on-overlayfs-compatibility

**Comment by thaJeztah** [comment]
If you know which directories are written to in the container, you could try defining a volume for those directories (e.g., use `-v /some/path`), which makes those paths being stored in a volume, outside of the container's filesystem, and not using a copy-on-write filesystem.

(note that those files will thus not end up in the container itself if you try to `docker commit` the modified container to an image)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
