### ISSUE TITLE
socket leak with port published in host mode

### ISSUE THREAD

**Issue by ajardan** [moby/moby#37518]
**Description**

Since we moved our ports to be published in host mode, we see a socket leak on our load balancers in the swarm cluster.

**Steps to reproduce the issue:**
1. Publish a service port in host mode
2. Make a few hundred thousands requests to the service
3. See used sockets growing

**Describe the results you received:**
# nsenter -t 9231 -n lsof -nPitcp | grep -c ESTAB
236288

**Describe the results you expected:**
The number of ESTABLISHED connections to be much lower.

**Additional information you deem important (e.g. issue happens only occasionally):**

It would be possible that these are real open connections, but then this number would have to drop considerably during the night together with our traffic, which doesn't happen (see the graph)
<img width="1421" alt="screenshot 2018-07-24 14 14 17" src="https://user-images.githubusercontent.com/347796/43137337-e3fb6f28-8f4b-11e8-9dd5-1d09d89ebe74.png">

**Output of `docker version`:**

```
# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
# docker info
Containers: 35
 Running: 5
 Paused: 0
 Stopped: 30
Images: 279
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: b80xs3j231348ife7dsue6i90
 Is Manager: true
 ClusterID: lbqfpif6v1gowlgutpsuxit3l
 Managers: 6
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.16.0.1
 Manager Addresses:
  172.16.0.1:2377
  172.16.0.2:2377
  172.16.0.3:2377
  172.16.0.5:2377
  172.16.0.6:2377
  172.16.0.7:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 46.98GiB
Name: swarm01
ID: MYMY:5UAR:KGJK:FINX:R3OR:6GCD:E2NT:2GTL:AE2T:ZRXF:6EER:BPD4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a 6 node swarm cluster on bare metal, with the service deployed in global mode and ports published in host mode.

**Comment by thaJeztah** [comment]
ping @fcrisciani @ctelfer

**Comment by fcrisciani** [comment]
@ajardan in host mode there is no network namespace around your container, so you are dealing directly with the host namespace.
If they are all marked as established it means that the server or the client ask to close it. 
Also considering that you are running in host mode I guess you are counting all the socket of the host, maybe you can filter per pid, so that you track more accurately your application and see who is holding the majority of them

**Comment by ajardan** [comment]
@fcrisciani the command above (nsenter -t 9231 -n lsof -nPitcp | grep -c ESTAB) does limit the counting to a specific pid in the container namespace that is listening on that specific port. It could be the problem resides on the container side, but we started experiencing this after:
1. Moving to host mode ports
2. Upgrading the version of the used load-balancer

I also was able to create a set of scripts to reproduce the issue here:

https://github.com/ajardan/socket-test/graphs/traffic

And the issue on the load-balancer software is also open here: 

https://github.com/containous/traefik/issues/3263

**Comment by fcrisciani** [comment]
@ajardan there is no network namespace in the case of host mode.
So you should continue the investigation on the client and server side that are not closing the connection

**Comment by thaJeztah** [comment]
@fcrisciani I think there's some naming confusing; this is host mode _publishing_ not `--network=host`. With host mode _publishing_, individual container ports are published (instead of going through the ingress network), similar to `docker run -p <port>:<port>`

**Comment by ajardan** [comment]
@thaJeztah that's absolutely right. Only the ports are published in host mode, so I guess some magic happens on the network level to make it available for the container.

**Comment by fcrisciani** [comment]
@ajardan ok sorry, let's reset the conversation :D
now it's clear how it is deployed, thanks also to @thaJeztah.

@ajardan to make progress, do you have a way to do some test with a different client/server like for example netcat? and see if that socket are getting properly closed? still the fact that the sockets are all established is fishy

**Comment by ajardan** [comment]
@fcrisciani unfortunately that is the only setup I was able to reproduce, and is similar to what we see in production. Maybe it is possible to reproduce it in a simpler way, but I would need to spend some more time experimenting, and I am not sure I will have that in the near future. But if the scripts provided are not suitable, and the issue doesn't have any progress, I might try to set up another test environment in a month or so.

**Comment by ajardan** [comment]
After setting ReadTimeout and WriteTimeout in the load balancer it seems the "leak" is gone, so probably can be closed.

**Comment by thaJeztah** [comment]
Thanks! I'll go ahead and close, but leave a comment if it's not resolved
