### ISSUE TITLE
Swarm mode handles volumes carelessly

### ISSUE THREAD

**Issue by koubas** [moby/moby#37517]
When image contains a VOLUME definition and the path is not explicitly mounted when the service is created, an implicit local volume with random name is created as expected. When the service is removed or downscaled, the implicit local volume is automatically deleted. I find it to be a too radical behavior, especially when in a simple docker container scenario (no swarm) the volumes are always preserved and all operations which would lead to unexpected volume deletion require user to give a consent (`docker system prune -v`, `docker-compose down -v`).

**Steps to reproduce the issue: (a real life postmortem, in fact)**
1. `service create -v /srv/mariadb-data:/var/lib/mariadb -e MYSQL_ROOT_PASSWORD=secret mariadb:10.3` mariadb
2. let the db be used by a service, writing useful data into it
3. realize you mistyped the internal path (should be /var/lib/mysql), but the data are stored in a volume I see in `docker inspect` output, we are safe, right? Let's move them to proper location, downscaling MariaDB to 0 instances first:
`docker service scale maria=0`

**Describe the results you received:**

YOU HAVE NO DATA!! The volume has been automatically deleted.

**Describe the results you expected:**

The volume with a random name should be kept OR service with unmounted volumes should not be allowed to be created (It is probably a misstake when you want to do it)

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 57
 Running: 36
 Paused: 0
 Stopped: 21
Images: 175
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: g1yfo6oyrvfv6mm0v5as10knl
 Is Manager: true
 ClusterID: 1nng3ycgk9r54ufl241x489ao
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.21.2.6
 Manager Addresses:
  10.21.2.6:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-1014-azure
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.769GiB
Name: swarm01n01
ID: JO3Y:JNJW:WVHR:SLFW:DPC4:METL:AA5T:VM3Y:VIQE:W7KU:LIS6:R46J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by koubas** [comment]
@cpuguy83 I would just go to the node, where the container was running and list and manage the volume using `docker volumes xxx`, or simply grab the data from /var/lib/docker/volumes/<id>. Cleaning up of such volumes could be ideally handled by some retention policy, current behavior is equivalent of setting that policy to 0 (days, no. of volumes, whatever...).
Such retention policy would also solve the legitimate throw-away volume cases.

> Note that there is no -v flag for services, only --mount

yeah, my bad, I blindly transformed my case from docker-compose.yml, where I was using a bind mount, sorry. It doesn't change anything on the point.

**Comment by cpuguy83** [comment]
So, outside of this cleanup of anonymous volumes on task exit, swarm does not manage storage currently.

I put together a rough proposal for that here: https://github.com/docker/swarmkit/issues/2168

Ultimately, swarm must clean up anonymous volumes otherwise these will pile up on nodes. This is the same behavior as a normal `docker run --rm` or `docker rm -v`.
Even if we wanted to change this behavior, doing so would be a breaking change.

Because of that, I will close this as won't-fix.
However orchestrating container storage is definitely on the radar as something that swarm is lacking.
