### ISSUE TITLE
Connectivity issues in swarms that span different host networks

### ISSUE THREAD

**Issue by algirdasp** [moby/moby#37536]
**Description**

I have a Docker Swarm Mode cluster running properly. Each host - be it worker or manager - is in to two networks - the internet (eth0), and a private network (eth1). All nodes have their advertise addresses set to their public internet address. I now want to switch all docker traffic to go over the private network eth1. However, removing a worker node from the swarm, and adding it using the advertise address of the private network results in no connectivity between containers running in nodes that advertise their internet address and their private address respectively.

Nodes that advertise their internet address have their containers communicate with each other succesfully over overlay (ingress) networks, and containers running in nodes that advertise their private address can also communicate with each other. However, all connections time out when communicating across these two groups.

All hosts can reach each other over the internet and over the private network properly.

**Steps to reproduce the issue:**
1. Create two DigitalOcean droplets. Enable Private Networking on both, and install Docker Engine 18.06.0-ce on both.
2. Initialize a swarm on the first droplet, advertising it's public internet address.
3. Join the swarm from the second droplet, specifying the private ip address of the first droplet and advertise addr to the private ip address of the second droplet.
4. Create a dummy nginx service that publishes port 80.

**Describe the results you received:**
CURLing `localhost:80` on the first droplet results in nginx dummy page being loaded correctly. CURLing `localhost:80` on the second droplet results in a request that never ends.

**Describe the results you expected:**
CURLing `localhost:80` on both hosts results in the same dummy page being displayed.

**Additional information you deem important (e.g. issue happens only occasionally):**
The same issue happens if a container on each host is run, joined to an attachable overlay network. No traffic can pass between the containers.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

First Droplet:
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: lthvjsuajo2g434u3ec851ccd
 Is Manager: true
 ClusterID: jzbs8gmwhbdy6ckb67jih7f9i
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 206.189.62.11
 Manager Addresses:
  10.135.101.9:2377
  206.189.62.11:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: test-1
ID: OXUE:STVV:P7TI:26VK:U3LO:YQCU:OA7P:OF7O:DSSC:77UQ:NKOB:SZVO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Second droplet:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 95g9svcz0jotngrzht0hwpzfi
 Is Manager: true
 ClusterID: jzbs8gmwhbdy6ckb67jih7f9i
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.135.101.9
 Manager Addresses:
  10.135.101.9:2377
  206.189.62.11:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: test-2
ID: VQNL:RWKF:PCTX:JMUW:BFSI:EBJX:GPWY:OUHN:EX2Y:HUJ7:GGAJ:SZCM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Freshly installed small DigitalOcean droplets, latest Ubuntu 16.04, Docker installed via get.docker.com

**Comment by namirsab** [comment]
@GordonTheTurtle any news regarding this one?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
