### ISSUE TITLE
docker failed to start with "invalid argument" when using overlay on top of ext4 on CentOS7.2

### ISSUE THREAD

**Issue by Light-Gao** [moby/moby#37530]
Newly installation of docker-engine, which `docker version` shows blow:
> [root@host-10-19-20-18 ~]# docker version
> Client:
>  Version:      17.04.0-ce
>  API version:  1.28
>  Go version:   go1.7.5
>  Git commit:   4845c56
>  Built:        Mon Apr  3 18:01:50 2017
>  OS/Arch:      linux/amd64
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

No other extra configuration except for adding `-g /apps/docker` for `dockerd` in `docker.service`.
And then, execute `systemctl start docker`, peng... Errors blow:

> -- 
> -- The result is failed.
> 7月 26 12:38:06 host-10-19-20-18 systemd[1]: Unit docker.service entered failed state.
> 7月 26 12:38:06 host-10-19-20-18 systemd[1]: docker.service failed.
> 7月 26 12:38:06 host-10-19-20-18 polkitd[877]: Unregistered Authentication Agent for unix-process:31254:6014364 (system bus name :1.639, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale zh_CN.U
> 7月 26 12:38:06 host-10-19-20-18 systemd[1]: docker.service holdoff time over, scheduling restart.
> 7月 26 12:38:06 host-10-19-20-18 systemd[1]: Starting Docker Application Container Engine...
> -- Subject: Unit docker.service has begun start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> -- 
> -- Unit docker.service has begun starting up.
> 7月 26 12:38:06 host-10-19-20-18 dockerd[31337]: time="2018-07-26T12:38:06.946582764+08:00" level=info msg="libcontainerd: new containerd process, pid: 31347"
> 7月 26 12:38:07 host-10-19-20-18 dockerd[31337]: time="2018-07-26T12:38:07.951849623+08:00" level=error msg="[graphdriver] prior storage driver overlay failed: invalid argument"
> 7月 26 12:38:07 host-10-19-20-18 dockerd[31337]: Error starting daemon: error initializing graphdriver: invalid argument
> 7月 26 12:38:07 host-10-19-20-18 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
> 7月 26 12:38:07 host-10-19-20-18 systemd[1]: Failed to start Docker Application Container Engine.
> -- Subject: Unit docker.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> -- 
> -- Unit docker.service has failed.

Configuration in docker.service and file system information below:
[root@host-10-19-20-18 ~]# systemctl cat docker
# /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -g /apps/docker
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
[root@host-10-19-20-18 ~]# 
[root@host-10-19-20-18 ~]# 
[root@host-10-19-20-18 ~]# 
[root@host-10-19-20-18 ~]# df -Th
文件系统                类型      容量  已用  可用 已用% 挂载点
/dev/mapper/centos-root xfs        36G  2.9G   33G    9% /
devtmpfs                devtmpfs   16G     0   16G    0% /dev
tmpfs                   tmpfs      16G     0   16G    0% /dev/shm
tmpfs                   tmpfs      16G  8.5M   16G    1% /run
tmpfs                   tmpfs      16G     0   16G    0% /sys/fs/cgroup
/dev/vda1               xfs       497M  110M  388M   22% /boot
/dev/vdc                ext4      197G  115G   73G   62% /apps
tmpfs                   tmpfs     3.2G     0  3.2G    0% /run/user/806
tmpfs                   tmpfs     3.2G     0  3.2G    0% /run/user/0
[root@host-10-19-20-18 ~]# 

Someone helps me please...
I will be in touch anytime, thanks!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
