### ISSUE TITLE
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by ackris** [moby/moby#37531]
Hi

We have installed Docker EE `17.06.2-ee-10` on three RHEL 7.4 (maipo) servers. When we executed ` docker version` command on 2 servers, it showed the expected output. But on the third server, it is outputting the following error. 

`docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory `

`uname -r: 3.10.0-693.5.2.el7.x86_64`

```
Client: Docker Enterprise Edition (EE) 2.0
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:38:41 2018
 OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:40:03 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

The above `docker version` output is from the servers which are showing intended o/p. 

We have tried to find a reason for this particular error by browsing multiple stackoverflow forums, but to no avail. Is there a solution for this error? 

The intended output should display proper docker outputs. 

Regards & Thanks in advance
Aditya

**Comment by vijaymuddu** [comment]
Hi 

Did you found any solutions i am also facing same issue with centos 7 and docker , same things works fine with ubuntu

**Comment by cwgem** [comment]
Curious, what's the output of `rpm -qa | grep libltdl7` on that third server? If it comes up blank you may want to try yum installing it.

**Comment by vijaymuddu** [comment]
The issue was resolved by apt-get install -y libltdl7 on container

**Comment by myroslavmail** [comment]
what If I'm working from Jenkins? How should I fix it via Jenkinsfile (or Dockerfile which I may also use via Jenkins) ?

**Comment by cpuguy83** [comment]
ping @seemethere 
Is there a missing dep on the rhel rpm manifiest?

**Comment by seemethere** [comment]
@ackris Are you able to update to the latest version of `17.06` and see if the problem still exists? If I remember correctly we're all the way up to `17.06.2-ee-21`.

**Comment by thaJeztah** [comment]
I wonder if this is still the case on 17.06.2-ee-20 or above; https://github.com/docker/cli/pull/1691 was backported to 17.06.2-ee20, and (I think) removes the dependency on libltdl

**Comment by thaJeztah** [comment]
Confirmed that this is no longer a dependency for current versions of Docker EE 17.06; let me close this issue, but feel free to continue the conversation
