### ISSUE TITLE
[feature request] FIPS mode support for docker registry

### ISSUE THREAD

**Issue by haoqing0110** [moby/moby#37554]
**Description**

In docker registry, the [configuration ](https://docs.docker.com/registry/configuration/#override-specific-configuration-options) file doesn't support FIPS mode. It will be good if docker registry can support FIPS mode, as FIPS is an important security standards. 

**Additional information you deem important (e.g. issue happens only occasionally):**

From https://blog.docker.com/2017/06/docker-ee-is-now-in-process-for-fips-140-2/, looks like docker is considering FIPS compliance, but I can't find any update about the process. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This should probably be opened in https://github.com/distribution/distribution, where the open source registry code is maintained.

I'll close this ticket here
