### ISSUE TITLE
Docker Swarm: Calico node pod is unhealthy

### ISSUE THREAD

**Issue by ackris** [moby/moby#37579]
Hi

### Details:

`OS: RHEL 7.4`

`uname -r: 3.10.0-693.el7.x86_64`

**Docker version**

```
Client: Docker Enterprise Edition (EE) 2.0
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:38:41 2018
 OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:40:03 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
**Error**
`Calico-node pod is unhealthy: %!s(<nil>)`

I am trying to join a node to docker swarm cluster as a worker. But i'm getting the aformntioned error in health status check. As a result, the node is unable to join the swarm cluster. 

The desired result must be successful node addition to the swarm cluster. 

Regards
Aditya

**Comment by thaJeztah** [comment]
Thanks for reporting; it looks like you're setting up the Docker EE platform (with UCP Universal Control Plane and Kubernetes); https://docs.docker.com/ee/end-to-end-install/

This error looks related to Kubernetes, and is coming from UCP, which is not open source, and not maintained in this repository.

Could you contact support@docker.com instead?

**Comment by ackris** [comment]
The reason for the aforementioned error:

`rp_filter` was set to `2`. Its value must be either `1` or `0`. rp_filter can be found in `/proc/sys/net/ipv4/conf/all`.

I hope this would help people in addressing this error. 

Regards
