### ISSUE TITLE
Kubelet is unhealthy: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by ackris** [moby/moby#37578]
`OS: RHEL 7.4 `
`uname -r: 3.10.0-693.el7.x86_64`

**docker version**
```
Client: Docker Enterprise Edition (EE) 2.0
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:38:41 2018
 OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:40:03 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

`Error:`
`Kubelet is unhealthy: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

I am trying to join a node to swarm cluster as a worker node, but I am getting the aforementioned error. Did anyone face this issue?

Expected result should be node must successfully added to the swarm cluster.

Regards

**Comment by thaJeztah** [comment]
Looks related to your other ticket (https://github.com/moby/moby/issues/37579#issuecomment-409902341)


It looks like you're setting up the Docker EE platform (with UCP Universal Control Plane and Kubernetes); https://docs.docker.com/ee/end-to-end-install/

This error looks related to Kubernetes, and is coming from UCP, which is not open source, and not maintained in this repository.

Could you contact support@docker.com instead?

Feel free to continue the conversation after I closed
