### ISSUE TITLE
Error processing tar file(exit status 1): unexpected EOF adding an 8G file (8G - 1 byte is ok)

### ISSUE THREAD

**Issue by djs55** [moby/moby#37581]
**Description**

This was first reported on Mac by @flagbug: https://github.com/docker/for-mac/issues/2388#issuecomment-409532891 but I believe it is a generic problem with the engine, not something specific to Mac.

To reproduce:

```
/tmp/test # cat Dockerfile
FROM ubuntu:18.04

RUN head -c 8G </dev/urandom >file

/tmp/test # docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu:18.04
 ---> 735f80812f90
Step 2/2 : RUN head -c 8G </dev/urandom >file
 ---> Running in 4debf740eb97
Error processing tar file(exit status 1): unexpected EOF
```

**Describe the results you received:**

The error "Error processing tar file(exit status 1): unexpected EOF"

**Describe the results you expected:**

The build should complete successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

The logs have:
```
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.598573889Z" level=debug msg="Tar with options on /var/lib/docker/overlay2/f89859e8af0b77222f209807333da05295ee03d1a9e2255895cf10ec57cce417/diff" storage-driver=overlay2
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.602482132Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/278e40f6fc45ea9828cb090bf339b4f85561fa03dd2446626c3d9b6a272d8f5b/diff" storage-driver=overlay2
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.750205351Z" level=debug msg="Cleaning up layer 278e40f6fc45ea9828cb090bf339b4f85561fa03dd2446626c3d9b6a272d8f5b: Error processing tar file(exit status 1): unexpected EOF"
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.751542982Z" level=error msg="Can't add file /var/lib/docker/overlay2/f89859e8af0b77222f209807333da05295ee03d1a9e2255895cf10ec57cce417/diff/file to tar: io: read/write on closed pipe"
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.751599637Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
```

If I switch the command to `head -c 8589934591 </dev/urandom >file` i.e. 8GiB - 1 byte then it succeeds correctly. 

I suspect this is same underlying issue as https://github.com/moby/moby/issues/37305 where a `microsoft/mssql-server-linux` database backup is restored and then `docker commit`ted. I suspect the root cause is that an individual file exceeds 8GiB, which is a limit in the tar header. According to [wikipedia](https://en.wikipedia.org/wiki/Tar_(computing)):

> Thus although there are 12 bytes reserved for storing the file size, only 11 octal digits can be stored. This gives a maximum file size of 8 gigabytes on archived files. To overcome this limitation, star in 2001 introduced a base-256 coding that is indicated by setting the high-order bit of the leftmost byte of a numeric field. GNU-tar and BSD-tar followed this idea. Additionally, versions of tar from before the first POSIX standard from 1988 pad the values with spaces instead of zeroes.

**Output of `docker version`:**

```
/tmp/test # docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:04:40 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
/tmp/test # docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: UFJG:WKJW:OBVN:JP4C:NXIX:YJ7Z:JHQS:AT4L:RO2C:MN7I:YMUW:EQN7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 68
 System Time: 2018-08-02T14:49:58.963009758Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by sudo-bmitch** [comment]
I can reproduce this error on a native Linux install, so it's not exclusive to MacOS. I've seen a bunch of questions in the last few days on StackOverflow on this, which leads me to believe it may be a bug in the current release that got introduced recently and it starting to hit a lot of users:

https://stackoverflow.com/questions/51875878/error-processing-tar-file-exit-status-1-unexpected-eof-when-building-with-doc
https://stackoverflow.com/questions/51872918/docker-add-folder-with-zip-files-result-in-error-processing-tar-fileexit-status
https://stackoverflow.com/questions/51857021/docker-build-crashes-when-i-download-large-file-40gb-on-ubuntu-16-04
https://stackoverflow.com/questions/51855702/adding-large-file-to-docker-build-gives-eof-exception

**Comment by bjholmes23** [comment]
I see this on Windows as well, just recently started happening. Version 18.06.0-ce-win72 (19098)

**Comment by StefanScherer** [comment]
Don‘t know if it‘s related, but some months ago e struggled in Packer (also a Go binary) creating huge tar files with files >8GB and solved it by setting some tar options https://github.com/hashicorp/packer/pull/6084

**Comment by thaJeztah** [comment]
ping @tonistiigi @dmcgowan

**Comment by bjholmes23** [comment]
Just following up. Rolled back my docker from `Version 18.06.0-ce-win72 (19098)` to `Version 18.03.1-ce-win65 (17513)`  and my builds stopped failing.

**Comment by Tim-Schwalbe** [comment]
Same for me on Ubuntu with rolling back to 18.03.1~ce-0~ubuntu.

**Comment by jedie** [comment]
Same here :( 

But not on every machine: A **Ubuntu 16.04** with **18.06.1-ce** running quietly so far.

A **Ubuntu 18.04** machine with **18.06.1-ce** run into the same problem: It created a /`tmp/tmpxxxxx` file that gets bigger and bigger until: `OSError: [Errno 28] No space left on device` is raised.

I have made a roll back to `18.03.1~ce~3-0~ubuntu` but this **doesn't** solve the problem!

Any idea?

**Comment by rjudin** [comment]
Same for **Debian** version, rolled back:
 - from `docker-ce=18.06.1~ce~3-0~debian `
 - to `docker-ce=18.03.1~ce-0~debian`

**Comment by dgageot** [comment]
I ran a few tests here:

+ The issue can be reproduced on `18.06.1` and `18.06.0`
+ Can't reproduce on `18.03.1`, `17.12.1` and `17.03.2`

However, it could also be reproduced on a custom build of `17.03.2` built with `go 1.10.2` instead of the version that was used to build the official `17.03.2` (`go 1.7.5`)

It looks like it could come from the go version rather than docker version.

**Comment by thaJeztah** [comment]
I recall we ran into issues with the archive package when updating to Go 1.10, and some changes were needed for that; initially it was attempted to remove the vendored version of pkg/archive, but that cause issues due to breaking changes in Golang, and that was reverted for the time being (all as part of https://github.com/moby/moby/pull/35739)


ping @tonistiigi @kolyshkin PTAL

**Comment by tonistiigi** [comment]
cc @dsnet

**Comment by kolyshkin** [comment]
USTAR tar format has a limitation of 8GiB file size, but from the first glance we're using (and explicitly setting since go 1.10) `tar.FormatPAX` everywhere.

**Comment by the-destro** [comment]
I wonder if this is still happening under 1.11.

**Comment by dgageot** [comment]
We spend the whole day debugging the code with @beaufortfrancois and it looks like the problem is coming from the usage of asm.NewInputTarStream [here](https://github.com/moby/moby/blob/b3e9f7b13b0f0c414fa6253e1f17a86b2cff68b5/layer/layer_store.go#L249)

If the reader is not wrapped in an InputTarStream. everything is alright.

I managed to reproduce the issue out of docker codebase. I'll post the sources a bit later.

**Comment by kolyshkin** [comment]
> I wonder if this is still happening under 1.11.

Yes, with go-1.11 (and the archive/tar from its stdlib) it's the same:

> Error processing tar file(exit status 1): unexpected EOF

**Comment by dgageot** [comment]
Comes out  `github.com/vbatts/tar-split` vendors a copy of `archive/tar.Reader` that is outdated and can't deal with large files

**Comment by dgageot** [comment]
Here's the code to reproduce: https://gist.github.com/dgageot/0007b4cbfa08f7cf95e93ba0db3bc12a

**Comment by dgageot** [comment]
ping @thaJeztah

**Comment by vbatts** [comment]
cc @vbatts 😜

**Comment by kolyshkin** [comment]
> Comes out github.com/vbatts/tar-split vendors a copy of archive/tar.Reader that is outdated and can't deal with large files
 
Why was it working before (in e.g. docker-ce-18.03, as per https://github.com/moby/moby/issues/37581#issuecomment-414442133)?

**Comment by dgageot** [comment]
@kolyshkin More precisely: since docker uses golang to produce a tarball and vbatts/tar-split to read it, both must be in sync in terms of supporting tar features. 

When 18.03 started using vbatts/tar-split, it was ok as long as go version was not updated.
When Docker 18.06 started using 1.10, then a difference between the tar writer and the tar reader was introduced regarding how they handle large files.

**Comment by dsnet** [comment]
Does anyone have a binary dump of first few kilobytes of the tar archive? Pre-go1.10 did have some bugs where it would generate hybrid tar-files that were simultaneously both GNU and PAX, which is invalid. That condition may confuse readers. Hard to say without a binary dump. 

Even better, if someone can reproduce this with a giant file with 8GiB of zeros, they can gzip (or xz or bzip2 or zstd) that up and attach it (should be small).

**Comment by thaJeztah** [comment]
Thanks for digging into this one @dgageot 🤗❤️

**Comment by dgageot** [comment]
@dsnet I couldn't reproduce it with a 8Gb file full of zeros

**Comment by dsnet** [comment]
Interesting, so the bug triggers if the input is random data, but not with zeros? Is there a compression step before the data is written to a tar file?

**Comment by kolyshkin** [comment]
OK, I think I have a fix for both the original issue (as described in https://github.com/moby/moby/issues/37581#issue-347048410), as well as for 8gb-zeroes issue (see comments above). Both seem to be fixed by https://github.com/vbatts/tar-split/pull/48.

I have a test branch at https://github.com/kolyshkin/moby/tree/fix-8gb which can be used for testing.

**Comment by kolyshkin** [comment]
The 8gb-zeroes issue I mentioned can be reproduced like this:
```sh
mkdir test && cd test && cat << EOF > Dockerfile
FROM busybox
RUN dd if=/dev/zero of=/zerofile bs=1M count=9K
<<EOF
docker build -t test .
```

(and I forgot what kind of error it gives but there is some error, caused by the fact that tar-split (erroneously) tries to encapsulate 8gb of zero data into json and it fails at 2GB or so).

**Comment by the-destro** [comment]
Awesome to see that there is a fix in master. I hope there will be a release soon.....

**Comment by thaJeztah** [comment]
@bitsofinfo it will be in 18.09; https://github.com/docker/engine/pull/46. There's a backport for 18.06, but that depends if there will be another patch release for 18.06 (that has not yet been decided)
