### ISSUE TITLE
[Enhancement] add buildkit enable nob in docker daemon

### ISSUE THREAD

**Issue by AntaresS** [moby/moby#37587]
**Description**
As a user, I want to be able to set a field in `daemon.json` to turn on buildkit instead of turning it on by defaut from `dockerd --experimental`

cc @tiborvass @andrewhsu 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Enabling experimental enables buildkit, but by default, the legacy builder will still be used, unless you set the `DOCKER_BUILDKIT=1` environment variable on the client so that it uses the buildkit API

**Comment by AntaresS** [comment]
@thaJeztah Yes. We were talking about to add a separate nob to enable/disable buildkit apart from experimental mode with @tiborvass and @dhiltgen. This issue is meant for tracking. I'm working on it right now.

**Comment by thaJeztah** [comment]
Ah; right

**Comment by AntaresS** [comment]
Closed since the PR was merged  https://github.com/moby/moby/pull/37593
