### ISSUE TITLE
Docker logging in multi threaded application

### ISSUE THREAD

**Issue by HarishHothi** [moby/moby#37599]
Hi all,
Docker recommend application to log in **STDOUT/STDERRR**. In multi threaded application environment, If two thread simultaneously logs to **STDOUT/STDERR** then is there any chance of logs get jumbled up? Or docker logging driver will take care of it? Docker logging driver is default i.e json-file.

**Comment by cpuguy83** [comment]
Docker won't jumble them, but you would still need to synchronize writes to the output stream.

**Comment by HarishHothi** [comment]
Thank you @cpuguy83
