### ISSUE TITLE
docke-containerd  daemon is not running but dockerd is running

### ISSUE THREAD

**Issue by ryanlyy** [moby/moby#37598]
**Description**
in some case, docker-containerd is not running. but dockerd is still running and docker ps still show some containers are up too. seems like dockerd does not restart docker-containerd daemon.

I read the code of monitorConnection thread. in this function, only r.shutdownContext.Done case, thread will exit. but in this thread, it just checks r.daemonPid is running or not, if there is process which pid is r.daemonPid, then it will continue. is it possible there is race condition whatever reason docker-containerd exits and before it is restarted by dockerd, there is another process started and by chance its pid is r.daemonPid. in this kind of case, dockerd will not start containerd any more. so for safety in order to check docker-containers is up or not, it is better to use docker-containerd name.

or is there any other case to block dockerd start containerd?

**Steps to reproduce the issue:**
can't reproduce it. some time, when I found kubernetes can't term a pod, and then I tried to rm it forcely but failed to do it. checked there is no docker-containterd running.

of course systemctl restart docker can recover it. but we can't always depend on restart, we need to find why containerd is not running.

**Describe the results you received:**
docker-containerd is not running

**Describe the results you expected:**
docker-containerd shall be running in whatever case if dockerd is running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e-unsupported
 Built:        Wed Mar 29 15:42:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e-unsupported
 Built:        Wed Mar 29 15:42:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]#
```

**Output of `docker info`:**

```
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e-unsupported
 Built:        Wed Mar 29 15:42:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e-unsupported
 Built:        Wed Mar 29 15:42:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker info
Containers: 196
 Running: 104
 Paused: 0
 Stopped: 92
Images: 56
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 4ab9917febca54791c5f071a9d1f404867857fcc)
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.42 GiB
Name: cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1
ID: TG3B:RKO3:CGJY:6PJ6:3E4Q:KAXO:JTOI:PQUI:4EFD:DR3J:YBXR:PF62
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 mncc-ntas-ft-docker-local.esisoj70.emea.nsn-net.net
 stas-change-registry.dynamic.nsn-net.net:5000
 ttas-change-registry.dynamic.nsn-net.net:5000
 itas-change-registry.dynamic.nsn-net.net:5000
 ktas-change-registry.dynamic.nsn-net.net:5000
 mtas-change-registry.dynamic.nsn-net.net:5000
 ntas-change-registry.dynamic.nsn-net.net:5000
 utas-change-registry.dynamic.nsn-net.net:5000
 gtas-change-registry.dynamic.nsn-net.net:5000
 qtas-change-registry.dynamic.nsn-net.net:5000
 vtas-change-registry.dynamic.nsn-net.net:5000
 otas-change-registry.dynamic.nsn-net.net:5000
 wtas-change-registry.dynamic.nsn-net.net:5000
 dtas-change-registry.dynamic.nsn-net.net:5000
 ztas-change-registry.dynamic.nsn-net.net:5000
 btas-change-registry.dynamic.nsn-net.net:5000
 jtas-change-registry.dynamic.nsn-net.net:5000
 ltas-change-registry.dynamic.nsn-net.net:5000
 rtas-change-registry.dynamic.nsn-net.net:5000
 xtas-change-registry.dynamic.nsn-net.net:5000
 ytas-change-registry.dynamic.nsn-net.net:5000
 atas-change-registry.dynamic.nsn-net.net:5000
 ctas-change-registry.dynamic.nsn-net.net:5000
 etas-change-registry.dynamic.nsn-net.net:5000
 ftas-change-registry.dynamic.nsn-net.net:5000
 htas-change-registry.dynamic.nsn-net.net:5000
 ptas-change-registry.dynamic.nsn-net.net:5000
 127.0.0.0/8
Live Restore Enabled: false
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
openstack VM

**Comment by ryanlyy** [comment]
just found this issue fired again, checked docker-containerd, it is in <defunct> state.
 3872 ?        Ssl  123:58 /usr/bin/dockerd -H fd:// -H tcp://172.24.16.104:2375 --disable-legacy-registry --max-concurrent-downloads 10 --max-concurrent-uploads 10 -g /var/lib/do
32066 ?        Zs     0:00  \_ [docker-containe] <defunct>

In this case, kill -s 0 32066 will return that pid exists then dockerd will not restart it.

**Comment by ryanlyy** [comment]
in this case:
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker exec -ti def67d476718 sh
rpc error: code = 14 desc = grpc: the connection is unavailable
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker exec -ti e932fdd8df2f sh
rpc error: code = 14 desc = grpc: the connection is unavailable
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]# docker stop e932fdd8df2f
Error response from daemon: Cannot stop container e932fdd8df2f: Cannot kill container e932fdd8df2f524f7c698dfdacfc7173e638b4846e9b2469a83214bd4320e024: rpc error: code = 14 desc = grpc: the connection is unavailable
[root@cbam-a9f9df9be9ac4dbfa908c194644-oam-node-1 ~]#

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
