### ISSUE TITLE
Swarm service instances won't restart when mode global

### ISSUE THREAD

**Issue by unglaublicherdude** [moby/moby#37608]
**Description**

We are running several services with mode global. Killing one instance of the service should lead to a restart of this instance. But atm the instances are not restarted for mode global, mode replicated is working fine.

There is no healthcheck in the image or compose files.

**Steps to reproduce the issue:**
1. deploy a service with mode global and a constraint 
2. kill an instance of the service on one node

**Describe the results you received:**

The service instance is gone and won't restart.

**Describe the results you expected:**

The service instance should restart like it does, when using mode replicated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: convoy local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 19qu31xbj2dfx9jf49f3k8hq6
 Is Manager: true
 ClusterID: 0j4acqvh7ce9579ra5wiajbrl
 Managers: 3
 Nodes: 19
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.10.12.114
 Manager Addresses:
  10.10.12.114:2377
  10.10.12.115:2377
  10.10.12.116:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: seclab-apphost-manager-gdata-001
ID: 5PLC:5R7B:BE67:5DKP:KWTR:3DGJ:ATHC:WNPJ:FRZE:HYRG:HUPR:GQEQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We are running a docker swarm with 19 nodes. 3 manager nodes and the rest as worker nodes. All nodes are on docker-version 18.06.0-ce.

I wrote compose files to test the behaviour.

Not working
```yaml
version: '3.7'
services:
  whoami:
    image: jwilder/whoami
    deploy:
      mode: global
      placement:
        constraints:
         - node.role == worker
```
Working
```yaml
version: '3.7'
services:
  whoami:
    image: jwilder/whoami
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints:
         - node.role == worker
```
Log output when `docker kill` an instance of the service

```
Aug  8 12:34:18 syssec-grid-003 dockerd[1108]: time="2018-08-08T12:34:18.343387883+02:00" level=error msg="fatal task error" error="task: non-zero exit (137)" module=node/agent/taskmanager node.id=ifzgif5424qb42bqiicu1tb9e service.id=mx331ych7wmjpw0te33vv9a9r task.id=c1e4iv77hnbdy89my5w95twcq
```

Instance down, but now restart.

My first thought was, that it is related to #37493 but there @taiidani stated that a kill will help with the update issues. For us it doesn't help because the container does not get restarted.

**Comment by unglaublicherdude** [comment]
I downgraded our manager nodes to 18.03.1. Workers are still on version 18.06.0. It works normal with this version on the mangers.

**Comment by unglaublicherdude** [comment]
Any news on this? Do you need more information about the issue?

**Comment by thaJeztah** [comment]
ping @dperny is this related to https://github.com/docker/swarmkit/issues/2705 ?

**Comment by thaJeztah** [comment]
@unglaublicherdude if this is indeed related to https://github.com/docker/swarmkit/issues/2705; a fix for that was included in the docker 18.06.1 patch release (through https://github.com/docker/engine/pull/32); perhaps you have a test-setup to verify if this is fixed in 18.06.1?

**Comment by unglaublicherdude** [comment]
@thaJeztah I updated our test environment to 18.06.1 and the problem seems to be gone. Thank you for the hint!

**Comment by thaJeztah** [comment]
Perfect! Let me go ahead and close this issue :+1:
