### ISSUE TITLE
SQL timeout when too many columns are being selected - only in Docker

### ISSUE THREAD

**Issue by cmeeren** [moby/moby#37621]
I may have hit upon a weird networking bug related to Docker, and [I'm not the only one](https://stackoverflow.com/questions/50657505/sql-timeout-with-dotnet-core-in-docker-when-getting-somewhat-larger-than-usual-d). I have no idea where i should report it, so I'm trying here first. Please let me know if there are better alternatives.

In short: I have a simple ASP.NET Core 2.1 app calling an SQL database. When running the app outside Docker, everything works fine all the time. But when running the app using Docker, the SQL connection times out if it tries to fetch to many columns. In my case I'm only fetching a single row from two joined tables, with a total of 40 columns being selected. None of the columns are larger than `nvarchar(128)`, and most are significantly smaller (e.g. `bit`) The request is a simple `SELECT ... FROM ... INNER JOIN ... WHERE ...`.

As long as I keep below some seemingly arbitrary number of columns (<29), the request finishes quickly (~1s). Once I hit that limit, the request times out after 30s, regardless of whether the column I add is `nvarchar(128)` or `bit`.

It does not seem to matter if I use a stored procedure or an inlined SQL string.

**Again, if I run outside of Docker, everything works fine no matter the number of columns.**

I know this isn't much to go on, but I'm hoping it might be enough for someone to at least point me in the right direction (whether in the direction of a solution or a better place to file this issue). Please let me know if I can provide any other relevant info.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 57
 Running: 2
 Paused: 0
 Stopped: 55
Images: 33
Server Version: 18.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.165)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.89GiB
Name: Navi
ID: VUXH:PMCX:6USB:3B7W:QTEP:WQT3:BV42:6VJN:XOYG:RQRO:QW4K:SZER
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 48
 System Time: 2018-08-10T11:23:09.0566271+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

* Windows 10 Pro

**Comment by cpuguy83** [comment]
Have you tried adjusting MTU?

**Comment by cmeeren** [comment]
Thanks, I'll try that on Monday. Will I need to edit my docker-compose.yml to make my services use `myNet`?

**Comment by cmeeren** [comment]
Unfortunately I am unable to create a network using that command. I get the error described here: https://github.com/docker/for-win/issues/1960

**Comment by yamac-kurtulus** [comment]
@cmeeren Make sure you don't use Docker in Linux mode, unless you have to. Also choose overlay or nat explicitly with the `--driver` option. I think bridge network driver is not available for Windows.

**Comment by cmeeren** [comment]
Thanks. I tried to place the following in my compose file, but I get the same behavior:

```yaml
networks:
  default:
    driver: nat
    driver_opts:
      com.docker.network.driver.mtu: 1420
```

I also tried with 1400 and 1300, but to no avail.

I also tried

    docker network create --driver nat --opt com.docker.network.driver.mtu=1420 myNet

and in my compose file

```yaml
networks:
  default:
    external:
      name: myNet
```

But again, no change.

**Comment by cmeeren** [comment]
Is there anything else to be done? Does this belong to this repo, or should it be reported anywhere else?

**Comment by sam3kh** [comment]
>           Is there anything else to be done? Does this belong to this repo, or should it be reported anywhere else?

Running into the same exact issue.  Without a resolution, our developers will have a hard time adding Docker to their workflow, since they all work with a local DB.

**Comment by richardgavel** [comment]
@cmeeren @sam3kh 

I was running into a similar issue (https://github.com/moby/moby/issues/38084) though mine involved an HTTP server running in a container. I noticed something very interesting today. It only seems to happen when using port mapping. If you hit the container directly via its IP (docker container xxx inspect), do you get the same problems? I don't, and the performance is better.

**Comment by cmeeren** [comment]
@richardgavel Can't test; I have dropped Docker for now (due to bugs such as this), and cannot easily get Docker up and running with the project I previously experienced problems with.

**Comment by cmeeren** [comment]
I was finally able to test. I still experience this error even when hitting the container directly via its IP.

**Comment by cpuguy83** [comment]
Oh just realizing this is Windows 10. Not really familiar with Windows troubleshooting in this regard. Can you trace the process to see where it's getting stuck/slowed down?

**Comment by cmeeren** [comment]
As I said in at the outset:

> when running the app using Docker, the SQL connection times out if it tries to fetch to many columns.

If this is not what you just meant, I'm afraid I didn't quite understand - could you then explain what exactly you mean by "trace the process"?

**Comment by cpuguy83** [comment]
@cmeeren On Linux I'd use something like strace and probably tcpdump in this case.

**Comment by cmeeren** [comment]
I tried using Fiddler to capture network traffic, but it only captures the call from Postman to my localhost API process, not from the localhost API process to the SQL server (even when running outside of Docker where the DB call works). So I'm afraid I'm a bit stuck in that regard.

By the way, this only happens using Windows containers. If I switch to Linux containers, things seem to work fine.

**Comment by KingpinEX** [comment]
Did you ever get it to work fast?

**Comment by cmeeren** [comment]
Sorry, I have not gotten anything to work. (Not working actively on it either, because I have nothing to go on and no idea how to proceed. Though I'd like it to work, of course.)

**Comment by KingpinEX** [comment]
In my case, it takes a very long time to connect, where if you run the same commands on the server itself it just executes immediately.

**Comment by rayjlinden** [comment]
I just ran into this problem as well.  Do a docker inspect to get the IP address (172.18.x.x).  Try to do a mysql connection to that IP and it is SLOW....

docker exec -it containerName mysql ...

is very fast.

Also, if using the default network in docker it works fast.  This issue came up because went from docker-compose V1 file to docker-compose v3.  The difference is it it not using the default docker network but one created by docker_compose.

How can I make that connection work at a normal speed?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
