### ISSUE TITLE
Docker pull fails on Windows Server Insider 17723 ("The specified procedure could not be found.")

### ISSUE THREAD

**Issue by jasharpe** [moby/moby#37625]
**Description**

Docker pull fails consistently on Windows Server Insider build 17723 with a message like:

```
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\docker\windowsfilter\76ae21e43fa6fdf92d84fd8b96b8859dcf1a49b87419cea427d7dad2a37ceb3f: The specified procedure could not be found.
```

**Steps to reproduce the issue:**
1. Install Windows Server Insider 17723.

2. Verify that this is the version you're using:

```
$ systeminfo
...
OS Version:                10.0.17723 N/A Build 17723
```

3. Install Docker according to the instructions at https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/using-insider-container-images. TL;DR:

```
Stop-Service docker
Uninstall-Package docker
Uninstall-Module DockerMsftProvider
Install-Module -Name DockerProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerProvider -RequiredVersion Preview
Restart-Computer
```

4. Try to pull any image (e.g. the appropriate windowsservercore-insider image, but any image will fail in the same way):

```
$ docker pull mcr.microsoft.com/windowsservercore-insider:10.0.17723.1000
```

**Describe the results you received:**

```
Unable to find image 'mcr.microsoft.com/windowsservercore-insider:10.0.17723.1000' locally
10.0.17723.1000: Pulling from windowsservercore-insider
107512a90ab2: Extracting [==================================================>]  1.524GB/1.524GB
C:\Program Files\Docker\docker.exe: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\docker\windowsfilter\199eb26b57af4ff0e5ec7755b519a2f1d3894f332e24a710139e9309365911ed: The specified procedure could not be found.
See 'C:\Program Files\Docker\docker.exe run --help'.
```

**Describe the results you expected:**

Image is pulled without error, and is runnable.

**Additional information you deem important (e.g. issue happens only occasionally):**

At least one other report on Kubernetes slack, #sig-windows (you'll have to sign up to see this): https://kubernetes.slack.com/messages/C0SJ4AFB7/convo/C0SJ4AFB7-1533840272.000128/

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17723 (17723.1000.amd64fre.rs5_release.180720-1452)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 60GiB
Name: windows-dev-insider-17723
ID: ZKQP:DP6F:UD3R:2337:ONCU:C2UU:WDS4:FMEX:I5PQ:3Q2G:ANZB:YGKX
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running on a GCP VM.

**Comment by jasharpe** [comment]
@cwilhit FYI

**Comment by cwilhit** [comment]
Do you have the Containers feature enabled and _do not_ have the Hyper-V feature enabled?

**Comment by jasharpe** [comment]
It does appear that Containers is enabled and Hyper-V is not:

```
Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online

FeatureName      : Microsoft-Hyper-V
DisplayName      : Hyper-V
Description      : Hyper-V
RestartRequired  : Possible
State            : Disabled
...
```

```
$ Get-WindowsOptionalFeature -FeatureName Containers -Online

FeatureName      : Containers
DisplayName      : Containers
Description      : Provides services and tools to create and manage Windows Server Containers and their resources.
RestartRequired  : Possible
State            : Enabled
...
```

However these are the same feature values as I have on an 1803 machine where Docker pull works fine.

**Comment by cwilhit** [comment]
This is a known bug in this build that we've resolved in newer builds. My recommendation is that you either move to a newer insider build OR enable the Hyper-V feature on this build as a workaround.

**Comment by jasharpe** [comment]
There's another workaround (adding some dlls) here: https://twitter.com/Abt_Benjamin/status/1027540447047102464

Do we know specifically which version it's fixed in. Is it fixed in 17728 (the next version), for instance? (Just to save me some time trying versions)

**Comment by cwilhit** [comment]
Build 17735--the latest insider build [released on Friday](https://blogs.windows.com/windowsexperience/2018/08/10/announcing-windows-10-insider-preview-build-17735/) should have the fix for this.

**Comment by jasharpe** [comment]
Any idea when that will be released as a Windows Server Insider release?

**Comment by cwilhit** [comment]
Windows Server insider builds tend to lag behind the Windows client fast insider ring by several days. It should be out in about a week or so.

**Comment by jasharpe** [comment]
At a first glance, the DLL workaround works for me in the meantime. I copied `C:\Windows\system32\vmwpctrl.dll` from an 1803 machine to my 17723 machine and now this works (bringing up an interactive console):

```
docker run -it mcr.microsoft.com/windowsservercore-insider:10.0.17723.1000
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
