### ISSUE TITLE
docker exec does not obey --security-opt no-new-privileges

### ISSUE THREAD

**Issue by margana** [moby/moby#37667]
**Description**

`docker run` supports starting a container with `no new privileges` enabled, however this does not seem to apply to processes started with `docker exec`

**Steps to reproduce the issue:**

1. Set up a test (suid root id)
```
$ sudo cp `which id` .
$ sudo chmod +s id
```

2. Check that it is working (elevate privs inside container)
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 centos:7 /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

3. Check that no-new-privs is working
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 --name nnp-test --security-opt no-new-privileges centos:7
bash-4.2$ /test/id
uid=1000 gid=1000 groups=1000
```

4. Check that no-new-privs is working with docker exec (in another terminal, leaving the container from previous step running)
```
$ docker exec -ti -u 1000:1000 nnp-test /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

**Describe the results you received:**
Eventhough the container was started with `--security-opt no-new-privileges` privilege elevation was possible through `docker exec`

**Describe the results you expected:**
No privilege elevation.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:45 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:14:07 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.14-202.fc28.x86_64
Operating System: Fedora 28 (Twenty Eight)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.53GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by margana** [comment]
For those looking for a workaround, you can prefix your command with `setpriv --no-new-privs`

So in the 'Steps to reproduce' above it would be: 
```
docker exec -ti -u 1000:1000 nnp-test setpriv --no-new-privs /test/id
```

**Comment by Bacto** [comment]
Hi,

Same strange behaviour with the option `no-new-privileges` here.

So, basically I give capabilities to netcat to listen to ports <= 1024, create a user "test" and start nc to listen to 514.

When using `docker run` with `no-new-privileges` to false, it works:
```
~ docker run --security-opt="no-new-privileges:false" -it alpine:3.9.4 /bin/sh -c "apk add sudo libcap netcat-openbsd ; setcap 'cap_net_bind_service=+eip' /usr/bin/nc ; adduser -D test ; echo Start nc ; sudo -u test /usr/bin/nc -l -p 514"
[...]
Start nc
```

When using `docker run` with `no-new-privileges` to true, it fails:
```
~ docker run --security-opt="no-new-privileges:true" -it alpine:3.9.4 /bin/sh -c "apk add sudo libcap netcat-openbsd ; setcap 'cap_net_bind_service=+eip' /usr/bin/nc ; adduser -D test ; echo Start nc ; sudo -u test /usr/bin/nc -l -p 514"
[...]
Start nc
nc: Permission denied
```

What is strange, is if I use `docker run` with `no-new-privileges` to true and start netcat in the container through `docker exec`:
```
# Starting container and sleep
~ docker run --security-opt="no-new-privileges:true" -it alpine:3.9.4 /bin/sh -c "apk add sudo libcap netcat-openbsd ; setcap 'cap_net_bind_service=+eip' /usr/bin/nc ; adduser -D test ; echo Waiting ; while true ; do sleep 10 ; done"
Waiting
```

Then, start netcat through `docker exec`, and it works, it waits for packets:
```
~ docker exec -it <CONTAINER_ID> sudo -u test /usr/bin/nc -l -p 514
```

That is I think really weird and not the desired behaviour.


Tested on `Docker version 18.09.2, build 6247962` and `Docker version 18.09.1-ce, build 4c52b901c6cb019f7552cd93055f9688c6538be4`

**Comment by pjbgf** [comment]
@Bacto That seems to have been fixed by https://github.com/docker/engine/pull/178. Testing on 18.09.7 this is not reproducible.

**Comment by cpuguy83** [comment]
Thanks for pointing this out @pjbgf 

Going to close this since it seems like this is resolved, but feel free to discuss. Let me know if that's incorrect.
