### ISSUE TITLE
Docker CE: Unable to connect to private docker registry

### ISSUE THREAD

**Issue by ackris** [moby/moby#37669]
@thaJeztah 

Hi Everyone

**Expected O/P**: Able to successfully login to a private docker registry. 

**Current Situation:**
I am unable to login to my private docker registry (artifactory) even after configuring according to this [documentation](https://www.jfrog.com/confluence/display/RTF/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-UsingDockerCompose-1MinuteSetup.1). As per the documentation, I have added the docker container IP in /etc/hosts and DOCKER_OPTS in /etc/default/docker.

**/etc/hosts:**

```
root@sw:/etc/default# cat /etc/hosts
127.0.0.1   localhost
127.0.1.1   sw
192.168.10.22     docker-local.192.168.10.22 docker-remote.192.168.10.22 docker-virutal.192.168.10.22 docker.192.168.10.22 192.168.10.22

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**/etc/default/docker:**
```

root@sw:/etc/default# cat /etc/default/docker 
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/admin/systemd/
#

# Customize location of Docker binary (especially for development testing).
#DOCKERD="/usr/local/bin/dockerd"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"


DOCKER_OPTS="$DOCKER_OPTS --insecure-registry docker-local.192.168.10.22 --insecure-registry docker-remote.192.168.10.22 --insecure-registry docker-virtual.192.168.10.22 --insecure-registry docker.192.168.10.22"
```

But still I am unable to login to private docker registry. I am getting the following error:

```
root@sw:/etc/default# docker login docker.192.168.10.22
Username: admin
Password: 
Error response from daemon: Get https://docker.192.168.10.22/v2/: dial tcp 192.168.10.22:443: connect: connection refused
```

I tried from root & non-root user, yet I am getting bricked with this error. Is anything missing or am I unable to see something which is obvious?

**Docker CE detail**:
```

root@sw:/etc/default# docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.605GiB
Name: sw
ID: XETG:RMK7:SLSJ:YQ36:MZ4O:LOTQ:Q7H6:2LEF:FKKU:CWCV:YHJD:I2PD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Docker Version details:**

```
root@sw:/etc/default# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Docker Compose Details:**

```
root@sw:/etc/default# docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
I have also created a self signed certificate and key using openssl & have mounted all those details in an  nginx container using docker exec. 

**The Nginx configuration file:**
```
###########################################################
## this configuration was generated by JFrog Artifactory ##
###########################################################

## add ssl entries when https has been set in config
ssl_certificate      /etc/nginx/ssl/domain.crt;
ssl_certificate_key  /etc/nginx/ssl/domain.key;
ssl_session_cache shared:SSL:1m;
ssl_prefer_server_ciphers   on;
## server configuration
server {
    listen 443 ssl;
    listen 80 ;
    server_name ~(?<repo>.+)\.192.168.10.22 192.168.10.22;
    
    if ($http_x_forwarded_proto = '') {
        set $http_x_forwarded_proto  $scheme;
    }
    ## Application specific logs
    ## access_log /var/log/nginx/192.168.10.22-access.log timing;
    ## error_log /var/log/nginx/192.168.10.22-error.log;
    rewrite ^/$ /artifactory/webapp/ redirect;
    rewrite ^/artifactory/?(/webapp)?$ /artifactory/webapp/ redirect;
    rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;
    chunked_transfer_encoding on;
    client_max_body_size 0;
    location /artifactory/ {
    proxy_read_timeout  900;
    proxy_pass_header   Server;
    proxy_cookie_path   ~*^/.* /;
    if ( $request_uri ~ ^/artifactory/(.*)$ ) {
        proxy_pass          http://192.168.10.22:8081/artifactory/$1;
    }
    proxy_pass          http://192.168.10.22:8081/artifactory/;
    proxy_set_header    X-Artifactory-Override-Base-Url $http_x_forwarded_proto://$host:$server_port/artifactory;
    proxy_set_header    X-Forwarded-Port  $server_port;
    proxy_set_header    X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header    Host              $http_host;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
```

Artifactory, Nginx and Postgres are all running inside containers, and they have been installed as per artifactory's docker-compose example.

Please help me as I am struggling with this for the past 3-4 days without any luck.

NOTE: I have referred to almost every similar question, but none were able to address my situation.

Regards

Aditya

**Comment by hvindin** [comment]
If nginx and artifactory are in different containers and nginx is proxy_pass'ing to arrifactory at 192.168.10.22 then wouldnt nginx be listening on a different IP address?

That is to say, shoudlnt your config look something like:

```
upstream artifactory {
  server 192.168.10.24:8081;
}

server {
  listen 192.168.10.22:443 ssl http2 default_server;
  server_name ~(?<repo>.+)\.192.168.10.22 192.168.10.22;
  ...
  location /artifactory/ {
    ...
    if ( $request_uri ~ ^/artifactory/(.*)$ ) {
        proxy_pass          http://artifactory/artifactory/$1;
    }
    proxy_pass          http://artifactory/artifactory/;
    ...
  }
  ...
}
```

note: the address in the upstream is 192.168.10.**24** not 192.168.10.**22**

**Comment by ackris** [comment]
Hi @hvindin 

I am new to nginx...still learning the ropes. 

Should we add upstream server bit below

```
## add ssl entries when https has been set in config
ssl_certificate      /etc/nginx/ssl/domain.crt;
ssl_certificate_key  /etc/nginx/ssl/domain.key;
ssl_session_cache shared:SSL:1m;
ssl_prefer_server_ciphers   on;
```
??

**Comment by hvindin** [comment]
In this case adding artifactory as an upstream rather than directly using `proxy_pass <IP Address>` doesn't really add a whole lot, I just thought it was a neat way of separating out the server declaration and the ip address of the upstream.

You could declare the artifactory upstream anywhere in that file.

More importantly you would just need to make sure that the address you provide to nginx matches the address that artifactory is actually running on. So if you ran the following:
```
sudo docker inspect --format '{{ range $n := .NetworkSettings.Networks }}{{ $n.IPAddress }}{{ end }}' <Your Artifactory Container>
```

Then you would get the IP Address of your artifactory container, and would be able to replace your artifactory IP address with the correct endpoint.

Alternatively, and possibly a better idea, you could simply use the container name of your artifactory container in the nginx config and rely on dockers dns to look up the ip address for you. To do this you just need to replace the IP address you are refering to in your `proxy_pass` with the container name of your artifactory container.

**Comment by ackris** [comment]
Hi @hvindin 

Now i am getting another error
`
Error response from daemon: Get https://docker.artifactory/v2/: Forbidden`

This time I have carefully configured everything, and the values are matching. Whatever configuration was given in artifactory's HTTP settings, it is visible in nginx.conf

Actually we are trying to set up artifactory inside our corporate network. Is this error related to proxy? But we have properly configured docker proxy settings and we are successfully pulling images from docker hub.

Regards
Aditya

**Comment by ackris** [comment]
Update:

Now it is back to `Error response from daemon: Get https://docker.artifactory/v2/: Forbidden`

Need help! Please...

**Comment by hvindin** [comment]
Just having a quick look at your nginx server block, there doesn't seem to be a `listen 443 ssl;` line, which would indicate that nginx is listening for HTTP requests and you are sending it HTTPS requests.

When you say you have configured proxies correctly, have you have made sure that your docker client isn't trying to go out to your proxies when it's connecting to something within your network?

You also almost definitely don't want to be setting your resolvers to the public google resolvers. Those will work great if you are resolving something on the internet, but you aren't, you're resolving an address internal to your network, so you should be leaving your resolvers pointing at your internal DNS.

**Comment by ackris** [comment]
@hvindin 

Hi

Actually, port 443 is being consumed by other service. Can we use port 8443 instead? 

Regards

**Comment by ackris** [comment]
@hvindin 

I am getting `bad request` on `docker.xx.xx.x.xxx:443 `

I am getting `forbidden` on `xx.xx.x.xxx:443/docker.xx.xx.x.xxx`

I am getting `forbidden` on `xx.xx.x.xxx:8081/docker.xx.xx.x.xxx`

As you had suggested, i have added `listen ssl 443` line in `nginx.conf`

Regards
Aditya

**Comment by ackris** [comment]
@hvindin 

Then why am I getting this kind of error? I checked error.logs, but they were empty. 

Regards
Aditya

**Comment by hvindin** [comment]
Taking a very quick guess, from what you commented previously vs the config you posted:

`server_name ~(?<repo>.+)\.artifactory artifactory;` does not match `docker.xx.xx.x.xxx`

If you are going to address your nginx as docker.xx.xx.x.xxx then it needs to be told about it in the server name.

Presumably you would want to change the server_name to `server_name ~(?<repo>.+)\.xx.xx.x.xxx xx.xx.x.xxx;`?

**Comment by ackris** [comment]
Hi @hvindin 

That `docker.artifactory` was an old one. Today we did a fresh installation based on ssl 443 suggestion. This time we configured it as `docker.xx.xx.x.xxx`.

**Comment by ackris** [comment]
@hvindin 

I ended up bricking my docker environment. My trick was of no use. 

Today i had TLS handshake timeout (a new error! :D)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
