### ISSUE TITLE
Single file copy fails in LCOW

### ISSUE THREAD

**Issue by clintsinger** [moby/moby#37677]
**Description**

**Steps to reproduce the issue:**
1. Create docker file with COPY command for a single file
ex:
FROM node:latest as node
RUN mkdir -p /app
COPY package.json /app/
WORKDIR /app
RUN npm install
COPY . /app
EXPOSE 4200/tcp

**Describe the results you received:**
Step 1/7 : FROM node:latest as node
 ---> b064644cf368
Step 2/7 : RUN mkdir -p /app
 ---> Using cache
 ---> 944adc3cd1bb
Step 3/7 : COPY package.json /app/
failed to copy files: invalid arguments

**Describe the results you expected:**
File is copied into image.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens every time I try to do a build.  

I have tried changing the syntax every possible way that I could think of but nothing worked while using LCOW.  

Switching to Linux Containers worked but with the obvious loss of not being able to run Windows Containers.

COPY   .   /app/    does work.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 32
Server Version: 18.06.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17741 (17741.1000.amd64fre.rs5_release.180814-1430)
Operating System: Windows 10 Pro Version 1809 (OS Build 17741.1000)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.92GiB
Name: DESKTOP
ID: G7M6:UQKL:VSLL:FNEQ:3KUU:UXUW:A3DT:UTRQ:T23Z:FCJQ:VLOS:W75Q
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2018-08-20T18:24:51.8614847-07:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Microsoft Windows [Version 10.0.17741.1000]

**Comment by bwateratmsft** [comment]
@clintsinger I was hitting this same issue, until I added the `--platform=linux` flag to the `docker build` command.  See if that has any effect.  My overall command is:
`docker build --platform=linux -f .\MyNetCoreWebApplication\Dockerfile .`

**Comment by thaJeztah** [comment]
ping @jhowardmsft ptal

**Comment by jhowardmsft** [comment]
IIRC, I fixed this a while back. Can you confirm using latest binaries from master.dockerproject.org. Thanks. Closing for now - re-open if it repros using latest.
