### ISSUE TITLE
docker start error

### ISSUE THREAD

**Issue by zhangtingshu** [moby/moby#37694]
Steps to reproduce:
1.cent os 7 new;
2.get docker-ce;
3.systemctl start docker;
iptables can not init nat table;
output:
8月 22 17:15:09 VM dockerd[31404]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insm
8月 22 17:15:09 VM dockerd[31404]: Perhaps iptables or your kernel needs to be upgraded.
8月 22 17:15:09 VM dockerd[31404]: (exit status 3)
8月 22 17:15:09 VM systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
8月 22 17:15:09 VM systemd[1]: Failed to start Docker Application Container Engine.

**Comment by zhangtingshu** [comment]
cent os 
Linux VM 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ljesparis** [comment]
ping @thaJeztah 

You should follow the following issue template:


**Description**



**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zhangtingshu** [comment]
cent os need join nat module and recompile the kernel.
or replace os.

**Comment by jiankunking** [comment]
> cent os need join nat module and recompile the kernel.
> or replace os.

This kind of work station is troublesome, have other method?

**Comment by jiankunking** [comment]
> cent os need join nat module and recompile the kernel.
> or replace os.

What are the specific causes?

**Comment by jiankunking** [comment]
关闭CentOS7的firewalld并启用iptables即可

Just close firewalld on CentOS7 and enable iptables

**Comment by jiankunking** [comment]
解决方案（solution）
[https://blog.csdn.net/jiankunking/article/details/84064695](https://blog.csdn.net/jiankunking/article/details/84064695)
