### ISSUE TITLE
Multiple "--dns" with "--network customNet" just use the first dns

### ISSUE THREAD

**Issue by hetykai** [moby/moby#37716]
When i run container with "--network customNet", container just use the first dns.

**Description**

When i run container with "--network customNet", that would raise this issue.

`docker run -it --rm --network customNet --dns-opt=rotate --dns-opt="timeout:1" --dns 202.112.20.131 --dns 8.8.8.8 alpine`
Run command `ping baidu.com` return `ping: bad address 'baidu.com'`
Check resolv.conf `cat /etc/resolv.conf`, this file does not contain the DNS IP address specified above.

Then i run `echo -e 'nameserver 202.112.20.131\nnameserver 8.8.8.8' >> /etc/resolv.conf`
And i check resolv.con `cat /etc/resolv.conf`, it contains the DNS IP address specified above, and i `ping baidu.com` return the right ip.

When i run container without "--network yourCustomNet", it does NOT raise the issue, and resolv.conf contains the DNS IP address specified above.

So i think this issue cause by that the resolv.conf file could not work correctly with custom network.

![powershell_2018-08-24_20-51-25](https://user-images.githubusercontent.com/3378432/44586052-f7ff0b80-a7e0-11e8-9a96-5fcfe59e861e.png)

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 18
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d010d38
ID: ABAU:5RGB:MHID:TN7S:7A2M:FEDQ:QPEG:FZQJ:U767:BVT2:7PR4:5MKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 89
 Goroutines: 101
 System Time: 2018-08-24T13:12:23.7451238Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
 https://docker.mirrors.ustc.edu.cn/
 https://hub-mirror.c.163.com/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dreamcat4** [comment]
Yeah I am seeing the same thing over here too:

```sh
id:~/big/docker-images] master(+22/-14)+* ± crane run -v dockerdns
Reading configuration /home/id/big/docker-images/crane.yml
No default network will be setup as prefix is disabled.
Command will be applied to: dockerdns
If needed, also creates networks: dkr

Removing container dockerdns ...
--> docker rm --force dockerdns
dockerdns
Running container dockerdns ...
--> docker create --dns 1.1.1.1 --log-opt max-size=10m --log-opt max-file=2 --name dockerdns dreamcat4/dockerdns
--> docker network connect --alias dockerdns --ip 192.168.53.54 dkr dockerdns
--> docker start dockerdns
dockerdns
[id:~/big/docker-images] master(+22/-14)+* ± docker exec dockerdns cat /etc/resolv.conf
nameserver 127.0.0.11
options edns0 single-request-reopen timeout:2 ndots:0
```

**Comment by thaJeztah** [comment]
this is expected; when using a custom network, docker uses an embedded DNS (at IP address `127.0.0.11` inside the container) that's used for resolution of internal hosts (for example, IP addresses of other containers on the same network); resolution of external domains is forwarded to the DNS servers you configured.

If you run the daemon with debug enabled, you should see debug messages in the daemon logs that show that its forwarding those requests to the external DNS servers.

The default bridge network does not (currently) use the embedded DNS, but rewrites entries in the container's `/etc/hosts`; this approach is kept for backward compatibility. 

I'll close this issue, because this is working as expected, but feel free to continue the conversation.

**Comment by dreamcat4** [comment]
Thanks @thaJeztah for letting us know how to see / debug this situation... answer accepted !!!

**Comment by thaJeztah** [comment]
answering from my phone now, so bit difficult to show example debug output; but this PR in libnetwork made some changes in the resolver (if you're interested in the implementation); https://github.com/docker/libnetwork/pull/2171

**Comment by vigohe** [comment]
@thaJeztah Does the "--dns-opt=rotate" works with the fix??? or is there any other solution to do round-robin instead of fail-over?

**Comment by thaJeztah** [comment]
@vigohe setting `--dns-opt` will only set the configuration in `/etc/resolv.conf` inside the container. When using a custom network, there will only be a single DNS configured (which is the embedded DNS), so `rotate` won't make a difference.

Configuring the embedded DNS to use round-robin for upstream DNS servers when forwarding is not supported currently; it will try the configured DNS servers sequentially.
