### ISSUE TITLE
OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/registry\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by katelynwang** [moby/moby#37713]
Run <code>docker run -d  --name test test</code>, I got the following error.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/registry\": executable file not found in $PATH": unknown.

docker info:
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 65
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.25GiB
Name: CTU1000117562
ID: GFZZ:GSOG:WB7M:CGRO:BTOL:TAWE:HTQA:RVTG:3SMX:OB56:WQ6V:VJ63
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://9f8a9340.m.daocloud.io/
Live Restore Enabled: false

```

docker version
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

My Dockerfile
```
FROM golang:1.10-alpine

ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution
ENV DOCKER_BUILDTAGS include_oss include_gcs include_obs

ARG GOOS=linux
ARG GOARCH=amd64

RUN set -ex \
    && apk add --no-cache make git

WORKDIR $DISTRIBUTION_DIR
COPY . $DISTRIBUTION_DIR
COPY cmd/registry/config-dev.yml /etc/docker/registry/config.yml

RUN make PREFIX=/go clean binaries

VOLUME ["/var/lib/registry"]
EXPOSE 5000
ENTRYPOINT ["registry"]
CMD ["serve", "/etc/docker/registry/config.yml"]
```

Really need some help and insights! Thx

**Comment by cpuguy83** [comment]
Either move "registry" to $PATH or execute "./registry"

**Comment by katelynwang** [comment]
@cpuguy83 
But i ran "make" in the Makefile folder before, it generated an executable registry file in ./bin/, and i added that bin into $PATH, still same error

I just executed "./registry", the error was permission denied.
Then I added <code>RUN chmod 777 ./registry</code>, still permission denied.

**Comment by cpuguy83** [comment]
"make" is in $PATH so the shell can execute it.

"Permission denied" would usually mean that the execute but is not set.

**Comment by katelynwang** [comment]
@cpuguy83 
Could you please tell em what to do?

**Comment by cpuguy83** [comment]
"chmod +x".
Closing because this is not a Docker issue.
Thanks!

**Comment by maietta** [comment]
This is happening to a lot of people and I'm experiencing this on a very stubborn install situation. It seems the up-to-date install instruction no longer work for Docker CE on a Ubuntu 18.04 install. This issue happens on ALL attempts to run ANY container. That leads me to believe this is actually related to Docker itself, not a permissions with any file within the containers. I have been without luck for several days, to solve this problem. Maybe it's time i leave Ubuntu because this OS is the only one I keep running into issues with regarding Docker.

**Comment by thaJeztah** [comment]
@maietta make sure to check if the error is exactly the same (not just the `container_linux.go` part, as that line is the line that will throw _any_ error that is returned by Linux when starting the container's process, so your issue may not be related; https://github.com/opencontainers/runc/blob/4fc53a81fb7c994640722ac585fa9ca548971871/libcontainer/container_linux.go#L343-L349

```go
	if err := parent.start(); err != nil {
		// terminate the process to ensure that it properly is reaped.
		if err := ignoreTerminateErrors(parent.terminate()); err != nil {
			logrus.Warn(err)
		}
		return newSystemErrorWithCause(err, "starting container process")
	}
```

**Comment by charan432** [comment]
I am getting the error 

C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"7a94b9e7f499d990d5f53b30edfdeeefc291926afd28e8a2debca5ad8d05a3dc\": executable file not found in $PATH": unknown.

Please help

**Comment by thaJeztah** [comment]
@charan432 what image are you trying to run, and what's the command you're trying to run in it? If the command is a shell-script, make sure that it's _executable_ (see above), but also that it has Linux line-endings (`\n`), not windows (`\r\n`). Linux reports "executable file not found" if a shell-script has Windows line-endings (which is very confusing, but unfortunately how Linux reports it)

**Comment by vdf-git** [comment]
@thaJeztah I seem to have the same problem, but _only_ when running docker in some kind of a virtual environment:

xubuntu bionic ("metal" laptop): Succes
xubuntu bionic (virtualbox, host xubuntu bionic, guest xubuntu bionic) : Failure
xubuntu bionic (virtualbox, host windows 7, guest xubuntu bionic) : Failure
xubuntu bionic (xen hypervisor, dom0 debian jessie, guest xubuntu bionic, paravirtualized) : Failure
xubuntu bionic (xen hypervisor, dom0 debian jessie, guest xubuntu bionic, hardware virtualization) : Failure

In all cases, I used a barebone ubuntu image and tried running the command /bin/ls, ie.
"docker run ubuntu /bin/ls"

"failure" means the error reported by @charan432 

I have used the docker-ce 18.09.1~3-0, docker-ce-cli 18.09.1~3-0 and containerd.io 1.2.2-1 debian packages for bionic ubuntu provided from https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

Please let me know if I can provide anything else (logfiles, additional tests, whatever) to help solve this bug: It really is a showstopper for my current project :(

**Comment by luckydonald** [comment]
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:2557e3c07ed1e38f26e389462d03ed943586f744621577a99efb77324b0fe535
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/hello\": stat /hello: no such file or directory": unknown.
ERRO[0004] error waiting for container: context canceled
```

**Comment by luckydonald** [comment]
I have this problem with **every** container after upgrading from `18.01.0-ce` to `18.09.2`.

**Comment by luckydonald** [comment]
Posted as https://github.com/moby/moby/issues/38789.

**Comment by altanner** [comment]
Also having this with every container, 18.09.2 build 6247962

`docker run ubuntu -it /bin/bash`

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"-it\": executable file not found in $PATH": unknown.`

**Comment by cpuguy83** [comment]
Your arguments are in the wrong order. "-it" needs to go before the image name.

**Comment by altanner** [comment]
ha erm I've been being a bit dozey all day long in that case.

Thanks.... errr, do I delete that comment, it isn't very helpful.

**Comment by sz332** [comment]
Problem still exists after installing an ubuntu/trusty64 on virtualbox and following the official docker install description.

**Comment by dudziakm** [comment]
I closed the terminal and open again - it helped :D

**Comment by tinours** [comment]
Same issue after a problem of hard disk space on Ubuntu eoan.
Had to do a apt-get reinstall docker-ce to make it work again.

**Comment by antoninadert** [comment]
I have the same issue on a fresh Debian 9 install. I only did install docker-ce on it following official instructions. Then I'm stuck with this error, the Hello World image won't open !

This is unbelievable to me this doesn't work on a fresh install... and there is no proper instruction on what to do here. chmod+x on WHAT? 

I am new to Linux and this seems impossible to find a solution by myself. Thanks for helping

**Comment by luckydonald** [comment]
@cpuguy83 could you clarify or reopen the issue?

**Comment by cpuguy83** [comment]
If you are having a problem, please open a new issue with all the details.

This error happens because the command you (or the image config) have told Docker to run does not exist in the container.

I would also mention if you have added a setting to the Docker systemd config like "MountFlags=slave" it could cause the problem since 18.09. You should remove any such setting.

**Comment by qlep** [comment]
> I closed the terminal and open again - it helped :D

this one worked on a vm, goddammit! I spent half a day trying to fix this stupid error and a simple logout and log back in solved it!

**Comment by AzimAhmadzadeh** [comment]
My solution: for some reasons the **old order gives this error**. 

This is what I used to do (for which I just started receiving the above-mentioned error):
`docker create -it --name my_container python -v /data:/data`

and this is what I do now and it works:
`docker create -it -v /data:/data --name my_container python`

**Comment by mary57** [comment]
I simply removed my old image & it worked afterward

**Comment by Yusov** [comment]
Just remove old images and thats all.

**Comment by nyukers** [comment]
I have now
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"\": executable file not found in $PATH": unknown.

**Comment by hbeita** [comment]
> I have now
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: "": executable file not found in $PATH": unknown.

ward...

**Comment by NdS-Research-Facilities** [comment]
fixed my same issues by using the command twice, so `docker-compose run [container] [container] --dkjhkjsds`
