### ISSUE TITLE
docker-run --memory slab cache leak on centos7

### ISSUE THREAD

**Issue by margana** [moby/moby#37722]
Apologies in advance if this isn't the right place to report this.

**Description**

The slab cache on a server grows until it uses up all available memory, causing kswapd to take 100% cpu and triggering oom-killer. A simple test case shows a steady increase in slab cache only when `--memory` is specified.

**Steps to reproduce the issue:**
1. Run `slabtop` to monitor caches
2. Repeatedly run `docker run --rm --memory 1g hello-world`

**Describe the results you received:**
Ever increasing slab cache. Output from `slabtop` a while after it filled all memory:
``` Active / Total Objects (% used)    : 9624891 / 18517834 (52.0%)
 Active / Total Slabs (% used)      : 263119 / 263119 (100.0%)
 Active / Total Caches (% used)     : 86 / 116 (74.1%)
 Active / Total Size (% used)       : 1681083.55K / 3255397.62K (51.6%)
 Minimum / Average / Maximum Object : 0.01K / 0.18K / 8.00K

  OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME                   
2952064 1635713  55%    0.03K  23063      128     92252K kmalloc-32             
2241728 1470553  65%    0.06K  35027       64    140108K kmalloc-64             
1932336 1470384  76%    0.19K  46008       42    368064K dentry                 
1887744 639474  33%    0.02K   7374      256     29496K kmalloc-16             
1780376 1672338  93%    0.12K  26182       68    209456K kernfs_node_cache      
1693098 590519  34%    0.04K  16599      102     66396K selinux_inode_security 
1364992 104960   7%    0.01K   2666      512     10664K kmalloc-8              
861390 747913  86%    0.62K  17265       51    552480K sock_inode_cache       
553824 348450  62%    0.66K  11867       48    379744K ovl_inode              
518070 212092  40%    0.09K  12335       42     49340K kmalloc-96             
422864  78247  18%    1.00K  13379       32    428128K kmalloc-1024           
389214 194808  50%    0.19K   9267       42     74136K kmalloc-192            
291296  22728   7%    0.25K   4607       64     73712K kmalloc-256            
285536  16867   5%    0.50K   4514       64    144448K kmalloc-512            
228864   9118   3%    0.12K   3576       64     28608K kmalloc-128            
185300   3740   2%    0.05K   2180       85      8720K shared_policy_node
```

**Describe the results you expected:**
Stable slab cache use.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running `echo 3 > /proc/sys/vm/drop_caches` didn't noticeably reduce slab cache use.

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.685GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmWare

**Comment by bjornkatuin** [comment]
running into the exact same issue, happened twice this month, both on Cent-OS.

Once running in azure cloud, once running on bare metal.

**Comment by kolyshkin** [comment]
@CharlieR-o-o-t @margana @bjornkatuin Slab cache is Linux kernel thing, of which Docker has no control. A leak in slab cache is a kernel bug, which can't be fixed in Docker (and I am not aware of any worarounds). Please file a bug to Red Hat (or see if https://bugzilla.redhat.com/show_bug.cgi?id=1507149 describes your symptoms).

@thaJeztah it could be, and we really need to fix this (at least for 3.10 kernel). I'll take another look today.

**Comment by CharlieR-o-o-t** [comment]
@kolyshkin , exactly, my point is that it's not a docker bug. We had a lot of issues with 3.10, this is why we moved to 4.x kernel

**Comment by chilicat** [comment]
Is that a solution for 3.10 kernels? 
https://github.com/opencontainers/runc/pull/1921

**Comment by kolyshkin** [comment]
not a docker bug, see https://bugzilla.redhat.com/show_bug.cgi?id=1507149 for more info and https://github.com/opencontainers/runc/pull/1921 for a workaround (already implemented in docker as packaged by Docker, Inc.)
