### ISSUE TITLE
LCOW support - container fails to start

### ISSUE THREAD

**Issue by safizn** [moby/moby#37733]
Hi, trying out Docker's Linux Container On Windows. The 'portainer/portainer' image fails to start.

I'm getting startup error :
```
bolt.Close(): funlock error: operation not supported
operation not supported
```

Steps to reproduce: 

- Turn Docker experimental features, & switch to Windows containers.
- `docker run -d -p 9000:9000 -v portainer_data:/data portainer/portainer`

Maybe the current implementation of LCOW is not full yet. Can you do anything about it ?

![capture](https://user-images.githubusercontent.com/7758497/44797908-f48ccb00-abb8-11e8-94ba-2b11724af4b2.PNG)

**Comment by myuseringithub** [comment]
https://github.com/portainer/portainer/issues/2227

**Comment by myuseringithub** [comment]
#https://github.com/portainer/portainer/issues/2227

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
