### ISSUE TITLE
docker daemon 1.13.0 hung: docker ps not responding.

### ISSUE THREAD

**Issue by djonnala** [moby/moby#37766]
Hi,

We are using Docker version 1.13.0 in our production environment where lot of application teams run the docker containers. Since the volume of creating and destroying containers have increased significantly , we are facing docker ps hung issue on the server and can only be restored by restarting the docker service. 

Docker ps does not respond but other docker commands work.
I have run SIG1 and attaching the stack trace
[goroutine-stacks-2018-09-05T113101-0700.log](https://github.com/moby/moby/files/2354310/goroutine-stacks-2018-09-05T113101-0700.log)

Output of docker info 
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 32
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.74 GiB
Name: 
ID: URG6:ZIMV:SAF4:52EM:6GJU:J4YL:FWHB:G3GG:ZDEK:3Y7A:IUP7:OBGJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Output of Docker version 
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by cpuguy83** [comment]
1.13 is a very old release. (getting close 2 years old at this point).... for that matter there is even a 1.13.1 (I see you are on 1.13.0).
There have been many fixes for all sorts of deadlock scenarios on `docker ps` (and other cases).
In general I don't think a deadlock on `docker ps` is even possible anymore, primarily because it's using snapshotted data (not to say it's impossible, just not likely).

Is there some reason you are not running on a supported release?
Please upgrade to a supported release to see if that fixes the issues you are seeing.

If you are worried about other changes, Docker CE 17.03 is a continuation of the 1.13 release branch, so just fixes no features or major code changes.
Note that 17.03 does also have some known deadlocking issues and the changes to use snapshotting for container metadata that's used on `docker ps` is only in releases >= Docker CE 17.05.

**Comment by thaJeztah** [comment]
Let me close this issue because of the above, but feel free to continue the conversation

**Comment by djonnala** [comment]
We have upgraded to 17.12.1-ce version . We still face the same issue, the command "docker stats" hangs without any output. It is only resolved when we restart the docker service. 

**Docker info**
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 17.12.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.74GiB
Name: xxxxxxxxxxxxxxxxxxx
ID: 2R6W:ZIMG:6TBL:QRMB:MWSF:IAZ7:PRVY:ZCTU:MJJA:H2JG:DRTQ:A7IA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false



**Docker Version**
Client:
Version: 17.12.1-ce
API version: 1.35
Go version: go1.9.4
Git commit: 7390fc6
Built: Tue Feb 27 22:15:20 2018
OS/Arch: linux/amd64

Server:
Engine:
Version: 17.12.1-ce
API version: 1.35 (minimum version 1.12)
Go version: go1.9.4
Git commit: 7390fc6
Built: Tue Feb 27 22:17:54 2018
OS/Arch: linux/amd64
Experimental: false
