### ISSUE TITLE
different images version in deploy new app version

### ISSUE THREAD

**Issue by chmodrs** [moby/moby#37767]
hi,

sometimes when i deploy a new app version in my swarm cluster for a service with two or more replicas, docker daemon update only one replica with new image version and for resolve this, i need to ssh login in worker with the old image and manually kill container, after that, docker daemon update second replica with a new app version.

**Steps to reproduce the issue:**
1. jenkins deploy in ECR a new version of application. e.g myapp:10
2. run docker stack deploy with new docker-compose version updated with new image (myapp:10)

**Describe the results you received:**
[root@master1 myapp]# docker service ps myapp_myapp
ID                  NAME                    IMAGE                                                     NODE                DESIRED STATE       CURRENT STATE               ERROR                              PORTS
g4kpnz638ryq        myapp_myapp.1       ecrregistry.amazonaws.com/myapp:10   worker4             Ready               Ready 9 seconds ago                                            
zxkyjz38r8l8         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker4             Shutdown            Shutdown 25 hours ago                                          
zwmbazdtiutj         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker1             Shutdown            Failed 6 weeks ago          "task: non-zero exit (137)"        
zr1vayf0zqn3         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker4             Shutdown            Shutdown 5 weeks ago                                           
zqznqxtnth02         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          slave2              Shutdown            Rejected 2 months ago       "invalid mount config for type…"   
rlif30zkmm30        myapp_myapp.2       ecrregistry.amazonaws.com/myapp:9                          slave2              Running             Running about an hour ago

**Describe the results you expected:**
[root@master1 myapp]# docker service ps myapp_myapp
ID                  NAME                    IMAGE                                                     NODE                DESIRED STATE       CURRENT STATE               ERROR                              PORTS
g4kpnz638ryq        myapp_myapp.1       ecrregistry.amazonaws.com/myapp:10   worker4             Ready               Ready 9 seconds ago                                            
zxkyjz38r8l8         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker4             Shutdown            Shutdown 25 hours ago                                          
zwmbazdtiutj         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker1             Shutdown            Failed 6 weeks ago          "task: non-zero exit (137)"        
zr1vayf0zqn3         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          worker4             Shutdown            Shutdown 5 weeks ago                                           
zqznqxtnth02         \_ myapp_myapp.1   ecrregistry.amazonaws.com/myapp:9                          slave2              Shutdown            Rejected 2 months ago       "invalid mount config for type…"   
rlif30zkmm30        myapp_myapp.2       **ecrregistry.amazonaws.com/myapp:10**                          slave2              Running             Running about an hour ago

**Output of `docker version`:**

Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Output of `docker info`:**

Containers: 15
 Running: 8
 Paused: 0
 Stopped: 7
Images: 5
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: dyssihnsb55zpxfrcsclwco8y
 Is Manager: true
 ClusterID: xgbn6yjw9ba0dgyhc2biufe14
 Managers: 3
 Nodes: 9
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.30.2.236
 Manager Addresses:
  172.30.1.157:2377
  172.30.1.29:2377
  172.30.2.236:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.8MiB
Name: master1
ID: FDRN:6CPF:ZA23:6IGL:X3MN:35FU:HBOY:IZRH:J2TK:P5RT:MEAS:BFDR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: tisegware
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

aws EC2 environment

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
