### ISSUE TITLE
ls: can't open '.': Value too large for defined data type

### ISSUE THREAD

**Issue by dgageot** [moby/moby#37763]
`docker run --entrypoint=sh --rm gcr.io/distroless/base:debug -c ls` should output

```
busybox
dev
etc
home
lib
lib64
proc
sys
tmp
usr
var
```

Instead, it **sometimes** prints `ls: can't open '.': Value too large for defined data type`.

It's really **sometimes**, not **always**. Sometimes it works just after I restart Docker but if I remove all the images and try again, if ** sometimes* fails.

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by dgageot** [comment]
Sorry should have been reported on D4M

**Comment by thaJeztah** [comment]
Issue continued in https://github.com/docker/for-mac/issues/3203
