### ISSUE TITLE
yarn install inside docker with git submodules

### ISSUE THREAD

**Issue by perevezencev** [moby/moby#37762]
**Description**

My app have structure like this:

    /app
      /web
        /submodule
        package.json
        yarn.lock
        Dockerfile
    .gitsubmodule
    docker-compose.yml

Dockerfile in /app/web:

    # build
    FROM node:10 AS build-env
    WORKDIR /usr/src/app
    
    COPY package.json /usr/src/app/
    COPY yarn.lock /usr/src/app/
    RUN yarn install
    
    COPY . /usr/src/app/
    RUN yarn build
    
    # run
    FROM nginx
    
    COPY --from=build-env /usr/src/app/storybook-static /usr/share/nginx/html

In package.json `submodule` include as dependency:

      "dependencies": {
        "submodule": "file:./submodule",

If i running `yarn install` without docker everything is fine, but when docker build running `yarn install` command, an error is thrown:

    Building web
    Step 1/9 : FROM node:10 AS build-env
     ---> c0cfd9444538
    Step 2/9 : WORKDIR /usr/src/app
     ---> Using cache
     ---> 31d2e6122773
    Step 3/9 : COPY package.json /usr/src/app/
     ---> Using cache
     ---> 385af24cf951
    Step 4/9 : COPY yarn.lock /usr/src/app/
     ---> Using cache
     ---> 861576eec879
    Step 5/9 : RUN yarn install
     ---> Running in edde173d5035
    yarn install v1.9.2
    [1/4] Resolving packages...
    error Package "submodule" refers to a non-existing file '"/usr/src/app/submodule"'.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 2
 Paused: 0
 Stopped: 13
Images: 173
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 5z3f6rsyfjvzumlff1wk8o8m5
 Is Manager: true
 ClusterID: wb8r7t4obvru5s0cp5qwka9bw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: AVGM:3SBK:IM4L:FCYB:2GLL:JNMT:AS6P:3JMO:WX2I:QXDA:QUKS:C5NI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 165
 System Time: 2018-09-05T10:12:03.1245976Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS: v10.13.6

**Comment by thaJeztah** [comment]
I'm not a node (or yarn) expert, but looks like you're running `yarn install` before running `COPY . /usr/src/app/`, so effectively you only have a directory with two files (`package.json`, and `yarn.lock`), but a directory `submodule` is expected to be there.

I suspect this is not a bug in Docker, so I'll go ahead and close, but feel free to continue the conversation
