### ISSUE TITLE
Host volume permissions in the container differ from that of the host

### ISSUE THREAD

**Issue by aki-k** [moby/moby#37776]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**Description**

I'm mounting a host directory /btrfs_root from the host to a container. The permissions change from the host's 700 to the container's 755. This bug has been open previously in https://github.com/moby/moby/issues/6137

**Steps to reproduce the issue:**

1. On host: mkdir /btrfs_root; chmod 700 /btrfs_root
2. In docker-compose yaml file: 
```
volumes:
  - "/btrfs_root:/btrfs_root:rw"
```
3. Observe the permissions in the container /

**Describe the results you received:**

The /btrfs_root directory permissions in the container is 755.

**Describe the results you expected:**

The /btrfs_root directory permissions should be the same as in the host (700)

**Additional information you deem important (e.g. issue happens only occasionally):**
I can "fix" this problem by running chmod in the container's /etc/rc.d/rc.local.

**Output of `docker version`:**

```
# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.9.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: server hostname
ID: OCQQ:SZMF:KKDH:S37U:STXR:KUSQ:JRO3:6DK7:ALDC:AHL3:VZVO:C5WJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Is your docker daemon running on your local machine, or is the daemon on a remote machine (or inside a VM?).

When bind-mounting files or directories from the host, those are mounted from the machine that the _daemon_ runs on. When using the shorthand `-v`/`--volume <host-path>:<container-path>` syntax, and `host-path` is not found on the machine where the daemon runs, docker will automatically create a new directory with the given name, and mount that in the container. That new directory will have default permissions (depending on the umask).


Here's an example where a container is started with two bind-mounts; `existing_directory` is created upfront and given the right permissions, whereas `nosuch_directory` doesn't exist, and is created automatically when the container is started;

```bash
mkdir /existing_directory; chmod 700 /existing_directory

docker run -v /existing_directory:/existing_directory:rw -v /nosuch_directory:/nosuch_directory:rw busybox sh -c 'ls -la / | grep _directory'
drwx------    2 root     root          4096 Sep  6 16:08 existing_directory
drwxr-xr-x    2 root     root          4096 Sep  6 16:08 nosuch_directory
```

**Comment by aki-k** [comment]
I'm running the docker daemon in a VM in a IaaS cloud. The containers run on the same machine.
/btrfs_root is the mount point under which I'm mounting the btrfs subvolid=0 for /dev/vda2 (host's btrfs root fs) and /dev/vdc1 (host btrfs data fs), so it'll have /btrfs_root/vda2 and /btrfs_root/vdc1.

**Comment by aki-k** [comment]
The permission for /btrfs_root/vdc1 is retained but not that of /btrfs_root.

**Comment by bflemi3** [comment]
Did you ever resolve your issue? I'm running into the same thing.

**Comment by aki-k** [comment]
I'm fixing the problem in the container's /etc/rc.d/rc.local. This is CentOS 7 docker host and CentOS 7 docker container with systemd. Could you describe your setup here so the devs could see it too?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
