### ISSUE TITLE
Handler for GET error in /var/log/message from docker

### ISSUE THREAD

**Issue by AraNaldinho** [moby/moby#37803]
I have a running jenkins container in the Instance.
I often get this Error very often.

```
dockerd-current:` time="2018-09-08T00:03:50.316108328+08:00" level=error msg="Handler for GET /v1.24/images/docker123321/cron/json returned error: No such image: docker123321/cron"
dockerd-current: time="2018-09-08T00:03:50.316139523+08:00" level=error msg="Handler for GET /v1.24/images/docker123321/cron/json returned error: No such image: docker123321/cron"
dockerd-current: time="2018-09-08T00:03:50.993212924+08:00" level=error msg="Handler for GET /v1.24/images/docker123321/cronm/json returned error: No such image: docker123321/cronm"
dockerd-current: time="2018-09-08T00:03:50.993251516+08:00" level=error msg="Handler for GET /v1.24/images/docker123321/cronm/json returned error: No such image: `docker123321/cronm"
```

Docker Version: 1.12.6

Docker info:

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vg_root_01-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.857 GB
 Data Space Total: 3.49 GB
 Data Space Available: 1.633 GB
 Metadata Space Used: 831.5 kB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 32.72 MB
 Thin Pool Minimum Free Space: 348.7 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null host bridge
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 3
Total Memory: 5.702 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

Please help us ASAP.

**Comment by tao12345666333** [comment]
Can you show me your `docker images` command output ?

**Comment by thaJeztah** [comment]
This error itself doesn't give much information, and could be a valid error if the image doesn't exist.

From your `docker info` output, it looks like you only have a single image in your local image cache;

```
Images: 1
```

But you're attempting to (at least) use multiple images; `docker123321/cron` and `docker123321/cronm`.

In addition, docker 1.12.6 has reached end of life in January 2017, and is no longer supported or maintained. Based on the name of your daemon binary (`dockerd-current`), I suspect you're running the Red Hat fork of Docker, which is not maintained in this repository, and has a huge amount of modifications that are not in this repository; I'd recommend to either switch to the official Docker packages, or if you cannot switch, report this issue in the Red Hat issue tracker.

I'll close this issue because of the above, but feel free to continue the conversation

**Comment by AraNaldinho** [comment]
Thanks for the response.
`REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
146.215.126.225:5000/devops-jenkins   2.121.2             242488ca1b1d        6 weeks ago         1.215 GB
`

**Comment by tao12345666333** [comment]
@AraNaldinho  You only have one image, named `146.215.126.225:5000/devops-jenkins` .

**Comment by AraNaldinho** [comment]
I am using only one image to run the Docker instance.
what else images are required.???

**Comment by thaJeztah** [comment]
The error message is about something (or someone) trying to use the `docker123321/cron` and `docker123321/cronm` images.

- Who (or what) is trying to do `docker inspect docker123321/cron` and `docker inspect docker123321/cronm`?
- Perhaps a cron-job you forgot about, or some other script?
- Do you give the `devops-jenkins` container you're running access to the Docker API (e.g., does it have access to `/var/run/docker.sock`?); if so, it could be the container trying to run those commands.

**Comment by AraNaldinho** [comment]
Thanks for your response.

1. Who (or what) is trying to do docker inspect docker123321/cron and docker inspect docker123321/cronm?
Ans: we are not sure who or what is calling this functionality

2. Perhaps a cron-job you forgot about, or some other script?
Ans: Devops-Jenkins Image is nothing but Jenkins.war hosted tomcat server.
basically, we had a devops-jdk image, on which tomcat server is built, on which Jenkins.war is hosted.
we customised images because to meet our company standards.

3. Do you give the devops-jenkins container you're running access to the Docker API (e.g., does it have access to /var/run/docker.sock?); if so, it could be the container trying to run those commands.
Ans: No we haven't provided any such permission to our container.

if you need any more clarity with the issue, please let me know. will provide more details to narrow down the issue.

**Comment by thaJeztah** [comment]
> Ans: Devops-Jenkins Image is nothing but Jenkins.war hosted tomcat server.

@AraNaldinho actually, if this is an image you built yourself; It looks like you did not use the official tomcat image, but a malicious image as base-image for your image. See https://github.com/docker/hub-feedback/issues/1121#issuecomment-326664651

**Comment by AraNaldinho** [comment]
Thank you so much
