### ISSUE TITLE
Docker daemon will not start anymore.

### ISSUE THREAD

**Issue by xavs** [moby/moby#37806]
**Description**
Docker daemon fails to start for node in swarm

The worker node (on AWS EC2) in the swarm does not start.  Nothing too special going on, a local volume, an overlay network and few services in the swarm that is composed by 2 nodes (on AWS EC2).
The docker had containers out of the swarm (a jenkins)

**Steps to reproduce the issue:**
1. Create two nodes
2. Have a local volume in each
3. Create a flink jobmanager and taskmanager
4. ... not sure of anything else.

**Describe the results you received:**
```
dockerd[25538]: panic: Copy for *types.BoolValue not implemented
dockerd[25538]: goroutine 321 [running]:
...
systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Describe the results you expected:**
The daemon started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by xavs** [comment]
So I upgraded the docker version to 18.06.1 and it works again.

**Comment by Nitrosito** [comment]
Good Morning
Is that the Beta version, daily, test?
I do not think the incidence should be closed. The same thing happened to me.
I have 3 Nodes in Docker SWARM:
- Ubuntu 18.04 LTS
- Docker version 18.03.1-ce, compilation 9ee9f40

And it happens to me exactly the same as you mistake yourself.
How do you have that version installed?


a greeting

**Comment by fabiopedrosa** [comment]
@Nitrosito found a solution? just got myself the same issue https://github.com/moby/moby/issues/38014

**Comment by Nitrosito** [comment]
> @Nitrosito found a solution? just got myself the same issue #38014

I delete de docker swarm. Force 3 nodes to leave swarm, purge docker-ce and docker-compose
Reinstall docker-ce and docker-compose
make a new cluster docker swarm...
