### ISSUE TITLE
Allow to mount a docker image as a read only volume

### ISSUE THREAD

**Issue by asfernandes** [moby/moby#37812]
It would be great if one could mount a docker image as a read only volume.

Lets say one want to build app-infra and app-deployment images.

app-infra would consist of an infrastructure to run an app, while the app-deployment would be created as another image in CI/CD server.

Then the app container would use the app-infra image mounting the app-deployment as a read only volume.

With that one could benefit from docker tags to tag app-deployment and use different deployments with the same infra image.

**Comment by thaJeztah** [comment]
Thanks for opening; looks like this is a duplicate of https://github.com/moby/moby/issues/30449, so let me close this one; feel free to participate in the issue I linked to 👍
