### ISSUE TITLE
re-exec error: hcsshim::ImportLayer failed in Win32: The system cannot find the path specified

### ISSUE THREAD

**Issue by dhirschfeld** [moby/moby#37821]
**Description**

I'm once again seeing the `re-exec error`/`hcsshim::ImportLayer failed` error as described in #32838.

After updating to Windows Server 1803 (SAC) when it was released I hadn't experienced that error again... until now.

Every time I built my images I was hitting this bug so, under the impression that this has been fixed I updated to the latest Windows Server Insider 17744 (SAC). Unfortunately this has not fixed the problem and I'm continuing to see this error every time I try to build my images :cry: 

**Steps to reproduce the issue:**
1. Attempt to build very complicated, 25 GB quant-analytics image:
   `docker build --force-rm --no-cache -t $image .\$image`

**Describe the results you received:**
```
Removing intermediate container 8d5ab20baf68
docker : re-exec error: exit status 1: output: time="2018-09-10T20:02:29-07:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3)
path=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\0b270c09eb72c6c3bab927beaf43d51a4047e83b61b6661782df08b390502684 folder=C:\\ProgramData\\docker\\tmp\\hcs996314031"
At C:\Temp\Jupyter\docker\images\build.ps1:33 char:5
+     docker build --force-rm --no-cache -t $image .\$image 2>&1 | Tee- ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (re-exec error: ...\\hcs996314031":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) path=\\?\C:\ProgramData\docker\windowsfilter\0b270c09eb72c6c3bab927beaf43d51a4047e83b61b6661782df08b390502684
folder=C:\ProgramData\docker\tmp\hcs996314031
```

**Describe the results you expected:**
The build to work.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens every single time I try to build my image.

**Output of `docker version`:**

```
PS C:\> docker version
Client:
 Version:           master-dockerproject-2018-09-09
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        8ec21567
 Built:             Sun Sep  9 23:53:42 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          master-dockerproject-2018-09-09
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.11
  Git commit:       c1d090f
  Built:            Mon Sep 10 00:02:41 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
PS C:\> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: master-dockerproject-2018-09-09
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17744 (17744.1001.amd64fre.rs5_release.180818-1845)
Operating System: Windows Server Datacenter Version 1809 (OS Build 17744.1001)
OSType: windows
Architecture: x86_64
CPUs: 40
Total Memory: 255.9GiB
Name: DC1THWN01
ID: A6LO:IIRA:5LCA:6GN4:JULP:O3QO:C2G2:SWGV:TJI2:KGYX:OWUJ:K7DW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical box:
```
PS C:\> $winver = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'
PS C:\> $versiontag = "$($winver.CurrentMajorVersionNumber).$($winver.CurrentMinorVersionNumber).$($winver.CurrentBuildNumber).$($winver.UBR)"
PS C:\> $versiontag
10.0.17744.1001
```
```
PS C:\> docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/windowsservercore-insider   10.0.17744.1001     f548cf725ce4        2 weeks ago         3.43GB
PS C:\>
```

**Comment by dhirschfeld** [comment]
***c.c.*** @jhowardmsft, @thaJeztah, @tianon

**Comment by dhirschfeld** [comment]
I'll try and create a repro but as mentioned it will require pushing a ~20GB base image.

I'm happy to provide any further info required and any suggestions how to debug would be greatly appreciated!

**Comment by dhirschfeld** [comment]
I added a repro over at https://github.com/dhirschfeld/hcsshim-bug

Unfortunately it's not exactly a minimal reproducer however this particular bug only seems to materialise on large/complicated builds.

I'd be interested if others can also reproduce using the repo above.

**Comment by jhowardmsft** [comment]
@dhirschfeld It may take me a few days before I have time to investigate, but it's on my list. Can you confirm what the base OS image is in dhirschfeld/repro-base? Are you positive its a patched utility VM image with the servicing fix? (Although I see 17744 in your docker images output above, but am not sure if that's be base image in use here). Also are you doing the build with process isolation (default on Server) or Hyper-V isolation (default on Client, but possible on Server). The servicing fix in #32838 only affected utility VMs, so this would be a different cause entirely if you are using process isolation. Finally, are you positive you are not running out of disk space?

**Comment by dhirschfeld** [comment]
The base image for `repro-base` is `mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001`

I ran the build both with and without `--isolation=hyperv`

I'm pretty sure I'm not running out of space since I have 144GB free:
```
PS C:\Temp\repro> Get-PSDrive C

Name           Used (GB)     Free (GB) Provider      Root    CurrentLocation
----           ---------     --------- --------      ----    ---------------
C                  54.74        144.81 FileSystem    C:\          Temp\repro
```

> * Are you positive its a patched utility VM image with the servicing fix?*
 
Sorry, I'm not sure of the terminology *"patched utility VM"*? I've got a bare metal cisco blade with Windows Server 1809 (17744) Semi-Annual Channel Insiders installed. 

I then pull the corresponding container with:
```
PS C:\> $winver = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'
PS C:\> $versiontag = "$($winver.CurrentMajorVersionNumber).$($winver.CurrentMinorVersionNumber).$($winver.CurrentBuildNumber).$($winver.UBR)"
PS C:\> $versiontag
10.0.17744.1001
PS C:\> docker pull mcr.microsoft.com/windowsservercore-insider:$versiontag
````

And use:
```dockerfile
FROM mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001
```
to create the `repro-base` image.

**Comment by dhirschfeld** [comment]
>  It may take me a few days before I have time to investigate, but it's on my list.

Also, thanks for taking a look! And if there's anything I can do to assist in debugging just let me know...

**Comment by jhowardmsft** [comment]
Could you post the dockerfile for dhirschfeld/repro-base somewhere? I want to build the full image from scratch so it matches the build I'm using.

**Comment by dhirschfeld** [comment]
@jhowardmsft - I've update the repo https://github.com/dhirschfeld/hcsshim-bug with the full build pipeline. I've confirmed that I still observe the bug with this repo.

**Comment by dhirschfeld** [comment]
As a further data point I was able to build my image if I used the `windows-insider:10.0.17744.1001` container. 

This allows me to work-around the problem for now but I would still like to be able to use `windowsservercore` containers in future...

**Comment by dhirschfeld** [comment]
***Note:*** Is this possibly because the layer I'm trying to create is itself larger than 20GB?

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#image-size

**Comment by leonardobissoli** [comment]
Hi, using docker run --storage-opt "size=75GB" it worked for me. I can user docker commit without issues.

**Comment by leonardobissoli** [comment]
> _**Note:**_ Is this possibly because the layer I'm trying to create is itself larger than 20GB?
> 
> https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#image-size

Hi, using docker run --storage-opt "size=75GB" it worked for me. I could use docker commit without issues.

**Comment by leonardobissoli** [comment]
By the way there is a way to change storage settings after the container creation via docker run? Example: stop container, change, start container. Via daemon.json didn't not work. It only worked for my using the --storage-opt in docker run. I'm asking this because I have a container without this clause and I can't use docker commit because this error (trying to avoid loosing what I did).

Thank you.

**Comment by dhirschfeld** [comment]
I've increased the default storage size (and also moved to 2019) and havent' seen the issue since so I'll close this issue
