### ISSUE TITLE
swarm label nodes

### ISSUE THREAD

**Issue by psby** [moby/moby#37824]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by duglin** [comment]
looks like a typo

**Comment by psby** [comment]
I'm sorry, have no clue how I created this issue - just while ago I got mail with your response.. 
I apologize for creating mess
