### ISSUE TITLE
RFC: recursive read-only bind-mount emulation using FUSE

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#37838]
`docker run -v /:/host:ro` (`docker run --mount type=bind,src=/,dst=/host,ro`) is not really read-only, because there is no way in the kernel to bind-mount a filesystem tree recursively as read-only.

So I suggest emulating "recursive read-only bind-mount" using FUSE.
CLI would be like `docker run --mount type=bind,src=/,dst=/host,ro,bind-driver=fuse`.

If we don't want to use FUSE, an alternative way is to bind the tree as `rprivate` and then bind each of submounts explicitly.
However, `rprivate` does not work for `/`, `/var/lib`, and `/var/lib/docker/*`:  https://github.com/moby/moby/commit/589a0afa8cbe39b6512662fd1705873e2d236dd0
Also,  it doesn't work for those who wants to use the shared propagation.

@justincormack @cpuguy83 @dmcgowan

**Comment by tianon** [comment]
This is something that could be implemented via a volume driver today, right?

**Comment by cpuguy83** [comment]
I would almost prefer to be able to disable recursive binds which would allow users to manually RO-bind each mountpoint.

**Comment by AkihiroSuda** [comment]
> This is something that could be implemented via a volume driver today, right?

Yes: https://github.com/AkihiroSuda/securebind-docker
But I'm wondering it might makes sense to have this as a standard feature (in long-term)

> I would almost prefer to be able to disable recursive binds which would allow users to manually RO-bind each mountpoint.

+1 to have `bind-disable-recursive` either way

**Comment by AkihiroSuda** [comment]
@brauner is working on kernel-side fix.

My FUSE proposal can be withdrawn if his patch is going to be merged.

**Comment by AkihiroSuda** [comment]
PR for `--mount type=bind,bind-norecursive`: https://github.com/moby/moby/pull/38003 https://github.com/docker/cli/pull/1430

**Comment by AkihiroSuda** [comment]
Closing this for now, as `BindOptions.NonRecursive` is implemented https://github.com/moby/moby/pull/38003

**Comment by AkihiroSuda** [comment]
Kernel 5.12 gained support for fully recursively-readonly mounts.

Integration to OCI is discussed in https://github.com/opencontainers/runtime-spec/pull/1090
