### ISSUE TITLE
Can only create one container (per host) with shared network stack on Windows Server 2019, build 17744

### ISSUE THREAD

**Issue by natalieparellano** [moby/moby#37832]
**Description**

We are only able to create one container (per host) that shares the network stack of another container. If we try to create two such containers, this fails with "CreateComputeSystem <guid>: The parameter is incorrect."

**Steps to reproduce the issue:**
1. `docker run -d --name main-container-1 mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001 powershell -command 'sleep(10000)`
2. `docker run -d --name main-container-2 mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001 powershell -command 'sleep(10000)'`
3. `docker run -d --name sidecar-container-1 --network container:main-container-1 mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001 powershell -command 'sleep(10000)'`
4. `docker run -d --name sidecar-container-2 --network container:main-container-2 mcr.microsoft.com/windowsservercore-insider:10.0.17744.1001 powershell -command 'sleep(10000)'`

**Describe the results you received:**

The first 3 commands succeed. The 4th command fails with "CreateComputeSystem <guid>: The parameter is incorrect."

**Describe the results you expected:**

All 4 commands should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

This seems to happen consistently.

**Output of `docker version`:**

```
Client:
 Version:           master-dockerproject-2018-09-11
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        82dff32b
 Built:             Tue Sep 11 23:50:35 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          master-dockerproject-2018-09-11
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.11
  Git commit:       738994f
  Built:            Tue Sep 11 23:59:21 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 25
 Running: 3
 Paused: 0
 Stopped: 22
Images: 1
Server Version: master-dockerproject-2018-09-11
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17744 (17744.1001.amd64fre.rs5_release.180818-1845)
Operating System: Windows Server Datacenter Version 1809 (OS Build 17744.1001)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 32GiB
Name: WIN-FNVIDPHLRGJ
ID: QG22:AXKG:QMH2:VFGG:DOMZ:FFDF:KU2W:DIYP:SRPQ:4GGK:W4SH:BSWQ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by natalieparellano** [comment]
This appears to be fixed in the GA version of Windows Server 2019!

**Comment by thaJeztah** [comment]
Thanks for the update @natalieparellano - let me go ahead an close this ticket; feel free to continue the conversation though! 👍

**Comment by achasveachas** [comment]
@thaJeztah, It seems that this broke again in the latest 2019 release. 

We reproduced this the same way it was recommended above (substituting the image for `mcr.microsoft.com/windows/servercore:ltsc2019`) and got the following error:
`encountered an error during CreateContainer: failure in a Windows system call: The parameter is incorrect.`

**Comment by achasveachas** [comment]
Interestingly, we tried reproducing the issue on Windows Server version 1903 (windows server semi-annual preview ISO - build 18282), but it looks like it was fixed there.

**Comment by michmike** [comment]
@achasveachas it was recommended to see if you and your team is able to create a test in the K8s test suite for sig-windows that captures this use case. do you all have that bandwidth?

**Comment by natalieparellano** [comment]
Hey @michmike I work on the same team as @achasveachas - we aren't familiar with the K8s test suite, I'm not sure how to even begin creating a test there unfortunately. Is there a reason the repro with docker isn't sufficient to demonstrate the issue?

**Comment by michmike** [comment]
@natalieparellano no problem. @dineshgovindasamy is looking into this from Microsoft

**Comment by dineshgovindasamy** [comment]
@natalieparellano @michmike @achasveachas Thanks for reporting this bug.

I was able to root cause this issue and we have already fixed them in 1903. we are working on backporting this fix to 2019. A little bit background on the issue.

This looks like a compiler optimization bug. We have a function signature where compiler sometime calls the wrong function due to an ambiguity in the signature resolving. Unfortunately this doesn't repro on our local tests and builds, it only repro'd on release bits. Very strange bug that shows up only on few systems and few builds.

We have proper tests validating this core scenario of 2 container sharing a network namespace, unfortunately these tests are still succeeding when we released the build. So some release specific optimization that is kicking in.

**Comment by michmike** [comment]
thanks Dinesh!

**Comment by PatrickLang** [comment]
This will be fixed in a Windows patch, current ETA late January. Windows OS bug number is 19831298

**Comment by daschott** [comment]
Can you validate that this is fixed in KB4476976. ETA for release is tomorrow.

**Comment by yharel** [comment]
We followed the reproduction steps and we can confirm that the issue was fixed with KB4476976.

**Comment by michmike** [comment]
thank you all!

**Comment by daschott** [comment]
@natalieparellano can we close this issue?

**Comment by natalieparellano** [comment]
Yes, this is all fixed - thank you!!
