### ISSUE TITLE
docker overrides containerd runtime configuration?

### ISSUE THREAD

**Issue by colemickens** [moby/moby#37856]
**Description**

`containerd+ctr run` = works
`containers+docker+docker run` = doesn't work

**Steps to reproduce the issue:**

First, observe that the system originally just uses `docker` and works fine. No errors about `docker-runc`.
Next:

1. Run `containerd`.
2. Sanity check it with `ctr`
    ```
    image="docker.io/library/redis:alpine"

    ctr container delete redis0
    ctr images pull "${image}"
    ctr run \
       --runtime "${RUNTIME}" \
       "${image}" redis0
    # works, hurray!
    ```
3. Configure dockerd to use `--containerd=/run/containerd/containerd.sock`
4. `docker run -it ${image}` results in: ` docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/d67148e0804441e8b2f3c30fa4804f48751546ffaf760a4644bb44a5700e71cc/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: : unknown.

I think this is due to how my operating system is laid out, such that containerd doesn't have access to the same environment that docker has.

But, I don't understand why this is happening. `containerd + ctr` work just fine, implying that `containerd` knows how to find and invoke the `runc` that I have made available to it. It seems that `docker` is somehow telling containerd to use `docker-runc`? Is this the case, and if so, why is `dockerd` able to dictate that to `containerd`? I was hoping to just configure `containerd` and be done with it.

(I suspect this is just my mis-understanding of the roles of dockerd/containerd when used together.)

This is happening with `docker 18.06.1-ce` and `containerd 1.2.0-beta.3`.

**Comment by colemickens** [comment]
This article also seems to demostrate that docker must be taught about the custom `runc` rather than it being specified to `containerd` as a (the default) runtime.

Maybe this will change as `containerd` is learning to support multiple runtimes, and instead `docker` would just passthrough a runtime name and leave the configuration in `containerd`?

**Comment by cpuguy83** [comment]
The configuration is specified on the Docker daemon and passed through to containerd.

https://docs.docker.com/engine/reference/commandline/dockerd/

See "--add-runtime" and "--default-runtime".

Docker packages its own runc right now, as such this is what's used as the default runtime.

**Comment by colemickens** [comment]
Yeah, I sort of pieced it together and worked around this by teaching dockerd about a new runtime (`runc`) that exists in the `PATH` that it sees. It's fine for now, I'll probably drop it anyway as I don't really need `dockerd` anyway; was just a nice to have.

Also, I think I was incorrectly thinking about the *cri* default/untrusted workload runtimes as being the containerd runtimes.

Thanks for clarifying, closing this...
