### ISSUE TITLE
docker exec -i sometimes hangs if stdin is empty

### ISSUE THREAD

**Issue by felixfontein** [moby/moby#37870]
**Description**
When running `docker exec -i <container> /bin/bash -c cat` (or something else which is waiting for input from stdin) and pipe an empty file into it, this often hangs.

**Steps to reproduce the issue:**
1. `docker run -d --name docker-test ubuntu:latest /bin/bash -c "sleep 1h"`
2. Repeatedly run `cat /dev/null | docker exec -i docker-test /bin/bash -c cat`
3. Wait until one of the calls hangs

**Describe the results you received:**
Sometimes, `cat /dev/null | docker exec -i docker-test /bin/bash -c cat` hangs indefinitely.

**Describe the results you expected:**
`cat /dev/null | docker exec -i docker-test /bin/bash -c cat` always returns immediately.

**Additional information you deem important (e.g. issue happens only occasionally):**
---

**Output of `docker version`:**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.11
 Git commit:        e68fc7a215
 Built:             Fri Sep  7 11:26:59 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       e68fc7a215
  Built:            Fri Sep  7 11:26:11 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
(This has also been observed with other versions of docker: https://github.com/ansible/ansible/issues/36725)

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 77
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.7-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57GiB
Name: mymachine
ID: JFYF:V2G4:IYL3:HDXW:FM4Y:R6XI:IFAX:QL6P:7OBG:OJNL:Y4O3:O5A3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: felixfontein
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by AkihiroSuda** [comment]
reproducible on master

**Comment by thaJeztah** [comment]
Reopening this, because https://github.com/moby/moby/pull/38001 should be vendored into the cli first

**Comment by AkihiroSuda** [comment]
@thaJeztah it is libcontainerd client, not docker client..

**Comment by thaJeztah** [comment]
@AkihiroSuda oh! That's what you get for trying to do multi-tasking 😅
