### ISSUE TITLE
Missing partial metadata for fluentd

### ISSUE THREAD

**Issue by vatcher** [moby/moby#37889]
https://github.com/moby/moby/blob/d6a7c22f7b9aa028623ef8c7cb31d1bb04dd9d84/daemon/logger/fluentd/fluentd.go#L166

In this case it is not enough to set the boolean. It is also important to add values of `PLogMetaData` to data.
i.e.
```go
if msg.PLogMetaData != nil {
    data["partial_message"] = "true"
    data["partial_id"] = msg.PLogMetaData.ID
    data["partial_ordinal"] = strconv.Itoa(msg.PLogMetaData.Ordinal)
    data["partial_last"] = strconv.FormatBool(msg.PLogMetaData.Last)
}
```
The same extension is needed for journald: https://github.com/moby/moby/blob/9c65b2206dbc4d950fcf40f94c9c05bd9130536c/daemon/logger/journald/journald.go#L107

**Comment by ju-la-berger** [comment]
Please fix this!

**Comment by thaJeztah** [comment]
@vatcher are you interested in opening a pull request for these changes?

**Comment by opteemister** [comment]
Any updates on this?

**Comment by dsouzajude** [comment]
+1 We'd really like this to get fixed. Please give us some updates.

**Comment by dsouzajude** [comment]
Hmm, just checked, correct me if i'm wrong, but it seems the desired change is updated in master for fluentd? (3 months ago)
https://github.com/moby/moby/blob/master/daemon/logger/fluentd/fluentd.go#L166-L171

**Comment by cpuguy83** [comment]
Yep. Thanks!

**Comment by dsouzajude** [comment]
@cpuguy83 Is this released? I still don't see the partial metadata in docker [18.09.6](https://docs.docker.com/engine/release-notes/), just `partial_message: true`

**Comment by cpuguy83** [comment]
It will be in 19.03, which is currently in the RC phase.
