### ISSUE TITLE
[Feature Request] Enhance docker volume mount logic to handle loop devices by itself

### ISSUE THREAD

**Issue by popsUlfr** [moby/moby#37893]
Hello everyone,

while working on my system sourcing buildroot images as base for docker images and wanting to handle configuration files in a way that could be easily moved to different systems, I was looking into being able to use files as read only volumes.

The volume subsystem of docker only likes having block devices for the device parameter while `mount` is capable of handling files by automatically reserving a loop device.
I was wanting to be able to use a squashfs image as volume that could be mounted as config location inside a container since it was the closest to a transportable `.tar` that I could think of.

Creating the volume goes without issue :
`docker volume create -d local -o type=squashfs -o device=$(pwd)/pia.squashfs`

But mounting it into the container would yield a `block device required` error.

Mount is capable of handling this itself : 
`mount -o loop pia.squashfs /mnt/pia`

which is actually doing: 
`losetup -f pia.squashfs`
`mount -t squashfs /dev/loopX /mnt/pia`

So doing the `losetup` beforehand and then using `/dev/loopX` as `device=` works for mounting it as volume.

So it would really be useful if one could tap into the features already exposed by the native mount command.

My suggestion would maybe be for the volume docker subsystem get closer to the native system mount capabilities or to allow the subsystem to use normal files for the `device=` parameter.

Right now I can push around my docker-compose stuff alongside the neatly squashed configuration stuff, and use a script on the different hosts to set up the loop device for mounting. It would make it less tedious though to expose the full `mount` capabilities in the docker mount subsystem.

**Comment by cpuguy83** [comment]
>  get closer to the native system mount capabilities

The `mount` command is magic on top of the `mount` system call.
Docker's built-in "local" driver is only calling the mount system call. It can't get any closer to the system than that.... with the exception that for type=nfs it will attempt a DNS lookup for the NFS host address (because the kernel module does not).

I don't think it would be wise to add a bunch of magic here, even if it is convenient.
A driver which sets up loop devices could do this easily enough.

**Comment by thaJeztah** [comment]
I agree that we should not add too much magic here. This proposal might be of interest to you though; https://github.com/moby/moby/issues/30449
