### ISSUE TITLE
Rest API /exec/<container id>/start accepting method POST only

### ISSUE THREAD

**Issue by rptl** [moby/moby#37898]
It's happening on both CE and EE/UCP rest api.

/containers/[container]/attach/ws - accepts GET method
/exec/[container/start - accepting only POST method (leading to 404)

According  https://tools.ietf.org/html/rfc6455#section-4.1 - it must be GET.

> The requirements for this handshake are as
>     follows.
> 
>         The handshake MUST be a valid HTTP request as specified by
>         [RFC2616].
> 
>         The method of the request MUST be GET, and the HTTP version MUST
>         be at least 1.1.

**Comment by cpuguy83** [comment]
Indont understand. "Start" is not a websocket endpoint.

**Comment by rptl** [comment]
Thanks for your reply.  Then I probably misunderstood '/exec/<execid>/start'.  I thought it was similar to to attach.
How can I execute a command into container and get Tty, similar to 'docker exec -it container bash' or any other command using Rest API?

**Comment by cpuguy83** [comment]
`docker exec` is doing 3 things here:

1. Create the exec
2. Attach to the exec (it's not running yet, but we attach so as to not lose any output once it is started)
3. Start the exec

**Comment by rptl** [comment]
Thanks for you clarification.

I am missing  step 2. How can I attach to an exec instance using API?

**Comment by cpuguy83** [comment]
Sorry, exec is a bit different than container (my mistake)...
There is no websocket endpoint for attaching to an exec.

https://docs.docker.com/engine/api/v1.37/#operation/ExecStart

There is only the start endpoint which will either stay attached for detach depending on options passed to the endpoint.

**Comment by rptl** [comment]
`Start an exec instance

Starts a previously set up exec instance. If detach is true, this endpoint returns immediately after starting the command. Otherwise, it sets up an interactive session with the command.
`

Ok, then I should be able to interact with HTTPS post request (if detach is set to false)?

**Comment by cpuguy83** [comment]
Yes.
