### ISSUE TITLE
Multi stages builds: prevent building useless stages

### ISSUE THREAD

**Issue by jlamur** [moby/moby#37905]
Suppose you have this Dockerfile where the `production-env` stage does not use `dev-env` files anywhere.
 
```
FROM debian AS build-env
...

FROM alpine AS dev-env
# use build-env files here
...

FROM alpine AS production-env
# use build-env files here
...
```

When you trigger a build with `docker build --target dev-env Dockerfile`, no problem, only the `build-env` and `dev-env` stages are built.

Now, if you trigger a build for the `production-env` stage, all stages are built, resulting in a useless build of the `dev-env` stage.

Questions:
1. Is this a bug?
2. If not, it seems to me that finding dependencies between steps is a computable problem (since both `FROM <previous-step>` and `COPY --from <previous-step>` only accept literals), so it should not be a huge deal to implement it. Is this a feature users would like to see in docker?

**Comment by cpuguy83** [comment]
This (should) work as expected if you use the buildkit builder backend.

On 18.06 you must set the daemon to experimental and "DOCKER_BUILDKIT=1" on the CLI.

Going to close this because this is a solved issue, just that for now buildkit must be manually enabled.

Thanks!

**Comment by usernamefghh** [comment]
37905
