### ISSUE TITLE
Huge syscall overhead when host-image OS miss match

### ISSUE THREAD

**Issue by dskarlatos** [moby/moby#37902]
I'm benchmarking syscall performance on docker. I wrote a simple getpid benchmark that iterates over the syscall. When the image and the host OS are similar e.g host ubuntu 16.04 and image is ubuntu 16.04 I get similar performance inside docker and on native. 
Although, if I'm running the same experiment on the same host ubuntu 16.04 but with an image based on ubuntu 18.04 the performance inside docker gets a huge hit. I did some perf analysis and most of the time comes from seccomp, 61% on syscall_trace_enter_phase1 and 18% on entry_SYSCALL_64_after_swapgs. If the host and image match both overheads go away. I also tried the same experiment with an unconfined image and the overhead still remains high because of entry_SYSCALL_64_after_swapgs.

My understanding is that due to OS miss match syscalls get routed differently but I'm not sure where this is handled in docker. Any pointers on why this is happening and how to go about fixing it, would be greatly appreciated!

**Measurements:**
Native: **2.713928s**
Docker (host==image): **2.723255s**
Docker (host != image): **97.801589s**
Docker (host != image && --security-opt seccomp=unconfined: **37.046339s**

**System:**
Docker: 17.06.1-ce
OS: Ubuntu 16:04, kernel 4.4.0-101
CPU: Intel(R) Xeon(R) CPU E5-1630 v3

**Benchmark Code:**
```
#define COUNT   1000000000
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include <unistd.h>

int main( int argc, const char* argv[] ){
    int rc;
    int i;
    int count;
    clock_t begin, end;
    count = COUNT;
    begin = clock();

    for ( i = 0; i < count; i++) {
        rc = getpid();
    }

    end = clock();
    printf("rc %d\n",rc);
    double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
    printf("Time %lf \n", time_spent);
}
```

**Dockerfile:**
```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y vim && apt-get install build-essential -y

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN gcc -O3 -Og -ggdb -g3 -fno-omit-frame-pointer bench.c -o myapp
ENTRYPOINT ["./myapp"]
```
**Commands:**
```
docker build -t syscall_bench .
docker run -ti  syscall_bench
docker run -ti --security-opt seccomp=unconfined syscall_bench
```

Cheers,
Dimitrios

**Comment by justincormack** [comment]
Between Ubuntu 16.04 and 18.04, Glibc changed the behaviour of `getpid`. In older versions, Glibc maintained a pid cache, so it would not actually perform the syscall at all after the first time. They removed this cache as it would break some use cases, eg with the `clone` syscall. (See Linus's complaint https://yarchive.net/comp/linux/getpid_caching.html for example). So if you compile a container for Ubuntu 16.04 it only calls the `getpid` syscall once, versus every time in 18.04.
