### ISSUE TITLE
LCOW: Linux containers take too long to stop

### ISSUE THREAD

**Issue by jtsalten** [moby/moby#37919]

**Comment by jtsalten** [comment]
I've just installed the Docker last version available for Windows 10 Pro (18.09.0-ce-beta1
) . When Running on mode Windows Containers to be able to run Linux and Windows containers at same time I realize that I can't stop the Linux ones.
If I run, for example, docker stop ubuntu it keeps waiting more than 5 minutes till the container is stopped (it should take seconds).
Also docker kill ubuntu doesn't work.
To stop it quickly I have to run hcsdiag kill , but I think is not the right way.

On the other side I can stop/kill perfectly a windows container with: docker stop nano or docker kill nano (being nano the name of a windows container)

Docker Version:
Server Version: 18.09.0-ce-beta1
Storage Driver: windowsfilter (windows) lcow (linux)

**Comment by jtsalten** [comment]
A basic ubuntu container takes 30 seconds to stop. An IRIS container (also based on Ubuntu) takes up to 5 min... it shouldn't take more than 1 min.

Console output:
PS C:\Users\salva> docker ps
CONTAINER ID        IMAGE                                                              COMMAND             CREATED             STATUS                             PORTS                                              NAMES
88fd8bf51b6b        docker.iscinternal.com/intersystems/iris:2018.2.0.491.0qdtestsys   "/iris-main"        25 hours ago        Up 40 seconds (health: starting)   0.0.0.0:5173->51773/tcp, 0.0.0.0:5273->52773/tcp   iris
PS C:\Users\salva> Get-Date; docker stop iris; Get-Date

miércoles, 26 de septiembre de 2018 20:21:13
iris
miércoles, 26 de septiembre de 2018 20:26:21


PS C:\Users\salva> docker start ubuntu
ubuntu
PS C:\Users\salva> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
37d12e01f2e9        ubuntu:latest       "/bin/sh"           9 minutes ago       Up 5 seconds                            ubuntu
PS C:\Users\salva> Get-Date; docker stop ubuntu; Get-Date

miércoles, 26 de septiembre de 2018 20:26:57
ubuntu
miércoles, 26 de septiembre de 2018 20:27:29

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
@jtsalten Can you confirm what kernel you are running for lcow, and where you got it from? I'm guessing/assuming it's from a Docker-For-Windows installation? If so, what version of D4W?

 `docker run --rm alpine uname -r` will get you the kernel version.

And also in the second case, how -exactly- did you create that ubuntu container so I can attempt to repro like-for-like.

**Comment by jtsalten** [comment]
@jhowardmsft sorry for answering late … i didn't see the notification.

running alpine: 4.14.35-linuxkit

I tested with 2 images, one the basic ubuntu, pulled from docker store. The other was an InterSystems IRIS image based on Ubuntu (published by InterSystems just for customers). Both took more time than expected to stop.

The ubuntu image is public so I guess is easier to reproduce the issue.
I include below output of:
  > docker image inspect ubuntu
  > docker images
  > get-date; docker stop ubuntu; get-date
 
**docker image inspect ubuntu**
PS C:\WINDOWS\system32> docker image inspect ubuntu
[
    {
        "Id": "sha256:cd6d8154f1e16e38493c3c2798977c5e142be5e5d41403ca89883840c6d51762",
        "RepoTags": [
            "ubuntu:latest"
        ],
        "RepoDigests": [
            "ubuntu@sha256:de774a3145f7ca4f0bd144c7d4ffb2931e06634f11529653b23eba85aef8e378"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-09-05T22:20:12.306501594Z",
        "Container": "9ec7e3534677f7131ca24d817f350f61a5f55b90213e72639a5d4544bc4ca661",
        "ContainerConfig": {
            "Hostname": "9ec7e3534677",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/bash\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:7305906e8de52626527daa8a6d557980a47021e3ad0fbc59259c63f9d09abd78",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "17.06.2-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:7305906e8de52626527daa8a6d557980a47021e3ad0fbc59259c63f9d09abd78",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 121113088,
        "VirtualSize": 121113088,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\lcow\\55ff159f03bbb53445c9b458a96fe1c8ea6975999c6468f0977eecb9de90b589"
            },
            "Name": "lcow"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:a30b835850bfd4c7e9495edf7085cedfad918219227c7157ff71e8afe2661f63",
                "sha256:6267b420796f78004358a36a2dd7ea24640e0d2cd9bbfdba43bb0c140ce73567",
                "sha256:f73b2816c52ac5f8c1f64a1b309b70ff4318d11adff253da4320eee4b3236373",
                "sha256:6a061ee02432e1472146296de3f6dab653f57c109316fa178b40a5052e695e41",
                "sha256:8d7ea83e3c626d5ef1e6a05de454c3fe8b7a567db96293cb094e71930dba387d"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**docker images**

REPOSITORY                                 TAG                       IMAGE ID            CREATED             SIZE
jtsalvador/iris                            jtsc                      074807d28fa4        26 minutes ago      1.64GB
alpine                                     latest                    196d12cf6ab1        2 weeks ago         6.82MB
ubuntu                                     latest                    cd6d8154f1e1        3 weeks ago         121MB

**docker stop**
_(get-date; docker stop ubuntu; get-date)_

PS C:\WINDOWS\system32> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS                                              NAMES
b99ff108f394        074807d28fa4        "/iris-main"        9 minutes ago       Up 8 minutes    0.0.0.0:5175->51773/tcp, 0.0.0.0:5275->52773/tcp   jts2018c
5d25f8cbabf0        ubuntu              "bash"              13 minutes ago      Up 6 minutes                                                                  ubuntu
PS C:\WINDOWS\system32> get-date; docker stop ubuntu; get-date

martes, 2 de octubre de 2018 12:54:06
ubuntu
martes, 2 de octubre de 2018 12:59:09

**Comment by mrfrankbell** [comment]
Seeing the same on fresh install of Docker Desktop v2.0.0.0-win78 (28905) on Windows 10 1809.

```
PS C:\WINDOWS\system32> docker pull nginx:alpine
alpine: Pulling from library/nginx
4fe2ade4980c: Pull complete
e11b023b07a0: Pull complete
aaf7d5908de5: Pull complete
8ae3a5ca453f: Pull complete
Digest: sha256:41dbd69d560c20712f90011689596f20a5db6d7f85436edda7f177a2e53d4da2
Status: Downloaded newer image for nginx:alpine
PS C:\WINDOWS\system32> docker run -d nginx:alpine
f4a23f43c9a589f41b3a908aabe85eefda8a307b4ef813fc2c9b20e19afb6766
PS C:\WINDOWS\system32> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f4a23f43c9a5        nginx:alpine        "nginx -g 'daemon of…"   10 seconds ago      Up 6 seconds        80/tcp              amazing_knuth
PS C:\WINDOWS\system32> get-date; docker stop f4a23f43c9a5; get-date

20 November 2018 12:49:44
f4a23f43c9a5
20 November 2018 12:54:49
```

Results of docker info:

```
PS C:\WINDOWS\system32> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.0
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows 10 Pro Version 1809 (OS Build 17763.134)
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 31.92GiB
Name: *******
ID: 5YGG:JBRH:KC5D:MXVS:XN3B:AMSI:VDZL:YICW:OPZZ:VUP3:D7L2:MWYW
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 28
 System Time: 2018-11-20T12:55:11.7222861Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by joostmeijles** [comment]
Same issue here, seems to be intermittent.
It's however quite annoying.

Any ETA on a fix for this?

**Comment by Barsonax** [comment]
Also waiting for a fix for this. Any ETA?

**Comment by jhowardmsft** [comment]
Absolutely not related to #37583. I suspect more likely it's the linuxkit kernel rather than docker itself. I'll try to investigate over the next few days. If someone can attach the relevant linuxkit kernel to a comment here, I can compare and contrast the performance of an internally built kernel to the linuxkit one.

**Comment by jhowardmsft** [comment]
Actually - don't need the above. It's available at https://github.com/linuxkit/lcow/releases/tag/v4.14.35-v0.3.9

**Comment by hulucc** [comment]
Maybe a workaround: docker kill -s 9

**Comment by jterry75** [comment]
@jhowardmsft - Do you have the logs timestamps between the signal notify and the hcsshim Wait return? We can eliminate the GCS between those two traces.

**Comment by Logiqx** [comment]
I'm seeing exactly the same behaviour; attempting to stop LCOW containers takes 300 seconds.

In an attempt to find a workaround, I've tried "docker attach" to send a ctrl-c but that hasn't worked either.

My Docker Compose file is available on [GitHub](https://github.com/Logiqx/logiqx-www/tree/master/docker). It's a simple two container NGINX and PHP-FPM setup which runs fine using LCOW but it can't be stopped cleanly.

Using docker kill isn't super-critical for containers that I regard as both immutable and ephemeral but it's not ideal for containers which write persistent data to a volume / bind mount, etc.

Docker version:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

Docker info:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: fkpezvdswhcj82aggd46l0b18
 Is Manager: true
 ClusterID: zswgp20g71sn240wvbptjv7hm
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.8GiB
Name: linuxkit-00155db9b108
ID: AZKJ:OHY4:HRZQ:XN26:Z4U2:2PZ6:B7JX:LWDN:6HKX:EPSL:MJJE:5SL2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 167
 System Time: 2019-04-13T18:57:36.7022241Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by desertspider** [comment]
Can confirm this problem still exist with kernel 4.19.27.

**Comment by moikot** [comment]
The same for me. I'm running Windows 10 1903

```
docker run --name some-redis -d redis
docker stop 
```

Docker version:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by desertspider** [comment]
> The fact that this issue is present and not many people complain, makes me wonder how popular LCOW is.

For me it is a deal breaker using docker on windows. I need host serial integration, so i need windows containers, but i also need linux containers but cannot do so because of this bug. Using linux only containers also is no option because of the delayed samba initiation bug.  (and of course because no serial).
Docker is just mostly used on Linux, for good reason considering docker on Linux is more mature. Luckily docker on windows is getting more mature day by day.

**Comment by mibollma** [comment]
Same issue here in latest stable release.
It's quite annoying as I have to run linux and windows containers at the same time.
Anyone has found some workarounds?

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by guillaume86** [comment]
I have a similar issue, not sure if the same but maybe related:
I started the `linux mozillaiot/gateway` image in lcow mode and it wouldn't respond to any docker command or http request, even waiting +5 mins. I restarted my machine and it still shows up as running with `docker ps`. 

`hcsdiag list` do not show anything, does it mean it's not running?
How can I force remove it from docker in that case?

Here's the docker inspect:
```
[
    {
        "Id": "9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5",
        "Created": "2019-08-02T21:50:47.8821763Z",
        "Path": "/usr/bin/runsvdir",
        "Args": [
            "/etc/service"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 302,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-02T21:50:48.94078Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:a90bd7c9dcbbf878c6114483d6f845dc9d491905835a979de1ab2a31b9fdeeff",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5\\9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5-json.log",
        "Name": "/mozilla-iot-gateway",
        "RestartCount": 0,
        "Driver": "lcow",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4443"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                50,
                120
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\lcow\\9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5"
            },
            "Name": "lcow"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "9e05c58064c4",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4443/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=8.16.0",
                "YARN_VERSION=1.15.2",
                "gateway_addon_version=@v0.9.0",
                "gateway_url=https://github.com/mozilla-iot/gateway",
                "gateway_branch=v0.9.1"
            ],
            "Cmd": null,
            "Image": "mozillaiot/gateway:latest",
            "Volumes": null,
            "WorkingDir": "/home/node",
            "Entrypoint": [
                "/usr/bin/runsvdir",
                "/etc/service"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4443"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "9e05c58064c4be89eafdc2df72fe730e80c221e8f377a4d6c2f13ca2bedffdb5",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a26bf546e61f74c57ab0ddb5cd8bcd8f5053fa57541c01b6515427170332ce3b",
                    "EndpointID": "94763bab4d3eee2f9019aa88b051ba3f3f78adee164503070c895e9ca9afaefe",
                    "Gateway": "172.25.32.1",
                    "IPAddress": "172.25.34.56",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:f4:55:72",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by moikot** [comment]
@mibollma There is one workaround but it might work for some stateless containers only,
```
docker stop --time=0 foo
```
Forces docker to send SIGKILL immediately instead of sending SIGTERM and waiting.

**Comment by mibollma** [comment]
@moikot Thanks for the hint. 
I started using `docker kill -s 9 foo` which seems to do pretty much the same. Hope it will be fixed some day.

**Comment by nevrax** [comment]
docker daemon has no setting like a timeout for stopping containers. stop --timeout or kill --signal are arguments passed by the client to the daemon.

having lcow on widows with --restart always per container will end up in a bad experience. it takes less time rebooting the physical or virtual server.

**Comment by Enf0** [comment]
I'm experiencing the same issue and it's making Docker on Windows useless for me. It takes 5 minutes each time I want to stop/restart a container. Is there a fix for this soon?

**Comment by ROBOTFALLOS** [comment]
Had the same issue on Windows Server 2019 1809 with **4.14.35-linuxkit**. I seem to have resolved it by downgrading to **4.14.29-linuxkit** (need to do more testing, but the delay is gone).

Docker version:
```
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       f660560464
  Built:            07/25/2019 20:57:41
  OS/Arch:          windows/amd64
  Experimental:     true
```
Also works with Docker EE 18.09.8.

**Comment by crossan007** [comment]
I'm getting a similar issue on Windows Server 2019 with Docker Engine `Server Version: 19.03.1`  and linuxkit version:
```
linuxkit version v0.6+
commit: ddb0fa509e6163bfbd71e9114ce8170b0a53c4fa
37595ab0d333ded65c58e3041d4dc9486e269d5c
```

**Comment by MattGarnettWelsh** [comment]
So far the only effective measure we've found to combat the long wait in a stateless container is to run the command from @hulucc :

**docker kill -s 9**

**Comment by martcastaldo** [comment]
Having the same issue, its taking about 10 minutes to kill all containers when using LCOW

**Comment by danny-p93** [comment]
I think i have the same problem. I'm running a (virtual) Microsoft Server 2019 (Version1809 - Build 17763) as an airgapped System with no Internet Connection. It uses the recent stable Docker Build:

Output docker version:
``` 
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     true
```

As you can see the experimental flag is enabled for execute LCOW. Just for testpurposes i run a local node Project Image, that has no problems on Photon OS (Linux based and docker optimized OS) to start and stop.
So as i tried the same image on Docker for Windows i had the same issue as described here, that it takes a few minutes to stop that container.
My experience was, that docker kill took as long as docker stop.
The fastest way for me is the solution that @moikot recommended. With docker stop -t=0 it sends signal 15 and 9 in short sequenze to the client forcing the container to stop almost immediatly.
But i was not able to find out in detail what is different when looking in the docker event-logs.

**Comment by ndarlington** [comment]
> ...
> The fact that this issue is present and not many people complain, makes me wonder how popular LCOW is.
_Originally posted by @moikot in https://github.com/moby/moby/issues/37919#issuecomment-495772381_

Just waiting in the wings, this had been bugging me for 9+ months now, but not much to do except hope it gets fixed.  Too few Windows containers available (or software just not running in them) to not use LCOW.

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
