### ISSUE TITLE
Latest 18.06.0-CE version ignores NO_PROXY settings

### ISSUE THREAD

**Issue by stefantrimborn** [moby/moby#37946]
**docker-18.06.0-ce on ubuntu ignores NO_PROXY environment or dockerd settings**

When using a proxy and exceptions are defined following the documentations here: _https://docs.docker.com/network/proxy/ the docker cli ignores the set exceptions_

Using an UCP client-bundle, we try to connect to a local UCP, bypassing the proxy. 
The error during connect: _Get https://ucp.example.de:443/v1.38/containers/json: proxyconnect tcp: read tcp 127.0.0.1:55370->127.0.0.1:3128: read: connection reset by peer_
If you downgrade to docker-18.03.1-ce the environment settings are wokring fine.

**How to reproduce:**
1. Set up an environment on ubuntu which uses a proxy
2. Install docker-18.06.0-ce and set it up to talk to a local repository (e.g. DTR)
3. Set up docker to bypass local address: see also: https://docs.docker.com/network/proxy/
4. Enable UCP client bundle
5. Try a cluster related command, e.g. docker ps
6. Error: Get https://ucp.example.de:443/v1.38/containers/json: proxyconnect tcp: read tcp 127.0.0.1:55370->127.0.0.1:3128: read: connection reset by peer > The proxy is not passed.
6. Downgrade to Version docker-18.03.1-ce, the login will work, without changing any configs

**Results:**
- docker-18.06.0-ce ignores all proxy bypass settings
- docker-18.03.1-ce works as designed

**Additional info:**
Test environment was a on-prem ubuntu installation, trying to bypass a localy installed proxy to connect to a local UCP management cluster.

**Comment by thaJeztah** [comment]
Note that the https://docs.docker.com/network/proxy/ section describes how to setup proxy-configuration for individual _containers_, not for the docker cli, or for the daemon itself. 

> Try a cluster related command, e.g. docker ps

Note that `docker ps` is not a "cluster command" (but when UCP, the UCP API _does_ execute this command on all nodes).

From the error message ("Error: Get https://ucp.example.de:443/v1.38/containers/json: proxyconnect"), it looks like you want to configure the docker _cli_ to not use a proxy; to configure the CLI to use (or "skip") using a proxy, you need to have the `NO_PROXY` environment variable set in the shell where you run the command; what does `env` show in your shell? Does it have the `NO_PROXY` environment variable set?

**Comment by stefantrimborn** [comment]
Here some further information:

Docker Versionen: 
Working: `18.03.0-ce (2018-03-21)`
NOT-Working: `18.06.1-ce (2018-08-21)`

Output of ENV:
```
XDG_VTNR=7
LC_PAPER=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/<hidden>
IBUS_DISABLE_SNOOPER=1
LC_MONETARY=de_DE.UTF-8
TERMINATOR_UUID=urn:uuid:9d4fb45b-1b1a-4cd0-903e-cb255acf1cc1
CLUTTER_IM_MODULE=xim
GPG_AGENT_INFO=/home/<hidden>/.gnupg/S.gpg-agent:0:1
TERM=xterm
SHELL=/bin/bash
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
WINDOWID=81788932
LC_NUMERIC=de_DE.UTF-8
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/<hidden>/2335
GNOME_KEYRING_CONTROL=
GTK_MODULES=gail:atk-bridge:unity-gtk-module
NO_PROXY=localhost,127.0.0.1,172.17.*,10.0.*
http_proxy=http://<hidden>/
LD_LIBRARY_PATH=<hidden>
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_TELEPHONE=de_DE.UTF-8
QT_ACCESSIBILITY=1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/<hidden>/keyring/ssh
FTP_PROXY=https://<hidden>/
ftp_proxy=https://<hidden>/
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
DA_SESSION_ID_AUTH=04fccb55-bff8-40a3-bfd2-42e3d2b93a60
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
DESKTOP_SESSION=ubuntu
PATH=<hidden>
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
LC_IDENTIFICATION=de_DE.UTF-8
XDG_SESSION_TYPE=x11
PWD=/
JOB=gnome-session
XMODIFIERS=@im=ibus
LANG=en_US.UTF-8
GNOME_KEYRING_PID=
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_MEASUREMENT=de_DE.UTF-8
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
PAPERSIZE=a4
https_proxy=https://<hidden>/
GDMSESSION=ubuntu
HTTPS_PROXY=https://<hidden>/
SESSIONTYPE=gnome-session
GTK2_MODULES=overlay-scrollbar
SHLVL=1
HOME=<hidden>
XDG_SEAT=seat0
LANGUAGE=en_US:en
no_proxy=localhost,127.0.0.1,172.17.*,10.0.*
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
HTTP_PROXY=https://<hidden>/
UPSTART_INSTANCE=
PYTHONPATH=<hidden>
UPSTART_EVENTS=started starting
XDG_SESSION_DESKTOP=ubuntu
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
QT4_IM_MODULE=xim
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-gFpee4zkL8
UID=<hidden>
PKG_CONFIG_PATH=<hidden>
LESSOPEN=| /usr/bin/lesspipe %s
INSTANCE=Unity
UPSTART_JOB=unity-settings-daemon
XDG_RUNTIME_DIR=/run/user/<hidden>
DISPLAY=:0
GTK_IM_MODULE=ibus
XDG_CURRENT_DESKTOP=Unity
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
COLORTERM=gnome-terminal
_=/usr/bin/env
```

**Comment by randytan** [comment]
hi there, we also having the same issues when running docker on Windows Server 2016. 
Docker version: 17.06.2-ee-16.

It seems it doesn't honour the proxy settings on the system variables.

**Comment by thaJeztah** [comment]
@stefantrimborn I was trying to reproduce the issue. It took me a bit to reproduce a "proxy" situation (turns out Go won't use a proxy if the destination address is a loopback address 😅).

I don't see a difference in behavior between 18.03 and 18.06, but will keep on digging. One thing I _do_ see is that wildcards in `NO_PROXY` don't seem to work;

Start daemon on a non-loopback address (otherwise no proxy will be used anyway, see: https://github.com/golang/net/blob/c21de06aaf072cea07f3a65d6970e5c7d8b6cd6d/http/httpproxy/proxy.go#L188-L190), and verify we can connect;

```
dockerd -H tcp://172.17.0.8:2375 --iptables=false &

docker -H tcp://172.17.0.8:2375 info --format '{{.ServerVersion}}'
18.06.1-ce
```

verify that HTTP_PROXY is used:

```
HTTP_PROXY=http://blabla.bla:1234 docker -H tcp://172.17.0.8:2375 info --format '{{.ServerVersion}}'
error during connect: Get http://172.17.0.8:2375/v1.38/info: proxyconnect tcp: dial tcp: lookup blabla.bla on 192.168.65.1:53: no such host
```

verify that connection failed when using some bogus IP-address;

```
HTTP_PROXY=http://123.123.123.123:80 docker -H tcp://172.17.0.8:2375 info --format '{{.ServerVersion}}'
^C
```


Try to use `NO_PROXY`

```
HTTP_PROXY=http://123.123.123.123:80 NO_PROXY=localhost,127.0.0.1,172.17.*,10.0.* docker -H tcp://172.17.0.8:2375 info
^C
```

Simplify the `NO_PROXY`;

```
HTTP_PROXY=http://123.123.123.123:80 NO_PROXY=172.17.* docker -H tcp://172.17.0.8:2375 info --format '{{.ServerVersion}}'
^C
```

Remove wildcard:

```
HTTP_PROXY=http://123.123.123.123:80 NO_PROXY=172.17.0.8 docker -H tcp://172.17.0.8:2375 info --format '{{.ServerVersion}}'
18.06.1-ce
```

**Comment by thaJeztah** [comment]
Ok, so it looks like wildcards are indeed not allowed in IP-addresses, only in hosts/DNS, or as a separate value (`*`) to indicate that no proxy should be used at all; https://github.com/golang/net/blob/c21de06aaf072cea07f3a65d6970e5c7d8b6cd6d/http/httpproxy/proxy.go#L39-L52

```
	// NoProxy represents the NO_PROXY or no_proxy environment
	// variable. It specifies a string that contains comma-separated values
	// specifying hosts that should be excluded from proxying. Each value is
	// represented by an IP address prefix (1.2.3.4), an IP address prefix in
	// CIDR notation (1.2.3.4/8), a domain name, or a special DNS label (*).
	// An IP address prefix and domain name can also include a literal port
	// number (1.2.3.4:80).
	// A domain name matches that name and all subdomains. A domain name with
	// a leading "." matches subdomains only. For example "foo.com" matches
	// "foo.com" and "bar.foo.com"; ".y.com" matches "x.y.com" but not "y.com".
	// A single asterisk (*) indicates that no proxying should be done.
	// A best effort is made to parse the string and errors are
	// ignored.
```

**Comment by thaJeztah** [comment]
I don't see any changes in the proxy-detection here; https://github.com/golang/go/blob/go1.9.2/src/net/http/transport.go#L1227-L1259 (compared to https://github.com/golang/go/blob/go1.10.4/src/net/http/transport.go#L1278-L1310)

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
