### ISSUE TITLE
How to read environment variable at run time using Shell Script

### ISSUE THREAD

**Issue by yasikmondal** [moby/moby#37960]
Here I am trying with shell script but If I am not setting the default ENV in docker file it's not taking the value from environment. Can you please tell me how read environment variable at run time instead of reading environment variable during docker compose. Below is my Docker Compose file.

```
FROM node:8
WORKDIR /src
ADD . /src
RUN npm install
RUN npm install -g @dojo/cli
RUN npm install @dojo/cli-build-app@3.0.7
RUN npm install @dojo/cli-upgrade-app --no-save
RUN dojo upgrade app
RUN npm install @dojo/framework
RUN npm uninstall -S -D @dojo/core @dojo/has @dojo/i18n @dojo/widget-core @dojo/routing @dojo/stores @dojo/shim @dojo/test-extras
RUN npm upgrade
RUN npm i @dojo/themes
RUN npm install @dojo/widgets@latest
EXPOSE 80
#CMD ["dojo", "build", "app","--feature","baseUrl=" "echo ${baseUrl}" ,"--mode", "dev", "--serve", "--port", "80"]


RUN echo "#!/bin/bash \n dojo build app --feature baseUrl=$baseUrl -m dev -w -s --port 80"> ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
# Run the generated shell script.
ENTRYPOINT ["./entrypoint.sh"]
```
and I am passing the environment variable at run time like below while running the docker in local.

 `docker run -it --name  dojoapplication -p 80:80 -e baseUrl=http://url.com:8080/ dojoImage:v1`

But if I am mentioning the ENV baseUrl=http://url.com:8080/ (which is default) in docker compose file then it's taking and working properly.

**Comment by thaJeztah** [comment]
Thanks for helping out @scopev24 !


Yes, looking at the reported issue, this doesn't look like a bug, so I'll go ahead and close this issue. Feel free to continue the conversation though!
