### ISSUE TITLE
Query about CopyToContainer in client

### ISSUE THREAD

**Issue by vrongmeal** [moby/moby#38035]
I am receiving an error every time. Can you help me out by an example program about using the following docker command through the SDK:
```
$ docker cp myfile.txt containerID:/path/to/copy
```

What I am doing is:
```go
func AddFileToContainer(containerID string, destinationPath string) error {
	ctx := context.Background()
	content, _ := ioutil.Readfile("myfile.txt")
	reader := bytes.NewReader(content)
	config := types.CopyToContainerOptions{
		AllowOverwriteDirWithFile: false,
	}
	err := cli.CopyToContainer(ctx, containerID, destinationPath, reader, config)
	if err != nil {
		return err
	}
	return nil
}
```

**Comment by vrongmeal** [comment]
EDIT:

I read that the content must be a tar archive.
The new code is:

func AddFileToContainer(containerID string, destinationPath string) error {
	ctx := context.Background()
	content, _ := ioutil.Readfile("myfile.txt")
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	header := &tar.Header{
		Name: filename,
		Mode: mode,
		Size: int64(len(content)),
	}
	_ := tw.WriteHeader(header)
	_, _ = tw.Write(content)
	_ = tw.Close()
	reader := tar.NewReader(content)
	config := types.CopyToContainerOptions{
		AllowOverwriteDirWithFile: false,
	}
	err := cli.CopyToContainer(ctx, containerID, destinationPath, reader, config)
	if err != nil {
		return err
	}
	return nil
}

**Comment by cpuguy83** [comment]
You need to flush the tar writer, I think.

**Comment by vrongmeal** [comment]
@cpuguy83 when calling `Close()`, or even `WriteHeader()` flushes the padding

According to documentation:
> This is unnecessary as the next call to WriteHeader or Close will implicitly flush out the file's padding.

**Comment by cpuguy83** [comment]
So this is all quite involved, I would recommend reading the docker CLI implementation: https://github.com/docker/cli/blob/master/cli/command/container/cp.go#L182

**Comment by vrongmeal** [comment]
@cpuguy83 Thanks, that was really helpful, did not notice, there was already a package `github.com/docker/docker/pkg/archive` for the same :-)

**Comment by thaJeztah** [comment]
Looks like this ticket can be closed, but feel free to continue the conversation 👍
