### ISSUE TITLE
[Enhancement] add VxLAN port configuration support in "swarm init"

### ISSUE THREAD

**Issue by selansen** [moby/moby#38030]
Currently VxLAN default port is 4789 in swarm cluster. This value is not configurable at present.
This proposal will allow user to configure VxLAN  UDP port number during swarm init.  This way if anyone blocks VxLAN default port 4789 for swarm cluster, by changing default port to different value we will be able to still send/receive VxLAN packets on new port.
 

The change will be in 4 components. CLI, Moby, SwarmKit and  Libnetwork.
IANA procedures for each range in detail
the Well Known Ports, aka the System Ports, from 0-1023
the Registered Ports, aka the User Ports, from 1024-49151
the Dynamic Ports, aka the Private Ports, from 49152-65535

So we can allow range between 1024 to 49151

CLI command syntax :
 swarm init --vxlan-udp-port <1024-49151>
PS : swarm update will not have this option.  Only swarm init will have port config option.

cc : @thaJeztah @mavenugo @fcrisciani   @mark-church
Pls provide your inputs.

**Comment by ctelfer** [comment]
A few quick thoughts:
  * `--overlay-net-vxlan-udp-port` might be a bit more clear (but is more verbose... I'm not 100% sold on it.)
  * While the UDP port should be in the 1024-49151 range, to be clear, I don't think there is any reason that the code should restrict the port range.  (well, it must be non-zero)  So the restriction above would be more for documentation, right?

Other than that, seems good to me.   We *could* make the port a property of the network itself in theory.  For example:  `docker network create -d overlay --opt "udp-port=12345"`.   That means that swarm has to carry around this info per network. But that may not be any more intrusive than the configuration change, and I imagine that users would *still* want a feature that changes the default port so they don't have to specify the option every time.

**Comment by selansen** [comment]
I thought vxlan it self overlay. and also this is only overlay we are supporting . so wanted to avoid overlay name .
 I thought we will allow user to configure only between 1024-49151 (just to avoid well known standard ports..and getting into debugging if port is already used , etc).  do you think its not a good idea?

**Comment by olljanat** [comment]
#38102 is merged so I will close this one

**Comment by olljanat** [comment]
Derek close
