### ISSUE TITLE
journald logging driver never re-appends `\n` to partials

### ISSUE THREAD

**Issue by nonspecialist** [moby/moby#38045]
**Description**

When using journald log driver with docker 18.06 or later, long messages (>16k) are split as partials and _all_ partials get the `CONTAINER_PARTIAL_MESSAGE` flag.

Compare this to 18.03, or to the `json-file` log driver, where all but the last partial get the flag.

This breaks logging of long messages via journald, because the trailing `\n` is never re-appended and log forwarders which are waiting for the newline never see it.

**Steps to reproduce the issue:**
1. On a system with docker 18.06.0 or 18.06.1 and journald, run the following:
```shell
localhost$ docker run --name bibble alpine:3.7 sh -c "dd if=/dev/urandom bs=1 count=16384 2>/dev/null | base64 | tr -d '\n'; echo -n -e '\r\n'"
```

2. Once the container completes, look at the log output via `docker logs bibble | hexdump -C | tail` and note that the trailing bytes look like:
```
000043a0  4c 6d 67 74 31 35 48 51  36 64 45 75 31 66 6a 6c  |Lmgt15HQ6dEu1fjl|
000043b0  51 55 2f 2b 34 41 3d 3d  0d                       |QU/+4A==.|
```
Note the last byte is a CR, the trailing LF has been stripped and not replaced.

3. Examine the logs straight from journald via 
```shell
localhost$ journalctl -o json-pretty --no-pager CONTAINER_NAME=bibble
```
and note that all message parts are flagged as `CONTAINER_PARTIAL_MESSAGE`, including the last one (which shouldn't be)

3. Run the same command on a system with docker 18.03 and note that the last two bytes are `0d 0a`, as they should be

**Describe the results you received:**

large log events lose their trailing newline

**Describe the results you expected:**

large log events shouldn't lose their trailing newline (they don't with json-file, for example)

**Additional information you deem important (e.g. issue happens only occasionally):**

For reference, see https://github.com/moby/moby/issues/32970 

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 162
 Running: 129
 Paused: 0
 Stopped: 33
Images: 91
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 30.53GiB
Name: xxxxxxxxxxxx
ID: AAAA:BBBB:CCCC:DDDD:EEEE:FFFF:GGGG:HHHH:IIII:JJJJ:KKKK:LLLL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 
systemd-219-42 installed; `/etc/systemd/journald.conf` configured with `RateLimitBurst=0`

**Comment by nonspecialist** [comment]
For reference, I believe the issue is at https://github.com/moby/moby/blob/503b1a9b6f24488db6a67f7ba24258e4ff5ea2a7/daemon/logger/journald/journald.go#L107

whereas in the `jsonfilelog` driver, the existence of the partial metadata is handled differently, and whether or not this is the last partial is used: https://github.com/moby/moby/blob/503b1a9b6f24488db6a67f7ba24258e4ff5ea2a7/daemon/logger/jsonfilelog/jsonfilelog.go#L135

**Comment by thaJeztah** [comment]
Should be fixed on master through https://github.com/moby/moby/pull/38046
