### ISSUE TITLE
Unable to install moby-engine in RHEL 7

### ISSUE THREAD

**Issue by mmasooddatascience** [moby/moby#38044]
Hi, I am new to Linux world. I am trying to install moby-engine in my RHEL 7 enterprise linux box but getting error saying "no package moby-engine found"

I am following https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux to setup my IoT Edge device.

Any guide or idea where I am doing wrong.

Thanks,
Masood

**Comment by AkihiroSuda** [comment]
Moby does not provide official `moby-engine` RPM.

Please ask to the author of the document you are following.
