### ISSUE TITLE
A container stuck, cannot docker stop/restart/info/exec container（happens often）

### ISSUE THREAD

**Issue by Nukker** [moby/moby#38073]
**Description**

As described in title, when that happens, We use the following method
1.  command `docker stop XXXX` （need few hours command effect usually）
2. command `docker start XXXX`
or
3. restart docked（when above method useless）

**Steps to reproduce the issue:**
1. large probability can reproduce when restart / start the container or up dockerfiles
2. Only happen run the JAVA/Go program In the container, C++ program never happen this situation.

**Describe the results you received:**
A container stuck, cannot docker stop/restart/info/exec container

**Describe the results you expected:**
All command should not hang

**Additional information you deem important (e.g. issue happens only occasionally):**
1. Only happen run the JAVA/Go program In the container, C++ program never happen this situation.
2. JAVA/Go program have a lot start up log 
 
**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 59
 Running: 55
 Paused: 0
 Stopped: 4
Images: 165
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.9-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.41GiB
Name: VM_2_228_centos
ID: WFEA:2QCF:KV3T:E2DU:F2IZ:WXQW:UDEO:BMJG:IR4U:ZVKT:53LR:I6E7
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 415
 Goroutines: 547
 System Time: 2018-10-24T15:23:35.372270592+08:00
 EventsListeners: 4
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://hub.c.163.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Linux VM_2_228_centos 4.18.9-1.el7.elrepo.x86_64 #1 SMP Thu Sep 20 09:04:54 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Nukker** [comment]
@thaJeztah help please : )

**Comment by cpuguy83** [comment]
Can you provide the goroutine stack trace of a stuck docker daemon?
You can get this by calling `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2`

**Comment by Nukker** [comment]
> Can you provide the goroutine stack trace of a stuck docker daemon?
> You can get this by calling `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2`

here is the stack trace  [trach.log](https://github.com/moby/moby/files/2513184/trach.log)
here is pprof.log  https://pastebin.com/raw/MKXg47wB  
(docker-containerd-ctr pprof --debug-socket /run/docker/containerd/docker-containerd-debug.sock goroutines
)

**Comment by cpuguy83** [comment]
Is this from a daemon that is stuck? I don't see anything stuck in the stack trace.

**Comment by Nukker** [comment]
> Is this from a daemon that is stuck? I don't see anything stuck in the stack trace.

yes, but data collection is after DOCKER has been restored

this log from a daemon that is stuck
[trace_1.log](https://github.com/moby/moby/files/2517501/trace_1.log)

**Comment by cpuguy83** [comment]
Thanks!

Here's where it is stuck:

<details>

```
goroutine 53810302 [semacquire, 19 minutes]:
sync.runtime_Semacquire(0xc420016d4c)
	/usr/local/go/src/runtime/sema.go:56 +0x3b
sync.(*WaitGroup).Wait(0xc420016d40)
	/usr/local/go/src/sync/waitgroup.go:129 +0x74
github.com/docker/docker/container.(*rio).Wait(0xc423757600)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/container/container.go:717 +0x33
github.com/docker/docker/vendor/github.com/containerd/containerd.(*task).Delete(0xc422264630, 0x56261b82f640, 0xc42003e018, 0x0, 0x0, 0x0, 0xc422264630, 0x0, 0x0)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/containerd/containerd/task.go:290 +0x3c6
github.com/docker/docker/libcontainerd.(*client).DeleteTask(0xc4203c1880, 0x56261b82f640, 0xc42003e018, 0xc424d0dec0, 0x40, 0x0, 0x0, 0xc422c226e8, 0x562619685d65, 0x0, ...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/client_daemon.go:504 +0xe2
github.com/docker/docker/daemon.(*Daemon).ProcessEvent(0xc4203c2c40, 0xc421a6cfc0, 0x40, 0x56261abe4192, 0x4, 0xc421a6cfc0, 0x40, 0xc421a6d000, 0x40, 0x8900005671, ...)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/daemon/monitor.go:54 +0x23c
github.com/docker/docker/libcontainerd.(*client).processEvent.func1()
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/client_daemon.go:694 +0x130
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc421a6cf00, 0x0, 0xc424aadf80, 0xc424e0be00, 0xc4203c18d8, 0xc421a6cfc0, 0x40)
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/queue.go:26 +0x3a
created by github.com/docker/docker/libcontainerd.(*queue).append
	/root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/libcontainerd/queue.go:22 +0x196
```
</details>

Looks like it's stuck waiting for containerd stdio to finish copying

Do you have a set of repro steps for this?

**Comment by Nukker** [comment]
Thanks 
I don't find steps to reproduce this issue:

But based on happened 
1. large probability can reproduce when restart / start the container or up dockerfiles (but maybe running status will be stuck, just i am not found)
2. Only happen run the JAVA/Go program In the container, C++ program never happen this situation.
3. JAVA/Go program have a lot start up log

and this issue happen everyday almost， if you need I will provide the goroutine stack trace until the problem fix..

**Comment by Nukker** [comment]
[trace_3.log](https://github.com/moby/moby/files/2518253/trace_3.log)
log from today.

**Comment by Nukker** [comment]
[trace_8.log](https://github.com/moby/moby/files/2518475/trace_8.log)


log from today.  @cpuguy83

**Comment by davojan** [comment]
Not sure this is the same issue, but seems related.
This starts to happening recently after upgrading to docker 18.06 with my java-based container during restart almost every time:

```bash
[21:20:31] $ docker restart backend
Error response from daemon: Cannot restart container backend: failed to get network during CreateEndpoint: network br8ih4g16j1aewtfo1qgsi9d5 not found
[21:21:00] $ docker restart backend
Error response from daemon: Cannot restart container backend: network br8ih4g16j1aewtfo1qgsi9d5 not found
[21:21:04] $ docker restart backend
backend
```

The network it complaining is an overlay multihost network and seems to be ok all the time. 

It definitely wasn't the case with earlier docker version.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
