### ISSUE TITLE
Docker pull downloads the image progress bar with a data display back to the client.

### ISSUE THREAD

**Issue by Jack-qing** [moby/moby#38079]
```
@api.route("/images_pull")
@cross_origin()
def docker_images_pull():
    name_pull = request.args.get("name")
    if ":" not in name_pull:
        name_pull = name_pull + ":latest"
    docker_connection = docker.Client(base_url='unix:///var/run/docker.sock')
    try:
        for line in docker_connection.pull(name_pull, decode=True, stream=True):
            if line.get('progressDetail'):
                progress[line.get('progressDetail')['total']] = line.get('progressDetail')['current']
            if "Downloaded" in json.dumps(line, indent=4):
                return jsonify({'cod': RET.OK, "dockerPull,NewImages": "ok"})
        return jsonify({'cod': RET.DATAEXIST, "dockerPull,LocalAlready": "local"})
    except Exception as e:
        return jsonify({'cod': RET.DBERR, "dockerPull": "error"})

@api.route("/progress")
@cross_origin()
def getProgress():
    total = sum(progress.keys())
    current = sum(progress.values())
    return jsonify({"current": current, "total": total})
```
describe：
Print the download progress to display all download process information, extract the dictionary value (current, tota) and add it back to the client
The data is downloaded from 0%~100% instead of 0%-20%-10%-70%.-50%

Download mirroring process
[pull image.txt](https://github.com/moby/moby/files/2517232/pull.image.txt)

The result is 0-100 calculation.

**Comment by cpuguy83** [comment]
Sorry, I have no idea what this issue means.
Could you fill in the issue template?

**Comment by Jack-qing** [comment]
for line in docker_connection.pull(name_pull, decode=True, stream=True):

(Attachment) A line of code to print out the mirror download process, I extract the key value, after each layer of mirror download key value added to get a value to return to the client to achieve the download progress bar, the problem is that I get the progress bar data bounce back number, I data extraction error.
{
    "status": "Downloading",
    "progressDetail": {
        "current": 22665998,
        "total": 27476713
    }

**Comment by thaJeztah** [comment]
> the problem is that I get the progress bar data bounce back number,

The reason is that `docker pull` can pull multiple layers in parallel, so you have to match each progress with the same `ID`. Looking at the first few lines from your example;

```json
[{
    "status": "Downloading",
    "progressDetail": {
        "current": 3767052,
        "total": 10291692
    },
    "progress": "[==================>                                ]  3.767MB/10.29MB",
    "id": "944465c7b0cd"
},
{
    "status": "Downloading",
    "progressDetail": {
        "current": 3357454,
        "total": 27476713
    },
    "progress": "[======>                                            ]  3.357MB/27.48MB",
    "id": "41a25a28317e"
},
{
    "status": "Downloading",
    "progressDetail": {
        "current": 3996428,
        "total": 10291692
    },
    "progress": "[===================>                               ]  3.996MB/10.29MB",
    "id": "944465c7b0cd"
},
{
    "status": "Downloading",
    "progressDetail": {
        "current": 3914510,
        "total": 27476713
    },
    "progress": "[=======>                                           ]  3.915MB/27.48MB",
    "id": "41a25a28317e"
}]
```

You can see that _two_ layers are being pulled in parallel;

- Layer with id `944465c7b0cd `, which is `10.29MB`
- Layer with id `41a25a28317e `, which is `27.48MB`
 

So you have to combine the progressbar-data for each one.


Looking at the above, I don't think there's a bug here, but feel free to continue the conversation if you have questions 👍
