### ISSUE TITLE
Container's status is not same in "all containers" and " one container" by docker.sock

### ISSUE THREAD

**Issue by Nebulazhang** [moby/moby#38078]
**Description**
When I delete a pod by k8s and I found the pod is terminating for a long time. 
I read the kubelet's log and found one container cannot be deleted 
and I can see this pod by `docker ps` and this container is **running**

</br>
I get this container by docker.sock like this
`curl -XGET --unix-socket /var/run/docker.sock http://localhost/containers/4635e2e5f81dc1417e2b456412f/json`

and the get result  as follows: this container's status is **exited!**
![image](https://user-images.githubusercontent.com/28707161/47473641-0485fb80-d846-11e8-89ec-a318a423511f.png)

</br>
I get all container by docker.sock like this and grep this container

`curl -XGET --unix-socket /var/run/docker.sock http://localhost/containers/json | grep 4635e2e5f81dc1417e2b456412f396ddfaf5a9fbb2383e0c9246ef6d85f4182d`

and the get result  as follows:this container's status is  **running**

![image](https://user-images.githubusercontent.com/28707161/47473671-1ff10680-d846-11e8-9a03-6876338210f3.png)

</br>
The same id  container has  different status. So kubelet cannot delete this pod correctly

**Steps to reproduce the issue:**

I happened to encounter this problem ,about twice two weeks.

**Describe the results you received:**

The same id  container has  different status so than kubelet cannot delete this pod correctly

**Describe the results you expected:**

The same id  container should have same status by "all container" and "appointed container"
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:13:43 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:20:43 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 61
 Running: 61
 Paused: 0
 Stopped: 0
Images: 63
Server Version: 17.12.1-ce
Storage Driver: aufs
 Root Dir: /opt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 474
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55GiB
Name: VM-0-55-ubuntu
ID: SFQA:XYOI:AVUV:ZCYW:O2H3:UGRH:O3M3:AZVZ:WMDV:ZLBJ:MN37:2UGR
Docker Root Dir: /opt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://mirror.ccs.tencentyun.com/
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Are you consistently able to reproduce this issue somehow?

If possible can you try if this still reproduces on a current version of Docker?

Also, if you still have this environment running, could you provide the JSON of both commands as a text file (not just as an image?)

Is there anything in the daemon logs that stands out (some errors, e.g))?

**Comment by Nebulazhang** [comment]
@thaJeztah 
Sorry  that I didn't have any log about dockerd. And the environment is not running.
I met this problem twice and `restart dockerd` can solve it .  Because  I need to recover this cluster as soon as possible. And I didn't notice  any error log about daemon.
</br>
I will save the log when I meet this problem next time. I will provide more infomation
