### ISSUE TITLE
deriving from latest ubuntu doesn't build on docker 18.06.1

### ISSUE THREAD

**Issue by jwatte** [moby/moby#38076]
The dockerfile:

FROM ubuntu:cosmic
RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
  && true

The important part of the log output:

Running hooks in /etc/ca-certificates/update.d...
done.
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.RqK3gS - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.as8vCH - IsAccessibleBySandboxUser (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.YSXYXw - IsAccessibleBySandboxUser (13: Permission denied)
Removing intermediate container 85bddfa46ecb

**Comment by jwatte** [comment]
Literally the minute after I filed this (which was reproducible,) it stopped reproducing.

**Comment by endlisnis** [comment]
Funny, I can reproduce this pretty consistently:
`docker run -it --rm ubuntu:18.10 /bin/bash -c 'apt update; apt upgrade -y'`

Produces this:
`W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.Ccx1E4 - IsAccessibleBySandboxUser (13: Permission denied)`
`W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.629VOZ - IsAccessibleBySandboxUser (13: Permission denied)`
`W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.w9cRYU - IsAccessibleBySandboxUser (13: Permission denied)`
