### ISSUE TITLE
Not complete documentation about HostConfig.DiskQuota in ContainerCreate method

### ISSUE THREAD

**Issue by vblz** [moby/moby#38081]
There are a HostConfig.DiskQuota option with description "Disk limit (in bytes)." on https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate.

But, unfortunately, I can't find any other information about what does it mean. What constrains of use does it have? Is it can be used on all platfroms/storage drivers? What would be if this limit will be exceeded?

**Comment by jaswdr** [comment]
@vblz 

This is only supported at BTRFS and activelly disallow in Windows, I take a look at the code and see this:

First of all look at this https://github.com/moby/moby/blob/master/daemon/graphdriver/btrfs/btrfs.go#L81

This is the only local where it is used, so I understand that BTRFS is the only who support it.

What it does is enabling BTRFS Disk Quota, you can read more about this [here](https://btrfs.wiki.kernel.org/index.php/Quota_support)

**Comment by cpuguy83** [comment]
I don't think this field is used anywhere. I don't know why it is in there... will need to track it down.

For storage drivers that support quotas, such as btrfs, quotas are passed through `StorageOpt`

**Comment by cpuguy83** [comment]
Yep, not used and does not belong... https://github.com/docker/engine-api/pull/52

**Comment by jaswdr** [comment]
@cpuguy83 if it's ok, I can remove this option

**Comment by yashmurty** [comment]
@cpuguy83 and @jaswdr I submitted a PR https://github.com/moby/moby/pull/39158 for this.
Do you guys think it looks good? 
Please let me know if you'd like me to change anything.

**Comment by yashmurty** [comment]
@cpuguy83 and @jaswdr my PR https://github.com/moby/moby/pull/39158 got merged.
Perhaps we can close this issue now. :bowing_man:
