### ISSUE TITLE
doskey broken in microsoft/windowsservercore containers

### ISSUE THREAD

**Issue by samlevy-microsoft** [moby/moby#38095]
**Description**

When running from a windows server container;
No matter which format I used, the doskey command always returns "Invalid macro definition."

C:\>doskey test=dir
Invalid macro definition.

C:\>echo "test=dir" > macro.txt

C:\>doskey /MACROFILE=macro.txt
Invalid macro definition.
Is the command broken ?

When I run it from my desktop it works fine

**Steps to reproduce the issue:**
1.run -it --rm microsoft/windowsservercore:ltsc2016 cmd
2.run any doskey command
3.

**Describe the results you received:**

Invalid macro definition

**Describe the results you expected:**

aliases working

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
C:\Windows\system32>docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Output of `docker info`:**

```
C:\Windows\system32>docker info
Containers: 22
 Running: 2
 Paused: 0
 Stopped: 20
Images: 4
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2551.amd64fre.rs1_release.181004-1309)
Operating System: Windows Server 2016 Essentials
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 31.8GiB
Name: XXXXX
ID: XXXXX
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 33
 System Time: 2018-10-28T09:13:43.8670201+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by samlevy-microsoft** [comment]
@PatrickLang

**Comment by PatrickLang** [comment]
@samlevy-microsoft - this is a Windows bug, not a Docker bug. Can you email me at my Microsoft address and I'll add the right person to file the bug

**Comment by samlevy-microsoft** [comment]
sure , thanks

**Comment by thaJeztah** [comment]
Thanks @PatrickLang - let me close the ticket here, as there's no actionable item for the codebase in this repository, but feel free to continue the conversation if there's updates 👍

**Comment by joelvaneenwyk** [comment]
@thaJeztah I’m still seeing this issue and would love to track progress. Where was the followup on this? Workaround of just not using doskey is not ideal ;)

**Comment by KaiWen0608021314** [comment]
@thaJeztah @samlevy-microsoft @PatrickLang 
Hello, I also encountered the same problem. Is there any solution? Or is there any reference information?

**Comment by thaJeztah** [comment]
From the above, it looks like this issue was a Windows bug, and resolved internally at Microsoft.

But this is a 5 Year old ticket, and I know at least @PatrickLang no longer works at Microsoft, so won't be able to help.

If you found an issue and think it's a bug, and if you have steps to reproduce, please open a new ticket instead (but it's ok to add a link to this ticket for cross-referencing).

**Comment by thaJeztah** [comment]
I'll lock the conversation on this ticket because of the above.
