### ISSUE TITLE
double dash arguments are causing an error in docker cli programmatic commands

### ISSUE THREAD

**Issue by purplesrl** [moby/moby#38093]
Version: 18.06.1-ce
API: 1.38

Example:
```

cmd := system.NewInspectCommand(cli)
cmd.SetArgs([]string{"-f {{range .NetworksAttachments}}{{.Addresses}}{{end}}", "<ID>"}) <<-- WORKS
cmd.SetArgs([]string{"--format {{range .NetworksAttachments}}{{.Addresses}}{{end}}", "<ID">}) <--- ERROR Invalid flag
cmd.Execute()

```
The same for NewStackCommand, there unfortunately I cannot use the "-f" because its used by the filter.

The only explanation for me, is that the "--" is not processed correctly, and this is why single dash commands work and double dash do not, but the strange thing is the flag is displayed correctly (--format) but is marked as invalid. I also tried to put the format in single/double quotes, nothing works.

```
Error: unknown flag: --format {{range .NetworksAttachments}}{{.Addresses}}{{end}}
Usage:
  inspect [OPTIONS] NAME|ID [NAME|ID...] [flags]

Flags:
  -f, --format string   Format the output using the given Go template
  -h, --help            help for inspect
  -s, --size            Display total file sizes if the type is container
      --type string     Return JSON for specified type

```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
