### ISSUE TITLE
Docker doesn't work with iptables v1.8.1

### ISSUE THREAD

**Issue by flbla** [moby/moby#38099]
**Description**
When I try to deploy a container and expose it on a port it failed with this error since I updated iptables to v1.8.1 : 
```
docker run -p 80:80 nginx 

docker: Error response from daemon: driver failed programming external connectivity on endpoint hopeful_kapitsa (f6bcba259f5ab3db1043515bb81dedad2b8aca51e2164fc8e9786d9fc45cfd7c):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0: iptables v1.8.1 (nf_tables): Chain 'DNAT' does not exist
 (exit status 1)).
ERRO[0000] error waiting for container: context canceled 
```
docker version : 18.06.1-ce
iptables v1.8.1

**Steps to reproduce the issue:**

1. Install iptables v1.8.1
2. Deploy a container on a port (for example: docker run -p 80:80 nginx)

**Describe the results you received:**

```
docker run -p 80:80 nginx 

docker: Error response from daemon: driver failed programming external connectivity on endpoint hopeful_kapitsa (f6bcba259f5ab3db1043515bb81dedad2b8aca51e2164fc8e9786d9fc45cfd7c):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0: iptables v1.8.1 (nf_tables): Chain 'DNAT' does not exist
 (exit status 1)).
ERRO[0000] error waiting for container: context canceled 

```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:06 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**EDIT:**

If I downgrade, it works with those packages/version: 
```libip4tc0=1.6.2-1.1  
libip6tc0=1.6.2-1.1   
libiptc0=1.6.2-1.1  
libxtables12=1.6.2-1.1  
iptables=1.6.2-1.1
```

So the issue is related to those packages/version:
```libip4tc0=1.8.1-2 
libip6tc0=1.8.1-2 
libiptc0=1.8.1-2 
libxtables12=1.8.1-2 
iptables=1.8.1-2
```

**Comment by thaJeztah** [comment]
@flbla what Linux distro (and version) are you running on?

**Comment by flbla** [comment]
@thaJeztah a Debian unstable

**Comment by eugenradu** [comment]
Same here: Debian buster with iptables v1.8.1 and docker 18.06.1-ce

**Comment by fvichot** [comment]
For Debian Testing/Unstable users looking for a fix until a new Docker version is released, run:
```
sudo update-alternatives --config iptables
```
and choose `iptables-legacy`.

**Comment by thaJeztah** [comment]
Fix was merged in libnetwork; https://github.com/docker/libnetwork/pull/2285, and being vendored in this repository through https://github.com/moby/moby/pull/38120

**Comment by tianon** [comment]
Fwiw, this is related to https://github.com/moby/moby/issues/26824 (the new `iptables` is now implemented via `nft`, which is way, way better in my experience playing with it so far).

**Comment by jessfraz** [comment]
okay I tested and it fixed the issue :)

**Comment by userAugustos** [comment]
Same Error are back now in iptables 1.8.7:

```
Error response from daemon: driver failed programming external connectivity on endpoint thecpay (651ac3aa4ef2536383ab7a08b0d4ea3ffd95f90d455340cef76b7fa7f68f5fe8):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5432 -j DNAT --to-destination 172.17.0.2:5432 ! -i docker0: iptables v1.8.7 (nf_tables): unknown option "--to-destination"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))
```
 trying to start a simple postgress container in `5432`

**Comment by cmnemoi** [comment]
> Same Error are back now in iptables 1.8.7:
> 
> ```
> Error response from daemon: driver failed programming external connectivity on endpoint thecpay (651ac3aa4ef2536383ab7a08b0d4ea3ffd95f90d455340cef76b7fa7f68f5fe8):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5432 -j DNAT --to-destination 172.17.0.2:5432 ! -i docker0: iptables v1.8.7 (nf_tables): unknown option "--to-destination"
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2))
> ```
> 
> trying to start a simple postgress container on `5432`

A temporary "fix" that worked for me would be to downgrade your Linux kernel. `6.2.6-76060206` worked for me

**Comment by cmnemoi** [comment]
> Same Error are back now in iptables 1.8.7:
> 
> ```
> Error response from daemon: driver failed programming external connectivity on endpoint thecpay (651ac3aa4ef2536383ab7a08b0d4ea3ffd95f90d455340cef76b7fa7f68f5fe8):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5432 -j DNAT --to-destination 172.17.0.2:5432 ! -i docker0: iptables v1.8.7 (nf_tables): unknown option "--to-destination"
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2))
> ```
> 
> trying to start a simple postgress container on `5432`

Is there any update about this being properly fixed ? We might want to open a new issue.
