### ISSUE TITLE
Docker Build Dry Run Check

### ISSUE THREAD

**Issue by Spenser309** [moby/moby#38101]
**Description**

I have Docker working in a CI setup where each branch and PR has it's own docker container.  This is working wonderfully and each developer is able to make changes to their environment without explicitly needing to come to the OPs team!  Kudos to the docker team for making this awesome software and for all the caching layers you have but into make this work really well!

However, I am facing an issue where I'd like to know whether or not a given CI job will trigger a docker build.  Docker builds in our environment are fairly expensive (source code is built in docker layers) .  We allow this because it's been the fastest way to get developers to continue moving without forcing them to learn how to do proper packaging.

Now the problem arises in CI where I'd like to limit the number of ongoing docker builds without blocking changes that do not require a docker rebuild.  To this end, I have a docker pipeline which runs docker with a short timeout and then pops it over to a "docker builder" node in the case of a docker rebuild.  This works but it's not really ideal because it wastes a couple of minutes waiting for the timeout to occur and even worse I can't tell if the build was fully cached or just completed really quickly.

Is it possible to implement something similar to "make -k" which just simply checks if a rebuild is required?  

**Steps to reproduce the issue:**
1. Build image
2. Make changes to repo
3. Rebuild image 

**Describe the results you received:**
No option to check if a rebuild is required

**Describe the results you expected:**
A --dry-run or -k option similar to Make

**Additional information you deem important (e.g. issue happens only occasionally):**
This could theoretically be implemented by Make but it would be nice to identify this from docker in order to reduce this to a single source of truth.  

**Output of `docker version`:**
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
(paste your output here)
```

**Output of `docker info`:**
$ docker info
Containers: 33
 Running: 4
 Paused: 0
 Stopped: 29
Images: 17
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc nvidia
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 28
Total Memory: 125.8GiB
Name: lab1.smnet
ID: RZD3:FFJ6:5HCI:5YGZ:4NUT:RCEO:4U3Z:THKC:CUGF:JLNL:RHDY:KS5P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ssicspenserg
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://dockermirror.smnet:5000/
Live Restore Enabled: false

WARNING: No swap limit support

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Ubuntu 16.04 system with Nvidia Docker and Docker installed.

**Comment by romintomasetti** [comment]
Hi there!
What's the status of this? We would also benefit from a sort of `dry run` `docker build`. Thanks!

**Comment by pankajkoti** [comment]
+1 . In need of this feature too

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.l, and this should probably be a feature request in BuildKit now 🤔
