### ISSUE TITLE
Unable to start docker after installing docker-ce v18.03

### ISSUE THREAD

**Issue by ankitgupta07** [moby/moby#38106]
I am here to talk about an issue I encountered while installing `docker-ce` v18.03. The installation works but when I start docker, the process doesn't start. I see below error in sys logs -

Oct 29 10:56:17 localhost dockerd: time="2018-10-29T10:56:17.341782532Z" level=info msg="Creating filesystem xfs on device docker-253:2-38-base, mkfs args: [-m crc=0,finobt=0 /dev/mapper/docker-253:2-38-base]" storage-driver=devicemapper
Oct 29 10:56:17 localhost dockerd: time="2018-10-29T10:56:17.342798221Z" level=info msg="Error while creating filesystem xfs on device docker-253:2-38-base: exit status 1" storage-driver=devicemapper

Anybody else who has faced this issue?

**Steps to reproduce the issue:**
1. Install docker-ce v18.03 on CentOS 7 host
2. Start docker service, service will not start
3. Sys log messages would lead to above error

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
[root@linux-slave-centos-70 ~]# docker info
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info: read unix @->/var/run/docker.sock: read: connection reset by peer```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am trying to setup docker v18.03 through chefdk on virtualbox VM.

**Comment by ankitgupta07** [comment]
As per docker documentation, we should be using v4.x of linux kernel - ```To use the new driver, you need version 4.0 or higher of the Linux kernel, unless you are a Docker EE user on RHEL or CentOS, in which case you need version 3.10.0-514 or higher of the kernel and to follow some extra steps.```

We are running CentOS7 which doesn't even has this version of kernel. The latest version of kernel on CentOS7 is - `kernel.x86_64  3.10.0-862.14.4.el7  updates`

Are there any config override which can help us run latest version with devicemapper.

**Comment by thaJeztah** [comment]
@ankitgupta07 the CentOS 7 kernel does have support for the overlay2 storage driver (`3.10.0-862.14.4.el7` is more recent than `3.10.0-514`). It _does_ require the underlying filesystem to be formatted as  xfs with d_type=true (ext4 should probably work as well, but not officially supported upstream by CentOS/RHEL), as is mentioned in the prerequisites https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites

**Comment by ankitgupta07** [comment]
This is fixed by using overlay2 storage on centos 7 running kernel version 3.10.0-693
