### ISSUE TITLE
--stop-timeout is not working

### ISSUE THREAD

**Issue by dungdm93** [moby/moby#38121]
**Description**
Hello Docker team,

I run jobs inside Docker container, and I'd like to set timeout to prevent some thing wrong happens.
I found this option in `docker run` command, but it does not seem to work.
![image](https://user-images.githubusercontent.com/6848311/47830439-69999e00-ddbe-11e8-88be-f5bbc09cef91.png)

**Steps to reproduce the issue:**
```bash
docker run --stop-timeout 10 ubuntu:18.04 bash -c "while true; do echo "foobar"; sleep 1; done;"
```

**Describe the results you received:**
After 10 seconds, my container still running...

**Describe the results you expected:**
Container should be stopped after 10s

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 29
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.744GiB
Name: KiT106
ID: 5U7Q:5UNH:VHY7:64VX:7R3K:DL56:2PNG:SPQS:6PMU:NAZX:3DIB:WAUE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine.

**Comment by lifubang** [comment]
"--stop-timeout" value is used for when you run `docker stop`
When you "docker stop" this container, the container will be killed after 10s.
If you didn't run "docker stop", the container would not be stopped by itself.

**Comment by dungdm93** [comment]
@lifubang You mean `--stop-timeout` is timeout for container graceful stop before Docker force kill that container?

**Comment by lifubang** [comment]
You are right.

**Comment by dungdm93** [comment]
@lifubang Thank you.
I mis-understand this option. So there is any Docker option for my case?

**Comment by dungdm93** [comment]
@lifubang It's not good idea.
But for now, I think I'll close this issue.
