### ISSUE TITLE
How are releases tracked?

### ISSUE THREAD

**Issue by jribe** [moby/moby#38134]
As far as I can tell, by looking at other docker projects like `docker/cli`, this repo has had several releases between `v17.03.2-ce` and today, but there is nothing on this repo that would indicate that.

I would like to use v18 of moby/the docker SDK, but I can't find a way to pin down which commits are official releases.

I tried digging through the docker projects that vendor this project, but the commit refs they list don't appear to exist any more?

How am I supposed to use this code? Is `v17.03.2-ce` actually the most recent supported release?

**Comment by cpuguy83** [comment]
@jribe Please see github.com/docker/engine for docker release tags.

Thanks!
