### ISSUE TITLE
Unable to install containerd.io 1.2.0-1 from download.docker.com/linux/ubuntu repository

### ISSUE THREAD

**Issue by pszczekutowicz** [moby/moby#38156]
**Description**

Latest available version of containerd.io package in Ubuntu repository is  1.2.0~rc.2-1. 

**Steps to reproduce the issue:**
1. Add the repository according to the instruction from  https://docs.docker.com/install/linux/docker-ce/ubuntu/
2. Execute sudo apt install containerd.io

**Describe the results you received:**
Version 1.2.0~rc.2-1 of containerd.io is installed  

**Describe the results you expected:**
Version 1.2.0-1 should be installed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tested in Ubuntu 18.04.1

Following file is present: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.0-1_amd64.deb

**Comment by thaJeztah** [comment]
ping @seemethere @andrewhsu @mataneja

**Comment by andrewhsu** [comment]
We're working on updating the index files of the apt repo. Stay tuned...

**Comment by andrewhsu** [comment]
This is now working:
```
$ docker --version
Docker version 18.09.0, build 4d60db4
$ ctr -v
ctr github.com/containerd/containerd 1.2.0
```
