### ISSUE TITLE
unexpected disk usage from docker pull with 18.09

### ISSUE THREAD

**Issue by coryb** [moby/moby#38170]
**Description**

running `docker pull` on an image is utilizing 2-3x more disk with 18.09 than with 18.06.

**Steps to reproduce the issue:**

1. Verify nearly empty /var/lib/docker: `sudo du -sh /var/lib/docker`
2. Install public docker image: `sudo docker pull openjdk`
3. Verify unexpected disk usage when compared with image size: `sudo du -sh /var/lib/docker`
4.  Prune image installed to verify we get back to original state: `sudo docker system prune --all --force`
5. Verify disk usage: `sudo du -sh /var/lib/docker`

**Describe the results you received:**

This is the results when running on docker-ce `5:18.09.0~3-0~ubuntu-xenial`
Download 960M image, use 2.5G of disk space:
```
$ sudo du -sh /var/lib/docker
132K    /var/lib/docker

$ sudo docker pull openjdk
Using default tag: latest
latest: Pulling from library/openjdk
38517b303516: Pull complete
d518e0b86e7e: Pull complete
75323769698f: Pull complete
56058d5d210a: Pull complete
15911fa38fed: Pull complete
05608362f0e0: Pull complete
b557609cc1f0: Pull complete
fea98ccfb6f5: Pull complete
Digest: sha256:4b6ed15fe162c6209c7fa5cfa4d5fdfdc639d99d76998114e4fc790cda098f66
Status: Downloaded newer image for openjdk:latest

$ sudo du -sh /var/lib/docker
2.5G    /var/lib/docker

$ sudo docker system prune --all --force
Deleted Images:
untagged: openjdk:latest
untagged: openjdk@sha256:4b6ed15fe162c6209c7fa5cfa4d5fdfdc639d99d76998114e4fc790cda098f66
deleted: sha256:4697b3a5fe9aec68bfc6b70fc5a4f7c7cb3c0ea1cce167f7ced8982d54327763
deleted: sha256:47d9e4cbb3f9ada94c86c41acf9cb0ab4b3784ebc748dfd7dc38d5e9bc61be5e
deleted: sha256:dc169d6aa79db7f54f8dbbd83bd8c04e993a1ce3ccd716dad14309d77932c7a5
deleted: sha256:d464a7b418e0c991334d7615027b1d4fb52f93866a73468fff51d71d5847c06e
deleted: sha256:346d9d63965c0da83a07b721f9a2fdf5326183e33595f8534662020b9db08212
deleted: sha256:c8bdd6694d714725f539e831ad308dd3bf30897bb0b581d4d5c47378ba98b09d
deleted: sha256:2de97eae9e04a8dac490775e59099f7255e12999d6369fe00a2d09755ac5bb1b
deleted: sha256:f10e331365656cf376e11ab2cd38603d1dd6d692bc2183521c85d47c16bb1748
deleted: sha256:eea2bb10fa7922f0a8ff9ce028d9c35ed6259b077bae7ff84eb91e0a99bfd652

Total reclaimed space: 961.7MB

$ sudo du -sh /var/lib/docker
196K    /var/lib/docker
```

**Describe the results you expected:**

This is the results when running on docker-ce `18.06.0~ce~3-0~ubuntu`
Download 960M image, use 1.1G of disk space:
```
$ sudo du -sh /var/lib/docker
13M     /var/lib/docker

$ sudo docker pull openjdk
Using default tag: latest
latest: Pulling from library/openjdk
38517b303516: Pull complete
d518e0b86e7e: Pull complete
75323769698f: Pull complete
56058d5d210a: Pull complete
15911fa38fed: Pull complete
05608362f0e0: Pull complete
b557609cc1f0: Pull complete
fea98ccfb6f5: Pull complete
Digest: sha256:4b6ed15fe162c6209c7fa5cfa4d5fdfdc639d99d76998114e4fc790cda098f66
Status: Downloaded newer image for openjdk:latest

$ sudo du -sh /var/lib/docker
1.1G    /var/lib/docker
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The setup is running on a usb linux built via unetbootin which I use for testing software installation.  Previous installations worked fine, but due to limited disk space I started getting disk-full errors after upgrading to 18.09 for tests that all pass under 18.06.

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.0
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-36-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.49GiB
Name: ubuntu
ID: EKWU:VJQK:MOGF:YZ3R:2D5Z:MG3R:4WFI:INEZ:FIVM:FVEJ:DJNQ:LHDH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical laptop running linux via usb stick on aufs file system:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ uname -a
Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ df -h /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
aufs            7.8G  543M  7.3G   7% /
```

**Comment by AkihiroSuda** [comment]
> Server Version: 18.09.0
> Storage Driver: vfs

Were you using `overlay2` for 18.06? Could you provide 18.06 `docker info`?

**Comment by AkihiroSuda** [comment]
I suppose this is a packaging issue related to `modprobe overlay`

cc @andrewhsu

**Comment by cpuguy83** [comment]
So yeah. For some reason Docker excluded drvicemapper from 18.09 even though it's only deprecated (I.e. won't be auto selected and warns when manually selected) in this repo.

I don't know why overlay2 isn't being selected, though.

Ping @andrewhsu @thajeztah

**Comment by thaJeztah** [comment]
Is overlay supported on top of aufs? Possibly it skips overlay2 because of that.

> Physical laptop running linux via usb stick on aufs file system:

**Comment by cpuguy83** [comment]
Ah yes that's why.

**Comment by coryb** [comment]
I see, so 18.09 no longer ships with any storage driver that works on top aufs except `vfs`.  I had not come across `vfs` before, so didn't realize the disk size increase is expected for that storage driver.

For my environment I was able to force the data-root to `/tmp` which is `tmpfs` and now both `aufs` and `overlay2` work as expected.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
