### ISSUE TITLE
Unable to run containers with MountFlags=slave and ZFS

### ISSUE THREAD

**Issue by max-m** [moby/moby#38191]
**Description**
After setting `MountFlags=slave` as per #24403 I am unable to start containers:
```
root@host ~ # docker run -it --init --rm debian bash
[FATAL tini (9)] exec bash failed: No such file or directory
root@host ~ # docker run -it --init --rm debian bash
[FATAL tini (8)] exec bash failed: No such file or directory
root@host ~ # docker run -it --init --rm debian bash
[FATAL tini (8)] exec bash failed: No such file or directory
```

**Steps to reproduce the issue:**
1. Docker daemon service override:
```
[Service]
MountFlags=slave
ExecStart=
ExecStart=/usr/bin/dockerd --live-restore --icc=false --ipv6 --fixed-cidr-v6=x:x:x:x:x::/80 -H unix:// --storage-driver=zfs --init --data-root /docker/
```
2. Reboot
3. Try to start a container

**Describe the results you received:**
I can’t start containers.

**Describe the results you expected:**
I can start containers.

**Additional information you deem important (e.g. issue happens only occasionally):**
After a reboot without `MountFlags` set I was able to restart the demon with this setting but on shutdown this happened: [truncated shutdown log](https://github.com/moby/moby/files/2573763/shotdown.log)

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:46 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 18.09.0
Storage Driver: zfs
 Zpool: rpool
 Zpool Health: ONLINE
 Parent Dataset: rpool/docker
 Space Used By Parent: 2147049472
 Space Available: 702088474624
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.6GiB
Name: *snip*
ID: TXBQ:26PS:V6N3:SGQX:CI5F:GD57:DEXZ:BHAF:TVZT:VL2Y:VBPD:7CAI
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ZFS: `ZFS: Loaded module v0.6.5.9-5, ZFS pool version 5000, ZFS filesystem version 5`

**Comment by thaJeztah** [comment]
ping @cpuguy83 @kolyshkin PTAL

**Comment by cpuguy83** [comment]
You cannot use"MountFlags=slave" with docker 18.09 because dockerd and containerd end up in different mount namespaces when you do that, and containerd can't see the mounts.

This change happened because docker is no longer starting containerd on its own but rather relying on systemd to do that.

There should be no need to use MountFlags=slave anymore.

**Comment by thaJeztah** [comment]
Let me close this issue, because of the above, but feel free to continue the conversation. (Opening a tracking issue internally to add a mention of this change in the release notes / documentation)
