### ISSUE TITLE
VNDR issues

### ISSUE THREAD

**Issue by jordanrh1** [moby/moby#38215]
I'm running into all sorts of crazy errors running VNDR. Would somebody who has a working VNDR setup be willing to update `golang.org/x/sys` to `90868a75fefd03942536221d7c0e2f84ec62a668` ? This is to get support for windows/arm.

**Comment by thaJeztah** [comment]
Sure, give me a few minutes

**Comment by thaJeztah** [comment]
There you go: https://github.com/moby/moby/pull/38216

**Comment by jordanrh1** [comment]
Thank you, really appreciate it!

**Comment by thaJeztah** [comment]
You're welcome!
