### ISSUE TITLE
How can i configure scheduler when using mirror

### ISSUE THREAD

**Issue by wacxt** [moby/moby#38210]
**Description**

I am using docker mirror following https://docs.docker.com/registry/recipes/mirror/. And I see entry will expired after a week. but i have no idea how to configure it to 3 days.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by wacxt** [comment]
anybody knows？it must be a week?

**Comment by cpuguy83** [comment]
This doesn't seem related to this repo at all.

For general support related questions please see the forums or the docker community slack.

Thanks!
