### ISSUE TITLE
Named pipes for Docker Engine 18.09 on Windows 1803 don't work

### ISSUE THREAD

**Issue by kkbruce** [moby/moby#38212]
I reference https://blog.docker.com/2017/09/docker-windows-server-1709/ document, run `-v \\.\pipe\docker_engine:\\.\pipe\docker_engine` command can't work.

already ref: https://github.com/moby/moby/issues/36562

**Steps to reproduce the issue:**

1. `docker run -d -p 8080:8080 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine friism/jenkins`

already fix 18.09 with LCOW problem by https://github.com/moby/moby/issues/38205 , LCOW Image run is fine, like:

```powershell
docker pull --platform linux busybox
docker run --rm --ti busybox sh
```

```powershell
docker pull --platform linux ubuntu
docker run --rm -ti ubuntu sh
```

**Describe the results you received:**

```
PS C:\> docker run -d -p 8080:8080 -v \\.\pipe\docker_engine:\\.\pipe\docker_engine friism/jenkins
C:\Program Files\docker\docker.exe: Error response from daemon: invalid volume specification: '\\.\pipe\docker_engine:\\.\pipe\docker_engine'.
See 'C:\Program Files\docker\docker.exe run --help'.
```

**Describe the results you expected:**

named pipes can bind-mounted and running container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.3
 Git commit:        33a45cd0a2
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       33a45cd0a2
  Built:            11/07/2018 00:24:12
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 18.09.0
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter Version 1803 (OS Build 17134.1)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.999GiB
Name: DOCKER00
ID: ZVYB:LYR7:SUS3:XFNR:32UD:C5YI:N67J:ECYC:2EX3:4TTU:GNT4:YPKA
Docker Root Dir: D:\docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: 
HTTPS Proxy: 
No Proxy: 
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
C:\>ver

Microsoft Windows [Version 10.0.17134.1]
```

**Comment by olljanat** [comment]
@kkbruce *friism/jenkins* is probably bad example as it is already quite old image and not compatible with Win Srv, version 1803.

But if you try example native Windows containers example on [Portainer deployment guide](https://portainer.readthedocs.io/en/stable/deployment.html#windows) it should works just fine.

**Comment by kkbruce** [comment]
@olljanat Yes, Portainer on windows deployment is work, Thanks your information.
