### ISSUE TITLE
[Windows Update servicing fix due March 2019] Absolute path of symlink does not work on Windows volume mapping

### ISSUE THREAD

**Issue by andyzhangx** [moby/moby#38220]
**Description**
The original symlink issue(https://github.com/moby/moby/issues/28401) has been fixed in windows 1803, while only relative symlink issue is fixed, symlink with **absolute** path is not fixed.

**Steps to reproduce the issue:**
1. Create a text file in `c:\test` directory
```
mkdir C:\test
cd c:\test
echo "Symlink Test" > test.txt
```
2. Create a symlink pointing to the text file with **absolute** path
```
cmd /c mklink symtmp.txt c:\test\test.txt
c:\test>type symtmp.txt
"Symlink Test"
```
3. Run powershellcontainer and mount the working directory as volume
```
docker run --rm -v c:\test:c:\test -it mcr.microsoft.com/powershell cmd
```

**Describe the results you received:**
Inside the container run
```
c:\test>dir
...
11/19/2018  05:57 AM    <SYMLINK>      symtmp.txt [c:\test\test.txt]
...
c:\test>type symtmp.txt
The create operation failed because the name contained at least one mount point which resolves to a volume to which the specified device object is not attached.
```

Actually here target path `c:\test\test.txt` exists inside container, while we cannot access symtmp.txt inside container.

**Describe the results you expected:**
```
C:\test> type .\symtmp.txt
Symlink Test
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7GiB
Name: 18986k8s9000
ID: PE4S:FFYI:L5Z3:XPNN:RSF6:WZCK:NZZN:3PFZ:D5NQ:S6MO:4QTR:EW56
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
winver : Windows 1803  (OS Build 10.0.17134.228)

@PatrickLang

**Comment by olljanat** [comment]
@andyzhangx can you try with combination of Windows Server 2019 and Docker 18.09 and tell if issue still exists on there?

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by olljanat** [comment]
@jhowardmsft @johnstep can this actually be reason why we cannot use bind mount when building go inside of container?
https://github.com/moby/moby/blob/3770f386477e5eea4e6ba02516393a1edd5cd28b/Dockerfile.windows#L135-L137

**Comment by jhowardmsft** [comment]
As for the original report - I have verified that this is the case in RS5 builds/Windows Server 2019, build 17763. There's nothing that can be done in docker here - it's a limitation of the implementation in Windows as it currently stands. I've filed an internal bug (VSO#20066507) to track it for a potential fix in a future release of Windows.

**Comment by andyzhangx** [comment]
@jhowardmsft thanks!

**Comment by jhowardmsft** [comment]
Follow-up to this. I just heard (and no promises) that the Windows fix should be available in the "2D" round of fixes. These are downloadable and installable QFEs, not delivered through Windows Update directly. 2D means February, 4th week. That should mean that the subsequent 3B update (that does get delivered through Windows Update) should have the fix. 3B meaning March, 2nd week. AKA March's "Patch Tuesday"

**Comment by jhowardmsft** [comment]
(For my own reference, the servicing bug for RS5 is VSO#19041763 so I don't have to hunt it down again)

**Comment by winterTTr** [comment]
Great to see this fix is coming, i will try later. Thanks everyone.

**Comment by filipesilva** [comment]
I tried this today, on a machine with the Windows 1903 update installed, and this is what I got:
```
Microsoft Windows [Version 10.0.18362.116]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\>mkdir C:\test

C:\>cd c:\test

c:\test>echo "Symlink Test" > test.txt

c:\test>cmd /c mklink symtmp.txt c:\test\test.txt
symbolic link created for symtmp.txt <<===>> c:\test\test.txt

c:\test>type symtmp.txt
"Symlink Test"

c:\test>docker run --rm -v c:\test:c:\test -it mcr.microsoft.com/powershell cmd
Microsoft Windows [Version 10.0.16299.904]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>cd C:\test

C:\test>dir
 Volume in drive C has no label.
 Volume Serial Number is 8865-94E7

 Directory of C:\test

05/28/2019  09:57 AM    <DIR>          .
05/28/2019  09:57 AM    <DIR>          ..
05/28/2019  09:57 AM    <SYMLINK>      symtmp.txt [c:\test\test.txt]
05/28/2019  09:57 AM                17 test.txt
               2 File(s)             17 bytes
               2 Dir(s)  64,373,338,112 bytes free

C:\test>type symtmp.txt
The symbolic link cannot be followed because its type is disabled.
```

That error led me to https://blogs.msdn.microsoft.com/junfeng/2012/05/07/the-symbolic-link-cannot-be-followed-because-its-type-is-disabled/. Tried following the steps there to enable all of the link types, but still no dice.

```
C:\test>fsutil behavior query SymlinkEvaluation
Local to local symbolic links are enabled.
Local to remote symbolic links are enabled.
Remote to local symbolic links are disabled.
Remote to remote symbolic links are disabled.

C:\test>fsutil behavior set SymlinkEvaluation R2R:1

C:\test>fsutil behavior query SymlinkEvaluation
Local to local symbolic links are enabled.
Local to remote symbolic links are enabled.
Remote to local symbolic links are disabled.
Remote to remote symbolic links are enabled.

C:\test>type symtmp.txt
The symbolic link cannot be followed because its type is disabled.

C:\test>fsutil behavior set SymlinkEvaluation R2L:1

C:\test>fsutil behavior query SymlinkEvaluation
Local to local symbolic links are enabled.
Local to remote symbolic links are enabled.
Remote to local symbolic links are enabled.
Remote to remote symbolic links are enabled.

C:\test>type symtmp.txt
The symbolic link cannot be followed because its type is disabled.
```
