### ISSUE TITLE
Response for container create has null value for non-nullable field

### ISSUE THREAD

**Issue by destruktiw** [moby/moby#38222]
**Description**

Docker API returns null value for Warnings field.

According to a definition it probably should never be null. It has `x-nullable: false

https://github.com/moby/moby/blob/master/api/swagger.yaml#L4659-L4676

**Steps to reproduce the issue:**

1. Send correct, /containers/create request to API https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate
2. Check response

Example response's body:
```json
{
    "Id": "6ce9cb39c1d6a905c0fc7909235b74491d5a0f184ff097bb73ffe9a30cd7743a",
    "Warnings": null
}
```

instead of:
```json
{
    "Id": "6ce9cb39c1d6a905c0fc7909235b74491d5a0f184ff097bb73ffe9a30cd7743a",
    "Warnings": []
}
```

**Comment by olljanat** [comment]
@destruktiw which Docker version you are using?

**Comment by olljanat** [comment]
@thaJeztah most probably one more swagger.yaml bug

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by thaJeztah** [comment]
Hm.. interesting yes;

```
```bash
curl -s \
  --unix-socket /var/run/docker.sock \
  -X POST \
  "http://localhost/v1.37/containers/create?name=test" \
  -H "Content-Type: application/json" \
  -d '{"Image": "busybox:latest"}'
```

```
{"Id":"cb4b2c8eb2d4fcd15f90a1c7c09d12583ee741d7054c68a78ffc51be49aa233d","Warnings":null}
```

I see the API type that is used (and which is generated from the Swagger) _does_ produce this; https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/api/types/container/container_create.go#L10-L21

But the problem looks to be in `httputils.WriteJSON()`, as marshalling the struct to JSON results in `null`; https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/api/server/httputils/httputils_write_json.go#L8-L15

Here's a playground example; https://play.golang.org/p/dS5fQWXr5Ly

```go
package main

import (
	"encoding/json"
	"fmt"
)

// ContainerCreateCreatedBody OK response to ContainerCreate operation
// swagger:model ContainerCreateCreatedBody
type ContainerCreateCreatedBody struct {

	// The ID of the created container
	// Required: true
	ID string `json:"Id"`

	// Warnings encountered when creating the container
	// Required: true
	Warnings []string `json:"Warnings"`
}

func main() {
	var resp ContainerCreateCreatedBody
	fmt.Printf("%+v\n",resp)

	out, _ := json.Marshal(resp)
	fmt.Printf("%s\n", out)
}
```

Which produces:

```
{ID: Warnings:[]}
{"Id":"","Warnings":null}
```


Looks like this may be related; https://github.com/golang/go/commit/48c75c5f9c8e97b87fbd8f24dffa73d6b2148691 (https://github.com/golang/go/issues/2278)


So either `ContainerCreateCreatedBody` needs a custom `MarshalJSON`, or we need to add a check, and initialize an empty slice if it's `nil`;

```go
if resp.Warnings == nil {
	resp.Warnings = make([]string, 0)
}
```
