### ISSUE TITLE
Cross Repository Blob Mount didn't mount from same repositry

### ISSUE THREAD

**Issue by mmpei** [moby/moby#38221]
i was pushing some images with same base layers into different repositrys.
my docker version is "docker/1.12.0 go/go1.6.3".
registry is v2.6 release verison.

my ~/.docker/config.json file is like,
{
	"auths": {
		"hub.domain.com": {
			"auth": "token1"
		},
		"hub.domain.com": {
			"auth": "token2",
		}
	}
}

reproduce steps,
1. first i push an image into hub.domain.com/user1/image:tag1, i should push all layers.
2. i push another image into hub.domain.com/user2/image:tag2, i should push all layers too. and image1 and image2 has same base images.
3.i build a third image taged with hub.domain.com/user2/image:tag3 , and has the same base images with image1 and image2.
4.push image3, all layers should be upload, and logs like:
`time="2018-11-19T14:00:41+08:00" level=warning msg="error authorizing context: insufficient scope" go.version=go1.11 http.request.method=POST http.request.uri="/v2/user2/image/blobs/uploads/?from=user1%2Fimage&mount=sha256%3A1110dc31e100a5baeeeedaa2231ca1ebb973eb45a778e6eff85031ff01a52a60" `

i want to know why docker doesn't mount layers from user2/image in priority.
after all image2 and image3 has the same repositry name and the auth scope is same.

**Comment by olljanat** [comment]
@mmpei 1.12.0 is over two years old unsupported version. Plz upgrade to Docker CE 18.09 and then provide fill ```docker push``` command output from last push.

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by mmpei** [comment]
OK. I just want to know whether some issue like this has been fixed for i did't find any related issue report.
and i will do some test in the Docker CE 18.09 version. and any way thank you @olljanat

**Comment by thaJeztah** [comment]
Closing as this went stale
