### ISSUE TITLE
Docker EE won't start on Windows Version 1803

### ISSUE THREAD

**Issue by MattPOlson** [moby/moby#38236]
Get the following error while trying to start docker EE version 18.09.0 on windows server core version 1803.

 PS C:\Program Files\Docker> .\dockerd.exe
WARN[0000] Running experimental build
DEBU[2018-11-20T14:35:16.665289100-05:00] Listener created for HTTP on npipe (//./pipe/docker_engine)
INFO[2018-11-20T14:35:16.668290500-05:00] Windows default isolation mode: process
DEBU[2018-11-20T14:35:16.668290500-05:00] Stackdump - waiting signal at Global\docker-daemon-2896
DEBU[2018-11-20T14:35:16.669292400-05:00] Using default logging driver json-file
DEBU[2018-11-20T14:35:16.669292400-05:00] [graphdriver] trying provided driver: lcow
INFO[2018-11-20T14:35:16.669292400-05:00] lcowdriver: init: dataRoot: C:\ProgramData\docker\lcow globalMode: false
DEBU[2018-11-20T14:35:16.670290300-05:00] Initialized graph driver lcow
DEBU[2018-11-20T14:35:16.670290300-05:00] [graphdriver] trying provided driver: windowsfilter
DEBU[2018-11-20T14:35:16.670290300-05:00] WindowsGraphDriver InitFilter at C:\ProgramData\docker\windowsfilter
DEBU[2018-11-20T14:35:16.670290300-05:00] Initialized graph driver windowsfilter
DEBU[2018-11-20T14:35:16.678290300-05:00] Max Concurrent Downloads: 3
DEBU[2018-11-20T14:35:16.678290300-05:00] Max Concurrent Uploads: 5
INFO[2018-11-20T14:35:16.679289700-05:00] Loading containers: start.
DEBU[2018-11-20T14:35:16.679289700-05:00] Option Experimental: true
DEBU[2018-11-20T14:35:16.679289700-05:00] Option DefaultDriver: nat
DEBU[2018-11-20T14:35:16.679289700-05:00] Option DefaultNetwork: nat
DEBU[2018-11-20T14:35:16.683289900-05:00] Network Control Plane MTU: 1500
INFO[2018-11-20T14:35:16.683289900-05:00] Restoring existing overlay networks from HNS into docker
DEBU[2018-11-20T14:35:16.683289900-05:00] [GET]=>[/networks/] Request :
DEBU[2018-11-20T14:35:16.689291000-05:00] Network Response : [  ]
DEBU[2018-11-20T14:35:16.691290400-05:00] [GET]=>[/networks/] Request :
DEBU[2018-11-20T14:35:16.693290100-05:00] Network Response : [  ]
DEBU[2018-11-20T14:35:16.693290100-05:00] Launching DNS server for network "none"
DEBU[2018-11-20T14:35:16.694291100-05:00] Allocating IPv4 pools for network nat (ce3f840cbf42477191747df62e8f4922b4ad90d1ab05d9262b4781d7757df76a)
DEBU[2018-11-20T14:35:16.694291100-05:00] RequestPool(LocalDefault, 192.168.1.0/24, , map[], false)
DEBU[2018-11-20T14:35:16.699288200-05:00] RequestAddress(192.168.1.0/24, <nil>, map[RequestAddressType:com.docker.network.gateway])
DEBU[2018-11-20T14:35:16.699288200-05:00] HNSNetwork Request ={"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"192.168.1.0/24"}]} Address Space=[{192.168.1.0/24  []}]
DEBU[2018-11-20T14:35:16.699288200-05:00] [POST]=>[/networks/] Request : {"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"192.168.1.0/24"}]}
DEBU[2018-11-20T14:35:16.779813000-05:00] releasing IPv4 pools from network nat (ce3f840cbf42477191747df62e8f4922b4ad90d1ab05d9262b4781d7757df76a)
DEBU[2018-11-20T14:35:16.779813000-05:00] ReleasePool(192.168.1.0/24)
DEBU[2018-11-20T14:35:16.780805700-05:00] daemon configured with a 15 seconds minimum shutdown timeout
DEBU[2018-11-20T14:35:16.781803300-05:00] start clean shutdown of all containers with a 15 seconds timeout...
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : There are no more endpoints available from the endpoint mapper.

**Comment by chetanchougle** [comment]
I seen this issue , After System restart it got fixed  . I got same error message . It was probablyt due to some dangling network i believe .  
If it doesn't fix in your case , try **docker system prune commands**

**Comment by olljanat** [comment]
@MattPOlson did you got this one working?

**Comment by olljanat** [comment]
Derek add label: version/18.09

**Comment by GregorySWI** [comment]
In case you still have this issue, or anyone else comes across the error:

> HNS failed with error : There are no more endpoints available from the endpoint mapper.

In my case, this issue was I had the Windows Firewall service disabled. Re-enabling it (and leaving all profiles turned off) fixed this error for me.

**Comment by thaJeztah** [comment]
Looks like the original reporter did not return, so let me close this one for now
