### ISSUE TITLE
failed to copy files: failed to copy directory: Error processing tar file(exit status 1): write * no space left on device

### ISSUE THREAD

**Issue by john612** [moby/moby#38234]
I am receiving the no space on disk error over and over.
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.03.1-ol
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: Oracle Linux Server 7.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51GiB
Name: dcmidavbrd4033
ID: XWYQ:2MB3:THRE:PKGN:S66Y:CT35:AOQC:4V5C:GWAH:JTOW:ZDRQ:FMV6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 32
 System Time: 2018-11-20T14:38:37.512002321-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              3                   0                   494.4MB             494.4MB (100%)
Containers          0                   0                   0B                  0B
Local Volumes       0                   0                   0B                  0B
Build Cache                                                 0B                  0B

I tried editing the config with simialr parameters but service wont start afterwards: ExecStart=/usr/bin/dockerd --graph="/mnt/docker-data" --storage-driver=overlay --storage-opt=dm.basesize=30G

**Comment by cpuguy83** [comment]
`--storage-opt=dm.basesize=30G` is not for the overlay driver, so I wouldn't be surprised if this causes an error on startup.

`--storage-driver=overlay` this is a legacy driver and uses an excessive amount of inodes which can also lead to the "no space left on device" error (when all inodes are exhausted)

**Comment by john612** [comment]
My driver is : Storage Driver: overlay2

**Comment by john612** [comment]
inodes are at 80% on that volume

**Comment by cpuguy83** [comment]
If you are getting no space left, then that's what it means. This is coming directly from the kernel.

**Comment by john612** [comment]
I dont think so there is plenty of disk space
 df -h
Filesystem                                                          Size  Used Avail Use% Mounted on
/dev/mapper/vgos-rootvol                                             16G  4.4G   11G  30% /
devtmpfs                                                            7.8G     0  7.8G   0% /dev
tmpfs                                                               7.8G     0  7.8G   0% /dev/shm
tmpfs                                                               7.8G   41M  7.8G   1% /run
tmpfs                                                               7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda1                                                           938M  307M  584M  35% /boot
/dev/mapper/vgos-homevol                                            1.9G   29M  1.7G   2% /home
/dev/mapper/vgos-tmpvol                                             1.9G  3.7M  1.8G   1% /tmp
/dev/mapper/vgos-varvol                                             7.3G  7.3G     0 100% /var
/dev/mapper/vgos-oemagentvol                                        9.8G  6.4M  9.4G   1% /opt/oracle/oemagent
nam.dcmisln19b.edc.nam.gm.com:/ifs/nam/gsmc/crmsaio0115932/data002  120G   29G   92G  24% /siebel

**Comment by john612** [comment]
There is plenty of disk space over 92gb

**Comment by cpuguy83** [comment]
Based on the fact that your `docker info` says it's running in `/var/lib/docker` and from your disk usage on `/var` (`/dev/mapper/vgos-varvol 7.3G 7.3G 0 100% /var`), it would appear full.

**Comment by john612** [comment]
I resolved the issue with the space it appears to be a permissions issue.

**Comment by EliasCh** [comment]
Deleting rubbish (unlabeled ) images solved a similar issue for me
