### ISSUE TITLE
Docker Service port is already exposed when service has not passed healthcheck yet.

### ISSUE THREAD

**Issue by darkl0rd** [moby/moby#38237]
**Description**

When deploying a replicated service in swarm mode, the port of a service is already exposed prior to the service being healthy.

**Steps to reproduce the issue:**
1. Create a global service with a port exposed 
2. On all nodes the port will be available as expected (curl localhost:port)
3. Kill the service on any node
4. curl localhost:port will fail, the iptables rules will be gone
5. wait for swarm to respawn the container.
6. As soon as the container is spawned, the port is accesible again - even when the container is still "Starting" and not "Healthy" yet.

**Describe the results you received:**

The port to be exposed as soon as the container starts up.

**Describe the results you expected:**

The port to be exposed as soon as the container becomes Healthy.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using the routing mesh or host publishing results in the same behavior.

**Output of `docker version`:**

18.06.1-ce

**Output of `docker info`:**

Containers: 35
 Running: 20
 Paused: 0
 Stopped: 15
Images: 31
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xxxxxxxxxxxx
 Is Manager: true
 ClusterID: xxxxxxxxxxxx
 Managers: 3
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
  x.x.x.x:2377
  x.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-139-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: xxxx
ID: xxxx:xxxx:xxxx:xxxx:xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels: xxxx
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by olljanat** [comment]
Derek add label: version/18.06

**Comment by olljanat** [comment]
@darkl0rd can you plz try with latest Ubuntu version together with latest Docker version and tell if problem still exists on there?

**Comment by darkl0rd** [comment]
Verified that this is no longer the case with 18.09.2

**Comment by darkl0rd** [comment]
3c78d017e10d        traefik:1.7.24                                                                       "/traefik"   16 minutes ago      Up 15 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik_traefik.1.hll3gfjpqd9frsmjbqa0qjcwm

$ docker rm -f 3c78
3c78

# Wait until the port comes back
$ while true; do netstat -an | grep -q grep :80.*LISTEN && break; sleep 1; done
# Confirm
$ netstat -an | grep :80.*LISTEN 
tcp6       0      0 :::80                   :::*                    LISTEN

# Traefik's health is still "starting" -- port should NOT be exposed yet.
$ docker ps -ef | grep traefik
f38ae0f7db7e        traefik:1.7.24                                                                       "/traefik --consul -…"   13 seconds ago      Up 6 seconds **(health: starting)**   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik_traefik.1.o6cga6wvkihxqsxmeifvwf0t0

This is running Docker 19.03.8 in Docker Swarm mode (I'm in doubt now whether it did properly work in 18.09.2!)
Ports exposed through 'host mode'.

**Comment by sam-thibault** [comment]
This is stale issue.  We don't have plans to support this right now.  I will close this.
