### ISSUE TITLE
Failed to start container: id already in use (after reboot)

### ISSUE THREAD

**Issue by ankul-shippable** [moby/moby#38249]
**Description**
Container with `restart=always` fails to restart after machine is rebooted

**Steps to reproduce the issue:**
1. Install docker version `18.03.1-ce` on ubuntu 16.04 LTS machine.
2. Start a container with `restart=always`
3. Reboot the machine several times.

**Describe the results you received:**
After sometime our container does not restart and fails with the error:
```
Nov 12 04:59:42 node-962a1238 dockerd[1290]: time="2018-11-12T04:59:42.510523865Z" level=info msg="Removing stale sandbox bf8038ecbf612879caeaa224f80f9995b6f62409cf66ac45fc707b96204d7afc (79c6ec76a773791ea3cdcbc88c9664ccfc0580a5c8a73faf12f23a1dd2323879)"
Nov 12 04:59:42 node-962a1238 dockerd[1290]: time="2018-11-12T04:59:42.542730939Z" level=info msg="Removing stale endpoint reqProc-5be8e8137551a306007999a1 (d553bcbfc82c4e9fb776fddf1bf9f77595a8936234132c731c9dbc2d839c78a0)"
Nov 12 04:59:42 node-962a1238 dockerd[1290]: time="2018-11-12T04:59:42.547410154Z" level=info msg="Fixing inconsistent endpoint_cnt for network bridge. Expected=0, Actual=1"
Nov 12 04:59:42 node-962a1238 dockerd[1290]: time="2018-11-12T04:59:42.611847891Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Nov 12 04:59:42 node-962a1238 dockerd[1290]: time="2018-11-12T04:59:42.999414691Z" level=error msg="Failed to start container 79c6ec76a773791ea3cdcbc88c9664ccfc0580a5c8a73faf12f23a1dd2323879: id already in use"
```

**Additional information you deem important (e.g. issue happens only occasionally):** It happens randomly.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by olljanat** [comment]
@ankul-shippable can you plz try with latest Ubuntu version together with latest Docker version and tell if issue still exists?

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by tschikarski** [comment]
Just had the exact same issue. Containers "failed to start", because "id already in use". Services weren't available until our monitoring made me aware of this. Doing `systemctl restart docker` solved the issue. It seems that the first start attempt failed, but somehow cleaned up the problem. Versions: Ubuntu 16.04.5, Docker version 18.09.1, build 4c52b90 (after the upgrade).

**Comment by rominator1983** [comment]
Same over here with docker 18.09.1 and Debian GNU/Linux 9.7 (stretch) on kernel Linux 4.9.0-8-amd64.

The error has been around much longer ony my machine and thus in different versions since I use auto-updates. I had no time to address this issue til now:

Output of `docker version`
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by AndyChuang1** [comment]
I also have the same problem on docker 18.09.1 and Ubuntu 16.05 LTS. Container will exit with `error : Failed to start container: id already in use`  randomly after reboot.

**Comment by RaulWhite** [comment]
Same over here. Docker 18.09.2 in Ubuntu Server 18.04.2 LTS amd64 with Kernel 4.18.0-15-generic, but it also occured with kernel 4.15. I am using Docker Compose, and it happens with all 3 containers at the same time. Restarting docker.service with systemctl starts containers with no problem.

Output of `docker version`

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by cpuguy83** [comment]
Should be resolved by https://github.com/moby/moby/pull/38364

**Comment by AndyChuang1** [comment]
How to use this version?

**Comment by cpuguy83** [comment]
It's not been released, but may be included in an 18.09.x release, if there is a new one.

**Comment by Kealman** [comment]
@cpuguy83 Is there any way to start container with that error on 18.09 or 18.06 without recreate?

**Comment by giorgiosironi** [comment]
Going by dates alone, https://docs.docker.com/engine/release-notes/#18093 which was released on 2019-02-28 should have that fix. 
Actually the changelog there links the [backport pull request](https://github.com/docker/engine/pull/154) that includes it.
