### ISSUE TITLE
Is there any easier way to restore the whole root fs from the image tar archive ?

### ISSUE THREAD

**Issue by zrss** [moby/moby#38247]
**Description**

Hi all, i am a fresh man in docker ... and currently i want to find a way to restore the root fs from the image tar archive for scanning file system

and i found this repo have done some stuff for this purpose https://github.com/GoogleContainerTools/container-diff

but it failed to cover some cases (lack of some files in image tar archive)

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zrss** [comment]
#22766

**Comment by AkihiroSuda** [comment]
`docker load; docker create; docker export`, or you can implement your own tool: https://github.com/moby/moby/tree/master/image/spec

**Comment by zrss** [comment]
@AkihiroSuda , thanks for the reply, i'd like to do it in a container rather than host, so i have to do it without docker

and do u means that i can use `docker export` for exporting an container and untar it for scanning ?

but in my case, i can download the image tar archive from the registry, but there is no a easier way to restore fs directly from the image tar archive without `docker`'s help

WDYT, or how can i impl that without **docker**

**Comment by zrss** [comment]
To clarify

i have a image for scanning user's image, and the workflow is

1. run my image (short as A) through a PAAS platform (yeah, kubernetes)
1. download the user's image tar archive in A
1. restore the image root fs from the tar archive
1. do scanning on the image root fs

2 - 4 are done in A container

and i found a tool to do some work for restoring the root fs of image tar archive without the help of docker

can there is a lib or an idea for helping me to do that ?

many thanks 😄

**Comment by AkihiroSuda** [comment]
You may want to look into https://github.com/containers/skopeo

**Comment by zrss** [comment]
thanks @AkihiroSuda , i will take a look at it
