### ISSUE TITLE
docker stats CPU usage greater than 100% times number of cores

### ISSUE THREAD

**Issue by lth2015** [moby/moby#38253]
> 
> result from docker stats
> ![screenshot from 2018-09-28 17-38-18](https://user-images.githubusercontent.com/6814841/46238904-160edd00-c346-11e8-8972-da89196376a2.png)
> result from docker inspect
> ![screenshot from 2018-09-28 17-43-23](https://user-images.githubusercontent.com/6814841/46238905-160edd00-c346-11e8-92bb-4e5180939095.png)
> result from htop
> ![screenshot from 2018-09-28 17-43-36](https://user-images.githubusercontent.com/6814841/46238906-160edd00-c346-11e8-83a6-ef5055954320.png)
> 
> @thaJeztah

I have the same problem.

![1e848d4a-84f4-4f0d-a28a-1cdcb8532a02](https://user-images.githubusercontent.com/12841814/48914222-b5b79a00-eeb5-11e8-8ca5-d41ab7efeb7f.png)

![82b9426c-cd7c-48e3-a7d3-42a107b372a5](https://user-images.githubusercontent.com/12841814/48914235-c10ac580-eeb5-11e8-93d0-ddee228e882a.png)

_Originally posted by @lth2015 in https://github.com/moby/moby/issues/28941#issuecomment-441076871_

**Comment by lth2015** [comment]
OS version:
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

-----------------------------------------

uname -a
Linux sjsa-k8s-node01 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

-----------------------------------------
docker info:

Containers: 241
 Running: 234
 Paused: 0
 Stopped: 7
Images: 1622
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16804
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.8 GiB
Name: sjsa-k8s-node01
ID: ECMN:RDMS:Q24L:6ON2:6OU5:VBYQ:GPOR:E2RN:3JCN:OESP:XYT2:UBPM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8


-----------------------------------------

docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

-----------------------------------------
we use kubernetes(1.4.9)
cpu.shares/cpu.cfs_quota_us/cpu.cfs_period_us:

docker_id: b44d524a89e6034999108791db3da8527924bb8dfca47b2a5d0bd876a63bf42e
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 200000
cpushares: 2048

docker_id: b8c2ff4fc9b5426970e879a51caeef6b1ab120f6eed6ef2406a4d1c1f00f9c19
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 200000
cpushares: 204

docker_id:  bec7143877eb1f2e0cf1bdb38bc7ac43c4427428c0c2ae66bfb851901eedd12f
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 20000
cpushares: 51


-----------------------------------------

### **In addition, the load of our physical machine will rise very high, causing the physical machine to crash, and no reason is found.**

**Comment by lth2015** [comment]
some data from monitoring system:

load5 from zabbix:
![c650f119-83f3-4aeb-a86c-2f97dcdcbc27](https://user-images.githubusercontent.com/12841814/48916956-68d8c100-eebf-11e8-9f16-3a0e5223a4a2.png)

idle from zabbix:
![image](https://user-images.githubusercontent.com/12841814/48916971-7db55480-eebf-11e8-8d72-38e1eff4f778.png)

docker stats:
![image](https://user-images.githubusercontent.com/12841814/48916984-902f8e00-eebf-11e8-88b7-cf6eb02dd9c0.png)

**Comment by thaJeztah** [comment]
That's a really, really old version of Docker (and kubernetes); Docker 1.12 reached end of life in January  2017, and hasn't been maintained since. Are you seeing the same issue on a current version of Docker?

Looking at those settings; `quota` is `100000` and `period` is `200000`, which (if I'm not mistaken) means; those containers are configured to use 2 CPUs (thus 200%) correct?

**Comment by lth2015** [comment]
In another environment we use docker(1.3.1) haven't this problem. 

I don't think docker is the reason of the crash problem. But I want to know about the probability of this issue, can you give me some suggestion?

Thank you for your help

**Comment by thaJeztah** [comment]
Closing as this went stale
