### ISSUE TITLE
[Feature Request] build args file

### ISSUE THREAD

**Issue by ysh7** [moby/moby#38257]
**Description**

Similar to `--env-file` flag in `docker run` which accepts a file for list of environment variables. Can we have a flag in `docker build` (eg. `--build-args-file`) for passing build arguments with a file.
This will be useful when there are more than one `--build-args`.

Thanks,
Yagnesh

**Comment by olljanat** [comment]
Derek remove label: status/more-info-needed

**Comment by AkihiroSuda** [comment]
`docker buildx bake` (https://github.com/docker/buildx#file-definition) supports specifying args in the bake file.
