### ISSUE TITLE
Can not auto mount /sys/kernel/security,

### ISSUE THREAD

**Issue by huandong-gohigh** [moby/moby#38260]
I want to build a base image and auto mount  /sys/kernel/security  when starting container，but atuo mount failed  I must manual mount.
my setup:
1. build base image.
2. create Dockerfile.
   .Dokerfile:
FROM ctrust-hte:7.4v3
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]

    entrypoint.sh
#!/bin/bash
set -e
mount -t securityfs securityfs /sys/kernel/security

3. run container
 docker build -t hte-test ./               
Sending build context to Docker daemon 1.443 MB
Step 1/5 : FROM ctrust-hte:7.4v3
 ---> 16af76cb504d
Step 2/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 36ba54915a57
Step 3/5 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> e24bc7637e99
Step 4/5 : RUN touch /test
 ---> Using cache
 ---> e5c6d2d6bcb5
Step 5/5 : CMD /entrypoint.sh
 ---> Using cache
 ---> e63cd0ce0179
Successfully built e63cd0ce0179

4. run container
   docker run -it  hte-test bash
   the result:
![image](https://user-images.githubusercontent.com/20769256/48964109-ff9aa000-efdb-11e8-8078-2cb73d0807fa.png)

5. manual operator mount -t securityfs securityfs /sys/kernel/security 
the result:
![image](https://user-images.githubusercontent.com/20769256/48964130-3f618780-efdc-11e8-864c-f5ff6e6c1ed3.png)

**Comment by lukahartwig** [comment]
Your Dockerfile specifies `CMD ["/entrypoint.sh"]`. When you do `docker run -it hte-test bash` you override the `CMD` with `bash` so your script never gets executed.

Change `CMD ["/entrypoint.sh"]` to `ENTRYPOINT ["/entrypoint.sh"]` and then add `exec "$@"` to the end of your script and it should work.

**Comment by thaJeztah** [comment]
Yes, this doesn't look like a bug, but a miss-understanding how `CMD` works. Let me go ahead and close this issue, but feel free to continue the conversation.

(Thanks @lukahartwig for helping out!)

**Comment by huandong-gohigh** [comment]
> ENTRYPOINT

You are right. Thank you.
