### ISSUE TITLE
Docker volume CreatedAt time is not really the date of creation

### ISSUE THREAD

**Issue by mihai-dinu** [moby/moby#38274]
**Description**
The volume createdAt time is not really the time of creation of the docker volume, but more the time the volume was last updated.

**Steps to reproduce the issue:**
1. docker volume create testCtime
2. docker volume inspect testCtime > ctime1.log
3. docker run --rm -v testCtime:/data debian:stretch-slim touch /data/a
4. docker volume inspect testCtime > ctime2.log
5. diff ctime1.log ctime2.log

**Describe the results you received:**
The docker volume creation time is updated based on when new files are written to the volume. So it's actually the change time rather than the creation time.
```bash
➜  docker volume create testCtime
testCtime
➜  docker volume inspect testCtime > ctime1.log
➜  docker run --rm -v testCtime:/data debian:stretch-slim touch /data/a
➜  docker volume inspect testCtime > ctime2.log
➜  diff ctime1.log ctime2.log
3c3
<         "CreatedAt": "2018-11-26T15:00:06+01:00",
---
>         "CreatedAt": "2018-11-26T15:00:19+01:00",
```

**Describe the results you expected:**
The creation time of the docker volume should have remained the one from ctime1.log and not change when files are added or removed from the volume. 

**Additional information you deem important (e.g. issue happens only occasionally):**
The problem seems to be with the way the creation time is computed on linux systems.
https://github.com/moby/moby/blob/0b7cb16dde4a20d024c7be59801d63bcfd18611b/volume/local/local_unix.go#L97
It uses  
```go
fileInfo.Sys().(*syscall.Stat_t).Ctim.Unix()
```
instead of 
```go
fileInfo.Sys().(*syscall.Statx_t).Btim.Unix()
```
which is desribed here: https://golang.org/src/cmd/vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go

The only constraint though is that `statx` is available with kernel versions 4.11+

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        
 Built:             Sat Aug 25 18:30:58 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
  Built:            Sat Aug 25 18:30:40 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 849
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8f54c750c67e87a3b1c218208bbd5cc427c653e9 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: N/A (expected: )
Security Options:
 apparmor
Kernel Version: 4.18.16-96.current
Operating System: Solus 3.9999
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.56GiB
Name: solus
ID: YHOL:PG7Q:YL6F:5XRA:7RYL:6RWA:VNGC:VVIX:BAQH:FTKU:HG4G:32CY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: syeupload
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by thaJeztah** [comment]
Thanks for reporting. What I _think_ is happening (haven't checked the code yet), is that `.CreatedAt` is determined from looking at the volume's `_data` directory; when initializing a volume for the first time, metadata (owner, permissions, timestamps) for that directory are copied from the container.

```bash
docker volume create testCtime
testCtime

docker volume inspect --format '{{.CreatedAt}}' testCtime
2018-11-26T14:24:51Z
ls -la /var/lib/docker/volumes/
total 36
drwx------  3 root root  4096 Nov 26 14:24 .
drwx--x--x 15 root root  4096 Nov  9 16:01 ..
-rw-------  1 root root 32768 Nov 26 14:24 metadata.db
drwxr-xr-x  3 root root  4096 Nov 26 14:24 testCtime

ls -la /var/lib/docker/volumes/testCtime/
total 12
drwxr-xr-x 3 root root 4096 Nov 26 14:24 .
drwx------ 3 root root 4096 Nov 26 14:24 ..
drwxr-xr-x 2 root root 4096 Nov 26 14:24 _data
```

Now create a container, touching some files

```bash
docker run --rm -v testCtime:/data busybox touch /data/a

docker volume inspect --format '{{.CreatedAt}}' testCtime
2018-11-26T14:25:39Z

ls -la /var/lib/docker/volumes/
total 36
drwx------  3 root root  4096 Nov 26 14:24 .
drwx--x--x 15 root root  4096 Nov  9 16:01 ..
-rw-------  1 root root 32768 Nov 26 14:24 metadata.db
drwxr-xr-x  3 root root  4096 Nov 26 14:24 testCtime

ls -la /var/lib/docker/volumes/testCtime/
total 12
drwxr-xr-x 3 root root 4096 Nov 26 14:24 .
drwx------ 3 root root 4096 Nov 26 14:24 ..
drwxr-xr-x 2 root root 4096 Nov 26 14:25 _data
```

If that's indeed the case, then I think a solution for this would be to take the creation date of the "parent" directory (`/var/lib/docker/volumes/<volumename>`) instead of `/var/lib/docker/volumes/<volumename>/_data`.

**Comment by thaJeztah** [comment]
I'll create a PR to fix this

**Comment by mihai-dinu** [comment]
Thanks for looking into it so fast! I think you might be right. The `createdAt()` function does look at the volume's `_data` directory. In that case, it might actually be sufficient to just look at the parent directory ctime since I assume no other folders will be created in the `/var/lib/docker/volumes/<volumename>/` path by docker.

**Comment by thaJeztah** [comment]
oh, almost forgot to actually push, haha; here's a PR https://github.com/moby/moby/pull/38276
