### ISSUE TITLE
Addressed these comments. I am now wondering if these flags work on Windows services and if there is a Windows server equivalent of `cgroups` anyway. @johnstep do you have thoughts on this?

### ISSUE THREAD

**Issue by abjinugu** [moby/moby#38288]
_Originally posted by @mistyhacks in https://github.com/moby/moby/pull/32631#issuecomment-294261441_

**Comment by thaJeztah** [comment]
No, windows doesn't have cgroups; cgroups are a feature of the Linux kernel
