### ISSUE TITLE
As a developer I advise not to display any passwords anywhere IN/ON the page.

### ISSUE THREAD

**Issue by vidhurraj147** [moby/moby#38295]
**Description**
The team has to work on the login page. I am a full stack developer. As a developer, I advise not to display any passwords anywhere IN/ON the page. Even though, if it is auto-populated OR auto saved. 

**Steps to reproduce the issue:**
1. Go to https://id.docker.com/login/   
2. Click F12 dev tools
3. Click on inspect element (CTRL+SHIFT+C )
4. Select on the password input box. 
5. Find "<input id="nw_password" value="E        @">" 
Literally, you will see the whole password.

**Describe the results you received:**
You will see the whole password.

**Describe the results you expected:**
Not to see my password at all times

**Additional information you deem important (e.g. issue happens only occasionally):**
All it takes is just a simple jQuery script (see the screenshot), Cookies OR even browser extension can get my password.

![image](https://user-images.githubusercontent.com/37847430/49232641-516b6d80-f3c2-11e8-87d7-8d7fb2f7d329.png)

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like this a security related issue about Docker Hub; could you send an e-mail to security@docker.com instead?
