### ISSUE TITLE
Buildkit in docker 18.09 won't allow insecure registry with self-signed TLS

### ISSUE THREAD

**Issue by lbndev** [moby/moby#38303]
**Description**
Docker 18.09 with buildkit activated fails to pull from my private "insecure" registry.
When buildkit is deactivated, the same Dockerfile builds fine.

I originally posted this as a comment to https://github.com/moby/buildkit/issues/606 , I did more tests since then : I've found that the problem only occurs when activating the experimental syntax (to allow using RUN --mount).

[ EDIT : the above isn't true : actually both builds fail if I properly delete all images before testing ]

**Steps to reproduce the issue:**
1. In daemon.json, declare private mirror + insecure registry and activate buildkit :
```
{
  "registry-mirrors": ["https://repo.mycompany.com"],
  "insecure-registries" : ["repo.mycompany.com"],
  "features":{
    "buildkit": true
  }
}
```
2. Build the following Dockerfile - it works :
[ Edit : this was beause I had maven:3.5.3-alpine available locally, if I remove it and retry, it fails ]
```
FROM maven:3.5.3-alpine
RUN mvn dependency:help
```
3. Now modify the Dockerfile to add the experimental syntax and a --mount argument to RUN :
```
# syntax=docker/dockerfile:experimental
FROM maven:3.5.3-alpine
RUN --mount=target=/root/.m2,type=cache mvn dependency:help
```

**Describe the results you received:**
This second build fails with :
```
[+] Building 0.4s (3/3) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 169B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => ERROR resolve image config for docker.io/docker/dockerfile:experimental
------
 > resolve image config for docker.io/docker/dockerfile:experimental:
------
failed to do request: Head https://repo.mycompany.com/v2/docker/dockerfile/manifests/experimental: x509: certificate signed by unknown authority
```

**Describe the results you expected:**
I was expecting the image to build without error.

As a bonus I'm also expecting that if I delete the generated image, and build it again, the maven dependencies will not need to be downloaded again, and fetched from the mounted cache instead, making my build a lot faster (which is the main reason why I want to use this feature).

**Additional information you deem important (e.g. issue happens only occasionally):**

Note that if I do `docker pull docker/dockerfile:experimental` (which works) and retry, the error will now be on pulling maven:3.5.3-slim as part of the build. [ Edit : this was because I had done `docker images -q | xargs docker rmi` between the tests ]

I've also tested with dockerfile:1.0-experimental instead of dockerfile:experimental (as found in https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information) - with the same result.

**Output of `docker version`:**
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 497
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 9.754GiB
Name: pic
ID: JMTB:MV5N:DFIK:T6VA:BMPB:46DT:R6XZ:CLOJ:7NDD:ZVVP:BYXY:7L2F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 repo.mycompany.com
 127.0.0.0/8
Registry Mirrors:
 https://repo.mycompany.com/
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM on VMWare ESXi 6.5.
The "insecure" registry is our internal instance of Sonatype Nexus OSS 3.11.0 behind a reverse-proxy handling SSL with a letsencrypt-issued certificate. Above, I've replaced the real server address by repo.mycompany.com.

**Comment by thaJeztah** [comment]
Looks like the insecure option is not passed on to buildkit; therefore pulling the image that contains the experimental syntax fails to be pulled from your registry mirror.


ping @tonistiigi @AkihiroSuda PTAL

**Comment by lbndev** [comment]
@thaJeztah : I think it's more complex.
If I understand correctly, mirrors and insecure registries are being passed to buildkit since  https://github.com/moby/moby/pull/37852 was merged, and this was backported into 18.09 by https://github.com/docker/engine/pull/59 => my version should have it.

**Comment by tonistiigi** [comment]
@lbndev Your registry is using https with a self-signed certificate, right? Or are you saying that you still have issues if you run the registry on plain http and configure the mirror to use that.

**Comment by lbndev** [comment]
The registry is behind a reverse-proxy which listens on ports 80 and 443. For SSL it uses a certificate issued by letsencrypt. If in daemon.json I set the mirror URL to http (and not https), I would expect the connection to be made without SSL on port 80. Yet, I'm still getting the same issue, so I assume it is trying to use SSL regardless of what is configured in daemon.json.

**Comment by tonistiigi** [comment]
@dmcgowan ^ does any of that make sense in regards how containerd resolver works?

**Comment by thaJeztah** [comment]
@lbndev does it work if you configure your mirror with an explicit `:80` port?

**Comment by lbndev** [comment]
@thaJeztah Nope, it doesn't work either. The error is slightly different though ;) - see in the log how it is using https despite the mirror address is configured as HTTP ?
```me@pic:~/test$ docker build .
[+] Building 0.1s (3/3) FINISHED
 => [internal] load .dockerignore
 => => transferring context: 2B
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 238B
 => ERROR resolve image config for docker.io/docker/dockerfile:1.0-experimental
------
 > resolve image config for docker.io/docker/dockerfile:1.0-experimental:
------
failed to do request: Head https://repo.mycompany.com:80/v2/docker/dockerfile/manifests/1.0-experimental: http: server gave HTTP response to HTTPS client
me@pic:~/test$ sudo cat /etc/docker/daemon.json
{
  "registry-mirrors": ["http://repo.mycompany.com:80"],
  "insecure-registries" : ["repo.mycompany.com"],
  "features":{
    "buildkit": true
  }
} 
```
(if I remove the "insecure-registries" entry, restart docker, and try again, I'm getting the same error)

**Comment by thaJeztah** [comment]
That may be because the insecure registry doesn't match your mirror; can you try using 

```
  "insecure-registries" : ["repo.mycompany.com:80"],
```

As different registries can be running on different ports

**Comment by tonistiigi** [comment]
If you are using a certificate from letsencrypt, why are you configuring insecure registries at all? I'm not sure we have tracked down the actual issue in here. There is a known problem with registries with self-signed certificates configured as insecure, everything else should work. 

Also, what do you mean by "private mirror".

**Comment by lbndev** [comment]
Initially the registry was using a self-signed certificate, so I had to declare it as insecure.
Then I switched to letsencrypt and it wouldn't work without that setting. Then I followed the documentation to add letsencrypt certificates in /etc/docker/certs.d/, and I am finally able to remove this setting and use my "secure" registry with the "default" builder. Still, it doesn't solve the issues with buildkit (see below).

Our "private mirror" is an instance of Sonatype Nexus 3 configured as a [proxy repository of docker.io](https://help.sonatype.com/repomanager3/private-registry-for-docker/proxy-repository-for-docker). We also have a [hosted private repository](https://help.sonatype.com/repomanager3/private-registry-for-docker/hosted-repository-for-docker-%28private-registry-for-docker%29) and both are in a [single group](https://help.sonatype.com/repomanager3/private-registry-for-docker/grouping-docker-repositories). URL https://repo.mycompany.com/ points to this group. It is used in daemon.json in the registry-mirrors entry.

This morning I'm testing with the following configuration in daemon.json :
```
{
  "registry-mirrors": ["https://repo.mycompany.com"],
  "features":{
    "buildkit": true
  }
}
```
This is the output I'm getting for `docker build .` (same Dockerfile as above):
```
[+] Building 0.3s (3/3) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 238B 
 => [internal] load .dockerignore 
 => => transferring context: 2B 
 => ERROR resolve image config for docker.io/docker/dockerfile:1.0-experimental
------
 > resolve image config for docker.io/docker/dockerfile:1.0-experimental:
------
docker.io/docker/dockerfile:1.0-experimental not found
```
(I've also tried with docker/dockerfile:experimental, same result)

However, `docker pull docker/dockerfile:1.0-experimental` succeeds...
So after pulling the "experimental" image, I retried and the build goes further, but fails with a similar error:
```
------
 > [internal] load metadata for docker.io/library/maven:3.5.3-alpine:
------
------
 > [1/4] FROM docker.io/library/maven:3.5.3-alpine:
------
rpc error: code = Unknown desc = docker.io/library/maven:3.5.3-alpine not found
```

If I understand correctly:

- buildkit has a problem when the insecure-registry setting is used, the workaround is to configure the certificates properly to use the registry as a secure one
 - even with a secure registry, buildkit fails to fetch the images when the registry-mirrors setting is used (in my case, Sonatype Nexus). The strange thing is that a `docker pull` of these same images succeeds : it seems that buildkit is not pulling images the same way the cli does ??

**Comment by helmuthva** [comment]
We are using private registries and a registry mirror on private domains with plain http. Will there be a fix for buildkit supporting plain http registries in the future?

**Comment by jamiejackson** [comment]
@tonistiigi, does this ticket suffice for the problem with the combination of buildkit, insecure registries, and plain HTTP, or do we need another ticket?

**Comment by thaJeztah** [comment]
Is this still a problem on Docker 19.03? (I recall some improvements were made; not sure if it's resolved or not)

**Comment by tonistiigi** [comment]
@jamiejackson Renamed the issue to be specific about self-signed tls support (that can now be implemented after https://github.com/moby/buildkit/pull/1145). Plain HTTP should already work in all cases.

**Comment by jansmets** [comment]
any update? I'm really struggling with this.

**Comment by tonistiigi** [comment]
@jansmets This has not yet been implemented. Try to add system ca as a workaround.

**Comment by jamiejackson** [comment]
> Plain HTTP should already work in all cases.

@tonistiigi , I'm not sure that's true: https://github.com/moby/buildkit/issues/606

**Comment by irischad** [comment]
This appears to still be an issue with 19.03.6. 
I'm using Artifactory as a private registry, and have it signed with a self signed cert. `docker push` and `docker pull` commands work without issue. I'm using `--build-arg BUILDKIT_INLINE_CACHE=1` to add cache to my images. When trying to reference for another build via `--cache-from $PRIVATE_REGISTRY/$IMAGE:$TAG` it fails with:

`=> ERROR importing cache manifest from $PRIVATE_REGISTRY/$IMAGE:$TAG`

rerunning with `--progress=plain` shows:

`#4 importing cache manifest from $PRIVATE_REGISTRY/$I...`
`#4 ERROR: failed to do request: Head $PRIVATE_REGISTRY/v2/$IMAGE/manifests/$TAG: x509: certificate signed by unknown authority`

The current workaround in my scripts is to do a `docker pull $PRIVATE_REGISTRY/$IMAGE:$TAG` right before the `docker build` command which then allows buildkit to find the image. 

Would be nice to get buildkit to honor the insecure-registries configuration.

**Comment by irischad** [comment]
Updated workaround: adding the cert used on my Artifactory server to the docker host works with buildkit. That is 
`cp <cert> /usr/local/share/ca-certificates/`
`update-ca-certificates`
`systemctl restart docker`
works just fine.

**Comment by tonistiigi** [comment]
https://github.com/moby/moby/pull/40814 https://github.com/moby/moby/pull/40967

**Comment by zhangguanzhang** [comment]
same issue with docker 20.10,  if registry work on http://repo.mycompany.com, notice the `insecure-registries`
```
{
  "registry-mirrors": ["https://repo.mycompany.com"],
  "insecure-registries" : ["http://repo.mycompany.com"],
  "features":{
    "buildkit": true
  }
}
```

**Comment by jansmets** [comment]
yeah, noticed last week it was still a problem :(

**Comment by iamkhalidbashir** [comment]
same problem

**Comment by omamoo** [comment]
Just facing the same problem, for now we disabled the BuildKit by setting environment variable `DOCKER_BUILDKIT=0`

**Comment by RonnyJiang** [comment]
If you don't want to configure the CA certificate，you can modify your docker configuration file (/etc/docker/daemon.json) so that it can work properly.
{
  "insecure-registries": ["http://myregistry.domain.com"]
}

**Add the prefix 'http://' in front of 'myregistry.domain.com'**

**Comment by cowwoc** [comment]
You can't use this workaround any more: https://github.com/moby/moby/pull/29988

```
time="2025-02-06T13:15:31.922128780Z" level=warning msg="insecure registry http://myregistry:5000/ should not contain 'http://' and 'http://' has been removed from the insecure registry config"
```
