### ISSUE TITLE
Docker EE download contains multiple copies of docker.exe and dockerd.exe starting in 18.09

### ISSUE THREAD

**Issue by davidmatson** [moby/moby#38308]
### Expected behavior
Docker download contains a single copy of docker.exe/dockerd.exe.

### Actual behavior
Docker download contains two copies of docker.exe/dockerd.exe.

### Information
Starting with version 18.09, the official download for Docker EE for Windows contains multiple copies of the same files. The download is multiple times larger than it used to be.

### Steps to reproduce the behavior
  1. Download:
https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip
  2. Download:
https://download.docker.com/components/engine/windows-server/18.03/docker-18.03.1-ee-4.zip
  3. Compare the contents of the two zips.
  4. Using 7-zip, note the two copies of docker.exe and dockerd.exe, one "Unix" and the other "FAT", in 18.09 only.

The "FAT" copy is not signed with a digital signature, while the "Unix" copy is. In 18.03, only a signed copy was provided. Is the duplication of these files with both signed & unsigned variants intended?

Previously, extracting using Windows built-in zip support just worked. Now, it gives an error saying the file already exists (due to two files with the same name in the same location).

**Comment by davidmatson** [comment]
I had originally posted in docker/for-win thinking the issue was specific to docker more than moby, but that repo appears to be CE only. If there's a better place to file this issue, please let me know.

**Comment by thaJeztah** [comment]
ping @jose-bigio I think this was fixed in packaging, correct?

**Comment by jhowardmsft** [comment]
ping @jose-bigio again

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.

**Comment by thaJeztah** [comment]
Thanks for checking, @davidmatson ❤️
