### ISSUE TITLE
One more personality API case should be allowed in seccomp/default.json

### ISSUE THREAD

**Issue by johnfound** [moby/moby#38317]
**Description**

In the file `default.json` there are several allowed variants of the API function `personality()`. But one variant is missing that is needed in some cases. (read [how we faced with this issue](https://board.asm32.info/docker-support.256/) in our project)

It is the personality `PER_LINUX32_3GB` == `0x08000008` - a 32bit program with memory limited to 3GB. (0xc0000000)

This personality is rarely used, but fully safe, so IMHO it worth to be added to the official default security profile. 

Regards

**Comment by cpuguy83** [comment]
ping @justincormack

**Comment by johnfound** [comment]
Here is the json that have to be added to the file [default.json](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json):
``` json
{
  "names": [
    "personality"
  ],
  "action": "SCMP_ACT_ALLOW",
  "args": [
    {
      "index": 0,
      "value": 134217736,
      "valueTwo": 0,
      "op": "SCMP_CMP_EQ"
    }
  ],
  "comment": "",
  "includes": {},
  "excludes": {}
}
```

**Comment by thaJeztah** [comment]
@justincormack @jessfraz PTAL

**Comment by thaJeztah** [comment]
From a chat with Justin on slack, and he was a bit on the fence on making this change

> Hmm, not sure about that. I got personality added to the OCI spec (although with only the 32 bit flag initially) so that you could set permanently instead. I think they should just run without seccomp.

Given that this (per the description) is rarely used, I'm closing this for now, but we can revisit if arguments come up to make the change.

**Comment by johnfound** [comment]
Well, it is rarely used, but it worth nothing to be fixed. Rejecting 0-cost fixes with argument of rare use is at least strange.

Anyway, it is your project. I only wanted to help.

**Comment by thaJeztah** [comment]
@justincormack is working on some changes in how the seccomp-policy is structured, and may take this one into account in that rewrite
