### ISSUE TITLE
LCOW Windows Server 2019 problem

### ISSUE THREAD

**Issue by JensNordenbro** [moby/moby#38320]
I was expecting LCOW to work out of the box on Windows Server 2019. 
This does not seem to be the case. What is the statement on this and if it is not supposed to work, how do I get experimental mode to work? 
I have been trying https://gist.githubusercontent.com/riezebosch/b683ef501f35050abf5fdd6a86926bb9/raw/install-docker.ps1 to be able to run a side-by-side installation however all I get is:
```

PS C:\Users\jnb\Desktop\experimental> docker.exe run -it ubuntu:trusty
Unable to find image 'ubuntu:trusty' locally
trusty: Pulling from library/ubuntu
aa1a66b8583a: Pull complete
aaccc2e362b2: Pull complete
a53116a2808f: Pull complete
b3a7298e318c: Pull complete
Digest: sha256:f961d3d101e66017fc6f0a63ecc0ff15d3e7b53b6a0ac500cd1619ded4771bd6
Status: Downloaded newer image for ubuntu:trusty
C:\Program Files\Docker\docker.exe: Error response from daemon: failed to start service utility VM (createreadwrite): kernel 'C:\Program Files\Linux Containers\kernel' not found.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS C:\Users\jnb\Desktop\experimental>




```

**Comment by dallaren** [comment]
I am also seeing this error on Windows Server 2019.

**Comment by JensNordenbro** [comment]
Downloading a later lcow in the gist PS script made it work however it is all experimental.

**Comment by olljanat** [comment]
Derek add label: area/lcow

**Comment by olljanat** [comment]
@JensNordenbro because LCOW is experimental feature I recommend that you ask help from https://github.com/linuxkit/lcow

Anyway, I would appreciate if you can share use cases where you are planning to use this feature on MicrosoftDocs/Virtualization-Documentation#851
I'm interested about it because I would like to understand why Microsoft waste their time to that (IMO useless) feature when there is over 200 open issues here and many of them are related real production use cases.

**Comment by JensNordenbro** [comment]
@olljanat, I started at linuxkit/lcow, they refered me here😁 I will just close this and await non-experimental support. I read your posts ans share your frustration on a lot of issues. At this point adopting Docker on Windows feels like being on thin ice.

**Comment by kkzz8888** [comment]
same error here even using the latest release.zip and docker executables as described here: https://github.com/linuxkit/lcow. I am quite surprised the state of running linux containers on widnows server 2019. I thought everything would just work OOTB, but not even close. It is useless to run anything on windows server if lcom support is not working as most of the images on the docker hub are linux based.

**Comment by olljanat** [comment]
@JensNordenbro @kkzz8888 @dallaren @kirkone btw there is epic of LCOW on #33850 where you can see state of it readiness.

I have also created this MicrosoftDocs/Virtualization-Documentation#851 item to Microsoft docs repo where I really would like to get feedback that which kind of use cases where people are planning to use this feature if/when it is ready? (plz answer either of those referenced issues. Not to this closed one).

**Comment by beruic** [comment]
I made a write-up based on this issue (and other pages) to explain how to setup Docker LCOW on Windows Server 2019.

I am posting it here, as I think it might be useful to readers of this thread:
https://stackoverflow.com/a/57691939/1031534
