### ISSUE TITLE
Overlay diff performance optimization

### ISSUE THREAD

**Issue by firjest** [moby/moby#38326]
**Description**
The overlay driver's diff function is implemented by NaiveDiffDriver. The roLayer must be implemented like this, but whether mountLayer can be directly packaged with upperdir, it will perform better than NaiveDiffDriver's diff function.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
@dmcgowan @tonistiigi

**Comment by dmcgowan** [comment]
This is for the `overlay` driver and not the `overlay2` driver

**Comment by thaJeztah** [comment]
Ah, right; and with the overlay driver being marked deprecated, I don't think we should make changes there

**Comment by thaJeztah** [comment]
Let me close this one because of the above, but feel free to continue the conversation
