### ISSUE TITLE
cgroup namespace support

### ISSUE THREAD

**Issue by rgulewich** [moby/moby#38332]
**Description**

Now that [cgroup namespace support has been added to runc](https://github.com/opencontainers/runc/pull/1916), I'd like to add support to docker.  I'm happy to do the work, but I'd like some input as to which of these approaches would work the best:

1. Always enable cgroup namespaces for all containers, provided that the currently running kernel supports it.
2. Enable for all containers, but only when the docker daemon was started with a flag to enable it (similar behaviour to `--userns-remap`).
3. Enable cgroup namespaces per-container (not for all containers), by passing a flag at container start time.

Thoughts?

CC: @cpuguy83, @stevvooe, @sargun

**Comment by cpuguy83** [comment]
Oh I hadn't realized this made it into the kernel yet, that's awesome.... guess I'm a bit behind seems it landed in 4.16!
I'll need to read up on how this works and side-effects.

Assuming there aren't any breaking side-effects, I think for all containers would be good.

**Comment by cpuguy83** [comment]
Might need to special case `--privileged`
