### ISSUE TITLE
Docker containers unable to reach internet (default CE install on Fedora 29)

### ISSUE THREAD

**Issue by jsdevel** [moby/moby#38343]
**Description**

Default installs of the nightly CE build on Fedora 29 result in containers that aren't able to reach the internet.

Applying the fix in https://github.com/systemd/systemd/issues/3374#issuecomment-339258483 resolved the issue for me, but it was frustrating because it felt like an issue with the way docker was configuring route tables.  docker0 never had attached interfaces nor did it have any route entries in the system routing table.   I stumbled across the fix via `journalctl -f` and saw a message similar to `Could not generate persistent MAC address for veth9e12d89b: No such file or directory`.

I'm really just submitting this in case others run into something similar.  Could save them some time.

**Steps to reproduce the issue:**
1.  Install Fedora 29
2.  Install CE nightly build
3.  Try to run `docker run --rm appropriate/curl http://yahoo.com`

**Describe the results you received:**

Could not reach host.

**Describe the results you expected:**

redirect from yahoo

**Additional information you deem important (e.g. issue happens only occasionally):**

I believe this is caused by systemd (see https://github.com/systemd/systemd/issues/3374)

**Output of `docker version`:**

```
Docker version 0.0.0-20181128010312-f9756bf, build f9756bf
```

**Output of `docker info`:**

```
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 11
Server Version: 0.0.0-20181128010312-f9756bf
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: de1f167ab96338a9f5c2b17347abf84bdf1dd411
runc version: 10d38b660a77168360df3522881e2dc2be5056bd
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.6-300.fc29.x86_64
Operating System: Fedora 29 (Twenty Nine)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55GiB
Name: localhost.localdomain
ID: RFJI:JBPZ:WXJL:YMA5:WTSX:OWTR:CKEK:LJAD:JPJX:D63J:2S5U:PQYY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jsdevel** [comment]
i haven't tried with the latest stable

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
