### ISSUE TITLE
consider replace Gotty with aec

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#38351]
Long time since https://github.com/Nvveen/Gotty has been updated. Looks like a much newer library can almost drop in with https://github.com/morikuni/aec

Not a high priority.

**Comment by thaJeztah** [comment]
> Latest commit by morikuni almost 2 years ago

Also not "that" new, but I guess things don't change much in these codes.

I'm fine with replacing (if there's advantages in the new dependency)

**Comment by thaJeztah** [comment]
ok; let's change this. I added some labels, perhaps someone is interested in picking it up. May need changes in docker/cli as well?

**Comment by RaviTezu** [comment]
@thaJeztah Can I take this up?

**Comment by thaJeztah** [comment]
@RaviTezu yes, sure!! Thanks!

I'll add a `status/claimed` label to this one 👍

**Comment by RaviTezu** [comment]
@thaJeztah Thanks. I see that we are trying to replace gotty with the aec and we are using gotty in [jsonmessage](https://github.com/moby/moby/blob/master/pkg/jsonmessage/jsonmessage.go) for getting the terminal info. 
But I am not sure on all the details, could you please let me know what all are expected from this PR? Any docs or references which can help me with this? Thank you.

**Comment by ijc** [comment]
@RaviTezu Gotty is quite complex and supports full termcap mapping of control characters, hence there is a bunch of code in `pkg/jsonmessage/jsonmessage.go` to consult `$TERM`, open the termcap database and handle it not being present etc with fallbacks.

By contrast aec just supports the standard ANSI subset so it is much simpler and requires no setup/open phase.

Ultimately I think you just need to replace the implementations of `clearLine`, `cursorUp` and `cursorDown` with the aec equivalents and strip out the whole `termInfo` thing which gets opened and passed around and replace it with a `bool isTerminal` (i.e. revert that subset of f02221a79419). You can remove the `termInfo interface` as well as the `noTermInfo` thing too.

Having reimplemented those three functions you might find they are now simple enough to pull up and inline into their single (each) callsites, it depends how it ends up looking after the first bit.

**Comment by RaviTezu** [comment]
Thank you for the info @ijc I will start on this.
