### ISSUE TITLE
Installing packages in Debian-based images with apt fails with "Invalid cross-device link"

### ISSUE THREAD

**Issue by bbc2** [moby/moby#38389]
**Description**

On Debian-based images, installing or upgrading causes an `Invalid cross-device link` error.

**Steps to reproduce the issue:**

```bash
docker run debian:stable bash -c 'apt update && apt install -y git'
```

**Describe the results you received:**

```
Fetched 24.1 MB in 0s (25.3 MB/s)
(Reading database ... 6498 files and directories currently installed.)
Preparing to unpack .../perl-base_5.24.1-3+deb9u5_amd64.deb ...
Unpacking perl-base (5.24.1-3+deb9u5) over (5.24.1-3+deb9u4) ...
dpkg: error processing archive /var/cache/apt/archives/perl-base_5.24.1-3+deb9u5_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/perl' before installing new version: Invalid cross-device link
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Invalid cross-device link
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

**Describe the results you expected:**

Successful installation.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue only appears on my Arch Linux installation, not on my Debian Testing. I guess it could be due to version or distribution parameter differences.

**Output of `docker version`:**

```
Client:
 Version:           18.09.0-ce
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        4d60db472b
 Built:             Fri Nov  9 00:05:34 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       4d60db472b
  Built:            Fri Nov  9 00:05:11 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 29
Server Version: 18.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: 079817cc26ec5292ac375bb9f47f373d33574949
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.8-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.43GiB
Name: ir
ID: 6KVN:LV25:SUBF:Y54Q:OCMK:JO2H:Y3Q3:JJYJ:LMWO:EATR:RWRJ:74JS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by Xorkle** [comment]
Hi @bbc2, try this:
```
 echo Y | sudo tee /sys/module/overlay/parameters/{redirect_always_follow,metacopy}
```

**Comment by cpuguy83** [comment]
metacopy needs to be turned off.

**Comment by bbc2** [comment]
Ah, very interesting!  So it indeed works if `metacopy` is `N`, regardless of the value for `redirect_always_follow`.

`redirect_always_follow` | `metacopy` | Result
--- | --- | ---
`N` | `N` | Success
`Y` | `N` | Success
`N` | `Y` | Failure
`Y` | `Y` | Failure

Is this expected or a bug with `metacopy`?  If it's expected, then I guess the distribution should change the default configuration of its Docker package because that's quite an issue.

**Comment by cpuguy83** [comment]
It is a kernel bug, there is a patch being worked on for it: https://www.spinics.net/lists/linux-unionfs/msg06316.html

We considered forcing metacopy to be off at mount time (as opposed to turning it off for the whole system), however decided to hold off while the patch is in progress since turning it back on would require making a patch release of Docker to do so (and likewise for turning it off)... and it's really something that users would want on anyway (assuming it actually works).
https://github.com/moby/moby/pull/38296

**Comment by cpuguy83** [comment]
I'm going to close this one because it is a dup of https://github.com/docker/for-linux/issues/480 and I'd prefer to keep discussion in one place.

Thanks!

**Comment by Xorkle** [comment]
Hi! (Sorry to respond to this closed issue, just wanted to add something regarding my earlier comment)

Sorry for possibly misleading everyone, somehow if I set both to Y, even if they're both Y already, the cross-device issue went away, very odd.

And yes, setting to N also fixes it!

:)
