### ISSUE TITLE
Broken download link in pre-release v17.03.1-ce-rc1

### ISSUE THREAD

**Issue by vanderson139** [moby/moby#38385]
All download links for this version are broken

Anyone can help me?

**Comment by olljanat** [comment]
@vanderson139 why you would like download that old pre-release version as many stable versions is released after that?

**Comment by olljanat** [comment]
Derek add label: kind/question

**Comment by thaJeztah** [comment]
I would _highly_ discourage using those old versions, versions older than 17.06 (including 17.03 and 17.05) have unpatched vulnerabilities (at least one critical that I know of)

I'll check if someone internally knows if the buckets attached to test.docker.com are still around, but not sure if they are.

Old `.deb` (http://apt.dockerproject.org/repo/pool/testing/d/docker-engine/) and `rpm` packages for pre releases can still be found in the `testing` channel at apt.dockerproject.org and yum.dockerproject.org;

- deb packages: http://apt.dockerproject.org/repo/pool/testing/d/docker-engine/
- yum packages (e.g. for CentOS 7); http://yum.dockerproject.org/repo/testing/centos/7/Packages/

But the same warning applies to those


I'll close this issue, as I'm not sure this is worth fixing, but I'll ask if it's possible. Feel free to continue the conversation though
