### ISSUE TITLE
Logging-in with an email address is supported but breaks CLI

### ISSUE THREAD

**Issue by GuyPaddock** [moby/moby#38394]
**Description**
On Docker for Windows, you can log-in with an email address in place of a username. The log-in will be accepted, but CLI tools like `docker-compose` will fail with `unauthorized: incorrect username or password` or `Stored credentials invalid or expired`.

**Steps to reproduce the issue:**
1. Install Docker for Windows.
2. Launch Docker for Windows.
3. On the log-in screen, instead of entering your Docker user ID, log-in with your email address in the username field.
4. Create a `docker-compose.yml` file that references an image on Docker Hub (e.g. `nginx`).
5. Run `docker-compose build` within the folder containing the `docker-compose.yml` file.

**Describe the results you received:**
- It is possible to log-in with an email address.
- Pulling images fails:
```
$ docker-compose build
app uses an image, skipping
Building web
Step 1/2 : FROM nginx:1
Service 'web' failed to build: Get https://registry-1.docker.io/v2/library/nginx/manifests/1: unauthorized: incorrect username or password
```

**Describe the results you expected:**
Either it is not possible (in step 3) to log-in with an email address in place of a Docker user ID; OR, doing so does not break the CLI.

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d890104
ID: JGWA:X3K6:OPSK:N4TQ:TFGV:R4CN:XOTV:TMWE:WUPM:6NE3:GJEU:K2CY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 46
 System Time: 2018-12-19T03:11:16.4047438Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by olljanat** [comment]
@GuyPaddock which version of Docker for Windows you are using? I just quickly tested and I was not able to either login with email address on username or create new user where email address would be username.

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by GuyPaddock** [comment]
@olljanat Just tried it again and am still able to log-in with my email address. Here's the "About" dialog: 
![image](https://user-images.githubusercontent.com/2631799/50489718-22531680-09d7-11e9-8886-2a976f565894.png)

**Comment by GuyPaddock** [comment]
Here's the proof:
![image](https://user-images.githubusercontent.com/2631799/50489740-562e3c00-09d7-11e9-9a23-879363226946.png)

**Comment by olljanat** [comment]
Derek remove label: status/more-info-needed

**Comment by olljanat** [comment]
@thaJeztah PTAL

**Comment by thaJeztah** [comment]
I think the Docker Desktop uses a different API to authenticate, not the registry authentication; see https://github.com/docker/cli/issues/961.

FWIW, I opened an internal ticket for that, to inform if there's an API that could be used by the CLI / daemon, but have not yet received information.

I suggest closing this one in favor of https://github.com/docker/cli/issues/961, so that the discussion doesn't diverse.

**Comment by thaJeztah** [comment]
closing in favor of https://github.com/docker/cli/issues/961
