### ISSUE TITLE
Buildkit adding remote file gives "invalid response status 400"

### ISSUE THREAD

**Issue by pwaller** [moby/moby#38396]
**Description**

(Using docker buildkit, cc @tonistiigi)

When running `DOCKER_BUILDKIT=1 docker build -t tmp .` with the following Dockerfile, I get `invalid response status 400`. I cannot reproduce this response status using curl.

**Steps to reproduce the issue:**
1. Use the following `Dockerfile` in an otherwise empty directory:

```dockerfile
FROM scratch
ADD https://github.com/aws/aws-fpga/archive/v1.4.5.tar.gz /tmp
```

2. Run `DOCKER_BUILDKIT=1 docker build -t tmp .`
3. Observe failure.

**Describe the results you received:**

```
#4 https://github.com/aws/aws-fpga/archive/v1.4.5.tar.gz
#4       digest: sha256:b45c4fefd636be0793a311d3219136defe759e5e37d0d544fc53f8768f7dbcdf
#4         name: "https://github.com/aws/aws-fpga/archive/v1.4.5.tar.gz"
#4      started: 2018-12-19 10:31:29.122483998 +0000 UTC
#4    completed: 2018-12-19 10:31:29.197220383 +0000 UTC
#4     duration: 74.736385ms
#4        error: "invalid response status 400"

invalid response status 400
```

**Describe the results you expected:**

A successfully built docker container with the given tar file downloaded to `/tmp`.

**Additional information you deem important (e.g. issue happens only occasionally):**

It ran a few times successfully, seemingly, but now always fails when I re-run.

`curl -OL https://github.com/aws/aws-fpga/archive/v1.4.5.tar.gz` succeeds, and downloads a 267M tar file.

My interpretation of the error is that docker is sending a bad HTTP request during the process of obtaining the file.

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 97
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-42-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.35GiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 [redacted]
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical host.

**Comment by tonistiigi** [comment]
Your example worked fine for me. I wonder if it could be related to https://github.com/moby/buildkit/issues/734

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
