### ISSUE TITLE
How to cross-compile ARM-based docker binary on X86 platforms?

### ISSUE THREAD

**Issue by xingzhao-tt** [moby/moby#38390]
We wanna run docker on ARM machine, so is there method to cross-compile ARM-based docker binary on X86 platform?

Thanks,
Felix

**Comment by olljanat** [comment]
Sure it is. Example https://github.com/rancher/os is also available for Raspberry Pi and it contains ARM64 version of docker.

And from https://github.com/rancher/install-docker/blob/master/18.06.1.sh you can see where they download pre-build version docker.

Afaik actual cross compile works on Go lang if you just define GOOS and GOARCH parameters before build.

**Comment by xingzhao-tt** [comment]
@olljanat Thanks your reply. I tried "make binary GOOS=linux  GOARCH=arm GOARM=7" under docker source code folder to compile ARM-based docker binaries, but the compile output is still X86-based.

root@ubuntu:~/docker/docker# file  bundles/binary-daemon/containerd
bundles/binary-daemon/containerd: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=174e63b8e0fdd58422af30a7001725821f3fa1ca, stripped

**Comment by olljanat** [comment]
Which device you are planning to use run Docker? Do you need some special build or can you just use use those pre-build versions?

I'm not fully aware of build process but I can see that ARM is not at least part of CI builds.

Derek add label: kind/question

**Comment by olljanat** [comment]
Derek add label: kind/question

**Comment by xingzhao-tt** [comment]
@olljanat We are planning run docker on Android system. It is predictable that we need to compile docker binary during development. I remember docker source code had one Dockerfile named Dockerfile.armhf, but the latest source code have no this file any more. I want to know how the prebuilt binaries were compiled .

Thanks,
Felix

**Comment by olljanat** [comment]
Looks that you can use environment variables:
- DOCKER_ENGINE_OSARCH
- DOCKER_ENGINE_GOOS
- DOCKER_ENGINE_GOARCH

https://github.com/moby/moby/blob/8eb7ed673b687ae17e2c7df5dd40f8081c299bc2/hack/make/.detect-daemon-osarch#L26-L28

Try set them and see if that affects build?

**Comment by olljanat** [comment]
@xingzhao-tt did you got build working? I also noticed that there is some info on https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/project/ARM.md

**Comment by thaJeztah** [comment]
I haven't tried myself, but I know that cross-compiling has not always been a solid solution to compile the engine.

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by thaJeztah** [comment]
@cpuguy83 recently provided some patches to improve cross-compiling; 

- https://github.com/moby/moby/pull/39010 Support cross-compile for arm
- https://github.com/moby/moby/pull/39090 Add support for setting GOARM in cross target
- https://github.com/moby/moby/pull/39091 Make CC toolchains available for other targets

**Comment by thaJeztah** [comment]
Closing as this went stale
