### ISSUE TITLE
How to get the exec command logs after run the command ?

### ISSUE THREAD

**Issue by frankLife** [moby/moby#38434]
I start a service by `docker exec` command through docker remote api by a server on host. But I want the log of the command that was executed after the `docker exec` command because the server would restart in future.

I find we can use [docker exec inspect remote api](https://docs.docker.com/engine/api/v1.37/#operation/ExecInspect) but there is no log related object in the response result.

Besides the hack that command `|` redirect log to file , do we have any better methods to get the log ?

**Comment by olljanat** [comment]
Derek add label: kind/question

**Comment by olljanat** [comment]
@frankLife can you tell bit more about use case? Why that process would be started with docker exec instead of on docker run command?

docker exec should be considered to be available for debug purposes only and the main process which is supposed to be started with docker run command (or specified on Dockerfile)

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by frankLife** [comment]
Some service which can stop or start at any time in the same container environment. So I need to control at any time  by `docker exec `.  But `docker run` maybe can't do this .

**Comment by olljanat** [comment]
It really sounds that you should look https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/

Especially: 
> 7) Don’t run more than one process in a single container

Idea is that when process stops container will stop too and if you are usimgs [Swarm](https://docs.docker.com/engine/swarm/) it will even remove that container and create new one which replaces it.

**Comment by frankLife** [comment]
Yes, I would just some container management tool about this and I need to control  a service in the container at any time.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
