### ISSUE TITLE
How about Cocker ? A container engine writen by C language from China :)

### ISSUE THREAD

**Issue by calvinwilliams** [moby/moby#38433]
https://github.com/calvinwilliams/cocker

**Comment by thaJeztah** [comment]
Not sure what you're asking; could you explain?

**Comment by olljanat** [comment]
@calvinwilliams cocker looks to be one guy project which is start just couple of months ago and it have no anything to do with Moby .

I will close this issue now but feel free to comment if it is someone related which I missed.

**Comment by olljanat** [comment]
Derek close
