### ISSUE TITLE
Moby 3.0.2 fails in starting Azure IoT Edge runtime

### ISSUE THREAD

**Issue by tedchina** [moby/moby#38461]
**Description**

**Steps to reproduce the issue:**
1. On a physical machine with Amd64 and Ubuntu 18.04, uninstall the previously installed `docker-ce`.
2. Install Moby and Azure-IoT-Edge according to the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux
2. After install/config/restart `iotedge`, `edgeAgent` is found unable to be started because of failure in dialing `dial unix:///run/containerd/containerd.sock`.
3. Uninstall `moby-engine` and `moby-cli`, and then reinstall `docker-ce` and `docker-ce-cli`. Then the `iotedge` installed/configured in the preceding step can now be successfully started.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
sudo apt show docker-ce
Package: docker-ce
Version: 5:18.09.0~3-0~ubuntu-bionic

sudo apt show moby-engine
Package: moby-engine
Version: 3.0.2
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by olljanat** [comment]
@tedchina those moby packages are build by Microsoft and they are not shared their build process with us.
Plz check issue reporting guide on https://github.com/Azure/azure-iotedge

**Comment by tedchina** [comment]
I see, thanks...
