### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#38471]
/ # ls
bin              dev              home             media            proc             run              srv              tmp              var
check_readiness  etc              lib              mnt              root             sbin             sys              usr
/ # 
file exist, but exec error

/ # ./check_readiness 
sh: ./check_readiness: not found
/ #

**Comment by olljanat** [comment]
@timchenxiaoyu plz use issue template provide all asked information.

**Comment by AkihiroSuda** [comment]
This is likely to because shared library files are missing.
