### ISSUE TITLE
Images are removed from database even if cannot be delete from disk

### ISSUE THREAD

**Issue by olljanat** [moby/moby#38488]
**Description**
I did troubleshooting for docker/for-win#745 issue and find out that it actually happens on Linux too if layers are protected on way that root cannot remove them

**Steps to reproduce the issue:**
1. Check that we have one image on disk:
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              3f53bb00af94        13 days ago         4.41MB
```
2. Check that we can see only it on overlay2 folder:
```
# ls -l /var/lib/docker/overlay2/
total 44
drwx------ 3 root root  4096 Jan  4 00:06 a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3
```
3. Mark folder as immutable:
```
chattr +i /var/lib/docker/overlay2/a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3/
```
4. Try remove image:
```
# docker rmi alpine
Error response from daemon: remove /var/lib/docker/overlay2/a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3/diff: operation not permitted
```
**Describe the results you received:**
Image is removed from database but still exists on disk:
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

# ls -l /var/lib/docker/overlay2/
total 44
drwx------ 3 root root  4096 Jan  4 00:06 a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3
```

**Describe the results you expected:**
Images should be either only removed from database when they are successfully removed from disk or they should be marked as waiting for removal and removed when *imageService.Cleanup()* is called.

**Additional information you deem important (e.g. issue happens only occasionally):**
Related to #38401

Error message found from event log on combination of Windows Server 2016 + Docker 18.09:
```
Handler for DELETE /v1.39/images/5d4d99af0cf4 returned error: GetComputeSystems: The requested compute system operation is not valid in the current state.
```
if those 500 retries is not enough this is what happens on:
https://github.com/moby/moby/blob/ea60a87fcfc8b4592a5d2dec60f021c44ebe6a05/daemon/graphdriver/windows/windows.go#L295-L309

**Comment by olljanat** [comment]
@cpuguy83 PTAL

**Comment by olljanat** [comment]
It looks to be that when this happens image is removed from imageDB but left to layerDB. I added Linux support to docker-leak-check tool on PR  jhowardmsft/docker-leak-check#1 (which also contains binary verrsion) which can be used to debug this.

This is result from it after steps done above:
```
./docker-leak-check
Error: Unreferenced layer in layerDB:  7bff100f35cb359a368537bb07829b055fe8e0b1cb01085a3a628ae9c187c7b8
Error: Unreferenced layer in overlay2:  a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3
```

**Comment by olljanat** [comment]
Derek add label: kind/bug

**Comment by cpuguy83** [comment]
We could add a go thread for layers...

I'm not too keen on making drastic changes to this part of the codebase just because of the containerd migration.

Ping @dmcgowan

**Comment by dmcgowan** [comment]
In containerd we implemented atomicity on delete and a garbage collector which is responsible for reclaiming unreferenced disk usage. Implementing this feature in Docker would non-trivial because of the way data is stored and lack of enumeration functions (I don't think `Cleanup` is enough to implement this correctly as it also requires deletion book-keeping in a non-atomic way).

**Comment by olljanat** [comment]
@cpuguy83 @dmcgowan so that basically means that #38043 need to be implemented before this can be fixed?

Btw. I supposed that this can be tricky to fix so I implemented workaround https://github.com/docker/for-win/issues/745#issuecomment-451441632 which looks to be quite secure to use. Maybe I then will do bit more testing with that and start schedule it run nightly.

**Comment by cpuguy83** [comment]
A/go thread/gc thread/
Thanks autocorrect.

**Comment by olljanat** [comment]
@cpuguy83 @dmcgowan I created simple garbage collector for image layers on #39193 and I tried to do it on way that needs minimal changes to existing logic. PTAL

**Comment by olljanat** [comment]
Some more details. I found running Windows container from production environment which was missing some files/file content. Here is how I was able to reproduce it on Windows Server 2019:

Using docker file like this, build it and push to docker registry:
```
FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator
RUN echo @echo off > /migrate.cmd && \
    echo echo Migrating database >> /migrate.cmd
RUN echo @echo off > /start.cmd && \
    echo start /b migrate.cmd >> /start.cmd && \
    echo echo Starting application >> /start.cmd
ENTRYPOINT ["/start.cmd"]
```

Then normal output of this looks like this:
```
docker run --rm ollijanatuinen/broken-layer-debug
Starting application
Migrating database
```

But if I lock all **migrate.cmd** files with PowerShell, remove old image:
```
$Files = Get-ChildItem -Path C:\ProgramData\docker\windowsfilter -Include migrate.cmd -Recurse
$i = 1
ForEach($File in $Files) {
    $LockName = "lock$i"
    $lock = [System.IO.File]::Open($File.FullName, "Open", "Read", "None")
    Set-Variable -Name $LockName -Value $lock
    $i++
}

docker rmi ollijanatuinen/broken-layer-debug
```
and then start new container:
```
docker run --rm ollijanatuinen/broken-layer-debug
The system cannot find the file migrate.cmd.
Starting application
```
it actually starts but misses **migrate.cmd** script.
