### ISSUE TITLE
Windows Server 2019 known issues

### ISSUE THREAD

**Issue by olljanat** [moby/moby#38498]
| Status      | Moby issue | Microsoft issue | Description                        |
| ----------- | ---------- | --------------- | ---------------------------------- |
| ~~Fixed privately (Waiting for Windows update)~~| #38114     | VSO#19599026. Should be available in 3B Windows update    | Files gets locked and cannot be removed without reboot. Will be fixed publicly in a future Windows Update. A private fix has been deployed to the RS5 CI servers. |
| ~~Workaround available for part 1 pending Windows update. Fix available in EE 18.09.03 for part 2.~~ | #38358     | Needs splitting into two issues. One has a workaround documented at https://github.com/moby/moby/issues/38358#issuecomment-466296997 with a Windows update pending, and the other is fixed in EE 18.09.03               | Default NAT network gateway is missing after startup |
| ~~Fixed (Waiting for Windows update)~~ | #38484     | Fix due in Windows Update 3B (March 2019 Patch Tuesday)              | Hybrid Swarm cluster breaks routing mesh traffic to Linux services |
| RS1 issue. Awaiting a repro to demonstrate is an actual RS5/Windows Server 2019 issue.| #30950     | 119010419510056 | RS1. Starting containers fails to error *Insufficient system resources exist to complete the requested service*
| In progress | #37709    | 20310680               | Wrong source ip in udp packets when port mapping like 8080:808 |

**Comment by olljanat** [comment]
Derek add label: version/18.09

**Comment by olljanat** [comment]
@jhowardmsft I see that you have added
> Believe fixed in RS5

comment to #30950 . Unfortunately I cannot believe that as I'm just uploading copy of broken Win 2019 + Docker 18.09.1 VM to as issue attachment 😕

**Comment by pbering** [comment]
FYI #38484 is fixed but now yet release, please update status.

**Comment by jhowardmsft** [comment]
> @jhowardmsft I see that you have added
> 
> Believe fixed in RS5
> 
> comment to #30950 . Unfortunately I cannot believe that as I'm just uploading copy of broken Win 2019 + Docker 18.09.1 VM to as issue attachment 😕

Where was that upload? I never saw it. Is there a CSS support case#? Does it still repro on latest RS5 patches and moby master?

**Comment by jhowardmsft** [comment]
Closing this issue. There's no point having an issue open which is just rolling-up what are now remains just two other already open issues. If we had issues like this open for all of moby, we would just be re-inventing the wheel given there are (as of now) some 3,433 open issues.
