### ISSUE TITLE
golang checksum mismatch

### ISSUE THREAD

**Issue by coolaj86** [moby/moby#38507]
Some package that I'm building has an indirect dependency on github.com/docker/docker which as of today no longer builds due to a checksum mismatch.

```
go: verifying github.com/docker/docker@v0.7.3-0.20180221142240-453f2b8b40b9: checksum mismatch
	downloaded: h1:j5P9Aya3JMe0sv7rAfRWIohQVP3YxHgui125drv1DAM=
	go.sum:     h1:T9/p6Tf8lgB+fBZRwUCn1/b0w8w2/xT2Lsi6SPVp7OU=
```

Is the rename from `github.com/docker/docker` to `github.com/moby/moby` recent?

It built Dec 20th, 2018 and it built last week. Today is the first day I'm seeing this error.

### Solution

1. Use **go1.11.4** (fixes an issue with cross-platform hashing of symlinks)
2. Also see https://github.com/moby/moby/issues/38507#issuecomment-456158913

**Comment by coolaj86** [comment]
Hmmm... it may be due to differences between go1.11.4 and go1.11.3 in handling symlinks within a repository.

https://github.com/golang/go/issues/29278

**Comment by cpuguy83** [comment]
No, the rename is not recent.
The packages should still be referenced as `github.com/docker/docker`, but you should probably fetch it from the `github.com/docker/engine` repo where Docker releases are tagged.

**Comment by SvenDowideit** [comment]
this is happening with https://github.com/nektos/act when using `go mod` ...

```
go: downloading golang.org/x/net v0.0.0-20181220203305-927f97764cc3
go: verifying github.com/docker/engine@v0.0.0-20181106193140-f5749085e9cb: checksum mismatch
	downloaded: h1:kbG92WIjuzlj1RaoaKkrdGZPR5cen5hNkr51WwhzrKU=
	go.sum:     h1:PyjxRdW1mqCmSoxy/6uP01P7CGbsD+woX+oOWbaUPwQ=
```

**Comment by SvenDowideit** [comment]
@thaJeztah this is related to the Sirupsen/logrus issue I had - without the `replace` line, things seem to get ugly.

**Comment by coolaj86** [comment]
@thaJeztah There are two things that you'd need to do to support go modules with your current versioning scheme:

1. Add a patch version: v17.xx.yy
2. Change the go.mod file (and imports) to be `github.com/moby/moby/17`

(and it doesn't _assume_, it _requires_ semver)

To install a non-semver version with `go get` you need only append the hash:

```
go get github.com/moby/moby@5ec3138 
```

However, from what I'm hearing it sounds like the repository that people should be tracking is not this one but rather `github.com/docker/engine`?

**Comment by thaJeztah** [comment]
> and it doesn't assume semver, it requires it

Correct, I understand go mod requires SemVer if you want to use a repository as dependency, but it assumes that if a repository has tags, that those tags are SemVer.

The point here is that if a repository has tags, but those tags were created for other reasons than for other Go projects to vendor the code / use it as dependency, that there's a "conflict of interest"

> However, from what I'm hearing it sounds like the repository that people should be tracking is not this one but rather github.com/docker/engine?

The docker/engine  repository can be used if you want your dependency to match the version that was used by a Docker release (which could make sense if you want to use the API client), however, if you want to use one of the other packages in this repo (and want the latest version from master of those), it could make sense to use this repository

**Comment by thaJeztah** [comment]
> - Add a patch version: v17.xx.yy
> - Change the go.mod file (and imports) to be github.com/moby/moby/17

I don't think that would be an option, as that would mean tagging a patch release for a two year old release; which is likely not what you want to use as a dependency

**Comment by SvenDowideit** [comment]
@thaJeztah na, IMO the thing Docker needs to do, is to write very clear and very well tested documentation for how they want us to consume the go code. @cpuguy83 has said in a few places something that read to me as "you only need to `import "docker/engine"` and everything will just work - which hasn't been my experience for anything that is more than trivial.

iirc, I tried to use `import moby/moby`, but I had some issues using that to talk to a Docker Daemon - hopefully that was something I did wrong, and also "just needs docs and tests".

In the process of writing the automated tests for the code integration and reuse docs, I'm pretty sure would make adding a `v17.xx.yy` tag, and for all subsequent releases an obvious "must do" - there is code out there that assumes v17 functionality/bugs.... 

as much as i dislike SemVer, its pretty obviously a standard that Docker's release and tag should be capable of working with.

**Comment by shenshouer** [comment]
```
$ go mod vendor
verifying github.com/docker/docker@v1.13.1: checksum mismatch
        downloaded: h1:5VBhsO6ckUxB0A8CE5LlUJdXzik9cbEbBTQ/ggeml7M=
        sum.golang.org: h1:IkZjBSIc8hBjLpqeAbeE5mca5mNgeatLHBy3GO78BWo=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

$ go version
go version go1.13 darwin/amd64

```

**Comment by thaJeztah** [comment]
closing in favour of https://github.com/moby/moby/issues/39302
