### ISSUE TITLE
regression: When using Docker 18.09 on CentOS 7 and the devicemapper

### ISSUE THREAD

**Issue by jcberthon** [moby/moby#38506]
**Description**

We have a machine running CentOS 7 (1804) with Docker CE 18.06.1. That machines runs many containers successfully. It is configured with the devicemapper storage backend (not th loopback variant). It is running perfectly fine.

When we upgrade to Docker CE 18.09, the upgrade is smooth and after the upgrade everything runs apparently. But if we reboot the machine, then Dockerd is unable to start any containers. In the logs we can see messages like:

    layer does not exist, not restoring image sha256:27f4c685fac8e0e1345f2fcc45d8dbddeb4e04b016ecab2156ec90d5ff98332d, sha256:392b6b007ef3df3c5d480d2537e16492a63c9c1009142f76b5d33774fcaa14a3, linux

In addition, spawning a container fails with message like "unable to execute bash" when doing `docker run --rm -it ubuntu:latest bash` (it fails with similar messages for centos:7 and alpine:latest images as well). Even building a simple image failed (it is able to pull and image but then the first `RUN ` argument fails with `OCI runtime create failed: rootfs (/var/lib/docker/devicemapper/mnt/f5ddfa8ada57b92d5ed386ef636e013307494704f6c627a5f719977e74ac034d/rootfs) does not exist: unknown`.

One worrying message in the log just after boot is:

    dockerd: time="2018-12-18T23:28:44.990059438Z" level=warning msg="Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored." storage-driver=devicemapper

Before, why devicemapper and why not overlay2 backend? Well historical reasons :-) when we setup that machine some 1,5 years ago, the devicemapper was the recommended storage. We are aware of the deprecation of the devicemapper backend and will make in due course a migration to overlay2. But today, I was expecting that nothing would break by upgrading to Docker CE 18.09.

**Steps to reproduce the issue:**
1. Setup a CentOS 7 machine with Docker CE 18.06.1 and using the devicemapper as storage backend
2. Verify that you can build or spawn containers
3. Upgrade to Docker CE 18.09
4. Reboot
5. You should have now a broken system: cannot build or spawn containers

**Describe the results you received:**

Builds are failing when trying to perform a `RUN ...` instruction.

Spawning of containers (even existing or new ones) are failing for abscons reasons.

**Describe the results you expected:**

Building and spawning should work as usual.

**Additional information you deem important (e.g. issue happens only occasionally):**

The week before, we had upgrade CentOS 7 from 1804 (kernel 3.10.0-862.14.4.el7.x86_64) to 1810 (kernel 3.10.0-957.1.3.el7). So we rebooted the machine on the older kernel, but that did not help. In order to rule out the CentOS upgrade, we also created a VM with CentOS 7 1804 and simply did the upgrade to Docker CE 18.09 and we encountered the problem. So IMHO, this is a regression in Docker CE 18.09.

**Output of `docker version`:**

Working version:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

Broken version:
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

Working version:
```
Containers: 28
 Running: 26
 Paused: 0
 Stopped: 2
Images: 460
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: vg_spc-thpl_docker
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 146.3GB
 Data Space Total: 2.302TB
 Data Space Available: 2.155TB
 Metadata Space Used: 39.7MB
 Metadata Space Total: 16.98GB
 Metadata Space Available: 16.94GB
 Thin Pool Minimum Free Space: 230.2GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.8GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Sadly, I have no longer a `docker info` of the corresponding broken system, because we quickly downgraded back to 18.06.1 and restored from backup. But here is the docker info from my test VM (which I configured using the **devicemapper loopback to do quick testing**)

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.0
Storage Driver: devicemapper
 Pool Name: docker-253:2-104-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 161.5MB
 Data Space Total: 107.4GB
 Data Space Available: 10.1GB
 Metadata Space Used: 802.8kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701GiB
Name: localhost.localdomain
ID: RULC:YS6X:2D2T:IOPG:4MJO:3W5O:S7QV:7IPO:2TOP:27Y4:YRPR:DTTY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The host on which we spotted first the problem is a physical Dell server running CentOS 7 64bit 1804, no virtualisation layer used. Docker CE 18.06.1 using the devicemapper is working robustly on this host.

The testing host on which I was able to reproduce the error is a VM on my laptop which runs Win10 + VirtualBox. I have setup CentOS 7 64bit 1804 in it. I was able to reproduce the error by upgrading from Docker CE 18.06.1 to 18.09.

**Comment by jcberthon** [comment]
I've been trying to reproduce the issue on a different distribution. On Ubuntu 18.04 I have a different problem:

1. Install Ubuntu 18.04
2. Install Docker CE 18.06.1
3. Configure devicemapper as backend
4. Test it: it works as expected
5. Upgrade to Docker CE 18.09

Result: Docker cannot be restarted, because it does not find the `devicemapper` backend plugin, even after enabling experimental features:

    level=error msg="Failed to GetDriver graph" driver=devicemapper error="Error looking up graphdriver plugin devicemapper: plugin \"devicemapper\" not found"

Expected result: it is still working or as broken as on CentOS 7

**Comment by jcberthon** [comment]
However, testing it with Fedora 28 and Docker CE 18.06.1 and devicemapper (loopback for quick testing), the upgrade to 18.09 went smoothly. Everything works. The kernel version on Fedora was: 4.19.13-200.fc28.x86_64

**Comment by thaJeztah** [comment]
The Ubuntu issue is unrelated to what you're seeing on CentOS, but wondering; do you have any modifications made in the systemd unit file (or using an override file) to change the `MountFlags` options? (e.g. `MountFlags=slave`)

What does `systemctl cat docker.service` show?

**Comment by jcberthon** [comment]
Hi @thaJeztah 

Yes, I had setup an override because of instabilities on CentOS when using Docker and the devicemapper.

Here it is:

```
cat /etc/systemd/system/docker.service.d/override.conf 
[Service]
MountFlags=slave
```

I can check, but I think I also did that override on my test VM many months (a year?) ago.

Is that the cause of my troubles?

**Comment by thaJeztah** [comment]
Yes; that's very likely the cause. In Docker 18.09, containerd is started as a separate service (no longer as a child process of `dockerd`), and as such it gets its own mount-namespace. Setting `MountFlags=slave` will cause problems because of that.

If you remove that override, `systemctl reload docker.service`, and `systemctl restart docker.service`, I think those problems should disappear.

For new installations, I would also recommend giving the `overlay2` storage driver a try; a lot of fixes have gone into current versions of the RHEL / CentOS kernels to improve overlayfs support (and it's therefore now used by default by docker).

**Comment by jcberthon** [comment]
This indeed resolved the issue on my testing machine.

Should we document it somewhere? And if yes where? (note that I could take the time to document it).

**Comment by MiniPlayer** [comment]
That saved us. Thank you ! Indeed a note about it in documentation would be nice. 
In our case we did not even knew that this configuration was overriden ! (Was done previously by other people)

**Comment by thaJeztah** [comment]
I opened a pull-request to add a note to the release notes / changelog: https://github.com/docker/docker.github.io/pull/8001

**Comment by jcberthon** [comment]
Thank you very much @thaJeztah for the updated changelog!

**Comment by Cactusinhand** [comment]
> Yes; that's very likely the cause. In Docker 18.09, containerd is started as a separate service (no longer as a child process of `dockerd`), and as such it gets its own mount-namespace. Setting `MountFlags=slave` will cause problems because of that.
> 
> If you remove that override, `systemctl reload docker.service`, and `systemctl restart docker.service`, I think those problems should disappear.
> 
> For new installations, I would also recommend giving the `overlay2` storage driver a try; a lot of fixes have gone into current versions of the RHEL / CentOS kernels to improve overlayfs support (and it's therefore now used by default by docker).

@thaJeztah Hi, 
To fix the error: `device or resource busy`,
I followed the comment: https://github.com/moby/moby/issues/34198#issuecomment-316647006, and added `MountFlags=slave`,

but now I encounter the error: 
```shell
node10 dockerd[339184]: time="xxx" level=error msg="stream copy error: reading from a closed fifo"
node10 dockerd[339184]: time="xxx" level=error msg="stream copy error: reading from a closed fifo"
node10 dockerd[339184]: time="xxx" level=error msg="72e3ab7f83fdd6133bb75ebdf16f585d46352a3296d5c62e956997551bf9d291 cleanup: failed to delete container from containerd: no such container"
node10 dockerd[339184]: time="xxx" level=error msg="Handler for POST /v1.30/containers/72e3ab7f83fdd6133bb75ebdf16f585d46352a3296d5c62e956997551bf9d291/start returned error: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:301: running exec setns process for init caused \\\"exit status 22\\\"\": unknown"
~
```
and saw this comment, I don't know whether to keep `MountFlags` or not.


- my docker info is:
```shell
[root@node10 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.0
  GitCommit:        c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc:
  Version:          1.0.0-rc5
  GitCommit:        4fc53a81fb7c994640722ac585fa9ca548971871
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- and my kernel:
```shel
[root@node10 ~]# uname -r
4.18.0-193.el8.x86_64
```
- docker deamon:
```json
{
    "iptables": false,
    "selinux-enabled": false,
    "storage-driver": "vfs"
}
```
