### ISSUE TITLE
sysctl tcp_tw_reuse failed on ubuntu14.04 kernel 4.2.0

### ISSUE THREAD

**Issue by jimmycmh** [moby/moby#38519]
sysctl tcp_tw_reuse failed on ubuntu14.04 kernel 4.2.0 when creating a container

**Steps to reproduce the issue:**
1. docker run --sysctl net.ipv4.tcp_tw_reuse=1  ubuntu

**Describe the results you received:**
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/ipv4/tcp_tw_reuse: no such file or directory\"": unknown.
ERRO[0001] error waiting for container: context canceled

**Describe the results you expected:**
on ubuntu14.04 kernel 4.15 and ubuntu16.04 kernel 4.15, it works fine

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:18:46 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:16:59 2018
  OS/Arch:      linux/amd64
  Experimental: false```

**Output of `docker info`:**

```
Containers: 39
 Running: 30
 Paused: 0
 Stopped: 9
Images: 14
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.5GiB
Name: WXEC0039
ID: EYAC:O3CB:P63R:DZVG:53VC:W4JQ:Z6OQ:2QLL:MIEX:H72F:S5QG:KYB2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
