### ISSUE TITLE
`docker info` should print the default builder 

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#38518]
**Description**

`docker info` should print the default builder  (legacy or buildkit)

**Steps to reproduce the issue:**
1. `docker info`

**Describe the results you received:**
```
Default builder: BuildKit
```

**Describe the results you expected:**

No such info in `Docker info`

**Comment by c0deWookiee** [comment]
hey, can i pick this up?

**Comment by kwojcicki** [comment]
Hey @AkihiroSuda I was looking to work on this, any pointers as to what files I should look at first 😄

**Comment by AkihiroSuda** [comment]
@kwojcicki Thanks

`docker info` is implemented in https://github.com/moby/moby/blob/8af91768c78c8655d8cbbc817ab4d6f4a6a62ae4/api/server/router/system/system_routes.go#L38

Builder version is here: https://github.com/moby/moby/blob/8af91768c78c8655d8cbbc817ab4d6f4a6a62ae4/api/server/router/system/system_routes.go#L30

**Comment by kwojcicki** [comment]
Thank you @AkihiroSuda will make a PR in the upcoming days ^_^

**Comment by kwojcicki** [comment]
Hey @AkihiroSuda I modified the structure that getInfo returns, https://github.com/moby/moby/blob/8af91768c78c8655d8cbbc817ab4d6f4a6a62ae4/api/types/types.go#L147, and am beginning to test my changes. I assume that I will need to rebuild the CLI with the new struct?

**Comment by AkihiroSuda** [comment]
No, API test is preferred over CLI test now. Please refer to `integration` dir

**Comment by kwojcicki** [comment]
Hey @AkihiroSuda  opened up a PR, one of the checks seemed to have failed but I dont believe it is due to my change.
