### ISSUE TITLE
docker-ce-18.09.1 cannot start on CentOS 7

### ISSUE THREAD

**Issue by lazurey** [moby/moby#38528]
**Description**
Docker version: 18.09.1
AWS EC2, CentOS 7

Since this morning, 10 Jan, docker failed to start after a fresh install on a fresh EC2 instance.
After remove the `18.09.1` version and install `18.09.0`, it's running all good.

**Steps to reproduce the issue:**
1. Start an EC2 instance with CentOS 7
2. `yum install docker-ce`
3. `docker` is installed, but not running. `/var/run/docker.sock` is not created

**Describe the results you received:**
Debug info:
```
[centos@ip-172-00-00-11 run]$ sudo systemctl status docker
● docker.service - Docker Daemon
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2019-01-10 12:51:54 CST; 20s ago
  Process: 26184 ExecStart=/usr/bin/dockerd -p /var/run/docker.pid -s overlay --insecure-registry (code=exited, status=1/FAILURE)
 Main PID: 26184 (code=exited, status=1/FAILURE)

Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: Unit docker.service entered failed state.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: docker.service failed.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: docker.service holdoff time over, scheduling restart.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: Stopped Docker Daemon.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: start request repeated too quickly for docker.service
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: Failed to start Docker Daemon.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: Unit docker.service entered failed state.
Jan 10 12:51:54 ip-172-00-00-11.xx-north-1.compute.internal systemd[1]: docker.service failed.
```

**Describe the results you expected:**
Need more instructions to find out why it's happening.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 18.09.1, build 4c52b90
```

**Output of `docker info`:**
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, EC2, CentOS 7.

**Comment by Bevisy** [comment]
make sure the firewalld was stopped and remove all files in "var/lib/docker",then restart docker

**Comment by lazurey** [comment]
@Bevisy I'll have a try and close this ticket first. Thank you.
