### ISSUE TITLE
'Nvveen/Gotty' import casing statement

### ISSUE THREAD

**Issue by mickael-carl** [moby/moby#38550]
**Description**

The import statement in pkg/jsonmessage/jsonmessage.go has some mixed casing (more or less the same issue as #33641). When using Bazel/Gazelle and including this as a dependancy, this can result in the following errors:

> GoCompile: missing strict dependencies:
>         /home/foo/.cache/bazel/_bazel_foo/c42f0cbd326bce63fb67245d6d8e7267/sandbox/processwrapper-sandbox/9/execroot/__main__/external/com_github_docker_docker/pkg/jsonmessage/jsonmessage.go: import of "github.com/Nvveen/Gotty"
> Known dependencies are:
>         github.com/docker/docker/pkg/term
>         github.com/docker/go-units
>         github.com/nvveen/gotty

**Additional information you deem important (e.g. issue happens only occasionally):**

I wonder how important this is considering that there is also a PR open to replace this specific library with another one (see #38398).

**Comment by cpuguy83** [comment]
Sounds like a bug in Bazel. Did this issue get reported there?

**Comment by thaJeztah** [comment]
We removed this dependency in https://github.com/moby/moby/pull/38398, so this should no longer be a problem 🤗
