### ISSUE TITLE
[Optimization] Whether docker image layer can replace gzip algorithm with lz4?

### ISSUE THREAD

**Issue by firjest** [moby/moby#38562]
**Description**

In my tests, the lz4 algorithm has better compression and decompression performance.

```
2.8G file
[root@abc /home/yifang.jy/1]
#time lz4 -d 2.tar.1.lz4 >/dev/null
Successfully decoded 1073741824 bytes

real	0m1.055s
user	0m0.951s
sys	0m0.103s

[root@abc /home/yifang.jy/1]
#time gunzip 4.tar.gz

real	0m28.816s
user	0m25.522s
sys	0m3.295s
```

When the new image is deployed to the server, you need to prepare the image download faster.
After testing, a large part time of the docker pull is consumed in gzip decompression.

[Squash Compression Benchmark](https://quixdb.github.io/squash-benchmark/)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
A new compression would have to be accepted by the OCI image specification; 
https://github.com/opencontainers/image-spec/blob/master/media-types.md

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
