### ISSUE TITLE
[Optimization] Whether docker pull can replace sha256 algorithm with md5？

### ISSUE THREAD

**Issue by firjest** [moby/moby#38563]
**Description**

The main reason is that md5 has better performance than sha256.
I understand that the docker push must use the sha256 algorithm in order to ensure that the layers do not conflict.
But with docker pull, the md5 algorithm is fully competent for data check.

In my testing:

```
2.8G file
[root@abc /home/yifang.jy/1]
#time sha256sum 1.tar
ec93b3153b45eeb6fe93fd1c8d5267c4a80a322da9bd7166dc819530a6ab871f  1.tar

real	0m15.185s
user	0m14.637s
sys	0m0.537s

[root@abc /home/yifang.jy/1]
#time md5sum 1.tar
fa366a3b89797d4850067ec453bd997a  1.tar

real	0m6.746s
user	0m6.234s
sys	0m0.507s
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Also something for the OCI specs 
https://github.com/opencontainers/image-spec/blob/master/manifest.md (and distribution spec 
https://github.com/opencontainers/distribution-spec/blob/master/spec.md#content-digests)


I don't think md5 would be suitable though, as there's a high risk of collisions 


I'll close the issue here, because this requires the specification to be changed, but feel free to comment after I closed

**Comment by firjest** [comment]
> Also something for the OCI specs
> https://github.com/opencontainers/image-spec/blob/master/manifest.md (and distribution spec
> https://github.com/opencontainers/distribution-spec/blob/master/spec.md#content-digests)
> 
> I don't think md5 would be suitable though, as there's a high risk of collisions
> 
 yes, there's a high risk of collisions, But the purpose of docker pull is to verify that the data is correct, not a conflict check.

As I said, when docker push, we use sha256 to avoid conflicts. At the same time, we save md5 in manifest. At docker pull, sha256 is used to assemble the download link, and md5 is used to check whether the data is correct only, whether the conflict is actually not important

@thaJeztah
