### ISSUE TITLE
Flaky test: TestClientWithRequestTimeout

### ISSUE THREAD

**Issue by elboulangero** [moby/moby#38587]
```
=== RUN   TestClientWithRequestTimeout
--- FAIL: TestClientWithRequestTimeout (0.00s)
    client_test.go:259: assertion failed: 
        --- context.DeadlineExceeded
        +++ err
        :
        	-: context.deadlineExceededError{}
        	+: &net.OpError{Op: "dial", Net: "tcp", Addr: s"127.0.0.1:37597", Err: &poll.TimeoutError{}}
...
FAIL
FAIL	github.com/docker/docker/pkg/plugins	33.678s
```
(source: https://salsa.debian.org/docker-team/docker/-/jobs/108963/raw)

Looking for this in your bugtracker, I noticed that you've add this issue as well on your build machines:
https://github.com/moby/moby/pull/38459#issuecomment-450646644

Is the test simply a bit flaky, or something else is going on?

**Comment by elboulangero** [comment]
Just updated the snippet above with the path `github.com/docker/docker/pkg/plugins`

**Comment by onlyjob** [comment]
Our pipelines in this project are not public and they are available to authenticated users only... However @elboulangero quoted the relevant part of the build log.

**Comment by thaJeztah** [comment]
The first issue should be addressed by https://github.com/moby/moby/pull/39168. Second issue https://github.com/moby/moby/issues/38587#issuecomment-456347737 is still happening occasionally (possibly a race-condition?)

See https://github.com/moby/moby/pull/39724#issuecomment-527493524

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39724/runs/48/nodes/35/log/?start=0


```
[2019-09-03T08:41:09.641Z] === Failed
[2019-09-03T08:41:09.641Z] === FAIL: pkg/plugins TestClientWithRequestTimeout (0.00s)
[2019-09-03T08:41:09.641Z]     client_test.go:254: assertion failed: expected an error, got nil: expected error
```
