### ISSUE TITLE
docker stack deploy with kubernetes orchestrator on microk8s errors with "invalid configuration: no configuration has been provided"

### ISSUE THREAD

**Issue by neerolyte** [moby/moby#38602]
**Description**

I'm trying to run through https://blog.docker.com/2018/12/simplifying-kubernetes-with-docker-compose-and-friends/ with Docker and [Microk8s](https://microk8s.io/). Originally I was running in to an error due to docker expecting a `~/.kube/config` file to exist even though it didn't and now I'm getting a less obvious error.

**Steps to reproduce the issue:**
1. Have an Ubuntu 18.04.x host
2. `snap install microk8s --classic`
3. `microk8s.status --wait-ready`
4. `sudo apt install docker.io`
5. try any `docker stack deploy --orchestrator=kubernetes -c docker-compose.yml foo` style deployment

**Describe the results you received:**

```
$ docker stack deploy --orchestrator=kubernetes -c docker-compose.yml foo
stat /home/foo/.kube/config: no such file or directory
$ kubectl config set-context microk8s # creates the missing config file
Context "microk8s" created.
$ docker stack deploy --orchestrator=kubernetes -c docker-compose.yml foo
invalid configuration: no configuration has been provided
```

Using `strace` to follow the deploy command I can see that docker is looking for a kubernetes token but it's not there:

```strace
19480 execve("/usr/bin/docker", ["docker", "stack", "deploy", "--orchestrator=kubernetes", "-c", "docker-compose.yml", "foo"], 0x7ffc2ae6aea8 /* 65 vars */) = 0
[...]
19480 newfstatat(AT_FDCWD, "/var/run/secrets/kubernetes.io/serviceaccount/token", 0xc4202c32e8, 0) = -1 ENOENT (No such file or directory)
19480 write(2, "invalid configuration: no config"..., 58) = 58
```

It's not immediately obvious where I should grab that token from or how I expose it to docker though.

**Describe the results you expected:**

Either an error that pointed me at what config I'm still missing or a working deployment.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 6
Server Version: 18.06.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.15.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58GiB
Name: davesmac
ID: YKWS:UWKM:A24J:PFON:37EA:CKN3:ISES:D5H3:UGD6:SC3S:RPEN:JQYW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: lyte
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by thaJeztah** [comment]
Thanks for reporting; this repository is not the best place to report this issue though, as the code for the Compose on Kubernetes feature is a separate project; could you open a ticket in that issue tracker instead? https://github.com/docker/compose-on-kubernetes/issues

I'll close the issue here, but feel free to continue the conversation
