### ISSUE TITLE
Docker daemon does not accept content trust configuration via /etc/docker/daemon.json

### ISSUE THREAD

**Issue by HouzuoGuo** [moby/moby#38639]
**Description**
According to:
https://docs.docker.com/engine/security/trust/content_trust/#enabling-dct-in-docker-engine-configuration

Content trust can be enabled on Docker daemon via config file `daemon.json`, however the configuration keys are no longer recognised.

**Steps to reproduce the issue:**
Put the following content inside `/etc/docker/daemon.json` and then restart docker daemon:

<pre>
{
"content-trust": {
	"allow-expired-trust-cache": true,
	"mode": "enforced",
	"trust-pinning": {
		"official-images": true,
		"root-keys": {
			"example.com/*": [
				"abcdabcd48297662451fdaeb5345182460ad0dc81343f31fec9bf7f3aaaabbbb"
			]
		}
	}
}
}
</pre>

**Describe the results you received:**
Content trust settings are enabled for the docker daemon.

**Describe the results you expected:**
Docker daemon fails to start and says those settings are not recognised:

     unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: allow-expired-trust-cache, mode, trust-pinning

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1036-azure
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.791GiB
Name: houzuo-guo-ability-edge-workspace
ID: D4IW:IAYU:I4Y2:P2H5:DOXT:LXUY:PT7O:XJBB:NF2N:JULF:AEMP:DQOH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
Hmm... there is no DCT in the engine, at least in OSS.

Maybe the docs are referring to Docker EE?

@thejeztah

**Comment by thaJeztah** [comment]
Yes, I think this is a feature that's only available in docker engine enterprise (18.09)

**Comment by thaJeztah** [comment]
I went to see if the docs need to be updated, but I see there's a note in that section mentioning that already;

> Note this only applies to Docker Enterprise Engine 18.09 or newer. This implementation is also separate from the only run signed images feature of Universal Control Plane


I'll go ahead and close this issue, but feel free to continue the conversation

**Comment by HouzuoGuo** [comment]
thanks!
