### ISSUE TITLE
LCOW: Running docker commands inside a linux container running on a Windows Host

### ISSUE THREAD

**Issue by ArnabKalita** [moby/moby#38638]
**Description**

I am running a bunch of Windows and Linux containers on a Windows Server 2019 host and the latest Docker EE edition (18.09.1). One of the linux containers is an Ubuntu (16.04) container. I install Docker inside the Ubuntu container to view all containers running on the Windows host from inside the Ubuntu container (`docker ps -a`). We are not able to view any containers since the docker commands do not run.

**Steps to reproduce the issue:**
  1. In the Windows host, change the hosts file inside `C:\ProgramData\docker\config\daemon.json` to     add a new field like

      `"hosts": ["tcp://0.0.0.0:2375"]`

so that the Docker daemon does not use the default named pipe socket for Windows. 

  2.  Next Run an Ubuntu container inside the Windows host with the command --
       `docker -H tcp://0.0.0.0:2375 run --name "ubuntu" -dit ubuntu`

The Ubuntu container starts successfully.

  3.  Exec into the container -
       `docker -H tcp://0.0.0.0:2375 exec -it ubuntu /bin/bash`

and run the below command 
```
root@xxxxxxx:/# docker -H tcp://0.0.0.0:2375 ps -a
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
 ```

**Describe the results you received:**

I am not able to run docker commands inside the container, and running any docker command gives me errors like 
```
Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
```

**Describe the results you expected:**

`docker -H tcp://0.0.0.0:2375 ps -a` should display all running and exited containers inside the container just like it does within the windows host
```
PS C:\ProgramData\docker\config> docker -H tcp://0.0.0.0:2375 ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                             PORTS               NAMES
a5a3506b9a56        ubuntu                        "/bin/bash"              4 hours ago         Up 4 hours                                             ubuntu
046dc4f3d776        ubuntu                        "/bin/bash"              6 hours ago         Exited (4294967295) 4 hours ago                        ubuntu-host
04cc0e5a6e55        ubuntu                        "/bin/bash"              21 hours ago        Created                                                ubuntu-new
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
PS C:\ProgramData\docker\config> docker -H tcp://0.0.0.0:2375 version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        20b67756d0
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      true

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       20b67756d0
  Built:            01/09/2019 17:09:57
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
PS C:\ProgramData\docker\config> docker -H tcp://0.0.0.0:2375 info
Containers: 8
Running: 1
Paused: 0
Stopped: 7
Images: 8
Server Version: 18.09.1
Storage Driver: windowsfilter (windows) lcow (linux)
Windows:
LCOW:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics l2bridge l2tunnel nat null overlay transparent
Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.253)
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: ************
ID: ZPGC:ABZ2:7DPK:IWMN:XLNB:M7F6:22RM:63SS:A3BO:5BBI:FHQ7:GSEP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: -1
Goroutines: 28
System Time: 2019-01-25T11:05:30.8512929Z
EventsListeners: 0
Username: *********
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure VM running Windows Server 2019.

**Comment by jazzdelightsme** [comment]
You expect to be able to connect to the host at `tcp://0.0.0.0`... but 0.0.0.0 means "local machine", which is the container, not the host. You will need to figure out a route to your host, which depends on how you have networking set up. (For instance, if you know the host name, you may be able to just that; or you could pass the host's relevant IP address into the container via env. var; etc.)

See also: https://github.com/moby/moby/issues/30372

**Comment by jhowardmsft** [comment]
Yes, what @jazzdelightsme said. If using a nat network, I think (@daschott will probably correct me), you probably want to be connecting to either your nat-assigned IP address or the nat gateway address.

Caveat: I'm not entirely convinced this is a scenario that the networking team want to support, or indeed if above does actually work, but I'll let them comment on that.

However, as this is user-error based on the description and use pattern, closing.
