### ISSUE TITLE
Suggestion: Add possibility to copy or mount data from an existing image/layer

### ISSUE THREAD

**Issue by Nuc1eoN** [moby/moby#38656]
I am suggesting a feature that grants access to _data_ on an already existing image during build time. This might be implemented in a `COPY --from` syntax. This data might be used as a "secure" cache for the build process. Currently as far as I know, there is no such functionality, but correct me if I'm wrong.

This would enable faster build times and ease the workflow in certain scenarios. Relying on non-mutable data, already precompiled by docker, would be better than relying on the host systems data or volumes - which seems like a quite popular bad practice. If the concept still sounds wrong let me explain a use case:

Consider an application that requires a resource expensive operation in order to be deployed on the first run. Updates can happen frequently and are also mandatory for the application and are deployed as delta updates.
But now baking in those updates into an updated image requires the entire image to be rebuild! - without any "cached" data. All resulting in high bandwidth usage, processing power and build time even though updates would be trivial in a non-docker workflow.

Currently there are several approaches to address this problem:
1) Let the updates happen inside the container without touching the image. Considered bad practice but actually used by many.
2) Use volumes as a storage of "cached" data for the build process. A container might even be configured to be responsible to update the volume on demand and serve up-to-date data. This approach is discouraged for a number of reasons obviously, but used by a number of users since it's "easy to understand" and can be implemented!
3) Using pre-build images as a starting point. Those base images would need to be updated in an arbitrary cycle OR delta updates might get huge over time (updates might be a few gigs), slowing down the process. Also working with already outdated information form the start sounds like a bad practice in a scalable environment over time. Also rather a hassle.. like a workaround for a more simple solution.
4) There might be a new approach with the new buildkit integration? Using `RUN --from` one could create a "data cache" directory on the host as far as I understand? `RUN --from` is currently not documented extensively however, so fell free to prove me wrong.
But if so - why not just use data already existing and up-to-date from the :latest image as suggested here? It would prevent being reliant on the host system and make use of the docker ecosystem.
5) Installing the application on the host system and take the updated data from there using a simple `COPY`. But this circumvents the whole docker ecosystem with all it's downsides attached.

_Those are the ones I come up with! If there's any better solution that I am not seeing don't hesitate to speak it out_!

**The goal is to have a simple, fast, secure and efficient solution for the above use case.**

Let me know what you think! :)

**EDIT:** Since this is a feature you'd rather want to use dynamically and not statically defined in the Dockerfile, something like a `--mount <image>` <image> flag for buildkit would actually be better I guess.

**Comment by hholst80** [comment]
Is this suggestion something like this? It would be very useful.

```
FROM ubuntu:18.04 as build
# lots of build stuff...
FROM ubuntu:18.04
RUN --mount=build:/build dpkg -i /build/path/to/artifact/artifact.deb
```

**Comment by cpuguy83** [comment]
This is already possible with buildkit enabled.
See https://docs.docker.com/develop/develop-images/build_enhancements/

Closing because while what buildkit has isn't exactly the same thing as what's asked for, the results should be, but feel free to call me out on this.

Thanks!

**Comment by hholst80** [comment]
@cpuguy83 how? As I understand it two things are possible:

1) Mount secrets
2) Mount build context

Mounting multi-stage layers is not supported.

**Comment by hholst80** [comment]
@cpuguy83  thank you that works like I want already!

https://github.com/hholst80/buildkit

**Comment by thaJeztah** [comment]
@hholst80 also for simple situations, where you only need to "copy" a file, `COPY --from` should also work, i.e., your example Dockerfile;

```Dockerfile
# syntax = docker/dockerfile:1.0-experimental
FROM ubuntu:18.04 as build
RUN echo "This is a test" > /testfile
FROM alpine:latest
RUN --mount=from=build,dst=/build ls -la /build > /contents-of-build && \
                                  cp /build/testfile /copy-of-testfile
CMD [ "cat", "/contents-of-build" ]
```

Could also use the non-experimental syntax, and use `COPY --from`;


```Dockerfile
FROM ubuntu:18.04 as build
RUN echo "This is a test" > /testfile

FROM alpine:latest
RUN --from=build /testfile /copy-of-testfile
CMD [ "cat", "/contents-of-build" ]
```

Note that `COPY --from` can use both a _buildstage_ as well as an _image_ directly, for example:

```Dockerfile
FROM alpine
COPY --from=ubuntu:18.04 /etc/os-release /ubuntu-os-release
CMD [ "cat", "/ubuntu-os-release" ]
```

**Comment by Nuc1eoN** [comment]
> Is this suggestion something like this? It would be very useful.
> 
> ```
> FROM ubuntu:18.04 as build
> # lots of build stuff...
> FROM ubuntu:18.04
> RUN --mount=build:/build dpkg -i /build/path/to/artifact/artifact.deb
> ```

Well not quite. This is the approach I wrote about in point 3, so not the solution I was content with.

> This is already possible with buildkit enabled.
> See https://docs.docker.com/develop/develop-images/build_enhancements/
> 
> Closing because while what buildkit has isn't exactly the same thing as what's asked for, the results should be, but feel free to call me out on this.

As said above this suggestion wasn't about multi-stage builds, but something a bit different for a tad different use case.. However @thaJeztah totally saved it, I never was aware `COPY --from` was actually capable of not only copying previous build-stages but also from external images.
> Note that `COPY --from` can use both a _buildstage_ as well as an _image_ directly, for example:
> 
> ```dockerfile
> FROM alpine
> COPY --from=ubuntu:18.04 /etc/os-release /ubuntu-os-release
> CMD [ "cat", "/ubuntu-os-release" ]
> ```

This is exactly what my suggestion was about. And now I acutally found one small paragraph in the docs [writing about it](https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage). So I guess this issue can stay closed.

Thanks for the valuable input guys!

**Comment by thaJeztah** [comment]
> Now one thing that might be missing is the possibility to not only copy but also mount external images. Not sure if this is actually possible with `RUN --mount`?

Yes, you can: both `--from=<reference>` and `--mount=from=<reference>` accept a build stage or image as `<reference>`. For example:

```Dockerfile
# syntax = docker/dockerfile:experimental
FROM busybox

# mount the docker CLI, and write its version to an "output" file
RUN \
  --mount=from=docker:18.09.2,src=/usr/local/bin/,dst=/usr/local/bin/ \
  docker version > /output || true
CMD cat /output
```

```bash
DOCKER_BUILDKIT=1 docker build -t foo .
docker run --rm foo

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```


Some more silly experiments I was trying a while back; https://gist.github.com/thaJeztah/cfd929a31976b745e3f7515ae37eb192

> PS: @thaJeztah I think in your first code snippet you've meant to write `COPY --from=build` instead of `RUN --from=build`?

Ah, good catch; updated 🤗

**Comment by Nuc1eoN** [comment]
> Yes, you can: both `--from=<reference>` and `--mount=from=<reference>` accept a build stage or image as `<reference>`. For example:

Thanks this is great news :)

Before writing up this bugreport I did dig into the new experimental syntax and read the corresponding docs from [here](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md), but the `--mount=from=<reference>` syntax is something that I don't see being mentioned there.. Is it simply missing from the documentation or why is it not mentioned?

**Comment by thaJeztah** [comment]
Hm... I see it mentions "Build stage or image name for the root of the source. Defaults to the build context.", but perhaps it should be made clearer.

Could you open a ticket for that in the buildkit repository? (Or even better: perhaps you're interested in opening a pull request to improve that page? 🤗 )

**Comment by Nuc1eoN** [comment]
> "Build stage or image name for the root of the source. Defaults to the build context."

Hm but reading that page I am still unsure how the whole syntax works. So `--mount=from=<reference>` is just a short form of `--mount=type=bind, from=<reference>`?

**Comment by thaJeztah** [comment]
Yes, `type=bind` is the default type, so you can omit `type=bind`
