### ISSUE TITLE
docker logs to stderr

### ISSUE THREAD

**Issue by hellojukay** [moby/moby#38651]
why `docker logs` print the output to stderr , i think it shoud print to stdout.
why not ？

**Comment by chilloutman** [comment]
I think it outputs to whatever was used by the process in the container. So if your program uses stdout and stderr, docker logs will also use both.

In a shell, the solution is adding `2>&1` and stderr will be redirected to stdout, so that everything will be printed to stdout.

**Comment by cpuguy83** [comment]
Yep, it sends to whatever stream was used on the container.
