### ISSUE TITLE
docker save error: Error response from daemon: open /var/lib/docker/aufs/diff/0c2b1325665ca467cbc7873c21e663cc2867cec4c1bba0e6f03b2ab4632596d1/opt/geronimo/var/catalina/logs/0.0.0.0_access_log.2016-04-20.txt: no such file or directory

### ISSUE THREAD

**Issue by tiendungitd** [moby/moby#38669]
Hi there,
I have some docker images cannot save, I have no idea why it happen. Another images, I can save successfully.
**Steps to reproduce the issue:**
1.  Run the command: docker save -o /tmp/geronimo-ictticket01022019 geronimo-ictticket:latest

**Describe the results you received:**

After that it show the error:  Error response from daemon: open /var/lib/docker/aufs/diff/0c2b1325665ca467cbc7873c21e663cc2867cec4c1bba0e6f03b2ab4632596d1/opt/geronimo/var/catalina/logs/0.0.0.0_access_log.2016-04-20.txt: no such file or directory

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:22 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:52 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 16
 Running: 12
 Paused: 0
 Stopped: 4
Images: 56
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 61.44GiB
Name: dockerhost2
ID: FSAZ:M3LU:SVN4:BHDV:HV25:MWGT:R3K4:6IU3:XAFV:EOV3:C4L5:5OYO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: Ubuntu 14.04.2 LTS
I tried to restart server, docker service but no luck
Thanks.

**Comment by tiendungitd** [comment]
this seen a problem with the container images, I also can not push to docker hub.

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
