### ISSUE TITLE
--secret flag leaves traces of the mounted secret file in an image

### ISSUE THREAD

**Issue by shedimon** [moby/moby#38667]
**Description**
According to the New Docker Build secret information paragraph [in this post](https://docs.docker.com/develop/develop-images/build_enhancements/) using the latest docker 18.09 and buildkit there is a way to build docker images passing secret information in a safe way that will not end up stored in the final image. 
However, building an image with secret ends up with an empty file of the secret stored in an image

**Steps to reproduce the issue:**
1. Create the following Dockerfile: 
```
# syntax = docker/dockerfile:1.0-experimental
FROM alpine

RUN mkdir /secret

RUN --mount=type=secret,id=test.secret,target=/secret/test.secret cat /secret/test.secret && ls -l /secret

RUN cat /secret/test.secret && ls -l /secret
```
2. Create a secret file:
```
echo "THIS IS A SECRET" > secret.file 
```
3. Build an image:
```
DOCKER_BUILDKIT=1 docker build --no-cache -t secret-test --progress=plain --secret id=test.secret,src=secret.file .
```
4. Execute `docker run`:
```
docker run --rm secret-test sh -c 'ls -l /secret && cat /secret/test.secret'
```
**Describe the results you received:**
* During the build time:
```
#7 [3/4] RUN --mount=type=secret,id=test.secret,target=/secret/test.secret ...
#7       digest: sha256:20d4c0f50044967c50953a719613bde314647e3832ac9dfec882e956942f8cb3
#7         name: "[3/4] RUN --mount=type=secret,id=test.secret,target=/secret/test.secret cat /secret/test.secret && ls -l /secret"
#7      started: 2019-02-01 09:47:02.3738038 +0000 UTC
#7 0.547 THIS IS A SECRET
#7 0.549 total 4
#7 0.549 -r--------    1 root     root            17 Feb  1 09:47 test.secret
#7    completed: 2019-02-01 09:47:03.1793146 +0000 UTC
#7     duration: 805.5108ms


#8 [4/4] RUN cat /secret/test.secret && ls -l /secret
#8       digest: sha256:d9fbdef826b7bd229a80409edb45bed501ae03172b847aaad43054330aa4ccf0
#8         name: "[4/4] RUN cat /secret/test.secret && ls -l /secret"
#8      started: 2019-02-01 09:47:03.1812485 +0000 UTC
#8 0.616 total 0
#8 0.616 -rwxr-xr-x    1 root     root             0 Feb  1 09:47 test.secret
#8    completed: 2019-02-01 09:47:03.9898056 +0000 UTC
#8     duration: 808.5571ms
```

* Docker run:
```
total 0
-rwxr-xr-x    1 root     root             0 Feb  1 09:47 test.secret
```

**Describe the results you expected:**
No traces of a secret file in an image. Also, note the permissions of the resulting file being 755.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 374
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: AES6:QH5N:65RB:UCJC:W6BQ:PWN3:XWPW:NUNF:ALKR:KAP5:I7ZP:Y3OG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 53
 System Time: 2019-02-01T09:52:56.9856759Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproduces on a MacOS and on a Linux in an AWS EC2 instance.

**Comment by thaJeztah** [comment]
Hm, yes, the path will have to be created, as linux requires a mountpoint to mount the secret in the image.

@tonistiigi @AkihiroSuda  PTAL; wondering if we could somehow track if we _created_ the path, and if so, could remove it afterwards?

**Comment by tonistiigi** [comment]
Like @thaJeztah said, stub files are how different mounts are connected in linux.

While we figure out what to do with it, if this concerns you, you can create another tmpfs parent mount and put your secret (stub file) inside that. eg. `--mount=type=tmpfs,target=/run,rw`

From security perspective, note that only the contents of the secret is protected. Eg. your build cache still tracks the information about whether a secret was used by `RUN` and where it was mounted. Eg. when you change the path of the secret your cache would be invalidated.

**Comment by plantfansam** [comment]
> From security perspective, note that only the contents of the secret is protected. 

It might be worth updating the [docs](https://docs.docker.com/develop/develop-images/build_enhancements/) to reflect this, specifically mentioning that the file stub will remain in the image. I got pretty nervous when I saw my secret file in my final image and was pretty perplexed as to why it was empty.
