### ISSUE TITLE
docker login HTTP/HTTPS redirect reports success for bad credentials >18.03

### ISSUE THREAD

**Issue by fopina** [moby/moby#38662]
**Description**

In our company setup we have a docker registry managed by https://jfrog.com/artifactory/ behind an nginx reverse proxy to enforce HTTPS.

Never noticed any issue until upgrading from docker 18.03 to 18.06 where logins stopped working.
`docker login docker.company` always returns success (even with invalid credentials) but I do not get the appropriate access (cannot override existing tags, which only authenticated users can).

I've setup two DinD containers, one with 18.03 and another with 18.06 to quickly make tests and proxied those `dockerd` processes through Burp Suite.

So quick analysis of the request history in Burp:

#### *BAD* login with 18.03

1. #22  
   Hit `/v2/` over HTTPS  
   server replies `{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}` giving HTTP `realm` - `WWW-Authenticate: Bearer realm="http://docker.dev.contoso/artifactory/api/docker/bf-docker/v2/token",service="docker.dev.contoso"`
2. #23  
   Hit `/artifactory/api/docker/bf-docker/v2/token?account=inv&client_id=docker&offline_token=true&service=docker.dev.contoso` with credentials using Basic Auth over HTTP  
   server replies with 301 to HTTPS
3. #24  
   Follow 301 and hit `/artifactory/api/docker/bf-docker/v2/token?account=inv&client_id=docker&offline_token=true&service=docker.dev.contoso` with credentials using Basic Auth over HTTPS  
   server replies with `{"statusCode":401,"details":"BAD_CREDENTIAL"}`

#### *GOOD* login with 18.03

1. #25 - Same as 22
2. #26 - Same as 23
3. #27  
   Follow 301 and hit `/artifactory/api/docker/bf-docker/v2/token?account=inv&client_id=docker&offline_token=true&service=docker.dev.contoso` with credentials using Basic Auth over HTTPS  
   server replies with `{"token":"...","expires_in":3600}`
4. #28  
   Hit `/v2/` over HTTPS with acquired token  
   server replies with 200 `{}`

#### *BAD* login with 18.06

1. #29 - Same as 22
2. #30 - Same as 23
3. #31  
   Follow 301 and hit `/artifactory/api/docker/bf-docker/v2/token?account=inv&client_id=docker&offline_token=true&service=docker.dev.contoso` *BUT WITHOUT THE CREDENTIALS*  
   server replies with `{"token":"...","expires_in":3600}` (probably attached to some anonymous session)
4. #32 - Same as 28 (resulting in fake *GOOD* login)

#### *GOOD* login with 18.06

All the same as *BAD* login, resulting in a fake *GOOD* login 

1. #33 - Same as 29
2. #34 - Same as 30
3. #35 - Same as 31
4. #36 - Same as 32

#### Wrap up

So the problem is step 31 where 18.03 follows the HTTP-HTTPS redirect and sends the credentials as well but 18.06 (and 18.09 as well) follow the redirect without sending credentials.
I've used Burp as well to modify the `WWW-Authenticate` response header and replace the http with https (avoiding the redirect) and everything works then.

**Steps to reproduce the issue:**
1. Setup an HTTP registry with Basic Auth support (that sends WWW-Authenticate)
2. Put nginx in front of it, redirecting HTTP to HTTPS
3. `docker login` to that HTTPS nginx

**Describe the results you received:**

Put together a script that logs in with invalid and valid credentials using docker 18.03 and then again with 18.06.

```bash
➜  docker1803 git:(tests) ./test.sh
*** docker 18.03 ***
=> Invalid user
Error response from daemon: Get https://docker.dev.contoso/v2/: unauthorized: BAD_CREDENTIAL
=> Valid user
Login Succeeded

*** docker 18.06 ***
=> Invalid user
Login Succeeded
=> Valid user
Login Succeeded
```

**Describe the results you expected:**

I'd expect invalid credentials with 18.06 to output BAD_CREDENTIAL (as a result of properly validating them)

```bash
➜  docker1803 git:(tests) ./test.sh
*** docker 18.03 ***
=> Invalid user
Error response from daemon: Get https://docker.dev.contoso/v2/: unauthorized: BAD_CREDENTIAL
=> Valid user
Login Succeeded

*** docker 18.06 ***
=> Invalid user
Error response from daemon: Get https://docker.dev.contoso/v2/: unauthorized: BAD_CREDENTIAL
=> Valid user
Login Succeeded
```

**Output of `docker version`:**

18.03

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.37 (downgraded from 1.39)
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ce
  API version:      1.37 (minimum version 1.12)
  Go version:       go1.9.5
  Git commit:       9ee9f40
  Built:            Thu Apr 26 07:23:03 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

18.06

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Clement-TS** [comment]
Hi there,
I'm experiencing a similar issue with a fresh new install of Artifactory Pro (6.17.0).
Artifactory is run behind a nginx reverse-proxy, all running as Docker containers.

It seems this is not related to Artifactory itself, but a common nginx misconfiguration, see: https://docs.docker.com/registry/recipes/nginx/

Basically redirects can void your headers, and cause issue relaying the basic auth tokens. That said, I do not get why `docker login` always returns success in that case.

**Comment by fopina** [comment]
Forgot I had this open, I’ll close it. Our configuration was forcing a redirect and the change I mentioned in docker version was a good change which was “not sending post parameters to a redirect”.
We simply fixed nginx rules.

**Comment by anshul0915** [comment]
Can you please let us know how you fixed it

**Comment by fopina** [comment]
> Can you please let us know how you fixed it

Can't really remember but there was a catch-all redirect for slash/no-slash I believe, in the nginx configuration.
As the old docker version did not respect the rule "do not send POST data on redirects" it worked.
We just reviewed the paths in the nginx conf and fixed them

**Comment by anshul0915** [comment]
we have setup docker registry on jfrog in onprem and devtools support it i am not getting much support from devtools . Is there any way i can handle at docker client level
