### ISSUE TITLE
how can we add UID and GID in stack file or compose file

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [moby/moby#38670]
Hi Team,

how can we add UID and GID in stack file or compose file. I know we can use uid,gid and mode with secret in compose file and we can add user in Dockerfile but we want non-root user in compose file who can run the containers and services. We are using swarm mode and run the docker stack deploy command to create services.

**Comment by drnybble** [comment]
https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir
