### ISSUE TITLE
ARG NCCL_VERSION changed once set in dockerfile

### ISSUE THREAD

**Issue by mirocody** [moby/moby#38690]
**Description**

BUG REPORT INFORMATION:
I set ARG NCCL_VERSION=2.3.5-2+cuda9.0 in Dockerfile and then found its value changed to 2.4.2. However, either set ENV NCCL_VERSION=2.3.5-2+cuda9.0 or ARG NCCL=2.3.5-2+cuda9.0 works. 
**Steps to reproduce the issue:**
```
FROM nvidia/cuda:9.0-devel-ubuntu16.04
ARG NCCL_VERSION=2.3.5-2+cuda9.0
RUN echo ${NCCL_VERSION}
```

**Describe the results you received:**
```
Step 5/19 : ARG NCCL_VERSION="2.3.5-2+cuda9.0"
 ---> Running in 57832a40eb86
Removing intermediate container 57832a40eb86
 ---> f40b39ab4835
Step 6/19 : RUN echo ${NCCL_VERSION}
 ---> Running in 608b8f09bdce
2.4.2
```

**Describe the results you expected:**
`2.3.5-2+cuda9.0`

**Additional information you deem important (e.g. issue happens only occasionally):**
I do understand best practice is using ENV for setting version, but I am still curious why this happen. Is this a pre-defined build argument or why it changed once after it gets set?
**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 107
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1075-aws
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 72
Total Memory: 137.5GiB
Name: ip-172-31-24-80
ID: AZMG:R5LQ:HCUK:M7XH:FJHT:VXU6:EISA:KC6L:FBRB:2RWW:EHGD:TGXP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS c5.18xlarge.

**Comment by drnybble** [comment]
[root@paw-build1 cuda]# docker inspect --format "{{.Config.Env}}" nvidia/cuda:9.0-devel-ubuntu16.04
[PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CUDA_VERSION=9.0.176 CUDA_PKG_VERSION=9-0=9.0.176-1 LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 NVIDIA_VISIBLE_DEVICES=all NVIDIA_DRIVER_CAPABILITIES=compute,utility NVIDIA_REQUIRE_CUDA=cuda>=9.0 **NCCL_VERSION=2.4.2** LIBRARY_PATH=/usr/local/cuda/lib64/stubs]

It is an environment variable set in the image.

**Comment by mirocody** [comment]
Thanks @drnybble! I did not know that builder file will import env from previous container, your answer really helps.
