### ISSUE TITLE
Misleading overlay2 driver documented prerequisites

### ISSUE THREAD

**Issue by dmandalidis** [moby/moby#38695]
Reading this introductory [note](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) one would understand that docker-ce *won't work* with RHEL kernel above 3.10.0-514.

However reading the [prerequisites](https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites) it seems that docker-ce *works* with RHEL kernel 3.10.0-514 and above.

Which one of the two statements above is correct?

**Comment by cpuguy83** [comment]
I'm not sure I follow why you think it won't work on RHEL, it says in both cases that it works on RHEL.

**Comment by dmandalidis** [comment]
Quoting from the note:

```
To use the new driver, you need version 4.0 or higher of the Linux kernel, *unless you are a Docker EE user on RHEL or CentOS, in which case you need version 3.10.0-514*
```

What I understand from this is that I either need 4.x kernel version to run *docker-ce* in any case. This is overturned in the prerequisites section below:

```
Version 4.0 or higher of the Linux kernel, *or RHEL or CentOS using version 3.10.0-514* of the kernel or higher.
```

Check the two emphasized phrases to spot the difference

**Comment by cpuguy83** [comment]
The "or" is definitely better worded, but to me they mean the same thing.
Did you want to update the wording?

By the way, I don't think Docker packages Docker CE for RHEL, only EE.

**Comment by dmandalidis** [comment]
Ok, since they mean the same I could open a PR for a tiny rephrase of the notes' section phrase. You re right for the packages, but using the CentOS package for having docker-ce in RHEL is a common practice;  after all it's all about the kernel version

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker.github.io/pull/8205
