### ISSUE TITLE
docker build shows no output until "Sending build contex to docker daemon"

### ISSUE THREAD

**Issue by ironjan** [moby/moby#38703]
**Description**
When executing `docker build .` in a directory wit a lot of files, it takes a long time until the message "Sending build context to docker daemon" is displayed. From a user perspective, the command  `docker build` seems to hang. 

Adding a message along the lines of  `Preparing to send the content of <context> to the docker daemon`  or `Preparing to send all contents of <context> to the docker daemon` could help to explain what is happening. `<context>` should be given as absolute path if local.

**Steps to reproduce the issue:**
Alternative 1:
1. `cd $HOME`
2. `touch Dockerfile` 
3. `docker build`

Alternative 2:
1. `docker build https://github.com/moby/moby.git` (This is not a valid repo for build, but shows the issue too)

**Describe the results you received:**
In both alternatives, no output is produced for quite some while. It seems that `docker build` hangs or is unresponsive. 

The output for Alternative 2 on Windows without a running docker daemon is:

```
PS > Get-Date; docker build https://github.com/moby/moby.git; Get-Date
Sunday, February 10, 2019 12:37:45 PM
[error messages omitted ...] This error may also indicate that the docker daemon is not running.
Sunday, February 10, 2019 12:42:41 PM
```
It takes 5 minutes for any output to show. This is worse for large local build contexts (150k files, 8GB ~ 20-30 minutes until output, depending on disk speed). 

**Describe the results you expected:**
"Something" should happen. 

Adding a message like mentioned above would prepare the user for a potentially long-running operation or hint at potential issues with the usage of `docker build`. E.g. in#14172 users who execute `docker build .` in their `$HOME` directory) however in my case it was just a context with 150k files 

**Additional information you deem important (e.g. issue happens only occasionally):**
I had a large local build context (150k files, 8GB ) and it took ~20-30 minutes until the first output. The initial pass(?) of the buld context can be sped up by replacing the big file collection with a tar. In that case (100 files, still 8G) output was shown after ~30 seconds, 

**Output of `docker version`:**
(docker daemon currently not running, this system is not setup for docker. I originally noticed the issue on another system but did not have the time to write this issue)
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false
[docker daemon not running]
```

**Output of `docker info`:**
(docker daemon currently not running, this system is not setup for docker. I originally noticed the issue on another system but did not have the time to write this issue)
```
[docker daemon not running]
```

**Comment by AkihiroSuda** [comment]
This should not happen in BuildKit mode

**Comment by thaJeztah** [comment]
> This should not happen in BuildKit mode

Yes, was thinking about that as well. Unfortunately though, BuildKit is not yet supported on Windows, and (I think) especially on Windows, it's more common to have bigger images.

So, depending how long it takes before BuildKit can be supported on Windows, I think it would make sense to print a message at the start if BuildKit is not used (and skip that message if it is).

This change would likely have to be in the CLI though, so it would be best to have this issue opened in that repository.

@ironjan could you open this issue in the docker/cli issue tracker https://github.com/docker/cli/issues/new

**Comment by ironjan** [comment]
@thaJeztah  Thanks for the info. Reported it there.
