### ISSUE TITLE
Flaky test: DockerDaemonSuite.TestDaemonRestartUnlessStopped

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#38720]
This test looks to have become flaky (recently updated in https://github.com/moby/moby/pull/35355)

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/44079/console

```
15:21:20 FAIL: docker_cli_daemon_test.go:118: DockerDaemonSuite.TestDaemonRestartUnlessStopped
15:21:20 
15:21:20 [d62b0ae349327] waiting for daemon to start
15:21:20 [d62b0ae349327] daemon started
15:21:20 
15:21:20 docker_cli_daemon_test.go:157:
15:21:20     // both stopped
15:21:20     testRun(map[string]bool{"top1": false, "top2": false, "exit": false}, "")
15:21:20 docker_cli_daemon_test.go:140:
15:21:20     c.Assert(strings.Contains(out, name), check.Equals, shouldRun, check.Commentf(format, prefix, name))
15:21:20 ... obtained bool = true
15:21:20 ... expected bool = false
15:21:20 ... container "exit" is running
15:21:20 
15:21:20 [d62b0ae349327] exiting daemon
```

**Comment by thaJeztah** [comment]
ping @x1022as @cpuguy83

**Comment by x1022as** [comment]
The testcase fails occasionally, and it is not unless-stopped policy related(I think), this is how I reproduce (propably not the same reason):

1. start an always-fail container with restart policy(always and unless-stopped both work):

`docker run -d --name test --restart always busybox false`

2. wait for a while, `test` will keep restarting itself, but with increasing penalizing waiting time. During this waiting period, `docker stop test` would make this container stuck in `restarting` status, and never get resumed.

```
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                PORTS               NAMES
d0595237054a        busybox             "false"             5 minutes ago       Restarting (1)       4 minutes ago                       exit
```
 *this container has been stuck in Restarting for > 4 minitues*

`docker rm exit` (without `-f`) works fine to remove it.

**Comment by thaJeztah** [comment]
Hm, ok, so what I see in that situation is that `docker inspect` shows the correct information (status: exited), but `docker ps` shows outdated information.

I think I see what's happening; working on a patch

**Comment by kolyshkin** [comment]
SGTM
