### ISSUE TITLE
rootless needs better overlay detection

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#38721]
Current detection for `overlay` support does not work ideally in rootless mode. Atm it tries to modprobe overlay and then check it under `/proc/filesystems`. Under rootless the `modprobe` will fail with permission error.

But it turns out that if I just mount overlay inside rootlesskit it will work fine and also load the module. So I propose checking if we are running in rootless and try to do a dummy overlay mount instead of modprobe.

@AkihiroSuda @tiborvass

**Comment by tiborvass** [comment]
Works for me. If we want to be more conservative, we could do that only if modprobe failed.

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/containerd/pull/2159 could be used?

**Comment by AkihiroSuda** [comment]
@dmcgowan WDYT?

**Comment by dmcgowan** [comment]
I like the idea of reusing what you wrote in the snapshotter. It is unfortunate that package has an `init()` on it though, it is harmless but still unnecessary memory usage.

**Comment by AkihiroSuda** [comment]
#40194
