### ISSUE TITLE
curl fails inside container on https connection

### ISSUE THREAD

**Issue by cytopia** [moby/moby#38724]
**Description**

_Sometimes_ when using curl inside the container with HTTPS connections it fails with the following error:
```
cURL error 60: SSL certificate problem: unable to get local issuer certificate
```

**Steps to reproduce the issue:**
1.
2.
3.

This is currently not entirely reproducible as it only fails sometimes and very randomly

**Describe the results you received:**
```
cURL error 60: SSL certificate problem: unable to get local issuer certificate
```

**Describe the results you expected:**

Valid return from the page

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 18.06.2-ce, build 6d37f41
```
Note that this issue was randomly present from any previous 18.06 version as well

**Additional environment details (AWS, VirtualBox, physical, etc.):**

An example of a failed Travis CI build is here: https://travis-ci.org/cytopia/devilbox/jobs/475445609#L595

All other jobs in the same pipeline success (seen here: https://travis-ci.org/cytopia/devilbox/builds/475445589)

The issue happens randomly around every 100/150 builds and most of the time it is a random build job that fails. Retriggering the job succesds.

**Linked issues**

https://github.com/moby/moby/issues/2011

**Comment by thaJeztah** [comment]
I'm not sure this is an issue in Docker, other than possibly a race condition if a service is not up yet; or the certificate was not loaded https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by cytopia** [comment]
> or the certificate was not loaded https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

It was loaded fine. As I said, it's more likely to be a race condition as this error happens around every 100th time.

In order to ensure this is not a general connectivity issue I will add a curl https check on the host system just before the check from within the Docker.

**Comment by cytopia** [comment]
I've hit the issue again. This time with a bit more info.

1. Host system [works fine](https://travis-ci.org/cytopia/devilbox/jobs/494190275#L586)
2. Container call [fails](https://travis-ci.org/cytopia/devilbox/jobs/494190275#L587)
3. Container call with `--cacert` [succeeds](https://travis-ci.org/cytopia/devilbox/jobs/494190275#L615)

To note again, before this error there were around 150 successful runs, only this very run randomly failed.

**Comment by o5** [comment]
Pruning of docker network has saved me!

```bash
docker network prune
```

**Comment by quicktoolbox** [comment]
Running: update-ca-certificates

Fixed my issues when sending via php/curl.

**Comment by thaJeztah** [comment]
Closing this one as I don't think there's a bug at hand here
