### ISSUE TITLE
Merge #38050 causing a failure?

### ISSUE THREAD

**Issue by EML-github** [moby/moby#38725]
I've got a new Win10 installation, and have been the following the Ubuntu tutorial [here](https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#6) on installing Docker. This fails at Step 7 with this message:

```
C:\home\evan\local\docker>.\dockerd.exe -D --data-root C:\lcow
WARN[2019-02-13T18:01:23.679810300Z] cannot set sticky bit on files under XDG_RUNTIME_DIR  error="homedir.StickRuntimeDirContents() is not supported on this system"
failed to load listeners: open //./pipe/docker_engine: Access is denied.
```

This seems to be from code that was added recently (pull request #38050, "Allow running dockerd as a non-root user", "Set sticky bit if XDG_RUNTIME_DIR is set && the file is actually under XDG_RUNTIME_DIR").

Unfortunately, I know exactly nothing about Windows; I didn't even know it had a sticky bit. I tried running dockerd as a non-root user after reading the comments, but this is no better. However, Windows does now produce  a "This app can't run on your PC" popup instead.

I don't suppose that you can throw any light on this?

**Comment by AkihiroSuda** [comment]
The XDG_RUNTIME_DIR message seems a warning, not an error.

Does v18.09.2 work?

**Comment by AkihiroSuda** [comment]
Please make sure to execute `dockerd.exe` in admin command prompt.

Rootless mode is not supported on Windows.

**Comment by AkihiroSuda** [comment]
@thaJeztah this doesn't seem related to `area/rootless`

https://github.com/moby/moby/issues/38725#issuecomment-463443432

**Comment by jhowardmsft** [comment]
Right, but the Ubuntu tutorial isn't applicable in any way to Windows. What's the output of `docker info` and `docker version`. How did you install docker? Through Docker-For-Windows? From master.dockerproject.org? Are you launching from an elevated command prompt, not a regular-user prompt?

**Comment by AkihiroSuda** [comment]
I assume this can be closed, let me know if not
