### ISSUE TITLE
A macvlan network that receives its configuration from a config-only network fails to grant network connectivity to containers using the macvlan network.

### ISSUE THREAD

**Issue by HouzuoGuo** [moby/moby#38731]
**Description**

A macvlan network that receives its configuration from a config-only network fails to grant network connectivity to containers using the macvlan network.

**Steps to reproduce the issue:**
1. `docker network create --config-only --subnet 10.58.44.0/24 -o "parent=eth0" --gateway=10.58.44.1 --ip-range 10.58.44.197/32 testnet-cfg`
2. `docker network create --config-from testnet-cfg testnet`
3. `docker container run -it --network testnet --rm hzgl/diagnosis-toolbox`

**Describe the results you received:**

The container receives the correct IP configuration according to the configuration network `testnet-cfg`, it appears to have also correctly received a new MAC address, however, the container does not have any network connectivity, even though the underlying LAN indeed offers Internet connectivity:

<pre>
root@58da29a45bc5 /# traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  58da29a45bc5 (10.58.44.197)  3068.211 ms !H  3068.175 ms !H  3068.171 ms !H
</pre>

**Describe the results you expected:**

The identical configuration achieved without usage of a config-only network works flawlessly and receives Internet connectivity, as expected:

<pre>
root@hzgl-ubuntu-vm ~# docker network create -d macvlan --subnet=10.58.44.0/24 --gateway=10.58.44.1 --ip-range 10.58.44.197/32 -o parent=eth0 testnet
67edf844d399059f4ff7a112cf16c3f96b422d564a8b18dad31db086733e1795
root@hzgl-ubuntu-vm ~# docker container run -it --rm --network testnet hzgl/diagnosis-toolbox
Welcome to fish, the friendly interactive shell
root@98d9c25dbfbb /# traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  10.58.44.2 (10.58.44.2)  0.538 ms  0.711 ms  0.712 ms
 2  10.58.54.30 (10.58.54.30)  1.262 ms  1.430 ms  1.788 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
......
.....
</pre>

Therefore, the usage of config network indeed caused the issue.

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 5osuj7hgo9dwlo09vrlmxs995
 Is Manager: true
 ClusterID: pcd9ovh7jz66rp04v5om05d7r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.58.44.129
 Manager Addresses:
  10.58.44.129:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 3.809GiB
Name: hzgl-ubuntu-vm
ID: N3M7:7AXY:DA5Q:NP76:FHSS:MI6U:ND5Q:6LPV:56MK:IJFP:2WTC:ZBH6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Container host is a fully patched Ubuntu 18.04 LTS running as a Hyper-V guest.

**Comment by itsgk92** [comment]
Looks like the network connectivity issue may be due to to improper configured gateway to a bridge network. Please validate the network creation with driver macvlan and reconfirm the issue.

* `docker network create -d macvlan --config-from testnet-cfg testnet`

**Comment by HouzuoGuo** [comment]
Thanks @itsgk92 , good catch.

**Comment by shanekuz** [comment]
--driver macvlan --attachable vlan500 --subnet=192.168.100.0/24 --ip-range=192.168.100.0/24 --gateway=192.168.100.254 ens160

isnt working whats the error here?
