### ISSUE TITLE
docker --version command is not showing the current docker engine version

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [moby/moby#38736]
After upgrade to new Docker engine 18.09.2-ee, the new version is not showing in docker --version command but it is perfectly showing in docker info, docker node ls and from UCP end.
 docker --version command still showing the old engine version even we reboot the daemon or restarted the server.

**Comment by cpuguy83** [comment]
"docker --version" shows the CLI version.
"docker version" shows the engine version and the cli version.

**Comment by cpuguy83** [comment]
Closing for house keeping as this seems to work as expected, but feel free to comment to let me know otherwise.

**Comment by dipanjanmukherjee83** [comment]
@cpuguy83 Thanks.
