### ISSUE TITLE
Limit on number of services / stacks

### ISSUE THREAD

**Issue by goetas** [moby/moby#38732]
**Description**
I'm trying to understand if there is a limit on the number of stacks / services that can be created on a swarm cluster.

Question: Is there a limit on the number of stacks and/or services a swarm cluster can manage?

**Steps to reproduce the issue:**
We have a 3-master swarm cluster, with 56 stacks each having 4 different services, each having one container.
This means 224 services (and also 224 containers).

One more stack named "shared" with only 1 service (1 container); the network of this stack is shared with two services from the previous stacks. This means that 112 containers are connected to the shared network part of the "shared" stack.
(The containers connected to the shared network should be far from the 254 IP limit due to the /24 subnet).

**Describe the results you received:**
When trying to add more stacks, the services are created but containers that should be connected to the shared network do not start and the task stays in "new" and never gets assigned to a node.

Tasks that do not are connected to the shared network start as usual.

**Describe the results you expected:**

The tasks to be assigned to a node, and then containers to be started on that node.

**Additional information you deem important (e.g. issue happens only occasionally):**

`docker service ps SERVICE_NAME` does not provide any error, just the task stays in new.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
$ docker info
Containers: 86
 Running: 71
 Paused: 0
 Stopped: 15
Images: 65
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: vtdi132vxr8t2fkhpfznnbli5
 Is Manager: true
 ClusterID: tzm417keomjtxndqclyvsz6fd
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.16.21.233
 Manager Addresses:
  172.16.21.232:2377
  172.16.21.233:2377
  172.16.21.234:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.1GiB
Name: server1
ID: ZIWT:GL7H:OVYS:52DH:CEPW:SNY6:JG4B:DNOC:JJ7G:AOES:ZX2C:WQIX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: goetas
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by cpuguy83** [comment]
This is likely due to the network subnet size.

**Comment by cpuguy83** [comment]
Which is customizable.

**Comment by goetas** [comment]
Are you saying that there should be no limit on stacks/services?

**Comment by cpuguy83** [comment]
There is no hard limit.

**Comment by goetas** [comment]
Thanks for the info. Will investigate my issue and check the subnet sizes once again
