### ISSUE TITLE
file ownership become root after delete and re-create in container

### ISSUE THREAD

**Issue by rongshen** [moby/moby#38747]
I have encountered this bug with **kernel-lt** version larger than 4.4.155-1.el7.elrepo.x86_64
**Description**

When deleting an existing file in a container, and then create a new one with same name, the file ownership will change to root:root, even though parent folder permission is not root

**Steps to reproduce the issue:**
1. Use a simple dockerfile like this
```
FROM centos:7

RUN useradd -ms /bin/bash -G wheel admin
RUN mkdir -p /usr/local/mytest/bin && \
    chown -R admin:admin /usr/local/mytest
```
2. Start a container from the above Dockerfile, log in as admin and delete /usr/local/mytest/bin
3. Create same folder /usr/local/mytest/bin

**Describe the results you received:**
```
[admin@72b5c39509e2 mytest]$ ls -la
total 12
drwxr-xr-x 1 admin admin 4096 Feb 18 03:14 .
drwxr-xr-x 1 root  root  4096 Feb 18 03:14 ..
drwxrwxr-x 2 root root 4096 Feb 18 03:14 bin
```
**Describe the results you expected:**
```
[admin@72b5c39509e2 mytest]$ ls -la
total 12
drwxr-xr-x 1 admin admin 4096 Feb 18 03:14 .
drwxr-xr-x 1 root  root  4096 Feb 18 03:14 ..
drwxrwxr-x 2 admin admin 4096 Feb 18 03:14 bin
```
**Additional information you deem important:**
We use kernel-lt in our machines. We noticed this issue only happens for kernel-lt version larger than 4.4.155-1.el7.elrepo.x86_64, starting from 4.4.156-1.el7.elrepo.x86_64 file permission changes.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.153-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 72
Total Memory: 251.8GiB
Name: he-459-5a-65.maas
ID: WXPI:WU74:73K2:WN4V:IAFN:DGC7:OJ6W:HNNJ:3G7P:LEI2:3LX4:PJSF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machines

**Comment by thaJeztah** [comment]
Can you explain why you expect the `bin` directory to be owned by `admin` if the directory was _created_ by `root`?

Here's the same steps outside of a container (on a CentOS 7 machine);


```bash
useradd -ms /bin/bash -G wheel admin
mkdir -p /usr/local/mytest/bin && chown -R admin:admin /usr/local/mytest

cd /usr/local/mytest
ls -la
total 0
drwxr-xr-x.  3 admin admin  17 Feb 18 13:51 .
drwxr-xr-x. 13 root  root  145 Feb 18 13:51 ..
drwxr-xr-x.  2 admin admin   6 Feb 18 13:51 bin

rm -rf /usr/local/mytest/bin
mkdir -p /usr/local/mytest/bin
ls -la
total 0
drwxr-xr-x.  3 admin admin  17 Feb 18 13:53 .
drwxr-xr-x. 13 root  root  145 Feb 18 13:51 ..
drwxr-xr-x.  2 root  root    6 Feb 18 13:53 bin
```

The only situation (that I'm aware of) that the new directory would inherit ownership of its parent directory would be if a "sticky bit" was set on the parent (`/usr/local/mytest`) directory, but in that case only the `group` would be inherited;

```bash
rm -rf /usr/local/mytest/bin

# set sticky-bit
chmod g+s /usr/local/mytest

mkdir -p /usr/local/mytest/bin
ls -la
total 0
drwxr-sr-x.  3 admin admin  17 Feb 18 13:59 .
drwxr-xr-x. 13 root  root  145 Feb 18 13:51 ..
drwxr-sr-x.  2 root  admin   6 Feb 18 13:59 bin
```


_Possibly_ the previous behavior was actually a bug in overlayfs, where _removing_ a directory is actually _creating_ a "white-out" file (indicating that a directory was removed), and the subsequent _create_ would either remove that file (showing the original file again).

**Comment by rongshen** [comment]
Sorry for the confusion.
On step 2, we don't delete the whole directory, we only delete bin folder under /usr/local/mytest/. The parent directory is not deleted and ownership is not touched.
```
useradd -ms /bin/bash -G wheel admin
mkdir -p /usr/local/mytest/bin && chown -R admin:admin /usr/local/mytest

cd /usr/local/mytest

cd  /usr/local/mytest/ && rm -rf bin && mkdir bin
```
We have found one suspicious changes here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/overlayfs/dir.c?id=v4.4.155&id2=v4.4.156
Is this the same overlayfs bug mentioned above?

**Comment by thaJeztah** [comment]
> On step 2, we don't delete the whole directory, we only delete bin folder under /usr/local/mytest/. The parent directory is not deleted and ownership is not touched.

Oh, but that's what my reproduction steps use as well; running `rm -rf /usr/local/mytest/bin` does not remove the parent directories, only removes the last element of the path (`bin`);


```bash
mkdir -p /usr/local/mytest/bin
ls -la /usr/local/mytest/
total 12
drwxr-xr-x    3 root     root          4096 Feb 19 13:50 .
drwxr-xr-x    1 root     root          4096 Feb 19 13:50 ..
drwxr-xr-x    2 root     root          4096 Feb 19 13:50 bin

rm -rf /usr/local/mytest/bin
ls -la /usr/local/mytest/
total 8
drwxr-xr-x    2 root     root          4096 Feb 19 13:51 .
drwxr-xr-x    1 root     root          4096 Feb 19 13:50 ..
```


> We have found one suspicious changes here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/overlayfs/dir.c?id=v4.4.155&id2=v4.4.156
> Is this the same overlayfs bug mentioned above?

I was not referring to a specific change, but from your description sounded like the change in behavior looked like a possible bug fix in overlayfs.

I don't see a commit message there that describes what's being addressed in that commit, but perhaps @gregkh can provide that information.

**Comment by gregkh** [comment]
Try contacting the developers who made those changes if you have questions about it.

Hint, it's not me :)

**Comment by thaJeztah** [comment]
oh! apologies @gregkh - your name showed as "author" and "committer" (but I'm not familiar with the git.kernel.org UI 🤗 😅 )

**Comment by rongshen** [comment]
Thank you all for the kind reply.
I opened the ticket to see if this is a known issue. Looks like it is not a known issue.
I'll close this ticket now. If anyone run into this issue in future, my suggestion is to fix your kernel-lt version to 4.4.155.
Will update here if this issue is resolved in overlayfs in future.

**Comment by thaJeztah** [comment]
I'm not sure if this will be fixed in future, because the old behavior looks to be a bug (the `bin` folder should not be owned by `admin`, but by `root`), so kernel 4.4.156 is actually the _correct_ behavior

**Comment by rongshen** [comment]
I want to point out in my test the mytest folder is owned by admin user not root. 
Here is my run on a bare mental Centos machine:
```
[admin@he-459-5a-65 mytest]$ ls -la
total 12
drwxr-xr-x   3 admin admin 4096 Feb 21 05:42 .
drwxr-xr-x. 16 root  root  4096 Feb 21 05:39 ..
drwxrwxr-x   2 admin admin 4096 Feb 21 05:42 bin
```

**Comment by thaJeztah** [comment]
But in that case I see you're logged in as `admin`, so yes, then new files will be created by admin;

     admin@he-459-5a-65 mytest

In the container example, it's run as `root` so new files and directories will be created as root
