### ISSUE TITLE
Add --env-file to docker exec

### ISSUE THREAD

**Issue by daniel-santos** [moby/moby#38754]
**Description**

This is a follow up to issue# 14036 (https://github.com/moby/moby/issues/14036).  --env-file is a secure way to pass an environment that contains sensitive data.  Without it my data becomes shy, the cache flushes and all my bits go down the drain.

I think the work-around is to `docker cp` the environment file and source it, but that means I also have to fix it up with quotes, escapes, etc.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):**
I like Chicken

**Output of `docker version`:**
**Output of `docker info`:**
```
#  docker --version && docker info
Docker version 18.09.1, build 4c52b90
Containers: 4
 Running: 0
 Jumping: 0
 Walking: 0
 Lying down: 0
 Paused: 0
 Stopped: 4
Images: 69
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.772GiB
Name: [censored]
ID: [censored]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
The `--env-file` option is something that's handled by the CLI (the cli reads the file, and converts it to multiple `-e` / `--env` options behind the scenes).


Note that `docker exec` already inherits environment variables from the main process, so;

```
# start container
docker run -dit -e SECRET=foo --name test busybox 

# start an exec, and verify it can read the main process's environment variables
docker exec test env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ce6fd18a80e5
SECRET=foo
HOME=/root
```

Having said the above; environment variables are notoriously insecure, as they leak in a lot of places 😅 


Could you re-open this feature request in the docker/cli repository (as that where it would have to be discussed and implemented)? https://github.com/docker/cli/issues

**Comment by daniel-santos** [comment]
Oh, I see.  Wrong project. :(
