### ISSUE TITLE
can moby.slack.com admin invite me to join

### ISSUE THREAD

**Issue by 13567436138** [moby/moby#38765]
my email address is 195446040@qq.com

**Comment by AkihiroSuda** [comment]
`moby.slack.com` has nothing to do with Moby Project.

You want to join `#moby-project` channel of `dockercommunity.slack.com`?
You can join via https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

**Comment by fuweid** [comment]
I remember that we cannot register a slack account with `*@qq.com` and `*@163.com` 😂 

@13567436138 

anyway...

**Comment by tiny1990** [comment]
I want to join moby slack
my email :  maxss0609.pan@gmail.com

**Comment by thaJeztah** [comment]
Should be able to join using http://dockr.ly/slack
