### ISSUE TITLE
Script at get.docker.com doesn't contain fingerprint

### ISSUE THREAD

**Issue by JonasT** [moby/moby#38773]
**Description**

The script at get.docker.com doesn't contain any fingerprint for the apt key. While this makes no difference when downloading it on-demand and piping it into a bash, this makes a *big* difference in security when downloading it once and baking it into an image, and using this fixed version for a longer time to install docker in a larger deployment.
 
**Steps to reproduce the issue:**
1. Open https://get.docker.com/ in web browser
2. Look through entire script. Maybe I'm blind, but I can't see the fingerprint so unless I'm very mistaken it's not verified

**Describe the results you received:**
No fingerprint check that I can see

**Describe the results you expected:**
Fingerprint of docker apt key is in script, and is verified

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

not relevant, this is about get.docker.com

**Output of `docker info`:**
not relevant, this is about get.docker.com

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
>				$sh_c "curl -fsSL \"$DOWNLOAD_URL/linux/$lsb_dist/gpg\" | apt-key add -qq - >/dev/null"

Is this what you are looking for?

**Comment by cpuguy83** [comment]
Closing because it does appear to be in there unless I'm mistaken.
Also note this should likely go into https://github.com/docker/for-linux since it's specific to docker product.

Thanks! Let me know if there is an issue. 🙇 👼

**Comment by JonasT** [comment]
@cpuguy83 can you explain to me how that line verifies the fingerprint of the apt key that is added? because I don't see it at all

**Comment by cpuguy83** [comment]
The key is there, and is "verified" from https on the domain.

**Comment by JonasT** [comment]
@cpuguy83 https is a much weaker verification than an embedded fingerprint. so this is *very* unsatisfactory. again as explained above, this makes a huge difference then the script is baked (vs downloaded on-demand each time via HTTPS, where it obviously doesn't make a difference)

**Comment by JonasT** [comment]
I forwarded the ticket now to here: https://github.com/docker/for-linux/issues/602
