### ISSUE TITLE
Piping arbitrary input into `apt-key add` seems unsafe - why not use a command that may only add a single key, and only AFTER fingerprint is verified?

### ISSUE THREAD

**Issue by JonasT** [moby/moby#38772]
The documentation here https://docs.docker.com/install/linux/docker-ee/ubuntu/ suggests the following command to add the docker key:

```bash
curl -fsSL "${DOCKER_EE_URL}/ubuntu/gpg" | sudo apt-key add -
```

However,

1. it seems somewhat unobvious that this may not do a DoS by adding 999 keys
2. when the next verification step fails, I am still stuck with a bad key

Why not suggest a proper targeted command like the following one?

`apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D`

This is secure if the long key id is used, and won't add 999 keys, and won't add a key at all if it's not the exact long-fingerprint-matched one, which seems like a much better idea.

**Comment by JonasT** [comment]
Edit: oops, apparently `apt-key adv` isn't good either:

```
    adv
           Pass advanced options to gpg. With adv --recv-key you can e.g. download key from
           keyservers directly into the the trusted set of keys. Note that there are no checks
           performed, so it is easy to completely undermine the apt-secure(8) infrastructure if
           used without care.
```
Maybe time to file a ticket with the `apt-key` developers? I'm not sure what the best solution is, but the currently suggested command seems quite unsatisfactory for the reasons above

**Comment by cpuguy83** [comment]
Can you open on https://github.com/docker/docker.github.io/ or complain to a docker sales rep?

Thanks!

**Comment by JonasT** [comment]
@cpuguy83 for what it's worth, it does also affect the docker-ce docs. made a ticket here: https://github.com/docker/docker.github.io/issues/8341
