### ISSUE TITLE
refusing to load key from delegation.key: private key file delegation.key must not be readable or writable by others

### ISSUE THREAD

**Issue by GodofGurus** [moby/moby#38771]
**Description**

Can not load delegation key 

**Steps to reproduce the issue:**
1.openssl genrsa -out delegation.key 2048
2.openssl req -new -sha256 -key delegation.key -out delegation.csr
3.openssl x509 -req -sha256 -days 365 -in delegation.csr -signkey delegation.key -out delegation.crt
4. C:\test> docker trust key load delegation.key --name tester
Loading key from "delegation.key"...
refusing to load key from delegation.key: private key file delegation.key must not be readable or writable by others
**Describe the results you received:**

refusing to load key from delegation.key: private key file delegation.key must not be readable or writable by others

**Describe the results you expected:**

key to be added 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
 docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2791.amd64fre.rs1_release.190205-1511)
Operating System: Windows Server 2016 Datacenter Version 1607 (OS Build 14393.2791)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: subzero
ID: IM7O:6MJT:GKDZ:6UHH:URZG:YE24:6VUX:4BPT:U2VM:WGWM:IS23:6WMA
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2019-02-21T14:40:03.2108863-05:00
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by GodofGurus** [comment]
Tried on both Linux and Windows

**Comment by cpuguy83** [comment]
> private key file delegation.key must not be readable or writable by others

Did you check the permissions on the file? `chmod 600 delegation.key`

In any case, if this is a real issue it should be in github.com/docker/cli
Closing this one here, thanks! 🙇

**Comment by GodofGurus** [comment]
chmod worked on linux but icacls did not work on windows. re-opening in docker/cli
