### ISSUE TITLE
After running 45 minutes, the docker ps CREATED and STATUS time error

### ISSUE THREAD

**Issue by getong** [moby/moby#38807]
docker 18.09.2
After running 45 minutes, the docker ps CREATED and STATUS time error , it turns out that 
```
About an hour ago
```
But it actually only 45 minutes. It might be a bug in the time status.

**Comment by thaJeztah** [comment]
I think the "human time" may be rounding times after 45 minutes (e.g. after 46 minutes, it will round at the next `15 minutes`, after that, round on `60 minutes` / `1 hour`, and so on).

This could also be if the clock of the host that the daemon runs on is out of sync with your local clock (the "duration" is calculated on the client; which is something we should address, but hasn't been a high priority)

What platform are you running on? Is docker running locally, or "remote" (or in a VM?).

You can check the clock on the daemon, by checking the date/time inside a container;

```
docker run --rm busybox date
```

Compare that with the date/time on your local machine (`date`) to check if the clocks are out of sync.

**Comment by getong** [comment]
My host is debian 9 amd64, not VM, docker runs locallly.
My docker container clock is in Shanghai timezone, but the time is the same with my host os. 
I run many times and find out this bug.

**Comment by thaJeztah** [comment]
Looking at the code, I think this is actually expected; https://github.com/docker/go-units/blob/57ccf259e39e1e6d33ebc140814166820abb4c6f/duration.go#L19-L34

```go
// HumanDuration returns a human-readable approximation of a duration
// (eg. "About a minute", "4 hours ago", etc.).
func HumanDuration(d time.Duration) string {
if seconds := int(d.Seconds()); seconds < 1 {
return "Less than a second"
	} else if seconds == 1 {
return "1 second"
	} else if seconds < 60 {
return fmt.Sprintf("%d seconds", seconds)
	} else if minutes := int(d.Minutes()); minutes == 1 {
return "About a minute"
	} else if minutes < 46 {
return fmt.Sprintf("%d minutes", minutes)
	} else if hours := int(d.Hours() + 0.5); hours == 1 {
return "About an hour"
	} else if hours < 48 {
return fmt.Sprintf("%d hours", hours)
	} else if hours < 24*7*2 {
return fmt.Sprintf("%d days", hours/24)
	} else if hours < 24*30*2 {
return fmt.Sprintf("%d weeks", hours/24/7)
	} else if hours < 24*365*2 {
return fmt.Sprintf("%d months", hours/24/30)
	}
return fmt.Sprintf("%d years", int(d.Hours())/24/365)
}
```

If the container is running for

- `< 1 seconds` - it shows "less than a second"
- `1 second` - it shows "1 second"
- More than a second, but under a minute; show number of seconds it's been running
- Less than 46 minutes; show number of minutes it's been running
- Less than 48 hours; it will use a precision of "hours" 
- and so on

In older versions of Docker it would use minutes _until_ it reached 1 hour, but that changed in https://github.com/docker/go-units/pull/22 (which started rounding after 46 minutes).

So, looking at this, this is working as designed. If you _do_ need the exact duration, you can use `docker container inspect` (or the API), to get the underlying fields, e.g.

```
docker container inspect --format '{{.Created}}' mycontainer
2019-02-28T10:15:39.6006747Z

docker container inspect --format '{{json .State}}' mycontainer State

{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 143,
  "Error": "",
  "StartedAt": "2019-02-28T10:15:40.4890903Z",
  "FinishedAt": "2019-02-28T10:44:50.8627412Z"
}

```

**Comment by getong** [comment]
Thanks.

**Comment by thaJeztah** [comment]
Addressing this in https://github.com/docker/go-units/pull/34
