### ISSUE TITLE
Cache not used if docker build is run on different hosts

### ISSUE THREAD

**Issue by romangrothausmann** [moby/moby#38815]
What is the current status on using cache for docker builds on different hosts?

Using GitLab CI I noticed that if caching is used in multi-stage builds and functions correctly on one host (e.g. by using a runner tag) caching from the images does not work if the built is run by a runner on a different host.

Fore example this built (job) used a custom runner, leveraging build caches as expected:
https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/169875266
whereas this built job (for the same git-commit) used a shared runner from GL and for some reason did not use the cache provided by exactly the same images (according to the SHAs):
https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/169882202

In both jobs the same SHAs are reported for the cache images:
```
docker:stable: 683afd3e5d5f8904fb8aa7874a84325970ac82b720d02336a380a77f874bc51e
registry.gitlab.com/romangrothausmann/dind-sikuli/master:system-latest: ff7fca3a1f3e6587807d41848fc4c3510181c28fbca64b1066fceffdc88a5f26
registry.gitlab.com/romangrothausmann/dind-sikuli/master:builder-latest 091c8818a462570a844721cd61bcbb9260821a57c5e392589436f918a491b41d
registry.gitlab.com/romangrothausmann/dind-sikuli/master:test f565c61fedd23957dafe8ee864e252240166bede9a0c6a070d04964b8b3b1913
```

In the custom runner job the building starts with:
https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/169875266/raw
```
Status: Downloaded newer image for docker:stable
 ---> 8044a7b7add7
Step 2/2 : RUN apk add --update --no-cache     curl
 ---> Using cache
 ---> 8df41a120c91
```
however in the GL runner building starts with:
https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/169882202/raw
```
Status: Downloaded newer image for docker:stable
 ---> 8044a7b7add7
Step 2/2 : RUN apk add --update --no-cache     curl
 ---> Running in 34ba059a4a77
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/4) Installing nghttp2-libs (1.35.1-r0)
(2/4) Installing libssh2 (1.8.0-r4)
(3/4) Installing libcurl (7.64.0-r1)
(4/4) Installing curl (7.64.0-r1)
Executing busybox-1.29.3-r10.trigger
OK: 7 MiB in 19 packages
Removing intermediate container 34ba059a4a77
 ---> 7f034b1d017d
```

These are some issues that seem related but are either quite old or the final reason discussed seems not to be related to different hosts:
https://github.com/moby/moby/issues/35286
https://github.com/moby/moby/issues/22600
https://github.com/moby/moby/issues/20316
https://github.com/moby/moby/issues/31613

It is said here:
https://stackoverflow.com/questions/45238429/docker-caching-how-does-it-really-work#45246760
> The build command needs to be run against the same docker host where the previous image's cache exists.

but I could not find any info on that in the docker docs. 
If that is actually the case it would be great to have some info on that and the reasons for it in the docker docs.
Is there any way to make use of cache images across different hosts?

**Comment by thaJeztah** [comment]
@tonistiigi @akihirosuda will this be addressed by the distributed build cache of buildkit?

**Comment by romangrothausmann** [comment]
Many thanks @thaJeztah for taking a look. So this host dependence is not expected?

**Comment by romangrothausmann** [comment]
Just triple checking running a 3rd job using the custom runner again now using the images from the shared runner for caching, however same problem: cache not used:
https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/169923734

**Comment by thaJeztah** [comment]
Host dependency may still be a thing when using the "classic" builder, but BuildKit has features to share cache through a registry, but I'm not sure if that's solving this exact use case, so I asked the BuildKit maintainers to have a look as they have more insight into that

**Comment by romangrothausmann** [comment]
Thanks @thaJeztah for that info. So is host dependency a know issue/feature for the "classic" builder? Is there any documentation about that somewhere in the docker docs?

**Comment by tonistiigi** [comment]
If this question is about `cache-from` then this does not work for multi-stage builds in the legacy builder, or more precisely it only works if you provide cache for all the stages in the multi-stage build.

**Comment by thaJeztah** [comment]
Ah, you're right, overlooked the multi-stage part; I think there's an issue discussing that

**Comment by romangrothausmann** [comment]
Many thanks @tonistiigi for your reply, concerning:

> provide cache for all the stages in the multi-stage build.

I do provide cache for all stages (https://gitlab.com/romangrothausmann/dind-sikuli/blob/9047920a431e5292f69121df66642c11cec411da/.gitlab-ci.yml#L23-48 and caching works if a runner of the same host is used) but the problem already appears for the first stage. In both cases docker build starts with docker:stable (same SHA: 683afd3...) and caches from master:system-latest (ff7fca... which was built with the custom runner) then for the GL-runner the second step (https://gitlab.com/romangrothausmann/dind-sikuli/blob/9047920a431e5292f69121df66642c11cec411da/Dockerfile#L6-7) is already not using the cache (see above).
So if that is expected, what is the reason? 
What host dependence is causing the cache invalidation here? 
Does docker take kernel versions or similar specifics into account when invalidating cache?

I saw that some provide the base image i.e. here docker:stable via `--cache-from` as well, however that is definitely built on a different host for both runners, and in the above example was used with the very same SHA (so no update to docker:stable in between). 
Is some meta-data used for cache invalidation that does not enter the computation of the image SHA?

**Comment by ericparton** [comment]
I'm seeing the same behavior even without using multi-stage builds. Is this a known issue?

**Comment by romangrothausmann** [comment]
@ericparton I think it is a known issue, but it would be nice to understand why.
@tonistiigi @thaJeztah do you have any answers on:

> So if that is expected, what is the reason?
What host dependence is causing the cache invalidation here?
Does docker take kernel versions or similar specifics into account when invalidating cache?
Is some meta-data used for cache invalidation that does not enter the computation of the image SHA?

**Comment by Dr-Desty-Nova** [comment]
`--cache-from` doesn't work when image that docker pulls is different from the one in the cache.

Case study
--------------

If an image wasn't updated in dockerhub since the tagged build:
```
Step 1/14 : FROM centos:7
7: Pulling from library/centos
8ba884070f61: Already exists
Digest: sha256:b5e66c4651870a1ad435cd75922fe2cb943c9e973a9673822d1414824a1d0475
Status: Downloaded newer image for centos:7
Step 2/14 : RUN yum update -y &&     yum groupinstall -y 'Development Tools' &&     yum install -y wget
 ---> Using cache
 ---> 071bec3016bb
```
Cache is used.

If the image in dockerhub is newer:
```
Step 1/21 : FROM ubuntu:16.04
 ---> 13c9f1285025
Step 1/21 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in df769f231930
````
Cache is not used.

**Comment by yxliang01** [comment]
I'm also observing this issue. Is there any progress, update on this issue? Has been almost 3 month since last comment.

**Comment by AkihiroSuda** [comment]
@yxliang01 DOCKER_BUILDKIT=1

**Comment by yxliang01** [comment]
@AkihiroSuda  Unfortunately, the build machine can only run docker 18.03 which can't use `DOCKER_BUILDKIT=1`...

**Comment by AkihiroSuda** [comment]
buildx should work with older docker releases

**Comment by yxliang01** [comment]
@AkihiroSuda Just now I did some experiment with Docker 18.09, `DOCKER_BUILDKIT=1`. However, I've observed that the pulled image that was built on the other machine is not being used for caches... I might be able to provide more information if it helps. Looking for suggestions.

**Comment by AkihiroSuda** [comment]
`--build-arg BUILDKIT_INLINE_CACHE=1` (requires either Docker 19.03 or buildx)

**Comment by liejuntao001** [comment]
> `--build-arg BUILDKIT_INLINE_CACHE=1` (requires either Docker 19.03 or buildx)

THANKS! this works for me

DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from test:test --tag test:test .
docker push test:test

then the 2nd same command from different host reuses all the caches.

**Comment by alitoufighi** [comment]
@AkihiroSuda 
We are using Docker 19.03.6 with BuildKit enabled and while using `--build-arg BUILDKIT_INLINE_CACHE=1` to build a multi-stage image, the cache doesn't work when cache image is built in a different host. Is there any update since closing this issue to consider?
Our build script looks like this:
```bash
docker pull image:builder
docker build --build-arg BUILDKIT_INLINE_CACHE=1 --target build-stage --cache-from image:builder -t image:builder
docker pull image:latest
docker build  --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from image:builder,image:latest -t image:latest
```

**Comment by AkihiroSuda** [comment]
Make sure to push

**Comment by alitoufighi** [comment]
@AkihiroSuda 
Of course, after building, we push without tag specified to push all recent built tags to our repo:
```
docker push image
```
Isn't there anything else to consider? Is pushing the whole repository to registry ignores inline cache? :-?

**Comment by giovannibonetti** [comment]
Have you tried specifying the multiple `--cache-from` entries separately?
```sh
docker build \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --cache-from image:builder \
  --cache-from image:latest \
  -t image:latest
```
