### ISSUE TITLE
Questions about how docker daemon initializes the seccomp filter

### ISSUE THREAD

**Issue by oubotong** [moby/moby#38829]
**Description**

I read the original code of the moby project and read the seccomp code in the moby/profiles folder. 
I know that docker use the libseccomp-golang to support the feature. 

We usually use the libseccomp.NewFilter() API to create a seccomp filter. However, I can't see any API in the libseccomp was involved in the project except the libseccomp.GetNativeArch() which can be seen in the moby/profiles/seccomp/seccomp.go file. 

So I am wondering how does the docker daemon initialize the seccomp filter for each container? Please correct me if I am wrong.

**Comment by thaJeztah** [comment]
docker includes the profile in the OCI spec, which gets sent to runc, which sets up the profile.

Let me close this ticket for now, as it looks like it went stale.
