### ISSUE TITLE
Feature Request: COPY files into the same directory structure

### ISSUE THREAD

**Issue by kylekthompson** [moby/moby#38826]
**Description**

While attempting to optimize a few Dockerfiles at work, I ran into a situation where I would have liked to be able to copy specific files from many directories into the same directory/file structure. It seems like I'm unable to do this unless I manually specify each directory and create additional layers (1 `COPY` command per directory).

I noticed that [there is an issue that mentions we can't do this because it'd break backwards compatibility](https://github.com/moby/moby/issues/15858), so I instead propose the following: I'd like to be able to reference capture groups from the first part of the `COPY` command (e.g. `COPY gems/([^/]+)/*.gemspec /workdir/gems/$1/`- pardon the possible Go path match typos).

For a more visual example, suppose we had the following tree:

```bash
$ tree gems -P "*.gemspec" -L 2
gems
├── sample1
│   ├── config
│   ├── lib
│   ├── spec
│   └── sample3.gemspec
├── sample2
│   ├── config
│   ├── lib
│   ├── spec
│   └── sample2.gemspec
└── sample3
    ├── config
    ├── lib
    ├── spec
    └── sample3.gemspec
```

The `COPY` command I proposed would ideally create:

```bash
workdir
└── gems
    ├── sample1
    │   └── sample3.gemspec
    ├── sample2
    │   └── sample2.gemspec
    └── sample3
        └── sample3.gemspec
```

**Comment by thaJeztah** [comment]
Looks like this may be similar to https://github.com/moby/moby/issues/35639 and https://github.com/moby/moby/issues/38710 (see https://github.com/moby/moby/issues/38710#issuecomment-462734118)

If doubt the regex would be implemented though; as an alternative, perhaps that could be handled with the [`RUN --mount` option](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#experimental-syntaxes) that BuildKit provides;

```Dockerfile
# Mount the build-context; any Linux command could now be used to use/copy those files
RUN --mount=type=bind,target=/gems cp ........
```

**Comment by kylekthompson** [comment]
Sorry I didn't see those! Tough to search for these 😅 

Hm, didn't know about the `RUN --mount` option. I'll definitely look into that- very much appreciated (and thanks for the fast reply!). I'll go ahead and close this for now then 👍
