### ISSUE TITLE
Dockerd trying to use systemd cgroup even if system booted without systemd

### ISSUE THREAD

**Issue by iyesin** [moby/moby#38822]
**Description**
Docker is built on test system. Test system have no systemd on it (gentoo with USE='-systemd' in make.conf and LFS). Kernel supports systemd, but init isn't systemd.
Dockerd starting normally. Every attempt to run any image ends up with message like
```docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.```

**Steps to reproduce the issue:**
1. Start VM from `http://distfiles.gentoo.org/releases/amd64/autobuilds/20190228T214502Z/install-amd64-minimal-20190228T214502Z.iso`
2. Use stage3 from `http://distfiles.gentoo.org/releases/amd64/autobuilds/20190228T214502Z/stage3-amd64-20190228T214502Z.tar.xz` to install system
3. reboot
4. Add `-systemd` to USE flags
5. `emerge =app-emulation/docker-18.09.2`
6. `rc-config restart docker`
7. `docker run --rm -it alpine:3.9`

**Describe the results you received:**
```docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.```

**Describe the results you expected:**
command prompt

**Additional information you deem important (e.g. issue happens only occasionally):**
See **Steps to reproduce**

**Output of `docker version`:**

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        6247962
 Built:             Mon Feb 11 21:25:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       6247962
  Built:            Mon Feb 11 21:24:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0                                                                                                                                                
 Running: 0               
 Paused: 0                           
 Stopped: 0
Images: 18         
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs 
 Supports d_type: true
 Native Overlay Diff: true         
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683b971d9c3ef73f284f176672c44b448662
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.20.11-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: chest
ID: IPTS:OMOR:SGAA:N7PQ:S2UA:QCWX:2364:Q3HW:LVZZ:3VM3:J5RC:Y2OM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
any environment I tried.

**Comment by thaJeztah** [comment]
the `docker info` output shows that dockerd is using `cgroupfs`, not systemd cgroups

```
Cgroup Driver: cgroupfs
```

Is there anything useful in the logs?

**Comment by iyesin** [comment]
> output shows that dockerd is using `cgroupfs`, not `systemd` cgroups
Exactly!
It can't spin up any container without `/sys/fs/cgroup/systemd` being mounted thou.
Unfortunately, nothing useful in logs.
This problems immediately solves when I'm mounting `/sys/fs/cgroup/systemd` but this lightens up hard-coded or very implicit dependency somewhere in code dockerd code.

**Comment by thaJeztah** [comment]
So the only location where this error is generated is in https://github.com/moby/moby/blob/98e23f2a8ef5703861eb98bf78c0354f2ece8c0f/vendor/github.com/containerd/cgroups/utils.go#L235-L254

Which (at a quick glance) doesn't seem to be called in the `dockerd` codebase, so possibly this error is trickling up from `containerd` 🤔


Does it work if you create and run a container directly using `containerd`?


```bash
ctr image pull docker.io/library/hello-world:latest

ctr container create docker.io/library/hello-world:latest mycontainer

ctr task start mycontainer
```

**Comment by misterunknown** [comment]
I have the same problem using alpine linux (edge) with docker 19.03.

**Comment by cpuguy83** [comment]
"I have the same problem" isn't very useful.
Can you provide any extra info like what @thaJeztah asked about?
🙏😇

**Comment by misterunknown** [comment]
> "I have the same problem" isn't very useful.

Indeed, sorry :man_facepalming:

My `Cgroup driver` is also `cgroupfs` and I also have nothing in the logs. However, I investigated on this issue and @thaJeztah is right: The error message originates from `containerd`. I traced the process and stumbled across this section:
```
841   newfstatat(AT_FDCWD, "/sys/fs/cgroup", {st_mode=S_IFDIR|0755, st_size=280, ...}, 0) = 0
841   statfs("/sys/fs/cgroup", {f_type=TMPFS_MAGIC, f_bsize=4096, f_blocks=2560, f_bfree=2560, f_bavail=2560, f_files=2042805, f_ffree=2042792, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=40
96, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_NOEXEC|ST_RELATIME}) = 0
841   openat(AT_FDCWD, "/proc/self/cgroup", O_RDONLY|O_CLOEXEC) = 7
841   epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2743557176, u64=139932778060856}}) = -1 EPERM (Operation not permitted)
841   epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc0001224ac) = -1 EPERM (Operation not permitted)
841   read(7, "12:name=systemd:/\n11:pids:/\n10:n"..., 4096) = 163
841   read(7, "", 3933)                 = 0
841   close(7)
```
I was really confused, because `systemd` really shouldn't appear in `/proc/self/cgroup`, but it somehow does. Even if I check this file from a normal shell, `systemd` seems part of it:
```
root@docker [~]# cat /proc/self/cgroup 
12:name=systemd:/
11:pids:/
10:net_prio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/sshd
0::/sshd
root@docker [~]#
```
Now I'm investigating how the `systemd` cgroup appears there (don't have an idea, yet).

I guess if @iyesin checks the contents of `/proc/self/cgroup` from a shell on his system, he might see something similar. As far as I'm concerned this seems to be neither a `dockerd`, nor a `containerd` problem.

**Comment by paddy-hack** [comment]
FYI, on my system I get
``` console
paddy-hack@boson:~$ cat /proc/self/cgroup
13:name=elogind:/1
12:rdma:/
11:pids:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
0::/slim
```
Running Devuan 3.0.0 (beowulf) with Docker.com's `docker-ce` (for Debian 10 (buster)).  No `systemd` in sight but `elogind` is filling in the most pertinent gaps without undue entanglement.
``` console
paddy-hack@boson:~$ dpkg-query -W | grep -E '(system|elogin)d'
elogind	241.4-2
libelogind0:amd64	241.4-2
libpam-elogind:amd64	241.4-2
libpolkit-gobject-elogind-1-0:amd64	0.105-25+devuan8
```
FWIW, the `1` in `13:name=elogind:/1` appears to correspond to a file in `/run/systemd/sessions/` making me think it may come from `libpam-elogind`.

@misterunknown Do you have `libpam-systemd` installed?

**Comment by paddy-hack** [comment]
Now the curious thing for me is that after I run `minikube start` (successfully if I may believe the output of `minikube status`) I see an extra
```
14:name=systemd:/
```
at the top of `/proc/self/cgroup` and I'm no longer able to run even a simple
``` console
paddy-hack@boson:~$ docker run hello-world
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
ERRO[0002] error waiting for container: context canceled 
```
For clarity's sake, this works *before* running `minikube start`.

Running the advice below (from https://github.com/docker/for-linux/issues/219#issuecomment-375160449) puts things back in "working order".
``` console
paddy-hack@boson:~$ sudo mkdir /sys/fs/cgroup/systemd
paddy-hack@boson:~$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```
I also noticed that I have an `/sys/fs/cgroup/elogind`.

/cc @afbjorklund

**Comment by misterunknown** [comment]
@paddy-hack No, I run entirely on alpine linux, and there is no such package. Tbh, I simply mount the systemd cgroup, even if I don't use systemd, just to make it work. I didn't find the time to further investigate, yet.

**Comment by worldomkar** [comment]
I must mention that I observed and fixed a similar issue while creating a cloud-init custom image for alpine-edge. I found this is fixed once docker "starts after" for "openerc default". If docker starts before openerc, it results in the mentioned cgroups error.
