### ISSUE TITLE
Performance difference between cpuset-cpu and cpu-quota & cpu-period

### ISSUE THREAD

**Issue by alex1993** [moby/moby#38839]
Hey guys,
  I'm facing a performance issue about docker when training models. Here are some details.

Scenario:

1. Using docker to run tensorflow training tasks.
2. Eliminate GPU and use tensorflow CPU only to control variables. 

Environment:
1. Centos 7: Kubernetes 1.9.5 & Docker 1.12
2. Centos 7: Docker 1.13
3. Windows Server 2016: Docker 18.09.2 & Kubernetes 1.10.11

Usage:
1. Use K8s to request and limit 1 CPU for container
2. Use docker command: `docker run –cpuset-cpus=0 image command` to limit 1 CPU for container
3. Use docker command: `docker run –cpu-period=100000 –cpu-quota=100000 image command` to limit 1 CPU for container
4. Use docker command: ` docker run –cpus=0 image command ` to limit 1 CPU in Docker(version >= 1.13).
5. Increase number of CPU, difference of performance decreases gradually. In our Named Entity Recognition task, performance loss vanishes when using 4 CPUs.

Observation:

1. The first method runs 4 times slower than the second one.
2. K8s calls docker API actually. When using the first method, K8s limits CPU usage by cpu-period=100000, cpu-quota=100000
3. In order to control environment differences, we tried the third way by running raw docker commands.
We found the first one and the third one had same performance loss comparing with the second one.
Problems still exist even switching to different environments.
4. When running on a 8 core machine, the first and the third method will try to split CPU requirements to 8 cores, making usage of each core up to about 12.5%. While the second one control one specific CPU monopoly.
5. The forth method will try to schedule task to 8 CPUs as well, however using a different parameter: NanoSec=1 000 000 000, but outperforms the second and the third ones both.

Problems:
  What’s the gap between the second, the third and the forth usage? Since Docker and K8s claim that they both obtain computation power of one CPU, however their performances vary tremendously.

**Comment by cpuguy83** [comment]
cpuset only pins the container to a cpu (or set of cpu) core but does not throttle access to the core, there may or may not be contention with other tasks in this case.

Adjusting period/quota sets the amount of cpu time. The `--cpus` flag just sets period and quota such that the CPU time that is allowed equals the number of cpus you requested.

**Comment by zq-david-wang** [comment]
CPU throttle has significant performance impact on compute intensive applications,  I test with 2 thread computing pi, all with a 1 cpu limit (quota = period = 100000), the run with two separate cpu core is about 50% slower than the run with two threads on a single core.... cpu.stat file under  container cpu cgroup path would show huge number for throttled_time.  Common suggestion would be either increase your cpu limit or restrict your number of threads for computing.

**Comment by cpuguy83** [comment]
@zq-david-wang If nothing else then I would cache locality would play a huge role here in the case of multiple threads on a single core being much faster. Possibly SMT as well.

**Comment by cpuguy83** [comment]
In any case, I don't think this is related to any particular issue with moby so I am going to close this, but feel free to discuss.

**Comment by kobigi** [comment]
Hi Guys
well having similar issue while running ceph osd's inside a container,
specifying the cpu-quoate .. 10000 is limiting the perfromance of teh processes and making it incosistent.
So after removing the quota we get better results
The questions are:
1. why ?
2. right now that i'm running with cpuset-cpus only without the quota like below
--net=host --privileged=true --pid=host --memory=5g --cpuset-cpus=0,1,36,12,24,25
should i specify also --cpus flag ?

**Comment by cpuguy83** [comment]
Quota is a low-level kernel tunable. It sets the amount of cpu time allotted per period ("period" being another configurable").

The "--cpus" option is a higher level option which configures quota/period  based on the number of cores on the system and the number of cores you requested... it doesn't actually give the container N cores but rather   the cpu time equivalent of the number of cores you requested.
