### ISSUE TITLE
Exec process doesn't preserve init process uid/gid/additionalgids since 18.06

### ISSUE THREAD

**Issue by Random-Liu** [moby/moby#38865]
**Description**

**Steps to reproduce the issue:**
```console
$ docker run --group-add 1234 busybox id -G
0 10 1234
$ docker run --group-add 1234 -d busybox sleep 1000
ded77fec7e0bc07542037ad4a669b7ffed3211d2762fc1d3381fa84af67f28c1
$ docker exec de id -G
0
```

**Describe the results you received:**
Exec doesn't preserve uid/gid/additionalgids.

**Describe the results you expected:**
Exec should preserve it. With 17.03.2-ce:
```
$ docker run --group-add 1234 busybox id -G
0 10 1234
lantaol@e2e-test-lantaol-minion-group-cq8p ~ $ docker run --group-add 1234 -d busybox sleep 1000
87e52362a4962267f408d6646c3de4482b5f6247de5362103c309bbeadccc175
lantaol@e2e-test-lantaol-minion-group-cq8p ~ $ docker exec 87 id -G
0 10 1234
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This is introduced by https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-3ed197c0a6f7a9ca73a3ee424e448ac1.

Before updating to containerd 1.0, when init process spec is preserved by default (uid/gid/additional gids are also preserved): https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-15c000aa4859d8b3bae42251a9a13b15L61

However, after updating to containerd 1.0, the OCI `spec` is generated and passed to containerd directly https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-10e0e646b98a7523848294e49bce04ecR268, and the user field of OCI `spec` doesn't default to init process spec. (See https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-3ed197c0a6f7a9ca73a3ee424e448ac1R218 and https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-9e56cba9cecf8fa358ccc62d97eb6320R12).

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 201
Server Version: 18.09.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 217
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 075e1ed4e0bbe6219c8ebbe57deace356970f1c7.m
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1021-gcp
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 118GiB
Name: workspace
ID: ZZQS:5I4Q:LHOK:XCBD:DOTJ:3ZTN:Y7PT:JIZI:TR6M:OQSO:INDV:WOEW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL

**Comment by crosbymichael** [comment]
I'll create a PR for this fix
