### ISSUE TITLE
docker doesn't encode url when pull/push to docker registry with S3 storage driver

### ISSUE THREAD

**Issue by danielmt** [moby/moby#38884]
Docker on macOS can't pull images from a docker registry with S3 storage driver. [docker/for-mac/issues/2653](original issue)

Docker version 18.09.2, build 6247962

The value for **X-Amz-Credential** is not being encoded, resulting in:

```
error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000009eae5-005c8baf66-4d4eeb4-default</RequestId><HostId>xxxxxxxx-default-default</HostId></Error>"
```

**Comment by thaJeztah** [comment]
ping @caervs @manishtomar ptal

**Comment by caervs** [comment]
Thanks for filing danielmt.

Do you ming sharing your registry version and config (secrets redacted 😊)?

Also would be good to know if there is anything interesting about your set up like if you're going through a proxy to access s3 or if you're using an s3 clone.

**Comment by thaJeztah** [comment]
Let me close this ticket then, but feel free to continue the conversation
