### ISSUE TITLE
docker image inspect .Metadata.LastTagTime displays with incorrect format

### ISSUE THREAD

**Issue by geekofalltrades** [moby/moby#38893]
**Description**

A `docker image inspect -f {{.Metadata.LastTagTime}}` returns the datetime string in a non-compliant format.

**Steps to reproduce the issue:**
1. `docker image inspect -f {{.Metadata.LastTagTime}} <image>`

**Describe the results you received:**

A non-compliant datetime string: `2019-03-14 11:05:07.844958173 -0700 PDT`

```
$ date -d '2019-03-14 11:05:07.844958173 -0700 PDT'
date: invalid date ‘2019-03-14 11:05:07.844958173 -0700 PDT’
```

**Describe the results you expected:**

An ISO-8601-compliant datetime string: `2019-03-14T11:05:07.844958173-07:00`

This string can be found in the full JSON output:

```
$ docker image inspect hopcloud-versioner | jq -r '.[].Metadata.LastTagTime'
2019-03-14T11:05:07.844958173-07:00

$ date -d '2019-03-14T11:05:07.844958173-07:00'
Thu Mar 14 11:05:07 PDT 2019
```

**Additional information you deem important (e.g. issue happens only occasionally):**

An issue similar to this seems to have been fixed in #14164, but it doesn't look like the fix was consistently applied.

**Output of `docker version`:**

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 2052
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-42-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.62GiB
Name: onsite
ID: TUVY:HR7A:JYF7:6OKG:HCUQ:WLAM:VKUG:UD6H:QCGE:AI3W:2KT5:2GTR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 16.04.

**Comment by thaJeztah** [comment]
Does it work if you use the `json` output for the value?

```
docker image inspect -f '{{json .Metadata.LastTagTime}}` <image>
```

**Comment by geekofalltrades** [comment]
It does (after I strip the quotes):

```
$ docker image inspect myimage -f '{{json .Metadata.LastTagTime}}' | sed 's/"//g' | date -f -
Thu Mar 14 11:05:07 PDT 2019
```

Thanks, I wasn't aware of that formatting option.

**Comment by boaz0** [comment]
I'm closing this as it seems to be resolved.
But feel free to reopen it if you think differently or something is changed.

Thanks.

**Comment by flowchartsman** [comment]
I think this issue should be reopened. This behavior is markedly different from using `{{ .Created }}` not only is the timestamp different if not using `{{ json`, but even with it the extra step of stripping quotes is required.
