### ISSUE TITLE
Docker 17.05.0-ce  unable to kill unresponsive containers

### ISSUE THREAD

**Issue by yxxhero** [moby/moby#38899]
time="2019-03-19T10:20:09.568324826+08:00" level=warning msg=container kill failed because of 'container not found' or 'no such process': Cannot kill container 1100ddf3afe4db29a564d36a1b9bd71ae0579cff6fc041522dd3ab27c8768b2d: rpc error: code = 2 desc = containerd: container not found"

**Comment by boaz0** [comment]
I am afraid 17.05.0-ce is no longer supported.
Can you update to the 18.09.3 and make sure this problem is fixed?

Thanks.

**Comment by thaJeztah** [comment]
Let me close this one for now, but feel free to open a new ticket with details if you're still having this on a current version, thanks!
