### ISSUE TITLE
mkimage-yum.sh allow multiple packages & groups with spaces in name.

### ISSUE THREAD

**Issue by ajatkj** [moby/moby#38938]
Similar issue fixed earlier (commit: fa900bd30a0881772b8964ee4d91d791af5b13c8) has given rise to another issue where you can't install multiple group or packages since they . I have fixed the issue to have multiple -p and and -g options for multiple packages and groups and handle the spaces in the name properly. 

Let me know if can I raise a pull request for this change?

**Comment by thaJeztah** [comment]
feel free to open a PR (it's probably easier to discuss the changes when looking at them 🤗)

**Comment by thaJeztah** [comment]
fixed by https://github.com/moby/moby/pull/38957, thanks!
