### ISSUE TITLE
IPv4 address not assigned to bridge network interfaces

### ISSUE THREAD

**Issue by stek29** [moby/moby#38942]
**Description**
When container connected to default bridge is removed, address on `docker0` (on host side) is removed, breaking connection in containers created after such removal.
It also affects build process -- I have to use `--net=host` for reliable builds.

**Steps to reproduce the issue:**
- Check addresses on docker0 interface
- Create and remove container which uses default bridge network
- Check addresses on docker0 interface again

```
# ip addr show dev docker0
475: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:6d:a4:79:9d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

# # Start with --rm to create and remove a container connected to def. bridge
# docker run -it --rm alpine:3.9 sh -c exit

# ip addr show dev docker0
475: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:6d:a4:79:9d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::42:6dff:fea4:799d/64 scope link
       valid_lft forever preferred_lft forever
```

**Describe the results you received:**
`docker0` loses it's IPv4 address, and gains IPv6 address it didn't have before.

**Describe the results you expected:**
Addresses on `docker0` don't change.

Here's what I get on VPS:
```
# ip addr show dev docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:0b:66:a3:22 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:bff:fe66:a322/64 scope link
       valid_lft forever preferred_lft forever

# docker run -it --rm alpine:3.9 sh -c exit

# ip addr show dev docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:0b:66:a3:22 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:bff:fe66:a322/64 scope link
       valid_lft forever preferred_lft forever
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue occurs on a VM, however, I'm unable to reproduce the issue on my VPS, and I can't find why. They have same OS (Ubuntu 18.04.2 LTS with latest updates, docker installed from download.docker.com repo), same docker version.

There are two network related differences between my VPS and VM:
- VPS has public IPv6 address
- VM has 3 "public" interfaces (one is in promisc mode, and two don't even have addresses on them)

**Output of `docker version`:**

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 81
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.947GiB
Name: netbox
ID: IHXE:5466:3WLL:C672:RYC2:M3DD:TWZ3:5365:PFIZ:5V6R:3QRU:XNSB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM is VMWare ESXi VM, VPS is a box on Hetzner.

**Comment by stek29** [comment]
Some corrections:
- It's actually removed when last container attached to that network is stopped.
- It's removed even if I add an address manually
- Literally all IPv4 addresses are removed on docker0 -- even if they're not in subnet range of bridge network. However, all IPv6 addresses aren't affected.

For now the only solution is to have an always running container which does nothing and is attached to the default network.

**Comment by stek29** [comment]
Oh, it affects all bridges, not just the default one.

When I create new bridge network, IPv4 address isn't assigned at all to the new bridge interface:

```
# docker network create test
9f92c4e594fadc0df37f82f64ea86b90be6bb41d27b1cd351f0c70a6067fc15b

# ip addr show dev br-9f92c4e594fa
102: br-9f92c4e594fa: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e2:b4:3a:c1 brd ff:ff:ff:ff:ff:ff
```

When I start some container attached to that network, IPv6 address is created on it:
```
# docker run -d --rm --network=test alpine:3.9 sh -c "sleep 5"
e31603442d64d17df9c9b299c34bc3c0b855e071d7bd2f84d65ef9b198380b85

# ip addr show dev br-42760d195d8c
110: br-42760d195d8c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:c7:c7:fa:12 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::42:c7ff:fec7:fa12/64 scope link
       valid_lft forever preferred_lft forever
```

And when last container is stopped&removed, IPv6 address is still preserved:
```
# ip addr show dev br-42760d195d8c
110: br-42760d195d8c: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c7:c7:fa:12 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::42:c7ff:fec7:fa12/64 scope link
       valid_lft forever preferred_lft forever
```

However, `docker network inspect` shows both valid subnet and gateway IP:
```
# docker network inspect -f '{{.IPAM}}' test
{default map[] [{192.168.0.0/20  192.168.0.1 map[]}]}
```

And just adding that gateway IP to the bridge is enough to fix networking in containers (until last container is stopped and IP is removed again) --  iptables rules are correct.

**Comment by stek29** [comment]
Ended up doing this:

```sh
#!/usr/bin/env bash

get_interface_name() {
	name="$(docker network inspect "$1" | grep 'docker.network.bridge.name' | sed 's/.*://'|tr -d '[ ",]')"
	if [ -z "$name" ]; then
		name="br-$1"
	fi
	printf "%s" "$name"
}

get_bridge_list() {
	docker network ls -f driver=bridge | tail -n +2 | cut -d' ' -f1
}

check_ipv4() {
	test ! -z "$(ip -4 addr show "$1")"
	return $?
}

get_preferred_addr() {
	docker network inspect -f '{{.IPAM.Config}}' "$1" | sed 's/^[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\)\.0.*$/\1.1/'
}

is_network_internal() {
	docker network inspect "$1" | grep -i Internal | grep -q true
	return $?
}

main() {
	for nid in $(get_bridge_list); do
		echo "Processing $nid"
		if is_network_internal "$nid"; then
			echo "Internal, skipping"
			continue
		fi

		ifn="$(get_interface_name "$nid")"
		echo "Interface is $ifn"

		if check_ipv4 "$ifn"; then
			echo "Has ipv4 already, skipping"
			continue
		fi

		addr="$(get_preferred_addr "$nid")"
		echo "Addr: $addr"

		ip addr add "$addr" dev "$ifn"
		echo "Added addr!"
	done
}

main
```

I'd love to debug this further, but I just can't find out where docker can be removing address(es) from the interface, and I'm not sure how to track who else might be doing that.

**Comment by stek29** [comment]
I ended up switching to different distro which worked fine.

**Comment by wmark** [comment]
I'm experiencing exactly this on Ubuntu 19.10 vanilla.

**Comment by wmark** [comment]
A workaround is to attach a dummy device to `docker0` to keep it `UP`.

```ini
# /etc/systemd/network/98-docker-dummy.netdev

[NetDev]
Name=dummy0
Kind=dummy
```
```ini
# /etc/systemd/network/98-docker-dummy.network
[Match]
Name=dummy0

[Network]
Bridge=docker0
ConfigureWithoutCarrier=true
IgnoreCarrierLoss=true
;KeepConfiguration=static

[Link]
RequiredForOnline=no
```

An `Address` is not needed, but could be configured. I didn't check, but it's possible your *systemd* will complain if `docker0` does not (yet) exist. In that case create the bridge as well. Docker will reconfigure it (but you'll need to set `--bridge=docker0`).

```ini
# /etc/systemd/network/97-docker0.netdev
[NetDev]
Name=docker0
Kind=bridge
```

**Comment by jrajahalme** [comment]
Had similar issue with Ubuntu 18.04 & 20.04 with default networking (bridge). Turned our I had a volume mount (`-v`) where the source directory did not yet exist in the host, somehow causing the container IP not getting configured. Added `mkdir` to create the directory before `docker run` and the container got its IPv4 address configured. `bridge0` had IPv4 address oon it all the time.

**Comment by Arturo-at-tyc-gis** [comment]
> Oh, it affects all bridges, not just the default one.
> 
> When I create new bridge network, IPv4 address isn't assigned at all to the new bridge interface:
> 
> ```
> # docker network create test
> 9f92c4e594fadc0df37f82f64ea86b90be6bb41d27b1cd351f0c70a6067fc15b
> 
> # ip addr show dev br-9f92c4e594fa
> 102: br-9f92c4e594fa: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
>     link/ether 02:42:e2:b4:3a:c1 brd ff:ff:ff:ff:ff:ff
> ```
> 
> When I start some container attached to that network, IPv6 address is created on it:
> 
> ```
> # docker run -d --rm --network=test alpine:3.9 sh -c "sleep 5"
> e31603442d64d17df9c9b299c34bc3c0b855e071d7bd2f84d65ef9b198380b85
> 
> # ip addr show dev br-42760d195d8c
> 110: br-42760d195d8c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
>     link/ether 02:42:c7:c7:fa:12 brd ff:ff:ff:ff:ff:ff
>     inet6 fe80::42:c7ff:fec7:fa12/64 scope link
>        valid_lft forever preferred_lft forever
> ```
> 
> And when last container is stopped&removed, IPv6 address is still preserved:
> 
> ```
> # ip addr show dev br-42760d195d8c
> 110: br-42760d195d8c: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
>     link/ether 02:42:c7:c7:fa:12 brd ff:ff:ff:ff:ff:ff
>     inet6 fe80::42:c7ff:fec7:fa12/64 scope link
>        valid_lft forever preferred_lft forever
> ```
> 
> However, `docker network inspect` shows both valid subnet and gateway IP:
> 
> ```
> # docker network inspect -f '{{.IPAM}}' test
> {default map[] [{192.168.0.0/20  192.168.0.1 map[]}]}
> ```
> 
> And just adding that gateway IP to the bridge is enough to fix networking in containers (until last container is stopped and IP is removed again) -- iptables rules are correct.

I can't believe that having a dummy container linked to that network enabled internet connection inmy docker compose networks. Certainly an issue I hadn't faced before...
