### ISSUE TITLE
the number of open file descriptor getting increased while get info from ContainerStats

### ISSUE THREAD

**Issue by yogihardi** [moby/moby#38950]
**Description**

I tried to get information from ContainerStats, but the open file descriptor on host is getting increased and after a while I got `too many open file` exception

https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/client/container_stats.go#L12

**Steps to reproduce the issue:**
1. run a container, ie. nginx
```
docker run --name tmp-nginx-container -d nginx
```

2. run the following golang code:
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/docker/docker/client"
)

func main() {
	dckr, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	loopNumber, err := strconv.Atoi(os.Args[2])
	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < loopNumber; i++ {
		data := stats(dckr, os.Args[1])

		fmt.Println(data)
		time.Sleep(1 * time.Second)
	}
}

func stats(dckr *client.Client, containerID string) string {
	ctx := context.Background()
	stat, err := dckr.ContainerStats(ctx, containerID, true)
	if err != nil {
		panic(err)
	}

	js, err := json.Marshal(stat)
	if err != nil {
		panic(err)
	}

	return string(js)
}
```

*command to run:*

```
$> ./main <containerID> 1100
```
3. monitor the open file descriptor with the following code:

```
$> vi openfile-2.sh
$> yes 'lsof | grep "/var/run/docker.sock" | wc -l; sleep 2' | /bin/sh
```

**Describe the results you received:**
please check the bottom left panel, the number of open file descriptor getting increased, and after a while I got the following exception:

```
panic: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/7218e95b7cc7/stats?stream=1: dial unix /var/run/docker.sock: socket: too many open files
```

![Screen Shot 2019-03-27 at 15 04 37](https://user-images.githubusercontent.com/5801107/55059594-e432c500-50a1-11e9-9f92-92889c3d8628.png)

**Describe the results you expected:**
the open file descriptor should not increase like `docker stats` cli behaviour.

here the open file descriptor number of `docker stats` cli command (still stay low)

![Screen Shot 2019-03-27 at 15 09 03](https://user-images.githubusercontent.com/5801107/55059720-4a1f4c80-50a2-11e9-9de2-e05aafa5afee.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

*docker library version:* 

```
- package: github.com/docker/docker
  version: v17.05.0-ce-rc3
```

*file descriptor:*

```
$>ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7846
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7846
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.25-yocto-standard
Operating System: (morty)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.95GiB
Name: 08002712d312
ID: CGWJ:5FTW:5GMI:WZPS:ZZMV:46D6:AJLD:PFW7:G4RF:MAPN:CFK6:XU4E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 localhost:5000
 127.0.0.0/8
Registry Mirrors:
 http://localhost:5000/
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Does it help if you disable _streaming_ ?

```go
stat, err := dckr.ContainerStats(ctx, containerID, false)
```

**Comment by thaJeztah** [comment]
Oh, actually; looks like you're not closing the response body; if you do, the problem should not occur;

```go
func stats(dckr *client.Client, containerID string) string {
	ctx := context.Background()
	stat, err := dckr.ContainerStats(ctx, containerID, false)
	if err != nil {
		panic(err)
	}
	defer stat.Body.Close()

	js, err := json.Marshal(stat)
	if err != nil {
		panic(err)
	}

	return string(js)
}
```

Note that `v17.05.0-ce-rc3` is very old; I'd highly recommend to either pick current master, or if you want to use a tagged version that matches a Docker release, to use a tag from https://github.com/docker/engine/releases (but _import_ it as `github.com/docker/docker`)

Looking at the above, I don't think there's a bug at hand here, so I'll close this issue, but feel free to continue the conversation

**Comment by yogihardi** [comment]
thanks @thaJeztah for the quick responses,

yes, it works, but I just curious, is there any reasons don't put the body close inside `ContainerStats` function? so we don't to close it manually outside?

> Note that v17.05.0-ce-rc3 is very old; I'd highly recommend to either pick current master, or if you want to use a tagged version that matches a Docker release, to use a tag from https://github.com/docker/engine/releases (but import it as github.com/docker/docker)

thanks, I will use that.

**Comment by thaJeztah** [comment]
When steaming, the body is kept open to read the stream; https://github.com/docker/cli/blob/bf4a96e5640f86860e68622d2498039d86bf5714/cli/command/container/stats_helpers.go#L70

**Comment by yogihardi** [comment]
hi @thaJeztah,

thank you for your explanation.
