### ISSUE TITLE
COPY and ADD with multiple <src> do not invalidate cache if Docker Buildkit is turned on.

### ISSUE THREAD

**Issue by Antiarchitect** [moby/moby#38964]
**Description**
BUG REPORT INFORMATION

**Steps to reproduce the issue:**
1. Use Dockerfile with `ADD 1.txt 2.txt ./`
2. Build it with DOCKER_BUILDKIT=1
3. Change 2.txt content
4. Build again

**Describe the results you received:**
The result of the ADD step is cached

**Describe the results you expected:**
ADD step should not be cached

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/Antiarchitect/docker-buildkit-bug - Repo where you can reproduce

**Output of `docker version`:**

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 507
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.0.3-200.fc29.x86_64
Operating System: Fedora 29 (Twenty Nine)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: localhost.localdomain
ID: P5EM:M6NC:P7AY:35ET:CJUH:AITQ:CENP:LJB7:4IOL:ZQMC:YVJG:F7OK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: antiarchitect
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for the detailed report!


I'm actually not able to reproduce the issue; here's the steps I used to reproduce;


First, try the non-buildkit case:

```bash
docker rmi buildkitbug:test alpine:3.9
docker image prune -f
docker builder prune -a -f

export DOCKER_BUILDKIT=0
./test.sh 2>&1 | grep -B1 cache
```

Produces only the expected "cached" step:

```
Step 2/4 : WORKDIR /app
 ---> Using cache
```


Running again, with buildkit enabled:

```
docker rmi buildkitbug:test alpine:3.9
docker image prune -f
docker builder prune -a -f

./test-buildkit.sh 2>&1 | grep -B7 'cached: true'
```

Shows that only the expected steps are cached;

```
#5         name: "[1/3] FROM docker.io/library/alpine:3.9@sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0"
#5      started: 2019-03-28 11:51:57.888038833 +0000 UTC
#5    completed: 2019-03-28 11:51:57.88844832 +0000 UTC
#5     duration: 409.487µs
#5      started: 2019-03-28 11:51:57.903237506 +0000 UTC
#5    completed: 2019-03-28 11:51:57.903271762 +0000 UTC
#5     duration: 34.256µs
#5       cached: true
--
#4         name: "[internal] helper image for file operations"
#4      started: 2019-03-28 11:51:57.888100946 +0000 UTC
#4    completed: 2019-03-28 11:51:57.888275001 +0000 UTC
#4     duration: 174.055µs
#4      started: 2019-03-28 11:51:57.903353481 +0000 UTC
#4    completed: 2019-03-28 11:51:57.903404178 +0000 UTC
#4     duration: 50.697µs
#4       cached: true
```


Could it be that you still had a cache around from a previous run? Running the buildkit test _again_ (without cleaning the cache) would indeed cache both steps:

```
./test-buildkit.sh 2>&1 | grep -B7 'cached: true'

#7 [2/3] ADD 1.txt 2.txt ./
#7       digest: sha256:4188c6b38c608c8125a46561520a1341df478a96cc8899ede44f6ac442bc1018
#7         name: "[2/3] ADD 1.txt 2.txt ./"
#7      started: 2019-03-28 11:57:41.242083133 +0000 UTC
#7    completed: 2019-03-28 11:57:41.242083133 +0000 UTC
#7     duration: 0s
#7       cached: true
--

#8 [3/3] RUN set -ex && cat ./2.txt
#8       digest: sha256:d149783cb2d9ce2dc55911a861a49cdef67d58860b03b0d7d47a100e8c9da816
#8         name: "[3/3] RUN set -ex && cat ./2.txt"
#8      started: 2019-03-28 11:57:41.242083133 +0000 UTC
#8    completed: 2019-03-28 11:57:41.242107479 +0000 UTC
#8     duration: 24.346µs
#8       cached: true
--

#7 [2/3] ADD 1.txt 2.txt ./
#7       digest: sha256:2d76c6506442a4dc3dbbed0d3371a10413c7c095ed88fbc1b3e9d23e509dd7d9
#7         name: "[2/3] ADD 1.txt 2.txt ./"
#7      started: 2019-03-28 11:57:41.410642152 +0000 UTC
#7    completed: 2019-03-28 11:57:41.410642152 +0000 UTC
#7     duration: 0s
#7       cached: true
--

#8 [3/3] RUN set -ex && cat ./2.txt
#8       digest: sha256:a5be1ec1ab4617ae6f21be9f777362b66e4685357d9059b8a2ebd4db1b1934c7
#8         name: "[3/3] RUN set -ex && cat ./2.txt"
#8      started: 2019-03-28 11:57:41.410642152 +0000 UTC
#8    completed: 2019-03-28 11:57:41.410664767 +0000 UTC
#8     duration: 22.615µs
#8       cached: true
```

**Comment by Antiarchitect** [comment]
Long story short initially found this in our CI/CD with far more complicated Dockerfile. When updating Gemfile.lock - ADD was cached and the build fails as it could not find a proper gem - so it's not a synthetic error. In this synthetic test, I have the same results as yours, but we're performing these steps:
```
docker rmi buildkitbug:test alpine:3.9
docker image prune -f
docker builder prune -a -f
```
I want my caches to be stored on CI/CD workers for builds speedup.

**Comment by thaJeztah** [comment]
Does the size of the `Gemfile.lock` change in those cases? wondering if there's a relation to https://github.com/moby/moby/issues/38072 / https://github.com/moby/moby/pull/38111 🤔 (although not sure if that affects BuildKit's cache when `COPY` or `ADD` is used).

@tonistiigi @AkihiroSuda any ideas?

**Comment by Antiarchitect** [comment]
It changes actually @thaJeztah

**Comment by Antiarchitect** [comment]
So the picture is that: there is a bundle update for one gem and Gemfile.lock changes slightly. But CI/CD steps are cached and rake sees a new version of a gem in Gemfile.lock but this version is not installed so it throws an error.

**Comment by tonistiigi** [comment]
> wondering if there's a relation to #38072 / #38111 🤔

No this is a different issue specific to gemfile.lock . I has been fixed in https://github.com/moby/buildkit/pull/858 and vendored into moby and 19.03 release branch.

**Comment by Antiarchitect** [comment]
OMG. Thank you for explanation @tonistiigi 
What is the current workaround? Do not use Buildkit?

**Comment by tonistiigi** [comment]
> What is the current workaround?

Copy these two files on separate lines.

```
COPY Gemfile .
COPY Gemfile.lock .
```

**Comment by Antiarchitect** [comment]
TY

**Comment by thaJeztah** [comment]
Ah! Perfect :+1:

@tonistiigi I guess it won't be possible to backport to 18.09 (as there's no release branches yet on buildkit)?

**Comment by tonistiigi** [comment]
@thaJeztah If you want I can make a release branch for docker.

**Comment by thaJeztah** [comment]
@tonistiigi that'd be great yes (that would be for `0.3.x`, right?)
