### ISSUE TITLE
We are not able to install mobi-engine on Debian 8(8.11)

### ISSUE THREAD

**Issue by Rajkumar1988** [moby/moby#38961]
Hi,

I am working on the operating system with the following config

Debian 8(8.11) with Kernel version - 4.1.15-224588-g76bd3bfa41df, CPU Architecture: armv7l

Board name is Freescale i.MX6 UltraLite

We tried installing moby engine using the below link and got the following error

https://docs.microsoft.com/bs-latn-ba/azure/iot-edge/how-to-install-iot-edge-linux-arm

Below is the error we are seeing:
Mar 27 23:29:01 imx6ul-var-dart dockerd[2452]: time="2019-03-27T23:29:01.523353228Z" level=error msg="AUFS was not found in /proc/filesystems" storage-driver=aufs
Mar 27 23:29:01 imx6ul-var-dart dockerd[2452]: time="2019-03-27T23:29:01.555788775Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded." storage-driver=overlay
Mar 27 23:29:01 imx6ul-var-dart dockerd[2452]: time="2019-03-27T23:29:01.558267138Z" level=error msg="Failed to built-in GetDriver graph devicemapper /var/lib/docker"
Mar 27 23:29:01 imx6ul-var-dart dockerd[2452]: time="2019-03-27T23:29:01.623227483Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.045554403Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.074280554Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.083604300Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.084273255Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.084477420Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Mar 27 23:29:04 imx6ul-var-dart dockerd[2477]: time="2019-03-27T23:29:04.084696086Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"

Any suggestions on fixing it pls.?

Cheers
Raj

**Comment by thaJeztah** [comment]
The Moby engine provided by Azure IoT is built by Microsoft/Azure; that package is built from closed source, and we can't provide support for those here; could you contact Microsoft support for this?
