### ISSUE TITLE
Stop auto installing kubectl.docker, it's annoying

### ISSUE THREAD

**Issue by max-rocket-internet** [moby/moby#38975]
I find it annoying that Docker automatically installs `kubectl.docker` into the path when the it starts up. There's no option to disable this and it happens even when the k8s feature is turned off.

It's annoying because it stops tab autocompletion in the shell of the `kubectl` command. i.e. I type `kub`, then `<tab>` and expect it to complete the command to `kubectl ` (with space) but because of this feature it only gets to `kubectl` (with no space). It sounds minor but if you are using `kubectl` all day like me, it's really annoying!

Currently on my Mac I run `rm -f $(which kubectl.docker)` to fix it but this is silly. It installs the file to `/usr/local/bin/kubectl.docker`

**Steps to reproduce the issue:**

1. Start Docker application
2. In a shell like bash, run `kubectl` and then `<tab>`

**Describe the results you received:**

```
$ kubectl<tab>
kubectl         kubectl.docker
```

**Describe the results you expected:**

```
$ kubectl<tab>
annotate       attach         cluster-info   cordon         describe       exec           label          plugin         rollout        taint          wait
api-resources  auth           completion     cp             diff           explain        logs           port-forward   run            top
api-versions   autoscale      config         create         drain          expose         options        proxy          scale          uncordon
apply          certificate    convert        delete         edit           get            patch          replace        set            version
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by cpuguy83** [comment]
Please open on github.com/docker/for-mac so the right people can see.
Thanks!
