### ISSUE TITLE
docker cp returns “no space left on device” if entire host filesystem is mounted

### ISSUE THREAD

**Issue by arindamchoudhury** [moby/moby#38995]
This is the definition of the docker container:

    version: '2'

    services:
        alpine-test:
           container_name: alpine-test
           image: alpine:latest
           command: tail -F /dev/null
           volumes:
               - /:/rootfs

If I try to copy a file from this container, eventually it returns "Error response from daemon: no space left on device" error:

    # docker cp alpine-test:/etc/hostname /tmp/
    # docker cp alpine-test:/etc/hostname /tmp/
    # docker cp alpine-test:/etc/hostname /tmp/
    Error response from daemon: no space left on device
    #

I am failed to find any workaround or explanation of this.

Thanks

**Comment by dangminhtruong** [comment]
That mean your host machine not enough hard disk space left. Just clean trash or remove somethings unused for get more space and this should work.

**Comment by arindamchoudhury** [comment]
@dangminhtruong host machine has enough free space.

**Comment by codebird** [comment]
df -h /tmp/

What's the output?

**Comment by codebird** [comment]
what does
 
`df -h /tmp/`

output?

**Comment by arindamchoudhury** [comment]
Here is it @codebird @dangminhtruong 
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            6.4G     0  6.4G   0% /dev
tmpfs           1.3G  139M  1.2G  11% /run
/dev/sda1        25G  3.6G   20G  16% /
tmpfs           6.4G     0  6.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
/dev/sdb         98G   36G   58G  39% /srv
overlay          98G   36G   58G  39% /srv/docker/overlay2/0cdda1b328cdfd7063791e4e8df1b817b0ae7c7de37eeef1aa13334329b37e2b/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/93ca017fbe2b89974e1f2c0d1e6aaea1fe35efda3c4756240aeef6d218052564/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/a7ee9cdd7578818041d46ae4698b17ae1635f74f8a38572123212685fcd484f0/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/8f1a3ade067f184f070d86deb47264eeaf2c6cca50de54d7a27a0919a9e9a5ab/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/88e2080939f9de668292c5b07fc47383e9c040925bb2e2e45e1d18a65578c693/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/057c89da0ad29533308915f82bf976d062edbd11624824ffaa9bce91c1b41468/merged
shm              64M     0   64M   0% /srv/docker/containers/3b809e73f0211c18fd57b449b97ca07f2f1c791465e6136454d6304cc24ad854/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/d875e6112daaf7b37d284c91499ac1a76ff1ee827b21ce055e5f61916a91fa58/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/d19f1c782dd10d78b3730c407bbff057dd612cdeba29d30fbf1f318fd164da8f/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/a6a66d7d2da48a2eddaf05406ec2d2199a0f5a51839a7f77f1e14d5d8005e972/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/8ff390f1f02ec767b1f22b4e305ede8b27a7cf864a0827c2bdbcdde9761daac8/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/4a1d1b3951370b6a56d366a2441297d0fe318fc080ee9537ebcceb978b2c949f/mounts/shm
overlay          98G   36G   58G  39% /srv/docker/overlay2/decec695e09e28ecb51bd63fc5ab78fb7b7c7394d3debc41588714b007df436c/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/c681d525535601bdb92be6beef568f84c0cb4bf202e1fbc8aedb61eabd718d65/merged
shm              64M     0   64M   0% /srv/docker/containers/dad1b4556de5de7c673d33f61d7458a22ffe6aa931b8c85de446a76a4fa2e4e4/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/97b6f03e0f67198edff7932f8ef998ecb2b42e6c2092d92e9154d8cc477c1ae9/mounts/shm
# 
# docker cp alpine-test:/etc/hostname /tmp/
# docker cp alpine-test:/etc/hostname /tmp/
# docker cp alpine-test:/etc/hostname /tmp/
Error response from daemon: no space left on device
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            6.4G     0  6.4G   0% /dev
tmpfs           1.3G  139M  1.2G  11% /run
/dev/sda1        25G  3.6G   20G  16% /
tmpfs           6.4G     0  6.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
/dev/sdb         98G   36G   58G  39% /srv
overlay          98G   36G   58G  39% /srv/docker/overlay2/0cdda1b328cdfd7063791e4e8df1b817b0ae7c7de37eeef1aa13334329b37e2b/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/93ca017fbe2b89974e1f2c0d1e6aaea1fe35efda3c4756240aeef6d218052564/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/a7ee9cdd7578818041d46ae4698b17ae1635f74f8a38572123212685fcd484f0/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/8f1a3ade067f184f070d86deb47264eeaf2c6cca50de54d7a27a0919a9e9a5ab/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/88e2080939f9de668292c5b07fc47383e9c040925bb2e2e45e1d18a65578c693/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/057c89da0ad29533308915f82bf976d062edbd11624824ffaa9bce91c1b41468/merged
shm              64M     0   64M   0% /srv/docker/containers/3b809e73f0211c18fd57b449b97ca07f2f1c791465e6136454d6304cc24ad854/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/d875e6112daaf7b37d284c91499ac1a76ff1ee827b21ce055e5f61916a91fa58/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/d19f1c782dd10d78b3730c407bbff057dd612cdeba29d30fbf1f318fd164da8f/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/a6a66d7d2da48a2eddaf05406ec2d2199a0f5a51839a7f77f1e14d5d8005e972/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/8ff390f1f02ec767b1f22b4e305ede8b27a7cf864a0827c2bdbcdde9761daac8/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/4a1d1b3951370b6a56d366a2441297d0fe318fc080ee9537ebcceb978b2c949f/mounts/shm
overlay          98G   36G   58G  39% /srv/docker/overlay2/decec695e09e28ecb51bd63fc5ab78fb7b7c7394d3debc41588714b007df436c/merged
overlay          98G   36G   58G  39% /srv/docker/overlay2/c681d525535601bdb92be6beef568f84c0cb4bf202e1fbc8aedb61eabd718d65/merged
shm              64M     0   64M   0% /srv/docker/containers/dad1b4556de5de7c673d33f61d7458a22ffe6aa931b8c85de446a76a4fa2e4e4/mounts/shm
shm              64M     0   64M   0% /srv/docker/containers/97b6f03e0f67198edff7932f8ef998ecb2b42e6c2092d92e9154d8cc477c1ae9/mounts/shm
```

**Comment by Wingsofcourage** [comment]
Same here. Did you found a solution ?

**Comment by thaJeztah** [comment]
@arindamchoudhury could you also provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue?

- provide the output of `docker version`
- provide the output of `docker info`

**Comment by kolyshkin** [comment]
Reproduced:

> Error response from daemon: mount /:/var/lib/docker/overlay2/93e01eef82486eee2edbb49cdb5c8547b49d1304560bd428fb8425afa2e67b74/merged/rootfs, flags: 0x5000: no space left on device

Here the "no space left on device" is ENOSPC error, but as it comes from mount it means "no space in kernel mounts table". This looks like mounts multiplication problem I am tackling in https://github.com/moby/moby/pull/38993

**Comment by h3c-open** [comment]
We have the same problem, did you get the solution?

**Comment by dangminhtruong** [comment]
Hi. This because you have too many networks, volumes, containers, and images in your system. Please prune network, volumes, and images that unused.

**Comment by h3c-open** [comment]
> Hi. This because you have too many networks, volumes, containers, and images in your system. Please prune network, volumes, and images that unused.

We restart docker.service, and the problem is gone

> Hi. This because you have too many networks, volumes, containers, and images in your system. Please prune network, volumes, and images that unused.

We found that the problem was just happened when the special image was loaded, and that must be reproduced after 'docker cp' was executed five times. We restart the docker.service, and the problem will gone with this container. We don not know if what configurations about this image brought this problem?

**Comment by arindamchoudhury** [comment]
it's a confirmed bug. we have to wait till it is fixed.

**Comment by h3c-open** [comment]
> it's a confirmed bug. we have to wait till it is fixed.

 According to the results I have found，it must be something special bring this.
do you know the specific conditions to trigger this bug? Can we avoid it and how ?

**Comment by arindamchoudhury** [comment]
As per my experience, this happens when I mount the whole root file system. as shown below:

> version: '2'
> 
> services:
>     alpine-test:
>        container_name: alpine-test
>        image: alpine:latest
>        command: tail -F /dev/null
>        volumes:
>            - /:/rootfs

**Comment by h3c-open** [comment]
> As per my experience, this happens when I mount the whole root file system. as shown below:
> 
> ```
> version: '2'
> 
> services:
>     alpine-test:
>        container_name: alpine-test
>        image: alpine:latest
>        command: tail -F /dev/null
>        volumes:
>            - /:/rootfs
> ```

Thank you and we have the same configuration with root file system. And without this point, everything is fine.

**Comment by thaJeztah** [comment]
From https://github.com/moby/moby/pull/38993#issuecomment-555769744 (substitute `$CT` in the examples below with the container name or id)

> a workaround is to replace `docker cp` with
> ```bash
> docker exec $CT cat /path/to/container/file > host_file
> ```
> or, if you need many files,
> ```bash
> docker exec $CT tar cf - /some/container/dir | tar xf -
> ```

Or, to copy _to_ the container;

> ```bash
> cat host_file | docker exec $CT cat > /path/to/container/file
> ```
> or, if you need many files,
> ```bash
> tar cf - files* more_files/* | docker exec $CT tar -C dest_dir xf -
> ```

**Comment by joerick** [comment]
Minor correction to the above:

```bash
cat host_file | docker exec $CT sh -c "cat > /path/to/container/file"
```

**Comment by larrycai** [comment]
`cat` doesn't work for me, it generates file with zero size

````
$ cat /usr/bin/whoami | docker exec test_container sh -c "cat > /tmp/whoami"
$ docker exec  test_container  ls -al /tmp/whoami
-rw-r--r-- 1 root root 0 Oct  2 15:39 /tmp/whoami
````

This way to copy from container works for me
````
$ docker exec test_container cat /usr/bin/whoami > /tmp/whoami
$ ls -al /tmp/whoami
-rw-r--r-- 1 user staff 39256 Oct  2 17:42 /tmp/whoami
````

**Comment by darnik22** [comment]
If you have a volume with the whole host filesystem mounetd let say under /hostfs you can do the copy from inside the container:
```docker exec $CT cp /hostfs/host-path /container-path```

**Comment by daikk115** [comment]
> If you have a volume with the whole host filesystem mounetd let say under /hostfs you can do the copy from inside the container:
> `docker exec $CT cp /hostfs/host-path /container-path`

This is right and very easy way, jut find a volume mount from `/host/path` to `/container/path` and execute the command: 

`docker exec $CT cp /container/path /new-path-in-container`

**Comment by xinfengliu** [comment]
So this issue still has not been fixed. The so-called fix attempt https://github.com/moby/moby/pull/38993 was closed long ago.

**Comment by kolyshkin** [comment]
😞 The bad news, I was not able to finish the work done in #38993, and do not have resources to work on it now.

😄 The good news, #38993 contains enough information for someone to pick up the flag that fell out of my hands.

**Comment by hao-lee** [comment]
@kolyshkin Hello. I think this problem is caused by [this commit](https://github.com/moby/moby/commit/cacd4007776672e918162936d8846eb51a5300e6). If we don't MakePrivate but create a new slave namespace instead and then do rbind/cp/umount in this new namespace, I think this problem could be addressed.
