### ISSUE TITLE
Make version tags on docker/engine semver compatible

### ISSUE THREAD

**Issue by gracenoah** [moby/moby#39007]
**Description**

The API client for docker is in the moby/moby repo. The moby/moby repo doesn't have tags. We have to import docker/engine to use the go docker API client. The tags on the docker/engine repo don't follow semver. Go mod doesn't recognize the versions. The version tags have leading zeros in the minor version.

Sorry to be filing this issue here. I don't know where else to file it since the docker/engine repo doesn't have an issue tracker.

**Steps to reproduce the issue:**
1. Try to import docker/engine as a go repo with go mod

**Describe the results you received:**
You have to reference commits by hash

**Describe the results you expected:**
Be able to import docker/engine as a dependency in Go mod without specifying a commit hash for the version

**Comment by cpuguy83** [comment]
The versions in the repo follow docker release versions, which does not follow semver.

**Comment by gracenoah** [comment]
It has been generally accepted in the Go community that go packages should use semver so that package managers know how to upgrade dependencies correctly. Since the only way to use a stable docker API client is to import docker/engine as a dependency, it would be very helpful if the repo followed semver like other go packages. If there's a different want to use the Docker API from Go, I'm open to ideas.

**Comment by cpuguy83** [comment]
The only way to use it is to specify the commit you want... more specifically the release version you want to use.
Docker does not follow semver.

The only way would be for someone to maintain a client library that practices semver.
The client in the repo follows the rest of the codebase.
