### ISSUE TITLE
Docker fails to start if it can't perform a DNS lookup on the RemoteAddr specified in /var/lib/docker/swarm/docker-status.json

### ISSUE THREAD

**Issue by niall-g** [moby/moby#39027]
**Description**
We have a few Docker Swarm clusters running in our infrastructure, and after a short network outage, one of the hosts was unable to reconnect to its Docker Swarm cluster.

The swarm cluster in question has 3 nodes: swarm-02, swarm-03, and swarm-04. The cluster was previously started using swarm-01, but this was subsequently retired and swarm-04 was added. Our puppet manifest for swarm nodes makes them join using the following command:

`docker swarm join --token ${swarm_join_token} ${swarm_master_nodegroup[0]}:2377` so it will use the hostname of the master rather than the IP address.

Earlier today, swarm-04 had some network troubles and was disconnected from the swarm. When we regained access, we could not start Docker, and the following was seen in the logs:

```
Error starting cluster component: could not find local IP address: dial udp: lookup swarm-01 on 127.0.0.1:53: no such host
```

Some digging showed the following:

```
root@swarm-04 ~ # cat /var/lib/docker/swarm/docker-state.json
{"LocalAddr":"","RemoteAddr":"swarm-01:2377","ListenAddr":"0.0.0.0:2377","AdvertiseAddr":"","DataPathAddr":"","JoinInProgress":false}
```

After replacing `swarm-01` in this with `swarm-02`, docker started as expected. We subsequently tested this a bit more thoroughly. Docker will only fail to start if it can't do a DNS lookup on the host specified in `docker-state.json` - It will start up successfully if any IP address is provided (even an unreachable one).

**Steps to reproduce the issue:**
1. Create a swarm with any number of nodes, using the manager's hostname in the `docker swarm join` command to join the other nodes
2. Replace the original manager in the swarm 
3. Attempt to restart docker on any of the swarm worker nodes

**Describe the results you received:**
Docker fails to start, and logs an error like ```Error starting cluster component: could not find local IP address: dial udp: lookup swarm-01 on 127.0.0.1:53: no such host```

**Describe the results you expected:**
Docker starts and joins the swarm

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happens if docker fails a DNS lookup on the hostname in `/var/lib/docker/swarm/docker-status.json`

**Output of `docker version`:**

```
root@swarmyboi-0003 ~ # docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:18 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
root@swarmyboi-0003 ~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 2bu1lxkba6nhu1pp8guwn3gva
 Is Manager: false
 Node Address: 192.168.4.5
 Manager Addresses:
  192.168.4.4:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.69GiB
Name: swarmyboi-0003
ID: 5LMX:MR4J:TGRE:GBXR:4K2T:RGTU:43VJ:FPZS:PVJ2:5IKK:SYEA:LJXD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All physical servers

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
