### ISSUE TITLE
Docker daemon error: "connect: network is unreachable"

### ISSUE THREAD

**Issue by shawnlsa** [moby/moby#39036]
**Description**

I just upgrade Docker from 17.06.2-ce to 18.06.3-ce. I use consul kv store for my overlay network,  setting --cluster-store and --cluster-advertise config when start docker, it works fine for version 17.06.2-ce. After docker upgraded, I got some error messages from docker daemon by chance when doing network related operation like docker login, docker pull etc. Finally, I found it may related to the overlay network, after I start/stop certain container. 

**Steps to reproduce the issue:**
1.Create a test overlay network:
docker network create \
--driver overlay \
--subnet=10.110.0.0/16 \
--gateway=10.110.0.1 \
mynet

2.Run a container using the network just created:
docker run -itd --name alpine3 --network mynet alpine

3.Disconnect or just stop the container:
docker network disconnect mynet alpine3 
or
docker stop alpine3 

4.docker login or docker pull. The error display by chance, use a loop procedure may reproduce more easily:
for i in {1..100}
do
docker login -u test -p test
done

**Describe the results you received:**
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
**Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 54.210.105.17:443: connect: network is unreachable**

**Describe the results you expected:**
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Additional information you deem important (e.g. issue happens only occasionally):**
Before disconnect or stop the container in overlay network, everything works fine. Containers could communicate with each other in the same overlay network, and docker login/pull could always success. After stop the overlay network container once (like alpine3 above), docker operation began to show network error by chance but I checked the network is fine all the time. After I restart docker daemon, everything goes well again.

I try start/stop overlay networking containers in docker swarm mode, the error never occur.

**Output of `docker version`:**

```
(paste your output here)
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
(paste your output here)
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 60
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Kernel Version: 4.9.0-0.bpo.5-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 47.16GiB
Name: ***
ID: ***
Docker Root Dir: ***
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 80
 System Time: 2019-04-09T16:16:22.103523924+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: consul://***
Cluster Advertise: ***
Insecure Registries:
***
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
