### ISSUE TITLE
Cannot push image using ipv6 address literal and port

### ISSUE THREAD

**Issue by cboylan** [moby/moby#39033]
**Description**

Docker push does not work when specifying the host as an escaped ipv6 address literal with port designation.

**Steps to reproduce the issue:**
1. `docker push [2607:ff68:100:54:f816:3eff:fe7c:e98a]:5000/zuul/nodepool:latest`

**Describe the results you received:**

`"[2607:ff68:100:54:f816:3eff:fe7c:e98a]:5000/zuul/nodepool:latest" is not a valid repository/tag: invalid reference format`

**Describe the results you expected:**

I expected docker to connect via ipv6 to tcp port `5000` at `2607:ff68:100:54:f816:3eff:fe7c:e98a` and push the image into the registry running there.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens because the [domainRegex](https://github.com/docker/distribution/blob/749f6afb4572201e3c37325d0ffedb6f32be8950/reference/regexp.go#L31-L34) in docker/distribution/regexp.go doesn't allow for the wrapping `[]`'s. I'm filing the bug here though as the desired end state is that ipv6 addresses will work and chances are fixing the regexp will just run into the next problem with using ipv6 addresses.

Though maybe we get lucky and it just works after updating the regex.

**Output of `docker version`:**

```
root@clarkb-docker-debug:~# docker version
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
root@clarkb-docker-debug:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.789GiB
Name: clarkb-docker-debug
ID: BQHT:G3FO:IKPY:7X6W:JAAK:VDK4:CD65:YOOM:LF7W:PA57:ECUB:22P6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was running on an Ubuntu 18.04 VM host with docker installed from the docker ubuntu deb repo.

**Comment by rnalrd** [comment]
bump. Any hope to get this fixed?

**Comment by jlkiri** [comment]
Bump

**Comment by thaJeztah** [comment]
DNS should work. The problem here is in code from https://github.com/distribution/distribution, which parses the reference, and which is used as a build-time dependency .

A fix for that was merged in https://github.com/distribution/distribution/pull/3489, but has not been released yet.

**Comment by artificial-intelligence** [comment]
I _think_ this would work now, I couldn't quite test this end to end just yet, because I used quay.io as a guinea pig and the TLS verification fails in the end (of course):

```
sven@notfound:~$ docker run busybox echo "fun" > newfile
sven@notfound:~$ docker ps -l
CONTAINER ID   IMAGE     COMMAND      CREATED         STATUS                     PORTS     NAMES
748775aaf91d   busybox   "echo fun"   7 seconds ago   Exited (0) 6 seconds ago             nervous_mclaren
sven@notfound:~$ docker commit 748775aaf91d [2600:1f18:483:cf01:c551:37d5:6cfd:c1c7]/svensaccount/test
sha256:81b17118005acb08a8780c471d2d6c8089d607ca6a826f6ec07670ac2c33b265
sven@notfound:~$ docker push [2600:1f18:483:cf01:c551:37d5:6cfd:c1c7]/svensaccount/test
Using default tag: latest
The push refers to repository [[2600:1f18:483:cf01:c551:37d5:6cfd:c1c7]/svensaccount/test]
Get "https://[2600:1f18:483:cf01:c551:37d5:6cfd:c1c7]/v2/": tls: failed to verify certificate: x509: cannot validate certificate for 2600:1f18:483:cf01:c551:37d5:6cfd:c1c7 because it doesn't contain any IP SANs
```

**Comment by thaJeztah** [comment]
Yeah, I think this should work now; at least parsing the format should work;

```bash
echo 'FROM busybox' | docker build -t [::1]:5000/myimage:latest -

docker push [::1]:5000/myimage:latest
The push refers to repository [[::1]:5000/myimage]
49b3a50a2039: Pushed
latest: digest: sha256:79a1955078f1b946770a44e86c517505acf9b0169078839ae3eb04e91cc26220 size: 527
```
