### ISSUE TITLE
Cannot copy to remote container through sdk

### ISSUE THREAD

**Issue by vieiramanoel** [moby/moby#39045]
Through SDK I can't copy remotely to a created container a file on my host every time I got:
``` Error: No such container:path: ec58d6684ccd070841d230bf99975c9f4776f2ec083bae6fc0e02e12f48af33e:PATH``` whatever PATH is (I've already tried /)

## Steps to reproduce the issue

1. create container

```golang

createResp, err := cli.ContainerCreate(c.dockerctx, &config, &hostconfig, nil, c.containerName)
if err != nil {
	logger.Errorf("Could not create container %s, due to error %s", c.containerName, err.Error())
	return nil, err
}
```
2. Send to created container

```golang
err = c.cli.CopyToContainer(c.dockerctx, createResp.ID, "lala", cayamlReader, types.CopyToContainerOptions{})
if err != nil {
	logger.Errorf("Could not send yaml to container %s due to error %s", c.containerName, err.Error())
	return nil, err
}
```
## Results

got error: 

` Error: No such container:path: ec58d6684ccd070841d230bf99975c9f4776f2ec083bae6fc0e02e12f48af33e:lala`

**Output of `docker version`:**

remote client
```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

host version 

```
Client:
 Version:           18.09.4-ce
 API version:       1.39
 Go version:        go1.12.1
 Git commit:        d14af54266
 Built:             Thu Mar 28 11:37:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.4-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       d14af54266
  Built:            Thu Mar 28 11:36:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**Output of `docker info` at remote:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1035-aws
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 479.9MiB
Name: ip-192-168-0-151
ID: MKB3:RX2N:JURZ:GSYE:3XPQ:T4J4:CHNW:K6R2:NTVX:A6CO:GDIQ:LKN3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Output of `docker info`:**

```
Containers: 19
 Running: 3
 Paused: 0
 Stopped: 16
Images: 177
Server Version: 18.09.4-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84.m
runc version: 69ae5da6afdcaaf38285a10b36f362e41cb298d6
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.32-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.702GiB
Name: vieirinho-pc
ID: 6PK4:N6BR:4AMJ:RBGB:MDDI:WSPF:L7IE:RO77:42PA:ODIK:GDUW:5FOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: manoelvieira
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Remote is an ec2 aws instance

**Comment by thaJeztah** [comment]
Did you have a look at the code as it's used in the Docker CLI? https://github.com/docker/cli/blob/b1d27091e50595fecd8a2a4429557b70681395b2/cli/command/container/cp.go#L182-L282

**Comment by vieiramanoel** [comment]
Ok this is absolutely usefull, thanks @thaJeztah. I'll take a look

**Comment by vieiramanoel** [comment]
On remote when I run 
`docker cp a9efcc18ab0f6cc4d6a4537e077f504f95708fbbef37145ec7165a0e72e6b393:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml .` command is successfull
But through sdk it points out that path doesn't exist when
`cli.ContainerStatPath(c.dockerctx, id, fabricServerPath)` is called
` No such container:path: a9efcc18ab0f6cc4d6a4537e077f504f95708fbbef37145ec7165a0e72e6b393:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml`

**Comment by vieiramanoel** [comment]
Found it. The reader was being read by a file write (at some debug point I made it be saved) and the 
reader was pointing out to file's end.
This said, problem was solved. Closing issue. Thank for the help once more.

**Comment by thaJeztah** [comment]
Great!

Do you think it would help if some utilities were added to the client (or another package), with parts of https://github.com/docker/cli/blob/b1d27091e50595fecd8a2a4429557b70681395b2/cli/command/container/cp.go#L182-L282 ?

**Comment by vieiramanoel** [comment]
For sure! It would help a lot if in case of nil Reader() or if Reader points out to its end sdk returns an error.

**Comment by thaJeztah** [comment]
I'm not sure if anyone from the docker team has work on that, but if you have suggestions for that, or want to draft a proposal (a pull-request with some of those changes), I guess that would help to start that discussion. (don't have to make the PR "perfect", but just to outline what it could look like)

**Comment by vieiramanoel** [comment]
Of course!

**Comment by vieiramanoel** [comment]
@thaJeztah I can't test on local, `go get` in `moby/client` returns 
```can't load package: package github.com/moby/moby/client: code in directory /home/vieirinho/go/src/github.com/moby/moby/client expects import "github.com/docker/docker/client"```
