### ISSUE TITLE
run PR jobs with DOCKER_BUILDKIT enabled

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39040]
Tracking issue to get all the PR jobs to run in an environment where we have the latest docker-ce release with buildkit enabled.

This will make sure we're exercising the buildkit build functionality and we can then take advantage of the new build capabilities provided by buildkit (caching, new front-ends, whatnot).

cc @dave-tucker @psftw @tonistiigi

**Comment by thaJeztah** [comment]
Related;

- https://github.com/moby/moby/pull/38847 Enable buildkit for Makefile build target
- https://github.com/moby/moby/pull/38415 / https://github.com/moby/moby/pull/37513 [carry 37513] Honor DOCKER_BUILDKIT in integration tests

**Comment by andrewhsu** [comment]
Just checked the nodes with jenkins label `ubuntu-1604-aufs-stable` and as of now looks like it is running with docker-ce 18.09.5.

So it looks like we can set the `DOCKER_BUILDKIT=1` to get docker builds enabled with buildkit when Jenkinsfile steps are run with this label https://github.com/moby/moby/blob/4d7721cdcc224c6af191ae3a191a9a78655b45ee/Jenkinsfile#L117

@dave-tucker @psftw just need to hook up the Jenkinsfile to jenkins

**Comment by andrewhsu** [comment]
I’ve set `DOCKER_BUILDKIT=1` for the jenkins jobs:
• Docker Master https://jenkins.dockerproject.org/job/Docker%20Master/
• Docker-PRs (aka janky) https://jenkins.dockerproject.org/job/Docker-PRs/
• Docker-PRs-experimental https://jenkins.dockerproject.org/view/Docker/job/Docker-PRs-experimental/

And PR #39592 has added the environment variable to `Jenkinsfile`.
