### ISSUE TITLE
Inconsistent container name regex in API reference

### ISSUE THREAD

**Issue by giovanism** [moby/moby#39067]
I thought someone forgot to update the docs, but it looks like this might be done on purpose. If this is the former case, I can make a quick PR. However if its the latter, I hope someone will be able to fill me in why this is done this way.

https://github.com/moby/moby/blob/0243936d92ea57f48c6a32beac797ee3b388ba28/api/swagger.yaml#L2246-L2251

https://github.com/moby/moby/blob/be97c66708c24727836a22247319ff2943d91a03/daemon/names/names.go#L5-L9

**Comment by boaz0** [comment]
Hi @giovanism 

What version of docker are you using?
Can you also provide ways to reproduce this problem?

Thank you for opening this issue.

**Comment by thaJeztah** [comment]
I think it's the former, and we forgot to update the swagger accordingly; feel free to open a PR; make sure to check other parts of the Swagger file (including descriptions); I did a quick search for `a-z` and I think there's one or two more that need to be updated 

Thanks! Nice catch :-)
