### ISSUE TITLE
can not run image error in armv7l  

### ISSUE THREAD

**Issue by gaoccnu** [moby/moby#39085]
kernel ：
linux 4.9.37
Architecture:
armv7l
ostype :
linux
docker version 18.09.0

when run a image error ,the error log is as follows:
INFO[0056] shim containeerd-shim started               address="/containerd-shim/moby/13802cea55547ac2bec8611bbdf2bc370fa32c0a18f108f16586300dc5968c7/shim.sock" debug=false pid=965
INFO[0056] shim reaped                                 id=13802cea55547ac2bec8611bbdf2bc370fa32c0a18f108f16586300dc5968c7
ERRO[1970-01-24T01:23:01.1282756852] stream copy error: reading from a close fifo
ERRO[1970-01-24T01:23:01.1282586852] stream copy error: reading from a close fifo
ERRO[1970-01-24T01:23:01.1291486582] 13802cea55547ac2bec8611bbdf2bc370fa32c0a18f108f16586300dc5968c7 cleanup: failed to delete container from containerd: no such container

**Comment by thaJeztah** [comment]
What method did you use to install docker? Did you install from an apt or rpm package? What distro are you running on? Also; are you able to reproduce the problem on the latest patch release (docker 18.09.5)?

**Comment by gaoccnu** [comment]
> What method did you use to install docker? Did you install from an apt or rpm package? What distro are you running on? Also; are you able to reproduce the problem on the latest patch release (docker 18.09.5)?
@thaJeztah I Install static binaries. not in a distro, My hardware is embedded device;
 The  binaries download from  this url https://download.docker.com/linux/static/stable/armel/.  In addition, the same problem exists in 18.09.5.

**Comment by thaJeztah** [comment]
closing as this one went stale, but feel free to open a new ticket if you're still able to reproduce on a current version, and with reproducible steps. I'm not sure we'd be able to do much without access to the hardware/environment you're using
