### ISSUE TITLE
Windows Server 2019: LockFile lock is not released by OS when process exits

### ISSUE THREAD

**Issue by drnybble** [moby/moby#39088]
**Description**

This problem is exhibited by running Mongo 4.0.8 with a named volume. If you restart Mongo it will not start because the WiredTiger.lock file remains locked. This is a general problem demonstrated by a sample Windows CLI program shown below.

**Steps to reproduce the issue:**
Using Visual Studio 2017, compile the Windows CLI application shown below. I used the C++ code generation option "Multi-threaded" so the VS redistributables did not need to be included in the Dockerfile.

```
#include "pch.h"
#include "Windows.h"
#include <iostream>
int main() {
	const wchar_t* FILE_NAME = L"c:\\data\\Test.lock";
	HANDLE h = ::CreateFile(FILE_NAME, GENERIC_WRITE, 0, NULL, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL);
	if (h == INVALID_HANDLE_VALUE) {
		std::cout << "CreateFile failed";
		exit(1);
	}
	std::cout << "Created file " << FILE_NAME << std::endl;

	const char* buf = "Test";
	DWORD written;
	if (!::WriteFile(h, (LPCVOID)buf, sizeof(buf), &written, NULL)) {
		std::cout << "WriteFile failed" << std::endl;
		exit(1);
	}
	std::cout << "Wrote content to file " << FILE_NAME << std::endl;

	if (!::LockFile(h, 0, 0, 1, 0)) {
		std::cout << "LockFile failed" << std::endl;
		exit(1);
	}
	std::cout << "Locked first byte of file " << FILE_NAME << std::endl;

	std::cout << "Exiting without closing handle, OS must unlock" << std::endl;
}
```
Use the following Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
COPY LockFileTest.exe /
CMD ["C:\\LockFileTest.exe"]
```
Build it:
```
docker build -t locktest .
```
Create a named volume:
```
docker volume create locktest
```
Run it:
```
docker run -v locktest:c:\data locktest
```

**Describe the results you received:**
A file called `Test.lock` is located in the named volume `C:\ProgramData\docker\volumes\locktest\_data`. Try to open it with Visual Studio Code, it fails with the error EBUSY. The file remains locked even though the owning process has exited.

**Describe the results you expected:**
As described by the documentation for LockFile (https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-lockfile) the OS should release the lock when the process exits. If you run the LockFileTest.exe on the desktop you will find that the file is not locked after the process exits.

**Additional information you deem important (e.g. issue happens only occasionally):**
Workaround is that you can delete the file even though it is locked. So for Mongo you can delete the WiredTiger.lock file on startup if it exists.

**Output of `docker version`:**

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 3
 Paused: 0
 Stopped: 7
Images: 26
Server Version: 18.09.3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: active
 NodeID: gith69a6jn2rev6tk5tzkdd4c
 Is Manager: true
 ClusterID: a9kqvee722zhpotilk8gmnsts
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.2.15
 Manager Addresses:
  10.0.2.15:2377
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.379)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: WIN-ER8SHU068SD
ID: W4KY:OBEM:VG5C:2KR7:ZYPJ:HKEJ:6SVH:GEY2:EQVS:HHUD:27T7:ZZO6
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 2019 Standard running in VirtualBox.

**Comment by drnybble** [comment]
Related issue: https://github.com/StefanScherer/dockerfiles-windows/issues/349

**Comment by olljanat** [comment]
@drnybble `OS Build 17763.379` means that you are missing April update.

Please, install it and tell if that helps? It fixed #38114 and this sounds related.

**Comment by drnybble** [comment]
Now I am on:
```
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.437)
```
The problem still happens.

**Comment by olljanat** [comment]
Ok. Will it be released if you restart Docker engine? (=> is that bug on Windows or Docker side).

**Comment by drnybble** [comment]
It is not released, seems to be a Windows problem.

**Comment by olljanat** [comment]
OK. Then it is better to contact Microsoft. Their premier support is best option if you have contract about it.

**Comment by drnybble** [comment]
I'll try the forum route: https://social.msdn.microsoft.com/Forums/en-US/76d49ce7-dd5d-4dac-bd4b-670e9fcc39c4/lockfile-lock-is-not-released-by-os-when-container-process-exits?forum=windowscontainers

**Comment by drnybble** [comment]
Well crickets so far over there....not very encouraging

**Comment by olljanat** [comment]
Btw. If you run LockFileTest.exe outside of container (directly from host example) will it be removed when process ends?

**Comment by drnybble** [comment]
Yes -- as stated above --  If you run the LockFileTest.exe on the desktop you will find that the file is not locked after the process exits.

**Comment by thaJeztah** [comment]
@jhowardmsft

**Comment by olljanat** [comment]
@drnybble OK. Thing which is bit unclear for me is that what extra that `LockFile` function does compared to normal file opening with share none setting?

As you can just start container with command:
```powershell
docker run -it -v locktest:c:\data mcr.microsoft.com/windows/servercore:ltsc2019 powershell
```
and inside of it open file without sharing anything with command:
```
$file = [System.IO.File]::Open("C:\data\Test.lock", "Create", "ReadWrite", "None")
```

which locks file but it will be released immediately when I exist from container.

**Comment by drnybble** [comment]
This is just how the WiredTiger engine is coded and why Mongo won't start up again since it still finds the lock held. You can see their code here: https://github.com/wiredtiger/wiredtiger/blob/master/src/os_win/os_fs.c

**Comment by awakecoding** [comment]
@drnybble any update on this issue? I opened https://github.com/docker-library/mongo/issues/385 on MongoDB, and then found this issue here. Combined with the older reports of the same issue here: https://github.com/StefanScherer/dockerfiles-windows/issues/349 I am now wondering if LockFile() in Windows Containers ever worked at all. I really hope this is a regression, otherwise I'm confused as to what it means in terms of number of people using MongoDB Windows containers (how can it be usable with such a big issue?)

**Comment by drnybble** [comment]
Sorry, no updates. If you have a support contract with Microsoft you can try that route.

**Comment by nkeemik** [comment]
Status update: problem is still present.

**OS Info**
```
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
```

**Docker Info**
```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

I have contacted Microsoft support (Convergys Corporation) and over the course of several months they came to a conclusion that this is not something that Microsoft can fix. They suggested to contact public forums.

Their finding: *The memory page we are trying to write has  value  set to PAGE_EXECUTE, which does not allow "CreateFileMapping"  function.* I tried the example executable outside containers and can confirm that API is called with the same flags, yet file does not stay locked when process exits.

Is there any other contact I should try ?

**Comment by nkeemik** [comment]
Ping:
@jhowardmsft
@olljanat

**Comment by awakecoding** [comment]
Maybe ping @taylorb-microsoft as well as a follow-up to this response on twitter: https://twitter.com/Taylorb_msft/status/1227417732682895360?s=20

**Comment by nkeemik** [comment]
Not sure whether @taylorb-microsoft will reply to ping... Would it make sense to get 2nd opinion from Docker engine devops team ?

**Comment by taylorb-microsoft** [comment]
Sorry I dropped the ball after starting the discussion with our dev team last month.  We think we know what the fix is and I'm re-engaged with the dev to validate and then get it serviced.

**Comment by nkeemik** [comment]
Any updates on this issue ? @taylorb-microsoft

**Comment by nkeemik** [comment]
Pinging @StefanScherer .

Its been 1 year and the community is still not able to use Windows Server 2019.

**Comment by corhere** [comment]
[Microsoft has fixed this issue, which was included in KB5001391](https://github.com/microsoft/Windows-Containers/issues/37#issuecomment-831488614)
