### ISSUE TITLE
Unable to propagate mounts of containers

### ISSUE THREAD

**Issue by ofek** [moby/moby#39093]
**Description**

I have a container that, after starting, mounts a FUSE file system. I need this to be seen by other containers in a way that works on Linux, macOS, and Windows.

By default, the mount update will not propagate unless you use the rshared option i.e. `-v source:target:rshared` (please correct me if I'm wrong!).

However, when I try that I'm getting https://github.com/moby/moby/issues/19625, https://github.com/kubernetes/kubernetes/issues/61058, etc.

For example `docker run -it --rm -v /c/Users/ofek.lev/Desktop/data:/data:rshared alpine` yields:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: linux mounts: path /host_mnt/c/Users/ofek.lev/Desktop/data is mounted on /host_mnt/c but it is not a shared mount.
```

I have C: shared in UI (and un/re-checked box + reset credentials just in case).

I then tried using the MobyLinux VM directly like `docker run -it --rm -v //tmp/test-data:/data:rshared alpine` which produces:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: linux mounts: path /tmp/test-data is mounted on / but it is not a shared mount.
```

A colleague confirmed this also happens on his macOS.

Upon further research, it seems the systemd unit file for Docker may sometimes have MountFlags set to an incorrect value, see [this](https://stackoverflow.com/a/43687970/5854007) and [that](https://www.ibm.com/support/knowledgecenter/en/SSBS6K_1.2.0/troubleshoot/kubelet_fails_install.html). However, the MobyLinux VM does not appear to use systemd.

The other recommendation I saw was to explicitly share `/`. Getting into the MobyLinux VM was tricky, but here is how I did it:

```
ofek.lev@ozone ~\Desktop $ docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh
/ # chroot /host
/ # mount --make-rshared /
/ #
```

Though alas, with or without a daemon restart, this too does not get rid of the `mounted on / but it is not a shared mount` error.

This is a hard blocker for a project I'm working on and I don't know where to go from here. I've been at this for days 😞 

**Output of `docker version`:**

```
ofek.lev@ozone ~\Desktop $ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.11
  StackAPI:         v1beta2
```

**Output of `docker info`:**

```
ofek.lev@ozone ~\Desktop $ docker info
Containers: 36
 Running: 36
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.915GiB
Name: linuxkit-00155d565f1b
ID: LE53:I25L:TVCD:W5CK:I5RA:JTXB:EUY2:WDA7:2U5Y:Y7XY:CQJO:DTUO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 120
 Goroutines: 124
 System Time: 2019-04-17T05:33:29.0972945Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 pro w/ Hyper-V (colleague is macOS High Sierra)

**Comment by cpuguy83** [comment]
This would require mount propagation to work across the VM boundary, which is not going to happen.
It also requires changing the mount propagation of the host's rootfs, which in the case of docker-for-mac and docker-for-windows, is a linux VM. You cannot make the rootfs shared from inside a container because the mount changes won't propagate back to the host.

Closing since it's not really an issue, and is not something that can be supported.

**Comment by ofek** [comment]
For those coming from search engines, the solution was https://github.com/ofek/docker-volume-gcs
