### ISSUE TITLE
runc regression - EPERM running containers from selinux

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#39109]
Trying to run containers on centOS with selinux enforcing on, runc gets a denial trying to access `/proc/self/attrs/keycreate`.

This happens when `selinux-enabled=false` on dockerd, which is the default. When `selinux-enabled=true` all is OK.

Reverting runc to an older commit (which does not mess with this file), everything starts up properly.

**Comment by cpuguy83** [comment]
Error from runc:

```
$ sudo docker run -it --rm busybox sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown.
```

Denial from selinux:

```
type=PROCTITLE msg=audit(1555611120.741:866): proctitle=2F7573722F62696E2F72756E6300696E6974
type=SYSCALL msg=audit(1555611120.741:866): arch=c000003e syscall=1 success=no exit=-13 a0=8 a1=557a6f0ab780 a2=0 a3=0 items=0 ppid=10782 pid=10790 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc:[2:INIT]" exe="/" subj=system_u:system_r:container_runtime_t:s0 key=(null)
type=AVC msg=audit(1555611120.741:866): avc:  denied  { create } for  pid=10790 comm="runc:[2:INIT]" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=key
```

**Comment by thaJeztah** [comment]
@cpuguy83 can you try if this still reproduces with the containerd.io 1.2.6-2 package?

**Comment by tao12345666333** [comment]
```
(MoeLove) ➜  ~ docker run --rm -it alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown.
(MoeLove) ➜  ~ docker version
Client: Docker Engine - Community
 Version:           0.0.0-20190602210104-8bc6c6593a
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        8bc6c6593a
 Built:             Mon Jun  3 07:31:03 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          0.0.0-20190602210104-8bc6c6593a
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       8bc6c6593a
  Built:            Mon Jun  3 07:29:41 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
I can reproduce it with `containerd.io-1.2.6-3.2.fc28.x86_64`.

```
(MoeLove) ➜  ~ rpm -qa |grep contai
container-selinux-2.85-1.git92af7fd.fc28.noarch
containers-common-0.1.31-13.dev.gite3034e1.fc28.x86_64
ghc-containers-0.5.10.2-70.fc28.x86_64
containerd.io-1.2.6-3.2.fc28.x86_64
systemd-container-238-12.git07f8cd5.fc28.x86_64
plexus-containers-component-annotations-1.7.1-5.fc28.noarch
ghc-containers-devel-0.5.10.2-70.fc28.x86_64

```

**Comment by thaJeztah** [comment]
Copying from the backport PR;

> https://github.com/opencontainers/selinux/pull/51#issuecomment-485950519
> 
> Dan says it's an issue container-selinux and it should be fixed.

..

> > @cpuguy83 LGTY?
> I can't verify that container-selinux fixes this since it doesn't appear to be updated yet.


@tao12345666333 can you post the version of `container-selinux` that you have installed, and try if an updated `container-selinux` is available and fixes this?

**Comment by thaJeztah** [comment]
@seemethere we may want to raise the minimum version for `container-selinux` in packaging if this is an issue

**Comment by daneelSoftware** [comment]
just starting with docker, i installed a Centos7.6-1810 vm  and updated to latest ( 3.10.0-957.12.2.el7.x86_64 )
installed docker 
docker-ce-19.03.0-2.2.rc2.el7.x86_64
docker-ce-cli-19.03.0-2.2.rc2.el7.x86_64
with 
containerd.io-1.2.6-3.2.el7.x86_64
container-selinux-2.95-2.el7_6.noarch
enabling Selinux causes the error, setting to permissive let the hello-word check work fine

**Comment by thaJeztah** [comment]
Thanks!

`container-selinux-2.95-2.el7_6.noarch`

@cpuguy83 do you recall which version of container-selinux fixed the issue for you?

**Comment by cpuguy83** [comment]
I'm not sure the exact version, last I checked was 2.95 though (b/c someone asked me the same thing last week).

**Comment by cpuguy83** [comment]
Let's close this since this is not a moby bug and is fixed in the relevant package.

**Comment by thaJeztah** [comment]
@cpuguy83 did you get the updated container-selinux package on CentOS or RHEL?

**Comment by cpuguy83** [comment]
centos

**Comment by heisnamsanjay** [comment]
Hello All,

what's the fix for the case, I encountered the same error -->

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown.

could someone please help

**Comment by kolyshkin** [comment]
Weird, I wanted to report this to CentOS but can't repro this:

```
[root@kir-ce75-gd ~]# docker run hello-world

Hello from Docker!
...
```

Versions:
```
[root@kir-ce75-gd ~]# rpm -q docker-ce container-selinux centos-release containerd.io
docker-ce-19.03.0-2.2.rc2.el7.x86_64
container-selinux-2.95-2.el7_6.noarch
centos-release-7-6.1810.2.el7.centos.x86_64
containerd.io-1.2.6-3.2.el7.x86_64
[root@kir-ce75-gd ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        f97efcc
 Built:             Wed Jun  5 01:40:20 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       f97efcc
  Built:            Wed Jun  5 01:38:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

SELinux:
```
[root@kir-ce75-gd ~]# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

Not sure what I'm doing wrong.

**Comment by cpuguy83** [comment]
container-demonic v2.95 has the fix in it.

**Comment by kolyshkin** [comment]
Oh OK I got it!
```
yum downgrade container-selinux
....
Installed:
  container-selinux.noarch 2:2.74-1.el7                                                                                                                                                                                                       

Complete!
[root@kir-ce75-gd ~]# docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by thaJeztah** [comment]
not sure if I have time this weekend (and Monday is a public holiday here) could someone open a PR to https://github.com/docker/docker-ce-packaging to raise the minimum version in the packages?

@kolyshkin @cpuguy83

**Comment by cpuguy83** [comment]
Lol. I guess iOS folks don't like selinux

**Comment by kolyshkin** [comment]
> could someone open a PR

https://github.com/docker/docker-ce-packaging/pull/340
https://github.com/docker/docker-ce-packaging/pull/339

**Comment by tao12345666333** [comment]
```
(MoeLove) ➜  ~ docker version                                                                                    
Client: Docker Engine - Community
 Version:           0.0.0-20190607210243-b93f571b01
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        b93f571b01
 Built:             Sat Jun  8 07:31:22 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          0.0.0-20190607210243-b93f571b01
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b93f571b01
  Built:            Sat Jun  8 07:30:01 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
(MoeLove) ➜  ~ docker run --rm alpine hostname 
bc7652c3f19e
(MoeLove) ➜  ~ rpm -q container-selinux
container-selinux-2.101-1.gitb0061dc.fc29.noarch
```

I upgraded my system from fedora 28 to 29 today, and upgraded `container-linux` to `container-selinux-2.101-1.gitb0061dc.fc29.noarch` and everything works fine. :smile:

**Comment by daveneeley** [comment]
Downloaded fresh binaries from releases page, without using a package manager.


```
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

docker version
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
 sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```
Still see this error:
`docker-compose[3295]: ERROR: for x  Cannot start service x: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown`

Both the PRs I see were closed and not merged, how is this fixed?

**Comment by thaJeztah** [comment]
@daveneeley what version of `container-selinux` do you have installed? Also what versions of `containerd.io` (and `runc`) ? `containerd.io` is a separate package, so might not be updated to the latest version.

(the error itself is bubbling up from runc; https://github.com/opencontainers/runc/blob/v1.0.0-rc8/libcontainer/container_linux.go#L345)

**Comment by daveneeley** [comment]
These were included in 18.09.8 tgz from `https://download.docker.com/linux/static/stable/`
``` 
runc --version
runc version 1.0.0-rc8
commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
spec: 1.0.1-dev

ctr --version
ctr github.com/containerd/containerd v1.2.6

containerd --version
containerd github.com/containerd/containerd v1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```
`containerd-shim` does not report a version.

**Comment by cpuguy83** [comment]
container-selinux v2.99 tmk does not have the correct patches.

**Comment by daveneeley** [comment]
hmm. 2.99 is the latest in CentOS Extras x86_64 for Centos 7.

**Comment by typekpb** [comment]
Facing the same issue, beeing on the RHEL 7.6. Could downgrading some specific package solve it for me?

**Comment by typekpb** [comment]
Ok, found a version, that works for me: `docker-ce-18.06.0.ce-3.el7.x86_64`, looking forward for the upstream fix

**Comment by cpuguy83** [comment]
That version is vulnerable to a nasty CVE.

Upgrade container-selinux and it will fix the issue.

**Comment by JulianRMedina** [comment]
I run into the issue that if I don't enable selinux, docker can't access the keycreate file. If I enable selinux, then the os won't let docker access the shared libraries: libtinfo.so.5.

**Comment by typekpb** [comment]
@cpuguy83 thanks for the suggestion. Manual update of the package `docker-selinux` to 2.99 fixed it, as the version is for whatever reason not available over my repos (RHEL 7.6):
```
sudo yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.99-1.el7_6.noarch.rpm
```
Afterwards I'm back to docker-ce latest stable:
```
rpm -qa |grep docker                                                                                                                                                            
docker-ce-cli-19.03.1-3.el7.x86_64
docker-ce-19.03.1-3.el7.x86_64
```

**Comment by YesThat** [comment]
> That version is vulnerable to a nasty CVE.
> 
> Upgrade container-selinux and it will fix the issue.

Thanks so much for this whole thread.   This really saved me a lot of head/heartache/burn.

**Comment by kalona** [comment]
sudo setenforce Permissive
did the trick for me!
