### ISSUE TITLE
Mounting /dev:/dev breaks TTY option

### ISSUE THREAD

**Issue by yanniszark** [moby/moby#39114]
**Description**

Mounting `-v /dev:/dev` and using `-t (tty: true)` doesn't work.
This happens in version `17.03.2-ce`.

**Steps to reproduce the issue:**
1. `docker container run -t -d -v /dev:/dev --name test debian:stable`
2. `docker exec -it test /bin/bash`
3. Inside the container: 
```console
$ echo "somelogs" > /dev/console
bash: echo: write error: Input/output error
```

**Describe the results you received:**
The `-t` option is supposed to allocate a TTY inside the container and mount it on `/dev/console`.
This happens correctly if /dev isn't mounted to /dev.
However, mounting /dev to /dev breaks this.

`/dev/console` doesn't appear in mounts:
```console
# With /dev to /dev mount
$ mount | grep console
<nothing>

# Without /dev to /dev mount
$ mount | grep console
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
```

**Describe the results you expected:**
I expected to be able to send logs to /dev/console, however it seems to be broken.

**Additional information you deem important (e.g. issue happens only occasionally):**

I suspect this is a timing issue, maybe the TTY should be allocated after /dev is mounted.
This doesn't happen with version `18.06.1-ce`.
I couldn't find a related issue, so I open this to investigate if it was fixed as a side-effect of another issue. 

**Output of `docker version`:**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64
 Experimental: false
root@gke-yanniszark-rok-new-default-pool-ee44aee5-82t9:~# docker info
Containers: 62
 Running: 51
 Paused: 0
 Stopped: 11
Images: 32
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1026-gcp
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.68 GiB
Name: gke-yanniszark-rok-new-default-pool-ee44aee5-82t9
ID: FKQ6:XVK3:GRSW:2RFR:UKHE:VZJQ:COSZ:VHMR:4GIN:H7BQ:BK5T:HJ6O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.0.0.0/8
 127.0.0.0/8
Registry Mirrors:
 https://mirror.gcr.io/
Live Restore Enabled: true

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine on GKE version `1.12.7-gke.7`

**Comment by thaJeztah** [comment]
I'm not sure if this would work; the `/dev` from the host will be bond-mounted over the container's `/dev`, so will mask anything in there (including the tty that's created when the container is created).

Mounting `/dev` _before_ creating the tty would result in the tty being created on the host.

**Comment by yanniszark** [comment]
@thaJeztah after some tests, I have managed to place the bug between two minor versions.
In `17.05.0-ce` -> bug occurs, `17.06.0-ce` bug fixed.
So the commit fixing this issue is somewhere between these two versions.
Haven't had the time to git bisect further, but once I manage to pin it down to a specific commit I will update with more info.

**Comment by AkihiroSuda** [comment]
Let me close this one, as 17.05 and older releases are no longer supported
