### ISSUE TITLE
docker daemon error cannot start container System error: mkdir /var/lib/docker/vfs/dir/2f1270f3f92d3ca1a3ed8cdb43bf3b878f7d555f034adb0df018fec56d261aec/sys/fs/cgroup: no such file or directory

### ISSUE THREAD

**Issue by andynkili** [moby/moby#39113]
**Description**

My Centos server crashed (power outage) and a docker container was running at that time. When I try to start the container, it fails with the error:
```mkdir /var/lib/docker/vfs/dir/2f1270f3f92d3ca1a3ed8cdb43bf3b878f7d555f034adb0df018fec56d261aec/sys/fs/cgroup: no such file or directory.```
I checked the directory "sys" and indeed it is empty.

**Full error**
```
$ sudo docker start edge2.2_2
Error response from daemon: Cannot start container edge2.2_2: [8] System error: mkdir /var/lib/docker/vfs/dir/2f1270f3f92d3ca1a3ed8cdb43bf3b878f7d555f034adb0df018fec56d261aec/sys/fs/cgroup: no such file or directory
Error: failed to start containers: [edge2.2_2]
```

**Troubleshooting**
I checked also the logs with: docker logs <container ID>  and the same error was there.
I restart the docker service "sudo service docker restart" and tried to start the container, in vain
I checked the images with docker ps -a and the status of the container I am trying to start is Exit(-1). So I googled and find some post about "starting a container after bad exit" but some recommend to restart docker service (already did) and other to start and attach the container, but I can't even start it.

**Output of `docker version`:**

```
$docker --verison
Docker version 1.7.1, build 786b29d/1.7.1
```

**Output of `docker info`:**

```
$docker info
Containers: 4
Images: 39
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-754.12.1.el6.x86_64
Operating System: <unknown>
CPUs: 16
Total Memory: 252.2 GiB
Name: localhost
ID: GJ3E:MNTR:YIVL:5KS7:ZJS6:EUAU:RVH3:L4UL:BKI4:TVMY:DDUD:ESGX

```

**Output of `name -a`:**
```
$ uname -a
Linux localhost 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `sudo docker ps -a`:**
```
sudo docker ps -a
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS                       PORTS               NAMES
692f1013ab18        bioedge/edge_dev       "/usr/sbin/init"       5 minutes ago                                                        edge2               
2f1270f3f92d        bioedge/edge_dev       "/usr/sbin/init"       10 months ago       Exited (-1) 47 minutes ago                       edge2.2_2           
384b11bffc22        bioedge/edge_mariadb   "/bin/bash -c /usr/s   11 months ago                                                        mysql_data          
4688f4fae7dc        bioedge/edge_dev       "/usr/sbin/init"       12 months ago                                                        jovial_carson 
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
