### ISSUE TITLE
Coredump support in docker

### ISSUE THREAD

**Issue by WanLinghao** [moby/moby#39127]
- What we need:

   In our bussiness, core dump feature is useful when our jobs crashed. But it seems that the docker itself does not provide some kind of control of core dump function.

- Why we need:

  A typical case is that the /proc/sys/kernel/core_pattern file was set to "core",  then if tasks in container was crashed, the core file would generated inside container rather than the host. As we know, container's filesystem is not persistent, which means admin must export those core files to host filesystem before container exits. This is really a burden for admin. Of course we could design some kind of scripts to complete this job. But I am wondering if docker itself could support core dump feature.

- History:

  A guy proposed something similar before(#19289) , it seems this idea was not that attractive to community at that time.   Could we reconsider this feature? Thank you.

**Comment by cpuguy83** [comment]
The other issue is still open. Let's keep the discussion there, thanks!
