### ISSUE TITLE
Failed to start a development container in the moby repository

### ISSUE THREAD

**Issue by niketagrawal** [moby/moby#39147]
**Description**

 I'm following the contributing guide here: (https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md). The step where a development container needs to be started fails.

**Steps to reproduce the issue:**
1. Fork moby/moby repository from github and clone it locally. 
2. Navigate to cd moby/ and start a development container by issuing the command 
    make BIND_DIR=. shell

**Describe the results you received:**

mypc@mypc:~/repo/moby$ make BIND_DIR=. shell
Makefile:152: The docker client CLI has moved to github.com/docker/cli. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

DOCKER_BUILDKIT="1" docker build  --build-arg=CROSS=false --target=dev -t "docker-dev:firstbranch" -f "Dockerfile" .
buildkit not supported by daemon
Makefile:152: recipe for target 'build' failed
make: *** [build] Error 1

**Describe the results you expected:**

Successfully built 3d872560918e
Successfully tagged docker-dev:dry-run-test
docker run --rm -i --privileged -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_CLIENTONLY -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER=devicemapper -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -v "home/ubuntu/repos/docker/bundles:/go/src/github.com/docker/docker/bundles" -t "docker-dev:dry-run-test" bash
#
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.688GiB
Name: niket-HP-ProBook-440-G4
ID: 3WQN:NYZ2:FAUL:5GPM:27VC:O4TS:7W3T:CYOI:T4HF:Y7LH:7XKM:ZWQR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by joshinv** [comment]
I am facing the same problem. Can you please tell how did you resolve this.

**Comment by niketagrawal** [comment]
Youneed to build the Docker CLI separately and provide that Linux binary to the development container. Step no.9 of the moby dev container tutorial (https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md) gives some information on this. You will find the commands to build the Linux binary for the Docker CLI on the docker cli github repository (https://github.com/docker/cli). The 'make' command to supply this binary to the development container is mentioned in step 9 of moby dev container tutorial itself. Lastly, you need to specify DOCKER_BUILDKIT=0 in that make call.
