### ISSUE TITLE
AIX support

### ISSUE THREAD

**Issue by Helflym** [moby/moby#39159]
Hi,

Now that AIX support has been added to Go toolchain, we might be able to port some Docker packages. 
We (my team and I) already know that having the whole Docker environment is impossible on AIX. The daemon isn't compatible with it (at least noone have managed to do it). 
However, discussing with elastic/beats community (which are using Docker), it seems that they are some Docker packages which can still be ported on AIX, especially the "client" side which, if I do understand, can be connected to a remote Linux docker with TCP (please do correct me if I'm wrong). 

Anyway, before porting the Docker packages like a mad man, I wish to understand a few things: 
 - is there any other OS where only the client part is available without the daemon ? 
 - which packages are needed by the docker client (not all but the main/hardest ones) ? 
 - Are you, the community, accepting unfinished port ? This question might be strange but `docker/pkg/*` might be imported by other Go packages as helpers and thus be must ported for AIX. Or are the whole cli/client packages must be ported in order to have even some `+build aix`? To sum up, which are the must-have packages ?  

We don't know yet, we will do such a port. It's depending on how long it will take, how many people want it, etc. But if you're interesting in having some Docker packages available on AIX, please don't hesitate to reply.

**Comment by estesp** [comment]
If you are looking to just do the client, then you should probably open this issue in the `docker/cli` repository.

A few data points:
 - Microsoft did initially focus on just the client side port before the client was actually a separate GitHub project, but it was done with the intent that the daemon would follow later.
 - For Docker Desktop, it is of course pretty normal that the client is running on a different OS than the engine (which is normally in a small VM running Linux), but the `docker` client commands are running on the hosted OS (MacOS or Windows as the case may be)

**Comment by justincormack** [comment]
MacOS only has client support at present. Most of the client code is pretty portable, but it would make more sense to open this issue on github.com/docker/cli rather than here (there are some dependencies on other libraries, some may be here, others are in containerd etc). I would see what doesnt work as a starting point...

**Comment by thaJeztah** [comment]
cli issue is here; https://github.com/docker/cli/issues/1858
