### ISSUE TITLE
How to use calico network with docker swarm

### ISSUE THREAD

**Issue by hegphegp** [moby/moby#39157]
**Description**

<b>How to use calico network with docker swarm, I don't want to user overlay network. Could provide some blogs or some examples about calico network with docker swarm?</b>

**software info:**

```
Docker version 18.09.5-ce
Calicoctl Version 3.6.1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by olljanat** [comment]
That is interesting question. I was investigated it about year ago and noticed that it is only described on old documentation https://docs.projectcalico.org/v1.6/getting-started/docker/tutorials/docker-swarm

Recent documentations only talks about Kubernetes but unless they are removed support it should still works as Moby API is backward compatible. Anyway, as Calico is plugin for Moby/Docker it is most probably good idea to ask from their community: https://www.projectcalico.org/community

**Comment by olljanat** [comment]
@hegphegp status looks to be documented to https://github.com/projectcalico/libnetwork-plugin

```The libnetwork plugin integration is no longer included as a core component in Calico releases, and is not being actively developed or supported by the core Calico team. The latest release of Calico which includes this plugin is the v2.6.x series of releases.```

**Comment by olljanat** [comment]
Derek close
