### ISSUE TITLE
Failed to start development container after setting DOCKER_CLI_PATH

### ISSUE THREAD

**Issue by niketagrawal** [moby/moby#39151]
Trying to set up a moby development environment by following the steps in https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md

I noticed the below error when trying to start a development container under newly cloned moby/moby repository following the step 4 in https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md,
---------------------------------------------------------------------------------------
Makefile:152: The docker client CLI has moved to github.com/docker/cli. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

DOCKER_BUILDKIT="1" docker build  --build-arg=CROSS=false --target=dev -t "docker-dev:firstbranch" -f "Dockerfile" .
buildkit not supported by daemon
Makefile:152: recipe for target 'build' failed
make: *** [build] Error 1
------------------------------------------------------------------------------------
I had to supply a new docker cli to the DOCKER_CLI_PATH. I successfully built the docker cli Linux binary from docker/cli repository, set the path but failed to start the dev container.

**Steps to reproduce the issue:**
1. Follow the steps in https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md and clone the moby/moby repository. 
2. Run a development container as in step 4 in the above URL and notice the below error
Makefile:152: The docker client CLI has moved to github.com/docker/cli. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

DOCKER_BUILDKIT="1" docker build  --build-arg=CROSS=false --target=dev -t "docker-dev:firstbranch" -f "Dockerfile" .
buildkit not supported by daemon
Makefile:152: recipe for target 'build' failed
make: *** [build] Error 1

3. Jump to step 9 in the URL mentioned in step 1 and build the Linux binary for docker cli from docker/cli github repo

4. Clone docker/cli github repo and build the binary by running the command : 
make -f docker.Makefile binary

Following output will be seen:
# build dockerfile from stdin so that we don't send the build-context; source is bind-mounted in the development environment
cat ./dockerfiles/Dockerfile.binary-native | docker build -t docker-cli-native -
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM    golang:1.12.4-alpine
 ---> b97a72b8e97d
Step 2/5 : RUN     apk add -U git bash coreutils gcc musl-dev
 ---> Using cache
 ---> 71e95c880af9
Step 3/5 : ENV     CGO_ENABLED=0         DISABLE_WARN_OUTSIDE_CONTAINER=1
 ---> Using cache
 ---> b3f3530e3fae
Step 4/5 : WORKDIR /go/src/github.com/docker/cli
 ---> Using cache
 ---> 01914ae74a3a
Step 5/5 : CMD     ./scripts/build/binary
 ---> Using cache
 ---> 00ba9f3c5368
Successfully built 00ba9f3c5368
Successfully tagged docker-cli-native:latest
docker run --rm -e VERSION=19.03.0-dev -e GITCOMMIT -e PLATFORM -e TESTFLAGS -e TESTDIRS -v "/home/niket/thesis/cli":/go/src/github.com/docker/cli -v "docker-cli-dev-cache:/root/.cache/go-build"  docker-cli-native
Building statically linked build/docker-linux-amd64

5. Copy the path of the binary named docker-linux-amd64. This binary is present in /home/../docker/cli/build/

6. Follow step 9 in https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md again and run the following command under the cloned moby/moby which sets the new path and then starts a dev container

make DOCKER_CLI_PATH=/home/../docker/cli/build/docker-linux-amd64 BIND_DIR=. shell

After running the above command, following error is seen:

Makefile:152: The docker client CLI has moved to github.com/docker/cli. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

DOCKER_BUILDKIT="1" docker build  --build-arg=CROSS=false --target=dev -t "docker-dev:firstbranch" -f "Dockerfile" .
buildkit not supported by daemon
Makefile:152: recipe for target 'build' failed
make: *** [build] Error 1

This is the same error as was seen in step 2 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.688GiB
Name: niket-HP-ProBook-440-G4
ID: 3WQN:NYZ2:FAUL:5GPM:27VC:O4TS:7W3T:CYOI:T4HF:Y7LH:7XKM:ZWQR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
I responded on your forum post.
Seems like your docker install does not have buildkiit enabled, as such you need to use `make DOCKER_BUILDKIT=0 shell`

Closing this.
Thanks!
