### ISSUE TITLE
How to get `cpuacct.stat` from stoped container? 

### ISSUE THREAD

**Issue by heckad** [moby/moby#39162]
I want to build system for checking the solution of olympiad problems using the docker for running tests. Now I need in getting time of container working. In documentation I found cpuacct.stat file wich contains needed information, but I cant get it from stopped contatiner using commandcp`. How to copy its?

**Comment by heckad** [comment]
Okey. Maybe if it is imposible, then add new key `--extend` to command `stats`, wich returns all information about container in json format?

**Comment by kolyshkin** [comment]
`docker stats` shows current usage (for the last second or so), while `cpuacct.stat` gives a cumulative usage (for the duration of this cgroup/container existence).

What you probably need is something like `time` shell built-in, see http://man7.org/linux/man-pages/man1/time.1.html
