### ISSUE TITLE
404 on Mobyproject.org

### ISSUE THREAD

**Issue by peterennisrda** [moby/moby#39170]
404

**Steps to reproduce the issue:**
1. Click the link
2.
3.

**Describe the results you received:**
404

**Describe the results you expected:**
Repo

**Additional information you deem important (e.g. issue happens only occasionally):**

![Capture198](https://user-images.githubusercontent.com/1280523/57167785-e29ca100-6db3-11e9-8d7d-d51793b70b2c.png)

![Capture199](https://user-images.githubusercontent.com/1280523/57167792-e7615500-6db3-11e9-9570-e92634225027.png)

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 1809
Chrome browser

**Comment by wlsc** [comment]
Same for me -- 404 when pressing GitHub logo on the main page.

**Comment by thaJeztah** [comment]
- fixed by https://github.com/moby/mobywebsite/pull/71
