### ISSUE TITLE
unable to build solaris base Image

### ISSUE THREAD

**Issue by SwathiKalahastri** [moby/moby#39181]
Hi 

I am unable to build solaris Imabge using dockerfile.solaris  getting bellow error

**repository docker.io/solaris not found: does not exist or no pull access** 

Please help.

Thanks, 
Swathi K

**Comment by SwathiKalahastri** [comment]
To build I used below cmd 
**sudo docker build -t nativebuildimage -f Dockerfile.solaris .**

**output** 
Sending build context to Docker daemon 34.26 MB
Step 1/5 : FROM solaris:latest
Trying to pull repository docker.io/library/solaris ... 
repository docker.io/solaris not found: does not exist or no pull access

**Comment by AkihiroSuda** [comment]
Attempt to support Solaris failed on the way
