### ISSUE TITLE
Please update vishvananda/netns for ppc64 support

### ISSUE THREAD

**Issue by zeldin** [moby/moby#39184]
**Description**

The version of vishvananda/netns (vishvananda/netns@604eaf189ee867d8c147fafc28def2394e878d25) that is currenly vendored does not support ppc64 (only ppc64le).  ppc64 support was added by upstreams in commit vishvananda/netns@1fec6582c067519857603311ad090e23a5ca57de, over 3 years ago, so updating to this commit or any newer one fixes the issue.

**Steps to reproduce the issue:**
1. Try to build docker on linux/ppc64
2.
3.

**Describe the results you received:**
Compilation failed due to missing support in a vendored dependency

**Describe the results you expected:**
Compilation succeeded

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.12.1
 Git commit:        e8ff056
 Built:             Wed May  1 16:42:46 2019
 OS/Arch:           linux/ppc64
 Experimental:      true

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       e8ff056
  Built:            Wed May  1 16:42:15 2019
  OS/Arch:          linux/ppc64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683b971d9c3ef73f284f176672c44b448662
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.34
Operating System: Gentoo/Linux
OSType: linux
Architecture: ppc64
CPUs: 64
Total Memory: 63.68GiB
Name: hakua
ID: WJWV:AD7M:FA6K:IR3B:SJT7:RERM:PVPY:MDSL:6HX4:RXQV:JW26:3OU4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: zeldin
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
See https://github.com/moby/moby/pull/39054 and https://github.com/docker/libnetwork/pull/2366. Still waiting for libnetwork maintainers to review/merge that one though
