### ISSUE TITLE
docker: Error response from daemon: failed to create endpoint ... on network bridge: failed to add the host (veth9754872) <=> sandbox (veth6a875bb) pair interfaces: operation not supported.

### ISSUE THREAD

**Issue by chenliu1993** [moby/moby#39188]
**Description**

I am running "docker run --privileged hello-world:latest" under Linux kernel built by own company.  But the error shown as the issue occurred. The iptables' relative modules like bridge.ko and iptable_nat.ko are all plugged-in manually through "insmod". 
systemctl status docker shows docker is active. 
I tried to delete /var/lib/docker/network/files, but didn't help.
My OS version is 4.9.*, OS doesn't have /lib/modules/4.9.* folders.
**Steps to reproduce the issue:**
1. docker run --privileged  hello-world:latest
2.  
3.

**Describe the results you received:**
docker: Error response from daemon: failed to create endpoint blissful_johnson on network bridge: failed to add the host (veth9754872) <=> sandbox (veth6a875bb) pair interfaces: operation not supported.

**Describe the results you expected:**
hello-world

**Additional information you deem important (e.g. issue happens only occasionally):**
Kernel is compiled based on one linux distribution version  without all unnecessary modules to make it as small as possible.  And it cannot be restarted. Each time it is restarted, all the modules manually inserted will be lost. The environment for docker will be cleaned-up.
**Output of `docker version`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 18.06.3-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.*
Operating System: Ubuntu 18.04.1 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.86GiB
Name: localhost.localdomain
ID: JILY:LIIM:BP3S:E5LV:ICZJ:UZGZ:5XCI:EOOB:5AVI:AUI3:5YTT:FCW4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mountkin** [comment]
Please check if `veth` module is loaded.
```
modinfo veth
ip link add vetha type veth peer name vethb
```

**Comment by chenliu1993** [comment]
> Please check if `veth` module is loaded.
> 
> ```
> modinfo veth
> ip link add vetha type veth peer name vethb
> ```

Solved! Thank you!

**Comment by qg0** [comment]
unxz /lib/modules/`uname -r`/kernel/drivers/net/veth.ko.xz
insmod /lib/modules/`uname -r`/kernel/drivers/net/veth.ko
