### ISSUE TITLE
Permission of /tmp dir changed when start a container

### ISSUE THREAD

**Issue by liqlin2015** [moby/moby#39195]
**Description**

Try to install k8s on CentOS host. But find some of docker container failed to start. Problem is permission of `/tmp` dir was changed to `drwxr-xr-x`. As we start the container as non-root user, we now have permission problem to write something in `/tmp` dir.

On other Ubuntu host, we did not get the problem. It's definitely not image issue.

**Steps to reproduce the issue:**
1. Start container by k8s on CentOS host.
2. Container failed to start due to permission problem to access `/tmp` dir.

**Describe the results you received:**

Docker container failed to start because there is permission problem to access `/tmp` dir.

**Describe the results you expected:**

`/tmp` dir should have permission `777`. Everyone can read/write.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

**Output of `docker info`:**

```
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

**Additional environment details (AWS, VirtualBox, physical, etc.):

By the way, selinux was disabled.

**Comment by liqlin2015** [comment]
@thaJeztah any thinking about this issue.

**Comment by thaJeztah** [comment]
Do you have some minimal steps to reproduce? What image are you using, and are you using exactly the same version of the image? I don't think docker does anything with the permissions on that directory (nor does it by default put a mount there);

To verify If you run the image below on both machines, do you see that issue?

```bash
docker run --rm alpine@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528 ls -la /tmp

total 8
drwxrwxrwt    2 root     root          4096 Sep 11  2018 .
drwxr-xr-x    1 root     root          4096 May 10 02:23 ..
```

**Comment by aki-k** [comment]
I reported this thing earlier (bind mounting a directory from the host to the container and permissions changing from 0700 to 0755):

https://github.com/moby/moby/issues/37776

Could it be related?

**Comment by thaJeztah** [comment]
Bind-mounting is different.

**Comment by liqlin2015** [comment]
@thaJeztah Any way I can check the image layer to find out what's the origin file permission of `/tmp` dir on the docker host?

**Comment by liqlin2015** [comment]
I got some interesting findings.
On the problem host, permission of `/tmp` dir was all changed to `755` instead of initial `777`. I guess some Linux setting forcefully changes permission of dir to `755` when docker pull images in local file system.

cc @thaJeztah

**Comment by thaJeztah** [comment]
> Any way I can check the image layer to find out what's the origin file permission of /tmp dir on the docker host?

You can `docker image save` to save an image as a tar

> I guess some Linux setting forcefully changes permission of dir to 755 when docker pull images in local file system.

docker does not set permissions on that directory on the host; the only things I can possibly see happening is;

- `/tmp` being _created_ if it does not exist (in which case the host's umask would probably be used)
- not sure if kubernetes (bind) mounts `/tmp` and possibly applies permissions on it

Can you reproduce the issue? If so, can you reproduce the issue without kubernetes? What are the steps to reproduce?

Without more information and steps to reproduce, I don't think there's much we can do.
