### ISSUE TITLE
404, GF_SERVER_ROOT_URL doesn't work fine.

### ISSUE THREAD

**Issue by cupen** [moby/moby#39224]
**Description**
404, It seems like  subpath doesn't work. 

**Steps to reproduce the issue:**
1. `sudo docker run --rm  -e "GF_SERVER_ROOT_URL=http://127.0.0.1:3000/grafana/" -p 3000:3000 grafana/grafana`
2.  `curl http://127.0.0.1:3000/grafana/login -v  1>/dev/null`

**Describe the results you received:**
1. docker run fine.
  ```
  ......
  t=2019-05-15T18:07:24+0000 lvl=info msg="HTTP Server Listen" logger=http.server 
  address=0.0.0.0:3000 protocol=http subUrl=/grafana socket=
  ```

2. subpath doesn't work
  ```
  > GET /grafana/login HTTP/1.1
  > User-Agent: curl/7.29.0
  > Host: 127.0.0.1:3000
  > Accept: */*
  >
  < HTTP/1.1 404 Not Found
  < Content-Type: text/html; charset=UTF-8
  < Date: Wed, 15 May 2019 18:10:15 GMT
  < Transfer-Encoding: chunked
  <
  { [data not shown]
  100 21988    0 21988    0     0  8696k      0 --:--:-- --:--:-- --:--:-- 10.4M
  * Connection #0 to host 127.0.0.1 left intact
  ```

**Describe the results you expected:**
It works

**Output of `docker version`:**

```
Docker version 18.09.5, build e8ff056
```

**Comment by cpuguy83** [comment]
Docker is only setting up a nat here and does not deal with the protocol at all.
This sounds like an issue with your configuration in the container rather than Docker.

**Comment by cupen** [comment]
@cpuguy83  Oh, I'm so sorry. I originally wanted to open issue for grafana.
