### ISSUE TITLE
`docker swarm leave` doesn't remove all Swarm networks

### ISSUE THREAD

**Issue by guillaumerose** [moby/moby#39225]
**Description**

Since 19.03.0-beta4, swarm tests are failing on Docker Desktop CI. It seems that after a `docker swarm leave`, Swarm networks are still present. 

Our tests are doing in BeforeEach and AfterEach `docker swarm init` and `docker swarm leave --force`. After the first test, a network is left in the network list.
The second test is then failing and we can see in the log: `Pool overlaps with other one on this address space`

Looking at the git log, this commit seems the faulty one: https://github.com/moby/moby/commit/2a7513a9721a222e384850c524aa499f80a40a7a

**Steps to reproduce the issue:**

```
#!/bin/sh -x
docker swarm init
cat > docker-compose.yml <<EOT
version: "3"
services:

  test:
    image: nginx
EOT
docker pull nginx
docker stack deploy mystack -c docker-compose.yml
sleep 10
docker stack rm mystack
docker swarm leave --force
docker network ls
```

**Describe the results you received:**

```
NETWORK ID          NAME                DRIVER              SCOPE
4569577938d3        bridge              bridge              local
dbc909e550ba        docker_gwbridge     bridge              local
8cb6e9320a38        host                host                local
s6dz39bbxf9x        mystack_default     overlay             swarm
35074e31cf14        none                null                local
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.0-beta4
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        d9934ea
 Built:             Tue May 14 06:40:00 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.0-beta4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       d9934ea
  Built:            Tue May 14 06:46:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by guillaumerose** [comment]
If I try to remove the Swarm network by hand, I can't.

```
$ docker service ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
4569577938d3        bridge              bridge              local
dbc909e550ba        docker_gwbridge     bridge              local
8cb6e9320a38        host                host                local
s6dz39bbxf9x        mystack_default     overlay             swarm
35074e31cf14        none                null                local
$ docker network rm mystack_default
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

**Comment by thaJeztah** [comment]
ping @arkodg PTAL; looks to be related to / introduced in https://github.com/moby/moby/pull/39174

(wondering if the remove should be attempted _both_ on ShutDown _and_ Remove)

**Comment by arkodg** [comment]
@guillaumerose  thanks for finding this regression
The code is bailing out here https://github.com/moby/moby/blob/994007dd89fdbb2272fc1f2623d03610e7195616/daemon/cluster/executor/container/controller.go#L373
and so `removeNetworks` is not getting executed, will send out a PR to address this 
soon

**Comment by guillaumerose** [comment]
I tried the latest 19.03.0-rc1 and this is not fixed. The network is still present. I ran the same script as above.

**Comment by thaJeztah** [comment]
This was merged after we started building the rc; the backport is still waiting to be merged https://github.com/docker/engine/issues/232

**Comment by stephen-turner** [comment]
@thaJeztah So to be clear: will this be in the RC in the end or not?

**Comment by thaJeztah** [comment]
It should get into an RC yes
