### ISSUE TITLE
'docker logs -f' hangs on logfile rotation with --max-file=1

### ISSUE THREAD

**Issue by Greek64** [moby/moby#39235]
**Description**
`docker logs -f` stops/hangs when the logfile rotates and `max-file` is configured to 1.  
Increasing the `max-file` fixes this problem.

**Steps to reproduce the issue:**
1. Start a container with a low `max-size` and `max-file=1` that prints a lot of output:
```
docker run -d --name hello_loop --log-driver=json-file --log-opt max-size=1k --log-opt max-file=1 alpine /bin/ash -c 'while true; do echo "Hello"; sleep 1; done'
```
2. Follow the output of the container:
```
docker logs -f hello_loop
```

**Describe the results you received:**

The `docker logs -f hello_loop` command stops showing the container output (hangs), even if the actual container is still outputting lines (can be seen by accessing the .log file directly)

**Describe the results you expected:**

The `docker logs -f hello_loop` command shows `Hello` messages until the command is interrupted or the container is stopped.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: WOLF-SERVER
ID: ENWT:3OUT:IXB6:VWQW:GRTZ:AOWZ:PKJN:2GAN:RLGK:UGO5:IBWU:USW7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Related Issues**

Amongst others:
#35332
#32038

Although in one of the linked issues it was mentioned that setting `max-file` to 1 
> is a bit of an edge case since it's weird to not retain some of the logs.

this is a bug in my eyes as this behavior is not documented anywhere (that I could find).  
If this behavior is to be expected, this should be documented accordingly.

**Comment by kolyshkin** [comment]
Reproduced locally, thank you for reporting this!

from `daemon/logger/loggerutils/logfile.go`:
> // Note: Using the follow option can become inconsistent in cases with very frequent rotations and max log files is 1.
> // TODO: Consider a different implementation which can effectively follow logs under frequent rotations.

This is definitely not the case with frequent rotation, as logging is pretty slow.

@Greek64 have you tried using the new `local` log driver yet? It should be better (albeit I'm not sure it's in 18.09).

// cc @cpuguy83

**Comment by kolyshkin** [comment]
It looks like this happens because in case of a single log file what happens in log producer (writer) is it closes the file and opens it with `O_TRUNC` flag, and neither event is reported via inotify mechanism back to log consumer (which only waits for "write", "rename" and "remove" events).


One way of fixing it would be to add a handler for `IN_CLOSE_WRITE` event (that is generated than a file that is opened for writing is closed), but for some reason fsnotify pkg does not even add this event to event mask when initalizing a watch (i.e. calling inotify_add_watch) so we can't catch it.

I don't see a fix at the moment but it's too late here... will take a fresh look soon.

**Comment by Greek64** [comment]
Yeah, I guessed this is not a simple fix.

Maybe it's just better to document it, and "shift" the responsibility to the user.
There is no real reason to use `max-file=1`. If it's because of size, just halve the `max-size` and use `max-file=2`.

**Comment by kolyshkin** [comment]
OK so both `write` and `truncate` generate the same event (called "modify" in inotify and "write" in fsnotify), we could distinguish between the two by doing stat on file and check if its size increased or decreased. A bit hackish but relatively easy to implement :-\

Other way is to make fsnotify work with CLOSE_WRITE events (see https://github.com/fsnotify/fsnotify/pull/252 for why it's not implemented).

choices, choces...

**Comment by cpuguy83** [comment]
Yeah it's not a very good library except for basic cases.
I'm not sure why cross-platform is an issue when these can be behind build flags... but 🤷‍♂️

**Comment by kolyshkin** [comment]
I have some ideas about how to fix this; will take a look once I have time (super busy atm)

**Comment by wataruoguchi** [comment]
Just leaving a note. Unfortunately, increasing the number of `max-file` wouldn't solve this (bumped up to 4 but still see the issue).

**Comment by kolyshkin** [comment]
> Unfortunately, increasing the number of max-file wouldn't solve this (bumped up to 4 but still see the issue).

@wataruoguchi I can't reproduce this locally, and what you see is definitely a different problem from what is described here. Please create a new issue for it, providing all the details. Thanks!
