### ISSUE TITLE
Daemon not listening on port 2375

### ISSUE THREAD

**Issue by Jacrys** [moby/moby#39230]
**Description**

**Steps to reproduce the issue:**
1. Set daemon to listen on 2375
2. try to run docker in WSL listening for host on 2375
3. fail

**Describe the results you received:**
```
ERROR: Couldn't connect to Docker daemon at http://localhost:2375 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
**Describe the results you expected:**
my container was started

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue worked until Windows build 1903. has worked once on 1903, but a restart broke the functionality again.

**Output of `docker version`:**
Windows
```
Docker version 18.09.2, build 6247962
```
WSL
```
Docker version 18.09.6, build 481bc77
```
**Output of `docker info`:**
Windows
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 63
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934GiB
Name: linuxkit-00155d36b60c
ID: 3O26:6H7D:ZWF6:CX35:GGDX:G76Q:APEL:GKYK:WHSO:CJZG:3IOE:WHL2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 48
 System Time: 2019-05-17T13:08:01.7783619Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```
WSL
```
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
WSL Ubuntu 18.04 running on Windows 1903

**Comment by thaJeztah** [comment]
> Set daemon to listen on 2375

How did you set up the daemon to listen on 2375? Note that when running Docker Desktop, `localhost` is `localhost` inside the VM in which the daemon runs; I think there's a proxy to forward this to the Windows host, but I'm not sure if all of that works in WSL (and may depend on "how" you configured the daemon to listen on tcp)

/cc @StefanScherer

**Comment by StefanScherer** [comment]
@Jacrys is this related to https://github.com/docker/for-win/issues/3924 ?

**Comment by StefanScherer** [comment]
On Windows 10 it's the `com.docker.proxy.exe` that opens the port 2375, not the engine.

**Comment by Jacrys** [comment]
docker/for-win#3546 did not show up in my initial search(es) on this issue. reserving the docker port seems to have resolved this issue.
