### ISSUE TITLE
docker run --user option doesn't respect volume mounts

### ISSUE THREAD

**Issue by eero-t** [moby/moby#39261]
**Description**

docker run "--user" option doesn't take volume mounts into account.

**Steps to reproduce the issue:**
1. docker run -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro --user grafana -it ubuntu:18.04 /bin/bash

**Describe the results you received:**
docker: Error response from daemon: linux spec user: unable to find user grafana: no matching entries in passwd file.

**Describe the results you expected:**
Docker uses the grafana user from the passwd file mounted from host.

**Additional information you deem important (e.g. issue happens only occasionally):**
Being able to specify a user defined on (mounted) host passwd file would make sharing data with host much more convenient.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
$ docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 146
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.2.0-rc1
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.669GiB
Name: testmachine
ID: FL5N:Q74W:ZIOA:6ZYZ:LEVX:SHDH:DPI5:EUS3:W33W:3PAR:AGN6:3JTE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy:
HTTPS Proxy:
No Proxy: localhost,127.0.0.0/8
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by eero-t** [comment]
Note: If the passwd file used at container build time happens to have "grafana" entry in passwd file, but host passwd file lists some other user with that UID, result is that:
* docker run succeeds
* I'm somebody else in the container than what I specified with the "--user" option.  E.g. user "foobar"

**Comment by eero-t** [comment]
When using numerical UID everything works fine.  Docker doesn't complain about it missing, and within container everything matches host.  It's just the user name matching that is broken.

**Comment by thaJeztah** [comment]
This is expected; the passwd file is mounted when the container is started, but the uid/gid has to be resolved before the container is created; see https://github.com/moby/moby/issues/22323#issuecomment-215449380, which won't work if the user is only known in the passwd file that is mounted.

This is not something that can be fixed, so let me close this issue (feel free to continue the conversation though)

**Comment by eero-t** [comment]
Ok, so issue is the API specified for runc, which requires resolving usernames before doing mounts, and as result only numeric UIDs work.

This should be mentioned in the Docker run --user option documentation.  Currently it's not documented.

**Comment by thaJeztah** [comment]
Yes, we might need better documentation for that; the ["run reference" docs shows](https://docs.docker.com/engine/reference/run/#user);

> root (id = 0) is the default user within a container. *The image developer can create additional users.* Those users are accessible by name. When passing a numeric ID, the user does not have to exist in the container.

But I agree it's not very clear; it should mention that (when using a username/groupname), that user/group must exist in the container / image.

We might also want to add a section in the `docker run` command page; https://docs.docker.com/engine/reference/commandline/run/ (there's no `--user` example in there currently)

I'm not sure we should document the bind-mounting case though, as it's not a standard thing to do 🤔

**Comment by eero-t** [comment]
> I'm not sure we should document the bind-mounting case though, as it's not a standard thing to do

I'm pretty sure it's not the only host resource sharing mechanism that suffers from this...
