### ISSUE TITLE
docker overlay network floating ip feature

### ISSUE THREAD

**Issue by lihao1994** [moby/moby#39284]
# docker overlay network floating issue

**Description**
three dockered VM: vm1 vm2 vm3,
each vm runs one container in one overlay network,
all container can ping each other.
I new a eth0:1 in container in vm1.
container in vm2 cannot ping eth0:1.

**Steps to reproduce the issue:**
1.I got three vms below.Docker is intalled and config consul to build an overlay network(not a swarm cluster)

| name | ip |
 |------ |------
| vm1 | 10.0.0.1|
| vm2 | 10.0.0.2|
| vm3 | 10.0.0.3|

2.run one container in each node

```shell
root@vm1:docker network create -d overlay --subnet=192.168.7.0/24 --gateway=192.168.7.1 formal_eth0
root@vm1:docker run --name container1 --net=formal_eth0 --ip=192.168.7.11 ${image} ${cmd}
root@vm2:docker run --name container2 --net=formal_eth0 --ip=192.168.7.12 ${image} ${cmd}
root@vm1:docker run --name container3 --net=formal_eth0 --ip=192.168.7.13 ${image} ${cmd}
```
3.new a floating ip
```shell
root@vm1:docker exec -it container1 ifconfig eth0:1 192.168.7.20
```
4.
```shell
root@vm2:docker exec -it container2 ping 192.168.7.20
```

**Describe the results you received:**
ping failed .
host uneachable

**Describe the results you expected:**

ping success
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:18:36 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
root@pekphicprd24183:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.92GiB
Name: pekphicprd24183
ID: B4TW:NKWO:JXEV:VP7H:XYGJ:4DX7:P5H6:HZ4A:YVO3:LYUG:QDUG:DT36
Docker Root Dir: /dockerData
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: consul://localhost:8500
Cluster Advertise: 10.0.0.1:2376
Insecure Registries:
。。。
Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2376 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by lihao1994** [comment]
@thaJeztah 
``docker network connect ${network} ${container}````
only this way can join the overlay network.Is there any other way?like,```docker network connect ${network} ${ip}```,
after this,we can use this ip in container as a float ip

**Comment by olljanat** [comment]
@lihao1994 I think that it is not possible. Can you please share some real world use case where you are planning to use this so we can look if there is other already exist way to end up to same result?

Also note that warning on `docker info` printout:
```
WARNING: API is accessible on http://0.0.0.0:2376 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
```
which tell that you are using very unsecure configuration which you should not do without very good reason.

**Comment by lihao1994** [comment]
@olljanat I can achieve two netcards in VM  like
![image](https://user-images.githubusercontent.com/24602093/61630882-7ac36b80-acbb-11e9-9afe-869d536fcfe9.png)
What about in a container?

My product need three vm to deploy with one entry IP.This IP is named floatIP.
I want to deploy my product in containers with modifing code.
But I can't find a way to fix floatIP.

**Comment by lihao1994** [comment]
fix by `arp -s ${ip_remote} ${mac_address}`
