### ISSUE TITLE
Run Windows Containers an linux containers together 

### ISSUE THREAD

**Issue by 93Kamuran** [moby/moby#39296]
Hi, 
I have a project that is used MssqlServer & Aspnet 4.6.2 & angular 7 & and some Cryptocurrency Nodes like litecoin, ethereum,  etc .  I would like to build them with docker than  I tried this on windows 10 pro machine. That means I achieve the run Linux and windows container together with docker experimental version. Next step I had to transport this simulation to windows server 2016. I tried to run containers together but I could not achieve this. After that, I thought maybe  I can do this on windows server 2019 v 1809 but  I could not too.
Can someone explain that Is this possible or impossible  to  build my project on windows servers Please

**Comment by olljanat** [comment]
@93Kamuran I highly recommend you to keep it simple and create separate Linux and Win Srv 2019 virtual servers for those different workloads and put them to same Swarm.

Even better option based on those components which you are using would be migrate your code to ASP.NET Core and SQL Server for Linux

Then you can use pure Linux only environment with much better performance and stability.
Look:
- https://hub.docker.com/_/microsoft-dotnet-core-aspnet
- https://hub.docker.com/_/microsoft-mssql-server

If you really want want to get those working on same Windows node you can look LCOW ( https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers )
but be aware that it is still very early beta and it will take years before it can be considered to be production ready.

Closing this one as it is not issue on Moby but feel free to ask if you have still questions.

**Comment by olljanat** [comment]
Derek close

**Comment by 93Kamuran** [comment]
@olljanat first of all thank you for answer... 

I'm new on docker and really do not know how to build a project on the swarm. You are right on ASpnet Core option. I thought about that before however, I have to two Large ASPnet 4.6 web APIs So to transport them to CORE is going to take time and I have to Publish the project as soon as possible.  After the broadcast, we can pass  APIs to aspnet Core.

So I have chosen the other option about the swarm. 

Can you please help me about dock swarm so how can ı  build it in Windows Server 2019, or can I?   

What SQL server version should I chose, On windows 10 I used mssqlserver Linux container. 

Can you share with me good articles about docker swarm? 

Thank you very much..

**Comment by olljanat** [comment]
If you are ready to spent some money for study then I can recommend these videos for Bret Fisher who is one of Docker captains:
- Docker basics: https://www.udemy.com/docker-mastery/
- Docker swarm basics: https://www.udemy.com/docker-swarm-mastery/

There looks to be discount still couple of hours :wink:

And super short guide about idea:
- Create Linux and Windows VMs to same network.
- Create new swarm on Linux with command: `docker swarm init`
- Copy/paste swarm worker join-token from Linux to Windows
- Build Linux apps on Linux and Windows apps on Windows using `docker build` command
- Create overlay network to swarm and deploy services to it so then can communicate with each others.

**Comment by 93Kamuran** [comment]
@olljanat ım really glad to talk with you. I was feeling  confused. Im gonna check the videos and try your advices to night  thanks 🙏🏻

**Comment by olljanat** [comment]
Nice to hear. You can also ping be on Docker community Slack if you need more help ;)

**Comment by 93Kamuran** [comment]
@olljanat  my friend ı want to ask one more question with apologies..    I cannot understand this. If when I use docker in Windows server like 19 or 16 not win Pro. Do I have to use Docker EE or can I use Docer CE  to ? and can I use docker windows application with EE if I have to use EE ..

**Comment by olljanat** [comment]
@93Kamuran techically Docker CE and EE is same. They just do more testing for EE.

Docker EE basic license is included to Windows Server license.
