### ISSUE TITLE
Hash Sum Mismatch

### ISSUE THREAD

**Issue by lz006** [moby/moby#39303]
---------------------------------------------------
Hash Sum Mismatch
---------------------------------------------------
**Description**
Building a debian based image does always fail due to a "hash sum mismatch".
It only occurs when tryin to install specific packages. Additionally this behavior can
only be observed while building the docker image in conjunction with a http proxy.

Same packages can be installed without any probs on docker host which is a debian stretch env as well as the docker base image. 

We tried many different scenarios and it turned out that this error must be in relation to docker
when sitting behind a http proxy. We also tried to decrease MTU of docker bridge -> without any success.

**Steps to reproduce the issue:**
1. prepare Dockerfile with following content:
FROM debian:9.4-slim
 
RUN echo 'Acquire::http { Proxy "http:/myhttpproxy:port"; };' >> /etc/apt/apt.conf.d/01proxy
 
RUN apt-get update
RUN apt-get install -y libfilter-perl=1.57-1 
2. run 'docker build .'

**Describe the results you received:**

Step 1/4 : FROM debian:9.4-slim
 ---> 3e235dbb0ba6
Step 2/4 : RUN echo 'Acquire::http { Proxy "http://myproxy:port"; };' >> /etc/apt/apt.conf.d/01proxy
 ---> Using cache
 ---> bb31790cf11f
Step 3/4 : RUN apt-get update
 ---> Using cache
 ---> fb50ea0f6a02
Step 4/4 : RUN apt-get install -y libfilter-perl=1.57-1
 ---> Running in dfa065eba231
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  cpp cpp-6 libgdbm3 libgmp10 libisl15 libmpc3 libmpfr4 libperl5.24 netbase
  perl perl-base perl-modules-5.24 rename
Suggested packages:
  cpp-doc gcc-6-locales perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl make
The following NEW packages will be installed:
  cpp cpp-6 libfilter-perl libgdbm3 libgmp10 libisl15 libmpc3 libmpfr4
  libperl5.24 netbase perl perl-modules-5.24 rename
The following packages will be upgraded:
  perl-base
1 upgraded, 13 newly installed, 0 to remove and 11 not upgraded.
Need to get 15.9 MB of archives.
After this operation, 67.2 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 perl-base amd64 5.24.1-3+deb9u5 [1345 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 perl-modules-5.24 all 5.24.1-3+deb9u5 [2722 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 libgdbm3 amd64 1.8.3-14 [30.0 kB]
Err:3 http://deb.debian.org/debian stretch/main amd64 libgdbm3 amd64 1.8.3-14
  Writing more data than expected (45697 > 30042)
  Hashes of expected file:
   - SHA256:fbce0e2500aa970ed03665d15822265ff8d31c81927b987ae34e206b9b5ab0b6
   - MD5Sum:4bd924fc8be5471a12d1e0204c74d6c3 [weak]
   - Filesize:30042 [weak]
Get:4 http://deb.debian.org/debian stretch/main amd64 libperl5.24 amd64 5.24.1-3+deb9u5 [3501 kB]
Err:4 http://deb.debian.org/debian stretch/main amd64 libperl5.24 amd64 5.24.1-3+deb9u5
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:ba980bf1bd644809f91d3bb9b07a8a3868d277c389d379fd394d7f61dfe7a602
   - MD5Sum:c1cd1c99e2fc7bafdc62a38aa35d2f06 [weak]
   - Filesize:3500808 [weak]
  Hashes of received file:
   - SHA256:61e8465367af69a52fe7f4300e9ea2e0b12a918a78beac41950b8a43be26aed9
   - MD5Sum:2d797837fadf625542bfe61ccf7a4814 [weak]
   - Filesize:18656 [weak]
  Last modification reported: Sat, 08 Apr 2017 20:13:54 +0000

**Describe the results you expected:**
should be a successful built

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:46 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Output of `docker info`:**

Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 10
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.957GiB
Name: debian
ID: YETJ:35QG:ADEG:6HXT:U5LI:DYQS:R2F7:HES3:EEXD:UFC7:TZYV:MQ4Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

Additional Info:
We know about the workaround that could be done by adding those pipelining settings to apt conf...
Acquire::http::Pipeline-Depth "0";
Acquire::http::No-Cache=True;
Acquire::BrokenProxy=true;

But this doesn't solve the root cause and we're not able to modify any Dockerfile in our use case therefore this is not a feasible solution for us. Our http proxy runs without caching and does nothing but forwarding.

At this point we're out of any further ideas.

Hopefully someone is able to identify what is causing this behavior.

Thanks in advance

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
