### ISSUE TITLE
LCOW: shm-size not honored in LCOW mode

### ISSUE THREAD

**Issue by kszicsillag** [moby/moby#39300]
**Description**

docker run's shm-size option is not honored while running linux containers in _Windows containers_ mode (LCOW).

**Steps to reproduce the issue:**
1. Enable LCOW
2. `docker run --rm --shm-size="1g" -it alpine /bin/sh`
3. `df -h`

**Describe the results you received:**
/dev/shm is 481MB.
Filesystem                Size      Used Available Use% Mounted on
overlay                  19.7G     40.0K     18.7G   0% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   481.2M         0    481.2M   0% /sys/fs/cgroup
**shm                     481.2M         0    481.2M   0% /dev/shm**
tmpfs                   481.2M         0    481.2M   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   481.2M         0    481.2M   0% /sys/firmware

**Describe the results you expected:**
If I switch back to Linux containers mode and running the same commands, the /dev/shm gets its expected size:
`docker run --rm --shm-size="1g" -it alpine /bin/sh`
`df -h`
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.4G      2.9G     52.5G   5% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   990.2M         0    990.2M   0% /sys/fs/cgroup
/dev/sda1                58.4G      2.9G     52.5G   5% /etc/resolv.conf
/dev/sda1                58.4G      2.9G     52.5G   5% /etc/hostname
/dev/sda1                58.4G      2.9G     52.5G   5% /etc/hosts
**shm                       1.0G         0      1.0G   0% /dev/shm**
tmpfs                   990.2M         0    990.2M   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   990.2M         0    990.2M   0% /sys/firmware

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.2
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows 10 Enterprise Version 1809 (OS Build 17763.503)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.95GiB
Name: **REDACTED**
ID: D562:4FVF:M3ZU:ZXAU:VMEP:YBML:D56X:SIOR:5PQR:ZLNA:LUXG:K2HG
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 33
 System Time: 2019-06-02T22:29:19.2498729+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by thaJeztah** [comment]
LCOW is not (yet) feature complete, and there's various options still not supported (also see https://github.com/moby/moby/issues/33850). I'm not on Windows myself; if `--mount` is supported, an alternative could be to manually mount a tmpfs (see the discussion on https://github.com/moby/moby/issues/26714#issuecomment-264303120), e.g.;

```bash
--mount type=tmpfs,dst=/dev/shm,tmpfs-size=1000000000
```

**Comment by kszicsillag** [comment]
`docker run --rm --mount type=tmpfs,dst=/dev/shm,tmpfs-size=1000000000 -it alpine /bin/sh` gives
> docker: Error response from daemon: invalid mount config for type "tmpfs": mount type unknown.

According to the docker docs, tmpfs mounts on Windows (host) are not supported:
https://docs.docker.com/storage/tmpfs/#limitations-of-tmpfs-mounts

> This functionality is only available if you’re running Docker on Linux.

**Comment by thaJeztah** [comment]
@jhowardmsft do you know if this is indeed not supported on LCOW (or if this is an over-enthusiastic validation rule, not taking LCOW into account?)

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
