### ISSUE TITLE
Zombie reaping not occurring as expected

### ISSUE THREAD

**Issue by cwpenhale** [moby/moby#39326]
I'm working on an issue, where I've got a test harness for reliable reproduction (and it's fairly simple), and I think I've tracked the source of the issue down to containerd. In any version after 17.09.1, the test fails. I think this is because of a change introduced in containerd 1.0.0. The test is essentially this:

1) create a container called bad_parent (we're using ubuntu:xenial) 
`docker run --init -itd --name bad_parent bad_parent /bin/bash`
2) run `docker exec bad_parent date` on a loop to show that the container is responsive
3) create a zombie pid
```
#!/usr/bin/env python
import os
import subprocess
import time


pid = os.fork()
if pid == 0:  # child
    # time.sleep(100)
    pid2 = os.fork()
    if pid2 != 0:  # parent
        while True:
            print('The zombie pid will be: {}'.format(pid2))
            time.sleep(30)
else:  # parent
    # os.waitpid(pid, 0)
    subprocess.check_call(('ps', 'xawuf'))
    time.sleep(5)
```
4) observe that the container stops responding

I've tried the latest containerd (compiled from git source). I've tried 18.09, but haven't been able to build rpms for 18.10 (build errors) from master. Any thoughts on where to go with this?

Here are the log files (in debug) for the issue: https://gist.github.com/cwpenhale/2eb23ffcb2abd2b4fccc509a50f2fd0a

Testing with the following host, virtualized in VirtualBox:
```
[root@localhost docker_exec_hang_issue]# uname -a
Linux localhost.localdomain 5.1.5-1.el7.elrepo.x86_64 #1 SMP Sat May 25 16:10:51 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost docker_exec_hang_issue]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

**Comment by thaJeztah** [comment]
I think there's an issue tracking this (reading on my phone, but i'll try to find it when I'm back at my computer)

**Comment by cwpenhale** [comment]
Hey @thaJeztah! I'll take another look though the issue backlog, thanks for the suggestion! ~Connor

**Comment by dwiyerr** [comment]
@thaJeztah did you get a chance to check for other occurrences of this issue? 
Irrespective, this is a simple recreate.  Who might be the best person to address this issue?

**Comment by thaJeztah** [comment]
Just did a quick search, and these were the ones I had in mind

- https://github.com/moby/moby/issues/38978 docker cannot terminate a container when processes linger after TERM
- https://github.com/moby/moby/pull/38980 Fixes #38978 should kill all children process when delete the task
- https://github.com/containerd/containerd/pull/3149 fix killall when use pidnamespace 

Although those could be specific to situations where the PID namespace is shared, so possibly different

**Comment by thaJeztah** [comment]
@kolyshkin @crosbymichael ptal

**Comment by cwpenhale** [comment]
Hey gang! Just checking in, is there any additional info or assistance we can provide here?

**Comment by cwpenhale** [comment]
Hey all, we haven't made any particular progress in sorting this out yet. Would strace information help the team understand whats going on?

**Comment by thaJeztah** [comment]
Had a chat with @crosbymichael, and this will be fixed by https://github.com/moby/moby/pull/39383, which is currently being reviewed
