### ISSUE TITLE
Regression due to CVE mitigation from 39292

### ISSUE THREAD

**Issue by tiborvass** [moby/moby#39348]
https://github.com/moby/moby/pull/39292 broke `docker cp` (discovered by @ehazlett trying to run `make` on buildkit repo)

@cpuguy83 @thaJeztah @AkihiroSuda @tonistiigi 

Repro:
```
rm -rf /tmp/out
docker build --iidfile=/tmp/iid - <<EOF
FROM scratch
COPY --from=alpine /etc/os-release /
EOF

cid=$(docker create $(cat /tmp/iid) foo)
mkdir -p /tmp/out
docker cp $cid:/ /tmp/out
ls /tmp/out/os-release
```

**Comment by tiborvass** [comment]
Specifically commit 3029e765e2

**Comment by anthonyleungdocker** [comment]
This is identified as a GA blocker, can you please provide a quick update COB today?

**Comment by seemethere** [comment]
Was not able to reproduce this with the following code:
```
#!/usr/bin/env bash

rm -f os-release

cid=$(docker create alpine:latest foo)
docker cp "${cid}:/etc/os-release" .

if [[ ! -f os-release ]]; then
    echo "WAS NOT COPIED OUT"
else
    echo "CP WORKED FINE"
fi
```

Is this unique only to `scratch` containers?

**Comment by seemethere** [comment]
Specifying `/os-release` specifically also works correctly as expected

```bash
#!/usr/bin/env bash

set -x

rm -rf /tmp/out
docker build --iidfile=/tmp/iid - <<EOF
FROM scratch
COPY --from=alpine /etc/os-release /
EOF

cid=$(docker create "$(cat /tmp/iid)" foo)
mkdir -p /tmp/out
docker cp "${cid}:/os-release" /tmp/out
if [[ ! -f /tmp/out/os-release ]]; then
    echo "FAIL"
else
    echo "SUCCESS"
fi
```

**Comment by seemethere** [comment]
Recursive `cp` also seems to function as expected too:
```bash
#!/usr/bin/env bash

rm -f os-release

tmpdir=$(mktemp -d)

cid=$(docker create alpine:latest foo)
docker cp "${cid}:/etc/" "${tmpdir}/"

if [[ ! -f ${tmpdir}/etc/os-release ]]; then
    echo "FAILED"
else
    echo "SUCCESS"
fi

rm -rf "${tmpdir}"
```

**Comment by tiborvass** [comment]
Thanks @seemethere !

**Comment by tiborvass** [comment]
So basically it's not about `scratch`, it's just about whether source of `docker cp` is `/` or not.

**Comment by seemethere** [comment]
Yup that seems to be the case,

<details>
<summary> repro script </summary>

```bash
#!/usr/bin/env bash

rm -f os-release

tmpdir=$(mktemp -d)

cid=$(docker create alpine:latest foo)
docker cp "${cid}:/" "${tmpdir}"

if [[ ! -f ${tmpdir}/etc/os-release ]]; then
    ls -latr "${tmpdir}"
    echo "FAILED"
else
    echo "SUCCESS"
fi

rm -rf "${tmpdir}"
```

</details>

Results:
* `18.09.6`: SUCCESS
* `19.03.0-rc2`: FAILED

**Comment by cpuguy83** [comment]
This seems to be happening because the code is special casing copying from root and passes down the source path as `filepath.Base(container.BaseFS())`.
In this case we chroot to `container.BaseFS()` but are trying to tar up  `filepath.Base(container.BaseFS())`.

As is, this is technically invalid input into `chrootarchive.Tar` and that should error out (it doesn't because it doesn't account for such a case).

So we need to update `chrootarchive.Tar` to error out in this case and fix the input from daemon/archive.go to give a proper chroot path.

**Comment by cpuguy83** [comment]
And here we are an example with chrootarchive.Tar setup to error out in this case:

```
FAIL: docker_cli_cp_from_container_test.go:403: DockerSuite.TestCpFromRoot

assertion failed:
Command:  /usr/local/cli/docker cp 65343c1e8a737f4a3553edb366af5676019e719c2243bbab124a0642b468c7e5:/ /tmp/test-cp-from-root870213619/foo
ExitCode: 1
Error:    exit status 1
Stdout:
Stderr:   Error response from daemon: source path /var/lib/docker/overlay2/977f4fb2befcb5f6c7afb646b059bd59fea93bf6d5710aec39e0a371859a1e70 must be within root path /var/lib/docker/overlay2/977f4fb2befcb5f6c7afb646b059bd59fea93bf6d5710aec39e0a371859a1e70/merged
```
