### ISSUE TITLE
how can i debug docker in mac

### ISSUE THREAD

**Issue by garyxiong123** [moby/moby#39350]
**Steps to reproduce the issue:**
1. i try to debug moby in my mac by run (/Users/gary/go/src/github.com/docker/docker/cmd/dockerd/docker.go), but it always notice me that i hava complier problem.

it notices me like this!

# github.com/docker/docker/daemon/config
daemon/config/config.go:153:2: undefined: BridgeConfig

**Comment by AkihiroSuda** [comment]
Run `make` in `$GOPATH/src/github.com/docker/docker`
