### ISSUE TITLE
What's the difference for next 3 repos?

### ISSUE THREAD

**Issue by atline** [moby/moby#39368]
I'm little confused about following repos, what's the relationship between them?

https://github.com/docker/engine
https://github.com/docker/docker-ce
https://github.com/moby/moby/

**Comment by thaJeztah** [comment]
- https://github.com/moby/moby/ is the upstream repository where development is done. When the "moby" project was created, repositories were reorganised to separate Docker's _products_ from the open source _projects_. When doing so, releases were no longer done from the open source projects, but from separate repositories within Docker's organisation on GitHub;
- The https://github.com/docker/engine repository is a mirror of the moby/moby repository, and used to maintain long-living branches for Docker releases (e.g. the https://github.com/docker/engine/tree/18.09 branch is used for the Docker 18.09 release). Those branches are used to backport fixes to releases. Other than backporting fixes, and tagging releases, no development is done in the docker/engine repository. 
- The https://github.com/docker/docker-ce repository is used for packaging (but might no longer be needed in future); it's used to combine the components that make up Docker CE; it contains snapshots of the "engine", "cli", and "packaging" scripts (https://github.com/docker/docker-ce/tree/v18.09.6/components). Those snapshots are created automatically, so no actual development is done in the repository.
