### ISSUE TITLE
hnsCall failed in Win32: An adapter was not found. (0x803b0006)

### ISSUE THREAD

**Issue by 93Kamuran** [moby/moby#39367]
Hi 
I'm working on docker swarm mode with 3 nodes whiches 2 windows server 2019 and 1 Ubuntu 18.04. 

when ı deploy my stack from docker-file my services shutting down suddenly. Protrainer and stefanscherer/traefik-windows services are shutting down. These services work only manager node. When ı look logs ı see that ''hnsCall failed in Win32: An adapter was not found. '' I already created an overlay network before deploying the stack.    Here is my docker-compose file 

version: '3.7'
networks:
  traefik-net:
    external:
      name: "traefik-net"
  backend: 
services: 
  'traefik':
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG     
    ports:
      - "8080:8080" 
      - "443:443"
      - "80:80"
    isolation: process
    networks:
      - "traefik-net"
    volumes:
      - .:C:/etc/traefik
      - C:\Users\Administrator\.docker:C:/etc/ssl:ro
       
    deploy:
      placement:
        constraints:
         - node.hostname == WIN-xx            
 
  'portainer':
    image: portainer/portainer 
    networks:
       - "traefik-net"      
    volumes:
      - ./portainerdata:C:/data
      - c:/test:C:/certs
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.hostname == WIN-xx 
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=Host:portainer.xx.com"

how can ı fix this? please help me.

**Comment by olljanat** [comment]
Duplicate with #39191
Closing...

**Comment by olljanat** [comment]
Derek close
