### ISSUE TITLE
Unable to launch stable service on swarm

### ISSUE THREAD

**Issue by niketagrawal** [moby/moby#39366]
**Description**

**Steps to reproduce the issue:**
1. Launch the swarm using docker swarm init
2. Deploy a service, example busybox: docker service create --name my_busybox --replicas 1 busybox
3. Service fails to launch so swarm repeatedly tries to launch the service 

**Describe the results you received:**
docker service create --replicas 1 --name busybox03 busybox
<service_id>
overall progress: 0 out of 1 tasks 
1/1: ready     [======================================>            ] 
verify: Detected task failure 
^COperation continuing in background.
Use `docker service ps <service_id>` to check progress.

**Describe the results you expected:**
Output of docker service ps <service_id>

ID                                    NAME                IMAGE           DESIRED STATE       CURRENT STATE
zej63w20zsee        busybox03.1         busybox:latest         Ready                   Ready 2 seconds ago
dzt4pq8d76b2         \_ busybox03.1     busybox:latest      Shutdown            Complete 2 seconds ago
ayrx7o9ha49c         \_ busybox03.1     busybox:latest       Shutdown            Complete 9 seconds ago
pt4esmyko2bq         \_ busybox03.1     busybox:latest      Shutdown            Complete 15 seconds ago
ytybssbnr98a         \_ busybox03.1     busybox:latest        Shutdown            Complete 22 seconds ago
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 6
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 15u84wjybm4mn3k154ucgjj35
 Is Manager: true
 ClusterID: jtjm58vt8zpvpbxlmhbavvjr0
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.0.145
 Manager Addresses:
  192.168.0.145:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-51-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.688GiB
Name: niket-HP-ProBook-440-G4
ID: 3WQN:NYZ2:FAUL:5GPM:27VC:O4TS:7W3T:CYOI:T4HF:Y7LH:7XKM:ZWQR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
The default command for the `busybox` image is `sh`, which requires a tty to be attached. otherwise it will start, and exit immediately after; docker will monitor the container, notice it exited, and start a new instance.

Try creating the service with the `--tty` option set, and it should stay running.


I'll close this issue, because this doesn't look like a bug, but feel free to continue the conversation after I closed
