### ISSUE TITLE
the problem applying cgroup configuration for process

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#39387]
**Description**
We reported an error when running docker. Does anyone know how to solve it?
the error is：
container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"No such device or address\""

**Steps to reproduce the issue:**
Deploy kubernetes+docker, run kube-apiserver, pod can not start, view log as：
container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"No such device or address\""

**Describe the results you received:**
container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"No such device or address\""

**Describe the results you expected:**
I want my apiserver to boot up properly.

**Output of `docker version`:**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:10 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:38:22 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 23
 Running: 17
 Paused: 0
 Stopped: 6
Images: 49
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 229
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.58-20180615.kylin.server.YUN+-generic
Operating System: Kylin 4.0.2
OSType: linux
Architecture: aarch64
CPUs: 16
Total Memory: 31.4GiB
Name: clusternode-10.200.72.30
ID: REML:BUTP:NIIV:SF66:VNKX:IC5I:5OPE:MWZB:VPJF:T4XK:24EZ:F2EA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry.inspurcloud.cn
 10.150.0.0/16
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a
Linux clusternode-10.200.72.30 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by timyinshi** [comment]
I solved this problem for cgroupfs by modifying docker's cgroup-driver.
Why do I have to use cgroupfs when my environment is arm-architected?Who can help to explain?

**Comment by crosbymichael** [comment]
@timyinshi cgroups is a linux feature, not a feature of arm or amd64, etc.  

cgroups limit the resource usage for containers such as cpu, memory, io, network.  

It sounds like something is different with the cgroup setup on your machines.  Does any container start on your system or just the api server fail?

**Comment by timyinshi** [comment]
@crosbymichael ok,thanks.

**Comment by qwert007** [comment]
how deal this questions?
