### ISSUE TITLE
Fork and update dependency of github.com/vishvananda/netns

### ISSUE THREAD

**Issue by carlosedp** [moby/moby#39404]
As spoke with @tonistiigi, we have been recently adding support to RISC-V architecture and one of Docker dependencies is `vishvananda/netns` but the repository haven't been updated for a while and there are already a couple of PRs waiting to get merged.

I believe that the best strategy on this is to have netns forked and maintained in moby since it's used by many projects.

I found the current architectures waiting for updates are:

* ppc64 - https://github.com/moby/moby/issues/39184
* mips64le - https://github.com/vishvananda/netns/pull/32
* riscv64 - https://github.com/vishvananda/netns/pull/34

cc. @tklauser

**Comment by tonistiigi** [comment]
@thaJeztah @ vishvananda

**Comment by tonistiigi** [comment]
@thaJeztah @vishvananda

**Comment by thaJeztah** [comment]
I"d rather not fork if not needed (as forking can easily to confusion); perhaps (more) collaborators could be added to the vishvananda/netns (and vishvananda/netlink) repositories?

/cc @aboch

**Comment by aboch** [comment]
We will look into it.

**Comment by thaJeztah** [comment]
Thanks Alessandro!

**Comment by thaJeztah** [comment]
https://github.com/vishvananda/netns/pull/34 and https://github.com/vishvananda/netns/pull/32 were merged (thanks @vishvananda!)

**Comment by carlosedp** [comment]
Thanks guys!
