### ISSUE TITLE
Is 'docker' available via curl script for Buster / Debian 10?

### ISSUE THREAD

**Issue by alexellis** [moby/moby#39417]
**Description**

Is 'docker' available via curl script for Buster / Debian 10?

A user reported that the 'docker' install script doesn't work on the new RPi4 - arm

https://twitter.com/8ice/status/1143591927880847360

**Steps to reproduce the issue:**
1. `curl -sLS https://get.docker.com | sudo sh`
2.
3.

**Describe the results you received:**

Waiting for user input

**Describe the results you expected:**

Docker to install / work.

```
pi@k4s-1:~ $ uname -a
Linux k4s-1 4.19.50-v7l+ #895 SMP Thu Jun 20 16:03:42 BST 2019 armv7l GNU/Linux
pi@k4s-1:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by alexellis** [comment]
```
pi@k4s-2:~ $ curl -LSs https://get.docker.com | sudo sh
# Executing docker install script, commit: 2f4ae48
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian 10 stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/raspbian 10 Release' does not have a Release file.
```

**Comment by alexellis** [comment]
@thaJeztah it'd be great to have this working whilst people are unboxing their shiny new RPi4s. Is there anyone who can look at this in your team?

Alex

**Comment by ndanyluk** [comment]
I can confirm the convenience script didn't work for me either.  There doesn't appear to be a buster section of the raspbian repo (https://download.docker.com/linux/raspbian/buster doesn't exist)

**Comment by thaJeztah** [comment]
No, there's no packages yet for raspbian buster; pull requests welcome to add something similar to https://github.com/docker/docker-ce-packaging/blob/master/deb/raspbian-stretch/Dockerfile

(there's probably some other locations in the packaging that would require `raspbian-buster` to be added)

After that, we'll likely have to add it to the containerd-packaging repository (which is not open-source yet)

**Comment by thaJeztah** [comment]
While those packages are not there, perhaps we could try if installing the `stretch` packages works, and temporarily modify the install script  to use `stretch` if the user is running `raspbian-buster`; https://github.com/docker/docker-install/blob/master/install.sh#L291-L301

**Comment by ndanyluk** [comment]
@thaJeztah I'm working on trying to build the package locally and I will try the stretch package in a bit, but I've gone ahead and opened a pull request for this here https://github.com/docker/docker-ce-packaging/pull/349

**Comment by ndanyluk** [comment]
I'm still working on getting buster set up on one of my Pi Zero Ws but I'll give the stretch package a shot then.

Also, is there any chance 18.09.6 could be added to the stretch repo?  It's currently at 18.09

**Comment by ndanyluk** [comment]
@thaJeztah I gave the modified build script a shot (using the stretch package instead of buster) but no luck.  It works to install docker-ce 18.09.0 but 18.09.0 doesn't run on the Pi Zero W (something is broken with the package).

I tried to roll back to 18.06.3 which has worked in the past on this Pi but that also failed using the stretch repo.  Here's the output of `sudo apt install docker-ce=18.06.3~ce~3-0~raspbian`

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following additional packages will be installed:
>   aufs-dkms aufs-tools cgroupfs-mount dkms git git-man libcurl3-gnutls liberror-perl libltdl7 pigz raspberrypi-kernel-headers
> Suggested packages:
>   aufs-dev python3-apport menu git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
> The following NEW packages will be installed:
>   aufs-dkms aufs-tools cgroupfs-mount dkms docker-ce git git-man libcurl3-gnutls liberror-perl libltdl7 pigz raspberrypi-kernel-headers
> 0 upgraded, 12 newly installed, 0 to remove and 3 not upgraded.
> Need to get 59.7 MB/60.1 MB of archives.
> After this operation, 335 MB of additional disk space will be used.
> Do you want to continue? [Y/n] Y
> Get:1 https://download.docker.com/linux/raspbian stretch/stable armhf docker-ce armhf 18.06.3\~ce\~3\-0\~raspbian [28.3 MB]
> Get:3 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20190620+1-1 [24.9 MB]
> Get:2 http://raspbian-us.ngc292.space/raspbian buster/main armhf pigz armhf 2.4-1 [47.2 kB]
> Get:4 http://raspbian.mirror.constant.com/raspbian buster/main armhf dkms all 2.6.1-4 [74.4 kB]
> Get:5 http://raspbian.mirror.constant.com/raspbian buster/main armhf aufs-dkms all 4.19+20190211-1 [183 kB]
> Get:6 http://raspbian.mirror.constant.com/raspbian buster/main armhf aufs-tools armhf 1:4.14+20190211-1 [103 kB]
> Get:7 http://raspbian-us.ngc292.space/raspbian buster/main armhf cgroupfs-mount all 1.4 [6,276 B]
> Get:8 http://raspbian.mirror.constant.com/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4 [291 kB]
> Get:9 http://raspbian.mirror.constant.com/raspbian buster/main armhf liberror-perl all 0.17027-2 [30.9 kB]
> Get:10 http://raspbian.mirror.constant.com/raspbian buster/main armhf git-man all 1:2.20.1-2 [1,619 kB]
> Get:11 http://raspbian.mirror.constant.com/raspbian buster/main armhf git armhf 1:2.20.1-2 [4,202 kB]
> Fetched 59.7 MB in 33s (1,832 kB/s)
> Selecting previously unselected package pigz.
> (Reading database ... 40289 files and directories currently installed.)
> Preparing to unpack .../00-pigz_2.4-1_armhf.deb ...
> Unpacking pigz (2.4-1) ...
> Selecting previously unselected package dkms.
> Preparing to unpack .../01-dkms_2.6.1-4_all.deb ...
> Unpacking dkms (2.6.1-4) ...
> Selecting previously unselected package aufs-dkms.
> Preparing to unpack .../02-aufs-dkms_4.19+20190211-1_all.deb ...
> Unpacking aufs-dkms (4.19+20190211-1) ...
> Selecting previously unselected package aufs-tools.
> Preparing to unpack .../03-aufs-tools_1%3a4.14+20190211-1_armhf.deb ...
> Unpacking aufs-tools (1:4.14+20190211-1) ...
> Selecting previously unselected package cgroupfs-mount.
> Preparing to unpack .../04-cgroupfs-mount_1.4_all.deb ...
> Unpacking cgroupfs-mount (1.4) ...
> Selecting previously unselected package libltdl7:armhf.
> Preparing to unpack .../05-libltdl7_2.4.6-9_armhf.deb ...
> Unpacking libltdl7:armhf (2.4.6-9) ...
> Selecting previously unselected package docker-ce.
> Preparing to unpack .../06-docker-ce_18.06.3\~ce\~3-0\~raspbian_armhf.deb ...
> Unpacking docker-ce (18.06.3\~ce\~3-0\~raspbian) ...
> Selecting previously unselected package libcurl3-gnutls:armhf.
> Preparing to unpack .../07-libcurl3-gnutls_7.64.0-4_armhf.deb ...
> Unpacking libcurl3-gnutls:armhf (7.64.0-4) ...
> Selecting previously unselected package liberror-perl.
> Preparing to unpack .../08-liberror-perl_0.17027-2_all.deb ...
> Unpacking liberror-perl (0.17027-2) ...
> Selecting previously unselected package git-man.
> Preparing to unpack .../09-git-man_1%3a2.20.1-2_all.deb ...
> Unpacking git-man (1:2.20.1-2) ...
> Selecting previously unselected package git.
> Preparing to unpack .../10-git_1%3a2.20.1-2_armhf.deb ...
> Unpacking git (1:2.20.1-2) ...
> Selecting previously unselected package raspberrypi-kernel-headers.
> Preparing to unpack .../11-raspberrypi-kernel-headers_1.20190620+1-1_armhf.deb ...
> Unpacking raspberrypi-kernel-headers (1.20190620+1-1) ...
> Setting up aufs-tools (1:4.14+20190211-1) ...
> Setting up libcurl3-gnutls:armhf (7.64.0-4) ...
> Setting up dkms (2.6.1-4) ...
> Setting up liberror-perl (0.17027-2) ...
> Setting up raspberrypi-kernel-headers (1.20190620+1-1) ...
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.50+
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.50-v7+
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.50-v7l+
> Setting up libltdl7:armhf (2.4.6-9) ...
> Setting up aufs-dkms (4.19+20190211-1) ...
> Loading new aufs-4.19+20190211 DKMS files...
> It is likely that 4.19.50+ belongs to a chroot's host
> Building for 4.19.50+, 4.19.50-v7+ and 4.19.50-v7l+
> Building initial module for 4.19.50+
> Error! Bad return status for module build on kernel: 4.19.50+ (armv6l)
> Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
> dpkg: error processing package aufs-dkms (--configure):
>  installed aufs-dkms package post-installation script subprocess returned error exit status 10
> Setting up pigz (2.4-1) ...
> Setting up git-man (1:2.20.1-2) ...
> Setting up cgroupfs-mount (1.4) ...
> Setting up docker-ce (18.06.3\~ce\~3-0\~raspbian) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
> Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
> Setting up git (1:2.20.1-2) ...
> Processing triggers for systemd (241-5+rpi1) ...
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for libc-bin (2.28-10+rpi1) ...
> Errors were encountered while processing:
>  aufs-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by raspberrycoulis** [comment]
It is possible to install Docker manually using the .deb files located [here](https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/) - you need to install the dependencies first `containerd.io_*_armhf.deb` and `docker-ce-cli_*~debian-buster_armhf.deb` then install the Docker .deb file. I have this working on my Pi 4 right now.

**Comment by ndanyluk** [comment]
No luck so far on my Pi Zero.  I tried using the packages @raspberrycoulis mentioned, but it errors out when setting up docker-ce.  My guess is that those packages are 64bit and will error out on the armv6 processor in the zero/pi1

Output from dpkg -i docker-ce:

> sudo dpkg -i docker-ce_18.09.7~3-0~debian-buster_armhf.deb
> (Reading database ... 41456 files and directories currently installed.)
> Preparing to unpack docker-ce_18.09.7~3-0~debian-buster_armhf.deb ...
> Unpacking docker-ce (5:18.09.7~3-0~debian-buster) ...
> Setting up docker-ce (5:18.09.7~3-0~debian-buster) ...
> update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode
> Job for docker.service canceled.
> invoke-rc.d: initscript docker, action "start" failed.
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>    Active: failed (Result: core-dump) since Sat 2019-06-29 11:38:22 EDT; 90ms ago
>      Docs: https://docs.docker.com
>   Process: 30541 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=dumped, signal=SEGV)
>  Main PID: 30541 (code=dumped, signal=SEGV)
> 
> Jun 29 11:38:20 pi-five systemd[1]: Starting Docker Application Container Engine...
> Jun 29 11:38:22 pi-five systemd[1]: docker.service: Main process exited, code=dumped, status=11/SEGV
> Jun 29 11:38:22 pi-five systemd[1]: docker.service: Failed with result 'core-dump'.
> Jun 29 11:38:22 pi-five systemd[1]: Stopped Docker Application Container Engine.
> dpkg: error processing package docker-ce (--install):
>  installed docker-ce package post-installation script subprocess returned error exit status 1
> Processing triggers for systemd (241-5+rpi1) ...
> Errors were encountered while processing:
>  docker-ce

**Comment by raspberrycoulis** [comment]
Yes @danyluk, the PiZero is a different processor so you’d need to use the correct .debs.

**Comment by nagubal** [comment]
The manual installation mentioned by @raspberrycoulis worked for me on Raspberry Pi 3 running Raspbian Buster: 
```
pi@raspberrypi:~ $ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
pi@raspberrypi:~ $ docker -v
Docker version 18.09.7, build 2d0083d
```

**Comment by alexellis** [comment]
I can also confirm this worked on RPi3 with Raspbian Lite:

```sh
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.6-3_armhf.deb
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce_18.09.7~3-0~debian-buster_armhf.deb


dpkg -i containerd.io_1.2.6-3_armhf.deb
dpkg -i docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb
dpkg -i docker-ce_18.09.7~3-0~debian-buster_armhf.deb
sudo usermod pi -aG docker
# log out / in again
```

```sh
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.50-v7+
Operating System: Raspbian GNU/Linux 10 (buster)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 926.1MiB
Name: alexellis
ID: WTDI:FLMB:TSZA:5LHR:ZWZV:E3LB:ZQ2E:K7AN:K3FJ:25OH:WRHA:LHSX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

$ docker run -ti alpine:3.8
Unable to find image 'alpine:3.8' locally
3.8: Pulling from library/alpine
6a2a63c54ac7: Pull complete 
Digest: sha256:04696b491e0cc3c58a75bace8941c14c924b9f313b03ce5029ebbc040ed9dcd9
Status: Downloaded newer image for alpine:3.8
/ # ping -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=53 time=18.148 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 18.148/18.148/18.148 ms
/ # 
```

Kubernetes via k3s is working, but I'm not sure if everything is configured correctly for Swarm. Perhaps something to check on Raspbian Buster when there is an official package in the Buster repository for Docker-ce.

**Comment by thunder2k** [comment]
> I can also confirm this worked on RPi3 with Raspbian Lite:
> 
> ```shell
> wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.6-3_armhf.deb
> wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb
> wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-ce_18.09.7~3-0~debian-buster_armhf.deb
> 
> 
> dpkg -i containerd.io_1.2.6-3_armhf.deb
> dpkg -i docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb
> dpkg -i docker-ce_18.09.7~3-0~debian-buster_armhf.deb
> sudo usermod pi -aG docker
> # log out / in again
> ```
> 
> ```shell
> $ docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 18.09.7
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
> runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
> init version: fec3683
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.19.50-v7+
> Operating System: Raspbian GNU/Linux 10 (buster)
> OSType: linux
> Architecture: armv7l
> CPUs: 4
> Total Memory: 926.1MiB
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
> 
> WARNING: No swap limit support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support
> 
> $ docker run -ti alpine:3.8
> Unable to find image 'alpine:3.8' locally
> 3.8: Pulling from library/alpine
> 6a2a63c54ac7: Pull complete 
> Digest: sha256:04696b491e0cc3c58a75bace8941c14c924b9f313b03ce5029ebbc040ed9dcd9
> Status: Downloaded newer image for alpine:3.8
> / # ping -c 1 8.8.8.8
> PING 8.8.8.8 (8.8.8.8): 56 data bytes
> 64 bytes from 8.8.8.8: seq=0 ttl=53 time=18.148 ms
> 
> --- 8.8.8.8 ping statistics ---
> 1 packets transmitted, 1 packets received, 0% packet loss
> round-trip min/avg/max = 18.148/18.148/18.148 ms
> / # 
> ```
> 
> Kubernetes via k3s is working, but I'm not sure if everything is configured correctly for Swarm. Perhaps something to check on Raspbian Buster when there is an official package in the Buster repository for Docker-ce.

This is not working for me:
```
sudo dpkg -i docker-ce_18.09.7~3-0~debian-buster_armhf.deb
Selecting previously unselected package docker-ce.
(Reading database ... 158345 files and directories currently installed.)
Preparing to unpack docker-ce_18.09.7~3-0~debian-buster_armhf.deb ...
Unpacking docker-ce (5:18.09.7~3-0~debian-buster) ...
Setting up docker-ce (5:18.09.7~3-0~debian-buster) ...
update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-07-12 22:54:25 IST; 23ms ago
     Docs: https://docs.docker.com
  Process: 16301 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 16301 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--install):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (241-5+rpi1) ...
Errors were encountered while processing:
 docker-ce
```

Any ideas? I've already installed the other 2 packages and containerd is running fine:
```
sudo service containerd status
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-07-12 22:53:34 IST; 2min 59s ago
     Docs: https://containerd.io
 Main PID: 15312 (containerd)
    Tasks: 14
   Memory: 15.8M
   CGroup: /system.slice/containerd.service
           └─15312 /usr/bin/containerd

Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.494979466+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.con
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.495044391+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.con
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.495091223+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.495135926+01:00" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.co
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.497961380+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.498163542+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.cont
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.498317946+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.co
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.498435869+01:00" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.499010078+01:00" level=info msg=serving... address="/run/containerd/containerd.sock"
Jul 12 22:53:34 raspberrypi4 containerd[15312]: time="2019-07-12T22:53:34.499250980+01:00" level=info msg="containerd successfully booted in 0.153559s"
```

**Comment by alexellis** [comment]
I've written up a brief blog post here to document the work-arounds (including getting Raspbian Stretch!)

https://blog.alexellis.io/how-to-fix-docker-for-raspbian-buster/

https://twitter.com/alexellisuk/status/1150851990668435457

**Comment by alexellis** [comment]
I'm getting a seg-fault with the packages once installed on RPi Zero (armv6)

```
pi@blinkt:~ $ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: core-dump) since Fri 2019-07-19 09:44:53 BST; 13s ago
     Docs: https://docs.docker.com
  Process: 19997 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=dumped, signal=SEGV)
 Main PID: 19997 (code=dumped, signal=SEGV)

Jul 19 09:44:52 blinkt systemd[1]: Failed to start Docker Application Container Engine.
Jul 19 09:44:53 blinkt systemd[1]: Stopped Docker Application Container Engine.
pi@blinkt:~ $ /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock 
Segmentation fault
```

@tianon @thaJeztah did we stop building as `GOARM=6`?

**Comment by wordlesswind** [comment]
Maybe we can wait for his https://download.docker.com/linux/raspbian/ release?
But it's only nightly version now.

**Comment by ndanyluk** [comment]
@alexellis none of the rpi docker packages have worked for me on my Pi Zeros since 18.06.3. (18.09.0 has failed every time I've attempted it and there hasn't been a 18.09.1+ release ported to raspbian stable in months)

There's several issues opened against it, but the largest thread is moby/moby #38175

**Comment by alexellis** [comment]
I had the same experience with RPi Zero and I've pinged @thaJeztah to ask if the ARM version was changed.

Please use my documented work-around which is to use Raspbian Stretch. I've even provided a link. It works unless you can think of a reason why you need Buster over Stretch?

Alex

**Comment by ndanyluk** [comment]
I am using stretch for now.  I have one Pi 3B+ and one Pi Zero W that I migrated to Buster to test out.

The Pi 3B+ works just fine with the stretch package like you mentioned, but the buster nightly works as well in my testing.

The Pi Zero W is unfortunately not working with stretch 18.09.0 or the buster nightly unfortunately.  I even tried installing the static binary but no luck.  It seems stretch 18.06.3 is the last known ARMv6 compatible version.

I just wanted to echo that I had the same experience you did

**Comment by thaJeztah** [comment]
Is the segfault in dockerd or in containerd? (I seem to recall it was containerd that was the problem)?

@seemethere might know more

**Comment by ndanyluk** [comment]
@thaJeztah I think it's in containerd.  I just tried the install again on my Pi Zero W and tried running containerd standalone and got a segfault immediately

**Comment by ndanyluk** [comment]
It also seems that someone might have found the commit where everything breaks, but since there's no source available for containerd (per their comment) they couldn't debug further.
 https://github.com/moby/moby/issues/38175#issuecomment-460386014

**Comment by robwilkes** [comment]
Looks like they compiled stable release on 26th July:
https://download.docker.com/linux/raspbian/dists/buster/pool/stable/armhf/

And it installs fine via:
curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

**Comment by alexellis** [comment]
A big thank you to the maintainers and to everyone who helped fix this 🎉  [I've updated my blog](https://blog.alexellis.io/how-to-fix-docker-for-raspbian-buster/).

**Comment by alexellis** [comment]
(Since the issue I raised has been fixed, I would encourage people to consider raising a new issue rather than asking any technical questions about Docker on RPi in this thread) 🙏
