### ISSUE TITLE
注解不生效

### ISSUE THREAD

**Issue by zxgit** [moby/moby#39421]
原：
$container = new Container(new DefinitionSource($serverDependencies, $scanDirs, new Scanner()));
是因为没有把要忽略的文件引入，只导入了默认的mixin
解决方案：
$ignoreAnnotations = $annotations['scan']['ignore_annotations'];
$container = new Container(new DefinitionSource($serverDependencies, $scanDirs, new Scanner($ignoreAnnotations)));

**Comment by AkihiroSuda** [comment]
doesn't seem related to this repo
