### ISSUE TITLE
ioutils: remaining race bug in bytespipe

### ISSUE THREAD

**Issue by lzhfromustc** [moby/moby#39438]
**Description**

When a contributor fixed [a data race bug in 2016](https://github.com/moby/moby/pull/23317), it seemed he or she forgot to fix another very similar data race in the same function, and this is still in **Master** branch now. The remaining bug can be easily fixed.

Sorry I can't provide inputs to trigger this bug since I detected this by a static checker, but the inconsistent in code is quite obvious: `bp.closeErr` is read/write 8 times; 7 out of 8 times it is protected by `bp.mu.Lock()`; 1 out of 8 times it is read without a Lock 

**The patch in 2016:**
Location: moby/pkg/ioutils/bytespipe.go Line: 127-140
```Go
func (bp *BytesPipe) Read(p []byte) (n int, err error) {
	bp.mu.Lock()
	if bp.bufLen == 0 {
		if bp.closeErr != nil {
			bp.mu.Unlock()
			return 0, bp.closeErr // THIS MAY ALSO NEED CHANGE
		}
		bp.wait.Wait()
		if bp.bufLen == 0 && bp.closeErr != nil {
+++                     err := bp.closeErr
			bp.mu.Unlock()
+++                     return 0, err
---		        return 0, bp.closeErr
		}
	}
```

**Additional information you deem important:**
I read related code and I don't think the data race can really happen _(please see `func (bp *BytesPipe) Close() error` at line 121)_, both in the version in 2016 and current version. However, the inconsistence in code may be a threat in the future.

**Comment by thaJeztah** [comment]
Thanks! Are you interested in contributing, and opening a pull request?

**Comment by lzhfromustc** [comment]
@thaJeztah Sure. I will open a pull request right now.

**Comment by thaJeztah** [comment]
Awesome, thanks!
