### ISSUE TITLE
Containers won't restart after sudden poweroff

### ISSUE THREAD

**Issue by Minipada** [moby/moby#39450]
**Description**
I am starting containers via the docker engine api. Containers are started properly with a restart=always, but if a sudden reboot happens right after they won't be restarted. This matters in a context of small embedded boards which are turned off an on often by unplugging/plugging power cable.

**Steps to reproduce the issue:**
1. Start container via docker engine
2. Wait they started (around 5 seconds)
3. Turn off power (not a soft shutdown) and turn ON

**Describe the results you received:**
The containers are not started. The log indicates 3 times (and 3 containers were started via the engine, so I think it's one per failed container)

```
Unable to complete atomic operation, key modified
```

**Describe the results you expected:**
Containers restarting

**Additional information you deem important (e.g. issue happens only occasionally):**
* I don't think this is a bug but I would at least like to understand what's happening in the background, and why they are not prepared to be restarted.
* The docker directory is on another partition
* The storage is an eMMC

I precise it is using a flash because it may be the case that docker information is not yet written on the flash with a sudden reboot. Would there be any optimization to do in the OS to improve/test this?

**Output of `docker version`:**

```
Client:
 Version:	18.03.0
 API version:	1.37
 Go version:	go1.9.7
 Git commit:	0f1bb35
 Built:	Fri Mar  1 11:45:16 2019
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.7
  Git commit:	708b068d3095c6a6be939eb2da78c921d2e945e2
  Built:	Fri Mar  1 11:44:39 2019
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 107
Server Version: 18.03.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c.m (expected: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c)
runc version: N/A (expected: 4fc53a81fb7c994640722ac585fa9ca548971871)
init version: fec3683-dirty (expected: 949e6facb7738)
Kernel Version: 4.9.126-intel-pk-standard
Operating System: Poky (Yocto Project Reference Distro) 2.5.1 (sumo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.708GiB
Name: oblac-drives-78684d4d
ID: DLAG:E462:FEZH:EKIR:WM7Y:3RLC:TVPM:KMC2:FM6B:G2Y7:FATH:2VXI
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by crosbymichael** [comment]
Can you restart these manually with `docker start <id>` or is that broken as well?

**Comment by Minipada** [comment]
Thanks for asking. It is not working this way. It seems it is an old issue by the way https://stackoverflow.com/questions/47807197/rpi-docker-does-not-restart-containers-after-power-failure

I looked the docker events, and after the containers are created and started, nothing happens. Also, i took a look at the docker daemon (in debug mode), nothing.
Can it be the daemon schedules some tasks and for some unknown reason the system is executing them much later?

FYI, it is running on a stripped down linux, with the minimum kernel features. There's no kernel message indicating any activity and no other process running in the background. I can't see why the system would execute the operations later but it seems this is what is happening. i am preparing an OS now to observe the i/o flow with dtsat and see if anything is blocking. That's the only track I can think of now. What do you think?

**Comment by Minipada** [comment]
I edited the configuration in /etc/fstab and added the parameter `sync` in the partition containing the docker folder. It now never fails. Would you have an explanation?

**Comment by Minipada** [comment]
So, I found a workaround. Executing the command `sync` directly after starting the containers work. I think docker schedule some tasks, containers are started but paths are not yet registered in /var/lib/docker. sync forces those tasks to be done. I still don't have details as I don't know what's happening in the background

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
