### ISSUE TITLE
Linux Containers on Windows (LCOW) feature vs Running Linux VM on Windows

### ISSUE THREAD

**Issue by basickarl** [moby/moby#39458]
As the following question on SO asks:
https://stackoverflow.com/questions/52968480/linux-containers-on-windows-lcow-feature-vs-running-linux-vm-on-windows

Apart from being able to have control over the isolated VM's via the docker cli on the Windows Server host, is there any other benefit to using LCOW over my own VM?

**Comment by guhuajun** [comment]
Personally speaking, using virtualbox is enough for me.
But some developer s may have the needs for LCOW.

**Comment by cpuguy83** [comment]
I'm going to close this since it's not really an issue or something that anyone can really answer for you.

A VM isolated container on Windows will be much lighter weight than spinning up a full vm, at least.
Beyond that there may be other trade-offs one way or another.
