### ISSUE TITLE
debugfs：How to mount the debugfs in container?

### ISSUE THREAD

**Issue by wenxuwan** [moby/moby#39457]
Hi, my app in container want read the /sys/kernel/debug/tracing/trace_marker file , but i can't mount the debugfs to container inside file system. Can you give some comments??

**Comment by cpuguy83** [comment]
The simplest thing to do would be to set `--cap-add SYS_ADMIN` on your container, however this is also the insecure option.

You could, possibly, mount debugfs as a volume, but you'd have to check what the kernel parameters are.
There are some examples in https://docs.docker.com/engine/reference/commandline/volume_create/ at the bottom of the page for other filesystems:

### tmpfs
```
$ docker volume create --driver local \
    --opt type=tmpfs \
    --opt device=tmpfs \
    --opt o=size=100m,uid=1000 \
    foo
```

### btrfs
```
$ docker volume create --driver local \
    --opt type=btrfs \
    --opt device=/dev/sda2 \
    foo
```

Then you can just use these like a normal volume.
I am however not familiar with debugfs personally so I don't know if this would work as expected or not.
