### ISSUE TITLE
Failed to publish container's port on window 10, 1903

### ISSUE THREAD

**Issue by frankero** [moby/moby#39463]
**Description**

I have an image based on Windows Server Core 2016 (microsoft/windowsservercore:ltsc2016)
and ran it on Windows Enterprise 10, 1903 with command like **docker run -d -p 10010:80 imagename**.
But failed to push the container's port to host.

**Steps to reproduce the issue:**
1.docker run -d -p 80:80 --name nginx sixeyed/nginx:windowsservercore

**Describe the results you received:**

**Describe the results you expected:**
succeed to publish container's port on Windows Enterprise 10, 1903

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:
```

**Output of `docker info`:**

```
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
Operating System: Windows 10 Enterprise Version 1903 (OS Build 18362.113)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.999GiB
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 37
 System Time: 2019-07-04T10:31:15.9879078+03:00
 EventsListeners: 1
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by frankero** [comment]
this issue is similar to **#36990 Publishing container ports in Windows Server 2019 does not work**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
