### ISSUE TITLE
May I compile docker with gccgo, to generate a fully dynamic binary?

### ISSUE THREAD

**Issue by TeaganZemel** [moby/moby#39473]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
gccgo is not really tested.
You can make a dynamically linked binary with "hack/make.sh dynbinary"

**Comment by TeaganZemel** [comment]
thanks, I compile docker-client by hack/make.sh dynbinary successfuly. But, the symbol in main.main is local, such as time.Now.
![image](https://user-images.githubusercontent.com/20655475/60936726-a9773480-a300-11e9-81fe-45cd6d1a9261.png)
I wanna the symbol is external, resoluted by plt and got, for the purpose that I can hook it by LD_PRELOAD.
such as the demo program compiled by "go build -compiler=gccgo", as shown.
![image](https://user-images.githubusercontent.com/20655475/60936777-e511fe80-a300-11e9-95cf-04d1a6f4c1f7.png)
Can you show me some method?

**Comment by cpuguy83** [comment]
Seems like since you are going to have to compile this yourself anyway, why not customize the code directly instead of hooking LD_PRELOAD?
