### ISSUE TITLE
docker, external symbol, gccgo

### ISSUE THREAD

**Issue by TeaganZemel** [moby/moby#39482]
hi, I compile docker-client by "hack/make.sh dynbinary" successfuly. 
![image](https://user-images.githubusercontent.com/20655475/60956469-78652700-a335-11e9-812b-31a1a2dce51b.png)

But, the symbol in main.main is local, such as time.Now.
![image](https://user-images.githubusercontent.com/20655475/60956489-831fbc00-a335-11e9-8194-06a8840dccfb.png)
when the demo program is compiled by "go build -compiler=gccgo", the symbol is external, as shown.
![image](https://user-images.githubusercontent.com/20655475/60956578-aea2a680-a335-11e9-84d6-3a0afd71db46.png)

Also, the different compile methods will result the different time.now.
![image](https://user-images.githubusercontent.com/20655475/60956716-f0335180-a335-11e9-8107-9dc099b08951.png)

![image](https://user-images.githubusercontent.com/20655475/60956888-3e485500-a336-11e9-91ee-e75977cc8f27.png)

I wanna compile docker to a pure dynamically linked binary, meaning that the symbol is external, resoluted by plt and got. For the purpose that I can hook it by LD_PRELOAD. 
May someone show me some method?

**Comment by TonyHaircut** [comment]
This really confused me too.  Why this happens?

**Comment by justincormack** [comment]
The standard Go compiler does not use a dynamically linked standard library, unlike gccgo. This isn't a Docker issue, you should ask on one of the Go support forums.
