### ISSUE TITLE
--network-add effectively kills container if it had a port published in host only mode

### ISSUE THREAD

**Issue by mjramtech** [moby/moby#39486]
Service fails to start properly after adding a 2nd network interface if it had a port published in host only mode. I observed this behaviour with a container running keycloak, but suspect the problem is generic.

**Steps to reproduce the issue:**
1. Run service on a specific network, publishing a port in host only mode:
docker service create --with-registry-auth --replicas 1 --network private --constraint 'node.hostname == some_host' --name keycloak-private --publish published=8080,target=8080,mode=host,protocol=tcp registry.some_reg.net/keycloak_project:latest

2.
Add a second network interface:
docker service update --network-add public keycloak-private

**Describe the results you received:**
The service is still listed, but the last thing in its log is JBoss receiving SIG_TERM. The service hasn't successfully restarted following the addition of the 2nd network.

The addition of the 2nd network works as expected without the --publish arg.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thaJeztah** [comment]
Do you have more details? I'm not able to reproduce an issue with a different image; could it be that the service running in your container is not working if multiple network interfaces are found inside the container?


Here's what I used to reproduce;


1. Create both overlay networks (`private`, `public`)

```bash
docker network create -d overlay --scope=swarm private
docker network create -d overlay --scope=swarm public
```

2. Create the service using the `private` network:

```bash
docker service create \
  --network private \
  --name repro-39486 \
  --publish published=8080,target=80,mode=host \
  nginx:alpine
```

3. Wait for the service to be up, and verify the service is functioning by visiting `http://<host ip>:8080`


4. Attach the `public` network:

```bash
docker service update --network-add public repro-39486
```

5. Wait for the service update to reconcile, and verify the service is functioning by visiting `http://<host ip>:8080`

**Comment by mjramtech** [comment]
I will re-run your same test in my environment asap. But for now, I can say that the service works fine with two NICs, because this is its normal state. The thing that differed from the ordinary was publishing the port - usually no ports are published (only accessed within swarm).

**Comment by mjramtech** [comment]
I can't reproduce this with another container, and am not in a position to re-run the exact test raised against, so we'll assume I was seeing things.

I know what I saw, though ;-)

**Comment by mjramtech** [comment]
I just got this error again and now remember something I forgot before. At first I see the following line in response to the network add command:

1/1: no suitable node (scheduling constraints not satisfied on 4 nodes; host-mo… [truncation not mine]

But then it gets overwritten on the console with this:

overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged

As though it decides it can't perform the action then changes its mind?

I now believe this is an intermittent bug. Is there anything specific you want me to test?

**Comment by thaJeztah** [comment]
The "no suitable node" may be if the previous task has not yet fully shut-down (networking removed); 
I see `host-mo…` at the end; host-mode publishing means that ports of the containers backing the service are directly published on the host, not using the SwarmKit load-balancer, which means that only a single instance of the service can run per node.

So likely; 
- docker told the previous task to shut-down
- started deploying, the new task
- found that the port was not (yet) available
- tried again (port was released)
- started the new task
- verified that the service has converged

**Comment by mjramtech** [comment]
I didn't stop/start the service with any speed, so the previous instance not having completely cleaned up I guess can linger?

I'm not convinced everything is quite as it should be, but can't outright demonstrate otherwise now, so I'll leave it with you as to whether you think this warrants anything further.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
