### ISSUE TITLE
docker run can not work normally on mips64

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#39480]
**Description**

hello,everyone,When i run docker on MIPS architecture and use command: docker run -it imagename sh , the container started,but it can't interact properly,it is stuck,and is ping all the time.if want to launch docker run command must to kill docker,  Does anyone know how to solve this problem?

my command:
docker run -it registry.icp.com:5000/library/os/neokylin-7.4-mips64el:5.0.0 bash

error:
7月 10 14:54:04 localhost.localdomain dockerd[25791]: time="2019-07-10T14:54:04.840645965+08:00" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
7月 10 14:54:04 localhost.localdomain dockerd[25791]: time="2019-07-10T14:54:04.869564796+08:00" level=debug msg="Calling POST /v1.38/containers/fc54b47a68008e3767d1b0420df5f4c8484958c849c59f440bb11738d3a5d366/resize?h=33&w=191"
7月 10 14:54:23 localhost.localdomain dockerd[25791]: time="2019-07-10T14:54:23.823483576+08:00" level=debug msg="Calling GET /_ping"
7月 10 14:54:23 localhost.localdomain dockerd[25791]: time="2019-07-10T14:54:23.825152647+08:00" level=debug msg="Calling GET /v1.38/containers/json"

**Steps to reproduce the issue:**
docker run -it registry.icp.com:5000/library/os/neokylin-7.4-mips64el:5.0.0 bash

**Describe the results you received:**
it can't interact properly,it is stuck,and is ping all the time.if want to launch docker run command must to kill docker

**Describe the results you expected:**
i want to use docker normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.12.5
 Git commit:        d7080c1
 Built:             Tue Jul  9 03:52:44 2019
 OS/Arch:           linux/mips64le
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       d7080c1
  Built:            Tue Jul  9 06:08:46 2019
  OS/Arch:          linux/mips64le
  Experimental:     false

**Output of `docker info`:**

```
Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 162
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e.m (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Kernel Version: 3.10.0-862.9.1.ns7_4.37.mips64el
Operating System: NeoKylin Linux Server 7.0 (loongson)
OSType: linux
Architecture: mips64el
CPUs: 8
Total Memory: 31.23GiB
Name: localhost.localdomain
ID: QWSA:7ETN:XXAF:QRK3:24H3:KHSI:E6MO:YSGV:3M6U:RF3Y:OFLT:7MJ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 52
 Goroutines: 77
 System Time: 2019-07-10T15:02:44.481423552+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 registry.icp.com:5000
 127.0.0.0/8
Live Restore Enabled: true

```

**Comment by timyinshi** [comment]
i find the error :
17156 <... ioctl resumed> , 0xc00002be50) = -1 ENOTTY (Inappropriate ioctl for device)
17156 ioctl(1, TIOCNXCL <unfinished ...>
17157 <... nanosleep resumed> NULL)     = 0
17156 <... ioctl resumed> , 0xc00002be50) = -1 ENOTTY (Inappropriate ioctl for device)
who know how to resolve the error?thanks.

**Comment by timyinshi** [comment]
area/runtime

**Comment by justincormack** [comment]
We do not support Docker on any MIPS architecture, and while I know a few people have tried to run it, mainly I have seen errors. Go is not well tested on MIPS, and there are all sorts of potential problems, eg the `ioctl` values on MIPS are non standard, so may well be wrong somewhere... I recommend you start with `runc`, and run all the test suites, fix the issues, and then move on to `containerd` and then `docker`.

**Comment by timyinshi** [comment]
@justincormack thanks,we will try to fix the error,can you give me some suggests abort the error?

**Comment by npu21** [comment]
we have run check-config.sh (https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh ) ,but still got no clue

warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.10.0-862.9.1.ns7_4.37.mips64el ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
    (cgroup swap accounting is currently enabled)
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_RESOURCE_COUNTERS: missing
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_NETPRIO_CGROUP: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled (as module)
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_FTP: enabled (as module)
    - CONFIG_NF_NAT_TFTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_TFTP: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

**Comment by thaJeztah** [comment]
Let me close this one for housekeeping, but feel free to continue the conversation
