### ISSUE TITLE
Windows 2019 Swarm: restart of Docker Service causes occasional HNS error on restart

### ISSUE THREAD

**Issue by drnybble** [moby/moby#39498]
**Description**

Occasionally on restarting the Docker service an error occurs on startup.
When this happens, the ingress network is not configured correctly.

**Steps to reproduce the issue:**
Run Docker is Swarm mode.
Restart-Service docker
ipconfig

**Describe the results you received:**
No vEthernet adapter present

**Describe the results you expected:**
vEthernet adapter present as used by ingress networking

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens perhaps 1 in 8 restarts on my system. Looks like some kind of race condition.

I wasn't able to reproduce it by manually stopping and then starting the service.

My observation is that a successful restart shows the following Host-Network-Service events:

HNS-Endpoint-Remove
HNS-Endpoint-Remove
HNS-Endpoint-Remove
HNS-Network-Remove
[restart]
HNS-Layer-Create
HNS-Network-Create

A failure shows the following Host-Network-Service events:
HNS-Endpoint-Remove
HNS-Endpoint-Remove
HNS-Endpoint-Remove
HNS-Network-Remove
[restart]
Error:
HNS-Network-Create :- 
 Network id = '{7d659485-3d1a-4150-8a39-d541a0231c16}'.
 Network type = 'UNKNOWN'.
  Result code = '0x803B0006'. 
  
This docker event corresponds to this error:
	Failed creating ingress network: hnsCall failed in Win32: An adapter was not found. (0x803b0006)

Note in the failure case there is no event for HNS-Layer-Create.

Attached hns.evtx and System.evtx files corresonding to first, a successful restart; and then second, an unsuccessful restart.

[hns_failure.zip](https://github.com/moby/moby/files/3383914/hns_failure.zip)

**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client: Docker Engine - Enterprise
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        b81f47481d
 Built:             06/27/2019 17:58:58
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       b81f47481d
  Built:            06/27/2019 17:57:09
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.7
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: active
 NodeID: fopsptvbl0laeocq011t27t4f
 Is Manager: true
 ClusterID: n0y8yrnzgzg2i1sv766zbqnep
 Managers: 1
 Nodes: 3
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.16.3.153
 Manager Addresses:
  172.16.3.153:2377
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.529)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16GiB
Name: p1dist1
ID: CEAR:USPM:ANIC:FPPQ:IDBR:HNYF:TRIS:XJ7P:K4ER:W5OV:V5PQ:3KJL
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM with two NICs.

**Comment by drnybble** [comment]
https://docs.docker.com/config/daemon/#enable-debugging says that if I enable debug that logs will be in AppData\Local. Is this true for running as a service?

**Comment by drnybble** [comment]
I got into a situation where I had two vEthernet adapters instead of just one. No other Swarm nodes could route to my node, and after I rebooted the machine became inaccessible to remote desktop. Not ready for production!

**Comment by daschott** [comment]
@drnybble does it help if you pin down the NIC you want Docker Swarm ingress network to use?
You can do this via:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced#bind-a-network-to-a-specific-network-interface 

Can you collect HNS  but also docker debug logs simultaneously? This could help determine if this is a Docker issue or a HNS issue.

**Comment by drnybble** [comment]
I have pinned this to one of my NICs and still had the issue. It is currently being pursued via Microsoft Premier Support case 119072324004399

**Comment by drnybble** [comment]
I have closed this case for now since I was unable to reproduce it. Not 100% sure if it is resolved by pinning the NIC or latest version of Windows/Docker or I just can't hit the timing condition to make it occur but closing for now.
