### ISSUE TITLE
flaky DockerSwarmSuite tests

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39499]
Looking at the latest [PRs in moby/moby](https://github.com/moby/moby/pulls), common `integration-cli` tests are failing because they are known flaky in the `DockerSwarmSuite`. The top ones seem to be:

1. `TestAPISwarmLeaderElection` #32673
1. `TestSwarmClusterRotateUnlockKey` #38885
1. `TestAPISwarmRaftQuorum` #34988
1. `TearDownTest ` #33041

@dperny are these failures representative of a bug in swarmkit? The `DockerSwarmSuite` flaky failures are popping up more often now and are slowing down time to merge PR.

**Comment by andrewhsu** [comment]
@dperny perhaps this is related? https://github.com/moby/moby/issues/34051#issuecomment-511073471

**Comment by thaJeztah** [comment]
^^ we're looking at a possible root-cause for all the failures; basically comes down to _all_ SwarmKit tests would be flaky; https://github.com/moby/moby/issues/34051#issuecomment-511073471

If multiple daemons are started (or the daemon of a previous test did not yet fully clean up), tests might fail because we're always using the same port; https://github.com/moby/moby/blob/ec86547244fa329148a096db56f9ade77a7ce7eb/vendor/github.com/hashicorp/memberlist/config.go#L226-L231

@ehazlett found that in libnetwork, the problem is circumvented by incrementing the port for each test; https://github.com/docker/libnetwork/blob/67b7970d93313b2c6032e4e8742baec92fabbdb3/networkdb/networkdb_test.go#L42-L45

We'll probably need something similar in the tests in this repository

**Comment by andrewhsu** [comment]
I setup a jenkins job to only run `DockerSwarmSuite` tests every hour from moby/moby master branch starting last night: https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/

As of this morning, the past 13 runs had 4 job failures, 30% flaky failure rate. The flaky tests that failed:
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/11/
  * `DockerSwarmSuite.TestAPISwarmLeaderElection`
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/17/
  * `DockerSwarmSuite.TestAPISwarmLeaderElection`
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/19/
  * `DockerSwarmSuite.TestAPISwarmRaftQuorum`
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/20/
  * `DockerSwarmSuite.TestAPISwarmLeaderElection`
  * `DockerSwarmSuite.TestSwarmPublishAdd`

**Comment by thaJeztah** [comment]
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/11/
  * `DockerSwarmSuite.TestAPISwarmLeaderElection`

[d2fd0aff23b9e.log](https://github.com/moby/moby/files/3398093/d2fd0aff23b9e.log)

```
time="2019-07-16T06:47:32.599960933Z" level=error msg="error in agentInit: failed to create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 7946: listen tcp 0.0.0.0:7946: bind: address already in use"
time="2019-07-16T06:47:32.600122651Z" level=error msg="error in agentInit: failed to create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 7946: listen tcp 0.0.0.0:7946: bind: address already in use"
time="2019-07-16T06:47:33.898940496Z" level=error msg="agent: session failed" backoff=100ms error=EOF module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:33.991710447Z" level=error msg="agent: session failed" backoff=300ms error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:34.197134441Z" level=error msg="agent: session failed" backoff=700ms error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:34.403867414Z" level=error msg="agent: session failed" backoff=1.5s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:35.708997201Z" level=error msg="agent: session failed" backoff=3.1s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:35.740304412Z" level=error msg="agent: session failed" backoff=6.3s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:41.981927409Z" level=error msg="agent: session failed" backoff=8s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:43.280885345Z" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\""
time="2019-07-16T06:47:50.236309808Z" level=error msg="agent: session failed" backoff=8s error="session initiation timed out" module=node/agent node.id=s7p8zxtck7ooiedh07a96jeg8
time="2019-07-16T06:47:54.193506013Z" level=error msg="Error getting node s7p8zxtck7ooiedh07a96jeg8: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
time="2019-07-16T06:47:54.193609355Z" level=error msg="Handler for GET /v1.41/nodes/s7p8zxtck7ooiedh07a96jeg8 returned error: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
time="2019-07-16T06:47:54.196667386Z" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
time="2019-07-16T06:47:59.197835912Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=d2fd0aff23b9e
```

[d87c59aa8a3bc.log](https://github.com/moby/moby/files/3398098/d87c59aa8a3bc.log)


```
time="2019-07-16T06:47:33.885254931Z" level=error msg="error in agentInit: failed to create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 7946: listen tcp 0.0.0.0:7946: bind: address already in use"
time="2019-07-16T06:47:33.885415671Z" level=error msg="error in agentInit: failed to create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 7946: listen tcp 0.0.0.0:7946: bind: address already in use"
time="2019-07-16T06:47:33.898077065Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = Unknown desc = context canceled" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:33.898142873Z" level=error msg="agent: session failed" backoff=300ms error="context canceled" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:34.014577100Z" level=error msg="agent: session failed" backoff=700ms error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:34.647166017Z" level=error msg="agent: session failed" backoff=1.5s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:34.750448905Z" level=error msg="agent: session failed" backoff=3.1s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:35.639664833Z" level=error msg="agent: session failed" backoff=6.3s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:41.054735491Z" level=error msg="agent: session failed" backoff=8s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:48.050561823Z" level=error msg="agent: session failed" backoff=8s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:49.186834178Z" level=error msg="agent: session failed" backoff=8s error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\"" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:47:52.375498265Z" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2477: connect: connection refused\""
time="2019-07-16T06:47:59.323089620Z" level=error msg="agent: session failed" backoff=8s error="session initiation timed out" module=node/agent node.id=o7junfkxtj20cnczifimw3gpy
time="2019-07-16T06:48:04.203355561Z" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
```

[d301ffb08464f.log](https://github.com/moby/moby/files/3398099/d301ffb08464f.log)

```
time="2019-07-16T06:47:30.514981812Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh2" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh2: no such file or directory"
time="2019-07-16T06:47:30.514999579Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh3" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh3: no such file or directory"
time="2019-07-16T06:47:30.515017753Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh1" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh1: no such file or directory"
time="2019-07-16T06:47:33.897390418Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = Canceled desc = context canceled" module=node/agent node.id=l1o0zj646atllkvphw94t9srr
time="2019-07-16T06:47:33.897596501Z" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=o7junfkxtj20cnczifimw3gpy node.session=nhneyk2meeb34xhf4nlakt3j5
time="2019-07-16T06:47:33.897727304Z" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=s7p8zxtck7ooiedh07a96jeg8 node.session=jccuctq8ekaoqpqp2zjq2rx0f
time="2019-07-16T06:47:33.898669698Z" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
```

**Comment by andrewhsu** [comment]
Failure rate still at 30% with 9 failures in the past 30 runs:
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/31/
  * DockerSwarmSuite.TestAPISwarmLeaderElection
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/34/
  * DockerSwarmSuite.TestAPISwarmLeaderElection
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/37/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/43/
  * DockerSwarmSuite.TestAPISwarmLeaderElection
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/45/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/51/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/54/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/56/
  * DockerSwarmSuite.TestServiceHealthRun

Longest runs of success is 5.

**Comment by andrewhsu** [comment]
🔥❄️ #39531

**Comment by andrewhsu** [comment]
From the last 30 runs (as of today), failure rate has dropped to 6%:
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/222/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/207/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey

**Comment by andrewhsu** [comment]
I have another jenkins job that is running all of the unit tests and integration tests and the failure rate is higher, 6 job failures from the last 30 runs which is 20% failure rate: https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/

And of the 6 flaky test failures, 4 of them are caused by `DockerSwarmSuite.TestSwarmClusterRotateUnlockKey`.

So the TestSwarmClusterRotateUnlockKey test is definitely top dog in flakiness for DockerSwarmSuite tests at the moment.

**Comment by andrewhsu** [comment]
🤞🏼#39616

**Comment by andrewhsu** [comment]
From the last 30 runs, 3 of the jobs failed (10% failure rate) because of a DockerSwarmSuite flaky test:
* https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/252/
  * DockerSwarmSuite.TestServiceLogsSince
* https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/242/
  * DockerSwarmSuite.TestServiceLogsSince
* https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/234/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey

**Comment by andrewhsu** [comment]
The good news: last 30 of the hourly runs of just DockerSwarmSuite tests on their own were all green: https://jenkins.dockerproject.org/job/andrewhsu/job/DockerSwarmSuite/

However, there is still flakiness when running all of the test suites together. The DockerSwarmSuite failures only amount to 2 job failures of the past 30 (6.7% failure rate): https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/

* https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/592/
  * DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
* https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/572/
  * DockerSwarmSuite.TestAPISwarmServicesMultipleAgents

**Comment by andrewhsu** [comment]
@dperny I saw a successful run of the `DockerSwarmSuite.TestSwarmClusterRotateUnlockKey` test in 71 seconds (see [bundles.tar.gz](https://jenkins.dockerproject.org/job/Docker-PRs/55421/) for daemon logs): https://jenkins.dockerproject.org/job/Docker-PRs/55421/console

And a flaky failure in 60 seconds (see [janky-bundles.tar.gz](https://ci.docker.com/public/blue/organizations/jenkins/moby/detail/PR-39682/39/artifacts) for daemon logs under directory `bundles/test-integration/3/DockerSwarmSuite.TestSwarmClusterRotateUnlockKey/d7d99f6461cb3/`): https://ci.docker.com/public/blue/organizations/jenkins/moby/detail/PR-39682/39/pipeline

**Comment by andrewhsu** [comment]
In the past 25 jobs triggered to run against code merged to `master` branch, I haven't found any `DockerSwarmSuite` failures which is fantastic: https://ci.docker.com/public/blue/organizations/jenkins/moby/activity?branch=master

The same `integration-cli` tests are also [run on amd64 for PRs](https://github.com/moby/moby/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3C%3D2019-09-30) and I spotted only one failure of flaky test `DockerSwarmSuite.TestSwarmLockUnlockCluster` https://github.com/moby/moby/pull/39975#issuecomment-536786416

As for addressing flaky `DockerSwarmSuite` test failures that were called out when this issue was first opened, I feel this issue can now be closed.
