### ISSUE TITLE
Filed to pull image from docker hub

### ISSUE THREAD

**Issue by Paniraj2010** [moby/moby#39505]
**Description**

**Steps to reproduce the issue:**
1.kind: service
apiVersion: v1
metadata:
	name:helloworldservice
spec:
	selector:
		app: hello-world
	ports:
		protocol: "TCP"
		port: 8080
		targetport: 80
		nodeport: 3001
	type:LoadBalancer
	
	

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
          - containerPort: 3000
2.**Failed to pull image "tutum/hello-world": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for GATEWAY.SPANSERVICES.COM, not registry-1.docker.io** 
3.

**Failed to pull image "tutum/hello-world": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for GATEWAY.xxx.COM, not registry-1.docker.io **

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Sounds like you have a MITM proxy intercepting your request.
Do you need to be using HTTP_PROXY or HTTPS_PROXY to do pulls, or perhaps some other configuration?

Closing since this doesn't really look like a Docker issue, but feel free to discuss.
Thanks!
