### ISSUE TITLE
Canonical Dockerfile

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39512]
Would like to have an up-to-date top-level canonical `Dockerfile` for the repo.

For instance, I'd like to use the new `build -o` feature to get the `dockerd`, `docker-proxy`, `docker-init` binaries:
```
$ export DOCKER_BUILDKIT=1
$ docker build --platform=local -o . git://github.com/moby/moby
```

As in the way https://github.com/docker/buildx/blob/master/Dockerfile is structured.

@tonistiigi @tiborvass @thaJeztah et al. are there other best practices that should go into the `Dockerfile` for moby/moby to make developer, PR checks, or build/release life easier?

**Comment by thaJeztah** [comment]
We don't have buildkit enabled yet in CI, and the CLI is pinned to 17.06, so that complicates things a bit.

I had a branch doing that, but I'm not sure I pushed it and (erm) it may have gone lost in a broken drive on my machine

**Comment by thaJeztah** [comment]
Also see https://github.com/moby/moby/pull/39340

**Comment by thaJeztah** [comment]
> and the CLI is pinned to 17.06, so that complicates things a bit

Doh! that's for the tests of course, but doesn't apply to the main Dockerfile
