### ISSUE TITLE
can not build docker for mips

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#39534]
**Description**
Hello, everyone. I have a question. When I built docker, I found that it was built through the alpine container, but our machine is MIPS, and alpine does not have the image of MIPS.Who can help?

**Describe the results you received:**
i can not  build docker for mips

**Describe the results you expected:**
i want to build docker for mips

**Output of `docker version`:**

```
18.06.3
```

**Comment by justincormack** [comment]
Alpine does not have a MIPS port at present. Musl libc does have mips, mips64 and mipsn32 ports, so porting is possible, but it is going to be a lot of work, and there is a lack of availability of suitable hardware for doing this kind of work, as all the available mips machines are very slow and have little memory.

**Comment by timyinshi** [comment]
ok,thanks.
