### ISSUE TITLE
Use standard DCO bot in moby org

### ISSUE THREAD

**Issue by justincormack** [moby/moby#39538]
The standard DCO bot https://probot.github.io/apps/dco/ which works as a github app is nicer than Gordon for DCO purposes, eg it can be installed for the whole org, and has fewer permissions and we don't need to maintain it. I propose to install this and remove the DCO functionality from Gordon.

**Comment by thaJeztah** [comment]
ping @andrewhsu @cpuguy83 WDYT? I was discussing this earlier today with Justin, and agree that this would be probably a better option

**Comment by cpuguy83** [comment]
You had me sold at "we don't need to maintain it".
The one issue is the old Docker DCO.

**Comment by thaJeztah** [comment]
@tiborvass can you help enabling this? Looks like I don't have admin access in the Moby org, so cannot enable it (at least; `moby` doesn't show up in the list of orgs to pick when trying to enable that bot);

1. https://probot.github.io/apps/dco/
2. [Deploying](https://github.com/probot/dco/blob/master/docs/deploy.md)
3. [Required Status Checks](https://github.com/probot/dco/blob/master/docs/required-statuses.md)

**Comment by tiborvass** [comment]
Done for moby repo on moby org. I followed the instructions, but I left out number 9 on [Required Status Checks](https://github.com/probot/dco/blob/master/docs/required-statuses.md)

**Comment by tiborvass** [comment]
I also kept the old dco check around for a few days

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/39783 for an example

**Comment by thaJeztah** [comment]
closing this one; disabling the old DCO is tracked through https://github.com/moby/moby/issues/39538
