### ISSUE TITLE
move windows RS1 checks to run on master branch after PR merge

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39532]
Discussed with @ddebroy: we already have PR checks to moby master branch run on windows RS1 and RS5. Would be simpler and faster to just run the RS5 checks on the PR code before merge and have RS1 and RS5 checks run on the master branch after merge.

**Comment by thaJeztah** [comment]
does anyone actively check master though? RS1 is quite different from RS5, and it's easy to introduce breakage; eg looks like RS1 might be broken currently https://github.com/moby/moby/pull/39068#issuecomment-511608097

**Comment by ddebroy** [comment]
Thinking about this a bit more, its probably safer to leave PR coverage for RS1 to especially look for breakages around major changes like @thaJeztah pointed out.

**Comment by thaJeztah** [comment]
Generally RS1 isn't problematic, unless the machines need reprovisioning. That's being worked on to automate, so I don't mind them running on each PR

**Comment by andrewhsu** [comment]
I have trust issues with our current windows RS1 nodes: #39556

**Comment by andrewhsu** [comment]
This issue has been addressed with PR #39789
