### ISSUE TITLE
Flaky test: TestFrequency

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39544]
First spotted in PR #39528 [windowsRS1 PR check](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25893/console):
```
--- FAIL: TestFrequency (0.53s)
    splunk_test.go:929: Unexpected number of requests 8
time="2019-07-15T18:54:46Z" level=warning msg="Error while sending logs" error="splunk: failed to send event - 500 Internal Server Error - " module=logger/splunk
```

Looks like the test is taking into account time for context switch: https://github.com/moby/moby/blob/9b0097a/daemon/logger/splunk/splunk_test.go#L927

But not sure why it would be flaky...could there be extra windows services running in background that eats resources?

cc @ddebroy

**Comment by ddebroy** [comment]
Fix submitted: https://github.com/moby/moby/pull/39552
