### ISSUE TITLE
PR checks on windowsRS1 fail to start then time out

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39556]
For example, PR #39531 windowsRS1 [logs show a timeout](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25948/console):
```
INFO: Commit hash is 096a7afd37
INFO: Nuke-Everything...
INFO: Container count on control daemon to delete is 0
Build timed out (after 230 minutes). Marking the build as failed.
Set build name.
New build name is '#39531'
Build was aborted
```

**Comment by andrewhsu** [comment]
More failed PR checks on windowsRS1:
* #39543 console log https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25936/console
* #39540 console log https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25931/console

**Comment by andrewhsu** [comment]
I see a pattern in these failures. All seem to fail on azure-windows-rs1-5 so I've taken the node offline. https://jenkins.dockerproject.org/computer/azure-windows-rs1-5/

**Comment by thaJeztah** [comment]
they likely have to be cleaned up?

**Comment by andrewhsu** [comment]
This is now happening on [azure-windows-rs1-3](https://jenkins.dockerproject.org/computer/azure-windows-rs1-3/)
* #39575 console log https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25982/console
* #39535 console log https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25975/console

**Comment by jhowardmsft** [comment]
@andrewhsu @ddebroy @thaJeztah 

They're all redeployed, but looks like someone might have changed the Jenkins key used to connect to them. ERROR: Server rejected the 1 private key(s) for jenkins.

**Comment by andrewhsu** [comment]
Closing this issue because the moby PR checks on `windowsRS1` nodes were pet machines that are no longer used now that the [PR checks are migrated](https://github.com/moby/moby/issues/39773) to a new jenkins setup that dynamically spins up windows server 2016 nodes.
