### ISSUE TITLE
how to limit total file descriptor number of the container level

### ISSUE THREAD

**Issue by qingwave** [moby/moby#39558]
**What happend**
In our k8s cluster, there are some containers using too many fd, I want to limit the fd usage. However, the ulimit (set `--default-ulimit` for dockerd or set `--ulimit`) only limit the per process usage rather than container level [see here](http://man7.org/linux/man-pages/man2/getrlimit.2.html). Is there a way to limit the fd usage in a container level.

>        RLIMIT_NOFILE
>              This specifies a value one greater than the maximum file
>              descriptor number that can be opened by this process.
>              Attempts (open(2), pipe(2), dup(2), etc.)  to exceed this
>              limit yield the error EMFILE.  (Historically, this limit was
>              named RLIMIT_OFILE on BSD.)

**Comment by cpuguy83** [comment]
It is per process, but each process should inherit the limit of its parent. Since docker only starts one process, the limit should apply to the whole container.

**Comment by qingwave** [comment]
> It is per process, but each process should inherit the limit of its parent. Since docker only starts one process, the limit should apply to the whole container.

you can have a try, ulimit nofile only limit the process itself without subprocesses.

**Comment by qingwave** [comment]
run container alpine:3.9 with `--ulimit nofile=100:100`, run two `ab` to create 90 sockets.

```bash
/ # ulimit -a
-f: file size (blocks)             unlimited
-t: cpu time (seconds)             unlimited
-d: data seg size (kb)             unlimited
-s: stack size (kb)                8192
-c: core file size (blocks)        unlimited
-m: resident set size (kb)         unlimited
-l: locked memory (kb)             64
-p: processes                      unlimited
-n: file descriptors               100
-v: address space (kb)             unlimited
-w: locks                          unlimited
-e: scheduling priority            0
-r: real-time priority             0
/ # 
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ # 
/ # cat fd.sh 
#!/bin/bash
echo "start"
ab -n 1000000 -c 90 http://61.135.169.125:80/ &
ab -n 1000000 -c 90 http://61.135.169.125:80/ &
sleep 3600

/ # 
/ # sh +x fd.sh &
/ # start
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 61.135.169.125 (be patient)
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 61.135.169.125 (be patient)

/ # ps -ef |grep fd
   56 root      0:00 sh +x fd.sh
/ # pstree 56
sh-+-2*[ab]
   `-sleep
/ # pstree -p 56
sh(56)-+-ab(57)
       |-ab(58)
       `-sleep(59)
/ # 
/ # ls /proc/56/fd | wc -l
4
/ # ls /proc/57/fd | wc -l
94
/ # ls /proc/58/fd | wc -l
94
/ # ls /proc/59/fd | wc -l
3
/ # 

```

**Comment by cpuguy83** [comment]
I see what you mean.
Yeah it seems the kernel accounting is per process not per process tree.

This would likely require some new type of cgroup in the kernel to account for these things.
One thing you could do is use the PIDs cgroup to limit the number of processes that can run in a container, and then use the `nofile` ulimit from there.

**Comment by qingwave** [comment]
Thank for your reply
