### ISSUE TITLE
change moby/moby PRs to run with docker graphdriver overlay2

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39561]
Currently using `vfs`, should use `overlay2`. Hopefully brings performance improvements to running the PR checks. Using `overlay2` would be closer to production environment because that is the default graphdriver.

**Comment by andrewhsu** [comment]
I'll test this out on a private jenkins job first before making the change in the Docker-PRs job.

**Comment by cpuguy83** [comment]
If it does cause problems... vfs has some optimizations for filesystems that support reflinking which massively reduces copy time.... specifically this would be xfs and btrfs.. the nodes would just need to provide this as the base filesystem for the docker storage dir (and for the test daemons we spin up).
Of course overlay2 is ideal at the very least to exercise the most used driver more, but just a thought there.

**Comment by andrewhsu** [comment]
Just running the `DockerSwarmSuite` tests I haven't found a significant difference on our jenkins slave nodes `ubuntu-1604-overlay2`:
* `vfs` 31 min 39.057 sec
* `overlay2` 31 min 53.847 sec

I'll run it on the whole suite of `hack/ci/janky` tests to see what the difference could be.

**Comment by cpuguy83** [comment]
I think swarm tests are mostly waiting on consensus rather than container startup.

**Comment by andrewhsu** [comment]
Running all of the `hack/ci/janky` tests, fastest I saw was:
* `vfs` 2 hr 11 min https://jenkins.dockerproject.org/view/Docker/job/Docker-PRs/buildTimeTrend
* `overlay2` 1 hr 52 min https://jenkins.dockerproject.org/job/andrewhsu/job/Docker-PRs/buildTimeTrend

I'll make the change to `overlay2` on the Docker-PRs job https://jenkins.dockerproject.org/view/Docker/job/Docker-PRs/
