### ISSUE TITLE
Windows "integration" tests report incorrect status

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#39576]
Seen on https://github.com/moby/moby/pull/39569#issuecomment-513266467

RS5 _failed_ due to https://github.com/moby/moby/issues/39574, but integration tests are not marked as "failed"

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/3055/console

```
09:13:44 Running C:\gopath\src\github.com\docker\docker\integration\container
09:13:45 INFO: Windows Base image is  microsoft/windowsservercore
09:13:45 INFO: Testing against a local daemon

...

09:13:52 === RUN   TestHealthKillContainer
09:13:59 --- FAIL: TestHealthKillContainer (7.58s)
09:13:59     health_test.go:57: assertion failed: error is not nil: Error response from daemon: Invalid signal: SIGUSR1
...

09:16:21 --- SKIP: TestWaitBlocked (0.00s)
09:16:21     wait_test.go:59: testEnv.DaemonInfo.OSType != "linux"
09:16:21 FAIL
09:16:21 Running C:\gopath\src\github.com\docker\docker\integration\image
```

Then it continues with `test-integration-cli`

```
10:22:01 OK: 524 passed, 548 skipped
10:22:01 PASS
10:22:01 ok  	github.com/docker/docker/integration-cli	3921.066s
10:22:02 INFO: Integration tests ended at 07/19/2019 10:22:02. Duration:01:05:31.5617086
```

**Comment by thaJeztah** [comment]
ping @ddebroy @andrewhsu

**Comment by ddebroy** [comment]
Should we assert on something else at https://github.com/moby/moby/blob/f1b5612f2008827fdcf838abb4539064c682181e/integration/container/health_test.go#L59-L61 ? It's odd that the test continues on and ends without any assertions.

**Comment by ddebroy** [comment]
Ignore the comment above. Re-posted it against the original merged that introduced this test at https://github.com/moby/moby/pull/39454#issuecomment-513288268

**Comment by thaJeztah** [comment]
So the test fails, but CI continues; running the `integration/` tests was added quite recently, perhaps it's not checking the final status of those?

**Comment by thaJeztah** [comment]
Then again; sometimes it does the right thing (and marks CI red), so still curious "how"

**Comment by olljanat** [comment]
I added integration API tests for Win was added on #39240 and it works on way that it checks return code from test.exe
https://github.com/moby/moby/blob/4fa57a8191b1d23c6466725b688519f83c0ac5dd/hack/make.ps1#L354-L356
but probably it actually does return zero if last tests on that test binary is successful?

Maybe adding `-test.failfast` to
https://github.com/moby/moby/blob/aac6e62209b1b7fe22717ca9c4714c8fc74c29e8/hack/ci/windows.ps1#L825 
would help?
