### ISSUE TITLE
Question: Docker daemon crash when freeing invalid pointer

### ISSUE THREAD

**Issue by zoramthanga** [moby/moby#39599]
**Description**

Docker daemon is randomly crashing with the following trace:

SIGABRT: abort
PC=0x7f06e9e94207 m=38
signal arrived during cgo execution

goroutine 1152 [syscall, locked to thread]:
runtime.cgocall(0x14737c0, 0xc421fe3d80, 0x0)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc421fe3d50 sp=0xc421fe3d10
github.com/docker/docker/daemon/logger/journald._Cfunc_free(0x7f043c001880)
        github.com/docker/docker/daemon/logger/journald/_obj/_cgo_gotypes.go:108 +0x41 fp=0xc421fe3d80 sp=0xc421fe3d50
github.com/docker/docker/daemon/logger/journald.(*journald).drainJournal(0xc422028000, 0xc42184c1e0, 0xed4c2a879, 0x0, 0x2458bc0, 0xffffffffffffffff, 0x1, 0x7f04880008c0, 0x7f043c001880, 0x7f043c001880)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/logger/journald/read.go:239 +0x263 fp=0xc421fe3eb0 sp=0xc421fe3d80
github.com/docker/docker/daemon/logger/journald.(*journald).followJournal.func1(0x7f04880008c0, 0x1cf0000019a, 0xc420b580c0, 0xc422028000, 0xc42184c1e0, 0xed4c2a879, 0x0, 0x2458bc0, 0xffffffffffffffff, 0x1)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/logger/journald/read.go:253 +0x11d fp=0xc421fe3f60 sp=0xc421fe3eb0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc421fe3f68 sp=0xc421fe3f60
created by github.com/docker/docker/daemon/logger/journald.(*journald).followJournal
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/logger/journald/read.go:269 +0x158

**Steps to reproduce the issue:**
This is non-deterministic. I don't have a reproducible test case.

**Describe the results you received:**

Docker daemon crashes.

**Describe the results you expected:**

Docker should not crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is happening at random.

**Output of `docker version`:**

```
Docker version 1.13.1-cs9, build 1bc62a2
```

**Output of `docker info`:**

```
Containers: 1462
 Running: 65
 Paused: 0
 Stopped: 1397
Images: 1895
Server Version: 1.13.1-cs9
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 154.8 GB
 Data Space Total: 204 GB
 Data Space Available: 49.22 GB
 Metadata Space Used: 126.2 MB
 Metadata Space Total: 2.143 GB
 Metadata Space Available: 2.017 GB
 Thin Pool Minimum Free Space: 20.4 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 59.81 GiB

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I just wanted to check whether this particular crash might have been fixed by https://github.com/moby/moby/commit/81630df85439adab1836e83a7e645d67b1c0eb83

**Comment by zoramthanga** [comment]
Correction: My Docker version is 1.13.0. It does look like 1.13.1-cs2 and up should have the fix (https://docs.docker.com/v17.09/cs-engine/1.13/release-notes/#cs-engine-1131-cs2-23-feb-2017). Can you please confirm if this is the case?

**Comment by cpuguy83** [comment]
cs-engine is a pay-for-support version of the engine provided by Docker. It is not maintained here.

Based on the release notes it would seem the issue was fixed in that build.
