### ISSUE TITLE
docker\docker\contrib\selinux LICENSE file

### ISSUE THREAD

**Issue by Pixcell** [moby/moby#39593]
**Description**

Hi,

I am installing the golang docker/client as a dependency.
The docker client is licensed as Apache-2.0 (vendor/github.com/docker/docker/LICENSE) but when I inspect the files included in my vendors directory, GPL licenses are presents in 3 directories :

vendor\github.com\docker\docker\contrib\selinux
vendor\github.com\docker\docker\contrib\selinux-fedora-24
vendor\github.com\docker\docker\contrib\selinux-oraclelinux-7

Each of those directory only contains one file: LICENSE.
No code alongside it.

I can't use any GPL license code in my current project. I was wondering why an Apache-2.0 licensed project as docker/client would include GPL License files.

**Steps to reproduce the issue:**
1. install github.com/docker/docker version 1.13.1 using go-dep
2. inspect the folder mentioned aboved

**Describe the results you received:**
GPL licenses found

**Describe the results you expected:**
No GPL licenses

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

N/A

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
These files are no longer in the master branch; the 1.13 tag is very old and should not be used

**Comment by Pixcell** [comment]
Thanks, I'll update my constraint in the toml file.
Would you be kind enough to let me know what version is the actual latest ?

**Comment by thaJeztah** [comment]
This repo doesn't do ragged releases, but if you want to align to the latest docker release, you can vendor from the https://github.com/docker/engine repository (19.03.0 is the latest release)

**Comment by Pixcell** [comment]
This does not work, I have opened an issue with go/dep https://github.com/golang/dep/issues/2193 regarding the version issue.

However, importing from docker/engine does not work either at compilation time because "github.com/docker/engine/api/types" expects an import from "github.com/docker/docker/api/types"

And using "github.com/docker/docker" leads to this compilation error: https://github.com/moby/moby/issues/28269

Removing the vendor folder, then leads a long list of unresolved imports:

```
../../docker/docker/errdefs/http_helpers.go:7:2: cannot find package "github.com/containerd/containerd/errdefs" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/containerd/containerd/errdefs (from $GOROOT)
        /Users/pixcell/go/src/github.com/containerd/containerd/errdefs (from $GOPATH)
../../docker/docker/api/types/container/host_config.go:10:2: cannot find package "github.com/docker/go-units" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/docker/go-units (from $GOROOT)
        /Users/pixcell/go/src/github.com/docker/go-units (from $GOPATH)
../../docker/docker/api/types/swarm/runtime/plugin.pb.go:16:8: cannot find package "github.com/gogo/protobuf/proto" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/gogo/protobuf/proto (from $GOROOT)
        /Users/pixcell/go/src/github.com/gogo/protobuf/proto (from $GOPATH)
../../docker/docker/api/types/registry/registry.go:7:2: cannot find package "github.com/opencontainers/image-spec/specs-go/v1" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/opencontainers/image-spec/specs-go/v1 (from $GOROOT)
        /Users/pixcell/go/src/github.com/opencontainers/image-spec/specs-go/v1 (from $GOPATH)
../../docker/docker/errdefs/http_helpers.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/github.com/sirupsen/logrus (from $GOROOT)
        /Users/pixcell/go/src/github.com/sirupsen/logrus (from $GOPATH)
../../docker/docker/errdefs/http_helpers.go:10:2: cannot find package "google.golang.org/grpc/codes" in any of:
        /usr/local/Cellar/go/1.12.7/libexec/src/google.golang.org/grpc/codes (from $GOROOT)
```

Solving those import by using `go get` on each of them will not solve my issue of using a fixed version of this client (since go get doesn't let me specify a specific version)


I also tried to update my dep constraint to the latest tag of moby/moby: 
```
[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.03.2-ce"
```

17.03.2-ce compiled, but still have the GPL licensed files.

**Comment by thaJeztah** [comment]
Yes, you need to import it as `github.com/docker/docker`, but fetch the code from `github.com/docker/engine`, e.g. similar to https://github.com/docker/compose-on-kubernetes/commit/3f1fc892da2be0a7cc837cfa54c33d44fa5b4d2c#diff-836546cc53507f6b2d581088903b1785

**Comment by Pixcell** [comment]
@thaJeztah Great thanks ! It worked like a charm.

For anyone else bumping into this issue, the proper Gopkg.toml syntax is:

```

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/docker/engine"
  version = "XXX (release from docker/engine repo)"

```
