### ISSUE TITLE
Question: Re-building Docker from moby and installation on another machine

### ISSUE THREAD

**Issue by niketagrawal** [moby/moby#39596]
In order to run a customized docker on my system, I first added my code changes to moby/moby repository and tested it using the moby development container procedure. I’d now like to build an entire docker package from this which I can install as a fully fledged working docker on another setup similar to just as I would install docker-ce usually. The 'contributing' section only explains the procedure for contributing code to moby/moby repository on github but in my case I'd like to build my own version of docker based on the custom changes I've added in the files under moby/moby. Is there a dedicated procedure or any related references that captures the steps required to accomplish this? I suppose it is not the same as building docker from source because the starting repository in that case is docker-ce and not moby/moby.

**Comment by AkihiroSuda** [comment]
You want to create RPM/DPKG packages?
You can use docker-ce-packaging scripts: https://github.com/docker/docker-ce-packaging

Also see https://src.fedoraproject.org/rpms/moby-engine/tree/master

**Comment by niketagrawal** [comment]
Unfortunately, I'm not familiar with the whole packaging concept yet. From what I've read so far, there seems another approach where in order to have this modified docker installed and running on a new machine, one can just replace the docker binaries on the new machine with newly created ones. So, the only downside here is that the new machine must already have docker installed. 
I prepared the new binaries after modifying the code in moby/moby using "make build" and "make binary" commands on my own PC which has docker installed. To, begin with I can replace the binaries in /usr/bin/docker in my PC with the new binary in order to run and experiment with the new docker. Which binaries are to be replaced exactly is where I'm stuck on at the moment.

**Comment by AkihiroSuda** [comment]
`make install`

**Comment by niketagrawal** [comment]
As mentioned in the moby development container procedure, `make install` copies the binary to the moby dev container's /usr/local/bin/ directory. However, since in my case I am trying to overwrite the docker binaries of my PC, I need to copy the binary to /usr/bin/docker so that it replaces the original one, Please correct me if I'm wrong.

**Comment by AkihiroSuda** [comment]
`DOCKER_MAKE_INSTALL_PREFIX=/usr/bin make install` (see `hack/make/install-binary`) if you want to overwrite /usr/bin binaries, but first you might need to remove preinstalled RPM/DEB to avoid breaking apt/dnf

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
