### ISSUE TITLE
Question: Removal of incompletely built docker binaries

### ISSUE THREAD

**Issue by niketagrawal** [moby/moby#39598]
After adding my changes to the clone of moby/moby repository, I issued the `make binary` command to build the binaries but to insufficient space in the disk, the command could not complete at the last moment of its execution. I notice that this incomplete run has consumed a coupe of gigabytes of disk space. Is there a way to track down and delete the files/directories which were generated in this process to restore disk space?
After this failed run I notice that there are no images created under `docker images`. This is unlike the case of previous successful runs where I could delete the large sized docker images which were created as part of the binary building process.

**Comment by thaJeztah** [comment]
You can use `make clean` to remove the volume used for the Go cache, and removing the `bundles` directory should remove all the build-artefacts.

From your description, I guess space is taken by either untagged versions of the build-container/image, or the build-cache. You can remove those using `docker system prune` (or `docker image prune` and `docker builder prune`)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue for housekeeping, but feel free to continue the conversation 👍
