### ISSUE TITLE
Upgrade to 19.03 from 18 results in libnetwork-setkey hitting UNIX_PATH_MAX limit

### ISSUE THREAD

**Issue by Rid** [moby/moby#39608]
**Description**
I just upgraded our test system from 18.09.3 to 19.03.0 and none of our daemons are working. I've traced the issue to the following commit:

https://github.com/moby/moby/pull/37850

We're hosting multiple daemons on a single host so the path length is slightly longer resulting in the following error due to hitting the UNIX_PATH_MAX limit (108 ours is 115):

failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /cylostore/sdj/9598/var/run/docker/libnetwork/b2757cb82eadaaea94aab22529663e38c3bf799369f5b578fe8a5bb4bcefe0f0.sock: bind: invalid argument

I understand that this is a configuration issue and we'll probably need to shorten our exec-root, however I think it's important for people to understand this limitation, as there's not much wiggle room.

**Steps to reproduce the issue:**
1. Start a daemon with an exec-root > 27 chars

**Describe the results you received:**
failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /cylostore/sdj/9598/var/run/docker/libnetwork/b2757cb82eadaaea94aab22529663e38c3bf799369f5b578fe8a5bb4bcefe0f0.sock: bind: invalid argument

**Describe the results you expected:**
Docker to start normally

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        aeac949
 Built:             Wed Jul 17 18:15:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       aeac949
  Built:            Wed Jul 17 18:13:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 19.03.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 5.0.3-050003-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 125.7GiB
 Name: m390.ata.ams-1.nl.cylo.io
 ID: QE2H:72ZE:6R52:Z7NT:ACKR:NCVE:TLUZ:R6CE:XLIY:QU6V:MB5M:4F6Y
 Docker Root Dir: /var/lib/docker/100000.100000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thaJeztah** [comment]
ping @akihirosuda

**Comment by AkihiroSuda** [comment]
Can we shorten the libnetwork hash length?

**Comment by cpuguy83** [comment]
Seems like we should be able to do at least the short id.

**Comment by mike2307** [comment]
Is there any workaround for that issue?

I'm having troubles with the rootless docker because of that. My UID is 10 digits, which causes the following:

`failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /run/user/1310810133/docker/libnetwork/0d6406c534bb514611f2f9affa7f10c7c5500bb98b3189c8527e92a6446b73e1.sock: bind: invalid argument`

**Comment by AkihiroSuda** [comment]
@mike2307 
A workaround is to set `$XDG_RUNTIME_DIR` (or `exec-root` in `~/.config/docker/daemon.json`) to a short path.

```
mkdir /tmp/s
chmod 700 /tmp/s
XDG_RUNTIME_DIR=/tmp/s
```

**Comment by mike2307** [comment]
> @mike2307
> A workaround is to set `$XDG_RUNTIME_DIR` (or `exec-root` in `~/.config/docker/daemon.json`) to a short path.
> 
> ```
> mkdir /tmp/s
> chmod 700 /tmp/s
> XDG_RUNTIME_DIR=/tmp/s
> ```

Thanks a lot. That worked brilliantly. I've chosen the json way. Seems like the directory is automatically created...

```
$ cat ~/.config/docker/daemon.json 
{
  "exec-root": "/tmp/rldocker/"
}
```
