### ISSUE TITLE
OOMKilled flag never set on Windows.

### ISSUE THREAD

**Issue by ecstatic-morse** [moby/moby#39611]
`State.OOMKilled` is never set when running `docker inspect` on a container on Windows, even if that container exceeded its memory limit. This is a known shortcoming; the test is [explicitly skipped on Windows](https://github.com/moby/moby/blob/b10cd5c0e6f479f131e33cf323b89212587fa38e/integration/container/kill_test.go). I'm aware that the "OOM killer" is Linux specific, but perhaps there's a way to communicate that a container exceeded its memory limit on Windows as well.

**Comment by thaJeztah** [comment]
not sure if this is possible; I recall discussing this at some point with @johnstep, and don't think it is

/cc @jhowardmsft

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
