### ISSUE TITLE
enable windows PR checks in Jenkinsfile

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39691]
Currently, the `Jenkinsfile` has windows tests disabled by default so the new https://ci.docker.com/public/job/moby/ jenkins rig does not run the tests by default.

https://github.com/moby/moby/blob/3a4b51ebb8b6559ce4c8f126a7533066369c6182/Jenkinsfile#L16-L17

Need to migrate what's needed from the legacy PR checks (which are still active) from https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/ to the `Jenkinsfile` so we can turn them on by default.

Having the configuration for running the PR checks in the moby repo instead of the legacy jenkins configuration page will also help developers to reproduce PR test failures.

This is a requirement before we can turn off the legacy jenkins PR check jobs.

cc @ddebroy @StefanScherer

**Comment by StefanScherer** [comment]
@ddebroy @andrewhsu I've updated #39747 to run the first tests on the new Windows nodes.

**Comment by andrewhsu** [comment]
This is done now that #39747 is merged.
