### ISSUE TITLE
fail to getdents in 32bit appliaction running in 64bit host

### ISSUE THREAD

**Issue by RogerYaozhenyu** [moby/moby#39732]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
getdents could work well.
### Actual behavior
return fail.
### Information

  - Windows Version: Win10 专业版 64bit （10.0 ，版本：17763）
  - Docker Desktop Version:
docker for win version:
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. ...
 my host os is win10 64bit.
run my continer.  docker run -it --rm -v /d:/home/d  -p 3333:3333 -p 6000:6000 -p 22:22 -p 830:830  --privileged=true
 uname -a
Linux 2f301d55e83f 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 ls ./ramdisk/
config.db  libpcre.so  metadata.so  nacm.so  yang
root@2f301d55e83f:/home/d/clearcase/spn/HZ05918_view_spn/OnsPlatform/dbuild/linux_x86_simu_opxx# 

``
#include <stdlib.h>
#include <dirent.h>
below is my code.
int main()
{
    const char * testdir="./ramdisk";
    DIR * dir = opendir(testdir);
    struct dirent *file;
    while(file=readdir(dir))
    {
        if(strlen(file->d_name)>0)
            printf("%s\n",file->d_name);
    }
}

  2. ...build it using gcc -m32 -o test test.c
3. run it  strace ./test

4. 
getdents(3, 0xc34145c, 32768)           = -1 EOVERFLOW (Value too large for defined data type)

**Comment by justincormack** [comment]
You may need to compile with `-D_FILE_OFFSET_BITS=64`. This is not a Docker issue specifically, it is just issues with 32 bit code on Linux.

**Comment by RogerYaozhenyu** [comment]
it seems compile with -D_FILE_OFFSET_BITS=64 not work .  the same  code and the same compile flags.
/var/run/spn is linux directory .   in this directory , it could display all files.
/home/d/ut/test  is a win10 directory  

root@2f301d55e83f:/var/run/spn# ./test_dir
yang
nacm.so
libpcre.so
.
config.db
..
metadata.so
root@2f301d55e83f:/var/run/spn# cd $OLDPWD
root@2f301d55e83f:/home/d/ut/test# ./test_dir
.
root@2f301d55e83f:/home/d/ut/test# ls ramdisk/
config.db  libpcre.so  metadata.so  nacm.so  yang
root@2f301d55e83f:/home/d/ut/test#

**Comment by Ecordonnier** [comment]
It is a glibc 2.28 bug: https://sourceware.org/bugzilla/show_bug.cgi?id=23960
