### ISSUE TITLE
"docker rmi -f" is stuck

### ISSUE THREAD

**Issue by yanghaichao12** [moby/moby#39739]
**What happened:**
 my execution “docker rmi -f imageXXX” is stuck when some other container in the same host has connected to an abnormal nfs server, and i'm very sure there's no any container using this imageXXX at time.

i notice:
https://github.com/moby/moby/blob/fade624f1696a46071b812606f4ddb0c6d2e4d16/daemon/images/image_delete.go#L369-L382

here, all containers will be checked  if running and then if the containter being checked has the identical imageid to the deleting imgid .
https://github.com/moby/moby/blob/fade624f1696a46071b812606f4ddb0c6d2e4d16/container/state.go#L239-L244
and there is global lock.  That's the reason. i think maybe adjusting the statement like that  will be better:
```go
return  c.ImageID == imgID && c.IsRunning()
```

**What you expected to happen:**
no stuck when running docker rmi .
**How to reproduce it (as minimally and precisely as possible):**
1.mount some containers to nfs server.
2.make nfs server unaccessible.
3.docker rmi any container.
Environment:

version:
any version
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release): Ubuntu 16.04 LTS 
Kernel (e.g. uname -a):4.4.0-21-generic #37-Ubuntu 
Install tools:
Network plugin and version (if this is a network-related bug):
Others:

**Comment by thaJeztah** [comment]
Thanks for reporting; don't know if it will resolve all of those issues, but swapping those as you suggested seems ok to me.

Are you interested in contributing, and opening a pull request to make that change? Or do you want me to take care of that?

**Comment by yanghaichao12** [comment]
that sounds good, i'm going to learn how to contribute and open a pr. thank for your replay
