### ISSUE TITLE
docker manifest push fails with error mounting

### ISSUE THREAD

**Issue by clauderobi** [moby/moby#39766]
----
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

I am getting an error when trying to push a multi-arch manifest list using docker manifest push. Others operations with the registry (local) are Ok.

**Steps to reproduce the issue:**
1.Create 2 single architecture images
2.Create a local manifest list, using docker manifest create
3. Try to push using dokcer manifest push

Most of the time, using -D I see that the tool performs each step needed to mount the other architecture image's blobs but eventually failed on a given blob (already the same if I repeat the command).

I am example of the error I am getting is:

error mounting dav-x86_64@sha256:.... to gitmaster.cbcr.me/dav:latest

**Describe the results you expected:**
A successful push to the registry

**Additional information you deem important (e.g. issue happens only occasionally):**

I did see cases where it worked as expected. Even repeatedly. However, the same manifest list create on the "other" architecture failed.

**Output of `docker version`:**

Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:33:17 2019
 OS/Arch:           linux/arm
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:27:09 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc7+dev
  GitCommit:        029124da7af7360afa781a0234d1b083550f797c
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Output of `docker info`:**

Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 75
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: mfyd6je7xks6pi51rz0oamcbk
  Is Manager: false
  Node Address: 192.168.31.31
  Manager Addresses:
   192.168.31.20:2377
   192.168.31.8:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 029124da7af7360afa781a0234d1b083550f797c
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.58+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv6l
 CPUs: 1
 Total Memory: 432.7MiB
 Name: raspberrypi
 ID: 4LJG:SJWE:7RKA:GWJV:4N32:FUDU:TW4P:CEJY:ZRTL:5VPI:TUWS:YAYU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  gitmaster.cbcr.me:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The local registry is TLS protected using a self signed certificate. Its image is registr:2, f32a97de94e1

**Comment by clauderobi** [comment]
Fix the issue. This was due to stall data in the local manifest file. The only work around was to manually delete the manifest directory (using rm -r ~/.docker/manifest).

**Comment by thaJeztah** [comment]
Thanks for the update: let me close this one

**Comment by Maleware** [comment]
Hey guys, the error seems still to persist on macOS with M1. Do you have a good solution to this?

**Comment by virajkanwade** [comment]
Ran into this on Mac M2

**Comment by noureddine-ennacir** [comment]
What is the solution for this?

I can't push the multi arch image to my ECR due to this error
error mounting amd64/broker@sha256: to myawsaccountid.dkr.ecr.us-west-2.amazonaws.com/multi-arch/broker:2.4

I tried from my local M1 and x86 T3.medium instance in AWS. Nothing works so not sure if I am doing something wrong.
