### ISSUE TITLE
docker manifest create - Add the ability to start from fresh (or new), ie discard the current local manifest list file

### ISSUE THREAD

**Issue by clauderobi** [moby/moby#39767]
I had a situation where the local manifest file had stall data. --amend did NOT updated the manifest to the point where the stall data was replace. Using versioning is certainly a solution to this, but during development it is sometime easier to not use (yet) versioning. So, I suggest to add a --new option to docker manifest create in order to ignore an existing manifest file and start anew.

**Comment by thaJeztah** [comment]
The `docker manifest` subcommand is a client side feature; could you reopen this in the https://github.com/docker/cli issue tracker (as that's where the code lives for that feature)?

I'll close the issue here; thanks!

**Comment by clauderobi** [comment]
For reference, an issue in docker/cli already existed... here it is: https://github.com/docker/cli/issues/954#issue-307063269
