### ISSUE TITLE
Typo in TestBuildMulitStageResetScratch testcase name

### ISSUE THREAD

**Issue by tmp6154** [moby/moby#39772]
https://github.com/moby/moby/blob/48ea015b57193bc051b7b05df5753760c3c3f0f1/integration-cli/docker_cli_build_test.go#L5955

```func (s *DockerSuite) TestBuildMulitStageResetScratch(c *check.C) {```

Obviously, "TestBuildMultiStageResetScratch" was meant here.

**Comment by yongtang** [comment]
@tmp6154 Are you willing to create a PR?

**Comment by tmp6154** [comment]
Yes, no problem.
