### ISSUE TITLE
Remove old PR checks that have migrated to the Jenkinsfile

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39773]
The moby PR checks are currently migrating from an old way of running Jenkins jobs with manual configuration on the Jenkins master to a `Jenkinsfile`-driven way that was added with PR #38565. Docker will still provide the compute resources and administration of the Jenkins infrastructure, but having the `Jenkinsfile` define the PR checks will allow the moby maintainers more control over optimizing the build jobs (#39651) and keeping code changes that affect build process in the same PR.

This also brings a migration from an old Jenkins master https://jenkins.dockerproject.org to the new Jenkins master https://ci.docker.com/public/job/moby/. The new Jenkins master is configured with a UI to help visualize the PR check steps:

![Screen Shot 2019-08-19 at 3 34 57 PM](https://user-images.githubusercontent.com/57640/63304208-1c2be600-c297-11e9-82c6-f83063397183.png)

And reporting of test results (#39675):
![Screen Shot 2019-08-19 at 3 37 38 PM](https://user-images.githubusercontent.com/57640/63304300-5bf2cd80-c297-11e9-9e05-42bf2dbb1af3.png)

As the new PR checks come online, driven by the new `Jenkinsfile`, the old PR checks will be removed:
 - [x] dco-signed
   - [x] enable alternative DCO bot: https://github.com/moby/moby/issues/39538
 - [x] experimental
 - [x] janky
 - [x] powerpc
 - [x] vendor
 - [x] windowsRS1
 - [x] windowsRS5-process
 - [x] z

![Screen Shot 2019-08-19 at 3 26 54 PM](https://user-images.githubusercontent.com/57640/63304063-96a83600-c296-11e9-9d3c-6b2d57390ba2.png)

**Comment by thaJeztah** [comment]
can we keep the dco-signed for now? it also adds a label and a comment to help contributors

**Comment by thaJeztah** [comment]
we could replace it with something else though

**Comment by thaJeztah** [comment]
Existing tracking issue for the DCO bot; https://github.com/moby/moby/issues/39538

**Comment by andrewhsu** [comment]
PR #39747 will bring the windows PR checks onto the new Jenkins.

**Comment by andrewhsu** [comment]
I see 3 DCO checks:
1. `dco-signed` - triggered by a private [poule operation](https://github.com/icecrime/poule/blob/master/src/poule/operations/catalog/README.md#poule-operations)
1. `DCO-check` - triggered by `Jenkinsfile` https://github.com/moby/moby/blob/339dd0a2e528938961a7882dc834db18d18f8755/Jenkinsfile#L38
1. `DCO` - https://probot.github.io/apps/dco/

@thaJeztah curious to know which one we should use?

**Comment by thaJeztah** [comment]
I think we can get rid of the one triggered by poule. There might also be one triggered by leeroy (I noticed we had two being triggered at some point recently)

Be sure to check though if other repositories are not using the same one


wrt the remaining ones;

- probot is useful because it's more visible and provides some instructions for the contributor
- the DCO check in the Jenkinsfile makes sure we don't run the whole test suite if the DCO check is failing (it's also useful because some other downstream repositories don't have the probot enabled)

**Comment by andrewhsu** [comment]
The `dco-signed` check has now been removed from poule and from branch protection https://github.com/moby/moby/settings/branches

**Comment by andrewhsu** [comment]
This is now done.
