### ISSUE TITLE
Cannot build from local image with buildctl

### ISSUE THREAD

**Issue by virgile-hogman** [moby/moby#39770]
**Description**

Cannot build from a local image with `buildctl` which always tries to resolve to `docker.io`. This applies to a multi-stage setup or simply from a local image in a CI setup. The base image should not be expected to be pushed to any repository (either `docker.io` or even private). It is only available locally (`docker images`).

This works with `docker build` and even `DOCKER_BUILDKIT=1` using image names (but not SHA ID in the last case). See also #39769. 

This looks similar to the problems with local cache described here: #39003.

**Steps to reproduce the issue:**
1. Demo project available here: https://github.com/virgile-hogman/docker-buildkit
2. Run `./buildctl-build.sh` from bash
3. See logs, fails to resolve `FROM docker.io/library/bk1:latest`

**Describe the results you received:**

```
+ buildctl build --frontend dockerfile.v0 --progress=plain --local context=src2 --local dockerfile=src2 --output type=docker,name=bk2
+ docker load
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 66B done
#2 DONE 0.1s

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s

#3 [internal] load metadata for docker.io/library/bk1:latest
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#4 [1/2] FROM docker.io/library/bk1:latest
#4 resolve docker.io/library/bk1:latest
#4 resolve docker.io/library/bk1:latest 0.4s done
#4 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/library/bk1:latest:
------
------
 > [1/2] FROM docker.io/library/bk1:latest:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
open /var/lib/docker/tmp/docker-import-259291410/repositories: no such file or directory
```

**Describe the results you expected:**

This should work as for `docker build` when using image names (with or without `DOCKER_BUILDKIT=1`. Note with SHA-ID it does not work either in the last case as described in #39769).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Output of `docker info`:**

```
Native install with Ubuntu 18.04. More info does not seem relevant for now, can provide if really needed.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Connected to a private repository on a different host but this should not have effect here since it works with standard `docker build`.

**Comment by thaJeztah** [comment]
Given that this looks to be related to `buildctl`, which is part of buildkit (standalone); could you re-open this in the buildkit issue tracker? (https://github.com/moby/buildkit/issues)

**Comment by virgile-hogman** [comment]
@thaJeztah thanks for fast reply. Here it is: https://github.com/moby/buildkit/issues/1142.

It was not clear where i should sent the issues. It is so confusing to understand where to go between these "false-twins" environments `DOCKER_BUILDKIT=1` vs `buildctl`, not only for github but also the reference documentation. In general do you mean all about the first case is here moby/moby whereas the rest is for moby/buildkit?

Also it's quite hard to understand how the standard docker build is going to evolve with respect to these two setups. The logic would be that the features in `DOCKER_BUILDKIT=1` becomes standard in the main docker distribution but you surely knows more about this.

**Comment by virgile-hogman** [comment]
Feel free to close this ticket if it's not relevant here.
