### ISSUE TITLE
how to load bridge module ( br_netfilter ) in container

### ISSUE THREAD

**Issue by zhujintao** [moby/moby#39803]
step 1
[root@1de8306e8c23 /]# lsmod | grep br
br_netfilter           22256  0 
bridge                151336  1 br_netfilter
stp                    12976  1 bridge
llc                    14552  2 stp,bridge

step 2
[root@1de8306e8c23 /]# modprobe bridge br_netfilter

step 3
[root@1de8306e8c23 /]# ls /proc/sys/net/
core  ipv4  ipv6  netfilter  unix

**Comment by cpuguy83** [comment]
Same way as on the host, but you need the modules in the container (e.g. mount the module dir). You must also use `--privileged`.
