### ISSUE TITLE
`ERROR exporting to image` with DOCKER_BUILDKIT=1 (experimental)

### ISSUE THREAD

**Issue by GuillaumeRochat** [moby/moby#39813]
**Description**
We use the experimental flag for the secret mount feature to build our containers. Whenever I build an image on my laptop, the step `exporting to image` fails and the step `exporting layers` keeps going on. 

The `/etc/docker/daemon.json` file has the `experimental` option set to true, the Dockerfile has the `# syntax = docker/dockerfile:1.0-exprimental` header at the top, yet it fails just as if the `experimental` option wasn't enabled.

Both the client and service have been set in experimental as it can be seen in the `docker info` and `docker version` results.

**Steps to reproduce the issue:**
1. Build an image with DOCKER_BUILDKIT=1
2. Wait for the step `exporting to image` to complete.

**Describe the results you received:**
The step errors out and the `exporting layers` keeps going on indefinitely.

**Describe the results you expected:**
The `exporting to image` step works correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue happens almost all the time. I try to reboot the docker.service and docker.socket, edit the `/etc/docker/daemon.json` config to see if something will reload. Eventually it works, but I haven't been able to point to a specific scenario to guarantee that it will work.

It also never worked on the first try. It always failed the first time I try to build something. The issue happens in all our projects using the experimental feature.

**Output of `docker version`:**

```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        74b1e89e8a
 Built:             Fri Aug 16 14:00:42 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       74b1e89e8a
  Built:            Fri Aug 16 13:58:02 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.8.m
  GitCommit:        a4bc1d432a2c33aa2eed37f338dceabb93641310.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 116
 Server Version: 19.03.1-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a4bc1d432a2c33aa2eed37f338dceabb93641310.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.2.9-arch1-1-ARCH
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.54GiB
 Name: grochat
 ID: JG3B:ZSVQ:BUVN:BUSN:Q4Y7:MABK:WYXA:SQLK:HZ4Y:NPZ5:ZM6H:ZYFI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The hardware on which it's being build is a Galago Pro, with an Intel i5-8250U CPU.

**Comment by GuillaumeRochat** [comment]
The behavior changed with version 19.03.2-ce. Now It fails at the same step but stop the processing and displays this error message :
```
 => ERROR exporting to image                                                                                                                                                                                   1.1s
 => => exporting layers                                                                                                                                                                                        1.1s
------
 > exporting to image:
------
error creating overlay mount to /var/lib/docker/overlay2/{somehash}/merged: device or resource busy
```

By repeatedly trying, it eventually works. There are no docker container running when that happens, nor are there any other container being built.

**Comment by lgaticaq** [comment]
I fix this error removing all unused containers and image

**Comment by patata3000** [comment]
same here

**Comment by GuillaumeRochat** [comment]
I wiped all images, volumes, networks and containers and it hasn't failed since. Thanks!

**Comment by burtsevyg** [comment]
It does not help for me. Docker down after "exporting to imageexporting layers"
