### ISSUE TITLE
devicemapper: GetTable() and GetStatus return only first line of the DM table

### ISSUE THREAD

**Issue by trgill** [moby/moby#39833]
**Description**

Device mapper target tables may have multiple lines. GetTable() and GetStatus should return the full results, they return only the first line.

The problem doesn't have any impact because only single line tables are created - but it is a bug in the DM API binding.

**Steps to reproduce the issue:**

1. Create a multi-line target with the following script:

```
#!/bin/bash
set -x
DATA_DEV=/dev/XXX # replace with scratch block device

dmsetup remove linear-dev

echo -e "0 1 error\n\n1 1 linear ${DATA_DEV} 1\\n2 7 error\\n9 1 linear ${DATA_DEV} 9\\n10 6 error" | dmsetup create linear-dev

```
2. Call GetTable() or GetStatus() functions

**Describe the results you received:**

Only the first line of the DM table is returned

**Describe the results you expected:**

The complete DM table is returned

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Sample output of dmsetup with a multi-line target:

```
# dmsetup status linear-dev
0 1 error
1 1 linear
2 7 error
9 1 linear
10 6 error

# dmsetup status -v linear-dev
Name:              linear-dev
State:             ACTIVE
Read Ahead:        256
Tables present:    LIVE
Open count:        0
Event number:      0
Major, minor:      253, 5
Number of targets: 5

0 1 error
1 1 linear
2 7 error
9 1 linear
10 6 error

# dmsetup table linear-dev
0 1 error
1 1 linear 8:32 1
2 7 error
9 1 linear 8:32 9
10 6 error
```

I'll open a PR with a proposed fix.

**Comment by thaJeztah** [comment]
The devicemapper storage-driver was deprecated, and has been removed, so closing issues related to this storage-driver. See;

- https://github.com/moby/moby/pull/38017
- https://github.com/moby/moby/pull/43637
