### ISSUE TITLE
Docker command fail on SSH context

### ISSUE THREAD

**Issue by RemiBou** [moby/moby#39841]
**Description**
I can't issue command against my host when using a context created via ssh

**Steps to reproduce the issue:**
1.  I created a context
`docker context create --docker "host=ssh://user@host" context-name`
2. Every command fails
`docker --context=dev-manager1 ps`

> Cannot connect to the Docker daemon at http://docker. Is the docker daemon running?

**Describe the results you expected:**

I expected my command to return the result without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

- I need to run my docker command as "sudo" on the server
- it works well with docker-machine

**Output of `docker version`:**

It odd because docker version seems to return the good server informations.

Docker version client side

> 
> Client: Docker Engine - Community
>  Version:           19.03.1
>  API version:       1.40
>  Go version:        go1.12.5
>  Git commit:        74b1e89
>  Built:             Thu Jul 25 21:18:17 2019
>  OS/Arch:           darwin/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.1
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.5
>   Git commit:       74b1e89
>   Built:            Thu Jul 25 21:17:52 2019
>   OS/Arch:          linux/amd64
>   Experimental:     true
>  containerd:
>   Version:          v1.2.6
>   GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc:
>   Version:          1.0.0-rc8
>   GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

Server side 👍 
 
> Client: Docker Engine - Community
>  Version:           19.03.1
>  API version:       1.40
>  Go version:        go1.12.5
>  Git commit:        74b1e89
>  Built:             Thu Jul 25 21:21:24 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.1
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.5
>   Git commit:       74b1e89
>   Built:            Thu Jul 25 21:19:56 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.6
>   GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc:
>   Version:          1.0.0-rc8
>   GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

**Output of `docker info`:**

Client side 

> 
> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 48
>   Running: 5
>   Paused: 0
>   Stopped: 43
>  Images: 292
>  Server Version: 19.03.1
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
>  init version: fec3683
>  Security Options:
>   seccomp
>    Profile: default
>  Kernel Version: 4.9.184-linuxkit
>  Operating System: Docker Desktop
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 4
>  Total Memory: 1.952GiB
>  Name: docker-desktop
>  ID: OOG7:2GXT:MHQT:KA2H:J2GO:U3YU:XHKD:HKIK:OJH4:DY4L:ZMPL:CDM5
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: true
>   File Descriptors: 63
>   Goroutines: 74
>   System Time: 2019-09-02T07:51:17.042202Z
>   EventsListeners: 2
>  HTTP Proxy: gateway.docker.internal:3128
>  HTTPS Proxy: gateway.docker.internal:3129
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: true
>  Insecure Registries:
>   192.168.99.102:5000
>   127.0.0.0/8
>  Live Restore Enabled: false
>  Product License: Community Engine

Server side

> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 12
>   Running: 12
>   Paused: 0
>   Stopped: 0
>  Images: 15
>  Server Version: 19.03.1
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: active
>   NodeID: r2ubspolakeyo6pdc3fap11i1
>   Is Manager: true
>   ClusterID: svegtmhs5ncwr6eqgjzlm26za
>   Managers: 2
>   Nodes: 2
>   Default Address Pool: 10.0.0.0/8
>   SubnetSize: 24
>   Data Path Port: 4789
>   Orchestration:
>    Task History Retention Limit: 5
>   Raft:
>    Snapshot Interval: 10000
>    Number of Old Snapshots to Retain: 0
>    Heartbeat Tick: 1
>    Election Tick: 10
>   Dispatcher:
>    Heartbeat Period: 5 seconds
>   CA Configuration:
>    Expiry Duration: 3 months
>    Force Rotate: 0
>   Autolock Managers: false
>   Root Rotation In Progress: false
>   Node Address: 51.68.41.183
>   Manager Addresses:
>    51.68.41.183:2377
>    51.68.43.4:2377
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
>  runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.19.0-5-amd64
>  Operating System: Debian GNU/Linux 10 (buster)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 2
>  Total Memory: 6.645GiB
>  Name: mypangee-dev-manager1
>  ID: FC6K:WI5T:BYLE:7NUJ:K5U3:WVKR:VTYL:QK4D:M7P3:VHER:CWLV:A3FE
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>   provider=openstack
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No swap limit support
> WARNING: Running Swarm in a two-manager configuration. This configuration provides
>          no fault tolerance, and poses a high risk to lose control over the cluster.
>          Refer to https://docs.docker.com/engine/swarm/admin_guide/ to configure the
>          Swarm for fault-tolerance.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenStack OVH VM

**Comment by AkihiroSuda** [comment]
`DOCKER_HOST=ssh://user@host docker --debug info` works? If not please try `echo "GET /dummy-bad-request" | ssh -l user host -- docker system dial-stdio`

**Comment by RemiBou** [comment]
Here is the output from first command

> DEBU[0000] commandconn: starting ssh with [-l user host -- docker system dial-stdio]
> DEBU[0003] commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied
> DEBU[0003] commandconn: starting ssh with [-l user host -- docker system dial-stdio]
> DEBU[0003] commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied
> DEBU[0003] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
> Client:
>  Debug Mode: true
> 
> Server:
> ERROR: Cannot connect to the Docker daemon at http://docker. Is the docker daemon running?
> errors pretty printing info

here the output from the second

> failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied

I fixed this by adding user to the docker group. Maybe the error message could be more explicit. Thanks for the help.
