### ISSUE TITLE
docker-ce fatal error: concurrent map writes

### ISSUE THREAD

**Issue by 493613735** [moby/moby#39843]
Description
Deployed k8s node, operating system centos, kernel version 4.19, docker version 18.09.8
Docker daemon (worker node of kubernetes) died with "fatal error: concurrent map writes" msg in log.

Steps to reproduce the issue:
1.Form k8s cluster of few 18.09.8 docker nodes.
2.Deploy some services (>50)
3.One docker worker died with "fatal error: concurrent map writes" msg.

Don't know if it is reproducable.

Describe the results you received:
Dead docker.

Describe the results you expected:
Alive docker.

K8s nodes deployed in batches, basic component information: 
docker: 18.09.8
k8s: 1.10
Os:centos7.4
Kernel: 4.19

Will add info if it will happen again.

After running for a while, the instances on the individual k8s nodes have been restarted in batches. The login node looks at the docker log and found that fatal error: concurrent map writes

Output of docker version:
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:40:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:10:42 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Output of docker info:

Containers: 168
 Running: 92
 Paused: 0
 Stopped: 76
Images: 8
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.12-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.9GiB
Name: 
ID: TYZE:M6GN:OKZ2:LLRA:T46W:ZW5T:3ZBV:J2KU:KW5Q:B7JV:I5HE:PYAU
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 docker.xxxx.com
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

![image](https://user-images.githubusercontent.com/41564930/64101351-43f37180-cda0-11e9-88ef-7a5aae1d3b86.png)

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/issues/39643

should be fixed in v18.09.9

**Comment by 493613735** [comment]
According to the link you sent, there is still this problem in version 19.03. Are you sure it was fixed in 18.09.9

**Comment by AkihiroSuda** [comment]
see https://github.com/docker/engine/pull/311

**Comment by 493613735** [comment]
At present, the status of docker 18.09-9 is still beta, may I ask if it is ok to back to a certain version
