### ISSUE TITLE
Flaky test: awslogs tests failing with ResourceAlreadyExistsException

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#39857]
Not sure if related to similar errors, but there were some fixes for race-conditions in the past (see https://github.com/moby/moby/issues/22963, and https://github.com/moby/moby/pull/22985)

Seen this failing a couple of times: 

Failure on RS1 (but I may have seen this on other platforms); https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39855/runs/1/nodes/39/log/?start=0

```
time="2019-09-03T10:15:19Z" level=info msg="Trying to get region from EC2 Metadata"
time="2019-09-03T10:15:19Z" level=info msg="Log stream already exists" errorCode=ResourceAlreadyExistsException logGroupName= logStreamName= message= origError="<nil>"
--- FAIL: TestLogBlocking (0.02s)
    cloudwatchlogs_test.go:313: Expected to be able to read from stream.messages but was unable to
time="2019-09-03T10:15:19Z" level=error msg=Error
time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
time="2019-09-03T10:15:19Z" level=info msg="Data already accepted, ignoring error" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token"
FAIL
coverage: 78.2% of statements
FAIL	github.com/docker/docker/daemon/logger/awslogs	0.631s
```

Interesting bit in that case is that the test that was marked failing looks to be using a `mockClient` (so should not even be connecting to AWS?) https://github.com/moby/moby/blob/e78a3dca21ea9ceb8d7a5e0252e94ee7ad05eadd/daemon/logger/awslogs/cloudwatchlogs_test.go#L288-L322

For other tests, we seem to be reusing the same `groupName` and `logStreamName`, so I suspect this is just a race condition (and AWS doesn't like attempting to create duplicates); https://github.com/moby/moby/blob/e78a3dca21ea9ceb8d7a5e0252e94ee7ad05eadd/daemon/logger/awslogs/cloudwatchlogs_test.go#L29-L36

Should we add a unique suffix to the `groupName` and `logStreamName` in the tests? (e.g., use the test name as suffix? `groupName+t.Name()`)

**Comment by samuelkarp** [comment]
None of these unit tests actually connect to AWS; they should all be using a mock.  This is now on my todo list to dig into later.

**Comment by thaJeztah** [comment]
Thanks! Let me know if I can help digging

**Comment by samuelkarp** [comment]
@thaJeztah Does this only occur on Windows?  What version(s) of Windows are running in CI (and failing) and with what version(s) of Go?  Is this running on hardware with constrained resources, running at the same time as other tests, etc?

**Comment by thaJeztah** [comment]
I think I've only seen it fail on Windows, and yes those can be a bit more constrained on resources (pulling/starting containers is more heavy on Windows)

**Comment by samuelkarp** [comment]
@thaJeztah I've opened https://github.com/moby/moby/pull/39968 to fix this.
