### ISSUE TITLE
Enhancement: Option to virtualize containers

### ISSUE THREAD

**Issue by mcandre** [moby/moby#39895]
Advanced deployments such as gathering core dumps for failing applications, involve making kernel tweaks that are difficult to do with a typical, unprivileged Docker container. The problem of altering the kernel is amplified in Kubernetes, where tenants may not even have access to run privileged containers.

One solution would be to explicitly wrap applications in a Vagrant VM inside the container, where the kernel can be tweaked at will.

I'm requesting that this wrapping become a straightforward option, so that `docker exec` and similar commands pass from the host, through the container, into Vagrant, able to seamlessly interoperate the VM as an normal, albeit slow, container for debugging purposes. As a side effect, this integration would allow for more guest OS's to run at scale in Docker pods, from Illumos to Haiku to macOS.

**Comment by AkihiroSuda** [comment]
You might want to try https://katacontainers.io/

Vagrant-based runtime also sounds good, but it should be implemented as a 3rd party OCI runtime
