### ISSUE TITLE
Add test to verify that all packages have import comments

### ISSUE THREAD

**Issue by SamWhited** [moby/moby#39898]
A test should be added to verify that all packages have correct import comments per the discussion in #39829.

**Comment by SamWhited** [comment]
Added a quick lint for this to https://git.sr.ht/~samwhited/checkdoc, we can use that later in CI if desired. It also checks for the presence of doc comments, so we'd need something like [git-ratchet](http://gitratchet.org/) to ensure that we're not firing on existing packages, but only if a package is added without docs.

**Comment by thaJeztah** [comment]
> so we'd need something like git-ratchet to ensure that we're not firing on existing packages, but only if a package is added without docs.

Wondering if that's needed; if someone happens to _remove_ the import comment, wouldn't that cause the mistake to be ignored? We should do a run once, to verify all packages have the comment, and after that we can enable the check (we can manually exclude paths if needed)

Also, related https://github.com/moby/moby/pull/39050 😅

**Comment by thaJeztah** [comment]
These import comments are ignored when using go modules (also in vendor mode). I think we don't have to add more validation for these (but hopefully we'll be able to make the full transition to modules in future).
