### ISSUE TITLE
Running gparted Dockerfile on macOS for microSD: no such file or directory

### ISSUE THREAD

**Issue by OutsourcedGuru** [moby/moby#39896]
**Description**
I was hoping to use the [desktop-integration/gparted](https://github.com/moby/moby/blob/master/contrib/desktop-integration/gparted/Dockerfile) Docker configuration in order to allow a MacBook to edit the partitions on an inserted microSD card. The card contains two partitions (FAT/ext4) to support a typical Raspbian Buster installation.

Given that neither Microsoft/Apple wishes to support `ext4`, this technique might be a game-changer for anyone within the Raspberry Pi support area.

Not sure if this is expected to work but a couple of online reviews seemed to suggest that it does work.

**Steps to reproduce the issue:**
1. Insert a Raspbian-imaged microSD into a macOS workstation
2. Install Docker of course
3. `df -h` # to determine how the card has been mounted (/dev/disk2s1 only the FAT)
4. `docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/disk2:/dev/disk2 --name gparted jess/gparted`

**Describe the results you received:**
`docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/disk2": no such file or directory.`

**Describe the results you expected:**
I was hoping that the `gparted` GUI would display, allowing me to potentially resize the second partition.

This activity would allow one in theory to shrink the second partition prior to using other software to create an IMG file suitable for publication/sharing.

**Additional information you deem important (e.g. issue happens only occasionally):**
I found it necessary each iteration to then:

```
docker ps -a
# Find that the container exists.
docker rm gparted
```

I also tried just `/dev/disk2s2` but that didn't work either. I also tried by prepending `sudo`; and that didn't work.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 79
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: UX4D:KFGT:GCK6:SNP3:VGQP:FLU5:F665:WBAP:2JRG:BWOR:UYPQ:O5BB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 57
 System Time: 2019-09-10T17:37:20.368517913Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacBook macOS Mojave 10.14.5

**Comment by OutsourcedGuru** [comment]
That was my fear, that it just wouldn't work on other platforms. But that's also the siren song of Docker, that it can bridge those gaps.

**Comment by AkihiroSuda** [comment]
Maybe you can run iSCSI target or NBD server on macOS and connect to it from a container

**Comment by bozzochet** [comment]
Ciao,

I found this thread looking for a 'recipe' to do the same thing: using `gparted` via Docker on macOS. I realized is not doable "as it is", but can be done "going back" to the old Docker approach on macOS: `docker-machine`.
I was able to do it by:
- creating a virtualbox docker-machine
- attaching to it the desired raw device via `vboxmanage` or VirtualBox GUI interface
- run the `docker` after moving the environment to `docker-machine` 

Even doing `docker-machine ssh` allows you to see if the device is seen by the machine and then you can run the docker with a "standard":
```
docker run --rm -t -i -v /dev:/dev -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 --privileged --cap-add=ALL prova_gparted:1.0 /bin/bash
```
Sorry for the "intrusion", I hope it helps!

Ciao,
Matteo
