### ISSUE TITLE
problem with DNS in container after router reboot

### ISSUE THREAD

**Issue by ofirule** [moby/moby#39907]
Env:
```
nvidia@tegra-ubuntu:~$ uname -a
Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Fri Oct 5 13:00:07 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
nvidia@tegra-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
nvidia@tegra-ubuntu:~$ docker -v
Docker version 18.06.1-ce, build e68fc7a
```

On host machine I create a static ip to my router via ethernet, using the following command:
```
nmcli c add type ethernet ifname eth0 con-name MyEth ip4 10.17.0.50/24 gw4 10.17.0.1 && nmcli con mod MyEth ipv4.dns "8.8.8.8 8.8.4.4"
```

After that running my container works fine and the content of the containers' /etc/resolv.conf is:
```
# Generated by NetworkManager
nameserver 127.0.1.1
```

After I reboot my rooter , the  containers' /etc/resolv.conf is empty, and dns resolving failes inside the container, but works on the host machine

My workaround is setting the dns server to the container with the --dns flag, but this solution is not ideal.

So I guess it's either a bug or I am doing something wrong in the process.

Would like to have a fix or an update on how should I handle this scenario differently

**Comment by thaJeztah** [comment]
note that docker 18.06 has reached EOL a year ago; are you still able to reproduce this on a current version of Docker (19.03 at time of writing)?

**Comment by thaJeztah** [comment]
Closing as this went stale
