### ISSUE TITLE
A mistake in the moby/image/spec/v1.md 

### ISSUE THREAD

**Issue by MChaus** [moby/moby#39914]
**A mistake in the moby/image/spec/v1.md **

**Steps to reproduce the issue:**
It looks like that titles below were swapped in the doc file moby/image/spec/v1.md :

**Entrypoint array of strings**
A list of arguments to use as the command to execute when the container starts. This value acts as a default and is replaced by an entrypoint specified when creating a container.

**Cmd array of strings**
Default arguments to the entry point of the container. These values act as defaults and are replaced with any specified when creating a container. If an Entrypoint value is not specified, then the first entry of the Cmd array should be interpreted as the executable to run.

**Describe the results you received:

**

**Describe the results you expected:

**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mebays** [comment]
These labels seem correct, and I don't think they are an issue. 

Take a look at the [docs](https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example) from docker. It might help explain it more.

**Comment by MChaus** [comment]
> These labels seem correct, and I don't think they are an issue.
> 
> Take a look at the [docs](https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example) from docker. It might help explain it more.

Seems you are right. Sorry, I am still just a noob in Docker and misunderstood the explanation. I'm closing the issue.
