### ISSUE TITLE
Fixme: SA1019: httputil.ClientConn is deprecated

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#39927]
Tracking issue for some remaining linting issues to be fixed after https://github.com/moby/moby/pull/39668 is merged.

```
integration-cli/docker_api_attach_test.go:239:134:    SA1019: httputil.ClientConn is deprecated: Use Client or Transport in package net/http instead.  (staticcheck)
```

These warnings are currently suppressed in `hack/validate/golangci-lint.yml` (after https://github.com/moby/moby/pull/39668 is merged), so when this is fixed, those lines should be removed

**Comment by jmartin84** [comment]
like #39926 hijack is not supported.

**Comment by yedamao** [comment]
ping @thaJeztah 

I submit a pr #40074 use writable ``` Transport's Response.Body```  to  replace deprecated ```hijacked httputil.ClientConn```. 

PTAL
