### ISSUE TITLE
Fixme: SA1019: grpc.WithDialer is deprecated

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#39928]
Tracking issue for some remaining linting issues to be fixed after https://github.com/moby/moby/pull/39668 is merged.

```
daemon/daemon.go:885:3:                               SA1019: grpc.WithDialer is deprecated: use WithContextDialer instead.  Will be supported throughout 1.x.  (staticcheck)
```

These warnings are currently suppressed in `hack/validate/golangci-lint.yml` (after https://github.com/moby/moby/pull/39668 is merged), so when this is fixed, those lines should be removed

**Comment by jmartin84** [comment]
I've started to work on a PR for this.
