### ISSUE TITLE
containerd-shim process left after stopping docker

### ISSUE THREAD

**Issue by mindrunner** [moby/moby#39976]
**Description**

After shutting down docker, some remnant processes seem to be left. This prevents me from proper unmounting and shutting down the server.

**Steps to reproduce the issue:**
1. `systemctl stop docker`
2. `ps aux | grep containerd`

**Describe the results you received:**
`root        6203  0.0  0.0 108988  4760 ?        Sl   Sep20   0:07 containerd-shim -namespace moby -workdir /mnt/data/docker/containerd
`
**Describe the results you expected:**
No processes running and all file descriptors closed on the /mnt/data/docker/ volume

**Additional information you deem important (e.g. issue happens only occasionally):**
This does not always happen. More likely the longer the server was up.

**Output of `docker version`:**

```
[le@nx]: ~>$ docker version
Client:
 Version:           19.03.2-ce
 API version:       1.40
 Go version:        go1.13
 Git commit:        6a30dfca03
 Built:             Tue Sep  3 23:41:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13
  Git commit:       6a30dfca03
  Built:            Tue Sep  3 23:39:37 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.9.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
[le@nx]: ~>$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 89
 Server Version: 19.03.2-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.1-arch1-1-ARCH
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: nx
 ID: CCE2:SHZM:I6QY:6BG3:3HA2:XHTO:45O3:AJAB:3GPP:UGOO:PETU:YJPB
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Arch Linux on Proxmox via KVM

**Comment by thaJeztah** [comment]
ping @crosbymichael @dmcgowan PTAL

**Comment by thaJeztah** [comment]
Where did you install those packages from? Note that Docker itself does not provide packages for Arch Linux (and it's definitely not tested); 

```
  Version:          v1.2.9.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
```

I see a `.m` suffix in those versions (and commit); if those packages are provided/built by Arch linux, there may be modifications in there. If the package you installed is provided by Arch Linux, have you also reported with the packagers?

**Comment by mindrunner** [comment]
I installed this packages from Arch package manager. I have no idea what `.m` means.

**Comment by mindrunner** [comment]
https://bugs.archlinux.org/task/63942
