### ISSUE TITLE
Remove Minsky and Stallman from the name generator

### ISSUE THREAD

**Issue by KatharinaViktoria** [moby/moby#39981]
Given the latest news about Minsky's involvement with Jeffrey Epstein, the really serious accusations against Minsky and related to it Richard Stallman's inappropriate comments, Minsky as well as Stallman should be removed from the name generator.

**Comment by thaJeztah** [comment]
😞 good catch, thanks!

I see you're working on a PR; I see that your commit does not have a DCO sign-off (which will cause CI to fail); you can fix that by;

```
git commit -s --amend --no-edit
```

and then _force push_ to your branch on GitHub (assuming your remove is named `origin`;

```
git push -f origin
```
