### ISSUE TITLE
Update links/references to transferred repositories

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#39989]
We transferred a couple of repositories to the moby org; GitHub redirects them from the old location, but we should not rely on those redirects, and update references to them to use the new location;

Old location | New location
---|---
https://github.com/jhowardmsft/docker-ci-zap | https://github.com/moby/docker-ci-zap
https://github.com/jhowardmsft/docker-signal | https://github.com/moby/docker-signal
https://github.com/jhowardmsft/busybox | https://github.com/moby/busybox
https://github.com/jhowardmsft/busybox64 | not transferred should not be referenced anywhere
https://github.com/jhowardmsft/docker-tdmgcc | https://github.com/moby/docker-tdmgcc

**Comment by thaJeztah** [comment]
@ddebroy @stefanberger 

/cc @jhowardmsft

**Comment by thaJeztah** [comment]
oops, apologies  @stefanberger - meant to type @StefanScherer (github autocomplete 🙄)

**Comment by stevewithey** [comment]
FYI the redirect doesn't seem to have been set up for the docker-ci-zap repo and now a security researcher is cyber squatting on the old url... Fortunately they are a good person and are notifying people who use the old url, but it would be good to fix that...

**Comment by thaJeztah** [comment]
Ugh, thanks for the heads-up. Looks like the happened because `jhowardmsft` changed his handle after we moved the repositories, which broke the redirects, and made the old name available for others to use 😞. I guess people would only run into this when building EOL versions of the code (and/or old mentions of that repository), but still not great.

**Comment by stevewithey** [comment]
Thanks, it's referenced in a few blog posts and other places across the web, I've contacted Microsoft and done a PR on one of their scripts that references the old url too: https://github.com/microsoft/nav-arm-templates/pull/197

**Comment by thaJeztah** [comment]
@stevewithey you mentioned that the squatter reached out to people; do you happen to have contact details for them? If so, could you send an email to `security@docker.com` ? (We could then reach out to them, and our contacts at GitHub to reserve the namespace, and to (re-)install redirects).

**Comment by stevewithey** [comment]
Sorry for the delay.  You can reach out to them through the email in the code here: https://github.com/jhowardmsft/docker-ci-zap/blob/master/zap.go#L13
