### ISSUE TITLE
 Why do docker take up a lot of system cache

### ISSUE THREAD

**Issue by Belyenochi** [moby/moby#40006]
**Description**

kernel version:  linux 4.19.1-1.e17.elrepo.x64_64
docker version: 18.06.3-ce
**Steps to reproduce the issue:**
cat /sys/fs/cgroup/memory/system.slice/docker.service/memory.stat

**Describe the results you received:**
I found that the dockerd process takes up a lot of system cache.

**Describe the results you expected:**
Docker automatically cleans up the cache

**Comment by nevermosby** [comment]
We have the same issue here. It is found that "docker" uses "container_memory_cache" about 40G reported by cAdvisor. 
Docker vesion: 1.12.1
OS version: RHEL 7.3
Kernel version: 3.10.0.514

**Comment by thaJeztah** [comment]
Note that both Docker 18.06 and 1.12.1 reached EOL and are no longer maintained; Docker 18.06 reached EOL a Year ago, and Docker 1.12.1 is _really_ old (has not been maintained for almost three years, and has known vulnerabilities).

Given that both reported versions are very old, and there's not a lot of information to go on (nor a reproducible step), I'll close this issue.

When reporting issues, please provide information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.
