### ISSUE TITLE
integration-cli failures in TestDockerNetworkSuite on s390x and ppc64le

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#40010]
The tests run against the code on `master` branch after PRs are merged are consistently red: https://ci.docker.com/public/blue/organizations/jenkins/moby/activity?branch=master

With the same 12 tests failing on `s390x` or `ppc64le`:

Test Name | Duration | Age
-- | -- | --
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverBindExternalVolume | 45 sec | 5
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverGet | 30 sec | 5
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverList | 45 sec | 5
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverNamed | 16 sec | 5
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverWithDaemonRestart | 1 min 0 sec | 5
Build / ppc64le integration-cli / Integration-cli tests / ppc64le.integration-cli.TestDockerNetworkSuite | 9 min 5 sec | 5
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverBindExternalVolume | 45 sec | 14
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverGet | 30 sec | 14
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverList | 45 sec | 14
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverNamed | 16 sec | 14
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite/TestExternalVolumeDriverWithDaemonRestart | 1 min 0 sec | 14
Build / s390x integration-cli / Integration-cli tests / s390x.integration-cli.TestDockerNetworkSuite | 9 min 6 sec | 14

I see that most of the build failures are solely because of these tests.

cc @arkodg @joeabbey

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/40015 to allow easier debugging of these tests; @arkodg @joeabbey let me know if you want commits to be cherry-picked into that branch and/or if you need push access

**Comment by thaJeztah** [comment]
LOL; at least we should fix this: https://github.com/moby/moby/pull/40016

**Comment by thaJeztah** [comment]
Looks like with #40016 applied, it's passing on https://github.com/moby/moby/pull/40015#issuecomment-536623378
