### ISSUE TITLE
RHEL 8 officially supported by docker-ce/docker-ee ?

### ISSUE THREAD

**Issue by taclano** [moby/moby#40025]
I would like to move update my servers to RHEL 8 for security reasons. 
On the official page https://success.docker.com/article/compatibility-matrix there is no mention of RHEL 8, is it supported ? 
If not, is there a timeline for when this will happen ?

**Comment by thaJeztah** [comment]
No, it's not yet supported, there are some issues to address around (I think) the switch to nftables, and some other issues; also kubernetes ran into the same problem and (again, I think) does not yet support RHEL 8.

> I would like to move update my servers to RHEL 8 for security reasons

Could you elaborate what security issues? RHEL 7 is still under active support (by Red Hat), so should not have security issues.

**Comment by taclano** [comment]
Thanks for the quick response !
The reason is that the openssl version that comes by default on RHEL 7 will go out of support on 2019-12-31 That's why we want to move to the next version.

**Comment by thaJeztah** [comment]
> The reason is that the openssl version that comes by default on RHEL 7 will go out of support on 2019-12-31 That's why we want to move to the next version.

That should not be a problem; when you're running RHEL, you're paying Red Hat to maintain and patch packages. This means that, even though the version of a package may be old (and out of support _upstream_), Red Hat takes the responsibility of backporting (security) fixes to those packages.

For example, RHEL 6 was released in 2010, but still receives patches until 2020; https://access.redhat.com/support/policy/updates/errata (or even 2024 with extended support); likely many packages that comes with RHEL 6 are no longer supported upstream.

**Comment by AkihiroSuda** [comment]
> there are some issues to address around (I think) the switch to nftables, and some other issues; 

do we have github issues for the nftables stuff?

**Comment by thaJeztah** [comment]
> do we have github issues for the nftables stuff?

Not sure if there is an issue; I was not closely working on that issue, but perhaps @seemethere, @arkodg or @justincormack could fill me in; I think some of these were in Kubernetes.

Note that this is about Docker EE, as Docker CE is not (officially) supported on RHEL

**Comment by arkodg** [comment]
There are no issues from a correctness perspective wrt `Docker` and` iptables-nft` (which RHEL 8 has installed) .
But it has introduced some slowness due to the extra translation layer which I believe @unclejack was looking into (by possibly intelligently circumventing the `iptables` layer and using `nft` directly ), can't find the thread right now

**Comment by thaJeztah** [comment]
The slowness issue was https://github.com/moby/moby/issues/39590

**Comment by kakoni** [comment]
@arkodg It seems that networking doesnt work correctly (as per https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8)

The fix seems to be that you need to enable Masquerading 
```firewall-cmd --zone=public --add-masquerade --permanent```

**Comment by arkodg** [comment]
hi @kakoni , I believe you are referring to `RHEL8` with `firewalld` installed .
And we've noticed that firewalld with `FirewallBackend=nftables` doesn't go well with Docker
And so two options to fix this issue are
1. Use FirewallBackend=iptables
2. or Include the interface
`firewall-cmd --permanent --zone=trusted --add-interface=docker0;
           firewall-cmd --reload`
A more permanent solution could be to automate this plumbing this `libnetwork` - https://github.com/docker/libnetwork/blob/master/iptables/firewalld.go
