### ISSUE TITLE
Docker for Windows requires installing Hyper-V even though it's not needed for WSL 2

### ISSUE THREAD

**Issue by aelij** [moby/moby#40033]
**Description**

**Steps to reproduce the issue:**
1. Install WSL 2
2. Install Docker for Windows preview
3. Start Docker for Windows

**Describe the results you received:**
D4W prompts to install Hyper-V. Clicking Cancel closes docker. However, right clicking the Docker icon and activating WSL 2 works just fine without Hyper-V installed (while the dialog remains open).

**Describe the results you expected:**
Prompt for Hyper-V installation only when running Docker in the default (non-WSL2) mode.

Additionally, under some conditions I've seen the Docker installer automatically enable Hyper-V, which should also be avoided.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.67-microsoft-standard
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.28GiB
 Name: DESKTOP-JGT4STF
 ID: ZEZX:V5QJ:ZZLS:WI2T:TGVV:PEXI:PNSF:AHLT:SHHL:CISE:LTZU:SEJU
 Docker Root Dir: /var/data/docker-desktop/default/daemon-data
 Debug Mode: true
  File Descriptors: 27
  Goroutines: 46
  System Time: 2019-10-03T13:56:32.8556708+03:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
I'm under the impression that hyper-v is a requirement for WSL2, given that WSL2 is a VM.

**Comment by aelij** [comment]
@cpuguy83 WSL 2 does use a VM, but it requires a different feature called "Virtual Machine Platform" which (as I understand it) is more lightweight than Hyper-V (see the [docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#enable-the-virtual-machine-platform-optional-component-and-make-sure-wsl-is-enabled).)

**Comment by cpuguy83** [comment]
It's the same.

**Comment by aelij** [comment]
@cpuguy83 Maybe the underlying technology is the same, but from the Windows Feature installer it's not the same (they have different IDs, `VirtualMachinePlatform` and `Microsoft-Hyper-V`.) On my machine Hyper-V wasn't installed but WSL2 and Docker worked.

**Comment by aelij** [comment]
Moving to docker/for_win

**Comment by thaJeztah** [comment]
moved to https://github.com/docker/for-win/issues/4934
