### ISSUE TITLE
host's "nproc"  and docker "nproc, cpuset.cpus" mismatch after hot plug CPUs

### ISSUE THREAD

**Issue by jmarcos-cano** [moby/moby#40041]
Docker does not sees a new cpuset if hot added after provisioning a VM with less CPUs because it hard codes somehow its original cpuset in `/sys/fs/cgroup/cpuset/docker/cpuset.cpus`

In other words:
Boxes that were provisioned with `N` CPUS and later you bumped the resources to `N+x` CPU cores, will experience the problem where Docker will only see N CPUs available in every container instead of N+x CPUs

I believe containers should use the value from `docker info` => `CPUs: 8` (runtime) instead of hardcoding it during installation.

**Steps to reproduce the issue:**
1. Create a VM and provision it with 2 CPUs, install docker and everything.

2. During installation docker writes the available cpuset at the moment (0-1) to `/sys/fs/cgroup/cpuset/docker/cpuset.cpus`

At this point `docker info` displays:
```
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 11.69GiB
```

3. Eventually you figure out you need more resources, because your apps require so, so you add 6 more CPUs.

If you run `docker info` indeed it knows about your new 6 CPUS

```
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.69GiB
```
### Host OS
Your OS knows about them
```
$ nproc
8
```

but the namespaced cpuset in docker is not refreshed (obviously):
```
$ cat /sys/fs/cgroup/cpuset/docker/cpuset.cpus
0-1
```

### Containers
Containers doesn't know about these new cores as well
```
$ docker run -it centos:7 nproc
2
```

If I try to use **more** cpus than available it claims that it knows about the new cpuset
```
$ docker run -it --cpuset-cpus=0-10 centos:7 nproc
docker: Error response from daemon: Requested CPUs are not available - requested 0-10, available: 0-7.
```

But if I try to use a range in between the available ones (0-3):

```
$ docker run -it --cpuset-cpus=0-3 centos:7 nproc
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"failed to write 0-3 to cpuset.cpus: write /sys/fs/cgroup/cpuset/docker/e55dce73f5174f16fb360f01a774163da027315d0a1f648268e3fca6368cdd4a/cpuset.cpus: permission denied\"": unknown
```

Which led me to [536](https://github.com/docker/for-linux/issues/536), even though this is related to 536 it is not fully related

### The solution seems to be
```
echo "0-7" > /sys/fs/cgroup/cpuset/docker/cpuset.cpus

# or more "dynamically"
echo "0-$(( $(nproc) - 1 ))" >  /sys/fs/cgroup/cpuset/docker/cpuset.cpus

```

**Additional information you deem important (e.g. issue happens only occasionally):**

I don't think this affects a particular version of Docker, rather all versions

<details><summary><bold>Output of `docker version`: </bold></summary>
<p><br>

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
<br>
</p>
</details>

<details><summary><bold>Output of `docker info`: </bold></summary>
<p><br>

```
Containers: 14
 Running: 9
 Paused: 0
 Stopped: 5
Images: 10
Server Version: 18.09.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: qskzvycajleyypxy56rjzt03n
 Is Manager: true
 ClusterID: c9bw8td1bw1zoc5ms77iwmkf3
 Managers: 3
 Nodes: 5
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.18.0.72
 Manager Addresses:
  10.18.0.71:2377
  10.18.0.72:2377
  10.18.0.73:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.69GiB
Name: xxx.xxxxx.x
ID: DXTN:VFYO:IJUP:DCAX:LEVQ:VKL6:2MMK:GLOI:3RKF:5PAX:DWP7:SLO3
Docker Root Dir: /usr/share/mobi/docker_data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

<br>
</p>
</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Note: I really don't think this is an issue but I wanted to point it out if anyone ever faces something related to this.

**Comment by satwikk** [comment]
Exactly the issue I was trying to resolve. I wonder if we can configure relevant settings or mention in daemon.json so that this cpuset is updated in real-time.

**Comment by thaJeztah** [comment]
Hm; so I think the base issue here might actually be in `runc`. IIUC, whenever a container is started, it first will make sure that all parent cgroups have `cpuset.cpus` set; https://github.com/opencontainers/runc/blob/46243fcea186a0712da0f8838e40b77c634879a1/libcontainer/cgroups/fs/cpuset.go#L116-L135

```go
// ensureParent makes sure that the parent directory of current is created
// and populated with the proper cpus and mems files copied from
// it's parent.
func (s *CpusetGroup) ensureParent(current, root string) error {
	parent := filepath.Dir(current)
	if libcontainerUtils.CleanPath(parent) == root {
		return nil
	}
	// Avoid infinite recursion.
	if parent == current {
		return errors.New("cpuset: cgroup parent path outside cgroup root")
	}
	if err := s.ensureParent(parent, root); err != nil {
		return err
	}
	if err := os.MkdirAll(current, 0755); err != nil {
		return err
	}
	return s.copyIfNeeded(current, parent)
}
```

Which means that those values are set the first time, and not updated afterwards.

I'm not sure if there's an easy fix to update those when the configuration changes (CPUs added), because it's also possible that a user explicitly/manually has overridden those values; there's use-cases where users want to restrict _all_ containers to specific CPUs, and thus update the parent cgroups to reflect that. If docker would be updating those values on restart/reloading the daemon, it would then be overwriting those custom settings 🤔


@AkihiroSuda @kolyshkin any ideas?

**Comment by kong62** [comment]
same issue：
```
[root@Sit-Test-08 ~]# docker run -it harbor.sit.hupu.io/ci/jenkins:2.178 nproc                       
4

[root@Sit-Test-08 ~]# nproc 
8

[root@Sit-Test-08 ~]# top
top - 14:25:09 up 77 days,  1:18,  1 user,  load average: 1.76, 2.15, 1.77
Tasks: 228 total,   2 running, 226 sleeping,   0 stopped,   0 zombie
%Cpu0  : 36.2 us,  2.3 sy,  0.0 ni, 60.5 id,  0.0 wa,  0.0 hi,  1.1 si,  0.0 st
%Cpu1  : 35.5 us,  2.9 sy,  0.0 ni, 59.9 id,  0.0 wa,  0.0 hi,  1.7 si,  0.0 st
%Cpu2  : 35.2 us,  2.8 sy,  0.0 ni, 60.8 id,  0.0 wa,  0.0 hi,  1.1 si,  0.0 st
%Cpu3  : 89.2 us,  8.1 sy,  0.0 ni,  1.4 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
%Cpu4  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.3 us,  0.3 sy,  0.0 ni, 99.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.9 us,  0.3 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
```


```
# docker info
Server Version: 18.09.6
CPUs: 8
```

```
[root@Sit-Test-08 ~]# uname -r
3.10.0-693.2.2.el7.x86_64
[root@Sit-Test-08 ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

**Comment by thaJeztah** [comment]
Let me close this one in favour of https://github.com/moby/moby/issues/27453, but possibly may have to be tracked elsewhere; https://github.com/moby/moby/pull/34533#issuecomment-343274761
