### ISSUE TITLE
Please move the github.com/Microsoft/hcsshim import to some windows specific file

### ISSUE THREAD

**Issue by elboulangero** [moby/moby#40067]
https://github.com/moby/moby/blob/588d0e61338e0d607ff62908bdfb5b33d02e0d86/libcontainerd/remote/client.go#L16

My understanding is that HCS is for Windows host only.

While packaging docker for Debian, I have to patch this out explicitly.

This was introduced in commit 85ad4b16c11. By looking at the code, only windows specific code imports Microsoft/hcsshim. This file is the only exception.

I'm not familiar enough with the code to find the right solution, so I just patch it out in order to build docker on Debian. However, maybe there's a better solution, and this bit could be moved somewhere else, in a Windows specific file?

Thanks!

**Comment by thaJeztah** [comment]
Opened a pull request to address this; https://github.com/moby/moby/pull/40146
