### ISSUE TITLE
What is the purpose of the build --rm=false option? 

### ISSUE THREAD

**Issue by TZubiri** [moby/moby#40078]
the --rm option of the build command allows users to decide whether they would like to override docker's default behaviour and save intermediate containers, which are containers used during the build process.

I personally don't see any reason to keep these containers as they can be generated at will from the images made out of them. I don't even see the physical differences between them other than the metadata recorded from its run, perhaps this is its purpose? Perhaps one would need to inspect the start and finish times, or its error codes and other such info.

**Comment by cpuguy83** [comment]
Yep, pretty much to inspect the intermediate build state.

**Comment by thaJeztah** [comment]
This flag is originating from legacy functionality. Way back, the builder would start a new container for each step in the Dockerfile, run the step, and commit the changes to a new image.

Originally, those containers would be stopped after the step completed (after which a new container was started for the next step), however, the container would not be _removed_; this allowed you to inspect the intermediate stages (for debugging), by inspecting the container (or starting the container)

Obviously, that left a lot of "clutter" after a build, and you'd have to manually clean up those containers. So, a `--rm` flag was added, which would allow you to automatically delete the container after a step was successful.

Most users wanted this behavior, thus at some point, `--rm`  was made the default; intermediate containers were now automatically removed. But, some users relied on the old behavior, and for those, the `--rm` flag was kept, allowing them to set `--rm=false` to keep the old behavior.


Given that this feature is only for debugging purposes, and not widely used, the next generation builder (BuildKit) no longer supports this option; so if you have buildkit enabled (which you can do by setting the `DOCKER_BUILDKIT=1` environment variable; which I highly recommend), the `--rm` flag no longer has an effect.
