### ISSUE TITLE
docker log driver syslog ,if syslog is not running ,docker daemon or container is health ?

### ISSUE THREAD

**Issue by arrow2012** [moby/moby#40093]
ubuntu 16

Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

/etc/docker/daemon.json

  "log-driver": "syslog",
  "log-opts": {
   "syslog-address": "tcp://localhost:514",
   "tag": "{{.Name}}/{{.ID}}/{{.ImageName}}"
  }

docker logs -f     
Error response from daemon: configured logging driver does not support reading

if the rsyslog server is not running .

the docker daemon service or docker container will be affect ?

**Comment by cpuguy83** [comment]
Not sure I'm understanding the question.
But I'm assuming you are asking what happens to container logging if the syslog service is down?
In that case writes will end up blocking until syslog is up. This can lead to the container process being blocked writing to stdout/stderr.
You can setup a non-blocking mode for the log driver in which case it will drop writes.

https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver
