### ISSUE TITLE
Hi @JohnStarich,

### ISSUE THREAD

**Issue by alexandru-ersenie** [moby/moby#40127]
Hi @JohnStarich,
take a look at this, it covers pretty much how to do it. 
http://www.tresmundi.com/docker-logging-pitfalls-solving-multiline-stacktraces-and-docker-16-kb-message-split/

**Comment by bamb00** [comment]
Is there an example like **http://www.tresmundi.com/docker-logging-pitfalls-solving-multiline-stacktraces-and-docker-16-kb-message-split/** but uses ```partial_key``` and ```partial_value```?
