### ISSUE TITLE
Nested `bash -c` in RUN instruction; JSON unmarshalling issue?

### ISSUE THREAD

**Issue by dgroomes** [moby/moby#40140]
**Nested `bash -c` in RUN instruction produces a malformed command**

I expect the issue has to do with the JSON unmarshalling for the `RUN` instruction in the exec form; the closest Github issue I could find was <https://github.com/moby/moby/issues/2105#issuecomment-26191138>.

The tip off is the error output `/bin/sh: 1: [bash,: not found`. It seems like Docker is trying to add the JSON form to my nested bash command. It's like it's adding the leading `[` and a `,`to `bash`.

**Steps to reproduce the issue:**
1. Clone <https://github.com/dgroomes/docker-shell-example> and checkout <542dda6495624e05d472c5be4bbfaf8cf4e368ce>
2. Execute the Docker build with `./go.sh`

**Describe the results you received:**

I received:

```
Step 3/3 : RUN ["bash", "-c", "bash -c 'echo SHLVL: \$SHLVL'"]
 ---> Running in 2255c65b43c9
/bin/sh: 1: [bash,: not found
```

See <https://github.com/dgroomes/docker-shell-example/commit/542dda6495624e05d472c5be4bbfaf8cf4e368ce/checks?check_suite_id=282761273#step:8:22>

**Describe the results you expected:**

I expected something like

```
Step 3/3 : RUN ["bash", "-c", "bash -c 'echo SHLVL: \$SHLVL'"]
 ---> Running in 2255c65b43c9
2
```

I expected similar to <https://github.com/dgroomes/docker-shell-example/runs/276150757#step:5:1>

```
Run bash -c "bash -c 'echo \$SHLVL'"
  bash -c "bash -c 'echo \$SHLVL'"
  shell: /bin/bash -e {0}
3
```

**Output of `docker version`:** 

See <https://github.com/dgroomes/docker-shell-example/commit/542dda6495624e05d472c5be4bbfaf8cf4e368ce/checks?check_suite_id=282761273#step:6:4>
```
Client:
 Version:           3.0.6
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        a63faebc
 Built:             Wed Jun 19 22:56:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b07f53d
  Built:            Wed Jun 19 22:28:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

See <https://github.com/dgroomes/docker-shell-example/commit/542dda6495624e05d472c5be4bbfaf8cf4e368ce/checks?check_suite_id=282761273#step:7:4>

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 3.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduced in Github Actions <https://github.com/dgroomes/docker-shell-example/runs/276150757> and asked question at <https://stackoverflow.com/questions/58568027/how-to-correctly-format-a-nested-bash-command-in-dockerfile/58572365#58572365>

**Comment by thaJeztah** [comment]
Given that the `RUN` command will accept either a JSON array of strings or a literal shell command, it will do an initial attempt to parse the line as a JSON array; if that fails, it will treat it as a shell command https://github.com/moby/buildkit/blob/3f8ab160d5079539f9ed971fb069e4205108dd9d/frontend/dockerfile/parser/line_parsers.go#L303-L339


From the error;

```
/bin/sh: 1: [bash,: not found
```

It looks like it's going that second path.

Looking at your example; the given JSON is invalid;

```json
["bash", "-c", "bash -c 'echo SHLVL: \$SHLVL'"]
```

And, the `\` itself should be escaped (the `$` doesn't need escaping in the JSON form, because it won't be evaluated in the Dockerfile parser)


After changing that line, it works correctly;

```json
["bash", "-c", "bash -c 'echo SHLVL: \\$SHLVL'"]
```

```bash
docker build -<<'EOF'
FROM ubuntu
RUN ["bash", "-c", "bash -c 'echo SHLVL: \\$SHLVL'"]
EOF
```
```console
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu
 ---> a2a15febcdf3
Step 2/2 : RUN ["bash", "-c", "bash -c 'echo SHLVL: \\$SHLVL'"]
 ---> Running in 5ad4b75ee274
SHLVL: $SHLVL
Removing intermediate container 5ad4b75ee274
 ---> b78c94c04fc5
Successfully built b78c94c04fc5
```

**Comment by thaJeztah** [comment]
Let me close this issue, because this doesn't appear to be a bug, but feel free to continue the discussion.

**Comment by dgroomes** [comment]
Thank you for the explanation of the JSON part @thaJeztah! That is really enlightening

```JSON
["bash", "-c", "bash -c 'echo SHLVL: \$SHLVL'"]
```

That is a great tip: check for valid JSON.

Is there a way to write the RUN instruction so that it is valid JSON *and* will be escaped for Bash to actually to do the variable expansion on `SHLVL`? What I mean is, how do I format the following command, which I run on my mac, into a Dockerfile RUN instruction? : 

```
$ bash -c "bash -c 'echo \$SHLVL'"
3
```

So it seems like:
* one escape character is too little (it is not valid JSON)
* two escape characters is too much (Bash won't do variable expansion on `SHLVL`)

Alternatively, I don't actually care about this issue too much. I was just trying to find a way to illustrate this issue: <https://stackoverflow.com/q/58573830>. If you could explain that issue, it would be much appreciated!
