### ISSUE TITLE
During setup of stable Docker Engine repository in Ubuntu 18.04.02 Server Edition: cannot import name '_gi' from 'gi'

### ISSUE THREAD

**Issue by marcoippolito** [moby/moby#40153]
Following the indications found here: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository 
I'm trying to install Docker Engine in Ubuntu 18.04.02 Server Edition.

The first installation's steps went fine but I encountered this error message:

    (base) marco@pc:~$ sudo add-apt-repository \ 
    > "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    > $(lsb_release -cs) \
    > stable"
    Traceback (most recent call last):
      File "/usr/bin/add-apt-repository", line 11, in <module>
        from softwareproperties.SoftwareProperties import SoftwareProperties, 
    shortcut_handler
      File "/usr/lib/python3/dist-packages/softwareproperties
    /SoftwareProperties.py", line 67, in <module>
        from gi.repository import Gio
      File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in 
    <module>
        from . import _gi
    ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-
    packages/gi/__init__.py)

But import gi in python3 works fine:

    (base) marco@pc:~$ python3
    Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import gi
    >>> 

How to solve the problem?

Marco

**Comment by AkihiroSuda** [comment]
Seems unrelated to Moby/Docker
