### ISSUE TITLE
Add INCLUDE feature

### ISSUE THREAD

**Issue by XVilka** [moby/moby#40165]
Make it possible to include other Dockerfiles, quite useful for multistage builds, especially if the number of stages is more than 2.

There is https://github.com/moby/moby/issues/735 but it's closed, and multistage builds are very common nowadays. Thus, this issue even more relevant than in 2013.

**Comment by perllaghu** [comment]
Another use case:

You are building multiple variations on a theme:

```
    FROM <OS-of-choice>
    RUN <update-OS>
    INCLUDE <install common libraries set>
    RUN <install variation libraries>
    INCLUDE <install common config set>
```

For **me** - when I update the common libraries, I have to edit 11 files, not just one

For **me** - when I update the common config, I have to edit 11 files, not just one.

**Multi Stage builds is not always the answer**

Multi-stage builds are great, and they can reduce the foot-print of the final image - eg:

```
    FROM node:12
    ADD <files>
    WORKDIR /path
    RUN yarn install
    RUN yarb build

    FROM nginx
    COPY <config>
    COPY --from=0 /<path>/dist /usr/share/nginx/html
```
This throws away _all_ the rubbish from the yarn build, and only takes the resultant built tree.

.... but this only works when the thing from the first stage is whole & complete & isolatable - code libraries often aren't: Some compile against OS libraries; some build configuration details based on paths.... 

Being able to say "insert these lines into the Dockerfile here" covers this different use-case.

**Comment by edrevo** [comment]
I have implemented a custom buildlkit frontend that supports a new "INCLUDE" scenario. You can use it like this on recent Docker builds:

```Dockerfile
# syntax = edrevo/dockerfile-plus

FROM alpine

INCLUDE+ Dockerfile.common

ENTRYPOINT [ "mybin" ]
```

More info at https://github.com/edrevo/dockerfile-plus

**Comment by KOGI** [comment]
@edrevo your syntax works like a charm! However, I can't use it because I also need `# syntax=docker/dockerfile:experimental` in order to do ssh-forwarding and only 1 syntax is allowed. Is there a way I can use both dockerfile-plus AND experimental?

**Comment by edrevo** [comment]
@KOGI, sorry I don't have much time right now to maintain the project. You can change this line https://github.com/edrevo/dockerfile-plus/blob/master/dockerfile-plus/Dockerfile#L21 to whatever "base Dockerfile" you want to use. Then you need to `docker build -f dockerfile-plus/Dockerfile -t KOGI/dockerfile-plus .` and you can use your own syntax. I hope that helps!

**Comment by remidebette** [comment]
Hi, I have made a similar request here: https://github.com/docker/buildx/issues/1378
Maybe I should have done it in the moby project?

**Comment by thaJeztah** [comment]
closing in favor of https://github.com/docker/buildx/issues/1378
