### ISSUE TITLE
Big guys, how do you switch the cpu container to a gpu container? Request help.

### ISSUE THREAD

**Issue by zhoulei232** [moby/moby#40182]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
see https://github.com/NVIDIA/nvidia-docker

**Comment by zhoulei232** [comment]
> see https://github.com/NVIDIA/nvidia-docker

sorry, I made a mistake,I mean that a container that already contains a nvidia-docker's plugin.But don't load the plugin first,when I need,how to switch this container to gpu.Is there a way to do it?

**Comment by AkihiroSuda** [comment]
you should ask nvidia
