### ISSUE TITLE
OpenRC: add support of proxy configuration for docker daemon

### ISSUE THREAD

**Issue by gagara** [moby/moby#40201]
For openrc init systems it would be good to have possibility to configure HTTP(S) proxy servers for docker daemon.
e.g. for systemd there is documented approach https://docs.docker.com/config/daemon/systemd/#httphttps-proxy.

**Comment by hammad13060** [comment]
@thaJeztah Is this bug assigned to someone? I'd like to work on this one.

**Comment by thaJeztah** [comment]
I think this should be addressed by https://github.com/moby/moby/pull/42835 (which is on `master` only currently), see https://github.com/moby/moby/pull/40202#issuecomment-985661083


> Looks like there's no real consensus on this PR, but #42835 implemented ways to configure the daemon's proxy settings through either `daemon.json` or using `--http-proxy`, `--https-proxy` and `--no-proxy` command-line options for `dockerd`.
> 
> That patch has not yet been released (will be in the release after `20.10`), but with those, it should be possible to set those options through either `daemon.json` or to set them as `DOCKER_OPTS` (which is used by the OpenRC script).


Let me go ahead and close this, but feel free to continue the conversation!
