### ISSUE TITLE
The Container is assigned a separate ipv4 address by macvlan. By using the docker network connect bridge containerid manually, the container service will lose UDP support and the rate will become bad

### ISSUE THREAD

**Issue by nishuo** [moby/moby#40208]
The Container is assigned a separate ipv4 address by macvlan. By using the docker network connect bridge containerid manually, the container service will lose UDP support and the rate will become bad.

I first use Proxmox6 create kvm vps,then actual operation

> docker network create -d macvlan \\
> --subnet=60.249.3.0/24 \\
>  --gateway=60.249.3.254 \\
> -o parent=ens18 macvlan_bridge

>  docker run -d --log-driver=none --network=macvlan --ip=60.249.3.125 --restart=always

> docker network connect bridge container id

The assigned inner network addresses are now available, but the outer network service gets worse, losing UDP, and network performance becomes sluggish

Is this a bug? When I access both the macvlan and the bridge network, there will be problems.

**Comment by thaJeztah** [comment]
@arkodg ptal
