### ISSUE TITLE
Mounted volume not accessible after autofs restart on host

### ISSUE THREAD

**Issue by mjramtech** [moby/moby#40206]
If this is accepted as a bug or valid improvement request I'll happily provide all the docker version info etc I witnessed this against. I suspect though this is version agnostic.

Scenraio:

- Image files hosted on SERVER-1 at /storage/images
- SERVER-1/storage/images mounted on SERVER-2 as /mnt/sshfs/images via autofs (sshfs)
- Docker container on SERVER-2 binds /var/www/images to /mnt/sshfs/images, e.g. (this is a swarm service container, btw):
--mount type=bind,source=/mnt/sshfs/images,target=/var/www/images

All good at this point, an `ls` of /var/www/images within the above docker container lists the contents of what is ultimately SERVER-1/storage/images.

Now, on SERVER-2 (the docker container's host):
`systemctl stop autofs`
`systemctl start autofs`

An `ls` of /mnt/sshfs/images on SERVER-2 still lists the expected contents, but the above `ls` in the docker container now returns:
Socket not connected

Is it reasonable to expect the container bind to survive the autofs restart? I'm guessing the link the container inherits on initialisation is deeper than just the directory path on the host ...

**Comment by cpuguy83** [comment]
You will need to use add "slave" (or "rslave") bind mount propagation to the bind mount spec. This ensures that whatever host changes are made to the mount are propagated to the container.

**Comment by mjramtech** [comment]
> 
> 
> You will need to use add "slave" (or "rslave") bind mount propagation to the bind mount spec. This ensures that whatever host changes are made to the mount are propagated to the container.

Oh ok, I'll give that a try. I did see that option but understood it to only apply to mount points beneath the one explicitly specified as an argument (sub directories).

**Comment by thaJeztah** [comment]
I don't think there's a bug here, so I'll close this issue, but feel free to continue the conversation 👍
