### ISSUE TITLE
How to restrict the access of the specified physical machine user to the docker container on Linux

### ISSUE THREAD

**Issue by Ruilkyu** [moby/moby#40204]
such as ,when I use test user to run docker container,I use docker ps only can to see this user runned container ?

**Comment by AkihiroSuda** [comment]
The official way is to use [AuthZ plugin](https://docs.docker.com/engine/extend/plugins_authorization/), but setting up Kubernetes with RBAC seems more straightforward.

**Comment by Ruilkyu** [comment]
Thanks!
But, can you give me a specific way.

**Comment by cpuguy83** [comment]
Not really anyway to do this since authz plugins can only authorize a request/response, not change it.

Users could run their own daemon instead of giving access to a system daemon.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
