### ISSUE TITLE
Has issue to build windows docker image when windows kernel version does not match

### ISSUE THREAD

**Issue by shaoxp** [moby/moby#40215]
i want to build out windows docker image for Windows Server 2019(kernel :10.0.17763）on my local build machine which is Win10(kernel:10.0.15063). it will fail with 
> a Windows version 10.0.17763-based image is incompatible with a 10.0.15063 host

I tried to build with hyperv isolation with the following, it will get the same error.
>docker build --isolation="hyperv"

actually, the docker image will not run on my build machine, can it be expected to success either in hyperv isolation or process isolation? 

Many Thanks.

_Originally posted by @thaJeztah in https://github.com/moby/moby/issues/36552#issuecomment-554113263_

**Comment by thaJeztah** [comment]
@ddebroy @StefanScherer ptal

**Comment by StefanScherer** [comment]
There are two problems, both can be dixed by updating your Windows 10 machine to a newer OS version. 

Windows 15063 (1703) is out of support: https://docs.microsoft.com/en-us/windows/release-information/

You can run only containers that have the same OS version or older on the container host. HyperV isolation doesn‘t change that rule. https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

You have to update to at least Windows 10 1809 to build images for Windows Server 2019.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
