### ISSUE TITLE
new storage driver: fuse-overlayfs

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40218]
Currently, rootless `overlay2` storage driver works only on Ubuntu and Debian 10 hosts.

Supporting [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) would be highly useful for the users of other distros.

## System requirement

* [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) needs to be installed
* Kernel needs to be >= 4.18

## Implementation

Podman already implements fuse-overlayfs, but it is implemented as a storage opt ("overlay.mount_program") rather than an independent storage driver: https://github.com/containers/storage/blob/01ea27db516e1ea8dd22b63b69d3a66c571effa7/drivers/overlay/overlay.go#L307

For Moby, I suggest implementing it as a new independent storage driver "fuse-overlayfs".

My first plan was to wait until Moby migrates to containerd snapshotters and use [containerd fuse-overlayfs plugin](https://github.com/AkihiroSuda/containerd-fuse-overlayfs), but it is not likely to happen in foreseeable future.

**Comment by AkihiroSuda** [comment]
fuse-overlayfs also provides shiftfs functionality, so this proposal should be also useful for userns-remap mode.

cc @cpuguy83

**Comment by thaJeztah** [comment]
also /cc @dmcgowan @tonistiigi for the containerd integration

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/40483
