### ISSUE TITLE
Example in documentation for --env does not work

### ISSUE THREAD

**Issue by raxod502** [moby/moby#40221]
**Description**

The example in the documentation for `--env` does not work when copied and pasted into a terminal.

**Steps to reproduce the issue:**

As per the example given at https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file:

```
$ export VAR1=value1
$ export VAR2=value2
$ docker run --env VAR1=value1 --env VAR2=value2 ubuntu env | grep VAR` as directed by the documentation
```

**Describe the results you received:**

No output

**Describe the results you expected:**

The documentation says I should get

```
VAR1=value1
VAR2=value2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I can verify that explicitly setting the environment variable works as desired (it's only the bare variable without a value that doesn't work):

```
$ export VAR1=value1
$ export VAR2=value2
$ docker run --env VAR1=$VAR1 --env VAR2 ubuntu env | grep VAR
VAR1=value1
```

**Output of `docker version`:**

```
Client:
 Version:           19.03.4-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        9013bf583a
 Built:             Sat Oct 19 04:40:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 1
  Paused: 0
  Stopped: 20
 Images: 370
 Server Version: 19.03.4-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.84-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.05GiB
 Name: shallan
 ID: 4VJU:YGC3:5LGY:L6MR:77ZI:RR6T:KSSK:YN26:VGYG:E6CZ:R52Q:55BY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Manjaro Linux running latest as of 2019-11-14. Shell is Zsh 5.7.1.

**Comment by thaJeztah** [comment]
I'm not able to reproduce the issue;


```bash
export VAR1=value1
export VAR2=value2

# values passed with the `--env` flags
docker run --env VAR1=foo1 --env VAR2=foo2 ubuntu env | grep VAR
VAR1=foo1
VAR2=foo2

# no value passed (env's take value from the current environment)
docker run --env VAR1 --env VAR2 ubuntu env | grep VAR
VAR1=value1
VAR2=value2

# combination
docker run --env VAR1=$VAR1 --env VAR2 ubuntu env | grep VAR
VAR1=value1
VAR2=value2
```


Note that Manjaro is not officially supported (at least; untested). Could there be something in your setup causing this?

For example, could `docker` be an alias for (e.g.) a wrapper shell script? I know there's setups where a shell script is used to automatically use `sudo docker`, which would strip environment variables if the `-E` (or `--preserve-env`) option is not used.
What does `type docker` output?

**Comment by raxod502** [comment]
You are indeed correct, and the problem is that `sudo` (on some distros) will strip out most environment variables. Clearly not a Docker problem, sorry for the confusion.

**Comment by raxod502** [comment]
It would be _really_ nice if Docker had an option to automatically request `sudo` privileges if it needs them, like https://github.com/Jguer/yay does for example. That would obviate the need for the shell script, and solve this problem for other unsuspecting users.
