### ISSUE TITLE
Start daemon on macOS system boot

### ISSUE THREAD

**Issue by dachev** [moby/moby#40239]
Currently, the daemon is launched on login. This means that services running in containers (e.g. database) are unavailable to any system software (e.g. HTTP middleware) that is launched at boot time. What's more, they are unavailable until a user logs in and a GUI session is established.

**Comment by AkihiroSuda** [comment]
Not scope of Moby.
Please open an issue at https://github.com/docker/for-mac/issues

**Comment by dachev** [comment]
That repo points back here for daemon issues:

<img width="774" alt="Screen Shot 2019-11-25 at 3 56 51 PM" src="https://user-images.githubusercontent.com/66780/69526278-6ca09700-0f9c-11ea-8771-63883c465b67.png">

**Comment by AkihiroSuda** [comment]
Not a daemon (`dockerd`) issue.

The issue is on the Docker for Mac app, which is proprietary and unrelated to this repo.

**Comment by dachev** [comment]
Thanks
