### ISSUE TITLE
"tls: bad record MAC" on Qemu Risc-V VM

### ISSUE THREAD

**Issue by carlosedp** [moby/moby#40240]
**Description**

While trying to `docker pull` some images, Docker logs multiple `local error: tls: bad record MAC` errors into the Journal and keep retrying layers to pull the images. Eventually they get pulled.

```bash
...
Nov 24 13:32:51 qemuriscv dockerd[430]: time="2019-11-24T13:32:51.589142373Z" level=error msg="fatal task error" error="No such container: func_gateway.1.s97f0g29121agb0ew8tegqc95" module=node/agent/taskmanager node.id=xnmja6254jyia6kahqri8cune service.id=ofbzjkclec63bkzr47mnzzyei task.id=s97f0g29121agb0ew8tegqc95
Nov 24 13:32:51 qemuriscv dockerd[430]: time="2019-11-24T13:32:51.716350921Z" level=info msg="API listen on /run/docker.sock"
Nov 24 13:33:06 qemuriscv dockerd[430]: time="2019-11-24T13:33:06.884992784Z" level=info msg="Download failed, retrying (1/5): local error: tls: bad record MAC"
Nov 24 13:33:14 qemuriscv dockerd[430]: time="2019-11-24T13:33:14.156336788Z" level=info msg="Download failed, retrying (2/5): local error: tls: bad record MAC"
Nov 24 13:33:14 qemuriscv dockerd[430]: time="2019-11-24T13:33:14.177138551Z" level=info msg="Download failed, retrying (3/5): local error: tls: bad record MAC"
Nov 24 13:33:25 qemuriscv dockerd[430]: time="2019-11-24T13:33:25.986011763Z" level=info msg="Download failed, retrying 
...
```

**Steps to reproduce the issue:**
1. Fetch Qemu Virtual machine from https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/debian-riscv64-20181123.tar.bz2
2. Unpack the VM and run with `run_debian.sh` script.
3. Download Docker for Risc-V built from `master` on 22/11/2019 in the VM from https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/docker-19.03.5-dev_riscv64.deb
4. Install Docker with `sudo apt install ./docker-19.03.5-dev_riscv64.deb`
5. Try pulling a Docker image like `docker pull carlosedp/faas-gateway:riscv64`
6. Check journal with `sudo journalctl -xef -u docker` for error messages.

**Describe the results you received:**

Docker keeps printing `local error: tls: bad record MAC` and retrying some layers until eventually pulling the image.

**Describe the results you expected:**

Image get pulled with no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

I also tried disabling all checksumming from eth0 in the VM (as I experienced similar problems on ARM before) but no behavior change:

```
❯ sudo ethtool --offload eth0 rx off tx off
sudo ethtool -K eth0 rx off tx off
sudo ethtool -K eth0 gso off
sudo ethtool -K eth0 gro off
sudo ethtool -K eth0 tso off
Cannot change rx-checksumming
Cannot change tx-checksumming
Cannot change rx-checksumming
Cannot change tx-checksumming
Cannot change tcp-segmentation-offload
                                                                                                                                                       
❯ sudo ethtool -k eth0
Features for eth0:
rx-checksumming: off [fixed]
tx-checksumming: off
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: off [fixed]
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]
scatter-gather: off
	tx-scatter-gather: off [fixed]
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
	tx-tcp-segmentation: off [fixed]
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off [fixed]
	tx-tcp6-segmentation: off [fixed]
udp-fragmentation-offload: off
generic-segmentation-offload: off
generic-receive-offload: off
large-receive-offload: off
rx-vlan-offload: off [fixed]
tx-vlan-offload: off [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on [fixed]
rx-vlan-filter: on [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]
```

**Output of `docker version`:**

```
❯ docker version
Client:
 Version:           unknown-version
 API version:       1.40
 Go version:        devel +1c193b20a6 in the future
 Git commit:        016a3232
 Built:             Fri Nov 22 16:22:26 2019
 OS/Arch:           linux/riscv64
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       devel +1c193b20a6 in the future
  Git commit:       d1d5f64766-unsupported
  Built:            Fri Nov 22 18:12:30 2019
  OS/Arch:          linux/riscv64
  Experimental:     false
 containerd:
  Version:          v1.3.1
  GitCommit:        c7a4f874b3267c499484aae602d1257b12d69e40
 docker-init:
  Version:          0.18.0
  GitCommit:        3c53686
```

**Output of `docker info`:**

```
❯ docker info
Client:
 Debug Mode: false

Server:
 Containers: 28
  Running: 7
  Paused: 0
  Stopped: 21
 Images: 13
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: xnmja6254jyia6kahqri8cune
  Is Manager: true
  ClusterID: z5l4k24sfd7z92uygtl1vcgma
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.2.15
  Manager Addresses:
   10.0.2.15:2377
 Runtimes: crun runc
 Default Runtime: crun
 Init Binary: docker-init
 containerd version: c7a4f874b3267c499484aae602d1257b12d69e40
 runc version: N/A
 init version: 3c53686 (expected: fec3683)
 Kernel Version: 5.3.0-rc4-g6c2a8bd-dirty
 Operating System: Debian GNU/Linux bullseye/sid
 OSType: linux
 Architecture: riscv64
 CPUs: 6
 Total Memory: 3.856GiB
 Name: qemuriscv
 ID: LWAK:QM3O:5VSI:VHOX:YBL5:3N6T:KOVA:IX5U:PR2A:77EG:K3VU:J6YK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Qemu Virtual Machine running Debian RootFS and Kernel 5.3-rc4.

I'm using crun (https://github.com/giuseppe/crun) as runtime since Runc depends on CGO which is not available on Risc-V.

My Kernel is built with this config: https://gist.github.com/carlosedp/4100815296675d126334f8f6afba4e93

Similar error to https://github.com/moby/moby/issues/38746.

**Comment by thaJeztah** [comment]
@justincormack @tiborvass @tonistiigi ptal

**Comment by jboero** [comment]
Hi I know this has been a while but I found the same issue on S390x.  The workaround for us was the flag `-cpu qemu,vx=off`

https://bugs.launchpad.net/qemu/+bug/1847232

Does that help?

**Comment by ivan-w** [comment]
I think the current implementation has fixed the issue. But I will need to retry with the latest

**Comment by davidhildenbrand** [comment]
> Hi I know this has been a while but I found the same issue on S390x. The workaround for us was the flag `-cpu qemu,vx=off`
> 
> https://bugs.launchpad.net/qemu/+bug/1847232
> 
> Does that help @carlosedp ? I think some issue with hardware native vx processing and endian issues...

AFAIKs, this is running debian-riscv64 via qemuriscv on $UNKNOWNARCH. It's not related to s390x cpu models (and therefore vx) in any way. Would only be applicable when running s390x guests via qemu-s390x.

**Comment by carlosedp** [comment]
@jboero unfortunately, `qemu-system-riscv64` doesn't support the `-cpu qemu,vx=off` flag:

```
qemu-system-riscv64: unable to find CPU model 'qemu'
```

@ivan-w when you mean "current implementation", you mean current Qemu or current Docker?

**Comment by palmer-dabbelt** [comment]
All those CPU flags are architecture specific.  Looks like "vx=off" turns off vector instructions on s390x, and I guess the theory there is that there was some bug floating around in the vector stuff either in Go or QEMU on s390x that this worked around.  None of that is relevant for RISC-V.

Unfortunately I don't have any theories as to what the bug would be on RISC-V, though.  My first approach here is usually to try and run on hardware, if it doesn't manifest over there then it's probably a QEMU bug.

**Comment by carlosedp** [comment]
It doesn't happen on the Unleashed board. Been using Docker for a while and never saw this. I think it might be related to Qemu.

There was a bug that printed this exactly message a some time ago on ARM64 where on some SOCs (RK3399 and RK3328) I had to disable hardware checksumming to avoid this.

In the end the root cause was found and I submitted a kernel patch (https://lore.kernel.org/patchwork/patch/1196336/).

**Comment by palmer-dabbelt** [comment]
OK, smells like a QEMU bug, then.  Can someone put together a rootfs that reproduces the issue so we can give it a look?

**Comment by palmer-dabbelt** [comment]
Oh, also: at least on my machine the QEMU packaged in Debian (Google's Debian, so IDK how that relates to the real stuff) is really old and loaded with known RISC-V bugs.  Trying this with the latest upstream master is the first thing I'd do.

````
$ qemu-system-riscv64 --version
QEMU emulator version 4.1.1 (Debian 1:4.1-3+build3)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
````

**Comment by carlosedp** [comment]
@palmer-dabbelt, there you go: https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/debian-riscv64-202002.tar.gz

On my Mac, I'm using Qemu 4.1.1 where this happens. I haven't tried with 4.2 since it has the FP bug preventing ssh.

**Comment by alistair23** [comment]
Can you try the latest master?

**Comment by carlosedp** [comment]
@alistair23 same happens:

```
❯ qemu-system-riscv64 --version
QEMU emulator version 4.2.50 (v4.2.0-2371-g61c265f066-dirty)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

```
root@debian10-riscv64:~# docker pull carlosedp/faas-gateway:riscv64
riscv64: Pulling from carlosedp/faas-gateway
84fbab6479a3: Downloading [=============================>                     ]  26.45MB/44.84MB
25366c1220fb: Downloading [===================>                               ]  27.87MB/70.39MB
370ca0db2924: Retrying in 10 seconds
5def8dd145ab: Waiting
27aedcccc490: Waiting
de41a27bb7bc: Waiting

# Logs:

Mar 14 13:45:13 debian10-riscv64 dockerd[2007]: time="2020-03-14T13:45:13.637553204Z" level=info msg="Download failed, retrying (1/5): local error: tls: bad record MAC"
Mar 14 13:45:20 debian10-riscv64 dockerd[2007]: time="2020-03-14T13:45:20.677336559Z" level=info msg="Download failed, retrying (2/5): local error: tls: bad record MAC"
```

**Comment by alistair23** [comment]
Thanks for trying that. I'll try to get some time to look into this.

Just to confirm, this isn't a regression right? As in it has never worked?

**Comment by carlosedp** [comment]
I never saw it working properly... but haven't used in Qemu versions older than 4.1.

**Comment by jboero** [comment]
Interesting it was worth a shot anyway. I had a theory this was caused by hardware emulation on mixed endian platforms but I see RISC-V is little endian anyway?

**Comment by jboero** [comment]
Also looks like RISC-V isn't yet hardware accelerated according to https://wiki.qemu.org/Documentation/Platforms

**Comment by alistair23** [comment]
I can't download your rootFS and I don't have a distro with Docker support.

Can you re-share the rootFS and command line args?

**Comment by carlosedp** [comment]
Sorry Alistair, wrong link.
Here is the correct one: https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/debian-riscv64-QemuVM-202002.tar.gz

**Comment by alistair23** [comment]
Thanks, what is the login password?

**Comment by carlosedp** [comment]
Ops, it's user is `root`, password is `riscv`.

**Comment by alistair23** [comment]
Thanks, it looks like Docker isn't installed and I can't download the deb in the issue. Is there another deb?

**Comment by carlosedp** [comment]
You can grab a tarball: https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/docker-19.03.8-dev_riscv64.tar.gz

Just unpack and move files/dirs to `/`.

**Comment by alistair23** [comment]
Great. I can pull the image as in your issue.

I don't see any errors though. I can correctly pull the Docker image

**Comment by alistair23** [comment]
Nothing in the log either.

```
riscv64: Pulling from carlosedp/faas-gateway
84fbab6479a3: Pull complete 
25366c1220fb: Pull complete 
370ca0db2924: Pull complete 
5def8dd145ab: Pull complete 
27aedcccc490: Pull complete 
de41a27bb7bc: Pull complete 
Digest: sha256:1e9b9d4575932cb12a6fc315058ef0139dce38d26a5cef3992e9555928a13e0c
Status: Downloaded newer image for carlosedp/faas-gateway:riscv64
docker.io/carlosedp/faas-gateway:riscv64
root@debian10-riscv64:~# journalctl -xe --no-tail -u docker | cat
journalctl -xe --no-tail -u docker | cat
-- Logs begin at Fri 2019-11-29 16:32:38 UTC, end at Wed 2020-03-18 19:07:15 UTC. --
-- No entries --
root@debian10-riscv64:~# .
```

This is what I'm running

```shell
apt update
apt install wget
wget https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/docker-19.03.8-dev_riscv64.tar.gz
tar -xvf docker-19.03.8-dev_riscv64.tar.gz
dockerd &
docker rm -vf $(docker ps -a -q) # To make sure it downloads again
docker rmi -f $(docker images -a -q) # To make sure it downloads again
docker pull carlosedp/faas-gateway:riscv64
journalctl -xe --no-tail -u docker | cat
```

I added a test case to keep testing this for new patches/PRs as well

**Comment by carlosedp** [comment]
Maybe it's something related to Qemu on MacOS hosts?
I've installed Qemu with homebrew from master branch with `brew install --HEAD qemu -s --verbose`.

**Comment by alistair23** [comment]
That's probably it

I'm not sure what homebrew is.

It sounds like an issue with either QEMU on OS X or how QEMU is packaged/installed for OS X.

Start by building QEMU master from source and see if that helps. Otherwise it's some OS X related issue. Unfortunately I can't really help with that.

**Comment by tonistiigi** [comment]
I'm not sure if this is related but I saw something that matches this description a couple of months ago. It was really mysterious, I did some debugging but didn't really get to anything useful.

To me, it was not risc-v related, just qemu with user-net on a mac. I saw some net corruption from processes like git and docker. When I tried to trace what was going on it seemed that sometimes a packet was missing the last byte. Sounds unbelievable but not making this up. I could even repro it with `nc` in a very basic linux vm in the end iirc.  When I traced the network traffic with qemu or tcpdump the missing byte was there. But it was not after syscall returned, or even in the strace/bpftrace output. I tried different versions of qemu as well. And I believe even different machines (cc @tiborvass)

**Comment by tiborvass** [comment]
I confirm that I've seen the same ghost and it was scary. We had just updated OSX prior, but I managed to repro on High Sierra and confirmed the culprit wasn't the OSX upgrade. Could be a hard to find timing issue too as it wasn't 100% reproducible, but more reproducible with higher latency.

**Comment by tiborvass** [comment]
The hardest part to grok was that everything else seemed to work fine otherwise (apt-get install, https), it was just git cloning that had this issue (sometimes) but it ended up not being git-related.

**Comment by apatrushev** [comment]
I got the same issue and did not find a way to fix it.
The interesting part is that my environment is x86-only.
## Host
```
MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)
2,4 GHz Dual-Core Intel Core i7
macOS Catalina, 10.15.4 (19E266)
```
```
$ qemu-system-x86_64 --version
QEMU emulator version 4.2.0
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```
```
$ qemu-system-x86_64 -nographic \
-accel hvf \
-monitor stdio \
-serial unix:/var/folders/1l/2b3ftgz14rz03cljyjnc3qlr0000gn/T/tmp8jthv4ju/monitor \
-drive file=sys.qcow2,if=virtio \
-drive file=docker.qcow2,if=virtio \
-device e1000,netdev=net0 \
-netdev user,id=net0,hostfwd=tcp::10022-:22
```
 ## Guest
```
docker:~# cat /etc/alpine-release
3.11.5
docker:~# uname -a
Linux docker 5.4.27-0-virt #1-Alpine SMP Mon, 23 Mar 2020 18:15:20 UTC x86_64 Linux
docker:~# docker --version
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bb
```
## Symptoms and actions
Everything works fine besides docker pull.
```
Download failed, retrying: local error: tls: bad record MAC
```
I tried to switch off offloading without success.
Ready to help with any additional information, images and so on.
