### ISSUE TITLE
Docker Daemon Stuck activating

### ISSUE THREAD

**Issue by harshanarayana** [moby/moby#40244]
**Description**

On an Ubuntu 16.04LTS machine running `5.2.21-050221-generic` of the kernel and `18.09.9` of docker, the dockerd systemd service gets stuck in `activating`/ `deactivating` state forever. 

**Steps to reproduce the issue:**
1. Take an ubuntu 16.04 machine and upgrade the kernel to `5.2.21-050221-generic`
2. Install docker-ce `18.09.9`
3. Start docker daemon and perform kubernetes control plane init via `kubeadm init`
4. After a while when the daemon restarts for any reason, it gets stuck in `activating` state forever. 

**Describe the results you received:**
```bash
* docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-start.conf
   Active: deactivating (stop-sigterm) since Sat 2019-11-23 19:40:02 UTC; 1 day 16h ago
     Docs: https://docs.docker.com
 Main PID: 6901 (dockerd)
   CGroup: /system.slice/docker.service
           `-6901 /usr/bin/dockerd -g /data/docker --max-concurrent-uploads 100 --icc=false --log-level=info --iptables=true --userland-proxy=false -H fd:// --containerd=/run/containerd/containerd.sock --bip=169.254.0.1/24 --log-opt=max-size=50m --log-opt=max-file=3 --liv

Nov 23 19:40:02 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T19:40:02.888086999Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 19:40:02 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T19:40:02.888104110Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Nov 23 19:40:02 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T19:40:02.888120558Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Nov 23 19:40:02 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T19:40:02.889104651Z" level=info msg="Loading containers: start."
Nov 23 20:09:15 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T20:09:15.450226652Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Nov 23 20:09:15 tardis-master-2.2.2.2 dockerd[6901]: time="2019-11-23T20:09:15.450724572Z" level=warning msg="2124a35a7413184db147ddb6501df278ef7c327f4ceff338abc1ac44211ca3fd cleanup: failed to unmount IPC: umount /data/docker/containers/2124a35a7413184db147ddb6501d
```

**Describe the results you expected:**
docker daemon to be restarted/stopped/started successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
1. Linux Kernel Details
```bash
5.2.21-050221-generic #201910111731 SMP Fri Oct 11 17:34:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
**Output of `docker version`:**

```bash
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 17:24:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**
```bash
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
1. VM Details
32 Core VM running on ESXi
```bash
processor       : 31
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Platinum 8176 CPU @ 2.10GHz
stepping        : 4
microcode       : 0x2000043
cpu MHz         : 2100.000
cache size      : 39424 KB
physical id     : 62
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 62
initial apicid  : 62
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx hypervisor lahf_lm 3dnowprefetch pti arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 4200.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
```
**containerd**
```bash
* containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-11-23 19:27:20 UTC; 1 day 16h ago
     Docs: https://containerd.io
 Main PID: 1319 (containerd)
   CGroup: /system.slice/containerd.service
           |- 1319 /usr/bin/containerd
           |- 3408 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/dd7473a706891ae88a06b00ac6162ae103a3bf765471d0c0aacb2a5c81fecd5d -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
           |- 3660 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/eafb6d6963ee8d676aa7954afd4e3b41d0d22f1bcf9603a8e1031cf298eec664 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
           |- 3773 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/a3d86ebd138317a59133e2293f5412d872d5072fec6ba1476dbdb5540873d2ac -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
```
**Stack Dump**
https://gist.github.com/harshanarayana/e31486f35144ae08c7861e0bea612bc4

**Systemd service definition**
```bash
# /lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

StartLimitBurst=3

StartLimitInterval=60s

LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

TasksMax=infinity

Delegate=yes

KillMode=process

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/start.conf
[Service]
EnvironmentFile=/etc/tardis/docker.env
ExecStart=
ExecStart=/usr/bin/dockerd -g ${DOCKER_DATA_DIR} --max-concurrent-uploads 100 --icc=false --log-level=info --iptables=true --userland-proxy=false -H fd:// --containerd=/run/containerd/containerd.sock --bip=169.254.0.1/24 ${DOCKER_MAX_LOG_SIZE} ${DOCKER_MAX_LOG_FILES} ${DOCKER_OPTS}
RestartSec=10
```
```bash
# Contents of /etc/tardis/docker.env
DOCKER_DATA_DIR=/data/docker
DOCKER_MAX_LOG_SIZE="--log-opt=max-size=50m"
DOCKER_MAX_LOG_FILES="--log-opt=max-file=3"
DOCKER_OPTS="--live-restore"
```
**containerd version**
```bash
containerd -v
containerd containerd.io 1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```

**Comment by thaJeztah** [comment]
the problem only occurs after running `kubeadm init` ? (wondering if running containers works ok before k8s is up). Is there anything in the docker daemon logs that could give some information?

**Comment by harshanarayana** [comment]
@thaJeztah I found it while doing `kubeadm init`. But the issues till persists after `kubeadm reset`. The `systemctl stop|restart` of the `docker.service` pushes it into `deactivating/activating` state. 

Only thing that helps me with successfuly docker service start via the systemd is the following
```bash
while true; do
    kill -9 $(pidof containerd) $(pidof dockerd)
    if [[ "$?" = "0" ]]; then
        break
    fi
done

systemctl start docker.service
```

**Comment by harshanarayana** [comment]
> Is there anything in the docker daemon logs that could give some information?

I enabled the docker `--debug` mode and it doesnt' have anything majorly useful that can indicate why it failed. But if you need me to enable some additional things and get the log to help RCA the issue, I can do so. I have a gist of the stack dump attached above

**Comment by harshanarayana** [comment]
@thaJeztah 

```bash
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.452931960Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/fc22087cb87701b178afc3d26fe77b046ace74e5270bf21559b7d73d2597416b/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.456610989Z" level=debug msg="restored container" alive=true container=008320c6e3120d9d3af06576dd5810376ed9e7b2eac4a04228ff073f1177fe77 module=libcontainerd namespace=moby pid=7523
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.456710248Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/e0639316f598a544b8c4d53913563bf1e51ee70631ee276b3f6eb21eada03024/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.457760277Z" level=debug msg="restored container" alive=true container=1cdf2bb532d8c9df25e1f9e6fdaad1d1662266f046d462ff5117e7cfca09f16d module=libcontainerd namespace=moby pid=3162
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.457837809Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/b0a81d79ad5af6977ba45afa51bc3240ed9544a6e97af815bfcce72be5b874e3/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.460265987Z" level=debug msg="restored container" alive=true container=b063c06bdb970269497cdf845cfa95b59a80bdd2efb7e673979ae6f595cacb22 module=libcontainerd namespace=moby pid=8782
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.460340079Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/24a47cbe556e5c63bac442c8faef43923e1ba5362fe196c59c3e9a901e4c2bed/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.468637966Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/d87861583dd8586d751f1be9c687e826a74b8b9fcc3fc86e0579888dd68013f3/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.468702237Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/810c7a491cbaf24adac46934674d83052858fde806357475bd15ede1c9b75967/merged 0x56142e4ca040 0x56142e4ca040}"
Nov 27 08:37:43 tardis-master-2-2-2-2 dockerd[3582]: time="2019-11-27T08:37:43.468812070Z" level=debug msg="container mounted via layerStore: &{/data/docker/overlay2/5bf443738d4d5672baa105c99625ed654f8d11d79e87028166122dbc164330bc/merged 0x56142e4ca040 0x56142e4ca040}"
```
Here is where things seem to get stuck in the docker daemon.

**Comment by harshanarayana** [comment]
@thaJeztah  Any suggestions on this? I am having this same problem while running 19.03.5 as well

**Comment by conz27** [comment]
Experiencing a same issue on 19.03.5 as described by original reporter.

**Comment by thaJeztah** [comment]
The output in the first comment is quite generic (unfortunately, output of systemd status is generally not very informative as it rarely shows the _actual_ status).


Looking at the additional details (sorry, looks like I missed some since my earlier comment);


- the `connection refused ...` errors seem to indicate that the `dockerd` daemon is not able to connect with `containerd`, which could indicate that containerd is not running / has issues
- I now notice that `--live-restore` is used; note that this option can be useful when installing minor updates (e.g. updating `docker 19.03.1` to `docker 19.03.2`) but is _not_ compatible with "major" updates (e.g. updating `docker 18.09` to `docker 19.03`)
- we did have a report at some point where updating containerd.io caused issues with docker failing to re-connect to existing containers due to a packaging issue resulting in the `postinstall` script not to run (causing `containerd` service not being restarted after updating); restarting both the `dockerd` and `containerd` service after updating solved that situation.

No direct other ideas at this point, but be sure to check system-, dockerd and containerd logs to see if there's anything useful in that that could provide more details

**Comment by toshiro92** [comment]
Having the same issue with `Ubuntu 18.04.4` and `Docker 20.10.1`

**Comment by astanwar99** [comment]
Having same issue on `ArchLinux` with `Docker 20.10.14`

**Comment by levimatheri** [comment]
Having exact same issue in `Windows Server 2019` with `Mirantis 20.10.9`> @harshanarayana have you had any luck?

**Comment by harshanarayana** [comment]
@levimatheri We eventually moved to using CRI Native way with `containerd` only infra and removed `docker`. This took us a while to get in place. Until we did that, we had a hacked up script that runs the remediation workflow which did the following

1. Check the Docker Daemon State
2. Check the ContainerD Daemon State
3. If they are stuck in Activating state, do a few cleanup
4. Restart the dockerd + contrainerd forcefully with `SIGKILL` ( I know this is a terrible thing!) [Do this in a loop no less ;)]

**Comment by thaJeztah** [comment]
> Having exact same issue in `Windows Server 2019` with `Mirantis 20.10.9`

@levimatheri is that when running the native Windows daemon, or a Linux daemon inside WSL2? (ISTR systemd is not supported on WSL2, so if you're trying to run it as a systemd service, that may be related)

**Comment by levimatheri** [comment]
@thaJeztah it's running native windows daemon. This is in Azure running service Fabric.

**Comment by thaJeztah** [comment]
@levimatheri hm, I don't see how that situation relates to the original report here, which was running on Linux, using systemd. The native Windows daemon is a completely different binary and operating system.

**Comment by aMohammadEmami** [comment]
Having the same issue on `Debian 10` and `Docker 20.10.9`

**Comment by thaJeztah** [comment]
docker 20.10.9 is quite an old patch release of the 20.10 release (with some known vulnerabilities); I'd highly recommend updating to the current patch release (20.10.21 at time of writing). Also note that Debian 10 "buster" reached end of mainstream support (some maintenance is done by the LTS project, but generally, Debian 11 would be recommended).

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
