### ISSUE TITLE
There are old running containers, the network config will not take affect

### ISSUE THREAD

**Issue by jxhsjxhs** [moby/moby#40272]
OS: CentOS Linux release 7.7.1908 (Core)
Docker version 19.03.5, build 633a0ea

bash
kill -9 `ps -ef |grep dockerd |grep -v grep | awk {'print $2'}`

Nov 29 13:52:53 awlkejfawejfklaierhgaklefianef systemd: docker.service: main process exited, code=killed, status=9/KILL
Nov 29 13:52:53 awlkejfawejfklaierhgaklefianef systemd: Unit docker.service entered failed state.
Nov 29 13:52:53 awlkejfawejfklaierhgaklefianef systemd: docker.service failed.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: docker.service holdoff time over, scheduling restart.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Stopped Docker Application Container Engine.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Closed Docker Socket for the API.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Stopping Docker Socket for the API.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Starting Docker Socket for the API.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Listening on Docker Socket for the API.
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef systemd: Starting Docker Application Container Engine...
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.888403991+08:00" level=info msg="Starting up"
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.889710777+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.889736546+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.889771971+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.889789915+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.892692766+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.892716762+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.892739618+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.892749098+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.900778577+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Nov 29 13:52:55 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:55.928328360+08:00" level=info msg="Loading containers: start."
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:56.100501387+08:00" level=info msg="There are old running containers, the network config will not take affect"
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:56.158083978+08:00" level=info msg="Loading containers: done."
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:56.178681890+08:00" level=info msg="Docker daemon" commit=633a0ea graphdriver(s)=overlay2 version=19.03.5
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:56.178759661+08:00" level=info msg="Daemon has completed initialization"
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef dockerd: time="2019-11-29T13:52:56.193311871+08:00" level=info msg="API listen on /var/run/docker.sock"
Nov 29 13:52:56 awlkejfawejfklaierhgaklefianef systemd: Started Docker Application Container Engine.

**Comment by thaJeztah** [comment]
Could you provide a bit more details as to the problem you're running into, what you expected to happen instead, and how to reproduce?

**Comment by thaJeztah** [comment]
closing as there's not enough information for this to be actionable
