### ISSUE TITLE
Feature request: nested docker containers

### ISSUE THREAD

**Issue by sixcorners** [moby/moby#40278]
**Description**
I want to run docker containers from my docker container.

**Steps to reproduce the issue:**
1. docker run --rm -it ubuntu

**Describe the results you received:**
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Describe the results you expected:**
root@3dbf6ab74920:/# 

**Additional information you deem important (e.g. issue happens only occasionally):**
Bind mounting allows this to work but doing this allows the container to see everything else on the host. It would be nice if the socket file exposed to each container gave it its own namespace to do stuff in.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 60
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: H6C2:PB4V:SXZZ:W5GP:4FXI:AHU4:5ET3:X7VT:XHGP:T4MQ:P3DH:RCOU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 52
  System Time: 2019-12-02T19:16:35.073023783Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac

**Comment by AkihiroSuda** [comment]
Here it is: https://hub.docker.com/_/docker

**Comment by sixcorners** [comment]
Isn't that not recommended and don't you have to run it as a privileged container?
What I'm proposing is that the container get a namespaced socket file that is served by the dockerd running outside the container but also doesn't give any access to things outside the container.
Does that seem like a good idea?

**Comment by thaJeztah** [comment]
Giving the container access to the dockerd API would still give full access (e.g. it could start a container that bind-mounts the host's disk and modify everything) unless you have something in place for (role base) access control to the docker API.

If this is for multi-tenancy, possibly running multiple rootless daemons (one per  user) could work

**Comment by sixcorners** [comment]
Would it be a good idea to build in namespaces and access control into docker?

**Comment by AkihiroSuda** [comment]
Kubernetes PSP might be what you want.

**Comment by sixcorners** [comment]
hmm. I'll check that out.
That multiple rootless daemons seems interesting too.
What does rootless mean? Does it mean running dockerd as a non root user?

**Comment by AkihiroSuda** [comment]
> What does rootless mean? Does it mean running dockerd as a non root user

yes

**Comment by thaJeztah** [comment]
> Would it be a good idea to build in namespaces and access control into docker?

namespaces may come when the containerd integration is completed. access control is out of scope for this project currently.
