### ISSUE TITLE
[Windows] How to restrict the overall memory/CPU limit for a set of containers

### ISSUE THREAD

**Issue by arjun024** [moby/moby#40288]
**Description**

We are trying to apply an overall limit for memory/CPU that a set of containers can use. This is very useful when we have a main container running the main workload, and 1 or more sidecar containers (proxy, health-check etc).

On linux, this could be done by creating a cgroup and applying that cgroup to each container using `--cgroup-parent`.
E.g.
```
docker run -it --rm -d --name main --cgroup-parent=/cgroup-limit/ ubuntu bash
docker run -it --rm -d --name side --cgroup-parent=/cgroup-limit/ ubuntu bash
```
On windows, we are able to share the network stack using `--network: container:<container>` as follows:
```
docker run -d --name main mcr.microsoft.com/windowsservercore-insider:latest powershell
docker run -d --name side --network container:main mcr.microsoft.com/windowsservercore-insider:lastest powershell
```
Similar to the network stack, is there a way in windows to share resource limits?

cc @Cara-Sciorilli

**Comment by thaJeztah** [comment]
I don't think there is, but perhaps @StefanScherer or @simonferquel would know 🤔

**Comment by StefanScherer** [comment]
A few resource controls are implemented for Windows containers:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/resource-controls

**Comment by arjun024** [comment]
@StefanScherer We know how to set **independent** resource limits on a per-container basis like in the article you provided. We are trying to set an overall limit for a group of containers (or a "pod" if you will).
