### ISSUE TITLE
Azure dockerd 100% CPU usage issue

### ISSUE THREAD

**Issue by ntotura** [moby/moby#40285]
Using Docker server version 18.09.9. Azure hosted multiple CPU VM, over time dockerd CPU usage spikes to 100% of multiple CPUs. 

I have captured a stack trace and CPU profile, and it indicates that most time is spent in readLogs.

How do I debug this further? Is there a way to see who is using the docker APIs to perform the log reads? 

I have tried disabling the Azure agents, and it did not seem to make a difference. We also use Data Dog and disabling also didn't seem to make a difference.

Possibly related to https://github.com/moby/moby/issues/34393, but any code fixes I would expect to see in this version of the server. 

Output of top: 
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                       
  1615 root      20   0 2000796 374908  36972 S 287.2  1.1   5210:54 dockerd                                                                                                                       
102408 root      20   0 11.481g 830272  24792 S  22.1  2.5 366:16.61 java                                                                                                                          
  3776 root      20   0 1323592 243916  88184 S  20.9  0.7   1995:47 kubelet      
```

**Steps to reproduce the issue:**
1. Run multiple Docker containers via Kubernetes on Azure hosted VMs 
2. Overtime, notice that the dockerd process on some worker VMs will spike to 100% CPU usage

**Describe the results you received:**
Stack trace and CPU profile, with default 30 seconds capture time below.
[dockerd.prof.hprof.zip](https://github.com/moby/moby/files/3923757/dockerd.prof.hprof.zip)
[goroutine-stacks-2019-11-24T044101Z.log.zip](https://github.com/moby/moby/files/3923758/goroutine-stacks-2019-11-24T044101Z.log.zip)

**Describe the results you expected:**
I don't expect dockerd CPU usage to spike to 300% of total CPU available

**Additional information you deem important (e.g. issue happens only occasionally):**
Stack trace and CPU profile attached

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 131
  Running: 105
  Paused: 0
  Stopped: 26
 Images: 218
 Server Version: 18.09.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1063-azure
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.39GiB
 Name: developmentv3-k8s-worker-1
 ID: LL45:EI2I:4YCS:6MIB:BV65:HDYQ:KQ2I:B7UI:RHKG:REPU:K6XM:QFTL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure, Standard E4s v3 (4 vcpus, 32 GiB memory), Rancher Kubernetes

**Comment by cpuguy83** [comment]
@ntotura It looks like you have a bunch of things reading container logs and that's consuming CPU. If you have a container outputing a lot this could really eat up lots of CPU. I would suggest to try throttling your readers so they don't consume so quickly and see if that brings the load down.

It is entirely possible there is a bug in the read logic causing a CPU spin, but the CPU profile is pretty deep in the json decoding stack it seems less likely.

**Comment by ntotura** [comment]
Thank you for replying, yes, that was the issue. It was in fact DataDog related, and switching the way DataDog collects logs to file based instead of using the docker socket did resolve the issue. Flag set was DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE.  

I never did find a way to view which processes were using the docker socket, that would have been helpful to identify the issue faster.
