### ISSUE TITLE
Non-experimental manifest images

### ISSUE THREAD

**Issue by avikivity** [moby/moby#40281]
Manifest (mulitarch) images are currently documented as experimental. We would like to use them in production.

Are there plans to make image manifests ready for production?

**Comment by thaJeztah** [comment]
Multi-arch images themselves are not experimental, but the `docker manifest` subcommand is marked experimental, mainly because the UX has not been frozen.

Most of the official images are already multi-arch (e.g. https://hub.docker.com/_/golang?tab=tags)

**Comment by avikivity** [comment]
Thanks for the clarification. Closing.
