### ISSUE TITLE
images gone

### ISSUE THREAD

**Issue by dustingooding** [moby/moby#40301]
**Description**

Running a recent version of Docker on Ubuntu 16.04 and 18.04. Occasionally I see all Docker images just disappear.  This usually happens on boot, and a restart of the Docker service "finds" them again (like nothing ever happened). The service restart doesn't always work though.

**Steps to reproduce the issue:**
1. Have one or more docker images pulled.
2. Reboot the machine.
3. Run `docker images` and see all images are gone.
4. Run `sudo systemctl restart docker`.
5. Run `docker images` and see images are listed.

**Describe the results you received:**

Docker images that I _know_ are present are not listed.

**Describe the results you expected:**

Docker images that I _know_ are present _are_ listed.

**Additional information you deem important (e.g. issue happens only occasionally):**

This problem doesn't always happen.  And the service restart doesn't always restore the images.

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-58-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.31GiB
 Name: operator
 ID: B4AR:6HVV:4NAV:DWRN:NZ72:AZ3A:GS4D:JCXS:WJAV:S5QC:GVUE:LQWX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  private_ip_address:5000
  private_hostname:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I've seen this on Ubuntu 16.04 and 18.04.

Ubuntu 16.04:

```
$ uname -a
Linux myhostname1604 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Ubuntu 18.04:

```
$ uname -a
Linux myhostname1804 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
Is the docker storage location (`/var/lib/docker`) on a separate disk perhaps? In that case, could it be a race condition where that disk is not yet mounted after reboot?

**Comment by dustingooding** [comment]
No, these are single disk systems.

**Comment by thaJeztah** [comment]
hm.. odd. no clue at this point; anything in the logs when this happens?

**Comment by thaJeztah** [comment]
closing this issue as there's currently not enough details to reproduce and to investigate, but happy to reopen if more details become available
