### ISSUE TITLE
Why Docker Still doesn't support add device to a running container?

### ISSUE THREAD

**Issue by pokerfaceSad** [moby/moby#40316]
### Question: Why Docker Still doesn't support add device to a running container?
I find this pull request [#8826](https://github.com/moby/moby/pull/8826) been asked 5 years ago.
Why it wasn't been merged ?
For what reason？
I'm confused cause I think it's a good feature.

**Comment by AkihiroSuda** [comment]
CLI spec seems the reason: https://github.com/moby/moby/pull/8826#issuecomment-82407010

The CLI was removed from this repo since then, so please feel free to submit PR for daemon-side code.

**Comment by pokerfaceSad** [comment]
> CLI spec seems the reason: [#8826 (comment)](https://github.com/moby/moby/pull/8826#issuecomment-82407010)
> 
> The CLI was removed from this repo since then, so please feel free to submit PR for daemon-side code.

Thanks for your reply.
In addition, I wanna if the feature of "add device to a running container" will lead to some Inevitable risks.
As far as I know, If we wanna add a device to a running container , we need to change the Deivce CGroup which the running container belongs to. If this device need some driver files, we also need to operate the Mount Namespace. 
So whether the operation to CGroup and Namespace will lead some risks？
Maybe security risk, break Isolation risk or some side I don't know? 😰
