### ISSUE TITLE
Windows 1909 containers starting issues on Docker 19.03.5

### ISSUE THREAD

**Issue by ghost** [moby/moby#40320]
**Description**
We are running .NET Windows containers which we recently updated to use Windows 1909. Up to monday the containers were starting fine on AWS ECS using AWS AMI with 19.03.4. AWS published December ECS optimized AMIs with Docker 19.03.5. At that point the docker container wouldn't start (it would timeout). Error messages below. After reverting the AMI back to 19.03.4 the containers again start ok.
I cannot easily check another versions of windows.

**Steps to reproduce the issue:**
1. Run .NET runtime 1909 container on docker 19.03.5
2. Check if the container is starting correctly

**Describe the results you received:**
```
"11","EC2AMAZ-XXXXXX","System.Byte[]","848","(0)","0","Warning","Syscall did not complete within operation timeout. This may indicate a platform issue. If it appears to be making no fo
rward progress, obtain the stacks and see if there is a syscall stuck in the platform API for a significant length of time. [cid=88f33b444ddf065ea4868ab0a7d57ecf992d4feca7e7ef2b3604b853
1a00645b timeout=4m0s]","docker","System.String[]","11","12/19/2019 10:58:55 AM","12/19/2019 10:58:55 AM",,,
```

**Describe the results you expected:**
Containers running after image pull and container start.

**Additional information you deem important (e.g. issue happens only occasionally):**
First time on fresh instance ECS reported this:
`DockerTimeoutError: Could not transition to started; timed out after waiting 8m0s`
After the first timeout, the container was not properly deleted, port was occupied and I had many containers fail with:
`CannotStartContainerError: Error response from daemon: failed to create endpoint <redacted> on network nat: hnsCall failed in Win32: The specified port already exists.`

After ~ 2 hours the containers started fine. Or also reboot of the server fixed it and container started correctly.
**Output of `docker version`:**

```
S C:\Windows\system32> docker version
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
PS C:\Windows\system32> docker info
Client:
 Debug Mode: false
 Plugins:
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-cluster.exe" is not valid: failed to fetch metadata: exit status 1

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows Server Datacenter Version 1909 (OS Build 18363.535)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4GiB
 Name: EC2AMAZ-XXXXXX
 ID: 5CKF:HL5Z:UZNU:A646:ZDOW:54EX:MZR5:D6FM:QLGA:DU4G:UWXJ:CZZS
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, AMI (us-east-1) ami-0181d918d9dc41608

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
