### ISSUE TITLE
buildkit rootless with custom ca certificate

### ISSUE THREAD

**Issue by everflux** [moby/moby#40329]
It seems there is no way to use a custom ca certificate with the moby/buildkit:rootless container image.
Related: When using insecure-registry no https will be performed at all, only http which breaks this use case as well.

**Comment by thaJeztah** [comment]
This looks related to using buildkit directly (running it as an image); probably better reported in https://github.com/moby/buildkit/issues

**Comment by AkihiroSuda** [comment]
You need to create custom image
