### ISSUE TITLE
[problem]docker rmi 

### ISSUE THREAD

**Issue by YesterdayxD** [moby/moby#40333]
Suppose that two images use same base layers, but top layers are different.
When I exec docker rmi a image, the same layers will not be deleted .
I have a problem that which file records that the layers ared used with two images?

**Comment by cpuguy83** [comment]
Layers are reference counted and are not deleted unless there are no images referencing them.

**Comment by YesterdayxD** [comment]
Thank you! Can you tell me where is the count? 

Is it in a file in /var/lib/docker? Or in memory?

And wish you happy new year!

**Comment by cpuguy83** [comment]
It's in memory, we do not provide this count.

**Comment by YesterdayxD** [comment]
Got it!
