### ISSUE TITLE
The dependency is not imported correctly (in pkg/archive/archive.go)

### ISSUE THREAD

**Issue by kubitre** [moby/moby#40338]
https://github.com/moby/moby/blob/473c5701cb66403b0535a5c01845cb0f27fbeb47/pkg/archive/archive.go#L20

**Comment by cpuguy83** [comment]
Sounds like you have an old checkout?

```termnial
docker $ git grep Sirupsen
docker $
```

**Comment by thaJeztah** [comment]
Yes, this was updated a long time ago; did you run into this problem when using `go mod` perhaps?


Closing this issue because it's fixed on master, but feel free to continue the conversation

**Comment by kubitre** [comment]
when using go mod, an exception is thrown that this dependency is incorrect. I tried to use the version from the master go get ... @ master and received a message in response that the current api in the system is less than the client

**Comment by thaJeztah** [comment]
The client can do API version negotiation, or be set to a fixed version (it'll default to the latest supported version)

**Comment by kubitre** [comment]
latest supported version on my environment it 1.40
![image](https://user-images.githubusercontent.com/32496864/72209384-06d28500-34e0-11ea-9088-1c5b236a1d11.png)
and i use latest master version i had this error: 
![image](https://user-images.githubusercontent.com/32496864/72209404-3f725e80-34e0-11ea-8a9f-c218617a499a.png)
How can i fixed it?

**Comment by kubitre** [comment]
i had any try update my docker engine to latest, but latest maximum api version had 1.40

**Comment by kubitre** [comment]
i use version from this commit: e238713cc9dade460ec961dde3f94173ca59a545 and it work for me. but it's spike

**Comment by thaJeztah** [comment]
When initializing the client you can set the API version to use, or use API version negotiation (see https://github.com/moby/moby/pull/39032 which was added not too long ago to simplify that)
