### ISSUE TITLE
Teeing Stderr to a bytes buffer is not possible if Tty: true

### ISSUE THREAD

**Issue by eine** [moby/moby#40336]
In the example below (which is based on https://docs.docker.com/develop/sdk/examples/), `io.MultiWriter` is passed to `stdcopy.StdCopy`, to tee the content that goes to `os.Stderr` to a bytes buffer. It works, as long as `Tty: false`. However, when `Tty: true`, the following error is produced: `Unrecognized input header: 115`. Moreover, if MultiWriter is NOT used, Tty can be set to true. It seems not to be possible to use both features (Tty and MultiWriter) at the same time. Am I missing anything?

```go
	resp, err := cli.ContainerCreate(
		ctx,
		&container.Config{
			Image:      img,
			Cmd:        []string{"./run"},
			WorkingDir: wrk,
			Tty: false,
		},
		&container.HostConfig{
			Binds: []string{bind},
		},
		nil,
		"",
	)
	if err != nil {
		return err
	}

	if err := cli.ContainerStart(ctx, resp.ID, types.ContainerStartOptions{}); err != nil {
		return err
	}

	exitCode := 0
	statusCh, errCh := cli.ContainerWait(ctx, resp.ID, container.WaitConditionNotRunning)
	select {
	case err := <-errCh:
		if err != nil {
			return err
		}
	case status := <-statusCh:
		fmt.Printf("status.StatusCode: %#+v\n", status.StatusCode)
		exitCode = int(status.StatusCode)
	}

	out, err := cli.ContainerLogs(ctx, resp.ID, types.ContainerLogsOptions{ShowStdout: true, ShowStderr: true})
	if err != nil {
		return err
	}
	buf := &bytes.Buffer{}
	_, err = stdcopy.StdCopy(os.Stdout, io.MultiWriter(os.Stderr, buf), out)
	if err != nil {
		return err
	}
```

**Comment by cpuguy83** [comment]
When using TTY there is no stderr, everything goes to stdout.
Additionally there is no header to different streams since there is only one stream.

**Comment by eine** [comment]
Thanks! Does that mean that I should just `io.Copy(io.MultiWriter(os.Stdout, buf), out)` (and skip `StdCopy`) as long as `Tty` is ensured to be `true`?

**Comment by cpuguy83** [comment]
Yep

**Comment by thaJeztah** [comment]
let me close this one as it doesn't look like a bug, but feel free to continue the conversation
