### ISSUE TITLE
Docker save -o image.tar image:latest not working

### ISSUE THREAD

**Issue by vinnyasa** [moby/moby#40346]
**Description**
Using Docker desktop for Windows version 2.1.0.5 (40693) channel stable with experimental features enabled on a Server 2019
I have not been able to tar any of my images when the containers are on windows mode, only if I switch to Linux can I save to a tar file.

I have to save both linux and windows images but llinux images do not save. 

**Steps to reproduce the issue:**
1. Enable experimental feautures
2. Switch to windows containers
3. Pull a linux image
4. Pull a windows image
5. save images
5a. On powershell call docker save -o linuxImage.tar linuxImage

**Describe the results you received:**
 the prompt just hangs for ever, no tar file is created

**Describe the results you expected:**
tar file created and prompt shows some sort of response

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
PS C:\> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     true

```

**Output of `docker info`:**

```
PS C:\> docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.864)
 OSType: windows
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.999GiB
 Name: WIN-CVBIS3QJSQI
 ID: 5ZXC:MCBN:6HLG:T6A3:FRIL:SMSJ:KRDF:MI7T:7U75:CEFB:NMY7:33KY
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-01-03T17:04:30.5077943-08:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Windows Server 2019

**Comment by jameshed** [comment]
I have been seeing this same issue on Windows 10.  Any siggestions?

`
Client:
 Version:           3.0.8
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        2355349d
 Built:             Wed Oct 23 17:47:59 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       adfac69
  Built:            Wed Oct 23 17:54:47 2019
  OS/Arch:          windows/amd64
  Experimental:     true
`

`
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 3.0.8
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.657)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 63.92GiB
 Name: JamesHedDev
 ID: 7GH6:KDR4:FLYH:COTD:4OZI:4Z4Z:MC4I:QSQX:CQYZ:MJEH:7X25:ELRD
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

**Comment by thaJeztah** [comment]
This is not supported on LCOW, and given that Microsoft will not continue development of LCOW, unfortunately, this won't be fixed, see https://github.com/moby/moby/issues/33850#issuecomment-591180956

> Linux Containers on Windows development moved to [ContainerD](https://github.com/containerd/containerd), and no more work is happening in the Moby codebase. I don't think we need to keep this epic open any longer since there's no progress tracked here.

If you want to run Linux Containers on a Windows machine, Docker Desktop with WSL2 may be a good alternative (https://docs.docker.com/docker-for-windows/wsl-tech-preview/)


I'm closing this ticket because of the above, but feel free to continue the conversation

**Comment by AG-LC** [comment]
@thaJeztah I use Docker with the WSL2 backend, and have the same issue as OP: `docker save -o ./image image_tag` hangs, outputs nothing, and doesn't create the required file. Is that expected? Is there any way of saving a Linux container image on Windows?

**Comment by thaJeztah** [comment]
@AG-LC I think it should work, but I'm not on Windows myself, and there could be some corner-cases. To get some more information; 

- just to double check "I use Docker with the WSL2 " - you have installed Docker Desktop, or manually installed a linux package on WSL2?
- are you using the CLI on "windows" or in WSL2? 
- does the problem go away if you disabled the "Enable cloud experience" option in the Docker Desktop preferences (under "Experimental Features")?
