### ISSUE TITLE
Docker (overlay2) mounts not being unmounted when stopping docker

### ISSUE THREAD

**Issue by mindrunner** [moby/moby#40344]
Description:
Running a server with multiple docker containers deployed by docker-compose. After some days/weeks/months, I want to reboot the server. Before rebooting, I am trying to cleanly stop and unmount everything. After stopping docker, there are some overlay2 mountpoints left over which prevent to unmount the underlying filesystem which eventually lets the whole server hang on shutdown.

How can I figure out where the issue is and/or whether this is a bug?

Additional info:
```
[le@nx]: ~>$ docker version
Client:
 Version:           19.03.2-ce
 API version:       1.40
 Go version:        go1.13
 Git commit:        6a30dfca03
 Built:             Tue Sep  3 23:41:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13
  Git commit:       6a30dfca03
  Built:            Tue Sep  3 23:39:37 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.9.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Steps to reproduce:
Not sure if that helps, because it does not seem to be always reproducible:

1) boot server
2) decrypt volumes
3) mount fs
4) start docker
5) start containers
6) wait
7) stop docker
8) mount | grep overlay2

umount /mnt/data fails because there are left over mounts in /mnt/data/docker

workaround:
```
for m in `mount | grep overlay | awk '{ print $3 }'`; do umount $m;done
for m in `mount | grep nsfs | awk '{ print $3 }'`; do umount $m;done
for m in `mount | grep shm | awk '{ print $3 }'`; do umount $m;done
```

followed by:
```
umount /mnt/data
```

Posted in arch bugtracker as well:
https://bugs.archlinux.org/task/65032

**Comment by thaJeztah** [comment]
Could you also post the output of `docker info` ?

Are there any (error) messages in the docker daemon logs or system logs? What kind of containers are you running (and, perhaps more importantly) are those containers bind-mounting directories from the host?

(Nested) mounts, or mounts leaking into other namespaces can sometimes cause problems, but could show error messages in the logs.

**Comment by mindrunner** [comment]
I posted more information in:
https://bugs.archlinux.org/task/65032

However, they closed the ticket because they did not answer, lol. No idea what's going on there. 

Anyways. Currently this seems to be not reproducible anymore...

**Comment by thaJeztah** [comment]
Let me close this ticket, but feel free to comment after that if there's updates

**Comment by seblu** [comment]
> However, they closed the ticket because they did not answer, lol. No idea what's going on there.
No. We closed because you didn't answer since Jan 3rd, to the questions asked by @thaJeztah on this very bug report.

**Comment by mindrunner** [comment]
my apologies! See other thread for explanation. I consider this as 'not a bug' now :)
