### ISSUE TITLE
LCOW: Cannot resolve container hostname on default network

### ISSUE THREAD

**Issue by riverar** [moby/moby#40357]
After spinning up a (LCOW) container, the container cannot resolve the name for any container on the same network, nor itself.

Repro
1. Set up Docker-CE or Docker-EE on a Windows host
2. On the host, issue command: `docker run -it --platform=linux --hostname test123 ubuntu:latest`
3. In the container, issue command: `apt update && apt install iproute2 dnsutils iputils-ping -y`
4. In the container, issue command: `hostname`.
5. Observe hostname matches specified hostname in step 1.
6. In the container, issue command: `nslookup test123`
7. Observe resolution failure

Actual
```bash
[apt package installation output removed]
...
root@test123:/# hostname
test123
root@test123:/# nslookup test123
;; Got SERVFAIL reply from 172.31.224.1, trying next server
;; Got SERVFAIL reply from 172.31.224.1, trying next server
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find test123: NXDOMAIN
```

Expected
Container hostname should have resolved, per DNS discovery design https://github.com/docker/libnetwork/issues/767

Version
```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     true
```

Info
```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 9
  Running: 1
  Paused: 0
  Stopped: 8
 Images: 171
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.535)
 OSType: windows
 Architecture: x86_64
 CPUs: 32
 Total Memory: 63.88GiB
 Name: Redacted
 ID: Redacted
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Seems to be related: docker/for-win#1976

**Comment by riverar** [comment]
This appears to be a result of https://github.com/moby/moby/commit/ebe0174f22ee9e26ff958a8ba607e8bb703c470e by @thaJeztah  where container hostnames and shortnames aren't added as aliases unless the network was created by the user. In other words, default `nat` networks cannot resolve container hostnames or shortnames.

Is this intentional new behavior?

**Comment by thaJeztah** [comment]
@riverar Trying to see what would've changed in that commit: I don't think the behavior changed in that commit; previously that part was in the `else`;

```go
if !containertypes.NetworkMode(n.Name()).IsUserDefined() {
    // validate options for non-user-defined network...
} else {
    // user-defined network: set aliases etc...
}
```

And the commit removed the first branch, so now it is

```go
if containertypes.NetworkMode(n.Name()).IsUserDefined() {
    // set aliases etc...
}
```

Did this work on older versions of Docker?

Note that behavior on Linux and Windows is different in this respect; on Linux, DNS entries were never created for the default ("bridge") network. If this DNS entries _should_ be created on Windows for the default network, then possibly this line should be changed from https://github.com/moby/moby/blob/6d9c219c549ba9e6b48e945dce3c9e4e64214850/daemon/container_operations.go#L684

To something like

```go
if containertypes.NetworkMode(n.Name()).IsUserDefined() || serviceDiscoveryOnDefaultNetwork() {
	// Configure aliases/service discovery on user-defined networks (Linux), or
	// if service discovery is available on the default network (Windows)
```



Not exactly sure what the behavior for LCOW would be (but I guess it's taking the "windows" path, so would follow the windows behavior). I should warn that the experimental LCOW feature is not actively worked on, and may be removed at some point, in favour of running docker in WSL2.

**Comment by riverar** [comment]
@thaJeztah Thanks for the quick response; agree with your assessment. I misread the diff.

The lack of service discovery on a bridged network makes sense, but less so on nat. But I can appreciate the alignment of _default_ DNS behavior across platforms. I'm torn and it's not really clear what the behavior should be.

It seems the intent, for Windows, was to enable this behavior
https://github.com/moby/moby/blob/ebe0174f22ee9e26ff958a8ba607e8bb703c470e/daemon/container_operations_windows.go#L157-L160

Minimally, I'd consider documenting this behavior (I'll scan the docs after some rest for a good location candidate.) Ideally, we'd commit your proposed change.

**Comment by thaJeztah** [comment]
> Thanks for the quick response; agree with your assessment. I misread the diff.

I must admit, I also had to look a few times to be sure I didn't screw up 😂. It did help though that you pointed to that part of the code, as it looks like it may be related.

I must admit that I'm not a Windows user, and not always familiar with the networking behavior on the Windows side

> The lack of service discovery on a bridged network makes sense, but less so on nat. But I can appreciate the alignment of default DNS behavior across platforms. I'm torn and it's not really clear what the behavior should be.

I feel the same; if I'm not mistaken, on Linux, "discovery" (and specifically: using the embedded DNS) is disabled on the default bridge network for historic reasons (before custom networks were implemented, the default network did not support it, so it was disabled to keep the old behavior and stay backward compatible / no breaking change).

Using `/etc/hosts` (for linked containers) instead is causing quite some headaches though (see https://github.com/moby/moby/issues/22295, and the discussion on https://github.com/docker/libnetwork/pull/2385#issuecomment-498516065 (among others) for the issues currently related to that 😞)

> Minimally, I'd suggest documenting this behavior. Ideally, we'd commit your proposed change.

Yes, I'm thinking of opening a pull-request with that change; we can discuss on that PR to decide if it's the right fix/approach (and otherwise close the PR and update the documentation instead).

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
