### ISSUE TITLE
Github links on website is wrong.

### ISSUE THREAD

**Issue by NetYaroze** [moby/moby#40350]
Sorry, I wasn't sure where to post this but noticed a few other site issues here. 

On the main site (https://mobyproject.org) the hrefs for the GitHub links on the page lead too:
`href="https://github.com/moby/moby/blob/moby/README.md`

Which subsequently 404.

Cheers!

**Comment by tnir** [comment]
dup: moby/mobywebsite#45

Will be addressed in moby/mobywebsite#42

**Comment by cpuguy83** [comment]
Thanks, I will close this in favor of the other.
