### ISSUE TITLE
Docker --privileged need more verbose or better inspect

### ISSUE THREAD

**Issue by florenthagard** [moby/moby#40365]
For understanding my request : [This is my current problem](https://stackoverflow.com/questions/59665735/docker-ecryptfs-capabilities-and-cgroup)

I think we need a tools or complete documentations to detect/know what --privileged exactely do, and how we can manualy reproduce to allow the strict needed kernel perms

**Comment by thaJeztah** [comment]
Looks like a duplicate  of https://github.com/moby/moby/issues/24387 (this comment describes better what `--privileged` does "behind the scenes"; https://github.com/moby/moby/issues/24387#issuecomment-249195810).

I'll close this one in favour of the existing issue, to prevent the conversation from diverging
