### ISSUE TITLE
Nightly binaries are outdated

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40378]
https://master.dockerproject.org/ hasn't been updated since 2019-12-12.

https://download.docker.com/linux/static/nightly/x86_64/ hasn't been updated since 2019-07-29.

**Comment by AkihiroSuda** [comment]
Or maybe we can create `moby/moby-nightlies` repo and set up GitHub Actions for shipping nightly releases?

@cpuguy83 WDYT?

**Comment by thaJeztah** [comment]
@StefanScherer @zelahi ptal. ISTR the cron-job was stopped at some point (but later on started again?). There was some discussion around retention policy (how long to keep older builds), but I guess that can be tweaked in the configuration.

**Comment by StefanScherer** [comment]
I remember it has been stopped due to the bigger release pipeline refactoring. But I don't know more details which jobs has triggered that.

**Comment by zelahi** [comment]
That but I also believe that they weren't being used, so the jobs were disabled

**Comment by AkihiroSuda** [comment]
https://get.docker.com/rootless depends on master.dockerproject.org

**Comment by AkihiroSuda** [comment]
master.dockerproject.org seems restarted, but it lacks vpnkit binary
https://github.com/docker/docker-install/issues/151#issuecomment-581270956

**Comment by StefanScherer** [comment]
@AkihiroSuda After updating the https://get.docker.com/rootless is still something missing? 
I'm able to install docker 19.03.5 now.

**Comment by AkihiroSuda** [comment]
19.03.5 is fine, but nightly channel seems still broken

**Comment by zelahi** [comment]
I believe we weren't releasing to nightlies or it was stopped as the usage was low

**Comment by tao12345666333** [comment]
Yes. I discussed this with @thaJeztah before.

But nightly build never seems to be updated. 
So I maintain a nightly build repo myself. (because I'm using fedora 30 myself, I haven't added branches to other distributions.) https://github.com/nightly-build/docker-nightly

If you need, I can provide other distributions. @AkihiroSuda 

Of course, I still hope to have the official nightly build channel.

For Fedora 30, can using this repo.

https://github.com/nightly-build/docker-nightly/blob/master/fedora30/docker-nightly.repo
```
[docker-nightly]
name=docker-nightly
baseurl=https://nightly-build.github.io/docker-nightly/fedora$releasever/$basearch/
repo_gpgcheck=0
gpgcheck=0
enabled=1
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by TBBle** [comment]
https://master.dockerproject.org/ seems to be functioning correctly now, and vpnkit has been reinstated in #40465.

Is it worth tracking the nightly channel (https://download.docker.com/linux/static/nightly/x86_64/ and, e.g., https://download.docker.com/linux/centos/7/x86_64/nightly/Packages/) in a separate issue? Specifically if it's not decided that they're worth maintaining, or it [was decided](https://github.com/moby/moby/issues/40378#issuecomment-582551701) that it's not worth maintaining "officially", in which case it maybe needs to be de-documented.

**Comment by AkihiroSuda** [comment]
Proposal: move https://github.com/AkihiroSuda/moby-snapshot to Moby org: https://github.com/moby/moby/issues/41187

**Comment by Mohsen7s** [comment]
Will anyone get on this issue ?

**Comment by TBBle** [comment]
Looks like https://master.dockerproject.org/ broke again, as of March 27th. Most-recent commit pushed is 8941dcfcc5db4aefc351cd5b5bb4d524823035c0. The next merge into master after that was 88e1fec49011c539c9da299f8e58ec2e25dbf8f1 which was a simple vendored library metadata upgrade, so I doubt that's related.

**Comment by thaJeztah** [comment]
We have as alternative https://hub.docker.com/r/moby/moby-bin

currently no plans to do the nightly channel again (but maybe one day again)

let me close this one for now
