### ISSUE TITLE
Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused"" module=libcontainerd namespace=plugins.moby

### ISSUE THREAD

**Issue by obeyler** [moby/moby#40390]
**Description**

I'm working with K8S and I've got severe issue with docker. The log :

time="2020-01-17T13:34:00.228328085Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused\"" module=libcontainerd namespace=plugins.moby

this error is in a permanent loop

I do not use snap and snap has never been install on this machine, so this pb is not link to a snap install.
I use a classic docker version: Docker version 18.09.9, build 039a7df9ba

If someone as any idea to fix it or find the reason...

**Steps to reproduce the issue:**
I don't know as I just use my K8S
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker version 18.09.9, build 039a7df9ba
**Output of `docker info`:**

```
docker info
Containers: 41
 Running: 0
 Paused: 0
 Stopped: 41
Images: 1
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-72-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66GiB
Name: 1b93ee77-d636-4555-9140-15e5da5cd904
ID: CNN4:IF4P:5EDQ:KUAX:2D26:2IO3:K45F:UEYX:33M7:VXTB:UFHI:QBLG
Docker Root Dir: /var/vcap/data/docker/docker

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
It seems like containerd is not running.
Can you check if the service is up?

**Comment by thaJeztah** [comment]
looks like this one went stale
