### ISSUE TITLE
POST /images/create does not use credentials stored with `docker login`

### ISSUE THREAD

**Issue by codeclown** [moby/moby#40397]
**Description**

Pulling an image by doing `POST /v1.40/images/create` should use credentials stored via `docker login`.

Using the API is generally equal to using the CLI. Based on this I would categorize this as a bug.

**Steps to reproduce the issue:**
1. Run `docker login registry.example.com` successfully
2. Credentials are now stored in `~/.docker/config.json`
3. To verify, run `docker pull registry.example.com/foobar`, which works
4. Run:

```bash
curl \
  --unix-socket /var/run/docker.sock \
  -X POST \
  http:/v1.40/images/create?fromImage=registry.example.com/foobar
```

**Describe the results you received:**

```json
{"message":"Get https://registry.example.com/image/v2/foobar/tags/list: no basic auth credentials"}
```

**Describe the results you expected:**

```json
{"status":"Pulling from foobar","id":"latest"}
...
```

Same as adding the [auth header](https://docs.docker.com/engine/api/v1.40/#section/Authentication) into the request via:

```bash
  -H 'X-Registry-Auth: [base64]'
```

**Additional information you deem important (e.g. issue happens only occasionally):**

–

**Output of `docker version`:**

<details>

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

</details>

**Output of `docker info`:**

<details>

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-65-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 985.3MiB
 Name: ubuntu-bionic
 ID: 23LF:4QLT:7U2Y:E6UY:GWV7:RYGI:42DN:WDUX:LD5O:75LZ:PJW5:YPPR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox using Vagrant

**Comment by codeclown** [comment]
It just occurred to me that because the credentials are stored under `~`, maybe this isn't a bug after all. The Docker daemon probably shouldn't look for credentials under random users' home directories.

**Comment by thaJeztah** [comment]
The `~/.docker/config.json` file is used by the `docker` CLI (not the daemon). Credentials can be either stored inside that file, or it can use a credential-helper (e.g. to store credentials in the macOS keychain, `pass` password storage on Linux, or other mechanisms).

When you use curl, those credentials are not automatically used (you'd have to do that yourself). (How would `curl` know about the credentials stored in `~/.docker/config.json` ?)

**Comment by codeclown** [comment]
@thaJeztah I agree and understand. I wrote an extra comment just a few seconds before yours, posing the question why would Docker daemon read those files. For no reason, of course. I am closing this issue, thanks!

**Comment by thaJeztah** [comment]
👍 happy to help!
