### ISSUE TITLE
Question regarding completeness of Dockerfile integration tests

### ISSUE THREAD

**Issue by 1605200517** [moby/moby#40400]
Hello moby team,

I have a question - how do you ensure the completeness of the unit/integration tests for Dockerfile?

That is, there should be a great variety of test Dockerfiles to test a mostly large set of possible AND meaningful combinations of tokens?

What I find here though are just a couple of files? Or how do you test this?

https://github.com/moby/moby/tree/master/integration/build/testdata

**Comment by AkihiroSuda** [comment]
See https://github.com/moby/buildkit/blob/master/frontend/dockerfile/dockerfile_test.go

**Comment by thaJeztah** [comment]
There's a couple more tests in [integration-cli/docker_api_build_test.go](https://github.com/moby/moby/blob/580d3677c80398fb0fffb12a6a7db784ec1a135d/integration-cli/docker_api_build_test.go), [integration-cli/docker_api_build_windows_test.go](https://github.com/moby/moby/blob/580d3677c80398fb0fffb12a6a7db784ec1a135d/integration-cli/docker_api_build_windows_test.go), [integration-cli/docker_cli_build_test.go](https://github.com/moby/moby/blob/580d3677c80398fb0fffb12a6a7db784ec1a135d/integration-cli/docker_cli_build_test.go), [integration-cli/docker_cli_build_unix_test.go](https://github.com/moby/moby/blob/580d3677c80398fb0fffb12a6a7db784ec1a135d/integration-cli/docker_cli_build_unix_test.go) as well

**Comment by thaJeztah** [comment]
Let me close this ticket because it's not really a bug report, but feel free to continue the conversation.

Also if there was a particular reason for your question (e.g. did you run into a problem with a specific Dockerfile), feel free to open a ticket for that!

**Comment by 1605200517** [comment]
@AkihiroSuda @thaJeztah thanks for quick reply!

Why are test files .go scripts, not Dockerfiles?

Let me explain the background. Due to organizational requirements and issues with Docker Machine we want to try Kaniko which allows building Docker images without Docker daemon. In the past, I've read that Kaniko had some compatibility issues. 

Therefore I thought there would have been something comparable to the ACID browser test, at least a set of Dockerfiles.

That is, there are specs describing set of all possible options, and there could be a test (set) measuring (allowing to derive data on) implementation completeness?

http://acid3.acidtests.org/

At Kaniko, I've asked same question.

https://github.com/GoogleContainerTools/kaniko/issues/991

**Comment by thaJeztah** [comment]
The moby/buildkit repository is the canonical place for the Dockerfile specification.

If you're intending to build on kubernetes, you may be interested in @AkihiroSuda's talks about Buildkit on Kubernetes; 

- https://www.slideshare.net/AkihiroSuda/dockercon2019-deploying-rootless-buildkit-on-kubernetes
- https://www.slideshare.net/AkihiroSuda/kubeconeu-building-images-efficiently-and-securely-on-kubernetes-with-buildkit

**Comment by AkihiroSuda** [comment]
Probably this test suite is useful

https://github.com/jessfraz/dockerfiles

**Comment by thaJeztah** [comment]
I know at some points we parsed/tested  _every dockerfile_ on GitHub 😂 ; https://twitter.com/thaJeztah/status/601434642126745601?s=20

https://github.com/moby/moby/pull/12648#issuecomment-104341648

<img width="774" alt="Screenshot 2020-01-23 at 16 46 34" src="https://user-images.githubusercontent.com/1804568/72999678-fc798a80-3dff-11ea-875b-e1aab1e9ee0f.png">
