### ISSUE TITLE
docker stack deploy api not present?

### ISSUE THREAD

**Issue by anshupitlia** [moby/moby#40407]
**Description**

I'm trying to run docker stack deploy through a golang application. I can't find an api for this. 
**Steps to reproduce the issue:**
1. Create a golang application with docker-compose.yaml file. The yaml file contains one of the image to be pulled by azure container repository
2. Get the container repository token by hitting /auth endpoint
3. In absence of an api for docker stack deploy, Try a exec.Command("docker", "stack", " deploy", .....)
4. How do I pass token to this? 

Had there been an api I would have made a curl call. 

My other alternative is to use docker-compose (forget the cluster and just run the file on one node), but that too will have the same problem.

**Comment by AkihiroSuda** [comment]
There was a PR for this, but closed: https://github.com/moby/moby/pull/38832

See https://github.com/docker/cli/blob/master/cli/command/stack/swarm/deploy.go for the CLI-side implementation.

**Comment by anshupitlia** [comment]
But it was closed because the PR was incomplete. No other active development for this?
