### ISSUE TITLE
docker build: "error creating overlay mount to /var/lib/docker/overlay2/xxx/merged: device or resource busy"

### ISSUE THREAD

**Issue by NoICE** [moby/moby#40410]
**Description**

When running docker build (parallel - around 3-6 other builds) on our Gitlab CI instance I encounter a lot of failed builds because of this error:

```
---> a4d65b2fc73e
Step 9/19 : RUN ["crystal", "spec", "--error-on-warnings", "--no-debug"]
error creating overlay mount to /var/lib/docker/overlay2/209a7dfb23bbf26404576987d2b3e1e847f3c6afcc328b201afe75f6d8de2639/merged: device or resource busy
```

This happens randomly. Sometimes there are 12 concurrent build jobs running and nothing happens, but then there is single build job (=multiple docker builds running at once) and this happens.
Sadly I don't know when this started occuring exactly, so I don't know since what docker or linux version is the cause.

NOTE: there is no push going on at the same time, just other docker builds. Verified multiple times that this is caused by docker build alone, so concurrent push isn't the cause.

Doing `docker system prune -af` was suggested in docker/for-linux#711, but that did not help.

I found only one similar issue to this one (moby/moby#39751), but that seems to be about `docker push`. Don't know if this is related, regression or duplicity. Either way, that issue is closed. Other issues are for incompatibility with newer versions of linux kernel.
Someone mentioned running with `overlay` driver instead of `overlay2`, or switching off concurrent builds in Gitlab, but I don't consider any of that to be a fix.

**Steps to reproduce the issue:**
1. run `docker build` multiple times at the same time
2. watch the world burn, receive failed build messages, watch your happiness go down
3. ... don't profit.

**Describe the results you received:**
Unexpected random error messages regarding overlay2.

**Describe the results you expected:**
No failed docker builds :-)

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens randomly, multiple times a day.
Gitlab runner is configured to use docker via mounted `/var/run/docker.sock`.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 25
  Running: 3
  Paused: 0
  Stopped: 22
 Images: 748
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.54GiB
 Name: dev
 ID: ESO2:YKCY:PW7K:XKWK:VNTK:S6UB:Y6TO:CLAN:JT4K:PR22:IVCU:UWQ5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMware VM running on iSCSI SSD array. VM has 8 cores and 24GB of memory. Running Debian buster. Docker CE via official docker repository.

**Comment by kryvel** [comment]
Same issue on Gitlab CI + Shell Gitlab Runner

Trying to push locally build image to gitlab repository result in
`error creating overlay mount to /opt/docker/overlay2/xxx/merged: device or resource busy`

**System env**
docker version 
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Tue, 03 Sep 2019 19:59:35 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Tue Sep  3 17:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker info
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 331
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-6-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.666GiB
Name: ci.akm.space
ID: RHMD:2L2L:BWCD:C4U5:47V3:U6LW:KVEU:YDGB:LJWX:LBEA:OE3I:KBXB
Docker Root Dir: /opt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by CybotTM** [comment]
We fixed this issue for our systems by updating to:
- Docker to 19.03.05
- Debian 10
- backported Kernel 5.4

(with overlay2 and buildkit enabled)

**Comment by t-8ch** [comment]
The non-backport kernel of Debian 10 also ships the fixes as of this week.

**Comment by kryvel** [comment]
Do you know what was cause a bug ?
Just updated on 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by NoICE** [comment]
Just updated to 4.19.0-8-amd64 (from 4.19.0-6-amd64). I'll let you know if that helped.

**Comment by vlauciani** [comment]
Same problem for me:
```
error creating overlay mount to /var/lib/docker/overlay2/bdds2vyhwpb3nqhs2i1sdg2nf/merged: device or resource busy
```

With:
```
# uname -r
4.19.0-6-amd64
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 251.6GiB
 Name: sqlx2-srvr
 ID: G3Q4:DJCB:BHCZ:IVMD:CEBD:BLAT:B6FM:UAIV:QBAN:M3DS:243J:X5F5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
#
# cat /etc/debian_version
10.3
#
```

**Comment by t-8ch** [comment]
@vlauciani 
> With:
> 
> ```
> # uname -r
> 4.19.0-6-amd64
> ```

It should be 4.19.0-8-amd64

**Comment by vlauciani** [comment]
ok, true!

With `4.19.0-8-amd64` it works!

**Comment by kryvel** [comment]
I confirm that update to 4.19.0-8 fixed that issue

**Comment by cpuguy83** [comment]
Seems like since this is a kernel issue and is fixed in various newer kernel patches, I'm going to go ahead and close this, but feel free to discuss.

Thank you! 😇

**Comment by devraj1414** [comment]
Please check the mounted images under Docker -> Dashboard. There might be multiple mounting of image for a same application.
