### ISSUE TITLE
Docker stats memory is higher than all processes summed up and growing steadily

### ISSUE THREAD

**Issue by bobzsj87** [moby/moby#40415]
I have a node server running in the docker (via AWS ECS), and the memory reported by the ECS (which is the same as the docker stats, confirmed by going inside the instance and show the figure) **keeps growing**. However, the Top command shows both inside the docker container and in the host machine are stable. The`memoryUsage().rss` value reported from node (12.14) also is the same as value shown in the RSS value in `top`.

The node application is an express HTTP server, which on each call users child_process to spawn and exec avconv for audio conversion. There is no zombie process observed either.

However, the memory is **automatically "released"** after reaching the soft limit (512 mb), going back to about 100mb. Can't explain why it happens, it doesn't look like memory leak either since the memory reported in `top` and node's RSS stays stable all the time.

Shown as below. The left is the `top` command run in instance c58, while the right is the `docker stats` run from the host machine.
 
![image](https://user-images.githubusercontent.com/568939/73124035-c15d8f80-3f96-11ea-8fbf-87c9da2b8b08.png)

Docker version: 18.09.9-ce

Investigated a number of previous issues like https://github.com/moby/moby/issues/10824 and https://github.com/moby/moby/issues/32253, but got no luck from there. 

Any clue will be helpful!

**Comment by bobzsj87** [comment]
More information today. The memory grows from ~160mb to 260. And here is some debug information from cgroup.

First, identify the proc id
`                                                                                                 
 7587 root      20   0  957536 112884  31180 S   1.0  2.8  37:58.73 node                                                                                                                
`

Second, figure out the cgroup location
`
3:memory:/ecs/1225b1ad-11cc-43aa-9cd7-514767671c69/31accd6a387bee47b660e421b39c3b47903db12f233a55b4139d861b1c24c2f6
`

Then, get the cgroup memory stats

```
[ec2-user@ip-10-1-10-166 ~]$ cat /sys/fs/cgroup//memory/ecs/1225b1ad-11cc-43aa-9cd7-514767671c69/31accd6a387bee47b660e421b39c3b47903db12f233a55b4139d861b1c24c2f6/memory.stat
cache 4096
rss 114470912
rss_huge 0
shmem 0
mapped_file 0
dirty 0
writeback 0
swap 0
pgpgin 181482989
pgpgout 181455041
pgfault 328865391
pgmajfault 0
inactive_anon 0
active_anon 114470912
inactive_file 4096
active_file 0
unevictable 0
hierarchical_memory_limit 536870912
hierarchical_memsw_limit 9223372036854771712
total_cache 4096
total_rss 114470912
total_rss_huge 0
total_shmem 0
total_mapped_file 0
total_dirty 0
total_writeback 0
total_swap 0
total_pgpgin 181482989
total_pgpgout 181455041
total_pgfault 328865391
total_pgmajfault 0
total_inactive_anon 0
total_active_anon 114470912
total_inactive_file 4096
total_active_file 0
total_unevictable 0

```

The RSS number is close to the value observed in `top`, just around 100mb, the same as yesterday. However, the docker stats shows very differently.
`
31accd6a387b        ecs-speech_request_service-7-speechrequestservice-aaa9caddc4f3db9a7000   0.72%               250.3MiB / 3.794GiB   6.44%               0B / 0B  
`

**Comment by bobzsj87** [comment]
After investigation, the memory.usage_in_bytes - cache is correctly reflected in the docker stats. So the question becomes why rss + cache is much lower than usage_in_bytes (like 40%), and why usage_in_bytes is growing. Thus closing the issue

https://unix.stackexchange.com/questions/451252/cgroup-memory-usage-in-bytes-shows-incorrect-value

**Comment by kenzshelley** [comment]
@bobzsj87 Did you ever figure out why `memory.usage_in_bytes` was steadily increasing? I'm seeing something very similar with a docker container running w/in a Kubernetes cluster in gcp

**Comment by bobzsj87** [comment]
Yes, in my case it was the creation of many files which led to dentry cache (which is safe though). I wrote about it here: https://medium.com/@bobzsj87/demist-the-memory-ghost-d6b7cf45dd2a

**Comment by kenzshelley** [comment]
Ah excellent, thanks for sharing. We are definitely having the same problem (kmem growing out of control)
