### ISSUE TITLE
Date with docker for Windows version stable 2.2.0.0

### ISSUE THREAD

**Issue by sylvainmouquet** [moby/moby#40418]
My PC is Windows 10 Pro and the timezone is UTC +1 Paris and the current time is 13h45
When i run ubuntu image the date and timezone are correct but when i run a debian image the date have 1 hour more :

```
PS C:\Temp> docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:8d31dad0c58f552e890d68bbfb735588b6b820a46e459672d96e585871acc110
Status: Image is up to date for ubuntu:latest
docker.io/library/ubuntu:latest
```

```
PS C:\Temp> docker pull debian
Using default tag: latest
latest: Pulling from library/debian
Digest: sha256:f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
Status: Image is up to date for debian:latest
docker.io/library/debian:latest
PS C:\Temp> docker run --rm --privileged -e TZ=Europe/Paris -it ubuntu bash -c "date && hwclock -w && date"
Mon Jan 27 13:45:21 Europe 2020
Mon Jan 27 13:45:21 Europe 2020
PS C:\Temp> docker run --rm --privileged -e TZ=Europe/Paris -it debian bash -c "date && hwclock -w && date"
Mon Jan 27 14:45:26 CET 2020
Mon Jan 27 14:45:27 CET 2020
```

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by sylvainmouquet** [comment]
With docker for windows version **2.1.0.5**
The current time is 14h20

```
docker pull debian
Using default tag: latest
latest: Pulling from library/debian
8f0fdd3eaac0: Pull complete
Digest: sha256:f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
Status: Downloaded newer image for debian:latest
docker.io/library/debian:latest

```

```
λ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
5c939e3a4d10: Already exists
c63719cdbe7a: Already exists
19a861ea6baf: Already exists
651c9d2d6c4f: Already exists
Digest: sha256:8d31dad0c58f552e890d68bbfb735588b6b820a46e459672d96e585871acc110
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
```

```
λ docker run --rm --privileged -e TZ=Europe/Paris -it ubuntu bash -c "date && hwclock -w && date"
Mon Jan 27 13:15:38 Europe 2020
Mon Jan 27 13:15:39 Europe 2020
```

```
λ docker run --rm --privileged -e TZ=Europe/Paris -it debian bash -c "date && hwclock -w && date"
Mon Jan 27 14:15:50 CET 2020
Mon Jan 27 14:15:50 CET 2020
```

λ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by thaJeztah** [comment]
The same is visible on a Linux machine; I suspect the `ubuntu` and `debian` images are configured different;

```
$ docker run --rm --privileged -e TZ=Europe/Paris -it ubuntu bash -c "date && hwclock -w && date"
Mon Jan 27 13:14:09 Europe 2020
Mon Jan 27 13:14:10 Europe 2020
$docker run --rm --privileged -e TZ=Europe/Paris -it debian bash -c "date && hwclock -w && date"
Mon Jan 27 14:14:14 CET 2020
Mon Jan 27 14:14:15 CET 2020
```

Given that the Ubuntu image looks to be 1 hour "off" in this case, I'd suggest opening a ticket there (the readme on Docker Hub (https://hub.docker.com/_/ubuntu) mentions canonical's "cloud-images bug tracker" to report issues: https://bugs.launchpad.net/cloud-images)


Note that you shouldn't need `--privileged` or `hwclock` unless you want to update the clock of your whole system; the clock is not currently namespaced in the kernel, so updating time in the container would update the actual time on the host. The `TZ` option should only affect the _presentation_ of the current time though. Work is in progress (or may have been accepted already) to add a `time namespace` to the Linux kernel (https://lwn.net/Articles/766089/)

(also see https://github.com/moby/moby/issues/12084)


```bash
docker run --rm -e TZ=Europe/Paris -it debian bash -c "date"
Mon Jan 27 14:14:31 CET 2020
docker run --rm -e TZ=Europe/Paris -it ubuntu bash -c "date"
Mon Jan 27 13:14:44 Europe 2020
```

**Comment by thaJeztah** [comment]
Let me close this ticket, because I don't think there's a bug in the docker daemon here, but feel free to continue the conversation.

**Comment by sylvainmouquet** [comment]
Ok i have not writen all.
When i have updated the docker for windows, the current date was not correct. The date was 23/01/2020 but we are the 27/01/2020.
I have sync the date in my docker containers with `hwclock -w`

And between the version 2.1.0.5 and 2.2.0.0
We show a difference of **one hour** : 
docker for windows **2.2.0.0**
PC time and Timezone : 13h45 Europe/Paris
```
docker run --rm --privileged -e TZ=Europe/Paris -it debian bash -c "date && hwclock -w && date"
Mon Jan 27 14:45:26 CET 2020 
```

and docker for windows **2.1.0.5**
PC time and Timezone : 14:15 Europe/Paris
```
docker run --rm --privileged -e TZ=Europe/Paris -it debian bash -c "date && hwclock -w && date"
Mon Jan 27 14:15:50 CET 2020
```

With version **2.1.0.5** the date and timezone are correct and not with version **2.2.0.0**
