### ISSUE TITLE
Enable support for AWS imdsv2 by upgrading aws-sdk version

### ISSUE THREAD

**Issue by logsnitch** [moby/moby#40422]
**Description**

Hi,

In November 2019 AWS announced their "version 2" of the metadata service, to protect users against SSRF attacks leading to credential compromises:
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

Amazon updated all of their SDKs to make this transparent to users.

However, I'm unable to opt into this protection because the docker awslogs driver is running an old version of the aws-sdk. I'd like to request that the awslogs driver be updated to use any version of the aws-sdk 1.25.38 or higher, which is when support was added:
https://github.com/aws/aws-sdk-go/releases/tag/v1.25.38

More details on this issue: https://github.com/aws/containers-roadmap/issues/670

Thanks very much!

**Comment by samuelkarp** [comment]
I'm planning on taking a look at this.
