### ISSUE TITLE
Question on logdriver entry.proto

### ISSUE THREAD

**Issue by FedericoPonzi** [moby/moby#40420]
**Description**
I'm writing a logging plugin, and was wondering: is there documentation for the meaning of these parameters? https://github.com/moby/moby/blob/master/api/types/plugins/logdriver/entry.proto
Also, if `source` is either `stdout`/`stderr`, I've tried a couple of things suggested [here](https://stackoverflow.com/questions/2990414/echo-that-outputs-to-stderr) but I always get "stdout" as source.

**Comment by thaJeztah** [comment]
I think that `.proto` file is only used for the "local" logging driver (see https://github.com/moby/moby/pull/37092 and  (and not intended for external use other than by that driver https://github.com/moby/moby/issues/33475)

/cc @cpuguy83

**Comment by FedericoPonzi** [comment]
For example:
```
docker run --log-driver my-log-driver -it --init --rm debian:stretch-slim  bash -c "e"
```
Leads to:
```
Jan 28 16:48:55 ActyxOS dockerd[1650]: time="2020-01-28T16:48:55+01:00" level=error msg="Source: stdout, Message: bash: e: command not found" plugin=1b54adb68cc94124fa7eda734b424f8aa191a2bd3c596f73a0667927a756f811
```

**Comment by FedericoPonzi** [comment]
> I think that `.proto` file is only used for the "local" logging driver (see #37092 and (and not intended for external use other than by that driver #33475)
> 
> /cc @cpuguy83

I've followed what's described here: https://docs.docker.com/engine/extend/plugins_logging/

**Comment by cpuguy83** [comment]
The proto is for plugins and the local log driver.

You are only getting `stdout` because you have setup a tty (the `-t` option). TTY is a single stream.

**Comment by thaJeztah** [comment]
> The proto is for plugins and the local log driver.

Ah, sorry, was mistaken then 😊

**Comment by FedericoPonzi** [comment]
> The proto is for plugins and the local log driver.
> 
> You are only getting `stdout` because you have setup a tty (the `-t` option). TTY is a single stream.
Awesome! It's working now, but still are there any docs on the proto file? For example, I assume that if a logentry has `partial` it contains a truncated `line`, right?

**Comment by cpuguy83** [comment]
>  but still are there any docs on the proto file?

Doesn't seem so: https://godoc.org/github.com/docker/docker/api/types/plugins/logdriver

>  I assume that if a logentry has partial it contains a truncated line

That's correct. There should be some extra metadata that goes along with that as well which will tell you if its't he last entry and the order.

**Comment by FedericoPonzi** [comment]
Thanks!
