### ISSUE TITLE
`make binary` doesn't build `bundles/binary-daemon/vpnkit`

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40459]
https://master.dockerproject.org was restarted a couple of days ago (https://github.com/moby/moby/issues/40378), but seems lacking vpnkit binary.

Originally reported in https://github.com/docker/docker-install/issues/151#issuecomment-581270956

**Comment by AkihiroSuda** [comment]
This is because `make binary` no longer builds `bundles/binary-daemon/vpnkit` due to some recent regression

**Comment by AkihiroSuda** [comment]
seems regression in https://github.com/moby/moby/pull/40180

cc @cpuguy83

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/pull/40465
