### ISSUE TITLE
Multistage: support for two base builds (cache)

### ISSUE THREAD

**Issue by HoneyryderChuck** [moby/moby#40450]
**Description**

Recently, we've moved from a monolithic image to using multistage builds in order to achieve leaner and more dependency free images for our web application. So far, we have accomplished that, but we stumbled into a side-effect, for which we'd like to have a better solution, possibly inside docker.

Our application is a rails application, with frontend assets built using webpack. Initially, we'd use a ruby base image, install javascript, and would run everything inside one machine. Now, our multistage contains: a base node image where we run the webpack dev server; a base ruby image where we run the application; a test node image which builds the assets in test mode; a test ruby image which copies those assets where rails/cucumber can pick them up; a prod node image which builds the assets in production mode; and a prod ruby image where we copy those prod assets and precompile the assets.

Although the resulting images are leaner and dependency-free, we **break intermediate cache all the time**, i.e. these images aren't cached in between themselves, which was our expectation in the beginning of the project. We'd like to see if this would be a possible feature for the multistage setup, because, as far as we understood, the multistage happy path is when you have one base and many resulting images, and not our case, where we have 2 base images (the node and the ruby image).

**Steps to reproduce the issue:**

This assumes that you have some base rails app with a package.json.

1. Use a Dockerfile like this:

```Dockerfile
# Node
FROM node:13.1-slim AS frontend
WORKDIR /app
COPY package.json yarn.lock .yarnrc ./
COPY ._npmrc .npmrc
RUN mkdir /node_modules
RUN yarn
CMD ["yarn", "start"]

FROM ruby:2.7 as backend
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

FROM frontend as frontend-test
COPY . .
RUN yarn build:dev

FROM backend as backend-test
COPY --from=frontend-test /app/vendor /app/vendor


FROM frontend as frontend-prod
COPY . .
RUN yarn build

FROM backend as platform-prod
ENV RAILS_ENV=production
COPY --from=frontend-release /app/vendor /app/vendor
RUN bundle exec rails assets:precompile
CMD ["bundle", "exec", "puma"]
```

**Describe the results you expected:**

builds these image multiple times. For the "backend" image, you'll see that, although it caches the "backend" intermediate images, it'll build "frontend" in the process again (and uncached). 

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 38
  Running: 6
  Paused: 0
  Stopped: 32
 Images: 208
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4.825GiB
 Name: docker-desktop
 ID: 4WLN:6EMU:LFAM:Y4IW:HY2N:PV2N:H53Z:3VEF:GD7X:XYP4:LZGF:XJUZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 93
  Goroutines: 121
  System Time: 2020-02-03T15:55:59.1341998Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by cpuguy83** [comment]
I'm not sure what you mean by:

> we break intermediate cache all the time

Could you explain more? What is busted?

Also are you building with `DOCKER_BUILDKIT=1`?

**Comment by thaJeztah** [comment]
If this is without buildkit, this is likely expected (because without buildkit enabled, all stages would always be built again, even if they're not used by the final stage)

**Comment by HoneyryderChuck** [comment]
yes, I can confirm, without buildkit. Is this always going to be like this without it?

**Comment by cpuguy83** [comment]
Until buildkit is made the default.

**Comment by thaJeztah** [comment]
There's a tracking issue/proposal for making buildkit the default; https://github.com/moby/moby/issues/40379

I'd definitely recommend enabling buildkit (setting `DOCKER_BUILDKIT=1`), as it has many improvements over the "classic" builder.

Given that this issue is already addressed by buildkit, and not something that can be fixed in the classic builder, I'll close this ticket, but feel free to continue the conversation
