### ISSUE TITLE
docker inspect containerID blocks

### ISSUE THREAD

**Issue by qiuhui** [moby/moby#40463]
On some of my machines,inspect or stop some running container will be blocked,and I can not find directories about them in my docker root directory,for example
![image](https://user-images.githubusercontent.com/3477024/73912248-fea71300-48ee-11ea-8028-10a819e91ed4.png)
docker version is 18.06.1.
Can any one help me?

**Comment by thaJeztah** [comment]
Are you still able to reproduce this on a current version of docker? 18.06 reached EOL over a year ago, and quite some things changed in the code since

**Comment by qiuhui** [comment]
@thaJeztah OK,I will try it on newer version of docker

**Comment by cpuguy83** [comment]
Let's go ahead and close this.
If you do hit the issue again on a the latest version of docker please let us know.

Thank you!
