### ISSUE TITLE
Cannot run process isolated containers anymore after updating to Windows 1909

### ISSUE THREAD

**Issue by drauch** [moby/moby#40468]
@mat007 closed my issue at https://github.com/docker/for-win/issues/5708 and recommended to create an issue here instead.

### Expected behavior

I can run `docker run --isolation Process mcr.microsoft.com/windows/servercore:ltsc2019` without errors.

### Actual behavior

I get the error:

```
docker: Error response from daemon: hcsshim::CreateComputeSystem 09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8: The system cannot find the file specified.
(extra info: {"SystemType":"Container","Name":"09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8","Owner":"docker","VolumePath":"\\\\?\\Volume{d937f6de-dd1b-4a79-a06f-e375663b1d2d}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\09a562689840ed63c6f51f1bdb34973e996a3339784380748322fcb44f1fe4f8","Layers":[{"ID":"9cc9c6c9-720e-56b8-8666-c55a447aa544","Path":"C:\\ProgramData\\Docker\\windowsfilter\\916f7433d2b4a29d206ea46b131f59539bafce49929dd18d8e063c73c7d66fcb"},{"ID":"a0b38a38-abce-595f-b355-ee7f95f5a446","Path":"C:\\ProgramData\\Docker\\windowsfilter\\237f0b01103775586bceeb74d2174ca8c929210cd5c1a431d10f50dd86daa100"}],"HostName":"09a562689840","HvPartition":false,"EndpointList":["2664327E-E3DA-4989-B292-D20A129FB749"],"AllowUnqualifiedDNSQuery":true}).
```

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, after updating to Windows 1909
  - Windows Version: W10 1909
  - Docker Desktop Version: 2.2.0.0 stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by thaJeztah** [comment]
Process isolation unfortunately isn't guaranteed to work if the version of the image's base image doesn't match the kernel version of the host (Windows does not have a stable kernel API, which means that kernel compatibility isn't guaranteed).

That said; things should have improved in recent versions of Windows to be more compatible, but possibly a breaking change was introduced somewhere in the latest Windows updates 😞


ping @taylorb-microsoft @jterry75 for visibility

**Comment by drauch** [comment]
@thaJeztah : Actually I'm pretty sure that mcr.microsoft.com/windows/servercore:ltsc2019 equals the 1909 Windows 10 version and should therefore be compatible. Are there additional known compatibility problems in regards to the 1909 version?

**Comment by thaJeztah** [comment]
Looking at https://hub.docker.com/_/microsoft-windows-servercore
`ltsc2019` is corresponding with kernel `10.0.17763.1039`, and 1909 ("19H2") is kernel `10.0.18363.657` (`17763` vs `18363`), so they're not identical

**Comment by drauch** [comment]
Oh boy, didn't realize that, I thought that the up-to-date Windows 10 release version always corresponds to the latest tag, So in other words: I shouldn't have updated my OS because there is no compatible container available yet for process isolation?

**Comment by drauch** [comment]
A colleague of mine just pointed out that there is a non-ltsc 1909 tag which can be used. This one indeed works, but still, if you want to run the LTSC container on a development machine for testing purposes for its entire lifespan you can't update your Windows version while doing so - is this information correct? Is this something that's planned to be fixed or will this be a limitation for the foreseeable future?

**Comment by thaJeztah** [comment]
>  if you want to run the LTSC container on a development machine for testing purposes for its entire lifespan you can't update your Windows version while doing so - is this information correct? 

If you want the container to run with `process` isolation, then that might be correct (IIUC, for some differences it works, but no guarantees). Otherwise, use hyper-v isolation.

> Is this something that's planned to be fixed or will this be a limitation for the foreseeable future?

The general issue of a stable kernel API is something to be resolved in the Windows kernel. While things have improved, I don't think a stable kernel API will become reality soon (and is also a contributor to Windows images being quite large compared to Linux images).

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
