### ISSUE TITLE
Faulting application name: vmcompute.exe, Faulting module name: ntdll.dll

### ISSUE THREAD

**Issue by SquallHalle** [moby/moby#40479]
### Expected behavior

Started Containers does not stop working.

### Actual behavior

after a random time, my containers stop working. 
I find these behavioir on two of my servers.
I cant stop them or whatever.
At the time of the containers stop working the log writes: 

    [16:56:19.310][WindowsDaemon     ][Error  ] Faulting application name: vmcompute.exe, version: 10.0.17763.1007, time stamp: 0xec9fd8bc
    Faulting module name: ntdll.dll, version: 10.0.17763.1007, time stamp: 0x178c7d7f
    Exception code: 0xc0000409
    Fault offset: 0x00000000000a4710
    Faulting process id: 0x117c
    Faulting application start time: 0x01d5de941c6e0060
    Faulting application path: C:\Windows\system32\vmcompute.exe
    Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
    Report Id: d2537f16-2d7a-4fea-8805-81b5435b287f
    Faulting package full name: 
    Faulting package-relative application ID: 
    [16:56:19.644][WindowsDaemon     ][Info   ] debug:  [notification-type=ServiceDisconnect system-id=f6bf3a4da8b297f00733a8f51afddc8d221f9176d39c37b818193566c384e9b3 pid=6776]
    [16:56:19.644][WindowsDaemon     ][Info   ] debug:  [notification-type=ServiceDisconnect system-id=f6bf3a4da8b297f00733a8f51afddc8d221f9176d39c37b818193566c384e9b3]
    [16:56:19.765][WindowsDaemon     ][Info   ] Fault bucket , type 0
    Event Name: BEX64
    Response: Not available
    Cab Id: 0

### Information

Setup:

- Windows Server 2019 1809: 17763.1012 (VMs on VSphere)
- Docker Version: 2.1.0.5 / 2.2.0.0
- Running Windows/Linux Containers

Very simila,r exact same infos form docker info:
#40328 

simple test conatiner:

    version: '3'
    services:
      simpletest:
        image: mcr.microsoft.com/windows/servercore/iis:latest
        container_name: simpletest
        restart: unless-stopped
        ports:
          - "8080:80"
        network_mode: nat
        volumes:
          - path:c:\inetpub\wwwroot
[extlog.txt](https://github.com/docker/for-win/files/4174642/extlog.txt)

Extended log File should be attached

### Steps to reproduce the behavior

 dont know if reproduceble 
[extlog.txt](https://github.com/moby/moby/files/4174644/extlog.txt)

**Comment by thaJeztah** [comment]
Looks like a possible kernel issue?

@jstarks @jterry75 ptal

**Comment by pgrawehr** [comment]
We've got the exact same issue here. After at most 30 minutes, the container dies, and all that helps in getting it to live again is restart the docker service(!). When the container stops responding, `docker stop` hangs and all traces we have are the exceptions stated above in the system log. 
Similar configuration: Host is Windows 2019 Server (Version 1809), running on VmWare 6.5. The problem happens both with hyperv isolation or process isolation.

**Comment by SquallHalle** [comment]
@pgrawehr take a look into 
#40328 
its likly the same problem but on this one is more activty. 

also do you got this windows update installed ? https://support.microsoft.com/de-de/help/4534273/windows-10-update-kb4534273

**Comment by pgrawehr** [comment]
Could be related, indeed. However, I never saw that error code. The container just stops responding (and does not exit, even if forced). 

Yes, that update is installed. Shall I try removing it?

**Comment by antonyoni** [comment]
Same issue here, running docker in a vSphere Windows Server 2019 VM, and unable to stop containers once vmcompute.exe fails, even with `docker kill`. Have to restart the docker service. Not sure if it's related to #37919 but one of the comments mentions a similar issue.

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 259
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.973)
 OSType: windows
 Architecture: x86_64
 Debug Mode: false
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
Faulting application name: vmcompute.exe, version: 10.0.17763.831, time stamp: 0x26b81899
Faulting module name: ntdll.dll, version: 10.0.17763.831, time stamp: 0x1f1a0210
Exception code: 0xc0000409
Fault offset: 0x00000000000a4720
Faulting process id: 0x1408
Faulting application start time: 0x01d5f23b80768412
Faulting application path: C:\Windows\system32\vmcompute.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by SquallHalle** [comment]
@antonyoni  did you tried the "workaround" from https://github.com/moby/moby/issues/40328 ? 
so downgrading the VMWare Tools to 10.3.10 ?

**Comment by generatives** [comment]
I'm experiencing very similar issues running Windows containers on Windows Server 2019, running on VMWare.

```
PS C:\Windows\system32> docker version
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Windows\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**Comment by antonyoni** [comment]
@SquallHalle I can confirm that rolling back to VMWare Tools to 10.3.10 has fixed the problem.

I decided to test this by only rolling back one of the nodes in a 2-node dev environment: node1 has 10.3.10 VMTools and node2 has 11.0.1. I deployed a stack across the two nodes. Node2 eventually fails with the `vmcompute.exe` error (same as above). `stack rm` removes the stack (services and network) from node1 but leaves them in a `Remove` state for node2. `Restart-Service docker` on node2 takes  about 30 seconds, but once it comes back up, the remaining stack services and network are removed from node2.

**Comment by hulltr1** [comment]
Same issues here, brand new 2019 build on ESXi 6.7u3, Docker 19.03.5. Container hangs after ~30 minutes. Anyone find a workaround or fix?

**Comment by yannovski** [comment]
We saw the exact same issue, upgrading to 11.0.6 resolved the issue.

[11.0.6 Release Notes](https://docs.vmware.com/en/VMware-Tools/11.0/rn/VMware-Tools-1106-Release-Notes.html)

> In VMware Tools 11.0.0, a new plugin called 'appInfo' was bundled. This new plugin runs every 30 minutes (can be configured by the guest administrator) to capture the information about running processes. For this, the plugin creates a remote thread in the target 64-bit process to capture the "command line" of the target process. If the 64-bit application of the process is not built with /LARGEADDRESSAWARE:YES, the "remote thread" crashes the application. For more information, refer KB 78550.
> 
> This issue is fixed in this release.

**Comment by thaJeztah** [comment]
Based on the comments above, it looks like this was resolved
