### ISSUE TITLE
Unfriendly docker run -p (--publish) syntax

### ISSUE THREAD

**Issue by pavel-the-best** [moby/moby#40485]
It's difficult to understand docker run -p syntax. (TO:FROM). It took a while for me to realize where is the "from" part and where is the "to" part. This syntax is not described in help. I think that it would be better for new users to create another syntax variant (FROM->TO). That syntax, in my opinion, is more user-friendly.

**Comment by AkihiroSuda** [comment]
Docker CLI (https://github.com/docker/cli) is not a part of Moby.

**Comment by cpuguy83** [comment]
We cannot chance this syntax. It would break so many users.

**Comment by pavel-the-best** [comment]
I mean adding alternative syntax
