### ISSUE TITLE
Overlay2 XFS readdir order variant on host and container

### ISSUE THREAD

**Issue by b-john** [moby/moby#40494]
**Description**
Hi--- I am using overlay2 and volume mounting an XFS file system on a RHEL machine. When creating files within the container, the container and host do not always display(readdir) the files in the same order from the host vs the container.

**Steps to reproduce the issue:**
1. Perform a volume mount on an XFS system with overlay2.
2. Create some files inside the container. 
3. On the host run "ls -l" to see the file order.
```bash
[root@myhost objects]# ls -l
total 1064
-rw-r--r--. 1 root root 235904 Feb 10 15:35 a.o
-rw-r--r--. 1 root root 167432 Feb 10 15:35 b.o
```
4. In the container run "ls -l" to see a variant order
```bash
[root@a1890a117ee3 objects]# ls -l
total 1064
-rw-r--r--. 1 root root 167432 Feb 10 15:35 b.o
-rw-r--r--. 1 root root 235904 Feb 10 15:35 a.o
```

**Describe the results you received:**
See above: Files are displayed in different order with any readdir command. (ls, find, etc.)

**Describe the results you expected:**
See above: File order is identical between host and container.

**Additional information you deem important (e.g. issue happens only occasionally):**
- Sometimes the order is identical. (I do the above in a loop and 30%ish of the time they don't match)
- I was able to reproduce the above with overlay as well as overlay2.
- I understand POSIX doesn't guarantee a readdir order; The XFS file system is deterministic and my problem here is the variation between host and container.
- There's no md5 difference between the files in the container & host. 
- The impact to me is this order impacts downstream scripts and builds which results in non-determinism in the end-result file or binary.

**Output of `docker version`:**

```
# docker version
Client:
 Version:           18.09.1-ol
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e32a1bd
 Built:             Thu Jun  6 14:55:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1-ol
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e32a1bd
  Built:            Thu Jun  6 14:47:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
```

**Output of `docker info`:**

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.1-ol
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
init version: fec3683
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-957.el7.x86_64
Operating System: Oracle Linux Server 7.6
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 23.39GiB
Name: facjenkinsl417
ID: PI7Y:GMFL:FVRY:I5IW:HOEF:4HYI:UW4K:52NK:3WP4:OMOT:QSM4:JWFT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Comment by thaJeztah** [comment]
I'd expect this to be an issue in the kernel; the docker "overlay2" drivers just mount directories using overlayfs, which is functionality provided by the kernel, so I'm not sure how we would be able to influence this.

When you write "files on the host" and "files in the container"; on the host, are you looking at the files from the container's rootfs (so somewhere in `/var/lib/docker/overlay...`) or are these files on the host, which you're adding to a Docker image (as part of `docker build`) after which you're browsing those files inside the container?

**Comment by b-john** [comment]
Files on the host which I'm volume mounting with docker run -v (rw,z).

Thanks Sebastiaan, let me know if there is any data I can grab or if I need to look to the [kernel](https://github.com/torvalds/linux/blob/master/drivers/of/overlay.c).

**Comment by thaJeztah** [comment]
> Files on the host which I'm volume mounting with docker run -v (rw,z).

In that case there's _literally_ nothing between the files on the host and the files inside the container. `-v <host-path>:<container-path>` is the equivalent to `mount --bind <host path> <path to container rootfs>`

However, the `z` option could potentially be involved, as that option will re-label files (not sure if that's causing the problem?). That option should be used with care, as it will relabel the original files on your host, so `-v $HOME:/container:z` could have, erm, "interesting" results

**Comment by b-john** [comment]
Removed 'z' option but still able to reproduce. Thanks Sebastiaan--- sounds like I need to go lower/remove docker from the stack. Appreciate the help!
