### ISSUE TITLE
docker restart unexpectedly

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#40504]
**Description**
my docker restart unexpectedly,i find some log info:

Feb 03 10:25:22 mgt02 dockerd[20987]: time="2020-02-03T10:25:22.686641160+08:00" level=info msg="Container c1a30fdaaafb549572a34b23c37016ab1bc5362b0b86867c0ece815ef18d4ed2 failed to exit within 10 seconds of signal 15 - using the force"
Feb 03 10:25:34 mgt02 dockerd[20987]: time="2020-02-03T10:25:34.018490700+08:00" level=info msg="Container c1a30fdaaafb failed to exit within 10 seconds of kill - trying direct SIGKILL"
Feb 03 10:32:13 mgt02 dockerd[20987]: time="2020-02-03T10:32:13.519952140+08:00" level=info msg="Container c1a30fdaaafb failed to exit within 10 seconds of kill - trying direct SIGKILL"

Feb 03 10:36:33 mgt02 dockerd[20987]: time="2020-02-03T10:36:33.045942120+08:00" level=info msg="Processing signal 'terminated'"
Feb 03 10:36:33 mgt02 systemd[1]: Stopping Docker Application Container Engine...
Feb 03 10:36:34 mgt02 systemd[1]: Stopped Docker Application Container Engine.

**Describe the results you received:**
the docker restart unexpectedly

**Describe the results you expected:**
resolve the bug

**Output of `docker version`:**
```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd
 Built:             Wed Jul 17 17:45:38 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:47 2019
  OS/Arch:          linux/arm64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 34
 Running: 30
 Paused: 0
 Stopped: 4
Images: 30
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-55-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: aarch64
CPUs: 16
Total Memory: 31.41GiB
Name: mgt01
ID: MVE3:TOHY:BNAP:AF3K:SV2N:GJMT:4CAJ:XPC3:7E4U:QTBH:RSK2:E5XT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 registry.icp.com:5000
 docker.inspur.com:5000
 registry-chongqing-test.inspurcloud.cn
 10.150.0.0/16
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Looks like a shutdown of the docker service was initiated from systemd. Docker itself doesn't control that, so something must've triggered / instructed systemd to shut down the docker service.

I'd suggest looking for earlier log entries in your system logs; perhaps they may give a clue what was triggering the shutdown (perhaps some scheduled task, or an upgrade?)

Given that this doesn't look like a bug in the docker engine itself, I'll close this ticket, but feel free to continue the conversation
