### ISSUE TITLE
COPY invalidates image caches on another machine

### ISSUE THREAD

**Issue by matti** [moby/moby#40513]
**Description**

Any image with COPY  long as it's on the same machine - when the image is pulled to another machine, the cached layers are invalidated after the copy

**Steps to reproduce the issue:**
```
git clone https://github.com/matti/docker-invalidate-repro
cd docker-invalidate-repro
docker-compose pull
docker-compose build
```

**Describe the results you received:**
Everything after COPY is not in cache. If you run the build again, then everything is in cache (because the image is now built by your docker daemon)

Only difference that could explain this in the `context/folder/file` is the timestamp, but if you `touch context/folder/file` that changes the timestamp, it doesn't invalidate (as expected). And since timestamps are different on every machine (the time when cloned), they would invalidate always, for everybody.

**Describe the results you expected:**
Everything after COPY should be in the cache.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens in all environments (mac, linux, etc)

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 20.05GiB
 Name: docker-desktop
 ID: YHXQ:F5M6:DV5W:LGID:E2TX:SPVF:RLLZ:S7M5:BMGR:JBSN:BVK5:7IJB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 487
  Goroutines: 975
  System Time: 2020-02-13T13:45:02.6602654Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Happens with docker for mac, ubuntu docker.io package, google cloud shell, google cloud build etc.

**Comment by matti** [comment]
Possibly related https://github.com/moby/buildkit/issues/1330

**Comment by thaJeztah** [comment]
Note that when using `docker-compose`, BuildKit is not used by default, unless you use the latest versions of compose, and have both `COMPOSE_DOCKER_CLI_BUILD=1` and `DOCKER_BUILDKIT=1` set.


Regarding the issue at hand; the build-cache is not reused between machines; there are some options though to use existing images that are pulled for the build-cache; one option is the `--cache-from` option, which is experimental in the classic builder, and requires some additional options when using buildkit (when building/pushing the image, it needs to add additional metadata to the image for verifying the build cache)

Some details in this issue: https://github.com/moby/moby/issues/39003#issuecomment-571473100

**Comment by matti** [comment]
Okay so with BUILDKIT envs it is possible to get this working.

```
DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t mattipaksula/invalidate-repro:buildkit_inline_cache context
docker push mattipaksula/invalidate-repro:buildkit_inline_cache
```
...
```
docker pull mattipaksula/invalidate-repro:buildkit_inline_cache
DOCKER_BUILDKIT=1 docker build --cache-from mattipaksula/invalidate-repro:buildkit_inline_cache context
```

I think that the documentation should mention that build cache is not reused between machines?

**Comment by matti** [comment]
okay, it does mention it:

```
To use an image as a cache source, cache metadata needs to be written into the image on creation. This can be done by setting --build-arg BUILDKIT_INLINE_CACHE=1 when building the image. After that, the built image can be used as a cache source for subsequent builds.
```
