### ISSUE TITLE
 Windows Server 2019 Win32: An attempt was made to create more links on a file than the file system supports

### ISSUE THREAD

**Issue by ivanguravel** [moby/moby#40511]
**Description**
On the some production environment , when multiple deployments happened i faced with the next issue:
```
hcsshim::ImportLayer - failed in Win32: An attempt was made to create more links on a file than the file system supports. (0x476)
```

**Steps to reproduce the issue:**
1. run docker on Windows
2. write simple script for force pullig docker images which containing the same layers inside. (Not sure that it's a correct approach to reproduce, maybe need to pull a lot of images with the same layers). 
```
  docker tag $originalTag "tmptag:$i"
  docker rmi $originalTag
  docker pull $originalTag
```
3. do a loop for multiple pulling of images which containing similar layers and leave it for some time

**Describe the results you received:**
failing docker pull process

**Describe the results you expected:**
I know about hard links limit in windows (1024 for NTFS) and also saw https://forums.docker.com/t/docker-and-link-limits/77568 , but this is production environment and
i'm looking for some workaround how to avoid this automatically. for now i'm fixing it with helps restart one of the cluster instances.

**Output of `docker version`:**
```
Client: Docker Engine - Enterprise
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        c92ab06ed9
 Built:             09/03/2019 16:38:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.8
  Git commit:       c92ab06ed9
  Built:            09/03/2019 16:35:47
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.1.0-8c33de7)

Server:
 Containers: 43
  Running: 40
  Paused: 0
  Stopped: 3
 Images: 40
 Server Version: 19.03.2
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.737)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 16GiB
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
`Azure, Azure Kubernetes Service, Windows nodes`

**Comment by thaJeztah** [comment]
@simonferquel @kevpar  PTAL

**Comment by turric4n** [comment]
Some news about this error? 

Things I do to avoid this error :

(On Windows Docker Environment)

`docker image prune -a` (This will remove dangling images and HardLinks)

Then docker pull again...

**Comment by immuzz** [comment]
Please check the latest status of this issue at Windows Containers official repo just announced for latest update on this : https://github.com/microsoft/Windows-Containers/issues/38 

This issue can be closed here as it pertains to Windows Containers on not Moby

**Comment by thaJeztah** [comment]
Thanks! to quote from that issue;

> This is a known issue. It has been fixed in Windows OS and backported to Windows Server 2019 (1809 & LTSC), 19H1 and 20H1(2004). This will be part of July 2020 Windows Server update.

closing it here
