### ISSUE TITLE
Docker Desktop, KB4532693 breaks SysWOW64 support in process isolation

### ISSUE THREAD

**Issue by jrad88** [moby/moby#40525]
Hi,

It seems Windows Update is at it again. The 2020-02 Cumulative update breaks docker on every machine and VM I've tested it on. This one is for Windows 10 1903. Running any 32 bit application will result in the same error code. For simplicity, here is a quick and easy way to reproduce. This is running latest Docker Desktop.

> docker run --isolation=process --rm -it mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-1903 powershell
> 
> PS C:> .\Windows\SysWOW64\cmd.exe
> PS C:> echo $lastexitcode
> -1073741502
> PS C:>

The important bit is process isolation. hyperv will work fine in my testing. That exit code is something to do with dll failing to load, my guess in the dark is because it's trying to load a 64bit version in to a 32bit application. Viewing in procmon you can see it run for a bit, load some system dlls and fail somewhere.

-1073741502 (STATUS_DLL_INIT_FAILED)

I've tried this on bare metal machines with just Windows + Docker installed, and also fresh hyperv instances with the latest windows updates.  

Uninstalling the offending KB does resolve the issue temporarily (until it gets pushed back to you)

**Comment by jrad88** [comment]
Potentially related reading (more guessing in the dark):

https://developercommunity.visualstudio.com/content/problem/916924/get-the-error-0xc0000142-with-dbghelp-100183620-on.html
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/4fd94e2b-5b9b-4f0c-8974-36256397946a/windows-19h1-sdk-dbghelpdll-does-not-load-on-windows-7?forum=windbg

**Comment by kirannhegde** [comment]
Hello, @jrad88  There is something wrong either with the latest Docker images or the latest updates that were pushed. I too am facing issues installing very simple software(such as Git) on a Windows Server 2019 container, which otherwise was working for a long time.

**Comment by thaJeztah** [comment]
We've seen other failures after recent Windows updates, e.g. https://github.com/moby/moby/issues/40468.

/cc @taylorb-microsoft @jterry75 for visibility

**Comment by Justin-Lessard** [comment]
Having the same issue with Microsoft Windows Server 2019 Standard Version 10.0.17763 Build 17763, running Docker Engine - Enterprise Version 19.03.5.

Also no need to use process isolation. I've reproduced with this command.

    docker run --rm -it mcr.microsoft.com/windows/servercore:1809 powershell
    PS C:> .\Windows\SysWOW64\cmd.exe

Uninstalling windows update KB4524244 fixes it.

**Comment by taylorb-microsoft** [comment]
Please see:  [https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im](https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im) for the latest status.

**Comment by jrad88** [comment]
Thanks for the quick turnaround, this indeed solves the issues I was having. 

I was curious how frequent we should expect this to be happening.  I think it's reasonable, given how the kernel is handling process isolation, that the container match the host kernel version to some degree.  It's another matter entirely to have to exactly match the version down to the UBR.  We're generating containers for the work we do and having to create and maintain new versions every month is going to cause a lot of scramble and downtime after updates roll out.

I guess I'm asking if we should expect this to be the new normal, or was this an isolated incident?

**Comment by taylorb-microsoft** [comment]
We are writing a blog to explain what and why this occurred as well as how we intend to better handle it in the future should such an event arise.   But we do not expect this to be a common or frequent occurrence.

**Comment by olljanat** [comment]
@taylorb-microsoft Thanks. Please also share link to it here.

I really wonder that how this is possible because my understanding from older discussions have been that Moby integration tests are used also inside of Microsoft to verify that new Windows versions does not break anything. Have I understood incorrectly or did this patch somehow manage to skip that testing?

**Comment by iskiselev** [comment]
Should be proper filtration of images in manifest in similar way as in #36327 to prevent this issue? Or some more complex way to affect only process isolation?
We need to run containers with process isolation on both patched and non-patched hosts. I can create manifest that will include images with both patched and non-patched base, but as I understand with current implementation of [checkImageCompatible](https://github.com/moby/moby/blob/b084ccda9d34e911c61a8a4c7f846e21dc12c3a9/distribution/pull_v2_windows.go#L125) it will not filter based on windows version 4th part.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
