### ISSUE TITLE
Different behavior between docker 1.13.1 and docker 18.03.0-ce

### ISSUE THREAD

**Issue by yuehliu** [moby/moby#40531]
**Description**
Encounter different behavior between docker 1.13.1 and docker 18.03.0-ce

**Steps to reproduce the issue:**
1. start a container using following command: docker run ... centos:7 /usr/sbin/init
2. then install mysql-server by following commands:
    yum install -y wget
    wget http://repo.mysql.com/mysql57-community-release-el7-8.noarch.rpm
    rpm -ivh mysql57-community-release-el7-8.noarch.rpm
    yum install mysql-server
    systemctl start  mysqld.service
3. After above actions, Running "systemctl restart mysqld" will block the terminal
4. Running "systemctl status mysqld" will encounter errors
5. All of these errors ONLY happened in docker 18.03.0-ce, It's OK if run them in docker 1.13.1

**Describe the results you received:**
[root@d7ebc5ca4de1 /]# systemctl status mysqld -l
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: activating (start) since Mon 2020-02-17 06:05:00 UTC; 35min ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html
  Process: 1386 ExecStart=/usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid $MYSQLD_OPTS (code=exited, status=0/SUCCESS)
  Process: 1371 ExecStartPre=/usr/bin/mysqld_pre_systemd (code=exited, status=0/SUCCESS)
   CGroup: /docker/d7ebc5ca4de1ad9d8042453097c56c60bc67e3d2ed5204457f983486bf674809/system.slice/mysqld.service
           └─1388 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Feb 17 06:05:00 d7ebc5ca4de1 systemd[1]: Starting MySQL Server...
Feb 17 06:05:01 d7ebc5ca4de1 systemd[1]: New main PID 1388 does not belong to service, and PID file is not owned by root. Refusing.
Feb 17 06:05:01 d7ebc5ca4de1 systemd[1]: New main PID 1388 does not belong to service, and PID file is not owned by root. Refusing.

**Describe the results you expected:**
[root@8337e83eba5e /]# systemctl status mysqld
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-02-13 15:20:38 UTC; 3 days ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html
 Main PID: 779 (mysqld)
   CGroup: /system.slice/docker-8337e83eba5eed73f62048c1e649802f4bf672ec6a405b30b78a71a9a5892e7e.scope/system.slice/mysqld.service
           └─779 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Feb 13 15:20:33 8337e83eba5e systemd[1]: Starting MySQL Server...
Feb 13 15:20:38 8337e83eba5e systemd[1]: Started MySQL Server.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
What are the exact options you're using to start the container? Running containerd inside a container requires the container to have additional permissions.

Both Docker 1.13.1 and 18.03 have reached EOL more than a year ago, and are no longer maintained (both versions have known, unpatched vulnerabilities).

Are you seeing the same problem on the current (19.03 at time of writing) release?

**Comment by yuehliu** [comment]
OK, I will try the same senario using 19.03. Due to 18.03 is already EOL, I'll close this issue firstly, if needed, I'll reopen it. Thank you.
