### ISSUE TITLE
Incorrect syntax highlighting in dockerfiles with escaped double quotes

### ISSUE THREAD

**Issue by JacksonKearl** [moby/moby#40536]
From https://github.com/microsoft/vscode/issues/90833

Windows dockerfiles require double quotes in `RUN` commands to be escaped, like `\"` (see: https://github.com/StefanScherer/dockerfiles-windows/tree/master/quotes).

Escaping a doublequote in vscode breaks the docker extension's syntax highlighting:
![screenshot of broken syntax highlighting](https://user-images.githubusercontent.com/6956487/74667423-450f3400-5171-11ea-9bca-c6b01106906f.png)

Steps to Reproduce:

1. Make a new Dockerfile and paste the following content:
```
FROM microsoft/windowsservercore:latest

RUN powershell Write-Host \"Hello world\"

COPY . .

**Comment by zhammer** [comment]
Thanks @JacksonKearl

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
