### ISSUE TITLE
msdeploy causes host system instability after installing KB4532691

### ISSUE THREAD

**Issue by pmartin-brierley** [moby/moby#40541]
Heavy usage of msdeploy.exe inside of a Windows Server Core container causes system instability of the host OS.  If the host OS has the wrong set of software installed, or certain windows updates, then msdeploy.exe will stop functioning inside of containers.  Running msdeploy.exe with no arguments will result in a crash, with exit code -1073741502.  The host system's storage will also become unstable, and the host will crash.

This happened to our system on 2/13/2020, after the following update was installed:
2020-02 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4532691)

I was able to replicate the above behavior on a Server Core 2019 VM running in Hyper-V on my laptop.  Installing the update broke msdeploy.exe in containers, removing the update fixed it.

**Steps to reproduce the issue:**
1. Run a windows server core image ltsc2019 on Windows Server Core 2019
2. In container, install MSDeploy (use dotnet-framework sdk image, and/or install vs_buildtools)
3. In container, run msdeploy with no arguments, check for expected output
4. Install KB4532691, reboot host
5. In container, run msdeploy with no arguments, should crash

**Describe the results you received:**

msdeploy crashes when run in a container, sometimes it can make the host unstable.

**Describe the results you expected:**

msdeploy should always work in a container, reguardless of the software installed on the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Evaluation Version 1809 (OS Build 17763.973)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.618GiB
 Name: WIN-IE03JUP7KLD
 ID: AZ44:2H6M:UD2C:PVFX:KK6P:GW2B:NIGI:YR4I:IZ3O:SMKZ:Y2RQ:7BNM
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Test on laptop uses Hyper-V

**Comment by thaJeztah** [comment]
Looks like the latest Microsoft patches caused quite some damage (e.g. https://github.com/moby/moby/issues/40525 also was introduced in the latest patches) 😞 


ping @taylorb-microsoft @jstarks

**Comment by thaJeztah** [comment]
@pmartin-brierley if you have a support contract with Microsoft, it might be good to open a ticket with them as well to get things prioritised.

**Comment by thaJeztah** [comment]
Also see https://github.com/moby/moby/issues/40525#issuecomment-587993478

> Please see:  [https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im](https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im) for the latest status.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
