### ISSUE TITLE
GitHub link on the "moby" homepage is dead

### ISSUE THREAD

**Issue by jschleus** [moby/moby#40569]
The GitHub link at the top of the [moby homepage](https://mobyproject.org/) is dead ("404 Not Found"):

 https://github.com/moby/moby/blob/moby/README.md

At least the following link works

 https://github.com/moby/moby/blob/master/README.md

**Comment by thaJeztah** [comment]
Looks like this should be fixed by https://github.com/moby/mobywebsite/pull/42, but perhaps the site was not yet redeployed.

@dmcgowan @justincormack any idea how to trigger a rebuild/re-deploy of the site?

**Comment by jschleus** [comment]
Ah, so probably not only a dead link but a dead page? The HTTP header says:

 `Last-Modified: Thu, 24 May 2018 00:11:15 GMT`

**Comment by tnir** [comment]
Is this description up to date? 🤔 
https://github.com/moby/mobywebsite#production

**Comment by jschleus** [comment]
Ah, yes. There I found that the probably according file `docs/_includes/links.html` was fixed 11 months ago. So maybe just a website regeneration (Jekyll run?) is missing.
