### ISSUE TITLE
Need to read ImagePush result for it to work

### ISSUE THREAD

**Issue by BrunoMCBraga** [moby/moby#40567]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
Currently using the Docker SDK for GO to build and push images to ECR on Amazon. Whenever i call ImagePush, if i don't take io.ReadCloser and read from it to the end, my images will not appear on ECR. If i do something simple as:

```go
io.Copy(ioutil.Discard, imagePushResult)
```
it works. 

**Steps to reproduce the issue:**
1. Call ImagePush to push image to ECR repo (have not tried with other repos)
2. Return after the call and don't bother with the io.ReadCloser returned by ImagePush
3. The image will not appear on the repository

**Describe the results you received:**

**Describe the results you expected:**
I expected the image to be on the repo regardless of how i handle the retured io.ReasCloser. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 0
  Paused: 0
  Stopped: 19
 Images: 5
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: SGU4:RG3S:FZPA:P67C:J3PQ:3WV5:T522:DART:YO5Y:J2VI:MSLA:JY7V
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 60
  System Time: 2020-02-22T19:29:09.8248016Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Pushing the images to AWS.

**Comment by cpuguy83** [comment]
This seems to be working as expected. Since the API is not asynchronous, the early return (and as such I'd expect closing the response) is considered a cancellation.

I will say I am on my phone and haven't looked deeply at this, but based on the description I'm not sure this should be unexpected.

**Comment by BrunoMCBraga** [comment]
@cpuguy83 thanks for the prompt response. Not complaining. Just weird and unexpected. Found out by sheer luck i guess.

**Comment by cpuguy83** [comment]
Understood.
I'm going to go ahead and close this because this is not something we can really change unless we introduce an async API (which we kind of do have with swarm services already).

Thank you! 😇
