### ISSUE TITLE
Docker loss ipv4 during build [#29588 again]

### ISSUE THREAD

**Issue by fraviemor** [moby/moby#40572]
The #29588 issue has been reproduced for me in last docker version (19.03.6).
I downgrade to 19.03.5 and still fails.

When i run a 'docker build' script, container and networks are created but docker0 interface lost ipv4 address and build fails with "getaddrinfo EAI_AGAIN" error.

Any idea?

**Comment by cpuguy83** [comment]
The PR you linked does not seems like it would be related.

If docker0 is losing it's address, then I would suspect NetworkManager is involved.
If so then try disabling it and see if that resolves the issue.

**Comment by fraviemor** [comment]
Sorry, i edit it with the correct issue number.

@cpuguy83 i have already tested disabling NetworkManager service and still fails. Downgrading docker and docker-compose too.

**Comment by fraviemor** [comment]
Ok, it seems that was a conflict with systemd-networkd daemon. My net manager is NetworkManager.
I stopped and disabled networkd daemon and docker is working ok now.
Thanks!
