### ISSUE TITLE
Pulling images results in EOF error

### ISSUE THREAD

**Issue by ZusorCode** [moby/moby#40578]
**Description**

Pulling any image results in an EOF error
```
PS C:\Users\Username> docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: unexpected EOF
```

**Steps to reproduce the issue:**
1. Pull image from docker hub

**Describe the results you received:**
EOF error instead of successfully pulling the image

**Describe the results you expected:**
Image is pulled successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: MN67:LXNP:YEY2:AKYH:IZ6V:S3B6:PSWV:N4O5:XB3X:4FWZ:AMJY:BV47
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 49
  System Time: 2020-02-25T15:32:54.055533794Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Windows 10 Docker for Windows

**Comment by AkihiroSuda** [comment]
Probably you need to configure proxy in Docker for Windows GUI

**Comment by ZusorCode** [comment]
What do you mean by that? I'm not behind any firewall or corporate proxy, are there still settings I need to configure?

**Comment by ZusorCode** [comment]
While trying to figure out what's going on I discovered that there's several strange things about my installation (even though I've done a full clean reinstall including resetting my entire network config and reinstall hyper-v).
I don't seem to have DockerNAT running on my system (I don't really understand what that is, sorry). When I try to list current networks it's not there
```
> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
305a80029a3d        bridge              bridge              local
1115d926cbd6        host                host                local
c5ca914edeea        none                null                local

> docker inspect nat
[]
Error: No such object: nat
```
And in Hyper-v there's no DockerNAT switch https://i.imgur.com/m0585di.png
I don't know if that has anything to do with my issue though.
I ran the microsoft troubleshooting script, here's the logs from that https://pastebin.com/8DmDY3rX

**Comment by thaJeztah** [comment]
Was your intent to run Windows containers or Linux containers? `nat` network is when using native Windows containers. You can switch Docker Desktop to Windows containers following the steps here; https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by ZusorCode** [comment]
For anyone who comes across this, it was caused by my FritzBox router.

https://github.com/docker/for-mac/issues/3493#issuecomment-616338458
