### ISSUE TITLE
single replica service update stops before new task

### ISSUE THREAD

**Issue by port22** [moby/moby#40589]
**Description**

Having an application scaled=1 which is ~2GB big, every service update first stops the service, then pulls the image and then starts the new task. Why is that so?

**Steps to reproduce the issue:**
1. run a big service
2. update it with a new image
3. wait for it

**Describe the results you received:**
Service is unavailable for as long as swarm schedules the update

```
ID                  NAME                  IMAGE                                         NODE                DESIRED STATE	CURRENT STATE             ERROR               PORTS
mqe9dvscxl4t        release_portal.1	  docker.corporate.intra/dev/portal:release   vm280            Running             Assigned 10 minutes ago
krfbj9rpmz93         \_ release_portal.1  docker.corporate.intra/dev/portal:release   vm280            Running             Shutdown 10 minutes ago

```
**Describe the results you expected:**
Most important thing I would require from a scheduler, is that it pulls the new image of the scheduled update in background, then starts a new task, and then, when the task is healthy, swarm-loadbalancer starts routing traffic to the new service, then stops routing to the old, then killing the old task.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:28:07 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
 Swarm: active
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Orchestration:
   Task History Retention Limit: 5
  Dispatcher:
   Heartbeat Period: 5 seconds
  Autolock Managers: false
  Root Rotation In Progress: false
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 Kernel Version: 3.10.0-1062.9.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.73GiB
 Debug Mode: false
 Registry: https://index.docker.io/v1/
```

**Comment by cpuguy83** [comment]
You can change the order by setting `--update-order`

      --update-order string                Update order ("start-first"|"stop-first") (default "stop-first")

Closing since this is working as expected and can be changed from the default, but feel free to comment. 😇

**Comment by port22** [comment]
thanks! I assumed the default would be `start-first`, which would make more sense as a sane default for most people without needing to append this option literally everywhere

**Comment by cpuguy83** [comment]
start-first was added later, which is why it's not default.
