### ISSUE TITLE
Does docker swarm perform well in production env? Are there still instability or network issues?

### ISSUE THREAD

**Issue by politoesolve** [moby/moby#40587]
I notice there are some articles or pages(like this https://github.com/moby/moby/issues/32195) mentioning network issues of docker swarm, like relatively large network latency between nodes, instability of nodes, blabla, have there issues been solved or improved?  Is it Ok to use docker swarm for micro-services in production environment?

**Comment by cpuguy83** [comment]
There are lots of improvements over the years. The only thing I could say is test it out.
There are many companies using swarm in production, but every environment is different.

I'm going to close this since there isn't really anything actionable here.
Thanks!
