### ISSUE TITLE
Cannot use white spaces with COPY

### ISSUE THREAD

**Issue by EricSalemi** [moby/moby#40602]
**Description**

Using white spaces in COPY arguments result in a error.

**Steps to reproduce the issue:**

Build minimal Dockerfile (Docker for Windows):

    # escape=`
    FROM mcr.microsoft.com/windows:1903
    COPY ["Dockerfile", "C:\Program Files\Dockerfile"]

**Describe the results you received:**

    Step 1/2 : FROM mcr.microsoft.com/windows:1903
     ---> 0a48f671c397
    Step 2/2 : COPY ["Docke rfile", "C:\Program Files\Dockerfile"]
    Error response from daemon: failed to process "[\"Docke": unexpected end of statement while looking for matching double-quote

**Describe the results you expected:**

I expect the build to run without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.657)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.83GiB
 Name: clswin01
 ID: V5UG:TY2O:N752:OLWP:UE3V:JRGT:OXFR:TPU3:MILF:MGOD:QCNI:NI37
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 38
  System Time: 2020-02-28T16:59:57.2201905+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  artifactory:8081
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Build executed in PyCharm over Docker remote API. Docker server is running on Windows 10 Pro 1903.

**Comment by EricSalemi** [comment]
JSON needs the backslashes to be escaped.

This minimal example works:

    # escape=`
    FROM mcr.microsoft.com/windows:1903
    COPY ["Dockerfile", "C:\\Program Files\\Dockerfile"]

**Comment by thaJeztah** [comment]
👍 Just booted a Window machine to try, and that worked indeed;

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/servercore:1809
 ---> 723ff6f8e0ef
Step 2/2 : COPY ["Dockerfile", "C:\\Program Files\\Dockerfile"]
 ---> 906b9c1f7912
Successfully built 906b9c1f7912
Successfully tagged test:latest
```
