### ISSUE TITLE
Docker For Mac new UI restricts using synthetic.conf links

### ISSUE THREAD

**Issue by federico-piazza** [moby/moby#40627]
Using the new UI of Docker for Mac restricts the usage synthetic links in Mac Catalina

On the previous Docker For Mac UI, we were able to set a manual path for Resource -> File Sharing. However after the new re-skin when we set up a path, the UI automatically expand the path when they are symbolic links.

For the case of Mac Catalina, when we use synthetic links (through synthetic.conf) then the UI expand the link to the real folder breaking this way the logic we have. However, the old UI allowed manual entry without expanding the link and it allowed us to work.

**Steps to reproduce the issue:**
1. In Mac Catalina, create a file `synthetic.conf` inside `/etc`
2. Add a synthetic link on the root directory like this (below creates the symbolic link `/datadrive` pointing to my home directory): 

```
datadrive	System/Volumes/Data/Users/federicop/datadrive
```

3. Create any mount directory using `/datadrive`. For instance in our docker compose we used:

```
  aerospike:
    image: "aerospike/aerospike-server:${AEROSPIKE_VERSION:-4.2.0.4}"
    volumes:
      - /datadrive/aerospike:/opt/aerospike/data
```

**Describe the results you received:**
On the new Docker for Mac UI, when we start our docker compose it says that it cannot mount the directory on `/datadrive/aerospike` and we must add it to File Sharing (but we cannot add it because of the automatic link expansion)

**Describe the results you expected:**
We should be able to put a symbolic link in File Sharing and avoid the link expansion

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
The mac UI is proprietary software and unrelated to this repo. Please open an issue in https://github.com/docker/for-mac .

**Comment by federico-piazza** [comment]
@AkihiroSuda thanks for letting me know. I leave here the link to the Docker For Mac repo issue for people that come here 

https://github.com/docker/for-mac/issues/4341
