### ISSUE TITLE
[Docker 19.03.7] - overlay/overlay2 shows Backing Filesystem as <unknown>

### ISSUE THREAD

**Issue by mtrensch** [moby/moby#40626]
**Description**

We are manually building docker / moby runtime in a project and after updating to 19.03.7 we remarked that the Backing Filesystem for overlay2 is now shown as `"<unknown>"` while it was `"extfs"` in 19.03.6.

**Steps to reproduce the issue:**
1. Install docker 19.03.7
2. Execute "docker info"

**Describe the results you received:**
```
Server:
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
```

**Describe the results you expected:**
```
Server:
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
```

**Additional information:**

This seems have been introduced with commit 5b6f2e1c59b442a118d1bfb6c76c01f0d14a26cb which removes the filesystem check and now ommits setting backingFs variable, making it default to `"<unknown>"`

I am not a Go programmer, but probably something like the following can be readded in overlay.go in both overlay drivers:
```
fsMagic, err := graphdriver.GetFSMagic(testdir)
if err == nil {
    if fsName, ok := graphdriver.FsNames[fsMagic]; ok {
        backingFs = fsName
    }
}
```

**Comment by AkihiroSuda** [comment]
@kolyshkin PTAL?

**Comment by devplayer0** [comment]
Just ran into this while upgrading and activating `overlay2.size` `storage-opt`, went through and discovered the exact cause of the bug myself - should have checked the issues tab first! 😅

**Comment by tao12345666333** [comment]
Any update?

**Comment by lf1029698952** [comment]
when I set docker storage-opt: overlay2.size=50G, docker start error:
```
dockerd: failed to start daemon: error initializing graphdriver: Storage Option overlay2.size only supported for backingFS XFS. Found <unknown>
```
because docker can't unrecognized Backing Filesystem, backingFS is <unknown>.
downgrade to 19.3.05 to resolve it.
Looking forward to fixing the problem as soon as possible.

**Comment by tao12345666333** [comment]
Opened a PR to fix it #40650

**Comment by haniokasai** [comment]
This issue is not resolved at 19.03.8.(There is no problem on 19.03.6)
```
 Storage Driver: overlay2
  Backing Filesystem: xfs

```

```
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 362
  Running: 177
  Paused: 0
  Stopped: 185
 Images: 27
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 26.79GiB
 Name: mirm_dockernode
 ID: XWSI:EE7Y:C36H:K5BM:T4IM:HDA5:KCMF:3TG5:B2RI:ZZJP:ECHR:YWLH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Therefore, I cannot use storage-opt even pquota is enabled.
```
# docker create --name mysql --memory=1000mb  --storage-opt size=2G -e BITNAMI_DEBUG=true -e MYSQL_ROOT_PASSWORD=test 
Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option
```

**Comment by thaJeztah** [comment]
19.03.8 was a security release and only has one change; the fix for this is scheduled to go out with the patch release after that (19.03.9)

**Comment by haniokasai** [comment]
@thaJeztah Thank you for letting me know.
I will update after 19.03.9 released.
