### ISSUE TITLE
Add support for --ulimit...to swarm mode 

### ISSUE THREAD

**Issue by gm0neyl0ve** [moby/moby#40639]
Based off this issue and the request by @theJeztah
https://github.com/moby/moby/issues/25209

    services:
          computer_simulation:
             ulimits:
                 rtprio:
                     soft: -1
                     hard: -1

**Comment by mightygorga** [comment]
Isn't this a bug? The [Compose File Reference](https://docs.docker.com/compose/compose-file/#ulimits) states that this should work with Swarm Mode.

**Comment by nartamonov** [comment]
> Isn't this a bug? The [Compose File Reference](https://docs.docker.com/compose/compose-file/#ulimits) states that this should work with Swarm Mode.

I've been fooled by incorrect docs too. It should be note that ulimits isn't currently supported in swarm mode.

**Comment by olljanat** [comment]
@thaJeztah I assume this one can be closed because https://github.com/docker/cli/pull/2712 was merged?
