### ISSUE TITLE
Why umount at host is successful while docker container is still writing into that disk?

### ISSUE THREAD

**Issue by bilibilixxyy** [moby/moby#40642]
I have been trying to research this problem for days but still not sure about why. If someone can help, I would really appreciate.

* There is a `disk A` mounted as `/mnt/x/y` at host
* Docker container has a bind mount: `/mnt/x/y:/y`
* Docker container is keeping writing into `/y`
* Execute `umount /mnt/x/y` at host
   * Expect this command failed with target is busy as docker container is keeping writing into `/y`.
   * Actual result is that this umount is successful, and I can confirm that docker container is still writing into `disk A`.

This is really strange to me. Does anyone know something about it? Thanks.

**Comment by cpuguy83** [comment]
An unmount causes an unmount in the mount namespace the call was executed from.
Containers each get their own mount namespace, which means they essentially get their own copy of the mount table.

Docker by default sets mounts to use private mount propagation. This means, effectively, that changes to the mount in the origin (host) namespace will not propagate to the container and vice-versa.
You can setup different levels of propagation.

https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

**Comment by bilibilixxyy** [comment]
Hi @cpuguy83 , thank you very much for your reply.

Yes, I got you. But even if I set the container mount to be `/mnt/x/y:/y:slave`. Unmounting at host is still successful while container still writs into `/y`. By running `df` inside container, I can see that the `disk A` is actually mounted to `/y` directly.

Our goal is to make sure data is not corrupted by performing unmouting before detaching disk from host. At the same time, we kind of not wanting to stop this docker container to save some downtime. Since unmount at host was successful, we thought it was probably fine initially. However, we realized that it can be a problem since container was still writing into `disk A`. 

Do you have any suggestions? Or the safest way is to stop containers? Thank you. Have a nice day.

**Comment by cpuguy83** [comment]
Can you check the actual propagation on the mount?
You'll need to parse /proc/mountinfo to get that.

**Comment by bilibilixxyy** [comment]
Yes, I executed below commands on the host. Initially there is `master:130`, after unmounting on the host, `master:130 ` disappears. And it looks like container at pid 1234 can still write into disk `/dev/sdc`?
```
$  cat /proc/1234/mountinfo | grep xxx 
838 462 8:32 / /xxx rw,relatime master:130 - ext4 /dev/sdc rw,discard,errors=panic,data=ordered

$ sudo umount /mnt/disks/mysql
$ cat /proc/1234/mountinfo | grep xxx 
837 461 8:32 / /xxx rw,relatime - ext4 /dev/sdc rw,discard,errors=panic,data=ordered
```

**Comment by cpuguy83** [comment]
Does the container have the mount active while you unmount?
Typically I would expect an error like `device or resource busy` in this case, but there may be some rules here wrt mount propagation and how the error might be handled.
