### ISSUE TITLE
'docker rm --force' to succeed when containers already deleted

### ISSUE THREAD

**Issue by mleonhard** [moby/moby#40640]
## Desired Behavior
I need the `docker rm --force` command to exit with success if the specified containers don't exist.  This analogous to the `rm -f` shell command.
```
$ docker rm --force nonexistent_container ; echo $?
0
```
## Current Behavior
Currently, the command exits with status 1 if no containers were deleted.
```
$ docker rm --force nonexistent_container ; echo $?
Error: No such container: nonexistent_container
1
```

## Why I need this change
I am calling this command in a cleanup script.  I need to be able to run the script repeatedly, without creating any containers in between runs.  The script needs to stop and report an error if `docker rm --force` cannot do what it needs to do.  For example, if it cannot connect to dockerd.  But if the containers are already deleted, then the script needs to continue.  With the current behavior of `docker rm --force`, the script must perform its own check for containers before calling `docker rm --force`.  This is extra code that I would like to delete.

**Comment by AkihiroSuda** [comment]
Should be proposed to https://github.com/docker/cli
