### ISSUE TITLE
Issue Building Linux Container with Multi-Platform Base Image

### ISSUE THREAD

**Issue by mikemercer** [moby/moby#40655]
**Description**

We have a Windows Server 2019 Azure VM with Docker EE installed and the experimental features enabled to build Linux containers. 

This Server appears to have an issue building Linux containers instead of Windows Containers when using multi-platform base images (in our case mcr.microsoft.com/dotnet/core/runtime:3.1). The build succeeds and successfully pushes to an Azure Container Registry (ACR), but as a Windows Container. Attempting to pull it from the ACR results in the build failing to run.

Replacing the base image with a Linux only base (i.e. mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim) builds/pushes successfully and shows as a Linux container in ACR.

**Steps to reproduce the issue:**

- Build Azure VM capable of Nested Virtualisation (any v3 size)
- Follow guide to install docker ee and enable experimental features (https://bcthomas.com/2019/02/getting-started-with-linux-containers-on-windows-server-2019/#enable-linux-container-support)
- Dockerfile using multi-platform base image:
 
```dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:3.1
 
ARG configuration=Test
COPY bin/$configuration/netcoreapp3.1/publish app/
 
ENTRYPOINT ["dotnet", "app/app.dll"]
```

- Docker build and attempt to use the built container

**Describe the results you received:**
A windows Container

**Describe the results you expected:**

A Linux Container 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     true)
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows: 
  LCOW: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 8GiB
 Name: 
 ID: 
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
I'm not sure how the builder works in this regard (windows server building linux containers)... but I do know that Docker's image store does not support multi-platform images.

I have a fix (work-around, really) for this for the buildkit builder... but I'm not sure how this would affect the Windows builder.
https://github.com/moby/moby/pull/40629

**Comment by cpuguy83** [comment]
ping @tonistiigi

**Comment by thaJeztah** [comment]
I guess this needs the `--platform` flag to be specified when building, so something like `docker build --platform=linux` or `docker build --platform=linux/amd64`. 

please note that LCOW is an experimental feature, and has known limitations / issues; currently no active work is done on development (see https://github.com/moby/moby/issues/39533)

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
