### ISSUE TITLE
Stack creates task with wrong arch

### ISSUE THREAD

**Issue by mcaulifn** [moby/moby#40698]
**Description**

docker stack deploy attempts to launch amd64 image on arm platform.

**Steps to reproduce the issue:**
1. Create swarm of arm devices.
2. Create and launch stack (example uses `grafana/grafana` image)
3. Container not scheduled.

**Describe the results you received:**
Task shows the following error:
`no suitable node (unsupported platform on 2 nodes)`

**Describe the results you expected:**
Task scheduled on one of the swarm nodes

**Additional information you deem important (e.g. issue happens only occasionally):**
On the first create of the stack, the task was started successfully. After an update, it no longer starts. I have attempted to delete the service and redeploy with the same results. Stack was created using Portainer. Same thing happens when

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c19
 Built:             Wed Mar  4 01:55:10 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c19
  Built:            Wed Mar  4 01:49:01 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 4ed3btyi3zt59h5l0mvbrfc0r
  Is Manager: false
  Node Address: 192.168.1.14
  Manager Addresses:
   192.168.1.13:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.97-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 975.6MiB
 Name: srv02
 ID: 3F5O:GLNP:FLQ7:4E6L:DTSR:47RT:XQCT:SAFK:TUXG:NDBU:CDEL:NYN6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Both nodes are Pi3s.

**Comment by thaJeztah** [comment]
are you seeing the same problem when using one of the other tags of that image (instead of `:latest`)? The `:latest` tag of that image is not multi-arch, so only supports amd64; https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-27a2e8121b747f9688114623be231946f2fccee715b6ea373f48f878327e8390?context=explore

**Comment by mcaulifn** [comment]
that did it. i bet i pulled an image that had that tag the first time. 🤦‍♂
