### ISSUE TITLE
why i have two processes of containerd

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#40690]
**Description**
i have a containerd service,it has a process of /usr/lib/containd 
but when i start docker,i have another process of containerd :
containerd --config /var/run/docker/containerd/containerd.toml --log-level info
i want my docker to use the process of  /usr/lib/containd  not containerd --config
how do i use the /usr/lib/containd ,how to modify the config of dockerd?

**Steps to reproduce the issue:**
1. have a docker 18.06
2. upgrade docker to 18.09
3. have a containerd service

**Describe the results you received:**
i want my docker to use the process of  /usr/lib/containd  not containerd --config

**Describe the results you expected:**
i want my docker to use the process of  /usr/lib/containd  not containerd --config

**Output of `docker version`:**

```
Client:
 Version:           v18.09.8-ce
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Fri Jul 19 05:03:03 2019
 OS/Arch:           linux/mips64le
 Experimental:      false

Server:
 Engine:
  Version:          v18.09.8-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Fri Jul 19 04:50:10 2019
  OS/Arch:          linux/mips64le
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 494
 Running: 92
 Paused: 0
 Stopped: 402
Images: 4335
Server Version: v18.09.8-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb.m
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f-dirty
init version: fec3683
Kernel Version: 3.10.0-862.9.1.ns7_4.37.mips64el.debug
Operating System: NeoKylin Linux Server 7.0 (loongson)
OSType: linux
Architecture: mips64el
CPUs: 8
Total Memory: 63.09GiB
Name: master1
ID: 7DT4:UISK:QJAB:NNY3:YSHY:PYBE:3NH7:GZTT:W2HF:UIK2:AEET:DAGX
Docker Root Dir: /opt/cke/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 docker.inspur.com:5000
 registry-lx.inspurspring.com
 registry.icp.com:5000
 10.150.0.0/16
 127.0.0.0/8
Live Restore Enabled: true
```

**Comment by thaJeztah** [comment]
Looks like you have a non-official package installed (the official packages don't support mips64el). There was a fix for this in https://github.com/docker/docker-ce-packaging/pull/298, which is included in the official 18.09.3 release and up; could you check your systemd unit file to see if it contains those changes?

**Comment by timyinshi** [comment]
@thaJeztah thanks,i modify the docker.service,i have resolved the proplem.

**Comment by thaJeztah** [comment]
If the package you're using was packaged by your distribution (NeoKylin Linux), it may be worth opening a ticket with them so that they can fix the package
