### ISSUE TITLE
Docker Desktop 2.2.0.3 on Windows 10 1909 with Linux Containers, randomly assign exposed ports on service, not able to access

### ISSUE THREAD

**Issue by ncresswell** [moby/moby#40700]
Docker Desktop 2.2.0.3, Windows 10 Enterprise 1909, Set to use Linux Containers.

Initialized the single node as a swarm cluster (docker swarm init).

create a single replica service called nginx, using the image nginx, expose port 80 of the container letting docker randomly select the host port (docker service create --publish 80 nginx)

Service deploys, however i am unable to browse it via its randomly assigned port (30001 in my case).

If i remove the service and redeploy it exposing as port 80 externally (on ingress) then it works fine. (docker service create --publish 80:80 nginx).

Also works fine on 8080, and even 30001 (when statically assigned); Its only the dynamic port assignment that fails to successfully expose.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
