### ISSUE TITLE
HTTP logging driver

### ISSUE THREAD

**Issue by sosedoff** [moby/moby#40701]
Im not sure if there's a proposal or maybe even an ongoing work to get a new logging driver implementation going in docker. Particularly a HTTP driver would be a pretty good general purpose solution to send logs to a HTTP/HTTPS endpoint without need of a sidecar container, especially when running in ECS Fargate. 

Docker comes with a few logging drivers that utilize (directly or not) HTTP delivery method, with Splunk (https://github.com/moby/moby/blob/master/daemon/logger/splunk/splunk.go) being the only option on Fargate. I'm interesting in getting the baseline driver implementation going, however, i'm curious if any similar proposals or PRs have ever been considered? Maybe there's a specific reason for HTTP driver being excluded from the docker distribution.

Thoughts? I'd like to help out.

**Comment by cpuguy83** [comment]
Fargate doesn't support cloudwatch?
What does an HTTP driver look like? What's the protocol?

I'm not very keen on including another driver since you can run a driver as a plugin.
Also see https://github.com/moby/moby/issues/40517

**Comment by sosedoff** [comment]
Fargate does support cloudwatch, however additional setup is needed to ship those logs into another system, its actually easier to use awsfirelens driver instead, via sidecar configuration. Such setup works but is not ideal since it does not provide a way to configure format. 

As for logging to HTTP endpoint - it would use a similar format to splunk or papertrail, i didnt put too much thought into yet. It could send logs in text/json format and include tags/labels. AFAIK Fargate does not support docker plugins.

**Comment by cpuguy83** [comment]
What I don't want to do is invent a protocol. This can be done through a custom plugin.
I couldn't speak to how this might work with Fargate.

**Comment by cpuguy83** [comment]
Based on other mantainers 👍  to my last comment, I'm going to close this. If there's some lightweight/generic protocol that already exists that we are missing we could look at including it, but I'm also not really wanting to accept new logging drivers in-tree.

I would be absolutely ecstatic to move all log handling out of the daemon and thus easily replaceable by anyone with whatever they need. Would love some help on this. See #40517
