### ISSUE TITLE
RFC: add GPL binaries (fuse-overlayfs and slirp4netns) to docker-rootless-extras.tgz

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40706]
The next version of Rootless Docker will support `fuse-overlayfs` storage driver (https://github.com/moby/moby/pull/40483) for providing overlayfs functionality on non-Ubuntu/non-Debian kernels.
The storage driver requires [`fuse-overlayfs`](https://github.com/containers/fuse-overlayfs) binary (GPL3) to be installed on the host.

However, a concern was once raised for putting GPL binaries to the `docker-rootless-extras.tgz` archive when we discussed putting `slirp4netns` binary (GPL2) to the archive: https://github.com/moby/moby/pull/38050#pullrequestreview-193039398 .
(So currently we are distributing VPNkit instead of slirp4netns, with the penalty of the [throughput](https://github.com/rootless-containers/rootlesskit/tree/v0.9.2#network-drivers) and 
 [the multiarch issue](https://github.com/moby/moby/blob/37defbfd9b968f38e8e15dfa5f06d9f878bd65ba/Dockerfile#L325).)

Can we reconsider putting GPL binaries to the archive?
IIUC it doesn't matter as long as the license files are included in the archive along with the binaries.

e.g.
```console
$ tar tzf docker-rootless-extras-20.03.0.tgz 
docker-rootless-extras/
docker-rootless-extras/fuse-overlayfs
docker-rootless-extras/slirp4netns
docker-rootless-extras/rootlesskit-docker-proxy
docker-rootless-extras/rootlesskit
docker-rootless-extras/dockerd-rootless.sh
docker-rootless-extras/docs/
docker-rootless-extras/docs/README.md                 <-- this file explains which license applies to which files
docker-rootless-extras/docs/LICENSE.Apache-2.0
docker-rootless-extras/docs/LICENSE.GPL-2.0
docker-rootless-extras/docs/LICENSE.GPL-3.0

**Comment by AkihiroSuda** [comment]
@thaJeztah @StefanScherer @tianon PTAL

**Comment by thaJeztah** [comment]
Asked about this internally, and "legal" would prefer GPL binaries to be packaged separately 😅. Any suggestions how to do so (and still make it as easy as possible to install?).

We could add installing directly from upstream https://github.com/rootless-containers/slirp4netns/releases to the script?

**Comment by tianon** [comment]
Could we make a separate `gpl-extras` bundle?
