### ISSUE TITLE
Remove XDG directories from rootless mode

### ISSUE THREAD

**Issue by andrew-aladev** [moby/moby#40708]
Please assign this issue to Akihiro Suda @AkihiroSuda, [the following commit](https://github.com/moby/moby/commit/ec87479b7e2bf6f1b5bcc657a377c6e6a847574f) is the reason.

[The following issue](https://github.com/containers/storage/issues/532) related to `buildah`.

**Description**

Docker and buildah today can work in rootless mode on **desktop** with **systemd lingering mode** only. I am sure that both docker and buildah should not depend on any imaginary freedesktop standard. `XDG_*` directories doesn't exist on server and are not stable across sessions on desktop without systemd or with lingering mode disabled.

**Steps to reproduce the issue:**
1. Make login using `ssh host`.
2. `XDG_RUNTIME_DIR = /run/user/1000`.
3. `mount | grep /run/user`:
`none on /run/user/1000 type tmpfs (rw,relatime,mode=700,uid=1000)`
4. `sudo umount /run/user/1000`.
5. `exit`.
6. Make login using `ssh host` once again.
7. `mount | grep /run/user`:
`none on /run/user/1000 type tmpfs (rw,relatime,mode=700,uid=1000)`

We can see that `/run/user/1000` was re-mounted.

Please remove `XDG_*` directories from docker code. I will help to backport it to buildah. Thank you.

**Comment by AkihiroSuda** [comment]
> Docker and buildah today can work in rootless mode on desktop with systemd lingering mode only.

Not true, at least for Docker.

If your `$XDG_RUNTIME_DIR` is configured by systemd, it is true that you need to enable lingering mode, but you don't need to use desktop.
If your `$XDG_RUNTIME_DIR` isn't configured by systemd, you don't need to enable the lingering stuff.

Also note that `$XDG_RUNTIME_DIR` can be set to an arbitrary path without systemd running on the host, and there is no code path that fallbacks to `/run/user/...` in Docker. (You can confirm by running `git grep /run/user`) 
Actually, we are running Docker with `XDG_RUNTIME_DIR=/tmp/docker-${uid}` and without systemd on CI: https://github.com/moby/moby/blob/37defbfd9b968f38e8e15dfa5f06d9f878bd65ba/hack/make/.integration-daemon-start#L83

**Comment by AkihiroSuda** [comment]
Even if we avoided using XDG dirs, anyway you need to use linger mode to keep user processes running on systemd hosts.

**Comment by andrew-aladev** [comment]
> Not true, at least for Docker.
> If your `$XDG_RUNTIME_DIR` is configured by systemd, it is true that you need to enable lingering mode, but you don't need to use desktop.
> If your `$XDG_RUNTIME_DIR` isn't configured by systemd, you don't need to enable the lingering stuff.

I lost a bunch of CPU time because of this issue. Than I lost a bunch of time to debug what is the reason. Than I tested a fix on several systems **without systemd**, **with systemd** and **with systemd linering mode**. I suffered enough.

I've provided a way how to reproduce issue. Please try.

`XDG_*` directories are not stable across user sessions and this behaviour is **known be design**. Lingering mode in systemd is just a dirty hack. The commit above made both docker and buildah not stable across user sessions.

Both docker and buildah should be stable across user sessions by default so `${HOME}/.local/share` will be a good unix/linux standard path.

> Also note that `$XDG_RUNTIME_DIR` can be set to an arbitrary path without systemd running on the host, and there is no code path that fallbacks to `/run/user/...` in Docker. (You can confirm by running `git grep /run/user`)

Yes, buildah itself has a broken fallback path, we will try to fix it.

> Actually, we are running Docker with XDG_RUNTIME_DIR=/tmp/docker-${uid} and without systemd on CI:

You will receive many angry users like me when rootless mode will become popular. Default settings should work on any system in the same way.

[The pull request](https://github.com/moby/moby/commit/ec87479b7e2bf6f1b5bcc657a377c6e6a847574f#diff-d3f6b8612a6b46337de40bb2010208b8R146) is not a solution too. Re-mount hammer from initialization system don't care about sticky bits. It just re-mounts and that's it. All data inside `XDG_*` will be lost.

You can easily reproduce this behaviour by using the following steps:

1. `ssh host`
2. `chmod +t /run/user/1000`
3. `touch /run/user/1000/fit`
4. `exit`
5. `ssh host`

Please try. You will see that content from `/run/user/1000` was lost.

Please remove `XDG_*` and replace it with canonical pathes used by 95% of unix/linux software: `${HOME}/.local/cache`.

**Comment by AkihiroSuda** [comment]
It seems you have issues only with buildah, not Docker.

If you use Rootless Docker, it is inevitable to enable lingering anyway, because otherwise the daemon doesn't even start automatically on system startup. And yet the next version will more depend on systemd user instances to support cgroup (v2) as in Podman.
So, the XDG issue you are claiming should be irrelevant to Docker users.

With regard to buildah, I have never contributed to it, I don't use it, I'm not familiar with it, and I'm not responsible for it at all, even if they copied my codes.

> ${HOME}/.local or ${HOME}/.cache.

You can set `$XDG_RUNTIME_DIR` as you like, but you are responsible to clean up the directory on every system startup.

**Comment by andrew-aladev** [comment]
> It seems you have issues only with buildah, not Docker.

I've provided steps how to reproduce the issue that is not related to third party software. I tried to present that `XDG_*` usage is not suitable for software **like docker** by design. I am sure that you have understand everything, but want just to ignore it.

Please reopen this issue. It is not resolved or closed.

> If you use Rootless Docker, it is inevitable to enable lingering anyway, because otherwise the daemon doesn't even start automatically on system startup. And yet the next version will more depend on systemd user instances to support cgroup (v2) as in Podman.
> So, the XDG issue you are claiming should be irrelevant to Docker users.

The commit we are talking about was the first commit that **nailed** docker to systemd. This is not acceptable. We need to do the following:

1. Tell authors of this project that Akihiro Suda silently decided to make docker systemd only.
2. Add warning into readme and docs that new versions of docker is systemd only.
3. Tell maintainers of docker all over the world to mask docker for systems without systemd.
4. Force users to enable mandatory linger mode support.

@thaJeztah Hello Sebastiaan, I know that you are one of core docker developers. Please clarify that new versions of docker are systemd only. I can help to make docker systemd free again.
