### ISSUE TITLE
Move docker-install/rootless-install.sh (except the curl part) to this repo + rewrite in Go

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40707]
The current rootless installer (https://get.docker.com/rootless) is maintained in https://github.com/docker/docker-install/blob/master/rootless-install.sh .

However, maintaining version-specific logic (e.g. storage driver, cgroup driver..) in the single shell script is hard.

So I suggest moving 90% of `rootless-install.sh` except the curl stuff into this repo.

The `rootless-install.sh` itself will remain in the `docker-install` repo, but will execute version-specific script like `docked-rootless-setuptool` contained in `docker-rootless-extras-20.03.0.tar.gz`.

I also suggest rewriting the script in Go, but it can be worked out later separately.

**Comment by thaJeztah** [comment]
I'd be ok with moving the script in this repository; we'll have to look how to make sure it's re-deployed when changes are needed likely?

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/40924
