### ISSUE TITLE
"Unable to remove filesystem" 

### ISSUE THREAD

**Issue by apenney** [moby/moby#40729]
Every so often, when using docker run we get:

```
time="2020-03-20T21:35:49Z" level=error msg="Error waiting for container: unable to remove filesystem for 49a885a6b785d34c3a5663a9b34ef908d5a210ae40ef40eda835afdefc73dab8: unlinkat /ephemeral0/docker/containers/49a885a6b785d34c3a5663a9b34ef908d5a210ae40ef40eda835afdefc73dab8: directory not empty"
```

When I look inside that directory:

```
root@ip-10-0-6-38:/ephemeral0/docker/containers/49a885a6b785d34c3a5663a9b34ef908d5a210ae40ef40eda835afdefc73dab8# ls -latr
total 8
-rw-r----- 1 root root    0 Mar 20 21:35 49a885a6b785d34c3a5663a9b34ef908d5a210ae40ef40eda835afdefc73dab8-json.log
```
It appears like the docker logs themselves are stopping it from successfully terminating.

**Steps to reproduce the issue:**
1.  I'm not sure, it's not every run
2.  docker run a container
3.  watch it return a 125 exit code

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a fairly unhelpful bug report, and I apologize for that, but I don't know how to make it happen on demand.  It only happens on a fraction of runs for us.  (We do a lot of docker run).  I'm just hoping to raise awareness in case anyone else has seen this.

**Output of `docker version`:**

```
root@ip-10-0-6-38:~# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
                                                           
Server: 
 Containers: 10     
  Running: 9         
  Paused: 0  
  Stopped: 1                
 Images: 4
 Server Version: 19.03.8                                   
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1063-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 59.96GiB
 Name: ip-10-0-6-38
 ID: ZXGJ:KRIK:FISP:Y75A:S7MS:2DJH:2ERC:4J6C:WNGV:YYYE:P6FW:65G4
 Docker Root Dir: /ephemeral0/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on Ubuntu 18.04, running in AWS.  Mostly seen on i3 instances (lots of local storage)

**Comment by apenney** [comment]
I tried rolling the daemon back to 19.03.6 (leaving everything else the same, cli etc, was .8) and still ran into this problem, where it leaves the single json.log file behind.  My next test will be to switch to journald and see if that fixes the problem (because if we don't write these logfiles, they can't break docker run).

Not sure what additional debug info I can give, other than to say we see this fairly frequently.

**Comment by thaJeztah** [comment]
@apenney were you able to narrow down the problem?

Some quick thoughts;

- are you running kubernetes?
- are you using tooling to collect container logs, such as https://github.com/gliderlabs/logspout, or a tool that directly uses the json-file logs ?

My thinking there is; if something was reading the json-file log at the moment that the container was removed, possibly that locked the file, and prevented the container from being fully removed.

**Comment by thaJeztah** [comment]
Closing as this went stale
