### ISSUE TITLE
Docker stats memory doesn't include tmpfs usage

### ISSUE THREAD

**Issue by RuRo** [moby/moby#40727]
**Description**

The `MEMORY USAGE` and `MEM %` columns in `docker stats` don't include RAM used by `tmpfs` filesystems.

**Steps to reproduce the issue:**

1) Run
    ```sh
    docker run --shm-size=256MB --memory=256MB -it alpine sh -c "
            dd if=/dev/urandom of=/dev/shm/file bs=32M
            ls -lh /dev/shm
            read
    "
    ```
    and/or
    ```sh
    docker run --shm-size=256MB --memory=256MB -it alpine sh -c "
            dd if=/dev/urandom of=/tmp/file bs=32M
            ls -lh /tmp
            read
    "
    ```
2) Observe that the `dd` process is killed after exhausting the `memory`/`shm-size` limits and the RAM resident filesystem now contains a `200M`ish file:
    ```
    Killed
    total 217M   
    -rw-r--r--    1 root     root      216.6M Mar 20 05:23 file
    ```
3) Run `docker stats`

**Describe the results you received:**
```
CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
8c601a0d8404        keen_elbakyan          0.00%               7.316MiB / 256MiB   2.86%               8.49kB / 0B         0B / 0B             1
7066646c1a76        infallible_engelbart   0.00%               1.613MiB / 256MiB   0.63%               5.06kB / 0B         0B / 0B             1
```

**Describe the results you expected:**

The `MEM USAGE` and `MEM %` columns in the above table to be around `200M`ish and `78%`ish.

**Output of `docker version`:**

```
Docker version 19.03.7-ce, build 7141c199a2
```

**Output of `docker info`:**

<details>

```
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 2
  Paused: 0
  Stopped: 19
 Images: 5
 Server Version: 19.03.7-ce
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.24-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.56GiB
 Name: ruro-laptop
 ID: XHD5:R5HL:34CY:3UJ2:4QD6:IP3P:FIOD:NUZX:ZBEE:XND6:OJ5P:J6RM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

**Additional details:**

Output of
```sh
curl --unix-socket /var/run/docker.sock "http://localhost/containers/<container-id>/stats?stream=0" | python -m json.tool
```

<details>
<summary>For the <code>/tmp</code> container</summary>

```json
{
    "read": "2020-03-20T05:24:03.754425567Z",
    "preread": "2020-03-20T05:24:02.752857441Z",
    "pids_stats": {
        "current": 1
    },
    "blkio_stats": {
        "io_service_bytes_recursive": [],
        "io_serviced_recursive": [],
        "io_queue_recursive": [],
        "io_service_time_recursive": [],
        "io_wait_time_recursive": [],
        "io_merged_recursive": [],
        "io_time_recursive": [],
        "sectors_recursive": []
    },
    "num_procs": 0,
    "storage_stats": {},
    "cpu_stats": {
        "cpu_usage": {
            "total_usage": 1841965540,
            "percpu_usage": [
                992402,
                1665649,
                1619827291,
                2729087,
                4554574,
                5189767,
                201081062,
                5925708
            ],
            "usage_in_kernelmode": 1620000000,
            "usage_in_usermode": 200000000
        },
        "system_cpu_usage": 2611727730000000,
        "online_cpus": 8,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "precpu_stats": {
        "cpu_usage": {
            "total_usage": 1841965540,
            "percpu_usage": [
                992402,
                1665649,
                1619827291,
                2729087,
                4554574,
                5189767,
                201081062,
                5925708
            ],
            "usage_in_kernelmode": 1620000000,
            "usage_in_usermode": 200000000
        },
        "system_cpu_usage": 2611719640000000,
        "online_cpus": 8,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "memory_stats": {
        "usage": 234754048,
        "max_usage": 268439552,
        "stats": {
            "active_anon": 0,
            "active_file": 113635328,
            "cache": 227082240,
            "dirty": 197885952,
            "hierarchical_memory_limit": 268435456,
            "hierarchical_memsw_limit": 536870912,
            "inactive_anon": 0,
            "inactive_file": 113577984,
            "mapped_file": 0,
            "pgfault": 8976,
            "pgmajfault": 0,
            "pgpgin": 64152,
            "pgpgout": 8749,
            "rss": 0,
            "rss_huge": 0,
            "total_active_anon": 0,
            "total_active_file": 113635328,
            "total_cache": 227082240,
            "total_dirty": 197885952,
            "total_inactive_anon": 0,
            "total_inactive_file": 113577984,
            "total_mapped_file": 0,
            "total_pgfault": 8976,
            "total_pgmajfault": 0,
            "total_pgpgin": 64152,
            "total_pgpgout": 8749,
            "total_rss": 0,
            "total_rss_huge": 0,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "failcnt": 19,
        "limit": 268435456
    },
    "name": "/keen_elbakyan",
    "id": "8c601a0d84047b079b4e409c0fd3197efc1ce80bd964c472f49cbf769517ee5d",
    "networks": {
        "eth0": {
            "rx_bytes": 5610,
            "rx_packets": 39,
            "rx_errors": 0,
            "rx_dropped": 0,
            "tx_bytes": 0,
            "tx_packets": 0,
            "tx_errors": 0,
            "tx_dropped": 0
        }
    }
}
```
</details>

<details>
<summary>For the <code>/dev/shm</code> container</summary>

```json
{
    "read": "2020-03-20T05:32:09.684746601Z",
    "preread": "2020-03-20T05:32:08.683481358Z",
    "pids_stats": {
        "current": 1
    },
    "blkio_stats": {
        "io_service_bytes_recursive": [],
        "io_serviced_recursive": [],
        "io_queue_recursive": [],
        "io_service_time_recursive": [],
        "io_wait_time_recursive": [],
        "io_merged_recursive": [],
        "io_time_recursive": [],
        "sectors_recursive": []
    },
    "num_procs": 0,
    "storage_stats": {},
    "cpu_stats": {
        "cpu_usage": {
            "total_usage": 1494756157,
            "percpu_usage": [
                822498,
                856679,
                558496,
                8284470,
                200931734,
                1192872,
                1278601167,
                3508241
            ],
            "usage_in_kernelmode": 1270000000,
            "usage_in_usermode": 200000000
        },
        "system_cpu_usage": 2615624390000000,
        "online_cpus": 8,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "precpu_stats": {
        "cpu_usage": {
            "total_usage": 1494756157,
            "percpu_usage": [
                822498,
                856679,
                558496,
                8284470,
                200931734,
                1192872,
                1278601167,
                3508241
            ],
            "usage_in_kernelmode": 1270000000,
            "usage_in_usermode": 200000000
        },
        "system_cpu_usage": 2615616430000000,
        "online_cpus": 8,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "memory_stats": {
        "usage": 234721280,
        "max_usage": 268439552,
        "stats": {
            "active_anon": 0,
            "active_file": 0,
            "cache": 233029632,
            "dirty": 0,
            "hierarchical_memory_limit": 268435456,
            "hierarchical_memsw_limit": 536870912,
            "inactive_anon": 232894464,
            "inactive_file": 0,
            "mapped_file": 0,
            "pgfault": 8976,
            "pgmajfault": 0,
            "pgpgin": 65604,
            "pgpgout": 8741,
            "rss": 0,
            "rss_huge": 0,
            "total_active_anon": 0,
            "total_active_file": 0,
            "total_cache": 233029632,
            "total_dirty": 0,
            "total_inactive_anon": 232894464,
            "total_inactive_file": 0,
            "total_mapped_file": 0,
            "total_pgfault": 8976,
            "total_pgmajfault": 0,
            "total_pgpgin": 65604,
            "total_pgpgout": 8741,
            "total_rss": 0,
            "total_rss_huge": 0,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "failcnt": 30,
        "limit": 268435456
    },
    "name": "/infallible_engelbart",
    "id": "7066646c1a76b421db4ccee09d9bf6e2802203b42509b4138913bcf16a5132b1",
    "networks": {
        "eth0": {
            "rx_bytes": 5737,
            "rx_packets": 40,
            "rx_errors": 0,
            "rx_dropped": 0,
            "tx_bytes": 0,
            "tx_packets": 0,
            "tx_errors": 0,
            "tx_dropped": 0
        }
    }
}
```
</details>

Addressing similar issues:

- This issue might be an unintended side effect of issue #10824 / https://github.com/docker/cli/pull/80. Not including caches in memory usage is correct, since they will be automatically freed, if memory is needed. Not including `tmpfs` is not correct since the kernel can't just delete these files and so exhausting this resource will result in dead processes.
- Possibly related to #39004, but not likely imo.

**Comment by RuRo** [comment]
Actually, the `MAP_SHARED` code in the last issue prompted me to try the following:

```python
#> docker run --shm-size=256M --memory=512M -it python python -c "
import os
import mmap

MMAP_SIZE = 256 * 1024 * 1024
BLCK_SIZE = 32 * 1024 * 1024

mm = mmap.mmap(-1, MMAP_SIZE)
pid = os.fork()
if pid:
    # Wait for the child to exit
    os.waitpid(pid, 0)
    # Find the last X in mmaped file
    while True:
        data = mm.read(BLCK_SIZE)
        if not len(data) or data[-1] != ord(b'X'):
            break
    print('Last X found at offset', mm.tell())
    # Wait for input (keep holding the mm handle)
    input('Waiting...')
else:
    # Write too much data to tmpfs
    try:
        mm.seek(0)
        for i in range(MMAP_SIZE // BLCK_SIZE):
            mm.write(b'X' * BLCK_SIZE)
    except:
        pass
#> "
```
Which outputs
```
Last X found at offset 268435456
```
and
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
c7da3eeea656        cranky_hermann      0.00%               7.523MiB / 512MiB   1.47%               6.82kB / 0B         1.99MB / 0B         1
```
in `docker stats`.

So it appears, that not even regular shared memory is accounted for in `docker stats`?

**Comment by RuRo** [comment]
This is a bug report, not a question btw. I understand, if you need to confirm/verify/review it, before assigning it the `kind/bug` label, I just wanted to point that out to avoid mislabeling this issue.

**Comment by AkihiroSuda** [comment]
I don't think this is a bug. We can consider adding a new stat field for tmpfs, but the existing stat fields should not be changed.

**Comment by AkihiroSuda** [comment]
changed the label to `kind/enhancement`

**Comment by RuRo** [comment]
@AkihiroSuda Are you sure, that the statistics are correctly extracted from cgroups? The process in the container **is** correctly killed when the `--memory` limit is exceeded by shared memory or tmpfs even though the `MEMORY USAGE` and `MEM %` values are not near the limit in the `docker stats`. I could understand if it was only related to tmpfs, but as it turns out (see my first comment), this even applies to regular shared memory mappings.

Currently, a process can exceed the `--memory` limit without any visible indication in `docker stats`, if it uses shared memory. The current behaviour is extremely misleading and counter-intuitive. I spent *a lot* of time trying to debug, why my containers were getting killed even though the `MEMORY USAGE` in `docker stats` was nowhere near the limit.

**Comment by AkihiroSuda** [comment]
> Are you sure, that the statistics are correctly extracted from cgroups? 

Yes, it is calculated as `usage_in_bytes - cache`:

https://github.com/docker/cli/blob/22acbbcc4b3fb5020492b1ed9e72186191bfedc0/cli/command/container/stats_helpers.go#L230

https://github.com/moby/moby/blob/c7ad2b866182325b49bc7addb7042e16afbb60b6/daemon/daemon_unix.go#L1515

https://github.com/containerd/cgroups/blob/6c3dec43a1030a55584ab8b5b181411029d43ecc/memory.go#L173

**Comment by AkihiroSuda** [comment]
Seems related to the extraction of `cache` on https://github.com/docker/cli side. https://github.com/docker/cli/blob/22acbbcc4b3fb5020492b1ed9e72186191bfedc0/cli/command/container/stats_helpers.go#L230
(Background: https://github.com/moby/moby/issues/10824 https://github.com/moby/moby/pull/32777 https://github.com/docker/cli/pull/80)

**Comment by RuRo** [comment]
> Yes, it is calculated as usage_in_bytes - cache

When I asked if it was calculated correctly, I didn't mean "Is the `usage_in_bytes - cache` formula used?", but "Are you sure, `usage_in_bytes - cache` is the correct formula?".

The reasoning behind the `usage_in_bytes - cache` formula AFAIK is that since the caches can be dropped at any time, they are not **actually** used and therefore shouldn't be counted. However, it appears that `cache` also includes mapped files and shared mappings, which can't be dropped like regular caches, so clearly this is an oversimplification.

So `usage_in_bytes` **over**estimates of the "non-reclaimable" RAM and `usage_in_bytes - cache` appears to be an **under**estimate it.

The [cgroups documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) is slightly confusing about what each statistic includes, but I don't think the documentation mentions `usage_in_bytes - cache`, or suggests that it should be used to calculate the "available" memory. 

Perhaps, `mapped_file`, `active_file`, `inactive_file`, `active_anon` or `inactive_annon` must be somehow accounted in the formula, or maybe this is a bug in how `cache` is calculated. I don't know enough about the low-level details of how `cgroups` and the kernel handle memory, but it's obvious, that something is wrong here.

**Comment by AkihiroSuda** [comment]
`usage_in_bytes - total_inactive_file` might be more accurate? (Used in containerd/CRI: https://github.com/containerd/cri/blob/c1115d4e57f55a5f45fb3efd29d3181ce26d5c6a/pkg/server/container_stats_list_unix.go#L106-L118)

In the `MAP_SHARED` example, the value on my machine is like `275644416 - 135168 = 275509248` .

**Comment by AkihiroSuda** [comment]
@thaJeztah @crosbymichael @kolyshkin 
PTAL? Do you think we can change the definition from `usage_in_bytes - cache`  into `usage_in_bytes - total_inactive_file`? Will it break existing applications?

**Comment by AkihiroSuda** [comment]
PR: https://github.com/docker/cli/pull/2415

@RuRo PTAL

**Comment by RuRo** [comment]
@AkihiroSuda. I am not an expert, so I can't 100% validate if `total_inactive_file` is correct. However, given that it's used in `cadvisor` and `containerd/CRI`, and seems to fix this issue (with a slight caveat that the very first example is still slightly wrong, but that's probably because the tmpfs file is closed in that example, at which point it doesn't belong to any process, so it's probably outside the scope of this issue), I'd say LGTM.

P.S. If you want a couple nitpicks:
1) Both `cadvisor` and `containerd/CRI` actively check if `total_inactive_file < usage` before substracting. I am guessing, that this is done so that if the 2 values are lagging slightly during a sudden memory usage change, we don't accidentally report negative memory usage.
2) You might want to change `cli/docs/reference/commandline/stats.md` to reflect the changes. 😁

**Comment by AkihiroSuda** [comment]
updated, thanks
