### ISSUE TITLE
rpc error: code = 2 desc = oci runtime error: exec failed: in HEALTHCHECK

### ISSUE THREAD

**Issue by loretoparisi** [moby/moby#40737]
When using the `HEALTHCHECK` in Docker 17:

```dockerfile
HEALTHCHECK --interval=5m --timeout=5s \
  CMD $MXM_ROOT_APPLICATION/healthcheck.sh localhost $WORKER_PORT || exit 1
```

 if a `docker-compose` variable is not assigned correctly like here

```yaml
   environment:
      - NODE_ID      
      - NODE_ENV=production
```

the `HEALTHCHECK` will command fail:

```
   "FinishedAt": "0001-01-01T00:00:00Z",
    "Health": {
        "Status": "unhealthy",
        "FailingStreak": 9,
        "Log": [
            {
                "Start": "2020-03-25T10:11:17.687207876Z",
                "End": "2020-03-25T10:11:17.829283718Z",
                "ExitCode": -1,
                "Output": "rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"invalid environment 'NODE_ID'\"\n"
```

Is this an expected behavior? I think it should be reported as a warning more than as an error, since the `docker-compose` works as expected when starting the container from that `yaml` file, while the `HEALTHCHECK` will fail.

Docker version:
```
$ docker --version
Docker version 17.05.0-ce, build 89658be
```

Ubuntu version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by thaJeztah** [comment]
> When using the HEALTHCHECK in Docker 12

Did you mean docker 1.12.x ? Note that Docker 1.12 is really old, and reached EOL in March 2017, after which it has no longer been maintained. I'd highly recommend upgrading to a current version of docker, because those old versions have unpatched, critical vulnerabilities.

**Comment by loretoparisi** [comment]
@thaJeztah sorry I'm using

```
$ docker --version
Docker version 17.05.0-ce, build 89658be
```

**Comment by AkihiroSuda** [comment]
17.05 reached EOL as well, please use 19.03: https://get.docker.com/

**Comment by loretoparisi** [comment]
@AkihiroSuda ok thank you, are you aware if this issue still affects docker 19.03?

Thank you.

**Comment by sam-thibault** [comment]
19.03 also is no longer maintained.  I don't see updates on this issue, so I will close it as stale.
