### ISSUE TITLE
CIFS mouting alternatives with docker desktop for linux containers?

### ISSUE THREAD

**Issue by Ageraluon** [moby/moby#40746]
I am regularly facing limits with sharing docker volumes on docker desktop with linux containers. 

The current way of mounting cifs volumes:

- does not support file locking/byte range locking
- either only allows a fixed set of uids/gids or does not retain uid/gid ownership over restarts

Against this, my question; is there any more flexible file sharing mechanism on the horizon? I understand that ntfs does not support linux file permissions, however, the necessary information could theoretically be written into an invisible file in each share by the docker daemon. I understand implementing such a system is an enormous effort, but this seems to be a regular limitation that many users face.
Does LCOW/WSL2 offer any alternatives to cifs file sharing?
Thank you for the help!

**Comment by thaJeztah** [comment]
Docker Desktop for Windows now uses WSL2, and no longer uses CIFS for sharing / mounting files into containers. 

Let me close this ticket, as it's not really a bug-report, but feel free to continue the conversation
