### ISSUE TITLE
Image property "created" makes hard to have reproducible builds

### ISSUE THREAD

**Issue by ppiotrow** [moby/moby#40754]
**Description**

The Reproducible Builds guideline points that build tools should make build timestamp configurable https://reproducible-builds.org/docs/source-date-epoch/

While building docker image with `docker build` the image "created" property is set up to the docker daemon system timestamp. This is against reproducibility guidelines as even on the same host you're unable to build the same image again. It's even more difficult to do it on different hosts with docker daemon.

There is this cool [blogpost](https://maori.geek.nz/how-to-digest-a-docker-image-ca9fc7630b71) that describes the simplest ever docker image ending up having different digests when running on two different hosts or without cache.

**Workarounds**
The JIB builds images on it's own, without using `docker build` command.
They create *.json and *.tar filles manually just to override "Created" property of the image.
It is described in their [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago)

**Describe the results you expected:**
I'd love to have additional option in the build command like
`docker build --sourceDateEpoch='1970-01-01 00:00:00.0' .`
or just `--sourceDateEpoch=0` with default value to `system.time()`.

This would enable to reuse layers cache while building docker images from various build tools plugins like this https://github.com/sbt/sbt-native-packager/issues/1321 or described here https://github.com/GoogleContainerTools/jib/issues/2252

**Comment by AkihiroSuda** [comment]
This should be discussed in BuildKit repo https://github.com/moby/buildkit/issues/1058

**Comment by ppiotrow** [comment]
Thanks, moving to the linked issue.
