### ISSUE TITLE
Swarm managers suddenly fail to communicate

### ISSUE THREAD

**Issue by mhaamann** [moby/moby#40750]
**Description**

Swarm managers fail to communicate, splits the swarm and restarts all containers.
This is a 3 host swarm clusters. All 3 hosts are managers.

From the logs we always see the following right before the incident:
```
Mar 26 22:55:10 docker01 dockerd: time="2020-03-26T22:55:10.862446958+01:00" level=info msg="memberlist: Suspect 094a7c2b3d98 has failed, no acks received"
Mar 26 22:55:11 docker01 dockerd: time="2020-03-26T22:55:11.055552741+01:00" level=warning msg="memberlist: Refuting a suspect message (from: 8fec40a63daf)"
```

Happens intermittently. Started Sunday 22nd March, occurs 2-4 times a day.
Changed dispatcher-heartbeat to 15s, this made no difference.

Could this be related to: https://github.com/moby/moby/issues/38668 ???

**Describe the results you received:**

Logs from one of the swarm managers: https://gist.github.com/mhaamann/f1114a47a3ab21e4ee0bdc4cdffffa16

**Output of `docker version`:** 
This happend first time on version 18.09.9 and we updated the day after to the latest Docker version. All 3 hosts are now on 19.03.8, build afacb8b

**Output of `docker info`:** https://gist.github.com/mhaamann/0684e3946ced0e180b5f48a2cae61d9e

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Dedicated servers all in the same data center. Almost no latency. Plenty of RAM and CPU is not overloaded.

**Comment by mhaamann** [comment]
Setting `docker swarm update --dispatcher-heartbeat 15s` had no effect. Default was 5s.

We set it to `docker swarm update --dispatcher-heartbeat 120s` which seems to have an effect. No server outages for 3 days

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
