### ISSUE TITLE
Rootless: provide instructions on how to run "deb" / "rpm" installs in rootless mode

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#40761]
I haven't dug into this deeply, but we were discussing this in the maintainers meeting (/cc @cpuguy83).

Currently, the "rootless" install script (https://github.com/docker/docker-install/blob/master/rootless-install.sh) is designed such that no `root` permissions are needed to install everything for running docker in rootless mode.

While this is _one_ scenario, another scenario could be that docker is installed the "regular" way, but now the user wants to either;

1. disable the regular docker service, and instead run rootless, or
2. run additional (rootless) instances

We should investigate if those scenarios are possible:

- should additional things be added to the `.deb` / `.rpm` packages (so that users have everything they need if they want to give "rootless" mode a spin)
    - if so, we could bundle them, e.g., in a `contrib` directory somewhere
- would there be permission issues with files installed by the `.deb` / `.rpm` packages that need to be addressed?
- (for 1. above); write instructions how to disable the regular `docker` (and `containerd`) services / systemd units
- document how to create a new `docker context` so that the user can switch between the "host" (rootful) daemon and "rootless" daemon (if both are running) 
- other things?

I think that having the _option_ to run docker in rootless mode (after doing a regular install) would be useful to have: it would make it easier to give it a try, and possibly lead to more users testing / trying it.

@AkihiroSuda ptal (you most likely know what would be needed)

**Comment by AkihiroSuda** [comment]
This is in-scope of https://github.com/moby/moby/issues/40707 .


> * should additional things be added to the `.deb` / `.rpm` packages (so that users have everything they need if they want to give "rootless" mode a spin)

Yes, probably we will need `docker-rootless-extras-$version.{deb,rpm}`.

>   * if so, we could bundle them, e.g., in a `contrib` directory somewhere


> * would there be permission issues with files installed by the `.deb` / `.rpm` packages that need to be addressed?
> * (for 1. above); write instructions how to disable the regular `docker` (and `containerd`) services / systemd units
> * document how to create a new `docker context` so that the user can switch between the "host" (rootful) daemon and "rootless" daemon (if both are running)

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/40924

**Comment by thaJeztah** [comment]
Oh, I see I didn't reply on your prior comment;

> if so, we could bundle them, e.g., in a contrib directory somewhere
>> Could you be more specific?

Our `.deb` and `.rpm` packages currently include some of the `contrib/` files. https://github.com/docker/docker-ce-packaging/blob/fcbe36668d1a66a2f7679ad191c9165c37c902e2/deb/common/rules#L35

Hmmm... or, so I _thought_ we were. I see we did so in the past (e.g. the `check-config.sh` script used to be included; https://github.com/moby/moby/blob/4d331573ffa2531bbfeb691e033c1c789e84f310/hack/make/.build-deb/docker-engine.install#L5

But looks like we may no longer be doing that; let me double check.


Anyway; my thinking was; if what we have to include is a script (i.e.; no huge binaries), that may be an easy way for users to have a "regular" install (from `apt` / `rpm`), and then start an instance of dockerd in rootless-mode.

**Comment by AkihiroSuda** [comment]
I'm planning to open PR to add `docker-rootless-extras-$version.{deb,rpm}` to docker-ce-packaging repo after https://github.com/docker/docker-ce-packaging/pull/457 gets merged

**Comment by AkihiroSuda** [comment]
deb PR: https://github.com/docker/docker-ce-packaging/pull/474

**Comment by AkihiroSuda** [comment]
The PR is merged
