### ISSUE TITLE
docker run image not working in windows 10 Docker for Desktop v2.2.0.4

### ISSUE THREAD

**Issue by payal-sharma-1606** [moby/moby#40763]
Error 1:
driver error deleting endpoint friendly_bell : hns failed with error : The endpoint was not found.
Error 2:
Failed to load container mount 0b0244c0e81684934d02fbd340c462d37a3a8e78db4eaab444d1733b0c397388: mount does not exist

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
