### ISSUE TITLE
/bin/bash: /bin/bash: cannot execute binary file

### ISSUE THREAD

**Issue by Misiur** [moby/moby#40776]
WSL ubuntu 16

```
docker -v
Docker version 18.09.7, build 2d0083d
```
```
docker-compose run --rm compiler
/bin/bash: /bin/bash: cannot execute binary file
```
Dockerfile command (including installation of bash)
```
ENTRYPOINT ["/bin/bash"]
CMD ["/bin/bash"]
```

Where do I locate `start.sh` on WSL? There are related mac os problems with that due to multiple available shells

**Comment by AkihiroSuda** [comment]
WSL1 is unsupported

**Comment by Misiur** [comment]
It's WSL 2

**Comment by AkihiroSuda** [comment]
Probably your bash binary doesn't match the distro of your base image, but the actual cause analysis would need full Dockerfile.

For WSL2, see https://docs.docker.com/docker-for-windows/wsl-tech-preview/

**Comment by Misiur** [comment]
```
FROM ubuntu:bionic AS compiler-build

RUN apt-get update && \
    apt-get install -y gcc \
                       gcc-multilib \
                       make \
                       cmake \
                       git \
                       python3.8 \
                       bash

WORKDIR /home
ADD . /home/pawn
RUN mkdir build
WORKDIR /home/build
ENTRYPOINT ["/bin/bash"]
CMD ["/bin/bash"]
```

With https://github.com/pawn-lang/compiler/

None of the binaries are working, I've tried sh, ls and bash, but same error, like
`/bin/ls: /bin/ls: cannot execute binary file` etc.

**Comment by AkihiroSuda** [comment]
Please try https://docs.docker.com/docker-for-windows/wsl-tech-preview/ , and open an issue at https://github.com/docker/for-win if it doesn't work

**Comment by Misiur** [comment]
It's a docker in WSL 2 container, it works for all my other containers for some reason. Is one of the packages faulty?
