### ISSUE TITLE
Difference in behaviour between whitespace in front of comments and whitespace in front of empty escaped newlines

### ISSUE THREAD

**Issue by rcjsuen** [moby/moby#40781]
**Description**
`docker build` handles whitespace in front of comments differently from escaped newlines. Should they be the same for consistency?

**Steps to reproduce the issue:**
1. Create the Dockerfile below.
```Dockerfile
FROM alpine
RUN echo a\
# comment
bc
RUN echo a\
    # comment
bc
RUN echo a\
\
bc
RUN echo a\
    \
bc
```
2. Build it.
```
$ docker build --no-cache .
Sending build context to Docker daemon  38.15MB
Step 1/5 : FROM alpine
 ---> a187dde48cd2
Step 2/5 : RUN echo abc
 ---> Running in 79d27c4ca35a
abc
Removing intermediate container 79d27c4ca35a
 ---> ea38504cb466
Step 3/5 : RUN echo abc
 ---> Running in 98bbef8a9d93
abc
Removing intermediate container 98bbef8a9d93
 ---> b5fbc315217d
Step 4/5 : RUN echo abc
 ---> Running in 28f19ca7f662
abc
Removing intermediate container 28f19ca7f662
 ---> 61cc66e30b11
Step 5/5 : RUN echo a    bc
 ---> Running in 9a5dab9f881e
a bc
Removing intermediate container 9a5dab9f881e
 ---> 2c7e72509911
Successfully built 2c7e72509911
```
3. Notice how the first three prints `abc` but the fourth one prints `a bc`.
4. The issue does not appear to be restricted to shell expansions caused by `RUN` and so on. The same behaviour occurs for `EXPOSE`.
```Dockerfile
FROM alpine
EXPOSE 800\
# comment
1
EXPOSE 800\
    # comment
2
EXPOSE 800\
\
3
EXPOSE 800\
    \
4
```
5. Building will display the same issue with it exposing both ports `800` and `4`.
```
$ docker build --no-cache .
Sending build context to Docker daemon  38.15MB
Step 1/5 : FROM alpine
 ---> a187dde48cd2
Step 2/5 : EXPOSE 8001
 ---> Running in 5cd4f43fad2b
Removing intermediate container 5cd4f43fad2b
 ---> 45591e5432f7
Step 3/5 : EXPOSE 8002
 ---> Running in 451a5da6eae1
Removing intermediate container 451a5da6eae1
 ---> abcbe582bd6a
Step 4/5 : EXPOSE 8003
 ---> Running in 1148717c152e
Removing intermediate container 1148717c152e
 ---> 88c4e85bb4d4
Step 5/5 : EXPOSE 800    4
 ---> Running in d3b52318efde
Removing intermediate container d3b52318efde
 ---> 32f8bb075f06
Successfully built 32f8bb075f06
```
6. You can verify this with `docker inspect`.
```
$ docker inspect --format='{{json .Config.ExposedPorts }}' 32f8bb075f06
{
  "4/tcp": {},
  "800/tcp": {},
  "8001/tcp": {},
  "8002/tcp": {},
  "8003/tcp": {}
}
```

**Describe the results you received:**
I noticed that whitespace in front of comments were ignored but the ones in front of an escape character were not.

**Describe the results you expected:**
I would have expected them to be the same. Either they both respect the whitespace or they both ignore them.

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:49:05 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 26
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-174-generic
 Operating System: Alpine Linux v3.10 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.4GiB
 Name: node1
 ID: AGBI:2YO2:52ND:VWNP:OD56:LL2U:GLGG:QACQ:ABNV:3NOI:SRUI:6Q7A
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 43
  System Time: 2020-04-06T12:07:58.957983198Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.1
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested online with [PWD](http://play-with-docker.com/).

**Comment by rcjsuen** [comment]
There is a [comment in BuildKit](https://github.com/moby/buildkit/blob/7c9d706a2a50818f389e04432b22ff7ca586a496/frontend/dockerfile/parser/parser.go#L336-L337) that points out the oddity of preserving whitespace on continuation lines. So while it seems this is intentional, it's not clear if anyone remembers the reason. 🤔

**Comment by thaJeztah** [comment]
Comments are part of the Dockerfile syntax, and will be removed before further process the instruction, so in your example;

```dockerfile
FROM alpine
RUN echo a\
# comment
bc
RUN echo a\
    # comment
bc
RUN echo a\
\
bc
RUN echo a\
    \
bc
```

Docker removes the comment-only lines

```dockerfile
FROM alpine
RUN echo a\
bc
RUN echo a\
bc
RUN echo a\
\
bc
RUN echo a\
    \
bc
```

Note that _officially_ comments must be at the _start_ of a line, so should not have leading whitespace; some versions of Docker accepted white-space before it, and that behaviour is kept to not break existing Dockerfiles (some discussion on https://github.com/moby/moby/pull/34333, https://github.com/moby/moby/pull/34333#issuecomment-322236475 and probably some other ones). Dockerfiles _do_ enforce that comments are per-line (as in; it does not consider comments (e.g.) at the end of a `RUN` line; doing so would be largely impossible as it doesn't know what rules a specific `SHELL` follows.

Before running, line-continuation markers (`\`) are processed;


```dockerfile
FROM alpine
RUN echo abc
RUN echo abc
RUN echo abc
RUN echo a    bc
```

When processing line-continuation, white-space is preserved, which is similar to how a shell processes this;

```bash
$ echo ab\
     \
c

# ab c
```

**Comment by rcjsuen** [comment]
> Note that _officially_ comments must be at the _start_ of a line, so should not have leading whitespace; some versions of Docker accepted white-space before it, and that behaviour is kept to not break existing Dockerfiles (some discussion on #34333, [#34333 (comment)](https://github.com/moby/moby/pull/34333#issuecomment-322236475) and probably some other ones).

Thank you for sharing this little important detail, @thaJeztah. It sounds to me then that there is nothing that can/will be done here given that backwards compatibility must be preserved. So unless some sort of versioning is introduced to the Dockerfile syntax, this behaviour must remain.

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/cli/pull/2617 to improve the documentation; feel free to comment on that PR if you have suggestions 👍

**Comment by rcjsuen** [comment]
> I opened [docker/cli#2617](https://github.com/docker/cli/pull/2617) to improve the documentation; feel free to comment on that PR if you have suggestions 👍

It looks okay to me. Thank you for fleshing this out in the documentation, @thaJeztah!

**Comment by thaJeztah** [comment]
Let me close this one as https://github.com/docker/cli/pull/2617 was merged (I'll backport it to be published on the docs  soon)
