### ISSUE TITLE
Add a go.mod file to support getting SDK as module

### ISSUE THREAD

**Issue by spellr** [moby/moby#40812]
Because the repo currently lacks a `go.mod` file, when importing this repo (or `docker/engine` repo), the importer's go.mod files fills with imports to "indirect" imports.

This is how the `go.mod` file looks empty:
```golang
module github.com/spellr/asdf

go 1.14

replace github.com/docker/docker => github.com/docker/engine v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible
```

The replace is for getting the correct client as it says [here](https://github.com/moby/moby/issues/37683#issuecomment-415054135) and [here](https://github.com/moby/moby/issues/39302#issuecomment-504146736).

By importing `"github.com/docker/docker/client"` and running `go mod tidy` it turns into:
```golang
module github.com/spellr/asdf

go 1.14

replace github.com/docker/docker => github.com/docker/engine v17.12.0-ce-rc1.0.20200309214505-aa6a9891b09c+incompatible

require (
	github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78 // indirect
	github.com/Microsoft/go-winio v0.4.14 // indirect
	github.com/containerd/containerd v1.3.3 // indirect
	github.com/docker/distribution v2.7.1+incompatible // indirect
	github.com/docker/docker v0.0.0-00010101000000-000000000000
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.4.0 // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/google/go-cmp v0.4.0 // indirect
	github.com/gorilla/mux v1.7.4 // indirect
	github.com/morikuni/aec v1.0.0 // indirect
	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
	github.com/opencontainers/image-spec v1.0.1 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/sirupsen/logrus v1.5.0 // indirect
	golang.org/x/sys v0.0.0-20200409092240-59c9f1ba88fa // indirect
	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
	google.golang.org/grpc v1.28.1 // indirect
	gotest.tools v2.2.0+incompatible // indirect
)
```

**Comment by cpuguy83** [comment]
👎 This will almost certainly break so many people.
I also don't think this would actually fix indirect imports.

In addition, you should be able to import directly from github.com/docker/docker now since we have tags in this repo.
Just be careful about which version go picks up is the one you want. It used to pick up 1.13 as the latest tag, now it picks 17.12, meanwhile 19.03.8 is the actual real latest tag.

If you don't mind, I'd like to keep discussion for such changes in #39302

Thanks! 🙇
