### ISSUE TITLE
Ctrl+C not work in `docker exec`

### ISSUE THREAD

**Issue by wangcong15** [moby/moby#40815]
**Description**
When I run `docker exec`, I find that Ctrl+C cannot stop the running process, which can be a threat in the following situation: 
Evil images can insert a fake binary to replace a common command. 
The fake binary may run many threads of infinite loops. In this case, uses can create containers in a normal way, but be affected when executing `docker exec $container_id $fake_binary`. 
Then the cpu quota could be occupied as much as possible. The computing resources waste cannot be stopped even if we press Ctrl+C.

**Steps to reproduce the issue:**
1. docker run --rm -it ubuntu /bin/bash
2. create a fake binary which raise an infinite loop
3. open another terminal
4. docker exec 'docker ps -q' ./fake-bin
4. press ctrl+c

**Describe the results you received:**
the process `./fake-bin` still runs, which wastes computing resources

**Describe the results you expected:**
the process `./fake-bin` should terminate

**Additional information you deem important (e.g. issue happens only occasionally):**
Perhaps this is not a critical problem. But it makes a better Docker to fix the issue above.

**Output of `docker version`:**

```
Docker version 19.03.8, build afacb8b
```

**Output of `docker info`:**

```

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
on both Linux and macOS

**Comment by dominikbraun** [comment]
`Ctrl + C` doesn't work because the container is (and has to be) detached by default. If you want to be able to interrupt the process you're executing, you have to use `docker container exec -it <container> <command>`.
