### ISSUE TITLE
kill/rm docker hang

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#40824]
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

![image](https://user-images.githubusercontent.com/9782796/79426824-4be1e800-7ff6-11ea-9aca-8ac814aeb8e0.png)

**Comment by timchenxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/9782796/79427455-4cc74980-7ff7-11ea-9525-388c3c7a6a41.png)

**Comment by thaJeztah** [comment]
docker 18.09.x reached EOL; if you're unable to upgrade to the current (19.03.x at time of writing) release, at least make sure you're running the latest patch release of 18.09 (v18.09.9) and the latest `containerd.io` package.


Are you still able to reproduce this on a current version?

**Comment by timchenxiaoyu** [comment]
ths，I will test 19.03.x。

**Comment by thaJeztah** [comment]
closing this one for now
