### ISSUE TITLE
20.x release code freeze

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#40838]
Hello @moby/moby-maintainers,

During the last maintainers call, we discussed plans for code freeze for the next release. We've been tracking desired features/changes for a couple of months now and I think we are basically there.

We wanted to ping everyone and set a freeze date for the next release.
The date we discussed is May 1st. This is a forcing function to get the last few changes in.
Please see https://github.com/moby/moby/projects/9 for a list of desirable for this.
If you have a change that is missing that you'd like to have reviewed, please add it.

Also, just to note May 1st is just a date we chose on the call, this can be adjusted as needed but it would be nice to lock this down.

**Comment by cpuguy83** [comment]
@thaJeztah Any chance you can ping teams in the docker org accordingly?

**Comment by thaJeztah** [comment]
@cpuguy83 will do, thanks!

**Comment by cpuguy83** [comment]
On the maintainers call, we decided to push freeze another week.
There are still some pending PR's and potentially a containerd 1.4 release which brings in full cgroups2 support.

**Comment by cpuguy83** [comment]
That will be Friday 5/8.

**Comment by AkihiroSuda** [comment]
What's current status?

**Comment by AkihiroSuda** [comment]
ping @cpuguy83 @thaJeztah

**Comment by cpuguy83** [comment]
There's still a few things pending. Not huge things.
Need some reviews: https://github.com/moby/moby/pulls?q=is%3Aopen+is%3Apr+milestone%3A20.03.0

**Comment by AkihiroSuda** [comment]
Is there any remaining blocker toward beta?

**Comment by cpuguy83** [comment]
We need to revert/change a swarmkit API https://github.com/docker/swarmkit/pull/2965

**Comment by Alvise88** [comment]
ping @cpuguy83 @thaJeztah

**Comment by cpuguy83** [comment]
@Alvise88 Docker is working on cutting a beta now.

**Comment by AkihiroSuda** [comment]
We have v20.10.0-beta1: https://download.docker.com/linux/static/test/x86_64/
https://github.com/docker/docker-ce/blob/master/CHANGELOG.md

**Comment by tianon** [comment]
We don't appear to have tags anywhere yet though 😩

**Comment by thaJeztah** [comment]
@tiborvass I think you were working on that (missing tags) ?
