### ISSUE TITLE
docker build - Windows Server 2019 - docker desktop 2.2.0.5 - "storage-opt": ["size=50GB"] doesn't WORK

### ISSUE THREAD

**Issue by mtola** [moby/moby#40849]
**In daemon.json:**

{
  "registry-mirrors": [],
  "insecure-registries": [],
  **"storage-opt": ["size=50GB"],**     <----- add by me and then restart
  "debug": true,
  "experimental": false
}

---

**Build:**

docker build -t vctools2017-vcpkg-osg-ltsc2019 --no-cache .
Sending build context to Docker daemon   2.49MB
Step 1/17 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
 ---> 673984b9bc97
Step 2/17 : SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]
 ---> Running in aff2a39ee216
Removing intermediate container aff2a39ee216
 ---> aa6ca9a8e60f
Step 3/17 : RUN gwmi win32_logicaldisk
 ---> Running in f610ebb7d6b1

DeviceID     : C:
DriveType    : 3
ProviderName :
**FreeSpace    : 21210583040
Size         : 21339549696**
VolumeName   :

**So : 21339549696 / 1024 / 1024 / 1024 = 19,87 Go !**

----> So, don't work at all, can you help me please ?

---

**Docker info:**

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 104
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.1158)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 32GiB
 Name: dockerwin01
 ID: KISO:YUUK:KAUD:DJTF:QGAU:HAV7:L6DN:2ZGY:B5I3:CLZF:TUEX:N5EK
 Docker Root Dir: E:\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 27
  System Time: 2020-04-22T11:31:55.6838954+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by mtola** [comment]
I found ! The doc is false here https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage

It is not
"storage-opt": ["size=50GB"],
but
"storage-opt**s**": ["size=50GB"],

but this is inconsistent because we can for example use with success (only to run, not to build):
docker run --storage-opt "size=60GB" mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 cmd /c dir

and here --storage-opt is without **s**

So i think there is something to do in the future to standardize : WITH or WITHOUT **s**

**Comment by thaJeztah** [comment]
The size used during build is currently hardcoded to 127GB; I have a PR in review that changes this behaviour to only apply the default if no custom size is set; https://github.com/moby/moby/pull/40256

**Comment by thaJeztah** [comment]
The reason the JSON uses plural is that for the flags, you specify only a single option for each flag, but set multiple flags if you want to set multiple options; 

```
--storage-opt foo=bar --storage-opt bar=baz
```

Whereas in the `daemon.json`, the value is a list of options:

```json
{
    "storage-opt": ["foo=bar", "bar=baz"]
}
```

**Comment by thaJeztah** [comment]
I'm closing this issue because I don't think there's a bug at hand here, and we can't change these options in the daemon.json as it would break existing installations, but feel free to continue the conversation

**Comment by mtola** [comment]
> 
> 
> The size used during build is currently hardcoded to 127GB; I have a PR in review that changes this behaviour to only apply the default if no custom size is set; #40256

No I'm really sorry : the size by default is not 127GB but 20GB !!!

**Comment by mtola** [comment]
> 
> 
> The reason the JSON uses plural is that for the flags, you specify only a single option for each flag, but set multiple flags if you want to set multiple options;
> 
> ```
> --storage-opt foo=bar --storage-opt bar=baz
> ```
> 
> Whereas in the `daemon.json`, the value is a list of options:
> 
> ```json
> {
>     "storage-opt": ["foo=bar", "bar=baz"]
> }
> ```

You have forgotten again the 's' in the .json : >     "storage-opt**s**": ["foo=bar", "bar=baz"]

Again, here the doc is FALSE because it don't work AT ALL without 's' : https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage

**Comment by thaJeztah** [comment]
Those docs are from Microsoft, and not maintained by us. I think they're open source though, and you may be able to open a pull request to fix that page

**Comment by thaJeztah** [comment]
Edited my comment to add the missing "s"; posted it from my phone (whoops)

**Comment by mtola** [comment]
> 
> 
> The size used during build is currently hardcoded to 127GB; I have a PR in review that changes this behaviour to only apply the default if no custom size is set; #40256

---> Look @my first post in this issue that demonstrates there is only 20GB when daemon.json is empty.
I'm not the only one with that problem (lot of posts everywhere since a long time).

I'm under Windows Server 2019 (ltsc2019) in 'process' mode.
(and don't know if the problem occurs as well in 'hyperv' mode)

Thank you.

**Comment by mtola** [comment]
> 
> 
> The size used during build is currently hardcoded to 127GB; I have a PR in review that changes this behaviour to only apply the default if no custom size is set; #40256

---> New test today : I confirm there is only 20GB when 'daemon.json' is empty.
I'm not the only one with that problem (we can find posts everywhere since a while).

I'm under Windows Server 2019 (ltsc2019) in '**process**' mode.
(and I don't know if the problem occurs as well in '**hyperv**' mode)

Thank you.
