### ISSUE TITLE
Disable autoremove on running container

### ISSUE THREAD

**Issue by retnikt** [moby/moby#40852]
**Description**

If I start a container with the `--rm` option, is it possible to remove that attribute while the container is running so that it is not removed when the container stops? For example, if I changed my mind about the desired ephemerality, or accidentally left some important data in the container which I need to keep, or similar. I see that `docker inspect` it shows `"AutoRemove": true`; but I believe this cannot be changed using `docker update`. Is there a way around this, or could it be added?

**Steps to reproduce the issue:**
1. Start a container with `--rm`
2. Decide you want to keep the container after all

**Describe the results you received:**
I could update the auto-remove property using `docker update` or similar

**Describe the results you expected:**
There appears to be no such way to do this.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
19.03.8-ce

Running on physical Linux machine.

**Comment by thaJeztah** [comment]
No, that's not currently supported. You could probably `docker commit` the container's filesystem to an image in case it happened to have important data (or `docker cp` those files to the host to backup them)

**Comment by tao12345666333** [comment]
> No, that's not currently supported. You could probably `docker commit` the container's filesystem to an image in case it happened to have important data (or `docker cp` those files to the host to backup them)

I think so.

If you support the removal of the effect of the `--rm` parameter in docker, it may mean that you can also support the effect of adding` --rm` to the running container. This will confuse its semantics.

I understand why you want to keep a container,  but as @thaJeztah  said, you can use `docker commit` or `docker cp` to keep important state/data.

**Comment by retnikt** [comment]
Thanks, I didn't know about `docker commit`! I guess there isn't really a use case for it then

**Comment by thaJeztah** [comment]
I think this would be really difficult to implement (or even impossible), given that the daemon starts monitoring a container with `--rm` the moment it's started (to perform the removal).

I'll close this issue for now

**Comment by MichaelVoelkel** [comment]
> I think this would be really difficult to implement (or even impossible), given that the daemon starts monitoring a container with `--rm` the moment it's started (to perform the removal).
> 
> I'll close this issue for now

Soooo... remove the monitoring then, too? Why would _that_ be so hard?
