### ISSUE TITLE
--net host does not allow access to open sockets with rootless Docker, except from other containers on the same host

### ISSUE THREAD

**Issue by kmfrick** [moby/moby#40865]
**Description**
When using rootless Docker, `--net host` does not allow for accessing ports opened inside a container, except from another container.

**Steps to reproduce the issue:**
1. Start a container with `--net host`.
2. `netcat -l 12345`
3. From outside the container, on the same host, `netcat localhost 12345`

**Describe the results you received:**
`netcat` does not allow for sending messages.

**Describe the results you expected:**
`netcat` should work as usual and forward any line typed on the host to the container, like it happens when running `netcat -l 12345` followed by `netcat localhost 12345` on the host itself.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. I originally noticed this with [ROS](https://hub.docker.com/_/ros/): if you start `roscore` on a container and then `curl http://localhost:11311` from the host, curl fails with a "connection refused"  message, while if you run the same command from inside a different container, an (expected) HTML error page is returned, so this means other containers can access open ports on containers, but not the host. I could not reproduce this behavior with netcat, though. 
2. With normal ("rootful") Docker, ROS works as expected.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:30:32 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 50
  Running: 1
  Paused: 0
  Stopped: 49
 Images: 98
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-26-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.677GiB
 Name: nymeria
 ID: 24YU:BPGQ:GEO6:VSBU:37AZ:VCOW:6UCB:WJ4V:335Y:25VV:J5C7:WZPO
 Docker Root Dir: /home/kmfrick/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by thaJeztah** [comment]
@AkihiroSuda ptal

**Comment by AkihiroSuda** [comment]
This is b
This is b
This is by design, because we execute the whole daemon inside VPNkit/slirp4netns network space.

**Comment by AkihiroSuda** [comment]
Also, even in rootful case, please consider not using --net=host. It may result in container breakout via abstract UNIX socket. Exposing ports with -p is always preferrable.

**Comment by kmfrick** [comment]
> Also, even in rootful case, please consider not using --net=host. It may result in container breakout via abstract UNIX socket. Exposing ports with -p is always preferrable.

My specific use case is running ROS nodes inside a Docker container and making them interact with other nodes on a network. The ROS master port is configurable, but individual nodes open random, non-configurable ports: there is no way to know ahead of time which ones to expose via -p, so --net host becomes a necessity. If you have any better solutions in mind please let me know! In the meantime, thank you for letting me know this is by design, I will note this in the project's internal documentation.

**Comment by Poweranimal** [comment]
How can one access the VPNkit/slirp4netns network space from the host system?

**Comment by AkihiroSuda** [comment]
> How can one access the VPNkit/slirp4netns network space from the host system?

Please use `-p`, e.g., `docker run -p 8080:80 nginx:alpine`

**Comment by AkihiroSuda** [comment]
But if you really need to enter the namespace of VPNKit/slirp4netns, please try `nsenter -U --preserve-credentials -n -m -t $(cat $XDG_RUNTIME_DIR/docker.pid)`

**Comment by msangel** [comment]
`--net host` should behave same way in rootles as it goes in usual docker. A lot of reasons why `--net host` exists and no reasoning why this should not work in rootless.

**Comment by AkihiroSuda** [comment]
Here is a PR, but failing the CI
- https://github.com/moby/moby/pull/47103
