### ISSUE TITLE
[vscode] Dockerfile grammar does not handle single quote escaping outside of strings

### ISSUE THREAD

**Issue by alexr00** [moby/moby#40861]
Originally from @rcjsuen in https://github.com/microsoft/vscode/issues/95924#issuecomment-620016545

**Description**
When there's an escaped single quote (not in a string), then grammar doesn't recognize it as being escaped.

**Steps to reproduce the issue:**
1. Create a dockerfile (in VS Code for example) with this contents:
```dockerfile
# type on line 4, it works
# type on line 6, it fails
# type on line 7 after the apostrophe, it works

RUN \'e\'

```
2. If you inspect the scope on the line after `RUN` you'll see that it's getting a string scope:
![image](https://user-images.githubusercontent.com/38270282/80383506-ed452580-88a3-11ea-8634-a2597f76283a.png)

3. Since escaping single quotes is needed for files that have single quotes in them, this is incorrect. See example and discussion here: https://github.com/microsoft/vscode/issues/95924#issuecomment-620016545

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
