### ISSUE TITLE
'since' filter on containers/images/networks prune

### ISSUE THREAD

**Issue by joehattori** [moby/moby#40879]
**Description**

On pruning containers, images, or networks, we currently have `until` filter, which filters those objects based on timestamp and prunes only the older objects. Isn't it better to have `since` filter, which prunes the newer objects?

**Describe the results you expected:**
With `since` filter, we can prune newer containers/images/networks than the specified timestamp.

**Comment by thaJeztah** [comment]
Can you describe the use-case for this? Given that the `prune` commands were created to remove "stale" / "old" objects, I'm wondering why you're looking for removing "fresh" objects.

**Comment by joehattori** [comment]
@thaJeztah For example, when you create some images/containers for a project that you will probably not be developing anymore, it would be more convenient to have `since` filter to prune the objects. Actually this happened to me when I did my homework to emulate Ubuntu environment, which I most likely would not develop after the week, and I wish I could remove the new ones with one command instead of removing the images one by one by the id (or maybe connecting some pipes on terminal).

**Comment by tao12345666333** [comment]
I think that in the user case you said, combining a pipe with `| head -n x` can solve. (Although it requires you to control the quantity yourself)

e.g. 

```
docker rmi $(docker image ls --format '{{ .ID }}' | head -n 3 )
```

**Comment by joehattori** [comment]
@tao12345666333 Yes, it is possible to do so as you pointed out, but I just thought having another filter would be more friendly to developers. Or maybe we should avoid adding this filter because of the simplicity?
