### ISSUE TITLE
Provide a --no-op or --noop flag for general CLI use case

### ISSUE THREAD

**Issue by ORESoftware** [moby/moby#40878]
I am having this issue:
https://unix.stackexchange.com/questions/583659/how-to-pass-empty-args-to-command

it would be nice to have a flag that is a no-op (no operation), for example:

```shell
docker build --no-op  -t foo .
```

or

```shell
docker run --no-op  foo
```

**Comment by AkihiroSuda** [comment]
CLI issues should be discussed in https://github.com/docker/cli/issues

Anyway, this proposal does NOTLGTM. This should be handled in the caller script.

**Comment by ORESoftware** [comment]
this proposal is harmless, its a no-op lol
