### ISSUE TITLE
ENV variable persistent in multistage docker

### ISSUE THREAD

**Issue by rmlganesh** [moby/moby#40889]
My dockerfile looks to be below. I couldnt preserve ENV variable across the stage. 
Could some one advice from the below dockerfile and please suggest if still can shrink the image size.

> FROM xxx.com/rhel-openjdk8 AS compile-image
> 
> ENV CON_UID=55100 CON_GID=55101
> RUN mkdir -p /xxx /xxx_app && \
>         groupadd --gid $CON_GID xxxxgrp & & useradd --gid $CON_GID --uid $CON_UID -ms /bin/bash xxxusr
> 
> ADD modules/kibana.tar.gz deployments/kibana/*.sh deployments/kibana/*.key /xxxx/
> COPY certs/ /xxxx/kibana/config/certs
> 
> RUN chmod -R 775 /xxxx /xxxx_app && \
>         chown -R xxxxusr:xxxxgrp /xxxx /xxxx_app
> 
> FROM xxx.com/rhel-openjdk8 AS runtime-image
> COPY --from=compile-image /xxxx .
> 
> RUN echo $CON_UID $CON_GOD
> 
> EXPOSE 5602
> 
> CMD ["bin/bash", "/xxxx/start_kibana.sh"]

**Comment by cpuguy83** [comment]
Your `ENV` applies to the first image `compile-image`, not to `runtime-image`
Since `runtime-image` is not inheriting from `compile-image`, there is no `ENV`.

**Comment by cpuguy83** [comment]
You'll need to define the `ENV` in both places if you need it in both places.
