### ISSUE TITLE
ERRO NPM Install

### ISSUE THREAD

**Issue by Slender1808** [moby/moby#40885]
`FROM node:current-alpine`
`WORKDIR /usr/src/app`
`COPY package*.json ./`
`RUN npm install`
`COPY . .`
`EXPOSE 3000`
`CMD [ "npm", "start" ]`

**ERRO**

Step 4/7 : RUN npm install
 ---> Running in 75df1b8102b8
added 101 packages from 102 contributors and audited 230 packages in 7.208s
found 0 vulnerabilities

The command '/bin/sh -c npm install' returned a non-zero code: 4294967295: failed to shutdown container: container 75df1b8102b8fc3c6ec4606f627c9c36a3e70290efb734507eb377ade48e8257 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 75df1b8102b8fc3c6ec4606f627c9c36a3e70290efb734507eb377ade48e8257 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.


From the error, I suspect you're using the experimental LCOW feature, which is not currently maintained and may be removed at some point; if you're running Docker Desktop, and only need to run Linux images on Windows, I would recommend switching Docker Desktop to "Linux containers" https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
