### ISSUE TITLE
Cant create images or run containers | OCI runtime create failed: listen unixgram /var/run/docker/runtime-runc/moby/<hash>/notify.sock: bind: invalid argument: unknown

### ISSUE THREAD

**Issue by Strum355** [moby/moby#40886]
**Description**
Trying to build an image or run a container gives output similar to:
`docker: Error response from daemon: OCI runtime create failed: listen unixgram /var/run/docker/runtime-runc/moby/f1ecb1f43cb3a9d3e3e3dcbcb58ee71a8d8635716441bdf1935e6942c2ecd1a0/notify.sock: bind: invalid argument: unknown.`

**Steps to reproduce the issue:**
1. Try build and image or run a container

**Describe the results you received:**
```
 docker run -it --rm archlinux bash -c "echo hello world"  
docker: Error response from daemon: OCI runtime create failed: listen unixgram /var/run/docker/runtime-runc/moby/f1ecb1f43cb3a9d3e3e3dcbcb58ee71a8d8635716441bdf1935e6942c2ecd1a0/notify.sock: bind: invalid argument: unknown.
```

**Describe the results you expected:**
To be able to build or run images/containers.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0
 Built:             Thu Apr  2 00:04:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.1
  Git commit:       afacb8b7f0
  Built:            Thu Apr  2 00:04:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 0
  Paused: 0
  Stopped: 22
 Images: 274
 Server Version: 19.03.8-ce
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.6.8-arch1-1
 Operating System: Antergos Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
 Name: noah-Banana
 ID: XGLR:7WVW:AQCT:NN3W:6FFL:Q4CS:EYIW:5BWA:MKBZ:P2IO:GXD3:2AEZ
 Docker Root Dir: /docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 34
  System Time: 2020-05-01T19:20:41.583917758+01:00
  EventsListeners: 0
 Username: strum355
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Antergos Linux machine

**Comment by thaJeztah** [comment]
Could you report this with the arch linux package maintainer? We don't build (or test) for Arch linux, and the docker package you have installed is a package that's maintained and built by arch linux maintainers.

I'm closing this ticket because of the above, but feel free to continue the conversation

**Comment by Strum355** [comment]
Thing is, it did work the days previous, and the exact same version (of docker, runc and containerd) work fine on my plain arch install on laptop. Not sure if taking this to the arch maintainers is the right place given this

**Comment by thaJeztah** [comment]
At least they shouldn't be building with Go 1.14. Go 1.14 has changes that currently prevent container runtimes from working correctly. It's being worked on, but not ready yet.

**Comment by pkulkark** [comment]
@thaJeztah I am seeing this on ubuntu 18.04 too,

```bash
# docker run hello-world
docker: Error response from daemon: OCI runtime create failed: listen unixgram /var/run/docker/runtime-runc/moby/05f4d033c4f1f37beb5d5f17c3893a9a945deaed81448e2f644e0cb277fb6020/notify.sock: bind: invalid argument: unknown.
ERRO[0000] error waiting for container: context canceled 
```

```bash
# docker version 
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        00dc70017d222b178a002ed30e9321b12647af2d
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thaJeztah** [comment]
@pkulkark that doesn't look like a standard installation; there's a _really_ old version of runc installed on your system that is many commits behind the correct version (https://github.com/opencontainers/runc/compare/00dc70017d222b178a002ed30e9321b12647af2d...dc9208a3303feef5b3839f4323d9beb36df0a9dd) and is missing patches for various CVE's. 

```
runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        00dc70017d222b178a002ed30e9321b12647af2d
```


What method did you use to install docker? Did you install from the official docker packages (https://docs.docker.com/engine/install/ubuntu) ?

If I use the official packages, I get containerd 1.3.7 and runc 1.0.0-rc-10;

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by pkulkark** [comment]
@thaJeztah I did install from the official docker packages by following the steps mentioned in https://docs.docker.com/engine/install/ubuntu. I'm not very well versed with docker so I'm not sure what components to check/update to get the right runc version. Could you help me with it?

**Comment by chenk008** [comment]
In my scene, the unixgram sock path is too long

**Comment by alculquicondor** [comment]
I'm running the following:

```Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

And seeing the same issue. Any help?

**Comment by shiyingyan** [comment]
0、Uninstall the Docker Engine, CLI, and Containerd packages:
      `yum remove docker-ce docker-ce-cli containerd.io`
1、Images, containers, volumes, or customized configuration files on your host are not automatically removed. To delete all images, containers, and volumes:
    ` sudo rm -rf /var/lib/docker
     sudo rm -rf /var/lib/containerd`
2、find all docker files : `find / -name "docker"  `
3、rm all docker files finded in the previous step 
4、reinstall docker

**Comment by alculquicondor** [comment]
Hi, I've done all of that and I still got the same issue. Did it work for you?

**Comment by edpsw** [comment]
It may be a version problem. I changed the Docker version from 18.09.7 to 19.03.12 and successfully solved the problem。

**Comment by thaJeztah** [comment]
I would not recommend running docker 19.03 (or 18.09); both of those versions reached EOL a long time ago, are no longer maintained, and have unpatched vulnerabilities. If possible, I'd recommend upgrading to a currently maintained version (but make sure to verify in a test environment before upgrading your production setup).
