### ISSUE TITLE
Feature request: Allow forcing log rotation

### ISSUE THREAD

**Issue by spellr** [moby/moby#40896]
Allow initiating a log rotation by signalling to moby's service.
Like [rsyslog](https://github.com/syslog-ng/syslog-ng/blob/master/contrib/fedora-packaging/syslog-ng.logrotate#L4) and other services allow, sending a signal to the service will trigger a log rotation.

This is helpful for 2 reasons:

1. To re-open the log file if something has changed in the underlying file-system like a mount etc.
2. We'll be able to use linux's `logrotate` cron job to rotate moby's logs, allowing us to use the same system-wide log rotation configuration for all services.

**Comment by thaJeztah** [comment]
This would be for the container logs or the daemon logs?

If for the container logs, I think this will be difficult (or not possible), given that the logging driver used, and log-rotation settings (e.g. "max-files" and "max-size") are configured for each container individually. Not all logging drivers support log-rotation, and if a container is configured without log-rotation, this would probably have to truncate the file instead of "rotate".

/cc @cpuguy83

**Comment by spellr** [comment]
I think we want both container logs and daemon logs.
IMO if the driver doesn't support log rotation, we don't have to truncate, just re-opening and appending to the file. If the file doesn't exist, we will create a new file in the mount, and if it does exist, we won't delete any data.

**Comment by thaJeztah** [comment]
> I think we want both container logs and daemon logs.

For the _daemon_ logs, I think this should be handled by your system logger; the `dockerd` daemon writes logs to `stdout` / `stderr`, and doesn't write to a file by itself (when running with systemd, that output is handled by / logged by `journald`).

For container logs, this may be more complicated (as outlined above); you could consider configuring the daemon to set `syslog` or `journald` as the default logging driver for containers (and as such, have journald/syslog handle rotation).

**Comment by cpuguy83** [comment]
👎  To this change. It just does not fit in with the current logging model at all.

To support such a scenario, probably what is outlined in https://github.com/moby/moby/issues/40517 needs to be done... e.g. allow admins to swap out the logging infrastructure with something else entirely.

**Comment by thaJeztah** [comment]
let me close this in favour of https://github.com/moby/moby/issues/40517 for further discussion
