### ISSUE TITLE
Detect whether `nvidia-container-toolkit` is installed without starting a container?

### ISSUE THREAD

**Issue by dzhu** [moby/moby#40903]
I'm working on an application for which it would be helpful to detect whether `nvidia-container-toolkit` is installed, so that the application can tell whether it will be able to start GPU-enabled containers later on. The best way I know of now is to actually start a container with GPUs requested (something equivalent to `docker run --gpus 0 debian true`) and see if it fails with a particular error ("could not select device driver").

That's not a _huge_ cost, but having to look for a specific error message is odd and the whole process slows down application startup, may require an image to be downloaded (which may be difficult in some installation scenarios), and adds complexity to the code (it's using the API, so it has to explicitly check if the image is present, pull it if not, create the container, and start the container).

With `nvidia-docker2`, it is possible to simply query `/info` and check whether "nvidia" is in the list of runtimes, but I don't see an equivalent for `nvidia-container-toolkit`, and I was hoping that something similar could be added or to find out if there is something that I missed.

(Apologies if this should've gone to https://github.com/NVIDIA/nvidia-docker, but I figured this is more about querying Docker's capabilities generally and not actually that specific to the NVIDIA packages. I'll be happy to take the issue over there if the maintainers here think otherwise.)

**Comment by thaJeztah** [comment]
@RenaudWasTaken ptal

**Comment by RenaudWasTaken** [comment]
Docker does basically a `which nvidia-container-toolkit`, you could do the same here :)
See: https://github.com/moby/moby/blob/master/daemon/nvidia_linux.go#L33-L36

**Comment by dzhu** [comment]
Ah, that's very interesting, thanks! But there's another wrinkle: the application is often running inside a container itself, with only the Docker socket mounted from the host, in which case that won't be reliable. (I guess it could try detecting whether it's in a container, but I don't like the sound of that.) Anyway, we decided to keep it simple and just skip the check, which will usually be good enough. So my personal need is not that great; I'll leave this issue open, because I think it's a reasonable request generally, but feel free to close if you think it's out of scope.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
