### ISSUE TITLE
curl: option --progress: is ambiguous

### ISSUE THREAD

**Issue by cristianrz** [moby/moby#40912]
**Description**

`download-frozen-image-v2.sh` does not download because of a wrong option passed to curl

**Steps to reproduce the issue:**
1. run `download-frozen-image-v2.sh dummy ubuntu:latest`

**Describe the results you received:**

```
curl: option --progress: is ambiguous
```

**Describe the results you expected:**

The image to be downloaded successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Is `--progress` the correct option? On all the implementations I have checked it is called `--progress-bar`. If both exist, the script should check for which one is installed, otherwise correct the option to `--progress-bar`. 

Never worked with pull requests but happy to try and fix it if someone answers the question above :)

**Output of `docker version`:**

N/A

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using gnu curl 7.68.0

**Comment by thaJeztah** [comment]
Interesting; nice catch! looks like that was added in the very first implementation of that script (https://github.com/moby/moby/commit/351074edcd22e4ca587713feda541268a66cdb86 / https://github.com/moby/moby/pull/11119). At the time,  the `Dockerfile` used ubuntu 14.04, but even that version doesn't seem to have `--progress`;

```bash
docker run -it --rm ubuntu:14.04 sh -c 'apt-get update -qq && apt-get install -y -qq curl && curl --help | grep progress'
# ...
#  -#, --progress-bar  Display transfer progress as a progress bar
```

Perhaps it was originally written to use `wget`;

```bash
docker run -it --rm ubuntu:14.04 sh -c 'apt-get update -qq && apt-get install -y -qq wget && wget --help | grep progress'
# ...
#        --progress=TYPE           select progress gauge type.
```

But that doesn't even seem to match 🤔

**Comment by thaJeztah** [comment]
I guess @tianon may recall 😂 (but it's been a very long time ago)

Let me know if you want to open a PR, or if you want me to open one

**Comment by cristianrz** [comment]
I'll open one!

**Comment by cristianrz** [comment]
Just created https://github.com/moby/moby/pull/40914. First pull request so let me know if everything's okay!

**Comment by cristianrz** [comment]
Now that I am thinking, isn't the v1 API deprecated [1]? Which means the v1 version of the script should not work even if this issue is fixed. The V1 version does not work at the moment but not sure if it is because of a different reason.

[1] https://www.docker.com/blog/registry-v1-api-deprecation/

**Comment by tianon** [comment]
Heh, it was probably written against an older version of `curl` where `--progress` wasn't ambiguous (best guess).

The v1 script is very likely not working for more reasons than just the deprecation, but even if we fix the "more reasons" I don't think it'll work (since v1 is deprecated).

I believe we opted to keep it merely as a reference, but at this point I think it's time to finally just delete it. :sweat_smile:

**Comment by tianon** [comment]
Fixed by https://github.com/moby/moby/pull/40914 :+1:
