### ISSUE TITLE
Feature Proposal: Copying activity indicator for docker cp command

### ISSUE THREAD

**Issue by jeffabailey** [moby/moby#40936]
**Description**

When running this command show an activity indicator.

`docker cp`

When running it could some sort of spinner like this.

https://www.shellscript.sh/tips/spinner/spinner.gif

If progress doesn't start or fails midstream the spinner would stop.

**Comment by thaJeztah** [comment]
This looks like an enhancement for the CLI, which is in a separate repository; could you reopen this in https://github.com/docker/cli/issues ?

**Comment by jeffabailey** [comment]
Done: https://github.com/docker/cli/issues/2564
