### ISSUE TITLE
idtools: NewIdentityMapping should not take groupname as an argument

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40947]
https://github.com/moby/moby/blob/298ba5b13150bfffe8414922a951a7a793276d31/pkg/idtools/idtools.go#L117-L120

`/etc/subgid` should not be looked up by a groupname: http://man7.org/linux/man-pages/man5/subgid.5.html

>     Each line in /etc/subgid contains a user name and a range of subordinate group ids that user is allowed to use.

**Comment by AkihiroSuda** [comment]
In addition, the function should support looking up the mapping by UID number.

**Comment by akhilerm** [comment]
I am willing to work on this issue. cc  @AkihiroSuda

**Comment by akhilerm** [comment]
> In addition, the function should support looking up the mapping by UID number.

In that case what should be the arguments passed?

**Comment by AkihiroSuda** [comment]
Just take username string as the argument, and look up the username into UID number

**Comment by akhilerm** [comment]
ohkay. got it.

**Comment by akhilerm** [comment]
At the caller site [here](https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/daemon/daemon_unix.go#L1225), we are already checking with uid. So, why should we do it again in `NewIdentityMapping`?

**Comment by AkihiroSuda** [comment]
We don't need to do that then
