### ISSUE TITLE
Docker SDK 1.31.1 (GO) broken references to 3rd party package github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by ssudweeks** [moby/moby#40954]
**Description**

I am completely new to the GO programming language.  I am learning it for the purpose of interacting with the Docker daemon via the Docker SDK.

I am using GO v1.14

I am following this documentation and guide https://docs.docker.com/engine/api/sdk/

Executing 'go get github.com/docker/docker/client'
results in this download and its dependencies 'go: found github.com/docker/docker/client in github.com/docker/docker v1.13.1'

Things work nicely for me for the basic examples.  But when I move on to try to use Builder I start running into an issue of your package referencing a package with incorrect upper case 'S'.

github.com/docker/docker/builder imports
  github.com/docker/docker/image imports
  github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
    module declares its path as: github.com/sirupsen/logrus
    but was required as: github.com/Sirupsen/logrus

Can you update your library to reference a specific version of github.com/Sirupsen/logrus before their rename?  Or can you update your library to reference their new name with the lower case 's'?  Or is there something I haven't learned about the GO lanuage where I can correct for an account for this on my system?

Any direction would be appreciated.  I have uploaded my failing code to https://github.com/ssudweeks/goexample

**Steps to reproduce the issue:**
1. starting from a fresh system,  
2. Get the default SDK client by executing 'go get github.com/docker/docker/client'
3. Write up a simple GO app to interact with the Docker daemon's Build engine
  func main() {
	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	buildContextDirectory, _, _ := builder.GetContextFromLocalDir(".","Dockerfile")
	buildContext := strings.NewReader(buildContextDirectory)
	build, err := cli.ImageBuild(context.Background(), buildContext, types.ImageBuildOptions{})

	if err != nil {
		panic(err)
	}

	body, _ := ioutil.ReadAll(build.Body)
	build.Body.Close()
	println(body)
}
3. Add necessary imports using intelij
  import (
	"context"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/builder"
	"github.com/docker/docker/client"
	"io/ioutil"
	"strings"
)
4. execute 'go mod vendor' and/or 'go build'

**Describe the results you received:**
go: scott.com/goexample imports
        github.com/docker/docker/builder imports
        github.com/docker/docker/image imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus

**Describe the results you expected:**
I would expect the GO package to build successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
C:\src\goexample>docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
C:\src\goexample>docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 39
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: IRGK:262E:4UIE:YT5F:IJYA:4VMX:FKNB:L3PB:5U3U:U3CM:B7IY:GS5V
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 34
  Goroutines: 50
  System Time: 2020-05-11T20:27:12.34704689Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
local physical windows 10

**Comment by cpuguy83** [comment]
Don't use 1.13, it is very old.
You can't really rely on modules to pick a good version from this repo since it relies on smever semantics, which this project does not use (it uses calver... and a long time ago it was semver-ish, hence the 1.13).

"19.03.8" is the latest release.
