### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [moby/moby#40960]
**Description**

I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running docker on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for docker if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/moby/moby/blob/a93e9eb0e95c6b2db723d0d2391e4559554c8597/daemon/logger/gcplogs/gcplogging.go#L198

**Steps to reproduce the issue:**

--

**Describe the results you received:**

--

**Describe the results you expected:**

--

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

master branch,
commit: a93e9eb0e95c6b2db723d0d2391e4559554c8597

**Output of `docker info`:**

--

**Additional environment details (AWS, VirtualBox, physical, etc.):**

--

**Comment by AkihiroSuda** [comment]
We don't support x86_32 and pre-ARMv6k seems too old as well. (200X)
