### ISSUE TITLE
AWS EC2 instance <Windows 10> - failed to start docker container

### ISSUE THREAD

**Issue by chavansachin20** [moby/moby#40972]
This issue was raised in docker / for-win  > https://github.com/docker/for-win/issues/6730 

as per request raising same here in https://github.com/moby/moby

I have tried with the latest version of my channel (Stable or Edge)
I have uploaded Diagnostics 

**Expected behavior**
Docker should start any container 
as of now trying to create hello-world container with below command
`docker run hello-world `

**Actual behavior**
docker creates container but fails to start the container, error as below
> docker : Error response from daemon: hcsshim::CreateComputeSystem 
7ddc29884f4c63413ca009346bbd21442de9866fae5941a58d3d331baf6be110: The virtual machine could not be 
started because a required feature is not installed.

**Information**
- Windows Version: Windows 10 
- Docker Desktop Version: 
- ![image](https://user-images.githubusercontent.com/5293496/82016071-d1ac8e00-969d-11ea-81b7-685c1dd57130.png)
- Using AWS EC2 instance: this was working, suddenly stopped working on the creation of containers.

**Steps to reproduce the behavior**
1. Installer Docker for Windows 
2. Start Docker 
3. Open PowerShell with Run as Admin - execute the command : docker run hello-world  
4. error as below Screenshot 

 
**Screenshot :**
![image](https://user-images.githubusercontent.com/5293496/82015873-69f64300-969d-11ea-90d6-4fe57f3d240b.png)

**Comment by shlok57** [comment]
Is there any update on this issue? I am currently stuck at the same problem.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
