### ISSUE TITLE
DRM drivers are disabled by Kernel, GUI is slow, rebuilding HyperKit VM not possible

### ISSUE THREAD

**Issue by ogryb** [moby/moby#40980]
**Description**

While DRM drivers are included to HyperKit's modprobe.d/kms.conf file
```
options radeon modeset=1
options i915 modeset=1
options nouveau modeset=1
```
DRM itself is disabled at Kernel level
```
/ # gunzip -c /proc/config.gz | grep DRM
# CONFIG_DRM is not set
# CONFIG_DRM_DP_CEC is not set
# CONFIG_DRM_XEN is not set
```
I've tried rebuilding HyperKit with updated Kernel using provided linuxkit.yml file, but it was not possible  because desktop-host-tools image is private:

> $ docker pull docker/desktop-host-tools:e881e43ded9958267f34ddc17c0bd3e2
> Error response from daemon: pull access denied for docker/desktop-host-tools, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

As a result, GUI apps like Chromium that require DRM drivers for fast rendering crash and the only way to run them is to disable GPU drivers all together, but that makes GUI extremely slow.

The best way of fixing it would be to allow re-building HyperKit VM from /etc/linuxkit.yml, but if 's not possible, please rebuild the VM with DRM enabled in Kernel. 

**Steps to reproduce the issue:**
1. Create a docker container with ArchLinux and LXDE enabled on Mac 
2. Install XQuartz on Mac, make sure that it accept X11 connections in UI and through "xhost + 127.0.0.1"
3. Run lxsession inside the container
4. When LXDE becomes visible on Mac in XQuartz window, run chromium from a terminal to see the output: 
[ogryb@79b8c59cd1f4 /]$ chromium
[1203:1203:0516/185814.970352:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[1203:1230:0516/185815.025320:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1203:1230:0516/185815.025368:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1203:1230:0516/185815.086814:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1203:1230:0516/185815.086871:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1203:1203:0516/185815.123042:ERROR:browser_switcher_service.cc(238)] XXX Init()
[1203:1277:0516/185815.232075:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1203:1277:0516/185815.232668:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
.... 
 Then disable GPU drivers and observe that Chromium works, but is very slow:
`chromium   --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage
`
**Describe the results you received:**
GUI that requires DRM drivers doesn't work. If DRM drivers are disabled, it becomes very slow and not very useful.

**Describe the results you expected:**
GUI should work with DRM drivers to achieve a reasonable performance

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 52
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: 4ITU:ZC5U:U65E:JQ66:ZOQ4:I4UU:SFAD:IKO3:BLLU:PJN5:NYHK:CAQO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 50
  Goroutines: 68
  System Time: 2020-05-17T02:28:37.702332Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacBookPro 2019
MacOS 10.15.4

**Comment by thaJeztah** [comment]
could you open this in the https://github.com/docker/for-mac/issues issue tracker? This looks specific to docker for mac, which is not maintained in this repository
