### ISSUE TITLE
Node LB not deleted after container exits itself (cause IP overlapping)

### ISSUE THREAD

**Issue by xinfengliu** [moby/moby#40989]
**Description**

Since docker 18.09, there's a node LB per network on the node. When the last container of the network is finished, the node LB is removed. 

This is correct when the swarm task container is explicitly shutdown. However, when the task container exits itself (either due to task completion or failure), the node LB is NOT removed. This is dangerous and could cause IP overlapping.

**Steps to reproduce the issue:**
On a simple 1-node swarmkit cluster:

1. Create a very small network to make IP overlapping quicky happen
`$ docker network create -d overlay --subnet 10.6.6.0/29 net0`

2. Create a simple service that will complete by itself. 
`$ docker service create --network net0 --name bb --restart-max-attempts=1 --restart-delay=10s busybox sleep 5`

3. Wait 30s for the service tasks to complete, at this time there's no container running, but node LB is still there.
```
$ docker network inspect --format '{{range .Containers}}{{printf "%s\t%s\n" .Name .IPv4Address}}{{end}}' net0
net0-endpoint	10.6.6.4/29
```
4. Now try creating an IP overlapping
```
$ docker service scale bb=3
$ docker service ps bb --no-trunc
```
You will see `"starting container failed: Address already in use"`

**Describe the results you received:**
node LB is not deleted and could cause IP overlapping later.

**Describe the results you expected:**
node LB should be deleted when the last container on this network on this node exists.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
I can reproduce this issue on any docker 18.09 and 19.03 version.

**Comment by thaJeztah** [comment]
ping @arkodg @dperny PTAL

**Comment by thaJeztah** [comment]
oh! I see there's a PR as well; thanks! https://github.com/moby/moby/pull/40997

**Comment by mightydok** [comment]
+1

**Comment by tartemov** [comment]
Hi! I meet issue with overlapping IP for services and LB in production env. Is there any workaround?

**Comment by xinfengliu** [comment]
@tartemov
 
You can create a dumb global docker service, attaching all overlay networks you are using.  This will make the node LB always exist to mitigate the cases that node LB should have been removed but actually not removed due to current bugs.

When a new network is added to the cluster or an existing network is removed, you can use `docker service update --network-add or --network-rm` to update the dumb service.

**Comment by tartemov** [comment]
@xinfengliu @thaJeztah Hi! Is there any information about this bug? Do you have version that this issue assigned on?
