### ISSUE TITLE
Possible incorrect use of /etc/subgid

### ISSUE THREAD

**Issue by szlend** [moby/moby#40986]
**Description**

Looking at the documentation for [subgid(5)](http://man7.org/linux/man-pages/man5/subgid.5.html), it says this:

```
Each line in /etc/subgid contains a user name and a range of
subordinate group ids that user is allowed to use. This is specified
with three fields delimited by colons (“:”). These fields are:

- login name or UID
- numerical subordinate group ID
- numerical subordinate group ID count
```

However, when running Docker with `--userns=foo:bar`, it tries to lookup `/etc/subgid` for the group name `bar`, raising the following error:

```
Can't create ID mappings: No subgid ranges found for group "bar"
```

According to the documentation, the first column in `/etc/subgid` is **not** a group name, but a user name.

In most cases this is not an issue, because most users have a corresponding primary group with the same name. However on some distributions local users have a primary group `users`, so you actually want to remap to something like `--userns=foo:users`.

**Steps to reproduce the issue:**
1. Create a user `foo` with the group `bar`
2. Set up `/etc/subuid` and `/etc/subgid` for the user `foo`
3. Run the Docker daemon with `--userns=foo:bar`

**Describe the results you received:**
The daemon fails to start with the error: `Can't create ID mappings: No subgid ranges found for group "bar"`

**Describe the results you expected:**
The daemon should start and use the correct uid/gid user namespace mapping.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0d8d4f9d2a8e8736e9c993e672b41f3
 Built:             Sun May 10 13:47:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested under NixOS 20.03

**Comment by thaJeztah** [comment]
@estesp @AkihiroSuda ptal

**Comment by AkihiroSuda** [comment]
duplicate: https://github.com/moby/moby/issues/40947
