### ISSUE TITLE
`docker build` hangs on FROM line

### ISSUE THREAD

**Issue by faucherb94** [moby/moby#40996]
**Description**

`docker build` hangs indefinitely, without even getting through the first line of the Dockerfile.

This appears to have happened in the past: https://github.com/moby/moby/issues/36067 but that issue went stale.

All other `docker` commands work as expected, it's just `build` that hangs.

**Steps to reproduce the issue:**
1. Create a docker file with just a `FROM` line
2. Run `docker build -t test:test .`
3. Wait indefinitely, nothing happens.

**Describe the results you received:**

```
> docker build -t test:test -f test.Dockerfile .

```

The cursor just hangs on a newline, showing no output.

**Describe the results you expected:**

`docker build` to execute the lines in the Dockerfile.

**Additional information you deem important (e.g. issue happens only occasionally):**

`docker build` was working fine for me all day. I went to make dinner, came back, and now it hangs.

This also happened to me on another machine - `docker build` had been working fine for months, then one day it started hanging.

This happens both when swarm mode is active and not.

The image I'm referencing in the `FROM` line has already been pulled.

**Output of `docker version`:**

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

Also seen on:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: d47wwez95z7oiezi0fsiumji6
  Is Manager: true
  ClusterID: rkqgrkc140h32giv0ligr0qnb
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.207.0.93
  Manager Addresses:
   10.207.0.93:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-101-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.79GiB
 Name: [redacted]
 ID: ZGUR:3PM4:XOKL:KAL7:IZVB:W73I:RQGT:Y76A:TAXZ:J7AS:6OC3:WAUK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

Also seen on:
```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: rynxaomvk9rpyuidhmnsm2pqa
  Is Manager: true
  ClusterID: wkdygqj67kpg11njnrqvvg0xa
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 127.0.0.1
  Manager Addresses:
   127.0.0.1:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: [redacted]
 ID: WV76:MUZJ:KSJC:USSR:V5TI:EAPR:JRJT:5KNY:2ARO:347H:QF25:3NA7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

These are both on-prem virtual machines.

**Comment by thaJeztah** [comment]
Are you able to reproduce this issue on the current patch release of 19.03? (19.03.9 at time of writing).

Docker 19.03.7 and up have a fix for a deadlock in the builder when using BuildKit (see the [release notes](https://docs.docker.com/engine/release-notes/#19037), and the related pull-request: https://github.com/moby/moby/pull/40557

**Comment by thaJeztah** [comment]
oh, I just see your second `docker version` shows 19.03.8. 🤔 

Just a random thought; have you tried running `docker builder prune`, to cleanup build cache?

**Comment by faucherb94** [comment]
```docker builder prune
WARNING! This will remove all dangling build cache. Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B```

Did not help.

**Comment by faucherb94** [comment]
@thaJeztah Any idea what might be going on?

**Comment by thaJeztah** [comment]
No, can't tell from the information that's here. 

- Are you seeing the same both with `DOCKER_BUILDKIT=1` and with `DOCKER_BUILDKIT=0` ?
- Is there anything in the daemon or system logs?
- Is build only failing with that specific image, or also with other images?
- You mention "These are both on-prem virtual machines."; are you connecting to all of those VM's from the same CLI, or using a CLI inside the VM?

**Comment by faucherb94** [comment]
> Are you seeing the same both with `DOCKER_BUILDKIT=1` and with `DOCKER_BUILDKIT=0` ?

Setting `DOCKER_BUILDKIT=0` changes nothing, still hangs. Setting `DOCKER_BUILDKIT=1` makes the output look completely different, and does get the build working!

> Is there anything in the daemon or system logs?

`sudo journalctl -u docker` shows nothing relevant.

> Is build only failing with that specific image, or also with other images?

Other images as well.

> You mention "These are both on-prem virtual machines."; are you connecting to all of those VM's from the same CLI, or using a CLI inside the VM?

Not sure what you mean by "connecting to all of those VMs from the same CLI". I'm SSHing into the VMs then running `docker` commands while SSH'd into them.

**Comment by hasheddan** [comment]
@thaJeztah @faucherb94 I have experienced this exact behavior on my local machine after updating to Ubuntu 20.04. One thing to add that I don't see mentioned anywhere else in this thread is that `sudo docker build` works fine for me, and the solution of `DOCKER_BUILDKIT=1` also works without `sudo`. I have included relevant information below, including a snippet from `strace docker build`.

<details>
  <summary>docker info</summary>

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-48-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.29GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

</details>

<details>
  <summary>strace docker build</summary>

After a bunch of `EPERM (Operation not permitted)` I just get the following forever:

```
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562d31cc5748, FUTEX_WAIT_PRIVATE, 0, NULL) = 0

```

</details>

**Comment by thaJeztah** [comment]
Closing as this went stale, but if you are still running into this, and think there's a bug at hand (and have ways to reproduce), feel free to open a new ticket
