### ISSUE TITLE
Windows log rotation errors with active readers

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#40999]
On Windows, when the daemon attempts to rotate logs, if there is an active reader, the rotation fails.
This failure was totally unrecoverable until https://github.com/moby/moby/pull/40920
However that PR only allows the daemon to recover after an error.

The issue occurs when the daemon tries to rename a file that a log reader (e.g. `docker logs` client) has open.
This should have, based on the best info I've found, been fixed by using FILE_SHARE_DELETE (https://github.com/moby/moby/pull/39974), however that does not seem to be the case.
Furthermore, I've tried to apply this same change to all file opens in that package and still hit the same issue.

What this means right now is that if there is a `docker logs` client open and log rotation is enabled, if a file is ready for rotation then log writes will error out until the log client is gone.

**Comment by cpuguy83** [comment]
Help wanted

**Comment by kevpar** [comment]
@cpuguy83 What is the actual error when rotating? Does moving/deleting the log file fail with ERROR_SHARING_VIOLATION, or does something else fail?

I think every process that has the log file open will need to have FILE_SHARE_DELETE added to their flags. Is it possible something has it open that isn't using this flag?

**Comment by cpuguy83** [comment]
The actual error is "the file is being used by another process".
The only process that has the file open would be dockerd.
I have tried to ensure that `FILE_SHARE_DELETE` is applied everywhere but ran into the same issue, which makes me suspect that we aren't doing this correctly.

**Comment by kevpar** [comment]
If you're seeing "The process cannot access the file because it is being used by another process.", then that's ERROR_SHARING_VIOLATION.

If you use [Sysinternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), you should be able to ctrl-f and search for the log file path, and see if anything else has it open.

**Comment by cpuguy83** [comment]
I'm certain it's only docker that has it open, because as soon as the client disconnect we can rotate the logs again.

**Comment by kevpar** [comment]
Could you link me to where the writing and reading/rotating of the log file occurs? I can take a look to see if I have any ideas.

**Comment by cpuguy83** [comment]
Error occurs in the rotate call: https://github.com/moby/moby/blob/89382f2f20745b9e63bed6c066f104980dff4396/daemon/logger/loggerutils/logfile.go#L182-L222

Read is here: https://github.com/moby/moby/blob/89382f2f20745b9e63bed6c066f104980dff4396/daemon/logger/loggerutils/logfile.go#L323

The read is what I tried to patch to make sure we open with FILE_SHARE_DELETE (the other code should already be doing this).

**Comment by kevpar** [comment]
It looks like `ReadLogs` is still using `os.Open` instead of `openFile`, so I don't think it will have FILE_SHARE_DELETE set. I think if you change this to use `openFile` it might fix the issue.

https://github.com/moby/moby/blob/master/daemon/logger/loggerutils/logfile.go#L325

**Comment by cpuguy83** [comment]
Thanks... I sear I tried this and it didn't work, but I might have missed a spot.

Confirmed it works with this change: https://github.com/moby/moby/pull/41100
