### ISSUE TITLE
Latest Edge Version (2.3.1.0) crashing on startup on Mac OS

### ISSUE THREAD

**Issue by dejan9393** [moby/moby#41005]
The latest edge release seems to be crashing on startup on my Macbook Pro running Mac OS Mojave 10.14.6, here's a screenshot of what's happening:

<img width="597" alt="Screen Shot 2020-05-21 at 10 51 55 am" src="https://user-images.githubusercontent.com/13180986/82524771-1f7c3700-9b73-11ea-8466-6c466c5686e3.png">

Hitting Diagnose & Feedback just opens a new window with a seemingly permanent spinner:

<img width="717" alt="Screen Shot 2020-05-21 at 2 56 32 pm" src="https://user-images.githubusercontent.com/13180986/82524854-49355e00-9b73-11ea-98c4-ff8e626d0ea4.png">

**Comment by thaJeztah** [comment]
Could you open this in the Docker for Mac issue tracker? https://github.com/docker/for-mac/issues
