### ISSUE TITLE
Empty logs are not Syslog RFC 5424 compliant

### ISSUE THREAD

**Issue by evandam** [moby/moby#41010]
**Description**

As outlined in https://github.com/treasure-data/omnibus-td-agent/issues/248, Docker logs using syslog RFC 5424 are not compliant and tools like Fluentd are unable to parse them.

**Steps to reproduce the issue:**
`docker-compose.yml`:
```yaml
version: '3'
services:
  fluentd:
    command: ["fluentd", "-c", "/etc/fluentd.conf"]
    image: fluent/fluentd:v1.10.4-1.0
    volumes:
      - ./fluentd.conf:/etc/fluentd.conf
    ports:
      - 5140:5140/udp
  test:
    image: alpine
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5140"
        tag: test
        syslog-format: rfc5424
    depends_on:
      - fluentd
```

`fluentd.conf`:
```
<source>
  @type syslog
  tag syslog.docker.containers
  port 5140
  protocol_type udp
  <parse>
    message_format rfc5424
  </parse>
  @log_level info
</source>

<match syslog.docker.containers.**>
  @type stdout
</match>
```

```sh
docker-compose up fluentd
docker-compose run test echo ""
docker-compose run test echo "test"
```

**Describe the results you received:**

```
fluentd_1  | 2020-05-21 21:18:10 +0000 [warn]: #0 failed to parse message data="<30>1 2020-05-21T21:18:10Z default test 2139 test - "
fluentd_1  | 2020-05-21 21:18:14.000000000 +0000 syslog.docker.containers.daemon.info: {"host":"default","ident":"test","pid":"2139","msgid":"test","extradata":"-","message":"test"}
```

**Describe the results you expected:**

```
fluentd_1  | 2020-05-21 21:18:14.000000000 +0000 syslog.docker.containers.daemon.info: {"host":"default","ident":"test","pid":"2139","msgid":"test","extradata":"-","message":""}
fluentd_1  | 2020-05-21 21:18:14.000000000 +0000 syslog.docker.containers.daemon.info: {"host":"default","ident":"test","pid":"2139","msgid":"test","extradata":"-","message":"test"}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

As per https://github.com/treasure-data/omnibus-td-agent/issues/248, it looks like Docker is including extra SP in the log when there is no MSG.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 33
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1065-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: nomad-compute-i-0fc56cf7700d38a6b.dev-usw2-dev1
 ID: DKFC:27MZ:XONM:TQUD:LNZ3:IKR4:SVNI:NITE:GQHV:3EHC:NVCW:UNHE
 Docker Root Dir: /docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by oldium** [comment]
RFC5424 allows empty MSG part after space:

     MSG             = MSG-ANY / MSG-UTF8
     MSG-ANY         = *OCTET ; not starting with BOM

*OCTET is 0 to infinite repetitions. So MSG can reduce to empty string, meaning the message is there, but empty.

**Comment by thaJeztah** [comment]
Thanks for reporting!

@oldium trying to understand your comment; you mean that the current implementation is "correct", or that docker should be adding a space in case the message is empty?


FWIW, we had a similar case for the Gelf (https://github.com/moby/moby/pull/40234) and Splunk (https://github.com/moby/moby/pull/34520) logging drivers; for those (see the linked PR's), a check was added for empty messages, in which case the log entry would be skipped.

I think it could make sense to apply a similar fix here, which would involve a similar check in https://github.com/moby/moby/blob/bc709991b37270e87b84d0102366deff7e402531/daemon/logger/syslog/syslog.go#L134-L137

Feel free to contribute a PR (or happy to open one)

**Comment by oldium** [comment]
@thaJeztah RFC 5424 states that log message format is `HEADER SP STRUCTURED-DATA [SP MSG]`. Report at treasure-data/omnibus-td-agent#248 shows a Docker log message with space at the end with no message. They thought that having a space `SP` with no message `MSG` is not valid (see the optional part `[SP MSG]`) and that Docker is not following RFC 5424. I checked the `MSG` definition in RFC 5424 and it says that it is `MSG = MSG-ANY / MSG-UTF-8` (one of alternatives) and that `MSG-ANY = *OCTET`. The star at the beginning means repetition, this exact notation means 0 to infinite repetitions. So I think that empty `MSG` (i.e. zero-length `MSG`) is valid according to RFC 5424 and Docker is not generating invalid logs.

Different question is why Docker generates empty log messages.

**Comment by thaJeztah** [comment]
> Different question is why Docker generates empty log messages.

Logging in Docker is line-delimited, so a process in the container that generates an empty line on `stdout` / `stderr` will generate a log-entry.

Wether or not those are useful is another question. Generally, I would say: we could skip those entries. That said, I've seen users dump "structured" output on stdout/stderr, and trying to reconstruct that structured output from the logs, so there _is_ a small risk we would break users (but given that other logging drivers already disallow it, I think the risk is small)

**Comment by wangyumu** [comment]
as the driver of Gelf and Splunk already skip these entries, so we'd better keep compliance first, let me make a trivial PR for it.
