### ISSUE TITLE
Docker exec hangs when child process still running 

### ISSUE THREAD

**Issue by OleksiiStepanov** [moby/moby#41052]
**Description**

When command executed by docker exec create child process, and this process still work after command exit. On next run command hung on exit.

For example:
`docker exec test sh -c 'exec sleep infinity &'`

first time command exited as expected but when execute same command again command will exit only if child process finished

same result if run command interactive with -it options

I think related bug #24974 describe same issue but was closed  
  
**Steps to reproduce the issue:**
1. Run any docker image based on alpine linux
2. Run command `docker exec test sh -c 'exec sleep infinity &'`  
3. Run command  again  `docker exec test sh -c 'exec sleep infinity &'`

**Describe the results you received:**
after run command second times or more command still wait while child processes not finished  

**Describe the results you expected:**
after run command second times or more command should exit immediately.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 13
  Paused: 0
  Stopped: 8
 Images: 44
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.3GiB
 Name: billion-az
 ID: NF6I:PGKE:RMIZ:RQGF:JDO2:GX5M:K5NY:WW6L:VP6R:IR5H:XTHB:JBGH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
it was tested with 2 different host OS: 
1. SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
2. Ubuntu 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Are both cases running the same version of Docker? Are you seeing the same issue with the latest patch release of docker (19.03.11) and containerd.io (1.2.13) ?

I tried reproducing, but didn't see the problem occur;

```bash
$ docker run -d --name test nginx:alpine

$ docker exec test sh -c 'exec sleep infinity &'
$ docker exec test sh -c 'exec sleep infinity &'
$ docker exec test sh -c 'exec sleep infinity &'
$ docker exec test sh -c 'exec sleep infinity &'
```

**Comment by OleksiiStepanov** [comment]
After upgrade to latest (19.03.11) version everything works as expected.
Thank you @thaJeztah
