### ISSUE TITLE
Encounter error from expect command when building Docker image

### ISSUE THREAD

**Issue by thyrlian** [moby/moby#41050]
**Description**
Encounter error `couldn't execute "xxx": no such file or directory` from `expect` command when running in Dockerfile (but works when running in a container).

**Steps to reproduce the issue:**
1. Have a Dockerfile like [this](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/vnc/Dockerfile#L20-L23), just replace the package `tightvncserver` with `tigervnc-standalone-server`;
2. Create a expect script like [this](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/vnc/vncpass.sh);
3. Try to build the image by `docker build ...`.

**Describe the results you received:**
```
spawn vncpasswd
couldn't execute "vncpasswd": no such file or directory
    while executing
"spawn vncpasswd"
```

**Describe the results you expected:**
A Docker image could be built successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
An interesting fact/comparison is:
* When running the same command inside a docker container (built with previous successful steps), it has no problem at all.  I suspected it might be the shells' difference, and changing the shebang inside the expect script wouldn't make any change.
* When using the same expect script with the original `tightvncserver` package, the image could be built without any issue.  The issue only occurs with `tigervnc-standalone-server` package.

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**
```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 55
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.811GiB
 Name: docker-desktop
 ID: 6BZ3:KM2Y:TIEC:W7O2:OYHQ:D4EV:W4AJ:FAMP:N7SL:5HIQ:RADS:GQET
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-06-01T09:10:47.3994187Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment]
Getting the same error when running in a regular container;

start a container;

```bash
docker run -it --rm ubuntu:20.04 sh
```

Create `/tmp/vncpass.sh`:

```bash
cat > /tmp/vncpass.sh <<EOD
#!/bin/sh

password="android"
password_view_only="docker"

/usr/bin/expect <<EOF
spawn vncpasswd
expect "Password:"
send "$password\r"
expect "Verify:"
send "$password\r"
expect "Would you like to enter a view-only password (y/n)?"
send "y\r"
expect "Password:"
send "$password_view_only\r"
expect "Verify:"
send "$password_view_only\r"
expect eof
exit
EOF
EOD
```

Run the failing `RUN` line (after replacing `tightvncserver` with `tigervnc-standalone-server`;

```bash
apt-get update -y && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends xfce4 xfce4-goodies xfonts-base dbus-x11 tigervnc-standalone-server expect && \
chmod +x /tmp/vncpass.sh; sync && \
/tmp/vncpass.sh && \
rm /tmp/vncpass.sh && \
apt-get remove -y expect && apt-get autoremove -y && \
FILE_SSH_ENV="/root/.ssh/environment" && \
echo "DISPLAY=:1" >> $FILE_SSH_ENV
```

And I get the same error:

```
spawn vncpasswd
couldn't execute "vncpasswd": no such file or directory
    while executing
"spawn vncpasswd"
#
```

The command doesn't fail if you install `tightvncserver` , so I guess `vncpasswd` is not provided by the `tigervnc-standalone-server` package. Looking at https://bugzilla.redhat.com/show_bug.cgi?id=427478, which is for Fedora so might not be full equivalent, the `vncpasswd` is provided by the vnc server package.

In any case, from these steps, this doesn't appear to be a docker bug, so I'll close this issue, but feel free to continue the conversation in case I missed something

**Comment by thyrlian** [comment]
@thaJeztah thanks for helping out.

My bad.  When testing in a container, I ran the `apt-get install tigervnc-standalone-server` comamnd without using `--no-install-recommends` which was specified in the Dockerfile.  That's why it failed in building, but succeded in a container.

**Comment by thaJeztah** [comment]
👍 good to hear you found the difference. Overall I'd recommend the `--no-install-recommend` (_especially_ for this reason), so that you know exactly what's installed in your dockerfile, and can be specific about what's _needed_, but it may sometimes take some extra work to know which packages to install that are _required_ for your case
