### ISSUE TITLE
BuildKit: "insecure-registries" ignored by "docker build --pull"

### ISSUE THREAD

**Issue by bronger** [moby/moby#41080]
**Description**

Although a local registry is included in "insecure-registries" in `daemon.json`, `docker build --pull` fails for a Dockerfile which starts with `FROM my-registry:5000/my-image`.

**Steps to reproduce the issue:**
1. Set up an HTTP (i.e. insecure) registry called e.g. `my-registry:5000`.
2. Add this to your `daemon.json` as an allowed insecure registry.
3. Create a Dockerfile starting with `FROM my-registry:5000/my-image`.
4. Call `DOCKER_BUILDKIT=1 docker build --pull .`

**Describe the results you received:**

Docker should build the image.

**Describe the results you expected:**

    [+] Building 0.1s (5/8)
     => [internal] load build definition from Dockerfile
     => => transferring dockerfile: 38B
     => [internal] load .dockerignore
     => => transferring context: 2B
     => ERROR [internal] load metadata for my-registry:5000/my-image:latest
     => ERROR [1/4] FROM my-registry:5000/my-image:latest
     => => resolve my-registry:5000/my-image:latest
     => [internal] load build context
     => => transferring context: 42B
    ------
     > [internal] load metadata for my-registry:5000/my-image:latest:
    ------
    ------
     > [1/4] FROM my-registry:5000/my-image:latest:
    ------
    failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://my-registry:5000/v2/my-image/manifests/latest: http: server gave HTTP response to HTTPS client

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 127
 Server Version: 19.03.8
 Storage Driver: btrfs
  Build Version: Btrfs v5.4.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-33-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 6.874GiB
 Name: brad
 ID: VX4R:N4HJ:2FSU:DU4C:YFLX:B3E2:3DP2:Z6DB:JX2N:AYAX:ZT3G:YLL5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: bronger
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  my-registry:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Daemon and client on the same bare-metal laptop.

**Comment by wangyumu** [comment]
maybe same issue with #41059 , you can add `http` scheme to your insecure-registries like `http://my-registry:5000` and test again.

**Comment by bronger** [comment]
Indeed, this did the trick.

**Comment by detailyang** [comment]
same issue here :( Disable `DOCKER_BUILDKIT=0` works

**Comment by LOVEChen** [comment]
> 

thank you 
disable DOCKER_BUILDKIT=0 works
