### ISSUE TITLE
config.RequireSchema2 is never set anywhere

### ISSUE THREAD

**Issue by markphelps** [moby/moby#41095]
Hi,

After doing a quick search, it seems that `config.RequireSchema2` is never set anywhere, which means these cases will always evaluate to false: https://github.com/moby/moby/search?q=RequireSchema2&unscoped_q=RequireSchema2

It would be great if we could somehow set `RequireSchema2` in order to prevent ['retry pushes' ](https://github.com/moby/moby/blob/a4abdce703394eac990274bc6b491fc786d226fc/distribution/push_v2.go#L184) with a v1 manifest, to registries that dont support it

**Comment by thaJeztah** [comment]
Looks to relate to https://github.com/moby/moby/pull/37874 and https://github.com/moby/moby/pull/39384

@tiborvass @dmcgowan PTAL

**Comment by markphelps** [comment]
One idea, it would be :100: if the cli could take into account the `"Docker-Distribution-API-Version"` response header from the registry to set this value. However I realize that there might be some ambiguity as `Docker-Distribution-API-Version=registry/2.0` may not necessarily imply that the registry ONLY supports v2

**Comment by thaJeztah** [comment]
That's not part of the distribution spec AFAIK, so not something that should be used for that. But both `v1` images, and v2 image schema 1 are deprecated, and support will be fully removed, so after that I think this will no longer be an issue.
