### ISSUE TITLE
Exec causes containerd-shim to hang

### ISSUE THREAD

**Issue by nyxi** [moby/moby#41093]
**Description**
Executing commands in a container over time causes containerd-shim to hang / become unresponsive.

We are seeing this issue in our Kubernetes clusters for containers with a healthcheck of type "exec". They are fine for days at a time. but then it is no longer possible to attach to the container, inspect it with Docker, or stop it.

**Steps to reproduce the issue:**
1. Execute a command in a Docker container repeatedly, for instance every 10th seconds and in 1-5 days it will no longer be possible to attach to the container or inspect it

**Describe the results you received:**
After a while I can no longer attach to the container, execute commands in it or inspect it with Docker.

**Describe the results you expected:**
Possibly to execute commands in the container indefinitely.

**Additional information you deem important (e.g. issue happens only occasionally):**
Our other containers where we not execute commands for healthcheck but rather just check a HTTP endpoint or something do not show this error.

If we kill the offending container-shimd process the container is restarted and it is once again possible to execute commands / inspect it.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:22:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:28:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 63
  Running: 56
  Paused: 0
  Stopped: 7
 Images: 32
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: /opt/bin/dockerbins/docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.5.10-200.fc31.x86_64
 Operating System: Fedora CoreOS 31.20200323.3.2
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 23.48GiB
 Name: k8s-w11-ki
 ID: 6XUT:P7EW:ULY6:M5RG:IAAJ:EYUF:VWNK:IMPB:QRPG:YLMX:5GIV:EOXR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: <redacted>
 HTTPS Proxy: <redacted>
 No Proxy: <redacted>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We are seeing this issue both with pasted versions above (official static binaries release v19.03.9) and with the Docker version shipped with Fedora CoreOS: v18.09.8

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
