### ISSUE TITLE
cgroup1: use shim v2

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41107]
We have been already using shim v2 (`containerd-shim-runc-v2`) on cgroup v2 hosts:

https://github.com/moby/moby/blob/aaf470eca7b588aa19e6681bff8bf08d17be1bf2/daemon/daemon_unix.go#L1759-L1761

We should use shim v2 on cgroup v1 hosts as well.

I think we can safely switch the default, but if we fear potential regression, probably we should have a new daemon flag like `--containerd-shim-api=(1|2)` which defaults to `1`.

**Comment by thaJeztah** [comment]
I guess this would break users that use live-restore, but we don't support live-restore when upgrading major releases, so I guess from that perspective this would be ok.

Note that _before_ https://github.com/docker/containerd-packaging/pull/146, we didn't bundle `containerd-shim-runc-v2`, so containerd.io packages `< v1.2.13-2` would not have this shim. I don't expect users to _downgrade_ containerd to an older version, but we should probably raise the minimum version in our packages if we make this change.


@cpuguy83 @tonistiigi @tiborvass PTAL

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/41115

**Comment by AkihiroSuda** [comment]
new PR: https://github.com/moby/moby/pull/41210
