### ISSUE TITLE
windows server 2004 rebooting when running jenkins jobs in docker

### ISSUE THREAD

**Issue by isanych** [moby/moby#41118]
**Description**

I could not provide reproducible description, but still would like to create an issue as maybe there are known workarounds for that or maybe somebody knows how easily reproduce it.

Since last year we are running some windows jenkins jobs in docker. Jenkins slave also run in docker and it mapping docker pipe `-v \\.\pipe\docker_engine:\\.\pipe\docker_engine` to expose docker to jobs. We were using `windows server 1903`, `mcr.microsoft.com/windows:1903` base image and `docker 19.03.5`, all containers run with isolation=process, and system worked reasonable well.
As SAC windows has short support cycle we recently upgraded to `windows server 2004` and `docker 19.03.11` and rebuilt all images based on `mcr.microsoft.com/windows/servercore:2004` (switching to  mcr.microsoft.com/windows:2004 not helping - issue still there).

And now some jobs rebooting whole server after 5 - 45 minutes of running, every time run time is different, in event viewer I see:
```
The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xfffff800361f0912, 0xffffcf018d49c100, 0x0000000000000000). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: ade83b41-58a5-489a-8d80-cf46a8922cea.
```
Other jobs can run much longer without issues, so I far I see common factor in jobs which crash server, that they use cygwin. I see the same behavior on physical machine and in VM on different server. I've tried docker 19.03.05, 19.03.11 and master - still crashing.

I've created VM with `windows server 1909` and `docker 19.03.11` and rebuilt all images based on `mcr.microsoft.com/windows/servercore:1909` - and I don't see a crash anymore.
Is there anything I can try to stop crashes on server 2004?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:
 Built:             Tue Jun  2 10:57:43 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Tue Jun  2 11:01:07 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 22
  Running: 3
  Paused: 0
  Stopped: 19
 Images: 253
 Server Version: 19.03.11
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows Server Standard Version 2004 (OS Build 19041.329)
 OSType: windows
 Architecture: x86_64
 CPUs: 56
 Total Memory: 159.9GiB
 Name: sink
 ID: GAGI:VWC5:JC6A:EMJ4:UQFS:VMJM:257W:5JEQ:QFKF:YINN:DV6N:5SO7
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by cpuguy83** [comment]
ping @kevpar

**Comment by freddydk** [comment]
I am experiencing similar issues with 2004 - random container restarts when accessing files on fileshares using process isolation.
Running containers in hyperv mode works.

**Comment by isanych** [comment]
Windows 20H2 demonstrates the same behavior, so we stuck on 1909 with looming EOL.

**Comment by olljanat** [comment]
@isanych bugcheck [0x0000003b](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x3b--system-service-exception) indicates driver issue and because Docker does not install drivers to Windows node (afaik) it must be bug on Windows it selves so I highly recommend to reporting this one to Microsoft and provide memory dump for them if it still happens on latest Windows versions with all patches installed.

Additionally you can use [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) to analysing those memory dumps.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
