### ISSUE TITLE
Client does not provide ServiceInspect

### ISSUE THREAD

**Issue by roidelapluie** [moby/moby#41134]
**Description**

The client/ package does not provide ServiceInspect, but provides ServiceInspectWithRaw. This is unequal with other features of the package (e.g. services)

**Comment by thaJeztah** [comment]
Could you describe the problem you're running into because of this? I'm a bit on the fence on adding a `ServiceInspect` function to the interface, that does exactly the same except for omitting the raw output.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
