### ISSUE TITLE
upgrading the version of image in Dockerfile for supporting mips64el

### ISSUE THREAD

**Issue by wanghuaiqing2010** [moby/moby#41141]
Now official-images has supported the following images for mips64el.
buildpack-deps:stretch
buildpack-deps:buster
debian:stretch
debian:buster

But official-images does not support the following images for mips64el.
debian:jessie
buildpack-deps:jessie

In order to run tests  at mips64el device， could we upgrade the version of image in Dockerfile ？

**Comment by wanghuaiqing2010** [comment]
I mean that we should modify the dockerfile of the moby as follows.

[root@localhost moby]# git diff  Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90
+
 # See also ensureFrozenImagesLinux() in "integration-cli/fixtures_linux_daemon_test.go" (which needs to be updated when adding images to this list)
 
 FROM base AS cross-false
[root@localhost moby]#

**Comment by wanghuaiqing2010** [comment]
I mean that we should modify the dockerfile of the moby as follows.

`[root@localhost moby]# git diff  Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90
+
 # See also ensureFrozenImagesLinux() in "integration-cli/fixtures_linux_daemon_test.go" (which needs to be updated when adding images to this list)
 
 FROM base AS cross-false
[root@localhost moby]# `

**Comment by wanghuaiqing2010** [comment]
`[root@localhost moby]# git diff  Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90
+
 # See also ensureFrozenImagesLinux() in "integration-cli/fixtures_linux_daemon_test.go" (which needs to be updated when adding images to this list)
 
 FROM base AS cross-false
[root@localhost moby]# `

**Comment by wanghuaiqing2010** [comment]
`[root@localhost moby]# git diff  Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90
+`

**Comment by wanghuaiqing2010** [comment]
`diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90`

**Comment by wanghuaiqing2010** [comment]
I mean that we should modify the dockefile of the moby as follows.

```[root@localhost moby]# git diff  Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 1536e23..d4fa0ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -87,11 +87,12 @@ RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/l
 # Get useful and necessary Hub images so we can "docker load" locally instead of pulling
 COPY contrib/download-frozen-image-v2.sh /
 RUN /download-frozen-image-v2.sh /build \
-        buildpack-deps:jessie@sha256:dd86dced7c9cd2a724e779730f0a53f93b7ef42228d4344b25ce9a42a1486251 \
-        busybox:latest@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0 \
-        busybox:glibc@sha256:0b55a30394294ab23b9afd58fab94e61a923f5834fba7ddbae7f8e0c11ba85e6 \
-        debian:jessie@sha256:287a20c5f73087ab406e6b364833e3fb7b3ae63ca0eb3486555dc27ed32c6e60 \
-        hello-world:latest@sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c
+        buildpack-deps:buster@sha256:d0abb4b1e5c664828b93e8b6ac84d10bce45ee469999bef88304be04a2709491 \
+        busybox:latest@sha256:1a41828fc1a347d7061f7089d6f0c94e5a056a3c674714712a1481a4a33eb56f \
+        busybox:glibc@sha256:4104c59416e9718228ea70e0d88c8a517cafb77761216ebf5076826a70359364 \
+        debian:buster@sha256:72a719c108d4c047e0a716f423bb02ea7abb8c2bb005f8d744e768925e2a36fd \
+        hello-world:latest@sha256:88b2e00179bd6c4064612403c8d42a13de7ca809d61fee966ce9e129860a8a90```

**Comment by thaJeztah** [comment]
@wanghuaiqing2010 are you interested in opening a pull request?

**Comment by wanghuaiqing2010** [comment]
@thaJeztah Yes， that is very good.
I would be honored to do it.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by wanghuaiqing2010** [comment]
@thaJeztah I have opened a pull request.
Please refer to the following link.
https://github.com/moby/moby/pull/41145

**Comment by tianon** [comment]
This can be closed now that https://github.com/moby/moby/pull/41145 is merged, right?

**Comment by thaJeztah** [comment]
Yes, looks like this can be closed
