### ISSUE TITLE
Splunk Logging Driver - No prefixes - JSON message only

### ISSUE THREAD

**Issue by mlcooper** [moby/moby#41154]
**Description**
When specifying the message format with the Splunk logging driver as raw, like this, `--log-opt splunk-format=raw` there are a few prefixes, such as Container ID, env variable or label that get prefixed to the JSON formatted log message.

We have found that the experience we're looking for is to ONLY ingest the JSON formatted *message* without any data prefixed to it.  This would allow us to use the native splunk `sourcetype` of `json` for the logs coming from our Docker containers.  

The issue we're facing now is having to use a custom transform/splunk sourcetype to essentially regex off all of the prefixed information that shows up before the JSON formatted message.  This custom transform in Splunk causes a good deal of overhead work for the Indexers that must take place on _every_ log message sent by our Docker containers.

In order to maintain backwards compatibility, perhaps a new message format of `--log-opt splunk-format=raw-message` that would ONLY send a JSON payload of the actual log message to splunk (no prefixes).

**For example:**
Here is a `splunk-format=raw` payload that the docker container sends to Splunk.  You can see the Container ID (`ec950baea86f`) is prefixed.  We would like instead for the Docker logging driver for splunk to send the message with **no prefixes**, only the JSON data:
```
ec950baea86f {"request":"GET /ent-service/service-status HTTP/1.1","loggerFqcn":"com.bst.valves.Log4j2JsonAccessLogValve","config_env":"us-west-2_qa","level":"INFO","CONID":null,"responseHeader":{"conversation-id":"","correlation-id":"9f507674-e01b-4156-be7e-bac10bfef845"},"label":["\"","\""],"service_version":"2.1.72","requestAttribute":{"buClientId":null,"Swid":null},"byteSent":7,"threadName":"https-jsse-nio-8443-exec-4","service":"entitlement","host":"10.0.0.0","requestHeader":{"conversation-id":null,"correlation-id":null,"X-Forwarded-For":null},"loggerName":"Log4j2JsonAccessLogValve","user":null,"timeMillis":1593107616320,"CID":"9f507674-e01b-4156-be7e-bac10bfef845","httpStatusCode":200,"elapsedTime":"0.005"}
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 34
  Running: 1
  Paused: 0
  Stopped: 33
 Images: 55
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.934GiB
 Name: docker-desktop
 ID: ORVS:HV4U:SFRN:22LV:NILV:4UP5:CWCF:LEJH:JB67:7ZEY:HNB7:FGD3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 36
  Goroutines: 55
  System Time: 2020-06-26T03:04:24.1411096Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Our containers run in AWS ECS and send their logs to an instance of Splunk which also runs in AWS (Splunk 8.0.1).

**Comment by thaJeztah** [comment]
Does it work if you set `--log-opt tag=""` ?

Looking at the code, the `raw` format prints the `tag` (if set; default is container-id), followed by custom attributes that were set as log option (which (I think) is empty by default); https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/daemon/logger/splunk/splunk.go#L335-L344

So I think if you specify `tag` to be empty, that you will only get the message itself

**Comment by mlcooper** [comment]
A few minutes ago I came up with the same idea you just did:
```
--log-opt splunk-format=raw
--log-opt tag=""
--log-opt labels=""
```
We are currently testing this configuration....

**Comment by thaJeztah** [comment]
perfect! let me know if that works (I don't use this logging driver myself, so didn't have a quick setup to try it)

**Comment by mlcooper** [comment]
@thaJeztah the testing worked!  The splunk logging driver no longer prefixes the data with the `--log-opt` settings I pasted above.  Thanks!!

Feel free to close this issue if you would like.

**Comment by thaJeztah** [comment]
Awesome! Easiest feature request ever 😂 👍 Closing
