### ISSUE TITLE
[Docker on Android] docker build error : error checking context: no permission to read from /config/sdcardfs/remove_userid

### ISSUE THREAD

**Issue by hessam94** [moby/moby#41170]
hello ,
i saw some similar issues but could solve my problem:
I tried to install docker on **Android** and could after some modifications on kernel, so now docker client and server both are running, by **sudo docker version.** i need to build a sample image but after running i get this error:
 error checking context: no permission to read from /config/sdcardfs/remove_userid
i don't know what to do because even this command shows me no permission to read , even with root access. I also modified the  **permissions of "remove_userid"** to rwx, but no change happens. ( I searched and found out that this file is under somehow virtual file system, no idea about it. i ran it with root access and under root path even, but not working.
I am working with android and do not have systemd and system ctl. although i am not sure if these can help me,
Thanks

**Comment by hessam94** [comment]
found the solution , we have to make a new directory and put Dockerfile and other files in there, then build the docker :

sudo docker build -t img1 /newdockerfolder

**Comment by thaJeztah** [comment]
Yes, it you run `docker build .`, then the build context (`.` - the current directory), including all subdirectories will be sent to the daemon. If you don't have access to some of those files, that will fail.

If you build with `DOCKER_BUILDKIT=1`, this is handled "smarter" (docker will only send files that are requested in the Dockerfile you're building), but the recommendation is to build from a directory that only contains files needed for your Dockerfile.


Let me close this ticket, but feel free to continue the conversation
