### ISSUE TITLE
GPU option introduced in 19.03 not available using the API

### ISSUE THREAD

**Issue by khayalan-mathew** [moby/moby#41171]
**Description**

Docker introduced the `--gpus` option with 19.03, which enables first class GPU support inside docker. Unfortunately this option doesn't seem to be available using the Docker API v1.40 (most likely should be located inside the HostOptions when creating the container, for reference this is what the current docs state [DOCS](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate))

Also the changelogs for version 1.40, didnt seem to include a change supporting this case.

**Steps to reproduce the issue:**
1. Try to launch a container using the new GPU option using the Docker API

**Describe the results you received:**
Option not available using the API

**Describe the results you expected:**
Option to be available using the API

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```

Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:   
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 268
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-61-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.29GiB
 Name: tanuki
 ID: MGDH:HBPR:BX2D:35L4:CRTC:7K34:D6QG:MCJZ:SYJC:GSBV:SWFF:NIEF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Perhaps you were looking at the `Request Samples` on the right-hand side (which may not have those particular fields propagated; we can probably add those).

The `--gpus` option of the cli uses the `HostConfig.DeviceRequests` fields. It's collapsed by default in the centre column of the docs, but you can expand the `HostConfig` section, and it should be there: https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate

<img width="772" alt="Screenshot 2020-07-03 at 12 08 16" src="https://user-images.githubusercontent.com/1804568/86458967-62126100-bd26-11ea-9a46-920555276009.png">


If you want to know what requests the CLI makes when using this option, you can enable "debug" mode on the daemon, which will log API calls in the daemon logs (you probably don't want to run that on a production setup, as it generates a lot more logging, and API requests _can_ contain sensitive data, which would then end up in the logs)

**Comment by khayalan-mathew** [comment]
@thaJeztah 
Thanks for the detailed response, seems like this can enable the functionality we want.
Thanks for the fast and nice help :)
