### ISSUE TITLE
May I know container live cycle or prevent build failed keeps loop then dead?

### ISSUE THREAD

**Issue by ckc** [moby/moby#41179]
**Description**

What is the problem?

My whole environment broken and cannot start

Checked logs as following, most likely overlay2 related issue
build failed, then dead loop to create the container
then dead

No idea what different between pure docker CLI and caprover(something extra features run as background?)

Could you please provide any possible solution or hint for it?

Thanks

**Steps to reproduce the issue:**
1. I used caprover panel to create & manage it; And I asked caprover developer said related docker

**Describe the results you received:**
cannot stop the app build failed loop, then reach the all host resource caused down

**Describe the results you expected:**
some build failed project have maximum attempted times

**Additional information you deem important (e.g. issue happens only occasionally):**
[Related issue](https://github.com/caprover/caprover/issues/669)

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
caprover under digitalocean one click

Thanks

**Comment by AkihiroSuda** [comment]
Seems because of full disk: https://github.com/caprover/caprover/issues/669#issuecomment-631133193

**Comment by ckc** [comment]
Yes, I know thatHope to know how prevent it under configuration layerThanksOn 6 Jul 2020 12:31, Akihiro Suda <notifications@github.com> wrote:
Seems because of full disk: caprover/caprover#669 (comment)

**Comment by AkihiroSuda** [comment]
If the issue is only reproducible in caprover environment, probably the issue is on caprover side.
If the issue is reproducible locally without caprover, please make sure to fulfill the issue template: https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE.md
