### ISSUE TITLE
compile non main package causes `can't load package`

### ISSUE THREAD

**Issue by gentcys** [moby/moby#41181]
**Description**
When execute `go build` to compile a non main package, it always fails.

**Steps to reproduce the issue:**
1. cd `$GOPATH/src/github.com/docker/docker/api/server/backend/build` or an arbitrary non main package's directory
2. execute `go build` in current direcotry

**Describe the results you received:**
```
can't load package: package github.com/moby/moby/api/server/backend/build: code in directory $GOPATH/src/github.com/moby/moby/api/server/backend/build expects import "github.com/docker/docker/api/server/backend/build"
```

**Describe the results you expected:**
Compile package successfully

**Comment by thaJeztah** [comment]
Do you have your source checked out in `$GOPATH/src/github.com/docker/docker/` or in `$GOPATH/src/github.com/moby/moby` ? Even though the GitHub repository has been renamed to moby/moby, the package name should still be docker/docker, and expects the source to be in `$GOPATH/src/github.com/docker/docker`

**Comment by gentcys** [comment]
I moved the source to `$GOPATH/src/github.com/docker/docker` then executed `go build` again in the same directory(`$GOPATH/src/github.com/docker/docker/api/server/backend/build`). And this error occured:
```
../../../../vendor/github.com/moby/buildkit/executor/oci/spec_unix.go:21:2: \
       build constraints exclude all Go files in $GOPATH/src/github.com/docker/docker/vendor/github.com/moby/buildkit/util/entitlements/security
../../../../vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go:25:2: \
       build constraints exclude all Go files in $GOPATH/src/github.com/docker/docker/vendor/github.com/moby/buildkit/util/rootless/specconv
```

**Comment by thaJeztah** [comment]
What platform are you building on? If you're trying to build on macOS, those errors are expected, as the daemon code only works on Linux or Windows.

**Comment by gentcys** [comment]
Oh, it is macOS unfortunately!

**Comment by thaJeztah** [comment]
For testing, you can try building inside the dev-container;

```
make BIND_DIR=. shell
```

That builds a development image with all dependencies and Go in it, and opens an interactive shell in which you can work.

That said; if you want to work with the buildkit code itself, you're probably looking for the upstream repository: https://github.com/moby/buildkit
