### ISSUE TITLE
How to compile and debug source code

### ISSUE THREAD

**Issue by ccnankai** [moby/moby#41184]
Hi,
I am a novice. I want to learn the source code, how to build the environment, compile the source code and debug. is there  tutorial on this?

**Comment by thaJeztah** [comment]
You can build (and run) in a development container. If you have docker installed on your local machine, your can run;

```bash
make BIND_DIR=. binary shell
```

Which will build an image that has all the dependencies needed, builds the docker daemon from your local source, starts a container with your source bind-mounted in it (so you can make changes on your host), and opens a shell in the container.

Inside that container you can run `make install` to install the daemon in the container, and run `dockerd --debug` (or a variant thereof) to start the daemon in the foreground, printing the daemon logs. You could make the daemon run in the background, but I usually open a second shell in the container (`docker exec -it <name of the development container>`) to run commands. 

Inside the container you can re-compile the daemon using `hack/make.sh binary`.

There's also docs in https://github.com/moby/moby/tree/master/docs/contributing, but they could be outdated 








There's some information about testing in https://github.com/moby/moby/blob/master/TESTING.md

**Comment by ccnankai** [comment]
This method is too helpful, thank you for your advice.

**Comment by thaJeztah** [comment]
You're welcome! Sorry, the contributing docs definitely need to be cleaned up a bit 😥, so I hope this gets you going. Also feel free to contact me in the Docker Community Slack if you're on there

**Comment by ccnankai** [comment]
@thaJeztah 
Slack can't reach you. So back to github,Sorry to bother you.
I have been engaged in software development in China for 4 years. As you know, most companies in China do not have core technologies. My personal technical level (programming ability, etc.) has not improved more. I want to ask you experience. Although I cannot reach the level of an expert like you, I also want to be an excellent engineer beyond most people. Can I learn from you, or you have a slightly simpler task assigned to me. I myself simply look at the source code is not an effective way. I sincerely worship you as a teacher, please accept me as a disciple.Where should I go to get mission goals, mission-driven is the best way to learn.
