### ISSUE TITLE
Proposal: move moby-snapshot to github.com/moby org

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41187]
https://github.com/AkihiroSuda/moby-snapshot provides auto-built binary snapshots of Moby/containerd/runc.

The snapshots are available as static binaries, debs, and rpms:
```console
$ tar xjvf moby-snapshot-x86_64.tbz
moby-snapshot-x86_64/
moby-snapshot-x86_64/bin/
moby-snapshot-x86_64/bin/containerd
moby-snapshot-x86_64/bin/containerd-shim
moby-snapshot-x86_64/bin/containerd-shim-runc-v2
moby-snapshot-x86_64/bin/ctr
moby-snapshot-x86_64/bin/docker
moby-snapshot-x86_64/bin/docker-init
moby-snapshot-x86_64/bin/docker-proxy
moby-snapshot-x86_64/bin/dockerd
moby-snapshot-x86_64/bin/dockerd-rootless-setuptool.sh
moby-snapshot-x86_64/bin/dockerd-rootless.sh
moby-snapshot-x86_64/bin/rootlesskit
moby-snapshot-x86_64/bin/rootlesskit-docker-proxy
moby-snapshot-x86_64/bin/runc
moby-snapshot-x86_64/bin/vpnkit

$ tar xjvf moby-snapshot-ubuntu-focal-x86_64-deb.tbz 
containerd.io_0.20200706.182234~68b9b8f-1_amd64.deb
moby-snapshot_0.0.0-20200706131654-66ea6250a1-0~ubuntu-focal_amd64.deb
moby-snapshot-cli_0.0.0-20200706131654-66ea6250a1-0~ubuntu-focal_amd64.deb

$ tar xjvf moby-snapshot-fedora-32-x86_64-rpm.tbz 
containerd.io-0.20200706.182234~68b9b8f-0.fc32.x86_64.rpm
moby-snapshot-0.0.0.20200706131654.66ea6250a1-0.fc32.x86_64.rpm
moby-snapshot-cli-0.0.0.20200706131654.66ea6250a1-0.fc32.x86_64.rpm
```

I'd like to move https://github.com/AkihiroSuda/moby-snapshot under https://github.com/moby to make these binaries official.

Related: https://github.com/moby/moby/issues/40378 https://github.com/docker/for-linux/issues/955

**Comment by tao12345666333** [comment]
LGTM

If this is available, can we replace download.docker.com or repair its nightly channel in other ways.

**Comment by AkihiroSuda** [comment]
@thaJeztah @cpuguy83 WDYT?

**Comment by cpuguy83** [comment]
Seems fine, assuming GH doesn't complain about storage.
Almost certainly could run into request throttling as well.

**Comment by AkihiroSuda** [comment]
> Seems fine, assuming GH doesn't complain about storage.

`Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.`
https://docs.github.com/en/github/administering-a-repository/about-releases#storage-and-bandwidth-quotas
