### ISSUE TITLE
Mounting device (--device) with golang client

### ISSUE THREAD

**Issue by MaximeAubanel** [moby/moby#41193]
**Description**

Hello, how can I create a container specifying devices like that:

`docker run --name container_blabla -d -it --device=/dev/ttyDevice:/dev/ttyDevice my_image:latest`

This is what I have so far:

```go
resp, err := docker.cli.ContainerCreate(docker.ctx, &container.Config{
    Image: image,
}, nil, nil, name)
```

But cannot find any option device or similar.

**Comment by MaximeAubanel** [comment]
I checked the code and AFAIK there is, as of today, no way to mount devices.

Therefore I opened a PR: #41194 to add the missing field Devices to HostConfig.

**Comment by MaximeAubanel** [comment]
Ok I missed it while reading the code but this is in fact how to do it for those wondering:

```go
_, err := docker.cli.ContainerCreate(docker.ctx, &container.Config{
	Image: image,
	Env:   env,
}, &container.HostConfig{
	Resources: container.Resources{Devices: devices},
}, nil, name)
```

**Comment by thaJeztah** [comment]
Looks like you worked it out. The docker cli code can also be useful to find some examples how it's used; https://github.com/docker/cli 

Let me go ahead and close this one
