### ISSUE TITLE
The image keep broken when remove the image`s overlay2 path 

### ISSUE THREAD

**Issue by eshujiushiwo** [moby/moby#41190]
**Description**

we met a problem about the overlay2 path of image.
when we remove the overlay2 path which "docker inspect imageid" shows,  the image is always broken.
And whatever we remove and pull the image again or clean the image ,this image can not work all the time.

**Steps to reproduce the issue:**
1.get the overlay2 path of A image
`docker inspect {imageid}|grep overlay2`

if the result is:

>  "MergedDir": "/var lib/docker/overlay2/f124d6b53e9f1064e3942d303f90723475eca4849013e8ef7007e29997e80beb/merged",

So the the overlay2 path is

>  /var lib/docker/overlay2/f124d6b53e9f1064e3942d303f90723475eca4849013e8ef7007e29997e80beb

2. stop docker and remove the path we got.

`systemctl stop docker `
`rm -rf /var/lib/docker/overlay2/f124d6b53e9f1064e3942d303f90723475eca4849013e8ef7007e29997e80beb`
`systemctl start docker `

3.tring to inspect the image
`docker inspect xxxx |grep overlay2`

the result is:

> Error response from daemon: stat /var/lib/docker/overlay2/f124d6b53e9f1064e3942d303f90723475eca4849013e8ef7007e29997e80beb no such file or directory

4. after that ,whatever we use `docker rmi xxx & docker pull xxxx:xxx` or `docker system prune --all --force `
the inspect of this image is always the same :

> Error response from daemon: stat /var/lib/docker/overlay2/f124d6b53e9f1064e3942d303f90723475eca4849013e8ef7007e29997e80beb no such file or directory
 

it seems the overlay2 path id is always the same and we have no idea about the solution.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.39
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 187
  Running: 183
  Paused: 0
  Stopped: 4
 Images: 90
 Server Version: 18.09.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 61.76GiB
 Name: master1.teambition.local
 ID: YHUB:MFSU:IJGI:2ORV:X4PW:7XEA:6FQH:4QER:74JP:U2SR:SAHE:OPW3
 Docker Root Dir: /teambition_data/docker_data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.cn-hangzhou.aliyuncs.com
  127.0.0.0/8
 Live Restore Enabled: true
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Why are you removing that path? Files inside `/var/lib/docker` are managed by the docker daemon, removing these files can definitely break things unexpectedly

**Comment by eshujiushiwo** [comment]
> Why are you removing that path? Files inside `/var/lib/docker` are managed by the docker daemon, removing these files can definitely break things unexpectedly

The Path is broken by accident.
Is there any way to solve this problem?
Thanks a lot.

**Comment by thaJeztah** [comment]
May not be easy if you have containers running. It's possible there's a container that still using the layer (so the remove now actually _removing_ the layer), and/or other images referencing it. I think the only "safe" way would be to remove all docker's state, but you would loose your local image, containers, volumes, etc, so there's no "real" answer, as it really depends on your situation.


Let me close this issue, because this doesn't look like a bug, but feel free to continue the conversation
