### ISSUE TITLE
The "Docker Subnet" option in Docker Desktop GUI does nothing

### ISSUE THREAD

**Issue by shellwhale** [moby/moby#41201]
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Changing the "_Docker subnet_" in the Docker Desktop for Windows GUI does nothing for what I can see. 
There is this default subnet `192.168.65.0/28` that I don't see being used anywhere. https://i.imgur.com/20d5VJc.png
I'm struggling to find documentation on what it is supposed to do exactly.

I tried to `docker network inspect` on every network, checked the docker-desktop WSL2 distro and my Windows host for routes or IPs but I don't see that default subnet being used anywhere.

**Comment by thaJeztah** [comment]
Looks like this is related to Docker Desktop for Windows; could you report this in the corresponding issue tracker instead? https://github.com/docker/for-win/issues
