### ISSUE TITLE
VOLUME inheritation buggy

### ISSUE THREAD

**Issue by kolbma** [moby/moby#41209]
**Description**

**Steps to reproduce the issue:**
1. An image A uses an anonymous volume mount for directory X (VOLUME /X)
2. Another image B uses image A as base and inherits the anonymous volume mount
3. The contents of directory /X from image B are lost and not accessible

**Describe the results you received:**
Fresh image B mounts anonymous volume at /X with the content from image A and the content of /X from image B is lost under the mount.

**Describe the results you expected:**
During build of image B the content of directory /X should also be copied to the anonymous volume.  
It should get the state the directory has when the VOLUME instruction from Dockerfile is handled.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
# docker history imageA:latest
IMAGE               CREATED             CREATED BY                                      SIZE  
10593a379cd3        3 days ago          /bin/sh -c #(nop)  VOLUME [/X]                  0B
ff0f3b9afe9a        3 days ago          |5 release_arch=x86_64 release_tarball=alxxx…   7.35MB
2b2413bd4cf1        3 days ago          /bin/sh -c #(nop) COPY dir:6e1a2ed73d23fe2a3…   1.44MB
698dad9e78f6        3 days ago          /bin/sh -c #(nop)  ARG release_url_version=3…   0B

# docker history imageB:latest
IMAGE               CREATED             CREATED BY                                      SIZE  
55ac77876dd3        18 seconds ago      /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B
371d1d554027        20 seconds ago      /bin/sh -c #(nop)  VOLUME [/X]                  0B <============
788fe7fe1fb2        27 seconds ago      |4 download_url=https://github.com/xxxxxx/xx…   153MB
2ce987afc79d        19 minutes ago      /bin/sh -c #(nop) COPY file:28211fe054e790f8…   524B
fda649e513f2        19 minutes ago      /bin/sh -c #(nop) COPY file:4a9378f10e1d81a1…   4.05kB
104ad9fed0fe        19 minutes ago      /bin/sh -c #(nop)  ENV admin_email=xxxxx@ema…   0B
87d7f73ee7f1        19 minutes ago      /bin/sh -c #(nop)  ARG webdir=/var/www/magen…   0B
10593a379cd3        3 days ago          /bin/sh -c #(nop)  VOLUME [/X]                  0B <============
ff0f3b9afe9a        3 days ago          |5 release_arch=x86_64 release_tarball=alxxx…   7.35MB
2b2413bd4cf1        3 days ago          /bin/sh -c #(nop) COPY dir:6e1a2ed73d23fe2a3…   1.44MB
698dad9e78f6        3 days ago          /bin/sh -c #(nop)  ARG release_url_version=3…   0B
```

A fresh container with imageB has in /X the state of image **10593a379cd3**.
But what is happening with the one at **371d1d554027**?!

The result is the same as there would be no VOLUME instruction for **371d1d554027**.

**Output of `docker version`:**

```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        42e35e61f352e527082521280d5ea3761f0dee50
 Built:             Wed Jun  3 13:10:57 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       42e35e61f352e527082521280d5ea3761f0dee50
  Built:            Wed Jun  3 13:09:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4
  GitCommit:        814b7956fafc7a0980ea07e950f983d0837e5578
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 3
  Paused: 0
  Stopped: 4
 Images: 42
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 814b7956fafc7a0980ea07e950f983d0837e5578
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.43-1-lts
 Operating System: Alpine Linux v3.12
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.845GiB
 Name: pavilion
 ID: YZPL:D3FM:IFV5:DJ5P:SAWU:IYPF:7D5V:4EJW:WHSV:HRK6:W6SP:UCCH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by cpuguy83** [comment]
Looking at history output is not easy to tell what you are trying to do.
However, `VOLUME` instructions prevent any new data from being persisted to the image at the volume path.

Volume data is not inherited between images because volumes are not part of the image.

**Comment by kolbma** [comment]
I have imageA with an empty dir /X which should always be a volume mount.  
The next imageB uses imageA (FROM).  
The volume instruction gets inherited.  
But all data which is put in the /X directory during build of imageB (with RUN instruction), is not copied to the mount.  
The data is lost.


> However, `VOLUME` instructions prevent any new data from being persisted to the image at the volume path.

Why is it prevented during build? This is an intransparent design mistake.
The question is, why the data is not copied to a volume mount with the 2nd VOLUME instruction for imageB, like it would have been done for imageA before.  
There should be a chain of copy actions.

> 
> Volume data is not inherited between images because volumes are not part of the image.

Sure the data is not inherited, but the VOLUME instruction and the mount is inherited.

**Comment by kolbma** [comment]
Here are some build and Dockerfiles to demonstrate...  
https://gist.github.com/kolbma/e8c80a4694c06e3ab6d35e29ffdabadf

**Comment by cpuguy83** [comment]
This is the line that would fail: https://gist.github.com/kolbma/e8c80a4694c06e3ab6d35e29ffdabadf#file-dockerfile-b-L6

And by fail I mean the data will not persist in the image, because it is being written to the volume, not to the image.

Any data that is in the path before the `VOLUME` declaration will stay in the image and be copied to the volume on container startup.

> Why is it prevented during build? This is an intransparent design mistake.

It's not prevented per-se, it's just doing what was instructed, put a volume at /X, and all the things that go along with it.

It is this way largely because of the design of the original builder implementation. It has been discussed to make `VOLUME` declarations metadata only for the build, but because people actually do rely on this current behavior we did not change this.

I agree, though, it is a mistake. I just don't see how we can change this behavior.

`buildkit`, the newer build implementation, supports custom frontends, which would mean you could copy the dockerfile format and modify it to your needs.
This gets defined at the top of your Dockerfile like `# syntax=kolbma/dockerfile`, where the reference `kolbma/dockerfile` is an image reference.

The dockerfile parser is here: https://github.com/moby/buildkit/tree/master/frontend/dockerfile

**Comment by kolbma** [comment]
> This is the line that would fail: https://gist.github.com/kolbma/e8c80a4694c06e3ab6d35e29ffdabadf#file-dockerfile-b-L6
> 
> And by fail I mean the data will not persist in the image, because it is being written to the volume, not to the image.
> 

Just to make it clear... This volume is an anonymous volume which is here only available for the build container during build. Is it like this? Make this any sense that it works like this?

> > Why is it prevented during build? This is an intransparent design mistake.
> 
> It's not prevented per-se, it's just doing what was instructed, put a volume at /X, and all the things that go along with it.
> 
> It is this way largely because of the design of the original builder implementation. It has been discussed to make `VOLUME` declarations metadata only for the build, but because people actually do rely on this current behavior we did not change this.
> 
> I agree, though, it is a mistake. I just don't see how we can change this behavior.
> 

On which behavior does anyone rely here?  
Does anyone use volumes by intention during build?

Maybe an UNVOLUME would be nice.  
Then you could copy data to tmp, unvolume and move data to image directory of mountpoint and do the VOLUME again, which copies now the complete data.

I will have a look in the new buildkit and the code link for the parser. Thanks.

**Comment by cpuguy83** [comment]
> On which behavior does anyone rely here?

People use it as scratch space either to explicitly not persist or for performance reasons.

> Maybe an UNVOLUME would be nice.

https://github.com/moby/moby/issues/3465

**Comment by kolbma** [comment]
That's the issue #3465 github should have shown by my search and when creating this one ;-)
