### ISSUE TITLE
Docker-compose volumes give permission denied after upgrade to moby.

### ISSUE THREAD

**Issue by kierun** [moby/moby#41202]
**Description**

On Fedora 32, I upgraded from `docker-ce` (from F31) to `moby`. The docker command works and can re-create all my docker images. However, none of the docker-compose file work as they cannot bind the volumes due to permissions errors. 

**Steps to reproduce the issue:**

1. Run docker-compose under docker-ce
2. Upgrade to moby.
3. Run the same docker-compose having changed nothing else.
4. *The above fails to launch containers since the volumes have the "wrong" permissions.*

**Describe the results you received:**

None of the previously mountable volumes are able to be mounted.

This is true of other docker containers as well: for example the ones to run mattermost.

**Describe the results you expected:**

I expected moby to be a drop in replacement for docker-ce. Since the volumes are no longer working, I am worried I made the wrong call.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 19.03.11, build 42e35e6

docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.3
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020

**Output of `docker info`:**
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 3
  Paused: 0
  Stopped: 10
 Images: 18
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version:
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 5.7.7-200.fc32.x86_64
 Operating System: Fedora 32 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.58GiB
 Name: nightwatch.neverness.org
 ID: LIG5:IX25:JPAP:V6VY:TBES:4QDE:EZBS:MY7E:MTCW:4QKW:VURB:KTPZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 32 OS, moby was installed from package.

**Comment by advaithm** [comment]
This is also present when using `-v` flag.

**Comment by kierun** [comment]
[It is SELinux's fault](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/).

Add `:Z` to your volumes mounts: `/host/path:/container/path:Z` and it should work.
