### ISSUE TITLE
applying cgroup configuration for process caused \"open /cpuset/docker/cpuset.cpus: no such file or directory

### ISSUE THREAD

**Issue by hessam94** [moby/moby#41204]
Hello, ( I am really need your help guys, please....)
I tried to load docker image on Android(the image was saved from ubuntu with same architecture). Cgroup is mounted by this [scrpit](https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount). Docker client and server shows correctly versions, same as ubuntu output. But after the running sudodocker run hello-world I got this error:
**applying cgroup configuration for process caused \"open /cpuset/docker/cpuset.cpus: no such file or directory**
there is something strange , after running the command and getting the error I see a new directory is created in root path, **cpuset** but i dont know why!! this does not happen on ubuntu!!
and this is the mount point for cpuset:
**cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0**

please let me know if you have any idea, thanks a lot

i tried to make a new file under that directory but there will be lots of similar errors , which seems to me it is in a loop.

**Comment by thaJeztah** [comment]
Android is not currently supported, and from others that tried to run docker on android, I know that a custom kernel was required (and even with that, things may not work, as the codebase does not take android into account).

Closing this issue because of the above, but feel free to continue the conversation

**Comment by hessam94** [comment]
Thanks , i modified the kernel and seems all necessary parts are enabled, by running check-config.sh, do you have any idea related to this issue? Thanks

Sent from Yahoo Mail for iPhone


On Monday, July 13, 2020, 9:29 AM, Sebastiaan van Stijn <notifications@github.com> wrote:




Android is not currently supported, and from others that tried to run docker on android, I know that a custom kernel was required (and even with that, things may not work, as the codebase does not take android into account).

Closing this issue because of the above, but feel free to continue the conversation

**Comment by hessam94** [comment]
As for more clearance: I could modify the kernel and docker is now running, i mean docker client and server. daemon is listening correctly and docker version shows me right output, but docker hello-world does not work. please be in touch with me as i really need it,, 
thanks
