### ISSUE TITLE
Setup cgroups v2 CI

### ISSUE THREAD

**Issue by tiborvass** [moby/moby#41218]
This issue is to track needed changes to Jenkins CI infra to enable running tests on cgroups-v2-enabled machines.

Related to https://github.com/moby/moby/pull/41065

**Comment by AkihiroSuda** [comment]
If setting up CI takes a time, can we use Vagrant on Travis or on GitHub Actions?

runc has been using Vagrant on Travis, containerd has been using Vagrant on GitHub Actions.

**Comment by cpuguy83** [comment]
Vagrant on Actions has been fairly unreliable.

**Comment by AkihiroSuda** [comment]
Travis might be better?

**Comment by AkihiroSuda** [comment]
How can we move this forward?

**Comment by AkihiroSuda** [comment]
Opened PR to use Fedora 33 on Vagrant on GitHub Actions: https://github.com/moby/moby/pull/41918

This is slow, but we really need to have cgroup2 CI toward moving cgroup2 out of experimental (#41916).

**Comment by StefanScherer** [comment]
I've created new AMI's and now we have cgroup2 machines in CI.

Jenkins labels `amd64 && ubuntu-2004 && cgroup2` and `amd64 && ubuntu-2004 && cgroup1` could be used to have two  different `amd64` Ubuntu 20.04 machines with Docker 20.10.2  installed.

Let me know if  you need more. :-)

**Comment by AkihiroSuda** [comment]
Thanks @StefanScherer !

Opened https://github.com/moby/moby/pull/41925 for adding cgroup2 to Jenkinsfile.
