### ISSUE TITLE
The docker service will stop when deleting the container

### ISSUE THREAD

**Issue by webPageDev** [moby/moby#41216]
**Description**

**Steps to reproduce the issue:**
1.When using kubernetes to delete 300 pods at a time, there will be a probability that the docker service will exit
2.
3.

**Describe the results you received:**

```
time="2020-07-16T11:27:29.936836394+08:00" level=debug msg="Calling GET /containers/3fb834cff4b0ee1fa0fab62c9fb749b6f7c8e8c33031fd598c991875699bd7a2/json"
time="2020-07-16T11:27:29.943993893+08:00" level=debug msg="Calling POST /containers/3fb834cff4b0ee1fa0fab62c9fb749b6f7c8e8c33031fd598c991875699bd7a2/stop?t=10"
time="2020-07-16T11:27:29.948820423+08:00" level=debug msg="Calling GET /containers/8acaf10649e030d47e8b5df69d71a328d0e5f90bcf5794ace52ed5a6a7153c86/json"
time="2020-07-16T11:27:29.950434458+08:00" level=debug msg="Calling GET /images/sha256:3367281657991059fd5cc0e80afdc20462e8008f0e61fbab92590e26344d8ea8/json"
time="2020-07-16T11:27:29.951950046+08:00" level=debug msg="Calling GET /containers/f998f7802408d20ad669fe172b46be8adf787da6e46e1ee9e07b650c4f2b9134/json"
time="2020-07-16T11:27:29.952426539+08:00" level=debug msg="Calling GET /containers/8acaf10649e030d47e8b5df69d71a328d0e5f90bcf5794ace52ed5a6a7153c86/json"
time="2020-07-16T11:27:29.953463867+08:00" level=debug msg="Calling GET /containers/da7d633399d1bd02adf2df2d5bf22c1781659d493188dfb4ecb14a12d5ba2dbb/json"
time="2020-07-16T11:27:29.953894505+08:00" level=debug msg="Calling DELETE /containers/8acaf10649e030d47e8b5df69d71a328d0e5f90bcf5794ace52ed5a6a7153c86?force=1&v=1"
time="2020-07-16T11:27:29.956355517+08:00" level=debug msg="Calling GET /containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%2C%22io.kubernetes.pod.uid%3D64c7157a-9ed3-4d31-a9e6-9f0a087a56fd%22%3Atrue%7D%7D&limit=0"
time="2020-07-16T11:27:29.973420036+08:00" level=debug msg="Calling GET /containers/f943a82c5549d693f6a0e80320e6bb3952115e6cefbbe4290ab99470b98b7599/json"
time="2020-07-16T11:27:29.974798053+08:00" level=debug msg="Calling GET /images/sha256:3367281657991059fd5cc0e80afdc20462e8008f0e61fbab92590e26344d8ea8/json"
time="2020-07-16T11:27:29.976108224+08:00" level=debug msg="Calling GET /containers/dc63689a6ff492206592b284c3bb9966751403d972793af71bb609398e19d914/json"
time="2020-07-16T11:27:29.977850440+08:00" level=debug msg="Calling GET /images/sha256:3367281657991059fd5cc0e80afdc20462e8008f0e61fbab92590e26344d8ea8/json"
time="2020-07-16T11:27:29.978283719+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978413022+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978431032+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978476406+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978490418+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978545760+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978560054+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978601127+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978613353+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978659510+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978671170+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978704825+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978706070+08:00" level=warning msg="failed to delete process" container=a004c62cf5420223a8d0869ccbadf4470a107968fb91fb2afe3683b26a8c4547 error="transport is closing: unavailable" module=libcontainerd namespace=moby process=f0fc176ae06146c2487a7799506096c548390c278b993a15acf94fb9b805380c
time="2020-07-16T11:27:29.978718398+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978753630+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978764854+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978798730+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978810086+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978837598+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
time="2020-07-16T11:27:29.978846510+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978865842+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:29.978911030+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
time="2020-07-16T11:27:29.978627205+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
time="2020-07-16T11:27:29.979003510+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
time="2020-07-16T11:27:29.979024459+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420782250, TRANSIENT_FAILURE" module=grpc
time="2020-07-16T11:27:29.979039935+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420782250, CONNECTING" module=grpc
time="2020-07-16T11:27:29.979066367+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42018a1d0, TRANSIENT_FAILURE" module=grpc
time="2020-07-16T11:27:29.979084225+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42018a1d0, CONNECTING" module=grpc
time="2020-07-16T11:27:30.703642734+08:00" level=info msg="Processing signal 'terminated'"
time="2020-07-16T11:27:30.826680830+08:00" level=debug msg="Clean shutdown succeeded"
time="2020-07-16T11:27:30.826760537+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:30.826800978+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2020-07-16T11:27:30.826778727+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=moby
time="2020-07-16T11:27:30.826828868+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=moby
```

**systemctl status docker**

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─restart.conf
   Active: inactive (dead) since Thu 2020-07-16 11:27:30 CST; 4h 4min ago
     Docs: https://docs.docker.com
  Process: 2187 ExecStart=/bin/bash -c exec /usr/bin/dockerd -H unix:///var/run/docker.sock -H fd:// --containerd=/run/containerd/containerd.sock 1>>/var/log/matrix-diag/Matrix/docker/docker.log 2>&1 (code=exited, status=0/SUCCESS)
 Main PID: 2187 (code=exited, status=0/SUCCESS)

Jul 16 10:56:18 matrix162 systemd[1]: Starting Docker Application Container Engine...
Jul 16 10:56:35 matrix162 systemd[1]: Started Docker Application Container Engine.
Jul 16 11:27:30 matrix162 systemd[1]: Stopping Docker Application Container Engine...
Jul 16 11:27:30 matrix162 systemd[1]: Stopped Docker Application Container Engine.
```

```
**systemctl status containerd|head -30**
● containerd.service - containerd container runtime
   Loaded: loaded (/usr/lib/systemd/system/containerd.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2020-07-16 11:27:30 CST; 4h 11min ago
     Docs: https://containerd.io
  Process: 2179 ExecStart=/usr/bin/containerd (code=exited, status=0/SUCCESS)
  Process: 2172 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 2179 (code=exited, status=0/SUCCESS)
    Tasks: 5381
   Memory: 715.7M
   CGroup: /system.slice/containerd.service
           ├─  411 /pause
           ├─  425 /webServer
           ├─  480 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/3596e3fb542208f7dbfc488db134eb7bd1593df5f28f2722fc2c76e8e3bb233a -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc -systemd-cgroup
           ├─  515 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/9890986f8e4ef76b5d9b838c0d192922d7700fd1c9ff895fd355e399919f93e6 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc -systemd-cgroup
           ├─  557 /pause
           ├─  631 /pause
           ├─  640 /pause
           ├─  784 /webServer
           ├─  844 /webServer
           ├─  848 /webServer
           ├─  853 /webServer
           ├─  864 /pause
           ├─  873 /webServer
           ├─  885 /webServer
           ├─  892 /webServer
           ├─  894 /webServer
           ├─  898 /webServer
           ├─  911 /pause
           ├─  933 /webServer
           ├─ 1007 /pause
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Containers: 62
 Running: 56
 Paused: 0
 Stopped: 6
Images: 28
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: H3Linux Release 1.1.1
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.26GiB
Name: matrix161
ID: HYQX:MHK3:EWAC:J2JC:STHG:CDWE:7OST:6CJ3:MY3G:DEU7:OMYG:54IN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 216
 Goroutines: 190
 System Time: 2020-07-16T15:36:54.020025501+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 matrix-registry.h3c.com:8088
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware
3 nodes（16core； 32G memory； 300G disk）

**Comment by thaJeztah** [comment]
Looks like containerd went AWOL. Is there anything useful in the containerd logs? (`journalctl -u containerd.service`) ?

I do notice that you're running on Docker 18.09.x, which reached EOL quite some time ago, and is no longer maintained, and the version of containerd is quite outdated as well (latest 1.2.x version is 1.2.13, and quite some changes went in since 1.2.5; https://github.com/containerd/containerd/compare/v1.2.5...v1.2.13).

If you're unable to upgrade to Docker 19.03.x, at least I'd recommend to (if possible in a test environment) try if  the problem still reproduces on the latest patch release of Docker 18.09 (v18.09.9) and containerd.

**Comment by webPageDev** [comment]
The logs of containerd are like this：
Jul 16 11:27:27 matrix162 containerd: time="2020-07-16T11:27:27.587348595+08:00" level=info msg="shim reaped" id=9b6870e2a3253343ee43a7af8dc929e4e1ffed848899808d575192932f09ecdf
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.084488474+08:00" level=info msg="shim reaped" id=7a9f454488bd0eba65d4189ecc64b474eb9cfb27655b79ae89cafe3582f8c6ac
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.707263480+08:00" level=info msg="shim reaped" id=933b9e9f32555b3677c8546e5e6a0117b5879b19ae38766cae0b9a1c2b89083e
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.729290025+08:00" level=info msg="shim reaped" id=7803acf1a1b031ffb03a52ef5470d911a976aa1bc0b6ae0210838665c3a31a7f
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.748897410+08:00" level=info msg="shim reaped" id=36cc489e2f3a1e62d080f0128759a7349d443539989bbfe2927b63d49b3cc9f9
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.771679682+08:00" level=info msg="shim reaped" id=3bc3c6ccc56d56ab02503f25d4cc873872f3a9100ac4566b8f64a195ae535379
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.780072156+08:00" level=info msg="shim reaped" id=7be6d8c29b450aad7bcf10f7fcd6080898239c46cc6d8f83f4a7cc1a9ca7f88b
Jul 16 11:27:28 matrix162 containerd: time="2020-07-16T11:27:28.797009117+08:00" level=info msg="shim reaped" id=4c08de94dd82aac534fd7d65fa861000836597d6bc7fa088423fbefd7f5aacd8
Jul 16 11:27:29 matrix162 containerd: time="2020-07-16T11:27:29.208434627+08:00" level=info msg="shim reaped" id=8c76826e72938c35dbf27e9d89199f88db22d0153b60ace09349df63efca5195
Jul 16 11:27:29 matrix162 containerd: time="2020-07-16T11:27:29.626024797+08:00" level=info msg="shim reaped" id=54edb041f22601d6ede493eb0913a20b1b9b8d48f2ccb341ee32825f5dd64744
Jul 16 11:27:29 matrix162 containerd: time="2020-07-16T11:27:29.719949778+08:00" level=info msg="shim reaped" id=c25906aa8f085d0562c7ad70d35481c5b84f9c161ff782556426d1a002f86b05
Jul 16 11:27:29 matrix162 containerd: time="2020-07-16T11:27:29.719999977+08:00" level=warning msg="cleaning up after killed shim" id=c25906aa8f085d0562c7ad70d35481c5b84f9c161ff782556426d1a002f86b05 namespace=moby

I can try to upgrade docker to 19.03.x, I want to know how this problem is triggered so that I can further test whether there is still the problem on 19.03.x. Every time this problem occurs, it is accompanied by rpc connection failure Information, is this related to rpc. I saw the following code in docker:
	func Trap(cleanup func(), logger interface {
		Info(args ...interface{})
	}) {
		c := make(chan os.Signal, 1)
		// we will handle INT, TERM, QUIT, SIGPIPE here
		signals := []os.Signal{os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGPIPE}
		gosignal.Notify(c, signals...)
		go func() {
			interruptCount := uint32(0)
			for sig := range c {
				if sig == syscall.SIGPIPE {
					continue
				}
	
				go func(sig os.Signal) {
					logger.Info(fmt.Sprintf("Processing signal '%v'", sig))
					switch sig {
					**case os.Interrupt, syscall.SIGTERM:**
						if atomic.LoadUint32(&interruptCount) < 3 {
							// Initiate the cleanup only once
							if atomic.AddUint32(&interruptCount, 1) == 1 {
								// Call the provided cleanup handler
								cleanup()
								**os.Exit(0)**
							} else {
								return
							}
						} else {
							// 3 SIGTERM/INT signals received; force exit without cleanup
							logger.Info("Forcing docker daemon shutdown without cleanup; 3 interrupts received")
						}
					case syscall.SIGQUIT:
						DumpStacks("")
						logger.Info("Forcing docker daemon shutdown without cleanup on SIGQUIT")
					}
					//for the SIGINT/TERM, and SIGQUIT non-clean shutdown case, exit with 128 + signal #
					os.Exit(128 + int(sig.(syscall.Signal)))
				}(sig)
			}
		}()
	}
I noticed that docker received a 15 close signal. Is this signal sent by docker?

**Comment by webPageDev** [comment]
Today I tried to reproduce the problem of containerd exit, more logs are as follows，
**The containerd logs：**
time="2020-07-17T17:27:35.204651682+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.225032646+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.235983037+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.295867413+08:00" level=info msg="shim reaped" id=1d12c9813127cfa4fce5817af1be556c29fbf754e976d8d404a1f104dbcdac5b
time="2020-07-17T17:27:35.296096848+08:00" level=info msg="shim reaped" id=55cc8f3e6612f7116a8c22c8d63f25f2481e3b2487f658c40d14a19e8d514fdb
time="2020-07-17T17:27:35.304192193+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.304248813+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.335860537+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.340777836+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.467380149+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.491607505+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.556259213+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.556388602+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.634478005+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.705281289+08:00" level=info msg="shim reaped" id=99972d511f05fffd17da00395be5944182e5f96c687e1b46b223b4efe880d1df
time="2020-07-17T17:27:35.707137647+08:00" level=info msg="shim reaped" id=6e6ab98a70b5796ff31f9c1f1a5242a553c795ec16fcf0fedd11fc4c6f9ee08e
time="2020-07-17T17:27:35.714057398+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.716199907+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.733876495+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.740146803+08:00" level=debug msg="event published" ns=moby topic="/tasks/exec-started" type=containerd.events.TaskExecStarted
time="2020-07-17T17:27:35.742286393+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.744932457+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.753819210+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.806914575+08:00" level=info msg="shim reaped" id=d5ddd28e18b6f2dbe81c2adb1f0861b6df03a09d088aad22e27d5e1bd25477ea
time="2020-07-17T17:27:35.806935058+08:00" level=info msg="shim reaped" id=a642db1dc9bfb2ff372d87d21b638f407e714f5749d493b8f35ad037a7ec1698
time="2020-07-17T17:27:35.807217511+08:00" level=info msg="shim reaped" id=476dd42fad4b44988e5385480f4837398336fa66de7bc04dd371007c08856a95
time="2020-07-17T17:27:35.807216920+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:35.816262678+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.825038260+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.825113047+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:35.853314286+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.893172174+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:35.894508456+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:36.066534279+08:00" level=info msg="shim reaped" id=6523b7d8efad00bd640e0a9f8415ecc0c31abce034dc3f278efe8c09a6cdecca
time="2020-07-17T17:27:36.070589015+08:00" level=info msg="shim reaped" id=cff0faf0649779d053dbd2c79d8fde581115bad77785f45b0b217a5cb85f144b
time="2020-07-17T17:27:36.075518261+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:36.079703016+08:00" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete
time="2020-07-17T17:27:36.083378139+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:36.109474301+08:00" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit
time="2020-07-17T17:27:36.155245849+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:36.180189098+08:00" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete
time="2020-07-17T17:27:36.319285321+08:00" level=debug msg="received signal" signal=terminated

**The docker logs：**
time="2020-07-17T17:27:36.240068915+08:00" level=debug msg="Calling GET /containers/debf53f3ef4d1d759fea197aad0873ca172aac456dd32ca8f6f1914bc652e871/json"
time="2020-07-17T17:27:36.240823979+08:00" level=debug msg="Calling GET /containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%2C%22io.kubernetes.pod.uid%3Da617fbf6-980b-4d08-ac20-caa3701b5c62%22%3Atrue%7D%7D&limit=0"
time="2020-07-17T17:27:36.252923213+08:00" level=debug msg="Calling GET /containers/d0f04f6e07ac97afbc7c9b999fb48aef5502192efe5122823cf9f1d619b04556/json"
time="2020-07-17T17:27:36.253766287+08:00" level=debug msg="Calling GET /images/sha256:3367281657991059fd5cc0e80afdc20462e8008f0e61fbab92590e26344d8ea8/json"
time="2020-07-17T17:27:36.255331560+08:00" level=debug msg="Calling GET /containers/debf53f3ef4d1d759fea197aad0873ca172aac456dd32ca8f6f1914bc652e871/json"
time="2020-07-17T17:27:36.255368281+08:00" level=debug msg="Calling GET /containers/feb587fc80e74822d5b9f2323e56cb77f3fec10ec7c2c6c8d75fa9230183bdc7/json"
time="2020-07-17T17:27:36.256052751+08:00" level=debug msg="Calling POST /containers/feb587fc80e74822d5b9f2323e56cb77f3fec10ec7c2c6c8d75fa9230183bdc7/stop?t=10"
time="2020-07-17T17:27:36.256063131+08:00" level=debug msg="Calling POST /containers/debf53f3ef4d1d759fea197aad0873ca172aac456dd32ca8f6f1914bc652e871/stop?t=10"
time="2020-07-17T17:27:36.272888845+08:00" level=debug msg="Calling GET /containers/d0f04f6e07ac97afbc7c9b999fb48aef5502192efe5122823cf9f1d619b04556/json"
time="2020-07-17T17:27:36.273695663+08:00" level=debug msg="Calling GET /images/sha256:3367281657991059fd5cc0e80afdc20462e8008f0e61fbab92590e26344d8ea8/json"
time="2020-07-17T17:27:36.274657238+08:00" level=debug msg="Calling GET /containers/d0f04f6e07ac97afbc7c9b999fb48aef5502192efe5122823cf9f1d619b04556/json"
time="2020-07-17T17:27:36.275382440+08:00" level=debug msg="Calling DELETE /containers/d0f04f6e07ac97afbc7c9b999fb48aef5502192efe5122823cf9f1d619b04556?force=1&v=1"
time="2020-07-17T17:27:36.309570967+08:00" level=debug msg="Calling GET /containers/d0f04f6e07ac97afbc7c9b999fb48aef5502192efe5122823cf9f1d619b04556/json"
time="2020-07-17T17:27:36.321991437+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
time="2020-07-17T17:27:36.322021059+08:00" level=warning msg="failed to delete process" container=a2ba48fdff2502c7ef7eba0e3e5f31d61886f6b3b2aebcf525e7a53c461a0037 error="transport is closing: unavailable" module=libcontainerd namespace=moby process=8db81db6d6da82fb3a610bf3cbae14a959069cefb0a42833ce8f3851bef90398
time="2020-07-17T17:27:36.322104571+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
time="2020-07-17T17:27:36.322116915+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
time="2020-07-17T17:27:36.322151562+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201a1060, TRANSIENT_FAILURE" module=grpc
time="2020-07-17T17:27:36.322172717+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
time="2020-07-17T17:27:36.322174645+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4201a1060, CONNECTING" module=grpc
time="2020-07-17T17:27:36.322189270+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-17T17:27:36.322211527+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4207b39b0, TRANSIENT_FAILURE" module=grpc
time="2020-07-17T17:27:36.322226474+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4207b39b0, CONNECTING" module=grpc
time="2020-07-17T17:27:36.322202418+08:00" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>" module=libcontainerd namespace=plugins.moby
time="2020-07-17T17:27:36.539667308+08:00" level=debug msg="Calling POST /containers/7037ab79ce28fe258878fdd390b608288df2dbaf1691bd40fce71f15ba88f0ed/stop?t=30"
time="2020-07-17T17:27:36.539749701+08:00" level=debug msg="Sending kill signal 15 to container 7037ab79ce28fe258878fdd390b608288df2dbaf1691bd40fce71f15ba88f0ed"
time="2020-07-17T17:27:36.624977279+08:00" level=info msg="Processing signal 'terminated'"
time="2020-07-17T17:27:36.642065677+08:00" level=debug msg="Calling POST /containers/8903e604f8e0484fe1d4442477ab6ca31150f387427283e37ddd81c2d4150f9b/stop?t=30"
time="2020-07-17T17:27:36.642132416+08:00" level=debug msg="Sending kill signal 15 to container 8903e604f8e0484fe1d4442477ab6ca31150f387427283e37ddd81c2d4150f9b"
time="2020-07-17T17:27:36.680927909+08:00" level=debug msg="Clean shutdown succeeded"
time="2020-07-17T17:27:36.681015942+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=plugins.moby
time="2020-07-17T17:27:36.681069805+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2020-07-17T17:27:36.681025427+08:00" level=debug msg="processing event stream" module=libcontainerd namespace=moby

**Comment by thaJeztah** [comment]
> I found that both docker and containerd received a 15 signal. Who sent the signal they received, and what caused it to send a 15 signal to stop them? Every time this problem occurs, the rpc error message is accompanied by the docker before receiving the terminated signal. Is it related to the failure of the docker and the failure of the rpc call?

Not sure what would send that signal; did the machine run out of resources and did systemd perhaps terminate?

We did recently (not yet in a release) merge a change to prevent containerd from being OOM-killed by the kernel (see https://github.com/docker/containerd-packaging/pull/186, and related https://github.com/containerd/containerd/pull/4409), but such situations would probably be visible in your system logs (see the discussion on https://github.com/docker/for-linux/issues/1062)

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
