### ISSUE TITLE
opentracing UDP packets getting dropped and not reaching to jaeger agent

### ISSUE THREAD

**Issue by mayankvaid88** [moby/moby#41220]
**Description**

In my application I have an NGINX which forwards request to microservice A which in turns hits microservice B.
All the three components are open-tracing enabled and should be reporting spans to host machine on port 6831 which in turns send packets to jaeger-agent container.

Now in real scenario what's happening is, NGINX and microservice B are always reporting the spans to <HOST IP>: 6831 and I am able to see them in jaeger query UI. However, there is a frequent UDP packet drop that are sent by microservice A and I am not able to see the spans reported by microservice A in jaeger UI

**jaeger container docker ps  :**

1e7cc93e8019        jaegertracing/jaeger-agent              "/go/bin/agent-linux…"   2 hours ago         Up 2 hours          5775/udp, 6832/udp, 5778/tcp, **0.0.0.0:6831->6831/udp**   jaeger_agent

**Steps to reproduce the issue:**
1. Have a setup as above
2. Run jaeger agent, collector and quey in a separate container (or could use jaeger all in one docker image)
3. expose the jaeger agent port 6831 and make all the components to send udp packets to host machine on 6831 port

**Describe the results you received:**
There is a frequent drop in udp packets sent by Microservice A and couldn't reach to jaeger-agent.

**Describe the results you expected:**
All the packets reported by Microservice A should have been received by jaeger-agent for further processing

**Additional information you deem important (e.g. issue happens only occasionally):**
The above setup works If i make `microservice A`  directly report spans to `jaeger agent` using jaeger IP

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 53
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.779GiB
 Name: docker-desktop
 ID: YNPZ:ZK7X:CTEK:VEMY:C7MY:SI3L:X5FC:VST4:P5FJ:FIFW:EOY3:WMKN
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 178
  Goroutines: 153
  System Time: 2020-07-16T13:15:36.7686233Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Host machine operating system : Mac OSX 

**Logs:** 
`Microservice A `

/ # tcpdump -n udp -X
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
13:27:32.558141 IP 172.18.0.15.42940 > 192.168.1.56.6831: UDP, bad length 6151 > 1472
	0x0000:  4500 05dc 7fcc 2000 4011 6743 ac12 000f  E.......@.gC....
	0x0010:  c0a8 0138 a7bc 1aaf 180f 4020 8281 0509  ...8......@.....
	0x0020:  656d 6974 4261 7463 681c 1c18 0965 6273  emitBatch....ebs
	0x0030:  2d6c 6f67 696e 193c 1808 686f 7374 6e61  -login.<..hostna
	0x0040:  6d65 1500 180c 6462 3533 3039 6165 6530  me....db5309aee0
	0x0050:  3832 0018 0e6a 6165 6765 722e 7665 7273  82...jaeger.vers
	0x0060:  696f 6e15 0018 0a4a 6176 612d 312e 312e  ion....Java-1.1.
	0x0070:  3000 1802 6970 1500 180b 3137 322e 3138  0...ip....172.18
(let me know if full log is required)

Since Jaeger-agent image is from Scratch therefore I won't able to provide the tcpdump over there but from Jaeger UI I can see the traffic that was sent by Microservice A is not visible. Also Jaeger logs doesn't have traces of span reported by Microservice A. Let me know if you are interested to have the logs of jaeger as well

**Comment by thaJeztah** [comment]
Do you have exact steps to reproduce the issue? Also, if possible; does the issue reproduce on a native Linux host as well? (I know there's additional networking-related things involved in Docker Desktop on Mac, which may be relevant)

**Comment by mayankvaid88** [comment]
Do you have exact steps to reproduce the issue? -> shall I put my working dummy code on git repo. Does that helps ?
 Also, if possible; does the issue reproduce on a native Linux host as well? I am not sure as I didn't tried on linux operating system (I don't have Linux host available to me).

**Comment by thaJeztah** [comment]
Yes, if you have exact steps to reproduce, that could help verifying the issue (and checking if it's scoped to Docker Desktop or on other platforms as well)

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
