### ISSUE TITLE
How to disable /etc/hosts /etc/hostname /etc/resolv.conf mounts with docker run ?

### ISSUE THREAD

**Issue by mrinaldhillon** [moby/moby#41229]
Is there a way to disable bind mounts of /etc/hosts /etc/hostname /etc/resolv.conf . Also can we make these files persist through container restarts?

**Comment by mrinaldhillon** [comment]
Is this supported ?

**Comment by AkihiroSuda** [comment]
No

**Comment by thaJeztah** [comment]
> Also can we make these files persist through container restarts?

You can specify most of those options in the container configuration when using `docker run` / `docker create`;

Options that specify the DNS to use (and options). Note that if the container is connected to a custom network, that the DNS in `/etc/resolv.conf` will always be pointing to docker's embedded DNS (but it will forward to the DNS you configured)

```
      --dns list                       Set custom DNS servers
      --dns-option list                Set DNS options
      --dns-search list                Set custom DNS search domains
```

Option to set the container's domain and host name

```
      --domainname string              Container NIS domain name
  -h, --hostname string                Container host name
```

Option to add custom entries to `/etc/hosts`:

```
     --add-host list                  Add a custom host-to-IP mapping (host:ip)
```

**Comment by kenyon** [comment]
This should be reopened. Without the option to disable these mounts, there is no way to use Docker for using or testing software that needs to replace `/etc/resolv.conf` with a symlink, for example, like [resolvconf](https://tracker.debian.org/pkg/resolvconf).

**Comment by j3pic** [comment]
Updating /etc/hosts via `docker run` or `docker create` is not useful if the container is being started by a third-party piece of software. It's even worse if the third-party software is controlled by another third party's managed service on their servers. The only thing I control directly is the Docker image itself.

The problem is *so* bad, that it looks like I'm going to be forced to patch Glibc to look someplace other than `/etc/hosts`.

**Comment by j3pic** [comment]
Patching Glibc worked and didn't cause any problems. The binary to alter in my Docker image was `/lib/x86_64-linux-gnu/libnss_files.so.2`.
