### ISSUE TITLE
Grafana Loki Logger

### ISSUE THREAD

**Issue by cyriltovena** [moby/moby#41246]
**Description**

Hello I'm one of the maintainer of https://github.com/grafana/loki and I was wondering if you would be interested into incorporating the loki logger driver into this repository. (https://github.com/moby/moby/tree/master/daemon/logger)

The driver is currently located here: https://github.com/grafana/loki/tree/master/cmd/docker-driver
and the documentation can be found here: https://github.com/grafana/loki/blob/master/docs/sources/clients/docker-driver/_index.md

I'm wondering what's the requirement for acceptance, but also what the PR should includes (not sure where the docs for each logger is).

Thank you in advance.

Cyril

**Comment by thaJeztah** [comment]
We prefer to not add more logging drivers in the daemon itself, but instead to provide additional logging drivers as plugins (https://docs.docker.com/engine/extend/) that can be installed through `docker plugin install` (https://docs.docker.com/engine/reference/commandline/plugin_install/)

There is a proposal from @cpuguy83  to move the existing logging drivers to separate binaries https://github.com/moby/moby/issues/40517 (which could be another option); that discussion is still ongoing, but I welcome you to participate in that discussion (and perhaps you're interested in contributing and helping with making those changes if the proposal is accepted)

**Comment by cyriltovena** [comment]
Ho that’s sad, more so since you support already many vendor logger, like splunk.

We already have a plugin which works well, the problem is when you run on restricted environment where you don’t have access to configuration of the daemon.

#40517 seems a bit stale, not against helping though.

ho well, I tried 😔

**Comment by thaJeztah** [comment]
> more so since you support already many vendor logger, like splunk.

Those drivers were added before the plugins were implemented. Some of the drivers brought in a big dependency graph, and with that additional load on maintaining them; this was one of the motivations driving the implementation of plugins

**Comment by cpuguy83** [comment]
Not stale, it's top of mind.
Would gladly take help implementing the changes.
GitHub <notifications@github.com> wrote:
““more so since you support already many vendor logger, like splunk.”

Those drivers were added before the plugins were implemented. Some of the drivers brought in a big dependency graph, and with that additional load on maintaining them; this was one of the motivations driving the implementation of plugins”

**Comment by pgassmann** [comment]
What's the way to update a logging plugin in a Swarm Cluster?

Today I exercised with updating the loki driver on a host with docker-compose and swarm services. It is not trivial. to update the driver, you need to disable it first. to disable a plugin, it should not be in use, that means to stop all containers using it. It is difficult and non-trivial to stop all containers and restart them after upgrading and re-enabling the loki driver.

In a swarm cluster, the services automatically get recreated if i stop them using `docker stop $(docker ps -a -q)`

If I stop the docker daemon I cannot manage the plugins.

**Comment by cpuguy83** [comment]
@pgassmann 

Note that swarm has some support for managing plugins on the cluster.
But... you should be able to use `docker plugin upgrade` to do this.

**Comment by pgassmann** [comment]
@cpuguy83 would be easy if it was so straightforward:
`
```
# docker plugin upgrade loki grafana/loki-docker-driver:latest --grant-all-permissions --skip-remote-check`
the plugin must be disabled before upgrading
# docker plugin disable loki
Error response from daemon: plugin loki:latest is in use

```

**Comment by cpuguy83** [comment]
Ok well, `docker plugin disable -f` ought to do.

**Comment by pgassmann** [comment]
Thank you. Yes the following procedure works:
```
docker plugin disable loki --force
docker plugin upgrade loki grafana/loki-docker-driver:latest --grant-all-permissions --skip-remote-check
docker plugin enable loki
systemctl restart docker
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
