### ISSUE TITLE
journald log driver send timestamp to systemd, doubles timestamp

### ISSUE THREAD

**Issue by helmut72** [moby/moby#41243]
**Description**

journald log driver send timestamp to systemd and therefore doubles the timestamp in systemd

**Steps to reproduce the issue:**
1. enable journald log driver
2. journalctl -f

**Describe the results you received:**

Jul 21 21:50:34 myserver dovecot[668]: Jul 21 21:50:34 imap-login: Info: Login:...

**Describe the results you expected:**

Jul 21 21:50:34 myserver dovecot[668]: imap-login: Info: Login:...

**Comment by thaJeztah** [comment]
Isn't the second time stamp generated by the container itself? Docker captures stdout and stderr from the container's process, so if the container's process generates logs with time stamps, those will be included in the log message

**Comment by helmut72** [comment]
Yes, I guess you are right. Nevertheless journald should receive just the message itself from Docker - without timestamp. If I strip the log format (if possible at all) of the service running in the container, then I get no timestamp in `docker logs container`.

**Comment by thaJeztah** [comment]
Docker doesn't manipulate the logs that the container process generated; each line of output is sent as a log message, and they're sent as-is (except for splitting messages that are longer than the buffer size)

**Comment by helmut72** [comment]
Ok, will close it.

Intention is that I want to have Grafana Dashboards with Loki, but:
- Avoid sending logs through multiple logserver chains because of the "one log driver" limitation of Docker CE
- Reduce running containers for a workaround of this limitation. Now I use Logspout container to send it to Rsyslog. Rsyslog filter the timestamps, but this isn't possible in systemd-journal.
- Having logs on the host for fail2ban to block unwanted logins. Fail2ban supports systemd-journal.
- Still having logs in Portainer GUI. It's easier to get the logs from a mobile phone in Portainer than using a Terminal. For using logs in Portainer, `docker logs` is required

Still a puzzle not to overload a Raspberry just for logs... :(

**Comment by thaJeztah** [comment]
> it's only possible with json and journald log driver in Docker CE...

If you don't need the JSON log files itself (I think kubernetes uses them), you can consider using the `local` logging driver, which also is supported by `docker logs` (and has some advantages; it's less resource intensive, and by default has log-rotation enabled). The next (20.xx) release of docker will also have support for "dual logging", which allows the `local` logging driver to be used as a local buffer for `docker logs`, and configuring any other logging driver (for example to send to a logging aggregator). That feature was previously only available in the Enterprise edition, but has been upstreamed in https://github.com/moby/moby/pull/40543

**Comment by helmut72** [comment]
> The next (20.xx) release of docker will also have support for "dual logging"

Fantastic! Thanks for the info. This resolves all my headaches regarding logging.

> you can consider using the local logging

Will do it with a strict limit. I only need docker logs for current logs/live debugging - nothing more.
