### ISSUE TITLE
Deprecate `docker run --kernel-memory`

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41252]
Kernel 5.4 deprecated `kmem.limit_in_bytes`, we should deprecate `docker run --kernel-memory` as well.

https://github.com/torvalds/linux/commit/0158115f702b0ba208ab0b5adf44cae99b3ebcc7

```
memcg, kmem: deprecate kmem.limit_in_bytes

Cgroup v1 memcg controller has exposed a dedicated kmem limit to users
which turned out to be really a bad idea because there are paths which
cannot shrink the kernel memory usage enough to get below the limit (e.g.
because the accounted memory is not reclaimable).  There are cases when
the failure is even not allowed (e.g.  __GFP_NOFAIL).  This means that the
kmem limit is in excess to the hard limit without any way to shrink and
thus completely useless.  OOM killer cannot be invoked to handle the
situation because that would lead to a premature oom killing.

As a result many places might see ENOMEM returning from kmalloc and result
in unexpected errors.  E.g.  a global OOM killer when there is a lot of
free memory because ENOMEM is translated into VM_FAULT_OOM in #PF path and
therefore pagefault_out_of_memory would result in OOM killer.

Please note that the kernel memory is still accounted to the overall limit
along with the user memory so removing the kmem specific limit should
still allow to contain kernel memory consumption.  Unlike the kmem one,
though, it invokes memory reclaim and targeted memcg oom killing if
necessary.

Start the deprecation process by crying to the kernel log.  Let's see
whether there are relevant usecases and simply return to EINVAL in the
second stage if nobody complains in few releases.
```

related: https://github.com/containerd/cgroups/pull/175

**Comment by thaJeztah** [comment]
That `kmem` option just keeps on giving 😂  /cc @kolyshkin 

Does that mean it will be deprecated for cgroup v1 as well, or just that it won't be supported by cgroup v2

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/41254


> Does that mean it will be deprecated for cgroup v1 as well, or just that it won't be supported by cgroup v2

The deprecation is for cgroup v1.
cgroup v2 does not have support for kernel memory limit.

**Comment by thaJeztah** [comment]
Interesting; has something like that been done before? (as the kernel promises backward compatibility) or is that out of scope for the kernel API?

**Comment by AkihiroSuda** [comment]
Yes kernel 5.0 dropped blkio.weight 


https://github.com/torvalds/linux/commit/f382fb0bcef4c37dc049e9f6963e3baf204d815c

**Comment by thaJeztah** [comment]
Should we deprecate `--blkio-weight` and `--blkio-weight-device` as well?

**Comment by AkihiroSuda** [comment]
No, cgroup2 supports io.weight

**Comment by AkihiroSuda** [comment]
(For cgroup1 it can be deprecated)
