### ISSUE TITLE
The swarm does not have a leader.

### ISSUE THREAD

**Issue by xxalfa** [moby/moby#41250]
**Description**

My docker swarm has three nodes. All three are classified as managers. As soon as two of the three nodes are offline, the ability to manage the swarm is removed. 

**Steps to reproduce the issue:**
```
root@SV3:~# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
91zozkbd6jma0hfo13zkjluvs     SV2                 Ready               Active              Reachable           19.03.8
n3nmdb8wuc13ofuufg26h5yyl *   SV3                 Ready               Active              Leader              19.03.8
2w6cpqrws8j42zzqoc49snvz4     SV4                 Down                Active              Unreachable         19.03.12
root@SV3:~# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
91zozkbd6jma0hfo13zkjluvs     SV2                 Ready               Active              Unreachable         19.03.8
n3nmdb8wuc13ofuufg26h5yyl *   SV3                 Ready               Active              Leader              19.03.8
2w6cpqrws8j42zzqoc49snvz4     SV4                 Down                Active              Unreachable         19.03.12
root@SV3:~# docker node ls
Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
root@SV3:~# docker node ls
Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
```
**Describe the results you received:**

To put it literally, the branch I'm sitting on is being cut off. 

**Describe the results you expected:**

Even with only one node, I should still be able to manage the swarm.

**Comment by AkihiroSuda** [comment]
Expected behavior of Raft.

**Comment by AkihiroSuda** [comment]
See https://docs.docker.com/engine/swarm/raft/

**Comment by xxalfa** [comment]
@AkihiroSuda

It is very rude, without any feedback from me, that you simply close the issue. 

Let's just say SV2 and SV4 fell into water. The services basic_proxy and basic_whoami can still be used on SV3, which is good. What do I have to do to add or remove a node? or if I want to change the service, there is nothing I can do in the current situation?

When I started building the swarm, there was only SV3, why is one node not enough when others fall into the water?

According to the documentation, the defined behavior is correct, only I say the definition has to be changed. I would like to know how to open Pandora's box again?

**Comment by AkihiroSuda** [comment]
> What do I have to do to add or remove a node? or if I want to change the service, there is nothing I can do in the current situation?

`docker swarm leave --force` and `docker swarm init` (if you can't bring back neither of SV2 and SV4)

> why is one node not enough when others fall into the water?

For preventing split-brain, you need to have the quorum, e.g. 2 nodes for 3-node cluster, 3 nodes for 5-node cluster.

**Comment by xxalfa** [comment]
When I leave the swarm, I am forced to recreate the service, which lowers the high availability for a short period of time. In my opinion, one manager is sufficient to then assign new managers. It would be an enormous amount of work to set up the service from scratch. We speak of reaction time, how quickly an admin can enter the commands. With `docker stack deploy`, the world is simple, but who knows after years whether there have been several service updates.

Since we're talking about `docker stack deploy`, I would like to give an example or maybe even hear a solution from you. I wanted to use the `--replicas-max-per-node` parameter in the YML file. No matter what I try, I get an error message. Do I have to store the parameter under placement or deploy?  Is the max deposited in the front or in the middle?

**Comment by AkihiroSuda** [comment]
`docker swarm init --force-new-cluster` keeps existing data

https://docs.docker.com/engine/reference/commandline/swarm_init/#--force-new-cluster

> `--force-new-cluster`
> This flag forces an existing node that was part of a quorum that was lost to restart as a single node Manager without losing its data.

**Comment by xxalfa** [comment]
Now I agree that the issue can be closed, oh it's already done. With the available parameters, the high availability can be improved again. Although I still believe that a node is sufficient to continue working without going through the `--force-new-cluster` parameter. I will stop my experiments with YML files in order to build good parameter chains. Thank you for the pioneering links that the documentation jungle had hidden from me.

**Comment by xxalfa** [comment]
I have to report problems again. On SV3 I ran the parameter `--force-new-cluster`, where I was happy to be able to control it again. When I was able to rescue SV2 and SV4 out of the water, all services recovered. Now my problem: if I send a request to SV3, it takes several seconds, as soon as the first connection is established, all further requests are set up very quickly. After a short pause, only the first request is again very sluggish. What could be the cause?

**Comment by thaJeztah** [comment]
>  Although I still believe that a node is sufficient to continue working without going through the --force-new-cluster parameter.

This is not possible, as doing so would cause inconsistent state in a "split head" situation. Take the following case; there's 3 managers. Because there's 3 managers, a majority is needed to take any decision (3/2=1.5, so 2 managers);

`manager-A + manager-B + manager-C` 

At some point, networking is disrupted with `manager C`:

`manager-A + manager-B`
`manager-C`

- From `manager-A + manager-B`'s perspective, 1 manager is unavailable, but they still hold a majority, so are able to make changes to the cluster state while `manager C` is not available. Once `manager-C` is able to connect to the cluster again, it will update it's state to match again. If this is expected to be a temporary situation, no action is needed (other than waiting for network-disruption to be gone, and `manager-C` to reconnect), however, risk has increased (if one of both remaining managers goes down, you'll lose control over the cluster). In some cases, additional managers can be (temporarily) added to prevent that situation (going from 3 to 5 managers). These managers can be demoted and removed once manager-C joins again (to get back to a 3 manager setup). 
- However, from `manager-C`'s perspective, _two managers_ are unavailable. Given that it's a 3-manager setup, `manager-C` is not allowed to make changes to the cluster state. If it _would_ be allowed to make changes, then both "sides" of the split would be able to change cluster state; once network connection is re-established, cluster state is effectively broken.

> Now my problem: if I send a request to SV3, it takes several seconds, as soon as the first connection is established, all further requests are set up very quickly. After a short pause, only the first request is again very sluggish. What could be the cause?

Really hard to tell, and likely beyond scope for this issue tracker (which is not intended as a support forum)

**Comment by xxalfa** [comment]
In the meantime I understand the topic of the split head, but now I would like the following message to appear when the situation arises.

New error message: The swarm control system is in a critical condition. Decision integrity can no longer be guaranteed. More than half of the managers must be available. Enter `docker node ls` to get an overview or enter `docker swarm init --force-new-cluster` to disconnect this node with the configuration and continue alone.

> Really hard to tell, and likely beyond scope for this issue tracker (which is not intended as a support forum)

I agree with you, this is not a forum, only I didn't know where to go. Is there a support forum here at Github?

root@SV2:~# docker swarm join --token SWMTKN-1-...
Error response from daemon: Timeout was reached before node joined. The attempt to join the swarm will continue in the background. Use the `docker info` command to see the current swarm status of your node.

In the meantime I have new problems when I wanted to leave a node and rejoin it, the node suddenly refused. `docker info` showed that SV2's IP was entered twice. The swarm was not able to heal itself, I had to completely dissolve the swarm in order to be able to continue normally. Right now I have more problems with `docker swarm` than I enjoy it. Sometimes the problems come from the containers because a condition is not met and sometimes, as shown in the last error message, the swarm is causing me the problems.
