### ISSUE TITLE
Docker Node Goes Into Non Responding Mode In Docker Swarm

### ISSUE THREAD

**Issue by amirakhan** [moby/moby#41251]
**Description**

**Steps to reproduce the issue:**
1. it is random which usually occurs randomly and not sure how to re-produce this issue
2. One observation is if we deploy some service in network=host it end up causing this issue
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens occasionally
**Output of `docker version`:**
```
18.09.0, build 4d60db4
```

**Output of `docker info`:**

```
Containers: 332
Running: 29
Paused: 0
Stopped: 303
Images: 6223
Server Version: 18.09.0
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
NodeID: 6ay21513lar6vjkvu7wh0mugv
Is Manager: true
ClusterID: -------------------
Managers: 3
Nodes: 6
Default Address Pool: 10.0.0.0/8
SubnetSize: 24
Orchestration:
  Task History Retention Limit: 5
Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
Dispatcher:
  Heartbeat Period: 5 seconds
CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
Autolock Managers: false
Root Rotation In Progress: false
Node Address: ----------------
Manager Addresses:
  ----------.93:2377
  ----------.94:2377
  ----------.95:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
seccomp
  Profile: default
Kernel Version: 3.10.0-1062.12.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 251.2GiB
Name: ----------
ID: 6SXS:PM5D:5WS3:UZS4:NN2A:VMDZ:5WGM:O76T:AQCP:MCJS:VUW2:MXGI
Docker Root Dir: --------------------/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
----------:5000
----------:5000
127.0.0.0/8
Live Restore Enabled: false
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by thaJeztah** [comment]
Note that docker 18.09.x reached EOL and is no longer maintained. It's possible that fixes went into patch releases for 18.09 or 19.03.x that fixed issues, but that's hard to tell from just the information in this ticket. Try to collect logs of the docker daemon, and syslog to try to find if there's anything that may point to what's causing it. If you have a test setup in which you can reproduce the issue, run the daemon with debug mode enabled (`{"debug":true}` in `/etc/docker/daemon.json` (this will create a lot of additional logs, so may not be ideal to run in a production setup).

I notice you have a lot of stopped containers and images in your machine; those can take up resources, and it might be good to periodically run `docker system prune` on your machines to clean up.

At least I would recommend having an up-to-date version of docker, the docker cli, and containerd.io installed; if you're not able to upgrade to docker 19.03.x, at least make sure you have the latest patch release of 18.09.x installed.

With the information currently in this ticket, I don't see anything actionable, so I'm closing this, but feel free to continue the conversation
