### ISSUE TITLE
Docker instaltion issue in windows 10

### ISSUE THREAD

**Issue by venkatnaveen7** [moby/moby#41263]
I would like to deploy this app with Docker.
So i downloaded and installed docker for windows,
But im not able to start docker

when I say docker version in cmd system said as below
Client: Docker Engine - Community
Version: 19.03.8
API version: 1.40
Go version: go1.12.17
Git commit: afacb8b
Built: Wed Mar 11 01:23:10 2020
OS/Arch: windows/amd64
Experimental: false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by thaJeztah** [comment]
This looks more an issue for the Docker Desktop for Windows issue tracker; https://github.com/docker/for-win/issues

Are you running commands from an elevated (privileged / admin) shell?

**Comment by venkatnaveen7** [comment]
HI, @thaJeztah  Thanks for your reply. The issue is with the installation.
I'm using Windows 10 Home. Now I have installed the Docker toolbox which is working fine.

**Comment by thaJeztah** [comment]
Installation on recent versions of Windows 10 Home should now be possible, using WSL2 as backend for Docker Desktop; https://docs.docker.com/docker-for-windows/install-windows-home/

Note that Docker Toolbox is deprecated, so not the recommended solution.
