### ISSUE TITLE
Incorrect API documentation for SystemDataUsage

### ISSUE THREAD

**Issue by mdonoughe** [moby/moby#41264]
**Description**

In the OpenAPI documentation for the SystemDataUsage operation, the response schema describes a BuildCache as having properties CreatedAt and LastUsedAt of type integer. However, in the code types.BuildCache is defined as having properties CreatedAt and LastUsedAt of type time.time, and when a time.time value is passed to json.Encoder the type emitted in the JSON document is a RFC 3339 string because of time.time's MarshalJSON implementation.

This causes problems for anyone who is using the API documentation to autogenerate API clients.

**Steps to reproduce the issue:**
1. Run builds using BuildKit.
2. Request SystemDataUsage via the API.

**Describe the results you received:**

    {
      "ID": "rrc3gr2ks5mm41ntmlqsqu2k4",
      "Parent": "2tub3atjmssqqh0ji08jjc5oj",
      "Type": "regular",
      "Description": "fileop target",
      "InUse": false,
      "Shared": false,
      "Size": 353,
      "CreatedAt": "2020-06-17T14:55:03.5952988Z",
      "LastUsedAt": "2020-06-17T14:55:44.6490503Z",
      "UsageCount": 1
    }

This causes [Bollard](https://github.com/fussybeaver/bollard) to return a parse error because the CreatedAt property is found, but cannot be converted to an integer for storage into the struct.

**Describe the results you expected:**

Either CreatedAt and LastUsedAt should be integers, or the API specification should define these properties as strings (or being possibly being either type?).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

I don't have the output of docker info because this issue was originally found by @mac-chaffee and raised as stepchowfun/docuum#78.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting; looks indeed that this was overlooked in the review of https://github.com/moby/moby/pull/37651. Let me open a PR for this

**Comment by thaJeztah** [comment]
PR is up; https://github.com/moby/moby/pull/41267
