### ISSUE TITLE
Enhancement: add more information when file not find in get host device for friendly to ops

### ISSUE THREAD

**Issue by zvier** [moby/moby#41280]
**Description**
`docker start` failed with error message:    
Error response from daemon: no such file or directory
Error: failed to start containers: test

The reason is `/dev/sda` device is not exist in the host which used it in the container when create.  This message is not so accurate which confused ops to find the reason if not  familiar with the source code.

**Steps to reproduce the issue:**
1. `docker create --name test --device /dev/sda:/dev/sda --device-read-bps /dev/sda:1mb busybox`（note: the host not have the `/dev/sda` device,  and can use `/dev/xxx` replace to simulate this  phenomenon）
2. `docker start test` 

**Describe the results you received:**

Error response from daemon: no such file or directory
Error: failed to start containers: test

**Describe the results you expected:**
Error response from daemon: failed to stat "/dev/sda": no such file or directory
Error: failed to start containers: test

May be can update functions  getBlkioThrottleDevices in daemon_unix.go with `errors.Wrapf` to wrap more value information for ops use.
```go
...
if err := unix.Stat(weightDevice.Path, &stat); err != nil {
      return nil, errors.Wrapf(err, "failed to stat %q", d.Path)
}
...
```
**docker version**
19.03.5

**Comment by thaJeztah** [comment]
Can you provide exact steps that you're running and the error that's printed?

Trying your initial example (after putting `busybox` after the options);

```bash
docker create --name=test --device /dev/sda:/dev/sda busybox
docker start test
# Error response from daemon: error gathering device information while adding custom device "/dev/sda": no such file or directory
# Error: failed to start containers: daf68805f58b2b4af0e7c884ca97f6bc79c031f8cda61d468a976bc11f261feb
```

```bash
docker run --rm --device /dev/sda:/dev/sda busybox
# docker: Error response from daemon: error gathering device information while adding custom device "/dev/sda": no such file or directory.
# ERRO[0000] error waiting for container: context canceled
```

**Comment by zvier** [comment]
> Can you provide exact steps that you're running and the error that's printed?
> 
> Trying your initial example (after putting `busybox` after the options);
> 
> ```shell
> docker create --name=test --device /dev/sda:/dev/sda busybox
> docker start test
> # Error response from daemon: error gathering device information while adding custom device "/dev/sda": no such file or directory
> # Error: failed to start containers: daf68805f58b2b4af0e7c884ca97f6bc79c031f8cda61d468a976bc11f261feb
> ```
> 
> ```shell
> docker run --rm --device /dev/sda:/dev/sda busybox
> # docker: Error response from daemon: error gathering device information while adding custom device "/dev/sda": no such file or directory.
> # ERRO[0000] error waiting for container: context canceled
> ```

Oh, sorry,  in my newest environment with docker 19.03.5, above probelem is not exist. The result is same with you. My older version is 18.9. 

So, I will close this ISSUE.

**Comment by thaJeztah** [comment]
Ah, that explains; we probably improved those errors already at some point. Thanks!

**Comment by zvier** [comment]
@thaJeztah Hello, may be I need to reopen this issue. I lost another flag such as `--device-read-bps` last time. Now, I update my description and it can also reproduce in the laste version.
