### ISSUE TITLE
DOCKER_CONTEXT has precedence over `docker build PATH`

### ISSUE THREAD

**Issue by benjaoming** [moby/moby#41313]
**Description**

The documentation does not AFAIK mention that environment would take precedence over command line arguments, which is AFAIK not conventional.

Only mention is this [1]

> You can also set the current context using the DOCKER_CONTEXT environment variable. This overrides the context set with docker context use.

[1] https://docs.docker.com/engine/context/working-with-contexts/#use-a-different-context

**Steps to reproduce the issue:**

```bash
  ~ ls test
Dockerfile
➜  ~ DOCKER_CONTEXT=/dev/null docker build ./test
unable to resolve docker endpoint: context "/dev/null" does not exist
```

**Describe the results you received:**

Environment is read instead of the positional `PATH`

**Describe the results you expected:**

Command line is read.

**Additional information you deem important (e.g. issue happens only occasionally):**

n/a

**Output of `docker version`:**

n/a - happens on all version I tried

**Output of `docker info`:**

n/a - happens on multiple systems

**Additional environment details (AWS, VirtualBox, physical, etc.):**

also n/a

**Comment by AkihiroSuda** [comment]
CLI is maintained in https://github.com/docker/cli , not in Moby

**Comment by AkihiroSuda** [comment]
The `DOCKER_CONTEXT` is for a CLI context like `docker --context=aci run`, not for a build context like `docker build ./some-dir`
