### ISSUE TITLE
Cannot use dmesg, I guess no root access even if logged as root and with --privileged

### ISSUE THREAD

**Issue by ssurrealism** [moby/moby#41318]
Having Windows 10 Pro 1809 and
`docker --version`
```
Docker version 19.03.12, build 48a66213fe
```

When I do.
`docker run -it --entrypoint /bin/bash ubuntu:groovy`
and then login into it
`docker exec -u 0 -it --privileged some_random_name bash`

when I type `dmesg` I see:
```
dmesg: read kernel buffer failed: Operation not permitted
```

I would like to use `dmesg` because my actual container hangs no idea why (off topic for this bug).
I do have (output of `sysctl kernel.dmesg_restrict`)
```
kernel.dmesg_restrict = 1
```
but with root/privileged that should not be an issue right? (btw, tried to set it to 0 and failed, both inside running container and with `sysctls` inside `docker-compose.yml`

**Comment by KungFuJesus3** [comment]
I found out that using `docker run` with `--privileged` solves the issue.
But why if I already do have container not created with `--privileged` (AFAIK correct way to do it) I have no access to `dmesg`?

Should it be this way? (I'm completely new to docker & hope this topic makes some sense)
