### ISSUE TITLE
Allow for custom seccomp profiles to be used in privileged containers

### ISSUE THREAD

**Issue by pjbgf** [moby/moby#41321]
**Description**
Allowing privileged containers to be restricted with custom seccomp profiles may provide users a better way to delimit their attack surface.

Currently privileged containers always disable seccomp if the container is privileged, even when a custom profile is defined:
https://github.com/moby/moby/blob/1370072eb7e9772b6a6b125660479cb75943589b/daemon/seccomp_linux.go#L25

This behaviour was observed in the past and hasn't changed since. https://github.com/moby/moby/issues/21984#issuecomment-209734717

This is inconsistent with apparmor, which allows for users to apply custom profiles whilst running privileged containers.
The following PR added support to honour custom AppArmor profiles whilst running privileged containers: https://github.com/moby/moby/pull/31773

**Steps to reproduce the issue:**
Assumes a file "profile.json" containing: `{ "defaultAction": "SCMP_ACT_ERRNO" }`

1.  Run unprivileged container blocking its actions:
```
$ docker run --rm --security-opt seccomp=profile.json alpine /bin/sh -c "touch /dev/shm/test && chmod 777 /dev/shm/test && stat /dev/shm/test"

docker: Error response from daemon: OCI runtime start failed: cannot start a container that has stopped: unknown.
```

2. Run same container as privileged and actions are allowed:
```
$ docker run --rm --privileged --security-opt seccomp=profile.json alpine /bin/sh -c "touch /dev/shm/test && chmod 777 /dev/shm/test && stat /dev/shm/test"

  File: /dev/shm/test
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 5ch/92d Inode: 3           Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-06 23:11:26.000000000
Modify: 2020-08-06 23:11:26.000000000
Change: 2020-08-06 23:11:26.000000000
```

**Alternative Steps to reproduce the issue:**

1. Checking process status of a privileged container shows seccomp is disabled:
```
$ docker run --rm --privileged alpine /bin/sh -c "grep Seccomp /proc/1/status"
Seccomp:        0

$ docker run --rm alpine /bin/sh -c "grep Seccomp /proc/1/status"
Seccomp:        2
```

**Describe the results you received:**
The privileged container runs without being confined by seccomp.

**Describe the results you expected:**
The privileged container to be bound and restricted by the seccomp profile.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by AkihiroSuda** [comment]
This doesn't sound meaningful. Even if you have a strict seccomp profile, a container process can easily escape from the container via procfs and sysfs.

**Comment by thaJeztah** [comment]
Curious; Why are you using `--privileged` if you don't want it to be fully privileged?

**Comment by saschagrunert** [comment]
> This doesn't sound meaningful. Even if you have a strict seccomp profile, a container process can easily escape from the container via procfs and sysfs.

I see you concerns. I still see it as useful addition for the reason of consistency and the use-case of testing. It could be used in combination with a custom AppArmor profile too, for example.

**Comment by thaJeztah** [comment]
At that point, wouldn't it be the same/similar to using `--cap-add=ALL` and setting a custom seccomp/apparmor profile, or are the masked paths the part that's missing if you're not using `--privileged` ?

**Comment by pjbgf** [comment]
@AkihiroSuda the idea was not to use seccomp as the only point of defense, but to rather use it in combination with other security controls.

**Comment by pjbgf** [comment]
@thaJeztah very fair points. This came from the idea of running `kured` in a less privileged way. Oversimplifying it, this application checks for a file in disk and if present reboots the cluster node - after draining its workloads. For both actions it uses nsenter to literally "break out" from the isolation.

However, this PR came from looking at the big picture, in which users have less security controls available to apply against a workload in a  `--privileged` container than they have if they are running as root on the host, which is quite puzzling.

**Comment by pjbgf** [comment]
Just to clarify, when I talked about "less security controls" I was referring to both seccomp and being able to cap drop.

**Comment by thaJeztah** [comment]
> However, this PR came from looking at the big picture, in which users have less security controls available to apply against a workload in a --privileged container than they have if they are running as root on the host, which is quite puzzling.

I'd be more in favour of either refusing to start a container if a combination if `--privileged` and `--security-opt`, `--cap-add` / `--cap-drop` is used (or at least a big warning), or even a big warning if just `--privileged` is used.

The short story is .that running a container with `--privileged` effectively means: _disable all security_. A container with `--privileged` **does not contain**. To get an idea of what that means, try;

```bash
docker run -it --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
```

And look around; yes, anything you run there is effectively directly on the host.

So, instead of allowing `--privileged` to disable all protection, and allowing `--security-opt` to "try" to add back some security, which likely won't work, and would give the _impression_ that the container is somewhat secure, I'd rather have users start from the default (which is mostly secure, but could be more secure if we could drop `NET_ADMIN` as a default), and granularly _add_ permissions they need for their use-case. 

Unfortunately, setting the right permissions is rather complicated, requires an understanding of what effect each option has, which makes it also easy to pick the wrong options (which is what the "entitlements" proposal (https://github.com/moby/moby/issues/32801) was intending to resolve, but that unfortunately didn't get much traction, and is not being worked on currently). The `--privileged` was a bad choice to add as a feature, as it's too easy to shoot oneself in the foot https://twitter.com/thaJeztah/status/1288553891563528192?s=20

**Comment by pjbgf** [comment]
I did like your renaming suggestion, you have :+1:  from me. :)

I completely agree that it is more secure, and more efficient, to go through an allow list approach instead of a deny list one. So in the end I did take your suggestion and reviewed the entire application perm requirements, it turns out similar results could be attained by dropping `--privileged` and keeping only `SYS_BOOT` and `--pid=host`.

As for the `--privileged` docker support, I would probably favour that this feature was actually deprecated, as not allowing users to apply security controls around it makes it even more dangerous than it already is. Effectively, there is no "secure" way of using it, pretty much like running as `root` in a linux kernel from the 90s. Removing `--privileged` would also force users to have to think slightly more what they actually need in terms of caps/perms.

Anyways, I am happy to close the issue. Thank you for your time and your suggestions.

**Comment by thaJeztah** [comment]
> As for the --privileged docker support, I would probably favour that this feature was actually deprecated, as not allowing users to apply security controls around it makes it even more dangerous than it already is. Effectively, there is no "secure" way of using it, pretty much like running as root in a linux kernel from the 90s. Removing --privileged would also force users to have to think slightly more what they actually need in terms of caps/perms.


Fully removing it would likely be difficult. By now, there's too many people relying on the option (legitimate uses for some). Perhaps a configurable option on the daemon to disable it (as default?) could be an option?
