### ISSUE TITLE
issue connecting mysql and flask containers.works well on Mac and windows docker desktop(2002, “Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)” in docker-compose up)

### ISSUE THREAD

**Issue by skiran252** [moby/moby#41325]
**Description**

**Steps to reproduce the issue:**(only on linux)
1.git clone https://github.com/skiran252/AYUSH_APP
2.docker-compose pull
3.docker-compose build
4.docker-compose up -d
**Describe the results you received:**
2002, “Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)” in docker-compose up

**Describe the results you expected:**
connect mysql and flask application

**Additional information you deem important (e.g. issue happens only occasionally):**
i tried containerizing this application on docker works well with windows docker desktop since i wanted to run on linux tried the same but doesnt works causes socket lock issue.also tried connecting containers through networks didnt work too.
**Output of `docker version`:**
latest
```
(paste your output here)
```2002, “Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)” in docker-compose up


**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Linux

**Comment by thaJeztah** [comment]
Are you deploying from the linux machine itself, or is your docker cli connected to a remote Linux machine (or a Linux VM)? I see the compose-file uses bind-mounts, which are always mounted from the host on which the daemon is running (Docker Desktop does some special setup to make paths on your Mac / Windows machine accessible to the Docker VM, but the same is not in place on Linux if you're connecting remotely).

Is the MySQL container actually listening on a socket? I see the Compose file publishing port 3306;

https://github.com/skiran252/AYUSH_APP/blob/e3e0d0f7e28bde88d22a0afb8bdddccf5e47d664/docker-compose.yml#L15-L16

```yaml
    ports:
      - 33036:3306
```

Which could indicate it's listening on a HTTP port, and not on a socket.

**Warning** I want to leave a warning here that the above (`33036:3306`) means that the MySQL container is publicly accessible on port `33036`; if you're deploying that stack on a docker host that is publicly accessible (from the internet, or a local network), that means that anyone that can connect to that machine will be able to access your database. If you don't need your database to be accessible (other than by other services in the compose file), I highly recommend removing that from the compose-file; other services should be able to connect to the mysql server over the internal container-container network.

**Comment by skiran252** [comment]
> Are you deploying from the linux machine itself, or is your docker cli connected to a remote Linux machine (or a Linux VM)? I see the compose-file uses bind-mounts, which are always mounted from the host on which the daemon is running (Docker Desktop does some special setup to make paths on your Mac / Windows machine accessible to the Docker VM, but the same is not in place on Linux if you're connecting remotely).
> 
> Is the MySQL container actually listening on a socket? I see the Compose file publishing port 3306;
> 
> https://github.com/skiran252/AYUSH_APP/blob/e3e0d0f7e28bde88d22a0afb8bdddccf5e47d664/docker-compose.yml#L15-L16
> 
> ```yaml
>     ports:
>       - 33036:3306
> ```
> 
> Which could indicate it's listening on a HTTP port, and not on a socket.
> 
> **Warning** I want to leave a warning here that the above (`33036:3306`) means that the MySQL container is publicly accessible on port `33036`; if you're deploying that stack on a docker host that is publicly accessible (from the internet, or a local network), that means that anyone that can connect to that machine will be able to access your database. If you don't need your database to be accessible (other than by other services in the compose file), I highly recommend removing that from the compose-file; other services should be able to connect to the mysql server over the internal container-container network.

i was just testing if connected to mysql i would not publish to port in future.so it works on windows how to make it accessible in linux host machine as i a linux cloud instance so i want to deploy there.since this doesnt work what could be the other way

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  If you encounter this issue on a current engine release, please open a new issue.
