### ISSUE TITLE
Requests with sufficiently big headers hang on hybrid swarm cluster

### ISSUE THREAD

**Issue by riccaa** [moby/moby#41332]
## Synopsis
On a hybrid swarm cluster (1 Ubuntu node and 1 Windows Server node) on Azure, when making an http request from a linux container (on linux node) to a windows container (on a windows node) all seems to be working fine with small size requests, but calls systematically stop working with sufficiently big headers.<br/>Issue possibly related to the following: [https://github.com/moby/moby/issues/41051](https://github.com/moby/moby/issues/41051)

<hr/>

### VM #1 (Windows)
- **Base image** : Windows Server 2019 Datacenter with containers
- **Name** : test-w-001
- **Size** : D2s v3 (https://docs.microsoft.com/en-us/azure/virtual-machines/acu)
- **NIC Private IP** : 10.1.0.13
- **Azure VM Networking, inbound port rules** : Allow for any Port, any Protocol, any Source, any Destination
- **Azure VM Networking, outbound port rules** : Allow for any Port, any Protocol, any Source, any Destination
- **Windows update and then reboot**
- **Windows Defender Firewall** : Disabled for Domain Profile, Private Profile, Public Profile ... And then reboot

Output of "docker version":

	Client: Docker Engine - Enterprise
	 Version:           19.03.5
	 API version:       1.40
	 Go version:        go1.12.12
	 Git commit:        2ee0c57608
	 Built:             11/13/2019 08:00:16
	 OS/Arch:           windows/amd64
	 Experimental:      false

	Server: Docker Engine - Enterprise
	 Engine:
	  Version:          19.03.5
	  API version:      1.40 (minimum version 1.24)
	  Go version:       go1.12.12
	  Git commit:       2ee0c57608
	  Built:            11/13/2019 07:58:51
	  OS/Arch:          windows/amd64
	  Experimental:     false

Output of "docker info":

	Client:
	 Debug Mode: false
	 Plugins:
	  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

	Server:
	 Containers: 0
	  Running: 0
	  Paused: 0
	  Stopped: 0
	 Images: 3
	 Server Version: 19.03.5
	 Storage Driver: windowsfilter
	  Windows:
	 Logging Driver: json-file
	 Plugins:
	  Volume: local
	  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
	  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
	 Swarm: inactive
	 Default Isolation: process
	 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
	 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1369)
	 OSType: windows
	 Architecture: x86_64
	 CPUs: 2
	 Total Memory: 8GiB
	 Name: test-w-001
	 ID: IMUI:CELM:ENKE:SJOT:KM5S:OZKW:KCSE:VJM2:CBM5:HBBZ:5RHW:2M46
	 Docker Root Dir: C:\ProgramData\docker
	 Debug Mode: false
	 Registry: https://index.docker.io/v1/
	 Labels:
	 Experimental: false
	 Insecure Registries:
	  127.0.0.0/8
	 Live Restore Enabled: false

<hr/>

### VM #2 (Ubuntu)
- **Base image** : Ubuntu Server 18.04 LTS
- **Name** : test-l-001
- **Size** : D2s v3 (https://docs.microsoft.com/en-us/azure/virtual-machines/acu)
- **NIC Private IP** : 10.1.0.14
- **Azure VM Networking, inbound port rules** : Allow for any Port, any Protocol, any Source, any Destination 
- **Azure VM Networking, outbound port rules** : Allow for any Port, any Protocol, any Source, any Destination 
- **System upgraded, updated etc. and then reboot**
- **Docker installed, "hello-world:latest" ok, reboot**
- **System upgraded, updated etc. and then reboot**

Output of "docker version":

	Client: Docker Engine - Community
	 Version:           19.03.12
	 API version:       1.40
	 Go version:        go1.13.10
	 Git commit:        48a66213fe
	 Built:             Mon Jun 22 15:45:36 2020
	 OS/Arch:           linux/amd64
	 Experimental:      false

	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.12
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.13.10
	  Git commit:       48a66213fe
	  Built:            Mon Jun 22 15:44:07 2020
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          1.2.13
	  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
	 runc:
	  Version:          1.0.0-rc10
	  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683
  
Output of "docker info":  

	Client:
	 Debug Mode: false

	Server:
	 Containers: 0
	  Running: 0
	  Paused: 0
	  Stopped: 0
	 Images: 1
	 Server Version: 19.03.12
	 Storage Driver: overlay2
	  Backing Filesystem: extfs
	  Supports d_type: true
	  Native Overlay Diff: false
	 Logging Driver: json-file
	 Cgroup Driver: cgroupfs
	 Plugins:
	  Volume: local
	  Network: bridge host ipvlan macvlan null overlay
	  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
	 Swarm: inactive
	 Runtimes: runc
	 Default Runtime: runc
	 Init Binary: docker-init
	 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
	 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
	 init version: fec3683
	 Security Options:
	  apparmor
	  seccomp
	   Profile: default
	 Kernel Version: 5.3.0-1034-azure
	 Operating System: Ubuntu 18.04.5 LTS
	 OSType: linux
	 Architecture: x86_64
	 CPUs: 2
	 Total Memory: 7.749GiB
	 Name: test-l-001
	 ID: 55PM:NZ2D:OVTG:4RIK:3TPN:ZP3B:NGZB:AGM6:XRSS:S2XX:AKQH:OTYT
	 Docker Root Dir: /var/lib/docker
	 Debug Mode: false
	 Registry: https://index.docker.io/v1/
	 Labels:
	 Experimental: false
	 Insecure Registries:
	  127.0.0.0/8
	 Live Restore Enabled: false

	WARNING: No swap limit support
	
<hr/>

### That said:

1. **VM #2 (Ubuntu)**<br/>Execute the following command:<br/>
	
    	sudo docker swarm init --advertise-addr 10.1.0.14:2377
	
    This should be the result:        

		Swarm initialized: current node ([REDACTED]) is now a manager.

		To add a worker to this swarm, run the following command:

			docker swarm join --token [REDACTED] 10.1.0.14:2377

		To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

1. **VM #1 (Windows)**<br/>Execute the following command:<br/>

		docker swarm join --token [REDACTED] 10.1.0.14:2377
	
    This should be the result:
    
		This node joined a swarm as a worker.
		
1. **VM #2 (Ubuntu)**<br/>Execute the following command:<br/>

		sudo docker node ls
	This should be the result:
    
		ID             HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
		[REDACTED] *   test-l-001          Ready               Active              Leader              19.03.12
		[REDACTED]     test-w-001          Ready               Active                                  19.03.5

1. **VM #2 (Ubuntu)**<br/>Execute the following command:<br/>
		
        sudo docker pull curlimages/curl:latest

1. **VM #1 (Windows)**<br/>Execute the following command:<br/>

		docker pull mcr.microsoft.com/windows/servercore/iis

1. **VM #2 (Ubuntu)**<br/>Create the following docker-compose, lets call it "**docker-compose-test.yml**":

		version: "3"
		services:
		  curlc:
			image: curlimages/curl:latest
			command: tail -f /dev/null
			deploy:
			  mode: replicated
			  replicas: 1
			  placement:
				constraints:
				  - node.platform.os == linux
		  iisc:
			image: mcr.microsoft.com/windows/servercore/iis
			deploy:
			  mode: replicated
			  replicas: 1
			  placement:
				constraints:
				  - node.platform.os == windows

	... and then launch it:
    		
            docker stack deploy --compose-file docker-compose-test.yml test
            
	Check that the service is up:
    
    	sudo docker container ls

    This should be the result:
        
		CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
		55dee8bf697b        curlimages/curl:latest   "/entrypoint.sh tail…"   22 seconds ago      Up 21 seconds                           test_curlc.1.wtd82bk3nysly017fvp56mghy

1. **VM #1 (Windows)** : check that the service is up : docker container ls	

		CONTAINER ID        IMAGE                                             COMMAND                   CREATED             STATUS              PORTS               NAMES
		39c34be1aae7        mcr.microsoft.com/windows/servercore/iis:latest   "C:\\ServiceMonitor.e…"   2 minutes ago       Up 2 minutes                            test_iisc.1.lq7hio5vgvwhcfwn1ojd8xj0l
		
1. **VM #2 (Ubuntu)**<br/>Execute the following command, **keep in mind that the number of "a" is a very strict constraint**:

        docker exec <curlc CONTAINER ID> curl -H "a:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" http://iisc

	This should be the result:

		  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
										 Dload  Upload   Total   Spent    Left  Speed
		100   703  100   703    0     0   3739      0 --:--:-- --:--:-- --:--:--  3739
		<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
		<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>IIS Windows Server</title>
		<style type="text/css">
		
		</style>
		</head>
		<body>
		<div id="container">
		<a href="http://go.microsoft.com/fwlink/?linkid=66138&amp;clcid=0x409"><img src="iisstart.png" alt="IIS" width="960" height="600" /></a>
		</div>
		</body>
		</html>

	That said, when adding a sufficient amount of characters to the header, the call hangs:	

		  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
										 Dload  Upload   Total   Spent    Left  Speed
		  0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0
		curl: (56) Recv failure: Connection reset by peer

**Comment by thaJeztah** [comment]
The length of your header value is 1255 characters (1255*8=10040 bytes, assuming 8-bit).

Could this be a RequestLimit on the IIS server? https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/ does the IIS-container receive the request? Anything in the logs for that container?

**Comment by riccaa** [comment]
The IIS values are the following:  

	{[maxAllowedContentLength, 30000000], [maxUrl, 4096], [maxQueryString, 2048]}

From the Windows machine I've used the command...  

	docker exec <curlc CONTAINER ID> curl -H "a:aaa[...]" [http://iisc](http://iisc/)

... With many more "a", but all was fine, that is: IIS work as expected.

From Ubuntu, I execute the "usual" command with too many "a":  

	docker exec <curlc CONTAINER ID> curl -H "a:aaa[...]" [http://iisc](http://iisc/)

On Windows, using  **netstat**, this is the result:  

	TCP    10.1.0.13:51416        [REDACTED]:http     ESTABLISHED

After a while (minutes, not seconds) the  **netstat**'s result is always the same.

**Comment by riccaa** [comment]
I have found the culprit and the workaround.

**Culprit**: mr. MTU

**Workaround**: see [here](https://github.com/moby/moby/issues/33596) and [here](https://mlohr.com/docker-mtu/).

That is...

**1. VM #1 (Windows)**:
In **C:\ProgramData\docker\config** create the "**daemon.json**" file, if it is not present, and add `"mtu": 1450`.
If the file was empty the result should be something like this:
```
{
   "mtu": 1450
}
```
Restart the Docker service.

**2. VM #2 (Ubuntu)**:
Change the "**docker-compose-test.yml**":
```
version: "3"

services:

  curlc:
    image: curlimages/curl:latest
    command: tail -f /dev/null
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
    networks:
      test-network: null  
    
  iisc:
    image: mcr.microsoft.com/windows/servercore/iis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == windows
    networks:
      test-network: null    

networks:
  test-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1400
```
Remove the old stack - if still present - and create a new one.

**2. VM #2 (Ubuntu)**:
Execute the following comand:
`sudo docker exec <curlc_CONTAINER_ID> curl -H "a:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" http://iisc`
The header is three times bigger than the header used in the **step nr. 8** but nonetheless the result is as expected:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>IIS Windows Server</title>
<style type="text/css">
<!--
body {
        color:#000000;
        background-color:#0072C6;
        margin:0;
}

#container {
        margin-left:auto;
        margin-right:auto;
        text-align:center;
        }

a img {
        border:none;
}

-->
</style>
</head>
<body>
<div id="container">
<a href="http://go.microsoft.com/fwlink/?linkid=66138&amp;clcid=0x409"><img src="iisstart.png" alt="IIS" width="960" height="600" /></a>
</div>
</body>
100   703  100   703    0     0   3429      0 --:--:-- --:--:-- --:--:--  3429
```
I've checked the issue using an hybrid swarm in...

- AWS
- Azure
- Google Cloud

... Without errors.
