### ISSUE TITLE
Please rewrite Docker in C

### ISSUE THREAD

**Issue by docker-user-2020** [moby/moby#41347]
**Description**

I'm trying to build Docker for ARM64 Windows but I'm getting a strange error:

![image](https://user-images.githubusercontent.com/69434105/90072000-4c1d9600-dcff-11ea-9643-ceda0566626d.png)
Cool ASCII art though.

Even building for ARM32 Windows fails:

![image](https://user-images.githubusercontent.com/69434105/90072290-dfef6200-dcff-11ea-800f-f1cdbf3e8a7e.png)

That might be realetd to the fact that Windows/ARM32 is pretty useless and [Go doesn't even attempt to support it for quite some time](https://github.com/golang/go/issues/38607).

Even if I fix it to build for ARM32 that pointless since there's no ARM32 version of `vmcomputer.dll` etc. on ARM64 Windows 10. HCS isn't really accessible from "ARMWOW64".

On the other hand, we've got _at least_ two commercial-grade C/C++ compilers for Windows/ARM64 and for many other platforms.

I know it's so very cool to be a 10xer who uses all the shiny crap from Google and the Commander, but it makes Docker a lot less usable than if it had been written in a language that has seen real world adoption based on its merits and is really cross-platform.

While we're waiting for Go to finally support Windows/ARM64, perhaps you'd consider migrating Docker to a useful language?

By the time Go supports Windows/ARM64 we'll want Docker for another platform it won't support, that probably already has C compilers supporting it.

**Steps to reproduce the issue:**
1. Do the steps documented in `Dockerfile.windows` but add `GOOS=windows` and `GOARCH=arm64`

**Describe the results you received:**
Build failure.

**Describe the results you expected:**
Windows/ARM64 `dockerd.exe` and `docker.exe` binaries.

**Comment by thaJeztah** [comment]
We considered Fortran, but decided to use Go after heavy discussion

It's open source though, so contributions welcome (don't Forget Kubernetes, which may also need a rewrite)

Closing this issue for now, because there's no plans currently to rewrite, but feel free to continue the conversation

**Comment by thaJeztah** [comment]
Seriously though, rewriting in C is not a realistic option at this point (and would be a massive amount of work, with unclear benefits).

As to the build error in `moby/term`, I think that may get resolved by https://github.com/moby/term/pull/14. Native Windows container support on Windows / arm, will require support from Microsoft (large parts of container support on Windows is using internal functionality of the Windows platform). If your interest is in running Linux containers, not native Windows containers, then WSL2 might be a more realistic option (I _think_ WSL2 may be supported on windows/arm ?), in which case the Linux builds could run.
