### ISSUE TITLE
Remount on subpath bind mount succeeds but sets whole subtree as readonly

### ISSUE THREAD

**Issue by venkatsc** [moby/moby#41363]
**Description**
Remounting inside docker container succeeds for FUSE and makes the whole subtree as readonly. Only happening with FUSE, with normal filesystems remounting fails with "target is busy".  

**Steps to reproduce the issue:**
1. Mount some FUSE file system `/mnt/source` from host into container with `rshared` and `rw` mode
2. Mount target path `/mnt/target/` from host into host into container with `rshared` and `rw` mode
3. Start container as privileged
4. Bind mount subpath `/mnt/source/a` to `/mnt/target/b`
5. Remount with `mount -o remount,ro,bind /mnt/target/b`
6. Check `/mnt/source` permissions on host (/mnt/source  permissions are changed to `ro`)

**Describe the results you received:**
Whole subtree became read-only instead of the subpath

**Describe the results you expected:**
Either remount fails with the error or if it succeeds setting only subpath to read-only but not the entire subtree

**Additional information you deem important (e.g. issue happens only occasionally):**
Happened only with FUSE client. Normal file system, fails with "target busy". Looking at the https://github.com/moby/moby/issues/31591, it seems remount is not supported inside docker container. Hence, we expect the remount in `step 5` to fail. 

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 32
  Paused: 0
  Stopped: 1
 Images: 31
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.12.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.544GiB
 Name: k8s-1
 ID: 7BL2:6PHM:GUBC:OQ27:S2KR:HVT3:635V:5PCI:2U3I:OF6S:VSK2:AL4S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):* VirtualBox*

**Comment by cpuguy83** [comment]
This sounds more like a fuse issue.
The issue you mentioned does not seem to be related, which was asking for Docker to have a way to add mounts.

Docker is only involved in bind mounting the paths you requested to the container fs. There is nothing special about the mounts.

Is the subpath just a simple path or is it a mount itself?

**Comment by venkatsc** [comment]
For kubernetes CSI, we need to do bind mounts inside container. Two paths `/mnt/src/` and `/mnt/target` are mounted into this container with `rshared` mount propagation. Some kubernetes events triggers bind mount `/mnt/src/a` to `/mnt/target/a`. Bind mount works without any issue.

Executing `mount -o remount,ro,bind /mnt/target/a` after the bind mount made whole `/mnt/src` as read-only. Executing `mount -o remount,ro,bind /mnt/src/a /mnt/target/a` inside the same container did not make neither subpath `readonly` nor the whole subtree. The expectation is, if the remount is not allowed inside container then it should throw the error instead of silently ignoring it or remounting whole subtree as readonly.

The above behavior only observed with FUSE file system. Trying same commands inside container with non-FUSE filesystem always resulted in failures.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
