### ISSUE TITLE
One click installation failed

### ISSUE THREAD

**Issue by bbhxwl** [moby/moby#41362]
[root@VM-4-3-centos ~]# yum install -y -q docker-ce
Repository epel is listed more than once in the configuration
Removing docker-ce.x86_64 3:19.03.12-3.el7 - u due to obsoletes from moby-engine.x86_64 0:19.03.12+azure-2 - u
Error: moby-containerd conflicts with containerd.io-1.2.13-3.2.el7.x86_64
Error: moby-runc conflicts with containerd.io-1.2.13-3.2.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by cpuguy83** [comment]
Where are you trying to install this?
Looks like Azure's moby builds are already installed on the system, and they conflict (rightfully so) with docker-ce.

**Comment by bbhxwl** [comment]
What should I do?

**Comment by thaJeztah** [comment]
Looks like docker is already installed, but from the Azure packages.

If you type `docker version` (or `sudo docker version`), does it work?

**Comment by maxima120** [comment]
I just got the same problem on GCP and no `sudo docker version` doesnt work.. CentOS7

**Comment by bbhxwl** [comment]
> I just got the same problem on GCP and no `sudo docker version` doesnt work.. CentOS7

I solved it.

**Comment by bbhxwl** [comment]
> I just got the same problem on GCP and no `sudo docker version` doesnt work.. CentOS7

I'm also centos7. I can't use Alibaba cloud, Tencent cloud or centos7 in any computer room, but I've solved it now.

**Comment by maxima120** [comment]
OK  and would you be so generous and tell how did you fix it?

**Comment by bbhxwl** [comment]
> OK and would you be so generous and tell how did you fix it?
 
sudo yum remove docker  docker-common docker-selinux docker-engine
sudo yum install -y yum-utils device-mapper-persistent-data lvm2

sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

sudo yum  -y install docker-ce --exclude=moby-\*
sudo systemctl start docker

sudo systemctl enable docker

docker version

**Comment by bbhxwl** [comment]
> OK and would you be so generous and tell how did you fix it?

Pay attention to this sentence

Look at this line of code

sudo yum  -y install docker-ce --exclude=moby-\*

**Comment by bbhxwl** [comment]
> OK and would you be so generous and tell how did you fix it?

--exclude=moby-*

**Comment by cpuguy83** [comment]
Closing since there isn't anything actionable on here.
