### ISSUE TITLE
versioning does not work with pkg.go.dev

### ISSUE THREAD

**Issue by jba** [moby/moby#41382]
It is difficult to read Go documentation for the right version on https://pkg.go.dev because versioning is broken in this repo (#39056, golang/go#37851). 

Relatedly, the doc link on https://docs.docker.com/engine/api/sdk points to godoc.org, but someday that will redirect to pkg.go.dev, which will serve an unintended version of the docs.

**Comment by thaJeztah** [comment]
This part should be fixed now, but you still need to add `+incompatible`

Let me close this ticket for now, as it looks like it went stale.
