### ISSUE TITLE
Linux kernel memory leak when run OpenTSDB in docker

### ISSUE THREAD

**Issue by xiegang1** [moby/moby#41384]
When running a Opentsdb test in docker, we hit a kernel memory leak issue. The mem limit of the OpenTSDB docker is 8GB, but after 1 hour,  almost all of the system memory, about 100GB are used. We checked the meminfo, top and slabtop, could not found where the memory is:

```bash
# free -g
              total        used        free      shared  buff/cache   available
Mem:            125         106          15           0           2          15
Swap:             0           0           0

top
top - 09:45:39 up 3 days, 17:26,  2 users,  load average: 1.09, 0.89, 0.82
Tasks: 597 total,   1 running, 596 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.0 us,  0.6 sy,  0.0 ni, 96.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13121584+total, 16477996 free, 11203886+used,  2698980 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 16429076 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

 Active / Total Objects (% used)    : 6291144 / 6867209 (91.6%)
 Active / Total Slabs (% used)      : 129664 / 129664 (100.0%)
 Active / Total Caches (% used)     : 92 / 132 (69.7%)
 Active / Total Size (% used)       : 1999446.39K / 2134431.48K (93.7%)
 Minimum / Average / Maximum Object : 0.01K / 0.31K / 8.00K

  OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME
2909312 2864927  98%    0.25K  45458       64    727328K kmalloc-256
559944 528426  94%    0.19K  13332	 42    106656K dentry
319616 295678  92%    0.06K   4994	 64     19976K kmalloc-64
265200 264741  99%    0.62K   5200	 51    166400K proc_inode_cache
227640 227597  99%    0.07K   4065	 56     16260K Acpi-Operand
220422 220154  99%    0.62K   4322	 51    138304K sock_inode_cache
246720 206281  83%    0.12K   3855	 64     30840K kmalloc-128
200976 200973  99%    1.94K  12561	 16    401952K TCP
```

**Steps to reproduce the issue:**
run OpenTSDB in docker and issue queries

**Describe the results you received:**
memory leak

**Describe the results you expected:**
no memory leak

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:
 Built:             Mon May 13 13:00:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Mon May 13 13:00:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**Output of `docker info`:**

```
Containers: 18
 Running: 17
 Paused: 0
 Stopped: 1
Images: 30
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.2-3.0.0.std7b.el7.5.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.1GiB
Name: xxxxx
ID: E4XY:AR3X:MRI4:ZQUK:D6XN:NG7R:KKYY:JLSF:Z77S:SAYR:RAMU:3HQZ
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 121
 Goroutines: 123
 System Time: 2020-08-25T09:52:12.46632502+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.3.1611 4.9.2-3.0.0

**Comment by thaJeztah** [comment]
Not sure if this is a bug in docker, as it mostly creates the namespaces for the process (OpenTSDB) to run in, but otherwise it's the kernel doing the work. So may be a bug in either OpenTSDB or a kernel issue.

If there's still reasons to look into this;

- Docker 18.09.x reached EOL Are you seeing the same behaviour on a currently maintained version of docker and containerd.io? (19.03.x at time of writing)
- I notice you're running CentOS with a non-standard kernel; this may work, but no testing has done with these combinations. The CentOS packages are built with the expectation to run on the Red Hat kernels, and for those (for example), kmem-cgroups are disabled in the builds to account for bugs in those kernels 
- What options are you using to deploy the OpenTSDB container? Are you using volumes for its data? Without the exact steps to reproduce the issue, it won't be possible to look into the issue (if any).

**Comment by xiegang1** [comment]
reproduced the issue and got a kdump:

**Comment by xiegang1** [comment]
crash> kmem -i
                 PAGES        TOTAL      PERCENTAGE
    TOTAL MEM  32803961     125.1 GB         ----
         FREE  10829493      41.3 GB   33% of TOTAL MEM
         USED  21974468      83.8 GB   66% of TOTAL MEM
       SHARED  5663181      21.6 GB   17% of TOTAL MEM
      BUFFERS     9656      37.7 MB    0% of TOTAL MEM
       CACHED   300470       1.1 GB    0% of TOTAL MEM
         SLAB   335787       1.3 GB    1% of TOTAL MEM

   TOTAL HUGE        0            0         ----
    HUGE FREE        0            0    0% of TOTAL HUGE

   TOTAL SWAP        0            0         ----
    SWAP USED        0            0    0% of TOTAL SWAP
    SWAP FREE        0            0    0% of TOTAL SWAP

 COMMIT LIMIT  16401980      62.6 GB         ----
    COMMITTED  5894185      22.5 GB   35% of TOTAL LIMIT

**Comment by xiegang1** [comment]
the memory usage of the process is far from the used mem of the system:

13970 13949 5 ffff881ff89f8000 IN 0.0 720272 16.1602 MB mi-exporter
14079 14061 5 ffff881013ef0000 IN 0.0 1545716 16.4297 MB linker
10514 1 7 ffff88202c743b80 IN 0.0 1337456 17.4688 MB sagent
2298 1 3 ffff882030241dc0 IN 0.0 553664 20.3477 MB tuned
14162 14144 14 ffff881ff6c58000 IN 0.0 119584 20.9375 MB node_exporter
13923 13904 39 ffff881ffb3e8000 IN 0.0 133364 21.6172 MB k8s-kc-reporter
10553 1 1 ffff882033a8bb80 IN 0.0 1029296 24.4023 MB ruby
11953 1 17 ffff881035795940 IN 0.0 2623068 27.8984 MB falcon-agent
14354 14337 37 ffff881ff5e90000 IN 0.0 1375424 29.125 MB k8s-lvm-gc
12106 1 7 ffff88202fb49dc0 IN 0.0 2374608 30.0078 MB flannel
12644 12637 23 ffff882033488000 IN 0.0 3411004 36.1367 MB containerd
11806 10514 10 ffff881035663b80 IN 0.0 3630872 38.5664 MB sagent
12180 1 37 ffff88203369d940 IN 0.0 145784 55.9531 MB kube-proxy
11938 1 16 ffff881031b2bb80 IN 0.0 1719532 56.9336 MB ruby
12228 1 22 ffff88202fb43b80 IN 0.1 3216252 79.3945 MB dockerd
13998 13981 25 ffff881ff8420000 IN 0.1 209860 98.0977 MB cadvisor
12716 1 37 ffff88202cef8000 IN 0.1 4641164 110.051 MB kubelet
12044 1 39 ffff88202c745940 IN 0.3 12713608 367.984 MB java
14592 14560 12 ffff881ffd7f0000 IN 5.5 10679512 7379.66 MB java
14597 14559 10 ffff881ff02f8000 IN 5.6 10679512 7402.82 MB java

**Comment by xiegang1** [comment]
> Not sure if this is a bug in docker, as it mostly creates the namespaces for the process (OpenTSDB) to run in, but otherwise it's the kernel doing the work. So may be a bug in either OpenTSDB or a kernel issue.
> 
> If there's still reasons to look into this;
> 
> * Docker 18.09.x reached EOL Are you seeing the same behaviour on a currently maintained version of docker and containerd.io? (19.03.x at time of writing)
[xiegang1] not tried yet，we will try it later.
> * I notice you're running CentOS with a non-standard kernel; this may work, but no testing has done with these combinations. The CentOS packages are built with the expectation to run on the Red Hat kernels, and for those (for example), kmem-cgroups are disabled in the builds to account for bugs in those kernels
[xiegang1]we have been running docker in the patched kernel for some years. never hit this before. the kmem accounting is enabled in our env.
> * What options are you using to deploy the OpenTSDB container? Are you using volumes for its data? Without the exact steps to reproduce the issue, it won't be possible to look into the issue (if any).
[xiegang1] I think OpenTSDB is not the key point. It just likes some other java programs using netty. neither hbase nor hdfs is not deployed in docker. OpenTSDB access them remotely without local data access.

I think there could 2 possibility:
1. there are some mem accounting problem. the kmem is not account to the process, so cgroup not working.
2. some driver or kernel components have memory leak. since in some kernel shared code path, it will not do the accounting by default, such as net if ring buffer, etc.

**Comment by xiegang1** [comment]
It seems that the root cause is that we doesn't enable the tcpmem of the cgroup. OpenTSDB is started without the limitation of the incoming request. It creates more than 10,000 sockets and each socket has some sk_buffs in the receive/write queue. Those memory is not accounted to the OpenTSDB process. 

crash> tcp_prot
..
  memory_allocated = 0xffffffff821ec8e8 <tcp_memory_allocated>,
crash> rd 0xffffffff821ec8e8
ffffffff821ec8e8:  0000000000a17368                    hs......

crash> memcg_sockets_enabled_key
memcg_sockets_enabled_key = $2 = {
  key = {
    enabled = {
      counter = 0
    },
    entries = 0xffffffff81d528e8,
    next = 0x0
  }
}

Tcpmem of the cgroup is disabled by default. I searched the information related to it but found no detailed experiences about it. Not sure the side effect.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  If you encounter this issue on a current engine release, please open a new issue.
