### ISSUE TITLE
Placement preferences gives too much weight to non-preferred nodes

### ISSUE THREAD

**Issue by sbrattla** [moby/moby#41399]
I'm running a 5 node swarm cluster. None of the services running in that cluster has any placement preferences, placement constraints or resource limits set.

The swarm cluster is spread across 3 data centers. One of the data centers participating in the cluster has a somewhat slower link than the two others. I therefore decided to add a placement preference to one service which is particularly sensitive to latency. 

The layout of the cluster is :

DC1: **swarm-01**
DC2: **swarm-02**, **swarm-04**, **swarm-05**
DC3: **swarm-03** (slow link)

I added a `primarynode` label to nodes in DC1 and DC2 :

**swarm-01**: `primarynode=a`
**swarm-02**: `primarynode=b`
**swarm-04**: `primarynode=c`
**swarm-05**: `primarynode=d`

The label was not applied to **swarm-03**.

I then added a placement preference to before mentioned service to spread tasks based on the `primarynode` label.

To my surprise, it appears that tasks for the service are scheduled just as often on the **swarm-03** node as on any of the other nodes - even though **swarm-03** node has no `primarynode` label. This happened even if one of the other nodes with the `primarynode` label set had no other tasks running. In other words, it appeared as if the placement preference had no impact.

Looking at #35433 , it appears that nodes without a given label will still have that label implicitly set. In this case, the node **swarm-03** would have the label `primarynode` set - but with the value `null`.

> Note that nodes which are missing the label used to spread, will still receive task assignments. As a group, they will receive tasks in equal proportion to any of the other groups identified by a specific label value. In a sense, a missing label is the same as having the label with a null value attached to it. 

I understand that the placement preference is only a preference. However, I would expect nodes with the label explicitly set to receive higher weight during task scheduling. 

It makes sense if a task with a placement preference is scheduled on a node without a label if all other nodes are either congested or unavailable. However, in this case that was not the case. 

Would it not be fair to say that nodes with a label explicitly set should receive higher weight than nodes without a label set?

**Comment by olljanat** [comment]
@sbrattla probably that way it would be smarter.

Unfortunately based on what I have studied swarm code there is no logic like that so I highly recommend that you use --constraint setting for avoid services scheduled to DC3.

**Comment by sbrattla** [comment]
@olljanat I was hoping that this issue would be regarded as a feature request, and not a support request.

**Comment by olljanat** [comment]
Derek add labea: area/swarm

**Comment by olljanat** [comment]
@sbrattla on that case might want to look https://github.com/docker/swarmkit/issues/2665

**Comment by sbrattla** [comment]
@olljanat that's a long thread which seems to be concerned with a road map, the future of swarm and minor comments on long awaited features. Are you thinking of anything in particular from that thread in the context of this issue?

I may be missing something, but I can't see anything in particular which relates to this feature request?

**Comment by olljanat** [comment]
@sbrattla my point was that (unfortunately) there is no roadmap or any active development for new features to swarm.

So if this feature is important for you then you should consider to implement your self and still (unfortunately) be prepared wait 6-18 months that version which contains it gets released.

This based on about 5 years experience when I followed this project and when I even have implement some features myself.

PS. Don't get me wrong. I really love swarm and would prefer to use it instead of Kubernetes but it starting to look more and more clear that some point of time we are forced to switch...

**Comment by sbrattla** [comment]
I see @olljanat - I thought you were referring to a certain issue.

I was not aware that Docker Swarm is now in the hands of a company which makes a living out of selling hosted K8s. Is it about time to jump ship?

**Comment by olljanat** [comment]
@sbrattla it really depends on use case.

IMO, K8s is very complex tool which why swarm can be much better option on companies who are just getting started with containers and/or are planning to migrate workloads from virtual machines to containers. Just use docker stack for deployments so you can easily convert those to K8s format using https://kompose.io on future.

But in case of new applications development it can be smarter to go directly with some managed K8s service.

**Comment by sbrattla** [comment]
@olljanat yes, agreed. I'd much rather stay with swarm. Overall, it's brilliant and works great - and very very simple to get started with.The swarm setups I usually manage are small (20 - 50 containers), and by far covers the needs I have in terms of container orchestration. However, It'd just be sad to find oneself heading down a dead alley.

**Comment by olljanat** [comment]
@sbrattla I think that is somewhere around 10 000 containers when K8s starting to make sense.

Anyway, this starting to be so offtopic that it is better to stop discussing here. You can find me from Docker community Slack if want discuss more.

**Comment by sbrattla** [comment]
@olljanat yes, agreed. By the way, I'm uncertain if this is the best place to request swarm features. Would the best place be here, or should I create an issue on the docker/swarmkit repository?

**Comment by thaJeztah** [comment]
@dperny ptal

**Comment by dperny** [comment]
I understand what you're asking for, but what do you think would be solved by a change to the behavior of placement preferences that would not be solved by simply putting a node constraint to keep tasks off of swarm-3?

**Comment by sbrattla** [comment]
To keep service off of DC3, a placement constraint would ensure that nodes in DC3 would never run those services. You could probably also argue that, with 3 managers, if DC1 and DC2 goes down then nothing will or can be scheduled anyway since DC3 at that point is a single-node broken swarm.

We run a few services that would be very preferable to run in DC1 only (but "fallback" to DC2 or DC3 if DC1 goes down). This has to do with applications which are latency sensitive and have dependencies on other services which have their primary / active nodes in DC1. 

- I can do this using placement constraints. But if DC1 goes down, the service goes down. So I trade away high availability for speed.
- I can do this using placement preferences. But with 2 replicas of the service, It's very likely that the service will also end up in the slow DC3 (the two DCs which don't satisfy the placement preference (a label) will have that label implicitly set with an empty value / null value). This time I trade away speed for high availability.

The way I see it; to overcome this a "hard" placement preference could help. So if there are nodes which satisfy a placement preference, then those nodes would be picked. Otherwise, if no nodes satisfy the placement preference the scheduler will just ignore that placement preference.

**Comment by olljanat** [comment]
@sbrattla btw. We have very similar setup which we solved by having manager nodes on all three DCs but worker nodes on those two primary ones. Then you just need make sure that there is enough resources available on those workers if you loose one DC. Either by increasing resources on thise or having totally four workers (two on DC 1 and two on DC 2). 

Another simple solution would be add example "do-not-schedule" label to DC 3 node(s) and setup script running on there which monitors DC1+DC2 and if both of those are not up then it removes that label but we haven't seen any point to do that.

**Comment by sbrattla** [comment]
If anyone should find this issue, and somehow find themselves facing a similar situation, then you may find the small piece of software i wrote to solve this of interest.

The application will watch the (collective) availability of one or more nodes, and when the watched nodes become unavailable disable labels on specified nodes. 

This means that swarm-03 can watch swarm-02, swarm-04 and swarm-05. If all the watched nodes becomes unavailable, the application may disable a label on swarm-03 which then will allow the previously constrained service to also be scheduled on swarm-03. 

You can read more about this on the repository page.

https://github.com/sbrattla/swarmconstraint
