### ISSUE TITLE
[Katacoda] Docker Rootless installation warnings/fail following a tutorial on how to install it

### ISSUE THREAD

**Issue by FelixBenning** [moby/moby#41396]
**Description**

systemd is not recognized. There seems to be some relation to the login method [see stack exchange question & answer](https://unix.stackexchange.com/questions/587674/systemd-not-detected-dockerd-daemon-needs-to-be-started-manually)

**Steps to reproduce the issue:**
1. Open [Docker Rootless Tutorial on Katacoda](https://www.katacoda.com/courses/docker/rootless)
2. Execute every command in the turorial

**Describe the results you received:**

receive the warnings 
```
systemd is not detected, dockerd daemon needs to be started manually
...
#WARN: systemd not found. You have to remove XDG_RUNTIME_DIR manually on every logout
``` 
and watch the first command in step 3 fail with
![image](https://user-images.githubusercontent.com/29106652/91537131-17702800-e916-11ea-9454-aa7eaa9d7eec.png)

**Describe the results you expected:**
A tutorial [suggested by the maintainer of the project](https://youtu.be/Qq78zfXUq18?t=659) should work. Especially since it is identical to the tutorial on https://docs.docker.com/engine/security/rootless/ which also results in these warnings on my machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

![image](https://user-images.githubusercontent.com/29106652/91537740-14296c00-e917-11ea-8559-128c79e19036.png)

**Output of `docker info`:**
![image](https://user-images.githubusercontent.com/29106652/91537683-fd831500-e916-11ea-80f4-e77ba371dbae.png)

I barely even understand what systemd does. So I really have no idea what is happening. If you have suggestions how to get this working it would be greatly appreciated.

**Comment by thaJeztah** [comment]
So, this is when connecting using an ssh session, then switching user accounts to the non privileged user?

Saw some answers here for similar issues; https://unix.stackexchange.com/a/188877

@AkihiroSuda perhaps you have some ideas?

**Comment by AkihiroSuda** [comment]
Katacoda should use machinectl for switching the user, not su.

Also Katacoda uses a wrong (old) xdg dir in their tutorial.


Please ask Katacoda to update their tutorial.

**Comment by FelixBenning** [comment]
So if I understand this correctly, a `su` command does not actually cause a log in, so that is why some things can not be accessed. I would have thought that `su -l ` would have worked then, but that does not appear to be the case either.

```
~$ curl -sSL https://get.docker.com/rootless | sh
# Installing stable version 19.03.12
# Existing rootless Docker detected at /data/home_prod/lowpriv_docker/bin/dockerd
# systemd not detected, dockerd daemon needs to be started manually

/data/home_prod/lowpriv_docker/bin/dockerd-rootless.sh --experimental --storage-driver vfs

# Docker binaries are installed in /data/home_prod/lowpriv_docker/bin
# Make sure the following environment variables are set (or add them to ~/.bashrc):

# WARN: systemd not found. You have to remove XDG_RUNTIME_DIR manually on every logout.
export XDG_RUNTIME_DIR=/data/home_prod/lowpriv_docker/.docker/run
export DOCKER_HOST=unix:///data/home_prod/lowpriv_docker/.docker/run/docker.sock
```

Other stuff which is confusing in this message:
- `--storage-driver vfs` (this is a ubuntu 16 server, is there a version requirement for overlay2?)
- the export suggestions are different from the suggestions in the [installation guide](https://docs.docker.com/engine/security/rootless/#install), in particular the guide states
  - `export DOCKER_HOST=unix:///run/user/1001/docker.sock` in contrast to
  - `export DOCKER_HOST=unix:///data/home_prod/lowpriv_docker/.docker/run/docker.sock`

Now if I ssh into `lowpriv_docker` directly (to avoid the su issue), I can try this
```
$ systemctl --user start docker
$ systemctl --user status docker
● docker.service - Docker Application Container Engine (Rootless)
   Loaded: loaded (/data/home_prod/lowpriv_docker/.config/systemd/user/docker.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Fri 2020-08-28 11:33:30 CEST; 2s ago
     Docs: https://docs.docker.com
  Process: 22169 ExecStart=/data/home_prod/lowpriv_docker/bin/dockerd-rootless.sh --experimental --storage-driver=overlay2 (code=exited, status=1/FAILURE)
 Main PID: 22169 (code=exited, status=1/FAILURE)
```

which seems to attempt using `overlay2` while the message suggests using vfs. Using vfs I can get it to run with the last info

```shell
INFO[2020-08-28T12:37:11.947839957+02:00] API listen on /run/user/46294/docker.sock 
```

which seems to match the tutorial instead of the installation message. But if I try

```shell
$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

it tries to connect to yet another `docker.sock` which does not even exist. I realized this is due to the fact that

```
$ export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
-sh: 4: Cannot: not found
```` 

which makes no sense to me at all. But if I substitute it with a hardcoded id it seems to work at least.

**Comment by FelixBenning** [comment]
I think I got it to run. Well I got `docker ps` to run. My current issue is this:

```
$ docker pull python
Using default tag: latest
latest: Pulling from library/python
d6ff36c9ec48: Extracting [==================================================>]   50.4MB/50.4MB
c958d65b3090: Download complete
edaf0a6b092f: Download complete
80931cf68816: Download complete
bc1b8aca3825: Download complete
edfe96a4dd20: Download complete
4e7c0e94bdeb: Download complete
8dffdfc294e3: Download complete
036c588c629e: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /etc/gshadow: operation not permitted
```

I think I should open a different issue for this?

**Comment by AkihiroSuda** [comment]
Yes, please, with full reproducer.
(Couldn't repro on katacoda)

**Comment by AkihiroSuda** [comment]
Sent an email to Katacoda support to update their tutorial.

**Comment by FelixBenning** [comment]
> Yes, please, with full reproducer.
> (Couldn't repro on katacoda)

I would like to, but I am not sure if I can provide a full reproduction. I installed this on a existing ubuntu server no one is currently using. I do not have physical access so completely reinstalling ubuntu is going to be... difficult. So I can only really guess what might be different to a normal installation. I guess one unique thing is, that the home directory is on a shared "data" mount with another server.

I thought that it might be easer to reproduce it, if I could do it inside an ubuntu container. But I ran into different issues trying to install docker rootless inside an ubuntu container. So I could not even install it in the first place. I would guess that this is why dind container exist.

Should I open a ticket anyway?

**Comment by AkihiroSuda** [comment]
Please open when you can repro

**Comment by AkihiroSuda** [comment]
Closing, as this is an issue of Katacoda side.

**Comment by AkihiroSuda** [comment]
Katacoda.com is shutting down

https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html
