### ISSUE TITLE
docker swarm does not support '--cap-add' and '--cap-drop'

### ISSUE THREAD

**Issue by tianshr123** [moby/moby#41408]
To date, docker swarm does not support the `--cap-add` and `--cap-drop` options, Is there any other way I can delete the default  capabilities provided by docker?

**Comment by cpuguy83** [comment]
There is not.
This will be in the next major release.

Last PR that needs to be merged is here: https://github.com/docker/cli/pull/2687
Expecting to have a beta release cut soon.

Thanks!

Closing since there's nothing really to be done, but feel free to discuss!
