### ISSUE TITLE
[discuss] move pkg/locker to a standalone repository

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#41422]
Just opening this for discussion, following https://twitter.com/ibuildthecloud/status/1303204483757875206?s=20

The pkg/locker package is a small package and, looking at git history, has low maintenance (last changes were made 3 years ago). Similar to (e.g.) the https://github.com/moby/sys and https://github.com/moby/term packages, we can consider moving the package to its own repository, to allow easier consumption of the package without having to pull in the whole docker repository and/or dealing with the CalVer versioning issues (which doesn't work well with Go modules).

/cc @ibuildthecloud @seemethere @cpuguy83 @kolyshkin

**Comment by thaJeztah** [comment]
FWIW, @seemethere already created a repository https://github.com/seemethere/locker/tree/v1.0.0 (we could consider moving that under the moby org)

**Comment by cpuguy83** [comment]
I despise the name of it (which when I created the package I hoped someone would suggest something different 😄 ), but otherwise 🤷

**Comment by thaJeztah** [comment]
We can name it "houdini" 😂
