### ISSUE TITLE
Docker inspect hangs when nfs server down

### ISSUE THREAD

**Issue by lyyao09** [moby/moby#41427]
**Description**
When the nfs server and nfs client pod stops working for some reason, then nfs client recreate with **Created** status. If we use `docker inspect` command to enter this created container, it will get stuck.
Similar issue https://github.com/docker/for-linux/issues/397 but without nfs server.
```
[root@node1 k8s-resources]# docker ps -a |grep deployment-nfs-pv
8959a5874b1d        c96b32b467f1       "/bin/sh -c 'sed -i …"   2 minutes ago       Created       k8s_2048-a_deployment-nfs-pv-64ffbff7fc-zdvb5_default_db71ca21-e1fd-4cd4-89f2-f8cd4dad5beb_1
39843832f267        matrix/pause:3.1   "/pause"                 3 minutes ago       Up 3 minutes  k8s_POD deployment-nfs-pv-64ffbff7fc-zdvb5_default_db71ca21-e1fd-4cd4-89f2-f8cd4dad5beb_0
[root@node1 k8s-resources]#
[root@node1 k8s-resources]# docker inspect 8959a5874b1d
its stuck...
```

**Steps to reproduce the issue:**
1. install k8s
2. deploy nfs server and client
3. stop nfs server and client container
4. docker inspect to client container

**Describe the results you received:**
docker inspect get stuck

**Describe the results you expected:**
docker inspect won't get stuck

**Additional information you deem important (e.g. issue happens only occasionally):**

We test latest docker version, the problem still exists.

**Output of `docker version`:**

```
[root@node14 runc-code]# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
[root@node2 ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
runc version: N/A
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.27.2.el7.x86_64
Operating System: H3Linux Release 1.1.2
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.51GiB
Name: node2
ID: XTQU:PF27:RBNZ:ZLKN:ZDAG:DSMN:W73D:BBUU:SC33:GNJ7:CZX3:CG4R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
I don't know why stopping the service would have anything to do with making docker get stuck, however you are running a very old version of Docker at this point and I don't think we can really troubleshoot much until you are on a more recent version (19.03 is the latest).

**Comment by lyyao09** [comment]
@cpuguy83 thank you for your reply. I updated the description information. The premise of the stuck is that nfs client container in the **Created** state after  stopped, and then I `docker inspect` to this **Created** container. 

I also tested the latest docker version and the problem still exists. By reading the docker source code, the stuck may be because the docker create and docker inspect commands share the same Mutex lock.

**Comment by jikunbupt** [comment]
In the same environment，we found that the reason of docker inspect hangs is container lock was  held when start nfs-client container. So we use a method named Trylock to try get the lock, and immediately return if get fail. Is this treatment appropriate?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
