### ISSUE TITLE
Windows Swarm: certain overlay network names break published ports

### ISSUE THREAD

**Issue by mr-field** [moby/moby#41434]
**Description**
When using Swarm mode on Windows, a service won't be reachable at its published port from any external host if:
- It's connected to a named network
- The network's name comes before "ingress" in alphabetic order

Similarly, any services in a stack whose name alphabetically comes before "ingress" won't be reachable at their published ports, as their network(s) will be prefixed with the stack name.

**Steps to reproduce the issue:**
I'm using the names `hotel` and `juliett` for my test networks, but the same goes for `ingresr` and `ingrest` or any other pair where the first network alphabetically comes before "ingress" and the second after.

1. Spin up a Windows Server VM (I'm using a fresh Azure VM with a Windows Datacenter 2019 image)
2. Start Swarm mode: `docker swarm init --advertise-addr {VM's public IP address}`
3. Create an overlay network with a name that alphabetically comes *before* "ingress": `docker network create -d overlay hotel`
4. Create a service attached to this network: `docker service create --name iis --publish 8080:80 --network hotel mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019`
5. From a different machine, try to connect to the VM on port 8080. Observe how the connection times out
   - We can confirm that IIS is actually running by connecting to port 80 within the service container: `docker exec {container ID} curl http://localhost:80`
6. Create another overlay network, this time with a name that alphabetically comes *after* "ingress": `docker network create -d overlay juliett`
7. Switch the service's network to the new one:
   - `docker service update --network-rm hotel iis`
   - `docker service update --network-add juliett iis`
8. Try again to connect to port 8080 from a different machine. Observe how you get back the default IIS page

Toggling between the two networks at this point works as a handy on/off switch. Also note that the `iis` service works fine if it's not connected to any named network (i.e. it's created without the `--network` option).

**Describe the results you received:**
When the `iis` service was connected to the `hotel` network (step 5), this is what I got when trying to connect from my PC to port 8080 on the test VM:
```
$ curl http://{VM's IP address}:8080
curl: (7) Failed to connect to {VM's IP address} port 8080: Timed out
```

**Describe the results you expected:**
I would have expected to receive the default IIS web page, like I do at step 8 when `iis` is connected to `juliett`:
```
$ curl http://{VM's IP address}:8080
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{snip}
</html>
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This also happens if any stack is deployed using a name that alphabetically comes before "ingress", as its network(s) will be prefixed with the stack name. For example, given this Compose file:
```
version: "3.7"

services:
  iis:
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019 
    ports:
      - "8080:80"
```

Deploying the file using `docker stack deploy -c test.yml hotel` and then connecting to port 8080 will result in the same output seen at step 5, as the network is called `hotel_default`. However, removing the stack and redeploying it with `docker stack deploy -c test.yml juliett` will work, as the network is now called `juliett_default`.

**Output of `docker version`:**
```
Client: Docker Engine - Enterprise
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0da829ac52
 Built:             06/26/2020 17:20:46
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise (Unlicensed - not for production workloads)
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.11
  Git commit:       0da829ac52
  Built:            06/26/2020 17:19:32
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker Enterprise clusters (Mirantis Inc., v1.4.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 3
 Server Version: 19.03.11
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: rikl41ga4ux824lt1a5zwmvgy
  Is Manager: true
  ClusterID: 8l72xb0i3j216lwubkqib8cdn
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.1.4
  Manager Addresses:
   10.0.1.4:2377
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1397)
 OSType: windows
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.5GiB
 Name: network-name-te
 ID: FGUC:4RJV:UDKQ:5CMC:3FRU:XPC7:TFWI:KXRF:GZUT:P22C:MPE6:JJRQ
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Unlicensed - not for production workloads
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This was tested on a fresh Azure VM using the image called "Windows Server 2019 Datacenter Server Core with Containers".

I also observed the same problem on our on-prem Windows Server 2019 VM, also running Docker Engine 19.03.11.

**Comment by olljanat** [comment]
@mr-field possibly caused by same bug than #40998 ?
IIUC fix to that one should be released tomorrow.

**Comment by mr-field** [comment]
It's possible, both VMs where I tried this had KB4551853 installed. I'll try to reproduce once the fix is released.

**Comment by olljanat** [comment]
@mr-field KB4577069 update is now available, can you check if that fixes issue on your environment?

**Comment by mr-field** [comment]
It does seem to fix the problem on the Azure VM I was using for testing. I'll see if I can get the fix deployed to our infrastructure and check that the problem is fixed there too (may take a while).

**Comment by olljanat** [comment]
Confirmed. I can see same bug our environment and that workaround also works.

**Comment by mr-field** [comment]
That's good, thanks for checking. It will likely take a while to update our environment, so I'll close this for now as it's almost certainly just a side effect of #40998.
