### ISSUE TITLE
Constant Id for Docker Daemon

### ISSUE THREAD

**Issue by jayeshjk** [moby/moby#41443]
**Description**

As described in https://github.com/moby/moby/issues/36463, we were using `deprecated-key-path` to persist the `key.json` to a different path other than the default `/etc/docker/key.json`. As mentioned in https://github.com/moby/moby/issues/36463, we need to do this as the path `/etc/` is ephemeral for us.
However, it seems that this flag is not supported anymore since v19.03.0. We need help in understanding how we can override the key file path.

**Steps to reproduce the issue:**

1. start docker demon. run the command "docker info and note the ID
2. stop docker demon and delete the file "/etc/docker/key.json"
3. Start the docker demon again and run the "docker info" it will have a different ID

**Describe the results you received:**
**Describe the results you expected:**

Though the result is expected as we have deleted "/etc/docker/key.json", as mentioned in the description we need a way to have a constant ID.

Please let me know if any other information is needed.

**Comment by AkihiroSuda** [comment]
`ln -s /somewhere/key.json /etc/docker/key.json` works for you?
If not `mount -o bind,ro  /somewhere/key.json /etc/docker/key.json` may work

**Comment by jayeshjk** [comment]
Thanks @AkihiroSuda for quick response, I will try this out and update here.e

**Comment by thaJeztah** [comment]
the id is now stored in /var/lib/docker/engine-id;

https://github.com/moby/moby/blob/e598ffcdf860042beacdecd14354a73543d8c779/daemon/id.go#L12
