### ISSUE TITLE
Docker container exit code is zero when program is terminated with SIGSEGV

### ISSUE THREAD

**Issue by f-squirrel** [moby/moby#41454]
**Description**

1. Create a simple program calling `raise(SIGSEGV)`:
```c++
#include <csignal>

int main() {
    std::raise(SIGSEGV);
    return 0;
}
```
Create a Dockerfile to build and run it:
```docker
FROM ubuntu:18.04

# Install tools
RUN apt-get update \
    && apt-get -y install \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Build the application
COPY ./ /src/
WORKDIR /src/
RUN g++ main.cpp -o app

WORKDIR /
CMD ["/src/app"]
```
3. Build and run Docker container:
```
$ docker build -f ./Dockerfile -t test:latest .
$ docker run --name test test:latest
```
4. Check the exit code:
```
$ docker inspect test --format='{{.State.ExitCode}}'
0
```
**Describe the results you received:**
The exit code is `0`.

**Describe the results you expected:**
The exit code is supposed to be `139` or at least not `0`.

**Additional information you deem important (e.g. issue happens only occasionally):**
With the workaround mentioned in https://github.com/moby/moby/issues/30593 the exit code is correct.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 71
  Running: 0
  Paused: 0
  Stopped: 71
 Images: 177
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-53-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.749GiB
 Name: ubuntu
 ID: 3CR2:7A6I:P7GV:M7EU:KNNV:UD3N:W3W5:7NOO:PXGS:GW6R:ERTI:CIWC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: fsquirrel
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested with Docker running on:
* VMware Fusion Professional Version 11.5.1 (15018442)
* macOS Catalina 10.15.5 (19F101)

**Comment by cpuguy83** [comment]
`SIGSEGV` is a signal. Signals are handled by the process they are sent to.
You aren't handling the signal here, only exiting.

One extra thing to note, is that you are running as PID 1 in the container, in which case most likely the default signal handlers are not loaded in your program.
If you run the container with `--init` you'll get exit code 139.

Closing since this is working as expected, but feel free to discuss. Thanks!

**Comment by f-squirrel** [comment]
@cpuguy83 , thank you for helping.
Does it mean that w/o `--init` the signals are not handled correctly?

**Comment by cpuguy83** [comment]
It means you either need to use "--init" or you need to explicitly setup signal handling in your program because your program is automatically dropping the default signal handlers because it is running as PID 1.

"--init" runs a small, proper PID 1 in the container for you, thus making your program not run as PID 1, and not dropping the default signal handlers.

**Comment by f-squirrel** [comment]
@cpuguy83 thank you for the clear explanation!
