### ISSUE TITLE
systemctl - Failed with result 'service-start-limit-hit'

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [moby/moby#41461]
Hi, 

env: Ubuntu 20.4
docker version:
```
Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```
I created file `deamon.json` with content:
```
{
 "hosts": ["unix:///var/run/docker.sock", "tcp://127.0.0.1:2375"],
 "dns": ["8.8.8.8", "8.8.4.4"]
} 
```
result: 
wrz 17 14:43:43  systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

`When I remove hosts from file everything works fine.`

How to define hosts in this file to make docker work correctly?

**Comment by Krzysztof-Lempicki** [comment]
`sudo nano /usr/lib/systemd/system/docker.service`

remove parameter `-H` from:
`ExecStart: //removed paramter -H from command`

This will solve problem.

**Comment by jrwren** [comment]
I just had same problem after a reboot. I had to delete empty dirs in /var/lib/docker before I could mount /var/lib/docker from ZFS. Not sure how those dirs were written, presumably by a deb package being installed when the zfs dir wasn't mounted.

```
sudo mv /var/lib/docker /var/lib/docker.bak
sudo zfs mount lxd/docker
```
