### ISSUE TITLE
High latency on first request in docker and docker swarm

### ISSUE THREAD

**Issue by Drealine** [moby/moby#41470]
Hi.

I've experienced an issue in docker.
For example, if no requests while 1h for example, the first request is very slow. I can take more than 30sec or 1min to show a page.
After that, all others pages are fast.

Do you have an idea ? Seems that somes others persons have the same problems but no response.

Regards,

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by Drealine** [comment]
Docker version : `Docker version 19.03.13, build 4484c46d9d`

Docker info : 
```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.854GiB
 Name: debian
 ID: 6SRS:CO7S:AWXU:7OKN:ZAGQ:AZCP:JMWR:N6CQ:KKOR:CLI3:RHBN:GLOQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- step 1 : No requests coming into docker during 1 hour for example
- step 2 : try a request http into one of containers
- step 3 : network request take 9 secs to be finished : 
![image](https://user-images.githubusercontent.com/61891683/93605863-99a8b500-f9c7-11ea-8c9d-f157775935de.png)

- step 4 : all others requests are fast after the first request : 
![image](https://user-images.githubusercontent.com/61891683/93605981-c1981880-f9c7-11ea-920a-5d33b4b4e223.png)

Docker is runing on VMware Esxi v6.7

**Comment by n0nvme** [comment]
I have the same problem but with docker swarm

`docker version`
```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 17:24:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

`docker info`
```
Containers: 195
 Running: 34
 Paused: 0
 Stopped: 161
Images: 490
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: REDACTED
 Is Manager: true
 ClusterID: REDACTED
 Managers: 3
 Nodes: 8
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 6
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: REDACTED
 Manager Addresses:
  REDACTED
  REDACTED
  REDACTED
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.3GiB
Name: REDACTED
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by Drealine** [comment]
Hi,

Did you see something about this problem ?

**Comment by Drealine** [comment]
> I have the same problem but with docker swarm
> 
> `docker version`
> 
> ```
> Client:
>  Version:           18.09.9
>  API version:       1.39
>  Go version:        go1.11.13
>  Git commit:        039a7df9ba
>  Built:             Wed Sep  4 17:24:10 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.9
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.11.13
>   Git commit:       039a7df
>   Built:            Wed Sep  4 16:19:38 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
> ```
> 
> `docker info`
> 
> ```
> Containers: 195
>  Running: 34
>  Paused: 0
>  Stopped: 161
> Images: 490
> Server Version: 18.09.9
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: active
>  NodeID: REDACTED
>  Is Manager: true
>  ClusterID: REDACTED
>  Managers: 3
>  Nodes: 8
>  Default Address Pool: 10.0.0.0/8
>  SubnetSize: 24
>  Orchestration:
>   Task History Retention Limit: 5
>  Raft:
>   Snapshot Interval: 10000
>   Number of Old Snapshots to Retain: 0
>   Heartbeat Tick: 1
>   Election Tick: 3
>  Dispatcher:
>   Heartbeat Period: 5 seconds
>  CA Configuration:
>   Expiry Duration: 3 months
>   Force Rotate: 6
>  Autolock Managers: false
>  Root Rotation In Progress: false
>  Node Address: REDACTED
>  Manager Addresses:
>   REDACTED
>   REDACTED
>   REDACTED
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
> runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
> init version: fec3683
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.4.0-116-generic
> Operating System: Ubuntu 16.04.4 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 31.3GiB
> Name: REDACTED
> ID: REDACTED
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  0.0.0.0/0
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
> 
> WARNING: No swap limit support
> ```

Docker is runing on VMWare environment or not ?

Seems that when docker is runing on physical machine, the problem desapear. .

**Comment by n0nvme** [comment]
> Docker is runing on VMWare environment or not ?

All managers are physical hosts, one worker is Hyper-V machine, all others are physical too. Problem still exists when I remove Hyper-V WM from cluster

**Comment by olljanat** [comment]
@Drealine what application you are running on top of Docker? I see that your pictures are from browser so most probably you are running some kind of web server? Are your sure that is configured to stay running without going to sleeping after a while?

**Comment by Drealine** [comment]
@olljanat Running apache and mysql on one only container.

**Comment by Drealine** [comment]
Certainly. If I install without docker, it work very well.

**Comment by olljanat** [comment]
@Drealine running multiple processes on single container is against on best practices. I highly recommend that you use those official Docker optimized images instead of:
- https://hub.docker.com/_/httpd
- https://hub.docker.com/_/mysql

**Comment by Drealine** [comment]
@olljanat Yes, I see. 

But why do this ? If I install for example the same image directly on a physical server, I've not the problem. 
Maybe VM Ware ?
Also, I already saw some problems with internal network bridge on Docker.

**Comment by n0nvme** [comment]
@olljanat I have one app in each container and problem still exists

**Comment by olljanat** [comment]
@Drealine we have plenty of servers running Docker on top of VMware ESXi 6.5 without problems but can be of course from configuration/hardware/etc.

I would maybe track how those processes are using memory. Sounds like they gets unloaded from RAM and next call need loads them back from disk which can take time.

**Comment by Drealine** [comment]
Yes @olljanat. I think that if we create a custom dockerfile, normaly, it would be work. 

I tried a lot of times with the same problem using others hardwares with the latest version for each. 

I don't know what happen ...
