### ISSUE TITLE
Moby website github link redirects to 404 Not found

### ISSUE THREAD

**Issue by ghost** [moby/moby#41476]
**Description**
I was visiting https://mobyproject.org/ and when I clicked github link it redirected to 404 Page Not found.

**Steps to reproduce the issue:**
1. Go to https://mobyproject.org/
2.Click on Github Link

**Describe the results you received:**
It redirected to `https://github.com/moby/moby/blob/moby/README.md` 

**Describe the results you expected:**
I think it should be `https://github.com/moby/moby/` or to README page `https://github.com/moby/moby/blob/master/README.md`

**Comment by patrickbrett** [comment]
Seconding this, was going to add this issue and found it was already reported.

Looks like it's been open for a while over at moby/mobywebsite: https://github.com/moby/mobywebsite/issues/45

There have been a few PRs to fix but none of them have been merged and the link is still broken.

https://github.com/moby/mobywebsite/pulls?q=is%3Apr+is%3Aclosed

**Comment by thaJeztah** [comment]
I think this was fixed
