### ISSUE TITLE
How to compile the docker? (when golang.org is not accessible)

### ISSUE THREAD

**Issue by Chr1s-T** [moby/moby#41480]
Hello, I prey for some help.

I want to compile the docker, and I have downloaded the docker source code in `~/go/src/github.com/docker/docker` directory.

When I was trying to use `make build` command, it was failed because I cannot connet golang.org which is not allowed to access in our country.
![image](https://user-images.githubusercontent.com/23159278/93836725-3ca64b00-fcb6-11ea-8fb1-f1a91a7692b5.png)

So I tried to use `./hack/make.sh binary` command, it was still failed for:
![image](https://user-images.githubusercontent.com/23159278/93836687-28fae480-fcb6-11ea-8ffa-5e2533acf12e.png)

What should I do now, please help me, thanks!

**Comment by olljanat** [comment]
Why you want build Docker yourself?
You can find night my builds from https://master.dockerproject.org

Afaik make build is correct way and connection to golang.org or its mirror is mandatory. Without those you need setup environment which matches to Dockerfile.

**Comment by loversugar** [comment]
According to this [document](https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md), after we should execute **make BIND_DIR=. shell**, the program should build the content of Dockerfile. In China, because of GFW, I meet the same question as you. So I annotate **gotestsum golangci_lint shfmt", and then run **make BIND_DIR=. shell", I found it's ok

**Comment by olljanat** [comment]
Ok. I think that least most critical libraries are mirrored to https://github.com/golang

And with quick search I found also this one https://goproxy.cn/

**Comment by Chr1s-T** [comment]
> Ok. I think that least most critical libraries are mirrored to https://github.com/golang
> 
> And with quick search I found also this one https://goproxy.cn/

Yeah, that's it.
However, `make build` command not only requires GOPROXY, but it sends request to `https://golang.org` and `goggle.golang.org` and `cloud.google.com` and so-on, which is not allowed in our country either. I want to find a mirrot site as an alternative, but still failed.

**Comment by yufeifly** [comment]
> According to this [document](https://github.com/moby/moby/blob/master/docs/contributing/set-up-dev-env.md), after we should execute **make BIND_DIR=. shell**, the program should build the content of Dockerfile. In China, because of GFW, I meet the same question as you. So I annotate _**gotestsum golangci_lint shfmt**_, and then run **make BIND_DIR=. shell***, I found it's ok

可以详细点讲一下你是怎么注释的，在哪里注释的吗？我编译时也遇到了同样问题。

**Comment by loversugar** [comment]
![image](https://user-images.githubusercontent.com/19316904/94023999-74fa7600-fde9-11ea-8a5a-7785c6099486.png)
![image](https://user-images.githubusercontent.com/19316904/94024015-79bf2a00-fde9-11ea-8158-544578e392e1.png)
这个要根据具体报错信息来，上面是我注解的代码，跟具体业务逻辑没有关系。我是在docker外部用goland开发docker，在内部进行build，但是anyway，你看对你有帮助吗。 @yufeifly

**Comment by thaJeztah** [comment]
So the problem looks to be in golang-ci-lint, which is a tool that's used in tests (so not really needed to build the dev container).

We should have a look why it insists on using the proxy (and look if we can override that, but explicitly disabling the go module proxy).

We also need to have a look at removing some of the stages from the (default) dev container, as some of them are unlikely used when you're developing. There's a WIP pull request that does some of that; https://github.com/moby/moby/pull/41404

**Comment by thaJeztah** [comment]
We could probably add a `GOPROXY` build-arg, to allow overriding for specific situations, but will have to check if the golang-ci-lint installer takes that into account.

**Comment by Chr1s-T** [comment]
> We could probably add a `GOPROXY` build-arg, to allow overriding for specific situations, but will have to check if the golang-ci-lint installer takes that into account.

In fact, we could set GOPROXY tag in the `hack/dockerfile/install/install.sh` by adding the command `export GOPROXY=https://goproxy.io`, but it just solved several network problems, because when `make build` command moving on the last building program, it requests the `golang.org` which is not available.

So I want to try `make binary` in the Ubuntu-like-OS, however, too much go packages were not available and made me crazy.

**Comment by yufeifly** [comment]
@loversugar 好的，我试试。非常感谢：）

**Comment by loversugar** [comment]
@Chr1s-T I recommend you can buy expressvpn or create your own VPS using trojan. It's easy to create it. By the way, if you build dev env, I think you can do it as I said, annotate some code. About setting goproxy at the file, I tried it, 翻墙才是王道

**Comment by Chr1s-T** [comment]
> @Chr1s-T I recommend you can buy expressvpn or create your own VPS using trojan. It's easy to create it. By the way, if you build dev env, I think you can do it as I said, annotate some code. About setting goproxy at the file, I tried it, 科学上网才是王道

我也想用VPN，但是我们这边内部环境不准上外网。

**Comment by loversugar** [comment]
@Chr1s-T 那就注释掉一些dockerfile里面的代码吧，在外部用goland开发，不影响内部操作。dockerfile里面的配置无非也是环境搭建，我试过注释掉之后，在内部执行make.sh之类的操作没有问题

**Comment by Chr1s-T** [comment]
> @Chr1s-T 那就注释掉一些dockerfile里面的代码吧，在外部用goland开发，不影响内部操作。dockerfile里面的配置无非也是环境搭建，我试过注释掉之后，在内部执行make.sh之类的操作没有问题

好的，谢谢你，我试试看

**Comment by yufeifly** [comment]
> > @Chr1s-T I recommend you can buy expressvpn or create your own VPS using trojan. It's easy to create it. By the way, if you build dev env, I think you can do it as I said, annotate some code. About setting goproxy at the file, I tried it, 科学上网才是王道
> 
> 我也想用VPN，但是我们这边内部环境不准上外网。

我用的v2ray，浏览器可以fq，但是终端不可以。终端fq的话，需要怎么设置呢？

**Comment by loversugar** [comment]
@yufeifly 终端设置代理

**Comment by yufeifly** [comment]
> @yufeifly 终端设置代理

请问setting goproxy at the file 是怎么操作呢？

**Comment by cpuguy83** [comment]
`make build` sets up a build environment which indeed has to do all kinds of things.

To compile, make sure you have a proper environment and run `hack/make.sh binary`.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
