### ISSUE TITLE
Docker Installation on Fedora 32

### ISSUE THREAD

**Issue by BBQigniter** [moby/moby#41489]
reminder issue as asked for by @thaJeztah , he posted a Howto at https://github.com/docker/for-linux/issues/955#issuecomment-694825085 and it seems that you still need to execute a command (e.g. on Fedora Server):

```firewall-cmd --permanent --zone=FedoraServer --add-masquerade```

so that containers can talk together in their assigned network.

**Comment by thaJeztah** [comment]
@arkodg could you have a look? Is this something we should set automatically (similar to how we set the other options https://github.com/moby/libnetwork/pull/2548)?

**Comment by arkodg** [comment]
@BBQigniter I tried out the following test on `fedora32` to create a container and ping it from another container and it works fine with the steps @thaJeztah shared

```
sudo docker run -it -d --name=test1 ubuntu
sudo docker run --rm -it alpine ping $(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test1)
```

But those steps are only valid for containers on the `default` bridge / `docker0` . If you create your own docker networks, you will need to manually  insert that bridge interface into the trusted zone
```
sudo firewall-cmd --permanent --zone=trusted --add-interface=<bridge-intf>; firewall-cmd --reload
```
This should be taken care of automatically once https://github.com/moby/libnetwork/pull/2548 is integrated into a docker release

**Comment by BBQigniter** [comment]
@arkodg yes, pinging works on the fly with only the "trusted" stuff. i'm testing around e.g. with https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html on my lab-server, and after adding the "masquerading" my elastic-nodes were able to talk via port 9200 to each other

**Comment by almereyda** [comment]
This has been released yesterday and is officially supported now.

Also see https://docs.docker.com/install/linux/docker-ce/fedora/

Can this be closed then?

**Comment by thaJeztah** [comment]
Yes, I think this is ready to close
