### ISSUE TITLE
docker stack deploy getting errors

### ISSUE THREAD

**Issue by ghost** [moby/moby#41498]
Hi All,

Getting network related errors in docker logs  after docker stack deploy.

docker-compose file
-------------------------
version: '3'

networks:
  replication:
    driver: overlay
services:
  pgmaster:
    hostname: hostname1
    image: postgres
    ports:
      - 22
    volumes:
      - pgmaster:/var/lib/postgresql
  pgstandby:
    hostname: hostname2
    image: postgres
    ports:
      - 22
    volumes:
      - pgstandby:/var/lib/postgresql
  pgbouncer:
    hostname: hostname1
    image: ubuntu
    ports:
      - 22
    volumes:
      - pgbouncer:/etc/pgbouncer
volumes:
  pgmaster:
   driver: local
  pgstandby:
   driver: local
  pgbouncer:
      driver: local

Docker log errors:
====================
level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=3k70bfdkyfm155tf8dbkb>
00" level=warning msg="underweighting node vc31viljuyp457jfzze6owyhd for service 3k70bfdkyfm155tf8dbkb14g9 because it experienced 5 failures or rejections within 5m0s">
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=warning msg="Entry was not in db: nid:vwgpykujawbb4xmbteg3wn2fc eid:205635a06bcb749075a166266b119f472a021e10288362c91f6875aaa8e30a5c peerIP:10.0.2.94 peerMac>
00" level=warning msg="Peer operation failed:could not delete fdb entry for nid:vwgpykujawbb4xmbteg3wn2fc eid:205635a06bcb749075a166266b119f472a021e10288362c91f6875aaa>
00" level=info msg="initialized VXLAN UDP port to 4789 "
00" level=info msg="initialized VXLAN UDP port to 4789 "
00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint vwgpykujawbb4xmbteg3wn2fc 8b51e34094f96ff207a37044b49edb9b24>
00" level=warning msg="deleteServiceInfoFromCluster NetworkDB DeleteEntry failed for 526524a7770df0726e7206bdfdfa072657593924af6780a0795a7d9fceb56b29 k8nrakj7fkx4lsgs5>
00" level=warning msg="rmServiceBinding deleteServiceInfoFromCluster tenent_pgbouncer 526524a7770df0726e7206bdfdfa072657593924af6780a0795a7d9fceb56b29 aborted c.servic>
00" level=error msg="4c97357c1be485309cdb0be2c59a076786cde4ee8c28ba25ba68d6adf7027f3c cleanup: failed to delete container from containerd: no such container"
00" level=warning msg="underweighting node wptaekrvuun83e8c7w294486e for service vr1al82axj9wlvb3sxi0g8kuq because it experienced 5 failures or rejections within 5m0s">
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=vr1al82axj9wlvb3sxi0g>
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=warning msg="underweighting node wptaekrvuun83e8c7w294486e for service 3k70bfdkyfm155tf8dbkb14g9 because it experienced 5 failures or rejections within 5m0s">
00" level=warning msg="memberlist: Failed to send ping: write udp [::]:7946->10.1.64.6:7946: sendto: network is unreachable"
00" level=warning msg="bulk sync to node aa270967e30a failed: failed to send a TCP message during bulk sync: dial tcp 10.1.64.6:7946: connect: network is unreachable"
00" level=error msg="periodic bulk sync failure for network k8nrakj7fkx4lsgs55l3vnsdp: bulk sync to node aa270967e30a failed: failed to send a TCP message during bulk >
00" level=warning msg="bulk sync to node aa270967e30a failed: failed to send a TCP message during bulk sync: dial tcp 10.1.64.6:7946: connect: network is unreachable"
00" level=error msg="periodic bulk sync failure for network vwgpykujawbb4xmbteg3wn2fc: bulk sync to node aa270967e30a failed: failed to send a TCP message during bulk >
00" level=info msg="NetworkDB stats mihealthcare2(0f80d2d85d82) - netID:qcoczsjii94urbfbil1tpb8de leaving:true netPeers:0 entries:36 Queue qLen:0 netMsg/s:0"
00" level=info msg="NetworkDB stats mihealthcare2(0f80d2d85d82) - netID:vwgpykujawbb4xmbteg3wn2fc leaving:false netPeers:2 entries:173 Queue qLen:0 netMsg/s:0"
00" level=info msg="NetworkDB stats mihealthcare2(0f80d2d85d82) - netID:k8nrakj7fkx4lsgs55l3vnsdp leaving:false netPeers:2 entries:236 Queue qLen:1 netMsg/s:1"
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=vr1al82axj9wlvb3sxi0g>
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=warning msg="underweighting node wptaekrvuun83e8c7w294486e for service 3k70bfdkyfm155tf8dbkb14g9 because it experienced 5 failures or rejections within 5m0s">
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=vr1al82axj9wlvb3sxi0g>
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=vr1al82axj9wlvb3sxi0g>
00" level=warning msg="underweighting node vc31viljuyp457jfzze6owyhd for service vr1al82axj9wlvb3sxi0g8kuq because it experienced 5 failures or rejections within 5m0s">
00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
00" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=vc31viljuyp457jfzze6owyhd service.id=3k70bfdkyfm155tf8dbkb>
lines 475333-475375/475375 (END)

**Comment by olljanat** [comment]
@vasudba sounds that you have multiple node swarm and some of those are either down. Plz check that you have opened these firewall ports between nodes https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts and check with command *docker node ls* that those can see each others.

PS. Using Github code block for those logs would make them much more readable.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
