### ISSUE TITLE
consider picking modules-friendly commits for dependencies in vendor.conf

### ISSUE THREAD

**Issue by thepudds** [moby/moby#41504]
As a stepping stone for one day adopting modules within this repo, and also to make things more workable for advanced modules-based consumers, consider picking modules-friendly commits for dependencies in vendor.conf.

Currently, cmd/go will complain about 5 dependencies in the current vendor.conf in master if you attempt to ask cmd/go to convert vendor.conf to the equivalent set of module `require` directives by running `go mod init`.

This can fail if a specific dependency is not complying with a requirement of cmd/go.  Resolving these issues moves this repo closer to one day being able to adopt modules, and also makes it easier for existing modules-based consumers today.

Separately, failures like this can alternatively be because of commits pointing to unmerged forks or similar issues that are arguably potentially vectors of attack (e.g., https://github.com/golang/go/issues/27191#issuecomment-419196656), so separately, it could be worth at least reviewing why these are occurring.

Behavior with with current master (0c9c828) and go 1.15.3:

```
$ git clone --depth=1 https://github.com/moby/moby
$ cd moby
$ go mod init github.com/docker/docker
 ```

Which outputs:
> go: creating new go.mod: module github.com/docker/docker
> go: copying requirements from vendor.conf
> go: converting vendor.conf: stat github.com/hashicorp/go-immutable-radix@826af9ccf0feeee615d546d69b11f8e98da8c8f1: unknown revision 826af9ccf0feeee615d546d69b11f8e98da8c8f1
> go: converting vendor.conf: stat github.com/cespare/xxhash/v2@d7df74196a9e781ede915320c11c378c1b2f3a1f: github.com/cespare/xxhash@v1.1.1-0.20191114174713-d7df74196a9e: invalid version: go.mod has post-v1 module path "github.com/cespare/xxhash/v2" at revision d7df74196a9e
> go: converting vendor.conf: stat gotest.tools/v3@bb0d8a963040ea5048dcef1a14d8f8b58a33d4b3: gotest.tools@v1.4.1-0.20200209214718-bb0d8a963040: invalid version: go.mod has post-v1 module path "gotest.tools/v3" at revision bb0d8a963040
> go: converting vendor.conf: stat github.com/coreos/go-systemd/v22@2d78030078ef61b3cae27f42ad6d0e46db51b339: github.com/coreos/go-systemd@v0.0.0-20191111152658-2d78030078ef: invalid version: go.mod has post-v0 module path "github.com/coreos/go-systemd/v22" at revision 2d78030078ef
> go: converting vendor.conf: stat github.com/godbus/dbus/v5@37bf87eef99d69c4f1d3528bd66e3a87dc201472: github.com/godbus/dbus@v0.0.0-20190930202911-37bf87eef99d: invalid version: go.mod has post-v0 module path "github.com/godbus/dbus/v5" at revision 37bf87eef99d
> 

This is also related to anyone who might try to follow Suggestion 3 from #41503, or otherwise try to follow this FAQ:

https://github.com/golang/go/wiki/Modules#i-have-a-problem-with-a-complex-dependency-that-has-not-opted-in-to-modules-can-i-use-information-from-its-current-dependency-manager

CC @thaJeztah @cpuguy83

**Comment by thepudds** [comment]
As far I can tell from a very quick look, there seem to be two main issues here.

### Issue 1

For this first error reported by 'go mod init':

> go: converting vendor.conf: stat github.com/hashicorp/go-immutable-radix@826af9ccf0feeee615d546d69b11f8e98da8c8f1: unknown revision 826af9ccf0feeee615d546d69b11f8e98da8c8f1

For that commit, github reports:
> This commit does not belong to any branch on this repository.

That warning is visible in the github web interface for example [here](https://github.com/hashicorp/go-immutable-radix/commit/826af9ccf0feeee615d546d69b11f8e98da8c8f1).

That seems to be an example of what I had mentioned above in terms cmd/go disallowing what arguably could be used as a potential attack vector (e.g., as described in https://github.com/golang/go/issues/27191#issuecomment-419196656).

----

### Issue 2

If you get past Issue 1 (for example, by just substituting current master of hashicorp/go-immutable-radix, which is presumably not a full fix but is just a workaround for now to get past the error), then you hit Issue 2, which seems to be https://github.com/moby/buildkit/issues/1561 and https://github.com/moby/buildkit/pull/1425. 

That appears to fixed at master of github.com/moby/buildkit. If you workaround this Issue 2 by using master, you get a valid go.mod file.

--------------

The remaining errors reported above appear to be 'go mod init' falsely complaining more than it should about finding `/v2`, `/v5`, and `/v22` in vendor.conf (which might be a variation of https://github.com/golang/go/issues/31549 or similar).

**Comment by thepudds** [comment]
In addition, in case it helps, here is one quick approach to converting vendor.conf to a go.mod with `require` directives for the corresponding commits from vendor.conf.

This is bypassing 'go mod init', which I sometimes find helpful.

Start fresh:

```
$ git clone --depth=1 https://github.com/moby/moby
$ cd moby
```

Then do a simple textual transform of vendor.conf into a textually valid go.mod:

```
echo 'module github.com/docker/docker'              > go.mod; \
echo 'require ('                                   >> go.mod; \
cat vendor.conf | awk '/^[^#]/{print " ", $1, $2}' >> go.mod; \
echo ')'                                           >> go.mod
```

Then do the two workarounds described above, using current master for github.com/moby/buildkit and github.com/hashicorp/go-immutable-radix:

```
$ sed -r -i 's#(github.com/moby/buildkit) .*#\1 2b6cccb9b3e9#' go.mod
$ sed -r -i 's#(github.com/hashicorp/go-immutable-radix) .*#\1 5cc8850adfb9#' go.mod
```


The result is the following go.mod, which passes `go list -mod=mod -m all`, which means at least the versions are findable by cmd/go.  (That doesn't mean it will build, though, including possibly because of the quick workarounds mentioned above).

````
module github.com/docker/docker

require (
  github.com/Azure/go-ansiterm d6e3b3328b783f23731bc4d058875b0371ff8109
  github.com/Microsoft/hcsshim 9dcb42f100215f8d375b4a9265e5bba009217a85
  github.com/Microsoft/go-winio 5b44b70ab3ab4d291a7c1d28afe7b4afeced0ed4
  github.com/docker/libtrust 9cbd2a1374f46905c68a4eb3694a130610adc62a
  github.com/golang/gddo 72a348e765d293ed6d1ded7b699591f14d6cd921
  github.com/google/uuid 0cd6bf5da1e1c83f8b45653022c74f71af0538a4
  github.com/gorilla/mux 98cb6bf42e086f6af920b965c38cacc07402d51b
  github.com/Microsoft/opengcs a10967154e143a36014584a6f664344e3bb0aa64
  github.com/moby/locker 281af2d563954745bea9d1487c965f24d30742fe
  github.com/moby/term 7f0af18e79f2784809e9cef63d0df5aa2c79d76e
  github.com/creack/pty 3a6a957789163cacdfe0e291617a1c8e80612c11
  github.com/konsorten/go-windows-terminal-sequences edb144dfd453055e1e49a3d8b410a660b5a87613
  github.com/sirupsen/logrus 60c74ad9be0d874af0ab0daef6ab07c5c5911f0d
  github.com/tchap/go-patricia a7f0089c6f496e8e70402f61733606daa326cac5
  golang.org/x/net ab34263943818b32f575efc978a3d24e80b04bd7
  golang.org/x/sys aee5d888a86055dc6ab0342f9cdc7b53aaeaec62
  github.com/docker/go-units 519db1ee28dcc9fd2474ae59fca29a810482bfb1
  github.com/docker/go-connections 7395e3f8aa162843a74ed6d48e79627d9792ac55
  github.com/moby/sys 6154f11e6840c0d6b0dbb23f4125a6134b3013c9
  golang.org/x/text 23ae387dee1f90d29a23c0e87ee0b46038fbed0e
  gotest.tools/v3 bb0d8a963040ea5048dcef1a14d8f8b58a33d4b3
  github.com/google/go-cmp 3af367b6b30c263d47e8895973edcca9a49cf029
  github.com/syndtr/gocapability 42c35b4376354fd554efc7ad35e0b7f94e3a0ffb
  github.com/RackSec/srslog a4725f04ec91af1a91b380da679d6e0c2f061e59
  github.com/imdario/mergo 1afb36080aec31e0d1528973ebe6721b191b0369
  golang.org/x/sync cd5d95a43a6e21273425c7ae415d3df9ea832eeb
  github.com/moby/buildkit 2b6cccb9b3e9
  github.com/tonistiigi/fsutil ae3a8d753069d0f76fbee396457e8b6cfd7cb8c3
  github.com/grpc-ecosystem/grpc-opentracing 8e809c8a86450a29b90dcc9efbf062d0fe6d9746
  github.com/opentracing/opentracing-go 1361b9cd60be79c4c3a7fa9841b3c132e40066a7
  github.com/google/shlex e7afc7fbc51079733e9468cdfd1efcd7d196cd1d
  github.com/opentracing-contrib/go-stdlib b1a47cfbdd7543e70e9ef3e73d0802ad306cc1cc
  github.com/mitchellh/hashstructure 2bca23e0e452137f789efbc8610126fd8b94f73b
  github.com/gofrs/flock 392e7fae8f1b0bdbd67dad7237d23f618feb6dbb
  github.com/grpc-ecosystem/go-grpc-middleware 3c51f7f332123e8be5a157c0802a228ac85bf9db
  github.com/docker/libnetwork d0951081b35fa4216fc4f0064bf065beeb55a74b
  github.com/docker/go-events e31b211e4f1cd09aa76fe4ac244571fab96ae47f
  github.com/armon/go-radix e39d623f12e8e41c7b5529e9a9dd67a1e2261f80
  github.com/armon/go-metrics eb0af217e5e9747e41dd5303755356b62d28e3ec
  github.com/hashicorp/go-msgpack 71c2886f5a673a35f909803f38ece5810165097b
  github.com/hashicorp/memberlist 3d8438da9589e7b608a83ffac1ef8211486bcb7c
  github.com/sean-/seed e2103e2c35297fb7e17febb81e49b312087a2372
  github.com/hashicorp/errwrap 8a6fb523712970c966eefc6b39ed2c5e74880354
  github.com/hashicorp/go-sockaddr c7188e74f6acae5a989bdc959aa779f8b9f42faf
  github.com/hashicorp/go-multierror 886a7fbe3eb1c874d46f623bfa70af45f425b3d1
  github.com/hashicorp/serf 598c54895cc5a7b1a24a398d635e8c0ea0959870
  github.com/docker/libkv 458977154600b9f23984d9f4b82e79570b5ae12b
  github.com/vishvananda/netns db3c7e526aae966c4ccfa6c8189b693d6ac5d202
  github.com/vishvananda/netlink f049be6f391489d3f374498fe0c8df8449258372
  github.com/moby/ipvs 4566ccea0e08d68e9614c3e7a64a23b850c4bb35
  github.com/BurntSushi/toml 3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005
  github.com/samuel/go-zookeeper d0e0d8e11f318e000a8cc434616d69e329edc374
  github.com/deckarep/golang-set ef32fa3046d9f249d399f98ebaf9be944430fd1d
  github.com/coreos/etcd d57e8b8d97adfc4a6c224fe116714bf1a1f3beb9
  github.com/coreos/go-semver 8ab6407b697782a06568d4b7f1db25550ec2e4c6
  github.com/ugorji/go b4c50a2b199d93b13dc15e78929cfb23bfdf21ab
  github.com/hashicorp/consul 9a9cc9341bb487651a0399e3fc5e1e8a42e62dd9
  github.com/miekg/dns 6c0c4e6581f8e173cc562c8b3363ab984e4ae071
  github.com/ishidawataru/sctp 6e2cb1366111dcf547c13531e3a263a067715847
  go.etcd.io/bbolt 232d8fc87f50244f9c808f4745759e08a304c029
  github.com/docker/distribution 0d3efadf0154c2b8a4e7b6621fff9809655cc580
  github.com/vbatts/tar-split 620714a4c508c880ac1bdda9c8370a2b19af1a55
  github.com/opencontainers/go-digest ea51bea511f75cfa3ef6098cc253c5c3609b037a
  github.com/mistifyio/go-zfs f784269be439d704d3dfa1906f45dd848fed2beb
  google.golang.org/grpc f495f5b15ae7ccda3b38c53a1bfcde4c1a58a2bc
  github.com/opencontainers/runc ff819c7e9184c13b7c2607fe6c30ae19403a7aff
  github.com/opencontainers/runtime-spec 4d89ac9fbff6c455f46a5bb59c6b1bb7184a5e43
  github.com/opencontainers/image-spec d60099175f88c47cd379c4738d158884749ed235
  github.com/cyphar/filepath-securejoin a261ee33d7a517f054effbf451841abaafe3e0fd
  github.com/coreos/go-systemd 39ca1b05acc7ad1220e09f133283b8859a8b71ab
  github.com/coreos/go-systemd/v22 2d78030078ef61b3cae27f42ad6d0e46db51b339
  github.com/godbus/dbus/v5 37bf87eef99d69c4f1d3528bd66e3a87dc201472
  github.com/Graylog2/go-gelf 1550ee647df0510058c9d67a45c56f18911d80b8
  github.com/fluent/fluent-logger-golang 7a6c9dcd7f14c2ed5d8c55c11b894e5455ee311b
  github.com/philhofer/fwd bb6d471dc95d4fe11e432687f8b70ff496cf3136
  github.com/tinylib/msgp af6442a0fcf6e2a1b824f70dd0c734f01e817751
  github.com/fsnotify/fsnotify 45d7d09e39ef4ac08d493309fa031790c15bfe8a
  github.com/aws/aws-sdk-go 2590bc875c54c9fda225d8e4e56a9d28d90c6a47
  github.com/jmespath/go-jmespath 2d053f87d1d7f9f48196ae04cf3daea4273d207d
  github.com/bsphere/le_go 7a984a84b5492ae539b79b62fb4a10afc63c7bcf
  golang.org/x/oauth2 bf48bf16ab8d622ce64ec6ce98d2c98f916b6303
  google.golang.org/api de943baf05a022a8f921b544b7827bacaba1aed5
  go.opencensus.io c3ed530f775d85e577ca652cb052a52c078aad26
  cloud.google.com/go 0fd7230b2a7505833d5f69b75cbd6c9582401479
  github.com/googleapis/gax-go 317e0006254c44a0ac427cc52a0e083ff0b9622f
  google.golang.org/genproto 3f1135a288c9a07e340ae8ba4cc6c7065a3160e8
  github.com/containerd/containerd c623d1b36f09f8ef6536a057bd658b3aa8632828
  github.com/containerd/fifo f15a3290365b9d2627d189e619ab4008e0069caf
  github.com/containerd/continuity efbc4488d8fe1bdc16bde3b2d2990d9b3a899165
  github.com/containerd/cgroups 318312a373405e5e91134d8063d04d59768a1bff
  github.com/containerd/console 8375c3424e4d7b114e8a90a4a40c8e1b40d1d4e6
  github.com/containerd/go-runc 7016d3ce2328dd2cb1192b2076ebd565c4e8df0c
  github.com/containerd/typeurl cd3ce7159eae562a4f60ceff37dada11a939d247
  github.com/containerd/ttrpc 72bb1b21c5b0a4a107f59dd85f6ab58e564b68d6
  github.com/gogo/googleapis 01e0f9cca9b92166042241267ee2a5cdf5cff46c
  github.com/cilium/ebpf 1c8d4c9ef7759622653a1d319284a44652333b28
  github.com/docker/swarmkit d6592ddefd8a5319aadff74c558b816b1a0b2590
  github.com/gogo/protobuf 5628607bb4c51c3157aacc3a50f0ab707582b805
  github.com/golang/protobuf 84668698ea25b64748563aa20726db66a6b8d299
  github.com/cloudflare/cfssl 5d63dbd981b5c408effbb58c442d54761ff94fbd
  github.com/fernet/fernet-go 9eac43b88a5efb8651d24de9b68e87567e029736
  github.com/google/certificate-transparency-go 37a384cd035e722ea46e55029093e26687138edf
  golang.org/x/crypto 75b288015ac94e66e3d6715fb68a9b41bf046ec2
  golang.org/x/time 555d28b269f0569763d25dbe1a237ae74c6bcc82
  github.com/hashicorp/go-memdb cb9a474f84cc5e41b273b20c6927680b2a8776ad
  github.com/hashicorp/go-immutable-radix 5cc8850adfb9
  github.com/hashicorp/golang-lru 7f827b33c0f158ec5dfbba01bb0b14a4541fd81d
  github.com/coreos/pkg 3ac0863d7acf3bc44daf49afef8919af12f704ef
  code.cloudfoundry.org/clock 02e53af36e6c978af692887ed449b74026d76fec
  github.com/prometheus/client_golang 6edbbd9e560190e318cdc5b4d3e630b442858380
  github.com/beorn7/perks 37c8de3658fcb183f997c4e13e8337516ab753e6
  github.com/prometheus/client_model 7bc5445566f0fe75b15de23e6b93886e982d7bf9
  github.com/prometheus/common d978bcb1309602d68bb4ba69cf3f8ed900e07308
  github.com/prometheus/procfs 46159f73e74d1cb8dc223deef9b2d049286f46b1
  github.com/matttproud/golang_protobuf_extensions c12348ce28de40eed0136aa2b644d0ee0650e56c
  github.com/pkg/errors 614d223910a179a466c1767a985424175c39b465
  github.com/grpc-ecosystem/go-grpc-prometheus c225b8c3b01faf2899099b768856a9e916e5087b
  github.com/cespare/xxhash/v2 d7df74196a9e781ede915320c11c378c1b2f3a1f
  github.com/spf13/cobra a684a6d7f5e37385d954dd3b5a14fc6912c6ab9d
  github.com/spf13/pflag 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
  github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
  github.com/morikuni/aec 39771216ff4c63d11f5e604076f9c45e8be1067b
  github.com/docker/go-metrics b619b3592b65de4f087d9f16863a7e6ff905973c
  github.com/opencontainers/selinux 25504e34a9826d481f6e2903963ecaa881749124
  github.com/willf/bitset 559910e8471e48d76d9e5a1ba15842dee77ad45d
)
```

**Comment by thaJeztah** [comment]
Thanks for opening (sorry, was busy, so didn't have time to look closely at everything yet)

> That seems to be an example of what I had mentioned above in terms cmd/go disallowing what arguably could be used as a potential attack vector (e.g., as described in golang/go#27191 (comment)).

Yes, I'd still like to get rid of that temporary fork (which has become not so "temporary"); some discussion here https://github.com/hashicorp/go-immutable-radix/pull/29

I think ideally, go would create a replace rule for that. As can be seen in the vendor.conf, the third column specifies the alternative location, which I think should be considered the equivalent of a `replace` rule in go.mod

https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/vendor.conf#L147



> ```
> go: converting vendor.conf: stat github.com/cespare/xxhash/v2@d7df74196a9e781ede915320c11c378c1b2f3a1f: 
> github.com/cespare/xxhash@v1.1.1-0.20191114174713-d7df74196a9e:
> invalid version: go.mod has post-v1 module path "github.com/cespare/xxhash/v2" at revision d7df74196a9e
> ```

That one looks a bit odd. I know that support for `vXX` suffixes was added not too long ago in vndr (and thus the `vendor.conf` file); I wonder if go ignore the v2 suffix and because of that produces the error? commit `d7df74196a9e781ede915320c11c378c1b2f3a1f` should match the v2.1.1 tag https://github.com/cespare/xxhash/releases/tag/v2.1.1


The other errors seem to be around the same issue (vXX imports defined in vendor.conf, but go trying to use them without?)

**Comment by thepudds** [comment]
Hi @thaJeztah 

> I wonder if go ignore the v2 suffix and because of that produces the error? 

Sorry, I suspect `go mod init` is wrong to complain there. That’s what I meant above in https://github.com/moby/moby/issues/41504#issuecomment-700996916 when I wrote:

> The remaining errors reported above appear to be 'go mod init' falsely complaining more than it should about finding /v2, /v5, and /v22 in vendor.conf (which might be a variation of golang/go#31549 or similar).

**Comment by neersighted** [comment]
This is not really relevant any more as we have moved to a hybrid go-mod vendoring solution.
