### ISSUE TITLE
multi-stage dockerfile builds all when selected target is last

### ISSUE THREAD

**Issue by xenoterracide** [moby/moby#41511]
given this dockerfile

```Dockerfile
ARG IMAGE=builder

FROM alpine:latest AS waitforit
RUN apk add wget
RUN mkdir /root/src
WORKDIR /root/src
RUN wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x wait-for-it.sh

FROM liquibase/liquibase:latest AS builder
COPY --from=waitforit /root/src /liquibase
USER root
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
USER liquibase

FROM ${IMAGE} AS main
ENV DB_PORT=5432
ENV DB_HOST=
ENV LIQUIBASE_LOG_LEVEL=info
ENV LIQUIBASE_CONTEXTS=
COPY entrypoint.sh /
COPY changelog /liquibase/changelog
ENTRYPOINT [ "/entrypoint.sh" ]
```

when running with this command

```
docker build --target=main --build-arg IMAGE=liquibase/liquibase:latest migrations/liquibase
```

docker builds every image in the file. I'd like a way to only build `main` for performance reason in CI.

**Comment by olljanat** [comment]
@xenoterracide it works exactly [like it is on documentation](https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target) so need either move main to be first stage on Dockerfile or use [buildx](https://docs.docker.com/buildx/working-with-buildx/) which can [share cache](https://medium.com/titansoft-engineering/docker-build-cache-sharing-on-multi-hosts-with-buildkit-and-buildx-eb8f7005918e) between CI servers.

**Comment by AkihiroSuda** [comment]
or just set `export DOCKER_BUILDKIT=1` (set by default on Docker for Mac/Win)
