### ISSUE TITLE
Windows Container Takes ~15 min to build

### ISSUE THREAD

**Issue by bestickley** [moby/moby#41526]
**Description**

With this Dockerfile:
```
FROM stefanscherer/node-windows:12 AS install-node
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2016
COPY --from=install-node /nodejs /nodejs
WORKDIR c:/the-bridge
COPY web/setup.ps1 .
RUN powershell ./setup.ps1
COPY build/ web/ ./
RUN powershell ./install.ps1
ENTRYPOINT [ "powershell", "-File", "start.ps1" ]
```
it takes ~15 min to build. The majority of the time is spent between the last RUN and ENTRYPOINT lines. That leads me to believe the issue is Docker takes a long time to clean up what install.ps1 does. Here is install.ps1:
```
Set-Location C:\the-bridge
Set-Location auth
npm i --production
Set-Location ..\bridge\server
npm i --production
Set-Location ..\..\maaps\server
npm i --production
Set-Location ..\..\questionnaire\api
npm i --production
Set-Location ..\..\
Copy-Item 'C:\the-bridge\web.config' -Destination 'C:\inetpub\the-bridge'
New-Item -Path 'C:\inetpub\the-bridge\bridge' -ItemType 'directory'
Copy-Item 'C:\the-bridge\bridge\client\*' -Destination 'C:\inetpub\the-bridge\bridge' -Recurse
New-Item -Path 'C:\inetpub\the-bridge\maaps' -ItemType 'directory'
Copy-Item 'C:\the-bridge\maaps\client\*' -Destination 'C:\inetpub\the-bridge\maaps' -Recurse
New-Item -Path 'C:\inetpub\the-bridge\questionnaire' -ItemType 'directory'
Copy-Item 'C:\the-bridge\questionnaire\client\*' -Destination 'C:\inetpub\the-bridge\questionnaire' -Recurse
```

**Steps to reproduce the issue:**
1. Build the container

**Describe the results you received:**
Wait ~15 minutes

**Describe the results you expected:**
Wait a couple minutes

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:14:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 60
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.1082)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.81GiB
 Name: BAH5CD0345SYW
 ID: UPYK:XKNR:KHKP:WGIZ:VTWX:SJRZ:ZUHF:P6DD:W2FP:OXNN:ZXNQ:TEEP
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 49
  System Time: 2020-10-05T08:58:25.3245739-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Side Note: Sometimes I get errors from the temporary containers that are creates to build each layer of the image specified above. When I checkout the resources given to that container, it only has 1GB of RAM, how can I increase? For windows containers on Docker, you can't go through the Docker Dashboard, I tried editing the VM in Hyper-V but couldn't find where to up the RAM.

Also, I'm required by my client to use a windows production environment, that's the only reason I'm using windows containers. My past experience with Linux containers has been much smoother.
CC: @olljanat

**Comment by thaJeztah** [comment]
> When I checkout the resources given to that container, it only has 1GB of RAM

The default "isolation" on non-server hosts is to use hyper-v isolation, which start a hyper-v vm for the container. I'm not a Windows user, but IIRC, setting the `--memory` "limit" will allow you to _increase_ the available memory for the VM that's started when using hyper-v isolation.

It's likely that performance will be faster if you use "process" isolation; in that case, containers are not started in their own VM, and share the kernel with the host (similar to how Linux containers operate). You can specify the isolation mechanism with `--isolation` on `docker run` and `docker build` (or set it in the daemon configuration file)

Is performance faster with process isolation? (`docker build  --isolation=process ...`) ?

The Windows kernel does not have a stable API, which means there can be incompatibility issues if you try to build/run a docker image for a non-matching version of Windows. That said, recent kernels have improved this situation, and `process` isolation has become less problematic for such cases.

**Comment by bestickley** [comment]
@thaJeztah, thanks for the quick response!
For convenience, I use `docker-compose up --build` for building but the benefit of a faster build from using `docker build` and then specifying the image in my docker-compose.yml would be worth the inconvenience. Thanks for the tip!
I'm running Windows 10, version 1903 and need Windows Server 2016 Image (client prod env) so I can only use Hyper-V isolation. Reference [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2016%2Cwindows-10-1903#windows-10-host-os-compatibility).
Although, my team may decide it's worth facing future possible incompatibility issues to speed up development.

**Comment by thaJeztah** [comment]
Ah, yes, Windows Server 2016 may be more problematic, as it's pretty old, and many improvements went into later kernel versions to make containers better

**Comment by bestickley** [comment]
@thaJeztah, that's great to know! Thank you. We may switch to WS2019 for the improved speed. Thanks for all your help!
