### ISSUE TITLE
Checkpoint fails with shimv2

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#41531]
Calling `docker checkpoint` with the (now default) v2 shim yields an error from the shim:

```
invalid task checkpoint option for io.containerd.runc.v2: unknown
```

**Comment by yufeifly** [comment]
I encounterd this bug too.

**Comment by rst0git** [comment]
The way containers are restored with `containerd` was changed in https://github.com/containerd/containerd/pull/2632.

containerd v1.2:
```go
containerd.WithCheckpoint(checkpoint, "redis-rootfs")
```
containerd v1.3:
```go
containerd.WithNewSnapshot("redis-rootfs", checkpoint)
```
As a result, checkpoint/restore in moby/docker was broken with commit https://github.com/moby/moby/commit/d4c63720e9e477224ef4e66ed843310abf06412b.

**Comment by cpuguy83** [comment]
The issue is with type checking for different runtimes.
We're using the checkpoint type for the v1 runtime only.

I'll prepare a patch for this.
