### ISSUE TITLE
Docker swarm not working, Can't connect my worker node with my manager node receive an error : docker swarm join --token SWMTKN-1-0jlxyzhh10qvgxkwzg2pw21wvvvp19m80ezka3rvzkbxn0rah8-3dj5kfp5m6h81pxd9rr0wpnr9 192.168.8.100:2377

### ISSUE THREAD

**Issue by yasartestgit** [moby/moby#41536]
**Description**

**Steps to reproduce the issue:**
1 I have win 10 pro I'm using two win system, I want to make one manager and one system is worker node.
2.when I do connect the worker node system receive an error:   docker swarm join --token SWMTKN-1-0jlxyzhh10qvgxkwzg2pw21wvvvp19m80ezka3rvzkbxn0rah8-3dj5kfp5m6h81pxd9rr0wpnr9 192.168.8.100:2377
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Closing this because of age, and because there's not a lot of information to go on in the report
