### ISSUE TITLE
max-concurrent-uploads 

### ISSUE THREAD

**Issue by Toplife** [moby/moby#41543]
max-concurrent-uploads=5 

why 5? how to adjust it?

**Comment by AkihiroSuda** [comment]
Please use the issue template https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by thaJeztah** [comment]
This can be configured on the daemon; either through a flag or the daemon.json configuration file https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by Toplife** [comment]
> This can be configured on the daemon; either through a flag or the daemon.json configuration file https://docs.docker.com/engine/reference/commandline/dockerd/

I know how to config it.
