### ISSUE TITLE
[20.10 beta] regression / change in behavior when running different architecture images

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#41552]
See https://github.com/moby/moby/pull/40725#issuecomment-709393496

This came up in CI for Docker Desktop;

looks like  https://github.com/moby/moby/pull/40725 introduced a regression / change in behavior; it will now  at all times print an error, even if the platform supports the other architecture (through quemu); 

```
docker run --rm arm32v7/alpine uname -m

Unable to find image 'arm32v7/alpine:latest' locally
latest: Pulling from arm32v7/alpine
52278dd8e579: Pulling fs layer
52278dd8e579: Verifying Checksum
52278dd8e579: Download complete
52278dd8e579: Pull complete
Digest: sha256:c929c5ca1d3f793bfdd2c6d6d9210e2530f1184c0f488f514f1bb8080bb1e82b
Status: Downloaded newer image for arm32v7/alpine:latest
docker: Error response from daemon: image with reference arm32v7/alpine was found but does not match the specified platform cpu architecture: wanted: amd64, actual: arm.
See 'docker run --help
```

The above previously worked, but now requires the `--platform` flag to be set (even though the image is not multi-arch)

/cc @cpuguy83 @tonistiigi

**Comment by cpuguy83** [comment]
I'll take a look at this today. 

I don't remember why it was needed to set the platform (when not set) in the API layer.

**Comment by thaJeztah** [comment]
Manifest is missing arch;

```json
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 1507,
		"digest": "sha256:7e4bece93b3e57b41f44ed293874207984d801979836c7aa4f8e9ef079f5283c"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 2406763,
			"digest": "sha256:52278dd8e57993669c5b72a9620e89bebdc098f2af2379caaa8945f7403f77a2"
		}
	]
}
```

**Comment by tianon** [comment]
That `config` object does have `os`+`architecture`, though:

```json
{
  "architecture": "arm",
  ...
  "os": "linux",
  ...
}
```

**Comment by StefanScherer** [comment]
Desktop CI was failing last night with the workaround adding `--platform linux/arm` running this command:

```
docker run --platform=linux/arm --rm arm32v7/alpine uname -m

"--platform" is only supported on a Docker daemon with experimental features enabled
```

Could we maybe have `--platform` out of experimental?

**Comment by cpuguy83** [comment]
@StefanScherer This is fixed by https://github.com/moby/moby/pull/41556, just needs one more review.

**Comment by stephen-turner** [comment]
@thaJeztah @cpuguy83 A very similar but not identical issue has been reported by a user at docker/for-win#9166. Does the patch fix this case too?

**Comment by StefanScherer** [comment]
The only detail in docker/for-win#9166 is that it's a mixture of Windows and Linux containers. I assume the user was using LCOW?

**Comment by stephen-turner** [comment]
I guess so. @croventis?

**Comment by cronventis** [comment]
>  I assume the user was using LCOW?
That is correct.

Please ask for any additional information I can provide. Although I went back to v19.03.13 because I need to continue working ;)

**Comment by StefanScherer** [comment]
Thanks @cronventis to confirm this. I suggest to make your use-case visible (eg. the thumbs up at the beginning) in this ticket https://github.com/docker/roadmap/issues/79 as well. Thanks.
