### ISSUE TITLE
docker kill does not execute "direct kill" if initial sigkill fails

### ISSUE THREAD

**Issue by sparrc** [moby/moby#41587]
**Description**

If killPossiblyDeadProcess within the Kill function fails here: https://github.com/moby/moby/blob/master/daemon/kill.go#L141, then docker waits for 2 seconds, and if the container is not killed then dockerd returns here: https://github.com/moby/moby/blob/master/daemon/kill.go#L160

What docker should do is fall-through to the "killProcessDirectly" function here: https://github.com/moby/moby/blob/master/daemon/kill.go#L165

so if killPossiblyDeadProcess fails, the user should expect to see a log message like "failed to exit within 10 seconds of kill - trying direct SIGKILL" coming from here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/container_operations_unix.go#L348

Instead, the return at https://github.com/moby/moby/blob/master/daemon/kill.go#L160 prevents killProcessDirectly from being called.

**Steps to reproduce the issue:**
1. add `return fmt.Errorf("foo error")` here: https://github.com/moby/moby/blob/7cf6dfcb9e6d0bb135039c73e1e1051e9ea6f2f6/daemon/kill.go#L181
2. Build a docker container that captures SIGTERM:
```
cat << EOF > Dockerfile
FROM bash:5.0

COPY killtrapper.sh /

ENTRYPOINT ["/killtrapper.sh"]
EOF
```
```
cat << EOF > killtrapper.sh
#!/usr/bin/env bash

sigterm() {
    echo "caught a signal"
}

trap 'sigterm' QUIT
trap 'sigterm' INT
trap 'sigterm' HUP
trap 'sigterm' TERM

echo "test script started. My PID is $$"
while :; do
    sleep 0.5
done
EOF
```
3. build and run the container `chmod +x killtrapper.sh && docker build -t "killtrapper" . && docker run -it --rm --name "kt" killtrapper`
4. attempt to kill the container: `docker kill kt`
5. command fails without trying "direct kill"
```
% docker kill kt
Error response from daemon: Cannot kill container: kt: foo error
```

**Describe the results you expected:**

if initial docker kill signal fails, fall back to "direct kill" (ie unix kill)

**Output of `docker version`:**

```
dockerd engine is current head of master:
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8a4671fb1f
  Built:            Fri Oct 23 04:07:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683 (expected: de40ad0)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.198-152.320.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.96GiB
 Name: ip-10-0-0-176.us-west-2.compute.internal
 ID: J7BA:BTKN:ZD5S:FWGT:2A2Y:NKTF:DDAJ:QSNA:UE23:L6S2:W7RG:BXBK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

this test was run on an AWS m5.xlarge instance

**Comment by tianon** [comment]
Can you provide a bit more detail on the reproducer?  I followed your steps on a fresh instance of Docker 20.10.6, with your exact copy-pasted `Dockerfile` and `killtrapper.sh`, but I fail to see how it prevents `SIGKILL`?

```console
$ docker build .
Sending build context to Docker daemon  35.84kB
Step 1/3 : FROM bash:5.0
5.0: Pulling from library/bash
339de151aab4: Already exists 
a2080f83c63e: Pull complete 
fc398eb49167: Pull complete 
Digest: sha256:c7f764584976b05c144dc17818c636172e8fe6c0e3525f60faf92378f8fc44ac
Status: Downloaded newer image for bash:5.0
 ---> 334b5571c1de
Step 2/3 : COPY killtrapper.sh /
 ---> 8a62d14f879b
Step 3/3 : ENTRYPOINT ["/killtrapper.sh"]
 ---> Running in 1b772fa44b0d
Removing intermediate container 1b772fa44b0d
 ---> 910ee0cd5d82
Successfully built 910ee0cd5d82
$ docker run -dit --rm --name kt 910ee0cd5d82
6df2851b0ac0e3017f8a9d8e4e1766fd0e1a18c0228fe406c77d025f0b546445
$ docker logs kt
test script started. My PID is 1
$ docker kill kt
kt
$ 
```

**Comment by sparrc** [comment]
It's not possible to capture SIGKILL. The reproduction also requires modifying docker engine to return an error from the sigkilling function (step 1 from the repro steps).

So the point being that you need the container to capture SIGTERM and the daemon to synthetically error on SIGKILL.

We haven't been able to reproduce the case where SIGKILL fails, all we really know is that it can happen. My best guess would be stuck IO but I'm not sure how to reproduce that, hence modifying the daemon to error "synthetically".

**Comment by tianon** [comment]
Aha, that helps -- sorry I missed that bit. :see_no_evil:

**Comment by tianon** [comment]
I wonder if we could synthesize this with an NFS mount (probably "hard") set with a long timeout and disconnecting the server once we start a process that's doing IO to it?  Probably *really* hard to write an actual test for, but IMO it would be really useful if we could at least come up with a non-synthetic reproducer.

**Comment by sparrc** [comment]
I can give that a try but it will probably take a few weeks before I can get to it with work obligations.

I guess I was hoping it wouldn't be necessary as we have had multiple engineers on our team try to reproduce this issue without much luck.

Though rare it does seem that `killPossiblyDeadProcess` can return errors in practice (and in theory of course it can since it has the function signature to do it). When it does error then [this code](https://github.com/moby/moby/blob/master/daemon/kill.go#L141-L162) will never call killProcessDirectly.

Do we need to reproduce if we know the behavior of `killPossiblyDeadProcess` erroring is problematic? If yes then I can work on that but it will mean quite a bit of further delay to this PR and issue.

**Comment by tianon** [comment]
I'm not sure it's _strictly_ necessary (I'll let other maintainers comment about that), but I was hoping if we could find a way to reliably reproduce it, it would help us resolve @cpuguy83's questions as to whether some of that fallback code is actually necessary or superfluous over in #41588. :sweat_smile:

**Comment by sparrc** [comment]
I see, I'm not entirely sure about the zombie process check fallback either. I would think it's possibly not necessary anymore but I didn't want to change that without knowing how to reproduce it.

The zombie process check was added in this PR: https://github.com/moby/moby/pull/40749 (see issue https://github.com/moby/moby/issues/40735). From what I can tell reading the discussion there, it was assumed that the process was already sent a SIGKILL before this check was run, but I think it's possible that the SIGKILL was never sent.
