### ISSUE TITLE
Docker checkpointing still broken

### ISSUE THREAD

**Issue by Dudeldu** [moby/moby#41602]
Is there any progress on fixing checkpointing in runtime v2 (continuing https://github.com/moby/moby/pull/41546) ? 

```
$ make BIND_DIR=. shell
...
$ docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
$ docker checkpoint create looper checkpoint1
time="2020-10-13T00:23:34.572955617Z" level=error msg="resuming exited container from paused state" error="runc did not terminate successfully: container \"c9331dc7c566530183a8a9fb4940058cd989354fd340ccafd90662af05fe544c\" does not exist\n"
INFO[2020-10-13T00:23:34.586458467Z] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2020-10-13T00:23:34.586652537Z] shim disconnected                             id=c9331dc7c566530183a8a9fb4940058cd989354fd340ccafd90662af05fe544c
ERRO[2020-10-13T00:23:34.690462147Z] Handler for POST /v1.30/containers/looper/checkpoints returned error: Cannot checkpoint container looper: image "docker.io/library/busybox": not found 
Error response from daemon: Cannot checkpoint container looper: image "docker.io/library/busybox": not found
```

It seems to be working in containerd, however the interaction with dockerd regarding the image checkpointing messes everything up.

1. Is there anyone actively fixing this?
2. Is there documentation available, especially on how the container checkpointing is supposed to be working (responsibilieties between containerd and dockerd)?

I would otherwise try to look into it, although some kind of starting point would be helpful.

**Comment by Dudeldu** [comment]
> The error happens because containerd started adding the image to the checkpoint, however docker does not use containerd's image store, and thus the error.
> 
> I looked at this briefly to see if I can disbale checkpointing the image data, but didn't find anything.

That's the same result, that I got from my inspections so far. But i traveled through the history of both projects (containerd and dockerd) but couldn't find any change, that might have introduced this unwanted behaviour.

**Comment by Dudeldu** [comment]
Following the call stack, of a checkpoint operation, ends up in the containerd client.
```
 github.com/docker/docker/vendor/github.com/containerd/containerd.(*task).Checkpoint (/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/task.go:426)
 github.com/docker/docker/libcontainerd/remote.(*client).CreateCheckpoint (/go/src/github.com/docker/docker/libcontainerd/remote/client.go:547)
 github.com/docker/docker/daemon.(*Daemon).CheckpointCreate (/go/src/github.com/docker/docker/daemon/checkpoint.go:74)
 github.com/docker/docker/api/server/router/checkpoint.(*checkpointRouter).postContainerCheckpoint (/go/src/github.com/docker/docker/api/server/router/checkpoint/checkpoint_routes.go:24)
 github.com/docker/docker/api/server/router/checkpoint.(*checkpointRouter).postContainerCheckpoint-fm (/go/src/github.com/docker/docker/api/server/router/checkpoint/checkpoint_routes.go:12)
...
```

Here the containerd checkpoint operation is done: 
GetLease -> GetContainerInfo -> PauseContainer -> Checkpoint container-process-tree -> Checkpoint container-image (crash)

This last step, was skipped in older versions (tested with 19.03), since it was guarded by this [if-statement](https://github.com/containerd/containerd/blob/ef79c99576ccbb620b0babe1592e6c9fa5e0929e/task.go#L474) (containerd client):
```go
if cr.Image != "" {
		if err := t.checkpointImage(ctx, &index, cr.Image); err != nil {
			return nil, err
		}
		index.Annotations["image.name"] = cr.Image
}
```

Back then, `cr.Image` used to be empty for docker containers. In the newer versions the variable contains the Image and this way leads to the crash, as containerd is not supposed to administrate images for docker.

We reenabled checkpointing for us, by simply adding the line `cr.Image = ""`. Obviously this isn't a permanent fix, as it would require a docker-specific change in a different project (containerd).

The underlying problem, is that the containerd container store, which sets the `cr` variable, gives back _too much_ information in this case. Previously it filled container related information in the `cr`variable but left out the `Image` field. This somewhat reflects, that containerd is not meant to know docker's images.

So the question is, whether there is really _too much_ information passed to containerd during docker container creation, or is this required somewhere else? 
Can someone help with an answer, so we can think about a way to restrict the passed information.

**Comment by cpuguy83** [comment]
Ok, I see we are setting an image when creating the container. I'm not sure why at the moment.
