### ISSUE TITLE
Docker inspect and API don't have the same data

### ISSUE THREAD

**Issue by OhMyMndy** [moby/moby#41610]
**Description**

The Docker API (which can be called over http) and `docker inspect` do not return the same data.

The information I am looking for are the container network aliases, which is filled for `docker inspect` but is always `null` for the API.

**Steps to reproduce the issue:**
```
script=$(cat <<'END_HEREDOC'
unset DOCKER_HOST;
dockerd &>/dev/null &
apk --no-cache add curl jq &>/dev/null;

docker network create --attachable user_bridge &>/dev/null;
docker run -d --hostname test_container --name test_container --network user_bridge --network-alias alias alpine &>/dev/null sleep infinity;

curl -s --unix-socket /var/run/docker.sock http://localhost/v1.40/containers/test/json | jq '.NetworkSettings.Networks.user_bridge.Aliases';

docker inspect test_container --format '{{ json . }}' | jq '.NetworkSettings.Networks.user_bridge.Aliases'

END_HEREDOC
)

docker run --rm  --privileged docker:19.03-dind ash -c "$script"
```

Output:

```
null
[
  "alias",
  "45302ae0eb1b"
]
```

**Describe the results you received:**
- Only Docker inspect shows the network aliases correctly

**Describe the results you expected:**
- The Docker API should also return the network aliases at http://localhost/v1.40/containers/json

**Output of `docker version`:**

```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker info`:**

_Not relevant since Docker in Docker is used_

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I used Docker in Docker (on Ubuntu 18.04) to create a simple reproducible environment

**Comment by OhMyMndy** [comment]
Docker info
```
Client:
 Debug Mode: false

Server:
 Containers: 35
  Running: 12
  Paused: 0
  Stopped: 23
 Images: 234
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.25GiB
 Name: mandy-work-ubuntu
 ID: QA6G:NFJT:BLIQ:NH7Y:22QD:SGGN:X4ZI:XCWZ:LDJF:PIRV:45AZ:QBKV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Uname: Linux mandy-work-ubuntu 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Is there any other information I can provide from my system?

**Comment by cpuguy83** [comment]
I'm not sure here.
`docker inspect` is calling the exact API that you are curling.
Are you sure you are hitting the same container? I can imagine the field could be omitted if it's empty.

**Comment by OhMyMndy** [comment]
Yes I am sure, you can try to run the example I made in the initial post, ran it on my Ubuntu 18.04 work machine and my Ubuntu 20.04 machine at home (both latest 19.03).

**Comment by OhMyMndy** [comment]
Still the same problem with Docker 20.10

```
script=$(cat <<'END_HEREDOC'
unset DOCKER_HOST;
dockerd &>/dev/null &
apk --no-cache add curl jq &>/dev/null;

docker network create --attachable user_bridge &>/dev/null;
docker run -d --hostname test_container --name test_container --network user_bridge --network-alias alias alpine &>/dev/null sleep infinity;

curl -s --unix-socket /var/run/docker.sock http://localhost/v1.40/containers/test/json | jq '.NetworkSettings.Networks.user_bridge.Aliases';

docker inspect test_container --format '{{ json . }}' | jq '.NetworkSettings.Networks.user_bridge.Aliases'

END_HEREDOC
)

docker run --rm  --privileged docker:20.10-dind ash -c "$script"
```

Output:
```
null
[
  "alias",
  "54df10167067",
  "test_container"
]
```

**Comment by cpuguy83** [comment]
You are hitting the wrong container name in your `curl`

**Comment by cpuguy83** [comment]
Closing since this looks like user error.

User is creating/inspecting a container named `test_container` but the curl is getting the container named `test`.
