### ISSUE TITLE
File not found when executing curl as liveness probe

### ISSUE THREAD

**Issue by mkoziel2000** [moby/moby#41630]
**Description**
Whenever a liveness probe is setup to execute a curl.exe command, it results in a "System cannot find the file specified" in the windows container.  I can find the curl.exe command and execute the probe successfully when I interact with the container via "docker exec"...but it seems the kubernetes initiated probe cannot find the executable.  Is it a permissions thing possibly?  I verified that curl is located in the c:\windows\system32 folder of the container so I don't think its a path visibility problem.

I'm using a docker compose file with the "kompose" tool to transform a locally deployable service into a deployable service on kubernetes.  The liveness probe using that tool can only interpret exec commands, otherwise, I would have taken the "http get" route in the deployment definition for the probe, which works.

**Steps to reproduce the issue:**
1. Create a docker compose file for a windows service using windowsservercore as OS.  Define a healthcheck with the command "curl --fail -s http://myservice/health || exit 1"
2. Run "kompose" tool to create a kubernetes deployment file (which converts healthcheck into liveness probe definition)
3. Deploy into kubernetes containing windows nodes.

**Describe the results you received:**
Dumbing down the healthcheck command to "curl --help" to remove the http endpoint being the issue has resulted in the same outcome.
![image](https://user-images.githubusercontent.com/11468797/98059752-1c18f700-1e05-11eb-9c9c-67dfda29dd92.png)

**Describe the results you expected:**

Liveness probe should succeed

**Additional information you deem important (e.g. issue happens only occasionally):**
Able to "docker exec" into container and run the curl command successfully.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All nodes are running as VMWare VMs.

**Comment by thaJeztah** [comment]
Could you post the output of `docker info` and `docker version` ? 

Unfortunately, there's a lot of "moving parts" in your problem description (kompose, kubernetes). Does the problem only reproduce with kubernetes health checks, or are you able to reproduce the problem with more minimal  reproduction steps using just docker? (e.g., a docker image that has a healtcheck defined https://docs.docker.com/engine/reference/builder/#healthcheck, or `docker run --health-cmd= ..  ...` https://docs.docker.com/engine/reference/run/#healthcheck


The error looks to come from the hcsshim library, which is the library used to connect with the Windows kernel  / API. It could be that the generated health check uses an incorrect format for the command, but it could be something completely else. There are some other reports with similar errors, but unfortunately, the errors returned by the kernel are often quite "generic" and not very descriptive, so similar error messages could be very unrelated (e.g. https://github.com/microsoft/hcsshim/issues/674)

**Comment by mkoziel2000** [comment]
The problem only occurs when the liveness probe is defined in a kubernetes deployment and uses the ExecAction.  The HttpGet seems to work fine when executed from within a K8S environment.

Using straight up docker + docker-compose also works when I used:

healthchecks: 
     test: curl --fail -s http://myservice:12345/health

I tried to use the "runAsUserName" security context with "ContainerAdministrator", "ContainerUser", "NT AUTHORITY\NETWORK SERVICE" and a domain user in the kubernetes deployment def to see if that made a difference as it seem to feel like an access problem...but the resulting error message was the same.

The interesting part here is that if I define the following liveness probe in a K8S deployment....the liveness probe error goes away...but it doesn't flag a problem when I simulate one by changing to a bad URL...rendering the probe as not useful.

docker-compose.yml
healthchecks:
    test: ["cmd","curl","--fail","-s","http://myservice:12345/health"]

resulting kubernetes deployment using kompose:
livenessProbe:
   exec:
     command:
      - cmd
      - curl
      - '--fail'
      - '-s'
      - '-i'
      - 'http://myservice:12345/health'

**Comment by mkoziel2000** [comment]
I think I found the magic combination that makes this work.

I have to define the healthcheck as an array in docker-compose and capitalize the "CMD" element in position 0.  

healthchecks:
test: ["CMD","curl","--fail","-s","http://myservice:12345/health"]

Once done, this results in a livenessProbe of:

livenessProbe:
  exec:
    command:
    - curl
    - '--fail'
    - '-s'
    - '-i'
    - 'http://myservice:12345/health'

This gives me successful probes in K8S.  when I simulate with a bad URL, this gives me the expected probe.  Now I have a universal healthcheck that works in both non-kubernetes and kubernetes deploys using a single docker-compose file.

Included the info and version of docker in case that might reveal why it seems so fickle.

[docker-info.txt](https://github.com/moby/moby/files/5489154/docker-info.txt)
[docker-version.txt](https://github.com/moby/moby/files/5489155/docker-version.txt)

**Comment by thaJeztah** [comment]
Could it be that kompose (?) is doing a case-sensitive compare to check if the first item is `CMD`? Looking at the default difference in the generated livenessProbe; the "bad one" has `cmd` as first item, whereas the "good one" does not.

What happens if you use the array notation, but skip the `cmd` in your array?

**Comment by olljanat** [comment]
@mkoziel2000 based on what you are saying this sounds like bug on kompose so it should be reported to https://github.com/kubernetes/kompose

**Comment by mkoziel2000** [comment]
this was resolved by changing the first parameter to upper case.  It has worked for all the services that we have deployed over the last couple months.
