### ISSUE TITLE
What's the minimum capabilities to update cgroups inside a container

### ISSUE THREAD

**Issue by zackliu** [moby/moby#41632]
**Description**
I'd like to update cgroups inside a container. E.g. create a sub-cgroup inside current container's cgroup. I found cgroups are mounted as 'ro' except I create the container with --privileged. I know using privileged mode it not recommended but I don't find a way to achieve it without privileged mode. 
What's the minimum capabilities to update cgroups inside a container?

**Steps to reproduce the issue:**
1. Execute `docker run -ti ubuntu mkdir /sys/fs/cgroup/memory/subgroup` 

**Describe the results you received:**
mkdir: cannot create directory '/sys/fs/cgroup/memory/subgroup': Read-only file system

**Describe the results you expected:**
Add some capabilities except using privileged mode to make it work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
