### ISSUE TITLE
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: permission denied

### ISSUE THREAD

**Issue by linuxadmin25** [moby/moby#41649]
Hi Team,

```
INFO[2020-11-07T00:58:29.883303900-08:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-11-07T00:58:29.884388500-08:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-11-07T00:58:29.885510400-08:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-11-07T00:58:29.911253300-08:00] [graphdriver] using prior storage driver: overlay2
WARN[2020-11-07T00:58:29.922973100-08:00] Your kernel does not support cgroup memory limit
WARN[2020-11-07T00:58:29.924297700-08:00] Unable to find cpu cgroup in mounts
WARN[2020-11-07T00:58:29.925239300-08:00] Unable to find blkio cgroup in mounts
WARN[2020-11-07T00:58:29.932863400-08:00] Unable to find cpuset cgroup in mounts
WARN[2020-11-07T00:58:29.933757400-08:00] mountpoint for pids not found
INFO[2020-11-07T00:58:29.935128600-08:00] Loading containers: start.
WARN[2020-11-07T00:58:29.956255100-08:00] Could not load necessary modules for IPSEC rules: protocol not supported
WARN[2020-11-07T00:58:29.976717900-08:00] Could not load necessary modules for Conntrack: Running modprobe nf_conntrack failed with message: `modprobe: WARNING: Module nf_conntrack not found in directory /lib/modules/4.4.0-18362-Microsoft`, error: exit status 1
INFO[2020-11-07T00:58:29.983629100-08:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2020-11-07T00:58:29.991130600-08:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2020-11-07T00:58:29.996683900-08:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
INFO[2020-11-07T00:58:29.996728100-08:00] stopping healthcheck following graceful shutdown  module=libcontainerd
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: permission denied
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$
```

Additional information :: 

```console
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```console
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 10
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 6.007GiB
 Name: docker-desktop
 ID: JP4M:MDR6:MP4S:XEPE:X3AA:XQDU:WMN6:XHBZ:MTH2:VEP2:7CO7:43Y2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$
```

```console
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$ uname -a
Linux DESKTOP-S3H1OVS 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
tanmayroot@DESKTOP-S3H1OVS:/var/tmp/dock$
```

I am running on Windows 10, WSL2[Ubuntu interface]

Note : I have gone through the previous comments related to this issue but none of them are solving my issue, all cases are closed thus opening a new one.

**Comment by thaJeztah** [comment]
> I am running on Windows 10, WSL2[Ubuntu interface]

Did you install manually on WSL2, or are you running Docker Desktop?

**Comment by killers78** [comment]
I have the same issue !!!

sudo dockerd --iptables=false &

INFO[2020-11-24T20:14:47.165933600-03:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2020-11-24T20:14:47.166605700-03:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2020-11-24T20:14:47.178308200-03:00] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2020-11-24T20:14:47.191165200-03:00] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2020-11-24T20:14:47.203388400-03:00] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2020-11-24T20:14:47.204166800-03:00] containerd successfully booted in 0.202269s
INFO[2020-11-24T20:14:47.230651000-03:00] parsed scheme: "unix"                         module=grpc
INFO[2020-11-24T20:14:47.231379000-03:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-11-24T20:14:47.231968600-03:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-11-24T20:14:47.232677500-03:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-11-24T20:14:47.237081000-03:00] parsed scheme: "unix"                         module=grpc
INFO[2020-11-24T20:14:47.237679300-03:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-11-24T20:14:47.238283600-03:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-11-24T20:14:47.239028400-03:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-11-24T20:14:47.290389900-03:00] [graphdriver] using prior storage driver: overlay2
WARN[2020-11-24T20:14:47.351257000-03:00] Your kernel does not support cgroup memory limit
WARN[2020-11-24T20:14:47.351834000-03:00] Unable to find cpu cgroup in mounts
WARN[2020-11-24T20:14:47.352377100-03:00] Unable to find blkio cgroup in mounts
WARN[2020-11-24T20:14:47.352927400-03:00] Unable to find cpuset cgroup in mounts
WARN[2020-11-24T20:14:47.353541800-03:00] mountpoint for pids not found
INFO[2020-11-24T20:14:47.355311200-03:00] Loading containers: start.
WARN[2020-11-24T20:14:47.576842400-03:00] Could not load necessary modules for IPSEC rules: protocol not supported
WARN[2020-11-24T20:14:47.636088400-03:00] Could not load necessary modules for Conntrack: Running modprobe nf_conntrack failed with message: `modprobe: WARNING: Module nf_conntrack not found in directory /lib/modules/4.4.0-18362-Microsoft`, error: exit status 1
INFO[2020-11-24T20:14:47.640970200-03:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2020-11-24T20:14:47.660093700-03:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2020-11-24T20:14:47.662490900-03:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2020-11-24T20:14:47.662521300-03:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: permission denied

**Comment by chodankarcc** [comment]
I am facing same issue, Did you have any resolution to this?

**Comment by findusl** [comment]
Same issue. Manually installed on WSL2

**Comment by findusl** [comment]
I removed the exception by running wsl as administrator. I got the tip here: https://dev.to/badsamaritan/comment/1l69f

**Comment by findusl** [comment]
And turns out my wsl was still version one even though I had set the default version to 2. Not sure why, but make sure to check your wsl version with `wsl -l -v`

**Comment by sam-thibault** [comment]
Looks like this is working based on latest comments.  I will close this.
