### ISSUE TITLE
Feature request: Set default registry

### ISSUE THREAD

**Issue by al45tair** [moby/moby#41663]
I'm aware that this has been discussed and discarded in the past on the basis that it will "break the global namespace".

**However**, Docker Hub's image pull restrictions also break that global namespace, and the simplest and most reasonable way to deal with them for many organisations is to put a caching Docker registry between their users and Docker Hub. The problem with doing this is that to use the caching registry requires users to explicitly specify the registry in their image pulls.

This creates two issues; the first is that users may forget to include the registry path in their pull requests, leading to exhaustion of the available pull requests. The second is that there are systems where the image name is provided by a third party (for instance a Helm chart, or the tests in a third-party project), where customising the image names is not necessarily a practical option.

An additional organisational benefit of interposing a private registry using a default registry setting is that it prevents inadvertent pushing to the global Docker Hub registry by staff.

Docker is adding these restrictions in order to avoid people placing undue load on Docker Hub, and caching registries are a sensible solution to that problem. But in order for them to be a properly viable option, Docker *needs* support for a default registry setting.

**Comment by thaJeztah** [comment]
> The problem with doing this is that to use the caching registry requires users to explicitly specify the registry in their image pulls.


How did you configure the caching registry? If a registry is configured as to pull-through mirror, this should be transparent

**Comment by al45tair** [comment]
@thaJeztah You misunderstand. Let's say our registry is called registry.example.com. Users have do explicitly do e.g.

    docker pull registry.example.com/ubuntu:latest

in order to use it as a cache. They can't just do

    docker pull ubuntu:latest

and have it automatically use our registry, because Docker Hub (registry-1.docker.io) is hard-coded as the default registry.

**Comment by thaJeztah** [comment]
That's what a pull-through mirror does; https://docs.docker.com/registry/recipes/mirror/

**Comment by al45tair** [comment]
@thaJeztah Ah, I hadn't spotted the --registry-mirror option. That's potentially useful, thank-you. I suspect this solves the problem we're after solving, so I'll close this Issue.

**Comment by thaJeztah** [comment]
You're welcome! Hope it all works with this 👍
