### ISSUE TITLE
SSOT: release notes

### ISSUE THREAD

**Issue by tnir** [moby/moby#41662]
## Description

https://github.com/moby/moby/blob/af34b94a78a194ae9bce48a200241d08c05b7187/CHANGELOG.md has been too obsolete for about 3 years, it should has links to https://docs.docker.com/engine/release-notes/ to achieve SSOT.

## TODO

Make all the release notes single-source of truth.

**Comment by thaJeztah** [comment]
closing as this file was removed in https://github.com/moby/moby/pull/44466
