### ISSUE TITLE
Creating seccomp filter for unnamed syscall entries

### ISSUE THREAD

**Issue by staticfloat** [moby/moby#41671]
I am trying to create a seccomp filter to allow usage of [`rr`](https://github.com/mozilla/rr) within a docker container.  `rr` uses unnamed syscalls numbered 1000-1020 or so; how can I enable a range of numeric syscalls with a docker seccomp filter?

The seccomp filter that I have assembled so far looks like this: https://github.com/staticfloat/julia-docker/blob/master/buildworker/rr_profile.json

Trying to run `rr` inside of `Docker` with this profile enabled, fails and tells me to allow syscall numbers over 1000.  Here's a MWE:

## Dockerfile
```Dockerfile
FROM debian

RUN apt update -y && apt install -y curl
WORKDIR /app
RUN curl -L 'https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/download/rr-v5.3.2%2B0/rr.v5.3.2.x86_64-linux-gnu-cxx11.tar.gz' | tar zx
RUN curl -L 'https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0%2B1/capnproto.v0.7.0.x86_64-linux-gnu.tar.gz' | tar zx

CMD ["/app/bin/rr", "record", "/bin/sh", "-c", "ls"]
```

## Build process
```
curl -L -O 'https://raw.githubusercontent.com/staticfloat/julia-docker/master/buildworker/rr_profile.json'
docker build . -t rr_test
```

## Output
```
$ docker run -ti --cap-add SYS_PTRACE --security-opt seccomp=./rr_profile.json rr_test
rr: Saving execution to trace directory `/root/.local/share/rr/sh-0'.
/workspace/srcdir/rr/src/preload/syscallbuf.c:775: Fatal error: Failed to communicated with rr tracer.
Perhaps a restrictive seccomp filter is in effect (e.g. docker?)?
Adjust the seccomp filter to allow syscalls above 1000, disable it,
or try using `rr record -n` (slow).
```

Ideally, there would be a mechanism by which I can specify a range of unnamed (numbered) syscalls to allow through the seccomp filter.

I have reproduced this on 64-bit Linux glibc machines running both docker 19.03.8 and 17.05.0-ce.

**Comment by Keno** [comment]
My suggestion would be a patch to runc like this:
```go
@@ -175,11 +176,13 @@ func matchCall(filter *libseccomp.ScmpFilter, call *configs.Syscall) error {
                return errors.New("empty string is not a valid syscall")
        }
 
-       // If we can't resolve the syscall, assume it's not supported on this kernel
-       // Ignore it, don't error out
-       callNum, err := libseccomp.GetSyscallFromName(call.Name)
-       if err != nil {
-               return nil
+       if callNum, err := strconv.Atoi(v); err != nil {
+               // If we can't resolve the syscall, assume it's not supported on this kernel
+               // Ignore it, don't error out
+               callNum, err := libseccomp.GetSyscallFromName(call.Name)
+               if err != nil {
+                       return nil
+               }
        }
 
        // Convert the call's action to the libseccomp equivalent
```
Which would allow syscalls to be specified numerically in the profile json.

**Comment by thaJeztah** [comment]
There's some discussion around this in https://github.com/opencontainers/runc/issues/2151, but this likely would require changes in the runtime specification (also see https://github.com/opencontainers/runtime-spec/issues/972).

Given that docker implements the specification, I don't think this can be resolved in this repository until the specs facilitate this.

I'm closing this ticket for that reason, but feel free to continue the conversation
