### ISSUE TITLE
The strange folder relevant to docker: /opt/containerd.

### ISSUE THREAD

**Issue by hongyi-zhao** [moby/moby#41672]
Hi,

On Ubuntu 20.04, I noticed the following folder:

```
werner@X10DAi:/opt$ sudo ls -la /opt/containerd
total 16
drwx--x--x  4 root   root   4096 Aug 23 22:08 .
drwxr-xr-x 10 werner werner 4096 Nov 14 08:20 ..
drwx--x--x  2 root   root   4096 Aug 23 22:08 bin
drwx--x--x  2 root   root   4096 Aug 23 22:08 lib
```

Is it created by docker? What is the purpose of its existence? Can I delete it safely?

Regards,
HY

**Comment by elboulangero** [comment]
It's created at startup, either by docker or containerd. Wonder why. indeed, I was asking myself the same question.

**Comment by elboulangero** [comment]
It's created by containerd, and this behavior was introduced a while ago: https://github.com/containerd/containerd/commit/1537f31381b946f395348d9891602a1e4a2c1070

**Comment by thaJeztah** [comment]
Yes, looks like that path is related to https://github.com/containerd/containerd/pull/2518, which allows containerd to install additional binaries through `ctr install ...`. I see the path is created when that containerd plugin is initialised on startup of containerd (https://github.com/containerd/containerd/blob/d21f0f116e29e498eeebf8440e9f43a06cf39cfc/services/opt/service.go#L44-L45); perhaps it's better to open a ticket for this in the containerd issue tracker if you want to have more details

**Comment by sebma** [comment]
Can these `/opt/containerd/bin` and `/opt/containerd/lib` empty directories be safely deleted ?

**Comment by thaJeztah** [comment]
It's probably ok to remove them, but they will be recreated when containerd restarts.

Given that this is an issue in containerd, I'll close this ticket here, but would recommend opening a ticket in the containerd issue tracker; https://github.com/containerd/containerd/issues
