### ISSUE TITLE
Select location of Hyper-V VMs used by Docker for Windows

### ISSUE THREAD

**Issue by rdeterre** [moby/moby#41694]
Hi,

This ticket was originally created on [docker/for-win](https://github.com/docker/for-win/issues/9557), but I was informed that the right place for it would be here.

I would like to have Docker for Windows use a different hard drive than the system disk on my computer. I have set "data-root" and "exec-root" in my docker daemon configuration to the new hard drive, but when docker runs, I see in the resource monitor that the most accessed file is under "C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM".

I modified the default folder for "Virtual Hard Disks" and "Virtual Machines" under "Hyper-V Settings" in the "Hyper-V Manager" to point to the right disk, but this did not make any difference.

I also tried forcing the isolation to either "hyperv" or "process" in the Docker daemon configuration, but the result was the same:

"exec-opts": ["isolation=hyperv"]

Is it possible for me to specify where the "Container Utility VM"s should be ?

**Steps to reproduce the issue:**

  1. Use the following JSON docker daemon configuration file:
      ```
      {
        "registry-mirrors": [],
        "insecure-registries": [],
        "debug": false,
        "experimental": false,
        "data-root": "d:\\docker",
        "exec-root": "d:\\docker-exec"
      }
      ```
  2. Change "Virtual Hard Disks" and "Virtual Machines" under "Hyper-V Settings" in the "Hyper-V Manager" to point to "d:\hyper-v\virtual-hard-disks" and "d:\hyper-v\virtual-machines" respectively.
  3. Run docker images

**Describe the results you received:**

Open the Resource Monitor then go to the "Disk" tab. Under "Disk Activity", notice that the most written to/read from file is under "C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM"

**Describe the results you expected:**

The files accessed most often by docker should be on the "d:" drive.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 26
  Running: 0
  Paused: 0
  Stopped: 26
 Images: 58
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.85GiB
 Name: docker-desktop
 ID: PGBP:N5QQ:GCIY:XHCZ:KORD:G5OX:BLVC:5BNA:J4FT:QUE3:EDNJ:7KWU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 38
  Goroutines: 43
  System Time: 2020-11-18T19:11:29.5652641Z
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Are you running Windows or Linux containers? If I see the output of your docker info, it looks like you're running Linux containers. 

In that case (with docker desktop), the daemon is likely running on WSL2, and the storage location for the daemon should (probably) only affect the storage location within the WSL2 VM.

I suspect the Hyper-V VM's your see would be the VMs used by WSL2. Not sure if there's a config to make WSL2 use a different drive

@stefanscherer @simonferquel you probably know more about this to keep me honest 🤔😂

**Comment by rdeterre** [comment]
Thanks for your quick response. Apologies, I'm running Windows containers, but I ran the `docker version` and `docker info` commands on the wrong machine 🤦. Here are the output of these commands from the right computer this time:

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:14:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.1198)
 OSType: windows
 Architecture: x86_64
 CPUs: 56
 Total Memory: 47.7GiB
 Name: orme
 ID: LSEN:M6FT:LLQV:F7GJ:CHFG:QKVW:ULBA:OXVW:ZZTX:OS2Q:FBSK:7OHM
 Docker Root Dir: D:\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by TBBle** [comment]
I believe this location is owned and managed by the vmcompute component in Windows, not Docker. I _suspect_ it's not possible to change its location through configuration, as it's hard-coded to `%PROGRAMDATA%\Microsoft\Windows\Hyper-V\Container Utility VM` inside vmcompute.exe.

Your best bet to will be to move the data somewhere else and use a junction point to redirect that directory to the 'somewhere else'. I can't guarantee that will work though.

That said, if your setup allows it, i.e. you're using container images based on a 10.0.18363 base image, 'process' isolation mode (instead of 'hyperv' isolation mode) should mean it won't use those Container Utility VMs at all. Since you mentioned that changing the daemon config didn't work, try it on the `docker` command line with `--isolation=process`.

**Comment by rdeterre** [comment]
Ok, this explains why changing settings in the Hyper-V Manager makes no difference. I can also confirm that the "problem" is solved when using `--isolation=process`; I see no heavy read/writes to files under `Container Utility VM`.

Thanks for your help ! I'll close the issue now.

**Comment by thaJeztah** [comment]
So, IIUC, the `"exec-opts": ["isolation=hyperv"]` option in `daemon.json` does not take effect (to set the default isolation?). If so, might be worth opening a ticket for that so that we can investigate (could be a documentation issue, or a bug in the daemon configuration-file handling code)
