### ISSUE TITLE
Allow dockerd to store registry credentials 

### ISSUE THREAD

**Issue by steveazz** [moby/moby#41706]
## Problem

With the new [Docker Hub limits](https://docs.docker.com/docker-hub/download-rate-limit/), users are required to login Docker Hub when using [Docker in Docker](https://github.com/docker-library/docker/blob/b1d2628005e12e79079c025c3653cba248d6f264/19.03/dind/Dockerfile) workflow so that users can build images. Building images usually involves pulling base images like `alpine` from Docker Hub.

Most of the time, these kinds of builds happen inside of a CI system, in multiple places. Right now users would have to remember to add `docker login` manually for every job that they run, this can be error-prone, tedious, and requires extra education/documentation for users writing **every** pipeline configuration. This also brings fragmentation to the CI system because credentials need to be specified in multiple projects/repositories/jobs which can be troublesome to rotate secrets, prevent leaking the secrets, and monitoring of those secrets.

The ideal scenario would be that you set this once somewhere, most likely by an administrator of the CI system so that it's transparent for the users that they need to login into the registry for Docker in Docker builds to prevent any rate limits.

## Proposal

*Originally an issue was opened in https://github.com/docker-library/docker/issues/272 but we [discussed](https://github.com/docker-library/docker/issues/272#issuecomment-730772188) that this might make more sense inside of `moby/moby`.*

Have `dockerd` configured so it stores registry credential and use the credentials stored inside of `dockerd` config (`/etc/docker/daemon.json`). If credentials for that registry are specified by the docker client, use those credentials, the `dockerd` credentials should only be used as a fallback.

**Comment by thaJeztah** [comment]
I don't think the daemon should store these credentials, however, there's some discussion around this in https://github.com/moby/moby/issues/38591, which is a proposal for an alternative solution that doesn't require configuring the daemon with specific credentials.

If this is to prevent hitting rate limits, then configuring a pull-through mirror (for public images) may be a better solution if you don't want to require clients to authenticate (see https://docs.docker.com/registry/recipes/mirror/)

**Comment by cpuguy83** [comment]
I don't think this is what we want. Global credentials is highly problematic and promotes bad practices.

As a registry user, I don't want to grant access to a single identity controlled by someone else, which also grants access to every other user of the system.

As a CI admin, I don't want to have access across repos I don't really need access to.

As a registry admin, I want to see who is pushing/pulling, contact users who are abusing the service, and be able to audit access.

**Comment by thaJeztah** [comment]
let's close this one in favour of https://github.com/moby/moby/issues/38591 to discuss enhancements around authentication

**Comment by steveazz** [comment]
Thank you folks for being quick on discussing this!
