### ISSUE TITLE
Enable IPv6 by default

### ISSUE THREAD

**Issue by ruben-herold** [moby/moby#41703]
hi,

why not enable IPv6 as default. Docker could use some space out of fc00::/7 and die NAT of host has IPv6 enabled. 
Especially on Centos8 with  Docker 20 and firewalld this should be no problem.

**Comment by bsousaa** [comment]
This is configurable in the daemon config: https://docs.docker.com/config/daemon/ipv6/ but we don't have plans, at the moment, to switch as default.
