### ISSUE TITLE
BuildKit cache mount does not take effect with --no-cache option

### ISSUE THREAD

**Issue by idzikovsky** [moby/moby#41715]
**Description**

I'm using BuildKit fronted to utilize `--mount=type=cache` and it seems like it take no effect when building images with `--no-cache` option.

**Steps to reproduce the issue:**
I have the following content in Dockerfile:
```
# syntax=docker/dockerfile:1.1.7-experimental
FROM centos:centos7 as builder

# ...
RUN --mount=type=cache,id=mvncache,target=/root/.m2 \
    mvn clean package ...
    # ...
```
With the following command to build image:
```
export DOCKER_BUILDKIT=1
docker build --no-cache . -t ...
```

**Describe the results you received:**
And after build finished I do able to see that I have newly created cache with `type=exec.cachemount` with near 1.5GiB of data in output of `docker system df -v` in Build cache section, but when I try to build image again (or even build another image in the same way), that cache got deleted, new empty cache appears and all maven artifacts downloading once more.
Also, I've tried to explicitly disable Builder GC as it's documented in https://github.com/docker/cli/issues/2325 (however I assume GC is disabled by default).

**Describe the results you expected:**
I remember that when I initially added this feature in our project ~ 1.5 years ago it worked fine and build of project took ~12 minutes instead of 45 :slightly_smiling_face:
Or this is expected behavior with `--no-cache` option now?

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 16
  Paused: 0
  Stopped: 17
 Images: 17
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.05GiB
 Name: ivanpc
 ID: VYW4:DOGX:V7RG:MG6R:XXO5:GD3O:KOM2:ICLN:4JA3:YWLR:C4AE:GMDQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: idzikovsky
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  10.2.14.44:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
This sounds like something that may have been a bug originally / unexpected to have cache persist if `--no-cache` is specified (not sure though, so I would have to ask)

Is there a specific reason you're specifying `--no-cache`, if you actually want the cache to be used?

**Comment by idzikovsky** [comment]
I thought that the goal of `--no-cache` is to disable layer caching only.
I can't avoid using `--no-cache` as in this case we don't run `docker build` in projects source directory, but rather doing `RUN git clone ...`, so without `--no-cache` I would not be able to get the latest version of the code as result of that `RUN git clone ...` would be taken from cache.

**Comment by thaJeztah** [comment]
> I thought that the goal of `--no-cache` is to disable layer caching only.

Yes, I think the definition (and thus expectation) may be somewhat under-specified.

I _do_ think it makes sense to invalidate cache-mounts if `--no-cache` is specified, and to start the build "from scratch", including building up the cache. Not invalidating cache mounts could influence the build (for example, I know that Golang may produces unexpected results if CGO is used, and cache is not invalidated).

That said, I understand your use-case to have a "pre-warmed" cache, but still force the `RUN` to be triggered.

From your description, I _think_ the "problem" is that source-code and Dockerfile are separated (and no option to include the Dockerfile in the source repository?).

Ideally, the Dockerfile would be in source-control together with the source, to "tie them together", which would give a single reference to get both the source-code that was used to build _and_ the Dockerfile, making the image's build more deterministic. Using `git clone` without a reference also makes the build non-deterministic (the Dockerfile itself does not describe what commit/reference was used for the build).

Another option would be to build directly from a remote git repository and specify an (alternative) Dockerfile from `stdin`, however, unfortunately BuildKit currently does not support this option (see https://github.com/moby/moby/issues/38254)

For your case, I would recommend trying to make the build more deterministic; this would automatically invalidate the cache for the `RUN`, and make the build more reproducible.

For example;

```dockerfile
FROM golang:1.15
# default repository, but can be overridden with --build-arg
ARG GIT_REPO=https://github.com/my-org/my-repo.git

# git-commit (optional) to build from
ARG GIT_COMMIT

# git reference to build from; if no GIT_COMMIT is specified, builds from master (but may use cache)
ARG GIT_REF=${GIT_COMMIT:-master}

# preserve source-repo and revision as metadata in the image
# see https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#pre-defined-annotation-keys
LABEL org.opencontainers.image.source="${GIT_REPO}"
LABEL org.opencontainers.image.revision="${GIT_REF}"

WORKDIR /src

# Clone the source (adjust for your use-case ':-))
RUN git init . \
 && git remote add origin "${GIT_REPO}" \
 && git fetch --depth 1 origin "${GIT_REF}" \
 && git checkout -q FETCH_HEAD

# further steps here
```

The above Dockerfile (without passing any build-args), would do a (shallow) clone of `https://github.com/my-org/my-repo.git`, and build from head of the "master" branch. Obviously, this would cause re-building the Dockerfile to use the existing cache, so to force a rebuild, `--no-cache` would be needed.

To make the build deterministic _and_ to invalidate the cache for the `RUN` step, pass build-args for the (repository and) git commit to build from;

```bash
export GIT_REPO=https://github.com/moby/moby.git
export GIT_REF=master
export GIT_COMMIT="$(git ls-remote --refs "${GIT_REPO}" "${GIT_REF}" |  awk '{print $1}')"

docker build --tag "myorg/myimage:git-${GIT_COMMIT}" --build-arg GIT_REPO --build-arg GIT_COMMIT .

[+] Building 11.7s (7/7) FINISHED
 ..
 => => writing image sha256:bf3d7d84a22a5027d15af678365a13f9c54b10c7e9b25cb5e23be15de80b6f5a  0.0s
 => => naming to docker.io/myorg/myimage:git-e1bba7456d9902d04eec8c402f852d0ae17d123c         0.0s
```

Added benefit is that the image-metadata now includes the repository and commit that the image was built from;

```bash
docker inspect --format='{{ json .Config.Labels}}' docker.io/myorg/myimage:git-e1bba7456d9902d04eec8c402f852d0ae17d123c | jq .
{
  "org.opencontainers.image.revision": "e1bba7456d9902d04eec8c402f852d0ae17d123c",
  "org.opencontainers.image.source": "https://github.com/moby/moby.git"
}
```

And repeated builds will be fully cached, unless the `GIT_COMMIT` changes;

```bash
export GIT_REPO=https://github.com/moby/moby.git
export GIT_REF=master
export GIT_COMMIT="$(git ls-remote --refs "${GIT_REPO}" "${GIT_REF}" |  awk '{print $1}')"

docker build --tag "myorg/myimage:git-${GIT_COMMIT}" --build-arg GIT_REPO --build-arg GIT_COMMIT .

[+] Building 0.3s (7/7) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 37B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => [internal] load metadata for docker.io/library/golang:1.15
 => [1/3] FROM docker.io/library/golang:1.15
 => CACHED [2/3] WORKDIR /src
 => CACHED [3/3] RUN git init .  && git remote add origin "https://github.com/moby/moby.git"  && git fetch --depth 1 origin "e1bba7456d9902d04eec8c402f852d0ae17d123c"  && git checkout -q FETCH_HEAD  0.0s
 => exporting to image
 => => exporting layers
 => => writing image sha256:bf3d7d84a22a5027d15af678365a13f9c54b10c7e9b25cb5e23be15de80b6f5a
 => => naming to docker.io/myorg/myimage:git-e1bba7456d9902d04eec8c402f852d0ae17d123c
```

**Comment by idzikovsky** [comment]
Thank you for detailed response.
Now I agree that it makes sense that the point of `--no-cache` option is to start build from scratch.
And it seems like it had no effect on `--mount=type=cache` some time ago was really some kind of bug.
I familiar with idea of passing git commit as an option to prevent taking some steps from cache, and I think that I'll proceed with this solution.
However sometimes its not enough, for example when I want to use `--mount=type=cache` with using base image of distributive like `centos:centos8` (not the CentOS Vault) and want to have all packages installed of the latest version, so in this case I still need to have `--no-cache` and simply passing git commit as an option would not be enough (for now the only possible solution for this is a trick which consists in pass something like timestamp argument that I'd use in some command at the beginning of Dockerfile). 
But that's another story for another time:)

**Comment by Clete2** [comment]
This issue has been plaguing me for the past few days. Without the workaround @idzikovsky mentioned, how is it possible to clear BuildKit cache?

All my attempts to clear the cache have been fruitless. When I do a buildkit prune it finds nothing to clean. Yet still my builds are all cached. Has anyone figured out how to clear it out?

MacOS Big Sur

**Comment by couling** [comment]
Likewise this issue is really bugging me.  This really undermines the usefulness of `--mount=type=cache`.  If I re-run a build at a specific commit I want to be able to get the latest versions of dependent packages (`yum`, `apt`, `pip`, `maven`, ...).

Adding build arguments to achieve this just makes the build more complicated, making CI templates less useful and making each project more difficult to just pick up and build.  Binding it to the git commit doesn't poison the layer cache when re-running.

It would be great if buildkit had a way to specifiy a step must not be cached.  Then `--mount=type=cache` could always be coupled with a "do not cache this step".
