### ISSUE TITLE
Non-blocking default for log drivers?

### ISSUE THREAD

**Issue by danieladams456** [moby/moby#41714]
**Description**
The default log driver mode of `blocking` causes containers not to start during an AWS CloudWatch outage.  I was wondering if there were any plans or concerns around switching the default log driver mode to `non-blocking` in a future.

When #28762 was implemented in 2017 it was optional (and #36522 for awslogs specifically in 2018).  Has there been enough proving out at this point it could be made the default?

**Steps to reproduce the issue:**
1. default log driver mode
2. CloudWatch outage
3. containers won't start

**Describe the results you received:**
```
failed to initialize logging driver: failed to create Cloudwatch log stream: SerializationError: 503 Service Unavailable status code
```

**Describe the results you expected:**
I expected the default to be `non-blocking` which would allow the container to start in event of CloudWatch unavailability.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens during unavailability of remote API.

**Output of `docker version`:**

```
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560
 Built:             Thu Jul 25 20:59:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       f660560
  Built:            Thu Jul 25 20:57:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

On premise

**Comment by cpuguy83** [comment]
I don't think we'd change the default, but you can set the default options at the daemon level.

**Comment by danieladams456** [comment]
Thank you for your response @cpuguy83.
