### ISSUE TITLE
unable to configure the Docker daemon with file /etc/docker/daemon.json

### ISSUE THREAD

**Issue by z760284582** [moby/moby#41725]
**Description**

i  change the kernel name when compiling kernel by setting CONFIG_LOCALVERSION
then i could not use docker:(
why?

**Steps to reproduce the issue:**
1.docker ps
Cannot connect to the Docker daemon at unix://var/run/docker.sock.Is the docker daemon running?
2.systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
3.systemctl status docker.service

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─kata-containers.conf
   Active: failed (Result: exit-code) since Sat 2020-11-28 14:59:08 CST; 7s ago
     Docs: https://docs.docker.com
  Process: 1631 ExecStart=/usr/bin/dockerd --add-runtime kata-runtime=/usr/local/bin/kata-runt
 Main PID: 1631 (code=exited, status=1/FAILURE)
      CPU: 100ms
```

4.dockerd

```
WARN[0000] Running experimental build                   
Failed to set umask: expected 0022, got 0044
```

5.dockerd -D -l debug
```
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: debug: (from flag: true, from file: true), log-level: (from flag: debug, from file: debug)
```

6./etc/docker/daemon.json
```
{
   "experimental":true,
   "registry-mirrors": ["https://harbor.sh.deepin.com"],
   "storage-driver": "overlay2",
   "debug":true,
   "log-level":"debug"
   }
```

**Describe the results you received:**
docker ps
Cannot connect to the Docker daemon at unix://var/run/docker.sock.Is the docker daemon running?
**Describe the results you expected:**
docker ps
show docker status
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
17.06.2-ce
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix://var/run/docker.sock.Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This is the error;

```
the following directives are specified both as a flag and in the configuration file: debug: (from flag: true, from file: true), log-level: (from flag: debug, from file: debug)
```

When setting configuration options for the daemon, those options should be _either_ specified using a flag (e.g. `dockerd --debug`) _or_ through the daemon.json configuration file.

I suspect one of your systemd unit-files passes `--debug` as flag in the `ExecStart`.


Also be aware that docker 17.06 has reached EOL more than three years ago, is unmaintained, and has unpatched vulnerabilities; I'd highly recommend considering to update to a maintained version.

Let me close this ticket as it doesn't look like a bug, but feel free to continue the conversation

**Comment by Olixc** [comment]
using dockerd solve the issue for me.
