### ISSUE TITLE
Healthcheck blocks container startup (network)

### ISSUE THREAD

**Issue by kolbma** [moby/moby#41726]
**Description**

If I use (swarm) containers with health-check enabled and the first running health-check doesn't `exit 0`, Docker isn't initializing the network of the container. At least **DNS** isn't working.  
So I've tried to use the `start_period: 120s` for the health-check, but it doesn't change anything. The first health-check needs to exit with 0 or the container won't bring up the network.

I have a sleep loop in my entrypoint which is waiting for the network to be ready. It does dns lookups for service names and breaks out of the sleep loop when there is success. There was never success in `exit 1` case. After 3 failing health-checks which is about 1.5 minutes after start the container is restarted.

So to enable health-checks I've to exit with 0 in the health-check script during the 1st minute after start. For the network to be fully available in the container the entrypoint scripts loops about 10 seconds. Why this needs so many seconds to be available?

As a workaround I'm using the timestamp of a file which is `touch`ed in the beginning of entrypoint script.  
But this is annoying and it shouldn't matter for the startup of the container if the return code of the first health-check is 0 or 1.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: hkcxhfi1snjbbamqurig9w2f7
  Is Manager: true
  ClusterID: sj8v28zxwbtsh6bgwnshbhnr4
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: xxxx
  Manager Addresses:
   xxxx
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.894GiB
 Name: xxxx
 ID: xxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Comment by thaJeztah** [comment]
I think this is expected; docker swarm does not resolve services/tasks that are not (yet) healthy. Could you describe your use-case a bit more in depth?

> I have a sleep loop in my entrypoint which is waiting for the network to be ready

Does that mean your entrypoint depends on wether or not the service can be resolved through DNS?

**Comment by kolbma** [comment]
Yes, there are multiple networks attached and I need to know the right ip address I can bind a daemon to.
So that only a specific network can access the daemon.  
I find the local ip address via the network of the service ip and configure the daemon to listen only on the device of this local ip.  
It would be simpler if you could be sure, that the order of specified networks during deployment would always be the order of  network devices. So 1st configured network is assigned to eth0, 2nd network eth1, ..., but I can't find any documentation about this.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
