### ISSUE TITLE
host network: Link not found

### ISSUE THREAD

**Issue by doublewinter0** [moby/moby#41730]
when I run
`sudo docker run --rm --network host --name box -it busybox sh`
then docker says:
**docker: Error response from daemon: failed to create default sandbox: Link not found.**

If I use none or bridge network, it works.

**Docker version 19.03.13-ce, build 4484c46d9d**
**OS: Arch Linux x86_64**
**Kernel: 5.9.9-arch1-1**

**Comment by thaJeztah** [comment]
Could you provide the full output of `docker version` and `docker info` ?

Note that docker does not provide packages for Arch Linux, and (from the output you provided), this looks to be a build of docker that's maintained by the Arch Linux packagers. Arch Linux, being a "bleeding edge" distribution is known to be somewhat problematic, and we frequently see (kernel) updates cause issues, so it may be worth reporting this in the Arch Linux issue tracker.

**Comment by doublewinter0** [comment]
> Could you provide the full output of `docker version` and `docker info` ?
> 
> Note that docker does not provide packages for Arch Linux, and (from the output you provided), this looks to be a build of docker that's maintained by the Arch Linux packagers. Arch Linux, being a "bleeding edge" distribution is known to be somewhat problematic, and we frequently see (kernel) updates cause issues, so it may be worth reporting this in the Arch Linux issue tracker.

Thank you!

I tried on my Debian 10, and the problem still exists.

**OS: Debian GNU/Linux 10 (buster) x86_64**
**Kernel: 4.14.129-bbrplus**

---
**docker version:**
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

---

**docker info:**
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.129-bbrplus
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 501.6MiB
 Name: erdong.ren
 ID: MYVK:O6LP:VSK5:CW5L:CMCW:KKTG:N2LK:QEBD:X3TD:TZBD:KBMU:C4ZV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

---

Any suggestions will be appreciated!

**Comment by thaJeztah** [comment]
Hm, no direct ideas; some things I notice;

```
Kernel Version: 4.14.129-bbrplus
```

I'm not familiar with that kernel note that we only support/test on the official distro kernels; custom kernels _may_ work, but we don't test on those. You can run the check-config script (which does some rudimentary checks) to see if anything stands out; https://github.com/moby/moby/blob/master/contrib/check-config.sh

Another possible issue is memory; 

```
Total Memory: 501.6MiB
```

500Mb may be quite low to run docker, containerd, runc _and_ your containers; it _may_ work, but it's quite likely you may be running onto memory issues (which _could_ also be related to weird errors, such as the one you posted)


Finally, it may be worth starting the daemon with debug enabled and to check daemon logs; assuming you don't have a `daemon.json` configuration file yet (https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file), you can create one with `debug` set to `true`;

```bash
mkdir -p /etc/docker/
echo '{"debug":true}' > /etc/docker/daemon.json
```

After that, restart the daemon;

```bash
sudo systemctl restart docker
```

Note that debug logging produces a _lot_ of logs, some of which may contain sensitive data, so best to disable it after you are done debugging.

**Comment by doublewinter0** [comment]
> Hm, no direct ideas; some things I notice;
> 
> ```
> Kernel Version: 4.14.129-bbrplus
> ```
> 
> I'm not familiar with that kernel note that we only support/test on the official distro kernels; custom kernels _may_ work, but we don't test on those. You can run the check-config script (which does some rudimentary checks) to see if anything stands out; https://github.com/moby/moby/blob/master/contrib/check-config.sh
> 
> Another possible issue is memory;
> 
> ```
> Total Memory: 501.6MiB
> ```
> 
> 500Mb may be quite low to run docker, containerd, runc _and_ your containers; it _may_ work, but it's quite likely you may be running onto memory issues (which _could_ also be related to weird errors, such as the one you posted)
> 
> Finally, it may be worth starting the daemon with debug enabled and to check daemon logs; assuming you don't have a `daemon.json` configuration file yet (https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file), you can create one with `debug` set to `true`;
> 
> ```shell
> mkdir -p /etc/docker/
> echo '{"debug":true}' > /etc/docker/daemon.json
> ```
> 
> After that, restart the daemon;
> 
> ```shell
> sudo systemctl restart docker
> ```
> 
> Note that debug logging produces a _lot_ of logs, some of which may contain sensitive data, so best to disable it after you are done debugging.

Thank you very much! The problem has been solved!

I modified the name of the local loopback interface before, which caused this problem.

When I changed the name back to the default name, lo, everything worked fine.

Thanks again!
