### ISSUE TITLE
Add umask configuration into runc

### ISSUE THREAD

**Issue by gauravg2683** [moby/moby#41734]
Description

I see now umask support added opencontainers/runc@a63f99f#diff-e0932af06cb46065b2ef5fc89bc2bd9b880c9578e01b89ef4ecaeffb78a8bef0 but don't see any option to add in config https://docs.docker.com/engine/reference/commandline/dockerd/ because it's not added into runc yet.
Please add this configuration into runc.

Slack reference : https://cloud-native.slack.com/archives/CGEQHPYF4/p1604609074087400 cc @thaJeztah

**Comment by thaJeztah** [comment]
looks like you already opened a ticket for this two weeks ago; https://github.com/moby/moby/issues/41680. Let me close this one as a duplicate
