### ISSUE TITLE
docker image rm --no-prune does not behaved as described in the --help.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [moby/moby#41758]
**Description**

`docker image rm --no-prune` does not behave as mentionned in the `--help`. The parent image is still removed.

I would like to be able to remove a tag from an image without removing the image. `docker image rm --no-prune` seemed to do that from the documentation. So either the documentation should be updated and made more accurate, either there is a bug with the `--no-prune` option.
**Steps to reproduce the issue:**
```bash
$ docker pull -q python:2.7-slim
docker.io/library/python:2.7-slim
$ docker image ls --no-trunc | grep 2.7-slim
python                        2.7-slim            sha256:eeb27ee6b89303f04a917e457eda70d032b1574ec80d0b4ea410d478a714538f   7 months ago        148MB
$  docker image rm --no-prune python:2.7-slim
Untagged: python:2.7-slim
Untagged: python@sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c9f061f9a45344e3992363
Deleted: sha256:eeb27ee6b89303f04a917e457eda70d032b1574ec80d0b4ea410d478a714538f
Deleted: sha256:05c4a4e72f132b4827fc5a47bc34ae97128781c4276748e0b5ee6d5bd4b52a05
Deleted: sha256:d72664b440e8b6baf929fe0ce6fe55465b77d253adedfd66ec503ac8f66d460c
Deleted: sha256:cb07337d03e7375dd017c9afe55c0a45843ff5f20f5e4530afb2eced8adad6b5
Deleted: sha256:b60e5c3bcef2f42ec42648b3acf7baf6de1fa780ca16d9180f3b4a3f266fe7bc
$ docker image ls --no-trunc | grep sha256:eeb27e
# No output there
```

**Describe the results you received:**

The image and all layers were removed, not only the tag

**Describe the results you expected:**

The image should exist and it should be possible to reference it with its ID (sha256:eeb27ee6b89303f04a917e457eda70d032b1574ec80d0b4ea410d478a714538f).

**Additional information you deem important (e.g. issue happens only occasionally):**

It's reproducible. So maybe I misunderstood the docs. But maybe they need to be clarified then.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.3
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.4.2)
  app: Docker Application (Docker Inc., v0.8.0)

Server:
 Containers: 33
  Running: 2
  Paused: 0
  Stopped: 31
 Images: 59
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 1dfg8pkzc18pc61ygjllhzl3y
  Is Manager: true
  ClusterID: mm6sl1v1qtzizk3ju9qqjp0bb
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.29.79.220
  Manager Addresses:
   172.29.79.220:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.805GiB
 Name: DESKTOP-CGESNGL
 ID: 2LEB:NCGC:VDJX:GSLN:BCNN:UWZT:3VIE:6M6K:T26A:QKAN:JNKW:BP4C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu in WSL2

**Comment by thaJeztah** [comment]
hm, not at my computer right now, but wondering if this only had an effect when building images locally using the classic builder and/or docker 1.9 and older (which used a parent chain for images).

Also, in that case it would need a "parent image", which in your case is not present when pulling an image from a registry.

Curious what your use case is; could you describe a bit more in depth?

**Comment by gabrieldemarmiesse** [comment]
Thank you for the answer, I understand what parents mean now. But since with buildkit, we don't have parents anymore, I wonder if `--no-prune` will still be useful.

Anyway, my use case is to wrap the `docker buildx build` call to make it usable from python, with the nicest api possible. See https://gabrieldemarmiesse.github.io/python-on-whales/sub-commands/buildx/#build

Very often the user would want to do this, it's a very common and intuitive workflow:
```
from python_on_whales import docker
my_image = docker.buildx.build(...)
docker.run(my_image, ....)

....
# much, much, much later, from bash:
# docker image prune
```
I was looking at ways of getting the docker image from buildx without adding a tag to it in the end. `--iidfile` didn't give the same id for the image in buildkit and once the image was loaded in docker. My second idea was to tag the image and then untag it afterwards (so that users can use `docker image prune`). Anyway, it seems that it's more a feature request for buildx than a bug report.

In the end, if we want to keep this issue open to track an improvement in the docs, let's note that I wasn't the only one to misunderstand the docs :) https://serverfault.com/questions/703344/how-to-remove-an-image-tag-in-docker-without-removing-the-image-itself#comment1132569_703352

**Comment by thaJeztah** [comment]
Do you see the same problem with `DOCKER_BUILDKIT=1 docker build ..`  as with buildx?

**Comment by thaJeztah** [comment]
> In the end, if we want to keep this issue open to track an improvement in the docs, let's note that I wasn't the only one to misunderstand the docs

To be honest, I completely forgot we had that flag. We'll definitely need to look into it, and perhaps if the flag no longer does anything useful, deprecate it.

**Comment by gabrieldemarmiesse** [comment]
I didn't try with `DOCKER_BUILDKIT=1 docker build `, from what I understand, this will be replaced buildx somewhat later

**Comment by gabrieldemarmiesse** [comment]
Anyway I believe that this issue isn't needed anymore. We should open a new one focused on discuting the utility of the `--no-prune` flag. I'll open an issue in the buildx repo to know if it's possible to get the ID of the docker image loaded into the daemon somehow. 

Thanks @thaJeztah  for the help and thanks the docker team for the awesome piece of software :)

**Comment by gabrieldemarmiesse** [comment]
See https://github.com/moby/moby/issues/41760 for the `--no-prune` flag

**Comment by gabrieldemarmiesse** [comment]
See https://github.com/docker/buildx/issues/420 for the issue I mentionned concerning the `--iidfile`.
