### ISSUE TITLE
Log a process when its launched

### ISSUE THREAD

**Issue by ramonssarmento** [moby/moby#41779]
Does anyone know if there is any way to log a process when its launched and associate it to the corresponding containers IDs or file path on host machine?
I tried to modify the overlay2 to place this trigger, but the launch of the process doesn't seem to be there.

Any help is appreciated.
Best regards.

**Comment by cpuguy83** [comment]
With ptrace or krpobes probably.

You could probably also wrap runc to log whatever you want to log.

Otherwise the only built in thing is "docker events", but that doesn't give you any details about files... just the container itself.

**Comment by cpuguy83** [comment]
Closing since there really isn't anything to do here.
