### ISSUE TITLE
`docker run --platform` doesn’t pull images for the requested platform under some circumstances.

### ISSUE THREAD

**Issue by Ferroin** [moby/moby#41782]
**Description**

When attempting to run an image for a specific platform and the image does not exist locally for the requested platform, but the image does exist locally for the native platform, the image for the native platform will be run instead of the one for the requested platform, without indicating any errors or attempting to pull the image for the correct platform.

**Steps to reproduce the issue:**
1. Set up multi-arch support: `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes`
2. Remove any existing copy of the `alpine:edge` image.
3. Pull the native `alpine:edge` image for your system: `docker pull alpine:edge`
4. Attempt to run the `uname -m` command in `alpine:edge` for a platform _other than_ the native one for your system. For example, on an AMD64 system, try something like `docker run -it --rm --platform linux/arm alpine:edge /bin/uname -m`.

**Describe the results you received:**

On an AMD64 system, the result was `x86_64` even though I attempted to run an ARMv7 image. On an ARMv7 VM, the result was `armv7l` even tough I attempted to run an i386 image.

**Describe the results you expected:**

The `docker run` command should pull the image for the requested platform and run that, or at least fail with a warning that the image is not locally available for the requested platform.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue seems to be independent of actual host architecture (verified in an ARM VM in addition to the AMD64 system I originally saw the issue on).

**Output of `docker version`:**

```
Client:
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.15.5
 Git commit:        5eb3275
 Built:             Thu Dec  3 12:32:09 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.5
  Git commit:       5eb3275
  Built:            Thu Dec  3 12:31:37 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.9
  GitCommit:        ea765ab
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 52
 Server Version: 19.03.14
 Storage Driver: btrfs
  Build Version: Btrfs v5.9 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765ab
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683b971d9c3ef73f284f176672c44b448662
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.9.9-ahferroin7+
 Operating System: Gentoo/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.48GiB
 Name: wild-karde
 ID: SR3S:P35O:G7ML:NT2E:HRAG:T3SB:KC2P:NNZ5:3Z5M:Q4DQ:24RC:EVTQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Originally seen on physical hardware, running a local build of Docker from Gentoo’s Portage tree. Later tested in an ARM VM running Docker 19.03.12 version from the Alpine Linux repositories.

**Comment by thaJeztah** [comment]
Could you check if docker 20.10 works as expected for your use case?

**Comment by Ferroin** [comment]
> Could you check if docker 20.10 works as expected for your use case?

Yes, it does indeed work correctly now in 20.10.

Closing as this appears to be fixed.
