### ISSUE TITLE
Will docker-ce support kubernetes 1.20 and later versions

### ISSUE THREAD

**Issue by king311247** [moby/moby#41780]
Will docker-ce support kubernetes 1.20 and later versions ?

**Comment by tao12345666333** [comment]
If you use kubernetes 1.20, docker-ce can work well, only one log will appear.

If you care about dockershim, you can refer to this article https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/

If you care about whether Docker will have built-in CRI support, you can take a look at https://github.com/moby/moby/issues/40966
