### ISSUE TITLE
contrib/check-config.sh shows dropped configuration as missing

### ISSUE THREAD

**Issue by aendeavor** [moby/moby#41797]
# `contrib/check-config.sh` uses dropped configurations

Looking at <https://github.com/torvalds/linux/commit/db8ab38880e06dedbfc879e75f5b0ddc495f4eb6>, we see that some configuration parameters were dropped.

**Steps to reproduce the issue:**
1. Run the `contrib/check-config.sh` with linux kernel `>=5.1`
2. See that `CONFIG_NF_NAT_IPV4: missing` and `CONFIG_NF_NAT_NEEDED: missing` is shown

**Describe the results you received:**

The parameters are shown as missing

**Describe the results you expected:**

These parameters are not "missing", they were dropped. This could be misleading.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

`/etc/os-release`

``` BASH
   1   │ NAME="Ubuntu"
   2   │ VERSION="20.04.1 LTS (Focal Fossa)"
   3   │ ID=ubuntu
   4   │ ID_LIKE=debian
   5   │ PRETTY_NAME="Ubuntu 20.04.1 LTS"
   6   │ VERSION_ID="20.04"
   7   │ HOME_URL="https://www.ubuntu.com/"
   8   │ SUPPORT_URL="https://help.ubuntu.com/"
   9   │ BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  10   │ PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  11   │ VERSION_CODENAME=focal
  12   │ UBUNTU_CODENAME=focal
```

`$ uname -a`

``` BASH
Linux <name> 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Related to https://github.com/docker/docker.github.io/issues/10592

**Comment by thaJeztah** [comment]
Was there a reason for closing this ticket? I suspect this is still an issue?

Let me reopen, but happy to hear if there was a reason for closing 😅

**Comment by aendeavor** [comment]
> Was there a reason for closing this ticket? I suspect this is still an issue?
> 
> 
> 
> Let me reopen, but happy to hear if there was a reason for closing 😅 

I thought this ticket is not being worked on since no labelling took place neither did I receive a response. But I'm glad I was mistaken. This indeed is still an issue.

**Comment by gunadhya** [comment]
Hi @aendeavor and @thaJeztah , I'd like to work on this issue. I'm new to open source so might need some guidance.
