### ISSUE TITLE
contrib/check-config.sh cgroup hierarchy: nonexistent?? with cGroups v2

### ISSUE THREAD

**Issue by aendeavor** [moby/moby#41798]
# `contrib/check-config.sh` shows `cgroup hierarchy: nonexistent??` with cGroups v2

**Steps to reproduce the issue:**
1. Use cGroups v2 on Ubuntu 20.04
2. Use the `contrib/check-config.sh` script to check your ocnfiguration

**Describe the results you received:**

The cgroup hierarchy is shown as nonexistent.

**Describe the results you expected:**

cGroup hierarchy should be working (?)

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm not a professional when it comes to cGroups. Maybe my setup is wrong.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

None I deem important at the moment.

**Comment by tpgxyz** [comment]
Yes i can confirm this on OpenMandriva cooker with systemd enabled unified cgroups hierarchy
