### ISSUE TITLE
[rootless] lchown [...]: no such file or directory

### ISSUE THREAD

**Issue by aendeavor** [moby/moby#41803]
# Rootless Docker cannot pull certain images?!

No matter what I do, I can't quite get it to work, and the internet is full of reports where this is the case. I'm on Ubuntu 20.04 with a `5.4.0-58` kernel. `systemctl --user status docker` reports:

``` BASH
dockerd-rootless.sh[1932]: [...] level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: failed to set opaque flag on middle layer: operation not permitted" storage-driver=overlay2
```

I tried:

1. Setting `options overlay metacopy=off redirect_dir=off` for the overlay kernel module
2. Installing packages like `fuse-overlayfs` and its libraries
3. https://mikeshade.com/posts/docker-native-overlay-diff/

Reports:

1. https://github.com/docker/for-linux/issues/1055
2. https://stackoverflow.com/questions/65273160/how-to-enable-native-overlay-diff-on-debian-docker-rootless
3. https://github.com/containers/buildah/issues/2326
4. https://github.com/containers/buildah/blob/master/troubleshooting.md#6-rootless-buildah-bud-fails-when-using-overlayfs

Why is this important? Some images cannot be pulled, and fail due to a strange error where `lchown` does not find a file or directory:

``` BASH
 ~ $ docker pull docker.io/gitlab/gitlab-ee:13.6.3-ee.0
13.6.3-ee.0: Pulling from gitlab/gitlab-ee
be8ec4e48d7f: Pull complete
33b8b485aff0: Pull complete
d887158cc58c: Pull complete
05895bb28c18: Pull complete
5a5da1768523: Pull complete
fabe58ce18d2: Pull complete
7eb97e608ff0: Pull complete
1ab51a6460c9: Pull complete
b07e61468e0b: Pull complete
c5dd26abc4c2: Extracting [==================================================>]  901.9MB/901.9MB
failed to register layer: Error processing tar file(exit status 1): lchown /opt/gitlab/sv/sshd/log/supervise/ok: no such file or directory
```

**Steps to reproduce the issue:**

1. Install rootless Docker on Ubuntu 20.04.1

**Describe the results you received:**

I'm seeing

``` BASH
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
```

and I cannot pull (large?) images.

**Describe the results you expected:**

If would like to see

``` BASH
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true  <--------
```

and I'd like to pull large images.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:54:00 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: itbsd
 ID: WCKE:YRNK:PITP:G345:T3KJ:IMZH:2N7L:Y5YP:FFLO:MLZW:CFD7:ZMGU
 Docker Root Dir: /home/notroot/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: Support for cgroup v2 is experimental
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Happens here: https://github.com/docker/docker-ce/blob/master/components/engine/daemon/graphdriver/overlay2/check.go#L55 ?

**Comment by AkihiroSuda** [comment]
Lack of native diff is expected, but `lchown /opt/gitlab/sv/sshd/log/supervise/ok: no such file or directory` is unexpected error. @aendeavor Could you modify the issue title and the description?

**Comment by AkihiroSuda** [comment]
> Installing packages like fuse-overlayfs and its libraries

fuse-overlayfs is unrelated and is not used by default.

To use fuse-overlayfs:

```console
echo '{"storage-driver":"fuse-overlayfs"}' > ~/.config/docker/daemon.json
systemctl --user restart docker
```

However, the exact error `lchown /opt/gitlab/sv/sshd/log/supervise/ok: no such file or directory` seems reproducible with fuse-overlayfs as well :cry:

**Comment by aendeavor** [comment]
> Lack of native diff is expected, but `lchown /opt/gitlab/sv/sshd/log/supervise/ok: no such file or directory` is unexpected error. @aendeavor Could you modify the issue title and the description?

Absolutely!

**Comment by AkihiroSuda** [comment]
Interesting, the issue happens even with `vfs` storage driver on rootless.

**Comment by sheeaza** [comment]
if the images have 'named pipe file' it will casue rootless docker both build and load images failed
```
Step 2/4 : RUN mknod /root/dfdfdf p
 ---> Running in b28218bcbe2d
Error processing tar file(exit status 1): lchown /root/dfdfdf: no such file or directory
```

**Comment by snajpa** [comment]
Can confirm. Unpacking the rootfs within the user namespace manually works without problems; also this bug is new to 20.10, 20.03 worked fine.

**Comment by sheeaza** [comment]
> Can confirm this is about named pipe files. Unpacking the rootfs within the user namespace manually works without problems; also this bug is new to 20.10, 20.03 worked fine.

should be 19.03?

**Comment by snajpa** [comment]
No, with 20.03 it worked fine in our conditions.

Now I also got it working with 20.10, by lying to Docker about running in user namespace. I don't get why this thing wants to act so smart, but all this smartness code does is introduce bugs...

Docker detect whether it's running UserNS by looking at `/proc/self/uid_map`, so I fake this quickly and crudely by this patch, it suddenly all works just fine.

Also probably only the "exe" match is needed, the other two are just precautionary.

```diff --git a/kernel/user_namespace.c b/kernel/user_namespace.c
index f6278662bcbb..940de4a1b76a 100644
--- a/kernel/user_namespace.c
+++ b/kernel/user_namespace.c
@@ -666,6 +666,15 @@ static void *uid_m_start(struct seq_file *seq, loff_t *ppos)
 {
        struct user_namespace *ns = seq->private;
 
+       if ((strcmp(current->comm, "containerd") == 0) ||
+           (strcmp(current->comm, "dockerd") == 0) ||
+           (strcmp(current->comm, "exe") == 0)) {
+               pr_warn("olol faked uid_m_start for comm %s\n", current->comm);
+               return NULL;
+       }
+
        return m_start(seq, ppos, &ns->uid_map);
 }
 
```

**Comment by AkihiroSuda** [comment]
Fix: https://github.com/moby/moby/pull/41892

**Comment by dimmel82** [comment]
Hi,
I get the error `"failed to register layer: Error processing tar file(exit status 1): lchown /usr/src/git-2.21.0/configure: invalid argument"` in a `docker:20.10.5-dind-rootless` container when executing the following command:
`docker pull gcr.io/jenkinsxio/builder-maven-java11:0.1.464`
I think that it is the same case with this issue, though I expected it to be resolved in this version of the dind-rootless image.
Should I create a new issue for this?

Note that gcr.io/jenkinsxio/builder-maven-java11:0.1.464 is quite an old image but we have to use it nevertheless, I'm not sure if this is related with the issue somehow.

**Comment by aendeavor** [comment]
I'd open a new issue for your case:)
