### ISSUE TITLE
docker rootless fails to run (newuidmap: Could not set caps)

### ISSUE THREAD

**Issue by WhyNotHugo** [moby/moby#41812]
```console
$ rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh uninstall
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 5349 [0 1000 1 1 165536 65536] failed: newuidmap: Could not set caps
```

I've cheked all the requirements and relevant settings for this:

```console
$ cat /etc/subgid /etc/subuid
hugo:165536:65536
hugo:165536:65536
$ cat /proc/sys/kernel/unprivileged_userns_clone
1
$ uname -a
Linux victory 5.10.1-arch1-1 moby/buildkit#1 SMP PREEMPT Tue, 15 Dec 2020 19:49:00 +0000 x86_64 GNU/Linux
$ which fuse-overlayfs
/usr/bin/fuse-overlayfs
$ dockerd --version
Docker version 20.10.1, build f0014860c1

```

Any hints as to what's up?

**Comment by AkihiroSuda** [comment]
Transferred this issue from moby/buildkit repo to moby/moby

**Comment by AkihiroSuda** [comment]
>  rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh uninstall

This command is wrong in two aspects
1. `dockerd-rootless.sh` should be executed outside RootlessKit, because `dockerd-rootless.sh` launches RootlessKit by itself..
2. There is no such command as `dockerd-rootless.sh uninstall`. Maybe you meant `dockerd-rootless-setuptool.sh uninstall`?
3.

**Comment by WhyNotHugo** [comment]
> Please make sure /usr/bin/newuidmap has SETUID bit or at least CAP_SETUID file capability.

How can I check this? I'm not sure how to print a files capabilities.

```console
$ getcap /usr/bin/newuidmap
$ ls -l /usr/bin/newuidmap
-rwxr-xr-x 1 root root 36992 Sep  7 15:42 /usr/bin/newuidmap
```

Does this look wrong? If that's the case, I guess I need to report this to by distribution, since these files are provided by it.

**Comment by WhyNotHugo** [comment]
Huh, reinstalling `shadow` (package that provides `/usr/bin/newuidmap`) seems to have changed this:

```
$ getcap /usr/bin/newuidmap
/usr/bin/newuidmap cap_setuid=ep
```

Looks like my setup was broken at some point. Thanks for the pointers and sorry for the noise!
