### ISSUE TITLE
"docker load" gives error "...not a valid parent for..." on Windows

### ISSUE THREAD

**Issue by rcowsill** [moby/moby#41829]
**Description**

On Windows, `docker load` gives an error when loading a tar file produced by `docker save` on the same machine and OS. So far I've only seen this happen when the tar file contains:
1) An image which is a direct child of windows/nanoserver:1809 or windows/servercore:ltsc2019
2) The parent image: windows/nanoserver:1809 or windows/servercore:ltsc2019

This may affect more base images, the above are the ones I've tried so far.

**Steps to reproduce the issue:**

With the following Dockerfile, on a Windows machine:
```
FROM mcr.microsoft.com/windows/nanoserver:1809
CMD ["cmd", "/C", "echo hello world"]
```
1. Run `docker build -t test-image .`
2. Run `docker save -o images.tar test-image mcr.microsoft.com/windows/nanoserver:1809`
3. Run `docker load -i images.tar`

This is already set up here: https://github.com/rcowsill/test-nanoserver-load. That repo includes a GitHub Actions workflow which builds the image, saves it with the base image and tries to load them back in.

**Describe the results you received:**
The `docker load` command fails with the error message:
```
image sha256:6795354d435f[...] is not a valid parent for sha256:d9a7d88ed5b0[...]
```
(Full logs here: https://github.com/rcowsill/test-nanoserver-load/runs/1586120647)

**Describe the results you expected:**

Images load successfully from the tar file

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking at [the code](https://github.com/moby/moby/blob/b5f863c67e6ffbaadedb94c885c3c50c625e4eb8/image/tarexport/load.go#L401) that produces this error message, it looks like the history for the parent image doesn't match the child image (ignoring the last step). Here are the json files for the two images as output by `docker save`:

[6795354d435f89ae3a76f71e9c4e8e8b29b70a69fefaba2b4d13581e20c19d71.json.txt](https://github.com/moby/moby/files/5721691/6795354d435f89ae3a76f71e9c4e8e8b29b70a69fefaba2b4d13581e20c19d71.json.txt)
[d9a7d88ed5b05d7f39f705b85717eab568e38ba8533211c862a20990fa7a0dac.json.txt](https://github.com/moby/moby/files/5721692/d9a7d88ed5b05d7f39f705b85717eab568e38ba8533211c862a20990fa7a0dac.json.txt)

Notice that the format of the "created" dates in the first history entry is different: `2020-12-03T08:05:47.704+00:00` vs `2020-12-03T08:05:47.704Z`

**Output of `docker version`:**

```
Client: Mirantis Container Runtime
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        0c38b2d
 Built:             11/12/2020 21:33:08
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       5b5efb2d49
  Built:            11/12/2020 21:31:44
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1637)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7GiB
 Name: fv-az41-664
 ID: 36N4:GU5B:533U:A3DM:WWG7:K7S4:EFNH:HY23:PFOE:NGGL:FS4E:N2LA
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on windows-latest in GitHub Actions

**Comment by thaJeztah** [comment]
Error is produced here; https://github.com/moby/moby/blob/42855ebc7fdf649d5e555a540078c48676dc665e/image/tarexport/load.go#L174-L176

After validation failed in https://github.com/moby/moby/blob/42855ebc7fdf649d5e555a540078c48676dc665e/image/tarexport/load.go#L401-L414

Wondering if this is related to "foreign layers"; IIRC, saving/loading those layers was restricted for licensing reasons https://github.com/moby/moby/pull/22866

> In the future we may want to extend this to support treating these foreign layers as normal layers for air-gapped scenarios. This is not supported yet.

/cc @lowenna

**Comment by rcowsill** [comment]
Something else I've noticed is that there are subtle differences in the config JSON format of the saved images. For example, the nanoserver image has "rootfS" (uppercase 'S') rather than "rootfs", and "config.cmd" instead of "config.Cmd". The child image produced by the CMD step in the Dockerfile has "rootfs" and "config.Cmd". That matches the output format I've seen from `docker save` on Linux. Not sure if it's related to this error message though.

**Comment by rcowsill** [comment]
I think I see what's happening here. The config JSON for windows/nanoserver:1809 has the following creation date in its History:
```
"created":"2020-12-03T08:05:47.704+00:00"
```
That unmarshals fine so the image itself works without any issues. If this image is used as the base to build another, the history entry gets copied into the new image. The problem occurs when that new image is marshalled back into JSON. Go's time library outputs the history timestamp as:
```
"created":"2020-12-03T08:05:47.704Z"
```
In other words, the time zone has been written as a "UTC time" rather than a "local time with zero offset from UTC". These two time representations compare equal when using `Time.Equal`, but `reflect.DeepEqual` or `==` treat them as different. That leads to `checkValidParent` reporting that the histories don't match.

This seems to be a flaw in go's time library; UnmarshalJSON treats "Z" and "+00:00" as different, but MarshalJSON considers them to be identical and outputs both as "Z".

I'll report this issue in the go repo, but it may be worth working around it in the meantime. One option would be to preprocess the parent history by running it through json.Marshal and json.Unmarshal. That should make the parent history format match what has been written into the child.

**Comment by thaJeztah** [comment]
> This seems to be a flaw in go's time library; UnmarshalJSON treats "Z" and "+00:00" as different, but MarshalJSON considers them to be identical and outputs both as "Z".

Oh, that's interesting indeed. If you opened a ticket in the go repo, feel free to post a link here, for those that are interested.

**Comment by thaJeztah** [comment]
Also /cc @tonistiigi in case there's other possible situations where we do such comparisons.

**Comment by rcowsill** [comment]
Issue logged at golang/go#43501

**Comment by rcowsill** [comment]
> Also /cc @tonistiigi in case there's other possible situations where we do such comparisons.

This looks like it may need the same workaround:
https://github.com/moby/moby/blob/41e5d459f1725546b58579fea585afb83ca389bc/image/cache/cache.go#L195
