### ISSUE TITLE
While using WSL-2 based engine, it can not be used bind mount from local file

### ISSUE THREAD

**Issue by burakkilincofficial** [moby/moby#41824]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/run/desktop/mnt/host/c/deneme/index.html" to rootfs at "/var/lib/docker/overlay2/aae70d8c897d66d4347cdedb0dd229986156874fc3a275c1215fdf1d989e33c8/merged/usr/local/apache2/htdocs" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

D:\Work\Development\Docker> cat $PWD/conf/nginx.conf
cat : Cannot find path 'D:\Work\Development\Docker\conf\nginx.conf' because it does not exist.
At line:1 char:1
+ cat $PWD/conf/nginx.conf
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Work\Develop...conf\nginx.conf:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by cpuguy83** [comment]
The error seems to indicate what the problem is. Did you check this? Is the file/dir available in wsl?

**Comment by thaJeztah** [comment]
Looks like this one went stale; closing this issue, but feel free to continue the conversation
