### ISSUE TITLE
DockerMsftProvider doesn't contain 20.10

### ISSUE THREAD

**Issue by ShemTovYosef** [moby/moby#41826]
Hi, 
I want to upgrade to the release 20.10 for Windows Server but repository outdated, the latest version is 19.03.13
Could you update it?

Thanks,
Yosef

**Comment by olljanat** [comment]
Afaiu it is up to Mirantis/Microsoft to publish those Docker enterprise edition builds.

DockerMsftProvider provider uses https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json file to get list of those so you can follow it to see when it is available.

@thaJeztah can you ping someone who know more details?

**Comment by cpuguy83** [comment]
@immuzz Can you take a look at this?

**Comment by ShemTovYosef** [comment]
Who can help with this issue?

**Comment by ShemTovYosef** [comment]
ping someone who can knows @andrew-sumner @mat007 @stephen-turner @nebuk89

**Comment by olljanat** [comment]
@ShemTovYosef FYI. Looks like that this one have been now handled. What is a bit boring is that they only released 20.10.0 which misses all bugfixes from versions 20.10.1 - 20.10.5: https://docs.docker.com/engine/release-notes/#20105

**Comment by ShemTovYosef** [comment]
It's better than nothing, thanks for update!

**Comment by ShemTovYosef** [comment]
Updates will be kept on, following this https://github.com/microsoft/Windows-Containers/issues/99
