### ISSUE TITLE
contrib/check-config.sh: verify available cgroup v2 controllers

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41874]
https://github.com/moby/moby/pull/41869 added cgroup v2 support for `contrib/check-config.sh`, but it doesn't verify available controllers currently.

We need to verify that
- availability of `cpu`, `cpuset`, `memory`, and `io` controllers, by reading `/sys/fs/cgroup/cgroup.controllers` file
- availability of `BPF_CGROUP_DEVICE` support, probably by checking that kernel >= 4.15 && `CONFIG_CGROUP_BPF`. This is an essential requirement for rootful mode.
- availability of freezer, probably by checking the existence of `cgroup.freezer` file. This requires kernel >= 5.2 and is optional.

**Comment by thaJeztah** [comment]
@gunadhya I saw you were interested in working on changes in this script (https://github.com/moby/moby/issues/41797#issuecomment-751825388); some changes have been implemented in https://github.com/moby/moby/pull/41869, but this ticket lists what's still left to do; perhaps you're interested in working on this?

**Comment by gunadhya** [comment]
Hi @AkihiroSuda @thaJeztah , I'd be happy to work on this issue.

**Comment by thaJeztah** [comment]
Thanks!
