### ISSUE TITLE
I use docker in windows10, and I found that the ip address on vEthernet (WSL) change everytime when I restart windows. It leads to I can't access Windows resources from docker container.

### ISSUE THREAD

**Issue by dmokel** [moby/moby#41881]
**Description**
I use docker in windows10, and I found that the ip address on vEthernet (WSL) change everytime when I restart windows. It leads to I can't access Windows resources from docker container.

 For example, I run an application using docker to access the mySQL running on windows host, I can't connect to mysql-server running on windows when I use the orignal config.
because ip address on the vEthernet (WSL) had changed, but the mysql-host ip in my original config as same as last time.

What can I do to keep the IP address of WSL unchanged when I restart windows?

thanks~

**Comment by thaJeztah** [comment]
Did you install docker with Docker Desktop, or did you manually install in WSL?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
