### ISSUE TITLE
WARNING: Error loading config file: .dockercfg: $HOME is not defined

### ISSUE THREAD

**Issue by atline** [moby/moby#41890]
**Description**

We have a software which will call `docker xxx` in its code.

a) It's ok in the past
b) After upgrade docker to `20.10.1`, it reports next:

> WARNING: Error loading config file: .dockercfg: $HOME is not defined

**NOTE: we don't have HOME set in our env. I wonder if it's a bug? What's the root cause?**
**Should I add `export HOME=/root` in our software to act as a workaround, or you will fix it in future release?**

**Steps to reproduce the issue:**
1. Install 20.10.1
2. unset HOME
3. `docker ps` or any other docker command will show warning.

**Describe the results you received:**

```
# docker ps
WARNING: Error loading config file: .dockercfg: $HOME is not defined
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Describe the results you expected:**

No warning.

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-13-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.593GiB
 Name: shlava
 ID: TULV:U34A:NIJQ:Y3SP:FKLM:UX64:YXUE:KMOU:LND5:HBBN:F5YV:F3D4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Looks like this happens if the current `~/.docker/config.json` configuration file was not found, and we're falling back to the deprecated `~/.dockercfg` configuration file; https://github.com/docker/cli/blob/v20.10.2/cli/config/config.go#L111-L123

```go
// Can't find latest config file so check for the old one
home, err := os.UserHomeDir()
if err != nil {
	return configFile, errors.Wrap(err, oldConfigfile)
}
```

The error is coming from , which is used in Docker 20.10 instead of the implementation from the docker repository (changed in https://github.com/docker/cli/pull/2101)

That said, we _do_ use the moby implementation for the default; https://github.com/docker/cli/blob/v20.10.2/cli/config/config.go#L35-L38

```go
configDir = os.Getenv("DOCKER_CONFIG")
if configDir == "" {
	configDir = filepath.Join(homedir.Get(), configFileDir)
}
```

Perhaps we should memoize the home-dir, and use that implementation here as well

Overall, this warning is safe to ignore, unless you are using the deprecated `~/.dockercfg` file (but support for that will be removed in the next release)

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/2934 to prevent the warning

**Comment by atline** [comment]
@thaJeztah , Great, I see the PR.

YES, manually, I can ignore it. But in some program, we will just get the output of `docker xxx`, then use the output to determine next action of program. In that scenario, additional unexpected output will make program fail.

So, I'm happy to see it could be resolved in later versions, thanks!

**Comment by thaJeztah** [comment]
The warning should be printed on `stderr`, and regular output on `stdout`, so perhaps redirecting would work for your use-case (until the fix is in a release)?

Piping output to `more` (to illustrate);

```console
$ unset HOME

$ docker version | more
WARNING: Error loading config file: .dockercfg: $HOME is not defined
Client: Docker Engine - Community
 Version:           20.10.1
error during connect: Get http://docker:2375/v1.24/version: dial tcp: lookup docker on 192.168.65.1:53: no such host
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:28:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

Same, but redirecting `stderr` to `/dev/null`;

```console
$ docker version 2> /dev/null | more
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:28:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by atline** [comment]
Yes, it could be, thanks.

**Comment by thaJeztah** [comment]
Let me keep the ticket open for tracking until https://github.com/docker/cli/pull/2934 is merged 👍

**Comment by thaJeztah** [comment]
closing as https://github.com/docker/cli/pull/2934 was merged (but not yet in a release)
