### ISSUE TITLE
Overflow in unix collector

### ISSUE THREAD

**Issue by ridv** [moby/moby#41915]
**Description**

While looking through the unix collector code to understand how the CPU percentage is calculated, I noticed that the total number of clock ticks is multiplied by a pretty big number before being divided by 100.

The relevant line is here https://github.com/moby/moby/blob/master/daemon/stats/collector_unix.go#L61

The information on the ticks is pulled from `/proc/stat`. Trying to better understand the code I went on a local system and got the output from that pseudofile. The numbers it spit out were particularly large which made me wonder if this was resulting in an overflow (even with uint64 which, just for quick reference, has a max of `18446744073709551615`).

These were the numbers pulled from that particular VM running on GCP:
```
~$ cat /proc/stat
cpu  391560803 250677279 651257224 21492460706 617141613 0 40558038 0 0 0
```
These numbers add up to: `23443655663`

This is then multiplied by 1e9 which (on a calculator) results in:  `2.3443655663e19`

This leads to an overflow in the program which returns: `49969115892904483`
https://play.golang.org/p/Dt7K2fRGg88

The result should actually be: `2.3443655663e17`
https://play.golang.org/p/1ZG7iUtyEwr

**Steps to reproduce the issue:**
1. Find a node with a large number of cpu clock ticks in /proc/stat
2. Calculate the numbers by hand

**Describe the results you received:**

SystemCPUUsage: `49969115892904483`

**Describe the results you expected:**

SystemCPUUsage: `234436556630000000`

**Additional information you deem important (e.g. issue happens only occasionally):**

Only happens on Nodes which contain a high number of CPU clock ticks on /proc/stat

**Output of `docker version`:**

```
Can be provided but isn't particularly useful for this bug.
```

**Output of `docker info`:**

```
Can be provided but isn't particularly useful for this bug.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM running GCP

**Comment by thaJeztah** [comment]
Thanks for reporting; are you interested in opening a pull request with a fix?

**Comment by ridv** [comment]
Absolutely!
