### ISSUE TITLE
Docker Windows LCOW failed to build container (The virtual machine or container with the specified identifier is not running)

### ISSUE THREAD

**Issue by hassanalbudairi** [moby/moby#41928]
**This is reported to docker and been advised to rise the issue here as it is a problem with the upstream engine.
After updating to Docker Desktop Community 3.1.0 on Windows 10 Pro (ver 1909 OS build 18363.1316), I faced an issue I could not build any container. Here is the details**
deamon config
{ "registry-mirrors": [], "insecure-registries": [], "debug": true, "experimental": true }

Dockerfile
FROM ubuntu:latest ENV DEBIAN_FRONTEND noninteractive RUN apt-get update && \ apt-get install -y python3 python3-dev python3-pil hugin-tools ADD generate.py /generate.py ENTRYPOINT ["python3", "/generate.py"]

Docker command
docker build -t generate-panorama .

The error message
The command '/bin/sh -c apt-get update &&     apt-get install -y python3 python3-dev python3-pil hugin-tools' returned a non-zero code:
4294967295:failed to shutdown container
:container c783e98680ab347d24f3c5df76cbd19b18e9c6a2652e649715d5f89d6ace5429 encountered an error during hcsshim::System::waitBackground:
 failure in a Windows system call: The virtual machine or container with the specified identifier is not running.
 (0xc0370110): subsequent terminate failed 
 container c783e98680ab347d24f3c5df76cbd19b18e9c6a2652e649715d5f89d6ace5429 encountered an error during hcsshim::System::waitBackground:
failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

diagnostics id 63D55BDE-0082-4486-AD62-F4A17C5C544D/20210125140153

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
Cloud integration: 1.0.7
Version: 20.10.2
API version: 1.41
Go version: go1.13.15
Git commit: 2291f61
Built: Mon Dec 28 16:14:16 2020
OS/Arch: windows/amd64
Context: default
Experimental: true
Server: Docker Engine - Community
Engine:
Version: 20.10.2
API version: 1.41 (minimum version 1.24)
Go version: go1.13.15
Git commit: 8891c58
Built: Mon Dec 28 16:26:48 2020
OS/Arch: windows/amd64
Experimental: true
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 2
 Server Version: 20.10.2
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.1316)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.894GiB
 Name: DESKTOP-I5C88UP
 ID: S5UH:W2I7:FXWC:QG5X:JXZG:HABZ:K4IX:2MBH:UOVX:IDVD:6W2R:W74F
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 26
  System Time: 2021-01-26T02:14:10.5698827Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
