### ISSUE TITLE
[cgroup2] docker info: `SwapLimit = true` is set without checking

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41926]
**Description**

https://github.com/moby/moby/blob/v20.10.2/pkg/sysinfo/cgroup2_linux.go#L69-L84

`info.SwapLimit = true` should be set only if `memory.swap.max` exists.

When the swap support is present (with `swapaccount=1` in kernel cmdline), `memory.swap.max` appears in a non-top cgroup.
i.e., `/sys/fs/cgroup/${dockerd_cgroup}/memory.swap.max` appears, but `/sys/fs/cgroup/memory.swap.max` does not appear (unless we are in dind)

Related: https://github.com/containers/podman/pull/8197/files

** `docker version` **
20.10.2

**Comment by jmguzik** [comment]
I can try this one. It will be my first issue in moby, so it can take a while.
/assign
