### ISSUE TITLE
Docker rootless does not exit properly if containers are running

### ISSUE THREAD

**Issue by WhyNotHugo** [moby/moby#41944]
**Description**

I'm running docker rootless (as a systemd service).

When stopping the service:

- ... if containers are NOT running, docker exits fine.
- ... if containers are running, docker stops the containers immediately, but **does not** exit fine, but is killed by systemd after the 90s timeout (service had 90s to exit cleanly before being `SIGKILL`'d.

This initial became evident since, when shutting down the system, systemd waits 90s for docker to stop, and _then_ kills it, so it's been slowing down people's shutdown.

I'm the maintainer for the docker-rootless [ArchLinux AUR package](https://aur.archlinux.org/packages/docker-rootless-extras-bin/), and several other users report the same issue.

**Steps to reproduce the issue:**

1. Run docker rootless
2. Run a container (e.g.: `docker run --rm -it node:12 bash`)
3. Stop the service (e.g.: `systemctl --user stop docker.service`)

**Describe the results you received:**

The container is killed immediately, but the docker service does not stop until the 90s timeout (systemd sends a SIGKILL after that time). Changing the systemd's timeout makes docker take that long to exit.

This _does not_ happen is no containers are running.

**Describe the results you expected:**

The docker service should exit immediately.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        2291f610ae
 Built:             Tue Jan 19 17:19:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm having this issue on a physical ArchLinux machine, and other Arch users report the same issue.

**Comment by thaJeztah** [comment]
Just to be sure; you're  seeing the same issue on docker 20.10.2 as well? https://github.com/moby/moby/compare/v20.10.1...v20.10.2

Also (not sure which patch release it went in); https://github.com/docker/docker-ce-packaging/pull/514

**Comment by kakawait** [comment]
> Just to be sure; you're seeing the same issue on docker 20.10.2 as well? [v20.10.1...v20.10.2](https://github.com/moby/moby/compare/v20.10.1...v20.10.2)
> 
> Also (not sure which patch release it went in); [docker/docker-ce-packaging#514](https://github.com/docker/docker-ce-packaging/pull/514)

About  [docker/docker-ce-packaging#514](https://github.com/docker/docker-ce-packaging/pull/514) I don't think could be related because is about docker non-rootless. And rootless service is a bit (completly) different https://aur.archlinux.org/cgit/aur.git/tree/docker.service?h=docker-rootless-extras-bin

**Comment by WhyNotHugo** [comment]
_Slightly_ different behaviour in 20.10.2, but the issue is still there:

```console
$ docker run --rm -it node:12 bash
root@bd22ca95a54e:/# exit
ERRO[0022] error waiting for container: unexpected EOF

~ took 22s
$
```

The `ERRO` is new on 20.10.2.

However, docker still did not stop before the timeout and was killed by systemd.

Another extra details I've noticed, after I `stop` the `docker.service`, if I restart it, docker does not work:

```console
$ docker ps
Cannot connect to the Docker daemon at unix:///run/user/1000/docker.sock. Is the docker daemon running?
$ systemctl --user status docker.service
● docker.service - Docker Application Container Engine (Rootless)
     Loaded: loaded (/usr/lib/systemd/user/docker.service; disabled; vendor preset: enabled)
    Drop-In: /home/hugo/.homesick/repos/dotfiles/home/.config/systemd/user/docker.service.d
             └─override.conf
     Active: active (running) since Wed 2021-01-27 18:55:59 CET; 1s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com/engine/security/rootless/
   Main PID: 14688 (rootlesskit)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/docker.service
             ├─14688 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /us>
             ├─14701 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave >
             ├─14717 slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 14701 tap0
             ├─14725 dockerd
             └─14752 containerd --config /run/user/1000/docker/containerd/containerd.toml --log-level info

Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003418123+01:00" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003430991+01:00" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003441770+01:00" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003456594+01:00" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003468019+01:00" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003479588+01:00" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003491360+01:00" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003502382+01:00" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
Jan 27 18:56:00 victory dockerd-rootless.sh[14752]: time="2021-01-27T18:56:00.003566801+01:00" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
Jan 27 18:56:00 victory dockerd-rootless.sh[14725]: time="2021-01-27T18:56:00.956210041+01:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/user/1000/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///run/user/1000/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
```

I'm clarifying this last point since it might clarify in what state the docker daemon ends up -- feel free to ignore it if it looks like a separate issue.

**Comment by AkihiroSuda** [comment]
I can repro this on Ubuntu 20.10 via systemd unit.

However, I can't repro when I run `dockerd-rootless.sh` on terminal and hit Ctrl-C...

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/41947

**Comment by WhyNotHugo** [comment]
Thanks for narrowing it down and finding a fix so quickly! :+1:
