### ISSUE TITLE
Container in an incorrect 'UP' status

### ISSUE THREAD

**Issue by coderwangke** [moby/moby#41941]
**Description**
I observe that the Contianer is in the UP state and the task (from ctr task list) is in the STOPPED state.
Container:
![image](https://user-images.githubusercontent.com/42019725/105995262-b4143d00-60e3-11eb-8999-c62eddcc7cb9.png)
Task:
![image](https://user-images.githubusercontent.com/42019725/105995295-c0989580-60e3-11eb-934d-9797652e6381.png)

**Describe the results you received:**
the exec stdio file is still there.
![image](https://user-images.githubusercontent.com/42019725/105992323-ef147180-60df-11eb-9278-8ccdeeededb9.png)

the docker can not deal 'tasks/exit' event.
![image](https://user-images.githubusercontent.com/42019725/105992437-1408e480-60e0-11eb-94d2-20e832b1ae19.png)
and write stdout stuck in cond.Wait(), The initial reason is that the length exceeds the BlockThreshold.
![image](https://user-images.githubusercontent.com/42019725/105992579-461a4680-60e0-11eb-9104-789aa655e8d0.png)

**Describe the results you expected:**
Delete the container correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 154
  Running: 109
  Paused: 0
  Stopped: 45
 Images: 62
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.105-19-0008
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.41GiB
 Name: vm-2-42-centos
 ID: 7ZD5:3KAS:KRHV:JVXS:WADR:R2AZ:TQ47:BFPB:M6ZH:BWU2:MAIS:RPQY
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by coderwangke** [comment]
kind/bug

**Comment by coderwangke** [comment]
Derek add label: kind/bug

**Comment by coderwangke** [comment]
@AkihiroSuda

**Comment by AkihiroSuda** [comment]
Could you try Docker 20.10 ?

**Comment by coderwangke** [comment]
@AkihiroSuda Haven't tried yet. I think Docker 20.10 had the same problem too.

**Comment by coderwangke** [comment]
[goroutine-stacks-2021-01-27T164933+0800.log](https://github.com/moby/moby/files/5880410/goroutine-stacks-2021-01-27T164933%2B0800.log)

**Comment by coderwangke** [comment]
> [goroutine-stacks-2021-01-27T164933+0800.log](https://github.com/moby/moby/files/5880410/goroutine-stacks-2021-01-27T164933%2B0800.log)

gountine stacks.

**Comment by ningmingxiao** [comment]
how you resolve this bug? will my commit work?
