### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by malishahi** [moby/moby#41940]
**Description**

1. This a kind of a FEATURE REQUEST. Searching on the Web, I did not find proper documentation on installation of Moby on Ubuntu. Is there any guide on this?
2. Reading legal notice, it says we should make sure we have the permission to use Moby, so I did not understand if this open source project can be used for testing purposes?

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
> This a kind of a FEATURE REQUEST. Searching on the Web, I did not find proper documentation on installation of Moby on Ubuntu. Is there any guide on this?

```console
$ make
$ sudo cp -f bundles/binary-daemon/dockerd-dev /usr/bin/dockerd
```

> Reading legal notice, it says we should make sure we have the permission to use Moby, so I did not understand if this open source project can be used for testing purposes?

Moby is licensed under the terms of Apache License 2.0: https://github.com/moby/moby/blob/master/LICENSE https://github.com/moby/moby/blob/master/NOTICE

**Comment by malishahi** [comment]
@AkihiroSuda thanks for the note. I faced this issue:

~/moby$ make
docker build  --build-arg=GO_VERSION  -f "Dockerfile" --output=bundles/ --target=binary --build-arg VERSION --build-arg DOCKER_GITCOMMIT --build-arg PRODUCT --build-arg PLATFORM --build-arg DEFAULT_PRODUCT_LICENSE .
unknown flag: --output
See 'docker build --help'.
Makefile:182: recipe for target 'binary' failed
make: *** [binary] Error 125

**Comment by AkihiroSuda** [comment]
You might need `export DOCKER_BUIDKIT=1`

**Comment by malishahi** [comment]
@AkihiroSuda the same error.

**Comment by AkihiroSuda** [comment]
Your docker might be too old. Needs to be v19.03 at least.

**Comment by malishahi** [comment]
It worked on Ubuntu 20.04 LTS with Docker version 20.10.5.
