### ISSUE TITLE
docker\docker@v20.10.2+incompatible\client\container_commit.go:17:15: undefined: reference.ParseNormalizedNamed

### ISSUE THREAD

**Issue by chenxuehui1** [moby/moby#41952]
在调用github.com\docker\docker@v20.10.2+incompatible\client的时候，运行项目的时候，出现下面的问题：github.com\docker\docker@v20.10.2+incompatible\client\container_commit.go:17:15: undefined: reference.ParseNormalizedNamed

github.com\docker\docker@v20.10.2+incompatible\client\container_commit.go:25:9: undefined: reference.TagNameOnly
github.com\docker\docker@v20.10.2+incompatible\client\container_commit.go:30:16: undefined: reference.FamiliarName
github.com\docker\docker@v20.10.2+incompatible\client\image_create.go:16:14: undefined: reference.ParseNormalizedNamed
github.com\docker\docker@v20.10.2+incompatible\client\image_create.go:22:25: undefined: reference.FamiliarName
github.com\docker\docker@v20.10.2+incompatible\client\image_import.go:18:16: undefined: reference.ParseNormalizedNamed
github.com\docker\docker@v20.10.2+incompatible\client\image_pull.go:23:14: undefined: reference.ParseNormalizedNamed
github.com\docker\docker@v20.10.2+incompatible\client\image_pull.go:29:25: undefined: reference.FamiliarName
github.com\docker\docker@v20.10.2+incompatible\client\image_pull.go:59:8: undefined: reference.TagNameOnly
github.com\docker\docker@v20.10.2+incompatible\client\image_push.go:19:14: undefined: reference.ParseNormalizedNamed
github.com\docker\docker@v20.10.2+incompatible\client\image_push.go:19:14: too many errors

**Comment by chenxuehui1** [comment]
解决了

**Comment by Sia2010** [comment]
请问是怎么解决的啊
