### ISSUE TITLE
container cannot start when enable no-new-privileges on centos with selinux enforcing

### ISSUE THREAD

**Issue by pandaamanda** [moby/moby#41951]
**Description**

when enable os selinux and docker no-new-privileges, the containers start failed.

**Steps to reproduce the issue:**
1. set  SELINUX=enforcing in /etc/selinux/config and reboot system
2. set "selinux-enabled": true in  /etc/docker/daemon.json and reboot docker
3. docker run -itd --name nginx-test --security-opt no-new-privileges 10.46.177.49:5000/nginx

**Describe the results you received:**
```
[root@node24 ~]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@node24 ~]# docker ps -a |grep nginx-test
3d5771bb3bb0        10.46.177.49:5000/nginx                  "nginx -g 'daemon of…"   13 seconds ago       Exited (1) 11 seconds ago                           nginx-test
[root@node24 ~]# docker logs 3d5771bb3bb0
standard_init_linux.go:207: exec user process caused "operation not permitted"
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 14
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: NewStart Carrier Grade Server Linux Core 5.04
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.358GiB
Name: node24
ID: ZPMF:JLX2:NWGZ:PUYE:T7ZQ:H4EK:Z6JS:5XIN:XUFA:OUQ6:BE5L:EJMO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
[root@node24 ~]# cat /etc/os-release
NAME="NewStart CGS Linux Core"
VERSION="5.04"
ID="ZTEOS"
ID_LIKE="centos rhel fedora"
VERSION_ID="5.04"
PRETTY_NAME="NewStart Carrier Grade Server Linux Core 5.04"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="http://www.gd-linux.com/"
BUG_REPORT_URL="http://www.gd-linux.com/"

[root@node24 ~]# uname -a
Linux node24 3.10.0-693.21.1.el7.x86_64 #1 SMP Mon Apr 15 10:48:16 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
are you seeing this problem with any image? the image you're using in your example looks like a custom image that we won't have access to (`10.46.177.49:5000/nginx`)


Also note that docker 18.09 reached EOL, and no longer maintained

**Comment by pandaamanda** [comment]
thanks for reply.
the nginx image is just a example, i can see the problem with any images.   about the docker version 18.09,  you mean i should use a newer version to test this problem?

**Comment by pandaamanda** [comment]
@thaJeztah   
i reinstall docker with version 19.03.9, now some containers can run successfully.  
`docker run -itd --name nginx-test --security-opt no-new-privileges nginx` still failed.
```
[root@node24 ~]# docker logs nginx-test
standard_init_linux.go:207: exec user process caused "operation not permitted"
```

**Comment by pandaamanda** [comment]
@thaJeztah  Looking forward to your reply

**Comment by thaJeztah** [comment]
> docker version 18.09 reached EOL, you mean i should use a newer version to test this problem?

Yes, older versions are unmaintained, and have known vulnerabilities, so definitely should no longer be used.

>`docker run -itd --name nginx-test --security-opt no-new-privileges nginx` still failed.

So, the `nginx` image itself runs as `root`, but falls back to a non-privileged user for the worker processes;

```console
$ docker top nginx-test -o uid,gid,pid,cmd

UID                 GID                 PID                 CMD
0                   0                   36431               nginx: master process nginx -g daemon off;
101                 101                 36492               nginx: worker process
```

I'm wondering if that's what's causing the issue for that particular container. 

Do the SELinux audit logs show what's blocked? 


https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-fixing_problems-searching_for_and_viewing_denials
https://wiki.gentoo.org/wiki/SELinux/Tutorials/Where_to_find_SELinux_permission_denial_details
