### ISSUE TITLE
Incorrect tag for version 20.10.3

### ISSUE THREAD

**Issue by DavidFW1960** [moby/moby#41980]
**Description**

**Steps to reproduce the issue:**
1. Incorrect tag for version 20.10.3 - should have the latest tag instead of the old version 19.x
2. 
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Do you mean this issue? https://twitter.com/thajeztah/status/1356577606745923584?s=21

![4453A19C-6E54-4573-AAB6-90932DA98BE8](https://user-images.githubusercontent.com/1804568/106821235-0b368680-667d-11eb-9ae3-68fa444a9464.jpeg)
![75B0BB52-698A-4B3F-A92A-FA8D4C2E483A](https://user-images.githubusercontent.com/1804568/106821240-0c67b380-667d-11eb-923f-9b92f5a14dca.jpeg)

**Comment by DavidFW1960** [comment]
Yes that one. Doesn't github give control over the tags?

**Comment by thaJeztah** [comment]
It prefers "releases" (which are a "GitHub" concept) over tags, but automatically assumes that a release associated with the last tag (by date) is the "most current" release.

Unfortunately that causes the _actual_ latest release to be hidden (we released 20.10.3 first, as it's the current release, then did a security release for the previous 19.03 release, for which we still maintain security fixes for a short period)

Because of that, the 19.03 patch release was tagged "after" the 20.10 patch release, and thus shows up as "latest" 😔

**Comment by thaJeztah** [comment]
Perhaps @clarkbw knows if there's a way to override that, or if there's plans to add an option for that 🤔

**Comment by DavidFW1960** [comment]
Yeah... it's a PITA because I get notifications on my system when an 'update' is available and that is based on the Latest tag.

**Comment by clarkbw** [comment]
We've got this with packages and are giving up on Latest tag for this reason. I'll have to check if there are plans for others to give up as well.

**Comment by thaJeztah** [comment]
Ouch, yes.

FWIW; the tag itself might be a better indicator for "when" we do a release (we create the "release" on GitHub after packages are put up on download.docker.com, and there may be some time between.

Are you installing using the deb/rpm packages from download.docker.com ? If so, using rpm/apt to get what's "latest" may work as well

**Comment by DavidFW1960** [comment]
No I'm using regular apt-update
I did hack together a script that writes the version to my MQTT Broker and I can pick it up from there.
```
versionstring=$(sudo apt-cache madison docker-ce | head -n 1 | awk '{print $3}' | cut -f1 -d"~" | cut -f2 -d":")
versionstring='{"state":"'"v$versionstring"'"}'
echo Docker Version Available $versionstring
```
I'm sure that's a really shitty hack I am using though..

**Comment by thaJeztah** [comment]
Yes, it's a bit ugly, but not sure if there's a better way currently if you need the version number. If you're looking for "latest", of course, `apt-get update && apt-get install docker-ce-cli docker-ce containerd.io` would work (and update to latest version of the engine, cli and containerd)

Looking at the above, I don't think there's much we can do currently (other than _removing_ the 19.03 release (but keeping the tag of course)), which may be disruptive as well.

Let me close this ticket, but feel free to continue the conversation 👍

**Comment by DavidFW1960** [comment]
ok no worries.. I'm not so much looking for the latest just looking to know what the latest is. If I'm not running the latest I get a notification but with 19.x tagged as latest it wasn't working. When I get the notification it prompts me to do a debian update (I don't only update docker)
Anyway my shell command seems to work fine.
Thanks!
