### ISSUE TITLE
19.03.15 docker-ce does not compile on LibreELEC buildhost - error is: idtools.CurrentIdentity

### ISSUE THREAD

**Issue by heitbaum** [moby/moby#41986]
**Description**

compiling docker-ce 19.03.15 errors with idtools.CurrentIdentity
19.03.14 builds correctly

**Steps to reproduce the issue:**
1. Run the LibreELEC compile 
2. The package.my that we are using is: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/docker/package.mk
3. Log file below.

**Describe the results you received:**

http://paste.ubuntu.com/p/DpHRVRbdSs/

**Describe the results you expected:**

Successful compile

**Additional information you deem important (e.g. issue happens only occasionally):**

reproducible 100% of the time

**Output of `docker version`:**

```
19.03.15
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is being built as a cross-compile target using Ubuntu 18.04

**Comment by AkihiroSuda** [comment]
Please report to the package maintainer of the distro.

**Comment by heitbaum** [comment]
Found the issue. Additional extension code added to idtools.go under following commit. https://github.com/docker/docker-ce/commit/4bb40a359791f75e9967a834e7906cbfd4094a72#diff-5af46d9f940e9786160035d29a635d5b83987219deed627899f846535a9e16a9

Fix added to LibreELEC addon package.mk 
https://github.com/LibreELEC/LibreELEC.tv/pull/5100/files#diff-d10acbf667916ab74f4e9b214183fed499c4371d069f0d9694b824753ce0dd66R78
