### ISSUE TITLE
docker build --ulimit flag has no effect?

### ISSUE THREAD

**Issue by yxxhero** [moby/moby#41997]
`docker build --ulimit flag has no effect?  `

`docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:16:13 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment]
This flag is currently only supported with the "classic" (non-buildkit) builder. Are you using BuildKit? (i.e., have `DOCKER_BUILDKIT=1` set?) the CLI currently "silently" ignores options that are not supported by buildkit (PR to change that; https://github.com/docker/cli/pull/2736)

Without buildkit, this option should work;

```bash
DOCKER_BUILDKIT=0 docker build --ulimit nofile=1024:1024 -<<EOF
FROM debian
RUN ulimit -n; exit 1
EOF


> FROM debian
> RUN ulimit -n; exit 1
> EOF
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian
 ---> ef05c61d5112
Step 2/2 : RUN ulimit -n; exit 1
 ---> Running in b84625b66715
1024
```

But with buildkit enabled, it won't have an effect;

```bash
DOCKER_BUILDKIT=1 docker build --ulimit nofile=1024:1024 -<<EOF
FROM debian
RUN ulimit -n; exit 1
EOF

[+] Building 1.0s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.3s
 => => transferring dockerfile: 76B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.2s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/debian:latest                                                                                                                                       0.0s
 => CACHED [1/2] FROM docker.io/library/debian                                                                                                                                                         0.0s
 => ERROR [2/2] RUN ulimit -n; exit 1                                                                                                                                                                  0.5s
------
 > [2/2] RUN ulimit -n; exit 1:
#5 0.356 1048576
------
```

**Comment by yxxhero** [comment]
Thanks, When I add DOCKER_BUILDKIT=0, it works. But, When I docker run, the effect lost. @thaJeztah

**Comment by thaJeztah** [comment]
> Thanks, When I add DOCKER_BUILDKIT=0, it works. But, When I docker run, the effect of the image by docker build lost.
> The --memory is the same behave. How I can keep --ulimit info when run the image. Thanks very much.

That is expected; options such as `--ulimit`, `--memory`, `--cpu`, `--network` are all _runtime_ options. This means that they can be set for the "build containers" used during build (which can be needed in some rare situations where build-containers need additional privileges/resources), but they're not persisted in the image itself.

This is by design; images should not be able to obtain additional privileges automatically, as that would be a security issue. If an image/container needs additional privileges or limits, those options must be set when _running_ the image.

If your original intent was to set these options in the image, but the `docker build` _itself_ does not need these additional `--ulimit`'s (_during build_), I would recommend using switching back to using BuildKit, as development on the "classic" builder is mostly frozen (BuildKit is the new builder, and will be the default at some point).

**Comment by yxxhero** [comment]
Thanks , how I can  switch back to using BuildKit. Please help me. Thanks very mucn again! @thaJeztah

**Comment by thaJeztah** [comment]
you can enable it by setting the `DOCKER_BUILDKIT=1` environment variable

**Comment by yxxhero** [comment]
Yes  @thaJeztah  How I can set these options in the image by DOCKER_BUILDKIT=1. thanks very much. thanks your reply.

**Comment by thaJeztah** [comment]
You can't set them in the image; as I mentioned above, these options are not stored as part of the image, and must be set at runtime, when running a container from the image (`docker run --sysctl .. --memory ... `)

**Comment by yxxhero** [comment]
oh. I know. Thanks very much.

**Comment by thaJeztah** [comment]
You're welcome! Hope this helps
