### ISSUE TITLE
Mounting CIFS shares using hostname does not work

### ISSUE THREAD

**Issue by bizmate** [moby/moby#42007]
**Description**

Mounting CIFS shares as docker volumes does not work using a hostname.

**Steps to reproduce the issue:**

As described [here ](https://forums.docker.com/t/docker-mount-cifs-samba-volume/104224)

1. Mount share

```
docker volume create \

 --driver local \
 --opt type=cifs \
 --opt device=//uxxxxx.your-server.de/backup \
 --opt o=username=uxxxxxxx,password=***********,file_mode=0777,dir_mode=0777 \
 --name testRemoteVolume
```
The above returns the name of the volume *testRemoteVolume*, no errors at this stage.

2. Inspecting the volume shows the mountpoint, looks correct to me

```
$ docker volume inspect testRemoteVolume
[
    {
        "CreatedAt": "2021-02-09T17:54:01Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/testRemoteVolume/_data",
        "Name": "testRemoteVolume",
        "Options": {
            "device": "//uxxxxx.your-server.de/backup",
            "o": "username=uxxxxxxx,password=***********,file_mode=0777,dir_mode=0777",
            "type": "cifs"
        },
        "Scope": "local"
    }
]

```

3. Trying to use the volume in a container does show errors when it tries to mount.
```
$ docker run -d   --name cifVolTest   --mount source=testRemoteVolume,target=/remoteVolume   nginx:latest bash
74615273335cba35f489e9df5ce4f393f0d1ac585469aeee32561f43ccd1e1a2
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/testRemoteVolume/_data': failed to mount local volume: mount //uxxxxx.your-server.de/backup:/var/lib/docker/volumes/testRemoteVolume/_data, data: username=uxxxxxxx,password=***********,file_mode=0777,dir_mode=0777: invalid argument.
```

**Describe the results you received:**
See point 3 above

**Describe the results you expected:**
Mount works correctly if using the hostname. Currently this only works with IPs but IPs are subject to change.

**Additional information you deem important (e.g. issue happens only occasionally):**

Mounting using mount.cifs (present in ubuntu) works fine with ip or hostname but cannot say the same on docker.

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 406
 Server Version: 20.10.3
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 1426
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-135-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.72GiB
 Name: bizmate-i7
 ID: D4K6:B2ZE:7YOK:K676:EV6Q:POQR:P3SE:R6UV:5A56:SHA5:VHSF:U6LD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local development host, although I am planning to use virtual servers and docker swarm.

**Comment by thaJeztah** [comment]
The example in the PR that enabled lookups is using a different syntax; can you try if that syntax works? https://github.com/moby/moby/pull/39250#issuecomment-494916195

**Comment by bizmate** [comment]
@thaJeztah thank you for pointing the PR, I did not notice it before posting. 
Also I think the best comment where I got it working from is this on https://github.com/moby/moby/pull/39250#issuecomment-765172947

To anyone interested when reading this post the fix is to add the address option such as

```
docker volume create \

 --driver local \
 --opt type=cifs \
 --opt device=//uxxxxx.your-server.de/backup \
 --opt o=addr=uxxxxx.your-server.de,username=uxxxxxxx,password=***********,file_mode=0777,dir_mode=0777 \
 --name testRemoteVolume
```
**--opt o=addr=uxxxxx.your-server.de,**

Also I noticed some comments related to adding examples to the CIFS specific implementation in the documentation. I must say the use of this extra option, a but redundant but fine,  is not something I need when using mount.cifs . It feels like an example of how to to use CIFS with a hostname would be great on 

https://github.com/docker/docker.github.io/blob/master/storage/volumes.md

**Comment by arobld00** [comment]
@bizmate Did you finally manage to connect via domain name? Because I still cant.

Read this pls https://github.com/docker/compose/issues/8404

**Comment by bizmate** [comment]
@arobld00 Ciao Alberto, one of the differences i see in mine vs your volumes is the use of forward vs backward slashes

mine `device=//uxxxxx.your-server.de/backup`

yours ` device: "\\\\${SRVCIFS}\\documentation\\_shared\\pdfs”`

if the addr option is set then i think docker/compose should be able to do the DNS lookup. Maybe try more variations of your command until hopefully you fix it? BTW this is just a suggestion and i have no understanding of the low level implementations so the way you refer to the CIFS mount might be correct for your system
