### ISSUE TITLE
iptables forwarding rules not being cleaned up upon container removal

### ISSUE THREAD

**Issue by ingenieurmt** [moby/moby#42029]
**Description**

When stopping/removing containers on a custom bridge network, Docker does not remove the iptables forwarding rules relating to that container. This causes various issues with container networking when the container is re-created with the same port(s) exposed.

**Steps to reproduce the issue:**
1. Run `iptables --list` to get a baseline of the iptables configuration.
2. Start a container with a port forward on a custom bridge network.
3. Run `iptables --list` again to see the port forward rule has been inserted.
2. Stop and remove the container and network.
3. Run `iptables --list` again, you will observe that the rule for that container's port forward has not been removed.

**Describe the results you received:**
iptables rules for container port forwards on a custom bridge network are left behind when you stop and remove the container/network.

**Describe the results you expected:**
iptables rules for container port forwards on a custom bridge network should be removed when the container/network is removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue may be specific to Alpine Linux 3.13 hosts, I have not yet tested it on any other host OS.

**Output of `docker version`:**

```
bl:~$ docker version
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.7
 Git commit:        48d30b5b32e99c932b4ea3edca74353feddd83ff
 Built:             Thu Feb  4 04:42:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.7
  Git commit:       46229ca1d815cfd4b50eb377ac75ad8300e13a85
  Built:            Thu Feb  4 04:41:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:   
```

**Output of `docker info`:**

```
bl:~$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.15-0-lts
 Operating System: Alpine Linux v3.13
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.845GiB
 Name: bl
 ID: ISHA:NL3H:YPIL:YAJJ:4I7F:GK7Y:ZV4J:WJ2H:TMXD:2SE4:2K5E:QV6F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host is running on a KVM hypervisor provided a third-party cloud provider.

**Comment by thaJeztah** [comment]
Thanks for reporting; wondering if this is a duplicate / the same as the issue that was reported in https://github.com/docker/for-linux/issues/1180 (there's also a number of fixes in libnetwork that are yet to make it into a release: https://github.com/moby/moby/pull/41908)

**Comment by ingenieurmt** [comment]
Seems like the issue has been resolved, possibly with a kernel update.

Docker version: 20.10.3
Kernel version: 5.10.27
