### ISSUE TITLE
Can't install rootless docker due to bug involving slirp4netns on Debian 10

### ISSUE THREAD

**Issue by schklom** [moby/moby#42048]
**Description**
After retrieving slirp4netns from `testing` branch of Debian 10, `curl -fsSL https://get.docker.com/rootless | sh` fails when activating `docker.service`. The buggy line is the one using `slirp4netns `.

**Steps to reproduce the issue:**
1. `sudo apt-get install -y uidmap`
2. `sudo apt-get install -y -t testing slirp4netns`
2. `sudo machinectl shell schklom@`
3. `curl -fsSL https://get.docker.com/rootless | sh`
4. `sh /home/schklom/bin/dockerd-rootless.sh`

**Describe the results you received:**
```
$ sh /home/schklom/bin/dockerd-rootless.sh
+ [ -w /run/user/1001 ]
+ [ -w /home/schklom/ ]
+ rootlesskit=
+ which docker-rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ :
+ :
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z ]
+ which slirp4netns
+ slirp4netns --help
+ grep -qw -- --netns-type
+ net=slirp4netns
+ [ -z ]
+ mtu=65520
+ [ -z slirp4netns ]
+ [ -z 65520 ]
+ [ -z ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/schklom/bin/dockerd-rootless.sh
[rootlesskit:parent] error: failed to setup network &{logWriter:0x400008dec0 binary:slirp4netns mtu:65520 ipnet:<nil> disableHostLoopback:true apiSocketPath: enableSandbox:true enableSeccomp:true ifname:tap0}: waiting for ready fd (/usr/bin/slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 1442 tap0): slirp4netns failed
[rootlesskit:child ] error: parsing message from fd 3: EOF
```

**Describe the results you expected:**
I expected the installer to finish successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Starting `dbus.service` doesn't help.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:29:43 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
I have no idea why it is written experimental: true, given that experimental flag is supposed enabled to be for Docker 19. Could my bug come from there ?

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a physical Raspberry Pi 4 8GB RAM with Debian 10 installed on it.
```
$ uname -a
Linux schklom 5.10.0-3-arm64 #1 SMP Debian 5.10.13-1 (2021-02-06) aarch64 GNU/Linux

$ slirp4netns -v
slirp4netns version 1.0.1
commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
libslirp: 4.4.0
```

Does anyone know what is happening ?

**Comment by AkihiroSuda** [comment]
> After retrieving slirp4netns from testing branch of Debian 10,

Do you mean it was working when you install slirp4netns from https://github.com/rootless-containers/slirp4netns/releases , or from Debian stable?

Could you try this and see whether it shows some error messages?

Terminal 1:
```console
unshare --user --map-root-user --net --mount sh -exc 'echo $$ > /tmp/pid && sleep infinity'
```

Terminal 2:
```console
slirp4netns --configure --mtu=65520 --disable-host-loopback --enable-sandbox --enable-seccomp $(cat /tmp/pid) tap0
```

**Comment by AkihiroSuda** [comment]
Workaround to use VPNkit instead of slirp4netns:

Add`Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=vpnkit"` to `~/.config/systemd/user/docker.service` and then run `systemctl --user daemon-reload`.

**Comment by schklom** [comment]
> > After retrieving slirp4netns from testing branch of Debian 10,
> 
> Do you mean it was working when you install slirp4netns from https://github.com/rootless-containers/slirp4netns/releases , or from Debian stable?

I mean I had a version issue before because `slirp4netns` was v0.2.something:
```
Either VPNKit or slirp4netns (>= 0.4.0) needs to be installed separately.
```
And since `vpnkit` is apparently unavailable from standard Debian apt sources, I tried the other :P

> Could you try this and see whether it shows some error messages?

Here are the results:
Terminal 1 not much happens
```
$ unshare --user --map-root-user --net --mount sh -exc 'echo $$ > /tmp/pid && sleep infinity'
+ echo 1715
+ sleep infinity
```
Terminal 2
```
$ slirp4netns --configure --mtu=65520 --disable-host-loopback --enable-sandbox --enable-seccomp $(cat /tmp/pid) tap0
WARNING: Support for seccomp is experimental
sent tapfd=5 for tap0
received tapfd=5
Starting slirp
* MTU:             65520
* Network:         10.0.2.0
* Netmask:         255.255.255.0
* Gateway:         10.0.2.2
* DNS:             10.0.2.3
* Recommended IP:  10.0.2.100
enable_seccomp failed
do_slirp is exiting
do_slirp failed
parent failed
```
It is a strange coincidence how the network is 10.0.2.* (wifi) when the server is only connected to a network 10.0.0.* (ethernet).

I can't try your other suggestion now because I have a major bug and I can't do any sudo command `sudo: no tty present and no askpass program specified`, or login with a new ssh session `PTY allocation request failed on channel 0`. It started right after I tried your commands. I need to reinstall the OS, but luckily I will only lose a bit of time since I don't have any important data on the server.

I will retry this after I reinstall everything properly, and update you :)

**Comment by AkihiroSuda** [comment]
Thanks for trying, running dockerd-rootless.sh with `DOCKERD_ROOTLESS_ROOTLESSKIT_SLIRP4NETNS_SECCOMP=false` might solve the issue.

> I can't try your other suggestion now because I have a major bug and I can't do any sudo command sudo: no tty present and no askpass program specified, or login with a new ssh session PTY allocation request failed on channel 0. It started right after I tried your commands. I need to reinstall the OS, but luckily I will only lose a bit of time since I don't have any important data on the server.

🤔 I don't think rootless processes can break the host.

If this catastrophe is really related to my commands, we are hitting some serious kernel bug... 😕

**Comment by schklom** [comment]
I installed Debian 11 instead of Debian 10 since it was available.
Now, no need to look for testing branch to install `slirp4netns` v1, and everything works well, I managed to run docker commands :D
I think me breaking the host was not because of you, but because of something else I had done before and was incompatible with your commands, though I can't see what exactly.

In the end, it all works out so thanks for breaking my raspberry pi ^^
Not much harm done, I now have Debian 11, and can use rootless docker. Win-win, thank you very much ;)

I don't think anyone would be willing to recreate my bug to investigate it, so I think I should close this issue.

## To anyone who has the same issue and is locked out of the server
I found a way to get in: `ssh -t ...` or `ssh -S ...` (don't remember which, but one worked),
source: https://stackoverflow.com/a/22651598 and https://stackoverflow.com/a/39553081

## Permanent fix
Install Debian 11 instead of Debian 10

**Comment by schklom** [comment]
Hello again !

I just noticed that Debian 11 is still testing, not stable (I'm kind of new to Debian ^^)
Since I want a longer term solution without having to reinstall the OS and tinker too much later, I'm back on Buster.

Building `vpnkit` fails because of an `opam` version error, here are the steps I took:
```
$ adduser dockeruser
$ sudo machinectl shell dockeruser@
$ mkdir -p ~/.config/systemd/user
$ echo 'Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=vpnkit"' > docker.service
$ exit

$ sudo apt install -y wget opam pkg-config
$ git clone https://github.com/moby/vpnkit.git
$ unset OPAMROOT
$ cd vpnkit
$ make
```
In the end:
```
+ export PATH=/home/dockeruser/vpnkit/_build/opam/4.07.0/bin:/home/dockeruser/vpnkit/_build/opam/4.07.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ opam install depext -y -v
[ERROR] depext unmet availability conditions: opam-version >= "1.1.0" & opam-version < "2.0.0~beta5"
'opam install depext -y -v' failed.
make: *** [Makefile:27: /home/dockeruser/vpnkit/_build/opam] Error 5
```
The version I have is:
```
$ opam --version
2.0.3
```

Should you guys change the max version requirement ? Or should I install version `2.0.0~beta4` ?

**Comment by AkihiroSuda** [comment]
The vpnkit issue should be reported to https://github.com/moby/vpnkit

**Comment by AkihiroSuda** [comment]
To use slirp4netns on Debian 10, please use the binary available in https://github.com/rootless-containers/slirp4netns/releases

**Comment by schklom** [comment]
Everything works ! Thank you so much for all the help and time you have given :D
Hope you have a great day, and stay safe :)

**Comment by rohankm** [comment]
Hi im getting this error on Ubuntu 22.04.2 LTS
can someone please help me how to solve
```
+ [ -w /run/user/1000 ]
+ [ -d /home/dockeruser ]
+ rootlesskit=
+ command -v docker-rootlesskit
+ command -v rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ :
+ :
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z  ]
+ command -v slirp4netns
+ slirp4netns --help
+ grep -qw -- --netns-type
+ net=slirp4netns
+ [ -z  ]
+ mtu=65520
+ [ -z slirp4netns ]
+ [ -z 65520 ]
+ dockerd=dockerd
+ [ -z  ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ id -u
+ [ 1000 = 0 ]
+ command -v selinuxenabled
+ exec rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh
open: No such file or directory
[rootlesskit:parent] error: failed to setup network &{logWriter:0xc0001d68c0 binary:slirp4netns mtu:65520 ipnet:<nil> disableHostLoopback:true apiSocketPath: enableSandbox:true enableSeccomp:true enableIPv6:false ifname:tap0 infoMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} info:<nil>}: setting up tap tap0: executing [[nsenter -t 1203 -n -m -U --preserve-credentials ip tuntap add name tap0 mode tap] [nsenter -t 1203 -n -m -U --preserve-credentials ip link set tap0 up]]: exit status 1
[rootlesskit:child ] error: parsing message from fd 3: EOF
```
