### ISSUE TITLE
Container uid 1000 provokes pid shortage on host (nproc)

### ISSUE THREAD

**Issue by antoinetran** [moby/moby#42069]
**Description**

In one host with multiple containers with processes launched with UID=1000, ssh as ansible (UID = 1000 in host) from another host fails:

```
-sh-4.2$ ssh ansible@dl2pdck-s00.l2pf.dev.mtg
shell request failed on channel 0
-sh-4.2$ ssh ansible@dl2pdck-s00.l2pf.dev.mtg -s /bin/bash
subsystem request failed on channel 0
```

Inside the host as another sudoer user, doing sudo -u fails too:

```
[rancher@dl2pdck-s00 ~]$ sudo -u ansible id
uid=1000(ansible) gid=1000(ansible) groups=1000(ansible),10(wheel)
[rancher@dl2pdck-s00 ~]$ sudo -u ansible bash
bash: fork: retry: No child processes
```

**Steps to reproduce the issue:**
1. Launch many container with UID = 1000 in the same host, or just one with many processes (minimum 4096 processes)
2. Ssh in the host with UID = 1000
3. it will fail

**Describe the results you received:**
Cannot create new process with UID = 1000

**Describe the results you expected:**

Expected behavior: to be able to ssh as ansible.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Analyze:**
This is because of nproc limit in host and uid collision.

[ansible@dl2pdck-s00 rancher]$ ulimit -a
max user processes              (-u) 4096

[rancher@dl2pdck-s00 ~]$ ps h -Led -o user | sort | uniq -c | sort -n|grep ansible
   4336 ansible

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Red Hat Enterprise Linux Server release 7.8 (Maipo)
Linux dl2psto-s00.l2pf.dev.mtg 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
docker-ce-19.03.12-3.el7.x86_64
RKE Rancher 2.4.8 Kubernetes 1.18.X

This looks like https://github.com/moby/moby/issues/31424 with the difference that the symptoms appears in host. One can make too much processes in a container and prevent admin to ssh in host.

I'm not sure but docker has a PID cgroup feature, that would allow a separation of PID from container and host? Should this be enabled by default?

**Comment by AkihiroSuda** [comment]
Expected behavior. You can specify `--pids-limit` to limit the number of the processes.
