### ISSUE TITLE
Docker installation fails on RHEL 7 Server

### ISSUE THREAD

**Issue by lawilog** [moby/moby#42086]
When trying to install Docker on Red Hat Enterprise Linux 7 Server (my version is 7.9), one is referred to the [CentOS installation guide](https://docs.docker.com/engine/install/centos/). On https://download.docker.com/linux/ there is an item "rhel", so it seems that RHEL is intended to be supported. However, the installation fails:
`sudo yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo`
works fine, but
`sudo yum install docker-ce docker-ce-cli containerd.io`
fails with the error:
> https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

There is a forward from `https://download.docker.com/linux/centos/7Server/` to `https://download.docker.com/linux/centos/7/` but this is not followed when yum tries to download the xml-file directly.

**Comment by AkihiroSuda** [comment]
> On https://download.docker.com/linux/ there is an item "rhel", so it seems that RHEL is intended to be supported. 

RHEL packages are only provided for IBM s390x.
https://download.docker.com/linux/rhel/7/

**Comment by lawilog** [comment]
OK, in any case the redirect from https://download.docker.com/linux/centos/7Server/ to ./7 is not working when yum tries to download https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml directly (Error 404). I guess this applies to CentOS, too.

As far as I understand, CentOS (in those versions) is designed to be binary-compatible with RHEL. Hence, fixing above link would also make it possible to install docker on RHEL 7 Server.

**Comment by lawilog** [comment]
The download link works now. :)
