### ISSUE TITLE
ContainerListOptions  keyword Quiet not worked!

### ISSUE THREAD

**Issue by einsli** [moby/moby#42092]
**when I use the api of ContainListOption, I want to find the exited container, but when I use the key of Quiet, it didn't work!**

**Steps to reproduce the issue:**
1. define ``` containerListopt = &types.ContainerListOptions{
			Quiet: true,
		}```
2. get the api response result

**When I defined the keyword of Quiet,  I find that I got the results of all container:**

**I hope that When I define the keyword of Quiet, I should get the container whcih status is existed!**

**Comment by thaJeztah** [comment]
Thanks for reporting; interesting; afaik, the `--quiet` option was always implemented in the CLI (so when _presenting_ the API response), as can be seen in the docker/cli repository; https://github.com/docker/cli/blob/v20.10.4/cli/command/container/list.go#L128, and https://github.com/docker/cli/blob/v20.10.4/cli/command/formatter/container.go#L28-L43

```go
func NewContainerFormat(source string, quiet bool, size bool) Format {
	switch source {
	case TableFormatKey:
		if quiet {
			return DefaultQuietFormat
		}
		format := defaultContainerTableFormat
		if size {
			format += `\t{{.Size}}`
		}
		return Format(format)
	case RawFormatKey:
		if quiet {
			return `container_id: {{.ID}}`
		}
```

I had a look at the history of that `Quiet` field, and it looks like it was was originally added in d05aa418b0466553a24d42896f99176cfa29765f (part of https://github.com/moby/moby/pull/18472), and moved around in 8b15839ee85b291266d07f97d9ad6ca0326d1339 (part of the same pull request).

However, it looks like this field was never used; the API always returns the standard information, and the "--quiet" option for `docker ps` is implemented on the CLI side, which uses different formatting when setting this option; https://github.com/moby/moby/blob/2ec468e2844365f0d7e2afd744f322cde25c077e/api/client/ps.go#L73-L79

Let me open a pull request to mark the field as "deprecated". If you're looking for ways to use the "quiet" formatting, I suggest looking at the docker CLI code :+1:

> I hope that When I define the keyword of Quiet, I should get the container whcih status is existed!

Note that the `Quiet` / `--quiet` option is for "quiet", not to return `quit` containers; if you're looking for a way to (only) get containers that have "quit" (exited), you're probably looking for the API equivalent of `--filter status=exited`; https://docs.docker.com/engine/reference/commandline/ps/#filtering

An example of using filters can be used (e.g.) in this test; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/client/container_list_test.go#L81-L90

**Comment by einsli** [comment]
Thanks, but I want to know if there is any official documentation for the open source project. I did not find any documentation for this project on the Internet. It may be that the method I looked for is wrong. Can you provide it if it is convenient for you?
