### ISSUE TITLE
OOM when following "local" logs of high-log-output container

### ISSUE THREAD

**Issue by dnrce** [moby/moby#42125]
**Description**

When logging to the `local` driver, Docker will quickly run out of memory when following the logs of a container with a lot of log output.

This also occurs when following local logs while using a driver such as `syslog` that supports dual logging.

This issue appears to be similar or identical to #39963.

**Steps to reproduce the issue:**
1. Run a container that logs heavily to the `local` driver:

    ```
    ID=$(docker run --rm -d --log-driver local alpine cat /dev/urandom)
    ```
2. Follow the container's logs:

    ```
    docker logs -f $ID > /dev/null
    ```

Alternatively:

1. Run a container that logs heavily to a driver that supports dual logging:

    ```
    ID=$(docker run --rm -d --log-driver syslog --log-opt syslog-address=udp://127.0.0.1:0 alpine cat /dev/urandom)
    ```
2. Follow the container's logs:

    ```
    docker logs -f $ID > /dev/null
    ```

**Describe the results you received:**
`dockerd` exits with `fatal error: runtime: out of memory`.

Stack trace: https://gist.github.com/2f674f1ff24c679ba4778f458facb7b2

**Describe the results you expected:**
Docker remains stable and keeps a reasonable memory footprint.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have been unable to reproduce the issue when logging to the `json-file` driver.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 981.1MiB
 Name: ubuntu-focal
 ID: 5X6F:5OLY:MQHX:I5T3:AVJQ:AMIX:5OBO:XI4L:CI62:LRA7:INKW:26IT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 40
  System Time: 2021-03-08T20:11:15.100104538Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was initially observed in a [Nomad](https://www.nomadproject.io/) environment. Nomad follows logs by default for Docker tasks. The host was a lightly loaded AWS `m5.xlarge` instance.

I have reproduced it on Ubuntu 16.04 and 20.04 using Virtualbox VMs, and on Docker for Mac 3.1.0 (20.10.2).

**Comment by thaJeztah** [comment]
@cpuguy83 PTAL

**Comment by cpuguy83** [comment]
I have a feeling this is happening here: https://github.com/moby/moby/blob/master/daemon/logger/local/read.go#L199

I do see you have a reader attached in your stack trace.
It will help if you can provide a heap dump.

You should be able to get it if you hit the docker API at `/debug/pprof/heap`.

**Comment by dnrce** [comment]
Heap dump: [heap1615862444.out.gz](https://github.com/moby/moby/files/6145718/heap1615862444.out.gz)

Hopefully this is helpful. It's a bit hard to time but I tried to get it shortly before a crash.

Thanks for taking a look!

**Comment by cpuguy83** [comment]
Thanks for grabbing that.

This doesn't look complete. Maybe you can get the svg version?
The `pprof` (https://github.com/google/pprof) command (or if you have `go` on the machine already `go tool pprof`) can generate svg (depends on graphviz).

**Comment by cpuguy83** [comment]
Also just to note, it'd probably be fine to grab it regardless of if it was just before it crashes, just so long as its had some time to exercise the logger.

**Comment by wesgur** [comment]
Seeing the same error here. Is there any updates on this issue?

**Comment by dnrce** [comment]
I have this in my backlog for the next week or so to grab additional `pprof` output (but don't let me stop you from doing so! :wink:).

**Comment by dnrce** [comment]
@cpuguy83 here's what I managed to come up with on another couple attempts:

1. [heap](https://github.com/moby/moby/files/6368379/heap1.gz), alloc_space:
![alloc_space1](https://user-images.githubusercontent.com/1084619/115936194-a19b6c80-a462-11eb-934b-f43c26e6913c.png)
2. [heap](https://github.com/moby/moby/files/6368394/heap2.gz), alloc_space:
![alloc_space2](https://user-images.githubusercontent.com/1084619/115936302-dc9da000-a462-11eb-9d6a-66fe22fe6eb2.png)

I'm still not sure I'm capturing it right but if this still doesn't get you what you need I can try further. This is reproducible with this [`Vagrantfile`](https://github.com/moby/moby/files/6368400/Vagrantfile.txt).

**Comment by varsanojidan** [comment]
Hey, experiencing the same issue here, looking for a fix because we need logs from these critical containers stored locally and shipped.

**Comment by apollo13** [comment]
I am seeing the same stack trace with the splunk logging driver. I think that all (?) loggers nowadays support dual logging since it was backported to the CE edition.

**Comment by apollo13** [comment]
FWIW I do not think "high" log output is neccessary. I managed to trigger this in a nomad setup where nomad (I think) runs log on every container and the amount of logs for a day are few MB (in this testcase).

**Comment by apollo13** [comment]
@cpuguy83 This is what I was able to gather:

alloc space:
![alloc_space](https://user-images.githubusercontent.com/81547/120757155-73ed1d00-c510-11eb-93e8-acb2b32aeb8c.png)
alloc objects:
![alloc_objects](https://user-images.githubusercontent.com/81547/120757145-72bbf000-c510-11eb-9949-cde5198e5592.png)
in use:
![in_use](https://user-images.githubusercontent.com/81547/120757158-751e4a00-c510-11eb-8475-c42e8166adfe.png)
inuse objects:
![inuse_objects](https://user-images.githubusercontent.com/81547/120757159-75b6e080-c510-11eb-9fee-8d7fe4588df0.png)

funnily enough the memory usage "jumped" at one point rather quickly without any log messages in the journal or anything interesting happening:
![graph](https://user-images.githubusercontent.com/81547/120757289-a72fac00-c510-11eb-9df2-33aac6e73729.png)

**Comment by apollo13** [comment]
I just noted that the rendered PNGs are not really readable, I have uploaded the SVGs to https://apolloner.eu/~apollo13/moby/

**Comment by apollo13** [comment]
I wonder if `d.buf` in my case is set to a few gb at some point and never resized down (capacity wise) -- would this be possible? That said I do not see why or how I could have such long log messages?

**Comment by apollo13** [comment]
After another jump in memory I stop all containers (and log tailers). Memory usage did not decrease, restarting docker did ;)

**Comment by agibson-bluecat** [comment]
At work we're running docker containers as part of jobs managed by Hashicorp Nomad, and use the `fluentd` log-driver in our docker daemon config. We've had the same issue with dockerd's memory usage ballooning over time, but we found we could prevent this using the following daemon.json setting:

```
  "log-opts": {
    "cache-disabled": "true",
```

[This disables Docker's "dual-logging" feature](https://docs.docker.com/config/containers/logging/dual-logging/#disable-the-dual-logging-cache), which creates a local log cache for log drivers that don't support local reads. Although this fixes the memory usage issue, it breaks the `docker logs` and `nomad alloc logs` commands. We decided we were fine with this compromise, because we already backup logs to a local file using fluentbit.

Before we made this change, over the course of a few hours dockerd would climb to 4.4 GB memory usage (plus 3 GB into swap space...). After making the change it uses a steady ~240 MB. Hope others find this useful.

**Comment by apollo13** [comment]
@thaJeztah Is there anything the community can provide to move this along and maybe get a patch?

**Comment by Newspaperman57** [comment]
We recently deployed a container that logs a lot more than previously and have been battling unexplained out of memory-issues for dockerd.
We're using the syslog-driver, and "docker logs" isn't critical, but it's definitely nice to have, instead of grep'ing through the syslog for the right time and container

**Comment by kzys** [comment]
What is your Go version on `docker version`? From Go 1.12 to Go 1.15, Go was using MADV_FREE to ask OS to reclaim memory. However it was not updating many userland-surfacing statistics (including RSS) and causing a lot of confusion. So in Go 1.16, the behavior has changed again to use MADV_DONTNEED instead.

Note that moby/moby's Dockerfile is using Go 1.13.15 in 20.10.7.

**Comment by apollo13** [comment]
Interesting, what affect would this have? Wrong pprofs and we'd need to regenerate them using a newer go version?

**Comment by kzys** [comment]
No. I think tools that are aware about Go runtime (such as pprof) is fine. However top and other general-purpose Linux commands may not report RSS and other stats correctly if your Go version is old.

**Comment by kzys** [comment]
Apparently msgLen below is sometimes getting pretty big, such as 71343681. Interestingly the byte sequence (4409e41) is actually appeared in the log file (in my case, /var/lib/docker/containers/09d9263ca4946e5543b0a0c979dd74c94dfc4cfc819204517eb310718d287b2c/local-logs/container.log).

https://github.com/moby/moby/blob/a17f288e65b45a9f4aa54526817ba83220a59709/daemon/logger/local/read.go#L136-L146

**Comment by kzys** [comment]
> I think, Decode() is assuming that the current position of the file is the beginning of a record. But fileWatcher wouldn't guarantee such a thing.

Sorry. No. Decode is not assuming that the current position of the file is the beginning of a record. EOF errors from Decode is ignored like below.

https://github.com/moby/moby/blob/a17f288e65b45a9f4aa54526817ba83220a59709/daemon/logger/loggerutils/logfile.go#L706-L735

However allocating a buffer based on `binary.BigEndian.Uint32(d.buf[:read])` is still problematic and potentially kills dockerd due to `fatal error: runtime: out of memory`.

**Comment by cpuguy83** [comment]
The value we are reading in this section you mentioned is literally the size of the record.

The biggest each log entry can be is 1MB.
Add the protobuf encoding and whatever metadata (timestamp, explicitly specified container labels).
These are not unbounded.
We could look at chunking the records somehow so they do not exceed some pre-determined buffer size.

I am surprised that you would see a buffer of 71MB and would be curious what the data in that file looks like.

**Comment by kzys** [comment]
I was doing `docker run --rm -d --log-driver local alpine cat /dev/urandom` as @dnrce suggested. So this would be too harsh and less realistic.

That being said, IIUC `d.buf[:read]` in Decode() could point literally anywhere in a protobuf-encoded log stream file. Since protobuf embeds UTF-8 strings as is, if a log message contains `abcd` (in UTF-8, `0x61 0x62 0x63 0x64`), is there a possibility of allocating 0x61626364 bytes -> 1633837924 bytes -> 1.6GB?

**Comment by cpuguy83** [comment]
@kzys No we write the log stream as `<record len><record><record len>`, which makes it easy to read both backwards and forwards.
So what's happening there when we set the buffer like above is we are reading `<record len>`.

**Comment by cpuguy83** [comment]
Those lengths have a fixed size.

**Comment by kzys** [comment]
I added Docker Engine a few extra logging and a panic condition like https://github.com/kzys/docker/commit/d4e2856281b8be448a19256f0d8912794ba36532.

By running `docker logs -f $(docker run --rm -d --log-driver local alpine cat /dev/urandom) > /dev/null`, it eventually hits `panic: too large 95e09737`. The byte sequence is appeared in the saved protobuf log file like below.

```
0000cfc0  27 88 0e 13 c5 ce be a3  6e 6e d1 6b 44 76 cf a5  |'.......nn.kDv..|
0000cfd0  b5 76 b0 98 8f 2a 68 30  5f 2f 82 74 53 9e 41 90  |.v...*h0_/.tS.A.|
0000cfe0  c0 84 3c 12 9c c2 79 de  48 17 3e 4b 9d c9 a2 7b  |..<...y.H.>K...{|
0000cff0  7d 53 6b 5f 7f 4f 3a c0  f1 03 14 6a ca 0e 61 3b  |}Sk_.O:....j..a;|
0000d000 [95 e0 97 37]37 62 c3 94  c6 8c f4 05 db ac 89 6d  |...77b.........m|
0000d010  fb a9 23 de 7a a7 32 4e  ed 68 eb 56 86 27 9e 86  |..#.z.2N.h.V.'..|
0000d020  d8 1d 65 f2 c4 b1 35 88  a5 e5 34 bd 4a 51 2e 15  |..e...5...4.JQ..|
0000d030  74 cf 0f 16 f1 1c 68 59  2c 9c 2b 14 cd f6 35 26  |t.....hY,.+...5&|
0000d040  c4 85 6c 9e 9b 29 6f 08  c5 69 da 54 b4 86 46 0f  |..l..)o..i.T..F.|
```

**Comment by apollo13** [comment]
@kzys
> When io.ReadFull() below doesn't read the bytes fully (returning ErrUnexpectedEOF), the next invocation of Decode() must not decode the record header.

But when `ErrUnexpectedEOF` is returned from `readFull`, the `maxDecodeRetry` loop continues to read the bytes from the reader till the length is read fully, no?

**Comment by apollo13** [comment]
The only thing I can imagine is that `readFull` returns `EOF` as shown in your log and now you have read half a msg length from the buffer? and now the next `Decode()` would be in the middle somewhere

**Comment by apollo13** [comment]
Oh that could be it: What happens in `decodeLogEntry` might be the following. Assume there is a message length of 100.

 * The first `readFull` reads 50 bytes because there are only 50 bytes available and set `ErrUnexpectedEOF`
 * The second `readFull` reads 0 bytes and sets `EOF` because we are still at the end of the filestream.
 
Now we return with the error `EOF` and the next decode is in the middle of the stream and tries to read the message length again. Does that make any sense @kzys & @cpuguy83?

**Comment by apollo13** [comment]
Working on the branch @kzys started I can get a stable behavior with the following diff:
```diff
diff --git a/daemon/logger/local/read.go b/daemon/logger/local/read.go
index 81c35902b9..1cbbaf4dc8 100644
--- a/daemon/logger/local/read.go
+++ b/daemon/logger/local/read.go
@@ -5,11 +5,11 @@ import (
        "encoding/binary"
        "io"
 
-       "fmt"
        "bytes"
+       "fmt"
+       "math/rand"
        "os"
        "os/exec"
-       "math/rand"
 
        "github.com/docker/docker/api/types/plugins/logdriver"
        "github.com/docker/docker/daemon/logger"
@@ -124,7 +124,7 @@ func (d *decoder) Decode() (*logger.Message, error) {
                var n int
                n, err = io.ReadFull(d.rdr, d.buf[read:encodeBinaryLen])
                if err != nil {
-                       if err != io.ErrUnexpectedEOF {
+                       if err != io.ErrUnexpectedEOF && err != io.EOF {
                                return nil, errors.Wrap(err, "error reading log message length")
                        }
                        read += n
@@ -189,13 +189,13 @@ func decodeLogEntry(rdr io.Reader, proto *logdriver.LogEntry, buf []byte, msgLen
        var (
                read int
                err  error
-               i int
+               i    int
        )
        for i = 0; i < maxDecodeRetry; i++ {
                var n int
                n, err = io.ReadFull(rdr, buf[read:msgLen+encodeBinaryLen])
                if err != nil {
-                       if err != io.ErrUnexpectedEOF {
+                       if err != io.ErrUnexpectedEOF && err != io.EOF {
                                return nil, errors.Wrap(err, "could not decode log entry")
                        }
                        read += n
```

This seems to suggest that much hunch was correct. I can still imagine edge cases with this patch, but I am running the provided example for minutes without a crash now.

**Comment by apollo13** [comment]
Found an even better panic condition than the one @kzys added:
```diff
diff --git a/daemon/logger/local/read.go b/daemon/logger/local/read.go
index b28aa90651..ab9d21c3c3 100644
--- a/daemon/logger/local/read.go
+++ b/daemon/logger/local/read.go
@@ -3,6 +3,7 @@ package local
 import (
        "context"
        "encoding/binary"
+       "fmt"
        "io"
 
        "bytes"
@@ -121,6 +122,9 @@ func (d *decoder) Decode() (*logger.Message, error) {
                n, err = io.ReadFull(d.rdr, d.buf[read:encodeBinaryLen])
                if err != nil {
                        if err != io.ErrUnexpectedEOF {
+                               if err == io.EOF && read > 0 {
+                                       panic(fmt.Sprintf("(readMsgLen) Failing with EOF, read %d of %d", read, encodeBinaryLen))
+                               }
                                return nil, errors.Wrap(err, "error reading log message length")
                        }
                        read += n
@@ -181,6 +185,9 @@ func decodeLogEntry(rdr io.Reader, proto *logdriver.LogEntry, buf []byte, msgLen
                n, err = io.ReadFull(rdr, buf[read:msgLen+encodeBinaryLen])
                if err != nil {
                        if err != io.ErrUnexpectedEOF {
+                               if err == io.EOF {
+                                       panic(fmt.Sprintf("(decodeLogEntry) Failing with EOF, read %d of %d", read, msgLen+encodeBinaryLen))
+                               }
                                return nil, errors.Wrap(err, "could not decode log entry")
                        }
                        read += n
```

It exactly illustrates the problem, when reading the msgLen:
 * `EOF` when reading the length of the message is fatal when we already read more than one byte from the stream. The reason is that this would advance the stream and the next call to `Decode()` would read a new length from a starting position incremented by one
and when reading the message itself:
 * `EOF` here is not valid even if read=0 because the length has already been read so if we exit here the next `Decode` will try to start reading a new msg length from somewhere inside the message.

**Comment by cpuguy83** [comment]
This is kind of a strange condition.

> If an EOF happens after reading some but not all the bytes, ReadFull returns ErrUnexpectedEOF

But we write the whole record in one shot.
So maybe the cursor is getting off somewhere else, or perhaps some weird fs behavior.

I think we should likely use ReadAt, track the cursor ourselves, and only advance after the cursor after a successful proto unmarshal.

**Comment by apollo13** [comment]
> I think we should likely use ReadAt, track the cursor ourselves, and only advance after the cursor after a successful proto unmarshal.

Yes, something like this is certainly the safest approach. Returning from `Decode` before the whole message is read just cries for issue (at least as soon as the reader state/seek position is advanced)

**Comment by kzys** [comment]
I've opened #43043. 

> But we write the whole record in one shot. So maybe the cursor is getting off somewhere else, or perhaps some weird fs behavior.

I'm not entirely sure an atomic write could guarantee a corresponding atomic read.
