### ISSUE TITLE
dind-rootless - "failed to register layer: Error processing tar file(exit status 1): lchown ... invalid argument

### ISSUE THREAD

**Issue by dimmel82** [moby/moby#42122]
**Description**

I get the error `failed to register layer: Error processing tar file(exit status 1): lchown /usr/src/git-2.21.0/configure: invalid argument` in a docker:20.10.5-dind-rootless container (crun is used as container runtime due to https://github.com/moby/moby/issues/40068) when executing the following command:
`docker pull gcr.io/jenkinsxio/builder-maven-java11:0.1.464`

Similar issue which is Closed is https://github.com/moby/moby/issues/41803, maybe the crun runtime is making the difference here.

Note that gcr.io/jenkinsxio/builder-maven-java11:0.1.464 is quite an old image but we have to use it nevertheless, I'm not sure if this is related with the issue somehow.

**Steps to reproduce the issue:**
1. Build custom dind-rootless image based on docker:20.10.5-dind-rootless with crun as default runtime to resolve https://github.com/moby/moby/issues/40068. Dockerfile:

> FROM docker:20.10.5-dind-rootless
> 
> USER root
> RUN mkdir -p /usr/local/bin
> COPY bin/crun-0.18-linux-amd64 /usr/local/bin/crun
> RUN chmod +x /usr/local/bin/crun
> 
> USER rootless
> CMD ["--default-runtime", "crun", "--add-runtime", "crun=/usr/local/bin/crun"]
> 

2. Run a privileged kubernetes pod with the custom dind-rootless image
3. Execute the command `docker pull gcr.io/jenkinsxio/builder-maven-java11:0.1.464`

**Describe the results you received:**
Docker pull failed with error: `failed to register layer: Error processing tar file(exit status 1): lchown /usr/src/git-2.21.0/configure: invalid argument`

**Describe the results you expected:**
Docker pull completes successfully

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:11 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:18:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 crun:
  Version:          0.18-dirty
  GitCommit:        808420efe3dc2b44d6db9f1a3fac8361dde42a95
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc crun
 Default Runtime: crun
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.15.0-96-generic
 Operating System: Alpine Linux v3.13 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 31.39GiB
 Name: docker-9b7969786-2hcrh
 ID: KDC7:537D:IFVA:JQMA:ITIJ:CFMT:QYFF:76DV:ZW6R:4TH7:NUTN:BCZ5
 Docker Root Dir: /home/rootless/.local/share/docker
 Debug Mode: false
 HTTP Proxy: http://10.100.50.17:8080
 No Proxy: *.cosmote.gr,*.ote.gr,localhost
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Kubernetes v1.14.8-docker-1 on Docker Enterprise (former name of Mirantis Kubernetes Engine)

**Comment by dimmel82** [comment]
Update: I also tested the pull command on a docker:20.10.5-dind-rootless container on a Centos machine (no crun, no Kubernetes), it gives same error:
`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/src/git-2.21.0/configure: invalid argument`

**Comment by dimmel82** [comment]
Container's log file from execution on kubernetes: [dind-rootless.log](https://github.com/moby/moby/files/6102657/dind-rootless.log)

**Comment by AkihiroSuda** [comment]
```console
$ docker run --rm gcr.io/jenkinsxio/builder-maven-java11:0.1.464  ls -l /usr/src/git-2.21.0/configure
-rwxr-x--- 1 110493 5000 251697 Feb 24  2019 /usr/src/git-2.21.0/configure
```

The file seems to be owned by UID 110493, which excess the number of the subuid (65536).

```console
$ docker run docker:20.10.5-dind-rootless cat /etc/subuid
dockremap:165536:65536
rootless:100000:65536
```

So, `COPY custom_subuid /etc/subuid` with the following `custom_subuid` would be needed:
```
dockremap:165536:65536
# Allocate 655360 subuids for "rootless"
rootless:100000:655360
```

The same is needed for `/etc/subgid` as well.

**Comment by AkihiroSuda** [comment]
( In future, rootless mode will work without /etc/subuid, but not soon: https://github.com/rootless-containers/subuidless )

**Comment by dimmel82** [comment]
Thanks @AkihiroSuda, I'll give it a try
