### ISSUE TITLE
Running docker swarm init as a systemd service will infrequently hang forever with no timeout or errors.

### ISSUE THREAD

**Issue by EricZaluzec** [moby/moby#42137]
**Description**
On a Linux system on boot-up, initializing docker swarm as a systemd service will infrequently hang forever with no timeout or errors. No system logs, journald logs, docker logs, or output is given which indicates the problem. The docker swarm systemd service is dependent on the docker systemd service to start first. After boot-up, attempting to initialize docker swarm will still result in the process to hang until the docker systemd service is restarted. 

The symptoms indicate that it could be some race condition where docker service is not completely ready when docker swarm is being initialized.

**Is there a docker cli command or a call that can be made from a system to indicate that the docker service is at a state where docker swarm can be successfully initialized?** 

Additionally, if there are ways to capture verbose logs from docker swarm, feel free to share. Looking at the docs, I could not find a way to capture any logs during initialization.

I'm using docker swarm to orchestrate container deployment on a single node. The OS is Azure/SONiC which is based off of Debian Linux. The system is running docker containers outside of the swarm along with docker service containers which are part of the swarm.

**Steps to reproduce the issue:**
1. `docker swarm init --advertise-addr 127.0.0.1`

**Describe the results you received:**
```
$ docker swarm init --advertise-addr 127.0.0.1

```

**Describe the results you expected:**
```
$ docker swarm init --advertise-addr 127.0.0.1

Initializing Docker Swarm
Swarm initialized: current node (sogwf6yu8zo0ohiboemlcfhw9) is now a manager.
To add a worker to this swarm, run the following command:
docker swarm join --token SWMTKN-1-2w2cti8ig4f1xoi70whlgcioqn4lz9uiijq1fwd7rys4lqnrjy-0o2bxbnyf7re6lzz8w2nfnlk6 127.0.0.1:2377
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

```

**Additional information you deem important (e.g. issue happens only occasionally):**
- Happens infrequently on boot-up of system. Sounds like race condition where docker swarm starts before docker is ready.
- No system logs or command line output information is given indicating the problem or errors that were encountered.

**Output of `docker version`:**

```
$ docker --version
Docker version 18.09.8, build 0dd43dd87f
admin@tor8:~$ docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:41:45 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
docker info
Containers: 16
 Running: 16
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-6-2-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.64GiB
Name: tor8
ID: MXCO:6QUH:EGFJ:5PJL:JQ5T:CYHP:NXPB:DSTF:YA7K:FW7R:SWTY:RJBW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
- Hardware: EdgeCore AS4630-54PE
- Arch: x86_64
- OS: Azure/SONiC Debian 4.19.67-2 Linux
```

**Comment by thaJeztah** [comment]
It's possible the daemon is running, but the API is not yet serving; you can check if you're able to connect to the `/_ping` endpoint on the API

```bash
$ curl --unix-socket /var/run/docker.sock http://localhost/_ping
OK
```

That said; Docker 18.09 reached EOL two years ago; I'd definitely recommend checking if this issue is resolved in current versions of Docker (e.g., Docker 20.10.x)
