### ISSUE TITLE
Dockerfile parser erroneously identifies comments inside line continuated strings

### ISSUE THREAD

**Issue by SiggyBar** [moby/moby#42135]
**Description**

The ``printf`` command can be useful in lieu of "heredoc" support (#34423).  In such "inline documents" one sometimes want lines that start with the hash character like illustrated by this example:

```Dockerfile
FROM debian:10.8-slim

# Useful GNU readline library settings.
RUN printf "\n\
# arrow up\n\
\"\\\\e[A\":history-search-backward\n\
# arrow down\n\
\"\\\\e[B\":history-search-forward\n" >> ~/.inputrc

CMD ["bash"]
```

But unfortunately the Dockerfile parser assumes all #-lines here are Dockerfile comments - and removes them.

**Steps to reproduce the issue:**
1. Copy the example above to a new Dockerfile in cwd
2. `docker build -t line-continuation-parser-bug .`
3. `docker run --rm -it line-continuation-parser-bug`
4. Inside the container run `cat ~/.inputrc`

**Describe the results you received:**
```Bash
root@ad892e7178a7:/# cat ~/.inputrc

"\e[A":history-search-backward
"\e[B":history-search-forward
```

**Describe the results you expected:**
```Bash
root@ad892e7178a7:/# cat ~/.inputrc

# arrow up
"\e[A":history-search-backward
# arrow down
"\e[B":history-search-forward
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Vaguely related: #20273

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.41GiB
 Name: docker-desktop
 ID: BIEI:KPSR:3KPM:FWGA:5LHG:DBWR:5UG6:VDMJ:J4GK:YSF5:QG7C:JP2U
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 44
  System Time: 2021-03-11T11:02:18.4295656Z
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by SiggyBar** [comment]
Using the `\xHH` syntax to specify a byte with hexadecimal value for the `printf` command, there is an easy workaround for this problem:

```Dockerfile
FROM debian:10.8-slim

# Useful GNU readline library settings.
RUN printf "\n\
\x23 arrow up\n\
\"\\\\e[A\":history-search-backward\n\
\x23 arrow down\n\
\"\\\\e[B\":history-search-forward\n" >> ~/.inputrc

CMD ["bash"]
```

**Comment by SiggyBar** [comment]
Something changed in the Dockerfile parser that broke the above workaround.  However, the `printf`'s octal notation can still be used:

```Dockerfile
FROM debian:10.8-slim

# Useful GNU readline library settings.
RUN printf "\n\
\43 arrow up\n\
\"\\\\e[A\":history-search-backward\n\
\43 arrow down\n\
\"\\\\e[B\":history-search-forward\n" >> ~/.inputrc

CMD ["bash"]
```

There seems to be great progress on an [heredoc implementation](https://github.com/moby/buildkit/pull/2132), so hopefully these hacks will soon belong to the past.

**Comment by thaJeztah** [comment]
> Something changed in the Dockerfile parser that broke the above workaround

Hmm... do you know when you observed that change? I'm not aware of anything in particular that was changed, but it feels like a corner-case, so it's definitely possible.

> But unfortunately the Dockerfile parser assumes all #-lines here are Dockerfile comments - and removes them.

This is expected; lines starting with `#` (including leading whitespace, for backward compatibility) are stripped before the Dockerfile is parsed. I know that there have been some attempts to change this, but unfortunately, doing so broke too many (valid) uses of this, that we weren't able to.

However, the heredoc syntax was merged in BuildKit, and is currently available for preview in the `docker/dockerfile-upstream:master-labs` syntax. If you have BuildKit enabled (`DOCKER_BUILDKIT=1`), you can try that frontend (docs can be found here: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#example-creating-inline-files)

Here's an example using `RUN` to write to the file:

```dockerfile
# syntax=docker/dockerfile-upstream:master-labs
FROM debian:10.8-slim

# using <<-, to allow indenting, and to strip leading <TAB> characters
# (note that leading <SPACE>s are not stripped)
RUN <<-"EOC"
	cat > ~/.inputrc <<"EOF"
		# arrow up
		"\e[A":history-search-backward
		# arrow down
		"\e[B":history-search-forward
	EOF
EOC
```

Build and run the image:


```bash
DOCKER_BUILDKIT=1 docker build -t foo .
docker run --rm foo sh -c 'cat ~/.inputrc'

# arrow up
"\e[A":history-search-backward
# arrow down
"\e[B":history-search-forward
```


Or (assuming `~/.inputrc` doesn't exist in the image, and it's ok to create "fresh".
Note that (currently) `~` is not evaluated, so using an absolute path (`/root` is the
home directory for the default (`root`) user in this image)

```dockerfile
# syntax=docker/dockerfile-upstream:master-labs
FROM debian:10.8-slim

# using <<-, to allow indenting, and to strip leading <TAB> characters
# (note that leading <SPACE>s are not stripped)
COPY <<-"EOC" /root/.inputrc
	# arrow up
	"\e[A":history-search-backward
	# arrow down
	"\e[B":history-search-forward
EOC
```

Build and run the image:

```bash
DOCKER_BUILDKIT=1 docker build -t foo .
docker run --rm foo sh -c 'cat ~/.inputrc'

# arrow up
"\e[A":history-search-backward
# arrow down
"\e[B":history-search-forward
```

**Comment by thaJeztah** [comment]
I'll close this ticket, because I don't think it'll be possible to keep the comment lines for the non-heredoc cased (as mentioned), but I hope the heredoc feature helps with your use-case; if you have feedback on that feature (before it's moved to the default dockerfile syntax), feel free to open a ticket in the buildkit repository (https://github.com/moby/buildkit).

Also, if you have more details about the change in behavior you mentioned; feel free to open a ticket for that with more details (which version of Docker did it work on, and which version did it stop working on)

**Comment by SiggyBar** [comment]
> Hmm... do you know when you observed that change?

Unfortunately I do not know the version number for when this change in behavior happened.  I noticed it on my machine running Docker Desktop, and normally I update right away when I see there is a new version.  So it worked on the 11th of March and not on the 3rd of June.  Assuming I have been using the latest versions on these dates, it should hopefully be possible to track down based on this (if anyone finds that worthwhile).

Thank you for the elaborate reply, the heredoc syntax looks awesome!

**Comment by thaJeztah** [comment]
> Unfortunately I do not know the version number for when this change in behavior happened

No worries, I'll just add it to my "list of mysterious changes" 🤗  Thanks!
