### ISSUE TITLE
[Question & Windows] Is it possible to configure docker not to create a new virtual ephemeral disk for each container on Windows?

### ISSUE THREAD

**Issue by ahrtr** [moby/moby#42169]
Each time when I run a docker container on a Windows 2019 VM, then a new ephemeral disk is automatically created for the container by the storage driver, and attached to the VM. When the container stops, then the disk is automatically detached from the Windows VM. Basically it's working well. You know, the behavior is different from the overlay2 on Linux. Is it possible to configure the docker engine or storage driver not to create a virtual disk for each container? Can it just use a directory on the host directly, just like overlay2?

The reason why I ask this is that the CSI Driver will also attach new disks to the VM on demand, and we can't easily programmatically tell which disks are attached by the CSI Driver, and which are created & attached by the docker & storage driver.

When we rolling update a K8S cluster, we need to drain each worker node one by one. When draining each worker node, we need to wait for all the POD/containers to be evicted, and all the related PV/disks to be unmounted & detached. You know, K8S DaemonSet can't be drained, so the virtual disks (created & attached by the docker windows's storage driver) related to the DaemonSet POD/containers will never be detached. So the drain process will be blocked.

We use exactly the same drain process on Linux and Windows, and we do not see any issue on Linux. But it doesn't work on Windows, and the root cause is that a new ephemeral disk is created & attached to a Windows VM by docker's storage driver for each container, just as I mentioned above. So is it possible to configure the docker engine or storage driver(windowsfilter?) on Windows to follow the same behavior as docker & storage driver (i.e. overlay2) on Linux? It's appreciated if anyone can share thoughts or comments.

Thanks.

**Comment by cpuguy83** [comment]
I do not think it is possible (though I'm absolutely not a Windows expert).

I don't think it makes sense to depend on the implementation details of a specific storage driver either unless you have end-to-end control of the stack and know it is not a problem.
ie. does your CSI driver work with btrfs? zfs? devicemapper?

**Comment by cpuguy83** [comment]
I'm going to go ahead and close this since theres nothing we can really do here, but feel free to discuss.

Maybe @olljanat has more ideas around the windows storage side.

**Comment by olljanat** [comment]
@ahrtr I'm not running Windows nodes with K8s but based on my experiences with Swarm nodes I would probably just deploy new nodes on parallel and do hard power off for old nodes. That simplify process and that is which you should be prepared foranyway to be sure that your cluster will survive from host failure.

**Comment by ahrtr** [comment]
@cpuguy83 & @olljanat  Thanks for the feedback. 

Actually there is an existing issue [75482](https://github.com/kubernetes/kubernetes/issues/75482) for the K8S.  I am just curious why a new virtual ephemeral disk is created & attached to the Windows host for each container.  Note that it's docker's behavior rather than K8S. But docker on Linux doesn't have such behavior. 

Based on the [container-storage](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage), all windows container I/O happens in a "scratch space" and each container gets its own scratch. File creation and file writes are captured in the scratch space and do not escape to the host. Probably it's the reason for the new ephemeral disk for each container on Windows?

**Comment by olljanat** [comment]
> Note that it's docker's behavior rather than K8S. But docker on Linux doesn't have such behavior.

Docker is just "client app" here and containerd runtime (which K8s will use instead of Docker on long term) is another.

Afaik the actual logic to use VHDs on this way is done by https://github.com/Microsoft/hcsshim + some of the logic might exist on Windows it selves too (as there is that feature called for "containers" which need to be enabled separately as prerequirement for Docker)
