### ISSUE TITLE
[Feature request][rootless] Support crun with the default installation

### ISSUE THREAD

**Issue by mo-saeed** [moby/moby#42160]
**Description**

Due to this https://github.com/moby/moby/issues/40068 rootless setup doesn't work with runc in our kubernetes cluster, so we have to install it manually and replace runc binary.

Could you please support crun installation in the default rootless installation, sth like runc is the default and can install crun if env variable exists.

**Output of `docker version`:**

```
docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:11 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:18:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          0.12.1
  GitCommit:        df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 58
 Server Version: 20.10.5
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.91-41.139.amzn2.x86_64
 Operating System: Ubuntu 20.04.2 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.35GiB
 Name: k8s-azure-devops-69cc75fdbf-mp2rz
 ID: 2RGA:ON55:KTAN:LU67:J2BJ:V5L6:Q33W:XPOD:AFOQ:KQCE:FLVV:7SOY
 Docker Root Dir: /azp/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on kubernetes EKS version 1.19.6

Let me know if you need more information or I need to open this request in a different repo.

Thanks a lot in advance

**Comment by AkihiroSuda** [comment]
If we can analyze and fix https://github.com/moby/moby/issues/40068 in runc, no need to use crun?

**Comment by mo-saeed** [comment]
Hi @AkihiroSuda 

I think regardless of this issue https://github.com/moby/moby/issues/40068, it would be good to support crun as I see it has better performance. similar to the concept of choice between vpnkit or slirp4netns during the installation. makes sense?

**Comment by cpuguy83** [comment]
I do not see why we need to support more combinations with an install script.
Build an image with crun in it and use that?

**Comment by mo-saeed** [comment]
by default, containerd config file is pointing to runc binary path and that can't be changed, so the workaround I am doing is to replace the runc binary with crun. and that's the behavior i want to avoid.

**Comment by cpuguy83** [comment]
`containerd` doesn't do anything here, its Docker setting the runtime to runc.
You can change the default runtime as a daemon option: https://docs.docker.com/engine/reference/commandline/dockerd/#docker-runtime-execution-options

**Comment by mo-saeed** [comment]
How to do that using the rootless setup ?

**Comment by cpuguy83** [comment]
For rootless, the daemon config is read from `$XDG_CONFIG_HOME/docker/daemon.json` or `$HOME/.config/docker/daemon.json` if `XDG_CONFIG_HOME` is not set.

**Comment by mo-saeed** [comment]
I have put it here besides this file ``` ~/.config/docker$ ls
key.json``` but didn't work.

**Comment by cpuguy83** [comment]
Did you do both `--add-runtime` and `--default-runtime`?
What does `docker info | grep runtime` say?

**Comment by cpuguy83** [comment]
Anyway, the options get set in the daemon.json, rootless *shouldn't* be any different here it is the same exact binary as rootful dockerd.

I can't remote troubleshoot your issue but we definitely have a means of configuring this.

**Comment by mo-saeed** [comment]
@cpuguy83 yes i remember well I added both options. right now I am just replacing the binary after i gave up making it work. I will try again to reproduce and send you the docker info command output. Thanks

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/issues/40068 is being fixed in https://github.com/moby/moby/pull/42189 , so let me close this issue.

> I think regardless of this issue #40068, it would be good to support crun as I see it has better performance. similar to the concept of choice between vpnkit or slirp4netns during the installation. makes sense?

I'm not sure crun's performance is significant enough to replace runc.
Anyway, crun is licensed under GPL3, and package maintainers aren't likely to be willing to mix up GPL binaries and Apache binaries together.
