### ISSUE TITLE
Docker Rootless I/O Error

### ISSUE THREAD

**Issue by onurbbr** [moby/moby#42206]
Hello there. I'm new to Docker. I am an Arch Linux user. After installing Docker's rootless, I follow the necessary steps. I get this error when I pull the archlinux and ubuntu image from Docker. I install busybox and hello-world images in Docker Rootless without any problem.

[onur@archlinux ~]$ docker pull archlinux
Using default tag: latest
latest: Pulling from library/archlinux
19c50925705c: Pull complete 
200e2a8b5fe3: Extracting [==================================================>]  6.645kB/6.645kB
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/var/cache/ldconfig") failed: createDirWithOverlayOpaque("/var/cache/rdwoo127155212") failed: failed to mkdir /var/cache/rdwoo127155212/m/d: mkdir /var/cache/rdwoo127155212/m/d: input/output error

[onur@archlinux ~]$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
04a5f4cda3ee: Pull complete 
ff496a88c8ed: Pull complete 
0ce83f459fe7: Extracting [==================================================>]     189B/189B
failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/run/systemd") failed: createDirWithOverlayOpaque("/run/rdwoo953609474") failed: failed to mkdir /run/rdwoo953609474/m/d: mkdir /run/rdwoo953609474/m/d: input/output error

[onur@archlinux ~]$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
8b3d7e226fab: Pull complete 
Digest: sha256:ce2360d5189a033012fbad1635e037be86f23b65cfd676b436d0931af390a2ac
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest

[onur@archlinux ~]$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
b8dfde127a29: Pull complete 
Digest: sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

I had installed docker in Ubuntu before and did not encounter any problems like this. I have such a problem. I installed and tried Docker Rootless 20.10.3 from the AUR repos, but this issue also exists in this version. I upgraded Docker Rootless to 20.10.5 but my problem still persists. How can I solve this?

I added to .zshrc:

export PATH=/usr/bin:$PATH
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

Filesystem Info:

[onur@archlinux ~]$ df -khT
Filesystem     Type      Size  Used Avail Use% Mounted on
dev            devtmpfs  7.8G     0  7.8G   0% /dev
run            tmpfs     7.8G  1.9M  7.8G   1% /run
/dev/nvme0n1p2 ext4      230G   64G  155G  30% /
tmpfs          tmpfs     7.8G  1.5M  7.8G   1% /dev/shm
tmpfs          tmpfs     4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs          tmpfs     7.8G   28M  7.8G   1% /tmp
/dev/nvme1n1p1 ext4      234G   61M  222G   1% /mnt/Projects
/dev/nvme0n1p1 vfat      511M  144K  511M   1% /boot/efi
/dev/sda1      ext4      916G   77M  870G   1% /mnt/Storage
tmpfs          tmpfs     1.6G  112K  1.6G   1% /run/user/1000

Docker Rootless Info:

[onur@archlinux ~]$ pacman -Qi docker-rootless-extras-bin
Name            : docker-rootless-extras-bin
Version         : 20.10.5-1
Description     : Extras to run docker as non-root.
Architecture    : x86_64
URL             : https://docs.docker.com/engine/security/rootless/
Licenses        : Apache
Groups          : None
Provides        : docker-rootless  docker-rootless-extras
Depends On      : docker
Optional Deps   : fuse-overlayfs: overlayfs support [installed]
                  slirp4netns: faster network stack [installed]
Required By     : None
Optional For    : None
Conflicts With  : docker-rootless  docker-rootless-extras
Replaces        : None
Installed Size  : 36.89 MiB
Packager        : Unknown Packager
Build Date      : Fri 26 Mar 2021 10:23:36 AM +03
Install Date    : Fri 26 Mar 2021 10:23:48 AM +03
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

Docker Version:

[onur@archlinux ~]$ docker version
Client:
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.16
 Git commit:        55c4c88966
 Built:             Wed Mar  3 16:51:54 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16
  Git commit:       363e9a88a1
  Built:            Wed Mar  3 16:51:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker info:

[onur@archlinux ~]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.11.9-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.47GiB
 Name: archlinux
 ID: C7P3:KBNS:5FMK:34AU:I2YH:YFJH:TN4X:OD7B:B77K:7IF7:5EEF:YWWH
 Docker Root Dir: /mnt/Storage/VMs/Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by AkihiroSuda** [comment]
This is being fixed in PR https://github.com/moby/moby/pull/42188

# Workaround until the PR  https://github.com/moby/moby/pull/42188 gets merged: use fuse-overlayfs:
```console
$ pacman -Syu fuse-overlayfs
$ mkdir -p ~/.config/docker
$ echo '{"storage-driver":"fuse-overlayfs"}' > ~/.config/docker/daemon.json
```
https://archlinux.pkgs.org/rolling/archlinux-community-x86_64/fuse-overlayfs-1.5.0-1-x86_64.pkg.tar.zst.html

**Comment by onurbbr** [comment]
Thank you. It's working.
