### ISSUE TITLE
Docker client requires access to current directory to perform commands via 'docker exec'

### ISSUE THREAD

**Issue by anatolybolshakov** [moby/moby#42208]
**Description**

Recently we updated docker-moby client version from v19.03.15 to 20.10.5 and faced with an issue that 'docker exec' always requires access to current working directory independently of command. For example if we run 'docker exec -u <some non-root user> <container> echo "message"' and current working directory in container is /root - it throws an error, but it looks like there was no such issue before.
Is this something expected?

**Steps to reproduce the issue:**
1. Create simple container with WORKDIR /root an the end (or use existing, for example  [hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.4.0_2.13.3](https://hub.docker.com/r/hseeberger/scala-sbt/tags?page=1&ordering=last_updated&name=graalvm-ce-20.0.0-java11_1.4.0_2.13.3))
2. Start this container (for example with 'sleep infinity' command) 
3. Create new user inside of this container via 'docker exec'
4. Run command with this user - 'docker exec -u <new_user> <container_id> echo "message"'

**Describe the results you received:**
Command throws an error:
OCI runtime exec failed: container_linux.go:367: starting container process caused: chdir to cwd ("/root") set in config.json failed: permission denied: unknown

**Describe the results you expected:**
Command is being executed successfully - comparing with terminal behavior (after switching to non-root user via 'su user' and /root as current directory - it is still able to perform commands like 'echo' - which don't require access to current directory.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 991MiB
 Name: osboxes
 ID: PLHJ:FDM2:IUHF:FWQ6:XKKZ:KUAZ:M5Z2:TU64:CRKY:FP4E:GBFO:G4CR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7, VirtualBox. Reproducible on other environments also - e.g. Ubuntu 20.04 (physical)

**Comment by cbdelavenne** [comment]
@anatolybolshakov I had the same exact problem with an update of Docker Desktop on Windows which upgraded the docker CLI from v19.03.13 to v20.x

**Comment by alexander-smolyakov** [comment]
@AkihiroSuda Could you please provide an update regarding this issue?

**Comment by thaJeztah** [comment]
This looks like (possibly) a fix in runc and docker where before it would perform actions with the default user before switching to the requested user.

Unlike a login session, switching to a different user with `-u` does not change the processes' home-directory, and the `docker exec` session will use the working-directory that's configured in the container (`/root`), which likely is not accessible to the user.

Does it work if you specify the working-directory for the `docker exec` ?

```
docker exec -u sbtuser:sbtuser -w /home/sbtuser <container> <command>
```

**Comment by anatolybolshakov** [comment]
@thaJeztah thanks for reply! Yes it works, and helps to resolve the issue.

**Comment by thaJeztah** [comment]
Great!

**Comment by cbdelavenne** [comment]
Thanks @thaJeztah 

I was also able to resolve this in my `Dockerfile` by changing my working directory (`WORKER <path>`) to a directory the non-root user has access rights to. 

I'm not using moby and this thread was helpful, haha 😄
