### ISSUE TITLE
(WSL2) docker build "output clipped, log limit 1MiB reached"

### ISSUE THREAD

**Issue by fcharron83** [moby/moby#42261]
**Description**

When performing lengthy `docker build` operations using `DOCKER_BUILDKIT=1` (not using `buildx`, as it is experimental), the command stops outputting logs with the "_output clipped, log limit 1MiB reached_" message, until the build is over.

(This was first opened on https://github.com/docker/for-win/issues/10839, but I've been instructed to open it here instead)

**Steps to reproduce the issue:**
1. `DOCKER_BUILDKIT=1 docker build ....` that produces more than 1MiB of logs on stdout/stderr

**Describe the results you received:**
- Last output line says "_output clipped, log limit 1MiB reached_"
- No more log output in the terminal until the build is finished.

**Describe the results you expected:**
- Continuous log output in the terminal
- Or, clear instructions on how to increase that limit using stable functionality

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.63GiB
 Name: docker-desktop
 ID: 3DGW:YZBD:OHOU:UUWW:J2JR:XV2Z:GCIF:3P43:6YAU:IJOX:7MAL:E2DI
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 49
  Goroutines: 52
  System Time: 2021-04-06T19:23:48.7791219Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Running on WSL2 (Hyper-V backend), on Windows 10 Enterprise, Version 20H2 (OS Build 19042.867)
- WSL2 VM OS: Ubuntu 18.04
- Can't use `docker buildx`, as it is an experimental feature, and I run in a production environment.

**Comment by thaJeztah** [comment]
@tonistiigi PTAL; I see this is configurable through environment variables; https://github.com/docker/buildx/issues/484#issuecomment-767434491 - is there a reason for buildkit not to stream the output (irregardless the size?)

**Comment by fcharron83** [comment]
TBH, I tried to set those variables, but the "WSL2/Ubuntu18.04 - docker" interface is a bit mysterious to me and it's not super clear where I should set them.

So far, I've tried editing the `docker.service` systemd config with:

```
[Service]
Environment="BUILDKIT_STEP_LOG_MAX_SIZE=1073741824"
```

And I could still reproduce the problem, but as I said, I'm not sure if that was the right place to set those vars. Or that they are even taken into account with the plain buildkit/`docker build` command...

**Comment by TYCOBKA** [comment]
The only workaround that I found is to limit the logs or set DOCKER_BUILDKIT=0
I too would be very interested in having this resolved, similar set up on Windows.

**Comment by LukeIreland1** [comment]
I'm having the same issue. Ideally, I want to use buildkit with normal docker build (so no docker-compose, buildx, etc.).

**Comment by jontro** [comment]
I am seeing this on docker for mac doing just "docker build ."

**Comment by bragarods** [comment]
I am able to reproduce the issue using docker build on Mac OS X. Tried to set "log-opts": {"max-size": "50m"} on daemon.json but still no lucky.

**Comment by LukeIreland1** [comment]
Just in case it helps anyone, literally the only way I could debug the image was by using buildx, then my normal build instructions. I couldn't replace the default build with buildx as it doesn't cache, but it appears to be the only way you can debug, so if anyone only cares about this issue for debugging failed docker builds, it's the only option you have (pretty much)

Something like
```
docker buildx create --use --name larger_log --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=50000000
docker buildx build <normal build instructions>
```
should work fine.

**Comment by pudiva** [comment]
+1 here having trouble with log limit

**Comment by TDiblik** [comment]
+1, just encouteted it today, after I was trying to cache dependencies. Funny thing is that without caching dependencies my build works fine, except that it takes forever to build.

**Comment by koffie** [comment]
One thing that would maybe help is if the part that was clipped from the log was not the last part. Usually the beginning and the end of the log are the most interesting parts. I guess most people running into this would already be very happy if they instead could see the last 1MiB or even just the last 0.5MiB of the log.

**Comment by PedroD** [comment]
+1

What a stupid design decision. I really agree that saving a few MBs of memory are worth hours of debugging failed builds without logs. <3

**Comment by wanglinqi123** [comment]
Add "--no-cache" works for me, but it took a really long time to build images

**Comment by TDiblik** [comment]
@wanglinqi123 this is a really good advice, if you can cache your dependencies correctlly.

**Comment by mwunderlich** [comment]
Just for the record: I ran into the same problem (Mac OS 11.6, Docker version 20.10.8) and the solution provided above by  @LukeIreland1 worked for me: 

> ```
> docker buildx create --use --name larger_log --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=50000000
> docker buildx build <normal build instructions>
> ```

**Comment by fazalmajid** [comment]
FWIW, this is where this misfeature comes from:

https://github.com/moby/buildkit/blob/f4fcba58837c49433afaa0e23b710d3e73a66e37/util/progress/logs/logs.go#L106

**Comment by krissetto** [comment]
I am having the same issue on Docker for mac. The only way to get a full log output was to set buildkit: false ni the daemon configuraton file. 
VERY annoying and time consuming issue, all i needed to see was to see the output

**Comment by lucid-at-dream** [comment]
On ubuntu 20.04 I could increase the limits by setting the appropriate environment variables.
To increase the limits to 20MiB overall limit and 1MiB speed limit, add the following to the following file:
`/etc/systemd/system/multi-user.target.wants/docker.service`

Then, under the `[Service]` tag, add the environment variables:
```
# Added this to increase the log limit of build kit!
Environment="BUILDKIT_STEP_LOG_MAX_SIZE=20971520"
Environment="BUILDKIT_STEP_LOG_MAX_SPEED=1048576"
```

Then restart the service
```
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
```

@krissetto

**Comment by qiangli** [comment]
If you are using docker compose: `docker buildx bake --builder larger_log --load`

**Comment by wolfheros** [comment]
> I am having the same issue on Docker for mac. The only way to get a full log output was to set buildkit: false in the daemon configuraton file.
> VERY annoying and time consuming issue, all i needed to see was to see the output

I'm on the tutorial of docker project , which specifically let the BuildKit to enable. what a design for this !

**Comment by fcharron83** [comment]
Since opening this ticket, I think buildx was promoted to a regular - non-experimental feature, which means it should be good to be used in production. As such, I suppose that unless they resolve this ticket some other way and provide a more user-friendly fix, the buildx solution detailed above is the best way to address the problem.

**Comment by JohnPremKumar** [comment]
Any one know how to fix it with for general "docker build" command? This issue happens even when not using buildx command

**Comment by namedgraph** [comment]
@thaJeztah how is this completed? The build logs are still clipping!

**Comment by thaJeztah** [comment]
I see https://github.com/moby/moby/pull/43239 had a "fixes" for this ticket. Note that the issue tracker tracks the master branch, not necessarily fixes that have shipped in a release yet.

**Comment by rjackson90** [comment]
For everyone else who is wondering how #43239 fixes this issue, it looks like the new version of buildkit includes https://github.com/moby/buildkit/pull/2577 , which adds a 256k ring buffer to hold the most recent output. This should help with debugging, and I look forward to this new version of Moby making its way into Docker Desktop for macOS.
