### ISSUE TITLE
Port sharing does not work on 20.10.6: "probably RootlessKit binary is too old (needs to be v0.14.0 or later)"

### ISSUE THREAD

**Issue by WhyNotHugo** [moby/moby#42290]
**Description**

```
$ docker run -p 8025:8025 mailhog/mailhog
docker: Error response from daemon: driver failed programming external connectivity on endpoint nervous_bose (1de16f5e5d6b9a46fa66b82a93365d4116aa27ccfaa951b964cfdf8530cb5530): Error starting userland proxy: failed to call info API, probably RootlessKit binary is too old (needs to be v0.14.0 or later): unexpected HTTP status Not Found, body="404 page not found\n".
ERRO[0000] error waiting for container: context canceled

$ docker --version
Docker version 20.10.6, build 370c28948e

$ rootlesskit --version
rootlesskit version 0.14.1

$ uname -srmo
Linux 5.11.13-arch2-1 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
1. Install docker 20.10.6, any any version of docker-rootless (tried 20.10.6 and a few previous ones).
1. Run the above command

**Describe the results you received:**

Can't run a container with a port exposed.

**Describe the results you expected:**

Service should start normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

I initially though this was an issue in docker-rootless, but downgrading to docker itself to 20.10.5 fixes the issue.

**Comment by AkihiroSuda** [comment]
> probably RootlessKit binary is too old (needs to be v0.14.0 or later)

Please provide rootlesskit --version, and how you installed it

**Comment by WhyNotHugo** [comment]
It's in the original post:

```
$ rootlesskit --version
rootlesskit version 0.14.1
```

I also tried a few different versions. Installed by installing [`docker-rootless`](https://docs.docker.com/engine/security/rootless/). I tried a few different versions of docker-rootless:

- 20.10.3
- 20.10.5
- 20.10.6

They all work with docker 20.10.5, but none of them work with docker 20.10.6.

**Comment by WhyNotHugo** [comment]
(`rootlesskit` is bundled with `docker-rootless`)

**Comment by AkihiroSuda** [comment]
Also please try `systemctl --user restart Docker` or just reboot

**Comment by WhyNotHugo** [comment]
I've made sure I stopped the service between tests.

- Upgrading again makes it fail again.
- Downgrading again makes it work again.

I tried rebooting _once_ after installing docker 20.10.6, and it also did not work.

**Comment by AkihiroSuda** [comment]
You might have multiple rootlesskit binaries with different version, e.g., /use/local/bin/rootlesskit and ~/bin/rootlesskit ?

**Comment by WhyNotHugo** [comment]
`~/.bin` is not in my path.

If that were the case, `rootlesskit --version` would have indicated that something didn't match.

**Comment by AkihiroSuda** [comment]
I can install Rootless Docker v20.10.6 from https://get.docker.com/rootless on Arch Linux without an error. I still think you have multiple version of RootlessKit accidentally.

Could you try:
```console
$ ps auxw | grep dockerd
suda        1318  0.0  0.0 1303752 9640 ?        Ssl  13:28   0:00 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/local/bin/dockerd-rootless.sh
suda        1377  0.0  0.0 1301748 8788 ?        Sl   13:28   0:00 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/local/bin/dockerd-rootless.sh
suda        1426  0.2  0.4 1277200 75608 ?       Sl   13:28   0:08 dockerd
suda       12418  0.0  0.0   9016   880 pts/1    S+   14:24   0:00 grep --color=auto dockerd
```

(1318:  PID of `rootlesskit`)
```console
$ /proc/1318/exe --version
rootlesskit version 0.14.1

$ readlink /proc/1318/exe 
/usr/local/bin/rootlesskit
```

(1426: PID of `dockerd`)
```console
$ xargs -0 -L1 -a /proc/1426/environ | grep ROOTLESSKIT
ROOTLESSKIT_PARENT_EUID=1001
ROOTLESSKIT_STATE_DIR=/tmp/rootlesskit401599851
ROOTLESSKIT_PARENT_EGID=1001

$ curl -s --unix-socket /tmp/rootlesskit401599851/api.sock http://dummy/v1/info | jq
{
  "apiVersion": "1.1.1",
  "version": "0.14.1",
  "stateDir": "/tmp/rootlesskit401599851",
  "childPID": 1377,
  "networkDriver": {
    "driver": "slirp4netns",
    "dns": [
      "10.0.2.3"
    ],
    "childIP": "10.0.2.100"
  },
  "portDriver": {
    "driver": "builtin",
    "protos": [
      "tcp",
      "tcp4",
      "tcp6",
      "udp",
      "udp4",
      "udp6"
    ]
  }
}
```

**Comment by cptpcrd** [comment]
FWIW, I'm not able to reproduce this on Arch.

```
$ uname -srmo
Linux 5.11.13-arch1-1 x86_64 GNU/Linux
$ which -a rootlesskit  # On Arch, /bin is a symlink to /usr/bin
/usr/bin/rootlesskit
/bin/rootlesskit
$ rootlesskit --version
rootlesskit version 0.14.1
$ docker --version
Docker version 20.10.6, build 370c28948e
$ dockerd --version
Docker version 20.10.6, build 8728dd246c
$ docker run -p 1234:1234 -it alpine:latest sh -c 'echo Started'
Started
```

**Comment by WhyNotHugo** [comment]
Works now with changes from https://aur.archlinux.org/packages/docker-rootless-extras-bin/

Not sure what was up before.
