### ISSUE TITLE
Feature Request: Rootless Docker able to upgrade OR Instructions for how to upgrade rootless Docker version

### ISSUE THREAD

**Issue by MarkErik** [moby/moby#42301]
**Description**

I am currently running rootless Docker 20.10.5 and I would like to update to the latest released version (20.10.6).

I couldn't find any instructions on how to upgrade, so I tried to run the install script, however it fails and presents the following message:
```
mark@vultr:~$ curl -fsSL https://get.docker.com/rootless | sh
# Installing stable version 20.10.6
# Existing rootless Docker detected at /home/mark/bin/dockerd
# See https://docs.docker.com/go/rootless/ for the usage.
```

I went to the link however I couldn't find anything about updating the software. 

Thank you for any help and apologies if I missed the instructions for how to upgrade the rootless Docker version.

I also posted about this in the GitHub install script section - I wasn't sure where the correct location is to log it.

**Steps to reproduce the issue:**
1. Ubuntu 20.04.2 with rootless Docker 20.10.5 installed
2. Try to upgrade to the latest version using the method described at: https://docs.docker.com/engine/security/rootless/
3. `curl -fsSL https://get.docker.com/rootless | sh`

**Describe the results you received:**

When trying to upgrade, I receive an error that an existing rootless Docker detected.

The link that was provided in the error message (https://docs.docker.com/go/rootless/) doesn't seem to include instructions for how to upgrade the version of rootless Docker.

**Describe the results you expected:**

Instructions for how to upgrade the rootless Docker version.
OR
Even better, have the installation script be able to upgrade the rootless Docker version without the user having to perform additional steps.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:11 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:18:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-70-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 981.2MiB
 Name: vultr.guest
 ID: 2PCI:I3VR:426L:DONE:5PPL:DBSC:DQHY:JS4J:SZ26:2TKH:IZLK:LWUE
 Docker Root Dir: /home/mark/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by Gymnae** [comment]
I started with the .sh script as well, but switched to the packaged version. I would recommend you to with as well, no headache with keeping things up to date:
https://docs.docker.com/engine/install/ubuntu/

**Comment by MarkErik** [comment]
@Gymnae Thank you for responding, I am not sure if I am able to use the methods that require a package manager since on the server that I am working on I don't have sudo access.

**Comment by Gymnae** [comment]
In this case you can follow the instructions for uninstalling rootless docker: https://docs.docker.com/engine/security/rootless/#uninstall

If you mounted host directories, no non-ephemeral data should be lost this way.

If you used docker volumes, you should copy out what you need to your user folder, maybe by mounting host folders into containers linking to running containers using volumes or any other method to get data out of running docket containers.

You can manually go through `~/.local/share/docker` to take what you need.  `docker inspect <containername>` can give you the id of volumes docker created and you can find them in the structure of `~/.local/share/docker`. Salvage all you need, then wipe rootless docker off your user folder via given instructions and reinstall. No non-ephemeral data should be lost this way.

**Comment by MarkErik** [comment]
@Gymnae Thank you for outlining the process in detail - it is appreciated (thanks for the reminder about saving out data from docker volumes).

To be honest, I was hoping that I missed something and that there would have been an easier way to upgrade, rather than delete everything and reinstall. It seems error-prone if I am to do that each time there is a new version, as I also need to install the non-default slirp4nets network driver, and modify the configs to use that.

If that is the way, it would be great if the Docker team could add a Section Header for "Upgrade" in the Rootless Docker webpage between Install and Uninstall that outlined the steps.

**Comment by AkihiroSuda** [comment]
Upgrade step:

```console
$ systemctl --user stop docker
$ rm -f ~/bin/dockerd
$ curl -fsSL https://get.docker.com/rootless | sh
```

**Comment by MarkErik** [comment]
@AkihiroSuda Thank you for sharing the instructions to upgrade it is appreciated! I was able to get the latest version installed.

However, upon upgrading to 20.10.6 my Traefik container would no longer start (using slirp4netns). I opened an issue with more details at the slirp4netns project: https://github.com/rootless-containers/slirp4netns/issues/262

**Comment by Sieboldianus** [comment]
There is a "Already installed verification" in https://get.docker.com/rootless that suggest that unattended updates should already work now if once installs the `docker-ce-rootless-extras` package:

```
echo "# Alternatively, install the docker-ce-rootless-extras RPM/deb package for ease of package management (requires root)."
echo "# See https://docs.docker.com/go/rootless/ for details."
```

It is a bit unclear though. Can someone verify? I could not find any information about this package.

**Comment by AkihiroSuda** [comment]
>  I could not find any information about this package.

The packages are available on download.docker.com:
- https://download.docker.com/linux/ubuntu/dists/mantic/pool/stable/amd64/docker-ce-rootless-extras_24.0.7-1~ubuntu.23.10~mantic_amd64.deb
- https://download.docker.com/linux/centos/9/x86_64/stable/Packages/docker-ce-rootless-extras-24.0.7-1.el9.x86_64.rpm

See https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository for setting up apt-get

**Comment by Sieboldianus** [comment]
Thank you for the links, but it is not what I meant. The question is:

With `docker-ce-rootless-extras` installed, do I still need to regularly execute `dockerd-rootless-setuptool.sh` to get the newest docker rootless version?

**Comment by AkihiroSuda** [comment]
The script is for setting up systemd, not for getting the "newest" version.
