### ISSUE TITLE
for http requests docker resolves Host header instead of using the provided ip

### ISSUE THREAD

**Issue by satanTime** [moby/moby#42306]
**Description**

I use `--add-host` to build my containers in order to forward requests to my local proxy.
But, on the latest docker it doesn't work anymore.

After investigation, I found that if a http request contains a `Host` header,
then docker resolves it and sends the request directly to the destination resolved ip.

In my case, I use `deb.debian.org.lo` and `--add-host deb.debian.org.lo:172.16.0.1`.
Because docker cannot resolve `deb.debian.org.lo`, all requests with `Host: deb.debian.org.lo` return `500`.

If I use `Host: test.com`, then the request goes to `test.com`, instead of my local ip.

**Steps to reproduce the issue:**

```sh
docker run curlimages/curl -Isv http://1.2.3.4 -H'Host: test.com'
```

The result is

```log
*   Trying 1.2.3.4:80...
* Connected to 1.2.3.4 (1.2.3.4) port 80 (#0)
> HEAD / HTTP/1.1
> Host: test.com
> User-Agent: curl/7.76.1-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Connection: keep-alive
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 18 Apr 2021 15:51:00 GMT
< Keep-Alive: timeout=20
< Location: http://www.test.com/
< Server: nginx/1.18.0
< X-Dis-Request-Id: 08dd739f70e2daa9c935426506954236
<
* Connection #0 to host 1.2.3.4 left intact
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Sun, 18 Apr 2021 15:51:00 GMT
Keep-Alive: timeout=20
Location: http://www.test.com/
Server: nginx/1.18.0
X-Dis-Request-Id: 08dd739f70e2daa9c935426506954236
```

**Describe the results you received:**

Although it says `* Connected to 1.2.3.4 (1.2.3.4) port 80 (#0)`, there was not a connection with `1.2.3.4` on port `80`.

**Describe the results you expected:**

I expected the request to go via `1.2.3.4` `80` with header `Host: test.com`

**Additional information you deem important (e.g. issue happens only occasionally):**

everything worked correctly one or two updates ago (around 1 month).

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 18
  Running: 3
  Paused: 0
  Stopped: 15
 Images: 34
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: ZRTA:UTOK:VR42:ICDN:ZRQG:RTJE:FVIW:7SUM:IUB3:HRN4:JDIS:NDFY
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 68
  Goroutines: 73
  System Time: 2021-04-18T15:54:05.6982891Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
nope, right on my MacOS host.

**Comment by thaJeztah** [comment]
The `--add-host` on `docker build` is only used during build (so for the containers that are created to execute `RUN` steps during build); that configuration is not persisted in the image, so if you need to use it when running the container, you need to set the `--add-host` on `docker run` as well.


> After investigation, I found that if a http request contains a Host header, then docker resolves it and sends the request directly to the destination resolved ip.

I don't think docker would be in the middle of that example; looking at the response;

```
HTTP/1.1 301 Moved Permanently
```

It looks like something is listening on 1.2.3.4, and sending a redirect header

**Comment by satanTime** [comment]
Hi, that was the original response from test.com, 1.2.3.4 wasn't reached at all. Instead of 1.2.3.4 any ip address can be specified. 

The issue is that it is ignored. If I remove the 'Host' header, then request goes go the right up address and fails.

**Comment by thaJeztah** [comment]
Does it work if you run the container with `--add-host` ? Note that `--add-host` adds an entry in `/etc/hosts` inside the container, so you should be able to verify if it's set correctly

**Comment by satanTime** [comment]
Nope. It used to work before I updated docker. 
If I add this param - I see in the container the updated /etc/hosts, but requests return 500 error for .lo domains.

**Comment by satanTime** [comment]
Let me try on another mac. Maybe my bad.

**Comment by satanTime** [comment]
Yep. On Mac with Apple CPU the same thing - 500 error on 'http://1.2.3.4' and 301 if I add '-H Host: test.com'

**Comment by satanTime** [comment]
Did the same test on a Linux machine with the same docker version - works correctly - failed with cannot connect to 1.2.3.4 on port 80.
Looks like it belongs to Mac only.

**Comment by thaJeztah** [comment]
Hmmm.. interesting; may be something related to DNS resolution within the Docker Desktop VM

@djs55 any ideas? anything here looking familiar to you?

**Comment by djs55** [comment]
I think there are 2 bugs in this area in Docker Desktop 3.3.0 and 3.3.1:

1. even when there is no upstream HTTP proxy configured, a transparent HTTP/HTTPS proxy is enabled anyway. I have a developer build which only enables the transparent proxy when an upstream HTTP proxy is configured: https://desktop-stage.docker.com/mac/stable/amd64/63310/Docker.dmg (also mentioned https://github.com/docker/for-mac/issues/5572 ). Assuming you have no upstream proxy, the traffic should go straight through without modification using this build. (Let me know if it still doesn't work!)
2. the transparent HTTP proxy inspects the `Host:` header (and any TLS SNI headers available) to match against `no_proxy` rules. It then forwards based on the `Host:` header rather than `SO_ORIGINAL_DST`. It should probably forward based on the original IP.

**Comment by satanTime** [comment]
Thanks @djs55, these 2 issues are exactly the problem I'm facing. I've subscribed to them.

This one can be closed. I didn't know about `for-mac` repo.

**Comment by thaJeztah** [comment]
> I didn't know about `for-mac` repo.

Yes, it can sometimes be a bit confusing where the best place is to report (and sometimes needs some triaging to see if an issue is specific to docker desktop for Mac / windows, or an issue in the linux binaries).

Glad we found that these issues were already tracker (thanks @djs55 !)

Let me close this one in favour of the `for-mac` ones 👍
