### ISSUE TITLE
Missing support for linux/ppc - please update vendored packages 

### ISSUE THREAD

**Issue by bwh-mind** [moby/moby#42344]
**Description**

moby currently cannot be built for linux/ppc (which is supported by gccgo).

In order to support it, these vendored packages should be updated:

* `golang.org/x/net` (recently added linux/ppc support)
* `golang.org/x/sys` (recently added linux/ppc support)

I would make a pull request, but I don't understand quite how you handle updates of vendored packages.

After updating these, there are still some build errors, but I believe these are bugs in gccgo which I will take up with them.

**Steps to reproduce the issue:**
1. Try to build moby using gccgo for linux/ppc:

```
$ GO111MODULE=off GOARCH=ppc GOROOT="" CC="powerpc-linux-gnu-gcc" CXX="powerpc-linux-gnu-g++" GCCGO="powerpc-linux-gnu-gccgo" GOBIN= CGO_ENABLED=1 GOPATH="$BUILD_DIR/gopath" go build  -v -compiler gccgo -gccgoflags='-s' -tags "autogen" -p 9 -o "$BUILD_DIR"/bin/dockerd ./cmd/dockerd
```

**Describe the results you received:**
Build quickly fails:
```
# github.com/docker/docker/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/affinity_linux.go:14:35: error: reference to undefined name ‘_NCPUBITS’
   14 | const cpuSetSize = _CPU_SETSIZE / _NCPUBITS
      |                                   ^
vendor/golang.org/x/sys/unix/affinity_linux.go:14:33: error: division by zero
   14 | const cpuSetSize = _CPU_SETSIZE / _NCPUBITS
      |                                 ^
...
```

**Describe the results you expected:**
Should build succesfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Not applicable as it didn't build. I used current master (commit `68bec0fcf7a5eeb59c027287d06598098edc9f2c`).

**Output of `docker info`:**
Not applicable as it didn't build.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This is for 32-bit PPC, correct? We definitely haven't tried that so far (we do have ppc64le running in CI).

If you're interested in contributing; to update these versions, you can update the versions referenced in `vendor.conf` at the root of the repository; https://github.com/moby/moby/blob/42a485f7fab03895fa6d50b04726f026aa6ce649/vendor.conf#L22-L23

update the commits that are currently referenced to a more current version, run the `hack/vendor.sh` script, which re-vendors the code to match the new commit, and then commit the results. Its _quite likely_ though that there's many parts in the code that do not take ppc into account, so probably best to first try locally if it works at all.

**Comment by bwh-mind** [comment]
> This is for 32-bit PPC, correct?

Yes.

> update the commits that are currently referenced to a more current version, run the hack/vendor.sh script, which re-vendors the code to match the new commit, and then commit the results.

I've tried that, but it deleted a load of unrelated vendored source files!

> Its quite likely though that there's many parts in the code that do not take ppc into account, so probably best to first try locally if it works at all.

We have an older version of Docker running successfully, and it didn't require ppc-specific changes other than in the few packages I've requested to update. But I haven't yet had the chance to test the current version beyond building it.

**Comment by thaJeztah** [comment]
> I've tried that, but it deleted a load of unrelated vendored source files!

I wonder if `vndr` needs an update in the list of OSes and architectures it considers;

https://github.com/LK4D4/vndr/blob/f12b881cb8f081a5058408a58f429b9014833fc6/build/syslist.go#L7-L8

```go
const goosList = "android darwin dragonfly freebsd linux nacl netbsd openbsd plan9 solaris windows "
const goarchList = "386 amd64 amd64p32 arm armbe arm64 arm64be ppc64 ppc64le mips mipsle mips64 mips64le mips64p32 mips64p32le ppc riscv64 s390 s390x sparc sparc64 "
```

**Comment by thaJeztah** [comment]
The above looks to have been taken from https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/go/build/syslist.go#L10

Perhaps you're interested in opening a pull request in the vndr repository to update that list with the latest version from Golang

**Comment by bwh-mind** [comment]
> > I've tried that, but it deleted a load of unrelated vendored source files!
> 
> I wonder if `vndr` needs an update in the list of OSes and architectures it considers;

`ppc` is already in that list (it's not alphabetical).

**Comment by thaJeztah** [comment]
> ppc is already in that list (it's not alphabetical).

🤦 you're right I overlooked it.

Let me try to have it updated; there's also some other dependencies to update that may require more recent versions of this dependency, so possibly it will roll up in one of those.

**Comment by bwh-mind** [comment]
Commit f0d3e905b6e93e8ecb76624d87d2c18dad818271 updated golang.org/x/sys, but golang.org/x/net still needs a further update.

**Comment by thaJeztah** [comment]
I think this was all done by now
