### ISSUE TITLE
ImagesPrune outputs requires API version 1.25, but the Docker daemon API version is v1.38

### ISSUE THREAD

**Issue by lifeblood** [moby/moby#42353]
github.com/docker/docker v20.10.3+incompatible

when I  use `ImagesPrune` function that always outputs error with  
"requires API version 1.25, but the Docker daemon API version is v1.38"

docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by thaJeztah** [comment]
Do you have the `DOCKER_API_VERSION` environment variable set, or are you using `v1.38` (including the `v` prefix) as API version?

**Comment by lifeblood** [comment]
> Do you have the `DOCKER_API_VERSION` environment variable set, or are you using `v1.38` (including the `v` prefix) as API version?

1. version = "v1.38" was set config file

where set DOCKER_API_VERSION environment , target host ?

**Comment by lifeblood** [comment]
When "v1.38" modify "1.38" then can run the ImagesPrune function successfully!

**Comment by thaJeztah** [comment]
Yes, it needs to be specified without the `v`.


Generally, I'd recommend initialising the client with the `WithAPIVersionNegotiation` option; doing so would make the client automatically negotiate what API version to use (depending on what daemon it connects with);


This example would use the `client.FromEnv` option (allowing you to use the environment-variables for overrides), and the  `client.WithAPIVersionNegotiation` to perform automatic version negotiation;

```
cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
```

Also see https://docs.docker.com/engine/api/sdk/examples/

and the docker cli source code may be useful to get some examples; e.g. https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/cli.go

**Comment by thaJeztah** [comment]
Looks like the question is answered, so I'll close this ticket, but feel free to continue the conversation

**Comment by lifeblood** [comment]
Thank you so much!
