### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "-p"

### ISSUE THREAD

**Issue by RenJunFeng** [moby/moby#42363]
![image](https://user-images.githubusercontent.com/12624913/117414556-d7078600-af49-11eb-9175-862b11123baa.png)

There is a Dockerfile I have built ：  docker bulid . -t xxx:xxx
Then I try create contains :  docker run -d xxx:xxx -p 9001:80
but docker does not work 
**Error message**    
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "-p": executable file not found in $PATH: unknown.

See the picture above for details~

help me，thankyou

**Comment by AkihiroSuda** [comment]
> docker run -d xxx:xxx -p 9001:80

The correct form is `docker run -d  -p 9001:80 xxx:xxx`
