### ISSUE TITLE
RemoveContainer failed because of Access is denied error.

### ISSUE THREAD

**Issue by lizhuqi** [moby/moby#42366]
**Description**

In GKE, when an API call is issued to terminate the pod, RemoveContainer started but failed because of the following error:
RemoveContainer "[ID]" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "[ID]": Error response from daemon: unable to remove filesystem for [ID]: CreateFile C:\ProgramData\docker\containers\[ID]\[ID]-json.log.2: Access is denied.

**Steps to reproduce the issue:**
This is not consistently happen and happens for Windows containers. It seems that there might be some racing condition caused the failure

**Describe the results you received:**
Container fails to remove and pod is stuck in termination.

**Describe the results you expected:**
Container is removed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
docker://19.3.14
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Service: GKE
Kernel version: 10.0.17763.1757
OS image: Windows Server 2019 Datacenter
Container runtime version: docker://19.3.14
kubelet version: v1.17.17

**Comment by thaJeztah** [comment]
Could possibly be related to how kubernetes collects containers logs (which I think involves directly attaching the internal files used by the JSONfile logging driver, which may not play well docker itself if it is configured to rotate those files). 

You could _try_ if the problem goes away if you disable rotation on the json-file logs, but this would mean that logs would be able to grow without boundaries.

In general,  would recommend opening a support ticket with GKE to do the initial triage

**Comment by lizhuqi** [comment]
Thanks Sebastiaan for your inputs! We found out the root cause is fluentd and very recent fluentd release v1.13.3 has the fix for this issue so close this issue now.
