### ISSUE TITLE
Show if a local image has a newer version on index when using docker images command

### ISSUE THREAD

**Issue by kencochrane** [moby/moby#4239]
When you do the docker images command, it would be nice if there was a way to show which images are out of date locally.

Secondly, it would be nice if there was a command like `docker update`,  which would look at your local images and see which ones are out of date compared to the index, and pull down the new ones for automatically. This would basically just be a convenience  method for doing a docker pull on all out of date images. 

If we need a new API endpoint on the docker index for this, just let me know.

**Comment by rmetzler** [comment]
+1 would be nice to have.

**Comment by cpuguy83** [comment]
Or how about `docker outdated`?

**Comment by thaJeztah** [comment]
Or, `docker images --filter=outdated=true`, which could be combined with other commands;

    docker rmi $(docker images -q -f outdated=true)
    docker pull $(docker images -q -f outdated=true)

**Comment by vjurenka** [comment]
#dibs

**Comment by thaJeztah** [comment]
@vjurenka I think it's great that you want to give this a go. Be prepared, however that (given the discussion above), there's no real agreement *if* (and in what "form") this should be implemented.

There may be a chance that your PR will be rejected, or that the implementation has to be changed; If you don't have a problem with that, Go for it! :+1:

(if you want to have some feedback, it may be good to discuss it in the #docker-dev IRC channel with one of the core maintainers)

**Comment by LK4D4** [comment]
still looks valid

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉
