### ISSUE TITLE
Deprecate `created` metadata field that is covered by digest. Create uncovered `created`

### ISSUE THREAD

**Issue by gabrieljones** [moby/moby#42417]
An image tag is not covered by digest. Is there any other image metadata that is also outside the digest? Like image labels or something? Is there a place where the `created` timestamp can live that is outside the digest? The rise of deterministic reproducible image build tools is rendering the digest covered `created` field useless at best, misleading noise at worst.

There are probably additional metadata fields that could benefit from being moved out from under digest coverage.

**Comment by gabrieljones** [comment]
https://stackoverflow.com/questions/59618712/docker-image-timestamp-issue
https://github.com/bazelbuild/rules_docker/issues/52
https://github.com/GoogleContainerTools/distroless/issues/242
https://github.com/GoogleContainerTools/jib/issues/606
https://github.com/GoogleContainerTools/jib/issues/2252
https://github.com/GoogleContainerTools/jib/issues/3030

Related:
https://github.com/moby/buildkit/issues/1058
https://github.com/docker/cli/pull/2107

**Comment by gabrieljones** [comment]
One kludgy way to add a hash uncovered created timestamp in the existing model is to add an extra tag on all images that is the created timestamp. Though if several different images with a given name were created at the exact same time...
You could get extra kludgy and try to avoid a created tag collision by checking if a given created tag exists, and incrementing the millis until...
Another way to avoid created tag collisions is to always prepend or append the image hash to the created tag...
I think I like this better. I'm going to go with append.

**Comment by gabrieljones** [comment]
Here is what I have so far

`build.gradle.kts`
```build.gradle.kts
import java.time.*
//...
jib {
  to {
    image = "${dockerRepository}/${project.name}:${project.version}"
    tags = setOf("latest", "created_" + ZonedDateTime.now(ZoneOffset.UTC).toString().replace(':', '-'))
  }
}
```

Not sure if it is possible to know the image digest at this point. A collision on ZonedDateTime at this point is extremely unlikely.

**Comment by thaJeztah** [comment]
I don't think we can _exclude_ the created field (if present), as the OCI spec describe that the digest needs to be calculated over the configuration; https://github.com/opencontainers/image-spec/blob/859973e32ccae7b7fc76b40b762c9fff6e912f9e/descriptor.md#digest-calculations. The `Created` field itself is marked as "optional" (https://github.com/opencontainers/image-spec/blob/master/config.md#properties), so an _empty_ field is allowed, but if it is to be replaced by annotations, I think those would be included in the digest calculation as well, so would bring the same issue.

Adding support for `SOURCE_DATE_EPOCH` (e.g.) could probably help (I see things along those lines are discussed in https://github.com/moby/buildkit/issues/1058); that said, there's many places where timestamps may prop up (which could be on the filesystem during build), so there may be many paths that need to be resolved. Note that, while the digest for the _configuration_ may depend on the "created" field; the image _layer_ digests may already be more stable (I know various metadata is reset when building images (especially when using BuildKit), which of course doesn't solve the whole issue with the image digest (as a whole).

For `docker build`, I think the ticket in Buildkit (https://github.com/moby/buildkit/issues/1058) would be the best location to start/discuss.

If the request is to _include_ metadata about "creation date", but _exclude_ them from the digest calculation, then the best location to propose changes is the OCI Image spec; http://github.com/opencontainers/image-spec

Based on the above, I don't think there's (currently) anything "actionable" in this ticket (until the above issues are resolved), so I'll go ahead and close this ticket for now, but feel free to continue the conversation.
