### ISSUE TITLE
l2bridge docker network: unable to map ports to container on Windows 21H1. The specified port already exists (0x803b0013)

### ISSUE THREAD

**Issue by paulh-adion** [moby/moby#42426]
**Description**

Unable to map any port to my windows docker container with the l2bridge network. 

**Steps to reproduce the issue:**

`docker network create -d l2bridge --subnet x.x.0.0/24 --gateway x.x.0.1 l2bridge`
`docker run --rm -itd --network l2bridge --ip x.x.0.190 -p 80:80 testimage`

**Describe the results you received:**

`docker: Error response from daemon: failed to create endpoint thirsty_mestorf on network l2bridge: failed during hnsCallRawResponse: hnsCall failed in Win32: The specified port already exists. (0x803b0013).`

**Describe the results you expected:**

Container launches successfully with port mapped.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time regardless of the port number.
The `docker run` command completes successfully if I omit the -p parameter
Only started happening after upgrading to Windows 21H1. Rolling back to Windows 1909 and the problem disappeared
I tried uninstalling and reinstalling Docker Desktop and Hyper-V

**Output of `docker version`:**

`Docker version 20.10.6, build 370c289`

**Output of `docker info`:**

Unfortunately I don't have it because I already reverted back to old version of Windows

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker Desktop for Windows version 3.3.3
Physical box with 2 network adapters, one for to "External Switch" for Hyper-V containers, the other for docker l2bridge network

**Comment by ritterzk** [comment]
Hello @paulh-adion, we are experiencing the same error with Windows Server 2022 Core. Were you able to find a solution?
