### ISSUE TITLE
What's the best way to process CorruptDockerOverlay2 problem

### ISSUE THREAD

**Issue by zvier** [moby/moby#42456]
**Description**
When execute `docker inspect` to a image,  it returns error message with `readlink /var/lib/docker/overlay2/l: invalid argument`. The reason is overlay2 corrupt as same as [https://github.com/moby/moby/issues/35747#issuecomment-501774879](https://github.com/moby/moby/issues/35747#issuecomment-501774879) describe.  And the [node-problem-detector](https://github.com/kubernetes/node-problem-detector/blob/master/config/docker-monitor.json) also support to monitor this problem.  

To fix this problem, can remove the image and retry to pull the image or `docker system prune`, but may not effect. Remove the whole overlay2 directory can fix it, but is expensive. Is there any other best practice to solve this problem or through improve `Dockerfile` for image make to avoid this problem ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
