### ISSUE TITLE
Docker context list --format throws exception when used with ContextType

### ISSUE THREAD

**Issue by pratiksanglikar** [moby/moby#42467]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**Description**
Using the attribute `ContextType` or `Type` in the command `docker context list --format "{{ .ContextType}}" throws an exception.

**Steps to reproduce the issue:**
1. execute the following command - `docker context list --format "{{json .ContextType}}"`

**Describe the results you received:**
`Template parsing error: template: :1:7: executing "" at <.ContextType>: can't evaluate field ContextType in type *formatter.clientContextContext`

**Describe the results you expected:**
I have three contexts created, so the output should have been -
```
moby
aci
ecs
```

**Additional information you deem important (e.g. issue happens only occasionally):**
If I execute `docker context list --format "{{json . }}"`, I get the correct JSON output as - 
```json
       {
		"Current": true,
		"Description": "Current DOCKER_HOST based configuration",
		"DockerEndpoint": "npipe:////./pipe/docker_engine",
		"KubernetesEndpoint": "https://b2kstresst-b2kstresstest-b1fdfb-82f667ef.hcp.eastus.azmk8s.io:443 (default)",
		"ContextType": "moby",
		"Name": "default",
		"StackOrchestrator": "swarm"
	}
	{
		"Current": false,
		"Description": "azds-aks@eastus",
		"DockerEndpoint": "",
		"KubernetesEndpoint": "",
		"ContextType": "aci",
		"Name": "myacicontext",
		"StackOrchestrator": ""
	}
	{
		"Current": false,
		"Description": "credentials read from environment",
		"DockerEndpoint": "",
		"KubernetesEndpoint": "",
		"ContextType": "ecs",
		"Name": "myecscontext",
		"StackOrchestrator": ""
	}
```

If I execute `docker context list --format "{{json .Current}}"`, I get the correct output as - 
```
true
false
false
```
But executing the command `docker context list --format "{{json .ContextType}}"` errors out with an error - 
```
`Template parsing error: template: :1:7: executing "" at <.ContextType>: can't evaluate field ContextType in type *formatter.clientContextContext`
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.95GiB
 Name: docker-desktop
 ID: DM5G:AI7Z:FUPX:2G3P:QMT2:7IZY:ZUWW:FB5T:QQKN:EKW7:XTQY:2WVR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tried on physical machines on both Mac and a Windows 10 machine.
Both produced the same results.

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like this is because the ContextType field is an addition made in the the "compose-cli";

 - https://github.com/docker/compose-cli/blob/c11a458666ac7e2de05719c5a0f461d0269f7d5d/cli/server/proxy/contexts_test.go#L77
 - https://github.com/docker/compose-cli/blob/c11a458666ac7e2de05719c5a0f461d0269f7d5d/cli/server/protos/contexts/v1/contexts.pb.go#L53

However, that field is unknown to the main docker CLI (there was a pull request to add this, but it was closed https://github.com/docker/cli/pull/2894)


Could you open this ticket in the https://github.com/docker/compose-cli/issues issue tracker? Unfortunately that's in a different org on GitHub, so I cannot transfer this ticket for you

/cc @gtardif
