### ISSUE TITLE
Feature Request: Add DOCKER-USER chain to ip6tables

### ISSUE THREAD

**Issue by SebastianJ91** [moby/moby#42477]
For now the DOCKER-USER chain is only created and referenced in iptables.
This needs to be implemented for ip6tables too, as this is the only secure way to add custom firewall rules in IPv6 only or dual stack environments.

https://github.com/moby/moby/blob/8dbd90ec00daa26dc45d7da2431c965dec99e8b4/libnetwork/firewall_linux.go#L19-L29

I'm deploying docker configuration via puppet, where it's not possible to add custom firewall rules in front of existing, so there also isn't a way to reference a self build DOCKER-USER chain at the right position as a workaround.

**Comment by neersighted** [comment]
Fixed in https://github.com/moby/moby/pull/44706
