### ISSUE TITLE
daemon.json Registry Mirrors not working.

### ISSUE THREAD

**Issue by yxxhero** [moby/moby#42476]
docker: 20.10.7  
Registry Mirrors:
  http://127.0.0.1:65001/

thanks very much.

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.
