### ISSUE TITLE
Flaky test: libnetwork TestSCTP4Proxy (broken on s390x?)

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#42495]
See https://ci-next.docker.com/public/job/moby/job/PR-42325/6/execution/node/255/log/

[s390x-integration-bundles.tar.gz](https://github.com/moby/moby/files/6623239/s390x-integration-bundles.tar.gz)

```
=== RUN   TestSCTP4Proxy
--- FAIL: TestSCTP4Proxy (0.43s)
panic: interface conversion: net.Addr is nil, not *sctp.SCTPAddr [recovered]
	panic: interface conversion: net.Addr is nil, not *sctp.SCTPAddr
goroutine 46 [running]:
testing.tRunner.func1(0xc0000a4a00)
	/usr/local/go/src/testing/testing.go:874 +0x41a
panic(0x206220, 0xc000063830)
	/usr/local/go/src/runtime/panic.go:679 +0x1d4
github.com/docker/docker/libnetwork/cmd/proxy.NewProxy(0x288640, 0xc000086340, 0x0, 0x0, 0xb, 0x1, 0x28ac00, 0xc000086320)
	/go/src/github.com/docker/docker/libnetwork/cmd/proxy/proxy.go:46 +0x1da
github.com/docker/docker/libnetwork/cmd/proxy.TestSCTP4Proxy(0xc0000a4a00)
	/go/src/github.com/docker/docker/libnetwork/cmd/proxy/network_proxy_test.go:294 +0x260
testing.tRunner(0xc0000a4a00, 0x255408)
	/usr/local/go/src/testing/testing.go:909 +0xd6
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x36c
FAIL	github.com/docker/docker/libnetwork/cmd/proxy	0.436s
```

**Comment by thaJeztah** [comment]
So the culprit may be somewhere due to https://github.com/golang/go/blob/go1.19.2/src/net/net.go#L214-L222

```go
// LocalAddr returns the local network address.
// The Addr returned is shared by all invocations of LocalAddr, so
// do not modify it.
func (c *conn) LocalAddr() Addr {
	if !c.ok() {
		return nil
	}
	return c.fd.laddr
}
```

Or at least, we’re using that value; it doesn’t return an error, so it may be unexpectedly `nil`


Could be an issue with that test; it’s using an `UDPEchoServer` for testing; which may not have all that’s needed to handle these cases

**Comment by Prabhav-Thali** [comment]
Hi @thaJeztah, 
The above test case failure error observed on s390x has been resolved by this [PR](https://github.com/ishidawataru/sctp/pull/62) in SCTP repo. Could you please pull the latest commits from [SCTP ](https://github.com/ishidawataru/sctp)repo for Docker-CE?

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/45301
