### ISSUE TITLE
Docker compose up with one or more volumes failed to start

### ISSUE THREAD

**Issue by MassimoTambu** [moby/moby#42525]
**Description**

Cannot start a container with one or more volumes with the new Version 3.4.0 of Docker Desktop.

**Steps to reproduce the issue:**
1. Install Docker Desktop 3.4.0 for windows.
2. Switch to Windows Container.
3. Add to docker compose one or more bind volumes.
4. run `docker compose up -d`.

**Describe the results you received:**

When I execute the command ` docker compose up -d` it gives me the following error:

`Error response from daemon: hcsshim::CreateComputeSystem 690966fdad9e4b447fd930354a2a7d6430f7f22d12979f304db99e4fc6cb7c39: The request is not supported.`

**This happens only if the docker compose file has one or more volumes (bind) and after updating to Docker Desktop 3.4.0, previous was 3.3.3 (and probably only on Windows Container, not tested on Linux).**

With no volumes the container starts.

**Describe the results you expected:**

The container should start as always.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to turn On/Off Hyper-V, restart, switch back and forth to Windows Container, enabled Desktop Virtualization and Hyper-V from BIOS settings but none of those have worked. I did those because the error seems, atleast googling on the internet, related to Virtualization.
I tried to set `isolation: process`, too. Same error.

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021   
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:41 2021   
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false  
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 95
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19042.1052)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.81GiB
 Name: NB10
 ID: JEHW:AHSR:FBMH:LBM5:TFMU:XUCQ:HT2H:O52N:RBWF:YOCH:VHDR:2AFQ
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on a Physical Machine, Win 10 Pro 20H2. WSL2 is enabled, but I tried with Hyper-V and I've got the same error, too.

If I downgrade to Docker desktop 3.3.3 it works fine.

I get the same error on another laptop.

**Comment by MassimoTambu** [comment]
It seems to work right now if I execute `docker-compose up -d`, but not with `docker compose up -d` . It gives me a generic "not implemented" message.

**Comment by thaJeztah** [comment]
If this works with the python implementation of compose (`docker-compose`) but fails with `docker compose`, I expect this may be an issue with the compose-cli; could you open a ticket (with a minimal compose-file as example) in the https://github.com/docker/compose-cli issue tracker?)
