### ISSUE TITLE
container killed every 48 hours

### ISSUE THREAD

**Issue by leafjungle** [moby/moby#42533]
problem desc:     I start a docker in my centos machine, but it is stopped automatically and unexpectedly every 48 hours. why?

docker version: Docker version 20.10.6, build 370c289

docker info:
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 33
 Server Version: 1.13.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: systemd
...
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
 runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
 init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
 Security Options:
  seccomp
  WARNING: You're not using the default seccomp profile
   Profile: /etc/docker/seccomp.json
  selinux
 Kernel Version: 3.10.0-862.11.6.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64

some useful tips maybe:
(1) the container's main process(pid=1) is just "bash", nobody will kill it.

(2) the memory costed by the container is almost the same all over its life.  Thus it is not killed by OOM.

(3) before the container is killed, it received a term signal, but I do not know who send this signal:
Container ... failed to exit within 10 seconds of signal 15 - using the force

**Comment by leafjungle** [comment]
then I upgrade docker api version to 1.41, the problem remains.

Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

------
I am wondering, if I start the docker with --stop-timeout with a large value, will it not be stopped?

**Comment by thaJeztah** [comment]
The " failed to exit within 10 seconds of signal 15 - using the force" message indicates that something told docker to stop the container. Docker itself won't kill containers (at least not every XX hours); I would suggest to check if there's no cronjob running on your machine that could be responsible. Automatic system updates could also play a role here (we've seen reports where unattended updates stop the docker service and/or other processes before performing system upgrades.

**Comment by cpuguy83** [comment]
This does not look like a docker issue, and the OP has not responded.
Closing.
