### ISSUE TITLE
Manually create the systemd unit files failed （ binary install）

### ISSUE THREAD

**Issue by SHIELD7** [moby/moby#42532]
**Description**

**Steps to reproduce the issue:**
1. For some reason we install docker with binary，and everything work.
2. Now I am trying to manually create the systemd unit files， [manually-create-the-systemd-unit-files](https://docs.docker.com/config/daemon/systemd/#manually-create-the-systemd-unit-files)
3. But I get this error `Failed to start docker.service: Unit containerd.service failed to load: No such file or directory.`

**Output of `docker version`:**

 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:28:35 2020
 OS/Arch:           linux/amd64
 Context:           default

**Output of `docker info`:**

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 38
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.73-5-default
 Operating System: SUSE Linux Enterprise Server 12 SP3
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.43GiB
 Name: linux-phte
 ID: 7YXP:XKOV:AQVR:YBZ4:XEOT:SKHA:UQAP:EERT:DJ22:N7IZ:ET33:5JW5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Additional environment details (AWS, VirtualBox, physical, etc.):**
system: SUSE 12 SP3

**Comment by AkihiroSuda** [comment]
You need `containerd.service` too
https://github.com/containerd/containerd/blob/master/containerd.service
