### ISSUE TITLE
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 10225 [0 1000000 1 1 100000 15665550]

### ISSUE THREAD

**Issue by Samahu** [moby/moby#42546]
**Description**

I am using rootless docker on a machine with no privilege access. I wanted  to use `gosu` tool as suggested by docker best practices guide and I applied all the steps successfully. However, due to some [issue](https://github.com/tianon/gosu/issues/85) when using `gosu` tool to map the host user id to the container user, the author of `gosu` suggested to increase the value of the third field in the two uid files (`/etc/subuid` and `/etc/subgid`). When I try that and restart docker, it no longer runs and I get the following error message:
```bash
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 10225 [0 1000000 1 1 100000 15665550]
```

The rootless mode guide doesn't specify any upper limit on the third field and just suggests to have a value larger than 65536 but this value doesn't work for me when integrating with `gosu` because my user id value is larger than that. 

**Steps to reproduce the issue:**
1. Change uid values to a value larger than 65536 that is suggested in the [rootless guide](https://docs.docker.com/engine/security/rootless/)
```bash
echo "<user>:100000:15665550" > /etc/subuid
echo "<user>:100000:15665550" > /etc/subgid
```
2. Start docker service: `systemctl --user start docker`
3. Check status: `systemctl --user start docker`

**Describe the results you received:**
`systemctl --user status docker` lists the following as the error:
```bash
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 10225 [0 1000000 1 1 100000 15665550]
```

**Describe the results you expected:**
Be able to set a value larger than 65536 and rootless docker would still work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```bash
Docker version 19.03.11, build 42e35e61f3
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///run/user/1000000/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ubuntu, rootless mode, gosu

**Comment by thaJeztah** [comment]
@AkihiroSuda this related to `SUB_UID_MAX ` and `SUB_GID_MAX ` and/or `SUB_UID_COUNT` ? (reading https://unix.stackexchange.com/a/271917 and https://man7.org/linux/man-pages/man5/login.defs.5.html ?

**Comment by Samahu** [comment]
Thanks @thaJeztah, I checked my `login.defs` file and it does not have any of these values set. Based on the man page to login.defs, the default values for SUB_UID_MIN, SUB_UID_MAX, SUB_UID_COUNT are respectively 100000, 600100000 and 65536. Do you think that merely increasing SUB_UID_COUNT to 15665550 would fix the issue?

**Comment by thaJeztah** [comment]
TBH, I don't know; I mostly went looking if I could find something about limits for these values, then stumbled upon that discussion.

If this is a test-system, or if you have a system to test on, it's also worth trying docker 20.10, just to be sure it's not something in the moby / docker code, that was fixed after 19.03 😅

**Comment by AkihiroSuda** [comment]
Is your host running on LXD or something similar?
Maybe you are already in user namespace with 65536 UID limit?

**Comment by Samahu** [comment]
> Is your host running on LXD or something similar?
> Maybe you are already in user namespace with 65536 UID limit?

Yes, I did have the UID limit set to 65536, but apparently merely adjusting the values found ` /etc/subuid` and ` /etc/subgid` does not cut it and you have to adjust the respective constants {SUB_UID_MIN, SUB_UID_MAX, SUB_UID_COUNT} found in `logins.def` and then restart. The problem I don't know much about the implication of this and I don't have a large leverage to validate them (no privileged access). 

That being the case, I think I am going call this ticket closed but anyone with background on this feel free to enlighten me on what can be done to run **gosu** with **docker** in _rootless mode_.

**Comment by Samahu** [comment]
> Is your host running on LXD or something similar?
> Maybe you are already in user namespace with 65536 UID limit?

Yes, I did have the UID limit set to 65536, but apparently merely adjusting the values found ` /etc/subuid` and ` /etc/subgid` does not cut it and you have to adjust the respective constants {SUB_UID_MIN, SUB_UID_MAX, SUB_UID_COUNT} found in `logins.def` and then restart. The problem I don't know much about the implication of this and I don't have a large leverage to validate them (no privileged access). 

That being the case, I think I am going call this ticket closed but anyone with background on this feel free to enlighten me on what can be done to run **gosu** with **docker** in _rootless mode_.
