### ISSUE TITLE
Is the latest https://master.dockerproject.org/windows/x86_64/dockerd.exe corrupted?

### ISSUE THREAD

**Issue by Keith-Mange** [moby/moby#42609]
**Description**

The latest https://master.dockerproject.org/windows/x86_64/dockerd.exe is only 2mb.  It should be much bigger based on history.

**Steps to reproduce the issue:**
1. Download https://master.dockerproject.org/windows/x86_64/dockerd.exe
2. dockerd --register-service

**Describe the results you received:**

dockerd --register-service
dockerd.exe : flag provided but not defined: -register-service

**Describe the results you expected:**

Normally it succeeds.  I tried 20.10.7 and it works and the file size of dockerd.exe is 64mb

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           master-dockerproject-2021-07-07
 API version:       1.41
 Go version:        go1.16.5
 Git commit:        5f07d7d5a1
 Built:             Thu Jul  8 00:06:08 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.43.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.729GiB
 Name: docker-desktop
 ID: AMHB:BC43:XXZP:26TP:XDQ2:JIGR:SSEZ:AHBS:H63C:OWDV:P4SS:RILK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows -- physical machine.

**Comment by thaJeztah** [comment]
It looks to be really small (only 2MB), so possibly that something is  wrong in the pipeline building those binaries

<img width="837" alt="Screenshot 2021-07-08 at 22 16 02" src="https://user-images.githubusercontent.com/1804568/124984987-2a757d80-e03a-11eb-8dcd-0ef4f8133778.png">

Regular (non-master) static packages are (since recently) pushed again on download.docker.com if that may help you; https://download.docker.com/win/static/stable/x86_64/

**Comment by thaJeztah** [comment]
LOL, I now see you also mentioned the 2MB size (sorry overlooked that)

**Comment by rmiller14** [comment]
It definitely got clobbered by something else - I think it's docker-proxy based on the "usage" output.

**Comment by Keith-Mange** [comment]
The newest version has the same issue.

Would this be the output for docker-proxy?

dockerd.exe -- help

Usage of c:\Users\kemange\Downloads\dockerd.exe:
  -container-ip string
        container ip
  -container-port int
        container port (default -1)
  -host-ip string
        host ip
  -host-port int
        host port (default -1)
  -proto string
        proxy protocol (default "tcp")

**Comment by thaJeztah** [comment]
Yes, that looks like the `docker-proxy` indeed.

**Comment by Keith-Mange** [comment]
Does anyone have advice on how we get this fixed?

Thanks,
Keith

**Comment by jeff-estes-saggs** [comment]
yep still borked...as of today.

**Comment by thaJeztah** [comment]
Should be fixed by https://github.com/docker/docker-ce-packaging/pull/578 (when the next build is triggered)
