### ISSUE TITLE
Windows: If HcsShutdownComputeSystem returns ERROR_PROC_NOT_FOUND, moby leaks the container

### ISSUE THREAD

**Issue by kevpar** [moby/moby#42610]
HCS provides two functions to stop a container:
- `HcsShutdownComputeSystem` is used first, and attempts to gracefully stop the container.
- `HcsTerminateComputeSystem` is used if shutdown fails, and force stops the container.

moby uses `hcsshim.IsAlreadyStopped` to check if the error returned from `HcsShutdownComputeSystem` indicates that the container has already terminated, and only calls `HcsTerminateComputeSystem` if it is still running. However, due to a bug in `hcsshim.IsAlreadyStopped`, this function returned `true` if the error was `ERROR_PROC_NOT_FOUND`, which can be returned even if the container is left running. When this happened, moby would effectively leak the container, leaving it running in HCS, but assuming from moby's point of view that it had stopped.

**Comment by kevpar** [comment]
This has been fixed in Microsoft/hcsshim#1064, backported to v0.8 in Microsoft/hcsshim#1065, and a new release cut (v0.8.20). Once we vendor the new release this issue should be fixed in moby.

**Comment by kevpar** [comment]
@thaJeztah Any concerns with backporting this to 19.03 as well? I'll send a PR if not.

**Comment by thaJeztah** [comment]
@kevpar already beat you to it; https://github.com/moby/moby/pull/42613. It sounds "fine" to backport (looking at the diff) but must admit I'm not a hcsshim "expert" 😅

**Comment by thaJeztah** [comment]
Oh! Misread; 19.03.. hmm.. I don't think there's plans to do more 19.03 releases

**Comment by thaJeztah** [comment]
We could discuss accepting PR's to be merged in the 19.03 branch (without doing a release) @cpuguy83 thoughts on that?

**Comment by kevpar** [comment]
I didn't realize 19.03 wasn't getting more releases. I think it's probably fine to just take this in 20.10 in that case. I had tried looking on Mirantis's website but couldn't find much info on release schedules. :)
