### ISSUE TITLE
Docker client SDK doesn't respect DOCKER_CONTEXT or 'docker context'

### ISSUE THREAD

**Issue by nicks** [moby/moby#42650]
**Description**

We develop a tool that uses the Docker Engine SDK, as documented here:
https://docs.docker.com/engine/api/sdk/examples/

Here's the sample code for creating a Docker client:

```
cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
```

Users have complained to us that they really like to use `docker context` / and the `DOCKER_CONTEXT` env variable to manage multiple docker instances. https://docs.docker.com/engine/context/working-with-contexts/

But a Docker client created this way doesn't use the current context.

Is this intentional? If not, is there something I can point users to to explain why not? Is there a recommended way to construct the client that does use this?

**Steps to reproduce the issue:**
See above

**Describe the results you received:**
DOCKER_CONTEXT never used

**Describe the results you expected:**
The DOCKER_CONTEXT env variable is used to determine DOCKER_HOST

**Comment by cpuguy83** [comment]
The client doesn’t have any concept of a context.

**Comment by nicks** [comment]
@cpuguy83 yep! I figured that out as well.

Is that the way it should be?

basically trying to figure out if:
- are there intractable technical reasons why client opts can't read the DOCKER_CONTEXT?
- if not, would you ever accept a change that added a client.FromEnvWithContext (similar to client.FromEnv)? Or would that make more sense as a separate library?

**Comment by thaJeztah** [comment]
`docker context` is all implemented in docker's CLI repository, and effectively as "one way" to store settings for the cli/client to be configured.

`client.FromEnv` implements a `client.Opt` https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/options.go#L16-L17

Which can be passed as option for `NewClientWithOpts()`; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/client.go#L119

I think it should be possible to implement such an option in docker/cli, which; takes the name of a context, reads the configuration options from the context, and applies client-opts as defined in this repository.

However, as mentioned, this would be best to implement in the docker/cli repository (https://github.com/docker/cli)

I'll close this ticket here for that reason, but feel free to open a ticket and/or draft PR / proposal there if you're interested.
