### ISSUE TITLE
"const rx" variables in "volume/mounts" should probably use "regexp.MustCompile"

### ISSUE THREAD

**Issue by tianon** [moby/moby#42667]
> This isn't new, so I'm not suggesting we change it now, but shouldn't this (and the friends it moved away from) be `regexp.MustCompile`'d?

_Originally posted by @tianon in https://github.com/moby/moby/pull/42520#discussion_r675735780_

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/42673 as draft
