### ISSUE TITLE
Rootless docker with overlay2 storage does not respect opaque directory entries for re-created directories

### ISSUE THREAD

**Issue by YenTheFirst** [moby/moby#42662]
**Description**

When running rootless docker 20.10.7 on an updated ubuntu 20.04, with the default overlay2 storage driver, files in deleted directories are "un-deleted", if the directory is deleted and re-created in the same step

**Steps to reproduce the issue:**
1. Install rootless docker per instructions
2. Write the dockerfile:
```
FROM alpine:3.14

WORKDIR tmp
RUN mkdir dir1
RUN touch dir1/should_be_deleted
RUN rm -r dir1 && mkdir dir1
RUN touch dir1/should_be_visible

CMD ls -R
```
3. Build and execute:
```
docker build --no-cache . -t imagetest && docker run imagetest
``` 

**Describe the results you received**:
Got the output:
```
.:
dir1

./dir1:
should_be_deleted
should_be_visible
```

**Describe the results you expected:**
Expected only:
```
.:
dir1

./dir1:
should_be_visible
```

**Additional information you deem important (e.g. issue happens only occasionally):**
On rootful docker on the same machine, I instead get the expected output with the same Dockerfile.

If `RUN rm -r dir1 && mkdir dir1` is instead split into 2 `RUN` commands, I get the correct output.

If the command is switched to `RUN rm -r dir1 && mkdir dir2`, `RUN touch dir2/should_be_visible`, I also get the expected output.

The error only occurs when deleting and re-creating the directory in the same step. In practice, this sometimes occurs with package managers such as `pip` doing a re-install. 

**Output of `docker version`:**

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:51:04 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:29 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 30
  Running: 0
  Paused: 0
  Stopped: 30
 Images: 1178
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.8.0-63-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.01GiB
 Name: mise
 ID: HMZJ:TITG:U4LG:CCK7:Q7OK:IRZ3:KZFN:WGCB:H44J:RBLT:HWKR:XLZZ
 Docker Root Dir: /home/talin/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Linux  5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
In particular, I notice that `Native Overlay Diff: false`, but on rootful docker this is `true`.

**Comment by YenTheFirst** [comment]
Further info: switching the storage driver to `fuse-overlayfs` on rootless docker also resolves the issue.

**Comment by thaJeztah** [comment]
Does the file re-appear in the same step as well? i.e, if you add an `ls` in the same step?

```dockerfile
RUN rm -r dir1 && mkdir dir1 && ls dir1
```

**Comment by YenTheFirst** [comment]
The file does _not_ re-appear in the same step.

Modified Dockerfile:
```
FROM alpine:3.14

WORKDIR tmp
RUN mkdir dir1
RUN touch dir1/should_be_deleted
RUN rm -r dir1 && mkdir dir1 && touch dir1/should_be_visible && ls dir1

CMD ls -R
```

building:
```
$ docker build --no-cache . -t imagetest
Sending build context to Docker daemon  28.67kB
<snip>
Step 5/6 : RUN rm -r dir1 && mkdir dir1 && touch dir1/should_be_visible && ls dir1
 ---> Running in 249fbca18450
should_be_visible
Removing intermediate container 249fbca18450
 ---> db54d88b462c
Step 6/6 : CMD ls -R
<snip>
```

and then running:
```
$ docker run imagetest
.:
dir1

./dir1:
should_be_deleted
should_be_visible
```

**Comment by cpuguy83** [comment]
Indeed this sounds like an issue with the overlay differ implementation.

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/moby/moby/pull/42188? @AkihiroSuda ?

I recall we once had a report for this, long time ago; https://github.com/moby/moby/issues/27070. I think there was another thread with more details about a similar case 🤔. Also recall https://github.com/moby/moby/issues/38072#issuecomment-475464321, but not sure if that's related here.

**Comment by YenTheFirst** [comment]
Seeing #42188 resolved, I re-run this test with rootless docker on overlay2 driver, and the correct output is observed.

Revisited this because I've started seeing similar issues with fuse-overlayfs and pip, but I haven't had time to narrow down a reproduction.
