### ISSUE TITLE
cgroups-v2: containerd v.1.4.8 / runc v1.0.0 is not compatible with container-selinux policy =< v2.164.1

### ISSUE THREAD

**Issue by dave-tucker** [moby/moby#42677]
**Description**

Since containerd 1.4.8 RPMs were made available on the docker repo, I'm unable to start containers on my Fedora 34 system with cgroups v2.

This appears to be because containerd 1.4.8 includes runc v1.0.0 which now (since the v1.0.0-rc95 release) appears to require additional permissions to do  bpf things and `container-selinux` is shutting it down.

```
SELinux is preventing runc from prog_run access on the bpf labeled init_t.
```

I've tested with the `container-selinux` v2.164.1 (which doesn't yet ship on fedora) and it still doesn't work, so I'll (speculatively) open an issue over there too.

Folks packaging moby for systems with SElinux will need to bump the dependency of container-selinux if the fix is indeed there.

**Steps to reproduce the issue:**
1. Install `docker-ce` on F34
2. `docker run -it --rm alpine`

**Describe the results you received:**

```
$ docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: cannot fetch program from id: get program by id: permission denied: unknown.
```

**Describe the results you expected:**

The container to run

**Additional information you deem important (e.g. issue happens only occasionally):**

Downgrading to containerd 1.4.6 - `dnf downgrade containerd.io` isn't recommended as a fix, since containerd v1.4.8 fixes a CVE.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:04 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.4-200.fc34.x86_64
 Operating System: Fedora 34 (KDE Plasma)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: dave-fedora
 ID: PUFS:FKND:F6JO:WD7P:F27M:3TUQ:MP7J:FRXI:I3AU:KN6M:DTWP:33YG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: davetucker
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Related: https://github.com/containerd/containerd/issues/5759

this is a regression in runc v1.0.0, and fixed by https://github.com/opencontainers/runc/pull/3055, which was back ported in https://github.com/opencontainers/runc/pull/3087 for v1.0.1

I asked the containerd maintainers for a new release to be tagged with the v1.0.1 update, and we'll do an updated package with that change (hopefully soon)

**Comment by dave-tucker** [comment]
Sounds like it's not container-selinux then :+1:. I'll close the issue over there for now.

**Comment by thaJeztah** [comment]
containerd.io v1.4.9 and v1.5.5 have been released, which have runc v1.0.1: https://github.com/containerd/containerd/releases, and `containerd.io` v1.4.9 packages have been published on download.docker.com

A patch release of Docker (20.10.8) will also be available soon (hopefully start of next week) for people that use the static binaries (which bundles docker, the docker cli, containerd and runc in a single tar) or the official docker-in-docker images from https://hub.docker.com/_/docker/)


Let me go ahead and close this ticket 👍

**Comment by dave-tucker** [comment]
@thaJeztah hmmm we might need to re-open it.

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:04 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Running containers works just fine, but roughly a few seconds after the container is started I get the same SELinux denial posted in the original description. So maybe container-selinux policy needs updating?

**Comment by thaJeztah** [comment]
Hmm... yeah, perhaps (I did try starting a container, and it worked, but perhaps some other things are blocked?)

Can you report this in the runc repository?

> I get the same SELinux denial posted in the original description.

(that's assuming it's runc giving the issue that is ^)

**Comment by cyphar** [comment]
> SELinux is preventing runc from prog_run access on the bpf labeled init_t.

Hmm, that should've been fixed by opencontainers/runc#3055 -- we ignore any program that we cannot fetch (which is the systemd-owned programs). I might need to try this out on Fedora myself (the patch I linked fixes the problem in openSUSE MicroOS which is where I first found this issue).

**Comment by thaJeztah** [comment]
Yeah, not sure either. Hope @dave-tucker is able to provide more details (or ask internally at Red Hat if they have ideas 😉).

A simple `docker run` worked for me on Fedora 34 (with runc v1.0.1), whereas it failed on v1.0.0. So, curious if there's some scenario that is different.

**Comment by dave-tucker** [comment]
Reported in https://github.com/opencontainers/runc/issues/3121

@cyphar @thaJeztah I'm not sure this is Fedora specific. We've all noted that, `docker run` works, and so far I haven't noticed any issues with functionality. The only reason I noticed the issue after updating containerd was because my daily driver is a Fedora machine and I have `setroubleshoot` installed so I get a pop-up notification for every denial.

From the CLI, you can try `sudo ausearch -m avc -c runc`
```
time->Tue Aug  3 16:50:50 2021
type=AVC msg=audit(1628005850.806:371): avc:  denied  { prog_run } for  pid=15175 comm="runc" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
----
time->Tue Aug  3 17:55:50 2021
type=AVC msg=audit(1628009750.664:405): avc:  denied  { prog_run } for  pid=33034 comm="runc" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
----
time->Tue Aug  3 17:56:41 2021
type=AVC msg=audit(1628009801.133:426): avc:  denied  { prog_run } for  pid=35102 comm="runc" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
----
time->Tue Aug  3 17:57:27 2021
type=AVC msg=audit(1628009847.253:447): avc:  denied  { prog_run } for  pid=36981 comm="runc" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
----
time->Tue Aug  3 17:58:11 2021
type=AVC msg=audit(1628009891.167:468): avc:  denied  { prog_run } for  pid=38767 comm="runc" scontext=system_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=bpf permissive=0
```
