### ISSUE TITLE
docker containers crashing rarely

### ISSUE THREAD

**Issue by guhan2104** [moby/moby#42687]
I am running my application as docker containers using docker-compose, rarely my containers were crashing. Here is the log

Docker 20 running on ubuntu 20.04 ( docker.io )

systemd[1]: Started PackageKit Daemon.
    systemd[1]: Stopping containerd container runtime...
    dockerd[730415]: time="2021-07-28T06:20:24.570714016Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
	dockerd[730415]: time="2021-07-28T06:20:24.570763160Z" level=info msg="Waiting for containerd to be ready to restart event processing" module=libcontainerd namespace=moby
	dockerd[730415]: time="2021-07-28T06:20:24.570836944Z" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
	dockerd[730415]: time="2021-07-28T06:20:24.575231200Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
	dockerd[730415]: time="2021-07-28T06:20:24.575258182Z" level=info msg="Waiting for containerd to be ready to restart event processing" module=libcontainerd namespace=plugins.moby
	dockerd[730415]: time="2021-07-28T06:20:24.575287313Z" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
	containerd[472]: time="2021-07-28T06:20:24.572203327Z" level=info msg="Stop CRI service"
	systemd[1]: containerd.service: Succeeded.
	systemd[1]: Stopped containerd container runtime.
	dockerd[730415]: time="2021-07-28T06:20:25.571835485Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
	dockerd[730415]: time="2021-07-28T06:20:25.575521541Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
	dockerd[730415]: time="2021-07-28T06:20:28.115344644Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
	dockerd[730415]: time="2021-07-28T06:20:28.242414629Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
	systemd[1]: Reloading.

**Comment by zouyonghao** [comment]
I got this issue today, it seems it is caused by automatic docker updating by systemd.

**Comment by thaJeztah** [comment]
Note that the `docker.io` package is a package that's not maintained by us, but by the distro maintainers; not sure if there's anything actionable in here (doesn't immediately look like a bug in the code in this repository); I'll go ahead and close, but feel free to continue the conversation if there's anything to address
