### ISSUE TITLE
What is the correct way to change docker version?

### ISSUE THREAD

**Issue by tufeigunchu** [moby/moby#42702]
I am trying to compile docker from source, it succeed but when I run docker version, the daemon version shows "dev" and kubernetes doesn't like it. I have tried to edit daemon/info.go dockerversion/version_lib.go but it has no effect. 
I build from this tag "v20.10.2"

**Comment by cpuguy83** [comment]
The builder sets some ldflags from here:

https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/hack/make/.go-autogen#L10-L17

**Comment by thaJeztah** [comment]
looks like this was answered
