### ISSUE TITLE
panic：‘invalid memory address or nil pointer dereference‘ in rejoinClusterBootStrap

### ISSUE THREAD

**Issue by wangchonghu** [moby/moby#42713]
**Description**

The swarm node crash with panic when cpu-load keeps high(>90%)。

 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xaaaac8a00f98]
 goroutine 3450 [running]:
 panic(0xaaaac96b64a0, 0xaaaaca638ff0)
 	/go/src/runtime/panic.go:1065 +0x4d8 fp=0x4009229d10 sp=0x4009229c40 pc=0xaaaac7f66948
 runtime.panicmem()
 	/go/src/runtime/panic.go:212 +0x58 fp=0x4009229d30 sp=0x4009229d10 pc=0xaaaac7f64d08
 runtime.sigpanic()
 	/go/src/runtime/signal_unix.go:734 +0x154 fp=0x4009229d70 sp=0x4009229d30 pc=0xaaaac7f7e374
 github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap(0x400974b680)
 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:305 +0x488 fp=0x4009229ee0 sp=0x4009229d80 pc=0xaaaac8a00f98
 github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap-fm()
 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:284 +0x30 fp=0x4009229f00 sp=0x4009229ee0 pc=0xaaaac8a26520
 github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0x400974b680, 0xdf8475800, 0x4007aa19e0, 0x4007f8d8e0)
 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:256 +0xdc fp=0x4009229fb0 sp=0x4009229f00 pc=0xaaaac8a0085c
 runtime.goexit()
 	/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x4009229fb0 sp=0x4009229fb0 pc=0xaaaac7f9e024
 created by github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x770

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.  Please provide more information on your configuration.
