### ISSUE TITLE
FEATURE REQUEST: Let awslogs driver support embedded metrics format (emf)

### ISSUE THREAD

**Issue by mooreniemi** [moby/moby#42731]
# Current state

Right now the `awslogs` driver does not accept the `json/emf` parameter in any way, which means when using embedded metrics format logs with CloudWatch, you won't be able to get those logs parsed as metrics.

# Desired state

`awslogs` driver accepts a `emf` or `log_format` configuration parameter, toggling on adding the `x-amzn-logs-format` header in requests to CloudWatch as described in https://github.com/awslabs/aws-embedded-metrics-python/issues/13

For example, could add `logFormat` to `logStreamConfig`:

https://github.com/moby/moby/blob/b88acf7a7a571b0fe054b8315c79caa16b0c92df/daemon/logger/awslogs/cloudwatchlogs.go#L86-L95

# Probable impact

Right now [ECS](https://aws.amazon.com/ecs/) users are in an awkward and confusing situation where turning `awslogs` on means you get logs from your containers to CloudWatch very easily (and you can even get some metrics using [Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html), which uses EMF), but if you structure your application logs for EMF you have to abandon the driver and set up an entirely different agent (either a CloudWatch agent or a Fluentd agent using FireLens) just to get back to the same state. 

Although there are cases where it's preferable to set up a separate agent, it seems like allowing users to decide this trade off and have the easiest experience getting custom metrics from their logs would be a great user experience for very minimal effort. I'm happy to try and submit a PR if the team is amenable to the idea.

## Related links
- [awslogs driver](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html)
- [EMF specification](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html)
 - [Using CloudWatch agent and EMF](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_CloudWatch_Agent.html)

**Comment by AWS-MattB** [comment]
The Amazon Cloudwatch Agent is opensource so you can [take a peek](https://github.com/aws/amazon-cloudwatch-agent/blob/26a8d281ce74295f72f69d1443458dcea73af1f9/plugins/outputs/cloudwatchlogs/cloudwatchlogs.go#L307) at how they do it. I'm actually not certain what happens if you include that header when not sending EMF-formatted logs.

**Comment by gordonpn** [comment]
@kennedyjustin @ferdingler @thaJeztah @AWS-MattB,

Any EMF logs that can reach CloudWatch Logs will now be parsed and metrics can be generated from them. You don't need the EMF header anymore.

If you face any issues, you can get in touch with me!

**Comment by samuelkarp** [comment]
This should have been closed back in December 2021 when we merged https://github.com/moby/moby/pull/42838, but it looks like we missed it.

Closing now, thanks!
