### ISSUE TITLE
Flaky test: lib network TestNetworkDBCRUDTableEntries

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#42739]
Have seen this failing various times now;

```
=== FAIL: libnetwork/networkdb TestNetworkDBCRUDTableEntries (7.25s)
    networkdb_test.go:314: Entry existence verification test failed for node2(df7cec9ba2d9)
2021/08/12 11:35:37 Closing DB instances...
````

This test also has other issues w.r.t. synchronisation, which could be related; https://github.com/moby/moby/issues/42646

**Comment by tiborvass** [comment]
This should be fixed by https://github.com/moby/moby/pull/44500 and has nothing to do with go-radix.
