### ISSUE TITLE
Docker is extremely slow to start multiple (20+) containers at once 

### ISSUE THREAD

**Issue by aholyoake-bc** [moby/moby#42817]
**Description**
When starting many containers at once (20+) docker is unable to start them in a timely fashion.

The downloading and extraction of images happens in an expected amount of time, but making the containers and running them hangs for many minutes.

When running `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2` we see a number of stacktraces such as 
```
goroutine 10777 [syscall, 3 minutes]:
syscall.Syscall(0xa6, 0xc00239e000, 0x2, 0x0, 0x7a, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
github.com/docker/docker/vendor/golang.org/x/sys/unix.Unmount(0xc002979e80, 0x79, 0x2, 0x0, 0x79)
        /go/src/github.com/docker/docker/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1493 +0x9c
github.com/docker/docker/daemon/graphdriver/overlay2.(*Driver).Put(0xc000050200, 0xc001289450, 0x45, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/graphdriver/overlay2/overlay.go:624 +0x327
github.com/docker/docker/layer.(*layerStore).initMount(0xc0001a8ea0, 0xc000f8f600, 0x40, 0xc001704040, 0x40, 0x0, 0x0, 0xc000fd6800, 0x0, 0xc001722cf0, ...)
        /go/src/github.com/docker/docker/layer/layer_store.go:689 +0x1f7
github.com/docker/docker/layer.(*layerStore).CreateRWLayer(0xc0001a8ea0, 0xc000f8f080, 0x40, 0xc001289400, 0x47, 0xc00107e400, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/layer/layer_store.go:539 +0x48e
github.com/docker/docker/daemon/images.(*ImageService).CreateLayer(0xc000428ea0, 0xc0016df200, 0xc000fd6800, 0x0, 0x0, 0xc0017a8000, 0xc001342d80)
        /go/src/github.com/docker/docker/daemon/images/service.go:133 +0x143
github.com/docker/docker/daemon.(*Daemon).create(0xc00000c3c0, 0x0, 0x0, 0xc0017a8000, 0xc001342d80, 0xc001262010, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/daemon/create.go:191 +0x2dd
github.com/docker/docker/daemon.(*Daemon).containerCreate(0xc00000c3c0, 0x0, 0x0, 0xc0017a8000, 0xc001342d80, 0xc001262010, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/daemon/create.go:93 +0x1c9
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc00000c3c0, 0x0, 0x0, 0xc0017a8000, 0xc001342d80, 0xc001262010, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/daemon/create.go:40 +0xf3
```

which indicates that the syscall to unmount is blocking for some reason.

Htop output confirms that the processes are in uninterruptible sleep

```
21622 root       20   0 5107M  371M 58024 D  0.0  0.4  0:42.67 /usr/bin/dockerd --config-file /etc/docker/daemon.json
21623 root       20   0 5107M  371M 58024 D  0.0  0.4  0:35.83 /usr/bin/dockerd --config-file /etc/docker/daemon.json
21626 root       20   0 5107M  371M 58024 D  0.0  0.4  0:53.79 /usr/bin/dockerd --config-file /etc/docker/daemon.json
21631 root       20   0 5107M  371M 58024 D  0.0  0.4  0:39.47 /usr/bin/dockerd --config-file /etc/docker/daemon.json
21632 root       20   0 5107M  371M 58024 D  0.0  0.4  0:47.29 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22496 root       20   0 5107M  371M 58024 D  0.0  0.4  0:24.77 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22497 root       20   0 5107M  371M 58024 D  0.0  0.4  0:24.31 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22500 root       20   0 5107M  371M 58024 D  0.0  0.4  0:48.86 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22505 root       20   0 5107M  371M 58024 D  0.0  0.4  0:55.75 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22507 root       20   0 5107M  371M 58024 D  0.0  0.4  0:29.16 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22508 root       20   0 5107M  371M 58024 D  0.0  0.4  0:32.49 /usr/bin/dockerd --config-file /etc/docker/daemon.json
22509 root       20   0 5107M  371M 58024 D  0.0  0.4  0:33.00 /usr/bin/dockerd --config-file /etc/docker/daemon.json
23364 root       20   0 5107M  371M 58024 D  0.0  0.4  0:50.08 /usr/bin/dockerd --config-file /etc/docker/daemon.json
24939 root       20   0 5107M  371M 58024 D  0.0  0.4  0:38.93 /usr/bin/dockerd --config-file /etc/docker/daemon.json
27097 root       20   0 5107M  371M 58024 D  0.0  0.4  0:25.73 /usr/bin/dockerd --config-file /etc/docker/daemon.json
28037 root       20   0 5107M  371M 58024 D  0.0  0.4  0:28.08 /usr/bin/dockerd --config-file /etc/docker/daemon.json
28039 root       20   0 5107M  371M 58024 D  0.0  0.4  0:13.48 /usr/bin/dockerd --config-file /etc/docker/daemon.json
28041 root       20   0 5107M  371M 58024 D  0.0  0.4  0:24.79 /usr/bin/dockerd --config-file /etc/docker/daemon.json
28042 root       20   0 5107M  371M 58024 D  0.0  0.4  0:15.27 /usr/bin/dockerd --config-file /etc/docker/daemon.json
```

No downloading / extracting of layers appears to be happening at the time, i.e. we no longer are recieving messages to the terminal and we receive the message
```
Status: Downloaded newer image for XXX
```

This is causing havoc with our orchestrator (Hashicorp Nomad) because tasks don't come up in a timely fashion, so they get killed and the process starts again. We this behaviour when draining an old node and the jobs get scheduled on a new one.

**Steps to reproduce the issue:**
1.
```
#!/bin/bash
images=($image_1
$image_2
$image_3)
for i in "${images[@]}"; do docker --config /etc/docker run  -td --entrypoint "/bin/bash" "$i"  -c tail -f /dev/null & done
```
2. `watch "docker ps"`

**Describe the results you received:**
Containers are very slow (up to 20 minutes of inactivity) to run after the image has been downloaded and extracted. My guess is that something times out and then suddenly all containers spring to life - the next stack trace has none of the blocked calls to `Unmount` 

inode usage on the root filesystem never exceeds 20% as reported by `df --inodes`

**Describe the results you expected:**
I would expect containers to be started soon after the last layer has finished extracting.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Tried with both the below
```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:05 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:34 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 38
  Running: 19
  Paused: 0
  Stopped: 19
 Images: 19
 Server Version: 19.03.15
 Storage Driver: overlay
  Backing Filesystem: extfs
  Supports d_type: true
 Logging Driver: syslog
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 4.19.0-17-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 102.3GiB
 Name: backend-servicemesh-v000-znv5
 ID: MTFJ:ZU7J:AG67:IEX4:P25T:7XBZ:VQIW:KHMU:VBEG:ODB7:KCSK:D3MO
 Docker Root Dir: /var/lib/docker/600200000.600200000
 Debug Mode: true
  File Descriptors: 183
  Goroutines: 104
  System Time: 2021-09-03T14:51:54.354024598Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.
```
Note: We have tried with both overlay and overlay2 and both suffer the same problem

I'm at a bit of a loss as to how to debug this further, so any pointers would be gratefully received!

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Google Cloud VMs (100+GB SSD, 16 cores, 100+GB RAM)

**Comment by zq-david-wang** [comment]
Try  `dmesg` to check kernel logs, seems like a lower layer IO issue, kernel may report something.

**Comment by aholyoake-bc** [comment]
There is nothing going on in `dmesg`, although that did highlight that my auditd rules for docker are a bit chatty. Turning off the auditd rules for docker at least allows it to fail more fluidly, whatever that means.
```

Sep 06, '21 18:18:01 +0100 | Not Restarting | Error was unrecoverable
-- | -- | --
Sep 06, '21 18:18:00 +0100 | Driver Failure | failed to create container: container already exists
Sep 06, '21 18:14:10 +0100 | Alloc Unhealthy | Task not running by deadline
Sep 06, '21 18:11:11 +0100 | Driver | Docker image pull progress: Pulled 8/8 (625.9MiB/625.9MiB) layers: 0 waiting/0 pulling
Sep 06, '21 18:09:11 +0100 | Driver | Downloading image
Sep 06, '21 18:09:10 +0100 | Task Setup | Building Task Directory
Sep 06, '21 18:09:10 +0100 | Received | Task received by client
```
This is a pretty standard mode of failure that I'm seeing

Here's a complete goroutine dump of what's going on at the moment, trying to start around 20 images at once

[goroutines.gz](https://github.com/moby/moby/files/7117296/goroutines.gz)

**Comment by jespada-bc** [comment]
After @aholyoake-bc reports I keep running tests, but wasn't able to reproduced this issue outside google GCP, even in small vagrant VM (virtualbox HV), so I open a case with GCP(below in case someone else want to try to reproduce it):

We initially thought it was related to docker but we are unable to reproduce it outside GCP, so now we suspect its related to GCP cloud images config (kernel, underlying HV or something else).

The problem seem to be that docker is unable to start new containers while is pulling images from the remote registry (eu.gcr.io or docker hub or any other), even if the image is already on the filesystem, could this be related to some feature in the underlying hypervisor(syscall inspection or something similar).

In order to reproduce this issue:
1- Spin up any VM (debian10/11 from gcp official cloud image: `gcloud compute images list |grep debian-cloud`).
2- install docker:
```
    apt-get update
    apt-get install -y apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io

    echo "to test run:  docker run hello-world"
```

3- Pull and run any image:
   docker --config /etc/docker run   -td --entrypoint "/bin/sh" ubuntu:21.04 -c tail -f /dev/null
4- Open another terminal(ssh) and launch `watch -n 1 docker ps` (you'll see a container running) so far so good.
5- Open yet another terminal and run the following script(or anything that makes docker pull and run a few images):
```
 images=(debian:bookworm debian:bookworm-backports debian:bookworm-slim debian:bullseye debian:bullseye-backports debian:bullseye-slim debian:buster debian:buster-backports debian:buster-slim debian:experimental debian:oldoldstable debian:oldoldstable-backports debian:oldoldstable-slim debian:oldstable debian:oldstable-backports debian:oldstable-slim debian:rc-buggy debian:sid debian:sid-slim debian:stable debian:stable-backports debian:stable-slim debian:stretch debian:stretch-backports debian:stretch-slim debian:testing debian:testing-backports debian:testing-slim debian:unstable debian:unstable-slim ubuntu:18.04 ubuntu:20.04 ubuntu:21.04 ubuntu:21.10 ubuntu:14.04 ubuntu:16.04)

for i in "${images[@]}"; do docker --config /etc/docker run  -td --entrypoint "/bin/sh" "$i"  -c tail -f /dev/null & done
```

6- As soon as you launch the script go to the terminal on step 3(you should get your prompt back) and run the same docker run again:
   `docker --config /etc/docker run   -td --entrypoint "/bin/sh" ubuntu:21.04 -c tail -f /dev/null`

7- You'll see that it hangs even tho the ubuntu:21.04 image is already in the filesystem and it hangs until the script on step 5 is done pulling and un-compressing the images.

Using tmux or similar system with 3 panes on the same screen will help visualise it.

This is not an issue on small vm with virtualbox as HV  or on any other modest laptop. I've even tried with really beefy VM's (IOPS optimised etc) on GCP and the issue remains

Google GCP support was able to reproduce it, but they claim this is 3rd party software so not supported.

I ran a few more tests and capture strace stats , iostat and pprof on a GCP VM(where we see the issue) and on local vagrant VM (vbox as HV): 
https://gist.github.com/jespada-bc/c3104b71e6da4dec336d3d8d4daa0b61

[GCP strace](https://gist.github.com/jespada-bc/c3104b71e6da4dec336d3d8d4daa0b61#gistcomment-3928728)

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 41.73 2381.873356    17013381       140        22 waitid
 31.78 1813.668715        1623   1117267     96144 futex
  9.52  543.353813     5078073       107           umount2
  4.47  255.278123      388551       657           fsync
  2.71  154.760989         177    874290     17781 write
  2.19  124.860147          93   1334039         6 nanosleep
  1.76  100.453225      851298       118           wait4
  1.68   95.713610         852    112267       943 openat
  1.54   87.933255        1201     73180         4 epoll_pwait
```

vagrant strace

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 69.97 2422.734157        1409   1718473     91692 futex
 14.13  489.118357     3705442       132        14 waitid
  5.19  179.775257         104   1714057        10 nanosleep
  3.29  113.750410         106   1070528           epoll_pwait
  2.85   98.637672      835912       118           wait4
  1.33   46.026081          42   1083560     91336 write
  1.23   42.696786          37   1139709    271138 read
  0.65   22.621971         165    136532       475 openat
  0.22    7.622616         214     35557     12575 rt_sigreturn
```

one thing that stood out is the amount of time spent on `unmount2` syscall on GCP .

[iostat profile](https://gist.github.com/jespada-bc/c3104b71e6da4dec336d3d8d4daa0b61#gistcomment-3928730) is also quite different in both cases (all those measurements where taken before, during and after the experiment to reproduce the issue)

Its seem indeed that this can be a lower layer IO issue as @zq-david-wang pointed out.

**Comment by aholyoake-bc** [comment]
@zq-david-wang do you have any ideas how we could diagnose this further?

**Comment by trajano** [comment]
I'm having somewhat the same behavior on Swarm with 18 containers.  It's weird as the first part of the container script simply does a few directory manipulations and outputs an env var.  But it takes 5 minutes to even get to show that env var.

**Comment by aholyoake-bc** [comment]
After much searching, we came to the conclusion that increasing the IOPs on our persistent disks provided a work-around for the problem.
The behaviour of the docker daemon of waiting for all images to finish being pulled before starting the first though is still frustrating.

In GCP we ended up attaching local disks to our backends an putting the overlayfs directory in there.
