### ISSUE TITLE
DF shows incorrect disk usage which include disk usage of a mounted path

### ISSUE THREAD

**Issue by pacoxu** [moby/moby#42823]
**Description**
-      DF shows incorrect disk usage which include disk usage of a mounted path

We run a registry with docker and the data dir is mounted from NFS or local disk. The docker is using device mapper.

**Steps to reproduce the issue:**
Not that clear
1.  run container with https://github.com/distribution/distribution and mount the data path to a local path
2. make many agents to pull images
3. run a monitor process to get `df -h` to check the container disk

DF result & du result
When registry is busy pulling images, there is no big files in registry container, but the `df -h` shows 7.8 G as below(Sometime 9G the below screenshot 8.5G)
```
[root@10-23-15-8 ~]# df -h | grep  /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e
/dev/dm-10                10G  7.8G  2.3G   78% /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e
```
The /var/lib/registry/docker is mounted
```
            {
                "Type": "bind",
                "Source": "/var/local/dce/registry",
                "Destination": "/var/lib/registry",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
```
And at the time, I run `du`.
```
[root@10-23-15-8 ~]# du -h /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e | tail -n 1
478M       /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e
```
The du details shows that `df -h` is not correct.
 
**Describe the results you received:**

**Describe the results you expected:**
When it became normal, the disk usage is about 400~500M.
```
[root@10-23-15-8 ~]# df -h | grep  /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e
/dev/dm-10                10G  478M  9.5G    6% /var/lib/docker/devicemapper/mnt/a0ba326c248009e14e9650c84818fdb45af904338bdc90e7d786a584f63ed47e
```
No matter what happened, the `df -h` should not take `mounted path ./var/lib/registry/docker` into account.
 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
We have upgraded a testing env to latest, and it has the same problem

**Output of `docker info`:**

```
Containers: 31
 Running: 21
 Paused: 0
 Stopped: 10
Images: 80
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 72.09 GB
 Data Space Total: 102 GB
 Data Space Available: 29.91 GB
 Metadata Space Used: 11.2 MB
 Metadata Space Total: 109.1 MB
 Metadata Space Available: 97.85 MB
 Thin Pool Minimum Free Space: 10.2 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.170-RHEL7 (2020-03-24)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 0576e6ae91f47a2e5871a0de927a387314828fd3 (expected: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 11.56 GiB
Name: 10-23-15-8
ID: DG2S:NOCP:W4GX:3CVL:BJWU:URIL:MQJK:KX2G:E2DA:TNP2:RITQ:JYEO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: gssjl2008
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I searched in stackoverflow and other place and only find some issues about `df and du show different` problem. I am not sure which is my case. Thanks.

**Comment by pacoxu** [comment]
I think this would be `df` bug of kernel. We may test with newer kernel later.

**Comment by thaJeztah** [comment]
Yes, this doesn't look like a bug in Docker; that's the default behavior of `df`. You can pass it some options to exclude mounted filesystems though; `df --local` should only report local filesystems, or `-x` allows you to exclude specific filesystem types. https://linuxcommand.org/lc3_man_pages/df1.html


That said, I see you're running docker 17.03, which is _really_ old by now, and reached EOL 4 years ago. If possible, I'd highly recommend updating to a more current version, because those old versions are no longer maintainer, and have known vulnerabilities (some of which may be _critical_.

Closing this ticket because of the above, but feel free to continue the conversation

**Comment by pacoxu** [comment]
Thanks for the information.
