### ISSUE TITLE
dockerd daemon exit unexpectly  with receive a terminated signal from systemd

### ISSUE THREAD

**Issue by zvier** [moby/moby#42820]
**Description**
Dockerd daemon exit unexpectly with  receive a terminated signal from systemd.  Other components such as kubelet, containerd was worked normal. If start dockerd use binary directly can worked well all the time. I think the problem is why the systemd send a terminated signal to dockerd, but no related information found. The exit log is:
```
...
systemd[1]: Stopping Docker Application Container Engine...
dockerd[2076433]: time="2021-09-04T10:10:54.900662868+08:00" level=info msg="Processing signal 'terminated'"
dockerd[2076433]: time="2021-09-04T10:10:54.901936633+08:00" level=info msg="Daemon shutdown complete"
```

And the docker.service content is:
```
cat /usr/lib/systemd/system/docker.service

[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket containerd.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# Both the old, and new location are accepted by systemd 229 and up, so using the old location
# to make them work for either version of systemd.
StartLimitBurst=3

# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# this option work for either version of systemd.
StartLimitInterval=60s

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Comment TasksMax if your systemd version does not support it.
# Only systemd 226 and above support this option.
TasksMax=infinity

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
```

**docker version**
20.10.1

**Comment by thaJeztah** [comment]
The `Processing signal 'terminated'` message comes from;
https://github.com/moby/moby/blob/9a6ff685a80639995311c0572d662360b55796d9/cmd/dockerd/trap/trap.go#L40

And signal corresponds with `SIGTERM`; 

- https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/syscall/zerrors_linux_amd64.go#L1366
- https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/syscall/zerrors_linux_amd64.go#L1531


>  I think the problem is why the systemd send a terminated signal to dockerd, but no related information found. 

Not sure what would trigger that. For sure that's not something the docker daemon would control. It could be that some other service that the docker service depends on shut down, in which case I'd expect systemd to shut down the docker service as well.


From the above, I don't think this is a bug in docker, so I'll go ahead and close this ticket, but feel free to continue the conversation
