### ISSUE TITLE
Improvement of namesgenerator package randomizing

### ISSUE THREAD

**Issue by ngopher** [moby/moby#42839]
**Description**
I was reviewing the code-base and I found something that could be developed better. Although there were some comments on codes, but they have not got fixed yet and I like to do them.

**Steps to reproduce the issue:**
1. Using crypto/rand instead of math/rand in namesgenerator package.
2. Using a different package name for the test files (packageName_test) to import  the source package name.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ngopher** [comment]
Issues resolved

**Comment by thaJeztah** [comment]
closing per https://github.com/moby/moby/pull/42841#issuecomment-921184928
