### ISSUE TITLE
client.ContainerRemove() unable to process ContainerRemoveOptions

### ISSUE THREAD

**Issue by NupurThakur27** [moby/moby#42850]
**Description**

**Steps to reproduce the issue:**
func stopAndRemoveContainer(client *client.Client, containername string) error {
	ctx := context.Background()

	if err := client.ContainerStop(ctx, containername, nil); err != nil {
		log.Printf("Unable to stop container %s: %s", containername, err)
	}
	removeOptions := types.ContainerRemoveOptions{
		RemoveVolumes: true,
		Force:         true,
	}

	if err := client.ContainerRemove(ctx, containername, removeOptions); err != nil {
		log.Printf("Unable to remove container: %s", err)
		return err
	}

	return nil
}
**Describe the results you received:**
```
cannot use removeOptions (type "github.com/moby/moby/api/types".ContainerRemoveOptions) as type "github.com/docker/docker/api/types".ContainerRemoveOptions in argument to client.ContainerRemove
```

It is showing me the error for `client.ContainerRemove()` specifically `removeOptions`
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 100
  Running: 1
  Paused: 0
  Stopped: 99
 Images: 218
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-27-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: nupur-Latitude-E7250
 ID: XSZO:4YEQ:MYUQ:RPI6:EOHH:W3IB:4W6P:4EDV:VWW4:Q34V:4YZN:D3O6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nupurthakur27
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
You need to import the package as `github.com/docker/docker/xxx`. The repository was renamed to moby/moby, but the packages provided are still named `docker/docker`.


This doesn't look like a bug, so I'll close this ticket for housekeeping, but feel free to continue the conversation after I closed the ticket

**Comment by NupurThakur27** [comment]
Thanks @thaJeztah for replying. But I am a bit confused between `github.com/moby/moby` and `github.com/docker/docker` should every package that I use be like `github.com/docker/docker/xxx` instead of `github.com/moby/moby/xxx`.

As for now, to resolve the issue I have only replaced it for `github.com/docker/docker/api/types` 
But other packages are still like `github.com/moby/moby/client` etc.

**Comment by thaJeztah** [comment]
All packages from this repository should currently be imported as `github.com/docker/docker/**`.

**Comment by NupurThakur27** [comment]
Okay Thanks @thaJeztah
