### ISSUE TITLE
The exponential backoff restart algorith does not increase indefinitely as the documentation suggests

### ISSUE THREAD

**Issue by christidis** [moby/moby#42873]
**Description**

I had an incident with an increased load to a system due to many `ifquery` processes that were caused by hundreds of restarting containers. Looking into the issue I found out that the exponential backoff algorith does not behave the same way like it used to be some years ago. When restarting containers could reach days since their last restart attempt if they were left unmanaged due to the never ending backoff algorithm.

**Steps to reproduce the issue:**
1. Simulate a restarting container ```docker run -d --name=testrestart --entrypoint=false --restart=always busybox```
2. Watch how often the exponential backoff algorith restarts the container ```watch "docker ps -a -f name=testrestart"```

**Describe the results you received:**

The restarts in Docker 18 (tested with `18.09.8`) and Docker 20 (tested with `20.10.7`) increase up to 1 minute. then the restarts are done every minute.
The restarts in Docker 17 (tested with `17.03.1-ce`) increase indefinitely.

**Describe the results you expected:**
According to the `docker run` documentation there is _an ever increasing delay to prevent flooding the server_.

https://docs.docker.com/engine/reference/run/#restart-policies---restart
> An ever increasing delay (double the previous delay, starting at 100 milliseconds) is added before each restart to prevent flooding the server. This means the daemon will wait for 100 ms, then 200 ms, 400, 800, 1600, and so on until either the on-failure limit is hit, or when you docker stop or docker rm -f the container.

So, either the documentation is outdated as there is no such thing like _an ever increasing delay_ anymore, or Docker 18+ 20+ have a bug in their exponential backoff restart algorith.

It would be nice to have an option for controlling the maximum restart delay setting.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 40
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.1-051401-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.01GiB
 Name: dev011
 ID: JKHI:UUHE:PLZ2:IL6M:EET2:Q6HS:23OB:WM6R:LOZV:SRXY:IIAW:4UPK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical node.

**Comment by thaJeztah** [comment]
Looks like this changed indeed in Docker 17.04 and up (through https://github.com/moby/moby/pull/30683, to address https://github.com/moby/moby/issues/30503), but the documentation was not updated accordingly.

> It would be nice to have an option for controlling the maximum restart delay setting.

I see that was discussed in the linked issue, and (at least at that time), it was decided to not make it configurable (the main intent of the incremental backoff is to prevent a failing container from causing a (too fast) crash-loop); trying "once a minute" for temporary failures seemed like a reasonable middle-ground, but if you have a specific use-case, feel free to leave a comment.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3306 to address the docs (will need a cherry-pick to have it published at docs.docker.com after that's merged)
