### ISSUE TITLE
Can't add file to tar: archive/tar: write too long

### ISSUE THREAD

**Issue by LLLLLBJ** [moby/moby#42884]
https://github.com/moby/moby/blob/b9c26a56a336e2fa029d9b21acf97c11b3bca7a9/pkg/archive/archive.go#L932

I call docker API to build a image, then I get this error in log and build an incomplete image:
time="2021-09-25T03:35:40Z" level=error msg="Can't add file /workspace/test.img to tar: archive/tar: write too long"

I think error occurs in tar but not returned
archive.TarWithOptions(myWorkspace, &archive.TarOptions{})

Could the tar error be returned?

**Comment by LLLLLBJ** [comment]
I guess this "write too long" error is caused by my fault, the file in tar is modified when I build the image.

**Comment by thaJeztah** [comment]
Looks like it was resolved, so let me go ahead and close (but let me know if I closed by mistake)
