### ISSUE TITLE
OnlyOffice Container not starting at all (`bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.`)

### ISSUE THREAD

**Issue by BentiGorlich** [moby/moby#42909]
**Description**

I try to start the onlyoffice documentserver with the following command:
```
sudo docker run -i -t -d -p 8002:443 --restart=always -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
```
I get the error message: 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.
```

It did work fine a few weeks ago, then I decided to make a complete update of my system with `sudo apt-get update`, `sudo apt-get upgrade`. After that I got the mentioned error message.
**Steps to reproduce the issue:**
I really don't know. Maybe try to run my command in docker

**Describe the results you received:**
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.`

**Describe the results you expected:**
Docker starting the container

**Additional information you deem important (e.g. issue happens only occasionally):**
everytime I try to run the command

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:42 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 83
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux bookworm/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: benni-nuc
 ID: X7IR:S4XC:K2SG:4J7V:HDXX:2JM5:57IR:UZAE:NXO3:OCIU:JIQF:FDEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpuset support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
Is this specific to OnlyOffice container? Does `docker run hello-world` work?

**Comment by BentiGorlich** [comment]
When I try to run hello world i get this output:
```
sudo docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by AkihiroSuda** [comment]
> Does anyone have additional information? I tried grading down the packages `docker-ce` and `docker-ce-cli` to version `5:19.03.15~3-0~debian-buster` and I get the exact same error message with the `hello-world` package

Docker 19.03 isn't compatible with cgroup v2.
Downgrading cgroup to v1 may work as a workaround. (Append `systemd.unified_cgroup_hierarchy=0` to kernel cmdline)

**Comment by thaJeztah** [comment]
`sid` is the codename for Debian's unstable releases (see https://www.debian.org/releases/sid/ and https://wiki.debian.org/DebianUnstable). It's named `sid` after a character in Toy Story that's known to break things all the time;

> As with all Debian release names, Sid takes its name from a ToyStory character. In the movie, Sid is the kid next door who breaks his toys and makes nasty creatures of them.
...

> sid is subject to massive changes and in-place library updates. This can result in a very unstable system which contains packages that cannot be installed due to missing libraries, dependencies that cannot be fulfilled etc. Use it at your own risk!


> The thing is, that I don't have `cgroup` installed, at least when I try to uninstall it:

Cgroups are not a package, it's a kernel feature; https://en.wikipedia.org/wiki/Cgroups

**Comment by BentiGorlich** [comment]
ok, and how do I change it to use a more stable branch of releases? Do I have to do a fresh install? (I hope not) Or do I just change my apt sources?

**Comment by BentiGorlich** [comment]
Can anyone help me with that?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
