### ISSUE TITLE
/var/run/docker.sock refused connection

### ISSUE THREAD

**Issue by zvier** [moby/moby#42920]
**Description**

When dockerd running a period of time and is still running, the /var/run/docker.sock may refused all connections.

```
docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
curl -XGET --unix-socket /var/run/docker.sock http://localhost/_ping
curl: (7) Failed to connect to /var/run/docker.sock: Connection refused
```

```
nc -U /var/run/docker.sock
Ncat: Connection refused.
```

But the dockerd process is still running now and the docker.sock file is LISTENED by dockerd
```
lsof /var/run/docker.sock
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF       NODE NAME
dockerd 262960 root    8u  unix 0x00000000756f1a90      0t0 2506817999 /var/run/docker.sock
```

And the metrics.sock is noraml.
```
nc -U /var/run/docker/metrics.sock
```
 

**Steps to reproduce the issue:**
Not found stable reproduce method.

**Describe the results you received:**
/var/run/docker.sock  refused connection

**Describe the results you expected:**
/var/run/docker.sock can worked noramlly all time if dockerd is running.

**Output of `docker version`:**

Almost all version has this problem. May be dockerd has some pressure or host abnormal? But we not found yet.

**Comment by thaJeztah** [comment]
closing, as this went stale
