### ISSUE TITLE
Error: error creating container storage: parsing named reference 

### ISSUE THREAD

**Issue by Avijit009** [moby/moby#42927]
System using:
Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

Docker: Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2

I was trying to migrate containers using podman but encounter the below problem.

`Error: error creating container storage: parsing named reference "d54056386fbb1ea69f9332f35ab083dd7062cc9cb78ed28ce6b8f85e9dfb56b3": invalid repository name (d54056386fbb1ea69f9332f35ab083dd7062cc9cb78ed28ce6b8f85e9dfb56b3), cannot specify 64-byte hexadecimal strings`

Is there any solution for this?

**Comment by Avijit009** [comment]
@AkihiroSuda  Ok, I will fill that.

I have not got your point; means what moby is?

In my case, I am using two VM (installed on KVM/QEMU), namely, client and server, on the same machine. 
So, in that case, what should be podman to moby or moby to podman?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
