### ISSUE TITLE
How to turn off the log color mark output by stdout？

### ISSUE THREAD

**Issue by wajika** [moby/moby#43003]
![微信截图_20211109161600](https://user-images.githubusercontent.com/17058349/140887115-a15d322b-211e-4727-8776-9ef7caecb2db.png)
I used filebeat to collect the logs output by container stdout, but why are the logs marked with colors? This makes the log structure very messy, is there any way to turn off the color mark?

**Comment by AkihiroSuda** [comment]
Unrelated to this repo
