### ISSUE TITLE
Longer time to create service on the system with more powerful CPU, with identical settings 

### ISSUE THREAD

**Issue by yy8402** [moby/moby#43014]
I had expected docker service would be created faster with more powerful CPU, but the fact is just the opposite: it takes much longer time to crate a service on VM with more powerful CPU. 

Docker CE 20.10 are running on two VMs, both with freshly installed AlmaLinux 8.4 on 8 cores 16GB mem. The two VMs are each on a Dell R630 server with Xeon E5-2678 v3 @ 2.50GHz and Xeon E5-2680 v4 @ 2.40GHz respectively. 

On the VM with more powerful CPU (Xeon E5-2680 v4, marked by 251), it takes 7+s to successfully create a service; while on the VM with Xeon E5-2678 v3 (marked by 90), it only takes ~1s. On both VMs, docker is running in swarm mode, and I used a local repository running on the same machine.

Moreover, I had even tried on a bare-metal Dell R630 server with dual Xeon E5-2680 v4 and 64 GB memory, it takes even longer with the same OS and docker settings.

I have all detailed information (cpu, memory, kernel, etc.) about the two VMs and the strace log when creating a service attached, any suggestion or clue to further debug will be very much appreciated.

**docker version**
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:56 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**docker info**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 37
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ohnlybgnncl4jd0lz0wb1hd0g
  Is Manager: true
  ClusterID: i3qiy18ljl3d2tlq8xxpszvnu
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.90
  Manager Addresses:
   192.168.0.90:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-305.el8.x86_64
 Operating System: AlmaLinux 8.4 (Electric Cheetah)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.46GiB
 Name: Alma90
 ID: LSYK:3GIW:UH2O:F37M:P66H:PXBW:BZ3J:YS47:5H44:54WS:FOH6:I3L2
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 48
  Goroutines: 163
  System Time: 2021-11-13T15:22:17.819185838+08:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  SupraRegistry:5000
  127.0.0.0/8
 Live Restore Enabled: false

[docker-90.txt](https://github.com/moby/moby/files/7531811/docker-90.txt)
[strace-90.log](https://github.com/moby/moby/files/7531812/trace-90.log)
[docker-251.txt](https://github.com/moby/moby/files/7531810/docker-251.txt)
[strace-251.log](https://github.com/moby/moby/files/7531813/trace-251.log)

**Comment by yy8402** [comment]
I got further information from journalct...

"sandbox set key processing took" several **seconds** on Machine 251, while only 100~200 **ms** on Machine 90. 

This should be the direct cause, but why "sandbox set key processing" acts so differently on the two almost identical VM's? How can I address this? Can anyone shed some light? Thanks!

**Comment by yy8402** [comment]
Well, I reinstalled the OS and the problem disappeared...

**Comment by thaJeztah** [comment]
Looks like the issue was resolved, so let me go ahead and close
