### ISSUE TITLE
build a development environment image fail (`chmod is not supported: requested prerelease feature file.base is not supported by build server, please update`)

### ISSUE THREAD

**Issue by bolinlee** [moby/moby#43038]
**Description**

I follow the document software-required.md , set-up-git.md and set-up-dev-env.md to set up a development environmen in centos7.  But i encounter a problem when a perform the command "make BIND_DIR=. shell", the error details as below:

[root@ct moby]# make BIND_DIR=. shell
: invalid optiont-daemon-osarch: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
hack/make/.detect-daemon-osarch: line 3: $'\r': command not found
hack/make/.detect-daemon-osarch: line 4: syntax error near unexpected token `$'{\r''
'ack/make/.detect-daemon-osarch: line 4: `docker-version-osarch() {
: invalid optiont-daemon-osarch: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
hack/make/.detect-daemon-osarch: line 3: $'\r': command not found
hack/make/.detect-daemon-osarch: line 4: syntax error near unexpected token `$'{\r''
'ack/make/.detect-daemon-osarch: line 4: `docker-version-osarch() {
docker build  --build-arg=GO_VERSION  -f "" --target=dev   -t "docker-dev" .
[+] Building 5.9s (10/10) FINISHED
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 153B                                                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                                                   0.1s
 => => transferring dockerfile: 17.99kB                                                                                                                                0.0s
 => resolve image config for docker.io/docker/dockerfile:1.3                                                                                                           2.9s
 => CACHED docker-image://docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 17.99kB                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/djs55/vpnkit:0.5.0                                                                                                          1.1s
 => [internal] load metadata for docker.io/djs55/vpnkit:0.5.0                                                                                                          1.1s
 => [internal] load metadata for docker.io/library/debian:bullseye                                                                                                     1.3s
 => [internal] load metadata for docker.io/library/golang:1.17.3-bullseye                                                                                              1.5s
rpc error: code = Unknown desc = chmod is not supported: requested prerelease feature file.base  is not supported by build server, please update
make: *** [build] Error 1

**Steps to reproduce the issue:**
1. Change into the root of the `moby-fork` repository.
2. And change to dry-run-test` branch
3. perform the "make BIND_DIR=. shell" command to build a development environment image and run it in a container

**Describe the results you received:**

I expect the command executed successfully, A development environment image is builded , and I can run it in a container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.93GiB
Name: ct
ID: DDS2:CQFP:MNEK:WKMI:L7B6:T762:SABZ:PA67:YHQ4:WGRO:EN5M:NEKB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://www-proxy.test.se:8080
HTTPS Proxy: http://www-proxy.test.se:8080
No Proxy: localhost,127.0.0.1,docker-registry.example.com,.corp
Username: bolinlee
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The centos linux is run in VirtualBox!

**Comment by AkihiroSuda** [comment]
>  Version:          18.09.5

Please update to 20.10
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/

**Comment by bolinlee** [comment]
Thanks AkihiroSuda for reply, I will try it out now.

**Comment by bolinlee** [comment]
Hi, AkihiroSuda
   I have update docker to 20.10, below are the detail:
Output of docker version:
"""
[root@ct ~]# docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:38:53 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:37:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
"""

Output of docker info:
"""
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.10.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.93GiB
 Name: ct
 ID: DDS2:CQFP:MNEK:WKMI:L7B6:T762:SABZ:PA67:YHQ4:WGRO:EN5M:NEKB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://www-proxy.test.se:8080
 HTTPS Proxy: http://www-proxy.test.se:8080
 No Proxy: localhost,127.0.0.1,docker-registry.example.com,.corp
 Username: bolinlee
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
"""


But when i reperform the command "make BIND_DIR=. shell" , I encounter another problem as below:
"""
[root@ct moby]# make BIND_DIR=. shell
: invalid optiont-daemon-osarch: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
hack/make/.detect-daemon-osarch: line 3: $'\r': command not found
hack/make/.detect-daemon-osarch: line 4: syntax error near unexpected token `$'{\r''
'ack/make/.detect-daemon-osarch: line 4: `docker-version-osarch() {
: invalid optiont-daemon-osarch: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
hack/make/.detect-daemon-osarch: line 3: $'\r': command not found
hack/make/.detect-daemon-osarch: line 4: syntax error near unexpected token `$'{\r''
'ack/make/.detect-daemon-osarch: line 4: `docker-version-osarch() {
docker build  --build-arg=GO_VERSION  -f "" --target=dev   -t "docker-dev" .
[+] Building 121.8s (43/78)
 => [internal] load build definition from Dockerfile                                                                                                                   0.1s
 => => transferring dockerfile: 17.99kB                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 153B                                                                                                                                      0.0s
 => resolve image config for docker.io/docker/dockerfile:1.3                                                                                                           9.6s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                                       0.0s
 => docker-image://docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2                                             4.0s
 => => resolve docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2                                                 0.0s
 => => sha256:93f32bd6dd9004897fed4703191f48924975081860667932a4df35ba567d7426 528B / 528B                                                                             0.0s
 => => sha256:e532695ddd93ca7c85a816c67afdb352e91052fab7ac19a675088f80915779a7 1.21kB / 1.21kB                                                                         0.0s
 => => sha256:24a639a53085eb680e1d11618ac62f3977a3926fedf5b8471ace519b8c778030 9.67MB / 9.67MB                                                                         3.1s
 => => sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2 2.00kB / 2.00kB
....
 => => extracting sha256:647acf3d48c2780e00cd27bb0984367415f270d78477ef9d5b238e6ebd5290da                                                                             88.8s
 => [vpnkit 1/2] COPY --from=vpnkit-amd64 /vpnkit /build/vpnkit.x86_64                                                                                                 0.2s
 => [vpnkit 2/2] COPY --from=vpnkit-arm64 /vpnkit /build/vpnkit.aarch64                                                                                                0.3s
 => CANCELED [frozen-images 2/4] RUN --mount=type=cache,sharing=locked,id=moby-frozen-images-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locked,id=mob  81.4s
 => [base 2/3] RUN echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache                                                          1.6s
 => [base 3/3] RUN sed -ri "s/(httpredir|deb).debian.org/${APT_MIRROR:-deb.debian.org}/g" /etc/apt/sources.list  && sed -ri "s/(security).debian.org/${APT_MIRROR:-se  0.8s
 => CANCELED [shfmt 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         GOBIN=/build/ GO111MODULE=on go insta  16.9s
 => [criu 1/2] ADD --chmod=0644 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_11/Release.key /etc/apt/trusted.gpg.d/criu.gpg.asc                0.2s
 => [rootlesskit 1/4] COPY /hack/dockerfile/install/install.sh /hack/dockerfile/install/rootlesskit.installer /                                                        0.3s
 => CANCELED [vndr 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         GOBIN=/build/ GO111MODULE=on go instal  17.0s
 => [dockercli 1/2] COPY /hack/dockerfile/install/install.sh /hack/dockerfile/install/dockercli.installer /                                                            0.2s
 => [swagger 1/2] WORKDIR /go/src/github.com/go-swagger/go-swagger                                                                                                     0.1s
 => CANCELED [tini 1/3] RUN --mount=type=cache,sharing=locked,id=moby-tini-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locked,id=moby-tini-aptcache,ta  17.0s
 => CANCELED [runtime-dev-cross-false 1/1] RUN --mount=type=cache,sharing=locked,id=moby-cross-false-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locke  17.0s
 => CANCELED [golangci_lint 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         GOBIN=/build/ GO111MODULE=on   16.9s
 => CANCELED [gotestsum 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         GOBIN=/build/ GO111MODULE=on go i  16.9s
 => CANCELED [containerd 1/3] RUN --mount=type=cache,sharing=locked,id=moby-containerd-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locked,id=moby-cont  16.9s
 => [registry 1/2] WORKDIR /go/src/github.com/docker/distribution                                                                                                      0.2s
 => CANCELED [tomll 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         GOBIN=/build/ GO111MODULE=on go insta  16.9s
 => CANCELED [swagger 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=tmpfs,target=/go/src/       16.3s
 => CANCELED [criu 2/2] RUN --mount=type=cache,sharing=locked,id=moby-criu-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locked,id=moby-criu-aptcache,ta  16.8s
 => ERROR [dockercli 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         PREFIX=/build /install.sh dockercli   15.9s
 => CANCELED [registry 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=tmpfs,target=/go/src/      16.7s
 => ERROR [rootlesskit 2/4] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         /install.sh rootlesskit      && "/  16.1s
------
 > [dockercli 2/2] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         PREFIX=/build /install.sh dockercli:
#30 15.76 /bin/sh: 1: /install.sh: not found
------
------
 > [rootlesskit 2/4] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         /install.sh rootlesskit      && "/build"/rootlesskit --version      && "/build"/rootlesskit-docker-proxy --help:
#69 16.05 /bin/sh: 1: /install.sh: not found
------
executor failed running [/bin/sh -c /install.sh rootlesskit      && "${PREFIX}"/rootlesskit --version      && "${PREFIX}"/rootlesskit-docker-proxy --help]: exit code: 127
make: *** [build] Error 1
"""


Please help me have a look at it again, thanks!

**Comment by thaJeztah** [comment]
Are you building from a clean state of the repository? What commit are you building from?

**Comment by bolinlee** [comment]
Yes, I build from a clean state of the repository, repository detail info as below:

"""
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
"""

and I build from the commit:
"""
commit ea0f3dc8f4466e456b74a079a3038bbf4e25e57e (HEAD -> master, origin/master, origin/HEAD)
Merge: f06314fa84 6d92d2c7c4
Author: Sebastiaan van Stijn <thaJeztah@users.noreply.github.com>
Date:   Fri Nov 19 13:39:01 2021 +0100

    Merge pull request #43031 from thaJeztah/fix_TestConntrackFlowsLeak_v1

    TestConntrackFlowsLeak: use busybox "nc"
"""

**Comment by thaJeztah** [comment]
Sorry for my late reply; are you still running into this issue? The only thing I _could_ think of is if your local git checkout has (e.g.) wrong line endings in those scripts (CRLF instead of LF), which could trigger odd "not found" errors. Also make sure to clean the build cache, in case some corrupted cache was left over from the old docker engine version. (you can run `docker system prune`)

I don't expect this to be a bug in the current version of docker, but possibly something in your environment, so I'll go ahead and close this ticket for housekeeping, but feel free to continue the conversation if you're still having issues
