### ISSUE TITLE
Running `ldconfig` (from `libc-bin` package) segfaults on arm64v8 (Debian) using `qemu-user-static` on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by amotl** [moby/moby#43039]
Hi there,

first things first: Thanks a stack to all people working on Docker and its ecosystem. We have been redirected here from https://github.com/docker/docker and dearly hope this is the right place to report our observations. Otherwise, please let us know where to direct this report better.

With kind regards,
Andreas.

**Description**

We are ramping up a new build machine with an AMD Ryzen 5 3600 (Zen2) CPU, aiming to build Docker images for [Kotori](https://github.com/daq-tools/kotori) for different architectures (amd64, arm64v8 and arm32v7), which works perfectly on our macOS workstation.

At https://github.com/daq-tools/kotori/issues/73, we reported some observations about an issue with the canonical Docker image `arm64v8/debian:bullseye-slim`, which we use as a baseline image. On the new machine, we are running Docker 20.10.11 on Linux kernel 5.4.0-77 (vanilla Ubuntu 20.04.3 LTS).

On this machine, while operating on the baseline image for amd64 and arm32v7 works, the operation on arm64v8 fails at one specific place, namely when, in Debian jargon, reconfiguring the package `libc-bin`, with a segfault.

**Steps to reproduce the issue:**
1. Install Docker
2. Install packages to support multiarch builds: `apt-get install qemu-user-static binfmt-support`
3. Invoke `docker run`:
   ```shell
   docker run --pull --rm -it --env DEBIAN_FRONTEND=noninteractive arm64v8/debian:bullseye-slim dpkg-reconfigure libc-bin  && echo OK
   ```

**Describe the results you received:**
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

**Describe the results you expected:**
No error, but `OK` to be printed.

It works when running it on arm32v7:
```shell
docker run --pull --rm -it --env DEBIAN_FRONTEND=noninteractive arm32v7/debian:bullseye-slim dpkg-reconfigure libc-bin && echo OK
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 15
  Running: 0
  Paused: 0
  Stopped: 15
 Images: 70
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.81GiB
 Name: trillian
 ID: T6N5:D7XU:XR5R:PPHC:TTI5:EYQ3:TU6T:OIOV:MNS6:QX4B:JRNM:XFBB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```shell
neofetch --stdout
```
```
root@trillian
-------------
OS: Ubuntu 20.04.3 LTS x86_64
Host: 1.0
Kernel: 5.4.0-77-generic
Uptime: 2 days, 19 hours, 55 mins
Packages: 442 (dpkg)
Shell: bash 5.0.17
Terminal: /dev/pts/0
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
Memory: 440MiB / 64314MiB
```

**Comment by amotl** [comment]
We have been able to narrow this down to the invocation of `ldconfig`.

### `arm64v8`
```shell
$ docker run --pull --rm -it arm64v8/debian:bullseye-slim /bin/sh -c "ldconfig --version"

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

### `arm32v7`
```shell
$ docker run --pull --rm -it arm32v7/debian:bullseye-slim /bin/sh -c "ldconfig --version"

ldconfig (Debian GLIBC 2.31-13+deb11u2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Andreas Jaeger.
```

**Comment by amotl** [comment]
Hi again,

we believe this is not related to Docker at all, so sorry for the noise. By following the discussion at [1], and using a more recent version of `qemu-aarch64-static` by manually installing a more recent `qemu-user-static` package [2], things start working smoothly again.

```shell
$ qemu-aarch64-static --version

qemu-aarch64 version 5.0.0 (Debian 1:5.0-5ubuntu9.9)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

```shell
$ docker run --pull --rm -it arm64v8/debian:bullseye-slim /bin/sh -c "ldconfig --version"

ldconfig (Debian GLIBC 2.31-13+deb11u2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Andreas Jaeger.
```

With kind regards,
Andreas.

[1] https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1791531.html
[2] http://security.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_5.0-5ubuntu9.9_amd64.deb

**Comment by amotl** [comment]
Others are also confirming that this has been resolved with Qemu 5, see [3].

[3] https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1928075/comments/15

**Comment by thaJeztah** [comment]
Thanks for the update; glad to hear it's resolved 👍
