### ISSUE TITLE
docker cp does not copy from hidden files

### ISSUE THREAD

**Issue by auwsom** [moby/moby#43048]
I'm not getting dot prefixed directories copied into a container.
https://github.com/moby/moby/issues/5410

Possibly also:
https://github.com/GoogleContainerTools/kaniko/issues/316

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.


I did a quick test, but was not able to see any issues;

```bash
mkdir repro-43048 && cd repro-43048
mkdir -p foo/.hidden-dir
touch foo/.hidden-file foo/.hidden-dir/.hidden-file2

docker build -t foo . -f-<<EOF
FROM alpine
COPY foo foo
EOF

docker run --rm foo sh -c 'ls -la /foo; ls -la /foo/.hidden-dir'
total 12
drwxr-xr-x    3 root     root          4096 Nov 29 09:12 .
drwxr-xr-x    1 root     root          4096 Nov 29 09:16 ..
drwxr-xr-x    2 root     root          4096 Nov 29 09:12 .hidden-dir
-rw-r--r--    1 root     root             0 Nov 29 09:10 .hidden-file
total 8
drwxr-xr-x    2 root     root          4096 Nov 29 09:12 .
drwxr-xr-x    3 root     root          4096 Nov 29 09:12 ..
-rw-r--r--    1 root     root             0 Nov 29 09:10 .hidden-file2



mkdir output

docker create --name testcontainer foo
docker cp testcontainer:/foo/.hidden-dir/.hidden-file2 output/
ls -la output/
total 0
drwxr-xr-x    3 sebastiaan  staff    96 Nov 29 10:17 .
drwxr-xr-x  269 sebastiaan  staff  8608 Nov 29 10:17 ..
-rw-r--r--    1 sebastiaan  staff     0 Nov 29 10:10 .hidden-file2
```

**Comment by auwsom** [comment]
@thaJeztah Yes, apologies. A standard bash alias for ls (-la) was different in the container I was using. The other issue wasn't formally resolved, so I thought is was worth asking again. Thanks for confirmation it's working.
