### ISSUE TITLE
Default http Go client connection has infinite timeout

### ISSUE THREAD

**Issue by colinfindlay-nz** [moby/moby#43071]
https://github.com/moby/moby/blob/847da184ad5048b27f5bdf9d53d070f731b43180/client/client.go#L165

In certain circumstances, Docker plugins that utilise the Go client can permanently disable Docker from starting. In the instance that a plugin is used within a container with auto-start enabled, the container, and thus the plugin may launch before the Docker router is ready. 
The infinite timeout will block the plugin, which will, in turn, block the container, which seems to then block the API router from coming up... resulting in a fully hung `dockerd`, and no way to interact via the docker client to disable the container or plugin 😢 
A quick solution would be a default timeout - of any length. A better solution would allow configuration of the timeout via `NewClientWithOpts` as well.
An example plugin issue is logged here:
https://github.com/devplayer0/docker-net-dhcp/issues/23

**Comment by colinfindlay-nz** [comment]
I completely missed that! Thank you.

I would still think a sensible default should apply, as the result is a
broken system.

**Comment by cpuguy83** [comment]
@colinfindlay-nz Best thing to do here is to set the timeout in your contexts you pass to client functions. I do not think changing go's default http client timeout is desirable since there is no single value that's a good timeout for everyone, which is why the default http client does not timeout.

**Comment by colinfindlay-nz** [comment]
I would agree if you were writing an HTTP client, but in the context of
writing a Docker client I think a reasonable timeout should straight
forward.

**Comment by cpuguy83** [comment]
It's not straight forward in any way. Every system and setup is different, and clients are not necessarily local to the machine.

**Comment by colinfindlay-nz** [comment]
If you strongly believe that clients that do not set a timeout should be
able to cause a catastrophic failure of the host system, because choosing a
number is "not going to suit everyone", then I am more than happy for this
issue to be closed.

**Comment by colinfindlay-nz** [comment]
Up to client implementation to ensure they don't break everything by using the defaults.

**Comment by x1unix** [comment]
`WithTimeout` breaks `.Events()` method that relies on long polling and will return a timeout error after timeout elapsed.
