### ISSUE TITLE
Issue with multicraft server crashing upon startup, gives these errors

### ISSUE THREAD

**Issue by MorbidMix** [moby/moby#43070]
This is the chain that the console throws out, its the same every time and seems to be stuck in a restart loop.

[Multicraft] Server shut down (starting)
08.12 00:28:01 [Multicraft] Restarting crashed server in 10 seconds
08.12 00:28:01 [Multicraft] Looks like a crash, check the server console. Return value: 137
08.12 00:28:01 [Multicraft] Server stopped
08.12 00:28:11 [Multicraft] Loading server properties
08.12 00:28:11 [Multicraft] Starting server!
08.12 00:28:11 [Multicraft] Loaded config for "AUTO UPDATING: Spigot Latest (Current: )"
08.12 00:28:12 [Multicraft] JAR file not found, copying from global JAR directory
08.12 00:28:13 [Multicraft] Updating eula.txt file
08.12 00:28:13 [Server] INFO WARNING: Error loading config file: .dockercfg: $HOME is not defined
08.12 00:28:13 [Server] INFO WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
08.12 00:28:14 [Server] INFO Unbundling libraries to /bundler
08.12 00:28:14 [Server] INFO Starting server

running 1.18 on spigot, no mods/plugins installed currently.

**Comment by AkihiroSuda** [comment]
Doesn't seem related to this repo
