### ISSUE TITLE
Pushing large images failing with "file already closed"

### ISSUE THREAD

**Issue by amokkara** [moby/moby#43089]
**Description**

**Steps to reproduce the issue:**
1. pushing large docker image on my windows machine with docker desktop running
2. 
3. 

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/91867833/146427345-28595dec-3536-4600-b531-d36a462a1144.png)

**Describe the results you expected:**
expected image to be completly pushed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sam-thibault** [comment]
I don't see any updates or new info for this issue so I will close it for now.
