### ISSUE TITLE
"docker info" reports a Deprecated Registry Configured

### ISSUE THREAD

**Issue by f1linux** [moby/moby#43091]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

In `docker info` for Docker CE v 20.10.11 using the "Stable" channel reports : 

"Registry: https://index.docker.io/v1/"

However in this [Docker blogpost](https://www.docker.com/blog/registry-v1-api-deprecation/), they report that the v1 Registry was deprecated as of June 1, 2019.

Investigated on Stack Exchange and see people with the same confusion [asking how this can be changed](https://stackoverflow.com/questions/62632798/change-the-registry-in-the-docker-https-index-docker-io-v1-to-v2) to 

"https://index.docker.io/v2/"

Although there is no command to show what repo an image was pulled from, by doing a `docker pull` I can see images are coming from `docker.io/repo/tag`. However, once pulled, there's no way to determine the provenance of any particular image- another thing I see lots of folks on Stack trying to figure out.

**Steps to reproduce the issue:**
Execute `docker info` and review the value of "Registry".

**Describe the results you received:**

"Registry: https://index.docker.io/v1/"

**Describe the results you expected:**

"Registry: https://index.docker.io/v2/"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
ubuntu@pi4host1:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:35:56 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:34:31 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
ubuntu@pi4host1:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: syslog
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1047-raspi
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.628GiB
 Name: pi4host1.f1linux.com
 ID: HTZQ:DKKH:WGT4:YO6Q:UEBX:6CQT:6MB4:SIGU:TV7D:WBRA:H3G3:UNCY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.X.0/24, Size: 28
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker is installed on Raspberry Pi 4's , each with 8GB memory and running Ubuntu 20.04 LTS for ARM64/v8

**Comment by thaJeztah** [comment]
Thanks for reporting; this information is for historic reasons, and only used for the Docker Hub authentication endpoint (which was needed when Windows images were introduced, which for some time were using a different registry); also see https://github.com/moby/moby/pull/21100 and https://github.com/docker/cli/pull/2819.

A different URL (`registry-1.docker.io/v2`) is used for the registry (so for pulling the actual images)

**Comment by thaJeztah** [comment]
this field was removed from the output in https://github.com/docker/cli/pull/4204

Let me close this ticket for now, as it looks like it went stale.
