### ISSUE TITLE
Cgroupv2: root cgroup.subtree_control is empty and cannot be written to when a private cgroup namespace is used

### ISSUE THREAD

**Issue by MarkKoz** [moby/moby#43093]
Since https://github.com/moby/moby/pull/38377, containers by default use a private cgroup namespace, at least for hosts with cgroupv2. This results in an empty `cgroup.subtree_control` in the cgroup root of the container, meaning any child cgroup I need to create within the container will have no controllers enabled. `cgroup.subtree_control` cannot be written to (results in "device or resource busy") presumably because the root cgroup already has processes in it (such as PID 1).

Unless I should be able to write to the root `cgroup.subtree_control` while the container is running, I don't believe this is a bug; it's documented by Linux that `cgroup.subtree_control` starts empty. Rather, it's a feature oversight. There needs to be a way to modify `cgroup.subtree_control` before the container is started, but as far as I can tell there isn't. The current workaround is to use the host's namespace instead of a private one.

**Comment by AkihiroSuda** [comment]
You can write, like this

https://github.com/moby/moby/blob/088afc99e4bf8adb78e29733396182417d67ada2/hack/dind#L28-L38

**Comment by MarkKoz** [comment]
Thank you, I somehow never thought to try that. This solution is good enough for me. Feel free to close if you don't think there's merit to making this a feature.
