### ISSUE TITLE
Unable to push docker image to ecr from ec2

### ISSUE THREAD

**Issue by varundunga** [moby/moby#43106]
**Description**
Im trying to push docker image to ecr from ec2 but fails

**Steps to reproduce the issue:**
1. login to ec2 and authenticate using the below command 
```
aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ************.dkr.ecr.us-west-1.amazonaws.com
```
This command will say login succeeded
2. now try to push a docker image using below command
```
docker push ***********.dkr.ecr.us-west-1.amazonaws.com/repo_name/image_name:tag
```

**Describe the results you received:**

It gives me the below EOF error after retrying for few seconds.
```
The push refers to repository [*********.dkr.ecr.us-west-1.amazonaws.com/repo_name/image_name]
926889218098: Retrying in 1 second 
ec8ddf59b508: Retrying in 1 second 
1a058d5342cc: Retrying in 1 second 
EOF
```

**Describe the results you expected:**
Image should be pushed to ECR successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.4, build d3cb89e
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 27
  Running: 17
  Paused: 0
  Stopped: 10
 Images: 163
 Server Version: 20.10.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.238-182.421.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: ip-***-**-**-***.us-west-1.compute.internal
 ID: JQGA:M2MB:2KF2:2NOY:SVY6:ZE73:GKKH:HVHP:JSZV:NSJQ:Z22H:2LCX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by varundunga** [comment]
Issue resolved. Was related to issue#24473([https://github.com/moby/moby/issues/24473](url)). The error shown is not pointing to actual issue which is the repository doesnot exist in the region specified

**Comment by vesubramanian** [comment]
In my case, I have the repository existing in the specified region. But I am still facing this issue. Can anyone please help?

**Comment by doguaraci** [comment]
Same here

**Comment by vesubramanian** [comment]
In my case, I had to call AWS and Docker login again via my GitHub action. This resolved the issue.

**Comment by jdiegosierra** [comment]
> In my case, I had to call AWS and Docker login again via my GitHub action. This resolved the issue.

This does not make sense. This is due to permissions. In my case this are my user permissions and still does not work:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ManageRepositoryContents",
            "Effect": "Allow",
            "Action": [
                "ecr:*"
            ],
            "Resource": "*"
        }
    ]
}

However, I can push with an admin user, so It seems the policy needs more permissions

**Comment by dsoyez** [comment]
in your ec2 run: `aws configure`
Then re-run your ecr login command

**Comment by tartarini** [comment]
same problem here. done as  @dsoyez suggests but back to same issue.
Any Idea?
