### ISSUE TITLE
Fluentd log driver causing containers to hang

### ISSUE THREAD

**Issue by stevenheinze57** [moby/moby#43108]
I'm running into an issue wherein my containers are hanging when a stop/kill command is sent. I am only noticing this when trying to use the fluentd log driver and only on my one particular container. I am not seeing this issue on any other containers weirdly. 

I came across this [post](https://github.com/moby/moby/issues/40063) about changes to the fluentd log driver and installed the plugin since it doesn't seem to be merged into the latest release yet, but this doesn't help and I just get the same results. 

Docker Version: 
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker error logs: 
```
Dec 24 12:09:29 hostname dockerd[951503]: time="2021-12-24T12:09:29.363016930-06:00" level=info msg="ignoring event" container=933228af53dc88553529dfcd1d91a513547b66bf57c75b3276012681419528e9 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Dec 24 12:09:34 hostname dockerd[951503]: time="2021-12-24T12:09:34.329903653-06:00" level=info msg="Container failed to exit within 5s of signal 15 - using the force" container=933228af53dc88553529dfcd1d91a513547b66bf57c75b3276012681419528e9
```

At this point the only way to kill this is to restart docker.socket and docker.service. 

The container in question is running Varnish and outputting logs to stdout and stderr. When I switch to use json-file log driver I do not run into this issue though.

**Comment by akerouanton** [comment]
Hello @stevenheinze57, this issue come from the golang library used to send logs to fluentd. Prior to its v1.7.0, it wasn't properly handling `Close()` request (which is called by Docker when a container is stopped) when the fluentd server it tries to talk with is not available. A newer version of that library will be used in the next major release of Docker.

I'm the author of the nonofficial Docker plugin [`akerouanton/fluentd-async-logger`](https://github.com/akerouanton/fluentd-async-logger). I used it a number of times and I'm a bit surprised you still see the bug. It'd be better to open an issue on that repository. If you do so, could you answer these questions, please?

1. Did you change the `log-driver` option in daemon's config and then restart Docker? Or did you specify `--log-driver fluentd-async` flag when launching `docker run` (or `logging` driver in docker-compose file)?
2. Did you delete the buggy container before recreating it with one of the option above?
3. Could you try to enable debug mode, set `LOG_LEVEL` to `debug` and take a trace as mentioned [here](https://github.com/akerouanton/fluentd-async-logger#how-to-debug)?

**Comment by stevenheinze57** [comment]
@akerouanton  In my case this ended up being a deeper issue with my infrastructure's DNS. Fixing that has resolved our issues. I will close this issue.
