### ISSUE TITLE
Create a 2.10.12 GitHub Release

### ISSUE THREAD

**Issue by rgl** [moby/moby#43134]
There is a [v2.10.12 tag](https://github.com/moby/moby/releases/tag/v20.10.12), but there is no corresponding GitHub release in the [GitHub releases page](https://github.com/moby/moby/releases) (the latest one is [2.10.11](https://github.com/moby/moby/releases/tag/v20.10.11)).

Can a 2.10.12 GitHub Release be created?

**Comment by thaJeztah** [comment]
Ah, yes, thanks for the reminder; done: https://github.com/moby/moby/releases/tag/v20.10.12
