### ISSUE TITLE
ZFS Storage Driver - ability to specify `parent dataset`? 

### ISSUE THREAD

**Issue by develop-Greenant** [moby/moby#43149]
The [Docker ZFS storage driver docs](https://docs.docker.com/storage/storagedriver/zfs-driver/) specify how to use ZFS backed storage for Docker.

However, the implementation shown requires the ZFS pool to be dedicated to Docker.  There are many cases in which an administrator may want to use ZFS-backed storage for Docker but not want to allocate a separate pool.

As far as I can see, all the ZFS functions used by the storage driver will work at the `dataset` level (primarily `zfs clone`,  and `zfs snapshot`).

Would it be possible to amend the driver to support a `parent dataset` path?

For instance:

```json
{
  "storage-driver": "zfs",
  "storage-opts": [
       "size=200G"
       "zpool=data"
       "parent-dataset=docker"
    ]
}
```

The Docker storage would then be in  the `docker` dataset in the `data` pool.

**Comment by develop-Greenant** [comment]
found this related forum post: https://forums.docker.com/t/docker-on-zfs-change-parent-dataset/94389

**Comment by develop-Greenant** [comment]
Looks like this is already implemented (my bad) - the dataset can be specified using the `zfs.name` property, see https://docs.docker.com/engine/reference/commandline/dockerd/#zfs-options

**Comment by thaJeztah** [comment]
Looks like this is resolved; let me go ahead and close
