### ISSUE TITLE
Docker Engine v20.10.12 no longer working with proxy

### ISSUE THREAD

**Issue by mhoare1984** [moby/moby#43164]
Docker Engine v20.10.12 on Windows via Docker Desktop 4.4.X no longer works with our corporate proxy. I can no longer do any docker command that connects to the internet. Two other people in our office are experiencing the same issue. If we uninstall Docker Desktop 4.4.X and reinstall 4.3.2 which comes with Docker Engine v20.10.11, the issue is resolved.

Our corporate proxy is Squid. we have set the HTTP and HTTP docker proxy settings to http://ourproxy.domain:3128. The proxy only has a HTTP endpoint so we set the HTTP and HTTPS proxy setting to the same value.

**Steps to reproduce the issue:**
1. Update Docker Desktop for Windows to 4.4.X. I've tested using 4.4.2 and current as of now 4.4.3
2. Attempt a docker pull

**Describe the results you received:**

docker pull mcr.microsoft.com/dotnet/sdk:6.0
Error response from daemon: Get "https://mcr.microsoft.com/v2/": dial tcp 204.79.197.219:443: connect: connection refused

**Describe the results you expected:**

The docker pull should work as it did in previous versions

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 20.10.12, build e91ed57

**Output of `docker info`:**

docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 42
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 11.69GiB
 Name: docker-desktop
 ID: DFRX:AIOR:IBEZ:KS2D:JUTD:SHJV:XA7L:VFMF:3H52:FMXS:RCBJ:U4PY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

This occurs in a physical environment on multiple computers in our office. In all cases it only started occurring after people upgraded above Docker Desktop v4.3.2

**Comment by AkihiroSuda** [comment]
Please report to https://github.com/docker/for-win/issues
