### ISSUE TITLE
[Feature request] Get a Docker container's IP address from the host

### ISSUE THREAD

**Issue by patsevanton** [moby/moby#43196]
Please add a command to get the container's IP address.

Script on bash:

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} %tab% {{.Name}}' $(docker ps -aq
) | sed 's#%tab%#\t#g' | sed 's#/##g' | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n

172.18.0.2       memcached
172.18.0.3       nginx
172.18.0.4       fpm-backup
172.18.0.5       dns
172.18.0.6       fpm-beta
172.18.0.7       exim
172.18.0.8       fpm-delta
172.18.0.9       mariadb
172.18.0.10      fpm-alpha
172.19.0.2       nextcloud-redis
172.19.0.3       nextcloud-db
172.19.0.4       nextcloud
```

**Comment by kponichtera** [comment]
Would it be better to implement this on the API or CLI side? If on the latter one, it should probably go to the [docker/cli](https://github.com/docker/cli) repository, shouldn't it?

**Comment by ndeloof** [comment]
This should indeed be reported on [docker/cli](https://github.com/docker/cli)
Sounds like an equivalent of `docker port` so makes sense to me

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
