### ISSUE TITLE
Not able to install Docker 20.10.12 on Fedora 36 using the script.

### ISSUE THREAD

**Issue by rayandas** [moby/moby#43233]
**Description**
Not able to install Docker on Fedora 36.

**Steps to reproduce the issue:**
1. Run a Fedora 36 instance
2. Get the Docker `20.10.12` script using `curl -Lsk http://get.docker.com/ -o 20.10.12.sh`
3. Run the script.

**Describe the results you received:**
```
[root@20492cd8fb2d /]# ./20.10.12.sh 
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c 'dnf install -y -q dnf-plugins-core'
+ sh -c 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/fedora/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'dnf makecache'
Docker CE Stable - x86_64                                                                                                                                                                                     208  B/s | 389  B     00:01    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/fedora/rawhide/x86_64/stable/repodata/repomd.xml (IP: 52.85.236.54)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Fedora rawhide openh264 (From Cisco) - x86_64                                                                                                                                                                 603  B/s | 989  B     00:01    
Fedora - Rawhide - Developmental packages for the next Fedora release                                                                                                                                         2.7 kB/s | 3.4 kB     00:01    
Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                                                                                                 2.9 kB/s | 3.8 kB     00:01    
Ignoring repositories: docker-ce-stable
Metadata cache created.
+ '[' -n '' ']'
+ sh -c 'dnf install -y -q docker-ce'
Error: Unable to find a match: docker-ce
```

**Describe the results you expected:**
Install Docker 20.10.12 successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
No RPMs for rawhide, but probably you can try Fedora 35 RPMs: https://download.docker.com/linux/fedora/

**Comment by IvanRafael-Dev** [comment]
Follow this post, it worked for me on Fedora 36.

https://computingforgeeks.com/how-to-install-docker-on-fedora/

**Comment by triksmelb** [comment]
@IvanRafael-Dev this instructions on the link (https://computingforgeeks.com/how-to-install-docker-on-fedora/) produce this error on Fedora 36:

$ sudo dnf install docker-ce docker-ce-cli containerd.io
Last metadata expiration check: 0:03:42 ago on Sun 22 May 2022 10:46:14.
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
Error: Unable to find a match: docker-ce docker-ce-cli containerd.io

**Comment by triksmelb** [comment]
found a solution, the author forgot to add a step to the instructions as described [here](https://itsfoss.com/install-docker-fedora/)

`sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo`

**Comment by simba1997** [comment]
> sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

thanks!
