### ISSUE TITLE
Retry required for manifest config blobs

### ISSUE THREAD

**Issue by shizhMSFT** [moby/moby#43267]
**Describe the results you received:**
The manifest config blob of docker schema 2 manifest is directly pulled in [distribution/pull_v2.go](https://github.com/moby/moby/blob/v20.10.12/distribution/pull_v2.go#L654-L663) without any retry logic while layer blobs are pulled via `DownloadManager` with a [retry logic](https://github.com/moby/moby/blob/v20.10.12/distribution/xfer/download.go#L296-L304) (max 5 times).

**Describe the results you expected:**

The manifest config blob is retried on network failure as layers are retried by the `DownloadManager`.

**Moby version:**

`v20.10.12`

**Comment by pete-woods** [comment]
PR here: #43291

**Comment by 77553322AHST** [comment]
📯👌

**Comment by pete-woods** [comment]
I have created a 20.10 backport PR for this fix here: https://github.com/moby/moby/pull/43329
