### ISSUE TITLE
what algorithm does docker pull use to allocate layers between cocurrent docker pull threads?

### ISSUE THREAD

**Issue by huangjunhao2019** [moby/moby#43266]
I know that docker defaultly use three threads to pull layers. But I am curious about how docker allocate these layers between these download threads?

**Comment by thaJeztah** [comment]
The imageService uses the [`distribution/xfer`](https://github.com/moby/moby/tree/32e5fe5099d2806df489feb3e15d8e3e6eca73c1/distribution)/xfer/) package to limit downloads and uploads.
A single instance of the DownloadManager is created when the daemon starts, which uses a TransferManager to limit the number of concurrent pulls. That manager just keeps a queue of pending downloads
https://github.com/moby/moby/blob/32e5fe5099d2806df489feb3e15d8e3e6eca73c1/daemon/images/service.go#L59

https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/distribution/xfer/transfer.go#L349-L354


Pull requests just en up in that queue in the order they arrive.

I hope that helps you further; let me close this ticket as this is not really a bug-report or feature request, but feel free to continue the conversation

**Comment by huangjunhao2019** [comment]
Thank you so much. I have understand.
