### ISSUE TITLE
Wrong operating system reported by docker info on Windows

### ISSUE THREAD

**Issue by crazy-max** [moby/moby#43284]
**Description**

For WCOW case, _Operating System_ reported by `docker info` is not right.

**Steps to reproduce the issue:**
1. _Switch to Windows containers_ on Docker Desktop
2. Open `cmd`
3. Type `docker info`

**Describe the results you received:**

```
> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  hub: Docker Hub (Docker Inc., 346ece73cb-dirty)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.12
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22000 (22000.1.amd64fre.co_release.210604-1628)
 Operating System: Windows 10 Pro Version 2009 (OS Build 22000.527)
 OSType: windows
 Architecture: x86_64
 CPUs: 32
 Total Memory: 63.93GiB
 Name: pc-sff
 ID: BJ23:IQXR:IXL3:FAEE:TGKX:5XWD:7ZKB:6GXF:P5BL:LU3E:T45O:MULU
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Username: ...
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Here we have:

```
Operating System: Windows 10 Pro Version 2009 (OS Build 22000.527)
```

**Describe the results you expected:**

Expected:

```
Operating System: Windows 11 Pro Version 21H2 (OS Build 22000.527)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking at the source code, we rely on the HKLM hive in the registry: https://github.com/moby/moby/blob/dc8fb8f03ba30a80b036706ef89d4dd156729216/pkg/parsers/operatingsystem/operatingsystem_windows.go#L45

Here are the registry values for me:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion]
"BaseBuildRevisionNumber"=dword:00000001
"BuildBranch"="co_release"
"BuildGUID"="ffffffff-ffff-ffff-ffff-ffffffffffff"
"BuildLab"="22000.co_release.210604-1628"
"BuildLabEx"="22000.1.amd64fre.co_release.210604-1628"
"CompositionEditionID"="Enterprise"
"CurrentBuild"="22000"
"CurrentBuildNumber"="22000"
"CurrentMajorVersionNumber"=dword:0000000a
"CurrentMinorVersionNumber"=dword:00000000
"CurrentType"="Multiprocessor Free"
"CurrentVersion"="6.3"
"DisplayVersion"="21H2"
"EditionID"="Enterprise"
"EditionSubManufacturer"=""
"EditionSubstring"=""
"EditionSubVersion"=""
"InstallationType"="Client"
"InstallDate"=dword:00000000
"ProductName"="Windows 10 Enterprise"
"ReleaseId"="2009"
"SoftwareType"="System"
"SystemRoot"="C:\\Windows"
"UBR"=dword:0000020f
"RegisteredOwner"="[redacted]"
"RegisteredOrganization"=""
"PathName"="C:\\Windows"
```

* `Windows 10 Pro`: As I can see `ProductName` is being used in the source code so should be `Windows 10 Enterprise` at least. Not sure where he found `Windows 10 Pro`.
* `2009`: Using `DisplayVersion` (`21H2`) should be more accurate with what is reported by sysinfo.

`winver` output:

![image](https://user-images.githubusercontent.com/1951866/155297027-b8454a86-5e81-413f-801b-d95b59f5ade0.png)

cc @thaJeztah

**Comment by thaJeztah** [comment]
So, this information is provided by the `pkg/parsers/operatingsystem` package, which uses the Windows registry to get the details; https://github.com/moby/moby/blob/dc8fb8f03ba30a80b036706ef89d4dd156729216/pkg/parsers/operatingsystem/operatingsystem_windows.go#L11

I see that originally it did (e.g.) `syscall.StringToUTF16Ptr("ProductName")` (https://github.com/moby/moby/commit/f7ae2a372d6d845040cdf40b246f4eec62512398 (https://github.com/moby/moby/pull/13099)), but later this changed to using the registry (https://github.com/moby/moby/commit/6de9f90417f1295fcdc2f1c977178bff7a735f99 (https://github.com/moby/moby/pull/36451)) to get the ReleaseID (version) and UBR. Wondering if this would've been because Windows Desktop and Server would otherwise produce the wrong information?

**Comment by slonopotamus** [comment]
WRT `ReleaseId`. MS no longer updates it. One instead needs to lookup `DisplayVersion` (and fallback to `ReleaseId` if one doesn't exist).

**Comment by superkkt** [comment]
@thaJeztah May I take this issue? I have already sent a PR.
