### ISSUE TITLE
Changes in host filesystem cause container to lose mount points

### ISSUE THREAD

**Issue by jiehanzheng** [moby/moby#43319]
**Description**

Changes in host filesystem cause container to lose mount points.

Host directories:
* volumes/mydir
* volumes/mydirc

In the container, if I mount `volumes/mydirc` to a mountpoint inside of the mountpoint for `volumes/mydir`, changes to `volumes/mydir` from the host can cause the container to lose access to `volumes/mydirc`.

**Steps to reproduce the issue:**
1/ Create 2 directories on host
```
host$ mkdir volumes/mydir
host$ mkdir volumes/mydirc
```

2/ Start a container using docker-compose like so, with nested mount points (one inside the other).  However you don't have to use docker-compose.
```
version: '2'
services:
  c1:
    image: alpine:latest
    volumes:
      - ./volumes/mydir:/mydir
      - ./volumes/mydirc:/mydir/child
    entrypoint: ["tail", "-f", "/dev/null"]
```

NOTE: In the container, `/mydir/child` is inside of `/mydir`, however on the host they are two separate directories.

```
host$ docker-compose up -d --build
```

3/ Verify that `/mydir/child` is mounted
```
host$ docker-compose exec c1 /bin/sh -c 'mount | grep child'
grpcfuse on /mydir/child type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```

4/ From **host**, delete `volumes/mydir/child`
```
host$ sudo rm -rf volumes/mydir/child/
Password:
```

NOTE: This step on its own is surprising, because I didn't expect to see `child` to show up in  host's `volumes/mydir/`.

**Describe the results you received:**
In container, the `/mydir/child` mount is gone:
```
host$ docker-compose exec c1 /bin/sh -c 'mount | grep child'
```
(No output)

**Describe the results you expected:**
That `/mydir/child` mount should continue to exist.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue repros on both macOS host (Docker Desktop) and Ubuntu 21.10 host.

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 13
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: UK3F:XHW7:WEVB:HXHS:BD6K:TFIA:QCYN:GNRM:SVET:QSO7:IPBB:I7F6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 53
  Goroutines: 54
  System Time: 2022-03-02T20:37:07.536049553Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on physical MacBook

**Comment by ndeloof** [comment]
> This step on its own is surprising, because I didn't expect to see child to show up in host's volumes/mydir/.

Basically, this is the main reason. To be able to create a mount in container under `/mydir/child`, a mount point **need** to be created. As parent folder `/mydir` is also a mounted volume, this mount point is actually created on your host folder. Removing this folder just removes the mount point, and so the volume attachment.

**Comment by jiehanzheng** [comment]
Thanks for the explanation!
