### ISSUE TITLE
Docker in Docker cannot install bundler (ruby gem), on alpine 3.14+

### ISSUE THREAD

**Issue by luke-hill** [moby/moby#43311]
**Description**

Using compose, build the following image in a Docker in Docker ecosystem (It is only possible with alpine 3.13 and below)

```
FROM ruby:3.0.3-alpine3.13

ENV BUNDLER_VERSION=2.3.6 \
    BUNDLE_PATH=/app/vendor/bundle

RUN apk add --no-cache --update build-base bash jq curl libffi-dev

RUN mkdir -p /app

RUN gem install bundler -v $BUNDLER_VERSION
```

**Describe the results you received:**
As soon as you use alpine 3.14 and above, you get a permission error.
```
ERROR:  While executing gem ... (Gem::FilePermissionError)

    You don't have write permissions for the /usr/local/bundle directory.
```
**Describe the results you expected:**
It works.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is **not an issue up to December 2021 - As alpine 3.13 exists for all modern rubies**

This is an issue for ruby 3.1.x+ as there is no alpine 3.13 equivalent for this (Minimum alpine is 3.14)

**Output of `docker compose version`:**

```
docker-compose version
— Shell Script
<1s
+ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by luke-hill** [comment]
I created this as the issue made in https://github.com/docker/compose/issues/9220 was asked to be moved to here. 

If you require more info, please let me know.

The Docker-in-Docker variant with alpine 3.13 works fine. As soon as I move to alpine 3.14 things fail.

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

With the information provided currently, there's no way to reproduce your situation, as the Dockerfile does not build;

```bash
 > [4/4] RUN gem install bundler -v 2.3.6 &&     bundle install &&     gem cleanup:
#8 1.104 Successfully installed bundler-2.3.6
#8 1.104 1 gem installed
#8 1.406 Could not locate Gemfile
------
executor failed running [/bin/sh -c gem install bundler -v $BUNDLER_VERSION &&     bundle install &&     gem cleanup]: exit code: 10
```

**Comment by luke-hill** [comment]
There was a fatter version of this. But you are immediately passing where I failed.

Can I double check you're running DinD?

**Comment by luke-hill** [comment]
docker info

```
+ docker info
Client:
 Context:    default
 Debug Mode: false

 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 274
 Server Version: 18.09.6

 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file

 Cgroup Driver: cgroupfs

 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc

 Init Binary: docker-init
 containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
 init version: fec3683
 Security Options:
  seccomp

   Profile: default
 Kernel Version: 4.18.0-193.41.1.el8_2.x86_64
 Operating System: Alpine Linux v3.10 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: ASDASD
 ID: EZRL:4MS2:5UCF:VNZD:5OZV:NHEE:C2WF:64Z2:ADHY:B7O2:UFTI:5RET
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
ASDASD

WARNING: stuff
```

**Comment by luke-hill** [comment]
docker version

```
+ docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.39
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:41:08 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by luke-hill** [comment]
We are running on Jenkins. Using a Docker in Docker interface. I'm not really sure what more to provide you. I have given you the output of a variety of docker commands.

Your repro scenario was running locally on docker, using a command. We run on Jenkins which is configured using the pipeline agents to build on docker in docker agents. Short of that I cannot provide more information, as I'm a bit hazy on the details.

The commands I run are either

```
sh 'docker-compose build'

# or

sh 'docker build ./'
```

I apologise if this isn't enough information, but this is literally our entire repro scenario. Short of you duplicating our entire infra stack

**Comment by thaJeztah** [comment]
Based on the server version;

```
Server Version: 18.09.6
```

I should note that (first of all) Docker 18.09 has reached EOL three years ago, and has known vulnerabilities (if you're unable to upgrade, at least I would recommend updating to the latest patch release of Docker 18.09 (18.09.9).

From your description of the issue, I suspect this is related to one of (or a combination of);

- https://github.com/moby/moby/pull/42681
    - fixes https://github.com/moby/moby/issues/42680
    - fixes https://github.com/moby/moby/issues/42963
    - fixes https://github.com/moby/moby/issues/42876
- https://github.com/moby/moby/pull/42369
- https://github.com/moby/moby/pull/42933


As it's related to an upgrade from alpine to 3.14, I suspect the first one of those; newer versions of alpine contain Linux userland binaries that execute syscalls that were not available in older kernel versions, and not yet supported by older versions of (lib)seccomp. As a result, those syscalls were blocked by default (returning an `EPERM` by the seccomp profile), which causes those to fail. 

If my suspicion is correct, this should be fixed in current versions of the engine (and containerd, runc).

**Comment by luke-hill** [comment]
Hi @thaJeztah one thing I failed to mention is I tried adding libseccomp to my packages, that didn't remedy it.

I've spoken to devops about this, about upgrading. So I figure that's something to do. However knowing my luck that won't be a quick fix / upgrade :(

**Comment by thaJeztah** [comment]
Ah, yes, the `stable-dind` image was deprecated (it was used when we had `edge` and `stable` releases, but we no longer do). Image deprecation is something that's being discussed on our roadmap (but it's somewhat complicated as the OCI distribution spec doesn't really have something in place for that (yet), and we don't (always) want to _remove_ old images as there's sometimes still use-cases for testing/using deprecated images https://github.com/docker/roadmap/issues/317)

**Comment by HugoPoi** [comment]
This is related to this https://github.com/docker-library/ruby/issues/351#issuecomment-899096462
Alpine need 3.14 at least docker 20.10 on the host.

**Comment by luke-hill** [comment]
I'll just close these issues, as until I have a non-ancient version of docker it's unrealistic to expect support. I'll keep hassling at devops' end.

**Comment by Rasanga** [comment]
> This is related to this [docker-library/ruby#351 (comment)](https://github.com/docker-library/ruby/issues/351#issuecomment-899096462) Alpine need 3.14 at least docker 20.10 on the host.

I am running Docker 20.10.21 but still having the issue though.
