### ISSUE TITLE
Volume synchronization bug on M1 Mac

### ISSUE THREAD

**Issue by mbrowne** [moby/moby#43315]
**Description**

When mounting a volume in an M1 Mac, file synchronization doesn't work reliably. Sometimes the Docker container still has an old copy of the file after saving a new version of the file on the host.

**Update:** this seems to happen when checking out a different branch using git on the host (maybe too many file changes for it to handle at once? But the repo I'm working with isn't particularly big...)

**Steps to reproduce the issue:**

```
docker run -it --rm \
    -v "$(pwd)":/infrastructure-live \
    my-image:latest
```

Then check out a different branch in git (e.g. run `git checkout some-other-branch` on the host)

**Describe the results you received:**

Changes on the host to files in the `infrastructure-live` folder sometimes reflect inside the docker and sometimes do not. Even after deleting the container and creating a new one, the container still had an old copy of at least one of the files in the volume.

**Describe the results you expected:**

Consistent synchronization of file contents inside and outside the container

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 25
  Running: 1
  Paused: 0
  Stopped: 24
 Images: 36
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: CZ37:ACXZ:BXSL:YTRK:WBB2:IGKJ:Q2X7:6ZMJ:EHU7:7ZO5:3NSJ:OTZI
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 53
  Goroutines: 62
  System Time: 2022-03-02T18:58:27.616574632Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Host machine is an M1 Mac (M1 Pro). MacBook Pro (16-inch, 2021)

**Comment by thaJeztah** [comment]
Thank you for reporting; this issue looks to be specific to Docker Desktop (which uses additional tooling to provide synchronisation of files between the macOS host and the Linux VM in which the container runs). That code is not part of the open source docker engine maintained in this repository.

Could you open a ticket in the https://github.com/docker/for-mac issue tracker instead? Unfortunately it's in a different organisation on GitHub, so I'm not able to move the ticket there. Thanks!

**Comment by mbrowne** [comment]
Thanks, I created the new issue here:
https://github.com/docker/for-mac/issues/6219
