### ISSUE TITLE
`/containers/json` response missing `SizeRw` and `SizeRootFs` fields from Swagger spec

### ISSUE THREAD

**Issue by nektro** [moby/moby#43345]
**Description**

Attempting to marshal the response from `/containers/json` based on auto-generated types from `ContainerSummary` yields an error

**Steps to reproduce the issue:**
1. get a container running, eg `docker run -it debian`
2. assert it is live with `docker ps`
3. call `GET http://localhost/v1.41/containers/json` on the dockerd unix socket
4. marshal it into `ContainerSummary` from https://github.com/moby/moby/blob/master/api/swagger.yaml

**Describe the results you received:**

```
error: missing field: SizeRw
error: missing field: SizeRootFs
```

**Describe the results you expected:**

no error

**Additional information you deem important (e.g. issue happens only occasionally):**

```json
[
  {
    "Id": "fbd656505dbb78ce901a20c4f72d18c7b8571118de7f64d12f49d4941f847b5f",
    "Names": [
      "/nice_dirac"
    ],
    "Image": "debian",
    "ImageID": "sha256:d40157244907583ef151d2de83245c018a7bf8b2025518dd1e108ec60c1a679c",
    "Command": "bash",
    "Created": 1646660889,
    "Ports": [],
    "Labels": {},
    "State": "running",
    "Status": "Up 43 seconds",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "91fc49b90ef404365918437fbc6c9ed907d805b7afa733971d98795a8ee4c52c",
          "EndpointID": "621fff99f7fe47e2a6ba8a85bb09c1f176bf2f7d50fe8fdbb54fcdeff46ef97a",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:02",
          "DriverOpts": null
        }
      }
    },
    "Mounts": []
  }
]
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        v20.10.7
 Built:             Thu Jan  1 00:00:00 1970
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       v20.10.7
  Built:            Tue Jan  1 00:00:00 1980
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.7
  GitCommit:        v1.5.7
 runc:
  Version:          1.0.0-rc95
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., 0.0.0+unknown)

Server:
 Containers: 75
  Running: 1
  Paused: 0
  Stopped: 74
 Images: 206
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: v1.5.7
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.79
 Operating System: NixOS 21.05 (Okapi)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: nixos
 ID: XV5J:MBQK:5IUG:HUZ5:OD5V:G2IA:F752:HCXT:UVVC:G244:ORQW:UHD2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by nektro** [comment]
possible fixes would be:
1. populating the fields in the json output
2. marking the fields as optional in swagger

**Comment by ndeloof** [comment]
Those are indeed omitted if value=0 ("empty")
https://github.com/moby/moby/blob/master/api/types/types.go#L148-L149

This is the case for many of the attributes in the Moby API

AFAIK swagger definition can't declare "optional" properties, but do the other way with `"required": [ "x", "y" ]` to make it explicit about required properties. Maybe this depends on the version of swagger you're using?

**Comment by admodev** [comment]
Does explicitly declaring required and optional fields in swagger fixes the issue?

**Comment by ndeloof** [comment]
@admodev Maybe I'm wrong, but AFAIK all fields are "optional" by default, as there's no way to declare an optional field. Only explicitly `required` fields should trigger an error when missing. Sounds to me this is an implementation bug in the generated REST client.

**Comment by admodev** [comment]
@ndeloof I think you're right, so here chances are that it is an implementation bug, an error generated by swagger version or something similar?...

**Comment by nektro** [comment]
I'm working on bindings for a non-Go language based on the swagger document. I was requesting that the fields that are not guaranteed to not be part of the response be omitted from an added `required:` block

**Comment by ndeloof** [comment]
@nektro sure, understood. I just wonder this is a bug in your swagger code generator. With no `required` definition, all fields _should_ be considered optional, and it doesn't seem the generated code in your client is doing so. Maybe you should ask the maintainers?

**Comment by nektro** [comment]
ah, I wasn't aware that thanks

**Comment by nektro** [comment]
(I'm writing the code generator myself, so if that was the intended outcome of omitting `required:` feel free to close the issue)
