### ISSUE TITLE
Docker CE systemctl daemon crashes after upgrade to 20.10.13 

### ISSUE THREAD

**Issue by jaiganeshvazhkudai** [moby/moby#43364]
**Description**

**Steps to reproduce the issue:**
1. Upgrade docker ce from 20.10.12 to 20.10.13 - through yum.
2. Upgrade succeeds, but docker systemctl process is stuck with failed to start 
3. Only way to fix is to reboot the host in a highly disruptive fashion4. 

**Describe the results you received:**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Describe the results you expected:**

docker info with all information and version changed
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:08:16 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.15.2.el7.x86_64
 Operating System: Oracle Linux Server 7.9
 OSType: linux
 Architecture: x86_64
 CPUs: 40
 Total Memory: 251.6GiB
 Name: <server>
 ID: JNZO:EXRQ:4WO5:PIMT:S3E4:CLQR:7BVK:XDZI:BK7M:7D6S:C3LJ:KCFT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
 <dockermirror>
 Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare Metal Host . OEL NOUEK/ UEK5 / UEK4

**Comment by AkihiroSuda** [comment]
Please provide logs (sudo journalctl)

**Comment by jaiganeshvazhkudai** [comment]
-- Logs begin at Fri 2022-03-11 22:23:12 UTC, end at Tue 2022-03-15 16:43:22 UTC. --
Mar 15 16:43:13 <server> systemd[1]: Stopping Docker Application Container Engine...
Mar 15 16:43:13 <server> dockerd[1638]: time="2022-03-15T16:43:13.778642123Z" level=info msg="Processing signal 'terminated'"
Mar 15 16:43:13 <server> dockerd[1638]: time="2022-03-15T16:43:13.780003227Z" level=info msg="Daemon shutdown complete"
Mar 15 16:43:13 <server> systemd[1]: Stopped Docker Application Container Engine.
Mar 15 16:43:13 <server> systemd[1]: Starting Docker Application Container Engine...
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.868812984Z" level=warning msg="The \"graph\" config file option is deprecated. Please use \"data-root\" instead."
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.869010599Z" level=info msg="Starting up"
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.871734661Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.871776316Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.871807211Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.871833733Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.873242320Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.873271381Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.873321387Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.873340744Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.958613082Z" level=info msg="Loading containers: start."
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993502846Z" level=error msg="failed to restore container with containerd" container=548c031d954b51cc12457d993b65973940b025984bdeddc26a4a4272ce58cb55 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin106483002: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993514510Z" level=error msg="failed to restore container with containerd" container=7c50415878f73d18e021cde23054340cac95e8a5bea746be2dfbd144970f827c error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin429309455: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993519464Z" level=error msg="failed to restore container with containerd" container=5547e70a39b72c10ba75debda82dc71678b9dec3515958ed9a66e33ab901554e error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin082824345: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993528849Z" level=error msg="failed to restore container with containerd" container=10bb475d5c655ecab6dd63cd793d852fa82032503131b0c5a6d1adbec87784dc error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin730335106: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993531536Z" level=error msg="failed to restore container with containerd" container=abdba4a712e9c9915ae46082f52f5768b0138223579c2942e81608cd2e68ed7e error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin503339948: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.993535496Z" level=error msg="failed to restore container with containerd" container=6ba4b8432011c7b367dd72ccfbd80be9eb0369f2c73f82622b3e426eb8642d8d error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin305260458: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.994370329Z" level=error msg="failed to restore container with containerd" container=1e8e59d173468dbf0d86b681ec042804775283c043625d140f52acb5db730214 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin575567955: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.994405498Z" level=error msg="failed to restore container with containerd" container=f0fd97c8f0c5b3a342a82a8384af50e5c5bd2e5c70222d91bae89d3b47e178ea error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin318320181: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995531395Z" level=error msg="failed to restore container with containerd" container=5ec9087b0904f84320121c9f1f08668fae43c04cb0b322d4e9fa94f85f4bf34d error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin290404347: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995528785Z" level=error msg="failed to restore container with containerd" container=7e214e57977e337c515e7745ba7e20db29535131eaa7985c87a7756040536e85 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin339039224: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995567655Z" level=error msg="failed to restore container with containerd" container=258c9353db3e2558292c7ab74dab601f5d5d991122d44b727bf1e1d5d015c4a4 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin547158442: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995656029Z" level=error msg="failed to restore container with containerd" container=bf8ffa5e413b05b9054f9f39f5bfb7ad9d27573d4730928e73021ec3bc5fa5e2 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin544765421: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995733016Z" level=error msg="failed to restore container with containerd" container=9c2c49b3cc8ce1e0b07989cc61545b23100082bf5a8ae42f263256e3af548060 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin438081597: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995801349Z" level=error msg="failed to restore container with containerd" container=e3f0b080d95cdc827ad5df3a1205cffc9218572fc3ced7623b0984f885273406 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin453016074: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.995907062Z" level=error msg="failed to restore container with containerd" container=ec107c90444cf11c70d06cc8b30d53099ff399e623075924f05956ee431a98cf error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin213845954: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996014537Z" level=error msg="failed to restore container with containerd" container=b0305630cfe5b5cdf18a473d3d0ec57f0813495602817782b56aaedff2b936fb error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin082328507: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996037497Z" level=error msg="failed to restore container with containerd" container=1e5bec40771ed4eaaea75c18b294cdf18cd9ab9463ee597d77b827844059192f error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin131488397: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996073963Z" level=error msg="failed to restore container with containerd" container=65e263b589a354cc9811db1252758356ee33322467f47a1e8b00fba079439408 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin615796092: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996258813Z" level=error msg="failed to restore container with containerd" container=203d83d1463e7007c697c59e1332b57649e69931bbadbfdcb36b861e278f0b83 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin306065761: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996308182Z" level=error msg="failed to restore container with containerd" container=75cc891a1719faf765a41d29f116d251b0a528a5ae394262a01e1bc5d27a5aaf error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin413654941: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996473820Z" level=error msg="failed to restore container with containerd" container=0b437dbd6d31ea3c6f7c841db82d894cd7e353aa40dad1f41886cf1e9dfdd216 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin209165683: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.996602158Z" level=error msg="failed to restore container with containerd" container=0a5d67e1f2eaaec58476a84615d186cdd376f18568493324b932797b49985d61 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin217519277: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.997122495Z" level=error msg="failed to restore container with containerd" container=88edaa16b3e06655723792c60ba1b25cd01b0eb5f1f3f11bf038744391c81e5f error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin424396979: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.997167717Z" level=error msg="failed to restore container with containerd" container=d545981df26ab3daa40fda3c95796410d2fd3ca4b66a9e1bbcdc2818f0e70fe5 error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin091047507: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:13 <server> dockerd[17413]: time="2022-03-15T16:43:13.997182362Z" level=error msg="failed to restore container with containerd" container=eea6f3de69f727c05f8677c30af35c012f13e64e1b0cbd116470e270e2e9c6ce error="error getting containerd task for container: failed to initialize logging driver: stat /tmp/plugin462534463: no such file or directory" paused=false restarting=false running=true
Mar 15 16:43:14 <server> dockerd[17413]: time="2022-03-15T16:43:14.990283376Z" level=info msg="Removing stale sandbox 42a752bcde3931a3ebed356a630ea19ff4c4a720f66018090bd866762ed2df19 (88edaa16b3e06655723792c60ba1b25cd01b0eb5f1f3f11bf038744391c81e5f)"
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.028179795Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 808704c0d27c3fcf3e49a6cd839777f6c4cd94ea84f3153c94271cdabb8701ac bf1894ce757cefd3491fd713fee19ec2e4a5715884469d0077cea40ffd875079], retrying...."
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.287988417Z" level=info msg="Removing stale sandbox 6ab3fda6e8e25478bf96f94eb74cdae39f3d404c51281077d33cbc4dc8933370 (6ba4b8432011c7b367dd72ccfbd80be9eb0369f2c73f82622b3e426eb8642d8d)"
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.322279269Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 808704c0d27c3fcf3e49a6cd839777f6c4cd94ea84f3153c94271cdabb8701ac 598f58159f758d568f5a8cc39a17ac34c2ec810adc72740daf4a34f2089f9cc5], retrying...."
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.557765487Z" level=info msg="Removing stale sandbox 6dc25522e677fcb1b3f42e67607040427a66fe109ef2d12ed3bb25e9a52494a4 (b0305630cfe5b5cdf18a473d3d0ec57f0813495602817782b56aaedff2b936fb)"
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.593218208Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 808704c0d27c3fcf3e49a6cd839777f6c4cd94ea84f3153c94271cdabb8701ac 37f5c79a631fbbf890a6cc91eeff973986b124467d98fd64d285d018116d3e01], retrying...."
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.826935481Z" level=info msg="Removing stale sandbox 95fc404a51bcead8c2c67f37384d0dd9ff3b49fb552cff22e43fbd59f30363b0 (7e214e57977e337c515e7745ba7e20db29535131eaa7985c87a7756040536e85)"
Mar 15 16:43:15 <server> dockerd[17413]: time="2022-03-15T16:43:15.861967679Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 808704c0d27c3fcf3e49a6cd839777f6c4cd94ea84f3153c94271cdabb8701ac 9a230e1b5c0cadf96e632a34be22ae7747ee72fda66b7f3782d8a63ee2d0df60], retrying...."
Mar 15 16:43:16 <server> dockerd[17413]: time="2022-03-15T16:43:16.098874035Z" level=info msg="Removing stale sandbox cfa891d8454895205cc1154500734fc05d10bdd945905fbb50a2e60df7dda332 (75cc891a1719faf765a41d29f116d251b0a528a5ae394262a01e1bc5d27a5aaf)"

**Comment by jaiganeshvazhkudai** [comment]
Apologies for the delay - had to recover the clusters and handle the issues stemming out of this.
I tried downgrading from this version 20.10.13 to 20.10.12 and got the same issue with systemctl giving up the recovery of docker daemon.

**Comment by jaiganeshvazhkudai** [comment]
@AkihiroSuda @thaJeztah do you need more information?

**Comment by Mrscherry** [comment]
SUN DEFi
 👉 Today's leading electronic financial application.
 👉Sun Defi investment is profitable.
 Annual profit up to 1440%.
 👉High security, absolute safety, quick and quick deposit and withdrawal procedures.
 👉New member promotion when inviting you to join someone get 20 USDt.
 Sun Defi will help you become a Finance expert.
 Quickly click on the link to join Sun Defi:

 https://www.funawealth.com?share_address=0x1813752628964484E01744527388ed5429024926

**Comment by sam-thibault** [comment]
I see a warning in the log `The \"graph\" config file option is deprecated.` but this is not seen in your config file.

It seems like you may have an override somewhere.  Can provide the output for both of these:
- `systemctl cat docker.service`
- `cat /etc/docker/daemon.json`

There is also errors about loading a plugin so there may some other state corrupted on your machine.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
