### ISSUE TITLE
How to change the Privileged mode of running docker container

### ISSUE THREAD

**Issue by Renukasonwane** [moby/moby#43388]
One of my docker container is running in Privileged Mode (as shown below) -

`docker inspect <ContainerID> | grep 'Privileged'
            "Privileged": true,`

I want to make the container as non-privileged , How can I change the mode in a running container ?

**Comment by AkihiroSuda** [comment]
> How can I change the mode in a running container ?

You can't. You have to recreate a container without `--privileged`.
