### ISSUE TITLE
Can't type into Username/Password prompts for DockerHub (Windows 10, 2022)

### ISSUE THREAD

**Issue by hzeig** [moby/moby#43405]
Hi there

When I use `docker login` in the command line, I'm prompted to enter a username but no letters appear when I type. I've tried just typing and pressing enter, but no letters are being inputed either.

Easy Workaround: I can log in fine when I input the information via that command line directly (`docker login -u <username> -p <password>`) but I still felt this is a strange issue that needs to be resolved. That's why I'm posting it. 

Any suggestions/recommendations? Thanks,

**Comment by corhere** [comment]
@hzeig could you please provide your `docker version` output? Which terminal software are you using: the new Windows Terminal, the original Windows Console, or something else?

**Comment by hzeig** [comment]
Sorry, but I don't remember anymore, this was many months ago and we ended up abandoning this method.

**Comment by thaJeztah** [comment]
Let me close this one per the above
