### ISSUE TITLE
Download a big-dash-name docker image with download-frozen-image-v2.sh 

### ISSUE THREAD

**Issue by James1freedictionary** [moby/moby#43421]
![397B9272-9A33-4CD0-8A30-7BE14A83EA32](https://user-images.githubusercontent.com/97018942/159960445-3cec955e-2627-4d47-a5b1-5fe637fb56f3.jpeg)

The docker image is almost 12GB.

**Comment by thaJeztah** [comment]
Thanks for reporting; that script's main purpose is to be used in our CI, where we download some images to be used in our integration tests.

The script _may_ be useful for some uses outside of that, but we don't have the intention to make it a generic tool, as there are other tools more suitable for doing that (also see the discussion on https://github.com/moby/moby/issues/40857)

For downloading images to a tar archive, consider using something like https://github.com/regclient/regclient or skopeo, which offer more advanced features and are more useful as a generic tool.
