### ISSUE TITLE
Can copy not generate a mirror layer？

### ISSUE THREAD

**Issue by fengzhibin** [moby/moby#43446]
![企业微信截图_16487972815637](https://user-images.githubusercontent.com/12097229/161216435-8940ce4d-3577-42dc-9c27-3808878cf8ba.png)

As shown in my screenshot, I copied a source code package through the copy command based on centos7 image. I expect the final volume of the image to be cenots7. The image volume (204m) + source code volume (113m) is equal to 317m.

However, the final mirror volume becomes 490m, which is about 204m + 113m * 2

By consulting the documentation, we know that the copy command will generate a mirror layer. Is there any way to copy files from the host to the image, but there is no volume consumption of the image layer?

For the time being, my idea is to open the HTTP server on the host computer, and then download the source code compressed package through curl.

Similar problems：https://github.com/moby/moby/issues/40890

**Comment by fengzhibin** [comment]
It seems that the --squash parameter is suitable for solving this problem.

Related documents:https://docs.docker.com/engine/reference/commandline/build/

**Comment by thaJeztah** [comment]
In general, I'd avoid `--squash` unless there's no other option, as it squashes the produced layers, which means that layer sharing can no longer be used (and a single file change will result in all of those layers combined to produce a new, potentially large, layer)

Curious; given that your `project_code.tar.gz` is a local file; is there a specific reason you have it as a `.tar.gz` and not the extracted files?

If you cannot have the files extracted as source for the `COPY`, I'd generally recommend using a multi-stage build; something like;

```Dockerfile
# syntax=docker/dockerfile:1

FROM alpine AS source
COPY project_code.tar.gz /temp/
RUN tar -zxf /temp/project_code.tar.gz -C /source/ --strip-components=1

FROM centos:9 AS deploy
COPY --from=source /source/ /data/htdocs/
```

You can also use the `RUN --mount` option (https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md) to mount the build-context in a temp location (which doesn't get into the produced image), e.g. this example bind-mounts the build-context to `/tmp/` for the `RUN` instruction, and extracts the archive;

```Dockerfile
# syntax=docker/dockerfile:1

FROM centos:8 AS deploy
RUN --mount=target=/tmp/ \
  mkdir -p /data/htdocs \
  && tar -zxf /tmp/project_code.tar.gz -C /data/htdocs --strip-components=1
```

This requires BuildKit to be enabled though, so set `DOCKER_BUILDKIT=1` when building;

```bash
DOCKER_BUILDKIT=1 docker build -t myimage .

+] Building 1.7s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 234B                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                     0.8s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:178c4e4a93795b9365dbf6cf10da8fcf517fcb4a17f1943a775c0f548e9fc2ff                0.0s
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/centos:8                                                                                    0.0s
 => [internal] load build context                                                                                                              0.0s
 => => transferring context: 269B                                                                                                              0.0s
 => CACHED [deploy 1/2] FROM docker.io/library/centos:8                                                                                        0.0s
 => [deploy 2/2] RUN --mount=target=/tmp/   mkdir -p /data/htdocs   && tar -zxf /tmp/project_code.tar.gz -C /data/htdocs --strip-components=1  0.4s
 => exporting to image                                                                                                                         0.1s
 => => exporting layers                                                                                                                        0.1s
 => => writing image sha256:5fa28601ae854a41517de2bf7f5923f1df4817a7a7526bff9172bcc940954a03                                                   0.0s
 => => naming to docker.io/library/myimage                                                                                                     0.0s
```

**Comment by fengzhibin** [comment]
> In general, I'd avoid `--squash` unless there's no other option, as it squashes the produced layers, which means that layer sharing can no longer be used (and a single file change will result in all of those layers combined to produce a new, potentially large, layer)
> 
> Curious; given that your `project_code.tar.gz` is a local file; is there a specific reason you have it as a `.tar.gz` and not the extracted files?
> 
> If you cannot have the files extracted as source for the `COPY`, I'd generally recommend using a multi-stage build; something like;
> 
> ```dockerfile
> # syntax=docker/dockerfile:1
> 
> FROM alpine AS source
> COPY project_code.tar.gz /temp/
> RUN tar -zxf /temp/project_code.tar.gz -C /source/ --strip-components=1
> 
> FROM centos:9 AS deploy
> COPY --from=source /source/ /data/htdocs/
> ```
> 
> You can also use the `RUN --mount` option (https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md) to mount the build-context in a temp location (which doesn't get into the produced image), e.g. this example bind-mounts the build-context to `/tmp/` for the `RUN` instruction, and extracts the archive;
> 
> ```dockerfile
> # syntax=docker/dockerfile:1
> 
> FROM centos:8 AS deploy
> RUN --mount=target=/tmp/ \
>   mkdir -p /data/htdocs \
>   && tar -zxf /tmp/project_code.tar.gz -C /data/htdocs --strip-components=1
> ```
> 
> This requires BuildKit to be enabled though, so set `DOCKER_BUILDKIT=1` when building;
> 
> ```shell
> DOCKER_BUILDKIT=1 docker build -t myimage .
> 
> +] Building 1.7s (11/11) FINISHED
>  => [internal] load build definition from Dockerfile                                                                                           0.0s
>  => => transferring dockerfile: 234B                                                                                                           0.0s
>  => [internal] load .dockerignore                                                                                                              0.0s
>  => => transferring context: 2B                                                                                                                0.0s
>  => resolve image config for docker.io/docker/dockerfile:1                                                                                     0.8s
>  => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:178c4e4a93795b9365dbf6cf10da8fcf517fcb4a17f1943a775c0f548e9fc2ff                0.0s
>  => [internal] load build definition from Dockerfile                                                                                           0.0s
>  => [internal] load .dockerignore                                                                                                              0.0s
>  => [internal] load metadata for docker.io/library/centos:8                                                                                    0.0s
>  => [internal] load build context                                                                                                              0.0s
>  => => transferring context: 269B                                                                                                              0.0s
>  => CACHED [deploy 1/2] FROM docker.io/library/centos:8                                                                                        0.0s
>  => [deploy 2/2] RUN --mount=target=/tmp/   mkdir -p /data/htdocs   && tar -zxf /tmp/project_code.tar.gz -C /data/htdocs --strip-components=1  0.4s
>  => exporting to image                                                                                                                         0.1s
>  => => exporting layers                                                                                                                        0.1s
>  => => writing image sha256:5fa28601ae854a41517de2bf7f5923f1df4817a7a7526bff9172bcc940954a03                                                   0.0s
>  => => naming to docker.io/library/myimage                                                                                                     0.0s
> ```

Thank you for your comments
