### ISSUE TITLE
`Mount` API to support creating host path if missing

### ISSUE THREAD

**Issue by ndeloof** [moby/moby#43483]
**Description**

docker/compose uses the `mount` API to create volumes, but has to rely on the legacy `bind` when missing host path must be created, as `mount` API doesn't offer an option to have the equivalent behavior. While we prefer the `mount` API being more explicit with a well defined data structure, we need to switch between those.

Would be nice `mount` API offers options so it can fully replace the `bind` one, and it can eventually be deprecated.

**Comment by cpuguy83** [comment]
Works for me.
I've had others give me pushback on this in the past.

some things to think about:
- what permissions/ownership?
- What if you have two requests to create but with different perms?
- What if it exists but has different perms?

Perms issues are similar to SELinux labeling problems.

**Comment by ndeloof** [comment]
host path binding feature indeed comes with this contradiction that actual permission isn't set in isolation, but depends on previously created paths and can impact other containers running on same host. I don't expect we can find a solution to this, this is just what bind mounts are about.

**Comment by thaJeztah** [comment]
I started writing up some things, but realise I didn't post :sweat:

Overall, I think this change may help us migrate away from the "old" API, correct? From that perspective, I think it makes sense (and having it as an explicit option is at least a lot better than the old API implicitly creating missing paths).

So while this isn't _worse_ than the old API, and (as said), makes it both explicit (at the API level), and could help us move away from the old API entirely, I do share some of @cpuguy83's concerns. Let me post those ramblings below (sorry, it's a bit long, but hope it helps with the discussion  and to come up with ideas).

**Comment by thaJeztah** [comment]
## Possible solution(s)

So.... what options do we have??

### Create the file locally

For scenarios `1.` and `2.`, assuming "inner loop" development (and working with Docker Desktop?), I'm _tempted_ to say; perhaps we should match the user's expectation; `-v "$PWD"/something:/foo` to mean "my local `"$PWD"/something` file (or directory); if the file doesn't exist, create it (as the current user). So perhaps that's exactly what we should do; have the CLI (which could be `docker` or `docker compose`) create the directory. When using Docker Desktop (or a local daemon), the path would now exist on the host, and the container can mount it. For this solution, the API call and daemon side would not change; if the daemon is running remotely, the file would only exist locally (and not on the daemon), so an error would still be produced.

This could be an opt-in/opt-out option (configurable in the CLI config or some option in the `docker context` metadata) for users that use the CLI to work with a remote daemon that _want_ the path to be created remotely (not locally).

### Pluggable "hooks"

Slightly orthogonal, and more of a "long term" thing to consider; This would  somewhat similar to https://github.com/moby/moby/pull/33375 (which wasn't merged); perhaps the daemon could provide an integration point for containers create and run cycles ("hooks" or "plugins" or `<insert some approach>`). Making this extendable could help with preparing things before a container is created or started, such as;

- translating paths (the bit that docker desktop does  to translate a path on the host to a path "within the VM")
- create (missing) paths
- or: produce an error if a path (or file) doesn't exist
- other things?

This would "formalize" some of the integration a bit better (but there might still be some bits to look into, such as translating "back" the VM path to "host path" when inspecting a container). To some extend this could be done with the "authz" plugins, but we explicitly didn't allow those at the time to _modify_ requests (they're also too broad, as they act on "all" requests).

> To some extend, this feels a bit similar to the CSI approach (https://github.com/moby/moby/pull/41982), which (if I'm not mistaken) also requires a driver to set up things, but not fully the same


### "file" type for bind-mounts

This is mostly for scenario `2.` (trying to mount a _file_); having a separate "type" for mounting a file at least allows the daemon to fail early if the host-path doesn't exist as file (or create a stub file). Perhaps this would already be covered with pluggable "hooks"; there's also cases where (think of `-v /var/run/docker.sock:/var/run/docker.sock`) a socket is expected (not a "plain" file), so not sure how much this would help.

**Comment by ndeloof** [comment]
This is going way belong my initial intent... I didn't considered revisiting the concept of bind mounts so deeply, just want to get rid of two APIs for the same need. But happy this helps to collect ideas for future improvements.
