### ISSUE TITLE
Docker is unuseable with vfs driver on exfat drive

### ISSUE THREAD

**Issue by punyidea** [moby/moby#43527]
**Description**
I ran into this issue while attempting to save space on my root drive by changing to my secondary hard drive, formatted in exfat.

**Steps to reproduce the issue:**
1. Change docker config file to include "data-root" on an exfat drive, with storage-driver vfs
2. Start docker service after running daemon-reload 
3. `docker run --rm hello-world` (either rootless or not)

**Describe the results you received:**

Docker will not run hello-world, claiming symlink function is not implemented. This is contrary to the current storage-driver documentation for vfs, which claims it will work on any filesystem with ubuntu. Error log:
```
docker run --rm hello-world
docker: Error response from daemon: symlink /proc/mounts /mnt/e_exfat/Code/Docker/vfs/dir/87af808901c5e10438263c70a19471c551bd67e85da4cc57a7912d9dc0c43919-init/etc/mtab: function not implemented.
```

**Describe the results you expected:**
A good running container

**Additional information you deem important (e.g. issue happens only occasionally):**
The program works okay when the vfs storage driver is used on the normal drive, or on an NTFS partition. Only exFAT seems to have the issue

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.14
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.13.0-40-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 19.39GiB
 Name: 42Comp
 ID: IIYN:ARQA:224C:4BGW:BEDW:2HVC:CNQY:VNYM:3OAI:TSXK:FTED:A7GG
 Docker Root Dir: /mnt/e_exfat/Code/Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I run Ubuntu 20.04 LTS.

**Comment by punyidea** [comment]
As a sidenote, do I have any options as it stands to use this exFAT storage? I am on a dual-boot machine.

**Comment by thaJeztah** [comment]
I don't think exFat supports symlinks (also see https://superuser.com/a/232266), so while the vfs driver itself does not require "special" features (it's literally just using directories with a full copy of each image), if the image uses a symlink, that won't work.

**Comment by punyidea** [comment]
Thanks for the reply. I did find that during a Google but didn't know enough about filesystems and how vfs operated to rule out that being the issue. Could the documentation please be updated to reflect this?

**Comment by thaJeztah** [comment]
The vfs driver is really for debugging, and usually only to be used as a last resort if nothing else can be used. For that reason, it also doesn't do any checks for compatibility on the underlying filesystem.

**Comment by punyidea** [comment]
Thanks again for the reply. I have to admit that I myself am not involved enough with docker that I 'm invested about the particular implementation details. I'm more interested in knowing if what I will do is supported, to make sure that there's not an error on my side. Since writing the last comment I found that I can make a separate issue for documentation requests so I will fill one there and link it with this issue, thanks!

If anyone would happen to have time, I'd like to ask if there is currently a way of having docker use exFAT storage for running its program. Looking through the documentation it didn't seem like it, but it makes sense to double-check here.
