### ISSUE TITLE
SSH scheme in DOCKER_HOST

### ISSUE THREAD

**Issue by borud** [moby/moby#43549]
Was there support for using ssh://user@host at some point and this functionality was removed?  This functionality would have been very useful.  Has anyone tried to add this (back in)?

https://github.com/moby/moby/blob/a6919e12b103aab6eb95a67450b2a487bfec1097/client/envvars.go#L41

**Comment by thaJeztah** [comment]
Has been supported since docker 18.09 through the docker cli, which handles the connection (related pull request is https://github.com/docker/cli/pull/1014);


```bash
$ DOCKER_HOST=ssh://swarm-test-01 docker version
Client:
 Cloud integration: v1.0.23
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by borud** [comment]
> Has been supported since docker 18.09 through the docker cli, which handles the connection (related pull request is [docker/cli#1014](https://github.com/docker/cli/pull/1014));

I was looking for a way to use this when using the library since it wasn't obvious how to achieve this.  If you set the DOCKER_HOST to an ssh-url and create a new client, it won't work (which, looking at the code wasn't too odd because the code doesn't seem to exist in this repository.  The solution is to use `github.com/docker/cli/cli/connhelper` and add a `client.WithDialContext()`.

Here's a short snippet demonstrating it:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/docker/cli/cli/connhelper"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)

func main() {
	helper, err := connhelper.GetConnectionHelper("ssh://my.ssh.host.com")
	if err != nil {
		log.Fatal(err)
	}

	cl, err := client.NewClientWithOpts(client.WithHost(helper.Host), client.WithDialContext(helper.Dialer))
	if err != nil {
		log.Fatal(err)
	}

	containers, err := cl.ContainerList(context.Background(), types.ContainerListOptions{All: true})
	if err != nil {
		log.Fatal(err)
	}

	jsonData, err := json.MarshalIndent(containers, "", "  ")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(jsonData))
}
```
