### ISSUE TITLE
docker run with attach option，does not work

### ISSUE THREAD

**Issue by dqnu** [moby/moby#43577]
when using command：

> docker -D run -a stdin -a stdout ubuntu /bin/bash

command teminated immediately with output：

> DEBU[0000] [hijack] End of stdout

while using command

> docker -D run -i -a stdin -a stdout ubuntu /bin/bash

bash in container works properly，typing ps for example：

> 
>  docker -D run -i -a stdin -a stdout ubuntu /bin/bash
> ps
>    PID TTY          TIME CMD
>      1 ?        00:00:00 bash
>      7 ?        00:00:00 ps
 
can someone explain that:）

**Comment by thaJeztah** [comment]
Looks like you opened tickets in multiple repositories. Let me copy my answer from  here; https://github.com/docker/cli/issues/3598#issuecomment-1122997874

> If there's no stdin attached, the `/bin/bash` process will terminate immediately (it runs the command, has nothing to do, and exits). The `/bin/bash` command itself doesn't print anything by default, so there's no output.
> 
> If you change it to, e.g. `/bin/bash -c 'ps'` (or just `ps`), you'll get output (but the container also exits once that command completes);
> 
> ```shell
> docker -D run -a stdin -a stdout ubuntu /bin/bash -c 'ps'
>   PID TTY          TIME CMD
>     1 ?        00:00:00 ps
> DEBU[0000] [hijack] End of stdout
> ```
> 
>  ```shell
> docker -D run -a stdin -a stdout ubuntu ps
>   PID TTY          TIME CMD
>     1 ?        00:00:00 ps
> DEBU[0000] [hijack] End of stdout
> ```
