### ISSUE TITLE
Failed to create a Container Manager: mountpoint for cpu not found

### ISSUE THREAD

**Issue by luoxue03** [moby/moby#43608]
**Description**

**Steps to reproduce the issue:**
1.Create container cadvisor
```
docker run   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:ro   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --volume=/dev/disk/:/dev/disk:ro   --publish=8080:8080   --detach=true   --name=cadvisor   --privileged   --device=/dev/kmsg  google/cadvisor
```
2.Container status exitd(255)

**Describe the results you received:**
docker logs cadvisor 
Get error 
`F0518 02:42:13.384527       1 cadvisor.go:146] Failed to create a Container Manager: mountpoint for cpu not found
`

**Describe the results you expected:**
Create a cadvisor container based on official documentation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.15
 API version:       1.41
 Go version:        go1.17.9
 Git commit:        fd82621
 Built:             Thu May  5 13:21:10 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.15
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.9
  Git commit:       4433bf6
  Built:            Thu May  5 13:19:15 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 20.10.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-25-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.897GiB
 Name: mjz-ubuntu-docker-vm
 ID: EUGI:MOZM:NUH7:777V:4RHU:G64V:OTAH:UVQR:AS7H:NNMV:3KIN:TQHM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://a8x1qfbv.mirror.aliyuncs.com/
 Live Restore Enabled: false

WARNING: API is accessible on http://192.168.117.59:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using VM virtual machine version 15.1
Ubuntu version
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

```

**Comment by luoxue03** [comment]
Using docker18 version and vmcentos7 virtual machine is not encountered

**Comment by thaJeztah** [comment]
The error comes from cAdvisor; I see the Ubuntu machine is running with cgroups v2, and I _suspect_ the CentOS 7 machine would be using cgroups v1.

The error `mountpoint for cpu not found` may indicate it's looking for the CPU group, but wasn't able to find it (perhaps because it's looking for the v1 cgroup?)

Overall, I don't think there's a bug at hand here, and the cAdvisor issue tracker may be a better place for this.

**Comment by luoxue03** [comment]
> 错误来自cAdvisor;我看到 Ubuntu 机器正在运行 cgroups v2，_我怀疑_ CentOS 7 机器会使用 cgroups v1。
> 
> 该错误可能指示它正在寻找CPU组，但无法找到它（也许是因为它正在寻找v1 cgroup？`mountpoint for cpu not found`
> 
> 总的来说，我不认为这里有一个错误，而cAdvisor问题跟踪器可能是一个更好的地方。

Thank you for your reply, because I am a rookie How do you view the cdadvisor problem tracker and modify the CGroup version used by the system

**Comment by luoxue03** [comment]
> 错误来自cAdvisor;我看到 Ubuntu 机器正在运行 cgroups v2，_我怀疑_ CentOS 7 机器会使用 cgroups v1。
> 
> 该错误可能指示它正在寻找CPU组，但无法找到它（也许是因为它正在寻找v1 cgroup？`mountpoint for cpu not found`
> 
> 总的来说，我不认为这里有一个错误，而cAdvisor问题跟踪器可能是一个更好的地方。

Thank you for your reply, because I am a rookie How do you view the cdadvisor problem tracker and modify the CGroup version used by the system

**Comment by thaJeztah** [comment]
The cAdvisor project is maintained in https://github.com/google/cadvisor

I generally don't recommend switching to cgroups v1, as v2 is the default now for most distros, but perhaps there's configuration changes needed in how you run the cAdvisor container (or perhaps it needs options to work with cgroups v2); it's been quite a while since I used cAdvisor myself, so I can't provide more help with that.

**Comment by luoxue03** [comment]
> cAdvisor 项目以 https://github.com/google/cadvisor
> 
> 我通常不建议切换到cgroups v1，因为v2现在是大多数发行版的默认值，但也许在运行cAdvisor容器的方式上需要进行配置更改（或者可能需要选项来使用cgroups v2）;自从我自己使用cAdvisor以来已经有很长一段时间了，所以我无法提供更多的帮助。


I solved the problem because my version of cdadvisor does not support cgroupv2 Because I'm in China, I can't go to Google to download the latest version of cdadvisor


I used the docker image of  zcube/cadvisor, and After cgroupv2 is closed in this page, cdadvisor is successfully run


Thank you again for your reply!

https://docs.docker.com/config/containers/runmetrics/

**Comment by thaJeztah** [comment]
> Because I'm in China, I can't go to Google to download the latest version of cdadvisor

Ah, yes, that's unfortunate; make sure that `zcube/cadvisor` is a trusted image though! (there's quite some malicious / bad images, sometimes to "trick" users into running them, but they may be (e.g.) including bitcoin miners, or worse).

I think there also may be mirrors available in China to pull images from `gcr.io/cadvisor/cadvisor`

**Comment by thaJeztah** [comment]
Let me close this ticket, as it looks it's resolved (feel free to continue the conversation after I closed)

**Comment by luoxue03** [comment]
> > Because I'm in China, I can't go to Google to download the latest version of cdadvisor
> 
> Ah, yes, that's unfortunate; make sure that `zcube/cadvisor` is a trusted image though! (there's quite some malicious / bad images, sometimes to "trick" users into running them, but they may be (e.g.) including bitcoin miners, or worse).
> 
> I think there also may be mirrors available in China to pull images from `gcr.io/cadvisor/cadvisor`

OK, thank you again for your help!
