### ISSUE TITLE
Pulling image from private registry when using DOCKER_HOST returns 'no basic auth credentials'

### ISSUE THREAD

**Issue by jetxr** [moby/moby#43602]
**Description**

When using `DOCKER_HOST=ssh://ec2-user@targetinstance` on a local machine, and trying to pull the image on the target instance with `docker pull image REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest`, returns a failure from Docker host on target instance

```
Calling HEAD /_ping
Calling POST /v1.41/images/create?fromImage=REDACT.dkr.ecr.us-east-1.amazonaws.com%2Fapp&tag=latest
hostDir: /etc/docker/certs.d/REDACT.dkr.ecr.us-east-1.amazonaws.com
Trying to pull REDACT.dkr.ecr.us-east-1.amazonaws.com/app from https://REDACT.dkr.ecr.us-east-1.amazonaws.com v2
Attempting next endpoint for pull after error: Head \"https://REDACT.dkr.ecr.us-east-1.amazonaws.com/v2/app/manifests/latest\": no basic auth credentials
Handler for POST /v1.41/images/create returned error: Head \"https://REDACT.dkr.ecr.us-east-1.amazonaws.com/v2/app/manifests/latest\": no basic auth credentials
```

However, the pull command works correctly when running directly on the target instance (i.e. by SSH-ing manually into the target instance and running `docker pull image REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest`):

```
Calling HEAD /_ping
Calling POST /v1.41/images/create?fromImage=REDACT.dkr.ecr.us-east-1.amazonaws.com%2Fapp&tag=latest
hostDir: /etc/docker/certs.d/REDACT.dkr.ecr.us-east-1.amazonaws.com
Trying to pull REDACT.dkr.ecr.us-east-1.amazonaws.com/app from https://REDACT.dkr.ecr.us-east-1.amazonaws.com v2
Pulling ref from V2 registry: REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest
.
.
.
Adding content digest to lease" digest="sha256:b27e3b8e090eba10309e65a79f3e8d3156303a00a0054cf9824924de4611bb90" lease="moby-image-sha256:f2c8af66a15dd2706264084c35cb7cdb6d1f752d608169a3905b69d114ce6f57" remote="REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest
```

All other docker commands run fine when using `DOCKER_HOST`. Only pulling images from an ECR private repo while using `DOCKER_HOST` fails.

**Steps to reproduce the issue:**

**Target instance**: EC2 instance with Docker, on which the image has to be pulled
**Local machine**: macOS/Debian machines which use `DOCKER_HOST` to connect to target instance using ssh

Target instance setup:
1. Created a new EC2 instance (has IAM role attached which allows pulling from ECR private registry)
2. Installed Docker with `amazon-linux-extras install docker -y`, `usermod -a -G docker ec2-user`, `systemctl enable --now docker`
3. Installed amazon-ecr-credential-helper with `yum install amazon-ecr-credential-helper` and created `config.json` in `~/.docker/config.json` with the contents:
```json
{
	"credsStore": "ecr-login"
}
```
4. Run `docker pull image REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest` directly on target instance. _Works_.
5. Add local machine's public key to authorized_hosts on target instance

Local machine setup:
1. Has Docker installed
2. Try pulling public image `export DOCKER_HOST=ssh://ec2-user@targetinstance` and then `docker image pull nginx:alpine`. _This works_.
3. Try pulling the ECR image `export DOCKER_HOST=ssh://ec2-user@targetinstance` and then `docker image pull REDACT.dkr.ecr.us-east-1.amazonaws.com/app:latest`. _This fails_.

**Describe the results you received:**
Fails with error:

```
Error response from daemon: Head "https://REDACT.dkr.ecr.us-east-1.amazonaws.com/v2/app/manifests/latest": no basic auth credentials
```

**Describe the results you expected:**
Image should have pulled successfully on target instance, just like it works when running the command from inside the instance

**Additional information you deem important (e.g. issue happens only occasionally):**
- I have tried with multiple local machines, the pull doesn't work for the ECR registry
- Tried setting `export DOCKER_CONFIG=/home/ec2-user/.docker` as mentioned [in this fix](https://issues.jenkins.io/browse/JENKINS-44143?focusedCommentId=325215&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-325215). Still din't work.

**Output of `docker version`:**

```
Client:
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 31 19:20:32 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 31 19:21:13 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc:
  Version:          1.0.3
  GitCommit:        f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0)
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc version: f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.112-108.499.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.685GiB
 Name: ip-172-21-32-154.us-east-1.compute.internal
 ID: TH6V:7WR4:4C2S:NJ4V:KZX6:NOOD:IJ2E:2NLV:BVLE:UW45:VBNN:BV6U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
**Target instance**: EC2 instance with Docker, on which the image has to be pulled
**Local machine**: macOS/Debian machines which use `DOCKER_HOST` to connect to target instance using ssh

**Comment by thaJeztah** [comment]
Trying to read your reproduction steps; is the `amazon-ecr-credential-helper` and `~/.docker/config.json`  installed on the remove machine (that you're `ssh` connecting with), or on the local machine that you're connecting _from_?

**Comment by thaJeztah** [comment]
So I _think_ in that case, the credentials should be present on your _local_ machine, not the remote one 🤔 (the local CLI connects with the remote daemon, and it's the CLI's responsibility to send the authentication information)

**Comment by jetxr** [comment]
That worked!

I added amazon-ecr-credential-helper local machine, and it picked up the creds.

Thanks @thaJeztah, wouldn't have been able to piece this together on my own.

Closing the issue, doesn't seem like there is anything wrong with Moby here. Will try and get this documented in Docker CLI docs.

**Comment by thaJeztah** [comment]
Good to hear it's resolved!

For a minute I was afraid there was a bug where it would actually look up credentials on the remote machine (which it shouldn't!), so happy to hear that's not the case, and just a misunderstanding.
