### ISSUE TITLE
The reassembling for the json-file logging driver happens when reading the logs (`docker logs`); I don't think the GELF logging driver has "read" support (so the daemon only sends the messages to GELF). When using docker 20.10, it should also write to a local buffer (which uses the `local` logging driver) to provide read support (through `docker logs`); https://docs.docker.com/config/containers/logging/dual-logging/.

### ISSUE THREAD

**Issue by AmyChik** [moby/moby#43600]
The reassembling for the json-file logging driver happens when reading the logs (`docker logs`); I don't think the GELF logging driver has "read" support (so the daemon only sends the messages to GELF). When using docker 20.10, it should also write to a local buffer (which uses the `local` logging driver) to provide read support (through `docker logs`); https://docs.docker.com/config/containers/logging/dual-logging/.

_Originally posted by @thaJeztah in https://github.com/moby/moby/issues/43162#issuecomment-1016602223_

**Comment by thaJeztah** [comment]
I suspect this was opened accidentally
