### ISSUE TITLE
up namespace

### ISSUE THREAD

**Issue by Scipi** [moby/moby#43638]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Scipi** [comment]
This issue was accidentally opened (and I don't really know how). Closed, since I don't have the ability to delete it

**Comment by thaJeztah** [comment]
I think you may have been "victim" of GitHub's keyboard shortcuts; in the overview page, pressing `c` is to create a new issue, so if you tried to search, (e.g.) `docker foo` then the `c` may have triggered "create ticket".

No worries! It happens all the time 😂
