### ISSUE TITLE
Unable to  pull docker images in the rootless mode  (`proxyconnect tcp: dial tcp 10.0.2.2:3128: connect: network is unreachable`)

### ISSUE THREAD

**Issue by ktdharan** [moby/moby#43630]
**Description**

After installing docker in the rootless mode, we are unable to pull images from Docker Hub 

`docker pull ubuntu
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 10.0.2.2:3128: connect: network is unreachable`

**Steps to reproduce the issue:**

1. We have set the proxy details to use in the following location 
`/local/home/<user>/.config/systemd/user/docker.service.d`

2.  The following are the contents of the  http-proxy.conf 
`[Service]
Environment="HTTP_PROXY=http://10.0.2.2:3128"
Environment="HTTPS_PROXY=http://10.0.2.2:3128"
Environment="NO_PROXY=localhost, 127.0.0.*,*."
`
3. The output of the docker service running in the rootless mode 
`docker.service - Docker Application Container Engine (Rootless)
   Loaded: loaded (/local/home/<user>/.config/systemd/user/docker.service; enabled; vendor preset: enabled)
  Drop-In: /local/home/<user>/.config/systemd/user/docker.service.d
           └─http-proxy.conf, override.conf
     Docs: https://docs.docker.com/go/rootless/
 Main PID: 1735274 (rootlesskit)
   CGroup: /user.slice/user-100.slice/user@100.service/docker.service
           ├─1735274 rootlesskit --net=slirp4netns --mtu=65521 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=slirp4netns --copy-up=/etc --copy->
           ├─1735287 /proc/self/exe --net=slirp4netns --mtu=65521 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=slirp4netns --copy-up=/etc --co>
           ├─1735301 slirp4netns --mtu 65521 -r 3 --disable-host-loopback --api-socket /tmp/rootlesskit247432169/.s4nn.sock --enable-sandbox --enable-seccomp 1735287 tap0
           ├─1735308 dockerd --iptables=false
           └─1735325 containerd --config /run/user/100/docker/containerd/containerd.toml --log-level info
`

**Describe the results you received:**

`docker pull ubuntu
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 10.0.2.2:3128: connect: network is unreachable`

**Describe the results you expected:**

Should be able to pull docker images without any issues 

**Additional information you deem important (e.g. issue happens only occasionally):**

- We are currently using the Redhat 8 Linux flavor  with the kernel version  4.18.0-348.20.1.el8_5.x86_64
- The slirp4netns version we use is as follows ->  `slirp4netns version 1.1.8
commit: d361001f495417b880f20329121e3aa431a8f90f
libslirp: 4.4.0
SLIRP_CONFIG_VERSION_MAX: 3
libseccomp: 2.5.1
`

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.15
 API version:       1.41
 Go version:        go1.17.9
 Git commit:        fd82621
 Built:             Thu May  5 13:15:49 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.15
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.9
  Git commit:       4433bf6
  Built:            Thu May  5 13:14:10 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.15
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.18.0-348.20.1.el8_5.x86_64
 Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 
 Total Memory: 
 Name: <hostname>
 Docker Root Dir: /local/home/<user>/.local/share/docker
 Debug Mode: false
 HTTP Proxy: http://10.0.2.2:3128
 HTTPS Proxy: http://10.0.2.2:3128
 No Proxy: localhost, 127.0.0.*,
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  
 Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- We use cntlm as our proxy 
- We tried using the workaround mentioned in the https://github.com/docker/docker-install/issues/150 , but it did not work for us .

**Comment by AkihiroSuda** [comment]
> the docker daemon doesn't even start

Do you get any error logs when you run `dockerd-rootless.sh` ?

**Comment by ktdharan** [comment]
@AkihiroSuda  Apologizes it looks like i also deleted  --port-driver=$DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER as well from the script  . Thank you for your support . It works now .
