### ISSUE TITLE
Swarm overlay network doesn't work when advertised over IPv6

### ISSUE THREAD

**Issue by mvforell** [moby/moby#43643]
**Description**

When creating a new swarm with an overlay network and adding standalone containers to the network, the containers cannot communicate with each other if the `docker swarm init` command received an IPv6 address as value for the `--advertise-addr` parameter. The exact same setup works if IPv4 is used instead of IPv6.

**Steps to reproduce the issue:**

These are the exact same steps as described at https://docs.docker.com/network/network-tutorial-overlay/#use-an-overlay-network-for-standalone-containers.

1. Set up the manager:
```
docker swarm init --advertise-addr $IPV6
docker network create --opt encrypted --driver overlay --attachable test_network
docker run -it --name manager --network test_network alpine
```
2. Set up the worker:
```
docker swarm join --token SWMTKN-1-31ss64p4lm5837a1tbfoaxcr9rkhjorp63qav83m6vhh6etnfm-8ks29wa50n2c09qnbqx773bol $IPV6:2377
docker run -dit --name worker --network test_network alpine
```
3. Try to ping the worker from the manager (execute in the shell that was opened by the last command from step 1):
```
ping worker
```

**Describe the results you received:**

```
$ ping worker
PING worker (10.0.1.4): 56 data bytes
^C
--- worker ping statistics ---
18 packets transmitted, 0 packets received, 100% packet loss
```

**Describe the results you expected:**

```
ping worker
PING worker (10.0.1.4): 56 data bytes
64 bytes from 10.0.1.4: seq=0 ttl=64 time=1.106 ms
64 bytes from 10.0.1.4: seq=1 ttl=64 time=0.683 ms
64 bytes from 10.0.1.4: seq=2 ttl=64 time=0.689 ms
64 bytes from 10.0.1.4: seq=3 ttl=64 time=0.646 ms
...
^C
--- worker ping statistics ---
45 packets transmitted, 45 packets received, 0% packet loss
round-trip min/avg/max = 0.590/0.717/1.414 ms
```

(This is what happens when using an IPv4 address with the `docker swarm init` command.)

**Additional information you deem important (e.g. issue happens only occasionally):**

As stated above, everything works as expected if you use an IPv4 address for advertising the swarm.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:18:18 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:16:22 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-33-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.74GiB
 Name: direktor
 ID: 5DHZ:L5K2:SNV5:FIUB:XX2N:QDNR:XD6O:TEDJ:YCWB:A2LK:IWPE:TW4J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I tested this twice: between two netcup VPS, and between two Hetzner VPS, everything on Ubuntu 22.04. Both times, I received the same results (IPv6 advertising doesn't work, IPv4 advertising does).

**Comment by mvforell** [comment]
These two issues may be related (as in they both are issues with overlay networks when using IPv6), though the details are different: #42712, #43615.

**Comment by s4ke** [comment]
Does this help? https://github.com/b-data/docker-swarm-ipv6-nftables/blob/main/NOTES.md#ipv6-connectivity

**Comment by s4ke** [comment]
Seems to be an open issue that needs to be worked around:

https://github.com/moby/moby/issues/24379#issuecomment-651771709

https://serverfault.com/questions/933211/how-to-create-docker-ingress-network-with-ipv6-support

**Comment by thaJeztah** [comment]
Yes, looks like this overlaps with the issues mentions above;

- https://github.com/moby/moby/issues/42712
- https://github.com/moby/moby/issues/43615
- https://github.com/moby/moby/issues/24379

Let me close this ticket to prevent the conversation on those diverging further, but feel free to participate on those tickets
