### ISSUE TITLE
Go SDK is too slow for no reason

### ISSUE THREAD

**Issue by synalice** [moby/moby#43706]
**Description**

I am writing a small program in Go that uses [this docker SDK for Go](https://pkg.go.dev/github.com/docker/docker/client). Right now, all it does is it creates a docker container with specific configuration (image, CMD etc.), creates whichever file you want inside it, runs this file inside a container, waits until the container is finished (or is killed due to exceeding a time limit), gathers logs from the container and then removes it.

The actual problem I run into is that all of this takes too much time. Around 4 - 5 seconds, which seems for me to be too much. My program is basically just a wrapper around docker's Go SDK. And I am very confident that the problem is somewhere with the docker's API and not my wrapper program.

**Steps to reproduce the issue:**
1. `git clone https://github.com/synalice/gobox.git`
2. `cd gobox/docker/container`
3. `go test -v container_lifecycle_test.go`

**Describe the results you received:**
```
=== RUN   TestContainerLifecycle
Hello, World!

--- PASS: TestContainerLifecycle (4.01s)
PASS
ok  	command-line-arguments	4.025s
```
The program created a container, then the file `main.py` inside it (the file that will be executed when the container starts), ran the container, gathered its logs, removed the container and printed the logs into the stdin.

**Describe the results you expected:**
I expected everything to be the same, but to take around 1 second of time. Not 4.

**Describe what you did:**
I suspect that the bottleneck is somewhere around where SDK actually communicates with the docker's API. I tried running my code with a blocking profiler and got this: https://ibb.co/r7NND2v Looking at this, it seems to me that everywhere, where the code blocks, it is because it is waiting on `select` statement for something to come from the channel. That probably means that the code blocks everywhere, where it waits for response from the docker's API. 

I have a feeling that my problem has something to do with TCP keep-alive, but I didn't manage to find any information about this

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:59 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:39 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.17
 Storage Driver: btrfs
  Build Version: Btrfs v5.18
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.17.12-300.fc36.x86_64
 Operating System: Fedora Linux 36 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 5.729GiB
 Name: fedora
 ID: XNO3:JUTM:MXZ4:NZD3:74XC:IG3M:X4AB:L2NZ:E3BN:QSV3:BP4S:JW7R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
How long does it take if you use the docker cli?

Are you sure this is running a native image and not something for another platform, and thus is bound by qemu?

What else is happening in the docker daemon?

**Comment by synalice** [comment]
> How long does it take if you use the docker cli?

Almost instantly. I created a small Dockerfile which doesn't have mounts and limits like the container created by the program, but it does pretty much the same:
```
FROM python:latest

# main.py has 1 line of code: print("Hello, Docker!")
COPY main.py /theFolder/

WORKDIR /theFolder
CMD ["python", "main.py"]
```
The results of running an image built from this Dockerfile:
```
$ time docker run test_docker_api
Hello, Docker!
docker run test_docker_api  0,03s user 0,06s system 12% cpu 0,701 total
``` 

> Are you sure this is running a native image and not something for another platform, and thus is bound by qemu?

Yes. It is 100% this [official Python image](https://hub.docker.com/_/python)

> What else is happening in the docker daemon?

Output of `journal -u dokcer` after running `docker run test_docker_api`:
`july 09 00:39:02 fedora dockerd[999]: time="2022-06-09T00:39:02.083026786+03:00" level=info msg="ignoring event" container=f85d294dea5a8c78302c817>`

I profiled my code once again now without setting any limits on the container, only setting an image, CMD and a mount in which the file is being written:
https://ibb.co/FgbNGCs

The results are still very bad:
https://ibb.co/Fb29KcS

The output into `journalctl -f` after I run my code:
https://pastebin.com/BFc3uBsJ


What else can I help?

**Comment by synalice** [comment]
The problem was that one of the methods in my code was calling `Client.ImagePull()`.

The actual problem was that _if the image actually does exist_ and you _don't need to pull it_, `Client.ImagePull()` still takes a long time to finish. At least for me, that seems to be too long for something so trivial — checking if an image is there or not.

I guess the issue can be marked as closed, although I would like to know your thoughts on this, @cpuguy83.

**Comment by cheerego** [comment]
same issue 
version:  	github.com/docker/docker v20.10.16+incompatibl


![image](https://user-images.githubusercontent.com/13394349/179361196-0edc23c1-f1a7-44a6-8bde-a0cc3f1bd9bd.png)

**Comment by thaJeztah** [comment]
```go
package repro43706

import (
	"context"
	"io"
	"testing"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)

func TestName(t *testing.T) {
	cl, err := client.NewClientWithOpts(client.FromEnv, client.WithVersion("1.41"))
	if err != nil {
		t.Fatal(err)
	}
	pull, err := cl.ImagePull(context.Background(), "golang:1.18.0-bullseye", types.ImagePullOptions{})
	if err != nil {
		t.Fatal(err)
	}
	all, err := io.ReadAll(pull)
	if err != nil {
		t.Fatal(err)
	}

	t.Log(string(all))
}
```

I tried with the code you posted and based on the v20.10.16 code, but not seeing the long delay (of course, would depend on networking as it's connecting with the registry);

```console
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/sebastiaan/go #gosetup
/usr/local/opt/go/libexec/bin/go test -c -o /private/var/folders/c_/vjh56sc12fd2b_q2n02_lt140000gn/T/GoLand/___TestName_in_github_com_docker_docker_repro43706.test github.com/docker/docker/repro43706 #gosetup
/usr/local/opt/go/libexec/bin/go tool test2json -t /private/var/folders/c_/vjh56sc12fd2b_q2n02_lt140000gn/T/GoLand/___TestName_in_github_com_docker_docker_repro43706.test -test.v -test.paniconexit0 -test.run ^\QTestName\E$
=== RUN   TestName
    repro_test.go:26: {"status":"Pulling from library/golang","id":"1.18.0-bullseye"}
        {"status":"Digest: sha256:da371518962826141d504029f0e8c27c64f57c69d2899ebf3c9a9e7afb136a10"}
        {"status":"Status: Image is up to date for golang:1.18.0-bullseye"}
        
--- PASS: TestName (1.79s)
PASS

Process finished with the exit code 0
```
