### ISSUE TITLE
access() reports file on bind mount as executable when it is not

### ISSUE THREAD

**Issue by Sjord** [moby/moby#43726]
The [access() syscall](https://linux.die.net/man/2/access) reports files on bind mounts as executable, when they are not:

```
$ touch hello.txt
$ docker run --rm -v "$PWD:/foo" -w "/foo"  python python3 -c 'import os; print(os.access("hello.txt", os.X_OK))'
True
```

The file hello.txt has default 644 permissions, so no executable bit, so I would expect access() to return false.

This is not specific to Python, I also tried it with a C program. It seems to be specific to MacOS:

I could reproduce this on:
* MacOS Docker server 20.10.7
* MacOS Docker server 20.10.16

But not on:
* Linux Docker server 20.10.12
* Linux Docker server 18.09.1

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:20:34 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.1 (81317)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 23
  Running: 0
  Paused: 0
  Stopped: 23
 Images: 10
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: JOCP:IUGQ:4KYM:ORYA:E44M:CGVK:CT34:ZXI6:XASD:CB3D:WMSZ:HNKV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
This looks like an issue specific to Docker Desktop file sharing. On Linux, bind-mounts are straight bind-mounts from the host into the container, but on macOS those paths have to cross the host <--> VM boundary, which is handled by either grpcFUSE or virtioFS; there's some known issues around ownership and permissions in some cases (e.g. https://github.com/docker/for-mac/issues/6243), and a roadmap ticket for feedback on virtioFS; https://github.com/docker/roadmap/issues/7.

Given that this is not related to the Docker Engine running on Linux (which is maintained in this repository), I'll close this ticket here, but feel free to participate on the tickets I linked to, or to open a new ticket in the Docker Desktop issue tracker (https://github.com/docker/for-mac)

**Comment by Sjord** [comment]
Thanks. I filed a new issue in docker/for-mac: [access() reports file on bind mount as executable when it is not · Issue #6367 · docker/for-mac](https://github.com/docker/for-mac/issues/6367)
