### ISSUE TITLE
incorrect accessible() implementation

### ISSUE THREAD

**Issue by setharnold** [moby/moby#43724]
https://github.com/moby/moby/blob/74286cba8c2c14d5360caec44d2da74858e9c707/pkg/idtools/idtools_unix.go#L95

```
func accessible(isOwner, isGroup bool, perms os.FileMode) bool {
	if isOwner && (perms&0100 == 0100) {
		return true
	}
	if isGroup && (perms&0010 == 0010) {
		return true
	}
	if perms&0001 == 0001 {
		return true
	}
	return false
}
```

Hello, the `accessible()` function can give incorrect results if `isOwner` or `isGroup` is true. (Well, 'incorrect' in the sense that it gives different results than Unix and Linux systems.)

The traditional implementation of discretionary access controls does NOT fall back to the wider permissions:

Consider:

```
$ mkdir owner
$ mkdir group
$ mkdir world
$ chmod 100 owner
$ chmod 010 group
$ chmod 001 world
$ cd owner/
$ cd ..
$ cd group/
bash: cd: group/: Permission denied
$ cd world/
bash: cd: world/: Permission denied
$ ls -ld owner group world
d-----x--- 2 sarnold sarnold 2 Jun 17 02:17 group
d--x------ 2 sarnold sarnold 2 Jun 17 02:17 owner
d--------x 2 sarnold sarnold 2 Jun 17 02:17 world
```

(For the ultra-curious, I strongly recommend checking out the ancient Unix source code at http://warsus.github.io/lions-/all.html ; there's a bit of complication around root getting all permissions except execution, but a very pleasing "shift the permissions right three bits" if the uid or gid don't match followed by a single test. Look for `access(aip, mode)`.)

I'm a little worried about the presence of this function at all, however; `access(2)` has been a source of security bugs in the Unix world for decades, and this implementation completely ignores the permissions on path resolution, so it's even less useful than the `access(2)` syscall provided by the Linux kernel.

How is this function used? Why?

Thanks

**Comment by corhere** [comment]
The `accessible` function is only used to implement [`idtools.CanAccess`](https://github.com/moby/moby/blob/a98bd75256122a3e386059e1a6336ee6b82aed62/pkg/idtools/idtools_unix.go#L82-L93), which itself is only used (within Moby) in one place: https://github.com/moby/moby/blob/a98bd75256122a3e386059e1a6336ee6b82aed62/daemon/daemon_unix.go#L1240-L1253
It appears that `idtools.accessible` is only being used to perform a pre-flight sanity check to provide an actionable error message, not in any security-sensitive context. And permissions on path resolution are considered, albeit on the caller side.

**Comment by hholst80** [comment]
great digging.

**Comment by thaJeztah** [comment]
Thanks @setharnold (and @corhere for spotting it's only used in that single location 😄) 

I was working on some cleaning up of the `pkg/idtools` package in https://github.com/moby/moby/pull/44254, and opened a follow-up in https://github.com/moby/moby/pull/44268 to remove this utility from that package and move it together with the code that uses it (as an un-exported function). Perhaps we can replace it altogether, but at least with that change it's no longer exported, and I added a comment to describe that it should not be use for anything other than the current use.
