### ISSUE TITLE
 open merged/etc/resolv.conf: permission denied

### ISSUE THREAD

**Issue by sunnoy** [moby/moby#43749]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
18.09.8
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

```
Jun 25 00:39:47 xxx dockerd: time="2022-06-25T00:39:47.443448045+08:00" level=error msg="Handler for POST /v1.38/containers/create returned error: open /xxx/docker/overlay2/05b660348bf5c21f2182d684a6800ce59936e0d8aabb487c0c36291172ee2df8-init/merged/etc/resolv.conf: permission denied"
```

**Comment by thaJeztah** [comment]
Docker 18.09 reached EOL 4 years ago; are you still able to reproduce this on a currently maintained version of docker?

Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sunnoy** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/19342276/176180645-741603e9-8d32-41a9-bec6-3a53a9d46209.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/19342276/176180848-1343cbcd-eb44-4671-9f69-c87806ba4a0c.png">

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/19342276/176180928-3370a4c6-ebfa-460f-8155-58b0e2431cfd.png">


docker version upgrade to 18.09.8

**Comment by sunnoy** [comment]
```
Containers: 272
 Running: 105
 Paused: 0
 Stopped: 167
Images: 78
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: N/A
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.76GiB
Name: private-docker-main
ID: QO2K:CPLP:DSKD:NRNS:SIIO:BFDE:ZB4U:AQJJ:YGMQ:AQNH:EFJN:D77F
Docker Root Dir: /mnt/xxx/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 10.31.148.164
 hub.xxx.com:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

```
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

The docker version upgrade from 1.13.1 to 18.09.8
