### ISSUE TITLE
Cannot perfom "docker load" using the go SDK.

### ISSUE THREAD

**Issue by juan0125** [moby/moby#43766]
**Question**
I want to perform "docker load -i xxx.tar.gz" using the go SDK.
But there is error as below.
{"errorDetail":{"message":"Error processing tar file(exit status 1): unexpected EOF"},"error":"Error processing tar file(exit status 1): unexpected EOF"}

**What I tried**

```
package main

import (
	"bytes"
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"helm.sh/helm/v3/pkg/action" // https://pkg.go.dev/helm.sh/helm/v3@v3.9.0/pkg/action
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/kube"
	_ "k8s.io/client-go/plugin/pkg/client/auth"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)
func main() {
cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		panic(err)
	}
	src := bytes.NewReader([]byte("/root/action/install/hello-world_latest.tar.gz"))
	imageLoadResponse, err := cli.ImageLoad(context.Background(), src, true)
	if err != nil {
		panic(err)
	}
	body, err := ioutil.ReadAll(imageLoadResponse.Body)
	fmt.Println(string(body))
}
```

Could you help me for this?

**Describe the results you expected:**
I want that my code perform command as "docker load"

**Comment by vvoland** [comment]
The `input` parameter of `ImageLoad` is an `io.Reader` which should provide the tar file content - not path to the file.
You should do something like this instead:
```go
file, err := os.Open("/root/action/install/hello-world_latest.tar.gz")
// TODO: Handle error
defer file.Close()
imageLoadResponse, err := cli.ImageLoad(context.Background(), file, true)
```

**Comment by thaJeztah** [comment]
Oh! Good catch! Completely missed a reader was used for the _filename_ not the content 😂 

As reference / example, you can also look at how the docker CLI handles this (note that the response from this endpoint is streaming, so the response may also have to be handled accordingly to get progress etc); https://github.com/docker/cli/blob/80b1285fec5409b1fe33f1f1202b041c408e7f3f/cli/command/image/load.go#L46-L81

**Comment by juan0125** [comment]
@thaJeztah , @vvoland 
I'm very appreciate for your interest.
And I did it successfully. Thank you!
