### ISSUE TITLE
Cannot set sysctl's in a host network namespace without --privileged

### ISSUE THREAD

**Issue by kaysond** [moby/moby#43769]
**Description**

[docker-ingress-routing-daemon](https://github.com/newsnowlabs/docker-ingress-routing-daemon/) is a solution to the issue of swarm obscuring packet source ips (https://github.com/moby/moby/issues/25526). We've been discussing the option of deploying this via docker swarm (see [here](https://github.com/newsnowlabs/docker-ingress-routing-daemon/issues/23)), and one of the things that has come up is the inability to set sysctls on the `ingress_sbox` network namespace inside the swarm service, because it does not yet support `--privileged` (https://github.com/moby/moby/issues/25303)

As far as I can tell, with the right cap_add's, it should theoretically be possible to set the sysctls, but it seems to be thwarted by the fact that docker mounts `/proc/sys` as read-only inside containers. Unmounting it to expose the parent `/proc` mount, which is rw, doesn't help because then you get a permission denied. 

Is there a way to tell a docker service not to protect `/proc/sys` without using `--privileged` (which isnt supported)?

Alternatively, are there any current plans to add `--privileged` support to `docker service create`? https://github.com/moby/swarmkit/pull/1722 was closed for https://github.com/moby/moby/issues/32801, but that seems to be dead.

**Comment by thaJeztah** [comment]
./cc @evol262 @dperny

**Comment by kaysond** [comment]
> Effectively, this looks to be "use a service to re-configure the host machine"? Wondering; would that be more something for a provisioning script that runs when creating the node

Sort of. It's not really changing the host machine. It's configuring sysctl in docker's `ingress_sbox` namespace only, so its directly relevant to the swarm in a way that I think warrants making the change from within a container. Without the settings being correct in that namespace, the routing performance is significantly degraded.

Haven't tried the workaround yet since I'm hoping for something cleaner.

Does that mean its not possible otherwise?

**Comment by thaJeztah** [comment]
@evol262 would this be possible when creating a custom ingress network? (https://github.com/moby/moby/pull/31714)

**Comment by kaysond** [comment]
So I guess our best bet is still `docker service create --privileged` then? Is there anything blocking this add? Or is it just a matter of a resource to actually do it?

**Comment by kaysond** [comment]
Got it! Thanks for the discussion.
