### ISSUE TITLE
Make it possible to specify parameters for 'docker-init'

### ISSUE THREAD

**Issue by dark-penguin** [moby/moby#43776]
Please correct me if this is possible, but I couldn't find a way to pass command-line arguments to `docker-init`.

As we know, it was originally `tini`, which supports commandline parameters. One important parameter is `-g`, which enables the behavior that's basically the reason for its existence: being able to stop containers by sending signals to all processes. The same way a shell sends SIGINT to the whole process group, and the same way SIGTERM is sent to all processes before system shutdown.

I could not find a way to run a container in this mode.

- You could try doing `ENTRYPOINT [ "docker-init", "-g", "/my/entrypoint.sh" ]`, but in this case, you get a docker-init as PID1 running another docker-init NOT as PID1 and complaining that "Tini (I thought it was docker-init now?!) is running as not-PID-1".
- You could try installing Tini into the container, then run without `--init`... but we already have docker-init specifically to avoid doing this.

Ideally, I see this being just another option to `docker run`: maybe `--init-g`, or even simply `--init -g` since `-g` is currently unused.

**Comment by corhere** [comment]
> You could try installing Tini into the container, then run without --init... but we already have docker-init specifically to avoid doing this.

Installing Tini into the container image is the right answer. That way you control the exact version of tini used, without any chance of it changing from under you—and possibly changing its behaviour or the meanings of the command-line flags.

The `docker run --init` flag is provided to work around broken container images which should have included their own init. It is not standardized and is not available on Kubernetes. And the specifics of which init binary are projected into the container depends on the host's configuration, which negates the host-isolation benefit of containers. The kind of init projected into the container as `docker-init` is not defined and is subject to change. While it may be a copy of `tini` on your installation, someone else's install could e.g. have `{"init-path": "/sbin/dumb-init"}` in their /etc/docker/daemon.json. `dumb-init`, for instance, does not understand the `-g` flag so passing that flag would break container startup on systems configured to use `dumb-init` as its `docker-init`. We therefore cannot safely assume that `docker-init` can accept _any_ command-line flags.

Did you know? Tini supports some configuration through environment variables in addition to command-line flags. The relevance of this fact to the current topic is left as an exercise to the reader. Just remember: assume `docker-init` is `tini` at your own peril as there is no guarantee it will be.

**Comment by dark-penguin** [comment]
Actually, this makes sense. Install tini yourself, and use it as the entrypoint, the rest of things remaining the same. It's not really a big problem to do this, and it makes things more "stable" and obvious. Thanks.
