### ISSUE TITLE
containerd integration: make sure images are sorted, and optimize before/since filters

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#43848]
### Description

- relates to https://github.com/moby/moby/pull/43816

The previous implementation sorted the results by "created" (descending order); https://github.com/moby/moby/blob/7624f8aeb1836cd75a0912d9614930e8a59eaf4e/daemon/images/image_list.go#L241

We can either sort locally, or possibly optimize and have containerd return the result in sorted order.

When sorting the results, we can also optimize the `before` and `since` filters to break the loop if we're reaching a certain "created" date.

**Comment by tianon** [comment]
As far as things containerd supports here, it _does_ support some amount of string-based filtering (`name=="foo"`) that we might be able to use to optimize some limited set of our filters, but doesn't appear to natively support any sorting or ordering today.
