### ISSUE TITLE
setcap in dockerfile not persistent in parent dockerfile

### ISSUE THREAD

**Issue by zffocussss** [moby/moby#43856]
### Description

setcap +options on base parent Dockerfile.but it works in the child(app) Dockerfile.why?

### Reproduce

1. make a parent Dockerfile ,including setcap +op  executable file
2. make a child Dockerfile ,including setcap +op  executable file instead

### docker version

```bash
I do not know.I am using public cloud K8s Cluster
```

### docker info

```bash
I do not know.I am using public cloud K8s Cluster
```

### Additional Info

Alibaba Kubernetes service

**Comment by olljanat** [comment]
I'm not sure what you mean with parent and child Dockerfiles. Can you share full examples?

**Comment by corhere** [comment]
_Possibly_ related?
- https://github.com/moby/moby/issues/20435

**Comment by bsousaa** [comment]
We are closing this issue as it looks like it is stale.
