### ISSUE TITLE
containerd integration: add support for image delete using image (short)ID

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#43854]
### Description

- relates to https://github.com/moby/moby/pull/43820

The existing implementation of image delete allows images to be referenced by their (local) ID or short ID; 
https://github.com/moby/moby/blob/b94f7157cae2b5d8943513e96ddfbaa744606c56/daemon/images/image_delete.go#L77-L84

see https://github.com/moby/moby/pull/43820#discussion_r926998019

**Comment by 26tanishabanik** [comment]
@thaJeztah , can I work on this?

**Comment by laurazard** [comment]
Closing since this was addressed by https://github.com/moby/moby/pull/45362
