### ISSUE TITLE
Golang SDK SSH Forwarding

### ISSUE THREAD

**Issue by tdenmon** [moby/moby#43869]
## Background

The docker cli allows for SSH forwarding through use of the `--ssh` argument, most notably in the case of `--ssh=default` to tell the docker daemon to use the default SSH config for satisfying things like pulling private git repositories inside of a Dockerfile.

However, it appears that the Golang SDK does not offer this same functionality. This is valuable for organizations with a lot of private repositories looking to pull those in at build time in a CI pipeline, and the disparity between the cli and SDK means that managing docker via Go code (which offers better maintainability and testing than something like a shell script) is only possible for more basic Dockerfiles.

## Feature Request

Add a build option to allow for SSH forwarding when building images using the Golang SDK. Alternatively, if I'm wrong and this functionality *does* exist but is not well documented then simply add better documentation for supplying this option.

**Comment by cpuguy83** [comment]
You are right, this is not in the main `client` SDK in this repo.
However the CLI really doesn't have any special magic, it's calling the same API's as you.

https://github.com/docker/cli/blob/v20.10.17/cli/command/image/build_buildkit.go

Building with buildkit is not a straight forward http `POST -> response`.
It sets up a session where the client and server communication is bi-directional, the ssh agent is forwarded over this session.
If you look at the above link you'll see how this is setup.

**Comment by tdenmon** [comment]
Ah, I see. So the issue is that the client from the SDK is configured as a typical REST-style API client while buildkit is expecting a session, and bridging that gap would require a lot of refactoring.

I'll look into alternate ways of making this work. Thanks for the link to how the cli is doing this!
