### ISSUE TITLE
Recover a container which exits immediately on startup

### ISSUE THREAD

**Issue by corhere** [moby/moby#43879]
### Description

A member of the Docker Community Slack, Ganesh Santosh Naik, [got their container into a bad state.](https://dockercommunity.slack.com/archives/C7GKACWDV/p1659007884345169)
> Hi Team,
>
> we had sonarqube running as container in ubuntu server. edited the sonar.properties file by using docker exec, to connect to postgresdb.
> after docker container restart the container exited due to the Bad format of JDBC URL.
> Is it possible to edit the file again and get the container started?

For a user who treats containers as disposable, this would not be an issue as they would simply delete the container and create a new one with the corrected configuration. But not all containers are disposable. A user has little hope of recovering a "pet" container which has gotten into an unbootable state. If they're lucky and the bad state is in a volume, they can mount the volume into a different container to fix it. But volumes cannot be mounted to existing containers, so they are out of luck if the bad state is in the container's rootfs.

- `docker exec` is not permitted on stopped containers.
- The entrypoint and command line of a container cannot be updated.
- A container's rootfs cannot be mounted into another container.

A user with an unbootable operating system on a physical or virtual machine has some options for getting access and attempting recovery. They could try booting the OS into single-user mode, or they could boot into another OS and mount the filesystem. Could we add some analogous feature to Moby? E.g.:
- Support `docker exec` into a stopped container. https://github.com/moby/moby/issues/30361
- Allow the entrypoint and/or command to be overridden for a single `docker start`.
- Support mounting a stopped container's rootfs as a volume on another container.

**Comment by thaJeztah** [comment]
- `docker cp` would probably still work, as it can act on stopped containers?
- `docker commit` can still work (if the files are in the container's filesystem) which would allow for the container to be committed as an image (and ran with a different command for debugging)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
