### ISSUE TITLE
Daemon.json : Log rotating options (log-opts) are ignored (don't work)

### ISSUE THREAD

**Issue by frenzymind** [moby/moby#43931]
### Description

I have daemon.json file:
```
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "30m",
    "max-file": "10"
  }
}
```

But log rotation is not work. *-json.log file grows with no limit until disk space is depleted.
For the same time if I write these options to docker-compose.yml file for a container - it works perfect.

### Reproduce

1. Create file /etc/docker/daemon.json
2. Write down:
```
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "30m",
    "max-file": "10"
  }
}
```
3. run the command: `systemctl restart docker.service` or reboot system.
4. Checking logs after some period of time.

### Expected behavior

It is expected to see log rotated files like this:
47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log    47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.5  
47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.1  47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.6  
47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.2  47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.7  
47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.3  47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.8  
47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.4  47e66a97b04b209179c5d951d9c449755534277e7bc1295868983b7ecd1c97ec-json.log.9  

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-14-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.802GiB
 Name: dns1
 ID: UNAY:VNAD:SLOT:BD7E:5HMP:NOH5:ZY7X:ZF2Z:X3OZ:OTHZ:F4WD:OLCM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by vvoland** [comment]
Changing the logger driver settings impacts only the newly created containers and not already existing ones.
Did you recreate the containers after changing the driver configuration?

**Comment by frenzymind** [comment]
> Changing the logger driver settings impacts only the newly created containers and not already existing ones. Did you recreate the containers after changing the driver configuration?
I am totally sure I am reboot the server. Is it should enough? 
In Docker version 20.10.2, build 2291f61  this problem is absent.

**Comment by vvoland** [comment]
No, restarting the daemon/rebooting the server does apply the change to the daemon, which affects only the newly created containers AFTER the change has been applied.
Logging configuration of existing containers is not affected - they still have the old configuration.
You must remove the containers and create them again.

**Comment by frenzymind** [comment]
> You must remove the containers and create them again.

Ok, I try this one tomorrow and write result here.

**Comment by frenzymind** [comment]
Recreating containers solve the issue, sorry, was my fault. Thanks @vvoland 
So, pay attention for `CREATED` column in `docker ps` output to make sure container was recreated.
If you use `restart: always` policy, then manually run `docker compose down`, because it keeps containers even after rebooting the host system.
