### ISSUE TITLE
Add support for option --stream=stdout|stderr for docker logs and docker service logs command

### ISSUE THREAD

**Issue by mcordova1967** [moby/moby#43989]
### Description

It would be very nice to have a docker-native way to filter logs by the stream, either by container or service, the stream is being saved on each log record (json and local at least), so I see no limitation for this, it just feels natural to have such an option.

Regards.

**Comment by vvoland** [comment]
The Moby API already supports this.
I see you already opened an issue in the cli repository (https://github.com/docker/cli/issues/3745). So let's close this one and keep the discussion in the cli issue.
