### ISSUE TITLE
VirtioFS chown not changing owner

### ISSUE THREAD

**Issue by marcpawl-arista** [moby/moby#44012]
### Description

I have an ENTRYPOINT program that chown's a mounted volume.  The test case that checks that the container has changed the ownership fails when VirtioFS is enabled, but passes with it disabled.  The test passes with or without the new virtualization framework enabled.

### Reproduce

0.  Mac M1
1.  Build image that has an entrypoint a setuid program that will chown a directory the the user and group of the process that the container is running as.  Use ubuntu:focal as base.
2.  docker run -e DIR=/build -v $(PWD):/build -u $(id -u):$(id -g) myimage ls -l --recursive /build
Entry point program creates a user with the UID, chowns DIR, and executes the ls command.

### Expected behavior

Expected is that the files ownership has been changed.
Actual is that the files are still owned by root.

### docker version

```bash
marcpawl@Marcs-MacBook-Pro fl-builder % docker version
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 122
  Running: 0
  Paused: 0
  Stopped: 122
 Images: 9
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 969.5MiB
 Name: docker-desktop
 ID: OTTH:D7QP:7Q4S:GZDB:T4WP:L2GX:6ZKI:M5PT:LV4F:DFX3:4237:OHZV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  localhost:5000
  127.0.0.0/8
 Registry Mirrors:
  https://docker.cache.eng.bigswitch.com/
 Live Restore Enabled: false
```

### Additional Info

Docker Desktop 4.11.1 (84025) is currently the newest version available.

Darwin XXXX 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

**Comment by thaJeztah** [comment]
This looks to be specific to Docker  Desktop, which is not maintained in this repository; perhaps you can open a ticket in the Docker Desktop issue tracker instead (if there's no existing ticket for this; I think there may be some already); https://github.com/docker/for-mac/issues

I'm closing this ticket here, because of the above, but feel free to continue the conversation 👍

**Comment by marcpawl-arista** [comment]
Similar to https://github.com/docker/for-mac/issues/6298 https://github.com/docker/for-mac/issues/6239
