### ISSUE TITLE
same IP for two containers in bridge

### ISSUE THREAD

**Issue by karniemi** [moby/moby#44010]
### Description

We've been using docker in CI environment for a long time, running tens of builds per day. Last week we had an occurrence in which two containers had the same IP, which of course broke the build.

The CI runs these steps:
* cleanup:
  * removes all old containers
  * runs "docker system prune -f"
  * as a workarrund for docker/cli/issues/1891, restarts dockerd if there are any hanging containers in the network ( was not restarted for the test round in which two containers got the same IP)
* then starts a new test rounds
  * create network
  * start ~100 containers using a few docker-compose files

The problem:
* some of the services did not come up properly, and there seemed to be some sort of networking issue between the containers
* our services that are running in jvm inside the containers find out IP using `localHost = InetAddress.getLocalHost();` and print it out on a log
* now, two containers logged their IP as : 192.168.16.40, which made them uncapable of communicating properly with other containers of the system

In messages-log of the host, we could see a lot of these:
```
messages-20220820:Aug 19 12:16:51 be-builder-3 kernel: IPv4: martian source 192.168.16.90 from 192.168.16.39, on dev eth0
messages-20220820:Aug 19 12:17:03 be-builder-3 kernel: IPv4: martian source 192.168.16.10 from 192.168.16.40, on dev eth0
```
* these message were logged for 192.168.16.39 and 192.168.16.40. But to us it seemed that only the containers that had IP:192.168.16.40 had trouble communicating with other containers. There was only one container using the IP:192.168.16.39, as far as we could see ( all containers don't log their IP, so we are not 100% sure of it.)

Analysis:
* I tried seeing other similar tickets: they were very old and supposed to be fixed already
* I tried reading the codebase and architecture, I could not figure out if the problem would be in:
  * ipam: which decides(?) the IP from the pool: would it be possible that it pops the same IP for two containers?
  * naming service: would it be possible that the problem is in docker internal naming service, because our code is effectively resolving the ip from naming service. Is there some old name-IP association hanging? Is it possible that our code does the name resolution before docker has added/updated the name in it's naming service?
  * could it be that the correctly decided IP gets later changed when passed to container creation and/or naming service, when creating tens of containers at the same moment
* unfortunately, by default there does not seem to be any logging for the IP-reservation in docker(?)
* we've only noticed this one time now, so it is very infrequent  - which will make troubelshooting more difficult
* it is probably a race condition when stopping/removing and then creating/starting lots of containers
* there would be a newer docker-package for rhel7, but it does not seem to have any updates on libnetwork:
  * https://git.centos.org/rpms/docker/c/f47bc1e86e7e91cfeea4c1c21bc924afec387882?branch=f47bc1e86e7e91cfeea4c1c21bc924afec387882

### Reproduce

Reproduction steps not known. 

### docker version

```bash
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64
 Experimental:    false
```

### docker info

```bash
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1160.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 45.04 GiB
Name: be-builder-3
ID: 7WTA:N2VF:PTFH:RYDA:QHZU:ORSZ:MMZS:A3BO:VNS2:KWTT:OCA4:QPE7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), registry.redhat.io (secure), docker.io (secure), docker.io (secure)
```

### Additional Info

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1160.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 45.04 GiB
Name: be-builder-3
ID: 7WTA:N2VF:PTFH:RYDA:QHZU:ORSZ:MMZS:A3BO:VNS2:KWTT:OCA4:QPE7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), registry.redhat.io (secure), docker.io (secure), docker.io (secure)

**Comment by karniemi** [comment]
Fixed a few typing errors

**Comment by thaJeztah** [comment]
It looks like you're running the Red Hat fork of Docker, which is based on an [EOL version of Docker from 2017](https://github.com/moby/moby/releases/v1.13.1), and contains a lot of modifications to the upstream that are not in this repository.

If you have a test-environment in which you can reproduce the issue; are you still able to reproduce this on a current release of docker using the official packages? (we don't have separate RHEL packages, but the CentOS 7 packages should match; https://docs.docker.com/engine/install/centos/)

If you cannot switch to using the official Docker packages, I recommend opening a support ticket with Red Hat, who's maintaining that fork.

**Comment by karniemi** [comment]
@thaJeztah OK thanks, I was afraid of this. Let's close the ticket, I'll need to decide how to go on with all the options I have( live with it, switch to docker-ce, switch to Ubuntu, contact Red Hat, ...). I have dealt with RH support with other issues before and I rather save my precious time.

I'll be back, if this happens again with an up-to-date version.
