### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [moby/moby#44056]
### Description

We were trying to update the `go.mod` of github.com/okteto/okteto and we have incompatibilities between [docker/libnetwork](https://github.com/docker/libnetwork) and [docker/docker](https://github.com/moby/moby). We've seen that `libnetwork` is not used anymore in `master`, and that solves our issue ❤️ .

When will the next patch release be out? Is there something I can do to help?

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/releases/tag/v23.0.0
