### ISSUE TITLE
Backslashes in X-Registry-Auth credentials must be escaped

### ISSUE THREAD

**Issue by BenasB** [moby/moby#44064]
### Description

Hi, I was following the [authentication API documentation](https://docs.docker.com/engine/api/v1.40/#section/Authentication) when trying to pull an image from a private docker registry (it's actually in [artifactory](https://www.jfrog.com/confluence/display/JFROG/Docker+Registry)). I base64url encode my personal credentials JSON object and add it in the `X-Registry-Auth` header when sending a request to pull an image (e. g. `/images/create?fromImage=my-registry.artifactory%2Fmy-image%3Alatest`) – everything works as expected, I am able to pull the image.

However, in production environment, we don't use personal credentials and instead we have service accounts which get assigned a random password according to some corporate password policy. So I give the service account access to my registry and follow the same steps I did with my personal credentials – it does not let me pull the image. Turns out that the service account password contains a backslash `\`. I have no knowledge of what's happening on the registry side, but I'm guessing it fails to correctly parse the JSON object, as it encounters a backslash and expects something to be escaped (the following character of the password was not a valid escape character). The solution to this problem is to **add an additional backslash in front of any "real" backslash characters**.

Thinking about it more, this does make sense from the JSON parsing side, however I expected that you just put in your password and it gets interpreted literally.

I am not sure if this issue calls upon any changes but it would be nice to have it documented (at least we'll have this issue page).

### Reproduce

1. Base64url encode your JSON credential object containing a backslash: `{"username":"my-service-account","password":"myse\cretpassword","email":"","serveraddress":"my-registry.artifactory"}`
2. Pull an image from your private registry by POSTing to `/images/create?fromImage=my-registry.artifactory%2Fmy-image%3Alatest` and including header `X-Registry-Auth` with value from step 1.

Workaround:
In step 1 add additional backslashes to your real credentials:  `{"username":"my-service-account","password":"myse\\cretpassword","email":"","serveraddress":"my-registry.artifactory"}`

### Expected behavior

You are able to pull the image by supplying your real credentials containing backslashes (without modifying them by adding additional backslashes)

### docker version

```bash
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker info

```bash
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.71.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.638GiB
 Name: <my-corporate-VM-hostname> (redacted)
 ID: FXTL:ZY4P:QSAO:WEYX:B2ZJ:ZLOT:NAQZ:CLBT:DAVL:ECNT:ZOU5:2VD6
 Docker Root Dir: /datadisk
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  <my-corporate-docker-registry-1> (redacted)
  <my-corporate-docker-registry-2> (redacted)
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

At first thought this was related to https://github.com/moby/moby/issues/41570

**Comment by thaJeztah** [comment]
> Base64url encode your JSON credential object containing a backslash

Where does that JSON come from? The issue there is indeed that the JSON looks to be invalid (`\` must be escaped if it's meant to be a literal backslash).

**Comment by BenasB** [comment]
The JSON object comes from the [Docker API docs](https://docs.docker.com/engine/api/v1.40/#section/Authentication)
```JSON
{
  "username": "string",
  "password": "string",
  "email": "string",
  "serveraddress": "string"
}
```
I just put in my values that I use to authenticate to my private registry. As I noted earlier, this may not be something that needs fixing, but more so others are aware that their credentials need escaping (as it was in my case when I had a password with a backslash)

**Comment by thaJeztah** [comment]
> but more so others are aware that their credentials need escaping (as it was in my case when I had a password with a backslash)

Perhaps a mention "make sure the JSON is valid" could be added.

That said, I generally try to avoid too much details on such things, as it's easy to go down the rabbit hole of explaining how to write JSON, YAML, or make a HTTP request 😅

**Comment by BenasB** [comment]
That makes sense, it's more of a misunderstanding on my part. Let this issue be the disclaimer for others in the future and I'm closing this, thanks!
