### ISSUE TITLE
manifest versioned with SHA256

### ISSUE THREAD

**Issue by marcpawl-arista** [moby/moby#44144]
### Description

I would like to see that a manifest is versioned with its own sha256, which can be used to reference the manifest.  In a manner that is similar to how images can be referenced.

**Comment by marcpawl-arista** [comment]
For an image I can use the sha256

    % docker run   ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16 uname -a
    Linux 1da9b6ee91fe 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022     aarch64 aarch64 aarch64 GNU/Linux
    % 

Using a sha256 in build scripts fixes the version, so if the new version replaces the previous version using the same tag, e.g. ubuntu:focal, my build does not change.


I would like to do the same thing with a manifest.


I can see the sha256 for an image, but cannot do so for a manifest.

marcpawl@Marcs-MacBook-Pro fl-builder % docker images ubuntu:focal
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
ubuntu       focal     bdbe84df0b98   13 days ago   65.6MB

marcpawl@Marcs-MacBook-Pro fl-builder % docker inspect  ubuntu:focal 
[
    {
        "Id": "sha256:bdbe84df0b988965129e5189bae37e09e29d17d090cf4b8c8cb8dabf2443fd77",
        "RepoTags": [
            "ubuntu:20.04",
            "ubuntu:focal"
        ],
        "RepoDigests": [
            "ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16"
        ],
        ...
        "Architecture": "arm64",
....

**Comment by cpuguy83** [comment]
Aha. So right now Docker does not store manifests (well... it's complicated... it was hacked it in to get manifest caching to help with docker hub rate limiting).

The state of this is... tricky.
Docker recreates manifests when it pushes, and the manifest digest may actually change when doing this.

We are working on this, namely to from the old image handling code and using containerd instead which will give us things like stable manifest digests, at which point we should be able to return that on the api.

**Comment by marcpawl-arista** [comment]
Having the SHA256 change when a new manifest is pushed is what I would expect.  The SHA256 should be a snapshot of the manifest at a point of time, with the underlying images being in the snapshot.  If the manifest has any timestamps like when last created, pushed, ..., then it would only be normal that the SHA256 changes.  As long as it does not change when pulled.

What I am thinking is the equivalent to the SHA256 is the real manifest, and the name, e.g.  ubuntu:focal, is just a pointer to the SHA256.

**Comment by thaJeztah** [comment]
> I can see the sha256 for an image, but cannot do so for a manifest.

So the digest shown in docker (`docker image ls --digests`) can be _either_ the digest of an image or the digests of an image manifest.

When you `docker pull <some image>`, the docker daemon resolves `<some image>`; if that image is a manifest _index_ ("multi-arch image"), then that's what's shown; if it's an image _manifest_ ("single arch image"), then that's what's shown. The difference is that in the manifest _index_ (multi-arch) case, the engine will resolve the manifest, pull it, and then pick the image from the list that matches the machine's platform (or the platform passed through `--platform`).

For example, here's what's resolved as digest for `ubuntu:focal`, whch is a manifest-list;

```bash
docker buildx imagetools inspect ubuntu:focal
Name:      docker.io/library/ubuntu:focal
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16

Manifests:
  Name:      docker.io/library/ubuntu:focal@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      docker.io/library/ubuntu:focal@sha256:d23aa8e657602b0991be01bc98845f0039044e0274be15e0cff1ae330ab013b8
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7

  Name:      docker.io/library/ubuntu:focal@sha256:b18dbe0837fd555c7028af6a1281ffa4fd1b5ffd835968f1009fd4cf9dfeaec3
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64/v8

  Name:      docker.io/library/ubuntu:focal@sha256:189ed3d4e1b2d68cb23cddd5b25351c45e0cf734f96cfe6faeb7502e5339b617
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le

  Name:      docker.io/library/ubuntu:focal@sha256:e75cfa7ef5d58be253efa7d0fd4e027453d426734953dd39dd0d195705180855
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/riscv64

  Name:      docker.io/library/ubuntu:focal@sha256:79b29fd5d282f6fa2b03eb47235ab8aaaf1c360d7ebcfb82ba3af8a6eb52eebe
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```

When pulling the image, you'll see the digest of the manifest-index (`sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16`) is printed, as that's what was resolved to, even though in this case only the `linux/amd64` was pulled;

```bash
docker pull ubuntu:focal
focal: Pulling from library/ubuntu
675920708c8b: Pull complete
Digest: sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
Status: Downloaded newer image for ubuntu:focal
docker.io/library/ubuntu:focal
```

`docker image inspect` also includes a reference to that digest;

```bash
docker image inspect ubuntu:focal
[
    {
        "Id": "sha256:a0ce5a295b637a10bc329ded296a0c895e5e56e7c5e674188d423e213b0d213e",
        "RepoTags": [
            "ubuntu:focal"
        ],
        "RepoDigests": [
            "ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16"
        ],
        ...
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 72776031,
```

The _Id_ that's stored is the digest of the image's _config_, which can be found when looking at the image manifest for the `linux/amd64` variant;

```bash
docker buildx imagetools inspect --raw docker.io/library/ubuntu:focal@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1463,
      "digest": "sha256:a0ce5a295b637a10bc329ded296a0c895e5e56e7c5e674188d423e213b0d213e"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 28572685,
         "digest": "sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f"
      }
   ]
}
```

If I would pull a different variant (arm64) from the same manifest (I'm deleting the image first as a workaround for https://github.com/moby/moby/issues/43188)

```bash
docker image rm ubuntu:focal

docker image pull --platform=linux/arm64/v8 docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16: Pulling from library/ubuntu
Digest: sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
Status: Downloaded newer image for ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
```

After that you'll find the same digest referenced in the image (digest of the manifest), but the ID refers to the image config of this specific variant (arm64);

```bash
docker image inspect docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
[
    {
        "Id": "sha256:bdbe84df0b988965129e5189bae37e09e29d17d090cf4b8c8cb8dabf2443fd77",
        "RepoTags": [],
        "RepoDigests": [
            "ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16"
        ],
        ...
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
        "Size": 65649073,
```

So, as I mentioned at the start, the digest can be "either". For example, if instead of resolving the manifest _index_ (and let the docker daemon pick the variant), I would manually pull a specific variant, for example, the `linux/amd64` variant from the index;

```bash
docker image pull docker.io/library/ubuntu:focal@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
docker.io/library/ubuntu@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db: Pulling from library/ubuntu
675920708c8b: Pull complete
Digest: sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
Status: Downloaded newer image for ubuntu@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
docker.io/library/ubuntu:focal@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
```

In this case, the digest shown is the digest of the _image_ variant;

```bash
docker image ls --digests
REPOSITORY   TAG       DIGEST                                                                    IMAGE ID       CREATED       SIZE
ubuntu       <none>    sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16   bdbe84df0b98   3 weeks ago   65.6MB
ubuntu       <none>    sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db   a0ce5a295b63   3 weeks ago   72.8MB
```

The Id of the image is the same as the first example (`a0ce5a295b637a10bc329ded296a0c895e5e56e7c5e674188d423e213b0d213e`), but this time the `RepoDigests` shows the digest of the image (not the index);

```bash
docker image inspect docker.io/library/ubuntu:focal@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db
[
    {
        "Id": "sha256:a0ce5a295b637a10bc329ded296a0c895e5e56e7c5e674188d423e213b0d213e",
        "RepoTags": [],
        "RepoDigests": [
            "ubuntu@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db"
        ],
```

**Comment by marcpawl-arista** [comment]
Can you pull/run by the SHA of the manifest?  That is what I am trying to get to.  The use case is similar to an image, record the SHA of the image in source control and use that SHA in the docker run command.  I was looking to do the same with manifests, record the SHA and use it in the docker run statement.

**Comment by thaJeztah** [comment]
Yes, you can; see the digest of the manifest I mentioned in my earlier comment;

```bash
docker image pull ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16: Pulling from library/ubuntu
675920708c8b: Pull complete
Digest: sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
Status: Downloaded newer image for ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
docker.io/library/ubuntu@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16
```

The above;

- pulls the manifest-index
- selects the host's platform from the manifest list
- pulls the image manifest, config, and layer(s) for that platform

**Comment by thaJeztah** [comment]
https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier
