### ISSUE TITLE
when I use "userns-remap" in daemon.json AND "--userns=host" at the same time, "userns-remap" don't take effect

### ISSUE THREAD

**Issue by zzyyzte** [moby/moby#44156]
### Description

When "--userns=host" is used, the owner of the processes in the container is root on host. The user namespace in container is the host's user namespace. This means the "userns-remap" didn't work. The user in container is root(this root user is the host root user), but the container rootfs belongs to the mapped user.

Is this reasonable? Whether it is forbidden to use "--usesrns=host" when "userns-remap" is used?

### Reproduce

1. docker run -id --name host --rm --userns=host busybox sleep 1000
2. ps -ef | grep sleep
root      245910  245897  0 20:40 ?        00:00:00 sleep 1000
3. docker exec -it host ls -ld /
drwxr-xr-x    1 165536   165536        4096 Sep 20 16:13 /

### Expected behavior

"--userns=host" should not be used when using "userns-remap" at the same time.

### docker version

```bash
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086349
 Built:             Thu Mar 24 17:14:32 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 17:15:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-47-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.51GiB
 Name: ubuntu-Desktop
 ID: Q5ZX:ZBXC:AETP:M3NB:OD7V:YKQ6:MCUA:O4WR:CZ4X:G3DX:RBDA:PSX7
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
This looks like the intended behaviour; the `--userns=host` option was added to allow running a privileged, non-remapped, container if the daemon has user-namespaces enabled; see the pull-request that implemented it; https://github.com/moby/moby/pull/20111

And the "Disable namespace remapping for a container" in the documentation https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container

**Comment by thaJeztah** [comment]
Let me close this ticket, as this doesn't look like a bug, but feel free to continue the converesation
