### ISSUE TITLE
Support for loading OCI images, reopen of #25779

### ISSUE THREAD

**Issue by pkit** [moby/moby#44162]
### Description

See #25779
Nothing changed since 2016, a lot of "related" issues were open (#38738, #33355) which do stuff that wasn't even considered in the original one.
The feature request is simple:
```
docker load -i oci.tar
```
Do you need help implementing it?

**Comment by AkihiroSuda** [comment]
Implemented in:
- https://github.com/moby/moby/pull/43822

**Comment by pkit** [comment]
Not sure I follow, why "containerd integration" is needed for `load`?

**Comment by sam-thibault** [comment]
#25779 is still open, so I will close this issue to keep the conversation from diverging.
