### ISSUE TITLE
Support for cfs burst 

### ISSUE THREAD

**Issue by pretentious7** [moby/moby#44204]
### Description

Currently, CPU resources can be allocated via `cpu_shares` for relative weighting, `cpu_quota` for absolute limiting. the kernel also provides for a 'burst' limiter, whereby a cgroup can burst momentarily in expectation of future underuse of allocated CPU (https://docs.kernel.org/scheduler/sched-bwc.html). 

It'd be nice to see this exposed in docker.

**Comment by kaffarell** [comment]
This issue regards runc (https://github.com/opencontainers/runc) not moby.

**Comment by pretentious7** [comment]
Yes, thank you!
