### ISSUE TITLE
Proposal: Restrict network access from specific IP addresses

### ISSUE THREAD

**Issue by uniuuu** [moby/moby#44270]
### Description

For security reasons, it could be useful to only allow a network's access from outside to a specific list of IP addresses. That requires iptables rules.

`docker network create --internal --allow=1.1.1.1,1.1.1.2`

Reference:
1. https://github.com/docker/compose/issues/3659
2. https://serverfault.com/questions/704643/steps-for-limiting-outside-connections-to-docker-container-with-iptables

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
