### ISSUE TITLE
Workflows for testing on Microsoft Windows

### ISSUE THREAD

**Issue by rmyorston** [moby/moby#44298]
### Description

I see that moby uses [busybox-w32](https://github.com/rmyorston/busybox-w32) to perform tests on Microsoft Windows. Downloads of the required busybox-w32 binaries from my [website](https://frippery.org/files/busybox) have increased substantially over the past few months. They now account for over 75% of download bandwidth, with most of that occurring between 10:00-11:00 UTC when the windows-2019 workflow is scheduled to run.

Some suggestions:
- Don't ship the windows-2019 workflow with the scheduled run enabled. Although GitHub ask users to understand the consequences of enabling workflows I'm sure many don't realise that windows-2019 will be run every day.
- Review the workflows to determine if it's really necessary to download busybox-w32 fourteen times on every run.
- Bundle the BusyBox binary.
- Use a caching server. The [Julia](https://github.com/JuliaLang/julia) project also uses busybox-w32 for testing. They direct their downloads to a caching server on their own infrastructure, only falling back to my website if that fails.
- Use something other than busybox-w32 to provide Unix-like utilities on Microsoft Windows.

Also, please note that [contrib/busybox/Dockerfile](https://github.com/moby/moby/blob/master/contrib/busybox/Dockerfile) is configured to use version FRP-3329-gcf0fa4d13 of busybox-w32. This is now the oldest binary on the website. It will be removed when it turns three years old on 9th January 2023. Switching to a more recent version before then is recommended.

**Comment by sam-thibault** [comment]
@rmyorston Thank you for reporting this issue, and sorry for the trouble. We believe this issue is fixed, and you should no longer see these downloads from the scheduled runs.
