### ISSUE TITLE
dockerd-rootless-setup.sh does not work when usernames contain a backslash

### ISSUE THREAD

**Issue by jmrouet** [moby/moby#44396]
### Description

In case of a linux host with ActiveDirectory users (winbind) names configured as DOMAIN\user, the dockerd-rootless-setup.sh script will fail when using '$(id -un)' inside a regex

I propose to replace $(id -un) occurrencies with $username defined as:
username=$(id -un | sed 's/\\/\\\\/g')

### Reproduce

1. have a host with active directory setup and a user logged as MYDOMAIN\myuser
2. run dockerd-rootless-setup.sh check or dockerd-rootless-setup.sh install
3. docker rootless will fail to install

### Expected behavior

docker should install correctly

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

### Additional Info

I created a PR fixing this isue here

https://github.com/moby/moby/pull/44395

It's my first PR in this repo so let me know if I did something wrong.

**Comment by tianon** [comment]
Thanks for the report! :+1:

Having `\` in a username on a Linux system sounds like the kind of thing that will probably break a lot of tools :grimacing:

It's bad enough that `adduser` even rejects it if you try to create one:

```console
root@c06a555fcf1e:/# adduser 'foo\bar'
adduser: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
```

IMO we should only support this if the changes can be kept extremely minimal (since I don't think any of the maintainers here will be testing this use case to make sure it doesn't break). :see_no_evil:
