### ISSUE TITLE
Character messy happen while using cmd 'docker exec'

### ISSUE THREAD

**Issue by CKchen0726** [moby/moby#44544]
### Description

Character messy happen while using cmd 'docker exec'

(base) [root@edge08 ~]# docker ps |grep ubuntu
fd74ac77a29b        icmp.harbor/open-images/ubuntu-system:v1   "/bin/bash"              11 days ago         Up 11 days                                        ubuntu-system
(base) [root@edge08 ~]# docker exec -it fd7 ls -l /tmp/
total 112
-rw-r--r-- 1 root root      0 Nov 29 07:29 ''$'\344\271\213\346\261\237\346\265\213\350\257\225''.txt'
-rw-r--r-- 1 root root 112700 Nov 29 07:27 ''$'\347\253\236\345\223\201\345\210\206\346\236\220''.xmind'

### Reproduce

1. There is a Chinese file in the container
2. Exec 'docker exec -it fd7 ls -l /tmp/', and then will get some messy characters

### docker version

```bash
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 16:58:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:04:43 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker info

```bash
Client:
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 81
  Running: 62
  Paused: 0
  Stopped: 19
 Images: 35
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-305.3.1.el8.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 80
 Total Memory: 125.3GiB
 Name: edge08
 ID: ******
 Docker Root Dir: /home/lab/kubenetes/k8s/docker/containerd
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment]
I suspect this is because the shell inside the container does not have the right locale set up; https://superuser.com/questions/436813/how-to-display-chinese-character-in-bash-shell

**Comment by CKchen0726** [comment]
> 
Display info in container and on the server is normal, but only 'docker exec ls'
![image](https://user-images.githubusercontent.com/47560998/204943127-04c0ddcf-fa02-469d-825d-e3b34fd716f4.png)

**Comment by thaJeztah** [comment]
Ah! The difference there is `ls` running as main process for the `exec` versus `ls` running inside a `bash` shell. I think this depends on the implementation of `ls` inside the container. On ubuntu that looks to not support unicode characters, and default to escaping them (perhaps because it runs in POSIX mode), 

```bash
mkdir test
cd test
touch '🐳🐳.txt'

docker run -it --rm -v $(pwd):/foo ubuntu ls /foo
''$'\360\237\220\263\360\237\220\263''.txt'
```

but (e.g.) a `busybox` image does show the unicode characters;

```bash
docker run -it --rm -v $(pwd):/foo busybox ls /foo
🐳🐳.txt
```


Maybe there's some environment variable or option that can be used to make it do one or the other (not sure); I had a look at the man page; https://man7.org/linux/man-pages/man1/ls.1.html, and there's a `-b` option to change escaping style, but that didn't change it either, only used a different way of escaping;

```bash
docker run -it --rm -v $(pwd):/foo ubuntu ls -b /foo
\360\237\220\263\360\237\220\263.txt
```

In either case, this doesn't look to be a bug in docker.

**Comment by thaJeztah** [comment]
But as a workaround, you can try running `exec` without a TTY attached (without `-it`), which looks to print it correctly;

```bash
docker run --rm -v $(pwd):/foo ubuntu ls /foo
🐳🐳.txt
```

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
