### ISSUE TITLE
Docker Socket unresponsive due to high disk IO

### ISSUE THREAD

**Issue by MartinLoeper** [moby/moby#44550]
### Description

We have an issue with the `unix:///var/run/docker.sock` being unresponsive during high IO on our CI/CD host.
I suspect that the IO is caused by docker cleaning up containers at the end of the build step.

The issue is discussed in the gitlab-runner repository and the following comment sums it up the best imo:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2408#note_59829618

I do not know how to analyze this issue further.
I would like to know if (a) it is by design that the docker socket might block for several seconds (apparently up to 2 min) and (b) how to prevent this condition.

### Reproduce

It is unfortunately not reproducible, see: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2408

### Expected behavior

The docker socket is responsive and does not hang for 120 seconds.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 28
 Server Version: 20.10.21
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.74-1-pve
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 60GiB
 Name: gitlab-cannon
 ID: NVV4:6BG4:W4JS:CFJ4:AIND:BB23:IFUV:OLWK:HKNS:SAXM:IEDW:DJ6I
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Gitlab-Runner Error:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (docker.go:529:120s)`

Source Code:
https://gitlab.com/gitlab-org/gitlab-runner/-/blob/v15.6.1/executors/docker/docker.go#L529

**Comment by thaJeztah** [comment]
One thing I notice is that `vfs` is used as storage driver;

    Storage Driver: vfs

Is there a specific reason for that? The vfs driver definitely won't help with performance, as every layer will result in a full copy of the entire image to be created (even if the layer only has minimal changes)

**Comment by MartinLoeper** [comment]
Thanks for pointing that out! It seems to be due to running docker in LXC. 
I set it to fuse-overlayfs. Hopefully this will reduce the disk IO.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
