### ISSUE TITLE
new type of container backend.

### ISSUE THREAD

**Issue by lemanschik** [moby/moby#44602]
### Description

I want to add a new type of container backend the name is not specificated we can choose what ever you like it will create a web sandbox a WInterOp Runtime build where you can build binary directly as Web Interoperable runtime that directly can be used via any 

web browser or other WInterOP Runtime. 

Tech is researched existing this is only a question for a name and other integrational strategie parts discussion interfaces and styles. 

i offical implement it as standard web-modules but i am not sure if you want to take the name web-modules as build traget. 

see:
- [ ] https://github.com/lemanschik/web-modules/issues/4#issuecomment-1340571118
- [ ] https://github.com/lemanschik/moby/issues/1

the web interop part takes ENTRYPOINT and CMD and turns it into ECMAScript useable by the browser and host via in memory linking and JITING.

overall maybe some additions to the DOCKER file syntax are guess able. 

while it is already out of the box compatible via your JSON usage it is not usefull that you build moby in go. 

as go is not needed anymore it was a lang experiment by some google engineers which found large adoption. but it is the same concept already but in a incompatible way

in fact the go vm is already drived from parts of V8 other branches of it are the Dart Lang VM

we have now all backported to V8

**Comment by neersighted** [comment]
Hi @lemanschik, I think you may have made a wrong term/have an out of date understanding of the current Moby stack. These days, Moby mostly delegates responsibility for standing up containers to containerd, and only concerns itself with things like volume mounts, network namespace setup, port mapping, and other 'support' functions.

The core container runtime is however containerd (and we run a containerd when one is not present), which then delegates to an OCI runtime like runc or crun.

In any case, something lower down the stack is the best place to introduce new container types. Moby will support anything OCI-compatible, which can include both non-Linux containers, and non-OS-based containers like WebAssembly. You can already run WebAssembly outside the browser as an OCI container using [wasmedge](https://wasmedge.org/book/en/use_cases/kubernetes/container/crun.html) and its integration with containerd/runc; it even works in Moby/Docker Desktop with some manual setup and shimming.

If you end up implementing something novel and with demand and identified use cases that requires special support in Moby (though this is not preferred, special support shouldn't be necessary for 90% of alternate runtimes) it can certainly be discussed, though I would also strongly suggest you focus on clear, concise, and coherent English in your proposal and/or merge requests.

I'll be closing this as off-topic/not actionable in Moby, and I hope you've found my input helpful.

**Comment by lemanschik** [comment]
@neersighted it was help full thanks a lot
