### ISSUE TITLE
Dockerized node app cannot access its own node_modules if node_modules is missing on host

### ISSUE THREAD

**Issue by twiddler** [moby/moby#44604]
### Description

I am trying to dockerize the dev environment of a react app. I would like to

- have hot module reloading, so I am mounting my project files into my docker container, and
- keep this mount read-only so the container cannot mess with the host.

My solution is:

```console
docker run -v $(pwd):/app:ro my-image 
```

However, this would prevent the image from populating its `node_modules` with `RUN npm i`. So I create an anonymous volume under /app/node_modules:

```console
docker run -v $(pwd):/app:ro -v /app/node_modules my-image
```

Now I don't know why, but that last command seemingly fails if `node_modules` does not exist on the host. I don't know if this is somehow intended behaviour; to me it seems like a bug. 🤷

### Reproduce

1. Download [this gist](https://gist.github.com/twiddler/7deb70deec62b298738858cee5aa00bb).
2. Run `./this-works.sh` from your terminal. You should not see an error.
3. Run `./this-fails.sh` from your terminal. You should see an error like this:

> docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker/volumes/2ab6fcb106bc90e22084e87b22bafc743731d59d2880e596b54cc3ff173edadf/_data" to rootfs at "/app/node_modules": mkdir /var/lib/docker/btrfs/subvolumes/032e3d315649b4a6e71663145593ae1bebd6695091464a838bd4b4a342af9e8f/app/node_modules: read-only file system: unknown.
> ERRO[0000] error waiting for container: context canceled

There's been times I could not reproduce this error. I don't know why.

### Expected behavior

`this-fails.sh` should not throw an error.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:36 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:17 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 182
 Server Version: 20.10.21
 Storage Driver: btrfs
  Build Version: Btrfs v6.0
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.0.11-300.fc37.x86_64
 Operating System: Fedora Linux 37 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.01GiB
 Name: fedora
 ID: GGNP:DDT5:P3RY:GESB:LT44:3LSS:7ALD:G6CU:32GH:B7HR:4KRV:U3OO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by corhere** [comment]
The behaviour you are seeing is expected. Volumes on Linux are [mounted](https://man7.org/linux/man-pages/man2/mount.2.html) into the container filesystem. Only paths which exist can be used as mount targets. Docker tries to create the mount target for the anonymous volume for you, which fails because the parent directory `/app` is read-only.

**Comment by twiddler** [comment]
Then why does it work with `this-works.sh`? 🤔

**Comment by corhere** [comment]
[Because a mount target that exists doesn't need to be created.](https://gist.github.com/twiddler/7deb70deec62b298738858cee5aa00bb#file-this-works-sh-L3)

**Comment by twiddler** [comment]
I am running `this-works.sh` on the docker host, not inside the container. As far as I understand, `-v /app/node_modules` creates an anonymous volume that is mounted at `/app/node_modules` *inside* the container. How would that be influenced by a `node_modules` directory on the host?

**Comment by twiddler** [comment]
Alright, I think I might understand your point. Let me get back tomorrow.

**Comment by corhere** [comment]
The `node_modules` directory is not merely "on the host," it is at path `$(pwd)/node_modules` on the host. You are bind-mounting `$(pwd)` on the host to `/app` in the container. Docker first mounts `/app`, then mounts `/app/node_modules`. (If it was to mount them the other way around, the `/app` mount would shadow the `/app/node_modules` mount.)

**Comment by twiddler** [comment]
Alright, I understand. Thanks!

Is there a way to achieve what I want without creating a `node_modules` on my host?

**Comment by thaJeztah** [comment]
You can configure your application to not store the `node_modules` _within_ the app-directory itself (I'm not a node developer, but ISTR it's configurable); this allows you to keep your "vendored" (dependencies) separate from the code you maintain yourself.
