### ISSUE TITLE
I cannot change system date after run a container

### ISSUE THREAD

**Issue by haumenphai** [moby/moby#44609]
### Description

I cannot change system date after run a container

### Reproduce

create:
`docker run -itd --privileged --name sv3 -h sv3.foo.baz haumenphai/sv3_mix:20.04 /usr/sbin/init && docker exec -it sv3 bash`

start:
`docker start sv3`

change system date 

### Expected behavior

can change system date after run a container 

### docker version

```bash
Docker version 20.10.21, build baeda1f
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 12
  Running: 1
  Paused: 0
  Stopped: 11
 Images: 150
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d986545181c905378b0f90faa9c5eae3cbfa3755
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.37GiB
 Name: laptop
 ID: 6Z2D:PWQZ:VNM2:VJWC:YVAR:4XH2:HIGJ:C6JO:V7JD:N5LE:SXGC:CF5G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: haumenphai
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

video:

https://user-images.githubusercontent.com/59251518/206335567-8d86c7d1-be9b-4df7-9a2a-4f9ac9592eb9.mp4

**Comment by thaJeztah** [comment]
It looks like you're running the container with `--privileged`, which effectively means the container is no longer running as a "container" (all security protection is basically disabled), and has full root privileges on your host. In this case, it may be that the container is changing the system time, which (currently) means that it will be setting the whole system's time.

I see the container runs a `setup.sh` script, which contains;

```bash
#!/bin/bash
timedatectl set-timezone Asia/Ho_Chi_Minh
systemctl start ssh && systemctl enable ssh
ufw allow ssh
systemctl start postgresql && systemctl enable postgresql
systemctl status postgresql
```

The first line changes may be the culpritrit, but I also see you're running `/sbin/init`, which may be taking control of the time.

While time-namespaces are [now supported in the kernel](https://www.phoronix.com/news/Linux-Time-Namespace-Coming ) / [time_namespaces(7)](https://man7.org/linux/man-pages/man7/time_namespaces.7.html), there's still some work to do to .

**Comment by haumenphai** [comment]
@thaJeztah Thank you.
I fixed my problem by running:
`sudo systemctl stop systemd-timesyncd && sudo systemctl disable systemd-timesyncd` in the container
