### ISSUE TITLE
[23.0.0-beta] go.sum and vendor/ tree currently mismatch go.mod

### ISSUE THREAD

**Issue by paralin** [moby/moby#44614]
### Description

Running "go mod vendor" also fails due to a missing line in go.sum.

Errors when running "go build -mod=vendor" without running "go mod tidy":

go: inconsistent vendoring in docker-engine-:
  cloud.google.com/go@v0.102.1: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/compute@v1.7.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/logging@v1.4.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  code.cloudfoundry.org/clock@v1.0.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  [snip]

  To ignore the vendor directory, use -mod=readonly or -mod=mod.
  To sync the vendor directory, run:
  go mod vendor

### Reproduce

1. Run `go build -mod=vendor ./cmd/dockerd`

### Expected behavior

Previous releases build correctly without any changes using `go build -mod=vendor`.

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

**Comment by thaJeztah** [comment]
The reason you're running into this is that this repository is not yet a go module, as the versioning and package name are not compatible with Go's conventions; adding a `go.mod` would break the repository currently until we rename the project.

we use a `vendor.mod` file to specify the dependencies (which is a custom name for `go.mod`), which is used through the `hack/vendor.sh` script (which creates a temporary `go.mod` file to use during vendoring, but is not used after that); also see https://github.com/moby/moby/pull/44497

closing this ticket, but feel free to continue the conversation.

**Comment by paralin** [comment]
See #44618 - this is actually a bigger issue than you might realize. @thaJeztah
