### ISSUE TITLE
Strange problem with docker

### ISSUE THREAD

**Issue by sprootik** [moby/moby#44647]
### Description

At the request of @thaJeztah  I create a topic in continuation of topic https://github.com/docker/desktop-linux/issues/107
Watching weird docker work.

### Reproduce

```
❯ docker run -it --rm --name test alpine:latest
sh-5.1# printenv
HOSTNAME=129487e4b428
PWD=/
HOME=/root
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/sbin/printenv
sh-5.1# 
sh-5.1# apk -V
sh: apk: command not found
sh-5.1# ls -l /sbin | grep apk
sh-5.1# 

```
```
❯ docker run -it --rm --name test nginx:stable-alpine
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/docker-entrypoint.sh": stat /docker-entrypoint.sh: no such file or directory: unknown.

```

### Expected behavior

```
[dan@dan-laptop ~]$ docker run -it --rm --name test alpine:latest
/ # printenv
HOSTNAME=85c390c50e03
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ # apk -V
apk-tools 2.12.10, compiled for x86_64.
/ #
```

### docker version

```bash
❯ docker version
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        baeda1f82a
 Built:             Thu Oct 27 21:30:31 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.2
  Git commit:       3056208812
  Built:            Thu Oct 27 21:29:34 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.13.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 49
 Server Version: 20.10.21
 Storage Driver: btrfs
  Build Version: Btrfs v6.0
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.17-2-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.35GiB
 Name: workLP
 ID: AYT5:RAT2:HOV2:RQDV:4EKG:5JXU:LOIV:BXUF:WUWS:SU3F:N3NF:ZIS7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nixit89
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.426269401+10:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.426312851+10:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.426324317+10:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.426411240+10:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/dc346679ec1e219c2151d342d9c174bf2e>
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.596244372+10:00" level=info msg="shim disconnected" id=dc346679ec1e219c2151d342d9c174bf2e8f12b903a5f1e2fa57dd232f75c35b
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.596295318+10:00" level=warning msg="cleaning up after shim disconnected" id=dc346679ec1e219c2151d342d9c174bf2e8f12b903a5f1e2fa57dd232f75c35b namespace=moby
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.596304942+10:00" level=info msg="cleaning up dead shim"
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.603659048+10:00" level=warning msg="cleanup warnings time=\"2022-12-15T09:35:43+10:00\" level=info msg=\"starting signal loop\" namespace=moby pid=20316 runtime=io.containerd>
dec 15 09:35:43 workLP dockerd[508]: time="2022-12-15T09:35:43.603892028+10:00" level=error msg="copy shim log" error="read /proc/self/fd/13: file already closed"
dec 15 09:35:43 workLP dockerd[476]: time="2022-12-15T09:35:43.604278487+10:00" level=error msg="stream copy error: reading from a closed fifo"
dec 15 09:35:43 workLP dockerd[476]: time="2022-12-15T09:35:43.803115468+10:00" level=error msg="dc346679ec1e219c2151d342d9c174bf2e8f12b903a5f1e2fa57dd232f75c35b cleanup: failed to delete container from containerd: no such container"
dec 15 09:36:05 workLP dockerd[508]: time="2022-12-15T09:36:05.756559481+10:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
dec 15 09:36:05 workLP dockerd[508]: time="2022-12-15T09:36:05.756609461+10:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
dec 15 09:36:05 workLP dockerd[508]: time="2022-12-15T09:36:05.756620666+10:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
dec 15 09:36:05 workLP dockerd[508]: time="2022-12-15T09:36:05.756715166+10:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a73ea935707fee6fa813e97b364f6eadc6>
dec 15 09:36:11 workLP dockerd[508]: time="2022-12-15T09:36:11.103701145+10:00" level=info msg="shim disconnected" id=a73ea935707fee6fa813e97b364f6eadc6174c9615bd04c8e2c27e0d03740e52
dec 15 09:36:11 workLP dockerd[508]: time="2022-12-15T09:36:11.103811226+10:00" level=warning msg="cleaning up after shim disconnected" id=a73ea935707fee6fa813e97b364f6eadc6174c9615bd04c8e2c27e0d03740e52 namespace=moby
dec 15 09:36:11 workLP dockerd[508]: time="2022-12-15T09:36:11.103830617+10:00" level=info msg="cleaning up dead shim"
dec 15 09:36:11 workLP dockerd[476]: time="2022-12-15T09:36:11.103953573+10:00" level=info msg="ignoring event" container=a73ea935707fee6fa813e97b364f6eadc6174c9615bd04c8e2c27e0d03740e52 module=libcontainerd namespace=moby topic=/tasks/d>
dec 15 09:36:11 workLP dockerd[508]: time="2022-12-15T09:36:11.110781801+10:00" level=warning msg="cleanup warnings time=\"2022-12-15T09:36:11+10:00\" level=info msg=\"starting signal loop\" namespace=moby pid=20842 runtime=io.containerd>

**Comment by sprootik** [comment]
Sorry guys.
The issue can be closed.
It was probably a problem on my system. After I deleted all the docker images altogether and uploaded them again, everything began to work correctly.  Perhaps it has something to do with restoring the system via btrfs+timeshift after an unsuccessful upgrade.

**Comment by thaJeztah** [comment]
Glad to hear it's resolved!
