### ISSUE TITLE
docker daemon stuck

### ISSUE THREAD

**Issue by dragon9783** [moby/moby#44677]
### Description

docker ps, docker images stuck, bring kubelet to not ready status
but ctr container ls work fine
`journalctl -u docker` got some error like `write unix /var/run/docker.sock->@: write: broken pipe`

### Reproduce

Not sure how to reproduce

### docker version

```bash
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        aeac9490dc
 Built:             Wed Jul 17 18:11:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       aeac9490dc
  Built:            Wed Jul 17 18:22:15 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker info

```bash
Client:
 Debug Mode: false

Server:
 Containers: 239
  Running: 197
  Paused: 0
  Stopped: 42
 Images: 127
 Server Version: 19.03.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-120-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.9GiB
 Name: ubuntu20-32-02
 ID: HKZU:XWKQ:E3YM:TSLU:YNZM:SOT2:6KZP:NBCX:JGYZ:WR2Y:3KIC:4BJS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry:5000
  127.0.0.0/8
 Registry Mirrors:
  https://bxsfpjcb.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

### Additional Info

[goroutine-stacks-2022-12-19T102125%2B0800.log](https://github.com/moby/moby/files/10265712/goroutine-stacks-2022-12-19T102125.2B0800.log)

[docker.log](https://github.com/moby/moby/files/10265746/docker.log)

**Comment by thaJeztah** [comment]
It looks like you're running docker 19.03, which reached EOL in 2021. Do you have ways to reproduce this issue, and are you still able to reproduce on a currently maintained version of Docker? (20.10.x at time of writing)?

If you're not able to upgrade to docker 20.10, at least I would _highly_ recommend upgrading to the last patch release of docker 19.03 (docker 19.03.15; https://docs.docker.com/engine/release-notes/19.03/).

EOL versions of Docker (including all versions of 19.03) will have unpatched vulnerabilities, so are _not_ recommended to use in general.

**Comment by dragon9783** [comment]
@thaJeztah thanks to reply, i will upgrade to 20.10.22, and reproduce this issue.

**Comment by thaJeztah** [comment]
Thanks! Happy to hear if there's still issues there; if there are, it's appreciated if you find ways to reproduce the issue (from a "clean" state); having ways to reproduce makes sure the the issue can be looked into (otherwise fixing it can be very difficult).

**Comment by dragon9783** [comment]
@thaJeztah I hope that i'm not bothering you,  I got same issue on docker version 20.10.22, this issue bring kubelet NOT ready, and `kubectl get cs` NOT response

[containerd-2023-01-13.log](https://github.com/moby/moby/files/10408748/containerd-2023-01-13.log)
[docker-2023-01-13.log](https://github.com/moby/moby/files/10408753/docker-2023-01-13.log)
[goroutine-stacks-2023-01-13T055137Z-00.log](https://github.com/moby/moby/files/10408796/goroutine-stacks-2023-01-13T055137Z-00.log)
[goroutine-stacks-2023-01-13T055137Z-01.log](https://github.com/moby/moby/files/10408798/goroutine-stacks-2023-01-13T055137Z-01.log)
[goroutine-stacks-2023-01-13T055137Z-02.log](https://github.com/moby/moby/files/10408800/goroutine-stacks-2023-01-13T055137Z-02.log)

**Comment by corhere** [comment]
```
goroutine 16523925 [syscall, 23178 minutes]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc0024ca390, 0x80000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
syscall.openat(0x0?, {0xc0024ca378?, 0x0?}, 0xc004c5d6c8?, 0x0?)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:68 +0x105
syscall.Open(...)
	/usr/local/go/src/syscall/syscall_linux.go:155
os.openFileNolog({0xc0024ca378, 0x12}, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:216 +0x9b
os.OpenFile({0xc0024ca378, 0x12}, 0x0, 0x2063a38?)
	/usr/local/go/src/os/file.go:338 +0x45
github.com/docker/docker/vendor/github.com/containerd/fifo.openFifo.func2()
	/go/src/github.com/docker/docker/vendor/github.com/containerd/fifo/fifo.go:130 +0xc5
created by github.com/docker/docker/vendor/github.com/containerd/fifo.openFifo
	/go/src/github.com/docker/docker/vendor/github.com/containerd/fifo/fifo.go:123 +0x3be
```
An `openat` syscall blocked for sixteen days?! What does your `dmesg` look like? This reminds me a lot of the sorts of chaos that Windows anti-virus software can cause; is there any sorts of security software installed on your system which might be hooking into your kernel or LD_PRELOAD?

**Comment by payall4u** [comment]
@dragon9783 
We found docker daemon stuck twice, recently, in our cluster with docker 19.3.9
I have no idea about it, so I try to find out what happened with strace.
The daemon world work normally after stracing every time.

I'm sure the stat of docker threads is not T

**Comment by corhere** [comment]
Ubuntu kernel 5.4.0-132 has a bug in epoll. Upgrading your kernel will resolve the issue. https://bugs.launchpad.net/bugs/1996678

**Comment by thaJeztah** [comment]
let me close this ticket, as it looks like this was the kernel-related issue
