### ISSUE TITLE
Symlink inside Docker container disappears and re-appears for no apparent reason

### ISSUE THREAD

**Issue by davidpcaldwell** [moby/moby#44671]
### Description

TypeScript's `tsc` compiler, installed in a local file inside a container, disappears during the build process and then reappears, for unknown reason.

### Reproduce

1. Clone https://github.com/davidpcaldwell/slime
2. Check out the `docker-engine-bug` branch (I am likely to try to work around this on the `main` branch, probably by disabling some tests)
3. `docker compose -f contributor/docker-compose.yaml build test && docker compose -f contributor/docker-compose.yaml run test`

The tests will fail, almost certainly (though I have seen them succeed a few times, but I think my last 10 or so runs in a row have failed). See "Additional info" for a much longer explanation of what is being tested in these tests and how.

Here is [a sample run that failed on GitHub](https://github.com/davidpcaldwell/slime/actions/runs/3732743653/jobs/6332599581).

This issue occurs on:
* Docker Desktop for macOS (Intel)
* Docker Desktop for macOS (Apple Silicon)
* Whatever GitHub is using for `ubuntu-latest` in its GitHub Actions implementation

### Expected behavior

`tsc` should not disappear.

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 34
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.772GiB
 Name: docker-desktop
 ID: KTTT:MPFE:ALRY:VUT5:KJU6:NOS5:EWXI:7C7H:MTK5:GGKL:NJXR:YJAW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Registry Mirrors:
  https://artifactoryedgedocker.service.csnzoo.com/
 Live Restore Enabled: false
```

### Additional Info

Many of the tests for the repository are written in TypeScript. The program it is using to run the tests "embeds" `tsc` by installing it to a known location. Partway through running tests, `tsc` disappears momentarily. Shortly thereafter, it reappears in the same location. But during the time it disappears, tests involving TypeScript fail because the TypeScript can't be compiled.

I've added several diagnostics to the output to try to pin it down.

The runtime is JVM-based, so I added a thread that continually checks (via polling) for the existence of `tsc` and emits a console message if the existence of `tsc` changes (it appears or disappears). The check is based on `java.io.File.exists()`. The console message starts with `tsc change` (and then "removed" or "added").

On startup, the test runner also checks to see whether `tsc` is already installed, and if it's not there, installs it and then forks a subshell to execute the program. This check emits messages like `fifty tsc check`, and it verifies that `tsc` is always installed on startup. (This check occurs four times during the testing process.)

Also, in the test where I was seeing failures, I added a bunch of synchronous tests to try to figure out which step might be causing `tsc` to disappear. I determined that the disappearance of `tsc` is unpredictable; it might not be related to one of the tests (or if it is, whatever goes wrong causes downstream effects asynchronously). (The only thing I can think of that the tests that manifest the problem have in common is running `git` on repositories created as test cases.)

Finally, this issue is somewhat new, I believe. I had not experienced these failures until recently -- perhaps the last week. I don't believe any related code in my project changed. I noticed the failures on GitHub (which is where I normally run the full test suite), and then learned that I could reproduce them locally.

**Comment by corhere** [comment]
[The version of Docker in `ubuntu-latest` GHA image was first upgraded to v20.10.21 on 2022-11-24](https://github.com/actions/runner-images/commit/d54fa255120bfd0f508c1feb53490190787b1316), nearly four weeks ago. Docker v20.10.21 was released on 2021-10-25, and first incorporated into Docker Desktop v4.14.0 released on 2021-11-10. Given that the issue started manifesting more recently, it seems unlikely that the issue is correlated with upgrading the Engine version.

Docker Engine does not play an active role in anything filesystem-related after the container has started. The Linux kernel does all the heavy lifting. If it isn't a bug in your code, it would have to be a bug in the kernel which is causing the symlink to randomly blink in and out of existence. While kernel bugs are not unheard of, it is also very unlikely.

[`java.io.File.exists()` returns false on dangling symlinks, by design.](https://bugs.openjdk.org/browse/JDK-4956115) That might explain your observations.

**Comment by davidpcaldwell** [comment]
Thanks for the clarity. Yes, there are a lot of layers involved here (and I didn't know the architecture of some of the lower ones). I'll close this and post here again if I discover anything pertinent.
