### ISSUE TITLE
Docker daemon hangs with write unix /run/docker.sock->@: write: broken pipe

### ISSUE THREAD

**Issue by dcarrion87** [moby/moby#44694]
### Description

We're having what appears to be random issues across a few nodes and hoping someone might be able to help direct us what could be causing this.

After some time docker on nodes start to experience these errors out of nowhere and only restarting the docker daemon seems to fix this.

Repeated errors in logs:

> Dec 12 21:48:23 XXX dockerd[2995832]: time="2022-12-12T21:48:23.054423962+11:00" level=error msg="Handler for GET /v1.41/containers/90bc3fa51589db450f92f8a4a9f7aae728317fae02000c2794f82621f4ebecd1/json returned error: write unix /run/docker.sock->@: write: broken pipe"
Dec 12 21:48:23 XXX dockerd[2995832]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)

I'm guessing it's one of the running containers but it's not obvious what is causing.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 nvidia:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 57
  Running: 23
  Paused: 0
  Stopped: 34
 Images: 34
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-132-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 256
 Total Memory: 1.968TiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by vvoland** [comment]
Do you have some background processes which call the `containers/*/json` endpoints? This could for example be a script which calls `docker inspect` to check state of the container.

The error you posted is not an unrecoverable engine error and the error itself shouldn't affect the operational state of the daemon. It indicates that some client of the engine initiated request and then stopped receiving the data from the Docker socket.
This can happen for example if you invoke `docker ps` and then immediately terminate it with Ctrl+C.

Could you post full content of the dockerd log? Turning on the `debug` mode before taking the logs could also be helpful. Also, can you include more details about your environment and how it interacts with the engine?

**Comment by dcarrion87** [comment]
It's a k3s environment running v1.24.4+k3s1. We're needing to use docker for vendor support reasons but there may be opportunity to move away from docker.

The issue is when it happens it sends the state of node into a spin and attempts to start terminating pods on that node. It of course cannot since the daemon isn't responding.

I'll see what I can get in terms of more verbose dockerd logs.

**Comment by dragon9783** [comment]
I got same issue on docker version 20.10.22, this issue bring kubelet NOT ready, and `kubectl get cs` NOT response
[containerd-2023-01-13.log](https://github.com/moby/moby/files/10408748/containerd-2023-01-13.log)
[docker-2023-01-13.log](https://github.com/moby/moby/files/10408753/docker-2023-01-13.log)
[goroutine-stacks-2023-01-13T055137Z-00.log](https://github.com/moby/moby/files/10408796/goroutine-stacks-2023-01-13T055137Z-00.log)
[goroutine-stacks-2023-01-13T055137Z-01.log](https://github.com/moby/moby/files/10408798/goroutine-stacks-2023-01-13T055137Z-01.log)

[goroutine-stacks-2023-01-13T055137Z-02.log](https://github.com/moby/moby/files/10408800/goroutine-stacks-2023-01-13T055137Z-02.log)

**Comment by dcarrion87** [comment]
Interesting. It's strange, we've not been able to replicate it in the last week. Do you find it happening during certain container activity on the affected node?

**Comment by dcarrion87** [comment]
We ended up switching over to containerd directly as we couldn't replicate this consistently, sorry.

**Comment by sam-thibault** [comment]
Many warnings in the log like: "Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."  I'm curious if you are hitting out of memory issues which are ultimately resulting in the write errors.

**Comment by sam-thibault** [comment]
I will close this.  I think this issue is stale now.  Please comment if more/other info.

**Comment by jhodysetiawansekardono** [comment]
I have the exact same issue with Kubernetes v1.15.9 and Docker engine v23.0.1, sadly I can't reproduce this issue.

**Comment by dcarrion87** [comment]
@jhodysetiawansekardono you're best to switch over to containerd if capable. It's the Kubernetes way and things have been extremely smooth for us since.

**Comment by samartha-kar23** [comment]
@dcarrion87, what is the image tool to be used with containerd, if its nerdctl?

**Comment by dcarrion87** [comment]
We're working with k3s so we use `k3s crictl`. I suppose nerdctl should work.
