### ISSUE TITLE
Docker daemon restarted automatically by systemd

### ISSUE THREAD

**Issue by hanumanacholia** [moby/moby#44696]
### Description

Docker daemon restarted automatically by systemd 2 times a week in a few servers and resources (CPU/RAM/IO) looks good on all the servers. 
We have 20 node swarm clusters with 11 manager nodes. Every time leader Docker daemon restarted first then few other worker nodes also gets restarted.

**Is there any situation where the swarm sends the docker daemon restarted command to the current leader if the current leader is not able to send a heartbeat to other managers due to network fluctuations or its by systemd due to high resource usages ?** 

Case 1: 17 Dec  9:05 AM UTC

**Node IP**        **Status**      **Restart time**
ip-10-17-157-103      --Leader --Dec 17 09:05:10 UTC
ip-10-17-153-4.         --Worker1 --Dec 17 09:06:10 UTC
ip-10-17-138-96       --Worker7 --Dec 17 09:06:50 UTC
ip-10-17-162-36.      --Worker9 --Dec 17 09:07:20 UTC

Case 1: 20 Dec  5:31 AM UTC

**Node IP**        **Status**      **Restart time**
ip-10-17-130-112    --- leader --Dec 20 05:31:10 UTC
ip-10-17-153-4.      ---worker --Dec 20 05:31:56 UTC
 ip-10-17-130-230  ---worker --Dec 20 05:32:36 UTC
ip-10-17-154-98     ---worker --Dec 20 05:33:25 UTC
ip-10-17-162-36     ---worker --Dec 20 05:34:04 UTC

I am attaching journalctl , auth, and last login details logs here for 20th Dec incident 

**Leader node logs :**

**journalctl.log**

<img width="1727" alt="Screenshot 2022-12-26 at 8 41 37 AM" src="https://user-images.githubusercontent.com/41193415/209496480-a7c8a7fd-c9fe-49b4-8f28-9a7cd6b55a86.png">

**Auth.log**

<img width="1151" alt="Screenshot 2022-12-26 at 8 42 52 AM" src="https://user-images.githubusercontent.com/41193415/209496493-11d462b1-db84-451a-9764-e12bc22ea197.png">

**Last login log**

<img width="530" alt="Screenshot 2022-12-26 at 8 43 41 AM" src="https://user-images.githubusercontent.com/41193415/209497578-0e9b6ddb-8362-4568-a533-3865cad1a4b8.png">

**dpkg logs for any unattended-upgrades (I am not seeing any upgrades )** 

<img width="671" alt="Screenshot 2022-12-26 at 8 44 22 AM" src="https://user-images.githubusercontent.com/41193415/209497804-cf98b4ef-83d0-41c0-a549-8a89b07247d9.png">

**One of the worker node logs :**

**journalctl.log**

<img width="1727" alt="Screenshot 2022-12-26 at 9 10 22 AM" src="https://user-images.githubusercontent.com/41193415/209496897-a1f08ca7-3254-4a60-872c-266668bae572.png">
<img width="1728" alt="Screenshot 2022-12-26 at 9 10 43 AM" src="https://user-images.githubusercontent.com/41193415/209496910-971fd76b-1b48-407b-bba3-1b7fb02127a4.png">

**Auth.log**
<img width="1143" alt="Screenshot 2022-12-26 at 9 12 04 AM" src="https://user-images.githubusercontent.com/41193415/209496964-dcb1b832-c527-49c3-9c9f-c91604af6b6f.png">

**Last login log**
<img width="536" alt="Screenshot 2022-12-26 at 9 12 49 AM" src="https://user-images.githubusercontent.com/41193415/209497021-e8ba1bfd-559f-4cd9-9f16-da2dfa7a4e0b.png">

### Reproduce

There are no steps to reproduce as the root cause is unknown 

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:13 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:05 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 39
  Running: 38
  Paused: 0
  Stopped: 1
 Images: 54
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: elbyz55vpfkk2lv7e0q8uuwsn
  Is Manager: true
  ClusterID: m9j4qsy7h6ode8v2mul6aydsq
  Managers: 11
  Nodes: 20
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 30 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.17.130.112
  Manager Addresses:
   10.17.130.112:2377
   10.17.131.172:2377
   10.17.132.30:2377
   10.17.138.12:2377
   10.17.140.113:2377
   10.17.146.73:2377
   10.17.148.107:2377
   10.17.157.103:2377
   10.17.161.69:2377
   10.17.166.185:2377
   10.17.175.240:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-16-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.11GiB
 Name: ip-10-17-130-112
 ID: PF4G:3VZO:65WL:OXFS:3FDZ:APOX:H5LQ:A6DM:TZRA:S4J5:R3BR:RORK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
That `auth.log` looks to have a login, and a `sudo service docker restart`, or is that no the restart you're looking at?


<img width="1151" alt="Screenshot 2022-12-26 at 8 42 52 AM" src="https://user-images.githubusercontent.com/41193415/209496493-11d462b1-db84-451a-9764-e12bc22ea197.png">

**Comment by hanumanacholia** [comment]
I want to make sure that it's manually restarted by our internal user or docker swarm has the authority to do this. Is there any scenario where the swarm restarts the old leader docker daemon while electing a new leader?

**Comment by thaJeztah** [comment]
The daemon itself wouldn't make changes to systemd services (or restart a daemon).
