### ISSUE TITLE
daemon/graphdriver/btrfs/btrfs.go args.lim.max_referenced undefined

### ISSUE THREAD

**Issue by s4uliu5** [moby/moby#44698]
### Description

While building docker-20.10.22 on Funtoo linux with btrfs-progs 6.1, got this error

> daemon/graphdriver/btrfs/btrfs.go:437:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)

### Reproduce

1. extract source
2. hack/make.sh dynbinary

### Expected behavior

Build not fail.

### docker version

```bash
Not relevant.
```

### docker info

```bash
Not relevant.
```

### Additional Info

Only fails with btrfs-progs 6.1, with previous versions (6.0.x) builds ok.

IMHO the change of btrfs-progs that caused this affect is 

https://github.com/kdave/btrfs-progs/commit/03451430de7cd2fad18b0f01745545758bc975a5

**Comment by thaJeztah** [comment]
Thanks for reporting! Hm... from that commit (https://github.com/kdave/btrfs-progs/commit/03451430de7cd2fad18b0f01745545758bc975a5); 

> ioctl.h is a public header but there are no users of the btrfs_qgroup_limit structure.

Looks like they missed that it was used in this repository (at least; it's possible other runtimes _may_ be using it as well). I see use of it was added for quota support in https://github.com/moby/moby/commit/401c8d17674379d9b727d25df2d560a2dfe07f27 (https://github.com/moby/moby/pull/19651)


That will be a tricky one; I don't think we can easily change the code to match the new version (as we need to build for various distros, most of which will still have the older btrfs-progs).

@kdave @josefbacik any suggestions how to keep it backward compatible?

**Comment by Conan-Kudo** [comment]
@thaJeztah This change will be reverted in the next btrfs-progs bugfix release (v6.1.1): https://lore.kernel.org/linux-btrfs/20230103113941.GN11562@twin.jikos.cz/

**Comment by Conan-Kudo** [comment]
FYI, the (correct) longer-term fix is to move to `libbtrfsutil` instead of using `libbtrfs`: https://lore.kernel.org/linux-btrfs/20230103120640.GO11562@twin.jikos.cz/

**Comment by thaJeztah** [comment]
Thanks for the heads-up @Conan-Kudo - appreciated! ❤️ 

We had some discussion about what headers would be best to use, and why we were not using the kernel headers (that last part we tracked down to support for RHEL7, which had experimental support for BTRFS, but (I think) not in the kernel headers of the kernel version used - @corhere or @neersighted did some digging into options).

**Comment by neersighted** [comment]
Indeed, the plan is to depend on the kernel uapi here, which exposes the fields we currently use. That being said, libbtrfsutil is good to keep in mind if we need to depend on functionality not in the uapi in the future (e.g. userspace code).
