### ISSUE TITLE
Docker v23.0.0-rc2 doesn't build in Mac

### ISSUE THREAD

**Issue by AdallomRoy** [moby/moby#44830]
### Description

This commit: https://github.com/moby/moby/commit/33572e98c1405a579da5adc597e74b0dbf2aee56 broke docker build in mac.
The reason is:
 /go/pkg/mod/github.com/docker/docker@v23.0.0-rc.2+incompatible/pkg/plugins/discovery_unix.go:27:26: undefined: homedir.GetLibHome

homedir.GetLibHome call was added for every unix, while an implementation was added for Linux only.
A stub for other unix implementations should be added

### Reproduce

build docker in mac

### Expected behavior

should build

### docker version

```bash
23.0.0-rc2
```

### docker info

```bash
23.0.0-rc2
```

**Comment by AdallomRoy** [comment]
It's a good question how we get to import this part, I think it's due to importing the graph driver registration, but not sure TBH

**Comment by thaJeztah** [comment]
I know we have various packages that were designed to be used in the daemon code only, and some of those definitely have some "incorrect" build-tags; in some cases fixing those would require some work, and for some of those we considered the "pros" of doing so not worth doing, as it would cause a lot of code-churn and we know the _intention_ of some of that code was to only be built on the (known) daemon platforms (linux or windows).

If it's possible to fix this without too much code-churn and without introducing too much complexity (I haven't looked closely what changes would be needed), then contributions are definitely welcome (we did so for some packages to allow easier debugging on macOS in some cases).

Is the code you're using it in in a public repository, or is this some private code base?

**Comment by AdallomRoy** [comment]
It's in a private code base, I can try to offer a contribution that resolves this

**Comment by AdallomRoy** [comment]
Just validated that this builds well in Mac now, closing.
