### ISSUE TITLE
cannot connect to container from another container

### ISSUE THREAD

**Issue by flixman** [moby/moby#44878]
### Description

I am starting a job through drone.ci, docker agent, that requires a dockerized postgres server and another container (the one being tested). If get into the container under test and I execute dig postgres, the name gets resolved successfully to 192.168.16.3 (the rest of my network is in 192.168.178.0/24). On that postgres server I am running an additional process on the port 8080 (so that I can download some files from that container without using docker utilities) and I can connect to the postgres port (5432) but not to the 8080 (from 192.168.16.2)... although I can connect to both from the host machine.

with a `docker container ls` I can see that both ports are exposed:
```
CONTAINER ID   IMAGE                 COMMAND                   CREATED          STATUS                PORTS
e3b7633b6eb7   ci_test:latest      "/bin/sh -c 'echo \"$…"   20 minutes ago   Up 19 minutes       
bd7b195373e5   postgresql:latest   "docker-entrypoint.s…"    39 minutes ago   Up 38 minutes     5432/tcp, 8080/tcp
```

The network is the same (drone-G6xfGPadfZUYuGTlnYO1) for both containers, and in firewalld the interfaces are properly set to the docker zone:
```shell
# firewall-cmd --list-all --zone=docker
docker (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: br-5d7f638d9cf9 br-9274c184cf2f br-cae3457c09ac docker0
  sources: 
  services: 
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

Is this a configuration error, or is it a bug?

### Reproduce

1. Drone is starting both containers, to which I can successfully log into (so I'd say "docker run --rm ....")
2. Get into the container under test and execute "dig postgres" (it returns 192.168.16.3)
3. telnet to 192.168.16.3 port 5432 and it works, do the same to 8080 and does not.
4. repeat the same from the host, and both work.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:22 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 13
  Running: 9
  Paused: 0
  Stopped: 4
 Images: 20
 Server Version: 20.10.22
 Storage Driver: zfs
  Zpool: rpool
  Zpool Health: ONLINE
  Parent Dataset: rpool/var/lib
  Space Used By Parent: 6019035136
  Space Available: 12384755712
  Parent Quota: no
  Compression: off
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-20-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.467GiB
 Name: kngnt
 ID: MLLA:IBF6:IOMC:7NQA:QUOJ:O5FD:OWZX:SXPE:DFTD:BGDP:7WRB:Z2GB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by corhere** [comment]
Note that exposing a container port means to port-forward a port from your host to a container such that packets destined for host-ip:host-port get routed into the container. It has nothing to do with direct container-to-container traffic using the containers' network interfaces.

To clarify, what is the exact command you are using in step 4 of your reproducer? Is it more like
1. `telnet 192.168.16.3 8080`, or
2. `telnet localhost 8080`?

How are you arranging to have a separate process run in the postgresql container which listens on port 8080? Can you connect to it from within the postgresql container?

**Comment by flixman** [comment]
@corhere Thank you for your answer. I have just found that... seems a reboot was required? I think I updated the server before starting these tests but I have checked and I had not rebooted it earlier. Anyway, after the reboot with the existing setup... everything just works. Again, thank you for your time... and regards.
