### ISSUE TITLE
`docker manifest inspect` doesn't support OCI manifests

### ISSUE THREAD

**Issue by flx42** [moby/moby#44898]
### Description

I believe this was working fine a few days ago on the Ubuntu 22.04 image from Docker Hub, but now it doesn't:
```console
$ docker manifest inspect ubuntu:22.04
no such manifest: docker.io/library/ubuntu:22.04
```

The reason is probably because the Ubuntu images on Docker Hub switched to OCI manifests recently: https://git.launchpad.net/cloud-images/+oci/ubuntu-base/tree/?h=dist-jammy-amd64-20230126

With buildah:
```console
$ buildah --log-level=debug inspect ubuntu:22.04
[...]
DEBU[0000] Content-Type from manifest GET is "application/vnd.oci.image.index.v1+json" 
```

Whereas older Ubuntu images that haven't been updated still work:
```console
$ docker manifest inspect ubuntu:16.04
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
[...]

$ buildah --log-level=debug inspect ubuntu:16.04
[...]
DEBU[0000] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json" 
```

**Comment by neersighted** [comment]
This was fixed in https://github.com/docker/cli/pull/3990 and is released in 23.0.0.
