### ISSUE TITLE
Daemon does not start without apparmor

### ISSUE THREAD

**Issue by FriendlyTroll** [moby/moby#44900]
### Description

Running on Debian 11 Bullseye, and using 
`deb https://download.docker.com/linux/debian bullseye stable`
in sources.list.d.

After upgrade from version  20.10.22 to 23. results in this error

```
Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `apparmor_parser apparmor_parser --version` failed with output: 
error: exec: "apparmor_parser": executable file not found in $PATH
Error: failed to start containers: somecontainer
```

This seems to be connected with [this ticket](https://github.com/moby/moby/issues/20554) and [this](https://github.com/rancher/k3os/issues/702). There is a workaround below.

### Reproduce

1. apt update
2. apt upgrade

to install docker version 23. 

### Expected behavior

Upgrade should run smoothly.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:43:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:43:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 125.8GiB
 Name: server
 ID: ASHT:IIYG:NTE5:MWJH:XKZH:LCB2:RYWI:EZQM:QNT6:SNKW:AQWU:UYDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Workaround is to install apparmor package

`apt install apparmor`

**Comment by thaJeztah** [comment]
^^ per a discussion on our slack, the package should be `apparmor`, not `apparmor-utils` (updated my comment above)

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/docker-install/pull/335 to fix the `get.docker.com` installation script as well

**Comment by kiorky** [comment]
There are cases where it's not that simple.
eg


- using a Debian based host
- running a lxc container inside which is used as a gitlab-runner executor: here you can workaround by installing apparmor userland
- But then , if in your CI, you use DIND workflows, you wont be able to spawn the dind container as it will check on the same error.

rel #44902

**Comment by visit1985** [comment]
Can confirm that. Today docker-ce 23.0.0 got pushed to centos repos.
We run dockerd in a centos lxd container on an ubuntu lxd host.
There is no way to install apparmor/-utils in this scenario.

**Comment by kiorky** [comment]
I would like to emphasis that this bug is a bit critical as docker can be upgraded during an unattended upgrade and then break the workload running on the related host.

**Comment by tianon** [comment]
FYI, this was discussed in today's maintainer call and a revert to the apparmor startup logic is being fast-tracked for a 23.0.1 release: https://github.com/moby/moby/pull/44902#issuecomment-1419665548

**Comment by reddwarf69** [comment]
FWIW, with 23.0.1:
```
$ apt list docker-ce docker-ce-cli
Listing... Done
docker-ce-cli/jammy,now 5:23.0.1-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce/jammy,now 5:23.0.1-1~ubuntu.22.04~jammy amd64 [installed]
$ docker run -ti --rm 0ab66881fb24 bash
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.
$
```

**Comment by MartinHotmann** [comment]
Getting the very same error.

Here my info:

```
OS:               Arch Linux ARM (Rolling Release)
Docker:           v23.0.1, build a5ee5b1dfc
Docker compose:   v2.16.0
Containerd:       v1.6.16 31aa4358a36870b21a992d3ad2bef29e1d693bec.m
Ctr:              v1.6.16
```

**Comment by thaJeztah** [comment]
I'll lock the conversation on this thread in favor of https://github.com/moby/moby/issues/44970, which is still open, and to prevent the conversation from diverging.

A short summary;

- `apparmor_parser` is needed for `dockerd` to provide AppArmor protection on a kernel that has apparmor enabled.
- `apparmor` (which provides `apparmor_parser`) is a _`Recommends:`_ dependency for `dockerd` (which is a _strong_ recommendation, and means that while `dockerd` is _able_ to run without, doing so may require manual intervention).
- Depending on your installation method and the package manager used, `apparmor` may not get automatically installed when upgrading; if that's the case, then make sure to (manually) install the `apparmor` dependency, and restart the docker daemon afterwards for it to detect that `apparmor_parser` is installed.
- This issue was caused by a regression in the containerd code we use; we made changes in this repository to work around this regression, and to improve handling of this situation, but additional changes are still needed in containerd; those changes have been merged, but have not yet been released.
- Subscribe to https://github.com/moby/moby/issues/44970 to get posted on updates (but please refrain from "me too" / "+1" comments if you don't have important details to add).
