### ISSUE TITLE
docker.socket not stopped/disabled on uninstall

### ISSUE THREAD

**Issue by sepek** [moby/moby#44901]
### Description

When freshly installing docker-ce on a Debian Bullseye the installation fails with:
```
# apt install docker-ce
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite
The following NEW packages will be installed:
  docker-ce
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/21,9 MB of archives.
After this operation, 98,7 MB of additional disk space will be used.
Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Selecting previously unselected package docker-ce.
(Reading database ... 495743 files and directories currently installed.)
Preparing to unpack .../docker-ce_5%3a23.0.0-1~debian.11~bullseye_amd64.deb ...
Unpacking docker-ce (5:23.0.0-1~debian.11~bullseye) ...
Setting up docker-ce (5:23.0.0-1~debian.11~bullseye) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-02-02 14:32:54 CET; 3ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 237734 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 237734 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The problem seems to be that the system directory is missing. The problem can be fixed by `mkdir /etc/docker` upfront the installation or restarting the service after creating the directory.

### Reproduce

# Make sure docker-ce is not installed
1. `apt purge docker-ce`
2. `rm -rf /etc/docker`
# Install docker-ce
1. `apt install docker-ce`

### Expected behavior

The service should start, the installation should not fail.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:43:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:43:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 23.0.0
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 6.1.0-3-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.13GiB
 Name: xxx
 ID: 3EAC:YXW2:Q4IJ:VVYC:UX34:SGWW:WH2G:P5FL:YEDA:6DRP:OJPN:AA4L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

FTR: I'm not 100% sure if that's the correct place for the issue in case it is a packaging issue.

**Comment by thaJeztah** [comment]
Thanks for reporting; we're looking into this. It looks like it's missing a check if `apparmor_parsor` is installed (it's marked as a `recommends` dependency, so may not always be installed.

Installing it likely should workaround that issue;

```
apt-get install apparmor-utils
```

**Comment by thaJeztah** [comment]
oh, sorry, looks like I commented on the wrong ticket; need to look into this one as well

**Comment by neersighted** [comment]
Packaging is at https://github.com/docker/docker-ce-packaging/, but we often handle packaging issues here for simplicity for users; if a packaging issue gets opened we can just close this as a duplicate.

**Comment by sepek** [comment]
> Packaging is at https://github.com/docker/docker-ce-packaging/, but we often handle packaging issues here for simplicity for users; if a packaging issue gets opened we can just close this as a duplicate.

Thanks for the hint! For me it's a bit confusing. In the meantime I could reproduce the problem for Debian 10 as well as Ubuntu 22.04. However Fedora 26 and CentOS 7 work just fine. So the indication is it's a package issue. But I couldn't find anything related for creating the system directory within the SPECS (but I'm no rpm expert).

**Comment by droans** [comment]
I had the same issue on Ubuntu 22.04.

In addition, either by a massive coincidence or due to other issues, it appears that this version also caused filesystem corruption for btrfs. I rebooted my system, hoping that the issue would fix itself. However, the reboot caused my filesystem to go into read-only mode. Every corrupted block belongs to a file inside one of my volumes used by my containers.

I don't know if it is relevant, but I did downgrade to the last release of v20 before I noticed that the filesystem was corrupted. I cannot say for certain that the filesystem was not corrupted prior to the downgrade as I did not check beforehand.

**Comment by sepek** [comment]
> In addition, either by a massive coincidence or due to other issues, it appears that this version also caused filesystem corruption for btrfs. I rebooted my system, hoping that the issue would fix itself. However, the reboot caused my filesystem to go into read-only mode. Every corrupted block belongs to a file inside one of my volumes used by my containers.
> 
> I don't know if it is relevant, but I did downgrade to the last release of v20 before I noticed that the filesystem was corrupted. I cannot say for certain that the filesystem was not corrupted prior to the downgrade as I did not check beforehand.

FTR: I'm on btrfs too and rebooted just now for testing without any issues.  If you think it's related to your upgrade please create another issue for easier issue tracking.

**Comment by tianon** [comment]
Can we get some daemon logs (`journalctl -u docker.service`)?  This seems like `dockerd` is failing to start, but `/etc/docker` _should_ be 100% optional at daemon startup (and none of the systemd service files even reference it).

**Comment by sepek** [comment]
> Can we get some daemon logs (`journalctl -u docker.service`)? This seems like `dockerd` is failing to start, but `/etc/docker` _should_ be 100% optional at daemon startup (and none of the systemd service files even reference it).

Uh, very interesting :) should have had a closer look at these first and not conclude from the supposed solution to the problem. Sorry for that.
```
Feb 02 22:52:55 xxx systemd[1]: Starting Docker Application Container Engine...
Feb 02 22:52:55 xxx dockerd[244126]: time="2023-02-02T22:52:55.616525520+01:00" level=info msg="Starting up"
Feb 02 22:52:55 xxx dockerd[244126]: failed to load listeners: no sockets found via socket activation: make sure the service was started by systemd
Feb 02 22:52:55 xxx systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 22:52:55 xxx systemd[1]: docker.service: Failed with result 'exit-code'.
Feb 02 22:52:55 xxx systemd[1]: Failed to start Docker Application Container Engine.
```
So when I do an additional `systemctl stop docker.socket` things work too. That's clearly a packaging issue if that needs to be done with an uninstall. But still the question why it fails as the socket should not change content wise however probably unrelated to docker and more a systemd thingy.   
I'll have a closer look tomorrow at the server which initially has led me to the conclusion which was doing a complete fresh installation and not like me on my local system a purge && install.

**Comment by inakimalerba** [comment]
FYI, this also broke the (officialy unsupported buy widely used?) docker-machine
https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/98

**Comment by thaJeztah** [comment]
> ## Make sure docker-ce is not installed
>
> 1. `apt purge docker-ce`
> 2. `rm -rf /etc/docker`

and

> So when I do an additional `systemctl stop docker.socket` things work too. 

That looks like the same issue as https://github.com/moby/moby/issues/41792. We had a fix for that (see https://github.com/docker/docker-ce-packaging/pull/686), but had to revert (for now) because it was not supported on Ubuntu 18.04; https://github.com/docker/docker-ce-packaging/pull/699. Given that Ubuntu 18.04 reaches EOL soon, we can probably apply that change again soon though, or see if we can work around that; https://github.com/docker/docker-ce-packaging/pull/698#issuecomment-1131953559

**Comment by sepek** [comment]
Thanks for the hint. Indeed that seems to be the same problem. I can confirm that the directory problem is not the issue. It's a pure `docker.socket` issue. I'm still not 100% sure why it worked for me yesterday but at least `service-start-limit-hit` plays a role here.  
The issue is as following:
1. `docker.service` (and so `docker.socket`) are up.
2. `docker-ce` is uninstalled and stops `docker.service` but not `docker.socket`
3. `docker.socket` is still active but not working anymore until it dies:
```
Feb 03 11:03:45 xxx systemd[1]: Starting Docker Socket for the API.
Feb 03 11:03:45 xxx systemd[1]: Listening on Docker Socket for the API.
Feb 03 11:04:12 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:13 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:13 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:13 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:22 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:22 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:22 xxx systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
Feb 03 11:04:29 xxx systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
```
4. If `docker-ce` is started(/installed) before `docker.socket` dies/stops it will fail.
5. `docker.socket`  can fail after some time if hitting `service-start-limit-hit`

I could reproduce it on Fedora 36 too with executing `systemctl daemon-reload` in between step 2. and 3. which seems to be responsible for triggering the line:
```
docker.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
```
`deb-systemd-helper` is triggering that with a `dpkg` installation.   
  
Summa summarum - yes the socket should properly be stopped and disabled even for Fedora :)

**Comment by sepek** [comment]
Duplicate of #41792
