### ISSUE TITLE
overlay2 usingMetacopy prevents daemon startup due to ENOTSUP on some filesystems

### ISSUE THREAD

**Issue by paralin** [moby/moby#44911]
### Description

After upgrading to Docker v23.0.0 on kernel 6.1.4, the daemon fails to start with `dockerd -D` with the following error:

```
failed to start daemon: error initializing graphdriver: metacopy flag was not set on file in the upperdir: operation not supported
```

I've run check-config.sh to check the kernel config and everything is set properly. Furthermore the previous version of Docker worked fine on this machine.

containerd 1.6.16
runc 1.1.4
go 1.20
libseccomp 2.5.4

### Reproduce

1. Upgrade to Docker 23.0.0 and containerd 1.6.16
2. Run `dockerd -D`

### docker version

```bash
Client:
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.20
 Git commit:        23.0.0
 Built:             unknown-buildtime
 OS/Arch:           linux/arm
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Unable to get because daemon won't start.
```

### Additional Info

Odroid XU4 on Arm with kernel 6.1.4.

**Comment by paralin** [comment]
I found this relevant commit which introduced the failing check: 2c3d1f7b4be754abf4c3a169aa19db0792847fc6

**Comment by neersighted** [comment]
That is correct. For some reason `lgetxattr(2)` returns with an error status on your system. What is your full kernel version, as well as the type of the filesystem at `/var/lib/docker`? Can you please provide a complete daemon log?

**Comment by paralin** [comment]
@neersighted `Linux xu4-1 6.1.4 #1 SMP PREEMPT Thu Feb  2 05:56:06 PST 2023 armv7l GNU/Linux`

I'm using these flags to change where the docker daemon stores things:

```
/usr/bin/dockerd --containerd=/run/containerd/containerd.sock --data-root="/mnt/persist/skiff/docker" --log-driver=journald -D
```

/mnt/persist is an ext4 partition.

Thanks!

**Comment by paralin** [comment]
If I remove the --containerd option it starts up but runs into other errors elsewhere... Really confusing what's happening with this new version, I think there's some conflict: do we need to start containerd with systemd now? Could you confirm that's the new requirement? If so I'll happily close this issue @neersighted

**Comment by paralin** [comment]
OK - my issue seems to be related to other things: the daemon seems to expect that containerd is started by systemd, and NO_PIVOT_ROOT is now not working. I'll close this one for now, thanks.

**Comment by neersighted** [comment]
Are you running that daemon as root, or rootless?

I'm not sure what you mean by removing `--containerd` -- in that case the Daemon will start its own containerd instead of relying on one run externally (e.g. by systemd). Can you please provide the logs instead of referring to "other errors elsewhere...?"

There probably is something here, but you are making leaps of logic and not clearly describing what issues you are observing.

**Comment by paralin** [comment]
@neersighted I'm not making any leaps of logic, the issue was that I was testing with `dockerd -D` which runs on /var/lib/docker on default which is a ramdisk on my system and therefore caused the overlay2 errors.

When removing the --containerd flag and ensuring the --data-root flag was set correctly, the issue is now the following:

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error jailing process inside rootfs: pivot_root .: invalid argument: unknown
```

The pivot_root issue is because, apparently, NoPivotRoot is being ignored by containerd/runc. You cannot use pivot root on a ramdisk. I have DOCKER_RAMDISK=true set in the environment for dockerd, which sets the NoPivotRoot option in Runc. In previous releases this made using a ramdisk at / work correctly. However, now it's not working properly.

This is a completely separate issue & I'll open one if I can't figure out why NoPivotRoot is not being passed to runc properly.

Thanks.

**Comment by neersighted** [comment]
Okay, so there is something here -- overlay2 should probably not fail in the metacopy check on tmpfs. I think that there is incomplete error handling in the metacopy code, and I was trying to get tot he bottom of that. I think this issue should stay open, as despite the fact that you have solved your issue by providing a more suitable FS to the daemon, the poor error handling in the metacopy check persists.

Can you confirm the type of filesystem in `/var/lib/docker`? Is it tmpfs?

**Comment by paralin** [comment]
@neersighted ah okay, my apologies for the close. I was not aware that overlay2 has /ever/ worked with a ramdisk. Iirc, the ramdisk filesystem is not a supported lower FS for overlay2.

Mount shows the following fs type;

rootfs on / type rootfs (rw)

This is the result of booting with / as an initrd (initial ramdisk).

**Comment by paralin** [comment]
@neersighted the ENOTSUP is pretty expected when the fs is an initrd. It doesn't support really any of the required features that are needed for overlay2 nor would I expect it to. But maybe I'm wrong here.

**Comment by neersighted** [comment]
I don't know that overlay2 supports rootfs -- the issue is more that we have checks for filesystem suitability that are much more explicit than 'metacopy check failed do to ENOTSUP.' That is to say, I think the failure should happen somewhere else or be more straightforward.

It's possible that this is as good as it can get (and the graphdrivers are semi-deprecated while we move toward containerd-as-the-layer-store), but I'd like to keep this open until we confirm that the error handling is correct, or we're preventing the better 'filesystem-is-suitable' checks we have from firing and returning a more intuitive error to the user.
