### ISSUE TITLE
[dind] [BUG] 23.0.1: Missing AMD64 docker images on Docker hub for certain tags

### ISSUE THREAD

**Issue by aleuffre** [moby/moby#44971]
### Description

Apologies if this is not the right place to report this issue.

With the 23.0.1 release, it seems like both ARM and AMD64 images were uploaded to the "generic" tags, but not to the more "specific tags.  https://registry.hub.docker.com/_/docker/tags

For example:
`dind` has images for both amd64 and arm:
![image](https://user-images.githubusercontent.com/78726989/218065402-d9cec63c-814b-424c-bc18-a8b7144b230b.png)

but `23.0.1-dind` does not:
![image](https://user-images.githubusercontent.com/78726989/218065496-acb5cbf5-0b73-4271-9c54-46bea9f48bd8.png)

even though both tags should have the same images (and in fact the hash of the arm image is the same under both tags, as it should be.)

This also applies to a lot of other tags: while `latest` has both arm and amd images, most of the other 23.0.1 tags do not:

![image](https://user-images.githubusercontent.com/78726989/218066709-d3b758be-5219-41cb-ab5b-d30dcec644f1.png)

Thank you for your time!

**Comment by thaJeztah** [comment]
Packages are available for other architectures, so now sure why they're missing in the images;
https://download.docker.com/linux/static/stable/x86_64/

(static binaries for 23.0.1 on x86 are in https://download.docker.com/linux/static/stable/x86_64/docker-23.0.1.tgz)

**Comment by thaJeztah** [comment]
Looks like a ticket was already opened in the issue tracker for the official images;

- https://github.com/docker-library/docker/issues/404

**Comment by thaJeztah** [comment]
I'll close the ticket here in favour of https://github.com/docker-library/docker/issues/404, as this is related to the official images, and not maintained in this repository

**Comment by aleuffre** [comment]
Thanks a lot @thaJeztah !
