### ISSUE TITLE
Package naming convention broken with ubuntu docker 23.0.0

### ISSUE THREAD

**Issue by iusetabs** [moby/moby#44998]
### Description

I maintain some automation pipelines which installs various versions of docker. Since the 23.0.0 release, the package name has changed. Running apt-cache policy docker-ce on Ubuntu 20.04 yields a list which looks something like :
```
     5:23.0.1-1~ubuntu.20.04~focal 500
        500 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages
     5:23.0.0-1~ubuntu.20.04~focal 500
        500 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages
     5:20.10.23~3-0~ubuntu-focal 500
        500 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages
     5:20.10.22~3-0~ubuntu-focal 500
        500 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages
     5:20.10.21~3-0~ubuntu-focal 500
```

Is this change in package naming convention intentional or is this a bug? 

Also as I can't seem to find an explanation anywhere, why has version 21 and 22 been skipped, or what happened there? Thanks a bunch in advance!  

### Reproduce

apt-cache policy docker-ce

### Expected behavior

That the naming convention be consistent with previous versions. 

## Current naming convention for 23.X.X 

 5:23.0.1-1\~ubuntu.20.04\~focal
 5:23.0.0-1\~ubuntu.20.04\~focal

---

## Expected

5:23.0.1\~3-0\~ubuntu-focal
5:23.0.0\~3-0\~ubuntu-focal

### docker version

```bash
23.0.X
```

### docker info

```bash
N / A
```

**Comment by thaJeztah** [comment]
This was an intentional change; the old format did not take into account distro upgrades (e.g. `debian bookworm` (debian 12) would be considered older than `debian bullseye` when sorted by package managers), which result in distro upgrades (without a corresponding update in _version_ of the packages) not using the correct package; see

- https://github.com/docker/docker-ce-packaging/pull/701
- https://github.com/docker/for-linux/issues/1315

**Comment by iusetabs** [comment]
Thx for the explanation and quick reply @thaJeztah. I guess then this isn't a bug 😄 But before it's closed, could someone explain why there is no 21 and 22 release? I'm curious!

**Comment by thaJeztah** [comment]
For the release _version_, I know I included a mention in the pre-releases, e.g. https://github.com/moby/moby/releases/tag/v23.0.0-rc.4, but not sure if we mentioned it in the release notes on docs.docker.com, as it was more targeted as consumers of the code as library (perhaps could be worth mentioning though);

> Starting with the 23.0.0 release, we're moving away from using CalVer versioning,
> and use versioning that's using SemVer _format_. Changing the version format is
> a stepping-stone towards go module compatibility, but the repository does not
> yet use go-modules, and still requires using a "+incompatible" version; we'll
> be working towards go module compatibility in a future release.

To be clear on this; tags on this repository were always intended for the _binary_ releases, which did not use SemVer, and git tags at the time had no meaning to Go (but some vendoring tools existed, which could use them as reference). Go modules changed this, and now "assumed" that versions that could be parsed as SemVer, _were_ semver. Still lots of things to sort out in that area though, but having tags in a format that at least doesn't get _ignored_ by Go (unlike CalVer) is a first step in that direction.

**Comment by iusetabs** [comment]
Thanks all for the explanations 😄 Will close this bug off as it's been addressed.
