### ISSUE TITLE
docker compose up -d will restart a service even if there are no changes

### ISSUE THREAD

**Issue by yorickdowne** [moby/moby#44991]
### Description

With docker 23.0.1, when making a change to a service and then issuing `docker compose up -d` will correctly restart it. However, a second `docker compose up -d` will also restart it, as will starting any service that depends on it.

This only clears with a `docker compose down && docker compose up -d`

### Reproduce

`docker compose up -d`

Make changes to the `.env` or in some other way alter the definition of a service

`docker compose up -d`

Service is restarted as expected

`docker compose up -d`

Service is again restarted, not expected

`docker compose down && docker compose up -d`

Force refresh of the entire stack

`docker compose up -d`

All services remain running, none are restarted, as expected

### Expected behavior

`docker compose up -d` should know when it has already applied changes to a service previously, and not restart it again on following runs.

This works as expected on docker-ce 22.10.x

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.936GiB
 Name: dirk3
 ID: 637f6cf4-3429-4b7b-9ef3-ab2135ba24d8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bsousaa** [comment]
Can you share a minimal/sample compose file to reproduce the issue?

**Comment by bsousaa** [comment]
Sounds like this one is being tracked at https://github.com/docker/compose/issues/10259.

**Comment by yorickdowne** [comment]
Yep, that looks exactly like the issue. It's for the compose team to solve.

**Comment by yorickdowne** [comment]
Minimal file to reproduce

Create an `.env` with one line:
```
BAR=Wunder
```

Create a compose.yaml:
```
services:
  foo:
    image: alpine
    command: watch -n5 echo "We are going to the ${BAR} bar"
```

`docker compose up -d` - the `foo` service starts

`docker compose up -d` - the `foo` service is not restarted, as expected.

Edit `.env` and change the value of `BAR`

`docker compose up -d` - the foo service is recreated as expected

`docker compose up -d` - the foo service is again recreated

**Comment by yorickdowne** [comment]
Fixed by https://github.com/docker/compose/pull/10275 in next compose release.

**Comment by yorickdowne** [comment]
Closing. I trust docker-ce can track inclusion of the new compose independent of this issue.
