### ISSUE TITLE
Potential goroutine leak in TestNetworkDBCRUDTableEntries

### ISSUE THREAD

**Issue by Jay-deng** [moby/moby#44994]
### Description

I  use Uber's goleak tool to run the test function in docker/libnetwork/networkdb/networkdb_test.go, and find some information about goroutine leak. Here is the  snapshot of my console‘s output. 
<img width="1278" alt="1" src="https://user-images.githubusercontent.com/37053493/218677991-3b4d3f83-0a23-44e0-9e38-012d225a441b.png">
`
![Uploading 1.png…]()
`

### Reproduce

Using goleak to run the test function of TestNetworkDBCRUDTableEntries() in libnetwork/networkdb/networkdb_test.go.

### docker version

```bash
20.10.17
```

### docker info

```bash
.
```

**Comment by thaJeztah** [comment]
Quite possible there's bugs in that test; it's a test we inherited from the libnetwork repository (which was now integrated into this repo), and it's known to be a flaky test;

- https://github.com/moby/moby/issues/42739
- there's a PR pending with some fixes in the test (not sure if it resolves this issue; I would have to look at that, but reviews welcome!) https://github.com/moby/moby/pull/44500

**Comment by corhere** [comment]
From a quick glance at the hashicorp/memberlist module, it looks like that goroutine is terminated asynchronously when `(*Memberlist).Shutdown()` is called. (see `(*Memberlist).deschedule()`.) So while there technically is a goroutine leak by the definition of "there are extra goroutines running when the test returns" it will eventually exit in a timely manner. You could confirm this theory in a quick'n'dirty way by delaying the invocation of goleak for a couple seconds. E.g.:
```go
defer func() {
	time.Sleep(3*time.Second)
	goleak.VerifyNone(t)
}()
```

**Comment by sam-thibault** [comment]
I will close this.  It looks like this is not an issue, based on @corhere comment above.  Please comment on the issue again if you have other followup.
