### ISSUE TITLE
Container ulimits are inherited from containerd by default

### ISSUE THREAD

**Issue by ChristianS99** [moby/moby#45060]
### Description

On master branch and branch 23.0, the docker.service file (https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.service and https://github.com/moby/moby/blob/23.0/contrib/init/systemd/docker.service)
has LimitNOFILE=infinity

In branch 20.10, it (https://github.com/moby/moby/blob/20.10/contrib/init/systemd/docker.service) has LimitNOFILE=1048576

I think, that the master/23.0 branch should have this limit too. There are some programs out there, that loop over all possible file descriptors, trying to close them (e.g. screen, actually it was improved there (https://git.savannah.gnu.org/cgit/screen.git/commit/src/misc.c?id=3e37405972d49eb3d81301167693bcea1b2c3d71) but only 2019, so if you are running an ubuntu 16.x or 18.x container, you are still affected), which takes quite a while when the limit is infinity, which means s.th. like 2^20 on linux.

I checked the other init scripts in branch 23.0, too:
openrc: 1048576
debian: 1048576
redhat none explicitly set
upstart 524288:1048576

Not sure if this intentional, but when not, I would propose to adjust these to the same.
Also, I would think using different soft and hard limits would be quite sensible, maybe s.th. like 1024-10240 for soft limit, and 2^20(=1048576)-2^30(=1073741824) for hard limit?

### Reproduce

1) docker run --tty --interactive --rm ubuntu:16.04 bash -c "apt-get update; apt-get -y install screen; screen"
2) watch processor usage (e.g. htop) somewhere else, as soon as screen is installed and starting, it takes a considerable while with full cpu usage before it get's usable.

### Expected behavior

A quite high file limit of 1073741824 shouldn't be applied to all containers by default

### docker version

```bash
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.4
 Git commit:        3a2c30b63a
 Built:             Thu Jan  5 01:59:49 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.4
  Git commit:       42c8b31499
  Built:            Fri Jan  6 13:28:15 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad007797e0dcd8b7126f27bb87401d224240

Note: a colleague of me stumbled over this with some docker 23.0, I don't know exactly, but since it only affects the service/init files, I think it doesn't matter, and I could reproduce it with this version with manually modifying the service files
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 20
 Server Version: 20.10.22
 Storage Driver: btrfs
  Build Version: Btrfs v6.1.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: 5fd4c4d144137e991c4acebb2146ab1483a97925
 init version: de40ad007797e0dcd8b7126f27bb87401d224240
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 6.1.1-gentoo-dist
 Operating System: Gentoo Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.16GiB
 Name: beteigeuze
 ID: Z3AR:K5JT:BXCU:V2V5:VWCD:O43Q:JEHK:EPQV:N4IL:C6FM:QNGT:3ALC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by corhere** [comment]
The change was introduced in https://github.com/moby/moby/commit/80039b4699e36ceb0eb81109cd1686aaa805c5ec and explains why it was done. If you want to set limits on a container, set the limits on the container. [Don't use global state to manage a local problem.](https://devblogs.microsoft.com/oldnewthing/20081211-00/?p=19873)
```docker run --ulimit nofile=1024:1048576 --tty --interactive --rm ubuntu:16.04 bash -c "apt-get update; apt-get -y install screen; screen"
```

If you must change the limits globally for the daemon and all containers, you can use [systemd "drop-in" files](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#:~:text=Along%20with%20a%20unit%20file%20foo.service%2C%20a,a%20unit%2C%20without%20having%20to%20modify%20unit%20files.) to override the `LimitNOFILE` configuration.

**Comment by ChristianS99** [comment]
Hm, ok, I understand your point. But I think, there should be a few more points be considered:
1) branch 20.10 had LimitNOFILE=infinite, too at one point and changed it later
2) most other init scripts (in branch 23.0) do set a NoFile limit. IMHO, this should be consistent, either all set it, or all don't set it
I guess, these points are because of the performance penalty in some circumstances.

3) It's quite different from what a user would expect, as most(all) distros set at least a softlimit that is small(er). When we hit the problem, it took us half a day, to find out the cause. Undoubtful, a progarm, that starts to close one billion fds is, at least, strange on its own, but that's how it is. In combination with the limit, that is normally set in a shell, this leads to this strange situation "hm, why is screen broken in a container" (actually, it is not, after it has iterated over all fds it works, but when s.th. that is immediately ready under different circumstances takes longer than a minute to startup, I guess, most people would wait any longer)

With these points, maybe you could reconsider.
BR,C hristian

**Comment by ChristianS99** [comment]
> I think reverting the change in `docker.service` is off the table because of the performance regression it would cause. 
Why would this be a regression for performance? actually, a high NOFILE limit decreases preformance in some situations.
We are using dokcer to make yocto builds inside container, and with a ulimit -n of 1024, I get these times to build a package (gpsd in this example)
```
real    0m47,103s                                                                                                                                                                                                                           
user    0m0,032s                                                                                                                                                                                                                            
sys     0m0,026s
```
and with a ulimit -n of 1024000, it is
```
real    1m53,767s
user    0m0,025s
sys     0m0,039s
````
(ofcourse bitbake buildcache cleared before)
So, this actually increases total preformance quite a margin. TBH, this isn't dockers fault, but probably coming from other programs that loop over all possible fds trying to close them, but it's quite noticeable.
Don't know, (but can't see any) if in different situations the performance would be better with high NOFILE limit.

>That being said, you have a good point about it being surprising that the default ulimits inside a container are higher than those of a typical login session. A related discussion is happening in [containerd/containerd#7566](https://github.com/containerd/containerd/pull/7566). We could explore other solutions for setting default ulimits applied to containers aside from inheriting the ulimits from dockerd or from containerd.

I just tried, to set a ulimit of 1024:1048576 in my docker service file and noticed, that in the container, the hard limit of the daemon is used as soft *and* hard limit, which is also not good, IMHO. In order to have a sane value of e.g. 1024 for interactive docker sessions, this would require to set the hardlimit of dockerd to this value, which prevents a container from getting a higher ulimt -n at all, like could be required for some server applications

> > 2. most other init scripts (in branch 23.0) do set a NoFile limit. IMHO, this should be consistent, either all set it, or all don't set it
> 
> That looks to be intentional; see [#24555 (comment)](https://github.com/moby/moby/pull/24555#issuecomment-232347939). My understanding is that systemd will massage `LimitNOFILE=infinity` to the maximum numeric value the kernel would accept, unlike the `ulimit` command used in the other init scripts.

Yeah, but it's different anyway:
setting LimitNOFILE=infinity results in a value of 1073741824 (=2^*30*) (at least for me), while the other init scripts set the value to 1048576 (=2^*20*)

**Comment by thaJeztah** [comment]
- This looks to be a duplicate (or close to) of https://github.com/moby/moby/issues/44547
- Related proposal  in https://github.com/moby/moby/issues/38814

(perhaps we need to close some to prevent the discussions from further diverging)

A more detailed summary can also be found in the containerd repository (but I see that's mentioned above); https://github.com/containerd/containerd/pull/7566#issuecomment-1285417325.

Note that it's also possible to set the `--default-ulimit` option (or `"default-ulimits"` in `daemon.json`) to configure defaults for containers that are started, but even with that, it would be generally recommended to set limits on containers (cpu, memory, other limits) to their "expected" values, but perhaps we need to revisit https://github.com/moby/moby/issues/19023 and https://github.com/moby/moby/issues/18647, and look at easier ways to set common defaults (which could be either a daemon option or a client-side option).

**Comment by thaJeztah** [comment]
I should probably mention that this is not a change in the 23.0 release of the _docker ce packages_; when the packaging scripts were moved out of this repository, the systemd units were originally copied over as well, and the systemd units in this repository were mostly unmaintained (and diverged from the actual systemd units used in packaging). The docker 20.10 packages already used these values (here's the output from tha docker 20.10 install); 

```bash
cat docker.service | grep infinity
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity

systemctl cat containerd.service | grep infinity
LimitNPROC=infinity
LimitCORE=infinity
LimitNOFILE=infinity
TasksMax=infinity
```

To prevent them diverging further, the packaging changes were moved back into this repository in https://github.com/moby/moby/pull/42373.

**Comment by ChristianS99** [comment]
> * This looks to be a duplicate (or close to) of ["Max open files" limit of containers do not match with the limit in dockerd systemd unit file #44547](https://github.com/moby/moby/issues/44547)
> 
>     * Related proposal  in [Default per-container ulimits are too generous #38814](https://github.com/moby/moby/issues/38814)

there first issue sounds like s.th. different to me, but the second talks about not so generous limits for containers by default, that's what would solve this issue here. There was just no discussion since almost four years.
Should I ask there to revive the discussion?

**Comment by corhere** [comment]
- This issue duplicates #38814. Let's continue the discussion over there.
