### ISSUE TITLE
[awx-project] make docker-compose error 127

### ISSUE THREAD

**Issue by gonzalezr82** [moby/moby#45079]
### Description

When I try to run make docker-compose to recreate the containers from an AWX installation with docker it gives me the following error

ERROR:
[root@awxdev awx-21.6.0]# make docker-compose
make: python3.9: Command not found
/bin/sh: python3.9: command not found
ansible-playbook -i tools/docker-compose/inventory tools/docker-compose/ansible/sources.yml \
    -e awx_image=[ghcr.io/ansible/awx_devel](http://ghcr.io/ansible/awx_devel) \
    -e awx_image_tag=HEAD \
    -e receptor_image=[quay.io/ansible/receptor:devel](http://quay.io/ansible/receptor:devel) \
    -e control_plane_node_count=1 \
    -e execution_node_count=2 \
    -e minikube_container_group=false \
    -e enable_keycloak=false \
    -e enable_ldap=false \
    -e enable_splunk=false \
    -e enable_prometheus=false \
    -e enable_grafana=false

PLAY [Render AWX Dockerfile and sources] ***********************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create _sources directories] *****************************************************************************************************************************************************************************
ok: [localhost] => (item=secrets)
ok: [localhost] => (item=receptor)

TASK [sources : Detect secrets] ********************************************************************************************************************************************************************************
skipping: [localhost] => (item=pg_password)
skipping: [localhost] => (item=secret_key)
ok: [localhost] => (item=broadcast_websocket_secret)
skipping: [localhost] => (item=admin_password)

TASK [sources : Generate secrets if needed] ********************************************************************************************************************************************************************
skipping: [localhost] => (item=pg_password)
skipping: [localhost] => (item=secret_key)
skipping: [localhost] => (item=broadcast_websocket_secret)
skipping: [localhost] => (item=admin_password)

TASK [sources : Include generated secrets unless they are explicitly passed in] ********************************************************************************************************************************
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
ok: [localhost] => (item=None)
skipping: [localhost] => (item=None)
ok: [localhost]

TASK [sources : Write out SECRET_KEY] **************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render configuration templates] ****************************************************************************************************************************************************************
ok: [localhost] => (item=database.py)
ok: [localhost] => (item=websocket_secret.py)
ok: [localhost] => (item=haproxy.cfg)

TASK [sources : Delete old local_settings.py] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Copy local_settings.py] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get OS info for sdb] ***************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get user UID] **********************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set fact with user UID] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set global version if not provided] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [sources : Generate Private RSA key for signing work] *****************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Generate public RSA key for signing work] ******************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Include LDAP tasks if enabled] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [sources : Render Docker-Compose] *************************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render Receptor Config(s) for Control Plane] ***************************************************************************************************************************************************
ok: [localhost] => (item=1)

TASK [sources : Render Receptor Hop Config] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render Receptor Worker Config(s)] **************************************************************************************************************************************************************
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [sources : Render prometheus config] **********************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0

docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans
make: docker-compose: Command not found
make: *** [Makefile:483: docker-compose] Error 127

can someone help me with this error

### Reproduce

make docker-compose-build
make docker-compose

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-425.13.1.el8_7.x86_64
 Operating System: Oracle Linux Server 8.7
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.582GiB
 Name: awxdev.uclm.es
 ID: V55X:DOEG:IGEP:7RBB:P5FQ:NBUM:CZ7Z:7R2S:WOYA:PZDZ:Z7IB:PPDT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
```
docker-compose -f tools/docker-compose/_sources/docker-compose.yml up --remove-orphans
make: docker-compose: Command not found
make: *** [Makefile:483: docker-compose] Error 127
```


Looks like the makefile needs to be updated to use `docker compose` instead of `docker-compose`, or you need to install docker compose (or alias as `docker-compose` to run it standalone)


Either case, this doesn't look like a bug, so I'll close it here
