### ISSUE TITLE
Containerd snapshotter in docker-ce

### ISSUE THREAD

**Issue by hinshun** [moby/moby#45082]
### Description

I noticed that the latest docker-ce releases don't have the changes for dockerd to use containerd snapshotter behind a feature flag. Are there plans to support this in docker-ce?

**Comment by vvoland** [comment]
Yes, we are actively working on upstreaming the containerd snapshotter integration into moby.

**Comment by hinshun** [comment]
Hi @vvoland thanks for answering. Is there a document / label / milestone where I can help move things along?

**Comment by vvoland** [comment]
Also, we would love to get some input in UX related discussions like: https://github.com/moby/moby/issues/44582

**Comment by neersighted** [comment]
I'm going to go ahead and close this as answered -- hopefully it serves as a useful place for anyone with similar questions to find answers.
