### ISSUE TITLE
The cpu usage of dockerd increases periodically

### ISSUE THREAD

**Issue by pixiake** [moby/moby#45119]
### Description

The cpu usage of `dockerd` increases every two minutes.

I used `perf top -p {docker pid} --call-graph graph` to record the information when the cpu usage of dockerd increased. 

![image](https://user-images.githubusercontent.com/22290449/223607700-bdd850ff-dd01-4c74-87f2-8957db5f3d6e.png)
![image](https://user-images.githubusercontent.com/22290449/223607939-b702810b-762c-4847-a348-f48827351980.png)

### Reproduce

At present, I have only encountered this problem in individual nodes, and I don't know how to reproduce it yet.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 44
  Running: 40
  Paused: 0
  Stopped: 4
 Images: 38
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.20-1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 376.5GiB
 Name: xpqgly1530xx12xxk8sm
 ID: 55KC:5GIC:BY6G:ON6I:M4YN:3R6Z:235L:L4K6:TA6W:6JWJ:EUQC:W4NQ
 Docker Root Dir: /kube/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Looks like the Go runtime garbage collecting; https://go.dev/src/runtime/mgcmark.go

I see you're running a very old version of docker 20.10 (20.10.8, where the latest patch release for 20.10 is 20.10.23). Not sure if there's differences since in this specific area, but 20.10.8 is built with an older (and EOL) version of Go (besides 20.10.8 having various vulnerabilities that have been patched since).

If you have an environment to test on, might be worth trying if more recent versions have the same issue.

**Comment by pixiake** [comment]
@thaJeztah I have several clusters, and each cluster also has many nodes, but only a few nodes have this problem.

I found that  executing `systemctl status docker` on the problematic node can find that docker occupied a lot of memory. And I can reduce the memory usage of docker by using `echo 3 > /proc/sys/vm/drop_caches`. But The cpu usage of dockerd still increases every two minutes. 

After restarting docker, the node can return to normal. So I suspect that the cpu usage may increase periodically due to memory leakage. 

How can I continue to investigate? Thanks !

![image](https://user-images.githubusercontent.com/22290449/226219221-035f21da-8777-4454-b95d-af2fe370dcc5.png)

**Comment by bsousaa** [comment]
Are you running Kubernetes in your setup? Is it possible that it starts something each 2 minutes (or reconciliation loop)?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
