### ISSUE TITLE
osl: protect field access with libnetwork to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [moby/moby#45146]
### Description

Fixed inconsistency and also potential data race in namespace_linux.go, neigh_linux.go and interface_linux.go:
n.nlHandle is read/written 4 times in namespace_linux.go, neigh_linux.go and interface_linux.go; 3 out of 4 times it is protected by n.Lock(); 1 out of 4 times it is read without a Lock, which is in func Destroy() on L471.
A data race may happen when Destroy() and other func like AddInterface() in interface_linux.go are called in parallel.
The fix is to protect the access to n.nlHandle and save the result to a local variable.

### Reproduce

Nil

### docker version

```bash
latest
```

### docker info

```bash
latest
```

**Comment by neersighted** [comment]
cc @corhere @akerouanton

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
