### ISSUE TITLE
container stats helper channel not close

### ISSUE THREAD

**Issue by bugou** [moby/moby#45154]
### Description

error code found in cli/command/container/stats_helpers.go
should add "close(u)" in line 97?

### Reproduce

error code found in cli/command/container/stats_helpers.go
should add "close(u)" in line 97?

### Expected behavior

error code found in cli/command/container/stats_helpers.go
should add "close(u)" in line 97?

### docker version

```bash
error code found in cli/command/container/stats_helpers.go
should add "close(u)" in line 97?
```

### docker info

```bash
error code found in cli/command/container/stats_helpers.go
should add "close(u)" in line 97?
```

**Comment by sam-thibault** [comment]
This issue should be created on the https://github.com/docker/cli repo.  I will close this issue.  Can you reopen a new issue there with more information?
