### ISSUE TITLE
docker-proxy get killed when many request

### ISSUE THREAD

**Issue by pzs-pzs** [moby/moby#45152]
### Description

my docker-proxy bind ipv4 get killed when pressure test , restart container docker-proxy will bind ipv4 port
![image](https://user-images.githubusercontent.com/25561451/224740200-13bdf2b4-b005-4ede-a80e-e2b5fb7a993b.png)

### Reproduce

pressure test 

### Expected behavior

get some logs for kill reason

### docker version

```bash
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        100c70180f
 Built:             Tue Mar  7 06:29:35 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       a89b842
  Built:            Tue Mar  7 06:30:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 80
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-67-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: zkxq-dev-server
 ID: 6O3P:7XXP:HMPB:H5AJ:GEQC:K5BJ:POFV:PU22:QKJN:OOLZ:M4XI:TH7H
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://registry.docker-cn.com/
  http://hub-mirror.c.163.com/
  http://f1361db2.m.daocloud.io/
 Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
What sort of stress testing are you doing?
If I had to guess what is causing it to be killed it would be the oom-killer, which depending on what you are doing is conceivable.

Have you tried this testing without docker in the middle? As an example, execute `docker-proxy` yourself and run your tests against it?

**Comment by pzs-pzs** [comment]
Thanks for your reply, I am doing the interface stress test, assuming `docker-proxy` is killed due to OOM, I did not find the relevant log proof on the host machine, can you give me some advice to check the relevant log? I haven't tried running docker-proxy alone, I will look for related methods to try

**Comment by pzs-pzs** [comment]
When I monitored the`strace` of `docker-proxy`, I found that there was an `exited with 0`, and I guessed that `syscall.SIGTERM` was received
<img width="622" alt="image" src="https://user-images.githubusercontent.com/25561451/226255681-8a950d14-f11f-4f20-b485-427d8ab7a2f0.png">

**Comment by lrascao** [comment]
This looks very similar to https://github.com/moby/moby/issues/8817, tried `wrk` over `docker-proxy` both `master` and `20.0.17` with no luck
@pzs-pzs what tool are you using to generate the load?

fwiw this is what i did:

```
docker run -d -p 8080:80 --name my-nginx nginx:1.18
wrk -t32 -c1000 -d30s --latency http://localhost:8080
```

**Comment by akerouanton** [comment]
Hi @pzs-pzs, according to [this comment](https://github.com/moby/moby/issues/8817#issuecomment-1233753133), snap can play a role here. I'm pretty much not knowledgeable about snap, but I think there're some memory limitations put on dockerd and its children, maybe by default by snap.

As pointed out by [this other comment](https://github.com/moby/moby/issues/8817#issuecomment-697499931), the `oom_adj` score on `docker-proxy` is slightly lower than default so it can probably be killed by the kernel if dockerd (and its children) are under memory pressure.

Can you check if you have the following logs in your kernel logs (`sudo systemctl -k`): `Memory cgroup out of memory` and/or `Killed process`?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.

Also seems to duplicate:
- #8817
