### ISSUE TITLE
build image id file cannot be used to create container with containerd backend

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#45162]
### Description

This works with the graphdriver backend and fails with the containerd backend.

```
docker build --iidfile=img.id.txt - <<<"FROM busybox" && cid="$(docker create $(cat img.id.txt))"; docker rm "${cid}"
```

### Reproduce

In /etc/docker/daemon.json
```json
{
  "features": {"containerd-snapshotter": true}
}
```
 
```
docker build --iidfile=img.id.txt - <<<"FROM busybox" && cid="$(docker create $(cat img.id.txt))"; docker rm "${cid}"
Error response from daemon: No such image: sha256:1a9320a3ff3b63ecad8a0e6e5acc8b0c187f015cc7885ee51f13534a2ce775f1
```

### docker version

```bash
dockerd commit: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
```

### docker info

```bash
N/A
```

**Comment by cpuguy83** [comment]
This seems to happen when the image is untagged.

**Comment by cpuguy83** [comment]
The content is in the content store, however the snapshots look like they are GC'd.

**Comment by vvoland** [comment]
I can't reproduce this one on latest master - the image shouldn't be GC'ed with https://github.com/moby/moby/pull/45123.

> dockerd commit: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f

Wanted to see if this includes the mentioned PR, but it seems that it's the containerd revision, not moby 😄

**Comment by thaJeztah** [comment]
> > dockerd commit: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
> 
> Wanted to see if this includes the mentioned PR, but it seems that it's the containerd revision, not moby 😄


Hmm... interesting yes; was that a slip-up on your side, Brian, or something we did wrong in packaging somewhere? (https://github.com/containerd/containerd/commit/1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f)

**Comment by cpuguy83** [comment]
Oh dang not sure sure how I copied the wrong thing... commit is 6f14c8ee5a

**Comment by cpuguy83** [comment]
It's possible I just missed that commit. Let me rebuild and test.

**Comment by cpuguy83** [comment]
Ok, this looks good on HEAD.
Sorry for the noise.
