### ISSUE TITLE
docker build -t <tag> ... creates 2 image references 

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#45179]
### Description

With containerd snapshotters enabled, when building an image with a tag (`docker build -t`), 2 image references are created and displayed to `docker images` output.

### Reproduce

```console
$ docker build -t asdf --iidfile=img.id.txt - <<<"FROM busybox" && cid="$(docker create $(cat img.id.txt))"; docker rm "${cid}"
$ docker images
REPOSITORY                  TAG       IMAGE ID       CREATED         SIZE
asdf                        latest    d3469aef8c13   2 minutes ago   2.59MB
asdf                        latest    d3469aef8c13   2 minutes ago   2.62kB
```

### Expected behavior

There should only be one reference

### docker version

```bash
HEAD
```

### docker info

```bash
N/A
```

**Comment by thaJeztah** [comment]
Probably same as https://github.com/moby/moby/issues/44573(each platform is shown as a separate image (https://github.com/rumpl/moby/pull/113), and with attestations, an extra platform is created)

Also related;

- https://github.com/moby/moby/issues/44582

**Comment by cpuguy83** [comment]
Ah yes, the extra entry appears to be the attestation. Setting `--provenance=false` gives me a single image reference.

**Comment by vvoland** [comment]
This will be fixed by: https://github.com/moby/moby/pull/45124

**Comment by thaJeztah** [comment]
- should be fixed by https://github.com/moby/moby/pull/45124
