### ISSUE TITLE
I have an issue in docker-compose, but it may also an issue for docker(moby)

### ISSUE THREAD

**Issue by yingshaoxo** [moby/moby#45205]
### Description

https://github.com/docker/compose/issues/10397

**Comment by sam-thibault** [comment]
> But it seems like once I set network_mode=host, I can no longer use networks: other_bridge_network

Yes, this is expected behavior as mentioned in the linked issue:

> network_mode=host basically drops the container isolation on the networking stack, so obviously other networking feature get disabled the same way. Getting the requester IP from container has been reported on [docker/cli#2945](https://github.com/docker/cli/issues/2945)

Regarding the IP address see this discussion:
- https://github.com/moby/moby/issues/25526

I will close this issue.
