### ISSUE TITLE
non-blocking docs say oldest event is deleted when buffer is full, but the code says that newest event is deleted

### ISSUE THREAD

**Issue by PettitWesley** [moby/moby#45200]
### Description

The `non-blocking` docs say: https://docs.docker.com/config/containers/logging/configure/
> When the buffer is full and a new message is enqueued, the oldest message in memory is dropped. Dropping messages is often preferred to blocking the log-writing process of an application.

Which sounds very nice! This is what I expect for a ring buffer. 

But then if you read the actual code, it says that newest event is just discarded if the queue is full: https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160

### Reproduce

Read the docs for `non-blocking`: https://docs.docker.com/config/containers/logging/configure/

Then read the code for RingLogger: https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160

### Expected behavior

Docs should accurately describe how the code works. 

### docker version

```bash
Master branch on github: https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160
```

### docker info

```bash
Master branch on github: https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160
```

### Additional Info

Please update the docs.

**Comment by cpuguy83** [comment]
Yep docs are definitely wrong.
IIRC the implementation was changed during code review for performance reasons and complexity.

**Comment by sam-thibault** [comment]
@PettitWesley would you like to open a PR to fix the docs?
https://github.com/docker/docs/blob/main/config/containers/logging/configure.md

**Comment by PettitWesley** [comment]
@sam-thibault implemented: https://github.com/docker/docs/pull/16972

**Comment by thaJeztah** [comment]
Thank you @PettitWesley ❤️ ! As you already dug into the issue, we thought you would know best what needed to be updated (and take the credits!)

**Comment by PettitWesley** [comment]
New work is being done to change the buffer to be a proper ring buffer: https://github.com/moby/moby/pull/45982
