### ISSUE TITLE
non-blocking bug in AWSLogs driver code 

### ISSUE THREAD

**Issue by PettitWesley** [moby/moby#45217]
### Impact to AWS Customers

**Amazon ECS for EC2 only**. Amazon ECS on Fargate is not affected because as explained below, the log driver is always started in blocking mode and is wrapped by a buffer in non-blocking mode.

This can be seen in the aws/amazon-ecs-shim-loggers-for-containerd code, it initially starts the log driver in blocking mode always:

1. AWSLogs driver options are configured without mode thus using the default blocking mode: https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L132
2. Failure to create group/stream is logged and causes exit: https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L92
3. For non-blocking mode, after the log driver is initialized, it is wrapped by the shim logger implementation of the RingBuffer (largely copied from Docker code base): https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/blob/4bcb0f7126a3eee95a31d8a93e3b0a0d2f7c3e91/logger/awslogs/logger.go#L108

See this comment for testing data on the bug's impact to log loss: https://github.com/moby/moby/issues/45217#issuecomment-1509272084

### Summary

Currently `non-blocking` mode has a bug that can cause unnecessary log loss in the AWSLogs driver and thus may not be safe for customers to use. Unless customers configure a large enough value for both `max-buffer-size` and `awslogs-max-buffered-events`, logs can be lost. As explained in the deep dive section below, setting `awslogs-max-buffered-events` should not be required to prevent log loss. 

This bug occurs because the AWSLogs driver code attempts to [handle the `non-blocking` behavior itself](https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447) and drops events if its internal buffer is full. However, `non-blocking` mode is supposed to be implemented purely by the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) which wraps the log driver. 

When this bug causes log loss, the following message will be logged in the Docker Daemon logs:

```
Mar 02 21:40:55 ip-10-192-11-106.us-west-2.compute.internal dockerd[12093]: 
 time="2023-03-02T21:40:55.527136424Z" 
 level=error msg="Error writing log message" 
 driver=awslogs error=" buffer is full"
```

### Deep Dive Explanation

![AWSLogs buffering (3)](https://user-images.githubusercontent.com/29443996/228090532-73f0a0b0-bfa1-49c0-943a-d8fbeaca2fff.png)

The above diagram shows the series of buffers when the AWSLogs driver is used in `non-blocking` mode. The `non-blocking` feature ensures that the stdout and stderr pipes do not block in the application container. This is achieved via the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) which holds messages before the AWSLogs driver code is ready to accept them. While the Docker docs claim the oldest messages are removed when this buffer fills up, it is actually the newest message, see: [moby/moby:45200](https://github.com/moby/moby/issues/45200). The AWSLogs driver ingests the messages via its ingestion buffer which can be configured with `awslogs-max-buffered-events`. They are then moved to its send buffer for the API call to `cloudwatch:PutLogEvents`. 

The non-blocking behavior is implemented in Docker in the [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160). The [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) holds messages and has a [goroutine which attempts to continually ingest messages into the actual log driver](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L129). The call to ingest the message into the log driver can/should block until the log driver is ready to uptake the message. 

Unfortunately, the AWSLogs code has a [custom code path for `non-blocking` mode](https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447) wherein it discards the message if the call to uptake it from the [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160) would block. This means that messages are discarded if the ingestion buffer controlled by `awslogs-max-buffered-events` is full. This is entirely unnecessary and undesirable because the `non-blocking` behavior and discarding of messages is supposed to be implemented solely by the Docker [RingBuffer](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L160). *None of the other log drivers have custom code paths for `non-blocking` mode.* 

### Solution

Simply remove the lines of code here in the **Docker** upstream code base: https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L440-L447

And test the change.

### Reproduce

See above issue/design doc

### Expected behavior

non-blocking is handled entirely by RingBuffer and not in the AWSLogs Driver code. AWSLogs should not proactively lose logs when its internal buffer is full. 

### docker version

```bash
All.
```

### docker info

```bash
All.
```

### Additional Info

I will work on fixing this.

**Comment by PettitWesley** [comment]
Please assign this issue to me, I will be working on fixing it this week/next.

**Comment by bsousaa** [comment]
We are unable to assign but we added the "claimed" label to the issue. Thanks!

**Comment by PettitWesley** [comment]
You might be wondering, how bad is this bug? How much more log loss will you have with AWSLogs driver in non-blocking mode with the bug vs with the patch?

I created a simple log loss benchmarking framework here that runs in Amazon ECS: https://github.com/aws/aws-for-fluent-bit/pull/630

Below is the raw testing data. Non-trivial log loss doesn't occur until 6+ MB/s and the bug roughy doubles the percent log loss. 

---
| Raw Test Data |
| --- |
| 7MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 7000, percent lost, 13, number_lost, 66262, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, e22bae1324eb4e33b7e8e97c6d7f5e58, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:6, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 7000, percent lost, 12, number_lost, 62695, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, be8bd8b70fe84e5b889e570ab513f55f, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:6, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 7000, percent lost, 13, number_lost, 69124, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, 742625f5c90042b394e25373e3dedcb7, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:6, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 7000, percent lost, 14, number_lost, 70226, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, 13001b7a0f1f4357832395e77527ee06, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:6, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 7000, percent lost, 27, number_lost, 136940, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, 60150b916b154abd873005a5e5d46c68, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:12, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 7000, percent lost, 28, number_lost, 140675, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, e4afeb127ecf48c3a5ae8de70912b2e8, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:12, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 7000, percent lost, 27, number_lost, 139607, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, 4ec0e723b21e454db4ee823bafc5f65d, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:12, EC2, us-west-2 |
| 7MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 7000, percent lost, 27, number_lost, 139230, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=7000, a12c86ce112d4c0babb0e3cf4f51fc4a, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:12, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 5000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, 575e1e518c5446bcaaa0bfaac49dd54e, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:5, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 5000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, 890190b53d0a48de8ad08b655f4a648d, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:5, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 5000, percent lost, 0, number_lost, 53, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, ce0fe90b79924a1b82a6914a840034b7, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:5, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 5000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, 2153e266ab694320b601a1a894a953d1, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:5, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 5000, percent lost, 0, number_lost, 923, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, da86e7ef0d6447659e700bb048547a1d, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:11, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅ - 5000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, 1b5f6d2d599949139f824d3b309d3a5c, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:11, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅ - 5000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, de714dd723874748a9cfe99cfa2b7e9f, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:11, EC2, us-west-2 |
| 5MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 5000, percent lost, 0, number_lost, 61, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=5000, 121bdb73b0e64f64bd0eb4c52914eb20, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:11, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 6000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, d8fd7d0eaf254f0fad23c14f506a47b7, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:4, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 6000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, cda2e2731f1048e9a32a0015739e4eff, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:4, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 6000, percent lost, 0, number_lost, 81, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, 63121b376be34f7abe03ac016a6ac50a, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:4, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 6000, percent lost, 0, number_lost, 949, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, 215e353dea4648869cb782c876529cfe, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:4, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 6000, percent lost, 16, number_lost, 81698, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, bd7f15437a334f0387a64c81a1c99b1d, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:10, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 6000, percent lost, 16, number_lost, 81698, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, 1fa6254bbac642e7bf7ae4f92a6221cf, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:10, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 6000, percent lost, 16, number_lost, 81698, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, 88dbe80f481a4f95b5f1a68c636e38b1, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:10, EC2, us-west-2 |
| 6MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 6000, percent lost, 16, number_lost, 81774, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=6000, 0cd8929211eb40bc9b3f332a4ba83c57, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:10, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 8000, percent lost, 20, number_lost, 103549, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, b9711a1ad6c6460a9550a98dddd6e988, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:3, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 8000, percent lost, 21, number_lost, 109525, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, ebf2bde8bca94b44b3f7e9de5db288d0, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:3, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 8000, percent lost, 23, number_lost, 116293, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, a693833a66ed42e0bffdadd662127cbd, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:3, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 8000, percent lost, 24, number_lost, 123332, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, 25df1838bcef43738b9006fe78ea00e1, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:3, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 8000, percent lost, 36, number_lost, 182000, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, a3c68271381a44359d956e8e65bd5252, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:9, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 8000, percent lost, 36, number_lost, 184997, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, 8c5f394a686445cd99ff35cd6baa45c3, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:9, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 8000, percent lost, 36, number_lost, 184997, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, d18bfe012ae7478c9ae429da1eccaf5c, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:9, EC2, us-west-2 |
| 8MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 8000, percent lost, 36, number_lost, 182999, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=8000, 0f21229bc0e144a69ede6d74bd598ed0, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:9, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, a584c6b7a4f14ff5b4229c5364db01f1, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:8, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, d87f27aa029c4701bd9d45aa8b614237, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:8, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, fdd33bcbc33b48f2bfaed539b1a52822, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:8, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER 🚨 - 4000, percent lost, 0, number_lost, 875, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, 04f80346774d4ba1a166444c4149eb7b, awslogs-benchmarking-ec2-bug, awslogs-benchmarking-test-the-bug:8, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, a1aa7a0b77e14cecb5851894e1487165, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:2, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, 02fe600fb13447189908a8132c783ccc, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:2, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅ - 4000, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, f7afa249420a468e984134061bb218ef, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:2, EC2, us-west-2 |
| 4MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨 - 4000, percent lost, 0, number_lost, 97, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, THROUGHPUT_IN_KB=4000, d31fb764040341128b134d49855d8f93, awslogs-benchmarking-ec2-patched, awslogs-benchmarking-test-the-patch:2, EC2, us-west-2 |
| 2MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, 090583796e82414c81ee46fc7fd8ae6a, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, 2aef4723943747b391962633f83b58ef, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, b6fb55b9c43d46e69e0654e7777f0e8a, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, f3d8afbbca204e4ead8c6c4350b776e4, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, 5e10e758b56141a78ff2251bf3050609, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, 0420db8f3812418b81c3a6f1f989d17c, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, a6cf9312f81f4f63aa383ed399fa8ac6, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 2MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 500000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=500, SIZE_IN_MB=1, deef057b069444a397f447c77c59758b, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 225313df2c8d426cb06dc7adf6007ffb, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 541406c3c01349bb8138d5f60ff1d2c6, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 93c5c7eaf58e4057b65775bce81a04bb, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_BUG_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 6319f50c84fb4ceaa230c5559b294a63, awslogs-benchmarking-ec2-bug, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 29382447514542e9b6f9ec8524f11d05, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨, percent lost, 0, number_lost, 999, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 760ccdef117c40bba3b6ced8f2a3f287, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  999 |
| 1MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER ✅, percent lost, 0, number_lost, 0, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 0b2a8ac0a1e0407a96dca9ceaf8ee5c0, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  0 |
| 1MB_1KB_AWSLOGS_PATCH_DEFAULT_BUFFER 🚨, percent lost, 0, number_lost, 999, total_input_record, 100000, duplicates, 11, group=awslogs-benchmarking-output stream=awslogs-benchmarking-output TOTAL_SIZE_IN_MB=100, SIZE_IN_MB=1, 45e3fd61e55d49b6a0bc8f792680472a, awslogs-benchmarking-ec2-patched, us-west-2 |
| missing,  999 |
---
