### ISSUE TITLE
fatal error: checkptr: converted pointer straddles multiple allocations: Moby still uses github.com/docker/libkv/store/boltdb that is unmaintained since 5+ yrs

### ISSUE THREAD

**Issue by thediveo** [moby/moby#45255]
### Description

The Moby code base not least in its integrated network plugins uses an unmaintained boltdb imported from `github.com/docker/libkv/store/boltdb` via `github.com/moby/libnetwork/datastore`. This unmaintained boltdb implementation is known to have an invalid unsafe pointer operation that writes beyond the end of an allocated object and triggers a "fatal error: checkptr: converted pointer straddles multiple allocations" when running any unit tests using the libkv store and its boltdb under the race detector. For instance, see: https://github.com/golang/go/issues/54690

The problem now is that there is no easy way (as far as I can tell) in swapping in the maintained fork from `etcd-io/bbolt`, as libkv needs to be wired up accordingly. Not least, this issue pops up when writing custom plugins for Docker where the boltdb should be used, as in its current situation libkv's unsafe pointer operation is known to be faulty, but `etcd-io/bbolt` would require a large rewrite where the `docker/libkv` layer essentially needs to be duplicated.

- Is this a moby issue or instead a docker issue?
- If the latter, where to correctly report and will this then get picked up by the moby project?

### Reproduce

run Moby-related unit tests, such as for networking plugins with the race detector enabled.

### Expected behavior

Moby unit tests should pass with the race detector enabled.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 48
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-69-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
 Name: ubuntu
 ID: JBAD:ID3T:XKGK:NA7Q:UNSY:N56R:VZTU:5MGM:5W6N:C6XV:2JKG:R3KU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I think we're already using a version of libkv that uses the new location;
https://github.com/moby/moby/blob/d2a5948ae839f6f06a9eee68924c64328f155ccc/vendor.mod#L40

https://github.com/moby/moby/blob/d2a5948ae839f6f06a9eee68924c64328f155ccc/vendor/github.com/docker/libkv/store/boltdb/boltdb.go#L15

**Comment by thaJeztah** [comment]
Yeah, so the plan is to ultimately have a proper `go.mod` in this repository, which would make go mod pick the expected minimum version, but .. it's complicated, and still requires a lot of work to pull that off (we have a "rought" concensus on how to get there, but there's still a lot of details to fill in). Currently, renaming our `vendor.mod` to `go.mod` would make the world explode, so we cannot (yet) do so. (the `vendor.mod` is a "regular" `go.mod`, but not named as that, and used with `go mod -modfile=vendor.mod`).

I'm not sure if I have access on that repository, but can check if there's interest in tagging a release. That said, I think we should (probably) be able to remove that dependency altogether. As far as I'm aware, libkv was primarily created for "pluggable" discovery backends for overlay networks. Looking at the current use of it, it's now _only_ used for `boltdb` (no other drivers used), so perhaps we can replace it with an (internal) package;

```bash
git grep "github.com/docker/libkv" -- ':!vendor*'
libnetwork/bitseq/sequence_test.go:     "github.com/docker/libkv/store"
libnetwork/bitseq/sequence_test.go:     "github.com/docker/libkv/store/boltdb"
libnetwork/config/config.go:    "github.com/docker/libkv/store"
libnetwork/datastore/cache.go:  "github.com/docker/libkv/store"
libnetwork/datastore/datastore.go:      "github.com/docker/libkv"
libnetwork/datastore/datastore.go:      "github.com/docker/libkv/store"
libnetwork/datastore/mock_store.go:     "github.com/docker/libkv/store"
libnetwork/drivers/overlay/overlay_test.go:     "github.com/docker/libkv/store"
libnetwork/drivers/overlay/overlay_test.go:     "github.com/docker/libkv/store/boltdb"
libnetwork/store.go:    "github.com/docker/libkv/store/boltdb"
libnetwork/store_linux_test.go: "github.com/docker/libkv/store"
libnetwork/store_test.go:       "github.com/docker/libkv/store"
```

**Comment by thediveo** [comment]
Aren't swarm-related plugins using etcd or other DB backends, depending on a customer's daemon configuration?

**Comment by thediveo** [comment]
Shall I close this issue? From my point of view, the current situation has been clarified and I got the necessary information to successfully build Docker plugins using `libkv`.
