### ISSUE TITLE
Docker unresponsive, containers continue to run. Error 'too many open files' - Btrfs

### ISSUE THREAD

**Issue by ilike2burnthing** [moby/moby#45253]
### Description

Been having an issue for the last ~6 months (there didn't seem to be any major update that triggered it), occurring anywhere between a few days to a few weeks. Initially did troubleshooting on the Asustor community forum (many thanks @Nazar78) - https://forum.asustor.com/viewtopic.php?f=184&t=13602 (see for steps and some logs). Not sure the issue ultimately lies with Docker, but might as well start here.

Periodically when accessing Portainer it will just freeze. Running `docker ps` or other Docker commands just times out, so the issue is definitely with Docker, not Portainer. Meanwhile however, all other containers are running fine.

Running `start-stop.sh stop` to shut down Docker also times out. Ultimately I just had to kill `docker` and then run `start-stop.sh start`.

A couple of short outputs when Docker is unresponsive:

<details>
<summary>ps -ef|grep docker</summary>

```text
/volume1/.@root$ ps -ef|grep docker
 1427 root      0:00 docker ps -a
 3862 root      0:00 grep docker
 7169 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 18989 -container-ip 172.18.0.5 -container-port 8989
 7186 root      0:02 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 6120c597ddfb0c74d53d81e1f1477a19f039448bd9ea0ce95597a17917278c03 -address /var/run/docker/containerd/containerd.sock
11274 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 38181 -container-ip 172.18.0.7 -container-port 8181
11301 root      1:07 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 9ec13083a55b9896219d4a66f14cb25943f1f29eb7c27998d946fd21c99ee81b -address /var/run/docker/containerd/containerd.sock
11627 root      2:12 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 6ecf6e7fb217d14de459af522b8bfbebecccbab37e688eac325e1e5a1015f942 -address /var/run/docker/containerd/containerd.sock
12479 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9091 -container-ip 172.18.0.2 -container-port 9091
12494 root      1:41 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 151e8565bcbdf41cdd742fd0d42f11514fe19f5a0c37e4c041c755b3ef28136a -address /var/run/docker/containerd/containerd.sock
16412 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8191 -container-ip 172.18.0.8 -container-port 8191
16427 root      0:15 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 06e66bb0332003a1fc70856153f80b393bc1675c949d5ef0df96dcdde00a2b2e -address /var/run/docker/containerd/containerd.sock
16818 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 17878 -container-ip 172.18.0.6 -container-port 7878
16846 root      2:09 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id d27ef4bf12f9a432f9b3b0ad5c87919c8e18bef919cc176ad55658eb6e2f2b8c -address /var/run/docker/containerd/containerd.sock
21463 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 19117 -container-ip 172.18.0.3 -container-port 9117
21492 root      0:12 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id e17f42f06ad883c1a406199ea15d41e007123804bee1c42aee86e4c54ca115dd -address /var/run/docker/containerd/containerd.sock
21854 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 19118 -container-ip 172.18.0.4 -container-port 9117
21876 root      0:11 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 9b7ade4d6a1cbb89d79c8a4faf6d466369db232847ccb7e36050b0210fa835b9 -address /var/run/docker/containerd/containerd.sock
22902 root     37:17 /usr/local/AppCentral/docker-ce/bin/dockerd --data-root /usr/local/AppCentral/docker-ce/docker_lib/
22910 root     10:50 containerd --config /var/run/docker/containerd/containerd.toml --log-level info
31542 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 19943 -container-ip 172.17.0.3 -container-port 9443
31590 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 19900 -container-ip 172.17.0.3 -container-port 9000
31643 root      0:00 /usr/local/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 19800 -container-ip 172.17.0.3 -container-port 8000
31661 root      2:48 /volume1/.@plugins/AppCentral/docker-ce/bin/containerd-shim-runc-v2 -namespace moby -id 76e95f3cdfc354a588077b19bb16d016916551e34b7b3830f24eaf656133d520 -address /var/run/docker/containerd/containerd.sock
```
</details>

<details>
<summary>mount|grep docker</summary>

```text
/volume1/.@root$ mount|grep docker
/dev/md1 on /volume1/.@plugins/AppCentral/docker-ce/docker_lib type btrfs (rw,relatime,ssd,discard,space_cache,subvolid=259,subvol=/.@plugins)
/dev/md1 on /volume1/.@plugins/AppCentral/docker-ce/docker_lib/btrfs type btrfs (rw,relatime,ssd,discard,space_cache,subvolid=259,subvol=/.@plugins)
nsfs on /var/run/docker/netns/ccec822d0a17 type nsfs (rw)
nsfs on /var/run/docker/netns/7059d189af74 type nsfs (rw)
nsfs on /var/run/docker/netns/6086e23c40ec type nsfs (rw)
nsfs on /var/run/docker/netns/1e4db016f43d type nsfs (rw)
nsfs on /var/run/docker/netns/af8b1bb4cec0 type nsfs (rw)
nsfs on /var/run/docker/netns/9a8df3764918 type nsfs (rw)
nsfs on /var/run/docker/netns/02c2fd9d67d0 type nsfs (rw)
nsfs on /var/run/docker/netns/a01210693e56 type nsfs (rw)
nsfs on /var/run/docker/netns/cc11f29537d5 type nsfs (rw)
```
</details>

@Nazar78 replicated the issue on a Btrfs partition, having previously had no issues one ext4. `docker ps -aq` had to be cancelled and `tail ~/docker.log` returned `http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files;`. It was only when having run `chroot ~/.chroot prlimit --pid $(pidof dockerd) --nofile=10240:10240` that Docker became responsive again (previously the soft limit was 1024 and the hard limit 4096).

Any help would be appreciated, even if it's pointing to a more likely source for a solution (Asustor? Btrfs?).

### Reproduce

1. install Docker on a Btrfs system
2. add a few containers
3. wait for a few days-weeks
4. access Portainer (or likely just docker)
5. freeze
6. try to stop docker
7. fail
8. have to kill docker
9. restart docker/system
10. containers run fine

### Expected behavior

Behaviour on Btrfs is the same as on ext4 (i.e. this doesn't happen).

### docker version

```bash
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:21:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:27:32 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.13
  GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.15.1)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.22
 Storage Driver: btrfs
  Build Version: Btrfs v5.10.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 78f51771157abb6c9ed224c22013cdf09962315d
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.13.0.x
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.857GiB
 Name: REDACTED
 ID: REDACTED
 Docker Root Dir: /volume1/.@plugins/AppCentral/docker-ce/docker_lib
 Debug Mode: false
 Username: REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment]
>  It was only when having run `chroot ~/.chroot prlimit --pid $(pidof dockerd) --nofile=10240:10240` that Docker became responsive again (previously the soft limit was 1024 and the hard limit 4096).

The docker daemon (or, when run as a separate service; containerd) will start many child-processes (depending on how many containers are run). The default limits are too low for that.

How is your daemon installed? Is it running as a systemd service? The systemd units that ship with `docker-ce` packages set these limits to "unlimited" (`infinity`) to disable accounting (and overhead involved);

- dockerd: https://github.com/moby/moby/blob/v23.0.2/contrib/init/systemd/docker.service#L29-L31
- containerd: https://github.com/containerd/containerd/blob/v1.6.20/containerd.service#L29-L33

The other scripts (but no longer used in default installs for docker-ce, which defaults to be run as systemd unit) also have similar options set; https://github.com/moby/moby/blob/v23.0.2/contrib/init/sysvinit-debian/docker#L96-L104

There may be issues with certain containers related to that (see the conversation on https://github.com/containerd/containerd/pull/7566), part of which is due to a regression in Go 1.19 and up (to be solved in the next release of Go), so instead of `infinity`, you could set the previously hard-coded default (`1048576 `), or one of the suggestions from https://github.com/containerd/containerd/pull/7566#discussion_r1148455486

**Comment by ilike2burnthing** [comment]
I'm going to hazard a guess at not a systemd service:

```bash
/$ systemctl --type=service
-sh: systemctl: not found
/$ systemd
-sh: systemd: not found
```

Apologies, *nix isn't really my thing, this NAS is the closest I've gotten, and even then I'm largely just installing applications from their 'store' App Central and using Portainer to add containers.

Happy to run commands to get you more information, or @Nazar78 might be able to answer some questions when they get some free time.

Is there a reason we'd be seeing a difference between Btrfs and ext4?

As I appear to be using `go1.18.9`, would the `1.19` regression be relevant? Was it backported?

**Comment by thaJeztah** [comment]
> Apologies, *nix isn't really my thing, this NAS is the closest I've gotten, and even then I'm largely just installing applications from their 'store' App Central and using Portainer to add containers.

Ah! Yes, not very familiar with those setups either; I know various NAS products ship with "some flavour" of the Docker Engine, but most (all?) of them build those themselves, and it's not always clear how they're built (build-time dependencies etc), and how they're configured. Unfortunately, sometimes the devil is in the detail, which can lead to situations where "things work" ... "until they don't" (such as the case you seem to be running into).

If it's  part of their "commercial" offerings, definitely also worth opening a support ticket / bug-report for.

> As I appear to be using go1.18.9, would the 1.19 regression be relevant? Was it backported?

To my knowledge that particular regression was only in go1.19 and up. It was a change the Go maintainers made to speed up their own tooling (it discards the soft limit, and raises it to be always the same as the hard limit), but a side-effect of that was that any process that's started from a Go binary _also_ gets the soft limit set to the hard limit. They were aware (and called out) that risk, but  decided to ignore it at the time.

Some of our (and containerd) maintainers managed to convince them that it wasn't a "great thing to do", and a patch was accepted (which hopefully gets into the next go 1.19.x and 1.20.x patch releases).

**Comment by ilike2burnthing** [comment]
Yes, the developer is listed as `Docker`, but the maintainer as `Asustor`, so I could definitely see them having added their own special sauce.

I'll open a support ticket with them later today/start of tomorrow, and will update here for any future weary travellers. Up to you if you want to leave this issue open until then, or close it for sake of tidiness *[stares at the 4k open issues...]*. 😉 

Many thanks for the clarity, keep up the good work.

**Comment by thaJeztah** [comment]
> stares at the 4k open issues...

🙈 yes, there's many (and _many_ that may not have a good producer, and may not be bugs at all); we're still very much on the fence on adding a "stale bot", but those often give a somewhat horrible experience, and we want to avoid closing "still relevant" issues (with useful information for others), or close issues without any interaction (or that could still be picked up by contributors). In the end; closing those tickets doesn't make them go away (just slightly less visible); we do go through them daily to look for (potentially) urgent issues (or useful feature requests to consider), but it .. takes time 😂 

> or close it for sake of tidiness

Let me go ahead and close this one to ever so slightly lower that number! 😅 From the above, we (very likely) understand the root-cause, and that one is not something we can fix in this repository.

Feel free to continue the conversation though after I closed (or to post updates if that may help others) 👍

**Comment by ilike2burnthing** [comment]
For whatever it's worth, I'll add my experience to the midst.

I'm one of the maintainers for Jackett and our bot closes issues after 7 days if we've added specific labels (`More information needed` or `Full logs needed`) and there has been no response from OP. We don't use a generic stale bot that closes everything after X amount of time. Our oldest open issue is from 2016.

This means that we don't have to chase up abandoned issues that are typically just troubleshooting, or which were so niche as to be solely dependent on specific user information.

On the other hand I have contributed to other repos where they do use a stale bot, and while it's easier to focus on the fewer remaining open issues, I have found myself bumping a few just so someone might eventually tackle them (because realistically, no one is going through closed issues to work on them out of the blue).

A possible compromise would be using a stale bot and also heavily utilising Projects, but not auto-archiving issues when they're closed.

Hopefully that's of some use 😉
