### ISSUE TITLE
Authorisation request does not seem to be using the right client certificate

### ISSUE THREAD

**Issue by jm-bertheas-datailor** [moby/moby#45327]
### Description

We have a docker registry and a token provider (gitlab) configured behind a reverse proxy, and it's necessary to be authenticated on the reverse proxy with a client certificate/key pair on the docker registry and the token provider with different client certificate/key pairs.

When we log on the registry with a 'docker login' command, the client certificate/key pair corresponding to the docker registry (stored in /etc/docker/certs.d/<registry>) is well sent to the reverse proxy, and the request is correctly transfered to the registry. The registry responds to acquire a auth token near the token provider. Here, all is ok...

But after that, the docker engine send an authorisation request to the token provider with the wrong client certificate/key pair => always the client certificate/key pair of the docker registry instead of the client certificate/key pair of the token provider. Then, the authorisation request is rejected by the reverse proxy!

### Reproduce

1. configure a docker registry and a token provider behind a reverse proxy needing different client certificate/key pairs on the docker registry and the token provider.

2. store the client certificate/key pairs on local host to /etc/docker/certs.d like:
/etc/docker/certs.d/registry.mydomain.com/client.cert
/etc/docker/certs.d/registry.mydomain.com/client.key
/etc/docker/certs.d/auth.mydomain.com/client.cert
/etc/docker/certs.d/auth.mydomain.com/client.key

3. docker login registry.mydomain.com

### Expected behavior

'docker login' command must succeed

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:05:48 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:05:48 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 96
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-38-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: jbd-T470
 ID: Q5PW:3KRE:6Q65:SGKQ:VRS4:NB6J:ZHT6:MWZT:GE5H:6R46:YCGA:KSCT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

This problem is quite similar to issue #13584

**Comment by jm-bertheas-datailor** [comment]
This problem also concern image pulling and pushing

**Comment by corhere** [comment]
Not a bug - support for multiple client identities per registry would be a misfeature which would only enable use cases where the daemon identifies to the token-auth service as a user, irrespective of the user running `docker login`.

Please open a new _feature request_ describing your use-case: `docker login` with Teleport mutual TLS for user credentials.
