### ISSUE TITLE
docker fails to start after upgrade to 23.0.4

### ISSUE THREAD

**Issue by betanummeric** [moby/moby#45356]
### Description

I updated to docker-ce `5:23.0.4-1~debian.11~bullseye` (tested with a fresh installation) and now dockerd fails to start:
```
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool "" subpool "100.64.0.0/26": Invalid Address SubPool
```
It worked with the previous version (`5:23.0.3-1~debian.11~bullseye`).

My `/etc/docker/daemon.json` contains:
```json
{
  "fixed-cidr": "100.64.0.0/26"
}
```

I suspect this is caused by #45246.

### Reproduce

Install docker as explained in the issue description and `systemctl start docker`.

### Expected behavior

normal docker startup

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Comment by betanummeric** [comment]
Docker starts again when specifying a `bip` in `/etc/docker/daemon.json`:
```json
{
  "bip": "100.64.0.1/26",
  "fixed-cidr": "100.64.0.0/26"
}
```
Was the `bip` config option made mandatory?
I would not expect such changes in a patch release.

**Comment by thaJeztah** [comment]
@akerouanton ptal

**Comment by akerouanton** [comment]
@betanummeric Can you confirm that you rebooted your server/computer between the update of `docker-ce` and the time you actually encountered this issue?

**Comment by betanummeric** [comment]
@akerouanton `apt upgrade` restarted `docker.service`, running into the error, before I had the time to reboot.

I tried it again today with a fresh installation of the versions mentioned earlier, with and without a reboot, but I could not reproduce the error. The system where I got the error had some containers (and hence probably some network state), but I am not sure what parts are relevant to the error.

**Comment by akerouanton** [comment]
> apt upgrade restarted docker.service, running into the error, before I had the time to reboot.

Not sure why, but it looks like your default bridge `docker0` was not there after you did `apt upgrade` :thinking: I don't think there's any other way to trigger that bug.
