### ISSUE TITLE
Buddy cli cannot be installed

### ISSUE THREAD

**Issue by heycrayonxiaoxin** [moby/moby#45369]
### Description

Due to multiple issues with CentOS running in Docker environment, this operating system is currently not supported.

docker.version: 23.0.4
docker-compose.version: v2.17.2

### Reproduce

buddy install

### docker version

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
```

**Comment by sam-thibault** [comment]
Can you share the error message/output?

**Comment by heycrayonxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/110439434/233812726-8456f7ee-70a0-42a8-9f33-d62e80bb9c5b.png)

This image shows the error message after executing the Buddy Install command

**Comment by heycrayonxiaoxin** [comment]
> Can you share the error message/output?


![](https://user-images.githubusercontent.com/110439434/233812726-8456f7ee-70a0-42a8-9f33-d62e80bb9c5b.png)

This image shows the error message after executing the Buddy Install command

**Comment by sam-thibault** [comment]
Some workarounds are described in the issue mentioned in the installer output:
- https://github.com/moby/moby/issues/40835

However, it seems the installer does not attempt the install.  These appear to be CentOS 7 issues, not fixes we can make in the Docker engine.  I will close this issue in favor of the issue above.
