### ISSUE TITLE
Cancelling pulls

### ISSUE THREAD

**Issue by mark-dr** [moby/moby#45433]
### Description

When I ask the engine to pull an image via `/images/create` with `fromImage`, it streams back update events. If I close the HTTP connection, the pull is cancelled. As far as I know, there is no other way to cancel a pull.

Suppose I'm making a UI application (like Docker Desktop, which I'm a maintainer of), and I want to be able to cancel pulls initiated through the UI. Currently, that's difficult - it's necessary to maintain a list of open HTTP requests, with mechanisms for searching and closing them, effectively duplicating data that already exists in the engine. It would be better if we could cancel pulls without needing a reference to any open HTTP connections. This becomes more valuable in combination with #45434.

### Proposal

- Add a new API endpoint (dubious strawman suggestion: `/images/create/cancel`). If I post to this, passing a string in the same format as the `fromImage` parameter of `/images/create`, any matching in-progress pulls should abort.
- When a pull is cancelled, any currently open HTTP connections from matching calls to `/images/create` should emit a cancellation event, and then the connection should close.

### Related issues

- #45434

**Comment by corhere** [comment]
> it's necessary to maintain a list of open HTTP requests, with mechanisms for searching and closing them, effectively duplicating data that already exists in the engine.

That data does not currently exist in the engine. The Go runtime and HTTP server know about all open client requests, but that information is not made available to application code, nor is there a way to look up open requests for a particular API endpoint. We would have to implement application code which maintains a list of open image-create requests with mechanisms for searching and canceling them, same as you would have to do on the client side.

Outside of Docker Desktop, the ability for one client to cancel another client's image pull seems like a misfeature to me. Why should one user with Engine API access be able to interfere with another user's pull? If I'm not mistaken, Docker Desktop already proxies the Engine API for things like the mount-rewriting magic; could the ability to cancel pulls not be implemented there?

**Comment by mark-dr** [comment]
> Outside of Docker Desktop, the ability for one client to cancel another client's image pull seems like a misfeature to me

Yes, I think there are two classes of engine clients:

- Tools like Docker Desktop, which act as management interfaces for the engine (among other features)
- Tools that aren't concerned with the engine itself, just with their own images and containers

I agree that the latter shouldn't be able to interfere with each other, although I think it's fair to point out that they already can; stopping/deleting another client's containers feels at least as undesirable as cancelling another client's pulls.

> If I'm not mistaken, Docker Desktop already proxies the Engine API for things like the mount-rewriting magic; could the ability to cancel pulls not be implemented there?

Good question. I'll check with my colleagues.

**Comment by mark-dr** [comment]
Your suggestion about implementing cancelling in the proxy is a good one, I'll close this issue to focus on that. Thanks!
