### ISSUE TITLE
Api for "images/create" used to work with no X-Registry-Auth Header when part of an organization

### ISSUE THREAD

**Issue by ddevoogt** [moby/moby#45448]
### Description

Using the api for `images/create` like so:
```
curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=amazon%2Fdynamodb-local&tag=latest' -d ""
```
Responds with `Please run 'docker login'` even if i am already logged in the current version of Docker (*docker desktop 4.19.0* and *docker engine 23.0.5*. We use Docker Desktop and our company [enforces sign-in](https://docs.docker.com/docker-hub/configure-sign-in/). In the previous Docker Desktop bundle (4.18.0, 20.10.24) This worked fine, pulling the necessary image.

We found originally using [Docker.Dotnet SDK](https://github.com/dotnet/Docker.DotNet/issues/631).

Perhaps there is way to use the existing login?

### Reproduce

1. Be part of a docker organization
2. Have the sign-in be enforced
    - See [Enforce sign-in for Desktop](https://docs.docker.com/docker-hub/configure-sign-in/)
3. Sign out and shut down docker
4. Start up (it should require you to sign in now)
5. Sign in to desktop
6. For good measure, open your command line and sign in using `docker login`
7. Now run this curl command

``` 
curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=amazon%2Fdynamodb-local&tag=latest' -d ""
```

### Expected behavior

Should pull the image or state the image is already up to date, instead it says `Please run 'docker login'`

### docker version

```bash
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:12:52 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:14 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/i53707/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/i53707/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/i53707/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/i53707/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/i53707/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/i53707/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/i53707/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/i53707/.docker/cli-plugins/docker-scout

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 21
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: fbe666d3-6e23-43b4-8595-e789e1957260
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Previous Docker suites this worked
**docker version (When it worked)**
```
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:21:21 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:17:07 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**docker info (When it worked)**
```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.4)
  compose: Docker Compose (Docker Inc., v2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.19)
  init: Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.2)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.9.0)

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 21
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: NG3N:YN5H:HKEC:3QRN:45S3:EKGW:GVUO:7VLU:B4KR:XO23:O3VI:OJ54
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Sample of command ran when it works**
```
➜  ~ curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=amazon%2Fdynamodb-local&tag=latest' -d ""

{"status":"Pulling from amazon/dynamodb-local","id":"latest"}
{"status":"Digest: sha256:bd10279256d657b3637862ab813b3b7f1c3438395ac318ccd99b62c17f35d2d3"}
{"status":"Status: Image is up to date for amazon/dynamodb-local:latest"}
➜  ~
```

**Sample of command ran when it fails**
```
➜  ~ curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=amazon%2Fdynamodb-local&tag=latest' -d ""

Please run 'docker login'
➜  ~ docker login
Authenticating with existing credentials...
Login Succeeded

Logging in with your password grants your terminal complete access to your account.
For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/
➜  ~ curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=amazon%2Fdynamodb-local&tag=latest' -d ""

Please run 'docker login'
```

**Comment by cpuguy83** [comment]
`docker login` works for the docker CLI. It stores credentials locally and sends them along in API requests when needed.
If you are going to use curl, you must pass those credentials along with the request.

The message from the daemon should definitely be updated.

**Comment by ddevoogt** [comment]
Whats interesting, that this wasn't required in Docker Engine 20.10.24. I there a build/ticket that we can link/reference to see when this changed? I seems like a security update?

**Comment by cpuguy83** [comment]
There is no change to docker.
Maybe an org change on Dockerhub or image changing from public to private?

**Comment by cpuguy83** [comment]
For instance, here is an example pulling busybox:

```
curl --unix-socket /var/run/docker.sock -X POST 'http:/v1.41/images/create?fromImage=busybox&tag=latest' -d ""
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Downloading","progressDetail":{"total":2295},"progress":"[\u003e                                                  ]       0B/2.295kB","id":"b5d6fe071263"}
{"status":"Download complete","progressDetail":{"hidecounts":true},"id":"b5d6fe071263"}
{"status":"Exists","progressDetail":{"hidecounts":true},"id":"acaddd9ed544"}
{"status":"Exists","progressDetail":{"hidecounts":true},"id":"7cfbbec8963d"}
```

**Comment by ddevoogt** [comment]
I am able to reproduce both failures and success if i switch between either Docker Desktop Bundle [4.19.0](https://docs.docker.com/desktop/release-notes/#4190) and [4.18.0](https://docs.docker.com/desktop/release-notes/#4180). So any changes in Dockerhub doesn't make sense to me and the image that i am pulling is the same too, so it cant be switching from public to private either.

**Comment by cpuguy83** [comment]
Actually I can pull your image without auth as well.

Maybe there's some proxy in docker desktop causing this.
Definitely nothing in the in the core engine or CLI.

/cc @thaJeztah to route this to the right folks.

**Comment by thaJeztah** [comment]
> Responds with `Please run 'docker login'`

That error comes from Docker Desktop, and is on purpose if the [enforce sign-in](https://docs.docker.com/docker-hub/configure-sign-in/) option is enabled.

I must admit that the error itself isn't very informative as to "why the error is produced". I have not worked on the feature myself, but located the part in the Docker Desktop code where this error is produced, and will have a look at improving that error.

> In the previous Docker Desktop bundle (4.18.0, 20.10.24) This worked fine, pulling the necessary image.

This was actually a bug; with the "enforce sign-in" option enabled, operations on the Docker Engine should be restricted. Previous versions of Docker Desktop did not restrict this at the API, which could be used as a "loophole" to avoid that policy. 

Given that this is not a bug, and not something that can be fixed in this upstream repository (as this is something specific to Docker Desktop), I'll close this ticket, but feel free to continue the conversation.

Also feel free to open a support ticket (or ask your company to) if there are specific use-cases where "enforce sign-in" is enabled, but access to the API should not be restricted.

**Comment by ddevoogt** [comment]
It would be nice if there were api to make calls with the already logged in user with docker. Or even api to run ```echo https://index.docker.io/v1/ | docker-credential-desktop get``` which caches the credentials for the next commands. We don't actually use curl to make these calls, we use a Docker.Dotnet client for integration tests.  I created a [ticket](https://github.com/dotnet/Docker.DotNet/issues/631) in hopes to "fix" this or come up with another solution that has minimal impact on the code. At least with say aws login, you can can use any api/cli with "default" credentials and it goes through the credential chain (Envs, .confs, etc). Any suggestions?

**Comment by thaJeztah** [comment]
> It would be nice if there were api to make calls with the already logged in user with docker. Or even api to run echo https://index.docker.io/v1/ | docker-credential-desktop get which caches the credentials for the next commands. 

The engine itself (which serves the API server) does not have access to the credentials, and authentication with registries is stateless (each API call can use different credentials), so from an "engine" (this repository) perspective, I don't think that will be an option (and Docker Engine itself (standalone) won't have this issue, as it's a restriction applied in Docker Desktop).

For Docker Desktop; not sure if they'd want to automatically apply credentials to API requests; doing so would be a security risk, as now it would be possible to hit the API (without credentials) and still make authenticated requests (push/pull) to a registry.

That said, there _have been_ some internal discussion to decouple "desktop authentication" (which is used to apply company policies/restrictions) from "registry authentication" (used for push/pull); with that, it would be possible to perform registry requests without authentication (if those requests don't require authentication); of course, that would also mean that such requests would have rate-limits applied based on non-authenticated pulls.

For your case, I would (if possible) recommend passing authentication when using Docker.Dotnet
