### ISSUE TITLE
Getting docker compose error using devcontainer with docker-ce-cli 23.0.6

### ISSUE THREAD

**Issue by hpe-ykoehler** [moby/moby#45497]
### Description

+ devcontainer up --workspace-folder /var/lib/jenkins/workspace/ton_cookiecutter-krypton-c_PR-14/cookiecutter-krypton-c-test-project --remove-existing-container
15:12:47  @devcontainers/cli 0.35.0. Node.js v18.16.0. linux 3.10.0-1160.62.1.el7.x86_64 x64.
Error: Command failed: docker compose -f /var/lib/jenkins/workspace/ton_cookiecutter-krypton-c_PR-14/cookiecutter-krypton-c-test-project/.devcontainer/docker-compose.yml --profile * config
    at Wc (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:867)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Cse (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1882:1370)
    at async Ase (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1864:3170)
    at async $se (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:2799)
    at async Ah (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:3741)
    at async aae (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17376)
    at async oae (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17117)
{"outcome":"error","message":"Command failed: docker compose -f /var/lib/jenkins/workspace/ton_cookiecutter-krypton-c_PR-14/cookiecutter-krypton-c-test-project/.devcontainer/docker-compose.yml --profile * config","description":"An error occurred retrieving the Docker Compose configuration."}

### Reproduce

Use devcontainer to bring up a container, note that this was working fine before and right now I can only point to docker-ce-cli new release.

### Expected behavior

This is the docker-compose

+ cat /var/lib/jenkins/workspace/ton_cookiecutter-krypton-c_PR-14/cookiecutter-krypton-c-test-project/.devcontainer/docker-compose.yml
version: '3'
services:
  krypton-c-env:
    image: docker.arubacorp.net:8443/base-krypton-c:mainline-53

    init: true
    privileged: true

    # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
    # mounts are relative to the first file in the list, which is a level up.
    volumes:
      - ../..:/work

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

#    user: aos-dev
    command: sleep infinity
    extra_hosts:
    - "krypton-conan.arubacorp.net:172.17.0.2"
    network_mode: bridge

### docker version

```bash
root@faa2b4ce09ec:/# docker version
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:28 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:48:42 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
root@faa2b4ce09ec:/# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 23.0.1
 Storage Driver: devicemapper
  Pool Name: docker-253:1-1611590639-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 64.14GB
  Data Space Total: 107.4GB
  Data Space Available: 43.23GB
  Metadata Space Used: 135MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.012GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 1
  Library Version: 1.02.170-RHEL7 (2020-03-24)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 3.10.0-1160.62.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 9.374GiB
 Name: jenkins-ion.arubanetworks.com
 ID: 7YSH:MCQ2:6XTY:ZNAO:BBRZ:WGSE:MDYM:GTAX:DFYR:3L6Q:XBLI:RSIM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


WARNING: The devicemapper storage-driver is deprecated, and will be removed in a future release.
         Refer to the documentation for more information: https://docs.docker.com/go/storage-driver/
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

### Additional Info

Appreciate any help/guidance as this is impacting CI jobs.

**Comment by hpe-ykoehler** [comment]
It seems to match this issue from docker-compose: https://github.com/docker/compose/issues/10405
The question, isn't docker-compose now part of the docker client CLI?  How can I control which version of docker-compose is used when used from docker CLI such as "docker compose ..." to be 2.17.0 ?

**Comment by laurazard** [comment]
Compose works as a CLI plugin for the Docker CLI, but it can also be used standalone. You can also download binaries for specific versions of Compose releases and use them with the Docker CLI by replacing the binary in the Docker CLI plugins folder (on mac, with Docker Desktop, `~/.docker/cli-plugins`).

The development/release/issues/support of Compose still happens over at https://github.com/docker/compose, so as mentioned before that's the best place to submit an issue.
