### ISSUE TITLE
name_to_handle_at is gated by CAP_SYS_ADMIN and not CAP_DAC_READ_SEARCH as documented

### ISSUE THREAD

**Issue by peterwaller-arm** [moby/moby#45518]
### Description

The docs state:
> https://docs.docker.com/engine/security/seccomp/
>  name_to_handle_at | Sister syscall to open_by_handle_at. Already gated by CAP_DAC_READ_SEARCH.

But the profile does not include this syscall in the CAP_DAC_READ_SEARCH, forcing use of CAP_SYS_ADMIN if you need this syscall.

https://github.com/moby/moby/blob/e58c267d66cd9c8fc89c582047b22158c9d44db8/profiles/seccomp/default.json#L580-L588

Consequently the syscall fails with EPERM (errno -1).

### Reproduce

N/A

### Expected behavior

It should be possible to enable this syscall with `docker run --cap-add CAP_DAC_READ_SEARCH`.

### docker version

```bash
20.10.23 and e58c267d66cd9c8fc89c582047b22158c9d44db8.
```

### docker info

```bash
N/A
```

**Comment by neersighted** [comment]
I spent a good amount of time digging into the what, how, and why of this -- and I've actually concluded that we should not filter this syscall at all (though I am still waiting for peers to agree with me).

See my comments at https://github.com/moby/moby/pull/45766#pullrequestreview-1493908145.
