### ISSUE TITLE
client idle connections leak FDs against Docker Desktop

### ISSUE THREAD

**Issue by tonistiigi** [moby/moby#45539]
### Description

When using the client (initialized via `dockercli` in my case) in a long-running process, the idle connections are not released. If you create multiple clients the FD count keeps growing indefinitely.

This can be demonstrated against Docker Desktop. I haven't tested other cases. I guess it also depends on the server's behavior and when the server will drop the connections.

A patch like https://github.com/tonistiigi/docker/commit/af6ada910f04efd695b1670573e137cef269aa85 fixes the issue (as does setting `DisableKeepAlives`).

Other possible fixes could be:
- initialize transport from DefaultTransport (that has better defaults)
- Somehow wrap transport so all clients use the same keepalive pool
- Make this configurable. I would also need dockerCLI update then.
- Explore server side
- There is a call to `CloseIdleConns` but that lifecycle is tricky to manage when initializing clients via `dockerCLI` based on multiple configs. Possibly defining a `Finalizer` could also result in the desired behavior.

### Reproduce

Make calls with clients and monitor FD count. Alternatively, wrap the connection from the UNIX dialer and see that `Close()` is never called on the connection.

### docker version

```bash
23.0 but I assume all
```

### docker info

```bash
23.0 but I assume all
```

**Comment by cpuguy83** [comment]
I wonder if this happens if we make sure response bodies are always drained.

**Comment by corhere** [comment]
> * Somehow wrap transport so all clients use the same keepalive pool

We don't need to wrap anything; simply share the same `*http.Transport` between all clients, or the same `http.Client` between all API clients. Or simply reuse the same API client for the lifetime of the process? Notwithstanding the race condition with `docker/client.Close()` if there is a request in-flight, this sounds to me like the consumer of the client is at fault for leaking resources by not closing clients when it's done with them.

**Comment by tonistiigi** [comment]
> I wonder if this happens if we make sure response bodies are always drained.

I don't think anything is left open. Otherwise adding `IdleConnTimeout` shouldn't fix it, but it does.

>  simply share the same *http.Transport between all clients

All the transports have their own custom Dial function afaics.

> this sounds to me like the consumer of the client is at fault for leaking resources by not closing clients when it's done with them.

Even if ignoring case with multiple clients, I don't see a reason why connections from a single client need to remain open indefinitely if there isn't anything using them. These are not the default that net/http stdlib exposes for example. The multi-client case comes into effect in current libraries that just associate `dockerCli/client.Client` with structs that may need access, not necessarily doing reference counting for every such case.

**Comment by corhere** [comment]
> All the transports have their own custom Dial function afaics.

...sigh. Out of all the ways to implement that, of course the go-connection authors went with the one which makes it impossible to reuse transports.

> I don't see a reason why connections from a single client need to remain open indefinitely if there isn't anything using them. These are not the default that net/http stdlib exposes for example.

Ah, I didn't think to look at `http.DefaultTransport`. I now see that its `IdleConnTimeout` is set to 90 seconds, and that `IdleConnTimeout == 0` disables idle connection timeout. You're right; the client should be configuring the transport to time out idle connections.

**Comment by thaJeztah** [comment]
This should be fixed through https://github.com/moby/moby/pull/48736
