### ISSUE TITLE
docker-rootless with zfs uses a non-existent fs paramete

### ISSUE THREAD

**Issue by un-couteau** [moby/moby#45533]
### Description

running /usr/bin/dockerd-rootless.sh on arch linux displays the following text:

> failed to start daemon: error initializing graphdriver: Cannot find root filesystem arch/home: exit status 1: `"/usr/bin/zfs fs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset arch/home"` => cannot open 'arch/home': dataset does not exist

I noticed that it uses "`zfs fs`" and there is no such parameter as "`fs`" for zfs.

When running a command like this:
`zfs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset arch/home`

The output is as follows:
> arch/home - 49733084160 189539045888 /home lz4 file system - 0 49733084160 49733084160 59878818304 49733084160

I will also complete the information with software versions:
1. docker --version
```
Docker version 23.0.6, build ef23cbc43
```
2. zfs --version
```
zfs-2.1.11-1
zfs-kmod-2.1.99-1884_gac18dc77f
```

### Reproduce

/usr/bin/dockerd-rootless.sh

### Expected behavior

the docker server inside the user space should start

### docker version

```bash
Client:
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.20.4
 Git commit:        ef23cbc431
 Built:             Tue May  9 15:05:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d
  Built:            Tue May  9 15:05:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          1.1.0
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /tmp/rootlesskit2032363408
 slirp4netns:
  Version:          1.2.0
  GitCommit:        656041d45cfca7a4176f6b7eed9e4fe6c11e8383
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.17.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.3.2-1-cachyos-cfs-lto
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 13.34GiB
 Name: book
 ID: 6b82cdab-941f-458a-892f-d6a2f18ec46f
 Docker Root Dir: /home/redmi/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

### Additional Info

I had to rename ~/.config/docker/daemon.json to run docker as ~/.config/docker/old-daemon.json

By the way, here is the contents of daemon.json itself:
```
{
  "storage-driver":  "zfs"
}

```

**Comment by corhere** [comment]
The `zfs list` command is not actually being called with a spurious `"fs"` argument; that's merely an artifact of a bug in how the github.com/mistifyio/go-zfs package builds up the error which reports that the `zfs list` command fails.
https://github.com/moby/moby/blob/9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff/vendor/github.com/mistifyio/go-zfs/utils.go#L42-L54
(`joinedArgs` is the string `"zfs list -rHp -t filesystem [...]"` so slicing it yields `"fs list [...]"`. Looks like they intended to chop off the whole first element of `cmd.Args` to replace it with the resolved path.)

This bug is entirely visual; the command invoked was really `/usr/bin/zfs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset arch/home`.

Also, [zfs is not supported in rootless mode.](https://docs.docker.com/engine/security/rootless/#known-limitations) If you do figure out how to get it to work, please let us know.

**Comment by corhere** [comment]
I've opened a PR upstream to fix the error message.

- https://github.com/mistifyio/go-zfs/pull/90
