### ISSUE TITLE
In K8s + dind, DNS forwards SERVFAIL instead of NXDOMAIN

### ISSUE THREAD

**Issue by dan0dbfe** [moby/moby#45553]
### Description

In a K8s cluster (GKE in my case) and Docker-in-Docker (dind) user-defined network, attempting to resolve non-existent domains will result in a `SERVFAIL` instead of a `NXDOMAIN`. This causes DNS clients like c-ares (used by default in gRPC clients) to error out instead of moving on to the next domain in the search path in `etc/resolv.conf`.

This is a bigger problem when attempting to reach other containers by name in a Docker user-defined bridge. If `ndots` is not 0 (5 is the default in GKE iirc) then attempting to resolve a name like `test` will immediately fail with `SERVFAIL` instead of trying all search paths till `test.` is finally attempted and resolved.

From Docker daemon logs, it seems that `NXDOMAIN` was received but when attempting to forward it, the client instead receivs a `SERVFAIL`.

- Likely related to the change in https://github.com/moby/moby/issues/44575 / https://github.com/moby/moby/pull/44664

### Reproduce

1. SSH into a K8s cluster (in my case, GKE)
2. Create a Docker network: `docker network create some-network`
3. Start dind with debug mode: `docker run --privileged --name some-docker -d --network some-network --network-alias docker -e DOCKER_TLS_CERTDIR=/certs -v some-docker-certs-ca:/certs/ca -v some-docker-certs-client:/certs/client docker:dind --debug --log-level debug`
4. Connect to dind: `docker run --rm -it --network some-network -e DOCKER_TLS_CERTDIR=/certs -v some-docker-certs-client:/certs/client:ro docker:latest sh`
5. Create another network: `docker network create another-network`
6. Run any container here: `docker run --rm -it --network another-network busybox`
7. `nslookup -debug test.test`
8. Get `SERVFAIL` instead of `NXDOMAIN`

```
bash-5.1# dig test.test

; <<>> DiG 9.16.22 <<>> test.test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 2193
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;test.test.			IN	A

;; Query time: 3 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Thu May 18 01:24:36 UTC 2023
;; MSG SIZE  rcvd: 27
```

Contents of `/etc/resolv.conf`:
```
search us-central1-c.c.gke-cluster-name.internal c.gke-cluster-name.internal google.internal
nameserver 127.0.0.11
options ndots:0
```

Docker daemon logs:
```
time="2023-05-18T01:24:36.702466753Z" level=debug msg="Name To resolve: test.test."
time="2023-05-18T01:24:36.702639405Z" level=debug msg="[resolver] forwarding query" client-addr="udp:127.0.0.1:44101" dns-server="udp:127.0.0.11:53" question=";test.test.\tIN\t A"
time="2023-05-18T01:24:36.704423670Z" level=debug msg="[resolver] external DNS udp:127.0.0.11 responded with NXDOMAIN for \"test.test.\""
time="2023-05-18T01:24:54.503033244Z" level=debug msg="event forwarded" ns=moby topic=/tasks/exit type=containerd.events.TaskExit
```

### Expected behavior

`NXDOMAIN` so that DNS clients move on to the next suffix in the search path

### docker version

```bash
Client:
 Version:           24.0.0
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        98fdcd7
 Built:             Mon May 15 18:47:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.0
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       1331b8c
  Built:            Mon May 15 18:48:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.0
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 24.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.10.162+
 Operating System: Alpine Linux v3.18 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.81GiB
 Name: 18d41bee0c7c
 ID: b7bd9e94-7c7f-4157-91c2-179b62732d5a
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 47
  System Time: 2023-05-18T02:10:17.356445457Z
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

#### Workarounds
* If using gRPC, disable the c-ares client by setting `GRPC_DNS_RESOLVER=native`. I don't yet understand why using OS native DNS client works, but not c-ares, when querying the Docker embedded DNS server.
* Always prepend `.` when referring to another container on the same Docker (non-default) bridge network, e.g. `postgres.:5432` rather than `postgres:5432`

**Comment by FearlessHyena** [comment]
We're facing the same issue (on GKE)

**Comment by NeoCat** [comment]
I'm hitting the same issue too. Especially, all versions of `Alpine` (based on musl libc) stops iterating searches when it receives `SERVFAIL` , this becomes a big problem that all of the DNS query fails.
Other distributions like Debian, Fedora etc. (based on glibc) continues resolving FQDN even if they hit `SERVFAIL`, they can resolve DNS.

**Comment by dan0dbfe** [comment]
Thank you for the very quick fix!
