### ISSUE TITLE
24.0.0: Pulling image with platform produces NotFound error for unrelated image (after pulling the correct image)

### ISSUE THREAD

**Issue by felixfontein** [moby/moby#45558]
### Description

Since Docker 24.0.0, running `docker pull --platform amd64 quay.io/ansible/docker-test-containers:hello-world` produces
```
hello-world: Pulling from ansible/docker-test-containers
0e03bdcc26d7: Pull complete 
Digest: sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
Status: Downloaded newer image for quay.io/ansible/docker-test-containers:hello-world
No such image: quay.io/ansible/docker-test-containers:latest
```
(This is on platform `amd64`.) The `quay.io/ansible/docker-test-containers:hello-world` image has been successfully pulled and can be used, but for some reason there is an error about `quay.io/ansible/docker-test-containers:latest` (which does not exist).

Without `--platform amd64`, this error does not show up. This also worked fine with `--platform amd64` on Docker < 24.0.0.

### Reproduce

`docker pull --platform amd64 quay.io/ansible/docker-test-containers:hello-world`

Might also work with other images where `:latest` does not exist in the repo.

### Expected behavior

Just pulls `quay.io/ansible/docker-test-containers:hello-world` without producing errors.

### docker version

```bash
Client:
 Version:           24.0.0
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        98fdcd769b
 Built:             Thu May 18 09:55:36 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.0
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       1331b8c39a
  Built:            Thu May 18 09:55:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.18.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.1-arch2-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: ...
 ID: ...
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

I was able to reproduce this locally on Arch Linux, but also had this in CI (https://dev.azure.com/ansible/community.docker/_build/results?buildId=77550&view=results) with RHEL 7.9, 9.0, and 9.1. In CI, this appeared when working directly with the API, next to the regular status outputs there was a final `{'error': 'No such image: quay.io/ansible/docker-test-containers:latest', 'errorDetail': {'message': 'No such image: quay.io/ansible/docker-test-containers:latest'}}` entry.

**Comment by laurazard** [comment]
This looks like it might be related to https://github.com/docker/cli/issues/4295 (cc @thaJeztah)

**Comment by felixfontein** [comment]
The error message comes from the Daemon and is only shown by the CLI. It's easiest to reproduce with using the `docker pull` command, but you can also do the appropriate HTTP request to the Daemon to get the same error.

**Comment by laurazard** [comment]
Thanks @felixfontein, I'm looking into it. We'd been missing a reproduction scenario for the other issue, so this is really helpful. I'll post updates.
