### ISSUE TITLE
Set read-only token permissions on GitHub workflows

### ISSUE THREAD

**Issue by pnacht** [moby/moby#45575]
### Description

Moby's GitHub workflows currently run with write-all permissions. This is dangerous, since it opens the project up to supply-chain attacks. [GitHub itself](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets) recommends ensuring all workflows run with minimal permissions.

I've taken a look at the workflows and they don't seem to need anything other than read permissions to the repository.

This issue can be solved in two ways:
- add top-level read-only permissions to the workflows; and/or
- set the default token permissions to read-only in the repo settings.

I'll be sending a PR along with this issue that sets the top-level permissions. If you instead (or also) wish to modify the default token permissions:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/moby/moby/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

---

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by neersighted** [comment]
Thanks! We've changed the repo-level setting.
