### ISSUE TITLE
Docker containers are not accessible from the internet anymore

### ISSUE THREAD

**Issue by crawlchange** [moby/moby#45585]
### Description

The issue was only affecting apt-get version of docker before. I went around the issue by using the snap version.

After 2 months of my company's services and platforms running with no issues, and absolutely no human intervention, all the servers simultaneously went down and are absolutely not accessible anymore.

This is causing MASSIVE financial losses. After extensive investigation from multiple teams, we all agreed docker is not working according to documentation. Exposed ports are not accessible, AT ALL.

Since I faced this issue before with the apt-get version, I was able to pinpoint that we are now facing the exact same issue with the snap version (again, after months of the servers running with no issues).

All the servers went down, with just hours of difference. No change has ever been deployed in the last months.

As pinpointed above, this is a issue with docker for linux. Two points make this extremely concerning:

1- The exact same application worked out of the box on the snap version but not on the apt-get version of docker some months ago.
2- That working configuration went down and the ports are completely inaccessible, after months of regular activity, SPONTANEOUSLY, and the platforms, services, etc, cannot be brought back up, the ports are simply not accessible, in ANY os.

The ubuntu version on a sample server is:

Distributor ID: Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy

This issue is extremely serious. Servers are spontaneously going down, one after the other, in different configurations, different platforms, different cloud providers, different versions of operating systems.

### Reproduce

1. docker run -p 5000:80 nginx
2. The server is accessible from the host machine (through 127.0.0.1) but not from outside. The ports are exposed and any server binding to those ports is accessible (react, flask, nginx, you name it) except by docker.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.2
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.7
 Git commit:        569dd73
 Built:             Mon Mar 27 16:16:18 2023
 OS/Arch:           linux/amd64
 Context:           ec_investments

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       5d6db84
  Built:            Mon Apr 10 09:55:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:
```

### docker info

```bash
Client:
 Context: *
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 4
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version:
 init version: N/A
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-67-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.763GiB
 Name: ubuntu-s-1vcpu-512mb-10gb-nyc1-01
 ID: 27BN:GQAJ:LWHE:VFJE:CBPP:P67V:QDU4:24AU:YJ56:5NAE:SJ7S:R2RR
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
If external networking is not working, and this happened at the same time across multiple servers, this sounds like potentially some (cron) job that made changes (could be firewall / iptables updated).

With just the information in this ticket, I don't think this is something that can be resolved, 

I'll close this ticket for now, but if you have specific daemon logs that may indicate events that occurred leading to this issue, feel free to provide those.

**Comment by crawlchange** [comment]
There are no deamons. This happens in any machine, any operating system, any cloud infrastructure. 100% reproducibility. This is a bug inside docker.

**Comment by neersighted** [comment]
The daemon is Dockerd; logs would be helpful to understand what you may be experiencing. Dockerd networking cannot change outside a release, and no contributor or end user has noticed an unexpected or unforseen change in the connectivity model.

**Comment by thaJeztah** [comment]
We have over 30 million monthly installations of the docker-ce engine (not including distro-provided packages), and no other reports of this issue, so it does not look to be 100% reproducible, but if you have logs that could provide more details, perhaps that can help narrowing down your case.
If you have a test-server that reproduces the issue, you can also enabled "debug" mode in the daemon configuration, which will provide more logging (but not generally recommended for production scenarios, as it produces high-volume logging).

**Comment by crawlchange** [comment]
I definitely want to help debugging this issue. Can you provide a step by step on how to output the ideal logs to post here? Dockerd definitely is running and it is the default installation from snap or apt on clean machines (say, digital ocean).

**Comment by crawlchange** [comment]
@thaJeztah "We have over 30 million monthly installations of the docker-ce engine"

Most people don't know what "moby" is, they know docker and they would more likely file bug reports under the docker repository.

However, docker employees are actively working to suppress reports about this issue. Example here:

https://github.com/docker/compose/issues/10584

This is, indeed, affecting dozens of US, UK and Canada companies that we are in contact with. Since this is causing massive damage (now pilling up in the billions of dollars in losses already since 17 May), the CEO of one of those companies managed to open a direct line of contact with Scott Johnston and I personally forwarded complaints regarding @chris-crone and @ndeloof to be added to the list of docker employees that are suppressing reports about this. Multiple people in our company are banned from opening bug reports in any of the github.com/docker repositories.

This is pretty serious, but I believe it is being resolved top down. I don't want to get in the middle of that fight (even though I myself was also banned from opening issues there) but I just want to help investigate this crazy issue.

**Comment by thaJeztah** [comment]
Usually the syslog will also include both the dockerd and containerd logs (`tail -n <number of lines> /var/log/syslog` or variations thereof). If things are related to systems/services outside of the docker service itself, the syslog can be useful as it may put events "within context" (e.g., `docekrd` stopped working after `some-other-service` produced an error). As you mentioned that things stop working "at some point", some digging may be needed beyond that (the relevant logs may not be in the "last" logs, so ideally, collect logs around the time that things stop working).

To view logs of individual services, you can also use systemd/journald's `journalctl`;

```bash
journalctl -xu <systmd service naem>
```

Optionally with `-n <number of records>`, for example, to get the last 50 log entries from the `docker.service`;

```bash
journalctl -xu docker.service -n 50
```

or for the `containerd.service`;

```bash
journalctl -xu containerd.service -n 50
```

Those are just some random pointers; these things can be hard to debug / narrow down. Some other things to consider (taking "it happens after some time" into account);

- monitor overall resources (memory, disk-space, etc); if you're running on systems that are resource-constrained (depending on the overall workload), (temporarily) running out of resources can have a ripple-effect (e.g. when running out of memory, Linux can start randomly OOM-killing processes. Other processes may continue running (seemingly) "as usual" but may actually be in degraded state).
- keep into account that while containers are "sandboxed", they are not (by default) constrainerd on resources (memory, cpu, etc). Depending on the process running inside the container, that may cause some type of workloads "take everything they can"; see  https://github.com/containerd/containerd/pull/7566 for some more information on that.
- for backward-compatibility reasons with some flavors of k8s, the default logging driver is `json-file`, which (by default) does not have log-rotation enabled. Your (basic) example (`docker run nginx`) did not specify log-driver options, which means that (with high volume of traffic), it can take up "infinite" amount of space for logs. Consider using the `local` logging driver (which does rotation by default), or configure logging-options for the `json-file` logging driver to rotate logs https://docs.docker.com/config/containers/logging/configure/ (be aware that logging options can be configured per container, and daemon defaults only apply to new containers, not existing ones).
- if your system runs many "ephemeral" containers, make sure that old containers are cleaned up. While they may no longer be running, they may still be present, and (depending on the situation) occupy resources (reference counting of images, volumes, networks, etc). You can use `docker system prune` (or other `prune` commands) to remove old containers, unused images, etc.

**Comment by neersighted** [comment]
I'm locking this as this thread is going nowhere productive. If you are able to produce a set of steps to reproduce this condition, please feel free to create a new issue. However, threats of litigation for software that explicitly bears no warranty, as per the license, is not only not constructive, but actively hostile.

Please do refrain from creating any more issues unless you have a scenario that reproduces on the latest release on a currently supported Linux distribution (e.g. Ubuntu 22.04).
