### ISSUE TITLE
No file docker.sock on debian without desktop

### ISSUE THREAD

**Issue by Lurius-Kitsune** [moby/moby#45590]
### Description

No file docker.sock on debian without desktop

### Reproduce

Just following this steps here : https://docs.docker.com/engine/install/debian/

### Expected behavior

Docker should start and I should get the confirm message when doing docker run hello-world

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.1
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        6802122
 Built:             Fri May 19 18:05:49 2023
 OS/Arch:           linux/arm64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Additional Info
Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.21-v8+
      Architecture: arm64

_No response_

**Comment by Lurius-Kitsune** [comment]
To make it appear i have to modify :

 /lib/systemd/system/docker.service


and change this line :  
`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock`

to !
`ExecStart=/usr/bin/dockerd -H unix:// --containerd=/run/containerd/containerd.sock`

**Comment by neersighted** [comment]
Did you enable `docker.socket`? As you observe, we use `fd://` as the default listen path as the packaged systemd units are configured to use socket activation. This means that systemd will listen on behalf of dockerd, start it on demand, and pass the already open socket (with pending datagrams) to dockerd once it reports readiness.

`systemctl enable --now docker.socket` should be sufficient to create the socket file if you revert the modifications to the systemd unit. Note that systemd is the only supported init system for the Debian packages.

**Comment by Lurius-Kitsune** [comment]
It does not work at all T^T

Still absent in /var/run/

But as I see the /var/run is a folder and not a symlink with /run

Normal?

**Comment by Lurius-Kitsune** [comment]
> Are you sure that you've successfully reverted the changes to `docker.service` (and reloaded systemd) and enabled `docker.socket`? After that, your next debugging step is `systemctl status docker.socket` as systemd is responsible for creating the socket.

By reverting you mean creating the symlink?

Because as i can see on /run there is a file named docker.sock but not on /var/run because no symlink

**Comment by neersighted** [comment]
I mean reverting your changes to the listen address in `docker.service` (replacing `fd://` with `unix://`). WRT `/run` vs `/var/run`, whether or not those are symlinks is up to your distro. As noted in the unit file, you may need to change things if your distro has made the choice to not create a symlink:

https://github.com/moby/moby/blob/6e98a7f2c9184d4e91df8abf06e2245a0cd77c58/contrib/init/systemd/docker.socket#L4-L7

**Comment by Lurius-Kitsune** [comment]
> I mean reverting your changes to the listen address in `docker.service` (replacing `fd://` with `unix://`). WRT `/run` vs `/var/run`, whether or not those are symlinks is up to your distro. If you're on Debian, that should be true -- I would suggest recreating the symlink (`/var/run -> /run`) if it was somehow destroyed.
> 
> Otherwise, as noted in the unit file, you may need to change things if your distro has made the choice to not create a symlink:
> 
> https://github.com/moby/moby/blob/6e98a7f2c9184d4e91df8abf06e2245a0cd77c58/contrib/init/systemd/docker.socket#L4-L7

Yeah i've done the symlink it's working just fine ! but the modification inside ListenStream I've tried but no succes ..
