### ISSUE TITLE
Unable to pull new images in Docker versions > 23.0.1

### ISSUE THREAD

**Issue by fchapo** [moby/moby#45593]
### Description

In a Windows Server Environement it seems to be impossible to pull images.

I have installed DockerCE as explained here https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1. We do have one server running Docker CE Standalone and one cluster running Docker CE Swarm.

I have started with Docker 23.0.1 which worked fine, but due to security issues I updated it to the latest version which ist 23.0.6.

Now when I try to pull an image that is not present in cache it fails with the following error:

```
docker image pull portainer/portainer-ee:2.15.0
2.15.0: Pulling from portainer/portainer-ee
5c9d6483dab1: Extracting [==================================================>]  103.2MB/103.2MB
72e1fd46c625: Download complete
27fce5bd47b6: Download complete
e4559fd71318: Download complete
failed to register layer: strconv.ParseInt: parsing "": invalid syntax
```

### Reproduce

Install Docker CE 23.0.2 or hight on Windows Server 2019 as explained here: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1

Then try to pull any image (portainer-ee is just an example).

```
docker image pull portainer/portainer-ee:2.15.0
```

### Expected behavior

`docker image pull portainer/portainer-ee:2.15.0` should pull the image sucessfully.

### docker version

```bash
Client:
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:35 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.24)
  Go version:       go1.19.9
  Git commit:       9dbdbd4
  Built:            Fri May  5 21:17:32 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 23.0.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Microsoft Windows Server Version 1809 (OS Build 17763.4377)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: 
 ID: 
 Docker Root Dir: 
 Debug Mode: false
 HTTP Proxy: http://1.2.3.4:3128
 No Proxy: localhost
 Username: 
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment]
hmm... haven't heard other issues about this. First thing I was looking at if this could be Windows version specific; 

```
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Microsoft Windows Server Version 1809 (OS Build 17763.4377)
```

If I see that correctly, you're running Windows Server 1809, which I think reached EOL in May 2021 (https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1803-1809-end-of-servicing, https://learn.microsoft.com/en-us/windows/release-health/status-windows-10-1809-and-windows-server-2019). Are you seeing the same issue on non-EOL versions of Windows as well?


Looking at the full diff: https://github.com/moby/moby/compare/v23.0.1...v23.0.2, I don't see immediate changes there. But containerd vendoring diff: https://github.com/containerd/containerd/compare/v1.6.16...v1.6.19

Only immediate code-paths that could be of importance at a glance;

- https://github.com/containerd/containerd/commit/84936fd1f6a0670ab8c7665cb87fae6b87b0b908
- https://github.com/containerd/containerd/commit/b327af6a4f635611d8b59beec94db0beace48063

**Comment by fchapo** [comment]
Thanks for the quick reply which freaked my out for a second. Windows Server 2019 (1809) is still supported via LTSC until at least next year : https://learn.microsoft.com/en-gb/windows/release-health/windows-server-release-info .

According to the website the latest version is 17763.107 which is the one I am running. But I know that this bug was already present a few month ago, so I don't think it could be related to windows updates.

And yes I searched desperately for someone with the same issues but I did not find any information, that why I finally ended up opening an issue.

I've tested 24.0.1 aswell, and the error is still there, so I rolled back to 23.0.1 which works. 

Let me know if I can get you any other valuable infos.

**Comment by thaJeztah** [comment]
Ah! Sorry for scaring you 😅 ☺️

Are you seeing this issue with every image? (I was also looking at the image's manifest if there's anything that immediately stood out)

**Comment by fchapo** [comment]
It's happening with portainer, with this one `docker pull mcr.microsoft.com/dotnet/samples:aspnetapp` and at least with another custom build image that build on top of `python:3.11-windowsservercore-1809` so I would say it happens with every image.

**Comment by vvoland** [comment]
Just tested it on Windows 10 with both 23.0.6 and 24.0.1 and couldn't reproduce it.

```
PS C:\Users\Pawel\Desktop> docker pull mcr.microsoft.com/dotnet/samples:aspnetapp
aspnetapp: Pulling from dotnet/samples
aaaa081173ae: Pull complete
6689fcf4e1c9: Pull complete
df9ec6cb55f2: Pull complete
5250f5b1b011: Pull complete
96d7a4d2153e: Pull complete
65d88a59496f: Pull complete
Digest: sha256:c11a4e3fa51c7900335ab776abb02e15d517d631741a052aa395bc14cdc1c52f
Status: Downloaded newer image for mcr.microsoft.com/dotnet/samples:aspnetapp
mcr.microsoft.com/dotnet/samples:aspnetapp
```



<details>
<summary>docker version & docker info</summary>

```
PS C:\Users\Pawel\Desktop> docker version
Client:
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:35 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.24)
  Go version:       go1.19.9
  Git commit:       9dbdbd4
  Built:            Fri May  5 21:17:32 2023
  OS/Arch:          windows/amd64
  Experimental:     false

PS C:\Users\Pawel\Desktop> docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 23.0.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19044 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Microsoft Windows Version 21H2 (OS Build 19044.2604)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.93GiB
 Name: tower-windows
 ID: <redacted>
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
</details>


Looks like this is where it fails:
https://github.com/moby/moby/blob/fa97b40bc2f94bab93a715091c7accb7d3746094/daemon/graphdriver/windows/windows.go#L770-L789

https://github.com/moby/moby/blob/fa97b40bc2f94bab93a715091c7accb7d3746094/daemon/graphdriver/windows/windows.go#L792-L799


which is.. weird? Because if it reaches the `ParseInt` that means that the reexec returned with 0 exit code and didn't print anything to the stdout, which shouldn't happen.

There are also no changes in this code between the 23.0.1 and 23.0.6 versions, except Go version (1.19.5 -> 1.19.9).

Possibly this could be some something with stdout buffering that happen under specific combination of Go and your Windows version?
Could you try again with the `DOCKER_WINDOWSFILTER_NOREEXEC=1` environment flag set for the dockerd daemon?

**Comment by thaJeztah** [comment]
@fchapo Perhaps some data-points that could help (thinking out loud here);

- Can you confirm that the same issue reproduces on multiple servers? (checking if it's not some data-corruption / previous that happened on a machine)
- Does it reproduce for you on a "fresh" machine same as on an existing machine? (also curious if it's something related to previous state of the machine)
- Do you know if any other software is running that could have an affect? (Thinking of Virus-Scanners; we've had situations in the past where files were blocked/quarantined by scanners, causing some obscure errors)
- Is there anything special about your setup that you could think of? (e.g. separate storage for Docker's storage locations)

**Comment by fchapo** [comment]
Hi together, thanks for the replys.

I can try `DOCKER_WINDOWSFILTER_NOREEXEC=1` but could you explain where I should put this setting? There arent much informations about this flag on google.

* I Can confirm that this is happening on 4 servers, all Windows Server 2019, 3 of them are in swarm mode, one in standalone
* I will try to setup a Sever 2019 Hyper-V to test it out on a new setup, but it's not going to have 100% the same setup as in the datacenter
* The only other software running on thoses machines is the Virus Scanner, which until now did not do much side effects
* Nothing special about the setup, the only thing that ever got installed there is Docker but with the following history:
 * Docker Enterprise Edition (Mirantis) in Version 20.X
 * Uninstalled the whole Docker EE thing as it's not included in the Windows licence anymore
 * Installed Docker CE 23.0.1

**Comment by vvoland** [comment]
I'm not very familiar with the Windows side, but looking at the code I'd suggest something like this:

1. Stop the daemon started by the Docker service:
```powershell
PS> Stop-Service -Name Docker
```

2. Run the daemon with modified env
```powershell
PS> $env:DOCKER_WINDOWSFILTER_NOREEXEC = '1'; dockerd --debug
```

3. You can now do the testing.
4. Once you finish, restart the normal Docker daemon service:
```powershell
PS> Start-Service -Name Docker
```

**Comment by fchapo** [comment]
So on a brand new Hyper-V Windows Server 2019 Datacenter 17763.rs5_release.180914-1434 (same same as the one where we have the issue on) it is working without any issue. Which leaves me in the dark... :(. 

I will give a triy to the NOREEXEC but I have to find some time to do this in maintenance time.

**Comment by fchapo** [comment]
Just to be sure, as Windows always makes it kind of complicated...

I used this manual to install DockerCE : https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1

Which basically uses that script: https://github.com/microsoft/Windows-Containers/tree/Main/helpful_tools/Install-DockerCE

Obviously Windows doesn't help you with unistalling nor updating... So to update Docker to a new version, I just downloaded the new exe from https://download.docker.com/win/static/stable/x86_64/ and I've replaced the existing ones in C:\Windows\System32 (docker.exe and dockerd.exe). Thats enougth right?

**Comment by neersighted** [comment]
That is a fine way to update, I think you can run that script again (I don't use the script regularly myself, though I did help with the latest refactor, so ymmv).

**Comment by vvoland** [comment]
I think it should be fine. What I did is I just removed [the check in the script ](https://github.com/microsoft/Windows-Containers/blob/258a240a5e9735b09233adb1a77249e8c2b83cc1/helpful_tools/Install-DockerCE/install-docker-ce.ps1#L379-L382)and reran it with `-DockerVersion <new-version`.

**Comment by thaJeztah** [comment]
> Is it possible that the function itself got moved from docker.exe to dockerd.exe?

Pulling images has always been on the daemon-side, so nothing moved in that respect.

> I will keep you updated when we will be able to make the changes in the scanner. But if you want we can close the ticket right now.

Thank you! I'll close the ticket, but feel free to continue the conversation. And if you have relevant information that may help others feel free to post as well 👍

**Comment by mstred** [comment]
Hi all. I was able to reproduce this again since version `28.2.0` onwards. AFAICT, `28.1.1` is the latest stable version to me.

Seems like the `failed to register layer: strconv.ParseInt: parsing "": invalid syntax` error gets to happen during image extraction right after pulling it from a registry server, either from a public (tested with docker.io and mcr.microsoft.com) or a private one. I tried compiling and using unpigz, but it didn't make any difference here.

Here's my `docker info`:
```powershell
docker info
Client:
 Version:    28.2.2
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 28.2.2
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 26100 (26100.1.amd64fre.ge_release.240331-1435)
 Operating System: Microsoft Windows Version 24H2 (OS Build 26100.4066)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.66GiB
 Name:
 ID:
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 29
  System Time: 2025-06-01T00:16:33.4247772-03:00
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Comment by yehiaIQ** [comment]
Facing the same issue

```
docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022
```

```
PS C:\Windows\system32> docker info
Client:
 Version:    28.3.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 28.3.2
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.3453)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 64GiB
 Name: DEV-CENAPP1-SRV
 ID: 47020ed1-db8e-427d-843a-754202bcc12e
 Docker Root Dir: E:\data\docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 32
  System Time: 2025-08-31T20:40:58.6054642+03:00
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

[DEPRECATION NOTICE]: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
In future versions this will be a hard failure preventing the daemon from starting! Learn more at: https://docs.docker.com/go/api-security/
PS C:\Windows\system32>
```
