### ISSUE TITLE
Idea: allow dockerd to fail-fast when running/starting with expired TLS certs

### ISSUE THREAD

**Issue by rrjjvv** [moby/moby#45611]
### Description

The problem (short version): the daemon continues to run after its cert expires.  There is no obvious way to know that until there is an incoming request that fails.  Additionally, the daemon will start even with expired certs.  Both of these, in their own way, make it difficult to detect with external monitoring.

The request (short version):
1. provide an option for the daemon to fail at startup if the cert is invalid
2. provide an option for the daemon to terminate if the cert become invalid at runtime

---

Our certs are generated on-demand and are relatively short-lived (hours/days), so the chances of expiration are increased.  This has never been an actual problem, until a bad system change resulted in the daemon not properly reloading when a new cert was generated.  The problem was relatively difficult to diagnose due to the service being healthy (from the perspective of systemd) and that the on-disk cert was perfectly valid.  It took some time to realize that the bad dates in the `certificate has expired or is not yet valid` message were from certs that existing only in dockerd memory.

It did not shock me that the daemon doesn't fail at runtime (there would be some overhead involved with tracking cert validity), but I was surprised that it would startup.  I imagine there are some non-conventional scenarios that have become reliant on this behavior, and in the course of this write-up, I now see that the daemon isn't 100% unusable; at the very least, the `/metrics` endpoint continues to work just fine.  This is why I assumed this is a feature request (vs. bug report) and why it would probably have to be opt-in.

My idea/request was for daemon failure, since that is easy to detect/monitor and probably easy to implement.  But _detection_ (or notification) is the key.  Preferably in a "structured" way (i.e., not scraping logs for a magic string).  As a contrived (?) example, I'd be okay with scraping the cert status from `/metrics`.

I'll briefly mention my current workaround (systemd-specific), in case you think the concept might make sense as a basis for a real solution.  I'm "wrapping" the dockerd invocation with a watchdog (in the systemd sense).  The watchdog hits `_ping`, and if it succeeds, it posts the `WATCHDOG=1` notification.  If it doesn't succeed, the notification is not sent, which results in the daemon restarting.  This satisfies my second request ("fail at runtime").  That isn't sufficient if the on-disk cert is actually expired, since the daemon will happily start up, so there's a pre-start check to fail if the on-disk cert is already expired (which satisfies my first request to "fail at startup").

Does this request seem reasonable?  Outside of compatibility or performance concerns, I couldn't think of any obvious reasons why it can't/shouldn't be done.

---

Notes:
* My idea refers both to (generic) "invalid certs" and (specific) "expired certs".  My actual concerns are only around expiration, but I didn't want to artificially constrain this idea to only expiration issues if it could apply to other classes of 'invalid cert' as well.
* I mention only cert expiration, though CAs can expire and be just as problematic.  I didn't call out CA expiration simply to make this request simpler and that CA expiration isn't as big of a risk in my scenario.  They probably deserve consideration though.
* This same behavior is present in buildkit as well.  That's not directly relevant obviously, but I know there's effort to maintain parity (when it makes sense).  If you folks are receptive to this idea, I would file a similar request against buildkit.  (We utilize the same PKI setup for both buildkit servers and docker servers... it just happens that this bad system change happened on a docker server.)

**Comment by rrjjvv** [comment]
> Any client can scrape the status of a server's certificate by scraping the certificate itself.

Ugh, you're absolutely correct.  I naively (and wrongly) assumed I would need to provide a valid client cert to retrieve it.  It would indeed be trivial to implement the necessary plugin for our system, if it doesn't already exist.

> I see little need to add a bespoke API to the daemon to export the status

I fully agree about (not) exporting cert data from the daemon.  I had only used that example to illustrate that I was not picky about how I could detect this expiration... though my preference was for daemon failure, I would have been happy with more indirect means.

> can't access the Engine API remotely over TLS—to a full outage of all containers and no access to the Engine API locally over /var/run/docker.sock. 

Incidentally, my original assumption was the reason the daemon was happy to start with expired certs was _because_ I was also listening on the local socket... since the API was still accessible via a second avenue, the daemon should still stay up.  Obviously that's not the case.

> The daemon could log a warning/error, but that would be counter to your request for "structured" monitoring.

Yup.

> Which brings us back around to external monitoring as the solution of best fit.

Yup.  Hopefully I had made it clear that this was always about external monitoring.  You gave me a much simpler way to do it, but my request was so I could (remotely) identify the issue by way of the service not listening on the port.  My workarounds were 'local', but had no part in actual monitoring; they were solely to take the daemon down, and keep it down, so we knew something was wrong.

At the end of the day, my actual problem statement ("remotely detecting then the daemon is holding onto an expired cert") has a simple solution; thanks for the TLS-101 refresher (and sorry that you had to!).  In that respect, I could close this issue.

That said... is there still validity to the idea of failing?  You gave plenty of reasons why daemon failure might be undesirable; some don't apply to me, and some I didn't consider.  Clearly it could never be _default_ behavior, which I had already assumed.  But I would still find it useful.  If there's a reason why implementing the _option_ is still objectionable, I'd be happy to close it.  But if there are no real objections, and just a matter of "nobody else will want it, so nobody will have reason to implement it"... I might be willing.

**Comment by corhere** [comment]
> If there's a reason why implementing the _option_ is still objectionable, I'd be happy to close it. But if there are no real objections, and just a matter of "nobody else will want it, so nobody will have reason to implement it"... I might be willing.

I would be concerned that people might enable the option without thinking through the consequences, then shoot themselves in the foot a few months later after forgetting that they opted in. And from what I can tell, such functionality is very niche. Surveying Apache HTTPd, nginx, lighttpd, haproxy, Envoy, and gunicorn, the only one I could find documented to (have an option to) refuse to start if a server certificate is expired is the out-of-tree [Apache mod_nss.](https://pagure.io/mod_nss/blob/master/f/docs/mod_nss.html#_1100) Neither of the in-tree mod_ssl nor mod_tls are documented to have such behaviour. On the whole, I don't have strong enough objections to outright say no, but following the adage "no is temporary but yes is forever," neither do I feel there is enough to warrant merging such a feature—and accepting the maintenance burden—at this time. You are welcome to keep this issue open to give other users a chance to weigh in and emoji-vote.

**Comment by rrjjvv** [comment]
You've convinced me.  If I had felt a little stronger about my idea and did that same research (to say "but all these similar products do it"), and found nothing, I may have talked myself out of it at that point.  I can now objectively say "it's not worth it", especially since the act of blocking startup is trivial (via systemd or otherwise).  The runtime component was the messy part, and the motivation for creating the request in the first place.

Thanks for hearing me out and the thoughtful feedback!

**Comment by thaJeztah** [comment]
I was reading this ticket, and initially thought the "fail to start if the cert has expired" could be reasonable, but @corhere made a very good point about clock skew, and that's definitely a footgun that could lead to service outages, e.g. scenario;

- server is restarted, but clock is not yet synchronised (now the engine is down)
- cert expired, and daemon shuts down (on restart), taking down _both_ the remote  TCP, and local `unix://` socket APis

Some things that (potentially) could be considered to help discoverability;

- A `WARN` log (which would also be shown when running `dockerd --validate` when validating the daemon's configuration
- The warning could be returned in the `/info` endpoint's warnings response (which could allow viewing potential issues when connecting to the `unix://` socket and running `docker info`
- Or included in the `listeners` information in `/info` (which I started working on, but didn't complete; https://github.com/moby/moby/pull/43459)

**Comment by rrjjvv** [comment]
The dialogue made me think it could be used intentionally as well.  I'm almost certain that if the daemon is configured for TLS, it *will* fail to start if the files don't exist or are not structurally valid (i.e., `touch ca.pem` won't cut it).  I could imagine a deployment scenario where a VM image has a TLS-enabled setup baked in, as well as intentionally bad (static) certs, with the intention that valid certs are placed later.  And perhaps they use (local) docker to do so....

But I do like those ideas (esp. the last two).  Neither would have helped me in my quest to _remotely_ discover cert issues, but in reality, our monitoring can both pull and push.  Your idea would work great in a push-based model.  Alternatively, actually serve up the raw cert directly; that way someone could make validity determinations on their own, without you having to do the processing, and without the user having to extract it via TLS exchange.  Not at all (end-)user friendly, but a generalized solution to "how do I get info on a cert that exists only in dockerd's memory".

Also, IIRC, `docker info` will emit warnings around using TCP without TLS, not doing cert validation, etc.  While those scenarios and expiration isn't quite apples-to-apples, I think your idea complements it quite well ('your security/usability is/will be at list")!
