### ISSUE TITLE
[Feature Request] Runtime secrets

### ISSUE THREAD

**Issue by lonix1** [moby/moby#45642]
### Description

There have been requests for runtime (/mounted) secrets going back years. (I'm not referring to build-time secrets.) Unfortunately this is [not](https://github.com/moby/moby/issues/40046#issuecomment-538777305) currently supported.

*Here's a question on [StackOverflow](https://stackoverflow.com/q/58257319/9971404) with 10k views so far.* There was a  [PR](https://github.com/moby/moby/pull/43543) for this feature, but was abandoned.

The typical workaround is to create a one-node swarm. Although that works, it's a pain to set up and maintain just to get the secrets feature. Also, it's *not possible to do that with docker rootless as the overlay network doesn't work, so swarm isn't available.*

Now that `docker compose` is integrated into the core cli tool, please consider adding this feature. It's something people have asked for going back many years because it's not just useful, but incredibly important: a core part of a deployment's security.

**Comment by neersighted** [comment]
This is a duplicate, more-or-less of https://github.com/moby/moby/issues/13490. While #13490 is less concrete, it's still the best place to start thinking about how secrets should be implemented in the future.

I'll make a note to come up with a basic design proposal/set of principles and a better tracking issue in the feature.

**Comment by gadget78** [comment]
i found this post, and 1, wanted to post something so secrets gets more attention and hopefully support,
and 2. ask about what you wrote about rootless docker.. 
`it's not possible to do that with docker rootless as the overlay network doesn't work, so swarm isn't available.`

i have no issue using the one-node swarm method (`docker swarm init`), 
i am just trying to get a workaround to the "overlay network" issue, as it does seem connected, it just never mounts the tmpfs.
i wanted to ask how i can confirm that this is what is blocking rootless docker from working in a one-node swarm,
and if there was any known workarounds for it, even if it needs manually adding somehow, the network overly within my environment is using slirp4netns, which could allow for a working alternative ? or if its a tmpfs mount issue how i could debug that.

EDIT 
ok i managed to get this working !.. i was initially implementing it incorrectly,
so i can confirm, if you use a rootless docker, within its own user space, and make sure there is no other containers are running, 
order would then be;
create the rootless docker with override features,
`Environment=DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns` within the override.conf
 `docker swarm init`  get single node swarm going
`printf "%s" "placeholder-only" | ${docker_bin}/docker secret create my_secret` create placeholder for your secret (or real)
`docker service create --secret my_secret rest-of-your-create-command.... image:latest`
