### ISSUE TITLE
serf: protect field access with lock to avoid potential data race

### ISSUE THREAD

**Issue by yanke-xu** [moby/moby#45655]
### Description

I found a potential data race based on the code analysis. For example, there are two confilicting operations on the field "EventLTime", where the read operation at: serf/delegate.go:223, and the write operation which is protected by the eventLock at: serf/delegate.go:264. Similar to preventing write conflicts on line 264, the two operations may cause a data race. 

### Reproduce

nil

### Expected behavior

Adding a lock to protect the access to the field.

### docker version

```bash
nil
```

### docker info

```bash
nil
```

### Additional Info

nil

**Comment by thaJeztah** [comment]
I think you're referring to https://github.com/moby/moby/blob/2cd23ffeecf3feee64ce6afe5a53a99e19389a3b/vendor/github.com/hashicorp/serf/serf/delegate.go#L263

Which is in an external dependency (maintained in github.com/hashicorp/serf), so may be worth reporting there (or check if there's a newer version of that dependency that has a fix)

**Comment by corhere** [comment]
Where's the write to `EventLTime`? Line 264 reads that field and writes to a different struct field.
https://github.com/moby/moby/blob/2cd23ffeecf3feee64ce6afe5a53a99e19389a3b/vendor/github.com/hashicorp/serf/serf/delegate.go#L262-L266
