### ISSUE TITLE
A potential data race in ssh/handshake.go

### ISSUE THREAD

**Issue by lobottt** [moby/moby#45656]
### Description

It seems to be a potential data race. Specifically, there are two conflicting operations on the field "sentInitMsg", where the read operation is protected by a lock at: ssh/handshake.go:567, and the write operation is unprotected by the lock at: ssh/handshake.go:498. A data race may occurs when the two functions where the two operations are located.

### Reproduce

Code analysis.

### Expected behavior

Adding a lock to protect the access to the field.

### docker version

```bash
nil
```

### docker info

```bash
nil
```

### Additional Info

nil

**Comment by thaJeztah** [comment]
This is code in an external dependency (golang.org/x/crypto); https://github.com/moby/moby/blob/2cd23ffeecf3feee64ce6afe5a53a99e19389a3b/vendor/golang.org/x/crypto/ssh/handshake.go#L569

Best to report this in https://github.com/golang/crypto, which is where that project is maintained
