### ISSUE TITLE
potential leak in ring.go

### ISSUE THREAD

**Issue by hhheiaenia** [moby/moby#45651]
### Description

I notice that all the r.wait.Wait(), r.wait.Signal() and r.wait.Broadcast() are protected by the mutex lock r.mu in https://github.com/moby/moby/blob/2cd23ffeecf3feee64ce6afe5a53a99e19389a3b/daemon/logger/ring.go#L186-L190
So I doubt whether this situation can cause a deadlock. 

Maybe what I said is not right, thank you for taking a look.

### Reproduce

.

### docker version

```bash
.
```

### docker info

```bash
.
```

**Comment by corhere** [comment]
The `r.wait` [condition variable](https://pkg.go.dev/sync#Cond) is associated with the `r.mu` mutex.

> Each Cond has an associated Locker L (often a *Mutex or *RWMutex), which must be held when changing the condition and when calling the Wait method.

> Wait atomically unlocks c.L and suspends execution of the calling goroutine. After later resuming execution, Wait locks c.L before returning.

Everything looks correct to me. Have you experienced any deadlocks in practice, or is this just speculation?

**Comment by thaJeztah** [comment]
Let me close this one for now, but if you have more details, please comment
