### ISSUE TITLE
libnetwork: protect field access with lock to avoid potential data race

### ISSUE THREAD

**Issue by lobottt** [moby/moby#45663]
### Description

Fixed inconsistency and also potential data race in libnetwork/service_linux.go and libnetwork/endpoint.go: 
ingressPorts is read/written many times in libnetwork/service_linux.go and libnetwork/endpoint.go; many times, it is protected by .mu.Lock(); 1 time it is read without a Lock, which is in func populateLoadBalancers() on L44.
A data race may happen when the func populateLoadBalancers() are called two times and they are called in parallel. 

### Reproduce

nil

### Expected behavior

data race

### docker version

```bash
nil
```

### docker info

```bash
nil
```

**Comment by bsousaa** [comment]
Please share a reproducer or stack trace.

**Comment by thaJeztah** [comment]
Let me close this one for now, but if you have more details how the race could happen, or have a reproducer, please leave a comment.
