### ISSUE TITLE
Potential leak in vendor file

### ISSUE THREAD

**Issue by hhheiaenia** [moby/moby#45679]
### Description

hello, I was wondering whether the number of calls to wg.Done() can be guaranteed to be equal to the number of  goroutineBudget in https://github.com/moby/moby/blob/master/vendor/github.com/prometheus/client_golang/prometheus/registry.go#L462.
If it cannot be satisfied, the goroutine where the wg.Wait() are located may be leaked.

Maybe what I've said is not correct, thank you for taking a look.

### Reproduce

.

### Expected behavior

.

### docker version

```bash
.
```

### docker info

```bash
.
```

**Comment by neersighted** [comment]
Hi, this should be an issue in https://github.com/prometheus/client_golang. As you have noted, this is a vendored file, and is not maintained in this repository. Feel free to ping back here if you get a change merged in Prometheus and we should update.
