### ISSUE TITLE
`unauthorized: access token has insufficient scopes` while running docker manifest inspect when authenticated with Docker Hub PAT

### ISSUE THREAD

**Issue by HarishKVarada** [moby/moby#45726]
### Description

I am receiving below error while running docker manifest inspect against a set of containers from my azure devops pipeline.

I am using docker version -- 24.0.0 stable release. The error is same with docker 23.0.0 as well. 

The error is :: 
**The ressponse code from subprocess command is ::: 

```
b'Get "https://registry-1.docker.io/v2/library/alpine/manifests/3.16": unauthorized: access token has insufficient scopes\n'**
```

We're using sPAT_Token which is BuildAccessToken from the pipeline. 

```yaml
        env:
          sPAT_Token: $(BuildAccessToken)
          RELEASE_ALL: ${{ parameters.release_all }}
```

    

### Reproduce

```
def main(release_all):
        try:
            args = ['docker', 'manifest', 'inspect', source_image]
            res = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            output = res.communicate()[0]
            print("The ressponse code from subprocess command is ::: ")
            print(output)            
        except OSError:
            print("error: popen")
            exit(-1)
        else:
          res.wait() # wait for process to finish; this also sets the returncode variable inside 'res'
          print("Printing the response code")
          print(res.returncode)
          if res.returncode != 0:
              print("  os.wait:exit status != 0\n")
              print("Unable to determine the images digest from docker manifest inspect command ")
              exit(-1)

if __name__ = '__main__'
personal_access_token = os.environ['sPAT_Token']
release_all = os.environ['RELEASE_ALL']

main(release_all)
```

### Expected behavior

Expected behaviour is to get the manifest output of the container(s)

### docker version

```bash
Client:
 Version:           24.0.0
 API version:       1.41 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        98fdcd7
 Built:             Mon May 15 18:47:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          20.10.24+azure-1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.6
  Git commit:       5d6db842238e3c4f5f9fb9ad70ea46b35227d084
  Built:            Tue Apr  4 18:03:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21+azure-1
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
Version:    24.0.0
Context:    default
Debug Mode: false
Plugins:
buildx: Docker Buildx (Docker Inc.)
Version:  0.10.4+azure-1
Path:     /usr/libexec/docker/cli-plugins/docker-buildx
compose: Docker Compose (Docker Inc.)
Version:  2.17.3+azure-1
Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 18
Server Version: 20.10.24+azure-1
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: false
userxattr: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Cgroup Version: 2
Plugins:
Volume: local
Network: bridge host ipvlan macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
Default Runtime: runc
Init Binary: docker-init
containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
init version:
Security Options:
apparmor
seccomp
Profile: default
cgroupns
Kernel Version: 5.15.0-1038-azure
Operating System: Ubuntu 22.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.781GiB
Name: fv-az367-608
ID: YOMJ:GNY2:47F3:3JFS:R33S:CHGD:PMF4:DAFD:VKYM:6BAH:WRIO:PDFE
Docker Root Dir: /var/lib/docker
Debug Mode: false
Username: githubactions
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

**Comment by corhere** [comment]
I can reproduce on both v20.10.24 and v24.0.2 (client and daemon) when using a "public read-only" PAT on Docker Hub. `docker manifest inspect alpine:3.16` returns the error in the issue description, whereas `docker pull alpine:3.16` succeeds.

**Comment by thaJeztah** [comment]
Manifest inspect is handled by the CLI, so would hit a different code-path.

- related / possible duplicate: https://github.com/docker/cli/issues/4345

(I'm not sure if authenticating should return an error though, or just return a token without `push` if the credentials / PAT doesn't have it)

/cc @jcarter3 (you're more familiar with this)

**Comment by jcarter3** [comment]
Yes, the issue is that `docker manifest inspect` requires `push` permission (which seems to be a bug?). A read-only token does not have permission to make this call.

**Comment by jcarter3** [comment]
@thaJeztah PATs are different, as they have a specific scope attached to them, apart from the permissions applied to a user. It is true that for a general user (or anonymous) we would swallow this error and only return the granted permissions. PATs handled differently, and the scopes for them are applied/checked before any user permissions. Long term, we'd like to apply this to users as well, as it'd be more logical, but old "specs" are what they are.

**Comment by HarishKVarada** [comment]
@thaJeztah  @jcarter3 :: what could be the possible resolution for this? Please advise, I was able to fix this by creating a user in docker hub and generating access token for that user with full permission (Read, write and Delete) and embedded docker login in the script. 
Then I was able to get the result for docker manifest inspect but the token should have full permissions, but for a public repository or images that are publicly available I was able to pull them without any issues (using docker pull). The issue is only with docker manifest inspect command along.

**Comment by jcarter3** [comment]
Are you able to switch to using `docker buildx imagetools inspect <repo>`? This is a replacement for `docker manifest ...` which AFAIK is is still "experimental"

**Comment by HarishKVarada** [comment]
> Are you able to switch to using `docker buildx imagetools inspect <repo>`? This is a replacement for `docker manifest ...` which AFAIK is is still "experimental"

The buildx is working but the issue is docker buildx imagetools inspect is returning the output in plaintext while the docker manifest inspect used to return the output in JSON format.

Is there any thought about modifying this to return in JSON format? 

Output from buildx command for alpine:3.17 is 
Name:      docker.io/library/alpine:3.17
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:e95676db9e4a4f16f6cc01a8915368f82b018cc07aba951c1bd1db586c081388

Manifests:
  Name:      docker.io/library/alpine:3.17@sha256:81a4480db344455c6e0dbbca3188962273b5eb5c22efa3fef05824de6048bfa8
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      docker.io/library/alpine:3.17@sha256:02af5d1500a2dfcafae175d7fa163640fe1ec9c785c60068a5e560475ba5b2e7
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v6

  Name:      docker.io/library/alpine:3.17@sha256:75d68ffc341f4f699d65d665d7f535a8b432591ccf893c486ec0493bbc398021
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7

  Name:      docker.io/library/alpine:3.17@sha256:f465359a4d1abc7defe7b9774a1077b2ccff79bc64aeab71a7296d13aa504a9a
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64/v8

  Name:      docker.io/library/alpine:3.17@sha256:763b57c84895c00327915d509ddcd8214249080d4a747b776d708d228168d628
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/386

  Name:      docker.io/library/alpine:3.17@sha256:eabc553b772b1999fc10211b5d03768401d209c2c064b2a3e563c4f20c932ab7
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le

  Name:      docker.io/library/alpine:3.17@sha256:c03aaecaf9d5f9716b9dbbaa96c3d2e8c436872773e401290eece1fe2feefcbe
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x

**Comment by cpuguy83** [comment]
@HarishKVarada Add `--format '{{ json . }}'`

**Comment by Linde7777** [comment]
I meet the same error info when using `docker push`, I check this to finish the problem: https://docs.docker.com/docker-hub/access-tokens/

you can finish the steps in 3 minutes
