### ISSUE TITLE
Include the name of a scientist in the name-generator.

### ISSUE THREAD

**Issue by Ashkanfarhady** [moby/moby#45752]
### Description

Dr. Firouz Naderi, an esteemed Iranian-American NASA scientist, made significant contributions to the field before his recent passing. It would be fitting and meaningful to honor his memory by including his name in this repository.

https://en.wikipedia.org/wiki/Firouz_Naderi

**Comment by thaJeztah** [comment]
- closing, per https://github.com/moby/moby/pull/45753#issuecomment-1591338298
