### ISSUE TITLE
Macvlan driver with IPAM configuration with `subnet` takes 15 seconds to create in compose

### ISSUE THREAD

**Issue by MobaLinux** [moby/moby#45831]
### Description

Running docker-compose.yaml to create network and a service, the network block I'm creating is:

network:

    debug1:
      name: debug1
      driver: macvlan
      driver_opts:
            parent: ens192
            macvlan_mode: bridge
      ipam:
          config:
          - subnet: 172.17.0.0/16
 service:

    test:
         image: test:latest
         command: >
             bash -c "echo hello-world"
         networks:
             debug1:

When creating this compose file, and running it, the network `debug1` takes **15 seconds** exactly to be created, is that an issue or a feature don't know, didn't find any documentation about this.
furthermore when creating the network without the ipam block it takes 0.1 second to be created, so I don't know what to do.

After days of troubleshooting I found out my docker daemon is getting an error message:

> level=warning msg="unable to locate plugin: , retrying in 1s"
> level=warning msg="unable to locate plugin: , retrying in 2s"
> level=warning msg="unable to locate plugin: , retrying in 4s"
> level=warning msg="unable to locate plugin: , retrying in 8s"
> level=error msg="Error handling plugin refcount operation" driver= error="plugin \"\ not found" mode=1

I don't know if its relevant to the case just what I saw from the debugging from my end

### Reproduce

Run the docker-compose that I wrote on the Description block, and docker-compose up 

### Expected behavior

the docker-compose macvlan with IPAM should be created like docker network create, and if not there should be another way to create the same network with IPAM configuration that wont take 15 seconds.

### docker version

```bash
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker info

```bash
Server:
 Containers: 18
  Running: 1
  Paused: 0
  Stopped: 17
 Images: 171
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.48GiB
 Name: ubuntu
 ID: UGMT:YDHP:AAML:BGOX:67PT:GRNV:RXAG:J6A2:GKVS:56AO:C4KZ:Z2FR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
The error message indicates that the name of the plugin looks to be empty (the name of the driver should be shown after `unable to locate plugin:`;

```
level=warning msg="unable to locate plugin: , retrying in 1s"
level=warning msg="unable to locate plugin: , retrying in 2s"
level=warning msg="unable to locate plugin: , retrying in 4s"
level=warning msg="unable to locate plugin: , retrying in 8s"
level=error msg="Error handling plugin refcount operation" driver= error="plugin "\ not found" mode=1
```

That error message comes from `loadwithRetry()`;
https://github.com/moby/moby/blob/3e4c9d90cf6a796334519f0de12ff09608d7abbe/pkg/plugins/plugins.go#L219

It looks like a safeguard for that was implemented in https://github.com/moby/moby/commit/ee09f5a4afb4442c6cb6297ac133e52d7201cc72 (https://github.com/moby/moby/pull/39422), which is part of docker 20.10 and up.


It looks like you're running a very old version of docker (19.03) which reached EOL 4 years ago; are you still seeing this issue on a current (24.0) version of Docker?

**Comment by sam-thibault** [comment]
I will close this as stale.  You are welcome to comment on the issue if you reproduce this issue on a current release.
