### ISSUE TITLE
Golang client fails to attach to streams with "http: invalid Host header" with go1.20.6, go1.19.11

### ISSUE THREAD

**Issue by markusthoemmes** [moby/moby#45935]
### Description

Since updating to Golang 1.20.6, the moby Golang client starts failing with `http: invalid Host header` errors when used against the default unix socket at least. Normal container operations seem to be fine, but `ContainerAttach` and `ContainerExecAttach` fail in particular.

I'm assuming this is related to Golang backporting Host header sanitization into 1.20 via https://github.com/golang/go/issues/61076.

### Reproduce

Create a container with the Golang client and try to attach to its streams. I can try to cook up a minimal code example if necessary.

### docker version

```bash
github.com/docker/docker v24.0.4+incompatible
```

### docker info

```bash
Server:
 Server Version: 23.0.4
```

**Comment by markusthoemmes** [comment]
Overriding the header manually by adding a `client.WithHTTPHeaders(...)` option didn't work. Pinning the respective Dockerfile (this component runs in a container) to be built by 1.20.5 fixes the issue reliably.

**Comment by thaJeztah** [comment]
Yikes. Hm... yes we need to look into that; I didn't come round to updating the Go version in CI in this repository, so I guess we'll see things fail once we do 😬 

I hope we don't have to add back a hack as we did for compatibility with go1.6;

- https://github.com/moby/moby/pull/39076
- https://github.com/moby/moby/commit/3d6f5984f52802fe2f4af0dd2296c9e2e4a1e003 (https://github.com/moby/moby/pull/22000)

**Comment by thaJeztah** [comment]
Looks like CI is already broken, because the BuildKit integration tests we run don't pin to a minor version of go, so have been silently updated to go1.19.11; https://github.com/moby/moby/pull/45937#issuecomment-1632378822

**Comment by 246859** [comment]
I upgraded the go version to 1.20.6 today and also encountered this issue after recompiling my project, so I had to temporarily roll back the go version to ensure that the project runs normally.

**Comment by dsimansk** [comment]
@markusthoemmes thanks for reporting it promptly, great job! 😉

**Comment by dmizelle** [comment]
Came here as a NixOS user running into this via a Google search. If you are as well, please see https://github.com/NixOS/nixpkgs/issues/244159#issuecomment-1666551743.

**Comment by blop** [comment]
No backport to docker 23 ? I still have this issue in docker 23.0.6-r4, will try to bump to 24.

**Comment by thaJeztah** [comment]
Yes, it's been backported to the 23 release-branch; https://github.com/moby/moby/pull/45971, but no patch release has been done for 23.0 since. I should add there that no new `docker-ce` packages may be done for 23.0 (but Mirantis does do 23.0 binary releases, and the branch will be tagged at some point).

If you're using the code as a module / dependency, then I'd recommend updating your dependency to 24.0.x

**Comment by kayvansol** [comment]
Hi, everyone,
I have a problem in Calico pod in kubernetes :
https://stackoverflow.com/questions/77022403/calico-kube-controllers-and-calico-node-pods-is-not-ready-but-is-running

Please help me, I'm new in Kubernetes.
Thanks in advance.
