### ISSUE TITLE
Draft RFC link in pkg/archive outdated

### ISSUE THREAD

**Issue by bobidle** [moby/moby#45952]
### Description

I noticed the link to a Draft RFC in the file https://github.com/moby/moby/blob/master/pkg/archive/archive.go#L163 is outdated because the Draft RFC expired.

I suggest to change
```
https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html#rfc.section.2
```
to
```
https://datatracker.ietf.org/doc/html/rfc8878#section-3
```

But i am not sure if `datatracker.ietf.org` is the preferred page for RFCs.

### Reproduce

Try access
```
https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html#rfc.section.2
```

Will result in a 404 error

### Expected behavior

The link to the RFC should be valid.

### docker version

```bash
unrelated
```

### docker info

```bash
unrelated
```

**Comment by binary-exe** [comment]
Hi @bobidle, I'm a beginner who wants to start contributing to open-source projects. I reviewed this issue and checked the links. 

As you reported above, the previous link (https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html#rfc.section.2) gives 404 error. While the other link (https://datatracker.ietf.org/doc/html/rfc8878#section-3) has the detailed information regarding Zstandard Compression. The same documentation can also be accessed using this link (https://datatracker.ietf.org/doc/rfc8878/). 

I want to contribute to this issue and need your guidance in this regard. Your feedback would be highly appreciated. 

Regards,

**Comment by corhere** [comment]
Linking to the most specific section of the RFC relevant to the code being documented would be preferred over linking to the top of the same.

**Comment by wic006** [comment]
👋 Another open source beginner here. Agree with the point about linking to the specific section in the RFC.

> But i am not sure if datatracker.ietf.org is the preferred page for RFCs.

Fwiw, grepping the code suggests to me that there is precedence in both this project and others for using `datatracker.ietf.org` links for RFCs. I was potentially interested in picking this issue up, but I'll let @binary-exe the first stab at it 🙂.

**Comment by binary-exe** [comment]
> Linking to the most specific section of the RFC relevant to the code being documented would be preferred over linking to the top of the same.

I digged a little into RFC standards and found that Internet Engineering Task Force (IETF) is the maintainer of RFCs and the IETF Datatracker is official repository for RFCs. Hence, the link you recommended (https://datatracker.ietf.org/doc/html/rfc8878#section-3) is a valid RFC reference document.
