### ISSUE TITLE
If we use a .sh or .py(-rwxr-xr--.) has defined #!/bin/sh or #!/usr/bin/python3 as the pid=1 of the container, starting the container with a normal user without permissions will report an error "permission denied"

### ISSUE THREAD

**Issue by zzyyzte** [moby/moby#45968]
### Description

While golang >= 1.20, If we use .sh and .py as the pid=1 of the container, starting the container with a normal user without permissions will report an error "permission denied".

But If the golang <1.20, If we use .sh and .py as the pid=1 of the container, starting the container with a normal user will start the .py or .sh success.

Accutally, this error returned by runc.
```
        // Check for the arg before waiting to make sure it exists and it is
	// returned as a create time error.
	name, err := exec.LookPath(l.config.Args[0])
	if err != nil {
		return err
	}
```

[https://github.com/opencontainers/runc/blob/main/libcontainer/standard_init_linux.go#L202](https://github.com/opencontainers/runc/issues/url)

This error return by exec.LookPath. In golang 1.20, https://github.com/golang/go/commit/2b8f21409480931b45c983853a78dc7984ed634e
I can understand that this commit introduces Eaccess.

But if we comment out this line, runc can start a .sh or .py script without permissions(we should define #!/bin/sh or #!/bin/python3 in script).
Actually in scripts, even if the file's mode is 754(-rwxr-xr--.), we can also call /bin/bash .sh or /usr/bin/python3 .py to run this script successfully without permision.

I found that there is a parameter in capability CAP_DAC_ OVERRIDE affects this phenomenon. docker will add CAP_DAC_ OVERRIDE to the config.json file can successfully pull up permissionless .sh while golang < 1.20, which may be the cause of this problem. But while golang >= 1.20, this will get an error from runc "permission denied"

But now, After runc is compiled by golang>=1.20, this will not succeed anymore.

I've raised this issue in the runc community: https://github.com/opencontainers/runc/issues/3926

### Reproduce

1. dockerfile just like this:
```
FROM centos
COPY sleep.sh /
COPY sleep.py /
RUN useradd -u 1000 test
```
sleep.sh and sleep.py mode is 754, just means -rwxr-xr--. sleep.sh and sleep.py like this:
```
#!/bin/sh
echo "sleep"
sleep 1000
```
```
#!/usr/bin/python3
import time
time.sleep(1000)
print("hello world")
```
2. docker build -t centos:sleep .
3. use the older version runc compiled by golang<1.20
4. docker run -id -u 1000 centos:sleep ./sleep.sh
5. use the up-to-date runc compiled by golang>=1.20
6. docker run -id -u 1000 centos:sleep ./sleep.sh

### Expected behavior

If runc is compiled by golang>=1.20, it will return "permission denied".
If runc is compiled by golang<1.20, it will success.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:56 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:25 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.0+dev
  GitCommit:        v1.1.0-586-g92c71e7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.0-586-g92c71e7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.112-2.el8.x86_64
 Operating System: NewStartOS V4.4.2-ZTE
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 11.71GiB
 Name: LIN-9AC90CF34F9.zte.intra
 ID: VZRH:AFRQ:VE5F:K2XQ:Z4YE:K7QP:E6GB:74N5:J54M:7HQH:D6TH:I3QD
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 35
  System Time: 2023-07-14T15:19:25.370483303+08:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  0.0.0.0/0
  ::/0
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

compiled by golang >= 1.20

**Comment by corhere** [comment]
It sounds like runc compiled with go1.20+ is behaving as intended by returning EACCESS when attempting to start the container. Your premise is invalid: running `/bin/sh ./my-script.sh` is not the same as running `./my-script.sh` from a shell. When you run `/bin/sh ./my-script.sh` the kernel executes bash, and bash in turn _reads_ `my-script.sh`. The kernel checks that the user has execute permission on `/bin/sh` and _read_ on `my-script.sh`. In contrast, when you run `./my-script.sh` the kernel is instructed to _execute_ `my-script.sh`, and therefore checks that the user has execute permission on the file. If that check succeeds, the kernel then examines the shebang `#!` line to locate the interpreter and executes that, which then proceeds to read the script file. Therefore for `./my-script.sh` to succeed, the user must have _read and execute_ permission on the script file _and_ execute permission on the interpreter (`/bin/sh`).

Give it a try for yourself:
```
docker run -id -u 1000 centos:sleep /bin/sh ./sleep.sh
```

It's interesting you bring up CAP_DAC_OVERRIDE. Is the issue that CAP_DAC_OVERRIDE is not having any effect when a container is started as an unprivileged user on Docker v20.10? If so, this is "intended" behaviour
- https://github.com/moby/moby/pull/36587

which other users are objecting to as well
- #45491 

and your issue report is very timely.

**Comment by zzyyzte** [comment]
I don't know very well about the runc version in docker, but this phenomenon is caused by runc compiling with golang 1.20, because golang in 1.20, the exec.LookPath in exec package adds permission checking, resulting in CAP_DAC_OVERRIDE unable to pass the check, making the old version of docker inconsistent with the new version. I wonder if there is any solution for this inconsistency between the old and new versions in docker?

**Comment by neersighted** [comment]
I don't think there's anything more to do on the moby/moby side here; the issue with file capabilities not applying is on our side and is tracked in #45491, but ultimately the new runc behavior is more correct, and is fully controlled by runc.

I doubt that the runc behavior will change, so I would suggest you adjust your entrypoint to invoke the shell directly, or the permissions of your script.
