### ISSUE TITLE
gotest.tools/v3 is being compiled into release binaries

### ISSUE THREAD

**Issue by corhere** [moby/moby#45996]
I noticed a funny thing about the `libnetwork-setkey` reexec:
```console
$ (exec -a libnetwork-setkey "$(which dockerd)" -help)
Usage of libnetwork-setkey:
  -exec-root string
    	docker exec root (default "/run/docker")
  -update
    	update golden values
```

That `-update` flag is not defined by libnetwork-setkey. It's not part of the Moby code base at all. [It actually comes from the package `gotest.tools/v3/internal/source`.](https://github.com/gotestyourself/gotest.tools/blob/a80f057529047c44e1a85d0d017b200787e537e0/internal/source/update.go#L21-L23)

Ultimately, it's quite harmless. Aside from the help text from an implementation detail and slightly bloating the binary, it's essentially inert in dockerd as the flag only alters the behaviour of the `gotest.tools/v3/golden` package. Notably, the -`update` flag does _not_ pollute the help text for the dockerd CLI as the flag is registered with the stdlib `flag` package whereas the dockerd CLI uses Cobra for parsing arguments.

**Comment by corhere** [comment]
quota/testhelpers.go is my current prime suspect. The definitions are also used by volume/local/local_linux_test.go so it can't be trivially fixed by renaming the file to quota/testhelpers_test.go. The quota test helpers reference unexported symbols from the package, so they can't be trivially moved to a quota/quotatest package either. Fun!

**Comment by thaJeztah** [comment]
It looks like it might be doable to remove gotest.tools from that package though; it's using some basic err assertions and the fs package is only used to create a directory, which could be t.TempDir()
