### ISSUE TITLE
Make docker context update | create --from option to act as a base layer for later changes

### ISSUE THREAD

**Issue by Pascal-Flores** [moby/moby#46042]
### Description

Hello everyone ! I'm currently working on a project that requires me to duplicate the default docker config in order to modify it with some values I want. For example, I would like to have a context for development that uses the default context except for the "skipTLSverify" flag, that I would like to set to true. 

To do this, I used the command  `docker context create dev --from default --docker skip-tls-verify=true`, but it didn't work : 

`cannot use --docker or --kubernetes flags when --from is set`

As it didn't work, I used this command instead : `docker context create dev --docker from=default,skip-tls-verify=true --kubernetes from=default`
The command succeeded, but the new `dev` context was exactly the same context as the default one. 

Last, I tried to to what I wanted in two steps, by creating the dev context by using `docker context create dev --from default` and then `docker context update dev --docker skip-tls-verify=true`.
The command also succeeded, but the entire docker endpoint config was wiped and replaced by skipTLSVerify=true.

I think that this behaviour could be improved in multiple ways : 

1. The --docker and --kubernetes should only replace the field specified in the option, eg `docker context update dev --docker skip-tls-verify=true` should only modify the skipTLSverify field instead of wiping everything not mentionned in the option (and maybe add a --wipe option to obtain the same behaviour as now)

2. The --docker and --kubernetes `from` field should be used as a base for later update, eg `docker context create dev --docker from=default,skip-tls-verify=true` should copy the content of default context docker endpoint in the new context and then modify it with skip-tls-verify=true

3. The `docker context create`'s option --from could be also be used to act as 2.

Thanks for reading, hope to have updates on this as I think it could be a nice improvement :+1:

**Comment by thaJeztah** [comment]
What version of docker are you using? Are you using Docker Desktop? The `--kubernetes` options have been removed from `docker context`;

```bash
docker context create --help

Usage:  docker context create [OPTIONS] CONTEXT

Create a context

Docker endpoint config:

NAME                DESCRIPTION
from                Copy named context's Docker endpoint configuration
host                Docker endpoint on which to connect
ca                  Trust certs signed only by this CA
cert                Path to TLS certificate file
key                 Path to TLS key file
skip-tls-verify     Skip TLS certificate validation

Example:

$ docker context create my-context --description "some description" --docker "host=tcp://myserver:2376,ca=~/ca-file,cert=~/cert-file,key=~/key-file"

Options:
      --description string      Description of the context
      --docker stringToString   set the docker endpoint (default [])
      --from string             create context from a named context
```

However, Docker Desktop still ships with a wrapper for the CLI that looks like it still has these options;


```bash
docker context create --help
Create a new context

Create docker engine context:
$ docker context create CONTEXT [flags]


Create Azure Container Instances context:
$ docker context create aci CONTEXT [flags]
(see docker context create aci --help)


Create Amazon ECS context:
$ docker context create ecs CONTEXT [flags]
(see docker context create ecs --help)


Docker endpoint config:

NAME                DESCRIPTION
from                Copy named context's Docker endpoint configuration
host                Docker endpoint on which to connect
ca                  Trust certs signed only by this CA
cert                Path to TLS certificate file
key                 Path to TLS key file
skip-tls-verify     Skip TLS certificate validation

Kubernetes endpoint config:

NAME                 DESCRIPTION
from                 Copy named context's Kubernetes endpoint configuration
config-file          Path to a Kubernetes config file
context-override     Overrides the context set in the kubernetes config file
namespace-override   Overrides the namespace set in the kubernetes config file

Example:

$ docker context create my-context --description "some description" --docker "host=tcp://myserver:2376,ca=~/ca-file,cert=~/cert-file,key=~/key-file"

Usage:
  docker context create CONTEXT [flags]
  docker context create [command]

Available Commands:
  aci         Create a context for Azure Container Instances
  ecs         Create a context for Amazon ECS

Flags:
      --default-stack-orchestrator string   Default orchestrator for stack operations to use with this context (swarm|kubernetes|all)
      --description string                  Description of the context
      --docker stringToString               Set the docker endpoint (default [])
      --from string                         Create context from a named context
  -h, --help                                Help for create
      --kubernetes stringToString           Set the kubernetes endpoint (default [])

Use "docker context create [command] --help" for more information about a command.
```

**Comment by thaJeztah** [comment]
And I just realised this was opened in the moby/moby repository, but `docker context` is fully client side; perhaps you could open a ticket in https://github.com/docker/cli instead, because that's where the code is maintained (unfortunately, I can't move this ticket because GitHub doesn't allow tickets to be moved between orgs)

**Comment by Pascal-Flores** [comment]
Oh, ok thanks for your quick response. I'm using the devcontainer feature Docker in Docker, which Docker version is `Docker version 20.10.25+azure-2, build b82b9f3a0e763304a250531cb9350aa6d93723c9`. I don't know if the feature uses docker desktop or not. 

I think I will close this issue and open anoter one in the repo you mentionned.
