### ISSUE TITLE
Usage of SSH Docker context while local daemon is running will cause memory leak on remote host

### ISSUE THREAD

**Issue by TheSilkky** [moby/moby#46076]
### Description

Memory leak probably isn't technically the right term for this, but I thought it was the best way to describe what happens.

You probably think that this is an issue with the Docker cli not the Docker daemon, I originally thought the same. However, I've observed that this issue only occurs when the local Docker daemon is running and you add a remote Docker host using ssh. If the local daemon isn't running, this doesn't happen.

Adding a docker context using ssh will start to continuously create ssh sessions and `docker system dial-stdio` processes on the remote system, even when the context is not being used:
``` 
docker system dial-stdio
sshd: user [priv]
sshd: user@notty
```
Each of these processes only use a small amount of system resources, however over time they become a major issue. I left my computer on overnight and in the morning I had **hundreds** of these processes running on my server, using over 6GB of memory.

The strangest part of this issue and why I don't think it's necessarily completely related to Docker cli, is that if you stop the Docker daemon on your local system, all of the processes on the remote server will exit. I'm not sure why since as far I know, cli contexts and the Docker daemon shouldn't have much to do with each other.

Related issues / forum posts:
docker/cli#3528
[Docker Continuously Making Unnecessary SSH Connections to Remote Servers](https://forums.docker.com/t/docker-continuously-making-unnecessary-ssh-connections-to-remote-servers/136132)

### Reproduce

1. Make sure the Docker daemon is running on your local system.
2. Install Docker on another system, make sure it's accessible over ssh.
3. Add the remote docker context using ssh on your local system: `docker context create --docker "host=ssh://user@server" your-remote-context`
4. Switch to the new context: `docker context use your-remote-context`
5. Test that it's working: `docker info`
6. Wait a few minutes
7. Check the remote server for `docker system dial-stdio` processes: `ps aux`. There should be a few, wait longer and you should start to see more.
8. Stop the Docker daemon on your local system
9. Check the remote server if the processes are still running: `ps aux`

### docker version

```bash
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /Users/ellie/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /Users/ellie/.docker/cli-plugins/docker-compose
  deployx: Deploy a new stack or update an existing stack (aaraney)
    Version:  0.0.1
    Path:     /Users/ellie/.docker/cli-plugins/docker-deployx
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/ellie/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/ellie/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/ellie/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ellie/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/ellie/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /Users/ellie/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 27
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.668GiB
 Name: docker-desktop
 ID: 7c813daa-98e6-446a-9a03-0b4ec69bf2e1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Output of `docker info` on my remote server:
```
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 23
  Running: 20
  Paused: 0
  Stopped: 3
 Images: 36
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ...
  Is Manager: true
  ClusterID: ...
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: ...
  Manager Addresses:
   ...
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.4-200.fc38.aarch64
 Operating System: Fedora Linux 38 (Thirty Eight)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.544GiB
 Name: ...
 ID: ...
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting. I think this is an issue with Docker Desktop, and there are some tickets tracking (parts of this) internally.

Docker Desktop's Dashboard makes various calls to the Docker Engine API. While _most_ of those calls are always using the correct (local engine) API, some of them are using the currently selected context. When you switch your context to the SSH one, those API calls now try to access the remote server (for example, to present container logs, but I also see calls to the `/_ping` endpoint (checking if the API is accessible).

It may be best to open a ticket for this in the Docker Desktop issue tracker; https://github.com/docker/for-mac

**Comment by TheSilkky** [comment]
Yeah that makes sense, looks like there's an open issue already docker/for-mac#6834.

I'll close, thanks.

**Comment by thaJeztah** [comment]
Ah, thanks! I didn't go looking yet.

I know the team was working on some of these, and I just installed a "nightly build" when looking at this ticket (curious if things improved). Here's a gist with some testing I did; https://gist.github.com/thaJeztah/0eeb9f27b81148b36ed30265ce6e7138
