### ISSUE TITLE
Enable the OCI Exporter through the API

### ISSUE THREAD

**Issue by fussybeaver** [moby/moby#46089]
### Description

The arguments to building an image [includes an `outputs` parameter](https://github.com/moby/moby/blob/master/api/swagger.yaml#L8179-L8183), that only makes sense in a buildkit context, but allows a client to parameterize the image build, and is internally parsed similar to the [OCI export documentation](https://docs.docker.com/build/exporters/oci-docker/).

After tweaking the moby codebase a little, I've been able to write a client with protobuf handlers to export an OCI image through the API. 

I think it would be great to add this capability to API clients so they can take advantage of more features that use buildkit. Let me know if there's issues around the roadmap or deprecation plans that I should be aware of before posting a PR.

**Comment by neersighted** [comment]
I'm not sure we intend to add more features to the "REST BuildKit" API, but if the change is minimal it might make sense? I'd have to see a diff to fully understand what you mean, I suppose.

cc @tonistiigi @crazy-max

**Comment by fussybeaver** [comment]
That's good to know.. @neersighted . My initial work on the moby codebase itself is here https://github.com/moby/moby/compare/master...fussybeaver:moby:ND-api-exporters?expand=1 

If the REST BuildKit API is to become frozen, is focus moving elsewhere for clients that live outside the moby codebase?

**Comment by neersighted** [comment]
Indeed, `docker build` is now implemented by the `buildx` plugin for most users, and the general intention is that consumers of the BuildKit service provided by dockerd should use the gRPC API. The REST API supports upgrading a connection to gRPC, and a subset of `buildkitd` functionality is exposed by that gRPC endpoint.

**Comment by fussybeaver** [comment]
From what I can see,  the `/session` endpoint that's responsible for upgrading a connection to gRPC only creates a client connection [1], and does not provide any mechanism to connect to buildkit's server-side protobuf facilities.

[1] https://github.com/moby/moby/blob/d8fa6b6ae10bf3b9ceeef30f697b892d469a7d1f/vendor/github.com/moby/buildkit/session/manager.go#L112

**Comment by neersighted** [comment]
The full facilities of BuildKit should be available; I'm not quite sure what distinction you're drawing. For example, `buildx` is fully capable of `type=oci` exports from a build, and it uses the gRPC API upgrade method.

**Comment by tonistiigi** [comment]
> I'm not sure we intend to add more features to the "REST BuildKit" API,

OCI exporter works via session connection anyway (already gRPC) so this isn't just sending the value of `--output` via HTTP URL.

> That's good to know.. @neersighted . My initial work on the moby codebase itself is here https://github.com/moby/moby/compare/master...fussybeaver:moby:ND-api-exporters?expand=1

Afaics this tries to enable OCI exporter in the non-containerd storage backend. This does not work as only containerd backend keeps the original compressed layer and manifest blobs that are needed for constructing the OCI tarball. What would happen instead is that a new set of blobs are created each time with a walking differ, leading to undefined behavior and digest mismatches. If you enable containerd storage backend (currently experimental) then OCI exporter is already enabled and available.

**Comment by fussybeaver** [comment]
I see.. I did verify that the exported tarball was working with `docker image load`, but I'm not aware of any of those ramifications mentioned. 

Thanks for the tip about the `buildx` plugin, I see in the source a second endpoint is used `/grpc` I wasn't aware of, and I've been able to create a client grpc connection that way, so hopefully I can progress further that way.

**Comment by neersighted** [comment]
I'll close this as not useful/going to move any further, but I'm glad you found the correct method in the buildx source!
