### ISSUE TITLE
chore: remove daemon.reduceContainers and containerReducer

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#46082]
Looks like this functionality is no longer used, so we can probably include all of this in `Daemon.Containers`;

> I see some cleaning opportunities up in the future 🪄 . Looks like `daemon.reduceContainers` is only called in one place. And that always calls it with `daemon.refreshImage` as argument, so we can probably get rid of all that indirection.

_Originally posted by @thaJeztah in https://github.com/moby/moby/pull/46081#discussion_r1275093140_

**Comment by thaJeztah** [comment]
@vchiranjeeviak github doesn't allow me to assign, but let me add a label "status/claimed" on it! Thanks in advance for working on this; let me know if you need more input on what needs to be done (admitted, I noticed we could probably get rid of it, but didn't make a full pass over all the code affected).

**Comment by vchiranjeeviak** [comment]
Thanks @thaJeztah . I m starting my open-source journey with this. I hope this is not something very urgent. I can definitely use your mentorship whenever possible.

**Comment by vchiranjeeviak** [comment]
The function `daemon.reduceContainers` is only called inside `daemon.Containers` and that is the only line of code inside `daemon.Containers`. So, if we can eliminate the `daemon.reduceContainers` and add that code inside `daemon.Containers`, it avoids one extra function call. The `daemon.refreshImage` is also called only inside `daemon.reduceContainers`, but this function has it's own functionality and looks better to keep it separated that way.

**Comment by vchiranjeeviak** [comment]
Also, the test file `list_test.go` which tests the list feature only involves `Daemon.Containers` and not any other functions. So, I don't think any changes to the tests are required in this case. Can I go ahead and raise PR for this approach? @thaJeztah

**Comment by vvoland** [comment]
Thank you for your interest in contributing to Moby!

Yes, your approach seems to be aligned with what we have in mind!
Eliminating `daemon.reduceContainers` and inlining it into `daemon.Containers` definitely makes sense there.
Having done that, the `containerReducer` will no longer be used by anything, so in result we get rid of the whole "reducer" concept, so we should probably also rename the `reduce*` functions into something more descriptive (although I must admit, I don't have a good candidate for a name yet 😅).
`refreshImage` definitely deserves to stay in its own function.

> Can I go ahead and raise PR for this approach? 

Always feel free to open a PR! Even if you're unsure if your changes are correct, having a draft PR is always a good starting point for a discussion.

**Comment by vchiranjeeviak** [comment]
Hey, please check the changes in PR and let me know if you see any issues with the code or any improvements can be done. Thanks!

**Comment by lentil32** [comment]
https://github.com/moby/moby/pull/46484
@thaJeztah 
This issue would be closed

**Comment by vvoland** [comment]
Thanks! Closing this one as fixed.
