### ISSUE TITLE
Missing IPv4 interface in new created containers

### ISSUE THREAD

**Issue by roman-axe-web** [moby/moby#46119]
### Description

I run a simple home network where one of machines is serving docker containers.

I want to connect to served apps from external machine on the same network.
For example the URL that I am trying to access is `http://10.0.0.5:2000/`. I also plan to spin MySQL server (3306 port) and MongoDB (27017 port).

However, for some wired reason, only port 80 is available from external machine.
When I run `curl 10.0.0.5:2000` from **the machine that hosts containers (local)** I get the expected response - all good!
When I run `curl 10.0.0.5:2000` from **external machine** I get a Timeout error. (curl 10.0.0.5:80 works just fine).

Then I tried to spin a regular PHP server by running `php -S 10.0.0.5:2000` from CLI and it worked!
The php app was available on local and external machines. It means there is some issue with custom ports on docker's network.

When I run next command: `lsof -i -P -n | grep LISTEN | grep 80` or 443 port.
I get next output:
```
docker-pr   9329            root    4u  IPv4  74036      0t0  TCP *:80 (LISTEN)
docker-pr   9336            root    4u  IPv6  72199      0t0  TCP *:80 (LISTEN)`
```

However, when I test custom port like 2000 I get a bit different output:
```
lsof -i -P -n | grep LISTEN | grep 2000
dockerd     6858            root   81u  IPv6 464849      0t0  TCP *:2000 (LISTEN)
```

As you can see, the app doesn't served by IPv4. This issue doesn't allow me to connect to containers from external machine on the same network. (curl 10.0.0.5:2000 falls with timeout error).

Any idea what's wrong with my setup?

### Reproduce

1. Spin a test container
`docker service create --name nginx_service --publish 2000:80  nginx:latest`

2. Try to reach the container from external machine on the same network (for example: 10.0.0.5:2000).

3. Run `lsof -i -P -n | grep LISTEN | grep 2000`. 
Do you see IPv4 there?

### Expected behavior

I expect to have the container available via IPv4 so I can access it from external machine on the same network.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 16
  Paused: 0
  Stopped: 1
 Images: 23
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: yjag8tub3s10b28begmjh0kaz
  Is Manager: true
  ClusterID: khko8v5oamblrh51tfwsjf1f9
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.5
  Manager Addresses:
   10.0.0.5:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.55GiB
 Name: roman-All-Series
 ID: c97d9154-ce4c-4b06-8f28-2b47fdeabc52
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Since this is a home setup and not production, I disabled all the ufw / iptables or any other firewalls to test the connection.

I checked the `sysctl net.ipv6.bindv6only` to see if the system is configured to only serve ipv6 traffic only and got: `net.ipv6.bindv6only = 0`

**Comment by maietta** [comment]
net.ipv6.bindv6only = 0 means that you are in fact, able to resolve ipv4 traffic with ipv6 enabled on your machine, so effectively, ipv4 should be working here.

**Comment by akerouanton** [comment]
@maietta The process name isn't the same for both runs of `lsof`. Did you disabled `userland-proxy` at some point? Could you check if docker logs anything about port 2000?

**Comment by roman-axe-web** [comment]
@akerouanton , 
Nope, I didn't disable `userland-proxy`. 

If I perform curl to localhost (same machine that runs Docker) the 2000 port is working properly.
For example if I run curl 10.0.0.5:2000 - I get expected/successful return.

However, when I try to reach the container from external machine on the same network, I am getting timeout error.
Usually, this case is related to firewall limitations. But in my case, firewalls are disabled and I am successfully reaching other non-docker apps. (for example if I run `php -S 10.0.0.5:2000` - external machine is able to reach the content).

**Comment by akerouanton** [comment]
Looks like dockerd failed to program external connectivity. Could you try to recreate your container and then look at dockerd logs (`journalctl -u docker.service`) to check if something about this port was logged?

Also, could you copy/paste the output of `iptables -t nat -nvL` please?

**Comment by thaJeztah** [comment]
Let me close this one, as it looks like it went stale, and I haven't seen other reports of this, but feel free to comment if this is still an issue.
