### ISSUE TITLE
Missing Binaries for Docker 20.10.25

### ISSUE THREAD

**Issue by AlJohri** [moby/moby#46128]
### Description

The docker binaries are missing on both the docker binaries page and the github releases page for version 20.10.25.

### Reproduce

Go to the following URLs and you will not find the binary:
- https://download.docker.com/linux/static/stable/x86_64/
- https://github.com/moby/moby/releases/tag/v20.10.25

### Expected behavior

I expect to see the binary available, at least on the docker binaries page.

### docker version

```bash
20.10.25
```

### docker info

```bash
not applicable
```

**Comment by thaJeztah** [comment]
more details on that in this ticket; https://github.com/docker/cli/issues/4294

**Comment by corhere** [comment]
https://github.com/docker/cli/issues/4294#issuecomment-1570092208

> There's no plans to do further releases of docker-ce for the 20.10 branch. Mirantis does have a commercially supported MCR (Mirantis Container Runtime); which has LTS support (https://docs.mirantis.com/mcr/20.10/overview.html), which is based on the same code-base (with additional patches), and of course you can build from source.
>
> If you don't need a commercially supported version, I'd recommend upgrading to the currently maintained version (24.0), but of course verify the upgraded version before rolling out to production.
