### ISSUE TITLE
Docker unmounts ZFS subvolumes 

### ISSUE THREAD

**Issue by LinAGKar** [moby/moby#46148]
### Description

I am running Docker on OpenSUSE Leap 15.4 with /var/lib/docker on a ZFS volume, with some directories in my Docker volumes on ZFS subvolumes (so I can apply separate options for them, and take snapshots). However, after updating from Docker 20.10.23 to 23.0.6, it unmounts all subvolumes in the Docker volumes soon after it starts, making the containers fail to run (and the PostgreSQL databases broke and required restoring from backup). The info below is from a different test system I set it up on. It seems to happen regardless of storage driver, as the test system below used overlay2, while the server mentioned above uses the ZFS driver.

### Reproduce

1. Install docker and ZFS (from https://download.opensuse.org/repositories/filesystems/$releasever/filesystems.repo) on OpenSUSE
2. Create a ZFS pool
3. Create a ZFS volume at /var/lib/docker/
4. Start Docker
5. Create a Docker volume
6. Create a ZFS subvolume in the Docker volume, e.g. at `/var/lib/docker/volumes/<volume>/_data`
7. Restart Docker

The subvolume will now get unmounted

### Expected behavior

The volume should still be mounted

### docker version

```bash
Client:
 Version:           23.0.6-ce
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        9dbdbd4b6d76
 Built:             Sun May 21 12:00:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6-ce
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.9
  Git commit:       9dbdbd4b6d76
  Built:            Sun May 21 12:00:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061b76bb
 docker-init:
  Version:          0.1.7_catatonit
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 23.0.6-ce
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061b76bb
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.14.21-150500.53-default
 Operating System: openSUSE Leap 15.5
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 970.5MiB
 Name: localhost
 ID: bc7334a1-3929-4740-8f25-5d0330713d44
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
At a first glance, I suspect you may have depended on a bug in 20.10 (and older) or a certain behavior of the daemon in that version. The `/var/lib/docker/volumes/` location is the location where the daemon creates "managed" volumes, and it will create the `_data` path inside it for storing the volume's data. Any location within `/var/lib/docker` (or the storage location configured for the daemon) is designed to be exclusively accessed by the daemon. For volumes it will mount/unmount paths there, so if you manually mounted a path in that location then it's very much possible that the daemon mounts (or unmounts) those.

./cc @vvoland @cpuguy83 who may be more familiar with the exact flow in this area, and to keep me honest.

**Comment by vvoland** [comment]
The volume unmount is explicit behavior to recover from situations like unclean shutdowns.

The reason you didn't experience this on 20.10 is that the unmount was only performed if `opts.json` file existed (it stores additional volume mount options), which was considered a roundabout way to avoid unmounting on Windows (which also doesn't support these mount options).

This was changed later by https://github.com/moby/moby/pull/43632 making the unmount function no-op on Windows and unmounting the volume independently from loading the `opts.json` and 


Looking at it, I'm wondering whether the 7e907e29a32e1a3b7d5a1569e74e361d19876b0c was really correct, as under no circumstances daemon will mount the `_data` directory, if there are no additional volume opts:

https://github.com/moby/moby/blob/01a9c5b70ebf2a5cb873db0c72969d6758526a04/volume/local/local.go#L303-L306

https://github.com/moby/moby/blob/01a9c5b70ebf2a5cb873db0c72969d6758526a04/volume/local/local_unix.go#L105-L113

Opened a PR for further discussion: https://github.com/moby/moby/pull/46152

Note: Above comment is stil true - `/var/lib/docker` is expected to be exclusively accessed by the daemon and if you want to do anything there, you're on your own. However, given that it seems pretty common for users to either symlink `_data` or create a zfs/btrfs subvolume in its place, I think it's okay to put a minimal effort to not break this workflow.

**Comment by LinAGKar** [comment]
Thanks. It is quite useful, so it would be nice for it to work, even if it's not necessarily the intended usage
