### ISSUE TITLE
Getting access to image vulnerabilities via http api

### ISSUE THREAD

**Issue by danilapog** [moby/moby#46164]
### Description

Hello!

It would be nice to be able to get information about vulnerabilities present in the image remote with http api. 
Maybe I'm wrong, correct me, but as far as I know, now this is not possible.

_p.s.
I hope I opened an issue in the right repository_

**Comment by thaJeztah** [comment]
The Moby engine itself does not provide image scanning, so wouldn't be able to provide an API endpoint for this. On the Docker Hub side, there's https://docs.docker.com/scout/, which can be used with the `docker scout` CLI plugin (https://github.com/docker/scout-cli). There's an  API that's used by that plugin, but I'm not sure if it's documented / to be used externally.

If your question is about obtaining the scan information from docker hub, then either https://github.com/docker/hub-feedback or https://github.com/docker/scout-cli are probably better places to ask.

I'll close this ticket here, but feel free to continue the conversation.
