### ISSUE TITLE
Mixing up x86_64 with i386/x86

### ISSUE THREAD

**Issue by bwoodsend** [moby/moby#46196]
### Description

When using `docker run` or `docker build` with `--platform=linux/i386` followed by another such command but with `--platform=linux/x86_64`, the second command reuses the `i386` base image rather switching to an `x86_64` base image. `uname -m` still reports `x86_64` which mismatches package managers' repository configurations leading to some rather bizarre install errors.

### Reproduce

```fish
> docker pull --platform=linux/i386 alpine:3.18
3.18: Pulling from library/alpine
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Image is up to date for alpine:3.18
docker.io/library/alpine:3.18

> docker run --platform=linux/x86_64 alpine:3.18 cat /etc/apk/arch
x86  # <- Should have used an x86_64 image
```

### Expected behavior

Docker should see that the current `x86` Alpine image is not an `x86_64` image and pull the correct image. This is how Docker handles seemingly any other variant of the above (where the `x86` and `x86_64` are swapped or replaced with any other architectures) correctly.

```fish
> docker pull --platform=linux/x86_64 alpine:3.18
3.18: Pulling from library/alpine
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:3.18
docker.io/library/alpine:3.18

> docker run --platform=linux/i386 alpine:3.18 cat /etc/apk/arch
Unable to find image 'alpine:3.18' locally
3.18: Pulling from library/alpine
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:3.18
x86
```

### docker version

```bash
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
 runc:
  Version:          1.1.8
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx

Server:
 Containers: 20
  Running: 2
  Paused: 0
  Stopped: 18
 Images: 57
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.3-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.494GiB
 Name: manjaro-2212
 ID: HBWP:AGRX:MHCB:XEVM:37M2:Z4PF:37RF:GDXA:7KP4:DERV:2JNI:XGKR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mayeut** [comment]
https://github.com/moby/moby/issues/48197#issuecomment-2282802313 seems to be the same issue as this one

**Comment by bwoodsend** [comment]
It's a real pain, this. I do a lot of bulk building/testing and this statefulness has meant that I've had to put redundant `docker pull` commands before each `docker run` and use `docker build --pull`. I keeping having to pause working because I've exceeded by 200 hub.docker.com pulls limit even though I didn't want to make more than a few pulls a week in the first place.

**Comment by yosifkit** [comment]
This stems from the inability of the default storage driver to be able to have a tag point to a multi-platform image. If you switch to the ["containerd image store"](https://docs.docker.com/engine/storage/containerd/), then it will be able to keep both architectures under the tag (if they came from the same image index). Then you can swap between them as needed (assuming you have them pulled locally).

- regular warnings that the containerd content store integration is still experimental. All of your current local images will not be available when switching (and vice versa if you switch back). The https://github.com/moby/moby/labels/containerd-integration label is tracking the issues and fixes for it.

**Comment by bwoodsend** [comment]
Nice! That works.
