### ISSUE TITLE
Replace existing /etc/hosts entries when using --add-host

### ISSUE THREAD

**Issue by MShekow** [moby/moby#46235]
### Description

Use case: I would like to have `localhost` inside the container point to a different IP (e.g. the IP of `host.docker.internal`).

When I run something like `docker run --add-host "localhost:host-gateway" <image>` (where Docker engine replaces `host-gateway` with the IP of `host.docker.internal`), I get a `/etc/hosts` file like the following:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.65.254	localhost
172.17.0.3	d4cb03d9b34e
```

When I then run `ping localhost` or other tools inside the container, `127.0.0.1` is always returned. I first have to remove the first line "manually" (in some entrypoint script), which is cumbersome, because I need root privileges to do this.

My feature request is to ask that Docker _replaces_ (rather than just _adding_) entries for hostname already present in `/etc/hosts`, so that the `127.0.0.1	localhost` entry is replaced by `192.168.65.254	localhost`.

**Comment by neersighted** [comment]
This file is scaffolded entirely by the daemon, so allowing overriding default entries could only be used to replace `localhost`. Outside of the UX challenges in exposing this in a non-confusing way, overriding `localhost` should not be done -- it will potentially break 'core' parts of the OS in the container (e.g. nsswitch plugins), and will potentially cause issues with other software, in non-obvious ways.

I'm going to close this issue as wontfix for the above reasons, but please feel free to continue to discuss what you're trying to achieve here, so better advice on how to accomplish it may be given.
