### ISSUE TITLE
Feature Request: Allow mirrors for other repos besides DockerHub

### ISSUE THREAD

**Issue by grochoge** [moby/moby#46319]
### Description

It's possible to configure [registry mirrors](https://docs.docker.com/registry/recipes/mirror/), but it's hardcoded to only work for docker.io

https://github.com/moby/moby/blob/cfd431d4d57c987353d84f5709af1ec7493278c7/daemon/daemon.go#L196

Please expand configuration to allow using mirrors for other servers (such as mcr.microsoft.com).

**Comment by thaJeztah** [comment]
looks like a duplicate of https://github.com/moby/moby/issues/18818
