### ISSUE TITLE
Dockerfile: error in image with VOLUME instruction

### ISSUE THREAD

**Issue by augusto-sb** [moby/moby#46399]
### Description

i was using the following image: porchn/php5.6-apache and discovered and error
if the VOLUME instruction is an array o single quotes paths it gives an incorrect path, when i try to mount something in the container it says:
invalid mount path: '[/etc/apache2/sites-enabled,/var/www,/var/log/apache2]' mount path must be absolute

so to reproduce i did a Dockerfile
```
FROM docker.io/alpine:3.18.3
VOLUME /path1 /path2
VOLUME [/path3,/path4]
VOLUME ["/path5","/path6"]
VOLUME ['/path7','/path8']
```

the 2nd and 4rd VOLUME instructions didnt work as expected

### Reproduce

```bash
docker build -f Dockerfile -t test .
docker run --rm -ti test sh
/ # tree /[
/[
├── path3,
│   └── path4]
└── path7,
    └── path8]
```
and

docker image inspect test

            "Volumes": {
                "/path1": {},
                "/path2": {},
                "/path5": {},
                "/path6": {},
                "[/path3,/path4]": {},
                "[/path7,/path8]": {}
            },

### Expected behavior

i think the behaviour should be an error during the build or correctly splitting the array

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 0
  Paused: 0
  Stopped: 13
 Images: 57
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-83-generic
 Operating System: Linux Mint 21.1
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.46GiB
 Name: augusto-HP-Pavilion-Gaming-Laptop-15-dk0xxx
 ID: EJ5I:L4S7:NQ3S:6G5Z:MOFR:45BR:DBJW:HJG5:6FMK:QM3N:YA7O:2HAW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

sorry for my english if i explained myself badly ill try to correct

**Comment by vvoland** [comment]
In JSON format single quotes are not equivalent to the double quotes. This is also documented in the Dockerfile reference: https://docs.docker.com/engine/reference/builder/#volume

> JSON formatting: The list is parsed as a JSON array. You must enclose words with double quotes (") rather than single quotes (').

As for making this a build time error - the [Buildkit repository](https://github.com/moby/buildkit/issues) would be a better place to discuss this.


\cc @crazy-max  @tonistiigi

**Comment by augusto-sb** [comment]
thank you for the response, ill post it in the buildkit repository, have a great day!

**Comment by thaJeztah** [comment]
Yes, the classic builder would print a warning / informational message for cases where the format "may" be JSON (but it fell back to using "non-JSON" syntax); unfortunately, BuildKit currently does not have a mechanism for that;

- related https://github.com/moby/buildkit/issues/1952

I'll close this ticket here, but feel free to continue the conversation.
