### ISSUE TITLE
containers are not restarted after docker daemon has been restarted

### ISSUE THREAD

**Issue by rstrlcpy** [moby/moby#46465]
### Description

Don't know it is bug or by-design.

The simple example:

```
version: "3"
services:
    rproxy:
        deploy:
            restart_policy:
                condition: "on-failure"
                delay: 10s
                max_attempts: 3
                window: 2m0s
        image: nginx:latest
```

If docker-daemon is restarted the container is not started. I tried to set `condition: "always"` but the value is not compatible with the `delay`, `max_attempts`, `window`

### Reproduce

```
$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

$ docker-compose -f 1.yaml up -d
[+] Running 1/1
 ⠿ Container tmp-rproxy-1  Started

$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS     NAMES
f9217ad5c474   nginx:latest   "/docker-entrypoint.…"   48 seconds ago   Up 47 seconds   80/tcp    tmp-rproxy-1

$ sudo rc-service docker restart
 * Stopping docker ...                                                                                                                                 [ ok ]
 * Starting docker ...

$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED              STATUS                      PORTS     NAMES
f9217ad5c474   nginx:latest   "/docker-entrypoint.…"   About a minute ago   Exited (0) 19 seconds ago             tmp-rproxy-1
```

### Expected behavior

It would be useful if the running containers are started automatically after docker-daemon has been restarted

### docker version

```bash
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ced0996600
 Built:             Thu Sep  7 16:19:33 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       4ffc61430bbe6d3d405bdf357b766bf303ff3cc5
  Built:            Fri Sep  8 02:11:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.7
  GitCommit:        4ffc61430bbe6d3d405bdf357b766bf303ff3cc5
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad007797e0dcd8b7126f27bb87401d224240
```

### docker info

```bash
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: 4ffc61430bbe6d3d405bdf357b766bf303ff3cc5
 init version: de40ad007797e0dcd8b7126f27bb87401d224240
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.1.41-gentoo-x86_64
 Operating System: Gentoo Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.32GiB
 Name: gentoo-rzenbook
 ID: 99477bb9-807a-4768-95ec-d6e6d470fbea
 Docker Root Dir: /opt/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by neersighted** [comment]
This is as-documented/by-design; the `on-failure` policy **only** restarts if a container exits with non-zero status. Daemon restart is intentionally not handled.

**Comment by rstrlcpy** [comment]
I think there is a bug as the code doesn't set HasBeenManuallyStopped = true on daemon.IsShuttingDown().

**Comment by thaJeztah** [comment]
> the code doesn't set HasBeenManuallyStopped = true on daemon.IsShuttingDown().

That looks to be expected, as shutting down the daemon doesn't imply that the container itself is "manually stopped"

**Comment by rstrlcpy** [comment]
My point here is: Docker knows that on reboot or daemon-restart it stops containers so it would be useful to return the containers beck to their previous state. Or I'm wrong somewhere?

**Comment by neersighted** [comment]
This is the currently intended/documented behavior, and is long-standing. Whether or not it is surprising from a UX standpoint/if we should deprecate the current option and introduce a new (**incompatible**) behavior is a slightly different discussion is one that we are currently having internally however.

You are also welcome to create your own feature request/design proposal if you would like -- the key thing to keep in mind is that we cannot change the behavior of a long-standing option like this in a backwards incompatible way, so we would likely have to preserve this behavior and design something new to replace it.

**Comment by rstrlcpy** [comment]
> This is the currently intended/documented behavior
that is the main issue. The opt is not well documented. There is no info that describes the behavior in case of reboot/daemon-restart. That is why I'm here. Moreover different projects process the system-signals differently so that one exists with non-zero and will be restarted after reboot/daemon-restart, another one will not be because exited with zero-code.

**Comment by neersighted** [comment]
It's described a bit in the negative space/this is maybe not surprising to longstanding users, but I agree that we could make it more explicit. PRs are welcome against docker/docs, as are issues.

cc @dvdksn if you don't mind putting this on your backlog.

**Comment by neersighted** [comment]
I'm going to close this issue out as the docs issue is solved; please feel free to open the suggested feature request/proposal if you want to take on designing a replacement for `on-failure`.
