### ISSUE TITLE
Docker Debian packages changed (different checksum) 

### ISSUE THREAD

**Issue by nudgegoonies** [moby/moby#46470]
### Description

The following files changed upstream:
http://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-compose-plugin_2.21.0-1~debian.10~buster_amd64.deb
http://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce-cli_24.0.6-1~debian.10~buster_amd64.deb
Debian packages must be immutable. But the files changed in the signature at the end (compose plugin):
```
diff sig.failed sig.correct 
1c1
< Z_gpgbuilder     1693932742  0     0     100644  1265      `
---
> Z_gpgbuilder     1694192471  0     0     100644  1265      `
7c7
< Date: Tue Sep  5 16:52:22 2023
---
> Date: Fri Sep  8 17:01:10 2023
16,28c16,28
< iQIcBAEBCgAGBQJk91zGAAoJEH6gqcPyc/zY5loQANpNeDjAMXF+5/2+B2NOD85J
< 3p6Zyu6UVfqTG4ZBoYckcGYjqgv0lQNiFzjGGbCza4biiwjmwCK3c9n1RYsyKGh+
< Y/P4DVUA5o6HLjoyazFOLgxV2N2DpJc/4PdQ+dhr1m0SyCKONRlgVPRJmiYWkR4g
< +vip9dO/FAlOWi0+lN7aa8tse9nCKCLKNaZ9F1KB1elSG7V2FtHALvda6dQ6baCv
< 6efyn3Ckv08h8VHG8qq0WcZ9uFrBKfl0cQP/giPMarB+1jX+ins7LcCv97Kgn9jq
< HmiHZdyWEfnF6KDHNqYDN6cm7qDesA0f4qTlZ2Yxm4BbsJvpj2i4SFULpORBz/E6
< cBqjOMTPJAoZdOMHb3z1EWfJqpCPyykGqvJsp014RIszoNFHfDC9vopKwZ8CNuTg
< 87fvN8abhGUv0zAKmlnAA4i6Kl+L7tjUnm1hP9Yiuk0GdlSuP0G97wPZOzws0o8I
< lBC4fc/vTlFPlAEfxAAz/YEELEFxpbmLcI0ogIZgLcQ0b4vW28LSxNpgobijskpf
< 6Yuy3v+FqtP0GZJLuwGqyPgFircC6SxFqcoNYkBAuwByFiFiS4jzBgqLUjhjLxVo
< pV36MDx7fc/jy7IHY4iHhuez/KZDMHfoFIW9X11WUIgATgP5Ux6poyfZSKI377H2
< Avmo3INRitUzGWI6NPuw
< =k5e1
---
> iQIcBAEBCgAGBQJk+1NWAAoJEH6gqcPyc/zYILwQALy2qEI6d46ALOsFOMKJ/HVP
> Qkt8kYDwusfPf9ypi70geLWzAdZgOdGZiInwlyE1UTKYxqq2DOFoM17v9xmUg9k2
> fOwNO4ymQmhbJITK/ou+7ezUgcegx7FW/tAyL6iDSt22XEelpgl3gRt1sd4LnKNo
> qJKZ4HTZ/V9v8Zn/8t5lnbrjBECbLRfHj2eQ2PvtIvlvCSfpZdC/GEBJugpUwe9W
> DfhE1PZviAk8k/tWWEalGrjKFg1pVkEfsvqxMfnWJeWjFocMoclfCc3w31guWAky
> XvHAx+m+95jK8hYs/9pw1Nt0ifg1nVgxXby1Sn+1tOayz3fMLhWc8BfQhKbWR1b8
> T3/WxnuJZ+E0vt576N1uZpIX3/2/i2v2jFwDLT2etNAJfGeikcKmPtFaluSxmQ1X
> WWWR+qBmOGQM4v63TEyChEME0rFZlI3nHT/op9HRWBrRiY7h2NfVdDP5+PGuGVN9
> Lg1s4Hk4jPfptYiAx4WI5jxNfmOlJgWXma59xO7yiNpaiuQQ2kfFcK6rvyrfD1hv
> SJW2GnL3oq9XQa/VYk7H3KqqyA50QGG/BGZ9ypDTRC756qACJYoZzB8auw6jmrfe
> vexegsRpvG0x3arXQuhPnkY6P6YrPISPzjItGrJ8OIvIyntkgvocwZMEyjf+MVzX
> 70YtCyP2FHuvZHHK/wXH
> =pWOq
```
This breaks proxies, caches and mirrors that correctly expect debian packages to be immutable.

### Reproduce

apt-get update
apt-get install docker-ce-cli
(via a proxy, cache or mirror that keeps the file with the old signature)

### Expected behavior

Never change an existing debian package.

### docker version

```bash
irrelevant
```

### docker info

```bash
irrelevant
```

**Comment by neersighted** [comment]
Howdy,

This was the result of a pretty extraordinary situation with our infrastructure, that required either:
* repository state (index + signatures) to be rebuilt from the last deploy
* indefinite revert of the 24.0.6 patch while we attempted another method

We ended up choosing the first; I don't expect this situation will ever come up again, but it could be helpful to know exactly how this could break downstream users. The previous signatures are valid and the index was rebuilt to match, and the packages are identical. Given that, the only thing I would expect to break is a tool that compares the packages on download.docker.com against those on a mirror.

**Comment by nudgegoonies** [comment]
Thank you very much for the answer.

In our case it is a caching proxy tuned for deb and rpm package repositories to reduce load from the servers in our data-centers. For example puppet runs every hour and does a apt-get update.

Another load is the daily building of lots of team specific docker images used on the internal gitlab runners which all contain docker-cli to talk to their dind to build docker images with our inhouse software.

The metadata of the deb/rpm repositories is cached only for a short time until the proxy checks upstream for changes. But because deb and rpm are idempotent the proxy does not check upstream for changes of packages itself. We had to invalidate the affected files in the caching proxy.

You are right. A real mirror would sync every change from upstream and is thus not affected.

**Comment by neersighted** [comment]
I see; I wonder how common that is (and how expensive it would be to add an Etag check to your proxy).

@tianon Do you know what apt-cacher-ng (or what your homebrew version) would do here?

**Comment by nudgegoonies** [comment]
@xorpaul Could etags be an option?

**Comment by neersighted** [comment]
I'm going to close this for now since it's tangential to the upstream Moby project; please feel free to continue the discussison however.

I will also think about surfacing a better/official forum for discussion/feedback/suggestions for Docker CE/Docker Inc.'s packaging, and making that discoverable.
