### ISSUE TITLE
profiles/seccomp: default profile for clone(2) has invalid flag index for x86_64

### ISSUE THREAD

**Issue by sitano** [moby/moby#46568]
### Description

It seems to me that this (`Index: 0`) only works 
https://github.com/moby/moby/blob/master/profiles/seccomp/default_linux.go#L615-L656 at x86_64 because runc seccomp profilers compiler completely ignores all unknown terms during json parsing such that Includes and Excludes are ignorred. And thus this https://github.com/moby/moby/blob/master/profiles/seccomp/default_linux.go#L581-L613 compiles into just the ALLOW list. 

### Reproduce

strace something, x86_64, arch linux:

```
clone(child_stack=NULL, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_PTRACE|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[1122058], tls=0x7ffd07c3ba10, child_tidptr=0x3f) = 1122058 <0.000029>
```

the first arg is the child_stack.

### Expected behavior

```
	"syscalls": [
		{
			"names": [ "clone" ],
			"action": "SCMP_ACT_ERRNO",
			"errnoRet": 1,
			"args": [ { "index": 0, "value": 2180898815, "op": "SCMP_CMP_MASKED_EQ" } ]
		},
		{
			"names": [
				"clone3"
			],
			"action": "SCMP_ACT_ERRNO",
			"errnoRet": 38
		}
	]
```

to block `clone`, but the index is wrong.

### docker version

```bash
-
```

### docker info

```bash
-
```

**Comment by thaJeztah** [comment]
Do you have a runnable example to reproduce the issue you're running into? It's also worth noting that the profile is the _template_ to generate the seccomp profile that will be included in the OCI spec for the container (which can differ based on architecture and capabilities added to the container, as well as kernel version).

To find the actual OCI spec used for the container, you can lookup the `state.json` for the container that's used by runc; you can find the file (while the container is running) in `/var/run/docker/runtime-runc/moby/<CONTAINER-ID>/state.json`, for example to get the `config.seccomp` for the container with ID `b4b979bee559229d6aae08c57dad7f7f33fd80b57a79dd1c3bd7cc63ac82b1b4`;

```bash
cat /var/run/docker/runtime-runc/moby/b4b979bee559229d6aae08c57dad7f7f33fd80b57a79dd1c3bd7cc63ac82b1b4/state.json | jq .config.seccomp
```

**Comment by sitano** [comment]
@thaJeztah Later I will write the reproducer in C to check if I missed something or not. I am not sure how to understand what is the exact layout of syscall arguments. I thought it must be defined by the syscall def in the source code.

I took the compiler from the `runc` and I could not find the parts that do compile Include and Exclude tags so those 2 were identical for me:

```
{
	"defaultAction": "SCMP_ACT_ALLOW",
	"defaultErrnoRet": 5,
	"archMap": [
		{
			"architecture": "SCMP_ARCH_X86_64",
			"subArchitectures": [
				"SCMP_ARCH_X86",
				"SCMP_ARCH_X32"
			]
		}
	],
	"syscalls": [
		{
			"names": [
				"clone",
				"clone3"
			],
			"action": "SCMP_ACT_ALLOW"
		}
	]
}
```

and

```
{
	"defaultAction": "SCMP_ACT_ALLOW",
	"defaultErrnoRet": 5,
	"archMap": [
		{
			"architecture": "SCMP_ARCH_X86_64",
			"subArchitectures": [
				"SCMP_ARCH_X86",
				"SCMP_ARCH_X32"
			]
		}
	],
	"syscalls": [
		{
			"names": [
				"clone",
				"clone3"
			],
			"action": "SCMP_ACT_ALLOW",
			"includes": {
				"caps": [
					"CAP_SYS_ADMIN",
					"# this section (includes) is not compiled"
				]
			}
		}
	]
}
``` 

resulting in

```
00000000: 2000 0000 0400 0000 1500 0004 3e00 00c0   ...........>...
00000010: 2000 0000 0000 0000 3500 0001 0000 0040   .......5......@
00000020: 1500 0001 ffff ffff 0600 0000 0000 ff7f  ................
00000030: 0600 0000 0000 0000                      ........

00000000: 2000 0000 0400 0000 1500 0004 3e00 00c0   ...........>...
00000010: 2000 0000 0000 0000 3500 0001 0000 0040   .......5......@
00000020: 1500 0001 ffff ffff 0600 0000 0000 ff7f  ................
00000030: 0600 0000 0000 0000
```

maybe I missed something.

Then this profile has to block CLONE_CHILD_CLEARTID calls of clone(2) when doing `$ bash` but it does NOT:

```
{
	"defaultAction": "SCMP_ACT_ALLOW",
	"defaultErrnoRet": 5,
	"archMap": [
		{
			"architecture": "SCMP_ARCH_X86_64",
			"subArchitectures": [
				"SCMP_ARCH_X86",
				"SCMP_ARCH_X32"
			]
		}
	],
	"syscalls": [
		{
			"names": [
				"clone"
			],
			"action": "SCMP_ACT_ERRNO",
      "errnoRet": 5,
			"args": [
				{
					"index": 1,
					"value": 2097152,
					"op": "SCMP_CMP_MASKED_EQ"
				}
			],
      "includes": {
        "comments": [
          "$ bash # induces -->",
          "clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f2d7c5bfa10)",
          "/usr/include/linux/sched.h: CLONE_CHILD_CLEARTID is 0x00200000 = 2097152",
          "this compiles into AND #2097152 + JEQ #0, X. where X is the num of instr to pass.",
          "so this declaration must filter out CLONE_CHILD_CLEARTID calls of clone(2).",
          "but it does not work."
        ]
      }
    }
  ]
}
``` 

then

```
$ docker run -it --rm --security-opt="seccomp=/tmp/example.json" debian bash
root@68cc6fcfa6c5:/# bash
root@68cc6fcfa6c5:/# exit
exit
root@68cc6fcfa6c5:/# exit
exit
```

if you will change the `Argument index to 1` it will work:

```
$ docker run -it --rm --security-opt="seccomp=/tmp/example.json" debian bash
root@7e80ee603792:/# bash
bash: fork: Input/output error
root@7e80ee603792:/# exit
exit
```

**Comment by sitano** [comment]
Speaking of Includes and Excludes maybe Moby level loader filters out syscalls blocks depending on the requested Bounding set. Not sure. But they are for sure are not getting filtered at the runc.

**Comment by sitano** [comment]
Seems like I confused something. Closing.
