### ISSUE TITLE
Add until filter to docker image ls (classic image backend)

### ISSUE THREAD

**Issue by RachitSharma2001** [moby/moby#46576]
### Description

Currently, `docker image ls` only accepts `since` and `before` filters, which are based on image ids. As seen [here](https://github.com/docker/cli/issues/3962) and [here](https://stackoverflow.com/questions/24659300/how-to-use-docker-images-filter/75095332#75095332), this feature would be useful to people who want to list out images that were created before a particular time. For example, one should be to do: `docker image ls --filter "until=6m"`

**Comment by corhere** [comment]
The `until` filter [was added to the (experimental) containerd image backend](https://github.com/moby/moby/pull/45270/commits/f8463498244fd505e82e6f65b07a44d007076fb4) but was not backported to the classic backend.
