### ISSUE TITLE
Docker daemon logger Log() method return type

### ISSUE THREAD

**Issue by tshan2001** [moby/moby#46635]
### Description

It was noticed that in the `Log()` method in the docker daemon daemon logger for AWS CloudWatch, the method will always return `nil` as error unless the log stream is EXPLICITLY closed. 
https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L437-L438.

Seems like all this function is doing is pushing the input log message to the log stream's channel to be consumed. May I ask are we assuming that the as long as the log stream stays open the logs are guaranteed to be delivered? Do we have some mechanism in place to actually confirm that the logs were delivered to the destination, in this case the CloudWatch log stream, as expected? Due to this lack of visibility, we were not able to confirm whether logs were delivered in the shim-logger, since shim-logger essentially depends on the error returned by the docker daemon's logger's `Log()` method to determine whether log redirection was successful. See shim-logger source: https://github.com/aws/shim-loggers-for-containerd/blob/0fe081af7810db59dd851915ee82e9604e725b34/logger/common.go#L295.

**Comment by thaJeztah** [comment]
I must admit that I'm not deeply familiar with that logging driver; most of the code in that logging driver was contributed by people on the AWS team (maybe @PettitWesley  or @samuelkarp can provide more pointers)


In general, I'd be cautious using this package for other projects; these drivers were really written specifically as adaptor / driver between docker's plugin API and (in this case) the AWS sdk / API, which may be very different from how the containerd shims work., and should mostly be considered internal packages (as most packages under the `daemon/` directory).

**Comment by tshan2001** [comment]
Thanks for the quick response! Will reach out to the AWS developers for more context. Thanks again!

**Comment by neersighted** [comment]
I'm going to close this for now as solved as these packages are really internal/should not be depended on by external consumers. If anything, a PR likely would be welcome that made dockerd depend on a definitive "awslogs for containers" implementation if one was created.

With hindsight being perfect, this code would have been `internal`/, but most of dockerd is importable even if you probably (really!!!) shouldn't import 90% of the codebase.

**Comment by samuelkarp** [comment]
> With hindsight being perfect, this code would have been `internal/`, but most of dockerd is importable even if you probably (really!!!) shouldn't import 90% of the codebase.

It'd be fairly reasonable for us to do that now, especially as we're moving major versions regularly and aren't attempting to be a semver-compatible library.
