### ISSUE TITLE
docker 20.10 deadlock

### ISSUE THREAD

**Issue by hdp7891000** [moby/moby#46661]
### Description

https://github.com/moby/moby/pull/44682
I found this problem in v20.10.23. 
Looking at the code of 20.10.26, it seems that it has not been fixed. 
Will it be fixed in the later 20.10 version?

### Reproduce

https://github.com/moby/moby/pull/44682

### docker version

```bash
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:30:35 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:36:08 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 61
  Running: 61
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-284.11.1.el9_2.x86_64
 Operating System: Rocky Linux 9.2 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 40
 Total Memory: 125.1GiB
 Name: rocky-t-01
 ID: GYEC:CN4V:YBBJ:K5FR:KOCT:HDWP:LWYQ:KFX4:RAMJ:3OYQ:WWO4:GQ7T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Live Restore Enabled: true
 Product License: Community Engine
```

**Comment by hdp7891000** [comment]
@thaJeztah 
Hello, can you help confirm?
The previous link cannot be replied to, so I raised a new issue.

**Comment by thaJeztah** [comment]
> Looking at the code of 20.10.26, it seems that it has not been fixed.

https://github.com/moby/moby/pull/44682 (https://github.com/moby/moby/commit/7f3a95d3608a363f704ed338c97ae8e6da54cb7f) is part of docker 20.10.23; can you elaborate "looking at the code", and what's not fixed?

Note that Docker will no longer publish updated packages for 20.10 (the release branch is still maintained, as other parties may still use it for building packages).

**Comment by hdp7891000** [comment]
> > Looking at the code of 20.10.26, it seems that it has not been fixed.
> 
> #44682 ([7f3a95d](https://github.com/moby/moby/commit/7f3a95d3608a363f704ed338c97ae8e6da54cb7f)) is part of docker 20.10.23; can you elaborate "looking at the code", and what's not fixed?
> 
> Note that Docker will no longer publish updated packages for 20.10 (the release branch is still maintained, as other parties may still use it for building packages).

https://github.com/moby/moby/pull/42545 is not included in 20.10.26. 
I also looked at https://github.com/moby/libnetwork/blob/master/store.go and it is not included.

**Comment by thaJeztah** [comment]
- https://github.com/moby/moby/pull/42545 is a pull request against the master branch;
- it looks like it was backported to the 20.10 release branch through https://github.com/moby/moby/pull/44682. Docker 20.10 still uses libnetwork from the https://github.com/moby/libnetwork repository, which received the same patches through https://github.com/moby/libnetwork/pull/2670


> I also looked at https://github.com/moby/libnetwork/blob/master/store.go and it is not included.

How did you look for that? https://github.com/moby/moby/commit/0c1a125644f4626b294cdd4b5862a728b1d974a7 looks to be  in master; 

<img width="291" alt="Screenshot 2023-10-18 at 17 24 04" src="https://github.com/moby/moby/assets/1804568/b63441f8-8f33-4a51-a7ba-9fd1b81e8fd4">

And looking at master at the current commit (https://github.com/moby/moby/commit/70589b8548ad71d46ae77babc2f963a1438bf515/); https://github.com/moby/moby/blame/70589b8548ad71d46ae77babc2f963a1438bf515/libnetwork/store.go#L206

<img width="941" alt="Screenshot 2023-10-18 at 17 25 13" src="https://github.com/moby/moby/assets/1804568/950877ac-f88e-4c5a-887f-3e33db1613d6">


Is there specific code you're missing in any of those branches? If so, could you be more specific and link to the lines that are missing the patches?

**Comment by hdp7891000** [comment]
Docker 20.10 still uses libnetwork from the https://github.com/moby/libnetwork repository, but there are only modifications to processEndpointCreate and no modifications to processEndpointDelete. 
Please see processEndpointDelete at https://github.com/moby/libnetwork/blame/master/store.go.
