### ISSUE TITLE
Docker push: Pushing blob chunks could have a max chunk size hint

### ISSUE THREAD

**Issue by gabivlj** [moby/moby#46744]
### Description

Hi! We've encountered a use-case we'd love to discuss over here. We're proposing a new header that could be useful for registries that are behind proxies. Those proxies usually buffer requests so for big layers it degrades performance and memory usage of the server. It would be nice if the registry, either on upload creation (`POST /v2/:name/blobs/uploads/`) or in another way to hint the client the preferred max chunk size.

For example, I've seen places that document the header `OCI-Chunk-Min-Length`, the purpose is hinting a minimum chunk size for clients. It would be amazing to see the counter-part `OCI-Chunk-Max-Length`.

Is it something interesting to see in https://distribution.github.io/distribution/spec/api/? 

I feel like this would be incredibly useful for registries that have limited resources.

**Comment by thaJeztah** [comment]
That website is related to the distribution repository, which is separate from the code in this repository (but we use some packages from it as build-time dependency); https://distribution.github.io/distribution/

However, the API specs documented on that site predate the OCI distribution specification (its the API spec before it was donated to the OCI); to have such a header added, it would have to be accepted by the OCI distribution spec maintainers, after which it can be implemented by registry clients.

I'm closing this ticket as it looks to be not directly actionable in this repository, but you can open a proposal in the OCI distribution spec; https://github.com/opencontainers/distribution-spec/

**Comment by gabivlj** [comment]
Thank you very much @thaJeztah for the guidance! Opened the issue there.
