### ISSUE TITLE
I removed images and containers and still 10gb file size used somewhere

### ISSUE THREAD

**Issue by kangarooo** [moby/moby#46753]
### Description

I removed images and containers and still 10gb file size used somewhere. I did Troubleshoot -> Clean/ purge and that gave 10gb free space back.

### Reproduce

Make images and containers and they use 10gb space
Remove them and space still is used

### Expected behavior

Remove files and give back free space or ask if i want to keep files

### docker version

```bash
Todays
```

### docker info

```bash
Todays
```

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by thaJeztah** [comment]
closing as this went stale
