### ISSUE TITLE
convert to go modules (go.mod/go.sum)

### ISSUE THREAD

**Issue by williamh** [moby/moby#46761]
### Description

Currently, this repo has vendor.mod/vendor.sum which look like they could be go.mod/go.sum.
However, I find the following comment in vendor.mod.

```
// 'vendor.mod' enables use of 'go mod vendor' to managed 'vendor/' directory.
// There is no 'go.mod' file, as that would imply opting in for all the rules
// around SemVer, which this repo cannot abide by as it uses CalVer.
```

Can you comment on what CalVer is, and whether I can treat vendor.mod/sum as go.mod/sum  when I build this repo?
Also, I am curious about your plans. Are you planning to move to go.mod/go.sum in this repo?
Making this move or being able to treat vendor.mod/sum as go.mod/sum down stream would make downstream building much easier.

Thanks for your time.

William

### Reproduce

n/a

### Expected behavior

Using go modules is the simplest way to build go programs these days.

### docker version

```bash
n/a
```

### docker info

```bash
n/a
```

**Comment by neersighted** [comment]
This appears to be something of a frequent question; but the answer in short is that we are not a Go module, and we are not compatible (directly) with Go modules.

The project must be built in GOPATH mode; the `vendor.mod` file is merely an artifact of the tooling we use to generate the `vendor/` folder, but should not be taken to be more. We are working to transition to a Go module (and I'm bugging @thaJeztah to open a tracking issue), but are not there yet, and until then will require GOPATH mode and be `+incompatible` in our Go module versions.

https://github.com/moby/moby/issues/44618 has more background on this, but the long and short of it is that building with a `go.mod` present changes the semantics of the Go toolchain, and we don't test or support that upstream. It may be possible to get correct results, but that is at your own risk/requires you to make the effort to ensure that.

**Comment by neersighted** [comment]
Also, with regard to `CalVer`, that comment is no longer accurate; we have transitioned (back!!!) to SemVer as part of our Go module transition. I've opened https://github.com/moby/moby/pull/46772 to address this (and help answer this question) among other things.

**Comment by williamh** [comment]
Cool. I think a tracker for your module migration would be beneficial.
I don't know how much longer gopath mode is going to be a thing; go upstream seems to strongly discourage using it at this point.

**Comment by neersighted** [comment]
Removing GOPATH mode will break the Go 1.x compatibility promise; however, the language version will be frozen in GOPATH mode, so we are on something of a timer as it's inevitable that vendored code will require future language versions.

**Comment by stevenh** [comment]
The above PR documents the why but doesn't appear to address the ask for this issue, which is to support go modules.

Should this be re-opened or another issue created to track the progress towards being go module compatible?
