### ISSUE TITLE
Docker run `--env-file` argument preserves quotations

### ISSUE THREAD

**Issue by ajhenry** [moby/moby#46773]
### Description

This seems like _undocumented_ behavior of using env files with `docker run`.

In most programs (won't say all because I'm not 100% sure), when env files are used, quotation marks are excluded: `"` and `'`. In Docker, they are _preserved_.

Expected behavior, which matches bash/sh.

```bash
$ export PRIVATE_KEY="This should be altered"
$ echo PRIVATE_KEY
This should be altered
```

Docker would output the following however

```txt
"This should be altered"
```

### Reproduce

`.env` file

```env
PRIVATE_KEY="This should not be altered"
```

`index.js` file

```js
console.log(process.env.PRIVATE_KEY);
console.log(process.env.PRIVATE_KEY.includes('"'));
```

`Dockerfile` file

```dockerfile
FROM node:18-alpine

COPY index.js .

CMD ["node", "index.js"]
```

When running the following:

```bash
docker build -t test .
docker run --env-file=.env test
```

```
[+] Building 0.6s (7/7) FINISHED                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 36B                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                          0.4s
 => [internal] load build context                                                                                                                          0.1s
 => => transferring context: 29B                                                                                                                           0.0s
 => [1/2] FROM docker.io/library/node:18-alpine@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d                                    0.0s
 => CACHED [2/2] COPY index.js .                                                                                                                           0.0s
 => exporting to image                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                    0.0s
 => => writing image sha256:23b54fa60b8c9f7134b7111c1fa76939ec725dcc13b1ff1b48cf63cc091e2678                                                               0.0s
 => => naming to docker.io/library/test                                                                                                                    0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
"This should not be altered"
true
```

### Expected behavior

We expect the string to output `false`

### docker version

Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 42
  Running: 0
  Paused: 0
  Stopped: 42
 Images: 67
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: S4ZX:RHV2:MRKC:OUGX:VONR:3IV5:4N3D:LCQC:VKV7:BPZS:QV4U:YUHG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8

### Additional Info

While changing this would be a breaking change, there should be some notes about it in the [documentation](https://docs.docker.com/engine/reference/commandline/run/#env).

I can make this change if this is the confirmed behavior, thanks!

**Comment by Sanjib8830** [comment]
The behavior you are observing is due to how environment variables work in Docker. When you use the --env-file option in docker run, it reads the environment variables from the file and sets them inside the Docker container. However, it does not export these variables to the current shell session.

In your case, you have an .env file with PRIVATE_KEY="This should not be altered". When you run the Docker container with docker run --env-file=.env test, the PRIVATE_KEY environment variable inside the container is set to "This should not be altered". This value is then accessible to your Node.js application inside the container.

When you print process.env.PRIVATE_KEY.includes('"') in your index.js file, it checks if the PRIVATE_KEY environment variable inside the container contains a double quote ("). Since the value of PRIVATE_KEY inside the container is "This should not be altered", the condition process.env.PRIVATE_KEY.includes('"') evaluates to true, and your application outputs true.

If you want the behavior to match the bash/sh behavior and output false, you would need to modify your Dockerfile to export the environment variable to the shell session:

FROM node:18-alpine

COPY index.js .

ENV PRIVATE_KEY="This should not be altered"

CMD ["node", "index.js"]

By adding ENV you can export env. variable inside the container. The result should be false

**Comment by sam-thibault** [comment]
I will close this as a duplicate of:
-  https://github.com/docker/cli/issues/3630

**Comment by chyzwar** [comment]
This is inconsistent with how env variable are parsed in docker-compose https://docs.docker.com/reference/compose-file/services/#env_file-format and general expectation about how this should work. 

If I have .env
```
DB_HOST="my.host.com"
```

Then in inside container 
I should have `process.env.DB_HOST === "my.host.com" `but currently it is `'"my.host.com"'`

Most importantly, it is not documented in https://docs.docker.com/reference/cli/docker/container/run/#env 
First result in google points to docker-compose documentation that is misleading people.
