### ISSUE TITLE
Failed to docker image build on OpenWRT, CPU MIPS32

### ISSUE THREAD

**Issue by cppcoffee** [moby/moby#46824]
### Description

I use golang build a hellomips bin program without any dynamic link library, can run it on MT7621(MIPS32) OpenWRT 22.03.4.

```shell
# ./hellomips
hello mips

# ldd hellomips
ldd: hellomips: Not a valid dynamic program
```

Create Dockerfile, it's content as follow:

```
FROM scratch
ADD ./hellomips /
CMD ["/hellomips"]
```

Compile the dockerfile into an image:

```shell
# docker build -t hello .
Sending build context to Docker daemon  5.581MB
Step 1/3 : FROM scratch
 --->
Step 2/3 : ADD ./hellomips /
 ---> a7731a3615e0
Step 3/3 : CMD ["/hellomips"]
operation not supported
```

Build failed.

Why does an error occur when executing the `step 3/3 CMD`?

### Reproduce

docker build --tag hello .

### Expected behavior

Build out the mirror image

### docker version

```bash
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        3a2c30b
 Built:             Thu Nov 16 09:29:00 2023
 OS/Arch:           linux/mipsle
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       42c8b31
  Built:            Sun Apr  9 12:27:46 2023
  OS/Arch:          linux/mipsle
  Experimental:     false
 containerd:
  Version:          1.6.13
  GitCommit:
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.15.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.22
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version: de40ad0
 Security Options:
  cgroupns
 Kernel Version: 5.10.176
 Operating System: OpenWrt 22.03.4
 OSType: linux
 Architecture: mips
 CPUs: 4
 Total Memory: 244.1MiB
 Name: IoT_board_F14E
 ID: 4IVZ:RT6E:FHMO:BSV7:PJZI:LJ47:QIGJ:P4PX:7RVA:5MJB:PLHU:4ZFH
 Docker Root Dir: /opt/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Thanks for reporting; we currently don't verify/test mips32 architectures, so I expect the build of docker you're running is provided by the OpenWRT maintainers/packagers. It's also worth mentioning that 20.10 is quite an old version; the release branch is still maintained by Mirantis for their runtime, but will fully reach EOL soon, so if possible, I'd recommend a more current version.

Does this issue reproduce with any Dockerfile, or only for this specific one? Does the `hellomips` have any extended attributes set? What filesystem is used on your system?

Wondering if it could be some permutation of these issues;

- https://github.com/moby/moby/issues/45417
- https://github.com/moby/moby/pull/45420
- https://github.com/moby/moby/pull/45464

In either case, it would be best to report this issue to the openwrt maintainers (or the packagers of the docker package you're running).

It's also worth checking if the "check-config" script shows anything that may provide information on things possibly missing; https://github.com/moby/moby/blob/master/contrib/check-config.sh

**Comment by cppcoffee** [comment]
Oh, It missing `fuse-overlayfs_1.7.1-1_mipsel_24kc.ipk` and `kmod-fuse_5.10.176-1_mipsel_24kc.ipk` packages, causing the error.

Solved after installation.
