### ISSUE TITLE
Docker Daemon consuming extremely high memory on the host. 800+GB

### ISSUE THREAD

**Issue by Vatsaldhar26** [moby/moby#46836]
### Description

We have a kubernetes cluster running docker as container runtime and cri-dockerd to let kubernetes controle docker via CRI.
Part of this cluster we have two machines,

Machine 1 - 128CPUs and 1TB RAM
Machine 2 - 128CPUs and 128GB RAM

Kubernetes - v1.26.1
cri-dockerd -  0.3.0
Kernel Version: 5.19.0-38-generic
Operating System: Ubuntu 22.04.1 LTS

Lately we are seeing scenarios, where when pods are running (20-30+) on the above hosts, after sometime the docker daemon starts consuming memory, untill OOM killed. On below attached picture, it took close 800GB memory on number of occasions.
![image](https://github.com/moby/moby/assets/35141195/cd69452d-2d07-49a7-a621-0b63e83f03e0)

### Reproduce

Only gets reproduced with specific set of pods being run

### Expected behavior

dockerd shouldn't consume all the memory available on the host

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:45:08 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:42:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 nvidia:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.10.0-docker)
  compose: Docker Compose (Docker Inc., v2.15.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 125
  Running: 37
  Paused: 0
  Stopped: 88
 Images: 744
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-38-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 128
 Total Memory: 1008GiB
 Name: hostname
 ID: some-id
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 245
  Goroutines: 195
  System Time: 2023-11-21T11:31:18.880900685Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting. We'll probably need more information to triage this issue.

> Lately we are seeing scenarios, where when pods are running (20-30+) on the above hosts, after sometime the docker daemon starts consuming memory, untill OOM killed.

Do you have more information what led to this issue?

- Was this an existing installation, and was this setup working before?
- If it was an existing installation, did anything change that could lead to this issue / coincide with this issue starting to appear? Considering;
   - Updates to your distro
   - Kernel version updates
   - Updates of docker or containerd
   - Updates in kubernetes, or other tooling that may interact with the docker engine (monitoring, log-aggregating)
   - Changes in workloads deployed
- Do daemon- or system-logs show anything that could be of interest?

Note that docker no longer maintains version 20.10 (we only maintain the current release, which is 24.0.x at time of writing), but commercially supported versions of 20.10 are available through Mirantis (as their Mirantis Container Runtime). If you have a test-environment in which you can reproduce the issue, it may be worth trying with a current release.

I also notice that you're running an outdated versions of `containerd` and `runc` (1.6.15/1.1.4; current patch releases are 1.6.25 and 1.1.10). I would recommend updating to current patch releases of those (also if you're unable to update to a more recent version of the engine itself).

**Comment by thaJeztah** [comment]
closing as this went stale
