### ISSUE TITLE
c8d: unconditionally use ref-counting, or get info from snapshotter

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#46842]
### Description

- relates to https://github.com/moby/moby/pull/45698
- relates to https://github.com/moby/moby/pull/45781
- relates to https://github.com/moby/moby/pull/45781#discussion_r1235917043
- slightly related to https://github.com/moby/moby/issues/46757

Commit https://github.com/moby/moby/commit/21c0a54a6b2dc059fae62f46a23d338a35fe6d1d (https://github.com/moby/moby/pull/45698) introduced a hard-coded list of snapshotters (`refCountedFileSystems`) that we know need reference-counting. With containerd, the list of available snapshotters is not known (additional snapshotters may be installed on the system), so maintaining a hard-coded list is problematic to maintain.

https://github.com/moby/moby/blob/54fcd40aa4de94cd75aedc5f6ebf38c6d8f92082/daemon/snapshotter/mount.go#L15-L16

We should consider to either;

- unconditionally use reference-counting (as suggested in https://github.com/moby/moby/pull/45781#discussion_r1236612727)
- get this information from the snapshotter (also related: https://github.com/moby/moby/issues/46757)
- :point_up: this may depend on containerd 2.0 though, so perhaps we need to go for the alternative in the meantime

**Comment by vvoland** [comment]
Done with https://github.com/moby/moby/pull/47105
