### ISSUE TITLE
Inconsistent behavior for logs timestamps timezone depending on logging driver used

### ISSUE THREAD

**Issue by RomanValov** [moby/moby#46910]
### Description

Please check [this SO answer](https://stackoverflow.com/a/77626300/265374) for details.

When I use `local` log-driver timestamps in logs are aligned to local timezone.
When I use `json-file` log-driver timestamps in logs are aligned to UTC timezone.

### Reproduce

json-file:

```
docker run --log-driver json-file --name json-file-test ...
docker logs --timestamps json-file-test
```

local:

```
docker run --log-driver local --name local-test ...
docker logs --timestamps local-test
```

### Expected behavior

Container logs should use same timezone irrespective to log driver used.
Or there should be an option to switch between local and utc.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 1
  Paused: 0
  Stopped: 11
 Images: 104
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.591GiB
 Name: chiaseed
 ID: 5411a4b6-0697-4058-8559-d645ead34a3c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Oh, interesting! Yes, I don't think that's correct. Wondering if that was intentional, or an oversight (as well as "where" the timezone is applied)

FWIW, the general design for logging has been to always use UTC (which allows aggregating logs from multiple machines, and make sure events align), but there has been discussion about providing a way to _present_ logs in a different timezone (which could be the local timezone of the CLI); see


- https://github.com/moby/moby/issues/33778
- https://github.com/moby/moby/pull/35051#issuecomment-334117784
- https://github.com/docker/cli/issues/604

(I see you found that last one 😅- not sure why it was closed though 🤔)

**Comment by RomanValov** [comment]
@thaJeztah thank for almost immediate feedback and summary of related topics.
IMHO the best way to track timezones is at presentation level (docker logs) command and utc/local switch should be sufficient + TZ env variable handling (at least on Linuxes) give all the flexibility.

As per my quick dig into sources the point where local timezone arises is:

https://github.com/moby/moby/blob/659e7b52df07d3854b23af3de7d59b09b94fe4b6/daemon/logger/local/local.go#L190C13-L190C13

```
		Timestamp: time.Unix(0, proto.TimeNano),
```

According to docs, this function returns local time.

**Comment by cpuguy83** [comment]
Definitely an oversight 😞
In fact we've explicitly rejected requests to make json-file not UTC, IIRC.

**Comment by RomanValov** [comment]
> Are you interested in contributing that fix? (I can make the change, but don't want to take away your moment of fame; you both reported the issue, AND, found the likely offending line ❤️)

Oh, well. It's okay to lose some fame for me and it's okay for me to end up only as an author of this issue :)
Hence I would avoid doing the changes and testing and getting into all the contributing process due to shortage of time

**Comment by thaJeztah** [comment]
No worries! Let me open a quick PR for this 👍
