### ISSUE TITLE
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Odonno** [moby/moby#47043]
I have this error for days now and I really don't know what to do... It happens when I do any of the following commands:

```
docker pull nginx
```
or even
```
docker login
```

I am running the following docker version on Windows 11 (no network specificity, no proxy, no fancy firewall)

```
Client:
 Version:           24.0.6-rd
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.7
 Git commit:        da4c87c
 Built:             Wed Sep  6 16:41:58 2023
 OS/Arch:           windows/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Thu Oct 12 14:14:03 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19
```

Can anyone help me?

**Comment by thaJeztah** [comment]
This looks like a general networking issue, but there's not a lot of information in this ticket;

- `24.0.6-rd` doesn't look like a standard version; what method did you use to install docker; is that a binary you built yourself?
- The CLI's commit also doesn't appear to exist in the CLI source repository (https://github.com/docker/cli/commit/da4c87c), but perhaps it's too short
- Same question for the daemon; what method did you use to install the daemon; if this is a distro-provided package, do you see the same problem with docker's packages (https://docs.docker.com/engine/install/)?
- What distro are you running on? Can you also provide the output of `docker info` ?
- Is the daemon running locally, or on a remote machine?
- I see the CLI is on Windows, and the daemon on Linux; is this on WSL2? (If so, do you get the same problem when using Docker Desktop?)

**Comment by thaJeztah** [comment]
Looks like you also posted this in https://github.com/docker/cli/issues/4761, and from that I see this is likely part of Rancher Desktop; have you reported an issue in their issue tracker?

**Comment by Odonno** [comment]
Well, well. I just retried and it works now... I spent 2 evenings finding a solution to this problem and I still don't know what happened.

Thank you anyway and sorry for the inconvenience.
