### ISSUE TITLE
Potential goroutine blocking in splunk.go due to misusing condition variable

### ISSUE THREAD

**Issue by xuxiaofan1203** [moby/moby#47077]
### Description

I was wondering if a situation may result in blocking of the Wait() in 
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk.go#L553
the signal function is in 
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk.go#L408
the function worker() try to call the Signal() to awaken the Wait(), but if case<- timer.C executes, the Signal() will not execute, and Wait() will blocking.
I'm not sure about it, but I have tried to describe it carefully.

### Reproduce

Like the test file in
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk_test.go#L466
the Close will be called in 
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk_test.go#L522
and the Wait is called
when call the function New() in
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk_test.go#L486
an the function New() call goroutine worker() in 
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk.go#L408
the function worker() try to call the Signal() to awaken the Wait(), but if case<- timer.C executes, the Signal() will not execute, and Wait() will blocking.

### docker version

```bash
Go version:1.16.15
```

### docker info

```bash
Go version:1.16.15
```

**Comment by corhere** [comment]
Not a bug.
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk.go#L551-L554
https://github.com/moby/moby/blob/608238ead6263b60c073a51a2195360888cdd138/daemon/logger/splunk/splunk.go#L411-L422

The `close(l.stream)` will wake up the worker goroutine. There is no deadlock.
