### ISSUE TITLE
Image list filtering behaves differently when containerd-snapshotter is used

### ISSUE THREAD

**Issue by ceache** [moby/moby#47133]
### Description

When using the containerd snapshotter, image search does not function properly. You cannot search images by name (without tag).

Using dockerd v24.0.7

### Reproduce

With an empty (default) dockerd config
``` shell
$ docker pull busybox:1.36.1-musl
[...]

$ docker image ls
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   59888ccc9e65   2 days ago   1.45MB

$ docker image ls busybox
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   59888ccc9e65   2 days ago   1.45MB

$ docker image ls busybox:1.36.1-musl
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   59888ccc9e65   2 days ago   1.45MB
```

Enable the containerd snapshotter with
``` json
{
  "features": {
    "containerd-snapshotter": true
  }
}
```
``` shell
$ docker pull busybox:1.36.1-musl
[...]

$ docker image ls
REPOSITORY   TAG           IMAGE ID       CREATED         SIZE
busybox      1.36.1-musl   630d0615440a   6 minutes ago   2.44MB

$ docker image ls busybox
REPOSITORY   TAG           IMAGE ID       CREATED         SIZE

$ docker image ls busybox:1.36.1-musl
REPOSITORY   TAG           IMAGE ID       CREATED         SIZE
busybox      1.36.1-musl   630d0615440a   6 minutes ago   2.44MB
```

### Expected behavior

`docker image ls <image_name>` should return all tags for that image

### docker version

```bash
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          v24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.6
  Git commit:       311b9ff0aa93aa55880e1e5f8871c4fb69583426
  Built:            Fri Jan 19 20:46:21 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: v24.0.7
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+b1
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-15-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.753GiB
 Name: bookworm
 ID: e432cf75-f542-4c5c-99a2-7c5fc146ce5c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by rumpl** [comment]
This is fixed in `25.0.0` (released yesterday):

```console
/ # docker info
Client:
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 25.0.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 71909c1814c544ac47ab91d2e8b84718e517bb99
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Alpine Linux v3.19 (containerized)
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.657GiB
 Name: 88236ac3ee3a
 ID: 16cfc59d-858f-4ff6-b755-34417e26a69b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

```console
/ # docker pull busybox:1.36.1-musl
1.36.1-musl: Pulling from library/busybox
d997961b9429: Download complete
Digest: sha256:630d0615440a82f995e20570e0b6882dc1d4a578cd4c291b1988a5bec77cff4f
Status: Downloaded newer image for busybox:1.36.1-musl
docker.io/library/busybox:1.36.1-musl
```

```console
/ # docker image ls
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   630d0615440a   2 days ago   2.66MB
```

```console
/ # docker image ls busybox
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   630d0615440a   2 days ago   2.66MB
```

```console
/ # docker image ls busybox:1.36.1-musl
REPOSITORY   TAG           IMAGE ID       CREATED      SIZE
busybox      1.36.1-musl   630d0615440a   2 days ago   2.66MB
```

**Comment by thaJeztah** [comment]
Thanks for reporting, and for using the containerd integration!

Yup, this looks to be working correctly now with v25.0;

```console
$ docker pull busybox
$ docker tag busybox myimage:latest
$ ocker tag busybox myimage:one
$ docker tag busybox myimage:two
```

```console
$ docker image ls myimage
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
myimage      latest    3d3698b745b0   2 days ago   6.09MB
myimage      one       3d3698b745b0   2 days ago   6.09MB
myimage      two       3d3698b745b0   2 days ago   6.09MB
```

```console
$ docker image ls myimage:one
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
myimage      one       3d3698b745b0   2 days ago   6.09MB
```

```console
$ docker image ls myimage:on
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
```

```console
$ docker image ls 'myimage:on*'
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
myimage      one       3d3698b745b0   2 days ago   6.09MB
```

```console
$ docker image ls 'myim*:on*'
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
myimage      one       3d3698b745b0   2 days ago   6.09MB
```

```console
$ docker image ls 'myim*'
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
myimage      latest    3d3698b745b0   2 days ago   6.09MB
myimage      one       3d3698b745b0   2 days ago   6.09MB
myimage      two       3d3698b745b0   2 days ago   6.09MB
```

Let me go ahead and close this ticket, but feel free to continue the conversation, and thanks again for reporting (it's appreciated!)

**Comment by ceache** [comment]
Is there a chance to see this backported to the v24 branch?

I am having some issue with my local S3 backed registry with v25 (which I am trying to get to the bottom of, but would be a separate issue)

thanks!

**Comment by thaJeztah** [comment]
No we're not planning to backport this to v24, but interested to hear about the issues you're seeing with the 25 release, if you have more details!

**Comment by ceache** [comment]
All I can say for now is regular remote https registry works fine for me.
Using a registry deployed on loopback ( 127.0.0.1) backed by AWS s3 does
not.

Thanks, I'll open a new issue for this one once I have a reproducible case

**Comment by ceache** [comment]
> No we're not planning to backport this to v24, but interested to hear about the issues you're seeing with the 25 release, if you have more details!

I managed to get v25 to work (see #47240) only to be hit with the fact that v25 raises the minimum client API version past what I unfortunately still need to support. So I'll need to stick to the v24 branch, at least for a while. v24.0.8 is still affected.

I tried to figure out the commit(s) that fixed this issue between v24 and v25 without real success. Would you be able to tell me what fixed this issue as, if it is not going to be officially backported, I may need to patch a v24 locally.

Thanks

**Comment by thaJeztah** [comment]
For the 25 release, you can configure a lower minimum API version through the `DOCKER_MIN_API_VERSION` env-var (env-var must be set in the daemon's environment); https://docs.docker.com/engine/deprecated/#deprecate-legacy-api-versions

But this option will no longer be available for v26, so I would highly recommend updating clients that don't support newer API versions (the API versions that are being deprecated are 7 Years old, so if the client doesn't support that, it may not have been maintained for 7 years 😬)

**Comment by ceache** [comment]
Thanks, that is great news!
I'll try that out. And yes, trust me I know about the old API client...
Thanks for the help!

**Comment by thaJeztah** [comment]
> And yes, trust me I know about the old API client...

No worries! I'm definitely familiar with situations where the world "isn't perfect".

I'm (of course) not familiar with your situation, and don't know what amount of control you have over the client, but in case it helps; if the client you're working with uses the Go client from this repository, and if it's configured with the `FromEnv` option, then you _MIGHT_ be able to go the other way round, and use the `DOCKER_API_VERSION` variable to make the client use a different API version (e.g. `DOCKER_API_VERSION=1.24`) https://github.com/moby/moby/blob/968f05910aca7550307957eb231438d13c22730d/client/envvars.go#L12-L21


:warning: this is really a _hack_ as using that env-var makes the client use whatever version of the API you set, including API versions it actually doesn't support (in this case a newer API version than it can use!). However, many (most) parts of newer API versions are "additive"; new options were added in addition to the existing options. Depending on your use-case, it's possible that the client may only be using a small set of the features in the API, and those parts of the API not having changed in newer API versions.

Taking that into account (and knowing the risks), it could be an escape hatch for your use-case until you're able to upgrade the client, and the advantage would be that you're not "locked in" to Engine v25.0, and still able to upgrade to Engine v26.0 and later once released.
