### ISSUE TITLE
Pulling from insecure registry failed when docker build

### ISSUE THREAD

**Issue by woshikid** [moby/moby#47212]
### Description

I have a local insecure registry listen on port 80. And I added the `--insecure-registry=192.168.1.100` argument.
When I do `docker pull 192.168.1.100/my/image` it works fine.
But when I used this image in Dockerfile: `FROM 192.168.1.100/my/image` and run docker build, it fails with
```
ERROR: failed to solve: 192.168.1.100/my/image: failed to do request: Head "https://192.168.1.100/v2/my/image/manifests/latest": dial tcp 192.168.1.100:443: connect: connection refused
```
the error message said it tried to use https instead of http. 

After more tests I found if I change the address to `--insecure-registry=192.168.1.100:80`  the both `docker pull 192.168.1.100:80/my/image` and `docker build` of `FROM 192.168.1.100:80/my/image` works fine.

Maybe there is a bug when no port is specified.

### Reproduce

1. make an insecure registry listen on port 80.
2. docker pull works fine.
3. docker build failed trying to connect to port 443.

### docker version

```bash
Client:
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:10:34 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.12
  GitCommit:        71909c1814c544ac47ab91d2e8b84718e517bb99
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 71909c1814c544ac47ab91d2e8b84718e517bb99
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Alpine Linux v3.19 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.44GiB
 Name: builder
 ID: 83698aaf-14ce-4731-94f7-fcf8676b01b8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  192.168.1.100:80
  192.168.1.100
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by woshikid** [comment]
Thanks, @thaJeztah 

I know that if there's no `.` (or a` :port`) in the hostname, it causes ambiguity. 
But for hostname with `.`  (or IP in my case), `docker pull` respect `--insecure-registry` settings but `docker build` does not.
In older versions, I can overcome this by adding `http://` prefix like `--insecure-registry=http://192.168.1.100`, it'll lead the buildkit to use http on registry `192.168.1.100`. But now it's not working anymore.

Is there any other way to hint docker to use http not https even though I've told it the registry is insecure?

**Comment by woshikid** [comment]
I just found https://github.com/docker/buildx/issues/2030
It seems that the bug is supposed to be fixed in 25.0 but still exists.

**Comment by zijin520** [comment]
I have saw serveral reports for this issue. Any plan to fix it?

**Comment by woshikid** [comment]
Seems to be fixed since v27 on Docker linux and docker-in-docker image.
But the Docker Desktop for Windows v27.1.1 still have this issue.
Hope it will be fix soon as other versions.
