### ISSUE TITLE
`docker import image.tar` (and other variants) fails to create usable images

### ISSUE THREAD

**Issue by autumnjolitz** [moby/moby#47235]
### Description

Given a `docker save my-image > image.tar`, one expects a `docker import image.tar my-image-2` will result in an identical image tagged as `my-image-2`

It does not as of `Docker version 24.0.7, build afdd53b` (`docker --version`)

```
$ docker inspect my-image:latest |  jq '.[].RootFS.Layers | length'
102
$ docker save my-image:latest > image.tar
$ docker import image.tar my-image-2
sha256:8feb25a4d15f7bcaa481543ad07db2ae604a5c76569f3571c0b7b1fcf987e080
$ docker inspect my-image-2:latest |  jq '.[].RootFS.Layers | length'
1
```

Looking at it with `dive my-image-2:latest` reveals a single layer, of which the contents of the image is identical to the *raw* contents of the `image.tar` (i.e. it did not import, it simply make one layer that's equivalent to a `tar -xf image.tar`)

### Reproduce

1. Create an image with several layers and tag it `my-image:latest`
2. `docker save my-image:latest > image.tar`
3. Check the cardinality of `docker inspect my-image:latest |  jq '.[].RootFS.Layers | length'` to see if it matches the number of layers
4. `docker import image.tar my-image-2:latest`
5. Check the cardinality of `docker inspect my-image-2:latest |  jq '.[].RootFS.Layers | length'` and see if it matches

### Expected behavior

the cardinality should be identical
the contents of the image should be identical

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/amd64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     /Users/autumn/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /Users/autumn/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/autumn/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/autumn/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     /Users/autumn/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /Users/autumn/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/autumn/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/autumn/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/autumn/.docker/cli-plugins/docker-scout

Server:
 Containers: 91
  Running: 1
  Paused: 0
  Stopped: 90
 Images: 335
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge ghcr.io/devplayer0/docker-net-dhcp:release-linux-amd64 host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 9.72GiB
 Name: docker-desktop
 ID: eb795cb4-6238-42e9-9c4d-1e58c8404f6f
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 58
  Goroutines: 85
  System Time: 2024-01-26T21:30:54.35185484Z
  EventsListeners: 11
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
`docker save` is the counterpart to `docker load`, not `docker import`. Does it work if you use `docker load` ?

**Comment by autumnjolitz** [comment]
I stand corrected. However, due to `docker import` working much like this person describes (https://stackoverflow.com/a/72352470), I was misled to believe that that was intended behavior:

> I want to share another difference from real world situation using docker save and on prod servers using docker import vs docker load.
> 
> On the server with internet access docker import worked the same way as docker load. Container was up and running without error and missing layers have been downloaded over internet.
>
> On the server without internet - on-prem setup docker import cause above error on container start e.g.
>
>> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: "/bin/bash": stat /bin/bash: no such file or directory": unknown.
>
> In order to get saved container up and running without that we need to use docker load < saved-container.tgz In that way all the layers are imported.

A more careful read of the current documentation shows there is a difference between `docker load` and `docker import`.

I cannot explain how or why `import` behaved like `load` in the past nor can I isolate when this behavior changed.

The code that did the `import` (instead of `load`) dates from early 2022.

In any case, I think there should be an addition to the documents to outline pitfall that others may have stepped into.
