### ISSUE TITLE
User namespace remap broken in Docker 24 (UID not applied to created files, only GID)

### ISSUE THREAD

**Issue by belotv** [moby/moby#47238]
### Description

UID is not applied on created files, they belong to root instead.

Tested on PhotonOS 5.0, but seems that issue has been observed on Ubuntu by other people too (https://stackoverflow.com/questions/77533753/docker-with-userns-remap-still-writes-into-volumes-as-root)

### Reproduce

1. groupadd -g 2003 dockmap
2. useradd -u 2003 -g dockmap -s /bin/false dockmap
Make sure that /etc/docker/daemon.json contains only "{ "userns-remap": "2003:2003" }"
Make sure that /etc/subuid and /etc/subgid both contain only  "dockmap:165536:65536"
3. Start docker
4. check permissions of /var/lib/docker with ls -al
5. Folders are drwx--x---  3 root 165536 instead of drwx--x---  3 165536 165536

### Expected behavior

New created files should be owned by remap user, not root. Due to this issue, the remap function is not usable.

(in addition, the autocreation of dockremap user/group mentioned in the documentation when using the "default" value has been broken for years according to some reports - but this is minor)

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.12
 Git commit:        ced0996
 Built:             Thu Dec 21 03:06:52 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.12
  Git commit:       a61e2b4
  Built:            Thu Dec 21 03:07:35 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  userns
  cgroupns
 Kernel Version: 6.1.70-2.ph5-esx
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.949GiB
 Name: photon-machine
 ID: 555f6176-6d31-446f-98cf-474c99d6e7f7
 Docker Root Dir: /var/lib/docker/165536.165536
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by cpuguy83** [comment]
The permissions look to be exactly as intended.
We do not want the remapped user to own files in /var/lib/docker.
We do want to allow members of the remap group to traverse into certain directories because it is necessary for the remapped container to function.

Are you experiencing a particular issue?

**Comment by belotv** [comment]
Indeed my example is not the best. Actually it is not only the directory /var/lib/dockerAny directory/file in that folder is owned by root. This is not aligned with the documentation, where we can see that the subfolders should be owned by the remap user: https://docs.docker.com/engine/security/userns-remap/Main issue is that I am trying to map host cgroup (as requested by freeipa) and it does not work. I am getting permission denied as the files created in /sys/fs/cgroups/xxx.slice are created with root as owner (but correct group).Le 28 janv. 2024 à 21:51, Brian Goff ***@***.***> a écrit :﻿
The permissions look to be exactly as intended.
We do not want the remapped user to own files in /var/lib/docker.
We do want to allow members of the remap group to traverse into certain directories because it is necessary for the remapped container to function.
Are you experiencing a particular issue?

**Comment by cpuguy83** [comment]
Docs are outdated for sure.

What's the exact command you are trying to perform and the error you are seeing?

**Comment by cpuguy83** [comment]
I'm not sure I understand if there are no errors seen what is the issue?

As I mentioned before, this is working as intended.
See  https://github.com/moby/moby/security/advisories/GHSA-7452-xqpj-6rpc

**Comment by belotv** [comment]
Based on the information shared, I guess the issue is mainly that documentation from both docker and freeipa is not very clear and not fully up-to-date.

I was able to make it work by **removing the /sys/fs/cgroup:/sys/fs/cgroup:rw mapping**. Even if it may seems a bit weird, the scope will be properly created under the system.slice and will work as expected.
(I also unset cgroup and cgroup_parent in my Docker compose file, so that it uses the default system.slice).

I guess it is complex to maintain documentation that properly cover docker root/root with namespace remap/rootless, with both cgroupv1 and v2 to handle.

I will close the ticket as it does not seem to be a system function bug.

**Comment by kylhuk** [comment]
@cpuguy83 I was mislead by a non-official guide. Thank you very much for pointing me in the right direction!
