### ISSUE TITLE
Status of swarm and adoption of compose-spec

### ISSUE THREAD

**Issue by sergioisidoro** [moby/moby#47241]
### Description

I have recently noticed some discrepancies between docker compose and docker swarm specification. The most recent being the `content` element of the `config` schema of the docker compose specification. -- https://github.com/docker/compose/issues/3538 and https://github.com/compose-spec/compose-spec/issues/346#issuecomment-1826282162

After digging a bit, I have seen some reports that the specs of docker swarm stack files, and the docker compose spec are significantly diverging. There are issues and discussions on the docker org projects, but it seems docker is no longer maintaining swarm, so these discussion are not going anywhere in those repos -- https://github.com/docker/cli/issues/2527. 

There are also some reports that docker swarm no longer has an active maintainer -- https://github.com/docker/cli/issues/2527#issuecomment-1836824601 

I'm opening this issue in an attempt to bring some clarity to the situation, understanding the status of docker swarm development, and the status of implementation of the compose spec in the project.

**Comment by corhere** [comment]
Cc @dperny

**Comment by corhere** [comment]
Swarm is actively maintained by Mirantis, with @dperny as lead maintainer. Implementation of the compose spec is on our backlog. If you are a Mirantis customer, please reach out to your support representative. It would really help us out in getting the work prioritized.

**Comment by trajano** [comment]
I think you should really move the issues to a new board for `docker swarm`, `docker stack`, `docker service` related items rather than mixing it up here.
