### ISSUE TITLE
dockerd start so slowly when running an unmanaged network plugin in a container

### ISSUE THREAD

**Issue by btkinghome** [moby/moby#47289]
### Description

docker version:  Docker version 24.0.6, build ed223bc

docker info:
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false

Server:
 Containers: 74
  Running: 74
  Paused: 0
  Stopped: 0
 Images: 76
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge cilium host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fe457eb99ac0e27b3ce638175ef8e68a7d2bc373
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.19.90-0.231008.openeuler.x86_64
 Operating System: openEuler 20.03 (LTS-SP3)
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 250.1GiB
 Name: node-192-168-30-231
 ID: cfc36132-0b78-47c9-b935-c393c976685d
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.nju.edu.cn/
  https://kuamavit.mirror.aliyuncs.com/
 Live Restore Enabled: true
 Product License: Community Engine

-----------------------------------------------------------
1、we use the cilium docker plugin
2、we created the custom network
3、we created  50+ containers use the custom network
4、when we reboot the  OS，the dockerd start so slowly

Log：

Feb 01 13:43:55 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:43:55.475163958+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint a5941c4b0420e232d6642c563e7dbd9bcc2d304af22707cd699904c37a0fa6e5 fbbca8d8ca7ebc8692995708c549e09951fa9faa22d8b9d92852fcb4fce356d9], retrying...."
Feb 01 13:43:55 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:43:55.513821328+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 1s"
Feb 01 13:43:56 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:43:56.514206620+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 2s"
Feb 01 13:43:58 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:43:58.515541724+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 4s"
Feb 01 13:44:02 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:02.518891813+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 8s"
Feb 01 13:44:10 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:10.519296515+08:00" level=warning msg="Failed to retrieve ipam driver to release interface address on delete of endpoint 1-datanode-3 (fbbca8d8ca7ebc8692995708c549e09951fa9faa22d8b9d92852fcb4fce356d9): plugin \"cilium\" not found"
Feb 01 13:44:10 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:10.613863026+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint a5941c4b0420e232d6642c563e7dbd9bcc2d304af22707cd699904c37a0fa6e5 1f88ba946f00986eb1560638706ac672da4f3e19c7f5a1101a4edcbfa6a8dc37], retrying...."
Feb 01 13:44:10 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:10.651071245+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 1s"
Feb 01 13:44:11 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:11.651420424+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 2s"
Feb 01 13:44:13 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:13.652727061+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 4s"
Feb 01 13:44:17 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:17.656083476+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 8s"
Feb 01 13:44:25 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:25.659216124+08:00" level=warning msg="Failed to retrieve ipam driver to release interface address on delete of endpoint 1-namenode-1-agent (1f88ba946f00986eb1560638706ac672da4f3e19c7f5a1101a4edcbfa6a8dc37): plugin \"cilium\" not found"
Feb 01 13:44:25 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:25.809615272+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint a5941c4b0420e232d6642c563e7dbd9bcc2d304af22707cd699904c37a0fa6e5 b231d0e635d9b414903feecb64fe9602f1fba44b227b7386b2c26d8be5dff54e], retrying...."
Feb 01 13:44:25 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:25.848463016+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 1s"
Feb 01 13:44:26 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:26.848821820+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 2s"
Feb 01 13:44:28 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:28.850210127+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 4s"
Feb 01 13:44:32 ailpha-node-10-50-2-41 dockerd[36792]: time="2024-02-01T13:44:32.851436351+08:00" level=warning msg="Unable to locate plugin: cilium, retrying in 8s"

-----------------------------

Analysis：

<img width="1775" alt="image" src="https://github.com/moby/moby/assets/75957/240f5c5e-b8c7-496d-b744-260e985f24de">

we found  dockerd try to clean localEnpoint  when it  init,  but every clean job  use the  function  plugin.go(libnetwork)  "loadWithRetry(name, true)" , it should cost 15 seconds

so  50 containers  cost about 750 seconds，because our  cilium-docker-plugin is also run as a container，dockerd will return normal when all remove job failed at last。

------------------------------

Suggestion：

When Plugin is not ready，skip  the cleanjob of this  custom network。

**Comment by corhere** [comment]
The Cilium plugin is an ["unmanaged" plugin which the daemon expects to already be running when it starts.](https://docs.docker.com/engine/extend/plugin_api/#plugin-lifecycle) The daemon does not support unmanaged plugins inside regular containers as plugins need to be ready before containers can be started. You could either run the Cilium plugin directly on the host, outside a container (e.g. as a systemd service), or you could ask the Cilium project [to package their plugin as a managed Docker plugin.](https://docs.docker.com/engine/extend/)

On the Moby side, we can't just skip cleaning up endpoints for networks when the plugin is unavailable. Cilium is also an IPAM plugin; it allocates IP addresses to endpoints. IP addresses would leak (be permanently unavailable for assignment to other endpoints/containers) if we simply dropped the endpoints without informing Cilium that the addresses assigned to the endpoints are no longer in use. That being said, we could perhaps make libnetwork smarter about handling networks of drivers that are not available. But that would affect all aspects of the container-network lifecycle, which would be a lot of work to implement.

**Comment by btkinghome** [comment]
Thanks for reply.  yes, i agree with you , I have already try to make cilium docker plugin work as systemd application。 but  i need to point out , my suggestion is not simply clean the endpoint and sandbox，that will destory the ipam  struct，all things will become bad。   I mean maybe  dockerd can decrease  per clean job  failed cost， because in current clean logic，the clean job is also failed at last，and this change will not modify the local-kv.db。 ofcourse  this change  would affect all aspects of the container-network lifecycle, which would be a lot of work to implement.
