### ISSUE TITLE
Make download link for wasm runtime

### ISSUE THREAD

**Issue by Avey777** [moby/moby#47305]
### Description

After turning on the wasm function on the server, I was unable to run any wasm container. This was mainly caused by my inability to compile the sample wasmtime myself and not knowing where to download the corresponding runtime file.

The following two suggestions are put forward for this purpose:
1. Automatically download the runtime when wasm is enabled (non-desktop version)
2. Provide a link to download the wasm runtime binary file in the docker manual

**Comment by corhere** [comment]
> After turning on the wasm function on the server

What do you mean? What are you turning on?

> 1\. Automatically download the runtime when wasm is enabled (non-desktop version)

`dockerd` does not automatically download or install any runtimes, so we can't do that just for your favourite WASM runtime. Installing software is a job best left up to your disto's package manager.

> 2\. Provide a link to download the wasm runtime binary file in the docker manual

https://docs.docker.com/engine/alternative-runtimes/ has a link to https://wasmtime.dev/ which has install instructions above the fold, [and instructions on how to build the shim for it.](https://docs.docker.com/engine/alternative-runtimes/#wasmtime) Please use the "Give feedback" button on docs.docker.com pages or open an issue on https://github.com/docker/docs if you have documentation requests.

**Comment by Avey777** [comment]
refer to:
https://github.com/moby/moby/discussions/46550
