### ISSUE TITLE
[macvlan] Same parent and gateway for multiple networks

### ISSUE THREAD

**Issue by andrewbaxter** [moby/moby#47317]
### Description

I'm remaking this from https://github.com/moby/libnetwork/issues/2384

It's still relevant to me (esp with ipv6 networking) and I'd be happy to try working on it, but wanted to check first if the solution proposed there had any issues.

**Comment by andrewbaxter** [comment]
Some quick questions:

- Is the check there for technical reasons or guidance (preventing people from making common mistakes)?
- I couldn't find any documentation on macvlan, but on source said there can only be one macvlan with passthrough.  I didn't see any other restrictions.  Rather than check `CreatedSlaveLink` maybe it would be better to check if either interface sharing the parent are `passthru`?

**Comment by andrewbaxter** [comment]
I said that I wanted to check first but I figured it'd be better to just go for it than try to come up with some local workaround.  PR #47318

**Comment by thaJeztah** [comment]
Thanks for reporting, and for working on an implementation. I left some comments on your PR, but I'm not an expert in this area, so will ask others to look at your changes (there may be subtle details, as there tend to be when networking is involved, so it's always good to have more eyes!)

**Comment by tabsmann** [comment]
In which version is this fix included?
According to https://github.com/moby/moby/pull/47318 it should be in v27.
In 27.1.1 it's no problem to create multiple macvlans with the same parent, but same gateway still fails with the error "failed to allocate gateway (w.x.y.z): Address already in use"
Thanks

**Comment by teenccu** [comment]
> In which version is this fix included? According to [#47318](https://github.com/moby/moby/pull/47318) it should be in v27. In 27.1.1 it's no problem to create multiple macvlans with the same parent, but same gateway still fails with the error "failed to allocate gateway (w.x.y.z): Address already in use" Thanks

The workaround I did is to use dummy different gateway in the same subnet of the network. Of course if the container wants to access outside network using that gateway then it will fail. However, it was not the case in my situation and I was able to run multiple containers with different macvlan on the same interface.
