### ISSUE TITLE
COPY statement fails on a certain condition, when the destination is a symlink

### ISSUE THREAD

**Issue by casperklein** [moby/moby#47367]
### Description

While migrating base images from Debian 11 to 12, I run into a problem.

```
Dockerfile
rootfs
├── bin
│   └── foo.sh
```

```Dockerfile
FROM debian:11-slim
COPY rootfs /
```

Building an image with the Dockerfile above works fine. Changing `debian:11-slim` to `debian:12-slim` let the build fail:

```
Dockerfile:2
--------------------
   1 |     FROM debian:12-slim
   2 | >>> COPY rootfs /
   3 |
--------------------
ERROR: failed to solve: cannot copy to non-directory: /docker/overlay2/5aowe5jcgl3u60vlsr2ej3vq3/merged/bin
```

I noticed, that in Debian 12 `/bin` is a symlink to `/usr/bin`. I would expect, that copying a file to symlink would behave like directly on the filesystem --> the file is copied to the location the symlink points to.

On the other hand, copying a file to a symlink destination, doesn't seem to be a problem in general, because this works just fine:

```Dockerfile
FROM debian:11-slim
COPY rootfs/bin/foo.sh /bin
```

### Reproduce

See above.

### Expected behavior

The build should success, when copying the content of a directory to a destination involving a symlink.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:25 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: tmpfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-17-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 13.62GiB
 Name: debian12
 ID: 35144c71-4638-4d6b-9275-f7e8ec87a2b0
 Docker Root Dir: /docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I think this may be the expected behavior here, and the classic builder actually had a bug in this area, which would silently replace a symlink with a directory; 

- https://github.com/moby/moby/issues/41035

The `COPY` command in your reproducer copies the contents of the `rootfs` directory to the destination, which means the `bin` _directory_ (and it's content) are copied to the destination. Semantics as mostly similar to [`docker cp`](https://docs.docker.com/engine/reference/commandline/container_cp/), although I think there are some minor differences for backward compatibility (IIRC, it doesn't enforce the trailing slash to be used for `SRC_PATH`).

Comparing this to the "roughly" equivalent in a shell;


Creating a "image" filesystem (which has a symlink), and a `rootfs` directory, which uses a directory;

```bash
mkdir test && cd test

mkdir -p image/usr/bin
touch image/usr/bin/existing-file.txt
ln -s usr/bin image/bin

mkdir -p rootfs/bin
touch rootfs/bin/foo.sh
```

Directory structure should now look like;

```
tree
.
|-- image
|   |-- bin -> usr/bin
|   `-- usr
|       `-- bin
|           `-- existing-file.txt
`-- rootfs
    `-- bin
        `-- foo.sh

6 directories, 3 files
```

Trying to copy the rootfs into the image produces an error, because it cannot overwrite the symlink with a directory;

```bash
cp -r rootfs/bin image/
cp: cannot overwrite non-directory 'image/bin' with directory 'rootfs/bin/'
```
But trying to copy the `foo.sh` to the `bin` symlink does resolve the destination, and copy to it;

```bash
cp rootfs/bin/foo.sh image/bin

tree
.
|-- image
|   |-- bin -> usr/bin
|   `-- usr
|       `-- bin
|           |-- existing-file.txt
|           `-- foo.sh
`-- rootfs
    `-- bin
        `-- foo.sh

7 directories, 3 files
```

**Comment by casperklein** [comment]
Thank you for your explanation and the example! That makes sense 👍

**Comment by thaJeztah** [comment]
You're welcome! And, not gonna lie, symlinks can be "fun" and things can get confusing fast when dealing with them!
