### ISSUE TITLE
i have a error in kali linux

### ISSUE THREAD

**Issue by Karim069** [moby/moby#47401]
### Description

$sudo add-apt-repository ppa:kelebek333/kablosuz
Repository: 'deb https://ppa.launchpadcontent.net/kelebek333/kablosuz/ubuntu/ kali-rolling main'
Description:
PPA for Realtek wifi drivers

If you installed your system in UEFI mode, you must disable secureboot for modules installed by dkms after installation.

You can check installation mode with following command.

[ -d /sys/firmware/efi ] && echo "EFI" || echo "BIOS"

You can check status of secureboot with following command.

mokutil --sb-state
More info: https://launchpad.net/~kelebek333/+archive/ubuntu/kablosuz
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/kelebek333-ubuntu-kablosuz-kali-rolling.list
Adding deb entry to /etc/apt/sources.list.d/kelebek333-ubuntu-kablosuz-kali-rolling.list
Found existing deb-src entry in /etc/apt/sources.list.d/kelebek333-ubuntu-kablosuz-kali-rolling.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/kelebek333-ubuntu-kablosuz-kali-rolling.list
Adding key to /etc/apt/trusted.gpg.d/kelebek333-ubuntu-kablosuz.gpg with fingerprint F30D3DBFB7534F670B44C71923E50C670722A6D9
Ign:1 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Ign:2 https://apt.dockerproject.org/repo ubuntu-trusty InRelease                                                                           
Hit:3 http://kali.download/kali kali-bleeding-edge InRelease                                                                               
Hit:4 http://kali.download/kali kali-experimental InRelease                                                                                  
Ign:5 https://download.docker.com/linux/debian kali-rolling InRelease                                                                        
Hit:6 https://download.docker.com/linux/debian bullseye InRelease                      
Hit:7 http://kali.download/kali kali-rolling InRelease                            
Ign:1 https://apt.dockerproject.org/repo ubuntu-xenial InRelease                  
Ign:2 https://apt.dockerproject.org/repo ubuntu-trusty InRelease                 
Err:8 https://download.docker.com/linux/debian kali-rolling Release              
  404  Not Found [IP: 108.158.245.53 443]
Ign:1 https://apt.dockerproject.org/repo ubuntu-xenial InRelease                 
Ign:2 https://apt.dockerproject.org/repo ubuntu-trusty InRelease
Ign:9 https://ppa.launchpadcontent.net/kelebek333/kablosuz/ubuntu kali-rolling InRelease
Err:10 https://ppa.launchpadcontent.net/kelebek333/kablosuz/ubuntu kali-rolling Release
  404  Not Found [IP: 185.125.190.80 443]
Err:1 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
  Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
Err:2 https://apt.dockerproject.org/repo ubuntu-trusty InRelease
  Something wicked happened resolving 'apt.dockerproject.org:https' (-5 - No address associated with hostname)
Reading package lists... Done
W: https://download.docker.com/linux/debian/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/kelebek333/kablosuz/ubuntu kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by thaJeztah** [comment]
Closing in favour of the discussion at https://github.com/moby/moby/discussions/47400
