### ISSUE TITLE
docker image list vs. docker images list is confusing

### ISSUE THREAD

**Issue by dmaphy** [moby/moby#47404]
### Description

I've made a typo, by accident, of course. The behavior is quite clear after some seconds. `docker images` is the same as `docker image list`. So if you type `docker images list`, the `list` is already handled as a repository name and just returning an empty list of images.

### Reproduce

1. docker images list
2. docker image list
3. docker images

### Expected behavior

My expectation as a user would be, that docker is telling me I've actually made a typo. So `docker images list` would not just return an empty list but is telling me, at least with a small hint like e.g. "Did you mean `docker image list`?", that this probably could have been a typo.

### docker version

```bash
❯ docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.21.0
 Git commit:        %{shortcommit_cli}
 Built:             Sun Aug 27 16:45:40 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.0
  Git commit:       %{shortcommit_moby}
  Built:            Sun Aug 27 16:45:40 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.23
  GitCommit:        
 runc:
  Version:          1.1.12
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
❯ docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  selinux
  cgroupns
 Kernel Version: 6.7.4-200.fc39.x86_64
 Operating System: Fedora Linux 39 (Xfce)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 14.39GiB
 Name: lapdhopf.inovex.de
 ID: XZUV:V2LS:IUIW:5SHT:Y2YL:FRFK:NPY4:FJAN:UFAE:JW7B:Q2BQ:6MLS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### Additional Info

I'm running the current moby-engine package on Fedora here:

```
> dnf provides `which docker`
moby-engine-24.0.5-1.fc39.x86_64 : The open-source application container engine
Repo        : @System
Matched from:
Filename    : /usr/bin/docker
```

**Comment by coolljt0725** [comment]
Looks like a client issue. https://github.com/docker/cli/issues  would be a better place for this issue

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, it's not ideal, because the `images` command existed before the introduction of the `<object> <verb>` commands (such as `image ls`, `image pull`).

We merged a pull request on the CLI that prints a warning when `docker images` does not return a result, and if the search-term used was one of the subcommands for `docker image` (such as `ls` or `list`);

- https://github.com/docker/cli/pull/4849

That patch didn't ship yet in a release, but will be part of the updating v26.0 release of the CLI.


I'll close this ticket because this should be addressed, but feel free to continue the conversation.

**Comment by dmaphy** [comment]
https://github.com/docker/cli/pull/4849 does exactly what the purpose of this bugreport was. Thanks very much for the prompt reaction and sorry for not reporting this issue in the right place, though!

**Comment by thaJeztah** [comment]
No worries, it's always confusing "where" to report! And glad the solution (although still a bit of a workaround) is matching what you had in mind.

Thanks again for opening a ticket; it's appreciated ❤️
