### ISSUE TITLE
How to set seccomp on docker services?

### ISSUE THREAD

**Issue by bgemmill** [moby/moby#47545]
### Description

I'm trying to deploy a service that uses io_uring, which is [disallowed by the default seccomp profile](https://github.com/moby/moby/issues/47532).

When trying to set the property in my service's yml file like [the documentation suggests](https://docs.docker.com/compose/compose-file/05-services/#security_opt):
```
  security_opt:
    - seccomp:unconfined # io_uring init
```

Docker reports: `Ignoring unsupported options: security_opt`

And that seems to be because that option [hasn't been wired up](https://github.com/moby/moby/issues/41371) yet for services.

I could set docker's [daemon.json file](https://docs.docker.com/reference/cli/dockerd/#daemon-configuration-file) on all of the target boxes to run with `seccomp:unconfined` by default, but that seems a little heavy handed since it will affect every service on those boxes.

Is there something better to do in the mean time until the `security_opt` flag gets wired in?

### Reproduce

1) Have a docker service that needs security options, as specified in a yml file
2) docker stack deploy yml file
3) see `Ignoring unsupported options: security_opt`
4) Ask what to do on github!

### Expected behavior

It should work like the `ulimits` set of options.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.4
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        1a576c5
 Built:             Wed Mar  6 16:32:12 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.4
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       061aa95
  Built:            Wed Mar  6 16:32:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 25.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-21-generic
 Operating System: Linux Mint 21.3
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 62.5GiB
 Name: spore
 ID: ZIHG:IUVG:WBMF:SWXK:7BIZ:WGNV:WDLY:B2FI:YHT7:LI2X:MV7G:D3HB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: project5
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by neersighted** [comment]
cc @dperny; I believe this is just not plumbed yet

**Comment by neersighted** [comment]
(also, please note that you are looking at the docs for the Compose spec; not Compose v3 which Swarm uses -- we know this is confusing and are working on it 😅)

**Comment by bgemmill** [comment]
Thanks for the heads up about the documentation, it looks like the proper place [would have informed me](https://docs.docker.com/compose/compose-file/compose-file-v3/#security_opt) of this option being ignored rather than going digging!

Is it possible to plumb this in? At the moment, it looks like anything gated behind the default seccomp profile is just unavailable in swarm unless it's opened up machine wide in `/etc/docker/daemon.json`.

**Comment by neersighted** [comment]
I'm going to close this as a duplicate of https://github.com/moby/moby/issues/41371; currently this is exposed in the API, but needs to be enabled in the CLI (both `docker service` and `docker stack`).
