### ISSUE TITLE
"systemd-journald" journal rotation seems to cause a SIGBUS error in a specific docker container

### ISSUE THREAD

**Issue by vxjohanforssell** [moby/moby#47565]
### Description

We have Dockerd set up to use Journald. 

First, Journald rotates the journal. This happens very often with my settings.
```
mar 13 20:18:26 systemd-journald[159]: /var/log/journal/ec255560a0c88b05c58ef2197f3fe77a/system.journal: Journal header limits reached or header out-of-date, rotating.
```

About once a day, this is followed by one of the docker containers (a very prolific logger) receiving a SIGBUS signal. It says "dockerd", but the PID in [] are one of the docker containers (Mongodb MongoS).
```
mar 13 20:18:26 dockerd[1905973]: fatal error: unexpected signal during runtime execution
mar 13 20:18:26 dockerd[1905973]: [signal SIGBUS: bus error code=0x2 addr=0x7f05bc400098 pc=0x7f1270178cfe]
mar 13 20:18:26 dockerd[1905973]: runtime stack:
mar 13 20:18:26 dockerd[1905973]: runtime.throw({0x5592dd2b56df?, 0x0?})
mar 13 20:18:26 dockerd[1905973]:         /usr/local/go/src/runtime/panic.go:1047 +0x5f fp=0x7f1224ff8b70 sp=0x7f1224ff8b40 pc=0x5592db69247f
mar 13 20:18:26 dockerd[1905973]: runtime.sigpanic()
mar 13 20:18:26 dockerd[1905973]:         /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f1224ff8bd0 sp=0x7f1224ff8b70 pc=0x5592db6a9f29
mar 13 20:18:26 dockerd[1905973]: goroutine 1157634 [syscall, locked to thread]:
mar 13 20:18:26 dockerd[1905973]: runtime.cgocall(0x5592dd23c3d0, 0xc003382910)
mar 13 20:18:26 dockerd[1905973]:         /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0033828e8 sp=0xc0033828b0 pc=0x5592db65b21c
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal._Cfunc_sd_journal_next(0x7f1200000e00)
mar 13 20:18:26 dockerd[1905973]:         _cgo_gotypes.go:179 +0x50 fp=0xc003382910 sp=0xc0033828e8 pc=0x5592dcfb1e50
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal.(*Journal).Next.func1(0x5592db6a6ba0?)
mar 13 20:18:26 dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/internal/sdjournal/sdjournal.go:118 +0x46 fp=0xc003382948 sp=0xc003382910 pc=0x5592dcfb3366
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal.(*Journal).Next(0xc003382ae0?)
mar 13 20:18:26 dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/internal/sdjournal/sdjournal.go:118 +0x19 fp=0xc003382990 sp=0xc003382948 pc=0x5592dcfb3299
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).drainJournal(0xc002a921c0)
mar 13 20:18:26 dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:166 +0x2a5 fp=0xc003382cb8 sp=0xc003382990 pc=0x5592dcfb5725
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).readJournal(0xc002a921c0)
mar 13 20:18:26 dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:301 +0x35b fp=0xc003382de8 sp=0xc003382cb8 pc=0x5592dcfb681b
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).readLogs(0xc002a921c0)
mar 13 20:18:26 dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:365 +0x2ca fp=0xc003382fc8 sp=0xc003382de8 pc=0x5592dcfb6dca
mar 13 20:18:26 dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*journald).ReadLogs.func1()
...
```

This stacktrace is approximately 39k lines long.

Looking at the stacktrace, I found my way over to https://github.com/moby/moby/blob/master/daemon/logger/journald/internal/sdjournal/sdjournal.go#L118, where it "advances the read pointer to the next entry".

_Could this next entry have disappeared, been rotated away by journald?_

This in turn causes dockerd to terminate all its containers, which I'm not that thrilled about.

### Reproduce

Run a busy Mongos instance and rotate journals? No idea really.

### Expected behavior

Docker should be able to handle journal rotation.

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 40
  Running: 40
  Paused: 0
  Stopped: 0
 Images: 61
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-1017-aws
 Operating System: Ubuntu 23.04
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.81GiB
 Name: wlc-9d6444-aza.eu1.vxfiber.dev
 ID: d5eb17a9-be82-43b4-9102-900b01743eed
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.29.0.0/16, Size: 24
```

### Additional Info

mar 13 20:18:26 machine-name systemd-journald[159]: Data hash table of /var/log/journal/ec255560a0c88b05c58ef2197f3fe77a/system.journal has a fill level at 75.0 (136536 of 182044 items, 50331648 file size, 368 bytes per hash table item), suggesting rotation.
mar 13 20:18:26 machine-name systemd-journald[159]: /var/log/journal/ec255560a0c88b05c58ef2197f3fe77a/system.journal: Journal header limits reached or header out-of-date, rotating.
mar 13 20:18:26 machine-name dockerd[1905973]: fatal error: unexpected signal during runtime execution
mar 13 20:18:26 machine-name dockerd[1905973]: [signal SIGBUS: bus error code=0x2 addr=0x7f05bc400098 pc=0x7f1270178cfe]
mar 13 20:18:26 machine-name dockerd[1905973]: runtime stack:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.throw({0x5592dd2b56df?, 0x0?})
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/panic.go:1047 +0x5f fp=0x7f1224ff8b70 sp=0x7f1224ff8b40 pc=0x5592db69247f
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.sigpanic()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7f1224ff8bd0 sp=0x7f1224ff8b70 pc=0x5592db6a9f29
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 1157634 [syscall, locked to thread]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.cgocall(0x5592dd23c3d0, 0xc003382910)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0033828e8 sp=0xc0033828b0 pc=0x5592db65b21c
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal._Cfunc_sd_journal_next(0x7f1200000e00)
mar 13 20:18:26 machine-name dockerd[1905973]:         _cgo_gotypes.go:179 +0x50 fp=0xc003382910 sp=0xc0033828e8 pc=0x5592dcfb1e50
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal.(*Journal).Next.func1(0x5592db6a6ba0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/internal/sdjournal/sdjournal.go:118 +0x46 fp=0xc003382948 sp=0xc003382910 pc=0x5592dcfb3366
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald/internal/sdjournal.(*Journal).Next(0xc003382ae0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/internal/sdjournal/sdjournal.go:118 +0x19 fp=0xc003382990 sp=0xc003382948 pc=0x5592dcfb3299
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).drainJournal(0xc002a921c0)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:166 +0x2a5 fp=0xc003382cb8 sp=0xc003382990 pc=0x5592dcfb5725
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).readJournal(0xc002a921c0)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:301 +0x35b fp=0xc003382de8 sp=0xc003382cb8 pc=0x5592dcfb681b
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*reader).readLogs(0xc002a921c0)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:365 +0x2ca fp=0xc003382fc8 sp=0xc003382de8 pc=0x5592dcfb6dca
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/docker/docker/daemon/logger/journald.(*journald).ReadLogs.func1()
mar 13 20:18:25 machine-name 0b1fca9ef43a[1905973]: {"t":{"$date":"2024-03-13T20:18:25.690+00:00"},"s":"I",  "c":"COMMAND",  "id":22749,   "ctx":"conn28254","msg":"Unexpected field for mongos collStats","attr":{"fieldName":"$configServerState"}}
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:386 +0x26 fp=0xc003382fe0 sp=0xc003382fc8 pc=0x5592dcfb7386
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc003382fe8 sp=0xc003382fe0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by github.com/docker/docker/daemon/logger/journald.(*journald).ReadLogs
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/daemon/logger/journald/read.go:386 +0x1f0
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 1 [semacquire, 4805 minutes, locked to thread]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x60?, 0x60?, 0x0?, 0x15?, 0x5592db66514a?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0032137e0 sp=0xc0032137c0 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goparkunlock(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:387
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.semacquire1(0xc002372338, 0x20?, 0x1, 0x0, 0x91?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/sema.go:160 +0x214 fp=0xc003213848 sp=0xc0032137e0 pc=0x5592db6a70b4
mar 13 20:18:26 machine-name dockerd[1905973]: sync.runtime_Semacquire(0xc0015fa340?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/sema.go:62 +0x27 fp=0xc003213880 sp=0xc003213848 pc=0x5592db6c60e7
mar 13 20:18:26 machine-name dockerd[1905973]: sync.(*WaitGroup).Wait(0xc000cb0000?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/sync/waitgroup.go:116 +0x4b fp=0xc0032138a8 sp=0xc003213880 pc=0x5592db6eb7eb
mar 13 20:18:26 machine-name dockerd[1905973]: main.(*DaemonCli).start(0xc000cb0000, 0xc000a155e0)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/cmd/dockerd/daemon.go:304 +0x174b fp=0xc003213cf0 sp=0xc0032138a8 pc=0x5592dd23096b
mar 13 20:18:26 machine-name dockerd[1905973]: main.runDaemon(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/cmd/dockerd/docker_unix.go:14
mar 13 20:18:26 machine-name dockerd[1905973]: main.newDaemonCommand.func1(0xc000004c00?, {0xc000caa000?, 0x3?, 0x3?})
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/cmd/dockerd/docker.go:39 +0x94 fp=0xc003213d20 sp=0xc003213cf0 pc=0x5592dd236fd4
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/spf13/cobra.(*Command).execute(0xc000004c00, {0xc0000520d0, 0x3, 0x3})
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/vendor/github.com/spf13/cobra/command.go:916 +0x862 fp=0xc003213e58 sp=0xc003213d20 pc=0x5592db85f942
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd fp=0xc003213f10 sp=0xc003213e58 pc=0x5592db86023d
mar 13 20:18:26 machine-name dockerd[1905973]: github.com/spf13/cobra.(*Command).Execute(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/vendor/github.com/spf13/cobra/command.go:968
mar 13 20:18:26 machine-name dockerd[1905973]: main.main()
mar 13 20:18:25 machine-name 0b1fca9ef43a[1905973]: {"t":{"$date":"2024-03-13T20:18:25.690+00:00"},"s":"I",  "c":"COMMAND",  "id":22749,   "ctx":"conn28254","msg":"Unexpected field for mongos collStats","attr":{"fieldName":"$clusterTime"}}
mar 13 20:18:26 machine-name dockerd[1905973]:         /root/build-deb/engine/cmd/dockerd/docker.go:109 +0x18c fp=0xc003213f80 sp=0xc003213f10 pc=0x5592dd23722c
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.main()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc003213fe0 sp=0xc003213f80 pc=0x5592db694e72
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc003213fe8 sp=0xc003213fe0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 2 [force gc (idle), 4805 minutes]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000084fb0 sp=0xc000084f90 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goparkunlock(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:387
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.forcegchelper()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000084fe0 sp=0xc000084fb0 pc=0x5592db6950f0
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.init.6
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:293 +0x25
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 3 [GC sweep wait]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x5592def5d401?, 0x0?, 0x0?, 0x0?, 0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000085780 sp=0xc000085760 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goparkunlock(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:387
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.bgsweep(0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000857c8 sp=0xc000085780 pc=0x5592db67dc7e
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gcenable.func1()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000857e0 sp=0xc0000857c8 pc=0x5592db672e06
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000857e8 sp=0xc0000857e0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.gcenable
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:178 +0x6b
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 4 [GC scavenge wait]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x5592def61200?, 0xb97c30?, 0x0?, 0x0?, 0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000085f70 sp=0xc000085f50 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goparkunlock(...)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:387
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.(*scavengerState).park(0x5592def61200)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000085fa0 sp=0xc000085f70 pc=0x5592db67bab3
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.bgscavenge(0x0?)
mar 13 20:18:25 machine-name 0b1fca9ef43a[1905973]: {"t":{"$date":"2024-03-13T20:18:25.690+00:00"},"s":"I",  "c":"COMMAND",  "id":22749,   "ctx":"conn28254","msg":"Unexpected field for mongos collStats","attr":{"fieldName":"$configTime"}}
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000085fc8 sp=0xc000085fa0 pc=0x5592db67c0c5
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gcenable.func2()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000085fe0 sp=0xc000085fc8 pc=0x5592db672da6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000085fe8 sp=0xc000085fe0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.gcenable
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:179 +0xaa
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 5 [finalizer wait]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x0?, 0x5592ddc8ee50?, 0x20?, 0xe0?, 0x2000000020?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc003bf8e28 sp=0xc003bf8e08 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.runfinq()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc003bf8fe0 sp=0xc003bf8e28 pc=0x5592db671da7
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc003bf8fe8 sp=0xc003bf8fe0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.createfing
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mfinal.go:163 +0x45
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 6 [GC worker (idle)]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x41f22365ed7a9?, 0x1?, 0x77?, 0x93?, 0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000086750 sp=0xc000086730 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gcBgMarkWorker()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000867e0 sp=0xc000086750 pc=0x5592db674b71
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000867e8 sp=0xc0000867e0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.gcBgMarkStartWorkers
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:1199 +0x25
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 18 [GC worker (idle)]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x41f22365ed835?, 0x3?, 0x91?, 0x5b?, 0x0?)
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000080750 sp=0xc000080730 pc=0x5592db6952b6
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gcBgMarkWorker()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000807e0 sp=0xc000080750 pc=0x5592db674b71
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.goexit()
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000807e8 sp=0xc0000807e0 pc=0x5592db6ca781
mar 13 20:18:26 machine-name dockerd[1905973]: created by runtime.gcBgMarkStartWorkers
mar 13 20:18:26 machine-name dockerd[1905973]:         /usr/local/go/src/runtime/mgc.go:1199 +0x25
mar 13 20:18:26 machine-name dockerd[1905973]: goroutine 34 [GC worker (idle)]:
mar 13 20:18:26 machine-name dockerd[1905973]: runtime.gopark(0x41f22365db381?, 0x3?, 0x2a?, 0xc2?, 0x0?)
mar 13 20:18:25 machine-name 0b1fca9ef43a[1905973]: {"t":{"$date":"2024-03-13T20:18:25.690+00:00"},"s":"I",  "c":"COMMAND",  "id":22749,   "ctx":"conn28254","msg":"Unexpected field for mongos collStats","attr":{"fieldName":"$topologyTime"}}
...

**Comment by thaJeztah** [comment]
@corhere ptal

**Comment by corhere** [comment]
It's a systemd bug; nothing we can do. Follow up with your distro to get a fix backported if possible.
- https://github.com/systemd/systemd/issues/24320

**Comment by vxjohanforssell** [comment]
Thank you for the quick response!
