### ISSUE TITLE
Search for `.config/docker-compose.yml`

### ISSUE THREAD

**Issue by bersace** [moby/moby#47600]
### Description

Hi,

There is an effort to unclutter root directory of project by using a local `.config` directory: https://github.com/pi0/config-dir. docker-compose.yml is very common at root of project to describe the development environment.

I suggest that docker compose also search for `.config/docker-compose.yml`.

Regards,
Étienne

**Comment by thaJeztah** [comment]
This looks like a feature request for compose or the compose specification, neither of which are maintained in this repository; I recommend opening a ticket in the compose issue tracker instead; https://github.com/docker/compose

**Comment by bersace** [comment]
Sorry. Thanks.

https://github.com/docker/compose/issues/11640
