### ISSUE TITLE
Viability of container start timeout

### ISSUE THREAD

**Issue by LarsSven** [moby/moby#47617]
### Description

I would be willing to look into this feature and work on it myself. This issue is to mainly discuss the viability of the feature.

 I think it would be extremely useful to have the option to add timeouts to running containers. So that when one starts a container, they can specify that the container must be killed after x time. This has some real use cases (For my team this feature is critical and is currently implemented in the program that runs containers, which is inefficient), but it's also a nice security feature, as imposing maximum time limits outside of CPU time on programs can prevent denial of service by users imposing reasonable limits.

As stated I would be fine looking into this, but I mainly wanted to ask the moby team whether this is something that has a chance of actually making it, or that this is something that you don't want to support within Moby for any reason.

**Comment by LarsSven** [comment]
@thaJeztah @cpuguy83 @vvoland are I believe the relevant contacts for this?

**Comment by LarsSven** [comment]
I believe this can be implemented quite elegantly through channels and select: https://gobyexample.com/timeouts

**Comment by neersighted** [comment]
This is a feature for a container orchestrator; if you wanted something built in, I think it would make sense as part of Swarm Jobs and Services.

cc @dperny

**Comment by thaJeztah** [comment]
Prior discussions / duplicates; there's quite some topics there, and I think various were related to "clean up containers that were forgotten about, after X hours or days";

- https://github.com/moby/moby/issues/1905
- https://github.com/moby/moby/issues/46870



Not sure if adding this to swarm would satisfy most of those use-cases, but I also don't think it should be a functionality for "docker run", as it's really an orchestration (or even for an external tool)

**Comment by LarsSven** [comment]
Our main use case is not about forgotten containers. For our use case, users get x time to complete a calculation, and if not their container gets killed and they "failed the test". Which doesn't feel like it's part of docker swarm but instead more a core docker thing.

**Comment by neersighted** [comment]
We tend to draw a distinction in this repository for "runtime functionality" vs "orchestrator functionality." In general, we only strive to be a runtime; features such as restart policy have been quite controversial (in terms of what people expect) and painful (to improve/maintain) over the years; and other value-on-top but optional features like healthchecks are often confusing to users (as we don't **do** anything with them at the runtime level).

I do think that in general, we are not interested in adding more reconciliation logic to the engine itself. For those that want reconciliation and orchestration functionality (or put another way: declarative containers), we have a built-in orchestrator that works quite well even with a single node.

See https://github.com/moby/moby/issues/47548 for some similar discussion from the last month.

**Comment by LarsSven** [comment]
That is a fair argument, thank you for your explanation.

**Comment by thaJeztah** [comment]
> Our main use case is not about forgotten containers. For our use case, users get x time to complete a calculation, and if not their container gets killed and they "failed the test"....

Thanks!

> We tend to draw a distinction in this repository for "runtime functionality" vs "orchestrator functionality."

Yes, correct; where possible, we try to limit scope to providing the _building blocks_ to make these use-cases possible. I should note that https://github.com/moby/moby/issues/1905 has various examples that may work for a number of use-cases, which could be the "linux way" of combining tools, which could be a script defining a timeout for running a container, or an entrypoint script in the container for this purpose. We realize this may sometimes be less "polished" as a built-in option, but must always be careful adding features that we can't back out of, or that can become a sliding slope leading to feature creep; specifically if expectations differ too much.
