### ISSUE TITLE
Split Healthcheck start interval into its own default value as per docs

### ISSUE THREAD

**Issue by saltydk** [moby/moby#47648]
### Description

Is there a particular reason that the start interval inherits the value from regular interval?
https://github.com/moby/moby/blob/a33b302d5496c0edb434a63fe927d71d9e333839/daemon/health.go#L253-L255

Docs indicate that the default is 5 seconds: https://docs.docker.com/reference/dockerfile/#healthcheck

This request is to have it defined as its own default value as per the docs.

I apologize if I have misread the code as I am not a Golang programmer.

**Comment by neersighted** [comment]
cc @cpuguy83

**Comment by cpuguy83** [comment]
I think this was just an oversight.

**Comment by j2walker** [comment]
Hi @vvoland, I am a student from UT Austin taking a class about virtualization and containerization (CS 360V). Could I tackle this bug fix?

**Comment by cpuguy83** [comment]
Please do.

**Comment by yumski** [comment]
Hey @cpuguy83, does this issue still need to be worked on? Happy to contribute if needed.

**Comment by thaJeztah** [comment]
I see there's a PR Linked to this that's in review;

- https://github.com/moby/moby/pull/47799
