### ISSUE TITLE
docker/client: support `DOCKER_HOST` with SSH protocol

### ISSUE THREAD

**Issue by giautm** [moby/moby#47650]
### Description

The `DOCKER_HOST` environment with `ssh://` protocol is currently supported with docker-cli. But when we create the connection with `docker/client`. It was unable to handle the connection string.

**Comment by trajano** [comment]
dup https://github.com/moby/moby/issues/46821

**Comment by thaJeztah** [comment]
Ah, yes, let's close in favour of https://github.com/moby/moby/issues/46821
