### ISSUE TITLE
Executing 'docker exec' to enter a container does not generate any logs.

### ISSUE THREAD

**Issue by Schorem2** [moby/moby#47714]
### Description

Issue Description:
Currently, there is no logging of login and logout events when logging into a container via Docker. This represents a certain deficiency in terms of security. Therefore, I suggest improving Docker to log relevant events when users log into a container.
Proposed Improvement:

1.Logging Login Events: Log login events to the Docker logs when users log into a container, including the timestamp of the login and relevant user information (such as username or ID).

2.Logging Command History: In addition to login events, log the command history of users executing commands within the container. This helps users understand the operational flow within the container and aids in troubleshooting when needed.

3.Configurability: To cater to different user needs, suggest designing this logging feature to be configurable, allowing users to flexibly enable or disable it as per their requirements.

Expected Outcome:

With these improvements, users will be able to more easily track the operations and events within containers, thereby facilitating faster troubleshooting and debugging.

Additional Information:

If more information is needed or if I should provide additional details, please let me know. Thank you for considering this proposal!

**Comment by vvoland** [comment]
There are events published when exec is created, started and dies:

```bash
$ docker run -d --name asdf nginx

$ docker events &

$ docker exec nginx sh
2024-04-16T10:12:11.513015590Z container exec_create: sh  396aa17a52c33e4ff2b1c9
647e0b5c54db5c656fea9f6be8d86fe288201c4d88 (execID=eedf99c918f136f18a852bd13da93
6d80dad6a3a03bf07da8ff02806eefa0d01, image=nginx, maintainer=NGINX Docker Mainta
iners <docker-maint@nginx.com>, name=asdf)
2024-04-16T10:12:11.513638390Z container exec_start: sh  396aa17a52c33e4ff2b1c96
47e0b5c54db5c656fea9f6be8d86fe288201c4d88 (execID=eedf99c918f136f18a852bd13da936
d80dad6a3a03bf07da8ff02806eefa0d01, image=nginx, maintainer=NGINX Docker Maintai
ners <docker-maint@nginx.com>, name=asdf)
2024-04-16T10:12:11.539399768Z container exec_die 396aa17a52c33e4ff2b1c9647e0b5c
54db5c656fea9f6be8d86fe288201c4d88 (execID=eedf99c918f136f18a852bd13da936d80dad6
a3a03bf07da8ff02806eefa0d01, exitCode=0, image=nginx, maintainer=NGINX Docker Ma
intainers <docker-maint@nginx.com>, name=asdf)
```

Also, please keep in mind that there is no such thing as `logging into a container`.  `docker exec` only creates a new task (process) inside the container. It shouldn't be regarded as an equivalent of sshing into a vm.

Let me close the issue as not planned, but feel free to continue the conversation!
