### ISSUE TITLE
Remove env-var that allows IPv6 to be left enabled on an IPv4-only interface

### ISSUE THREAD

**Issue by robmry** [moby/moby#47773]
### Description

Once it's easy to enable IPv6 on a network, without needing to configure IPAM (and just end up with kernel-assigned addresses) ... remove the env-var escape hatch that was added in https://github.com/moby/moby/pull/47769

**Comment by thaJeztah** [comment]
@robmry v26.1 now has a release branch, so I think we can open a PR against master to remove it (so that it gets into v27.0)

**Comment by robmry** [comment]
> @robmry v26.1 now has a release branch, so I think we can open a PR against master to remove it (so that it gets into v27.0)

I'm not sure we'll be ready in 27.0 ... the current plan is that, if there's no IPv6 in default-address-pools, we'll allocate from a unique-local subnet (with a global id based on the engine id or similar). I don't think we'll get as far as having an easy way to allow a network to be IPv6-enabled without allocating IPv6 addresses - we'll need to add some more control over IPAM, probably making it possible to specify default IPAM for v4 and something else for v6.

So, this issue is likely to get bumped to milestone 28.0 ... but we're probably not quite there yet.

**Comment by thaJeztah** [comment]
Ah, gotcha! I incorrectly assumed this was a reminder to remove the patch as soon as the release-branch was created; sorry for the noise 😅 🙈
