### ISSUE TITLE
ConfigFrom and ConfigOnly are not documented in OpenAPI spec for network create/get operations

### ISSUE THREAD

**Issue by felixfontein** [moby/moby#47790]
### Description

`ConfigFrom` and `ConfigOnly` are not documented in OpenAPI spec for network create/get operations

### Reproduce

-

### docker version

```bash
-
```

### docker info

```bash
-
```

**Comment by thaJeztah** [comment]
And... I just noticed there's a `docs/revisit` label on that one; it looks like I noticed at the time that docs were missing, but I recall that there was some time-pressure to have it included in the release, and no follow-up happened :see_no_evil: https://github.com/moby/moby/pull/32981#pullrequestreview-38818982

<img width="922" alt="Screenshot 2024-05-02 at 10 43 39" src="https://github.com/moby/moby/assets/1804568/f05a193d-4094-4bf4-a4e6-46ba808b5760">
