### ISSUE TITLE
Docker 26 return IPv6 localhost (::1) even when ipv6 is disabled in /etc/docker/daemon.json

### ISSUE THREAD

**Issue by Yaytay** [moby/moby#47948]
### Description

Install docker-ce (5:26.1.4-1~ubuntu.22.04~jammy) and exec into a container to get the address of localhost:
# docker exec 4d28a72fed10 ping localhost
PING localhost (::1): 56 data bytes
64 bytes from ::1: seq=0 ttl=64 time=0.060 ms
64 bytes from ::1: seq=1 ttl=64 time=0.077 ms

The service we have running on that container does not handle IPv6 and thus health checks based on IPv6 fail.

The aspect that I think is a bug is that the /dev/docker/daemon.json on this host contains:
{
  "storage-driver": "overlay2"
  , "ipv6": false
  , "bip": "10.11.12.1/24"
  , "debug": false
  , "log-driver": "json-file"
  , "log-opts": {
    "max-size": "100m"
    , "max-file": "5"
  }
}

we should not have to take any other steps to avoid IPv6 in our containers.

I think the issue is that https://github.com/moby/moby/pull/47406 doesn't check for the setting.

### Reproduce

Start a container on docker-c2 26.
Exec into it and check the DNS entry for localhost.

### Expected behavior

When /etc/docker/daemon.json contains 
 "ipv6": false
there should be no IPv6 in any containers.

### docker version

```bash
I have downgraded back to a working version.
The version that failed was 5:26.1.4-1~ubuntu.22.04~jammy
```

### docker info

```bash
Note that this has been run on a downgraded host:

Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: xylt3h9tq7tzz4nx3cnu46z7v
  Is Manager: false
  Node Address: 172.*.*.*
  Manager Addresses:
   172.*.*.*:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-112-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 39.17GiB
 Name: *.*.*
 ID: a8563ccb-ead7-4b68-868a-a03cb2517203
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://*.*.*.*:5000/
 Live Restore Enabled: false
```

**Comment by akerouanton** [comment]
Hi @Yaytay, thanks for reporting.

> When /etc/docker/daemon.json contains
> "ipv6": false
> there should be no IPv6 in any containers.

I think there's a misunderstanding here due to misleading docs: the daemon's `ipv6` flag doesn't disable ipv6 daemon-wide, but it only controls the availability of IPv6 on the _default_ bridge network. How did you create this container?

What you're observing is due to https://github.com/moby/moby/pull/47062. If you look at the [release notes for 26.0.0](https://docs.docker.com/engine/release-notes/26.0/#bug-fixes-and-enhancements-2), there's a note about this:

> To disable IPv6 in a container, use option `--sysctl net.ipv6.conf.all.disable_ipv6=1` in the create or run command, or the equivalent sysctls option in the service configuration section of a Compose file.
> 
> If IPv6 is not available in a container because it has been explicitly disabled for the container, or the host's networking stack does not have IPv6 enabled (or for any other reason) the container's `/etc/hosts` file will not include IPv6 entries.

If your software don't handle IPv6 properly, you should consider using this syctl to disable IPv6 altogether in that container.

**Comment by Yaytay** [comment]
Oh!
OK, thank you.

I think it would be convenient for there to be a way to prevent docker using IPv6 at all, but I guess I'll have to find another approach for now.
Rather than having to change a load of compose files we are going to look into remove IPv6 from the host as a first step.
