### ISSUE TITLE
Intermittent failure to recognize IPv4 forwarding enabled at system boot

### ISSUE THREAD

**Issue by delfuego** [moby/moby#47966]
### Description

I am running Docker on a fleet of Oracle Linux servers, and at system boot, occasionally Docker comes up claiming that IPv4 forwarding isn't enabled and that networking won't work:

```
dockerd[1462]: time="2024-06-11T11:34:36.927601576-04:00" level=warning msg="WARNING: IPv4 forwarding is disabled"
dockerd[1462]: time="2024-06-12T18:40:12.331985003-04:00" level=warning msg="IPv4 forwarding is disabled. Networking will not work."
```

And then, true to its word, Docker networking doesn't work in this state. Simply restarting the Docker daemon/service then cures the issue, which demonstrates that IPv4 forwarding is indeed enabled, and that this is some sort of race condition between the system networking coming up fully and Docker starting, a race that Docker only occasionally (like, 10-15% of the time) loses.

Just to prove it, on all the systems, `sysctl` shows that IPv4 forwarding is enabled:

```
$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

Docker was installed on all these servers using the [standard process](https://oracle-base.com/articles/linux/docker-install-docker-on-oracle-linux-ol8), so the systemd unit files and everything are the base defaults; then we have a systemd unit override file that allows us to set a different data root dir and enable network communication to the daemon.

Given that this is only an intermittent issue at boot, testing fixes has been difficult, but supporting the race-condition theory, if I add a systemd unit override file that includes a 5-second wait before starting the service, I haven't yet seen a failure like this happen:

```
[Service]
ExecStartPre=/bin/sleep 5
```

I'd love to hear any thoughts as to how to properly debug this, or if there are services on Oracle Linux 8 that are unique and need to be added to a serviced unit override file as dependencies for Docker to reliably start. 

### Reproduce

1. Stand up an Oracle Linux Server 8.10 server.
2. Install Docker (using [standard method](https://oracle-base.com/articles/linux/docker-install-docker-on-oracle-linux-ol8)).
3. Reboot server a few times, and see if the Docker daemon logs come up reporting that IPv4 forwarding is disabled.

### Expected behavior

Expected would be no error reports that IPv4 forwarding is disabled.

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:34:39 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:34 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-553.5.1.el8_10.x86_64
 Operating System: Oracle Linux Server 8.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.579GiB
 Name: fsccrl-jel02p.ncifcrf.gov
 ID: 2723c500-cb48-4d8a-b8b8-7379a2dfeceb
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by akerouanton** [comment]
Hi @delfuego,

Did you double-check that you didn't change dockerd's unit file or config file to set `ip-forward=false`?

Looking at the code, this is where we toggle `ip_forward` if the setting isn't disabled: https://github.com/moby/moby/blob/09777ade5af44889e800cbfc2948ded2a523bb00/libnetwork/drivers/bridge/setup_ip_forwarding.go#L35-L39

Through a number of indirection, this is where that code is called (during the daemon initialization): https://github.com/moby/moby/blob/8e96db1c328d0467b015768e42a62c0f834970bb/daemon/daemon.go#L1220-L1231

The first warning log you reported is written by the loop at the end of that code snippet.

So either, you disabled the `ip-forward` setting, or something else is racing against dockerd to enable/disable it.

**Comment by delfuego** [comment]
100% sure we haven't changed that — and the proof is in Docker working fine once we simply just issue `systemctl restart docker`.

But for the sake of completeness, the sum total of the changes we've implemented beyond the default Docker install and systemd unit files are adding this at `/etc/systemd/system/docker.service.d/docker.conf`:

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd
```

and then adding this at `/etc/docker/daemon.json`:

```
{
  "data-root": "/data/docker",
  "hosts": [ "tcp://0.0.0.0:2376", "unix:///var/run/docker.sock" ],
  "tls": true,
  "tlsverify": true,
  "tlscacert": "/etc/docker/ssl/ca.pem",
  "tlscert": "/etc/docker/ssl/server.pem",
  "tlskey": "/etc/docker/ssl/server.key"
}
```

And then as I said above, in our testing so far, if we add `ExecStartPre=/bin/sleep 5` to the `docker.conf` unit override file, we haven't seen any IPv4 forwarding failure state yet (but since the condition doesn't happen 100% of the time, it's not clear whether this is truly a workaround, or we just haven't tested enough).

Tracking backwards through code, this appears to be where the "WARNING: IPv4 forwarding is disabled" warning gets emitted (or added to the list of warnings to be emitted):

https://github.com/moby/moby/blob/450f18d3cae6be625d671b6bacd3eefcaaa13bb9/daemon/info_unix.go#L160

and that `IPv4ForwardingDisabled` flag gets set here:

https://github.com/moby/moby/blob/450f18d3cae6be625d671b6bacd3eefcaaa13bb9/pkg/sysinfo/sysinfo_linux.go#L269

which I believe means its set by reading the value of `/proc/sys/net/ipv4/ip_forward`. So I'm wondering if the race condition I'm seeing is related to the `/proc/sys/net/ipv4` namespace not yet being available at the time that that code above runs — I know that there have been times we've seen various errors related to not being able to read `/proc/sys/net/ipv4/vs/` entries that then go away as soon as the `ip_vs` module gets dynamically loaded, so I wonder if there's something similar going on here where Oracle Linux 8 isn't getting that namespace in place fast enough for Docker, and Docker doesn't have any way (or ability) to retry once the `ip_forward` "file" becomes available there.

**Comment by corhere** [comment]
> So I'm wondering if the race condition I'm seeing is related to the `/proc/sys/net/ipv4` namespace not yet being available at the time that that code above runs

`/proc/sys/net/ipv4` is part of the IPv4 network stack, [which cannot be built as a module. It must be built into the kernel.](https://unix.stackexchange.com/a/595509) Unless dockerd is being started before procfs is mounted, that seems unlikely.

The `Enabling IP forwarding failed` error (and the underlying error it wraps) gets logged by dockerd. What is the logged error message?
https://github.com/moby/moby/blob/450f18d3cae6be625d671b6bacd3eefcaaa13bb9/libnetwork/drivers/bridge/bridge_linux.go#L529-L535

**Comment by delfuego** [comment]
I don't see anything more in the logs above that's relevant than what's above. An example of the entirety of the log entries at startup (for an instance where the IPv4 forwarding bug/issue is present) are:

```
Jun 11 11:34:35 fsccrl-jel02p.ncifcrf.gov systemd[1]: Starting Docker Application Container Engine...
Jun 11 11:34:35 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:35.801764533-04:00" level=info msg="Starting up"
Jun 11 11:34:35 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:35.916505973-04:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jun 11 11:34:35 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:35.917023114-04:00" level=info msg="Loading containers: start."
Jun 11 11:34:36 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:36.476259230-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 17>
Jun 11 11:34:36 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:36.845451774-04:00" level=info msg="Loading containers: done."
Jun 11 11:34:36 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:36.927601576-04:00" level=warning msg="WARNING: IPv4 forwarding is disabled"
Jun 11 11:34:36 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:36.927637277-04:00" level=info msg="Docker daemon" commit=8e96db1 containerd-snapshotter=false>
Jun 11 11:34:36 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:36.927690658-04:00" level=info msg="Daemon has completed initialization"
Jun 11 11:34:37 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:37.362654836-04:00" level=info msg="API listen on /var/run/docker.sock"
Jun 11 11:34:37 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-11T11:34:37.372108184-04:00" level=info msg="API listen on [::]:2376"
Jun 11 11:34:37 fsccrl-jel02p.ncifcrf.gov systemd[1]: Started Docker Application Container Engine.
Jun 12 18:40:12 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-12T18:40:12.331985003-04:00" level=warning msg="IPv4 forwarding is disabled. Networking will not work."
Jun 12 18:40:12 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-12T18:40:12.988678908-04:00" level=warning msg="IPv4 forwarding is disabled. Networking will not work."
Jun 12 18:40:17 fsccrl-jel02p.ncifcrf.gov dockerd[1462]: time="2024-06-12T18:40:17.474079932-04:00" level=error msg="[resolver] failed to query external DNS server" client-ad>
```

(That last error then repeats anytime a container attempts to do a hostname lookup via the network.)

**Comment by delfuego** [comment]
Oh. My. LORD. I hadn't thought to look at the `/etc/sysctl.d/` stuff, and sure enough, there's a file there that's "enforcing CIS benchmarks" and disabling IPv4 forwarding (this fleet of servers are all US federal government systems, and have to adhere to CIS benchmarks when possible):

```
# required as per CIS benchmark
net.ipv4.ip_forward = 0
```

Which then begs the question: how is it being *re-enabled*? I obviously WANT it enabled, and now need to work with our security team to exempt it from this benchmark (since the benchmark doesn't make sense for a system that literally depends on IPv4 forwarding to function).

In any event, this now appears to (probably) be a huge waste of your time. UGH.

**Comment by corhere** [comment]
@delfuego dockerd is re-enabling the sysctl on daemon startup when the first bridge network is restored by `d.restore()`.
https://github.com/moby/moby/blob/8e96db1c328d0467b015768e42a62c0f834970bb/daemon/daemon.go#L1220-L1231
What's probably causing the warning is that systemd-sysctl is racing dockerd startup, flipping the sysctl back to 0 between `d.restore()` and the following `d.SystemInfo()` call.

**Comment by delfuego** [comment]
@corhere Just wanted to throw out a thanks for helping me work through this — when we discussed this issue with our own central configuration management team, they didn’t think to bring up that they were pushing and enforcing these baselines on these servers, so I didn’t suspect this as a cause. Now… I know better!

We’re now pushing to get this fleet of servers exempted from the baseline settings related to IP forwarding, and in the mean time, I’m going to try out your succession to add an `After=systemd-sysctl.service` ordering constraint — because I have to presume that would work around the issue entirely.
