### ISSUE TITLE
Latest version on GitHub is marked 23.0.13

### ISSUE THREAD

**Issue by aptalca** [moby/moby#48047]
### Description

Hi, it looks like a release for 23.0.13 is marked as the latest stable version on GitHub. Can that be changed to the actual latest stable release, 26.1.4?

Thanks

### Reproduce

N/A

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

**Comment by thaJeztah** [comment]
Ah, yes, look like GitHub was too eager when v23.0.13 was created, setting it to latest.

Should be fixed now 👍 /cc @corhere
