### ISSUE TITLE
NAT is disabled error when setting IPV6 loopback address in port mapping

### ISSUE THREAD

**Issue by ollipa** [moby/moby#48067]
### Description

Previously these settings worked in my docker compose file:

```yaml
my-service:
    ports:
      - "127.0.0.1:3000:3000"
      - "[::1]:3000:3000"
```

Now after updating docker, I get and error:
> Error response from daemon: driver failed programming external connectivity on endpoint my-service (...): NAT is disabled, omit host address in port mapping [::1]:3000:3000/tcp, or use [::]::3000 to open port 3000 for IPv6-only
host port must not be specified in mapping [::1]:3000:3000/tcp because NAT is disabled

### Reproduce

Not sure exactly what are the conditions but using IPV6 loopback address in port mapping causes this for me.

### Expected behavior

I would expect the configuration to still work or there should be clearer instructions how to make IPV6 loopback address in port mapping work again if the configuration is invalid.

### docker version

```bash
➜ docker version
Client: Docker Engine - Community
 Version:           27.0.2
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        912c1dd
 Built:             Wed Jun 26 18:47:16 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       e953d76
  Built:            Wed Jun 26 18:47:16 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

### Additional Info

Issue seems to be related to this commit:
https://github.com/moby/moby/commit/01eecb6cdf9496057af7e3a80503e9b5b46a8eaa

Which is part of:

- https://github.com/moby/moby/pull/47871

**Comment by robmry** [comment]
Hi @ollipa - thank you for reporting this.

I can reproduce the issue when the network is created without `--ipv6`. Previously, the userland proxy (`docker-proxy`) would have picked up traffic from the host's `::1` and sent it to the IPv4 address of the container.

As you say, the problem was introduced in https://github.com/moby/moby/commit/01eecb6cdf9496057af7e3a80503e9b5b46a8eaa - the check that's meant to be for the new mechanism for disabling NAT is missing this special case.

I don't think there's a workaround, other than to stick with 26.x until we can make a patch release.
