### ISSUE TITLE
Feature request: IPv6-enabled embedded DNS server

### ISSUE THREAD

**Issue by howardjohn** [moby/moby#48125]
### Description

This is like https://github.com/moby/moby/issues/41651. That issue was resolved by allowing the DNS server, which only listens on IPv4, to forward to IPv6 external DNS servers.

What this FR is about is adding IPv6 addresses into the `nameserver` of `resolv.conf` in  the container

In https://github.com/moby/moby/pull/47442#issuecomment-1965102267 it was mentioned this was put on hold until there were concrete use cases.

A concrete use case of this is in `kind`. See https://github.com/kubernetes-sigs/kind/issues/3114.

What happens is the pod networks get a `eth0` with only IPv6 addresses:
```
istio-proxy@b-v1-78688f5b46-7m8g9:/$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::6/128 scope global
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether da:5c:cd:9d:25:35 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fd00:10:244::2e/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d85c:cdff:fe9d:2535/64 scope link
       valid_lft forever preferred_lft forever
```

As a result, they cannot query the upstream DNS server, which is only on IPv4.

**Comment by corhere** [comment]
Your concrete use case involves [monkey-patching the container's iptables ruleset](https://github.com/kubernetes-sigs/kind/blob/79ffb67882fb77f0c8286ea89af66293bed76e1e/images/base/files/usr/local/bin/entrypoint#L458-L470) to forward packets received on a non-loopback interface to the container's embedded DNS resolver. It is tightly coupled to implementation details of container networking which are subject to change and therefore too brittle for kind to depend upon. (Or from another perspective, users actively depending on such implementation details ossifies our implementation, blocking us from making changes necessary to resolve long-standing limitations and bugs.) Extending our embedded DNS resolver to also listen on IPv6 loopback only serves to further entrench kind's use of monkeypatching, without benefiting any other users.

**Comment by howardjohn** [comment]
My use case is not "monkey patching docker rules" it is "I want to run Kubernetes in docker with Ipv6 DNS". I don't really care how that is done. Afaik the kind folks are under the impression this is not feasible without changes to docker, hence the issue (I am not a kind developer)

**Comment by corhere** [comment]
[I am engaging with the kind developers](https://github.com/kubernetes-sigs/kind/issues/3114#issuecomment-2218719891) to resolve this issue on their end.

**Comment by BenTheElder** [comment]
The "monkey patching" is completely orthogonal to not providing an IPv6 endpoint ...?

> It is tightly coupled to implementation details of container networking which are subject to change and therefore too brittle for kind to depend upon.

That's a totally reasonable and expected stance, but nobody here is asking that you further enable depending on this aspect, we're asking for an IPv6 listener ...? Which seems more generally useful, the embedded DNS resolver returning hostnames for containers is really handy for various purposes ..

It is totally expected that there may be a breaking change to the undocumented iptables rules and kind will deal with it then without making requests about any moby changes. In fact, if moby switched to e.g. actually putting the socket on the correct address without the iptables rules that would make life simpler for us once older implementations were phased out.

**Comment by BenTheElder** [comment]
As an aside: Unfortunately this hack (which we have not promoted or discussed!) has been copied to other popular projects including K3D and minikube:

https://github.com/k3d-io/k3d/blob/35dbaa4dedc510b5a4a0953be700b1cf5dc6b816/pkg/types/fixes/assets/k3d-entrypoint-dns.sh#L17-L23

https://github.com/kubernetes/minikube/blob/be3c33ce61aedfefed3729400c5b69e6378618b3/deploy/kicbase/entrypoint#L441-L453

.. but I think it is totally reasonable and expected if any breaking change happens to this, and the maintainers of those projects will have to deal with it.

What is unfortunate is the IPv4 only resolver, and I don't think it's reasonable for projects to run a v4 to v6 gateway within the container. KIND certainly could, but it's hardly the only user of the embedded resolver.

**Comment by BenTheElder** [comment]
> What is unfortunate is the IPv4 only resolver, and I don't think it's reasonable for projects to run a v4 to v6 gateway within the container. KIND certainly could, but it's hardly the only user of the embedded resolver.

https://github.com/moby/moby/pull/47442#issuecomment-1963730269 is a good point

**Comment by corhere** [comment]
> we're asking for an IPv6 listener ...? Which seems more generally useful, the embedded DNS resolver returning hostnames for containers is really handy for various purposes ..

While it may be useful, an IPv6 listener for the embedded DNS resolver is only _necessary_ to service DNS queries forwarded from some other network namespace. https://github.com/moby/moby/pull/47442#issuecomment-1964737825 

> In fact, if moby switched to e.g. actually putting the socket on the correct address without the iptables rules that would make life simpler for us once older implementations were phased out.

We use the iptables forwarding rule to allow containers to "shadow" the embedded resolver by binding to 127.0.0.11:53.

> What is unfortunate is the IPv4 only resolver, and I don't think it's reasonable for projects to run a v4 to v6 gateway within the container. KIND certainly could, but it's hardly the only user of the embedded resolver.

We expect projects to provide v4 to v4 gateways for DNS resolution of nested containers, too. Not only do we think it's reasonable, we are going to add one to buildkit! https://github.com/moby/moby/issues/48015#issuecomment-2173937848
