### ISSUE TITLE
Different checksum for same package on Docker PPA

### ISSUE THREAD

**Issue by tirolerstefan** [moby/moby#48306]
### Description

Hi,
the following packages have the same version, but a different checksum in the upstream docker repo:

```
https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_1.7.19-1_amd64.deb
https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/containerd.io_1.7.19-1_amd64.deb
```

```
$ md5sum *
256d3839ad01831941c6d4fefca62eb8  containerd.io_1.7.19-1_amd64.deb   #jammy
9fce91b00e093a4622ab47e4c6d47d9e  containerd.io_1.7.19-1_amd64.deb   #noble
```

In this situation, it is not possible to store those packages in a common repo (reprepro) at once:

```
File "pool/main/c/containerd.io/containerd.io_1.7.19-1_amd64.deb" is already registered with different checksums!
md5 expected: 256d3839ad01831941c6d4fefca62eb8, got: 9fce91b00e093a4622ab47e4c6d47d9e
sha1 expected: 069a5eb59d81cc5b2e2bcbe7fbe08eee2038ef79, got: 4034413ecf7d01836308866961a4c10578f1da86
sha256 expected: 53420426d602bdd8b9ecb7b023cd4f07e823a5ce682f37034e5370340e8af904, got: a3c7de1adcc145a685ba1b25a69a98a3b5d42be51748c8cec151f9f4806a55c7
size expected: 30490916, got: 30478536
There have been errors!
```

The docker-ce package has a OS specific appendix in its version - so it's possible to store all OS specific packages of (e.g.) version 26.0.0-1 in one repo:
docker-ce_26.0.0-1~**ubuntu.24.04~noble**_amd64.deb

Please - could you do this for the containerd.io package, too?
Thanks a lot!

### Reproduce

See above

### docker version

```bash
not specific - repository.
```

### docker info

```bash
not specific - repository.
```

**Comment by thaJeztah** [comment]
Thanks for reporting; Yes, this is something to add at some point, and being tracked in this issue;

- https://github.com/docker/containerd-packaging/issues/303

Given that packaging containerd is not part of the Moby project, I'll close this ticket, but feel free to continue the conversation.
