### ISSUE TITLE
Many colons in serial path worked before, but stopped working a week or so ago

### ISSUE THREAD

**Issue by Mastiffen** [moby/moby#48312]
### Description

I have a Docker image of SignalK with two connected serial ports in my boat Pi, one ESP32 NMEA2000 Sailor Hat and another one for NMEA1883 from the Garmin plotter. Using USB0/USB1 meant that they can change places after a reboot, and then neither of them will work. That happened to me today, because a week or so ago my Docker Compose file with this entry stopped working, after having worked for a couple of years or so:

```yaml
    devices:
      - /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0:/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0
      - /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-port0:/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-port0
```
 
After the update I had on the Pi 4 about a week ago it throws this error:
```
invalid spec: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0:/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0: too many colons
```
I tried with double and single quotes and the Unicode `\u0003A`, but that did not work.

I tried using a regular Docker command, from Decomposerize, but that thew an error as well:
```
docker: bad format for path: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0:/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0.
```

According to those at the Docker forum who knows what they are talking about (unlike me...) it really shouldn't have worked for the last couple of years, but it did. The final solution was to create symlinks. That works.

### Reproduce

1. Connect two serials.
2. Put in serial by path.
3. Try to start it up.

### Expected behavior

Docker should start.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:14 2024
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.31+rpt-rpi-v8
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.702GiB
 Name: MadMax
 ID: ec620975-9ab2-4aa7-9e49-671d6c402fee
 Docker Root Dir: /media/pi/Docker/Docker-System
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Hm, yeah not sure how that worked for you in the past; the format uses a colon as separator, which has been a known issues if those paths would contain a colon on its own; https://docs.docker.com/compose/compose-file/05-services/#devices

And I think you may be hitting this part in the compose-spec code; https://github.com/compose-spec/compose-go/blob/2ac541e85aa51d576e04e0b4b9e1992dafdf8c15/format/volume.go#L84

However if that error wasn't hit, looking at the code in compose itself, it seems like it wouldn't correctly handle splitting (or at least, it looks like the code would ignore the device if it had more than 3 parts) https://github.com/docker/compose/blob/69384a9a0f72cb0c5065c0aea1fd15b38b4dbd1e/pkg/compose/create.go#L648

**Comment by thaJeztah** [comment]
Looking at the history in the compose spec; I think this patch may be related https://github.com/compose-spec/compose-go/commit/072aa6418dcd93b4e31d0235df9dad5a6c11e63e

That one changed handling of devices to use the volumeIndexer (IIUC); and was part of this PR;

- https://github.com/compose-spec/compose-go/pull/610

That code would've probably introduced parsing as part of the spec, which then hit the error mentioned above.

**Comment by thaJeztah** [comment]
From the above, I think the cause of this is an issue in docker compose, not the docker engine (daemon); I would recommend opening a ticket in the docker compose issue tracker;

- https://github.com/docker/compose

**Comment by thaJeztah** [comment]
(But I must mention that such paths may still be problematic, due to the colon being the separator in the format)

**Comment by Mastiffen** [comment]
@thaJeztah That sounds logical. But from what I could see it didn't work in Docker without Docker Compose either:

`I tried using a regular Docker command, from Decomposerize, but that thew an error as well:
docker: bad format for path: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0:/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0.`

Do you mean that this probably never worked, and that it only worked on Docker Compose before this merge? That is confusing 
to me, because I have done `sudo apt-get full-upgrade` several times since March the 27th, I usually do it at least once a month.

**Comment by Mastiffen** [comment]
Thanks! Then I guess there's no real point in going further with this. I got it working with symlinks after advice from Rimelek at the Docker forum. Closing this.

**Comment by thaJeztah** [comment]
I think it might still be worth a try opening a ticket in compose to see if there's options there. I did not have a setup myself to easily test the "success" case with an older version of the engine; I'm interested to know if older versions of compose indeed created a correct container configuration (or at least what it looked like).

If it _DID_ work fully correctly in compose, that's still a regression there  I think.

**Comment by Mastiffen** [comment]
OK, then I will do that. I understood it as this was a conciuos desicion, but I probably misunderstood you.

**Comment by thaJeztah** [comment]
Hmm. yes it's a bit "grey area" for sure; IIUC the linked change, the _goal_ was to prevent duplicate devices from being created, i.e.;

```
- /dev/foo:/something
- /dev/foo:/something-else
- /dev/foo:/something-else-again
```

For that to work, the parsing now had to happen, but I don't think "paths with colons" was taken into account in that, and it being a "niche" use-case, the team working on compose very likely isn't aware they broke this scenario (assuming it all worked correctly somehow before).

Problems with colons in paths _were_ indeed a known issue, so yeah, from that perspective you may have depended on undocumented behavior (and just lucky); that doesn't make your use-case invalid though, and perhaps from that perspective it should be considered a feature request (provide an alternative syntax to allow for paths with colons).



Having a ticket to have that discussion doesn't do harm I think; it can help discuss options, and maybe someone from the compose-team or a contributor is interested in working on that. At worst, the ticket is rejected/closed, and no real harm done! ❤️

**Comment by Mastiffen** [comment]
Well, no harm done for me either, I could copy most of this ticket and only edit a few things.  👍🤘

**Comment by Mastiffen** [comment]
Seems like the powers that be listened to this, at least that's how I understand this: https://github.com/compose-spec/compose-go/pull/673
