### ISSUE TITLE
LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format

### ISSUE THREAD

**Issue by Nefcanto** [moby/moby#48327]
### Description

I get this error when I run `docker --debug ...` command to build my image:

```
 1 warning found:
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
Legacy key/value format with whitespace separator should not be used
More info: https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
Dockerfile:15
--------------------
  13 |     FROM node:lts-bookworm-slim AS runner
  14 |     WORKDIR /Project/Panel
  15 | >>> ENV NODE_ENV production
  16 |     RUN npm install --location=global serve
  17 |     COPY --from=builder /Project/Panel/dist .
```

As you can see the line being complained about is:

     ENV NODE_ENV production

This line does not have an equal sign in it.

### Reproduce

1. Create a Dockerfile
2. Add `ENV NODE_ENV production` to it
3. Build it

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:14 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /home/saeed/.docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-40-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.5GiB
 Name: local
 ID: 654cdb50-3549-4dc2-a722-ecd2183e7099
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by vvoland** [comment]
It's a linter warning coming from Buildkit builder.
Let me close this issue in favor of https://github.com/moby/buildkit/issues/5130.

**Comment by Nefcanto** [comment]
@vvoland I read that issue. I felt misunderstood. The point is that I have followed the new syntax `ENV key value`, yet I still get the warning. It's a bug. Because sometimes the `key` part contains the word `ENV` all in uppercase.

Or maybe I didn't understand the other issue well.

**Comment by thaJeztah** [comment]
The new format is `key=value`;

>  "ENV key=value" should be used instead of legacy "ENV key value" format

**Comment by Nefcanto** [comment]
@thaJeztah I see. So please let me provide this feedback.

I think it's better to show the problem first, and then the solution. That's how most linters work as much I have experienced. 

I just saw the `warning` and my mind assumed that the first thing that comes after it is the problem.

I know we're supposed to read the whole text, but most developers don't (including me). That's just a suggestion to make the message clearer. Thank you.

**Comment by Nefcanto** [comment]
To be fair, I asked ChatGPT to give me a list of lining messages from known projects, and this is the list. Am I right that most linting messages point to the problem first, and then present the solution? (JS seems to be the opposite)

### JavaScript/TypeScript (ESLint)
1. **no-unused-vars**: `'variableName' is assigned a value but never used.`
2. **no-undef**: `'variableName' is not defined.`
3. **eqeqeq**: `Expected '===' and instead saw '=='.`
4. **no-console**: `Unexpected console statement.`
5. **semi**: `Missing semicolon.`
6. **quotes**: `Strings must use singlequote.`
7. **indent**: `Expected indentation of 2 spaces but found 4.`
8. **no-extra-semi**: `Unnecessary semicolon.`
9. **prefer-const**: `Use 'const' instead of 'let' if the variable is never reassigned.`
10. **no-trailing-spaces**: `Trailing spaces not allowed.`

### Python (Pylint)
1. **missing-module-docstring**: `Missing module docstring.`
2. **unused-import**: `Unused import 'moduleName'.`
3. **too-many-locals**: `Too many local variables.`
4. **line-too-long**: `Line too long (82/80 characters).`
5. **too-many-arguments**: `Too many arguments (6/5).`
6. **invalid-name**: `Variable name "x" doesn't conform to snake_case naming style.`
7. **consider-using-enumerate**: `Consider using 'enumerate' instead of iterating with range and len.`
8. **too-few-public-methods**: `Too few public methods (0/2).`
9. **bad-continuation**: `Continuation line with indent of 4 spaces.`
10. **unnecessary-pass**: `Unnecessary 'pass' statement.`

### C# (StyleCop)
1. **SA1101: PrefixLocalCallsWithThis**: `The call to 'methodName' should be prefixed with 'this.'.`
2. **SA1600: ElementsMustBeDocumented**: `The element 'elementName' must be documented.`
3. **SA1309: FieldNamesMustNotBeginWithUnderscore**: `Field names should not begin with an underscore.`
4. **SA1200: UsingDirectivesMustBePlacedCorrectly**: `Using directives must be placed either at the beginning of the file or within a namespace declaration.`
5. **SA1407: ArithmeticExpressionsMustDeclarePrecedence**: `Arithmetic expressions should declare operator precedence explicitly.`
6. **SA1028: CodeMustNotContainTrailingWhitespace**: `Code must not contain trailing whitespace.`
7. **SA1121: UseBuiltInTypeAlias**: `Use built-in type alias instead of framework type name.`
8. **SA1503: BracesMustNotBeOmitted**: `Braces should not be omitted from multi-line statements.`
9. **SA1516: ElementsMustBeSeparatedByBlankLine**: `Elements must be separated by a blank line.`
10. **SA1116: SplitParametersMustStartOnLineAfterDeclaration**: `Parameter list should start on a new line.`

### CSS (Stylelint)
1. **block-no-empty**: `Unexpected empty block.`
2. **color-no-invalid-hex**: `Invalid hex color "#12345z".`
3. **declaration-block-semicolon-newline-after**: `Expected newline after ";".`
4. **selector-max-id**: `Expected no more than 0 ID selectors.`
5. **no-duplicate-selectors**: `Unexpected duplicate selector ".className".`
6. **property-no-unknown**: `Unexpected unknown property "prop-name".`
7. **declaration-colon-space-after**: `Expected single space after ":".`
8. **no-eol-whitespace**: `Unexpected whitespace at end of line.`
9. **max-nesting-depth**: `Expected nesting depth to be no more than 3.`
10. **selector-class-pattern**: `Expected class selector to match pattern "^[a-z]+[a-zA-Z0-9]+$".`

### Go (Golangci-lint)
1. **errcheck**: `Error return value not checked (errcheck).`
2. **ineffassign**: `Ineffective assignment to 'variableName'.`
3. **deadcode**: `This code is never executed (deadcode).`
4. **gosimple**: `Should use 'value := make([]type, 0, 100)' instead of 'value := make([]type, 100)' (gosimple).`
5. **structcheck**: `Field 'FieldName' is unused.`
6. **typecheck**: `Cannot use 'variable' (type int) as type string.`
7. **govet**: `Possible formatting directive in Printf call.`
8. **staticcheck**: `This value of 'variable' is never used.`
9. **misspell**: `This word is misspelled.`
10. **stylecheck**: `Comment should begin with a capital letter.`

### HTML (HTMLHint)
1. **tag-pair**: `Tag must be paired, missing: [end tag].`
2. **attr-lowercase**: `Attribute name must be in lowercase.`
3. **attr-value-double-quotes**: `Attribute value must be enclosed in double quotes.`
4. **id-unique**: `ID 'elementID' must be unique.`
5. **spec-char-escape**: `Special characters must be escaped.`
6. **src-not-empty**: `Src attribute of image must not be empty.`
7. **tagname-lowercase**: `Tag name must be in lowercase.`
8. **doctype-first**: `Doctype must be the first element in the document.`
9. **head-script-disabled**: `The script tag cannot be used inside the head tag.`
10. **img-alt-require**: `The alt attribute of an image tag must be set.`

**Comment by thaJeztah** [comment]
I'd recommend either commenting that on https://github.com/moby/buildkit/issues/5130 or a separate ticket in the BuildKit repository, because that's where the builder code (including parsing Dockerfiles) is maintained.

**Comment by tonistiigi** [comment]
@Nefcanto If you have a proposal/PR for improving the message you can submit that for consideration. I don't think there is any rule about the word order(as also visible from your example set) and it depends on the meaning of the sentence.

**Comment by thaJeztah** [comment]
Using active voice would probably be good ("use X" instead of "X should be used").

Perhaps more along the lines how we format `Deprecated:` messages in our Go codebase, e.g.;


```console
LegacyKeyValueFormat: The "ENV key value" format is deprecated. Use "ENV key value" format instead.
```

Not sure where to fit in the `line 15` though;

```console
LegacyKeyValueFormat: The "ENV key value" format is deprecated. Use "ENV key value" format instead. (line 15)
```

I'm used to linters pointing out the issue inline, but not sure if possible, and not sure if that could make the output more noisy / harder to read if it's in more complex parts of a Dockerfile;

```console
Dockerfile:15: The "ENV key value" format is deprecated. Use "ENV key value" format instead (LegacyKeyValueFormat).
ENV NODE_ENV production
    ^
```

I guess that's the intent of the current output, which may work well for a single error, but with the "lines before / after" becomes quite verbose, and also puts a lot of separation between the error and the line containing the error / issue.


I can comment on the other ticket.
