### ISSUE TITLE
Docker build failed with apt-get from ubuntu22.04 container image

### ISSUE THREAD

**Issue by geotransformer** [moby/moby#48410]
### Description

Docker build failed with apt-get from ubuntu22.04. Would like to know the analysis from Docker team.
See https://stackoverflow.com/questions/73699753/the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-avai

### Workaround
Upgrade docker version with the instruction from docker documentation https://docs.docker.com/engine/install/ubuntu/

### Reproduce

see https://stackoverflow.com/questions/73699753/the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-avai

### docker version

```bash
"19.03.11"
```

### docker info

```bash
"19.03.11"
```

### Additional Info

Ubuntu 18.04

**Comment by thaJeztah** [comment]
Yes, it's possible that the ubuntu 22.04 image attempts to make syscalls that are not handled on the older host or not supported by seccomp on the older docker version.

Docker 19.03 is a 5 year old version of docker and no longer maintained and Ubuntu 18.04 reached EOL in May of last year, and docker no longer provides updated packages for it.

If possible, I'd highly recommend upgrading your environment to a supported version.

**Comment by geotransformer** [comment]
> Yes, it's possible that the ubuntu 22.04 image attempts to make syscalls that are not handled on the older host or not supported by seccomp on the older docker version.
> 
> Docker 19.03 is a 5 year old version of docker and no longer maintained and Ubuntu 18.04 reached EOL in May of last year, and docker no longer provides updated packages for it.
> 
> If possible, I'd highly recommend upgrading your environment to a supported version.

Thanks for the prompt reply. Upgrade the docker to latest does fix the issue.

```ubuntu@dev:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:13 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
ubuntu@dev:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

**Comment by thaJeztah** [comment]
Thanks! Yes, let me go ahead and close this one, as it looks to be addressed by more current versions of docker
