### ISSUE TITLE
Filtered packets between containers in bridged network after upgrade

### ISSUE THREAD

**Issue by Tony763** [moby/moby#48411]
### Description

Hi, I have similar problem to #48375.  After upgrading to 27.2.0. My containers cannot reach each others. Before update, everything worked. Oddly only ping now works, everything else is filtered.

```
networks:
  lan:
     name: hass
     driver: bridge
     ipam:
       config:
         - subnet: "10.1.5.0/24"
           gateway: "10.1.5.1"
     driver_opts:
       com.docker.network.bridge.name: hass
       com.docker.network.bridge.enable_icc: "true"
```
Server container:  
```
networks:
      lan:
        ipv4_address: 10.1.5.2
```
Client container:
```
networks:
      lan:
        ipv4_address: 10.1.5.3
```

Running nc on server container, sending packets from host works, but sending them from Client container not:
![image](https://github.com/user-attachments/assets/0bee5e5b-2849-445d-b454-a72305bcc3b0)

### Reproduce

Start two containers with same bridged network.
Try to open port on one of them (`nc -l ....`)
Try to send packets from host (works)
Try to send packets from second container (don't work)

### Expected behavior

As both containers are in same bridged network (same subnet - L2) with `enabled_icc: "true"`, they should be able to communicate with each other without any changes to hosts firewall rules (communication go directly between them).

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:15:15 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: syslog
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.9.8-x64v3-xanmod1
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.46GiB
 Name: ares
 ID: 2d1963cd-6189-4bc3-9702-197687bec6fa
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Ubuntu server 24.04
nftables v1.0.9

**Comment by Tony763** [comment]
NFTable rules
```bash
add rule ip filter INPUT iifname "hass" ct state established,related counter accept
add rule ip filter FORWARD iifname "hass" oifname "lan"  counter accept
add rule ip filter FORWARD iifname "lan" oifname "hass" counter accept
add rule ip filter FORWARD iifname "wg" oifname "hass" counter accept
add rule ip filter FORWARD iifname "hass" oifname "wg0"  counter accept
add rule ip nat PREROUTING iifname {"lan","wg"} tcp dport 8123 counter dnat 10.1.5.2:8123
add rule ip nat POSTROUTING iifname "hass" oifname  {"lan","wg"} counter masquerade

```

**Comment by Tony763** [comment]
Hi @robmry, these two commands no longer work.
```bash
tony@ares:~$ sudo iptables -nvL
iptables v1.8.10 (nf_tables): table `filter' is incompatible, use 'nft' tool.
tony@ares:~$ sudo iptables -nvL -t nat
iptables v1.8.10 (nf_tables): table `nat' is incompatible, use 'nft' tool.
````

`daemon.json` look like this (I did not touch it for almost two years)
```json
{
"iptables":false,
"log-driver": "syslog",
"log-opts": {
  "syslog-address": "unixgram:///dev/log",
  "tag" : "docker/{{.Name}}"
  }
}
```

nft rules (removed unrelated rules):

```bash
tony@ares:~$ sudo nft list ruleset
table ip mangle {
	chain PREROUTING {
		type filter hook prerouting priority mangle; policy accept;
	}

	chain INPUT {
		type filter hook input priority mangle; policy accept;
	}

	chain FORWARD {
		type filter hook forward priority mangle; policy accept;
	}

	chain OUTPUT {
		type route hook output priority mangle; policy accept;
	}

	chain POSTROUTING {
		type filter hook postrouting priority mangle; policy accept;
	}
}
table ip filter {
	chain INPUT {
		type filter hook input priority filter; policy drop;
		ip protocol icmp counter packets 53948 bytes 5920101 accept
	
		iifname "docker0" accept
	
		iifname "hass" ct state established,related counter packets 0 bytes 0 accept
		log prefix "[nftables] Inbound Denied: " counter packets 138795 bytes 25792832 drop
	}

	chain FORWARD {
		type filter hook forward priority filter; policy drop;
		ip protocol icmp counter packets 64948 bytes 4565650 accept
		iifname "docker0" counter packets 1749 bytes 223328 accept
		oifname "docker0" ct state established,related accept
		iifname "docker0" accept
		
		iifname "hass" oifname "lan" counter packets 226693 bytes 41930811 accept
		iifname "lan" oifname "hass" counter packets 0 bytes 0 accept
		iifname "hass" oifname "wan" counter packets 20616076 bytes 22349788939 accept
		iifname "wan" oifname "hass" ct state established,related counter packets 0 bytes 0 accept
		iifname "wg" oifname "hass" counter packets 0 bytes 0 accept
		iifname "hass" oifname "wg" counter packets 229 bytes 109561 accept
		
		log prefix "[nftables] Forward Denied: " counter packets 20932 bytes 1293312 drop
	}

	chain OUTPUT {
		type filter hook output priority filter; policy accept;
	}

	chain DOCKER {
	}

	chain DOCKER-ISOLATION-STAGE-1 {
	}

	chain DOCKER-ISOLATION-STAGE-2 {
	}

	chain DOCKER-USER {
	}
}
table ip nat {
	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;

		iifname { "wg", "lan" } tcp dport 8123 counter packets 672 bytes 42964 dnat to 10.1.5.2:8123
	}

	chain INPUT {
		type nat hook input priority srcnat; policy accept;
	}

	chain OUTPUT {
		type nat hook output priority dstnat; policy accept;
	}

	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;

		iifname "hass" oifname "lan" counter packets 55245 bytes 24717084 masquerade
		iifname "hass" oifname "wan" counter packets 0 bytes 0 masquerade
	}
}
```

**Comment by robmry** [comment]
With `iptables` disabled, I'd expect [things to be a bit broken](https://docs.docker.com/engine/network/packet-filtering-firewalls/#prevent-docker-from-manipulating-iptables). But, if `iptables-nft` doesn't work I guess you don't have the option of trying with `"iptables": true`. (I'm not sure why it doesn't work though, it's fine for me on an Ubuntu 24.04.1 LTS.)

But, two containers attached to the same bridge should be able to talk to each other. So, it'll be a case of working out where packets are going missing ...

You could try watching the `nft list ruleset` output to see if any of the drop counters are incrementing when the containers try to send packets to each other. Running tcpdump on the bridge and veth interfaces might also provide some clues.

It might be worth checking whether an older version of docker still works - if not, I guess it points at some change on the host, otherwise it might be interesting to compare working and broken network configs to try to spot a difference.

**Comment by Tony763** [comment]
Downgrading to version `26.1.4` fixes problem.

**Comment by robmry** [comment]
> Downgrading to version `26.1.4` fixes problem.
> ...
> Fixing problem seems to be adding nft rule `ip filter FORWARD iifname "hass" oifname "hass" counter accept` which I find quite odd that packets between containers need to exit host interface and go back.

Ok, thank you. Unfortunately, I'm still quite mystified by this.

I can't see any way docker would to try to create that rule with `"iptables": false` in 26.1.4 (or 27.2.0) and, even if it tried, I don't think it would be able to without `iptables` (`iptables-nft`) working.

To make progress - a minimal way to repro might help, with exact config and commands, and in case it still won't repro on my host [debug-level engine logs](https://docs.docker.com/engine/daemon/logs/#enable-debugging) as they record the iptables rules.

**Comment by robmry** [comment]
Hi @Tony763 - I think you were right, this is the same issue as https://github.com/moby/moby/issues/48375.

As noted in https://github.com/moby/moby/issues/48375#issuecomment-2346359640 - kernel module `br_netfilter`gets loaded if either `iptables` or `ip6tables` are enabled, and loading the module automatically enables filtering for both protocols.

Because you have a default-drop rule for forwarding, packets between containers on one bridge network get dropped ...

```
table ip filter {
	...
	chain FORWARD {
		...
		log prefix "[nftables] Forward Denied: " counter packets 20932 bytes 1293312 drop
	}
```

So, with `iptables` disabled, the change to enable `ip6tables` by default broke things ... setting`"ip6tables": false` as well as `"iptables": false` in your `daemon.json` should work around the problem.

**Comment by Tony763** [comment]
Hi @robmry, adding `"iptables": false` and removing rule for forwarding fixed communication between containers. Thanks

**Comment by robmry** [comment]
> Hi @robmry, adding `"ip6tables": false` and removing rule for forwarding fixed communication between containers. Thanks

Great! Thank you for the update.
