### ISSUE TITLE
Docker pull limit for Docker Pro members

### ISSUE THREAD

**Issue by shalini2385** [moby/moby#48420]
### Description

Hi 
Being a part of Docker pro , i wanted to look for the docker pull limits left for my plan nd create alerts based on the details.
As the document [Docker Hub Rate Limit Documentation](https://docs.docker.com/docker-hub/download-rate-limit/#how-can-i-check-my-current-rate). doesnt help in my case. can you please have some APIs setup to look for the rate limit remaining and utilised details for Pro members.

Also, i don find these details either in UI with the billing / profile, which should have been a basic and minimum as part of the plan to look for the utilized and utilized data/limits 

Curl command output:
curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/library/ubuntu/manifests/latest
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
content-length: 1338
content-type: application/vnd.oci.image.index.v1+json
docker-content-digest: sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee
docker-distribution-api-version: registry/2.0
etag: "sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee"
date: Thu, 29 Aug 2024 08:50:14 GMT
strict-transport-security: max-age=31536000
docker-ratelimit-source: a645ce4d-4328-42eb-8241-1624241605ef

**Comment by laurazard** [comment]
Hiya @shalini2385, thanks for the report.

This issue doesn't directly pertain to https://github.com/moby/moby, and you're more likely to get a reply/relevant eyes on it by submitting it over in https://github.com/docker/roadmap/issues.

Closing this one, but feel free to open another one in another repo!
