### ISSUE TITLE
Fail to run the Engine SDK example due to wrong errors package imported

### ISSUE THREAD

**Issue by ChocolateAceCream** [moby/moby#48618]
### Description

Fail to run the Engine SDK example

../go/pkg/mod/github.com/docker/docker@v27.3.1+incompatible/client/errors.go:28:16: undefined: errors.As
../go/pkg/mod/github.com/docker/docker@v27.3.1+incompatible/client/request.go:127:14: undefined: errors.Is
../go/pkg/mod/github.com/docker/docker@v27.3.1+incompatible/client/request.go:129:14: undefined: errors.Is
../go/pkg/mod/github.com/docker/docker@v27.3.1+incompatible/client/request.go:153:13: undefined: errors.Is

with github.com/docker/docker v27.3.1+incompatible

### Reproduce

go run main.go

### docker version

Client:
  Version:           20.10.17
  API version:       1.41
  Go version:        go1.17.11
  Git commit:        100c70180fde3601def79a59cc3e996aa553c9b9
  Built:             Mon Jun  6 21:36:39 UTC 2022
  OS/Arch:           linux/amd64
  Context:           default
  Experimental:      true

Server:
  Engine:
    Version:          20.10.17
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.17.11
    Git commit:       a89b84221c8560e7a3dee2a653353429e7628424
    Built:            Mon Jun  6 22:32:38 2022
    OS/Arch:          linux/amd64
    Experimental:     true
  containerd:
    Version:          1.6.6
    GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  runc:
    Version:          1.1.2
    GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
  docker-init:
    Version:          0.19.0
    GitCommit:

### docker info

Client:
  Context:    default
  Debug Mode: false
  Plugins:
    buildx: Docker Buildx (Docker Inc., 0.8.2)
    compose: Docker Compose (Docker Inc., 2.6.0)

Server:
  Containers: 4
    Running: 2
    Paused: 0
    Stopped: 2
  Images: 80
  Server Version: 20.10.17
  Storage Driver: overlay2
    Backing Filesystem: xfs
    Supports d_type: true
    Native Overlay Diff: false
    userxattr: false
  Logging Driver: local
  Cgroup Driver: cgroupfs
  Cgroup Version: 1
  Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Swarm: inactive
  Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  runc version: a916309fff0f838eb94e928713dbc3c0d0ac7aa4
  init version: 
  Security Options:
    apparmor
    seccomp
    Profile: default
  Kernel Version: 5.13.0-1031-azure
  Operating System: Ubuntu 20.04.4 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 4
  Total Memory: 15.63GiB
  Name: dev
  ID: UC44:2RFL:7NQ5:GGFW:34O5:DYRE:CLOH:VLGZ:64AZ:GFXC:PY6H:SAHY
  Docker Root Dir: /var/lib/docker
  Debug Mode: true
    File Descriptors: 46
    Goroutines: 134
    System Time: 2022-07-06T18:07:54.812439392Z
    EventsListeners: 0
  Registry: https://index.docker.io/v1/
  Labels:
  Experimental: true
  Insecure Registries:
    127.0.0.0/8
  Live Restore Enabled: true

### Additional Info

The bug is caused because "github.com/pkg/errors" is used instead of "error"
In request.go, both errors.Is and errors.Wrap are used, so both "github.com/pkg/errors" and "error" should be imported. Not sure how this passed test though. 
I will create a pull request to fix the issue.

**Comment by ChocolateAceCream** [comment]
I was using github.com/pkg/errors v0.8.1, and update to github.com/pkg/errors v0.9.1 solved the issue.
BTW, is there any special reason why using github.com/pkg/errors ? I guess the only reason here for using it is to support older go versions?

**Comment by thaJeztah** [comment]
Yes, it's important to match dependency versions with  what's defined in our vendor.mod;

https://github.com/moby/moby/blob/41ca978a0a5400cc24b274137efa9f25517fcc0b/vendor.mod#L87

We don't have a go.mod yet, so unfortunately getting the correct versions is still manual in some cases.

> BTW, is there any special reason why using github.com/pkg/errors ? I guess the only reason here for using it is to support older go versions?

The pkg/errors modules provides some features that are not provided by Go stdlib, and some of those are essential for BuildKit; longer discussion can be found here;

- https://github.com/moby/moby/discussions/46358

**Comment by thaJeztah** [comment]
I'll close this ticket per the above, but feel free to continue the conversation

**Comment by cgf120** [comment]
> 我之前使用的是 github.com/pkg/errors v0.8.1，更新到 github.com/pkg/errors v0.9.1 后问题解决了。 顺便问一下，使用 github.com/pkg/errors 有什么特殊原因吗？我猜这里使用它的唯一原因是为了支持老版本的 Go 代码？

very good
