### ISSUE TITLE
Regarding the issue of Capability

### ISSUE THREAD

**Issue by GuoYingLong** [moby/moby#48845]
### Description

Will the Capability configuration in moby be removed from the runtime? How can I default to using the Capabilities configuration in the runtime instead of the default configuration in moby?

**Comment by coolljt0725** [comment]
What kind of runtime do you use ?  Capability configuration is part of OCI runtime spec. I think the runtime just use the OCI spec generated by the client. In this case, the moby create the OCI spec for the container, and the runtime just use it.

**Comment by thaJeztah** [comment]
I saw you also opened a discussion. I also have the same question, as it's not 100% clear what exactly you're asking (perhaps you could describe the problem a bit more?)

- https://github.com/moby/moby/discussions/48837

**Comment by GuoYingLong** [comment]
Before starting Docker, I set the Capabilities using AKS capabilities. Adding any Capability parameter does not take effect and can only be done using -- cap add | -- cap drop during Docker run. Is that correct?

Here is the code for me to add cap:
```go
func SetCapabilities(s *specs.Spec, caplist []string) error {
	if s.Process == nil {
		s.Process = &specs.Process{}
	}
	s.Process.Capabilities = &specs.LinuxCapabilities{
		Effective: caplist,
		Bounding:  caplist,
		Permitted: caplist,
	}
	return nil
}
```

**Comment by GuoYingLong** [comment]
Before I start docker, I use SetCapabilities to set Capabilities, but adding any Capabilities parameters does not work. I can only use --cap-add | --cap-drop during docker run to do it. Is that right?

Below is the code I used to add cap
```go
func SetCapabilities(s *specs.Spec, caplist []string) error {
	if s.Process == nil {
		s.Process = &specs.Process{}
	}
	s.Process.Capabilities = &specs.LinuxCapabilities{
		Effective: caplist,
		Bounding:  caplist,
		Permitted: caplist,
	}
	return nil
}
```

**Comment by GuoYingLong** [comment]
> What kind of runtime do you use ? Capability configuration is part of OCI runtime spec. I think the runtime just use the OCI spec generated by the client. In this case, the moby create the OCI spec for the container, and the runtime just use it.

Yes, in theory, the Capability in OCI Runtime should be modifiable or updated, but I don't quite understand why the runtime update cannot be used in Docker? Or what operations need to be done? The code I tested and updated is below.

**Comment by coolljt0725** [comment]
> Before I start docker, I use SetCapabilities to set Capabilities, but adding any Capabilities parameters does not work. I can only use --cap-add | --cap-drop during docker run to do it. Is that right?
> 
> Below is the code I used to add cap
> 
> func SetCapabilities(s *specs.Spec, caplist []string) error {
> 	if s.Process == nil {
> 		s.Process = &specs.Process{}
> 	}
> 	s.Process.Capabilities = &specs.LinuxCapabilities{
> 		Effective: caplist,
> 		Bounding:  caplist,
> 		Permitted: caplist,
> 	}
> 	return nil
> }
> Actually, what I want to know is whether I can modify the Capabilities configuration in docker when using the runtime I developed myself. I am currently in the testing process and cannot modify it. I have actually added it in: /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json, but the docker container does not take effect. I have been stuck on this for many days. Can you help me solve this problem? Thank you very much.

` /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json` is not the OCI spec file of the container. If you are using containerd, the OCI spec file is `/run/containerd/io.containerd.runtime.v2.task/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/config.json`, this should be something you want to change.  

Close the issue since it's not a docker issue.

**Comment by GuoYingLong** [comment]
> > Before I start docker, I use SetCapabilities to set Capabilities, but adding any Capabilities parameters does not work. I can only use --cap-add | --cap-drop during docker run to do it. Is that right?
> > Below is the code I used to add cap
> > func SetCapabilities(s *specs.Spec, caplist []string) error {
> > if s.Process == nil {
> > s.Process = &specs.Process{}
> > }
> > s.Process.Capabilities = &specs.LinuxCapabilities{
> > Effective: caplist,
> > Bounding:  caplist,
> > Permitted: caplist,
> > }
> > return nil
> > }
> > Actually, what I want to know is whether I can modify the Capabilities configuration in docker when using the runtime I developed myself. I am currently in the testing process and cannot modify it. I have actually added it in: /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json, but the docker container does not take effect. I have been stuck on this for many days. Can you help me solve this problem? Thank you very much.
> 
> ` /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json` is not the OCI spec file of the container. If you are using containerd, the OCI spec file is `/run/containerd/io.containerd.runtime.v2.task/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/config.json`, this should be something you want to change.
> 
> Close the issue since it's not a docker issue.

```shell
 cat /run/containerd/io.containerd.runtime.v2.task/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/config.json

{
    "ociVersion": "1.2.0",
    "process": {
        "terminal": true,
        "user": {
            "uid": 0,
            "gid": 0,
            "additionalGids": [
                0
            ]
        },
        "args": [
            "bash"
        ],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOSTNAME=8d80e02bb405",
            "TERM=xterm",
            "TASK_ID=cf4b40b1da85",
            "REGION_ID=1",
            "JUPYTER_PASSWD=",
            "NVIDIA_VISIBLE_DEVICES=none"
        ],
        "cwd": "/",
        "capabilities": {
            "bounding": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_DAC_READ_SEARCH",
                "CAP_FOWNER",
                "CAP_FSETID",
                "CAP_KILL",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETPCAP",
                "CAP_LINUX_IMMUTABLE",
                "CAP_NET_BIND_SERVICE",
                "CAP_NET_BROADCAST",
                "CAP_NET_ADMIN",
                "CAP_NET_RAW",
                "CAP_IPC_LOCK",
                "CAP_IPC_OWNER",
                "CAP_SYS_MODULE",
                "CAP_SYS_RAWIO",
                "CAP_SYS_CHROOT",
                "CAP_SYS_PTRACE",
                "CAP_SYS_PACCT",
                "CAP_SYS_ADMIN",
                "CAP_SYS_BOOT",
                "CAP_SYS_NICE",
                "CAP_SYS_RESOURCE",
                "CAP_SYS_TIME",
                "CAP_SYS_TTY_CONFIG",
                "CAP_MKNOD",
                "CAP_LEASE",
                "CAP_AUDIT_WRITE",
                "CAP_AUDIT_CONTROL",
                "CAP_SETFCAP",
                "CAP_MAC_OVERRIDE",
                "CAP_MAC_ADMIN",
                "CAP_SYSLOG",
                "CAP_WAKE_ALARM",
                "CAP_BLOCK_SUSPEND",
                "CAP_AUDIT_READ",
                "CAP_PERFMON",
                "CAP_BPF",
                "CAP_CHECKPOINT_RESTORE"
            ],
            "effective": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_DAC_READ_SEARCH",
                "CAP_FOWNER",
                "CAP_FSETID",
                "CAP_KILL",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETPCAP",
                "CAP_LINUX_IMMUTABLE",
                "CAP_NET_BIND_SERVICE",
                "CAP_NET_BROADCAST",
                "CAP_NET_ADMIN",
                "CAP_NET_RAW",
                "CAP_IPC_LOCK",
                "CAP_IPC_OWNER",
                "CAP_SYS_MODULE",
                "CAP_SYS_RAWIO",
                "CAP_SYS_CHROOT",
                "CAP_SYS_PTRACE",
                "CAP_SYS_PACCT",
                "CAP_SYS_ADMIN",
                "CAP_SYS_BOOT",
                "CAP_SYS_NICE",
                "CAP_SYS_RESOURCE",
                "CAP_SYS_TIME",
                "CAP_SYS_TTY_CONFIG",
                "CAP_MKNOD",
                "CAP_LEASE",
                "CAP_AUDIT_WRITE",
                "CAP_AUDIT_CONTROL",
                "CAP_SETFCAP",
                "CAP_MAC_OVERRIDE",
                "CAP_MAC_ADMIN",
                "CAP_SYSLOG",
                "CAP_WAKE_ALARM",
                "CAP_BLOCK_SUSPEND",
                "CAP_AUDIT_READ",
                "CAP_PERFMON",
                "CAP_BPF",
                "CAP_CHECKPOINT_RESTORE"
            ],
            "permitted": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_DAC_READ_SEARCH",
                "CAP_FOWNER",
                "CAP_FSETID",
                "CAP_KILL",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETPCAP",
                "CAP_LINUX_IMMUTABLE",
                "CAP_NET_BIND_SERVICE",
                "CAP_NET_BROADCAST",
                "CAP_NET_ADMIN",
                "CAP_NET_RAW",
                "CAP_IPC_LOCK",
                "CAP_IPC_OWNER",
                "CAP_SYS_MODULE",
                "CAP_SYS_RAWIO",
                "CAP_SYS_CHROOT",
                "CAP_SYS_PTRACE",
                "CAP_SYS_PACCT",
                "CAP_SYS_ADMIN",
                "CAP_SYS_BOOT",
                "CAP_SYS_NICE",
                "CAP_SYS_RESOURCE",
                "CAP_SYS_TIME",
                "CAP_SYS_TTY_CONFIG",
                "CAP_MKNOD",
                "CAP_LEASE",
                "CAP_AUDIT_WRITE",
                "CAP_AUDIT_CONTROL",
                "CAP_SETFCAP",
                "CAP_MAC_OVERRIDE",
                "CAP_MAC_ADMIN",
                "CAP_SYSLOG",
                "CAP_WAKE_ALARM",
                "CAP_BLOCK_SUSPEND",
                "CAP_AUDIT_READ",
                "CAP_PERFMON",
                "CAP_BPF",
                "CAP_CHECKPOINT_RESTORE"
            ]
        },
        "oomScoreAdj": 0
    },
    "root": {
        "path": "/var/lib/docker/overlay2/ab8d27d3f9a0369b112c6c69088ef76b09fa5d427570dec5b785e3d98782ad80/merged"
    },
    "hostname": "cf4b40b1da85",
    "mounts": [
        {
            "destination": "/proc",
            "type": "proc",
            "source": "proc",
            "options": [
                "nosuid",
                "noexec",
                "nodev"
            ]
        },
        {
            "destination": "/dev",
            "type": "tmpfs",
            "source": "tmpfs",
            "options": [
                "nosuid",
                "strictatime",
                "mode=755",
                "size=65536k"
            ]
        },
        {
            "destination": "/dev/pts",
            "type": "devpts",
            "source": "devpts",
            "options": [
                "nosuid",
                "noexec",
                "newinstance",
                "ptmxmode=0666",
                "mode=0620",
                "gid=5"
            ]
        },
        {
            "destination": "/sys",
            "type": "sysfs",
            "source": "sysfs",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "ro"
            ]
        },
        {
            "destination": "/sys/fs/cgroup",
            "type": "cgroup",
            "source": "cgroup",
            "options": [
                "ro",
                "nosuid",
                "noexec",
                "nodev"
            ]
        },
        {
            "destination": "/dev/mqueue",
            "type": "mqueue",
            "source": "mqueue",
            "options": [
                "nosuid",
                "noexec",
                "nodev"
            ]
        },
        {
            "destination": "/dev/shm",
            "type": "tmpfs",
            "source": "shm",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "mode=1777",
                "size=67108864"
            ]
        },
        {
            "destination": "/etc/resolv.conf",
            "type": "bind",
            "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/resolv.conf",
            "options": [
                "rbind",
                "rprivate"
            ]
        },
        {
            "destination": "/etc/hostname",
            "type": "bind",
            "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/hostname",
            "options": [
                "rbind",
                "rprivate"
            ]
        },
        {
            "destination": "/etc/hosts",
            "type": "bind",
            "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/hosts",
            "options": [
                "rbind",
                "rprivate"
            ]
        }
    ],
    "hooks": {
        "prestart": [
            {
                "path": "/proc/200460/exe",
                "args": [
                    "libnetwork-setkey",
                    "-exec-root=/var/run/docker",
                    "8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
                    "e3ee660a43f5"
                ]
            }
        ],
        "createRuntime": [
            {
                "path": "/usr/bin/nvidia-container-runtime-hook",
                "args": [
                    "nvidia-container-runtime-hook",
                    "prestart"
                ],
                "env": [
                    "LANG=en_US.UTF-8",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin",
                    "NOTIFY_SOCKET=/run/systemd/notify",
                    "TMPDIR=/var/lib/docker/tmp"
                ]
            }
        ],
        "poststop": [
            {
                "path": "/opt/sitonai/share/agent/sitonai-agent-Linux-x86_64",
                "args": [
                    "sitonai-agent-Linux-x86_64",
                    "stop_hook"
                ],
                "env": [
                    "ContainerID=8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
                    "REGION_ID=1",
                    "TASK_ID=cf4b40b1da85",
                    "Forwarding_Mode=proxy"
                ]
            }
        ]
    },
    "linux": {
        "sysctl": {
            "net.ipv4.ip_unprivileged_port_start": "0",
            "net.ipv4.ping_group_range": "0 2147483647"
        },
        "resources": {
            "devices": [
                {
                    "allow": false,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 5,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 3,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 9,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 8,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 5,
                    "minor": 0,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 5,
                    "minor": 1,
                    "access": "rwm"
                },
                {
                    "allow": false,
                    "type": "c",
                    "major": 10,
                    "minor": 229,
                    "access": "rwm"
                },
                {
                    "allow": false,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 5,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 3,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 9,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 1,
                    "minor": 8,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 5,
                    "minor": 0,
                    "access": "rwm"
                },
                {
                    "allow": true,
                    "type": "c",
                    "major": 5,
                    "minor": 1,
                    "access": "rwm"
                },
                {
                    "allow": false,
                    "type": "c",
                    "major": 10,
                    "minor": 229,
                    "access": "rwm"
                }
            ],
            "memory": {
                "disableOOMKiller": false
            },
            "blockIO": {}
        },
        "cgroupsPath": "/docker/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
        "namespaces": [
            {
                "type": "mount"
            },
            {
                "type": "network"
            },
            {
                "type": "uts"
            },
            {
                "type": "pid"
            },
            {
                "type": "ipc"
            }
        ],
        "maskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware",
            "/sys/devices/virtual/powercap"
        ],
        "readonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ]
    }
}
```
config.json has also been updated, but there is still no corresponding cap permission in the container

**Comment by coolljt0725** [comment]
> > > Before I start docker, I use SetCapabilities to set Capabilities, but adding any Capabilities parameters does not work. I can only use --cap-add | --cap-drop during docker run to do it. Is that right?
> > > Below is the code I used to add cap
> > > func SetCapabilities(s *specs.Spec, caplist []string) error {
> > > if s.Process == nil {
> > > s.Process = &specs.Process{}
> > > }
> > > s.Process.Capabilities = &specs.LinuxCapabilities{
> > > Effective: caplist,
> > > Bounding:  caplist,
> > > Permitted: caplist,
> > > }
> > > return nil
> > > }
> > > Actually, what I want to know is whether I can modify the Capabilities configuration in docker when using the runtime I developed myself. I am currently in the testing process and cannot modify it. I have actually added it in: /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json, but the docker container does not take effect. I have been stuck on this for many days. Can you help me solve this problem? Thank you very much.
> > 
> > 
> > ` /run/docker/runtime-runc/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/state.json` is not the OCI spec file of the container. If you are using containerd, the OCI spec file is `/run/containerd/io.containerd.runtime.v2.task/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/config.json`, this should be something you want to change.
> > Close the issue since it's not a docker issue.
> 
>  cat /run/containerd/io.containerd.runtime.v2.task/moby/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/config.json
> 
> {
>     "ociVersion": "1.2.0",
>     "process": {
>         "terminal": true,
>         "user": {
>             "uid": 0,
>             "gid": 0,
>             "additionalGids": [
>                 0
>             ]
>         },
>         "args": [
>             "bash"
>         ],
>         "env": [
>             "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>             "HOSTNAME=8d80e02bb405",
>             "TERM=xterm",
>             "TASK_ID=cf4b40b1da85",
>             "REGION_ID=1",
>             "JUPYTER_PASSWD=",
>             "NVIDIA_VISIBLE_DEVICES=none"
>         ],
>         "cwd": "/",
>         "capabilities": {
>             "bounding": [
>                 "CAP_CHOWN",
>                 "CAP_DAC_OVERRIDE",
>                 "CAP_DAC_READ_SEARCH",
>                 "CAP_FOWNER",
>                 "CAP_FSETID",
>                 "CAP_KILL",
>                 "CAP_SETGID",
>                 "CAP_SETUID",
>                 "CAP_SETPCAP",
>                 "CAP_LINUX_IMMUTABLE",
>                 "CAP_NET_BIND_SERVICE",
>                 "CAP_NET_BROADCAST",
>                 "CAP_NET_ADMIN",
>                 "CAP_NET_RAW",
>                 "CAP_IPC_LOCK",
>                 "CAP_IPC_OWNER",
>                 "CAP_SYS_MODULE",
>                 "CAP_SYS_RAWIO",
>                 "CAP_SYS_CHROOT",
>                 "CAP_SYS_PTRACE",
>                 "CAP_SYS_PACCT",
>                 "CAP_SYS_ADMIN",
>                 "CAP_SYS_BOOT",
>                 "CAP_SYS_NICE",
>                 "CAP_SYS_RESOURCE",
>                 "CAP_SYS_TIME",
>                 "CAP_SYS_TTY_CONFIG",
>                 "CAP_MKNOD",
>                 "CAP_LEASE",
>                 "CAP_AUDIT_WRITE",
>                 "CAP_AUDIT_CONTROL",
>                 "CAP_SETFCAP",
>                 "CAP_MAC_OVERRIDE",
>                 "CAP_MAC_ADMIN",
>                 "CAP_SYSLOG",
>                 "CAP_WAKE_ALARM",
>                 "CAP_BLOCK_SUSPEND",
>                 "CAP_AUDIT_READ",
>                 "CAP_PERFMON",
>                 "CAP_BPF",
>                 "CAP_CHECKPOINT_RESTORE"
>             ],
>             "effective": [
>                 "CAP_CHOWN",
>                 "CAP_DAC_OVERRIDE",
>                 "CAP_DAC_READ_SEARCH",
>                 "CAP_FOWNER",
>                 "CAP_FSETID",
>                 "CAP_KILL",
>                 "CAP_SETGID",
>                 "CAP_SETUID",
>                 "CAP_SETPCAP",
>                 "CAP_LINUX_IMMUTABLE",
>                 "CAP_NET_BIND_SERVICE",
>                 "CAP_NET_BROADCAST",
>                 "CAP_NET_ADMIN",
>                 "CAP_NET_RAW",
>                 "CAP_IPC_LOCK",
>                 "CAP_IPC_OWNER",
>                 "CAP_SYS_MODULE",
>                 "CAP_SYS_RAWIO",
>                 "CAP_SYS_CHROOT",
>                 "CAP_SYS_PTRACE",
>                 "CAP_SYS_PACCT",
>                 "CAP_SYS_ADMIN",
>                 "CAP_SYS_BOOT",
>                 "CAP_SYS_NICE",
>                 "CAP_SYS_RESOURCE",
>                 "CAP_SYS_TIME",
>                 "CAP_SYS_TTY_CONFIG",
>                 "CAP_MKNOD",
>                 "CAP_LEASE",
>                 "CAP_AUDIT_WRITE",
>                 "CAP_AUDIT_CONTROL",
>                 "CAP_SETFCAP",
>                 "CAP_MAC_OVERRIDE",
>                 "CAP_MAC_ADMIN",
>                 "CAP_SYSLOG",
>                 "CAP_WAKE_ALARM",
>                 "CAP_BLOCK_SUSPEND",
>                 "CAP_AUDIT_READ",
>                 "CAP_PERFMON",
>                 "CAP_BPF",
>                 "CAP_CHECKPOINT_RESTORE"
>             ],
>             "permitted": [
>                 "CAP_CHOWN",
>                 "CAP_DAC_OVERRIDE",
>                 "CAP_DAC_READ_SEARCH",
>                 "CAP_FOWNER",
>                 "CAP_FSETID",
>                 "CAP_KILL",
>                 "CAP_SETGID",
>                 "CAP_SETUID",
>                 "CAP_SETPCAP",
>                 "CAP_LINUX_IMMUTABLE",
>                 "CAP_NET_BIND_SERVICE",
>                 "CAP_NET_BROADCAST",
>                 "CAP_NET_ADMIN",
>                 "CAP_NET_RAW",
>                 "CAP_IPC_LOCK",
>                 "CAP_IPC_OWNER",
>                 "CAP_SYS_MODULE",
>                 "CAP_SYS_RAWIO",
>                 "CAP_SYS_CHROOT",
>                 "CAP_SYS_PTRACE",
>                 "CAP_SYS_PACCT",
>                 "CAP_SYS_ADMIN",
>                 "CAP_SYS_BOOT",
>                 "CAP_SYS_NICE",
>                 "CAP_SYS_RESOURCE",
>                 "CAP_SYS_TIME",
>                 "CAP_SYS_TTY_CONFIG",
>                 "CAP_MKNOD",
>                 "CAP_LEASE",
>                 "CAP_AUDIT_WRITE",
>                 "CAP_AUDIT_CONTROL",
>                 "CAP_SETFCAP",
>                 "CAP_MAC_OVERRIDE",
>                 "CAP_MAC_ADMIN",
>                 "CAP_SYSLOG",
>                 "CAP_WAKE_ALARM",
>                 "CAP_BLOCK_SUSPEND",
>                 "CAP_AUDIT_READ",
>                 "CAP_PERFMON",
>                 "CAP_BPF",
>                 "CAP_CHECKPOINT_RESTORE"
>             ]
>         },
>         "oomScoreAdj": 0
>     },
>     "root": {
>         "path": "/var/lib/docker/overlay2/ab8d27d3f9a0369b112c6c69088ef76b09fa5d427570dec5b785e3d98782ad80/merged"
>     },
>     "hostname": "cf4b40b1da85",
>     "mounts": [
>         {
>             "destination": "/proc",
>             "type": "proc",
>             "source": "proc",
>             "options": [
>                 "nosuid",
>                 "noexec",
>                 "nodev"
>             ]
>         },
>         {
>             "destination": "/dev",
>             "type": "tmpfs",
>             "source": "tmpfs",
>             "options": [
>                 "nosuid",
>                 "strictatime",
>                 "mode=755",
>                 "size=65536k"
>             ]
>         },
>         {
>             "destination": "/dev/pts",
>             "type": "devpts",
>             "source": "devpts",
>             "options": [
>                 "nosuid",
>                 "noexec",
>                 "newinstance",
>                 "ptmxmode=0666",
>                 "mode=0620",
>                 "gid=5"
>             ]
>         },
>         {
>             "destination": "/sys",
>             "type": "sysfs",
>             "source": "sysfs",
>             "options": [
>                 "nosuid",
>                 "noexec",
>                 "nodev",
>                 "ro"
>             ]
>         },
>         {
>             "destination": "/sys/fs/cgroup",
>             "type": "cgroup",
>             "source": "cgroup",
>             "options": [
>                 "ro",
>                 "nosuid",
>                 "noexec",
>                 "nodev"
>             ]
>         },
>         {
>             "destination": "/dev/mqueue",
>             "type": "mqueue",
>             "source": "mqueue",
>             "options": [
>                 "nosuid",
>                 "noexec",
>                 "nodev"
>             ]
>         },
>         {
>             "destination": "/dev/shm",
>             "type": "tmpfs",
>             "source": "shm",
>             "options": [
>                 "nosuid",
>                 "noexec",
>                 "nodev",
>                 "mode=1777",
>                 "size=67108864"
>             ]
>         },
>         {
>             "destination": "/etc/resolv.conf",
>             "type": "bind",
>             "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/resolv.conf",
>             "options": [
>                 "rbind",
>                 "rprivate"
>             ]
>         },
>         {
>             "destination": "/etc/hostname",
>             "type": "bind",
>             "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/hostname",
>             "options": [
>                 "rbind",
>                 "rprivate"
>             ]
>         },
>         {
>             "destination": "/etc/hosts",
>             "type": "bind",
>             "source": "/var/lib/docker/containers/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745/hosts",
>             "options": [
>                 "rbind",
>                 "rprivate"
>             ]
>         }
>     ],
>     "hooks": {
>         "prestart": [
>             {
>                 "path": "/proc/200460/exe",
>                 "args": [
>                     "libnetwork-setkey",
>                     "-exec-root=/var/run/docker",
>                     "8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
>                     "e3ee660a43f5"
>                 ]
>             }
>         ],
>         "createRuntime": [
>             {
>                 "path": "/usr/bin/nvidia-container-runtime-hook",
>                 "args": [
>                     "nvidia-container-runtime-hook",
>                     "prestart"
>                 ],
>                 "env": [
>                     "LANG=en_US.UTF-8",
>                     "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin",
>                     "NOTIFY_SOCKET=/run/systemd/notify",
>                     "TMPDIR=/var/lib/docker/tmp"
>                 ]
>             }
>         ],
>         "poststop": [
>             {
>                 "path": "/opt/sitonai/share/agent/sitonai-agent-Linux-x86_64",
>                 "args": [
>                     "sitonai-agent-Linux-x86_64",
>                     "stop_hook"
>                 ],
>                 "env": [
>                     "ContainerID=8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
>                     "REGION_ID=1",
>                     "TASK_ID=cf4b40b1da85",
>                     "Forwarding_Mode=proxy"
>                 ]
>             }
>         ]
>     },
>     "linux": {
>         "sysctl": {
>             "net.ipv4.ip_unprivileged_port_start": "0",
>             "net.ipv4.ping_group_range": "0 2147483647"
>         },
>         "resources": {
>             "devices": [
>                 {
>                     "allow": false,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 5,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 3,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 9,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 8,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 5,
>                     "minor": 0,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 5,
>                     "minor": 1,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": false,
>                     "type": "c",
>                     "major": 10,
>                     "minor": 229,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": false,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 5,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 3,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 9,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 1,
>                     "minor": 8,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 5,
>                     "minor": 0,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": true,
>                     "type": "c",
>                     "major": 5,
>                     "minor": 1,
>                     "access": "rwm"
>                 },
>                 {
>                     "allow": false,
>                     "type": "c",
>                     "major": 10,
>                     "minor": 229,
>                     "access": "rwm"
>                 }
>             ],
>             "memory": {
>                 "disableOOMKiller": false
>             },
>             "blockIO": {}
>         },
>         "cgroupsPath": "/docker/8d80e02bb405153935aafae1eb3aa983790644cb84e8893d400d01f3422f4745",
>         "namespaces": [
>             {
>                 "type": "mount"
>             },
>             {
>                 "type": "network"
>             },
>             {
>                 "type": "uts"
>             },
>             {
>                 "type": "pid"
>             },
>             {
>                 "type": "ipc"
>             }
>         ],
>         "maskedPaths": [
>             "/proc/asound",
>             "/proc/acpi",
>             "/proc/kcore",
>             "/proc/keys",
>             "/proc/latency_stats",
>             "/proc/timer_list",
>             "/proc/timer_stats",
>             "/proc/sched_debug",
>             "/proc/scsi",
>             "/sys/firmware",
>             "/sys/devices/virtual/powercap"
>         ],
>         "readonlyPaths": [
>             "/proc/bus",
>             "/proc/fs",
>             "/proc/irq",
>             "/proc/sys",
>             "/proc/sysrq-trigger"
>         ]
>     }
> }
> config.json has also been updated, but there is still no corresponding cap permission in the container

I think you should update the config.json before the runtime start the container. 
If you change runc, you must update the config.json before https://github.com/opencontainers/runc/blob/main/utils_linux.go#L360
