### ISSUE TITLE
[BUG] docker-ce & iptables discrepancy

### ISSUE THREAD

**Issue by the-hotmann** [moby/moby#48844]
### Description

I use standard Debian (Sid) with docker & docker compose. This automatically installes iptables aswell.
In general this is no problem, and as long as I used `docker compose down && docker compose up -d` everything works fine.
But after a reboot NO container is reachable from outside of the VM (local requests succeed!).

I noticed this after a kernel-update, because I had to reboot to apply it, but I am very confident, it has nothing to do with the kernel itself.
When I run `iptables -t nat -F` everything works again - so I suspected the culprit to be `iptables` or dockers handling of it.

I checked the iptables rules after `docker compose down && docker compose up -d` and the iptables rules after a reboot and compared them:

fresh docker compose up -d (working):

```
# iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 205 packets, 12720 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1572 3244K DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 1572 3244K DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  904 1867K ACCEPT     all  --  *      br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   23  1196 DOCKER     all  --  *      br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0
  645 1377K ACCEPT     all  --  br-755c00b46b0d !br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     udp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.16          udp dpt:69
    0     0 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.16          tcp dpt:80
   23  1196 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.17          tcp dpt:443
    0     0 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.16          tcp dpt:3000
    0     0 ACCEPT     udp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.21          udp dpt:51820

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
  645 1377K DOCKER-ISOLATION-STAGE-2  all  --  br-755c00b46b0d !br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0
 1777 3257K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      br-755c00b46b0d  0.0.0.0/0            0.0.0.0/0
  645 1377K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
 1777 3257K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

reboot (not working):

```
# iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 40 packets, 2588 bytes)
 pkts bytes target     prot opt in     out     source               destination
   40  2588 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   40  2588 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     udp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.15          udp dpt:51820
    0     0 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.24          tcp dpt:443
    0     0 ACCEPT     udp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.20          udp dpt:69
    0     0 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.20          tcp dpt:80
    0     0 ACCEPT     tcp  --  !br-755c00b46b0d br-755c00b46b0d  0.0.0.0/0            172.18.0.20          tcp dpt:3000

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
   40  2588 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
   40  2588 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

And indeed they are different.
I have reproduced the issue (on one VM) several times and the problem ALWAYS occured and always went away with `iptables -t nat -F`.

### Reproduce

1. use Debian SID (latest version of all tools/applications)
2. use a `docker compose` stack.
3. start some services in the stack (with ports mapped out/in)
4. reboot
5. realize problem to connect to any container from outside of the VM
6. use `iptables -t nat -F`
7. check again an see that it works

### Expected behavior

Ofc I expect docker to setup the very same iptables rules after a reboot as after a `docker compose up -d` and everything to work fine.
Setups should be reboot-proof.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 25
  Running: 25
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.6-amd64
 Operating System: Debian GNU/Linux trixie/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.65GiB
 Name: public
 ID: a76ca45b-31a4-4e6b-81cd-a737efb90382
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Additional Info

I discovered this issue today (2024.11.10) but maybe a update the days before caused this.
Since I am on Debian SID I always have the latest version of all packages, so it is likely I am the first to expirience this.
Please look into this, so others do not run into the same issue.

I doubt it, but is it possible it has something to do with this: https://github.com/moby/moby/issues/48815 ?
As this shall be released in v28.x and I have v27.x I think this actually _should_ not affect me and therefore _should_ not have anything to do with this issue.

```
ls -l $(which iptables)
lrwxrwxrwx 1 root root 26  8. Nov 19:13 /usr/sbin/iptables -> /etc/alternatives/iptables
```

```
# iptables -v
iptables v1.8.11 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by the-hotmann** [comment]
Tickets maybe related??

- https://github.com/moby/moby/issues/48664
- https://github.com/moby/moby/issues/48815

**Comment by robmry** [comment]
Hi @the-hotmann - comparing the working/not-working dumps - the order of ACCEPT rules in the DOCKER chain is different but that doesn't matter. In the "before" case you have no rules for `docker0`, I suspect that's because you'd already flushed the filter table without restarting docker engine?

However, after the reboot, there are no rules for a user-defined network in the filter-FORWARD chain. I'm not sure why that would be if the network had been created at that point.

Creation of iptables rules is shown at debug level in the daemon logs. It would be useful to compare those. Could you [enable debug logging](https://docs.docker.com/engine/daemon/logs/#enable-debugging), and capture the logs generated when compose creates the network and containers, for the working and non-working cases?

`iptables -L -v -n` prints the `filter` table, but `iptables -t nat -F` flushes the `nat` table - to display the `nat` table, it's `iptables -nvL -t nat`.

> I doubt it, but is it possible it has something to do with this: https://github.com/moby/moby/issues/48815 ?
> As this shall be released in v28.x and I have v27.x I think this actually should not affect me and therefore should not have anything to do with this issue.

As you say, those changes aren't in a released build yet.

**Comment by the-hotmann** [comment]
@robmry first: thank you for you professional reply, I really appreciate it!

I will provide all the requested info ASAP.
FYI: Now I updated and rebooted 4 other Debian SID (1 is Testing) Servers (Baremetal and VMs) and am expiriencing the very same issue on them.

**Comment by the-hotmann** [comment]
There is one more thing to mention:

I have adopted my Debian Installations to use `netplan.io`: https://github.com/moby/moby/issues/47153#issuecomment-2394112488
But that is about it.

**Comment by robmry** [comment]
> I have adopted my Debian Installations to use `netplan.io`: [#47153 (comment)](https://github.com/moby/moby/issues/47153#issuecomment-2394112488) But that is about it.

Could this be caused by netplan/NetworkManager interfering? ... https://github.com/moby/moby/issues/47153#issuecomment-2394194004

**Comment by the-hotmann** [comment]
> > I have adopted my Debian Installations to use `netplan.io`: [#47153 (comment)](https://github.com/moby/moby/issues/47153#issuecomment-2394112488) But that is about it.
> 
> Could this be caused by netplan/NetworkManager interfering? ... [#47153 (comment)](https://github.com/moby/moby/issues/47153#issuecomment-2394194004)

I dont think it is, because after the switch to netplan I rebooted several times and nothing happened.
This just happened lately. Like 1-3 days ago it must have happened.

But what I have seen:


```
# tail -n 500 /var/log/apt/history.log | grep tables -A1 -B2
Start-Date: 2024-11-09  03:38:46
Commandline: apt full-upgrade -y
Upgrade: libxtables12:amd64 (1.8.10-4+b1, 1.8.11-1), iptables:amd64 (1.8.10-4+b1, 1.8.11-1), libexpat1:amd64 (2.6.3-2, 2.6.4-1), libip4tc2:amd64 (1.8.10-4+b1, 1.8.11-1), libip6tc2:amd64 (1.8.10-4+b1, 1.8.11-1)
End-Date: 2024-11-09  03:38:47
```

Seems like 2 days ago iptables was updated.

**Comment by the-hotmann** [comment]
Maybe it is `iptables` .. https://tracker.debian.org/pkg/iptables
It shows some regressions on the debian tracker.

Also this issue can be reproduced on ALL by debian sid servers. To do so follow this tutorial:

1. install debian
2. add `sid` source lists
3. switch to netplan
4. install docker
5. use `docker compose` to install any container with a exposed port
6. reboot

**Comment by the-hotmann** [comment]
I can confirm: the `Debian Testing` VMs actually do not have the problem/issue.
The only meaningfull thing changed between these is currently `iptables`.
This substantiates the suspicion that the problem is `iptables`.

I will keep this thread updated as soon as there are any news.

**Comment by robmry** [comment]
Ok, thank you! When I get time, I'll try to set up a VM where I can take a closer look too.

**Comment by the-hotmann** [comment]
Maybe someone expirienced as you can also figure out what of the changes might would have caused this:

https://www.netfilter.org/projects/iptables/files/changes-iptables-1.8.11.txt

**Comment by the-hotmann** [comment]
News: 
[2024-11-20] [Accepted iptables 1.8.11-2 (source) into unstable ](https://tracker.debian.org/news/1586677/accepted-iptables-1811-2-source-into-unstable/)(Jeremy Sowden)

Once it is out, I will update iptables to `1.8.11-2` and retest, then report back.

**Comment by the-hotmann** [comment]
`1.8.11-2` fixed the issue for me.
After the update reboots work just fine.

**Comment by robmry** [comment]
@the-hotmann - great! Thank you for spotting this and keeping an eye on it.

**Comment by mbrodala** [comment]
Thank you guys a lot for gathering all the details. I stumbled upon the same issue, no container could reach other containers in the same network anymore. And the fact that there was no response (and e.g. a `Gateway Timeout` in Traefik) led me to believe this may be a firewall issue. Now updating `iptables` to `1.8.11-2` indeed fixed the issue.

**Comment by the-hotmann** [comment]
> Since I am on Debian SID I always have the latest version of all packages, so it is likely I am the first to expirience this.
> Please look into this, so others do not run into the same issue.

Thats why RR/SID Teter are so important. I knew that with me beeing the only one running into this it will be hard to get some help - but that is the price you pay beeing on the bleeding edge ;)

@robmry your welcome :)
@mbrodala yes, since 2 weeks updating the rolling release `Debian SID` would fix the issue, and since today `Debian Testing` received the fix aswell. So if you downgraded from SID to Testing, today it also would be fixed for you.

Related Issues:
- https://github.com/docker/cli/issues/5646
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087210

**Comment by mbrodala** [comment]
@the-hotmann Always with Sid, downgrade is not an option. ;-)

**Comment by thaJeztah** [comment]
It's named Sid for a reason 😅 

https://wiki.debian.org/DebianUnstable

> As with all Debian release names, Sid takes its name from a ToyStory character. In the movie, Sid is the kid next door who breaks his toys and makes nasty creatures of them.
> While other release code names progress in time from being "testing" to being "stable", Sid is forever doomed to being unstable.
