### ISSUE TITLE
br_netfilter module is not loaded by docker

### ISSUE THREAD

**Issue by sshedi** [moby/moby#48948]
### Description

With `docker-27.3.1` `br_netfilter` module is not loaded by default when docker service is started.

The code was removed in https://github.com/moby/moby/commit/db25b0dcd0461802289e962aa0df3abd323d1994;

- https://github.com/moby/moby/pull/48492

And this seems to be a regression.

### Reproduce

1. `docker swarm init --advertise-addr 127.0.0.1:8090`
2. `docker service create --name my_web --replicas 1 --publish 8090:80 nginx`

When the second command is run, I see the below error in journal.

```
Nov 25 13:55:38 ph5dev dockerd[9682]: time="2024-11-25T13:55:38.866243855Z" level=error msg="fatal task error" error="error creating external connectivity network: cannot restrict inter-container communication: ensure that the br_netfilter kernel module is loaded" module=node/agent/taskmanager node.id=ymvxcf846da1w705604iv6mzd service.id=hbhvrkgmqbs7h4evch9c1q7gh task.id=izaubnqj8cnq02le61okgnlmg
```

cc: @robmry 

### Expected behavior

`br_netfilter` module should be loaded when docker service starts and backward compatibility should be maintained.
This was working as expected till `docker-27.2.1`

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Mon Nov 25 13:35:46 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Mon Nov 25 13:36:04 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:       ''
 runc:
  Version:          1.1.14
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        ''
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.118-1.ph5
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.916GiB
 Name: ph5dev
 ID: db2af409-5f08-402a-bb47-a57db13191b8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by sshedi** [comment]
@robmry Thanks for the prompt response.

In `docker-27.2.0`, `br_netfilter` module gets loaded by default during service initialisation but in `docker-27.3.1` it is not getting loaded by default. That is the issue, if I do `modprobe br_netfilter` it will start working but a manual step in the middle means, docker upgrade is introducing a regression. Please correct me if I've misunderstood anything.

I reverted https://github.com/moby/moby/commit/db25b0dcd0461802289e962aa0df3abd323d1994 from `v27.3.1` and things started working as expected.

**Comment by sshedi** [comment]
My understanding of the modprobe of bridge & br_netfilter logic is this.
If `/proc/sys/net/bridge` directory is not present, then `modprobe bridge br_netfilter`.

But there is a catch, if only `bridge` module is loaded, `/proc/sys/net/bridge` will be present and docker will silently ignore `br_netfilter` not being present. IMO, this logic needs some rework.

Content of `/proc/sys/net/bridge` when bridge module is loaded:
```
root@ph5dev [ ~ ]# modprobe bridge

root@ph5dev [ ~ ]# ls /proc/sys/net/bridge
arp_probe  arp_probe_per_packets  arp_probe_src_mac  mac_flap
```

Content of `/proc/sys/net/bridge` when bridge and br_netfilter modules are loaded:
```
root@ph5dev [ ~ ]# modprobe br_netfilter

root@ph5dev [ ~ ]# ls /proc/sys/net/bridge
arp_probe              bridge-nf-call-arptables  bridge-nf-filter-pppoe-tagged  mac_flap
arp_probe_per_packets  bridge-nf-call-ip6tables  bridge-nf-filter-vlan-tagged
arp_probe_src_mac      bridge-nf-call-iptables   bridge-nf-pass-vlan-input-dev
```

So, i think it is better to check for presence of a specific file rather than checking for existence of `/proc/sys/net/bridge` directory alone to be absolutely sure that both modules are loaded.

At this moment, I'm unsure on how this code block to load the module simply getting moved to a different location could cause this behaviour but it is happening somehow. I will try to debug this further.

**Comment by robmry** [comment]
Ah yes - that makes sense, thank you.

The call to load the module will now happen later ... perhaps it previously happened before the bridge module was loaded, so it was working by-chance?

I can look at checking for the specific files. Or, as you already have it figured out, if you'd like to contribute a fix (?) it'd be very welcome.

**Comment by sshedi** [comment]
Sure, I will try. Thank you so much for your time and patience. Appreciate it.

**Comment by robmry** [comment]
All I did was break it! Thank you for spotting the problem and tracking it down.

A `27.4.0` build should ship some time this week. Ideally we'll get a fix in to that but, if not, it can go into a patch release. (I'll try to find out exactly when the deadline is.)

**Comment by sshedi** [comment]
Hi @robmry, thanks for the confirmation. I tried the changes I suggested but the behaviour remained same in `v27.3.0`.
I have made an attempt to solve it (attaching the patch). Can you PTAL? If it looks good to you, I will raise a PR.
If you have other ideas to solve this and raise a PR yourself, I'm fine with it.

[0001-Fix-br_netfilter-module-loading-logic.patch](https://github.com/user-attachments/files/17912918/0001-Fix-br_netfilter-module-loading-logic.patch)

**Comment by robmry** [comment]
Thanks @sshedi ...

If I understand correctly - just adding the check for file `bridge-nf-call-iptables` to `enableBridgeNetFiltering` didn't help, but loading the module during `driver.configure` did?

If so, that's good information ... but it means we haven't quite understood the problem yet. Unfortunately, unconditionally loading the driver in `configure` will reintroduce the original bug, described in https://github.com/moby/moby/pull/48511 ... the idea of that change was to only load `br_netfilter` when needed, because it's enabled when newly loaded and can affect other services.

How are you testing it? Is it with the `swarm init`, `service create` commands in the description? With the port numbers changed?

(I wasn't able to repro yesterday, but had only unloaded `br_netfilter`, not `bridge`. So I'll have another go in a bit.)

**Comment by sshedi** [comment]
> If I understand correctly - just adding the check for file bridge-nf-call-iptables to enableBridgeNetFiltering didn't help, but loading the module during driver.configure did?

That' correct.

I tested it with:
docker swarm init --advertise-addr 127.0.0.1:8090
docker service create --name my_web --replicas 1 --publish 8090:80 nginx

The second command simply gets blocked if br_netfilter module is not loaded.

**Comment by robmry** [comment]
I see, thank you. The first command's `--advertise-addr` specifies the host address/port swarm should use for API access and overlay networking. The second command tells the engine to map from port 8090 on all of the host's addresses, to nginx's port 80 in the container (which includes the localhost address swarm will be trying to use).

So, I'm surprised it works with `br_netfilter` loaded, I'd have expected an error about the port already being in use. I'll experiment with it a bit to try to understand how `br_netfilter` makes a difference, and what it does.

What's the intention of this configuration though? Does it work if you use a different port in one of the commands?

**Comment by sshedi** [comment]
I'm using this in a simple test script of mine but this could lead to a regression in production environments.

**Comment by sshedi** [comment]
Sorry @robmry, my bad. I think I missed something in my initial testing. I'm attaching the updated patch. This works as expected.
Indeed my analysis was correct (loading modules based on file presence for each module).

Please try it at your end once.

[0001-Fix-br_netfilter-module-loading-logic.patch](https://github.com/user-attachments/files/17920095/0001-Fix-br_netfilter-module-loading-logic.patch)

**Comment by robmry** [comment]
Ok, that's good - thank you!

Using the existence of `/proc/sys/net/bridge/` to decide whether `br_netfilter` is loaded seems wrong, and checking for the file instead makes sense.

I'm still a bit mystified though ... I've been testing on Debian because I don't have a PhotonOS host to look at - and presumably that's why I'm seeing different behaviour ...

But, for me, creating a service with a port published to the `--advertise-addr` just doesn't work, the service doesn't start. It doesn't matter whether `br_netfilter` is loaded first. That doesn't seem surprising, but I don't know enough about swarm to point at exactly what'll go wrong when there's only a single node - or how it's working on your machine.

Does your service start (with an unmodified dockerd) if the nginx port is different to `--advertise-addr`'s?

Thank you for raising the PR!
