### ISSUE TITLE
DataPathAddr missing from REST API payload

### ISSUE THREAD

**Issue by cowwoc** [moby/moby#49033]
### Description

https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Swarm/operation/SwarmJoin mentions DataPathAddr on the list of request fields but does not include it in the sample request payload

### Reproduce

See https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Swarm/operation/SwarmJoin

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

**Comment by XxRoloxX** [comment]
Hi @cowwoc, I updated the documentation in  https://github.com/moby/moby/pull/49122 . 
Let me know if this PR meets your expectations.

**Comment by cowwoc** [comment]
@XxRoloxX Once you change the port number to 4789 (which is the default value) it looks good to me.

**Comment by XxRoloxX** [comment]
@cowwoc Thanks for pointing out the issue of the wrong port number. 
Thanks to your comment I found another issue with this PR.

I looked into the DataPathAddr validation and it appears to accept **only interface names or IP addresses (without port numbers).** 

The documentation related to DataPathAddr itself mentions that it is: 

Address or interface to use for data path traffic (format: `<ip|interface>`), for example,  `192.168.1.1`, or an interface,  like `eth0`. If `DataPathAddr` is unspecified, the same address as `AdvertiseAddr` is used.

And here is the code responsible for validation to confirm this:
https://github.com/moby/moby/blob/0d53725a7f8abb0b75961806da252f31155cb813/daemon/cluster/listen_addr.go#L16
https://github.com/moby/moby/blob/0d53725a7f8abb0b75961806da252f31155cb813/daemon/cluster/listen_addr.go#L146

The error returned when validation fails mentions that ports are not allowed for this parameter: 
![Image](https://github.com/user-attachments/assets/be449c0b-3fc9-4985-88fd-917facac59ea)

As far I as understand the default port value you are referencing is mentioned in the `DataPathPort` for `POST /swarm/init` (another endpoint)

**I have removed the port number** from the changes introduced in https://github.com/moby/moby/pull/49122

Please confirm that this change would solve this issue.

Thanks!

**Comment by cowwoc** [comment]
Heh, good point. Yes, the new PR looks good to me! Thank you.
