### ISSUE TITLE
Add option to docker build to output build statistics

### ISSUE THREAD

**Issue by kencochrane** [moby/moby#5473]
It would be really nice to give the option to show the build statistics for a build when it is complete. For example.
- Build time
- CPU usage
- Memory used (Max)
- network usage (in/out)

I know most of this information isn't available at the moment, but it would be nice to show the information we have available to us now. The one that I want/need the most is the Memory used for a build.

We can get the memory used from the build container stats before it is destroyed (in /cgroup/<container>/)  List of available values. https://www.kernel.org/doc/Documentation/cgroups/memory.txt

The hard part about this is that the build process actually has many containers, so we would need to combine the different results into one result, not sure how to do that. 

This is just a rough idea, and we need to figure out a lot of details. If you have some ideas on how to make this better, please let me know.

**Comment by jfrazelle** [comment]
This could extend Docker stats ;)

**Comment by AkihiroSuda** [comment]
This should be discussed in BuildKit repo.

If somebody has a detailed proposal, feel free to open an issue at https://github.com/moby/buildkit/issues
