### ISSUE TITLE
Provide mkimage-debootstrap.sh customizations as an installed Debian package

### ISSUE THREAD

**Issue by olberger** [moby/moby#5523]
Whenever possible, I'd prefer to have a specific Debian package installed inside a Debian image, which would provide the customizations currently made "manually" by mkimage-debootstrap.sh, but which could also be removed, to restore a "standard" debootstrap install.

This way, there could be a way to find with dpkg -S / alternatives how/why things like /usr/sbin/policy-rc.d occurred in the image.

Hope this helps.

**Comment by vdemeester** [comment]
Given the activity on this issues, I'll close it as I think it's either not needed or already done. But if you think otherwise, feel free to discuss it and we'll re-open 😉
