### ISSUE TITLE
Flexible/Pluggable Docker CLI Logic

### ISSUE THREAD

**Issue by zinic** [moby/moby#5648]
### Pluggable Remote Logic

The Docker CLI should allow for pluggable remote methods to abstract away underlying implementation details. This would also allow for the addition of future remote call protocols such as BEAM.
### Pluggable Command Hooks

The Docker CLI should allow for pluggable Before and After hooks to allow for custom logic to occur in concert with the Docker work flow.

**Comment by AkihiroSuda** [comment]
@thaJeztah Is this closable?
Moby allows 3rd parties to build their own CLI with lego blocks.

**Comment by thaJeztah** [comment]
Yes, I think we should close this; part of the goals of "moby" is also to have an automatically generated (bare bones) CLI at some point
