### ISSUE TITLE
Proposal: Self-describing images

### ISSUE THREAD

**Issue by shykes** [moby/moby#6805]
Different Docker users need different "routes" for distributing their images. Possible distribution methods include:
- Publishing images publicly on https://hub.docker.com, for anyone to discover and consume
- Publishing images _privately_ on https://hub.docker.com, for deployment to other machines, or consumption by trusted collaborators
- Storing images on an [open-source registry](https://registry.hub.docker.com/_/registry/), hosted on the local network
- Saving images to the local filesystem, moving them out-of-band (for example to an sealed-off LAN appliance), and loading them back from local filesystem
- Saving images to a static file server such as S3, Swift or equivalent
- Consuming images from a public mirror of the Hub operated by the local network operator
- Consuming images from a "satellite" registry operated by an independent software vendor
- Augmenting all of the above with custom middleware for authentication, caching, federation, peer-to-peer transfer, etc.

Most of these customizations are possible today, but they often degrade the user experience. In some cases, they require unsafe tweaks or even patching of the Docker engine, which is not recommended in production environments and puts interoperability at risk.

We must upgrade Docker's image distribution system to make these customizations not only possible, but easy to configure and use. We must do this while respecting Docker's design philosophy:

1) _Don't break interoperability_. Every container and every image must work predictably on every engine.
2) _Don't break separation of concerns_. Site-specific configuration must not affect application-specific considerations.

We can implement a robust solution in 2 steps.
### 1: separate naming and transport

Currently the name of an image is directly linked to its method of transport:
- If the name is a valid URL, then an https connection to that URL is the sole authorized transport for this image
- If the name is of the form _repo_/_name_, then an https connection to https://registry.hub.docker.com/*<repo>_/_<name>\* is the sole authorized transport for this image
- If the name is of the form _name_, then an https connection to https://registry.hub.docker.com/_/*<name>\* is the sole authorized transport for this image

This breaks separation of concerns. For example, if a sysadmin wants to change the URL at which an internal registry is available, all developers building on top of an image stored in that registry will need to change their Dockerfiles. In this example, we want the sysadmin to be free to change the URL (or other configuration aspects, for example authentication) without affecting the development workflow, and vice-versa.

The solution is to attach an image's name _to its content_, independently of transport. In practice, this means that 1) the image format should be changed to include its name, and 2) how the image was transferred should not influence its name.

Similar to #6802, this requires removing the concept of anonymous images. It should _not_ be possible to designate a filesystem layer (with their random generated IDs) as an image. An image should be defined by the combination of 1) A name (eg. _shykes/myapp_), 2) a tag (eg. _latest_) 3) a json manifest and 4) a filesystem layer.

A strict 1-1 mapping of name to image should be enforced: 2 different names means 2 different images (even if these images are identical in every other way).

**Comment by aknauf** [comment]
+1 for separating image name from registry location.

As an application developer, who works for a large internet company, my ability to adopt docker is limited by the fact that image names and registry locations are tightly coupled.  While I can easily setup an internal docker image repository on development infrastructure, any eventual production deployment of such images would need to be on a more industrial-strength registry, in a different security zone, with a different ip address and dns name.  For that reason, having the registry location hard-coded into the image name creates a problem for me.  That location will inevitably change, possibly multiple times, during the dev lifecycle.  Sure, I can play with hosts files, DNS tricks, etc. to try and work around this issue, but that is adds to the complexity of my solution and makes docker more difficult to adopt.

It is this tight coupling that also creates the possibility of fat-fingering a push (or a pull) to/from an unintended registry.  If my image name and my repository location were separate concepts, then a fat-fingered push/pull would ask my preferred registry for the image and allow for access control implemented on that registry to decide what to do.  Once again it is technically possible to work around this with DNS tricks, or clever proxy magic, but my ability to change corporate network configuration is far more limited than my ability to setup development infrastructure.

**Comment by ginbalin** [comment]
+1 is there any milestone for this? From my point of view it is Docker is almost not usable because of this.

**Comment by LK4D4** [comment]
@thaJeztah @tonistiigi do you think this is still actual?

**Comment by divyangjp** [comment]
+1 This needs to be DONE!

**Comment by faliqulamin** [comment]
+1

**Comment by metaa** [comment]
How about something similar to how some package managers do _namespacing_ or _organizations_?
Some use `@vendor/image`, although that's for namespaces in the _main_ registry.

To preserve backwards compatibility, we could use the `@` to declare a FQDN that holds the desired registry.
An example would be: `@example.com/foo`, or to preserve namespacing, maybe a third segment exclusive to external registries (`@example.com/vendor/image`) could be introduced.

**Comment by thaJeztah** [comment]
I think this work is done, and this ticket ultimately led to the foundation of the OCI (https://opencontainers.org), and OCI specifications;

- The OCI image specification (formalizes images) https://github.com/opencontainers/image-spec
- The OCI distribution specification (formalizes the APIs and formats to distribute images through registries) https://github.com/opencontainers/distribution-spec
- The OCI runtime specification (formalizes how container runtimes must run images) https://github.com/opencontainers/runtime-spec
