### ISSUE TITLE
Have an API for introspection of daemon capabilities

### ISSUE THREAD

**Issue by vbatts** [moby/moby#6889]
As an initial use-case, this would allow `docker images --help` to show the user supported parameters for the --filter flag. Though this API could allow for other similar use-cases.

See some conversation on https://github.com/dotcloud/docker/pull/6162

**Comment by krasi-georgiev** [comment]
@vbatts - is this still ongoing or outdated? I might give it a try

**Comment by vbatts** [comment]
I have no idea if this is an ongoing effort.

**Comment by krasi-georgiev** [comment]
@thaJeztah can you find out if it is ok to work on this ? 
From what I understand we need to add all supported labels for the filter option

**Comment by cpuguy83** [comment]
@krasi-georgiev #26331

**Comment by krasi-georgiev** [comment]
@cpuguy83 isn't this different ?

@vbatts  is talking about [UX] adding all available filter the docker images --help 
so the use know how to use the command 
and #26331 is about getting info from inside a container at runtime.

**Comment by cpuguy83** [comment]
Sorry, was on mobile when I answered this.
Indeed this would be nice.

**Comment by krasi-georgiev** [comment]
it would be interesting to see if I can use the new swagger that generates the api for this as well

https://docs.docker.com/engine/api/v1.25/

**Comment by krasi-georgiev** [comment]
@cpuguy83 - ok I will give it a try

**Comment by cpuguy83** [comment]
Thanks!
If you could put together a proposal for the changes that way you don't spend a lot of time changing an implementation.

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉
