### ISSUE TITLE
Registry Automated Deploy Troubleshooting Doc

### ISSUE THREAD

**Issue by hollietealok** [moby/moby#7253]
After working SaaS tickets for all of ~~one week~~ two weeks, it's become clear that Registry users would benefit from a troubleshooting guide for their automated deploys. I'm gathering common errors that folks run into based on tickets, and will work with Fred to develop this doc.

So far:
- "This image does not belong to the repository" 
- "Failed to clone repository" - often related to submodules in GitHub, which need a DR deploy key. I have a ticket boilerplate for how to add a deploy key to a submodule that I can put here. Also useful: "docker clone --recursive [repo-name]" to test whether the failure to clone is due to a submodule.
- "Specified Dockerfile was not found"
- "Failed to checkout 'master'."
- "[script|process|command] returned error exit status 1"
- "Error removing intermediate container" - doesn't seem to result in a build failure every time, but it startles folks. Need to figure out the reason behind this error. Dustin?

More to come as I work here longer!

**Comment by jfrazelle** [comment]
changed from proposal to improvement bc this would be very nice

**Comment by sahajamit** [comment]
I am struck with this error : "Specified Dockerfile was not found" when trigering the build on docker hub.

**Comment by vdemeester** [comment]
I think it has nothing to do with `moby/moby` anymore. It's more Docker Hub related. Issues related to the Hub should be reported here : https://github.com/docker/hub-feedback 👼
