### ISSUE TITLE
allow `attach` endpoint to consume arbitrary fds

### ISSUE THREAD

**Issue by paultag** [moby/moby#7404]
I want to attach to a process's `fd` that it writes to during runtime that's not stdout or stderr. I can likely attach to it outside of Docker, but that's a bit of a hack.

Can we have support for attaching to arbitrary fds? Seems like we could do this without breaking API

**Comment by thaJeztah** [comment]
closing this one for now, as I haven't seen more interest for this, but we can reopen if things change
