### ISSUE TITLE
Create hard-link between multiple volumes

### ISSUE THREAD

**Issue by fenduru** [moby/moby#7457]
On my host, I have two folders: `/home/media/downloads` and `/home/media/library`. In one container I am running Transmission which has the downloads folder mounted. In a second container, I am running a service that organizes media, and has both the downloads and library folders mounted.

I would like to create a hard link from `/home/media/downloads/myFiLe_with_messy_name` to `/home/media/library/my-file` so I can organize my library, while still allowing Transmission to seed.

The problem is that  when I mount the folders by doing `docker run -v /home/media/downloads:/data/downloads -v /home/media/library:/data/library ...` the container sees those folders as two separate file systems and prevents me from creating a hard link between them.

In reality the files live on the same file system, and should be able to be hard linked. If I was not using docker this would be doable. To work around this, I must run `docker run -v /home/media:/data ...`, and mount the parent folder. This exposes data to the container that it doesn't need, and I am limited to having these host folders be near each other (i.e. siblings).

Is there a way to achieve what I am trying to do?

**Comment by strarsis** [comment]
+1!

**Comment by suneetk92** [comment]
Any update/progress on this issue?

**Comment by thaJeztah** [comment]
This is the way mounts work; every `-v /host/path:/container/path` creates a mount inside the container; hard links don't work between mounts / filesystems (see https://www.cyberciti.biz/tips/why-isnt-it-possible-to-create-hard-links-across-file-system-boundaries.html, https://unix.stackexchange.com/questions/290525/why-are-hard-links-only-valid-within-the-same-filesystem)

This is not something we can support, so I'll close this issue.
