### ISSUE TITLE
Docker should not forcibly make your applications public on the Hub

### ISSUE THREAD

**Issue by benlangfeld** [moby/moby#7940]
## Steps to reproduce
1. Create a new organisation on the public Docker registry with no private repositories. Do not create any repositories.
2. Create a Docker image containing some sensitive data, prefixed with the name of the new organisation.
3. Push the image.
4. Observe as a public repo is silently created and your sensitive data published to the world.
## Proposed new behaviour

`docker push` complains that the repo doesn't exist, offers to create it on your behalf and gives the option of public/private.
## `docker version`

```
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): darwin/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```
## `docker -D info`

```
Containers: 11
Images: 20
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 42
Execution Driver: native-0.2
Kernel Version: 3.16.1-tinycore64
Operating System: Boot2Docker 1.2.0 (TCL 5.3); 3.16.1-config-file : e75396e - Fri Aug 22 06:45:30 UTC 2014
Debug mode (server): true
Debug mode (client): true
Fds: 14
Goroutines: 16
EventsListeners: 0
Init Path: /usr/local/bin/docker
Username: benlangfeld
Registry: [https://index.docker.io/v1/]
```

**Comment by h0h0h0** [comment]
Hello, Curious. Has there been a Dockerfile "speed bump" provided? One that would allow the author of the Dockerfile to reasonably stop users from making a docker image public?  

This is an additional use case (with same function) that speaks more to the user side. If the author of the Dockerfile would want to protect against  novice (re: academics or power users who may not have the tool knowledge) users. These are the users (we were all those users once) who would potentially and accidentally make the image public. 

Has a best practice defense possibly been provided? (sorry if I am off-topic or off-practice).

**Comment by AkihiroSuda** [comment]
The issue is on Docker Hub side, not on Moby.
This should be discussed in https://github.com/docker/hub-feedback
