### ISSUE TITLE
Files with changed contents but identical metadata are not committed

### ISSUE THREAD

**Issue by burke** [moby/moby#8242]
When committing a file with identical metadata in two subsequent layers, the second file's changes are discarded.
### System Configuration

Reproduced on both machines I tested on:
##### Machine 1:
- `docker 1.0.0`
- `--storage-driver=btrfs`
- `ubuntu 14:04`
- `Linux 3.13.0-30-generic #54-Ubuntu SMP Mon Jun 9 22:45:01 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
##### Machine 2:
- `docker 1.2.0`
- `--storage-driver=btrfs`
- `ubuntu 14:04`
- `Linux 3.16.0-031600-generic #201408031935 SMP Sun Aug 3 23:36:11 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
### To reproduce

1) Create files `A` and `B` containing different bytes, but having the following attributes in common:
- bytesize
- mtime (with second granularity; µsecs don't _seem_ to matter)
- mode
- owner/group

2) Write `A` into a container and commit to an image (`iA`).
3) Using the image `iA`, write `B` to the same path and commit the result as `iB`.
4) Run `iB` and print the file. Notice that the contents are the contents from the first layer.
### Minimal reproduction:

``` bash
#!/bin/bash
#
# This script creates two files with identical metadata in two subsequent layers.
# It prints the file as of the second layer, which actually prints the first file.
set -xeuo pipefail

workdir=/tmp/bug-workdir
mkdir "${workdir}"
trap "rm -rf ${workdir}" EXIT

cd "${workdir}"

mkdir p1 p2
cat > p1/go <<GO
#!/bin/bash
cp --archive /stage/file /file

cat > /file <<FILE
This file is from the first image. Its bytesize, mode, owner, and mtime are
identical to the file that should have replaced it in the second image.
....................................................................
FILE

touch -t 201409250000 /file
stat /file
GO

cat > p2/go <<GO
#!/bin/bash
rm -f /file
cp --archive /stage/file /file

cat > /file <<FILE
This file is from the second image. It was copied overtop of the file of the
same name, bytesize, mode, owner, and mtime from the first image.  However, it
is not present when that container is committed as an image.
FILE

touch -t 201409250000 /file
stat /file
GO

chmod a+x p1/go p2/go

docker run --rm=false --cidfile a.cid -a stdout -v "$(pwd)/p1:/stage:ro" --entrypoint=/stage/go ubuntu:14.04
docker commit $(<a.cid) > a.id

docker run --rm=false --cidfile b.cid -a stdout -v "$(pwd)/p2:/stage:ro" --entrypoint=/stage/go $(<a.id)
docker commit $(<b.cid) > b.id

docker run -it --entrypoint=/bin/bash $(<b.id) -c 'cat /file'
```

/cc @graemej @Sirupsen @marc-barry

**Comment by jfrazelle** [comment]
@burke are you still seeing this on the latest version of docker

**Comment by burke** [comment]
I'lll check later this afternoon. I've mucked with our build process to avoid the problem so I'm not sure off the top of my head.

**Comment by burke** [comment]
I just realized I don't actually have any more BTRFS filesystems around to test this out without spending a few hours on it, but looking at the code in `pkg/archive/changes.go` on master, I don't see any evidence of it being fixed.

**Comment by jfrazelle** [comment]
cool don't worry about it

**Comment by icecrime** [comment]
Hi! I believe this was fixed by @tonistiigi in the past few months (we started seeing this with overlay too). I'll close this one, let me know if it's appears again!

**Comment by tonistiigi** [comment]
No, naivediffdriver based drivers do not calculate checksum to find the changeset.

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
