### ISSUE TITLE
Proposal: multitenancy: user specific images and containers

### ISSUE THREAD

**Issue by aigarius** [moby/moby#8310]
Currently on each host system there is only one image and container repository and one list or running containers that de-facto belongs to the root user. This proposal is an exploration of changes required to provide a proper multi-user Docker host environment. Or - what to do when the calling user does not have the 'docker' group.

The prime use case would be multi user hosting - there is one server and multiple users that are allowed to import and run Docker containers. This would also work we in 'Docker as app distribution tool' scenario as a way to allow users to install apps just for themselves.

In such situations would be useful to:
- separately track disk space usage by images and containers of different users, preferably by storing all of that in their home folder
- provide separate views to the list of images and containers to different users
- provide access controls allowing to only control own images and containers
- reducing the run capabilities of the containers so that they do not exceed the capabilities of the user that started the container: file system access, port mapping, process limit controls, ...

**Comment by termie** [comment]
+1

**Comment by jokeyrhyme** [comment]
Seems somewhat related to the security issues discussed here:
http://reventlov.com/advisories/using-the-docker-command-to-root-the-host

**Comment by AkihiroSuda** [comment]
Rootless mode solved this issue https://docs.docker.com/engine/security/rootless/
