### ISSUE TITLE
Proposal: like run -P but bind to the same port, not a random one (ie, -p X:X where X is already exposed)

### ISSUE THREAD

**Issue by mhart** [moby/moby#8449]
As per https://docs.docker.com/reference/run/#expose-incoming-ports

> When using -P, Docker will bind the exposed ports to a random port on the host between 49153 and 65535

I see many cases where people are doing, for example, `run -p 3000:3000` when they already have `EXPOSE 3000` in their Dockerfile. They could have used `-P`, but then they'd need to query for the random port that was bound and potentially update external config files, restart load balancing processes, etc.

It would be great not to have to explicitly specify the port, use the `EXPOSE`d port, and _also_ bind it to the same port instead of a random one that then needs to be queried.

If the port is already in use, then the command could just exit with an error (or just treat it exactly the same as `-p X:X` if it's already bound).

This would be very useful for simple scenarios where people are just replacing containers that are behind a load balancer without needing to update the load balancer's config each time.

**Comment by mhart** [comment]
Any status or comments on this? It's been a while now and I still think it's valid (like I literally parse my Dockerfiles at the moment to figure out the exposed port – but that can only been done if I *have* the Dockerfile where I'm running)

**Comment by aboch** [comment]
@mhart  I think this request makes sense.

Only thing is that there might be cases or automated tools which are now relaying on the fact that `docker run -P` always succeeds and they are fine with the host random port. With this change this would no longer be true (if the port is already taken on the host), and user would need to migrate them to handle the failure and retry with `-p X`.

**Comment by mhart** [comment]
Right – and I actually don't want to change the behaviour of `-P`, it was just an illustration.

Perhaps I should have said I'd like `-p` but without an argument.

Would it be clearer if I changed the title of this issue to that?

**Comment by mhart** [comment]
Or maybe `-p exposed` or `-p EXPOSE` or something – you get my drift.

**Comment by aboch** [comment]
@mhart  Cool, we are on the same page.
It looks like we either need a new flag or modify the semantic of an existing one (empty `-p`). We also need to make sure it fits properly in the remote API.

Given this is a new feature which requires UX discussion, maintainers need to take a look and decide which major release this can be targeted for.

**Comment by mhart** [comment]
@aboch great! thanks for the clarification 👍

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Comment by rixed** [comment]
I don't think this have been implemented already and still think it would make sense. I subscribed to this ticket because I couldn't find this exact option that I needed.

**Comment by Kralizek** [comment]
any chance to resurrect this? just landed on Docker world and I was quite surprised to see that there is a `-P` option but not an equivalent to map all exposed ports to themselves and be able to avoid `-p X:X -p Y:Y -p Z:Z`...
