### ISSUE TITLE
Can't set docker exec working directory

### ISSUE THREAD

**Issue by ndeloof** [moby/moby#8917]
docker run let me set the working directory for the main process
docker exec doesn't offer such an option.

**Comment by mzedeler** [comment]
docker exec *really* should have an option to set which directory in the container, the command is executed from. It is really cumbersome to have to write stuff like `docker exec <container> /bin/bash -c 'cd /somedir/somewhere && some_command that requires "'$a_local_variable'"'`.

**Comment by servel333** [comment]
+1

**Comment by mjdavies** [comment]
+1

**Comment by tmds** [comment]
+1
https://issues.jenkins-ci.org/browse/JENKINS-33510

**Comment by ndeloof** [comment]
@tmds did you tried [docker-slaves](https://wiki.jenkins-ci.org/display/JENKINS/Docker+Slaves+Plugin) ?

**Comment by igustafson** [comment]
+1

**Comment by irishkurisu** [comment]
+1

**Comment by servel333** [comment]
Please reopen this issue @ndeloof. It looks like a lot of people want this feature!

**Comment by ndeloof** [comment]
@servel333 this conflicts with roadmap decision https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec

**Comment by servel333** [comment]
Ok, thanks for the clarification. I assume you mean this:

> # 2.1 Docker exec
> We won't accept patches expanding the surface of docker exec, which we intend to keep as a debugging feature, as well as being strongly dependent on the Runtime ingredient effort.

Do you happen to know the reasoning for this decision? Is there a different tool that is in planning? Why freeze it?

**Comment by mzedeler** [comment]
@ndeloof - I'd really like to know as well.

The `exec` command is just not feature complete as it is now.

Not having an option to specify the working directory is a pain.

I think that the overall direction of docker is wrong. There is too much focus on all the enterprisey stuff and not enough effort in making the core tools work.

**Comment by ojhaujjwal** [comment]
+1 this feature is needed

**Comment by akwiatek** [comment]
+1

**Comment by jaryroxas** [comment]
+1

**Comment by servel333** [comment]
@ndeloof Ok, thanks for the clarification.

> # 2.1 Docker exec
> 
> We won't accept patches expanding the surface of docker exec, which we intend to keep as a debugging feature, as well as being strongly dependent on the Runtime ingredient effort.
- https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec

Do you happen to know the reasoning for this decision? Is there a different tool that is in planning? Why freeze it?

It seems like there is interest in this feature, significant interest. Can we please get more clarification?

**Comment by ndeloof** [comment]
I guess "_we intend to keep as a debugging feature_" is enough as an explanation. There's some use-case that would benefit additional features to `exec` but this isn't part of project roadmap.

**Comment by servel333** [comment]
That doesn't really address the issue. The reason I want to set the path in an exec is to use it in debugging situations, and I'd be willing to guess that others want it for this reason too. Keeping a tool as a "debugging feature" is not a good reason to freeze a feature, in my opinion. Maybe there is a reason to freeze this tool, but it's not stated in that document that I can tell and not clear to me.

**Comment by geerlingguy** [comment]
+1 (sorry to keep beating a dead horse in this issue); I probably end up doing the hacky `/bin/bash -c 'cd /some/folder && command'` a few times a day when I'm building and debugging Docker images.

**Comment by rickshawhobo** [comment]
Whoa wait, docker exec is a debugging feature? I use it to change the state of my container before committing it and pushing it for deploys. I agree a "-w" feature similar to docker run would be useful.

**Comment by bmeeder22** [comment]
+1

**Comment by mgsomeone** [comment]
docker exec -it containerName sh -c "cd /var/www && /bin/bash"

**Comment by ndeloof** [comment]
there's for sure some workaround, but that's stupid one can do this with `runc` but not `docker` CLI

**Comment by cadavre** [comment]
+1.

**Comment by TomCan** [comment]
+1
Using run to execute multiple commands is also slower than attaching to a running container as it needs to create/destroy the containers.

**Comment by JRice** [comment]
This certainly feels like a missing feature, despite the workaround. There's certainly a clear use-case for it, and there's clearly demand for it.

**Comment by NevesLucas** [comment]
+1

**Comment by taylorday** [comment]
+1

**Comment by ndeloof** [comment]
`runc` fully support setting process current directory when running additional process, so I don't see any reason this isn't exposed to docker API / CLI as well.
(by the way this is a major issue for Jenkins' docker pipeline support)

**Comment by thaJeztah** [comment]
@ndeloof we've been discussing this in the maintainers meeting, and are ok with adding a `--workdir` flag to `docker exec`. Would you be interested in implementing it?

**Comment by ndeloof** [comment]
@thaJeztah for sure !

**Comment by ndeloof** [comment]
https://github.com/moby/moby/pull/35661

**Comment by steve-todorov** [comment]
@thaJeztah, @ndeloof that's awesome news and I'm really happy to hear it! This missing feature has made our Jenkins pipeline extremely complicated and full of "hacks" just because we can't change the working directory of Jenkins in a docker container. ([JENKINS-33510](https://issues.jenkins-ci.org/browse/JENKINS-33510))

**Comment by thaJeztah** [comment]
This is now implemented through https://github.com/moby/moby/pull/35661 and https://github.com/docker/cli/pull/732, which are on "master" and will be included in the upcoming Docker 17.12 release

**Comment by isometriq** [comment]
why not also on `docker-compose` ?

**Comment by thaJeztah** [comment]
Docker compose is a separate project; you can open a feature request over there; https://github.com/docker/compose/issues
