### ISSUE TITLE
Feature request: -v and --privileged options for 'docker start'

### ISSUE THREAD

**Issue by RoelVdP** [moby/moby#9343]
Currently, one can specify --privileged and/or -v (volumes) for 'docker run'. It would be great if these options were also available for 'docker start'.

This would allow one to attach new volumes or 'host directories' to an already existing container.

I searched the manual, but if I missed any option which already allows doing this, I apologize. Please let me know.

**Comment by cpuguy83** [comment]
Hi, this can be done through the API but is not supported via the CLI... I'm not sure of the reasoning behind this.

I think ideally we would not support it on the API either.

**Comment by RoelVdP** [comment]
@cpuguy83  Thanks for commenting Brian, but - why not? i.e. would it not be great to allow one to attach new volumes/host directories to an already existing container?

**Comment by thaJeztah** [comment]
Closing this one, as passing hostconfig at container start was deprecated in https://github.com/moby/moby/pull/22570
