### ISSUE TITLE
Implement 'not-pushed' filter on 'docker images -f'

### ISSUE THREAD

**Issue by fbueno** [moby/moby#9590]
It would be nice if "docker images -f" could also filter by images that were not pushed to the repository after its creation whether by commit, build or import / load.

``` sh
docker images -f 'not-pushed=true'
```

**Comment by jfrazelle** [comment]
This would be pretty hard to define, but a proper set of what means what would help

**Comment by vdemeester** [comment]
Given the inactivity and the fact that we don't really have any knowledge of this information (i.e. pushed or not), I'm gonna close this feature request. If you think it still need discussion, feel free to comment on the issue 😉
