### ISSUE TITLE
Proposal: allow for multi-inspect of images and containers through remote-api

### ISSUE THREAD

**Issue by cdancy** [moby/moby#9596]
Currently we can only inspect a single image or container. It would be great as part of the listing of all images or containers to be able to specify a parameter, something like '/images/json?inspect=true' which will return all images/containers in their 'inspected format' instead of the summary we get now. Thoughts?

**Comment by duglin** [comment]
ping @crosbymichael - is there any reason why we don't just return the full json for each image?
If we're concerned about performance for `docker images -a` and we want to keep this summary form, I think what @cdancy suggests make sense but I would rename it to `?full=true` instead.
Thoughts?

**Comment by thaJeztah** [comment]
ping @icecrime @crosbymichael ^^ https://github.com/docker/docker/issues/9596#issuecomment-121427605

**Comment by cdancy** [comment]
Closing as there does not seem to be much talk going on around this area.

**Comment by thaJeztah** [comment]
I think the main reason is that the `/images/json` and `/containers/json` only return information that's actually needed for the endpoint.


Having said the above, while the API doesn't have an option to inspect all containers/images at once, it is possible by combining some commands, e.g.;

```
docker image ls -aq | xargs docker image inspect
```

**Comment by cdancy** [comment]
@thaJeztah that makes sense it would just be nice to have a paged version of these like other restful api's do is all.

**Comment by thaJeztah** [comment]
Yes, pagination has definitely been discussed a couple of times (possibly using a [graphql](http://graphql.org) API), but there's a lot of work involved in that, and I don't think anyone had the bandwidth to turn that into reality 😅

**Comment by cdancy** [comment]
@thaJeztah that would be very nice indeed :)
