### ISSUE TITLE
update docs for volumes

### ISSUE THREAD

**Issue by yaronr** [moby/moby#9929]
Hi

Here's a transcript from a chat I had (with one of your employees?) a few minutes ago, that describes everything:

yaronr: Strange. After bind-mounting a file, it changes to be a directory. removing the -v - and the file is a file again..
yaronr: has anyone seen this?
erikh: it's a known issue
yaronr: erikh: really ?! I've spent hours on it
yaronr:it used to work.
erikh: when?
yaronr: up until a couple of weeks ago. I have this unit file that uses this approach to map a config file from the host to the container
yaronr: erikh: I actually have a few of them..
erikh: what version of docker were you using before?
yaronr: 1.3.x
erikh: and it doesn't work in 1.4 now?
erikh: put in an issue
yaronr: yup
erikh: I swear it never worked this way though
yaronr: I'm pretty sure there even was an example for mounting specific files, in the docs.
yaronr: erikh: you said it's a known issue - what do you mean?
erikh: well, then definitely put in an issue :)
erikh: I swear that we didn't support this
erikh: but I could be wrong
erikh: other people know that code better than me, like cpuguy83
erikh: but I think he's at lunch
yaronr: erikh: AHA, it IS (or should be) supported, read the docs: https://docs.docker.com/userguide/dockervolumes/  'Mount a Host File as a Data Volume'
yaronr
erikh: don't swear so quickly ;)
yaronr: so I guess what you're saying is that you think something has changed in this area?
yaronr: this explains why one day, a bunch of my unit files stopped responding..
yaronr: ping?

**Comment by cpuguy83** [comment]
@yaronr Can you provide a script to reproduce?

**Comment by yaronr** [comment]
Hi there @cpuguy83 

Ok I think I understand what the problem is.
My image (yaronr/softether) creates a config file, and I used to mount it the following way: -v ${SYNC_DATA_DIR}/${CLUSTER_NAME}/vpn_server.config:/usr/local/vpnserver/vpn_server.config

However, the first time I run the image, the config file does not yet exist.
Docker doesn't know that  vpn_server.config is a file (since it doesn't exist), and creates a directory.
Later, when the application within the image tries to create the file, it doesn't fail (I don't know why), and the actual config file just evaporates.

So I guess (see below) bind mounting an EXISTING file from the host, works.
HOWEVER :)  bind mounting an existing file on the container, that does not exist on the host, does NOT work (see below). Am I wrong to expect it to work? 

Maybe there should be an operand that defines precedence, like:
-v /test/a.b:>/tmp/test/a.b  (host to container)
-v /test/a.b<:/tmp/test/a.b (container to host)
-vf /test/a.b:>/tmp/test/a.v (host to container, FILE)
-vd /test/a.b:>/tmp/test/a.v (host to container, DIR (default))
and
-v /test/a.b:/tmp/test/a.b (host to container, dir or file, if it doesn't exist assume dir)

core@ip-10-0-5-226 /tmp $ docker run -ti --name test -v /tmp/tmp.tmp:/tmp/tmp.tmp  yaronr/debian-wheezy bash
root@ed7274fc03a6:/# cd /tmp
root@ed7274fc03a6:/tmp# ls
tmp.tmp
root@ed7274fc03a6:/tmp# cat tmp.tmp
cat: tmp.tmp: Is a directory
root@ed7274fc03a6:/tmp# ls -la
total 0
drwxrwxrwt 1 root root  14 Jan  7 09:17 .
drwxr-xr-x 1 root root 188 Jan  7 09:17 ..
drwxr-xr-x 2 root root  40 Jan  7 09:17 tmp.tmp
root@ed7274fc03a6:/tmp# 

core@ip-10-0-5-226 /tmp $ docker rm test
test
core@ip-10-0-5-226 /tmp $ docker run -ti --name test -v /tmp/tmp.tmp:/tmp/tmp.tmp  yaronr/debian-wheezy bash
root@fdfcc8490925:/# cd /tmp
root@fdfcc8490925:/tmp# ls
tmp.tmp
root@fdfcc8490925:/tmp# ls -las
total 0
0 drwxrwxrwt 1 root root  14 Jan  7 09:19 .
0 drwxr-xr-x 1 root root 188 Jan  7 09:19 ..
0 -rw-r--r-- 1  500  500   0 Jan  7 09:19 tmp.tmp

core@ip-10-0-5-226 /tmp $ docker run -ti --name test -v /tmp/dpkg:/usr/bin/dpkg  yaronr/debian-wheezy bash
FATA[0000] Error response from daemon: Cannot start container 745799edb40fd09c82722fc8237ddc60cfe1a274844b184f5f438ab97ba29e7a: setup mount namespace mounting /tmp/dpkg into /var/lib/docker/btrfs/subvolumes/745799edb40fd09c82722fc8237ddc60cfe1a274844b184f5f438ab97ba29e7a/usr/bin/dpkg not a directory

**Comment by cpuguy83** [comment]
Today Docker never bind-mounts files from inside the container to the outside.  The closest thing to that would be in a normal `-v /foo` volume, the contents of `/foo` are copied into the new volume on the host for convenience.

If you'd like to be able to bind-mount a file out of a container (as opposed to the current way which is only to bind-mount into the container), please open a PR with the proposed changes to the docs and prefix the title with `Proposal: `

I think this can be closed.

**Comment by yaronr** [comment]
@cpuguy83 
I think that the documentation needs to be updated to clarify exactly what Docker does today (e.g - Host to Container, and what you've explained above), and specifically specify what Docker does in case a mapped file does not exist.

**Comment by cpuguy83** [comment]
@yaronr PR's are welcome :) all docs are in this repo under "docs"

**Comment by cpuguy83** [comment]
cc @SvenDowideit because I know he wanted some better volume docs.

**Comment by thaJeztah** [comment]
@cpuguy83 roughly relates to https://github.com/docker/docker/pull/9092 ? (But in stead of for directories, for single files?)

**Comment by cpuguy83** [comment]
@thaJeztah Yep, kinda I suppose. Single files won't work in terms of copying out, but I could see a proposal that would bind-mount files from the container to the host.

**Comment by frntn** [comment]
I had a similar issue. Posting how I resolved it here so it may someone in the future.

I was supposed to : 

1. send my config file on remote host
2. start a container on that remote host with a file volume `-v /data/etc/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg` 

Simple. But...

On the first run the file hadn't been copied to remote host (I don't know how/why..)
So docker create an empty folder `/data/etc/haproxy/haproxy.cfg` on the host
Then each time I rerun my script, the file was copied inside this folder and the actual file path was `/data/etc/haproxy/haproxy.cfg/haproxy.cfg`

I lost quite some time to figure it out *"because"* of the ls ouput
```bash
$ ls -l /data/etc/haproxy/haproxy.cfg               # <-- this is a folder
total 0
-rw-rw-r-- 1 ekino ekino 0 Mar 30 02:27 haproxy.cfg # <-- this is the file inside the folder
```
So each time I check for the file with `ls` I thought everything was ok, while it was not : 
```bash
$ [ -f /data/etc/haproxy/haproxy.cfg ] && echo "file exists" || echo "file is missing"
file is missing
```

Finally error the message from docker was quite relevant : he cannot mount a directory (host level) to a file (container level).
I remove the folder and all its content with `rm -rf /data/etc/haproxy/haproxy.cfg`, rerun my script and **everything was ok this time** !

Hope this will help someone someday... somehow :)

**Comment by kennethlimcp** [comment]
I see that the current docs mention this at the beginning:

```
The -v flag can also be used to mount a single file - instead of just directories - from the host machine.
```

That sort of mentions but we can probably improve it with:

```
The -v flag can also be used to mount a single file - instead of just directories - from the host machine.

The file will be copied from the host machine to the container it is spun up.
```

As for the issue with file name becoming a directory, i am unable to reproduce this with:

- `docker build -t test .`
- `docker run -v ~/desktop/docker-vol-test/example.md:/example/example.md test:latest ls -la`

Dockerfile:

```
FROM ubuntu:14.04

WORKDIR /example

RUN ls -la
```

**Comment by yaronr** [comment]
@GordonTheTurtle to be truthful, I haven't used Docker in a long while.
But please check if the documentation has been updated. If so, close the issue.
If not, update the doc, and then close the issue ;)

**Comment by lewisdaly** [comment]
As @GordonTheTurtle is a turtle, I had a look to see if this documentation has changed. It appears to be in the docs repo now `engine/tutorials/dockervolumes.md`, but doesn't have any of  @yaronr 's proposed changes above.

I'm happy to look at this one - @thaJeztah @cpuguy83 has any of this behaviour changed (that you know of) in the last year? Or are the above changes still valid?

**Comment by thaJeztah** [comment]
Closing as this went stale, and docs around this now live in the https://github.com/docker/docs repository
