### ISSUE TITLE
`docker cp` should support Windows OS filesystem paths with drive specifiers (`C:\`)

### ISSUE THREAD

**Issue by jlhawn** [moby/moby#9932]
`docker cp` currently uses a `:` character to separate a container ID from a path, similar to how `scp` uses a `:` between a remote host and path. Since absolute paths in Windows OS always have a `:` we need a different way to disambiguate whether the argument has a container ID or not.

related to #9871

**Comment by cpuguy83** [comment]
What if this was handled in the Windows client to convert to a Unix-y notation?  I _think_ you can access paths on Windows that way.

**Comment by tianon** [comment]
> `\` (relative to %CD%)
> or `[drive_letter]:\`
> or `\\[server]\[sharename]\`
> or `\\?\[drive_spec]:\`
> or `\\?\[server]\[sharename]\`
> or `\\?\UNC\[server]\[sharename]\`
> or `\\.\[physical_device]\`
from https://en.wikipedia.org/wiki/Path_%28computing%29

Also: https://en.wikipedia.org/wiki/Path_%28computing%29#UNC_in_Windows
> UNC stands for Universal Naming Convention.
>
> Windows Command Prompt does not support having a UNC path as the current directory, so CD \\host\directoryname does not work. If an attempt is made to start CMD with a UNC current directory then it forces it to C:\Windows. It does not appear to be possible to determine the original working directory.

**Comment by jlhawn** [comment]
wait, @cpuguy83 does the windows client have a separate source repository? Is there a way to handle this without an `if/else` case looking at `runtime.GOOS`?

**Comment by tianon** [comment]
We could use `filepath.ListSeparator`: http://golang.org/pkg/path/filepath/#pkg-constants

This would mean that it's `:` on Unix platforms, but `;` on Windows platforms.

**Comment by jfrazelle** [comment]
pretty sure the windows guys know about this, its part of what they are working on to get jenkins to pass unsure if we should close or not but its a known issue its why the windows client is currently unsupported

**Comment by jfrazelle** [comment]
i added the label, im content lol

**Comment by DoraALin** [comment]
Would like to take this task. Like what @tianon commented, separator in cp.go could be replaced with os.PathListSeparator in filepath.
And I am wondering if there is another task needed for associated modification about separator in docs.
#dibs

**Comment by rudes** [comment]
How about if the character before the ':' is only a single letter than it's a windows path otherwise it's a container ID?

```go
if len(parts[0]) == 1 && !strings.HasPrefix(parts[0], ".") {
      // Windows Drive Letter
} else {
      // Container
}
```

Which is sort of what is being done [here](https://github.com/docker/docker/blob/master/cli/command/container/cp.go#L296-L300).

**Comment by broder** [comment]
Unless I'm missing something, I think this issue should be covered by https://github.com/docker/docker/blob/master/cli/command/container/cp.go#L289.

Can anyone confirm that this the case? If it is still a problem, I'd be happy to look into fixing this.

**Comment by thaJeztah** [comment]
This ticket is very old now, and if this is still an issue probably needs to be addressed in the CLI repository (https://github.com/docker/cli), so let me close this here.
