### ISSUE TITLE
`docker commit' Driver btrfs failed to create image rootfs

### ISSUE THREAD

**Issue by gdm85** [moby/moby#9997]
# Problem

I have a container that cannot be committed; I tried when it was running, and also now that it's stopped, still failing with same error:

```
FATA[0018] Error response from daemon: Driver btrfs failed to create image rootfs 11857348c457a545c5c0756414b644ff0b921b191561d3126d8d69d33b3a7a04: stat /var/lib/docker/btrfs/subvolumes/2a5f6bc606ad782bb84b36bfcca78f304db8d1a551e182cda6fd61b6f6624be5: no such file or directory
```
# Context information

On this host images are aggressively attempted to be removed every night, e.g. I attempt to remove all intermediate images.

A command like: `docker ps -a -q | xargs docker rmi --force=true`
# Root cause?

Is it possible that docker glitched and removed some subvolume that was necessary? May I assume that when this happens, containers will operate in inconsistent state?

Please connect with other relevant issues, I couldn't find any.
# Host information

docker info:

```
Containers: 75
Images: 1402
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 18
Total Memory: 23.53 GiB
Name: masterblaster
ID: CAYV:JZX2:LRRO:OK2D:XF2U:XZRZ:AUK5:22HE:TTVY:2RE6:IHF3:QZQI
Debug mode (server): true
Debug mode (client): false
Fds: 481
Goroutines: 352
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
```

docker version:

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by Fandekasp** [comment]
@gdm85 I'm facing a similar issue. Have you fixed this issue ? How did you proceed ?

**Comment by gdm85** [comment]
@Fandekasp nope, eventually I have removed that inconsistent container. But I expect it to happen again since it is a bug somewhere in Docker or btrfs.

**Comment by unclejack** [comment]
@gdm85 This is most likely a btrfs bug. The Docker btrfs code is running just fine for me and I haven't seen such an error at all.

**Comment by gdm85** [comment]
@unclejack ok, so the impact would be that in yet-to-be-determined conditions btrfs can "forget" about a container? scary :\

time to prep up for overlay :)

I will post again here if I see this again and/or have more information; meanwhile, you can either leave it open to gather more input (as issue is not really understood/fixed/addressed) or close it, as nobody is actively working on a fix for it. Your pick.

**Comment by gdm85** [comment]
I have today received this error again, with two containers. Right after a ``docker stop``, I cannot commit them.

I think it really happens because - overnight - I aggressively purge images and intermediate layers that are not used, although one would not expect that a necessary layer will get discarded this way.

If it's an issue internal to btrfs subvolume dependencies, maybe Docker should be aware of it in its storage driver?

**Comment by balboah** [comment]
I've experienced this issue as well on CoreOS with "Docker version 1.5.0, build a8a31ef-dirty".
This occurs when I'm doing multiple docker loads at the same time on an Amazon instance that has the slow default ELB making it having to wait for IO to complete. It seems somewhere this causes layers to disappear into cyberspace resulting in the same "no such file" error as mentioned above.

**Comment by JoeOrtiz** [comment]
Showing the same issue with 1.6:

core@ip-10-171-50-193 ~ $ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64


Going to try to switch away from btrfs to see if the issue happens again.

**Comment by GeertJohan** [comment]
I also see this happening when two services try to pull the same dependency layers.
The pull action writes to the log: `Layer already being pulled by another client. Waiting.`, but it looks like docker doesn't wait. Because the other btrfs layers are pulled and docker continues to try to create the container, which causes the error `Error response from daemon: Driver btrfs failed to create image rootfs <hash> : stat /var/lib/docker/btrfs/subvolumes/<hash>: no such file or directory`.

This happens a dozen of times in just a  few seconds because I have Restart=always in my systemd service. Another sign that docker doesn't wait for the layer to be pulled. If it had waited it shouldn't state that the layer is being pulled a second time.

**Comment by aaron42net** [comment]
This looks like a race condition in docker 1.6.2's pull.  I have a simplified test case and steps to reproduce here: https://github.com/aaron42net/dockertest

**Comment by carmstrong** [comment]
> This looks like a race condition in docker 1.6.2's pull.

We're seeing this cause major problems and instability issues for Deis, causing us to consider reverting to the ancient Docker 1.5. Can we please get a response from the Docker team on this?

**Comment by cpuguy83** [comment]
I would suggest trying with either master or the experimental release which has a fix for some race issues.

**Comment by e-max** [comment]
I've tried latest master v.1.9.0 and experienced "Driver btrfs failed to create image rootfs"  problem. It happened when I tried massive parallel 'docker pull'

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, but feel free to comment, or to open a new ticket with details if this is still an issue.
